### ISSUE TITLE
定时任务更新数据，选择参数后保存报错

### ISSUE THREAD

**Issue by plateauandsp** [dataease/dataease#10]
定时任务更新数据，选择参数后保存报错。这边按照官方文档，需要手动写SQL，感觉不合理
![image](https://user-images.githubusercontent.com/30932762/123370547-8825b680-d5b2-11eb-995c-4685f8d99423.png)

**Comment by xuwei-fit2cloud** [comment]
增量更新使用方式错误，我们会改进增量同步的使用体验。
