### ISSUE TITLE
[Bug]柱线组合图修改指标显示名称，横轴下方的显示名称显示无变化

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#10009]
**DataEase 版本**
2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
离线安装包

**浏览器版本**
最新版

**Bug 描述**
柱线组合图修改指标显示名称，横轴下方的显示名称显示无变化

**Bug 重现步骤(有截图更好)**
![9f0530593650b8c9d5e18f114516dd5](https://github.com/dataease/dataease/assets/43403764/b86047a8-dca1-472f-92a3-ed14d4fbe627)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本修复；

**Comment by maninhill** [comment]
v2.10-lts 版本已经发布，请在最新版本上面验证，有问题请 re-open。
