### ISSUE TITLE
[Bug]动态排序图无法过滤空数据

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#10002]
**DataEase 版本**
v1.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
动态排序图无法过滤空数据

**Bug 重现步骤(有截图更好)**
1.设置过滤条件不显示空字符串和不为空
2.图表中依旧显示空数据
![image](https://github.com/dataease/dataease/assets/133861755/1694098c-9372-4252-a15d-631ce485c27c)
![image](https://github.com/dataease/dataease/assets/133861755/c8856313-a5f5-4bdf-8c71-448bf99a4f62)

**Comment by BBchicken-9527** [comment]
感谢反馈，你过滤地区非空是图表显示是没问题的，因为地区这个字段是有值的；
