### ISSUE TITLE
v2.8 仪表板在上方多tab显示-方便一个窗口不同报表的切换[Feature]

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#10006]
DataEase 版本: V2.8

![image](https://github.com/dataease/dataease/assets/30259184/a7cbfed4-26b4-4fed-b73f-2ce6421b99c1)
上图为 quickBi现在的样式， 我在不同报表直接切换非常方便，不用去来回切换页面。 一个页面可以打开多个报表.
且重新打开不用再去 查询后台.

![image](https://github.com/dataease/dataease/assets/30259184/0c5dd39a-3dad-43dc-a12a-de118dfa68d6)
下图为目前 dataease的改进方法。 麻烦看看。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈和建议，目前保持当前的设计，近期没有计划去修改。
