### ISSUE TITLE
V1.18.19 新增Oracle 19c production 19.3.0.0数据源驱动提示当前版本不支持

### ISSUE THREAD

**Issue by Sky-shang** [dataease/dataease#10001]
**请描述您的问题.**
增加Oracle驱动使用ojdbc8-19.3.0.0.jar，提示当前版本驱动不支持
![image](https://github.com/dataease/dataease/assets/29321889/12ec4719-500a-4a22-90b3-c4fdaa88baf9)

**Comment by yayanpei-fit2cloud** [comment]
下图所示的位置，需要写上jar包所支持数据库的大版本号，您试试看。
![image](https://github.com/dataease/dataease/assets/84168063/7ce09abb-d754-4fca-9331-41e720fd2891)

**Comment by Sky-shang** [comment]
可以使用。感谢@

> 下图所示的位置，需要写上jar包所支持数据库的大版本号，您试试看。 ![image](https://private-user-images.githubusercontent.com/84168063/335517695-7ce09abb-d754-4fca-9331-41e720fd2891.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNDgyNjAsIm5iZiI6MTcxNzE0Nzk2MCwicGF0aCI6Ii84NDE2ODA2My8zMzU1MTc2OTUtN2NlMDlhYmItZDc1NC00ZmNhLTkzMzEtNDFlNzIwZmQyODkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA5MzI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MDRiOGZjZTViYmJiZTc4ODllOWYxMTJhOTliYTI1ODNmNTYzZjZjNDMyNjBmZWI5MGYwZWRkMjQyZTRhMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BPO6izwmEpaDVnDcTibLtzekCsqqqN5ZalA3Xv9K5F4)

按照你的方式操作，可以使用。非常感谢！
