### ISSUE TITLE
[Bug]v1.18.19 日期组件在移动端会挤在一起，在配置移动端的时候显示正常。

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#10000]
![image](https://github.com/dataease/dataease/assets/141667200/a0ec6d79-85b7-443c-83c0-3c7bd8bf95c9)
![image](https://github.com/dataease/dataease/assets/141667200/010f7506-d21f-4920-a961-7d70b964d126)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
