### ISSUE TITLE
[Bug]sql数据集中带有注释时，执行、保存均成功，数据预览异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#10018]
**DataEase 版本**
2.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
<img width="1472" alt="image" src="https://github.com/dataease/dataease/assets/89771514/47ccc21a-041f-4543-9182-58878ee2e40b">

<img width="1460" alt="image" src="https://github.com/dataease/dataease/assets/89771514/e7fba194-53f6-401a-acc5-1fb5f627c6a6">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前暂时不支持注释的留存；
