### ISSUE TITLE
[Bug]MySQL数据源，sql数据集使用with as语法执行异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#10017]
**DataEase 版本**
2.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
<img width="1475" alt="image" src="https://github.com/dataease/dataease/assets/89771514/b6e16880-77aa-4a7a-8752-ad4691d8d531">
<img width="1296" alt="image" src="https://github.com/dataease/dataease/assets/89771514/b07f156d-d300-44bc-99d3-1ea81b44263f">

<img width="775" alt="image" src="https://github.com/dataease/dataease/assets/89771514/8a322f9b-d7a0-4e85-bc6b-e82d7bb0dd6c">

异常sql:

WITH a AS ( SELECT account, `name` FROM per_user ),
b AS( SELECT account, email FROM per_user )
select a.*,b.email from a join  b ON a.account = b.account

**Comment by BBchicken-9527** [comment]
感谢反馈，目前单数据源为jdbc方式连接与客户端是存在出入的，建议遵守sql的规范；
