### ISSUE TITLE
[Feature] API 数据源同步数据时是否可以自定义保留小数位

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#10012]
DataEase 版本:
v2.6.1（安装包安装）

**请描述您的需求或者改进建议.**
API 数据源同步数据时，默认保留三位小时，是否可以全量显示或者支持自定义保留小数位。
原因：银行、证劵对数据保留小数位特别敏感，默认保留三位小数不能满足实际业务需求。

![image](https://github.com/dataease/dataease/assets/43403764/c61f4d8a-8d32-41eb-847d-fa01974ebaa3)

**Comment by xuwei-fit2cloud** [comment]
看您截图里的API应该是新浪股票接口，例如：
http://money.finance.sina.com.cn/quotes_service/api/json_v2.php/CN_MarketData.getKLineData?symbol=sz002095&scale=60&ma=no&datalen=1023

这个接口返回的几个数值字段确实就是3位小数，并不是我们有特殊处理。

**Comment by xuwei-fit2cloud** [comment]
由于长时间无反馈，暂时先关闭该问题。如还有其他信息补充，请再次打开此问题。
