### ISSUE TITLE
[Feature]希望数据集中新增计算字段能够在关联数据集时使用，能够在sql数据集的sql语句中使用。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#10014]
DataEase 版本:
V2.6.0

**请描述您的需求或者改进建议.**
希望数据集中新增计算字段能够在关联数据集时使用，能够在sql数据集的sql语句中使用。
![636a5017c814eae21290d9bd8948851](https://github.com/dataease/dataease/assets/83771182/dd861e8b-b1c5-4b04-a021-bfa2dea8578b)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划进行支持。
