### ISSUE TITLE
[Bug]添加sql数据集时，sql中添加了时间属性，设置参数时修改时间参数为日期，保存提示正常，但是重新进入后时间参数又变成文本类型了

### ISSUE THREAD

**Issue by 674236876** [dataease/dataease#10016]
**DataEase 版本**
V1.18.19
**运行方式(安装包运行 or 源码运行 ?)**
安装包运行
**浏览器版本**
chrome

**Bug 描述**
添加sql数据集时，sql中添加了时间属性，设置参数时修改时间参数为日期，保存提示正常，但是重新进入后时间参数又变成文本类型了

**Bug 重现步骤(有截图更好)**
第一步：
<img width="1680" alt="image" src="https://github.com/dataease/dataease/assets/22359285/3958c31d-d610-4263-8fb3-36eeec15564e">
第二步：修改month类型
<img width="1680" alt="image" src="https://github.com/dataease/dataease/assets/22359285/95fd8e63-67b7-4007-b08a-8c96c1dc1608">
第三步：保存成功
<img width="1680" alt="image" src="https://github.com/dataease/dataease/assets/22359285/a1a7ea4f-19e7-419d-ba7c-f764ac5b3af3">
第四步：重新进入编辑页面
<img width="1680" alt="image" src="https://github.com/dataease/dataease/assets/22359285/bb7b91dd-ea50-49de-a63c-d60f411c1c79">
第五步：设置被自动还原了，换成其他属性也是一样的
<img width="1680" alt="image" src="https://github.com/dataease/dataease/assets/22359285/97cfe952-8c83-4acb-b57a-a081ef3c84b3">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
