### ISSUE TITLE
[Feature]关于月初仪表板和定时报告无数据场景的优化

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#10021]
DataEase 版本:
v1 v2

场景：
用户数据 t+1 计算，仪表板日期过滤为 “当月”，当月初时（比如 6月1号），日期过滤组件更新为“6.1-6.30”，但数据只有5.31的数据，6.1的数据还没有生成；导致，仪表板为空，定时报告为空。

建议：
在日期过滤组件中，添加一个功能：”月初时是否显示上个月“，日期范围上个月则是 5.1-5.31，日期组件上个月则是5.31。

如果开启了此按钮，当每个月月初时就显示上个月的数据，不再是空白看板。

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
建议每天23:59:59执行。
