### ISSUE TITLE
[Feature]在数据集编辑自定义SQL时，增加表结构comment备注提示

### ISSUE THREAD

**Issue by YanceyHan** [dataease/dataease#10022]
DataEase 版本: v2.6
在数据集里编辑SQL的时候，点击这个按钮弹出的表结构提示，建议增加一列comment描述，这样就可以避免我有的字段不知道什么意义，或者不知道怎么取值的时候，再去数据库里查看comment。

![1717382545936](https://github.com/dataease/dataease/assets/10508311/32f1852f-3e3f-4151-acd1-abab5b100055)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们会在2.8版本支持。
