### ISSUE TITLE
[Feature]数据集列表的排序，增加自定义排序

### ISSUE THREAD

**Issue by YanceyHan** [dataease/dataease#10023]
DataEase 版本: v2.6

数据集列表这个排序，首先逻辑比较混乱，每次设置好名称升序，编辑其中某个数据集后又变时间排序。总之就是顺序经常变。
建议可以考虑增加一个排序设置，可以手动排序，对于我这种数据集很多的业务来说会非常友好。

**Comment by xuwei-fit2cloud** [comment]
这个是个bug，我们修复一下。
