### ISSUE TITLE
[Feature]在编辑数据集时，拖拽表进到编辑框后，建议增加一个where条件

### ISSUE THREAD

**Issue by YanceyHan** [dataease/dataease#10024]
DataEase 版本: v2.6
在编辑数据集时，拖拽表进到编辑框后，是否会考虑增加一个where条件的设置，这样连表就不会全表扫描。
每个表拖拽进去后，都可以写单表的where条件，这样可以过滤大多数数据。
但实现起来可能非常复杂，涉及到拼SQL的核心逻辑。但有没有其他更合适的办法能过滤大多数数据，可以讨论下。
这个需求可能也不是特别痛。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，当拖拽表时，系统没办法识别用户需要什么where条件。建议拖拽sql片段，自定义where条件，用于过滤表数据。
