### ISSUE TITLE
[Bug]对数值型维度加过滤器，输入内容为字符时导致全部数据被过滤掉

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1002]
**DataEase 版本**
V1.3.0

**浏览器版本**
Chrome 94

**Bug 描述**
对一个数值型维度做过滤，设置过滤条件为不等于 null 后，全部数据被过滤掉了。

**Bug 重现步骤(有截图更好)**
1.发现数据中有空值
![image](https://user-images.githubusercontent.com/48945409/138223978-9197ff67-4a03-45bb-af41-953ee53f1cdf.png)

2.增加了一个对该值的过滤器，设置为“不等于 null”。
![image](https://user-images.githubusercontent.com/48945409/138224119-d4e747b1-94c3-43f0-9d94-d2c51e6ae60c.png)

3.确认后仪表盘所有数据都没有了。
![image](https://user-images.githubusercontent.com/48945409/138224188-a6c1bed7-fd26-4164-83b3-351a020cdb9f.png)

4.经验证，输入任何一个字符型的串结果一致，例如“不等于 w”，也无数据。

**Comment by xuwei-fit2cloud** [comment]
可以设置不等于0来过滤
