### ISSUE TITLE
[Bug]v2 API数据源校验通过有正常显示数据，但在创建数据集时无数据

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#10044]
![image](https://github.com/dataease/dataease/assets/141667200/5ae39861-075d-49b5-bc4e-b315f00a8bae)
![image](https://github.com/dataease/dataease/assets/141667200/10dc8da9-ba2f-403a-84a8-daf2b41dcb63)

webhook：https://www.kdocs.cn/api/v3/ide/file/300981336818/script/V2-XDVLWahNdFCax6m3GJB8H/sync_task
脚本令牌：AirScript-Token  4wh6Aal1vqZUo37rotdnON

![image](https://github.com/dataease/dataease/assets/141667200/740e4647-bba0-434e-a71a-e79bd432949e)
![image](https://github.com/dataease/dataease/assets/141667200/ee6b2839-4272-4190-982e-e378e198dc0e)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本尽快修复；
