### ISSUE TITLE
[Bug]仪表板tab组件中使用富文本排版，保存仪表板，退出后再次进入编辑页面，富文本处会出现样式错乱

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#10042]
**DataEase 版本**
V2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
chrome 109

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.使用仪表板添加tab组件
2.在tab组件中使用富文本排版
3.保存仪表板，退出后再次进入编辑页面，富文本处会出现样式错乱
![d6f2a96e50fea7fe543868bd3592cef](https://github.com/dataease/dataease/assets/83771182/0cb8166e-3d98-4122-a3d6-a84110a1f514)

**Comment by BBchicken-9527** [comment]
感谢反馈，方便给我们一个模版看一下吗？

**Comment by BBchicken-9527** [comment]
感谢反馈，一般图表错位是因为在查看这个仪表板的时候客户端的内存不足以支撑仪表板的绘制导致运算出现了错误，从而导致了图表定位的错位，建议更换配置更高一点儿的电脑或者清一下内存试试看
