### ISSUE TITLE
[Feature]关于仪表板的分享功能：1、希望支持分享整个文件夹；2、允许取消分享。

### ISSUE THREAD

**Issue by zyy2721** [dataease/dataease#1004]
**请描述您的需求或者改进建议.**
关于仪表板的分享功能：
1、希望支持整个文件夹分享；
    当需要分享的仪表板较多时，一个个的点击，操作不便。希望能直接分享整个文件夹。
2、希望可以取消已分享的仪表板。
   希望可以取消已分享的仪表板，同时支持取消部分人的分享。
  例：一个仪表板分享给了三个人，有时只需要取消一个人查看的权限。

**Comment by yayanpei** [comment]
感谢您的反馈，您的建议非常好，我们会优先考虑加入优化清单中。
