### ISSUE TITLE
[Bug]地图视图带有缩放按钮导出后失真都变成黑色

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#10058]
**DataEase 版本**
2.6

**运行方式(安装包运行 or 源码运行 ?)**

安装包

**Bug 重现步骤(有截图更好)**
1.
<img width="628" alt="image" src="https://github.com/dataease/dataease/assets/101089844/7b5059e7-5baa-40a1-af51-9ffcfacc34b5">

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
