### ISSUE TITLE
[Bug]指标卡更换指标并更新数据后颜色样式会丢失

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#10056]
**DataEase 版本**
v2.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.指标卡更换指标并更新数据后颜色样式会丢失
![image](https://github.com/dataease/dataease/assets/101089844/92e7daac-86d9-4ef8-abe2-657543e5000e)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，这个问题和你上一个提交的批量是不是同一个问题？单独设置目前测试环境看起来是正常的；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
