### ISSUE TITLE
[Bug]指标卡批量设置颜色失效

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#10057]
**DataEase 版本**

2.6
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.
2. 编辑界面
![image](https://github.com/dataease/dataease/assets/101089844/0b7c84ae-2c3e-4f1f-bb85-4b03faef9907)

3.
![image](https://github.com/dataease/dataease/assets/101089844/49ce0a2c-b044-4031-944f-f790ecd97f8c)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
