### ISSUE TITLE
[Bug]elasticsearch 数据源新建仪表板，维度字段无法展示

### ISSUE THREAD

**Issue by crazyGiter** [dataease/dataease#10067]
**DataEase 版本**
V1.18.19

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 124.0.6367.208（正式版本） (arm64)

**Bug 描述**
elasticsearch 数据源新建仪表板，维度字段无法展示，只能展示指标字段和数据条数。

**Bug 重现步骤(有截图更好)**
1.新建elasticsearch 数据源。
2.新建数据集
![image](https://github.com/dataease/dataease/assets/12457281/e68c19f3-6a97-41e7-95a1-d602a0e319d6)

3.新建仪表板，并选择刚刚新建的elastic数据集
![image](https://github.com/dataease/dataease/assets/12457281/39b31baf-d170-4ca0-8103-0ae29e111351)

问题复现

**Comment by BBchicken-9527** [comment]
感谢反馈，请问使用的版本是？

**Comment by greenyhsj** [comment]
1.18.19 的elasticsearch 数据源 使用表格（明细表汇总表）会报错，如果是指标卡、柱状图不会

**Comment by BBchicken-9527** [comment]
使用的es版本是？

**Comment by BBchicken-9527** [comment]
感谢反馈，目前最新版本的es数据源没有你说的问题，可以更新到最新版本体验
