### ISSUE TITLE
[Bug]横向柱状图指标改变，标签颜色提前设置好的颜色会掉成默认

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#10069]
**DataEase 版本**
2.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
横向柱状图指标改变，标签颜色提前设置好的颜色会掉成默认

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，这是因为标签现在细分到每个指标了，每个指标可以进行单独的设置，所以更换指标后会显示默认颜色；
