### ISSUE TITLE
[Feature]V2版本啥时候可以更新出和V1版本一样的定时报告功能

### ISSUE THREAD

**Issue by daviadong** [dataease/dataease#10079]
DataEase 版本:
V2.6.1

**请描述您的需求或者改进建议.**
希望V2版本可以更新出和V1一样的定时发送仪表盘到钉钉之类的第三方平台的功能

**Comment by xuwei-fit2cloud** [comment]
本周即将发布的v2.7.0版本中支持了邮件和飞书两种方式，其他通知方式后续会补充。
