### ISSUE TITLE
[Feature] 组合图支持多折线

### ISSUE THREAD

**Issue by limin-fit2** [dataease/dataease#10083]
DataEase 版本:
V2.6.1

**请描述您的需求或者改进建议.**
目前有很多场景需要用到组合图场景，例如制造公司用组合图展示设备产出达成情况（计划数、产出数、达成率），例如航空公司需要组合图展示航班情况（销售量、客座率、贡献值）等场景，都是一个柱状图+多条折线表示，希望V2版本的组合图能像V1一样可以设置多个指标。
![image](https://github.com/dataease/dataease/assets/61964761/c893c33a-a674-4aad-8b40-8c3db809b1ac)

**Comment by limin-fit2** [comment]
AntV中有一个多轴图能达到类似的效果，是否可以考虑加入这个图表类型：https://g2.antv.antgroup.com/examples/general/dual/#multi-line

**Comment by xuwei-fit2cloud** [comment]
目前多折线的数据处理上有点问题，我们正在想办法解决。
