### ISSUE TITLE
[Bug]【同步管理】将 Oracle 中的数据同步至 Doris 当中报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10098]
**DataEase 版本**
v2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
将 Oracle 中的数据同步至 Doris 当中报错，报错如下。
![image](https://github.com/dataease/dataease/assets/24768910/3b4e5a4e-596f-4476-b116-b851cfaaff5c)

**Bug 重现步骤(有截图更好)**
可能原因如下：
![image](https://github.com/dataease/dataease/assets/24768910/1cb98c3c-cfab-402f-9fa3-65021ff3ab71)

**Comment by xuwei-fit2cloud** [comment]
我们的同步管理支持的是Apache Doris，StarRocks的话，咱们现在还不支持。

**Comment by AndroidBaby1** [comment]
了解，感谢！
