### ISSUE TITLE
[Bug]antv 组合图副坐标轴标签位置不生效

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#10109]
**DataEase 版本**

1.18.19
**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**
谷歌

**Bug 描述**
antv 组合图副坐标轴标签位置不生效，选副坐标轴标签择标签在上、下、中心，都没有变化

**Bug 重现步骤(有截图更好)**
1.主标签显示上方，副的下方，下方这个没有生效
![未命名](https://github.com/dataease/dataease/assets/127368807/c0b7d5f6-1b83-4f77-afab-da8b42646d89)

**Comment by xuwei-fit2cloud** [comment]
副轴标签仅对柱状图生效。
![图片](https://github.com/dataease/dataease/assets/1892127/23432296-ef17-4bfb-8f5b-60e1fbf6a9dc)
