### ISSUE TITLE
[Bug]v2.6.1基础折线图加载速度很慢

### ISSUE THREAD

**Issue by senn117** [dataease/dataease#10104]
**DataEase 版本**
v2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome125.0.6422.113（正式版本） （64 位）

**Bug 描述**
v2.6.1基础折线图加载速度很慢，同样的数据源在v1.18.2展示速度很快

**Bug 重现步骤(有截图更好)**
企业微信交流群在4月29号的时候提供了加载过程的视频，当时的版本是v2.4.1，加载速度和目前v2.6.1差不多。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们核实一下。

**Comment by xuwei-fit2cloud** [comment]
可以升级版本到2.10.2试试，SQL处理方式有调整。
