### ISSUE TITLE
[Bug]EChart 组合图切换到 AntV 的时候会被清空，图表无法显示

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#10110]
**DataEase 版本**

1.18.19
**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**
谷歌

**Bug 描述**
EChart 组合图切换到 AntV 的时候会被清空，且该图表无法显示
**Bug 重现步骤(有截图更好)**
1.![未命名](https://github.com/dataease/dataease/assets/127368807/b0c404d8-a8da-4370-8b81-fee1bff02d37)

2.
3.

**Comment by xuwei-fit2cloud** [comment]
您可以在 https://dataease.fit2cloud.com 环境上试试，并没有复现您描述的问题。
