### ISSUE TITLE
[Bug]移动视图分组到另一个分组是视图树展开方式错误

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#1012]
**DataEase 版本**
1.3

**浏览器版本**
谷歌版本 94.0.4606.61（正式版本） (arm64)

**Bug 描述**
通过鼠标右键迁移视图分组，点击分组，弹出视图分组，点击展开所有视图，第一次展开后会系统会自动快速关闭视图树
另外，期待模式视图树打开到第一根节点下
**Bug 重现步骤(有截图更好)**
1.选择某分组，点击迁移
2.选择打开视图树，等待1-3秒
3.视图是自动合并
![image](https://user-images.githubusercontent.com/60059766/138635090-6cd53238-0591-4a15-8cc7-552b9dd9a594.png)

**Comment by xuwei-fit2cloud** [comment]
v1.4.0 已修复
