### ISSUE TITLE
[Bug]【仪表板】时间范围组件外部参数传入值不对

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10124]
**DataEase 版本**
v1.18.19

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
时间范围组件外部参数传入值不对，详见重现步骤

**Bug 重现步骤(有截图更好)**
1.创建一个有时间范围组件的仪表板。
![image](https://github.com/dataease/dataease/assets/24768910/a667722a-2323-438a-a77c-522d907cf3fb)

2.生成公共链接。
![image](https://github.com/dataease/dataease/assets/24768910/eac9a472-698c-4e00-9915-bf4f04c3c06c)

3.创建外部参数。
![image](https://github.com/dataease/dataease/assets/24768910/a822e27b-a017-4b8e-95fb-3de2140ad76b)

4.加密筛选条件。
![image](https://github.com/dataease/dataease/assets/24768910/4a784d57-6411-4106-a616-d736f6ac8465)

5.带参数访问公共链接。
![image](https://github.com/dataease/dataease/assets/24768910/204ba8ae-eefd-4fce-baed-7f323b675a38)
问题补充：时间范围应该是 "2024-06-01","2024-06-02"，此处显示 "1970-01-01","1970-01-01"。

**Comment by BBchicken-9527** [comment]
感谢反馈，时间需要将其转为13位时间戳才可以的；
