### ISSUE TITLE
v2.6.1 如何创建多用户？

### ISSUE THREAD

**Issue by simcyber** [dataease/dataease#10129]
v2.6.1 如何创建多用户？
谢谢，安装好后看界面上没有，是要自己从数据库创建吗？

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，创建多用户是企业版的功能，如有需要，建议您先通过以下链接申请试用。
https://jinshuju.net/f/TK5TTd

**Comment by simcyber** [comment]
> 感谢反馈，创建多用户是企业版的功能，如有需要，建议您先通过以下链接申请试用。 https://jinshuju.net/f/TK5TTd

1.xx版本是不是支持？
谢谢！

**Comment by yayanpei-fit2cloud** [comment]
1.x社区版也不支持创建多用户，这个是属于企业版的功能哈。
