### ISSUE TITLE
查询组件不点击查询，选择元素后自动开始查询

### ISSUE THREAD

**Issue by yanlong-big** [dataease/dataease#10136]
DataEase 版本:2.5.0

在查询组件中，选择元素后，为什么要再点查询才能开始查询呢，应该选择元素后自动的就开始查询。

![1717639810031](https://github.com/dataease/dataease/assets/116066130/f3c88b73-1454-4faa-8a93-598bc6c1c3de)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，这是基于节省查询次数的考虑，如果有多个查询条件，那么等所有查询条件全部选择完毕后，再统一请求数据，避免每个查询条件选择完后就触发一次数据请求。
