### ISSUE TITLE
[Bug]数据大屏导入模版后，组合图层大小不一致

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#10144]
**DataEase 版本**
V2.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome

**Bug 描述**
数据大屏导入模版后，组合图层大小不一致

**Bug 重现步骤(有截图更好)**
1.数据大屏导出模版
2.导入模版
3.应用模版发现组合后的涂层，大小有变化
点一下组合或放大缩小画布又恢复正常
<img width="1225" alt="image" src="https://github.com/dataease/dataease/assets/133861755/f73c9404-fa51-4ea9-b4b7-a740c09d4476">
<img width="1241" alt="image" src="https://github.com/dataease/dataease/assets/133861755/708082c8-edbd-4a9d-9880-7787722d9e89">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本尽快进行修复；
