### ISSUE TITLE
[Bug] pg 字符串日期转换时间类型异常

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#10149]
**DataEase 版本**
2.7

**Bug 描述**
pg 数据集字符串日期转时间类型失败

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/40597893/4989c184-39e1-4049-8d19-809d7ff00cc2)

![image](https://github.com/dataease/dataease/assets/40597893/ff102740-7348-4ebe-b2c1-067890116e93)

![image](https://github.com/dataease/dataease/assets/40597893/dd4d697f-1a90-4c53-9252-3385ac6ee572)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快在后续版本修复；
