### ISSUE TITLE
汇总方式新增“无”选项

### ISSUE THREAD

**Issue by jnfJNF** [dataease/dataease#10148]
DataEase 版本:2.6.0

**请描述您的需求或者改进建议.**
汇总方式是否增加一个“无”选项。有些数据不需要二次计算指标值。
![image](https://github.com/dataease/dataease/assets/25213350/5eb8d7f7-e6c9-44f3-b2e8-014536745c16)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，有些图表比如汇总表，是需要进行根据维度，对指标进行聚合计算的，否则图表中无法展示。因此，如果需要使用汇总表，那么汇总方式便不能选择无；如果汇总表所使用的数据集是根据维度聚合后的结果，那么选择哪种汇总方式都是一样的结果。

**Comment by jnfJNF** [comment]
> 捐赠人的反馈，有些是图表比如表，是需要根据维度，对指标进行聚合计算的，否则图表中无法展示。因此，如果需要使用图表，那么就不能选择无；如果使用维度，则不能选择哪种方式，如果使用集合，则不能选择哪种方式。

我说的是组件内的“汇总方式”，并不是说的汇总表组件。是所有组件在进行指标回显时，需要选择的“汇总方式”。

**Comment by yayanpei-fit2cloud** [comment]
我说的也是这种情况，汇总表是举的一个例子，再比如柱状图，也是需要根据维度，对指标进行聚合计算的，如果不需要聚合计算，建议使用明细表。聚合与不聚合，其实与图表类型是有关的。
