### ISSUE TITLE
[Bug]数据集展示0值时，展示为科学计数法，无法用round函数处理

### ISSUE THREAD

**Issue by lyons-hz** [dataease/dataease#10152]
**DataEase 版本**
2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 124.0.6367.60

**Bug 描述**
数据集展示0值时，展示为科学计数法，无法用round函数处理

**Bug 重现步骤(有截图更好)**
1. 原始数据有为0的值
2. 制作数据集，预览为科学计数法
3. 新建计算字段，使用round函数处理，仍然为0。建议显示为0，并且可以用round函数处理为指定的小数位数
![image](https://github.com/dataease/dataease/assets/89773363/c17f77eb-6f14-40c7-ad69-b351733e0cc7)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前数据会经过calcite处理，calcite中0的显示会以科学技术法的方式显示，目前没有合适的方式去处理，不好意思给你的使用带来不便啦😬，我们会持续对calcite进行优化，但短期无法实现；
