### ISSUE TITLE
[Feature]支持时间过滤的最近1天、3天、7天、1个月等的过滤

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#1015]
**请描述您的需求或者改进建议.**
支持基于时间的最近一段时间的过滤，如：
最近1天
最近3天
最近7天
最近1个月
最近3个月
主要解决如资源容量的监控数据，取近一段时间的平均值等

**Comment by xuwei-fit2cloud** [comment]
1月份即将发布的 v1.6.0 将会进行支持。
