### ISSUE TITLE
[Bug] Dockerfile Build时，CoreApplication.jar: file does not exist

### ISSUE THREAD

**Issue by baiwei0703** [dataease/dataease#10151]
**DataEase 版本**
V2.7

**运行方式(安装包运行 or 源码运行 ?)**
Git Clone后，使用项目中的Dockerfile进行built

**浏览器版本**
构建镜像时就报错了。。。

**Bug 描述**
在构建镜像时，报错如下：
Step 7/12 : ADD core/core-backend/target/CoreApplication.jar /opt/apps/app.jar
ADD failed: file not found in build context or excluded by .dockerignore: stat core/core-backend/target/CoreApplication.jar: file does not exist
**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/34114426/e091a6d5-db45-4335-ab41-5aa4e1fff878)

**Comment by maninhill** [comment]
https://dataease.io/docs/v2/installation/deployment_installation/
请参考这个。
