### ISSUE TITLE
[Bug]组合图如果没有维度，则统计结果显示不对

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#1016]
**DataEase 版本**
1.3

**浏览器版本**
谷歌

**Bug 描述**
【组合表】视图没有维度选项时，统计中有个【合计】信息展示占行了

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/60059766/138650621-c21beb09-84eb-4f68-8b23-4e9bbd5844dc.png)

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 已处理
