### ISSUE TITLE
[Bug] Oracle获取Schema报错，oracle.jdbc.driver.OracleDriver

### ISSUE THREAD

**Issue by SerMs** [dataease/dataease#10161]
**DataEase 版本**
dev-v2

**运行方式(安装包运行 or 源码运行 ?)**
Windows宿主机本地源码方式启动,在本地打包后用Java -jar 的方式启动

**浏览器版本**
Chrome  125.0.6422.142

**Bug 描述**
启动后点击获取Schema报错，提示：oracle.jdbc.driver.OracleDriver
![image](https://github.com/dataease/dataease/assets/67584847/37aaf9fa-69ca-4abc-aec8-b92495b099f8)
控制台报错如下
![image](https://github.com/dataease/dataease/assets/67584847/a4263800-9d01-409e-a195-fb262fee3866)

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/67584847/15241ebd-8f4c-4a5d-9df1-777b7b1626c0)
2.
3.

**Comment by maninhill** [comment]
请参考这个：https://dataease.io/docs/v2/installation/deployment_installation/

**Comment by SerMs** [comment]
> 请参考这个：https://dataease.io/docs/v2/installation/deployment_installation/

是参考这个来的，只是没做docker镜像，能告诉我为什么源码部署启动后配置Oracle时点击获取Schema提示：oracle.jdbc.driver.OracleDriver呢？

**Comment by SerMs** [comment]
数据源管理面板中，Mysql连接源能成功创建，当尝试创建Oracle时需要填写Schema就显示没驱动还是什么原因

**Comment by liuqiyanabc** [comment]
请问这个问题解决了吗，怎么解决的
