### ISSUE TITLE
[Feature]【仪表板】多媒体组件中的图片支持适应组件、等比适应、原始尺寸等设置。

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10168]
DataEase 版本:
v2.7 版本

**请描述您的需求或者改进建议.**
多媒体组件中的图片支持适应组件、等比适应、原始尺寸等设置，参考 v1，如下图所示。
<img width="500" alt="image" src="https://github.com/dataease/dataease/assets/24768910/6ef71fd8-b85c-4926-b5e2-9c025c01e318">

**Comment by xuwei-fit2cloud** [comment]
已排期。
