### ISSUE TITLE
更改数据类型时报错

### ISSUE THREAD

**Issue by yanlong-big** [dataease/dataease#10165]
社区版2.5.0

edge

![1717740370195](https://github.com/dataease/dataease/assets/116066130/91596f1e-438a-4260-9fc4-91bda50f9807)
![image](https://github.com/dataease/dataease/assets/116066130/8bd1a006-e28b-45a9-8fe8-83bfe5f48180)
这个数据日期字段，在mysql中是文本，我在dataease的数据集中更改成日期格式后他就报错了，是怎么回事呢，都是标准日期

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内尽快修复；

**Comment by BBchicken-9527** [comment]
感谢反馈，后续需要使用数据库方式：%Y%m%d；
