### ISSUE TITLE
[Feature] v2 中国地图图表中能否支持图例数值范围设置

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#10164]
DataEase 版本:
v2.6.1

**请描述您的需求或者改进建议.**
<img width="467" alt="image" src="https://github.com/dataease/dataease/assets/45967454/a8c11ad9-6bb0-471b-bf22-3d89db0cb258">
问题描述：地图图表中，这个图例是有什么生成规则吗，这个数值间的范围能够调的更小一些吗，比如200 ~ 250 ,300 ~ 350 ，数值范围需要可以自定义。
场景：有些省份或者城市数据比较接近，会存在两个省份一个颜色的情况，这种不易区分。
为什么坚持使用地图图表：我坚持用地图的原因是，地图不仅仅能够显示每个省份的人数多少、占比多少以及排号第几，还有一个因素是，它能直观的表达出来区域分布，比如说排名前五的患者都来自华北华东地区的沿海省份，这个是其他图表所不具备的。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，已排期。
