### ISSUE TITLE
[Bug]全屏预览后，右边多出一截

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#10176]
**DataEase 版本**

1.18.20
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

谷歌
**Bug 描述**

编辑界面下，左右两边是一样的，全屏后，右边就多出来一截。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/127368807/920ceb4e-5e18-4024-9ddb-7fdeb0584414)

2.
![image](https://github.com/dataease/dataease/assets/127368807/363befe1-8957-4711-b5a3-452e44f82fc7)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前组件之间是会存在一些留白，这些留白可能会在全屏显示中存在差异，我们调整一下，去掉tab组件中不必要的留白，优化显示效果；
