### ISSUE TITLE
[Feature]v2透视表 小计希望可以分级控制显示

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#10170]
![d81e6ac38471c0017a5b5f416cbb221](https://github.com/dataease/dataease/assets/141667200/bd70613f-3a22-4ddf-a908-97a706972859)
当出现多级显示时，希望小计可以单独控制。
比如只需要2级显示小计，1级不需要显示小计。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们需要调研一下图库是否支持。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，需求我们先记录一下，近期暂时没有计划支持。
