### ISSUE TITLE
[Feature]希望支持自定义时间转换格式

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#10172]
DataEase 版本:
2.7.0

**请描述您的需求或者改进建议.**
希望在数据集管理中能够支持自定义时间格式。
当前版本效果图：
<img width="728" alt="image" src="https://github.com/dataease/dataease/assets/60059766/5d61acbd-b02c-4b1a-9c21-5e7c15361a01">
V1.0版本已实现自定义的参考图：
![image](https://github.com/dataease/dataease/assets/60059766/b8f82872-e674-4fa5-a6b6-cb47d7b6e45e)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，自定义格式是支持的，弹框高度展示不全，因此需要滚动才能展示出来，如下图所示：
![image](https://github.com/dataease/dataease/assets/84168063/d9d32162-331b-4904-885d-993037e90b73)
