### ISSUE TITLE
使用1panel安装dataease报错

### ISSUE THREAD

**Issue by cs0618-ui** [dataease/dataease#10184]
Caused by: io.dataease.exception.DEException: apisx配置错误！
这是日志
[Uploading dataease-20240611150331.log…]()

**Comment by cs0618-ui** [comment]
[dataease-20240611150331.log](https://github.com/user-attachments/files/15783747/dataease-20240611150331.log)

**Comment by cs0618-ui** [comment]
![image](https://github.com/dataease/dataease/assets/153248531/b78c2f32-a4c6-4351-ad58-bfe134e60c93)

**Comment by CupOfBread** [comment]
我也是这个报错欸

**Comment by longshao5520** [comment]
这个问题是没人管吗

**Comment by xuwei-fit2cloud** [comment]
这个报错信息并不影响使用，在v2.10.2版本中已处理。
