### ISSUE TITLE
自定义插件开发

### ISSUE THREAD

**Issue by huiLingJun** [dataease/dataease#10186]
**请描述您的问题.**
请问如何开发自定义插件，可以举个详细的案例说明一下嘛，哒哒么

**Comment by xuwei-fit2cloud** [comment]
目前有插件的版本是V1版本。
V1版本有两类插件，视图插件：
https://dataease.io/docs/v1/dev_manual/dev_view_plugin/

数据源插件：
https://dataease.io/docs/v1/dev_manual/dev_datasource_plugin/

可以参考一下上面的文档，示例插件在文档里也有链接。

**Comment by huiLingJun** [comment]
> 目前有插件的版本是V1版本。 V1版本有两类插件，视图插件： https://dataease.io/docs/v1/dev_manual/dev_view_plugin/
> 
> 数据源插件： https://dataease.io/docs/v1/dev_manual/dev_datasource_plugin/
> 
> 可以参考一下上面的文档，示例插件在文档里也有链接。

你好，请问一下下，比如要开发一个自定义的进度条插件，我应该怎么去开发，直接按着文档来，建一个类似官方视图插件的文件吗？然后调试是直接本地调试吗？因为我是前端，目前还不太懂后端，看不懂Java，嘤嘤。

**Comment by maninhill** [comment]
请查看文档。
