### ISSUE TITLE
[Bug]指标卡背景设置其他颜色有白底

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#10188]
**DataEase 版本**
2.7.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器最新

**Bug 描述**
部署最新版本2.7.0，以及从2.6.1升级到2.7.0均存在此问题，之前2.6.1版本是正常的

**Bug 重现步骤(有截图更好)**
配置指标卡视图，设置指标卡背景色为其他颜色，就会出现白底
![image](https://github.com/dataease/dataease/assets/35896106/9531acfa-f836-4a70-aa2e-0e742a942d8c)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，目前已被修复将会在下个版本中上线；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新到v2.7.1版本。
