### ISSUE TITLE
[Bug]Echarts明细表在仪表板创建公共链接的情况下，无法导出Excel数据，点击按钮无反应

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#10194]
**DataEase 版本**
v1.18.20

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
Echarts明细表在仪表板创建公共链接的情况下，无法导出Excel数据，点击按钮无反应

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，目前正在努力解决，会在下个版本修复完成；
