### ISSUE TITLE
[Feature]系统变量支持同一个变量名，变量值可以多选

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#10190]
DataEase 版本:
V2.7.0

**请描述您的需求或者改进建议.**
同一个变量名可以多选多个变量值，比如某个老师负责两个学院，他希望看两个学院相关的数据，可以在用户配置添加选择两个学院的系统变量，行权限那边通过or配置两个系统变量，如下图：
![image](https://github.com/dataease/dataease/assets/35896106/a9ce19a8-4826-4606-b292-1c6de73a8284)
![image](https://github.com/dataease/dataease/assets/35896106/1818efd8-057f-4f9c-baab-db959b6db9b8)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，需求已排期。
