### ISSUE TITLE
[Feature]跑马灯跑完后，最后一个字与第一个字进行衔接循环

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#10197]
DataEase 版本:
2.7

**请描述您的需求或者改进建议.**
跑马灯跑完后会接着消失，过一会又开始第一个字的滚动。
希望可以跑马灯的最后一个字与第一个字进行衔接，跑完后空一段距离继续滚动。
![image](https://github.com/dataease/dataease/assets/133861755/940af802-be34-4770-b078-91f636d17d0d)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们在近期的版本中优化一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
