### ISSUE TITLE
[Bug]v2 admin管理员登录 一直在线编辑会突然“提示无权访问当前资源......”

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#10196]
<img width="578" alt="7b435bc429dca6b65ee9d03f8facd9b" src="https://github.com/dataease/dataease/assets/141667200/774c7337-1b61-4de6-a4a2-0a75949abd5c">

**Comment by wolf-kingx** [comment]
然后会强制退出，一下午出现了三次。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前v2账号不能切换不同组织去多组织操作，其实并不是admin独有，其他的账号也会提示异常的，因为目前v2对数据进行了组织隔离，当修改仪表板后切换组织去保存，系统时无法找到当前组织下的仪表板的，从而出现异常；
