### ISSUE TITLE
[Bug]V1.18.20 数据集无法导出

### ISSUE THREAD

**Issue by htl258** [dataease/dataease#10198]
**DataEase 版本**
V1.18.20

**运行方式(安装包运行 or 源码运行 ?)**
源码运行（1panel安装的）

**浏览器版本**
EDGE或谷歌最新版

**Bug 描述**
数据集导出报错

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by htl258** [comment]
![QQ20240611191108](https://github.com/dataease/dataease/assets/131636095/5da59ca0-33e8-4bed-9be8-6379c9291a2b)

**Comment by xuwei-fit2cloud** [comment]
已修复，请等待新版本发布。

**Comment by xuwei-fit2cloud** [comment]
请更新到v1.18.21版本。

**Comment by htl258** [comment]
> 请更新到v1.18.21版本。

已更新，更新后问题依然存在。还是感谢你们的努力
![QQ截图20240614035706](https://github.com/dataease/dataease/assets/131636095/bae0b01d-cd64-4c53-ae57-73daaa9faf5c)
