### ISSUE TITLE
[Feature]一个信息化咨询师的建议，希望能实现

### ISSUE THREAD

**Issue by gdtool** [dataease/dataease#1019]
>首先感谢dataease提供了这么好的工具
# 1. 手机自适应
现在手机比pc便捷，毋庸置疑，报表主要给老板看，老板经常出差，在手机看报表需求极其强烈
# 2.支持API接口同步数据
数据库很敏感，读取接口的json成为趋势
# 3.常见系统的数据集成
用友、金蝶、管家婆，这些常见系统，直接做成现成的管理驾驶舱demo，将有利dataease的迅速普及
# 4.建一个论坛
论坛的好处是可以沉淀为知识库，微信群算个啥？

**Comment by xuwei-fit2cloud** [comment]
1. 目前已支持移动端展示
2. 目前也已支持API数据源，支持json格式数据
3. DataEase以应用的形式来对接常见第三方系统，目前内置了对Jumpserver的支持，用友、金蝶等实现起来也是类似的
4. 我们现阶段是以在线文档+在线知识库的形式提供知识查询，如还有不能解决的问题，则可以在微信群里咨询
