### ISSUE TITLE
[Feature] 图表能否支持不同指标下来设置不同样式

### ISSUE THREAD

**Issue by snecker** [dataease/dataease#10202]
DataEase 版本: 2.7.0

**请描述您的需求或者改进建议.**

如果有三个指标，现在想设置其中两个用左侧Y轴，第三个指标设置到右侧Y轴，当前的设置是对于所有指标一起生效。希望能增加按指标进行不同图标样式设置开关（可以默认统一设置，然后支持自定义指标样式设置），这样可以灵活很多。

比如截图，因为三个指标的数值范围相差太远，无法在一个图表上清晰展示。
![image](https://github.com/dataease/dataease/assets/4178594/1fcf117e-e55b-465d-bcae-b144f67a0ff9)

**Comment by xuwei-fit2cloud** [comment]
可以等等我们后续版本推出的双轴图系列。
