### ISSUE TITLE
[Feature]建议支持仪表板的租户迁移

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#10200]
DataEase 版本:

v2.7

**请描述您的需求或者改进建议.**

希望能将一个仪表板从A租户完整迁移到B租户

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已在需求池中，近期暂时没有计划进行支持，待有更多用户反馈后，我们再进行下一步的规划。
