### ISSUE TITLE
[Bug]公共链接分享（无密码保护），打开依然需要输入密码，且报错。

### ISSUE THREAD

**Issue by zyy2721** [dataease/dataease#1020]
**DataEase 版本**
v1.3.0

**浏览器版本**
edge，火狐，谷歌均有该问题。

**Bug 描述**
公共链接分享（无密码保护），打开依然需要输入密码。
取消输入密码后报错，但内容能查看。

**Bug 重现步骤(有截图更好)**
1.<img width="890" alt="1" src="https://user-images.githubusercontent.com/71361375/138789971-7077f9e9-b3eb-42c3-b38c-3117b3604574.png">
<img width="840" alt="2" src="https://user-images.githubusercontent.com/71361375/138789980-fce9a7af-fea5-435d-9df4-c7e39273df41.png">
2.
3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，该问题已修复，请等待 v1.4.0 版本发布

**Comment by xuwei-fit2cloud** [comment]
v1.4.0 版本已修复
