### ISSUE TITLE
[Bug]更换错误的地图KEY后，不能显示地图

### ISSUE THREAD

**Issue by SuxueCode** [dataease/dataease#10219]
**DataEase 版本**
2.7.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
edge 125.0.2535.92

**Bug 描述**
新版本多了流向地图，试用了一下，建议你们添加一下地图key的描述需要的是js api key
今天我先是用了web的key，不行，后面换到js api的key，一下子可以一下子不行
后面排查了一下应该是前端cookie内缓存了online-map-key，所以key更新后，错误的key在缓存依旧存在，所以地图不能正常显示，建议你们优化一下

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们后续版本优化一下。
