### ISSUE TITLE
[Bug]360浏览器 组件显示不出来

### ISSUE THREAD

**Issue by ITwuwei** [dataease/dataease#1021]
![image](https://user-images.githubusercontent.com/35763006/138806197-b84f52a0-56c3-4bbd-a746-52c36f63b42f.png)
![image](https://user-images.githubusercontent.com/35763006/138806225-b5543b15-6f4f-4bf5-a675-7c9f44e8983a.png)

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
