### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by xun986** [dataease/dataease#1022]
**DataEase 版本**
1.3.0

**浏览器版本**
Safari浏览器14.0.3

**Bug 描述**
字体切换后不是所有部分的字体都能迅速切换至另一种字体，需要刷新一下网页才能全部切换，就是说点击切换后界面字体不能及时统一的感觉。

**Bug 重现步骤(有截图更好)**
1.字体由简体中文切换至繁体中文。
2.看到部分字体换了但部分没有切换过来，比如最上面一行“仪表板”、“视图”、“数据集”等，“系统管理”中左侧一列“站内消息”等字体还是简体中文；但“系统管理”中“所有消息”的“同步类型”、“仪表板分享”等界面字体已经是繁体中文。
3.刷新一下网页，所有的字体才统一变成繁体中文。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这是浏览器的兼容性问题，用谷歌浏览器应该不会有这个问题，我们尽量处理一下。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，浏览器兼容性问题还需要一些时间来处理，近期内还不会支持，先暂时关闭。
