### ISSUE TITLE
[Bug]v2.7 一个仪表板上图标多的排好版之后，预览和点击编辑器进去的排版不一样。

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#10222]
https://github.com/dataease/dataease/assets/141667200/ee7312a3-1179-4d9b-b994-3a74efb5dc83

这是第二次排版好之后出现这样的情况，之前的没录屏重新搞了。

**Comment by wolf-kingx** [comment]
已保存好，清缓存无变化，做好的是预览的那样，点进去之后感觉每个图表的大小是调整之后的，但是位置错乱了。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
