### ISSUE TITLE
[Bug]仪表板&数据大屏部分模板在模板市场下载后导入DataEase中，显示异常，无法正常使用

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#10239]
**DataEase 版本**
v2.7.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
仪表板&数据大屏模板在模板市场下载后导入DataEase中，显示异常，无法正常使用，只占屏幕的四分之一左右。

**Bug 重现步骤(有截图更好)**
1.模板市场下载对应的模板或者数据大屏（如仪表板：物业车位管理看板、连锁门店2021年销售驾驶舱；数据大屏：销售管理可视化大屏）
2.导入到模板管理
3.新建仪表板或者数据大屏，使用模板新建
![image](https://github.com/dataease/dataease/assets/70566485/b0e15ba0-1c8e-459d-ab03-00123570e6b3)
![image](https://github.com/dataease/dataease/assets/70566485/a6bf95e3-da6c-45b1-80c9-9e1268bffc01)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
