### ISSUE TITLE
[Feature] 折线图标签位置可否开放调整

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#10231]
DataEase 版本:
v2.7

**请描述您的需求或者改进建议.**
折线图标签位置可否跟柱状图一样开放位置调整，v1 v2 同需求。
![image](https://github.com/dataease/dataease/assets/30063018/7de3d360-4cf4-4509-a93a-9f69a67fa338)
![image](https://github.com/dataease/dataease/assets/30063018/1ee71638-93cb-4cc9-bf95-2648c4f1ac25)

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
