### ISSUE TITLE
[Question]公共链接不能导出数据，提示前往数据导出中心查看下载进度

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#10237]
**请描述您的问题.**
创建”公共链接“，通过公共链接访问并尝试导出数据，导出完成后，期望数据直接导出，实际提示”前往数据导出中心查看下载进度“。 然后一定要登录系统后才能在去下载，较之前直接下载体验差了一些

**Comment by xiaorsly88** [comment]
V1.0版本社区版

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们下个版本修复一下。

**Comment by xiaorsly88** [comment]
![image](https://github.com/dataease/dataease/assets/27687681/67fc8c0c-3e80-412d-886a-af4a850afc13)
问题仍然存在
