### ISSUE TITLE
[Feature]视图中的明细表如果当前图框可以展示所有数据，能否不显示分页按钮

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#1023]
视图---插入明细表；加载数据后，当期那图框可以展示所有的数据，明细表下面也会有分页按钮，能否判断，只有当前表框超出显示范围（一页显示不全）才会有分页按钮。
                                                                                       -----yumin.fan-fit2cloud

**Comment by xuwei-fit2cloud** [comment]
v1.12.0版本已支持。
