### ISSUE TITLE
[Bug]数据集修改以后，使用了该数据集的仪表板都要重新设置一下数据集字段

### ISSUE THREAD

**Issue by paopaoteng** [dataease/dataease#10241]
**DataEase 版本**
V2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**

**Bug 描述**
修改数据集，比如修改了查询条件或新增了字段，那么使用了该数据集的仪表板都要重新设置数据集的字段信息

**Bug 重现步骤(有截图更好)**
1.仅仅修改了数据集SQL，加了个空格，重新保存数据集以后，原来的仪表盘字段就变成红色了
<img width="1737" alt="image" src="https://github.com/dataease/dataease/assets/3022192/f134bae7-d4da-4e28-9753-7d05f94de272">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前sql自定义方式创建的数据集我们无法判断你的sql变动是否会导致字段处理出现问题的；
