### ISSUE TITLE
[Feature] 过滤组件允许配置组合里的视图

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#10247]
DataEase 版本:
v 2.7.1

**请描述您的需求或者改进建议.**
过滤组件允许配置组合里的视图
![image](https://github.com/dataease/dataease/assets/45852479/3e0a1204-de49-4954-9f42-d624b1606c7b)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们修复一下。
