### ISSUE TITLE
[Bug]arm64机器下离线部署镜像程序崩溃

### ISSUE THREAD

**Issue by hyeluoh** [dataease/dataease#10244]
**DataEase 版本**
2.7.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
arm64机器下离线部署镜像程序崩溃

**Bug 重现步骤(有截图更好)**
进入docker内部查看程序，jdk版本如图
<img width="1416" alt="image" src="https://github.com/dataease/dataease/assets/31063160/f7e02429-1872-45c3-a3f3-46c15d001b1a">
**疑问**
是否能提供arm环境的离线安装包呢？

**Comment by xuwei-fit2cloud** [comment]
社区版并没有提供arm环境的离线安装包，您可以加入我们的企业微信群，找我们的服务人员获取arm架构的离线安装包。
