### ISSUE TITLE
新建参数时能不能新建一个今天日期的参数

### ISSUE THREAD

**Issue by yanlong-big** [dataease/dataease#10251]
s社区版 2.5.0

新建参数时可以添加今天日期的参数，这个日期参数是动态的，今天是6/13明天是6/14后天是6/15

![image](https://github.com/dataease/dataease/assets/116066130/496c9734-327c-4dcc-950a-4a89f247f3f0)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，暂时没有计划进行支持，参数值仅在数据集预览时生效，如果要使用，需要配合仪表板或者大屏的过滤组件进行使用，建议给过滤组件设置动态默认值。
![image](https://github.com/dataease/dataease/assets/84168063/bc11b9f3-ee3b-4feb-b9aa-1bdf01b7836c)
