### ISSUE TITLE
[Bug] 直接拖动左侧图层排序无法触发保存按钮事件

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#10254]
**DataEase 版本**
v 2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
125.0.6422.142

**Bug 描述**
直接拖动左侧图层排序无法触发保存按钮事件，保存按钮还是灰色的

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/45852479/227a2175-b774-4dbf-8acd-f88eecc02f16)
![image](https://github.com/dataease/dataease/assets/45852479/82697a4a-9b10-4d3d-93b0-75f3f480104b)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
