### ISSUE TITLE
[Feature]【图表】流向地图支持显示起点和终点名称

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10263]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
流向地图支持显示起点和终点名称
![image](https://github.com/dataease/dataease/assets/24768910/3e26c438-5bb1-4f10-a9be-c25d66d2f4df)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经加入近期的版本迭代中。
