### ISSUE TITLE
[Feature]【图表】组合图支持调整柱状图的样式

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10266]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
组合图支持调整柱状图的样式，参考 v1。
<img width="382" alt="image" src="https://github.com/dataease/dataease/assets/24768910/29d8a854-0e21-4e4e-b9bb-3dfc4b89dea3">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，v1支持后效果不太好，v2暂时没有计划支持调整柱宽等。
