### ISSUE TITLE
[Feature]建议矩阵模式下图形可调整的大小颗粒度可以更小一些

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1027]
**请描述您的需求或者改进建议.**
在矩阵模式下拉动图表的大小会按照一定的宽度颗粒度进行限制，目前这个颗粒度感觉有点大，给人的自由度就小了很多。例如下图的标题宽度要么感觉会有点窄要么会有点宽，但是在该模式下无法找到一个自己感觉更适合的。
![image](https://user-images.githubusercontent.com/48945409/139026268-afe501d4-6023-4247-bfdd-b43883606088.png)
![image](https://user-images.githubusercontent.com/48945409/139026302-eac3dd7a-3fe1-48fa-942c-233a9a8d813e.png)

**Comment by xuwei-fit2cloud** [comment]
v1.12.0版本支持的粒度已经精细化了很多，可以试试。
