### ISSUE TITLE
[Bug]v2 组合图更改了指标显示名称后未生效

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#10277]
**DataEase 版本**
2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**Bug 描述**
v2 组合图更改了指标显示名称后未生效

**Bug 重现步骤(有截图更好)**
1.

![image](https://github.com/dataease/dataease/assets/101089844/41f7603b-3fa7-4859-9197-99eaaf96882e)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，目前我们正在抓紧修复，将会在下个版本完成修复；
