### ISSUE TITLE
[Feature]希望仪表板能支持树形菜单组件，组件内可以设置菜单级别，并指定每级菜单点击后跳转的仪表板地址链接。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#10278]
DataEase 版本:

希望仪表板能支持树形菜单组件，组件内可以设置菜单级别，并指定每级菜单点击后跳转的仪表板地址链接。客户会制作多个仪表板，想用菜单做为首页进行跳转。目前在明细表视图中虽然也能实现类似功能但是不够美观。

**请描述您的需求或者改进建议.**

**Comment by maninhill** [comment]
重复提交。
