### ISSUE TITLE
[Bug]矩阵模式下编辑仪表盘会出现调整浏览器大小而挤压图表相对位置的情况

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1028]
**DataEase 版本**
V1.3.0

**浏览器版本**
Chrome 94

**Bug 描述**
矩阵模式下编辑仪表盘，当调整浏览器窗口大小会导致挤压图表相对位置变化。

**Bug 重现步骤(有截图更好)**
1.初始仪表盘
![image](https://user-images.githubusercontent.com/48945409/139027311-6088f77c-ea25-478d-b584-4bec99e2ecbb.png)

2.调整浏览器窗口大小变窄
标题图表被挤压到最下面
![image](https://user-images.githubusercontent.com/48945409/139027413-dceb48d0-575f-4e00-85fd-03dcd65397c4.png)

3.重新把标题元素放上去
![image](https://user-images.githubusercontent.com/48945409/139027451-79998670-a349-47a3-91da-53c0aba2c827.png)

4.尝试拉宽浏览器窗口，同样会出现被挤压到下面的情况
![image](https://user-images.githubusercontent.com/48945409/139027602-438fa22d-02c2-4252-93d0-984298a6f278.png)

**Comment by xuwei-fit2cloud** [comment]
v1.5.0已修复
