### ISSUE TITLE
[Bug]仪表板中地图视图，世界地图中标签无法正常显示，但中国地图中标签可以正常显示。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#10282]
**DataEase 版本**

V2.7.1
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome126

**Bug 描述**
仪表板中地图视图，世界地图中标签无法正常显示，但中国地图中标签可以正常显示。

**Bug 重现步骤(有截图更好)**
1.仪表板中地图视图
2.世界地图中标签无法正常显示
![image](https://github.com/dataease/dataease/assets/83771182/905ab613-3171-40fc-80d5-3c4b34d1176c)
3.但中国地图中标签可以正常显示。
![image](https://github.com/dataease/dataease/assets/83771182/26f2fe8c-28b0-494c-9478-26221372ab13)
4.V1版本地图也可正常显示标签

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，我们将会在下个版本进行修复；
