### ISSUE TITLE
[Feature]希望地图视图地名映射与数据集不一致时，可以增加提示功能。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#10283]
DataEase 版本:

V2.7.1
**请描述您的需求或者改进建议.**
希望地图视图地名映射与数据集不一致时，可以增加提示功能。希望不一致的要有提示信息或者标注，现在每次做视图还要自己对比国家名称，觉得增加了工作量。或者视图的地名列表增加导出功能，自己用excel对比下也可以。在地名这块很难与视图默认的名称保持完全一致。
![7ca85da08a17752dd523abfae58a255](https://github.com/dataease/dataease/assets/83771182/35c77b59-8bc9-4e6d-9f54-1da947cae9ab)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，由于系统无法获知地图中的地名与数据集中地名的匹配规则，因此无法进行匹配给出提示。如果需要地名对比，建议先拿json文件（opt/dataease/data/custom），解析后进行对比和地名映射。
