### ISSUE TITLE
[Bug]复制大屏链接地址到其他未登录浏览器上打开，页面报500

### ISSUE THREAD

**Issue by spritelyl** [dataease/dataease#10297]
**DataEase 版本**
v2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
125.0.6422.77
**Bug 描述**
复制大屏链接地址到其他浏览器上打开，页面报500

**Bug 重现步骤(有截图更好)**
1.打开大屏展示页面
2.复制大屏链接地址到其他未登录的浏览器上打开，页面报500，无痕打开也报500
报错日志：
![d7f8fc085b29ebd4d28e34531b726f7](https://github.com/dataease/dataease/assets/50016789/59e568fb-7a24-45f6-97f9-22a9a6bf3516)
其他截图：
![cea7064f3d8e40020770f7714fa2d7c](https://github.com/dataease/dataease/assets/50016789/6ccd863a-9d55-45ff-a5bc-8b5702040c6b)

![982a1cb78ba9cb662da432bc27c234c](https://github.com/dataease/dataease/assets/50016789/c11bff8c-d764-467a-a312-b78979937fc4)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们尝试优化一下windows系统中的提示，会在后续两个版本内完成优化；
