### ISSUE TITLE
[Bug]【仪表板】过滤组件传参视图，提示有误

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10295]
**DataEase 版本**
v2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
过滤组件直接传参参数，提示类型不一致，如下所示。
![image](https://github.com/dataease/dataease/assets/24768910/92234cc3-8863-471d-8ad2-ab3c86efd499)

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是直接通过提示或添加过滤规则标识（加号）进行创建是吗？目前测试环境没发现你说的这种情况，方便详细说明一下吗？

**Comment by AndroidBaby1** [comment]
非常抱歉，场景没有测试详细。当前这种场景下是必现，我补充一下，具体如下。
1.单独筛选富文本，无异常；
![image](https://github.com/dataease/dataease/assets/24768910/81dfdf89-c53c-4f5c-9803-81afdb839641)

2.单独筛选指标卡，无异常；
![image](https://github.com/dataease/dataease/assets/24768910/8157c93a-4aa0-45dc-a121-5a0088e71c66)

3.大屏中同时存在富文本和指标卡，筛选其中一个都会有以上提示。
![image](https://github.com/dataease/dataease/assets/24768910/c85c66a5-b28f-40af-ace2-7835489a6886)
![image](https://github.com/dataease/dataease/assets/24768910/a8811393-9c3f-4286-ac7b-74bdd36b8139)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
