### ISSUE TITLE
[Bug]【图表】数据大屏过滤组件确定按钮保存失败

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10291]
**DataEase 版本**
v2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
数据大屏过滤组件确定按钮保存失败，详解步骤。

**Bug 重现步骤(有截图更好)**
1.数据大屏插入过滤组件，绑定字段选择指标类型
![image](https://github.com/dataease/dataease/assets/24768910/ef156fd8-114f-4d29-99eb-c1db6e9487c2)

2.选项值来源选择【手动输入】，点击确认，无反应，报错如下
![image](https://github.com/dataease/dataease/assets/24768910/bae8a72b-0388-46a1-9866-90ad6d086e5a)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
