### ISSUE TITLE
[Feature]移动端开发

### ISSUE THREAD

**Issue by ynqjwsm** [dataease/dataease#103]
**请描述您的需求或者改进建议.**
为移动端定制H5页面，可以将报表，图表进行小屏展示（支持多级下钻），支持wechat，dingding等api，可实现认证，报表推送

**Comment by xuwei-fit2cloud** [comment]
我们整体的规划中是会对移动端进行支持的，但移动端上可视化图形的展示和PC端还是有区别的，我们还需要更多的去思考和讨论移动端的具体设计。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0版本会对移动端做支持，请等待1月份版本的发布

**Comment by ynqjwsm** [comment]
邮件已经收到，谢谢。
