### ISSUE TITLE
[Question]最新版本前台和后台只能用localhost访问不能用ip访问是更新加了什么限制导致

### ISSUE THREAD

**Issue by jinlongLiu0** [dataease/dataease#10300]
**请描述您的问题.**
最新版本前台和后台只能用localhost访问不能用ip访问是更新加了什么限制导致跨域了吗
![4145c84c50d7f563dec8a7660042a67](https://github.com/dataease/dataease/assets/120174430/aa4092c8-9155-4115-bf65-d01e0a96be97)

**Comment by biao-lvwan** [comment]
遇到同样问题，求解答，新版本是有什么限制嘛

**Comment by ziyujiahao** [comment]
请问一下是否是最新代码 看一下这里是否一致 
![124](https://github.com/dataease/dataease/assets/42510293/84c6e711-2546-4451-96c6-716e02e61eea)

**Comment by jinlongLiu0** [comment]
是最新的
![1718586451995](https://github.com/dataease/dataease/assets/120174430/b74e1b87-4b99-4227-b55b-8a446ee9c953)

**Comment by fit2cloud-chenyw** [comment]
如果是本地运行请使用v2.7版本，开发版本不是很稳定；请把浏览器清空lolocalStorage再试
