### ISSUE TITLE
[Bug]添加的视频，默认是需要手动点击播放才能播放的，但是网页版本点击播放后，也是没有动静黑屏，手机端点击播放是可以正常播放的

### ISSUE THREAD

**Issue by huangxine** [dataease/dataease#10306]
**DataEase 版本**

V2.7.1
**运行方式(安装包运行 or 源码运行 ?)**
标准安装

**浏览器版本**
Chrome 125版本；火狐、edge浏览器

**Bug 描述**
[Bug]添加的视频，默认是需要手动点击播放才能播放的，但是网页版本点击播放后，也是没有动静黑屏，手机端点击播放是可以正常播放的

**Bug 重现步骤(有截图更好)**
1.
![6e6e8d1e4889470e9690aa703bedecb](https://github.com/dataease/dataease/assets/78218624/7b28d66a-df3b-4124-a6a9-6c9a2e4ed0e9)

2.
![image](https://github.com/dataease/dataease/assets/78218624/297dbf00-9383-4935-86a4-13203861f2b2)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，方便给我们一个你们的测试连接我们看一下吗？因为我们这边的连接是没有问题的，我们需要通过你们的链接做一下分析；
