### ISSUE TITLE
[Feature]横向柱状图支持按照图例调整颜色

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#10309]
DataEase 版本:
V2

**请描述您的需求或者改进建议.**
V1版本支持按照图例设置颜色
<img width="1439" alt="image" src="https://github.com/dataease/dataease/assets/70566485/3f240ce0-42b0-48aa-9d16-b4b279c9fb4a">
V2版本不支持按照图例设置颜色随机，建议增加功能，比较实用
![image](https://github.com/dataease/dataease/assets/70566485/ad823a65-358f-4ae5-aa62-082cf5007ba5)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中支持一下。
