### ISSUE TITLE
[Bug]视频组件网页预览没有声音并且也没有开启声音按钮，手机端预览是可以看到开启声音按钮

### ISSUE THREAD

**Issue by huangxine** [dataease/dataease#10304]
**DataEase 版本**
V2.7.1

**运行方式(安装包运行 or 源码运行 ?)**

标准安装

**浏览器版本**
Chrome浏览器最新版本125.0.*；火狐浏览器；edge浏览器

**Bug 描述**
视频组件网页预览没有声音并且也没有开启声音按钮，手机端预览是可以看到开启声音按钮

**Bug 重现步骤(有截图更好)**
1. 网页预览，视频文件没有声音，并且也没有开启声音按钮
![image](https://github.com/dataease/dataease/assets/78218624/8bc25e88-e250-416d-9021-0cd1805e11a0)

2.手机端展示，可以开启声音
![image](https://github.com/dataease/dataease/assets/78218624/362351b7-a115-42e5-9ed3-41b8c29ee26d)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，起始并不是没有按钮而是目前组件没有根据自身的高度去让视频自适应大小导致的，你拖拽一下将组件的窗口加高就可以看到了，这确实会让使用的时候产生误会，我们讨论一下是否可以将此处优化一下；
![image](https://github.com/dataease/dataease/assets/84372766/ebe74c4c-08db-4f01-91d6-35c89af10a8b)
