### ISSUE TITLE
[Bug]日期选择控件，选得日期后，后台SQL参数中年度错误

### ISSUE THREAD

**Issue by dengfj** [dataease/dataease#10302]
**DataEase 版本**
2.6

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome

**Bug 描述**
日期控件选择 2023-12-31时，返回到后台，变成 2024-12-31

**Bug 重现步骤(有截图更好)**
原因：前端返回的日期格式为 YYYY-MM-DD，后台接收时，只替换了DD为dd，没有将 YYYY替换为 yyyy，
导致SimpleDateFormat格式化时，显示的是该日期对应的星期的 年。

修改：
io.dataease.commons.utils.SqlparserUtils ，将前台传过来的YYYY 再替换为 yyyy
![image](https://github.com/dataease/dataease/assets/54826920/07fd99bd-02b9-49a7-a0fa-3a6b04949df1)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题应该已经在2.8中修复完成了，可以下载新的版本进行体验；
