### ISSUE TITLE
[Feature]视图编辑界面，数据栏和样式栏，能否优化一下明显显示？

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#1030]
视图编辑界面，数据栏和样式栏，能否优化一下明显显示，有些用户以为样式栏就是对应下面的界面框，不知道样式栏可以点击切换。---社区群不愿透露姓名的王先生反应

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 已经调整了显示方式，可以看看
