### ISSUE TITLE
[Feature]支持调用数据填充，播放放音乐mp3或mp4的；场景：我现在这边的场景就是销售有业绩出单了就会需要播放一次，但希望这个是自动更新的

### ISSUE THREAD

**Issue by huangxine** [dataease/dataease#10305]
DataEase 版本:

**请描述您的需求或者改进建议.**
[Feature]支持调用数据填充，播放放音乐mp3或mp4的；场景：我现在这边的场景就是销售有业绩出单了就会需要播放一次，但希望这个是自动更新的

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，需求已记录，但近期还没有开发计划，暂时先关闭。
