### ISSUE TITLE
[Feature]跳转时可以携带过滤器的时间

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#10307]
DataEase 版本:
v1 v2

比如做穿透分析，我选取了一个时间范围，一个项目的数据，然后我发现某个品牌有问题，我需要跳转到品牌明细数据里面，这时候，我是需要把这个仪表板上，筛选器中的值同样带过去的，要不然，就没法定位到问题位置。
所以设定跳转携带维度，还需要携带过滤器的时间。

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前是只带图表的维度值，暂时没有计划支持携带过滤器，联动等传递给图表的值。
