### ISSUE TITLE
[Feature]V1.18.X 能否开发一款支持SAP RFC调用的数据源插件。

### ISSUE THREAD

**Issue by cadcamzy** [dataease/dataease#10303]
DataEase 版本: V1.18.21

**请描述您的需求或者改进建议.**
能否开发一款支持 SAP RFC 函数调用的数据源插件， 在日常仪表屏报表或大屏开发中，调用SAP的数据是非常常见的需求，如果有此插件将会非常大拓展业务场景。

一种是用数据源插件直接显示RFC调用结果，一种是缓存到DataEase的中间表中。

否则现在还需要在另外的数据中台之类的平台上做中间表缓存，再用DataEase处理数据。

希望官方考虑如上需求，谢谢。

**Comment by xuwei-fit2cloud** [comment]
开发插件是没有问题的，但这个插件的原理也是调用SAP RFC，获取到数据后存放在DataEase中间表中，按照您说的第一种方案，直接显示RFC调用结果，这个目前不好支持。因为前端视图的数据展示所需要用到的查询、聚合等操作，后台都是统一使用SQL的方式来处理的。

**Comment by cadcamzy** [comment]
是的， 一般的方案也是采用中间表的方式，查询出来的结果存到Dataease中，并且可设置定时任务来跑这个数据源。

**Comment by xuwei-fit2cloud** [comment]
感谢您的反馈。SAP RFC 插件的需求我们已记录，后续如有其他用户反馈，我们会调整优先级进行排期。
