### ISSUE TITLE
请问默认的dev2.7开发分支调用的是企业商用的Api吗？

### ISSUE THREAD

**Issue by SerMs** [dataease/dataease#10310]
我通过Dev2.7默认分支拉取源码进行本地部署，部署后访问页面提示404，页面无法正常跳转，请求啥都是404，查询问题网友说是因为：API接口调用为企业版功能，不对开源用户开放，想求证一下默认的dev2.7就是走的企业版Api吗？如果是，请问如何修改不走企业版呢？
![816ef05c32af35f04053e9f223fd88fb](https://github.com/dataease/dataease/assets/67584847/85a43283-d4c2-4aa6-aa9c-fcb622be2627)

![f4e414a6577778ac5519192cb7b1eb13](https://github.com/dataease/dataease/assets/67584847/8c50490f-80c7-4d73-8b68-84cc376001a7)

**Comment by ziyujiahao** [comment]
这边做了验证 并没有发现这种情况 处理的方式1.使用无痕默认访问测试一下 可能是之前有企业版的token影响的 2.如果还有请打开F12 -》网络 帮忙贴一下是哪个接口报错

**Comment by SerMs** [comment]
> 这边做了验证 并没有发现这种情况 处理的方式1.使用无痕默认访问测试一下 可能是之前有企业版的token影响的 2.如果还有请打开F12 -》网络 帮忙贴一下是哪个接口报错

 项目运行后，浏览器访问目标接口地址进入首页出现404
![3a20651a9ce3eeeb7df904a97afa1a16](https://github.com/dataease/dataease/assets/67584847/dab0fd66-0dbc-4442-a42b-176560389fe6)
输入账号密码点击登录，后台有响应token，前端不跳转
![74d3348d6e05fb58fb5e0aad90a6a839](https://github.com/dataease/dataease/assets/67584847/2a30daf0-92e8-493a-8c78-e653e8d393c9)
手动修改前端地址后进去系统首页也同样出现404
![d49344e27fdf5c4dc52720540d24c369](https://github.com/dataease/dataease/assets/67584847/7286a205-322a-45a0-8faa-189f4cdb6f50)
404资源如下：DEXPack.umd.js 请求错误走的是 de2api接口，
![457d4ac4e8a5882f01b45b2615e73ab6](https://github.com/dataease/dataease/assets/67584847/8117326c-40f7-4934-92b2-674f0a0ddb61)

另外前端在启动的时候，似乎没有预编译，只有访问接口的时候才会执行前端的编译，vite的插件导致的？还是什么原因？
还有启动之后后台有很多in81的警告

**Comment by fit2cloud-chenyw** [comment]
请确定一下版本，正常情况社区版不会请求DEXPack.umd.js，并且我们使用社区版本v2.7.0源码运行不能复现您所描述的场景！建议您先清空lolocalStorage再确定版本后重试
