### ISSUE TITLE
[Feature]标签显示在最右侧的时候需要优化

### ISSUE THREAD

**Issue by kkljcf** [dataease/dataease#10315]
DataEase 版本:
![image](https://github.com/dataease/dataease/assets/125198800/f1d6f71a-f601-49c7-b8fd-dd0e640f0cf0)
标签显示在最右侧,常规数据都没问题,但是最大的那条数据就会被挤压在图形内部了,应该是不管数据大小,全部都显示在最右侧才合理,也就是需要预留一定的空间显示数值,而不是让横条挤满

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，这是图表的一个比较好的显示效果，目前暂时没有计划进行优化。
