### ISSUE TITLE
[Bug]Excel数据源替换数据报错：上传文件与源文件不一致，请检查文件!

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#10319]
**DataEase 版本**
V2.71

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
最新

**Bug 描述**
Excel数据源替换数据报错：上传文件与源文件不一致，请检查文件!
原因：第一次上传的累计同比增速字段为：0.065，第二次替换数据时上传的累计同比增速字段为：6.5%，则报错：上传文件与源文件不一致，请检查文件!
[月度赢单-替换.xlsx](https://github.com/user-attachments/files/15862540/-.xlsx)
[月度赢单第一次.xlsx](https://github.com/user-attachments/files/15862541/default.xlsx)

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/70566485/17e26deb-a57d-493e-9094-4bf218d8d898)

**Comment by xuwei-fit2cloud** [comment]
这个是因为【累计同比增速】字段，之前是小数，后面改成了百分比。
在v2版本里，百分比目前是按文本处理，所以会有上面的提示。

**Comment by xiebei-l** [comment]
现在除了列名要保证一致，每个列的值的字段类型也需要保持一致吗？

**Comment by xuwei-fit2cloud** [comment]
字段类型决定了我们在创建数据表的时候，这个字段的具体类型，所以是需要保持一致的。

**Comment by xiebei-l** [comment]
好的，明白了
