### ISSUE TITLE
[Feature]图表联动设置图表源字段希望可以多选

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#10322]
DataEase 版本:
v2
A图表 联动 B图表时，A图表可选字段只有维度上的一个字段，如果A图表设置了多层下钻，就无法实现下钻后再联动；
希望 A图表可选的字段是整个数据集的字段，而不是仅仅维度框上的一个字段。
![图片](https://github.com/dataease/dataease/assets/48307752/e6e2ed8e-4060-4850-9028-7ee9ca3f0f10)

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
此处不应该整个数据集可选，而是改为下钻路径中的维度可选即可。
