### ISSUE TITLE
更新到v1.18.21 还是提示导出失败

### ISSUE THREAD

**Issue by yaocanke** [dataease/dataease#10329]
![image](https://github.com/dataease/dataease/assets/89123307/374cf23d-984c-4930-9745-794fef38a659)
![image](https://github.com/dataease/dataease/assets/89123307/01489aca-29ff-4b81-a3f3-250a8f40c816)

**Comment by xuwei-fit2cloud** [comment]
这个是源码开发的吧，本地是不是没有 /opt/dataease2.0/data/exportData 这个目录？

**Comment by yaocanke** [comment]
> 这个是源码开发的吧，本地是不是没有 /opt/dataease2.0/data/exportData 这个目录？

我是在1Panl里安装部署的DateEase
这个路径是固定的吗 还是在哪里配置？

**Comment by BBchicken-9527** [comment]
感谢反馈，按照这个路径手动创建一下就可以了，下个版本会优化1p安装时没有添加这个导出路径的问题；

**Comment by cadcamzy** [comment]
试了建了如上的目录，还是不能导出，1panel里用docker安装的。

**Comment by yaocanke** [comment]
> 试了建了如上的目录，还是不能导出，1panel里用docker安装的。

我安装的是V1.18.21版本，进入容器后，执行下面的命令新建exportData文件夹后，是可以正常导出的。
mkdir -p /opt/dataease/data/exportData

**Comment by BBchicken-9527** [comment]
是的，目前1p脚本已经做了相应的优化，下个版本将会直接创建相应的路径，一不小心和1p小小的联动了一把😂，这个问题我现在是关闭了；
