### ISSUE TITLE
[Bug] LDAP属性不应该分大小写

### ISSUE THREAD

**Issue by xyziven** [dataease/dataease#1032]
**DataEase 版本**
1.3.0

**浏览器版本**

**Bug 描述**
在ldap的属性映射{"userName":"sAMAccountName","nickName":"cn","email":"mail"}中，如果把userName或nickName写成username或nickname，会提示“ldap用户缺失映射属性”：

2021-10-27 22:21:06,178 [qtp1942356772-12237] WARN  org.eclipse.jetty.server.HttpChannel ? - /api/auth/login
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is io.dataease.exception.DataEaseException: ldap用户缺失【userName,nickName】映射属性, 请联系管理员

实际上LDAP本身是不区分大小写的，包括ldap属性。在软件中也不应该区分大小写。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
经讨论，暂时先不做修改
