### ISSUE TITLE
[Feature] LDAP支持组映射

### ISSUE THREAD

**Issue by xyziven** [dataease/dataease#1033]
**请描述您的需求或者改进建议.**

当前ldap用户默认登录后是普通用户。在企业中通常管理员在ldap中都属于一个group，
希望可以将ldap的组映射为组，并为组赋予角色和成员。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
