### ISSUE TITLE
[Feature]仪表板下钻需求

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#10331]
DataEase 版本:
v2.7.1

**请描述您的需求或者改进建议.**
场景描述：第一级数据为4、5、6月的收入指标，通过曲线发现6月收入降低，下钻后查看A、B两个产品的收入数据情况用来定位问题。目前DE只能按月下钻，比如点击6月下钻到A、B产品的数据，但无法同时显示4、5两个月的A、B产品数据，无法将这三个月的A、B指标进行对比，没有其他月份的对比，则无法判断哪里出现的问题，因此希望可以第一层级4、5、6月的收入指标为一个整体，下钻后可以分别显示这三个月的A、B产品数据；以此类推，继续下钻也能保持这样的展现效果。客户反馈Tableau以及很多BI工具都可以实现。（客户目前正在选型，有明确采购意向，此功能是刚需，希望可以实现）

目前DE的效果：从6月下钻后只显示该月的两个产品数据，无法跟4、5两月的产品数据对比，无法直观的发现问题
![image](https://github.com/dataease/dataease/assets/77324661/a8a0e614-0fc0-4e4d-9d3e-d2145759cff1)
![image](https://github.com/dataease/dataease/assets/77324661/22874fa6-6e65-48cf-b0bf-fd3cb77fc526)

期望下钻后的效果基本是这样：
![image](https://github.com/dataease/dataease/assets/77324661/e26e68f8-69e4-431b-b29e-83831ab16845)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，通过6月下钻至第二层级，会将6月作为过滤条件传递给第二层级，因此第二层级只会显示6月份的数据，不显示其他月份，上述场景，建议制作两个图表使用。
