### ISSUE TITLE
[Bug]动态排序图，个别分组下某些维度的指标数据缺失，维度展示但是没有数值，实际是有值的

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#10343]
**DataEase 版本**
1.18.21

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
动态排序图，个别分组下某些维度的指标数据缺失，维度展示但是没有数值，实际是有值的
![image](https://github.com/dataease/dataease/assets/89771514/de6517ca-0987-4d1e-87c6-7d7e110fe946)

另一种表现形式是：
正常动态排序下，个别维度的数值展示与实际不符
![image](https://github.com/dataease/dataease/assets/89771514/e41f3bad-7aca-4f0c-bb05-ee00b5e74502)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，我们正在努力修复中，将会在后续两个版本内完成修复；
