### ISSUE TITLE
[Bug]v1公共链接 iframe 嵌入仪表板后，全屏按钮失效

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#10348]
**DataEase 版本**
1.18.20

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
v1 iframe嵌入仪表板后，全屏按钮失效

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，iframe本身是无法支持全屏的他嵌套在了元素里面；
