### ISSUE TITLE
[Feature]希望能优化下拉树的下级排序

### ISSUE THREAD

**Issue by Xyuncheng** [dataease/dataease#10347]
DataEase 版本:
v1.18.19

**请描述您的需求或者改进建议.**
如图所示：
![59517301b7f14bc1bac4abdd518f550](https://github.com/dataease/dataease/assets/137035261/f0ae146f-ede4-430c-90b7-70651efb3a60)
希望能够进行优化，另外看到 v2 的最新版本暂时还不支持下拉树组件，希望能够尽快支持并且将这一块也考虑进行，感谢！

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，回复请见：
1、下级排序不对的情况，这是按照汉字的排序规则进行排序的，如果排序结果不理想，建议给部门增加排序字段，根据排序字段排序。
2、v2版本的下拉树已经在开发中，预计在7月初发布。
