### ISSUE TITLE
[Bug]数据集被删除后，仪表板中的视图重新选择数据集，仍无法正常显示图表数据

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#10344]
**DataEase 版本**
v1.18.20

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
edge

**Bug 描述**
仪表板原数据集被删除后，回到仪表板中为视图重新选择新的数据集，拖拽好字段后，视图仍无法正常显示图表数据，仍显示报错界面。目前只能复制一个新的视图才可以正常显示，刷新也没有作用。希望可以当重新选择数据集和拖拽字段后，正常显示图表数据。

**Bug 重现步骤(有截图更好)**
1.创建建仪表板，选择数据集，拖拽字段，正常生成图表
2.到数据集模块，将该数据集删除
3.回到该仪表板中，选中任意视图（此时视图已无法正常显示），重新选择一个数据集，拖拽字段后，无法生成图表

重新选择数据集后，仍无法显示图表：
![1718695496923](https://github.com/dataease/dataease/assets/77324661/f415e558-1e0b-40ca-957f-8c593a203089)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前编辑状态出现异常无法恢复当修改并保存后退出编辑即可正常显示，问题为已知问题，我们正在努力修复，将会在后续两个版本内修复；
