### ISSUE TITLE
视图-汇总表-同换比设置-新增日环比、月同比

### ISSUE THREAD

**Issue by 2023fan** [dataease/dataease#10349]
DataEase 版本:V2

**请描述您的需求或者改进建议.**
同换比设置，目前只有日环比、月环比；是否可以加上日环比、月同比

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，请问日期粒度选的是年月日吗？支持的同环比计算和日期的粒度有关。
![image](https://github.com/dataease/dataease/assets/84168063/40d68caf-e674-4eff-b4c1-682e558d0d90)
