### ISSUE TITLE
[Bug]V1版本 地图下钻不生效

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#10351]
![bb801126ca893e2a46365e35118198a6](https://github.com/dataease/dataease/assets/141667200/28eef7d5-21bb-4011-9d5a-ab33bbc7280e)
官方模板中的这个地图下钻不生效
![image](https://github.com/dataease/dataease/assets/141667200/8a561e75-177b-4c45-80b4-9d27a66e3634)
这个官方数据集下钻有问题

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
v1.18.22版本已处理，请更新版本。
