### ISSUE TITLE
[Bug]富文本里面字段配置超链接，链接打开方式选择当前窗口打开，仍然另开新窗口

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#10354]
**DataEase 版本**
V2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器最新

**Bug 描述**
富文本里面字段配置超链接，链接打开方式选择当前窗口打开，仍然另开新窗口

**Bug 重现步骤(有截图更好)**
1.使用富文本，配置字段
![image](https://github.com/dataease/dataease/assets/35896106/b7b8683e-ebf2-4a62-b719-575045dbb75f)
2.选中字段，配置超链接，打开方式选择当前窗口打开
![image](https://github.com/dataease/dataease/assets/35896106/95005265-dc39-4eaa-b0bc-29e99618c4aa)
3.预览仪表板，点击字段，仍然打开新窗口

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，正在努力修复中，我们会在后续两个版本内进行修复；
