### ISSUE TITLE
[Bug]设置定时浏览器刷新的公共链接打开后点击全屏按钮，刷新的时候会退出全屏

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#10359]
**DataEase 版本**

1.18.21
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

谷歌
**Bug 描述**

**Bug 重现步骤(有截图更好)**
设置定时浏览器刷新的公共链接打开后点击全屏按钮，刷新的时候会退出全屏，变成没有全屏。如果是tab页全屏预览，和编辑下的预览不回退出，只有点击公共链接的全屏按钮会。
![image](https://github.com/dataease/dataease/assets/127368807/1fe15b4b-7aec-4594-aad3-0554ca64ec4e)

![image](https://github.com/dataease/dataease/assets/127368807/65368cbf-17dc-4dbf-9a72-bc550c75cec9)
![未命名 (1)](https://github.com/dataease/dataease/assets/127368807/34a68fb2-7521-44af-b63b-f040aceb1896)

**Comment by xuwei-fit2cloud** [comment]
已排期，近期版本会支持。

**Comment by xuwei-fit2cloud** [comment]
只能用客户用浏览器自带全屏，就是手动浏览器全屏，这样的话，自动刷新不会退出全屏。

目前无解。
