### ISSUE TITLE
[Bug]动态排序图，有数据却不显示且排序错乱，并存在负数

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#10358]
**DataEase 版本**
V1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome

**Bug 描述**
动态排序图设置显示10个，有数据却不显示且排序错乱，并存在负数

**Bug 重现步骤(有截图更好)**

https://github.com/dataease/dataease/assets/133861755/4171d873-6425-489d-9f1d-2acaa95d8c65

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
