### ISSUE TITLE
[Feature]图表支持指定排序字段（非展示字段）

### ISSUE THREAD

**Issue by ny0946** [dataease/dataease#10353]
DataEase 版本:
2.7.1

**请描述您的需求或者改进建议.**
目前针对各类统计图或透视表的标签/维度中字段排序只能采用本身字段内容的升序、降序和自定义排序，自定义排序也只能手动根据内容排序
![image](https://github.com/dataease/dataease/assets/141575198/95be18f0-59bc-4be3-bfd0-0c34e5e45a1e)

现在希望排序可以根据本身以外的某个字段来排序，比如说我们有几十个分公司，前端系统时不时会增加或者修改分公司，数据表的结构包含了分公司及一个公司排序字段，再做统计图表的时候希望图表都能按这个公司排序来展示。这个人工手动维护不太现实也不方便。希望增加此功能。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持。
