### ISSUE TITLE
[Bug]v2 移动端苹果手机第一次打开非常慢，并且报错数据不显示，时间过滤组件无效

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#10362]
**DataEase 版本**
2.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
v2 移动端苹果手机打开慢，并且报错数据不显示，时间过滤组件无效

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/101089844/3fa6ba7b-89bb-49c2-8b83-8dc9342843c2)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，是否有什么其他操作？方便的话受累说明一下，并且可以升级到最新版本尝试；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
