### ISSUE TITLE
[Feature]v2版本 在图表中希望支持按中文升降序排列

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#10361]
![image](https://github.com/dataease/dataease/assets/141667200/06c16e97-7577-4a27-9614-5d7d36e11a9a)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，这个是根据数据库设置的中文编码规则进行排序的，并且排序结果和数据库的排序结果保持一致。
