### ISSUE TITLE
[Feature]数据集中的数据预览界面字段显示宽度可以拖拉，位置可以调整，表和字段名称可修改

### ISSUE THREAD

**Issue by ljf-data** [dataease/dataease#10368]
DataEase 版本:V2.6

**请描述您的需求或者改进建议.**
数据集中的数据预览界面字段显示宽度可以拖拉，位置可以调整
![数据集数据预览字段可调](https://github.com/dataease/dataease/assets/173240580/5a446da6-f45c-4a85-99a6-38dc6278b5ea)

**Comment by ljf-data** [comment]
表名称可改
![数据集数据预览表名称可改](https://github.com/dataease/dataease/assets/173240580/26e16ec6-7f86-4573-8b82-4375c9f7e96b)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复如下：
1、数据集预览界面可以调整列宽，已经在v2.8完成，会在7月初进行版本发布。
2、表名和字段名，这里是从数据源中读取的，因此与数据源保持一致，暂时没有计划支持修改。
