### ISSUE TITLE
[Bug]V2tab页内组件批量样式修改，部分设置不生效。

### ISSUE THREAD

**Issue by Linkjie-11** [dataease/dataease#10366]
**DataEase 版本**
V2.7.1/V2.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
edge，火狐，chrome

**Bug 描述**
tab页内组件批量样式修改，部分设置不生效。

**Bug 重现步骤(有截图更好)**
1.初始样式
![image](https://github.com/dataease/dataease/assets/52249559/3fe449a6-e55f-410b-a24e-427f8dd2f179)

2.批量修改背景和指标值颜色
![image](https://github.com/dataease/dataease/assets/52249559/f444d100-0e6f-4ff1-9255-c7cb992a57d3)

3.完成后，点击保存，切换tab页，在回到第一个tab页，指标值颜色修改未生效。
![image](https://github.com/dataease/dataease/assets/52249559/206f4c36-0bf8-4ea4-b33e-b546a615a2fe)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
