### ISSUE TITLE
[Feature]查询组件设置为范围查询时，目前必须要选择开始和结束日期，无法查询一个日期之后或一个日期之前的所有数据

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#10377]
DataEase 版本:

**请描述您的需求或者改进建议.**
查询组件设置为范围查询时，目前必须要选择开始和结束日期，无法查询一个日期之后或一个日期之前的所有数据，希望能够支持。还希望可以单独设置起止时间，目前不能单独设置开始日期和结束日期，当跨度很大的日期查询场景下很难选择开始和结束日期，除非自己手动收入开始日期和结束日期，易用性较差。
![image](https://github.com/dataease/dataease/assets/83771182/2dcf323f-b872-4a05-9580-7daedcec8b7f)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，日期范围组件的使用，开始日期和结束日期是必选，如果需要查询一个日期之前的所有数据，建议开始日期设置的小一些。
