### ISSUE TITLE
[Bug] v2 标题关闭的情况下，备注仍会显示

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#10378]
**DataEase 版本**
v2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 125.0.6422.142（正式版本） (arm64)

**Bug 描述**
v2 标题关闭的情况下，备注仍会显示

**Bug 重现步骤(有截图更好)**
1. 如下所示：
<img width="1005" alt="image" src="https://github.com/dataease/dataease/assets/30063018/5d1abf90-be62-4b24-8c22-545765d62721">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们下个版本修复。
