### ISSUE TITLE
[Feature] 折线图 轴值 自动 配置下，希望基于数据的最小值 和最大值的范围进行自适应展示，加强数据波动的显示效果

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#10381]
DataEase 版本:
 2.7

**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/40597893/874cbc38-3adb-434b-942b-a539df470786)
![image](https://github.com/dataease/dataease/assets/40597893/dcfa39a8-8834-43a7-b7b1-91f54c181df9)
希望在自动场景下，基于数据的的最大值和最小值范围进行自适应展示，增加图标的美观性。
手动设置存在较多的限制，是用体验比较差

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，自动情况下，是图库根据计算结果自动分配轴值的和刻度数，自适应展示的。自定义情况下，可自己定义最大值、最小值，建议您设置后，每个刻度值为整数，这样查阅效果会好一些。

**Comment by lillcol** [comment]
> 感谢您的反馈，自动情况下，是图库根据计算结果自动分配轴值的和刻度数，自适应展示的。自定义情况下，可自己定义最大值、最小值，建议您设置后，每个刻度值为整数，这样查阅效果会好一些。

自动情况下，图库根据计算结果自动分配轴值的和刻度数，看起来并没有自适应展示呀，我最小值 600W 都是直接从 0 开始，这里就损失图标的波动效果了。自己定义存在数据落在设置的范围之外了的情况导致无法显示

**Comment by lillcol** [comment]
> > 感谢您的反馈，自动情况下，是图库根据计算结果自动分配轴值的和刻度数，自适应展示的。自定义情况下，可自己定义最大值、最小值，建议您设置后，每个刻度值为整数，这样查阅效果会好一些。
> 
> 自动情况下，图库根据计算结果自动分配轴值的和刻度数，看起来并没有自适应展示呀，我最小值 600W 都是直接从 0 开始，这里就损失图标的波动效果了。自己定义存在数据落在设置的范围之外了的情况导致无法显示

图库根据计算结果应该是指获取到我实际上数据的计算结果范围吧
