### ISSUE TITLE
[Question]【仪表板】富文本显示异常

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10384]
**请描述您的问题.**
v2.6.1 版本升级到 v2.7.1 版本，出现富文本显示异常情况，如下截图。
其中有关联数据集的富文本显示正常，未关联数据集的富文本显示异常。
感觉富文本这种文字类的图表是不是可以不一定非要带数据库字段呀？
![image](https://github.com/dataease/dataease/assets/24768910/85005a94-ecd5-498a-b4a0-6d48ff4a61d0)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们下一个版本优化一下。
