### ISSUE TITLE
[Feature]建议任务执行记录和列表的任务名称和任务状态调整为非红色

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1038]
**请描述您的需求或者改进建议.**
1.查看任务执行记录时，红色的名称很直接的给人第一直觉是任务出错了，而且也会第一时间吸引注意力在该字段上。但是要再看看才发现任务状态是成功的，并没有报错；
![image](https://user-images.githubusercontent.com/48945409/139183611-b02f4517-9bae-4b57-9b9f-9cb3b43f4811.png)

2.任务列表的任务状态也有此情况，会第一时间吸引到注意力并且产生是否有错误的想法，注意看下发现只是告知“执行结束”的状态。
![image](https://user-images.githubusercontent.com/48945409/139183540-d71918f6-f07b-4b54-bfda-af1d0e206922.png)

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 已调整
