### ISSUE TITLE
[Feature]希望嵌入后的仪表板也能支持全屏展示

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#10385]
DataEase 版本:
2.7.1

**请描述您的需求或者改进建议.**
希望嵌入后的仪表板也能支持全屏展示
![da9eeea838e98bfaf599e1132d8a065](https://github.com/dataease/dataease/assets/83771182/f099bc28-29d8-442d-900d-0e09f1dbfea3)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
div方式嵌入的仪表板在v2.8.0版本中即将支持全屏展示。iframe方式目前不支持，前端可以自行支持一下。
