### ISSUE TITLE
[Bug]中国地图，鼠标悬浮不显示拖拽箭头

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#10389]
**DataEase 版本**
v2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
最新版

**Bug 描述**
中国地图，鼠标悬浮不显示拖拽箭头
![image](https://github.com/dataease/dataease/assets/43403764/ff509a30-c861-448c-99d4-1d7dd20b6762)

**Bug 重现步骤(有截图更好)**
1.中国地图，鼠标悬浮不显示拖拽箭头
![image](https://github.com/dataease/dataease/assets/43403764/475dae4f-582a-4681-b4d5-b2951d9385f7)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，是否有其他的特殊操作方便的话麻烦说明一下，也可以更新到最新版本尝试一下；
