### ISSUE TITLE
[Feature]视图的过滤器中，手动配置的过滤条件时对于日期无法设置当前年度作为条件，希望能支持函数方式获取当前年度

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#10386]
DataEase 版本:
2.7.1

**请描述您的需求或者改进建议.**
视图的过滤器中，手动配置的过滤条件时对于日期无法设置当前年度作为条件，希望能支持函数方式获取当前年度
![dd19daf8282bea57a6123432e80f3fd](https://github.com/dataease/dataease/assets/83771182/07dc46ad-081b-4441-b246-ca0180266ffa)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
需求已记录，如有更多用户反馈同样的需求，我们会排期进行支持。
