### ISSUE TITLE
[Bug]阈值的动态平均值,，小数点后位数未规范

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#10392]
**DataEase 版本**
v1.18.20

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
任意浏览器

**Bug 描述**
阈值的动态平均值出现除不尽的情况，经测试对比发现，v1版本没有针对此情况处理小数点后显示的位数，v2处理为小数点后默认显示4位

**Bug 重现步骤(有截图更好)**
1.设置视阈值或者辅助线的动态平均值
2.某些显示出现除不尽的情况，则平均值的小数点后显示了很多位

v1版本中此平均值小数点后出现了11位：
![1718808582989](https://github.com/dataease/dataease/assets/77324661/8f43ba14-d855-4afa-87b9-b3106b2f92c0)

同样的数据，v2版本中此平均值小数点后出现了4位：
![1718809406959](https://github.com/dataease/dataease/assets/77324661/d2abc3b1-0237-4be6-b6c6-c0a61270c6f3)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，已排期。
