### ISSUE TITLE
[Bug]阈值中不能绑定计算字段

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#10391]
**DataEase 版本**
v1.18.20、v2.7.1**DataEase 版本**
v1.18.20、v2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
任意浏览器

**Bug 描述**
客户觉得我们的固定阈值/辅助线、)动态阈值/辅助线，都不够灵活，想自己制定规则，用公式计算一个新建字段，然后用这个字段来当阈值/辅助线，经测试发现目前v1和v2版本均不支持该功能。

**Bug 重现步骤(有截图更好)**
1.对已有仪表板的数据集中，新建计算字段，如计算某个指标的平均值
2.回到仪表板中，将该新建字段拖入到任意图表或表格类的视图中，可以正显示该字段数值
3.对图表类或表格类的视图设置阈值/辅助线，发现无法使用新建计算字段
新建计算字段：
<img width="611" alt="e82e51948a7a225fb3650868381ddfe" 
src="https://github.com/dataease/dataease/assets/77324661/443a3ca3-8df3-4657-a545-5a070a69e6d8">
将字段拖入图表或表格中：
<img width="925" alt="07236a2e07d366e3082cbf9573546cb" src="https://github.com/dataease/dataease/assets/77324661/c7f89930-aa01-4344-b241-e7ef52ccaa89">
阈值/辅助线中没有该新建计算字段：
<img width="954" alt="5f3f828155cac54ccc1119bb6bc3d10" src="https://github.com/dataease/dataease/assets/77324661/ed746c47-de71-4de5-b9e4-74accffd2219">
<img width="762" alt="95d62d2f348b71f7f3f691b78a5d548" src="https://github.com/dataease/dataease/assets/77324661/5175dfd6-100e-4543-a83f-d8d8e51434b5">

**Comment by xuwei-fit2cloud** [comment]
设计如此，无法支持。
