### ISSUE TITLE
[Bug]环比数据图表无法设置动态阈值

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#10394]
**DataEase 版本**
v1.18.20版本、v2.7.1版本

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
任意浏览器

**Bug 描述**
仪表板中，设置了环比的图表，无法设置动态阈值，设置后未生效

**Bug 重现步骤(有截图更好)**
1.仪表板中，将某个视图的指标数据设置为环比
2.对该视图设置辅助线/阈值，选择动态值，任意选择平均值、最大值、最小值
3.辅助线/阈值都不会在视图上生效

v1版本：
![image](https://github.com/dataease/dataease/assets/77324661/84b13c88-a911-4019-ac10-d58e189ad312)

v2版本：
![image](https://github.com/dataease/dataease/assets/77324661/693cedca-87a4-46a1-96de-6873818d87ac)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前辅助线的动态值无法按照同环比计算后的数据显示辅助线，目前辅助是根据原始数据取进行获取并计算，而同环比的特性目前无法做到动态处理，我们优化一下相对应的提示；

**Comment by xuwei-fit2cloud** [comment]
调整y轴的最大值最小值范围可以展示
