### ISSUE TITLE
[Bug]仪表板中更换视图类型后，样式里的标签位置会自动变成居中

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#10393]
**DataEase 版本**
v1.18.20

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
任意浏览器

**Bug 描述**
仪表板中更换视图类型后，样式里的标签位置原本设置的居上或者居下，都会自动变成居中。经测试部分视图会出现这样的情况，比如先使用基础柱状图，然后切换成堆叠柱状图就会出现此问题，可能因为这些视图标签可以设置的位置是相同的；如果从柱状图切换到折线图就不会出现这个问题。

**Bug 重现步骤(有截图更好)**
1.在仪表板中选择基础柱状图展示图表，设置样式中标签为上，或者下
2.切换图表类型为堆叠柱状图或者分组柱状图等
3.图表中标签的位置会自动变成居中

选择柱状图，设置标签为“上”：
![1718810739666](https://github.com/dataease/dataease/assets/77324661/2a986c03-6c23-4f14-958e-ae501f9080eb)

切换为分组柱状图，标签自动变为了居中：
![1718810739678](https://github.com/dataease/dataease/assets/77324661/d5f3932d-a172-4108-8dec-d8af05aed56d)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内修复完成；

**Comment by maninhill** [comment]
v1 版本目前进入维护阶段，仅修复安全漏洞相关问题。
