### ISSUE TITLE
[Bug]编辑仪表盘跟预览页面不一样，编辑页面没有自适应，预览有自适应

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#10397]
**DataEase 版本**
2.7.1

**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**

谷歌
**Bug 描述**

编辑页面没有自适应，预览有自适应，导致编辑仪表盘跟预览页面不一样

**Bug 重现步骤(有截图更好)**
1.预览界面可以自适应
![1](https://github.com/dataease/dataease/assets/127368807/8bababf7-1ff5-424b-81e2-4f37bb7048d5)
2.编辑界面自适应不好
![2](https://github.com/dataease/dataease/assets/127368807/bc57d9d8-ce50-4312-9d7f-b12e2c4bd315)

3.编辑和预览效果不一样
![image](https://github.com/dataease/dataease/assets/127368807/f3d9c67f-497a-4817-8f1b-c848f3779c60)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将在后两个版本内进行修复；
