### ISSUE TITLE
[Feature]多种数据源支持

### ISSUE THREAD

**Issue by cucy** [dataease/dataease#104]
不支持clickhouse数据源, 能否添加支持clickhouse
https://github.com/edp963/davinci 宜信开源类似组件支持多种数据源

**Comment by xuwei-fit2cloud** [comment]
我们会持续增加对主流数据源的支持，目前在开发中的是Oracle，预计在下一个版本 v1.1.0 中提供支持。

**Comment by darkz1984** [comment]
基本jdbc数据库应该支持方法类似? 求统一支持

**Comment by xuwei-fit2cloud** [comment]
v1.3 版本中已支持ck
