### ISSUE TITLE
[Bug]v1 仪表板上富文本框存在很多，再点击某一个视图进行编辑的时候，富文本框的工具栏会闪一遍

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#10403]
https://github.com/dataease/dataease/assets/141667200/acb3038c-97e1-4d0d-a196-cfb278b80721

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内作出优化；

**Comment by maninhill** [comment]
v1 版本目前进入维护阶段，仅修复安全漏洞相关问题。
