### ISSUE TITLE
[Bug]v2.7.1 导入使用的模板会缩在一个角

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#10401]
![75fd96ab647caa69f0cedc3c42bd1ed](https://github.com/dataease/dataease/assets/141667200/ed807f42-754d-4c00-8722-704d537693d0)
![790b0e02845dabea167049852fcf3d8](https://github.com/dataease/dataease/assets/141667200/12a96835-92e5-41c1-aa84-9f841937fe8c)
![cb5aaebc-652a-430e-872d-8b45691031ed](https://github.com/dataease/dataease/assets/141667200/9c2ac937-0e09-4929-a65b-ea6b46b13a61)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你使用的模版是模版市场导入还是自己上传的？目前测试环境没有发现你说的问题；

**Comment by BBchicken-9527** [comment]
经确认为模版市场部分模版导致，正在尝试修复，将会在后续两个版本内修复并上线；
