### ISSUE TITLE
[Feature]GIS地图是否可以自行上传样式？

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#10408]
DataEase 版本:
V1.18.2
 
**请描述您的需求或者改进建议.**
1.目前GIS地图样式较为固定，是否可以支持在mapbox 或 高德开放平台自行配制的样式上传到DataEase(如样式ID、 token)?
![image](https://github.com/dataease/dataease/assets/133861755/ee40fc90-8de5-480e-b8d2-b4010cc48cd0)

![image](https://github.com/dataease/dataease/assets/133861755/cae13039-1c27-425d-898b-d842a3444cf6)
2.地图点位是否可以自定上传图片
![image](https://github.com/dataease/dataease/assets/133861755/0ec0207b-6569-4568-bf18-10024a0f2955)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们优先在v2版本中进行支持。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
