### ISSUE TITLE
[Bug]v1 oracle数据源 在使用sql数据集时，join union 在嵌套时汇报类型转换错误

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#10400]
![image](https://github.com/dataease/dataease/assets/141667200/277bcacc-522b-4b7e-bcde-97d27801b7ea)

SELECT *
FROM
(SELECT ORDER_ID from ORDER_ITEMS aa join COUNTRIES cc on aa.ORDER_ID = cc.REGION_ID
 where ORDER_ID = '${n1}'
) xx join 
(SELECT 'A' as ff,CUSTOMER_ID,ORDER_ID as ID from ORDERS
UNION
SELECT 'B' as ff ,SALESMAN_ID,ORDER_ID as ID from ORDERS) a 
on xx.ORDER_ID = a.ID

报错：
class net.sf.jsqlparser.statement.select.SetOperationList cannot be cast to class net.sf.jsqlparser.statement.select.PlainSelect (net.sf.jsqlparser.statement.select.SetOperationList and net.sf.jsqlparser.statement.select.PlainSelect are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @68be2bc2)

**Comment by wolf-kingx** [comment]
补充一下 描述不太准确 
![85e242b7118a08fcedd36e4af4b980f](https://github.com/dataease/dataease/assets/141667200/8046b349-cc2c-40b2-a29d-9fd92a889f24)
应该是这种结构，主要是第一个中 where为是变量不可以

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将会在后续两个版本内完成修复；

**Comment by maninhill** [comment]
v2.10-lts 版本已经发布，请在最新版本上面验证，有问题请 re-open。
