### ISSUE TITLE
[Feature]建议在辅助线配置界面提示辅助线数值格式配置方式

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#10416]
DataEase 版本:
 V2.7.1

**请描述您的需求或者改进建议.**
如图，大部分用户不了解如何配置辅助线数值格式，希望能有引导提示
![image](https://github.com/dataease/dataease/assets/30886198/221c4e65-3d83-4503-b267-4ce92253e75b)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，已排期。
