### ISSUE TITLE
[Bug]纵轴默认保留两位小数，但辅助线却使用了原始数据

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#10417]
**DataEase 版本**
v2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
整包

BUG 描述：
在仪表板中添加一个柱状图，纵轴使用一个小数格式指标。添加成功后，使用此指标平均值添加一个辅助线。
期望效果：辅助线格式与纵轴格式一致，都是自动保留两位小数
实际效果：辅助线数值达到了小数点后九位，需要再将纵轴标签格式类型修改为数值才会生效
![image](https://github.com/dataease/dataease/assets/30886198/fe8afe17-97f6-4559-a238-59b2c3cf54c3)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，已排期。
