### ISSUE TITLE
[Bug]V1.18.21 数据集导出报错

### ISSUE THREAD

**Issue by htl258** [dataease/dataease#10410]
**DataEase 版本**
v1.18.21

**运行方式(安装包运行 or 源码运行 ?)**
源码运行（1panel安装的）

**浏览器版本**
EDGE或GOOGLE最新版

**Bug 描述**
数据集导出报错

**Bug 重现步骤(有截图更好)**
1.
![339535085-bae0b01d-cd64-4c53-ae57-73daaa9faf5c](https://github.com/dataease/dataease/assets/131636095/1debb7db-56c5-43c8-8701-f94ba1e93bb3)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，由于你是源码运行，不确定你是否改动和以及打包方式都有可能存在问题，建议你加入我们的交流群，上面有非常专业的同学会实时的回复你的问题，方便你快速并精准的定位到你的问题所在；

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本尽快处理；

**Comment by xuwei-fit2cloud** [comment]
这个应该是不存在导出数据文件的目录导致的，我们和1panel一起处理一下。

**Comment by htl258** [comment]
> 这个应该是不存在导出数据文件的目录导致的，我们和1panel一起处理一下。

1.18.22已正常，谢谢
