### ISSUE TITLE
[Feature]V2版本新增的流媒体组件，希望能够支持h265格式的视频播放

### ISSUE THREAD

**Issue by Aiolimp** [dataease/dataease#10423]
DataEase 版本:

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们并不想通过浏览器插件来支持不同格式的流媒体，所以我们会更推荐使用第三方工具将格式转换成flv。目前并没有相关的支持计划。
