### ISSUE TITLE
[Feature]v1版本 希望支持禁用默认仪表板功能，或者支持默认仪表板各用户之间不能互相看见

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#10422]
不禁用的话，每个用户设置的默认版大家都能看到，admin大老板用起来肯定不舒服。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，默认仪表板的权限是根据如下逻辑显示的：
1、普通用户，可以通过授权的方式，让一部分用户可以看到，另外一部分用户无法看到；
2、admin，是整个系统拥有最高权限的人，即拥有所有的权限，且不可以对其权限做修改。

因此暂时没有计划对这里进行的权限进行修改。
