### ISSUE TITLE
[Feature]移动端预览的时候希望支持和PC端一样的查询数据功能

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#10433]
DataEase 版本:
V2.7.1

**请描述您的需求或者改进建议.**
移动端预览的时候希望支持和PC端一样的查询数据功能

PC的这个查看数据的功能
![image](https://github.com/dataease/dataease/assets/35896106/24d72a36-5264-4d09-80df-f4fa0ce04992)

为什么需要？
1、移动端做的图一般不会显示标签，因为标签多了就会挤压在一起如下图
![image](https://github.com/dataease/dataease/assets/35896106/a1772ddf-fdc3-45a5-9b8a-a3cfeb6a2f7e)
2、如果我想在移动端查看每个指标的数值只能一个个点折点看，如下图
![image](https://github.com/dataease/dataease/assets/35896106/c73d945f-aec8-495d-838d-fede39186573)
3、如果我给视图配置了下钻，那么我点折点的时候会直接下钻，更没法查看指标对应的具体值了

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池中，近期暂时没有计划进行支持。
