### ISSUE TITLE
[Bug]使用Tab页制作的仪表板，在移动端展示有各种问题

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#10430]
**DataEase 版本**
V2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器最新

**Bug 描述**
使用Tab页制作的仪表板，在移动端展示有各种问题
1、整体自适应显示不友好，视图里面的字体大小，图表样式可读性比较差
![image](https://github.com/dataease/dataease/assets/35896106/a8b52993-1a85-4ce1-a904-2317667dd717)

2、使用的富文本字体大小没自适应，文本比较长的显示不全
![image](https://github.com/dataease/dataease/assets/35896106/601f04e3-c711-4087-8f11-b530a1e5e7ee)

2、Tab页的视图无法在移动端编辑页在做调整
![image](https://github.com/dataease/dataease/assets/35896106/e9db3377-1a74-490f-95f0-0ed4cb48d2d9)

**Bug 重现步骤(有截图更好)**
1.使用Tab页组件制作仪表板（Tab页组件里面使用了富文本）
PC端展示效果如下
![image](https://github.com/dataease/dataease/assets/35896106/527c8694-f348-42de-a4d9-c969d306ef23)

2.切换到移动端进行编辑

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在近两个版本内作出优化；
