### ISSUE TITLE
[Bug]【数据大屏】透视表空值置零功能失效

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10444]
**DataEase 版本**
v2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
透视表空值置零功能失效，如截图所示。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/24768910/1d2d1416-d0e4-48b3-ad2c-7ddffde0b97f)

**Comment by BBchicken-9527** [comment]
感谢反馈，透视表收到多个维度拉扯看起来置零失效，实际是因为根本没有那条数据，所以并不存在数据为空；
<img width="1214" alt="image" src="https://github.com/dataease/dataease/assets/84372766/07d25e92-d11a-4be9-88dc-e6e84c3dd823">
