### ISSUE TITLE
[Bug]v1版本 未给用户授权对默认仪表板的管理权限，用户却可以设置默认仪表板

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#10442]
![image](https://github.com/dataease/dataease/assets/141667200/b7084579-9626-484f-9b1c-8c68fe131869)
![image](https://github.com/dataease/dataease/assets/141667200/f6e4e8f7-cd1f-4811-86a9-6941e30a6d2b)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内完成修复；

**Comment by xuwei-fit2cloud** [comment]
v1.18.22版本已处理，请更新版本。
