### ISSUE TITLE
[Feature]希望Mysql数据源支持方式连接，因为de服务器和数据库网路不通，需要通过跳板机连接才行。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#10445]
DataEase 版本:
V2.7.1

**请描述您的需求或者改进建议.**
希望Mysql数据源支持方式连接，因为de服务器和数据库网路不通，需要通过跳板机连接才行。
![fa75afc653a9377c9973b061d2a88cc](https://github.com/dataease/dataease/assets/83771182/700d439b-75b5-40ea-b22c-7081be030a43)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要讨论一下。
