### ISSUE TITLE
[Feature]【图表】分组堆叠柱状图

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10454]
DataEase 版本:
v2.7.1

**请描述您的需求或者改进建议.**
图表看能否支持分组堆叠柱状图，v1 当前有

**Comment by xuwei-fit2cloud** [comment]
v2版本是有分组堆叠柱状图的。
![图片](https://github.com/dataease/dataease/assets/1892127/9eddd33e-eed8-4edf-95c6-72144f13bea8)
