### ISSUE TITLE
[Feature]【图表】组合图支持分组柱状图

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10455]
DataEase 版本:
v2.7.1

**请描述您的需求或者改进建议.**
组合图支持分组柱状图
![image](https://github.com/dataease/dataease/assets/24768910/7057d856-9d66-4a21-9f94-e1914b281a15)

**Comment by xuwei-fit2cloud** [comment]
v2.8.0版本中已支持分组柱线组合图，请等待新版本发布。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，7月初发布的v2.8中会支持。
