### ISSUE TITLE
[Feature]【图表】组合图支持多条折线图

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10456]
DataEase 版本:
v2.7.1

**请描述您的需求或者改进建议.**
组合图支持多条折线图
![image](https://github.com/dataease/dataease/assets/24768910/c569a830-6ce6-4e72-9408-0181d369423f)

**Comment by xuwei-fit2cloud** [comment]
v2.8.0已支持，请等待新版本发布。
