### ISSUE TITLE
[Bug]已保存的数据集-数据预览提示“非企业版支持的最大数据量为【100000】”，点击编辑后无法显示sql

### ISSUE THREAD

**Issue by zgq344929174** [dataease/dataease#10459]
**DataEase 版本**
2.7.1(社区版）

**运行方式(安装包运行 or 源码运行 ?)**
安装包允许

**浏览器版本**
Microsoft Edge 版本 126.0.2592.61 (正式版本) (64 位)

**Bug 描述**

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/24764461/8eb607df-8779-476b-ac86-48800b8855ab)
![image](https://github.com/dataease/dataease/assets/24764461/e0c484eb-4085-4d7f-9493-846f54fad76b)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们近期版本优化一下。
