### ISSUE TITLE
[Feature]DataEase字体设置更小字号

### ISSUE THREAD

**Issue by zjdc** [dataease/dataease#10452]
DataEase 版本: V2.7.1

**请描述您的需求或者改进建议.**
1. 如果图表缩小的话，比如横轴的部分字体会不显示。如下图：
![图片](https://github.com/dataease/dataease/assets/156915989/feef935b-aa28-473b-8b2e-6e9cfbaa161a)
2. 尝试了给横轴字体设置角度，但是觉得不好看。
3. 尝试设置字体的时候，发现最小的字号是10号字体，请问是否可以更新设置更小号字体？

**Comment by xuwei-fit2cloud** [comment]
技术上支持更小字号是没有问题的，但再小的文字看起来可能就很费力了，可能并不是特别合适。
