### ISSUE TITLE
[Feature]【图表】组合图支持堆叠柱状图

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10457]
DataEase 版本:
v2.7.1

**请描述您的需求或者改进建议.**
组合图支持堆叠柱状图
![image](https://github.com/dataease/dataease/assets/24768910/07f7cd37-43a0-4728-a01a-90ccb1d5dbf1)

**Comment by xuwei-fit2cloud** [comment]
v2.8.0已支持堆叠柱线组合图，请等待新版本发布。
