### ISSUE TITLE
[Feature]【图表】透视图树形展示支持设置默认展开还是不展开，当前是默认展开。

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10458]
DataEase 版本:
v2.7.1

**请描述您的需求或者改进建议.**
透视图树形展示支持设置默认展开还是不展开，当前是默认展开。
![image](https://github.com/dataease/dataease/assets/24768910/900032d7-1f08-4fb9-9936-f0d9500a4aca)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，已排期。
