### ISSUE TITLE
[Feature]仪表板排序清空缓存后顺序打乱

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#10468]
DataEase 版本:
v1

仪表板排序应该是在前端排序，清空浏览器缓存，顺序会打乱，这个问题能避免吗？

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
仪表板、大屏等列表排序就是前端排序，我们理解这个操作是低频操作，没有必要做入库操作，目前没有支持的计划。
