### ISSUE TITLE
[Feature]希望视图图例能够支持单独排序，目前图例排序会根据维度排序变化。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#10475]
DataEase 版本:
V2.7.1

**请描述您的需求或者改进建议.**
1、希望视图图例能够支持单独排序，目前图例排序会根据维度排序变化。
![1719223354610](https://github.com/dataease/dataease/assets/83771182/e01c76d5-f29a-4cea-88a4-bf56112d81e8)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，目前暂时没有计划支持图例排序。
如下图所示，分组堆叠排序图，图例是由堆叠项生成的，可以根据堆叠项进行排序，从而实现图例的排序。
<img width="748" alt="image" src="https://github.com/dataease/dataease/assets/84168063/54bbfea0-ea2c-4c0d-a000-a910b0fcfcec">
