### ISSUE TITLE
[Feature]Dataease本身支持其他类型数据库

### ISSUE THREAD

**Issue by yimlin** [dataease/dataease#10470]
DataEase 版本:

**请描述您的需求或者改进建议.**
当前DataEase自身运行在mysql之上，期望开放支持其他数据源，如PostgreSQL或者Apache Derby

**Comment by xuwei-fit2cloud** [comment]
与MySQL语法兼容度高的数据库支持起来会更容易一些。如果要支持多种其他数据库，改动量较大，近期版本暂时还不考虑。我们会在后期的大版本里考虑进行相关改造。
