### ISSUE TITLE
[Bug]v2富文本框 插入表格调整宽度，其他宽度会自动后移

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#10471]
https://github.com/dataease/dataease/assets/141667200/54af108a-f7ea-4d4d-92d9-aaf8779e8e81

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在两个版本内进行优化；

**Comment by xuwei-fit2cloud** [comment]
暂不好处理。
