### ISSUE TITLE
[Feature]支持ES等数据库的kerbors认证

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#1047]
**请描述您的需求或者改进建议.**
建议增加针对使用kerbors登录认证的功能。
谢谢

**Comment by xuwei-fit2cloud** [comment]
目前还不支持，我们会加入到需求列表中。

**Comment by xuwei-fit2cloud** [comment]
目前在v1.11.0版本实现了针对hive的kerberos认证支持，其他数据库的支持再看实际需要了。
