### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by huadisan** [dataease/dataease#10483]
DataEase 版本: v1.18.18

**请描述您的需求或者改进建议.**
组件和组件之间可不可以联动啊，感觉不联动，割裂感很强

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，图表之间是可以设置联动的，如下图所示：
![image](https://github.com/dataease/dataease/assets/84168063/70837108-f2bd-4dcc-b855-8bdfaf5080e5)
