### ISSUE TITLE
[Bug]2.7版本如果明细表设置样式设置列汇总 总计选项 显示按钮切换会出现总计计算出现问题

### ISSUE THREAD

**Issue by zcx992132258** [dataease/dataease#10499]
**DataEase 版本**
2.7

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
谷歌  125.0.6422.142

**Bug 描述**
设置明细表拖入字段，设置样式列汇总，关闭总计显示，再打开总计显示，总计计算显示错误错误，变成字符串相加，不是数字计算了

**Bug 重现步骤(有截图更好)**
1.
设置如下 默认总计是数字计算方式
![image](https://github.com/dataease/dataease/assets/54138798/044112c9-e810-4152-9eb7-56d86eae1420)
![image](https://github.com/dataease/dataease/assets/54138798/cc17c953-d3dd-4681-83d5-abc25ba9889a)
2.
关闭列汇总 总计显示
![image](https://github.com/dataease/dataease/assets/54138798/f1c7e1b5-2067-4cfc-9cb3-abbc1fa6b5d4)
3.
打开列汇总 总计显示 变成了字符串相加
![image](https://github.com/dataease/dataease/assets/54138798/4d0ebf81-efc4-4542-9171-0a06b16de3bd)

**Comment by zcx992132258** [comment]
数据列 / 指标 如果是字符串的话 有总计的话  是不是应该做下限制

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将会在两个版本内进行修复；
