### ISSUE TITLE
[Question] v2 能不能和 v1 一样区分富文本视图和富文本

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#10498]
**请描述您的问题.**
![image](https://github.com/dataease/dataease/assets/45852479/c10e8119-be82-4e47-8eda-995df729d868)
v2 版本新建视图默认绑定数据集，在编辑时没法区分是否使用数据集，能否去除绑定

v2 能否和 v1 一样允许从数据集侧配置过滤组件

**Comment by xuwei-fit2cloud** [comment]
建议为不同的富文本设置不同的名称。
![图片](https://github.com/dataease/dataease/assets/1892127/283abafc-580c-42ab-a24d-c4145a0a0258)
