### ISSUE TITLE
[Bug] 组合图，修改指标显示名称后，图例显示仍不生效

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#10495]
**DataEase 版本**
v2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 125.0.6422.142（正式版本） (arm64)

**Bug 描述**
组合图，修改指标字段显示名称后，图例显示出来的名称不变，仍然为字段原始名称

**Bug 重现步骤(有截图更好)**
如下所示：
![image](https://github.com/dataease/dataease/assets/30063018/e5fc8ebc-d6b4-4c3f-88b9-5a0e0c666f4c)
![image](https://github.com/dataease/dataease/assets/30063018/38cc7320-3a4e-43ee-a368-542e2294e007)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前组合图进行了优化，不会再出现您说的这类问题，可下载最新版本进行体验；
