### ISSUE TITLE
[Bug]定时报告发送邮件时，部分发送成功，部分失败。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#10505]
**DataEase 版本**
V2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrom125

**Bug 描述**
定时报告发送邮件时，部分发送成功，部分失败。

**Bug 重现步骤(有截图更好)**
1.设置定时报告发送，邮件发送方式，部分发送成功，部分失败。
<img width="1240" alt="d5c11a0a85015998bf9924cc931d061" src="https://github.com/dataease/dataease/assets/83771182/7e4962c4-1002-4f22-b7e4-dad4d3fd62ba">
2.查看日志
<img width="1055" alt="6f4bc4a1eee3d4d382a5e6a423d781a" src="https://github.com/dataease/dataease/assets/83771182/6db6c16e-7fbc-46f8-9f16-2e62b2651dd9">
3.查看邮件
<img width="1260" alt="31635a8af2a74ed12b4860a72ff8eeb" src="https://github.com/dataease/dataease/assets/83771182/527e5742-843e-4e57-957f-98a32d746c12">

**Comment by BBchicken-9527** [comment]
感谢反馈，看着是频率太高了，降低执行的频率呢？

**Comment by BBchicken-9527** [comment]
感谢反馈，应该就是频率过高导致同一个任务有正在执行的实例，新实例被打断导致，建议降低任务周期，以保证下次执行上次任务已结束；
