### ISSUE TITLE
[Feature]明细表-高级-滚动设置：开启了滚动设置时，希望可以设置是否在鼠标移入或悬浮到表格上方时停止滚动。

### ISSUE THREAD

**Issue by liuxinxin2020** [dataease/dataease#10502]
DataEase 版本:
2.7.1

**请描述您的需求或者改进建议.**
需求描述：明细表-高级-滚动设置：开启了滚动设置时，希望可以设置是否在鼠标移入或悬浮到表格上方时停止滚动。
解决问题：当用户对滚动中的某条数据感兴趣，需要停留下来进行详细查看时，可以通过某种操作让表格暂时停止滚动。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已加入近期的版本迭代中，相同issue：https://github.com/dataease/dataease/issues/9106
