### ISSUE TITLE
[Bug] 数据集字段类型转换异常

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#10507]
**DataEase 版本**
v2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 125.0.6422.142（正式版本） (arm64)

**Bug 描述**
MySQL 数据源，SQL 数据集， 数据集中，将 yyyyMMdd 格式的文本转日期类型后，显示为空白

**Bug 重现步骤(有截图更好)**
1. 数据集预览如下所示：
<img width="1360" alt="image" src="https://github.com/dataease/dataease/assets/30063018/903e7af3-dce0-400f-840b-d176bd1d17f3">

2. 配置好字段类型转换：
<img width="1478" alt="image" src="https://github.com/dataease/dataease/assets/30063018/a33a46d9-f235-453b-b540-70ce1e5279ed">

3. 数据预览为空
<img width="1415" alt="image" src="https://github.com/dataease/dataease/assets/30063018/caf671c1-d8dc-41f3-bbaf-b155b12073ad">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前最新版本一堆自此进行处理，目前可以正常适应，使用数据库方式：%Y%m%d即可；
