### ISSUE TITLE
[Bug]将数据大屏导出为图片时，未将数据大屏中通过素材添加的边框导出。

### ISSUE THREAD

**Issue by liuxinxin2020** [dataease/dataease#10501]
**DataEase 版本**
2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 
版本 126.0.6478.127（正式版本） (x86_64)
**Bug 描述**
将数据大屏导出为图片时，未将数据大屏中通过素材添加的边框导出。

**Bug 重现步骤(有截图更好)**
1.数据大屏预览部分视图效果：
<img width="474" alt="image" src="https://github.com/dataease/dataease/assets/72063838/8a1dd774-db25-4d79-99a9-27ccef0475a4">
2.导出为图片时的效果（少了边框）
<img width="602" alt="image" src="https://github.com/dataease/dataease/assets/72063838/a689199a-1be4-456a-8416-5b3994e1e843">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现您说的问题，可以尝试升级新环境查看问题是否得到解决，这边先暂时将问题关闭，若依然存在问题可选择将问题打开或在公众群中进行咨询；
<img width="613" alt="image" src="https://github.com/dataease/dataease/assets/84372766/18a81485-3682-4879-b3c9-7f99ca92c019">
