### ISSUE TITLE
[Feature] 仪表板数据导出支持筛选字段

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#10517]
DataEase 版本:
 2.7

 目前导出数据都是全字段导出，有时候不需要这么多的字段，希望可以指定导出的字段
![image](https://github.com/dataease/dataease/assets/40597893/bbf575aa-52e2-44ed-8da0-df2155ee4911)

**Comment by xuwei-fit2cloud** [comment]
目前导出的数据会导出图表中的所有字段，未参与图表制作的字段并不会导出。
后续我们会增加全字段导出，以及数据集数据导出。
数据集数据的导出里，会支持条件导出。

**Comment by lillcol** [comment]
> 目前导出的数据会导出图表中的所有字段，未参与图表制作的字段并不会导出。 后续我们会增加全字段导出，以及数据集数据导出。 数据集数据的导出里，会支持条件导出。

是希望仪表板支持查询结果按需要字段导出，如果每次导出得去调整编辑图表制作字段也太麻烦了

**Comment by xuwei-fit2cloud** [comment]
可以试试v2.10.0版本支持的数据集数据导出功能，可以添加任意的过滤条件。
