### ISSUE TITLE
[Feature]仪表板定时报告如果没有数据就不发送

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#10516]
DataEase 版本:
v2

仪表板定时报告如果没有数据就不发送，避免误判和不必要沟通；
下图是其它产品的功能示例：
![图片](https://github.com/dataease/dataease/assets/48307752/1fda9045-4c43-472d-ae61-f92a87d5f191)

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
我们讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池中，待有更多用户反馈后再做下一步的规划。
