### ISSUE TITLE
[Feature]v1 移动端视图，折点大小能否自适应，目前移动端是无法调整大小的

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#10522]
DataEase 版本:
1.18.21

**请描述您的需求或者改进建议.**
v1 移动端视图，折点大小能否自适应，目前移动端是无法调整大小的,是否可以和pc段保持一致大小。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，移动端的折点是统一的大小，暂时没有计划支持自定义。
