### ISSUE TITLE
[Bug]嵌入式版本，嵌入视图的放大、查看数据功能无法使用，由于无法访问数据导出中心，无法拿到视图导出数据

### ISSUE THREAD

**Issue by lyons-hz** [dataease/dataease#10529]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.点击放大或查看数据之后是空白弹窗
<img width="1424" alt="image" src="https://github.com/dataease/dataease/assets/89773363/004a0d9a-47cd-4b62-83a1-f886efdd9215">

2.无法获取导出数据
<img width="1420" alt="image" src="https://github.com/dataease/dataease/assets/89773363/e4af6dd1-0bf3-4622-a67c-3d6933030112">

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
