### ISSUE TITLE
筛选组件能否支持对聚合后的数据进行筛选

### ISSUE THREAD

**Issue by 2023fan** [dataease/dataease#10530]
DataEase 版本:V2.7.1

**请描述您的需求或者改进建议.**
需求：筛选组件支持对聚合后的数据进行筛选；
应用场景：当通过聚合运算获得了求和、平均值等数据后，筛选组织可以针对聚合后的值进行筛选（目前版本筛选的是数据集层面的数据）

改进建议：可以参看quickBI的这个设计
<img width="590" alt="fece19dfa535382d232f6fca04d8801" src="https://github.com/dataease/dataease/assets/145900305/7bf29ebd-5cc2-4b6d-a00d-6fb9b1c0a896">
<img width="590" alt="fece19dfa535382d232f6fca04d8801" src="https://github.com/dataease/dataease/assets/145900305/7bf29ebd-5cc2-4b6d-a00d-6fb9b1c0a896">
![image](https://github.com/dataease/dataease/assets/145900305/52c5b028-b8b1-4b90-82b2-10b5f8629cb6)
![image](https://github.com/dataease/dataease/assets/145900305/52c5b028-b8b1-4b90-82b2-10b5f8629cb6)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，指标过滤这块我们会做一下优化，目前还没有计划对这个需求做相关支持。
