### ISSUE TITLE
[Bug] v1 AntV 组合图移动端显示异常

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#10548]
**DataEase 版本**
v1.18.21

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 125.0.6422.142（正式版本） (arm64)

**Bug 描述**
v1 AntV 组合图移动端显示异常，折线图折点大小显示异常

**Bug 重现步骤(有截图更好)**
1. 设置组合图折点大小为1，PC端效果如下：
![image](https://github.com/dataease/dataease/assets/30063018/9c398d83-e289-4510-8fea-9bb6800ff2fc)

2. 移动端效果如下：
![image](https://github.com/dataease/dataease/assets/30063018/f189674a-cd8b-49c8-8a0e-25bb08d9730f)

3.修改折点大小，移动端的折点大小也不受控制。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前v1的移动端显示折点的大小都是固定了大小的，是不支持再设置的；
