### ISSUE TITLE
[Bug]数据大屏流媒体无法播放

### ISSUE THREAD

**Issue by Seelly** [dataease/dataease#10547]
**DataEase 版本**
v2.7

**运行方式(安装包运行 or 源码运行 ?)**

安装包运行
**浏览器版本**
chrome 版本 126.0.6478.116（正式版本） （64 位）

**Bug 描述**
使用的是西瓜视频测试视频https://sf1-cdn-tos.huoshanstatic.com/obj/media-fe/xgplayer_doc_video/flv/xgplayer-demo-720p.flv
流媒体组件无法播放报错如下，但是用官方的在线预览能播放
index-0.0.0-dataease.js:1 never mind this error about '/xpackComponent/content', just a reminder to support the official license

Uncaught (in promise) 缺少许可证
video.js-0.0.0-dataease.js:11 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) 此视频暂无法播放，请稍后再试 
Fe {code: 4, message: '此视频暂无法播放，请稍后再试'}

**Bug 重现步骤(有截图更好)**
1.新建数据大屏
2.添加流媒体组件，添加链接
3.报错

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你的问题，你这个问题是必现的吗？
![image](https://github.com/dataease/dataease/assets/84372766/bacba521-a916-4267-a4bb-b6c0382ba860)

**Comment by ziyujiahao** [comment]
需要注意的事 如果系统是http链接 是不能播放https的链接的视频的

**Comment by Seelly** [comment]
是必出现的，本地是没用https，可能是这个原因造成的
