### ISSUE TITLE
[Bug]编辑状态下首次加载时因多个筛选组件因层级问题使接口携带过滤参数不符

### ISSUE THREAD

**Issue by zwbcc** [dataease/dataease#10552]
**DataEase 版本**
官网版本

**运行方式(安装包运行 or 源码运行 ?)**
官网

**浏览器版本**
chrome 109.0.5414.120

**Bug 描述**
编辑状态下第一次加载时，获取视图组件的接口会因多个筛选组件的层级问题使接口携带过滤参数filters 里面数据不符

**Bug 重现步骤(有截图更好)**
1.
![1719457011806](https://github.com/dataease/dataease/assets/41459254/628cbd55-c5e9-4ca7-bf09-28db37ecf031)
2.
![1719457175969](https://github.com/dataease/dataease/assets/41459254/ec69982c-34f2-4f60-90b8-7fb3acf018ca)

3.

**Comment by zwbcc** [comment]
筛选组件都设置了默认值

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是设置了三个组件查看接口发现只有两个生效了是这个意思吗？

**Comment by zwbcc** [comment]
是的，在点击编辑的首次加载会出现这个情况



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月8日(星期一) 上午10:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dataease/dataease] [Bug]编辑状态下首次加载时因多个筛选组件因层级问题使接口携带过滤参数不符 (Issue #10552)














 
感谢反馈，你的意思是设置了三个组件查看接口发现只有两个生效了是这个意思吗？

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，可以使用最新版本再尝试一下；
![image](https://github.com/user-attachments/assets/b4419575-b51a-43db-adea-cc95651970d5)

**Comment by zwbcc** [comment]
> 感谢反馈，目前测试环境没有发现你说的问题，可以使用最新版本再尝试一下； ![image](https://private-user-images.githubusercontent.com/84372766/348642848-b4419575-b51a-43db-adea-cc95651970d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2OTkyMDUsIm5iZiI6MTcyMTY5ODkwNSwicGF0aCI6Ii84NDM3Mjc2Ni8zNDg2NDI4NDgtYjQ0MTk1NzUtYjUxYS00M2RiLWFkZWEtY2M5NTY1MTk3MGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDAxNDE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MTEyOGM5NjVmMzk2NWUyZjZjNGI0NWEzMTgyNGY2MjNkNjBiNGE3ZjI1MTZhODI2YjdhN2IwYTRhMmY0ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cK0CIDA2dnzN2Zs20T4GsLMBgJQ89Gp9a3AN4NdN4Fk)

视图组件和查询组件都在悬浮条件下，且查询组件的层级比视图组件层级靠后，此时点击编辑后的首次加载，层级靠后的组件不生效。
![1721700061875](https://github.com/user-attachments/assets/5d9c357c-2592-4b61-af3c-0fc6cba52cf6)

![1721699320482](https://github.com/user-attachments/assets/d09d3f47-91dd-41e6-8501-14e916746361)

**Comment by zwbcc** [comment]
也不用非要悬浮状态下，只要 panel/group/findOne 这个接口里 panelData 数据中，比视图数据的排序靠后的组件数据就会出现这个问题，简单复现： ①：先拉一个 下拉组件设置默认值，②：在拉一个视图，③：在拉一个下拉组件设置默认值，保存后退出，再点击编辑后首次加载，③步骤拉的组件失效。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
