### ISSUE TITLE
部分功能使用建议

### ISSUE THREAD

**Issue by github-tsg** [dataease/dataease#10562]
DataEase 版本:V2
1.建议批量编辑设置“全选”功能
 
![image](https://github.com/dataease/dataease/assets/146046004/e3685a6c-e76c-4d74-b6a1-c3b6689567e0)

2.建议配色方案像PS一样，可以有“自定义”保存功能
 
![image](https://github.com/dataease/dataease/assets/146046004/548b3b82-375e-44a1-bd89-010e1b993336)

3.地图图例能否设置位置以及自定义数值？
![image](https://github.com/dataease/dataease/assets/146046004/55f4a7a6-2428-43f7-b37a-8853b3dee782)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复如下：
1、建议在仪表板的主题中设置公共的样式。
2、暂时没有计划支持配色方案的保存。
3、自定义图例的数值，已经在v2.8中进行了优化，下周四会进行版本发布，可以先试用看看；自定义位置，我们先记录下需求。
