### ISSUE TITLE
[Question]SQL 数据集外部参数功能添加相关注释

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10579]
**请描述您的问题.**
当前对于【数据集预览时全局生效】以及【仅编辑时生效】的相关概念前端用户混淆情况较多，故是否考虑在如下截图标注出添加相关注释，注释如图中标注。
![image](https://github.com/dataease/dataease/assets/24768910/c0700a5a-78b2-493a-8aa5-e6f69d0dcf13)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，目前的提示中已经说明，此处设置的参数值，仅在数据集编辑或者预览时生效。
