### ISSUE TITLE
[Bug]-dataease不同数据集不定时同步失败-

### ISSUE THREAD

**Issue by qqinc** [dataease/dataease#10574]
**DataEase 版本**
1.18.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 126.0.6478.127

**Bug 描述**
dataease设置数据集定时更新，无规律的偶发失败

![image](https://github.com/dataease/dataease/assets/20720886/495e2c98-05b8-4d8d-9bfc-13bd9448ffad)

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/20720886/9d4af259-9fbd-4401-b6e2-66208d72a699)

**Comment by qqinc** [comment]
![Uploading 企业微信截图_17194856163384.png…]()

**Comment by BBchicken-9527** [comment]
感谢反馈，emm不定时同步是什么意思？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
