### ISSUE TITLE
[Question]【仪表板】SQL 数据集逻辑调整，整个仪表板都要再调整一遍，可否能够优化自动识别能力？

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10585]
**请描述您的问题.**
SQL 数据集逻辑调整（新增字段、调整原字段逻辑但是不改变字段名），整个仪表板的图表的一些字段都要再调整一遍，可否能够优化自动识别能力？有时候一个仪表板用的同一个数据集，但是二三十个图表都要调整一遍，尤其是图表过滤器设置，有时一个图表设置好几条过滤条件，字段逻辑调整罢了，结果整个过滤条件都要重新配置一遍，这个不知道可否优化，感谢。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复如下：
1、「SQL片段中新增字段」已经在v2.8中进行优化，不需要再对之前的图表进行字段调整；
2、「SQL片段中调整原字段逻辑不改变字段名」，图表中字段标红需要重新配置，请问字段类型前后有变化吗？

**Comment by AndroidBaby1** [comment]
感谢，第二点目前字段类型没有变化，但是确实还存在需要重新拉入的情况。具体可以等 v2.8 版本更新之后再测试情况，做一个具体反馈。

**Comment by yayanpei-fit2cloud** [comment]
好的，如果字段名称没有发生变化、字段类型也没有发生变化，是不需要重新拉入的。
