### ISSUE TITLE
[Feature] 支持对接多个企业微信

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#10587]
DataEase 版本:
v1 / v2

**请描述您的需求或者改进建议.**
客户公司有这个场景，企业微信是事业部管理的。每个事业部都有自己的企业微信。希望 DataEase 可以按照组织配置不同的企业微信。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论下。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，目前暂时没有计划对接多个企业微信。
