### ISSUE TITLE
[Bug]柱状图基础样式配色方案没有生效，所有柱子都是同一个颜色。

### ISSUE THREAD

**Issue by lyons-hz** [dataease/dataease#10589]
**DataEase 版本**
2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
125.0.6422.142（正式版本） (arm64)

**Bug 描述**
柱状图基础样式配色方案没有生效，所有柱子都是同一个颜色。

**Bug 重现步骤(有截图更好)**
1.设置柱状图基础样式配色方案没有生效，所有柱子都是同一颜色。
![image](https://github.com/dataease/dataease/assets/89773363/145be087-24ac-41ec-85a6-901566621906)

2.不同的颜色更有视觉效果。
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，并不是配色方案没有生效而是目前你所有的数据都是统计各个地区的人数，都是人数所以显示第一个颜色红色，你多加几个指标就看出颜色的变化了；
