### ISSUE TITLE
[Bug] v2 数据大屏跑马灯组件使用空格后展示出现转义字符

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#10597]
**DataEase 版本**
v2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌

**Bug 描述**
跑马灯文本出现空格

**Bug 重现步骤(有截图更好)**
在跑马灯里文字中穿插空格，保存并展示
![chrome_TEX4V5I4Pp](https://github.com/dataease/dataease/assets/163749505/bc4fbd71-9f91-4343-855c-4d4991c79fd0)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。
