### ISSUE TITLE
[Feature] v2 表格视图支持横竖格子线分别隐藏

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#10609]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
如下图表格支持横竖格子线**分别**隐藏，如下图单独隐藏了竖线
![image](https://github.com/dataease/dataease/assets/163749505/12088a06-35bb-43dc-82a6-31023cfda634)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先看下图库是否支持。
