### ISSUE TITLE
[Bug] v2 版本查询组件不能多个视图关联同一个动态参数（之前可以）

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#10602]
**DataEase 版本**
v2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
自定义 SQL 使用动态参数
在仪表板中新建查询组件
选择同一个数据集中的动态参数，不能查询多个图表（之前版本可以，或者之前创建的查询组件也没问题）
点击确认会报错，保存不成功，如下图
![image](https://github.com/dataease/dataease/assets/163749505/0edd50f7-e288-43bc-898a-ba8bcc9614da)

**Bug 重现步骤(有截图更好)**
1.步骤同上，先创建数据集，带动态参数
![image](https://github.com/dataease/dataease/assets/163749505/9b6690d8-8e32-4ed9-86bd-8398c465028d)

2.先用该数据集创建多个视图，再选择查询组件，选择多个视图使用动态参数
![chrome_MFSCNALk9J](https://github.com/dataease/dataease/assets/163749505/1b899621-20e5-46fe-847b-b3a024771dd9)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题应该已经在最新版本上得到了修复，可以下载体验；
