### ISSUE TITLE
[Feature]希望在一个视图内，既有列表也有柱状图，类似Excel表形式，可以根据所选列表内容自动更新柱状图。而不是现在已有的联动功能。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#10619]
DataEase 版本:
V2.7.1

**请描述您的需求或者改进建议.**
希望在一个视图内，既有列表也有柱状图，类似Excel的形式，可以根据所选列表内容自动更新柱状图。而不是现在已有的联动功能。
![image](https://github.com/dataease/dataease/assets/83771182/852e805a-6db1-416e-ba71-bf276d6386bd)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，图库不支持，因此暂时没有计划支持。
