### ISSUE TITLE
[Question]【认证配置】OIDC 登录优化

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10614]
**请描述您的问题.**
OIDC 登录可否省略要点击 OIDC 按钮才可实现登录的问题。加入类似如下的设置。
![image](https://github.com/dataease/dataease/assets/24768910/d22cc8f2-3763-41af-ab0e-c2e0754e11f0)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。
