### ISSUE TITLE
[Feature]地图组件增加经纬度点位标记！

### ISSUE THREAD

**Issue by sunhangwei** [dataease/dataease#10615]
DataEase 版本:2.7.1

**地图组件增加经纬度点位标记！.**

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，请问是这个地图吗？
![image](https://github.com/dataease/dataease/assets/84168063/75c3af08-4fcd-474c-ae90-b4ca622a34ca)

**Comment by xuwei-fit2cloud** [comment]
可以使用符号地图。
