### ISSUE TITLE
[Bug]创建密码分享链接失效，输入密码后报错

### ISSUE THREAD

**Issue by shancuser** [dataease/dataease#1061]
**DataEase 版本**

v1.13.0企业版
**浏览器版本**
版本 94.0.4606.54（正式版本） （32 位）

**Bug 描述**
仪表板创建分享链接，复制链接及密码，新浏览器打开，报错，内容如下所示
![image](https://user-images.githubusercontent.com/86365242/139543031-5a0eaf1c-7968-4652-a91e-4194baa828cf.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，此问题已修复，请等待1.4.0 版本发布
