### ISSUE TITLE
[Feature]希望仪表板跳转功能可以根据查看人的权限进行设置，可设置不同权限的人跳转到不同仪表板。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#10620]
DataEase 版本:
V2.7.1

**请描述您的需求或者改进建议.**
希望仪表板跳转功能可以根据查看人的权限进行设置，可设置不同权限的人跳转到不同仪表板。例如A权限和B权限看到的是同一个列表视图点击跳转看到的是不同的仪表板内容

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划进行支持。
