### ISSUE TITLE
[Feature]希望列表视图每列都能单独设置颜色字体，支持单元格合并，内置展示迷你视图，支持图片直接显示在表中，而不是显示URL。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#10621]
DataEase 版本:
V2.7.1

**请描述您的需求或者改进建议.**
希望列表视图每列都能单独设置颜色字体，支持单元格合并，内置展示迷你视图，支持图片直接显示在表中，而不是显示URL。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复如下：
1、支持单独设置每列的颜色字体，我们先记录下需求，透视表应该支持不了，透视表的列不固定，和字段值有关。
2、单元格合并，透视表已经支持，汇总表我们先记录下需求，明细表展示数据明细，因此没有计划支持。
3、内置展示迷你视图，目前暂时没有计划支持。
4、表格中展示图片，该需求已经记录在需求池中。
