### ISSUE TITLE
[Feature]希望在数据源设置时增加类似数据集的行列权限功能。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#10625]
DataEase 版本:
V2.7.1

**请描述您的需求或者改进建议.**
希望在数据源设置时增加类似数据集的行列权限功能。例如一个saas系统的数据库，里面有很多单位的客户，希望可以在连接数据源就按不同单位的DE账号权限区别数据。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，近期暂时没有计划支持。
