### ISSUE TITLE
[Feature]创建视图时，能不能对已经存在的字段进行二次修改

### ISSUE THREAD

**Issue by shancuser** [dataease/dataease#1063]
**请描述您的需求或者改进建议.**
1、创建视图选中数据集，勾选完成后 想对一些字段进行修改
2、我们产品现在支不支持，还是本人操作问题，没有找到实现该方式的方法
![image](https://user-images.githubusercontent.com/86365242/139543394-5805e32e-d655-4579-9c33-bc5690a5d0ef.png)

**Comment by shancuser** [comment]
如上所示，想对CPU字段写入文字、数字，但是无法写入

**Comment by yayanpei** [comment]
感谢您的反馈，产品目前不支持对视图的数据进行编辑。
