### ISSUE TITLE
[Bug]查询过滤组件自定义时间显示不全

### ISSUE THREAD

**Issue by Linkjie-11** [dataease/dataease#10647]
**DataEase 版本**
2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
docker

**浏览器版本**
edge

**Bug 描述**
![企业微信截图_17198049666410](https://github.com/dataease/dataease/assets/52249559/4388d8af-1cbf-45fc-a5e9-b49ba79e2c3f)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，是不是窗口缩的比较小？
![image](https://github.com/dataease/dataease/assets/84372766/9b4b3b5d-b507-4cd8-af0a-fde8a60e798f)

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
