### ISSUE TITLE
[Feature]【认证对接】OIDC 协议对接 Realm 支持非必填

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10641]
DataEase 版本:
v2.7.1

**请描述您的需求或者改进建议.**
OIDC 协议对接 Realm 支持非必填。目前 Dex 并不使用 realm 这个概念。Dex 专注于简化的身份认证和授权，不提供像 Keycloak 那样复杂的多租户或多域管理功能。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先调研一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们在近期的版本中支持一下。
