### ISSUE TITLE
[Feature]移动端时间区间组件显示优化

### ISSUE THREAD

**Issue by Linkjie-11** [dataease/dataease#10646]
DataEase 版本:
2.7.1

**请描述您的需求或者改进建议.**
![图片](https://github.com/dataease/dataease/assets/52249559/c9c9b9a1-adf0-4938-a194-b1003239ec64)
移动端筛选组件时间区间显示无法调整。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前的组件还需要再优化，我们先记录进需求池中，建议先将查询条件的名称显示在组件上侧，这样显示效果稍微好一些。
![image](https://github.com/dataease/dataease/assets/84168063/fdccd8af-441c-4570-92c0-7721c36bab99)

**Comment by xuwei-fit2cloud** [comment]
请更新版本。
