### ISSUE TITLE
[Feature]支持矩阵热力图

### ISSUE THREAD

**Issue by heddawx** [dataease/dataease#10689]
DataEase 版本:

**请描述您的需求或者改进建议.**
能否增加表示相关性的图表，例如矩阵热力图：
![微信图片_20240702111435](https://github.com/dataease/dataease/assets/48548653/ebb61b6d-c243-4fcf-9ceb-09c880c16673)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，已记录需求池，等待后续排期。
