### ISSUE TITLE
[Bug]前端打包问题

### ISSUE THREAD

**Issue by MrZhangWeiCe** [dataease/dataease#10682]
**DataEase 版本**
v2.6.0
**运行方式(安装包运行 or 源码运行 ?)**
yarn build:base

前端打包报错，会找别的目录的文件，只能把前端项目放到系统根目录才能打包成功
<img width="1354" alt="image" src="https://github.com/dataease/dataease/assets/29146229/3875a960-063f-45e4-b0e4-a79b1e7b1929">
<img width="1447" alt="image" src="https://github.com/dataease/dataease/assets/29146229/5459a84e-4641-4e15-8f6d-5d748717a420">

**Comment by xuwei-fit2cloud** [comment]
我们本地拉取了2.6的代码，并没有复现您说的问题。
您是不是在dataease的工程下面新建了前端项目？
或者您升级一下代码到v2.7分支试试？

**Comment by MrZhangWeiCe** [comment]
> 我们本地拉取了2.6的代码，并没有复现您说的问题。 您是不是在dataease的工程下面新建了前端项目？ 或者您升级一下代码到v2.7分支试试？

没有新建项目，不知道为什么会找别的目录下的前端项目，必须放到电脑根目录才能打包成功，系统是 macos14.5  node版本 v20.9.0

**Comment by maninhill** [comment]
这个还得你自己再排查排查。

**Comment by RazzzeWang** [comment]
v2.10.0同样的问题

**Comment by GuitarHusky** [comment]
> > 我们本地拉取了2.6的代码，并没有复现您说的问题。 您是不是在dataease的工程下面新建了前端项目？ 或者您升级一下代码到v2.7分支试试？
> 
> 没有新建项目，不知道为什么会找别的目录下的前端项目，必须放到电脑根目录才能打包成功，系统是 macos14.5 node版本 v20.9.0

windows也是这样的  rollup去检测外部目录文件去了

**Comment by GuitarHusky** [comment]
临时解决方案，可参考：
src/components/plugin/src/index.vue
``` javascript
const importProxy = (bytesArray: any[]) => {
  try {
    const pathParts = bytesArray.slice(6, 11).map((item: any) => formatArray(item))
    const relativePath = pathParts.join('/')

    // 确保路径不会回溯到项目外部
    if (relativePath.includes('../') || relativePath.startsWith('/')) {
      console.error('Invalid plugin path:', relativePath)
      showNolic()
      return
    }

    const promise = import(`../../../../../${relativePath}.vue`)
    promise
      .then((res: any) => {
        plugin.value = res.default
      })
      .catch(e => {
        console.error(e)
        showNolic()
      })
  } catch (error) {
    console.error('Failed to import plugin:', error)
    showNolic()
  }
}
```
