### ISSUE TITLE
[Bug]【同步管理】同步数据逻辑错误

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10693]
**DataEase 版本**
v2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
同步数据时，创建的表名和目标库存在相同表，点击确定的时候会提示存在同名表；但是再次点击，则会确认成功，且会删除原表，重新建表。如下视频所示。

https://github.com/dataease/dataease/assets/24768910/f2b2848e-bdbf-4d7c-9916-193f27ba606b

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内修复；
