### ISSUE TITLE
[Bug] 默认普通用户角色权限过大问题

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#10691]
**DataEase 版本**
v2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
离线安装

**浏览器版本**
最新版

**Bug 描述**
普通用户权限问题：
（1）默认普通用户的权限太大了，登录后可以看到组织管理员创建的所有仪表板、数据源、数据集；
（2）普通用户登录之后不能新建仪表板，只能查看，没有新建功能；管理员还需要重新创建一个角色，然后自定义权限才行，比较影响用户体验；

**Bug 重现步骤(有截图更好)**
1.创建李四，角色普通用户
![image](https://github.com/dataease/dataease/assets/43403764/c6f4312d-8bf7-4b83-8bcf-8bbc6410b4d8)

2.李四账号的登录
![image](https://github.com/dataease/dataease/assets/43403764/070bf025-8fad-44a7-8dc7-cadea0281d06)
![image](https://github.com/dataease/dataease/assets/43403764/a7058d94-b776-46ff-a461-20505178af00)
![image](https://github.com/dataease/dataease/assets/43403764/e65502b0-71d6-442d-8d4a-41dcc14eb33d)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，系统的内置角色如果权限不合适，建议新增自定义角色。
