### ISSUE TITLE
插入文字过多保存后文字丢失

### ISSUE THREAD

**Issue by huguangya** [dataease/dataease#1070]
**DataEase 版本**
V1.3.0

**浏览器版本**
谷歌

**Bug 描述**
如图，插入文本，输入了有10条数据但是保存后只有一条
![image](https://user-images.githubusercontent.com/54281046/139575529-5b748bc1-4de1-45b3-a12b-bb6c1b7f50e9.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们排查一下。

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 已修复。
