### ISSUE TITLE
[Feature]地图地名字段去除空格

### ISSUE THREAD

**Issue by dragonhaimax** [dataease/dataease#1072]
**请描述您的需求或者改进建议.**
数据集中地区的字段名，去除空格。否则无法正确关联地名

![image](https://user-images.githubusercontent.com/18454230/139575850-d63529ce-7d7f-4419-9562-824bb68b6cfc.png)
![image](https://user-images.githubusercontent.com/18454230/139575866-cd1fc3ad-9048-4890-b213-ac5573350388.png)

**Comment by xuwei-fit2cloud** [comment]
由于这是数据内本身自带的空格，目前我们不做处理。
后续可以考虑对导入进来的数据集字段增加一些操作，如去除空白、分割等。
