### ISSUE TITLE
[Bug]嵌入de，点击de菜单打开新的页面时，网页title有一瞬间还是线上咱们的产品名字，已经修改了所有白标信息

### ISSUE THREAD

**Issue by huangxine** [dataease/dataease#10721]
**DataEase 版本**

v2.7
**运行方式(安装包运行 or 源码运行 ?)**

标准安装
**浏览器版本**
Chrome

**Bug 描述**

嵌入de，点击de菜单打开新的页面时，网页title有一瞬间还是线上咱们的产品名字，已经修改了所有白标信息
**Bug 重现步骤(有截图更好)**
1.
2.
![image](https://github.com/dataease/dataease/assets/78218624/b81326a9-b62b-4ce5-bcdb-1318df2893db)

3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
试试2.8版本。
嵌入式模式下v2.8现在都是内部打开，不是window.open。
