### ISSUE TITLE
[Feature]明细表优化建议

### ISSUE THREAD

**Issue by cy414933307** [dataease/dataease#1073]
1.明细表左下角的【共*条数据 10条/页】，增加隐藏/显示开关
2.明细表的每一列可以设置条件格式，如图[https://s3.bmp.ovh/imgs/2021/10/944e877b258afd6a.jpg]

**Comment by xuwei-fit2cloud** [comment]
感谢建议，我们会考虑加上支持。

**Comment by xuwei-fit2cloud** [comment]
v1.12.0已支持。
