### ISSUE TITLE
[Feature]建议明细表支持自定义列宽，如图第一列信息展示不全

### ISSUE THREAD

**Issue by huguangya** [dataease/dataease#1074]
**请描述您的需求或者改进建议.**
![0180bb6a6ffe402b0f8ca373293e843](https://user-images.githubusercontent.com/54281046/139591708-549da0df-9dbf-44e4-b65f-d90c1819af2c.png)
![f4c2b01782c6dedc9134878b3695984](https://user-images.githubusercontent.com/54281046/139591726-35eb7ad6-45d2-4a72-858d-202b9d034fc3.png)

**Comment by xuwei-fit2cloud** [comment]
明细表类型的视图目前样式支持不完全，后续会支持单元格大小调整等。
