### ISSUE TITLE
[Feature]建议明细表列支持居中

### ISSUE THREAD

**Issue by huguangya** [dataease/dataease#1075]
**请描述您的需求或者改进建议.**
![fe771a4d1f394c0f77959a40f32e330](https://user-images.githubusercontent.com/54281046/139591747-a32d25f6-066f-4648-baf6-0ef557dc26fb.png)

**Comment by xuwei-fit2cloud** [comment]
需要对明细表增加更多的样式支持。

**Comment by xuwei-fit2cloud** [comment]
v1.8.0 已支持，请关注
