### ISSUE TITLE
[Feature] v2 SQL 参数配置界面，参数类型下拉框显示完整列表，移除滚动条。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#10758]
DataEase 版本:
v2.7.1

**请描述您的需求或者改进建议.**
收到过很多次反馈，参数不支持 年月日，实际上是滚动条不太明显，这个地方的下拉项不多，是否可以移除滚动条？
![image](https://github.com/dataease/dataease/assets/30063018/bcba1eb0-9c7e-4e8f-a183-c9e6a49eb933)

**Comment by xuwei-fit2cloud** [comment]
我们优化一下。
