### ISSUE TITLE
[Bug]平台对接点击的企业微信，但是显示的是钉钉设置

### ISSUE THREAD

**Issue by jstbw** [dataease/dataease#10764]
**DataEase 版本**

2.8
**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**

**Bug 描述**
打开系统设置对接企业微信，但是显示的是“钉钉设置”

![image](https://github.com/dataease/dataease/assets/66759501/e4817ad0-155d-4fbf-83ad-acab0dcf3e10)
![image](https://github.com/dataease/dataease/assets/66759501/d9cedfae-d410-49c7-9d25-4fb221767287)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下。
