### ISSUE TITLE
[Feature]建议支持自定义元素留白的宽度

### ISSUE THREAD

**Issue by huguangya** [dataease/dataease#1076]
**请描述您的需求或者改进建议.**
![de785d9af1d2b99e3e5c28b4d4cd6b5](https://user-images.githubusercontent.com/54281046/139591770-693213b1-9b97-4f72-8b36-95a861999434.png)

**Comment by xuwei-fit2cloud** [comment]
在 v1.4.0 版本中，新的图库会带来更好一些的体验。
