### ISSUE TITLE
[Feature]期望优化富文本组件工具栏按钮遮挡内容问题

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#10773]
DataEase 版本:
 v2.7.1

**请描述您的需求或者改进建议.**
 富文本组件在编辑时上方的工具栏会遮挡内容，导致调整内容格式时每修改一次都要推出编辑查看效果再重新编辑。

希望能够拖动工具栏或将工具栏显示在富文本框边框以外的区域
![image](https://github.com/dataease/dataease/assets/30886198/9e354a96-73d6-471e-9dc9-07574be0d4cc)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，是已知问题，该组件还需要优化。

**Comment by xuwei-fit2cloud** [comment]
目前该第三方组件无法调整。
