### ISSUE TITLE
[Bug] 双轴图最大轴值小于最大值

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#10774]
**DataEase 版本**
v2.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 126.0.6478.127

**Bug 描述**
在自动轴值情况下，双轴图最大轴值小于最大值，导致现实在最上面的标签无法展示完全

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/45852479/5039e90c-b546-4c4b-a5a2-f4e0ccc7688e)

**Comment by BBchicken-9527** [comment]
感谢反馈，图库本身是顶满的，我们尝试优化一下，会在近两个版本内完成；

**Comment by xuwei-fit2cloud** [comment]
图库bug，暂不好处理。
