### ISSUE TITLE
Feature 制作仪表板时，是否可以，维度字段，也可以拖到指标进行展示，默认进行count计数，也可以增加一些函数

### ISSUE THREAD

**Issue by shaohuayangfit2** [dataease/dataease#10771]
DataEase 版本:
2.7.1

**请描述您的需求或者改进建议.**
1，制作仪表板时，比如有班级、学生名称两列；默认都是维度；
2，是否可以，维度字段，也可以拖到指标进行展示，比如默认进行count计数，展示内容，一年级，名字叫张三的，总共4个；
3，如果还可以的话，也可以增加一些函数，聚合，最大最小之类；

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，目前暂时没有计划支持维度拖拽至指标栏，并进行聚合。如果需要，建议将维度转换为指标进行计数。
