### ISSUE TITLE
[Bug] v2 下拉过滤组件，存在空值的情况下，排序后下拉内容显示异常

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#10770]
**DataEase 版本**
v2.7.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 126.0.6478.127（正式版本） (arm64)

**Bug 描述**
v2 下拉过滤组件，存在空值的情况下，排序后下拉内容显示异常

**Bug 重现步骤(有截图更好)**
1. 数据集数据如下所示，sales_quantity 存在空值
<img width="1236" alt="image" src="https://github.com/dataease/dataease/assets/30063018/ca1691dc-e945-415e-80f0-8239d54c9dd9">

2. 针对该字段配置过滤条件，排序字段也选择为该字段，且选择升序
<img width="1715" alt="image" src="https://github.com/dataease/dataease/assets/30063018/dcc9bf88-b34a-4f25-8a10-6839741aa1f5">

3. 下拉框内容无显示
<img width="1297" alt="image" src="https://github.com/dataease/dataease/assets/30063018/2534782b-d703-4287-ac4c-261f222c2dee">

4. 选择降序则正常，经测试，文本过滤组件也存在该问题。
<img width="1303" alt="image" src="https://github.com/dataease/dataease/assets/30063018/95af3a09-7e17-43e3-9bc0-2397e2a78f29">

<img width="1303" alt="image" src="https://github.com/dataease/dataease/assets/30063018/4a98dbbc-4e51-4fc5-82fb-06a64c00d158">

**Comment by xuwei-fit2cloud** [comment]
我们处理一下。
