### ISSUE TITLE
[Feature]v2版本 时间组件默认值希望增加月底

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#10776]
![image](https://github.com/dataease/dataease/assets/141667200/6bebf41d-812c-434a-b307-52fb3b0e8871)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，这里是内置了常见的选项，我们先记录一下，待有更多用户反馈后，我们再做下一步的规划。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
