### ISSUE TITLE
[Bug] 公共链接替换后面字符串，回车后不会跳转新链接

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#10778]
**DataEase 版本**
v2.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 126.0.6478.127

**Bug 描述**
公共链接替换后面字符串，回车后不会跳转新链接

**Bug 重现步骤(有截图更好)**
https://github.com/dataease/dataease/assets/45852479/c425ee5d-a920-4c6c-b48d-f7c7f49570cb
<img width="1476" alt="image" src="https://github.com/dataease/dataease/assets/45852479/f10f765f-ae7b-4248-b8a2-b80cadeaa2ed">
f12 打开，回车后浏览器没有请求信息

**Comment by BBchicken-9527** [comment]
感谢反馈，我们尝试优化一下，会在后续两个版本内给出结果；

**Comment by fit2cloud-chenyw** [comment]
v2.9版本修复
