### ISSUE TITLE
[Bug] 仪表板-创建视图，可以切换tab到数据集，导致没有保存的仪表板数据丢失

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#1079]
**DataEase 版本**
1.3
**浏览器版本**
chrome 95.0.4638.69
**Bug 描述**
仪表板-创建视图，可以切换tab到数据集，导致没有保存的仪表板数据丢失

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们想办法优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 版本开始，视图页面不带头部导航栏，不会进行切换了。
