### ISSUE TITLE
[Feature]建议如果开启水印功能，导出单个图表也增加水印

### ISSUE THREAD

**Issue by mmmlong** [dataease/dataease#10798]
DataEase 版本:
v2.7

**请描述您的需求或者改进建议.**

建议如果开启水印功能，导出单个图表也增加水印,现在导出的图表没加水印

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们支持一下。

**Comment by ziyujiahao** [comment]
https://github.com/dataease/dataease/commit/158b8e98f6121c2bbf68f44f7db5a1e8a9b2b6ee

**Comment by ziyujiahao** [comment]
https://github.com/dataease/dataease/commit/18847b1df6b1e57e78e269bc23fc7ce09df48d71
