### ISSUE TITLE
[Question]导入模板文件失败

### ISSUE THREAD

**Issue by PureNatural** [dataease/dataease#10792]
**请描述您的问题.**
我在官方下载了一个模板文件，后缀是.DET
想要导入到自己部署的dataease服务里面，但是无法选取该文件，请问需要怎么处理
![image](https://github.com/dataease/dataease/assets/29674550/3a0de86e-4eec-48a4-8072-6f0be32fe82f)

![image](https://github.com/dataease/dataease/assets/29674550/c807841b-89c1-4338-8583-a9b8f19949ae)

**Comment by PureNatural** [comment]
我明白了，是不是因为v1和v2的模板文件不一样，我部署的是v2的服务，想导入的是v1的模板

**Comment by PureNatural** [comment]
我改成了v1版本的，还是不行

**Comment by PureNatural** [comment]
我改成了v1版本的，还是不行

**Comment by BBchicken-9527** [comment]
> 我改成了v1版本的，还是不行
感谢反馈，我们在测试环境中看了一下没有发现你说的问题，方便问一下是哪个那个模版？不排除是模版适用版本过低导致，我们验证一下；

**Comment by maninhill** [comment]
长时间未反馈，先关闭。

**Comment by xiaoxiao5** [comment]
@maninhill 试了好几个后缀是.DET的模板都不行，模板： 物业管理数据中心、物业车位管理看板
