### ISSUE TITLE
[Bug]DB2 iSeries 使用LIMIT语法问题

### ISSUE THREAD

**Issue by LynkLin** [dataease/dataease#10807]
**DataEase 版本**
V2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge

**Bug 描述**
DB2 for iSeries 不支持LIMIT 0 OFFSET 0的语法，只有DB2 for  Linux/Unix/Windows支持。
目前DatasetDataManage中写死的LIMIT OFFSET。
需要更换为FETCH FIRST n ROWS ONLY或者使用ROW_NUMBER() OVER 语法。
**Bug 重现步骤(有截图更好)**
1. 无

**Comment by BBchicken-9527** [comment]
非常抱歉给你的使用带来不便，目前我们暂时还无法支持DB2 for iSeries；
