### ISSUE TITLE
明细表导出失败

### ISSUE THREAD

**Issue by show1abc** [dataease/dataease#10808]
**DataEase 版本**
1.18.22

**Bug 描述**
明细表数据导出中心导出失败
io.dataease.plugins.common.exception.DataEaseException: java.lang.RuntimeException: Data set no permission

**Comment by BBchicken-9527** [comment]
感谢反馈，看着像是缺少权限，方便补充一下当时的场景吗？

**Comment by show1abc** [comment]
仪表板分享给普通用户。如组件表格类型为“汇总表”则正常导出，如为明细表则导出失败。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后两个版本内完成修复；
