### ISSUE TITLE
[Bug]登录状态下在公链上下载文件，弹框后点击蓝色按钮 数据导出中心 无反应

### ISSUE THREAD

**Issue by zhangwenkl** [dataease/dataease#10810]
**DataEase 版本**
v1.18.20

**运行方式(安装包运行 or 源码运行 ?)**
官网：https://dataease.fit2cloud.com/#/about/index

**浏览器版本**
126.0.6478.127

**Bug 描述**
登录状态下在公链上下载文件，弹框后点击蓝色按钮 数据导出中心 无反应

**Bug 重现步骤(有截图更好)**
1.创建公链并访问
2.点击视图右上角下载按钮
![公链下载提示前往数据导出中心查看](https://github.com/dataease/dataease/assets/28699054/db3a2b84-f497-4451-a662-a8b1bff30137)

3.点击弹框的蓝色汉字：数据导出中心 无反应，未跳转到此页面，也未下载文件

**Comment by BBchicken-9527** [comment]
感谢反馈，问题是已知问题，目前我们正在努力修复当中；
