### ISSUE TITLE
[Bug] 更新之后配置界面显示不正确

### ISSUE THREAD

**Issue by syx112233** [dataease/dataease#10817]
**DataEase 版本**
2.18.0

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0

**Bug 描述**
配置界面移动端样式异常

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/22700932/54c9c696-8504-4179-a1be-ec2d467ff3a3)
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by paopaoteng** [comment]
> 感谢反馈，我们会在后续两个版本内进行修复；

这个要在哪里进行修复？如果不麻烦的话我想现在我本地先改了
