### ISSUE TITLE
[数据导入，当Excel单元格录入错误的计算表达式时，取数会再该表达式处中断并进行重新计数。导致数据记录数不准确 ]

### ISSUE THREAD

**Issue by zpler** [dataease/dataease#10811]
DataEase1.18版本
进行Excel数据导入时，当表格中出现录入错误的函数时 #NAME? 进行excel数据读取时会从改单元格进行结束，单元格后的重新记录成一条数据。这种问题如何处理？

如图，下发表格中只有2条数据，实际读取出来变成了3条
![image](https://github.com/dataease/dataease/assets/26763963/d21dfb67-8dac-468d-96e7-eb89f44244a5)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你所说的问题，方便问一下是否有其他的特殊操作吗？如果方便话是否可以将你使用的测试图表给我们一份，脱敏即可，因为excel的问题可能因为您使用的版本甚至是excel和wps的都会导致不同的结果；
![image](https://github.com/dataease/dataease/assets/84372766/b1ded247-6b25-4f34-a125-ee21039ed3da)

**Comment by zpler** [comment]
这样的单元格
![image](https://github.com/dataease/dataease/assets/26763963/693a8dd6-d5b9-4343-bcf0-b2faf8ae62c2)

**Comment by zpler** [comment]
[错误函数测试.xls](https://github.com/user-attachments/files/16170435/default.xls)
这是我的测试文件

**Comment by zpler** [comment]
> 感谢反馈，目前测试环境没有发现你所说的问题，方便问一下是否有其他的特殊操作吗？如果方便话是否可以将你使用的测试图表给我们一份，脱敏即可，因为excel的问题可能因为您使用的版本甚至是excel和wps的都会导致不同的结果； ![image](https://private-user-images.githubusercontent.com/84372766/346352800-b1ded247-6b25-4f34-a125-ee21039ed3da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NjIxNzYsIm5iZiI6MTcyMDY2MTg3NiwicGF0aCI6Ii84NDM3Mjc2Ni8zNDYzNTI4MDAtYjFkZWQyNDctNmIyNS00ZjM0LWExMjUtZWUyMTAzOWVkM2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDAxMzc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MmM4YzgyY2VlODkzNjA1M2UzZDNhZWM5MDVjMDQyZTMzZGRlMmFmNjY4ZTRiNGNkYWYxMmQ4ZDdlNzJhYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xseH7NKnKU1ieGTWk3TMTuiQkLCBBkyDgcxnTv4Sp3k)

[错误函数测试.xls](https://github.com/user-attachments/files/16170440/default.xls)

**Comment by zpler** [comment]
> 感谢反馈，目前测试环境没有发现你所说的问题，方便问一下是否有其他的特殊操作吗？如果方便话是否可以将你使用的测试图表给我们一份，脱敏即可，因为excel的问题可能因为您使用的版本甚至是excel和wps的都会导致不同的结果； ![image](https://private-user-images.githubusercontent.com/84372766/346352800-b1ded247-6b25-4f34-a125-ee21039ed3da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NjQ2MDIsIm5iZiI6MTcyMDY2NDMwMiwicGF0aCI6Ii84NDM3Mjc2Ni8zNDYzNTI4MDAtYjFkZWQyNDctNmIyNS00ZjM0LWExMjUtZWUyMTAzOWVkM2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDAyMTgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4YzMxMzYzZGUxNjJhODkxYzRkNTMyMThkYTFjZTk2YTJkNGRlOTY3NjhhMjAyOGFlMjdiOGI0Yjg4NDE3NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NBGL6sFu3TDwQEkuDMzVQJTzBiQp-Dz2K8QDYE0N_mk)

![1720664350831](https://github.com/dataease/dataease/assets/26763963/419dc7c6-3098-449f-ab1b-ba59604edeff)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by zpler** [comment]
> 感谢反馈，我们会在后续两个版本内进行修复；

处理后可以告知一下1.18.8这个版本如何对应着去增量升级处理这个问题下吧

**Comment by zpler** [comment]
麻烦告知下增量升级的处理代码片段，今天在git上面没找到对应的内容&nbsp;


纠结已成歌
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月15日(星期一) 上午9:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dataease/dataease] [数据导入，当Excel单元格录入错误的计算表达式时，取数会再该表达式处中断并进行重新计数。导致数据记录数不准确 ] (Issue #10811)





 
Closed #10811 as completed.
 
&mdash;
