### ISSUE TITLE
[Bug]透视表总计小计聚合方式修改不生效

### ISSUE THREAD

**Issue by show1abc** [dataease/dataease#10814]
**DataEase 版本**
1.18.22

**运行方式(安装包运行 or 源码运行 ?)**
在线升级

**Bug 描述**
透视表总计小计聚合方式修改不生效
默认为求和，切换为均值、最大、最少均不生交
**Bug 重现步骤(有截图更好)**
![Uploading 1720165977579.png…]()

**Comment by show1abc** [comment]
![1720166210569](https://github.com/dataease/dataease/assets/20981586/6c21e54e-c296-42a8-aa94-01f1cfe6c722)

**Comment by show1abc** [comment]
![1720166404367](https://github.com/dataease/dataease/assets/20981586/78514450-6dd7-412d-93e1-f09876fc6e5c)

**Comment by BBchicken-9527** [comment]
感谢反馈，我在在线环境上看了一下没发现您说的这个问题，请问是有什么特别的操作方式吗？或者是否是毕现呢？

**Comment by show1abc** [comment]
这是一个很奇怪的问题，这个面板是旧有的，原有字段的统计是正常的，数据源新增加的字段，怎么改也不生效，谷歌和Firefox试是了，怀疑是数据源问题格式问题也全部用了整数。后查数据库发现在前台修改，组件的在数据库的配置也没变，后手工修改配置后正常，下附修改前的配置数据totalCfg":{"row":{"showGrandTotals":true,"showSubTotals":true,"reverseLayout":true,"reverseSubLayout":false,"label":"总计","subLabel":"小计","subTotalsDimensions":[],"calcTotals":{"aggregation":"SUM","cfg":[{"dataeaseName":"C_a246f630603ffc142a0a9c3fb91abf39","aggregation":"AVG"},{"dataeaseName":"C_59d2a902ef1a9a38be7fa4080928d556","aggregation":"AVG"},{"dataeaseName":"C_377bda165d285db63182ade33ff9410e","aggregation":"AVG"},{"dataeaseName":"C_e3e26f760ff63be4720dfd6a3a4b7fca","aggregation":"AVG"},{"dataeaseName":"C_683692d4b6fb0879dceb993199978c83","aggregation":"AVG"},{"dataeaseName":"C_d6b643b358a2dbb780b4db1bb379536f","aggregation":"AVG"},{"dataeaseName":"C_e2f12c93a3bbdb304cd18114bc281079","aggregation":"AVG"},{"dataeaseName":"C_0be9ac1d810cdf7d660a8f6feecc0ae0","aggregation":"SUM"}]},"calcSubTotals":{"aggregation":"SUM","cfg":[{"dataeaseName":"C_a246f630603ffc142a0a9c3fb91abf39","aggregation":"AVG"},{"dataeaseName":"C_59d2a902ef1a9a38be7fa4080928d556","aggregation":"AVG"},{"dataeaseName":"C_377bda165d285db63182ade33ff9410e","aggregation":"AVG"},{"dataeaseName":"C_e3e26f760ff63be4720dfd6a3a4b7fca","aggregation":"AVG"},{"dataeaseName":"C_683692d4b6fb0879dceb993199978c83","aggregation":"AVG"},{"dataeaseName":"C_d6b643b358a2dbb780b4db1bb379536f","aggregation":"AVG"},{"dataeaseName":"C_e2f12c93a3bbdb304cd18114bc281079","aggregation":"AVG"},{"dataeaseName":"C_0be9ac1d810cdf7d660a8f6feecc0ae0","aggregation":"SUM"}]},"totalSort":"none","totalSortField":"C_a246f630603ffc142a0a9c3fb91abf39"},"col":{"showGrandTotals":false,"showSubTotals":true,"reverseLayout":true,"reverseSubLayout":false,"label":"总计","subLabel":"小计","subTotalsDimensions":[],"calcTotals":{"aggregation":"SUM","cfg":[{"dataeaseName":"C_a246f630603ffc142a0a9c3fb91abf39","aggregation":"AVG"},{"dataeaseName":"C_59d2a902ef1a9a38be7fa4080928d556","aggregation":"AVG"},{"dataeaseName":"C_377bda165d285db63182ade33ff9410e","aggregation":"AVG"},{"dataeaseName":"C_e3e26f760ff63be4720dfd6a3a4b7fca","aggregation":"AVG"},
--------这段怎么改都没生效。
{"dataeaseName":"C_683692d4b6fb0879dceb993199978c83","aggregation":"SUM"},{"dataeaseName":"C_d6b643b358a2dbb780b4db1bb379536f","aggregation":"SUM"},{"dataeaseName":"C_e2f12c93a3bbdb304cd18114bc281079","aggregation":"SUM"},{"dataeaseName":"C_0be9ac1d810cdf7d660a8f6feecc0ae0","aggregation":"SUM"}]},
------------------
"calcSubTotals":{"aggregation":"SUM","cfg":[{"dataeaseName":"C_a246f630603ffc142a0a9c3fb91abf39","aggregation":"SUM"},{"dataeaseName":"C_59d2a902ef1a9a38be7fa4080928d556","aggregation":"SUM"},{"dataeaseName":"C_377bda165d285db63182ade33ff9410e","aggregation":"SUM"},{"dataeaseName":"C_e3e26f760ff63be4720dfd6a3a4b7fca","aggregation":"SUM"},{"dataeaseName":"C_683692d4b6fb0879dceb993199978c83","aggregation":"SUM"},{"dataeaseName":"C_d6b643b358a2dbb780b4db1bb379536f","aggregation":"SUM"},{"dataeaseName":"C_e2f12c93a3bbdb304cd18114bc281079","aggregation":"SUM"},{"dataeaseName":"C_0be9ac1d810cdf7d660a8f6feecc0ae0","aggregation":"SUM"}]},"totalSort":"none","totalSortField":"C_a246f630603ffc142a0a9c3fb91abf39"},"modifyName":"row","propertyName":"total-cfg"}}

**Comment by BBchicken-9527** [comment]
”怎么改也不生效“是什么意思？不是很理解你的意思；

**Comment by show1abc** [comment]
那是在前台界面修改 聚合方式为为均值、最大、最少，查看数据库信息{"dataeaseName":"C_683692d4b6fb0879dceb993199978c83","aggregation":"SUM"},{"dataeaseName":"C_d6b643b358a2dbb780b4db1bb379536f","aggregation":"SUM"},{"dataeaseName":"C_e2f12c93a3bbdb304cd18114bc281079","aggregation":"SUM"},{"dataeaseName":"C_0be9ac1d810cdf7d660a8f6feecc0ae0","aggregation":"SUM"}]},这一段都是不变，统计结果也始终为求和，我手动改为AVG后，前台统计正常。

**Comment by show1abc** [comment]
找到问题了，是我操作问题。正确操作方法应该是设置列聚合方式，而不是行
