### ISSUE TITLE
[Bug]查询条件设置时，"图表所使用的数据集不同, 无法展示配置项"，这样处理的原因是什么？

### ISSUE THREAD

**Issue by paopaoteng** [dataease/dataease#10821]
**DataEase 版本**
2.8.0

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.
<img width="803" alt="image" src="https://github.com/dataease/dataease/assets/3022192/7cb9a708-c09e-40c6-b72e-66e2126a94de">

2.
<img width="1176" alt="image" src="https://github.com/dataease/dataease/assets/3022192/aeddc67e-1b43-4e17-93fa-4ca8292b50b2">

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，主要是为了限制下拉树的层级均处于同一数据集；

**Comment by paopaoteng** [comment]
> 感谢反馈，主要是为了限制下拉树的层级均处于同一数据集；

如果是为了限制下拉树，建议在其他场景放开。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下；
