### ISSUE TITLE
[Feature]仪表板或数据大屏中的维度、指标字段失效能进行提示

### ISSUE THREAD

**Issue by jstbw** [dataease/dataease#10824]
DataEase 版本:
v2.8

**请描述您的需求或者改进建议.**
仪表板或数据大屏中的维度、指标字段失效能进行提示。类似当前数据源失效会进行提示一样，用户去修改数据集之后，关联了很多的仪表板和视图，要自己去一个个的找有点麻烦，特别是数量很大的情况下（或者是加个批量一家添加）
![5b6778ff65e36e7d7e1d9fda0cb9f8f](https://github.com/dataease/dataease/assets/66759501/510325d3-8aaf-452d-915f-2045696f379a)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，暂时没有计划支持数据集失效提醒功能。但是血缘关系功能会在近期的版本中进行支持，可以根据血缘关系去找到与数据集相关联的仪表板，然后做相应的调整。
