### ISSUE TITLE
[Feature]自定义系统变量支持同一变量添加多个参数

### ISSUE THREAD

**Issue by jstbw** [dataease/dataease#10823]
DataEase 版本:
v2.8

**请描述您的需求或者改进建议.**
![22dd3d3f0d3dfab767e0e04b638edc3](https://github.com/dataease/dataease/assets/66759501/ddc7b000-4b25-4f3e-b316-c6ad77f5cf98)
当前系统变量同一变量名只能选择一个参数，如图，同一用户在多个办事处下就没法在行权限进行关联了

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，已经加入近期的版本迭代中。
