### ISSUE TITLE
[Feature]移动端的样式能否支持单独设置

### ISSUE THREAD

**Issue by htl258** [dataease/dataease#10822]
DataEase 版本:
V1.18.22

**请描述您的需求或者改进建议.**
目前移动端的显示直接受制于PC端的设计，建议针对移动端也能进行样式的一些调整。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池中。

**Comment by syx112233** [comment]
+1， 目前单独针对移动端做修改真的很麻烦呢

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。

**Comment by htl258** [comment]
1开头的也能支持吗
