### ISSUE TITLE
[Feature]视图的横向柱状图的纵轴希望有个左对齐、右对齐、居中等功能。

### ISSUE THREAD

**Issue by Jacker0429** [dataease/dataease#10826]
DataEase 版本:
1.18.18

**请描述您的需求或者改进建议.**
![issue](https://github.com/dataease/dataease/assets/149593799/f47eaea4-8389-404c-a7d0-7faeee268475)
视图的横向柱状图的纵轴希望有个左对齐、右对齐、居中等功能。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持。
