### ISSUE TITLE
[Feature]【图表】透视图支持比率场景的合计计算

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10830]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
当前透视图的合计是算的累加，对于求合格率，达标率的场景，不知道当前版本能否支持这种场景的合计。
<img width="1140" alt="image" src="https://github.com/dataease/dataease/assets/24768910/563df2b4-5d35-4dc3-bf26-a9c09649cacc">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前的透视表组件无法支持。
