### ISSUE TITLE
[Bug]V2.8.0指标卡无法获取数据

### ISSUE THREAD

**Issue by PotatoYummy** [dataease/dataease#10836]
**DataEase 版本**
v2.8.0

**运行方式(安装包运行 or 源码运行 ?)**
在线安装

**浏览器版本**
Chrome 126.0.6478.115（正式版本） （64 位）

**Bug 描述**
升级v2.8后指标卡无法获取数据，其他图表正常/查询组件显示异常

**Bug 重现步骤(有截图更好)**

![微信截图_20240709085800](https://github.com/dataease/dataease/assets/86452004/90b7fbdd-fce7-40d7-9b68-cce1d4a630ba)
![微信截图_20240709085814](https://github.com/dataease/dataease/assets/86452004/81b901dd-9bfc-441d-b5a1-37fac9f3e447)
![微信截图_20240709085956](https://github.com/dataease/dataease/assets/86452004/3920727e-9b5b-439b-b3ce-af1cdb0b9505)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，方便详细说明一下复现步骤吗？
![image](https://github.com/dataease/dataease/assets/84372766/6c6577f4-171d-4177-b32f-d47f9142a5ac)

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
