### ISSUE TITLE
[Feature]增加数据源 Hologres

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#10839]
DataEase 版本:
v2

增加数据源： 阿里的实时数仓 Hologres，可以先记录，后期再调研。

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，需求已记录，等待后续有相同需求后我们再排期支持。

**Comment by mfanoffice** [comment]
Hologres 兼容 PostgreSQL，可以直接使用。
