### ISSUE TITLE
对称条形图有俩“横轴”

### ISSUE THREAD

**Issue by github-tsg** [dataease/dataease#10837]
**DataEase 版本**
V2

**运行方式(安装包运行 or 源码运行 ?)**
略

**浏览器版本**

略
**Bug 描述**
对称条形图有俩“横轴”，忘记升级前截图了，上面的那个应该是纵轴吧？

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/146046004/6d6b7dc7-cbcb-45d1-a799-3466e69edbe8)
2.另外提个建议，纵轴文字的颜色和大小好像不能设置吧？望优化
![image](https://github.com/dataease/dataease/assets/146046004/515fa416-1612-484a-989c-5debf4f0fd83)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，确实是写错了，我们改一下。
