### ISSUE TITLE
[Bug]视图联动功能，没设置联动的字段也能触发联动

### ISSUE THREAD

**Issue by 2023fan** [dataease/dataease#10832]
**DataEase 版本**
2.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
最新版

**Bug 描述**
我设置的联动规则是明细表联动柱状图，关联字段是province
![image](https://github.com/dataease/dataease/assets/145900305/4cacc326-82bc-4569-9395-51b1403a9960)
![image](https://github.com/dataease/dataease/assets/145900305/b26045cb-07a7-4262-b710-8a2c1a20c5c7)

但是当我点击明细表的city、gdp字段的时候也会触发联动
例如我点击辽源市，他就触发了如下联动
![image](https://github.com/dataease/dataease/assets/145900305/b2d3753d-86bf-43a5-a562-4c0580d85949)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，这是因为表格具有其特殊性，在联动穿参时是将整行数据都传过去进行联动的，可能对使用理解上确实有一些困难，我们优化一下；
