### ISSUE TITLE
[Bug] 数据集创建时，左侧数据表栏宽度调整无效

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#10844]
**DataEase 版本**
v2.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 126.0.6478.127（正式版本） (arm64)

**Bug 描述**
数据集创建时，左侧数据表栏宽度调整无效

**Bug 重现步骤(有截图更好)**

https://github.com/dataease/dataease/assets/30063018/2c56e268-f082-4ec6-b1c3-29c4661fed8d

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，确实有这个问题，我们优化一下。
