### ISSUE TITLE
[Feature] 过滤组件筛选框内字体大小可进行配置调整

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#10847]
DataEase 版本:
v2.8

**请描述您的需求或者改进建议.**
目前 DataEase 过滤组件的标题文字大小可以调整，但是筛选框内文字大小不可调整，可否也开放筛选框内文字大小调整配置。
![image](https://github.com/dataease/dataease/assets/30063018/00a43a84-5e58-45ce-9f52-efa6bacfe6bd)

**Comment by xuwei-fit2cloud** [comment]
在目前查询组件选择框高度不可变的情况下，调整框内的字体大小意义不大，暂时不考虑支持。
