### ISSUE TITLE
[Bug]双轴图的标签显示问题

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#10841]
**DataEase 版本**
 V2.8.0

**运行方式(安装包运行 or 源码运行 ?)**
 安装包

**浏览器版本**
Edge 最新

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/30886198/6b3bb1a8-8ec1-46ce-bf1e-4435732962e5)
1. 双周图标签配置了位置为下时，右纵轴对应的折线图未生效
2. 折线图与柱形图标签重叠，影响查看
3. 顶部的标签显示不全只显示了一半
4. 当同一个指标即放在左纵轴又放在右纵轴，但计算方式不一致时，无法分别设置标签格式
![image](https://github.com/dataease/dataease/assets/30886198/2f027a9e-1e6c-4ee9-b5ba-bf14ceb9fdc5)

**Comment by BBchicken-9527** [comment]
感谢反馈，1.坐标位置只有柱状图可调整，这个是给了提示的，目前折线是不支持位置的调整的；2.重叠是因为您设置了标签为下且折线的标签是跟随折点导致的，我个人认为是不需要去优化的；3.因为组合图为双轴线导致处理上限比较困难暂时目前我们没有找到合适的方案处理，暂时建议通过自定义轴值调整上限以满足显示条件；4.因为是同一字段可能处理上存在难度，我们尝试优化一下； 
![image](https://github.com/dataease/dataease/assets/84372766/82140f4f-8e64-4bc9-bcbd-85e03d28b50f)

**Comment by liuboF2c** [comment]
第二个问题与第四个问题有关联，当使用同一字段时，无法单独调整折线标签的显示隐藏。重叠的标签值没有任何意义，无法查看，所以希望当重叠时可以隐藏部分标签（就像横轴数据过多时并不会全部显示一样）。
第三个问题，数据是动态的，通过轴值调整无法适应动态数据
