### ISSUE TITLE
[Bug]v2.8 文本搜索组件，设置默认值同时设置必填，不能识别默认值报错无选项值

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#10853]
![image](https://github.com/dataease/dataease/assets/141667200/d70fc696-731a-4761-9004-933a27ae352e)
![image](https://github.com/dataease/dataease/assets/141667200/88a13139-3066-4c02-a1cc-1678bac1f1b2)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
