### ISSUE TITLE
[Bug]仪表板和数据大屏在外部跳转时，原页面报错

### ISSUE THREAD

**Issue by leleyuan** [dataease/dataease#10852]
**DataEase 版本**
v2.8.0 开源版

**运行方式(安装包运行 or 源码运行 ?)**
在线安装

**浏览器版本**
edge浏览器、谷歌浏览器

**Bug 描述**
组件添加跳转链接后，点击组件，能跳转到其他页面，但是在原页面会报“跳转错误，URL不合法....”，

**Bug 重现步骤(有截图更好)**
1.
![c143b7130748e78a56312e5382112de](https://github.com/dataease/dataease/assets/107379796/9bc3181d-06a3-4c44-b3b7-f3dee633c469)

2.
3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，确实有这个问题，我们下个版本修复。
