### ISSUE TITLE
[Question]【数据集】SQLServer image 类型字段不知道是否考虑支持

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10856]
**请描述您的问题.**
SQLServer image 类型字段不知道是否考虑支持
![image](https://github.com/dataease/dataease/assets/24768910/53ebb57c-1a3d-4466-8588-f4ed3310fbd5)

**Comment by xuwei-fit2cloud** [comment]
image字段类型并不适合做数据分析，所以这里也没有必要做支持。建议您在做数据集的时候去掉该字段。
