### ISSUE TITLE
Dataease添加Postgresql数据源数据表名不支持字符串带"-"

### ISSUE THREAD

**Issue by gabreilcollins** [dataease/dataease#10851]
**DataEase 版本**
V1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome

**Bug 描述**
Dataease添加Postgresql数据源数据表名不支持字符带"-"

**Bug 截图**
![asimco](https://github.com/dataease/dataease/assets/73423850/cf1839e6-29e9-4d2a-a4fc-6f2bbc037c74)

**Comment by xuwei-fit2cloud** [comment]
问题修复：https://github.com/dataease/dataease/commit/b9a05adc6c77843a6d257c3bc33757e74e28069b

![图片](https://github.com/dataease/dataease/assets/1892127/fe2692e3-3a8e-4193-85e5-28943e2b9db7)
