### ISSUE TITLE
[Bug]v2.8 数据大屏在分享出去之后缩小会出现画布外的东西

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#10867]
![image](https://github.com/dataease/dataease/assets/141667200/d859943b-11f3-4f40-a4f9-a70f82de9a8a)
![image](https://github.com/dataease/dataease/assets/141667200/6bb97eeb-8e81-4d06-8745-81b593aff62e)

**Comment by xuwei-fit2cloud** [comment]
已处理该问题，请等待新版本发布。
