### ISSUE TITLE
[Bug]分组柱状图下钻后变成单维，且指标值异常

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#10875]
**DataEase 版本**
 v2.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 最新

**Bug 描述**
如视频
1. 分组柱状图下钻后丢失了分组信息，变成了单维
2. 下钻后最高的柱子指标值小于其他柱子指标值
![WeChate2ebff8250b679e50ae5093be1a17381](https://github.com/dataease/dataease/assets/30886198/1258bfcf-a042-40fd-a423-e901b8e2b1d9)
![WeChatf81f02820292df5500b712c6076b872f](https://github.com/dataease/dataease/assets/30886198/1adcee05-67f4-4953-b047-c7758f65546b)

3. 下钻后数值总和与下钻前数值总和不一致

https://github.com/dataease/dataease/assets/30886198/bb285d8d-a8fb-4e21-a332-40bff7f92443

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
