### ISSUE TITLE
仪表板新增查询条件设置时，"图表所使用的数据集不同, 无法展示配置项"

### ISSUE THREAD

**Issue by hyfcute** [dataease/dataease#10879]
DataEase 版本:
V2.8.0
Bug 描述
新建的仪表板，有多个数据集，在新增查询条件是，提示“图表所使用的数据集不同, 无法展示配置项”，为什么会这么设计呢？难道仪表板只能是同一数据集吗？ 这样是否合理呢？

**Comment by xuwei-fit2cloud** [comment]
这是一个bug，我们已处理，请等待新版本发布。
Duplicate of #10821

**Comment by hyfcute** [comment]
多谢
