### ISSUE TITLE
外部链接跳转时，查询组件的参数是否可以配置

### ISSUE THREAD

**Issue by hyfcute** [dataease/dataease#10889]
DataEase 版本:
V2.8.0

**请描述您的需求或者改进建议.**
![Snipaste_2024-07-10_17-09-25](https://github.com/dataease/dataease/assets/28752544/9dcd9214-415b-49e6-bbc3-fd0669125d29)
![Snipaste_2024-07-10_17-10-29](https://github.com/dataease/dataease/assets/28752544/e2ce6b90-3de3-4dc7-be11-c11209e0abd4)
新建仪表盘时，添加了时间查询字段，配置图表跳转到外部链接时，需要把时间范围传到外部链接如何是否可以实现

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先加入需求池中，目前暂时没有计划支持。
