### ISSUE TITLE
[Bug] v1， oracle 数据源制作仪表板，使用过滤组件后，视图异常报错。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#10882]
**DataEase 版本**
v1.18.22

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 126.0.6478.127（正式版本） (arm64)

**Bug 描述**
v1， oracle 数据源制作仪表板，使用过滤组件后，视图异常报错。
测试下来，无论是数据库数据集、SQL 数据集，文本、数字等过滤组件，均会出现该问题。

**Bug 重现步骤(有截图更好)**
1.  未使用过滤组件
![image](https://github.com/dataease/dataease/assets/30063018/73363d44-6134-4cc0-8b97-f86d243b0995)

2. 使用过滤组件
![image](https://github.com/dataease/dataease/assets/30063018/7dd2a4e2-62f6-46ac-a291-3f7d51044b0f)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复；
