### ISSUE TITLE
[Feature]配置api数据源时，能否支持动态传参功能

### ISSUE THREAD

**Issue by hyfcute** [dataease/dataease#10899]
DataEase 版本:
V2.8.0

**请描述您的需求或者改进建议.**
api数据源查询数据时，需要动态传递参数，比如开始时间、结束时间
能否在api数据源定义功能中，增加动态传参功能，动态传参能够关联过滤组件，实现动态数据查询和仪表板数据的动态刷新功能。
谢谢！

**Comment by xuwei-fit2cloud** [comment]
API数据源的数据需要定时拉取到本地MySQL数据库中，利用SQL函数为前端图表展示提供支持。
您说的动态传参其实是想实时的直接查询API数据，由于数据没有入库，图表展示没有SQL支撑，所以目前是做不到的。
