### ISSUE TITLE
[Bug]默认的组织管理员角色无法查看该组织下所有的操作日志

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#10897]
**DataEase 版本**
v2.8

**运行方式(安装包运行 or 源码运行 ?)**

安装包运行

**浏览器版本**
谷歌

**Bug 描述**

创建2个用户分别都为该组织的组织管理员（默认角色），两个人同时访问DataEase平台，访问过程中产生的操作日志信息，各个组织管理员只能看到自己的
其他结果为：组织管理员可以看到该组织用户所有的操作日志信息。

**Bug 重现步骤(有截图更好)**
<img width="1436" alt="image" src="https://github.com/dataease/dataease/assets/60059766/dfc4f814-52f5-43c3-a600-ad9c4e3eeff7">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前平台只支持admin账号查看全部日志的；
