### ISSUE TITLE
[Bug]【数据集】SQL 数据集设置动态参数进行数据查询时报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10908]
**DataEase 版本**
v2.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准版本浏览器

**Bug 描述**
SQL 数据集在子查询中设置动态参数在数据集编辑页面中进行数据查询时报错，但是 SQL 编辑页面中预览正常。
数据库类型：SqlServer 数据库
![image](https://github.com/dataease/dataease/assets/24768910/42ea3a0d-d025-486f-ad11-e35783b14f0f)

**Bug 重现步骤(有截图更好)**

https://github.com/dataease/dataease/assets/24768910/7ac59161-9e6e-400f-95a7-5364d22f424a

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下；

**Comment by AndroidBaby1** [comment]
感谢，发现是 SQL 没写对，抱歉
