### ISSUE TITLE
[Feature] 详情表分页情况下排序支持全局排序

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#10911]
DataEase 版本:
 2.8

**请描述您的需求或者改进建议.**
 目前详情表或者汇总表在分页的情况下点击标头的排序。只会针对当前页排序，而不是全局数据排序。
这会造成误解以为是所有页面排序了的结果，希望这块实现全局排序更符合正常使用逻辑

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，加了分页器后，一次只读取一页的数据，因此无法根据表头实现全部数据的排序。
