### ISSUE TITLE
[Question] v1仪表板导入到v2

### ISSUE THREAD

**Issue by tzengshinfu** [dataease/dataease#10917]
**请描述您的问题.**
您好，请问v1已开发的仪表板能导入到v2吗？
因为数量有点多，所以如果能不重新开发最好。
尝试将v1仪表板导出成模板，
但在导入v2时虽然能显示预览画面却显示错误讯息而无法导入。
（如下图）
![image_20240712_101657](https://github.com/user-attachments/assets/c6da339c-fbe5-4ce5-8075-31cb91811159)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，v1的仪表板是不支持导入v2的。

**Comment by tzengshinfu** [comment]
收到，谢谢回覆。
