### ISSUE TITLE
[Bug]【仪表板】富文本不按照默认值筛选对应的结果

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10912]
**DataEase 版本**
v2.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
富文本不按照默认值筛选对应的结果，要点击查询才会生效默认值

**Bug 重现步骤(有截图更好)**

https://github.com/dataease/dataease/assets/24768910/322ee469-49be-4fe1-87c0-caf75a64e1d5

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
