### ISSUE TITLE
[Feature] 过滤组件输入框提示部分内容支持配置修改

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#10916]
DataEase 版本:
v1.18.22 / v2.8

**请描述您的需求或者改进建议.**
过滤组件输入框提示部分内容支持配置修改。
![image](https://github.com/user-attachments/assets/544df3a4-3f50-47f2-817d-8ee4a1c71dc2)
![image](https://github.com/user-attachments/assets/32da0661-adbc-418c-beda-27ebac7901cf)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池中。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
