### ISSUE TITLE
[Bug]无法获取Doris2.1.x的数据

### ISSUE THREAD

**Issue by juice411** [dataease/dataease#10927]
**DataEase 版本**
v2.8.0

**运行方式(安装包运行 or 源码运行 ?)**
离线安装

**浏览器版本**
edge

**Bug 描述**
通过新建Doris数据源，可以正常连接，能获取到Doris外部表，但无法获取表信息与表数据。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by juice411** [comment]
![image](https://github.com/user-attachments/assets/78ebb039-9a4b-4ed8-ad3e-f6602282fdc0)
补充个图片

**Comment by BBchicken-9527** [comment]
感谢反馈，我们测试一下；

**Comment by BBchicken-9527** [comment]
感谢反馈，目前我们在测试环境中尝试没有发现你说的问题，请问外部表配置是否正常？如果使用manger工具是否能正常获取到数据呢？
![image](https://github.com/user-attachments/assets/1262796a-72d2-4bd4-a1e6-415b45f7c63b)

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
