### ISSUE TITLE
[Bug]【权限】更新 License，资源文件会隐藏

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#10921]
**DataEase 版本**
v2.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
在仪表板模块创建一个名字叫’测试文件夹‘的文件夹，数据大屏模块也创建一个名字叫’测试文件夹‘的文件夹，里面同样创建同名的数据大屏和仪表板。更新 License 之后，数据大屏和仪表板的这两个文件夹连带里面的数据大屏和仪表板都被隐藏（看不到），但是数据库数据在。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下；
