### ISSUE TITLE
[Feature]移动端布局可以支持横屏设置

### ISSUE THREAD

**Issue by daviadong** [dataease/dataease#10936]
DataEase 版本:
V2.8.0

**请描述您的需求或者改进建议.**
建议增加移动端布局自定义选择竖屏或横屏的配置模式，因移动端是自适应的，所以在碰到需要手机横屏查看仪表盘时会有自适应上的问题，如有在配置移动端时就设置好展示竖屏或横屏的效果会比较方便

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，仪表板是在浏览器中打开的，目前无法处理，建议将手机设置为竖屏模式，去查阅仪表板。
