### ISSUE TITLE
[Bug]提取表单的API数据在API预览界面显示正常，但在数据集界面无法显示

### ISSUE THREAD

**Issue by kkkzhonghaiwei** [dataease/dataease#10935]
**DataEase 版本**
1.8.22

**运行方式(安装包运行 or 源码运行 ?)**
docker 镜像

**浏览器版本**

chrome版本 109.0.5414.120（正式版本）
**Bug 描述**
提取明道云的表单的API，在预览界面数据能够看到，一切正常；
在数据集界面，预览数据无显示，异常，尝试同步字段，立即更新数据，后仍然一样无显示。

**Bug 重现步骤(有截图更好)**
1.在API设置界面（一切正常）：
![1](https://github.com/user-attachments/assets/9f758e24-c810-47eb-b0c8-cb59c5e92da6)
![2](https://github.com/user-attachments/assets/e303b92a-b444-4044-9ec8-b0527b64cf77)
![3](https://github.com/user-attachments/assets/4368035e-20ef-46a4-b47b-d004c3e9b445)

2.在数据集界面（DepartmentName字段不显示了）

![4](https://github.com/user-attachments/assets/1d8a3264-6d0b-4b45-b951-02ef69fff473)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问返回的内容是一个完整的json吗？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
