### ISSUE TITLE
[Bug]修改配置文件后引发的异常

### ISSUE THREAD

**Issue by f2m4** [dataease/dataease#10949]
**DataEase 版本**
v1 所有版本

**运行方式(安装包运行 or 源码运行 ?)**
源码安装

**浏览器版本**
任何浏览器

**Bug 描述**
修改 安装配置文件 install.conf
部署方式为： local
若修改doris的密码
DE_DORIS_PASSWORD=Password123@doris
部署后，会影响定时同步功能，提示错误
Data source connection exception: Access denied for user 'root@172.19.0.4' (using password: YES)

**Bug 重现步骤(有截图更好)**
1. 部署时：修改  DE_DORIS_PASSWORD=Password789@doris
2. 使用定时同步功能会出现错误
![image](https://github.com/user-attachments/assets/361bc65b-cbe7-40a9-9b23-fee4a372d8e8)

3. 
4.

**Comment by maninhill** [comment]
请参考：https://dataease.io/docs/v1/dev_manual/dev_deployment/tool/

源码安装还行自行排查，各种情况很多。
