### ISSUE TITLE
GIS数据展示应用

### ISSUE THREAD

**Issue by ifuleme** [dataease/dataease#10948]
DataEase 版本:2.x

**请描述您的需求或者改进建议.**
增加业务图层编排和空间数据的可视化，提供事件交互功能；比如通过添加图层可以实现网格的展示、拥堵信息展示、拥堵告警通知等；

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池中。

**Comment by xuwei-fit2cloud** [comment]
请升级到2.10.2版本。
https://dataease.io/docs/v2/change-v2-10-2/#121
