### ISSUE TITLE
JS代码注入

### ISSUE THREAD

**Issue by ifuleme** [dataease/dataease#10947]
DataEase 版本:2.x. 期望是2.9

**请描述您的需求或者改进建议.**
请提供二次代码注入开发功能，通过注入js代码可以做出更好的效果，如webgl实现流光酷炫的效果，点击某个按钮弹出后也可以通过代码注入调用第三方服务等

**Comment by ifuleme** [comment]
类似
<img width="462" alt="未命名" src="https://github.com/user-attachments/assets/5f2f6c5c-0880-4df4-aa70-eb3b8517c47f">
![WechatIMG612](https://github.com/user-attachments/assets/c901c7f1-370a-4b69-8446-8ad657a1ddca)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持。
