### ISSUE TITLE
[Feature] 复用后能否保持原有大小呢

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#10952]
DataEase 版本:
v2.8.0

**请描述您的需求或者改进建议.**
原本仪表板的视图是调整好排列的，但是不管怎么选复用组件样式，最后的大小都会变也导致排列发生变化。
![chrome_fxzFcc742W](https://github.com/user-attachments/assets/a484aeda-645b-42c4-a2a3-a251951f0ffc)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先记录进需求池中。

**Comment by ziyujiahao** [comment]
https://github.com/dataease/dataease/pull/11533/commits/86f49da257e234d51cd2a49d354de6dbaa2a8b71
