### ISSUE TITLE
[Feature]堆叠柱线组合图的堆叠维度支持排序

### ISSUE THREAD

**Issue by luca-woo** [dataease/dataease#10957]
DataEase 版本: v2.8.0

![6b19cbb568e9e1633e3f82f75d563cb](https://github.com/user-attachments/assets/439ebf99-5b0b-4615-b52e-494824894cff)

**请描述您的需求或者改进建议.**
![1692b308ca6e26e22bfce36e7cd94fd](https://github.com/user-attachments/assets/94d1ee59-4e28-4f61-af72-7c281fa2f95b)
希望堆叠柱线组合图的堆叠维度可排序。普通堆叠柱形图是可以的，但是新增的这个组合图不行。显示出来的图形随机显示顺序和颜色，体验非常不好。希望能加上该需求

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，已经规划在近期的版本迭代中。
