### ISSUE TITLE
[Feature]希望通过辅助线功能，做一个监控告警，告警可以通过邮箱或者短信进行外发。

### ISSUE THREAD

**Issue by zjdc** [dataease/dataease#10950]
DataEase 版本: V2.8.0
希望通过辅助线功能，如果超过辅助线了，就触发告警，告警可以通过邮箱或者短信进行外发。
目前很多客户存在这个需求，部分外企单位不使用钉钉企业微信等软件，需要通过短信或者邮箱外发。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
已支持阈值告警功能。
