### ISSUE TITLE
[Bug]Mongodb-BI数据源添加失败

### ISSUE THREAD

**Issue by leavateinzhou** [dataease/dataease#10953]
**DataEase 版本**
v2.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 126.0.6478.127

**Bug 描述**
创建 Mongodb-BI 数据源时提示 'CLIENT_PLUGIN_AUTH is required'，但BI可在Navicat中正常访问

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/c39ac76a-4b62-44de-a080-dd50c75c25d2)
2.
![1721013001772](https://github.com/user-attachments/assets/dfe0d887-0846-4bc6-850b-6fed1b9ae70e)
3.
![1721013600089](https://github.com/user-attachments/assets/999e3794-5b06-4fee-aa49-51babc96b43a)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行优化；
