### ISSUE TITLE
[Feature]系统变量的值支持多选

### ISSUE THREAD

**Issue by Xyuncheng** [dataease/dataease#10956]
DataEase 版本:
v2.8.0

**请描述您的需求或者改进建议.**
系统变量里面的值需要多选，希望能够支持。
![image](https://github.com/user-attachments/assets/1bc02bc8-0ab6-4dfb-a1ef-07ba9d3615df)
如图所示，这个界面只能选择一个值，有一些场景需要选择多个值，希望这里能够优化一下。

同时，在支持多选之后，行权限的设置界面需要支持 in ，看界面上的“包含”应该是使用 like 的方式去做的，所以这块也麻烦能够优化一下。
![image](https://github.com/user-attachments/assets/a52472d5-ee7b-4351-bd16-11014516de90)

**Comment by yayanpei-fit2cloud** [comment]
同issue：https://github.com/dataease/dataease/issues/10823
