### ISSUE TITLE
[Bug]文本列表多选鼠标选不中

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#1095]
**DataEase 版本**
1.3.0

**浏览器版本**
chrome最新版

**Bug 描述**
仪表盘--组件--文本列表---选择多选，确定；
在仪表板中点击刚才插入的文本，视图有相应的变化，但前段图形显示没反应，没有选中的提示。

**Bug 重现步骤(有截图更好)**
1. 仪表盘--组件--文本列表---选择多选，确定；
![image](https://user-images.githubusercontent.com/48307752/139654498-132e12a9-df49-46b7-8ccd-3b2aed955ad8.png)

2. 回到仪表盘，多选刚才插入的文本列表，鼠标点击多选列表无反应，但视图显示有变化。
![image](https://user-images.githubusercontent.com/48307752/139654715-1307e76a-08fb-474d-af87-b28dc1eeb016.png)

**Comment by tjlygdx** [comment]
感谢反馈，我们处理一下

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 已修复
