### ISSUE TITLE
[Bug] 过滤组件参数配置选项值来源和对应图表不同时，过滤不生效

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#10961]
**DataEase 版本**
v2.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 126.0.6478.127

**Bug 描述**
过滤组件参数配置选项值来源和对应图表不同时，过滤不生效

**Bug 重现步骤(有截图更好)**
1. 点击查询按钮，页面没有反应
![image](https://github.com/user-attachments/assets/0d259deb-cba9-4f9c-a0c7-e7b2152a81f8)
2. 再次进入编辑页面，配置项丢失
![image](https://github.com/user-attachments/assets/c3b9624a-b90e-490f-8212-3dd92065e9d5)
3. 配置页面如下 
![image](https://github.com/user-attachments/assets/450dfea8-a13e-4fc5-b302-5ceaf745fca9)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内修复；
