### ISSUE TITLE
[Feature] 建议将嵌入式能力作为基础能力开放给社区版

### ISSUE THREAD

**Issue by xbestwiz** [dataease/dataease#10969]
如题，建议社区版也具备嵌入式能力，让fit2cloud和用户实现双赢，理由如下：

1、首先，嵌入式能力只是一种被集成的能力，而非管理功能方面的完善、强化和保障（企业版）；
2、社区版dataease支持无缝嵌入到用户自有系统中后，将扩大dataease的采用率（在一众大屏开源软件中获得比较优势），进一步提升dataease的用户基数，赢得口碑；
3、一旦用户将dataease与自有系统深度集成后，有了更好的呈现效果，更有利于用户获得公司决策者的支持，从而成为企业版的潜在客户（从“好用”到“用好”+“保障”）。

以上，还望fit2cloud能慎重考虑、积极支持，谢谢！

**Comment by maninhill** [comment]
感谢你的建议，我们会认真考虑。
