### ISSUE TITLE
[Bug] 修改在线地图key之后未生效

### ISSUE THREAD

**Issue by 0-error** [dataease/dataease#10974]
**DataEase 版本**
2.8.0

**运行方式(安装包运行 or 源码运行 ?)**
离线安装包运行

**浏览器版本**
chrome 126.0.6478.127

**Bug 描述**
修改key未生效

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/80be0267-93b7-4824-a401-60a52efc739b)

2. 
![image](https://github.com/user-attachments/assets/2cd24b74-a63d-4769-b2f1-9e71d8aabae8)

3. 导致流向地图不显示地图

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后去版本进行优化；

**Comment by 0-error** [comment]
能告诉我如果现在想要临时修改下，应该怎么做么

**Comment by 0-error** [comment]
好像过了几个小时之后好了

**Comment by xuwei-fit2cloud** [comment]
免费的key调用次数是有限制的，等下次可用周期到了自然就可以用了。
