### ISSUE TITLE
[Bug] 配置完访问路径打不开 API 文档

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#10975]
**DataEase 版本**
DataEase v2.8 嵌入式

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌浏览器

**Bug 描述**
参考知识库[文章](https://kb.fit2cloud.com/?p=57a47d64-4eda-4ae8-a0b0-4329e57b13ff)设置访问路径为 /dataease 后，访问其他页面都可以，访问不到 API 文档
![868db72e-88b8-47f1-a48d-41168260b4f5](https://github.com/user-attachments/assets/c33d64c7-9fe4-44a6-9d6e-ce339ecb4c87)

**Bug 重现步骤(有截图更好)**
1.安装包部署 DataEase v2.8 嵌入式
2.参考知识库[文章](https://kb.fit2cloud.com/?p=57a47d64-4eda-4ae8-a0b0-4329e57b13ff)设置访问路径为 /dataease
3.查看 API 文档

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们在下个版本修复。
