### ISSUE TITLE
Elasticsearch 数据源

### ISSUE THREAD

**Issue by xukrat** [dataease/dataease#10971]
DataEase 版本:V2.8.0

DataEase v1.0支持Elasticsearch 数据源，希望DataEase v2.0也支持Elasticsearch 数据源。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个需求已经在需求池中，但存在一些技术难点未解决。
等我们处理完之后会做相关支持。

**Comment by xuwei-fit2cloud** [comment]
请升级版本。
