### ISSUE TITLE
[Bug]1.18.23数据集导出又异常了

### ISSUE THREAD

**Issue by htl258** [dataease/dataease#10989]
**DataEase 版本**
1.18.23

**运行方式(安装包运行 or 源码运行 ?)**
1panel安装运行

**浏览器版本**
EDGE或google最新版

**Bug 描述**
数据集导不出来，如图

**Bug 重现步骤(有截图更好)**
1.
2.
![微信截图_20240716174551](https://github.com/user-attachments/assets/5870e3a1-131f-44e5-aa77-ed8f24368bed)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，我们正在努力修复中，目前数据导出中心只能在仪表板页面打开，我们会尽快修复；

**Comment by UncleNine** [comment]
右上角的下载按钮可以上吧，不过导出那边我看1.8还有bug，等我有时间我也写个pr
