### ISSUE TITLE
[Bug]查看分享的仪表板时明细表视图数据无法导出

### ISSUE THREAD

**Issue by DanteL126** [dataease/dataease#10987]
**DataEase 版本**
1.18.23

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 126.0.6478.127

**Bug 描述**
查看分享的仪表板时，明细表视图数据导出数据显示导出失败，无数据权限；

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/39188672-8ea6-45e0-9249-51d240c4d264)
2.
![image](https://github.com/user-attachments/assets/86a41296-3113-483f-961a-7ff68ab6316a)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前导出权限和查看权限是分开的，是需要你有相应的导出权限才才能正常导出的，分享的仪表板只赋予了被分享人查看的权限，导出的权限还是已自身权限为主的；
