### ISSUE TITLE
[Feature]饼图标签显示问题

### ISSUE THREAD

**Issue by xun986** [dataease/dataease#1098]
**请描述您的需求或者改进建议.**
饼图标签布置在外侧时，如果饼图的某几个部分面积占比比较小，往往出现标签显示不全的问题。而且标签特别容易和标题或图例重叠，希望能够调整并增加手动拉拽标签位置，同时自动调整引导线指向的功能

**Comment by yayanpei** [comment]
感谢您的反馈，标签显示不全的问题，我们尽量优化一下。如果发现标签和标题、图例等重叠，建议您将饼图的大小设置小一些。
![image](https://user-images.githubusercontent.com/84168063/139819298-f555e061-9f65-4208-bdb8-952321b88134.png)
