### ISSUE TITLE
[Feature]明细表的数据显示只支持一次显示多行，可以加入单行显示吗

### ISSUE THREAD

**Issue by LYL55555** [dataease/dataease#10981]
DataEase 版本:2.8.0

明细表的数据显示只支持一次显示多行（5/10/20行），可以加入单行显示吗，然后可以和其他组件关联实现动态实时显示的效果

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前已经内置了常见的分页条数，暂时没有计划支持每页显示一条。
