### ISSUE TITLE
[Feature]透视表汇总支持公式

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#10997]
DataEase 版本:
v2.8.0

**请描述您的需求或者改进建议.**
透视表汇总选项只支持求和、平均、最大、最小值
当字段使用计算字段时，比如 完成率 = 已完成 / 总量
汇总时需要先把已完成和总数求和再相除计算出完成率
目前无法通过透视表实现上述需求

**Comment by xuwei-fit2cloud** [comment]
我们讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，已经加入近期的版本迭代中。
