### ISSUE TITLE
[Feature]API数据源 请求头，需要能设置“Bearer<空格>” 前缀

### ISSUE THREAD

**Issue by radomwalk** [dataease/dataease#11007]
DataEase 版本: V2.8.1

**请描述您的需求或者改进建议.**
希望 请求头，能自定义设置，比如增加 Bearer<空格> 前缀。
![image](https://github.com/user-attachments/assets/dea68c53-73de-4ee7-91a1-563aa5d0e0a1)
![image](https://github.com/user-attachments/assets/408bcb78-9a05-47f6-bcd8-f2f34e9d663a)
![image](https://github.com/user-attachments/assets/a4d6ea55-f6ca-4e60-9bd2-ec5e48cc48d6)

**Comment by maninhill** [comment]
重复提交
