### ISSUE TITLE
请提供mongo-bi的镜像和使用示例

### ISSUE THREAD

**Issue by liuyunfeng2017** [dataease/dataease#11002]
DataEase 版本: 2.8.0

v2版本没有mongodb直连的数据源了，看了文档安装mongo-bi失败，请问dataease有没有mongo-bi的镜像和使用说明，数据源限制了，BI使用就无法进行下去了呀

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们这边没有mongo-BI的镜像和使用说明，建议您去它们的官网下载。
