### ISSUE TITLE
[Bug]新建用户无法创建仪表板

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#11019]
**DataEase 版本**

v1.18.23
**运行方式(安装包运行 or 源码运行 ?)**

安装包

**浏览器版本**

版本 126.0.6478.127（正式版本） (arm64)

**Bug 描述**
新建用户无法创建仪表板，可以创建数据源、数据集

**Bug 重现步骤(有截图更好)**
![image](https://github.com/user-attachments/assets/514ad03e-c89d-47eb-963f-9eb69aa88a5b)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在两个版本内尽快修复；
