### ISSUE TITLE
[Feature]定时报告富文本编辑按钮遮挡文本内容，期望优化按钮，防止遮挡

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#11023]
DataEase 版本:
2.8.0

**请描述您的需求或者改进建议.**
![image](https://github.com/user-attachments/assets/29b6d7d3-9fed-4b54-ae69-8021f04c5735)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，相同issue： https://github.com/dataease/dataease/issues/10773 ，组件会在后续的版本中进行优化。

**Comment by liuboF2c** [comment]
> 感谢反馈，相同issue： #10773 ，组件会在后续的版本中进行优化。

10773 是仪表板中的富文本组件，本 ISSUE 是指定时报告中的富文本组件。目前看两边的样式是不一样的。

**Comment by yayanpei-fit2cloud** [comment]
用的是同一个组件，因此都存在遮挡文本内容的情况。

**Comment by xuwei-fit2cloud** [comment]
目前还无法处理。
