### ISSUE TITLE
[Feature]希望能增加一些多选处理的功能

### ISSUE THREAD

**Issue by xun986** [dataease/dataease#1102]
**请描述您的需求或者改进建议.**
1.在导入数据集时，希望能够新增 字段类型多选后一键处理修改 的选项，智能识别的选项不一定是使用者想要的，字段一多一个一个修改又很麻烦。
2.在制作仪表板时，希望能新增 组件多选后同步调整位置 的选项，都排整齐了再一个一个调又得排一遍。
3.在制作仪表板时，希望能新增 同类型组件多选后一键调整标题图例等 的选项，会更加方便快捷。

**Comment by yayanpei** [comment]
感谢您的反馈，我们需要讨论一下。

**Comment by xuwei-fit2cloud** [comment]
1和2在短期内还不会支持，3的话，目前已经可以通过批量设置来实现了。
