### ISSUE TITLE
[Bug]一个看板多个透视表，设置汇总的配置项后，点击另外一个透视表，汇总配置无变化

### ISSUE THREAD

**Issue by mmmlong** [dataease/dataease#11024]
**DataEase 版本**
v2.8

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**

**Bug 描述**
仪表板中多个透视表，配置汇总后，点击另外一个透视表，行汇总的配置还是第一个的

**Bug 重现步骤(有截图更好)**
![image](https://github.com/user-attachments/assets/83e82961-0027-4735-8264-3a3e7a8bd014)

1.创建透视表，复制一个透视表
2.点击第一个透视表的行汇总配置总计相关的内容
3.点击第二个透视表行汇总的配置还是第一个的，

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行优化；
