### ISSUE TITLE
[Bug]对称条形图的横轴标签颜色没办法修改、右侧标签修改不生效

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#11020]
**DataEase 版本**
v2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**

对称条形图的横轴标签颜色没办法修改、右侧标签修改不生效（左边生效）

**Bug 重现步骤(有截图更好)**
![image](https://github.com/user-attachments/assets/467de8bb-4f58-4a6a-84a4-4865edbaaba0)
![image](https://github.com/user-attachments/assets/64af80dc-f2b3-4e64-8b57-becb6e3cf76d)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本尽快修复；
