### ISSUE TITLE
[Feature]de-selenium的地址可以在配置文件配置

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#11025]
DataEase 版本:
v2

de-selenium如果外置部署无法关联，代码中可能写死了使用容器名通讯；
de-selenium的 IP 地址配置希望可以开放到配置文件，de-selenium部署到单独的服务器，DE 可以调用。

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
可以在application.yml配置文件里配置，
默认设置为：
selenium-server: http://de-selenium:4444/wd/hub
