### ISSUE TITLE
[Bug]查询组件配置富文本查询并设置默认值，仪表板预览时展示的仍是总的而非设置的默认值

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#11034]
**DataEase 版本**
2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌浏览器最新

**Bug 描述**
查询组件配置富文本查询并设置默认值，仪表板预览时展示的仍是总的而非设置的默认值

**Bug 重现步骤(有截图更好)**
1.配置一个富文本组件，设置富文本展示的指标值
2.配置一个查询组件，组件设置查询富文本的指标，同时设置一个默认值
<img width="1274" alt="bd2c70180d8d44ecd28bc6b27341f2a" src="https://github.com/user-attachments/assets/6254de34-d8bd-4c55-95bb-d16a58e60f2e">
3.查询默认值显示的富文本数据是正常的
<img width="955" alt="08eda44168bd856219fd27af5cb3fb8" src="https://github.com/user-attachments/assets/4b58c6fe-8495-4453-ad9a-1a27549604fe">
4.点击全屏预览显示的值仍然是总的，而非设置的默认值
<img width="299" alt="42013c42140692417fb165412013817" src="https://github.com/user-attachments/assets/ef90fcbf-bf86-4825-a1bc-502f925ab3ff">
<img width="570" alt="9bde53d33368c4887f715deb2c50624" src="https://github.com/user-attachments/assets/583594c2-fc83-48d1-8a5e-f21f6d744d88">

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #11047
