### ISSUE TITLE
[Bug]符号地图调节符号大小不生效

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#11038]
**DataEase 版本**

v2.8.1
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
符号地图调节符号大小不生效，选择几号大小都是一样的大小，没有改变

**Bug 重现步骤(有截图更好)**
![未命名](https://github.com/user-attachments/assets/d1211be3-3e94-4666-92b6-a8a70c3f46de)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问是否设置了气泡大小，若在气泡大小中添加了字段则样式中大小则不会生效，因为会强制按照你的添加的字段数量觉得气泡大小的显示的；
