### ISSUE TITLE
[Bug]过滤组件设置默认值时对富文本未生效

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#11047]
**DataEase 版本**
2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装部运行

**浏览器版本**
Chrome 最新版

**Bug 描述**
过滤组件设置默认值时对其他图表生效，但是对富文本未生效。

**Bug 重现步骤(有截图更好)**
1.仪表板上同时有富文本组件及其他组件，使用的相同数据集；
2.设置过滤组件并设置默认值，关联图表包括富文本及其他组件：
![image](https://github.com/user-attachments/assets/48a0a22d-03e1-44a4-9ffb-6c5c7bd346c9)
3.预览仪表板时，过滤组件中带的值”武汉一店“仅对下图中表格生效了，富文本数据未被过滤：
![image](https://github.com/user-attachments/assets/cf29ef7b-4404-45e5-9013-9333fb1c2096)
4.手动对”武汉一店“执行一次查询后，富文本才生效。
![image](https://github.com/user-attachments/assets/62cf6f73-99a8-4d83-9995-f8a645ebafe3)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们在下个版本解决。
