### ISSUE TITLE
仪表板-移动端布局-筛选组件-日期筛选-无法正常使用

### ISSUE THREAD

**Issue by 2023fan** [dataease/dataease#11042]
**DataEase 版本**
V2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
最新版

**Bug 描述**
仪表板-移动端布局-筛选组件-日期筛选
展示类型：时间范围
时间颗粒：年月 
PC端可以正常使用，移动端无法使用

**Bug 重现步骤(有截图更好)**
1.新建一个时间筛选组件，展示类型：时间范围，时间颗粒：年月 （一定要选这个）
![image](https://github.com/user-attachments/assets/9fc97e9d-8ea1-45c1-8cc8-91008e52069b)

2.开启移动端布局，选中筛选组件
3.生成一个公共链接，用手机打开
4、测试筛选组件，会发现无法使用

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
