### ISSUE TITLE
[Bug]筛选组件的查询条件配置一个和图表所使用的不同的数据集时，保存完仪表板再进入会丢失

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#11048]
**DataEase 版本**
2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 最新版

**Bug 描述**
筛选组件的查询条件配置一个和图表所使用的不同的数据集时，保存完仪表板再进入会丢失

**Bug 重现步骤(有截图更好)**
1.配置筛选组件如下：
![image](https://github.com/user-attachments/assets/a44cde2a-cd5a-417c-a46b-1182e1c1240e)

2.保存仪表板
![image](https://github.com/user-attachments/assets/2ad34681-0c59-44c3-9575-7613f611776b)

3.重新编辑仪表板
![image](https://github.com/user-attachments/assets/9c94fa18-77b2-482e-bdbc-21a81ca14c67)

4.重新进入刚才配置的筛选组件的编辑界面，发现之前的配置不见了
![image](https://github.com/user-attachments/assets/1907130c-7df1-4cef-9db8-3a3033c5ce45)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
