### ISSUE TITLE
[Question]v1.18.23源码编译报错

### ISSUE THREAD

**Issue by wolfgang1219** [dataease/dataease#11061]
**请描述您的问题.**

`[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for dataease 1.18.23:
[INFO] 
[INFO] dataease ........................................... SUCCESS [  0.600 s]
[INFO] frontend ........................................... SUCCESS [01:42 min]
[INFO] mobile ............................................. SUCCESS [01:16 min]
[INFO] backend ............................................ FAILURE [07:51 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:50 min
[INFO] Finished at: 2024-07-22T10:30:54+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project backend: Could not resolve dependencies for project io.dataease:backend:jar:1.18.23: The following artifacts could not be resolved: org.apache.commons:commons-compress:jar:1.27.0-SNAPSHOT, io.dataease:dataease-plugin-interface:jar:1.18.23, io.dataease:dataease-plugin-view:jar:1.18.23, io.dataease:dataease-plugin-datasource:jar:1.18.23, pentaho-kettle:kettle-core:jar:8.3.0.18-1112, pentaho-kettle:kettle-engine:jar:8.3.0.18-1112, pentaho:metastore:jar:8.3.0.18-1112, org.pentaho.di.plugins:pdi-engine-configuration-impl:jar:8.3.0.7-683: Could not find artifact org.apache.commons:commons-compress:jar:1.27.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :backend`

**Comment by xuwei-fit2cloud** [comment]
可以参考一下在线文档：

[开发环境搭建](https://dataease.io/docs/v1/dev_manual/dev_manual/)
[【常见问题】编译源码时，dataease-plugin 相关依赖无法拉取](https://kb.fit2cloud.com/?p=107)
[编译 DataEase 项目源码的时候报错，提示缺少依赖](https://dataease.io/docs/v1/faq/dev_faq/)
