### ISSUE TITLE
[Bug]视图放大后视图标题样式丢失，一直是一个默认大小，用户反馈太小了，且无法调整，v1 、v2.8.0 等版本都有这个情况

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11082]
**DataEase 版本** v2.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
google

**Bug 描述**
视图放大后视图标题样式丢失，一直是一个默认大小，用户反馈太小了，且无法调整，v1 、v2.8.0 等版本都有这个情况

**Bug 重现步骤(有截图更好)**
1. v2 下使用明细表测试，调整单元格标题样式、标题样式
![image](https://github.com/user-attachments/assets/6688e4a4-30a9-4ce3-ac00-a07b4977b899)

2.视图组件放大，单元格样式可以显示样式，标题样式恢复默认
3. 用户 v1 下也存在这个问题

**Comment by BBchicken-9527** [comment]
感谢反馈，图表放大后标题样式与画板中的标题是没有关系的，所以样式丢失是不成立的；
