### ISSUE TITLE
[Bug]外观设置之后移动端不生效

### ISSUE THREAD

**Issue by Xyuncheng** [dataease/dataease#11096]
**DataEase 版本**
v2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome（123.0.6312.59）

**Bug 描述**
在系统设置的外观配置中进行 logo 的替换，发现电脑打开的已经替换了，但是移动端的还保持原样。以下为现象截图
![c50caf78a3f75dcdf5776ba7798e0c0](https://github.com/user-attachments/assets/149169ec-0121-4cf1-bdaa-4c6fdb387342)
![7255107d5636eaaf0044a889807ea17](https://github.com/user-attachments/assets/c2f07991-1834-4a7e-b2a8-66a27d01b422)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，移动端目前还没有支持外观设置，您的建议非常不错，我们会规划在后面的版本中进行支持。
