### ISSUE TITLE
[Bug]登录状态下访问公共链接，无法导出视图数据

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#11095]
**DataEase 版本**
1.18.20

**运行方式(安装包运行 or 源码运行 ?)**
访问官网体验

**浏览器版本**
chrome 126

**Bug 描述**
登录状态下访问公共链接，无法导出视图数据

**Bug 重现步骤(有截图更好)**
1.登录
2.创建仪表板
3.创建公共链接
4.在登录状态下访问公共链接
5.点击视图，点击下载
6.弹出“后台导出中,可前往数据导出中心查看进度，进行下载”
7.点击“数据导出中心”无反应

![image](https://github.com/user-attachments/assets/9b5e812e-3599-4d7b-8e4a-a94b2a33c636)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前最新版本已经修复此处的处理，可以下载最新版本进行体验；
