### ISSUE TITLE
[Bug]创建/编辑新仪表板的加载是不是有点慢了？我自己本地启的貌似也会这样，看了这个 demo 体验环境也是，有时完全就卡住了

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11098]
**DataEase 版本**
2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
创建/编辑新仪表板的加载是不是有点慢了？我自己本地启的貌似也会这样，看了这个 demo 体验环境也是，有时完全就卡住了

**浏览器版本**
google

**Bug 描述**
我感觉跟配置没太大关系，https://demo.dataease.cn/websocket/785/w1v4pzrg/xhr_streaming?userId=1&t=1721702982275，这个，其他都几十毫秒，说明没问题，就这个接口有点问题，你们可以瞅瞅

**Bug 重现步骤(有截图更好)**
1.![9a408042-c44b-41f1-9723-460acb1d38d5](https://github.com/user-attachments/assets/480a1652-cbde-491d-afac-127e62384c58)
![6e540841-5f75-4168-8dfd-b88c7372d21c](https://github.com/user-attachments/assets/66d5ecab-c76f-429e-97bd-bc9702cde42a)

2.刷新了几次都卡到最后不动了
![e60a3cc8-5fef-4fa4-b41b-91be09f1b211](https://github.com/user-attachments/assets/3483abcb-aa27-49b4-8484-25e762b44508)
![ac4f560d-b08f-4394-8816-6dce21686403](https://github.com/user-attachments/assets/a2205abd-9475-42eb-88d1-9f9027c6e7af)

3.点击新建的地方

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行优化；
