### ISSUE TITLE
[Bug] 行权限添加满后无法翻页

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#11119]
**DataEase 版本**
v2.8.1 版本

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌浏览器

**Bug 描述**
行权限页面点击第二页翻页无反应
![image](https://github.com/user-attachments/assets/2204ce34-30b5-416e-922f-072fb67ac76a)

**Bug 重现步骤(有截图更好)**
1.添加多条行权限，点击第二页无反应

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
