### ISSUE TITLE
[Feature]能否新增图层绑定，或者图层合并，类似photoshop那种

### ISSUE THREAD

**Issue by dividduang** [dataease/dataease#11117]
DataEase 版本:
v1.8

**请描述您的需求或者改进建议.**
在调整模板图层的位置的时候，当要调整背景图层和数据图层，icon图层的时候，我就需要挪动三次。希望以后新增一个类似photoshop那种图层绑定，或者图层合并的功能
祝好！
感谢！

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持，建议您试用2.x的数据大屏。
