### ISSUE TITLE
[Bug] Oracle 数据源， 自定义 SQL，添加参数异常报错。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#11110]
**DataEase 版本**
v2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 126.0.6478.183（正式版本） (arm64)

**Bug 描述**
Oracle 数据源， 自定义 SQL，添加参数异常报错。

**Bug 重现步骤(有截图更好)**
1. 自定义 SQL 如下所示：
`select * from ((
select * 
from QRTZ_TRIGGER_LOG
where job_id = '${job_id}'))`

2. 此时执行报无效数字异常
![image](https://github.com/user-attachments/assets/b917fd10-21de-487b-a8b1-4c3c590295ce)

3. 设置默认参数后，可正常查询
![image](https://github.com/user-attachments/assets/d5b0667f-b194-433b-a528-d579c0bb085b)

4. 若去掉一层括号，不设置默认参数，也可查询
![image](https://github.com/user-attachments/assets/6c92c758-5c5f-443e-9f65-98bbf29d295b)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
