### ISSUE TITLE
[Feature] 仪表盘过滤条件联动

### ISSUE THREAD

**Issue by caiiansheng** [dataease/dataease#1113]
很多场景 多个过滤条件之间是联动的，比如部门和产品信息，部门选择后，部门对应产品信息自动更新
![issue](https://user-images.githubusercontent.com/26760483/139810985-b05f9290-f5cb-4d6f-8773-9c7082c0bfff.PNG)

**Comment by yayanpei** [comment]
感谢您的反馈，已经在需求清单中，会根据优先级在接下来的版本中支持的。

**Comment by xuwei-fit2cloud** [comment]
v1.11.0支持了下拉树组件，可以试试。
