### ISSUE TITLE
[Bug]2.8.1 升级后覆盖了自定义数据库配置，导致升级后恢复成了内置数据库链接和密码

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#11148]
**DataEase 版本**
 v2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
1. 升级前后配置文件被修改
升级前配置如图：
![11971721802508_ pic](https://github.com/user-attachments/assets/3bdc76e0-dc04-4214-b41a-03fb2f5ff555)
![11981721802528_ pic](https://github.com/user-attachments/assets/c7baf120-4319-44ee-8346-5a6d61a7d8cf)

升级过程：
![image](https://github.com/user-attachments/assets/a74dd95f-6efd-4c3c-8a39-83754f56f0f1)

升级后配置文件：
![image](https://github.com/user-attachments/assets/c2c98721-0ca9-41e7-a9ad-4873e200368d)

2. 升级过程配置文件被覆盖，导致之前配置的端口映射、application.yml 中的嵌入式配置全部被恢复，每次升级都需要修改
![image](https://github.com/user-attachments/assets/4e9feb2a-d95a-4593-96c9-3784ba260359)

3. 执行升级提示的是安装完成，提示的依然是默认访问链接和密码，期望提示升级完成，且不再提示密码
![image](https://github.com/user-attachments/assets/502f692e-014d-458a-bc1b-15431592c8f8)

4. 当密码存在特殊字符时，升级过程有报错
![image](https://github.com/user-attachments/assets/72a07fe0-8487-423f-97f3-0d0b23e82dde)

**期望**
1.修改过的自定义数据库地址、密码升级后不覆盖
2.修改过的端口映射、配置文件不被覆盖
3.安装后的提示区分首次安装和升级的提示信息
4.兼容特殊字符密码

**Comment by xuwei-fit2cloud** [comment]
1.修改过的自定义数据库地址、密码升级后不覆盖
> 问题没有复现；

2.修改过的端口映射、配置文件不被覆盖
> 端口和需要调整的配置我们在后面版本可以增加到配置文件中；

3.安装后的提示区分首次安装和升级的提示信息
> 下个版本优化一下；

4.兼容特殊字符密码
> 使用特殊字符作为密码时，可以将密码用双引号括起来，例如 DE_MYSQL_PASSWORD="Test@4&^%*^"

**Comment by liuboF2c** [comment]
1.修改过的自定义数据库地址、密码升级后覆盖
可能与首次安装修改了数据库密码有关，详情请看视频
4.兼容特殊字符密码
如视频，安装时双引号填写的密码没有写入.env
另外希望在 install.conf 中说明一下如果有特殊字符，需加双引号。或默认添加双引号，并备注说明。

https://github.com/user-attachments/assets/3b230e78-422f-4f77-9bcf-9a3d12c78ef9
