### ISSUE TITLE
[Bug] 设置访问路径后，嵌入式 demo 运行 iframe 嵌入失败

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#11157]
**DataEase 版本**
v2.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌浏览器

**Bug 描述**
参考知识库[文章](https://kb.fit2cloud.com/?p=57a47d64-4eda-4ae8-a0b0-4329e57b13ff)设置访问路径为 /dataease 后
嵌入式 demo 运行 div 没有问题，但是 iframe 嵌入失败

**Bug 重现步骤(有截图更好)**
1.安装包部署 DataEase v2.8 嵌入式
2.参考知识库[文章](https://kb.fit2cloud.com/?p=57a47d64-4eda-4ae8-a0b0-4329e57b13ff)设置访问路径为 /dataease
3.嵌入式 demo 运行 div 没有问题，运行 iframe 嵌入失败

**Comment by BBchicken-9527** [comment]
感谢反馈，问一下异常是什么？方便的话给我们看一下相关日志以便我们进行排查；

**Comment by janus177** [comment]
> 感谢反馈，问一下异常是什么？方便的话给我们看一下相关日志以便我们进行排查；
跑嵌入式 demo 的时候，嵌入仪表板时，该接口报错
![image](https://github.com/user-attachments/assets/cf0f3fb2-c761-4fdb-a29f-2785f7d49ad8)

嵌入设计器，以下4个接口报错
![image](https://github.com/user-attachments/assets/0a8dc04a-00a8-43ab-bb63-7d9299c42af1)

**Comment by yufuchen** [comment]
你好，iframe嵌入需要配置一下origin-list属性，具体文件为：/opt/dataease2.0/conf/application.yml，如果安装目录不是/opt/dataease2.0，请使用自定义的安装目录。在文件的dataease节点下，增加origin-list属性，属性值为DataEase的访问地址。参考如下：
<img width="1191" alt="image" src="https://github.com/user-attachments/assets/5d982c2c-9b06-48fe-9a06-6038795eb467">

**Comment by janus177** [comment]
> 你好，iframe嵌入需要配置一下 origin-list 属性，具体文件为：/opt/dataease2.0/conf/application.yml，如果安装目录不是 /opt/dataease2.0，请进入自定义的安装目录。在文件的 dataease 节点下，增加 origin-list 属性，属性值为 DataEase 的访问地址。参考如下： <img alt="image" width="1191" src="https://private-user-images.githubusercontent.com/28720310/355008584-5d982c2c-9b06-48fe-9a06-6038795eb467.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MTM4NDMsIm5iZiI6MTcyMjkxMzU0MywicGF0aCI6Ii8yODcyMDMxMC8zNTUwMDg1ODQtNWQ5ODJjMmMtOWIwNi00OGZlLTlhMDYtNjAzODc5NWViNDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDAzMDU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NTM1NzkwYmFhYmU5M2VmMGMxZWI1ZjI4ZmFiOTgzNmY5ZTY1MmQ0MWZmZDc2MjY4Mjg5NGZmNDViNzVmNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UqSL8rNwatm6bJhHk3wGHYHuAYJJQ_QpK9TItu_B6gQ"> 修改文件后，重启 DataEase 服务。

嗯嗯，添加完 origin-list 属性，还是不行，我这边是有加二级目录
![image](https://github.com/user-attachments/assets/4d9e4068-2c9a-4065-825a-ee05e6afa4b1)
