### ISSUE TITLE
[Bug]视图-对称条形图-样式-横轴中间的标签颜色和大小无法调节

### ISSUE THREAD

**Issue by 2023fan** [dataease/dataease#11155]
**DataEase 版本**
2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌最新版

**Bug 描述**
视图-对称条形图-样式-横轴中间的标签颜色和大小无法调节
<img width="960" alt="770801bfa865501fdcff7923c37bf93" src="https://github.com/user-attachments/assets/24bc299f-a0dc-4510-a200-921e1fb52124">

**Bug 重现步骤(有截图更好)**
1.新建一个对称条形图
2.样式-横轴-调一下标签颜色及大小
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前已经修复，可以下载最新版本进行体验；
![image](https://github.com/user-attachments/assets/aa042393-f2a4-4231-8de6-6b6696d3135f)
