### ISSUE TITLE
[Feature]仪表板图层切换后希望立即生效

### ISSUE THREAD

**Issue by zyyfit** [dataease/dataease#1115]
**请描述您的需求或者改进建议.**
仪表板图层切换后需要再拖动一下仪表板才会生效，建议优化一下这里

![图片](https://user-images.githubusercontent.com/73461316/139824207-b8afbc89-30c9-4543-87da-bbaa82c6aab1.png)

**Comment by yayanpei** [comment]
感谢反馈，您的建议非常好，我们会根据优先级安排在后面的版本中优化。

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 版本已支持。
