### ISSUE TITLE
筛选框的级联不能选择非仪表板中的数据集.[Bug]

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#11177]
**DataEase 版本** V2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行.

**浏览器版本** 谷歌.126.0.6478.127（正式版本）

**Bug 描述**
在筛选框配置 级联时， 选择非 仪表板中出现的 数据集， 查询组件级联配置 按钮打不开。
![3a9c40f1797b7dc86504d5d30efc394](https://github.com/user-attachments/assets/aae368a6-1889-4c59-8c2a-c8c12b1936d9)

![67f40b0d7bb0850e98d43bd6004ca70](https://github.com/user-attachments/assets/93b7e321-9b73-4cc5-8477-de1b531fd9ac)

![43789a38b651318620af5a2bceb4689](https://github.com/user-attachments/assets/f478ff78-3e9a-4d00-99e1-4a886c1981d8)

浏览器debug看， 这里出现 js 报错， 原因是 选择的数据集 找不到。  估计是限制了只能选择该仪表板出现过的。 
但是这样的话， 比如我有多个图形， 每个图形代表一类。 我如果选择一个已出现的。  会导致我筛选框的值不全. 

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你的意思是使用关联数据集创建导致异常吗？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
