### ISSUE TITLE
[Bug]指标卡视图的标题调整垂直位置无效

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1117]
**DataEase 版本**
V1.3.0

**浏览器版本**
Chrome 95

**Bug 描述**
对指标卡视图调整其标题位置，其文字始终位于上方，点击中、下，位置并未变动

**Bug 重现步骤(有截图更好)**
1.标题位置初始在上方
![image](https://user-images.githubusercontent.com/48945409/140019308-b9fe16da-9282-4887-a112-625c6ae7b371.png)

2.修改为中，仍然在上方
![image](https://user-images.githubusercontent.com/48945409/140019344-af7d63ef-a3e7-4f41-8cd0-10b8b77f8ede.png)

3.修改为下也是一致的
![image](https://user-images.githubusercontent.com/48945409/140019365-15bcbfe9-0d76-462f-bc16-7d2a1a8c129f.png)

4.尝试其他内容的调整，是有效的
![image](https://user-images.githubusercontent.com/48945409/140019413-84e0d523-6743-48a7-a949-66e94d25fc80.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 已修复
