### ISSUE TITLE
[Feature]数据大屏复用的时候，希望支持将组件的坐标和大小都按照原来的样式复用过去，不然每次复用后都要重新调整

### ISSUE THREAD

**Issue by Aiolimp** [dataease/dataease#11170]
DataEase 版本:

**请描述您的需求或者改进建议.**

**Comment by luca-woo** [comment]
同样需求，是个痛点，TAB还有一个很蛋疼的地方是一个tab的内容后，其他tab的排版都乱了

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，组件的大小和样式，支持按照原先的样式和大小，已经加入近期的版本迭代中。组件的坐标目前暂时没有计划支持。

**Comment by ziyujiahao** [comment]
https://github.com/dataease/dataease/pull/11533/commits/86f49da257e234d51cd2a49d354de6dbaa2a8b71
