### ISSUE TITLE
[Bug] 应用大屏模板后，全屏显示问题

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#11174]
**DataEase 版本**
2.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome 最新

**Bug 描述**
应用大屏模板后，全屏的时候上下部分有有留白。

**Bug 重现步骤(有截图更好)**
1.
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/adcae4e9-8d99-4e03-bd0e-3f045b189d99">

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，数据大屏的全屏是根据你的画板尺寸去显示的，如果你的画板尺寸不满足全屏显示则会上下留白显示；

**Comment by xuwei-fit2cloud** [comment]
数据大屏一般用于比较精细的图表制作，所以数据大屏的自适应是根据宽高比适应的。
仪表板是根据整体去适应的。如果不希望留白的话，建议试试仪表板。
