### ISSUE TITLE
[Feature]【主题设置】侧边栏支持颜色调整

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#11186]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
侧边栏支持按照 hex 色号去调整配色
![image](https://github.com/user-attachments/assets/2d392ec2-b8a5-4a9e-b913-e7eb914beb0c)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持。
