### ISSUE TITLE
创建postgresql 15数据源报错

### ISSUE THREAD

**Issue by buttonwang** [dataease/dataease#11182]
**DataEase 版本**
2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge
版本 126.0.2592.113 (正式版本) (64 位)

**Bug 描述**
在数据源管理中创建postgresql数据源， 目标数据库是postgresql version 15.0
使用127.0.0.1地址连接，获取schema提示“Connection to 127.0.0.1:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.”
使用网络地址10.3.28.210连接，获取schema提示“致命错误: 没有用于主机 "172.18.0.3", 用户 "postgres", 数据库 "netbox", no encryption 的 pg_hba.conf 记录”， IP地址提示不对了。
**Bug 重现步骤(有截图更好)**
![1721900499848](https://github.com/user-attachments/assets/39c5d629-e540-45ec-8716-c614fe7df252)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，可以尝试升级看看；
![image](https://github.com/user-attachments/assets/1eddf735-e9c1-46cf-b550-ac3df8333f09)
