### ISSUE TITLE
[Bug]数据集等名称较长时不显示可以打开操作的三个小点

### ISSUE THREAD

**Issue by xun986** [dataease/dataease#1118]
**DataEase 版本**
1.2.1

**浏览器版本**
Safari14.0.3

**Bug 描述**
上传的数据集名称比较长的时候，鼠标移动到名称最右侧就不会出现那三个小点，不方便打开重命名、移动和删除的操作

**Bug 重现步骤(有截图更好)**
1.数据集名称较长，鼠标移动到名称最右侧就不会出现那三个小点
2.数据集名称也不能通过左右拖拽或鼠标左划来显示数据集名称的最末尾处，从而出现三个小点
3.拉宽左侧边栏的程度是有限的，只有数据集名称在一定长度内才能通过这个方法来显示三个小点
4.综上所述，我觉得把那三个小点设置浮在每一个数据集名称靠近左边栏右侧界限的位置，而不是放在文字末尾比较好。就是说虽然名称没有显示全，但鼠标移动到使用者能看到的数据集名称最右侧就能出现三个小点会比较好。

**Comment by xuwei-fit2cloud** [comment]
可以升级到1.4 版本试试，新版本没有出现这个问题。

**Comment by xun986** [comment]
了解了
