### ISSUE TITLE
[Bug]【仪表板】筛选条件参数情况下选择不了时间范围类型

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#11194]
**DataEase 版本**
v2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
【仪表板】筛选条件参数情况下选择不了时间范围类型
![image](https://github.com/user-attachments/assets/c2940756-8058-4df4-85c5-a2add8cc1a70)

1.数据集截图
![image](https://github.com/user-attachments/assets/dd2a77e9-77c0-4cd6-bbf3-186ccc46ed0c)

2.参数截图
![image](https://github.com/user-attachments/assets/9dd9768a-529e-4b9e-bbc8-b9cb8959906f)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前参数还不支持时间范围，后续我们会逐步进行支持，请耐心等待；
