### ISSUE TITLE
[Feature]查询组件的两条滚动条客户反馈不美观，能否优化一下

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11195]
DataEase 版本:  2.8.1

**请描述您的需求或者改进建议.**

查询组件的两条滚动条客户反馈不美观，能否优化一下

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，请追加一下截图。

**Comment by yayanpei-fit2cloud** [comment]
重复issue（https://github.com/dataease/dataease/issues/11266 ）
