### ISSUE TITLE
v2.8.1 仪表板tab中包含多个表格时，下拉会出现卡顿情况[Bug]

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#11190]
**DataEase 版本** v2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装表运行

**浏览器版本**

**Bug 描述**
v2.8.1 仪表板tab中包含多个表格时，下拉会出现卡顿情况

**Bug 重现步骤(有截图更好)**
1. 在仪表板中使用tab
2. 在tab中放置多个表格，使tab在一页展示不下，需要往下拖动的场景.
3. 往下拖动的时候，明显会感觉中间卡顿了一下.

**Comment by BBchicken-9527** [comment]
感谢反馈，我不是很确定你说的卡顿是什么表象，方便的话能录个视频吗？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
