### ISSUE TITLE
[Feature]类似这个数据集的左右轴都在一个范围，就难通过调坐标轴的max,min来分隔柱形图和折线图，那种范围没什么交集的能这么操作才有效果。如果能默认加个偏移就好了，类似MPAndroidChart那种

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11196]
DataEase 版本:2.8.1

**请描述您的需求或者改进建议.**
类似这个数据集的左右轴都在一个范围，就难通过调坐标轴的max,min来分隔柱形图和折线图，那种范围没什么交集的能这么操作才有效果。如果能默认加个偏移就好了，类似MPAndroidChart那种
![f5e523d6-07bb-4a44-8953-125d8021e58d](https://github.com/user-attachments/assets/06adfcce-4b07-4f29-a7cb-78031b28db60)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，请问需要怎么分隔柱形图和折线图？烦请将效果图追加到评论区。

**Comment by zhainanshidai** [comment]
就是比如图片中折线图很多时候并不想和统计图有交叉，想更清晰体现出数据的情况，但是实际上数据的范围不确定之下，很难精细地调整到这样的效果，特别是数据不相近的时候才能这样去调，如果有个偏移量就很省事了，让图表有一定的偏移，使得数据更清晰。

**Comment by yayanpei-fit2cloud** [comment]
建议按照下图所示自定义左、右纵轴的轴值
![image](https://github.com/user-attachments/assets/80225ad9-b846-45b0-8e99-41151c171a86)
