### ISSUE TITLE
[Question]查询条件下选择日期范围时，如何跟SQL中的参数进行绑定？

### ISSUE THREAD

**Issue by paopaoteng** [dataease/dataease#11193]
查询条件选择范围时，查询条件应该有两个值（起始日期与截止日期），这时候怎么跟SQL中的参数进行绑定呢？

**Comment by yayanpei-fit2cloud** [comment]
请参考下图所示，添加查询条件：开始日期、结束日期，然后分别绑定SQL中的开始日期参数和结束日期参数
![image](https://github.com/user-attachments/assets/981683bc-401b-4df5-8dd2-ef7b91f14bc2)

**Comment by xuwei-fit2cloud** [comment]
请升级版本。
https://dataease.io/docs/v2/change-v2-10-2/#16
