### ISSUE TITLE
跨多个查询控件的筛选框联动[Feature]

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#11199]
DataEase 版本: v2.8

**请描述您的需求或者改进建议.**
在第一个筛选框有一级，二级业务模块，下面的图表用来展示属于一二级的。

第二个筛选框中有三级业务模块， 下面的报表用来展示三级业务模块特有的报表。

目前多个筛选框之间不能配置级联。 期望在同一个仪表板，多个筛选框也能配置级联.

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池中

**Comment by xuwei-fit2cloud** [comment]
请升级版本。
