### ISSUE TITLE
[Bug]选项设置了默认值，然后展开下拉默认值没有选中，还有手动点一下

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11198]
**DataEase 版本**
2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
google

**Bug 描述**
[Bug]设置了默认值，然后展开下拉默认值没有选中，还有手动点一下

**Bug 重现步骤(有截图更好)**
1.
2.
3.
![cfb5bb0b-314b-4084-ac0d-8c030c2180c4](https://github.com/user-attachments/assets/1c14d88d-55b9-4e9f-8c2d-7d17c00e14ce)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现此类问题，建议升级到最新环境中尝试；
