### ISSUE TITLE
[Feature]支持修改图标的横轴和纵轴的刻度字体大小

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#112]
**请描述您的需求或者改进建议.**
支持修改图标的横轴和纵轴的刻度字体大小
同时能支持最小字体能小于10，有时候10号字体挺大的，最小一般是6，可以与一般常用软件保持一致

**Comment by yayanpei** [comment]
首先感谢您的反馈，下个版本V1.1.0 会支持图表横纵轴刻度字体大小、颜色等调整，最小字体和所使用的插件有关，后期我们内部会就这个优化进行讨论

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已支持
