### ISSUE TITLE
[Feature]期望数据源格式支持wps原生格式.et文件和在线文档

### ISSUE THREAD

**Issue by zjdc** [dataease/dataease#11209]
DataEase 版本:V2.8.1

1. 目前DEv2支持的本地文件格式有excel和csv，部分企业的本地文件需要经过加密，不能使用excel和csv，需要使用wps原生的.et文件或者使用在线文档。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，建议您将wps文件转换为excel后，再进行上传。
