### ISSUE TITLE
[Bug]使用K8S部署dataeasev2版本，存储使用ceph对象存储，apisix无法初始化

### ISSUE THREAD

**Issue by daviadong** [dataease/dataease#11201]
**DataEase 版本**
dataease-v2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
k8s部署

**浏览器版本**

**Bug 描述**
看了https://kb.fit2cloud.com/?p=c26a1a5a-7c02-4938-8c23-65e1ea44d430中的k8s部署方式，存储采用的ceph。部署完后apisix和apisix-dashboard 都是CrashLoopBackOff，apisix-etcd会自动变成CrashLoopBackOff状态。查看报错：/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
本以为是我K8S的问题，但更换存储使用NFS就正常了，权限是没问题的，初步判断原因是apisix无法初始化造成，在K8S中创建 etcd 会有需要初始化 initContaner 这个步骤 但是我看在我们的 helm 中并为发现，请问是否是有遗漏。

**Bug 重现步骤(有截图更好)**
1.
<img width="804" alt="截屏2024-07-26 下午9 11 53" src="https://github.com/user-attachments/assets/1aa6a913-604e-475f-be92-325848e0b806">
2.
<img width="580" alt="截屏2024-07-26 下午9 15 14" src="https://github.com/user-attachments/assets/35b3a316-947a-4192-a397-139df4f5d66d">

**Comment by BBchicken-9527** [comment]
感谢反馈，apisix使用etcd存储的，没支持ceph的，k8s是自带etcd，可以使用etcd试一下；
