### ISSUE TITLE
[Bug]SQLServer 2019 使用自建的 Schema 时，拖拽表创建数据集报错

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#11202]
**DataEase 版本**
v2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新

**Bug 描述**
SQL Server 2019 数据库信息如图
<img width="1277" alt="image" src="https://github.com/user-attachments/assets/88e9acca-31cb-4d6a-8675-72e716425ec8">

使用 DataEase 创建数据源如图
<img width="1025" alt="image" src="https://github.com/user-attachments/assets/490cf115-e523-4b1f-9a55-197c29cc2870">

创建数据集刷新数据时报错如图
<img width="1675" alt="image" src="https://github.com/user-attachments/assets/3e571a91-56db-4ef0-a0b9-4917577b088c">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
