### ISSUE TITLE
[Feature]富文本支持超链接

### ISSUE THREAD

**Issue by Xyuncheng** [dataease/dataease#11216]
DataEase 版本:
v2.8.1

**请描述您的需求或者改进建议.**
在v1 的版本中，富文本是可以支持超链接设置的；到 v2 的版本之后这个功能就没有了，希望能加上。
![24ccad91c052efa2a91704ceb4f7df7](https://github.com/user-attachments/assets/d40b771a-97f3-48ea-b4a6-9d81a246d03f)
![5c5162a00cf96439a1e8d6bb471f296](https://github.com/user-attachments/assets/6fe40818-f9ef-45e4-b88c-1561cdf7356e)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请参考下图所示制作超链接
![image](https://github.com/user-attachments/assets/5f40e4a1-f75d-4fbc-9c40-fcc686ab3481)

**Comment by Xyuncheng** [comment]
您说的这个实现效果v1也有，但是v1还额外多了一个；
![59f5a40efeed50f69621b0bacf7b63c](https://github.com/user-attachments/assets/dc63598f-6696-4f8e-a8d2-941148a5ca57)
![cc02dcbbf4adb4bbba76fb933349d83](https://github.com/user-attachments/assets/d55f0efa-1455-4b22-a484-d075573d632b)
并且这个设置出来的效果是给某个字加跳转链接，相当于是内部链接了，不是超链接，希望还是能再优化一下，最起码是把 v1 的实现方式整过来，感谢！

**Comment by yayanpei-fit2cloud** [comment]
好的，了解。
