### ISSUE TITLE
[Bug]【数据源】API 同步数据异常

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#11218]
**DataEase 版本**
v2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
同一个接口，读取的层级不同，一个层级可以在数据集查询数据，一个层级数据源可以读取数据但是数据集不显示数据。
![image](https://github.com/user-attachments/assets/ace13de6-c2dc-4b02-83b7-e30d17c2b1de)
![image](https://github.com/user-attachments/assets/54560173-afb2-4c4f-9d4b-16b5982ff015)

**Bug 重现步骤(有截图更好)**
1.status 层有数据。
![image](https://github.com/user-attachments/assets/8c03dc3e-89ee-48b2-bd81-c0cd0e81e4f6)
![image](https://github.com/user-attachments/assets/1cf08c59-adff-422c-ab73-7bff8d332f8b)

2.result 层没数据。
![image](https://github.com/user-attachments/assets/800c3481-6e12-4623-ae20-5a50dfae9ee1)
![image](https://github.com/user-attachments/assets/a2727e2d-563e-40a0-ad85-f8c4ebcd9e3f)

3.相关配置如下：
POST 请求地址：https://www.kdocs.cn/api/v3/ide/file/cpp4EgN690Nv/script/V2-3Tu1RDdYTG28t9UO7n69cq/sync_task

请求头参数：
Content-Type：application/json
AirScript-Token：2LZtFcvq49UFu3ONQ3CXPs
![image](https://github.com/user-attachments/assets/6c2251af-9bab-4af9-9484-cc03a49bea71)

请求体（json）：
{
    "modelType": "dataset"
}{
    "Context": {
        "argv": {
            
        }
    }
}
![image](https://github.com/user-attachments/assets/d9e10da2-c4c9-4f35-8231-a07a26911ca0)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
