### ISSUE TITLE
[Feature]图表放大后可以导出数据

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#11210]
DataEase 版本:
v2

图表放大查看后，可以直接在当前界面导出数据；
目前放大后的界面没有导出数据，需要关闭--再点击导出数据按钮。增加操作步骤，不太方便。
<img width="1948" alt="图片" src="https://github.com/user-attachments/assets/3a9d95cc-df32-4c5a-a775-256faab46667">

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，目前暂时没有计划支持，如果需要导出数据，建议点击导出按钮，并选择导出为excel，如下图所示：
<img width="755" alt="image" src="https://github.com/user-attachments/assets/b7d1a93e-7adf-4711-8777-0985b35c3e4a">
