### ISSUE TITLE
[Bug] 图表跳转配置 key-value 的过滤组件，过滤不生效

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#11230]
**DataEase 版本**
v2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 126.0.6478.127

**Bug 描述**
图表跳转配置 key-value 的过滤组件，过滤不生效

**Bug 重现步骤(有截图更好)**
![image](https://github.com/user-attachments/assets/d7fa196d-b0e8-4c94-913f-c79a3007058a)

**Comment by BBchicken-9527** [comment]
感谢反馈，跳转字段应该使用显示字段而非查询字段；
