### ISSUE TITLE
[Bug]仪表板模块嵌入后，不能看到仪表板的名称

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#11241]
**DataEase 版本**
v2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome  127.0.6533.72

**Bug 描述**
本地运行嵌入式的demo（https://embedded-bi.dataease.cn/#/home/index），使用mac电脑，查看仪表板模块，仪表板的名称不展示，使用Windows访问正常
mac操作系统如下：
![image](https://github.com/user-attachments/assets/d2019191-62d4-4c7c-af1f-77d810a28508)

浏览器版本如下：
<img width="769" alt="3b9b7b89bf59056ed3504282efd7d10" src="https://github.com/user-attachments/assets/45e1e370-27ae-4146-a9f4-acf57600febd">

**Bug 重现步骤(有截图更好)**
<img width="1043" alt="1cacdfc93b22e61894c6c25d7a9dadd" src="https://github.com/user-attachments/assets/f948c045-8ea8-427f-be57-0ae8bba37900">

1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈目前最新版本的div 和iframe嵌入式没有发现你说的问题，可以尝试升级看一下，这里我先将问题关掉如果依然存在问题可以随时将问题打开或联系我们公众群会有非常专业的小伙伴尝试帮你解决；
![image](https://github.com/user-attachments/assets/dd6454d4-2224-48ec-bc03-d4f3bf3da137)
![image](https://github.com/user-attachments/assets/738e91cc-37a1-40b9-8e91-a118ab5fc2a4)
