### ISSUE TITLE
[Feature]视图的过滤器，能否增加取前10条功能，省去再自定义数据集了

### ISSUE THREAD

**Issue by zhanggefei** [dataease/dataease#1125]
**请描述您的需求或者改进建议.**
看图说话
<img width="1190" alt="WechatIMG41" src="https://user-images.githubusercontent.com/37612532/140339240-1e5a949f-b954-4d14-863e-c3a2b198796a.png">

**Comment by yayanpei** [comment]
请问升级到 V1.4.0 版本吗？该版本发布了新功能，可以对指标排序的结果进行控制，如下图：
![image](https://user-images.githubusercontent.com/84168063/140455266-80d59a53-5b6d-49ab-af11-8bc36b832a17.png)
