### ISSUE TITLE
[Feature] API动态参数

### ISSUE THREAD

**Issue by zhaohaihong** [dataease/dataease#11261]
DataEase 版本: v2.8.1

请问如何将仪表盘的查询组件中选择的参数传递到API数据源中，根据查询条件获取不同的报表数据？

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，请问是要将参数传递到api数据源的接口中，获取不同的接口数据吗？

**Comment by zhaohaihong** [comment]
是滴，请问有办法实现没？是这样一个场景，比如我选择一个公司名称，那就需要对应公司的数据，如果我直接全部查出来再进行筛选的话，这样比较耗时。或者后续能不能加一个代办的feature也行，谢谢~

**Comment by yayanpei-fit2cloud** [comment]
实现不了，图表数据的返回是以传sql到数据库的方式，接口是不具备数据库的数据查询处理能力的。
