### ISSUE TITLE
[Feature]图表编辑操作可以双击添加字段

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#11260]
DataEase 版本:
v2

图表编辑操作可以双击添加字段，拖拽不方便

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经在需求池中，待更多用户反馈后，再进行下一步的规划。

**Comment by xuwei-fit2cloud** [comment]
由于有些图表字段栏较多，如堆叠项等，我们并不能确定点击的字段应该添加到哪一栏中，所以不予支持。
2.10.2版本可以支持批量选择多个字段进行拖动操作，可以通过选择多个字段来进行批量操作。
