### ISSUE TITLE
[Feature]仪表板&大屏的权限需要单独有完全的权限，而不是一个个去给数据集权限

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11265]
DataEase 版本: v2.8.1

**请描述您的需求或者改进建议.**
我授权某个角色能使用看板A，看板A使用了数据集1,2,3,4,5

现在的结果：我要授权该角色数据集1,2,3,4,5，才能正常使用看板A

我们希望：能看看板A的，看板A里使用的任何结果集都不受限制，能正常使用

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，暂时没有计划修改，资源的权限和数据的权限是独立的，需要分别授权。
