### ISSUE TITLE
[Bug]Excel新增sheet页后，替换原有Excel数据集，提示错误“Excel的列名与原数据集不一致”。

### ISSUE THREAD

**Issue by zhanggefei** [dataease/dataease#1126]
**DataEase 版本**
1.3.0

**浏览器版本**
chrome95

**Bug 描述**
Excel新增sheet页后，替换原有Excel数据集，提示错误“Excel的列名与原数据集不一致”。

**Bug 重现步骤(有截图更好)**
<img width="864" alt="WechatIMG43" src="https://user-images.githubusercontent.com/37612532/140375008-d4408bca-e58e-493e-ab23-5e5d8cbd3933.png">

**Comment by tjlygdx** [comment]
我们排查一下

**Comment by tjlygdx** [comment]
替换指得是将选中的sheet页中内容替换现有的数据集； 
选中的的sheet页的列名必须一致；
【城市客户管理】、【业务机会漏斗】 这两个的列名应该不一致，所以才会爆出页面的提示；
我们会优化一下页面提示--> "所选sheet页面的列名不一致"

**Comment by zhanggefei** [comment]
不是的。
【城市客户管理】这个列没有变化。【业务机会漏斗】 这是新增的一个页签，原来没有这个页签。
