### ISSUE TITLE
[Feature]查询组件的两条滚动条客户反馈不美观，能否优化一下

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11266]
DataEase 版本: v2.8.1

**请描述您的需求或者改进建议.**
查询组件的两条滚动条客户反馈不美观，能否优化一下
![image](https://github.com/user-attachments/assets/032d9caa-041f-4759-9432-6cf1ce3db35d)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，请问您使用的是什么浏览器？建议使用谷歌浏览器。

**Comment by zhainanshidai** [comment]
用的是google，这个想要增加一些查询条件、查询按钮位置、样式等相关的美化，目前查询组件对美化方面的功能支持较少

**Comment by zhainanshidai** [comment]
这部分有时候会多出两条轴来了，你们可以看看这里出现两条轴的情况，然后看看能否美化一下的

**Comment by zhainanshidai** [comment]
google

**Comment by zhainanshidai** [comment]
105%->100% 会出现2条
95%->100% 显示1条

**Comment by zhainanshidai** [comment]
缩放到75%会消失

**Comment by zhainanshidai** [comment]
苹果macbook pro

**Comment by zhainanshidai** [comment]
> 感谢反馈，请问您使用的是什么浏览器？建议使用谷歌浏览器。

google

**Comment by zhainanshidai** [comment]
> 感谢反馈，请问您使用的是什么浏览器？建议使用谷歌浏览器。

mac 用户反馈有这样的情况，win 我这里没有的

**Comment by yayanpei-fit2cloud** [comment]
经沟通，可能是由于谷歌浏览器版本较低导致的，建议用户升级浏览器版本。
