### ISSUE TITLE
[Bug] 已有新建计算字段的数据集进行关联，字段全选后，刷新数据会报错

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#11263]
**DataEase 版本**
v2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌浏览器

**Bug 描述**
已有的数据集里存在非 calcite 新建计算字段，再进行关联，字段全选会报错；选择部分字段则关联成功。原因是 SQL 有把新建计算字段的逻辑代进去，实际字段是选择不了新建计算字段的，如下图，字段选择是选不到新建计算字段的。
![image](https://github.com/user-attachments/assets/3b9feb2a-5594-41a1-a1cd-9e6ef8e5203c)

![image](https://github.com/user-attachments/assets/5c0262e7-f387-4155-97b1-03c41d1ae12a)

**Bug 重现步骤(有截图更好)**
1.已有的数据集包含非 calcite 新建计算字段，该数据集先保存
![image](https://github.com/user-attachments/assets/eb1cbfb4-42e6-465c-bcd4-7385afce81fd)

2.再编辑该数据集进行关联，默认左边的字段选择是全选，这样刷新数据保存会报错，就是上面bug描述的错误
![image](https://github.com/user-attachments/assets/edcf104a-ef76-46ff-92bd-8631c9178855)

3.放弃此次关联，重新编辑数据集，进行关联，只选择部分字段，能够成功
![image](https://github.com/user-attachments/assets/01db183d-14b5-44c7-a3c1-14c3592146ce)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
