### ISSUE TITLE
[Bug]移动端表格字体太小

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#11268]
**DataEase 版本**
v2.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome、firefox

**Bug 描述**
移动端对于表格显示字体过小，能否放大一点。之前的版本没有这么小。
<img width="645" alt="图片" src="https://github.com/user-attachments/assets/5e27afd7-44e4-4e23-aace-65efe1e248fb">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by cv3x** [comment]
还有查询组件的 @mfanoffice

**Comment by BBchicken-9527** [comment]
感谢反馈，查询组件和图表我们这个新版本都做了适当的优化，可以尝试升级体验；
