### ISSUE TITLE
[Feature]在制作组件或仪表板时，退出界面希望能有一个 未保存内容 的提醒

### ISSUE THREAD

**Issue by xun986** [dataease/dataease#1127]
**请描述您的需求或者改进建议.**
制作过程中有时会忘记保存，退出页面后就得重做一遍，如果可以希望退出界面时能加个“检测到有未保存的内容，是否保存”之类的选项

**Comment by yayanpei** [comment]
感谢反馈，常规操作退出之前，点击右上角关闭，会有未保存提示。非常规操作，如关闭浏览器，我们需要内部讨论一下能否实现。

**Comment by xun986** [comment]
就是在上边栏从仪表板切换到数据集或者视图时有时会忘记，主要能记得点关闭就不会忘记点保存了哈哈

**Comment by xuwei-fit2cloud** [comment]
仪表板编辑状态不再显示上面的菜单栏，应该不存在该问题了
