### ISSUE TITLE
[Bug]关联视图传递参数偶尔生效偶尔不生效

### ISSUE THREAD

**Issue by caiiansheng** [dataease/dataease#1128]
**DataEase 版本**
v1.4

**浏览器版本**
all

**Bug 描述**
仪表盘设置完跳转，关联视图传递参数偶尔生效偶尔不生效，目标视图没有根据跳转参数刷新数据，而是显示全部

**Bug 重现步骤(有截图更好)**
1.仪表盘设置跳转，
![image](https://user-images.githubusercontent.com/26760483/140446573-a60a31d3-7615-47ca-b299-c24efb991849.png)
2.点击元仪表盘跳转
![image](https://user-images.githubusercontent.com/26760483/140446777-720be2e9-7c18-4b02-ba2a-7a5b31b48ad1.png)

3. 查看目标仪表盘，发现一个表格视图根据传递的参数刷新数据，而图表没有刷新（随机的，可能是都刷新了，也可能是表格没有刷新，表格不刷新的概率很大，基本第一次可以，其余都不可以）
第一次
![image](https://user-images.githubusercontent.com/26760483/140447038-dc368a8e-c226-4582-95c4-54b7413d8780.png)
第二次
![image](https://user-images.githubusercontent.com/26760483/140447107-69066875-e112-4152-b8a0-655280a7aded.png)
第三次
![image](https://user-images.githubusercontent.com/26760483/140447352-0e94f464-9d03-4c17-bfcc-446ecdfc7c26.png)
 仪表盘单个视图也是一样

**Comment by xuwei-fit2cloud** [comment]
我们处理一下

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 版本已修复，请等待新版本发布
