### ISSUE TITLE
[Bug]堆叠柱状图钻取层级超过 2 层时失效

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#11296]
**DataEase 版本**
v2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新

**Bug 描述**
堆叠柱状图添加钻取维度超过 2 个时，从第三级开始无法下钻。

**Bug 重现步骤(有截图更好)**

![屏幕截图 2024-07-31 181806](https://github.com/user-attachments/assets/08d90fc2-38e2-40a8-a754-e4fb5d06cabe)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题已修复，请下载新版本体验；
