### ISSUE TITLE
[Feature] 行权限规则-系统变量中 无法像筛选框一样选择参数变量1

### ISSUE THREAD

**Issue by niusunshine** [dataease/dataease#11290]
DataEase 版本: v2.8.1
![image](https://github.com/user-attachments/assets/44f2bec4-d9c6-43b4-9c96-54d841efeae9)

**请描述您的需求或者改进建议.**
比如我有一个数据集。里面是按天统计的一些指标。 里面按不同的业务模块通过筛选来展示数据。
我将需要筛选的字段配置为 参数。 在过滤条数时按 参数来传递。

我要实现不同的人能看不同的业务模块数据。  那我在数据配置行权限的时候。 
通过给每个人配置不同的 系统变量 来实现。  需要再行权限规则中 能  参数变量 与 系统变量 来配置.

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议按照如下流程操作。
第一步，在系统变量中增加业务模块变量；
![image](https://github.com/user-attachments/assets/3d3a1f86-1794-418a-87a1-d47d61eefe17)

第二步，在用户管理页面，给每个用户绑定业务模块变量值；
第三步，在行列权限中，将数据集中的字段：业务模块，与变量绑定，从而实现不同的人查看不同业务模块的数据。
![image](https://github.com/user-attachments/assets/413a43cd-d2a0-49f3-8ac0-3ee0bced2186)

**Comment by niusunshine** [comment]
![image](https://github.com/user-attachments/assets/930df172-6540-49f3-961c-c4ded712eea0)
你好， 是这里  无法像筛选框一样选择参数变量。

**Comment by yayanpei-fit2cloud** [comment]
这里筛选的是数据集的字段，参数变量指什么？数据集中sql片段的参数吗？

**Comment by niusunshine** [comment]
是的，是参数变量。 类似于筛选框里面的 参数 一样。

**Comment by yayanpei-fit2cloud** [comment]
如果仪表板中的查询组件绑定了参数，在数据集的行权限中直接将数据集的字段和系统变量绑定即可，在仪表板中更换查询组件的选项值后，图表的数据：参数和行权限同时生效后的数据。

**Comment by niusunshine** [comment]
现在的问题是，  在行权限这里  选不到 数据集里面的 参数字段作为 字段名。   字段名=系统变量。   这个字段名不能选择 参数。

**Comment by yayanpei-fit2cloud** [comment]
数据集中的参数只能在where条件中，用于过滤数据集数据，因此参数是不在数据集的字段列表中。

**Comment by niusunshine** [comment]
不对喔， 行权限怎么控制我说的场景了？   比如我按部门统计有 每天使用的 cpu数  和 容器数， 
我的数据集为3个字段。  dt,  cpu,  container.    参数为,  business_1,  bussiness_2,  bussiness_3,  机房，业务部门，等等. 
我需要按不同的  business_1,  bussiness_2 来控制这个数据集的权限。  那这个时候需要怎么控制？
另外我的数据集怎么设计。 是按这个参数列表group by 再去做二次计算会面临值不准的问题.

**Comment by niusunshine** [comment]
111

**Comment by niusunshine** [comment]
@yayanpei-fit2cloud
