### ISSUE TITLE
[Feature]社区版本 DataEase 容器日志中出现 xpack 相关日志

### ISSUE THREAD

**Issue by wanghe-fit2cloud** [dataease/dataease#11317]
## DataEase 版本：

**v2.9.0**

## 请描述您的需求或者改进建议

在 [1Panel](https://github.com/1Panel-dev/1Panel)  应用商店部署的社区版本 DataEase 中，发现容器日志中包含了 xpack 相关的日志信息。

希望能够对此进行检查和修复，以避免不必要的日志信息泄露。

![image](https://github.com/user-attachments/assets/b8eab68f-3aa2-4ade-a3c9-1f2596c3b7af)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们优化一下。
