### ISSUE TITLE
[Bug] 堆叠柱状图排序结果不正确

### ISSUE THREAD

**Issue by yuqun-nj** [dataease/dataease#11316]
**DataEase 版本**
v2.8.0 和 v1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
126.0.6478.183

**Bug 描述**
<img width="824" alt="image" src="https://github.com/user-attachments/assets/beeb576a-03d1-4531-a125-85fc97985351">
<img width="1393" alt="image" src="https://github.com/user-attachments/assets/99ea828b-328a-4dc0-92b0-42e43345ebd3">
<img width="1150" alt="image" src="https://github.com/user-attachments/assets/d1fd0f8a-c77a-4498-a0ee-c854c2f34b82">

**Bug 重现步骤(有截图更好)**
1、选择堆叠状态的指标求和项进行倒序排序，排序后的结果并非按倒序显示

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
