### ISSUE TITLE
[Feature]容器日志中包含大量 SQL 语句，默认 INFO 级别导致日志过多

### ISSUE THREAD

**Issue by wanghe-fit2cloud** [dataease/dataease#11315]
## DataEase 版本:

**v2.9.0**

## 请描述您的需求或者改进建议

在 [1Panel](https://github.com/1Panel-dev/1Panel) 应用商店中部署了 DataEase，并在使用过程中发现容器日志中包含了大量的 SQL 语句。
> 目前日志级别为默认的 INFO，请问是否可以调整为 DEBUG？

![image](https://github.com/user-attachments/assets/faf3692c-90ec-419a-89e2-345816285b1a)

**Comment by xuwei-fit2cloud** [comment]
已排期
