### ISSUE TITLE
[Feature]仪表盘分享连接添加嵌入到网页的代码

### ISSUE THREAD

**Issue by baoshan2020** [dataease/dataease#1132]
仪表盘分享连接的时候,添加嵌入到网页的代码(如下) 自动生成宽高和src地址
<iframe id="Example2"
    title="Example2"
    width="400"
    height="300"
    frameborder="0"
    scrolling="no"
    marginheight="0"
    marginwidth="0"
    src="https://dataease.io">
</iframe>

![f61499047e1e7d7ffe4d1d5f3e5745f](https://user-images.githubusercontent.com/61979600/140510677-bc39e317-019e-43c6-a97e-a2224ac45ca6.png)

**Comment by yayanpei** [comment]
感谢您的反馈，我们内部讨论一下。

**Comment by xuwei-fit2cloud** [comment]
近期版本暂时不予支持。
