### ISSUE TITLE
[Feature]希望数据集里面的参数设置，日期可以支持动态时间。目前只有查询组件支持动态时间，不太方便。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#11328]
DataEase 版本:
V2.8.1

**请描述您的需求或者改进建议.**
希望数据集里面的参数设置，日期可以支持动态时间。目前只有查询组件支持动态时间，不太方便。
<img width="1237" alt="74a52370f7cbecf315706516e142022" src="https://github.com/user-attachments/assets/4a22061d-5d7f-46ea-93f4-e7c3ef75ed38">

希望做成的样子：
<img width="552" alt="44df6bab0ee2aa2d70e3cd35f5b6555" src="https://github.com/user-attachments/assets/66fbd4d5-2c3e-4508-b424-b0e3fbb4a4b5">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，此处的参数值，仅在数据集编辑时预览生效，建议直接选择对应日期，目前暂时没有计划支持。
