### ISSUE TITLE
[Feature]希望列表类型的视图可以支持弹框信息的设置。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#11329]
DataEase 版本:
V2.8.1

**请描述您的需求或者改进建议.**
希望列表类型的视图可以支持弹框信息的设置。
<img width="293" alt="b50d236d556209b7081942d57d2b265" src="https://github.com/user-attachments/assets/ed1f84d5-7b15-4e44-9a26-bc3fa063edbc">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，需求已记录，如有更多用户反馈，我们会做相关排期，短期内还不会支持。
