### ISSUE TITLE
[Feature]维度/指标很多，现有的能拖拉拽过去，但是几十个字段要拖很久，能不能增加一个全选

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11334]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
维度/指标很多，现有的能拖拉拽过去，但是几十个字段要拖很久，能不能增加一个全选，然后再拖拉拽。

**Comment by zhainanshidai** [comment]
比如在明细表的制作的时候，有时需要用到很多个字段

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，建议按住shift键，选择多个字段一起拖拽，如下图所示：
![image](https://github.com/user-attachments/assets/1adff01f-be3c-46a0-8dc9-e74db8ec61e8)
