### ISSUE TITLE
[Bug] Excel 和 MySQL 数据集进行关联，日期字段在仪表板中数值错误

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#11339]
**DataEase 版本**
v2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌

**Bug 描述**
关联 Excel 数据集和 MySQL 数据集，关联后数据集处显示正常，但在仪表板中拖入数据库日期字段则会数值错误始终为 1970-01-01

**Bug 重现步骤(有截图更好)**
1.查看 Excel 数据集
<img width="625" alt="excel" src="https://github.com/user-attachments/assets/3d0c87d6-6275-4558-bb0b-4a0d4e700df7">
查看 MySQL 数据集
<img width="580" alt="MySQL数据集" src="https://github.com/user-attachments/assets/47ed164b-4f63-45fc-935b-4bb79ca2dc76">

2.使用关联数据集
<img width="715" alt="关联中" src="https://github.com/user-attachments/assets/57c88324-fa9e-45af-b6fd-ae77a4050755">
关联后数据正常
<img width="610" alt="关联" src="https://github.com/user-attachments/assets/513b429f-2dc5-488c-a32f-03ab2c7ecc59">

3.在仪表板中使用
<img width="645" alt="仪表板" src="https://github.com/user-attachments/assets/3922f21d-c970-4ea4-a812-f82948832c74">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行修复；

**Comment by maninhill** [comment]
俊杰辛苦了。
