### ISSUE TITLE
[Bug] 无法读取PostgresSql Timestamp格式

### ISSUE THREAD

**Issue by ouchuji** [dataease/dataease#11333]
**DataEase 版本**
2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
127

**Bug 描述**
无法读取PostgresSql Timestamp格式，可以看下图片

**Bug 重现步骤(有截图更好)**
1.
列的类型为 timestamp with timezone 
![image](https://github.com/user-attachments/assets/e28ac7ba-b573-4c63-86e3-b5edd6a221ff)
2.
第一个问题，字段类型无法自动识别为时间，而是被识别为了 文本
![image](https://github.com/user-attachments/assets/0a6923eb-6278-4724-addd-c67daa25c9de)
3.
第二个问题，修改格式
![image](https://github.com/user-attachments/assets/340d24d0-f864-445e-b60f-4b430015b30e)
保存直接报错
![image](https://github.com/user-attachments/assets/c4d7af50-88b0-4678-b25a-db17cb878721)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
