### ISSUE TITLE
自由构图功能[Feature]

### ISSUE THREAD

**Issue by niusunshine** [dataease/dataease#11337]
DataEase 版本: v2.9

**请描述您的需求或者改进建议.**
针对报表查看同学， 可以支持自由构图功能。可以由查看权限的同学， 自由拖动 指标和维度， 选择图形。构建数据.
![image](https://github.com/user-attachments/assets/6360cbaf-7fa6-4d58-846c-a531d63c7f9f)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，图表的制作方式目前暂时没有计划调整，即先选择图表类型，然后拖拽字段，生成图表；如果需要，可以更换图表类型。
