### ISSUE TITLE
[Feature]修改了结果集A里面的sql，可能是增加或删除了一列，或者修改了sql条件，进行保存的时候，结果集里的维度、指标就完全变更了 这样就出现刚才看板里面看引用的结果集的维度、指标的时候，就全红了【删除重新添加，还得重新设置颜色等事情，不单单把维度、指标重新拉进来】 看看这个怎么优化，尽量减少这种不需要变更的维度、指标

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11335]
DataEase 版本:
v2.8.1

**请描述您的需求或者改进建议.**
修改了结果集A里面的sql，可能是增加或删除了一列，或者修改了sql条件，进行保存的时候，结果集里的维度、指标就完全变更了
这样就出现刚才看板里面看引用的结果集的维度、指标的时候，就全红了【想不暴红要删除重新添加，还得重新设置颜色等事情，不单单把维度、指标重新拉进来】
看看这个怎么优化，尽量减少这种不需要变更的维度、指标

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，如果图表使用了该数据集后，数据集的sql片段中又新增了字段a，那么图表的维度或者指标处是不会变红的。如果图表使用了数据集的字段a，然后再将数据集的sql片段中a字段删除，由于字段被删除后找不到了，因此图表中的该字段会变红。
