### ISSUE TITLE
[Feature]透视表小计可以根据维度灵活配置

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#11336]
DataEase 版本:
2.8.1

**请描述您的需求或者改进建议.**
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/70f09497-1d58-447f-be4d-e1c1de815a74">
<img width="529" alt="image" src="https://github.com/user-attachments/assets/3a71bf4d-3884-4306-8208-3d59b11e59e7">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先加入需求池中，在近期的版本中支持一下。

**Comment by xuwei-fit2cloud** [comment]
请升级版本。
