### ISSUE TITLE
[Feature]sql编辑后，中文<字段名>名会恢复成<原始名>。

### ISSUE THREAD

**Issue by baoshan2020** [dataease/dataease#1133]
问题：sql编辑后，中文<字段名>名会恢复成<原始名>。
需求：提供一个字段数据库一键匹配字段名的功能。（字段名称可以提前录入到一个表里自动匹配 或者在“字段管理”一键导入到dataease数据库里存储）
![3e1cf68182d4b06094c87d0be080423](https://user-images.githubusercontent.com/61979600/140518094-fb03b5ec-b8f6-46ce-8d2b-d9b78ad23815.png)
*

**Comment by yayanpei** [comment]
感谢您的反馈，SQL 数据集重新编辑后，后台重建了数据集，因此之前数据集的信息会丢失，我们也在讨论优化方案。

**Comment by xuwei-fit2cloud** [comment]
v1.5.0版本已处理该问题。
