### ISSUE TITLE
[Feature]明细表的表格是否可以支持单元格内自动换行？

### ISSUE THREAD

**Issue by LinkedBear** [dataease/dataease#11348]
DataEase 版本: V2.9.0

Dataease的功能非常强大，我使用它获得了非常棒的体验。目前有一个问题正在困扰我，当我使用仪表盘的明细表组件展示数据时，发现当一个单元格内的数据过长时，单元格内无法全部显示（过长被隐藏），请问贵团队对此是否有优化计划？

以下是一个展示该问题的示例截图：

![数据过长被隐藏示例](https://github.com/user-attachments/assets/3a390ed9-94eb-4085-a300-208b678aa542)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的支持和反馈，目前图库尚未支持，我们先加入需求池中。建议先将列宽调整为自适应模式。

**Comment by LinkedBear** [comment]
我查阅了AntV-S2的官方文档和咱们的源码版本，发现S2的2.x版本已经支持了多行文本，咱们目前使用的是S2-1.49，请问贵团队有升级S2版本的计划吗😀

**Comment by yayanpei-fit2cloud** [comment]
已在 v2.10.3 版本支持上，请升级版本。
