### ISSUE TITLE
[Bug]自定义主题颜色没有同步

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#11340]
**DataEase 版本**
V 2.8.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
自定义主题颜色没有同步

**Bug 重现步骤(有截图更好)**
<img width="1433" alt="image" src="https://github.com/user-attachments/assets/8b99ecb4-ed8a-4387-89f4-ba115958b202">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
