### ISSUE TITLE
[Bug]v2 折线图开启缩略轴后切换组合图，组合图也会有缩略轴

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#11342]
![image](https://github.com/user-attachments/assets/c5023bf3-33aa-48bb-92a3-d5251a602610)

**Comment by wolf-kingx** [comment]
不止切换组合图会有这样的现象，其他的能滑动图基本都会出现这样的情况

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
