### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by LinkedBear** [dataease/dataease#11349]
**DataEase 版本**

V2.9.0

**运行方式(安装包运行 or 源码运行 ?)**

安装包运行

**浏览器版本**

Chrome 127

**Bug 描述**

当我使用仪表盘的折线图类组件展示数据时，发现最高点的数据展示不完整（貌似是 div 溢出被隐藏了？），开启最值显示后该问题依然存在。

**Bug 重现步骤(有截图更好)**

未开启最值显示时的显示问题（不完整）

![折线图最高点数据显示不完整示例](https://github.com/user-attachments/assets/3bbef30b-bb66-422a-941c-cc87a7e47445)

开启最值显示后的显示问题（仍然不完整）

![开启最值显示后折线图最高点数据显示仍然不完整示例](https://github.com/user-attachments/assets/f9cf18f8-78a7-4993-adea-307907f98d85)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，但目前没有较好的方式实现此处的计算，建议可以开启自定义轴值去取进行调整；

**Comment by LinkedBear** [comment]
我觉得咱是不是可以加入一个图表外边距的配置，现有的内边距相当于缩小了整个图表的展示空间（应该是外层做了display: none吧），引入外边距并不设置溢出隐藏是否可以处理该问题？

可能文字表达不是很直观，我简单绘制了一个草图如下，右侧是引入外边距概念后的效果，折线的最大展示范围同时受现有的内边距和新引入的外边距控制，而标签数值的展示仅受内边距控制，这样就可以将标签数值展示出来。不知这样从设计和现有技术层面是否可以实现~

![image](https://github.com/user-attachments/assets/31ffb13a-7b03-4217-9e2a-a4ffe16fd851)
