### ISSUE TITLE
[Bug] 不同数据集使用级联时报错无法正常使用

### ISSUE THREAD

**Issue by SnakeWhale** [dataease/dataease#11344]
**DataEase 版本**
社区版2.8

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chorme 127.0.6533.88（正式版本） （64 位）

**Bug 描述**
![image](https://github.com/user-attachments/assets/225bf0e4-684c-46e9-abae-be27844c7411)
![image](https://github.com/user-attachments/assets/d9f85dee-0450-4cdb-b963-7e5ea3036c17)
不同数据集使用级联时报错无法正常使用

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈,请问你说的不同数据集使用级联是级联关系是不同的数据对吗？像图片中这样；
![image](https://github.com/user-attachments/assets/d208cb97-b5fe-45c4-8119-e712b78b942d)
![image](https://github.com/user-attachments/assets/9b9a19a5-ec09-4232-b344-e01d00ee4d5d)

**Comment by SnakeWhale** [comment]
1处的数据集和2处的数据集不是同一个，级联配置无法打开配置
![image](https://github.com/user-attachments/assets/4cf9e35d-f5cf-445c-b255-1709d6d6ee8e)

**Comment by BBchicken-9527** [comment]
现在最新版你试了吗？我这边测试环境是没问题的可以正常打开的；
![image](https://github.com/user-attachments/assets/ea45173e-0d09-45c2-bbe3-6ad278345ace)
![image](https://github.com/user-attachments/assets/7ad8f89c-35c4-4384-bde3-f40546f2877f)

**Comment by SnakeWhale** [comment]
您好请问您这里的最新版本是多少，我这里更新试试

**Comment by SnakeWhale** [comment]
升级2.9版本正常使用，感谢
