### ISSUE TITLE
[Feature]希望可以在配置api数据源的时候使用url里面的外部参数

### ISSUE THREAD

**Issue by zxbly-pro** [dataease/dataease#11357]
DataEase 版本:
2.9.0

**请描述您的需求或者改进建议.**
目前遇见一个场景是需要在通过api数据源请求数据的时候携带一些参数,比如时间或者项目id,这些参数是通过url访问大屏的时候传递的,目前外部参数应该是在数据请求完之后进行过滤,希望添加一个外部参数可以作为api请求参数使用,比如http://url?attachParams=eyJjcmVhdGVfc3RhZmZfaWQiOiIxMDEifQ==,希望可以把attachParams传递到后台接口去

**Comment by xuwei-fit2cloud** [comment]
数据集的数据是需要入库才能提供查询与分析功能。通过仪表板或者数据大屏的点击，向数据源传递参数，此时基于该数据源创建的数据集并不会更新数据，而且此处还可能存在权限问题。很抱歉目前还没有支持计划。
