### ISSUE TITLE
建议AI生成的图表能直接和仪表板进行集成

### ISSUE THREAD

**Issue by mrlisir** [dataease/dataease#11356]
DataEase 版本: V2.9

**请描述您的需求或者改进建议.**
AI 功能 生成的图形，建议能和仪表板进行集成

**Comment by xuwei-fit2cloud** [comment]
感谢反馈。
现在Copilot生成的图表相对来说还比较简单，等功能再强大一些，我们会考虑和仪表板、数据大屏进行集成。

**Comment by LiXunGuan** [comment]
隔壁家，已经有 FineChatBI  可以参考借鉴下  https://www.fanruan.com/finechatbi
