### ISSUE TITLE
[Bug]配置K线图的日期/维度，日期显示选择了年月日时分秒只能显示年月日，不显示时分秒

### ISSUE THREAD

**Issue by zjdc** [dataease/dataease#11354]
DataEase 版本：V2.8.1，V2.9.0

运行方式：安装包运行

浏览器版本：
edge 127.0.2651.86 (正式版本) (64 位)
chrome 127.0.6533.89（正式版本） （64 位）

Bug 描述：
仪表板选择K线图图表，配置日期/维度的日期显示为年月日时分秒，只能显示年月日，不显示时分秒。数据集里面的数据是有时分秒的。

Bug 重现步骤(有截图更好)**
1. 添加数据源和数据集，截图为数据集中相关字段的时间格式，包含了年月日时分秒
![图片](https://github.com/user-attachments/assets/e7d36adc-0100-456d-aef3-d9f6efa68c5f)

2. 仪表板选择K线图，配置日期/维度的日期显示为年月日时分秒。
![图片](https://github.com/user-attachments/assets/b0f1328c-2dec-4f91-b38b-4067b6e8d96f)

3. 鼠标放到K线图，日期只能显示年月日。
![图片](https://github.com/user-attachments/assets/b8002d1c-38ed-4e2d-be40-faebbdf7eb78)

**Comment by 35plus** [comment]
东区有个客户，需要甘特图，目前的区间条形图，展示的是 开始和结束时间，客户 还想要任务进度也展示出来。下面这个是客户数据。如果有任务进度展示，就完美了。

[日期 甘特图.xlsx](https://github.com/user-attachments/files/16490102/default.xlsx)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前平台支持的是日k线图表，而你说的场景和k线图真正的使用场景是不相通的，暂时不会去因为这个场景去修改k线图；

> 东区有个客户，需要甘特图，目前的区间条形图，展示的是 开始和结束时间，客户 还想要任务进度也展示出来。下面这个是客户数据。如果有任务进度展示，就完美了。
> 
> [日期 甘特图.xlsx](https://github.com/user-attachments/files/16490102/default.xlsx)

**Comment by zjdc** [comment]
怎么就关闭问题了呢？他提问的这个任务进度的问题和K线图不相关，我的问题是，数据集里面的数据是有的，为什么仪表板里面就不显示呢？

**Comment by BBchicken-9527** [comment]
不好意思，我以为你们是帮同一个用户提交的问题，后续两个版本内我们会对你提的问题进行优化；
