### ISSUE TITLE
行权限规则-系统变量中 无法像筛选框一样选择参数变量--需求无法实现，第一次被关闭[Feature]

### ISSUE THREAD

**Issue by niusunshine** [dataease/dataease#11353]
DataEase 版本:
![image](https://github.com/user-attachments/assets/c8e73a96-251c-4307-acaf-5e2db7d7729f)

行权限怎么控制我说的场景了？ 比如我按部门统计有 每天使用的 cpu数 和 容器数，
我的数据集为3个字段。 dt, cpu, container. 参数为, business_1, bussiness_2, bussiness_3, 机房，业务部门，等等.
我需要按不同的 business_1, bussiness_2 来控制这个数据集的权限。 那这个时候需要怎么控制？
另外我的数据集怎么设计。 是按这个参数列表group by 再去做二次计算会面临值不准的问题.

如果不支持变量， 那这类需求不能做。  第一次提被关闭。 请告诉我这类需求怎么实现了.

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，business_1, bussiness_2，参数指的是什么？和数据集中的哪个字段关联呢？或者可以加我微信：18317092178 ，进行沟通交流。

**Comment by niusunshine** [comment]
你好，business_1, bussiness_2 表示 ，  一级业务模块， 二级业务模块，   和数据的关系为. 

数据集:
dt, cpu, containe  为这三个字段。  
 business_1, bussiness_2, bussiness_3, 机房，业务部门 为数据集的 参数.

**Comment by yayanpei-fit2cloud** [comment]
行列权限是在数据集层面做数据的筛选，建议将「业务模块」添加至数据集的字段中。

**Comment by niusunshine** [comment]
不能添加进去的。 相当于我的报表要二次计算。   数据集里面如果要添加进去要把 这些字段加到  group by里面。   二次计算会影响结果。

**Comment by niusunshine** [comment]
你们可以想一下这个场景， 特别常见.

**Comment by yayanpei-fit2cloud** [comment]
明白了，我们内部先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
方便的话，可以加我微信：18317092178，一起沟通下。
