### ISSUE TITLE
[Bug] starrocks数据源聚合查询 v2.9.0 比v1.18.19 查询慢很多

### ISSUE THREAD

**Issue by marvel-007** [dataease/dataease#11358]
**DataEase 版本**
v2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
官方镜像部署测试

**浏览器版本**

**Bug 描述**
都是starrocks数据单表查询  根据时间字段指定范围查询：select etl_ts_hour,count() 性能差别很大

**Bug 重现步骤(有截图更好)**
<img width="1179" alt="image" src="https://github.com/user-attachments/assets/84d893ad-cd43-46c2-8611-fb43e7338da3">
这是v1.18.19 版本聚合查询的效果，非常高效，而且是两个字段的聚合查询。
<img width="1145" alt="image" src="https://github.com/user-attachments/assets/d17a4f98-ff70-4314-939f-0938d8a4603f">
这是v2.9.0聚合查询，只有一个字段的聚合统计

初步分析：
2.9.0 查询了很多明细字段，而且时间字段还用的函数转换，导致查询能行较低

**Comment by BBchicken-9527** [comment]
感谢反馈，目前v2是需要通过calcite去进行和数据源进行交互，而calcite再出处理sql的同时会对sql进行一定的优化，此处我们是无法进行限制的，所以暂时没有合适的方法可以对这里进行相应的优化；

**Comment by marvel-007** [comment]
> 感谢反馈，目前v2是需要通过calcite去进行和数据源进行交互，而calcite再出处理sql的同时会对sql进行一定的优化，此处我们是无法进行限制的，所以暂时没有合适的方法可以对这里进行相应的优化；

感谢回复，不过v2为了能够使用starrocks进行快速分析查询，得看看能否优化calcite，如果不行能否对starrocks的查询数据源提供一个可选择的交互组件 进行灵活切换，提供v1.18.19版本中实现的交互选择，实现不同的数据源的最优选择，最大化提高查询效率
