### ISSUE TITLE
[Question] 部署clickhouse时遇到报错

### ISSUE THREAD

**Issue by ruanruanr** [dataease/dataease#11351]
使用dataease部署20.8.3.18版本clickhouse遇到报错
Code: 47, e.displayText() = DB::Exception: Missing columns: 'comment' while processing query: 'SELECT name, comment FROM system.tables WHERE database = 'ladg_db'', required columns: 'name' 'comment' 'database', source columns: 'total_bytes' 'sampling_key' 'primary_key' 'create_table_query' 'dependencies_table' 'storage_policy' 'is_temporary' 'dependencies_database' 'data_paths' 'name' 'metadata_modification_time' 'engine' 'uuid' 'lifetime_bytes' 'partition_key' 'engine_full' 'metadata_path' 'lifetime_rows' 'total_rows' 'sorting_key' 'database' (version 20.8.3.18) , server ClickHouseNode [uri=http://192.168.2.7:8123/ladg_db]@-1183682800

**Comment by xuwei-fit2cloud** [comment]
请问DataEase的具体版本是多少？什么运行方式？
另外，能否提供一下对应的SQL以及表结构截图？

**Comment by ruanruanr** [comment]
版本：-v2.8.1-ce web端部署
![clickhouse](https://github.com/user-attachments/assets/37c9ccf9-949b-4656-9c84-d332ac316c3e)
ladg_db中只有一张表，表结构
![image](https://github.com/user-attachments/assets/73561162-0aa5-459d-8936-5cfa86668a27)

**Comment by xuwei-fit2cloud** [comment]
谢谢，我们看看。

**Comment by xuwei-fit2cloud** [comment]
之前版本的CK的 system.tables 表里名没有comment 字段，我们后续版本调整一下。

**Comment by ruanruanr** [comment]
好的辛苦，麻烦后续在这条下面通知我，辛苦~

**Comment by xuwei-fit2cloud** [comment]
已修复，等待下个版本发布。
[4b13d91741e7b0f7fc81a859c477723dd4ca9c8b](https://github.com/dataease/dataease/commit/4b13d91741e7b0f7fc81a859c477723dd4ca9c8b)
