### ISSUE TITLE
[Feature]地图在数据极差过大时只按照图例数进行区间划分，大部分数据都在同一个区间内，期望自定义区间

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#11350]
DataEase 版本:
V2.9.0

**请描述您的需求或者改进建议.**
数据极差过大时只按照图例数进行区间划分，大部分数据都在同一个区间内，后续是否可以支持自定义的区间
<img width="550" alt="image" src="https://github.com/user-attachments/assets/aae7c0ca-18cf-457e-92ab-095b70b2f769">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录进需求池中，当有更多用户反馈后，再做下一步的规划。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
