### ISSUE TITLE
[Feature]表格数据多选后支持复制多值

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#11368]
**DataEase 版本**
v2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome 127.0.6533.89

**Bug 描述**
明细表经过筛选后，需要将筛选结果复制出来，表格数据多选后点击右键，只复制到一个值
![image](https://github.com/user-attachments/assets/a7082eab-4894-4c43-8cc1-fab2848a895a)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，DataEase当前版本支持的表格数据复制，仅支持鼠标当前所在单元格的复制，并不支持多数据复制。
我们可以在后续版本支持一下多数据复制。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
