### ISSUE TITLE
[Bug]堆叠柱状图显示记录数非聚合结果后的记录数

### ISSUE THREAD

**Issue by YinQh520** [dataease/dataease#11372]
**DataEase 版本**
2.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
使用堆叠柱状图时，需要显示记录数，非聚合结果后的记录数

**Bug 重现步骤(有截图更好)**

![Uploading 0022.png…]()

**Comment by YinQh520** [comment]
<img width="741" alt="0022" src="https://github.com/user-attachments/assets/aab8400a-8dd1-483e-8301-6d71f617274c">

**Comment by BBchicken-9527** [comment]
感谢反馈，结果展示这边的数值是图表运算的数据量，如你输入了10则图表只会用拿到的前10条数据去进行运算和制图，若获取到的前十条存在相同的维度是会这样的，您可以看一下图表明细，是否显示了十条数据，若只获取到了10条则这个功能就是正确的。可以使用图表过滤器或者其他图表去达到你理想的输出；
