### ISSUE TITLE
[Bug]通过设置外部参数和Ticket 设置 过滤查询结果 pc端视图可以生效 手机端视图不生效

### ISSUE THREAD

**Issue by zhangfachao** [dataease/dataease#11373]
**DataEase 版本**

v2.8.0社区版

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**

**Bug 描述**
通过设置外部参数和Ticket 设置 过滤查询结果 pc端视图可以生效 手机端视图不生效

**Bug 重现步骤(有截图更好)**
1.
![Uploading 微信图片_20240806123334.png…]()

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是手机端使用ticket外部参数不生效是这个意思吗？

**Comment by zhangfachao** [comment]
是的 手机端没生效 加的过滤ticket 没起效果 还是所有数据都能看到 pc端生效了

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行优化；
