### ISSUE TITLE
[Bug] 当前版本发现log4j2安全漏洞

### ISSUE THREAD

**Issue by spritelyl** [dataease/dataease#11376]
**DataEase 版本**
v1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
127.0.6533.73

**Bug 描述**
用阿里云安全中心扫描出如下漏洞：
![3eaa06bb5e8fa2e7e43cf85c9b55dad](https://github.com/user-attachments/assets/060957cc-fa23-4bf2-8ac0-bea489f97b4c)

![199233f19306405402efa08c56e1c01](https://github.com/user-attachments/assets/424c2540-f07d-4137-bf62-13dffcc5ced0)

**Bug 重现步骤(有截图更好)**
1. 阿里云安全中心扫描

**Comment by maninhill** [comment]
请先升级到 v1.18.23，如果还有问题请再 re-open。

**Comment by spritelyl** [comment]
![be9874c4b91b58ae863701827f662c1](https://github.com/user-attachments/assets/25297183-7f26-4634-bca6-56b2244f7096)
sheng升级之后还是存在这个漏洞
