### ISSUE TITLE
[Feature]时间过滤组件动态时间支持本周、上周、昨天、当月等

### ISSUE THREAD

**Issue by yxp1** [dataease/dataease#11379]
DataEase 版本:
2.9.0

**请描述您的需求或者改进建议.**
时间范围和时间组件中的动态时间，都只能设置前、后的年月日，但是动态时间更多想展示的是动态的本周、上周、当月、上月这种，目前的前后设置无法满足
![image](https://github.com/user-attachments/assets/f3e1b322-f765-4547-a890-8aa3ff93f383)
![image](https://github.com/user-attachments/assets/53bddd75-b18d-42fc-8135-2045f96458e1)

**Comment by yxp1** [comment]
![image](https://github.com/user-attachments/assets/c98a1418-2a81-47b2-80a6-93bdfd8a1a67)
原来你们v1版本是支持的，那希望v2可以加上，目前的前后真的无法满足

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，年、年月、年月日的快捷选项预计在v2.10.lts版本会支持上。按周、按季度的目前组件不支持，还需要一些时间。
