### ISSUE TITLE
[Feature]增加页面级刷新，整个浏览器刷新

### ISSUE THREAD

**Issue by yxp1** [dataease/dataease#11378]
DataEase 版本:
v2.9.0

**请描述您的需求或者改进建议.**
我们都挂到大屏幕上去了，设置数据刷新后不会再去动。但是数据刷新对过滤组件不生效，过滤组件设置前7天，但是到了第二天，还是之前的前一天，过滤组件没有刷新。
另外平时也会修改一些样式，如果不手动去大屏刷新，样式也不会更新。

**Comment by yxp1** [comment]
浏览器刷新v1也是支持的啊 ，v2加上呗
![image](https://github.com/user-attachments/assets/6ca54695-8a7a-47a9-957a-593b4bdc90d1)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中进行支持。
