### ISSUE TITLE
[Question]v1.5.0 版本规划和时间

### ISSUE THREAD

**Issue by xuwei-fit2cloud** [dataease/dataease#1138]
**请描述您的问题.**
v1.5.0 版本规划和时间

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 计划12月2日发布，该版本的计划内容有：

**数据集**

- 数据集变化对视图选项的兼容性处理


**视图**

- 优化前端数据量大的情况下，所有视图组件的渲染问题
- 增加词云图支持
- 视图分类优化

**仪表板**:

* 支持嵌入式视频播放

**数据源**:

* 支持 Hive 数据源

**Comment by lnts2015** [comment]
API 数据源呢？

**Comment by maninhill** [comment]
1.5 版本已经发布，具体请参考：https://github.com/dataease/dataease/releases/tag/v1.5.0
