### ISSUE TITLE
[Feature]冻结大屏上方区域功能

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#11381]
DataEase 版本:
v2

鼠标上下滑动的时候，红框中的组件一直都显示在上面，类似excel的冻结前2行数据的功能
<img width="763" alt="图片" src="https://github.com/user-attachments/assets/bdb48642-08c4-4c9c-b816-12d43eaf4b17">

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持。
