### ISSUE TITLE
[Bug]Copilot问答页面中指标数据的数据类型标识错误

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#11384]
**DataEase 版本**
2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
数据集中的指标数据（文本转换后）的数值类型，但是数值类型在页面中展示为文本标识。

**Bug 重现步骤(有截图更好)**
截图如下：
![image](https://github.com/user-attachments/assets/281097da-d7bf-4f5b-b05e-c8a8af79e617)

**Comment by BBchicken-9527** [comment]
感谢反馈，在copilot中显示字段类型为数据数据库存储的类型，是通过大模型直接生成图表的；
