### ISSUE TITLE
[Bug]【仪表板】年月筛选组件数据筛选异常

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#11405]
**DataEase 版本**
v1.18.23

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
年月筛选组件数据筛选异常，详见步骤

**Bug 重现步骤(有截图更好)**
1.创建以下表，录入以下数据。
![image](https://github.com/user-attachments/assets/5279e51e-dc03-4e9e-9410-da2a33528c1b)
![image](https://github.com/user-attachments/assets/06b7ffb2-b891-44ed-97d3-73b39ad1160f)

2.用 DataEase 接入之后，添加以下计算字段。
concat(left([time],4),"-",right([time],2),"-01")
![image](https://github.com/user-attachments/assets/d7ae5836-de41-4744-9f30-67a5f40d917a)
![image](https://github.com/user-attachments/assets/b87591c8-26fe-47f6-be53-b148b2c7f90e)

3.在仪表板用年月组件进行查询，查询不出来数据。
![image](https://github.com/user-attachments/assets/222fcc60-3211-473d-9b84-d202ffcba5d9)

4.猜测可能是进行数据查询的时候时间转换这里有问题。
![image](https://github.com/user-attachments/assets/22646e00-e84a-4e4d-b6e9-5001c5ef6d87)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，请问是必现的嘛？
![Uploading image.png…]()

**Comment by BBchicken-9527** [comment]
感谢反馈，字段表达式要和字段类型一致的；
