### ISSUE TITLE
[Feature] V1 过滤组件是否可以不绑定字段

### ISSUE THREAD

**Issue by cadcamzy** [dataease/dataease#11400]
DataEase 版本: 1.8.23

**请描述您的需求或者改进建议.**
在V1 版本中，想对数据集传参，只能通过过滤组件，但过滤组件需要绑定字段，这个会导致传参的不方便，有时会为了这个组件的特定去建一个无实际作用的数据集来给组件绑定。

过滤组件只是对 参数 进行传值的，是否可以取消 字段 绑定的强制关系， 请官方评估。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，请问对数据集传参数，是传外部参数吗？

**Comment by cadcamzy** [comment]
是内部参数，不是外部。

**Comment by yayanpei-fit2cloud** [comment]
是数据集sql语句中的变量吗？

**Comment by cadcamzy** [comment]
是的， 数据集中的变量。

**Comment by yayanpei-fit2cloud** [comment]
请问是哪个过滤组件？是文本搜索组件吗？

**Comment by cadcamzy** [comment]
时间过滤组件，业务上需要传递一个时间段过去，比如2024-07-31 16:00:00   至  2024-08-31 16:00:00

**Comment by yayanpei-fit2cloud** [comment]
v1 上后面主要是修复bug，目前没有计划进行功能的优化，issue我们先关闭了，再次感谢您对项目的支持。
