### ISSUE TITLE
[Bug]视图编辑界面，排版混乱

### ISSUE THREAD

**Issue by caiiansheng** [dataease/dataease#1140]
**DataEase 版本**
1.4

**浏览器版本**
all

**Bug 描述**
视图编辑界面，数据排版混乱

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/26760483/140697341-53b5f928-ac8e-4f30-bc02-5a06e5b77faa.png)

**Comment by xuwei-fit2cloud** [comment]
一直未重现该问题，应该和本地源码开发环境有关。
