### ISSUE TITLE
[Feature]基础柱形图/条形图的不同类别可以有不同颜色

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#11402]
DataEase 版本:

v2.9.0
**请描述您的需求或者改进建议.**
目前基础柱形图/条形图的不同类别：
![image](https://github.com/user-attachments/assets/e2d96660-8bfc-4c70-a003-ab0bfd18b24f)
期望效果，可以设置颜色上的区分：
![image](https://github.com/user-attachments/assets/74bf46a6-04b6-410a-ac52-257706eb022e)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已经在需求池中，目前图库不支持，近期暂时无法解决，issue我们就先关闭了。
