### ISSUE TITLE
[Feature]动态数据可视化

### ISSUE THREAD

**Issue by xun986** [dataease/dataease#1141]
**请描述您的需求或者改进建议.**
不知道以后会不会考虑制作一些高大上的动态数据可视化效果，比如BV1H441137kj这种随着时间流动变化的视图，或者流向地图什么的

**Comment by yayanpei** [comment]
感谢您的反馈，随着产品成熟度越来越高，后期我们也考虑支持更加丰富的图表，还请多多关注。

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已支持流向地图，请更新最新版本。
