### ISSUE TITLE
[Feature]公共链接支持全屏功能

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#11425]
DataEase 版本:
v2.9.0

**请描述您的需求或者改进建议.**
分享链接打开的数据大屏，没有办法全屏。v1 的公共链接有全屏的功能，希望加上。

**Comment by xuwei-fit2cloud** [comment]
已经在设计中。

**Comment by xuwei-fit2cloud** [comment]
可以添加组件，通过组件的事件来实现全屏。
