### ISSUE TITLE
[Bug]升级到 1.4 后之前的一些数据集打开报错

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1142]
**DataEase 版本**
V1.4.0

**浏览器版本**
Chrome 95

**Bug 描述**
今天发现打开之前正常使用的一些 Excel 数据集报错，不知是否与升级有关系

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/48945409/140720986-845b8e0a-4882-4fde-98c9-496d2836e6de.png)

**Comment by xuwei-fit2cloud** [comment]
我们排查一下

**Comment by tjlygdx** [comment]
doris-fe没有启动, dectl reload  就好了
