### ISSUE TITLE
增加点击数据或者按钮弹窗的功能[Feature]

### ISSUE THREAD

**Issue by aitting** [dataease/dataease#11421]
DataEase 版本:

**请描述您的需求或者改进建议.**
很多时候都需要点击某一个数据然后弹出窗口显示明细数据的场景，目前没有弹窗的功能

**Comment by xuwei-fit2cloud** [comment]
您说的点击某一个数据，弹出的是该行数据相关的明细，还是这个数据所在图表的所有明细数据？
