### ISSUE TITLE
[Bug]符号地图提示修改后恢复默认值问题

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#11435]
**DataEase 版本**
v2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge最新

**Bug 描述**
如图，修改了提示内容后，重复选中图表点击空白处，会出现提示恢复默认配置问题

**Bug 重现步骤(有截图更好)**
![recording](https://github.com/user-attachments/assets/0ac57c21-07e0-4708-9fcd-8917006723f6)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内修复；
