### ISSUE TITLE
[Bug]大屏空白处无法右键粘贴

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#11438]
**DataEase 版本**
2.9.0
如图，复制组合后，无法在大屏空白处右键粘贴。右键组合有粘贴选项，此时再右键点击空白处，菜单会变为粘贴，但无法在空白处唤出右键菜单。
![recording](https://github.com/user-attachments/assets/173d655b-5b84-49a8-a1e9-24f679d7d867)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
