### ISSUE TITLE
[Bug]数据大屏组合复制后无法双击修改组合内的富文本

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#11437]
**DataEase 版本**
2.9.0

如图，组合复制后，无法双击编辑组合内的富文本
![recording](https://github.com/user-attachments/assets/9a24628c-80df-49c2-915f-0b8e8d6786f6)

**Comment by BBchicken-9527** [comment]
反馈，如果无法修改应该是组合图层中边框或者图表在最上层的原因，我们讨论一下是否有方法可以对此处作出优化；

**Comment by liuboF2c** [comment]
> 反馈，如果无法修改应该是组合图层中边框或者图表在最上层的原因，我们讨论一下是否有方法可以对此处作出优化；

第一次创建组合后可以修改富文本，只有复制组合后才无法修改。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
