### ISSUE TITLE
[Bug]组件背景色误触发问题

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#11439]
**DataEase 版本**
2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge最新

**Bug 描述**

如图，当调整组件背景色时，如果鼠标移动到最底部，会出现色值恢复红色问题
![recording](https://github.com/user-attachments/assets/04f9b1e4-fc93-40de-bdd6-ee022990a007)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行优化；
