### ISSUE TITLE
[Feature] 数据源StarRocks选择数据源表详情其中表备注是否可以显示注释

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#11433]
DataEase 版本:
v2.9.0

**请描述您的需求或者改进建议.**
数据源中表带注释
![image](https://github.com/user-attachments/assets/af7ce640-69db-4c1c-bb74-b7bce5a6e618)
目前StarRocks数据源中表备注未能显示
![image](https://github.com/user-attachments/assets/cd71aebc-e0ff-4db5-98c1-6ee50bfb2ee8)

**Comment by xuwei-fit2cloud** [comment]
已排期。
