### ISSUE TITLE
[Feature]针对查询内容的精确授权

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#1144]
**请描述您的需求或者改进建议.**
需求：企业内部为销售团队制作一个仪表板，每个用户仅能查询授权的数据，比如与自己相关的数据、与团队相关的数据等等。
改进建议：建议规划针对用户、数据的映射关系，实现更精确的授权策略。

**Comment by yayanpei** [comment]
感谢反馈，您的建议非常好，我们会优先考虑加入版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 版本已支持，请等待新版本发布
