### ISSUE TITLE
[Feature]查询组件清空重置按钮颜色支持配置

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#11440]
DataEase 版本:
2.9.0

**请描述您的需求或者改进建议.**
如图，只能配置查询按钮颜色，清空重置按钮无法配置，默认的白色有些突兀，希望能提供颜色修改能力。
![image](https://github.com/user-attachments/assets/b142cb14-2bc3-44f9-938b-237a57832c0b)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
