### ISSUE TITLE
[Bug]应用包含计算字段时，复用后计算字段显示异常，预览报错

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#11441]
**DataEase 版本**
2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge最新

**Bug 描述**
应用导入后，数据集中的计算字段显示undefined，预览报错
![image](https://github.com/user-attachments/assets/eb5875d6-9f4f-44b8-8f15-65a197173358)
![image](https://github.com/user-attachments/assets/a4cf6dae-796e-4d35-9a93-bfeb0a88c99a)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by ziyujiahao** [comment]
https://github.com/dataease/dataease/commit/2830b36f93769131d432b19fdca67f66cc1a1786
