### ISSUE TITLE
[Feature]查询组件冻结窗格

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11456]
DataEase 版本:v2.9

**请描述您的需求或者改进建议.**
查询组件在网页、移动端的页面中不会随着页面的滚动而消失，类似 excel 的冻结窗格

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先加入需求池中。

**Comment by xuwei-fit2cloud** [comment]
短期内没有支持计划。建议使用大屏的弹窗区。
