### ISSUE TITLE
[Bug]数据大屏在浏览器打开全屏后底部有个白条

### ISSUE THREAD

**Issue by hmc819358194** [dataease/dataease#11455]
**DataEase 版本**2.7以及在线体验版本都有

**运行方式(安装包运行 or 源码运行 ?)**源码运行

**浏览器版本**谷歌、联想浏览器都有

**Bug 描述**数据大屏在浏览器打开全屏后底部有个白条

**Bug 重现步骤(有截图更好)**
1.
![0809](https://github.com/user-attachments/assets/a8d7c388-651e-4598-b567-7feca76eac0f)

2.
3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们在v2.10版本会对数据大屏的屏幕适应方式提供多种选择，届时应该能解决该问题。
