### ISSUE TITLE
[Feature]安装脚本加入 umask 设置

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#11459]
DataEase 版本:
v2

有些用户环境对虚拟机做了初始化配置，导致 umask 不是默认的 0022，这种设置，会导致 MySQL 启动报错没有权限；
我们会手动将操作系统的 umask 改为 0022 ，删除安装目录，再次安装才会成功。
希望在安装脚本检测系统 umask，如果不为 0022 则改为 0022。

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
用户环境处于安全考虑，可能会对umask进行一些优化配置。
我们不建议在用户不知情的情况下，通过脚本修改umask。
建议保持现状。
