### ISSUE TITLE
仪表板导出图片没反应[Bug]

### ISSUE THREAD

**Issue by JuneYanL** [dataease/dataease#11461]
**DataEase 版本**
社区版 v2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
docker一键部署

**浏览器版本**
Chrome 已是最新版本
版本 127.0.6533.100（正式版本） （64 位）

**Bug 描述**
仪表板导出图片没反应

**Bug 重现步骤(有截图更好)**
1.编辑仪表板，选择视频，视频链接：http://vjs.zencdn.net/v/oceans.mp4
2.保存仪表板
3.导出图片，没有反应
![image](https://github.com/user-attachments/assets/217d07e8-3a43-461f-858d-f8d2092a8746)

**Comment by xuwei-fit2cloud** [comment]
抱歉，视频组件不支持导出图片。
