### ISSUE TITLE
[Feature]时间组件能动态支持最近1天或者7天等

### ISSUE THREAD

**Issue by liudezhi2098** [dataease/dataease#1146]
<img width="761" alt="企业微信截图_de8c9dea-5abc-4cbe-9b56-4f7412566bbd" src="https://user-images.githubusercontent.com/33149602/140847070-8d5c19ae-06f7-41f2-b494-d44eceb07da3.png">

增加最近1天或者7天，当打开报表时自动显示的是最新的，而不是全部数据

**Comment by yayanpei** [comment]
感谢反馈，该需求已经在需求清单中，我们需要先讨论一下方案。

**Comment by liudezhi2098** [comment]
@yayanpei 这个需求什么时候会支持哈

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 已支持，请等待新版本发布
