### ISSUE TITLE
[Feature]1.18.23 密码到期修改能否优化为类似初始密码登录后弹窗强制用户改密码

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#11467]
DataEase 版本:
1.18.23

**请描述您的需求或者改进建议.**
该版本的密码到期后，在登录时提示“密码已过期，请联系管理员进行密码重置”，这种做法是否能优化为让用户登录后弹窗强制用户改密码？ 类似用初始密码登录强制改密码的效果？
![8a46be0264856bba4c8ff47ba447758](https://github.com/user-attachments/assets/cf580b85-bd1f-407b-8e0c-9440f43a8988)

**Comment by xuwei-fit2cloud** [comment]
在密码即将到期前一周，DataEase会在页面上强提醒。我们并不好强制在某个时间上以弹窗的形式要求用户改密。所以目前先保持现状。
