### ISSUE TITLE
无法对数据集进行排序

### ISSUE THREAD

**Issue by SuperManYo** [dataease/dataease#11460]
自定义的数据集无法使用order by  排序 查询数据，
![image](https: //github.com/user-attachments/assets/c9f1d9be-5f48-4580-9cbd-f6b052d24c35)

在仪表盘中对表格中的数字类型字段选择排序方式，表格直接无法显示内容
![image](https://github.com/user-attachments/assets/89d88a5f-5287-445b-a079-cf626592a06d)

有什么办法可以使用排序

**Comment by SuperManYo** [comment]
补充自定义数据集的图片
![image](https://github.com/user-attachments/assets/e1de4a35-4497-42d9-a6d7-1350bbba1b30)

**Comment by yayanpei-fit2cloud** [comment]
数据集中sql语句执行报错了吗？建议将sql语句直接在数据库中执行试试，能够执行。

**Comment by SuperManYo** [comment]
> 数据集中sql语句执行报错了吗？建议将sql语句直接在数据库中执行试试，能够执行。

在数据库中可以执行，实际上在数据集中只要把order by 去掉，也是可以执行的，加上就不可以了，是sql server 数据库

**Comment by yayanpei-fit2cloud** [comment]
是sql server 的哪个版本？

**Comment by SuperManYo** [comment]
> 是SQL Server 的哪个版本？

SQL Server 2019

**Comment by yayanpei-fit2cloud** [comment]
图表中查询数据时，会将数据集的sql语句作为子查询进行查询，数据库不支持子查询中直接加order by，因此sql查询时会报错。
