### ISSUE TITLE
[Bug] 未修复的  Bug 仪表板和数据大屏在外部跳转时，原页面报错 #10852

### ISSUE THREAD

**Issue by pmtea** [dataease/dataease#11469]
**DataEase 版本**

2.9.0 社区版
**运行方式(安装包运行 or 源码运行 ?)**

安装包运行
**浏览器版本**
edge 106

**Bug 描述**

#10852 同样的Bug
提示跳转错误，但是可以跳转成功。
**Bug 重现步骤(有截图更好)**

![IMG_7798](https://github.com/user-attachments/assets/99b4c651-f78f-4bac-b4f5-b581a1a25182)

**Comment by BBchicken-9527** [comment]
感谢反馈，方便详细说明一下复现步骤吗？我们这边测试环境模拟一下；

**Comment by yxp1** [comment]
跳转设置外部链接，为仪表板/大屏公共链接的链接

**Comment by BBchicken-9527** [comment]
目前测试环境没有发现你说的问题，方便看一下后台日志嘛？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
