### ISSUE TITLE
切换主图功能优化

### ISSUE THREAD

**Issue by chenly-y** [dataease/dataease#11472]
**DataEase 版本**
V1社区版

**运行方式(安装包运行 or 源码运行 ?)**
官网上运行

**浏览器版本**
最新

**Bug 描述**
切换主图的，没保存的时候不要回到初始化呢？用户只是想看下主题色的效果，然后不满意选了不保存，返回页面一看，都回到默认样式了

**Bug 重现步骤(有截图更好)**

<img width="632" alt="1e140bc061c79cd34ac0e6fab4fe6e0" src="https://github.com/user-attachments/assets/89b80910-3dfb-4e7a-b847-d3bc0a743457">
<img width="626" alt="817157f3bf52ff3fbae899a9a8e959c" src="https://github.com/user-attachments/assets/337c288b-38bf-4298-9478-a470c5478772">
<img width="628" alt="457df8c6a78637c17fef529dfb2230b" src="https://github.com/user-attachments/assets/8e01188f-15bf-40ac-9ce2-a66e85241a4a">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后两个版本内进行修复；
