### ISSUE TITLE
[Bug] 数据源、数据集，数据格式显示错误

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#11474]
**DataEase 版本**
2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
离线

**浏览器版本**
最新版

**Bug 描述**
数据源、数据集，数据格式显示错误

**Bug 重现步骤(有截图更好)**
1.新建数据源，原始数据（文本类型）如下：
![image](https://github.com/user-attachments/assets/405064ad-a58b-4590-b125-0252c74bf413)
2.shuan上传之后数据源数据预览，不限是“0”
![image](https://github.com/user-attachments/assets/6d63f793-1a94-49a2-beba-9293cae77e2a)
3.数据集预览，不显示“0”
![image](https://github.com/user-attachments/assets/5b799f58-5714-4987-a918-e792fc1e9ca7)
4、仪表板数据预览，不显示“0”
![image](https://github.com/user-attachments/assets/44dce968-d811-44cf-91e4-7644f5a521d2)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题会在后续两个版本内修复；
