### ISSUE TITLE
[Feature]DataEase的表单是否可以支持Blob字段

### ISSUE THREAD

**Issue by vvccjj111** [dataease/dataease#11488]
DataEase 版本: V2

目前表单中只有文本，日期时间，数值可选，是否可以增加对数据库中存储的 图片文件路径展示 或者直接可以读取数据库中的blob字段，从二进制转换为图片？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前我们暂时没有计划支持，v2.10.lts版本会支持新的图片类型，建议将图片转为在线图片，即可以在图表中展示为图片。
