### ISSUE TITLE
[Feature]希望明细表支持自定义固定一列或多列

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#11482]
DataEase 版本:
2.9

**请描述您的需求或者改进建议.**
希望明细表支持自定义固定住一列或多列，然后后面的列可以以滚动条方式拖拉。像透视表一样，表头字段会固定，但客户的数据格式更适合使用明细表，所以希望增加此功能。（意向客户需求）
![image](https://github.com/user-attachments/assets/422d2b58-6823-441b-bf8b-56ebe8266702)

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
