### ISSUE TITLE
[Feature]希望精细化调节多个筛选框长度不一致，导致不对齐的问题

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#11484]
DataEase 版本:
2.9

**请描述您的需求或者改进建议.**
当设置多个筛选框时，筛选名称字数不同，会导致筛选框不对齐，影响美观，希望可以根据每一个筛选框的位置调整或拖拽移动。（意向企业客户需求）
![image](https://github.com/user-attachments/assets/8c47780e-d23a-402a-9866-d21a3bf39dee)
![image](https://github.com/user-attachments/assets/95812de7-1ad6-4c37-bcb3-b982d3c6d779)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议将查询条件位置设置在组件的上侧。
![image](https://github.com/user-attachments/assets/91e5dce3-f9d8-4314-b221-eb450fe85d4b)
