### ISSUE TITLE
[Feature]希望支持对普通用户隐藏DE系统中API和API Key

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#11481]
DataEase 版本:
2.9

**请描述您的需求或者改进建议.**
希望支持配置DE系统中API 和API Key的权限，管理员可以对普通用户隐藏该功能，面对各种不同的DE使用场景，包括内部多区域多组织共用、外包人员共用、客户共用等情况，隐藏API和API Key后，避免有人利用了API造成风险。（准企业客户需求）

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们讨论一下。

**Comment by xuwei-fit2cloud** [comment]
API key的权限和用户本身在控制台的权限是一致的，不会存在风险问题。
