### ISSUE TITLE
[Feature] v2 公共链接视图明细导出优化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#11487]
DataEase 版本:
v2.9

**请描述您的需求或者改进建议.**
v2.9 公共链接导出明细数据，点击下载后没有提示，数据量比较大的情况下，用户可能会认为系统无响应而多次点击，造成服务崩溃，是否可进行优化，增加遮罩层，或者重复点击时给予提示。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。
