### ISSUE TITLE
[Feature] 水印功能需要完善，开启水印后，图表的放大和查看数据目前没有水印

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#11496]
DataEase 版本:
v2.9.0

**请描述您的需求或者改进建议.**
开启水印后，其他角色只有查看权限，仪表板上有水印，点击查看数据和放大也应该带有水印
![image](https://github.com/user-attachments/assets/4391edf1-e856-4b52-9b3c-ad179c16b7cc)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，这个需求已经在v2.10.lts版本中完成，请等待新版本的发布。
