### ISSUE TITLE
[Feature] 仪表盘查询条件二次过滤

### ISSUE THREAD

**Issue by zhaohaihong** [dataease/dataease#11499]
DataEase 版本:

**请描述您的需求或者改进建议.**

仪表盘的查询条件是从数据中获取枚举值，希望在设置外部参数的情况下，在外部参数生效之后从过滤后的数据中获取枚举值，谢谢~

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，外部参数值传递给查询条件，查询条件联动图表，用于过滤图表数据。外部参数值并不用于过滤查询条件的枚举值。
