### ISSUE TITLE
[Feature]关联数据集想要提供 sql 功能或简单的数据处理等功能

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11503]
DataEase 版本:
v2.9.0

**请描述您的需求或者改进建议.**
关联数据集想要提供 sql 功能或简单的异常值处理等处理功能，能够对数据作简单的预处理。

**Comment by yayanpei-fit2cloud** [comment]
相同issue：https://github.com/dataease/dataease/issues/11505
