### ISSUE TITLE
[Bug]单数据集sql动态传参传入动态的参数出错

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11502]
**DataEase 版本**
v2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
google

**Bug 描述**
单数据集使用动态参数传入动态参数错误

**Bug 重现步骤(有截图更好)**
1.写sql
![image](https://github.com/user-attachments/assets/a175728d-2bf6-41e9-ac29-fd10a9a574d5)
![image](https://github.com/user-attachments/assets/b5171491-7976-4bcc-b467-48183d7447cd)

2.为普通的维度时正常传参
![image](https://github.com/user-attachments/assets/1aeb513f-b18b-4798-9eb7-39c183f028fe)
![image](https://github.com/user-attachments/assets/d4dfa916-a7b1-466f-8bbc-7a0325156675)
查询正常
3.使用sql参数传参时报错
![image](https://github.com/user-attachments/assets/03eb1d0e-3b76-45c9-bf97-8eaa6d2995fb)
测试发现，现在的时间转为文本格式或者是时间格式都会产生这个错误。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，方便详细说一下具体步骤以及给出相应的日志嘛？
![image](https://github.com/user-attachments/assets/58ae32ff-b010-48bc-a8a0-df9b754a5a86)
