### ISSUE TITLE
[Feature] 仪表盘外部参数必传校验 

### ISSUE THREAD

**Issue by zhaohaihong** [dataease/dataease#11501]
DataEase 版本:

**请描述您的需求或者改进建议.**

希望可以为仪表盘外部参数添加必传校验开关，如果分享链接中不包含必传参数，就不能进行访问，和 ticket 必填效果一样，谢谢~

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本迭代中会进行支持。
