### ISSUE TITLE
[Feature] 数据大屏缩放放大至 300%

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#11519]
DataEase 版本:
v2.9

**请描述您的需求或者改进建议.**
当前数据大屏的缩放最高 200%，在做一些复杂的大屏的时候，仍然不太够，可否最大允许 300%

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先记入需求池中，近期暂时没有计划再放大。
