### ISSUE TITLE
[Feature] 数据大屏支持更多的整体样式设置

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#11518]
DataEase 版本:
v2.9

**请描述您的需求或者改进建议.**
数据大屏同仪表板，支持更多的整体样式配置，如图表样式、查询组件等
![image](https://github.com/user-attachments/assets/ee63c72d-4263-4fb1-9a7e-f91c73d490ce)
![image](https://github.com/user-attachments/assets/b90fe538-18f1-4f32-b7a3-24272dd40b25)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，目前暂时没有计划支持，建议批量选中组件，批量修改组件样式。
