### ISSUE TITLE
[Bug]The server responds 500 but no detailed message.

### ISSUE THREAD

**Issue by 1312564541** [dataease/dataease#1151]
**DataEase 版本**
v1.4.0

**浏览器版本**
Safari浏览器 版本15.1 (17612.2.9.1.20)

**Bug 描述**
The server responds 500 but no detailed message.

**Bug 重现步骤(有截图更好)**
1.添加Excel数据集
2.点击文件上传
3.选取Excel文件
4.点确认。
![image](https://user-images.githubusercontent.com/26996878/140876444-4859f2d6-2028-4afc-b7f8-96abc1e6bae9.png)

**Comment by xuwei-fit2cloud** [comment]
看截图应该是网络问题
