### ISSUE TITLE
[Bug] api 数据源转换为数值的字段图标仍然是文本类型，影响快速判别类型

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11525]
**DataEase 版本**
v2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
google

**Bug 描述**
api 数据源转换为数值的字段图标仍然是文本类型，影响快速判别类型
![5ac5ade3-e281-4b9e-8211-ce2825271af9](https://github.com/user-attachments/assets/9f2bda4c-2ddb-46fb-81e1-3564fef568a5)

![5a541c10-fa46-4d36-82ab-d20e02fcfa24](https://github.com/user-attachments/assets/721fe737-a1b0-494d-93e9-ed902c1986fe)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行优化；
