### ISSUE TITLE
[Bug]数据源是impala时转换时间字段不行，但是相同数据在 mysql 中可以

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11522]
**DataEase 版本**
v2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
google

**Bug 描述**
 我的是自定义SQL 查询出来的这种
![dbe7c32c-ed18-4a92-951d-7705052d8f78](https://github.com/user-attachments/assets/b5f98e71-41d6-4b7f-a760-a32c99a5f63f)
转化的时候就有问题

格式 没啥问题。因为类似的SQL，在MySQL协议查出来转化就没问题，数据源是impala就不行。 
用MySQL协议的数据源 没有这个问题。原始是 timestamp，也尝试了在SQL里先处理为了日期字符串
![2f2f1af7-166f-4694-8f9b-03db65b1169a](https://github.com/user-attachments/assets/98597e97-8f29-4472-86f0-2b628aa9c7ef)

试过了，这些也不行。
![企业微信截图_17235383128279](https://github.com/user-attachments/assets/85f75af5-e6eb-4a08-9a44-cefcce76884c)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
