### ISSUE TITLE
[Feature]查询条件，输入文本大小设置不了&查询组件只能设定一个按钮大小

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11523]
DataEase 版本:
v2.9.0

**请描述您的需求或者改进建议.**
查询条件，输入文本大小设置不了，但是其他的一旦设置，这里会显得很丑，需要优化
![ac1fb5dd5f86933136381f0c047c66a](https://github.com/user-attachments/assets/d6f7e8bd-d1a9-4ddd-bede-dbce1a3a8de4)
查询组件只能设定一个按钮大小，确定按钮一设置后，清空这些按钮就显得特别突兀，需要优化
![e0bdaabc4249e59bed4f3596959feed](https://github.com/user-attachments/assets/0b707086-4e88-4966-8019-321519980b1f)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们在近期的版本中优化一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
