### ISSUE TITLE
[Feature]tips添加

### ISSUE THREAD

**Issue by xun986** [dataease/dataease#1152]
**请描述您的需求或者改进建议.**
希望能在刚进入页面时，能像DataGrip等软件一样出一些用户不容易想到的tips小窗随机出现。
如果可以的话，也许可以做一个用户初次登陆的入门操作教程，就是用提示操作的方法牵引用户用demo材料制作出一个简单的仪表板，让对方熟悉这个流程。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个在后期我们会考虑加到产品了来。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
