### ISSUE TITLE
[Feature] 数据大屏支持按住空格键，鼠标点击移动画布位置

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#11521]
DataEase 版本:
v2.9

**请描述您的需求或者改进建议.**
数据大屏支持按住空格键，鼠标点击移动画布位置，这样可以更方便的进行大屏布局。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记入需求池中，快捷键后期会逐渐进行支持。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
