### ISSUE TITLE
[Bug] 富文本字段选择图标被遮挡

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#11520]
**DataEase 版本**
v2.9 

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
Chrome 已是最新版本
版本 127.0.6533.100（正式版本） (arm64)

**Bug 描述**
富文本数据库字段选择图标被工具栏遮挡

**Bug 重现步骤(有截图更好)**
1. 如下所示：
![image](https://github.com/user-attachments/assets/33106396-2ecd-48b9-b3eb-eafcf426631d)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行优化；

**Comment by xuwei-fit2cloud** [comment]
暂不处理。
