### ISSUE TITLE
[Feature]进度条视图也可以加圆角效果

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#11542]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
<img width="196" alt="image" src="https://github.com/user-attachments/assets/9ae50684-c4a2-4785-a16c-6b50c81d80c0">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中会进行支持。
