### ISSUE TITLE
[Bug]v1 指标卡批量操作字体和名称加粗失效

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#11543]
**DataEase 版本**
1.18.23

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**Bug 描述**
v1 指标卡批量操作字体和名称加粗失效

**Bug 重现步骤(有截图更好)**
1.v1 指标卡批量操作字体和名称加粗失效
![image](https://github.com/user-attachments/assets/f3ff8129-8b7d-485a-afe8-6666e00830c0)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
