### ISSUE TITLE
[Feature]自定义数据集中期望给出注释的地方，加载时自动过滤这些注释

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11546]
DataEase 版本:
v2.9.0

**请描述您的需求或者改进建议.**
自定义数据集中期望给出注释的地方，加载时自动过滤这些注释。实际上， sql 自定义数据集的 ctrl + / 是有 handle 的方法来生成 "--注释" 格式的，但是执行会报错，能不能加一个官方的注释，然后自动过滤掉这些注释，仅方便编辑呢，发现很多用户会加上注释，然后研究半天发现是不能注释的问题。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池中，在版本迭代中优化一下。
