### ISSUE TITLE
[Feature]透视表维度数据全为列维度时希望可以显示数据表数据

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11553]
DataEase 版本:

**请描述您的需求或者改进建议.**
透视表维度数据全为列维度时希望可以显示数据表数据。透视表全为列维度时无法显示数据表数据，而全为行时可以
![f50f4035a14de9bf01eef07953d10c1](https://github.com/user-attachments/assets/a6f296de-8a23-43a2-9f67-2b4532aebb80)
![00984d3d5fbecea8d27dfe35b8a2949](https://github.com/user-attachments/assets/41f3adbb-7f73-4e3e-aaa9-3bfae8a6ad90)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要看下图库是否支持。

**Comment by yayanpei-fit2cloud** [comment]
图库不支持，因此近期无法进行支持，issue我们就先关闭了。
