### ISSUE TITLE
[Bug]高分辨率下，定时报告中的折线和柱状图显示不正确

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#11568]
**DataEase 版本**
1.18.20

**运行方式(安装包运行 or 源码运行 ?)**
企业版试用包

**浏览器版本**
chrome

**Bug 描述**
在企业版试用版中，antV的折线图、柱状图类图形横向拉满屏幕的时候，此时定时报告使用比较大的分辨率时，邮件中的图形会出现折线图断点，柱状图柱高显示和数值对应不上的问题。 echarts的折线图、柱状图在1660以上的分辨率下，邮件的图形也出现不稳定（时好时坏）的情况。 
另外，我们看到2.0版本只使用了antV的图形，请也同样验证下2.0是否有一样的问题。

**Bug 重现步骤(有截图更好)**
以下为图例，二个柱状图，都是横向拉满了屏幕宽度。上面为antV柱状图，下面为echarts柱状图，高分辨率下，antV柱状图的柱高明显和数值不符
![image](https://github.com/user-attachments/assets/70c91412-095c-453f-b8ff-c15611e3e060)

**Comment by BBchicken-9527** [comment]
感谢反馈，可能是当时导出时图表没有加载完全导致的，可以试试加载仪表板额外等待时间这个配置项；

**Comment by xiaorsly88** [comment]
试过，不是加载时长的问题，而是antV的折线图和柱状图，高分辨率下就有这个问题，你们可以试试1660以上的分辨率，像我的示例中一样，横向全屏测试下

**Comment by xiaorsly88** [comment]
echarts的折线和柱状图在1660以下分辨率还算稳定，但高分辨率下也会经常出现。你们可以多验证1.0和2.0版本， 特别是2.0版本，只保留了antV图形，1.0的这些问题都可能是2.0的潜在问题

**Comment by xiaorsly88** [comment]
@BBchicken-9527 @Shenguobin0102 请查阅以上回复

**Comment by BBchicken-9527** [comment]
感谢反馈，我这边测试发现正好与你相反，我这边看应该是echarts存在问题，但这个问题看着像是没有加载完全导致的；
![image](https://github.com/user-attachments/assets/fa1d292b-f3b8-4ac9-aa78-8e5d99d0c2dc)

**Comment by BBchicken-9527** [comment]
我尝试了一下延长等待时间发现是可以显示完整的，你可以再尝试一下加长延迟等待时间试试看；
![image](https://github.com/user-attachments/assets/a8e47d4b-7745-4acf-9a81-ace107dde49e)

**Comment by xiaorsly88** [comment]
不是时间的问题，是在1440以上的高分辨率下，antV和echarts都是有大概率出现这种问题，但在小于等于1440的分辨率下，相对而言echarts比antV要稳定很多。 这是组件本身的问题导致的吗？

**Comment by BBchicken-9527** [comment]
感谢反馈，定时报告的截图其实也是用的前台的截图功能，只不过是后台打开了一个无头的浏览器，所以如果时间足够其实是可以显示完整的，如果你导出的图片过于大，导致加载时间过长，那是会导致图表在动画的途中被截图的，所以你看到的指标轴与图片不一样；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
