### ISSUE TITLE
[Feature]希望增加一个图片超链接类型，这个图片是请求http地址呈现出来的

### ISSUE THREAD

**Issue by wys1010** [dataease/dataease#11566]
DataEase 版本:V2

**请描述您的需求或者改进建议.**
希望增加一个图片超链接类型，列表中某个字段如果是这种类型就去请求图片，图片是http地址请求得来的，其实很多场景都有这种需求，比如车辆通行记录列表中就包括车辆抓拍图片，人员通行记录列表中就有人员抓拍图片等。

呈现的效果参考：
![image](https://github.com/user-attachments/assets/ed5cb6aa-e36a-4981-9cc2-964a7a71d15d)

目前dataease的效果如下：
![image](https://github.com/user-attachments/assets/4f90f234-398d-4ffc-b2a7-6b7f7e5d313c)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，该需求已经规划在v2.10.lts版本中，请等待新版本的发布。
