### ISSUE TITLE
[Feature]查询组件按钮只能放在选项框后面，不符合使用习惯，如果隐藏按钮后清空，重新输入不太方便

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11565]
DataEase 版本:
v2.9.0

**请描述您的需求或者改进建议.**
查询组件按钮只能放在选项框后面，用户反馈不符合使用习惯，如果隐藏按钮后清空，重新输入不太方便。需要按钮支持位置调整，支持大小设置，清空、重置按钮也需要有相应的调整适配。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，目前暂时没有计划调整。

**Comment by zhainanshidai** [comment]
为啥，是不好实现还是，目前是只能放在最后面的，感觉有点不灵活
