### ISSUE TITLE
[Feature] v2 版本查询组件时间范围动态传参是否可以优化直接选择范围

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#11567]
DataEase 版本:
v2.9.0

**请描述您的需求或者改进建议.**
目前需要一个一个参数去绑定时间
![image](https://github.com/user-attachments/assets/7061311a-a3e7-40d7-a9f2-690d9a040634)
是否可以优化为直接可以选择时间范围
![image](https://github.com/user-attachments/assets/da356e5d-29b8-4e09-b147-fdf0a6d137ca)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，目前暂时没有计划支持。
