### ISSUE TITLE
[Bug] v2.8.0 升级到 v2.9.0 后，出现查询组件关联组件样式混乱的现象，且仅在部分用户有体现。已经试过清除缓存、更换浏览器、放缩页面大小比例等常规方法

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11574]
**DataEase 版本**
v2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
google、edge

**Bug 描述**
 v2.8.0 升级到 v2.9.0 后，出现查询组件关联组件样式混乱的现象，且仅在部分用户有体现。已经试过清除缓存、更换浏览器、放缩页面大小比例等常规方法

**Bug 重现步骤(有截图更好)**
1.升级后使用
![74fef2cd-63f0-4dd2-a28c-b23c36999185](https://github.com/user-attachments/assets/703d1098-c211-43a9-ad28-c6cf1912ffa0)

2.重装后使用
![de0ba1d1-a282-47a4-bd5c-4f94afa598f5](https://github.com/user-attachments/assets/e9b0bb27-17af-45b0-8e0e-c8ac612472da)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下；

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
