### ISSUE TITLE
[Question]【图表】后续如果要支持复杂报表，不知道是否可以支持上维护上下标的功能

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#11578]
**请描述您的问题.**
咨询一下哈。
后续如果要支持复杂报表，不知道是否可以支持上维护上下标的功能，如下图所示。
比如维护同比和环比展示到上标或者下标。
![8e286de2381c58d772fcfa6bb05f870](https://github.com/user-attachments/assets/ddf58c01-e091-48e7-9cff-92c10757cc5d)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，复杂报表支持后，功能会逐渐完善的，需求已记录记录，目前还不确定，issue我们先关闭了。
