### ISSUE TITLE
[Bug]查询组件关联字段处不能删除多余关联字段，且未选关联项也必须有关联字段

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11571]
**DataEase 版本**
v2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
google

**Bug 描述**
查询组件关联字段处不能删除多余关联字段，且未选关联项也必须有关联字段

![image](https://github.com/user-attachments/assets/98dfdac5-5d16-48cf-ba0b-e3dd08d3b400)

已选择好字段后，点击确认，发现没有关联字段且未勾选的组件会导致报错。这时想删除关联的组件发现删除不了。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境未发现你说的问题，尝试了直接拖拽字段和创建规则，方便的话详细说明一下；
![image](https://github.com/user-attachments/assets/2d564b1e-2269-40ac-8435-0a1a3350e8bc)
