### ISSUE TITLE
[Feature]查询组件可以上传图片当作背景

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#11585]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
![image](https://github.com/user-attachments/assets/b2c02b00-4c1b-4e1f-acf4-181d66c9f209)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中支持一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
