### ISSUE TITLE
[Bug] 堆叠柱线组合图下钻后，横轴发生错位

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#11587]
**DataEase 版本**
v2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌浏览器

**Bug 描述**
堆叠柱状组合图设置钻取维度后，点击下钻横轴发生错位
<img width="589" alt="图片1" src="https://github.com/user-attachments/assets/3b77d113-8cb1-4aeb-917c-7d77e8e12e7d">
![image](https://github.com/user-attachments/assets/cdb1384f-5999-4df9-84f0-f1be2b316534)

**Bug 重现步骤(有截图更好)**
1.按上图拖入字段钻取
2.点击下钻后，横坐标第一列会多出顶层钻取维度（日期），后面也发生了错位，柱状图不在对应字段上
![image](https://github.com/user-attachments/assets/6ee59899-df41-4574-86a2-e50106e87c59)

**Comment by BBchicken-9527** [comment]
感谢反馈，因为是双轴可能不太好处理，我们想办法看看是否能处理；
