### ISSUE TITLE
[Feature]希望Copilot 对话分析对更换模型

### ISSUE THREAD

**Issue by 673092756** [dataease/dataease#11580]
DataEase 版本:0.2.9

**请描述您的需求或者改进建议.**
希望Copilot 对话分析对更换模型，可以更好的使用本地话模型

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们在后面的版本支持一下。

**Comment by xuwei-fit2cloud** [comment]
Copilot可支持独立运行，企业版可支持配置其他模型。
