### ISSUE TITLE
[Bug] 仪表盘添加筛选条件选择字段时页面错位

### ISSUE THREAD

**Issue by zhaohaihong** [dataease/dataease#11592]
**DataEase 版本**

2.8.1

**运行方式(安装包运行 or 源码运行 ?)**

安装包运行

**浏览器版本**

Chrome 127.0.6533.120

**Bug 描述**

仪表盘添加筛选条件选择字段时页面错位

**Bug 重现步骤(有截图更好)**

仪表盘复用情况下，仪表盘和数据集的名称都比较长，选择关联图表及字段时页面错位，如图所示：
![image](https://github.com/user-attachments/assets/6bf05f00-c334-48e8-a1c1-def22b146c80)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，我这边尝试了新建测试组件复用后添加和直接复用过滤组件，请问有什么必现的方式可以让我这边复现一下吗？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
