### ISSUE TITLE
[Bug]api 数据源连接时非相同字段选用非 json path 连接时，字段能显示全，但本应该出现的数据有缺失

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11595]
**DataEase 版本**
v2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
google

**Bug 描述**
api 数据源连接时非相同字段选用非 json path 连接时，字段能显示全，但本应该出现的数据有缺失。

此外，使用 json path 时，默认是只能选相同全出现的字段，一个字段确实都会导致加载不出来。

详细可以看重现步骤。

**Bug 重现步骤(有截图更好)**

连接 api 数据源 ，查看表字段，发现原应有的都缺失。连接参数正常写，不使用 json path 连接，直接点下一步然后勾选 data 字段
![1723724077216](https://github.com/user-attachments/assets/acab8be1-7203-4731-a77e-c63f0382cd0e)

使用连接工具测试 api 接口，查看数据，发现数据正常，且已经检查参数，和在 DE 都是一致的。但是在 DE 中，查出来是空白的
![a2d62fe0ff26fdb7083feba7d5fbde7](https://github.com/user-attachments/assets/cb2d083f-cf3b-4068-8ad3-8296e46db66b)

使用明细表查看数据，然后使用查询组件查出此人名称，对应数据空白：
![企业微信截图_172371254368](https://github.com/user-attachments/assets/369fbbce-4906-4f26-803f-51306453e1ca)

此时返回去使用 json path 来解析数据，发现解析数据没有对应字段，检验发现 json path 连接需要有相同字段才会解析出来（10000个数据解析时解析数组中少了一个字段的数据就丢掉这个数据，显然是不合理的，至少是可以主动勾选）
![企业微信截图_17237112883481](https://github.com/user-attachments/assets/add38671-66bb-4de6-b990-f892a4d1c7fb)
可以看见，抽取两个 json 组后，没有对应字段：
![企业微信截图_17237112735341](https://github.com/user-attachments/assets/83ed4d5d-e586-4669-b587-1a1cb9f029de)
而选用有该字段的数据后，可以看见字段。
![企业微信截图_17237113523102](https://github.com/user-attachments/assets/ea5617f9-bee2-410a-8918-1235ed97729c)
![企业微信截图_17237113352540](https://github.com/user-attachments/assets/f73dbe89-dd78-4fe0-b0eb-020fe589ab32)

复现完毕

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你的问题，使用你的接口尝试，发现你选择的范围确实是没有这个字段的，前包不后包，所以你索引1的时候可以找到这个字段，你把范围扩大一些就好了；
