### ISSUE TITLE
[Feature]模板可单独调整样式

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#11593]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
这个是有一个真实的场景的，不是只是仅限于做模板市场的那个模板，比如说，往客户的内网，传图片素材不方便，做一个大屏要一直随着调整。随着调整，各种素材要适配，便捷的办法是，导出一个模板，在自己本地完全适配好之后，再把整个模板再导进客户的内网就行了。就不用把一个图片多次各种传来传去。
![image](https://github.com/user-attachments/assets/0885fb64-b627-4515-a920-9143fa44ed53)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划进行支持。
