### ISSUE TITLE
[Bug] 数据大屏图片上传失败

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#11604]
**DataEase 版本**
v2.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 126.0.6478.127

**Bug 描述**
数据大屏图片上传失败

**Bug 重现步骤(有截图更好)**
![image](https://github.com/user-attachments/assets/c16d9324-fdca-4fea-a8b3-f1025497dc9f)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行优化；

**Comment by ziyujiahao** [comment]
https://github.com/dataease/dataease/pull/11826/commits/949cd26758d2458a684c330891ac135450c5e1c0
