### ISSUE TITLE
[Feature]纵轴的格式可以和提示、标签同步

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#11606]
DataEase 版本:
2.x

目前纵轴的数值格式和标签、提示，需单独设置，能否同步设置？设置一个标签，比如单位“万”，同步到纵轴、提示。

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，目前暂时没有计划支持，是各自独立设置的。
