### ISSUE TITLE
[Feature]需要双纵轴的条形，折现图

### ISSUE THREAD

**Issue by 673092756** [dataease/dataease#11608]
DataEase 版本:2.9

**请描述您的需求或者改进建议.**
需要双纵轴的条形，折现图，是两个数据差值太大的话在一个纵轴上面，数值小的显示不全无法更好的观察数据，希望可以增加双轴图形

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，双轴的折线图已规划在近期的版本迭代中，双轴的条形图目前暂时没有计划支持。
