### ISSUE TITLE
[Feature]白标定制 copilot 没有配置关闭的选项

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11605]
DataEase 版本:
v2.9.0

**请描述您的需求或者改进建议.**
白标定制 copilot 没有配置关闭的选项，目前只有小助手的，需要对应的配置。

**Comment by zhainanshidai** [comment]
外观配置处需要增加对应的配置

**Comment by yayanpei-fit2cloud** [comment]
相同issue：https://github.com/dataease/dataease/issues/11458
