### ISSUE TITLE
[Feature]折叠屏手机查看仪表板会横向拉伸

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#11613]
DataEase 版本:
v2

折叠屏手机查看仪表板会横向拉伸
单屏幕查看正常，双屏展开，查看不正常，会横向拉伸
如果有条件可以研究一下，能否识别双屏展开时按 PC 展示。
![图片](https://github.com/user-attachments/assets/8a7449f5-6d16-4d8f-8189-9ccb48fe6b72)

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持。
