### ISSUE TITLE
[Bug] MySQL数据源自定义SQL中同时包含动态参数和 union all 可运行但保存报错

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#11612]
**DataEase 版本**
2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌

**Bug 描述**
MySQL 数据源自定义 SQL 中使用 with as 方式包含动态参数和 union all 可运行但保存报错，删除一个即可

**Bug 重现步骤(有截图更好)**
1.MySQL 数据源创建自定义 SQL，设置好参数值，运行可以出结果
![image](https://github.com/user-attachments/assets/e4369d3d-8d5b-4a5c-8305-6e5893102b2e)
![image](https://github.com/user-attachments/assets/b4102899-347f-453b-906b-3318f651afcf)

2.但是无法保存数据
![image](https://github.com/user-attachments/assets/d678eeb5-4207-4a31-b9b3-8888d85af96e)

3.自定义 SQL 里面删除动态参数或者 union all 其中一个就可以运行并保存
with
    case_base_set as (
        select * from events where id < ${num}
    )
select "test1" as `name`,pa_ming from case_base_set
union all
select "test2" as `name`,pa_ming from case_base_set
union all
select "test3" as `name`,pa_ming from case_base_set;

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内修复；
