### ISSUE TITLE
[Feature] 能否支持从DE上对数据源中的表进行备注

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#11619]
DataEase 版本:
v2.9.0 

**请描述您的需求或者改进建议.**
场景：非数据人员在使用复杂的数据库数据源时，对每张表的作用都不太能理解，希望在研究数据后，能够在DE上对此数据源中的表进行中文备注。
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/dc697506-b135-4966-b558-ab87378c2740">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，目前暂时没有计划支持。
