### ISSUE TITLE
[Bug] tab 组件隐藏选项卡后底部边距变大

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#11628]
**DataEase 版本**
v1.18.23

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

谷歌浏览器最新
**Bug 描述**
tab 组件本来底部组件距离边框正常，隐藏选项卡后底部边距变大影响tab组件

**Bug 重现步骤(有截图更好)**
没有隐藏选项卡的时候边距：
![image](https://github.com/user-attachments/assets/1cce7d41-a39f-4720-89ff-f44b333a5815)
隐藏选项卡，边距巨宽：
![image](https://github.com/user-attachments/assets/b24be844-72db-4dca-8847-af05dfbca729)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
