### ISSUE TITLE
[Bug]postgresql数据源无法创建数据集

### ISSUE THREAD

**Issue by sanwacompany** [dataease/dataease#11623]
**DataEase 版本**
2.9.0社区版本

**运行方式(安装包运行 or 源码运行 ?)**
源码运行+1panel安装包运行都试了

**浏览器版本**
Chromium

**Bug 描述**
连接到postgresql数据库，数据源正常，可以读取表名。打开表，也可以看见字段名。但创建数据集，提示错误“SQL ERROR: ERROR: relation "sheet1" does not exist Position: xxxx”

**Bug 重现步骤(有截图更好)**
1.
![screenshot-20240817-234253](https://github.com/user-attachments/assets/b524a605-c063-481f-a4ec-2e01cff75646)

2.确定schema是正确的，额外字符串也尝试了
![screenshot-20240817-234446](https://github.com/user-attachments/assets/8443ccaa-07da-4157-89f6-2f1bcace696d)

3.通过navicat查看数据库，确认各项信息都是正确的。
![screenshot-20240817-234642](https://github.com/user-attachments/assets/ae2e4b6b-a4be-4f9e-abd2-bd751d334599)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没发现你说的问题，需要确认一下你这边表的数据类型我们这边再看一下是否是数据类型导致；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
