### ISSUE TITLE
[Bug]富文本的插入超链接，选择跳转当前页面，点击后还是跳转到新页面打开了

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#11632]
**DataEase 版本**
v2.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
富文本的插入超链接，选择跳转当前页面，点击后还是跳转到新页面打开了
![image](https://github.com/user-attachments/assets/3867b7c7-a46a-45ba-8714-cdf56d58278c)
<img width="1147" alt="image" src="https://github.com/user-attachments/assets/a50718ad-1e73-4240-ae1a-c5c48a65e52f">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
