### ISSUE TITLE
[Feature]公共链接全屏按钮没法隐藏

### ISSUE THREAD

**Issue by yxp1** [dataease/dataease#11631]
DataEase 版本:

1.18.23
**请描述您的需求或者改进建议.**
tab里面嵌入网页组件想轮博大屏，但是公共链接打开，就会出现这两个全屏按钮，影响轮播展示
![image](https://github.com/user-attachments/assets/d6f66947-facc-41a8-a437-7c6b09dc85ef)

**Comment by xuwei-fit2cloud** [comment]
我们近期版本处理一下。
