### ISSUE TITLE
[Bug]V2.9 API数据识别不全

### ISSUE THREAD

**Issue by Linkjie-11** [dataease/dataease#11633]
**DataEase 版本**
V2.9

**运行方式(安装包运行 or 源码运行 ?)**
离线部署

**浏览器版本**
edge

**Bug 描述**
V1 可以识别到数据，V2识别不到
![图片](https://github.com/user-attachments/assets/811f6ece-5c45-4062-969c-63a8e7a5139b)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前我们这边的测试接口没有发现你说的情况，方便透露一下你的接口结构吗？我们这边模拟一下；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
