### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by hbnight** [dataease/dataease#11649]
**DataEase 版本**
1.18.23

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
安卓 微信内置浏览器

**Bug 描述**
微信浏览器内无法显示内容

**Bug 重现步骤(有截图更好)**
1. 部署项目，添加数据
2. 通过nginx对自有域名进行转发至真实项目
3. chrome浏览器中显示正常。
4. 用微信扫码查看未显示数据
5.
![image](https://github.com/user-attachments/assets/0431c4e6-5262-4a87-9ebc-dff088fd9085)
![image](https://github.com/user-attachments/assets/22ded70b-1c28-4eb3-8f91-eed71adeca5d)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问是否对仪表板进行了移动端布局？

**Comment by hbnight** [comment]
感谢感谢。 我的我的。
