### ISSUE TITLE
[Feature] 表格自适应样式希望可以铺满整个组件宽度

### ISSUE THREAD

**Issue by limin-fit2** [dataease/dataease#11640]
DataEase 版本:

V2.9.0

**请描述您的需求或者改进建议.**
如果表格使用的是自定义列宽和固定宽度方式，自定义列宽方式需要去调整每个列宽的宽度，列宽比较多的时候非常消耗时间，如果当前表格再切换到移动端布局展示时候，宽度就是移动端宽度，那么表格文字就无法看全，只能选择的自适应方式才能去满足移动端展示的效果，但是自适应场景，如果PC端表格的宽度无法铺满整个组件的宽度，导致整体效果看起来会比较奇怪，所以希望表格能够在自适应的情况下铺满整个组件。
当前效果：
![image](https://github.com/user-attachments/assets/08f96cd5-c07f-4d42-8d3d-05298f886e6a)
![image](https://github.com/user-attachments/assets/a994d668-805b-4d7a-a103-a6f2c0aa6de1)

希望展示的效果：
<img width="1319" alt="image" src="https://github.com/user-attachments/assets/95aacbb3-e4c5-42de-8e78-5e3ab58734d0">
![image](https://github.com/user-attachments/assets/341947a4-fe71-40f3-a619-c10c57f79528)

**Comment by xuwei-fit2cloud** [comment]
我们近期版本处理一下。

**Comment by MilkWangStudio** [comment]
+1 同样遇到这个问题了，表格列不够铺满组件，跟第一张图一样，看起来比较奇怪

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
