### ISSUE TITLE
[Bug]创建公链后非报表创建人登录访问公链异常

### ISSUE THREAD

**Issue by zhangwenkl** [dataease/dataease#11650]
**DataEase 版本**
1.18.23

**运行方式(安装包运行 or 源码运行 ?)**
 源码运行

**浏览器版本**
Google Chrome 最新版

**Bug 描述**
A账号创建报表公链
1、在A账号登录的情况下访问公链正常
2、无账号登录的情况下访问公链正常
3、B账号登录的情况下访问公链**异常**

**Bug 重现步骤(有截图更好)**
1.A账号登录并创建报表公链
![创建公链](https://github.com/user-attachments/assets/4dc6cfe4-248e-4deb-9108-f5affb4d9882)

2.登录B账号，并且新加标签页，访问A账号创建的公链，提示无权限
![非创建人访问异常](https://github.com/user-attachments/assets/b7017657-05fb-48ed-91e3-c0b3612b1c66)

**Comment by BBchicken-9527** [comment]
感谢反馈，公共链接本身就是为了外部传递的，如果浏览器存在token会直接用当前的token去访问的，若这个token没有权限就会产生异常；
