### ISSUE TITLE
[Bug] 表格同时设置字号和条件样式后单元格变黑

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#11652]
**DataEase 版本**
v2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌

**Bug 描述**
表格同时设置样式单元格文本14和高级条件样式
![image](https://github.com/user-attachments/assets/49fee64b-052d-40c7-8f52-b69588e88033)

单元格设置条件字段变黑
![image](https://github.com/user-attachments/assets/4d895655-05c2-46a8-8144-27dd34f43a86)

**Bug 重现步骤(有截图更好)**
1.如上图
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
