### ISSUE TITLE
[Feature]能否支持WebApi接口数据源

### ISSUE THREAD

**Issue by 15806122600** [dataease/dataease#1165]
**请描述您的需求或者改进建议.**
考虑到数据库安全性问题，能否在不暴露数据库的情况下通过http网络请求获取数据信息

**Comment by xuwei-fit2cloud** [comment]
这个其实是属于 API 数据源的范畴了，关于对 API 数据源的支持，我们目前还没有明确安排，需要看后续的一个需求情况。

**Comment by lnts2015** [comment]
同问！
