### ISSUE TITLE
[Question]如何去掉数据库依赖的函数和触发器

### ISSUE THREAD

**Issue by mcnultyboy** [dataease/dataease#1166]
由于内部不能使用自定义函数和触发器，是否存在不依赖函数和触发器的分支？如果进行改造，有无建议和方案？

**Comment by xuwei-fit2cloud** [comment]
目前DataEase是通过触发器来自动添加数据权限相关记录的，所以是不可以去掉的，有不存在不依赖函数和触发器的分支。
由于权限体系这块并不在开源版本中，因此没有教好的建议方案。
