### ISSUE TITLE
[Bug]数据集选择日期格式，选择自定义，输入yyyy-MM，刷新数据后字段为空

### ISSUE THREAD

**Issue by wxcen** [dataease/dataease#11665]
**DataEase 版本**
最新版

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome 浏览器

**Bug 描述**
数据集选择日期格式，选择自定义，输入yyyy-MM，刷新数据后字段为空

**Bug 重现步骤(有截图更好)**
1.字段类型为日期
2.选择字段类型为日期的，格式自定义，输入yyyy-MM
3.刷新数据后为空

**Comment by BBchicken-9527** [comment]
感谢反馈，修改字段类型最终也是需要sql去实现的，需要确认你使用的数据库支不支持 yyyy-MM的时间格式；

**Comment by wxcen** [comment]
是用的 Excel 表上传的。
