### ISSUE TITLE
[Bug] V1的WEB组件没有动态刷新功能

### ISSUE THREAD

**Issue by cadcamzy** [dataease/dataease#11663]
**DataEase 版本** 1.8.23

**运行方式(安装包运行 or 源码运行 ?)** Docker

**浏览器版本**

**Bug 描述**
目前显示远程图片，只能通过WEB组件的URL来指定，但此组件无定时刷新功能，无法自动刷新组件来达到更新的目的。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by maninhill** [comment]
v1 不再接受新需求，望理解。
