### ISSUE TITLE
[Bug]v2.9 oracle数据源 日期字段转化

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#11671]
oracle直连，select * from tableA；之后，tableA的日期字段会被判断为文本类型，使用类型转化会报错，如下：
<img width="706" alt="44633106-18fa-4d14-a3a6-9bfd13fd0962" src="https://github.com/user-attachments/assets/6957cc21-ca9d-4e8e-a245-da454c47e948">

oracle通过dblink连接查询（select * from tableA）；tableA的日期字段也会被判断为文本类型，使用类型转换可以转化，但是’yyyy-mm-dd'会转化为‘dd-mm-yyyy’；影响后期对日期字段进行筛选。

**Comment by wolf-kingx** [comment]
补充第二种情况的配图：
![企业微信截图_17242324742841](https://github.com/user-attachments/assets/c40045f7-03ca-46d8-80c9-8d966134d7a5)

**Comment by wolf-kingx** [comment]
补充情况2配图：
![877f2f70b9c72983c75656e6def0e66](https://github.com/user-attachments/assets/d02e16af-fb64-445e-87d4-22077113f12d)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问这个存在问题的字段在源数据中是什么类型？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
