### ISSUE TITLE
[Feature] excel 数据源优化建议

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#11681]
DataEase 版本:
v2.9

**请描述您的需求或者改进建议
当前 excel 数据源追加或者替换时对于文件名称、sheet 名称都必须校验完全相同，并且替换时不允许有新增字段，这样导致 excel 增加列时必须重新创建数据源，是否可以在进行 excel 替换时，不检验字段名称？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，追加和替换是对数据源的数据进行修改，并不涉及表结构的修改，因此需要校验名称、列数等，并与数据源的表结构保持一致。
