### ISSUE TITLE
[Question]最新版本进入系统后点击任意菜单提示Illegal mix of collations for operation 'UNION'

### ISSUE THREAD

**Issue by 15806122600** [dataease/dataease#1168]
**请描述您的问题.**
### Error querying database. Cause: java.sql.SQLException: Illegal mix of collations for operation 'UNION' ### The error may exist in io/dataease/base/mapper/ext/ExtPanelGroupMapper.xml ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### Cause: java.sql.SQLException: Illegal mix of collations for operation 'UNION'

**Comment by xuwei-fit2cloud** [comment]
这个是编码混用造成的问题，我们后续会完善一下flyway里的编码

**Comment by xuwei-fit2cloud** [comment]
v1.5.1 版本中处理了该问题。
