### ISSUE TITLE
[Feature]希望查询组件可以悬浮或者类似 Excel 首行冻结，在仪表盘的内容比较多时，滑到最下面还可以做筛选

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#11688]
DataEase 版本:
v2.9

**请描述您的需求或者改进建议.**
![image](https://github.com/user-attachments/assets/f3378d07-7ea7-4f04-9a5a-f2b95e53f144)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录进需求池中。

**Comment by yayanpei-fit2cloud** [comment]
短期内没有支持计划。建议使用大屏的弹窗区。
