### ISSUE TITLE
[Feature]希望组件的条件格式支持动态值

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#11695]
DataEase 版本:
v2.9

**请描述您的需求或者改进建议.**
![image](https://github.com/user-attachments/assets/2f6a4685-83df-4496-8bc0-3afa30646100)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中支持一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
