### ISSUE TITLE
[Feature]普通员工可以给自己授管理员权限

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#1169]
**DataEase 版本**
1.4

**浏览器版本**
版本 95.0.4638.69

**Bug 描述**
普通用户角色可给自己授权管理员权限

**Bug 重现步骤(有截图更好)**
1.
![de-1](https://user-images.githubusercontent.com/40846859/141226408-ab99e38f-b142-4257-a664-d5250f76ccf1.png)

2.
![de-2](https://user-images.githubusercontent.com/40846859/141226431-62ad8b6b-54d0-4538-aa2e-3758668e9215.png)

3.
![de-3](https://user-images.githubusercontent.com/40846859/141226446-7fda3fbb-ea6c-440c-b575-6e1fd7cea6a4.png)

**Comment by xuwei-fit2cloud** [comment]
默认“普通用户”角色的 用户 是看不到用户管理菜单的，这个应该是在权限管理里对“普通用户”角色进行了权限修改，授予了更大的权限，所以才造成了您遇到的情况。这个不是bug，应该是管理员已经授权了。

**Comment by xusongtao** [comment]
> 默认“普通用户”角色的 用户 是看不到用户管理菜单的，这个应该是在权限管理里对“普通用户”角色进行了权限修改，授予了更大的权限，所以才造成了您遇到的情况。这个不是bug，应该是管理员已经授权了。

您好，开始的时候给了管理员权限，后来把管理员权限取消了，但是还能进行相应的授权。下面是“权限管理”中普通用户的授权策略
![image](https://user-images.githubusercontent.com/40846859/141228245-724e3be3-c9c1-403c-895f-fe77fb85096d.png)
