### ISSUE TITLE
[Feature] 过滤组件优化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#11696]
DataEase 版本:
v2.9

**请描述您的需求或者改进建议.**
过滤组件筛选框高度、文字大小可进行调整。
在分辨率比较高的屏幕上，当前文字显示非常小，如下所示：
![ee46cb7a518190cd18858f9af8cb003](https://github.com/user-attachments/assets/7c94c602-6944-4887-968f-77400b0d31a3)
是否可以开放高度、文字大小的调整，或者仅开放高度调整，文字大小跟随高度变化。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中支持一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
