### ISSUE TITLE
[Feature]建议优化组织、管理、用户

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#1170]
**请描述您的需求或者改进建议.**
场景：公司内部有A、B、C、D等多个部门，每个部门下面又有多个小组。领导想实现权利下放，让部门的管理者、小组的管理者分别管理内部的事务，但是又不想让下层的用户看到同层或上层的组织架构。
建议：<1>为每个组织设置组织管理员角色、<2>对普通用户所能看到的内容做优化

**Comment by yayanpei** [comment]
感谢反馈，我们内部先讨论下。

**Comment by xuwei-fit2cloud** [comment]
目前的设计上还不支持，需要在后续的2.0版本中实现。
