### ISSUE TITLE
[Feature] 表格组件优化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#11704]
DataEase 版本:
v2.9

**请描述您的需求或者改进建议.**
表格组件当前默认列宽为自适应，列比较少的情况下都是缩在一起，每次均需要手动调整。
可否与 v1 相同，默认铺满整个组件画布？

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下。

**Comment by jackieha** [comment]
同，+1

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
