### ISSUE TITLE
[Feature] 仪表板/数据大屏/数据集/数据源去掉创建人相关信息

### ISSUE THREAD

**Issue by limin-fit2** [dataease/dataease#11715]
DataEase 版本:

V2.9.0

**请描述您的需求或者改进建议.**
    BI和内部业务系统做了平台集成，做项目汇报时候，是直接展示仪表板或数据大屏相关看板数据，在仪表板/数据大屏/数据集/数据源都会展示创建人信息，实际上与汇报人不是同一用户，所以希望是否能加个配置项，是否展示“创建”相关信息记录。
![image](https://github.com/user-attachments/assets/17a73d09-6af0-48d7-8820-bf3e00076fad)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
暂不考虑。
