### ISSUE TITLE
地图联动及样式[Feature]

### ISSUE THREAD

**Issue by magicpose** [dataease/dataease#1171]
1,下钻的同时触发联动
2,地图“样式”-“标签”-“内容格式”中选择{c}时，如果指标是“记录数”，且不存在统计数据的时候地图上显示的是'NaN'，希望能优化一下

**Comment by yayanpei** [comment]
感谢您的反馈，下钻同时触发联动，我们需要讨论下；记录数显示“NaN”的情况，后面版本会优化，还请多加关注。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 已处理，请等待新版本发布
