### ISSUE TITLE
[Bug]数据大屏中富文本的项目符号颜色和大小无法更改

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#11721]
**DataEase 版本**
2.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
edge

**Bug 描述**
数据大屏中，富文本的项目符号颜色默认为白色，当背景色同样是白色时，就看不到项目符号，并且无法修改颜色；同时当调整富文本字体大小时，项目符号大小也不会同步变化，也无法手动更改。（仪表板中项目符号也不可以调整颜色和大小，只不过仪表板中默认是黑色）

**Bug 重现步骤(有截图更好)**
1.创建数据大屏
2.添加富文本选项，编写文本内容
3.给文本内容添加项目符号
<img width="319" alt="5ca4fc2583b1ac8e69971a3867633cd" src="https://github.com/user-attachments/assets/951852e1-0358-4d4e-9d3b-d282cf295a42">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前因为原生组件问题，我们这里暂时没有可以入手去改动的空间，目前只能建议你手动输入达到你想要的效果；
