### ISSUE TITLE
[Question]桑基图是不是有问题，节点只能有两个？

### ISSUE THREAD

**Issue by xuhuigithub** [dataease/dataease#11732]
**桑基图为什么目标维度只能有一个**

正常的桑基图是不是可以有需要中间可以添加其他节点进来
![image](https://github.com/user-attachments/assets/3653db76-7c31-48b3-a13e-90e332bc16df)

**Comment by xuhuigithub** [comment]
目前看在创建图表时只能看到源和目的中间不能添加节点。。
![image](https://github.com/user-attachments/assets/5a18950d-8e00-4464-8e2c-cb831a395e25)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们调研下图库是否支持。

**Comment by xuhuigithub** [comment]
貌似是支持的 是不是哪里没传参进去？https://g2plot.antv.antgroup.com/en/api/plots/sankey#gatsby-focus-wrapper

**Comment by xuhuigithub** [comment]
我提交了一个[PR](https://github.com/dataease/dataease/pull/11790)麻烦看下可以不，在本地试过没太大问题

**Comment by xuhuigithub** [comment]
@yayanpei-fit2cloud @xuwei-fit2cloud

**Comment by xuwei-fit2cloud** [comment]
![图片](https://github.com/user-attachments/assets/37e08367-983d-4281-8b9d-3f63e7bb13b2)
能不能显示多节点，和数据本身有关，并不需要额外添加中间节点字段的。
一个节点，既是源节点，又是另一条记录的目的节点，就可以有上面截图的效果。

**Comment by xuhuigithub** [comment]
您上图的数据可以给一份我吗 我在本地试下 @xuwei-fit2cloud
