### ISSUE TITLE
[Feature]建议增加支持oauth2协议

### ISSUE THREAD

**Issue by jstbw** [dataease/dataease#11745]
DataEase 版本:

v2.9.0
**请描述您的需求或者改进建议.**
当前单点登录不支持常见的oauth2协议，这个还是比较常用的

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经规划在近期的版本中。
