### ISSUE TITLE
[Feature] 仪表板、数据大屏、数据集等排序规则持久化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#11758]
DataEase 版本:
v2.9

**请描述您的需求或者改进建议.**
目前 仪表板、数据大屏、数据集等排序规则是存放在缓存里的，清缓存或者是换浏览器后就丢失了，可否对排序规则进行持久化？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持。
