### ISSUE TITLE
[Bug] v2 移动端日期范围组件查询异常

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#11756]
**DataEase 版本**
v2.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
微信自带浏览器

**Bug 描述**
v2 移动端日期范围组件，只选择前面日期的情况下，会自动带出后面的日期，此时查询报错；再手动选择一次后面的日期，查询正常。

**Bug 重现步骤(有截图更好)**

https://github.com/user-attachments/assets/74adc457-ba62-4628-9d14-7bde1b9edce0

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修改；
