### ISSUE TITLE
[Bug] clickhouse时间格式化异常

### ISSUE THREAD

**Issue by Muxin-007** [dataease/dataease#11763]
**DataEase 版本**
2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 128.0.6613.85

**Bug 描述**
clickhouse查询时间分钟变成月份
原因我发现是formatDateTime格式化中使用%Y-%m-%d %H:%M:%S ，新版clickhouse 会把%M识别成月份
使用%Y-%m-%d %H:%i:%S 新 老版本都正常
我测试的版本是23.3.13.6 和 24.6.2.17

**Bug 重现步骤(有截图更好)**
1.
<img width="2136" alt="Snipaste_2024-08-26_17-38-32" src="https://github.com/user-attachments/assets/66f82d32-e34f-4332-afbb-d141e7a90be7">
2.这是dataease转化的sql
<img width="1188" alt="image" src="https://github.com/user-attachments/assets/ce5dca4b-2f4a-41ed-a83f-4ad298e16ed4">
3.更改后的sql
<img width="1160" alt="image" src="https://github.com/user-attachments/assets/0479c044-2e81-4e9e-8779-9f1d6aabefee">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
