### ISSUE TITLE
[Feature]希望能够增加记忆颜色功能

### ISSUE THREAD

**Issue by xun986** [dataease/dataease#1177]
**请描述您的需求或者改进建议.**<img width="237" alt="image" src="https://user-images.githubusercontent.com/88481290/141272778-8fb1b197-41f0-417c-9789-b4886aad232d.png">有时候在调色板上随便一个个试色看视图效果，但是要记住之前的具体颜色还得一个个记色号，不知后续会不会加入“历史颜色”，能记住最近用过的几个自定义颜色，类似EXCEL这种。

**Comment by yayanpei** [comment]
感谢反馈，您的建议很不错，需求已记录。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
