### ISSUE TITLE
[Bug]2.9.0版本源码本地环境搭建，前端刷新很卡

### ISSUE THREAD

**Issue by jacksonhou** [dataease/dataease#11789]
**DataEase 版本**
2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome

**Bug 描述**
本地源码搭建环境，前端刷新很卡

**Bug 重现步骤(有截图更好)**
1. 本地源码搭建环境
2. 前端刷新，每个页面都加载的好慢
3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前在优化中。

**Comment by jacksonhou** [comment]
太棒了，请问最新版预计什么时候发布

**Comment by xuwei-fit2cloud** [comment]
可以试试v2.10.2版本的代码试试，已经做了较多优化。
v2.10.3版本会再进一步优化。
