### ISSUE TITLE
[Feature]文本类型筛选项支持自定义排序

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#11786]
DataEase 版本:
V2

**请描述您的需求或者改进建议.**
当筛选项字段类型为文本时，支持自定义排序。
![image](https://github.com/user-attachments/assets/1a0dd874-e8a3-41fa-ae81-f79b65cc2ce6)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，需求已记录，但效率上会有较大下降，目前没有较好的办法处理，暂时无计划支持。
