### ISSUE TITLE
[Feature]视图页面能否更改数据集？

### ISSUE THREAD

**Issue by zhanggefei** [dataease/dataease#1179]
**请描述您的需求或者改进建议.**
我想在做好的视图上尝试不同的数据集效果，能否快捷的更改数据集？

**Comment by yayanpei** [comment]
感谢反馈，可以通过下图方式切换数据集：
![image](https://user-images.githubusercontent.com/84168063/141401157-97a0c37a-5e76-4946-adf0-55fac2aa4e9b.png)
