### ISSUE TITLE
[Feature] copilot需要有一个引导/提示，让用户提问更准确，体验感更好

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11801]
DataEase 版本:
v2.9.0

**请描述您的需求或者改进建议.**
目前 copilot 精确度不够高，需要有提问技巧，精细构建问题，很多时间用户都提问回答不上来。

以下是一次对客户的沟通建议：
1、字段有备注的表回答的会比较准确。
2、提问时，尽量指定好返回的类型，比如金额总表，店铺金额对比，用途金额对比，店铺金额占比等，日期金额趋势等，对比->柱状图，占比->饼图，趋势->折线图，表-> 表格
3、提问的字段可用中文命名，如为英文字段时描述需要准确些
4、提问时，问题描述应清晰，如"年份为 2024 时，销售金额的总和"
5、模型会解析用户提问的字段和采用图表类型，分析后转义为 SQL 进而生成图表，可根据这个特点进行提问，如分组、求和、总计、做一个饼图、表格等字眼，能更好地生成图表

但客户也是B端，也有需要对接的用户，这样每次对接一次都得作一次培训/沟通，效率低下。
因此 copilot 需要有一个引导/提示，让用户提问更准确，可在 copilot 页面给用户一个操作技巧/提问方式建议，让用户高效构建自己的问题，体验感更佳。

**Comment by zhainanshidai** [comment]
提示可以通俗易懂，让受众都能看得懂最佳，专业的可另去社区/知识库看贴

**Comment by xuwei-fit2cloud** [comment]
非常感谢您的建议，我们后续会对Copilot功能的使用引导做相关优化。

**Comment by xuwei-fit2cloud** [comment]
目前尝试了一下，由于提示的问题以及生成的对应SQL，与后台的查询是分开的两个步骤，目前还无法保证提示的问题100%能正常获得查询结果，所以暂时还没有上线计划。
