### ISSUE TITLE
[Feature]是否可以默认按照我的excel表进行排序。

### ISSUE THREAD

**Issue by zhanggefei** [dataease/dataease#1180]
**请描述您的需求或者改进建议.**
导入excel数据后，是否可以默认按照我的excel表进行排序。升序、降序都不能满足我的需求。

**Comment by yayanpei** [comment]
感谢反馈，我们需要内部讨论一下。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
