### ISSUE TITLE
[Feature]建议图表文字默认样式不要用纯白色或纯黑色

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#11813]
DataEase 版本:
V2.9

**请描述您的需求或者改进建议.**
建议图表文字默认样式不要用纯白色或纯黑色，无法确定用户是做浅色还是深色，做浅色大屏时，默认颜色看不到无法辨认。
建议统一用灰色或灰蓝色做默认颜色。
![image](https://github.com/user-attachments/assets/0e7d18c9-4811-43a2-a9a4-5f38fab60a73)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，目前暂时没有计划调整。
