### ISSUE TITLE
[Feature] 希望允许查看视图、数据集的对应关系。

### ISSUE THREAD

**Issue by zyy2721** [dataease/dataease#1181]
**请描述您的需求或者改进建议.**
查看视图的时候，如果需要修改数据字段等信息。需要查看该视图对应的数据集。希望能支持该功能。
<img width="483" alt="1" src="https://user-images.githubusercontent.com/71361375/141394158-9574733d-777b-473f-b79b-bff7a777613e.png">

**Comment by yayanpei** [comment]
感谢反馈，您的建议很不错，我们会优先加入版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
在视图名称边上有一个信息图表，点击该图标可以查看视图相关的详细信息，包括数据集和数据源等。
