### ISSUE TITLE
[Bug]导出应用没有包含数据集计算字段

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#11816]
**DataEase 版本**
v2.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
导出应用没有包含数据集计算字段，导致使用应用创建的仪表板，其中使用计算字段的图表无法显示数据

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
