### ISSUE TITLE
[Bug]仪表板中图表过多时，无法修改柱状图的颜色

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#11820]
**DataEase 版本**
2.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
仪表板中图表过多时，无法修改柱状图的颜色
如下如的柱状图，设置好颜色后，保存，预览又恢复了默认颜色。
（可以提供模版复现）
<img width="1664" alt="图片" src="https://github.com/user-attachments/assets/a0b78bec-483a-43a7-ace0-beaa595af3b7">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，请问是批量编辑吗？还是说单个的修改然后全部柱状图颜色都没有变更？

**Comment by mfanoffice** [comment]
> 感谢反馈，请问是批量编辑吗？还是说单个的修改然后全部柱状图颜色都没有变更？

单个图表设置的

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
