### ISSUE TITLE
[Feature]组合图设置渐变颜色希望影响对折线颜色

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#11821]
DataEase 版本:
v2.9

**请描述您的需求或者改进建议.**
组合图设置渐变颜色,柱子颜色发生变化，如果折线渐变，下半部分会颜色变浅，不合理。
<img width="1051" alt="图片" src="https://github.com/user-attachments/assets/d32b7a80-95ab-4591-897a-339c6baf220e">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，已经在 v2.10.lts 版本优化完成，请等待新版本的发布。
