### ISSUE TITLE
[Bug] 导入模版时出错

### ISSUE THREAD

**Issue by liyu44775131** [dataease/dataease#11836]
DataEase 版本
2.9.0

运行方式(安装包运行 or 源码运行 ?)
源码

浏览器版本
chrome

Bug 描述
https://github.com/dataease/dataease/blob/f08399ba32ee2c3937ba7b8947d6985ba4d950c4/core/core-backend/src/main/resources/mybatis/ExtVisualizationTemplateMapper.xml#L143

此处sql代码delete后希望能加上表别名（delete tcm from visualization_template_category_map tcm），否则在mysql8.0+稍低的版本（如：8.0.12）会出现如下错误：
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'tcm WHERE tcm.template_id in ( select id from visualization_template vt where vt' at line 1

**Comment by xuwei-fit2cloud** [comment]
请更新一下代码。
