### ISSUE TITLE
[Bug] 汇总表 取平均值无效 V1.18.22

### ISSUE THREAD

**Issue by WSenOS** [dataease/dataease#11830]
**DataEase 版本**
 V1.18.22

**Bug 描述**
汇总表 取平均值无效

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，方便详细描述一下你的复现步骤吗？
![image](https://github.com/user-attachments/assets/d03f140c-9519-43cb-b069-76b56d238df0)

**Comment by WSenOS** [comment]
发您截图，可以看一下


________________________________
发件人: 9527 ***@***.***>
发送时间: 2024年9月1日 7:36
收件人: dataease/dataease ***@***.***>
抄送: Sen_OS ***@***.***>; Author ***@***.***>
主题: Re: [dataease/dataease] [Bug] 汇总表 取平均值无效 V1.18.22 (Issue #11830)


感谢反馈，目前测试环境没有发现你说的问题，方便详细描述一下你的复现步骤吗？
image.png (view on web)<https://github.com/user-attachments/assets/d03f140c-9519-43cb-b069-76b56d238df0>

―

**Comment by BBchicken-9527** [comment]
你好，请问方便看一下详细的操作步骤我这边复现一下吗？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
