### ISSUE TITLE
[Bug]视图模块，选择南丁格尔玫瑰图，在样式-标签里勾选引导线时，图形当中并显示引导线。

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#1183]
**DataEase 版本**
1.4.0

**浏览器版本**
Microsoft Edge 版本 95.0.1020.44

**Bug 描述**
视图模块，选择南丁格尔玫瑰图，在样式-标签里勾选引导线时，图形当中并显示引导线。

**Bug 重现步骤(有截图更好)**
1.进入视图模块
2.将数据拖拽后，选择南丁格尔玫瑰图
3.切换到样式-标签-勾选引导线
![Uploading e1d62c0a738816116d6e885701bcaaf.png…]()

**Comment by XiaJunjie2020** [comment]
引导线与标签位置有关，需要设置标签位置到外部

**Comment by binbin0406** [comment]
好的，把标签位置调整到外部后，可以了
