### ISSUE TITLE
[Feature]视图模块，选择组合图，进行样式-标签，希望可以分别设置两个图形的标签颜色。

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#1184]
**选择组合图时，两个图的标签数据很容易重叠在一起，当然可以通过调整标签位置进行区分，但如果能分别设置标签颜色会更加容易区分。**
![image](https://user-images.githubusercontent.com/77324661/141402824-58ea0a8c-0318-41c3-a5bd-9599ef21f031.png)

**Comment by binbin0406** [comment]
补充一下，标签位置也应该可以分别设置

**Comment by yayanpei** [comment]
感谢反馈，我们先记录下需求。

**Comment by xuwei-fit2cloud** [comment]
在近期版本中还不会支持，暂时关闭。
