### ISSUE TITLE
[Feature]仪表板模块，添加文本框和图片后，关于位置移动的优化

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#1185]
**1. 文本框希望增加格式刷功能，这样就不用分别设置文本的字体、大小、颜色等
   2. 增加图片和文本框后，希望可以通过键盘来调整上下左右的位置，因为这两个组件跟视图不一样，不会自动占位，需要手动调整，经常出现只差一点的距离，但就是无法对齐。**

**Comment by yayanpei** [comment]
感谢反馈，对不齐的话，建议用矩阵模式，能够实现吸附自动对齐。键盘事件有些冲突还未解决，近期暂不规划支持。

**Comment by binbin0406** [comment]
还有#1184没有回复。

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："yayanpei ***@***.***&gt;;
发送时间：2021年11月12日(星期五) 下午5:41
收件人："dataease/dataease" ***@***.***&gt;;
抄送："张树彬 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [dataease/dataease] [Feature]仪表板模块，添加文本框和图片后，关于位置移动的优化 (Issue #1185)
-----------------------------------

 

 
感谢反馈，对不齐的话，建议用矩阵模式，能够实现吸附自动对齐。键盘事件有些冲突还未解决，近期暂不规划支持。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
