### ISSUE TITLE
[Bug]仪表板模块，文本框在页面边界位置时，编辑器内容显示不全

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#1186]
**1.4.0**

**Microsoft Edge
版本 95.0.1020.44**

**在仪表板中添加文本框，如果文本框在页面的边界位置时，点击文本进行编辑，编辑器的选项就会显示不全，需要挪动文本框位置后才能显示完整，操作起来有点麻烦**

**Bug 重现步骤(有截图更好)**
1.仪板表
2.增加文本框
3.编辑文本框
![image](https://user-images.githubusercontent.com/77324661/141404795-c229525c-34c0-40ed-8230-04988c2c2e4b.png)

**Comment by yayanpei** [comment]
感谢反馈，建议您使用谷歌浏览器，可能 Edge 浏览器适配不太好。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 已修复该问题，请等待新版本发布
