### ISSUE TITLE
[Bug]仪表板模块，增加文本框，文本填充背景色无效

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#1187]
**1.4.0**

**Microsoft Edge
版本 95.0.1020.44**

**在仪表板里增加文本框，文本框编辑器里有背景颜色选项，但是选择颜色后并未填充**

**Bug 重现步骤(有截图更好)**
1.仪表板
2.增加文本框，选择文本框或选择文本
3.选择背景颜色后，都未填充背景颜色
![image](https://user-images.githubusercontent.com/77324661/141406239-f04b1c71-7feb-490c-b5d0-fdcdd8dbcf03.png)

**Comment by yayanpei** [comment]
感谢反馈，不透明度需要设置为100试一下，设置为0的话，是背景完全透明的。
![image](https://user-images.githubusercontent.com/84168063/141444324-a414212f-8e4e-43d6-b71c-c829ec10fd42.png)
