### ISSUE TITLE
[Bug] excel 字段类型识别错误

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#11882]
**DataEase 版本**
2.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 126.0.6478.127

**Bug 描述**
数据源侧数值类型字段，数据集页面拖入后展示为文本

**Bug 重现步骤(有截图更好)**
1.![image](https://github.com/user-attachments/assets/4dbd74d3-52a7-4aaa-8165-1f6e179eb6e7)
2.![image](https://github.com/user-attachments/assets/e0256cdc-09f9-4b97-a7b8-52a5bff376e9)

**Comment by BBchicken-9527** [comment]
感谢反馈，因为excel比较特殊，每个版本中的code数值可能都存在差异，方便可以给我一份你那边的测试数据吗？

**Comment by MaekBlack** [comment]
[区间.xlsx](https://github.com/user-attachments/files/16860075/default.xlsx)

**Comment by BBchicken-9527** [comment]
没问题的；
![image](https://github.com/user-attachments/assets/04c26193-2f2f-473d-bc39-5076242c146d)
