### ISSUE TITLE
[Feature] 过滤组件相关优化

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#11881]
DataEase 版本:
2.9 

**请描述您的需求或者改进建议.**
1. 过滤组件的查询宽度可以单独调整
2. 过滤组件 placeholder 字体设置

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们考虑一下。

**Comment by xuwei-fit2cloud** [comment]
placeholder我们可以支持一下相关设置，但组件的宽度暂时先保持现状。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
