### ISSUE TITLE
[Bug]定时同步数据无法识别到SQL Server数据源的视图

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#11887]
**DataEase 版本**
v2.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
xpack中的定时同步，源数据源SQL Server 2012 ，目标数据源Doris，数据表下拉选项没有视图，希望支持上。
![图片](https://github.com/user-attachments/assets/f4a1fb85-790a-4be2-8a9e-2ff98e57ad94)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，方便问一下你的sqlserver的版本吗？
![image](https://github.com/user-attachments/assets/bb8ab28a-2e06-477e-a4f7-84d4c2db582e)

**Comment by mfanoffice** [comment]
> 感谢反馈，目前测试环境没有发现你说的问题，方便问一下你的sqlserver的版本吗？ ![image](https://private-user-images.githubusercontent.com/84372766/363473691-bb8ab28a-2e06-477e-a4f7-84d4c2db582e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTM5MzIsIm5iZiI6MTcyNTM1MzYzMiwicGF0aCI6Ii84NDM3Mjc2Ni8zNjM0NzM2OTEtYmI4YWIyOGEtMmUwNi00NzdlLWE0ZjctODRkNGMyZGI1ODJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA4NTM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NmI4NThkMTM0YzUxYTkzZjg1ZjA0MzRlZDQyNWQ5NDhmZGRlZTRiYmZmMjFiZWI2Y2RkZmZlMDAxZDBlOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sbGifg-sPeVU79jwPaMY2226bh_mt7ixmo3soKGXnhU)

SQLServer 版本 2012

**Comment by mfanoffice** [comment]
> 感谢反馈，目前测试环境没有发现你说的问题，方便问一下你的sqlserver的版本吗？ ![image](https://private-user-images.githubusercontent.com/84372766/363473691-bb8ab28a-2e06-477e-a4f7-84d4c2db582e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNTM5MzIsIm5iZiI6MTcyNTM1MzYzMiwicGF0aCI6Ii84NDM3Mjc2Ni8zNjM0NzM2OTEtYmI4YWIyOGEtMmUwNi00NzdlLWE0ZjctODRkNGMyZGI1ODJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA4NTM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NmI4NThkMTM0YzUxYTkzZjg1ZjA0MzRlZDQyNWQ5NDhmZGRlZTRiYmZmMjFiZWI2Y2RkZmZlMDAxZDBlOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sbGifg-sPeVU79jwPaMY2226bh_mt7ixmo3soKGXnhU)

SQLServer 2017 版本，刚刚试过，定时同步任务选择图表，确实没有拉出视图表

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
