### ISSUE TITLE
[Bug]视图模块，选择图形后，进入样式-颜色，自定义颜色无效

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#1188]
**1.4.0**

**Microsoft Edge
版本 95.0.1020.44**

**在视图里，选择任意图形后，进行样式菜单设置颜色，选择自定义颜色无效**

**Bug 重现步骤(有截图更好)**
1.视图
2.样式
3.颜色-自定义
![image](https://user-images.githubusercontent.com/77324661/141407099-409c971d-9ea1-4e93-9b55-5285d224fdb3.png)

**Comment by yayanpei** [comment]
感谢反馈，柱形图的颜色选择的是配色方案的第一个颜色，自定义第一个色块
![image](https://user-images.githubusercontent.com/84168063/141443831-c7bbdd56-e5c9-4f20-99fb-44eaf94ab848.png)
