### ISSUE TITLE
[Bug]企业版到期后，导入应用，点击保存时，无论右侧输入信息如何修改，一直提示分组重复。

### ISSUE THREAD

**Issue by huangxine** [dataease/dataease#11890]
**DataEase 版本**v2.9

**运行方式(安装包运行 or 源码运行 ?)**
标准安装

**浏览器版本**
chrome

**Bug 描述**
企业版到期后，导入应用，点击保存时，无论右侧输入信息如何修改，一直提示分组重复。

**Bug 重现步骤(有截图更好)**
1.做好的仪表板导出为应用
2.在模板里上传应用
3.新增仪表板使用该应用
4、在应用配置那里里点击保存，一直提示分组重复
5、重新导入lic文件，然后在导入应用，能正常保存
![image](https://github.com/user-attachments/assets/1201049e-e931-492b-89bd-805fd167590c)

**Comment by BBchicken-9527** [comment]
感谢反馈，应该是到期后因为资源合并之前其他组织中存在相同的命名导致，所以重新上传可以正常创建
