### ISSUE TITLE
[Feature]气泡地图的地图区域需要增加颜色设置，丰富图表的制作

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11900]
DataEase 版本:
v2.9.0

**请描述您的需求或者改进建议.**
气泡地图的地图区域需要增加颜色设置，丰富图表的制作。能够整体填充地图区域（如省份）部分的颜色。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们增加一下配置项。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
