### ISSUE TITLE
[Bug]新搭建的dataEase连不了clickhouse数据库

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11904]
**DataEase 版本**
DataEase v2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
google

**Bug 描述**
以前社区也有人有类似问题：新增chickhouse数据源时报错问题 https://bbs.fit2cloud.com/t/topic/6069。社区有人 V2.6.1 可以连接，在 V2.7.1 报这个错误
用户在 V1 的版本正常连接的版本是 v1.12.0，配置没问题，在 V1 的时候可以连接，在 v2.9.0 连接出错

配置经检查，没问题，在 v1 是正常使用的
![08a0b0d4561e5dac01d060d0cc72e0a](https://github.com/user-attachments/assets/cf0cbd69-9a3f-41eb-a982-06626327090e)

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #11351
