### ISSUE TITLE
[Feature] 钉钉内打开公共链接，title 显示优化问题

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#11903]
DataEase 版本:
v2.9

**请描述您的需求或者改进建议.**
在钉钉里打开 dataease 公共链接，标题显示的是系统设置-外观设置里的网页名称，查了下资料，钉钉的导航栏标题是需要单独进行设置，链接如下所示，可否在后续的版本里进行优化：https://open.dingtalk.com/document/orgapp/set-the-navigation-bar-title
![b0f8208557c2e65affb500aac89fae3](https://github.com/user-attachments/assets/9a9901fa-18df-4e40-b7b9-f22726cc04bd)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们在近期的版本中优化一下。
