### ISSUE TITLE
[Feature]仪表板模块，在仪表板中编辑视图，希望可以在当前页面直接进行编辑，不用再跳转到视图。

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#1191]
**因为把所有的视图都放到仪表板里面后，包括图形、颜色、字体颜色等，都要从仪表板的整体上去设计，所以在样式上的改动会非常多，每个视图样式调整后都要对比一下是否跟整体仪表板匹配，往往在一个视图上的改动就要很多次。每次都要跳转到视图页面上进行编辑，操作体验上感觉有点麻烦。**

**Comment by yayanpei** [comment]
感谢反馈，目前确实存在这个情况，与系统的设计架构有关，近期应该不会改动。
