### ISSUE TITLE
[Feature]仪表板中，希望增加对视图批量编辑的相关设置

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#1192]
**希望仪表板中增加，可以同时选中多个视图，批量编辑标题字号大小、颜色、视图背景颜色等元素。以及可以批量自定义设置视图大小，可以以输入数值的方式呈现**

**Comment by yayanpei** [comment]
感谢反馈，这块的优化我们也在讨论方案，能够实现统一设置标题，图例等，还请多加关注。

**Comment by xuwei-fit2cloud** [comment]
该需求还需要几个版本后才能排期，暂时先关闭
