### ISSUE TITLE
[Bug]系统管理-权限管理，所有权限列表的表头应该固定

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#1193]
**系统管理-权限管理，所有权限列表的表头应该固定，否则当数据多时，下拉后就看不到下面几个选项的名称了**
![image](https://user-images.githubusercontent.com/77324661/141426438-52ccf6d3-bd3a-4d22-8c6e-b7b2aa44ea48.png)

**Comment by yayanpei** [comment]
感谢反馈，您的建议非常好，我们会加入后面的版本进行优化，请多加关注。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 版本已支持，等待新版本发布
