### ISSUE TITLE
[Feature]希望数据大屏添加参考线功能，方便对齐

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#11936]
DataEase 版本:
V2.9

**请描述您的需求或者改进建议.**
希望数据大屏添加参考线功能，方便对齐
![image](https://github.com/user-attachments/assets/316ee0b9-e6a6-43ec-a43f-3025fffa4bea)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，点击选中组件，会显示该组件的起始位置。
![image](https://github.com/user-attachments/assets/9c660667-c7bc-4a75-a729-07eb42f9745d)

**Comment by zhangtong9898** [comment]
当需要多个组件进行排列对齐时，每一个都去看一下组件的起始位置，计算所需间隔，没有吸附功能就只能挪动鼠标慢慢对齐坐标是否太影响工作效率

**Comment by zhangtong9898** [comment]
当需要多个组件进行排列对齐时，每一个都去看一下组件的起始位置，计算所需间隔，没有吸附功能就只能挪动鼠标慢慢对齐坐标是否太影响工作效率
