### ISSUE TITLE
[Bug]【图表】地图的全球地图没有新加坡

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#11938]
**DataEase 版本**
v2.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
1.目前全球地图没有新加坡；
<img width="945" alt="0bad218d62ebec4c8398616166d21db" src="https://github.com/user-attachments/assets/3a1eb53e-f94a-4d97-bc94-f77a317aef15">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行优化；

**Comment by xuwei-fit2cloud** [comment]
请升级版本。
