### ISSUE TITLE
[Feature]建议对Excel数据集中的文本类型，支持trim

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#1194]
**请描述您的需求或者改进建议.**
建议对Excel数据集中的文本类型，支持trim操作，这样即使是有空格（人眼很难察觉，尤其是数据量大的时候），也可以自动处理，提高效率，否则依靠人工纠正，太费事费力了。

**Comment by yayanpei** [comment]
感谢反馈，目前不支持对excel数据集的数据进行编辑，可通过新建计算来实现，如下：
![image](https://user-images.githubusercontent.com/84168063/141714460-c659f9d2-17b4-4100-add4-806a123e9517.png)
