### ISSUE TITLE
[Feature]【仪表板】仪表板中的指标卡添加可以设置固定长宽的样式

### ISSUE THREAD

**Issue by daiqingyao6238** [dataease/dataease#11968]
DataEase 版本:
2.9.0

**请描述您的需求或者改进建议.**

需求：
设置5个指标卡的宽度一致，铺满一列，目前没找到特别好的方法。

建议：
仪表板中的指标卡添加可以设置固定长宽的样式。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，仪表板是自适应模式，目前没有计划支持设置组件的固定长宽，如果需要设置固定长宽，建议使用数据大屏。
