### ISSUE TITLE
[Feature]建议对仪表板中视图的放大、缩小进行参数化控制（关闭或开启）

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#1197]
**请描述您的需求或者改进建议.**
建议对仪表板中视图的放大、缩小进行参数化控制（关闭或开启），尤其是演示的时候，很容易出现放大的情况而导致视图不好看。

**Comment by yayanpei** [comment]
感谢反馈，我们记录一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.3版本对此已做优化，只有选中对应的视图后，缩放操作才会生效。
