### ISSUE TITLE
[Feature]doris2.0+ 语法 有些sql解析器不支持，如列转行，这个后续是否有计划支持呢

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#11989]
DataEase 版本:
v1.18.23

**请描述您的需求或者改进建议.**
doris2.0+ 语法 有些sql解析器不支持，如列转行，这个后续是否有计划支持呢？

<img width="1223" alt="874f2980-6d67-4a5c-b0ce-8595c77ce589" src="https://github.com/user-attachments/assets/18aa5dbe-9e28-4ade-bd80-93e6317cb409">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，1.x版本没有计划支持。
