### ISSUE TITLE
[Feature] 权限体系能够导出，包括行列权限和用户权限

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#11990]
DataEase 版本:
2.9

**请描述您的需求或者改进建议.**
合规审计要检查系统权限，希望权限体系能够导出，包括行列权限和用户权限

**Comment by xuwei-fit2cloud** [comment]
不是太清楚具体的需求细节，还请详细说明。
是导出表数据，还是导出可视化结果，以及其他一些需求细节。

**Comment by MaekBlack** [comment]
导出成 excel 表，导出前可以勾选待导出的内容

**Comment by xuwei-fit2cloud** [comment]
暂无计划支持。
