### ISSUE TITLE
[Bug] 富文本框插入链接，选择当前窗口打开，然后是在新窗口打开网页链接

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [dataease/dataease#11998]
**DataEase 版本**
2.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器 114

**Bug 描述**
富文本框插入 URL 链接，设置为当前窗口打开，结果还是在新窗口打开网页链接。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/user-attachments/assets/3fa3c4bb-843d-4841-8560-e1bb1b83e8c6)
点击之后，还是新开标签页的方式打开 网页链接
![image](https://github.com/user-attachments/assets/f6800bf1-de2f-43b0-85ad-ed1751506e2f)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行优化；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
