### ISSUE TITLE
[Feature]数字下拉组件优化

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#1199]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/46042812/141722329-1a4838a9-6e47-465c-b112-cce5e7d5c9ce.png)
![image](https://user-images.githubusercontent.com/46042812/141722366-aa6035d0-5d11-4c45-9627-936755d9e7c1.png)

显示器分辨率不同，显示效果看上去不一样，而且多选时「+1」的显示，不好理解

**Comment by yayanpei** [comment]
感谢反馈，显示效果差异的情况，建议根据最终显示设备的分辨率去调整。"+1"，提示用户有一个过滤值，不好理解的情况，我们先记录，后面优化一下体验，还请多加关注。

**Comment by xuwei-fit2cloud** [comment]
暂时还没有比较好的处理方案
