### ISSUE TITLE
数据量大的情况下，加载图表加载不出来（3万多条数据）

### ISSUE THREAD

**Issue by plateauandsp** [dataease/dataease#12]
数据量大的情况下，加载图表加载不出来，预览可以（3万多条数据）
![image](https://user-images.githubusercontent.com/30932762/123370661-c58a4400-d5b2-11eb-9344-ed92d0b2fccb.png)
![image](https://user-images.githubusercontent.com/30932762/123370663-c6bb7100-d5b2-11eb-96f6-dbb4e1527bb6.png)
![image](https://user-images.githubusercontent.com/30932762/123370669-c91dcb00-d5b2-11eb-81c0-07bca81d30f7.png)

**Comment by xuwei-fit2cloud** [comment]
已做优化，请等待下一个版本 v1.0.1

**Comment by xuwei-fit2cloud** [comment]
v1.0.1 版本已发布
