### ISSUE TITLE
[Feature] 定时报告设置查询组件参数，添加配置项，能够对被选中的图表数据生效

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#12008]
DataEase 版本:
2.9

**请描述您的需求或者改进建议.**
定时报告设置查询组件参数，添加配置项，能够对被选中的图表数据生效

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持，如果不需要对一些图表生效，建议查询组件不要绑定这些图表；如果需要对一些图表生效，建议查询组件绑定图表。
