### ISSUE TITLE
[Bug]屏幕分辨不同时，布局差异大

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#1200]
**DataEase 版本**
1.14.1

**浏览器版本**
chrome  95.0.4638.69

**Bug 描述**

**Bug 重现步骤(有截图更好)**
Mac上仪表板设计：
![image](https://user-images.githubusercontent.com/46042812/141730770-029d293f-382d-4dd1-a74a-8b458b791139.png)
大屏显示器上显示：
![image](https://user-images.githubusercontent.com/46042812/141730866-5244f37d-ea17-444c-bcea-5b78d77dfa75.png)

Mac上仪表板设计（仪表板设计中视图都是两边靠齐的）：
![image](https://user-images.githubusercontent.com/46042812/141731051-f9a499b2-442d-4da7-951f-78675b11054d.png)
大屏显示器上显示（两边间隙不一样，左窄右宽）：：
![image](https://user-images.githubusercontent.com/46042812/141731206-fe5df902-7814-40a7-9036-86b801cf9fc7.png)

**Comment by yayanpei** [comment]
感谢反馈，如果设备分辨率差异大，建议根据最终展示的设备去调整适应。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 版本对不同分辨率做了一定的适配，视图及组件会随分辨率的改变而相应的进行缩放
