### ISSUE TITLE
[Bug]饼状图标签引导线配置无效

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#1201]
**DataEase 版本**
1.14.1

**浏览器版本**
chrome 95.0.4638.69

**Bug 描述**
当标签位置为上、下、左、右时，标签引导线配置无效

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/46042812/141732541-b8ab64e4-9087-4737-af17-a266f6ca6f4b.png)

**Comment by yayanpei** [comment]
感谢反馈，把标签位置调整为“外”就可以了。
