### ISSUE TITLE
[Feature]PostgreSQL能否支持展示分区前的表

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#12016]
DataEase 版本:
V2

**请描述您的需求或者改进建议.**
目前我们数据表可以拿到分区后的表(device_rawdataa_sec_y24p01、device_rawdataa_sec_y24p02)，没有分区前的表，能否支持拿到分区前的表（device_rawdataa_sec）
![image](https://github.com/user-attachments/assets/d558a89c-9ff6-4dd7-bc5a-315e5e853f25)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。
