### ISSUE TITLE
[Feature]系统设置主题切换逻辑有点乱

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#1203]
**请描述您的需求或者改进建议.**
目前的逻辑是需要先点击「编辑」按钮——>切换主题——>保存，对于大多数人来说，编辑的理解是对当前主题的颜色进行配置，没有联想到这个「编辑」还和切换主题有关联，建议可以直接点击主题进行切换

![Uploading image.png…]()

**Comment by yayanpei** [comment]
感谢反馈，您的建议很不错，我们会优先考虑的。

**Comment by xuwei-fit2cloud** [comment]
v1.7.0 版本已支持
