### ISSUE TITLE
[Bug]模板市场中的模板使用时报错“解析错误”

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#12039]
**DataEase 版本**
2.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome、Firefox

**Bug 描述**
下面两个模板，直接在模板市场点“应用”，报错解析错误，但在网页版模板市场中 https://templates-de.fit2cloud.com/ 下载模板，然后导入DE中，模板可正常使用。
![图片](https://github.com/user-attachments/assets/e50edcec-6cb2-41d8-9f9c-20df2bd0a762)
![图片](https://github.com/user-attachments/assets/fab3e3f3-5c3f-4a0e-88c8-a63c7407c03d)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
