### ISSUE TITLE
[Feature] 组件上下间距不能调，有很大的空白，建议新增调整上下间距功能

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#12045]
DataEase 版本:
v2.9

**请描述您的需求或者改进建议.**
组件上下间距不能调，有很大的空白，建议新增调整上下间距功能
![image](https://github.com/user-attachments/assets/6a656e9c-74b9-4fa3-9ba8-b96baf0413fc)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划调整。
