### ISSUE TITLE
[Feature] sheet 页为空不能导入

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#12046]
DataEase 版本:
v2.9

**请描述您的需求或者改进建议.**

excel  sheet 页为空不能导入，v1的版本sheet也为空导入不会报错，建议v2可以优化一下，导入excel不是很友好

![image](https://github.com/user-attachments/assets/5ab5bedc-45b3-4e60-abc5-db3ef965440b)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，系统是以第一行作为表头，在数据库中创建表的，而数据库是不支持建空表的，如果不需要空的sheet页，建议删掉后再上传。
