### ISSUE TITLE
[Feature] 视图提示功能触发不灵敏

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#12044]
DataEase 版本:
v2.9

**请描述您的需求或者改进建议.**

如下图：（1）这个点如果太小，触发特别不灵敏有时会触发不到；（2）还有这个占比和边线太近，有点紧凑；

![285622e22cb9e0eb76d2339f8901c44](https://github.com/user-attachments/assets/40488698-99e4-4544-ace5-a21f6bc215e0)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，这是一个已知优化项，我们已规划在近期的版本中进行优化。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
