### ISSUE TITLE
[Bug]富文本框的内容使用超链接，链接打开位置选择当前窗口，但是点击还是会新开一个窗口

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#12043]
**DataEase 版本**
v2.10.0

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
![image](https://github.com/user-attachments/assets/e94a0c20-9a56-4d85-954b-4a6b075c22ac)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，这是一个已知bug，我们计划在近期的版本中进行修复。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
