### ISSUE TITLE
[Feature]模板市场想要支持批量导入导出，适配只能离线使用的环境

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12052]
DataEase 版本:
v2.9.0

**请描述您的需求或者改进建议.**
https://templates.dataease.cn/?de-version=V2 模板市场想要支持批量导出，适配离线使用的环境，有些客户可能不能在线使用，那模板市场部分不能用了，能否增加批量导入导出，然后让工作台对应位置可以展示离线模板

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，建议您修改url，搭建内网环境。
