### ISSUE TITLE
[Feature]V2 跳转到公共链接也有返回按钮

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#12054]
DataEase 版本:
v2.10.0

**请描述您的需求或者改进建议.**
![image](https://github.com/user-attachments/assets/24087314-dcd8-4865-8ed2-59398874d54e)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持，建议点击浏览器的返回按钮进行返回。
