### ISSUE TITLE
[Feature]外部参数传参关联筛选项后，筛选项不能再被修改。

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#12056]
DataEase 版本:
v2.10.0

**请描述您的需求或者改进建议.**
![5517236cd11336c737034182856bca4](https://github.com/user-attachments/assets/d3871875-a7d2-4194-8df6-081c85b01ba9)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前设计上外部参数是要在当前页面生效的，因此不能修改，暂时没有计划调整此处的逻辑。
