### ISSUE TITLE
[Feature]当设置表格条件样式后，背景色跟随当前背景颜色，不要默认为透明，还有如果设置了斑马纹，这里的背景色也要跟随本来的背景色

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#12055]
DataEase 版本:
2.9

**请描述您的需求或者改进建议.**
![2e2ee103138f75a7a4b4f0e5528ea93](https://github.com/user-attachments/assets/23e8827a-65b3-4518-baf0-d4972b43990f)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中优化一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
