### ISSUE TITLE
[Bug]创建数据源时信息写错校验会一直白屏

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#12068]
**DataEase 版本**
v2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome\firefox

**Bug 描述**
创建数据源，信息写错了，点击校验，报错消失后，页面一是白屏转圈。
![图片](https://github.com/user-attachments/assets/a3b6a423-fbae-4384-9cdd-cc756381b7b4)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，我们正在努力修复，将会在下个版本进行修复；
