### ISSUE TITLE
[Feature] 联动后设置跳转，源字段能否携带联动字段进行过滤

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#12062]
DataEase 版本:
2.10版本

**请描述您的需求或者改进建议.**
效果是希望地图显示的是行政区划的价格，柱状图显示的是星级分类的价格，然后地图跟柱状图做了联动，联动后的柱状图做跳转，要显示行政区划和星级分类筛选后的价格
目前是跳转设置源字段选不到行政区划（城市），跳转后依旧是全部明细
![chrome_8dIJKBsBRY](https://github.com/user-attachments/assets/da45f34b-6f03-448a-ab9f-0cb599285e3f)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划调整。
