### ISSUE TITLE
[Question]dataease 前端页面很卡，需要大概20秒才能显示一个页面

### ISSUE THREAD

**Issue by SwallowData** [dataease/dataease#12064]
**请描述您的问题.**
阿里云实例，2核4G
用1panel 安装的dataeasse

**Comment by SwallowData** [comment]
文件也是上传不了
![image](https://github.com/user-attachments/assets/dee384e4-8a1f-493e-8132-28f8b4896eeb)

**Comment by xuwei-fit2cloud** [comment]
我们已做了相关优化，请升级版本到2.10.2试试。
