### ISSUE TITLE
[Feature]优化表格类图表表头排序显示区域，现在最后一列的排序方式会被遮挡

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#12063]
DataEase 版本:
V2

**请描述您的需求或者改进建议.**
优化表格类图表表头排序显示区域，现在最后一列的排序方式会被遮挡
![image](https://github.com/user-attachments/assets/b3d36af2-7443-4157-b2c1-1823c423d2f2)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经加入近期的版本的迭代中。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
