### ISSUE TITLE
[Question]ClickHouse 版本 驱动不支持，需要升级Clickhouse驱动版本，该如何处理

### ISSUE THREAD

**Issue by zmyer** [dataease/dataease#12072]
**请描述您的问题.**
版本：1.18.23
ClickHouse：24.3.2
![image](https://github.com/user-attachments/assets/d5d3c41d-2d13-4d90-a4ab-c4bdaf6e8b83)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，可以参考下图所示，在驱动页面增加一下该版本的驱动。
![image](https://github.com/user-attachments/assets/79deeb26-6e97-49ba-a3ef-5aee662d0ecc)
