### ISSUE TITLE
[Feature] 对象名称取消最低 2 个字符的限制，至少对于汉字，取消 2 个字符的限制

### ISSUE THREAD

**Issue by ycyuxin** [dataease/dataease#12077]
DataEase 版本: 社区版 2.10.0

在创建目录等对象时，有时候希望使用一个汉字，但系统提示 "2-64字符"。

个人以为，对于小项目，单个汉字、甚至单个字符都可能是很好的选择，因此建议取消最低 2 个字符的限制。

谢谢。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。
