### ISSUE TITLE
[Bug]视图开启最值关联时间组件，通过时间过滤数据为空时，依然显示最值。

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#12074]
**DataEase 版本**
2.10

**运行方式(安装包运行 or 源码运行 ?)**
离线安装

**浏览器版本**
最新版

**Bug 描述**
视图开启最值关联时间组件，通过时间过滤数据为空时，依然显示最值。
![image](https://github.com/user-attachments/assets/b82b2667-ee92-408b-b7ee-22e3af53b4bb)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
