### ISSUE TITLE
[Bug]透视表使用导出带格式的 Excel，数据为 0 的导出空

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#12088]
**DataEase 版本**
2.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌最新

**Bug 描述**
透视表使用导出带格式的 Excel，数据为 0 的导出空

**Bug 重现步骤(有截图更好)**
1.使用明细表制作的视图，数据中有字段内容为0，选择导出Excel（带格式）
![image](https://github.com/user-attachments/assets/e841f3d0-216e-4e14-8359-4a965822cbab)

2.查看导出的表格内容为空
![image](https://github.com/user-attachments/assets/c4b3b3f5-2042-4035-8cf8-353b7100ef14)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
