### ISSUE TITLE
[Feature]V2.10.0仪表盘-明细表建议新增自动换行

### ISSUE THREAD

**Issue by stillflood** [dataease/dataease#12084]
DataEase 版本:
2.10.0

**请描述您的需求或者改进建议.**
1、仪表盘添加明细表，列宽调整为固定列宽或者是自定义；
2、当某个单元格的文字超过长度时，不能自动换行，导致阅读困难；
<img width="147" alt="iShot_2024-09-09_10 38 07" src="https://github.com/user-attachments/assets/8aca9fff-edb2-470d-b7ad-53b8f7877f42">

3、鼠标放上去悬停可以显示，但是鼠标悬停区域有限，阅读困难。
<img width="569" alt="iShot_2024-09-09_10 38 27" src="https://github.com/user-attachments/assets/40ced2d0-c789-416a-ae06-94942066e918">

4、仪表盘添加明细表，列宽调整为自适应，文字很长的列就会拉的很长，阅读困难。
<img width="1548" alt="iShot_2024-09-09_10 39 34" src="https://github.com/user-attachments/assets/9fc7c7fb-4100-43eb-b1f8-9b3f78787cb8">

建议考虑单元格内如果文字过长如何增强易读性的功能优化

**Comment by xuwei-fit2cloud** [comment]
自动换行在技术上可以支持，但我们并不推荐在表格里存放过长的内容，内容过长的话，并不太适合在仪表板或者大屏上进行展示。

**Comment by stillflood** [comment]
> 自动换行在技术上可以支持，但我们并不推荐在表格里存放过长的内容，内容过长的话，并不太适合在仪表板或者大屏上进行展示。

如果列很多的话，超过5-8个字就会隐藏了，这个内容也不算长吧，能考虑优化吗？

**Comment by xuwei-fit2cloud** [comment]
可以的

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
