### ISSUE TITLE
[Bug]透视表没有数据列维度的时候，总计的聚合计算使用自定义，结果显示为“NaN”

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#12081]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
![image](https://github.com/user-attachments/assets/8e24cbe5-911d-45da-ae4a-774eac83970e)
![image](https://github.com/user-attachments/assets/16323c0a-39a5-421f-9b10-7d8f6b242067)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
