### ISSUE TITLE
[Bug]V2.10版本的查询组件字体模糊不清

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#12098]
**DataEase 版本**
V2.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌浏览器最新

**Bug 描述**
V2.10版本的查询组件字体模糊不清

**Bug 重现步骤(有截图更好)**
1.添加查询组件
![image](https://github.com/user-attachments/assets/075b58b5-3dc0-42ae-8e71-12fa11ce3d41)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行优化；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
