### ISSUE TITLE
[Feature]大数据查询-数据集预览界面数据返回太慢

### ISSUE THREAD

**Issue by 2023fan** [dataease/dataease#12099]
DataEase 版本:
V2.10

**请描述您的需求或者改进建议.**
问题：大数据查询-数据集预览界面数据返回太慢

原因：数据预览界面需要通过一条count的语句去计算有多少行数据，主要是这条SQL比较耗时

改进建议：把这个求总数的SQL单独分开弄一个请求

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中优化一下。
