### ISSUE TITLE
[Bug]最新版本chrome浏览器中Failed to initialize WebGL

### ISSUE THREAD

**Issue by xiaokai0** [dataease/dataease#12097]
**DataEase 版本**
2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 版本 128.0.6613.120（最新版本）

**Bug 描述**
在chrome中Failed to initialize WebGL，导致地图加载失败
在safari和Microsoft Edge浏览器中没有问题正常运行

**Bug 重现步骤(有截图更好)**
1.![5](https://github.com/user-attachments/assets/823568f3-db08-4933-bfa6-50e0fd84277f)【chrome浏览器】
2.
![4](https://github.com/user-attachments/assets/1739e550-8833-4d12-ba91-aefdc3f63965)
![6](https://github.com/user-attachments/assets/5d8168c5-cf2b-445c-b590-f9f08e45d637) 【safari 和 Microsoft Edge浏览器】

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，请问你使用的是什么系统？
![image](https://github.com/user-attachments/assets/0baa4d49-7b82-4835-971b-d64c04fd3347)

**Comment by xiaokai0** [comment]
我用的mac，我的浏览器和mac系统都是最新的，我同事的也都是最新的，他那里好使，我这报错，真是奇了怪了

**Comment by BBchicken-9527** [comment]
请问你的问题必定出现吗？清除缓存看看呢？

**Comment by xiaokai0** [comment]
必定出现，清了几次缓存了，在我两个同事电脑都好使，就我这不好使，我不知道是那块有可能影响到这，如果确实没法定位到问题，就先关了吧

**Comment by xiaokai0** [comment]
![1](https://github.com/user-attachments/assets/07d8d55f-9119-428c-9ba4-1bb62518e987)
chrome浏览器 需要把这个配置打开，不打开的话，就会报那个错误

**Comment by BBchicken-9527** [comment]
![image](https://github.com/user-attachments/assets/c31ade53-0eee-45a9-a64f-457fadf0005a)
emm...我这边吧他关了还是没问题的，如果你那边是因为浏览器配置导致问题那我这边想将问题关闭了；

**Comment by xiaokai0** [comment]
好
