### ISSUE TITLE
[Question]升级1.18.23后富文本的工具栏不出来。

### ISSUE THREAD

**Issue by hbnight** [dataease/dataease#12094]
**请描述您的问题.**
离线安装完1.18.23后富文本的工具栏出不来，其他功能目前看是正常的。排查后发现找不到以下三个样式文件，是否跟这个有关？需要怎么处理？
tinymce/skins/ui/oxide/content.inline.min.css
tinymce/skins/content/default/content.css
tinymce/skins/ui/oxide/skin.min.css

**Comment by ziyujiahao** [comment]
对应的文件在代码的这个位
![WX20240909-171828@2x](https://github.com/user-attachments/assets/d555ee69-b1a1-475a-96d7-6bf65595a8bc)
如何是二开的话可以检查一下对应位置是否存在 如果是官方安装包 建议升级一下清理一下缓存试试

**Comment by hbnight** [comment]
升级1.8.24后正常
