### ISSUE TITLE
[Feature]数据大屏图表的提示内容，希望增加维度字段

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#12105]
DataEase 版本:
V2.10.0

**请描述您的需求或者改进建议.**
数据大屏图表的提示内容，希望增加维度字段，目前只支持提示指标字段
<img width="913" alt="e3900b86e70fd6c50ef34e4213b115e" src="https://github.com/user-attachments/assets/de8b57f4-e21b-4b93-b5ee-bcd4d8ef09b2">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，用于图表制作的维度可以在提示中展示，其他的维度字段无法展示，因此目前暂时实现不了。
