### ISSUE TITLE
[Bug] 手机端访问仪表板提示在视图下方

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#12102]
**DataEase 版本**
2.10

**运行方式(安装包运行 or 源码运行 ?)**
离线

**浏览器版本**
最新版

**Bug 描述**
手机端访问仪表板提示在视图的下方，使用Mate30访问正常

**Bug 重现步骤(有截图更好)**
1、手机端访问：苹果14 
![a28237647e1563dca07bd0a0d6a60e3](https://github.com/user-attachments/assets/4d541148-3e27-4d74-8bc8-8aa5b39d86fe)
2、Mate30访问正常
![0608d95ec4e7176fbec3337c2cb0bd5](https://github.com/user-attachments/assets/f4bf9dbd-ca75-498b-85c0-f9295bddc9f3)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，我这边用的是苹果15，请问清除缓存后是否依然存在这个问题呢？
![image](https://github.com/user-attachments/assets/6ebaedcd-1330-49f2-8622-fed2a5d9e1a5)

**Comment by LinuxLeader** [comment]
苹果15没有问题，苹果14和14pro都有问题，下面这个是14pro访问的
![4ac2fcdb69d532e722274444b614255](https://github.com/user-attachments/assets/6a3c0c99-f53c-4fec-88ed-71d73a95ae2a)

**Comment by BBchicken-9527** [comment]
感谢反馈，14我们也是看了的，也是没有问题的；
![image](https://github.com/user-attachments/assets/ee627a3d-6888-45c3-9bde-b51d14a203d6)

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
