### ISSUE TITLE
[Bug]SQL Server 2008 数据源校验时提示“Connection reset”

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#12103]
**DataEase 版本**
v2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
在DataEase 服务器以及容器里都可以访问数据库的端口，网络是通的。
SQL Server 2008的版本
![d0cfa2499b22b018c744acbfd9d7ed1](https://github.com/user-attachments/assets/08bd7e6d-9081-4f1c-8113-add993c0a3df)
报错页面及日志
![image](https://github.com/user-attachments/assets/14e6794a-dc6c-4d38-b5a4-d455f5ac54ff)
![8578fad2a798a5ab0befabac8046d54](https://github.com/user-attachments/assets/4e539e94-9dfe-4a09-b8c5-a1d61b0acac0)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，看日志不是说是登录失败导致的吗；

**Comment by shimengqiao** [comment]
是最下面的那条日志，上面那个是没有输入密码
