### ISSUE TITLE
[Feature]饼状图图例超过一行后，切换下一行的按钮过大且无法调整大小。

### ISSUE THREAD

**Issue by zhenzhendong** [dataease/dataease#12114]
DataEase 版本:

**请描述您的需求或者改进建议.**
饼状图图例超过一行后，切换下一行的按钮过大且无法调整大小。
![image](https://github.com/user-attachments/assets/94fa9aed-c629-4b6b-a118-d4b692a79371)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们调小一些。

**Comment by zhenzhendong** [comment]
这个可以调整成自定义设置大小么

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
