### ISSUE TITLE
[Bug]模版解析错误

### ISSUE THREAD

**Issue by xiaokai0** [dataease/dataease#12113]
**DataEase 版本**
v2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome最新版

**Bug 描述**
想要查看模版或者在现有模版基础上改动，打开模版后报了错误

**Bug 重现步骤(有截图更好)**
1.
![1](https://github.com/user-attachments/assets/91b40393-a065-428c-98cb-c3bfbd3c7946)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题我们已经收到了，请问一下是用的那个模版导致的异常呢？

**Comment by xiaokai0** [comment]
业务全景监控大屏

**Comment by xiaokai0** [comment]
1. DataEase 基础数据分析大屏-平台对接
2. 业务全景监控大屏-平台对接
3. Jira 业务数据看板-平台对接
4. Zabbix 监控告警大屏-平台对接
5. 禅道业务数据分析大屏-平台对接
6. JumpServer 安全大屏（浅色）-平台对接
7. 智能生产驾驶舱-制造行业
8. 2022年国民经济统计数据-金融财务
9. GitHub 2022年度报告-开源洞察
10. 2024 高考大数据看板-教育行业
11. 2022航空运输情况-交通运输

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
