### ISSUE TITLE
[Feature]v2.10, 数据填报，公司下发给门店进行填报，经常碰到 填报数据 如销量，都超过库存了。有些门店填报数据错误。希望能添加校验或者和数据库库存数据联动。

### ISSUE THREAD

**Issue by 35plus** [dataease/dataease#12115]
DataEase 版本:
v2.10

**请描述您的需求或者改进建议.**
v2.10, 数据填报，用户下发给门店进行填报，经常碰到 填报数据 如销量，都超过库存了。有些门店填报数据错误。

希望能添加校验或者和数据库库存数据联动。用户现在经常遇到填报上来的总的销售量，超过 下发给门店的产品库存。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已经加入了近期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
