### ISSUE TITLE
[Bug]v2.10 数据大屏若干问题反馈

### ISSUE THREAD

**Issue by huahua2023** [dataease/dataease#12118]
**DataEase 版本**
v2.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
最新版的EDGE

**Bug 描述**
1、tab选项中的组件在图层管理中是看不到的
2、组件的位置参数填写后保存是无效的，只有用鼠标拉动保存才有效果。
3、日期时间组件放在tab选项里面保存后是看不到的
4、查询组件在参数是年月日的情况下是没有年月或者年的选项的，v1.18版是有的

**Bug 重现步骤(有截图更好)**
1.如下图，tab中的组件不法显示到图层管理里面，是空的
![image](https://github.com/user-attachments/assets/036d5be8-dad3-4b88-a250-806cc2ed4afb)

2.这下面位置的参数手动填写保存后实际是没有效果的
![image](https://github.com/user-attachments/assets/a58f7ff5-637f-4b79-b73f-54df2debce07)

3.这个日期时间组件放在tab中保存后是看不到的
![image](https://github.com/user-attachments/assets/2f4967f0-1a0c-414b-987a-c3c1d8873ce8)

4、如图，只有年月日的选项
![image](https://github.com/user-attachments/assets/e1c3e644-f5f2-424a-a78b-51ba999d20cf)

**Comment by huahua2023** [comment]
跑马灯的字也显示不出来

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的2和4，需要受累你看一下清除缓存是否依然无法调整和查看，1的话我们记录下来了，后续会加入到需求池中，我们修复一下部分组件无法显示的问题；

**Comment by huahua2023** [comment]
> 感谢反馈，目前测试环境没有发现你说的2和4，需要受累你看一下清除缓存是否依然无法调整和查看，1的话我们记录下来了，后续会加入到需求池中，我们修复一下部分组件无法显示的问题；

第2点也是在tab选项里面是无效的，非tab选项里面是没有问题的。第4点不是缓存问题，数据库参数如下面这样设置的，但是v1.18版本是没问题的。
![image](https://github.com/user-attachments/assets/49756ffe-88c4-4f9d-9099-66e8978ce3e7)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复如下：
第2点没有复现，第3点已经修复。
第1点和第4点我们加入需求池中，优化一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
