### ISSUE TITLE
[Feature]查询条件名称能够调整选项框内的文字，和组件名称文字一起调整，单独调整也是可以的

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12111]
DataEase 版本:
v2.10.0 its

**请描述您的需求或者改进建议.**
目前：查询条件名称调整文字大小后，选项框内的提示词不会改变字号，包括日期的数字也不会改变。
其他提示词倒还好，那个日期的数字太小了，年纪大点的人可能都看不清
![image](https://github.com/user-attachments/assets/1bba8144-0e4f-4208-b5fb-2f2e6f742f59)
需求：能够调整选项框内的文字，和组件名称文字一起调整，单独调整也是可以的

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已经在v2.10.1的优化清单中，请等待新版本的发布。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
