### ISSUE TITLE
[Bug]v2安装包 mysql my.cnf中max_allowed_packet配置项重复，导致修改配置不生效

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#12117]
![image](https://github.com/user-attachments/assets/18764f23-d633-4253-a55a-ae538195cb1b)

**Comment by wolf-kingx** [comment]
安装目录 dataease2.0/conf/my.cnf

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
