### ISSUE TITLE
[Bug]V1 明细表 翻页之后 再查询，会出现查询不到的问题

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12125]
**DataEase 版本**
v1.18.23

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
google

**Bug 描述**
V1 明细表 翻页之后 再查询，会出现查询不到的问题

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
