### ISSUE TITLE
[Bug]面积图多个指标也是堆叠的效果

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#12124]
**DataEase 版本**
v2.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
![图片](https://github.com/user-attachments/assets/f3c4e23b-d3a2-4f02-8e6a-b7eccacb43f1)
如图：面积图，两个指标，展示的是堆叠面积图的效果

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，方便说一下详细的操作步骤吗？
![image](https://github.com/user-attachments/assets/1c70a596-ee64-4882-abb6-5a78d53e3d54)

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
