### ISSUE TITLE
[Bug]自定义SQL出来的字段无法自动识别

### ISSUE THREAD

**Issue by Xyuncheng** [dataease/dataease#12129]
**DataEase 版本**
v2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome 126.0.6478.183

**Bug 描述**
自定义SQL运行出来结果之后，发现属于数值类型的字段被识别为文本类型的字段，同时维度跟指标也无法自动识别，还需要手动去批量调整，比较麻烦，希望能够优化。

**Bug 重现步骤(有截图更好)**
![8d0fad860376382226c10ced13db908](https://github.com/user-attachments/assets/4fb88fcd-0504-48b7-ba8e-f76e01708796)
![1725957198864](https://github.com/user-attachments/assets/8a1421bd-ff13-4670-996c-ae5fc7f573c9)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问字段类型是什么？我们模拟看一下；

**Comment by Xyuncheng** [comment]
字段类型是数值的，识别为文本了

**Comment by maninhill** [comment]
6个月内无更新，关闭。
