### ISSUE TITLE
[Bug] 仪表板空白

### ISSUE THREAD

**Issue by huadisan** [dataease/dataease#12127]
**DataEase 版本**
v.1.18.24

**运行方式(安装包运行 or 源码运行 ?)**

安装包运行 

**浏览器版本**

谷歌浏览器 版本 128.0.6613.120（正式版本） (x86_64)

**Bug 描述**

仪表板，显示空白，重新选择字段显示，保存后打开消失

**Bug 重现步骤(有截图更好)**
1.仪表板，显示空白，
<img width="1023" alt="image" src="https://github.com/user-attachments/assets/450ab9fd-cc4b-406a-83a5-a24baef8fc46">
2.重新选择地图显示
<img width="1100" alt="image" src="https://github.com/user-attachments/assets/e83faa99-f9c0-4ed9-8e4d-38c9058a9918">
<img width="1150" alt="image" src="https://github.com/user-attachments/assets/cdb5be34-2cbd-4e51-8a7b-8513bd778a63">
3.保存后打开消失
<img width="1067" alt="image" src="https://github.com/user-attachments/assets/34f3aa4f-1f81-4501-a699-57e97642e727">

https://github.com/user-attachments/assets/95a9faaf-fb47-41b0-8d6a-4cc22d904df0

**Comment by BBchicken-9527** [comment]
感谢反馈，方便问一下你是用的模版吗？方便能详细描述一下你复现的步骤吗？我这边模拟看一下；

**Comment by huadisan** [comment]
<img width="1337" alt="image" src="https://github.com/user-attachments/assets/f78f5105-46a1-430b-b469-fbb53f638b15">
<img width="1309" alt="image" src="https://github.com/user-attachments/assets/a72afb2b-51e4-4672-8df7-2951316604c3">

导出入应用的时候，这个组件数据变空了，导致全部显示为空。我把这个组件删除了就显示了

<img width="1305" alt="image" src="https://github.com/user-attachments/assets/7307565b-d851-4cd1-a170-dbebf95cf47b">

**Comment by huadisan** [comment]
[互认统计驾驶舱v3现场112.zip](https://github.com/user-attachments/files/16959932/v3.112.zip)
应用

**Comment by huadisan** [comment]
[互认统计驾驶舱v3现场112-TEMPLATE.DET.zip](https://github.com/user-attachments/files/16960374/v3.112-TEMPLATE.DET.zip)
模版

**Comment by BBchicken-9527** [comment]
感谢反馈，我这边查看你的模版是存在问题的，方便给我一份正常可使用的吗？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
