### ISSUE TITLE
[Bug] 查询组件的背景边框是固定不变的，字体过大时会超出边框

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#12134]
**DataEase 版本**
2.10

**运行方式(安装包运行 or 源码运行 ?)**
离线

**浏览器版本**
最新版

**Bug 描述**
1、查询组件的背景边框是固定不变的，字体过大时会超出边框
![image](https://github.com/user-attachments/assets/268d4f5f-ca8a-4a2b-a304-8915e27191e1)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行优化；

**Comment by BBchicken-9527** [comment]
感谢反馈，经讨论暂时不对此处进行处理；
