### ISSUE TITLE
[Question]请问如何避免

### ISSUE THREAD

**Issue by hzhwyh0116** [dataease/dataease#12135]
**请描述您的问题.**

请问如何避免跳转时出现的白屏？

https://github.com/user-attachments/assets/b1ab2f26-7043-4413-8f02-31a0d4275e4a

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，跳转的页面加载需要时间，因此加载的慢白屏时间久一些，加载的快白屏的时间短一些。
