### ISSUE TITLE
[Feature] 数据和视图部分太过紧凑，有重合

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#12136]
DataEase 版本:
2.10

**请描述您的需求或者改进建议.**
数据和视图部分太过紧凑，有重合，可以考虑新增设置  数据和视图部分 间距的功能
![7d13a95986b1d2047882168f88e03e3](https://github.com/user-attachments/assets/71d954e6-1dc0-4d04-81da-bf7d0969b6e2)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持。
