### ISSUE TITLE
[Bug]【数据集】Excel 数据源自定义 SQL 关联 Doris 数据源自定义 SQL 报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#12137]
**DataEase 版本**
v2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
Excel 数据源自定义 SQL 关联 Doris 数据源自定义 SQL 报错，关联条件是文本字段类型

**Bug 重现步骤(有截图更好)**
<img width="1281" alt="e146574f59cd56585f7c1a7294b4253" src="https://github.com/user-attachments/assets/1ad6db6d-7425-4d4a-ab72-a3ed0adb62ae">

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，正在努力修复中，我们会在后续版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
请升级版本。
