### ISSUE TITLE
[Bug]v2.10 tab中的组件，在编辑的时候组件之后有空隙，在预览界面，无空隙

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#12132]
![image](https://github.com/user-attachments/assets/6c0e7d49-c161-440c-a8a5-0b3cbbe3bad8)
![image](https://github.com/user-attachments/assets/0f47a91e-d87c-4009-9b0e-7929761f0af0)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
