### ISSUE TITLE
[Feature]自定义指标名称字符数调大

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#12145]
DataEase 版本:
2.x

自定义指标名称，最大只能20个字符，希望可以调大，如 50
国际化语言环境下，通常单词比较长，容易超过20字符
![图片](https://github.com/user-attachments/assets/936bba76-2ca2-4f0d-9e3b-843d7f44d009)

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
