### ISSUE TITLE
[Bug]查询组件问题

### ISSUE THREAD

**Issue by jacksonhou** [dataease/dataease#12147]
**DataEase 版本**
2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
在线试用

**浏览器版本**
chrome

**Bug 描述**
![image](https://github.com/user-attachments/assets/3a7492c0-4fec-4eec-b4a8-40c0820a780f)

**Bug 重现步骤(有截图更好)**
1. 修改查询组件的区域的高度，组件位置没有适配
2. 查询组件和按钮高度不对其
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行优化

**Comment by BBchicken-9527** [comment]
感谢反馈，经讨论button位置是跟着查询组件的右下角进行位置变化，查询组件的位置不变，因此调整查询组件的宽高时，会出现对不齐的情况。所以暂时不对此处进行优化；
