### ISSUE TITLE
[Bug] 查询组件的文字显示模糊

### ISSUE THREAD

**Issue by jacksonhou** [dataease/dataease#12148]
**DataEase 版本**
2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
在线试用

**浏览器版本**
chrome

**Bug 描述**
![image](https://github.com/user-attachments/assets/565d6f72-4d5a-4c02-8f4f-530e4ff64b61)

**Bug 重现步骤(有截图更好)**
1. 查询组件的文字显示模糊，没有其他地方清晰
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，我们已经在努力修复中；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
