### ISSUE TITLE
[Feature]添加Excel数据源时，子表只能最多八个，第九个不显示

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#12150]
DataEase 版本:
V2.10

**请描述您的需求或者改进建议.**
添加Excel数据源时，子表只能最多八个，第九个不显示
![image](https://github.com/user-attachments/assets/8d2d5769-24d7-4f4c-8b23-d475da034f1b)
![image](https://github.com/user-attachments/assets/5c82fbf0-f8c4-45dc-9527-201bd6eab9a7)
![image](https://github.com/user-attachments/assets/bb7038b0-9876-4ec9-8b67-c92f730853f6)

**Comment by xuwei-fit2cloud** [comment]
你好，我们并没有复现这个问题，方便联系我们提供一下相关Excel文件吗？
![图片](https://github.com/user-attachments/assets/d4638a54-3d34-4866-90f1-e01c3c3eed2b)
![图片](https://github.com/user-attachments/assets/a690e92e-3d1a-4348-b73f-4c06ff204394)

**Comment by zhangtong9898** [comment]
麻烦了，现在没问题了
