### ISSUE TITLE
[Feature]新增组件时，建议新增位置在屏幕中心而不是画布中心

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#12152]
DataEase 版本:
V2.10

**请描述您的需求或者改进建议.**
新增组件时，建议新增位置在屏幕中心而不是画布中心。目前在放大画布情况下，添加的组件需要调整大屏位置之后才能看到。
![image](https://github.com/user-attachments/assets/71af1c50-ecae-4bba-ae62-6cfbc5a6c62d)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划调整。
