### ISSUE TITLE
[Feature]上传的字体希望支持 otf 格式

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#12154]
DataEase 版本:
V2.10

**请描述您的需求或者改进建议.**

上传的字体希望支持 otf 格式
![image](https://github.com/user-attachments/assets/81bafd7d-6948-422c-8d6f-86992906805b)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录进需求池中，可以先用转换工具转换成ttf，然后上传使用。

**Comment by xuwei-fit2cloud** [comment]
暂无支持计划。
