### ISSUE TITLE
[Feature] 想要达到点击某个图表时，复制某个组件或者新建图表时，都在其附近生成图表

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12158]
DataEase 版本:
v2.10.0

**请描述您的需求或者改进建议.**
想要达到点击某个图表时，复制某个组件或者新建图表时，都在其附近生成图表。
1.现在的仪表板是自动占位，复制生成是向下，会打乱全部的顺序，新生成是在足够宽度的占位处。
2.数据大屏是生成在中间，当图表多的时候，每次都需要拖拽
需求：看看仪表板/数据大屏是否方便选中当前操作图表，复制某个组件或者新建图表时，都在其附近生成图表。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划调整。像仪表板，新增或者复制是向下添加的，如果打乱了已有的顺序，将该图表拖拽至其它位置即可恢复原有的布局；大屏中添加图表时，不管添加在哪个位置，为了布局上的美观，应该都需要调整。

**Comment by zhainanshidai** [comment]
> 前

不是呀，是期望要一个快捷添加的功能

**Comment by zhainanshidai** [comment]
> 感谢您的反馈，目前暂时没有计划调整。像仪表板，新增或者复制是向下添加的，如果打乱了已有的顺序，将该图表拖拽至其它位置即可恢复原有的布局；大屏中添加图表时，不管添加在哪个位置，为了布局上的美观，应该都需要调整。

不是呀，是期望要一个快捷添加的功能

**Comment by zhainanshidai** [comment]
> 感谢您的反馈，目前暂时没有计划调整。像仪表板，新增或者复制是向下添加的，如果打乱了已有的顺序，将该图表拖拽至其它位置即可恢复原有的布局；大屏中添加图表时，不管添加在哪个位置，为了布局上的美观，应该都需要调整。

这样能够加快仪表板/大屏制作进度
