### ISSUE TITLE
[Feature]按钮可以反复点击，导致反复加载数据

### ISSUE THREAD

**Issue by 2023fan** [dataease/dataease#12156]
DataEase 版本:V2.10

**请描述您的需求或者改进建议.**
问题：界面上很多蓝色按钮可以反复点击，导致反复加载数据；下面举例说明一下
新增数据集之后，需要点击“确认”按钮，但是由于数据量太大，加载一段时间，这个时候用户可能就可能会以为没点击成功，而反复点击；
![image](https://github.com/user-attachments/assets/a20ae8bf-24ac-4146-bd3a-b070cda6187d)
改进建议：
用户点击一下后，按钮颜色由蓝色变成灰色或者出现一个转圈圈的标识，这样可以从一定程度上避免反复点击了

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中优化一下。
