### ISSUE TITLE
[Feature]功能优化需求

### ISSUE THREAD

**Issue by zjdc** [dataease/dataease#12168]
DataEase 版本:V2.9.0

1.不同图表的图例图标不统一。例如折线图的图例是空心的，但是在标签中又是实心的，而柱状图的图例图标和标签中又是实心圆。需要统一下。
![image](https://github.com/user-attachments/assets/9708a5e0-895f-4721-9a08-e8781cf2f3f6)
2.折线图最好可以实现鼠标放在任意地方都可以显示标签，而不是只在轴线处显示。（V1可以实现）。如下图，鼠标放在轴线处可以显示标签，但是放在折线处不能显示标签。且在V2版本中标签不可以自定义（V1可以实现），希望可以实现标签自定义。
![image](https://github.com/user-attachments/assets/8446f5e5-c2b0-46a0-abea-a01fefb669e7)
![image](https://github.com/user-attachments/assets/a75d2d07-86af-4755-9123-6493b309bbd2)
3.数据大屏默认为黑色，修改背景颜色为白色后需要手动全部修改各图表的字体颜色，且左边的图层管理列，右边的大屏配置列，上面的功能部分为黑色，观感比较难受。
![image](https://github.com/user-attachments/assets/d6a86783-706c-4d85-bbeb-f89e2857e83c)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复请见如下：
1、图例统一，已经加入近期的版本迭代中。
2、提示触发区域，已经加入近期的版本迭代中。
3、如果更换白色背景图，建议使用批量修改，统一调整标签、图例等的颜色。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
