### ISSUE TITLE
[Bug]Echarts中的地图视图功能增强

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#1216]
**请描述您的需求或者改进建议.**
1、支持多选地图要素，如我可以选择浙江省、江西省、江苏省、安徽省、上海市等做为地理要素进行数据展示
2、支持地图要素中无数据的展示方式，当前都是NaN方式；
3、美化默认地图展示效果，并支持用户自定义地图边框颜色配置；
4、支持自定义地图展示区域，如全国地图我想默认展示华东区域，而不是整个地图

**Comment by yayanpei** [comment]
感谢反馈，第2点已规划在 V1.6.0（2022.1.6号发布） 版本优化，其余几点我们需要内部讨论一下。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
