### ISSUE TITLE
[Bug]数据集替换数据提示“java.lang.NoClassDefFoundError: org/apache/commons/math3/util/ArithmeticUtils”（dataease-v1.18.23-offline）

### ISSUE THREAD

**Issue by zifangsky** [dataease/dataease#12170]
**DataEase 版本**
dataease-v1.18.23-offline.tar.gz

**运行方式(安装包运行 or 源码运行 ?)**
用离线版本升级到的 dataease-v1.18.23

**浏览器版本**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36

**Bug 描述**
用离线版本升级到的 dataease-v1.18.23 后，更新数据集的数据提示“java.lang.NoClassDefFoundError: org/apache/commons/math3/util/ArithmeticUtils”

**Bug 重现步骤(有截图更好)**
1. 通过“替换数据”的方式更新某个Excel类型的数据集的数据
2. 然后上传Excel文件后，后端返回以下提示
![image](https://github.com/user-attachments/assets/cbfa094e-7b88-45bb-92f0-b9736f3dd5ba)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，可以升级后尝试；
![Uploading image.png…]()
