### ISSUE TITLE
[Feature]同一个页面嵌入多个相同的视图 ID

### ISSUE THREAD

**Issue by hzhwyh0116** [dataease/dataease#12171]
DataEase 版本:
V2.10.0

**请描述您的需求或者改进建议.**

需求场景：我想在 DE 这边设计一个饼状图，但是嵌入时根据不同的过滤参数分化出 3 个饼图来展示。
目前现状：由于目前同一个页面不支持嵌入多个相同的视图 ID，若要达到此场景需要我在 DE 设计3 个视图才能达到效果。
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/7ba591f8-f97b-4eda-801b-6f151c20f7af">

原因：目前视图渲染是根据视图 ID 来的，所以多个 div 要嵌入同一个视图 ID 时会出现 ID 冲突的情况，只给第一个 div 进行渲染。
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/bff9b9cf-2712-4dde-bbf1-31bcf66b57bb">

期望：希望能够在嵌入时，div 的 ID 拼接个递进值

**Comment by xuwei-fit2cloud** [comment]
ID是图表的唯一标识，我们不想在ID上进行调整，建议您通过图表的复制功能复制出3个图表。

**Comment by hzhwyh0116** [comment]
上述举例 3 个是示例

实际场景是动态的，是根据业务场景动态的，若是动态的就不太好判断事先要复制出多少个视图
