### ISSUE TITLE
[Bug]字段类型识别错误，备注未识别

### ISSUE THREAD

**Issue by hzhwyh0116** [dataease/dataease#12174]
**DataEase 版本**
 v2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
 chrome

**Bug 描述**
数据源 Doris(paimon)

字段类型识别错误，备注未识别
<img width="1408" alt="image" src="https://github.com/user-attachments/assets/8dd03750-4598-46b3-b00e-fac73c476b9e">

建表语句和自定义 SQL 如下：

-- 按维度统计n月-m月累计数据
create table if not exists fuel.dws_buy_use_inventory_report_ave(
	-- 报表基础信息
	start_date   string  comment'统计开始日期，使用固定格式yyyy-mm',
	end_date   string  comment'统计结束日期，使用固定格式yyyy-mm',
	-- month_year  string  comment'时间数据类型分类：本月，累计',
	data_type  string  comment'数据类型分类：基础数据，汇总数据',
	caliber_type string comment'口径:默认口径 个性化口径 特殊口径',
	caliber_name varchar  comment'口径名称',
	coal_type  string  comment'标准煤种',
	buy_mode  string  comment'采购方式：竞价、议价、月度重点等',	
	order_type string  comment'订货口径',
	comp_id  string  comment'机构id',
	organ_type string comment'机构类型：电厂、分公司',
	org_name string comment'机构名',
	supplier_id  string  comment'供应商id',
	-- supplier_name  string  comment'供应商名称',
	mine_id	 string  comment'矿点id',
	-- mine_name string comment'矿点名称',
	area_id	 string  comment'地区id',	
	-- area_name string  comment'地区名称',
	transport  string  comment'运输方式',
	cum_use_amount double comment'累计耗用量（万吨）',
	cum_buy_amount double comment'累计采购量（万吨）',
	cum_stan_unit_price double comment'累计标单（元/吨）',
	low_price_buy_amount double comment'低价时期采购量（万吨）',
	low_price_use_amount double comment'低价时期耗用量（万吨）',
	low_price_dif_buy_use_amount double comment'低价时期供耗差（万吨）',
	dif_buy_use_per_buy double comment'低价时期供耗差占采购量（%）',
	low_price_use_per_cum_use double comment'低价时期耗用占总耗用量（%）',
	low_price_use_and_time double comment'低价时期耗用占总耗用量与时间进度比',
	dif_cost double comment'低价时期供耗差成本（万元）',
	dif_cost_per_cum_cost double comment'低价时期供耗差成本占采购总成本（%）',
	judge1 string comment'低价时期供耗差占采购量<0',
	judge2 string comment'低价时期耗用占总耗用量与时间进度比<0',
	judge3 string comment'低价时期供耗差占采购量>0,低价时期供耗差成本占采购总成本>0',
	-- judge1 as if(dif_buy_use_per_buy<0,'低价时期采购量小于耗用量，没有利用低价时期提库存，采购节奏把握不好',' '),
	-- judge2 as if(low_price_use_and_time<0,'低价时期耗用占本单位总耗用量在时间进度以下，低价时期采购量没有达到月度平均水平，负数越大，表明低价时期生产耗用越少，耗用节奏越不合理',' '),
	-- judge3 as if(dif_buy_use_per_buy>0 and dif_cost_per_cum_cost>0,'低价时期虽然提升库存了，但从本年整体来看，低价时期采购并没有达到控价效果。比如在低价时期的多个月份中，没有在价差大、价格优势明显的月度大幅采购，提库存，甚至某个月采购量小于耗用量',' '),
	proc_time timestamp(3),
	primary key (start_date,end_date,data_type,caliber_type,caliber_name,coal_type,buy_mode,order_type,comp_id,supplier_id,mine_id,area_id,transport) not enforced	
)
partitioned by (end_date)
with (
	'connector' = 'paimon',
	'path' = 'hdfs://masters/paimon',
	'snapshot.time-retained'='120 h',
	'sink.parallelism'='4',
	'scan.parallelism'='4',
	'bucket' = '4',
	'changelog-producer'='input'
);

select * from fuel.dws_buy_use_inventory_report_ave;

**Comment by BBchicken-9527** [comment]
感谢反馈，目前拖拽方式可正常支持commit显示，我们通过table name方式获取所以自定义方式暂时还无法识别；
![image](https://github.com/user-attachments/assets/de5ded31-ab2f-4094-8352-9e79c5ed3cf6)
