### ISSUE TITLE
[Bug] PG  timestamp with time zone 类型字段识别为文本，且无法转换为时间

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#12173]
**DataEase 版本**
v2.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 128.0.6613.121（正式版本） （64 位）

**Bug 描述**
PG  timestamp with time zone ，带时区的日期类型，默认在 dataease 里识别为文本，且尝试转换为日期时，存在异常报错。

**Bug 重现步骤(有截图更好)**
1. 数据集引入后，数据默认显示为文本数据。
![70f77ce203f901c0099385af80aee3e](https://github.com/user-attachments/assets/5964f8bd-3b9b-4936-b790-301969083072)

2.  数据集字段管理切换字段类型为时间时，抛出如下的异常。
![c84869428e7943c3787845c1176477b](https://github.com/user-attachments/assets/4a62ee72-9b26-4792-8e34-2d4ba81c8c58)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，请问具体的复现步骤是什么；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
