### ISSUE TITLE
[Feature]组件选项卡的视图支持查看明细

### ISSUE THREAD

**Issue by liudezhi2098** [dataease/dataease#1217]
![image](https://user-images.githubusercontent.com/33149602/142340482-d592c69d-9127-4278-a30a-482ead9d2965.png)

视图左上角没有查看明细的菜单
![image](https://user-images.githubusercontent.com/33149602/142340704-80ea9eff-6a63-4b32-b3eb-d874468185e5.png)

**Comment by xuwei-fit2cloud** [comment]
收到需求，我们讨论一下

**Comment by xuwei-fit2cloud** [comment]
1月初即将发布的v1.6.0 已支持，请关注最新版本的发布。
