### ISSUE TITLE
[Feature] v2 查询组件在外面显示精确匹配和模糊匹配需支持配置显示与不显示

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12183]
DataEase 版本:
v2.9.0

**请描述您的需求或者改进建议.**
 v2 查询组件在外面显示精确匹配和模糊匹配需支持配置显示与不显示
![3a94779d960612e11d9e59291517145](https://github.com/user-attachments/assets/aac68d8e-6368-4cce-9857-f2fceaf91555)
这个已有些客户反馈希望支持查询组件在外面显示精确匹配和模糊匹配需支持配置显示与不显示。比如配置好精确匹配的默认值选项，可选在界面中显不显示。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，近期会做一下相关优化。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
