### ISSUE TITLE
[Bug]数据大屏鼠标批量选择图层之后按键盘 Backspace 会删除最后一个图层

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#12195]
**DataEase 版本**
2.10.0lts

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge最新

**Bug 描述**
如图，按键盘 backspace 应删除已选中图层，结果删除了最后一个图层
![Backspace从后往前删](https://github.com/user-attachments/assets/b293ea43-3f7a-462c-b013-835178e48d82)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by ziyujiahao** [comment]
https://github.com/dataease/dataease/pull/12378/commits/a60aa76a071dabac668454d600a6646ddd39f30c

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
