### ISSUE TITLE
[Bug]指标卡修改数值格式，再配置同比环比数值格式会重置为默认配置

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#12199]
**DataEase 版本**
2.10.0lts

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge最新

**Bug 描述**
如图
![指标卡配置同环比导致数值格式重置](https://github.com/user-attachments/assets/c4476418-e26e-4309-ab66-4b085dec8bf6)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行优化；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
