### ISSUE TITLE
[Bug]导出事件导出的文件无扩展名导致无法直接打开

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#12198]
**DataEase 版本**
2.10.0lts

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge最新

**Bug 描述**
如图
![导出文件无扩展名导致无法直接打开](https://github.com/user-attachments/assets/95eb6d98-7ca0-4577-95a6-028daec4ca9e)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境暂时没有发现你说的这个问题，方便问一下有什么复现的步骤吗。我们这边尝试复现一下；

**Comment by liuboF2c** [comment]
> 感谢反馈，目前测试环境暂时没有发现你说的这个问题，方便问一下有什么复现的步骤吗。我们这边尝试复现一下；

大屏名称使用 v2.10 时会出现此问题

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
