### ISSUE TITLE
[Bug]图表的数据集切换后，数据集中的计算参数未跟随切换，显示的还是之前数据集的计算参数

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#12196]
**DataEase 版本**
2.10.0lts

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge最新

**Bug 描述**
如图
![计算字段变量在切换数据集时未更新](https://github.com/user-attachments/assets/f1e0e112-9129-42c9-b858-a8ee595c76fb)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
