### ISSUE TITLE
[Bug]数据大屏 TAB 轮播数值修改后保存按钮灰色

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#12193]
**DataEase 版本**
2.10.0lts

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge最新

**Bug 描述**
如图
![TAB 轮播修改不触发保存按钮](https://github.com/user-attachments/assets/43bc3e7b-745c-436d-8801-2fd7ab12904d)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
