### ISSUE TITLE
[Bug] 系统管理/用户管理的「新建用户」按钮经常由于页面刷新（例如根据组织进行刷新）而隐藏

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#1219]
**DataEase 版本**
1.14.1

**浏览器版本**
chrome  95.0.4638.69

**Bug 描述**
系统管理/用户管理的「新建用户」按钮经常由于页面刷新（例如根据组织进行刷新）而隐藏。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/46042812/142386314-a19fadb5-c9bb-40c6-8e69-fdc581b2e6b5.png)

**Comment by yayanpei** [comment]
感谢反馈，我们尽快修复一下。

**Comment by BBchicken-9527** [comment]
问题已修复。
