### ISSUE TITLE
[Bug]分组柱线组合图导出原始明细只有一条数据

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#12197]
**DataEase 版本**
2.10.0lts

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge最新

**Bug 描述**
如图
![分组柱线组合图导出原始明细只有一条数据](https://github.com/user-attachments/assets/60fceb0c-f05e-4889-9478-5ac7e928777a)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
