### ISSUE TITLE
[Feature] 当气泡大小没有值时，散点图的大小直接安装已拖入的值轴渲染大小

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#12206]
DataEase 版本:
2.10.0

**请描述您的需求或者改进建议.**
![image](https://github.com/user-attachments/assets/310b50d0-1e9d-47d2-902e-4eb9677d78a5)
当气泡大小没有值时，散点图的大小直接安装已拖入的值轴渲染大小

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论下优化方式。

**Comment by xuwei-fit2cloud** [comment]
气泡图的指标栏本身只应该支持单个指标，不允许多个指标的使用。我们会在后续版本里加上数量限制。
