### ISSUE TITLE
[Bug]自定义sql运行能查出数据，保存后，报错，显示没有字段

### ISSUE THREAD

**Issue by JOJO30317** [dataease/dataease#12201]
**DataEase 版本**
2.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
自定义SQL运行能查出数据，保存后，报错，显示没有字段

**Bug 重现步骤(有截图更好)**
1.
![QQ20240913-160248](https://github.com/user-attachments/assets/81e70256-d0f7-404a-b2f4-1f9b004ee896)

2.
![QQ20240913-160314](https://github.com/user-attachments/assets/af21ebf4-3d54-4ee5-9be1-1940c1f9d212)

3.

**Comment by JOJO30317** [comment]
另外，添加参数，会报错，或者运行结果无数据
![image](https://github.com/user-attachments/assets/5f5f90d9-538d-4a2a-aecc-fdbef85984c3)

![image](https://github.com/user-attachments/assets/955283ae-9596-4f33-b12f-aa1d85bc4578)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问使用的是什么数据源？

**Comment by JOJO30317** [comment]
> 感谢反馈，请问使用的是什么数据源？

SQL SERVER 2019

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，你可以尝试更新看一下问题是否修复，再者，建议这样的sql运行时添加上参数，若参数为字符串需要将字符串进行用引号包裹；
![image](https://github.com/user-attachments/assets/2acb1b1b-cd55-4ce2-b210-18ecc3ffcea4)
![image](https://github.com/user-attachments/assets/0968ae74-5530-49e6-9ad7-d03a5b6d9187)

**Comment by JOJO30317** [comment]
> 感谢反馈，目前测试环境没有发现你说的问题，你可以尝试更新看一下问题是否修复，再者，建议这样的sql运行时添加上参数，若参数为字符串需要将字符串进行用引号包裹； ![image](https://private-user-images.githubusercontent.com/84372766/371829808-2acb1b1b-cd55-4ce2-b210-18ecc3ffcea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1OTY4OTgsIm5iZiI6MTcyNzU5NjU5OCwicGF0aCI6Ii84NDM3Mjc2Ni8zNzE4Mjk4MDgtMmFjYjFiMWItY2Q1NS00Y2UyLWIyMTAtMThlY2MzZmZjZWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDA3NTYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYjkxZDk0ZWIzNjI4OWViYzE4ZWExZWM1NDk2MWJiMzE5NzZhYWYzYWUyYjQ3ODgyNWZkMzRjYjE5ZWNjZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5iB4sUWnbOKHEodlCulwOjRcgg_9FD-vGWdeVbvhRow) ![image](https://private-user-images.githubusercontent.com/84372766/371829882-0968ae74-5530-49e6-9ad7-d03a5b6d9187.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1OTY4OTgsIm5iZiI6MTcyNzU5NjU5OCwicGF0aCI6Ii84NDM3Mjc2Ni8zNzE4Mjk4ODItMDk2OGFlNzQtNTUzMC00OWU2LTlhZDctZDAzYTViNmQ5MTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI5VDA3NTYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1ZjBmMjdmYmNhOTFlNmIxOTIyMGFiODhhMWQxMTRhMjliNWFkZTg4YjEzMGIxZTA3Yzg1NDExMzhmNWYxODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S3rUzyfeg3YvXibYjA2rLNFWaUTtsEGoO6kmtyIMOB0)

后来测试，应该是sql里引用了名称是@开头的表格，因为@开头表格，sql server 要求用[]引用。
但如果sql语句中有[]，就会导致参数失效。
另外，如果注释   --，后面没有空格，而是直接跟着注释内容   --内容，也会导致参数失效。

**Comment by BBchicken-9527** [comment]
emm....目前[]的方式完全是升级以来后，由依赖直接支持的，所以参数化无法做到完全应对，我这边测试环境看一下你说的这个情况；
注释的话，我们统一是按照sql注释去处理的，标准的注释是要求后面带空格的，这里我们认为是合理的；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
