### ISSUE TITLE
[Bug]自定义sql添加参数的情况下不支持方括号引用字段或表格的查询语句

### ISSUE THREAD

**Issue by JOJO30317** [dataease/dataease#12203]
**DataEase 版本**
1.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
ERP系统的数据表名称，会有一部分以@开头命名，sql server 中查询需要使用方括号引用dbo.[@表名]，但dataease中加方括号提示语句不正确，不加也不行。
修正：
不带参数的情况下，支持，添加参数的情况下，报错。

**Bug 重现步骤(有截图更好)**
1.没有参数
![image](https://github.com/user-attachments/assets/b9b02ca9-3f7f-4618-9e84-309639f45a1b)

2.有参数
![image](https://github.com/user-attachments/assets/210ed342-c9dd-4acb-8892-b037d4a6fe94)
![image](https://github.com/user-attachments/assets/23367f3c-08a1-4ece-909c-7e1fb34f4ec1)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前参数化还在完善当中，暂时不支持以这种方式使用参数化；
