### ISSUE TITLE
[Bug]设置两个仪表板之间跳转，设置【当前页打开】会跳转失败

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#12208]
**DataEase 版本**

v2.10.0
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome
版本 128.0.6613.120（正式版本） (arm64)

**Bug 描述**
两个看板互相设置跳转
1 设置【新开页面】会是正常调整
2 设置【当前页面】打开会无法跳转（包括新开预览页时）

**Bug 重现步骤(有截图更好)**
1.正常跳转
![image](https://github.com/user-attachments/assets/1af8cc8b-e712-4508-bb7d-326bddcf2a18)
![image](https://github.com/user-attachments/assets/830602fe-315b-48ef-9c78-57a04b7887d3)
 ![未命名](https://github.com/user-attachments/assets/2ee990bc-3fc0-46b0-b610-2d90c6240cad)

2.无法正常跳转
![image](https://github.com/user-attachments/assets/eaedf333-1402-497a-bec9-bb74c89c3517)
![image](https://github.com/user-attachments/assets/8de402cd-db44-43d0-a4f0-5efec6b9451e)
![未命名](https://github.com/user-attachments/assets/6c6cad81-c81f-42df-aa24-b59dba16ce08)
![未命名3](https://github.com/user-attachments/assets/72e4a245-2541-499f-8894-b05d598b1de5)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，目前正在努力修复中，请耐心等候；

**Comment by ziyujiahao** [comment]
https://github.com/dataease/dataease/commit/545b702e473d1dcc57a49002736d0cedd6246b80

**Comment by xuwei-fit2cloud** [comment]
请升级版本。
