### ISSUE TITLE
[Feature] v2 地图组件想要每个色块范围都自定义，因为可能存在数据分布不均匀的情况，想要每个色块范围可以自定义

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12212]
DataEase 版本:
v2.10.0

**请描述您的需求或者改进建议.**
目前图例只能支持最大值最小值和图例数的自定义，但因为可能存在数据分布不均匀的情况，想要每个色块范围可以自定义。
![285563fa6228874dd0af170bd655da4](https://github.com/user-attachments/assets/30994f4a-20ae-4113-8821-5bbeafded049)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池中。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
