### ISSUE TITLE
[Bug]双柱图，出现折现画错的情况

### ISSUE THREAD

**Issue by 35plus** [dataease/dataease#12223]
**DataEase 版本**
v2.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
 128.0.6613.138

**Bug 描述**
详见重现步骤。

**Bug 重现步骤(有截图更好)**
1. 使用下面excel 数据作为数据源。
[市场需求完成情况.xlsx](https://github.com/user-attachments/files/17001056/default.xlsx)
2. 创建一个数据集，包含所有字段。
3. 创建一个仪表板，添加 “堆叠柱线组合图”，选择第2步的数据集，【数据】字段配置如下
<img width="182" alt="1726289863179" src="https://github.com/user-attachments/assets/86f82686-ca82-4800-ae4f-3e6aa9e574f7">

4. 查看图表。
<img width="759" alt="1726290458963" src="https://github.com/user-attachments/assets/9d5cb089-210a-4ecb-84de-4ae4000b5156">

5. 如果选择对月份进行自定义排序，图表变成如下。出现点没有连起来的情况。
<img width="476" alt="f714f3a8583ff8cd5702694681c9de6" src="https://github.com/user-attachments/assets/3312c5c1-86c7-4f31-99ad-13efd20d386a">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by 35plus** [comment]
感谢

**Comment by BBchicken-9527** [comment]
你好，经我们排查，此处暂时无法做出优化，因为空置存在点无法连接成线，本身想添加空置处理隐藏的，但由于双轴图的特殊性为了保证左右轴对齐，所以无法添加隐藏空置的设置；
