### ISSUE TITLE
[Bug]v2.10, 散点图，如果 指标 包含多个字段，会出现气泡大小失效的情况。

### ISSUE THREAD

**Issue by 35plus** [dataease/dataease#12224]
**DataEase 版本**

v.2.10
**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**
128.0.6613.138

**Bug 描述**

v2.10, 散点图，如果 指标 包含多个字段，会出现气泡大小失效的情况。
**Bug 重现步骤(有截图更好)**
1. 新建一个仪表板，添加散点图，做如下字段配置：
<img width="1272" alt="1726290522890" src="https://github.com/user-attachments/assets/dccf5a9b-1ddc-4d76-9cab-302c9cfe19d9">

2. 目前验证下来，如果指标 只包含一个字段，气泡大小是正常的。
3. 若果指标包含多个字段，气泡大小 就会失效。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现此类问题，请问是毕现的吗？是否可以说明一下完整的复现流程；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
