### ISSUE TITLE
[Bug]URL类型字段，明细表中URL类型显示空白，鼠标悬停时有URL地址显示，点击可以看到图片，但表格中图片不显示

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#12221]
**DataEase 版本**
2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**Bug 描述**
![image](https://github.com/user-attachments/assets/2c943fe9-c6fc-4b8b-908f-f7fb832e4315)
图片地址：
https://pic.imeitou.com/uploads/allimg/240724/10-240H4163639-50-lp.jpg

**Comment by BBchicken-9527** [comment]
感谢反馈，看着应该是域的问题，这个和你使用的浏览器安全策略有关系，可以调整一下再试试；
