### ISSUE TITLE
[Feature]查询组件的宽度固定，会导致一些展示不适配问题，这个需要优化一下，看一下能不能适应变化仪表板所在的位置而适应

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12226]
DataEase 版本:
v2.10.0

**请描述您的需求或者改进建议.**
数据编辑界面：
![image](https://github.com/user-attachments/assets/bf48186f-0746-45a7-9926-2ae91bdda67d)

转到数据预览界面：
![image](https://github.com/user-attachments/assets/508c03cc-6be3-4bc4-9583-db8ec11ff4a0)
因为查询组件的宽度固定，会导致一些展示不适配问题。
这个需要优化一下，看一下能不能适应变化仪表板所在的位置而适应

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，仪表板中的组件是根据画布大小自适应的，自适应模式目前暂时没有计划去调整。
