### ISSUE TITLE
[Bug] 组件中 “选择关联图表及字段” 的“维度”和“参数”混淆，选择“维度”后显示的仍然是“参数”的过滤数据

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#12236]
**DataEase 版本**
2.10

**运行方式(安装包运行 or 源码运行 ?)**
离线

**浏览器版本**
最新版

**Bug 描述**
组件中 “选择关联图表及字段” 的“维度”和“参数”混淆，选择“维度”后显示的仍然是“参数”的过滤数据

**Bug 重现步骤(有截图更好)**
1.原始数据
![image](https://github.com/user-attachments/assets/cc295d55-f160-4ffe-b4ea-f797d279d82f)

2.数据集sql
select * from excel_renwu_67dbb8e82b
  where 日期 between '2024-08-05' and '2024-08-08'
 and  日期 between DATE_SUB('${date}', INTERVAL 2 DAY) and '${date}'

3.创建视图
（1）基础柱状图（时间为维度、指标是数量）（2）指标卡（指标是数量）（3）基础柱状图（时间为维度、指标是数量）
![image](https://github.com/user-attachments/assets/b2da718c-c8a9-461e-87a3-0af5ae4fb433)

4、添加组件
![image](https://github.com/user-attachments/assets/83d41209-931b-47fb-9245-192c2e978546)

5、查看显示结果
![a31d895a449eba51d10b6b597646172](https://github.com/user-attachments/assets/2fff36f5-ba83-462f-b88d-d76f9a6f072e)

预期效果：（1）第一个柱状图显示时间范围是正常的，组件里面选择的是参数；（2）指标卡和折线图应该显示当天数据，组件中选择的是维度。v1版本是正常的。

请核实一下这一块是否存在问题，谢谢。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by BBchicken-9527** [comment]
更新平台后，将有问题的规则删除重新编辑一下就可以了；
