### ISSUE TITLE
[Bug]系统管理-已读消息，「删除」按钮执行删除动作后，有时会导致「删除」按钮隐藏

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#1223]
**DataEase 版本**
1.14.1

**浏览器版本**
chrome 95.0.4638.69

**Bug 描述**
系统管理-已读消息，「删除」按钮执行删除动作后，有时会导致「删除」按钮隐藏

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/46042812/142419027-1063eb70-97be-42b8-ab9f-a6951ad1cdb2.png)
2.
![image](https://user-images.githubusercontent.com/46042812/142419099-e07684e4-f540-413d-823d-c289694e92ab.png)

**Comment by yayanpei** [comment]
感谢反馈，我们尽快排查并修复。

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 已修复
