### ISSUE TITLE
[Bug]更改纵轴标签字体大小，默认颜色会变化

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#12238]
**DataEase 版本**
2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**Bug 描述**
更改纵轴标签字体大小，默认颜色会变化

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/24705e7c-8db7-4add-97e8-d94f89f8bf05)2.
3.
![image](https://github.com/user-attachments/assets/30d9bc44-5680-486b-ac57-d085790430ac)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有复现你的问题，方便补充一下复现步骤吗？我这边模拟一下；
![image](https://github.com/user-attachments/assets/c114ad84-cb7a-47f5-998f-2bc524b05ea9)

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
