### ISSUE TITLE
[Bug] 数据集 - 自定义 sql，字段参考按钮被遮挡

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#12237]
**DataEase 版本**
v2.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
Google Chrome
版本 128.0.6613.138（正式版本） （64 位）

**Bug 描述**
数据集 - 自定义 sql，字段参考按钮被遮挡

**Bug 重现步骤(有截图更好)**
1. windows
![image](https://github.com/user-attachments/assets/30368b55-2dc3-488b-9f75-b5d1d98c7e51)

2. mac
<img width="849" alt="58c78292d32dccb9f3d4e462c8dd07c" src="https://github.com/user-attachments/assets/c14ba143-4707-48c6-9f22-c85c910f0855">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行优化；
