### ISSUE TITLE
[Bug]全屏方式展示大屏时，对Firefox浏览器的兼容性不太好

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#1224]
**DataEase 版本**
1.14.1

**浏览器版本**
firefox 94.0.1

**Bug 描述**
仪表板使用FireFox浏览器全屏预览，在下方处出现一偏空白，而Chrome浏览器正常

**Bug 重现步骤(有截图更好)**
1.FireFox
![image](https://user-images.githubusercontent.com/46042812/142432772-5134ed23-dd84-4116-8b8b-f5d31c943895.png)
2.Chrome
![image](https://user-images.githubusercontent.com/46042812/142432875-532a86f0-1583-4798-b15b-0aa558cec934.png)

3.

**Comment by yayanpei** [comment]
感谢反馈，谷歌浏览器适配效果好一些，建议您使用谷歌浏览器。

**Comment by maninhill** [comment]
这个算Bug吧，还是得修复吧...

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 已处理
