### ISSUE TITLE
[Bug]数据大屏明细表打开序号列后会出现一道竖线

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#12242]
**DataEase 版本**
V2.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome

**Bug 重现步骤(有截图更好)**
1.明细表表头背景设置透明
2.打开序号列后会出现一道竖线
<img width="281" alt="image" src="https://github.com/user-attachments/assets/2e339caf-d6e9-44d9-a0cf-0e883d9b6153">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行优化；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
