### ISSUE TITLE
能否使用传参，进行动态数据库表查询

### ISSUE THREAD

**Issue by skyyan2000** [dataease/dataease#12248]
**DataEase 版本**
社区版
2.9.0

**运行方式(安装包运行 or 源码运行 ?)**

安装包 
 

**Bug 描述**
能否使用传参，进行动态数据库表查询， 由前端传参过来

例如 select * from ${tableName}

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，由于动态的表名数据集的结构无法固定，因此目前无法支持动态表名。
