### ISSUE TITLE
支持单一登录设置[Feature]

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#1225]
**请描述您的需求或者改进建议.**
如下图
![image](https://user-images.githubusercontent.com/35896106/142553225-005713eb-2fab-4229-9e35-164dacf30abc.png)

**Comment by yayanpei** [comment]
感谢您的反馈，需求已记录。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
