### ISSUE TITLE
[Feature]V2 数据大屏地图提示显示显示不全，目前默认是向右边提示，如果一旦放大，在右下的地图区域的提示就会显示不全，看起来好像残缺了一样，这个需要改善一下，最终让提示显示全。

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12254]
DataEase 版本:
v2.10.0

**请描述您的需求或者改进建议.**
V2 数据大屏地图提示显示显示不全，目前默认是向右边提示，如果一旦放大，在右下的地图区域的提示就会显示不全，看起来好像残缺了一样，这个需要改善一下，最终让提示显示全。
![b3ff9e48a38a07cc4886d55f04be0ab](https://github.com/user-attachments/assets/9a7d0f19-06cd-4748-8b7e-910d5221b47c)
![9601ef1592f74ea8b7a2f9329ad927b](https://github.com/user-attachments/assets/5acf77ed-a277-416c-b0fc-0195f98d0ddd)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中优化一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
