### ISSUE TITLE
[Feature]Copilot和小助手开放配置地址，可以改为用户本地的地址

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#12259]
DataEase 版本:
v2

Copilot 和小助手开放配置地址，可以改为用户本地的地址

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复如下：
1、Copilot，可以提供离线包，可修改配置文件，配置为本地的大模型地址。
2、小助手，可以在数据库中修改小助手地址。

**Comment by mfanoffice** [comment]
感谢
