### ISSUE TITLE
[Feature]查询组件希望可以排版对齐

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#12250]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
查询组件过多时显得有点乱，希望可以对齐
![图片](https://github.com/user-attachments/assets/04dca36c-7ece-4359-861e-a86bd5dd23f8)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持。如果有多行查询条件，如下图所示，建议将查询条件的名称放置在上侧。
![image](https://github.com/user-attachments/assets/304f4825-d0b4-475f-a18a-7a5c088b9f7b)
