### ISSUE TITLE
[Bug]创建视图的时候偶尔会提示数据库死锁

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#1226]
**DataEase 版本**
1.14.1

**浏览器版本**
chrome 95.0.4638.69

**Bug 描述**
创建视图的时候偶尔会提示数据库死锁，阐述该视图然后再重新创建，又正常~

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/46042812/142564046-47b4c6ac-f43f-4ab7-945d-7fdc5f695898.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 已处理
