### ISSUE TITLE
[Feature]保存数据大屏/仪表板需要加一个提示，当其他人作了修改时，做必要的保存警告，来减少丢失更新的行为。

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12261]
DataEase 版本:
2.9.1 2.10.0

**请描述您的需求或者改进建议.**
两个人同时编辑的话，后保存人的修改是会覆盖掉先保存的人的，这个没同步机制，刚加的报表被其他同事覆盖掉了。
比如同一个看板，两个人同时打开，我只修改了图表1然后保存，另一位同事只修改了图表2然后保存，最后再看的话图表1的保存就失效了。
保存数据大屏/仪表板需要加一个提示，当其他人作了修改时，做必要的保存警告，来减少丢失更新的行为。

注： 如果可以，看看能不能做类似 redo log 这样的机制，能够回滚版本。这个可选，如果不好做，至少需要上述必要的提示。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们讨论下优化方式。

**Comment by xuwei-fit2cloud** [comment]
目前版本无法支持协同操作。

**Comment by ziliang-wan** [comment]
能否增加下提示呢？比如对比下当前数据库的更新时间戳与前端修改时取到的时间戳做个对比，提示下用户看板已被修改，继续保存可能覆盖其他人的操作等，这样会更友好一些。
