### ISSUE TITLE
[Feature]辅助线能写加减乘除以及结合其他字段等公式，或者可以用同一个数据源里面的其他字段，这两种方案二选一都能满足上述场景的需求。

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12260]
DataEase 版本:

**请描述您的需求或者改进建议.**
辅助线是只能用我放在条形图里面的字段，这个不满足实际应用，比如每个月有销售额和销售指标，然后达到销售指标1.2倍为优秀、0.8倍为良好、0.6倍为及格，我希望在条形图里面通过辅助线的形式体现出来，这个没法很好展现，现在只有最大值最小值平均值这些。
如果想实现得用计算字段创建一个倍数来，这样还得放在指标处，不符合实际场景。
需要：辅助线能写加减乘除以及结合其他字段等公式，或者可以用同一个数据源里面的其他字段，这两种方案二选一   都能满足上述场景的需求。

![3329cc99667c05438247ddf596d8026](https://github.com/user-attachments/assets/428f4051-7fa0-437b-8b94-f48129735dcd)

**Comment by zhainanshidai** [comment]
2.10.0、2.9.1

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持辅助线中添加公式，如果需要使用数据源中的其它字段，建议在数据集中将表关联后获取。
