### ISSUE TITLE
[Feature]鼠标悬浮在图表上时，右上角的数据查看、导出按钮支持通过API控制进行开启/禁用

### ISSUE THREAD

**Issue by lyons-hz** [dataease/dataease#12273]
DataEase 版本:
2.9.0

由于数据比较敏感，用户下载或查看图表数据前，需要对用户权限进行校验。是否可以开放查看、导出按钮的开启/禁用接口来进行控制。
<img width="742" alt="image" src="https://github.com/user-attachments/assets/b31c6618-df1b-4106-86a1-0f684fffb358">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，下载数据的权限控制，可以在权限矩阵中完成。数据查看的权限无法控制，要先拥有数据的查看权限才可以查看图表，因此无法实现仅查看图表却去权限查看数据。
