### ISSUE TITLE
[Bug] 在线体验环境在跳转的时候会有报错信息，提示url不合法，但是却可以跳转

### ISSUE THREAD

**Issue by daiqingyao6238** [dataease/dataease#12276]
**DataEase 版本**
v2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
https://demo.dataease.cn/#/panel/index?dvId=1034077647027703808

**浏览器版本**

**Bug 描述**
点击设置好的跳转地址，de提示跳转错误

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/673567ce-37b5-44bc-a8c5-271c5c5f5df1)
2.
![0473820b-64ca-45e3-89b8-82174d68b0be](https://github.com/user-attachments/assets/9bb9aa81-f8ef-49e2-8443-64c4c52f034b)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，目前正在努力修复中，将会在下个版本完成修复；

**Comment by xuwei-fit2cloud** [comment]
请升级版本。
