### ISSUE TITLE
[Feature]上传到DataEase的图片等静态资源支持对接minio存储

### ISSUE THREAD

**Issue by lyons-hz** [dataease/dataease#12272]
DataEase 版本:
V2.9.0

集成DataEase后，统一使用minio存储，DataEase上传的图片等静态资源是否可以支持对接到minio存储

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
暂时没有支持计划，短期内不想增加其他组件。
