### ISSUE TITLE
[Feature]建议各视图颜色配置增加取色器的功能，获取屏幕某个区域或像素的色值，提高工作效率

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#1227]
**请描述您的需求或者改进建议.**
建议各视图颜色配置增加取色器的功能，获取屏幕某个区域或像素的色值，提高工作效率

![image](https://user-images.githubusercontent.com/46042812/142564517-f3ccbec7-c04c-4810-8ac5-42ff228413ee.png)

**Comment by yayanpei** [comment]
感谢您的反馈，该功能暂不考虑支持。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
