### ISSUE TITLE
[Feature] v2 在复制仪表板和数据大屏操作时需要增加 loading 提示

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12289]
DataEase 版本:
v2.9.1、 v2.10.0

**请描述您的需求或者改进建议.**
场景：在网络延迟时，复制数据大屏时，不知道此时是在等待还是出错了，那客户就可能等不及会一直点，导致请求挤压。
需求：v2 在复制数据大屏/仪表板等操作时想要增加 loading 提示，否则不清楚是错误了还是还在数据加载中，有一个较友好的提示会比较清晰。

**Comment by xuwei-fit2cloud** [comment]
我们近两个版本优化一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
