### ISSUE TITLE
[Bug]v2 sqlserver 数据源 新建计算字段包含聚合字段时，数值显示不正确

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#12283]
新建三个字段：第一个字段为分子，第二个字段为分母，第三个字段为分子/分母；分子和分母都正确，但是分子/分母不正确
![530b901313b0dfdf5eaee85cdf6eff7](https://github.com/user-attachments/assets/768177d8-f516-4d3c-b20a-33bf3c80d6ad)
![c51cfa812e164c876b6da6ff7222b70](https://github.com/user-attachments/assets/1ae834bd-3cab-42ea-ba5f-880bcb82d096)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，方便的话说明一下具体的步骤、字段类型等信息说明一下我们这边模拟看看；
