### ISSUE TITLE
[Bug]视图等名称过长时授权按钮会错位

### ISSUE THREAD

**Issue by zyyfit** [dataease/dataease#1228]
**DataEase 版本**
1.4.0

**浏览器版本**
Chrome 95.0.4638.69（正式版本） (x86_64)

**Bug 描述**
视图、数据集等名称太长的时候，会把授权按钮挤错位

**Bug 重现步骤(有截图更好)**
1.创建一个视图分组，名称输入最大长度
2.在权限管理-视图权限 中查看这个视图
3.
![图片](https://user-images.githubusercontent.com/73461316/142584287-3d8234e2-6998-49ac-a08d-53b2a8b90481.png)

**Comment by xuwei-fit2cloud** [comment]
我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 版本解决。
