### ISSUE TITLE
[Feature]图标过滤器增加参数选择

### ISSUE THREAD

**Issue by JOJO30317** [dataease/dataease#12285]
DataEase 版本:
V2.10.0

**请描述您的需求或者改进建议.**
图表过滤器中能增加数据集参数吗
![image](https://github.com/user-attachments/assets/b5231dad-ede9-49a8-95b4-b0d1ed1d665d)
![image](https://github.com/user-attachments/assets/b1e535d1-8600-410d-a120-1194bc1548f5)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持。
