### ISSUE TITLE
[Bug]v2 sqlserver数据源，sql传参数据集在使用in传参时，有问题

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#12292]
![7dd62245f21146004424f558a050a13](https://github.com/user-attachments/assets/6c386893-75f5-497b-87c3-732e677c9327)
![d5260eac8781e33971b72f6e081c529](https://github.com/user-attachments/assets/5d0cc4db-3103-4a2d-8c0e-0aea652c6763)
![cd152c321c4ad13736f0fa06e342595](https://github.com/user-attachments/assets/f7b2748b-0985-469b-9bed-2db3d3b44c00)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行修复；
