### ISSUE TITLE
[Bug] 透视表 同一个数据、同一个透视表 平铺展示的 正常  树形展示的 就有问题

### ISSUE THREAD

**Issue by daiqingyao6238** [dataease/dataease#12291]
**DataEase 版本**
2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
最新版

**Bug 描述**
同一个数据、同一个透视表 平铺展示的 正常  树形展示的 就有问题

**Bug 重现步骤(有截图更好)**
1.
![bdb486b6-0155-439c-a7a6-a88cd24b9926](https://github.com/user-attachments/assets/90bb14d4-8ce8-429c-8b6f-5e4424de0077)

2.
![51444683-664b-4fa4-9619-9dc15c42490e](https://github.com/user-attachments/assets/4fdc3166-a73c-4706-bd8d-e4330157b8c3)

3.
![6fa0d6b4-fb23-4385-8f28-b831b270d523](https://github.com/user-attachments/assets/a518ec02-1d01-470a-9ddb-7d5245954d6f)

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是当数据集中存在计算字段时会产生问题是吗？

**Comment by daiqingyao6238** [comment]
我的意思是透视表树形时存在计算字段会产生NAN的问题

**Comment by daiqingyao6238** [comment]
> 感谢反馈，你的意思是当数据集中存在计算字段时会产生问题是吗？

我的意思是透视表树形时存在计算字段会产生NAN的问题

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
