### ISSUE TITLE
[Bug] V1 仪表板分享给其他用户，导出明细表会出现报错

### ISSUE THREAD

**Issue by daiqingyao6238** [dataease/dataease#12295]
**DataEase 版本**
v1.24

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
最新版

**Bug 描述**
管理员将仪表板分享给其他用户，其他用户导出明细表报错

**Bug 重现步骤(有截图更好)**
1.
![企业微信截图_17267304073287](https://github.com/user-attachments/assets/c4801455-730e-46f6-8dba-da2599e6331e)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，目前问题正在修复当中；

**Comment by xuwei-fit2cloud** [comment]
v1.18.25版本已处理。
