### ISSUE TITLE
[Bug]v2 clickhouse数据源，做数据集的时候，数值类型会被识别为文本类型

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#12293]
ck版本：
![c7cd3a9b015b90069b4d8ea5aa99200](https://github.com/user-attachments/assets/c730f58c-71fe-46e3-b67e-14e50cf057f4)

![29690e7781578703b39fcd97e8caca8](https://github.com/user-attachments/assets/5a4d89a5-a6f5-41ee-981c-ee6e97e04137)

表结构
[数据结构(1).txt](https://github.com/user-attachments/files/17055594/1.txt)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题已修复，可下载最新版本；
