### ISSUE TITLE
[Feature]v2 查询组件 选择关联图表及字段 每次点加号进来都会自动加一个关联条件，但是是加到最后面，容易被其它条件挡住了，看不到没有填写的条件而报错 找很久，这个新增的条件期望加到最上面去，这样方便操作。

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12290]
DataEase 版本:
v2.9.1 v2.10.0

**请描述您的需求或者改进建议.**
查询组件 选择关联图表及字段 每次点加号进来都会自动加一个关联条件，但是是加到最后面，容易被其它条件挡住了，看不到没有填写的条件而报错 找很久，这个新增的条件期望加到最上面去，这样方便操作。
![image](https://github.com/user-attachments/assets/a68e0dd4-5d27-4f34-9fa1-fb90f814e9bb)

**Comment by xuwei-fit2cloud** [comment]
存在问题的查询条件，前面都会有一个非常明显的警示标记，很容易看到。这块暂时不做调整。
![图片](https://github.com/user-attachments/assets/b1bda2dc-88d4-4a4d-aff9-b4d505322056)
