### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by xxy126789** [dataease/dataease#12300]
**DataEase 版本**
v2.10 企业试用版

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Microsoft Edge
版本 127.0.2651.74 (正式版本) (64 位)

**Bug 描述**
数据集自定义sql页面，当clickhouse sql存在关联或嵌套的时候，${date}参数在自定义sql页面内设置完默认参数后可以执行sql，查询数据，但是当保存，退出页面后就会报错，从数据库日志中发现是参数没有更新而是以${date} 的形式作为sql条件执行的，所以报错

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xxy126789** [comment]
![1726739824394](https://github.com/user-attachments/assets/6c391b0e-cb95-416d-961c-ad1d1e2ddf20)
![30d49fd2169e152ff6c627368cd18b4](https://github.com/user-attachments/assets/724966ef-19cb-4e1f-8d15-6e7f7988f261)
![97423456f8165d764931731bb319a27](https://github.com/user-attachments/assets/b2d5eb8b-d6cb-489a-993f-e9eb9d9f4a0a)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下；

**Comment by xuwei-fit2cloud** [comment]
首先，因为空值的关系，本来就连不成线。

其次，基础折线图里面的空值处理可以设置“隐藏空值”解决这个问题

![图片](https://github.com/user-attachments/assets/7f093bf0-2d5b-4ea9-9651-7bc1c83e832f)

![图片](https://github.com/user-attachments/assets/1ce47679-fa5e-44f5-bbd1-0438677dda48)

最后，组合图里，由于为了保证左右轴对齐，所以没有隐藏空值的选项，所以无法连线
![图片](https://github.com/user-attachments/assets/57d62087-19bd-46e1-8f6c-9728a2bddbe0)
