### ISSUE TITLE
[Feature]当前只支持仪表板复制，其他视图和数据集都不支持复制（不利于快速复制和搭建项目）

### ISSUE THREAD

**Issue by geyesheng** [dataease/dataease#1230]
**请描述您的需求或者改进建议.**
当前只支持仪表板复制
![image](https://user-images.githubusercontent.com/38676947/142746654-b505cb92-6eb3-4a1f-9b5d-2ebdee57198b.png)
其他视图和数据集都不支持复制
![image](https://user-images.githubusercontent.com/38676947/142746673-c559de07-09b8-4ab6-8ece-d25d55de667b.png)
![image](https://user-images.githubusercontent.com/38676947/142746684-c006ae81-1559-46fa-a5b8-8a25c95bf603.png)
复制仪表板后数据还是套用前个内容，如果要重改视图还需要从数据集-视图-仪表板的步骤重新来一次，增加很多不必要的时间（调试样式非常繁琐和浪费时间）
![image](https://user-images.githubusercontent.com/38676947/142746757-4331c44b-5c45-4e85-ab6f-5437e6606686.png)

**Comment by yayanpei** [comment]
感谢反馈，视图支持在仪表板内复制，其他的我们讨论一下。

**Comment by geyesheng** [comment]
> 感谢反馈，视图支持在仪表板内复制，其他的我们讨论一下。

老师，这里应该是我描述的场景让你误解了，此处要表达的是1.如果只是单纯复制仪表板的意义不大，因为复制后的仪表板取的还是同一份视图 （如：存在数据集1-视图1-仪表板1这个时候复制后命名仪表板2） 2.如果需修改复制后仪表板（仪表板2）-视图1的内容，这个时候是无法修改视图1的内容（数据源仍取数据集1的），那么为了让仪表板2展示最新的数据只能再创建一次数据集2-视图2-添加到仪表板2 3.不是单纯为了复制视图即可，最终目的是为了仪表板上呈现不同的数据而不是同样的视图，同样的数据

**Comment by yayanpei** [comment]
再次感谢您的反馈，复制后仪表板的视图是支持编辑的，您看下如下的操作是否符合能满足需求呢？
1、在仪表板中点击编辑视图
![image](https://user-images.githubusercontent.com/84168063/143410881-0cdf6f25-62c7-4656-9684-c33dfe4d7c38.png)
2、在视图中可点击更换视图的数据集
![image](https://user-images.githubusercontent.com/84168063/143411014-10c2505c-cfbb-4879-b82d-30fd2a8d6692.png)


另外关于数据集的复制，不太了解咱们这边的使用场景，方便的话可以添加我的微信：18317092178，进一步沟通交流。

**Comment by xuwei-fit2cloud** [comment]
从v1.8.0版本开始，DataEase中的视图复制为独立视图。
仪表板的复制亦为独立副本。视图在更换数据集时，能根据源数据集字段对新数据集字段进行自动匹配，更加便捷。
关于数据集的复制，处于权限控制以及数据冗余性的考虑，我们在近期版本不会支持。
