### ISSUE TITLE
[Feature]如果存在多个产品或项目，分组后不支持跨数据集的筛选（需要全人为干预，影响到无法落地）

### ISSUE THREAD

**Issue by geyesheng** [dataease/dataease#1231]
**请描述您的需求或者改进建议.**
业务操作：
1.如果用sql查询所有项目（比如：select * from projects）后，然后分组统计出每个项目的问题（select name,count(1） from projects)后，这个时候通过文本下拉选择字段name维度统计
2.继续按项目添加其他维度的内容（细化项目的统计，如项目的时长，人员投入等）

选择项目的时候只能针对单独的视图统计显示，而无法全局匹配（选择一个项目后，整个大盘的数据都会动）
![image](https://user-images.githubusercontent.com/38676947/142747025-4b490aa8-45ca-4a5d-8edb-2716d5ab809f.png)

![99bb3a4a46e8b5d6361d521defabf30](https://user-images.githubusercontent.com/38676947/142747114-99c191bb-62e3-408b-91b0-97c3df6c14e8.png)

这种业务场景是经常会遇到的  官方模板里文本下拉的，但是都是基于已有数据的（逐一加数据集和视图，然后再条件匹配，在实际场景中会增加非常多的工作量）
![image](https://user-images.githubusercontent.com/38676947/142747140-23052ac1-12a1-4ddd-adb5-33c8bdaa2290.png)
![image](https://user-images.githubusercontent.com/38676947/142747148-218683cd-11ce-4d14-9237-35530cc500be.png)
![image](https://user-images.githubusercontent.com/38676947/142747157-2e1153fd-07ea-48ac-9bbf-7032c9eff3d6.png)
![image](https://user-images.githubusercontent.com/38676947/142747184-b6633fbb-647c-432f-9537-c016b0d36fb1.png)

**Comment by yayanpei** [comment]
感谢反馈，跨数据集的筛选已规划在 V1.6.0（2022年1月初发布） 版本，请多加关注。
