### ISSUE TITLE
[Feature] 创建数据源，连接不上的时候输入连接数据源信息会消失需要重输 使用体验不好

### ISSUE THREAD

**Issue by daiqingyao6238** [dataease/dataease#12316]
DataEase 版本:
v2.10

**请描述您的需求或者改进建议.**
创建数据源，连接不上的时候输入连接数据源信息会消失需要重输 使用体验不好

**Comment by xuwei-fit2cloud** [comment]
您好，如果连接不上数据源的话，应该会在当前页面提示错误，而不会重置连接信息，如下图所示：
![图片](https://github.com/user-attachments/assets/bfe3dcf2-8c2a-47c8-aba2-2c69f7c62e9f)

您能否截个图告知是何处会重置连接信息？

**Comment by daiqingyao6238** [comment]
在创建SQL SERVER 数据源时
![fb37fb76-bb55-4b4b-bfa7-27e593bfdc0b](https://github.com/user-attachments/assets/9c1e6c90-35a1-4979-8b8f-0dad5e2c3fd0)

**Comment by daiqingyao6238** [comment]
> 您好，如果连接不上数据源的话，应该会在当前页面提示错误，而不会重置连接信息，如下图所示： ![图片](https://private-user-images.githubusercontent.com/1892127/369784943-bfe3dcf2-8c2a-47c8-aba2-2c69f7c62e9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNDUyMjcsIm5iZiI6MTcyNzE0NDkyNywicGF0aCI6Ii8xODkyMTI3LzM2OTc4NDk0My1iZmUzZGNmMi04YzJhLTQ3YzgtYWJhMi0yYzY5ZjdjNjJlOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjRUMDIyODQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzA1YjQ0NmEzNmMwYmIxZTI0MDRkOWIxMGIzNzFiMGU4NDQ3NGY1NWI2ZjBiYjU1ZTJlNmM2MjgyZDJiOTA1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.N3V3mLKs-yNLdJQFuvoeFQZ0Cj1U10ZXjlp8Y928MAo)
> 
> 您能否截个图告知是何处会重置连接信息？

创建SQL SERVER数据源时提示connection reset

**Comment by fit2cloudrd** [comment]
数据源在创建的时候，只要必填信息都有填写，是可以进行保存的。
如果有必填信息未填写，如SQLServer的Schema，那整个填写是不会保存的。
