### ISSUE TITLE
[Bug] v1 系统管理 -> 任务列表加载不出来

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#12323]
**DataEase 版本**
v1.18.24

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 128.0.6613.139（正式版本） （64 位）

**Bug 描述**
定时任务比较多，且授权信息比较多的情况下，任务列表无法加载，如下图所示：
![d1a337b0e383c04a6aa034b3fd47861](https://github.com/user-attachments/assets/eeec8d8b-fa79-4bb4-aa0b-3a02ae05f0eb)

**优化思路**
1、当前定时任务的查询 SQL 如下所示：
`SELECT dataset_table.name as table_name, get_auths(dataset_table_task.table_id,'dataset', ${userId}) as
`privileges`,dataset_table_task.* , qrtz_triggers.NEXT_FIRE_TIME
FROM dataset_table_task
left join dataset_table on dataset_table.id=dataset_table_task.table_id
left join qrtz_triggers on dataset_table_task.id=qrtz_triggers.TRIGGER_NAME and qrtz_triggers.TRIGGER_STATE != 'PAUSED'
where 1=1
order by dataset_table_task.status desc
limit 10`

如上所述，数据量比较大的情况下，先全表执行完 get_auths 函数后，再排序效率很慢，可以优化成如下的写法，排序分页完取出数据后，再执行 get_auths 函数 ：
`select tmp.*,	get_auths ( tmp.table_id, 'dataset', ${userId}) AS `privileges`
from (  SELECT
	dataset_table.NAME AS table_name,
	dataset_table_task.*,
	qrtz_triggers.NEXT_FIRE_TIME 
FROM
	dataset_table_task
	LEFT JOIN dataset_table ON dataset_table.id = dataset_table_task.table_id
	LEFT JOIN qrtz_triggers ON dataset_table_task.id = qrtz_triggers.TRIGGER_NAME 
	AND qrtz_triggers.TRIGGER_STATE != 'PAUSED' 
WHERE
	1 = 1 
 ORDER BY	dataset_table_task.`status` DESC 
	LIMIT 10 ) tmp;
	`

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行优化；
