### ISSUE TITLE
[Feature]仪表板的时间可取消“时间格式”（或可配置），当前为必选字段（部分业务只需要到年月日）

### ISSUE THREAD

**Issue by geyesheng** [dataease/dataease#1232]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/38676947/142748061-066d0712-ed1f-446e-92cc-db52c8376f8c.png)
![image](https://user-images.githubusercontent.com/38676947/142748075-5739f25a-a086-4279-a6a0-5318bb73c609.png)

**Comment by yayanpei** [comment]
感谢反馈，您的建议非常好，我们会优先规划在优化清单中。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0版本已支持，请等待新版本发布
