### ISSUE TITLE
[Feature]国际化问题

### ISSUE THREAD

**Issue by LiuJian1216** [dataease/dataease#12322]
DataEase 版本:
V1

**请描述您的需求或者改进建议.**
1.明细表在英文的条件下，没有数据的提示是中文
<img width="1899" alt="836f330529ee5dd6649efcf35a8f31b" src="https://github.com/user-attachments/assets/e9489410-4fed-427b-9728-9d2c76a96fed">
2.仪表盘在英文的条件下创建公共链接，对方打开链接地址时显示的都是中文

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复如下：
1、我们修复一下，这里的提示国际化漏掉了。
2、显示语言和浏览器的默认语言一致，将浏览器的默认语言设置为英语，建议再清理一下浏览器缓存，应该就可以显示英语了。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，该提示是图库本身自带的，因此无法处理国际化。
