### ISSUE TITLE
[Feature]如果需知道统计数对应的明细无法获悉（当前跳转不支持，只支持外链和仪表板）

### ISSUE THREAD

**Issue by geyesheng** [dataease/dataease#1233]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/38676947/142748162-2867bbbb-d162-4302-b40c-550375893067.png)
![image](https://user-images.githubusercontent.com/38676947/142748184-69248803-347f-43f9-ac43-b60a3ad7f698.png)
![image](https://user-images.githubusercontent.com/38676947/142748240-1d89cc7d-6b29-4a30-bd81-08cb934109a2.png)
![image](https://user-images.githubusercontent.com/38676947/142748266-c8c54eef-d971-4d27-af1f-734870f471db.png)

**Comment by yayanpei** [comment]
感谢反馈，建议您先将表单放入仪表板中，然后设置跳转，跳转至该仪表板
