### ISSUE TITLE
[Feature] v2仪表盘刻度需要增加刻度值的格式化，目前只有标签的格式化，当他可视化但表盘数值不格式化时，会显得很丑

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12339]
DataEase 版本:
v2.10.0

**请描述您的需求或者改进建议.**
仪表盘刻度需要增加刻度值的格式化，目前只有标签的格式化，当他可视化但表盘数值不格式化时，会显得很丑

![8c26e23386c3a4c10786274c0e8fca1](https://github.com/user-attachments/assets/0c5a9285-7fdb-44d9-b33b-8e63eb8e1b71)
![afb3b6c5ab58b8f838892c8d40184de](https://github.com/user-attachments/assets/35048682-5a8a-4e34-8ba2-0da1f220ea48)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中优化一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
