### ISSUE TITLE
[Bug]v2 登陆页面点击登录之后没反应，无痕或者换浏览器都一样无反应，需要刷新，刷新之后直接进入页面

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#12332]
https://github.com/user-attachments/assets/0368a098-0a98-4aab-b748-c0060e60100c

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，方便的话看一下前端请求，在你点击登陆的时候请求发送状况；

**Comment by wolf-kingx** [comment]
视频大，不能上传，已发送私信。
