### ISSUE TITLE
[Bug] postgresql 数据使用汇总表时，小数数值指标降序排列时，使用查询组件后，空值会在前面，而 excel 数据时正常

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12337]
**DataEase 版本**
v2.9.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
google

**Bug 描述**
postgresql 数据使用汇总表时，小数数值指标升序排列时，空值会在前面，而 excel 数据时正常

**Bug 重现步骤(有截图更好)**
1.创建一个postgresql 数据源、数据集，维度为时间，准备一个数值指标a，书写其对应计算字段a1： a/10000
2.在汇总表加入a1
3.a1按降序排列
4.新建查询组件，查询时间（动态时间，选包含空值范围的时间），关联上述汇总表
5.选择查询时间，汇总表更新后，空值在上面，估计这个是因为把 pgsql 降序空值当成最大值了
用 excel 数据源正常。
另外，局部点击降序是可以的，但是刷新就失效了，这个很影响数据看板的展示。
<img width="224" alt="5d7a6ae36d9f9a4684100289adaa379" src="https://github.com/user-attachments/assets/24184989-d38a-47d5-be22-895c0ddcf582">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，这里是前端操控应该不会产生不同的结果；
![image](https://github.com/user-attachments/assets/481a3df6-815a-4470-9fe1-9f00813de410)

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
