### ISSUE TITLE
[Feature]建议添加针对仪表板、视图、数据集的版本管理功能

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#1234]
**请描述您的需求或者改进建议.**
现状：设计仪表板、视图的时候需要反复尝试，包括修改视图的样式、仪表板的布局，但是修改完成后无法回退到历史的样式。

远期建议：增加“版本管理”功能，详细记录操作过程日志，可方便回退到历史版本。

近期解决方案：新增视图、数据集的复制功能。

**Comment by yayanpei** [comment]
感谢反馈，该需求已经在规划中，方案还需要进一步确定。

**Comment by xuwei-fit2cloud** [comment]
该需求在当前1.x系列版本中还没有相关开发计划，我们会在2.0版本中考虑。
