### ISSUE TITLE
[Feature] tab 页签能否设置整体隐藏不需要体现两个tab的名称及空白位置

### ISSUE THREAD

**Issue by daiqingyao6238** [dataease/dataease#12342]
DataEase 版本:

v2.10.0
**请描述您的需求或者改进建议.**
这两个tab位置，能否整体隐藏掉呢？  就不需要体现两个tab的名称及空白位置。
![fe7bf7e9-e68c-432d-828c-2a54f79c73b4](https://github.com/user-attachments/assets/da65320f-98b0-4717-9c48-4ec77da4acf6)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，两个tab页隐藏掉，请问还需要切换吗？

**Comment by daiqingyao6238** [comment]
需要，就是切换支持设置隐藏tab那个空白区域

**Comment by daiqingyao6238** [comment]
> 感谢您的反馈，两个tab页隐藏掉，请问还需要切换吗？

需要，就是切换支持设置隐藏tab那个空白区域

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
