### ISSUE TITLE
[Feature] Dataease能否增加Gis离线地图的支持

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#12364]
DataEase 版本:
2.10

**请描述您的需求或者改进建议.**
Dataease能否增加Gis离线地图的支持，目前除了基础地图外，其他的地图都需要联网可以使用，内网环境没法使用地图。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论评估后再回复。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持离线地图。
