### ISSUE TITLE
[Bug] V1 版本两个仪表板跳转，分享给其他用户时无权限查看跳转的面板

### ISSUE THREAD

**Issue by lanyugod** [dataease/dataease#12366]
**DataEase 版本**
V1.18.24

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
管理员用户创建了 A和 B两个面板，点击 A 面板的属性跳转到 B展示对应的信息，当分享给其他用户时，在分享界面都可以看到 A和 B 页面，并且都可以进行单独查看相关数据。但是在 A面板点击跳转到 B面板时，会提示无权限，需要由管理员开通权限。

**Bug 重现步骤(有截图更好)**
(创建信息)
1.
<img width="1846" alt="image" src="https://github.com/user-attachments/assets/8dda9a26-b27a-4734-b36f-057c256240e4">

2.
<img width="1460" alt="image" src="https://github.com/user-attachments/assets/19cb96d1-c2b9-45b8-94e6-31632f720bf2">

(被授权用户界面信息)
3.
<img width="1266" alt="image" src="https://github.com/user-attachments/assets/4ecd7a67-7cd8-4920-882c-c7dfc0c98c7e">

<img width="1939" alt="image" src="https://github.com/user-attachments/assets/d1f30127-2f13-44e4-ae38-beeb77f10649">
4.
跳转后打开新的 tab页进行展示：提示无权限
<img width="1732" alt="image" src="https://github.com/user-attachments/assets/f8a3bae9-c1c4-4d82-b9e3-1ba65dc883c9">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行修复；

**Comment by maninhill** [comment]
v1 版本目前进入维护阶段，仅修复安全漏洞相关问题。
