### ISSUE TITLE
[Feature]条形图进度条辅助线支持在同一个辅助线作数值匹配

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12363]
DataEase 版本:
v2.10.0

**请描述您的需求或者改进建议.**
条形图进度条辅助线支持在同一个辅助线作数值匹配，比如 =1.5 倍的 a

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持，建议在数据集中对字段的数学计算进行处理。
