### ISSUE TITLE
[Feature]建议支持使用图片作为视图背景

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#1236]
**请描述您的需求或者改进建议.**
背景：视图的背景只能使用纯色，目前只能通过调视图背景的整透明度在仪表板中使用图片来组合，效率较低。
![image](https://user-images.githubusercontent.com/40846859/142756149-9de1e134-362b-438d-867f-6a8565645bc2.png)

建议：视图支持使用图片作为背景。

**Comment by yayanpei** [comment]
感谢反馈，建议您把视图放置在背景图的上层（调整视图层级），然后调整背景的不透明度来实现。
