### ISSUE TITLE
[Feature] 数据大屏支持批量操作

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#12368]
DataEase 版本:
2.10.0

**请描述您的需求或者改进建议.**
数据大屏支持批量操作

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，可参考下图所示进行操作，先批量选中画布中的组件，然后在属性设置窗口进行设置。
![image](https://github.com/user-attachments/assets/bfccd333-20d3-48a6-8e66-51e184e31554)
