### ISSUE TITLE
[Bug]添加同步任务，报错No enum constant io.dataease.xpack.sync.core.datasource.datatype.type.MySqlType.BIGINT UNSIGNED

### ISSUE THREAD

**Issue by shaohuayangfit2** [dataease/dataease#12367]
**DataEase 版本**
2.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
很新

**Bug 描述**
添加同步任务，存储mysql的数据，到

**Bug 重现步骤(有截图更好)**
![4](https://github.com/user-attachments/assets/20c085ab-71ba-4125-ab60-947dc971954d)
![5](https://github.com/user-attachments/assets/a0507b75-17be-464b-96e8-39123c872c3d)

**Comment by shaohuayangfit2** [comment]
[saledetailforsup字段.json](https://github.com/user-attachments/files/17092330/saledetailforsup.json)
[saleorder字段.json](https://github.com/user-attachments/files/17092331/saleorder.json)
![6](https://github.com/user-attachments/assets/dbfb7274-23d5-4f3d-8d28-9d90a8f64a23)
mysql：阿里云数据库，暂不确认版本；
doris：doris-fe:v2.1.5 和 doris-be:v2.1.5；

**Comment by shaohuayangfit2** [comment]
阿里云 Mysql 8.0
![12401727077646_ pic](https://github.com/user-attachments/assets/621d3935-498d-4824-953f-7c1164468b0b)

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
