### ISSUE TITLE
[Bug]同一个数据、同一个透视表 平铺展示的 正常 树形展示的 就有问题

### ISSUE THREAD

**Issue by yangdun001** [dataease/dataease#12374]
**DataEase 版本**
2.10

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**
Google

**Bug 描述**
同一个数据、同一个透视表 平铺展示的 正常  树形展示的 就有问题

**Bug 重现步骤(有截图更好)**
![微信图片_20240923134446](https://github.com/user-attachments/assets/719b4859-c1e1-4c90-a69a-09c086c87ab7)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，方便细化一下你的操作步骤我们复现一下吗？
![image](https://github.com/user-attachments/assets/f7d4b1f3-bfc9-4a90-aa5e-f4ab8a92ec94)

**Comment by BBchicken-9527** [comment]
请问你是不是对字段进行了自定义设置？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
