### ISSUE TITLE
[Feature]建议雷达图可填充颜色

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#1237]
**请描述您的需求或者改进建议.**
背景：如下图，各项指标突出效果不明显，并且不能在顶点添加icon
![image](https://user-images.githubusercontent.com/40846859/142756290-960b04a9-ff50-4012-add7-8ebd04686f70.png)
建议：雷达图的连接线内区域可填充，实现如以下这种效果
![image](https://user-images.githubusercontent.com/40846859/142756331-f17cb30e-067b-4294-a4a1-7606a3ddfcac.png)
![image](https://user-images.githubusercontent.com/40846859/142756369-77ba477d-c359-4bfd-943f-a6ad07f94e3e.png)

**Comment by yayanpei** [comment]
感谢反馈，我们规划在后面的版本优化一下。

**Comment by xuwei-fit2cloud** [comment]
短期内还不会支持，暂时先关闭。
