### ISSUE TITLE
[Bug]受联动的图表b（a图表配置联动b）如果用了快速计算（同比/环比）会有些问题，查询不到对应的数据

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12370]
**DataEase 版本**
v2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
受联动的图表b（a图表配置联动b）如果用了快速计算（同比/环比）会有些问题，查询不到对应的数据

**Bug 重现步骤(有截图更好)**
1.做一个数据集，包含时间维度、一个数值指标a，做一个折线图和统计图，折线图联动统计图（反过来也可以）
2.让受联动的图表对a做同比（环比也可以试一下）
3.点击联动的某个值，查不到对应数据

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
