### ISSUE TITLE
[Bug]符号地图 更新数据，报错：Cannot invoke \"io.dataease.extensions.view.dto.ChartViewDTO.getIsExcelExport()\" because \"view\" is null

### ISSUE THREAD

**Issue by shaohuayangfit2** [dataease/dataease#12384]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
很新

**Bug 描述**
配置符号地图，在2.10.0上可以，同样数据，同样高得key，配置后，更新数据报错；
code: 50002
data: null
msg: "Cannot invoke \"io.dataease.extensions.view.dto.ChartViewDTO.getIsExcelExport()\" because \"view\" is null"

**Bug 重现步骤(有截图更好)**
1.
2.
3.
![81727082641_
![39151727082496_ pic](https://github.com/user-attachments/assets/015bb702-1eb2-4a40-9d7e-6fb580bd12ee)
 pic](https://github.com/user-attachments/assets/a5be05e4-8f77-4091-8e2e-b8264d09c5dc)
![39161727082496_ pic](https://github.com/user-attachments/assets/97815d8c-1f71-4d07-87d6-6ebc0f558e81)

**Comment by shaohuayangfit2** [comment]
![39151727082496_ pic](https://github.com/user-attachments/assets/379057b5-730b-4d77-b49f-68fa262cc946)

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
