### ISSUE TITLE
[Feature]媒体条件显示

### ISSUE THREAD

**Issue by JOJO30317** [dataease/dataease#12380]
DataEase 版本:
V2.10.0

**请描述您的需求或者改进建议.**
多个单位LOGO不同，但展示内容一样。
能否插入多个LOGO，根据Ticket不同，显示不同的LOGO。

**Comment by xuwei-fit2cloud** [comment]
您这里说的Logo，是仪表板或者大屏中的图片吗？

**Comment by JOJO30317** [comment]
> 您这里说的Logo，是仪表板或者大屏中的图片吗？

是的

**Comment by JOJO30317** [comment]
咋没有反馈了？

**Comment by xuwei-fit2cloud** [comment]
可以试试刚刚发布的v2.10.2版本，里面有新增的图片组组件，可以通过外部参数的方式设置图片组的字段值，从而达到您要的效果。

**Comment by JOJO30317** [comment]
> 可以试试刚刚发布的v2.10.2版本，里面有新增的图片组组件，可以通过外部参数的方式设置图片组的字段值，从而达到您要的效果。

配置了图片组，但外部参数选不到图片组，具体如何操作？
