### ISSUE TITLE
[Feature]建议丰富数据集数据处理能力

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#1238]
**请描述您的需求或者改进建议.**
背景：现阶段无法在数据集对数据进行如“保留小数点后几位”、“单位换算”等
![image](https://user-images.githubusercontent.com/40846859/142756478-d441632b-dd45-4a74-acf5-c0bc0d0a6407.png)
建议：新增保留小数点后几位、单位换算、日期转换等

**Comment by yayanpei** [comment]
感谢反馈，已经规划在需求中。
