### ISSUE TITLE
[Feature]建议丰富“指标卡”视图的功能

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#1239]
**请描述您的需求或者改进建议.**
背景：制作仪表板时希望实现指标卡中的数值低于阈值的时候显示红色，高于阈值的时候显示绿色
建议：建议丰富指标卡的功能，在样式中添加条件判断功能，根据设定的值动态跳转文字的颜色

**Comment by Andyguo5891** [comment]
这个需求确实是常见的场景

**Comment by yayanpei** [comment]
感谢反馈，阈值的设置及使用，已经在规划中，后期会支持多种图表类型阈值的设置（如指标卡、柱形图、折线图等等），请多加关注。
