### ISSUE TITLE
[Feature]柱线组合图增加子类别维度排序和指标排序

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#12398]
DataEase 版本:
2.10.1

**请描述您的需求或者改进建议.**
![image](https://github.com/user-attachments/assets/e1f57696-4d7c-49da-855a-e02e34db3ecc)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，组合图是两个图层叠加在一起的，因此需要根据共同的维度去排序，除此之外的排序字段支持不了。
