### ISSUE TITLE
[Bug]v2.10.1版本，clickhouse数据源，sql数据集，使用union all，如果数据中包含null报错

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#12403]
![dc71ed9359769b14d1d9c80adf5d677](https://github.com/user-attachments/assets/32ca9e8f-040c-48b1-8e0f-112c61de0ba9)

![fcb08df4ab44f2bf7ac9149f0d9105b](https://github.com/user-attachments/assets/a0119580-0b95-4ccf-8757-fd78e2b1ab4a)

**Comment by BBchicken-9527** [comment]
<img width="1022" alt="image" src="https://github.com/user-attachments/assets/84f08cf4-1af0-437d-b82a-9c1b1b1420a5">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们尝试通过calcite处理一下；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
