### ISSUE TITLE
[Bug]堆叠条形图增加记录数排序后提醒“获取数据异常，如有疑问联系管理员”

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#12407]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
堆叠条形图增加记录数排序后提醒“获取数据异常，如有疑问联系管理员”

**Bug 重现步骤(有截图更好)**
1.基于之前已有的堆叠条形图，更新版本；
2.仪表板中的堆叠条形图提醒：”获取数据异常，如有疑问联系管理员“。其他仪表板使用同样数据源没有报错！
3.删除按照记录数排序，数据展示正常，去掉堆叠项，数据展示正常。

**Comment by BBchicken-9527** [comment]
感谢反馈，后台异常日志是什么呢？还有需要确定你升上来之前的版本；

**Comment by xueqidove** [comment]
> 感谢反馈，后台异常日志是什么呢？还有需要确定你升上来之前的版本；

升级之前是2.10版本，后台日志未获取过。

**Comment by xueqidove** [comment]
> > 感谢反馈，后台异常日志是什么呢？还有需要确定你升上来之前的版本；
> 
> 升级之前是2.10版本，后台日志未获取过。

再补充下，即使是新建一样会报错哦。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
