### ISSUE TITLE
[Bug]【图表】Antv 图库的组合图周同比展示有问题

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#12401]
**DataEase 版本**
v1.18.24

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
Antv 图库的组合图周同比展示有问题
![image](https://github.com/user-attachments/assets/011312fa-3b36-4097-8c8c-a9d1df81fb72)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；
