### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by lucawoo** [dataease/dataease#12410]
DataEase 版本: 2.10.0

**请描述您的需求或者改进建议.**
1.  透视图增加横向滚动条，现在要点开放大才能滚动，希望在页面上也添加横向滚动
2. 仪表盘保存经常出现如下现象(白色蒙层)卡住
![image](https://github.com/user-attachments/assets/b054c1ed-2015-4334-a952-b1a8a6c82047)
3. 数据集字段变更后，即时重新配置好也会报数据错误，但是复制图表出来未做任何修改就能正常显示

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复如下：
1、透视表有横向滚动条，鼠标悬浮上去之后是可以滚动的。
2、保存时出现的白色蒙层，并不是卡住，是提示用户正在保存中。
3、这边没有复现，请问数据集做了什么变更？重新配置好字段后，图表刷新了吗？

**Comment by xuwei-fit2cloud** [comment]
由于长时间无反馈，暂时先关闭该问题。
