### ISSUE TITLE
[Bug]Excel数据源（表头没有修改）替换后，通过数据下拉框设计的仪表板无法更新

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#1241]
**DataEase 版本**
1.14.1

**浏览器版本**
Chrome 95.0.4638.69

**Bug 描述**
Excel数据集执行替换（表头没有变化）操作后，视图更新了，但之前在仪表板中通过数据下拉框设计的仪表板，无法显示，需要先删除，然后再拖拽添加。

建议：如果表头没有变化，是否可以自动更新？

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/46042812/142799033-afd286ef-711b-4d2b-9e0e-5bee5bbad5f8.png)
2.
![image](https://user-images.githubusercontent.com/46042812/142799058-06266739-9b60-492b-b72c-050d11e283dc.png)
3.
![image](https://user-images.githubusercontent.com/46042812/142799083-34c00c6a-eafb-4be4-9c5b-a74c4b093660.png)

**Comment by yayanpei** [comment]
感谢反馈，该优化在下月初的 V1.5.0 版本会进行优化，请多加关注。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 版本已支持，请等待新版本发布。
