### ISSUE TITLE
[Feature]阙值告警数值指标需要支持当前指标的倍数的计算

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12418]
DataEase 版本:

**请描述您的需求或者改进建议.**
阙值告警需要支持当前指标的倍数。目前，数值类型的告警只有最大最小值和平均值，不灵活，需要增加根据选中的指标的几倍来告警
![image](https://github.com/user-attachments/assets/70625262-7752-4ea5-b3db-3206dbfa8d5e)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，数学计算建议在数据集中计算，图表主要用于展示数据集数据。
