### ISSUE TITLE
[Feature]仪表板名称可以自定义排序并保留排序规则

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#12415]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**

仪表板名称可以自定义排序并保留排序规则:
自定义排序：用户习惯 1，2，3，4....，11，12 开头命名仪表板，如果顺序排序，会出现2 会大于 11，仪表板位置错乱；
保留排序规则：大部分使用场景是管理员配置好排序规则，其他用户登录后显示管理员的排序规则，无需手动排序，用户自己可以做临时排序查看。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈。
我们认为排序是个性化的设置，所以每个人有自己的一套排序设置，暂不考虑支持使用管理员配置好的排序；
对于文字来说，11和2的比较，并不是数字的比较，所以会出现您所描述的情况，建议在个位数前加上0，如01/02等。
