### ISSUE TITLE
[Bug]通过飞书应用打开 DataEase 加载慢

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#12411]
**DataEase 版本**
v2.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
飞书

**Bug 描述**
通过飞书应用打开 DataEase 加载慢，出现进度条多次加载，等待数秒甚至 10 几秒才能进入。希望优化。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by maninhill** [comment]
是 2.10.1 吗？

**Comment by mfanoffice** [comment]
> 是 2.10.1 吗？

是的。

**Comment by BBchicken-9527** [comment]
感谢反馈，用户首次登陆因为三方平台存在之前登陆的token所以会经过token失效-退出-进入登陆界面-应用自动登录等多个过程，这个过程中会出现多次的页面重定向，但后续如果再次登陆则会很快非常快的；

**Comment by xuwei-fit2cloud** [comment]
暂无调整计划。
