### ISSUE TITLE
[Bug] MySQL 数据库设置了 sql_require_primary_key = 1，导致 Excel 数据集创建失败

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [dataease/dataease#12429]
**DataEase 版本**
2.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
使用公司默认的数据库服务，由于数据库的设置问题，设置了建表必须包含主键，导致 Excel 数据集创建失败。
如下图：
![image](https://github.com/user-attachments/assets/6ae0dc5a-ae12-421f-86b6-09d9e1d700ab)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前在世不支持的；
