### ISSUE TITLE
[Bug]用户管理执行上一页、下一页操作，有时会导致控件消失

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#1242]
**DataEase 版本**
1.14.1

**浏览器版本**
chrome 95.0.4638.69

**Bug 描述**
用户管理执行上一页、下一页操作，有时会导致控件消失

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/46042812/142799764-9d5347db-470d-4c5d-a6b0-2ead59b06146.png)

**Comment by tjlygdx** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 已修复，请等待新版本发布
