### ISSUE TITLE
[Bug]Mysql数据源对接后数据表中的时间戳字段识别为指标+数值类型

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#12424]
**DataEase 版本**
v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌

**Bug 描述**
对接Mysql数据源，从数据源中获取数据表，数据表中的Create timestamp字段在数据库中为时间戳，但是DataEase对接后识别出来的统一为数值类型，且放在了指标中，这个是否可以直接识别为时间且放在维度类型中。

**Bug 重现步骤(有截图更好)**
1.通过DataEase对接MeterSphere的Mysql数据源，添加数据集，选择数据源中的数据表user
2.刷新数据，展示Create timestamp字段，默认为数值+指标

**Comment by BBchicken-9527** [comment]
感谢反馈，我们讨论一下；

**Comment by BBchicken-9527** [comment]
感谢反馈，如果您的字段类型为bigint类型，我们这边不太好判断你的这个字段到底是时间戳还是只是个较大的数值；
