### ISSUE TITLE
[Bug]投屏分辨率不一致时DE 界面的字体放大比例不一样

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#12422]
**DataEase 版本**
v2.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
笔记本投屏时，如果大屏幕分辨率比较高，仪表板左侧的字体变小，仪表板左侧目录大小能否不受分辨率影响？
![图片](https://github.com/user-attachments/assets/4bb38f41-8c3a-42a2-9888-eadedf6be07d)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，暂时没有考虑支持平台内部目录导航条等支持自适应；
