### ISSUE TITLE
[Feature]辅助线动态值增加是选择的指标的几倍。

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12437]
DataEase 版本:

**请描述您的需求或者改进建议.**
辅助线动态值增加是选择的指标的几倍。比如下面的单价，设置为倍数，然后倍数填1.5，为选择指标的1.5倍
![image](https://github.com/user-attachments/assets/17343dd5-d3e4-49d9-a394-0a218b143397)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，指标的数据计算建议在数据集中完成后，图表主要用于展示数据集中的数据。
