### ISSUE TITLE
[Feature]查询组件筛选器可以添加跳转，可以跳转到另一个仪表盘，然后和某个筛选器关联起来，这样会方便很多，因为不仅可以筛某一天，还可以筛选年和月或者范围

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12445]
DataEase 版本:
v2.10.0

**请描述您的需求或者改进建议.**
目前跳转只能选一个值，对于范围值的跳转还是有所欠缺，查询组件筛选器需要添加跳转，可以跳转到另一个仪表板，然后和某个筛选器关联起来，这样会方便很多，因为不仅可以筛某一天，还可以筛选年和月或者范围。
具体场景之一就是日期列不在汇总表里，它只作为一个汇总表的筛选条件，然后想从汇总表跳转到明细表并且筛选日期，但这种情况下汇总表可以设置的源字段里是不包含日期的。
或者想要筛选多个值的情况。

**Comment by zhainanshidai** [comment]
或者考虑新增组件

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，暂时没有计划支持查询组件的跳转。建议通过图表跳转，关联目标仪表板的查询组件。
