### ISSUE TITLE
[Bug]v2.10.1 数据大屏 两个图表之前切换时，标签显示BUG

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#12441]
1 选择对称条形图，随便放点数据
![image](https://github.com/user-attachments/assets/6128ca68-0059-4cff-b145-181ac4ffc0ea)

2 切换到柱状图，打开标签
![image](https://github.com/user-attachments/assets/20989b64-4ddc-4aa5-b784-64fd183e650a)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行优化；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
