### ISSUE TITLE
[Feature]富文本表格列属性改为中文显示

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#12468]
DataEase 版本:
2.10.1

**请描述您的需求或者改进建议.**
![image](https://github.com/user-attachments/assets/fa34aa9a-7aae-47bb-ac50-aebfeae8f503)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们修复一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
