### ISSUE TITLE
[Bug]富文本组件表格列宽调整失效

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#12467]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**Bug 描述**
富文本组件表格列宽调整失效

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/51235ac5-142b-44e9-a804-62643ac07236)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
