### ISSUE TITLE
[Feature]表格可以根据未展示字段设置条件样式

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#12460]
DataEase 版本:
2.10.0

**请描述您的需求或者改进建议.**
原始数据中有性别一列，展示使用字段中没有，只展示如下字段
![f52b5d326f007e693ee90c4f40dc216](https://github.com/user-attachments/assets/23490236-af3b-4c87-aa93-cc9a7ca4fb91)

展示字段中，想根据性别字段给添加颜色效果展示，比如男生信息的底色是蓝色，女生信息的底色是粉色
![7f6d7ae7ea63cb4b1bbac63ebfdd142](https://github.com/user-attachments/assets/b89e474f-83cf-405f-9ae1-661a13a1df09)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持，近期会增加字段的隐藏，建议将字段拖拽至表格中，然后隐藏字段。

**Comment by hcff2c** [comment]
隐藏了好像不行，是根据性别字段去判断然后将整行记录背景标红，然后性别字段不展示
