### ISSUE TITLE
[Feature]进度条视图标签除了显示比例，也可以把实际数值指标显示出来

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#12469]
DataEase 版本:
2.10.1

**请描述您的需求或者改进建议.**
![image](https://github.com/user-attachments/assets/3894c76f-ac5d-417a-a8a8-4372236afa4e)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
