### ISSUE TITLE
[Bug]仪表盘修改仪表盘风格后查询组件样式变化

### ISSUE THREAD

**Issue by jacksonhou** [dataease/dataease#12470]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
在线试用

**浏览器版本**
chrome

**Bug 描述**
仪表盘编辑时，修改仪表盘风格后查询组件样式变化
![微信截图_20240925210503](https://github.com/user-attachments/assets/f97811e8-9bd6-407f-8bab-3d4eafe375d2)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，不是很理解你说的意思，方便补充一下你想表达的问题嘛？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
