### ISSUE TITLE
[Bug] 这些Xpack的前端请求接口能不能去掉？

### ISSUE THREAD

**Issue by meimosor** [dataease/dataease#12477]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome最新

**Bug 描述**
每次页面刷新都会调用/xpackComponent/content, 影响页面加载效率，如果社区版没有这个接口，那前端可否把这块去掉？

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/7722ed75-1d0f-499b-9290-18c7e566fa43)

2.页面刷新
3.一堆接口报错，如上图

**Comment by maninhill** [comment]
已解决，待发布。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
