### ISSUE TITLE
[Feature]tab组件标签可以切换位置，有移到前面或者移到后面的选项

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#12487]
DataEase 版本:
2.10.1

**请描述您的需求或者改进建议.**
![image](https://github.com/user-attachments/assets/87bf7865-3523-49d4-8e8f-44218b7fea2e)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，如下图所示，可以调整tab页的位置。
![image](https://github.com/user-attachments/assets/21f4e3fc-13c4-4471-aebe-235a889d8a6f)

**Comment by hcff2c** [comment]
数据大屏，不是仪表板

**Comment by yayanpei-fit2cloud** [comment]
好的，已加入需求池中。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
