### ISSUE TITLE
[Feature] 维度指标拖拽优化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#12489]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
拖拽维度指标字段时，希望可以按照鼠标的落点放置字段，现在默认都是放置在最后，需要再次收手动调整，在表格类等字段比较多的图标上体验不是很好。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中优化一下。

**Comment by fit2cloudrd** [comment]
暂时无法实现。
