### ISSUE TITLE
[Bug]时间格式数据处理问题

### ISSUE THREAD

**Issue by zyyfit** [dataease/dataease#1248]
**DataEase 版本**
1.4.0

**浏览器版本**
chrome

**Bug 描述**
创建excel数据集，有处理过的日期格式数据，在创建的时候显示的是一串数字，保存后显示也不对

**Bug 重现步骤(有截图更好)**
1. 这是上传文件的预览界面
![图片](https://user-images.githubusercontent.com/73461316/142979139-beda86ee-47ed-4e26-a7c3-6de3c45942f2.png)

2. 这是保存后的预览界面
![图片](https://user-images.githubusercontent.com/73461316/142979209-77d3871a-2786-496c-988b-51f5087ad293.png)

这是Excel文
[各种日期及其他处理123.xlsx](https://github.com/dataease/dataease/files/7586107/123.xlsx)
件

**Comment by tjlygdx** [comment]
感谢反馈，我们处理一下。

**Comment by qianye101** [comment]
您好，我对这个issue感兴趣，请问可以由我来实现这个需求吗？非常感谢。
