### ISSUE TITLE
[Feature]显示名称字符长度限制放开，因为英文名称会占据很长

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#12485]
DataEase 版本:
2.10.1

**请描述您的需求或者改进建议.**
![1727321286820](https://github.com/user-attachments/assets/7ce01b18-8164-4399-90d8-5fad4877653e)
<img width="179" alt="9a3ddb5cb6921ef4ea00671cbc6769f" src="https://github.com/user-attachments/assets/51f325fc-af08-4108-8865-965b78af8b4a">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们把长度限制扩大一些。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
