### ISSUE TITLE
[Bug]pgsql 时间范围查询 utc（+08） 的数据会出现转换异常，出现不是当天的数据

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12488]
**DataEase 版本**
v2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.pg sql下  时间列：2024-09-20 18:06:45+08   2024-09-19 15:42:27+08等，查询组件时间范围，查询20240920时，会出现异常，查到19号的数据
![image](https://github.com/user-attachments/assets/362835f5-a9fd-42c9-ae25-65aa391aecda)

2.解析sql：
WHERE
            FLOOR(
                EXTRACT(
                    epoch
                    FROM
                        (
                            (
                                "t_a_0"."f_69bf028bc08a5e2b" - TIMESTAMP '1970-01-01 00:00:00'
                            )
                        )
                ) * 1000 - 0
            ) BETWEEN '1726761600000' AND '1726847999000'
本地时间：
1726761600000    2024-09-20 00:00:00
1726847999000 2024-09-20 23:59:59
utc时间：
2024-09-19 16:00:00
2024-09-20 15:59:59
解析后发现可能是pgsql解析utc的问题

3.excel下测试正常

**Comment by BBchicken-9527** [comment]
感谢反馈，最新版本修复了相关问题，可以升级新版本体验；
