### ISSUE TITLE
[Feature]给仪表板中图表添加辅助线（使用动态值），发现不能给计算结果指定数值格式（例如:不保留小数位数或只保留N位小数）是否可以增加相应配置项讷

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12492]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
给仪表板中图表添加辅助线（使用动态值），发现不能给计算结果指定数值格式（例如:不保留小数位数或只保留N位小数）是否可以增加相应配置项讷

**Comment by xuwei-fit2cloud** [comment]
可以试试跳转纵轴的数值格式，辅助线的数值格式是跟随对应轴的数值格式的。

**Comment by li-rong-gz** [comment]
问题 已解决感谢。
