### ISSUE TITLE
[Feature]在使用过程中发现不能对仪表板中图表钻取/维度字段排序，图表数据显示结果混乱，例如:下图车间顺序显示是乱的。 下钻能否支持加排序讷

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12491]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
在使用过程中发现不能对仪表板中图表钻取/维度字段排序，图表数据显示结果混乱，例如:下图车间顺序显示是乱的。
下钻能否加排序讷
![image](https://github.com/user-attachments/assets/57c3e8a8-6ce6-4da8-a8ac-656a5c2953d0)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已经在v2.10.2-lts版本的优化清单中。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
