### ISSUE TITLE
[Feature]希望可以增加指标计算功能

### ISSUE THREAD

**Issue by fitchibing** [dataease/dataease#125]
1、最基础的数字类型指标的加减乘除；
2、多个指标列相互之间的计算；
3、字符串类型指标的substring等。

**Comment by xuwei-fit2cloud** [comment]
感谢您的建议，我们内部先讨论一下相关功能的设计。

**Comment by wangyw1863** [comment]
数据透视表的计算项和计算字段需求

**Comment by xuwei-fit2cloud** [comment]
v1.2.0 支持计算字段功能，可以支持常见计算公式。
