### ISSUE TITLE
[Bug]仪表板编辑-矩阵分布方式，添加过滤组建-取消添加，占位不会消失

### ISSUE THREAD

**Issue by zyyfit** [dataease/dataease#1250]
**DataEase 版本**
1.4.0

**浏览器版本**
chrome

**Bug 描述**
仪表板编辑-矩阵分布方式，添加过滤组建-取消添加，占位不会消失

**Bug 重现步骤(有截图更好)**
1.添加视图、文字等组件
2.添加过滤组件，拖动到已添加的组件上方，在弹出选择过滤条件时，关掉弹窗（也就是不真正的添加过滤组件）

此时过滤组件的占位不会消失
![图片](https://user-images.githubusercontent.com/73461316/142988588-52fa163f-3d30-41bd-a16a-1ad7f712f243.png)

**Comment by tjlygdx** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 已修复
