### ISSUE TITLE
[Bug] api数据源，无法解析过大数字；

### ISSUE THREAD

**Issue by shaohuayangfit2** [dataease/dataease#12507]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
很新

**Bug 描述**
添加API数据源：
1，api，在数据源时，无法解析过大金额，文本格式也异常，在数据源的数据预览时，直接转变为科学计数了
2，api，在数据源预览时能看到数据，保存后，到数据集，就看不到数据了；查看数据库里表，字段也是null；

**Bug 重现步骤(有截图更好)**
1.
2.
3.
![111](https://github.com/user-attachments/assets/34505b39-0052-42fb-ae4f-561ff60ffe22)

**Comment by xuwei-fit2cloud** [comment]
API数据源添加数据表时，会将字段类型默认设置为文本类型，不会存在转成科学计数法的问题，请检查API返回数据本身是否存在null和科学计数。
