### ISSUE TITLE
[Bug]矩阵模式两个时钟放在一起会叠加

### ISSUE THREAD

**Issue by BBchicken-9527** [dataease/dataease#1251]
**DataEase 版本**

**浏览器版本**
谷歌

**Bug 描述**
矩阵模式两个时钟放在一起会叠加

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/84372766/142993403-907f462b-1617-481f-a13d-0beb9e62474b.png)

1.
2.
3.

**Comment by tjlygdx** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 已修复，请等待新版本发布
