### ISSUE TITLE
[Bug]v2.10.1 数据大屏在编辑的时候显示和全屏预览大屏的时候显示不一致

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#12519]
编辑时：文字和标题都没重合
![image](https://github.com/user-attachments/assets/1262cc3c-cc08-4404-8503-fe94ae96c2ac)
全屏看的时候，标题的样式都变了
![image](https://github.com/user-attachments/assets/66743e3a-5685-4b62-b23c-181dec6f87b4)

数据大屏不会自适应，正常来说应该不会出现这样的问题吧。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，先暂时过关闭；
