### ISSUE TITLE
[Bug]数据集，clickhouse 数据集文本转数值报错。

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#12516]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
使用clickhouse 数据源，新建数据集时，clickhouse 表的某个字段为文本且可以为空，在数据集批量管理时候，将文本改为数值时候报错如截图，这个需要处理一下，使用 cast 转换会出现问题。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/2081eaad-7257-4da7-b58d-4a62d9aeff0b)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，cast在ck中是会提示异常的，如果字段存在null的情况下，如果更换toint32这种可能虽然能解决null的问题但无法处理空字符串，但涉及改动可能会影响到其他源的处理，所以经我们讨论暂时不对此处进行优化；
