### ISSUE TITLE
[Bug]v2.10.0 中，sqlserver2016 左关联数据集时，在图表的结果展示选择15时降序排序出错

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12521]
**DataEase 版本**
v2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
v2.10.0 中，sqlserver2016 左关联数据集时，在图表的结果展示选择15时降序排序出错

**Bug 重现步骤(有截图更好)**
1.做一个非跨源非跨库左关联 sqlserver2016 数据集
2.做一个汇总表，降序指标选择结果展示全部，正常：
![企业微信截图_17274188497409](https://github.com/user-attachments/assets/174a3392-2005-40c4-a4d7-3465d612bf6b)

3.选择15，更新，排序错误：
![企业微信截图_17274188001386](https://github.com/user-attachments/assets/c07be6de-4639-491e-87de-6acc0e436c54)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们确认一下；
