### ISSUE TITLE
[Bug]横向堆叠柱状图设置排序后图表不显示

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#12523]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**

横向堆叠柱状图设置排序后图表不显示
<img width="457" alt="image" src="https://github.com/user-attachments/assets/fc2e102c-fc59-4b33-963c-257b6a10feed">
<img width="446" alt="image" src="https://github.com/user-attachments/assets/ae2e7d53-2f42-45ed-9901-7ffa1fff3954">

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，目前正在修复中，将会在下个版本上线；
