### ISSUE TITLE
[Bug]点击图表自动跳到上一个位置

### ISSUE THREAD

**Issue by JOJO30317** [dataease/dataease#12530]
**DataEase 版本**
V2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome版本 108.0.5359.95（正式版本） （64 位）

**Bug 描述**
某个仪表板，编辑界面，创建新图表，复制图表，距离顶部位置的长度，超过一定长度时，点击此图表，会自动往上跳一个位置；

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，不是很理解你说的意思，距离顶部位置的长度超过一定长度时画板高度吗？方便的话可以详细描述一下吗？如果你认为文字不好描述受累录制视频或截图均可；

**Comment by JOJO30317** [comment]
刚刚查看问题已经不存在了，但当时有录频，当时重复进入编辑问题仍然存在：
https://github.com/user-attachments/assets/f8dabe25-25e9-4f0b-ac9d-f28fece5623b

**Comment by BBchicken-9527** [comment]
感谢反馈，我这边看没有这个问题，你那边还能复现吗？看着像是点击图表的时候位置定位的问题，你当时在制作图表的时候是否客户端内存存在消耗过大的情况？

**Comment by JOJO30317** [comment]
> 感谢反馈，我这边看没有这个问题，你那边还能复现吗？看着像是点击图表的时候位置定位的问题，你当时在制作图表的时候是否客户端内存存在消耗过大的情况？

那我后续再关注下，如果出现异常，客户端内存情况吧

**Comment by BBchicken-9527** [comment]
好的，如果再有问题，可以继续打开问题或者通知我们的小伙伴，我们会尽可能的帮你进行处理；
