### ISSUE TITLE
[Feature]希望热力图可以新增一个标签自动，用于展示标签名称

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#12532]
DataEase 版本:
v2.10.0

**请描述您的需求或者改进建议.**
![dd3591892bcfa8a8d837bed565a48bf](https://github.com/user-attachments/assets/da260053-1a30-44a4-9deb-9f021ac03e36)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请问标签名称指？

**Comment by shimengqiao** [comment]
就是还会有一个字段是设备的名称，现在的值展示就是指标，希望可以再定义一个字段来展示图标的标签名称
![企业微信截图_17276638318214](https://github.com/user-attachments/assets/52674042-8208-4fca-b845-f4ccdfcaae92)

**Comment by yayanpei-fit2cloud** [comment]
图表中的维度，要参与图表的聚合，会影响图表最终的展示结果。
