### ISSUE TITLE
玫瑰图内容聚集

### ISSUE THREAD

**Issue by scholar-ye** [dataease/dataease#12534]
DataEase 版本:2.10

**请描述您的需求或者改进建议.**

以前V1的玫瑰图数据多也能正常展示，现在V2.10都聚集在一起了，能否使用以前的玫瑰图，饼图也是类似。
![image](https://github.com/user-attachments/assets/076f6f18-835c-40ee-bde7-cd944525e01d)
![fb6f80e849bd19b0f02bcef341480f7](https://github.com/user-attachments/assets/65a9c03a-a14d-4df4-a0c1-34d86951d51c)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划更改，玫瑰图一般适用于展示5个左右的分类，如果分类较多，建议您使用其他的图表类型。
