### ISSUE TITLE
[Feature]【数据填报】

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#12533]
DataEase 版本:
2.10.1

**请描述您的需求或者改进建议.**
希望这个界面可以看到新建表单时填写的数据库表名，可以有一个地方可以查看到表信息，否则任务多了之后，去数据集那边连接，会忘记对应的表。

![image](https://github.com/user-attachments/assets/06025296-5ce0-43ac-912c-1b185fcea5f6)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池中。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
