### ISSUE TITLE
[Bug]时间组件靠边时悬浮的设置会隐藏部分

### ISSUE THREAD

**Issue by BBchicken-9527** [dataease/dataease#1253]
**DataEase 版本**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/84372766/142995490-ea9c77c2-74ad-4159-ba59-492ec3c551f1.png)

1.
2.
3.

**Comment by tjlygdx** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 版本已修复
