### ISSUE TITLE
[Bug]数据导出功能异常

### ISSUE THREAD

**Issue by ghyghoo8** [dataease/dataease#12540]
**DataEase 版本**
2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
docker运行

**浏览器版本**
chrome 129

**Bug 描述**
* 数据导出进度一直卡在 0%
<img width="795" alt="image" src="https://github.com/user-attachments/assets/fb691f9e-889b-44ad-8de7-3f14866485f9">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
请检查一下下图的目录是否已创建。
![图片](https://github.com/user-attachments/assets/37b6548a-1458-415a-b8e7-ba3dcf8ab86e)

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
