### ISSUE TITLE
[Bug]v2.10.1 数据大屏 全屏或者预览的时候，不是根据大屏尺寸，而是根据背景图片了

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#12545]
![image](https://github.com/user-attachments/assets/d50b2da9-0518-41d3-b039-6abee7cbee2b)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们在下个版本修复一下。

**Comment by ziyujiahao** [comment]
https://github.com/dataease/dataease/commit/1b2a2c24d5140b5496c8a224e64003f6b96d5405

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
