### ISSUE TITLE
[Bug]数据同步中DORIS进行有UNSIGNED这个字段的同步报错，并且删除这个字段还是报错

### ISSUE THREAD

**Issue by armored-glitch** [dataease/dataease#12556]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
主流浏览器均进行测试

**Bug 描述**
尊敬的dataease团队：
     doris同步时候，有UNSIGNED这个字段的表删除掉对应的字段他同步还是报同样的错误，然后重建表后新的表 改表名改成老的还是报错
考虑代码层面是否对表名是否进行缓存，然后直接判断

**Bug 重现步骤(有截图更好)**
1.
![cdc45116a3e0937f71f48f5ceef6587](https://github.com/user-attachments/assets/5d6de8bc-d429-4f7e-84e6-dbb1a82d99ff)

2.
![6f15fef3586a4a7a209e3559a68a7b9](https://github.com/user-attachments/assets/1ecf7617-8e0a-4c29-b61a-5981259d168e)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，请问你说从什么数据源进行的同步？字段又是如何创建的？如果方便建议将异常时的后台日志也看一下；

**Comment by armored-glitch** [comment]
尊敬的dataease团队：数据库同步使用的是mysql，是因为您的测试环境版本和我不同嘛。

**Comment by BBchicken-9527** [comment]
这个我不能确定，方便的话，先给我看一下你那边日志异常信息，还有就是说明一下你是从什么版本的mysql迁移数据到什么版本的doris，给个大版本就行；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
