### ISSUE TITLE
[Bug]文本下拉框添加（存在标题）后复制，然后在拉取一个文本搜索框放在两个下拉框之间添加标题，之后重叠

### ISSUE THREAD

**Issue by BBchicken-9527** [dataease/dataease#1255]
**DataEase 版本**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/84372766/142997362-0fab73bc-4b3f-4ef3-8e69-e6948502fa75.png)

1.
2.
3.

**Comment by tjlygdx** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 已修复，请等待新版本发布
