### ISSUE TITLE
[Feature]指标卡添加对 时间列 最大值和最小值 的支持

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12561]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
指标卡添加对 时间列 最大值和最小值 的支持。
指标卡有可能添加对 时间列 最大值和最小值 的支持吗？之后这个需求我们应该会很常用，如果只能用富文本的话统一各报表的格式会比较麻烦

**Comment by xuwei-fit2cloud** [comment]
指标卡设计之初是为了显示数值类型的数据，如果要显示时间数据的话，我们需要讨论一下是进行扩展还是新增组件。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议使用富文本。
