### ISSUE TITLE
[Feature] 饼图一些优化建议

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#12565]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
1. 允许设置第一扇区的起始角度
![image](https://github.com/user-attachments/assets/aa3a4f91-94c8-4927-a1fd-702d47be46c4)
2. 类别较多时，标签处于一侧，展示较为拥挤，希望能够拆开
（如图，这种就完全重叠在左边，但是右边很空）
![image](https://github.com/user-attachments/assets/dfeeddec-ec8c-46d2-b386-3f546b734fb5)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，标签位置图库自行分配的，暂时没有计划支持拆分。
