### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by 673092756** [dataease/dataease#12577]
DataEase 版本:2.10.1

**请描述您的需求或者改进建议.**
![image](https://github.com/user-attachments/assets/b61f32c1-9285-430c-b58c-0ed4e27e8b14)
希望这个可以修改字段类型，因为我发现在更新或者追加数据的时候当字段类型不匹配或者无法定义字段类型的时候就会报错，错误显示内容这种，希望可以自定义字段类型或者可以修改字段类型

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议在数据集中修改字段类型，数据源中暂时没有计划支持修改字段类型。
