### ISSUE TITLE
[Bug] 【地图显示不全】 世界地图俄罗斯地图显示会出现空缺

### ISSUE THREAD

**Issue by daiqingyao6238** [dataease/dataease#12581]
**DataEase 版本**

2.10.1
**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌最新版

**Bug 描述**

![image](https://github.com/user-attachments/assets/2004b5ea-ca54-4ac6-aad3-52ca2ae8634b)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，下个版本将更换地图文件，在测试环境中查看没有发现你说的问题，可以到时候下载最新版本看看；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
