### ISSUE TITLE
[Bug]v2 数据大屏，tab 组件内视图位置编辑后保存预览不生效

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#12586]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**

谷歌
**Bug 描述**
1 在数据大屏使用 tab 组件覆盖整个大屏，在 tab 组件中新建视图，编辑位置后保存，然后在编辑界面预览，保存不生效。不知道是不是自适应的问题
第一张图为编辑前效果
第二张图为保存后效果
第三张图为退出预览后效果

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/911e4775-4973-425a-9a11-9ee205c47494)

2.
![image](https://github.com/user-attachments/assets/83087d88-cffe-4f00-a384-48767e5a090e)

3.
![image](https://github.com/user-attachments/assets/a38605e4-edad-4400-96f0-9a8aac832bd9)

**Comment by BBchicken-9527** [comment]
感谢反馈，经排查应该是在对组件细微调整时会出现这样的问题，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
