### ISSUE TITLE
[Bug] 堆叠条形图有堆叠项时指标排序显示异常

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#12594]
**DataEase 版本**
v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌

**Bug 描述**
堆叠条形图  拖入堆叠项后 在指标进行排序时 显示数据异常 不排序则可以正常显示 数据是数值型的
![image](https://github.com/user-attachments/assets/95deea42-3f5e-4ffb-b65b-446b3e8a6974)

![image](https://github.com/user-attachments/assets/5c95cd0a-2db9-4db6-95c4-29f1fb5a9fa8)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，正在努力修复中，将会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
