### ISSUE TITLE
[Bug]字段跳转关联时间范围组件，没有传递给结束时间报错

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#12600]
**DataEase 版本**

v2.10.1
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌浏览器

**Bug 描述**
字段跳转关联时间范围组件，只传给开始时间，没有传给结束时间，跳转缺少结束时间报错。需要同时传给开始时间和结束时间

**Bug 重现步骤(有截图更好)**
1.设置跳转，选择过滤组件会字段关联，
![image](https://github.com/user-attachments/assets/733eb1db-37da-409c-8a62-bdc5980f68e2)

2.只传给开始时间没有传给结束时间，缺少结束时间，跳转到新仪表板就会报错。需要同时传给开始时间和结束时间
![image](https://github.com/user-attachments/assets/10283ade-2859-44b4-87cb-450c21847195)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
