### ISSUE TITLE
[Bug] 仪表板删除后仍能通过血缘关系-数据源 过滤搜索找到

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#12607]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
仪表板删除后仍能通过血缘关系-数据源 过滤搜索找到

**Bug 重现步骤(有截图更好)**
![image](https://github.com/user-attachments/assets/1d0e7009-3983-4e34-84e6-67f8bdd6f00c)
![image](https://github.com/user-attachments/assets/cab16c98-bfac-4450-846e-d2c10cae6de2)

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
