### ISSUE TITLE
[Bug]链接oracle数据库会话不断增加，无法自动回收直至oracle会话资源耗尽

### ISSUE THREAD

**Issue by jstbw** [dataease/dataease#12606]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
从2.9升级到2.10.1后，发现链接oracle数据库 会话不断增加，无法自动回收直至oracle会话资源耗尽

SELECT machine,count(*) FROM v$session  GROUP BY machine
执行查看到
![fd4700db6de4497edd94ee2f0946c7d](https://github.com/user-attachments/assets/700adc21-22e8-4b91-92b1-ee0d1de30a92)
每执行一次，增加10个或更多，前端数据展示并不多，应该是连接没有释放

**Comment by maninhill** [comment]
已知问题，已解决，将在2.10.2版本发布。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
