### ISSUE TITLE
[Bug]v2.10.1 仪表板图表提示多且图表处于下方时，提示显示不完全

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#12616]
编辑时：
![image](https://github.com/user-attachments/assets/0e63145b-4221-44c4-a0ac-e657e824bc68)
预览时：
![image](https://github.com/user-attachments/assets/2d4b9207-4bad-4dbc-98ce-9e3b081a785b)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，目前正在努力修复中，将会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
