### ISSUE TITLE
[Feature]流向地图的优化建议

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#12619]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
1. 标注文本和地图文本同时显示，比较乱，希望可以设置隐藏地图自带的文本。
<img width="684" alt="图片" src="https://github.com/user-attachments/assets/070d169a-99f2-4c2c-828b-9b2952f93e21">

2. 希望选择关闭显示流向地图中的公路铁路线；

3. 选择地区区域只显示选择的区域，如中国地图，只显示中国地图不显示外面的地图，选择山东省只显示山东省区域。

**Comment by xuwei-fit2cloud** [comment]
已加入开发计划。

**Comment by xuwei-fit2cloud** [comment]
1和2已支持。3的话，可以自定义中心点坐标，配合缩放等级来实现。
