### ISSUE TITLE
[Bug] 年月组件过滤失败

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#12617]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
年月组件过滤失败

**Bug 重现步骤(有截图更好)**
1. ![image](https://github.com/user-attachments/assets/405813a1-1cf1-4e7a-8b8d-2069330c45dc)
2. 页面无法通过年月组件过滤出对应内容
![image](https://github.com/user-attachments/assets/d91fb13c-91e8-4299-98b2-fc49a8465ef8)
![image](https://github.com/user-attachments/assets/f84a8df5-c4f8-4f74-910e-ec0e2e82c209)

**Comment by BBchicken-9527** [comment]
感谢反馈，concat方法的返回值应该是文本类型，计算字段的过滤需要和字段的数据库中的原始字段类型统一，所以你需要在表达式中转成日期才可以通过日期过滤规则进行过滤，你现在通过文本方式过滤是没有问题的；
