### ISSUE TITLE
[Feature]告警管理的告警规则增加动态值支持

### ISSUE THREAD

**Issue by calvinit** [dataease/dataease#12612]
DataEase 版本: 2.10.1

**请描述您的需求或者改进建议.**
https://dataease.io/docs/v2/xpack/alarm_management/#3
新的【告警管理】功能，【告警规则】新增支持 “动态值” 配置，比如 “动态日期/时间” 等。

![配置位置](https://github.com/user-attachments/assets/1435cca6-af1d-49e3-93e2-6af98da0b23d)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们在近期版本支持一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
