### ISSUE TITLE
[Bug]流向地图修改线条颜色时，地图风格也会改

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#12614]
**DataEase 版本**
v 2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome

**Bug 描述**
流向地图修改线条颜色时，地图风格也会改
https://github.com/user-attachments/assets/911e5acd-d4c4-466f-ae74-ab9b4775433c

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
