### ISSUE TITLE
[Feature]v2.10，定时报告》接收人 里面的 接收设置，是否可以添加 "下载中心" 选项，某SAAS ISV需要该选项。

### ISSUE THREAD

**Issue by 35plus** [dataease/dataease#12626]
DataEase 版本:
v2.10

**请描述您的需求或者改进建议.**
本来客户想要的是下面的需求：
管理员做好一份仪表板报告，可以推送给 一群用户，用户在站内信 看到信息后可以下载 pdf报告。

后来经过沟通，用户也能接收说下面这种实现方式。
管理员做好一份仪表板报告，可以通过定时报告推送给 一群用户，然后用户在下载中心里可以下载报告。

如果要实现这种，需要 在 定时报告》接收人 里面的 接收设置，添加 "下载中心" 选项。这样报告会被推送到下载中心，被推送人 的下载中心那里 会有一个 提示。

该SAAS厂商有 100多个客户，目前是在几个客户那里推DE。他们的用户以餐饮行业为主，人员IT水平不高，所以希望能让用户登录 直接下载 平台推送的pdf报告。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持下载中心。定时报告建议发送到用户邮箱，在邮箱中打开或者下载使用。
