### ISSUE TITLE
[Feature]告警规则支持选动态时间

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#12634]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
告警规则中希望可以支持动态时间（当日、本周、本月、近 30 日等）
场景：当天某指标数据达到阈值则告警，当月某指标数据达到多少就告警。
<img width="906" alt="图片" src="https://github.com/user-attachments/assets/45b3baaf-00df-407a-be8b-dc85b96730ba">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经加入近期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
