### ISSUE TITLE
[Feature] 条形图增加横轴标签长度限制

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#12639]
DataEase 版本:
2.10.1

**请描述您的需求或者改进建议.**
和 v1 一样  条形图增加横轴标签长度限制
![image](https://github.com/user-attachments/assets/bb3e273b-5869-4ff7-922c-298c268e271b)

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
