### ISSUE TITLE
[Feature]增加用户限制登录

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#12638]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**

像 v1 一样，增加用户限制登录功能
<img width="763" alt="图片" src="https://github.com/user-attachments/assets/9a705c32-3eb9-4331-bc47-0aa067f159d2">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经加入近期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
