### ISSUE TITLE
[Feature]雷达图坐标轴轴值可以跟柱状图坐标轴轴值一样自定义

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#12637]
DataEase 版本:
2.10.1

**请描述您的需求或者改进建议.**
比如，此图中几个数值是101.104.105.106.109，本身差别不大，但是在图上看，有明显短板，影响观感
希望可以自定义轴值最大值和最小值甚至是刻度数等
![image](https://github.com/user-attachments/assets/44fae7df-00e8-4d55-b70c-55f28c097a5f)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已经加入近期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
