### ISSUE TITLE
[Feature]阙值告警现在只支持邮件，可不可以支持企业微信等这些的通知呢

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12642]
DataEase 版本:
v2.10.0

**请描述您的需求或者改进建议.**
阙值告警现在只支持邮件，可不可以支持企业微信等这些的通知呢

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经在v2.10.1版本中进行支持，请升级版本。
