### ISSUE TITLE
[Question]打包时总是报错Rollup failed to resolve import "element-plus-secondary/es" from "D:/Code/..." element-plus-secondary组件的引入问题

### ISSUE THREAD

**Issue by Jean-maker** [dataease/dataease#12648]
**请描述您的问题.**
使用vite build打包时采用import "element-plus-secondary/es"方法引入组件的地方全部报错，查看node_modules文件夹下发现存在相关文件，请问这个问题改如何解决
<img width="350" alt="79740BA3-678C-4caf-9011-1358B6CD2B01" src="https://github.com/user-attachments/assets/67970ed4-70b3-490b-9282-2e0c329d5f73">
<img width="966" alt="A2C97A25-2A5A-45db-82EF-38DF788DCC98" src="https://github.com/user-attachments/assets/10585edc-dcba-42e6-babd-b8aceb5705b9">

**Comment by xzl1634602832** [comment]
同问

**Comment by wmy94827** [comment]
同问

**Comment by GuitarHusky** [comment]
+1,很莫名其妙，检测项目目录外的文件去了。。。。。。

**Comment by sea-yu** [comment]
我按照下面的结构是编译成功的
-  dataease
   - core
      - core-frontend

你可能把core-frontend单独拆出来了，他编译的时候我猜测关于使用相对路径(../../	)扫描文件夹,去找xe-pack这个文件夹,没找到没关系，主要别让他扫到其他没权限或者其它项目vue文件夹就好了

**Comment by likeeprunning** [comment]
同问 请问怎么解决

**Comment by CHANGEGE** [comment]
> 我按照下面的结构是编译成功的
> 
> * dataease
>   
>   * core
>     
>     * core-frontend
> 
> 你可能把core-frontend单独拆出来了，他编译的时候我猜测关于使用相对路径(../../ )扫描文件夹,去找xe-pack这个文件夹,没找到没关系，主要别让他扫到其他没权限或者其它项目vue文件夹就好了

验证有效！！！
一模一样的问题！！！
路径补齐，并修改项目目录名称，打包成功了
