### ISSUE TITLE
[Feature]阙值告警，目前是定期触发的，需要每分钟（或某个颗粒度的时间）就去轮询触发告警

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12641]
DataEase 版本:
v2.10.0

**请描述您的需求或者改进建议.**
阙值告警，目前是定期触发的，但有时候工厂内部有一些指标的是很重要的，比如一些生产指标不能出错，一出错就得马上排查，恢复现场，需要每分钟（或某个颗粒度的时间）就去轮询触发告警，比如每分钟/每秒，这个能否支持下呢

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
DataEase并不是监控告警系统，如果对告警的实时性要求较高，建议用其他告警方案。
