### ISSUE TITLE
[Bug]日志表中无法分辨移动端操作还是 PC 操作

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#12646]
**DataEase 版本**
v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
PC 端 Firefox
手机端 safari

**Bug 描述**
我分别用 PC 和手机，登录并访问仪表板，xpack_log 中都记录了 PC。
<img width="1240" alt="图片" src="https://github.com/user-attachments/assets/5edde87e-a271-475a-8089-7136d58385cf">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前client字段为预留字段，并无实际使用，记录来源均为pc，会根据后续需求对这个字段进行处理；
