### ISSUE TITLE
[Feature]图表内单元格可以左右滚动以缩小单元格所需宽度

### ISSUE THREAD

**Issue by Yiki380** [dataease/dataease#12655]
DataEase 版本:
v2.10.0

**请描述您的需求或者改进建议.**
一个大屏想要放的东西太多，而有些字段值大部分较短，偶尔几个值较长，为了显示不得不拉长整个单元格。如果能实现这样的效果 就太好了

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持。

**Comment by Yiki380** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
