### ISSUE TITLE
[Bug] 使用mongobi 连接，发现表名或是字段带中文查询不了

### ISSUE THREAD

**Issue by FantasyNeurotic** [dataease/dataease#12659]
**DataEase 版本**

2.10.1
**运行方式(安装包运行 or 源码运行 ?)**

安装包运行
**浏览器版本**
chrome 129.0.6668.100（正式版本） (x86_64)

**Bug 描述**
<img width="648" alt="image" src="https://github.com/user-attachments/assets/b139a12d-8927-44b2-8c72-8e8cbff9b2ca">

<img width="241" alt="image" src="https://github.com/user-attachments/assets/8cf82f6c-067d-4e46-83d4-8bedbedd3a97">

<img width="646" alt="image" src="https://github.com/user-attachments/assets/7cd1f923-9750-4fdd-84e3-fb0bed9ee26b">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
