### ISSUE TITLE
[Bug]doris数据源表的comment字段读取错误。

### ISSUE THREAD

**Issue by BeiLiu1** [dataease/dataease#12653]
**DataEase 版本**
2.9.0

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**

**Bug 描述**
doris数据源表的comment字段读取错误。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/user-attachments/assets/c07f9e56-4cc6-4da7-a960-c72320afc032)
![image](https://github.com/user-attachments/assets/c87cfb08-2539-4d57-bb88-85591366fadb)

**Comment by maninhill** [comment]
请使用最新的 v2.10 代码。
