### ISSUE TITLE
[Bug]汇总表当表头和表格背景色相同时，表格边框颜色会深浅不一

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#12663]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**Bug 描述**
汇总表当表头和表格背景色相同时，表格边框颜色会深浅不一

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/903851c9-f162-4ac0-93ee-23a26b276393)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
