### ISSUE TITLE
[Feature]填报完成自动发邮件功能和开权限

### ISSUE THREAD

**Issue by daviadong** [dataease/dataease#12661]
DataEase 版本:
2.10

**请描述您的需求或者改进建议.**
填报填写提交后，自动发邮箱通知对应的用户，并且在填报截止后，开通查看的权限
比方说：两个填表的A表和B表都是填报的表单，A表单是A类人员填写，B表单B类人员填写。A表单填写提交后会发邮件，让B类人员填写B表单。A类人员填报截止时间之前是看不到的B表单，只有填报截止后，才会自动开通权限。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，表单之间是相互独立的，因此目前暂时没有计划支持。
