### ISSUE TITLE
[Bug] 数据同步中源数据库使用mysql，目标数据库doris，同步时候一直显示在加载

### ISSUE THREAD

**Issue by armored-glitch** [dataease/dataease#12669]
**DataEase 版本**
v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
尊敬的dataease团队：
       数据同步中源数据库使用mysql，目标数据库doris。同步时候一直显示在加载，加载结束后没有同步过来表结构，显示空白页面。     目前这张表字段数是50个（列），是不是DE对字段数做限制，或者有设置超时时间。
![image](https://github.com/user-attachments/assets/0ff9c671-beee-4108-b47c-ae93d7bb8e60)
![image](https://github.com/user-attachments/assets/1973d857-85ff-4002-b0ac-f9f53936ad08)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，方便问一下前台还有后台有异常提示吗？

**Comment by armored-glitch** [comment]
不好意思后台忘记查看，前台没有异常提示

**Comment by BBchicken-9527** [comment]
emm..数据结构的同步应该很快才对的。目前我这边没有发现你说的情况，我们也并没有在这里做出任何的限制，需要看看你那边后台是否有异常信息才可能做出判断了；
![image](https://github.com/user-attachments/assets/ba01a865-2a1b-4c35-8fc5-43d4fd0823c3)

**Comment by BBchicken-9527** [comment]
或者如果方便的话给我们一份你有问题的表结构，我这边测试环境模拟一下看看是否存在相同的问题；

**Comment by armored-glitch** [comment]
好的感谢！不好意思图表截取的有点模糊，看报错内容和longtext 这个类型有关系
![image](https://github.com/user-attachments/assets/682ccd88-2d83-41ec-8a9c-fbc56641327a)
![image](https://github.com/user-attachments/assets/91bad068-f2dd-46d1-8141-834c574faee8)
`SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for abpusers
-- ----------------------------
DROP TABLE IF EXISTS `abpusers`;
CREATE TABLE `abpusers`  (
  `Id` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `TenantId` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `UserName` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `NormalizedUserName` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `Name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `Surname` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `Email` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `NormalizedEmail` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `EmailConfirmed` tinyint(1) NOT NULL DEFAULT 0,
  `PasswordHash` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `SecurityStamp` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `IsExternal` tinyint(1) NOT NULL DEFAULT 0,
  `PhoneNumber` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `PhoneNumberConfirmed` tinyint(1) NOT NULL DEFAULT 0,
  `TwoFactorEnabled` tinyint(1) NOT NULL DEFAULT 0,
  `LockoutEnd` datetime(6) NULL DEFAULT NULL,
  `LockoutEnabled` tinyint(1) NOT NULL DEFAULT 0,
  `AccessFailedCount` int(11) NOT NULL DEFAULT 0,
  `ExtraProperties` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `ConcurrencyStamp` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `CreationTime` datetime(6) NOT NULL,
  `CreatorId` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `LastModificationTime` datetime(6) NULL DEFAULT NULL,
  `LastModifierId` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `IsDeleted` tinyint(1) NOT NULL DEFAULT 0,
  `DeleterId` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `DeletionTime` datetime(6) NULL DEFAULT NULL,
  `FaceImageUrl` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT 'https://public-server-center-prod-1258963190.cos.ap-guangzhou.myqcloud.com/studentCard/avatar2',
  `Gender` tinyint(3) UNSIGNED NOT NULL DEFAULT 0,
  `OrganizationId` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `OrganizationName` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `Platform` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `FromUserId` char(36) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `Birthday` datetime(6) NULL DEFAULT NULL,
  `RealFaceImageUrl` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `IsActive` tinyint(4) NOT NULL DEFAULT 1,
  `EntityVersion` int(11) NOT NULL DEFAULT 0,
  `LastPasswordChangeTime` datetime(6) NULL DEFAULT NULL,
  `ShouldChangePasswordOnNextLogin` tinyint(1) NOT NULL DEFAULT 0,
  `PhoneNumberUniqueHash` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `UserNameUniqueHash` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`Id`) USING BTREE,
  UNIQUE INDEX `IX_AbpUsers_Id`(`Id`) USING BTREE,
  UNIQUE INDEX `IX_AbpUsers_UserNameUniqueHash`(`UserNameUniqueHash`) USING BTREE,
  INDEX `IX_AbpUsers_Email`(`Email`) USING BTREE,
  INDEX `IX_AbpUsers_NormalizedEmail`(`NormalizedEmail`) USING BTREE,
  INDEX `IX_AbpUsers_NormalizedUserName`(`NormalizedUserName`) USING BTREE,
  INDEX `IX_AbpUsers_UserName`(`UserName`) USING BTREE,
  INDEX `IX_AbpUsers_PhoneNumber`(`PhoneNumber`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;`

**Comment by BBchicken-9527** [comment]
我用你的表结构创建看也没有什么问题，你的截图太糊了老哥，啥信息也看不到，我只看到了一堆马赛克；
![image](https://github.com/user-attachments/assets/62c1b705-09d3-4fe0-b7a6-43fef6b72024)

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
