### ISSUE TITLE
[Bug]v2.10.1 使用以前的数据大屏模板，大屏配置项没有缩放方式设置

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#12666]
![image](https://github.com/user-attachments/assets/59e2b790-e1da-488d-8fe7-a591a041208a)
正常情况：
![image](https://github.com/user-attachments/assets/a24d671b-d5b9-4bce-87ca-84520ae7dc13)

这个不太正常吧？这个选项应该是个功能，如果不能兼容旧版本，感觉有点奇怪。

**Comment by BBchicken-9527** [comment]
感谢反馈，只有历史的模版会有这种问题，并且保存后再次进入会正常显示，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
