### ISSUE TITLE
[Bug] 世界地图提示轮播数据缺失

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#12679]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
世界地图提示轮播数据缺失

**Bug 重现步骤(有截图更好)**
[世界地图.xlsx](https://github.com/user-attachments/files/17359044/default.xlsx)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
