### ISSUE TITLE
[Feature] 表格滚动优化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#12677]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
表格滚动效果到最后一行的时候没有停顿直接重第一条开始滚动，体验感欠佳，是否可以设置滚动到最后一条后，停顿1~2秒再次翻到最上面。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，已经加入近期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
