### ISSUE TITLE
[Feature] 图片组件优化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#12685]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
图片未设置跳转的情况下，鼠标悬浮仍然会显示成一个手指，就容易让用户理解为这里可以互动，期望在无交互事件的时候，鼠标显示没有变化。
<img width="490" alt="72ac4987022884bdbf0eb3d6e80a1d0" src="https://github.com/user-attachments/assets/8d5baedd-ba61-452f-86e4-3cdf9e7ac65f">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
