### ISSUE TITLE
[Bug]富文本编辑的时候，拉表格，结果最左边的变大了，并且不可调回，设置全局的也不能改变这个比例

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12688]
**DataEase 版本**
v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
![image](https://github.com/user-attachments/assets/7273eb20-53e3-4cd1-a821-41b6130c8b54)

**Bug 重现步骤(有截图更好)**
富文本设置5x7表格，然后设置全局表格宽度（可以正常），然后拖动某个表格列，这时候只有最左边的变大了，并且不可调回，且全局也是

**Comment by Yiki380** [comment]
单元格属性里，单列表格在的宽度无法设置，拉表格的时候，预览的位置与实际位置有差别，具体可以说是往最左边拉是往左拖动，往最右边拉是往右拖动，
按图上三个线的位置 拖到第一根线的地方才是将第一个单元格缩小，二和三的位置反而会将第一个单元格变大
![微信图片_20241014151251](https://github.com/user-attachments/assets/44fba2ba-29e9-4b84-b421-9eaf65842864)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，正在努力修复中，将会在下个版本完成；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。

**Comment by Yiki380** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
