### ISSUE TITLE
数据大屏切换数据源

### ISSUE THREAD

**Issue by SuperManYo** [dataease/dataease#12704]
数据大屏中可以做到一键切换数据集吗

比如下面这两个图表，我数据集中写好了不同数据库但表一样的sql   现在显示的是A数据库的，有什么办法可以做到一键切换B数据库数据。
![image](https://github.com/user-attachments/assets/7b931688-d7f9-4425-8330-bb2cf75d1d91)

**Comment by xuwei-fit2cloud** [comment]
很抱歉，目前还没有这样的功能。我们先讨论一下看看有没有其他的解决方案。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经加入需求池中，待更多用户反馈之后再进行下一步的规划。
