### ISSUE TITLE
[Feature] 日期范围与文本过滤组件联动

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#12707]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
日期范围组件能否与文本过滤组件联动，达到级联的效果，如下所示：
![369423d283c2a575d689c09cc3e9b34](https://github.com/user-attachments/assets/b383e6b8-0fcf-4fc1-a417-49aace585219)
希望可以根据时间段来动态筛选后面的岗位和业务员

**Comment by xuwei-fit2cloud** [comment]
需要讨论一下技术可行性。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持。
