### ISSUE TITLE
[Bug] 仪表板明细表导出数据失败

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#12706]
**DataEase 版本**
v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 129.0.6668.90（正式版本） （64 位）

**Bug 描述**
仪表板明细表导出数据失败

**Bug 重现步骤(有截图更好)**
1. 异常信息如下所示：
![afabb622128b52c8611144745e174db](https://github.com/user-attachments/assets/47c0a8bf-18d3-4401-b177-cae4c6590fcc)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们排查一下；

**Comment by xuwei-fit2cloud** [comment]
请升级版本。
