### ISSUE TITLE
[Bug]堆叠柱状图按照记录数排序显示数据异常

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#12701]
**DataEase 版本**
企业版 v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
离线安装

**浏览器版本**
最新版

**Bug 描述**
堆叠柱状图按照记录数排序显示数据异常

**Bug 重现步骤(有截图更好)**
1. 记录数无排序显示正常
![dea3054832867eba38a5947e5b57163](https://github.com/user-attachments/assets/e6eab626-6a42-4137-9153-79c049593ff6)

2. 按照记录数升序显示异常
![5b7dfdf46c5ea8838c96d30628364f3](https://github.com/user-attachments/assets/29cdad57-3823-4449-8e9d-6dd7ca4169e0)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，目前正在努力修复中，将会在下个版本完成修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
