### ISSUE TITLE
[Feature] 前端资源缓存优化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#12716]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
当前 dataease 登录有时会提示 500 的异常，查看后端日志后有如下报错。
![eb819dba23fa38bbc860cad01d8f94f](https://github.com/user-attachments/assets/8e0f2966-66e8-4840-9b0b-38b80ba00f27)
判断为前端的 key 缓存问题导致用户加密出现异常，在服务重装或者域名对应的服务地址切换时几乎必现
能否对此进行优化

**Comment by maninhill** [comment]
我也遇到过这个问题。

**Comment by ziyujiahao** [comment]
这个清理已浏览器缓存即可 这种情况只有在开发环境中能遇到切换rsa的场景 正式用的话 首次安装会自动生成rsa以后也不会变了只有切换数据库 或者 同一个服务器重装了之后才会遇到
