### ISSUE TITLE
[Feature]过滤组件隐藏时，可以选择生效或不生效

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#12714]
DataEase 版本:
2.10.1

**请描述您的需求或者改进建议.**
![image](https://github.com/user-attachments/assets/dba5abc9-0762-447d-b0aa-2b7bb84b6f86)

**Comment by xuwei-fit2cloud** [comment]
我们讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们加入近期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
