### ISSUE TITLE
最新版源码部署成功后，点击仪表板、数据大屏无法显示，F12查看控制台报 TypeError: De is not a function 错误

### ISSUE THREAD

**Issue by qq402026752** [dataease/dataease#12717]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 127.0.6533.100

**Bug 描述**
最新版源码部署成功后，点击仪表板、数据大屏无法显示，F12查看控制台报 TypeError: De is not a function 错误

**Bug 重现步骤(有截图更好)**
![image](https://github.com/user-attachments/assets/a6f43570-c9a9-4122-b3f1-e55285331183)
![image](https://github.com/user-attachments/assets/59454274-3eed-441a-8427-dcad9625d8eb)

**Comment by qq402026752** [comment]
看这个  ![image](https://github.com/user-attachments/assets/b7ac8b95-4be4-4329-89c4-5eda98b58f1f)

**Comment by qq402026752** [comment]
![image](https://github.com/user-attachments/assets/9fc92630-f08d-4194-a559-4785a76ae5c3)
这个要怎么改呢？

**Comment by BBchicken-9527** [comment]
感谢反馈，由于你是源码运行，不确定你是否改动和以及打包方式都有可能存在问题，建议你加入我们的交流群，上面有非常专业的同学会实时的回复你的问题，方便你快速并精准的定位到你的问题所在；

**Comment by ziyujiahao** [comment]
经过测试清理一下前端缓存即可

**Comment by qq402026752** [comment]
已经试过清空缓存，是不行的 @ziyujiahao

**Comment by qq402026752** [comment]
> 经过测试清理一下前端缓存即可

已经试过清空缓存，是不行的

**Comment by qq402026752** [comment]
![Uploading a7677f8e88e4cc5a2445ab48e147959.png…]()
![Uploading 6833fbe5b7ad512c9171ad3073d216c.png…]()

**Comment by qq402026752** [comment]
![a7677f8e88e4cc5a2445ab48e147959](https://github.com/user-attachments/assets/217667db-baf7-4078-8d1f-e0a9a6771466)
![6833fbe5b7ad512c9171ad3073d216c](https://github.com/user-attachments/assets/e7ffc6b5-c665-48d5-8bdd-89587943ce86)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
