### ISSUE TITLE
[Feature]希望V2的tab能够支持隐藏标题

### ISSUE THREAD

**Issue by Xyuncheng** [dataease/dataease#12729]
DataEase 版本:
2.10.1

**请描述您的需求或者改进建议.**
v1的选项卡组件能支持隐藏标题，v2不支持，希望能够支持一下，谢谢！
![1729064571171](https://github.com/user-attachments/assets/497181a9-b872-4e6e-aa8f-b0a671b8592d)
![1729064763037](https://github.com/user-attachments/assets/2e436643-b0c7-44ef-936e-89e53d355c8c)

**Comment by xuwei-fit2cloud** [comment]
已排期。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
