### ISSUE TITLE
最新版源码部署成功后，点击仪表板、数据大屏均报错（已清空缓存无效，本代码没有作任何修改），看着应该是社区版本去到xpack，没有完全测试

### ISSUE THREAD

**Issue by qq402026752** [dataease/dataease#12724]
![1729058505249](https://github.com/user-attachments/assets/27a2dc92-5229-4dfd-8c3e-8d8947e28352)
![a7677f8e88e4cc5a2445ab48e147959](https://github.com/user-attachments/assets/7da43948-9570-4b5d-b724-75c7e8fb222f)
![330e0d78865b489c8640ee9f990fc39](https://github.com/user-attachments/assets/b0123ef5-38fa-4cdd-a6c1-0a120e87db8f)
![d2c6451922cc60b7b7c1657f723d892](https://github.com/user-attachments/assets/f8cf6339-964e-4a56-b9d9-0092991e8d4e)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #12717

**Comment by fit2cloud-chenyw** [comment]
Done! https://github.com/dataease/dataease/commit/eb3f667ca6fd0360ee9d6b64671102fbc8cc67d5

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
