### ISSUE TITLE
[Bug] 图表自定义配色设置时，没有显示对应配置项

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#12728]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
图表自定义配色设置时，没有显示对应配置项

**Bug 重现步骤(有截图更好)**
<img width="464" alt="image" src="https://github.com/user-attachments/assets/138e0577-bc6c-472d-ab55-373e66bd2cfb">

**Comment by BBchicken-9527** [comment]
感谢反馈，请问图表添加字段了吗？是什么图表方便说一下吗？是折线图还是双轴图，自定义字段需要添加相应的字段才能显示的；
