### ISSUE TITLE
[Bug] tab 组件下添加富文本组件，保存/预览 切换，位置的值会变动

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#12721]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
tab 组件下添加富文本组件，保存/预览 切换，位置的值会变动

**Bug 重现步骤(有截图更好)**
![image](https://github.com/user-attachments/assets/0c4ae5db-abb5-4fb1-8e7c-e1b75047ad69)
![image](https://github.com/user-attachments/assets/9db96ca9-2d56-49f3-a812-4360088363fc)
![image](https://github.com/user-attachments/assets/c1fe21d2-c645-4890-b991-d2b44a73d7ab)

**Comment by xuwei-fit2cloud** [comment]
我们排查一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
