### ISSUE TITLE
[Bug]仪表板tab放汇总表，然后汇总表拉出来，在移动端放显示空白，回来PC端也显示空白，如果没有显示，关掉重新进一下PC端又空白，且多出新表

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12726]
**DataEase 版本**
v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
谷歌

**浏览器版本**
最新

**Bug 描述**
tab放汇总表，然后汇总表拉出来，在移动端放显示空白，回来PC端也显示空白，如果没有显示，关掉重新进一下PC端又空白，然后会多出新的汇总表来。

**Bug 重现步骤(有截图更好)**
1.新建仪表板，新建tab，新建汇总表，放好数据，保存页面
2.汇总表=》tab，这时候PC和移动端正常
3.汇总表在tab拉出来，在移动端/PC显示，这时候也可能正常/开始空白
4.关闭页面，重新进入，这时多出来1-2个空白的汇总表。移动端也如此。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
