### ISSUE TITLE
[Feature]可以支持elastic吗

### ISSUE THREAD

**Issue by StarSsfe** [dataease/dataease#12746]
DataEase 版本:
]可以支持elastic吗

**请描述您的需求或者改进建议.**
]可以支持elastic吗

**Comment by xuwei-fit2cloud** [comment]
正在开发的v2.10.2版本已支持，请等待下个月版本发布。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
