### ISSUE TITLE
[Feature] 查询条件中的“模糊匹配”是否能隐藏？

### ISSUE THREAD

**Issue by Xyuncheng** [dataease/dataease#12748]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
查询条件中的“模糊匹配”选项能否支持隐藏起来？不去掉模糊查询选项，查询条件对齐都麻烦的。
![image](https://github.com/user-attachments/assets/42e610c7-1e6c-497a-b205-36ab96d13aa6)
如图所示，设置了文本搜索的查询组件之后，会自动带有“模糊匹配”或者“精确匹配”的字样，最终展示出来的查询条件无法对齐，所以希望能够支持隐藏“模糊匹配”或者“精确匹配”这些字样。

**Comment by xuwei-fit2cloud** [comment]
正在开发的v2.10.2版本已支持，请等待下个月版本发布。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
