### ISSUE TITLE
[Bug]数据源连接无效错误

### ISSUE THREAD

**Issue by xuewenquan** [dataease/dataease#12758]
**DataEase 版本**
v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome

**Bug 描述**
连接mysql8.0的数据源，隔一段时间就会出现连接无效的错误。

**Bug 重现步骤(有截图更好)**
Debug一下，发现rootSchema.getSubSchema(String.format(SQLConstants.SCHEMA, dsId))的NULL，从而出现了空指针异常。
![image](https://github.com/user-attachments/assets/6dad49a3-c775-4414-a4a7-5d16c5178336)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们排查一下。

**Comment by xuewenquan** [comment]
> 感谢反馈，我们排查一下。

不好意思，是dev-v2分支。

**Comment by xuwei-fit2cloud** [comment]
已做了一些代码处理，可以再试试。
