### ISSUE TITLE
[Bug]sqlserver数据源，在使用查询组件时，比如文本下拉，首先中文无法搜索下拉，然后选中后视图也筛选不出数据

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#12759]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
sqlserver数据源，在使用查询组件时，比如文本下拉，首先中文无法搜索下拉，然后选中后视图也筛选不出数据

**Bug 重现步骤(有截图更好)**
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，请问数据的字段类型是nvarchar吗？

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
