### ISSUE TITLE
[Bug]v2 嵌入式在线体验环境 数据集复制不管用

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#12769]
链接：
https://embedded-bi.dataease.cn/#/iframe/module/dataset_module

![image](https://github.com/user-attachments/assets/28fd61fe-ac7f-4fb3-8f4e-7eb2215cbfbe)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
