### ISSUE TITLE
[Bug] 明细表空置处理 置为0 后导出仍未空

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#12766]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
明细表空置处理 置为0 后导出仍未空

**Bug 重现步骤(有截图更好)**
![image](https://github.com/user-attachments/assets/6f8506d7-b519-4979-8669-98c7964ab93e)
<img width="556" alt="image" src="https://github.com/user-attachments/assets/1ef9322f-00ea-48eb-a289-cb22333396da">

**Comment by xuwei-fit2cloud** [comment]
数据导出是后台导出的，空值处理是前台处理的。
此处不做修改。
