### ISSUE TITLE
[Feature]可以自定义颜色默认模式

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#12777]
DataEase 版本:
2.10.1

**请描述您的需求或者改进建议.**
![image](https://github.com/user-attachments/assets/eafb52a6-5422-46f9-83ee-d321f75d5bc6)
![image](https://github.com/user-attachments/assets/706c03c9-4aae-49df-bf7c-1194826b2794)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持。
