### ISSUE TITLE
[Bug]图表复制字段后，再切换一个数据集，复制的字段没有清空

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#12770]
**DataEase 版本**
v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 129.0.6668.101

**Bug 描述**
复制字段后，再切换一个数据集，复制的字段没有清空

**Bug 重现步骤(有截图更好)**
1.复制一个字段
![image](https://github.com/user-attachments/assets/7ad8fce8-fb34-4aa5-8b3c-7c405fcc82f5)

2.再切换一个数据集，发现复制的字段没有被清掉
![image](https://github.com/user-attachments/assets/d174fdea-0572-4985-9c32-f5c59736833f)

**Comment by BBchicken-9527** [comment]
感谢反馈，图表层面复制字段为图表计算字段，是不归属数据集的，你从数据集也是不应该能被看到的，是这样的；
