### ISSUE TITLE
[Bug]面积图堆叠问题

### ISSUE THREAD

**Issue by JOJO30317** [dataease/dataease#12775]
**DataEase 版本**
V2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome最新

**Bug 描述**
面积图堆叠，是不是应该都是从坐标0开始，而不是堆叠

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/022adb3c-ebb3-4fab-84c7-3414574bc331)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，目前问题已被修复，将会在下个版本发布；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
