### ISSUE TITLE
[Bug] SQLServer数据集动态参数配合查询组件报错

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#12776]
**DataEase 版本**
v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌浏览器

**Bug 描述**
问题一：数据集中动态参数类型为文本且字段值为中文，数据集无法查询
![c376b7f83f2efe003d4c600d3fb214b](https://github.com/user-attachments/assets/00ce4c0b-498c-4c95-94d7-389be0c66af1)
![image](https://github.com/user-attachments/assets/c823bce3-2639-4a26-bd0f-b80924fa52f7)

问题二：数据集中其他动态参数类型可以运行的，但在查询组件绑定参数后获取数据异常
![3b81c289ca2541676a86d9416d2bd79](https://github.com/user-attachments/assets/e412d04f-4f74-4f28-b4e5-ba3fc78b916f)
![1d1679d2a41e1b3404b4220a781005f](https://github.com/user-attachments/assets/70f5aaca-eafd-4b1f-8526-32bb4bcfee9a)
![image](https://github.com/user-attachments/assets/a31df525-f5b2-40a7-b9d9-a4af3ab4005e)

数据库版本 SQLServer 2014和2019都有该问题

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前问题一为已知问题，是因为对sqlserver 的nvarchar这个字段类型目前无法支持，我们这边尝试修复与下；问题二数值类型不要带有引号；

**Comment by XiaJunjie2020** [comment]
该问题已修复。但SQL Server的中文字段类型，一般是nvarchar或nchar类型，在过滤时写为 where field = N'value' 或 where field in (N'value1', N'value2')，请确保SQL片段的准确性。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
