### ISSUE TITLE
[Bug]数据大屏批量锁定失效

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#12783]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
数据大屏批量锁定失效

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/9982f53a-7b68-4e35-bf86-e629be1535c2)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
