### ISSUE TITLE
[Bug]静态资源映射代码错误

### ISSUE THREAD

**Issue by xuewenquan** [dataease/dataease#12780]
**DataEase 版本**
dev2

**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**
Chrome

**Bug 描述**
代码中静态资源映射的前缀错误

**Bug 重现步骤(有截图更好)**
![image](https://github.com/user-attachments/assets/eeba30fa-e530-41c1-bf40-34998ce7d422)
正确的代码应该是：public static final String FILE_PROTOCOL = "file:";

**Comment by BBchicken-9527** [comment]
感谢反馈，经确认此处是没有问题的；

**Comment by BBchicken-9527** [comment]
感谢反馈，经确认此处没有发现问题；

**Comment by BBchicken-9527** [comment]
感谢反馈，经确认可能在windows下会存在问题，我们将会在下个版本进行修复；

**Comment by xuewenquan** [comment]
windows下肯定是有问题的。我还有一个建议，代码中都是写死的路径，强制将路径放在opt下面，我觉得是不合理的。正确的做法应该是路径可配置，默认使用与Jar同级的目录，如下：
![image](https://github.com/user-attachments/assets/c42890bd-8861-49d3-9178-e4b00c9cf71a)
![image](https://github.com/user-attachments/assets/c0658229-a121-4691-91e4-5e622c565365)

**Comment by xuewenquan** [comment]
> 感谢反馈，经确认可能在windows下会存在问题，我们将会在下个版本进行修复；

windows下肯定是有问题的。我还有一个建议，代码中都是写死的路径，强制将路径放在opt下面，我觉得是不合理的。正确的做法应该是路径可配置，默认使用与Jar同级的目录，如下：
![image](https://github.com/user-attachments/assets/ac62fd4d-02be-468e-8955-28d2b2faea32)
![image](https://github.com/user-attachments/assets/5122710f-6847-41d0-9fb2-d0456ae14e91)

**Comment by xuwei-fit2cloud** [comment]
https://github.com/dataease/dataease/commit/7b465a8c067eaef276734a894cbe21ecb5abf591

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
