### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by xingchenkobe123** [dataease/dataease#12782]
**DataEase 版本**
v1.18.24 

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
在线升级最新修正版 1.18.25
提示无最新版

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/dd5c3a08-1a3a-4847-b3d5-f396c5802abe)
2.
![d944f0144d84df4092281b116532b31](https://github.com/user-attachments/assets/99e578a8-ab8a-4e36-91d3-7c42f0146b4b)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题已经修复，你可以先在尝试一下；
