### ISSUE TITLE
[Feature]数据大屏移动的时候能不能直接拖动屏幕移动

### ISSUE THREAD

**Issue by Yiki380** [dataease/dataease#12787]
DataEase 版本:v2.10.0

**请描述您的需求或者改进建议.**大屏移动能便捷点吗，每次都得去拖动，上下可以用鼠标滚轮，左右就好难受

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。

**Comment by Yiki380** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
