### ISSUE TITLE
[Bug]v2.10.1 数据大屏跑马灯 在全屏或者预览模式下，不显示

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#12794]
![image](https://github.com/user-attachments/assets/254624ee-ba7f-477a-80f6-c73a58da6617)

![image](https://github.com/user-attachments/assets/6e008dad-3cdc-47cd-a210-12273fe9e3d7)

**Comment by xuwei-fit2cloud** [comment]
请等待新版本发布。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
