### ISSUE TITLE
SQL数据集不支持定时同步吗？

### ISSUE THREAD

**Issue by xix1** [dataease/dataease#12798]
使用版本  v1.15.0
创建sql数据集时只有直连选项，没有定时同步，是因为版本太低吗？

**Comment by xuwei-fit2cloud** [comment]
可能是DataEase对您选择的数据源还没有支持同步功能，可以参考文档：
https://dataease.io/docs/v1/user_manual/dataset_description/#2

**Comment by xix1** [comment]
谢谢！还想请教一下除了设置定时同步，还有什么办法可以提高数据查询速度吗？有些看板每次要转好几秒才转出来。我尝试在SQL语句中添加INDEX，但是会报错

**Comment by xuwei-fit2cloud** [comment]
直连模式的话，主要还是看数据库本身的查询速度了，添加索引是比较常用的方法。如果有报错的话，还请把报错信息贴出来看看，另外，还需要告诉我们使用的DataEase版本，以及数据源类型及对应版本。
