### ISSUE TITLE
[Feature]仪表板的当前数据集能快速定位在资源树上的具体位置

### ISSUE THREAD

**Issue by calvinit** [dataease/dataease#12799]
DataEase 版本:
2.10.1

**请描述您的需求或者改进建议.**
如果数据集（特别是有多层级文件夹的情况）有很多的话，如果不能记住它所在位置，需要一个一个尝试点开查看。

![location_quick](https://github.com/user-attachments/assets/74ddb91b-65dc-4d3e-a81c-15465a411097)

**Comment by xuwei-fit2cloud** [comment]
此处功能是用于切换数据集的，如果要对当前数据集进行编辑，可以点击边上的编辑图标。

**Comment by cv3x** [comment]
> 此处功能是用于切换数据集的，如果要对当前数据集进行编辑，可以点击边上的编辑图标。

对，有时候可能需要切换数据集，这个新数据集跟旧数据集在同一个文件夹目录内（但是不记得在哪个里面了），如果有定位功能，我能马上找到这个文件夹，然后快速找到它
