### ISSUE TITLE
[Feature]【图表】表格图表支持单元格内文本为链接时，点击链接跳转

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#12808]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
表格图表支持单元格内文本为链接时，点击链接跳转

**Comment by xuwei-fit2cloud** [comment]
在跳转设置里，将该字段的值作为跳转内容即可。
![图片](https://github.com/user-attachments/assets/6ec3215e-27fe-4e23-b20f-cb703eb52d37)

**Comment by xiebei-l** [comment]
收到，明白
