### ISSUE TITLE
[Question]dataease-v1.18.25是否支持opensearch?

### ISSUE THREAD

**Issue by DK-dzz** [dataease/dataease#12809]
**dataease-v1.18.25是否支持opensearch?**
CentOS Linux release 7.5.1804 (Core) 
dataease-offline-installer-v2.10.1-ce

操作过程(已确定dataease/opensearch均正常)：
添加数据源选ElasticSearch，
账号:略
密码:略
地址填https://192.168.1.120:9200
点击校验报：

数据源无效: java.lang.RuntimeException: HttpClient查询失败: {"error":"Incorrect HTTP method for uri [/_sql?format=json] and method [POST], allowed: [GET, DELETE, HEAD, PUT]","status":405}

![Uploading 321.png…]()

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前没有支持 OpenSearch 。
