### ISSUE TITLE
[Feature]数据集预览表格，当某个字段的内容很多时，应该截断内容（后面跟 ... 链接，点开时才显示完整内容）

### ISSUE THREAD

**Issue by calvinit** [dataease/dataease#12802]
DataEase 版本:
2.10.1

**请描述您的需求或者改进建议.**
![x](https://github.com/user-attachments/assets/d9e93cf4-37e4-40a2-bcbf-313f1183b37e)

**Comment by xuwei-fit2cloud** [comment]
我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
