### ISSUE TITLE
[Feature]仪表板或者数据大屏的分享功能是否能够支持全局配置开启或者关闭

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#12815]
DataEase 版本:

**请描述您的需求或者改进建议.**
支持对分享功能进行全局配置，全局开启或者全局关闭即禁用分享功能。
此需求主要是为了针对于部分公司，安全等级较高，保护仪表板和数据大屏的数据安全，防止被人分享出去。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，该需求已经加入需求池中，待有更多用户反馈后再进行下一步的规划。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
