### ISSUE TITLE
[Feature]查询组件按钮清空、重置支持字号调整

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#12823]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
查询组件按钮清空、重置支持字号调整
![image](https://github.com/user-attachments/assets/5b73f16c-a882-45d5-a5eb-90e2406b020f)

**Comment by xuwei-fit2cloud** [comment]
2.10.2版本支持按钮字体整体控制。
