### ISSUE TITLE
[Feature]v2 查询组件中，时间查询要类似时间范围查询的设置时间筛选范围这样的功能

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12822]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
v2 查询组件中，时间查询要类似时间范围查询的设置时间筛选范围这样的功能，而现在，这个是没有时间范围限制的，我们想做只能查询比如6个月内的数据，更早的就不让查询

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，您的建议很不错，该需求已经加入近期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
