### ISSUE TITLE
[Feature]图表数据导出功能，出现多种导出情况时，希望可以独立控制。

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#12840]
![image](https://github.com/user-attachments/assets/c0da7f1f-19d2-4ed1-aa4f-aa1835949096)
如上图，现在只能要么都禁止导出，要么都支持导出；希望支持可以禁用导出明细可以导出汇总后的；或者反过来。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池中，近期暂时没有计划进行支持。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
