### ISSUE TITLE
[Bug]数据大屏明细表在组合中调节列宽时，整个组合都会移动

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#12845]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
数据大屏明细表在组合中调节列宽时，整个组合都会移动
https://github.com/user-attachments/assets/5b3067b4-a3b5-4dc9-8489-cdde853a6652

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你描述的问题，可以尝试一下是否是毕现的问题，因为在使用当中可能会因为缓存或内存等原因导致前端计算的时候产生问题；
