### ISSUE TITLE
[Feature] 时间范围默认截止时分秒 23:59:59

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#12850]
DataEase 版本:
v2.10.2

**请描述您的需求或者改进建议.**
时间范围默认点击后是 00:00:00-00:00:00，默认点击后 00:00:00 - 23:59:59 会更符合使用习惯
<img width="648" alt="企业微信截图_17296667486092" src="https://github.com/user-attachments/assets/98eb91b0-00f7-4467-aa01-23f6007e02a6">
<img width="617" alt="企业微信截图_4407c314-1457-46ff-971e-606d5487cfcd" src="https://github.com/user-attachments/assets/17949d5d-1aa8-4bae-bc78-ea425ec43c3c">

以下情况比较合理
<img width="393" alt="企业微信截图_b635d17b-5202-426d-b3e4-a11cb600aef5" src="https://github.com/user-attachments/assets/669b8c6a-28b9-433b-9d90-9b5aacfa5bfd">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
