### ISSUE TITLE
[Feature]查询条件设置里面，选择数据集中，排序字段需要支持自定义排序

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12852]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
查询条件设置里面，选择数据集中，排序字段需要支持自定义排序。目前是只有升序降序排序，但很多时候选项的优先级是不一样的，有些优先级需要前置，虽然可以用一个规定顺序的字段来升降序自定义，但是有时候数据本身无序，又得调整数据集了，需要这个支持，就像 图表-数据-维度-排序-自定义排序 那样的设置

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已经规划在 v2.10.3 版本中实现，请等待该版本的发布。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
