### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by BaleW123** [dataease/dataease#12855]
**DataEase 版本**

1.18.25

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
谷歌浏览器125.0.6422.142（正式版本） （64 位）

**Bug 描述**
移动端定时刷新或者手动触发刷新后，外部参数-下拉组件-数据集where参数过滤失效；PC端没有这个问题。

**Bug 重现步骤(有截图更好)**
1.外部参数关联下拉组件过滤
![image](https://github.com/user-attachments/assets/6807efcb-589e-4052-a0ea-f133d3d3bf79)
![image](https://github.com/user-attachments/assets/31b9a461-2a47-4421-b993-d882fc9b19a4)
2.下拉组件关联数据集的参数，首次进入报表过滤正常
![image](https://github.com/user-attachments/assets/b5002d12-6352-45c2-859e-a2d984e07e62)

3.定数刷新后，过滤失效
![image](https://github.com/user-attachments/assets/afa45561-f1c1-4eae-b0f4-53eecd76896e)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，我这边测试了两种刷新，分别是刷新频率和整体刷新，你是否有对代码做了修改？不确定你是否改动和以及打包方式都有可能存在问题，建议你加入我们的交流群，上面有非常专业的同学会实时的回复你的问题，方便你快速并精准的定位到你的问题所在；
