### ISSUE TITLE
[Feature]查询组件下拉框宽度需要优化

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12853]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
查询条件的下拉框宽度是跟着查询条件的宽度来变的，现在查询条件的宽度设成一些值的时候，下拉框的内容就显示不全了。这个需要调整一下，比如可以根据内容自动调整下拉框宽度，或者可以自定义设置每个下拉框的宽度，这样适用度会比较广一些。
![image](https://github.com/user-attachments/assets/7a881528-56a2-4d6d-a784-9fc1aeb6edc9)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中优化一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
