### ISSUE TITLE
[Feature]使用查询组件之后跳转到其他仪表板可以带过去查询条件

### ISSUE THREAD

**Issue by jstbw** [dataease/dataease#12866]
DataEase 版本:
2.10.1

**请描述您的需求或者改进建议.**
使用查询组件之后跳转到其他仪表板可以带过去查询条件
比如一个仪表板展示的是所有人员全年的概览数据，另外一个仪表板是详细数据，设置了点击人名跳转到第二个仪表板。
在第一个仪表板设置查询组件，选择当月，第一个仪表板会过滤为当月的全员数据，点击一个人名跳转到第二个仪表板就只展示当月数据，同样的，选择上个月，跳转之后则展示上个月数据

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先讨论后再回复您。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经加入近期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
