### ISSUE TITLE
[Bug]sql数据集动态传参问题

### ISSUE THREAD

**Issue by gongjing123** [dataease/dataease#12877]
**DataEase 版本**
dataease-1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
dataease-helm-1.18.14    helm方式容器运行

**浏览器版本**

Google  129.0.6668.101
**Bug 描述**
动态传参时sql数据集报错，但是随便写死一个参数时数据集可以正常展示数据

**Bug 重现步骤(有截图更好)**
1.
![20241024-135603](https://github.com/user-attachments/assets/cf34513d-61ca-4eff-a187-4a8fa2952590)

2.
![20241024-135632](https://github.com/user-attachments/assets/98f956d5-97cf-42cb-b1e1-07bcb34dd05a)

3.![20241024-135639](https://github.com/user-attachments/assets/b18e33f4-7829-4879-a001-d7635ddcb797)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你是用的是什么数据源？我们这边模拟一下；

**Comment by gongjing123** [comment]
> 感谢反馈，请问你是用的是什么数据源？我们这边模拟一下；

查询数据源是mysql8，dataease本身数据库没做改动

**Comment by XiaJunjie2020** [comment]
你好，文本类型参数，请在SQL参数外加上单引号。如 where production_line_code = '${linCode}'

**Comment by gongjing123** [comment]
> 你好，文本类型参数，请在SQL参数外加上单引号。如 where production_line_code = '${linCode}'

谢谢，加上单引号就ok了，另外请问下sql数据集里面可以调用MySQL的函数存储过程吗，刚刚试了下貌似不行
![call](https://github.com/user-attachments/assets/85e49370-f107-4f9d-8aa4-6c8e9199c059)

**Comment by XiaJunjie2020** [comment]
> > 你好，文本类型参数，请在SQL参数外加上单引号。如 where production_line_code = '${linCode}'
> 
> 谢谢，加上单引号就ok了，另外请问下sql数据集里面可以调用MySQL的函数存储过程吗，刚刚试了下貌似不行 ![call](https://private-user-images.githubusercontent.com/44971287/380355421-85e49370-f107-4f9d-8aa4-6c8e9199c059.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MDk2NDYsIm5iZiI6MTcyOTkwOTM0NiwicGF0aCI6Ii80NDk3MTI4Ny8zODAzNTU0MjEtODVlNDkzNzAtZjEwNy00ZjlkLThhYTQtNmM4ZTkxOTljMDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDAyMjIyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMDIxMWVjMDNmMDg3YjFmYjVkOWJkNmI4ZGU5YmU1ODNkZmU1Nzk0YTBkNmJiNjg0MzY4ODMzOTcwZjE3MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rlEv4DUlJV-SAWEbHrwGgk11aC4eL-qY23-Iey1tNYc)

是的，不支持调用存储过程
