### ISSUE TITLE
[Bug] 文本组件的样式拦遮挡文本内容

### ISSUE THREAD

**Issue by limin-fit2** [dataease/dataease#12872]
**DataEase 版本**
v1.18.25

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 129.0.6668.101（正式版本） (arm64)

**Bug 描述**
      在仪表板中放了一个tab组件，在tab组件放置文本组件，隐藏tab组件的标题后，文本组件样式拦遮挡了文本内容

**Bug 重现步骤(有截图更好)**
1.
<img width="1234" alt="image" src="https://github.com/user-attachments/assets/c4144412-042e-4fdd-bdbe-bfabbaf89a41">

2.
<img width="1109" alt="image" src="https://github.com/user-attachments/assets/8af28ce5-519d-478b-8aa4-0d54d03af7ae">

3.
<img width="1303" alt="image" src="https://github.com/user-attachments/assets/1760f1df-21a6-457f-a879-d4156cad43ee">
<img width="1022" alt="image" src="https://github.com/user-attachments/assets/43398bcb-ee80-4351-b890-2debef18e6c8">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
受限于第三方组件，暂时无法处理。
