### ISSUE TITLE
[Feature]明细表、汇总表支持同类项合并展示

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#12880]
DataEase 版本:

**请描述您的需求或者改进建议.**
类似于下图：
![image](https://github.com/user-attachments/assets/5b088e8e-1e15-4730-aece-411a682abf7a)

**Comment by xuwei-fit2cloud** [comment]
该需求已在近期的开发计划中。

**Comment by xuwei-fit2cloud** [comment]
明细表支持合并功能。
