### ISSUE TITLE
[Bug] 仪表板视图名字带 / 导出 Excel 会失败

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#12883]
**DataEase 版本**
v1.18.25
v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌

**Bug 描述**
![image](https://github.com/user-attachments/assets/a38a23e3-7b43-450e-adf0-363d2d23b452)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
