### ISSUE TITLE
[Bug]数据大屏 TAB 内部的组件位置 XY 是以 TAB 为基准的，而外部标尺却可以识别到这个组件以大屏位置为基准的标尺

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#12886]
**DataEase 版本**
V2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
数据大屏 TAB 内部的组件位置 XY 是以 TAB 为基准的，而外部标尺却可以识别到这个组件以大屏位置为基准的标尺。
是否可以统一以外部的位置计算？

https://github.com/user-attachments/assets/3a3664de-68d8-48b7-800c-d38800c08b82

**Comment by BBchicken-9527** [comment]
感谢反馈，目前暂时无法做到tab组件内外统一，因为理论上tab组件相当于一个新的画板，所以x与y是存在区分的；
