### ISSUE TITLE
[Bug查询组件级联的级联状态不能重置

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12885]
**DataEase 版本**
谷歌

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
最新

**Bug 描述**
查询组件级联的级联状态不能重置

**Bug 重现步骤(有截图更好)**
1.新建一个明细表
2.新建查询组件，4个查询条件，1、2、3、4
3.设置级联，1-2，2-3，1-3，1-4
4.发现保存后，正常选择，点击重置，发现后面的级联不能重置，还有原数据

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
