### ISSUE TITLE
[Feature] 富文本优化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#12889]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
当前富文本内容超长后只能换行，并且当高度不足时会出现滚动条，是否可以支持如下功能，
1、不换行，文字溢出时...展示，鼠标悬浮能展示完整内容，
2、不换行，根据实际宽度动态缩放文字大小，使内容完整展示。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，目前使用的第三方组件无法支持上述需求。
