### ISSUE TITLE
[Question]本地不能编译，使用版本 V2.9

### ISSUE THREAD

**Issue by silloy** [dataease/dataease#12882]
**请描述您的问题.**
[INFO] 
[INFO] core ............................................... SUCCESS [  0.451 s]
[INFO] core-frontend ...................................... SUCCESS [04:00 min]
[INFO] core-backend ....................................... FAILURE [  0.538 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:01 min
[INFO] Finished at: 2024-10-24T14:07:51+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project core-backend: Could not resolve dependencies for project io.dataease:core-backend:jar:2.9.0
[ERROR] dependency: io.dataease:api-base:jar:2.9.0 (compile)
[ERROR] 	io.dataease:api-base:jar:2.9.0 was not found in https://repository.fit2cloud.com/repository/fit2cloud-public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of fit2cloud-public has elapsed or updates are forced
[ERROR] 	io.dataease:api-base:jar:2.9.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
[ERROR] dependency: io.dataease:api-permissions:jar:2.9.0 (compile)
[ERROR] 	io.dataease:api-permissions:jar:2.9.0 was not found in https://repository.fit2cloud.com/repository/fit2cloud-public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of fit2cloud-public has elapsed or updates are forced
[ERROR] 	io.dataease:api-permissions:jar:2.9.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
[ERROR] dependency: io.dataease:api-sync:jar:2.9.0 (compile)
[ERROR] 	io.dataease:api-sync:jar:2.9.0 was not found in https://repository.fit2cloud.com/repository/fit2cloud-public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of fit2cloud-public has elapsed or updates are forced
[ERROR] 	io.dataease:api-sync:jar:2.9.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
[ERROR] 
[ERROR] -> [Help 1]

**Comment by xuwei-fit2cloud** [comment]
所需jar包的源码在sdk目录下，可以参考文档：
https://dataease.io/docs/v2/installation/deployment_installation/#32
