### ISSUE TITLE
[Bug]双轴组合图取消平滑只对一条线生效

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#12894]
**DataEase 版本**
v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**
谷歌

**Bug 描述**
双轴组合图取消平滑只对一条线生效
![image](https://github.com/user-attachments/assets/a560cc2e-a92a-43be-bc82-66cb21bea037)
![image](https://github.com/user-attachments/assets/e6ea5489-1c85-45ee-9d7d-b4477454a919)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
