### ISSUE TITLE
[Bug]数据大屏Tab 组件，排列好的位置，保存刷新后，内部组件位置大小错乱

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#12898]
**DataEase 版本**
V2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
数据大屏Tab 组件，排列好的位置，保存刷新后，内部组件位置大小错乱

![image](https://github.com/user-attachments/assets/4a5af88c-71f2-4a33-acfc-2dee2a0cb3a4)
<img width="477" alt="image" src="https://github.com/user-attachments/assets/e65cfcd7-d19a-416b-a678-5585a90ee282">

**Comment by ziyujiahao** [comment]
[8d6de683d26e115380c00592faaac6b92a143596](https://github.com/dataease/dataease/commit/8d6de683d26e115380c00592faaac6b92a143596)

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
