### ISSUE TITLE
[Feature]数据大屏 Tab 组件可点击区域太小，只集中在文字上，而不是选项框上

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#12899]
DataEase 版本:
V2.10.1

**请描述您的需求或者改进建议.**
数据大屏Tab组件ke可点击区域太小，只集中在文字上，而不是选项框上

https://github.com/user-attachments/assets/aa03d82b-8f3a-47d1-bff5-dfe1459c9e21

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已经加入近期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
