### ISSUE TITLE
[Bug] 使用明细表展示Excel内容时，列宽设置问题

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#12908]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**
离线

**浏览器版本**
最新版

**Bug 描述**
使用明细表，展示EXCEL内容是，列宽需要设置很大才能显示全部内容，自适应和固定列宽都测试了，后面会有很大的留白，这一块是不是没有做换行处理？

**Bug 重现步骤(有截图更好)**
<img width="1677" alt="25c456425e2ca486ca988460893fd11" src="https://github.com/user-attachments/assets/6911b011-01d8-430a-8b79-c20eb7ea955b">

![image](https://github.com/user-attachments/assets/83c3d460-74a1-4b08-92f8-fabdbf0ee261)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前表格无法支持换行，后续有较优的方案会对此处进行优化，目前暂时无法处理；
