### ISSUE TITLE
[Bug] 跳转关联查询组件时偶现查询组件显示内容与过滤内容不符问题

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#12909]
**DataEase 版本**
 v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新

**Bug 描述**
如视频，父仪表板关联了子仪表板的两个查询组件，但跳转有时带过去了查询条件但没有按查询条件正确过滤数据。比如点击 C 公司实际显示 B 公司。
![image](https://github.com/user-attachments/assets/9629cf80-0d54-45ac-8430-f467b0b6d42f)

https://github.com/user-attachments/assets/e97d65f7-358e-4d79-8fc6-6a8ad47fd7b7

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
