### ISSUE TITLE
[Feature]希望雷达图可以支持更改折点和颜色覆盖，如下图这样

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#12916]
![bd6554b88b2c125e246d920effa17b5](https://github.com/user-attachments/assets/80e1bda7-9244-4c55-a398-2ed987c2118e)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经规划至近期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
