### ISSUE TITLE
[Question] v2.10.1 源码执行maven  clean package 失败

### ISSUE THREAD

**Issue by sunshineshenjin** [dataease/dataease#12919]
**请描述您的问题.**

从项目中的 release 页面直接下载 v2.10.1 的源码，IDEA 打开后，执行 mvn clean package -Pstandalone -U -Dmaven.test.skip=true
命令时，出现编译报错问题， 是否是源码提交的遗漏问题 ？（未改动任何源码）

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:30 min
[INFO] Finished at: 2024-10-25T17:44:41+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project core-backend: Compilation failure: Compilation failure: 
[ERROR] /Users/xx/dataease-2.10.1/core/core-backend/src/main/java/io/dataease/copilot/api/CopilotAPI.java:[15,23] 程序包org.json.simple不存在
[ERROR] /Users/xx/dataease-2.10.1/core/core-backend/src/main/java/io/dataease/dataset/utils/TableUtils.java:[7,39] 程序包org.apache.calcite.avaa.util不存在
[ERROR] /Users/xx/dataease-2.10.1/core/core-backend/src/main/java/io/dataease/datasource/provider/ApiUtils.java:[20,23] 程序包org.json.simple不存在
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

<img width="1364" alt="image" src="https://github.com/user-attachments/assets/28775897-10f1-470c-baa2-8d54d81d6ee4">

**Comment by xuwei-fit2cloud** [comment]
可以参考一下在线文档中的步骤：
https://dataease.io/docs/v2/installation/deployment_installation/#32
