### ISSUE TITLE
[Feature]移动端的适配

### ISSUE THREAD

**Issue by 13813586515** [dataease/dataease#12915]
DataEase 版本:
2.1.0

**请描述您的需求或者改进建议.**
现在一个仪表盘做好之后，在移动端的适配真的是一言难尽啊，尤其是指标卡，现在指标卡一个指标卡只能放一个指标，但是移动端是不可能像pc端有那么大的空余空间可以放那么多的豆腐块，只能退而求其次选择富文本，这个富文本组件，你们用的真的不难受吗，格式没法调整，表格插入之后光标一直飘，各种难用，跪求官方出几个移动端的模版

**Comment by ziyujiahao** [comment]
目前在V2.10.2中计划支持移动端的独立样式设计，可以等到我们发布尝试一下

**Comment by xuwei-fit2cloud** [comment]
请升级版本。
