### ISSUE TITLE
[Bug]v2版本，click house数据源，图表过滤功能，日期字段不能正常转换

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#12913]
![image](https://github.com/user-attachments/assets/8c7c032f-72ac-48c3-977a-7152da0c7768)
![761e8b3b2ec481930b40a901b4ac30f](https://github.com/user-attachments/assets/bd533ddb-8c94-471b-a0e0-caf50c82c1a1)

![396a74adcfb29dbdf49ebb47ed81538](https://github.com/user-attachments/assets/e483faae-7215-480c-b202-5ebe25ff64cb)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
