### ISSUE TITLE
[Bug] 透视表树形结构行小计不计算

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#12928]
**DataEase 版本**
v2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌

**Bug 描述**
透视表拖入【数据行/维度】和【数据列/指标】，【行汇总】小计聚合方式平均，平铺展示可以，开启树形展示，无效果

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/2e737588-3236-468b-b18a-a3a9d7a9eea7)

2.
![image](https://github.com/user-attachments/assets/bd452e0b-8a93-4fd0-aa5e-9d021ffac956)

3.平铺模式生效，改为树形展示无效果
![image](https://github.com/user-attachments/assets/f1a11b2a-61f9-4e92-b62f-b65c24f3b150)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
