### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Fit2CloundGhh** [dataease/dataease#1292]
**DataEase 版本**
V1.4.1

**浏览器版本**
 95.0.4638.69

**Bug 描述**
这个issue应该是个bug+需求。
问题现象：
![image](https://user-images.githubusercontent.com/92966838/143554666-c9965038-fb64-4e7b-8487-41704ef571cc.png)
在新增计算字段（计算的规则不符合sql语法标准），可以保存成功，刷新数据集的时候，就会提示出错

**Bug 重现步骤(有截图更好)**
1.新增错误的sql语法计算字段
2.点击保存，保存成功
3.再次刷新计算集

**Comment by yayanpei** [comment]
感谢您的反馈，此处优化已经在计划中，在新建计算字段保存时，支持校验，如果不符合规则当即给出提示。

**Comment by xuwei-fit2cloud** [comment]
v1.7.0版本已对该问题进行处理。
