### ISSUE TITLE
[Bug]明细表的自定义单元格宽度问题

### ISSUE THREAD

**Issue by JOJO30317** [dataease/dataease#12925]
**DataEase 版本**
V2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome最新

**Bug 描述**
当设置自定义宽度，两列各设置50%时，如果数据过多，有滚动条时，仍然会显示横向滚动条

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/3c22611a-5666-4497-b615-e9985586f1ba)

**Comment by BBchicken-9527** [comment]
感谢反馈，方便说明一下你的操作步骤吗？我们这边尝试复现一下；

**Comment by JOJO30317** [comment]
> 感谢反馈，方便说明一下你的操作步骤吗？我们这边尝试复现一下；

只要列的宽度加起来是100%，都会有横向滚动条。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，可以尝试升级最新版本看看；
