### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by githubxiaoou** [dataease/dataease#12930]
DataEase 版本: 2.10.1

![企业微信截图_17298430048685](https://github.com/user-attachments/assets/55ef838d-b823-4686-85df-6c322c7cd398)

**请描述您的需求或者改进建议.**
建议雷达图可以实心显示（如图），并且可以设置去掉标点圆圈。

**Comment by githubxiaoou** [comment]
修改title

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #12916
