### ISSUE TITLE
[Bug] 图表数据导出，部分导出数据不是十进制格式

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#12946]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
图表数据导出，部分导出数据不是十进制格式

**Bug 重现步骤(有截图更好)**
<img width="1446" alt="image" src="https://github.com/user-attachments/assets/73749953-279f-4359-87d5-8407fec1bb28">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行优化；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
