### ISSUE TITLE
[Feature] ticket 最大数限制放宽一些

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12944]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
（建议）ticket 最大数限制放宽一些，这个会用到的应用场景大概是给每个部门自动生成 Ticket 、指标各个品类的链接等，限制了这个功能有一定的局限。

**Comment by xuwei-fit2cloud** [comment]
我们讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划调整，建议使用行列权限，控制各个部门对仪表板数据的查看。
