### ISSUE TITLE
[Feature]  明细表里面如何显示图片？

### ISSUE THREAD

**Issue by gongjing123** [dataease/dataease#12941]
DataEase 版本:

**请描述您的需求或者改进建议.**
我的明细表里面有个字段是头像，我希望显示图片出来，目前没有看到在哪配置
![image](https://github.com/user-attachments/assets/3f2491ab-6e8a-4ab2-9c18-202df0c65f53)

**Comment by xuwei-fit2cloud** [comment]
请参考文档：
https://dataease.io/docs/v2/change-v2-10/#17

**Comment by gongjing123** [comment]
> 请参考文档： https://dataease.io/docs/v2/change-v2-10/#17

请问这个只有V2版本才支持，V1版本不支持对吗

**Comment by xuwei-fit2cloud** [comment]
v1版本目前不支持。
