### ISSUE TITLE
[Bug]本地编译，前端代码引用出错

### ISSUE THREAD

**Issue by tgluon** [dataease/dataease#12943]
**DataEase 版本**
dev

**运行方式(安装包运行 or 源码运行 ?)**
本地编译
![image](https://github.com/user-attachments/assets/f130494d-f81f-410b-9f41-b42faba18fe2)

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
重启一下编辑器试试？代码没有问题的。

**Comment by tgluon** [comment]
@xuwei-fit2cloud 
![image](https://github.com/user-attachments/assets/71511662-a2ee-4cf2-9c1e-2f93ed444563)
编译还是报这里有错

**Comment by dataeaseShu** [comment]
依赖删了 重新安装一遍

**Comment by tgluon** [comment]
@dataeaseShu  我在package.json   引入codemirror 依赖就可以了。
