### ISSUE TITLE
[Bug] 基础柱状图支持指标排序，但是组合图，例如柱线组合图不支持指标排序

### ISSUE THREAD

**Issue by RedCG** [dataease/dataease#12957]
**DataEase 版本**
V2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
最新版本

**Bug 描述**
基础柱状图支持指标排序，但是组合图，例如柱线组合图不支持指标排序。
![image](https://github.com/user-attachments/assets/35497552-bb95-4a2b-b98a-6f8dbd8ccf32)
![image](https://github.com/user-attachments/assets/695d3a13-2907-48f6-aa72-650777fc8625)

**Bug 重现步骤(有截图更好)**
1.如描述所述

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，组合图目前仅支持根据类别轴排序，该图表类型比较特殊，如果根据左、右值轴中的指标排序，图表渲染时会有数据错乱的情况，因此暂不支持根据左、右值轴中的指标进行排序。
