### ISSUE TITLE
[Feature]折线图等图表支持旋转只改变文字排列，不改变文字方向

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12959]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
折线图等图表支持旋转只改变文字排列，不改变文字方向。
现在的旋转只能同时改变，能不能只改变排列方式？
![image](https://github.com/user-attachments/assets/aa784021-f759-435d-b566-bda463cf69a9)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，轴标签是整体旋转的，因此图库不支持改变文字排列，不改变文字方向。
