### ISSUE TITLE
[Feature] 希望可以设置查询组件的内边距

### ISSUE THREAD

**Issue by githubxiaoou** [dataease/dataease#12960]
DataEase 版本: 2.10.1
![image](https://github.com/user-attachments/assets/64cc0598-b051-464c-9261-366ec8165e71)
![image](https://github.com/user-attachments/assets/42fe56cd-a08f-45a4-8f3b-7665971061a1)

**请描述您的需求或者改进建议.**
查询组件的内边距无法设置，导致包括但不限于组件无法准确设置在大屏中的位置等问题

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经加入近期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
