### ISSUE TITLE
[Feature]分布图类图库增加高级-空值处理选项

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12961]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
分布图类图库增加高级-空值处理选项
分布图类像环形图这类还没有空值处理选项，其他的线/柱类等的这些有的

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
已线下沟通，用户是想过滤掉维度为null的数据，已建议使用图表过滤器。
