### ISSUE TITLE
[Bug] ID长度被限制，导致数据查询不正确

### ISSUE THREAD

**Issue by Hexcpp** [dataease/dataease#12971]
**DataEase 版本**
2.10

**运行方式(安装包运行 or 源码运行 ?)**
1panel应用商店安装

**浏览器版本**
Microsoft Edge
版本 130.0.2849.56 (正式版本) (64 位)

**Bug 描述**
数据集问题：
主表左连接其他表ID长度被限制，导致查询出来的数据不正确
如ID：151440526046334976、151440526046334977 在左连接时被截断为15144052604633497，导致查询出来的数据不正确
![image](https://github.com/user-attachments/assets/efc4c118-498a-41aa-8502-4db5a3fb81f6)
![image](https://github.com/user-attachments/assets/f00e8a24-ec1b-4b4a-9bc0-66fa3aa9f5fe)

**Bug 重现步骤(有截图更好)**
1. 新建数据库表
2. 创建关联表
3. 填写数据（主键ID需要超过18未，ID类似且最后一位不同更易复现）
4. 在DataEase中创建数据集并且关联相关表
5. 创建仪表盘，查看数据

**Comment by BBchicken-9527** [comment]
感谢反馈，经过验证应该是js精度丢失导致，目前看受限于图库暂时没有较优的方式解决这个问题，可以考虑到这种id不会去做数值的指标运算，可以将id字段转成文本，这样就不会因为精度导致显示与实际不一致的问题；
