### ISSUE TITLE
[Bug]自适应表格的列宽换行后还是按照全部字数来计算宽度

### ISSUE THREAD

**Issue by kuangyoubo** [dataease/dataease#12984]
**DataEase 版本**
v1

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**
chrome 126.0.6478.127

**Bug 描述**
自适应表格的列宽换行后还是按照全部字数来计算宽度，这样看起列就很宽了。比如：
“今年
赔付率”

按理是根据“赔付率”来计算宽度，实际上按照“今年赔付率”来计算宽度了。实际情况我们有10多个字的列标题，看起就太宽了。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，目前暂时没有想到较优的解决方案，若后续有比较完整的方案会进行优化，但目前没有办法完成；
