### ISSUE TITLE
[Feature]数据集目录对文件夹的权限没有批量操作，复制功能，使用体验不太友好

### ISSUE THREAD

**Issue by daiqingyao6238** [dataease/dataease#12982]
DataEase 版本:

2.10.1
**请描述您的需求或者改进建议.**

我的数据集目录里头有嵌套文件夹，一个个移动，复制很不方便，能否出个批量操作，复制的功能。

![111](https://github.com/user-attachments/assets/d517583f-e7e5-4e27-82c6-3807fc2bd273)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们尝试优化移动的交互。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
