### ISSUE TITLE
[Bug]在当前页面无法打开新报表

### ISSUE THREAD

**Issue by kuangyoubo** [dataease/dataease#12985]
**DataEase 版本**
v1

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
在当前页面无法打开新报表，不能在本页的弹出层中用iframe打开一张新报表，现在只能新弹出一个窗口打开。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by maninhill** [comment]
v1版本已停止接受新需求，望理解。

**Comment by kuangyoubo** [comment]
> v1版本已停止接受新需求，望理解。

@maninhill 请问v1迁移到v2有教程没有？
