### ISSUE TITLE
无法访问浏览器，重启dataease 提示：Error response fram daemon: failed to create task for container: dial unix /run/containerd/s/7h5429eh88916d885033b48438mdclc2h52943661458f6199b0a2501c98d7d9:connect: connection refused:unknown

### ISSUE THREAD

**Issue by TMACys** [dataease/dataease#12987]
无法访问浏览器，重启dataease 提示：Error response fram daemon: failed to create task for container: dial unix /run/containerd/s/7h5429eh88916d885033b48438mdclc2h52943661458f6199b0a2501c98d7d9:connect: connection refused:unknown
![WechatIMG1469](https://github.com/user-attachments/assets/fc8e98cc-e1d1-4cb1-9b1d-06431524fba7)

**Comment by xuwei-fit2cloud** [comment]
可以加一下我们的社区群，我们远程帮你看看。
![图片](https://github.com/user-attachments/assets/f21ef997-77de-4cc2-9abd-538283bd40f9)
