### ISSUE TITLE
[Bug]文本下拉组件切换数据集后再变更为下拉树无法获取数据问题

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#12990]
**DataEase 版本**
 2.10.1lts

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新

**Bug 重现步骤(有截图更好)**
1.新建仪表板，添加一个明细表
![image](https://github.com/user-attachments/assets/63f9bbd9-acf1-4247-8657-7f23eedaf9b8)

2.添加一个查询组件，查询组件中选择一个文本类型的维度，展示类型选择文本下拉，选项值来源选择数据集，且选择一个与图表数据集不一致的另外一个数据集。
![image](https://github.com/user-attachments/assets/98847758-6c64-46aa-a282-41dccfe5ea28)

3.将展示类型切换为下拉树
4.此时，编辑下拉树时，层级一变成了请选择，层级二下拉选项变成了第二步选择的下拉选项，且保存后，下拉树显示无数据
![image](https://github.com/user-attachments/assets/3e7d941e-ff7f-4061-9766-57bf0501dc9e)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
