### ISSUE TITLE
[Feature]图表基础样式的自定义配色方案在设置时，能不能每个字段先从预设的几个颜色中去选择，选择后再根据需要做自定义色号的设置。比如像 值轴/指标 那样可以上下拖动预设颜色的顺序。

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#12994]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
图表基础样式的自定义配色方案在设置时，能不能每个字段先从预设的几个颜色中去选择，选择后再根据需要做自定义色号的设置。比如像 值轴/指标 那样可以上下拖动预设颜色的顺序。

字段和前面的颜色现在是纵向排列，如果要改的话，字段部分不用动，颜色部分像自定义排序那样的可拖拽，就能实现我说的这种效果
![ab51fa9ff1f1c19bf2c380a99e3ab6f](https://github.com/user-attachments/assets/6f3deb18-ad58-4deb-9394-42f6757fff8c)

不然的话，给了这么多套配色方案，但颜色的顺序是固定的，实际使用时，多个字段的颜色要前后调整时，还是要一个一个去改色号，就变得很麻烦。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划调整，系统提供的配色方案是仅供参考，可根据自身需要再自定义颜色。
