### ISSUE TITLE
[Bug]Excel数据集某列设置为数据验证之后，视图的过滤器筛选失效了

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#1299]
**DataEase 版本**
1.4.1

**浏览器版本**
chrome 96.0.4664.55

**Bug 描述**
Excel 数据集某列设置为数据验证之后，过滤器筛选失效了
同样的Excel文件，只需要把改列的数据验证取消之后，过滤器还是正常的

**Bug 重现步骤(有截图更好)**
1.带有数据严重的Excel数据集
![image](https://user-images.githubusercontent.com/46042812/143804310-386580bc-5bdf-40f0-a27e-dfd633f84eb1.png)

2.筛选
![image](https://user-images.githubusercontent.com/46042812/143804949-16a33ccd-3263-48a6-8b14-e46517b0612e.png)

3.筛选失效
![image](https://user-images.githubusercontent.com/46042812/143804506-0566e94b-470f-4d06-b704-e0810fa23d8f.png)

**Comment by xuwei-fit2cloud** [comment]
我们确认一下

**Comment by xuwei-fit2cloud** [comment]
该问题一直未重现。
