### ISSUE TITLE
[Bug]数据集自定义的SQL保留的小数和数据预览保留的小数不一致,导出的明细表Excel没有保留页面设置的小数点位数

### ISSUE THREAD

**Issue by LiaoMinYu** [dataease/dataease#12997]
**DataEase 版本**

dev-v2

**运行方式(安装包运行 or 源码运行 ?)**
源码运行
安装包运行
**浏览器版本**

**Bug 描述**
1：数据集的SQL 金额字段是保留两位小数，但是在数据预览保留的是8位小数点。导致数额较大的变成了e+
2：明细表类型的报表，金额字段设置小数点位数2，但是导出来的数值是保留8位小数。导致报表和导出的Excel的数据呈现不一致

**Bug 重现步骤(有截图更好)**
![image](https://github.com/user-attachments/assets/4497058c-6ff0-45da-a1ea-c2d41c47b09b)
![image](https://github.com/user-attachments/assets/d59c9fbb-9e56-41ec-b922-4acb449fee59)
![image](https://github.com/user-attachments/assets/83e18d78-5695-43a0-a48a-e2d1b51b7b8b)
![image](https://github.com/user-attachments/assets/beab79d0-1583-424c-a6d8-bed515b5cdf7)

**Comment by BBchicken-9527** [comment]
感谢反馈，保留八位小数是我们强制进行的八位截取的，确保在图表中如果你需要更精准的数值时可以有更多的位数可以显示，导出目前测试环境没有发现你说的问题，方便问一下你使用的什么数据源和什么类型的字段吗？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
