### ISSUE TITLE
仪表盘分享公共连接地址为localhost，无法访问

### ISSUE THREAD

**Issue by plateauandsp** [dataease/dataease#13]
![image](https://user-images.githubusercontent.com/30932762/123370685-d1760600-d5b2-11eb-8959-73b5883cd7ee.png)

**Comment by fit2cloud-chenyw** [comment]
fixed on commit b717b40
 detail https://github.com/dataease/dataease/commit/b717b406b2d93da5e11c866dc892e0a3149cd665

**Comment by xuwei-fit2cloud** [comment]
请等待下个版本 v1.0.1 发布。

**Comment by xuwei-fit2cloud** [comment]
v1.0.1 已发布
