### ISSUE TITLE
[Bug]导出图片不显示地图图表

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#13004]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

谷歌浏览器
**Bug 描述**

点击【导出】，导出的图片没有地图，缺少
**Bug 重现步骤(有截图更好)**
1.
<img width="1112" alt="image" src="https://github.com/user-attachments/assets/b86fc509-4f8c-4a89-b8f2-52730a7782e7">

2.
<img width="1313" alt="image" src="https://github.com/user-attachments/assets/42358389-1a71-4618-96cc-b8ed7687ba2f">

**Comment by xuwei-fit2cloud** [comment]
已知问题，暂时无法解决。
