### ISSUE TITLE
[Feature] 查询组件的字体偏模糊

### ISSUE THREAD

**Issue by LiaoMinYu** [dataease/dataease#13000]
DataEase 版本:

源码运行最新版 dev-v2
**请描述您的需求或者改进建议.**
报表字体和查询组件的字体对比，可以明显看出查询组件的字体偏模糊，看到社区这边是有提交了该优化建议，但是运行了最新版还是能明显看出模糊，调试发现取消样式：box-sizing: border-box 字体正常
希望能优化清晰度
![image](https://github.com/user-attachments/assets/9d4e9a2f-bcd6-48fc-a706-84d0e85d614b)

![image](https://github.com/user-attachments/assets/44bdaa8a-002b-4b8c-9b0a-ed8d56ceacb4)

**Comment by dataeaseShu** [comment]
缩放的问题 和这个属性没关系 [CSS](https://developer.mozilla.org/zh-CN/docs/Web/CSS) 中的 box-sizing 属性定义了 [user agent](https://developer.mozilla.org/zh-CN/docs/Glossary/User_agent) 应该如何计算一个元素的总宽度和总高度
