### ISSUE TITLE
[Question] 前端build报错 

### ISSUE THREAD

**Issue by fy951002432** [dataease/dataease#13001]
**请描述您的问题.**
前端build报错，
1. 缺少 codemirror 依赖；
2. 本地添加之后 yarn add codemirror，ts定义类型和默认值不匹配错误 
<img width="1096" alt="iShot_2024-10-30_13 58 16" src="https://github.com/user-attachments/assets/54d17862-ba1a-429c-8474-c948577df107">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，报错已经修复，请等待下周四发版。
