### ISSUE TITLE
[Bug]世界地图有一块地方缺失填充

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#13005]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

谷歌浏览器
**Bug 描述**
世界地图有一块地方缺失填充

**Bug 重现步骤(有截图更好)**
![image](https://github.com/user-attachments/assets/c1962dce-489d-47f5-91e4-b6f03696502a)
![wecom-temp-321864-e9d902721580be2d4e1a73eb54f84ae5](https://github.com/user-attachments/assets/758d4426-ff50-41e8-8644-bd32be65715a)

**Comment by xuwei-fit2cloud** [comment]
等待 v2.10.2 版本发布。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
