### ISSUE TITLE
[Feature]创建仪表板-复用模版的时候，模版名称显示不全，建议名称列可以拖动

### ISSUE THREAD

**Issue by zyyfit** [dataease/dataease#1302]
**请描述您的需求或者改进建议.**
创建仪表板，复用模板，模板名称太长会显示…，如果有多个名称相似的，就不知道哪个模板才是要选的那个，需要一个一个点击查看内容来分辨
建议左侧显示名称的这一列可以拖宽，就跟仪表板列表一样

![图片](https://user-images.githubusercontent.com/73461316/143816617-bfd1c996-e7bd-4bc5-9aa8-20e04096adce.png)

**Comment by yayanpei** [comment]
感谢您的反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
鼠标移动在仪表板上的时候，会显示完整的名称。
