### ISSUE TITLE
[Feature] 表格数据未空时，默认展示空数据占位符

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#13037]
DataEase 版本:
2.10.1

**请描述您的需求或者改进建议.**
![image](https://github.com/user-attachments/assets/06d476ae-cf08-4eee-8690-509d8902b606)
在不展示表头的情况下，空数据的表现形式有点难看

**Comment by xuwei-fit2cloud** [comment]
后续版本我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
