### ISSUE TITLE
[Bug]汇总表下钻后不展示数据

### ISSUE THREAD

**Issue by yingchunsyc6656** [dataease/dataease#13031]
**DataEase 版本**
2.10

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome

**Bug 描述**
汇总表下钻时，如果选择的维度值有\时，下钻后未返回数据

**Bug 重现步骤(有截图更好)**
1.选择汇总表，配置维度，配置维度下钻
![image](https://github.com/user-attachments/assets/b8ccc148-bb70-4a53-9280-aba997986735)
2.下钻值带有\内容，下钻后无数据展示，接口也未返回数据
![image](https://github.com/user-attachments/assets/724417c4-0695-45c4-8924-be445facc39c)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
