### ISSUE TITLE
[Feature] 由于数据过多导致图表放不下，希望提供一个”更多“按钮，显示全部数据

### ISSUE THREAD

**Issue by daiqingyao6238** [dataease/dataease#13039]
DataEase 版本:

2.10.1
**请描述您的需求或者改进建议.**
![a60731e8-059b-4414-af7b-7c90d9529c23](https://github.com/user-attachments/assets/04440cb4-e1e4-403e-a08d-3ce4d2ad5815)
因排版有限无法显示所有数据，希望能提供类似点击“更多”按钮，展示所有数据的功能.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先记录一下，如有其他用户反馈同样的问题，我们再排期开发。
