### ISSUE TITLE
[Feature] 建议优化安装配置文件中数据库相关说明，避免用户修改端口导致服务无法启动

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#13033]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
当用户安装 DataEase 时，通常会由于担心端口冲突等问题修改数据库端口（用户不清楚 DataEase 未映射端口）
此时，用户会在 install.conf 中修改DE_MYSQL_PORT=3306参数
修改后即使 DE_EXTERNAL_MYSQL=false，也会影响系统运行时连接的数据库导致服务启动时无法正常连接数据库

期望：
1. 在数据库配置处明确提示，仅使用外部数据库时才生效，即使虚拟机中 3306 端口有运行程序，内部数据库也不会出现端口冲突问题
2. 即使用户修改了端口，当 DE_EXTERNAL_MYSQL=false 时，端口不生效，防止启动异常

**Comment by xuwei-fit2cloud** [comment]
等待新版本发布。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
