### ISSUE TITLE
[Question]v1.18前端打包部署时布局错乱问题

### ISSUE THREAD

**Issue by 91MrZhang** [dataease/dataease#13042]
**请描述您的问题.**
![q1](https://github.com/user-attachments/assets/42163e6c-5815-4763-a070-d4c0c8db5dfa)
![q2](https://github.com/user-attachments/assets/a14bb236-73ae-41a0-9e66-62edf4b5c9e2)

![q3](https://github.com/user-attachments/assets/cdecd2f3-35e0-4ff6-9a51-65528f7edc82)

v1.18按步骤npm打包后，部署时界面错乱，但是后端可以正常调用接口

nginx.conf如下：

events {
}

http {
        server {
                listen      80;
                server_name localhost;
                location / {
                        root    /opt/dataease/frontend/dist/;
                        index   index.html;
                }
                location /app.html {
                        root    /opt/dataease/mobile/dist/;
                }
                location /de-app/ {
                        alias   /opt/dataease/mobile/dist/;
                }
                location /de-api/ {
                        proxy_pass http://192.168.28.130:8001/de-api/;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header Host $host:80;
                        #server_name_in_redirect on;
                }
        }
}

**Comment by maninhill** [comment]
v1.18 已经停止接受需求，望理解。
