### ISSUE TITLE
[Feature]仪表板、大屏的默认排序规则可选

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#13050]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
仪表板、大屏的默认排序规则是按创建日期排序的，希望可以配置默认排序规则，部分场景会将资源有序命名，前端缓存失效，切换会默认日期排序，资源命名排序会打乱。
如果选择默认排序为按名称升序，就不会出现这种情况。
<img width="750" alt="图片" src="https://github.com/user-attachments/assets/68d29af9-6a13-44ca-a1be-b0b5d0c91725">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经加入近期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
