### ISSUE TITLE
[Bug]存量图表柱状图复制出来的配色顺序不对

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13054]
**DataEase 版本**
v2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
存量图表柱状图复制出来的配色顺序不对

**Bug 重现步骤(有截图更好)**
1.左边是存量图表，右边是复制的图表
 复制了一个存量图表加上过滤条件，使用颜色配色，发现和原图表的图例是反的（如），这时候处理一下异常值，null=》0，这时候回正，但是改配色方案后，还是变反（这时应该是加了过滤的原因），然后清掉了过滤条件，现在2个图的数据、样式、高级都是一样的，过滤也清空了，结果柱子和图例的颜色是互换的，配色的自定义改不了。
后续花了不少时间，通过改指标顺序和配色方案的自定义色号，才让2个柱状图的柱子顺序、图例顺序以及对应的颜色是一致的。
![image](https://github.com/user-attachments/assets/2881e6a0-d879-445f-be3f-a2bb2745889e)
2.复制了存量的图表。昨晚还能改配色方案里面自定义的色号，今天下午再打开配色方案的自定义就不显示字段和颜色了。

**Comment by BBchicken-9527** [comment]
目前测试环境没有发现你所说的问题，建议下载新版本体验；
