### ISSUE TITLE
[Feature]富文本支持保留固定位数，现在只有保留固定小数位数

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13052]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
富文本支持保留固定位数，现在只有保留固定小数位数，比如10.12000，120.1200，1111.10，这样能保证文字的对齐

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，那如果一个数值是1000，一个数值是10000，那按照固定位数设置长度留4，10000数值少个0，就变成1000了。数值格式只对显示格式调整，不对数据本身做调整。

**Comment by xuwei-fit2cloud** [comment]
暂不考虑支持。
