### ISSUE TITLE
[Bug]富文本+默认查询出现苹果端显示不正常但PC、移动端正常的现象

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13053]
**DataEase 版本**
v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
最新

**Bug 描述**
富文本+默认查询出现苹果端显示不正常但PC、移动端正常的现象
![image](https://github.com/user-attachments/assets/0d420160-43d6-4245-b7c0-1f88da62ccf9)
![e3505ca9bf6299145d48939a92b5ebd](https://github.com/user-attachments/assets/d32eb6dd-5233-4ce4-99c9-218fb690e75b)

**Bug 重现步骤(有截图更好)**
1.做一个富文本，一个查询组件
2.富文本选用时间字段和其他字段
3.查询组件查富文本，时间字段这样配置：
![image](https://github.com/user-attachments/assets/3ef3e5f0-30e8-4325-981b-6c57263b1588)
4.打开移动端、组件都拖进去，开启。保存
5.保存，分享链接，pc、移动、苹果显示，现在只有苹果不行了，并且时间选不上
![b93755a35093677d38acdd4b197b28f](https://github.com/user-attachments/assets/85cfe472-aeee-4859-bb08-f099528211f6)

预计选固定时间默认也不行。经实际环境反馈，绑定ssl证书搞https也没有效果。

**Comment by zhainanshidai** [comment]
其他组件也可以测一下，这里只测了富文本

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。

**Comment by ziyujiahao** [comment]
https://github.com/dataease/dataease/commit/bc16373b24c557c7812cde39466eca3623a5a9e1
