### ISSUE TITLE
[Feature]能不能支持类似PowerBI的多行卡组件？

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13051]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
我的数据是一个有固定列的多行数据，想要把这些数据以下面的形式展示全，已经试过明细表、富文本，效果不太理想。
<img width="232" alt="f21b8b128e5f74315873bb014bd79dc" src="https://github.com/user-attachments/assets/4ff4d27b-c1c9-45d4-9fde-485022797f40">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，如果是计算各分类的占比，建议使用分布图，显示更直观。
