### ISSUE TITLE
[Feature]希望可以展示需要账号密码登录的web网址

### ISSUE THREAD

**Issue by ryswork1993** [dataease/dataease#13061]
DataEase 版本:

**请描述您的需求或者改进建议.**
目前希望可以支持dataease展示zabbix，jumpserver等需要登录的网址页面

**Comment by xuwei-fit2cloud** [comment]
不是很确定您的使用场景，一般使用网页组件就可以展示了。当然，有些平台默认可能不允许第三方嵌入，比如JumpServer，这就需要去调整JumpServer的设置了。
