### ISSUE TITLE
源码编译报错

### ISSUE THREAD

**Issue by lyons6** [dataease/dataease#13060]
完全按照官方文档步骤配置环境，下载2.9版本dataease源码
在dataease\core\下执行mvn clean package -Pstandalone -U -Dmaven.test.skip=true命令报错。

![image](https://github.com/user-attachments/assets/2091cbce-266d-4480-a3b5-0914581ce9b0)

以下为配置环境
java:
![image](https://github.com/user-attachments/assets/c2b1505a-39e2-4205-9813-6fba6f4f98c2)

git:
![image](https://github.com/user-attachments/assets/222af612-5b1f-4ef9-ac1c-181ac58b0eea)

Maven:
![image](https://github.com/user-attachments/assets/64dcabb0-c9c9-4df7-8111-360d4c19b4fb)

nodejs:
![image](https://github.com/user-attachments/assets/5895d681-b877-4e46-8168-121e84f5d0b8)

**Comment by xuwei-fit2cloud** [comment]
已提交修复，请更新代码。
