### ISSUE TITLE
[Feature]数据大屏建议指标卡优化排列方式：文字在上/文字在下/两端对齐

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#13087]
DataEase 版本:
V2.10.2

**请描述您的需求或者改进建议.**

目前这种简单样式指标卡实现不了，只能使用富文本一个个敲空格/回车，而这种样式在大屏中较常用
建议优化指标卡排列方式：文字在上/文字在下/两端对齐

<img width="196" alt="image" src="https://github.com/user-attachments/assets/b67978fb-d1ec-43fe-a458-b9970264a1c7">

<img width="813" alt="image" src="https://github.com/user-attachments/assets/1a8edd9a-c1e6-400f-90c5-53a9b58f9050">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议使用富文本。

**Comment by zhangtong9898** [comment]
使用富文本一旦数据变了，空格就对应不上，无法对齐，需要重新调整。富文本当做指标卡并不好用。
