### ISSUE TITLE
[Bug]用户管理删掉某个用户后,该用户的浏览器的cookies还保存着导致报错

### ISSUE THREAD

**Issue by yjking** [dataease/dataease#13084]
**DataEase 版本**
V2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome

**Bug 描述**
登录某个账号，一直挂在浏览器上，然后在用户管理将该账号删除掉，再重新进那个浏览器就会出现报错提示

**Bug 重现步骤(有截图更好)**
1.希望能自动跳到登录页
![image](https://github.com/user-attachments/assets/1905e60c-7efe-458c-be9d-89cb62796457)

**Comment by xuwei-fit2cloud** [comment]
我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
