### ISSUE TITLE
[Feature]仪表板列表或详情刷新建议保留在当前页面，或者增加刷新功能

### ISSUE THREAD

**Issue by zyyfit** [dataease/dataease#1309]
**请描述您的需求或者改进建议.**
仪表板列表或详情刷新会返回列表，建议保留在当前页面，或者增加刷新功能
因为仪表板没有发现有单独刷新当前仪表板的地方，如果视图有更新，刷新页面后需要再重新找到我当前编辑的仪表板，操作不方便

![图片](https://user-images.githubusercontent.com/73461316/143824497-82272031-fd3f-49b7-91f2-6b514cde7257.png)

**Comment by zyyfit** [comment]
视图好像也没有刷新功能，如果数据集有同步数据的话

**Comment by xuwei-fit2cloud** [comment]
v1.8.0已支持
