### ISSUE TITLE
[Bug] Excel 导出问题

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#13100]
**DataEase 版本**
2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
1. DE 中的数值，在 excel 里是文本
2. DE 中的小数 0，被导出后会变成 0E-8

**Bug 重现步骤(有截图更好)**
<img width="513" alt="image" src="https://github.com/user-attachments/assets/e456a6ad-b90d-4e48-bab9-7ed5b08f3e33">

**Comment by xuwei-fit2cloud** [comment]
我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
请升级版本。
