### ISSUE TITLE
[Feature]ticket放开数量限制

### ISSUE THREAD

**Issue by JOJO30317** [dataease/dataease#13109]
DataEase 版本:
V2.10.1

**请描述您的需求或者改进建议.**
V1没有ticket限制，可以根据需要创建。
但V2里限制只能创建5个，希望和V1一样放开限制。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请问什么场景下使用？

**Comment by JOJO30317** [comment]
> 感谢您的反馈，请问什么场景下使用？

公司一直都是通过共享链接方式，发布虚拟应用，来给不同用户显示同一个仪表板不同的数据，所以数据划分是通过ticket来实现的。

**Comment by yayanpei-fit2cloud** [comment]
不同用户查看不用数据，建议通过配置行列权限控制。
