### ISSUE TITLE
[Bug]无法删除自定义主题

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1310]
**DataEase 版本**
V1.4

**浏览器版本**
Chrome 96

**Bug 描述**
点击删除自定义主题的按钮，界面只闪一下，但是主题并未删除，也没有任何提示。

**Bug 重现步骤(有截图更好)**
1.点击删除自定义主题的小图标；
![image](https://user-images.githubusercontent.com/48945409/143824488-ca5eea05-09b6-4021-86ed-be99ff0528df.png)

2.界面就只快速的闪了一下，然后主题未被删除，也没有提示，重新刷新也还是在的；
3.写这个 issue 的时候又试了下可以删掉了一个，但是删另一个又不行了，还是只闪一下，点旁边的设置小图标也是一样。

**Comment by xuwei-fit2cloud** [comment]
该问题已确认，我们尽快修复。

**Comment by xuwei-fit2cloud** [comment]
已修复，等待v1.5.1 版本
