### ISSUE TITLE
[Bug] dataease-license-sdk 2.10.2不能拉取

### ISSUE THREAD

**Issue by xuewenquan** [dataease/dataease#13110]
**DataEase 版本**
dev-v2

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**

**Bug 描述**
dataease-license-sdk 2.10.2不能拉取

**Bug 重现步骤(有截图更好)**
![image](https://github.com/user-attachments/assets/62369aea-0362-4954-911b-b7fe00d8d5d1)

**Comment by maninhill** [comment]
v2.10.2 还未发布，请使用稳定分支的代码。
