### ISSUE TITLE
[Bug]v2.10.1 使用oracle数据源时，柱状图系列辅助线为动态值时，不显示辅助线

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#13114]
![image](https://github.com/user-attachments/assets/55d40034-56ed-43cb-baa5-b29c470fd953)

**Comment by xuwei-fit2cloud** [comment]
已处理，请等待新版本发布。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
