### ISSUE TITLE
[Feature]透视表采用树形结构的时候排序逻辑也不太对，它最外层分组没有排,需要调整一下逻辑

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13127]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
透视表采用树形结构的时候排序逻辑也不太对，它最外层分组没有排。
比如设置了按部门客户应收降序，但是它只有部门的客户是按照应收降序排列的，部门之间没有按照应收降序排列，这个影响使用就比较严重了..

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们下个版本优化一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
