### ISSUE TITLE
[Feature]能否环形图等图表增加对数据的重新命名匹配呢

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13136]
DataEase 版本:

**请描述您的需求或者改进建议.**
（建议）能否环形图等图表增加对数据的重新命名匹配呢，比如数据里面有true、false，以及一些别的（如none），然后true、false可以重新命名，当查询的时候查到true，就改成真。如果没有匹配到，就按原值处理

**Comment by zhainanshidai** [comment]
环形图、柱状图这些

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，建议在数据集中通过新建计算字段实现。
