### ISSUE TITLE
[Feature]定时报告发送的仪表板可以与行权限关联

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#13145]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
定时报告发送的仪表板可以与行权限关联, 实现同一个仪表板不同用户收到的定时报告内容不一样

**Comment by xuwei-fit2cloud** [comment]
技术上可以实现，但由于定时报告截图采用的是后端渲染的方式，如果使用行列权限的话，那极端的情况下，每个收件人都需要按自己的权限生成一份报告，对于DataEase的资源消耗是巨大的。所以我们还是保持现在的设计，以定时报告创建人的权限给接受者发送报告。
