### ISSUE TITLE
[Question]热力地图和符号地图可以选择省市区吗

### ISSUE THREAD

**Issue by fy951002432** [dataease/dataease#13140]
**请描述您的问题.**

**Comment by xuwei-fit2cloud** [comment]
热力地图、流向地图、符号地图，这三个地图是在线的经纬度坐标地图，目前不支持选择省市区。

**Comment by fy951002432** [comment]
考虑支持吗

**Comment by fy951002432** [comment]
普通气泡地图标记气泡目前是仅能通过省市区名称去进行分类标记，考虑可以通过经纬度标记吗

**Comment by xuwei-fit2cloud** [comment]
您可以描述一下您的具体需求吗？如果是想热力地图和符号地图仅显示某个区域的地图，这个已经在我们的开发计划中，后续版本会支持。如果是其他需求，还请详细描述一下。

**Comment by fy951002432** [comment]
想在地图上，通过经纬度去体现某个省、市、区县不同经纬度的机构的数据量的大小

**Comment by fy951002432** [comment]
最好是可以整合区域图和气泡图的功能；举个例子，我们这个地图通过色块体现北京市，每个区数据量的大小；然后对于top5的区域我会用气泡或者符号通过经纬度标记出来

**Comment by xuwei-fit2cloud** [comment]
技术上是可以做到的，比如v1版本的地图，我们其实就支持了，但同时支持地名和经纬度标记，可能使用上容易让人误会，所以在v2版本的时候把这个功能给去掉了，我们再讨论一下。

**Comment by fy951002432** [comment]
麻烦了
