### ISSUE TITLE
[Feature]汇总表支持最大值、最小值等项，而不是只有汇总

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13158]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
汇总表支持最大值、最小值等项，而不是只有汇总

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，汇总方式支持最大值、最小值，如下图所示：
![image](https://github.com/user-attachments/assets/7a779cd0-8634-44bc-b397-514897befb7a)
