### ISSUE TITLE
[Bug]v2 数据源hologres的实体表跨源查询异常

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13153]
**DataEase 版本**
v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
v2 数据源hologres的实体表跨源查询异常，单表查询正常，但是跨源-左连接后，查询的列随机缺失。如果查出来SQL也是不对的（有时又会对）。全连接、左连接等都会这样。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前平台暂不支持hologres数据源；
