### ISSUE TITLE
[Feature]增加横向柱状图的维度和指标大小范围控制

### ISSUE THREAD

**Issue by BertonSun-fit2cloud** [dataease/dataease#13161]
DataEase 版本:

最好能够增加横向柱状图的名称范围和数值范围的控制功能。
痛点为指标的名称长度通常不确定，有的很长，这样会挤压指标值展示的范围，一半以上的位置被名称占据，这样的图很丑；
同时多个横向柱状图展示时，每一个因为名称长短的关系导致展示区域各不相同，看起来很乱。

建议：
增加通过百分比设置名称和数值显示区域的大小。
增加名称超长的自动缩略展示功能。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中优化一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
