### ISSUE TITLE
[Feature]如果有多个组件得过滤了，但不想改动数据集，或者联表不方便改动，想问下能不能在数据集到指标卡中，提前一步做过滤从而达到口径控制的效果

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13165]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
如果有多个组件得过滤了，但不想改动数据集，或者联表不方便改动，想问下能不能在数据集到指标卡中，提前一步做过滤从而达到口径控制的效果

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，建议在指标卡中设置过滤器，从而过滤数据。
