### ISSUE TITLE
[Bug]批量导入用户时邮箱带有下划线会报错

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#13176]
**DataEase 版本**
v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
chrome

**Bug 描述**
批量导入用户时,表格中的邮箱带有下划线会报错：

比如 test_123@qq.com

这种格式的邮箱无法识别，需要更正。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行优化；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
