### ISSUE TITLE
[Bug] PostgreSQL 数据源如果 table schema 是 default 时会报错 

### ISSUE THREAD

**Issue by calvinit** [dataease/dataease#13189]
**DataEase 版本**
v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome 130.0.6723.92

**Bug 描述**
**PostgreSQL** 数据源如果 table schema 是 default 时会报错，因为 default 是关键字，应该不能直接拼接表名：`default."tb_xxx"` 这样会报错！
```
PSQLException: ERROR: syntax error at or near "default"
```

延伸出所有数据源如果 schema 是一些关键字可能需要特殊处理，比如使用双引号括起来（`"default"."tb_xxx"`）等。
**Bug 重现步骤(有截图更好)**
略。

**Comment by xuwei-fit2cloud** [comment]
请等待新版本发布。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
