### ISSUE TITLE
[Feature]告警信息支持自定义模板：比如输入一些备注或说明信息，插入仪表板某个视图，然后在输入另外一些信息，再插入仪表板另外一个视图。/

### ISSUE THREAD

**Issue by huangxine** [dataease/dataease#13188]
DataEase 版本:

**请描述您的需求或者改进建议.**
告警信息支持自定义模板：
比如输入一些备注或说明信息，插入仪表板某个视图，然后在输入另外一些信息，再插入仪表板另外一个视图。
目前是图和说明不能对应

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，图表的备注信息是固定的，给所有用户看的，因此只能在图表编辑时添加，暂时没有计划在告警中给图表添加备注信息。
