### ISSUE TITLE
[Feature]仪表盘编辑器嵌入，设置变动方面只对个人生效，其他人看到的仪表盘还是原始的

### ISSUE THREAD

**Issue by huangxine** [dataease/dataease#13187]
DataEase 版本:

**请描述您的需求或者改进建议.**
仪表盘编辑器嵌入，设置变动方面只对个人生效，其他人看到的仪表盘还是原始的
1、业务系统中嵌入了A仪表盘编辑器，
2、比如王三在业务系统重调整了颜色从蓝色改为灰色；
3、但是李四在业务系统中打开A仪表板时，看到的演示还是蓝色
即：仪表板编辑器调整只对个人生效

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，暂时没有计划进行支持。
