### ISSUE TITLE
[Feature]支持用户自定义Doris的be fe

### ISSUE THREAD

**Issue by armored-glitch** [dataease/dataease#13196]
DataEase 版本:v2.10.1

**请描述您的需求或者改进建议.**
DataEase请求Doris be会默认去fe的所在ip的8040,能否支持用户自定义Doris的be fe
<img width="436" alt="0a661989bc4bbe9c0e5f8337ad20853" src="https://github.com/user-attachments/assets/36458e9a-920e-4f66-8036-d177b1e00239">
<img width="804" alt="79bafc00a81eb9a303de4b1f88eb687" src="https://github.com/user-attachments/assets/18755a01-25bd-4a3c-b899-7dbc86e001bc">

**Comment by xuwei-fit2cloud** [comment]
这个需求已经在计划中。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
