### ISSUE TITLE
[Bug]级联查询选择后，清空或者重置按钮没清空级联关系

### ISSUE THREAD

**Issue by verntern-chen** [dataease/dataease#13201]
**DataEase 版本**
2.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
googel

**Bug 描述**
级联查询选择后，清空或者重置按钮没清空级联关系，需要下拉选择框本身清空才清空级联关系

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/b196186c-4eb1-4f72-88af-65ada1dcc570)
![image](https://github.com/user-attachments/assets/b96b2249-45df-4e38-a486-74d6dc7f5d8d)
2.
![image](https://github.com/user-attachments/assets/ff171a03-c335-4c5c-a53d-72b6924aa516)
3.
![image](https://github.com/user-attachments/assets/e212cdc8-012b-4c22-b9fc-e5fc5bb019e7)
![image](https://github.com/user-attachments/assets/31570408-9c5d-4ac0-8c51-7bd33821ded9)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前发布版本问题已修复，可以尝试升级；

**Comment by verntern-chen** [comment]
重置后传值还是有问题，不是用的查询字段，而是直接用的显示字段
