### ISSUE TITLE
[Feature]增加轮播控件

### ISSUE THREAD

**Issue by armored-glitch** [dataease/dataease#13205]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
为美观考虑增加轮播控件，类似tab。或者允许tab的标签为空

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，Tab标签可配置展示或者不展示，该功能已经规划在 v2.10.3 版本中，预计在12月初发布。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
