### ISSUE TITLE
[Bug]显示最值勾选后，如果切换其他视图仍然会显示

### ISSUE THREAD

**Issue by JOJO30317** [dataease/dataease#13215]
**DataEase 版本**
V2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome最新

**Bug 描述**
![image](https://github.com/user-attachments/assets/8985dcda-c16b-4cf0-8d7b-4b491829ac05)

**Bug 重现步骤(有截图更好)**
1.线形图勾选最值显示后复制成新的组件
2.更换其他视图后仍会显示最值，且无法勾选不显示，必须切换回去
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
