### ISSUE TITLE
[Feature]查询条件框

### ISSUE THREAD

**Issue by JOJO30317** [dataease/dataease#13213]
DataEase 版本:
V2.10.2

**请描述您的需求或者改进建议.**
![image](https://github.com/user-attachments/assets/aec70790-986d-4913-b8f9-cb7ac3595a30)
希望能够减少条件与框的间距，或者提供调整间距的功能。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，可参考下图所示，调整条件与选框的间距。
![image](https://github.com/user-attachments/assets/6f05c5c1-237a-4d5f-9956-f31e11ff90d3)
