### ISSUE TITLE
[Bug]仪表盘自动恢复默认配置

### ISSUE THREAD

**Issue by JOJO30317** [dataease/dataease#13214]
**DataEase 版本**
V2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome最新

**Bug 描述**
仪表盘配置好后，重新点击查看配置属性，有很大概率会恢复默认状态

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，麻烦能详细说一下具体的复现过程吗
