### ISSUE TITLE
[Feature] 横向滚动条太细，不好操作

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#13216]
DataEase 版本:
2.10.2

**请描述您的需求或者改进建议.**
<img width="1147" alt="image" src="https://github.com/user-attachments/assets/8ac3e479-2340-4ff1-b960-8673123b283d">
下面滚动条太精细，没那么好操作
可以调粗，或者开放相关设置

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中优化一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
