### ISSUE TITLE
[Bug]源码编译报错2.10.2

### ISSUE THREAD

**Issue by lyons6** [dataease/dataease#13220]
**DataEase 版本**
2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
源码编译

**浏览器版本**
chrome浏览器

**Bug 描述**
源码编译报错
在core目录下
运行
mvn clean package -Pstandalone -U -Dmaven.test.skip=true
报错
![image](https://github.com/user-attachments/assets/c0a65d23-9b63-419b-8e5a-2ea724c9ca1f)

源码获取来源
git clone -b v2.10 https://github.com/dataease/dataease.git

**Comment by JaneYork** [comment]
正确步骤：
1. 下载源码，导入dataease根目录
2. install这个【这个过程会将sdk install本地maven】
3. A. 单独导入cre-front 自行install, build b.单独导入core-back，用idea或命令package
4. B.除了3说的分开，也可以直接导core或者add as maven project 直接package【这个过程会install build copy --->. jar】

**Comment by ziyujiahao** [comment]
https://github.com/dataease/dataease/commit/dccb7cf72522ab67e6a6561f1a8adc75864c5ab0
