### ISSUE TITLE
[Feature] 数据大屏的视图支持导出Excel数据 

### ISSUE THREAD

**Issue by gongjing123** [dataease/dataease#13223]
DataEase 版本:
V2  

**请描述您的需求或者改进建议.**
V2的仪表盘只支持矩阵模式，且时间戳组件和图形组件没有，所以只能在数据大屏配置，但是数据大屏的表格数据没有导出的功能，希望数据大屏支持excle导出功能

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，大屏导出已经在v2.10.1进行了支持，请升级版本。
