### ISSUE TITLE
[Question] Doubt Regarding AI copilot

### ISSUE THREAD

**Issue by Greatz08** [dataease/dataease#13227]
AI copilot means what ? To be honest I couldn't understand this so asking here . Does it mean it supports ollama ? or open ai API compatible llm's ? or something else ?  or both ollama and open ai API compatible llm's (which will be the best possible thing in my opinion as we can run both open source and proprietary llm's easily without any issue) .

Btw Thankyou very much for this awesome project :-))

**Comment by xuwei-fit2cloud** [comment]
Thank you very much for your interest in our project. 
Our AI Copilot can support both ollama and open ai API compatible llm's,But at present, the source code of AI Copilot function has not been opened yet, which may take some time.
We look forward to your suggestions on our project.
