### ISSUE TITLE
[Bug] 多个图表连续设置标题生效目标错误问题

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#13237]
**DataEase 版本**
 v2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新

**Bug 描述**
1.在仪表板中添加两个指标卡
A 指标卡命名为“指标卡qwe123”
B 指标卡命名为“指标卡”
2.点击 B 指标卡，双击右上角标题来修改
3.输入完成后，直接点击 A 指标卡
4.此时修改的标题会在 A 指标卡上生效

期望：修改的标题应在 B 指标卡生效

见视频

https://github.com/user-attachments/assets/66fece90-8dc4-4a58-8725-3d0aae85b466

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行优化；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
