### ISSUE TITLE
字段类型能否增加超链接

### ISSUE THREAD

**Issue by xix1** [dataease/dataease#13233]
DataEase 版本:
	v1.15.0

有些数据是url格式的，字段类型能否增加超链接类型，在表格中可以直接点击该链接字段跳转

**Comment by xuwei-fit2cloud** [comment]
在跳转设置里，参考下面的设置即可。
![图片](https://github.com/user-attachments/assets/7a294081-bcde-4823-a99a-8895e3338373)

**Comment by xix1** [comment]
感谢！！！！！！
