### ISSUE TITLE
[Bug]明细表图片不显示问题

### ISSUE THREAD

**Issue by gongjing123** [dataease/dataease#13248]
**DataEase 版本**
2.10.2   社区版

**运行方式(安装包运行 or 源码运行 ?)**
k8s

**浏览器版本**

Google
**Bug 描述**
数据集图片字段类型改为了url类型，但是在仪表盘明细表中图片不渲染，只有空白单元格，点击空白单元格才跳出图片

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/1d38fbac-5002-49b8-9d97-a3d3563735a2)

2.
![image](https://github.com/user-attachments/assets/002a0493-37f4-4569-bcb3-63395258985d)

3.
![image](https://github.com/user-attachments/assets/c2368335-7bf5-4c67-be97-30e1af775d12)
![image](https://github.com/user-attachments/assets/d3fdfeed-aa14-4ef8-86bd-0dbf4cd1bdbe)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前url的策略为浏览器直接打开，应该是因为url跨域导致；_

**Comment by gongjing123** [comment]
> 感谢反馈，目前url的策略为浏览器直接打开，应该是因为url跨域导致；_
@BBchicken-9527   请问有什么解决办法解决跨域吗，图片地址是其他服务的

**Comment by gongjing123** [comment]
> 感谢反馈，目前url的策略为浏览器直接打开，应该是因为url跨域导致；_

@BBchicken-9527   请问dataease怎么配置处理跨域问题，因为要访问的图片接口不是一个服务和域名且无法修改
