### ISSUE TITLE
[Question] 2.10.2 直接编译不过

### ISSUE THREAD

**Issue by qiaozhanwei** [dataease/dataease#13249]
**请描述您的问题.**
[ERROR] Failed to execute goal on project core-backend: Could not resolve dependencies for project io.dataease:core-backend:jar:2.10.2: The following artifacts could not be resolved: io.dataease:xpack-permissions:jar:2.10.2, io.dataease:xpack-sync:jar:2.10.2, io.dataease:xpack-base:jar:2.10.2: Could not find artifact io.dataease:xpack-permissions:jar:2.10.2 in fit2cloud-public (https://repository.fit2cloud.com/repository/fit2cloud-public/) -> [Help 1

xpack https://repository.fit2cloud.com/repository/fit2cloud-public/中也没有啊？如果xpack是不开源的，为啥要找这玩意？

**Comment by xuwei-fit2cloud** [comment]
请使用 v2.10 分支，已处理。
