### ISSUE TITLE
[Bug]多个图表关联查询组件显示数据异常

### ISSUE THREAD

**Issue by lyons6** [dataease/dataease#13243]
**DataEase 版本**
2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包、源码编译都报错

**浏览器版本**
chrome

**Bug 描述**
当多个图表关联查询组件时，图表会报错

**Bug 重现步骤(有截图更好)**
1.新建图表A并关联数据集，并关联查询组件
![image](https://github.com/user-attachments/assets/aa3a8d7c-c74d-4dc1-9801-77ae939beda6)

2.新建图表B并关联数据集，但未关联查询组件
![image](https://github.com/user-attachments/assets/217fe1ac-1dfd-4292-a1b0-93be9dd112b6)

此时查询组件设置如下
![image](https://github.com/user-attachments/assets/d1202150-29d7-4292-94e6-8ee55795e55e)

3.设置图表B关联查询组件
![image](https://github.com/user-attachments/assets/394b6118-1d4d-4a3c-b468-f8e166febe09)

4. 点击查询组件的确定，图表A显示获取数据异常
![image](https://github.com/user-attachments/assets/2c13e2c3-682d-4e86-aaeb-772cbab65914)

注：2.10.1没有此问题。

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，将会在下个版本修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
