### ISSUE TITLE
[Bug] 将字段转为 URL 类型的功能消失了

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#13242]
**DataEase 版本**
2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
chrome、firefox

**Bug 描述**
之前的版本可以将 字段类型  转为 URL 类型，现在没有了。
<img width="1953" alt="图片" src="https://github.com/user-attachments/assets/4c523800-56da-410b-83ce-0605e074e602">
<img width="1959" alt="图片" src="https://github.com/user-attachments/assets/5a1ca058-9837-4e7f-8ea6-57672b4e23a6">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
滚动条向下滚动一下。
