### ISSUE TITLE
[Feature]查询组件的必填和隐藏关联

### ISSUE THREAD

**Issue by verntern-chen** [dataease/dataease#13240]
DataEase 版本:
2.10.2

场景1：
查询1，查询2，查询3，查询4
若查询1为空，查询2必填，反之不必填
若查询2为空，查询3为空，则查询4必填，反之不必填
最好可以满足某个条件（取值可以取查询组件值，支持js语法或者特定语法）

场景2：
查询1，查询2，查询3，查询4
若查询1值为xxx，则显示查询2，反之不隐藏
若查询1值满足某个条件，则显示查询3，反之不隐藏

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，可以描述下具体的业务场景吗？

**Comment by verntern-chen** [comment]
具体业务场景如描述，报表的查询条件的必填性的可联动，根据某个选择值展示不同的下拉条件
如：有个输入类型包含下列枚举值，身份证、电话、邮箱
选择身份证后，隐藏电话和邮箱的输入不必填，只显示身份证的输入且必填
