### ISSUE TITLE
[Feature]新建仪表板风格

### ISSUE THREAD

**Issue by armored-glitch** [dataease/dataease#13253]
DataEase 版本:

v2.10.2
**请描述您的需求或者改进建议.**
尊敬的DataEase团队：
       目前仪表板风格有深色和浅色两种，后续会考虑开发给用户自定义嘛。

**Comment by xuwei-fit2cloud** [comment]
您可以按照下面的文档试试自定义仪表板主题：
https://dataease.io/docs/v2/user_manual/dashboard_basicfunctions/#41
