### ISSUE TITLE
[Bug]数据集A关联数据集B，创建一个自定义数据集，然后修改数据集A的关联字段，关联成数据集C，然后编辑自定义数据集，就报错了

### ISSUE THREAD

**Issue by BBchicken-9527** [dataease/dataease#1327]
**DataEase 版本**

**浏览器版本**

**Bug 描述**

![image](https://user-images.githubusercontent.com/84372766/144001559-dd89bf95-2943-48aa-af49-9cf38f146fe8.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
收到反馈，我们完善一下具体的提示信息。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 已处理，请等待新版本发布。
