### ISSUE TITLE
[Bug]v2.10.2 明细表展示数据出错

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#13283]
问题：
一样的数值单元格合并导致展示的数据不对，“你好”只有两个，合并之后成3行了
![image](https://github.com/user-attachments/assets/7d3ed7d3-73ec-44c1-80f3-3acbdce2af01)
![image](https://github.com/user-attachments/assets/78ab43c1-4e4e-4668-973d-7cdc927d4b8e)
![image](https://github.com/user-attachments/assets/481cd3d3-36bf-4e4e-982d-108e99cc8868)

**Comment by wolf-kingx** [comment]
测试数据集
[级联测试数据.xlsx](https://github.com/user-attachments/files/17727854/default.xlsx)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
