### ISSUE TITLE
[Bug]“带公式”姓名关联“工作簿2”的姓名字段在添加一个关联，excel分组不展示内容，但是excel中还有很多数据

### ISSUE THREAD

**Issue by BBchicken-9527** [dataease/dataease#1328]
**DataEase 版本**

**浏览器版本**

**Bug 描述**

![image](https://user-images.githubusercontent.com/84372766/144001813-f23cd0eb-da25-4758-9976-154a4532fead.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
收到，我们尽快处理一下

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 已修复，请等待新版本发布。
