### ISSUE TITLE
[Feature]关联表中如果是多个自定义传参sql关联，但部分传参名一样时，每个同名的参数还需要分别绑定，希望能像一个查询能绑定多个传参一样的数据集一样，只绑定一次就能给多个数据集传参。

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#13290]
![image](https://github.com/user-attachments/assets/829c5d39-f0d9-481d-9515-13f5ca73edf0)
![image](https://github.com/user-attachments/assets/6fcb1bcd-647a-44cc-bebd-714dddbdbd1c)

**Comment by xuwei-fit2cloud** [comment]
多个SQL数据节点，不能保证同名的参数是一个意思，如果多个SQL节点上参数定义不同，比如类型不同，也会有问题。暂时不做支持。
