### ISSUE TITLE
[Feature] 过滤组件-文本下拉-手工输入选项值 去除字符长度 20 的上限

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#13303]
DataEase 版本:
 v2.10.2

**请描述您的需求或者改进建议.**
过滤组件-文本下拉-手工输入选项值 去除字符长度 20 的上限
<img width="1677" alt="image" src="https://github.com/user-attachments/assets/c1535c31-1450-4cdb-8d22-e87051af2fef">

**Comment by xuwei-fit2cloud** [comment]
我们调整一下上限，但不能无限。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
