### ISSUE TITLE
[Feature]希望通过公共链接访问时，支持在表格上隐藏个别列

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#13306]
DataEase 版本:

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，如果某些列需要隐藏，建议在仪表板或者大屏编辑时，隐藏这些列。预览状态下，目前暂时没有计划支持隐藏列。

**Comment by wolf-kingx** [comment]
有时候展示字段很多，只想看关键指标，但是又不想给他们编辑仪表板的权限。感觉这个功能还挺需要的
