### ISSUE TITLE
[Feature]希望能有类似POWERBI中度量值（DAX）的功能，可以考虑作为一个长期的开发项来考虑

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13304]
DataEase 版本:
v2.10.2

**请描述您的需求或者改进建议.**
希望能有类似 POWERBI 中度量值（DAX）的功能，如果不好实现，可以考虑下作为一个长期的开发项来考虑

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，但对这个功能没有支持计划。
