### ISSUE TITLE
[Feature]柱状图标签太高时会被遮挡

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#13319]
DataEase 版本:
v2.10.2

**请描述您的需求或者改进建议.**

需要优化一下标签的位置：
<img width="939" alt="图片" src="https://github.com/user-attachments/assets/3163e811-69bb-40a8-b1a4-cb797f8f84fc">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，标签超出了图表的显示区域。建议调整标签位置为中或者下，或者自定义轴值。
