### ISSUE TITLE
[Bug]数据集调试执行成功，保存报错，不使用参数也可以保存成功

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#13317]
**DataEase 版本**
v2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
Doris 数据库，在数据集调试执行成功，保存报错，不使用参数可以保存成功。
sql如下：
![44cc12a9a761462bd674ad4097e2a1c](https://github.com/user-attachments/assets/9dd145bc-39fd-4b72-a571-0ed24c091a76)
报错如下：
![7d86163bf173794a6902a3164489bb2](https://github.com/user-attachments/assets/2ece3d13-1a6e-4be9-9620-d268a723155a)
![64efcc5cccc0aae71d169affd92dfc0](https://github.com/user-attachments/assets/a27a1ffb-52d1-4db4-bf0a-ff187172687c)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
