### ISSUE TITLE
[Bug]项目起止时间为同一天，在区间条形图中就无法显示

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#13313]
**DataEase 版本**
v2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
区间条形图中，起止时间为同一天且不带时分秒的日期无法显示
数据如下：XD 项目起止时间为同一天，格式为年月日，没有时分秒，在区间条形图中，就无法显示。
<img width="373" alt="图片" src="https://github.com/user-attachments/assets/0dd7d3fd-1217-41b3-a9e2-5ca7207c11d8">

<img width="998" alt="图片" src="https://github.com/user-attachments/assets/cd884e8c-be66-4e45-b666-925a3a146b7d">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，图表显示没有问题，如果你没有带时分秒计算出来是没有色块的，如果你存在时分秒是可以正常显示；
