### ISSUE TITLE
[Bug] 地图图表 自定义区间没有效果

### ISSUE THREAD

**Issue by lixuedong0925** [dataease/dataease#13327]
**DataEase 版本**
2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 130.0.6723.119

**Bug 描述**
地图图表 自定义图例区间没有效果， 地图没有根据自定义区间变色

**Bug 重现步骤(有截图更好)**
1.
![微信图片_20241114162639](https://github.com/user-attachments/assets/655022fe-7a0e-487f-b181-370ebf1e10d1)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈 ，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
