### ISSUE TITLE
[Bug]2.10.2版本  flyway文件 SQL问题

### ISSUE THREAD

**Issue by NotFeel** [dataease/dataease#13325]
**DataEase 版本**

2.10.2版本
**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**Bug 描述**
core-backend/resources/db/desktop/V2.10.2__ddl.sql错误
core-backend/resources/db/migration/V2.10.2__ddl.sql错误

**Bug 重现步骤(有截图更好)**
去除SQL中的 dvi
delete from data_visualization_info where delete_flag =1;

**Comment by BBchicken-9527** [comment]
感谢反馈，desktop在当前版本没有使用的，此处我们会进行处理的，migration目前测试环境没有发现你说的问题，因为你是直接源码运行不确定你是否对部分文件进行改动所以建议可以和我们社区群f to f沟通，可能更方便解答你的疑问；
