### ISSUE TITLE
data_visualization_info 表主键类型和 java 类中主键类型不一致，导致根据ID查询出现模糊匹配问题

### ISSUE THREAD

**Issue by sunshineshenjin** [dataease/dataease#13326]
**DataEase 版本**
版本2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**
chrome 最新版本

**Bug 描述**
mysql 数据库版本 5.7.33
data_visualization_info 这个表的主键id 为varchar 类型，类 DataVisualizationInfo 中的 id 为 Long 类型
导致调用：dataVisualizationInfoMapper.selectById(resourceId) 这个方法时，出现了id 近似 查询的情况，如图：

**Bug 重现步骤(有截图更好)**
<img width="331" alt="image" src="https://github.com/user-attachments/assets/44dc9400-c6bd-4dfa-a6d0-66805ae62bfb">

图中返回数据的ID 与入参的ID 不同， 如果where条件后面明确使用字符串则正确

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，由于你是源码运行，不确定你是否改动和以及打包方式都有可能存在问题，建议你加入我们的交流群，上面有非常专业的同学会实时的回复你的问题，方便你快速并精准的定位到你的问题所在；

**Comment by sunshineshenjin** [comment]
> 感谢反馈，目前测试环境没有发现你说的问题，由于你是源码运行，不确定你是否改动和以及打包方式都有可能存在问题，建议你加入我们的交流群，上面有非常专业的同学会实时的回复你的问题，方便你快速并精准的定位到你的问题所在；



> 感谢反馈，目前测试环境没有发现你说的问题，由于你是源码运行，不确定你是否改动和以及打包方式都有可能存在问题，建议你加入我们的交流群，上面有非常专业的同学会实时的回复你的问题，方便你快速并精准的定位到你的问题所在；

这个和代码没关系，我截图是通过mysql 数据库客户端查询存在这个问题。

mybatis 根据类型拼接出来的sql如下： 
SELECT * FROM dataease.data_visualization_info where id = 1048231502007111681;

这里id 本身是个字符，但是因为java 类标明是 Long 类型，所以不带引号，在mysql 8.0.26 上运行也是有问题的。

mysql 在类型不一致时，会做隐士的转换，是否考虑需要将字段类型统一为 bigint ?
