### ISSUE TITLE
[Question] dataease 2.10.2版本 新引入的依赖没有上传到你们的Mavn仓库中

### ISSUE THREAD

**Issue by NotFeel** [dataease/dataease#13323]
2.10.2版本新加入的。此依赖位于 dataease/core/core-backend/pom.xml

Maven依赖:
`

<dependency>
            <groupId>io.dataease</groupId>
            <artifactId>xpack-permissions</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.dataease</groupId>
            <artifactId>xpack-sync</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.dataease</groupId>
            <artifactId>xpack-base</artifactId>
            <version>${project.version}</version>
        </dependency>
`

**Comment by xuwei-fit2cloud** [comment]
确实有问题，请使用v2.10分支代码。
