### ISSUE TITLE
[Bug]2.10.2 clickhouse数据源，查询组件统一字段不能同时查询直接数据集和sql传参数据集，如视频所示

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#13331]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by wolf-kingx** [comment]
https://github.com/user-attachments/assets/2689ce01-96a3-4b48-a1d0-b281c5246b55

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，目前已经成功修复，将会在下个版本发布；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
