### ISSUE TITLE
[Bug]Oracle 19c 的数据源，编辑数据集时自定义SQL查询视图结果正常，但是无法保存

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#13342]
**DataEase 版本**
v2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
最新

**Bug 描述**
Oracle 19c的版本，编辑数据集时，原自定义SQL查询视图，如果视图有调整字段名称和删减字段之后，数据集自定义SQL可以查询，但是无法保存，关掉自定义SQL页面之后，保存数据集报错，退出编辑，查询原数据集也报错如下图：
![image](https://github.com/user-attachments/assets/95e4bbf6-a04b-454e-85a1-d98738787def)
删掉原有的自定义SQL，重新拖拽正常。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，提示是因为你在删除字段后没有对字段进行同步，导致无法找到字段，重新勾选一下字段即可；
