### ISSUE TITLE
[Bug]排序后图例颜色错误

### ISSUE THREAD

**Issue by JOJO30317** [dataease/dataease#13341]
**DataEase 版本**
V2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome最新

**Bug 描述**
柱状图按照记录数排序，会导致图例颜色异常

**Bug 重现步骤(有截图更好)**
1.自定义图例颜色
2.指标选记录数
3.对记录数进行排序
![image](https://github.com/user-attachments/assets/b4865e15-3896-4583-82e9-80e487322a40)

**Comment by JOJO30317** [comment]
不排序是正常的；
复制的图，指标更换为计算字段金额，显示又是正常的。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，清除缓存是否可以正常显示？
![image](https://github.com/user-attachments/assets/634079e6-de58-41b6-aefc-b030ae6edc16)
![image](https://github.com/user-attachments/assets/10ae2b48-7e54-49d9-ae29-8389f54c08fa)

**Comment by JOJO30317** [comment]
> 感谢反馈，目前测试环境没有发现你说的问题，清除缓存是否可以正常显示？ ![image](https://private-user-images.githubusercontent.com/84372766/386433023-634079e6-de58-41b6-aefc-b030ae6edc16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MzkzODksIm5iZiI6MTczMTYzOTA4OSwicGF0aCI6Ii84NDM3Mjc2Ni8zODY0MzMwMjMtNjM0MDc5ZTYtZGU1OC00MWI2LWFlZmMtYjAzMGFlNmVkYzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAyNTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MTRlYTgzZDNkMmIxN2Y0NDk2ZTIwMjY3MTQ5MDc4MDRhOGNjNmVmODVlMjJkNzVkMmFmNTBiMzcxNmE2NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VOWRdxC_AsjUt4dFBeEF_9_fgie_nk_Bip0KyDR-WzI) ![image](https://private-user-images.githubusercontent.com/84372766/386433374-10ae2b48-7e54-49d9-ae29-8389f54c08fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MzkzODksIm5iZiI6MTczMTYzOTA4OSwicGF0aCI6Ii84NDM3Mjc2Ni8zODY0MzMzNzQtMTBhZTJiNDgtN2U1NC00OWQ5LWFlMjktODM4OWY1NGMwOGZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDAyNTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZjI3MWM3NTU1NDYzNTQ0ODUwMTYzODA5MzAzNDczYzgwZTAxNTMxZWZlMGMzYjQzMjIzZTIxNGRmZWNiZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RipuY8ve3xzOQ61lCowzqMBy35kxIZ7sRuLMjv6C74c)

按照记录数排序看看呢？
我换了一台电脑也是这个问题

**Comment by BBchicken-9527** [comment]
不好意思。我一直想的是我已经排序了😂，好的，问题会在后续两个版本内进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
