### ISSUE TITLE
[Bug]条形图标签设置为右侧时，最大值显示不全

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13352]
**DataEase 版本**
v2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
条形图标签设置为右侧时，最大值显示不全

**Bug 重现步骤(有截图更好)**
![image](https://github.com/user-attachments/assets/e2490ff7-7ec2-4444-a23d-fcd40fffae1e)
![image](https://github.com/user-attachments/assets/88bf137b-0938-4f20-8284-faa39ea04872)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行优化；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
