### ISSUE TITLE
[Bug]v2.10.2 当查询组件前一次查询A、B有错误时，下面的查询即使去掉错误原因B,只查A结果也不会显示，必须重新来一个查询再次查询A才行

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#13357]
1.确保查询A时是正确的
2.查询AB触发查询错误
3.删除错误原因B，再次查询A
4.查不了
5.新建一个查询，条件和3中的查询A完全一致
6.正确查询
https://github.com/user-attachments/assets/1eef4a62-5785-4b97-9813-231a52eabf12

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境暂时没有发现此类问题；
