### ISSUE TITLE
[Bug] 折线图最值标签编辑页面能展示，预览页面展示不全

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#13354]
**DataEase 版本**
v2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
折线图最值标签编辑页面能展示，预览页面展示不全

**Bug 重现步骤(有截图更好)**
1. 预览页面
![image](https://github.com/user-attachments/assets/e7a7666b-278e-48fc-9b6d-0fce002caa86)
2. 编辑页面
![image](https://github.com/user-attachments/assets/e3235b3a-7c4e-4d1f-b5e8-860cf51ed3ab)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们尝试优化一下；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
