### ISSUE TITLE
[Feature]希望可以推出数据源对SQLite的支持

### ISSUE THREAD

**Issue by Pyangs** [dataease/dataease#13350]
DataEase 版本:

2.10.2
**请描述您的需求或者改进建议.**
有些小项目本身不计划使用中大型数据库而使用了Sqlite，或者一些项目的可行性测验阶段就使用了Sqlite来快速验证思路，在这些情况下需要使用DE时需要去建库或手动转换太麻烦。希望增加sqlite支持

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，近期暂时没有计划支持。
