### ISSUE TITLE
[Feature]查询组件查询年份后，此时柱状图时间维度是同一年的，那年份期望支持可以配置或者自动省略

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13361]
DataEase 版本:
v2.10.2

**请描述您的需求或者改进建议.**
查询组件查询年份后，此时柱状图时间维度是同一年的，那年份期望支持可以配置或者自动省略

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，查询组件主要用于过滤图表数据，并不会改变图表中的数据格式，图表中的日期格式是在图表编辑时已经设置好，因此目前没有计划支持该功能。
