### ISSUE TITLE
[Bug] 使用外部传参，第一次传参显示正常，第二次传显示异常，需要重新刷新才能显示正常。

### ISSUE THREAD

**Issue by daiqingyao6238** [dataease/dataease#13362]
**DataEase 版本**
2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌浏览器版本 130.0.6723.117（正式版本） （64 位）

**Bug 描述**
使用外部传参第一次传参显示正常，第二次传显示异常，需要重新刷新才能显示正常。

**Bug 重现步骤(有截图更好)**
1.无痕浏览器访问http://183.6.47.163:9080/#/de-link/BkHBXRd0?attachParams=eyJuYW1lIjoi5be05aOr6ZuG5ZuiIn0%3D
2.将attachParams=后面的参数换成eyJuYW1lIjoi5LiA5rG95YWs5Y%2B4In0%3D后回车，画面显示异常。
3.重新刷新页面才能显示正常。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快在后续版本做出优化；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
