### ISSUE TITLE
[Bug]透视表组件在高级设置了条件样式后，“总计”那列文字颜色没生效

### ISSUE THREAD

**Issue by yjking** [dataease/dataease#13373]
**DataEase 版本**
V2.10.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome

**Bug 描述**
透视表组件在高级设置了条件样式后，“总计”那列文字颜色没生效

**Bug 重现步骤(有截图更好)**
![透视表组件高级设置条件样式](https://github.com/user-attachments/assets/ffb7af9a-7e7b-46b4-9d48-a75148ac6bb6)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，可以更新后尝试一下；
![image](https://github.com/user-attachments/assets/68158626-ca37-4420-9a14-a296985388fb)
