### ISSUE TITLE
[Bug]当筛选条件关联两个及以上数据集的动态参数，点击查询报错。

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#13382]
**DataEase 版本**
v2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
1、筛选条件关联数据集的动态参数，只关联一个没问题，关联多个后查询后报错
![image](https://github.com/user-attachments/assets/ff2fa62b-7551-4b49-8691-51120c2f6259)
![image](https://github.com/user-attachments/assets/d8f8370d-7c10-4696-bc9e-74f478e16ce5)
![image](https://github.com/user-attachments/assets/b631d723-e353-4e09-b26b-4f1697a8255f)
![image](https://github.com/user-attachments/assets/90d1be98-3ced-4c13-9544-3b5737552489)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题并且已经修复，将会在下个版本更新；

**Comment by zd1990** [comment]
@BBchicken-9527 能给下修复的commit吗，多谢

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
