### ISSUE TITLE
[Feature]解除表格行高 100 的限制

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#13385]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
表格中如果用在8米的大屏上显得很小，通过调整行高可以得到合适的展示效果，但DE 对行高限制了最高 100，希望解除限制。
<img width="307" alt="图片" src="https://github.com/user-attachments/assets/d8054d8c-292c-4acf-a1ed-adf8ce215261">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中优化一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
