### ISSUE TITLE
[Bug]仪表板时间组件，设置完成后删除设置时间组件的视图，打开时间组件，发现之前删除的视图以及绑定的字段依然在时间组件中

### ISSUE THREAD

**Issue by BBchicken-9527** [dataease/dataease#1338]
**DataEase 版本**

**浏览器版本**

**Bug 描述**

![image](https://user-images.githubusercontent.com/84372766/144016489-d0c7017b-fe64-4955-a408-9bd4762affdf.png)
**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
收到，我们处理一下。
