### ISSUE TITLE
[Feature]增量更新方式，若增量添加与增量删除同时设置，两条语句同时执行

### ISSUE THREAD

**Issue by BBchicken-9527** [dataease/dataease#1339]
**请描述您的需求或者改进建议.**
增量更新方式，若增量添加与增量删除同时设置，两条语句同时执行，但现在等方式很容易让人误会是选中增量添加则不执行增量删除，选择增量删除则不执行增量添加；建议优化此处展示，或限制隐藏的增量删除或添加其中一个不执行

![image](https://user-images.githubusercontent.com/84372766/144013784-46a810d0-aacd-4b60-afb9-abc9854f627a.png)

**Comment by yayanpei** [comment]
感谢您的反馈，我们需要内部讨论一下。

**Comment by xuwei-fit2cloud** [comment]
此处暂时没有较好的优化方案。
