### ISSUE TITLE
[Feature]横向柱状图去掉横轴标签遮挡

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#13399]
DataEase 版本:
2.10.2

**请描述您的需求或者改进建议.**
在使用横向柱状图的时候，关闭横轴标签会被遮挡，不关闭不会，自适应的问题，看看能不能优化一下。
[明细表.xlsx](https://github.com/user-attachments/files/17808245/default.xlsx)

![image](https://github.com/user-attachments/assets/3a5c9a60-c636-498f-8c72-c67cd6b6dfb9)
![image](https://github.com/user-attachments/assets/ef0e067f-63a6-4973-be58-ef0d3dd33319)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，图库自适应的结果，不支持修改。建议自定义轴值。
