### ISSUE TITLE
[Feature]信创要求，国产数据库支持

### ISSUE THREAD

**Issue by a3225167** [dataease/dataease#13396]
DataEase 版本:v2.10.2

**请描述您的需求或者改进建议.**
DataEase本身只支持Mysql，不支持国产数据库，目前信创要求不仅仅数据源要支持国产数据库，软件本身也需要支持。

**Comment by xuwei-fit2cloud** [comment]
可以试试信创数据库 GreatSQL。
我们在 GreatSQL 8.0.32 上验证过。

**Comment by a3225167** [comment]
> 可以试试信创数据库 GreatSQL。 我们在 GreatSQL 8.0.32 上验证过。

达梦、人大金仓这些呢？

**Comment by xuwei-fit2cloud** [comment]
v2版本目前不考虑，v3版本会做支持。

**Comment by a3225167** [comment]
> v2版本目前不考虑，v3版本会做支持。

V3版本要到什么时候啊？

**Comment by xuwei-fit2cloud** [comment]
需要到明年年中的样子了。

**Comment by JFeng99999** [comment]
v3版本什么时候发布
