### ISSUE TITLE
[Feature] 支持直连模式的 API 数据源

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#13405]
DataEase 版本:
v 2.10.2

**请描述您的需求或者改进建议.**
1.  复杂场景下的计算通过 SQL 不好处理，API 直接获取就简单多了
2. 外企对于数据安全性有担忧，不愿意同步，也不愿意开放 DB对接
3. 实时更新数据，适用于实时性要求高的小数据量场景

可以同 QuickBi 一样，要求 在 API 直连模式下，每次请求返回的数据量应满足以下条件：不超过10MB，同时列数不超过100列，行数不超过1000行
同时 直连模式 支持开启短效缓存，缓存时间可以选择5分钟、10分钟、30分钟

![image](https://github.com/user-attachments/assets/7733e1b1-7ceb-4a0f-9ed7-cd81cbfc016b)

**Comment by xuwei-fit2cloud** [comment]
DataEase对数据的处理都是通过SQL处理，API数据必须入库才能处理。数据不入库的方式目前做不到，短期内也没有支持计划。

**Comment by aaaxian** [comment]
如果是用sql处理，为什么调用api不先入库，然后通过，sql查询呢
