### ISSUE TITLE
[Feature]字体管理上传的字体，支持在图表标签、提示、横纵轴的字体都可以选择

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#13408]
DataEase 版本:
v1.10.2

**请描述您的需求或者改进建议.**
支持在图表标签、提示、横纵轴的字体都可以选择，指标卡的值和名称也支持选择上传的字体

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经加入近期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
