### ISSUE TITLE
[Feature]筛选组件支持自定义筛选框跟边框的距离

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#13401]
DataEase 版本:
v2.10.2

**请描述您的需求或者改进建议.**
![image](https://github.com/user-attachments/assets/ef358bb9-6440-43d5-988a-877c71f6b387)

**Comment by xuwei-fit2cloud** [comment]
内边距的设置在下个版本中会发布，还请等待。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
