### ISSUE TITLE
[Bug]时间组件日期设置完成后选择任意一个日期，之后点击右上角编辑不用去修改之后点击保存，再次点击组件就失效了；

### ISSUE THREAD

**Issue by BBchicken-9527** [dataease/dataease#1340]
**DataEase 版本**

**浏览器版本**

**Bug 描述**

![image](https://user-images.githubusercontent.com/84372766/144018564-a8519473-f65b-468e-8498-4621ad0f282d.png)
![image](https://user-images.githubusercontent.com/84372766/144018959-ba3f9e5f-c92b-47ad-a618-4b702ab77420.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 版本已修复
