### ISSUE TITLE
[Bug] 自定义 SQL 中 -- 被默认识别为注释导致 SQL 运行失败

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#13403]
**DataEase 版本**
v2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
自定义 SQL 中 -- 被默认识别为注释导致 SQL 运行失败

**Bug 重现步骤(有截图更好)**
1. 使用 -- 拼接
![image](https://github.com/user-attachments/assets/e7d0c83f-fa95-4a8d-b133-34951970d8f7)
2. 使用 - 拼接
![image](https://github.com/user-attachments/assets/e47b8529-5a69-465a-ab2e-6e00ecf8b215)

**Comment by fit2cloudrd** [comment]
请等待新版本发布。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
