### ISSUE TITLE
[Feature]【数据大屏】希望地图及其他图表提示框支持上传背景图

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#13419]
DataEase 版本:
v2.10.2

请描述您的需求或者改进建议.
希望地图及其他图表提示框支持上传背景图
<img width="314" alt="image" src="https://github.com/user-attachments/assets/60ca3409-3514-4087-827c-e9f75038efcc">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持。
