### ISSUE TITLE
[Bug]仪表板地图放到最小后，无法放大

### ISSUE THREAD

**Issue by BBchicken-9527** [dataease/dataease#1341]
**DataEase 版本**

**浏览器版本**

**Bug 描述**

![image](https://user-images.githubusercontent.com/84372766/144020572-0b4a6167-0707-4ec8-ae6d-52706230d638.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
缩小到最小后，确实不太好还原，我们后期会增加一个重置按钮。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 版本支持重置按钮，请等待新版本发布
