### ISSUE TITLE
数据集定时更新任务失败

### ISSUE THREAD

**Issue by xix1** [dataease/dataease#13428]
版本：v1.15.0
描述：定时连接的mysql数据集，执行全量更新任务失败，同样的SQL语句在直连状态是可以运行成功的，只是时间有点久，为什么在定时连接会任务失败呢？而且前几次全量更新是成功的，这两天就失败了。
错误信息：SQL ERRORStatement cancelled due to timeout or client request

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，建议将数据源的超时时间设置大一些。
![image](https://github.com/user-attachments/assets/200c5a9a-a1a7-4d0d-919d-8b94f0f3c31e)

**Comment by xix1** [comment]
感恩！！！可以了！！！！！
