### ISSUE TITLE
[Bug]PostgreSQL数据库在数据大屏中导不出来数据

### ISSUE THREAD

**Issue by huahua2023** [dataease/dataease#13426]
DataEase 版本
v2.10.2

运行方式(安装包运行 or 源码运行 ?)
安装包运行

浏览器版本
chrome和edge最新版本

**Bug 描述**
PostgreSQL数据库的图表在数据大屏中导出来的EXCEL表格是有问题的，打开会提示： 无法打开，因为文件格式或文件扩展名无效。
用记本事打开导出来的EXCEL文件里面的内容是：{"code":40001,"msg":"分享链接Token不支持访问当前url[/chartData/innerExportDetails]","data":null}。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/c5c2f7ae-2c1c-49ed-96f4-66c2f06554f1)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前问题应该是已经修复了的，方便说一下你的步骤吗？

**Comment by huahua2023** [comment]
> 感谢反馈，目前问题应该是已经修复了的，方便说一下你的步骤吗？

就是正常的下载导出，所有PostgreSQL数据库的都失败的，sqlserver的数据库正常。

**Comment by BBchicken-9527** [comment]
emm...点击明细后导出excel或导出原始明细还是直接从外面的下载悬浮标识点击下载excel？目前我这边看下载是正常的；这个问题如果有问题应该都有问题才对，因为我看你的提示是权限问题，和实际数据应该关系不大；

**Comment by huahua2023** [comment]
> emm...点击明细后导出excel或导出原始明细还是直接从外面的下载悬浮标识点击下载excel？目前我这边看下载是正常的；这个问题如果有问题应该都有问题才对，因为我看你的提示是权限问题，和实际数据应该关系不大；
查看明细没有看到下载的地方，是悬浮标识点击下载excel的，社区版的应该没有权限可以设置的吧，v2.10.1还是可以的，升级不行了。

**Comment by huahua2023** [comment]
> emm...点击明细后导出excel或导出原始明细还是直接从外面的下载悬浮标识点击下载excel？目前我这边看下载是正常的；这个问题如果有问题应该都有问题才对，因为我看你的提示是权限问题，和实际数据应该关系不大；

查看明细没有看到下载的地方，是悬浮标识点击下载excel的，社区版的应该没有权限可以设置的吧，v2.10.1还是可以的，升级不行了。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前最新版本应该没有此类问题，我先将你的问题暂时关闭若再次出现相同问题欢迎对外群留言或是将问题重新打开；
