### ISSUE TITLE
[Bug]CORS(跨站资源共享)原始验证失败

### ISSUE THREAD

**Issue by 15001244901** [dataease/dataease#13423]
**DataEase 版本**
v2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
深信服扫描

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，只有在嵌入式应用中注册的域名允许跨域；
