### ISSUE TITLE
[Feature]【定时报告】定时报告主题可通过传参数方式设置

### ISSUE THREAD

**Issue by armored-glitch** [dataease/dataease#13429]
DataEase 版本:
v2.10.2

**请描述您的需求或者改进建议.**
尊敬的DataEase团队：
       定时报告可采用占位符或其他方式传入平台其他属性如组织名，用户名，时间日期等,方便用户查看
![image](https://github.com/user-attachments/assets/8c3779c2-50fb-42ea-8c9f-99fe5402b2fa)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
平台其他属性如组织名，用户名等其实对定时报告来说本身就是固定的，没有必要通过参数支持。
另外，邮件等本身就带有日期属性，也没有比较加上日期信息。暂时不考虑支持。
