### ISSUE TITLE
[Feature]【定时报告】通过邮箱发送没有带上数据权限

### ISSUE THREAD

**Issue by armored-glitch** [dataease/dataease#13433]
DataEase 版本:
v2.10.1

**请描述您的需求或者改进建议.**
尊敬的DataEase团队：
       经过多次测试，定时报告通过邮箱发送是没有携带数据权限，不知道是bug还是设计就是如此。并且通过邮箱发送存在某些邮箱号收不到信息。

**Comment by armored-glitch** [comment]
企微等其余办公软件测试较为不便没有进行测试

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，定时报告是带数据权限的，用的是定时报告创建者的数据权限。如果有一些邮箱账号收不到消息，建议检查邮箱账号输入是否有误。
