### ISSUE TITLE
[Bug]【数据大屏】仪表盘设置好了以后，点其他的再重新点仪表盘样式会还原

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#13434]
**DataEase 版本**
V 2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
仪表盘设置好了以后，点其他的再重新点仪表盘会还原

https://github.com/user-attachments/assets/c4c1a93f-51a2-4c52-a678-89751749bc37

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
