### ISSUE TITLE
[Feature]建议仪表板增加刷新按钮(可用作当前页面刷新）

### ISSUE THREAD

**Issue by geyesheng** [dataease/dataease#1343]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/38676947/144046263-a32bb62b-3cdd-4b40-b9b6-3d9228e05945.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，需求已记录

**Comment by xuwei-fit2cloud** [comment]
v1.8.0 已支持，请关注
