### ISSUE TITLE
[Bug] v2 版本数值类型导出在 excel 被识别为文本，后续不好处理

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#13436]
**DataEase 版本**
2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
v2 版本数值类型导出在 excel 被识别为文本，后续不好处理

**Bug 重现步骤(有截图更好)**
1. v1 版本
![image](https://github.com/user-attachments/assets/70329f96-3577-41d6-937d-9c6f8ca964e5)
![image](https://github.com/user-attachments/assets/cec0f23f-14f4-422f-868f-96d7b41547ac)
2. v2 版本
![image](https://github.com/user-attachments/assets/1c019d9a-661e-4513-ae8f-fc7625db7eb9)
![image](https://github.com/user-attachments/assets/02b95ad8-3357-4202-99b1-57893200633b)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行优化；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
