### ISSUE TITLE
[Bug]v2.10.2 es数据源 sql传参数据集  使用查询组件多选报错

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#13449]
![image](https://github.com/user-attachments/assets/a8d88458-b62b-4977-ac07-b9e3c69c2887)
![image](https://github.com/user-attachments/assets/abf3cbac-2132-4826-a086-22aa20677e2d)

"DEException(code=40001, msg=HttpClient查询失败: {\"error\":{\"root_cause\":[{\"type\":\"verification_exception\",\"reason\":\"Found 1 problem(s)\\nline 1:285: 1st argument of [age in('22','25','26','28')] must be [long], found value ['22'] type [keyword]\"}],

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。

**Comment by fr58386612** [comment]
ES数据源，使用明细表的时候 无法翻页的问题请问在那个版本解决了吗？
