### ISSUE TITLE
[Feature]希望跳转功能可以关联视图中没有添加的字段

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#13442]
DataEase 版本:
v2.10.2

**请描述您的需求或者改进建议.**
在跳转界面，如果当前视图的数据集有时间字段，但是这个字段没有添加到视图，那在关联字段中就没有该字段。希望不在视图中的字段，也可以被关联
![image](https://github.com/user-attachments/assets/0831919f-6a2a-4838-a792-29d3936f6701)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，目前暂时没有计划支持该功能。
