### ISSUE TITLE
[Bug]关于折线图中数据升序无法展示最新n条数据的问题

### ISSUE THREAD

**Issue by Pyangs** [dataease/dataease#13450]
**DataEase 版本**
2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
Chrome
版本 131.0.6778.70（正式版本） （64 位）

**Bug 描述**
1.在制图过程中，使用折线图时一般对轴（我的示例为date）采用升序，符合读图习惯，使用de制作时由于我的数据（10月份起至今每天的最高最低气温）是逐渐增加的，不可能选用显示所有数据，所以预期只显示最新的20条，而目前的de无法实现这个目的。
2.采用降序情况下可以展示数据，但不符合读图习惯和开发预期，因为这样变成了左边是最新日期，而右边是过往信息

我个人思路是对数据选取提供切片形式的选取功能，如[-20;]，这样可以极大提高灵活性，例如[-20:-5]选取特定区间。贵司有更好思路也可

**Bug 重现步骤(有截图更好)**
1.

![微信图片_20241120231435](https://github.com/user-attachments/assets/b251f4fb-5926-454f-93dd-e068d36ff60a)
2.
![image](https://github.com/user-attachments/assets/dc2a3db7-da31-470e-b174-5e50cb507922)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，结果展示条目数为可显示的条目数，而排序在获取条目数之后，所以你看到的数据可能不连贯，可以使用图表过滤器选择动态时间去进行控制；后续版本我们会进行top n的支持；

**Comment by Pyangs** [comment]
谢谢！使用图表过滤器可以实现我的目标
