### ISSUE TITLE
[Feature]线面图无法将时间维度精细化到日以下的问题以及汇总方式问题

### ISSUE THREAD

**Issue by Pyangs** [dataease/dataease#13451]
DataEase 版本:
2.10.2

**请描述您的需求或者改进建议.**
![252b1ab1e186988c13d06b6b5539540](https://github.com/user-attachments/assets/93174376-cd89-4e75-a794-555317fe89fc)
![253c53954025b2b1d6965e928447297](https://github.com/user-attachments/assets/0c8ab519-eb99-43cc-ab6f-84ade3ced822)
有以上数据示例和展示情况，因为数据是每3小时一条，一天8条。事实上预期是按小时展示数据，而在绘制折线图时经过长期探索仍然无法实现预期，不知道是没有这个功能还是我不会用。

1是否可以按其他时间单位作为颗粒度，如：小时
2是否能新增“不汇总”的选项，以显示原值。图2展示了无法展示图1的每3小时的温度值的问题

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复如下：
1、可以按小时作为颗粒度进行汇总，计算每个时间点的数据，建议新建计算字段，截取年月日时；或者如下图所示，设置日期格式为：时分秒
![image](https://github.com/user-attachments/assets/3ba01500-1590-4640-bf92-53649cad8fff)
2、线面图是根据维度聚合的，如果数据不需要聚合，建议使用明细表。

**Comment by Pyangs** [comment]
谢谢！明白了！
