### ISSUE TITLE
[Bug] mysql和API数据集的左关联无法关联

### ISSUE THREAD

**Issue by alonegem** [dataease/dataease#13468]
**DataEase 版本**
V2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
EDGE

**Bug 描述**
mysql和API数据集的左关联

**Bug 重现步骤(有截图更好)**
1.创建数据集
2.左表选择mysql类型的
3.右表选择API类型的
4.创建关联查询为左关联
5.无法正常查出关联数据
![image](https://github.com/user-attachments/assets/5937a285-c04a-44f0-a0cd-6ebd938f3911)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，测试使用mysql8，受累试一下你那边还会不会有问题；
![image](https://github.com/user-attachments/assets/13d99a83-4828-45e1-bc20-a9a5a078de0c)

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
