### ISSUE TITLE
[Feature]【定时报告】发送普通用户的报告

### ISSUE THREAD

**Issue by armored-glitch** [dataease/dataease#13464]
DataEase 版本:
v2.10.2

**请描述您的需求或者改进建议.**
尊敬的DataEase团队：
        目前定时报告是用的是定时报告创建者的数据权限,后续会开发类似模块，发送的定时报告所带有的权限是使用者的权限（使用场景是，给员工发送每个月的薪资待遇）

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，定时报告一般用于统一发送仪表板报告，所有用户收到的内容相同，因此目前暂时没有计划支持报告带使用者的权限。
