### ISSUE TITLE
[Bug]SQL中同时包含 UNION 和参数会报错

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#13472]
**DataEase 版本**
2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
创建数据集，编写 SQL，SQL 中使用左连接子查询中包含 UNION ，并且带参数 name in (${name}) 
会报错；
去掉 子查询中UNION ，或 参数 name in (${name}) ，均可正常运行。

SQL Server 2017 数据源报错
<img width="1163" alt="image" src="https://github.com/user-attachments/assets/d038e43f-75ea-4984-86af-f8c3067bbae7">

MySQL 8 数据源报错
<img width="1337" alt="image" src="https://github.com/user-attachments/assets/cd4f71b2-fc7f-4f3d-87e3-fbff6e6c3e95">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，建议尝试升级体验；
