### ISSUE TITLE
[Bug] 点击数据导出中心，就会报错，原本有数据的导出列表无法显示，需要重启服务，删除掉所有导出数据才恢复正常。

### ISSUE THREAD

**Issue by daiqingyao6238** [dataease/dataease#13483]
**DataEase 版本**
2.10.1和2.10.2

**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**

版本 131.0.6778.70（正式版本） （64 位）
**Bug 描述**
有两个客户出现点击数据导出中心出错问题

其中一个客户点击数据导出中心，原本有导出数据的列表为空，报空指针错误，重启服务，再删除历史导出数据才恢复正常。
![d4f10830e43e4f4196a2f0b2c23472f](https://github.com/user-attachments/assets/e0151892-6e05-46ec-ab8a-e4e74e5aa961)

另一个客户点击数据导出中心 ，dataease服务内存巨增，直接崩掉，页面显示502
![企业微信截图_17321678686870](https://github.com/user-attachments/assets/9a26f8a2-db6a-40c9-8425-f9792d2693a1)
![企业微信截图_17320891331461](https://github.com/user-attachments/assets/66745513-6db3-40bb-9c34-eca8f5fb3fd6)

重启服务，再删除历史导出数据才恢复正常。
![image](https://github.com/user-attachments/assets/c10a2de4-777d-4829-9dec-f36eea312929)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，请问是否又后台日志我们可以看一下？
