### ISSUE TITLE
[Feature]已创建的数据同步任务可以修改字段类型

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#13497]
DataEase 版本:
2.10.2

**请描述您的需求或者改进建议.**
定时同步任务中，获取的字段类型和长度，有时候不一定准确，希望可以在已创建的同步任务修改字段类型，此修改直接 alter Doris 数据库中创建的表。
<img width="1928" alt="image" src="https://github.com/user-attachments/assets/38f79b7f-cb02-42a0-8eb6-089b637e82ec">

**Comment by xuwei-fit2cloud** [comment]
在创建同步任务的时候，是可以点击字段后面的编辑按钮对字段类型、长度等进行调整的。
在任务创建完成后，不支持对字段进行修改。
