### ISSUE TITLE
[Feature]数据集关联另一个数据集

### ISSUE THREAD

**Issue by tinyxia** [dataease/dataease#13505]
DataEase 版本:2.10.2

我建了一个企业信息的数据集，这个数据集是我从业务库加工过的，类似数仓里的dwd层的一张表，我现在订单信息数据集中想引用企业信息数据集，避免重复关联业务表，做重复劳动，提升效率。反正我就是想加工一些常用的数据集做中间表，方便我后续数据集的创建，思路像做数仓一样。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持数据集的关联。
