### ISSUE TITLE
[Feature]【大屏】筛选条件按照上次条件查看

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#13502]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
需求：筛选组件支持默认展示支持配置上次选择条件。
![image](https://github.com/user-attachments/assets/6368a8f5-3cf6-43d5-aba7-fbce3b28c1c8)
效果：用户上次查询大屏的筛选条件选择情况，会被系统记录，下次进入改大屏，显示的是筛选条件是上次一样的筛选条件。

**Comment by xuwei-fit2cloud** [comment]
目前没有支持计划。
