### ISSUE TITLE
[Bug] 明细表数据导出，数据类型全部为文本格式

### ISSUE THREAD

**Issue by daiqingyao6238** [dataease/dataease#13517]
**DataEase 版本**
2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 131.0.6778.86（正式版本） （64 位）

**Bug 描述**
在2.10.2 版本的仪表板导出数据，数据格式全部显示为文本类型，在 2.9 版本的仪表板导出数据，数据格式可以正常显示。

**Bug 重现步骤(有截图更好)**
1.使用 2.10.2 版本仪表板数据导出的 excel 表显示，有感叹号报警
![image](https://github.com/user-attachments/assets/8c18b585-b7a7-4ad5-9ca9-9e24e85361bc)

2.使用 2.9 版本仪表板数据导出的 excel 表显示，没有感叹号报警
![image](https://github.com/user-attachments/assets/0e708524-20af-4439-a340-e587d018e270)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，目前正在努力修复中，将会在下个版本完成；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
