### ISSUE TITLE
[Feature]希望能像tableau那样的loc（固定级）表达式

### ISSUE THREAD

**Issue by Kentxiaoju** [dataease/dataease#13515]
有时候数据库不方便改动，但是计算小计和总计
时某些数据是固定的，遇到一个instance 对应多个行的时候会重复计算，最终导致部分小计过多，总计过多，这个可以用loc 解决
即
gpt：
在 Tableau 中，LOC（Level of Calculation，即级别计算）表达式通常是指 固定级别计算，即 FIXED 级别的计算字段。FIXED 表达式是一种 LOD（Level of Detail）计算，用来控制聚合级别，允许你在特定维度上计算值，而不受可视化中的其他上下文过滤器或维度的影响

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们已将需求记录。
这个功能的支持复杂度较高，短期内还无法实现，后续我们会尽力支持。
