### ISSUE TITLE
[Bug] dectl restore 启动失败问题

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#13526]
**DataEase 版本**
 v2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
有两台机器，分别为 A、B
1.分别在 A 和 B 上整包安装 DataEase v2.10.2
2.安装后创建一些资源，如仪表板、大屏、上传背景图等
3.使用 dectl backup 将 A 服务备份
4.将 A 服务备份文件上传至 B 服务，使用 dectl resotre 恢复备份

期望：B 服务正常运行，且数据与 A 服务一致
实际：B 服务数据库启动异常。B 服务的 安装目录中与 A 服务不一致的文件未被删除，二者做了并集合并，导致 B 服务有多余文件。

建议：恢复备份时提示用户先备份，随后删除安装目录，将其替换为要恢复的内容。

**Comment by xuwei-fit2cloud** [comment]
我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
