### ISSUE TITLE
[Feature]【大屏】大屏支持评论功能

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#13523]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
大屏支持评论功能，类似下图。
![image](https://github.com/user-attachments/assets/9fcccd39-da6c-4c15-a72e-73bd57d0465d)
参考地址：https://help.aliyun.com/zh/quick-bi/user-guide/manage-dashboards#4f094de057be6

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，需求已记录，等后期有同类需求反馈后我们再考虑支持。短期内没有支持计划。
