### ISSUE TITLE
[Bug]查询条件时间范围设置时间筛选范围后，限制单次查询最多3日，但是实际渲染的范围控件上 只限制了向后选择，向前还是能跨越选择很多天

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#13533]
**DataEase 版本**
v2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
最新

**Bug 描述**
查询条件时间范围设置时间筛选范围后，限制单次查询最多3日，但是实际渲染的范围控件上 只限制了向后选择，向前还是能跨越选择很多天

**Bug 重现步骤(有截图更好)**
1.设置查询组件
<img width="1476" alt="image" src="https://github.com/user-attachments/assets/b0c21f4e-240f-4cc2-a89d-f85ac5d62e4d">
2.筛选如视频所示：

https://github.com/user-attachments/assets/e38bf106-2613-4762-a8ef-fef4ebd02659

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，目前正在努力修复中，将会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
