### ISSUE TITLE
[Question] MySQL 表数据中含有换行符时，查询组件会查不出来数据，这个是产品机制还是 bug 呢

### ISSUE THREAD

**Issue by daiqingyao6238** [dataease/dataease#13536]
**请描述您的问题.**
当 数据库中的username 字段有数据含有换行符，在 dataease 中使用查询组件筛选数据显示异常。
![image](https://github.com/user-attachments/assets/f7fed86f-6484-4731-8a1a-69392bd72f0e)
![image](https://github.com/user-attachments/assets/784727bb-9c80-466a-b0e0-67f5f5c99bf7)
![image](https://github.com/user-attachments/assets/56108c3e-1d45-4cd1-8e86-24b0b1c4b508)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，数据中带换行符目前没有做处理，我们需要先讨论下处理方式。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们修复一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该bug已在 v2.10.3 版本修复，建议升级版本。
