### ISSUE TITLE
[Feature] 柱状图支持 Small multiples，类似于 powerbi

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#13532]
DataEase 版本:
v2.10.2

**请描述您的需求或者改进建议.**
柱状图支持 Small multiples，类似于 powerbi
![image](https://github.com/user-attachments/assets/94e7c41c-b543-4a2f-ad11-06af98b12a36)

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #12712
