### ISSUE TITLE
[Bug]折线图设置最值后，最值处标签显示不全，已经上去了，但很多时候这里要固定最值

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13545]
**DataEase 版本**
折线图设置最值后，最值处标签显示不全，已经上去了，但很多时候这里要固定最值

![image](https://github.com/user-attachments/assets/3dc812cb-16e2-4bc5-873b-c8e43649fef4)

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
