### ISSUE TITLE
[Bug] 明细表通过设置可以使得圆角不生效

### ISSUE THREAD

**Issue by daiqingyao6238** [dataease/dataease#13568]
**DataEase 版本**

2.10.2
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 已是最新版本
版本 131.0.6778.86（正式版本） （64 位）

**Bug 描述**
明细表通过设置可以使得圆角不生效
内边距设置为0，取消标题，前端圆角设置不生效
**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/04049873-6b74-4650-ad86-9c2d74222199)

2.
![image](https://github.com/user-attachments/assets/86657f84-a389-46ec-96e4-d0ed569db51d)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，当前版本没有发现你说的问题，方便的话建议升级体验；
