### ISSUE TITLE
[Question]如何降版本

### ISSUE THREAD

**Issue by lyons6** [dataease/dataease#13584]
**请描述您的问题.**
从2.10.1升级到2.10.2后，因2.10.2出现了新的bug导致可用性还没2.10.1的高，现在想从2.10.2降回2.10.1，该如何操作？(离线安装)

**Comment by yayanpei-fit2cloud** [comment]
请问升级之前做备份了吗？如果备份了，可以参考文档（https://dataease.io/docs/v2/installation/backup_faq/ ）还原。

**Comment by maninhill** [comment]
请问具体是出现了什么 bug ？

**Comment by maninhill** [comment]
是这个问题吗？ https://github.com/dataease/dataease/issues/13243

**Comment by lyons6** [comment]
> 是这个问题吗？ #13243

您好！是的，是这个问题

**Comment by lyons6** [comment]
@maninhill 您好！是的，是这个问题

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
