### ISSUE TITLE
[Bug]仪表板配置中设置联动钻取跳转的图标相关设置时，下钻的层级间箭头颜色未变化

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#13589]
**DataEase 版本**
v2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
最新

**Bug 描述**
仪表板配置中设置联动钻取跳转的图标相关设置时，下钻的层级间箭头颜色未变化，如图所示

**Bug 重现步骤(有截图更好)**
1.
<img width="968" alt="image" src="https://github.com/user-attachments/assets/4616d4b3-3368-4c8b-a9b7-92024e8f9efe">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
