### ISSUE TITLE
[Feature] 数据大屏支持批量选择图表，横向或纵向平均分布排列

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#13599]
DataEase 版本:
v2.10.2

**请描述您的需求或者改进建议.**
数据大屏支持批量选择图表，横向或纵向平均分布排列

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论后再进行回复。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，由于图层的叠加，组件之间的间距有的要参与平均分，有些组件不需要，系统不好统一分配，目前暂时没有计划支持。
