### ISSUE TITLE
[Bug] 分组柱状图，设置钻取维度排序，钻取后排序未生效

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#13598]
**DataEase 版本**
v2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
Google Chrome
版本 131.0.6778.86（正式版本） （64 位）

**Bug 描述**
分组柱状图，设置钻取维度排序，钻取后排序失效

**Bug 重现步骤(有截图更好)**
1.  分组柱状图设置好自定义排序
![image](https://github.com/user-attachments/assets/d7c6ddcf-c079-4ef1-bd94-8bc02b43a741)

2. 钻取后排序并未生效

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
