### ISSUE TITLE
[Bug] 符号地图全屏时，地图被缩放

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#13603]
**DataEase 版本**
v2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
符号地图全屏时，地图被缩放

**Bug 重现步骤(有截图更好)**
1. 正常
![image](https://github.com/user-attachments/assets/80a5855d-2896-45d9-96fb-8fd8ab667173)
2. 全屏
![image](https://github.com/user-attachments/assets/313f142a-8442-4c00-9553-2bc2723dcfc3)

附： 热力地图同理

**Comment by xuwei-fit2cloud** [comment]
试试去掉自适应缩放选项
![图片](https://github.com/user-attachments/assets/80a85ddf-a59e-4028-b98e-f9c73d1e0a46)
