### ISSUE TITLE
[Feature]辅助线希望这边可以选择其他数据表的字段，因为一般都是会把指标标准和真实数据分开放的

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13604]
DataEase 版本:
v2.10.2

**请描述您的需求或者改进建议.**
辅助线希望这边可以选择其他数据表的字段，因为一般都是会把指标标准和真实数据分开放的

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持，建议在数据集中做表关联，放到一个数据集中。
