### ISSUE TITLE
[Feature]平潭综合实验区 未显示

### ISSUE THREAD

**Issue by armored-glitch** [dataease/dataease#13602]
DataEase 版本:
2.10.2

**请描述您的需求或者改进建议.**
尊敬的DataEase团队：
      福建地图中，平潭综合实验区（福建省辖行政管理区）未显示。

**Comment by armored-glitch** [comment]
从福建省的规划上来说，现在是9市1区

**Comment by xuwei-fit2cloud** [comment]
从国家统计局和民政部的数据上，目前还没有看到相关数据。我们以国家政府官网数据为准。
