### ISSUE TITLE
[Feature]（建议）能够出更多sql优化方案

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13629]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
（建议）能够出更多对查询 sql 优化的方案，现有的除了参数、doris（有工作量且迁移数据不是一个小事情）、sql数据集命中索引，就没有别的很多的优化了，实际查询还是有些慢的

**Comment by xuwei-fit2cloud** [comment]
SQL的优化是个持续的过程，我们也在不断减少和优化查询的嵌套层次等方面。
你目前还有什么更具体的优化需求可以具体列出来。

**Comment by zhainanshidai** [comment]
那顺便可以都放这儿
1.sql 数据集我记得是整体传库里查的，好像不会抽取字段而是在外部做处理，这个整体sql能不能按数据集为单位，一个仪表板/大屏只查一次，可以很大程度上减少查询时间，这个可以讨论一下的
2.sql能不能像帆软一样给出性能提示
3.sql中间层做优化处理，像指令编译过程一样，有一个中间代码优化环节。

**Comment by FantasyNeurotic** [comment]
> 那顺便可以都放这儿 1.sql 数据集我记得是整体传库里查的，好像不会抽取字段而是在外部做处理，这个整体sql能不能按数据集为单位，一个仪表板/大屏只查一次，可以很大程度上减少查询时间，这个可以讨论一下的 2.sql能不能像帆软一样给出性能提示 3.sql中间层做优化处理，像指令编译过程一样，有一个中间代码优化环节。

发现现有的大屏时每个指标没有图形都去查一次，这里非常消耗性能，不是应该每个数据集在需要的时候去查一次就可以么

**Comment by yayanpei-fit2cloud** [comment]
数据集查询的是明细数据，图表请求的sql是带过滤条件，而且是根据维度聚合后的结果，这个数据量会少很多，而且对比把数据集的明细数据都查询出来，放在内存中再进行聚合计算，在数据库中进行聚合计算性能更优。

您也可以下载源码，通过修改源码进行性能方面的验证，如果有更好的方案也欢迎给我们提交pr。我们也会持续不断的进行性能方面的优化。

**Comment by yayanpei-fit2cloud** [comment]
我们就先把issue关闭了，如果后期有更好的建议，您可以重新打开issue。
