### ISSUE TITLE
[Feature]仪表板切换提高加载速度

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#13653]
DataEase 版本:
 v2 \ v3

**请描述您的需求或者改进建议.**
点击左侧菜单切换仪表板使用缓存数据，可以做到秒加载，增加用户体验；
仪表板右上方的刷新数据可以是实时加载的。
<img width="1447" alt="image" src="https://github.com/user-attachments/assets/7ea8c2b0-9674-4d55-86db-130231ef7803">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，v2.10.3 版本已经做了加载速度的优化，预计下周四发版。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
