### ISSUE TITLE
Failed to start DataEase Service

### ISSUE THREAD

**Issue by lizhichao999** [dataease/dataease#13675]
**请描述您的问题.**
[root@localhost dataease-offline-installer-v2.10.0-ce]# ./install.sh
当前时间 : Fri Nov 29 10:52:38 CST 2024
1. 检查安装环境并初始化环境变量
	停止 DataEase 服务
	升级安装
2. 设置运行目录
	运行目录 /opt/dataease2.0
	配置文件目录 /opt/dataease2.0/conf
3. 初始化运行目录
	复制安装文件到运行目录
	调整配置文件参数
4. 安装 dectl 命令行工具
	安装至 /usr/local/bin/dectl & /usr/bin/dectl
5. 修改操作系统相关设置
	防火墙未开启，忽略端口开放
6. 安装 docker
	检测到 Docker 已安装，跳过安装步骤
	启动 Docker 
7. 安装 docker-compose
	检测到 Docker Compose 已安装，跳过安装步骤
8. 加载 DataEase 镜像
	已存在镜像 dataease:v2.10.0
	已存在镜像 mysql:8.4.0
9. 配置 DataEase 服务
10. 启动 DataEase 服务
Job for dataease.service failed because the control process exited with error code. See "systemctl status dataease.service" and "journalctl -xe" for details.

======================= 升级完成 =======================

[root@localhost dataease-offline-installer-v2.10.0-ce]# systemctl status dataease.service
● dataease.service - DataEase Service
   Loaded: loaded (/etc/systemd/system/dataease.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2024-11-29 10:52:41 CST; 7s ago
  Process: 2368 ExecStart=/usr/bin/dectl start (code=exited, status=1/FAILURE)
 Main PID: 2368 (code=exited, status=1/FAILURE)

Nov 29 10:52:39 localhost.localdomain dectl[2368]: Container mysql-de  Starting
Nov 29 10:52:39 localhost.localdomain dectl[2368]: Container mysql-de  Started
Nov 29 10:52:39 localhost.localdomain dectl[2368]: Container mysql-de  Waiting
Nov 29 10:52:40 localhost.localdomain dectl[2368]: Container mysql-de  Error
Nov 29 10:52:40 localhost.localdomain dectl[2368]: dependency failed to start: container mysql-de exited (1)
Nov 29 10:52:41 localhost.localdomain dectl[2368]: 未找到容器 dataease。
Nov 29 10:52:41 localhost.localdomain systemd[1]: dataease.service: main process exited, code=exited, status=1/FAILURE
Nov 29 10:52:41 localhost.localdomain systemd[1]: Failed to start DataEase Service.
Nov 29 10:52:41 localhost.localdomain systemd[1]: Unit dataease.service entered failed state.
Nov 29 10:52:41 localhost.localdomain systemd[1]: dataease.service failed.

离线安装，一建启动报这个错

**Comment by xuwei-fit2cloud** [comment]
docker logs -f mysql-de 看看，看着是MySQL容器启动出错了。

**Comment by sweeticetea** [comment]
我是这样解决的，仅供参考：
查了mysql-de日志提示`2026-01-29T01:16:00.818570Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.`
删除dataease/data/mysql目录，在docker-compose-mysql.yml加入`privileged: true`（操作系统是openEuler）
在项目下`docker-compose -f docker-compose-mysql.yml -f docker-compose-apisix.yml ...down` 
最后dectl reload 启动成功
