### ISSUE TITLE
[Feature]富文本为decimal的单行输入仍然提示类似报错的信息，虽然可以保存，这个需要优化一下。

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13670]
DataEase 版本:
v2.10.2

**请描述您的需求或者改进建议.**
富文本为decimal的单行输入仍然提示类似报错的信息，虽然可以保存，这个需要优化一下。
在数据库中，单行小数可以保存：
![image](https://github.com/user-attachments/assets/293d4bc2-fc17-4510-b7be-d9a74322b131)
![image](https://github.com/user-attachments/assets/3d91e2c1-925f-405d-856f-7a6481cb3741)

这样不报错
![image](https://github.com/user-attachments/assets/783ee25a-aac1-427b-9f21-a4f423dbe5d1)
这样提示错误，会让人觉得是错了
![image](https://github.com/user-attachments/assets/ca60d5a5-ca30-4ea1-90ec-3646df5709c2)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，这个是组件自带的，我们试试给隐藏掉。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
