### ISSUE TITLE
[Feature] 允许单独设置查询条件和按钮的字体

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#13674]
DataEase 版本:
2.10.2

**请描述您的需求或者改进建议.**
允许单独设置查询条件和按钮的字体
![image](https://github.com/user-attachments/assets/bfcef683-658c-4912-9710-ed558e1c122e)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该功能已经开发完成，预计在v2.10.3版本发布。在仪表板配置中设置全局字体后，可以控制查询组件的字体。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
