### ISSUE TITLE
[Bug]指标卡过滤器等于今年不生效

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#13684]
**DataEase 版本**
v2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
最新

**Bug 描述**
在数据集中，将文本的年份，新建计算字段，修改为日期格式的字段，通过指标卡过滤器过滤大于小于今年生效，等于今年不生效

**Bug 重现步骤(有截图更好)**
1.基于DataEase内置表，新建自定义SQL语句：select name ,DATE_FORMAT(FROM_UNIXTIME(create_time/1000), '%Y') AS create_time from per_user
![image](https://github.com/user-attachments/assets/f9c2692d-fd9a-4742-ac09-6f1ab1f6052b)
2.基于create_time新建一个计算字段，保存数据集
![image](https://github.com/user-attachments/assets/00798bca-7bb3-4d33-b2b7-1e5a6362039c)
3.使用指标卡统计记录数，增加过滤器，过滤今年的数据
大于去年的SQL（生效）：SELECT * FROM (SELECT COUNT(*) AS `f_ay_0` FROM (SELECT t_a_0.`name` AS `f_31d669b8f9f753cf`,t_a_0.`create_time` AS `f_3bcb46db6b86ddc9` FROM (select name ,DATE_FORMAT(FROM_UNIXTIME(create_time/1000), '%Y') AS create_time from per_user) t_a_0) AS `t_a_0` WHERE `t_a_0`.`f_3bcb46db6b86ddc9` > '2023-12-31 23:59:59') AS `t_a_1` LIMIT 1000 OFFSET 0

等于今年的SQL（不生效）：SELECT * FROM (SELECT COUNT(*) AS `f_ay_0` FROM (SELECT t_a_0.`name` AS `f_31d669b8f9f753cf`,t_a_0.`create_time` AS `f_3bcb46db6b86ddc9` FROM (select name ,DATE_FORMAT(FROM_UNIXTIME(create_time/1000), '%Y') AS create_time from per_user) t_a_0) AS `t_a_0` WHERE `t_a_0`.`f_3bcb46db6b86ddc9` BETWEEN  '2024-01-01 00:00:00' AND '2024-12-31 23:59:59') AS `t_a_1` LIMIT 1000 OFFSET 0
![image](https://github.com/user-attachments/assets/34959577-2e0f-4566-8fd4-e0afbd1e9864)
![image](https://github.com/user-attachments/assets/f5fd87f7-838a-4749-97cf-7c96518f3660)
![image](https://github.com/user-attachments/assets/db379317-9fdf-4548-bc75-2722ffb34dcd)

**Comment by xuwei-fit2cloud** [comment]
因为字段类型和表达式的类型不一致，所以导致了不生效。
我们后续优化一下相关提示信息，不至于产生使用上的误会。
