### ISSUE TITLE
[Feature]这个统计数据导出，里面的数字，进行排序，是按照字符串/原始格式的方式在排的，我们现在是要下载，然后可能要根据另外字段去排序，看看能否优化一下，增加相关项

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13683]
DataEase 版本:
v2.10.2

**请描述您的需求或者改进建议.**
这个统计数据导出，里面的数字，进行排序，是按照字符串/原始格式的方式在排的，我们现在是要下载，然后可能要根据另外字段去排序，看看能否优化一下，增加相关项

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持，建议下载后在excel中根据另外的字段进行排序。
