### ISSUE TITLE
[Feature]sql性能提示

### ISSUE THREAD

**Issue by armored-glitch** [dataease/dataease#13699]
DataEase 版本:
2.10.2

**请描述您的需求或者改进建议.**
尊敬的DataEase团体：
         有时候加载过慢不好定位问题点，能否考虑添加性能分析功能，监控服务器情况等，帮助用户更快定位性能问题

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by huahua2023** [comment]
V2版本的数据加载越来越慢了，特别是10.2版本的，V1的很快

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前没有计划支持性能分析、服务器监控等功能。

**Comment by yayanpei-fit2cloud** [comment]
> V2版本的数据加载越来越慢了，特别是10.2版本的，V1的很快

v2.10.3 对性能进行了优化，提升了仪表板的加载速度等，建议升级版本。
