### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by daviadong** [dataease/dataease#1369]
**请描述您的需求或者改进建议.**
因使用人比较多，但在mysql数据源中，原始数据都存在同一张表上，虽然通过企业版的权限管理把数据集的操作权限限制住，但因业务人员太多，且业务范围会经常调整，频繁修改SQL数据集对于数据管理人员工作量实在太大。
希望能增加数据库的行级限制，可以精确到数据库行级权限控制，允许不同用户查看同一张表时，看到不同的数据。
或者增加SQL数据集的变量传参功能，根据登入的人，来刷选展示数据。
![image](https://user-images.githubusercontent.com/51897467/144245094-c0482f05-9a38-4457-b922-dad7be0f62c8.png)

**Comment by xuwei-fit2cloud** [comment]
行级权限的支持还在开发中，请等待新版本。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 版本支持行权限，请等待新版本发布。
