### ISSUE TITLE
[Feature]左中右的提示会挡住字体大小选项

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#13697]
DataEase 版本:
2.10.2

**请描述您的需求或者改进建议.**
实际图标的意思很明确，是否可以去掉提示框
![image](https://github.com/user-attachments/assets/83b542d1-aeb3-47c5-b5d9-ae880c0b3327)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，将鼠标从位置选项上移开，便不再展示提示框，不影响字体的设置。
