### ISSUE TITLE
[Question]部署好以后, 登录提示错误

### ISSUE THREAD

**Issue by Mr-TChao** [dataease/dataease#13707]
**请描述您的问题.**
![bug](https://github.com/user-attachments/assets/576d178c-acba-420d-823f-822fd8d3a9cc)
![bug](https://github.com/user-attachments/assets/9b2dfbeb-3714-446f-9641-c1e85076965c)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，建议先清理前端缓存后，再进行登录。
