### ISSUE TITLE
求支持greenplum和RestfulAPI数据源[Feature]

### ISSUE THREAD

**Issue by plateauandsp** [dataease/dataease#1370]
**请描述您的需求或者改进建议.**
求支持greenplum和RestfulAPI数据源

**Comment by yayanpei** [comment]
感谢您的反馈，我们会先进行内部讨论，综合考虑后，规划优化。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
