### ISSUE TITLE
数据大屏中表格里的放大功能，能否自己改放大后的窗口大小

### ISSUE THREAD

**Issue by SuperManYo** [dataease/dataease#13715]
**请描述您的问题.**
版本：2.10.1
源码启动
如下图红框内容为放大后显示，我想把这个放大后的窗口改下大小，能否告知如何在代码中左调整，谢谢！
![image](https://github.com/user-attachments/assets/aac8e464-7c5f-4cb5-8bda-f8efe51c22b0)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，对源码的修改，原则上我们是不提供技术支持的，建议您尝试自己去找到相应的代码，并进行修改。
