### ISSUE TITLE
[Question]表格视图在超大屏幕字体会变糊，请问有没有好的办法避免

### ISSUE THREAD

**Issue by hzhwyh0116** [dataease/dataease#13729]
**请描述您的问题.**
<img width="1120" alt="image" src="https://github.com/user-attachments/assets/3a1a5c02-637c-40dd-bd66-0e7e3bbbd6e4">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，v2.10.3 版本增加了缩放模式：不缩放，建议新版本发布后，将数据大屏设置为不缩放的模式。
