### ISSUE TITLE
[Feature]查询条件样式能否分开设置 “查询框宽度”和“查询下拉条件宽度”

### ISSUE THREAD

**Issue by hzhwyh0116** [dataease/dataease#13728]
DataEase 版本:
v2.10.2

**请描述您的需求或者改进建议.**
查询条件样式能否分开设置 “查询框宽度”和“查询下拉条件宽度”
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/2bee1d94-172a-47ec-b652-fe5822bec395">

目前查询框宽度和下拉条件的宽度是绑定的，能否分开设置以便展示

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已经开发完成，请等待本周四的新版本发布。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
