### ISSUE TITLE
[Feature]分析场景自由构图拖拽维度指标功能

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#13736]
DataEase 版本: v2.10.2

**请描述您的需求或者改进建议.**
目前只能由开发人员来构建拖拽图形， 拥有查看权限的人员无法操作。 同时现有方式又太复杂。

能否提供自由构建图形能力，在现有已定义的报表下面提供自由构图功能，
可以供选择，维度和指标。同时选择 展示图形。
类似下图效果:
![image](https://github.com/user-attachments/assets/f893ad4a-3bf6-40d8-a024-551216659d8f)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，在仪表板预览状态下，目前暂时没有计划提供构图功能。如果需要对仪表板的图表进行编辑、重新布局等，建议管理员授予用户仪表板的管理权限。
