### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by supersarah123** [dataease/dataease#1374]
**DataEase 版本**
 v1.5.0

**浏览器版本**
chrome 版本 96.0.4664.55（正式版本） (x86_64)

**Bug 描述**
导入的excel数据集，数值类型的字段转成时间类型的字段后，转成的时间不对。

**Bug 重现步骤(有截图更好)**
1.原始数据中的年度字段是数值类型
![image](https://user-images.githubusercontent.com/45278450/144375465-f95fa1a3-d073-4747-9cec-04cf4331e836.png)
2.转成时间类型字段后
![image](https://user-images.githubusercontent.com/45278450/144375595-159e4795-740c-4cc8-929d-b525c4fb7585.png)

**Comment by BBchicken-9527** [comment]
感谢你的发现，因为现在时间类型只支持固定的格式，目前不知支持单独的年月日的情况。
