### ISSUE TITLE
[Bug] windows下地图资源映射不正确

### ISSUE THREAD

**Issue by xuewenquan** [dataease/dataease#13748]
**DataEase 版本**
dev-v2

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
最新版

**Bug 描述**
windows下不能显示地图

**Bug 重现步骤(有截图更好)**
应该使用URL_SEPARATOR常量，而不是FILE_SEPARATOR原因：在windows下FILE_SEPARATOR的值是反斜杠，导致DeMvcConfig在配置静态资源映射的时候，url路径是错的。
![image](https://github.com/user-attachments/assets/a64c4f0b-8fb7-4e20-841d-2776c0094785)

**Comment by xuwei-fit2cloud** [comment]
已处理，请更新代码。
