### ISSUE TITLE
[Bug] 系统报错，导致无法进入系统页面

### ISSUE THREAD

**Issue by mars-Linzp** [dataease/dataease#13745]
**DataEase 版本**
2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
1Panel应用商店安装

**浏览器版本**
与浏览器无关

**Bug 描述**
系统异常导致程序崩溃无法进入

**Bug 重现步骤(有截图更好)**
![image](https://github.com/user-attachments/assets/ee6d22a7-6a20-4a30-8f3e-1be0a4803768)

![image](https://github.com/user-attachments/assets/e2ddf869-de7c-40e2-bf70-533625d99e59)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们尝试了一下目前没有发现你说的安装问题，请问你是如果操作的呢？

**Comment by mars-Linzp** [comment]
我是从1Panel安装正常使用，一段时间后出现这个问题，期间没有操作，从应用商店重新安装后正常
