### ISSUE TITLE
[Bug]透视表未设置【数据列 / 维度】下载报错

### ISSUE THREAD

**Issue by zhangwenkl** [dataease/dataease#13753]
**DataEase 版本**
1.18.25

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome 131.0.6778.86

**Bug 描述**
创建透视表视图，设置【数据行 / 维度】、【数据列 / 指标】。未设置【数据列 / 维度】。点击【导出Excel（带格式）】无反应

**Bug 重现步骤(有截图更好)**
1.创建透视表视图
2.设置【数据行 / 维度】、【数据列 / 指标】，不设置【数据列 / 维度】
![image](https://github.com/user-attachments/assets/c7deab7a-d4b4-4bdc-8606-59bec9be4fe7)

3.点击【导出Excel（带格式）】
![image](https://github.com/user-attachments/assets/dbf5a00b-f056-43e7-8e7c-2457231f2717)

4.控制台异常，且未下载Excel成功（保存后到预览页面访问也无法下载）
![image](https://github.com/user-attachments/assets/19002088-30a8-4112-a1d4-b7c503563f1a)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，可以尝试下载最新版本；
![image](https://github.com/user-attachments/assets/5a776cfe-7ee2-4ea7-974d-782cb2ad2dea)
