### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by supersarah123** [dataease/dataease#1375]
**DataEase 版本**
v1.5.0

**浏览器版本**
chrome 版本 96.0.4664.55（正式版本） (x86_64)

**Bug 描述**
excel数据集中的数据改变后，用该数据集制作的视图并没改变

**Bug 重现步骤(有截图更好)**
1.用这个数据集制作了一个视图
数据集如下：
![image](https://user-images.githubusercontent.com/45278450/144376321-acb0e3a1-aff6-47d0-b296-00e6dca835fe.png)
用该数据集做出的视图如下：
![image](https://user-images.githubusercontent.com/45278450/144376416-df5a05c0-8eab-4f1f-830b-e24d8c28d13b.png)

2.
把这个数据集中的年度字段类型从数值改成时间类型后，年度字段的值改变了
数据集如下：
![image](https://user-images.githubusercontent.com/45278450/144376645-adb40285-d8b9-432d-a518-32f49620e9c6.png)
视图中的年度字段值没变，如下
![image](https://user-images.githubusercontent.com/45278450/144376830-56e2f336-4dc1-4a1b-b1ab-22986dcbb1ed.png)

3.

**Comment by BBchicken-9527** [comment]
感谢你的发现：
1.我们正在处理，非常感谢
2.因为现在时间格式只支持固定的格式，目前不支持单独的年、月或日的情况。

**Comment by BBchicken-9527** [comment]
已解决：将int类型修改为时间类型视图与仪表板显示不同问题
