### ISSUE TITLE
[Feature]让用户自定义主题

### ISSUE THREAD

**Issue by armored-glitch** [dataease/dataease#13764]
DataEase 版本:

v2.10..2
**请描述您的需求或者改进建议.**
尊敬的DataEase团队：
       目前管理者可以设置仪表板风格，后续会考虑分享给用户，让用户自定义查看的风格吗
（就是用户可以自己选择查看的风格是深色主题或者其他自定义主题）
![image](https://github.com/user-attachments/assets/4cffae7a-3b6d-4589-ab10-66a22966167d)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划在预览模式下，支持自定义风格。
