### ISSUE TITLE
[Bug]Could not resolve dependencies for project io.dataease:extensions-datasource:jar:2.10.3: Could not find artifact io.dataease:dataease-license-sdk:jar:2.10.3 in fit2cloud-public (https://repository.fit2cloud.com/repository/fit2cloud-public/) -> [Help 1]

### ISSUE THREAD

**Issue by whenjs** [dataease/dataease#13803]
**DataEase 版本**
2.10.3

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome 130

**Bug 描述**
进入项目根目录执行mvn clean install报错，dataease-license-sdk:jar:2.10.3包找不到
Could not resolve dependencies for project io.dataease:extensions-datasource:jar:2.10.3: Could not find artifact io.dataease:dataease-license-sdk:jar:2.10.3 in fit2cloud-public (https://repository.fit2cloud.com/repository/fit2cloud-public/) -> [Help 1]

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
请使用已发布分支的代码，如 v2.10 分支。

**Comment by kevinzrs123** [comment]
今天更新了2.10.3 install失败，显示 Could not resolve dependencies for project io.dataease:extensions-datasource:jar:2.10.3

是不是新的license包还没发布
