### ISSUE TITLE
[Feature]权限配置某个文件夹下只勾选了一个子节点默认勾选上级节点

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#13811]
DataEase 版本:
v2.10.2

**请描述您的需求或者改进建议.**
在权限配置的地方，如果某个文件夹下只勾选了一个子节点，是不是可以默认的把它的上级节点也给勾选上，不然在用户登录的时候只会看到只有一个仪表板，没有目录层级，如果主动勾选上级节点，会默认勾选此上级节点的所有内容，需要再次反选，不够灵活。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前保持现状，暂时没有计划调整。
