### ISSUE TITLE
[Feature] sql 预览时间超时&requestTimeOut参数全局不适用

### ISSUE THREAD

**Issue by boolean-dev** [dataease/dataease#1381]
**请描述您的需求或者改进建议.**
### 问题描述
我创建数据集和修改数据集的时候，因为 SQL 执行时间较长，超过了 20S，导致数据集无法预览和创建。

随后我查看源代码，发现有一个配置超时时间的配置接口：`/system/requestTimeOut` ，然后修改了 `system_parameter` 数据库表
![image](https://user-images.githubusercontent.com/20177406/144542616-18370ad2-6a4c-4d63-81af-112396fec723.png)

发现其它接口的超时时间都已经是 60S，但是预览 sql 的超时时间依旧是 20S

随后查看源码，发现 `/frontend/src/api/dataset/dataset.js` 这个文件的 `post` 方法设置了个默认的超时时间 20S，与全局的超时时间独立配置
![image](https://user-images.githubusercontent.com/20177406/144542841-fa6ab27b-e88f-46a0-8aa1-35ac5e96de44.png)

### 相关建议

建议前端的所有接口统一使用 `system_parameter` 中的超时时间，否则错误排查起来过于麻烦

**Comment by yayanpei** [comment]
感谢您的反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 版本已调整，请等待新版本发布。
