### ISSUE TITLE
[Bug]StaticResourceConstants类中Windows目录分隔符兼容性问题

### ISSUE THREAD

**Issue by FDship** [dataease/dataease#13812]
**DataEase 版本**
2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**

**Bug 描述**
    
    public static final String FILE_SEPARATOR = File.separator;
    public static final String USER_HOME = "/opt/dataease2.0/data".replaceAll("/",FILE_SEPARATOR);

   replaceAll是按照正则表达式进行匹配，windows的分隔符是'\\'  ,替换应为 '\\\\\\\\'

    public static final String USER_HOME = "/opt/dataease2.0/data".replaceAll("/","\\\\");

**Bug 重现步骤(有截图更好)**
1.启动报错
2.
3.

**Comment by FDship** [comment]
replaceAll是按照正则表达式进行匹配，windows的分隔符是"\" ,替换应为 "\\"

**Comment by BBchicken-9527** [comment]
感谢反馈，目前最新版本已经对你的问题进行了处理，可以下载最新版本进行体验；
