### ISSUE TITLE
[Bug]替换Excel数据源，仪表板中时间选择框选择月份后显示“无法正常显示”

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#1382]
**DataEase 版本**
1.5

**浏览器版本**
Chrome

**Bug 描述**

Excel数据做好仪表板后，更新Excel数据，替换Excel数据源，仪表板中图形正常，但时间选择框选择月份后显示“无法正常显示...” 
这时需要重新在时间选择框中删除已有的维度，重新添加一下维度就恢复正常了。
![image](https://user-images.githubusercontent.com/48307752/144560487-2e7159fd-82a1-465f-8de8-84a5cbebc575.png)

![image](https://user-images.githubusercontent.com/48307752/144560460-372a8857-8113-42bb-8af2-044b6d69bb64.png)

**Comment by BBchicken-9527** [comment]
该问题已确认，我们尽快修复。

**Comment by BBchicken-9527** [comment]
因为excel的特殊性，您替换相当于换了库，所以组件无法匹配上导致问题，若是更新数据应当使用最佳的方式

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 已支持，请等待新版本发布
