### ISSUE TITLE
[Bug]堆叠柱状图，含查询组件，设置堆叠项颜色时，切到不同查询项，设置会被重置

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#13852]
**DataEase 版本**
v2.10.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
堆叠柱状图，含查询组件，设置堆叠项颜色时，切到不同查询项，设置会被重置

现在是会往前推颜色只能把堆叠项的数据补全，没有的都补 0 ，通过补0，来凑排序  不是长久办法

**Bug 重现步骤(有截图更好)**
1.新建
![image](https://github.com/user-attachments/assets/3aa6286d-3a45-4862-a79c-d124279a1863)

2.查询组件筛选其他条件
![image](https://github.com/user-attachments/assets/8b0a8074-936f-46ec-8cb8-16a900512988)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前没有支持自定义默认颜色的打算；
