### ISSUE TITLE
[Bug]v2.10.3 如果旧版本更换过系统字体，新版升级后，仪表板的所有字体都会显示改变，需要重新加载刷新一下，才会恢复正常字体

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#13863]
不正常的样子：
![image](https://github.com/user-attachments/assets/b610fc09-48f2-4a64-b6fc-213a5f0fce68)
正常样子：
![image](https://github.com/user-attachments/assets/e703d237-a496-41ad-9ca3-49c36563a772)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题；
