### ISSUE TITLE
[Question]翻页模式表格翻到后面页后跳转设置会失效

### ISSUE THREAD

**Issue by xix1** [dataease/dataease#13861]
**请描述您的问题.**
版本：v1.15.0
给明细表格设置翻页模式后，第一页的跳转设置是成功的，后面页的跳转会失效，点击跳转字段会提示：未获取跳转信息
这种情况要怎么设置呢？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，旧版本可能有这个bug，建议升级至较新的版本。
