### ISSUE TITLE
[Bug] macbook pro chrome浏览器加载报错

### ISSUE THREAD

**Issue by FantasyNeurotic** [dataease/dataease#13885]
**DataEase 版本**
2.10.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 已是最新版本
版本 131.0.6778.109（正式版本） (x86_64)

**Bug 描述**
<img width="633" alt="image" src="https://github.com/user-attachments/assets/52f4d9b4-f0aa-42e9-9fed-3fb0ed78d8e6">

**Bug 重现步骤(有截图更好)**
1. 升级2.10.3，直接访问8100端口
2. mac book chrome报错，其他浏览器没这些问题
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，请问是否升级后刷新浏览器或清除缓存呢？

**Comment by zltck** [comment]
![image](https://github.com/user-attachments/assets/f7677643-82b8-474c-86fe-170caf5d55e9)
的确有这个问题，最新版的chrome，win11，你们自己的demo网站

**Comment by FantasyNeurotic** [comment]
已经更新
