### ISSUE TITLE
[Feature]数据集边框自动恢复

### ISSUE THREAD

**Issue by songrui88** [dataease/dataease#1390]
V1.4版本：
数据集下拉菜单中，excel表格名称长，拉宽边框将表格名称显示完全，再点到其他表格后，边框又恢复原样，名称又重新显示不全。
![image](https://user-images.githubusercontent.com/46080992/144697821-5968f857-6557-42cc-83fd-d4b9fb0a1973.png)

**Comment by yayanpei** [comment]
感谢反馈，我们安排优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.9.0 版本已修复，请下载最新版本。
