### ISSUE TITLE
[Bug]excel表头有阴影格式，导入就为空

### ISSUE THREAD

**Issue by songrui88** [dataease/dataease#1391]
**DataEase V1.4**
**Bug 描述**
数据集导入excel表格，表头只要有阴影格式的，导入后预览就为空。
![image](https://user-images.githubusercontent.com/46080992/144697901-658b89ed-15bb-4bda-9989-6c9de677db30.png)
![image](https://user-images.githubusercontent.com/46080992/144697911-1d6f6282-82bc-43d3-a6bc-5b07f1e59332.png)

**Comment by BBchicken-9527** [comment]
目前最新版本没有发现此类问题，可以升级一下看看；
