### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by africaadonis** [dataease/dataease#1392]
**请描述您的需求或者改进建议.**
1、表格组件可以设置联动，但是不支持点击
2、是否可以通过多个“过滤组件”对表格数据进行过滤？
3、在A仪表板中柱状图组件上增加了跳转设置，跳转至B仪表板，同时设置了联动视图，B仪表板中增加了一个组件“其他-文字”，设置了A仪表板的公共链接（在仪表板【创建公共链接】中生成的），用于点击后返回至A，A跳转至B之后，B中的表格数据能被过滤，再次点击A跳转至B，B中的表格数据就不能被过滤了
![image](https://user-images.githubusercontent.com/40649464/144741193-4c58c668-8c75-4427-b2bc-7a9898ded2e7.png)

![image](https://user-images.githubusercontent.com/40649464/144741206-1429ec9d-9322-4772-88a1-05285ac4c989.png)

4、地图组件中区划是否能到乡镇一级？

**Comment by xuwei-fit2cloud** [comment]
1. 表格组件当前确实还不支持点击事件，所以表格目前还不能支持跳转、钻取等操作
2. 可以添加多个过滤组件对同一个表格数据进行筛选
3. 确实存在这个问题，我们处理一下
4. 目前还不支持乡镇一级的区划

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 已对2和3做了处理，1和4在近期版本还不会支持。
