### ISSUE TITLE
[Bug]使用默认密码登录时，弹出的强制修改初始密码框可以通过删除html元素绕过

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#13968]
**DataEase 版本**
1.18.25

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 131.0.6778.139

**Bug 描述**
可绕过系统的强制修改密码来做到不修改密码而使用系统功能

**Bug 重现步骤(有截图更好)**
1.使用默认密码登陆后弹出强制修改默认密码弹窗
2.删除以下html元素来绕过
![image](https://github.com/user-attachments/assets/565b833d-c651-44e1-b264-f32e48fd2142)

**Comment by BBchicken-9527** [comment]
感谢反馈，个人认为这种方式不算是bug，目前没有考虑对此处进行修改；
