### ISSUE TITLE
[Bug]2.10.3 使用网页链接组件时，仪表板导出为PDF，在PDF中网页组件链接是空白

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#13977]
![image](https://github.com/user-attachments/assets/e6ecfb93-db11-485a-a22d-436fd8373c66)
![image](https://github.com/user-attachments/assets/8cd7d7d6-15c4-4ccf-b2f2-005868f49f58)
![image](https://github.com/user-attachments/assets/3e154562-5252-4d23-a66a-f6ec8c0552eb)

**Comment by BBchicken-9527** [comment]
感谢反馈，由于组件原因限制目前暂时无法处理；
