### ISSUE TITLE
[Bug]导出的 PDF 内容不全

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1398]
**DataEase 版本**
1.5.0

**浏览器版本**
Chrome 96

**Bug 描述**
导出的 PDF 只有左半边的内容，右半边像是被截掉了。

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/48945409/144806739-c79d8430-f962-461a-b2ea-9c61956e0eeb.png)

2.
![image](https://user-images.githubusercontent.com/48945409/144806823-a850fde8-1126-446d-8c73-6d610a39a49e.png)

3.同时清晰度也比较差

**Comment by BBchicken-9527** [comment]
感谢你的发现，我们已经修复了这个问题，将会在下个小版本中修正

**Comment by xuwei-fit2cloud** [comment]
v1.5.1 版本已修复
