### ISSUE TITLE
[Feature]导入 Excel 数据后呈现最终导入的详细结果描述

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1399]
**请描述您的需求或者改进建议.**
目前 DE 导入 Excel 对于完全相同的数据是会过滤掉的，比如导入 100 条数据，有几条是重复的，最终只有 95 条。但用户导入完数据后导入的数量与之前文件中的数量不符并不清楚原因。建议基于类似情况在导入后有详细信息供用户查看，譬如，本次共导入 XX 条数据，XX 条数据导入完成，XX 数据由于什么原因未导入。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们会做一下优化。

**Comment by ainilili** [comment]
有没有办法不去重，或者产品层面允许用户选择是否去重？
