### ISSUE TITLE
Execl一些特殊不支持

### ISSUE THREAD

**Issue by plateauandsp** [dataease/dataease#14]
资产导入与预览
![image](https://user-images.githubusercontent.com/30932762/123387335-41dc5180-d5ca-11eb-9bfc-3aa3bb95abc0.png)
![image](https://user-images.githubusercontent.com/30932762/123370725-e18de580-d5b2-11eb-895f-560f17b0a82b.png)
重新打开后报错
![image](https://user-images.githubusercontent.com/30932762/123370737-e94d8a00-d5b2-11eb-8e1c-6ab34af730ce.png)

**Comment by xuwei-fit2cloud** [comment]
表格组件需要重构，对上述格式近期内还不能支持。
