### ISSUE TITLE
[Bug]数据集 order by无效

### ISSUE THREAD

**Issue by LiaoMinYu** [dataease/dataease#14005]
**DataEase 版本**
2.10.3

**运行方式(安装包运行 or 源码运行 ?)**

安装包运行
**浏览器版本**

**Bug 描述**
相同的sql 在数据集中使用order by 没有生效，数据源 doris

**Bug 重现步骤(有截图更好)**
<img width="948" alt="图片" src="https://github.com/user-attachments/assets/9fabd095-d22a-4705-a31f-fa031bc90d81" />

1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，这是考虑到可能你查询的表数据量庞大，导致等待时间较长，所以通过分页的方式限制了你的查询数量，当doris通过外层仅从limit分页后显示的数据就变成了无序的状态；
