### ISSUE TITLE
[Feature]计算字段为聚合函数时，支持设置辅助线的动态值

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#14009]
DataEase 版本:
v2.10.3

**请描述您的需求或者改进建议.**
当新建计算字段使用聚合函数计算之后，在辅助线的动态值无法选到此字段，建议支持设置、

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们内部讨论后再进行回复。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，数据集的计算字段如果已经使用聚合函数，那么是不支持对聚合字段进行二次聚合的，因此目前暂无计划支持该需求。
