### ISSUE TITLE
[Bug]复用模板中的图表时报错，期望给出友好提示或显示模板数据

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#14014]
**DataEase 版本**
 v2.10.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新

**Bug 重现步骤(有截图更好)**
1. 使用模板创建一个大屏不做任何操作，直接保存
![image](https://github.com/user-attachments/assets/b6276336-23ea-4c46-8bb4-c89bf33b386f)
2. 新建一个空白大屏复用第一步创建的大屏中的图表
![image](https://github.com/user-attachments/assets/63f1df49-b460-4356-b138-6f5e1fa38cd0)
3. 报错如下
![image](https://github.com/user-attachments/assets/5dadd2f6-ae89-4fb7-a836-70afb52cc340)
4. 点击查看详细信息 
![image](https://github.com/user-attachments/assets/81465d51-f603-4691-b6c3-9a17313552ba)

**Comment by BBchicken-9527** [comment]
感谢反馈，因为没有添加数据集导致服用提示异常，这个是符合预期的，因为你是复用的原因，所以无法显示查看数据的；
