### ISSUE TITLE
[Bug] Excel 数据集做数据替换后，筛选、下钻等功能失效

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1402]
**DataEase 版本**
V1.5.0

**浏览器版本**
Chrome 96

**Bug 描述**
Excel 数据集替换后，原来仪表板上的筛选值没有了，下钻也会出错。

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/48945409/144855936-0358dccd-6258-49f6-9ef9-6e06faee075b.png)

2.字段无变化，主要为了做数据更新。
3.该数据集的一些相关功能失效。
例如原来有值的筛选框：
![image](https://user-images.githubusercontent.com/48945409/144856099-acc8454e-32a0-4626-89ca-d0f71701c368.png)
例如下钻后出错：
![image](https://user-images.githubusercontent.com/48945409/144856631-ad7991ce-4258-4b51-9494-08defb4accd4.png)

**Comment by BBchicken-9527** [comment]
感谢你的发现，我们会尽快处理的

**Comment by luyang351** [comment]
如果之前的数据有变动使用追加会变成新增一条数据，而之前的历史数据也不能删除。目前的情况是需要对数据做一些日常更新操作，追加无法满足。

**Comment by xuwei-fit2cloud** [comment]
我们近期版本处理一下。
