### ISSUE TITLE
[Bug]源码编译不通过

### ISSUE THREAD

**Issue by chenlinks** [dataease/dataease#14024]
**DataEase 版本**
2.10.3

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**

**Bug 描述**
1.CalciteProvider  中 CalciteConnectionProperty.LEX.camelName()   无法访问
2.TableUtils 中 import org.apache.calcite.avatica.util.Quoting  引用不存在
3.org.json.simple.JSONObject 包不存在

**Bug 重现步骤(有截图更好)**

**Comment by chenlinks** [comment]
补充一点，缺少 calcite-linq4j  依赖

**Comment by ziyujiahao** [comment]
这些是公网上的依赖包 可能是编译下载中断导致 解决方法是 在自己的Maven库中找到对应的包的目录，删除一下上层文件夹 重新下载一遍
