### ISSUE TITLE
[Feature]请添加选项卡设置背景色的功能

### ISSUE THREAD

**Issue by liulongleo** [dataease/dataease#1403]
**请添加选项卡设置背景色的功能**
像下图所示，当选项卡的颜色与仪表板的背景颜色色差较大时，显示效果实在感人，请添加支持的功能，thx
![image](https://user-images.githubusercontent.com/18008062/144870360-17ccb29d-1ffa-4d63-a9aa-415fc85c3ded.png)

**Comment by xuwei-fit2cloud** [comment]
我们近期版本会做一下相关优化处理

**Comment by xuwei-fit2cloud** [comment]
可以修改透明度，让背景色和仪表板背景色一致
