### ISSUE TITLE
[Feature]执行记录数据量过大时等待时间较长

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1404]
**请描述您的需求或者改进建议.**
目前该页面的数据量平均需要等待 4-5 秒左右，是否可进一步优化。
![image](https://user-images.githubusercontent.com/48945409/144959270-994e7d40-cfc8-4e72-9399-fc70bc8eba43.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 已修复，请等待新版本发布
