### ISSUE TITLE
多个数据大屏轮播需求

### ISSUE THREAD

**Issue by DAGMAC786** [dataease/dataease#14059]
DataEase 版本:
2.9

**请描述您的需求或者改进建议.**
假如有三个数据大屏，三个数据大屏对外展示的话 是有三个URL哈
现在想  让他们三个URL能够定时10秒 或者20秒 在一个URL里面 来回切换大屏

**Comment by DAGMAC786** [comment]
<img width="931" alt="9ae6f71d6ae3eaa9c9ad861f8276649" src="https://github.com/user-attachments/assets/8827ac97-7723-4432-9e80-fda60d1b765c" />

可以点这两个箭头换一页吗，或者15秒自动换一页

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议百度一下，可以用谷歌浏览器的插件实现几个url的轮播。
