### ISSUE TITLE
[Feature] 预览页面能否添加控制加载中的转圈圈特效的显示和隐藏

### ISSUE THREAD

**Issue by daiqingyao6238** [dataease/dataease#14063]
DataEase 版本:

2.10.3
**请描述您的需求或者改进建议.**
<img width="1901" alt="2620440f17b8c7a0c96f2d8466b57f2" src="https://github.com/user-attachments/assets/b9e33336-4867-4f1f-a935-b28ac1b7e65f" />

**Comment by xuwei-fit2cloud** [comment]
因为数据加载是每个组件独立的动作，目前还没有计划增加控制项来控制加载动画的显示与隐藏。
