### ISSUE TITLE
[Bug] 报表明细没有按时间降序显示

### ISSUE THREAD

**Issue by tinyxia** [dataease/dataease#14066]
**DataEase 版本 2.10.2**

我使用自定义sql语句制定的数据集，使用了order by create_time desc; 但是明细报表却没有按创建时间降序进行排列，如图：
![1212](https://github.com/user-attachments/assets/89edcf35-927f-47c9-ab64-721755ddf3a5)
![3333](https://github.com/user-attachments/assets/bdd67903-416d-45f9-8e7a-1975c3e03652)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前图表数据是抽取的，在数据集中能否按照排序显示也需要看你使用的数据源是否支持在limit之后依然按照你的排序显示，若你图表需要进行排序，需要在前台对字段设置排序即可；
![image](https://github.com/user-attachments/assets/939868f9-de89-4ebf-b51f-90a5b2f40d31)
