### ISSUE TITLE
[Feature] 支持 JDBC 驱动接入

### ISSUE THREAD

**Issue by yinbo3** [dataease/dataease#14076]
DataEase 版本:

**请描述您的需求或者改进建议.**
建议可支持自定义 JDBC 驱动，以快速接入更多的的数据源。

**Comment by xuwei-fit2cloud** [comment]
DataEase对数据处理有附加自己的一层逻辑在内，目前对JDBC方式连接数据源是通过分别的数据源插件来实现的，还无法做统一支持。
