### ISSUE TITLE
[Bug]API数据源无法传参

### ISSUE THREAD

**Issue by daviadong** [dataease/dataease#14075]
**DataEase 版本**
V2.10.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome 131.0.6778.140

**Bug 描述**
API数据源无法传参

**Bug 重现步骤(有截图更好)**
1.使用API动态参数，请求体中只能form-data和x-www-form-urlencoded格式可以传参，raw和json都不行
![21734338955_ pic](https://github.com/user-attachments/assets/6f62d53a-cb08-468c-ad74-adb1368e952c)

![61734338958_ pic](https://github.com/user-attachments/assets/f99b5e2d-c5aa-41ee-afb0-0da5862eaa60)
json和raw格式都会失败
![51734338957_ pic](https://github.com/user-attachments/assets/281bbea3-e326-4394-8f90-b3f372a8cca5)
写固定值就可以成功
![71734339462_ pic](https://github.com/user-attachments/assets/b741c976-efa6-44d9-8eea-b82b1b1e38d1)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前暂时不支持在请求体中进行参数的书写;
