### ISSUE TITLE
[Feature] 数据大屏图层栏允许伸缩，在较短的情况下，名称显示不全

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#14112]
DataEase 版本:

**请描述您的需求或者改进建议.**
数据大屏图层栏允许伸缩，在较短的情况下，名称显示不全
<img width="245" alt="image" src="https://github.com/user-attachments/assets/5ec8a8ce-e9a2-4270-8d44-b56f199b8ecb" />

**Comment by xuwei-fit2cloud** [comment]
鼠标停留，会显示完整名称。
![图片](https://github.com/user-attachments/assets/d368d42d-93ec-40c8-802d-9a8a78b46b6d)
