### ISSUE TITLE
[Feature] 过滤组件允许设置代选项居中、左、右

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#14115]
DataEase 版本:
2.10.3

**请描述您的需求或者改进建议.**
过滤组件允许设置代选项居中、左、右
<img width="643" alt="image" src="https://github.com/user-attachments/assets/adec0c87-6522-4ff1-9d63-56d6499832e9" />

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持。
