### ISSUE TITLE
[Bug] 复制的数据集进行切换数据源，发现无法保存，保存了也无法更新

### ISSUE THREAD

**Issue by daiqingyao6238** [dataease/dataease#14118]
**DataEase 版本**
2.10.3

**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**
最新版

**Bug 描述**

复制的数据集进行切换数据源，发现无法保存，保存了也无法更新
**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/user-attachments/assets/4c0f9d46-ecf3-4fdc-8530-4679c5e89833)

2.

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，因为de支持跨源，所以在你更换数据源的时候自定义sql是会跟着一起切换数据源的，自定义sql使用的数据源为：编辑自定义sql时抽屉左侧的数据源；
