### ISSUE TITLE
[Feature]数据集也可以成为一个数据源，和其他表做关联

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#14126]
DataEase 版本:
v2.10.3

**请描述您的需求或者改进建议.**
数据集也可以成为一个数据源，和其他表做关联

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，近期暂时没有计划支持该功能。

**Comment by xuhaiping** [comment]
数据集之间能支持关联查询就好了，查询语法可以沿用sql的。
