### ISSUE TITLE
[Feature]v2 地图下面的群岛区域能不能单独截取出来放在右下角展示，整体看看不清

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#14129]
![e23a8f895f1957ddfd77d880f592add](https://github.com/user-attachments/assets/e4d11807-2cd8-4752-b7d1-5d5ffd390192)
 类似纸质地图的这样

![image](https://github.com/user-attachments/assets/366944cd-5dda-4cd5-a2d5-09347fcc3913)
希望这部分也能放在右下角放大显示

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，地图采用的是新版的竖版地图（南海诸岛与大陆连在一起，在图上可以清楚地看到南海诸岛内的主要岛屿、岛礁，以及与周边岛国、岛屿、岛礁的地理位置关系）。目前暂时没有计划更换为横版地图。
