### ISSUE TITLE
[Question]【仪表板】通过公共链接使用仪表板跳转功能显示图形不正确

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#1412]
**请描述您的问题.**
仪表板中自己使用跳转显示正常图形，别人通过公共链接打开仪表板，点击指定位置跳转需要登录，登录之后（任何有权限的用户）跳转的显示的视图没有变化；如下图：
通过自己账号登录DE操作：
![image](https://user-images.githubusercontent.com/48307752/145179538-a686fdb4-63d8-4b77-8eb0-cd4c875ee759.png)
通过公共链接登录DE分享的仪表板操作：
![image](https://user-images.githubusercontent.com/48307752/145179864-f76f2b66-6595-41f1-940b-55889096761a.png)

此现象属于设定内的现象还是bug?

**Comment by yayanpei** [comment]
感谢反馈，该场景下参数没有传，我们后面安排优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 版本已修复，请等待新版本发布
