### ISSUE TITLE
[Feature]条形图向下滚动

### ISSUE THREAD

**Issue by LuHan20** [dataease/dataease#14128]
DataEase 版本:
2.10.2

**请描述您的需求或者改进建议.**
问题：行列较多的时候，条形图数据堆叠在一起看不清。拉动缩略图放大只能显示前一二十列，看不见后面的；缩小都堆在一起。
需求：条形图可以向下滚动，通过滚动查看所有数据；可以自定义内容居中靠左或者靠右；可以自定义上下左右边距，下边距太大了，空着没用还占位置。
BUG：不显示图例或者图例位置居下时，首行文字只显示一半
![1734487905734](https://github.com/user-attachments/assets/78789809-d3e6-4490-9b89-9c1ab7b86dce)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，当分类较多时，条形都堆积在一起，效果不好，建议使用表格。
