### ISSUE TITLE
[Feature]分组堆叠柱状图标签显示总计

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#14127]
DataEase 版本:
2.10.3

**请描述您的需求或者改进建议.**
类似于这里 的
![2045bae9-b9e5-415a-8e7f-f76c8893f034](https://github.com/user-attachments/assets/524ab0b6-885b-4917-8972-1cf669914659)

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #13815
