### ISSUE TITLE
[Feature] 下拉按钮允许隐藏

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#14137]
DataEase 版本:
2.10.3

**请描述您的需求或者改进建议.**
下拉按钮允许隐藏

<img width="602" alt="image" src="https://github.com/user-attachments/assets/0f1125c4-6314-4a51-8a50-ddbd1e18980b" />

**Comment by xuwei-fit2cloud** [comment]
这个是用来标识查询组件的类别的，目前没有支持的计划。
