### ISSUE TITLE
[Feature]地图组件，指标能添加多个

### ISSUE THREAD

**Issue by 588liujuncao** [dataease/dataease#14142]
DataEase 版本:2.10.3

**请描述您的需求或者改进建议.**

地图组件，指标能添加多个
例子：
<img width="101" alt="eeaf32ad07c9b98577fa814bd423af6" src="https://github.com/user-attachments/assets/8685e9a4-28b6-467a-a3ad-7b35f19105fd" />
<img width="213" alt="6a57eb85a0873dfe7d3a2341bfe1aa1" src="https://github.com/user-attachments/assets/0604e6d6-f49c-4f34-a8f6-4370c31732f6" />

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，此处的指标用于地图区块颜色的渲染，若需要在提示中展示其他指标，建议在提示中选择其他指标，如下图所示。
![image](https://github.com/user-attachments/assets/be4e1362-3ddd-4218-824a-f50b4a4120ca)
