### ISSUE TITLE
[Bug]v2.10.3 数据集批量转化为指标（或者维度之后），再进行批量操作时，数值转换不显示

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#14144]
1.批量转为指标
![image](https://github.com/user-attachments/assets/09f49f40-d06b-494f-b520-5243aa22fe95)

2.再次批量操作的时候，shu'ju'w数据未刷新过来，操作显示栏数值选项消失
![image](https://github.com/user-attachments/assets/0214c680-bbb5-4a27-bdd6-047063b347d7)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境查看历史数据是有一些问题，我们会在后续两个版本内进行修复；
