### ISSUE TITLE
[Bug]网页组件配置公共链接，无密码提示需要密码

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#14167]
**DataEase 版本**
2.10.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
网页组件配置公共链接，无密码提示需要密码

**Bug 重现步骤(有截图更好)**
1.有一个公共链接无密码
2.一个网页组件，链接写公共链接
3.配置后
![企业微信截图_17345791652586](https://github.com/user-attachments/assets/12f622aa-1e9a-4162-9027-9b69f3338a1a)

**Comment by zhainanshidai** [comment]
发现企业版（学习班环境测试和本地测试）有的环境可以正常，社区版的似乎有这个问题

**Comment by BBchicken-9527** [comment]
感谢反馈，看提示像是系统设置中开启了相关配置项，建议查看一下配置项是否开启；
