### ISSUE TITLE
[Feature]表格的行高可以自适应

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#14176]
DataEase 版本:
2.10.3

希望行高可以自适应，有些数据会有多行（非自动换行），多行与单行 的行高可以自适应为合适的行高。

<img width="691" alt="图片" src="https://github.com/user-attachments/assets/3c48a51e-a777-405e-8ee2-71a686efffdc" />

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先调研下图库是否支持。

**Comment by xuwei-fit2cloud** [comment]
这个需求之前讨论过，实现起来比较复杂，暂时还无法支持。
