### ISSUE TITLE
[Feature]【数据填报】组件增加”不允许填入空格“校验，不允许在组件中输入空格

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#14180]
DataEase 版本:
v2.10.3

**请描述您的需求或者改进建议.**
组件增加”不允许填入空格“校验，不允许在组件中输入空格：比如从网页上复制的数据，整理到excel，没有注意到空格问题，比如张三，“张 三”，会影响数据质量；上传的时候 提示一下，有空格，修改了之后再上传
![image](https://github.com/user-attachments/assets/88bf16db-90f9-4102-8a56-17f7b1420f0c)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
暂时不考虑支持。
