### ISSUE TITLE
[Bug]pgsql数据源处查看数据表，发现查询结果为空

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#14198]
**DataEase 版本**
v2.10.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
pgsql数据源处查看数据表，发现结果为空，没有表显示

**Comment by BBchicken-9527** [comment]
感谢反馈，目前暂时不支持hologres源的链接；
