### ISSUE TITLE
[Bug] MacOS Intel芯片下，按照安装手册一步一步操作，下载的DataEase桌面版仍无法打开

### ISSUE THREAD

**Issue by kyzhangs** [dataease/dataease#14204]
**DataEase 版本**
版本：`DataEase桌面版`
系统：MacOS 15.2（Intel芯片）

**Bug 描述**
按照安装手册一步一步操作，下载的`DataEase`桌面版仍无法打开

**Bug 重现步骤(有截图更好)**
1.下载`DataEase`桌面版，解压后双击发现无法打开
<img width="296" alt="image" src="https://github.com/user-attachments/assets/676edb6d-ff10-4a18-a783-5a86e2a398b0" />
2.按照安装手册操作，并开启允许任何来源
3.执行`xattr -cr xxx`,然后再双击应用，仍无法打开
<img width="1475" alt="image" src="https://github.com/user-attachments/assets/13e765c6-3eba-4487-a7b7-04f2d6cb7148" />

**如需远程可以联系我**

**Comment by xuwei-fit2cloud** [comment]
很抱歉，目前能支持的平台有：

- Windows(x86)
- Linux(x86)
- MacOS(arm64)

Intel芯片的MacOS目前还不支持。

**Comment by kyzhangs** [comment]
请问未来是否有相关的支持计划呢

**Comment by xuwei-fit2cloud** [comment]
目前桌面版的构建是完全基于Github Action的，官方提供的三个构建平台就是当前支持的三个平台。
我们后续会考虑通过self-hosted runners的方式加入对其他平台的支持，还请等待。

**Comment by zhangliwen** [comment]
MacOS Intel芯片下，按照安装手册一步一步操作，下载的DataEase桌面版仍无法打开，一直卡在截图这个位置，cpu 与 内存并未达到瓶颈。
我看这个 Issue 已经 Closed 了，已经能支持 Intel 了吗？

**DataEase 版本**
版本：DataEase桌面版，dataease_2.10.3_mac_amd64
系统：MacOS 13.4（Intel芯片）

**Bug 描述**
按照安装手册一步一步操作，下载的DataEase桌面版仍无法打开

**Bug 重现步骤(有截图更好)**
<img width="955" alt="image" src="https://github.com/user-attachments/assets/9e1c122e-6b13-4004-af83-9e028eef6dbc" />

@kyzhangs @xuwei-fit2cloud
