### ISSUE TITLE
[Feature]建议优化导出 PDF 的清晰度

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1420]
**请描述您的需求或者改进建议.**
导出 PDF 的清晰度对比 Web 版会差很多，尤其是一些文字看起来比较明显，不利于以该文档传播或汇报。
![image](https://user-images.githubusercontent.com/48945409/145364777-0be16361-9b48-47fc-bb7b-2fae72725f66.png)
![image](https://user-images.githubusercontent.com/48945409/145364955-2b878869-43d6-42b4-a284-7a17eac586d3.png)

**Comment by yayanpei** [comment]
感谢反馈，我们安排优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 版本会做优化。
