### ISSUE TITLE
[Feature]数据集支持更换连接，不影响源报表的使用

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#14210]
DataEase 版本:
v2.10.3

**请描述您的需求或者改进建议.**
数据集支持更换连接，不影响源报表的使用
现在一旦数据源失效、地址有变更，会导致从数据源-数据集到图表的影响，能不能支持更换连接，当结构啥的相同的时候能支持更换（类似模板应用那样对接上新数据源）

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持。
