### ISSUE TITLE
[Feature]sql传参希望支持表名传参。

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#14221]
场景：如果业务每天的数据都生成一张新表，命名为xxxxxx_ggggg_当天日期，现在需要每天查当天的表，sql中的传参只能用在where后，这样就得每天手动创建数据集，很不方便。

**Comment by xuwei-fit2cloud** [comment]
由于表的变化可能会导致表的结构变化，我们无法保证原有字段的可用性，所以目前还无法支持。
