### ISSUE TITLE
希望增加数据大屏/仪表盘里的查询组件与API接口的动态参数进行关联

### ISSUE THREAD

**Issue by kusen-alpha** [dataease/dataease#14256]
DataEase 版本: 

在仪表盘/大屏查询组件进行选择时，能直接对API进行实时获取数据，该功能极大提高了查询组件对接API接口数据的便捷切换

**Comment by kusen-alpha** [comment]
可以增加API数据集，逻辑和API数据源类似

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，api接口没有数据库的数据计算能力，因此需要定时将api的数据抽取至数据库中，用于数据的聚合计算等。

**Comment by kusen-alpha** [comment]
> 感谢您的反馈，api接口没有数据库的数据计算能力，因此需要定时将api的数据抽取至数据库中，用于数据的聚合计算等。

在以下情况：API已经将数据全部进行处理好了，只需要数据大屏对接实时显示的能力，不需要另外的计算啥的，这不是最基本的前端数据大屏功能吗
