### ISSUE TITLE
[Feature]希望增加数据大屏/仪表盘里的查询组件与API接口的动态参数进行关联

### ISSUE THREAD

**Issue by kusen-alpha** [dataease/dataease#14275]
DataEase 版本:

**请描述您的需求或者改进建议.**
参考另一个项目：https://ajreport.beliefteam.cn/report-doc/guide/dataset.html#http%E6%95%B0%E6%8D%AE%E9%9B%86

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈和建议，我们先调研一下。

**Comment by kusen-alpha** [comment]
> 感谢您的反馈和建议，我们先调研一下。

谢谢，我感觉这是最基本的数据大屏功能，毕竟绝大部分网站大屏都是直接对接后端从接口里获取数据用于直接显示，接口里都处理好了，不需要其他处理了

**Comment by kusen-alpha** [comment]
> 感谢您的反馈和建议，我们先调研一下。

根据定的频率实时访问后端API的数据进行实时显示，不需要额外对其数据进行加工

**Comment by kusen-alpha** [comment]
这里发表一下个人的逻辑：
针对API数据源进行功能增加
方案1：临时表方案，兼容sql查询
1、API数据源增加动态参数默认值选项，必须设置默认值，当前的API数据源表根据默认值进行获取数据，来支持当前业务逻辑。
2、对于有动态参数的API数据源，数据表增加一张动态数据表，用于存储查询组件设置动态参数值时的数据，该数据每行数据根据设置的访问频率记录过期时间，通过触发器等定期删除历史数据。

方案2：增加API数据集，该类情况直接访问API，抛弃sql等数据处理功能。

**Comment by kusen-alpha** [comment]
mysql有临时表概念，可根据API数据源里的数据表字段创建，每次请求完数据存入 用完自动删或者手动删

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，近期暂时没有计划支持。
