### ISSUE TITLE
[Feature] 希望桌面版支持链接分享访问

### ISSUE THREAD

**Issue by fcwys** [dataease/dataease#14274]
DataEase 版本:
dataease_2.10.3_win_amd64

**请描述您的需求或者改进建议.**
希望桌面版恢复链接分享访问，经过测试直接浏览器访问8100端口可正常访问，在桌面端复制大屏分享链接，作为局域网内大屏展示会比较方便（如临时或短期内性数据展示）。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，桌面版是单机的，暂时没有计划支持用户之间的共享。

**Comment by fcwys** [comment]
> 感谢您的反馈，桌面版是单机的，暂时没有计划支持用户之间的共享。

不是用户之间共享，只需要复制当前内网预览链接即可
