### ISSUE TITLE
[Feature] 过滤组件默认值动态时间配置，支持更多选项

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#14282]
DataEase 版本:
2.10.3

**请描述您的需求或者改进建议.**
过滤组件默认值动态时间配置，支持更多选项
![image](https://github.com/user-attachments/assets/48d0cd9c-31f3-4b49-9b28-590a464e7415)
支持周、季度的维度选择，支持使用页面的快速选择
![image](https://github.com/user-attachments/assets/61e1a711-cac8-4f34-8d46-f7142018c424)
<img width="797" alt="image" src="https://github.com/user-attachments/assets/15db66e0-4c2c-4271-a0a5-c3e9ca535939" />

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #14280
