### ISSUE TITLE
[Bug]前后端分离部署，访问仪表盘公共链接，跳转错误

### ISSUE THREAD

**Issue by caiiansheng** [dataease/dataease#1430]
**DataEase 版本**
1.5.1

**Bug 描述**
前后端分离部署，访问仪表盘公共链接，跳转错误（跳转到了后端服务器的ip 和端口）

**Bug 重现步骤(有截图更好)**
1.创建好公共链接，浏览器访问链接地址
![image](https://user-images.githubusercontent.com/26760483/145543454-31c96d9b-0923-4ea5-bb46-167909d058bf.png)

2. 访问链接地址，重定向到了后端服务器地址
![image](https://user-images.githubusercontent.com/26760483/145543651-a80da312-e5ec-4525-ad10-548d1e2e9f95.png)

**Comment by xuwei-fit2cloud** [comment]
可以参考文档：
https://dataease.io/docs/dev_manual/dev_deployment/#nginx_1

**Comment by liutianyuan** [comment]
> 可以参考文档： https://dataease.io/docs/dev_manual/dev_deployment/#nginx_1

Nginx参考这个配置了，跳转还是有问题。 我用的v1.8分支。
