### ISSUE TITLE
[Feature]【仪表板】通过外部传参作用到数据集外部参数，影响到筛选组件的值列表

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#14316]
DataEase 版本:
v2.10.3

**请描述您的需求或者改进建议.**
通过外部传参作用到数据集外部参数，影响到筛选组件的值列表，当前只能影响到视图。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持，建议通过配置查询条件的级联来影响筛选组件的选项值列表。
