### ISSUE TITLE
[Bug]大屏中打开图表的跳转开关报错 Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) 

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#14313]
**DataEase 版本**
2.10.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
大屏中打开图表的跳转开关立即弹出报错；
此问题只存在于 2.10.2 升级到 2.10.3 之后存在，新装 2.10.3 不存在。
报错截图如下：
<img width="1450" alt="图片" src="https://github.com/user-attachments/assets/dcbe2f07-d7b3-4846-aa66-390e2edec9a0" />
报错完整信息如下：
`Request processing failed: org.springframework.jdbc.UncategorizedSQLException: ### Error querying database. Cause: java.sql.SQLException: Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '=' ### The error may exist in class path resource [mybatis/ExtVisualizationLinkJumpMapper.xml] ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: SELECT core_dataset_table_field.id AS source_field_id, core_dataset_table_field.de_type AS source_de_type, core_dataset_table_field.NAME AS source_field_name, visualization_link_jump_info.id, visualization_link_jump_info.link_jump_id, visualization_link_jump_info.link_type, visualization_link_jump_info.jump_type, visualization_link_jump_info.window_size, visualization_link_jump_info.target_dv_id, visualization_link_jump_info.content, xpack_share.uuid AS publicJumpId, ifnull( visualization_link_jump_info.checked, 0 ) AS checked, ifnull( visualization_link_jump_info.attach_params, 0 ) AS attach_params, visualization_link_jump_target_view_info.target_id, visualization_link_jump_target_view_info.target_view_id, visualization_link_jump_target_view_info.target_field_id, visualization_link_jump_target_view_info.target_type, visualization_link_jump_target_view_info.source_field_active_id, visualization_outer_params_info.param_name as outer_params_name FROM core_chart_view LEFT JOIN core_dataset_table_field ON core_chart_view.table_id = core_dataset_table_field.dataset_group_id LEFT JOIN visualization_link_jump ON core_chart_view.id = visualization_link_jump.source_view_id AND visualization_link_jump.id = ? LEFT JOIN visualization_link_jump_info ON visualization_link_jump.id = visualization_link_jump_info.link_jump_id AND core_dataset_table_field.id = visualization_link_jump_info.source_field_id LEFT JOIN visualization_link_jump_target_view_info ON visualization_link_jump_info.id = visualization_link_jump_target_view_info.link_jump_info_id LEFT JOIN xpack_share ON xpack_share.creator = ? AND visualization_link_jump_info.target_dv_id = xpack_share.resource_id left join visualization_outer_params_info on visualization_outer_params_info.params_info_id = visualization_link_jump_target_view_info.target_view_id WHERE core_chart_view.id = ? AND core_chart_view.type != 'VQuery' ORDER BY CONVERT ( core_dataset_table_field.NAME USING gbk) ### Cause: java.sql.SQLException: Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '=' ; uncategorized SQLException; SQL state [HY000]; error code [1267]; Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='`

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
建议您检查一下对应的表，统一使用 utf8mb4_0900_ai_ci 编码。
