### ISSUE TITLE
[Feature] 趋势图等点数显示为啥只能展示100个点，不能提供配置来扩大显示么

### ISSUE THREAD

**Issue by FantasyNeurotic** [dataease/dataease#14315]
DataEase 版本:

2.10.3
**请描述您的需求或者改进建议.**

大屏趋势图，只能展示100个数据点，在以小时为单位的趋势显示在达到7天的范围情况下显示不全，需要提供趋势图点数的配置

**Comment by xuwei-fit2cloud** [comment]
不好意思，麻烦您截图说明一下？没看太明白你的意思。

**Comment by FantasyNeurotic** [comment]
> 不好意思，麻烦您截图说明一下？没看太明白你的意思。

就是折线图只能显示100个点的数据，超过100个点的情况下折线图显示的点不全
<img width="494" alt="image" src="https://github.com/user-attachments/assets/ee1d0b1a-4e89-4039-81f4-4cb74ada7337" />

**Comment by FantasyNeurotic** [comment]
一般情况下，我们需要监控起码是一周的趋势，也就是最少是7 * 24的点位，如果只支持100个点的展示，肯定是不够的

**Comment by FantasyNeurotic** [comment]
您这边可以尝试下超过100个点的折线趋势图展示

**Comment by xuwei-fit2cloud** [comment]
您可以检查一下下面两张图红框部分是否有设置100的数据限制。

![图片](https://github.com/user-attachments/assets/bf118ca5-e21f-4dd8-945c-4dccedfa473f)
![图片](https://github.com/user-attachments/assets/49ed1b15-d04c-4bd7-89f3-317e6b7f2daf)

**Comment by FantasyNeurotic** [comment]
> 您可以检查一下下面两张图红框部分是否有设置100的数据限制。
> 
> ![图片](https://private-user-images.githubusercontent.com/1892127/398507211-bf118ca5-e21f-4dd8-945c-4dccedfa473f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTgxMDIsIm5iZiI6MTczNTA5NzgwMiwicGF0aCI6Ii8xODkyMTI3LzM5ODUwNzIxMS1iZjExOGNhNS1lMjFmLTRkZDgtOTQ1Yy00ZGNjZWRmYTQ3M2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjVUMDMzNjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjA1N2M5OTcwYmJiZTJmMzU0M2NiZDU4NmJhN2NmN2Q5MWE0YTNmZmM1Njk4M2EyM2VhZjI5NWVkZTdlOWFmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.o-34mkfIFba315mF_18sc0hAsT1FnJXbd9_VjcZ8JiM) ![图片](https://private-user-images.githubusercontent.com/1892127/398507321-49ed1b15-d04c-4bd7-89f3-317e6b7f2daf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTgxMDIsIm5iZiI6MTczNTA5NzgwMiwicGF0aCI6Ii8xODkyMTI3LzM5ODUwNzMyMS00OWVkMWIxNS1kMDRjLTRiZDctODlmMy0zMTdlNmI3ZjJkYWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjVUMDMzNjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTAxMTAyYTg2NWZkZjVmYmQ0N2MwNmVlNjcwZWZmOGUxMGJiZTczYjZkMjllNjA2YTU1YmY0NmE4OTQ4NzU5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zEo2LLkFBTW2sDfHysojQmxMaScWGzIIHiYTYV5mYu4)

在仪表这边可以看到你上面的按钮， 我是在数据大屏这边使用，没发现仪表板配置这个按钮

**Comment by FantasyNeurotic** [comment]
还有结果展示那里我是设置的全部

**Comment by FantasyNeurotic** [comment]
> > 您可以检查一下下面两张图红框部分是否有设置100的数据限制。
> > ![图片](https://private-user-images.githubusercontent.com/1892127/398507211-bf118ca5-e21f-4dd8-945c-4dccedfa473f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTgxMDIsIm5iZiI6MTczNTA5NzgwMiwicGF0aCI6Ii8xODkyMTI3LzM5ODUwNzIxMS1iZjExOGNhNS1lMjFmLTRkZDgtOTQ1Yy00ZGNjZWRmYTQ3M2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjVUMDMzNjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjA1N2M5OTcwYmJiZTJmMzU0M2NiZDU4NmJhN2NmN2Q5MWE0YTNmZmM1Njk4M2EyM2VhZjI5NWVkZTdlOWFmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.o-34mkfIFba315mF_18sc0hAsT1FnJXbd9_VjcZ8JiM) ![图片](https://private-user-images.githubusercontent.com/1892127/398507321-49ed1b15-d04c-4bd7-89f3-317e6b7f2daf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwOTgxMDIsIm5iZiI6MTczNTA5NzgwMiwicGF0aCI6Ii8xODkyMTI3LzM5ODUwNzMyMS00OWVkMWIxNS1kMDRjLTRiZDctODlmMy0zMTdlNmI3ZjJkYWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjVUMDMzNjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTAxMTAyYTg2NWZkZjVmYmQ0N2MwNmVlNjcwZWZmOGUxMGJiZTczYjZkMjllNjA2YTU1YmY0NmE4OTQ4NzU5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zEo2LLkFBTW2sDfHysojQmxMaScWGzIIHiYTYV5mYu4)
> 
> 在仪表这边可以看到你上面的按钮， 我是在数据大屏这边使用，没发现仪表板配置这个按钮

我在大屏设置这里找到了这个配置，感谢
