### ISSUE TITLE
[Bug] 选项卡控件小BUG 

### ISSUE THREAD

**Issue by gcfanjiawen** [dataease/dataease#1432]
1.同一仪表板拖了多个选项卡控件后。
2.点击新增Tab，多个选项卡会同时新增Tab。
3.未仅仅新增在当前操作的选项卡上。

目前我的解决方案是通过事件bus 将对应当前组件信息回传处理解决 ，大佬看看有啥其它方式分享下哈。

**Comment by BBchicken-9527** [comment]
感谢你的提出，不过需要你受累提供一下使用的版本型号

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，已确认问题，我们尽快修复。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 版本已修复，请等待新版本发布
