### ISSUE TITLE
[Feature] 数据集字段管理切换字段类型为数字时，支持转换带格式的文本

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#14331]
DataEase 版本:
v2.10.3

**请描述您的需求或者改进建议.**
数据集字段管理切换字段类型为数字时，支持转换带格式的文本，如千分符等可直接进行转换
![1735115267374](https://github.com/user-attachments/assets/1f3919e5-6673-4e79-a58c-754c0b5e40a2)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，字段类型转换是用的数据库的转换函数，有的数据库可能不识别千位分隔符，转换会报错；有的数据库可能识别出来，但是也可能会发生截断。建议将千位分隔符去掉后再进行数值转换。
