### ISSUE TITLE
[Bug]图表开启提示后移动端提示框堆叠，优化提示展示：点击下一个图表时，关闭上一个图表提示

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#14334]
DataEase 版本:
2.10.3

**请描述您的需求或者改进建议.**
图表开启提示后移动端提示框堆叠，优化提示展示：点击下一个图表时，关闭上一个图表提示
![image](https://github.com/user-attachments/assets/1ec6f149-0cba-4cc0-a1b5-b84173c9a0a7)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续两个版本内进行优化；
