### ISSUE TITLE
[Feature]桌面版仪表板地图图例自定义区间划分数调整建议

### ISSUE THREAD

**Issue by caudong2024** [dataease/dataease#14354]
DataEase 版本:
桌面版

**请描述您的需求或者改进建议.**
仪表板->图表->地图->图例->图例区间划分 中的自定义区间 的图例数调整后 划分的数字保持之前设置的数值不变。
新增加的划放在最大值之前，默认0。便于使用。

![image](https://github.com/user-attachments/assets/7d1823ee-a89e-45e3-bce6-6cf2f2ee6c8d)

![image](https://github.com/user-attachments/assets/50732fb2-7b8d-40c2-a19f-431fe1d3910f)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前系统是根据区间数等分区间，如有需要，可重新自定义各区间的值，默认值暂时没有计划调整。
