### ISSUE TITLE
[Feature]v2 流向地图，不考虑精度的情况下，可以根据地名映射一个经纬度出来嘛

### ISSUE THREAD

**Issue by zhainanshidai** [dataease/dataease#14382]
DataEase 版本:
v2.10.3

**请描述您的需求或者改进建议.**
v2 流向地图，不考虑精度的情况下，可以根据地名映射一个经纬度出来嘛？比如：国内 xxx省可以映射为省会城市的经纬度。国外，首都的经纬度。这样的好处，可以在数据中没有经纬度的情况下，也可以根据城市/国家名称实现流向地图。
现有的方案中，如果是纯内网环境，这个图表类型就有些不能用了，如果这样能不能替代实现纯离线的环境呢

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，流向地图是根据经纬度进行制作的，因此用户的数据中需要包含起始位置的经纬度信息。流向地图用的是在线地图，地图厂商不支持离线使用。
