### ISSUE TITLE
[Question]CONTRIBUTING.md文件中的development guideline 链接失效了吗？打开页面是404

### ISSUE THREAD

**Issue by likexin-kk** [dataease/dataease#14393]
**请描述您的问题.**
CONTRIBUTING.md文件中的development guideline 链接打开是404
![404](https://github.com/user-attachments/assets/0607e2bc-df11-4ae2-9b31-209da9535870)

**Comment by likexin-kk** [comment]
看代码之前在dev分支修改过[(https://github.com/dataease/dataease/compare/dev)](https://github.com/dataease/dataease/commit/48b6fdfe3749cbc7ab6cdc11a64a95272546c254#diff-efccd95e122ccb13a9a5f2c5c698e2e4706bb0400e549d9a655e0e673f440cc4)

**Comment by xuwei-fit2cloud** [comment]
已更新v2版本对应文档链接。
