### ISSUE TITLE
[Feature]可否实现在大屏/仪表版中对指标维度数据，特别是数字类型数据增加条件颜色显示

### ISSUE THREAD

**Issue by kusen-alpha** [dataease/dataease#14395]
DataEase 版本:

**请描述您的需求或者改进建议.**
比如条件判断正数字为红色，负数字为绿色等等可根据条件判断来显示颜色，以及其他样式等等。

**Comment by xuwei-fit2cloud** [comment]
在图表【高级】-【条件样式】中是可以做设置的。
![图片](https://github.com/user-attachments/assets/7f4d2110-b7a1-49fb-ba67-6ab760e8e771)

**Comment by kusen-alpha** [comment]
看到了，谢谢
