### ISSUE TITLE
1.5版本测试的几点需求和bug

### ISSUE THREAD

**Issue by africaadonis** [dataease/dataease#1440]
**请描述您的需求或者改进建议.**
1、仪表板-其他-多媒体-图片，不支持更换图片，建议再增加调整大小的功能
2、select CONCAT(count(1),CONVERT('间',char)) as 房间在用数 from test，单纯CONCAT(count(1),'间')这样拼接的话，预览数据的时候显示乱码，需要CONVERT之后才行
3、从仪表板中复制的视图（主要是复用样式），点击编辑，建议能在编辑页面修改视图名称，不然还得回到主页，选择上面tab页找到复制的视图改名，有时候复制好几个，找起来很费劲。
4、建议表格增加一个轮播效果
5、仪表板中对表格列宽的调整不是很方便，来回变
6、数据集中通过数字类型字段辅助字符类型字段排序，视图中的排序为无不好使，应该还是走asc去了
![image](https://user-images.githubusercontent.com/40649464/146151851-ed5c364e-28ea-40b6-96e7-6277ea1d9596.png)
![image](https://user-images.githubusercontent.com/40649464/146152213-ca728091-4cc4-405a-ba1d-788aa1619c3e.png)

**Comment by xuwei-fit2cloud** [comment]
非常感谢反馈的问题，我们尽快处理。

**Comment by xuwei-fit2cloud** [comment]
1. 已处理
2. 已处理
3. 已处理
4. 暂时不支持
5. 目前图库还不支持记录列宽
6. 目前确实是这样的，数据集中的排序并不会生效
