### ISSUE TITLE
[Bug] 文字组件中使用Emoji表情后保存报错

### ISSUE THREAD

**Issue by fit2cloud-mahaoyu** [dataease/dataease#1441]
**DataEase 版本**
1.5.2

**浏览器版本**
Microsoft Edge 96.0.1054.57

**Bug 描述**
在文字组件中使用Emoji表情后保存报错，删除Emoji表情后保存成功。
报错内容：
`### Error updating database. Cause: java.sql.SQLException: Incorrect string value: '\xF0\x9F\x8F\x85\xEF\xB8...' for column 'panel_data' at row 1 ### The error may exist in io/dataease/base/mapper/PanelGroupMapper.xml ### The error may involve io.dataease.base.mapper.PanelGroupMapper.updateByPrimaryKeySelective-Inline ### The error occurred while setting parameters ### SQL: update panel_group SET panel_style = ?, panel_data = ? where id = ? ### Cause: java.sql.SQLException: Incorrect string value: '\xF0\x9F\x8F\x85\xEF\xB8...' for column 'panel_data' at row 1`

**Comment by xuwei-fit2cloud** [comment]
这是一个已知问题，暂时还不太好处理。
