### ISSUE TITLE
[Feature]用户间权限隔离

### ISSUE THREAD

**Issue by armored-glitch** [dataease/dataease#14429]
DataEase 版本:
2.10.3

**请描述您的需求或者改进建议.**
  我想尝试用DataEase 做中职院校的BI教学工具，希望将每个学生自己上传的数据时隔离开来的（自己仅能操作自己的数据），目前咱们数据并不能通过用户角色来做，目前考虑用组织来做替代方案（一个组织内设置一个学生），不知道后续会考虑做用户间的数据隔离嘛
。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，v2.x 是用组织做数据隔离的，暂时没有计划调整。
