### ISSUE TITLE
[Bug] 本地模式无法更新HIVE数据

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#1445]
**DataEase 版本**
1.5.0

**浏览器版本**
 96.0.4664.93（正式版本） （64 位）

**Bug 描述**
本地模式无法更新HIVE数据，但是可通过SQL查询到数据。同步任务失败，无日志提示。
直连时正常。

**Bug 重现步骤(有截图更好)**
1.
![1639553556(1)](https://user-images.githubusercontent.com/40846859/146144008-4f313d9c-4037-438d-812b-fed476005a5f.jpg)

2.
![1639554105(1)](https://user-images.githubusercontent.com/40846859/146144052-04af4242-abe7-4e23-b0c6-44cd220872bd.jpg)
3.
![1639554134(1)](https://user-images.githubusercontent.com/40846859/146144118-dd0a7212-7688-4957-a850-e87894e0abb3.jpg)

**Comment by xuwei-fit2cloud** [comment]
可以在DataEase用户群里联系一下@徐伟

**Comment by xuwei-fit2cloud** [comment]
仔细看了一下截图，这个应该是二开的功能吧？产品里对于hive数据源是不支持定时同步的。
