### ISSUE TITLE
[Bug]升级到1.5.2之后，视图出现 no such attribute: limitFiled 错误，导致无法正常显示

### ISSUE THREAD

**Issue by baoshan2020** [dataease/dataease#1446]
**DataEase 版本** 1.5.3

**浏览器版本** edge

**Bug 描述**
升级到1.5.2之后 视图 出现 no such attribute: limitFiled,无法正常显示
如有疑问请联系管理员
**Bug 重现步骤(有截图更好)**
1.![image](https://user-images.githubusercontent.com/61979600/146145191-ef3de840-50e6-4835-b938-678a26e5f763.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们排查一下

**Comment by BBchicken-9527** [comment]
hello目前edge没有做到兼容，我们会在后续版本支持，可以使用谷歌尝试，感谢你的支持

**Comment by baoshan2020** [comment]
收到，非常感谢

**Comment by xuwei-fit2cloud** [comment]
此问题将在 v1.6.0 版本中修复。
