### ISSUE TITLE
[Bug] 查看数据集详情，描述为空时显示问题。

### ISSUE THREAD

**Issue by zyy2721** [dataease/dataease#1447]
**DataEase 版本**
v1.5.2

**浏览器版本**

**Bug 描述**
查看数据集详情，描述为空时显示问题。
**Bug 重现步骤(有截图更好)**
1.
![1](https://user-images.githubusercontent.com/71361375/146156925-021d9505-4afc-4d0c-886e-5697d125f140.jpg)

2.
3.

**Comment by xuwei-fit2cloud** [comment]
显示N/A是因为该数据集对应的数据源没有设置描述信息。可以在【数据源】页面，给对于的数据源增加描述信息。

**Comment by zyy2721** [comment]
这个问题在于，描述为空时，不应该显示N/A。
