### ISSUE TITLE
[Feature]基础折线图增加对比维度参数

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1449]
**请描述您的需求或者改进建议.**
目前需要在基础折线图上实现多条折线的对比只能使用拖拉多个指标的方式，但是很多数据无法直接满足这种条件，需要提前对行列做处理。希望可以增加类似于堆叠折线图里堆叠项的这种参数，比如命名为对比维度，可以通过拖入维度来实现多条折线以形成想要的对比效果。
![image](https://user-images.githubusercontent.com/48945409/146292805-b9fe463f-d953-421a-b390-8512cf032a6d.png)
![image](https://user-images.githubusercontent.com/48945409/146293018-e9b0cf54-87cb-449b-81e0-484019e47054.png)

**Comment by yayanpei** [comment]
感谢您的反馈，基础折线图暂时不考虑增加堆叠项，考虑在堆叠折线图中增加属性（是否显示面积），如果需要建议您先选用堆叠折线图或者堆叠柱形图。
