### ISSUE TITLE
[Bug]API 切换语言为英文时目录大多仍然为中文

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1452]
**DataEase 版本**
V1.5.2

**浏览器版本**
Chrome 96

**Bug 描述**
![image](https://user-images.githubusercontent.com/48945409/146337258-2b2398b5-a1be-40fc-af59-a4e04f35b241.png)

**Comment by xuwei-fit2cloud** [comment]
api 文档内容本身并没有支持国际化，我们把语言切换功能先移除。
