### ISSUE TITLE
系统不支持 COUNT(*) 函数  

### ISSUE THREAD

**Issue by baoshan2020** [dataease/dataease#1462]
**请描述您的需求或者改进建议.**
系统不支持 COUNT(*) 函数  
![d5cf9e42791064b9943836c2641fb71](https://user-images.githubusercontent.com/61979600/146513868-6a834013-1d90-4eab-b339-52aff31907ef.png)

**Comment by zyyfit** [comment]
感谢反馈，我们会尽快处理这个问题

**Comment by BBchicken-9527** [comment]
感谢反馈，已确认问题，我们尽快修复。

**Comment by xuwei-fit2cloud** [comment]
可以暂时先用 select count(*) as abc from xxx 这种方式
