### ISSUE TITLE
[Bug]增加或删除数据源，只有一条数据时操作完需要刷新页面才会更新

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1464]
**DataEase 版本**
1.5.2

**浏览器版本**
Chrome 96

**Bug 描述**
增加或删除数据源，只有一条数据时操作完需要刷新页面才会更新

**Bug 重现步骤(有截图更好)**
1.数据源列表为空时，新增一个数据源后界面未出现新增数据，需要手动刷新后才出现。
![image](https://user-images.githubusercontent.com/48945409/146524552-70214560-cb36-42e8-ad88-5441f92b6bf5.png)

2.当剩余最后一个数据源时，删除数据源后界面上仍然存在，需要手动刷新后才消失。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们在下个版本修复
