### ISSUE TITLE
[Bug] 添加数据源报错

### ISSUE THREAD

**Issue by hao65103940** [dataease/dataease#147]
**DataEase 版本**

v1.0.0
--

**浏览器版本**
91.0.4472.114（正式版本） (arm64)
**Bug 描述**
添加数据源的时候，校验报错

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/33945037/124451015-92686180-ddb7-11eb-81c6-1468f75048b5.png)

**Comment by XiaJunjie2020** [comment]
请确认您安装dataease的机器，可以正常访问这个数据库，是否能ping通，需要代理等

**Comment by hao65103940** [comment]
是公司的环境：http://democenter.fit2cloud.com:40777/#/dataset/index
