### ISSUE TITLE
[Feature]能否同时过滤2个数据表单？

### ISSUE THREAD

**Issue by baoshan2020** [dataease/dataease#1481]
**请描述您的需求或者改进建议.**
视图->组件->文件过滤的时候，能否同时过滤2个数据表单。
![image](https://user-images.githubusercontent.com/61979600/146780887-28f7de5d-cb88-4ed2-ad31-70e5cbda874b.png)

**Comment by xuwei-fit2cloud** [comment]
这个在下个月即将发布的 v1.6.0 版本中会支持
