### ISSUE TITLE
[Bug]文字组件填入字体没保存

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#1499]
**DataEase 版本**
1.5.2
**浏览器版本**
Microsoft Edge
版本 96.0.1054.62 (官方内部版本) (64 位)
**Bug 描述**
仪表板文字组件，清空文字后修改字体大小、字体粗细、对齐方式，再填入文字保存，填入的字体消失。

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/96223591/147081927-162dcc51-4304-4b9b-b2c9-d1a8592f28b4.png)
清空文字
![image](https://user-images.githubusercontent.com/96223591/147081998-75d72018-69e7-46c8-8898-9e8fcca4b0ee.png)
2.修改字体大小22到25，再填入文字
![image](https://user-images.githubusercontent.com/96223591/147082104-f46df583-b436-4705-bc2c-23feb46c60fb.png)
3.保存失败
![image](https://user-images.githubusercontent.com/96223591/147082208-0520156e-c9c5-4ee6-8fdd-6a1e6712a0ed.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下

**Comment by xuwei-fit2cloud** [comment]
v1.6.0版本已修复，请等待新版本发布
