### ISSUE TITLE
[Feature]sql数据集及自定义数据集缺陷

### ISSUE THREAD

**Issue by wangcy727** [dataease/dataease#1500]
sql数据集暂不支持选择表及字段，只能手动写sql。自定义数据集的数据关联只能是两张表的join，无法对数据进行条件过滤，统计汇总。
![image](https://user-images.githubusercontent.com/20203708/147098409-b2e56cca-b5e1-4b31-9800-8f09f12bfd82.png)

**Comment by wangcy727** [comment]
![image](https://user-images.githubusercontent.com/20203708/147094934-1810fc62-faae-4bc6-b0ac-fc2825f3833a.png)
只能join两张表，实际情况可能需要对join的数据进行过滤，汇总，得到一个新的汇聚表，可以定义新的汇聚表有哪些字段。现在的数据关联不能对数据进行过滤，且不能进行函数计算，汇总。要想选中展示字段还要去定义数据集，功能简单不实用，且很零散。建议参考简道云的数据汇聚表。希望能尽快改进

**Comment by xuwei-fit2cloud** [comment]
非常感谢您的建议，我们已记录需求。
