### ISSUE TITLE
[Bug]设置相同的两个视图切换不刷新

### ISSUE THREAD

**Issue by w62651515** [dataease/dataease#1501]
**DataEase 版本**

**浏览器版本**

**Bug 描述**

![image](https://user-images.githubusercontent.com/5866141/147184429-f5ba6087-a059-41b1-b0b7-2bc3b5f64f62.png)
QQ20211223-113424-HD.mp4
**Bug 重现步骤(有截图更好)**
1.设置相同的两个视图切换不刷新
2.
3.

**Comment by w62651515** [comment]
![QQ20211223-114320-HD](https://user-images.githubusercontent.com/5866141/147184980-8ed60deb-d6f8-4204-9a76-7ca1def64cda.gif)

**Comment by BBchicken-9527** [comment]
你好 ，因为刷新较快这样看是不准的。目前测试环境查看是没有发现你说的问题，你直接打开F12查看是否有发送请求就可以了。
