### ISSUE TITLE
[Question]本地模式（基于Apache Doris和Kettle）的使用

### ISSUE THREAD

**Issue by africaadonis** [dataease/dataease#1503]
**请描述您的问题.**
你好，我想测试一下“本地模式（基于Apache Doris和Kettle）”，doris和kettle有可视化的操作界面吗？还是需要自己找呢，看了看官方文档中没有相关的介绍！想着借助doris和kettle发挥dataease更大的能力！
![image](https://user-images.githubusercontent.com/40649464/147186214-1b40fa9d-cdbf-434f-8d11-4f5e395eecb2.png)

**Comment by xuwei-fit2cloud** [comment]
kettle 的话，可以用spoon

**Comment by xuwei-fit2cloud** [comment]
doris的话，可以打开fe的8030端口，从浏览器访问。
也可以用任意的mysql client去连接doris-fe的9030端口，访问数据库
