### ISSUE TITLE
[Bug] 连接Apache Hive2报错

### ISSUE THREAD

**Issue by annisun2020** [dataease/dataease#1507]
**DataEase 版本**
dataease:v1.5.2

**浏览器版本**
Google Chrome :96.0.4664.110

**Bug 描述**
无法预览数据,SQL执行LIMIT 语法错误

**Bug 重现步骤(有截图更好)**

1.Apache Hive2数据源配置
![image](https://user-images.githubusercontent.com/68275306/147207184-6970492a-171e-4244-89f4-08ac9b2df38b.png)

2.数据集设置报错
![image](https://user-images.githubusercontent.com/68275306/147207269-e39cb468-72b5-4889-b647-c592a9ad788f.png)

3.Cloudera Manage后台执行SQL:

![image](https://user-images.githubusercontent.com/68275306/147207420-9339b441-ed2e-4ca1-aa8b-675250e29e49.png)

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 已处理，请等待新版本发布

**Comment by annisun2020** [comment]
V1.7.0 同样的错误 @xuwei-fit2cloud
