### ISSUE TITLE
[Bug]Excel数据替换不成功

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#151]
**DataEase 版本**
1.0

**浏览器版本**
版本 91.0.4472.114（正式版本） (x86_64)

**Bug 描述**
已经导入的Excel数据集，通过编辑完成Excel数据替换，替换完成后数据未更新

**Bug 重现步骤(有截图更好)**
1.首先导入Excel数据，完成相关视图制作
2.然后通过数据集进入刚才导入的Excel数据集，通过编辑/替换/完成excel数据替换。其中excel内容的日期时间人工做了调整
3.然后通过数据预览发现excel未更新替换更新、相关视图也未替换

![image](https://user-images.githubusercontent.com/60059766/124534376-b757e580-de46-11eb-94f8-ebecf17b1cc4.png)

**Comment by xuwei-fit2cloud** [comment]
在 v1.0.1 版本中（体验环境：https://demo.dataease.io)没有复现您说的问题。

**Comment by xuwei-fit2cloud** [comment]
已和您确认，v1.0.1 版本中已修复
