### ISSUE TITLE
[Bug]Oracle直连无法创建自定义数据集。

### ISSUE THREAD

**Issue by qiulinjie0327** [dataease/dataease#1512]
**DataEase 版本**
v1.5.1

**浏览器版本**
chrome

**Bug 描述**
Oracle 直连无法创建自定义数据集

**Bug 重现步骤(有截图更好)**
1.创建Oracle直连数据集A&B
2.创建自定义数据集，选择A&B数据集内字段
3.报错java.sql.SQLSyntaxErrorException: ORA-00972: identifier is too long

![4fc01f4061942fbf9b59fb014157a65](https://user-images.githubusercontent.com/52249559/147327399-67389388-01a3-498e-8926-cde514db1184.png)

**Comment by BBchicken-9527** [comment]
你好，目前环境上没有发现你这种情况，你可以尝试升级到最新版本，看看是否存在此问题。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 版本已修复，请等待新版本发布
