### ISSUE TITLE
视图带自动计算能力[Feature]

### ISSUE THREAD

**Issue by plateauandsp** [dataease/dataease#1521]
**请描述您的需求或者改进建议.**
目前DE的视图不带任何计算能力，而在实际使用场景中，需要技术一定数值。比如下图，希望视图直接显示新增/总数*100%的占比。
![image](https://user-images.githubusercontent.com/30932762/147404202-df134efb-8d69-4995-9c09-224e4f08475d.png)
而此功能在帆软finebi中具备。见下图和链接：
![image](https://user-images.githubusercontent.com/30932762/147404299-72cd9085-5751-4240-acac-89b7d6307f3e.png)

https://help.fanruan.com/finebi/doc-view-498.html

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 版本会支持同比、环比的计算方式，其他计算方式后续会逐步添加。
