### ISSUE TITLE
[Feature]支持表格展示方式快速样式

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#154]
**请描述您的需求或者改进建议.**
支持基于表格视图快速定义表格样式，可参考PPT方式：
![image](https://user-images.githubusercontent.com/60059766/124536701-fdaf4380-de4a-11eb-807c-700b46384e61.png)

**Comment by yayanpei** [comment]
非常感谢您的反馈，您的建议非常好，我们会优先考虑并纳入后期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
近期版本还不会对该功能进行支持。
