### ISSUE TITLE
[Question]目前仓库的sql脚本貌似不是最新的？

### ISSUE THREAD

**Issue by lesliechueng** [dataease/dataease#1540]
通过idea启动项目报错，sql脚本不是最新的，有些表字段扩充了，目前sql脚本中不包含该字段

**Comment by xuwei-fit2cloud** [comment]
请贴出具体的错误截图。
另外，建议用v1.5分支，不要直接使用main和dev分支的代码，这两个分支属于开发分支，代码并不稳定。

**Comment by lesliechueng** [comment]
由于自动执行脚本存在错误，重新手动导入之后不存在该问题
