### ISSUE TITLE
[Feature] 数据集添加定时同步数据，更新结果中，建议增加影响行数和所执行的SQL

### ISSUE THREAD

**Issue by shaolinah** [dataease/dataease#1541]
**请描述您的需求或者改进建议.**

数据集中，添加数据集，定时同步，更新数据，更新结果中，建议增加影响行数和所执行的SQL，现在用的定时同步，只知道同步成功了，但结果不符合预期，同步的数据比预期的要多很多，没有SQL，也没有影响的行数，排查很不方便

另外，数据集数据预览列表，总数量不能放出来么？根据SQL数据集的时候，想知道当然数据集有多少数据，见图2

![image](https://user-images.githubusercontent.com/37900818/147546538-7d4219fe-b066-440e-b462-64c009861669.png)

![image](https://user-images.githubusercontent.com/37900818/147551328-1388d3f8-27b9-4f57-8f1a-dba1b4ea61e7.png)

**Comment by xuwei-fit2cloud** [comment]
这个已经在我们需求列表中，暂时因为一些技术问题不太好处理，一旦有方案后，我们会优先实现。
