### ISSUE TITLE
[Bug]仪表盘中筛选数据，最后一页分页数据不正确

### ISSUE THREAD

**Issue by shaolinah** [dataease/dataease#1543]
**DataEase 版本**
v1.5.2

**浏览器版本**
Chrome

**Bug 描述**
时间范围选择12-01号至第二年01-31号，数量大于1000，分页正常
![image](https://user-images.githubusercontent.com/37900818/147553913-4f314899-a296-4a5b-9e26-722d669a6dc0.png)

时间范围改为12-01号至12-02号，总数量478，分页默认为最后一页，但最后一页的八个数据并没有显示，往前翻一页在回来才会显示
![image](https://user-images.githubusercontent.com/37900818/147554053-e8915e02-ad47-4268-8fe7-326cc0c0cf0b.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

小毛病，使用中发现了，影响不大

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 版本已修复，请等待新版本发布
