### ISSUE TITLE
添加数据集的时候支持快速配置[Feature]

### ISSUE THREAD

**Issue by plateauandsp** [dataease/dataease#155]
**请描述您的需求或者改进建议.**
添加数据集的时候，选择定时或者直连支持时能够快速配置定时任务或者立即同步，不然每次都需要重复配置
![image](https://user-images.githubusercontent.com/30932762/124540371-dad45d80-de51-11eb-8747-30d3432687ae.png)

**Comment by yayanpei** [comment]
非常感谢您的反馈，您的建议非常好，我们会优先内部讨论并考虑加入后期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已支持
