### ISSUE TITLE
支持维度和指标转化，丰富指标函数[Feature]

### ISSUE THREAD

**Issue by plateauandsp** [dataease/dataease#156]
**请描述您的需求或者改进建议.**
支持维度和指标转化，支持丰富的指标函数，目前只有一个

**Comment by yayanpei** [comment]
感谢您的反馈和建议，V1.1.0版本会支持维度和指标转化，其他的指标函数也会在后期的版本迭代中逐渐完善

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已支持维度和指标转化
