### ISSUE TITLE
[Question]在线安装错误提示

### ISSUE THREAD

**Issue by youc3576** [dataease/dataease#1578]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/20590152/147798358-7978a8d0-43de-4a94-9b2f-3c7276040e89.png)

**Comment by xuwei-fit2cloud** [comment]
这个是因为在线安装docker失败了，可以手动安装docker环境，也可以用离线包安装。
离线包中包含了安装所需的软件及docker镜像，下载地址为：
https://community.fit2cloud.com/#/products/dataease/downloads

**Comment by 8debug** [comment]
> 这个是因为在线安装docker失败了，可以手动安装docker环境，也可以用离线包安装。 离线包中包含了安装所需的软件及docker镜像，下载地址为： https://community.fit2cloud.com/#/products/dataease/downloads

最好在文档中写明！！！！
