### ISSUE TITLE
[Bug]基于自适应画布，画布大小为1600*900的布局定义仪表盘

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#158]
**DataEase 版本**
1.0.1

**浏览器版本**
谷歌91

**Bug 描述**
最下层基于画布定义排布整齐，整齐后，预览仪表盘，仪表盘未对其

**Bug 重现步骤(有截图更好)**
1.自适应画布，非矩阵设计场景下自定义；1600*900
2.布局整个图片，图片靠底部对整齐，整齐后最终仪表盘未对其
【仪表盘编辑页面】
![image](https://user-images.githubusercontent.com/60059766/124554543-aa4bee00-de68-11eb-9427-4d5c5ef928fc.png)
【仪表盘展示页面】
![image](https://user-images.githubusercontent.com/60059766/124554647-c64f8f80-de68-11eb-8cab-b39191ad5a70.png)

**Comment by xuwei-fit2cloud** [comment]
这个是不同页面尺寸不同导致的自适应问题，我们处理一下

**Comment by xuwei-fit2cloud** [comment]
v1.2.0 已处理
