### ISSUE TITLE
[Feature] 希望可以区分观看者和管理员模块

### ISSUE THREAD

**Issue by 1797890817** [dataease/dataease#1582]
**请描述您的需求或者改进建议.**
你们好体验了你们的Demo系统，体验确实不错，不过有一点，系统没有区分一般用户和后台管理员。
建议进行区分，比如：
一般用户，给他们一个入口进去看就好了，他们不需要知道如何去配置，很多用户也完全不懂；
后台管理员：具有所有的功能，同时可以把新建或者更新的模块发布到一般用户那边。

**Comment by xuwei-fit2cloud** [comment]
体验环境中没有提供权限体系，这个需求可以通过权限控制来满足。

**Comment by 1797890817** [comment]
你们能提供带有权限控制的体验系统吗？我想确认是不是能分开，并且仪表板菜单是动态可配置的。

**Comment by maninhill** [comment]
你可以填写这个表单，我们会有同事与您进一步沟通。https://jinshuju.net/f/TK5TTd

谢谢。

**Comment by 1797890817** [comment]
没有企业邮箱，你们也可以直接提供企业版体验系统啊。
