### ISSUE TITLE
[Feature]用户所在组织给与数据集【授权】权限后，用户可以所有用户信息(X-PACK)

### ISSUE THREAD

**Issue by Ankers-liu** [dataease/dataease#1585]
**请描述您的需求或者改进建议.**
**DataEase 版本**
v1.5.2

**浏览器版本**
Chrome版本 96.0.4664.110（正式版本） （64 位）
Firefox 95.0.2 (32 位)

**问题描述**
只是普通用户权限的账号，只要在所在组织内授予了数据集的授权权限，就可以看到DE上说有的人员信息。而理论上讲，普通用户只可以看到本用户的用户信息。

**重现步骤(有截图更好)**
1.在管理员界面中设置普通用户权限用户，并且设置其所在组织对某个视图的授权权限。
![image](https://user-images.githubusercontent.com/57253444/148006470-60af6fef-5da8-4095-adc7-22d965f9cdf9.png)
![image](https://user-images.githubusercontent.com/57253444/148006627-19a8d444-827f-42ad-8021-d22a817961df.png)

2.登陆到普通用户界面，查看这个用户可以查看到DE上所有的用户信息。
![image](https://user-images.githubusercontent.com/57253444/148006962-d8d0ffee-37c9-4628-a799-abf8d8c12734.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们在自己的环境中并没有重现此问题。
在issue里的截图，该用户被分配到 默认组织 中，且授权也是对 默认组织 进行授权。可以查看一下 默认组织 的 菜单和操作权限 选项中是否有用户管理的相关权限。
