### ISSUE TITLE
[Question]dataease.properties文件在哪里。

### ISSUE THREAD

**Issue by MrJackBack** [dataease/dataease#1587]
**请描述您的问题.**
您好，项目启动需要加载dataease.properties文件，下载了整个项目没有发现这个文件，这个文件是在什么位置呢，查看操作手册也没有看到相关说明。

**Comment by xuwei-fit2cloud** [comment]
你好，可以参考这个文档
https://dataease.io/docs/dev_manual/dev_manual/#dataease

源文件在 
https://github.com/dataease/installer/blob/master/dataease/templates/dataease.properties
