### ISSUE TITLE
[Bug]动态时间自定义时预览部分有遮挡

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1602]
**DataEase 版本**
1.6.0

**浏览器版本**
Chrome 96

**Bug 描述**
![image](https://user-images.githubusercontent.com/48945409/148333754-d117870c-fe45-4971-b306-664fc9e04d66.png)

**Comment by BBchicken-9527** [comment]
我们将会在下个小版本中修复，感谢反馈

**Comment by xuwei-fit2cloud** [comment]
v1.6.2 版本已修复
