### ISSUE TITLE
[Bug]修改视图详情的类型 更新不及时

### ISSUE THREAD

**Issue by Hjw52** [dataease/dataease#1606]
**DataEase 版本**
1.6.0

**浏览器版本**
Chrome 96

**Bug 描述**
![image](https://user-images.githubusercontent.com/49404132/148640107-f1fa023e-ef3b-43c5-9b4b-761897dda189.png)

**Bug 重现步骤(有截图更好)**
1.修改某个视图的类型 点击保存
2.查看视图详情，图表类型没有更新
3.预期效果：修改后应更新视图详情，而不是手动刷新或者重新点击后再更新（其他地方也有类似情况）

**Comment by BBchicken-9527** [comment]
感谢反馈，我们修复一下

**Comment by xuwei-fit2cloud** [comment]
v1.6.2 版本已修复
