### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by JamieSlome** [dataease/dataease#1607]
Hey there!

I belong to an open source security research community, and a member (@ready-research) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by xuwei-fit2cloud** [comment]
Thank you very much! We have added the SECURITY.md file to the project.

**Comment by JamieSlome** [comment]
Just for reference, the report can be found here:

https://huntr.dev/bounties/c4293d06-4155-482f-b4e7-540ed0241266/

**Comment by ready-research** [comment]
@xuwei-fit2cloud Hi provided a patch also in the above [huntr](https://huntr.dev/bounties/c4293d06-4155-482f-b4e7-540ed0241266/) link.

**Comment by ready-research** [comment]
@fit2cloudrd @xuwei-fit2cloud  Can you please validate this report https://huntr.dev/bounties/c4293d06-4155-482f-b4e7-540ed0241266/ using `Mark as Valid` and also `Confirm the fix` with the provided patch(you can select my patch). Thanks.

**Comment by JamieSlome** [comment]
@fit2cloud-chenyw @fit2cloudrd @xuwei-fit2cloud - it looks like the issue might have been addressed (https://github.com/dataease/dataease/commit/fc1720c5184b82962dbc79cfaa9d745fc66bfce3).

Can you please confirm if this commit addresses the following report:
https://www.huntr.dev/bounties/c4293d06-4155-482f-b4e7-540ed0241266/
