### ISSUE TITLE
[Bug]折线图同比功能

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#1608]
**请描述您的需求或者改进建议.**
同比往年的数据，往年数据的坐标轴还会显示出来
![image](https://user-images.githubusercontent.com/96223591/148712595-e258b286-4e2f-4412-a6ba-eb81ada8e92e.png)

**Comment by yayanpei** [comment]
感谢您的反馈，日期横坐标轴的显示范围由所选字段的值均定，如果不需要展示2020年的数据，可以在视图中的过滤器中添加过滤条件，过滤掉2020年的数据，请见如下：
![image](https://user-images.githubusercontent.com/84168063/148725424-873a1bc8-5cae-4842-933e-c8b70e4e0e2a.png)

**Comment by Avanbchen** [comment]
好的，谢谢！

**Comment by xyd113** [comment]
v1.8.0同样遇到这个问题，并且在视图中的过滤器中添加过滤条件，过滤掉2020年的数据之后，会显示2021年的没有折线的坐标轴。这里的筛选是筛选掉2020年的数据，而不是截掉2020年的坐标轴，请确认。
