### ISSUE TITLE
[Bug]标签换行定义输入\n不生效，直接切换换行即可

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#161]
**DataEase 版本**
1.0.1

**浏览器版本**
91

**Bug 描述**
标签换行定义输入\n不生效，直接切换换行即可

**Bug 重现步骤(有截图更好)**
1.标签换行定义输入\n不生效，直接切换换行即可
2.
3.
![image](https://user-images.githubusercontent.com/60059766/124562161-47128980-de71-11eb-8618-079c57fce568.png)

**Comment by xuwei-fit2cloud** [comment]
感谢您的反馈，我们尽快修复

**Comment by XiaJunjie2020** [comment]
我们会在下个版本v1.0.2中修复，感谢您的反馈

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已修复
