### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by 18744269713** [dataease/dataease#1617]
**DataEase 版本**

v1.5.2
**浏览器版本**

**Bug 描述**
mongodb 数据集里的数据变更后，dataease查询无法加载最新数据

**Bug 重现步骤(有截图更好)**
1.最新的数据
![image](https://user-images.githubusercontent.com/41908512/148884295-c266cf4c-2c17-40a8-8995-670b61e18045.png)

2.重新查询，显示不正常
![image](https://user-images.githubusercontent.com/41908512/148884193-1c3bc9fb-8b18-449e-90fd-cdda2cda2df3.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们确认一下
