### ISSUE TITLE
[Bug]侧边栏树（数据集界面）重命名后 预览界面名称没有刷新

### ISSUE THREAD

**Issue by Hjw52** [dataease/dataease#1619]
**DataEase 版本**
v1.6

**浏览器版本**
chrome.95

**Bug 描述**
![屏幕截图 2022-01-11 135645](https://user-images.githubusercontent.com/49404132/148889148-032fa5ed-7e9d-4a9e-8a8e-061b5a2b82ed.png)

**Bug 重现步骤(有截图更好)**
1.预览数据集A
2.导航处修改数据集名称（图中，修改后4444，修改前333）
3.查看修改后导航变化和预览区域名称变化

预期效果：名称修改后，预览区域也要进行相应的更新

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复

**Comment by BBchicken-9527** [comment]
感谢反馈 ，问题将会在下个小版本修复

**Comment by xuwei-fit2cloud** [comment]
v1.6.2 版本已修复
