### ISSUE TITLE
视图过滤支持更丰富的算法[Feature]

### ISSUE THREAD

**Issue by plateauandsp** [dataease/dataease#162]
**请描述您的需求或者改进建议.**
目前在视图中进行过滤设置只有等于不等于这些，没有包含不包含，不支持&这些算法。多些筛选的，配置太复杂
![image](https://user-images.githubusercontent.com/30932762/124566539-ba1dff00-de75-11eb-9ca7-a28ec4a8186c.png)

**Comment by xuwei-fit2cloud** [comment]
v1.1.0 中将支持包含与不包含，请等待版本发布
