### ISSUE TITLE
[Bug]地图通过鼠标缩放到最小点击重置按钮消失

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1620]
**DataEase 版本**
1.6.1

**浏览器版本**
Chrome 96

**Bug 描述**
地图通过鼠标缩放到最小点击重置按钮消失

**Bug 重现步骤(有截图更好)**
1.用鼠标将视图中的地图缩放到最小（使用缩小图标不会出现此种情况）
![image](https://user-images.githubusercontent.com/48945409/148895296-26539f73-77ee-4a76-8152-a25eb615d093.png)

2.点击重置按钮
![image](https://user-images.githubusercontent.com/48945409/148895330-d1382a33-0bfc-4fad-acf7-663c2fd5e36d.png)

3.地图消失
![image](https://user-images.githubusercontent.com/48945409/148895346-9ced0fca-97f2-47ef-8650-23c068cfbc05.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复

**Comment by BBchicken-9527** [comment]
感谢反馈 ，问题将会在下个小版本中修复

**Comment by xuwei-fit2cloud** [comment]
v1.6.2 版本已修复
