### ISSUE TITLE
明细表样式需求

### ISSUE THREAD

**Issue by chenzutong** [dataease/dataease#1621]
**明细表样式需求**
*使用版本1.6.0*
我们原本需求
![image](https://user-images.githubusercontent.com/58797046/148906713-f47f773a-52e2-4b83-9586-426d7542268e.png)
目前dataease只能做到这效果
![image](https://user-images.githubusercontent.com/58797046/148906913-4cae2eb7-2bea-49c1-a51c-8c2605851ef4.png)
**明细表样式建议.**
1. 可以把边框去掉
2. 最小字体能不能再小一点
3. 表下的数据总数和分页功能，可否不显示
4. 可否隐藏排序功能的图标
5. 如果能做到自动循环滚动，最好了

望采纳 ~~

**Comment by xuwei-fit2cloud** [comment]
感谢反馈需求，我们内部讨论一下
