### ISSUE TITLE
视图集名称显示不全

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#1625]
**请描述您的需求或者改进建议.**
因为视图比较多，将视图集边框宽度拉长后，再添加视图，边框又自动回复。
![image](https://user-images.githubusercontent.com/96223591/149048347-4f59f67c-8e94-426f-8dff-330ecfd4ee1f.png)
重新添加视图，视图边框回复到原位，一些视图的名称显示不全
![image](https://user-images.githubusercontent.com/96223591/149048837-ea8f30c7-ae63-4855-b246-c8bb781f7f09.png)

**Comment by yayanpei** [comment]
感谢您的反馈，我们优化一下。
