### ISSUE TITLE
[Bug] 数据源无法添加 SQL Server 「SSL 加密模式」

### ISSUE THREAD

**Issue by lvxiaohu** [dataease/dataease#1639]
**DataEase 版本**
v1.6.0

**浏览器版本**
chrome

**Bug 描述**
新建数据源提示：

com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "The server selected protocol version TLS10 is not accepted by client preferences [TLS12]". ClientConnectionId:9773888f-ee23-409c-9400-0f96cc9c01c0

**Bug 重现步骤(有截图更好)**
1. 登录Dataease
2. 新建数据源
3. 填写 SqlServer 服务器信息
![image](https://user-images.githubusercontent.com/29087369/149309474-39639c15-fb61-4bda-8dea-bd6cfe704a51.png)

**Comment by xuwei-fit2cloud** [comment]
该问题已修复，请等待新版本发布

**Comment by lvxiaohu** [comment]
赞！期待新版本发布

**Comment by xuwei-fit2cloud** [comment]
v1.6.2 版本已修复
