### ISSUE TITLE
[Bug] 数据集行权限设置优化

### ISSUE THREAD

**Issue by lvxiaohu** [dataease/dataease#1640]
**DataEase 版本**
v1.6.0

**浏览器版本**
chrome

**Bug 描述**
平台管理员admin，编辑某个数据集的行权限时，有权限编辑图标为蓝色，没权限编辑时为灰色，不是很友好，新用户理解会是都用admin了，有的按钮为什么不能点。既然不能编辑，**不显示编辑按钮**会更好。
![image](https://user-images.githubusercontent.com/29087369/149310897-5d9f5b2d-a9a8-44c2-83d3-1f6f758cc89b.png)

**Bug 重现步骤(有截图更好)**
1. 权限管理
2.编辑数据集权限

**Comment by Avanbchen** [comment]
是不是先授权给用户，才赋予这个用户的行权限，这个逻辑没问题呀（吃瓜）

**Comment by lvxiaohu** [comment]
> 是不是先授权给用户，才赋予这个用户的行权限，这个逻辑没问题呀（吃瓜）

逻辑没有问题的，只是站在用户使用体验角度上觉得可以优化一下。没权限编辑，就不显示编辑功能按钮。
