### ISSUE TITLE
[Bug] mongo 同一个collection下的字段不一样，加载出来的数据集默认只显示了第一条的字段

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#1646]
源数据如下：
![image](https://user-images.githubusercontent.com/30063018/149650099-cee7ec93-07c1-4efd-b92d-740a6af5d085.png)
数据集显示如下：
![image](https://user-images.githubusercontent.com/30063018/149650106-259a885b-1105-4052-8cb6-ce9bbbdd8bbe.png)
多出来的的字段就不加载了

**Comment by BBchicken-9527** [comment]
感谢反馈，我们尽快修复。
