### ISSUE TITLE
[Bug]分享给其它用户的仪表板联动事件失效

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1647]
**DataEase 版本**
1.6.1

**浏览器版本**
Chrome 96

**Bug 描述**
分享给其它用户的仪表板，其它用户查看时联动事件无效。

**Bug 重现步骤(有截图更好)**
1.为仪表板增加联动效果；
![image](https://user-images.githubusercontent.com/48945409/149720994-4cf71e5e-bf8f-49ab-80e6-558fcf2fd25c.png)

2.分享给一个没有该仪表板权限的用户；
![image](https://user-images.githubusercontent.com/48945409/149721121-a054fb42-6c2c-4cbd-82c5-98926afd614d.png)

3.使用该用户账号登录在”分享给我“的仪表板中查看点击视图无联动效果。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复。

**Comment by BBchicken-9527** [comment]
已经修复，下个版本发布
