### ISSUE TITLE
查看数据集的时候，保留 右边数据集视图和左侧菜单栏之间分割线的位置

### ISSUE THREAD

**Issue by Fit2CloundGhh** [dataease/dataease#1649]
在左侧的菜单栏中建立的数据集的名称相对较长，拖动分割线至数据集名称可见，但是每次点击数据集查看具体内容时，分割线又会回到默认的位置，当仪表板视图比较多的时候，就会相对繁琐

**Comment by yayanpei** [comment]
感谢您的反馈，左侧菜单栏的调整需要将页面进行重构，已经在需求池中。
