### ISSUE TITLE
mongodb视图不支持条件过滤

### ISSUE THREAD

**Issue by evilhy** [dataease/dataease#1655]
![微信图片_20220118171349](https://user-images.githubusercontent.com/49869612/149906825-2338b7fc-ec03-47e2-bb1a-7e3e87470145.png)

**Comment by evilhy** [comment]
情况出现在 关联数据集 下  单个mongodb集合数据可以正常过滤。 关联数据集下过滤需要每个数据集下都必须要有该字段才能过滤。

**Comment by evilhy** [comment]
![截图_选择区域_20220119103308](https://user-images.githubusercontent.com/49869612/150052769-98a1ab1f-c89a-41c7-9e38-bf113a2912c2.png)

**Comment by xuwei-fit2cloud** [comment]
v1.7.0 已修复，请更新版本。
