### ISSUE TITLE
一键脱机部署1.6.1 登录报错Decryption error

### ISSUE THREAD

**Issue by soscat** [dataease/dataease#1656]
新服务器 centos7  一键脱机部署1.6.1 登录报错 Decryption error!

**Comment by xuwei-fit2cloud** [comment]
是否是升级到 1.6.1 版本？可以试试用隐身模式打开，或者清理一下浏览器缓存试试

**Comment by soscat** [comment]
升级后需要刷新浏览器。可能是浏览器版本过旧。

**Comment by soscat** [comment]
是从1.1升级到1.6.1后出现此问题，清除缓存依然弹出报错信息。浏览器版本chrome87。
