### ISSUE TITLE
中国地图支持多个指标[Feature]

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#1676]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/35896106/150309662-4abbd46b-db34-48cd-addf-c20bf50ca265.png)
目前只能拖一个指标，希望支持多个指标

**Comment by yayanpei** [comment]
感谢您的反馈，我们先调研一下。如果急需使用，建议用tab组件切换的方式。
