### ISSUE TITLE
指标卡支持插入自定义描述内容[Feature]

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#1677]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/35896106/150312879-12d583d6-783b-4ac0-83cd-11f550b48e74.png)

目前只有标题+显示名设置，希望可以增加指标数据描述，类似备注

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，该需求已记录
