### ISSUE TITLE
外部链接跳转参数传递

### ISSUE THREAD

**Issue by caiiansheng** [dataease/dataease#1680]
从发布的更新日志看从
V1.6版本仪表板跳转支持外部链接传递参数，但是我没有找到这个怎么用，从跳转地址上没有看到相关的参数
![image](https://user-images.githubusercontent.com/26760483/150628921-dd241337-7a5e-4d20-8407-cf015db3182d.png)
希望左侧的参数，能在跳转的时候，传过去，实际使用参数没有传递过去
![image](https://user-images.githubusercontent.com/26760483/150629006-1cda2c18-743d-48e2-98dd-5ae710a13dcf.png)

跳转后地址：
![image](https://user-images.githubusercontent.com/26760483/150629046-2cb7769b-7075-4c28-9c69-2bf5bba809db.png)

**Comment by yayanpei** [comment]
感谢反馈，跳转目标为仪表板时，V1.6.0 是支持传参数的；如果跳转目标为第三方网站（比如百度），目前是不支持传参数的。
