### ISSUE TITLE
[Feature]希望增加世界地图

### ISSUE THREAD

**Issue by 1799498637** [dataease/dataease#1682]
希望增加世界地图，以便展示涉及国外访问的项目，感谢各位大大

**Comment by xuwei-fit2cloud** [comment]
是需要类似中国地图这样精度的地图，还是世界地图国家级别的地图呢？

**Comment by 1799498637** [comment]
> 是需要类似中国地图这样精度的地图，还是世界地图国家级别的地图呢？

世界地图国家级别的地图就可以了

**Comment by xuwei-fit2cloud** [comment]
收到，已经添加到需求列表中

**Comment by pwjack** [comment]
能知道世界地图大概的进度吗?
