### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by songbing0312** [dataease/dataease#1683]
**请描述您的需求或者改进建议.**

目前v1.16版本仪表盘中的图片上设置了目标地址后，是这个效果，是点击了当前仪表盘的这个图片后，会跳转到另一个网址
<img width="830" alt="WechatIMG13" src="https://user-images.githubusercontent.com/18387151/150736799-611ca1b1-9bde-44ad-9d00-3937dd3cdc33.png">

我的需求是，仪表盘直接显示某个链接地址的图片
1、相当于在仪表中盘填加图片时，可以输入一个URL地址，然后图片展示的就是当前URL地址对应的图片
2、还可以设置一个定时任务，比如每分钟定时访问这个URL地址后，在仪表盘就是每分钟会定时刷新当前图片

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们讨论一下

**Comment by xuwei-fit2cloud** [comment]
v1.7.0 版本可支持。
