### ISSUE TITLE
[Bug] 系统管理-数据同步下执行记录没有查询到数据

### ISSUE THREAD

**Issue by WinterChenS** [dataease/dataease#1686]
**DataEase 版本**
1.6.0

**浏览器版本**

Microsoft Edge
版本 97.0.1072.62 (官方内部版本) (64 位)

**Bug 描述**
通过创建数据库数据集执行同步，失败之后的执行记录没有在执行记录中查询到，通知跳转到执行记录也是没有的

**Bug 重现步骤(有截图更好)**
1. 创建数据库数据集并执行同步，失败之后
2. 打开系统管理-数据同步-执行记录
3. 没有失败的执行记录

**Comment by xuwei-fit2cloud** [comment]
建议扫描下方的二维码，联系技术支持人员处理一下。
![图片](https://user-images.githubusercontent.com/1892127/150941030-78f214f3-4e7f-4d3c-953e-83fbb87ff84d.png)
