### ISSUE TITLE
[Bug] 仪表板选择文本下拉页面会卡住

### ISSUE THREAD

**Issue by WinterChenS** [dataease/dataease#1688]
**DataEase 版本**
前端：1.5.0

**浏览器版本**
Microsoft Edge
版本 97.0.1072.62 (官方内部版本) (64 位)

**Bug 描述**
仪表板选择文本下拉框，并选择视图字段页面会卡死

**Bug 重现步骤(有截图更好)**
1. 新建仪表板，拖入视图，拖入文本下拉
![image](https://user-images.githubusercontent.com/15863367/150932288-925e874d-f3d9-43e8-a13e-6703cadbb416.png)

**Comment by BBchicken-9527** [comment]
需要和你确认一下这个字段有多少数据？
