### ISSUE TITLE
[BUG]搜索分组后不能对分组进行操作

### ISSUE THREAD

**Issue by linyuantang001** [dataease/dataease#169]
**DataEase 版本**

v1.0.1

**浏览器版本**
 chrome 91.0.44

**Bug 描述**

搜索分组后不能对分组进行操作
![image](https://user-images.githubusercontent.com/39185981/124632931-5ae0de80-deb7-11eb-8400-56b0b9a3a6ef.png)

**Comment by xuwei-fit2cloud** [comment]
感谢您的反馈，该问题已修复，将在 v1.0.2 里发布

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已修复
