### ISSUE TITLE
【优化建议】 创建视图完成之后，点击保存可以有个反应。另外保存之后的视图希望可以修改重命名

### ISSUE THREAD

**Issue by hao65103940** [dataease/dataease#17]
【优化建议】 创建视图完成之后，点击保存可以有个反应。另外保存之后的视图希望可以修改重命名

**Comment by hao65103940** [comment]
【优化建议】 创建视图完成之后，点击保存可以有个反应。另外保存之后的视图希望可以修改重命名

**Comment by wxcen** [comment]
可以修改
![image](https://user-images.githubusercontent.com/40848979/123404348-8fad8580-d5db-11eb-854c-3c474dee0a72.png)

**Comment by xuwei-fit2cloud** [comment]
已增加重命名功能，将在 v1.1.0 版本发布。
