### ISSUE TITLE
[Question] DataEase 能不能做出类似这个的效果？

### ISSUE THREAD

**Issue by maninhill** [dataease/dataease#171]
**请描述您的问题.**

![image](https://user-images.githubusercontent.com/41712985/124696140-1d13a280-df17-11eb-8e9f-cffa25294396.png)

**Comment by maninhill** [comment]
https://bi.aliyun.com/template/nl/preview?templateId=dd4c9615-4aa0-4602-aaf1-93a1f046fbae

**Comment by xuwei-fit2cloud** [comment]
DataEase 目前还做不到类似的效果，您的需求就是我们前进的方向
