### ISSUE TITLE
[Feature]希望汇总方式支持自定义方式

### ISSUE THREAD

**Issue by amuluowin** [dataease/dataease#1718]
**请描述您的需求或者改进建议.**
指标的汇总和计算方式支持自定义，
可以是函数（提供内部函数）
或者SQL
很多场景下指标不单是简单的计算，还会涉及到一些处理，
例如在`ClickHouse`下，会做`sumIf`,`avgIf`等判断统计

**Comment by xuwei-fit2cloud** [comment]
感谢您的建议，我们已经记录，先进行一下内部讨论。
