### ISSUE TITLE
[Bug] EsQueryProvider时间问题

### ISSUE THREAD

**Issue by yuebo** [dataease/dataease#1721]
**DataEase 版本**
1.6.2

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome 94

**Bug 描述**
ES数据源时间格式年份错误，数据里面无2021年1月1号数据，但是统计信息里有，经排查时时间格式错误是时间格式默认为，"YYYY-MM-dd HH:mm:ss"，应该使用"yyyy-MM-dd HH:mm:ss"
**Bug 重现步骤(有截图更好)**
![1643358572(1)](https://user-images.githubusercontent.com/9998927/151513097-a5f34994-e65f-42d1-8d82-ae2296ad2101.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们尽快修复。
