### ISSUE TITLE
[Feature] 手机端能否和PC端一致

### ISSUE THREAD

**Issue by yuebo** [dataease/dataease#1723]
**请描述您的需求或者改进建议.**
手机端报表分享后，可以输入密码访问或者公开访问而不需要用户必须登录才能访问，这样方便使用webview嵌入现有的手机应用。

**Comment by xuwei-fit2cloud** [comment]
可以选中要分享的仪表板，创建无密码的公共链接，把公共链接发送给用户，用户通过手机端访问时，显示的也是移动端的样式，也不需要登录的。
![图片](https://user-images.githubusercontent.com/1892127/151649076-a3829ed4-3d2c-484c-a29c-05dfd05f5b50.png)

**Comment by yuebo** [comment]
我在官网demo里面创建了一个公开链接[https://dataease.fit2cloud.com/link/1]( https://dataease.fit2cloud.com/link/1) ，pc端没问题的，当打开手机端会重定向到登录页面
![1643435261(1)](https://user-images.githubusercontent.com/9998927/151649304-84bbe2c9-b0d5-44a9-9fc9-2f4968b5f656.png)

**Comment by yayanpei** [comment]
感谢您的反馈，该情况已经在 V1.6.0 版本已经优化。
