### ISSUE TITLE
[Bug] mongodb 数据预览bug

### ISSUE THREAD

**Issue by 18744269713** [dataease/dataease#1730]
**DataEase 版本**

v1.7.0 

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

chrome 版本 98.0.4758.81（正式版本） （64 位）

**Bug 描述**
mongodb 数据集无法正常预览数据
![image](https://user-images.githubusercontent.com/41908512/152714642-5bdcb143-8eae-423a-97df-4f5e108d42e3.png)

**Bug 重现步骤(有截图更好)**
1.添加mongodb的数据源
2.添加数据库数据集
3.数据预览报错
![F4A261C8-F794-4c93-B07A-78F94FF71E74](https://user-images.githubusercontent.com/41908512/152715757-58ad9706-2dc1-4006-97aa-f499a35daa6a.png)

**Comment by eagle-du** [comment]
线下沟通结果是不支持嵌套的json解析，这种用递归的方式应该是可以实现的吧， 可否转需求呢
