### ISSUE TITLE
MongoDB集群连接报超时[Bug]

### ISSUE THREAD

**Issue by evilhy** [dataease/dataease#1734]
**DataEase 版本**
1.7.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome 97.0.4692.71（正式版本）

**Bug 描述**
MongoDB集群连接有问题，检验失败，web端报错超时，日志报错超时
ERROR i.d.s.datasource.DatasourceService 167 - Method[lambda$handleConnectionPool$0][Failed to handle datasource connection pool: clouddata]
io.dataease.exception.DataEaseException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=192.168.1.228:20000, type=UNKN
OWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
您好，我们暂时还没有复现此问题，您可以在我们的社区群里联系我们的技术支持人员远程定位处理一下，谢谢。
