### ISSUE TITLE
[Bug] ES 数据源 索引名中包含【-】导致预览数据报错

### ISSUE THREAD

**Issue by zhangchaochao-fit2cloud** [dataease/dataease#1736]
**DataEase 版本**
1.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Microsoft Edge
版本 98.0.1108.43 (官方内部版本) (64 位)

**Bug 描述**
预览es sql数据集，index中包含【-】导致预览数据报错

**Bug 重现步骤(有截图更好)**
1.![image](https://user-images.githubusercontent.com/70739359/152767488-ec531021-e7ad-482d-98b6-5b909b6e9add.png)
2.
3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下

**Comment by tjlygdx** [comment]
得这样子，加引号
SELECT * from "fit2cloud-cmp-logs"
