### ISSUE TITLE
[Bug]同一个浏览器不能同时打开多个带密码的公共链接仪表板

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#1740]
**DataEase 版本**
1.7.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
 98.0.4758.81（正式版本）

**Bug 描述**
同一个浏览器不能同时打开多个带密码的公共链接仪表板

**Bug 重现步骤(有截图更好)**
1. 准备两个仪表板，分别创建公共链接
2. 在同一浏览器演示，打开第1个仪表板的公共链接，输入密码，可以查看仪表板内容；
3. 新建浏览器标签，打开第2个仪表板的公共链接，输入密码，可以查看仪表板内容；
4. 回到第1个仪表板标签，点击浏览器页面刷新，这时需要重新输入公共链接的密码才可以访问。
5. 同样，输完第1个仪表板的密码，回到第2个仪表板，刷新页面同样出现输密码的页面。

**Comment by mfanoffice** [comment]
感谢回复，同一个浏览器播放多个仪表板 的场景就无法正常进行。后面会考虑做多个仪表板轮播的功能吗？

**Comment by BBchicken-9527** [comment]
目前没有这个规划，可以使用Revolver-Tabls这个插件来实现你说的情况，后续我们会整理出详细的文档。希望可以帮助到你

**Comment by mfanoffice** [comment]
对，我们是使用Revolver-Tabls这个插件实现轮播发现的这个问题，多个标签，播放多个 加密的公共链接，仪表板每到刷新时间就得重新输入密码 ，后续还请解决这个问题。
