### ISSUE TITLE
mongoDB校验出错

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#1745]
**DataEase 版本**
1.7.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge
版本 98.0.1108.43 (官方内部版本) (64 位)

**Bug 描述**
使用用户名和密码不同也可以效验成功，但是读取数据集时就报错了

**Bug 重现步骤(有截图更好)**
1.密码正确的
![image](https://user-images.githubusercontent.com/96223591/152941278-0146f34d-c7e2-4b66-bff4-0a03f694eb83.png)

2.
![image](https://user-images.githubusercontent.com/96223591/152941412-c77a32b2-8226-46a2-bd36-912557fd1f08.png)

3.密码填错可以校验成功，但是读取不到数据
![image](https://user-images.githubusercontent.com/96223591/152942074-08ddc44f-796f-4b13-af36-e56331bbece1.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们尽快修复。

**Comment by xuwei-fit2cloud** [comment]
v1.8.0 版本已修复，请关注新版本发布。
