### ISSUE TITLE
[Bug]DashBoard 筛选组件无法控制tab组件

### ISSUE THREAD

**Issue by mispower** [dataease/dataease#1753]
**DataEase 版本**
1.7

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
设置TAB组件以后，再选择筛选组件，筛选组件无法控制TAB组件内的视图

**Bug 重现步骤(有截图更好)**
<img width="720" alt="刷选组件无法控制tab" src="https://user-images.githubusercontent.com/3365904/153616345-c329b73c-17ee-469d-bad7-6ec2abe1af79.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，已安排处理。

**Comment by BBchicken-9527** [comment]
问题已修复，可下载下个版本体验
