### ISSUE TITLE
[Feature]类似excel的透视图功能

### ISSUE THREAD

**Issue by liujianbing214** [dataease/dataease#1764]
1. 表格现在汇总和明细表，有没有类似excel透视表或者其他BI的交叉表一样的功能开发计划？
2. 表格表头的多样式支持：例如合并表头等

**Comment by yayanpei** [comment]
感谢您的反馈，透视表格的功能已经在开发中。

**Comment by xuwei-fit2cloud** [comment]
v1.8.0 已支持，请关注新版本发布
