### ISSUE TITLE
[Bug] MongoDB数据源，新增collection后，拉取不到最新的collection

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#1767]
**DataEase 版本**
v1.7
**运行方式(安装包运行 or 源码运行 ?)**
安装包运行
**Bug 描述**
MongoDB数据源，新增collection后，拉取不到最新的collection

**Bug 重现步骤(有截图更好)**
<img width="910" alt="image" src="https://user-images.githubusercontent.com/30063018/153985958-6cade851-f16c-437c-9546-1e061f125ca7.png">
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/30063018/153985976-3541b0b2-d2d1-46b5-a452-03d2fd2e59e7.png">
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/30063018/153985987-aa4405c7-4694-4175-af43-58dd889bfed0.png">

**Comment by xuwei-fit2cloud** [comment]
收到，我们核实一下，如有问题会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.8.0 已修复，请关注新版本发布。
