### ISSUE TITLE
[Bug] 数据集 MongoDB 数据集，key 为中文的时候数据库数据集预览会报错。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#1777]
**DataEase 版本**
V1.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**Bug 描述**
数据集 MongoDB 数据集，key 为中文的时候数据库数据集预览会报错。

**Bug 重现步骤(有截图更好)**
原数据如下：
{
 "_id" : "rec2FJL3Sd",
 "血样操作人员" : "null,null",
 "试剂FL1入库批号" : "H210908",
 "pbmc接收人" : null,
 "溶血情况" : "正常",
 "血样操作日期" : ISODate("2022-01-23T16:00:00Z"),
 "试剂FL3入库批号" : "430953",
 "血样操作登记复核人" : null,
 "试剂FB1入库批号" : "2022.1.17",
 "纸质实验记录附件" : "null,null",
 "plasma产物接收人" : null,
 "确认物种类型" : true,
 "物种类型" : null,
 "血样处理非标准操作记录" : "/",
 "全血体积（mL）" : "1",
 "plasma产物编号" : "1220124001",
 "试剂FB2入库批号" : "2021.11.23",
 "血液分层情况" : "正常",
 "pbmc产物编号" : "2220124001",
 "试剂FL2入库批号" : "00121",
 "实验操作编号" : "220124001",
 "脂血情况" : "正常",
 "血样编号" : "1000814"
}
数据库数据集报错如下：
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/30063018/154029445-9b1689ac-082b-4571-8902-ab7f789c2607.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by tjlygdx** [comment]
mongo 驱动不支持中文

**Comment by eagle-du** [comment]
希望能尽早支持，等更新
