### ISSUE TITLE
[Bug]对接ES数据源，部分表读取错误

### ISSUE THREAD

**Issue by HotMancheA** [dataease/dataease#1781]
**DataEase 版本**
1.6.2

**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**
谷歌浏览器

**Bug 描述**
当读取带有数组的数据结构的时候会报错
如下这个格式
{
    "aaaa": {
        "bbbb": [
            123,
            456
        ],
        "cccc": 350
    }
}

**Bug 重现步骤(有截图更好)**
1.添加数据库数据集（es数据源）
![image](https://user-images.githubusercontent.com/45034584/154233319-775d60e9-8e8b-4352-9f9c-f15edefef2b5.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们处理一下。
