### ISSUE TITLE
[Bug] Elasticsearch 数据源，不支持数组数据

### ISSUE THREAD

**Issue by caiiansheng** [dataease/dataease#1782]
**DataEase 版本**
1.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
添加es 数据源，读取数据表的时候，当数据没有数组的时候，可以读取，有数组的表，无法读取

**Bug 重现步骤(有截图更好)**
表数据：
![image](https://user-images.githubusercontent.com/26760483/154396795-63be26b1-dc47-45f4-941d-7a59d0a2a275.png)
提示错误：
![image](https://user-images.githubusercontent.com/26760483/154396894-69e03d66-9a65-4dd8-9204-747ad0ac8c4e.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们处理一下。
