### ISSUE TITLE
项目浏览器兼容性需求建议！！请看描述，本人有兼容小示例

### ISSUE THREAD

**Issue by xrlinn** [dataease/dataease#1791]
**请描述您的需求或者改进建议.**
此项目的输入框和选择框等组件在360浏览器极速模式下，出现样式兼容问题，如图1、2所示：360浏览器显示选择框组件异常，经本人排查发现项目中的CSS inset属性存在兼容问题，目前基于项目做了部分修改兼容如图3所示，望项目基于此需求对项目中的css进行兼容调整。
![image](https://user-images.githubusercontent.com/47049300/154662259-fb76f584-7d99-46a7-b09f-9212b92858ee.png)
![image](https://user-images.githubusercontent.com/47049300/154662670-d29f23dc-ff77-451e-aea7-63bab6bd05ca.png)
![image](https://user-images.githubusercontent.com/47049300/154663149-1b3d19f1-341b-4bfa-9a94-1e54bb146a74.png)

**Comment by xuwei-fit2cloud** [comment]
非常感谢您的反馈，我们后续会对常用浏览器的兼容性问题进行处理。
