### ISSUE TITLE
[Bug]Hive数据源添加SQL数据集报错

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#1795]
**DataEase 版本**
1.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
1.数据源是Hive
2.数据集选择SQL数据集，输入SQL脚本，可以预览数据
![image](https://user-images.githubusercontent.com/82353425/154905897-22c0c41a-d502-46d5-bcee-91c74faccd6f.png)

3.点击报错之后报错
![image](https://user-images.githubusercontent.com/82353425/154905765-0aed412e-2f88-4969-ad5e-ef7163c883aa.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
Hello，受累看一下是不是hive环境停掉了

**Comment by ywhfzy** [comment]
没有停掉。。。

**Comment by pengcheng4451** [comment]
我也遇到这样的问题了，本质上是因为hive查询的字段会带上表名。dataease会在原sql外面套一个select（如：select  * from (原语句)  tmp  limit ），查询出来的字段就是 tmp.a，tmp.b 这样的。要想解决这个问题，需要添加一个额外的jdbc参数就可以了，注意前面有个问号。（如下：
?hive.resultset.use.unique.column.names=false）
![image](https://user-images.githubusercontent.com/17725612/159613984-39490aa0-aaa1-4cfd-b162-4186f20ec4a9.png)
