### ISSUE TITLE
【bug】在编辑仪表盘的时候，选择自适应画布区域，添加控件的时候不能往下拖。

### ISSUE THREAD

**Issue by hao65103940** [dataease/dataease#18]
在编辑仪表盘的时候，选择自适应画布区域，当当前画布区域占满之后，再次添加控件的时候，鼠标拉取控件往下滑动，当前画布区域并不会自适应往下拓展。必须把自适应画布区域给关掉，然后设置长宽之后，编辑区域画布才能扩大。 不知道是bug还是设计如此？

**Comment by ziyujiahao** [comment]
当前设计是这样 暂时不支持动态扩展 需要提前定义和屏幕尺寸
