### ISSUE TITLE
[Feature]仪表盘关闭默认未保存且未提醒用户注意

### ISSUE THREAD

**Issue by fitchibing** [dataease/dataease#180]
仪表盘点击关闭任何提示都没有，且默认没有保存；此处如果默认是不保存的那么关闭操作需提示用户类似“您的操作尚未保存，是否确认关闭”

**Comment by yayanpei** [comment]
非常感谢您的反馈，您的建议非常好，我们会在下个版本1.1.0中纳入该优化

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已支持

**Comment by fitchibing** [comment]
验证了一下怎么还是没有提醒

**Comment by fitchibing** [comment]
> v1.1.0-rc1 版本已支持

好像没有支持
