### ISSUE TITLE
[Bug]db2的添加sql数据集定时同步，脚本内有函数的话定时同步任务就会报错，可以预览数据

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#1805]
**DataEase 版本**
1.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
1.数据源是db2，数据集类型是sql数据集并且是定时同步，我们添加数据集脚本的时候，不写trim函数就可以正常报错，假如新增函数例如trim或者left报错的话就会报错
![image](https://user-images.githubusercontent.com/82353425/155110019-f00e956b-a8cd-4404-bf38-4c6f9c94e0cc.png)
![image](https://user-images.githubusercontent.com/82353425/155110093-bdc744ab-a3a7-4e53-a4f8-a76e1f521a78.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.8.0 版本已修复，请关注新版本。
