### ISSUE TITLE
[Bug] 上传excel状态一直是执行中

### ISSUE THREAD

**Issue by swmachine1401** [dataease/dataease#1809]
**DataEase 版本**
1.7.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
上传excel后，状态一直是执行中。
excel大概10M左右。上传后可以预览数据，点击确认后，更新信息一直是“执行中”
等待时间超过5小时，中间页没有任何报错，cpu一直也有占用

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
你好，目前我这边环境没有发现你说的问题，方便说一下数据有多少个字段并且包含什么数据类型吗

**Comment by swmachine1401** [comment]
> 你好，目前我这边环境没有发现你说的问题，方便说一下数据有多少个字段并且包含什么数据类型吗

需要我提供excel吗。24个字段，有两个计算字段

**Comment by BBchicken-9527** [comment]
如果方便的话这是最好的

**Comment by swmachine1401** [comment]
> 如果方便的话这是最好的
[x.xlsx](https://github.com/dataease/dataease/files/8123219/x.xlsx)

**Comment by BBchicken-9527** [comment]
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/84372766/155448130-452fd652-3454-4acd-97a8-3c649a9a5de8.png">
不好意思我这边确实复现不了，你可以加入交流群让协助的同学帮你看一下日志以及更细致的帮助

**Comment by swmachine1401** [comment]
> <img alt="image" width="1183" src="https://user-images.githubusercontent.com/84372766/155448404-d6d2fe41-2711-4090-a5dc-4b46d63d53bb.png">
> 
> 不好意思我这边确实复现不了，你可以加入交流群让协助的同学帮你看一下日志以及更细致的帮助
好的谢谢，我去群里问问
不过你这个是预览数据，我这边预览也是没有问题的。点击确认后，更新信息里面一直是执行中
![企业微信截图_16456812602467](https://user-images.githubusercontent.com/33212266/155464955-81138a2b-4499-49d8-b34c-980bf985a24b.png)

**Comment by BBchicken-9527** [comment]
不好意思，是我这边操作步骤问题，我现在看一下，有问题我们尽快解决

**Comment by BBchicken-9527** [comment]
不好意思，是我这边操作步骤问题，我现在看一下，有问题我们尽快解决

**Comment by BBchicken-9527** [comment]
已确定确实存在此类问题，我们将尽快修改
