### ISSUE TITLE
dataease 1.7.0存在多处引用存在安全风险的开源组件

### ISSUE THREAD

**Issue by seclab-seczone** [dataease/dataease#1820]
**DataEase 版本**
最新版1.7.0

**描述**
存在多处引用存在安全风险的开源组件

**风险说明**
1. 通过开源网安 SCA产品 SourceCheck 对dataease 最新版本1.7.0进行开源组件安全检测
2. 发现引用了 存在’超危‘，’高危‘ 安全风险漏洞的开源组件42个。
![image](https://user-images.githubusercontent.com/99455940/155512160-31afcdd1-3054-4ea4-b830-e461f7b484f9.png)

![image](https://user-images.githubusercontent.com/99455940/155512244-595fea93-3145-4d9a-ba44-2b9c5ace8932.png)

**期待的正确结果**
请及时更新存在漏洞风险的开源组件，防止存在被利用的风险。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快升级
