### ISSUE TITLE
[Bug] 新建计算字段Round保留两位数，但是部分数据还是超过两位数

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#1831]
**DataEase 版本**
1.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
1.原先的数据集有一个数据的小数点后是7，8位数字
2.我新建了计算字段，然后选择了round（x，2），保留两位点击保存之后，有些数字还是不保留2位

![image](https://user-images.githubusercontent.com/82353425/155676415-2094abd5-d905-4efa-a225-1f31e78f2f9f.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
不好意思我这边没有复现出来，如果方便的话可以说一下具体的数据结构吗？然后透露一个其中出问题的字段数值

**Comment by ywhfzy** [comment]
> 不好意思我这边没有复现出来，如果方便的话可以说一下具体的数据结构吗？然后透露一个其中出问题的字段数值

就是数值型数据，例如 140.79000000002,不过我每一个选项都有函数 VLOOKUP(A15,元数据!A14:E29,5,0)

**Comment by BBchicken-9527** [comment]
你好 我加了函数还是没有复现你可以尝试升级到最新版本看一下是否还有此类问题

**Comment by okworld26** [comment]
我也出现了这个问题。   复现的关键是:
1:  选择计算。段类型是    数值(小数)
2； 视图里面添加一个过滤条件
