### ISSUE TITLE
[Feature] 建议删除重复的索引

### ISSUE THREAD

**Issue by Rabbit-st** [dataease/dataease#1864]
**请描述您的需求或者改进建议.**
version: v1.6.1

表名：
    qrtz_blob_triggers
重复的索引：
    索引SCHED_NAME和主键重复

表名：
    qrtz_triggers
重复的索引：
    索引 IDX_QRTZ_T_STATE 和索引 IDX_QRTZ_T_NFT_ST 重复
    索引 IDX_QRTZ_T_NFT_MISFIRE 和索引 IDX_QRTZ_T_NFT_ST_MISFIRE 重复
    索引 IDX_QRTZ_T_G 和索引 IDX_QRTZ_T_N_G_STATE 重复
    索引 IDX_QRTZ_T_NFT_MISFIRE 和索引 IDX_QRTZ_T_NFT_ST_MISFIRE_GRP 重复

表名：
    qrtz_fired_triggers
重复的索引：
    索引 IDX_QRTZ_FT_TRIG_INST_NAME 和索引 IDX_QRTZ_FT_INST_JOB_REQ_RCVRY 重复

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们确认一下。
