### ISSUE TITLE
[Feature]DataEase报表字段指标多的时候不自动缩放，可通过拖动滚动条展示所有报表指标

### ISSUE THREAD

**Issue by weijiahuan** [dataease/dataease#1876]
**请描述您的需求或者改进建议.**
DataEase报表字段指标多的时候不自动缩放，可通过拖动滚动条展示所有报表指标内容
![image](https://user-images.githubusercontent.com/100816845/156485537-2ce912f5-581e-42eb-a1f1-c583fc8c4555.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们在后面版本优化一下。

**Comment by weijiahuan** [comment]
具体大概什么时间会优化版本呢，我们目前对报表的需求比较强烈，需要展示的字段指标比较多，现有的表格样式展现效果不太理想啊

**Comment by xuwei-fit2cloud** [comment]
可以使用 v1.8.0 版本 AntV 图库下的表格组件，样式中支持自适应宽度。
