### ISSUE TITLE
添加excel数据集，若有小数则数据显示为空[Bug]

### ISSUE THREAD

**Issue by baixin513** [dataease/dataease#188]
**DataEase 版本**

1.0.2
**浏览器版本**
chrome

**Bug 描述**
上传的Excel表中有带小数的数值，导入数据集后不显示

**Bug 重现步骤(有截图更好)**
1.添加excel数据集-导入excel中有带小数的数据
2.导入后显示所有数据
3.点击保存后，只有整数，带小数的数值显示为空

![image](https://user-images.githubusercontent.com/52996290/124883738-3b0b0100-e004-11eb-83b9-2dd80a0dc5a6.png)

![image](https://user-images.githubusercontent.com/52996290/124883770-41997880-e004-11eb-89b3-70a04a319710.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复

**Comment by tjlygdx** [comment]
fixed on commit d611114

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已支持
