### ISSUE TITLE
[Feature] tab组件选择视图的时候，弹框大点，支持拖拉或左右滑动也可以。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#1884]
tab组件选择视图的时候，弹框大点，支持拖拉或左右滑动也可以。
<img width="466" alt="image" src="https://user-images.githubusercontent.com/30063018/156698350-ced7f086-9f85-488d-9632-0a2a88547166.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们调整一下
