### ISSUE TITLE
[Bug]tar -zxvf 归档文件中异常的 EOF

### ISSUE THREAD

**Issue by mklzl** [dataease/dataease#1885]
**DataEase version**
    
    1.18.0 

**download link :**
      
    https://cdn0-download-offline-installer.fit2cloud.com/dataease/dataease-v1.8.0-offline.tar.gz? 
  

**review**
   
    tar -zxvf dataease-v1.8.0-offline.tar.gz
**Expect the result**
    
    Extract the normal
**Real behavior**
    
    dataease-v1.8.0-offline/.gitignore
    dataease-v1.8.0-offline/images/
    dataease-v1.8.0-offline/images/dataease:v1.8.0.tar.gz
    dataease-v1.8.0-offline/images/kettle:8.3-v1.7.tar.gz

    gzip: stdin: unexpected end of file
    tar: 归档文件中异常的 EOF
    tar: 归档文件中异常的 EOF
    tar: Error is not recoverable: exiting now

**Comment by BBchicken-9527** [comment]
你好 请确定一下是否下载完整，安装包我看了一下是没有问题的
