### ISSUE TITLE
[Bug]多层级联数据不准确

### ISSUE THREAD

**Issue by little-nine** [dataease/dataease#1887]
**DataEase 版本**
1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
源码前后端分离部署(nginx)

**浏览器版本**
chrome98.0.4758
edge96.0.1054.57

**Bug 描述**
三个图A,B,C
点击A级联B , 点击B级联C 
在点击B级联C时, A级联后B的数据就被初始化了

**Bug 重现步骤(有截图更好)**
1. 三个图A,B,C
<img width="2131" alt="1" src="https://user-images.githubusercontent.com/26848111/156958922-c7cd5257-74cd-4bf6-b89c-e0a29a83a7bf.png">
2. 点击A中某一条数据级联B
<img width="2146" alt="2" src="https://user-images.githubusercontent.com/26848111/156959031-d45a6d1b-7258-45d0-a46c-07426baab4b9.png">
3. 再点击B环形图中的一部分, 正常是级联C,结果如图,数据被初始化了,并没有根据A和B的条件过滤出C
<img width="2072" alt="3" src="https://user-images.githubusercontent.com/26848111/156959097-f0b5a448-b009-451b-8e8d-2df0bdae61df.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by little-nine** [comment]
> 

还有个问题, 瀑布图不显示合计列, 数据集是 时间+数量
<img width="2499" alt="瀑布图" src="https://user-images.githubusercontent.com/26848111/156976591-a8940d39-1945-4179-ae42-60e6faf5f6c1.png">

**Comment by BBchicken-9527** [comment]
确实有此类问题，这个我们看了一下应该是组件导致，我们会讨论一下如何解决此类问题
