### ISSUE TITLE
[Feature]以列表形式展现数据时，指标可以为空，不必一定选择记录数。

### ISSUE THREAD

**Issue by torres0212** [dataease/dataease#189]
![image](https://user-images.githubusercontent.com/33819007/124889263-7b20b280-e009-11eb-9f02-de2ec54ff422.png)
如图所示，我在用列表展现一个用户登录的情况统计时候，只想展示出用户/登录时间就足够了。
目前的版本指标这里不能为空，我只能选一个**记录数**上去，这样红框部分的内容实际上对于我的展示没有意义，希望可以优化下可以实现只展示出去红框部分的内容，谢谢！

**Comment by yayanpei** [comment]
非常感谢您的反馈，我们计划在下下个版本V1.2.0中纳入此优化。

**Comment by xuwei-fit2cloud** [comment]
v1.3.0 支持明细表可以满足上面的需求
