### ISSUE TITLE
[Bug]选项卡切换tab过滤组件失效

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#1890]
**DataEase 版本**
1.8

**Bug 描述**
仪表板加入“选项卡”组件后，添加两个tab视图，过滤组件只对选项卡中当前显示tab视图有效，切换tab选项卡后，筛选过滤失效。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
你好能详细说明一下吗，目前没有发现有此类问题

**Comment by hcff2c** [comment]
你好，第一步，我选择国家组件对tab1进行筛选，效果如下
![image](https://user-images.githubusercontent.com/101089844/157584632-1495f3d1-3c8b-4df6-9bb2-61df824928ec.png)
第二步，切换到tab2，筛选框未对tab2生效
![image](https://user-images.githubusercontent.com/101089844/157584676-d53473fa-afe6-41c3-a162-4132daf0a576.png)
第三步，返回tab1，刚刚对tab1的筛选也失效了
![image](https://user-images.githubusercontent.com/101089844/157584756-2245bb9e-561c-4960-ac9e-9abb005213b8.png)
最后展现，筛选框对整个tab组件失效

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
已经修复，下个版本进行更新即可
