### ISSUE TITLE
[Bug]仪表板分享给指定的用户之后，移动端打开报没有权限

### ISSUE THREAD

**Issue by wxcen** [dataease/dataease#1891]
**DataEase 版本**
V1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包版本

**浏览器版本**
移动端手机浏览器

**Bug 描述**
仪表板分享给指定的用户之后，移动端打开报没有权限。
在企业版的环境中，在权限管理那块，在仪表板上给对应的人员钩上查看权限后，大概则不报错了。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/40848979/157055807-4e98e549-141c-4a8a-8b29-cce411837041.png)
<img width="725" alt="image" src="https://user-images.githubusercontent.com/40848979/157055759-75336df8-9b54-4235-8a60-2c98f639394b.png">
企业版里面加上权限后，则访问不报错。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们确认一下

**Comment by xuwei-fit2cloud** [comment]
v1.9.0 版本已修复，请关注新版本发布。
