### ISSUE TITLE
[Feature]支持图表数字显示可以自定义格式化

### ISSUE THREAD

**Issue by marco-tian** [dataease/dataease#1894]
建议在样式设置中增加对图表、表格视图支持对数字类型进行千分位进行格式化显示。如下图中提示显示是正确的，但是图例数字显示未格式化。
![Xnip2022-03-08_12-24-58](https://user-images.githubusercontent.com/62366871/157166282-65fbb969-ebf9-400d-932b-03184f77ab66.png)

对日期也可以进行格式化最好了，比如数据是2022-03-01，显示的时候可以格式化为2022年3月😄

**Comment by xuwei-fit2cloud** [comment]
数值格式化的需求已经记录在需求池里了，我们会在后续版本进行开发。

**Comment by SariaCxs** [comment]
您好，我想要实现这个需求，请问这个需求是说，右侧的视图按照左侧的内容格式里的设置显示吗？
