### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by asuio** [dataease/dataease#1898]
**DataEase 版本**
v1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome

**Bug 描述**
服务数据库使用外部mysql，部分自动创建的表和视图名是小写的，而服务访问需要的是大写的

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/29577613/157387506-9f5aaa55-1a79-469e-b54f-c61252c6f07a.png)

2.
![image](https://user-images.githubusercontent.com/29577613/157387599-924c973d-3203-4db4-8181-a830646c1fab.png)

3.
![image](https://user-images.githubusercontent.com/29577613/157387744-d2daaab8-7258-4aab-8816-6c01c11ccc6a.png)

**Comment by xuwei-fit2cloud** [comment]
可以参考在线文档：
https://dataease.io/docs/faq/configuration_faq/#dataease-table-datashowdbv_auth_model-doesnt-exist
