### ISSUE TITLE
[Bug]Excel数据中包含百分比和公式，导入后数据丢失

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#190]
**DataEase 版本**
1.0.1

**浏览器版本**
91

**Bug 描述**
准备excel数据，用公式计算出一列环比，通过excel数据导入，导入预览时，百分比数据展示成了小数，确认上传后计算公式计算的百分比数据未展示

**Bug 重现步骤(有截图更好)**
1.Excel数据准备，自行计算百分比，并将数值类型设置为百分比形式，保留两位小数
2.通过数据集导入将数据导入，预览数据时，百分比形式展示的数据变成了小数
3.点击确认数据导入后，计算公式计算的数据百分比丢失
excel原始数据：
![image](https://user-images.githubusercontent.com/60059766/124896193-cdfd6880-e00f-11eb-8ede-596898900a63.png)
![image](https://user-images.githubusercontent.com/60059766/124896052-b1f9c700-e00f-11eb-9aad-b62a721ce4e8.png)
![image](https://user-images.githubusercontent.com/60059766/124896101-bc1bc580-e00f-11eb-9c8f-f568f3e3b6d9.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复

**Comment by tjlygdx** [comment]
fixed on commit  d611114

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已支持
