### ISSUE TITLE
[Feature]数据集选择按照层级返回

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#1901]
**请描述您的需求或者改进建议.**
你好，当我新建组件或者视图选择数据集时，数据集有三个层级，我选到第三层找到自己需要的数据集后，发现点错了，想返回上一级选择新的数据集，但是它直接返回第一层了，我还得重新第一层第二层再去找，想提议，如果数据集选错，返回键可以加按照层级逐次返回功能。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们已经记录。
