### ISSUE TITLE
[Bug]超级严重的BUG

### ISSUE THREAD

**Issue by kksay2010** [dataease/dataease#1903]
**DataEase 版本**1.8

**运行方式(安装包运行 or 源码运行 ?)**安装包

**浏览器版本**edge

**Bug 描述**
我2021年有100条数据，  2022年有100条数据。  我希望显示12条，从左到右，最右边是最新时间的数据

我选择升序，只显示12条，你们是从2016年第一条数据展示的。  我选择降序 结果横坐标第一个竟然是2017年最大的时间 降序排的。         

我要求只显示12条数据，从左到右  最右边是最新的数据，怎么实现？

这个问题非常非常严重！！！！

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by kksay2010** [comment]
![1111111](https://user-images.githubusercontent.com/29589474/157616462-a3421f21-6fe3-45c6-bfd7-bd669c9b490c.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，这个需求我已经记录了。
