### ISSUE TITLE
mysql 定时更新 任务获取空数据

### ISSUE THREAD

**Issue by opshongwu** [dataease/dataease#1904]
在设置 定时更新 任务获取mysql数据时候，同一时间或两个任务时间重叠的时候 都会显示执行成功，但有可能其中一个获取的数据为空，这个能否直接显示执行失败，这样就不用挨个去排查重叠的任务了？

**Comment by BBchicken-9527** [comment]
想和你先确认一下是两个数据集相同表定时任务，还是说是同一个数据集有两个有可能重叠同步的定时任务？

**Comment by opshongwu** [comment]
不同数据集之间的定时任务执行时间重叠，举例 8:00执行A任务，8:05执行B任务，由于A任务执行了6分钟才结束，导致B任务执行完后显示成功，实际获取数据为空，如果B任务能显示执行失败，对排除问题会提高效率。
同样，我把两个任务间隔拉长也不会出现此问题，由于我们服务器使用UTC时间，所以统计数据必须等到北京时间8点以后才可以执行。

**Comment by xuwei-fit2cloud** [comment]
请升级到最新的 v1.18.4 版本。
