### ISSUE TITLE
[Feature]建议自适应和自定义分辨率都支持

### ISSUE THREAD

**Issue by kksay2010** [dataease/dataease#1905]
你们不支持画布和视图，横向、纵向自适应扩展。
换句话说，购买商业版的客户大部分锁死在10:9分辨率的大屏上，如果一旦有客户是横屏或者竖屏，你们的BI就无法满足，到时候会取消购买商业版的计划。

**Comment by kksay2010** [comment]
> 你们不支持画布和视图，横向、纵向自适应扩展。 换句话说，购买商业版的客户大部分锁死在10:9分辨率的大屏上，如果一旦有客户是特殊比例横屏或者竖屏，你们的BI就无法满足，到时候会取消购买商业版的计划。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，其实屏幕的自适应以及自定义分辨率，都在我们的需求池内，我们也进行过讨论，后续会进行相关支持。
