### ISSUE TITLE
[Feature]替换EXCEL数据源后增加自动刷新功能

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#1906]
**请描述您的需求或者改进建议.**
我第一次导入Excel数据源时，小数数值自动被辨认为时间类型，我没有更正然后点了确认。
![image](https://user-images.githubusercontent.com/101089844/157626475-f5d7c58c-1b06-4b25-9c77-9defd8f419e0.png)
确认后我发现展示出错，我想替换excel来更新一下数据
![image](https://user-images.githubusercontent.com/101089844/157626658-6722372d-3911-4185-bcc1-038111563415.png)
编辑excel，替换数据集，然后将这一列的数据类型选为数值（小数），
![image](https://user-images.githubusercontent.com/101089844/157626824-7be23e7c-3933-4e69-9a02-100cdf09c378.png)
确认后页面展示还是错误展示类型，误以为数据源更新替换无效
![image](https://user-images.githubusercontent.com/101089844/157626933-b64ab4bc-60d8-4c5c-91f7-f9129f4f2548.png)
刷新页面重新进入我导入的数据集，发现其实已经更新替换成功
![image](https://user-images.githubusercontent.com/101089844/157627174-46921b75-812d-4cfb-b3a2-a981121f080c.png)
在此想提议，可否在替换导入数据集后，加一个自动刷新的功能

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下。
