### ISSUE TITLE
[Bug]透视图钻取后列位置改变

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#1908]
**Bug 重现步骤(有截图更好)**
1.钻取前，省市数据列在最左侧
![image](https://user-images.githubusercontent.com/101089844/157632412-58095274-a18a-4955-9dbd-63d1e0848333.png)
2.按照省市钻取后，省市列跑到了最右侧
![image](https://user-images.githubusercontent.com/101089844/157632523-57a71167-8a2d-4cea-98ea-2d5cdb66d54d.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先内部讨论一下必要性
