### ISSUE TITLE
[Question]仪表盘是否支持实时更新数据

### ISSUE THREAD

**Issue by asuio** [dataease/dataease#1909]
**请描述您的问题.**
我添加了API数据源，并在数据集中设置了每10秒刷新一次，在仪表盘中使用了这个数据集，无论是预览的仪表盘还是分享的仪表盘，都不能定时刷新数据，刷新页面，数据会改变。想问一下现在的版本（v1.8.0）是否支持实时刷新？如果不支持，后续会有支持计划吗？

**Comment by xuwei-fit2cloud** [comment]
仪表板默认刷新时间是5分钟刷新一次，也可以在仪表板里对仪表板的刷新频率进行设置，最小支持秒级。
![图片](https://user-images.githubusercontent.com/1892127/158114308-255808eb-80ca-4612-bce9-bf1e7a089310.png)

**Comment by asuio** [comment]
感谢感谢
