### ISSUE TITLE
[Bug]OIDC提示Incorrect directUrl

### ISSUE THREAD

**Issue by Fit2CloundGhh** [dataease/dataease#1912]
**DataEase 版本**
V1.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
98.0.4758.109

**Bug 描述**
使用OIDC对接keycloak 提示Incorrect directurl，但是同样的keycloak配置信息配置在metersphere可以单点登录成功，怀疑是接口auth的时候state参数传递错误

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/92966838/158089219-940bc811-f778-463d-9fb1-a96badd155a9.png)
这张图片是在metersphere平台上进行OIDC登录时，重定向到keycloak校验界面，发现在调用openid-connect/auth接口的时候state参数有数值
2.
![image](https://user-images.githubusercontent.com/92966838/158089318-3e4a4fa3-6e7d-4190-8312-9d60214a5420.png)
而dataease上state参数获取有问题？变量值获取问题？
3.
<img width="665" alt="image" src="https://user-images.githubusercontent.com/92966838/158089392-5549129c-90b9-46ee-96ec-371353cc4ec5.png">
其次，在DE界面准备编辑OIDC信息的时候，默认值是metersphere的模板  。。。

**Comment by xuwei-fit2cloud** [comment]
检查一下 keycloak de realm里对应的 client，Valid Redirect URIs 是否正确

**Comment by Fit2CloundGhh** [comment]
发现了，是我自己的我的问题，在OIDC配置中的redirect Url中的 sso/callBack 写成 sso/callback

**Comment by xuwei-fit2cloud** [comment]
问题已解决。
