### ISSUE TITLE
[Feature]多个紧急需求，详细查看文档

### ISSUE THREAD

**Issue by kksay2010** [dataease/dataease#1913]
我之前发过你们两份文档，署名石理恒的。只要不是最新日期，3.14的，可以略过，查看我此份文档！

1、横轴和纵轴分别使用其他字段排序或者使用数据集语句排序结果.（注意是横轴和纵轴都可以设置，或者使用原语句）
2、只显示N条排序问题
3、图例和图表的间距可以更改，或者设置近一些，你们的太远了。/4、
[dataease-客户需求V3-石理恒20220314.docx](https://github.com/dataease/dataease/files/8241297/dataease-.V3-.20220314.docx)
evnt透视表，基数（奇数）行背景色可以调节问题

**Comment by kksay2010** [comment]
> 我之前发过你们两份文档，署名石理恒的。只要不是最新日期，3.14的，可以略过，查看我此份文档！
> 
> 1、横轴和纵轴分别使用其他字段排序或者使用数据集语句排序结果.（注意是横轴和纵轴都可以设置，或者使用原语句）
 2、只显示N条排序问题 
3、图例和图表的间距可以更改，或者设置近一些，你们的太远了。
4、 evnt透视表，基数（奇数）行背景色可以调节问题


[Uploading dataease-客户需求V3-石理恒20220314.docx…]()

**Comment by yayanpei** [comment]
感谢您的反馈，需求我们先记录并评估一下。
