### ISSUE TITLE
[Bug]1.8.0 release版本编译无法实现组件拖拽

### ISSUE THREAD

**Issue by shenruizong** [dataease/dataease#1915]
**DataEase 版本**
1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
·源码运行

**浏览器版本**
Chrome 99.0.4844.51

**Bug 描述**
1.8.0 release版本无法实现组件拖拽

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by shenruizong** [comment]
我直接对frontend进行npm run serve后发现过滤组件无法拖拽切图标中的拖拽也无效

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by eveningqn** [comment]
![test2](https://user-images.githubusercontent.com/34156779/160735622-65df21ef-d24e-4fce-8f19-77fd92703252.gif)
1.8版本,源码编译运行，同样无法拖曳图标。
但是打开chrome devTools后可以正常拖曳。
