### ISSUE TITLE
[Question]关于DataEase的一些疑问。

### ISSUE THREAD

**Issue by vzrs** [dataease/dataease#1916]
我是首次尝试使用这款开源产品，可能对该产品的定位不是很明确，有提的不妥的问题请谅解。
1、DataEase抓取的数据能否再对外提供查询接口，或者能否通过直连Apache Doris查询这些数据？
2、DataEase是否提供基于分布式架构的部署方式，对硬件有什么要求（例如是否需要万兆交换环境）？
3、与第1个问题比较相似。DataEase是否会向大数据平台发展？提供一些类似总线服务的功能？

**Comment by xuwei-fit2cloud** [comment]
你好，关于你的问题，可以参考一下：
1. DataEase本身支持Rest API，可以通过接口来查询数据（受权限控制）；定时同步模式的数据集数据，都会存放在Doris中，在运行DataEase时，可以将Doris组件的访问端口暴露出来，就可以直接连接Doris来查询数据，但目前Doris中的表名是以UUID命名的，并不具备良好的可读性
2. 目前DataEase在部署方面，要求DataEase本身和Kettle运行在一台服务器上（如不需使用Excel数据集，则可以分开部署），其他组件如Doris和MySQL，可以部署在其他地方；集群方式的支持会在近期版本进行完善；
3. DataEase主要还是面向数据的展示和分析，短期内还不会向其他方向发展

**Comment by vzrs** [comment]
非常感谢您！
