### ISSUE TITLE
mongodb时间筛选报错[Bug]

### ISSUE THREAD

**Issue by evilhy** [dataease/dataease#1918]
**DataEase 版本**
 dataease-v1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 99.0.4844.51（正式版本） （64 位）

**Bug 描述**
mongodb 时间过滤器报错

**Bug 重现步骤(有截图更好)**
1.
![d4a4c4975704ff6afa2b6c0dc7c7826](https://user-images.githubusercontent.com/49869612/158321605-518e8281-4003-4402-beb4-23c2c5a124d8.png)

2.
![image](https://user-images.githubusercontent.com/49869612/158321652-78d5f8b6-ab01-4864-b684-37406c06f397.png)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下。
