### ISSUE TITLE
[Bug]1.8.0 release版本-PostgreSQL数据源使用非public schemas时部分图表数据查询报错

### ISSUE THREAD

**Issue by iguanjing** [dataease/dataease#1919]
**DataEase 版本**
v1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
源码编译包运行

**浏览器版本**
Microsoft Edge
版本 96.0.1054.62 (官方内部版本) (x86_64)

**Bug 描述**
数据源使用PostgreSQL12、schamas名称为app、ods等（非public），例如：dws等；仪表板数据图表配置部分图表报错无法展示数据，例如：指标卡、仪表盘、水波图；

报错内容如下：
SQL 错误: ERROR: relation "t_test_data" does not exist 位置：117

**Bug 重现步骤(有截图更好)**
1. PostgreSQL数据源，schemas创建名称为app，添加表数据
2. 添加数据源、数据集
3. 制作仪表板，选择指标卡，报错；

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by iguanjing** [comment]
@BBchicken-9527 非public schema下数据集添加关联数据集时同样有该问题，希望一并关注下

**Comment by BBchicken-9527** [comment]
好的，我们一并处理一下

**Comment by BBchicken-9527** [comment]
已修复可升级最新版本体验

**Comment by you10906** [comment]
@BBchicken-9527  我用的1.9.1版本，存在同样的问题
