### ISSUE TITLE
[Feature]数据集展示字段内容过长截断问题

### ISSUE THREAD

**Issue by keithwei0120** [dataease/dataease#1928]
当前数据集预览时，若表格的某个字段内容过长，会自动截断，且通过调整列宽也无法查看完整数据

建议：
1、鼠标悬浮（或点击）在字段内容上时弹出气泡框展示完整数据
2、支持调整行宽

**Comment by xuwei-fit2cloud** [comment]
v1.8.0版本中，antv库里的表格可以支持设置宽度，且支持根据内容自适应

**Comment by keithwei0120** [comment]
![企业微信截图_16478297175452](https://user-images.githubusercontent.com/72774206/159198028-2605ad47-5eeb-45cb-b15b-c43a8bd4f738.png)
那如果是这种调整了列宽也没法看到完整数据的该怎么办呢？字段多，且字段值较长的话，总要有个方法能够看完整数据的吧

**Comment by xuwei-fit2cloud** [comment]
在表格的样式里，可以设置宽度自适应
![图片](https://user-images.githubusercontent.com/1892127/160046902-73427fc6-d2f9-4b7a-9aef-5d86b80319c1.png)
遇到长度过长的字段，会出现横向滚动条，如下图
![图片](https://user-images.githubusercontent.com/1892127/160046979-a696dfcb-cd97-4f00-b2e2-3fbf124e834d.png)

**Comment by keithwei0120** [comment]
好的，感谢您的回复
