### ISSUE TITLE
[Feature]时间序列的数据增加进来后默认支持按照时间排序

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#193]
**请描述您的需求或者改进建议.**
纬度为月份的时间序列的数据在制作视图时，默认按照时间排序，当前是混乱的，也没有按照数据的顺序，也没有按照时间的顺序
![image](https://user-images.githubusercontent.com/60059766/125041598-820ff980-e0cb-11eb-9386-5216e9acfaf8.png)

**Comment by yayanpei** [comment]
非常感谢您的反馈，您的建议非常好，我们会安排在后期版本迭代中实现该需求。

**Comment by xuwei-fit2cloud** [comment]
v1.3.0 版本已支持排序。
