### ISSUE TITLE
[Bug] 移动端提示权限不足

### ISSUE THREAD

**Issue by swmachine1401** [dataease/dataease#1935]
**DataEase 版本**
1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
谷歌

**Bug 描述**
admin账号将仪表盘分享给其他账号，该账号在web端可以正常访问分享的仪表盘，切换到移动端打开相同的仪表盘会返回Subject does not have permission[PANNEL_LEVEL_VIEW:PANEL:fe084982-bba8-4990-8bc6-83ccbd62aad8]
源码未修改

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/33212266/158981929-b1870120-56cc-42c1-b096-ce291ab450f7.png)

**Comment by BBchicken-9527** [comment]
感谢你的反馈，我们会尽快处理

**Comment by xuwei-fit2cloud** [comment]
v1.9.0 版本已修复，请下载最新版本。
