### ISSUE TITLE
[Bug] API 数据源字段类型设为数值时，排序规则仍按文本顺序排序

### ISSUE THREAD

**Issue by wangzhen-fit2cloud** [dataease/dataease#1937]
**DataEase 版本**
v1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
DEMO 环境测试

**浏览器版本**
Edge 版本 99.0.1150.39 (正式版本) (64 位)

**Bug 描述**
对于 API 数据源中的原始类型为文本，实际内容为数值的字段，设置其类型为数值。使用排序规则对该字段进行排序时，未按照数值大小进行排序，而是使用了文本顺序排序。

**Bug 重现步骤(有截图更好)**
添加 API 数据源，获取类似下图的数据
![image](https://user-images.githubusercontent.com/27671436/159102932-2e9637ca-6e68-4206-9be8-8a60de38f1b1.png)
使用该数据源添加数据集，并标记 a 字段类型为数值
创建仪表盘并添加视图，以明细表为例，使用 a 字段进行排序。期望顺序为 `1, 2, 4, 8, 9, 11, 12, 123`
实际顺序为
![image](https://user-images.githubusercontent.com/27671436/159102992-4ae182bc-37b8-49ad-890b-093938c70935.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快处理

**Comment by xuwei-fit2cloud** [comment]
v1.9.0 版本已修复，请下载最新版本。
