### ISSUE TITLE
[Feature]建议标题字段增加鼠标移动上去的提示

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1938]
**请描述您的需求或者改进建议.**
如下图，标题字段过长无法显示全，是否增加一个鼠标移动上去的标题显示，可以将完整的标题显示出来。
<img width="475" alt="image" src="https://user-images.githubusercontent.com/48945409/159104121-eded96fd-442b-4d07-a8a0-22602ac6a0c1.png">

**Comment by xuwei-fit2cloud** [comment]
v1.9.0版本已支持。
