### ISSUE TITLE
[Feature]仪表盘添加背景框时能支持透明度设置

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#194]
**请描述您的需求或者改进建议.**
仪表盘添加背景框时能支持透明度设置
![image](https://user-images.githubusercontent.com/60059766/125044443-8b4e9580-e0ce-11eb-98a8-120eea9e8689.png)

**Comment by yayanpei** [comment]
非常感谢您的反馈，我们规划在下下个版本V1.2.0中纳入此优化。

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 已支持
