### ISSUE TITLE
[Feature]明细表建议可以对多个列设置合并表头

### ISSUE THREAD

**Issue by asuio** [dataease/dataease#1941]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/29577613/159209964-3080e8cb-3bf8-478c-818e-2103841d4f07.png)
如图，在明细表中，abcdefgh为列名，可以对cde和fgh分别设置合并表头，能更方便的展示数据

**Comment by yayanpei** [comment]
感谢反馈，您的需求已收录。

**Comment by kksay2010** [comment]
me too 。特别是anvt的表格（因为你们的eachrt的表格不支持联动）
