### ISSUE TITLE
[Bug] 分享仪表板的 URL 后面可随意更改“user”的值，存在安全

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#1944]
**DataEase 版本**
v1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌最新

**Bug 描述**
分享的仪表板的URL，最后面“user”的信息可随意更改，导致权限变更，造成安全隐患。
![image](https://user-images.githubusercontent.com/40846859/159237702-5d4e1189-d9ed-490a-a1ba-b1e665e00709.png)

**Bug 重现步骤(有截图更好)**
1.分享仪表板url
2.使用无痕浏览器浏览
3.修改地址栏中“user”的值

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.9.0 版本已修复，请下载最新版本。
