### ISSUE TITLE
[Bug]词云图联动与跳转失效

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#1949]
**DataEase 版本**
1.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌

**Bug 描述**
1.相互设置了两个视图的联动，一个是柱状图一个词云图，点击词云图的时候无法联动柱状图，但是点击柱状图的时候可以联动词云图，并且词云图设置了跳转也没起到作用。
2.
![image](https://user-images.githubusercontent.com/82353425/159415698-a54119b8-8bfd-4f4b-a411-c35205439dee.png)
3.
![image](https://user-images.githubusercontent.com/82353425/159415715-7ae612e2-4a32-42aa-8ba6-3ff22d092794.png)
4.
![image](https://user-images.githubusercontent.com/82353425/159415771-d84ac99a-236a-4d4e-9c82-eac9aad51214.png)
5.
![image](https://user-images.githubusercontent.com/82353425/159415801-cc2302ad-5e5d-4a7e-a258-0f0980ff2acc.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前词云图是不支持主动的关联和跳转的。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，该问题已记录。
