### ISSUE TITLE
UNION ALL 连表查询MySQL数据集

### ISSUE THREAD

**Issue by opshongwu** [dataease/dataease#1952]
**请描述您的问题.**
MySQL数据集，定时活期数据。
UNION ALL的语法貌似是UNION，all 没生效。
直连方式没有这个问题，定时获取的数据存在这个问题？

**Comment by xuwei-fit2cloud** [comment]
数据同步后做了去重处理，我们讨论一下是否将去重取消掉。

**Comment by opshongwu** [comment]
请问，数据同步后做了去重处理，这个有了结论吗？是否把需要去重的选择让用户自行选择？
