### ISSUE TITLE
[Feature]API 数据源支持获取非数组类型的值

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1953]
**请描述您的需求或者改进建议.**

API 数据源是否可以新增支持获取非数组类型的值，例如如下 GitHub 数据中项目的一些信息。或者单独拿某一字段的。
<img width="959" alt="image" src="https://user-images.githubusercontent.com/48945409/159515167-aea29e5e-839a-4af7-ba20-6c4150aedc83.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，该需求已记录
