### ISSUE TITLE
[Bug]Mysql 定时同步 union all函数失效问题

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#1955]
**DataEase 版本**
1.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌

**Bug 描述**
1.两张sql表如图所示
![image](https://user-images.githubusercontent.com/82353425/159631139-2587f3ec-5738-4a01-a39a-36b2b422c6a5.png)
![image](https://user-images.githubusercontent.com/82353425/159631156-a90ca851-fc58-4044-9423-f8f3d0c76c0d.png)
2.当我写select * from test1 union all select * from test2,数据预览如图
![image](https://user-images.githubusercontent.com/82353425/159631271-abcd0a93-22e7-4cc5-b851-245ea918ced3.png)
3.点击立即更新之后，数据保存如图
![image](https://user-images.githubusercontent.com/82353425/159631321-7e25865b-6491-4037-a1ea-a700f328b48c.png)
4.少了几个数字，这个跟union函数的结果一样，定时同步的union all 与union函数结果一致
**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
数据同步后做了去重处理，我们讨论一下是否将去重取消掉。
