### ISSUE TITLE
excel的判断单元是否为日期格式

### ISSUE THREAD

**Issue by zouconghui** [dataease/dataease#1961]
( (14 <= format && format <= 17) || format == 20 || format == 22 || format == 31 || format == 35 || format == 45 || format == 46 || format == 47 || (57 <= format && format <= 59)
                    || (175 < format && format < 178) || (182 <= format && format <= 196) || (210 <= format && format <= 213) || (208 == format))
参照的标准是出自哪里

**Comment by xuwei-fit2cloud** [comment]
我们是通过 POI SAX事件读取数据的，所以不能使用 DateUtil.isCellDateFormatted(Cell cell) 来判断单元的类型。目前的判断是我们对自己和用户遇到的日期类型逐步添加上的判断规则。
