### ISSUE TITLE
[Bug]Mysql 数据集定时同步，数据库的表新增字段后预览数据报错

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#1962]
**DataEase 版本**
1.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌

**Bug 描述**
1.首先我们在dataease里面新建一个sql数据集，类型是定时同步，点击保存之后如图所示
![image](https://user-images.githubusercontent.com/82353425/159866567-1cbbc548-d48e-48c1-8e04-4c8774fff17a.png)
2.数据库的表字段如下
![image](https://user-images.githubusercontent.com/82353425/159866618-6ff15435-177f-43ae-a034-f4a89f5b31b2.png)
3.我们在表里面新增一个字段，例如xx
![image](https://user-images.githubusercontent.com/82353425/159866710-881e29e5-66f6-46fc-b9e1-e43cd1d489b0.png)
4.回到dataease里面同步字段，确实新增了
![image](https://user-images.githubusercontent.com/82353425/159866785-27bc04e0-f407-4cef-85b5-2646264a883b.png)
5.但是点击了数据预览就会报错
![image](https://user-images.githubusercontent.com/82353425/159866873-bc871116-8a6d-4960-8cd6-c5916146423e.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
这个目前确实是这样处理的，在出错的提示信息里也有明确提示因为字段有所变化导致同步失败。
关于数据集字段变化的处理，我们内部再讨论一下。
