### ISSUE TITLE
[Bug]AntV折线图不显示纵轴时标签显示不全

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1965]
**DataEase 版本**
v1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 99

**Bug 描述**
AntV折线图不显示纵轴时标签显示不全

**Bug 重现步骤(有截图更好)**
不显示纵轴时，自动给的高度不够，导致最大数字的标签被遮挡。
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/48945409/160088478-6c74d076-7d76-42a2-baa0-b95a0403e06e.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们确认一下
