### ISSUE TITLE
[Feature]视图横轴旋转超过一定角度建议将字序改为从上到下，提高可读性

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#1974]
**请描述您的需求或者改进建议.**
视图横轴旋转超过一定角度建议将字序改为从上到下，提高可读性

![image](https://user-images.githubusercontent.com/101089844/160318775-12efd5f7-bd0f-4ca7-923b-0e75bb8397f8.png)

真正使用过程中有可能为了展示坐标轴标签而旋转字体，但是旋转角度过大就降低了可读体验

**Comment by yayanpei** [comment]
感谢您的反馈，旋转是用于调整角度，便于更好的显示内容，对内容是不做改变的；建议您在使用过程中将角度调整为小于90度，以方便阅读。
