### ISSUE TITLE
[Question]context-path便捷修改

### ISSUE THREAD

**Issue by asuio** [dataease/dataease#1978]
**请描述您的问题.**
现在是否支持自定义前后端的context-path，方便nginx的代理

**Comment by xuwei-fit2cloud** [comment]
如果前后端分离部署，则可以修改前端 publicPath 和 后端 context-path
![图片](https://user-images.githubusercontent.com/1892127/160559741-cc0971b5-6389-4571-af17-946be5edcd03.png)
![图片](https://user-images.githubusercontent.com/1892127/160559767-80d213c5-dc8a-4b1e-8cfe-5b3960d00a96.png)

如果不是分离部署，那就只改后台的context-path

**Comment by asuio** [comment]
后续会考虑在离线版中设置配置项吗？前后端统一的context-path

**Comment by xuwei-fit2cloud** [comment]
目前我们都是前后端统一部署的，暂时还不会做配置项。
