### ISSUE TITLE
[Bug]仪表板导出为PDF后边框样式有问题

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#1985]
**DataEase 版本**
v1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 99

**Bug 描述**
仪表板加了边框后再导出 PDF，导出的样式与仪表板上不一致。

**Bug 重现步骤(有截图更好)**
<img width="2904" alt="image" src="https://user-images.githubusercontent.com/48945409/160514713-847271fb-4047-4dae-b53d-981f39c14793.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下

**Comment by BBchicken-9527** [comment]
已修复，可以更新1.9.0体验
