### ISSUE TITLE
[Feature] 纬度在列中选择

### ISSUE THREAD

**Issue by lvxiaohu** [dataease/dataease#199]
**请描述您的需求或者改进建议.**
试图维度是否可以在列上进行选择
例如：
![image](https://user-images.githubusercontent.com/29087369/125054229-94446480-e0d8-11eb-9b0d-801e6a564b50.png)

dataease的效果：
![image](https://user-images.githubusercontent.com/29087369/125054471-d1a8f200-e0d8-11eb-8da3-601c9da85c68.png)

期望效果：
![image](https://user-images.githubusercontent.com/29087369/125054406-c05fe580-e0d8-11eb-9a0e-c2196e547466.png)

**Comment by yayanpei** [comment]
感谢您的反馈，您的建议是我们产品优化和改进的方向。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
