### ISSUE TITLE
[Bug] mongodb 数据库数据集，字段管理调整维度为指标，切换字段类型后，视图侧聚合报错

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#1992]
**DataEase 版本**
v1.8.0
<img width="863" alt="image" src="https://user-images.githubusercontent.com/30063018/160539866-6334f723-52da-4602-852e-d4ce337adbf4.png">
<img width="585" alt="image" src="https://user-images.githubusercontent.com/30063018/160539896-1f7a00df-f7e0-4559-b8d8-fd6bf14b4aec.png">
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/30063018/160539999-64743f62-431c-43f0-b124-5dc675161e17.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。
