### ISSUE TITLE
个人信息输入框太长，“个人信息”没有使用国际化显示

### ISSUE THREAD

**Issue by liufei20151013** [dataease/dataease#20]
<img width="1439" alt="图片" src="https://user-images.githubusercontent.com/15103510/123389890-ec557400-d5cc-11eb-9e5d-30e5e516d451.png">

**Comment by fit2cloud-chenyw** [comment]
fixed on commit 12807ebac2b7963566f98ea918e98777707181fe

**Comment by xuwei-fit2cloud** [comment]
已修复，请等待下一个版本 v1.0.1

**Comment by xuwei-fit2cloud** [comment]
v1.0.1 已发布
