### ISSUE TITLE
[Bug]仪表板-数值区间组件上边框被遮挡

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#2004]
**DataEase 版本**
1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge
版本 99.0.1150.55 (正式版本) (64 位)

**Bug 描述**
数值区间组件在矩阵模式下，仪表板样式设置有间隙情况下，上边框被遮挡

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/96223591/160752579-36642454-a2f2-4253-b19a-d4f1c214295e.png)

2.
3.

**Comment by xuwei-fit2cloud** [comment]
v1.9.0 已修复，请等待新版本发布。

**Comment by xuwei-fit2cloud** [comment]
请下载v1.9.0 版本
