### ISSUE TITLE
[Bug]数值型维度排序不正确

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2005]
**DataEase 版本**
v1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 99

**Bug 描述**
数值型维度排序不正确

**Bug 重现步骤(有截图更好)**
<img width="1749" alt="image" src="https://user-images.githubusercontent.com/48945409/160802945-f922ea82-a23b-42d6-a8f6-46dd2c26a2d8.png">

**Comment by xuwei-fit2cloud** [comment]
v1.9.0 版本已修复，请等待新版本发布。
