### ISSUE TITLE
[Bug]用户仪表板A保存为模板a，然后从模板a新建仪表板B，改了B，A也跟着变

### ISSUE THREAD

**Issue by xyd113** [dataease/dataease#2007]
**DataEase 版本**
v1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 版本 98.0.4758.80（正式版本） (x86_64)

**Bug 描述**
用户仪表板A保存为模板a，然后从模板a新建仪表板B，改了B，A也跟着变。

**Bug 重现步骤(有截图更好)**
1. 新建并编辑一个仪表板A并保存；
2. 将A保存为模板a；
3. 新建仪表板-复用模板，选择模板a，新建仪表板B；
4. 修改仪表板B中的数据源，并保存；
5. 查看仪表板A。

仪表板A和B应该是独立的两个仪表板，修改其中一个不影响另一个。而实际上，步骤5看到仪表板A变成和仪表板B一样了。

**Comment by xuwei-fit2cloud** [comment]
1.8及之前的版本确实是这样的，因为在仪表板模板中记录的是视图的ID。从下个版本1.9开始，仪表板模板这块做了重构，基于模板创建的仪表板里面包含的视图是独立的视图，不会再有这个问题。

**Comment by xuwei-fit2cloud** [comment]
请使用v1.9版本
