### ISSUE TITLE
[Bug] 先选定时同步后选数据源类型

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2008]
**DataEase 版本**
1.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌

**Bug 描述**
1.当我先选定时同步模式的时候，再去选数据源，可以选择到不支持定时同步的数据源，例如clickhouse
这是正常情况下
![image](https://user-images.githubusercontent.com/82353425/160809492-ed2ed8f4-d1c1-41ba-a5ea-1d60645a39c5.png)
先选定时同步之后还能选ck,能不能再做个判断嘞
![image](https://user-images.githubusercontent.com/82353425/160809598-8211fd6d-2b0a-4c77-a2fc-1167be1aa1f9.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下

**Comment by xuwei-fit2cloud** [comment]
v1.9.0 版本已修复，请下载最新版本
