### ISSUE TITLE
[Bug]组件的自定义控制范围无效

### ISSUE THREAD

**Issue by xyd113** [dataease/dataease#2009]
**DataEase 版本**
v1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 版本 98.0.4758.80（正式版本） (x86_64)

**Bug 描述**
组件的自定义控制范围无效

**Bug 重现步骤(有截图更好)**
1. 添加一个字符串下拉组件X；
2. 按组件选择-选择组件A-将字段project_name拖入右侧文本框；
3. 按组件选择-选择组件B-将字段project_name拖入右侧文本框；
4. 按组件选择-选择组件C-将字段project_name拖入右侧文本框；
5. 不勾选自定义控制范围，点确定；
6. 下拉组件X的实际控制效果：A、B、C都会被X控制；

1. 添加一个字符串下拉组件Y；
2. 按组件选择-选择组件A-将字段project_name拖入右侧文本框；
3. 勾选自定义控制范围，并选择控制范围A、B、C，点确定；
4. 下拉组件Y的实际控制效果：A被Y控制，B、C没反应；

![image](https://user-images.githubusercontent.com/39815896/160808420-ba15984a-ecca-4bf2-a35a-5ad05911d751.png)
![image](https://user-images.githubusercontent.com/39815896/160808963-131c114a-1a97-4663-893d-37bb410baac1.png)

**Comment by xuwei-fit2cloud** [comment]
这个确实是这样的，因为传入的过滤字段其实是其中一个视图（对应数据集）的字段，这个字段本身并不能影响到其他视图（基于其他数据集制作的视图）。过滤真正产生作用，是根据数据集的字段来实现的，如果页面上其他视图和过滤组件选择的视图是同一个数据集，那默认情况下该过滤组件也可以影响这些视图。
