### ISSUE TITLE
[Bug]组织权限管理

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#2017]
组织管理员可以对其他组织成员的权限进行修改，当前组织管理员可以对其他组织成员跨组织赋权

**Comment by xuwei-fit2cloud** [comment]
目前权限设计确实是没有考虑这个层面，近期内版本还不会做相应支持，我们会先仔细考虑如何加入该功能。

**Comment by LinuxLeader** [comment]
正常来讲各个组织的权限应该是相互独立的吧，组织管理员只能管理组织内成员的权限，这样好实现各部门人员权限划分。

**Comment by xuwei-fit2cloud** [comment]
是的，当前的设计并没有实现租户之间的资源及权限隔离，如果要支持的话影响面比较大，需要好好考虑一下细节问题。
