### ISSUE TITLE
[Feature]文本过滤组件【文本下拉】增加手输模糊匹配功能

### ISSUE THREAD

**Issue by xyd113** [dataease/dataease#2028]
**请描述您的需求或者改进建议.**
目前的文本过滤组件【文本下拉】只支持下拉选择，当数据过多的时候，一个一个查找很慢，希望能添加手动输入模糊匹配的功能，类似于【文本列表】那样。
我为啥不干脆就用【文本列表】算了呢？因为相比较而言【文本下拉】更简洁常规一些，所以希望能给【文本下拉】添加手动输入模糊匹配的功能。

**Comment by xuwei-fit2cloud** [comment]
收到反馈，我们会在1.10版本中加入支持。
