### ISSUE TITLE
手机使用自带浏览器访问共享连接，表格数据量不足时，出现表格背景为黑色

### ISSUE THREAD

**Issue by whmhm** [dataease/dataease#2030]
**DataEase 版本**
 1.8

**运行方式(安装包运行 or 源码运行 ?)**
1】源码运行
2】体验环境

**浏览器版本**
华为自带浏览器；钉钉中访问共享连接；

**Bug 描述**
手机使用自带浏览器访问共享连接，表格数据量不足时，出现表格背景为黑色

**Bug 重现步骤(有截图更好)**
1. 创建视图，使用视图使用表格类型。
2. 选择数据量少的数据集，使用手机布局，并将表格撑满视口。
3. 保存仪表盘并创建连接
4.使用华为（p30 pro）,荣耀v30pro手机自带浏览器访问共享连接就可以复现问题   (tips:苹果12，小米11 的自带浏览器没问题)。
5.使用qq或者钉钉打开连接除了苹果都有问题。
![190A6F32EE6C8E8B268FC86721692883](https://user-images.githubusercontent.com/54785004/161363683-eda514b5-b67b-4ff4-b7d7-454f425ac33d.jpg)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，确实有这个问题，我们尽量处理一下。

**Comment by phsy** [comment]
这个问题解决了没？

**Comment by whmhm** [comment]
已解决


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月20日(周日) 上午9:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dataease/dataease] 手机使用自带浏览器访问共享连接，表格数据量不足时，出现表格背景为黑色 (Issue #2030)




 
这个问题解决了没？
 
&mdash;
