### ISSUE TITLE
[Bug] 报错：OIDC用户缺失【preferred_username】,请联系管理

### ISSUE THREAD

**Issue by GitProBo** [dataease/dataease#2031]
**DataEase 版本**
v1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 99.0.4844.84（正式版本） (x86_64)

**Bug 描述**
使用oidc并配置好之后，从Provider返回用户信息，提示“OIDC用户缺失【preferred_username】,请联系管理员”

**Bug 重现步骤(有截图更好)**
1.在dataease系统中，系统管理->系统参数->OIDC配置
2.在OIDC-Provider侧配置user信息
3.在dataease系统中, 登录页面，选择OIDC，并跳转到sso登录页面， 输入账号密码成功登录后返回dataease页面时出现错误
![WX20220402-110952](https://user-images.githubusercontent.com/18132900/161363605-e73642ae-8022-48d6-807e-afd75fe6e9bc.png)

**Comment by xuwei-fit2cloud** [comment]
在 v1.9.0 版本中支持属性映射，请等待新版本发布。

**Comment by xuwei-fit2cloud** [comment]
v1.9.0 版本支持oidc属性映射，可以尝试一下。
