### ISSUE TITLE
[Bug]文本过滤组件中的搜索框搜到的字段，拖拽后发生变化

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#2037]
**DataEase 版本**
1.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome最新

**Bug 描述**

文本下拉组件、文本列表组件、文本搜索组件，通过搜索框选择要过滤的字段，拖拽后，字段发生了变化。
**Bug 重现步骤(有截图更好)**

<img width="654" alt="图片" src="https://user-images.githubusercontent.com/48307752/161376362-8ac3077b-8b69-415a-9977-247d719eaa6d.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下。

**Comment by BBchicken-9527** [comment]
感谢反馈，问题已修复，将会在下个版本更新

**Comment by xuwei-fit2cloud** [comment]
v1.9.1 已修复，请升级最新版本。
