### ISSUE TITLE
[Bug]API数据源（不需要认证，只能内网访问），添加过程中获取数据成功，数据集中数据预览时请求失败

### ISSUE THREAD

**Issue by xyd113** [dataease/dataease#2038]
**DataEase 版本**
1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
Chrome 版本 98.0.4758.80（正式版本） (x86_64)

**Bug 描述**
[Bug]API数据源（不需要认证，只能内网访问），添加过程中获取数据成功，数据集中数据预览时请求失败

**Bug 重现步骤(有截图更好)**
1. 添加一个API数据源（这个数据源url用的我们内网域名，不用认证，点击链接可以直接获取到数据的那种）；
2. 一步一步操作添加过程，注意过程中会显示请求拿到的数据；
3. 在数据集中添加一个API数据集，选择刚刚添加的API数据源;
4. 添加成功后点击API数据集预览数据，请求失败，提示错误信息如下：
数据源连接异常: Communications link failure The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.

**Comment by xuwei-fit2cloud** [comment]
api数据源的数据会存放在dataease 内置的doris里，如果doris无法正常访问的话，确实是会报上述错误。
在v1.9.0 版本中支持精简模式运行方式，可以将api数据源和excel数据集的数据存放在指定的MySQL数据库里，这样可以避免doris无法访问导致的一些常见问题。

**Comment by xuwei-fit2cloud** [comment]
可以尝试使用v1.9 版本的精简模式
