### ISSUE TITLE
[Feature]仪表盘表格返回数据时，数据分页在前端，浏览器会崩溃，页面产生oom问题，能否支持后端分页？

### ISSUE THREAD

**Issue by dxiyang** [dataease/dataease#2039]
数据一下子会灌到前端，浏览器扛不住；

**Comment by yayanpei** [comment]
感谢反馈，浏览器崩溃，我们推断应该是数据量大，后台接口读取数据卡或者查询耗时导致的，也在商讨解决方案。您这边如果有好的建议，欢迎随时与我们沟通交流，再次感谢。
