### ISSUE TITLE
[Question]配置运行不起来

### ISSUE THREAD

**Issue by qich1234** [dataease/dataease#2040]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/90487563/161380207-51a6c504-998b-46c1-a616-d25345c7f85c.png)
按照开发环境部署，启动后访问doris出现错误，请问这大概是什么问题？

**Comment by qich1234** [comment]
主程序导入excel一直为灰色无法点击，在线安装因为是girhub网络无法访问，用线下部署情况类似。

**Comment by xuwei-fit2cloud** [comment]
excel数据集置灰，是因为kettle运行不正常，可以检查一下kettle。doris的问题，可以在也没上看到详细的错误信息。
另外，在4月7日要发布的 v1.9.0 版本中，提供了精简模式的支持（simple），使用excel数据集，可以存放在指定的MySQL数据库中，而不需要用到kettle和doris组件，可以等待新版本发布试试新版本。

**Comment by xuwei-fit2cloud** [comment]
v1.9 版本已发布，请使用新版本的精简模式。
