### ISSUE TITLE
[Feature]删除数据集及数据源时，能够支持用户选择确定删除基于该数据集或者数据源的视图

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#2046]
**请描述您的需求或者改进建议.**
删除数据集及数据源时，能够支持用户选择确定删除基于该数据集或者数据源的视图
删除时罗列数据集及数据源相关的视图仪表板清单供用户确认即可，或直接删除，或不删除

**Comment by yayanpei** [comment]
感谢反馈，您的需求我们已收到
