### ISSUE TITLE
[Bug] db2 10.1 数据源添加失败

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2059]
**DataEase 版本**
v1.8

**Bug 描述**
db2 10.1 版本添加数据源报错如下：
![image](https://user-images.githubusercontent.com/30063018/161952842-a17e2ad5-ad3a-490c-a31c-ccca0014b345.png)
跟db2 sql 后面都拼接上了 分号有关
<img width="984" alt="image" src="https://user-images.githubusercontent.com/30063018/161953038-6db43226-d4bf-4c2c-a8c3-adc6ab9ac91a.png">

**Comment by xuwei-fit2cloud** [comment]
v1.9.0 版本已修复，请等待新版本发布。
