### ISSUE TITLE
[Bug]Doris对单行数据的长度有限制，若超出限制则无法建表

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#2060]
我们在学习dataEase的时候，上传excel作为数据集的功能，会将Excel映射成Doris的一张表并创建，但是程序无法预知每个字符串字段的长度，我看程序默认都给了doris单列字符串的最大长度（65536），而Doris对单行数据的长度也有限制（100000），这样所有字段长度之和就超出了这个限制，会导致无法动态创建Doris表

**Comment by xuwei-fit2cloud** [comment]
目前确实有这个问题，我们再想想如何处理。
