### ISSUE TITLE
[Feature]能够支持管理员对所有定时报告进行删除操作

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#2064]
**请描述您的需求或者改进建议.**
当前管理员无法对所有定时报告进行删除操作，那么如果发布定时报告的用户被删除了，这个定时报告怎么处理？
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/60059766/161984538-34057a3c-e9c1-4c2c-b14b-d6f9f233f4df.png">

**Comment by yayanpei** [comment]
感谢反馈，您的建议很不错，我们会在下个版本中优化一下。

**Comment by BBchicken-9527** [comment]
问题已修复，将会在下个版本更新
