### ISSUE TITLE
[Bug]定时报告查看权限控制

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#2065]
**DataEase 版本**
1.8.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
70+

**Bug 描述**
普通用户能够看到所有的定时报告

**Bug 重现步骤(有截图更好)**
1.应该只能看到自己定制的定时报告
2.
3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by BBchicken-9527** [comment]
已完成修复，将会在下个版本更新
