### ISSUE TITLE
[Question]通过DataEase删除数据同步定时任务，提示错误

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#2066]
**请描述您的问题.**
通过DataEase删除数据同步定时任务，提示网络错误，查看后台应用状态提示，如下图所示
<img width="707" alt="image" src="https://user-images.githubusercontent.com/60059766/162007711-f60c76af-d3bd-4cd6-afaa-e28236dd29a1.png">

**Comment by xuwei-fit2cloud** [comment]
浏览器是不是举例出现问题比较长时间之前打开的，且并未做其他页面跳转操作，然后出现错误提示？
看情况应该当时的服务已经退出了。
