### ISSUE TITLE
[Bug]用户已经被授权创建定时报告，页面创建时提示无权限

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#2070]
**DataEase 版本**
V1.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
谷歌80+

**Bug 描述**
新用户创建定时报告，页面提示无权限

**Bug 重现步骤(有截图更好)**
1、用户角色为：普通员工
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/60059766/162103719-14bf5d01-9759-4851-a0f9-f55f99bdadc1.png">
2、普通员工授权为：支持管理定时报告
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/60059766/162103650-7b05a8e2-7abd-4c7d-9c70-6282dc39be4e.png">
3、普通用户登录后：提醒没有权限
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/60059766/162103989-0eec3dc6-5996-46fc-a885-697880a0d1c4.png">

**Comment by BBchicken-9527** [comment]
已经完成修复，将会在下个版本进行更新
