### ISSUE TITLE
手机端 布局适配问题

### ISSUE THREAD

**Issue by 8debug** [dataease/dataease#2079]
**DataEase 版本**
1.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
小米10s 内置浏览器

**Bug 描述**
![5758ef1d8a92d7aa0058f06926af205](https://user-images.githubusercontent.com/3394927/162193548-c36876fd-d9f0-46eb-a861-b62c116a65dc.jpg)

**Bug 重现步骤(有截图更好)**
1. admin登录web端，制作仪表板。将仪表板分享给新建的普通用户test
2. test 用户使用手机登录 dataease，查看分享的仪表板

**Comment by BBchicken-9527** [comment]
方便复制一下手机端的链接看一下吗

**Comment by xuwei-fit2cloud** [comment]
其他手机访问会出现一样的问题吗？

**Comment by 8debug** [comment]
http://123.57.251.114:8080/link/IgmLTs2x

另外手机端打开上面链接 是这样的

![742402268292fef6584954cdadaf730](https://user-images.githubusercontent.com/3394927/162655041-dbd49aec-08fd-47e2-ac00-b08df55c3f50.jpg)

**Comment by BBchicken-9527** [comment]
这个链接是公共链接，出问题的也是公共链接吗？还有就是我看你的视图排版不太对，有没有开启移动端布局？
