### ISSUE TITLE
[Bug] 视图编辑里“更换数据集“图标的问题

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2083]
**DataEase 版本**
1.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 描述**
1.大部分用户都觉得这个图标是刷新维度与指标字段而不是更换数据集
![image](https://user-images.githubusercontent.com/82353425/162355762-d4a1c569-b5ea-4a33-853c-fd99090e624c.png)
2.能不能换一个更显眼的图标嘞

**Comment by yayanpei** [comment]
感谢反馈，您的建议很不错，我们会在后面的版本中对此优化。

**Comment by Xiamu-ssr** [comment]
感谢，终于找到了在哪里换数据。
