### ISSUE TITLE
公共链接外部参数不生效

### ISSUE THREAD

**Issue by sewenc** [dataease/dataease#2091]
你好，我创建的公共链接外部参数不生效
版本：1.9.1

配置：
![image](https://user-images.githubusercontent.com/40030020/162624427-63ed2f10-6633-42b9-b041-909d15969f7f.png)

此dashboard的链接： http://192.168.56.10/link/iTmifm53

我带参数请求，发现不生效:  http://192.168.56.10/link/iTmifm53?dscode=dihu

是我姿势错了么？

**Comment by yayanpei** [comment]
感谢反馈，可以按照操作文档中所示的方式进行设置，链接如下：https://dataease.io/docs/user_manual/dashboard_basicfunctions/#6

**Comment by sewenc** [comment]
> 感谢反馈，请确认一下是否与操作文档中的设置方式一致，链接如下：https://dataease.io/docs/user_manual/dashboard_basicfunctions/#6

非常感谢，之前没找到文档说明
