### ISSUE TITLE
[Feature]柱状图辅助线设置及展示优化建议

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#2096]
**请描述您的需求或者改进建议.**
1、支持辅助线名称能够显示；
2、支持辅助线能够计算平均值、最大值、最小值等；
3、如果辅助线设置中的数值无法输入单位等，则控制下数值输入框不能输入中文字符。同时建议能够设置数值单位
具体参见如下图：
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/60059766/162901577-1117e2e1-80d0-4e0d-8d62-2c4c92c713e6.png">

**Comment by yayanpei** [comment]
感谢您的反馈，您的建议很不错，我们会优先考虑加入版本迭代中。
