### ISSUE TITLE
[Bug]柱状图+线状图组合图部分图例丢失

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#2097]
**DataEase 版本**
V1.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器：版本 99.0.4844.83（正式版本） (arm64)

**Bug 描述**
基于门店销量数据制作组合图，分别将销量数据拖入主轴值和副轴值，分别设置汇总计算为求和+快速计算为无、汇总计算求和+快速计算为同环比百分比计算，其中主轴值为柱状图、副轴值为折线图，但是图例在显示的时候只显示了主轴值的图例，未显示副轴值的图例。

**Bug 重现步骤(有截图更好)**
1、加入包含时间和商品销量数据集，开始制作视图，数据拖拽如下所示：
<img width="301" alt="image" src="https://user-images.githubusercontent.com/60059766/162917853-51a62f6a-5e71-4544-bc4c-88c375337b25.png">
2、其中主轴值和副轴值的数据汇总计算和快速计算方式设置如下图所示：
主轴值设置：
<img width="149" alt="image" src="https://user-images.githubusercontent.com/60059766/162917990-551b4d19-5ca4-49b7-952e-6d4f5dc8b882.png">
副轴值设置：
<img width="160" alt="image" src="https://user-images.githubusercontent.com/60059766/162918131-1d92248e-0ae2-4f71-87bd-8e752ac5c34d.png">
<img width="597" alt="image" src="https://user-images.githubusercontent.com/60059766/162918302-36684925-cd4a-4e3f-851b-c18b7899aa43.png">
3、最终展示图例及图例设置如下图所示：
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/60059766/162918531-2aa9d689-8bad-41f3-8096-50d25f530de5.png">

**Comment by XiaJunjie2020** [comment]
修改其中一个指标的显示名即可，多指标同名称，在图库中，将被认为是同一图例。
