### ISSUE TITLE
[Feature]同环比的差值百分比在坐标轴中建议显示百分比

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#2098]
**请描述您的需求或者改进建议.**
快速计算后的同环比的百分比数值，在坐标轴中显示时建议能直接按照百分比显示刻度线的刻度值

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/60059766/162921937-74124d05-1ead-4ca4-a886-86e1d93ff59a.png">

**Comment by yayanpei** [comment]
感谢您的反馈，该需求已经在规划开发了
