### ISSUE TITLE
“删除”提示文本修改为“移出”

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2101]
建议：仪表板页签下的默认仪表板分组中，其中的仪表板的“删除”操作的文本提示建议改成“移出”（移出默认仪表板），不然容易认人误会成彻底删除的意思。
路径：仪表板->默认仪表板->删除按钮
![删除改移出](https://user-images.githubusercontent.com/24768910/162932867-c71da59f-59e6-49f1-883b-fd8e7d31e090.png)

**Comment by yayanpei** [comment]
感谢反馈，您的建议已收到。
