### ISSUE TITLE
[Bug]视图复制后原视图内容全部丢失

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#2102]
**DataEase 版本**
V1.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌版本 99.0.4844.83（正式版本） (arm64)

**Bug 描述**
复制仪表板中的视图，视图数据全部被置空，原视图中的数据全部丢失。

**Bug 重现步骤(有截图更好)**
1、新建仪表板、创建指标卡视图；
2、点击指标卡中的视图复制按钮，完成复制
3、复制完成的视图所有原视图的配置及数据内容全部丢失
备注：已验证其他视图均是如此，同时发现如果是曾经保存过的视图再复制就不会丢失数据。
<img width="497" alt="image" src="https://user-images.githubusercontent.com/60059766/162941411-848e4a2b-e77b-4112-b962-6bd05949446f.png">

**Comment by xuwei-fit2cloud** [comment]
v1.9.1版本已修复，请升级到1.9.1版本。
