### ISSUE TITLE
[Bug]ECharts柱状图降序排序错误

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#2106]
**DataEase 版本**
V1.9.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器：版本 99.0.4844.83（正式版本） (arm64)

**Bug 描述**
ECharts图库中的横向柱状图数据按照降序排序，但是视图展示是按照从小到大的升序排列的，最终导致无法制作一个从大到小的 TOP10从大到小的横向柱状图

**Bug 重现步骤(有截图更好)**
1.创建ECharts图库中的横向柱状图，拖入相关指标，点击按照降序排序，视图中展示的排序是从小到大，多次实验发现数据升序降序排序与视图展示升序降序效果相反，结果如下图所示：
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/60059766/163116724-1f55ac31-2524-4d86-a8a6-eab540ce6e7a.png">

2.如果进一步按照降序展示TOP10，则展示效果比较奇怪，无法展示从大到小的TOP10效果
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/60059766/163116405-79e85dc6-ed14-45c7-b148-3bb813b32c81.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，ECharts组件设计本身就是从起始点开始排列的，我们讨论一下是否要摒弃组件自身设计，以及优化的空间
