### ISSUE TITLE
[Bug] 在创建自定义数据集关联两个 Oracle 数据集时报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2112]
**DataEase 版本**
1.9.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome 版本 100.0.4896.60（正式版本） (arm64)

**Bug 描述**
在系统中创建自定义数据集时报错

**Bug 重现步骤(有截图更好)**
1.创建了两个 Oracle 数据库数据集，并进行了数据关联；
![image](https://user-images.githubusercontent.com/24768910/163322384-9a82a466-bb54-4c28-a41c-5e839bed6b58.png)

2.创建【自定义数据集】选择其中一个数据集中的某个字段，点击确定报错；
![image](https://user-images.githubusercontent.com/24768910/163322282-c0cbfe24-a8cb-44b8-a73d-972b155f82be.png)

3.以下是后台日志报错的截图；
<img width="795" alt="Snipaste_2022-04-14_13-44-33" src="https://user-images.githubusercontent.com/24768910/163322576-90f64d9e-520c-4d86-9dfa-42d9e77d91e3.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，建议使用关联数据集，以为一些特殊原因，自定义数据集功能将不在进行维护。

**Comment by AndroidBaby1** [comment]
好的，了解，谢谢

**Comment by AndroidBaby1** [comment]
问题已解决
