### ISSUE TITLE
[Feature]建议替换选项卡组件中新增 Tab 的图标

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2128]
**请描述您的需求或者改进建议.**
选项卡组件新增 Tab 的图标与其它组件的联动设置为同一图标，容易产生误解，建议更改与“新增 Tab”含义相近的图标。
<img width="370" alt="image" src="https://user-images.githubusercontent.com/48945409/163713440-35c15bcb-1952-43a7-a1d7-1ebcba406699.png">

**Comment by yayanpei** [comment]
感谢您的反馈，我们更换一下图标。
