### ISSUE TITLE
[Bug] 定时同步任务，同时设置了增量删除及增量添加，当增量删除的SQL查出来的数据为0的时候，增量添加任务也不生效

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2133]
**DataEase 版本**
v1.9.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
定时同步任务，同时设置了增量删除及增量添加，当增量删除的SQL查出来的数据为0的时候，增量添加任务也不生效。

**Bug 重现步骤(有截图更好)**
1、如图，初始时数据库有一条 2021-11-30 日的数据。
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/30063018/163797406-b930d59a-0091-41c8-9251-153de8a7ba49.png">
2、往数据库插入一条 2021-12-31 日数据。
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/30063018/163797511-d618e6cb-dbf7-4118-b065-f1fbbb69e7c3.png">
3、配置定时任务，先删 2021-12-31 日数据，再添加 2021-12-31 日数据。
<img width="722" alt="image" src="https://user-images.githubusercontent.com/30063018/163797626-8766b349-1433-4949-827b-0318c9de4d15.png">
<img width="720" alt="image" src="https://user-images.githubusercontent.com/30063018/163797651-9ab01b40-26de-42bc-83b9-061ab073cf60.png">
<img width="723" alt="image" src="https://user-images.githubusercontent.com/30063018/163797678-26e7950a-117b-48da-a0b8-340b739f6a0f.png">
4、执行成功后查看数据，发现 2021-12-31 数据并没有添加进来
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/30063018/163797749-26cc7a7d-4115-497f-82b2-6abe95cf0518.png">
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/30063018/163797762-f18d0d5c-992c-4242-9358-cb62dc993572.png">
5、删除 增量删除 任务，再次尝试
<img width="741" alt="image" src="https://user-images.githubusercontent.com/30063018/163797915-84364ef0-a39d-4da6-8257-cd26c6168557.png">
6、执行成功后查看数据。
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/30063018/163797986-f8ca3435-e913-4af1-a93e-8f2df28e5213.png">
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/30063018/163798004-eced1714-ec9d-467f-917e-5be954033ac5.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，因为是相通的sql语句，而实现逻辑上是先进行增加之后进行删除操作，所以导致以为没有生效。可以从info日志观察到的。
