### ISSUE TITLE
[Bug] 针对同一数据集，添加两个定时同步任务时，增量删除、添加的配置会相互干扰

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2134]
**DataEase 版本**
v1.9.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
如题，针对同一数据集，添加两个定时同步任务时，增量删除、添加的配置会相互干扰

**Bug 重现步骤(有截图更好)**
1、添加定时任务 1 
<img width="721" alt="image" src="https://user-images.githubusercontent.com/30063018/163907664-5c4a4277-1683-4e0a-8204-8712de0ad939.png">
2、添加定时任务 2
<img width="722" alt="image" src="https://user-images.githubusercontent.com/30063018/163907914-3f0e84e6-6df6-4322-bc1c-442f44f61cdf.png">
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/30063018/163908046-618e29c1-a36e-47b8-80d2-8dfd7436495b.png">
3、查看第一个定时任务
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/30063018/163908154-7ee47d46-dc4a-4970-99ac-9a16e65f6c91.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/30063018/163908189-944dbf47-34d3-4dff-a9a0-7a496d213435.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们讨论一下
