### ISSUE TITLE
[Feature]建议给视图元素操作增加快速删除的方式

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2137]
**请描述您的需求或者改进建议.**
建议在指标、维度等场景的元素右侧直接增加一个删除图标，会方便一些，尤其是复制视图做编辑的场景中。
<img width="463" alt="image" src="https://user-images.githubusercontent.com/48945409/163957702-f220a7dc-aa1d-4d85-828b-cd4b233ba6bd.png">
同类产品参考：当鼠标悬浮上去后，删除图标显示出来，可以直接点击图标快速删除元素。
<img width="569" alt="image" src="https://user-images.githubusercontent.com/48945409/163957593-578f5ebe-f28d-4891-8205-82c25ae300a6.png">
<img width="607" alt="image" src="https://user-images.githubusercontent.com/48945409/163957903-87837a0c-c4b5-4182-a935-143b974d7e17.png">

**Comment by yayanpei** [comment]
感谢反馈，您的建议很不错，我们会优先考虑加入后续的版本迭代中。
