### ISSUE TITLE
[Bug]精简模式下上传 3000 多行的 Excel 文件超时失败

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2138]
**DataEase 版本**
v1.9.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包精简模式

**浏览器版本**
Chrome 99

**Bug 描述**
服务器配置为阿里云 4c8g，精简模式下上传 3182 行，10 个字段的 Excel 文件超时失败，文件可见附件。

**Bug 重现步骤(有截图更好)**
[2015-2020在线教育投融数据.xlsx](https://github.com/dataease/dataease/files/8511687/2015-2020.xlsx)
1.配置好了数据引擎为 DE 自带的 MySQL;
2.请求超时时间设置为了 100 秒；
3.上传【2015-2020在线教育投融数据】文件；
4.几次尝试均失败。
<img width="1731" alt="image" src="https://user-images.githubusercontent.com/48945409/163973493-e56828db-ae39-437a-9987-b3fb0b4d2db5.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，但描述中的超时问题，我们并没有复现。
但这里确实有些问题，比如空值及特殊字符处理，我们尽快修复。
