### ISSUE TITLE
[Bug]数据集，Excel 数据集在【精简模式】下只能导入 100 行 Excel 里的数据

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#2141]
**DataEase 版本**
1.9.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Microsoft Edge
版本 100.0.1185.44 (正式版本) (64 位)

**Bug 描述**
Excel 数据集在【精简模式】下只能导入 100 行的 Excel 数据

**Bug 重现步骤(有截图更好)**
1.原始数据：
[北京历史天气数据.xlsx](https://github.com/dataease/dataease/files/8511928/default.xlsx)

2.上传数据，预览：
<img width="960" alt="2022-04-19_174522" src="https://user-images.githubusercontent.com/96223591/163978882-ccd03b72-742a-4816-bf87-d2649ac4ca79.png">

3.查看 MySQL 数据库：
<img width="400" alt="2022-04-19_174848" src="https://user-images.githubusercontent.com/96223591/163978950-2fc2ec50-5e1b-4c34-b7bb-c5c48da2b92f.png">

**Comment by xuwei-fit2cloud** [comment]
确实有这个问题，我们正在修复中。
