### ISSUE TITLE
[Bug] 数据源API post 报错 HttpClient查询失败: Unsupported Media Type

### ISSUE THREAD

**Issue by lnts2015** [dataease/dataease#2142]
**DataEase 版本**
1.9.1

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Google Chrome 100

**Bug 描述**
数据源API post  请求， 请求体为： x-www-form-urlencoded  
报错信息为：HttpClient查询失败: Unsupported Media Type
    

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/6037915/164132332-1678d781-59fc-4b2d-b508-c37604f8d6eb.png)

**Comment by xuwei-fit2cloud** [comment]
试试在请求头里设置一下 Content-Type看看？这个需要看调用的API具体支持什么类型的 Content-Type 了。

**Comment by xuwei-fit2cloud** [comment]
下图供参考：
![图片](https://user-images.githubusercontent.com/1892127/164191248-91d4629f-f134-4d53-926b-ebb358314d70.png)

**Comment by lnts2015** [comment]
请求头已设置： 
![image](https://user-images.githubusercontent.com/6037915/164959990-d3077de6-5f30-4e94-a07d-b529550aa7e6.png)
请求体为：
![image](https://user-images.githubusercontent.com/6037915/164960000-0b0f1b80-db47-4c01-bc63-76e0706c4ea5.png)

设置后仍然报错：HttpClient查询失败: Unsupported Media Type
