### ISSUE TITLE
[Bug]数据集，Excel 数据集导入，Excel 表字段含空数据时导入报错

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#2143]
**DataEase 版本**
1.9.1 版本

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge
版本 100.0.1185.44 (正式版本) (64 位)

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.原始数据：
![image](https://user-images.githubusercontent.com/96223591/164141910-ab43947f-354c-4d71-8a1a-a816e17ecce3.png)
[x_cards(1).xlsx](https://github.com/dataease/dataease/files/8517972/x_cards.1.xlsx)

2.导入报错：
![image](https://user-images.githubusercontent.com/96223591/164141982-6a6a0bfc-806e-4eab-9e82-17704c357595.png)

3.错误
![image](https://user-images.githubusercontent.com/96223591/164142083-c6334f59-d663-4fe9-a47d-48503957e2aa.png)

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #2138
