### ISSUE TITLE
[Bug] 重启 DataEase 之后，自定义视图插件消失

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2150]
**DataEase 版本**
1.9.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌浏览器

**Bug 描述**
1.我将插件压缩包导入 DataEase 里面，然后点击编辑视图可以看到最新的 3D 饼图
![image](https://user-images.githubusercontent.com/82353425/164381974-36c488af-5ffc-4b75-ac02-6190a5f0acbc.png)
![e4106df4ffd827fd185124e1ce14232](https://user-images.githubusercontent.com/82353425/164382264-834bf103-a974-4509-80ec-1bd19e4d1d7e.png)

2.我重启 DataEase 之后 再次打开编辑视图就看不到 highcharts  了
![image](https://user-images.githubusercontent.com/82353425/164382038-453755bb-7661-43f0-9b9c-6ccc7cc84ede.png)

3.用了无痕浏览器与清空浏览器缓存还是没有作用
**Bug 重现步骤(有截图更好)**
1.首先导入自定义视图插件的压缩包
2.编辑视图可以查看到刚才导入的视图
3.重启 DataEase ，并且清空浏览器缓存与无痕模式打开 DataEase，找不到之前导入的视图

**Comment by BBchicken-9527** [comment]
感谢反馈，我这边看了一下没有发现你说的情况方便把你使用的插件给我这边看一下吗

**Comment by ywhfzy** [comment]
[plugin.zip](https://github.com/dataease/dataease/files/8551085/plugin.zip)

**Comment by ywhfzy** [comment]
@BBchicken-9527  重启dataease之后，记得清除浏览器缓存以及打开无痕浏览器试试

**Comment by BBchicken-9527** [comment]
![image](https://user-images.githubusercontent.com/84372766/165011138-87df1dc7-393a-403c-bca5-b0cc2b22efdb.png)
目前没有发现你说的问题，我用你给的插件，无痕浏览器关闭后再开启查看

**Comment by ywhfzy** [comment]
https://user-images.githubusercontent.com/82353425/165011935-62d7bd7b-d514-474f-9884-4d5a1d326374.mp4

这个是我重启之后的dataease

**Comment by BBchicken-9527** [comment]
感谢反馈，使用最新插件试一下，这个只是测试的插件

**Comment by wux9530** [comment]
@ywhfzy 调试下代码就能知道问题啦，数据库my_plugin这个表里面的插件版本和你源码编译的插件版本不一致，项目启动时按照这个版本去找的，找不到重启后自然就找不到那个插件了，修改下数据库的版本和你的插件jar包的版本一致就可以了
