### ISSUE TITLE
[Feature]建议去掉仪表板、数据集编辑页面的白色遮罩(查询比较慢时，要等到数据加载完才能开始编辑，不太合理)

### ISSUE THREAD

**Issue by nigel001** [dataease/dataease#2151]
**请描述您的需求或者改进建议.**
建议去掉仪表板、数据集编辑页面的白色遮罩。
因为白色遮罩要等到所有数据加载完才会消失，期间不能对页面进行操作，
如果仪表板或数据集中存在查询比较慢的情况，则要干等到查询完或查询超时，才可以继续进行操作，非常影响操作的效率！

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到
