### ISSUE TITLE
[Bug] 数据集，monggodb 数据集字段同步预览报错

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#2152]
**DataEase 版本**
1.9.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge
版本 100.0.1185.44 (正式版本) (64 位)

**Bug 描述**
mongodb 数据集字段同步时预览报错

**Bug 重现步骤(有截图更好)**
1.原始数据，admin 用户下
![image](https://user-images.githubusercontent.com/96223591/164590377-b74563e6-d822-48de-bd35-93d2bcc11f45.png)

2.
![image](https://user-images.githubusercontent.com/96223591/164590502-04420be8-30ff-4c18-ae7a-50fb10718b95.png)

3.执行 SQL 失败
![image](https://user-images.githubusercontent.com/96223591/164590511-3242693f-e0e1-4ff3-8afd-a3c90bfab72a.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，正在考虑解决方案
