### ISSUE TITLE
[Feature]建议视图的重置按钮不要设置太过引人注目

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2153]
**请描述您的需求或者改进建议.**
用户反馈，重置按钮的暖色调太过显眼与引人注目，常常导致全神贯注做仪表板想要点【保存】时，点到了【重置】。
<img width="1649" alt="image" src="https://user-images.githubusercontent.com/48945409/164591813-566d7210-d26f-4e6e-96c6-619a07e3f801.png">

**Comment by yayanpei** [comment]
感谢反馈，我们优化一下
