### ISSUE TITLE
[Feature]建议增加数据颜色自定义和新图表样式

### ISSUE THREAD

**Issue by xiaopengyou123** [dataease/dataease#2156]
1、增加数据颜色自定义。比如表格的环比同比增量用红色  减量用绿色，最好有站内预警功能，快速感知
2、增加横向表格样式。竖向是年份环比同比  横向是月份

**Comment by yayanpei** [comment]
感谢反馈，您的建议很不错，我们会优先考虑加入到后续的版本迭代中
