### ISSUE TITLE
[Bug] 同时创建多个定时同步的数据集，会出现部分数据集更新信息显示成功但是预览数据为空的情况

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2159]
**DataEase 版本**
v1.9.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
如题

**Bug 重现步骤(有截图更好)**
1. 同时添加多个定时同步的数据库数据集。
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/30063018/164954705-8837ab61-fe50-4dc9-a12a-248fdee358c6.png">

2. 查看数据集数据，发现某些数据集预览数据为空，更新信息里初始导入任务显示成功
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/30063018/164954884-63a979cc-4de8-4837-9bb8-45a2c2269573.png">
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/30063018/164954890-08798484-6790-4ba6-a6e8-8de1547a3d8e.png">

3. 针对这个数据集，添加全量更新任务，发现数据同步过来了
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/30063018/164954958-dbbbf22f-27b2-4c03-8928-c1e941d732bc.png">
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/30063018/164954963-5234e099-7920-4f73-bb51-ed59dba67f28.png">

**Comment by fit2cloud** [comment]
感谢反馈，正在处理中
