### ISSUE TITLE
[Bug]精简模式配置无效的数据引擎 Excel 上传未报错

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2162]
**DataEase 版本**
v1.9.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包精简模式

**浏览器版本**
Chrome 100

**Bug 描述**
数据引擎配置了无效的 MySQL 信息，但是在上传 Excel 时未报错，目录显示已经有该 Excel，但是点击这个数据集就会一直加载卡主。

**Bug 重现步骤(有截图更好)**
1.之前配置的数据引擎已经失效；
<img width="1535" alt="image" src="https://user-images.githubusercontent.com/48945409/165011407-b0100c64-7f4c-43ba-b97e-2f720c618b5f.png">

2.选择一个 Excel 文件上传；
<img width="1526" alt="image" src="https://user-images.githubusercontent.com/48945409/165011457-d24e5e88-9ba1-4afd-9254-83fba3b0fbea.png">
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/48945409/165011480-9d17b3f1-5ecb-4128-8d89-d19d15bff5bb.png">

3.**预期是不应该上传成功**，但是系统未报错，且左侧的目录已经存在该数据集；
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/48945409/165011585-0d83cc83-30e8-4acd-8a55-a39dedcab2f8.png">

4.在并未意识到真实情况而去制作仪表板时，发现无法选上该数据集；
<img width="1533" alt="image" src="https://user-images.githubusercontent.com/48945409/165011740-ef3bcc64-0158-4fc5-b7d6-92801ab91cfa.png">

5.回到数据集列表，点击刚才的数据集，则一直处于加载中，卡死。
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/48945409/165011815-85c6a8be-ee3c-40b8-aac7-563ad2aac20f.png">

**Comment by fit2cloud** [comment]
感谢反馈，正在修复中
