### ISSUE TITLE
[Feature]建议组件样式中边框与背景（颜色或图片）可以共存

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2163]
**请描述您的需求或者改进建议.**
如题，比如一个文字组件，希望可以同时在设置背景的情况下再加上边框；
例如下图已经存在背景色，再为其加上边框效果：
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/48945409/165012566-20e9825f-f2d4-46ec-ba5e-3a9f8392d364.png">

但实际选择了边框之后，无法再具备背景，文字背景就变成了透明。
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/48945409/165012677-a306668b-418d-414f-ac4e-434202ae2280.png">

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到
