### ISSUE TITLE
[Feature]数据集，新建计算字段，选择时间类型时可否选择年，年月

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#2178]
**请描述您的需求或者改进建议.**
MySQL 数据库将 varchar 类型年份拼接成时间类型如下：
![image](https://user-images.githubusercontent.com/96223591/165062411-020067c6-79ee-4666-9427-727856f9271b.png)
字段可正常做转换：
![image](https://user-images.githubusercontent.com/96223591/165062600-f2f6ca26-9f79-431a-a00e-68ad9d512091.png)
只保留年份
![image](https://user-images.githubusercontent.com/96223591/165062833-eb8b4871-0e48-4e0d-8b00-a9197c66d980.png)
数值则为空：
![image](https://user-images.githubusercontent.com/96223591/165063011-71c1e5eb-eb0c-40bc-83de-52d6d7f3437d.png)
当前版本在维度框已支持调整时间字段类型显示为年，年月，年月日等，建议新建字段时可选择的时间类型时为年，年月，如下示例图：
![image](https://user-images.githubusercontent.com/96223591/165065154-aba7fb7d-12dd-4342-b9e6-6fdff594749f.png)

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到
