### ISSUE TITLE
[Bug]将字段的文本格式转换为数值格式后，无法排序

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#2186]
DataEase 版本
v1.9.1

运行方式(安装包运行 or 源码运行 ?)
安装包运行

浏览器版本
chrome

Bug 描述
如题

**Bug 重现步骤(有截图更好)**
1.将excel数据源导入，以 2019 列为例子，进行演示，原始字段类型设置为 文本
![image](https://user-images.githubusercontent.com/101089844/165232633-1681992b-7875-4843-896d-54895dec96c6.png)

2.当字段类型是文本格式时，排序无效
![image](https://user-images.githubusercontent.com/101089844/165232760-48964a3a-3af1-471c-93ec-d9c6ec98c230.png)

3.将 2019 转换为数值类型后，排序依旧无效
![image](https://user-images.githubusercontent.com/101089844/165232902-1951dcd1-dfb0-4470-b2d2-74ebca8f6625.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前没有看到您说的问题，方便将您使用的数据给我们一份吗
