### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by chuzig** [dataease/dataease#2189]
**DataEase 版本**
V1.9.1

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 100

**Bug 描述**
插件zip打包时，如果在mac操作系统上，会默认打包”__MACOSX“的目录及文件，导致上传失败

**Bug 重现步骤(有截图更好)**
1.
2.
<img width="450" alt="23" src="https://user-images.githubusercontent.com/6312316/165252629-a7eb4c1e-f025-49ad-94a9-6108048ad19d.png">

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，可以尝试换个大包的工具尝试一下
