### ISSUE TITLE
[Bug] 识别不了excel中时间类型的字段

### ISSUE THREAD

**Issue by lvxiaohu** [dataease/dataease#221]
**DataEase 版本**
v1.0.1

**浏览器版本**
Chrome  版本 91.0.4472.114（正式版本） (x86_64)

**Bug 描述**
识别不了excel中时间类型的字段

**Bug 重现步骤(有截图更好)**
1. excel 数据源，类型为时间
![image](https://user-images.githubusercontent.com/29087369/125386849-8f7cfa80-e3cf-11eb-92e8-3da1b52a3755.png)

2. 数据原始类型还是文本 
![image](https://user-images.githubusercontent.com/29087369/125386897-a58abb00-e3cf-11eb-8de9-64d283d663a1.png)

3.手动修改字段为时间类型，就看不到时间字段了
![image](https://user-images.githubusercontent.com/29087369/125386983-cc48f180-e3cf-11eb-91de-5288713c16ba.png)

![image](https://user-images.githubusercontent.com/29087369/125387044-e08cee80-e3cf-11eb-8d69-c1ab7db85e85.png)

**Comment by xuwei-fit2cloud** [comment]
感谢您的反馈，我们尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.2.0 版本已修复
