### ISSUE TITLE
[Bug] 修改数据源信息后，数据集中使用的数据库连接池未更新

### ISSUE THREAD

**Issue by you10906** [dataease/dataease#2220]
**DataEase 版本**
1.9.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
修改数据源信息后，数据集中使用的数据库连接池未更新

**Bug 重现步骤(有截图更好)**
1. 新建数据源mysql_bdmt
![image](https://user-images.githubusercontent.com/26760641/165907959-8c3ba95c-f48c-40fa-b169-b3f0aec7148e.png)

2. 修改数据库的名称
![image](https://user-images.githubusercontent.com/26760641/165908451-65aca53b-30a4-448a-9d79-86e508e310c2.png)

3. 新建SQL数据集，预览数据报错，从报错内容可知连接的数据库还是第一次创建时配置的bdmt，而不是修改后的数据库bdqc
![image](https://user-images.githubusercontent.com/26760641/165908706-a908e835-781f-44ec-8634-6eefadd0d04a.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快处理

**Comment by maqiangyuen** [comment]
问题已修复，将在下个版本发布

**Comment by xuwei-fit2cloud** [comment]
v1.11.0 版本已修复
