### ISSUE TITLE
[Bug] 自定义数据集PostgreSQL数据源使用非public schema时报错

### ISSUE THREAD

**Issue by you10906** [dataease/dataease#2221]
**DataEase 版本**
1.9.1
**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1、创建postgresql数据源，schema不是public
![image](https://user-images.githubusercontent.com/26760641/165911217-bdbe48f8-21c7-45fd-a101-88cefc75de01.png)

2. 新建postgresql的数据库数据集
![image](https://user-images.githubusercontent.com/26760641/165910673-1214137d-5723-4cd8-978a-6cef69bd97d5.png)

2. 使用上一步创建的的数据集创建自定义数据集，报错

![image](https://user-images.githubusercontent.com/26760641/165910520-b81bb62b-45bc-47b4-af57-10d65af8e220.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，建议使用关联数据集，自定义数据集因为历史原因将不再维护的
