### ISSUE TITLE
[Bug]添加数据库数据集时无法选择”定时同步“

### ISSUE THREAD

**Issue by leim** [dataease/dataease#2225]
**DataEase 版本**
v1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行（docker）

**浏览器版本**
100.0.4896.127

**Bug 描述**
添加数据库数据集，无法选择【定时同步】。
已确认该数据集为MySQL，根据文档描述，可以支持定时同步功能。

**Bug 重现步骤(有截图更好)**
1. 新建一个MySQL数据源
2.添加数据集，选择数据库数据集，选择添加的MySQL数据源
3.点击【直连】，下拉框显示【定时同步】按钮为灰色，点击无反应。

![de](https://user-images.githubusercontent.com/1665397/166870527-a298e37a-38cc-4c20-869b-8c02ebc352c6.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前我这边环境没有发现你的问题，配置文件看一下运行的模式是否属于精简模式，如果你之前没有安装过dataease的话，首次安装默认是精简模式，修改成local即可
