### ISSUE TITLE
[Bug]定时同步类型任务执行会报错

### ISSUE THREAD

**Issue by leim** [dataease/dataease#2226]
**DataEase 版本**
v1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行（docker）

**浏览器版本**
100.0.4896.127

**Bug 描述**
关联问题，[issue 100.0.4896.127](https://github.com/dataease/dataease/issues/2225)
该版本是从1.8版本升级而来，当时可以添加【定时同步】数据源，现在对之前添加的【定时同步】类型的数据源执行同步操作，会报错。

**Bug 重现步骤(有截图更好)**
1. 进入”系统管理“->”数据同步“，在”任务列表“中，找到一条记录，点击右侧”执行一次“按钮
2. 看日志，会报错。

![de](https://user-images.githubusercontent.com/1665397/166871102-7aebb97f-b915-4b42-b80f-64ac11e60f1e.png)

**Comment by BBchicken-9527** [comment]
再次感谢你的反馈，还是需要先确认一下具体的模式，如果模式是local的话看一下.env文件doris的ip是否成功

**Comment by leim** [comment]
我这边没有使用一键安装脚本，而是单独启动了一份doris，包含be和fe，使用mysql客户端连接看是没有问题的。
我又另外编辑了一份docker-compose.yml文件，只启动了dataease和kettle。
在之前的版本，是直接把doris信息配置在 conf/dataease.properties 中的，系统运行也是可以的，但是升级到1.9之后，发现还需要在“系统关联”-> “系统参数”->“引擎设置”中配置doris的信息才行，所以又在这里配置了一次，结果发现就是目前的状态。

**Comment by tjlygdx** [comment]
DE有三种运行模式，你采用的应该是“simple” ？
可以尝试下：
1、配置文件（dataease.properties）中，设置运行模式engine_mode=local；同时在配置文件中设置doris、kettle的参数；
2、清空缓存 /opt/dataease/data/ehcache
3、重启
