### ISSUE TITLE
[Bug]ElasticSearch数据源中的时间字段，在添加视图时，无法设置成维度

### ISSUE THREAD

**Issue by songbing0312** [dataease/dataease#2227]
**DataEase 版本**
v1.9

**运行方式(安装包运行 or 源码运行 ?)**
离线包本地部署

**浏览器版本**

**Bug 描述**
ElasticSearch数据源中的时间字段，在添加视图时，无法设置成维度

**Bug 重现步骤(有截图更好)**
我本地有用户操作的完整视频，时长为3分钟，如有需要，请联系songbing@fit2cloud.com
以下是部分操作截图
1.
2.
3.
<img width="1147" alt="WechatIMG396" src="https://user-images.githubusercontent.com/18387151/166873993-955fc6e5-b769-4fe0-b0cd-8afe6fd52d31.png">
<img width="1186" alt="WechatIMG397" src="https://user-images.githubusercontent.com/18387151/166874016-0043cddb-26d4-4870-aa85-fefc264a480d.png">
<img width="1205" alt="WechatIMG398" src="https://user-images.githubusercontent.com/18387151/166874029-278f20da-5d94-485f-893e-0c8f2894bdc3.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，麻烦看一下明细表添加此字段是否可以正常显示

**Comment by ZacXiong** [comment]
> 感谢反馈，麻烦看一下明细表添加此字段是否可以正常显示

最新版本的 1.10 也有问题，数据源没问题，数据集也没问题，仪表也有问题
![image](https://user-images.githubusercontent.com/105619766/168514770-2aea91e8-96fd-4eff-96ac-722f03927ac9.png)
![481652427292_ pic](https://user-images.githubusercontent.com/105619766/168514784-7c9099c1-8b84-44f8-8773-93e2c794bcfc.jpg)
![531652427389_ pic](https://user-images.githubusercontent.com/105619766/168514791-f46bceea-34f0-431d-90ed-46f6b9bd2a2d.jpg)
![541652427410_ pic](https://user-images.githubusercontent.com/105619766/168514798-c3f3c6db-d007-43c0-a1b5-1a5421c48e30.jpg)

**Comment by ZacXiong** [comment]
> 感谢反馈，麻烦看一下明细表添加此字段是否可以正常显示

也还是提示报错
