### ISSUE TITLE
[Bug] DataEase 无法加载移动端界面

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2229]
**DataEase 版本**
1.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 重现步骤(有截图更好)**
1. 安装最新的版本的 DataEase，然后用浏览器模拟手机端登录
2. F12查看 出现加载超时的情况
![image](https://user-images.githubusercontent.com/82353425/167061564-3dc1edb6-f21f-4aa3-88d1-534d942eac3b.png)
![image](https://user-images.githubusercontent.com/82353425/167061622-661fdf8e-a8a1-401b-b482-91bf1a8b5ff8.png)
![image](https://user-images.githubusercontent.com/82353425/167061654-287435a2-abe5-49ce-a6a4-65007ef22d08.png)

3.原因就是走的是https协议，假如是http协议的话就能打开移动端界面

**Comment by BBchicken-9527** [comment]
感谢反馈，目前环境上没有发现你说的问题，能否给出更详细的报告，方便进一步排查问题
