### ISSUE TITLE
[Bug] 气泡地图的 SQL 数据集展示报错

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2231]
**DataEase 版本**
1.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 重现步骤(有截图更好)**
1. 选择DataEase自带的表名demo_gdp_district_top100，并且创建sql数据集 写上select * from demo_gdp_district_top100
![image](https://user-images.githubusercontent.com/82353425/167109666-34b0a96f-d909-49b2-a4d7-86440ce1bbaf.png)

2. 一个使用标准地图则不会报错，另一个气泡地图会报错
![image](https://user-images.githubusercontent.com/82353425/167109776-bb4b027d-371c-45bf-a81f-4b638b672bfd.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，应该是数据导致的这种结果，方便将数据给我这边验证一下吗

**Comment by ywhfzy** [comment]
> 感谢反馈，应该是数据导致的这种结果，方便将数据给我这边验证一下吗

 DataEase的数据库 有这张表 demo_gdp_district_top100，就是系统全国gdp仪表板的数据集，你可以找一下

**Comment by BBchicken-9527** [comment]
感谢反馈我们会尽快修复
