### ISSUE TITLE
[Feature]添加消息通知【所有消息】页面的多选功能以支持批量将未读消息置为已读

### ISSUE THREAD

**Issue by guilin-f2c** [dataease/dataease#2233]
从DataEase界面主菜单的右边消息通知“气泡”按钮点击进入“所有消息”列表。但是，该列表没有多选按钮帮助我批量将未读消息置为已读。当前用户只能点击进入”未读消息“ 列表，在其中才有批量选择和 ”全部已读“按钮。

个人建议：

1）参考大部分网站在消息通知界面的设计，即只有一个列表显示所有消息。在消息列表中已读和未读区别显示，列表支持多选和”全部已读“快捷键；

如果以上建议不能采纳，至少期待：

2）能够在所有消息页面支持“多选”功能，并提供“全部已读”快捷键。

**Comment by yayanpei** [comment]
感谢您的反馈，消息已进行了分类，在未读消息中，已经支持批量标记已读，以及全部已读，请见如下：
<img width="713" alt="image" src="https://user-images.githubusercontent.com/84168063/167323050-c10bdf13-5b80-4462-8d72-9c610d16b8a1.png">
