### ISSUE TITLE
[Bug] 企业版主题设置，主题模板刷新不显示问题

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2234]
**DataEase 版本**
1.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌

**Bug 重现步骤(有截图更好)**
1.导入企业版 License 之后点击 【参数设置】-【主题设置】之后，主题模板不显示。
![image](https://user-images.githubusercontent.com/82353425/167328604-e9fcc6db-5b97-4e6a-99d6-83587f7ccd97.png)
2.自己编辑下主题颜色，然后点击另存为 测试3 主题之后，主题模板才显示。
![image](https://user-images.githubusercontent.com/82353425/167328684-a25e6652-29ac-4b6c-aebf-1844188ea461.png)
3.重新刷新界面，主题模板又消失。
![image](https://user-images.githubusercontent.com/82353425/167328717-a7c165b7-8ebc-4c0b-bcb1-5bfba5b951c6.png)

**Comment by xuwei-fit2cloud** [comment]
此处有部分公网资源请求，需要进行优化，请等待新版本发布

**Comment by xuwei-fit2cloud** [comment]
v1.11.0 版本已修复
