### ISSUE TITLE
[Bug] 简易模式部署，使用关联数据集创建两个 Excel 的关联报错

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2235]
**DataEase 版本**
v1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 101.0.4951.54

**Bug 描述**
如题，截图如下
![image](https://user-images.githubusercontent.com/30063018/167356813-4a0ce74c-08c1-4556-909f-894c1c89db55.png)

**Bug 重现步骤(有截图更好)**
1. 分别上传两个 excel ，测试1 和 测试2
![image](https://user-images.githubusercontent.com/30063018/167356969-b4083cad-af3e-4012-b208-954043f41c47.png)
2. 针对两个 excel 添加关联数据集，预览结果正常
![image](https://user-images.githubusercontent.com/30063018/167357113-1c725b0d-ffea-4469-9fe6-f8eba18c9eda.png)
3. 点击确认报错，提示当前用到的数据源已被删除
![image](https://user-images.githubusercontent.com/30063018/167357221-258bb759-a03d-428d-9982-7e4e34f90d36.png)

**Comment by xuwei-fit2cloud** [comment]
该问题已修复，请等待新版本发布

**Comment by ziliang-wan** [comment]
好的
