### ISSUE TITLE
[Feature] 基础透视表有支持树状的计划么

### ISSUE THREAD

**Issue by zhangyenull** [dataease/dataease#2240]
**请描述您的需求或者改进建议.**
https://s2.antv.vision/zh/examples/basic/pivot#tree
<img width="900" alt="image" src="https://user-images.githubusercontent.com/13203670/167586112-2e7e6085-7e4a-4e5e-8987-c5f4fc68fde2.png">

**Comment by yayanpei** [comment]
感谢您的反馈，我们需要先讨论一下。
