### ISSUE TITLE
[Bug] AntV 明细表列宽调整设置为自适应的情况下数值类型字段显示不全

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2242]
**DataEase 版本**
v1.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 101.0.4951.54

**Bug 描述**
如题

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/30063018/167754844-e31d75ce-80ac-499e-8258-312b0ba4e680.png)
![image](https://user-images.githubusercontent.com/30063018/167754868-ebdc0f2e-1642-415c-95b4-93366c43c368.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个确实是有这样的问题，s2的图库本身自适应的支持既是如此。我们会尝试处理一下。

**Comment by ziliang-wan** [comment]
好的 收到
