### ISSUE TITLE
[Bug] Excel 表格时间格式为yyyy/MM/dd 导入后过滤组件不生效

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2245]
**DataEase 版本**
v1.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
Excel 表格时间格式为yyyy/MM/dd 导入后过滤组件不生效

**Bug 重现步骤(有截图更好)**
1. 如图，excel 里两个 sheet ，分别对应两个时间格式 yyyy/MM/dd 和 yyyy-MM-dd，均为文本
![image](https://user-images.githubusercontent.com/30063018/167773459-1c284e41-829d-425a-aca4-c019229f99dd.png)
![image](https://user-images.githubusercontent.com/30063018/167773487-0f7160a6-efc6-4234-8a91-57229445b64e.png)
2. 将两个 sheet 页都导入 DataEase ，字段类型都改为时间格式的
![image](https://user-images.githubusercontent.com/30063018/167773892-68f3a2e7-1140-4c9d-86f4-ff7cf2177e99.png)
![image](https://user-images.githubusercontent.com/30063018/167773928-e93b9a9d-23d4-40f7-97d5-3f1046d181f9.png)
可以看出，格式有些区别
3.添加两个明细表，分别展示两个数据，展示没问题，一切正常
![image](https://user-images.githubusercontent.com/30063018/167774275-575a9604-dac5-4d08-801e-8d88d8f8a41d.png)
4.添加过滤组件，可以看到只对 yyyy-MM-dd 的生效
![image](https://user-images.githubusercontent.com/30063018/167774384-b2f15544-d577-429f-ac13-5e7c36513683.png)

**Comment by yayanpei** [comment]
感谢您的反馈，目前导入的日期格式与过滤器的日期格式不匹配的话，过滤器是不生效的，我们先记录，后面优化一下。

**Comment by ziliang-wan** [comment]
好的 收到
