### ISSUE TITLE
sql数据集传参，日期时间过滤，自助分析

### ISSUE THREAD

**Issue by ynzzxc** [dataease/dataease#2252]
1、添加SQL数据集时，支持传递参数，仪表板组件可调用对应参数
2、时间过滤组件支持日期时间
3、支持自助分析

**Comment by fanmaoyang** [comment]
SQL查询中，查询条件支持添加变量设置

**Comment by yayanpei** [comment]
感谢反馈，SQL数据集支持参数已经在规划实现了，初步预计7月初的版本发布。时间过滤组件，请问是支持到时分秒，又或者是到小时就可以了呢？自助分析近期暂不考虑。

**Comment by fanmaoyang** [comment]
时间过滤组件，请问是支持到时分秒，又或者是到小时就可以了呢？

能支持到年月日时分秒就可以了呢，比如 时间区 between "2022-05-16 00:00:00" 至 "2022-05-20 23:59:59" 



***@***.***
 
发件人： yayanpei
发送时间： 2022-05-18 13:46
收件人： dataease/dataease
抄送： fanmaoyang; Comment
主题： Re: [dataease/dataease]sql数据集传参，日期时间过滤，自助分析 (Issue #2252)
感谢您的反馈，SQL数据集支持参数已经在规划实现了，初步预计7月初的版本发布。时间过滤组件，请问是支持到时分秒，又或者是到小时就可以了呢？自助分析近期暂不考虑。
