### ISSUE TITLE
[Feature]列表类型视图增加标题和表格之间间距调整的设置

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2258]
**请描述您的需求或者改进建议.**
列表类型视图增加标题和表格之间间距调整的设置
![image](https://user-images.githubusercontent.com/24768910/168554063-80a8b501-48c8-43cb-94bf-f3269c08798d.png)

**Comment by yayanpei** [comment]
感谢您的反馈，间距我们暂时不考虑增加设置。如果咱们这边觉得默认间距不合适，可通过隐藏图表的标题，然后用文本组件作为标题，间距的调整会更加灵活。

**Comment by AndroidBaby1** [comment]
好的，明白，谢谢
