### ISSUE TITLE
[Bug]视图明显显示[object Object]

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2259]
**DataEase 版本**
1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
汇总表计算同比环比，没有同期或上期数据时列表数据显示为0   视图明细显示[object Object]

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/24768910/168555129-fbcd202e-a360-45a5-9bc5-8a933f9ef723.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，正在努力处理

**Comment by maqiangyuen** [comment]
问题已修复，将在下个版本发布

**Comment by maqiangyuen** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by maqiangyuen** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
