### ISSUE TITLE
[Bug]视图编辑点击保存没有反应，但是实际已保存成功

### ISSUE THREAD

**Issue by huguangya** [dataease/dataease#226]
**DataEase 版本**
1.0.1

**浏览器版本**
谷歌

**Bug 描述**
![image](https://user-images.githubusercontent.com/54281046/125404027-c01d5e00-e3e8-11eb-9bac-030971a7c359.png)

**Bug 重现步骤(有截图更好)**
1.见截图

**Comment by xuwei-fit2cloud** [comment]
已知问题，我们优化一下体验

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #47
