### ISSUE TITLE
[Bug]SQL 数据集报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2260]
**DataEase 版本**
1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
【数据库类型】：PostgreSQL
【问题描述】：
1、navicat 执行 SQL 没有问题，但是在 DE 数据集插件里面初步执行dblink后，再次预览数据集报错。
2、创建dblink时报错：后边这俩图都是创建dblink的错，创dblink通常情况下先create，然后再select dblink

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/24768910/168555706-9de1e460-7f96-4de8-8aa6-7861733bae79.png)
![image](https://user-images.githubusercontent.com/24768910/168556406-2b40f269-b23d-4ca6-9475-d0e34a79567e.png)
![image](https://user-images.githubusercontent.com/24768910/168556432-fa71670e-465b-445d-bc9c-655404cb15a2.png)

**Comment by AndroidBaby1** [comment]
![b2be5fafbfd7ba093e5029e21b5e0782](https://user-images.githubusercontent.com/24768910/169260291-036c5696-1cdf-4af6-b144-f7d66298bf56.png)
![fd7320f7f9b13baee8cf236fb94d2be3](https://user-images.githubusercontent.com/24768910/169260618-19a17af0-3319-47d8-b5f9-ba04611d9b90.png)
这个优先级不高，用户昨天说又不报错了。应该是偶发的情况，不是很好重现，如果有户反馈较多可以再统一看看。

**Comment by BBchicken-9527** [comment]
![image](https://user-images.githubusercontent.com/84372766/169469455-2e078f2e-f0a2-45b2-97a0-91df558a4e1d.png)
目前我这边没有看到此类问题，如果再出现d到时候详细说明吧。要不也不知道怎么改这个东西
