### ISSUE TITLE
[Bug]折线图数据显示问题

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2261]
**DataEase 版本**
1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌浏览器

**Bug 描述**
【问题描述】：折线图数据显示问题，保留两位小数不成功

**Bug 重现步骤(有截图更好)**
![企业微信截图_b4aeb399-f31e-4a55-b6a1-0ea1261e0f3a](https://user-images.githubusercontent.com/24768910/168556777-dfa0a9ef-c27b-44e2-ad72-48b2c3e51999.png)
![企业微信截图_a18f44cc-69dc-41eb-ba3f-7392e58dc2d2](https://user-images.githubusercontent.com/24768910/168556816-b0040efd-b94a-40d3-a588-663c8cc577f5.png)
![企业微信截图_b6da0854-9e8c-4801-a2c5-5eb1b69338a8](https://user-images.githubusercontent.com/24768910/168556831-85226727-a5b1-420f-a64c-d6fabed55e34.png)
![image](https://user-images.githubusercontent.com/24768910/168556716-754786ef-2c39-4d65-929a-7e35ca1755b2.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，需要确认一下，其次您是用的什么库？以那种方式获取的数据，是直连还是定时同步？

**Comment by AndroidBaby1** [comment]
【数据库】：MySQL
【获取方式】：定时同步

**Comment by BBchicken-9527** [comment]
定时同步是doris中拿到的数据，目前doris精度存在一定的问题，正在努力修复，已知问题。感谢你的反馈，我们会尽快修复此问题，
