### ISSUE TITLE
[Feature]数据集数据库对象排列友善

### ISSUE THREAD

**Issue by Larry3z** [dataease/dataease#2263]
**请描述您的需求或者改进建议.**
![dataease#advice1](https://user-images.githubusercontent.com/20963863/168716167-b10c5eae-1a10-4427-994d-7af4e64d8f82.png)

**Comment by yayanpei** [comment]
感谢您的反馈，目前是按照首字母顺序平铺排列的，如果数据库表比较多，也可通过右上角搜索。
