### ISSUE TITLE
权限开放，以便其他系统整合

### ISSUE THREAD

**Issue by yangjunzhou861012** [dataease/dataease#2265]
**请描述您的需求或者改进建议.**
目前有个这样的一个项目，已经做了不少功能，但现在系统想加上dataease功能，以便解决报表开发的功能，可是整合进项目的时候，因为权限的体系和架构不一样，我们想用项目本身的权限控制，请问一下，这个权限可以做为插拔式的？或者去掉权限功能吗？或是有其他的好的建议吗？

**Comment by yayanpei** [comment]
感谢您的反馈，系统整合集成目前还不行，如果后期需要集成的话，可能需要把两边的用户做一下匹配，通过传用户参数给dataease的形式来实现，dataease的权限不仅包括用户权限，还包括用户对数据的权限管控，建议先申请个license试用一下，企业版试用：https://jinshuju.net/f/TK5TTd
