### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by fanmaoyang** [dataease/dataease#2268]
**DataEase 版本**

v1.10.0
**运行方式(安装包运行 or 源码运行 ?)**
离线安装方式

**浏览器版本**
chrome:92.0.4515.131

**Bug 描述**

添加SQL数据集，选择定时同步，编写SQL语句，点确认时报错，报名内容如下：
“Data source connection exception: Communications link failure The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server”

**Bug 重现步骤(有截图更好)**
1.
![1](https://user-images.githubusercontent.com/46638118/168929319-fa2853b0-4f19-4af4-bd4d-a2024e9d5c04.jpg)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，麻烦确认一下你的数据源是否有效。

**Comment by xuwei-fit2cloud** [comment]
请检查一下doris运行状态及连接信息是否正确
