### ISSUE TITLE
[Bug]时间过滤组件失效

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2269]
**DataEase 版本**
1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 100.0.4896.88（正式版本） (arm64)

**Bug 描述**
时间过滤组件对 拼接字符串再转化成时间格式 的字段 不生效

**Bug 重现步骤(有截图更好)**
1.以官方数据集为例
![image](https://user-images.githubusercontent.com/24768910/168940509-39dbb878-e76b-4b66-945d-88c87c0d4d85.png)

2.用字符串拼接的方式创建一个时间字段
![image](https://user-images.githubusercontent.com/24768910/168940447-ea0c9048-8964-450d-ace1-3e6ebad4bc6a.png)

3.使用改视图插件一个 AntV 图库下的明细表视图，在仪表板中我们可以看到有 2022-04-01 这个值
![image](https://user-images.githubusercontent.com/24768910/168940595-b1a1e98d-a4cb-464a-87a5-fb998f404d8e.png)

4.以下三种时间过滤组件皆不生效
![image](https://user-images.githubusercontent.com/24768910/168940794-cf1a2120-4ead-4d92-a62f-3ff065f37b0c.png)
![image](https://user-images.githubusercontent.com/24768910/168940816-59c3447a-a012-4188-ad00-337d39590cd5.png)
![image](https://user-images.githubusercontent.com/24768910/168940844-59b0f708-bc53-4382-9977-46056792c3b9.png)

**Comment by xuwei-fit2cloud** [comment]
concat函数创建出来的计算字段，其类型是文本类型，而不是时间类型。
可以修改一下计算字段的公司，类似 STR_TO_DATE(CONCAT('2022-', [a2026ff9-34ad-4115-a25d-364e6d0d9fd3], '-01'),'%Y-%m-%d')，加上STR_TO_DATE，将文本转成时间类型即可。

**Comment by AndroidBaby1** [comment]
这样确实是可以解决当前的问题，但是站在用户角度上来说确实不够友好。因为用户确实是设置成了时间格式，系统也没在数据集处报错，且时间预览处也确实显示了对应的时间结果。所以这一块可能还需要再斟酌一下，不过优先级不是那么高啦！

**Comment by BBchicken-9527** [comment]
你说的确实，这个问题我们会好好的商量一下解决办法，感谢反馈。
