### ISSUE TITLE
[Bug]系统管理-站内消息-菜单选中背景颜色问题

### ISSUE THREAD

**Issue by huguangya** [dataease/dataease#227]
**DataEase 版本**
1.0.1

**浏览器版本**
谷歌

**Bug 描述**
![image](https://user-images.githubusercontent.com/54281046/125404225-fbb82800-e3e8-11eb-8233-e2f5e6b52172.png)

**Bug 重现步骤(有截图更好)**
1.见截图

**Comment by xuwei-fit2cloud** [comment]
此功能非 v1.0.1 版本发布的正式功能
