### ISSUE TITLE
[Bug]精简模式同步API数据集报错“Incorrect string”

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2276]
**DataEase 版本**
v1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 101

**Bug 描述**
精简模式下配置的 DE 自己的 MySQL 数据库为数据引擎，在同步某个 API 数据集时报错，错误信息为“java.sql.SQLException: Incorrect string value: '\xF0\x9F\xA5\xBA\xE7\x9C...' for column 'C_a9fc96ea9e1a90c0012acdab34b72105' at row 10”。

**Bug 重现步骤(有截图更好)**
1.配置了多个 API 数据源与数据集，其中有一个同步失败的情况；
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/48945409/169239952-0d23570c-2ea7-408d-9bde-1e7dfa1148a9.png">

2.查看失败详情如下：
<img width="860" alt="image" src="https://user-images.githubusercontent.com/48945409/169240017-3dd604e2-32c5-4054-bef2-580f38b6814f.png">

3.API 地址为：https://api.github.com/repos/halo-dev/halo/issues

4.在本地模式下同步是正常的。

**Comment by xuwei-fit2cloud** [comment]
这个应该是中文引起的，是数据库编码导致的，可以将编码改为 utf8mb4

**Comment by luyang351** [comment]
使用 DE 自己的 MySQL 作为引擎的，本身字符集即是 utf8mb4，且其它有中文的情况也可以，当时只有那一个会报错。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
