### ISSUE TITLE
[Feature]建议在新建同步任务时数据集无数据无需提示“请先完成数据同步”

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2277]
**请描述您的需求或者改进建议.**
该数据集还未做过同步，且无数据同步任务，我当前到同步任务下去新建任务的目的就是为了完成数据同步，这个场景下弹出“请先完成数据同步”感觉很奇怪。
<img width="1656" alt="image" src="https://user-images.githubusercontent.com/48945409/169243128-9e44e826-7ce1-48e8-9e3a-827f71f827d2.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，此处提示是因为预览导致的，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.11.0 版本已处理
