### ISSUE TITLE
[Bug] DB2 10 版本，SQL数据集及数据库数据集添加报错

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2278]
**DataEase 版本**
v1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 101.0.4951.54

**Bug 描述**
DB2 10 版本，SQL数据集及数据库数据集添加报错
异常信息如图：
![image](https://user-images.githubusercontent.com/30063018/169242194-30c68837-bd77-459b-856e-c734f445974e.png)

**Bug 重现步骤(有截图更好)**
1. DB2 版本  10.1.3
![image](https://user-images.githubusercontent.com/30063018/169242347-c2c042d1-d000-4759-9d63-7b7e9cf9922d.png)

2. 数据源接入信息如下
![image](https://user-images.githubusercontent.com/30063018/169242676-7e7f6ba7-5152-4246-9f14-7c7620766d69.png)

3. 添加数据库数据集，数据库表显示正常，点击确认后预览数据集报错
![image](https://user-images.githubusercontent.com/30063018/169242948-2dee18ee-81db-4d9e-a253-bd6ab730682f.png)
![image](https://user-images.githubusercontent.com/30063018/169242994-1e17af54-2e9c-48d5-8cfb-ed2a9f11e548.png)

4. 添加 sql 数据集，数据预览报错
![image](https://user-images.githubusercontent.com/30063018/169243213-4ae0e38b-689e-441f-b131-7bf44fcd644a.png)

5. 跟sql结尾的 ; 有关，好像多驱动自己又拼了个 ; 号，去掉之后可以正常预览
![image](https://user-images.githubusercontent.com/30063018/169244548-61833c59-83bd-443a-9d45-a161874eb105.png)
![image](https://user-images.githubusercontent.com/30063018/169244623-2068c606-7930-492e-b50f-dfef9c29b3d1.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
