### ISSUE TITLE
[Bug]文本组件字体颜色设置不生效

### ISSUE THREAD

**Issue by huguangya** [dataease/dataease#228]
**DataEase 版本**
1.0.1

**浏览器版本**
谷歌

**Bug 描述**
按照如下操作，文本组件字体颜色设置不生效。（之前正常的，按照如下操作后颜色就一直是黑色了）

**Bug 重现步骤(有截图更好)**
1.文本组件-组件标题不启用
![image](https://user-images.githubusercontent.com/54281046/125411590-a5e77e00-e3f0-11eb-9c3c-bc11be3edb68.png)

2.修改字体颜色
![image](https://user-images.githubusercontent.com/54281046/125411457-86e8ec00-e3f0-11eb-987b-c2fe111a6ccb.png)

3.在仪表盘中字体还是黑色
![image](https://user-images.githubusercontent.com/54281046/125411749-f3256118-5312-4fb4-90ca-6e85c7a5fe2c.png)

**Comment by XiaJunjie2020** [comment]
视图中样式优先级，调整至视图优先即可
