### ISSUE TITLE
[Feature]静态资源请求路径添加自定义前缀路径

### ISSUE THREAD

**Issue by luckymuye** [dataease/dataease#2280]
我在nginx里面配置 了  www.xxxx.com/dataease/  如下配置：
`
location ^~/dataease/ {
           proxy_set_header Host $http_host;
           proxy_set_header X-Real-IP $remote_addr;
           proxy_set_header REMOTE-HOST $remote_addr;
           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
           proxy_pass http://127.0.0.1:8082/;
        }

`
请求静态资源的时候没法，静态资源请求的路径是 
www.xxxx.com/js/chunk-2d2138e8.36e615f5.js，
无法匹配到相应的静态资源，建议增加相应的静态资源的前缀自定义方式，这样 可以通过 如下方式访问到
www.xxxx.com/dataease/js/chunk-2d2138e8.36e615f5.js  
->
http://127.0.0.1:8082/js/chunk-2d2138e8.36e615f5.js

**Comment by yayanpei** [comment]
感谢反馈，建议您参考我们的前后端分离部署文档进行配置，文档地址：https://dataease.io/docs/dev_manual/dev_deployment/tool/

**Comment by dayzKo1** [comment]
文档地址404了，有最新地址吗

**Comment by dayzKo1** [comment]
@yayanpei-fit2cloud
