### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2281]
**请描述您的需求或者改进建议.**
希望 Echarts 图库的折线图、柱状图等图形可以增加调节边框的距离的设置，现在空白太多了，谢谢。
![wecom-temp-617002e70efc2ef8569024a1f9d45230](https://user-images.githubusercontent.com/24768910/169266291-4dc96b17-ec47-4a23-83e8-1ccc2cae1004.png)

**Comment by yayanpei** [comment]
感谢反馈，留白受限于echarts图库，暂时调整不了，建议您先使用antv图库的折线图、柱形图。
