### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by sherryleeli** [dataease/dataease#2283]
数据集导入本地excel数据时，已经追加成功之后，发现追加的数据有误时，无法删除掉追加的有误的那部分数据，希望在数据集编辑excel时，追加成功的数据也能实现删除功能

![image](https://user-images.githubusercontent.com/20622441/169435499-64636432-864a-40e5-8c1a-a5ce3e6c6d34.png)

**Comment by yayanpei** [comment]
感谢反馈，目前数据集的数据是不支持系统内编辑的，如果发现数据追加有误，建议将全部数据在excel中整理好，选择替换操作，修正数据。
