### ISSUE TITLE
[Bug]mysql里面的数据类型为bit(1)的字段在数据集中为空

### ISSUE THREAD

**Issue by xuyan-tail** [dataease/dataease#2284]
**DataEase 版本**
v1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**
edge浏览器

**Bug 描述**
想问一个问题  如果mysql里面的数据类型为bit  dataease建立数据库定时同步的数据集后 对应的字段就变成空

**Bug 重现步骤(有截图更好)**
1.新建mysql数据库，其中字段类型为bit(1)
2.date建立数据库数据集，选择定时同步
3.查看建立的数据集，对应的字段值为空的
![QQ截图20220520105203](https://user-images.githubusercontent.com/25627516/169439602-624d2800-8154-468e-a8f5-c22e78e427f3.png)
![QQ截图20220520105220](https://user-images.githubusercontent.com/25627516/169439656-9ac34692-b715-41c6-aca1-aa1de2e8bcff.png)
mysql版本号
![image](https://user-images.githubusercontent.com/25627516/169444545-a1413f4b-532d-4d52-b66b-9949b4ebc69d.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
