### ISSUE TITLE
[Bug]仪表板复制后，指标卡中值的颜色会恢复为黑色

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#2286]
**DataEase 版本**
v1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
FireFox最新版
Chrome最新版

**Bug 描述**
指标卡视图中，值的颜色已设置非黑色，当复制整个仪表板时，新的仪表板指标卡的值颜色会恢复为黑色。

**Bug 重现步骤(有截图更好)**
1.  新建仪表板--添加指标卡；
2. 设置该数据集的指标卡颜色，选择红色，保存；
3. 复制该仪表板，在复制后的仪表板会发现，指标卡的值颜色恢复了黑色。

**Comment by yayanpei** [comment]
感谢反馈，我们尽快修复一下

**Comment by xuwei-fit2cloud** [comment]
v1.11.0 版本已修复
