### ISSUE TITLE
[Bug]复制仪表板 BUG

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2290]
**DataEase 版本**
1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 101.0.4951.64（正式版本） (arm64)

**Bug 描述**
1、复制仪表板生成的新仪表板，「图片组件」无法更换图片（毕现）。
![image](https://user-images.githubusercontent.com/24768910/169728295-aaf0e5f5-9dcf-4931-80b7-c09febb6dc66.png)
2、指标卡组件的文本颜色显示会置灰，但是在属性栏位还是原仪表板对应的颜色（毕现）。
![image](https://user-images.githubusercontent.com/24768910/169728294-0e84f1a5-aa3b-4cc8-90bf-c1f4c5876a12.png)

**Comment by maqiangyuen** [comment]
感谢反馈，指标卡问题为已知问题，会尽快修复，图片问题是复制之后的仪表板无法更换图片吗？

**Comment by AndroidBaby1** [comment]
图片组件无法更换图片

**Comment by maqiangyuen** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yayanpei** [comment]
感谢反馈，图片组件问题，我们尽快修复一下

**Comment by xuwei-fit2cloud** [comment]
v1.11.0 版本已修复

**Comment by maqiangyuen** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
