### ISSUE TITLE
[Question]想问一下为什么用clickhouse数据源的SQL数据集不支持定时同步

### ISSUE THREAD

**Issue by nigel001** [dataease/dataease#2298]
**请描述您的问题.**
想问一下为什么用clickhouse数据源的SQL数据集不支持定时同步

**Comment by ywhfzy** [comment]
截取码云 DataEase 官方回复：
定时同步模式，其实就是定期将数据同步到DataEase内置的doris里，CK本身性能和doris是不相上下的，且DataEase内置的docker方式运行的doris，其性能并不能和外置的CK相比，所以我们认为CK数据源没有支持定时任务的必要。
