### ISSUE TITLE
[Bug]创建 Excel 的关联数据集提示“当前用到的数据源已被删除”

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2301]
**DataEase 版本**
v1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 101

**Bug 描述**
在 v1.10.0 版本下创建 Excel 的关联数据集，保存时会提示“当前用到的数据源已被删除”，部署模式为本地模式。

**Bug 重现步骤(有截图更好)**
1.创建关联数据集，选择两个数据集均为 Excel，预览时没有问题，保存时报错。
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/48945409/170007924-08c8beb6-d817-4a32-97a0-ee150e81d42f.png">

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/48945409/170007255-a38be17d-703c-47c2-92f9-9b6d6bd12a9b.png">

**Comment by BBchicken-9527** [comment]
感谢反馈。我们验证一下
