### ISSUE TITLE
[Bug] mongoDB 数据集，制作明细表时拉入指标报错

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2306]
**DataEase 版本**
v1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
Google Chrome 101.0.4951.54

**Bug 描述**
mongoDB 数据集，制作明细表时拉入指标报错，如图所示：
![image](https://user-images.githubusercontent.com/30063018/170212642-8ca30926-9281-4bee-a47f-0de32492e6d9.png)

**Bug 重现步骤(有截图更好)**
1. 添加MongoDB 数据集，如下所示：
![image](https://user-images.githubusercontent.com/30063018/170217301-3d4df877-fbe2-4021-ac54-e3461468cbd5.png)

2. 创建明细表视图，拖拉维度时没有问题，拉到指标时就发生了报错。
![image](https://user-images.githubusercontent.com/30063018/170227111-c0a8befb-c319-412e-b2cc-0b7fd1854e7f.png)
![image](https://user-images.githubusercontent.com/30063018/170227183-ef3f0590-b3a7-4c31-ae10-d657115ab1fa.png)

3. 试了下其他的视图，都可以正常展示，只有明细表存在该问题，Echarts及AntV的明细表都存在问题
![image](https://user-images.githubusercontent.com/30063018/170227693-fc259e33-e906-4fdc-9f43-f0f8464c705d.png)

**Comment by maqiangyuen** [comment]
感谢反馈，我们会尽快修复
