### ISSUE TITLE
[Bug] Oracle 11g ，有 blob 类型字段的表添加数据集失败

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2309]
**DataEase 版本**
v1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome  101.0.4951.54

**Bug 描述**
Oracle 11g ，有 blob 类型字段的表添加数据集失败

**Bug 重现步骤(有截图更好)**
1. 数据库版本如下：
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

2.建表语句如下：
create table blob_test
(id int ,
 image blob);

3. 添加数据库数据集预览报错如下：
![image](https://user-images.githubusercontent.com/30063018/170401600-49cdb62a-b68d-47ea-929b-fa1662af5d7b.png)

4. 添加 SQL 数据集预览报错如下：
![image](https://user-images.githubusercontent.com/30063018/170401686-9783a3d8-ec32-4ede-9c87-85eadca2c873.png)

5.看网上有同样的问题，是因为使用 String 接收了 Blob 类型的字段导致的，改为用 byte[] 接就可以，供参考
https://www.javacodegeek.com/2020/07/invalid-column-type-getString-getNString.html

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by Liuhailong2016** [comment]
BLOB字段在OLAP中一般不会使用，可以在数据集中对表中BLOB字段进行删除。但操作时，报“字段表达式语法错误”
![image](https://user-images.githubusercontent.com/22953858/173316939-1e513be3-e7d7-403c-95c7-e7c534479782.png)
