### ISSUE TITLE
[Feature] 仪表板-视图-地图

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#2316]
**请描述您的需求或者改进建议.**
版本 v1.10.0
地图右下角 High 和 low 建议可跟随标题颜色更变，不然在视图背景颜色更变后，黑色太凸显了
![image](https://user-images.githubusercontent.com/96223591/170432971-c5265505-74c5-4f16-9516-c6612a8bc994.png)

**Comment by yayanpei** [comment]
感谢反馈，您的建议很不错，我们优化一下

**Comment by fit2cloudrd** [comment]
v1.12.0版本已处理，请等待新版本发布
