### ISSUE TITLE
[Bug] 视图优先级切换，标题样式没切换回来，还是仪表板的

### ISSUE THREAD

**Issue by zhangchaochao-fit2cloud** [dataease/dataease#2328]
**DataEase 版本**
v1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Microsoft Edge
版本 101.0.1210.53 (正式版本) (64 位)

**Bug 描述**
切换视图的样式优先级，标题的透明度没有切换回来视图的设置
![image](https://user-images.githubusercontent.com/70739359/170620374-8aedb464-9c12-4c9f-8949-eb00ca28f4ea.png)
![image](https://user-images.githubusercontent.com/70739359/170620196-3494b71d-b3e0-4a5e-ad9d-8d30e1b7f2d2.png)
![image](https://user-images.githubusercontent.com/70739359/170620295-b3eb1fe4-8f56-495e-85e7-e10a6afa2326.png)

**Bug 重现步骤(有截图更好)**
1. 使用 AntV 的基础折线图
2.把组件样式中的不透明设置为0
3.切换视图的样式优先级

**Comment by BBchicken-9527** [comment]
感谢反馈我们会尽快修复
