### ISSUE TITLE
[Bug] 视图优先级切换后，选择不保存仪表板，查看效果是已经保存了

### ISSUE THREAD

**Issue by zhangchaochao-fit2cloud** [dataease/dataease#2329]
**DataEase 版本**
v1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Microsoft Edge
版本 101.0.1210.53 (正式版本) (64 位)

**Bug 描述**
视图的优先级切换后，选择不保存仪表板，但是实际上是保存了
![image](https://user-images.githubusercontent.com/70739359/170623378-fed66f71-61c9-4f1d-b292-30bbae42d2dc.png)
![image](https://user-images.githubusercontent.com/70739359/170623423-e4ba2119-edde-45ff-9a31-b3deb40835e1.png)

**Bug 重现步骤(有截图更好)**
1.选择视图是 AntV 的基础折线图
2.编辑视图，修改视图优先级
3.直接点击关闭，选择不保存
4.查看视图，发现已经保存了

**Comment by BBchicken-9527** [comment]
感谢反馈，目前逻辑保存只负责仪表板样式等内容，视图因为历史原因是实时保存的。
