### ISSUE TITLE
[Bug]使用外部参数进入仪表盘，放置一段时间后，视图内容变化为其他参数的内容

### ISSUE THREAD

**Issue by GitProBo** [dataease/dataease#2336]
**DataEase 版本**
1.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 版本 101.0.4951.64（正式版本） (x86_64)

**Bug 描述**
1. 仪表盘设置外部参数，并设置好联动的视图
2. 共享仪表盘，并使用外部参数进入
3. 放置5分钟左右后，视图内容变化为其他参数的内容

**Bug 重现步骤(有截图更好)**
1.刚进入时展示的内容
<img width="1274" alt="WX20220528-212631@2x" src="https://user-images.githubusercontent.com/18132900/170827724-62f852bd-4a94-4b5c-9655-18da923fa6f8.png">

2.放置5分钟左右内容变化
<img width="1273" alt="WX20220528-212617@2x" src="https://user-images.githubusercontent.com/18132900/170827730-38059ec4-b40e-44d4-b1a0-7cc2ff1c2beb.png">

3. 经过测试，同时打开仪表盘的多个不同外部参数的链接时才会复现，疑似与后台更新视图缓存机制有关

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
