### ISSUE TITLE
[Feature]excel创建关联数据集保留原数据类型

### ISSUE THREAD

**Issue by knikht** [dataease/dataease#2339]
**请描述您的需求或者改进建议.**
使用excel集创建关联数据集时，原数据集数据类型有文本、数值、时间，但是创建的关联数据集类型只有文本。因为关联数据集是用原有数据集创建的，因此希望保留原数据类型。
![图片](https://user-images.githubusercontent.com/104270483/170833099-ee9e8cb5-d1af-4638-b776-de1aa5f54171.png)
![图片](https://user-images.githubusercontent.com/104270483/170833107-d92d1d6e-a1e4-40d8-915b-59fcdaabe205.png)

**Comment by yayanpei** [comment]
感谢您的反馈，关联数据集创建时是保留了原数据类型的，请问在创建了关联数据集后，原excel数据集有做过修改或者替换吗？我微信：18317092178，方便的话，可以加一下我微信进一步沟通交流。
