### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2353]
**DataEase 版本**
1.11.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
批量更新视图样式

**Bug 重现步骤(有截图更好)**
1.批量勾选仪表板某两个视图，选择颜色风格【商务】；
![image](https://user-images.githubusercontent.com/24768910/170945725-7387b057-68ec-4722-91bc-db1d72aa7fb0.png)
2.再勾选第三个视图；
![image](https://user-images.githubusercontent.com/24768910/170945898-3231a53f-4002-47ea-9657-c853d05eff9e.png)
3.配上继续选择【商务】，发现第三个视图并没有改成商务风格

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这是开发分支的功能，还没发布，我们正在努力测试和修复中。
