### ISSUE TITLE
[Bug]mysql表中有json格式字段定时同步失败

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#2364]
**DataEase 版本**
1.10

**Bug 描述**
![image](https://user-images.githubusercontent.com/101089844/171125301-e73e99f0-0294-49bd-8c23-69a801a9f68d.png)

**Bug 重现步骤(有截图更好)**
1.mysql表中有json格式字段定时同步失败
测试内容如下
<img width="377" alt="image" src="https://user-images.githubusercontent.com/101089844/171129704-942955b8-9451-495e-9a37-bbfafa85227f.png">

**Comment by BBchicken-9527** [comment]
感谢反馈。测试环境中没有发现此类问题，测试环境为最新版本，可以尝试升级看看

**Comment by hcff2c** [comment]
已经升级，含有jion类型字段，添加mysql数据集选择定时同步模式会失败

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
问题以修复，可在新版本中体验
