### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by liutianyuan** [dataease/dataease#2380]
版本1.8.0。使用源码部署安装。之前使用正常，突然出现两个问题：
1、新建仪表板和目录时，报错 io.dataease.exception.DataEaseException: 未查询到用户对应的资源权限，请尝试刷新重新保存
2、新添加数据集，数据源，页面提示成功，数据库里也确实保存了，但是页面显示不出来。

谢谢。

**Comment by yayanpei** [comment]
感谢反馈，刷新不出来，可能是查询超时了，尝试将超时事件设置大一些试试。
<img width="692" alt="image" src="https://user-images.githubusercontent.com/84168063/179954939-2a884e07-001a-4333-b1ec-402d54da6f66.png">
