### ISSUE TITLE
[Feature]天气数据源及天气图表类型支持

### ISSUE THREAD

**Issue by yhl173** [dataease/dataease#2381]
因做数据大屏需求
需要展示实时不同地区天气情况，及历史天气情况
期望产品后期可以支持天气情况动态图表展示

期望DataEase后期可以 默认集成相关天气数据接口，方便通过修改参数实现接口调用
非常感谢提供如此优秀的数据分析产品

**Comment by yayanpei** [comment]
感谢反馈与支持，您的建议我们已收到。

**Comment by yhl173** [comment]
补充开源天气图标资料
https://dev.qweather.com/docs/resource/icons/
https://github.com/qwd/Icons

**Comment by yayanpei** [comment]
感谢您的提供，资料已收到
