### ISSUE TITLE
[Feature]数据同步失败按钮附近添加提示

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#2384]
**请描述您的需求或者改进建议.**
<img width="721" alt="企业微信截图_befe50de-2eb6-484f-b06d-cc2cd4a1bc46" src="https://user-images.githubusercontent.com/101089844/172293122-cfdf08ca-4e2b-4a64-a311-027bc0c70922.png">
数据同步失败时，经常有人不知道在哪里看报错日志，个人感觉可以在“失败”附近添加灰色小字提示点击“失败”查看错误日志

**Comment by yayanpei** [comment]
感谢您的反馈，您的建议很不错，我们会优先考虑加入优化中。
