### ISSUE TITLE
[Bug]文本搜索组件中，按表/组件选择多个字段后（单个字段可以），在最终视图中筛选不生效

### ISSUE THREAD

**Issue by Fit2CloundGhh** [dataease/dataease#2386]
**DataEase 版本**
v1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 102.0.5005.61（正式版本） (x86_64)

**Bug 描述**
文本搜索组件中，按表/组件选择多个字段后（单个字段可以），在最终视图中筛选不生效

**Bug 重现步骤(有截图更好)**
按表选择字段效果：
1.编辑文本搜索框
![image](https://user-images.githubusercontent.com/92966838/172316864-77a52198-a47c-4526-b073-5b628e311ffa.png)
2.提交并保存，在当前编辑界面和仪表板界面执行搜索
![image](https://user-images.githubusercontent.com/92966838/172317281-cccf8afc-6a2b-457a-97d1-fea4cd9bc48a.png)
![image](https://user-images.githubusercontent.com/92966838/172317438-cc4e03c2-ebeb-479a-bfc3-06bfa22676e5.png)

按组件选择效果：
1.编辑文本搜索框
![image](https://user-images.githubusercontent.com/92966838/172317577-6476a844-1ae7-4171-9a9b-064548a2b1e2.png)
2.提交并保存，在当前编辑界面和仪表板界面执行搜索
![image](https://user-images.githubusercontent.com/92966838/172318035-52168bc9-48e9-4feb-893f-c8372c1ec754.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，添加多个过滤字段无法过滤的原因是因为两个字段是与的关系，也就是说name=“男” and sex=“男”

**Comment by Fit2CloundGhh** [comment]
明白，如果组件暂不支持 & | 逻辑选择，建议先在功能点上做个说明吧

**Comment by BBchicken-9527** [comment]
你说的我们会讨论一下，看一下可行性，感谢反馈
