### ISSUE TITLE
[Bug]使用外部参数拼接仪表板链接后访问，提示“外部参数解析错误未生效，请按规定编码方式传参”

### ISSUE THREAD

**Issue by Fit2CloundGhh** [dataease/dataease#2387]
**DataEase 版本**
v1.10.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 102.0.5005.61（正式版本） (x86_64)

**Bug 描述**
使用外部参数拼接仪表板链接后访问，提示“外部参数解析错误未生效，请按规定编码方式传参”
![image](https://user-images.githubusercontent.com/92966838/172322695-14e4b4b9-3026-46ba-bd62-83bcd9fc637b.png)

**Bug 重现步骤(有截图更好)**
1.创建仪表板外部参数
![image](https://user-images.githubusercontent.com/92966838/172322772-73e9f3d3-374c-425e-bcbd-0e0a8a807da0.png)
2.定义JSON数据
![image](https://user-images.githubusercontent.com/92966838/172322942-c09f3ae7-cffa-4a12-8319-55da5ce755e3.png)
3.JSON数据Base64编码
![image](https://user-images.githubusercontent.com/92966838/172323020-fdb4b1bc-aa4a-4b13-8f7e-bbd663d7a5d6.png)
4.拼接访问链接
![image](https://user-images.githubusercontent.com/92966838/172323093-4c61bfb2-f253-4d14-b445-de932ff4132c.png)
5.提示解析错误
![image](https://user-images.githubusercontent.com/92966838/172322695-14e4b4b9-3026-46ba-bd62-83bcd9fc637b.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，加号不可以直接放到路由里面的，需要转换一下，否走url会自动将加号转换成空格
