### ISSUE TITLE
[Question]请问如何使用时间作为指标进行展示

### ISSUE THREAD

**Issue by tylor-e** [dataease/dataease#2390]
**请描述您的问题.**
当下遇到一个问题，我有我每天的打卡时间数据，想做一个打卡的折线图展示，但是涉及到时间作为指标，就只有计数了
虽然我可以处理一下用离一个基准时间的分钟数来作图，但是这样纵轴的标签就不对了，不能看到每个点的具体时间
请问有大神能给帮助吗？

**Comment by yayanpei** [comment]
感谢您的反馈，指标主要用于数学聚合计算，而时间数据作为指标，目前只能做计数处理。这种情况下，用折线图展示不太合适，建议您用明细表试试。
