### ISSUE TITLE
[Bug] 使用 MongoDB 关联数据集制作视图，仪表板使用过滤组件报错

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2393]
**DataEase 版本**
v1.11.1 

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 101.0.4951.54

**Bug 描述**
 使用 MongoDB 关联数据集制作视图，仪表板使用过滤组件报错

**Bug 重现步骤(有截图更好)**
1. 使用 MongoDB 数据集制作关联数据集
![image](https://user-images.githubusercontent.com/30063018/172523012-831fe9db-85a6-43e9-acbd-0985a04ed36c.png)

2. 使用关联数据集制作明细表
![image](https://user-images.githubusercontent.com/30063018/172523174-a2433b0f-e09d-45de-a725-c300df9f6484.png)

3. 添加过滤组件，视图展示报错
![image](https://user-images.githubusercontent.com/30063018/172523267-763363be-c4ad-4403-8887-503196227398.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by fit2cloudrd** [comment]
可以使用Mongodb-BI类型数据源对接试试。
