### ISSUE TITLE
[Bug] 柱状图辅助线，保存仪表板后关闭再此打开，编辑辅助线确认后辅助线会消失

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2394]
**DataEase 版本**
v1.11.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 101.0.4951.54

**Bug 描述**
柱状图辅助线，保存仪表板后关闭再此打开，编辑辅助线确认后辅助线会消失

**Bug 重现步骤(有截图更好)**
1. 仪表板新建柱状图，添加好辅助线，保存仪表板并关闭仪表板
![image](https://user-images.githubusercontent.com/30063018/172524584-c0036f87-207a-46e5-addd-0af9ad1a9c39.png)

2. 再次编辑仪表板，编辑视图，编辑辅助线，不修改任何内容，直接点击确认，辅助线消失
![image](https://user-images.githubusercontent.com/30063018/172525309-e0ff6cea-1b09-4ba9-bf26-0aaff77073c5.png)
![image](https://user-images.githubusercontent.com/30063018/172525392-c98d9cce-4034-4643-9389-1621dafdcb19.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
问题已修复，可在下次更新时下载体验。
