### ISSUE TITLE
[Feature]视图调整添加长宽设置

### ISSUE THREAD

**Issue by hzhfit2cloud** [dataease/dataease#2397]
**请描述您的需求或者改进建议.**
目前视图大小的调整只能通过拖拉的形式完成
当用户在制作一个相同大小的视图时往往难以用肉眼判断精准，并且不断对视图进行拖拉调整，效率较低

希望可以对视图的大小进行长宽的设置，这样可以大大提高视图大小调整的效率

**Comment by yayanpei** [comment]
感谢您的反馈，我们会认真考虑的。
