### ISSUE TITLE
[Feature]透视表列汇总算总计不按照列维度分开算

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#2398]
**请描述您的需求或者改进建议.**
如图在表格中，我想得到3月份鸡和鸭的总数量，在列汇总中无法计算，列汇总算总计是否可以不按照列维度分开算
![image](https://user-images.githubusercontent.com/101089844/172580820-c2dbfb13-1da3-4e1a-9810-671cd31d7564.png)

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。
