### ISSUE TITLE
希望数据集SQL增加占位符查询

### ISSUE THREAD

**Issue by Luo-99** [dataease/dataease#2399]
希望SQL直连模式下支持占位符查询

我试着改动了下代码,简单实现了
我是想着尽量改动最少的代码实现的
毕竟不熟悉代码,很多也看不懂,肯定没官方支持的好

由于不熟悉代码,很多也看不懂,技术有限
不过希望官方后续的版本可以支持这种方式的查询

这是示例图
![image](https://user-images.githubusercontent.com/22796879/172601356-63434754-6efa-409a-bf31-f5390c1dd9aa.png)

这是全部改动的地方
[SQL增加动态参数.pdf](https://github.com/dataease/dataease/files/8860912/SQL.pdf)

希望官方后续可以支持类似的功能吧

**Comment by yayanpei** [comment]
感谢您的反馈与支持，我们会认真考虑的
