### ISSUE TITLE
切换为英文，查看个人信息，左侧无空白区域，切换为中文，左侧有空白区域，再切换为英文，左侧依然有空白区域

### ISSUE THREAD

**Issue by liufei20151013** [dataease/dataease#24]
<img width="1439" alt="图片" src="https://user-images.githubusercontent.com/15103510/123392398-97672d00-d5cf-11eb-82a6-2b4ebcf6aec8.png">
<img width="1439" alt="图片" src="https://user-images.githubusercontent.com/15103510/123392444-a3eb8580-d5cf-11eb-8a56-a125104db926.png">
<img width="1439" alt="图片" src="https://user-images.githubusercontent.com/15103510/123392496-b06fde00-d5cf-11eb-91cc-4b40a1e9f6e0.png">

**Comment by fit2cloud-chenyw** [comment]
fixed on commit 73f45d9d09ed6c4281e72e781a991a1738ebee08

**Comment by xuwei-fit2cloud** [comment]
已优化，请等待下一个版本 v1.0.1
