### ISSUE TITLE
数据集添加SQL数据集时候建议支持上下自由滑动sql输入框和数据预览高度，[Feature]

### ISSUE THREAD

**Issue by limin-fit2** [dataease/dataease#240]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/61964761/125638889-f803ef82-9936-4e2e-abb4-ab796494c7d4.png)

**Comment by yayanpei** [comment]
感谢您的反馈，您的建议是我们产品改进和优化的方向。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
