### ISSUE TITLE
[Bug] AntV 词云图重要展示内容被忽略

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#2400]
**DataEase 版本**
V1.11.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome  版本 102.0.5005.61（正式版本） (arm64)

**Bug 描述**
Antv 词云图默认展示视图丢失了统计数据最多的维度，与点击查看的视图统计数据不一致，差异较大。

**Bug 重现步骤(有截图更好)**
1.创建 AntV 词云图，拖拽项目为维度，*记录数（会议次数）为词大小，想突出展示会议次数最多的项目；
2.在仪表板中调整好大小，保存仪表板，在保存好的仪表板中查看词云图；
3.词云图展示效果如图所示，但是点击查看词云图视图明细，发现默认仪表板种展示的词语图丢失了关键数据展示，二者不统一，丢失了需要重点突出展示的重要信息。
截图一：
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/60059766/172752300-6c706394-6628-430d-b384-e50491821653.png">
截图二：
<img width="310" alt="image" src="https://user-images.githubusercontent.com/60059766/172752515-aeba40dd-dbcf-41cb-a638-299c1855b5fb.png">
截图三：
<img width="962" alt="image" src="https://user-images.githubusercontent.com/60059766/172752516-00555ea8-377d-46d5-a8d0-44f307798261.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，你说的关键数据是除项目名称和记录数以外的字段吗？
