### ISSUE TITLE
[Bug] DataEase 日志导出的xlsx 无法用excel打开

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2401]
**DataEase 版本**
1.11.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版本

**Bug 重现步骤(有截图更好)**
1.首先进入DataEase 的系统管理，点击日志，点击导出
![image](https://user-images.githubusercontent.com/82353425/172781401-3e93a1ac-e7d7-4dfc-a9eb-59fd6ff6067d.png)

2.用Excel工具无法打开
![5d2f4d8d-c9c5-4393-98aa-613b3f972f06](https://user-images.githubusercontent.com/82353425/172781502-6ab8b844-ca39-4ca1-9fea-805e0f9d8d7c.png)

3.将DataEase.xlsx 文件改成 DataEase.xls文件 就可以打开

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
