### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2402]
**DataEase 版本**
1.11.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 101.0.4951.64（正式版本） (arm64)

**Bug 描述**
在编辑仪表板的时候，更换视图的颜色，但是不保存仪表板，颜色还是更换掉了；

**Bug 重现步骤(有截图更好)**
复现简单

**Comment by BBchicken-9527** [comment]
感谢返回，因为视图是实时保存的，保存按钮只能选择保存或不保存仪表板样式等

**Comment by AndroidBaby1** [comment]
有两个点哈：
一个是用户会觉得挺奇怪的，我都没有保存，怎么就变了。
另一个就是如果某个用户动了仪表板某个视图的样式，但是他没有做保存这个动作，日志记录也不会记录谁动了这个仪表板中某个视图的样式，那岂不是谁改了的都不好排查（昨天交付的时候一个公司的用户提出的问题点）。

**Comment by BBchicken-9527** [comment]
感谢反馈，已经加入需求池中；
