### ISSUE TITLE
漏洞修复建议

### ISSUE THREAD

**Issue by keithwei0120** [dataease/dataease#2407]
dom4j: 2.0.x及以下版本的升级至2.0.3及以上版本；2.1.x的升级至2.1.3及以上commons_beanutils: 升级至1.9.4及以上版本。
netty: netty迁移至netty-all，并升级netty-all至最新版本4.1.71.Final。
shiro: 升级到1.8.0或以上版本。
log4j: Java 8及以上用户升级至2.16.0或以上版本，推荐升级至最新版本2.17.1；Java 7用户建议升级至2.12.4版本；
jackson-databind: 升级至2.13.2.2或以上版本。

**Comment by yayanpei** [comment]
您的建议我们已收到，会在后续的版本中进行优化，感谢对产品的关注和支持
