### ISSUE TITLE
[Bug] 视图，AntV 图库表格无法调整自定义列宽

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#2413]
**DataEase 版本**
v 1.11.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Microsoft Edge
版本 102.0.1245.33 (正式版本) (64 位)

**Bug 描述**
仪表板中的视图，AntV 图库表格类图表无法调整自定义列宽

**Bug 重现步骤(有截图更好)**
1. 示例图如下：
![image](https://user-images.githubusercontent.com/96223591/173035436-da106b19-55c6-41d0-99e4-5c1e18449f1a.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，是拖动表头行高和表格行高没有生效吗？
