### ISSUE TITLE
[Bug]使用本地模板新建仪表板有移动端布局但无移动端标识

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2415]
**DataEase 版本**
v1.11.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 102

**Bug 描述**
将带有移动端布局的仪表板导出为模板，再以模板创建仪表板，该仪表板不带有移动端布局的标识。

**Bug 重现步骤(有截图更好)**
1.将带有移动端布局的仪表板导出为仪表板模板
<img width="371" alt="image" src="https://user-images.githubusercontent.com/48945409/173271197-b6a966f4-61d5-404f-b15c-8444217ef583.png">

2.通过导入模板的方式创建仪表板，并使用刚刚的模板
<img width="613" alt="image" src="https://user-images.githubusercontent.com/48945409/173271255-3c8d21aa-28ad-4821-b260-19a251fe3ac5.png">

3.以该模板新建的仪表板查看移动端布局是有的，但是并未带有移动端布局的小图标
<img width="366" alt="image" src="https://user-images.githubusercontent.com/48945409/173271348-ef692db2-8023-4717-8696-ef7c62a5d8a7.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，因为缓存原因菜单栏没有及时更新，刷新即可，已知问题，正在讨论更好的处理方式
