### ISSUE TITLE
[Bug]移动端 Echarts 折线图的展示效果差别比较大

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#2416]
**DataEase 版本**
V1.11.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Web 端：
Chrome：
版本 102.0.5005.61（正式版本） (arm64)
移动端：
IOS操作操作系统通过微信直接点击链接地址

**Bug 描述**
在 Web 端设置 ECharts 的折线图的图标大小，在移动端展示效果与 Web 端的展示效果差异较大

**Bug 重现步骤(有截图更好)**
1.在 Web 端制作 ECharts 类型的基础折线图视图，制作完成后设置折线图样式；
2.图形属性中的大小设置为3，在 Web 端展示效果ok；
3.设置移动端，调整适当大小，同时创建共享链接地址；
4.在苹果ios操作系统的微信上直接点击共享链接地址查看移动端的基础折线图，效果与web端相差较大；
5.另外在移动端布局时仪表板中的矩形框样式效果在可选框中展示与实际矩形框样式不一致，且移动端没法进行叠加布局。
步骤一：
<img width="330" alt="image" src="https://user-images.githubusercontent.com/60059766/173270748-e65c47f8-2bae-492d-8eba-67f9d87e2856.png">
步骤二：
<img width="477" alt="image" src="https://user-images.githubusercontent.com/60059766/173270877-53fd0426-5bba-4a79-93e0-777aeee73dfe.png">
步骤四：
![image](https://user-images.githubusercontent.com/60059766/173271242-951659b7-d3db-40cd-b30b-532f24c23a01.png)
步骤五：
<img width="821" alt="image" src="https://user-images.githubusercontent.com/60059766/173271641-190e23ff-c0bf-4c60-83b8-727e7f5f227a.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
