### ISSUE TITLE
[Bug]字段没有按DataEase中选择的类型排序

### ISSUE THREAD

**Issue by hzhfit2cloud** [dataease/dataease#2420]
**DataEase 版本**
v1.11.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 102.0.5005.61

**Bug 描述**
如果字段原始类型为“文本”类型，那么即便在数据集中选择字段类型为“数值”，在字段排序时仍然不会按照“数值”类型进行排序

**Bug 重现步骤(有截图更好)**
1.官方示例数据库表字段把月份修改成了文本类型
<img width="922" alt="image" src="https://user-images.githubusercontent.com/89765365/173479250-c4285c7a-a403-4ed4-992a-4b251dce1bfb.png">

2.仪表板中图表字段类型进行升序排序
<img width="640" alt="WechatIMG272" src="https://user-images.githubusercontent.com/89765365/173479612-d018231d-3572-4ebc-89ed-fe28db068a3f.png">

3.没有按照数值类型进行排序，而是文本类型排序的

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，将会在下个版本发布

**Comment by PheonixHkbxoic** [comment]
1.11.2版本 问题仍然存在
