### ISSUE TITLE
[Feature]组合图可以对主纵轴和副纵轴分别指定不同的提示内容格式吗

### ISSUE THREAD

**Issue by hzhfit2cloud** [dataease/dataease#2423]
**请描述您的需求或者改进建议.**
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/89765365/173508920-4af8e3b5-779b-45b2-aa5f-4eb5d99cdbe2.png">

目前组合图的提示样式是统一指定的
能否
柱状图指定提示内容格式为：{c}
折线图指定提示内容格式为：{c}%

**Comment by yayanpei** [comment]
感谢您的反馈，目前还不支持单独设置，我们先记录一下。
