### ISSUE TITLE
[Bug]分享仪表板跳转到新仪表板无权限permission

### ISSUE THREAD

**Issue by yunti5689** [dataease/dataease#2425]
**DataEase 版本**
1.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
edge, chrome

**Bug 描述**
打开另一个账号分享过来的仪表板, 点击跳转打开新仪表板链接, 报permission错误

**Bug 重现步骤(有截图更好)**
1. 创建明细表视图, 设置跳转-仪表板-新开页面, 分享本页和跳转目标页给其它用户
2. 其他用户可以正常浏览本页和目标页, 但点击本页上的跳转链接报无权限异常
3.![image](https://user-images.githubusercontent.com/30047501/173724766-364bb90f-e151-4b7f-b997-b1ab06cdf9c3.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
如果无目标仪表板的查看权限，是不允许直接跳转的，否则会出现越权的情况。此处我们已完善提示信息。
