### ISSUE TITLE
[Feature]标签太长希望可以自动换行展示

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#2427]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/101089844/173736621-1c880437-9db3-4c8b-9a13-115550af46a9.png)
空间不大，标签太长展示受阻，拉长就会跑到别的视图上去，希望可以自动换行

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到
