### ISSUE TITLE
[Bug]普通用户可上传插件至任意代码执行

### ISSUE THREAD

**Issue by Ryze-T** [dataease/dataease#2431]
**DataEase 版本**
最新版

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
任意

**Bug 描述**
普通用户可上传插件至任意代码执行

**Bug 重现步骤(有截图更好)**
在官网编译插件，并在主要连接presto的功能处加入恶意代码：
<img width="949" alt="image" src="https://user-images.githubusercontent.com/76553352/173777803-7efc6013-cbf1-4529-8baa-0384a0c0fd38.png">
插件安装处未鉴权，普通用户可调用接口上传插件：
<img width="973" alt="image" src="https://user-images.githubusercontent.com/76553352/173777598-2ae69ad6-1246-41ea-9062-d751d9cf86af.png">
上传成功后普通用户新建presto数据源：
<img width="972" alt="image" src="https://user-images.githubusercontent.com/76553352/173777925-9f3af872-9750-4cc8-8aa8-a4342d63d8f8.png">
查看dnslog平台：
<img width="783" alt="image" src="https://user-images.githubusercontent.com/76553352/173777990-56e6a402-718a-4188-9c20-e81eb8c9fcf7.png">
命令成功执行

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复。

**Comment by maninhill** [comment]
v1.11.2 已修复，详情请参考：https://github.com/dataease/dataease/releases/tag/v1.11.2
