### ISSUE TITLE
[Bug]对接MongoDB数据库，表格视图使用日期显示、日期格式设置无效，使用排序报错

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#2432]
**DataEase 版本**
1.11.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌最新版

**Bug 描述**
对接MongoDB数据库，表格视图使用日期显示、日期格式设置无效

**Bug 重现步骤(有截图更好)**
1.对接MongoDB数据源，配置数据集
2.创建仪表板，选择明细表视图
3.选择时间维度，选择日期显示，设置哪个都无效
4.选择日期格式，设置哪个都无效
![d76e08bb65c8177c97a8f578a7da0bb](https://user-images.githubusercontent.com/35896106/173786158-f8322481-aaed-4274-aba5-344df346701e.png)

5.选择升序或者降序，页面直接报错
![image](https://user-images.githubusercontent.com/35896106/173786104-57d26d3c-8af9-47f8-8779-01c8b4b8295f.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，MongoDB此处driver对一些字段的支持较低，我们正在考虑这个问题如何解决

**Comment by BBchicken-9527** [comment]
问题已修复，将会在下个版本上线，到时可下载体验

**Comment by xuwei-fit2cloud** [comment]
v1.13.1版本已修复，请更新版本。
