### ISSUE TITLE
[Feature]支持配置视图动画相关参数

### ISSUE THREAD

**Issue by wan92hen** [dataease/dataease#2433]
**请描述您的需求或者改进建议.**

默认情况下，视图的动画都是打开的，例如展示一个折线图时会有每个数据点依次出现的动画效果。
有时候并不需要这样的动画效果，希望可以针对视图动画增加相关配置，可以选择关闭动画或配置时间等。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们会考虑加入相关功能。
