### ISSUE TITLE
[Bug]编辑关联数据集界面，API 数据集缺少 logo

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2435]
**DataEase 版本**
v1.11.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 102

**Bug 描述**
编辑关联数据集界面，API 数据集缺少 logo，其它数据集有对应的 logo。

**Bug 重现步骤(有截图更好)**
1.如下图所示，数据库数据集和 Excel 数据集名称前有 logo，API 数据集缺失 logo。
<img width="714" alt="image" src="https://user-images.githubusercontent.com/48945409/174006259-b81d90a4-8bbb-444a-be41-026b71770feb.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复。

**Comment by xuwei-fit2cloud** [comment]
问题已修复，请等待新版本发布

**Comment by xuwei-fit2cloud** [comment]
v1.11.2 版本已修复，请更新版本。
