### ISSUE TITLE
[Bug]打开视图的编辑栏，所对应的 Tab 与下方所展示的内容不一致

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2436]
**DataEase 版本**
v1.11.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 102

**Bug 描述**
打开视图的编辑栏，所对应的 Tab 与下方所展示的内容不一致。例如 Tab 的下划线在【数据】那，但是下方的内容属于【样式】的内容。

**Bug 重现步骤(有截图更好)**
1.编辑某视图的样式，并让 Tab 停留在【样式】一栏，此时关闭视图的编辑界面；
<img width="622" alt="image" src="https://user-images.githubusercontent.com/48945409/174007359-dbdc1ca5-9f40-4510-b46a-a867e5fd79bc.png">

2.再次打开视图的编辑界面；
<img width="598" alt="image" src="https://user-images.githubusercontent.com/48945409/174007622-64b9b245-01ca-47e2-8625-c0228e34999d.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
