### ISSUE TITLE
[Feature]建议设置背景图片后，可直接进行替换无需先删除再上传

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2438]
**请描述您的需求或者改进建议.**
1.仪表板背景图片设置后，如果想要替换背景，目前是需要先删除原图，再上传新图，过于繁琐，**系统可直接提供替换功能，一次完成**。
![image](https://user-images.githubusercontent.com/48945409/174010819-89c997fc-5bc4-46dd-a348-b3671c8cb736.png)
<img width="816" alt="image" src="https://user-images.githubusercontent.com/48945409/174009423-1c1c2f8a-be00-4254-a5bf-56346744e806.png">
2.组件的背景设置同理，希望可以直接替换。
<img width="872" alt="image" src="https://user-images.githubusercontent.com/48945409/174009598-2e7bb0c8-d638-4043-94c8-7d4af631ace0.png">

**Comment by yayanpei** [comment]
感谢反馈，我们优化一下
