### ISSUE TITLE
[Bug]仪表板分享给用户后，用户在仪表板中跳转出现Subject does not have permission报错

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#2445]
**DataEase 版本**
v1.11.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome、火狐最新

**Bug 描述**
用户A将仪表板分享给用户B后，用户B在仪表板中点击预设好的跳转功能，弹出新的浏览器页面报错 “Subject does not have permission[PANNEL_LEVEL_VIEW:PANEL:c46320d3-62ce-46dc-9686-f993bbf34adf] ”

**Bug 重现步骤(有截图更好)**
1. 用户A创建仪表板，并通过分享功能分享给用户B；
2. 用户B登录，通过分享标签，打开用户A分享过来的仪表板；
3. 用户B在仪表板中点击图形的跳转菜单，弹出新的浏览器标签页，并报错如下图：

![图片](https://user-images.githubusercontent.com/48307752/174510942-74b21b52-90a6-43a3-9a83-cc5023f138c9.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，下次发版将会修复
