### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2447]
**请描述您的需求或者改进建议.**
用户希望在仪表板查看的时候，每个视图增加一个可以查看对应数据集全部数据的按钮（小图标什么的都可以）。展示的样式希望是一个弹窗的样式，可以滚动查看全部数据。

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。建议先目前可以通过点击【更换数据集】的方式，弹框弹出后默认为当前所用数据集的数据。
