### ISSUE TITLE
[需求建议]是否能够显示组件的大小和位置

### ISSUE THREAD

**Issue by dujunyi370785** [dataease/dataease#2451]
在进行可视化编辑的过程中，为了页面统一和美观，旺旺需要使各个控件的大小一致，是否可以在页面编辑界面显示控件的大小和坐标？以便统一控件大小？
2.有时需要对控件位置进行微调，是否能够支持手动录入坐标和大小，或者支持键盘方向键？

**Comment by yayanpei** [comment]
感谢反馈，键盘方向键我们先收录需求。控件大小调整一致，可以在仪表板编辑页面，打开辅助网格设计，以便直观的看出组件的宽高，请参考如下：
<img width="459" alt="image" src="https://user-images.githubusercontent.com/84168063/174703275-2b343613-d128-491d-9c38-b2b6b6c25d36.png">

**Comment by yayanpei** [comment]
好的，我们再优化优化
