### ISSUE TITLE
[Bug]数据集数据定时同步不生效

### ISSUE THREAD

**Issue by YLBYR007** [dataease/dataease#2452]
**DataEase 版本**
1.11.1

**运行方式(安装包运行 or 源码运行 ?)**
源码运行
**浏览器版本**
谷歌浏览器：102.0.5005.115（64位）
**Bug 描述**
数据集中定时任务显示任务同步成功，数据预览显示无数据

**Bug 重现步骤(有截图更好)**
1.
![7121dac7a3bab343e14129cd73c2f9c](https://user-images.githubusercontent.com/107836874/174544755-d0652c8b-be96-45d3-a40e-9fa1c5fd6ef5.png)

2.
![1b39dabe46e66a833a9d8538f29f0f3](https://user-images.githubusercontent.com/107836874/174544791-c4655ac5-c10e-4c26-9ddd-3ba82df04ad8.png)

3.
![d331e530e54af45c4b9227a636f51e5](https://user-images.githubusercontent.com/107836874/174544832-b5b173f6-f44f-470b-a2b7-d9b3f52531a4.png)

**Comment by YLBYR007** [comment]
补充：我有两个数据集，一个数据集定时同步生效，一个数据集定时同步不生效，需要手动同步才会生效。

**Comment by BBchicken-9527** [comment]
感谢反馈，需要和你确认一下使用的数据源是什么？

**Comment by YLBYR007** [comment]
你好，没明白什么意思。我用的是mysql数据库。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月21日(星期二) 上午10:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dataease/dataease] [Bug]数据集数据定时同步不生效 (Issue #2452)





 
感谢反馈，需要和你确认一下使用的数据源是什么？

**Comment by BBchicken-9527** [comment]
你好，我在测试环境没有模拟出你的问题，我用的是mysql数据库的sql定时任务，使用同一数据源创建了两个数据集，两个数据集都做了定时同步任务并设置五分钟，然后在原数据库中添加一条数据，定时同步完成后两个数据集的数据都是有新增数据的；是我的模拟步骤和你有什么出入吗？

**Comment by BBchicken-9527** [comment]
不生效的数据集也是mysql数据源是吗？有产生什么异常信息？后台或者前端。我看你的截图是有字段的，说明已经通不过了，但是没有字段内容..里面数据都是什么类型的？不行我按照你不生效的数据源造一个看看，你说呢？

**Comment by YLBYR007** [comment]
我在DataEase 交流群 19，我叫应磊。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataease/dataease"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月6日(星期三) 下午5:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataease/dataease] [Bug]数据集数据定时同步不生效 (Issue #2452)





 
好的，你在那个群？叫什么？我在群里加一下你

**Comment by BBchicken-9527** [comment]
好的，我现在加一下你
