### ISSUE TITLE
[Bug]MySql数据库表名称含有小数点，使用直连模式无法正常预览数据

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#2457]
**DataEase 版本**
1.11.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器最新

**Bug 描述**
MySql数据库表名称含有小数点无法正常同步

**Bug 重现步骤(有截图更好)**
1.对接数据源，类型MySQL
2.创建数据集，选择刚才连接的数据源，选择直连模式
3.选择含有小数点的数据表如下图
![image](https://user-images.githubusercontent.com/35896106/174574820-f65757c2-c601-4013-a3af-32fa01f62461.png)
![image](https://user-images.githubusercontent.com/35896106/174575615-9a240b52-032b-4e02-8617-28dab3b1cfa6.png)
4.数据预留发现没有数据
![image](https://user-images.githubusercontent.com/35896106/174575143-1e855e8c-9485-4ec0-9702-dcfab08cf066.png)
5.表里面小数点去掉可以正常预留
![image](https://user-images.githubusercontent.com/35896106/174576187-c545e2e5-fa08-49a5-a1dc-e34b9a361788.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
问题已修复，可下载新版本体验
