### ISSUE TITLE
[Bug]视图联动缺陷

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2471]
**DataEase 版本**
1.11.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准最新版本

**Bug 描述**
基于 SQL 数据集创建的视图无法和其他视图进行联动

**Comment by BBchicken-9527** [comment]
感谢反馈，受累说一下具体使用的那个数据库，什么视图，并于什么视图做的联动，如果无法联动应该不会是数据集的问题，可能是使用的视图不支持所以需要和你确认一下
