### ISSUE TITLE
[Feature]制作视图时支持为指标值设置别名

### ISSUE THREAD

**Issue by wangzhen-fit2cloud** [dataease/dataease#2480]
**请描述您的需求或者改进建议.**
假设有如下格式数据，其中性别列 `0` 代表男性，`1` 代表女性，目前可以通过增加计算字段的方式，达到在图表中显示 `男`、`女` 而非 `0`、`1` 的效果，但配置起来稍微有些麻烦。

| 性别| 人数|
| ----------- | ----------- |
| 0 | 20 |
| 1 | 30 |

希望可以直接通过配置 `原始值`-`显示值` 映射的方式，来修改指标值的显示名。

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。
