### ISSUE TITLE
[Bug] 对 AntV 图表编辑样式时，配色组件没有响应

### ISSUE THREAD

**Issue by intoyang** [dataease/dataease#2482]
**DataEase 版本**
1.11.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome 102.0.5005.115（正式版本） (x86_64)

**Bug 描述**
1. 编辑 AntV 图表样式，选择颜色模块，可以切换成套配色，但不支持变更配色方案内每个独立的配色；
2. 退出重新登录、使用无痕窗口重新打开没有解决上述问题；
3. 切换到 Echart 图标样式，没有出现上述问题。

**Bug 重现步骤(有截图更好)**
1. 点击编辑--样式--颜色--配色方案；
2. 点击配色方案内色块，无响应。
<img width="380" alt="屏幕快照 2022-06-23 下午12 22 52" src="https://user-images.githubusercontent.com/73098982/175208523-130c06fc-2e36-480c-a3aa-e0cede7a8f42.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，需要和你确认一下是哪个视图？还是说所有AntV的视图都有这个问题？你也可以升级到最新版本看一下，最新版本有关于你这个问题的修复。

**Comment by intoyang** [comment]
感谢。两种堆叠柱状图及饼图都出现这个问题。升级后会验证这个修复。

**Comment by intoyang** [comment]
升级到 1.11.3 版本后，问题仍然存在。
