### ISSUE TITLE
Dateease服务连续几次出现内存溢出[Bug]

### ISSUE THREAD

**Issue by limin-fit2** [dataease/dataease#249]
**DataEase 版本**

**浏览器版本**

**Bug 描述**
Dataease连续出现3-5次堆内存溢出，只能大概判断出是导入excel表格时候有合并单元格原因引起的
![image](https://user-images.githubusercontent.com/61964761/125889792-f5da51ea-8752-4b3d-9cc1-2dd050bd712c.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
感谢您的反馈，我们尽快修复

**Comment by xuwei-fit2cloud** [comment]
我们已在 v1.5.0 版本做了处理。
