### ISSUE TITLE
下拉列表动态调整功能

### ISSUE THREAD

**Issue by dujunyi370785** [dataease/dataease#2494]
在实际业务需求中，往往需要给用户展示最新一期的数据，而目前下拉列表只能显示固定默认值，这样可能很不方便，是否可以增加默认值根据规则动态设置的功能？

**Comment by yayanpei** [comment]
感谢反馈，日期类组件已经在 V1.7.0 版本支持上动态默认值的设置。

**Comment by dujunyi370785** [comment]
有示例地址或者截图么 我没找到

**Comment by yayanpei** [comment]
动态默认值的设置，请参考下图所示：
<img width="782" alt="image" src="https://user-images.githubusercontent.com/84168063/175456481-1f4cb2fe-2fd7-4789-8d4f-de37be0d07df.png">
