### ISSUE TITLE
[Bug]antV词云显示个数依赖于视图大小，显示出来的词条数和实际数据不符

### ISSUE THREAD

**Issue by xyd113** [dataease/dataease#2496]
**DataEase 版本**
V1.11.1

**运行方式(安装包运行 or 源码运行 ?)**
docker

**浏览器版本**
chrome

**Bug 描述**
antV词云显示个数依赖于视图大小，显示出来的词条数和实际数据不符

**Bug 重现步骤(有截图更好)**
1. 测试中有14条用例是100%成功的
2. 用antV的词云视图显示这14条用例的名字
3. 调节视图大小。
问题：视图明细里面数据倒是显示全的。视图小的时候，词条整体大小不变，词条数量变少了。
实际情况是 数据量会变的，可能是50个词条，可能是5个词条，我不能把这个视图无限的拉大去兼容50个词条的情况而导致只有5个词条的时候界面没法看。
需求：词条整体大小根据视图总体大小自动调整，保证词条能全部显示。
![image](https://user-images.githubusercontent.com/39815896/175455504-1089b67e-fe5f-4754-aae4-038830be125a.png)
![image](https://user-images.githubusercontent.com/39815896/175455448-a23a768c-43f6-447a-b0f0-70d32d8192a8.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，你说的这个问题确实存在，但因为这个问题是原声组件导致，我们商讨一下怎么解决
