### ISSUE TITLE
创建dashboard，保存页面报错

### ISSUE THREAD

**Issue by liufei20151013** [dataease/dataease#25]
<img width="1409" alt="图片" src="https://user-images.githubusercontent.com/15103510/123393012-43a91380-d5d0-11eb-98b3-735a505e80c9.png">

**Comment by ziyujiahao** [comment]
已修复 小版本发

**Comment by xuwei-fit2cloud** [comment]
已修复，请等待 v1.0.1 版本的发布。

**Comment by xuwei-fit2cloud** [comment]
v1.0.1 已发布
