### ISSUE TITLE
[Feature]透视图优化

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2502]
**请描述您的需求或者改进建议.**
透视图支持全透明设置，当前不能透明全部
![企业微信截图_fa21621a-67c7-4a12-a6a7-fb67a81c4a6d](https://user-images.githubusercontent.com/24768910/175508592-fd9a674a-c609-44b8-a87a-b7912ebe24e2.png)

**Comment by yayanpei** [comment]
感谢反馈，我们优化一下。
