### ISSUE TITLE
[Question]  源码本地运行报错 

### ISSUE THREAD

**Issue by songsh** [dataease/dataease#2504]
**请描述您的问题.**
我在二次开发时，在idea 中打开项目， 报错
io.dataease:dataease-plugin-interface:pom:1.12.0   是哪不对 ？

**Comment by xuwei-fit2cloud** [comment]
v1.12.0版本还未发布，请使用v1.11分支的代码进行开发。如使用dev分支开发的话，需要下载https://github.com/dataease/dataease-extension-sdk工程，切换到对应的dev分支，在本地执行 mvn install 命令。
二次开发的具体细节可以参考在线文档 https://dataease.io/docs/dev_manual/dev_manual/
