### ISSUE TITLE
数据源支持动态参数传递

### ISSUE THREAD

**Issue by eechenyi** [dataease/dataease#2506]
**请描述您的需求或者改进建议.**
从组件选出的参数能传递到数据源，让数据源能动态获取

**Comment by yayanpei** [comment]
感谢反馈，该需求已经在开发中，预计 V1.12.0（2022.7.8）版本发布，还请多加关注。

**Comment by ainilili** [comment]
- 文本输入框是否能支持sql参数传递
- 外部参数能否支持sql参数专递（attachParams

**Comment by xuwei-fit2cloud** [comment]
@ainilili 目前还没有支持，后续版本会对参数的使用进行调整和优化

**Comment by ainilili** [comment]
@xuwei-fit2cloud 好的呢，非常期待
