### ISSUE TITLE
[Bug]编辑组件，选择文件下拉组件--添加多个内容，会出现翻页异常造成文件下拉无法展示（提示超时timeout of 10000ms exceeded错误）

### ISSUE THREAD

**Issue by geyesheng** [dataease/dataease#2511]
**DataEase 版本**
v1.11.0
**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 版本 102.0.5005.115（正式版本） （64 位）

**Bug 描述**
编辑组件，选择文件下拉组件--添加多个内容，会出现翻页异常造成文件下拉无法展示（提示超时timeout of 10000ms exceeded错误）

**Bug 重现步骤(有截图更好)**
1.编辑组件，选择文件下拉组件--添加多个内容：
![image](https://user-images.githubusercontent.com/38676947/175874232-2a80b658-ca55-4554-837a-480fe166222d.png)

2.出现翻页异常造成文件下拉无法展示（提示超时）

![image](https://user-images.githubusercontent.com/38676947/175873083-5dd2c7ea-bf2a-4a96-b519-70a731d28db4.png)
![image](https://user-images.githubusercontent.com/38676947/175873191-d7ee9be1-1701-4ad3-9c06-d70faa9df91a.png)
3.文件下拉无生效，造成该功能无法使用
![image](https://user-images.githubusercontent.com/38676947/175874497-41e312bc-84d5-4345-b631-f46c1993a30e.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，此问题为已知问题，我们正在考虑解决的办法。
