### ISSUE TITLE
[bug] 水波图，仪表板配置定时刷新，自动刷新后水波图样式消失

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2513]
**DataEase 版本**
v1.11.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome 101.0.4951.54

**Bug 描述**
水波图，仪表板配置定时刷新，自动刷新后水波图样式消失。

**Bug 重现步骤(有截图更好)**
1. 水波图原始样式：
![image](https://user-images.githubusercontent.com/30063018/175892504-9a6c46fb-9fd7-4f40-8b28-be4de8ae268a.png)
2. 仪表板自动刷新后样式：
![image](https://user-images.githubusercontent.com/30063018/175892633-c2fa3a03-763e-4576-a463-232b3c966d45.png)

**Comment by zrfit** [comment]
已复现该问题，后续版本修复。
