### ISSUE TITLE
[Feature][仪表板视图]当视图的标题很长时，展示的标题内容显示不全 会自动省略显示，应当支持用户设置视图的标题换行展示 或 添加子标题

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#2516]
**请描述您的需求或者改进建议.**
优化建议：
1、视图的标题支持设置换行展示
2、视图支持添加 子标题

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。目前的标题不支持换行展示，建议您将图表的标题设置为不可见，然后用富文本框输入标题内容，放置在图表的标题处，如下图所示：
<img width="443" alt="image" src="https://user-images.githubusercontent.com/84168063/176078523-c69d5d58-fa72-4d71-b566-eeecfa2cccdb.png">
