### ISSUE TITLE
[Feature]数据集的数据预览不便于排查问题

### ISSUE THREAD

**Issue by legend818** [dataease/dataease#2523]
**请描述您的需求或者改进建议.**
导入excel数据，经常会发现或多或少问题，由于导入的数据到系统会乱排序，导致定位问题很难
1、建议按默认顺序预览（与excel一致性），或者支持排序
2、可以调整数据项（列）位置
3、支持全局检索

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。
