### ISSUE TITLE
[Bug] 仪表板分享的权限问题

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2526]
**DataEase 版本**
1.11.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.做了一个基金的仪表板，分享给A，B两个用户
2.其中A用户能打开，并且也能通过下拉框去筛选
3.B用户报错缺少表的权限
![image](https://user-images.githubusercontent.com/82353425/176403353-4fa74290-093e-49f6-9795-8456c29534d1.png)
4.两个用户的权限配置是一模一样，如果我手动赋予B相应的数据集权限则不会报错，这是什么小问题类

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们在自己的环境里并没有复现上述问题，还请重新检查授权关系，如有问题请再反馈，谢谢。
