### ISSUE TITLE
[Question] 关于创建公共链接后打开异常

### ISSUE THREAD

**Issue by Lvxinbo666** [dataease/dataease#2529]
**请描述您的问题.**
最初前后端没分离 创建公共链接打开正常。

**Comment by Lvxinbo666** [comment]
> **请描述您的问题.** 最初前后端没分离 创建公共链接打开正常。

前后端分离，创建公共链接打开异常，我想问下，公共链接的原理是什么

**Comment by Lvxinbo666** [comment]
我看到前端拼接是拿前端的域名 和后端返回的url来组合

**Comment by yayanpei** [comment]
感谢反馈，应该是nginx没配好，请参考在线文档：https://dataease.io/docs/installation/HA/nginx_installation/?h=ngi#4-nginx
