### ISSUE TITLE
模板市场下载的模板，在新建仪表时背景不显示

### ISSUE THREAD

**Issue by longshang** [dataease/dataease#2536]
**DataEase 版本**

版本号 | v1.11.1

**Bug 描述**
从【模板市场】下载的模板，在”新建仪表“时背景不显示，如下图所示：
![image](https://user-images.githubusercontent.com/17903581/176633335-4f021dc6-c600-474b-be01-c87486ac4010.png)

**Comment by xuwei-fit2cloud** [comment]
这个问题已经在v1.11.2版本中修复，可以升级一下新版本
