### ISSUE TITLE
[Feature]日期范围新增一些上月等默认选项

### ISSUE THREAD

**Issue by legend818** [dataease/dataease#2547]
**请描述您的需求或者改进建议.**
日期范围
建议新增 上月 上周的选项，一般统计都是月统计，7月才能看到6月数据，建议新增一些默认选项
![image](https://user-images.githubusercontent.com/19423100/176824693-baedf48b-dfe3-4e6a-b126-02625d4a30af.png)

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到
