### ISSUE TITLE
[Bug]连接分享看到的仪表盘和实际编辑的仪表盘布局有出入

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#256]
**DataEase 版本**
v1.0.1

**浏览器版本**
Chrome 91.0.4472.114

**Bug 描述**
连接分享看到的仪表盘和实际编辑的仪表盘布局有出入

**Bug 重现步骤(有截图更好)**
1.在 DE 界面看到的仪表盘
![image](https://user-images.githubusercontent.com/48945409/126099741-ad16a27b-48bb-4027-9769-3e60286a033a.png)

2.通过分享链接看到的仪表盘，可以看到第二排的图表标题明显上移了很多
![image](https://user-images.githubusercontent.com/48945409/128299330-bfe25392-259a-4423-aa7e-311686aba577.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.5.0版本做了处理
