### ISSUE TITLE
[Question]我们这边es索引都是按日期分割，如何统一查询？

### ISSUE THREAD

**Issue by soopsle** [dataease/dataease#2572]
**请描述您的问题.**
数据集或者仪表盘内数据 怎么使用 es 索引通配符
es能支持通配符索引么？
我们这边es索引都是按日期分割，如何统一查询？
仪表盘会报错：unresolved object ?* as ?

![1513f260a64bcb400f3c57e50f0bcef](https://user-images.githubusercontent.com/15059588/177127331-656db778-691b-4615-a605-15d7dbabd329.png)

**Comment by yayanpei** [comment]
感谢反馈，按日期分割后的数据表，是不支持统一查询的。建议您通过新建sql数据集，用sql语句将不同的表数据合并后再进行查询。
