### ISSUE TITLE
[Bug]无法连续两次传入同一张图片

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#258]
**DataEase 版本**
v1.0.1

**浏览器版本**
Chrome 91.0.4472.114

**Bug 描述**
同一张图片无法连续两次被导入到仪表盘，第二次导入界面无任何报错提示，但是操作完成后就仍然只有一张该图片。只有重新导入一张其它图片后再次导入之前的图片才有。

**Bug 重现步骤(有截图更好)**
1.传入一张图片
![image](https://user-images.githubusercontent.com/48945409/126108235-08842b53-9417-4297-8315-6a1b1dac3bfa.png)

2.想再次传入该图片
![image](https://user-images.githubusercontent.com/48945409/126108301-e72464d6-fdcc-4b67-8219-1b5b09ffc957.png)

3.操作完成之后，发现那张图片仍然只有之前那一张
4.重新换一张图片导入后再次导入之前的图片就可以了

**Comment by xuwei-fit2cloud** [comment]
感谢您的反馈，我们尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已修复
