### ISSUE TITLE
[Bug] 配置的定时任务，在运行一段时间后会被清除

### ISSUE THREAD

**Issue by lichao0124** [dataease/dataease#2580]
**DataEase 版本** v1.8.0

**运行方式(安装包运行 or 源码运行 ?)** linux环境docker部署

**浏览器版本**

**Bug 描述**
我现在通过debug日志分析，发现spring 事件监听注解@EventListener的下面这个方法由主线程在项目启动时被执行两次，然后当问题出现时，由另外一个子线程又执行了两次导致定时任务被清除掉了
![c0ba30090458c21b154b36bb082f141](https://user-images.githubusercontent.com/67251281/177240484-8cc10cd7-129b-4988-aeb9-c2e1e4835506.png)
![0e8f7b269d98a0d9f051d03aaf6d0c2](https://user-images.githubusercontent.com/67251281/177240486-56f852b2-1c92-4521-9c70-2a8000777e03.png)
![0c2ddff2e7a85cd5874f45c67aa0ce0](https://user-images.githubusercontent.com/67251281/177240492-218d3a46-6d74-4595-af33-bbff1696a8cc.png)

**Bug 重现步骤(有截图更好)**
1.在linux环境docker部署，运行一段时间后会复现，时间不定
2.完整日志
[quartz-job.log](https://github.com/dataease/dataease/files/9042903/quartz-job.log)

**Comment by lichao0124** [comment]
问题解决了，因为接入nacos，会引起spring再次刷新，导致又一次执行startScheduler方法。目前的简单处理方法：
![image](https://user-images.githubusercontent.com/67251281/177296958-d8f815f4-bc49-450c-bac8-8ab3b37f9978.png)
![image](https://user-images.githubusercontent.com/67251281/177297041-6a25976f-08db-4f04-ba92-920e57978f13.png)

**Comment by BBchicken-9527** [comment]
好的，感谢你的反馈，必须给个赞
