### ISSUE TITLE
[Bug]透视表的隔行无法修改背景色

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2589]
**DataEase 版本**
v1.11.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 102

**Bug 描述**
透视表的表格属于隔行的颜色不同，修改表格背景色时只有双数行的颜色被修改，单数行的白色无法配置。

**Bug 重现步骤(有截图更好)**
如图所示，始终无法配置白色的部分。
<img width="668" alt="image" src="https://user-images.githubusercontent.com/48945409/177333959-6701fd01-281d-4d06-88db-d83ea8df05c2.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，我们正在讨论处理的方法。

**Comment by xuwei-fit2cloud** [comment]
目前我们使用的图库还不能支持，若图库支持了，我们会随后加上支持。
