### ISSUE TITLE
[Feature]建议瀑布图的“增减、较少、合计”样例的字的颜色可以调整

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2598]
**请描述您的需求或者改进建议.**
如下图所示，未找到可以调整以下红色框出部门文字颜色的地方，若背景为深色系，会看不清楚，建议可以自行调整颜色。
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/48945409/177482067-d5fffd02-0db2-4b80-80f3-d0f3b85d181f.png">

**Comment by yayanpei** [comment]
感谢反馈，V1.12版本对仪表板主题进行了优化，深色主题下图例可自动切换为浅色系，还请多加关注。
