### ISSUE TITLE
[Question] 源码启动后，添加数据集->数据库数据集报错

### ISSUE THREAD

**Issue by HotMancheA** [dataease/dataease#2602]
![image](https://user-images.githubusercontent.com/45034584/177523413-55f30357-d4bf-4795-bc6a-39db241d9ec2.png)
选择表后点确定报错！
![image](https://user-images.githubusercontent.com/45034584/177523089-fc3e55e8-eb6d-4339-a963-41204bc322fe.png)

**Comment by HotMancheA** [comment]
版本最新版1.11.3

**Comment by HotMancheA** [comment]
最新版本1.12.0

**Comment by xuwei-fit2cloud** [comment]
报错的这个类一直在 [dataease-extension-sdk](https://github.com/dataease/dataease-extension-sdk/tree/1aa97af0381ca9a9e439aac8c046ea8f2a55035b) 工程里，可以把 .m2 目录下 dataease 相关的依赖清除，然后重新编译试试。也可以下载 dataease-extension-sdk 源码，本地 mvn clean install 一下。
