### ISSUE TITLE
[Feature] 什么时候升级到vue3+ts，有计划吗？

### ISSUE THREAD

**Issue by PaulMing** [dataease/dataease#2606]
什么时候升级到vue3+ts，有计划吗？社区这边可以参与吗【迁移方案共建】
全面拥抱vue3+ts

**Comment by yayanpei** [comment]
感谢您的反馈，升级到vue3在我们的规划内，应该还要再等待一些时间，当然也非常欢迎大家参与，再次感谢您对产品的支持。

**Comment by PaulMing** [comment]
怎么参与尼，哈哈

**Comment by ruibaby** [comment]
个人建议可以尝试先升级到 Vue 2.7，逐步替换现有的写法。目前如果直接升级到 Vue 3 + TypeScript 可能成本比较大，因为还涉及到一系列依赖的升级（最主要还是 Element UI），而且需要进行大量的测试。可以探讨一下如何逐步向上升级。

目前 Vue 2.7 已经向上兼容了一些新特性，可以考虑尝试一下。另外， Vue 2 目前还剩下 18 个月的生命周期，提前考虑升级是有必要的。

**Comment by yayanpei** [comment]
感谢 @PaulMing 的反馈，可以通过提交pr的方式提交代码，我们这边查验过代码后，会合并到项目中。

**Comment by yayanpei** [comment]
非常感谢@ruibaby 的建议，我们会慎重考虑升级相关事宜。

**Comment by xuwei-fit2cloud** [comment]
由于近期版本还没有此计划，该issue先暂时关闭。

**Comment by PaulMing** [comment]
嗯嗯，全面拥抱vue3+ts
