### ISSUE TITLE
[Feature]  指标卡和文本卡能否支持跳转联动？

### ISSUE THREAD

**Issue by PangZiZzz** [dataease/dataease#2608]
指标卡和文本卡能否支持跳转联动

**Comment by yayanpei** [comment]
感谢您的反馈，目前是支持跳转的，如下图所示：
<img width="337" alt="image" src="https://user-images.githubusercontent.com/84168063/178176481-ef3f0eca-0fdc-4c0d-99f9-bba7d830f406.png">
