### ISSUE TITLE
[Bug] get_auths函数的modelType参数未使用

### ISSUE THREAD

**Issue by sds0917** [dataease/dataease#2610]
**DataEase 版本**
v1.12.0

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Edge 103.0.1264.49

**Bug 描述**
SQL中的get_auths函数的modelType参数未使用

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/7779851/178008626-81a153c3-44e7-4374-832a-a502f8cd811e.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，这个函数是授权使用的，所有的权限控制都是走这里的，是使用的
