### ISSUE TITLE
项目升版本难度大，有没有好的解决方案

### ISSUE THREAD

**Issue by PaulMing** [dataease/dataease#2611]
**请描述您的问题.**
v1.2.3
基于v1.2.3部署的dataease，如何升级到最新版本，需要考虑哪些问题？

**Comment by maninhill** [comment]
请参考在线文档。

**Comment by xuwei-fit2cloud** [comment]
建议用离线升级方式：
https://dataease.io/docs/installation/offline_upgrade/

升级之前建议备份：
https://dataease.io/docs/faq/backup_faq/
