### ISSUE TITLE
[数据源]不支持使用数据库示例的方式添加SQL Server数据源

### ISSUE THREAD

**Issue by Leeee1998** [dataease/dataease#2612]
数据源类型：SQL SERVER
IP：填写为数据库实例，如 192.168.1.88\SQLSERVER2016
其余信息合法完善，点击“获取Schema”

结果：超时（实际上是因为不支持通过实例方式添加数据源）

**Comment by BBchicken-9527** [comment]
感谢反馈，目前暂时不支持实例方式添加数据源，我这边记录一下。
