### ISSUE TITLE
[数据源]数据库名称在数据源中校验通过，在数据源中校验不通过

### ISSUE THREAD

**Issue by Leeee1998** [dataease/dataease#2613]
数据库版本：SQL Server 2016

复现步骤：
1.【数据源】添加sql sever类型的数据源，填写数据库名称为 xxx.xxx.xxx.db 这种四段的，其余信息合法完善
2.【数据源】校验数据库连接信息，校验通过并保存
3.【数据集】添加数据库数据集，选择刚刚添加的数据源，直连

结果：
报错“xxx对象名称xxx包含的前缀超出了最大限值，最多只能有3个”

预期：
1.数据库名称结构不符合要求，应该在【数据源】添加的时候就校验了，而不是在【数据源】添加的时候才校验提示
2.现实场景中是会存在多段的数据库名，不应该限制的那么死

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
