### ISSUE TITLE
v1.11.3更新至v1.12.0，旧仪表板-文本下拉组件展示呈现透明

### ISSUE THREAD

**Issue by IsSeptember** [dataease/dataease#2615]
**DataEase 版本**
v1.12.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome 版本 103.0.5060.114（正式版本） (x86_64)

**Bug 描述**
社区版v1.11.3更新至v1.12.0，部分旧仪表板中的文本下拉组件，选中某值后再次点击，下拉框呈现透明状态

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/54738906/178203738-fde2a4b4-0c43-425d-890f-f156c8fe343f.png)
![image](https://user-images.githubusercontent.com/54738906/178204184-c4aed9ee-cadb-42bb-bf6d-4f05202c35a4.png)
![image](https://user-images.githubusercontent.com/54738906/178204312-7981cf8e-e88b-470a-98a2-60ef0c9741c4.png)
![image](https://user-images.githubusercontent.com/54738906/178204424-a565f2be-bd75-4542-838c-ec4aa05b9ad4.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.13版本已修复，请升级最新版本。
