### ISSUE TITLE
表格如明细表支持根据单元格内容显示不同颜色值

### ISSUE THREAD

**Issue by IsSeptember** [dataease/dataease#2616]
如下，表格列的值可例举，希望可以实现根据值自定义单元格颜色，突出显示
![image](https://user-images.githubusercontent.com/54738906/178205843-d30a4f4f-17dc-4024-9f49-40755350b0fd.png)

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
