### ISSUE TITLE
[Bug]仪表板编辑时，选择手机模式添加几个视图后，取消视图时，勾选按钮需要点击两次页面视图才生效

### ISSUE THREAD

**Issue by Jack-Dh** [dataease/dataease#2617]
**DataEase 版本**
1.12.0

**运行方式(安装包运行 or 源码运行 ?)**
 源码运行

**浏览器版本**
Google Chrome 版本 103.0.5060.114（正式版本） （64 位）

**Bug 描述**
仪表板编辑时，选择手机模式添加几个视图后，取消视图时，勾选按钮需要点击两次页面视图才生效

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/33785393/178211040-f47c9a28-e406-4ab1-b2a3-6d544fd8427b.png)

2.仪表板编辑时，选择手机模式添加几个视图后，取消视图时，勾选按钮需要点击两次页面视图才生效
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，第一次点击是确定视图，第二次点击若上下移动则可以调整视图位置，若取消勾选可以从手机预览中移除。不过你说的确实可以提升使用者的体验，这里我们做一个小优化吧

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
