### ISSUE TITLE
复用模板支持复用更深层次的样式

### ISSUE THREAD

**Issue by IsSeptember** [dataease/dataease#2618]
源模板：
1、指标卡，使用了过滤器，手动输入逻辑条件，筛选status为passed
![image](https://user-images.githubusercontent.com/54738906/178212018-adbb166b-01e9-4abc-b986-cbf09a918aa3.png)
2、明细表，对字段设置了数据格式
![image](https://user-images.githubusercontent.com/54738906/178212731-3e2bf449-81cd-4139-8fc2-1091d264b771.png)

新建仪表板复用模板，更换数据集（数据集字段完全一致）后：
1、指标卡，显示有过滤器，但是筛选条件已丢失
2、明细表，字段数据格式已丢失

希望能够保持原有样式，不需要再手动重新设置

**Comment by yayanpei** [comment]
感谢反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
