### ISSUE TITLE
[Bug]添加es数据集报错

### ISSUE THREAD

**Issue by liuhetongzi** [dataease/dataease#2623]
**DataEase 版本**

v1.12.0
**运行方式(安装包运行 or 源码运行 ?)**
docker

**浏览器版本**
谷歌103.0.5060.114

**Bug 描述**
添加es数据集报错

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/23496061/178418178-2dd77d95-09eb-4398-8433-6634e50da131.png)

2.
3.

**Comment by BBchicken-9527** [comment]
好的，我尝试一下有结果再和你说一下
