### ISSUE TITLE
[Bug] 表格视图精度缺失问题

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2624]
**DataEase 版本**
1.12.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 描述**
1. 创建数据表如图所示：
![image](https://user-images.githubusercontent.com/82353425/178421228-3b06e35c-54ac-4943-b06a-731aebd969e8.png)
2.表字段结构如图所示：
![image](https://user-images.githubusercontent.com/82353425/178420687-7ac7630e-79cf-498c-91ba-57a875e604df.png)
3.然后直连Mysql 数据库的这张表，数据集展示的结果没有丢失精度
![image](https://user-images.githubusercontent.com/82353425/178421509-6ae3695b-9692-4773-b7e1-d5de2ce545ce.png)

4.将数据集制作成 antv的明细表或者透视表就默认保留2位小数了，而且是五入的规则
![image](https://user-images.githubusercontent.com/82353425/178421389-fb04a264-c2ab-409d-8038-1a40ac60fdc9.png)
5.这时候采用数值格式的功能也只是往后面新添“0”。
![image](https://user-images.githubusercontent.com/82353425/178421571-e54cf53a-60f0-47a0-8495-72dab9a8790e.png)

**Comment by yayanpei** [comment]
感谢反馈，我们尽快修复一下。

**Comment by Toy-data** [comment]
数值格式：百分比的时候也会有这样精度丢失，0.782 百分比展示保留一位小数展示的是78.0%，两位小数则是78.00%

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
