### ISSUE TITLE
[Bug] 增加 Oracle 的数据集，同步表数据失败，错误提示类型相关异常

### ISSUE THREAD

**Issue by it-noob** [dataease/dataease#2626]
**DataEase 版本**
v1.12.0

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 103.0.5060.53

**Bug 描述**
新建数据集，进行数据同步的时候，kettle 处理的数据类型同步异常

**Bug 重现步骤(有截图更好)**
1.  相关截图
     ![image](https://user-images.githubusercontent.com/12043442/178459839-e7f90f98-2555-47d7-86aa-d5c73c552ab5.png)
     
     ![image](https://user-images.githubusercontent.com/12043442/178460387-29492e10-9753-42e3-a19e-891aa1ab0f07.png)

2.  kettle 的错误日志提示：`ID Integer : There was a data type error: the data type of java.lang.String object [1000000015] does not correspond to value meta [Integer]`
3.  源表的 对应字段的 DDL语句： `create table QRTZ_TRIGGER_LOG
(
  id               NUMBER(10) not null,
  job_group        NUMBER(10) not null,
  job_id           NUMBER(10) not null,
  glue_type        VARCHAR2(50),
  executor_address VARCHAR2(255),
  executor_handler VARCHAR2(255),
  executor_param   VARCHAR2(512),
  trigger_time     DATE,
  trigger_code     VARCHAR2(255) default '0',
  trigger_msg      VARCHAR2(2048),
  handle_time      DATE,
  handle_code      VARCHAR2(255) default '0',
  handle_msg       VARCHAR2(2048)
)`

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
