### ISSUE TITLE
[Feature]echarts饼图这可以显示一个总数

### ISSUE THREAD

**Issue by liuhetongzi** [dataease/dataease#2627]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/23496061/178629033-f37dee07-9847-4f3d-b49a-a817fc951202.png)
只有每一个类别的数量，饼图这可以有个配置 显示全部加起来的总数，看到总数比较直观

**Comment by yayanpei** [comment]
感谢反馈，如果需要展示总数，建议您增加指标卡，悬浮在饼图的上层。
