### ISSUE TITLE
[Bug]数据集，增量更新设置定时同步为工作日无法更新

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#2630]
**DataEase 版本**
v1.12.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Microsoft Edge
版本 103.0.1264.49 (正式版本) (64 位)

**Bug 描述**
增量更新设置定时同步为工作日无法执行

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/96223591/178662365-bf08bbab-9f79-48af-b745-d9ecea93ffa4.png)

2.
![image](https://user-images.githubusercontent.com/96223591/178662383-03696753-3dbd-48eb-b305-aaf49de516ce.png)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈 我们按照你给出的cron验证一下

**Comment by BBchicken-9527** [comment]
验证cron无异常，只是没有到达执行时间，没问题
