### ISSUE TITLE
[Feature]echarts 堆叠的柱状图 是否可以考虑在顶部显示一个总的数量呢

### ISSUE THREAD

**Issue by liuhetongzi** [dataease/dataease#2633]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/23496061/178690709-14a5f3e3-9662-4d3e-9be7-fd67cd2ef85b.png)
堆叠的柱状图 是否可以考虑在顶部显示一个总的数量呢

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。目前还不支持，如果需要，建议在顶部悬浮指标卡显示总数。
