### ISSUE TITLE
[Bug]下钻字段无法进行排序

### ISSUE THREAD

**Issue by hzhfit2cloud** [dataease/dataease#2634]
**DataEase 版本**
v1.12.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
 103.0.5060.114

**Bug 描述**
维度排序只能对第一层级排序，下钻到第二层级的时候顺序就乱了，

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/89765365/178874206-ab829ed4-e473-49bc-8c6c-3253e6684c57.png)

1.第一层为月份、第二层为日期
2.无法对下钻的字段进行排序

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，已在下个版本的排期中。

**Comment by xuwei-fit2cloud** [comment]
下钻后延续第一层排序规则（仅对升降序有效）

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
