### ISSUE TITLE
[Bug]导入的Excel最后有格式无数据，数据集会出现空行

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#2635]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
firefox最新

**Bug 描述**
精简模式安装后，Excel表格最后几行有格式无数据，倒入后数据集会出现空行

**Bug 重现步骤(有截图更好)**
1.精简模式的安装
2.准备表格，最后几行有格式，但是没有数据
<img width="315" alt="图片" src="https://user-images.githubusercontent.com/48307752/178902920-8248f33d-6a65-4484-9fbc-0d9fc0190810.png">

3.上传excel作为数据集，预览效果如下：
<img width="773" alt="图片" src="https://user-images.githubusercontent.com/48307752/178901839-479e81cd-a82f-4352-9ad8-be9170ca3d24.png">

**Comment by BBchicken-9527** [comment]
感谢反馈
请问是什么版本呢
