### ISSUE TITLE
[Bug] 仪表板表格自适应问题

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2640]
**DataEase 版本**
1.12.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
1.首先我制作展示透视表的仪表板，然后表格配置选择自适应。
2.我在显示器上能看到 “总计”下的“success”列。
![24aec9c8169903b0ae50f2956824ec9](https://user-images.githubusercontent.com/82353425/179435975-f571fda4-7c3c-4444-ab5b-695d742add30.jpg)
3.我切换到笔记本预览的时候，明显展示的列数减少了。
![b61d8fbfd22a101bff4151f3bd34dd9](https://user-images.githubusercontent.com/82353425/179436019-296d5fb1-8359-4c75-997b-2abcf7c2e813.jpg)

因为使用的是自适应的配置，维度的宽度应该是按比例缩放的吧。

**Comment by xuwei-fit2cloud** [comment]
表格宽度的自适应是根据该列的内容自适应，而不是屏幕大小。
目前来看，在某些情况下，S2在随内容自适应宽度时，也会出现不能完全适应的情况。

**Comment by ywhfzy** [comment]
收到
