### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by 623352421** [dataease/dataease#2641]
v1.12

linux 单机部署

chrome 103.0.5060.114

clickhouse数据源每过一个小时 或者半个小时就要校验一次数据源，不然就数据无效

**Bug 重现步骤(有截图更好)**
1.
![f9bf6afd27d4a3333297fad2739fa92](https://user-images.githubusercontent.com/109494651/179439154-c23d3084-12a8-4fcf-b85a-de6fc1251727.png)

2.
![445ad666a6e3cbdfb0ecf5e10551a25](https://user-images.githubusercontent.com/109494651/179439184-1d493bb6-9ba9-4c9d-9399-e35d4171abd2.png)

3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们排查一下

**Comment by xuwei-fit2cloud** [comment]
请问一下，DataEase服务器与ClickHouse服务器之间是否容易存在网络的不稳定情况？

**Comment by 623352421** [comment]
> 

这个要怎么确认

**Comment by xuwei-fit2cloud** [comment]
比如获取ClickHouse数据的时候是否容易超时，比如多次点击校验ClickHouse数据源的时候是否容易超时等。

**Comment by 623352421** [comment]
> clickhouse数据量很少，每次点击校验数据源响应很快，没有发现任何超时的情况，

**Comment by 623352421** [comment]
你好有在跟进吗

**Comment by BBchicken-9527** [comment]
好的，我们已经收到，现在正在进行排查。因为我们环境中没有发生你的这种情况所以正在想办法复现你的问题。
