### ISSUE TITLE
[Question]下拉组件的数据源与视图组件能否不同？

### ISSUE THREAD

**Issue by tzengshinfu** [dataease/dataease#2642]
您好：
请问能否达到以下需求？
1.现有1个文本下拉组件，数据源为SQL数据集(员工资料表，只取采购人员)，SQL如"SELECT USER_NAME FROM USERS WHERE TYPE = '采购员'"
2.视图组件数据源为SQL数据集(订单资料表)，SQL如"SELECT ORDER_ID, ORDER_DATE, PROJ_ID FROM ORDERS WHERE ORDER_EMP = ${USER_NAME}" -->以文本下拉组件选中的采购员姓名为条件过滤之

**Comment by yayanpei** [comment]
感谢反馈，V1.12版本已支持SQL数据集传递参数，可参考文档：https://dataease.io/docs/user_manual/dataset_configuration/dataset_SQL/#3-sql

**Comment by tzengshinfu** [comment]
感谢回复，我这边测试成功了。

我发现数据集SQL语法要因应过滤组件的行为而有所更动，如下：
情况一，过滤组件为单选时，要用 =
SELECT ORDER_ID, ORDER_DATE, PROJ_ID FROM ORDERS WHERE ORDER_EMP = ${USER_NAME}

情况二：过滤组件为多选时，要用 IN(用 IN 可单选也可多选，但相反地用 = 只能单选)
SELECT ORDER_ID, ORDER_DATE, PROJ_ID FROM ORDERS WHERE ORDER_EMP IN ${USER_NAME}

情况三：有多个过滤组件时，要用括号包复成一个组，不然视图组件不会更新
SELECT ORDER_ID, ORDER_DATE, PROJ_ID FROM ORDERS WHERE (ORDER_EMP IN ${USER_NAME} AND PROJ_ID IN ${USER_PROJ_ID})

**Comment by yayanpei** [comment]
如您回复，在使用上确实有差异。文档部分我们也会再细化一下，再次感谢您对产品的关注和支持。
