### ISSUE TITLE
[Bug]在透视图中，选择新增视图计算字段后，计算逻辑问题

### ISSUE THREAD

**Issue by mispower** [dataease/dataease#2643]
**DataEase 版本**
V1.12

**运行方式(安装包运行 or 源码运行 ?)**

官方DEMO环境
**浏览器版本**
chrome

**Bug 描述**

在透视图中，选择新增视图计算字段的时候，总计并没有按照计算字段的逻辑合并，而是直接将每个计算结果直接相加了，如图:实际期望是93/1523=0.06，但是实际上是将三行相加。并且在计算的小数点好像默认是2位小数，计算的值超过2为没有数值的时候就默认显示0了，调整显示多少小数位，不能起到作用，如图2

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/3365904/179660167-2a8dd802-6843-42ab-967b-56362abdafdc.png)

![image](https://user-images.githubusercontent.com/3365904/179665623-095addff-c558-4093-a7c5-2c484434446a.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，能将计算字段的公式截图看一下吗

**Comment by mispower** [comment]
> 感谢反馈，能将计算字段的公式截图看一下吗
就是a/b
![image](https://user-images.githubusercontent.com/3365904/179951719-74697253-796d-4349-be28-00af8a5821a4.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，这个是原生组件问题，我们尽量处理但是无法确定可操作的空间。

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
