### ISSUE TITLE
[Feature]使用SQL数据集时，由于检测到SQL风险，请求被防火墙拦截

### ISSUE THREAD

**Issue by lyons-hz** [dataease/dataease#2645]
**请描述您的需求或者改进建议.**
使用SQL数据集，发送请求时对SQL语句进行加密，否则会被防火墙拦截，报403错误。
建议有类似发送SQL语句的地方，都进行优化。
<img width="976" alt="image" src="https://user-images.githubusercontent.com/89773363/179699419-05b56a42-c2be-4c23-960d-1b617d2c9e40.png">

<img width="991" alt="image" src="https://user-images.githubusercontent.com/89773363/179699153-7775188b-af6d-4abc-b2b8-1b66848f36e7.png">

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。
