### ISSUE TITLE
[Feature] sql server 如果存在实例名的情况，默认端口是0，但是端口号等于0的话，程序又会检查

### ISSUE THREAD

**Issue by issueye** [dataease/dataease#2646]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/28434476/179709159-0e66df28-60c0-4a96-9272-8b6ea2922a78.png)
![image](https://user-images.githubusercontent.com/28434476/179709607-d6e79e78-a391-42fb-a7f9-f3b7b3fd0d7f.png)

**Comment by yayanpei** [comment]
感谢反馈，Sql Server暂时还不支持通过实例的方式添加数据源，目前在调研中。
