### ISSUE TITLE
[Bug] Oracle数据源配置字符集ISO-8859-1字符转GBK后，数据集定时同步报错

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#2649]
**DataEase 版本**
1.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
firefox最新

**Bug 描述**
Oracle数据源配置字符集ISO-8859-1字符转GBK后，Oracle表中如果存在number类型的字段，数据集定时同步模式会报错

**Bug 重现步骤(有截图更好)**
1. 部署Oracle11.2.0.4，可以用容器启动复现：
    docker pull registry.cn-shanghai.aliyuncs.com/techerwang/oracle:ora10g_10205

    #修改镜像
    docker tag registry.cn-shanghai.aliyuncs.com/techerwang/oracle:ora10g_10205 jemora10g:10205

    #运行oracle容器
    docker run -itd --name jemora10205 -h jemora10g -p 3380:3389  -p 31521:1521  -p 312:22  --privileged=true  jemora10g:10205 init
    #查看日志，等待初始化完成
     docker logs -f jemora10205
    ......
   Starting crond:                                            [  OK  ]
   Starting atd:                                              [  OK  ]

    #进入容器
    docker exec -it jemora10205 bash
    
    #启动oracle
    su - oracle
    lsnrctl start
    sqlplus / as sysdba
    startup
    select * from v$version;
    
    #外部连接容器内的数据库
    sqlplus sys/jem@192.168.1.54:31521/JEM10G AS SYSDBA
    注意：此处访问宿主机端口为31521，容器内部是1521，端口映射,系统管理员密码为jem

2. 将字符集修改为ISO-8859-1
SYS@JEM11GR2> shutdown immediate
SYS@JEM11GR2> startup restrict
SYS@JEM11GR2> alter database character set INTERNAL_USE WE8ISO8859P1;
SYS@JEM11GR2> shutdown immediate
SYS@JEM11GR2> startup
SYS@JEM11GR2> select userenv('language') from dual; 
#可以查看到字符集已修改为AMERICAN_AMERICA.WE8ISO8859P1

3. 随意创建一个表格，要有number类型的字段，此字段类型存在时下面的定时同步会报错。

4. DataEase创建Oracle数据源，字符集： ISO-8859-1，目标字符集：GBK。

5. DataEase创建数据集，选择定时同步，立即更新，稍后会同步失败，报错查看日志：
（以下报错中“value11 ” 是 Oracle 表中的字段，类型为“number”）
value11 BigNumber : There was a data type error: the data type of java.lang.String object [23452.0] does not correspond to value meta [BigNumber]
![图片](https://user-images.githubusercontent.com/48307752/180117695-40d4203d-59c8-468a-80eb-e48b8e880ebc.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们的环境中没有发现你的这个问题，我按照你的步骤安装验证一下。

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
