### ISSUE TITLE
[Bug] 全屏仪表板无法点击下拉树组件

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2658]
**DataEase 版本**
1.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 重现步骤(有截图更好)**
1.选择一个下拉树组件，在编辑状态是可以点击的
![image](https://user-images.githubusercontent.com/82353425/180186374-4f8a0cc8-8016-4183-82c8-f8b59f442606.png)

2.当我的仪表板全屏之后就无法点击了
![image](https://user-images.githubusercontent.com/82353425/180186520-fc77f600-a2da-4c5e-aaf4-70c7407562e2.png)

**Comment by yayanpei** [comment]
感谢反馈，我们尽快修复一下

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
