### ISSUE TITLE
[Feature] Mycat数据源，直连看不到数据库下的表名

### ISSUE THREAD

**Issue by hzhfit2cloud** [dataease/dataease#2661]
**请描述您的需求或者改进建议.**
虽之前未在官方看到过 DataEase 对于 Mycat 数据源支持的相关发布，

但是 V1.10.0 版本时尝试使用 MySQL 数据源类型 连接 Mycat，能够正常进行数据库直连和查询，

升级到 V1.12.0 版本后，配置 Mycat 数据库能校验成功，可以正常使用SQL数据集，但是【直连看不到数据库下的表名】，查看容器日志后台无报错信息
![image](https://user-images.githubusercontent.com/89765365/180353393-f3844adc-d163-4fb9-ae89-62cb1a6bbb28.png)
(user_info 为 mycat 数据库)

后续是否会支持 Mycat 数据库呢~

**Comment by yayanpei** [comment]
感谢反馈，您的需求我们已收到，各种类型的数据源支持在持续进行中，可以关注下我们的release note。
