### ISSUE TITLE
[Bug] 系统管理 - 基础设置 - 消息保留时间（天）提示信息不正确

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2662]
**DataEase 版本**
v1.12.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 103.0.5060.134

**Bug 描述**
如图所示：实际允许填写的内容与提示符不一致
![image](https://user-images.githubusercontent.com/30063018/180353534-9014bd04-9730-48c9-a9a6-6db1d65c49d7.png)

**Comment by BBchicken-9527** [comment]
感谢反馈我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
