### ISSUE TITLE
[Feature] 视图层的时间格式能不能支持季度或者周

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2664]
**请描述您的需求或者改进建议.**
1.例如现在DataEase 里面是这种格式
![eba49364831251d709877c608bca93f](https://user-images.githubusercontent.com/82353425/180354922-83f5f341-5039-4fe2-841b-afc81ed43488.png)
2.能不能新增支持，季度，天数，周数这种嘞
![c1e8eb42426055e4749b9285a9a922f](https://user-images.githubusercontent.com/82353425/180354943-cbdd04e6-70b3-4dd9-9622-99b5e3af73b8.png)

**Comment by yayanpei** [comment]
感谢反馈，您的建议很不错，我们会优先规划的。
