### ISSUE TITLE
[Bug] 透视表无法按照设置的字段跳转

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2665]
**DataEase 版本**
1.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 重现步骤(有截图更好)**
1.将官方实例制作好透视表
![image](https://user-images.githubusercontent.com/82353425/180357719-3a59445d-4820-4737-ad79-68192012ebc5.png)

2.将产品名称作为跳转点，将销售额也作为跳转点
![image](https://user-images.githubusercontent.com/82353425/180358057-c68a4167-765c-4c5d-805f-61207cf70ba0.png)

3.只能点击第一列可以跳转，其他都不能跳转
![image](https://user-images.githubusercontent.com/82353425/180357829-280ec413-6c72-4641-bfca-2989c6b3be29.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，透视表目前只支持指标的跳转的

**Comment by ywhfzy** [comment]
销售额也是指标吧，为什么销售额那列点了不跳转了。。。

**Comment by BBchicken-9527** [comment]
点击销售额是不是有提示？如未获取跳转信息这样的提示

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
