### ISSUE TITLE
[Bug] 透视表指标排序问题

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2674]
**DataEase 版本**
1.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 重现步骤(有截图更好)**
1.首先将官方案例制作透视表，如图所示
![image](https://user-images.githubusercontent.com/82353425/180417304-5dee5345-9478-429c-af47-f5212d98ec4e.png)

2.我将销售额进行从大到小排序，1322居然排到1222后面
![image](https://user-images.githubusercontent.com/82353425/180417410-4251f407-aa30-40c2-adc0-6595f4e7f9e2.png)

3.我将销售额进行从小到大排序，1222居然排到1322后面
![image](https://user-images.githubusercontent.com/82353425/180417655-60b9738f-04cd-4ed9-947a-7952f7d0ca24.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，如果如你所说二部在第一个位置那2021年的就错了...透视表这么用其实是有问题的

**Comment by ywhfzy** [comment]
后续会不会新增按照总计来排序呢。。。

**Comment by BBchicken-9527** [comment]
感谢反馈，透视表按字段排序的话，同一字段生成多个列，所以没有办法去按照表格列排序，所以只能前端处理。

**Comment by ywhfzy** [comment]
只能前端处理的意思是视图层面对指标进行排序吗？还是说什么。。。

**Comment by BBchicken-9527** [comment]
嗯。。。这个地方这个地方我们例会讨论一下吧。目前的排期来看是没有新增字段排序的。
