### ISSUE TITLE
[Bug]backend编译package io.dataease.plugins.common.base.domain 找不到AreaMappingGlobal

### ISSUE THREAD

**Issue by yffwawa** [dataease/dataease#2675]
**DataEase 版本** dev版本

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome

**Bug 描述**
mvn clean package -Pstage
backend编译package io.dataease.plugins.common.base.domain 找不到AreaMappingGlobal

**Bug 重现步骤(有截图更好)**
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/109802232/180434056-ae230ad7-37aa-4cb7-a5da-7c8e7c9467f6.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，建议使用正式版本的

**Comment by xuwei-fit2cloud** [comment]
在以源码方式运行 DataEase 时，推荐大家使用 v1.0、v1.1 等已发布分支的代码，main 和 dev 分支的代码均处于开发阶段，有些使用到的依赖由于没有达到稳定状态，并没有上传到中央仓库。
