### ISSUE TITLE
[Bug]数据集添加定时同步数据集，为数据集添加立即执行的同步任务，任务执行中时删除任务，导致无法再执行其他任务

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#2678]
**DataEase 版本**
v1.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
数据集添加定时同步数据集，为数据集添加立即执行的同步任务，任务执行中时删除任务，导致无法再执行其他任务
提示异常：“已有同步任务在运行，稍后同步”

**Bug 重现步骤(有截图更好)**
1、添加定时同步数据集
2、为数据集添加 一个 立即执行的 同步任务
3、当任务处于执行中状态时，删除此任务
4、再次创建一个 立即执行的 同步任务，此时提示异常：“已有同步任务在运行，稍后同步”
且无论等待多久，都是这种状态，只能删掉这个数据集 重新添加新的数据集
![tapd_55578866_base64_1658717018_23](https://user-images.githubusercontent.com/89771514/180692703-d3485747-3bc1-4c08-ba40-666be7cd3c16.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，从报错上来看你应该是删除了之后再在同一个数据集上创建定时任务，提示是因为你虽然删除了定时同步，但是程序依然在执行你删除的定时任务并且没有完成，当完成后才可以执行下一个，你不删除任务也是无法创建两个同时执行的任务的

**Comment by ZhaoQian1222** [comment]
是的，但是实际上执行中的任务删除后一直执行不完，这应该是个bug，百分百复现

--------------原始邮件--------------
发件人："BBchicken-9527 ***@***.***&gt;;
发送时间：2022年7月25日(星期一) 下午3:01
收件人："dataease/dataease" ***@***.***&gt;;
抄送："赵乾 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [dataease/dataease] [Bug]数据集添加定时同步数据集，为数据集添加立即执行的同步任务，任务执行中时删除任务，导致无法再执行其他任务 (Issue #2678)
-----------------------------------

 

 
感谢反馈，从报错上来看你应该是删除了之后再在同一个数据集上创建定时任务，提示是因为你虽然删除了定时同步，但是程序依然在执行你删除的定时任务并且没有完成，当完成后才可以执行下一个，你不删除任务也是无法创建两个同时执行的任务的

**Comment by BBchicken-9527** [comment]
嗯...这个是我们的执行策略，并不是bug的。因为要考虑大数据情况下，删除任务即停止同步的话会导致大量数据回滚。这个对服务器的性能的消耗和时间的消耗会比较大，所以采用这种正在执行中的任务执行后终止定时计划

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
