### ISSUE TITLE
产品使用中的感悟和建议

### ISSUE THREAD

**Issue by sanlywork** [dataease/dataease#2682]
1 查询组件和view的关联
 当前: 在这个绑定上面,目前只让选着每个view里面的某个字段和查询组件去关联.
 问题: 每个view的字段如果都相同情况下,无法区分出来什么view已经绑定了查询组件.
 建议:绑定关系建议用列表或tree的形式显示当前查询和哪个view已经做了关联设置了.
2 查询组件数据集设定
  当前:下拉查询的的数据集是通过绑定关联view的字段,取最大合集
  问题:正常使用中,例如一个公司/项目,是一个独立的数据集,而不是从每个view去取数合计,
  建议:一个查询组件的数据集也应该和普通组件一致,从某个数据集中来构建的
3 页面操作性
   3.1 定位
           当前:定位是依赖鼠标来调整位置
           问题:依赖鼠标的话,精确位置其实很难做到很高的
           建议:可以响应键盘的方向操作做到以像素级别的移动来实现.
  3.2 批量操作
       当前:目前12版本里面已经提供了批量操作效果.
       问题:实现是用每个每个去勾选选定后,再操作,其实这样操作实际很慢,而且在层重叠情况下,几乎很难选的
       建议:批量操作应该有个tree的结构列表,去选择操作要批量操作的对象组件.
  3.3 无容器和分组概念
      当前:每个组件都是独立的,要复制必须单独复制
      问题:实际业务场景里面,一个部件,应该是一批的组件来构建的,而且这个部件里面一般是一个矩形外框,里面放入组件,那么这个矩形是容器,矩形里面的组件,的定位相对于矩形的..这样就可以把按矩形定位的组件放入矩形定位的矩形容器里.而且也可以建立一个分组的部件集合.如果选矩形来复制,那么就可以复制里面的全部子控件.而且从操作来所,用tree来展示也是最佳的.
   3.4 操作时候可以定时保存&版本历史
    当前:一个大屏设计中,除非点保存,否则都不记录操作
    问题:如果设计过程漫长,不小心点了什么操作,那之前的整体设计就全丢了.(有惨痛教训,那些危险按钮操作,需要加二次确认的)
    建议:给一个定时保存操作草稿和历史版本,可以回溯历史的.这样就不会丢操作了.
4 扩展性
    4.1 建议开放模板的外部贡献,这样可以极大丰富-模板市场.包括背景图片,这些素材,
   4.2 建议对封装的echart的和antv的组件,可以再展现前,可以自定义修改相应图形化配置的json对象.,这样可以有很多想象空间.或者也可以用图形化市场方式来丰富图形化组件.
图形化的东西,一般是给领导或者决策层看的,那么关注点并不是在于数据怎么来的,关键是,[好看],[新颖],能第一眼抓住眼球的.所以颜值是第一的.这点是决定了是否使用的关键了.
这个产品,在同类开源里面,做的不错的,口碑在慢慢积累,有不少的关注度,所以要真正去了解市场-关注点也最关键的.要用市场眼光看产品,而非技术的角度..
   另外有个bug.
     excel导入数值的时候,例如74.1.会变成74.099999999这样的数值的.
希望贵软件,越来越好.

**Comment by sanlywork** [comment]
3.5  数据集和看板的关系
     目前:目前是数据集和看板是引用关系.我猜其目的是为了最大化复用数据集
     问题:目前的i项目,其实都是一个看板定义自己一堆的数据集,很难跨看板去服用的.而且独立分开了,不便于迁移看板.有时候修改数据的时候还需要回到看板去找用了什么数据集,再去到数据集里面再找到对象修改,这样很是麻烦
    建议: 把数据集融合到每个看板里面,这样做的好处是,-看板是独立对象了.其二,可以做到请求一次整体数据集就可以减少很多组件的单独请求了.其三,修改时候也很方便的.
3.6 建议数据集的列表页面,增加excel数据集的导出功能.便于修改.

**Comment by xuwei-fit2cloud** [comment]
非常感谢您反馈的问题，也非常感谢您对我们产品的关注。关于您在issue里提到的一些问题，我在这里给您解答一下：

1 查询组件和view的关联
> 这个是一个已知问题，目前已经移交给UX进行相关交互设计，后期会有改进。

2 查询组件数据集设定
> 过滤组件选择字段时，目前版本也是可以按照数据集来选择的。如果多个视图是基于同一个数据集制作的，可以选择这个方式。

3 页面操作性
3.1 定位
> 很好的建议，我们已记录。我们也会综合考虑是否支持具体坐标设置等方案。

3.2 批量操作
> 之前的设计是以树形结构提供选择的，但觉得树形展示在视图及组件过多的情况下并不直观，所以才设计成了预览勾选的方式。对重叠下难选择的情况，我们再想想如何处理。

3.3 无容器和分组概念
> 分组的功能我们内部也有讨论过，但目前还没有一个商定的结果，后续有明确设计的话，我们会做支持的。

3.4 操作时候可以定时保存&版本历史
> 当前版本已经对一些可能导致仪表板未保存的事件进行了处理，如浏览器的前进、后退，页面的返回等，但确实仍然有操作并未记录。这个问题我们内部也有过多次讨论，也是我们后续会处理的问题。

3.5 数据集和看板的关系
> 在我们所知的大部分用户的使用场景中，一个仪表板确实需要用到来自多个数据集的数据，甚至有相当用户的数据是来自不同的数据源。我们也清楚，在视图制作时会需要修改数据集的一些设置，所以我们将更换数据集，修改数据集字段等功能以快捷方式融入到了视图制作中，目前除了SQL数据集语句修改外，大部分都还是可以处理的。关于仪表板的迁移，我们对视图所用到数据集的替换也做了优化，若替换数据集字段能匹配的话，我们会自动匹配，并没有过多其他的操作。当然可能还有更便捷的方式，我们也会持续改进。

3.6 建议数据集的列表页面,增加excel数据集的导出功能.便于修改
> 目前在数据集页面中我们也仅提供了最多9999条数据的预览功能，若数据集数据量过大，Excel的导出压力也会比较大。如果可以接受导出数据上限的限制，我觉得还是可以支持的。


4 扩展性
4.1 建议开放模板的外部贡献,这样可以极大丰富-模板市场.包括背景图片,这些素材
> 模板市场刚刚推出还在探索阶段，关于后续是否会开放模板的提交，目前还在讨论阶段。

4.2 建议对封装的echart的和antv的组件,可以再展现前,可以自定义修改相应图形化配置的json对象.,这样可以有很多想象空间.或者也可以用图形化市场方式来丰富图形化组件
> 这个我们也有讨论过，但我们产品设计是想一步步降低DataEase的使用门槛，可以让更多人轻松的上手来使用，我们后续也会考虑提供高级设置功能，来支持代码层面的自定义。当然，如果有更深入的定制化需求的话，也可以参考我们提供的插件工程进行二开修改。

excel导入数值的时候,例如74.1.会变成74.099999999这样的数值的
> 这个问题是一个已知问题，我们使用的POI的读取方式导致的，目前还没有比较好的解决方案。
