### ISSUE TITLE
[Bug] API数据源获取的json中有中括号，jsonpath无法识别

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#2684]
**DataEase 版本**
1.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome最新

**Bug 描述**
通过API数据源获取的API接口数据，API返回的json格式中带有中括号，jsonpath无法识别它。

**Bug 重现步骤(有截图更好)**
1. API接口是prometheus接口，http://10.1.13.196:32216/api/v1/query?query=up
用postman可以查看返回的数据如下：
<img width="943" alt="图片" src="https://user-images.githubusercontent.com/48307752/180731262-53b87f32-8763-44e2-855e-3acf6e40ce6f.png">

2. 在DataEase中新建api数据源，api如上，json只能写到 $.data.result
通过jsonpath提取的信息如下所示：
<img width="769" alt="图片" src="https://user-images.githubusercontent.com/48307752/180731511-715eba62-c50e-4bed-af5c-ee73c1da9908.png">

3. 返回结果为最终提取数据，如果再继续写jsonpath为：$.data.result.metric 就反会报错:
<img width="899" alt="图片" src="https://user-images.githubusercontent.com/48307752/180731888-304a34f9-f3bc-4eb3-9d1f-5d72ca3622cc.png">

4.在新版本的api接口调整有没有兼容json中括号 避免出现无法识别格式的报错？

**Comment by BBchicken-9527** [comment]
感谢反馈,如果你想取list中的数据需要添加下标你可以尝试使用$.data.result.[0].metric
