### ISSUE TITLE
[Feature] 自定义数据源检测时间间隔

### ISSUE THREAD

**Issue by hzhfit2cloud** [dataease/dataease#2685]
**请描述您的需求或者改进建议.**
发现定时同步任务中设置的是每天同步一次数据，但是在调用系统的后台日志中发现几乎每半个小时DE就会调用一次接口
根据研发小伙伴的反馈：
DE内置了数据源的检测机制，每半小时会调用一次数据源来验证数据源是否有效

考虑到每次检测数据源时，会对数据源产生一定的压力
希望：能在系统管理设置中，用户能自定义检测数据源有效性的间隔时间

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。
