### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by yhy729** [dataease/dataease#2686]
系统管理-操作日志 建议添加 操作用户IP信息。
一般admin会给多个用户使用，当多个用户操作后无法区分实际是谁修改了仪表板设置

**Comment by yayanpei** [comment]
感谢反馈，目前是不记录ip的，我们先记录一下需求。建议您先给不同的用户创建不同的账号使用。

**Comment by yhy729** [comment]
好的 谢谢
