### ISSUE TITLE
[Bug]backend 编译失败

### ISSUE THREAD

**Issue by yffwawa** [dataease/dataease#2690]
**DataEase 版本**
1.12

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome

**Bug 描述**
mvn clean package 报错

**Bug 重现步骤(有截图更好)**
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/109802232/180773875-a915a438-ebc9-4da0-b440-b65b7f07cd26.png">

**Comment by BBchicken-9527** [comment]
https://dataease.io/docs/dev_manual/dev_manual/

**Comment by xuwei-fit2cloud** [comment]
再次对v1.12分支代码进行过验证，是可以正常编译的，请参考相关文档
https://dataease.io/docs/dev_manual/dev_manual/
