### ISSUE TITLE
[Bug] 权限管控紊乱

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2695]
**DataEase 版本**
1.2.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版本

**Bug 描述**
给【普通用户】添加某个数据集的「使用」权限，但是用户却可以删除该数据集以及可以编辑数据集。

**Bug 重现步骤(有截图更好)**
同描述

**Comment by BBchicken-9527** [comment]
感谢反馈，使用权限是无法进行数据集的修改和删除操作的，因为de的权限控制是三个方向叠加的分别是组织、角色与用户。如果这三类有任何一个存在管理及以上权限都是可以进行删改操作的。所以需要你再确定一下

**Comment by AndroidBaby1** [comment]
1 新建一个用户
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/24768910/180943838-48116786-9913-4181-91eb-a6f97dabdecf.png">
2 给配置数据集使用权限
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/24768910/180943916-b4435832-44b5-461c-ae97-1550315adc5c.png">
3 进入用户界面，点击数据集操作
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/24768910/180943725-025e3190-3868-406b-bc97-3d24ade54e2c.png">

**Comment by BBchicken-9527** [comment]
嗯，你普通员工是否又这个数据集的管理权限呢？

**Comment by AndroidBaby1** [comment]
感谢，这边查看确实默认给予的【普通员工】这个角色有该数据集的管理权限，去掉，权限达到想要的效果了，谢谢。
