### ISSUE TITLE
[Bug]仪表板定时刷新时外部参数失效

### ISSUE THREAD

**Issue by IsSeptember** [dataease/dataease#2696]
**DataEase 版本**
v1.12.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 103.0.5060.134（正式版本） (x86_64)

**Bug 描述**
1、对仪表板设置外部参数与公共链接，将仪表板刷新频率设置为较小值如30s
2、仪表板数据集使用API数据源
3、访问公共链接追加参数对仪表板视图数据进行筛选

一、
在平台数据集更新设置里进行全量更新，数据有新增
正在访问的仪表板到时间刷新后，数据将变为所有数据，筛选失效

二、
数据集不进行更新，访问的仪表板到时间刷新后，数据变成不符合参数条件的数据（或为空），刷新窗口变正常，再次定时刷新复现

**Comment by BBchicken-9527** [comment]
感谢反馈，此处已知问题，目前正在修复

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
