### ISSUE TITLE
[Bug]Abnormal log output The log information is incorrect.

### ISSUE THREAD

**Issue by wjh769720251** [dataease/dataease#2697]
**DataEase 版本**
dev

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
Abnormal log output The log information is incorrect.

**Bug 重现步骤(有截图更好)**
1.LogUtil.info("Succsss to {} datasource connection pool: {}", type, datasource.getName());
2.
![微信图片_20220726142532](https://user-images.githubusercontent.com/65284523/180938200-f9ca4016-6f57-48e8-98fb-9029d78908aa.jpg)

3.
![Snipaste_2022-07-26_14-26-05](https://user-images.githubusercontent.com/65284523/180938214-39e707d6-ae43-4cda-8cb2-e9d2f9ae1ff4.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by wjh769720251** [comment]
: )

**Comment by BBchicken-9527** [comment]
问题已修复，感谢你的反馈
