### ISSUE TITLE
[Bug] 仪表板样式颜色设置与视图颜色设置不同步的问题

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2698]
**DataEase 版本**
1.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.新建一个仪表板，里面添加视图，然后编辑仪表板样式颜色。我已经将仪表板的表头颜色设置了紫色，但是视图层面还是黄色
![image](https://user-images.githubusercontent.com/82353425/180941204-9836116f-d4aa-4e14-8daa-3ab612373093.png)

2.然后我点击视图，表格配置选择左对齐，表头颜色又变成了黄色。
![image](https://user-images.githubusercontent.com/82353425/180941463-52c89286-b0e8-4281-939a-349e39f507c5.png)

3.后面自己测试下了，只能将鼠标点击其他地方，然后再重新点击视图上，视图的表格颜色才会跟仪表板上的对齐。

4.能不能选择仪表板的颜色配置之后，视图颜色就能同时生效呢？

**Comment by xuwei-fit2cloud** [comment]
目前确实是这样设计的，只有焦点从颜色选择上移开后才会触发渲染，避免不必要的操作。
