### ISSUE TITLE
[视图] AntV 图库透视表

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#2700]
**请描述您的需求或者改进建议.**
在样式框，调整字体颜色后，总计栏颜色没有变化。
1. 截图如下
![image](https://user-images.githubusercontent.com/96223591/180950823-d3f56f57-b036-4c48-9469-68fbdf387729.png)

![image](https://user-images.githubusercontent.com/96223591/180950916-c57413c4-b98f-4461-87c5-93c18d7362d1.png)

字体颜色定义的不是整个表格内的字体颜色吧，按理调整这边应该是整个表格的字体颜色发生改变。

**Comment by yayanpei** [comment]
感谢反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
