### ISSUE TITLE
[Bug] AntV 图库汇总表没有合计

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#2702]
**DataEase 版本**
v1.12.0 版本

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 103.0.1264.71 (正式版本) (64 位)

**Bug 描述**
理论上汇总表应该是有合计的汇总功能，AntV 图库汇总表无法显示合计。

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/96223591/180954781-4e3742a0-d7ed-456d-95e1-83e15e3e4d41.png)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，AntV的汇总表是不带汇总的，若你想使用带汇总功能的汇总表可以使用Echartst的汇总表
