### ISSUE TITLE
[Bug]仪表板分享 无法选定角色、用户

### ISSUE THREAD

**Issue by yffwawa** [dataease/dataease#2710]
**DataEase 版本**
1.12

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 103.0.5060.134（正式版本） (x86_64)

**Bug 描述**
仪表板点击“分享”，用户tab下 无法选定某个用户

**Bug 重现步骤(有截图更好)**
1. 
<img width="340" alt="image" src="https://user-images.githubusercontent.com/109802232/181008016-ff73a3ae-b717-4d73-907b-6b6fc3a95daa.png">

2.
<img width="448" alt="image" src="https://user-images.githubusercontent.com/109802232/181008150-6d66c2dc-bf74-4375-a83f-85439f98c7f6.png">

**Comment by xuwei-fit2cloud** [comment]
在这一行最后面有一个勾选框，可以勾选，参考下图
![图片](https://user-images.githubusercontent.com/1892127/181145622-4f1f6e75-dd76-40b1-ba6b-c384900742b8.png)
