### ISSUE TITLE
[Bug] 数据集 - SQL 数据集子查询中用参数报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2712]
**DataEase 版本**
1.12.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版本

**Bug 描述**
SQL 数据集子查询中用参数报错

**Bug 重现步骤(有截图更好)**
1.SQL 数据集子查询中用参数报错
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/24768910/181145619-485d26d8-b75d-4983-ac04-b47331047a70.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下

**Comment by tjlygdx** [comment]
这个sql本身就是错误的

sql 应该这样写：SELECT id, user_id,login_name FROM  sys_log t where t.login_name='${login_name}';

**Comment by xuwei-fit2cloud** [comment]
测试了一下，应该是少了alias，可以写成这样：
SELECT id, user_id,login_name FROM (select * from sys_log t where t.login_name='${login_name}') s
然后在参数里加上值即可
