### ISSUE TITLE
[Bug]文本下拉组件联动表格进行筛选，清空所选值，表格外部参数失效

### ISSUE THREAD

**Issue by IsSeptember** [dataease/dataease#2714]
**DataEase 版本**
v1.12.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 103.0.5060.134（正式版本） (x86_64)

**Bug 描述**

**Bug 重现步骤(有截图更好)**
非百分百复现
1、仪表板内设置文本下拉组件单选，根据某个字段联动下方表格视图
2、通过公共链接与外部参数访问仪表板
3、选中文本下拉组件某个值，表格正常筛选；点击下拉框后边的清除按钮，表格显示所有数据，外部参数失效

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
