### ISSUE TITLE
[Bug]系统管理-权限设置，给个人-数据集《新建视图》只设置使用权限生效后，个人数据集《新建视图》不见了不能继续修改权限

### ISSUE THREAD

**Issue by xhy12** [dataease/dataease#2717]
**DataEase 版本**

v1.12.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**

系统管理-权限设置，给个人-数据集《新建视图》只设置使用权限生效后，个人数据集《新建视图》不见了不能继续修改权限
**Bug 重现步骤(有截图更好)**
1.系统管理-权限设置，给个人-数据集《新建视图》只设置使用权限，生效后数据集不能对字段进行编辑
2.再次进入系统管理-权限设置，修改个人-数据集
<img width="1440" alt="微信图片_20220727171353" src="https://user-images.githubusercontent.com/43202800/181224652-e068112b-ca78-4a5d-807e-bc016b43c948.png">
<img width="960" alt="新建视图数据集不见了" src="https://user-images.githubusercontent.com/43202800/181224668-1904ec67-9869-47f9-92be-d34ed1e2ff63.png">
此时无法选择到《新建视图》
3.期望：再次修改权限可以选到《新建视图》

**Comment by BBchicken-9527** [comment]
感谢反馈，请问用户也是普通员工的角色吗？

**Comment by xhy12** [comment]
账号是普通员工角色

**Comment by xhy12** [comment]
改成管理员也看不到

**Comment by BBchicken-9527** [comment]
嗯...是这样的，数据源、数据集和视图内的数据具有唯一性，比如你创建的一个【新建数据集】那么你讲拥有最高权限，除了你以外没有人可以看到并操控这个【新建数据集】（admin除外），如果你要是自己给自己降级的话，就会导致你没有了管理权限和授权权限这样当然也无法再去更改【新建数据集】。

**Comment by xhy12** [comment]
那这样谁能在管理呢？admin账号现在也看不到了，那这个数据集就报废了吗？这里不是很合理吧

**Comment by BBchicken-9527** [comment]
admin账号也看不到了吗？受累你看一下admin账号中在数据集下面能不能看到你的这个数据

**Comment by BBchicken-9527** [comment]
其实你可以用这里搜索的
![image](https://user-images.githubusercontent.com/84372766/181678108-c6b55f9b-d02a-4f55-894b-a8d4fc60e107.png)

**Comment by xhy12** [comment]
试用管理员账号demo_admin  但是也看不到《新建视图》  见截图
<img width="960" alt="试用管理员账号demo_admin  但是也看不到《新建视图》" src="https://user-images.githubusercontent.com/43202800/182106755-3366a4b3-154a-43d0-a924-2aa9338144c0.png">

**Comment by BBchicken-9527** [comment]
额。这个账号是你自己建的还是你改名字了？我说的是id为admin的账号，只有id为admin的账号才可以看到的

**Comment by xhy12** [comment]
就是默认管理员账号

**Comment by xhy12** [comment]
你试下呢？？

**Comment by BBchicken-9527** [comment]
不可以的。在de中管理员也是角色的一种。并不是超管的意思

**Comment by xhy12** [comment]
好吧，获取不到超管权限，先关闭吧
