### ISSUE TITLE
[Feature] 可以删除一些无用依赖包不？

### ISSUE THREAD

**Issue by hankaibo** [dataease/dataease#2720]
**请描述您的需求或者改进建议.**
简单看了一下前端代码，安装了好多5年，甚至8年之前已停止维护的代码库。而且也找不到在代码中有什么地方引用。
例如：
css-color-function
file-save
videojs-flash
vcolorpicker // 未看到其使用
vue-codemirror, vue2-ace-editor // 是否考虑合并为一个？

**Comment by yayanpei** [comment]
如果是引用后没有使用的话，没有影响，可以删除的。无用的代码我们也在逐步清理中，感谢您对产品的关注和支持。

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
