### ISSUE TITLE
[Bug] 定时报告发送仪表板图片，仪表板图片内容不完全。

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2721]
**DataEase 版本**
1.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌

**Bug 描述**
1.用户做的一个仪表板很长，需要下拉才能看到完整版。
2.进行定时报告设置之后，发送的图片只能是截图一半。
3.但是在仪表板内导出图片是没有问题的。

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，正在修复中，下个版本就会上线
