### ISSUE TITLE
[Bug]sql动态入参复杂where条件拼接bug、带有临时表sql且带有动态入参 sql拼接后临时表部分丢失

### ISSUE THREAD

**Issue by wei352641884** [dataease/dataease#2722]
**DataEase 版本**
12

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
谷歌5.1.6.6 

**Bug 描述**
bug1：

> 类似如下的复杂where条件当前12版本动态入参替换后出错

示例sql：
`where IFNULL(a.disabled,0) = 0 and IFNULL(a.type,0) = 110 and name = ‘${NAME}’`

**期望**替换后sql输出：

`where IFNULL(a.disabled,0) = 0 and IFNULL(a.type,0) = 110 and 'BI'='BI'`

**实际**替换后sql输出：

`where IFNULL(a.disabled0) = 0 and IFNULL(a.type0) = 110 and 'BI'='BI'` （IFNULL(a.disabled0) 逗号丢失，导致sql报错）

bug2：

> 对于使用了临时表的并且带有动态参数的sql，12版本会在替换掉动态参数的时候 也会把with条件的临时表部分丢失

示例sql：

`WITH temp_1 AS ( SELECT id FROM a WHERE type = 1; ) SELECT temp_2.id, temp_2.NAME FROM b AS temp_2 LEFT JOIN temp_1 ON temp_1.id = temp_2.a_id WHERE temp_2.type = 1 AND IFNULL( temp_2.closed, 0 ) = 1 AND DATE_FORMAT( temp_2.createDate, '%Y-%m' ) = '${date}';`

**期望**替换后sql输出：

`SELECT * FROM(WITH temp_1 AS ( SELECT id FROM a WHERE type = 1; ) SELECT temp_2.id, temp_2.NAME FROM b AS temp_2 LEFT JOIN temp_1 ON temp_1.id = temp_2.a_id WHERE temp_2.type = 1 AND IFNULL( temp_2.closed, 0 ) = 1 AND DATE_FORMAT( temp_2.createDate, '%Y-%m' ) = '2022-07';) AS tmp LIMIT 0,1000`

**实际**替换后sql输出：

`SELECT * FROM(SELECT temp_2.id, temp_2.NAME FROM b AS temp_2 LEFT JOIN temp_1 ON temp_1.id = temp_2.a_id WHERE temp_2.type = 1 AND IFNULL( temp_2.closed, 0 ) = 1 AND DATE_FORMAT( temp_2.createDate, '%Y-%m' ) = '2022-07';) AS tmp LIMIT 0,1000 （WITH部分丢失）`

**Bug 重现步骤(有截图更好)**
bug1修复步骤如下：下图代码替换

![image](https://user-images.githubusercontent.com/101615277/181404712-11ac25b0-6305-4b32-bc8d-9aaf9592b237.png)

```
@Override
public void visit(ExpressionList expressionList) {
    for (Iterator<Expression> iter = expressionList.getExpressions().iterator(); iter.hasNext();) {
        Expression expression = iter.next();
        expression.accept(this);
        if (iter.hasNext()) {
            buffer.append(", ");
        }
    }
}
```

bug2修复步骤如下：下图代码添加

![image](https://user-images.githubusercontent.com/101615277/181406307-70be251d-75ae-4b36-a760-acc06fd46982.png)

```
//这里处理 WITH的情况
StringBuilder builder = new StringBuilder();
if (CollectionUtils.isNotEmpty(select.getWithItemsList())) {
    builder.append("WITH");
    builder.append(" ");
}
for (Iterator<WithItem> iter = select.getWithItemsList().iterator(); iter.hasNext();) {
    WithItem withItem = iter.next();
    builder.append(withItem.toString());
    if (iter.hasNext()) {
        builder.append(",");
    }
}
builder.append(plainSelect);
return builder.toString();

```

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下。

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
