### ISSUE TITLE
[Bug] 日期范围过滤组件

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2725]
**DataEase 版本**
1.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
DataEase 中的日期范围组件的自定义日期能不能支持开始时间设置1日前，结束时间设置1日前。
场景就是我需要默认查看前一天的信息，然后还能给普通用户进行日期范围的选择。
现在的判断逻辑是开始时间与结束时间相等不能按【确认】
![image](https://user-images.githubusercontent.com/82353425/181446218-2a01c214-4a40-4235-b043-83b96cbeb278.png)

并在仪表板上设置时间范围可以选择同一天时间。
![image](https://user-images.githubusercontent.com/82353425/181446778-b605fe7a-43e1-4bdb-8189-b49d4baa3d82.png)

**Comment by xuwei-fit2cloud** [comment]
嗯，目前是这么设计的，我们考虑一下是否需要支持同一天的选项。

**Comment by ywhfzy** [comment]
好嘞好嘞

**Comment by xuwei-fit2cloud** [comment]
v1.14版本中已经实现，请等待新版本。
