### ISSUE TITLE
[Bug]Excel 模块显示为灰色

### ISSUE THREAD

**Issue by behradiy** [dataease/dataease#2742]
**DataEase 1.11.3**

**本地安装**

**Chrome 103 on macOS (Monterey)**

**我无法将 Excel 文件导入 DataEase**
也不支持 CSV 文件
是否有任何进一步的更新？

**这是它的图片:**
![image](https://user-images.githubusercontent.com/63799050/182013025-8935e756-c0b2-4748-923a-04604ae03277.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前环境上没有发现你的问题，可以尝试升级看看

**Comment by behradiy** [comment]
tagging release w.t.f.
