### ISSUE TITLE
[Feature]如果目标是数据可视化平台，是否可以考虑添加报表的功能

### ISSUE THREAD

**Issue by yl-yue** [dataease/dataease#2750]
你好，如果目标是数据可视化平台，是否可以考虑添加报表的功能。
报表+大屏=数据可视化平台（BI商业智能）

**Comment by maninhill** [comment]
感谢您的反馈。我们当前阶段专注把数据可视化工具做好，达到人人可用，暂时还没有开发报表功能的计划。
