### ISSUE TITLE
[Bug] 精简模式传入Excel强制保留两位小数

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2751]
**DataEase 版本**
1.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌标准

**Bug 重现步骤(有截图更好)**
将Excel传入精简版DataEase 中，默认保留两位小数。

![image](https://user-images.githubusercontent.com/82353425/182119106-1daf537f-ca42-4010-89fc-84ccf76f07b1.png)

![image](https://user-images.githubusercontent.com/82353425/182119163-00a9aa0a-5778-40a7-92a9-19d3d77efd9a.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，下个版本将修复此问题

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已解决，请使用最新版本。
