### ISSUE TITLE
[Bug] Antv表格与Echart表格默认保留两位小数

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2753]
**DataEase 版本**
1.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
1.Antv表格与Echart表格默认保留两位小数

![1960afa6-263d-45fd-b98b-a57c10af1ca6](https://user-images.githubusercontent.com/82353425/182123052-cf8d8067-32ce-4d70-b456-af0d149e5c3e.png)

2.使用的是Excel数据集，本地模式，在数据集层看的是0.027，是正常的，但是转入表格的话就自动保留两位小数。
![799e8a3e-f763-4569-b46a-2634453bc7e7](https://user-images.githubusercontent.com/82353425/182123249-352f541a-a523-44b0-996c-174686a21cf4.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前使用版本因为doris原因强制截取两位小数，，视图层面也被控制了，问题将会在下个版本修复，欢迎到时下载体验

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已支持，请使用最新版本。
