### ISSUE TITLE
[Bug] 仪表板主题色更换，视图标题显示

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2760]
**DataEase 版本**
1.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 重现步骤(有截图更好)**
1.在浅色背景下，视图内的标题不显示
![image](https://user-images.githubusercontent.com/82353425/182294424-77a7d7f5-5861-4a51-ab41-c6139ab91194.png)

2.切换到深色背景的时候，视图的标题显示了

![image](https://user-images.githubusercontent.com/82353425/182294482-cf87c417-9902-4ef4-a6c4-3e47c3ada8db.png)

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已支持，请使用最新版本。
