### ISSUE TITLE
[Bug] 系统管理不能创建用户模板分类

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2771]
**DataEase 版本**
1.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 重现步骤(有截图更好)**
1.新建分类创建，报错500
![image](https://user-images.githubusercontent.com/82353425/182532438-6de75039-ae5a-48ea-abb5-d23c4bd4ebd8.png)

2.bug代码
![4c6502e6-a70d-42c6-8c18-f7c331a62d2d](https://user-images.githubusercontent.com/82353425/182532468-a2883327-0310-4584-85b4-e48611dce5e6.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下。

**Comment by xuwei-fit2cloud** [comment]
v1.13.0版本已支持，请使用最新版本。
