### ISSUE TITLE
[Bug]SQL 数据集问题

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2777]
**DataEase 版本**
1.12.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版本

**Bug 描述**
SQL 数据集用参数的形式数据预览处不显示数据

**Bug 重现步骤(有截图更好)**
1.写死参数有数据
![image](https://user-images.githubusercontent.com/24768910/182568536-778bbc1f-a8e5-4fe6-9508-e9f8c524d971.png)
2.用参数，然后用第 1 步写死的参数做默认值
2.1 编辑窗口有预览数据
![image](https://user-images.githubusercontent.com/24768910/182568718-4d6be6a7-0437-4e7b-bd7a-c87452060c56.png)
2.2 查看窗口无预览数据
![image](https://user-images.githubusercontent.com/24768910/182568816-cb647024-722e-4307-b74c-ef93a7772878.png)

注意：SQL 只能私发，不可公开
数据源类型：SQLserver

**Comment by xuwei-fit2cloud** [comment]
某些形式的带参的SQL语句还没有完全支持上，在后续版本会逐步完善。

**Comment by AndroidBaby1** [comment]
好的，感谢
