### ISSUE TITLE
[Feature]增加符合参数场景的过滤组件

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2779]
**请描述您的需求或者改进建议.**
目前用户的 SQL 数据集中的参数非数据集展示字段，在与过滤组件关联的时候，希望支持用户手动输入值，而不需要关联视图字段或者数据集字段的情况。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个需求已经在计划内。

**Comment by AndroidBaby1** [comment]
好的，谢谢。
