### ISSUE TITLE
[Feature] 视图时间显示多样化

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2786]
**请描述您的需求或者改进建议.**
![origin_img_v2_f10cced0-d6cb-4863-b80a-59e2ccedab4h](https://user-images.githubusercontent.com/82353425/182745512-62d8aff5-96f4-4887-a052-18c9c31767f8.png)
这块日期显示，能比较个性化吗？
24小时，按5分钟展示。
![origin_img_v2_c18e706a-0a0c-4c87-822e-6695fe4d7eeh](https://user-images.githubusercontent.com/82353425/182745541-14393aa9-1051-4260-bd2a-66472782d7d8.jpg)
希望能多点格式。

**Comment by yayanpei** [comment]
感谢反馈，时间是根据数据集中的时间显示的，如您描述的按5分钟展示，建议您将先在数据集中将时间按需处理后，再在视图中展示。
