### ISSUE TITLE
[Bug]下拉树插件在全屏模式下无法输入关键字搜索

### ISSUE THREAD

**Issue by robinli2022** [dataease/dataease#2788]
**DataEase 版本**
v1.13.0/

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

google Chrome浏览器 版本 97.0.4692.71（正式版本） （64 位）
**Bug 描述**
下拉树插件在全屏模式下无法输入关键字

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/99721830/182760267-65e976c4-492e-4e8e-8934-a621a41aa9c9.png)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，下拉树搜索与其他组件不同， 搜索并不是实时的，需要点击搜索按钮才可以进行搜索，你尝试点击看一下

**Comment by xuwei-fit2cloud** [comment]
v1.14.0版本已解决，请升级到最新版本。
