### ISSUE TITLE
[Bug] 前端项目 canvas 组件源代码 （src\components\canvas\index.vue）中 import 路径似乎有错误

### ISSUE THREAD

**Issue by Dovahkinn** [dataease/dataease#2789]
**DataEase 版本**
最新， dev 分支

**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**
Chrome 100+

**Bug 描述**
源代码 import 路径

**Bug 重现步骤(有截图更好)**
1. ![](https://s3.bmp.ovh/imgs/2022/08/04/98f5d692374eda91.png)

2. src/components 目录下没有看到有对应的目录，应该是少了一层 /canvas

**Comment by BBchicken-9527** [comment]
感谢反馈，目前这个文件并没有得到实际的使用的。

**Comment by Dovahkinn** [comment]
好的
