### ISSUE TITLE
[Feature] Antv饼图支持丰富标签展示

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2790]
**请描述您的需求或者改进建议.**
1.希望Antv的饼图与Echart的饼图标签展示能一样。
可以都设置{a}{b}{c}等
![image](https://user-images.githubusercontent.com/82353425/182775326-cc17c73a-eb8b-4a6e-bb32-5873978036ea.png)

**Comment by xuwei-fit2cloud** [comment]
AntV系列视图支持了数值格式化，这部分目前会有些冲突，我们先讨论一下。
