### ISSUE TITLE
[Bug]组件为仪表盘，数值偏大时会出现挤在一起，无法做调整

### ISSUE THREAD

**Issue by geyesheng** [dataease/dataease#2791]
**DataEase 版本**

v1.13.0

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
104.0.5112.81（正式版本） （64 位）

**Bug 描述**
组件为仪表盘，数值偏大时会出现挤在一起，无法做调整

**Bug 重现步骤(有截图更好)**
1.设置仪表盘最大值为10000
![image](https://user-images.githubusercontent.com/38676947/182786025-dedf9b5d-839d-4bec-9fc9-34c7bd6c60f7.png)

2.设置标签展示，显示仪表盘值，叠加在一起（无地方可做调整）
![image](https://user-images.githubusercontent.com/38676947/182785575-c2e2d93d-17cc-4898-885c-bb4543229bf3.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，echarts因为一些原因不太好做调整，建议使用antv
