### ISSUE TITLE
[Bug]仪表板设置文件下拉组件，选择多个值时（有23个），会出现超时错误，无法正常显示下拉值（设置失效，不起作用）

### ISSUE THREAD

**Issue by geyesheng** [dataease/dataease#2792]
**DataEase 版本**
v1.13.0

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
104.0.5112.81（正式版本） （64 位）

**Bug 描述**
仪表板设置文件下拉组件，选择多个值时（有23个），会出现超时错误，无法正常显示下拉值（设置失效，不起作用）

**Bug 重现步骤(有截图更好)**
1.仪表板设置文件下拉组件，设置多个值（有23个），然后保存

![image](https://user-images.githubusercontent.com/38676947/182787347-5bc2681e-6efc-4dce-b736-1a4351146f4b.png)

2.打开仪表板，页面出现长时间加载及提示错误
![image](https://user-images.githubusercontent.com/38676947/182787546-a4a306f3-de3f-4524-bb7a-766f3c14557b.png)

3.选择文件下拉无显示添加的值（设置失效，不起作用）
![image](https://user-images.githubusercontent.com/38676947/182787933-b2ede8d1-fa1f-4759-8b0c-cb0a68b2c5d9.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，方便问一下这23个字段数据中最对的一个数据量是多少？

**Comment by geyesheng** [comment]
> 感谢反馈，方便问一下这23个字段数据中最对的一个数据量是多少？

方便的话，加微信聊，github描述不清楚

**Comment by BBchicken-9527** [comment]
好的，你在那个群叫什么名字我加一下你

**Comment by geyesheng** [comment]
> 好的，你在那个群叫什么名字我加一下你
DataEase交流群5  予美花下

**Comment by BBchicken-9527** [comment]
好嘞，已经加你了
