### ISSUE TITLE
[Feature]时间组件的默认时间格式可以优化下

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2793]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/48945409/182794439-763724da-21e9-4c78-9a8a-03c646b8c82e.png)
可以调整为：xxxx年xx月xx日 或 xxxx-xx-xx，目前中文加上短横线的间隔符不太标准。

当想重新选一个其它的时间格式时是正确的，不会有默认的那种格式。
![image](https://user-images.githubusercontent.com/48945409/182794811-f799f05c-7cb1-4a8c-9b2b-65d310387a64.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们调整一下。

**Comment by xuwei-fit2cloud** [comment]
v1.14.0版本已解决，请升级到最新版本。
