### ISSUE TITLE
[Question] missing V1.14 artifacts in Maven Repo

### ISSUE THREAD

**Issue by alifzl** [dataease/dataease#2803]
Hello Team,

sorry I'm a noob in maven, but I'm facing this error in compiling V1.14 backend.
I assume some of V1.14 artifacts are not yet uploaded into Maven repository. besides I compiled the The latest extensions project beforehand. kindly please advise.

``` INFO] Scanning for projects... [INFO] [INFO] ------------------------< io.dataease:backend >------------------------- [INFO] Building backend 1.14.0 [INFO] --------------------------------[ jar ]--------------------------------- Downloading from pentaho-public: https://nexus.pentaho.org/content/groups/omni/io/dataease/dataease- plugin-interface/1.14.0/dataease-plugin-interface-1.14.0.pom [WARNING] The POM for io.dataease:dataease-plugin-interface:jar:1.14.0 is missing, no dependency inf Ormation available Downloading from pentaho-public: https://nexus.pentaho.org/content/groups/omni/io/dataease/dataease- plugin-view/1.14.0/dataease-plugin-view-1.14.0.pom [WARNING] The POM for io.dataease:dataease-plugin-view:jar:1.14.0 is missing, no dependency informat ion available Downloading from pentaho-public: https://nexus.pentaho.org/content/groups/omni/io/dataease/dataease- plugin-datasource/1.14.0/dataease-plugin-datasource-1.14.0.pom [WARNING] The POM for io.dataease:dataease-plugin-datasource:jar:1.14.0 is missing, no dependency in formation available [WARNING] The artifact xerces:xerces:jar:2.0.2 has been relocated to xerces:xercesImpl:jar:2.0.2 Downloading from pentaho-public: https://nexus.pentaho.org/content/groups/omni/io/dataease/dataease- plugin-interface/1.14.0/dataease-plugin-interface-1.14.0.jar Downloading from pentaho-public: https://nexus.pentaho.org/content/groups/omni/io/dataease/dataease- plugin-datasource/1.14.0/dataease-plugin-datasource-1.14.0.jar Downloading from pentaho-public: https://nexus.pentaho.org/content/groups/omni/io/dataease/dataease- plugin-view/1.14.0/dataease-plugin-view-1.14.0.jar [INFO] ------------------------------------------------------------------------ [INFO] BUILD FAILURE [INFO] ------------------------------------------------------------------------ [INFO] Total time: 3.831 s [INFO] Finished at: 2022-08-05T04:47:10Z [INFO] ------------------------------------------------------------------------ [ERROR] Failed to execute goal on project backend: Could not resolve dependencies for project io.dat aease:backend:jar:1.14.0: The following artifacts could not be resolved: io.dataease:dataease-plugin -interface:jar:1.14.0, io.dataease:dataease-plugin-view:jar:1.14.0, io.dataease:dataease-plugin-data source:jar:1.14.0: Could not find artifact io.dataease:dataease-plugin-interface:jar:1.14.0 in penta ho-public (https://nexus.pentaho.org/content/groups/omni) -> [Help 1]  ```

**Comment by alifzl** [comment]
sorry for spamming, the issue has been resolved.
I've should use the [dataease-extension-sdk](https://github.com/dataease/dataease-extension-sdk) firstly for compiling the artifacts. issue is resolved.

**Comment by nigel001** [comment]
1.15.0对应的包也没在maven上面
