### ISSUE TITLE
[Bug] Antv的矩形树图默认展示的值而不是维度名

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2804]
**DataEase 版本**
1.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.拖入矩形树图，展示如下
![image](https://user-images.githubusercontent.com/82353425/183011454-da5889d6-7fd9-4592-aebb-8bcd0e585299.png)

2.在1.12版本中，标签是可以展示维度名的，而不是指标值。
3.能不能改回来嘞，或者支持标签丰富化

**Comment by BBchicken-9527** [comment]
感谢反馈，嗯.... 这不是维度的显示不是图例的作用吗，丰富标签的话我记录一下，内部讨论看看
