### ISSUE TITLE
[Bug] 【视图】AntV 堆叠柱状图及横向堆叠图，提示内容不显示指标值。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2809]
**DataEase 版本**
v1.13.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 版本 101.0.4951.54（正式版本） （64 位）

**Bug 描述**
【视图】AntV 堆叠柱状图及横向堆叠图，提示内容不显示指标值。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/30063018/183350070-4a5d9325-4f79-4aef-af50-202a32ddbef1.png)
![image](https://user-images.githubusercontent.com/30063018/183350097-ca30db0e-37a2-4daa-a798-63deb839a2a1.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，受累看一下你的样式中提示这一块儿

**Comment by xuwei-fit2cloud** [comment]
样式中文字颜色导致，此问题关闭。
