### ISSUE TITLE
[Feature]建议替换插件管理的图标，含义不明确

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2810]
**请描述您的需求或者改进建议.**
如题，当收起导航栏时会更明显，插件管理的图标与用户管理是同一个，图标所指含义不明确。
![image](https://user-images.githubusercontent.com/48945409/183359877-3bfe597f-ca8d-4756-bbb5-b132a2e3a3ba.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.14.0版本已解决，请升级到最新版本。
