### ISSUE TITLE
[Bug] 视图明细 报表导出Excel后，数字控件都显示成了文本 应该是数字才对

### ISSUE THREAD

**Issue by yhy729** [dataease/dataease#2811]
**DataEase 版本** 
v1.12.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 版本 104.0.5112.79（正式版本） （64 位）

**Bug 描述**
视图明细 报表导出Excel后，数字控件都显示成了文本 无法试用Excel自动的合计等功能 详情见截图

**Bug 重现步骤(有截图更好)**
1.
![c6e7205d7436211a69473120aea45dc](https://user-images.githubusercontent.com/16042766/183371656-12d9f3f9-2ac5-4c71-b6eb-96d571ede382.jpg)

2.
![ae1981127b5ac4a43b7a60eae6a4ab2](https://user-images.githubusercontent.com/16042766/183371819-d6f8ea67-9404-4eea-b0d5-c6f29e7c3dfc.jpg)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这部分我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.14.0版本已解决，请升级到最新版本。
