### ISSUE TITLE
[Feature] 针对明细表 在实际使用中 的几点建议

### ISSUE THREAD

**Issue by yhy729** [dataease/dataease#2813]
**请描述您的需求或者改进建议.**
1、目前没发现能争对列进行合计显示的功能，在做一些报表时对一些数值的合显示是很有价值的，如仓储中库存数量的合计
2、用户为了方便输入查询条件一般会从表格中直接复制数据后进行相关查询，目前明细表好像没法复制单元格内容
详情见下方截图，谢谢，祝好！
![c0fb9065e0e7aa6fcdc89779dd5a28a](https://user-images.githubusercontent.com/16042766/183377412-1c1e496f-3fda-4ab6-976b-744afc92835e.jpg)

**Comment by xuwei-fit2cloud** [comment]
1. 目前在AntV图库里的透视表是可以设置小计和总计的，但还无法针对指定的字段进行单独统计
2. 复制功能也是类似的，我们用的图库没有提供复制的接口，需要我们自己实现，我们希望在表格相关功能稳定下来后我们再来修改它，加上一些补充功能

**Comment by yhy729** [comment]
好的，谢谢！希望后面能把这些功能进加进来

**Comment by yayanpei** [comment]
感谢您的关注和支持，我们会持续不断的改进和优化产品。
