### ISSUE TITLE
[Feature]能否开源dockerfile中的base镜像的构建文件？

### ISSUE THREAD

**Issue by hellozhaoxudong** [dataease/dataease#2814]
请问能够开源dockerfile中的base镜像的dockfile？registry.cn-qingdao.aliyuncs.com/dataease/fabric8-java-alpine-openjdk8-jre:edge-chromium

**Comment by xuwei-fit2cloud** [comment]
你好，我们的Dockerfile中带有DataEase license的验证器，一般正常情况下，用任意带JDK8的镜像就可以的，和源码运行一样，不需要验证器。如果有license的话，请联系我们。
