### ISSUE TITLE
[Bug]选项卡点击新增tab后无反应

### ISSUE THREAD

**Issue by yffwawa** [dataease/dataease#2815]
**DataEase 版本**
1.12

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome

**Bug 描述**
新建仪表盘 添加选项卡 点击新增tab后无反应

**Bug 重现步骤(有截图更好)**
<img width="455" alt="image" src="https://user-images.githubusercontent.com/109802232/183578522-ffcc417d-39e1-454b-841e-6116eb1e850f.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前环境中没有发现你说的情况，或许你可以升级后尝试一下，并且13版本增加了很多实用的新功能也可以体验

**Comment by xuwei-fit2cloud** [comment]
tab组件的部分代码没有合并到主工程中，在下个版本中我们会合并进去，请关注1.14版本

**Comment by xuwei-fit2cloud** [comment]
v1.14.0版本已将选项卡组件代码合并到主工程，请更新相关代码。
