### ISSUE TITLE
[Question]可以上传pdf文件进行文件列表展示可以管理吗

### ISSUE THREAD

**Issue by yffwawa** [dataease/dataease#2817]
**请描述您的问题.**
如标题所示，谢谢

**Comment by xuwei-fit2cloud** [comment]
你好，不好意思，没看太明白问题的意思。麻烦具体描述一下使用场景或者需求。

**Comment by yffwawa** [comment]
嗯嗯 就是仪表盘中 是否支持本地上传多个pdf文件 并进行文件列表的展示和管理（删除、排序等）呢

**Comment by xuwei-fit2cloud** [comment]
这个是不支持的哈，这个需求和数据可视化不是太贴合，我们在近期的版本也还没有相关计划。
