### ISSUE TITLE
[Bug]深色主题下“收起导航”菜单颜色未适配

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2823]
**DataEase 版本**
v1.13.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 104

**Bug 描述**
![image](https://user-images.githubusercontent.com/48945409/183837538-4ee91a55-d63b-4cc5-aff2-000fcb4f9814.png)

**Bug 重现步骤(有截图更好)**
主题设置选择深色主题并应用，【收起导航】的菜单仍然为浅色，未适配。
![image](https://user-images.githubusercontent.com/48945409/183837739-462a6e42-0068-4042-a7b6-cfd8fbda01ea.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，目前正在处理

**Comment by xuwei-fit2cloud** [comment]
v1.14.0版本已解决，请升级到最新版本。
