### ISSUE TITLE
[Bug] 视图计算 字段 过滤筛选 无效 

### ISSUE THREAD

**Issue by ChewJ404** [dataease/dataease#2824]
**DataEase 版本**
版本号 :  1.13.0

**运行方式(安装包运行 or 源码运行 ?)**
k8s

**浏览器版本**
chrome 版本 104.0.5112.80（正式版本） （64 位）

**Bug 描述**

-  视图 如果 用  视图字段管理 里面 计算的 字段 做  指标  ，这时候 用 过滤 过滤组件  进行范围查找 无效
-  如果是 数据集内的 计算字段  点击过滤组件的 查询  是 有效的
-  下方截图 一个 用的 是 视图计算 字段 ，一个 用的是 数据集  计算 字段 ，一个筛选有效 一个无效

**Bug 重现步骤(有截图更好)**
1.  
![image](https://user-images.githubusercontent.com/10162958/183874469-4493b416-0e86-4d7c-a656-31a787815902.png)

2. 
![image](https://user-images.githubusercontent.com/10162958/183874719-fcb355cf-1258-4cd9-ad00-8cb4654cd754.png)

3.
![image](https://user-images.githubusercontent.com/10162958/183875023-09d89d31-1437-4726-9a85-eb3081b16c42.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前视图计算字段是不支持过滤钻取等操作的，后续版本中我们会逐步完善此处的功能
