### ISSUE TITLE
[Question]仪表盘 可以对视图的查询结果做数据去重吗

### ISSUE THREAD

**Issue by yffwawa** [dataease/dataease#2832]
**请描述您的问题.**
仪表盘 可以对视图的查询结果做数据去重吗
<img width="514" alt="image" src="https://user-images.githubusercontent.com/109802232/184083326-9b07bd48-cbf7-41db-9b3b-12872fe9f4f0.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前明细表是不支持去重处理的，可以尝试使用AntV的汇总表
