### ISSUE TITLE
[Bug]如果字段过滤后无数据，增加的计算字段出现NaN异常

### ISSUE THREAD

**Issue by jetyou** [dataease/dataease#2835]
**DataEase 版本**
version 21.9.4.35 (official build)

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
'FUNCTION toDecimal64(avg(toInt64(divide(if(equals(flow_status, '30'), 1, 0), 1))) :: 0, 2 :: 1) -> toDecimal64(avg(toInt64(divide(if(equals(flow_status, '30'), 1, 0), 1))), 2) Decimal(18, 2) : 2'

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，如果方便的话可以给我截个图吗，目前知道的信息量比较小，最好是有截图之类的信息辅助
