### ISSUE TITLE
[BUG] https域名移动端无法打开看板

### ISSUE THREAD

**Issue by qdsang** [dataease/dataease#2839]
https://github.com/dataease/dataease/blob/eac8997d8e86910dbf338701ee7833ed29f7a732/backend/src/main/java/io/dataease/controller/IndexController.java#L86
写法未考虑https情况，导致302到http，浏览器拦截报错无法打开iframe页面
was loaded over HTTPS, but requested an insecure frame 'xxx'. This request has been blocked; the content must be served over HTTPS.

解决方案：
Https被sendRedirect到Http https://blog.csdn.net/successli1994/article/details/82658176

**Comment by qdsang** [comment]
@fit2cloud-chenyw

**Comment by BBchicken-9527** [comment]
感谢反馈，有没有一种可能是nginx配置问题导致的，https://dataease.io/docs/dev_manual/dev_deployment/?h=nginx#2nginx你可以参考这个文档看一下

**Comment by brizer** [comment]
这个还是得从逻辑上面解决，有的用的不是nginx，比如用istio，同端口设置不允许等限制。  所以还是最好从代码逻辑层处理一下，谢谢。

**Comment by brizer** [comment]
这个还是得从逻辑上面解决，有的用的不是nginx，比如用istio，同端口设置不允许等限制。  所以还是最好从代码逻辑层处理一下，谢谢。

**Comment by qdsang** [comment]
https://github.com/dataease/dataease/issues/5893#issuecomment-1677014211

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_redirect http:// $scheme://;

解决
