### ISSUE TITLE
[Bug]选项卡中不能添加选项

### ISSUE THREAD

**Issue by yokebtc** [dataease/dataease#2843]
**DataEase 版本**
1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 103.0.5060.134

**Bug 描述**
编辑-》其它=》选项卡显示有问题

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/43801754/184812829-2c987592-58d8-4b3a-8d93-972c12473ad5.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们修复一下

**Comment by xuwei-fit2cloud** [comment]
选项卡的代码因为单独做了优化，没有合并到主工程中，下个版本会合并进来。

**Comment by BBchicken-9527** [comment]
问题已修复，可等待下个版本后更新体验

**Comment by xuwei-fit2cloud** [comment]
v1.14版本已将选项卡代码并入主工程，请更新相关代码。
