### ISSUE TITLE
[Bug]API数据源数据结构不含暂时为空的字段，且API数据集同步字段受限

### ISSUE THREAD

**Issue by IsSeptember** [dataease/dataease#2845]
**DataEase 版本**
v1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 104.0.5112.79（正式版本） (x86_64)

**Bug 重现步骤(有截图更好)**
API数据源-添加数据表，”连接API“后点击下一步进入”提取数据“，数据结构中不含字段值为空的字段
如下图，使用接口工具请求返回的result里有attachmentId，值为空
平台的数据结构不含该字段
![image](https://user-images.githubusercontent.com/54738906/184828946-6af4b773-2c73-426f-91db-62865937e1af.png)
![image](https://user-images.githubusercontent.com/54738906/184829856-3008ca0d-527c-473f-a342-5e0ae0e71976.png)
![image](https://user-images.githubusercontent.com/54738906/184830160-a6ff3e4a-23d7-40c5-aed8-8466fedfc5db.png)

**影响**
后续该字段有值时，如果需要使用它，需要编辑数据源 -> 同步数据集的字段 -> 数据集更新设置里同步数据。非常不方便
另外，如果我的接口有新的字段返回，API数据集的同步字段功能并不能同步出新的字段（旧版本是可以的），也需要进行如上操作才能使用

**Comment by BBchicken-9527** [comment]
感谢反馈，我们后续修复一下

**Comment by xuwei-fit2cloud** [comment]
v1.14.0版本已解决，请升级到最新版本。
