### ISSUE TITLE
[Bug]AntV明细表分页时单元格跳转功能不健全

### ISSUE THREAD

**Issue by IsSeptember** [dataease/dataease#2846]
**DataEase 版本**
v1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 104.0.5112.79（正式版本） (x86_64)

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1. 对AntV明细表视图设置为attachmentId列可跳转至外部链接
2. 使用时，第1页跳转功能正常，第2页及后续页的空值单元格可跳转，有值单元格无法跳转
将视图设置为不翻页，则不会有该现象
![image](https://user-images.githubusercontent.com/54738906/184832793-33d59218-49ef-4681-bb6a-dcfbc509e9e9.png)
![image](https://user-images.githubusercontent.com/54738906/184833455-bd508ee7-5ab4-4e0a-80db-5c992bed928d.png)
![image](https://user-images.githubusercontent.com/54738906/184833599-2cd02255-fe02-44a5-aa42-ea325b8dc6ae.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
问题已修复，将会在下个版本上线，到时可以升级体验

**Comment by xuwei-fit2cloud** [comment]
v1.14.0版本已解决，请升级到最新版本。
