### ISSUE TITLE
[Bug]AntV明细表非设置列且值为空的单元格也可跳转

### ISSUE THREAD

**Issue by IsSeptember** [dataease/dataease#2847]
**DataEase 版本**
v1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 104.0.5112.79（正式版本） (x86_64)

**Bug 描述**
AntV明细表视图进行跳转设置，非设置列且值为空的单元格也可跳转

**Bug 重现步骤(有截图更好)**
1. 如下，只设置了attachmentId列可跳转
2. 使用时，不是attachmentId列，且单元格值为空可跳转，跳转地址同设置的一致
![image](https://user-images.githubusercontent.com/54738906/184839188-3ffcab35-5e63-4556-b25b-34a4348ebefb.png)
![image](https://user-images.githubusercontent.com/54738906/184839475-448933fb-0ca4-45b4-acd0-3aee80329960.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，这个问题应该和你上一个问题是有关联性的。我们会尽快解决
