### ISSUE TITLE
[Feature]建议移动端布局下不直接使用 PC 端的背景图

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2849]
**请描述您的需求或者改进建议.**
在 PC 端上传了自己的背景图，一般情况其布局或者图案在移动端下展示是不合适的，此时该仪表板便无法进一步制作移动端。因为背景很奇怪。
例如如下仪表板：
![image](https://user-images.githubusercontent.com/48945409/184849486-7f3cee53-d94c-44ad-b679-2ff1c1dfbc9f.png)
![image](https://user-images.githubusercontent.com/48945409/184849577-0018f5ea-279b-4af6-83f7-936aaf441910.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们考虑一下移动端单独设置。
