### ISSUE TITLE
[Feature]建议数值区间组件标题文字位于左中时与输入框中间对齐

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2851]
**请描述您的需求或者改进建议.**
数值区间组件的标题位于左侧中间时却并未与输入框中部位置对齐，而是偏下的。
![image](https://user-images.githubusercontent.com/48945409/184850949-41e7073e-44a6-4c89-aad9-ee7a1a4279b3.png)

正常对齐的组件是这样的。
![image](https://user-images.githubusercontent.com/48945409/184851012-9438c834-4006-44d0-a5da-72d8587e7a38.png)

根本原因应该是数值区间组件的最小高度问题，当组件略大于输入框时，右侧仍然会出现滚动条。
![image](https://user-images.githubusercontent.com/48945409/184851371-ab2ea05d-16e7-4ae6-85f8-f0e6ebe52488.png)

当增加至以下高度时，滚动条才会消失，而标题文字是基于该高度居中的。
![image](https://user-images.githubusercontent.com/48945409/184851595-261e79e4-9326-4260-9d79-317941104af0.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下。

**Comment by xuwei-fit2cloud** [comment]
v1.14.0版本已解决，请升级到最新版本。
