### ISSUE TITLE
[Feature]建议表格数据设置阈值的情况下未设置背景颜色则跟随表格本身的颜色

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2852]
**请描述您的需求或者改进建议.**
1.当我为该表格设置了阈值，只需要改变文字的颜色，所以背景颜色清除掉了为空。
![image](https://user-images.githubusercontent.com/48945409/184858159-8347df83-6d5b-4a21-972f-584374cbe71e.png)

2.符合阈值的格子背景色则去掉了表格本身背景的颜色，透出了仪表板本身的背景色。
![image](https://user-images.githubusercontent.com/48945409/184858376-4ce5d3cc-45a9-4fcc-b3e8-20f591bdaed8.png)

综上：这里的逻辑是否应该是：如果我需要另一个跟随阈值变化的背景色则设置一个颜色。如果不需要，未设置颜色，那么格子的颜色仍然保持原表格本身的背景色。
否则是需要用户再将表格的背景色拷贝进阈值的背景色才行。
![image](https://user-images.githubusercontent.com/48945409/184859128-4fce6a35-0067-4b9b-a143-ca1714d2bef4.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们后续版本优化一下。
