### ISSUE TITLE
[Bug]添加Sql数据集，当sql语句嵌套查询时，参数设置未生效

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#2853]
**DataEase 版本**
V1.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 104.0.5112.79（正式版本） (arm64)

**Bug 描述**
添加Sql数据集，当sql语句嵌套查询时，预览有数据，点击确认保存后，数据预览页面没有数据，且仪表板视图中使用此数据集也没有数据

**Bug 重现步骤(有截图更好)**
1.添加sql数据集，其中参数设置在嵌套查询中
sql语句：SELECT b.* from (SELECT * FROM user WHERE name='${name}') b

2.点击参数设置，设置参数值
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/89771514/184858793-e784b801-02e8-49b6-9090-9c294b10e0e8.png">

3.点击预览，可以看到数据，但是点击确认后，数据预览页面没有数据，且仪表板视图中使用此数据集，设置文本搜索组件也没有数据
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/89771514/184858872-f85d423e-1156-4889-bfce-6df5a871fa03.png">

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/89771514/184861852-98317a40-9b76-458f-8bde-55c82ebe4b05.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个是已知问题，目前还没有支持。我们会在后续的版本中增加对它的支持。

**Comment by xuwei-fit2cloud** [comment]
v1.14.0版本已解决，请升级到最新版本。
