### ISSUE TITLE
[Bug]堆积柱状图通过数据格式设置不生效

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#2856]
**DataEase 版本**
V1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
版本 103.0.5060.114（正式版本） (arm64)

**Bug 描述**
堆积柱状图通过数据格式设置数据单位为万，数据标签显示内容未生效

**Bug 重现步骤(有截图更好)**

<img width="994" alt="image" src="https://user-images.githubusercontent.com/60059766/185031280-64dec388-8145-44af-8ab0-332e03229664.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，本地环境没有发现这种情况，清一下缓存看看呢？
