### ISSUE TITLE
我们如何添加另一个国家的地图？

### ISSUE THREAD

**Issue by hamidreza07** [dataease/dataease#2858]
我想添加另一个国家的地图。 我正在寻找解决方案，我找到了这个网站：http://datav.aliyun.com/tools/atlas 但这仅适用于中国地图，我想添加另一个国家的地图，如德国。 如果这个问题有其他解决方案，我非常感谢您提出来。

**Comment by BBchicken-9527** [comment]
感谢反馈，可以讲地理位置的文件通过系统设置-系统参数-地图设置上传到de，可以参考：https://img.hcharts.cn/mapdata/

**Comment by hamidreza07** [comment]
我非常感谢您抽出时间并在短时间内回复我的问题。
