### ISSUE TITLE
[Bug]批量设置指标卡名称加粗不生效

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#2861]
**DataEase 版本**
1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
版本 103.0.5060.114（正式版本） (arm64)

**Bug 描述**
通过批量设置指标卡的名称样式，设置加粗样式后不生效。

**Bug 重现步骤(有截图更好)**

![image](https://user-images.githubusercontent.com/60059766/185047911-cc47a01e-9a45-4949-9c1e-73b81709d631.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，我们会尽快修复
