### ISSUE TITLE
[Feature]建议能够支持标题和图表之间的距离设置

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#2862]
**请描述您的需求或者改进建议.**
建议能够支持标题和图表之间的距离设置；
或者默认图表和标题之间的距离比较合适，当前的距离有点略显紧凑。
![image](https://user-images.githubusercontent.com/60059766/185048672-6ef55806-d89e-4b9c-894f-b891291662aa.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，视图样式方面有很多设置项，我们会记录下来，集中讨论一下对哪些设置项进行支持。
