### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#2865]
**DataEase 版本**
v1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

chrome 104.0.5112.79
**Bug 描述**
excel数据导入，重复列名下值覆盖

**Bug 重现步骤(有截图更好)**
<img width="887" alt="image" src="https://user-images.githubusercontent.com/45852479/185075400-e842bcf6-1587-45f8-969f-46a18432c948.png">

![image](https://user-images.githubusercontent.com/45852479/185075372-32d8f17a-9ce6-4465-a1eb-638dbbdc47b7.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你是追加还是替换？使用的上传方式。

**Comment by MaekBlack** [comment]
这个我知道，我的问题是在于导入后的数据预览和源数据不匹配了。（我做的是excel数据集的添加，后续我这边也尝试了“替换”操作，得到的预览也是如此）

**Comment by BBchicken-9527** [comment]
嗯 ，明白的，我们想办法优化一下，感谢反馈
