### ISSUE TITLE
[Bug]AntV 图库透视表背景颜色

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#2868]
**DataEase 版本**
v1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge
版本 104.0.1293.54 (正式版本) (64 位)

**Bug 描述**
Antv 透视表调整表格背景颜色后，表格行没有全部改变颜色，只改变一部分。

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/96223591/185095076-1a0b9bde-49aa-434d-bcd3-6dc95b3a00b0.png)

2.
![image](https://user-images.githubusercontent.com/96223591/185095106-c2554dec-9c25-4764-860a-def9c4e7c0fc.png)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，我们目前正在考虑解决的方案
