### ISSUE TITLE
明细表支持多维度统计数据

### ISSUE THREAD

**Issue by YLBYR007** [dataease/dataease#2869]
**请描述您的需求或者改进建议.**
1.在明细表视图内，增加多维度数据统计功能。
比如我前面三列数据是按日进行展示明细，第四列数据按月将前面的日数据汇总。

**Comment by xuwei-fit2cloud** [comment]
汇总方式的话，我们在后续版本会加上最大、最小、平均值等，其它自定义的方案目前还没有计划。当前版本里可以试试看用计算字段的方式。
