### ISSUE TITLE
公共链接创建，域名为localhost，无法通过其他设备访问[Bug]

### ISSUE THREAD

**Issue by wakakaaaa** [dataease/dataease#2876]
**DataEase 版本** V1.13.0 及V1.13.1 均出现此BUG

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
google浏览器104.0.5112.81

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/51689037/185338468-5e056118-9ac2-4bd3-86a4-d757a22140ee.png)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，这个可能是部署的问题，https://dataease.io/docs/installation/online_installation/，看一下配置文件

**Comment by wakakaaaa** [comment]
是在windows系统上安装了子系统，然后出现这个问题的，把localhost替换为本机IP地址就好了
