### ISSUE TITLE
[Bug] 瀑布图，在维度为时间格式的情况下，维度显示不全且不显示总计

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2881]
**DataEase 版本**
v1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 104.0.5112.101（正式版本） (arm64)

**Bug 描述**
瀑布图，在维度为时间格式的情况下，维度显示不全且不显示总计

**Bug 重现步骤(有截图更好)**
1. 数据集使用的官方示例里的数据集。
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/30063018/185822886-8335aa08-6869-42d2-b8ba-ff9c12688934.png">
2.创建瀑布图，横轴显示不全，总计无显示
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/30063018/185823004-cd112020-f2f4-4c7c-aef5-d1033e82c6fd.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快处理

**Comment by xuwei-fit2cloud** [comment]
v1.14.0版本已解决，请升级到最新版本。
