### ISSUE TITLE
[Feature]视图标签显示望增加“千分位”显示设置

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2884]
**请描述您的需求或者改进建议.**
标签数值显示增加“千分位”显示设置。

**Comment by xuwei-fit2cloud** [comment]
v1.13版本开始对AntV中大部分视图类型均支持设置数值格式，标签和提示的显示格式可以在下图所示的位置设置。
![图片](https://user-images.githubusercontent.com/1892127/185864618-b87a2f4c-985c-40fa-a025-37f43ce93642.png)

**Comment by AndroidBaby1** [comment]
好的，谢谢。
