### ISSUE TITLE
[Feature]报表组件穿透查询能支持到以行为过滤条件设置关联性

### ISSUE THREAD

**Issue by sanlywork** [dataease/dataease#2885]
报表的跳转,例如从主到明细,目前只能设置单列关联,即数据行的某一列匹配子报表的某一列.目前是无法支持到点主报表的某一列时候,用这一行的多列,匹配到子报表的多列.实际中有多对多的穿透关联设置的.
[问题如图](https://github.com/sanlywork/temp/blob/main/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20220822114436.png)

**Comment by yayanpei** [comment]
感谢您的反馈，我们需要讨论一下。
