### ISSUE TITLE
[Feature]【数据集】API 数据源配置未录入名称点击下一步提醒一下“未录入名称”

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2891]
**请描述您的需求或者改进建议.**
【数据集】API 数据源配置未录入名称点击下一步提醒一下“未录入名称”。
![image](https://user-images.githubusercontent.com/24768910/185853183-8978dd84-a1da-487b-ad22-c1dd3c29094a.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们在下个版本优化一下。

**Comment by AndroidBaby1** [comment]
好的，谢谢。
