### ISSUE TITLE
[Bug] 小数刻度相关视图展示错误

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#2893]
DataEase 版本
v1.13.1

运行方式(安装包运行 or 源码运行 ?)
安装包

浏览器版本
chrome 104.0.5112.79

**Bug 描述**
小数刻度相关视图展示错误

**Bug 重现步骤(有截图更好)**
如图 
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/45852479/185873087-f06bf5b5-3630-4acd-a697-a7eba041af7a.png">
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/45852479/185873116-35fa5e47-1899-4d90-af4d-05af6d5737cc.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这是一个已知问题。
我们在考虑通过轴值格式化或数值格式化的方式处理。
