### ISSUE TITLE
[Bug] 新版本数据集管理模块依旧可以创建自定义数据集

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#2894]
DataEase 版本
v1.13.1

运行方式(安装包运行 or 源码运行 ?)
安装包 最新安装包安装，非老版本升级

浏览器版本
chrome 104.0.5112.79

**Bug 描述**
 新版本数据集管理模块依旧可以创建自定义数据集

**Bug 重现步骤(有截图更好)**
如图
<img width="494" alt="image" src="https://user-images.githubusercontent.com/45852479/185874401-067429e1-b690-4e75-bd76-c063e73baf1f.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，但我们最新测试的结果并没有复现上面的问题。如果方便的话，可以通过社区群找我们的同事帮忙排查。
