### ISSUE TITLE
[Bug] 创建自定义数据集选择excel数据集保存报错

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#2895]
DataEase 版本
v1.13.1

运行方式(安装包运行 or 源码运行 ?)
安装包 最新安装包安装，非老版本升级

浏览器版本
chrome 104.0.5112.79

**Bug 描述**
创建自定义数据集选择excel保存报错

**Bug 重现步骤(有截图更好)**
<img width="914" alt="image" src="https://user-images.githubusercontent.com/45852479/185878828-1ca0714e-3df5-41e6-afc2-ec6532e53ece.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈。新安装的v1.13.1版本的DataEase，默认应该不会再出现自定义数据集。
如果需要做多表的关联，可以用SQL数据集，或者关联数据集。
