### ISSUE TITLE
[Bug]兼容问题

### ISSUE THREAD

**Issue by want2gohome** [dataease/dataease#2897]
**DataEase 版本**
1.13.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
微信\企业微信

**Bug 描述**
问题1、nginx 配置用户认证（htpasswd）后，在微信和企业微信PC端，访问页面不会弹出认证的弹框；

**Bug 重现步骤(有截图更好)**
1.nginx配置用户认证；设置访问账号和密码；
2.分享仪表板链接到微信；
3.打开链接，在微信和企业微信PC端，不会弹出认证框，直接显示401 Authorization Required。（浏览器和企业微信手机端可以正常弹出认证框，只有输入错误账号密码才会401）

![3771cfbe06aee96173b3aab5939b016](https://user-images.githubusercontent.com/109954263/185888302-ed7ff3b3-7234-4829-b4ad-5e75d5a4f543.jpg)

问题2、分享仪表板在企业微信打开后，页面显示兼容存在问题，表格内容外的是黑色的，微信、浏览器、企业微信PC端正常，只有企业微信有此问题。

**Bug 重现步骤(有截图更好)**
AntV透视表，
![image](https://user-images.githubusercontent.com/109954263/185889569-82166717-37f6-42c0-b2f9-45f20495e074.png)

![3f2ea3665e9a09a37044b08e09e1fff](https://user-images.githubusercontent.com/109954263/185889301-15d59bba-93d0-4bb8-bacc-468972e81b39.jpg)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈。

问题1：
nginx配置的认证，因为没有自己的认证页面，在微信和企业微信PC端，不会弹出认证框，这个是在nginx侧出现的，还没有到DataEase这边。
DataEase中原本就有用户认证环节，有自己的登录页面，即使在微信和企业微信的浏览器中，也不会被拦截。

问题2：
确实是有这个问题，我们尽力修复。
