### ISSUE TITLE
手动点关闭报错信息的小×无效

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#29]
报错信息左侧的关闭小×手动点击无效，错误信息未被实时关闭。
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/48945409/123395956-596c0800-d5d3-11eb-9c66-a19dc7adef8f.png">

**Comment by fit2cloud-chenyw** [comment]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/67260074/123397218-c03df100-d5d4-11eb-8c4f-7a1c61a041ad.png">
左侧只是错误标识 右侧的x才是关闭按钮

**Comment by luyang351** [comment]
那可能建议样式上做下调整，右边的和左边比起来太不起眼了，容易造成误解。

**Comment by xuwei-fit2cloud** [comment]
我们调整一下错误信息展示
