### ISSUE TITLE
[Feature]【数据集】API 数据集录入框固定

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2902]
**请描述您的需求或者改进建议.**
目前 API 接口的这个框框，一点其他位置就缩回去，数据都不保存，需要可以改善这一点。
![wecom-temp-36366-6c667918b5d36d78abf9bc9a93e7debe](https://user-images.githubusercontent.com/24768910/186063496-c23ea10b-428e-4c92-b186-3fdd99112394.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，下个版本会修复。

**Comment by AndroidBaby1** [comment]
好的，谢谢。
