### ISSUE TITLE
[Bug] 如果历史数据有update  那不是增量更新 那不是 会产生重复了  如何实现upsert 语义

### ISSUE THREAD

**Issue by ChewJ404** [dataease/dataease#2904]
**DataEase 版本**
版本号 :  1.13.0

**运行方式(安装包运行 or 源码运行 ?)**
k8s

**浏览器版本**
chrome 版本 104.0.5112.80（正式版本） （64 位）

**Bug 描述**

-  增量更新 设置了  条件判断 
-  这个时候如果是想 历史 数据如果更新了 则定时任务是 同步更新 而不 新增 何实现upsert 语义

**id,2,4 是更新 语句 更新了state**
**id 6 是 新增 数据**

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/10162958/186067898-624a8242-e80b-4ecc-9594-d50650085365.png)
![image](https://user-images.githubusercontent.com/10162958/186067956-c61080cf-7811-46e8-b1b5-22a705cc279f.png)

![image](https://user-images.githubusercontent.com/10162958/186068054-64dd2ed6-7bab-44b4-9c6e-fa95597d7b50.png)

**Comment by xuwei-fit2cloud** [comment]
你好，目前DataEase支持的增量更新功能会有一些限制，需要历史数据处于稳定状态，也就是历史数据不发生变动，所以目前还不能支持。
