### ISSUE TITLE
[Bug] 视图设置背景色后，点击放大查看视图后背景色丢失，且导出的图片也无背景色

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2908]
**DataEase 版本**
v1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 104.0.5112.101（正式版本） (arm64)

**Bug 描述**
视图设置背景色后，点击放大查看视图后背景色丢失，且导出的图片也无背景色

**Bug 重现步骤(有截图更好)**
1. 设置视图背景色
<img width="1396" alt="image" src="https://user-images.githubusercontent.com/30063018/186084162-af865096-d6ad-4f4b-85e6-d35242893bb4.png">
2.点击视图放大查看，发现背景色丢失
<img width="750" alt="image" src="https://user-images.githubusercontent.com/30063018/186084315-a4ad4bfd-1855-47c3-b170-36b854261376.png">
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/30063018/186084442-a2313f0c-8365-487b-999a-e61986a059ee.png">
3. 点击导出图片，导出图片的背景色也是丢失的
<img width="941" alt="image" src="https://user-images.githubusercontent.com/30063018/186084577-e91733e9-7da9-4ea7-aab6-e65298d9c5fd.png">
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/30063018/186084658-c337bca4-ae41-470d-b2b4-ea785b0c618d.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们下个版本修复一下。

**Comment by xuwei-fit2cloud** [comment]
v1.14.0版本已解决，请升级到最新版本。
