### ISSUE TITLE
[Bug]CAS 认证 重定向到cas server 的登陆页面失败

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [dataease/dataease#2909]
**DataEase 版本**
v1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌浏览器

**Bug 描述**
启用cas 认证之后，重定向到cas server 的登陆页面失败， 依旧还是de 的登陆页面

**Bug 重现步骤(有截图更好)**
1.  第一次登陆可以跳转到cas server ，登陆成功
2. 退出登陆
3. 浏览器再重新输入de 的地址访问，这时候就不会跳转到 cas server。 还是de 的登陆页面，输入账号密码登陆，重定向到cas server 的登陆页面

**Comment by ywhfzy** [comment]
10.xx.xx.236 是cas服务器
https://user-images.githubusercontent.com/82353425/186091233-0cd720dd-9428-401a-8833-822d87dd84de.mp4

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们排查一下。
