### ISSUE TITLE
[Feature]每次下载新版本都要登录，然后推销电话就打过来了

### ISSUE THREAD

**Issue by leim** [dataease/dataease#2910]
首先dataease是一个非常好的开源项目。

然后，让人不爽的是，每次下载新版本的时候，都要求登录，输入手机号和验证码，然后每次下载完，推销电话就打过来了。

已经跟推销的人员说过很多次了，不要再打电话了，结果完全没有效果，下次还打。

太讨厌了。

**Comment by ChewJ404** [comment]
这属于 半开源吧 ，git下来后 项目 都跑不起来 ，核心文件应该没开源  ，都没有 编译部署教程 ，只有一键安装之类的

**Comment by xuwei-fit2cloud** [comment]
@leim 非常感谢您对我们产品的肯定，同时也非常抱歉打搅了您的工作，我们会反馈给销售同事，避免重复联系。

**Comment by maninhill** [comment]
感谢你的反馈。对于我们做的不好的地方，我们会改进和优化。

**Comment by xuwei-fit2cloud** [comment]
@ChewJ404 DataEase可视化相关的核心功能都是开源的，下载下来后，可以参考我们官网的在线文档进行编译、安装、升级等操作。如果仍有问题，可以联系我们社区群的同事们。
我们的官网地址是： https://dataease.io/docs/

**Comment by ChewJ404** [comment]
> @ChewJ404 DataEase可视化相关的核心功能都是开源的，下载下来后，可以参考我们官网的在线文档进行编译、安装、升级等操作。如果仍有问题，可以联系我们社区群的同事们。 我们的在线文档地址是： https://dataease.io/docs/

3q  我再去试试

**Comment by wat1r** [comment]
源码安那一段，很难安装成功
