### ISSUE TITLE
[Bug] Echarts 组合图，主纵轴与副纵轴名称及标签在字号大小一致的情况下视觉存在明显偏差

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#2911]
**DataEase 版本**
v1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 104.0.5112.101（正式版本） (arm64)

**Bug 描述**
Echarts 组合图，主纵轴与副纵轴在字号大小一致的情况下视觉存在明显偏差。

**Bug 重现步骤(有截图更好)**
1. 如图所示，主纵轴及副纵轴名称及标签视觉偏差
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/30063018/186090855-e476123a-d549-4da0-bc82-13959ed650aa.png">
2. 实际配置时，所有的字号大小均一致为12，如下图所示：
<img width="373" alt="image" src="https://user-images.githubusercontent.com/30063018/186091124-9f217d60-1159-49fb-8a97-807aeccd8484.png">
<img width="370" alt="image" src="https://user-images.githubusercontent.com/30063018/186091204-c53a57d7-525b-4d33-bf60-9019b4a36a83.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们复现了此问题。在浏览器缩小的情况下，左侧的字体会变小。我们修复一下。

**Comment by xuwei-fit2cloud** [comment]
v1.14.0版本已解决，请升级到最新版本。
