### ISSUE TITLE
[Feature] 选择视图时提示该视图的数据结构模型图

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2912]
**请描述您的需求或者改进建议.**
对于一个普通用户来说，他可能不知道
普通地图或者气泡地图使用的数据集结构图是什么样子的，能不能在选择视图的时候有一个小感叹号或者其他图标提示呢？
![image](https://user-images.githubusercontent.com/82353425/186094670-7878b0b4-36ac-45a0-9fb5-8d70656de427.png)
或者能不能改成先选视图 然后再选数据集呢？

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这部分我们正在优化。我们会将您的建议考虑进去的。
