### ISSUE TITLE
[Bug]AntV横向柱状图的标题位置显示问题

### ISSUE THREAD

**Issue by want2gohome** [dataease/dataease#2913]
**DataEase 版本**
1.13.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 版本 104.0.5112.102（正式版本） （64 位）

**Bug 描述**
升级1.13.0之后，AntV的横向柱状图的标题位置显示有问题，如图：

**Bug 重现步骤(有截图更好)**
效果图：
![image](https://user-images.githubusercontent.com/109954263/186103847-dcf461c0-7b2e-4db9-9b77-8bdbd62b9526.png)

配置：
![image](https://user-images.githubusercontent.com/109954263/186102896-b0402566-8a70-4aca-bccf-3ecffd318b0a.png)

**Comment by xuwei-fit2cloud** [comment]
近期版本样式上有所调整，我们会在下个版本修复。

**Comment by xuwei-fit2cloud** [comment]
v1.14.0版本已解决，请升级到最新版本。
