### ISSUE TITLE
[Feature]【仪表板】增加一键清除无用过滤组件功能

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2915]
**请描述您的需求或者改进建议.**
时间联动控件里面的内容不会自动变，更新多了搞不清楚哪个有用哪个没用，对于界面上找不到的无效配置建议增加一键清除无用过滤组件功能。

**Comment by yayanpei** [comment]
感谢反馈，该功能已经在开发中，还请关注9.1号发布的V1.14版本。

**Comment by AndroidBaby1** [comment]
好的，谢谢。
