### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by shuiyouzhi** [dataease/dataease#2918]
**DataEase 版本**
1.13.0

**运行方式(安装包运行 or 源码运行 ?)**
源码运营

**浏览器版本**
Chrome 104.0.5112.101（正式版本） (x86_64)

**Bug 描述**
1: 
  **描述**:  _增量更新、简单重复未从Kettle中拉取数据_
  **详细说明**: 
        _数据集 -> 更新信息 -> 更新设置 -> 添加任务
        表单内容为增量更新、简单重复，如图1。保存后，存储的数据内容如图2, incremental_add字段为空。
        从Kettle中拉取数据的源码有个判断异常，导致“增量更新”时不会执行拉取数据函数，如图3_

**Bug 重现步骤(有截图更好)**
1. 
<img width="736" alt="image" src="https://user-images.githubusercontent.com/12723715/186122302-9f4816fd-0c45-4dc8-ba7e-80e6cb41bd65.png">

2.
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/12723715/186123122-9aa77c6a-e701-4200-a1c0-4f87e81c3a3a.png">

3.
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/12723715/186123727-85089c65-f58f-4ac5-bdeb-c241f3ea5dc7.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复的

**Comment by xuwei-fit2cloud** [comment]
是否在使用增量更新的时候，没有填写增量更新的SQL？如下图所示：
![图片](https://user-images.githubusercontent.com/1892127/186310958-74d8a52f-a078-4e77-8804-cf1aad38bd6d.png)

**Comment by xuwei-fit2cloud** [comment]
v1.15.0版本中优化了增量更新的使用逻辑，请更新版本。
