### ISSUE TITLE
[Bug]世界地图下拉树过滤器不生效

### ISSUE THREAD

**Issue by KanaSukita** [dataease/dataease#2922]
**DataEase 版本**
v1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 版本 104.0.5112.102（正式版本） （64 位）

**Bug 描述**
使用Impala直连的方式，在使用下拉树对字段进行过滤时不生效，但在使用文本下拉的时候是可以过滤的

**Bug 重现步骤(有截图更好)**
1. 使用Impala数据源创建一个直连模式的数据库数据集
2. 在仪表板中使用世界地图创建图表
3. 添加一个下拉树组件，选择数据集中的三个字段
4. 选择下拉树组件中的值，选中后世界地图的数据不会更新（在使用文本下拉的时候是可以过滤并更新数据的）

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们在对应的环境中没有复现此问题。
您可以在 https://dataease.fit2cloud.com 在线体验环境上验证一下，这个环境也是v1.13.1版本。

**Comment by xuwei-fit2cloud** [comment]
问题复现了，已经修复，请等待新版本发布。

**Comment by xuwei-fit2cloud** [comment]
v1.14.0版本已解决，请升级到最新版本。
