### ISSUE TITLE
[Feature]希望DataEase的第三方系统参数，可以从URL中获取变量值传递给仪表板，实现仪表板数据筛选

### ISSUE THREAD

**Issue by cnjianming** [dataease/dataease#2924]
**请描述您的需求或者改进建议.**
在业务系统与可视化系统集成的过程中，业务系统需要直接传递参数给可视化系统来展现。如业务系统中有客户列表，点击某个客户时，将客户ID传递给可视化系统，让可视化系统展示该客户的客户画像（仪表板）。目前DataEase不支持通过URL传递变量值以便进行数据筛选，无法实现上述场景。
希望DataEase的第三方系统参数，可以从URL中获取变量值传递给仪表板，实现仪表板数据筛选的功能。

**Comment by yayanpei** [comment]
感谢反馈，该功能已经实现，请参考文档：https://dataease.io/docs/user_manual/dashboard_basicfunctions/#6
