### ISSUE TITLE
[Feature]【视图】横向柱状图支持滚动效果

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2925]
**请描述您的需求或者改进建议.**
横向柱状图支持滚动效果，就是想在宽度不够的情况下滚动展示每个柱，最好是可以个性化设置第一个柱固定等个性化设置。
用户原话：
![image](https://user-images.githubusercontent.com/24768910/186320120-1797266b-effe-4d3a-9530-e96adade5a70.png)

**Comment by xuwei-fit2cloud** [comment]
需求已收到，我们内部先讨论一下需求的合理性和可行性。
