### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by stigma220140630** [dataease/dataease#2928]
**DataEase 版本**
1.13.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 104.0.1293.54(64位)

**Bug 描述**
添加Oracle数据源，选择Schema时，
报错：java.sql.SQLRecoverableException: IO Error: Connection reset by peer, connect lapse 2 ms., Authentic

**Bug 重现步骤(有截图更好)**
1.  新建数据源，选择Oracle数据源，填写数据库 用户名/密码等信息
2.  获取Schema，提示报错java.sql.SQLRecoverableException: IO Error: Connection reset by peer,
3.  已检查用户名/密码等信息无误。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们排查一下。

**Comment by BBchicken-9527** [comment]
目前没有发先你说的问题，方便问一下你使用的oracle的版本吗？

**Comment by stigma220140630** [comment]
Oracle版本是11.0.2，其他的Oracle数据库连接都正常，就这一个连接报错。




贾伟
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataease/dataease"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月1日(星期四) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataease/dataease] [Bug] (Issue #2928)





 
目前没有发先你说的问题，方便问一下你使用的oracle的版本吗？

**Comment by BBchicken-9527** [comment]
好的，我们本地环境看一下，如果存在问题我们会尽快处理

**Comment by BBchicken-9527** [comment]
你好，我本地测试使用oracle11并没有出现你说的情况，方便的话可以将后台日志给我看一下吗
