### ISSUE TITLE
[Bug]  如果服务绑定 域名 带端口的  分享链接 端口就 丢失了

### ISSUE THREAD

**Issue by ChewJ404** [dataease/dataease#2935]
**DataEase 版本**
版本号 :  1.13.0

**运行方式(安装包运行 or 源码运行 ?)**
k8s

**浏览器版本**
chrome 版本 104.0.5112.80（正式版本） （64 位）

**Bug 描述**
1. 仪表盘分享链接 
2. `http://demo.apps.dataease.com:30052/link/UXtOy5wL`
3.  会有一次重定向 重定向完了后  端口丢失
4. `http://demo.apps.dataease.com/link.html?link=h3jk9UOyPRDTEAJVTtxnr/VtN7pIOxWVmARGx3ifwccU3E9iWHMlgLsQfk9+8qpyhiaUh3ulEBnNEIcu4i45Bw==&user=VFCfODGLrELu5jcEzufHz6B/kKzPQdOh0rDMqY+uzGD7P5DcIxLIum3Y5zM9t2uJFgJx1BRwIAnKrYB7g/G0pg==`

**Bug 重现步骤(有截图更好)**

**Comment by BBchicken-9527** [comment]
感谢反馈，是否有完整的日志等信息方便我们排查一下呢？

**Comment by ChewJ404** [comment]
没有报错日志， 就是  从 分享链接 跳转的时候 从

`http://demo.apps.dataease.com:30052/link/UXtOy5wL`  

302  重定向

`Location: http://demo.apps.dataease.com/link.html?link=KZdZGUovliJOqfP5M/DCIKSYcyvUsbTJnoTTkfouGTaq/ujD3iUkUZBqJA5t/Ug5qjH3FEFWq2X6759cy4hshA==&user=eYBoSFag5g4mBT8mKFiTtL+iObaTxk87BArGwUJi4dms2hl+MoJRMqgfPke5WPyjgziD8/zaWjZhWCvlA6AQZw==`

端口丢失
![image](https://user-images.githubusercontent.com/10162958/186805129-79bdb792-3bad-4313-83a5-2c518f00239f.png)


知道原因了 ，应该是 外层 nginx   没有 往内层  X-Forwarded-For 导致 request.getServerPort()取不到 端口 就 默认设置80了
