### ISSUE TITLE
[Feature]【视图】指标卡支持在指标值左右拼接文本内容

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2938]
**请描述您的需求或者改进建议.**
指标卡支持在指标值左右拼接文本内容，类似标签设置里的这种形式【百分比 ：{b} %】

**Comment by yayanpei** [comment]
感谢反馈，指标卡是不支持拼接文本内容，下周发布的版本中新增了【富文本视图】支持，建议使用该组件。

**Comment by AndroidBaby1** [comment]
好的，谢谢。
