### ISSUE TITLE
[Feature]表格配置时支持单独设置各列的宽度

### ISSUE THREAD

**Issue by yhy729** [dataease/dataease#2948]
**请描述您的需求或者改进建议.**
当前表格设置时列宽时只能进行整体进行设置自适应或是自定义相同列宽。在实际使用场景中每列的数据宽度相差会很大，希望能支持单独对每一列宽度进行设置。
谢谢！

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。
