### ISSUE TITLE
[Feature]【数据集】API 数据集支持直连模式

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#2949]
**请描述您的需求或者改进建议.**
API 数据集支持直连模式

**Comment by yayanpei** [comment]
感谢反馈，API数据集是无法支持直连的，您这边具体的使用场景是什么，烦请描述回复描述一下。

**Comment by AndroidBaby1** [comment]
场景：不想在 DE 存取实时变化的数据，希望可以开放直连模式让用户去斟酌查询效率和实时性的优先级。

**Comment by linliqingvip** [comment]
api的数据都是变化的，没有存下来的必要，现查现用就是最常见的场景。
平常自己部门的数据用sql取，其他部门的数据通常就是提供api。这是两个刚性需求。
阿里的datav支持api，就是现查现用的，好用且合理。
因为api慢而不得不定时同步的场景，也许存在吧，但一定是低频需求。api都写不好，抓出来打一顿就好了。

另一个问题是，现在dataease要使用api，必须得有kettle和doris，不必要的代价呀，为了使用api，我非得装上，这俩占用的资源可不少
