### ISSUE TITLE
[Bug] 文本卡不支持换行

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2953]
**DataEase 版本**
1.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌标准

**Bug 重现步骤(有截图更好)**
1.选择两个视图。一个是汇总表，一个是文本卡，都是AntV类型的。
![image](https://user-images.githubusercontent.com/82353425/186815801-106e29a6-6474-4ca9-834f-9972f5e637fa.png)

2.数据库的内容是 \r\n 换行的。
![image](https://user-images.githubusercontent.com/82353425/186815983-9f5176cb-e4ad-438f-aa18-a37032fb8212.png)

3.按道理来说，文本卡应当与数据库表格式一致才对嘞。

**Comment by BBchicken-9527** [comment]
感谢反馈，文本开是不支持换行的，不过后续会新推出一个视图，可以满足你说的这个需求
