### ISSUE TITLE
[Feature] ECharts类型的视图会支持自适应列宽吗？

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2962]
**请描述您的需求或者改进建议.**

跟 AntV 一样，支持自适应列宽？
![81fca05d021dcd29b9c2f009d993831](https://user-images.githubusercontent.com/82353425/187109792-b67393cb-f7e9-4844-9cc8-5c9e0373fbf1.jpg)

**Comment by yayanpei** [comment]
感谢反馈，推荐您使用antv的表格，echarts表格近期没有规划支持自定义列宽

**Comment by ywhfzy** [comment]
> 感谢反馈，推荐您使用antv的表格，echarts表格暂时没有规划支持自定义列宽

因为 AntV 的表格视图会浏览器内存溢出。。。迫不得已才选择了 ECharts。。。

**Comment by yayanpei** [comment]
感谢反馈，请问大致多少的数据量？

**Comment by ywhfzy** [comment]
几百万-几千万

**Comment by yayanpei** [comment]
建议减少一下数据量，一方面数据量大会卡，另外表格中大数据量查看可读性不强。
