### ISSUE TITLE
[Bug]公共链接参数不生效

### ISSUE THREAD

**Issue by yffwawa** [dataease/dataease#2965]
**DataEase 版本**
1.12

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome

**Bug 描述**
仪表板设置外部参数不生效

**Bug 重现步骤(有截图更好)**
1.创建外部参数
<img width="403" alt="image" src="https://user-images.githubusercontent.com/109802232/187139385-69d98ca6-11dc-43cc-ae67-3ba04fa6350f.png">
<img width="881" alt="image" src="https://user-images.githubusercontent.com/109802232/187139435-166360eb-57f4-42f8-99ab-1943dea53b8d.png">

2.仪表板新tab打开，添加参数，不生效
链接后添加参数：preview/83f68506-2763-11ed-9c9f-c70594bec59d?fundcode=110022
<img width="632" alt="image" src="https://user-images.githubusercontent.com/109802232/187139594-324b6e83-0118-4572-bee1-2b6954cfdaa0.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，异常的日志可以看一下吗，还有提示的信息是什么呢？

**Comment by yffwawa** [comment]
看着没有异常呢，也没有信息提示，视图中显示的是全量产品信息，有个疑问，视图关联字段必须在仪表盘上有展示才可以做外部参数关联吗？

**Comment by yffwawa** [comment]
链接中的 外部参数名是attachParams= 还是我自定义的fundcode=呢

**Comment by xuwei-fit2cloud** [comment]
构建完整的 URL，在公共链接后加上 ?attachParams=加密后的字段，不是自定义的fundcode=
