### ISSUE TITLE
[Bug]已删除的视图在选项卡中还是可以获取

### ISSUE THREAD

**Issue by flashboo** [dataease/dataease#2966]
**DataEase 版本**
V1.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrom71.0

**Bug 描述**
已删除的视图在选项卡中还是可以获取

**Bug 重现步骤(有截图更好)**
1.新增两个视图【新建视图】、【新建视图1】
![image](https://user-images.githubusercontent.com/44344081/187144752-439bf62a-367f-4749-94c4-c77f012f64e2.png)
2.删除【新建视图】，并添加选项卡组件
![image](https://user-images.githubusercontent.com/44344081/187144909-a6d04cca-8e79-4bf9-8a14-15aacf07e601.png)
3.在选项卡中选择视图，发现【新建视图】依然可以被选上
![image](https://user-images.githubusercontent.com/44344081/187145088-40512181-76c5-415e-83ae-d484a752bc65.png)
![image](https://user-images.githubusercontent.com/44344081/187145131-6e05edc6-d98f-4251-8345-8a15bbc0abdc.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，这是因为你删除之后没有保存吧，如果没有保存的话系统依然记录了这个视图，所以可以选中的，保存之后绑定关系解除就选不到了的。
