### ISSUE TITLE
[Bug]仪表板复制后视图计算字段丢失

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#2972]
**DataEase 版本**
v1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 最新版

**Bug 描述**
如图一，Redmine 任务分析中的 countage 是一个视图计算字段，复制此仪表板后，countage依然存在，但编辑视图时显示为红色且在视图字段管理页面不可见。

**Bug 重现步骤(有截图更好)**
1. 原仪表板， countage 是视图计算字段
<img width="1187" alt="WeChat42823d22627bcd6f6a8abedd61de132f" src="https://user-images.githubusercontent.com/30886198/187182042-38f24272-f1ad-4a0a-8d87-20af9fb391a8.png">
2. 复制后的仪表板，coutage 显示为红色
<img width="1189" alt="WeChate4df82ccf012ec1e99fab6162007d0c2" src="https://user-images.githubusercontent.com/30886198/187181918-355ccb1b-e37b-4524-95c4-66ed0fea7d17.png">
3. 复制后的仪表板视图字段管理页面也没有 countage
<img width="1187" alt="WeChatc8a216f5d21b826d9c076f25d1f5a113" src="https://user-images.githubusercontent.com/30886198/187182067-69d7c3d2-72f6-4378-bac2-c34c8ada723a.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，确实有这个问题，我们修复一下。
