### ISSUE TITLE
[Question]组件支持 先选定字段 再进行字段值的范围筛选吗？

### ISSUE THREAD

**Issue by yffwawa** [dataease/dataease#2974]
**请描述您的问题.**
数据表字段数量多，仪表盘功能区中  需要支持先从字段列表中选定某一字段 再设置对应的字段值/范围，该怎么配置实现呢？

**Comment by yayanpei** [comment]
感谢反馈，选择视图后，可以通过设置过滤器设置对应字段的范围
<img width="200" alt="image" src="https://user-images.githubusercontent.com/84168063/187329998-d339e038-f9e8-4112-9ec4-3a01ae8c204f.png">

**Comment by yffwawa** [comment]
仪表板是分享给其他人使用的，这个过滤器能力在分享出去的仪表板里也是有的吗？

**Comment by xuwei-fit2cloud** [comment]
可以使用Mongodb-BI类型数据源来对接试试。
