### ISSUE TITLE
[Feature] 支持 LDAP 用户登录不需要判断用户类型

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#2981]
**请描述您的需求或者改进建议.**
1.首先需要测试 DataEase  的可靠性，我们会普通注册公司员工账号。
2.测试完毕之后，想再集成 LDAP 用户，这时候普通用户与LDAP 个别用户重合的了，同步的时候同样的用户名或者同样的邮箱是不会重新注册的。
3.现在用A用户的账号密码用LDAP类型登录就会报错。
<img width="915" alt="7ad89a41ec191c078b674c3104b0be1" src="https://user-images.githubusercontent.com/82353425/187345234-0100d37d-513a-4d62-8b1c-83d1269187e7.png">
4.能不能改成 隔壁 JumpServer 一样，不需要判断类型，判断账号密码邮箱等通过呢？
5.现在只能手动去更改数据库的用户类型，由普通用户的0改成LDAP的1解决。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们内部讨论一下。
