### ISSUE TITLE
[Bug] 关联数据集两个表有同名字段可以保存，数据集生成后字段管理无法区分两个

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#2991]
DataEase 版本
v1.13.1

运行方式(安装包运行 or 源码运行 ?)
安装包

浏览器版本
chrome 104.0.5112.79

**Bug 描述**
关联数据集两个表有同名字段可以保存，数据集生成后字段管理无法区分两个

**Bug 重现步骤(有截图更好)**
<img width="793" alt="image" src="https://user-images.githubusercontent.com/45852479/187386705-9a496594-43b7-4ca4-8c67-cade2c974763.png">
<img width="824" alt="image" src="https://user-images.githubusercontent.com/45852479/187386715-907a79be-3113-49a4-a7af-64ed19daf4c6.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下
