### ISSUE TITLE
[Bug]Excel 导入后数据显示异常，修改字段类型后数据显示为空

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#2994]
**DataEase 版本**
v1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 最新版

**Bug 描述**
将 Excel 导入后发现数字变成了日期，将字段格式修改为日期后预览无数据。

**Bug 重现步骤(有截图更好)**
1.导入如下 Excel 数据
姓名 | 时长
-- | --
张三| 397.62
赵四 | 395.53
王五 | 368.18
钱六 | 282.67
孙七 | 230.80
<img width="1716" alt="WeChat2de5874ac1e81066351ecd23e19e4ff0" src="https://user-images.githubusercontent.com/30886198/187394413-8010769d-614f-4c9f-aa4e-ae6e979f9fe9.png">

2.导入后预览数据显示异常
<img width="1710" alt="WeChat2eda6819f47676937edfb4ab7dc7116a" src="https://user-images.githubusercontent.com/30886198/187394369-66b0b14a-5baa-4d5f-9d5c-e9b659ec971e.png">

3.修改字段类型为小数后，数据显示为空
<img width="1697" alt="WeChat4f14f17f22a581c876e1b44aa29d987e" src="https://user-images.githubusercontent.com/30886198/187394473-ff3d59f4-5b42-434a-9d3e-84281e6c8cc8.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前时间只支持固定格式的时间，目前不支持时长的转换的

**Comment by liuboF2c** [comment]
> 感谢反馈，目前时间只支持固定格式的时间，目前不支持时长的转换的

实际上我需要的就是小数显示即可，不需要转换成时间。这里有两个问题
1、自动识别问题：表格里是数值格式，默认识别成了时间格式。
2、我在字段管理中将格式改成数字之后预览显示为空。

**Comment by liuboF2c** [comment]
> 感谢反馈，目前时间只支持固定格式的时间，目前不支持时长的转换的

实际上我需要的就是小数显示即可，不需要转换成时间。这里有两个问题
1、自动识别问题：表格里是数值格式，默认识别成了时间格式。
2、我在字段管理中将格式改成数字之后预览显示为空。

**Comment by BBchicken-9527** [comment]
类型转换是根据excel表格中字段类型去转换的，你说的这个问题我这边目前没有模拟出来，如果方便的话可能不可能给我你的原表看一下。如果真的有问题的话我们及时修复一下，空白的原因是入库的时候已经是时间类型的了，强转数值类型失败导致的

**Comment by liuboF2c** [comment]
[学习时长.xlsx](https://github.com/dataease/dataease/files/9475399/default.xlsx)
这是我测试使用的 Excel 表格

**Comment by BBchicken-9527** [comment]
你的这个excel确实存在识别异常的问题，我们想办法进一步完善一下数据类型的问题，受累问一下你创建表格使用的系统、工具以及工具的版本，因为我使用excel合wps都没有办法模拟出问题，哪怕是你的表另存为也不行。所以需要详细的询问一下看看是不是系统或工具造成

**Comment by liuboF2c** [comment]
系统：macOS 12.5 (21G72)
软件：WPS 3.8.1(6116)

**Comment by BBchicken-9527** [comment]
好的，我们会进一步进行排查同时优化一下excel的类型识别

**Comment by liuboF2c** [comment]
最新发现：
当单元格设置为[常规]时，DataEase会识别成[数值]
当单元格设置为[数值]时，DataEase会识别成[时间]
![image](https://user-images.githubusercontent.com/30886198/188531239-0b38b373-aca8-4eee-bfc9-f4ef493d2e28.png)

**Comment by BBchicken-9527** [comment]
你那边可以稳定复现嘛？我看过数值类型了，但是我这边创建的不管是excel或者是wps都没办法复现的

**Comment by xuwei-fit2cloud** [comment]
![图片](https://user-images.githubusercontent.com/1892127/193200000-5c820d45-71d3-495d-a919-91741728673d.png)
导入时，指定为小数

**Comment by liuboF2c** [comment]
> ![图片](https://user-images.githubusercontent.com/1892127/193200000-5c820d45-71d3-495d-a919-91741728673d.png) 导入时，指定为小数

这样固然可以，但是仍然希望能够提供高精准度的自动识别字段类型。当字段过多时不需要一个个修改字段类型，尤其是 Excel 数据集过多时会增加很多重复的无意义工作。
