### ISSUE TITLE
[Bug] PostgreSQL 计算字段数值计算不准确

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#2999]
**DataEase 版本**
v1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 104

**Bug 描述**
例如 1/2，结果为 0。2/3 结果为 1。选择的类型为小数，但是只能得到整数。

**Bug 重现步骤(有截图更好)**
**1.增加计算字段，输出结果选择小数。**
<img width="814" alt="image" src="https://user-images.githubusercontent.com/48945409/187428319-d4a1207b-d1b1-4939-8d39-dc937fe5a052.png">
<img width="835" alt="image" src="https://user-images.githubusercontent.com/48945409/187428607-a37a26b2-f6e9-41b3-b7ac-0cc663b0a0cf.png">

**2.查看数据。**
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/48945409/187428839-fd2c6c09-d817-4b2c-9871-a83072a0a479.png">

**3.使用其它数据库测试正常，此处使用 MySQL。**
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/48945409/187429029-67656143-2f11-4942-83ba-da0c9a4107de.png">

**Comment by ywhfzy** [comment]
补充下，MySQL的SQL数据集直连情况下也会出现1/2= 0的情况
![image](https://user-images.githubusercontent.com/82353425/187574955-125ef480-e218-4b57-bffb-af807e989028.png)
![image](https://user-images.githubusercontent.com/82353425/187574976-4558d85e-6439-43a7-8416-f1c9207de271.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，计算字段是交给数据库自身完成的，所以你处理的时候必须针对数据库自身规则去完成的，1.0/2试一下

**Comment by luyang351** [comment]
1.0/2 是可以的。

**Comment by xuwei-fit2cloud** [comment]
v1.15.0版本已发布，请更新版本。
