### ISSUE TITLE
数据集上传excel，保存后点击视图，页面报错

### ISSUE THREAD

**Issue by liufei20151013** [dataease/dataease#30]
<img width="1435" alt="图片" src="https://user-images.githubusercontent.com/15103510/123396638-2118f980-d5d4-11eb-9d63-6e06568661e7.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们会尽快修复。

**Comment by tjlygdx** [comment]
excel 第一行中不能有重名的字段
fix on commit f30b86a
