### ISSUE TITLE
[Bug]MacBook Pro 下Chrome 退出最大化模式后，明细表之前制定字段的排序又还原了

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#3004]
**DataEase 版本**
1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome 版本 104.0.5112.79（正式版本） (x86_64)
运行环境：Mac Book Pro

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.MacBook Pro 上使用Chrome 最大化展示明细表仪表盘（只有一个明细表）；
2.并指定某一字段排序
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/46042812/187577753-4184b636-58fb-420a-a6d5-302a98f55cd2.png">

3.当鼠标向上移动到浏览器Tab标题区域，chrome退出最大化模式，明细表试图的字段的排序又恢复了
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/46042812/187578135-953fc07b-50ee-4671-98fc-5d0b7afd5fdc.png">

期望：所见即所得，排序的动作不应受浏览器的变化而被触发

备注：同样的场景 firefox 正常

**Comment by xuwei-fit2cloud** [comment]
从全屏预览返回到之前页面，其实是两个不同页面。全屏状态下的排序是前端的排序，所以并不会影响到不同页面上。
如果是在仪表板里对视图字段进行了排序，那么只要是预览该仪表板，排序都会保持一致。

**Comment by Andyguo5891** [comment]
同样的场景，firefox是正常，不会跟这浏览器的全屏/返回而变化

**Comment by BBchicken-9527** [comment]
这个是临时的页面排序，触发重新渲染的地方都会失效，要是想一直排序的话 可以把排序设置在字段上，火狐的话我这边环境试了也是不行的。你那边确定是每次都可以保存状态的吗？
