### ISSUE TITLE
[Feature]建议支持数据集批量进行定时任务设置

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#3009]
**请描述您的需求或者改进建议.**
支持数据集批量统一设置定时任务，或者基于数据源一次性进行定时同步任务设置。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈。如果是简单的批量任务添加应该是可以考虑加上的，如果涉及到增量同步SQL的话，可能就不太好实现批量添加了。
我们先考虑一下。
