### ISSUE TITLE
[Feature]数据集/字段管理中的多选按钮建议给个说明，告知用户如何使用

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#3010]
**请描述您的需求或者改进建议.**
该按钮是控制在视图制作时是否显示该字段，能否在全选复选框按钮上给一个说明，如【是否用于视图】等，不然用户挺难理解该复选框的含义的。
![image](https://user-images.githubusercontent.com/60059766/187603526-010932a3-5919-403b-82b2-0baf122c8f4a.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们会增加写说明，表述清楚相关功能。
