### ISSUE TITLE
[Feature]建议在数据集更新设置中支持用户再次重复执行某执行结束的更新任务

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#3011]
**请描述您的需求或者改进建议.**
建议在数据集更新设置中支持用户再次重复执行某执行结束的更新任务，特别是立即执行的任务，其实就是再次执行下更新，然而现在还需要再重新新建一个更新任务，有点不太方便。

![image](https://user-images.githubusercontent.com/60059766/187604853-ec93744b-43f5-44df-969c-4d2867d721b2.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们后续优化一下。
