### ISSUE TITLE
[Feature] 仪表板左方的目录支持缩进。

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3017]
**请描述您的需求或者改进建议.**
在系统管理的左边目录是支持缩进的，想仪表板这边也支持下，可以在不编辑的状态下让仪表板更大的显示。
![image](https://user-images.githubusercontent.com/82353425/187637905-9e395e20-4898-4046-9c8b-fe8e1d93c5e1.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈。
目前的话，在仪表板右上角的按钮栏里可以选择全屏预览，可以获得更大的展示区域。

关于左侧缩进的需求，我们内部讨论一下。
