### ISSUE TITLE
[Bug]配置行权限时，若表字段过多，则无法显示全，缺失滚动条。

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3021]
**DataEase 版本**
v1.13.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 104

**Bug 描述**
配置行权限，配置筛选字段。字段过多时无法显示出全部，缺失滚动条上下滑动。

**Bug 重现步骤(有截图更好)**
1.配置行权限，配置筛选字段。字段过多时无法显示出全部，缺失滚动条上下滑动。
![image](https://user-images.githubusercontent.com/48945409/187658119-17372109-8db0-4fcc-88d5-6d86eacc4737.png)

2.继续拉高浏览器才能显示更多的字段。
![image](https://user-images.githubusercontent.com/48945409/187658808-b963dffb-f64f-43ae-92b2-e379666279f6.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复。
