### ISSUE TITLE
[Bug]Antv明细表格中列宽调整为自适应，实际展示后未自适应

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#3028]
**DataEase 版本**
1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome版本 104.0.5112.101（正式版本） (arm64)

**Bug 描述**
选择Antv明细表格，拖入日期和名称两个字段，然后通过样式中的表格配置将列宽调整设置为【自适应】，明细表格自适应后有内容被省略。

**Bug 重现步骤(有截图更好)**
具体参见如下图：
<img width="659" alt="image" src="https://user-images.githubusercontent.com/60059766/187818337-d26bd33c-68a3-468b-bf78-b9b5946633dc.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，AntV S2图库确实有这个问题，还没有修复。修复后我们将做相应的升级。
