### ISSUE TITLE
[Feature]建议表格颜色配置时同时支持表头字体颜色和表格字体颜色配置

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#3029]
**请描述您的需求或者改进建议.**
当前是支持【表格背景】和【表头背景】颜色分别设置的，但是不支持【表格字体】和【表头字体】颜色分别设置，这样会导致表格表头背景设置不一致时，字体颜色无法一致适配，然后配色就比较难了。
![image](https://user-images.githubusercontent.com/60059766/187819847-dc147ba2-9ff8-44f7-858d-cff9ae907074.png)
如下是PPT中的表格颜色配置效果，供参考：
<img width="351" alt="image" src="https://user-images.githubusercontent.com/60059766/187820243-15461beb-f5f4-48ad-8ab0-3918d8e3c814.png">

**Comment by xuwei-fit2cloud** [comment]
收到，我们会在后续版本对此进行优化。
