### ISSUE TITLE
[Feature]建议“仪表盘”视图的刻度数可以自由调整颜色

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3030]
**请描述您的需求或者改进建议.**
如下图所示，仪表盘默认指针的颜色不一定会很适配当前的仪表板，希望可以自定义。
![image](https://user-images.githubusercontent.com/48945409/187823964-e940e83b-4947-49c9-9c75-7f43b09c1370.png)

**Comment by xuwei-fit2cloud** [comment]
当前版本的仪表盘指针，会跟随仪表板指标值所处区域的颜色，在加了阈值设置后会更加明显。
我们还需要讨论一下该需求的合理性。

**Comment by luyang351** [comment]
之前描述的可能不太贴切，应该是指指针所对应的刻度文字。如上图均为灰色。

**Comment by yayanpei** [comment]
感谢反馈，我们记录一下。
