### ISSUE TITLE
[Feature]添加API数据源后设置数据字段类型时无时间类型

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#3032]
**请描述您的需求或者改进建议.**
在API数据源添加时，完成连接API设置，然后提取数据后，基于解析字段进行字段类型设置时无时间类型可选，如下图所示：
![image](https://user-images.githubusercontent.com/60059766/187841083-0348b8c3-68ce-48b1-8260-964846e2a361.png)

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到
