### ISSUE TITLE
[Bug]汇总表配置跳转字段后切换明细表跳转字段未清空

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3034]
**DataEase 版本**
v1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 104

**Bug 描述**
汇总表配置跳转字段后，切换成明细表，字段被系统清空且未放入新的字段，然而跳转设置中仍然存在之前汇总表的指标字段在其中。注：使用的为 AntV 图表。

**Bug 重现步骤(有截图更好)**
1.新建一个汇总表，并拖入多个维度与指标字段，配置字段的跳转。
![image](https://user-images.githubusercontent.com/48945409/188044149-e898b250-e40d-4ca4-9997-0280d81a86a9.png)

2.将该视图切换为明细表，所有字段均被清空，且当下未配置新的字段。再次打开跳转设置，其中保留了之前汇总表时的指标类型的字段未清除掉。
![image](https://user-images.githubusercontent.com/48945409/188044839-986a63fe-e2d7-4193-bd78-80e2a9059d53.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.15.0版本已发布，请更新版本。
