### ISSUE TITLE
[Bug]【数据集】基于SQL Server 数据源创建 SQL 数据集支持参数情况下报错，详见【Bug重现步骤】

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3035]
**DataEase 版本**
1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准版本

**Bug 描述**
基于SQL Server 数据源创建 SQL 数据集支持参数情况下报错，详见【Bug重现步骤】

**Bug 重现步骤(有截图更好)**
1.dateadd 函数里面添加文本参数
![image](https://user-images.githubusercontent.com/24768910/188068907-d5bd0a52-19ec-42c9-b736-a79686226e35.png)

2.文本参数填入“2022-08-28”
![image](https://user-images.githubusercontent.com/24768910/188069009-db196dc4-8216-4dc7-bed2-161f72b0a3cb.png)

3.点击确认，报错截图以及日志如下
![image](https://user-images.githubusercontent.com/24768910/188069054-58ffb1a6-8d61-433b-884b-e418688a0bf7.png)
[error.log](https://github.com/dataease/dataease/files/9475221/error.log)

4.如果 dateadd 函数写死文本“2022-08-28”，点击确认则不报错
![image](https://user-images.githubusercontent.com/24768910/188069246-0bb9e9fb-0bef-41c6-9b3e-d037833c8eb5.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前参数化功能还在进一步完善当中，我们先看一下
