### ISSUE TITLE
[Bug] 公共链接传参，当参数名称为英文，参数值为中文时，解析报错。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#3036]
**DataEase 版本**
v1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 104.0.5112.101（正式版本） (arm64)

**Bug 描述**
公共链接传参，当参数名称为英文，参数值为中文时，解析报错。

**Bug 重现步骤(有截图更好)**
1. 以2021年全国 GDP 数据为例，创建外部参数，参数名称为 province，联动今年上半年GDP（亿元）的 province 字段。
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/30063018/188087541-fc1a84d9-c029-440e-b105-7c2b8c781cd1.png">
2. 对数据 {"province":"江苏省"} 进行 base64 位编码。
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/30063018/188089593-3db611bf-6442-4e10-b60f-6071c3591758.png">
3. 带参数打开公共链接，报错：外部参数解析错误未生效，请按规定编码方式传参
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/30063018/188090772-615d90d2-2be6-485e-a4d0-b9322af55b2e.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前环境上没有发现你说的问题，应该是url转换上出了问题，你将base64结果url转换一下看看，应该就不会有问题了

**Comment by wangjunboit** [comment]
在线体验 遇到同样的问题
