### ISSUE TITLE
[Bug]如果仪表板为多组件/视图叠加则复用很难选到

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3037]
**DataEase 版本**
v1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 104

**Bug 描述**
想要复用视图时，如果所选择的仪表板中存在多视图/组件进行了图层叠加。则下层的很难被选到，或者被完全覆盖无法选到。
![image](https://user-images.githubusercontent.com/48945409/188102250-bb986864-926d-42c0-8fa9-2f778357e208.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们研究一下这里的处理方式
