### ISSUE TITLE
[Bug] SQL语句 Base64加密，原表新增字段后同步字段会报错

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3039]
**DataEase 版本**
1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.1.13版本的SQL语句直连的方式，在1.14版本上新增了一个字段
2.同步字段报错。
![dc56b6db5e8d7bc2aa1ddceeb4dc15d](https://user-images.githubusercontent.com/82353425/188256515-40e8bbef-d267-451c-8dca-3470008c3a8a.png)

3.百度下了问题。
![image](https://user-images.githubusercontent.com/82353425/188256522-5a1154ca-204f-42be-b0b3-107328380724.png)

4.目前的解决方式就是重新写了一遍SQL语句，是不是Base64加密后新增字段会导致报错呢？

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快处理

**Comment by xuwei-fit2cloud** [comment]
v1.15.0版本已发布，请更新版本。
