### ISSUE TITLE
[Bug] 视图标题编辑错误

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3043]
**DataEase 版本**
1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.首先我在A视图写好标题名字
![2022-09-05_144059](https://user-images.githubusercontent.com/82353425/188381474-583722e3-d2c3-4d22-b1d0-ce8175511cc0.png)

2.当我没有点保存的时候，点了一下B视图，B视图就被命名A视图的标题。
![2022-09-05_144128](https://user-images.githubusercontent.com/82353425/188381498-38c2e5de-a325-4d73-a0be-d652622ae001.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前逻辑需要修改完成后点击一下修改弹窗空白位置完成标题修改，动态逻辑切换最后选中的是那个视图最终修改就是那个视图
