### ISSUE TITLE
[Bug] 全屏情况下，EChart的汇总表看不到汇总行

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3044]
**DataEase 版本**
1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.编辑状态下。
![2022-09-05_145017](https://user-images.githubusercontent.com/82353425/188382811-d3681340-1eb7-41c0-b4ee-4b8e43a28875.png)

2.全屏状态下。
![2022-09-05_145032](https://user-images.githubusercontent.com/82353425/188382847-04816dfa-fa72-46b0-97a3-cfc86438ed8a.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，环境中没有发现你说的情况，清一下缓存看看呢？
