### ISSUE TITLE
[Bug]  精简模式 Api数据源解析报错。

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3046]
**DataEase 版本**
1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.编辑API数据源 ，报错如下。
![f86dcfacf7ba854b25398b7a68b8ba8](https://user-images.githubusercontent.com/82353425/188581499-32985f7f-e0bb-429b-a701-a9165b591160.jpg)

2.以下是返回的JSON中有个空格的value。
![231fdfd34fea8d8ea3b99161551b202](https://user-images.githubusercontent.com/82353425/188581546-4cad3f5c-30e0-4885-b585-a58408a44ff4.jpg)

3.百度了下相关报错，修复如下。
![image](https://user-images.githubusercontent.com/82353425/188581681-4dfc07cb-e79c-44fc-88d3-188caf26ffb2.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by tjlygdx** [comment]
建议新建一个API数据源，在测试一遍
