### ISSUE TITLE
[Bug]定时同步或Excel数据集中包含 150D\96F 时，使用下拉框过滤会失效

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#3047]
**DataEase 版本**
v1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新版

**Bug 描述**
1. 数据集存在文本类型字段 姓名，包含固定内容 150D\96F
2. 将姓名字段配置为下拉框过滤，选择包含 150D\96F 的数据
3. 筛选会失效，无法过滤出对应数据

**Bug 重现步骤(有截图更好)**
筛选前：
<img width="750" alt="image" src="https://user-images.githubusercontent.com/30886198/188601636-6e7a01fc-fcba-4991-8941-2915d5977858.png">
筛选后：
<img width="738" alt="image" src="https://user-images.githubusercontent.com/30886198/188601700-4ad5896b-ddb6-4a89-84e3-5ed6d4140c80.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复的

**Comment by BBchicken-9527** [comment]
感谢反馈，因为\导致查询到数据库的时候引起了歧义所以没有找到的，如果通过数据库直接搜索也是找不到的，除非对\进行翻译，但这可能会影响到原本的含义，所以我们决定暂不处理这个地方，后续如果想到什么更好的解决方式再处理
