### ISSUE TITLE
[Bug] 精简模式 Api 数据源同步报错

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3048]
**DataEase 版本**
1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.同步三个字段，每个字段都有内容则同步成功。
![QQ截图20220906174413](https://user-images.githubusercontent.com/82353425/188604216-06314572-8b15-4fe3-8c12-204e7e2dbe97.jpg)
![QQ截图20220906174430](https://user-images.githubusercontent.com/82353425/188604231-4e273ea5-aeee-46a4-8765-cc48f14a3b86.jpg)
![QQ截图20220906174638](https://user-images.githubusercontent.com/82353425/188604405-f80443a6-2eff-4a1a-9672-8e05cefda91f.jpg)

2.同步多字段，且有些字段里面是空值，则同步失败。
![QQ截图20220906174604](https://user-images.githubusercontent.com/82353425/188604364-4ed5f2af-db99-4b9a-a519-072039cf8fc2.jpg)
![QQ截图20220906174609](https://user-images.githubusercontent.com/82353425/188604373-6fbea500-44f0-44a6-9af3-8e5255f7a5c9.jpg)
![QQ截图20220906174631](https://user-images.githubusercontent.com/82353425/188604392-62f7ca39-caf3-43bb-b9bd-09de01370d38.jpg)

3.报错空指针异常了。
![QQ截图20220906174504](https://user-images.githubusercontent.com/82353425/188604436-e6b8b695-da91-487d-aa42-816fd0f637a9.jpg)

**Comment by BBchicken-9527** [comment]
感谢反馈，你说的这个问题环境中没有发现，方便的话微信或者企业微信沟通一下，或许是我这边少了什么关键步骤
