### ISSUE TITLE
[Feature] 请求原生支持Docker部署

### ISSUE THREAD

**Issue by AlianBlank** [dataease/dataease#3051]
**请描述您的需求或者改进建议.**
由于部署环境比较复杂。能不能直接一键部署到docker容器环境中。快速迁移和设置

**Comment by yayanpei** [comment]
感谢您的反馈，目前采用的是原生编排方式，暂不支持原生的docker部署。

**Comment by xuwei-fit2cloud** [comment]
你好，DataEase本身就是运行在原生的Docker环境中的，只是DataEase运行时的一些配置参数以及相关运行目录的创建，我们放在了外部脚本中做了处理。如果要跳过安装脚本安装的话，需要参考一下[installer](https://github.com/dataease/installer)工程，按实际情况调整 docker-compose 文件，通过 docker-compose 命令运行即可。

**Comment by AlianBlank** [comment]
DataEase 有没有计划发布docker 镜像到docker hub？

**Comment by xuwei-fit2cloud** [comment]
国内从docker hub上拉取镜像速度会比较慢一些，我们目前使用的是国内阿里云的镜像服务。
我们也做过相关的拉取测试，国内外的服务器上拉取镜像速度都还是不错的，所以短期内还没有计划推送到docker hub。

**Comment by AlianBlank** [comment]
请问一下aliyun 的docker 镜像地址是在什么地方的呢？是否是公共镜像呢？

**Comment by xuwei-fit2cloud** [comment]
DataEase的镜像是公共镜像，无需认证即可拉取，但阿里云现在的镜像中心还不完善，不能像docker hub一样进行查询和浏览。

DataEase的镜像地址在对应的docker-compose文件中有描述，比如最新的v1.14.0版本的镜像地址为：
registry.cn-qingdao.aliyuncs.com/dataease/dataease:v1.14.0
一般前缀都是不变的，每个版本仅修改后面的版本号。

**Comment by raind-cd** [comment]
-INFO in org.springframework.boot.logging.logback.SpringBootJoranConfigurator@7f560810 - Registering current configuration as safe fallback point
Logging system failed to initialize using configuration from 'null'
java.lang.IllegalStateException: Logback configuration error detected:
ERROR in ch.qos.logback.core.joran.action.PropertyAction - Could not find properties file [/opt/dataease/conf/dataease.properties].


阿里云镜像启动时报如上错误，是需要手动创建/opt/dataease/conf/dataease.properties ？
