### ISSUE TITLE
[Feature] 建议提供封装好的 DataEase Vue.js 组件，便于嵌入 DataEase 仪表板

### ISSUE THREAD

**Issue by maninhill** [dataease/dataease#3052]
**请描述您的需求或者改进建议.**

请参考：https://github.com/microsoft/powerbi-client-vue-js

**Comment by xuwei-fit2cloud** [comment]
感谢您提供的宝贵建议，但目前的DataEase还不能提供相关支持。
实现以上需求需要对DataEase做较大改动，我们会考虑在后续的大版本中加入支持。
