### ISSUE TITLE
[Bug] Kettle集群后，相应的KTR与KJB脚本中，未写入集群信息（Kettle集群配置不起作用）

### ISSUE THREAD

**Issue by shuiyouzhi** [dataease/dataease#3053]
**DataEase 版本**
1.3.0

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
版本 104.0.5112.101（正式版本） (x86_64)

**Bug 描述**
Kettle集群后，相应的KTR与KJB脚本中，未写入集群信息
1 系统管理 -> 系统参数 -> Kettle设置 中，维护了集群配置信息，如图1
2 数据集立即更新
3 生成相应Kettle脚本后发现，集群配置未生效，原因是脚本中的 “slaveservers”标签内容为空，如图2

**Bug 重现步骤(有截图更好)**
1.
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/12723715/188777433-863b2bec-1c04-4eba-ad3a-b5bda1669288.png">

2.
<img width="656" alt="image" src="https://user-images.githubusercontent.com/12723715/188777771-b7e59276-3b82-490b-8260-c7c9da383e84.png">

**Comment by tjlygdx** [comment]
添加多个kettle服务后，并不是组成kettle集群，而是从这几个kettle中选取一个执行任务，所以不会用到slaveservers
