### ISSUE TITLE
[Bug] 在线体验环境的默认仪表板显示问题

### ISSUE THREAD

**Issue by maninhill** [dataease/dataease#3054]
如图

![image](https://user-images.githubusercontent.com/41712985/188778609-80709085-02c6-4c9c-b4fd-baefeeb0a9a0.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.15.0版本已发布，请更新版本。
