### ISSUE TITLE
[Bug]ECharts 图表同时开启缩略轴与图例时，两者会重叠

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3055]
**DataEase 版本**
v1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 104

**Bug 描述**
ECharts 图表同时开启缩略轴与图例时会重叠，图例会位于缩略轴上。

**Bug 重现步骤(有截图更好)**
1.选择 ECharts 坐标系类图表，并打开该图表的缩略轴与图例，可看到其位置会重叠。
![image](https://user-images.githubusercontent.com/48945409/188780633-bd400ce2-f766-4a52-95e9-7ac0508b2641.png)

2.切换为 AntV 图表，不会有遮挡。
![image](https://user-images.githubusercontent.com/48945409/188780916-d31baa08-e9f7-41b2-80b6-62906bb3d05c.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，echarts图库问题我们也在努力想办法优化，目前最好是通过图例设置去调整
