### ISSUE TITLE
[Bug]当 SQL 中包含特殊字符 `` 时数据预览报错

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#3057]
**DataEase 版本**
1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
最新版 Edge

**Bug 描述**
以下 SQL 在添加数据集页面预览正常，添加成功后在数据预览界面会报错
select region_name '地域', zone_name '集群', sum(`host`) from cloud_server
去除反引号后恢复正常
select region_name '地域', zone_name '集群', sum(host) from cloud_server

**Bug 重现步骤(有截图更好)**
1. 添加 SQL 数据集并能够正常预览数据
select region_name '地域', zone_name '集群', sum(`host`) from cloud_server
2. 添加后进入数据集预览界面，会报错如下：
预览数据错误：执行SQL失败。可能因相关字段、表、数据集等元素发生变更，请检查->SQL ERRORYou have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '`)` AS f_ax_2 FROM (select region_name '地域', zone_name '集群'' at line 4
<img width="1716" alt="image" src="https://user-images.githubusercontent.com/30886198/188837153-a110ec4b-a7b0-404a-90f5-0ea135f7b89e.png">

是否考虑支持特殊字符或限制字段名不允许填写特殊字符？

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先讨论一下如何处理。
