### ISSUE TITLE
[Bug] sql数据集修改字段先后顺序后，预览不起作用

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3062]
DataEase 版本
v1.14.0

运行方式(安装包运行 or 源码运行 ?)
安装包

浏览器版本
chrome 104.0.5112.79

**Bug 描述**
sql数据集修改字段先后顺序后，预览不起作用

**Bug 重现步骤(有截图更好)**
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/45852479/189253704-dd17b043-20a0-4381-9a70-b3162c069fd0.png">
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/45852479/189253712-842fbf0c-eb76-4c86-ade2-30a7c395cad0.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们下个版本处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.15.0版本已发布，请更新版本。
