### ISSUE TITLE
表格组件MongoDb数据集数据混乱[Bug]

### ISSUE THREAD

**Issue by qq976314419** [dataease/dataease#3066]
**DataEase 版本**
1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
离线安装包，Local模式部署。1.13.1升级到1.14.0

**浏览器版本**
Chrome 版本 88.0.4324.150（正式版本）

**Bug 描述**
表格组件显示直连MongoDb数据集，表格字段数据混乱

**Bug 重现步骤(有截图更好)**
1.MongoDb数据源，直连模式。

2.新建Sql数据集
![image](https://user-images.githubusercontent.com/48644912/189288810-0e969a19-9885-4264-9314-41ccb9c4e518.png)
3.新建表格视图
![image](https://user-images.githubusercontent.com/48644912/189289942-671227fd-0f5e-4ff8-b802-795f56a8b85b.png)
库存数据和名称数据混乱。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们目前没有重现此问题，还需要点时间深入查找原因以解决此问题。
建议您可以先试试重新创建一个视图看看。

**Comment by qq976314419** [comment]
你好，我尝试新建了一个表格视图，问题依然存在
1.尝试更简sql语句，取消了Where 和order by，问题依旧存在。
2.新建表格视图，切换 Ant V和Echarts明细表，问题依旧存在。
3.SQL 仅取DisplayName及库存数量，问题解决。

问题复现建议，SQL语句取出3个及以上属性或字段，使用表单视图，显示2个属性，数据错乱。

**Comment by xuwei-fit2cloud** [comment]
以下是我的测试结果：
![图片](https://user-images.githubusercontent.com/1892127/190123635-13470323-ab07-41d6-bb60-f805fcba0234.png)
![图片](https://user-images.githubusercontent.com/1892127/190123676-1bba20d8-a39a-4ac4-8a6d-24ae4b13a69a.png)

确实是没有复现，不过我们的技术人员还在排查中。

**Comment by qq976314419** [comment]
数据源类型换成MongoDb而不是MongoDb Bi试一下呢？不知道会不会有影响。

**Comment by xuwei-fit2cloud** [comment]
![图片](https://user-images.githubusercontent.com/1892127/190293551-16ab98e3-cd72-4f28-ae92-49abdd68451f.png)
![图片](https://user-images.githubusercontent.com/1892127/190293460-a202b2c6-6bdd-40e3-b6c3-1566c329f183.png)
也都正常，我们再看看哈。
