### ISSUE TITLE
[Bug] 导出视图PDF和图片时，只导出了部分，请见截屏

### ISSUE THREAD

**Issue by jason-fit2cloud** [dataease/dataease#3069]
**DataEase 版本**
v1.14.0 

**运行方式(安装包运行 or 源码运行 ?)**
导出PDF和图片时，只导出了部分

**浏览器版本**
Google Chrome Version 104.0.5112.101 (Official Build) (x86_64)

**Bug 描述**
导出PDF和图片时，只导出了部分

**Bug 重现步骤(有截图更好)**
1. 选择某个视图，打开【视图】页面
2. 在【视图】页面的操作选择中，选择【导出】/【导出为PDF】、【导出】/【导出为图片】
3. 查看导出的PDF文件、图片文件
![销售部门业绩数据](https://user-images.githubusercontent.com/9998431/189394349-4a26fd94-ed4f-4244-9cab-7ce9f0e23cb3.png)
[销售部门业绩数据.pdf](https://github.com/dataease/dataease/files/9537071/default.pdf)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复。
