### ISSUE TITLE
是否可以向下钻取到另一个国家的地图，例如德国？

### ISSUE THREAD

**Issue by hamidreza07** [dataease/dataease#3070]
在地图上，我们可以向下钻取中国城市，但我想在德国等另一个国家添加和向下钻取。 我之前要求添加另一个国家，并引用了 https://img.hcharts.cn/mapdata/ 网站，但它不支持向下钻取。 请你帮助我好吗？

**Comment by BBchicken-9527** [comment]
感谢支持，国家地图是支持钻取的，任何区以上的行政区域都可以钻取，不知道你是否映射了属性，可以在视图设置弹窗中高级分栏设置一下看看

**Comment by hamidreza07** [comment]
当我单击地图时，我正在向地图图表中添加钻取，我不断收到此错误“无关字段”。 请你帮助我好吗？

**Comment by BBchicken-9527** [comment]
方便的话我能看一下你的异常和高级分栏里面的设置吗

**Comment by hamidreza07** [comment]
谢谢你回答我的问题。 你的回答解决了我的问题。
