### ISSUE TITLE
[Feature] 指标卡在数据为 null ，或者无法查询出数据时，显示为 - ，或显示无数据

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#3071]
当前指标卡在无数据时显示为0，这个是不是不太合适，0 也是一个数值，无数据时是否应该标明无数据。
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/30063018/189794263-79875e6c-9ac6-484b-a257-e2b9b90c3efd.png">

**Comment by xuwei-fit2cloud** [comment]
收到反馈，我们已调整，请等待新版本发布。

**Comment by xuwei-fit2cloud** [comment]
v1.15.0版本已发布，请更新版本。
