### ISSUE TITLE
[Bug] 管理员无法看到删除用户创建的数据集文件夹或者数据集。

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3073]
**DataEase 版本**
1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.创建A用户，A用户创建B仪表板，C数据集。被管理员删除A用户之后。
2.管理员能看到B仪表板，但是不能看到C数据集，但在权限管理配置里面能看到C数据集。
3.然后对D用户授权C数据集，用D登录DataEase之后，再用管理员登录DataEase 就能看到C数据集。
![image](https://user-images.githubusercontent.com/82353425/189846004-92854d84-e6ea-4174-9258-3ef145467bb8.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复。

**Comment by xuwei-fit2cloud** [comment]
v1.15.0版本已发布，请更新版本。
