### ISSUE TITLE
[Bug]新建数据集计算字段是使用CONCAT函数第二个逗号不是英文逗号

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3074]
DataEase 版本
v1.14.0

运行方式(安装包运行 or 源码运行 ?)
安装包

浏览器版本
chrome 104.0.5112.79

**Bug 描述**
新建数据集计算字段是使用CONCAT函数第二个逗号不是英文逗号

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/45852479/189857837-62f18dbd-2cef-44c0-a571-751fec3c3ac5.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们会尽快修复。

**Comment by xuwei-fit2cloud** [comment]
v1.15.0版本已发布，请更新版本。
