### ISSUE TITLE
[Bug]富文本视图设置数值格式后不生效

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#3076]
**DataEase 版本**
v1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Microsoft Edge
版本 105.0.1343.33 (正式版本) (64 位)

**Bug 描述**
富文本视图设置数值格式后不生效

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/96223591/190044930-a1f9c3f4-2dfa-48cf-9def-43549aeff60c.png)

2.
![image](https://user-images.githubusercontent.com/96223591/190044977-d4290aa4-764f-4192-98b3-7775cc588240.png)

3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，已确认问题，我们会尽快修复。

**Comment by xuwei-fit2cloud** [comment]
v1.15.0版本已发布，请更新版本。
