### ISSUE TITLE
[Bug]AntV 图库柱状图柱间隔调整无效

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#3080]
**DataEase 版本**
v1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge
版本 105.0.1343.33 (正式版本) (64 位)

**Bug 描述**
AntV 图库柱状图有柱间隔选项，但是调整无效，在数据少的情况下，柱子就显得大了。

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/96223591/190131949-56bb6109-91d8-4b22-a262-1d8ca2ea8c0b.png)

2.
3.

**Comment by xuwei-fit2cloud** [comment]
这个柱间距调整的不是单个柱的间距，而是一组柱的间距。此处柱间距设置功能确实容易误解，我们正在考虑优化。
