### ISSUE TITLE
[Bug]权限设置中缺少部分权限

### ISSUE THREAD

**Issue by wan92hen** [dataease/dataease#3081]
**DataEase 版本**
v1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge 105.0.1343.33

**Bug 描述**

从 v1.13.1 升级到 v1.14.0 后，同样是内置的管理员角色，后创建的用户无法看到该菜单，只有初始的 admin 用户可以看到。

查看角色权限发现权限设置中缺少了系统配置下的外观配置。

![image](https://user-images.githubusercontent.com/27671436/190150378-37b28070-d409-4297-88e4-2147d616ed4f.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们后续版本修复一下。

**Comment by xuwei-fit2cloud** [comment]
v1.15.0版本已发布，请更新版本。
