### ISSUE TITLE
[Bug]饼图弹出动画不能连续触发

### ISSUE THREAD

**Issue by wan92hen** [dataease/dataease#3082]
**DataEase 版本**
v1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge 105.0.1343.33

**Bug 描述**
仪表盘中的饼图弹出效果，同一片扇形点击触发弹出、收起效果后，再次点击这个扇形无法再次触发弹出，需要点击其他扇形触发弹出后，才能点击这个扇形再次触发。

**Bug 重现步骤(有截图更好)**
1. 制作一个带饼图的仪表盘，假设仪表盘分为了 A、B、C 三个扇形；
2. 点击 A 扇形区域，触发弹出效果，再次点击触发收起效果；
3. 再次点击 A，无法触发弹出效果；
4. 点击 B 触发弹出效果后，再次点击 A 才能触发弹出效果。

**Comment by xuwei-fit2cloud** [comment]
ECharts 图库中的饼图和玫瑰图确实有这个问题，我们处理一下。
