### ISSUE TITLE
[Feature]外观配置中的图片展示优化

### ISSUE THREAD

**Issue by wan92hen** [dataease/dataease#3083]
**请描述您的需求或者改进建议.**
建议外观配置中的各个图片缩略图按照建议尺寸的比例进行展示，目前都被压缩成了方形，不是特别美观。

**Comment by xuwei-fit2cloud** [comment]
很好的建议，我们后续会做相关优化。

**Comment by xuwei-fit2cloud** [comment]
v1.15.0版本已发布，请更新版本。
