### ISSUE TITLE
年环比、月环比出现问题

### ISSUE THREAD

**Issue by smingk** [dataease/dataease#3087]
在做年环比时，总是出现前一年的维度，且没有数据；在月环比时，当年1月有维度也无数据，并不出现9月（当月）数据。
![image](https://user-images.githubusercontent.com/113573868/190351035-ba082a9b-1904-4112-81aa-0c04805d0b89.png)

**Comment by smingk** [comment]
是最新的DATAEASE 1.14版本。

**Comment by BBchicken-9527** [comment]
感谢反馈，这是因为没有数据造成的，同环比的话是需要之前数据和现在数据对比，如月环比没有1月份数据的原因是因为没有上期数据做运算所以导致显示为空，可以看一下提示的

**Comment by BBchicken-9527** [comment]
![image](https://user-images.githubusercontent.com/84372766/190371979-7bb739ae-06a1-4903-bb79-94e983813a9e.png)

**Comment by BBchicken-9527** [comment]
年同比同理

**Comment by smingk** [comment]
感谢回复，你的意思我懂，
但我们的各药店数据库里，历年每一天都有数据，但同比和环比的第一个维度总是没数据，这样的识图总是不太美观



***@***.***
 
发件人： 走日
发送时间： 2022-09-15 17:43
收件人： dataease/dataease
抄送： smingk; Author
主题： Re: [dataease/dataease] 年环比、月环比出现问题 (Issue #3087)
感谢反馈，这是因为没有数据造成的，同环比的话是需要之前数据和现在数据对比，如月环比没有1月份数据的原因是因为没有上期数据做运算所以导致显示为空，可以看一下提示的

**Comment by BBchicken-9527** [comment]
嗯 .... 你的意思我明白了，你是觉得不太美观，想问一下是不是可以隐藏没有数据的月份是吗？如果是这样的话目前可以通过视图过滤器的方式过滤掉没有数据的首尾，设置一次后后续都不会再重复设置了，因为我理解你们数据开始的起点已经是固定的了，所以只要限制不去显示开始就可以了。

**Comment by BBchicken-9527** [comment]
更进一步的优化我这边记录一下，我们开会讨论一下是否有必要去优化一下如一键勾选隐藏不存在数据的字段这些
