### ISSUE TITLE
[Feature]【气泡地图】气泡地图支持设置地图颜色

### ISSUE THREAD

**Issue by Xiaominm** [dataease/dataease#3093]
当前只支持设置数值气泡的的颜色。地图的背景颜色均为白色；在深色大屏的场景下气泡地图的白色背景就格格不入了。
希望可以支持设置气泡地图，地图本身的颜色，最好可支持渐变色。
例如：现在单独设置的地图边线。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，需求已收到，我们后续版本会做相关开发计划。
