### ISSUE TITLE
[Feature]【组件】增加轮播图

### ISSUE THREAD

**Issue by Xiaominm** [dataease/dataease#3094]
当前只有单独的图片组件，是否可增加轮播图的组件，可以支持设置

- 轮播图的数量
- 是否自动轮播
- 图片停留展示时间
- 轮播动画的时间
- 轮播的效果：动画播放的效果，可选：水平滚动、垂直滚动、淡入淡出、马赛克。
- 轮播图底部的圆点样式：圆点颜色支持设置当前选中图片圆点颜色及未选中图片的圆点颜色
- 图片的适应方式

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，该需求已在我们的需求池中，后续版本会安排开发。
