### ISSUE TITLE
[Feature]【选项卡组件】支持设置选项卡的排列方式、轮播显示、选中文字和未选中文字的大小

### ISSUE THREAD

**Issue by Xiaominm** [dataease/dataease#3095]
当前只支持设置标题文字的选中颜色和为选中颜色，希望可以支持如下设置
支持选项卡标题文字的大小。包含选中时文字大小和未选中时文字大小；
支持选项卡标题文字在选项卡内的对齐方式；
支持设置选项卡是否轮播显示，包含停留时间；
支持设置选项卡网格布局，当前选项卡均为横排布局，是否可考虑支持选项卡的竖排布局；

**Comment by xuwei-fit2cloud** [comment]
收到需求，我们已有相关计划，会在后续版本支持。
