### ISSUE TITLE
[Bug]视图，组合图设置主轴和副轴的过滤条件，图表数据显示不全

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#3096]
**DataEase 版本**
v1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Microsoft Edge
版本 105.0.1343.42 (正式版本) (64 位)

**Bug 描述**
组合图设置主轴和副轴的过滤条件，图表数据显示不全

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/96223591/190605160-af862673-cf0c-4e2d-80c3-93088fca6a4c.png)

2.正常展示：
![VriPckuWVl](https://user-images.githubusercontent.com/96223591/190606759-ec38772d-1d6b-4d89-ac50-5245f4e36b08.png)

3.操作过滤上图数值
![image](https://user-images.githubusercontent.com/96223591/190606412-1f3bacf0-6583-4946-b2cf-b0608f090fab.png)

结果
![image](https://user-images.githubusercontent.com/96223591/190606489-27d6953e-7730-48db-b516-07110bb9786a.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，环境中没有发现你说的问题，你看看复制一下视图，调整成表格视图看看数据是不是有缺少？
