### ISSUE TITLE
[Bug]【过滤组件】过滤组件标题设置一遍，关闭再开启第一次设置标题内容不在。

### ISSUE THREAD

**Issue by Xiaominm** [dataease/dataease#3097]
**DataEase 版本**

v1.13.0
**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**

过滤组件标题设置初始一遍，关闭再开启第一次设置标题内容不在。需要再次输入标题，是否可保留之前设置文字。

**Comment by xuwei-fit2cloud** [comment]
收到，我们下个版本做一下优化。

**Comment by xuwei-fit2cloud** [comment]
新版本已发布，请更新版本。
