### ISSUE TITLE
[Feature]【视图组件】辅助线的数值显示与指标的数值格式保持一致

### ISSUE THREAD

**Issue by Xiaominm** [dataease/dataease#3098]
**请描述您的需求或者改进建议.**
当前可支持设指标的数值格式、横纵的数值格式，但在添加辅助线时还是初始数值格式。希望辅助线的数值格式跟随指标的数值格式
<img width="866" alt="image" src="https://user-images.githubusercontent.com/105192435/190613621-fc29d467-923a-4d2d-87dc-c236dabe865a.png">
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/105192435/190614791-ddd1a5a8-7c7d-45cd-ab29-f45d95a10de4.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前正在计划做相关支持，请等待后续版本发布。
