### ISSUE TITLE
[Bug]文字组件修改字号时数字变动异常

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#3099]
**DataEase 版本**
1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome

**Bug 描述**
仪表板中的文字组件，修改字号，删除字号会自动变为12。

**Bug 重现步骤(有截图更好)**
1.在仪表板中，配置文字组件的字体大小，如下图，当前时 20 号大小；
<img width="424" alt="图片" src="https://user-images.githubusercontent.com/48307752/190836161-797c0d8a-ee14-478c-846d-c4e325b891c7.png">

2. 比如，将 20 号改为 24 号，删除 2 0 后面的 0 时，会自动变为 12
<img width="528" alt="图片" src="https://user-images.githubusercontent.com/48307752/190836299-c11ddef6-cd9c-45a0-9f05-da06af8f1fbf.png">

3.  将 20 号改为 24 号，常规的习惯是，将 0 删除，敲一个 4 ，但删除 0 时，字号框变成了12， 继续敲一个 4，目光在键盘上，没有主意屏幕，就变成了124。

**Comment by BBchicken-9527** [comment]
感谢反馈，这个问题我们也在讨论以怎样的形式去优化会更好，确认之后将会在下个版本做出改变，感谢

**Comment by xuwei-fit2cloud** [comment]
新版本已发布，请更新版本。
