### ISSUE TITLE
「优化建议」对于组织的概念不清晰

### ISSUE THREAD

**Issue by fitchibing** [dataease/dataease#31]
组织可以不填，也可以选择默认组织，不经过重度尝试不太清楚有什么区别，如果无 license 不能新建组织的话 建议所有用户都在默认组织下是不是更合理一些

**Comment by yayanpei** [comment]
感谢您的反馈，您的建议是我们产品改进的方向

**Comment by wangyw1863** [comment]
这个我也是看不太明白

**Comment by xuwei-fit2cloud** [comment]
v1.4 版本已经在开源版本里去掉了组织和角色的选择。
