### ISSUE TITLE
明细表数据量太大，浏览器会崩溃，请问一下 目前这个版本是不支持 后端分页吗

### ISSUE THREAD

**Issue by SopLong** [dataease/dataease#3100]
使用明细表，数据量超过2W条，使用分页后，加载浏览器会直接崩掉
看了一下，现在的分页是在前端直接进行的分页，可以配置后端进行分页吗

**Comment by xuwei-fit2cloud** [comment]
这个需要分情况，如果是定时同步模式的数据集，数据是存放在Doris里的，但目前我们对Doris中存放的数据并没有进行排序（不排序是因为数据量大的情况下会存在些性能问题），所以这种类型的数据集是不支持排序的。

我们后期版本会针对直连模式的数据集进行前后端分页的支持。
