### ISSUE TITLE
[Bug]仪表盘视图中使用包含union all的sql数据集报错

### ISSUE THREAD

**Issue by xlostway** [dataease/dataease#3101]
**DataEase 版本**
v1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
docker安装包

**浏览器版本**
chrome

**Bug 描述**
sql数据集不支持包含union all的语句

**Bug 重现步骤(有截图更好)**
1.创建包含union all的sql数据集
2.保存预览正常
3.仪表盘视图报异常如下
      "io.dataease.exception.DataEaseException: java.lang.ClassCastException,无法正常显示"
推测sql解析器JSqlParser不支持union all语法

**Comment by BBchicken-9527** [comment]
感谢反馈，我们的环境中没有发现你说的问题，请问一下具体使用的什么数据库，以及使用的什么图标，我们使用的是mysql数据库表格图标。

**Comment by xlostway** [comment]
你好，我是谢晋峰，你的邮件我已经收到，谢谢！

**Comment by BBchicken-9527** [comment]
期待你的详细参数

**Comment by xlostway** [comment]
升级到v1.14.0版本未见此问题了
