### ISSUE TITLE
[Bug]  关联数据集无法在气泡地图使用

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#3103]
**DataEase 版本**
1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
 MySQL 或 SQLServer 直连数据集，做关联数据集后，在气泡地图中使用报错。

**Bug 重现步骤(有截图更好)**
1.在 MySQL 数据库中准备两张表，如下：
<img width="428" alt="图片" src="https://user-images.githubusercontent.com/48307752/190952954-c9227550-31f4-4936-a0ad-77563fe36ff3.png">

2. DataEase 创建数据库数据集，选择 两张表 -- 直连；
3. 创建关联数据集，选择刚才创建的两个数据集数据集；关联字段为 ID；
4. 仪表板创建 “气泡地图”，选择刚才创建的 关联数据集，将 “地区” 字段拖入气泡地图的维度框，视图报错：
<img width="586" alt="图片" src="https://user-images.githubusercontent.com/48307752/190953272-a3af23eb-ca48-41ad-97df-93a54f5d5ad2.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
新版本已发布，请更新版本。
