### ISSUE TITLE
[Bug] 分享公共链接，登陆用户访问视图提示无权限

### ISSUE THREAD

**Issue by zhangchaochao-fit2cloud** [dataease/dataease#3107]
**DataEase 版本**
v1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge
版本 105.0.1343.42 (正式版本) (x86_64)

**Bug 描述**
分享公共链接，访问提示无权限（可能是因为登陆用户没权限导致的，权限优先级的问题，公共链接不应该判断权限）
无痕访问没问题

**Bug 重现步骤(有截图更好)**
1. 分享公共链接，登陆了系统的用户访问提示没权限
2.无痕访问没问题
3. 报错截图如下：
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/70739359/190976931-93d1e17b-95a8-4e04-8f31-ea255ebdfa3b.png">

**Comment by xuwei-fit2cloud** [comment]
目前是这样设计的。
用同一个浏览器访问DataEase平台时，浏览器可以从cookie中获取到用户信息，会走权限校验。
用户不登录的话，访问公共链接是不会走权限校验的。
