### ISSUE TITLE
[Bug] 编辑视图，活动的 Tab 显示问题

### ISSUE THREAD

**Issue by zhangchaochao-fit2cloud** [dataease/dataease#3119]
**DataEase 版本**
v1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge
版本 105.0.1343.42 (正式版本) (x86_64)

**Bug 描述**
视图的 Tab 回显问题，点击 [样式] 或 [高级] ，收缩侧边栏后，再次打开，默认显示的是 [数据] Tab 栏

**Bug 重现步骤(有截图更好)**
1. 点开视图编辑，选择 [样式] Tab
2. 收缩右侧编辑栏
3. 再打开视图编辑，会发现活动的标识在 [数据] Tab上
<img width="345" alt="image" src="https://user-images.githubusercontent.com/70739359/191187486-d0dd60cd-060c-496e-af78-c5289cde1f87.png">
<img width="348" alt="image" src="https://user-images.githubusercontent.com/70739359/191187700-180371e2-4dff-4f3c-961c-ae0daaefcfc7.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，我们会尽快修复
