### ISSUE TITLE
[Feature]内置MySQL数据库是否考虑更换为PostgreSQL

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#3126]
很多公司不方便使用 Oracle 旗下的产品，所以 内置的 MySQL 直接导致用户不能使用 DataEase；

可否考虑替换使用 PostgreSQL 替换 MySQL ？或者用户安装时自行选择使用 MySQL和 PostgreSQL 。

**Comment by xuwei-fit2cloud** [comment]
当前版本已经不太方便去调整运行数据库了，在今后的2.x版本中我们会把这个需求考虑在内。
