### ISSUE TITLE
Tab组件实现的效果建议

### ISSUE THREAD

**Issue by sanlywork** [dataease/dataease#3127]
目前tab组件是选某个试图或者单一的现有组件包裹进去。
而习惯做大屏的操作是。tab组件只是一个容器，容器里面可以放入不同的多个组件或者文字，就类似于一个内嵌页面，而且大多数展示的时候，tab组件可以支持自动循环播放tab子组的。
这个和目前的效果差距蛮大的。看能否改进下。

**Comment by yayanpei** [comment]
tab组件我们正在规划重构，会将您的建议考虑在内的，感谢您的反馈和支持。
