### ISSUE TITLE
[Bug]针对文本筛选组件筛选后的富文本视图再次编辑问题

### ISSUE THREAD

**Issue by flashboo** [dataease/dataease#3128]
**DataEase 版本**
V1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrom105.0.5195.125

**Bug 描述**
富文本视图创建完成，通过时间、文本或者数字筛选组件筛选后，不清空筛选内容再次编辑富文本视图，视图内参数字段会被固定，无法修改

**Bug 重现步骤(有截图更好)**
1.创建一个富文本视图
<img width="485" alt="image" src="https://user-images.githubusercontent.com/44344081/191246635-969a4976-b127-40f2-b56f-a20291f68e04.png">
<img width="575" alt="image" src="https://user-images.githubusercontent.com/44344081/191246814-eadd94ba-6dbd-43ac-94c6-7e96f527edc7.png">

2.通过文本下拉组件对富文本视图进行筛选展示
<img width="894" alt="image" src="https://user-images.githubusercontent.com/44344081/191246813-c760872e-b673-4851-babb-f1cbd14bd18e.png">

3.在此基础上不删除shai xuan wen ben k筛选文本框中的筛选条件编辑富文本视图
<img width="864" alt="image" src="https://user-images.githubusercontent.com/44344081/191246944-420810bb-2e80-4035-a805-d3c5867b9aa5.png">

4.保存后第一次编辑的参数字段就被固定，无论如何筛选都不会变化
<img width="897" alt="image" src="https://user-images.githubusercontent.com/44344081/191247063-a0ae0167-8d44-4908-a816-b184ccd4fa3f.png">
<img width="845" alt="image" src="https://user-images.githubusercontent.com/44344081/191247103-f7433d88-8ac5-4f84-912b-5d055ebc5f70.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
感谢反馈，问题已经修复，将会在下个版本上线，到时候可以更新体验

**Comment by xuwei-fit2cloud** [comment]
v1.15.0版本已发布，请更新版本。
