### ISSUE TITLE
[Bug]气泡地图无法通过鼠标放大以及移动

### ISSUE THREAD

**Issue by flashboo** [dataease/dataease#3129]
**DataEase 版本**
V1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrom105.0.5195.125

**Bug 描述**
气泡地图无法通过鼠标放大以及移动

**Bug 重现步骤(有截图更好)**
1.创建一个气泡地图
<img width="489" alt="image" src="https://user-images.githubusercontent.com/44344081/191247584-8fa727cc-31b6-4a05-a913-7298f907096d.png">

2.通过鼠标滚轮放大无法放大
3.通过左下角将地图放大后，无法进行拖拽，边缘地图无法展示
<img width="469" alt="image" src="https://user-images.githubusercontent.com/44344081/191248043-15984fba-612a-40aa-a004-dc65e85c40e4.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，气泡地图本身是不可以移动的，因为放开这里会引起一些问题，我们也在寻找更好的解决方式。
