### ISSUE TITLE
[Bug] 定时报告发送尚未加载完的仪表板图片

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3141]
**DataEase 版本**
1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌标准版

**Bug 描述**
1.由于仪表板数据量加载时间过长，可能超过定时报告的一个限定时间，没有加载完毕之后就直接发送了。
以下就是定时报告发送的仪表板图片。
![a864fd53c75ffc061c28f57166b9f58](https://user-images.githubusercontent.com/82353425/191478562-650d4949-8f76-4539-a921-1431eb57772e.png)

2.能不能延长加载时间呢？或者说判断仪表板加载完毕之后再发送定时报告。

**Comment by BBchicken-9527** [comment]
感谢反馈，此问题为已知问题，我们目前也在想办法解决
