### ISSUE TITLE
[Bug] 定时同步将 MySQL decimal 类型字段 转化为 Doris 表精度缺失问题

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3142]
**DataEase 版本**
1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌标准版

**Bug 描述**
1.MySQL 数据表的字段是decimal，定时同步过后转成 Doris 数据表的字段类型就变成了 double。
2.这时候就会出现精度缺失的问题，然后数据集上取的也是doris数据。
3.只需要手动去改doris的字段类型，由double改成decimal就可以了。
4.后端逻辑判断能不能识别出decimal类型的，再将doris建表字段语句也改成对应的decimal

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
你好，问题已修复，要重新同步字段，并做全量更新，请在10月8日新版本发布时进行更新。

**Comment by xuwei-fit2cloud** [comment]
v1.15.0版本已发布，请更新版本。
