### ISSUE TITLE
[Feature] 矩形视图能支持百分比吗？

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3144]
**请描述您的需求或者改进建议.**
矩形视图能支持百分比吗？
像饼状图一样，丰富标签{d}设置，或者其他形式实现。
![image](https://user-images.githubusercontent.com/82353425/191481445-a52f6c0d-aee2-4a5c-b9ea-f6cab34ba755.png)

**Comment by yayanpei** [comment]
感谢您的反馈，我们优化一下。
