### ISSUE TITLE
[Feature] 仪表板上方的新 tab 页预览展示不明显。

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3145]
**请描述您的需求或者改进建议.**
右上方的按钮这种看起来不明显，有没有考虑转成文字或者
界面UI 变化呢。
![image](https://user-images.githubusercontent.com/82353425/191481886-d398b1af-9a35-44b8-833b-b6b3a9fc128b.png)

**Comment by yayanpei** [comment]
感谢反馈，仪表板UI交互的优化目前已经在规划中，可以关注下我们的release note
