### ISSUE TITLE
[Feature] ECharts 与 AntV 视图的差异性。

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3146]
**请描述您的需求或者改进建议.**
ECharts 与 AntV 视图有一些不同的地方。例如我使用了 ECharts 是因为它支持列排序的功能，但是这种我又想设置阈值功能的话又没有。
所以对于 ECharts 支持的功能 与 AntV 支持的功能后续会不会整合出来，或者出其他视图避免这种情况。

![image](https://user-images.githubusercontent.com/82353425/191483212-f9660170-4694-41ce-90f9-a413c51d6440.png)

**Comment by yayanpei** [comment]
感觉反馈，echarts和antv的表格确实存在上述情况，表格功能在后期的迭代中会逐渐加强的，再次感谢您的关注和支持。
