### ISSUE TITLE
[Bug] 富文本的文本内容无法自适应

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3148]
**DataEase 版本**
1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.这个是显示器下的效果图。
![image](https://user-images.githubusercontent.com/82353425/191484531-de7e84cc-30f4-4887-bf73-630673890c29.png)

2.这个是笔记本的情况。
![image](https://user-images.githubusercontent.com/82353425/191484652-c0f6424b-9a82-4ce0-b4e1-026e26054239.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前富文本视图是不支持自适应的

**Comment by ywhfzy** [comment]
有没有考虑修复这个问题哇？

**Comment by yayanpei** [comment]
感谢反馈，我们先讨论看看。

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
