### ISSUE TITLE
[Question] 仪表板内的表格加载 Content Download 耗时过多。

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3155]
**请描述您的问题.**
如图所示，表格的 Content Download 耗时时间最长，而其他类型的视图较少。
表格视图名字：新建视图22，数据量 970W。
1.可以看到  Content Download 耗时了 9 秒。
![image](https://user-images.githubusercontent.com/82353425/191687551-dfb1e786-ee51-49ed-b2b4-10be96c6a64e.png)

2.这个是对应的请求 response
![image](https://user-images.githubusercontent.com/82353425/191687658-63bedb89-0387-4ba2-8c25-6567c0ce13bf.png)

3. 对比其他请求  Content Download 的时间
![image](https://user-images.githubusercontent.com/82353425/191686953-ea3b2ecb-df28-4eb6-96dd-f97a3dfd4dbd.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，你的这个表格应该是明细表吧，如果是明细表就没问题的。明细表是全量返回，而其他的表图是会集合处理的，所以明细表返回时间会根据请求的数据量产生大小变化
