### ISSUE TITLE
[Bug] AntV 表格阈值无法设置日期类型

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3159]
**DataEase 版本**
1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.直接将默认的【新冠疫情仪表板】的【全国现有确诊趋势】视图改成 AntV 的汇总表，然后将日期又文本改成时间类型。
![image](https://user-images.githubusercontent.com/82353425/191724733-25ecb1ec-e19e-44da-81a3-628c63d5b63a.png)

2.开始设置阈值，设置了新增确诊是可以的
![image](https://user-images.githubusercontent.com/82353425/191724650-26b9c46b-da12-41cf-b55f-c78477b996e0.png)

3.设置日期，是无效的
![image](https://user-images.githubusercontent.com/82353425/191724569-656c2b96-5960-4c76-bb30-030198fb1ed1.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，老哥。你这个显示的三十是去重计数.....阈值比对的是大于10的显示红色，这俩不是一个维度的东西的，而且汇总表是有聚合操作的，这个时候显示的数据并不是数据比对的数据的。
