### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#3160]
**DataEase 版本**
v1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
标准谷歌

**Bug 描述**

**Bug 重现步骤(有截图更好)**
MongoDB V4.4.13 直连模式，表名中带“-”同步失败
![83263e148e0853da42119f05d6e2858](https://user-images.githubusercontent.com/43403764/191882392-3f3834aa-dd99-4a8a-bec7-ae164800fa8f.jpg)

**Comment by BBchicken-9527** [comment]
感谢反馈，建议使用mongodb bi mongodb因为driver限制很多地方没有办法实现

**Comment by LinuxLeader** [comment]
我使用的就是MongoDB-BI

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快优化

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
