### ISSUE TITLE
[Bug]【组件】前面查询框结果还未出时切换查询条件，之后查询出来还是原来条件的结果

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3167]
**DataEase 版本**
1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准版本

**Bug 描述**
前面查询框结果还未出时切换查询条件，之后查询出来还是原来条件的结果。

**Bug 重现步骤(有截图更好)**
1.文本查询框选择值 A 点击查询；
2.在未出现结果的时候，切换成值 B 再次点查询；
3.等待出现的结果是之前 A 的结果。

**Comment by BBchicken-9527** [comment]
感谢反馈，想问一下你使用数据大概是多少条？

**Comment by AndroidBaby1** [comment]
40 W 的数据量，因为会因为数据查询慢，卡顿一下。在卡顿的时间里会切换其他的结果还是会显示第一次的查询结果。

**Comment by BBchicken-9527** [comment]
感谢反馈，我记录一下尽快优化
