### ISSUE TITLE
[Bug]【仪表盘】切换查询条件echarts表格出现字段丢失

### ISSUE THREAD

**Issue by lansyy** [dataease/dataease#3175]
**DataEase 版本**
1.12

**运行方式(安装包运行 or 源码运行 ?)**
源码运行
**浏览器版本**
103.0.5060.114（正式版本） （64 位）

**Bug 描述**
切换查询条件echarts表格出现字段丢失

**Bug 重现步骤(有截图更好)**
1.创建一个较宽的表格
2.滚动条拉到右边
3.切换查询条件
![image](https://user-images.githubusercontent.com/31096895/192180682-c9ed8595-b321-4a4f-9a85-d92cbc2fe659.png)

**Comment by xuwei-fit2cloud** [comment]
可以试试1.14版本，在线体验环境上并没有这个问题。

**Comment by lansyy** [comment]
你们线上版本也有复现的，在你们社区群里反馈过，
![1664160376429](https://user-images.githubusercontent.com/31096895/192183923-cf825691-3035-47e3-b167-36726a8fbfe7.png)

**Comment by xuwei-fit2cloud** [comment]
收到，我们排查处理一下。

**Comment by lansyy** [comment]
这个有解决么

**Comment by BBchicken-9527** [comment]
感谢反馈，目前我这边环境还是没有出现你相同的问题，所以还在排查，我想问一下就是你保存之后清除缓存显示还是这样吗

**Comment by lansyy** [comment]
![20220919195920](https://user-images.githubusercontent.com/31096895/196069757-21ca1428-cf26-4a5e-a974-4ce68e672595.gif)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们想办法复现一下，目前我们一直在想办法复现你说的这个问题，但是在我们的环境还没有出现过
