### ISSUE TITLE
建议[Feature]

### ISSUE THREAD

**Issue by fxy507707472** [dataease/dataease#3178]
1.轴线与标签的间隔量  当标签设置角度时且标签字体数量较多时时 标签字体会被轴体线和轴线上的柱状图遮挡
2.图表等跳转链接设置  外部链接情况下可否增加自定义打开事件，当dataease仪表盘处于iframe中时 点击图表字段以便打开新的iframe tab页而不是将仪表盘页面跳转到外部链接.（暴露jump方法 用户填充其中js事件而不仅仅是URL）

**Comment by yayanpei** [comment]
感谢反馈，我们先记录并讨论一下。
