### ISSUE TITLE
[Feature]创建 Excel 数据集合并表格提示是英文

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#3196]
**请描述您的需求或者改进建议.**
添加 Excel 数据集时，合并表格提示是英文，如下图：
<img width="1117" alt="图片" src="https://user-images.githubusercontent.com/48307752/192418030-3da1f497-30cd-4238-a744-c6191fcc4e49.png">

**Comment by yayanpei** [comment]
10月8日发布的版本中会优化该项，感谢您的关注和支持。
