### ISSUE TITLE
数据集编辑时和确认后展示的不一致

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#32]
编辑时预览有四条数据
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/48945409/123399513-452a0a00-d5d7-11eb-9538-853b0fbb0502.png">
保存后在外层看却只有一条数据
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/48945409/123399578-5ecb5180-d5d7-11eb-8f90-686f57d3ee74.png">

**Comment by xuwei-fit2cloud** [comment]
bug 已修复，请等待下一个版本发布

**Comment by xuwei-fit2cloud** [comment]
v1.0.1 已修复且已发布
