### ISSUE TITLE
[Bug]创建多sheet页的Excel数据集，表中数据格式有问题仍然会创建数据集，并且该数据集创建后提示无权限查看。

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#3205]
**DataEase 版本**
1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome

**Bug 描述**
创建Excel数据集，如果多sheet页中有一个sheet数据格式有问题，提示报错后，仍然创建数据集，并且该数据集创建后提示无权限查看。

**Bug 重现步骤(有截图更好)**
1. 多 sheet 页的 Excel ，有一个sheet 数据格式存在错误，会导致报错；

<img width="1474" alt="图片" src="https://user-images.githubusercontent.com/48307752/192467061-01426919-72a8-404a-b0b1-987a9eb25c13.png">

2. 报错之后不再继续操作，刷新几遍浏览器（2-3遍），数据集出现了报错的数据集名称，点击该数据集名称有权限错误
<img width="1475" alt="图片" src="https://user-images.githubusercontent.com/48307752/192467281-be13c1b4-9cc4-4923-a53d-d75b4b08eb4e.png">

3.删除该数据集，提示没有权限，需要用admin账户才可以删除
希望检测 Excel 格式不对，报错后不创建数据集

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，问题确认，我们尽快修复。

**Comment by zhuliuyi** [comment]
请问这个bug在dev分支修复了吗

**Comment by xuwei-fit2cloud** [comment]
v1.15.0版本已发布，请更新版本。
@zhuliuyi dev分支也做了修复。
