### ISSUE TITLE
[Feature]业务数据库定期生成新表， DataEase 针对这种场景有没有解决方案？

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#3207]
**请描述您的需求或者改进建议.**
为了优化数据库性能，避免单表数据过大，每个月会生成一个新表，表中字段都一样。
 DataEase 针对这种场景有没有合适的方案？

**Comment by xuwei-fit2cloud** [comment]
数据量过大的情况下，我们也不推荐使用SQL数据集的UNION来把多个表合并。
目前还没有特别合适的方案可以解决这个问题，我们内部再讨论一下。
