### ISSUE TITLE
[Question] 编译打包 frontend  错误

### ISSUE THREAD

**Issue by mouse-dg** [dataease/dataease#3209]
DataEase 版本
1.14.0

运行方式(安装包运行 or 源码运行 ?)
源码编译
Node.js v16.17.0.

问题 描述
编译出现问题如下：

PS D:\dataease\frontend> npm run build:stage

> dataease@1.14.0 build:stage
> vue-cli-service build --mode staging

\  Building for staging...Deprecation Warning: As of Dart Sass 2.0.0, !global assignments won't be able to declare new variables.

Recommendation: add `$B: null` at the stylesheet root.

   ╷
81 │   $B: $namespace + "-" + $block !global;
   │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    stdin 81:3   b()
    stdin 154:1  root stylesheet

D:\dataease\frontend\node_modules\neo-async\async.js:16
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (D:\dataease\frontend\node_modules\neo-async\async.js:16:11)
    at D:\dataease\frontend\node_modules\neo-async\async.js:2818:7
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by xuwei-fit2cloud** [comment]
你好，是不是代码在编译的时候引入了一些自己的css？
如果是的话，可以试试把 module.exports = { css: { extract: false } } 加到 vue.config.js 里看看。
参考：
https://stackoverflow.com/questions/68538778/getting-throw-new-errorcallback-was-already-called

**Comment by mouse-dg** [comment]
把 module.exports = { css: { extract: false } } 加到 vue.config.js 里，也是同样错误。

**Comment by xuwei-fit2cloud** [comment]
你好，工程里的代码在编译时并没有发现上述问题，如果是有自己的css的话，可以加一下我们的社区交流群，在群里找我们的技术支持同事帮忙看看具体问题。
