### ISSUE TITLE
[Feature]文本过滤组件->文本搜索,支持SQL 数据集的传参

### ISSUE THREAD

**Issue by xlostway** [dataease/dataease#3210]
**请描述您的需求或者改进建议.**
有这样的需求:
select sum(job_title) from (select job_title from table where job_title like '${job_title}%') t1
需要在"文本搜索"组件中输入'大数据'替换sql数据集子查询中的变量${job_title},并且查询的结果字段中没有job_title这个字段

**Comment by xlostway** [comment]
你好，我是谢晋峰，你的邮件我已经收到，谢谢！

**Comment by wikimo** [comment]
+1

**Comment by xlostway** [comment]
你好，我是谢晋峰，你的邮件我已经收到，谢谢！
