### ISSUE TITLE
[Bug] 增量同步表达式设置问题

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3218]
**DataEase 版本**
1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.选择增量同步，添加表达式，保存之后表达式重置了。
2.
![d893dccaddc6ba181da7104cd943d55](https://user-images.githubusercontent.com/82353425/192496715-53a638fb-987b-4611-af0e-4da91b93f1bc.png)

3.
![04d7157cd8912fc6d9fb87f24cec135](https://user-images.githubusercontent.com/82353425/192496742-415ce15d-3567-40d3-850d-77c468a99438.png)

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请等待新版本发布。
