### ISSUE TITLE
[Bug] 仪表板-数据集字段管理修改字段名后，仪表板未实时更新或者有提示

### ISSUE THREAD

**Issue by zhuliuyi** [dataease/dataease#3223]
**DataEase 版本**
1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
仪表板-数据集字段管理修改字段名后，仪表板未实时更新或有提示

**Bug 重现步骤(有截图更好)**
1.在仪表盘编辑界面，点击数据集字段管理，更改字段名
![image](https://user-images.githubusercontent.com/92585563/192666372-87c916d5-a445-41ae-ae7e-96fad84cf10f.png)

2.更改字段名
![image](https://user-images.githubusercontent.com/92585563/192666644-3d1c5490-4dd1-49ea-8f8d-1f727caa6b70.png)

3.在维度里面已经更新，但图中所标注的位置没有实时更新，或者有提示提醒字段名发生变化，需要删除过后在添加才能更新
![image](https://user-images.githubusercontent.com/92585563/192666833-40ef1b73-45ce-4b39-b390-505722620e43.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈问题。
如果是想设置字段在视图中的显示，可以参考下图：
![图片](https://user-images.githubusercontent.com/1892127/192675853-1346d506-1814-474a-8616-0d4a6e67db46.png)
字段管理那里的设置，最初的目的仅是改变其在维度和指标栏的显示，并没有希望影响在视图里的显示。
我们内部再讨论一下，这个地方是否需要优化。
