### ISSUE TITLE
[Bug]复制 “富文本” 视图过多时，编辑富文本视图字段，就会报错 “标题不能大于50个字符”

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#3240]
**DataEase 版本**
1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
复制 “富文本” 视图过多时，编辑富文本视图字段，就会报错“标题不能大于50个字符”

**Bug 重现步骤(有截图更好)**
1. 复制“富文本”视图
2.编辑最后复制的富文本视图
3.出现报错提示，并没有修改标题的地方
<img width="1470" alt="图片" src="https://user-images.githubusercontent.com/48307752/192741164-26320f96-90f3-48fc-bea0-abf036c7f16d.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
问题已修复，将会在下个版本更新；到时候可以下载体验，感谢关注。
