### ISSUE TITLE
[Feature]图表不显示标题、横轴和纵轴、图例等内容时能够图片显示内容最大化

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#325]
**请描述您的需求或者改进建议.**
图表不显示标题、横轴和纵轴、图例等内容时能够图片显示内容最大化

不然每次设计的图总汇发现图表聚集在一个很小的区域，但是仪表盘中的图表大小有很大，周边都是空白，很影响布局
![image](https://user-images.githubusercontent.com/60059766/126894646-232f93e8-f1bb-4d11-8d26-5962292101da.png)

**Comment by yayanpei** [comment]
您的建议很不错，我们会考虑加入到之后的版本迭代中，感谢反馈。

**Comment by xuwei-fit2cloud** [comment]
v1.4.0 版本增加了antV图库的支持，对显示区域的控制会更好一些。
