### ISSUE TITLE
[Feature]可以复制富文本视图中的内容

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#3252]
**请描述您的需求或者改进建议.**
目前无法复制富文本中的内容
希望可以在视图展示界面可以做一个类似其他视图的“导出数据”的功能。

**Comment by xuwei-fit2cloud** [comment]
富文本视图比较特别，里面包含的内容有很多与数据本身无关。
如果要支持导出的话，只能限于展示数据的导出，其他富文本内容无法导出。
不知道这个是不是满足需求。

**Comment by mfanoffice** [comment]
展示数据的导出是可以的

**Comment by yayanpei** [comment]
感谢反馈，您的需求我们已收到。
