### ISSUE TITLE
[Feature]支持更多的预设大屏样式和图表样式

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#326]
**请描述您的需求或者改进建议.**
支持更多的预设大屏样式和图表样式
自己配色太难了

![image](https://user-images.githubusercontent.com/60059766/126894676-ab525eb0-7e47-47ff-8b27-f5fbe5a12127.png)

**Comment by yayanpei** [comment]
非常感谢您的反馈，您的建议是我们产品改进和优化的方向

**Comment by xuwei-fit2cloud** [comment]
近期版本还不会对这部分进行改进
