### ISSUE TITLE
[Bug] 仪表板网页组件导出PDF 显示的是空白

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3260]
**DataEase 版本**
1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.如何在仪表板上显示
![image](https://user-images.githubusercontent.com/82353425/192970306-090c6bee-1ec6-45bf-88e8-2af9d7468a11.png)

2.点击导出 PDF 之后
![image](https://user-images.githubusercontent.com/82353425/192970438-a0775e87-1a6e-488a-aa75-d81ec08e6a38.png)

**Comment by xuwei-fit2cloud** [comment]
目前网页组件导出时确实是空白，暂时还不会调整。
