### ISSUE TITLE
[Feature] 视图【明细表】组件中的列，仅展示和下载通过外部参数传递的列

### ISSUE THREAD

**Issue by shuiyouzhi** [dataease/dataease#3261]
DE您好, 以下是需求说明，望采纳排期：
需求说明: 仪表板 -> 视图 -> 明细表, 【明细表】组件中的列，允许通过外部参数的数据传递，显示与下载所传递的列。
比如，外部参数设置 中传递了 accounts_name 列，那么公共报表仅显示此列。
如图
<img width="1436" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/12723715/192971449-df2324d0-1cce-4ddb-b153-784a5095fb85.png">

**Comment by yayanpei** [comment]
感谢反馈，我们先记录并讨论一下。
