### ISSUE TITLE
[Bug] Emoji 表情等符号数据导入失败

### ISSUE THREAD

**Issue by zhicheng-ning** [dataease/dataease#3287]
**DataEase 版本**
v1.14.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 版本 105.0.5195.127（正式版本） （64 位）

**Bug 描述**
导入 Excel 数据集时，如果 Excel 数据集中存在 Emoji 表情等符号，则无法导入成功（插入数据库失败）

**Bug 重现步骤(有截图更好)**
1.导入 Excel 数据集
2. 数据集中存在 emoji 表情![image](https://user-images.githubusercontent.com/39022409/193270616-fe54613c-88fc-4539-9516-d0cf6af42e42.png)
3. 插入失败
![image](https://user-images.githubusercontent.com/39022409/193270398-a9f51a5d-64fa-4a7c-8fc4-e3b4445c4358.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前是不支持Emoji的导入你的需求我已经记录了，我们仔细商讨一下是否有必要进行Emoji的导入

**Comment by zhicheng-ning** [comment]
> 感谢反馈，目前是不支持Emoji的导入你的需求我已经记录了，我们仔细商讨一下是否有必要进行Emoji的导入

是否可以通过修改一些数据库配置来支持该字符编码

**Comment by BBchicken-9527** [comment]
目前暂时不考虑的，是这样的，主要我们需要考虑如果支持了Emoji导入的话那如何兼容图表的现实以及过滤的实现，如果单纯的家这一个功能其实不麻烦，主要后续的一系列需要考虑，我们需要一起开会商量一下，希望你可以理解

**Comment by zhicheng-ning** [comment]
好的，谢谢
