### ISSUE TITLE
[Feature]AntV可以支持自定义标签和提示，ECharts可以支持设置数值格式

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#3297]
饼图拖进一个指标，选 AntV 可以设置指标的数值格式，在样式设置中无法自定义标签文字和提示文字；选 ECharts 可以在样式设置中无法自定义标签文字和提示文字， 而不能设置指标的数值格式。

期望：
AntV 可以支持自定义标签和提示（像 ECharts 那样）。
ECharts 可以支持设置数值格式（像 AntV那样）。
![image](https://user-images.githubusercontent.com/89771514/194686213-a88f8b77-b0ee-4339-bff1-13da3f9f0332.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个需求已经在需求池中，我们后续版本会做相关开发安排。
