### ISSUE TITLE
向优秀的开源项目MeterSphere学习：数据库源信息录入增加超时时间，否则数据量太大会报超时

### ISSUE THREAD

**Issue by luty2018** [dataease/dataease#33]
![image](https://user-images.githubusercontent.com/36292514/123399708-84585b00-d5d7-11eb-82fb-a4017e1bbf91.png)
![image](https://user-images.githubusercontent.com/36292514/123399788-9f2acf80-d5d7-11eb-8aa8-87c1e54ab290.png)

**Comment by chixq** [comment]
Respect!

**Comment by yayanpei** [comment]
感谢您的反馈，您的建议是我们产品改进的方向

**Comment by xuwei-fit2cloud** [comment]
v1.2.0 版本已向优秀开源项目 MeterSphere 学习，加上了对连接参数的支持。
