### ISSUE TITLE
[Bug]SQL数据集添加日期参数，sql中包含union联合查询时异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#3302]
**DataEase 版本**
v1.15.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
Google 版本 105.0.5195.125（正式版本） (x86_64)

**Bug 描述**
添加sql数据集，数据集中添加日期参数，当sql中含有 UNION 时，预览数据无数据，且F12查看控制台调用接口未返回异常，点击保存按钮抛出异常，见截图
![image](https://user-images.githubusercontent.com/89771514/194698008-f4bad0d0-91bb-4514-93fe-c5262bb05a16.png)

当去掉 UNION 时，预览数据也没有数据，点击保存按钮保存成功，见截图
![image](https://user-images.githubusercontent.com/89771514/194698007-7c3dda23-fed8-4496-a265-6d7d45e32eba.png)

sql脚本：
`select t.title,sum(t.curPv) growthPv,t.user,t.created_time,t.publish_time from (
		select answer1.pv-answer2.pv as curPv,answer1.title,answer1.user,answer1.`created_time`,answer1.publish_time from t_zhihu_answer  answer1
			JOIN t_zhihu_answer answer2 on DATE_FORMAT(answer2.`created_time`,"%Y-%m-%d") = DATE_SUB(DATE_FORMAT(answer1.`created_time`,"%Y-%m-%d"),INTERVAL 1 DAY)
			and answer1.title = answer2.title
			and answer1.user = answer2.user
		UNION
		select article1.pv-article2.pv as curPv,article1.title,article1.user,article1.`created_time`,article1.publish_time from t_zhihu_article  article1
			JOIN t_zhihu_article article2 on DATE_FORMAT(article2.`created_time`,"%Y-%m-%d") = DATE_SUB(DATE_FORMAT(article1.`created_time`,"%Y-%m-%d"),INTERVAL 1 DAY)
			and article1.title = article2.title
			and article1.user = article2.user
	) t
	WHERE t.publish_time>'2022' and DATE_FORMAT(t.`created_time`,"%Y-%m-%d" )= ${parm_name1} 
	GROUP BY t.title`

**Comment by BBchicken-9527** [comment]
感谢反馈，提示的异常应该是你的语句有问题，报错信息我们是直接抓取driver的你看一下你的这个语句能不能从命令行或navicat等工具中运行呢

**Comment by ZhaoQian1222** [comment]
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/89771514/194733262-6a00f12b-299a-4876-adc4-757e45730523.png">

navicat中运行没有问题，见截图

**Comment by BBchicken-9527** [comment]
哦，你看看再de的变量两侧加上'应该就没问题了

**Comment by ZhaoQian1222** [comment]
![image](https://user-images.githubusercontent.com/89771514/194740288-2e275ba5-9f19-4c3a-9bc6-5be0e02083fc.png)

建议优化示例

**Comment by BBchicken-9527** [comment]
嗯嗯，好的，我们优化一下这个例子
