### ISSUE TITLE
[Bug]新建的仪表板中复用已存在的仪表板中的视图，复用后直接修改影响的是已存在的仪表板中的视图

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#3305]
**DataEase 版本**
v1.15.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome 版本 105.0.5195.125（正式版本） (x86_64)

**Bug 描述**
新建的仪表板中复用已存在的仪表板中的视图，复用后直接修改影响的是已存在的仪表板中的视图，而新建的仪表板中的视图没有变化

**Bug 重现步骤(有截图更好)**
1.新建的仪表板
2.复用已存在的仪表板中的视图
![WechatIMG264](https://user-images.githubusercontent.com/89771514/194733782-4cd3ccfe-8cac-4537-838c-c1dc07cf63e9.png)

3.直接编辑修改，发现新建的这个仪表板中的视图没有任何变化
4.点击保存，然后到被引用的仪表板查看视图，发现原视图发生了变化

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
