### ISSUE TITLE
[Bug]Echatrs气泡图标签和提示设置内容格式不符合预期

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#3306]
**DataEase 版本**
v1.15.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome 版本 105.0.5195.125（正式版本） (x86_64)

**Bug 描述**
Echarts的气泡图，设置标签的内容格式，设置{c}，显示错误，见截图
![image](https://user-images.githubusercontent.com/89771514/194734085-150a1220-882a-4826-81b3-5e8b8ff162b9.png)

设置提示的内容格式也存在同样的问题

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，echarts的标准气泡图就是这样显示的，目前我们正在想办法优化
