### ISSUE TITLE
[Feature]阈值设置中针对单个字段设置多个阈值表达式时，实际是或的关系，建议优化提示信息

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#3308]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/89771514/194734522-255fc7d9-269c-4523-916c-3e8d4acff192.png)

**Comment by xuwei-fit2cloud** [comment]
阈值部分并不是或的关系，而是按照规则顺序判断，当满足其中一条规则后，就按这条规则执行，后面的规则不再判断。

**Comment by ZhaoQian1222** [comment]
截图中显示：满足 20<=值<=100和 值=584 的数据都变成了红色，那就说明现有的提示信息与实际生效的效果不一致

**Comment by xuwei-fit2cloud** [comment]
文案的意思是不要重复选择同一个字段，而你截图里的用法是在一个字段下的多条规则，并没有问题。
