### ISSUE TITLE
[Bug]AntV明细表视图，下钻区域文字与背景存在遮挡

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#3309]
**DataEase 版本**
v1.15.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome 版本 105.0.5195.125（正式版本） (x86_64)

**Bug 描述**
AntV明细表视图，下钻区域文字与背景存在遮挡，见截图
![image](https://user-images.githubusercontent.com/89771514/194735822-cef5dccc-b05b-483d-955c-5f56952849c7.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
