### ISSUE TITLE
[Bug]AntV基础折线图过滤器过滤单元格不为空不生效（单元格为空白单元格）

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#3313]
**DataEase 版本**
V1.15版本

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器版本 105.0.5195.125（正式版本） (x86_64)

**Bug 描述**
AntV基础折线图过滤器过滤不为空不生效，单元格为空时，去重计数无法过滤成功，依然展示单元格为空的数据；
将空单元格置换为’空‘字时，可以过滤成功

**Bug 重现步骤(有截图更好)**
1.
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/70566485/194747034-a34cfc7b-5255-4dd1-af7c-3abb199c9bf8.png">
2.
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/70566485/194747069-38f516cf-4bb5-470a-8d4f-ecbf4a65c8a7.png">
3.
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/70566485/194747096-0a7dc45d-702b-4763-b99e-01aeba5fc231.png">

可私聊提供Excel表格

**Comment by BBchicken-9527** [comment]
感谢反馈，你这个数据是用的excel吗，如果数据源来自excel导入的话空过滤不出来是正常的，因为导入进去之后属于空字符串，并不是真正意义上的null的，这个为空不为空过滤的是数据库中为null的数据

**Comment by xiebei-l** [comment]
> 感谢反馈，你这个数据是用的excel吗，如果数据源来自excel导入的话空过滤不出来是正常的，因为导入进去之后属于空字符串，并不是真正意义上的null的，这个为空不为空过滤的是数据库中为null的数据

好的明白了，建议支持Excel的空哈

**Comment by BBchicken-9527** [comment]
好的我这边记录一下具体是否支持我们商讨一下
