### ISSUE TITLE
[Bug]气泡地图无法显示其他国家的数据

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#3316]
**DataEase 版本**
1.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome

**Bug 描述**
地图可以显示其他国家的数据，切换为气泡地图后显示空白，无报错。

**Bug 重现步骤(有截图更好)**
1. 使用地图，选择 俄罗斯 后，可以正常显示
<img width="979" alt="图片" src="https://user-images.githubusercontent.com/48307752/194790259-d23f8fab-8d90-4e06-aa36-e037da27af6d.png">

2. 切换为 气泡地图 则没有显示
<img width="1011" alt="图片" src="https://user-images.githubusercontent.com/48307752/194790341-90666042-a516-479b-9241-9d0101df1032.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，因为目前自带的俄罗斯地图缺少气泡地图需要的center和centroid导致的，如果你有文件的话可以自己上传也可以等待下个版本；我们会统一更新目前现有的地图文件
