### ISSUE TITLE
[Feature]建议在Excel 数据集创建页面左右滚动时只滚动表格而不是整个页面

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#3318]
**请描述您的需求或者改进建议.**
如图，在 Excel 数据集添加页面上传 Excel 后，如果列过多，左右滚动时会滚动整个页面。
期望只滚动查看表格就可以，这样我可以同时看到上方的按钮和左侧的选择数据表区域。
![image](https://user-images.githubusercontent.com/30886198/194979036-e16d3617-fcec-4c1d-9737-8faac0d4dd84.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们近期版本会做优化。

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
