### ISSUE TITLE
[Feature]柱状图标签支持滚动设置

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#3319]
**请描述您的需求或者改进建议.**
当使用柱状图时，有的标签可能很长，这时候视图就无法很好的展示标签的内容，即使调整标签的角度也无法完整的展示，如图中所示
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/89771514/194981586-37d65666-5e26-455a-ae7f-023f10320fd2.png">

建议：柱状图的标签支持设置标签滚动展示，且支持滚动标签的展示区域的滚动宽度

**Comment by xuwei-fit2cloud** [comment]
建议：
1. 精简标签内容
2. 调整显示角度
3. 加大视图宽度
4. 更换视图类型

我们不建议支持标签的滚动显示。
