### ISSUE TITLE
[Bug]Excel 文件中包含空值时会将字段识别为文本类型，实际是数字类型

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#3321]
**DataEase 版本**
V1.15.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
最新版本 Edge

**Bug 描述**
创建 Excel 数据集时，若 Excel 文件中有一个单元格为空，即使此列全部是数字类型数据，也会被自动识别为文本类型。

**Bug 重现步骤(有截图更好)**
1. 创建 Excel 数据集
2. Excel 文件中全部写数字类型数据，其中有一个或多个单元格的数据为空
3. 上传 Excel 后，无数据的单元格所在列会被识别为文本类型
4. 期望忽略空数据，自动识别为数字(小数)类型
![image](https://user-images.githubusercontent.com/30886198/195008853-f47bcdbe-955c-4a94-a52a-520e2030b05d.png)
![image](https://user-images.githubusercontent.com/30886198/195008973-db7a4588-e07b-401c-90ad-ed565f0c61a6.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，因为空表格进入数据库为空字符串“”所以识别列为string类型

**Comment by liuboF2c** [comment]
> 感谢反馈，因为空表格进入数据库为空字符串“”所以识别列为string类型

在这一列全都是数字的情况下，如果有空单元格是否应该以 NULL 值存入，而不是空字符串？

**Comment by BBchicken-9527** [comment]
表格数据存放到doris中而抓去数据是kettle完成的，这里我们的操作空间并不大，我们也会商讨一下收否有更好的解决方法
