### ISSUE TITLE
[Bug] 定时报告发送仪表板视图不全

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3323]
**DataEase 版本**
1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.原本仪表板如图，需要往下拉才能看到全部
![image](https://user-images.githubusercontent.com/82353425/195013168-903df906-ef6d-46b5-9cac-3278281de4f9.png)

2.定时报告的设置选择了所有视图，邮件上收到的图片如图，只能截图到默认点开仪表板查看到视图情况。
![6807ea40e8fcd05695d604551cd87df](https://user-images.githubusercontent.com/82353425/195013395-f403ad7d-4059-4913-ae9d-4bd28b33aeb8.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，此处修复存在难度，我们正在努力解决此问题

**Comment by xuwei-fit2cloud** [comment]
v1.15.3版本已修复，请更新版本。
