### ISSUE TITLE
[Bug]【API数据源添加时候预览数据与添加数据集数据不一致】

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#3324]
**DataEase 版本**
V1.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器版本 105.0.5195.125（正式版本） (x86_64)

**Bug 描述**
API数据源添加时候预览数据与添加数据集数据不一致

**Bug 重现步骤(有截图更好)**
1.API数据源：测试Bug
2.添加API数据集
查看两边数据不一致
![image](https://user-images.githubusercontent.com/70566485/195020145-af2fc1d3-0da7-4394-a748-6d9b1bf82ff8.png)
![image](https://user-images.githubusercontent.com/70566485/195020173-a3a431af-85c3-4d79-b8ed-db6b562b8946.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，这里我们想办法优化一下
