### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by tzengshinfu** [dataease/dataease#3325]
**请描述您的问题.**
您好：
请问有计划支援表格视图的自定公式改变栏位格式(字体大小/背景颜色等)的功能，或是此功能在X-Pack方案里？
(如下图示意)
![image](https://user-images.githubusercontent.com/2170033/195019677-81a04ea3-51f4-436c-b33d-5f8f00b82a7b.png)

**Comment by yayanpei** [comment]
感谢反馈，建议您在高级设置中通过设置阈值来改变单元格的颜色，该功能社区版本中也是有的，可以参考在线文档：https://dataease.io/docs/user_manual/view_module/view_design/?h=%E9%98%88%E5%80%BC#43

**Comment by tzengshinfu** [comment]
谢谢回覆，我先将进度的正常/延迟改成量化指标，这样就能设定各区间的阈值。
