### ISSUE TITLE
[Bug] SQL数据集添加参数控制

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3330]
**DataEase 版本**
v1.15.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
添加SQL数据集时，参数添加在join后添加、预览失败。此时去设置下参数，可以预览并且添加成功

**Bug 重现步骤(有截图更好)**
1.添加SQL数据集，编写SQL，预览、保存均失败
<img width="1467" alt="image" src="https://user-images.githubusercontent.com/45852479/195050206-1eafb8f7-ca39-4ffc-b7a5-1ee224853836.png">

2.配置添加‘参数设置’
<img width="686" alt="image" src="https://user-images.githubusercontent.com/45852479/195049824-64b6f695-4d36-41bb-93b3-b42bd48f190c.png">

3.预览，保存
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/45852479/195049999-897b85cb-a96c-4b6a-9653-7900c79c224f.png">
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/45852479/195050341-2a3591a8-9c4a-4100-9943-218ff0c79848.png">

**Comment by BBchicken-9527** [comment]
问题已修复，可以下载新版本体验，感谢支持

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
