### ISSUE TITLE
[Bug]使用数据集使用权限的用户查看数据集字段管理时样式错误

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3331]
**DataEase 版本**
v1.15.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 105

**Bug 描述**
只用数据集使用权限的用户查看数据集字段管理时样式错误，搜索框位置不正确。

**Bug 重现步骤(有截图更好)**
1.使用有管理权限的用户查看数据集，搜索框正确位置如下，位于右侧。
![image](https://user-images.githubusercontent.com/48945409/195062040-f48c5d99-a4b6-492d-87fe-64b048e9c342.png)
2.使用只有对该数据集有使用权限的用户查看该数据集。
![image](https://user-images.githubusercontent.com/48945409/195062236-da988b86-0ca1-4276-aa55-9eb5fb33c0d9.png)
搜索框位置位于中间。
![image](https://user-images.githubusercontent.com/48945409/195061788-4c5c9126-3354-4eb1-a80b-695d4fff5987.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快处理

**Comment by BBchicken-9527** [comment]
问题已经修复，可以下载最新版本体验，感谢支持

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
