### ISSUE TITLE
[Bug]数据集计算字段表达式过长未换行时系统样式错乱

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3332]
**DataEase 版本**
v1.15.1

**运行方式(安装包运行 or 源码运行 ?)**
安装部

**浏览器版本**
Chrome 105

**Bug 描述**
数据集计算字段表达式过长未换行时，弹框右侧两栏的样式错乱，被挤压。

**Bug 重现步骤(有截图更好)**
表达式过长时，输入框被拉宽，右侧两栏被挤压。
![image](https://user-images.githubusercontent.com/48945409/195063918-555ba4ab-5d35-4c47-8027-d053ff45f6d4.png)

给表达式换行或缩短表达式恢复。
![image](https://user-images.githubusercontent.com/48945409/195063852-4f9a31e7-5e6a-41ca-b9c3-a41bace275f7.png)
![image](https://user-images.githubusercontent.com/48945409/195064110-d04063fb-dcf1-4100-af87-230f38dcc111.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
