### ISSUE TITLE
[Bug]插件管理中更新x-pack插件异常，导致系统企业版功能无法使用，重新导入lincense依旧无法使用企业版功能

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#3333]
**DataEase 版本**
v1.15.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome 版本 105.0.5195.125（正式版本） (x86_64)

**Bug 描述**
见截图
![iShot_2022-10-11_18 54 59](https://user-images.githubusercontent.com/89771514/195072198-935a2e16-2e12-4d3e-9fa4-59752723bdb6.png)

![iShot_2022-10-11_18 53 44](https://user-images.githubusercontent.com/89771514/195072075-eb755de1-733e-40e8-97ac-a354c0268ffb.png)

更新的文件：[plugin.zip](https://github.com/dataease/dataease/files/9754336/plugin.zip)

目前临时的解决方案：
1、手动插入原先的x-pack插件的数据到 my_plugin 表中
2、重启dataeasea容器 docker restart dataease
3、再次用这个zip包更新x-pack的插件
4、刷新浏览器之后就恢复了

建议：
1、内置的插件不允许手动更新
2、修复代码中存在的bug

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
