### ISSUE TITLE
[Bug] 添加数据源时，PostgreSQL 图标不正确，使用了 Presto 的图标

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#3334]
**DataEase 版本**
v1.15.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome
版本 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
添加数据源时，PostgreSQL 图标不正确，使用了 Presto 的图标
如下图所示：
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/30063018/195229431-60785778-e77b-4144-9fac-04b4bc140b82.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
