### ISSUE TITLE
[Bug] AntV横向堆叠图针对指标排序无效

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3335]
DataEase 版本
v1.15.1

运行方式(安装包运行 or 源码运行 ?)
安装包

浏览器版本
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
AntV横向堆叠图针对指标排序无效

**Bug 重现步骤(有截图更好)**
新建AntV横向堆叠图，拖入相关字段，对指标‘成绩’进行升序，结果并未升序（无论是总和还是某一个堆叠项）
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/45852479/195229993-bc4340d2-4d20-4e43-85bc-d76edfeb7770.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，其实是排序了的，你现在看到的这个效果是因为存在两个维度导致的。你把维度替换成科目就看出来的
