### ISSUE TITLE
[Bug] AntV 透视表的数据行没有自定义排序

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3337]
**DataEase 版本**
1.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1透视表.数据行没有自定义排序
![image](https://user-images.githubusercontent.com/82353425/195235914-447539be-96e9-4cdd-be80-94f0fc925588.png)

2.透视表数据列有自定义排序
![image](https://user-images.githubusercontent.com/82353425/195235999-b04362ae-2e3d-4c37-bfe9-b9345852049c.png)

**Comment by BBchicken-9527** [comment]
目前数据行维度的自定义排序还不支持的，我这边会记录你的需求，感谢支持
