### ISSUE TITLE
[Feature] AntV 的表格能不能支持多列排序

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3338]
**请描述您的需求或者改进建议.**
例如如图，我想先对人进行排序，排序完毕之后再对优先级排序。
![img_v2_a486c27f-3293-475b-8cf0-ec45f647805h](https://user-images.githubusercontent.com/82353425/195236147-f0f2cb21-b41b-4f4e-8b0b-ec5605093de0.jpg)

例如首先按照人物排序，A-》B
![image](https://user-images.githubusercontent.com/82353425/195236412-ca7e94a2-5394-4ed7-a8d9-aef1c9b47b11.png)

然后我再按照优先级排序
![image](https://user-images.githubusercontent.com/82353425/195236544-4bdb27af-6c2e-43ca-8ecf-db3494ce6eb6.png)

**Comment by xuwei-fit2cloud** [comment]
先对人进行排序，排序完毕之后再对优先级排序
可以把人这一列放在优先级这一列前面

**Comment by ywhfzy** [comment]
> 先对人进行排序，排序完毕之后再对优先级排序 可以把人这一列放在优先级这一列前面

🐮

**Comment by xuwei-fit2cloud** [comment]
排序的优先顺序，是按照字段的顺序来的。
