### ISSUE TITLE
[Bug]视图插件开发示例按文档操作异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#3339]
**DataEase 版本**
v1.15

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**Bug 描述**
拉取项目dataease-extensions，未改动任何代码，按文档操作，执行到 npm i 异常
![image](https://user-images.githubusercontent.com/89771514/195266464-b03a841f-b6d0-429f-82fd-953cdf63fdf4.png)

![image](https://user-images.githubusercontent.com/89771514/195266933-494f164d-f806-48bf-9760-ad3988f08a24.png)

**Comment by xuwei-fit2cloud** [comment]
忽略npm i，执行 npm run dev即可。
我们会调整相关文档。

**Comment by ZhaoQian1222** [comment]
根目录下执行：mvn clean install 成功后
然后直接执行 npm run dev 还是报异常，见截图
![image](https://user-images.githubusercontent.com/89771514/195287149-6255b803-1b16-42e3-8c0e-c89749da48b4.png)

**Comment by Houtaroy** [comment]
原因是`webpack-dev-server`和`webpack`版本冲突

**Comment by maninhill** [comment]
直接提交 pr 解决。

**Comment by Houtaroy** [comment]
已提交pr: https://github.com/dataease/dataease-extensions/pull/42
@maninhill

**Comment by yuandajn578** [comment]
package.json中需要修改webpack相关的版本，1.18.8版本修改为：
"webpack": "^4.46.0",
"webpack-cli": "^3.2.3",
"webpack-dev-server": "^3.1.11"
之后运行  npm install --registry=https://registry.npmmirror.com
npm run dev
