### ISSUE TITLE
[Question]maven仓库缺少v1.15.0对应的包

### ISSUE THREAD

**Issue by nigel001** [dataease/dataease#3345]
maven仓库缺少v1.15.0对应的包
`<dependency>
            <groupId>io.dataease</groupId>
            <artifactId>dataease-plugin-interface</artifactId>
            <version>1.15.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>guava</artifactId>
                    <groupId>com.google.guava</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.dataease</groupId>
            <artifactId>dataease-plugin-view</artifactId>
            <version>1.15.0</version>
        </dependency>
        <dependency>
            <groupId>io.dataease</groupId>
            <artifactId>dataease-plugin-datasource</artifactId>
            <version>1.15.0</version>
        </dependency>
`

**Comment by xuwei-fit2cloud** [comment]
DataEase在发布版本的时候，会将对应的SDK依赖上传到Maven中央仓库，见下图：
![图片](https://user-images.githubusercontent.com/1892127/195485760-0c656495-f008-4360-bb5f-bc1c9eee529d.png)

如果不能正常下载，可以通过修改Maven settings.xml文件中的proxy、mirror等设置处理一下。
如果还是不能正常下载，也可以下载[SDK](https://github.com/dataease/dataease-extension-sdk)对应的工程代码，在本地执行mvn clean install即可。
