### ISSUE TITLE
[Bug] 定时同步的SQL数据集，参数设置未隐藏，可以进行点击，需要进行隐藏

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#3346]
**DataEase 版本**
v1.15.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome
版本 106.0.5249.119（正式版本） (arm64)

**Bug 描述**
定时同步的SQL数据集，参数设置未隐藏，可以进行点击
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/30063018/195307712-3fa166b3-b43e-4d70-bb4e-161a0a40a277.png">
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/30063018/195308071-bca4253d-22e1-45c0-a99e-e0e00723e1e5.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快优化

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
