### ISSUE TITLE
[Bug] Hive数据源配置指标卡超时

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3347]
DataEase 版本
v1.15.1

运行方式(安装包运行 or 源码运行 ?)
安装包运行

浏览器版本
Chrome
版本 106.0.5249.119（正式版本） (arm64)

**Bug 描述**
Hive数据源数据量过大时（14w），仪表板加载指标卡超时

**Bug 重现步骤(有截图更好)**
![wecom-temp-18953-a2d3091fcb1598efc0ebac3e539d2971](https://user-images.githubusercontent.com/45852479/195519906-c2343662-4665-4839-b660-075cde3f8e1d.jpg)

**Comment by BBchicken-9527** [comment]
感谢反馈，因为超时请求的原因种类较多，建议你设置一下数据源的超时时间看一下会不会有好转，数据源-编辑数据源-高级-设置超时时间
