### ISSUE TITLE
[Bug]API 数据源编辑界面显示内容超出边框

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#3351]
**DataEase 版本**
V1.15.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
最新 Edge

**Bug 描述**
添加 API 数据源后，API地址显示内容超出了边框

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/30886198/195555638-d733ae2a-f990-4aba-a97f-6ba0bb5cc865.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快优化

**Comment by BBchicken-9527** [comment]
问题已修复，可以下载新版本尝试，感谢支持
