### ISSUE TITLE
[Bug]创建筛选组件时样式错位问题

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3352]
**DataEase 版本**
v1.15.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 105

**Bug 描述**
创建筛选组件时样式错位问题，调整浏览器窗口大小比例，组件中样式适配度不好，如下图所示。
![image](https://user-images.githubusercontent.com/48945409/195567807-efc62a70-6757-4d20-bdf9-578bc7b5388a.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
