### ISSUE TITLE
[Feature]企业版定时报告功能支持立即执行

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#3353]
**请描述您的需求或者改进建议.**
企业版定时报告功能支持立即执行
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/89771514/195575725-977bcccc-f8db-4abe-80ea-8648e7a18112.png">

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。
