### ISSUE TITLE
[Bug]默认管理员角色没有初始化模板市场及数据集表单的权限

### ISSUE THREAD

**Issue by wan92hen** [dataease/dataease#3356]
**DataEase 版本**
v1.15.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microso Edge 106

**Bug 描述**
从 v1.14.0 版本升级到 v1.15.2 版本，内置的管理员角色没有勾选模板市场及数据集表单权限，仅有默认的 admin 用户有该权限。
![image](https://user-images.githubusercontent.com/27671436/195755511-f20cdad3-2847-43ed-972d-49ab9fcf68b3.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复。
