### ISSUE TITLE
[Bug]【离线安装】安装 DataEase 成功，但是日志却报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3366]
**DataEase 版本**
1.15.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
无需浏览器

**Bug 描述**
安装 DataEase 成功，但是日志却报错：提示服务不成功。

**Bug 重现步骤(有截图更好)**
1.在一个 80 端口被占用的服务器中安装 DataEase，只调整 install.conf 脚本为 local 模式，正常离线安装 DataEase。
2.提示端口被占用，未安装成功。
3.dectl uninstall 卸载 DataEase，清空  /opt/dataease 目录下的文件。
4.调整 install.conf 文件，将服务端口改成未被占用的端口 8080。
5.安装结束提示：服务未成功。
6.dectl status 查看各个服务状态正常，但是提示：服务未成功。
7.浏览器访问 DataEase，发现可以正常使用功能。

猜测：服务状态打印脚本中关于端口的判断或者其他地方估计哪里写得有问题。

**Comment by xuwei-fit2cloud** [comment]
请参考文档：
https://dataease.io/docs/faq/configuration_faq/configuration/#5-dataease

**Comment by AndroidBaby1** [comment]
好的吧，非常感谢。（按理说我卸载干净重新安装，就应该正常不报错才对，哈哈哈哈！）

**Comment by xuwei-fit2cloud** [comment]
dectl uninstall只是停止dataease服务，并不是卸载。命令行工具里没有提供卸载的功能。

**Comment by AndroidBaby1** [comment]
好的，谢谢
