### ISSUE TITLE
[Bug] 计算字段语句过长导致 UI 界面异常

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3368]
**DataEase 版本**
1.15.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.在1.14版本中，语句过长UI界面也没问题，如图是1.15.1
![image](https://user-images.githubusercontent.com/82353425/196150076-a33cea75-eb9c-4e88-bba4-1f2fb0bccb76.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题已修复，建议升级最新版本看一下
