### ISSUE TITLE
[Bug]新版本创建部分类型数据集时无法填写名称

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3370]
**DataEase 版本**
v1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装部运行

**浏览器版本**
Chrome 105

**Bug 描述**
新版本创建数据集时没有填写数据集名称的位置，都是默认的名称，需要创建完成后再调整。

**Bug 重现步骤(有截图更好)**
1.创建新的 SQL 数据集，界面中没有自定义名称的位置。
![image](https://user-images.githubusercontent.com/48945409/196162269-b86f8ff7-fd51-4544-b7fb-de1a5249ef2e.png)

2.保存数据集后名称为默认的“新建SQL数据集”
![image](https://user-images.githubusercontent.com/48945409/196162440-3b3168c7-c500-44e5-958b-40dbf0ba3486.png)

3.新建关联数据集同样的问题
![image](https://user-images.githubusercontent.com/48945409/196162584-2da470da-0761-4f23-a3d0-11e2b6cbfb95.png)
![image](https://user-images.githubusercontent.com/48945409/196162646-3928b6a3-6abf-4f5f-ba51-853d361c092b.png)

**Comment by BBchicken-9527** [comment]
感谢反馈 ，点击编辑页面左上角名称将会进入名称编辑状态
![image](https://user-images.githubusercontent.com/84372766/196321570-5113ec20-2d75-4c13-8e6b-5d28b3c45173.png)

**Comment by luyang351** [comment]
> 感谢反馈 ，点击编辑页面左上角名称将会进入名称编辑状态 ![image](https://user-images.githubusercontent.com/84372766/196321570-5113ec20-2d75-4c13-8e6b-5d28b3c45173.png)

好的，不过这里可以点击确实很不明显，而且**与其他数据集设置名称的位置逻辑不一致**，比如数据库数据集的名称编辑位置很清晰，再去使用 SQL 数据集时在目前的 UI 设计下引导不到左上角位置做编辑，建议优化下界面引导性~
![image](https://user-images.githubusercontent.com/48945409/196322440-56a11591-883e-4519-8347-f6beec7a653a.png)

**Comment by BBchicken-9527** [comment]
明白你的意思，是这样的，因为数据库数据集和excel是可以添加多个表单，所以和sql数据集这种只能添加单一表单的处理逻辑会有所不同，目前的样式我们也考虑了很久，在权衡使用习惯与操作链路长度考虑最终决定创建时直接点击名称进行修改，但单一的表单添加确实名称修改也不太明显，我们会做点小优化让这里更直观的被用户所知道可以进行修改，感谢

**Comment by luyang351** [comment]
好的，明白。

**Comment by yayanpei** [comment]
感谢反馈，V1.16版本（11.3日发布）已对此进行优化，还请多加关注。
