### ISSUE TITLE
[Bug]仪表板中两个ECharts堆叠折线图，纵轴数值格式错乱

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#3372]
**DataEase 版本**
v1.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 106.0.5249.119（正式版本） (x86_64)

**Bug 描述**
1、新建一个ECharts堆叠折线图，设置纵轴的数值格式为数值
2、在此新建或者复制一个ECharts堆叠折线图，设置纵轴的数值格式为百分比
3、此时放大或缩小视图中的内容，就会发现数值会变成百分比，或者百分比会变成数值，发生错乱
![image](https://user-images.githubusercontent.com/89771514/196328917-0e7fd4c1-32b9-4c8b-881a-ac3f5953c28c.png)
![image](https://user-images.githubusercontent.com/89771514/196329530-bb3f209d-699b-406a-b54a-611323c14b8d.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复。

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
