### ISSUE TITLE
[Feature] Echarts 或者 Antv 堆叠图支持多个指标

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3375]
**请描述您的需求或者改进建议.**
1.目前 DataEase 的 Antv 与 Echarts 的堆叠图只能支持一个指标，能不能支持多个嘞？
如图实现的场景，这个是用 Echarts 来实现的。
![img_v2_a7fb7195-58e2-4af8-a72b-54064ff4685h](https://user-images.githubusercontent.com/82353425/196332111-ab142120-b4ef-4f6a-ba04-c539e5e2c6ab.jpg)
如图数据表的结构。
![img_v2_667c7341-5ad8-46c2-ac5c-ee5ef5154c5h](https://user-images.githubusercontent.com/82353425/196332145-5dcf0ef2-5457-44f4-a537-83b78cb7fb70.jpg)

**Comment by ywhfzy** [comment]
> 感谢反馈，目前是支持按照指标堆叠的，使用方式如下： 第一种，如果根据维度堆叠，那么指标中选择了多个指标的情况下，默认第一个指标根据维度堆叠项展示。 第二种，如果根据指标堆叠，那么【堆叠项/维度】处空着，默认多个指标堆叠。您截图中的使用方式为第二种，如下图所示 <img alt="image" width="698" src="https://user-images.githubusercontent.com/84168063/196575538-ca13afea-be29-415b-be5c-55ff2fc9cf56.png">

类别轴与堆叠项我都拖入的维度，然后指标的话再拖入多个只能默认展示第一个，看看下面的嘞图
![6e1a209c-9a95-417a-a0d7-7a00d2d0f8b6](https://user-images.githubusercontent.com/82353425/196580390-0db54db7-0372-4656-baac-c8645cc77af2.jpeg)
数据集的结构如图
![image](https://user-images.githubusercontent.com/82353425/196580456-df035a87-b9f1-43d5-9cd9-9ead6f337189.png)

**Comment by yayanpei** [comment]
是的，要么根据维度堆叠，要么根据多指标堆叠。不能既根据维度堆叠，又根据多指标堆叠，如果两者都存在，默认根据维度堆叠，并展示第一个指标。
