### ISSUE TITLE
[Feature] 首页除了可以开启关闭，是否可以自定义URL

### ISSUE THREAD

**Issue by zhanggefei** [dataease/dataease#3377]
**请描述您的需求或者改进建议.**
企业内有自己的首页宣传，是否可以替换首页，建议可以自定义首页URL。

**Comment by xuwei-fit2cloud** [comment]
v1.10.0版本开始，在企业版【系统配置】->【显示设置】里，是支持首页URL设置的。

**Comment by zhanggefei** [comment]
简直不要太优秀
