### ISSUE TITLE
[Feature] excel字段过多时 保存按钮没有固定

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3384]
**请描述您的需求或者改进建议.**
如图
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/45852479/196393944-2e6d5b97-9b9e-4e04-b0a7-8576ea933f81.png">
excel字段过多时 保存按钮没有固定，或者做一个滚轮

**Comment by yayanpei** [comment]
感谢反馈，我们优化一下。

**Comment by MaekBlack** [comment]
就是谷歌浏览器哈

**Comment by yayanpei** [comment]
收到，我们尽快优化，11.3日发布的版本会更新，还请多加关注。
