### ISSUE TITLE
[Bug] 指标卡与富文本关联同一表格联动报无法获取字段值

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3385]
**DataEase 版本**
1.15.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.首先拖入表格，指标卡与富文本都进行设置关联表格中的“企业字段”，并且仪表板设定5秒刷新一次
如图
![image](https://user-images.githubusercontent.com/82353425/196407100-12a45a56-517e-4639-b9ea-cb9a28dd75ae.png)

2.这时候去更改企业的信息，由“抖音哈哈是的”改成“抖音”，等待仪表板刷新的时候就会报错如下
![image](https://user-images.githubusercontent.com/82353425/196407340-a2337313-3b62-4156-a895-2e91779db8f0.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前环境中没有复现你说的问题，可以升级看一下
