### ISSUE TITLE
[Feature]视图中的日期格式多样化配置

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3387]
**请描述您的需求或者改进建议.**
1.我们的场景是每分钟记录信息，拖到DataEase展示的时候没有按照整点展示，缩小的话右边就展示了。
仪表板展示
![img_v2_8db3370e-29e2-4df3-8a1e-eacd5d41b49h](https://user-images.githubusercontent.com/82353425/196583364-31d0bcbf-f1f9-48e5-90ce-a23046bc3fcd.jpg)
数据集展示
![img_v2_1a8f7de0-c03c-4800-888b-b1b48f34ff2h](https://user-images.githubusercontent.com/82353425/196583377-c88c69c1-e915-4522-8227-ee9998b106a1.jpg)
之前有用过SQL处理每小时的展示量，但我们是每分钟计算一次，会有延迟的发生。
同样的例如每隔5分钟展示，每隔10分钟展示，按每周，每季度，年，月，日
![image](https://user-images.githubusercontent.com/82353425/196592581-b6a182a4-70b0-432f-ac76-183dec769fbd.png)

**Comment by yayanpei** [comment]
感觉您的反馈，需求已经在需求池中，会根据需求的优先级顺序进行优化，还请多加关注。
