### ISSUE TITLE
[Question] 计算字段的二次计算

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3389]
**请描述您的问题.**
我们绝大部分的使用场景不仅仅是基于一次计算就能得出结果。需要将计算出来的内容再次进行计算。
发现其他厂商 tableau 会支持此方式，那么咱们 DataEase 对于二次计算有相应的规划吗？

**Comment by xuwei-fit2cloud** [comment]
是有计划的，目前还在设计阶段。这个功能的支持相对会复杂一些，会比较耗时。
