### ISSUE TITLE
[Feature]支持仪表板中的视图能够通过参数联动嵌入仪表板的浏览器组件

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#3391]
**请描述您的需求或者改进建议.**

如下图所示的效果
<img width="1661" alt="image" src="https://user-images.githubusercontent.com/60059766/196639839-534e57c4-0113-4d10-a3db-45652fad3bda.png">

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到
