### ISSUE TITLE
[Bug]一次创建多个数据库数据集时，选中一个后再使用搜索框键入受限

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3392]
**DataEase 版本**
v1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 105

**Bug 描述**
创建数据库数据集时，选中一个数据库表后，再使用“表名称搜索框”，无法输入进非已选中表名称中所带的字符。
例如下图所示， 2 号位置所能输入的字符只有选中的 1 的表名称中所带有的。其它字符输入无效，不会出现在搜索框。
![image](https://user-images.githubusercontent.com/48945409/196653055-ed1ca532-6685-4964-bc9c-e426184b78fe.png)

当输入大于一个字符时也要完全按照已选中的表的名称顺序，否则无法输入进框中。其内在逻辑是只能输入可以匹配到目前已选中的表名称的字符串才可以。
![image](https://user-images.githubusercontent.com/48945409/196653542-2f57edf6-dec7-4596-af2d-6f9b9112e11a.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复的
