### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by xiazhiliangfeng** [dataease/dataease#3393]
**DataEase 版本**
1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**

**Bug 描述**
1、编译报错，包引用错误 import org.apache.commons.lang 应为 import org.apache.commons.lang3
2、引用了 knife4j，但通过 访问 ip+port+doc.html，报错404 

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，本地并没有复现你说的问题，不知道你有没有更具体的信息方便我们判断,或者也可以登陆我们的网站看一下文档：https://dataease.io/docs/index.html
