### ISSUE TITLE
[Feature]【仪表板】仪表板跳转内部的公共链接的时候起到筛选的作用

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3394]
**请描述您的需求或者改进建议.**
当前仪表板可以跳转内部的公共链接，但是不能像跳转外部链接一样可以起到参数筛选的作用（公共链接要通过加密筛选）。
私下认为之前要加密参数的原因是由于给到外部要考虑到安全问题。
那如果是自己内部去调用是不是可以不用加密。

**Comment by yayanpei** [comment]
感谢您的反馈，我们内部讨论一下。

**Comment by AndroidBaby1** [comment]
好的，谢谢
