### ISSUE TITLE
[Bug]【数据源】Hive 数据源报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3395]
**DataEase 版本**
1.15.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
Hive 2.1.1 版本数据源连接报错，报错信息如下：
![image](https://user-images.githubusercontent.com/24768910/196866998-05a6c5a7-7e5e-4c05-8ea2-027eec785393.png)

**Bug 重现步骤(有截图更好)**
1.在驱动管理内上传了对应的数据库驱动：hive-jdbc-2.1.1-cdh6.3.2.jar
2.具体参数配置如下（详细参数内容可私聊，用户信息不方便公开）：
![image](https://user-images.githubusercontent.com/24768910/196867226-573818dc-3b49-4fbb-a12f-3bd365f009c9.png)

**Comment by xuwei-fit2cloud** [comment]
用默认驱动不能连吗？可以单聊。
