### ISSUE TITLE
[Bug] 超长仪表板导出为图片时下半部分会缺失，导出 PDF 为空白

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#3398]
**DataEase 版本**
v1.15.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome
版本 106.0.5249.119（正式版本） (arm64)

**Bug 描述**
超长仪表板导出为图片或者PDF时下半部分会缺失

**Bug 重现步骤(有截图更好)**
1、导出图片缺失，如下图所示：
<img width="384" alt="image" src="https://user-images.githubusercontent.com/30063018/196885660-f2d4c632-ede0-4b87-a8a6-40b46b160c99.png">
2、导出 PDF 空白，如下图所示：
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/30063018/196886060-b3265b84-792f-4247-9108-2998540e0e4a.png">

**Comment by xuwei-fit2cloud** [comment]
试试v1.15.3版本?

**Comment by ziliang-wan** [comment]
忘记回复了，测试下来 1.15.3 版本也是有同样的问题的，超长仪表板从中间被截断了

**Comment by BBchicken-9527** [comment]
没法先你这种情况，是有什么特殊操作吗，大概是多少行的视图？我这边测试了16行
