### ISSUE TITLE
[Bug]新建仪表板报错

### ISSUE THREAD

**Issue by luty2018** [dataease/dataease#34]
**DataEase 版本**

1.0.0
**浏览器版本**

**Bug 描述**
![image](https://user-images.githubusercontent.com/36292514/123402518-650efd00-d5da-11eb-8550-04b939cbc17b.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by ziyujiahao** [comment]
已修复 暂时不要来回切换 自定义和 复用模板
