### ISSUE TITLE
[Bug] SQL数据集对于数值格式参数预览

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3400]
DataEase 版本
v1.15.1

运行方式(安装包运行 or 源码运行 ?)
安装包

浏览器版本
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
SQL数据集添加数值类型多选参数时，设置参数后，预览报错

**Bug 重现步骤(有截图更好)**
1.未设置值前可以预览
<img width="1461" alt="image" src="https://user-images.githubusercontent.com/45852479/196891955-e6096b02-98bf-4a40-b472-2a77da2dc693.png">
2.设置后预览报错
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/45852479/196892248-b9f3d391-6d4d-4de7-8d06-2d95cff7855a.png">
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/45852479/196892612-e533a2da-0c62-4aba-b338-4bec34d9fec4.png">

**Comment by ywhfzy** [comment]
'${sorce}' 参数旁边加单引号试试

**Comment by MaekBlack** [comment]
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/45852479/196898082-9e415591-d0ed-4faa-91e1-e54a2c8ac76a.png">
还是不行哈

**Comment by ywhfzy** [comment]
> <img alt="image" width="1464" src="https://user-images.githubusercontent.com/45852479/196898082-9e415591-d0ed-4faa-91e1-e54a2c8ac76a.png">
> 
> 还是不行哈

in？？？？？ SQL 的 in 只能是区间

**Comment by BBchicken-9527** [comment]
感谢反馈，目前预览只支持文本类型，但并不影响实际使用，这个地方我们优化一下
