### ISSUE TITLE
[Feature] 创建关联数据集的时候，能够把直连、定时同步的图标也带上

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#3401]
**请描述您的需求或者改进建议.**
创建关联数据集的时候，能够把直连、定时同步的图标也带上，现在在创建关联数据集的时候看不出来是直连还是定时同步的数据集，会造成一定的困扰。
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/30063018/196901742-92c9bab5-65f9-4db2-a77a-23d6f16e3a72.png">

**Comment by yayanpei** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
