### ISSUE TITLE
[Feature] 仪表板后续会考虑支持工作空间吗？

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3402]
**请描述您的需求或者改进建议.**
例如我已经做了80个仪表板，且有20多个目录，专门展示本国数据。这时候我们需要展示外国数据，需要重新再创建80个仪表板，目录肯定也不一样。
![image](https://user-images.githubusercontent.com/82353425/196908331-143bc49f-e154-48fd-aa49-d12de1919d49.png)

或者说，DataEase 后续会支持工作空间的想法吗？将仪表板、数据集、数据源整体都切换。

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到
