### ISSUE TITLE
[Bug]视图的数据集计算字段不随sql更新变化

### ISSUE THREAD

**Issue by Toy-data** [dataease/dataease#3405]
**DataEase 版本**
V15.3

**运行方式(安装包运行 or 源码运行 ?)**
在线安装

**浏览器版本**
Edge  106.0.1370.42

**Bug 描述**
创建数据集计算字段后，如果更新计算字段的sql，只有数据集的计算字段内容汇改变，仪表板的视图里计算字段仍然是修改前的值

**Bug 重现步骤(有截图更好)**
1.创建一个计算字段 字段D = 字段A+字段B，保存；
2.修改计算字段 字段D = 字段A+字段B+字段C，保存；
3.查看视图的 字段D 时，发现还只是 字段A+字段B 的值，并不是 字段A+字段B+字段C。

**Comment by BBchicken-9527** [comment]
感谢反馈与支持，此处目前确实存在你说的这个问题，因为动态处理后会增加很多不确定因素如多个属于都添加了这个字段的视图处理（字段频繁改变数值多个视图的计算），其实不是计算字段，如果数据库变更原始数据依然要通过同步字段来进行处理是一个道理。我们会在后续版本逐步完善此处功能
