### ISSUE TITLE
[Bug] API数据源json格式解析与数据集不匹配

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3421]
DataEase 版本
v1.15.3

运行方式(安装包运行 or 源码运行 ?)
安装包

浏览器版本
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
当值为JSONArray转换成的String时，API数据源可以预览，但数据集添加后无数据
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/45852479/197465312-76808bb4-0194-4367-bd2c-45db7ead5d45.png">

**Bug 重现步骤(有截图更好)**
1.添加API数据源，填写相关信息，勾选所需字段，此时数据预览有值。
<img width="874" alt="image" src="https://user-images.githubusercontent.com/45852479/197464543-e449faec-2712-4fd6-9acc-a879ff029dc4.png">
2.添加该数据源对应的API数据集，数据预览只有字段名称。
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/45852479/197464838-bed6ec45-6972-47b4-9e71-8fbbf48651af.png">
3.保存后，立即更新，更新显示成功，但是无数据。
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/45852479/197464993-17353581-1783-439c-b2a9-b9fdc21c1fd9.png">
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/45852479/197465027-75f1b4bc-d6d2-40f9-bdaa-a9bdd711d0f1.png">

附：当使用如下JSON时无问题：
<img width="376" alt="image" src="https://user-images.githubusercontent.com/45852479/197465488-3b0909b0-0745-4da2-a70e-2ddd82188f81.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈！
确实有这个问题，按理来说当字段内容为文本时，是不应该解析字段内容的。
我们在后续版本处理一下。
