### ISSUE TITLE
[Feature] API数据源添加时数据字段值缺失

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3423]
**请描述您的需求或者改进建议.**
DataEase版本：v1.15.3
当API数据源解析如下JSON时，添加后只有第一条数据的message和request_id有值。
<img width="672" alt="image" src="https://user-images.githubusercontent.com/45852479/197469355-89d87ab3-2284-48dd-b460-51559fcbcb6f.png">
<img width="876" alt="image" src="https://user-images.githubusercontent.com/45852479/197469417-bc34b2a1-b393-42b5-b18b-7ca535935f65.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈！
由于选择的是数组与上级字段的组合，所以出现了现在的情况。
我们考虑一下如何处理这种情况，目前有两个方案：
1. 上级字段后面的数组字段在每条记录里重复
2. 不允许这种带数组的跨层级选择
我们先内部讨论一下。
