### ISSUE TITLE
[Bug] API数据源添加时大小写无法作为区分不同字段名的依据

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3424]
DataEase 版本
v1.15.3

运行方式(安装包运行 or 源码运行 ?)
安装包

浏览器版本
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
API数据源添加时提示字段名重复，把首字母大写后保存成功，使用该数据源添加数据集后，同步失败。

**Bug 重现步骤(有截图更好)**
1.添加API数据源，填写相关信息，勾选所需字段，此时提示字段名重复
<img width="944" alt="image" src="https://user-images.githubusercontent.com/45852479/197474740-af45c4a2-7ea7-4099-a497-b789524e6e13.png">
2.修改其中一个为大写后，添加成功
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/45852479/197475346-1a08dc41-e5a4-4892-915d-04ff12be2861.png">
3.添加数据集时，数据预览没有问题
<img width="877" alt="image" src="https://user-images.githubusercontent.com/45852479/197475347-44f483c8-5568-426c-9365-4e924a571915.png">
4.保存后，字段管理页面只有两个字段（缺少了一个display_name）
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/45852479/197475466-f5af039e-a29c-47b2-a3d5-86d0d4bf361a.png">
5.数据同步失败
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/45852479/197475598-44445275-ee55-49ff-b052-1004bd58b5de.png">
<img width="772" alt="image" src="https://user-images.githubusercontent.com/45852479/197475643-564af470-eb0a-4880-b6e8-6d7adfbb518b.png">
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/45852479/197476755-af2975eb-349c-4b50-a62b-0368ad408870.png">
(当前为local部署模式，若为simple，则报错为Column count doesn't match value count at row 1)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈！
确实有这个问题，我们后续版本修复一下。

**Comment by tjlygdx** [comment]
是数据的的问题，方便把这个API的返回数据发过来，我们测试一下？

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。

**Comment by MaekBlack** [comment]
发现个新的问题，还是原来的数据集，导入后的字段无法做指标，维度的切换
![image](https://user-images.githubusercontent.com/45852479/210481610-c5936aa4-6a8f-468d-b78e-bd7dd55d39e1.png)
