### ISSUE TITLE
[Feature] API数据源选择字段，支持设置时间格式类型

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3425]
**请描述您的需求或者改进建议.**
DataEase版本 v1.15.3

API数据源添加时，选择数据字段，支持字段类型选择时间格式
<img width="870" alt="image" src="https://user-images.githubusercontent.com/45852479/197485504-5066336d-1dcf-4c31-8597-888e3552686c.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，时间类型的字段正在做日期格式的支持，请等待新版本。
