### ISSUE TITLE
[Bug] 点击编辑关联数据集保存之后，数据集名会被重置

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3426]
**DataEase 版本**
1.15.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌浏览器

**Bug 重现步骤(有截图更好)**
1.首先，新建一个关联数据集，并且将名字改成“测试1”
![image](https://user-images.githubusercontent.com/82353425/197486721-68c11319-4418-4126-ae69-be325bc93baf.png)

2.然后点击编辑关联数据集之后，左上角的数据集名字变成“变脸数据集”，我只是想改显示字段，并不改名字。
![image](https://user-images.githubusercontent.com/82353425/197487036-af79b6c9-8d61-49a6-9d67-427f036b3dc4.png)

3.点击保存之后，名字变回了“关联数据集”
![image](https://user-images.githubusercontent.com/82353425/197487121-314841ce-7984-4ba3-b9ef-c8c982000c64.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈！
我们后续版本处理一下。

**Comment by fit2cloudrd** [comment]
v1.17.0已处理，请等待新版本发布。
