### ISSUE TITLE
使用clickhouse作为数据库的时候，如果使用了带参数的sql配置， 会导致频繁超时

### ISSUE THREAD

**Issue by shenyuhit** [dataease/dataease#3429]
请描述您的问题.
version:dataease-v1.15.3-online.tar.gz
database: clickhouse 22.2.2.1
error: 频繁超时，但是clickhouse本身没有问题，可以正常使用，其他代码可以运行；并且如果配置的sql中不带参数，也不会超时，配置了一个带参数的sql 之后 select code from t_table where c_date = ${sdate} 后 就频繁超时 
预览数据错误：执行SQL失败。可能因相关字段、表、数据集等元素发生变更，请检查->SQL ERRORClickHouse exception, code: 1002, host: xxx, port: 8123; Code: 159. DB::Exception: Timeout exceeded: elapsed 5.000357056 seconds, maximum: 5. (TIMEOUT_EXCEEDED) (version 22.2.2.1)

**Comment by shenyuhit** [comment]
好象 mysql的也有问题，用现成的demo，加一个参数就不行了，无法包存

select a.province,a.num,b.gdp from demo_gdp_district_top100 as a
left join (select province,sum(gdp) gdp from demo_gdp_by_city group by province ) as b
on a.province=b.province and b.gdp > ${param}

设置 param 为文本 :1000

error:
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'DATAEASE_PATAMS_BI' in 'on clause

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先内部排查一下。

**Comment by xuwei-fit2cloud** [comment]
这些有问题的数据集是否都是定时同步类型数据集？
定时同步类型的数据集是不能使用参数功能的，目前只有直连模式的SQL数据集才支持参数。
我们在下个版本里已经做了处理。

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
