### ISSUE TITLE
新增数据库

### ISSUE THREAD

**Issue by ccczhouxin** [dataease/dataease#3432]
你好我想要新增一种数据库进去，具体位置在哪里呢

**Comment by yayanpei** [comment]
感谢反馈，如果要新增一种数据库类型，可通过提交pr的形式，我们合并后放进产品中；您也可以以插件的形式开发。

**Comment by ccczhouxin** [comment]
> 感谢反馈，如果要新增一种数据库类型，可通过提交pr的形式，我们合并后放进产品中；您也可以以插件的形式开发。

好的

**Comment by ccczhouxin** [comment]
> 感谢反馈，如果要新增一种数据库类型，可通过提交pr的形式，我们合并后放进产品中；您也可以以插件的形式开发。

你好，第一种我要fork下来开发吗，还是提供数据库
