### ISSUE TITLE
[Bug]【视图】图例多行情况下，显示不全

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3434]
**DataEase 版本**
1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
图例多行情况下，显示不全，希望可以显示完整。

![b28c4476cfc3623108fe591af72fb725](https://user-images.githubusercontent.com/24768910/197664321-135f0882-5383-41ec-ac16-0da03d97e9ee.jpeg)

**Comment by BBchicken-9527** [comment]
这个问题是已知问题，组建内部操控空间较低，我们也在商量优化的方案，感谢反馈与支持

**Comment by AndroidBaby1** [comment]
好的，谢谢
