### ISSUE TITLE
[Bug]EXCEL提交数据自动识别类型问题2个

### ISSUE THREAD

**Issue by garyearth** [dataease/dataease#3438]
**DataEase 版本**

v1.15.3
**运行方式(安装包运行 or 源码运行 ?)**
centos

**浏览器版本**
搜狗浏览器，11.0.1

**Bug 描述**
1.EXCEL上传，自动识别类型错误（WPS保存的EXCEL类型问题），用office转存一下后，自动识别成功率90%，但还是有自动识别问题
2.自动识别出错后，手动更改，同一张表，不同列，有的列能手动更改类型，有的列不可以，像是锁定。
**Bug 重现步骤(有截图更好)**
1.1:设置单元格格式为百分比，小数2位
1.2:保存上传
1.3:被识别为文本“T”格式

2.1一次上传存在多张工作表的工作簿后手动更改类型
2.2有的列可以更改，有的列无法更改。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，Excel的类型判断目前是根据类型码来判断的，有些情况如果未加入判断条件中的话，确实会存在不准确的问题。
我们后续处理一下。
