### ISSUE TITLE
[Feature] 过滤组件字段的过滤与选择

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3439]
**请描述您的需求或者改进建议.**
DataEase 版本  v1.15.3

当前现象：
当前有这样的两个数据集
<img width="539" alt="image" src="https://user-images.githubusercontent.com/45852479/197736724-bdd79a24-18a0-4081-a5cb-0b3cfdc4c6e7.png">
<img width="573" alt="image" src="https://user-images.githubusercontent.com/45852479/197736789-3e80fc68-a939-4ea9-ac39-8099aaaef246.png">
当我在仪表板设置文本下拉过滤组件时，仅配置SQL_Test1的gender，却同时勾选上SQL_Test1的gender1和SQL_Test2的gender2。
<img width="917" alt="image" src="https://user-images.githubusercontent.com/45852479/197737258-f5478cfd-14a1-4807-8f8c-332c145c9584.png">
页面使用过滤组件
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/45852479/197737420-d2372af6-a03b-44da-9acc-bda413934a97.png">

改进建议：
在选择参数前，应首先过滤所使用的数据集。

**Comment by yayanpei** [comment]
感谢您的反馈，回复如下，如有疑问，也可以加我微信交流：18317092178.

1、【我在仪表板设置文本下拉过滤组件时，仅配置SQL_Test1的gender，却同时勾选上SQL_Test1的gender1和SQL_Test2的gender2】
> 由于您用了数据表 students 中的同一个字段 gender 绑定了两个参数 gender1、gender2，所以会存在如下情况，当过滤组件选择了字段gender之后，勾选一个参数，另外一个参数会默认选中

2、【改进建议：在选择参数前，应首先过滤所使用的数据集】
> 方便具体描述一下吗？首先是在什么时候过滤？在选择性别 M 之前吗？如果下拉组件还未选择选项值，那么参数值默认是空，即过滤条件不生效，展示所有性别的数据。
