### ISSUE TITLE
[Feature]建议仪表板批量操作界面样式优化一下

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#3442]
![image](https://user-images.githubusercontent.com/30886198/197744356-aa88f9fb-4d2d-4f9e-80f7-5d595889ac0b.png)
如图，批量配置界面文字与边框靠的很近，样式比较丑，行距过大，且与单独编辑某个视图时的样式不一致。建议保持统一。

**Comment by yayanpei** [comment]
感谢反馈，您的建议很不错，我们会优先加入优化清单的

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
