### ISSUE TITLE
[Bug]【数据集】Excel 数据集上传文件时无法修改文件类型

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3443]
**DataEase 版本**
1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
Excel 数据集上传文件时无法修改文件类型

**操作步骤**
[集贲工程1(1).xlsx](https://github.com/dataease/dataease/files/9859440/1.1.xlsx)

https://user-images.githubusercontent.com/24768910/197749588-e244c40c-32cd-4d4a-b975-b7dd882c3542.mov

**Comment by xuwei-fit2cloud** [comment]
问题已修复，请等待新版本发布。
