### ISSUE TITLE
[Feature]【仪表板】增加不定时刷新页面设置

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3444]
**请描述您的需求或者改进建议.**
【仪表板】增加不定时刷新页面设置

**Comment by yayanpei** [comment]
感谢您的反馈，刷新分为两种：
1、定时刷新，可通过设置时间间隔实现。
2、不定时刷新，可通过手动点击如下按钮触发，或者手动点击浏览器的刷新的按钮。
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/84168063/197917955-dc8a2b10-78d5-45cb-a288-2b81f729c33a.png">
