### ISSUE TITLE
[Bug] 仪表板修改名称后没有自动修改顶部名称

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3445]
DataEase 版本
v1.15.3

运行方式(安装包运行 or 源码运行 ?)
安装包

浏览器版本
Google Chrome 105.0.5195.125（正式版本） (arm64)
**Bug 描述**
对仪表板重命名，左侧树状目录下的名称已修改，但当前仪表板顶部的名称没有修改，需要手动刷新

**Bug 重现步骤(有截图更好)**
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/45852479/197925822-204ea844-d353-421c-aaf2-c06474503281.png">

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
