### ISSUE TITLE
建议添加文本卡的阈值功能

### ISSUE THREAD

**Issue by tanzhouhzou** [dataease/dataease#3446]
在实际的运用中，很多都需要文本内容显示内容，或者在公司的宣传中，或者在运维监控中，都需要高亮显示文字的颜色来区分不同的需求，在汇总表的高级选项中就很好的支持这一项，但是单个指标在文本卡里没有高级选项，也没有阈值的功能。建议在文本卡中添加高级--阈值功能

**Comment by BBchicken-9527** [comment]
感谢反馈，因为文本卡有他的局限性，能详细说一下您的建议吗？或者你使用的场景我们好讨论一下是否支持和如何支持

**Comment by tanzhouhzou** [comment]
我们公司内部在做运维监控大屏展示的时候，监控服务的运行状态和网卡的运行状态时，我们要用正常和异常表示，我们想显示正常时为绿色，显示异常时为红色，能为实际的监控中提高发现问题的效率，文本卡不支持设置颜色。我们用正常和异常表示，在数据库中也是0和1，或者数字显示卡可以支持值的转换就好了，0 转换成正常，1转换成异常，颜色跟值一起变化就好了

**Comment by tanzhouhzou** [comment]
![Uploading 监控.jpg…]()

**Comment by tanzhouhzou** [comment]
![监控](https://user-images.githubusercontent.com/84854569/199943935-b13f69ef-e3b2-4e38-b6a1-d1dfeff4bd86.jpg)

**Comment by yayanpei** [comment]
1、文本卡支持根据不同的值，显示不同的颜色，需求我们已收到。
2、支持值的转换，建议您先通过新建计算字段，并写 case when…then 语句的方式来做转换，我们也在规划用更便捷的方式来实现数据的转换。

> 我们公司内部在做运维监控大屏展示的时候，监控服务的运行状态和网卡的运行状态时，我们要用正常和异常表示，我们想显示正常时为绿色，显示异常时为红色，能为实际的监控中提高发现问题的效率，文本卡不支持设置颜色。我们用正常和异常表示，在数据库中也是0和1，或者数字显示卡可以支持值的转换就好了，0 转换成正常，1转换成异常，颜色跟值一起变化就好了

**Comment by xuwei-fit2cloud** [comment]
v1.18.0版本已处理，请更新最新版本。
