### ISSUE TITLE
[Bug] SQL查询语句有中文，中文会变成乱码，导致查询结果不准确

### ISSUE THREAD

**Issue by bingkun-z** [dataease/dataease#3447]
**DataEase v1.14.0**

**运行方式(源码运行)**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
![42e02c37b35a8fbb1e62376cabc6146](https://user-images.githubusercontent.com/68404132/197939656-5dee36a6-ca14-4bb7-ade0-a4dd08908b68.jpg)

**Comment by BBchicken-9527** [comment]
感谢反馈，问一下数据库的字符集是什么
