### ISSUE TITLE
[Bug]使用hive数据源时，视图一直请求超时

### ISSUE THREAD

**Issue by aptx4869211** [dataease/dataease#3448]
**DataEase 版本**
DataEase版本：1.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行
部署模式为本地部署
**浏览器版本**
chrome 106

**Bug 描述**
创建视图时，如果使用的数据集的数据源是hive数据库。图表不能正常显示，一直查询超时。

**Bug 重现步骤(有截图更好)**
1.点击新建数据源，选择hive连接
![image](https://user-images.githubusercontent.com/57996919/197927654-995b4c7c-2fb4-46e0-ae83-7fc0145b5370.png)
![image](https://user-images.githubusercontent.com/57996919/197927805-369c6096-c7d9-46cc-89d6-d5c82bbce833.png)

2.进入到数据集页面，点击+号新建数据集，选择数据库数据集。
![c005b818498dfdbdf2f57d76db4c3dc](https://user-images.githubusercontent.com/57996919/197928103-e3562990-975b-4ecc-b5c5-9562f525533d.jpg)
获取数据成功并点击保存
3.进入到仪表板编辑页面，创建视图，选择数据源为hive数据库的数据集
![13f79f6d176e3aa8f3375fcfcd71040](https://user-images.githubusercontent.com/57996919/197947638-2f624096-7d92-44f3-b77c-28fab7215bbc.jpg)
只有明细表类型可以进行正常显示，其他所有图表都不能正常显示数据并显示查询超时（左右两个视图使用的是同一数据源，左边明细表加载时间约2s）

**Comment by JanvenZhao** [comment]
？？？ 同问，如何解决？
