### ISSUE TITLE
添加插件时报错

### ISSUE THREAD

**Issue by ccczhouxin** [dataease/dataease#3449]
**DataEase 版本**
1.14

**运行方式(安装包运行 or 源码运行 ?)**

源码运行
**浏览器版本**

chorm106
**Bug 描述**
本地安装插件时报错

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/43168824/197947819-2b9f5a8e-b0d9-4421-9c45-f7d073e15b27.png)
![image](https://user-images.githubusercontent.com/43168824/197947968-a2e8d639-f9de-4cde-b676-d7445de6dc80.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，看着像是传的文件有问题，你传的是什么文件呢？

**Comment by BBchicken-9527** [comment]
嗯... 看一下压缩后的文件是一个文件夹吗，平台接收解压后是一个json一个jar

**Comment by ccczhouxin** [comment]
> 嗯... 看一下压缩后的文件是一个文件夹吗，平台接收解压后是一个json一个jar
是的，现在好了

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
