### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by aptx4869211** [dataease/dataease#3450]
**请描述您的需求或者改进建议.**
数据源界面显示连接数据库的表时，如果连接库的表过多，1000以上。页面会因为渲染dom过多出现明显卡顿以及loading较久的情况
![a7b55d6aa1a2cd7d82e8d0772f3434b](https://user-images.githubusercontent.com/57996919/197948386-932cd951-4b41-4cf6-9fe7-10ddbfd4c6cd.jpg)
建议：可以在该页面加上分页功能，减少表格渲染的行数，或者使用虚拟列表

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们后期会进行相关优化。
