### ISSUE TITLE
[Bug] AntV面积图标签设置显示BUG

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3456]
DataEase 版本
v1.15.3

运行方式(安装包运行 or 源码运行 ?)
安装包

浏览器版本
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
设置AntV面积图标签时，打开与关闭标签选项，☑️没有去除

**Bug 重现步骤(有截图更好)**
1.当前为打开状态（正常）
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/45852479/197959554-ed3a6201-9931-46cf-bf9a-7c7119544553.png">
2.当前为关闭状态，仍然有☑️
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/45852479/197959646-e8e33cfe-ab52-49f3-b468-dc492bc187a5.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们下个版本修复一下。

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
