### ISSUE TITLE
[Bug] 指标卡视图名称设定不显示时没有缩略相关配置项

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3462]
DataEase 版本
v1.15.3

运行方式(安装包运行 or 源码运行 ?)
安装包

浏览器版本
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
指标卡视图名称设定不显示时没有缩略相关配置项

**Bug 重现步骤(有截图更好)**
1.正常状态
![image](https://user-images.githubusercontent.com/45852479/197982173-0fc2264e-19c1-4a64-9e82-2e331754e069.png)
2.取消☑️名称，相关配置没有缩略
<img width="948" alt="image" src="https://user-images.githubusercontent.com/45852479/197982571-cd8f2fde-0038-428f-ac5a-d8957c9b78ae.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
