### ISSUE TITLE
[Feature]建议优化网页组件的提示语

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3465]
**请描述您的需求或者改进建议.**
“请点击添加网页信息….”给人的感觉是点了这个组件的内部，就会有添加网页信息的入口出来，但实际上是需要点击左上角的小图标的。对于用户来说没注意的话以为是系统点了没反应。
![image](https://user-images.githubusercontent.com/48945409/197994408-a748b447-527e-4bee-aa3b-5b61680ef952.png)

**Comment by yayanpei** [comment]
感谢您的反馈，我们优化一下。
