### ISSUE TITLE
[Bug]【仪表板】移动端时间范围组件显示不全问题

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3466]
**DataEase 版本**
1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准浏览器

**Bug 描述**
移动端时间范围组件显示不全问题
![image](https://user-images.githubusercontent.com/24768910/197996787-285be2e5-68d2-4874-bd15-d6114c3b6452.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这是个已知问题，需要替换相应的组件，后续我们会处理。
