### ISSUE TITLE
[Bug]数据集计算字段函数表述错误

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3468]
**DataEase 版本**
v1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装部运行

**浏览器版本**
Chrome 105

**Bug 描述**
箭头指示位置应该修改为 r2。
![image](https://user-images.githubusercontent.com/48945409/198010274-ace83cd9-1fa5-404f-a1e5-23c2b6bdd4e3.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
