### ISSUE TITLE
[Bug] 视图字段管理，指标的类型显示不正确

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3472]
**DataEase 版本**
1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌

**Bug 重现步骤(有截图更好)**
1.首先原本的数据集的字段类型是“文本”，然后手动改成“数值”
![image](https://user-images.githubusercontent.com/82353425/198171995-e4f7b564-a9e6-4da1-bc7b-8f3fd68b3a17.png)

2.在视图字段管理的对应的字段显示还是“文本”。
![image](https://user-images.githubusercontent.com/82353425/198172027-877c5d9e-fe99-4309-bc27-247e3e5dc199.png)

3.在数据集字段管理显示的是“数值”
![image](https://user-images.githubusercontent.com/82353425/198172087-1e41876e-dde4-4adc-83a1-4eef25459ec1.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，视图计算字段此处显示的是原始数据类型的
