### ISSUE TITLE
[Feature]【视图】组件设置里选择的字段提示属于哪个数据集

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3473]
**请描述您的需求或者改进建议.**
【视图】组件设置里选择的字段提示属于哪个数据集
如下图所示：
![wecom-temp-32433-7eba92b567d3367ab07bcbc020aca425](https://user-images.githubusercontent.com/24768910/198172442-1f5cc752-d8a9-470a-b06a-7bb583aaab26.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这是个已知需求，我们后续版本会进行相关优化。
