### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by sunnidy2008** [dataease/dataease#3475]
![image](https://user-images.githubusercontent.com/11849175/198182616-8d11bb7b-3b10-4f85-a59e-046e455c354f.png)
如果按照你们的产品思路，我要传一个id到另外的页面，这个id必须在页面上显示，客户会不会觉得奇怪？另外对于数据钻取，大部分的客户只提出来对于这个视图点击进去想看到其他关联的东西，所以能带id到另外的界面是最好的，另一个页面想显示什么就显示什么。另外打开方式除了当前页面，新开页面，还应该支持当前弹窗（宽高就按百分比或者固定px设置就好）”

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。
