### ISSUE TITLE
[Feature] 希望可以支持数据源复制、编辑功能；报表的批量更新关联数据源功能

### ISSUE THREAD

**Issue by 945226956** [dataease/dataease#3476]
**请描述您的需求或者改进建议.**

我们开发的应用系统支持很多种数据源，例如mysql oracle clickhouse。并且系统部署环境也有很多套，例如生产、测试、预生产等。之前部署起来一套系统，针对一个数据源和生产环境做了一套报表，现在想同样复制到其他的数据源和不同环境系统中。发现系统不能好好的支持。希望可以提供数据源复制和编辑功能，报表目前是有一个复制功能，如果在支持批量修改当前关联的数据源，这样就可以轻松实现报表的轻松跨数据源和环境功能。（当然这里面存在数据集sql语法的兼容问题，这个是需要业务员注意写一些通用的sql。）

**Comment by xuwei-fit2cloud** [comment]
目前在开发的1.16版本会支持导出应用的功能，可以将仪表板+数据集+数据源一并导出。
在其他环境中导入的时候，会提示填写相关的数据源信息（此处目前支持和源视图使用的同类型数据源），然后自动创建一系列数据源+数据集+视图，并生成仪表板。
如果数据源类型有变化的话，需要手动在视图里进行数据集的切换，并进行一些必要的调整。
