### ISSUE TITLE
[Question] 数据源的驱动管理

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3477]
**请描述您的问题.**
我们新建的驱动，驱动名只能取一个，jar包可以上传多个。那程序是如何判断走不同jar包呢的？
还是说应该优化到每个驱动只能上传一个jar包。
![image](https://user-images.githubusercontent.com/82353425/198185895-07d7ca18-dd35-4fea-b32f-c8df54ff0f50.png)

**Comment by xuwei-fit2cloud** [comment]
这里建议每次添加一个版本的驱动哈。
