### ISSUE TITLE
[Bug]【仪表板】大屏展示仪表板白色背景显示黑色

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3482]
**DataEase 版本**
1.13.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
标准飞视浏览器

**Bug 描述**
大屏展示仪表板明细表视图没数据的地方显示黑色。

**Bug 重现步骤(有截图更好)**
![wecom-temp-250092-58f177b422e66c49865696fe2b256a4f](https://user-images.githubusercontent.com/24768910/198209874-b9c01d97-0e06-4d19-8df2-3b8a49e1870d.jpg)
![image](https://user-images.githubusercontent.com/24768910/198210013-3111ab72-7321-4fcb-8498-e4a62da89421.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，近期我们努力解决一下这个问题
