### ISSUE TITLE
[Bug]添加SQL数据集，通过修改sql调整了数据列可以预览，但无法获取数据且会报错

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#3483]
**DataEase 版本**
V1.5.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 已是最新版本
版本 107.0.5304.62（正式版本

**Bug 描述**
添加SQL数据集，调整SQL 语句中的列名称，预览数据无误，但是保存数据后报错。

**Bug 重现步骤(有截图更好)**
1.创建SQL数据集保存，如下图所示，保存后数据展示无误
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/60059766/198212030-8d5491f1-c322-4bc2-8f70-674e82773090.png">
2.编辑该SQL数据源，如下图所示，预览数据无误：
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/60059766/198212200-e0daa96f-5c67-442a-8c74-910a546ac4ca.png">
3.点击保存该SQL数据源，提示报错，点击同步字段后再次查看依旧报错
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/60059766/198214595-85f87357-ac93-43d2-b6ed-60f6839df722.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
