### ISSUE TITLE
[Bug]【视图】文本下拉组件目前不支持等比压缩

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3499]
**DataEase 版本**
1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准浏览器

**Bug 描述**
【视图】文本下拉组件目前不支持等比压缩

**Bug 重现步骤(有截图更好)**
大屏幕换到小屏幕上 会重叠
<img width="1422" alt="wecom-temp-1192441-779e01ea6541cf72089c77d5291aaf0e" src="https://user-images.githubusercontent.com/24768910/198251562-72359ec4-7c08-423c-a3eb-7c3b629e8b76.png">

**Comment by AndroidBaby1** [comment]
大屏幕：
![wecom-temp-68094-c2e62f40c6e65663f3e637a8d55cec75](https://user-images.githubusercontent.com/24768910/198252039-0ce81845-c87e-4210-a127-ead671adc678.jpg)

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题目前已经在通过其他方式去尝试解决这个问题了，请耐心等待
