### ISSUE TITLE
[Bug]SQL数据集count(*)时数据不准确

### ISSUE THREAD

**Issue by wangzhen-fit2cloud** [dataease/dataease#35]
**DataEase 版本**
v1.0.0

**浏览器版本**
Chrome 91.0.4472.114 on Windows

**Bug 描述**
在 SQL数据集中，使用如下 SQL 语句时，预览数据正常，保存确定后显示的数据不正常。
```
select count(*), DATE_FORMAT(DATE_ADD(FROM_UNIXTIME(create_time/1000) , INTERVAL(-WEEKDAY(FROM_UNIXTIME(create_time/1000))) DAY),"%Y-%m-%d") as week from issues where create_time is not null group by week
```

**Bug 重现步骤(有截图更好)**
1. 添加MySQL数据源
2. 添加SQL数据集
3. 使用如下 SQL 语句 count(*) 不指定别名
```
select count(*), DATE_FORMAT(DATE_ADD(FROM_UNIXTIME(create_time/1000) , INTERVAL(-WEEKDAY(FROM_UNIXTIME(create_time/1000))) DAY),"%Y-%m-%d") as week from issues where create_time is not null group by week
```
![image](https://user-images.githubusercontent.com/27671436/123402486-5de7ef00-d5da-11eb-8f5e-dcd3a981c42b.png)
![image](https://user-images.githubusercontent.com/27671436/123402522-65a79380-d5da-11eb-8ef9-7527ef27b5ed.png)

如果为 count(*) 指定别名，则数据正常
```
select count(*) as count .............................
```

**Comment by xuwei-fit2cloud** [comment]
感谢您的反馈，我们尽快修复

**Comment by XiaJunjie2020** [comment]
c89a837 1248188
此bug已修复，将随后续版本发布，感谢您的反馈。

**Comment by xuwei-fit2cloud** [comment]
已修复，请等待 v1.0.1 版本发布。

**Comment by xuwei-fit2cloud** [comment]
v1.0.1 已发布
