### ISSUE TITLE
[Bug]【仪表板】仪表板导出 PDF 格式是，组件中的文本内容有偏移

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3503]
**DataEase 版本**
1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
仪表板导出 PDF 格式是，组件中的文本内容有偏移

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/24768910/198270802-7172888e-113f-41fe-8414-2300c50dcea5.png)
![wecom-temp-59126-161572ad238cb0acff0a51df639cf229](https://user-images.githubusercontent.com/24768910/198270901-3846dfbc-53d9-4062-bb6a-d0b6f3739288.jpg)

**Comment by BBchicken-9527** [comment]
感谢反馈，此问题为已知问题，将会在后续版本中解决
