### ISSUE TITLE
[Bug]【视图】Echarts 图库的明细表下拉设置的时候表格数据滚动不了

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3511]
**DataEase 版本**
1.15.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
【视图】Echarts 图库的明细表下拉设置的时候表格数据滚动不了

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/24768910/198496012-69466f9f-a5fd-4d72-854d-02a2aa6fd6e3.png)

**Comment by BBchicken-9527** [comment]
升级一下看看，我在1.15.3中没有发现这个问题；还有一种可能就是你数据已经显示全了所以没有滚动的效果；讲表格高度收窄看看
