### ISSUE TITLE
[Bug]本地数据集在同步时，sql报错，配置数据源时正常

### ISSUE THREAD

**Issue by y1328676847** [dataease/dataease#3516]
**DataEase 版本**
1.15.2/1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器 106.0.5249.119

**Bug 描述**
本地在配置数据源和数据集的时候，能够正常的获取到数据，但是保存后的数据同步就会报sql错误。demo 无问题，小南也无问题。

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/74576406/198538552-4ce7d279-bd0b-49bb-809d-9570853f215d.png)
![image](https://user-images.githubusercontent.com/74576406/198538640-79b2170e-ace4-4c2e-b137-64e7ab545c2c.png)
2.
![image](https://user-images.githubusercontent.com/74576406/198538846-267767ac-2646-48de-b6f1-368453a162e6.png)
3.
![image](https://user-images.githubusercontent.com/74576406/198539582-fe81366f-383c-4f11-bc1f-bb0dd69e3afa.png)
![image](https://user-images.githubusercontent.com/74576406/198539679-d95351c4-3995-4555-82f6-af1d9704e35b.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，但从异常上来看是sql语句写的有问题，是API数据源吗？
