### ISSUE TITLE
[Question] kettle issue in uploading excel files (cluster mode)

### ISSUE THREAD

**Issue by alifzl** [dataease/dataease#3523]
I deployed dataease 1.14.0 in cluster mode and I created a kettle with version 9.3. 
when I try to upload an excel file in DE, i face this error:

<img width="1542" alt="image" src="https://user-images.githubusercontent.com/12857891/198819266-475c4a94-c518-4f97-9f47-81da5fec4d3a.png">

my kettle cluster is based on docker-compose:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/12857891/198819294-5d3c4c83-08c4-41ae-99ec-6777cdb54638.png">
also on system params kettle cluster is connected and connection is verified.

Questions:
1. Can you recommend a proper kettle cluster with it's proper configurations in order to work things up?
2. Can you advise for "How to create database-based repository in PDI"?

so many thanks.

**Comment by xuwei-fit2cloud** [comment]
Thanks for your interest!
We are currently interfacing with Kettle version v8.3 and have not yet interfaced with v9.3, so we need to do some testing works.
Also, we don't support dataease-based repo yet.

**Comment by alifzl** [comment]
thanks for the kind response. I wonder is there any document explaining how to integrate dataease with kettle v8.3? speaking of CARTE database repository creation and stuff? thanks in advance.

**Comment by tjlygdx** [comment]
backend/src/main/java/io/dataease/service/dataset/ExtractDataService.java
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/12710377/223959509-87e11bab-d526-4fbd-b533-eb85e38f3cd1.png">
You can adjust the way to call kettle here.
