### ISSUE TITLE
[Bug] 手机端时间过滤组件展示问题

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3536]
**DataEase 版本**
v1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
手机端谷歌浏览器

**Bug 描述**
<img width="498" alt="image" src="https://user-images.githubusercontent.com/45852479/198947616-2c6ec156-6784-4025-8c1f-02574b4539fe.png">

**Bug 重现步骤(有截图更好)**
无

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这是个已知问题，我们后续版本会对移动端所用的控件进行改造。
