### ISSUE TITLE
[Question]基础镜像是否支持ARM架构运行

### ISSUE THREAD

**Issue by eanfs** [dataease/dataease#3537]
registry.cn-qingdao.aliyuncs.com/dataease/fabric8-java-alpine-openjdk8-jre:edge-chromium
基础镜像是否支持ARM架构运行？

**Comment by xuwei-fit2cloud** [comment]
基础镜像是支持在ARM架构下运行的。
![图片](https://user-images.githubusercontent.com/1892127/198954931-713a41b2-1c97-4ef4-a73b-03f94b27796d.png)

**Comment by eanfs** [comment]
好的，谢谢
