### ISSUE TITLE
[Feature]建议优化数据集提示文字的大小

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3546]
**请描述您的需求或者改进建议.**
如图所示，在视觉感受上，建议优化下字号相对情况。
![image](https://user-images.githubusercontent.com/48945409/198965767-be7f7a44-a7d7-4304-b472-f42d9a41d7a1.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们调整一下。
