### ISSUE TITLE
[Bug] SQLServer 2000 数据源连接提示无效数据源：“数据库schema为空”

### ISSUE THREAD

**Issue by gaohonghai** [dataease/dataease#3552]
**DataEase 版本**
V1.15.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 106.0.5249.119（正式版本） (x86_64)

**Bug 描述**
1、使用默认的数据库驱动提示 无效数据源：“数据库schema为空”；
2、怀疑是默认驱动不支持，自主上传了相关版本的 jar，依旧提示上述报错。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/92966838/198973141-61b2a214-e6ec-40f5-9845-b9625ec05ad0.png)
![image](https://user-images.githubusercontent.com/92966838/198973176-414a34e6-7ddc-4b8f-afd1-c07ef0c3f452.png)

**Comment by BBchicken-9527** [comment]
<img width="651" alt="image" src="https://user-images.githubusercontent.com/84372766/199147880-24f88b33-10f9-4f11-8fd8-6c7c5d8f20a2.png">
感谢反馈，设置完基础信息后是需要点击获取schema的确定好schema后就不会有这个提示了

**Comment by gaohonghai** [comment]
![image](https://user-images.githubusercontent.com/92966838/199382227-b853af58-dfb4-436e-9498-78d15e168bb2.png)
点击schema之后，提示 class not found；驱动选择的是自主上传的 SQLServer 2000 的jar；

使用default驱动，提示驱动不兼容
![image](https://user-images.githubusercontent.com/92966838/199382638-8b832a49-89c6-4188-af9d-cb2a0e00d688.png)

**Comment by BBchicken-9527** [comment]
感谢反馈目前暂不支持2000版本，我们会考虑在后续版本中加入，给你的使用带来不便非常抱歉
