### ISSUE TITLE
[Bug]瀑布图没有图例选项

### ISSUE THREAD

**Issue by lichang950215** [dataease/dataease#3556]
**DataEase 版本**
V1.15.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
EDGE

**Bug 描述**
瀑布图没有图例选项

**Bug 重现步骤(有截图更好)**
![6CBA0D0D-F3DB-4e6a-BC3D-CD3C01D31C17](https://user-images.githubusercontent.com/68042506/198982480-a3935415-4483-4baa-9b11-25710ce67e75.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，确实是这样的，目前瀑布图图例是不支持设置的
