### ISSUE TITLE
[Bug]符号地图，添加坐标后地图没有反应，并且更改样式也没有反应

### ISSUE THREAD

**Issue by lichang950215** [dataease/dataease#3557]
**DataEase 版本**
V1.15.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
EDGE，CHROME

**Bug 描述**
符号地图，添加坐标后地图没有反应，并且更改样式也没有反应

**Bug 重现步骤(有截图更好)**
数据库字段：
[TABLE_MAP.xlsx](https://github.com/dataease/dataease/files/9900079/TABLE_MAP.xlsx)
截图：
![1D4B4B73-D0A8-4589-BA2C-E3E564EFDDDF](https://user-images.githubusercontent.com/68042506/198982742-f6d1c20d-a6c5-47c0-a9b2-19b61199a8b4.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们内部排查一下

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
