### ISSUE TITLE
[Bug] 本地开发使用mysql 8.0 时，页面出错

### ISSUE THREAD

**Issue by eanfs** [dataease/dataease#3581]
**DataEase 版本**
1.15.4

**运行方式(安装包运行 or 源码运行 ?)**
源码运行 

**浏览器版本**
Chrome

**Bug 描述**
本地开发使用mysql 8.0 时，页面出错
![image](https://user-images.githubusercontent.com/5432110/199182793-aac8b0e4-28ce-48b7-8938-dcc1a5f4bb0e.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，此处确实是有问题，可以参见：
https://github.com/dataease/dataease/commit/53c43967e3cd03db93383150c8d6e0571108139a
