### ISSUE TITLE
[Bug] api数据源添加选择字段‘[UUID]’，数据表保存成功，数据源校验失败

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3585]
**DataEase 版本**
v1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
api数据源添加数据表，字段选择'[UUID]'，保存成功后，数据源校验失败

**Bug 重现步骤(有截图更好)**
1.数据集保存成功
![image](https://user-images.githubusercontent.com/45852479/199190503-facc81ac-7695-4399-be55-790c5dcd4175.png)
2.数据源校验失败
![image](https://user-images.githubusercontent.com/45852479/199190705-85b05b0c-53ec-40a8-84e0-3b92c02edd66.png)

附：api对应json
![image](https://user-images.githubusercontent.com/45852479/199190841-3d14b557-6d53-434b-bf61-0ed40c3eceb4.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.16.0版本已处理，请更新版本。
