### ISSUE TITLE
[Bug] 编辑视图页面，字段名修改后，视图页面及左侧字段都没有修改名称

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3587]
**DataEase 版本**
v1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
编辑视图页面，字段名修改后，视图页面及左侧字段都没有修改名称

**Bug 重现步骤(有截图更好)**
1.初始视图样式
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/45852479/199200565-73c4c92c-ee91-49f3-b0ac-cb4964a09d4d.png">
2.修改字段名称
<img width="869" alt="image" src="https://user-images.githubusercontent.com/45852479/199200681-564fa934-dfa5-46f3-a0dd-04b45bb7a0ef.png">
3.视图中字段名及左侧都没有修改
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/45852479/199200806-937d9dde-0e68-438f-aeea-dcab77218c59.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前是这样设计的，你可以理解为添加进入视图后是单独的一个对象，但确实使用体验上会有割裂感，嗯...但是改动的话已目前系统来说可能会改动很大，我们再考虑一个更安全更好的方法
