### ISSUE TITLE
[Bug]富文本无法添加超链接

### ISSUE THREAD

**Issue by lichang950215** [dataease/dataease#3594]
**DataEase 版本**
V1.15.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
EDGE.CHROME

**Bug 描述**
富文本无法添加超链接，修改保存没反应

**Bug 重现步骤(有截图更好)**
1.添加富文本文字超链接无法保存
2.无法跳转
3.原有版本都可以

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前没有重现这个问题。
您可以在本周更新到1.16.0版本试试。
