### ISSUE TITLE
[Feature]可否放個离线安装包在github

### ISSUE THREAD

**Issue by asakous** [dataease/dataease#3598]
**请描述您的需求或者改进建议.**
fit2cloud 需中國手機注冊。非中國地區很難下載。

**Comment by yayanpei** [comment]
请提供您的 email 地址，我们将 Dataease 的下载地址发送到您的邮箱。

**Comment by asakous** [comment]
> 请提供您的 email 地址，我们将 Dataease 的下载地址发送到您的邮箱。

asakous@gmail.com

**Comment by yayanpei** [comment]
> > 请提供您的 email 地址，我们将 Dataease 的下载地址发送到您的邮箱。
> 
> [asakous@gmail.com](mailto:asakous@gmail.com)

下载地址已发送至您的邮箱，请查收。

**Comment by asakous** [comment]
> > > 请提供您的 email 地址，我们将 Dataease 的下载地址发送到您的邮箱。
> > 
> > 
> > [asakous@gmail.com](mailto:asakous@gmail.com)
> 
> 下载地址已发送至您的邮箱，请查收。

感謝，已下載
