### ISSUE TITLE
[Feature] 视图计算字段和数据集计算字段建议保持一致

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3599]
**请描述您的需求或者改进建议.**
DataEase版本 v1.15.3
视图计算字段和数据集计算字段样式建议保持一直，如图：
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/45852479/199376674-6eb7a618-e5c5-4e9c-9798-e4ad906a46fe.png">
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/45852479/199376876-21bc647e-7e2a-4924-9206-8b9f908c5bc0.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们后续版本会调整。
