### ISSUE TITLE
[Bug]偶尔输入框无法删除，只能全选后修改

### ISSUE THREAD

**Issue by wxcen** [dataease/dataease#36]
**DataEase 版本**

v1.0.0-rc2

**浏览器版本**
 91.0.4472.114（正式版本） (x86_64)

**Bug 描述**
偶尔输入框无法删除，只能选择后输入替换修改

**Bug 重现步骤(有截图更好)**

**Comment by xuwei-fit2cloud** [comment]
无法重现

**Comment by xuwei-fit2cloud** [comment]
始终无法复现
