### ISSUE TITLE
[Bug] 视图计算字段从管理列表删除后，对应视图所拖入列及图表未删除

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3600]
**DataEase 版本**
v1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
视图计算字段从管理列表删除后，对应视图所拖入列及图表未删除

**Bug 重现步骤(有截图更好)**
1.新建视图计算字段
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/45852479/199377438-d63e3174-2172-451e-a788-ee6e8cfd04ab.png">
2.拖入所在视图指标列
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/45852479/199377902-cff5408f-cb40-4206-9157-3cf2f09876b3.png">
3.从视图计算字段中删除，视图指标列和图标中依旧存在该列
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/45852479/199378017-0406c667-89e4-4968-86c5-82724ad95bb3.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快优化
