### ISSUE TITLE
[Bug] 集群模式校验Doris报错数据源无效

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3607]
**DataEase 版本**
1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.报错如图所示：
![image](https://user-images.githubusercontent.com/82353425/199417174-34348473-ebec-44d4-92fb-0ea8250d05cb.png)

超过最大连接数了。

**Comment by xuwei-fit2cloud** [comment]
可以尝试调整一下 max_user_connections 的值，比如设置成 500 试试？
