### ISSUE TITLE
[Bug] mongodb编辑数据源是没有加载所选驱动

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3620]
**DataEase 版本**
v1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
mongodb编辑数据源是没有加载所选驱动

**Bug 重现步骤(有截图更好)**
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/45852479/199475478-632bd723-7ed7-4718-ac22-74d52e7a8298.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，你这个是历史数据吗？在出驱动功能之前的数据源是会显示为空的
