### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by littleSaltZz** [dataease/dataease#3632]
pgsql数据库 字段类型int8范围是-9223372036854775808到9223372036854775807 最长有19位 PgConstants内DEFAULT_INT_FORMAT为"numeric(18,0)" 
![c6e60fade3e0a83a58129700eab05a0](https://user-images.githubusercontent.com/69560211/199678847-7114db14-fd76-4211-9b7a-d5b6a08bb9da.jpg)

![66b4e61690fd01a1a481532c97540a2](https://user-images.githubusercontent.com/69560211/199678742-aba43b87-4bdb-4939-bf77-3989bd20f0c6.jpg)

**Comment by BBchicken-9527** [comment]
感谢反馈， 我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
