### ISSUE TITLE
[Bug] API 数据源数据同步失败

### ISSUE THREAD

**Issue by Zruo** [dataease/dataease#3637]
**DataEase 版本**
v1.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌 104.0.5112.81

**Bug 描述**
配置数据源喝数据集都成功，在数据集执行定时同步时，同步失败出现报错：jsonPath 路径错误：path can not be null or empty 

**Bug 重现步骤(有截图更好)**
1.配置数据源
![1667469450293](https://user-images.githubusercontent.com/33833680/199692245-5dd5b55b-cb18-447b-8f7c-150e0fc1d59f.jpg)
![image](https://user-images.githubusercontent.com/33833680/199692457-862e94dc-3cf8-4ef1-8c9d-a85c40d82ba3.png)

2.配置数据集
![image](https://user-images.githubusercontent.com/33833680/199693317-5b1e49eb-1a25-43ef-b862-a5380840a9d5.png)
![image](https://user-images.githubusercontent.com/33833680/199693365-72d0c371-e3e2-4073-a10b-996938ba832b.png)

3.定时同步失败
![image](https://user-images.githubusercontent.com/33833680/199692733-36d402a9-b77e-47a0-b781-6ea27c44569b.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前环境中没有发现你说的问题，目前已经有新版本发布，你可以升级后再尝试看看
