### ISSUE TITLE
[Bug]"JMS运维安全审计大屏" 应改名为 "JumpServer 运维安全审计大屏"

### ISSUE THREAD

**Issue by maninhill** [dataease/dataease#3638]
<img width="912" alt="image" src="https://user-images.githubusercontent.com/41712985/199734254-9ed36e20-dadb-41d9-a4fe-2ca3d7ac5e9c.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
