### ISSUE TITLE
[Bug] 点击进入【应用】模块，控制台报错

### ISSUE THREAD

**Issue by maninhill** [dataease/dataease#3639]
**DataEase 版本**

1.16

**运行方式(安装包运行 or 源码运行 ?)**

安装包

**Bug 描述**

<img width="715" alt="image" src="https://user-images.githubusercontent.com/41712985/199741264-40e781b6-85a5-463b-9600-3eaa19073fcc.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
