### ISSUE TITLE
[Bug]AntV堆叠柱状图，指标排序不准确

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#3640]
**DataEase 版本**
v1.16

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 106.0.5249.119（正式版本） (x86_64)

**Bug 描述**
AntV堆叠柱状图，指标排序不准确
Echrts的堆叠柱状图也有相同的问题

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/89771514/199877342-e1e4fa9d-4b02-49e6-834c-4c1be32ffa92.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，此问题为已知问题，目前堆叠项会影响到排序的计算，我们正在讨论如何优化这里
