### ISSUE TITLE
饼图联动其它组件，渲染出现卡顿[Bug]

### ISSUE THREAD

**Issue by Xiezhenfeng** [dataease/dataease#3641]
**DataEase 版本**

1.15
**运行方式(安装包运行 or 源码运行 ?)**
all

**浏览器版本**
chorme

**Bug 描述**
饼图联动其它组件，饼图点击出现卡顿、页面性能差

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，大概的数据量是多少呢，还有仪表板存在多少视图，每个视图大概的数据量是什么
