### ISSUE TITLE
[Bug] 计算字段Round保留两位数，但是数据还是超过两位数

### ISSUE THREAD

**Issue by xhbmud** [dataease/dataease#3643]
**DataEase 版本**
v1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
curl -sSL https://github.com/dataease/dataease/releases/latest/download/quick_start.sh | sh

**浏览器版本**
chrome 96.0.4664.45

**Bug 描述**
导入excel数据，添加一个列求平均的计算字段，使用Round保留两位小数，还是超过2位小数

**Bug 重现步骤(有截图更好)**
1.数据集
![image](https://user-images.githubusercontent.com/4849898/199903599-d8c6fcf1-1c6c-4884-8c71-b8fc1b14d146.png)
2.计算计算公式
![image](https://user-images.githubusercontent.com/4849898/199903658-691bd310-3271-4a50-beb4-4d0dd4909d82.png)
3.数据集字段管理
![image](https://user-images.githubusercontent.com/4849898/199903724-9d54077e-6d67-4e8d-a40b-8009708daa18.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前设计如此，前端保留8位小数，不够用0代替；确实会存在你说的这个问题，我们开会讨论一下这个地方的处理

**Comment by xhbmud** [comment]
> 感谢反馈，目前设计如此，前端保留8位小数，不够用0代替；确实会存在你说的这个问题，我们开会讨论一下这个地方的处理

Round(x,2)不是保留小数点后2位吗？为啥后面还有那么多0呢？

**Comment by BBchicken-9527** [comment]
后面补零并不是数据库层面的操作...就是说从数据库拿出来确实是两位小数，但我们会给他补0所以你看到的还是8位小数；我们也在讨论解决的办法请耐心等待
