### ISSUE TITLE
[Bug]antV 富文本在外部链接中显示下移

### ISSUE THREAD

**Issue by mayjiang0203** [dataease/dataease#3645]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**
1.16 安装包运行

**浏览器版本**

**Bug 描述**
边界页面对齐后，外部链接显示的下移了很多，导致原本对齐的出现了错位

**Bug 重现步骤(有截图更好)**
1.边界页面
![image](https://user-images.githubusercontent.com/9443637/199932041-fde54c66-6ea0-495d-b5ee-38d68ffbb44c.png)

2. 外部链接显示页面
![image](https://user-images.githubusercontent.com/9443637/199932119-652522a0-c8f4-4150-adf2-b2b821ce893f.png)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，看你的截图是过滤组件但是标题说的是富文本，所以不是很清楚你说的是什么问题，方便可以具体描述一下或者给出更多的截图嘛
