### ISSUE TITLE
[Bug]antV 分组柱状图，自动轴临界值，标签显示不全

### ISSUE THREAD

**Issue by mayjiang0203** [dataease/dataease#3646]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**
1.16

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/9443637/199934465-4b3099d1-1042-409a-a201-65cc06bc86e5.png)

![image](https://user-images.githubusercontent.com/9443637/199934653-818acacc-ee13-4361-91ea-80fe7e21d736.png)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，受限于组件原因此处确实有此问题，我们也在想更好的处理方式但会需要一点时间。
