### ISSUE TITLE
数据库的请求超时时间建议不要限制在300s，复杂的sql语句查询较慢，300s的超时时间不够用

### ISSUE THREAD

**Issue by zhangshihao930112** [dataease/dataease#3648]
请求超时时间建议不要限制在300s，复杂的sql语句查询较慢，300s的超时时间不够用

**Comment by yayanpei** [comment]
感谢您的反馈，改需求已经加入V1.17（12.1日发布）的优化清单中。

**Comment by yayanpei** [comment]
感谢反馈，您可以在数据源编辑窗口，展开高级设置，设置查询超时时间，如下
<img width="639" alt="image" src="https://user-images.githubusercontent.com/84168063/200210716-c125b266-6424-4ab8-a95e-209958796b9b.png">

**Comment by zhangshihao930112** [comment]
已经在高级设置中，设置了查询超时时间，但是执行自动更新时仍然会失败，看提示应该还是连接超时了，
![微信截图_20221107152537](https://user-images.githubusercontent.com/85295604/200250972-9e755854-bcce-46c4-8194-403f89b00917.png)
![微信截图_20221107152805](https://user-images.githubusercontent.com/85295604/200250981-6303c171-ed68-4a16-a103-97763941fa3b.png)

**Comment by yayanpei** [comment]
超时时间已经比较大了，如果仍然出现time out 的情况，建议您检查一下网络，或者优化一下 sql 语句
