### ISSUE TITLE
[Feature]建议通过应用创建仪表板时可以选择存量数据源

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3656]
**请描述您的需求或者改进建议.**
目前通过应用创建仪表板时需要填写新的数据源信息，建议增加选项，可以选择已有数据源或新增数据源。
在一些场景下是希望可以在我自己已有的数据源中选择现有的。例如：

1.之前已经有一个自己在使用的数据源，想直接使用这个；
2.多个应用都需要使用同一个链接，第一次创建了之后后面只想要选择之前已创建的；
3.更倾向于先在数据源处维护链接信息，再在创建时选择。

![image](https://user-images.githubusercontent.com/48945409/200226954-670d4433-01c6-40e2-9e94-8c024e0beeaf.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们会加入后续优化列表中。
