### ISSUE TITLE
SQL ERRORerrCode = 2, detailMessage = There is no scanNode Backend available.[10002: not alive][Question]

### ISSUE THREAD

**Issue by qk693516337** [dataease/dataease#3664]
使用定時SQL數據集時
報錯 SQL ERRORerrCode = 2, detailMessage = There is no scanNode Backend available.[10002: not alive]
且定時任務失敗 此錯誤從使用離綫包本地升級后開始

**Comment by xuwei-fit2cloud** [comment]
你好，可以用 docker ps -a 命令查看一下 doris-be 的状态，看看是否正常运行。
如正常运行，则可以进入 doris-fe 中查看该be节点是否被加入到集群中；
如非正常运行，可以尝试dectl reload重新启动该服务，如还未正常运行，可以联系社区用户群里的技术支持。
