### ISSUE TITLE
[Bug] DataEase 接入 Elasticsearch 6.3.2 ，添加数据库数据集报错：java.lang.ArrayIndexOutOfBoundsException: 2

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#3666]
**DataEase 版本**
v1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome
版本 107.0.5304.87（正式版本） (arm64)

**Bug 描述**
[Bug] DataEase 接入 Elasticsearch 6.3.2 ，添加数据库数据集报错：java.lang.ArrayIndexOutOfBoundsException: 2

**Bug 重现步骤(有截图更好)**
1. Elasticsearch 版本 6.3.2
<img width="605" alt="image" src="https://user-images.githubusercontent.com/30063018/200278255-5053a5ba-0918-4a56-98b0-6ba2cb8030f7.png">
2. DataEase 数据源接入正常
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/30063018/200278484-7425f56f-ff08-4060-a9d1-3dc8f361b114.png">
3. 添加数据库数据集报错
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/30063018/200279045-75f15268-6c05-425e-a30d-ffe4b204b6c2.png">
4. 添加 SQL 数据集正常
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/30063018/200279274-7ee5a126-6439-49af-9f4e-88799bb0b379.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
