### ISSUE TITLE
[Bug] API 数据集立即同步报错 (too many filtered rows)

### ISSUE THREAD

**Issue by zhangchaochao-fit2cloud** [dataease/dataease#3668]
**DataEase 版本**
v1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge
版本 107.0.1418.35 (正式版本) (x86_64)

**Bug 描述**
API 数据集定时任务同步不到数据，可能是因为数据中存在null，保存到doris的时候会导致类型问题
应该根据数据集中定义好的数据类型来进行设置默认值（如果doris不允许为空的话）

**Bug 重现步骤(有截图更好)**
1. 创建 API 数据源，可以预览到数据，选择全部列，默认类型都是文本
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/70739359/200282211-79975d17-1969-495b-a1b2-1d05244c4ff4.png">
2. 创建 API 数据集，点击更新信息发现都是任务失败
<img width="955" alt="image" src="https://user-images.githubusercontent.com/70739359/200282778-26d89612-fa47-4c74-8352-f740cd4b5808.png">
3. 详细信息
<img width="652" alt="image" src="https://user-images.githubusercontent.com/70739359/200282850-84146caf-0878-46fb-9ddb-48647c7aca33.png">
4.API数据
[data.zip](https://github.com/dataease/dataease/files/9950337/data.zip)

**Comment by BBchicken-9527** [comment]
感谢反馈，你说的存在null的情况我在环境上看了没有问题，方便问一下你大概的数据量吗

**Comment by zhangchaochao-fit2cloud** [comment]
后面有个 zip 包，JSON 在压缩包里面

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
