### ISSUE TITLE
[Bug]创建定时任务时，写的增量 SQL 语句保存后会出现不一致的情况

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3678]
**DataEase 版本**
v1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 105

**Bug 描述**
创建定时任务时，写的增量 SQL 语句保存后会出现不一致的情况，变成之前别的任务的语句。

**Bug 重现步骤(有截图更好)**
1.在数据集模板新增定时任务“new1”。
![image](https://user-images.githubusercontent.com/48945409/200508769-b61badc2-4d86-4602-848b-c704ea8829f9.png)

2.在系统管理的数据同步功能下新增定时任务“new2”与“new3”，发现保存后他们的语句均为 new1 的语句。详情见录屏：
https://user-images.githubusercontent.com/48945409/200509006-dbedea19-0449-4a73-8bd0-7dcbd85931f4.mp4

**Comment by BBchicken-9527** [comment]
感谢反馈，我们修复一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.2版本已处理，请更新相关版本。
