### ISSUE TITLE
[Feature]建议选项卡组件的 Tab 标签可以自行配置位于上方或下方

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3679]
**请描述您的需求或者改进建议.**
如果在拉满全屏的场景下，会更希望 Tab 标签放置在下方的位置。
![image](https://user-images.githubusercontent.com/48945409/200510557-87cc9aa0-7630-46bf-a06b-1fc05814fdf2.png)

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到
