### ISSUE TITLE
插件问题

### ISSUE THREAD

**Issue by zhaomen** [dataease/dataease#3680]
**DataEase 版本**
1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge
版本 107.0.1418.35 (正式版本) (arm64)

**Bug 描述**
3dpie插件加载错误，
1.15.0版本只是样式不能显示，
1.16.0版本插件图标都没有

**Bug 重现步骤(有截图更好)**
1.截图1.15.0版本
![15191667456712_ pic](https://user-images.githubusercontent.com/37888994/200530023-8d7f7199-5c83-4202-a69c-503ad703ed26.jpg)

2.截图1.16.0版本
<img width="403" alt="image" src="https://user-images.githubusercontent.com/37888994/200531008-cb319fe1-9ee7-4624-9ab6-2681cd53b26b.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈。
从1.15升级到1.16，插件的SDK也会有相应的升级，可以重新编译一下3d饼图插件，重新升级一下插件试试。
我们最新版本的3d饼图，图标部分并没有问题，但样式部分确实存在问题，我们会尽快修复。
