### ISSUE TITLE
[Feature]关于 dectl 命令报错：语法错误的修改

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#3683]
**请描述您的需求或者改进建议.**
执行 dectl status 命令时，有一行报错：
`/usr/local/bin/dectl:行76: [[: 4.0: 语法错误: 无效的算术运算符 （错误符号是 ".0"）`

经排查 /usr/local/bin/dectl 脚本中，73 行：` df -H --output=avail,pcent /opt | tail -1 ` 获得的结果是 **4.0G** 
执行 74 行： `available_disk=${available_disk%?}` 后，available_disk 赋值为 4.0，
最后在 76 行 if 判断时  `if [[ $available_disk -lt 2 ]]` 无法做小数比较，导致报错： `/usr/local/bin/dectl:行76: [[: 4.0: 语法错误: 无效的算术运算符 （错误符号是 ".0"）`

**解决方法：**

 ` [[ $available_disk -lt 2 ]]`  改为` [ $available_disk \< 2.0 ]`

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们后续版本改进一下脚本。

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
