### ISSUE TITLE
[Feature]建议增加数据源复制功能

### ISSUE THREAD

**Issue by tcgdy0201** [dataease/dataease#3684]
**请描述您的需求或者改进建议.**
同一关系型数据库实例内会存在多个schema，现在数据源配置时，数据库（即schema）为必填项。
这就导致如果一个数据库实例可能需要配置N个数据源，重复性劳动过多。
建议能在数据源的编辑/删除按钮外，增加一个复制功能，那用户只需更改数据源名、数据库名即可。

**Comment by yayanpei** [comment]
感谢反馈，您的建议很不错，我们会优先考虑加入优化中。
