### ISSUE TITLE
engine_mysql和mysql区别

### ISSUE THREAD

**Issue by ccczhouxin** [dataease/dataease#3686]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/43168824/200717184-c063dc96-87c8-42e9-bdf2-8ed5ac9752f9.png)
你好，这个engine_mysql作用是什么呢，和mysql有没有区别呢

**Comment by xuwei-fit2cloud** [comment]
你好，DataEase有多种部署方式，如精简模式、本地模式和集群模式，这个地方的代码主要是用来处理不同部署模式下Excel数据集以及API数据集的数据的。
在精简模式下，Excel和API数据都存放在MySQL里，所以会使用engine_mysql；
其他模式下，Excel和API数据会存放在Doris里，所以使用engine_doris。

**Comment by ccczhouxin** [comment]
> 你好，DataEase有多种部署方式，如精简模式、本地模式和集群模式，这个地方的代码主要是用来处理不同部署模式下Excel数据集以及API数据集的数据的。 在精简模式下，Excel和API数据都存放在MySQL里，所以会使用engine_mysql； 其他模式下，Excel和API数据会存放在Doris里，所以使用engine_doris。

ok
