### ISSUE TITLE
[Feature]期望撤销、重做按钮执行成功时给提示，并且快速点击时不要有文字选中效果

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#3687]
**请描述您的需求或者改进建议.**
仪表板编辑页面的撤销、重做按钮在点击的时候没有提示也看不出来是否点击成功了，而且快速点击时会出现文字选中效果，体验不是太好。期望按钮做成 button，不要出现双击文字选中效果，且执行成功时给出提示让用户知道点击成功了。
<img width="1371" alt="WeChat4f56c3127a2f05c156a45861d869e54e" src="https://user-images.githubusercontent.com/30886198/200721279-33d9aa3c-eeba-4f6a-856c-c2216f49b2cc.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这部分我们改进一下，但一般撤销和重做都不会给出提示的。
