### ISSUE TITLE
[Question] JumpServer 应用的数据内容太长

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3690]
**请描述您的问题.**
系统从1.15升级到1.16，应用的图片内容是存储在数据库（外置数据库）上，insert超过数据max_allowed_packet限制，需要更改set global max_allowed_packet=67108864;

是不是应用上的图片都会存储在数据库上。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈。
由于JumpServer这个应用是内置的，我们这次是通过flyway插入数据库的方式实现的。
但在应用管理中上传应用的话，应用的图片等资源文件是存放在磁盘上，而不是数据库里，是不会存在上面的问题的。
后续版本我们改进一下这里。
