### ISSUE TITLE
mongodb 链接报错

### ISSUE THREAD

**Issue by DajunXU** [dataease/dataease#3693]
版本1.16本地启动创建mongodb数据源报错
![image](https://user-images.githubusercontent.com/33217333/200749568-02712042-a783-4020-ba5b-4816c3c75f32.png)

**Comment by xuwei-fit2cloud** [comment]
可以查看一下后台日志，看看具体的错误信息，是否是驱动问题。

**Comment by xuwei-fit2cloud** [comment]
如果要对接MongoDB的话，建议用MongoDB BI Connector，这个相对来说问题会少一些。

**Comment by DajunXU** [comment]
你好 ，调试出原因了， 是需要将代码里面drivers 文件复制到\opt\dataease\ 下面，我是根据开发文档1.14配置的，没有提到这一块，我加进去之后就好了
