### ISSUE TITLE
[Bug]代码里有个debugger，执行 npm run build 会提示异常信息

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#3696]
**DataEase 版本**
v1.16

**运行方式(安装包运行 or 源码运行 ?)**
源码

**Bug 描述**
frontend目录下执行 npm run build 会提示异常信息，见截图
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/89771514/200767932-db1927db-97cb-49f9-8e1c-eb913b63cb61.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
