### ISSUE TITLE
[Bug]视图数据与仪表板数据显示不一致

### ISSUE THREAD

**Issue by luty2018** [dataease/dataease#37]
**DataEase 版本**

1.0.0
**浏览器版本**

**Bug 描述**

![image](https://user-images.githubusercontent.com/36292514/123403888-73a9e400-d5db-11eb-8d67-9bbcef5d6e33.png)
![image](https://user-images.githubusercontent.com/36292514/123404093-7efd0f80-d5db-11eb-8156-0f95f5a86cad.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by ziyujiahao** [comment]
显示问题 视图的尺寸不一样 x轴的显示会不同 这个字段长度太长数据不太合理

**Comment by luty2018** [comment]
> 显示问题 视图的尺寸不一样 x轴的显示会不同 这个字段长度太长数据不太合理

这个是项目的uuid就是这么长， 或者是否允许在页面上取别名

**Comment by xuwei-fit2cloud** [comment]
一般来说不会以uuid来作为维度显示，而应该以该UUID对应的名称来显示
