### ISSUE TITLE
[Bug]国际飞书配置问题

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#3708]
**DataEase 版本**
v1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge
版本 107.0.1418.35 (正式版本) (64 位)

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1. 【单独】  启用了国际飞书，在个人信息处无法绑定国际飞书
![image](https://user-images.githubusercontent.com/96223591/200996344-e3ae0cb2-d29b-499e-ad7e-d19f3c6881bc.png)

2启用企业微信可以在个人信息处绑定国际飞书
![image](https://user-images.githubusercontent.com/96223591/200996552-3c1c94ca-b454-4dad-b2bd-eeba45771243.png)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.16.1版本已处理，请更新最新版本。
