### ISSUE TITLE
[Bug]配置定时报告任务推送失败

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#3710]
**DataEase 版本**
v1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
配置定时报告任务，lark 登录的账号，推送失败没错误信息。

**Bug 重现步骤(有截图更好)**
1.配置定时报告任务
2.失败详情
![img_v2_59fb02d5-61ed-4087-9217-cf5a548035eh](https://user-images.githubusercontent.com/96223591/201011859-f528fb90-a47c-4934-9a03-e37aa0eefd35.jpg)
3.报错内容如下：
![img_v2_2aaeea64-aa74-4fbc-9497-2ae53894263h](https://user-images.githubusercontent.com/96223591/201011919-57970fe5-fdc4-48f5-bffc-1e43a12eee52.jpg)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们排查处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
