### ISSUE TITLE
[Bug]矩阵模式视图全部叠在一起

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#3717]
**DataEase 版本**
v1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.开启辅助网格线
2.
![image](https://user-images.githubusercontent.com/96223591/201106360-0a42b5c9-94d4-4ffd-b7bf-b4e0525aebb5.png)

3.
![image](https://user-images.githubusercontent.com/96223591/201106530-0392cf9a-043f-444e-896d-e94e80062b1e.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复。

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
