### ISSUE TITLE
堆叠折线图“值轴/指标”与纵坐标的值不对应[Bug]

### ISSUE THREAD

**Issue by clearcode1124** [dataease/dataease#3718]
**DataEase 版本**
v1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome 106.0.5249.119（正式版本） （64 位）

**Bug 描述**

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/46983983/201232404-5b0d6261-6f9e-4261-b160-c3ad106eae77.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，方便说明一下原本应该是多少吗，并且需要确认一下是否存在重复数据，因为重复数据是会做集合的，还有就是你是否使用了堆叠项，如果使用堆叠项，视图展示将以指标的第一个值进行计算，剩余指标不是不参与的
