### ISSUE TITLE
仪表板大屏创建的公共链接无法访问

### ISSUE THREAD

**Issue by zhantiao** [dataease/dataease#3723]
**DataEase 版本**
1.15

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
版本 5.0.2.10 （32 位）

**Bug 描述**
创建的公共链接无法访问，白屏
![image](https://user-images.githubusercontent.com/67528597/201252498-29370d78-5cd7-4cc1-8c4a-3dc435e11759.png)

**Bug 重现步骤(有截图更好)**
1. 
![image](https://user-images.githubusercontent.com/67528597/201252647-b0d02d90-4f18-42ed-bb80-db100f6bcc95.png)

2.
![image](https://user-images.githubusercontent.com/67528597/201252682-55e1c39d-5439-44f1-b381-f255877368eb.png)

3. 浏览器无法访问公共链接

**Comment by BBchicken-9527** [comment]
感谢反馈，请问是所有的都出现这样的问题还是只有这一个是白屏的？

**Comment by zhantiao** [comment]
所有的都不行

**Comment by zhantiao** [comment]
> 谢谢，请问是所有的都出现这样的问题还是只有这个是白屏的？

所有都不行

**Comment by BBchicken-9527** [comment]
方便的话F12看一下有没有什么异常或者在给个视频什么的我们看一下你的操作，我们这边的环境是没有你说的问题的

**Comment by zhantiao** [comment]
https://user-images.githubusercontent.com/67528597/201273543-87fe5cb9-ea71-4ba7-8ac3-044b20582c0c.mp4

**Comment by zhantiao** [comment]
> 方便的话F12看一下有没有什么异常或者在给个视频什么的我们看一下你的操作，我们这边的环境是没有你说的问题的


https://user-images.githubusercontent.com/67528597/201273711-c5ef9215-c0d3-41f0-aa21-6ad6e2362f0c.mp4

**Comment by zhantiao** [comment]
> > 方便的话F12看一下有没有什么异常或者在给个视频什么的我们看一下你的操作，我们这边的环境是没有你说的问题的
> 
>  20221111-135645.mp4

Google Chrome 版本 107.0.5304.107（正式版本） （64 位）

**Comment by BBchicken-9527** [comment]
![image](https://user-images.githubusercontent.com/84372766/201298597-5e604ee8-b7b1-46e8-b6c9-fafcf4553abd.png)
看一下这个
我看你的index.js有点儿问题呀怎么可能三十多秒😱

**Comment by zhantiao** [comment]
> ![image](https://user-images.githubusercontent.com/84372766/201298597-5e604ee8-b7b1-46e8-b6c9-fafcf4553abd.png) 看一下这个 我看你的index.js有点儿问题呀怎么可能三十多秒😱

因为我那一次刷新使用的时浏览器的 “清楚缓存并硬性重新加载” 我的目的是想排除缓存的问题

**Comment by zhantiao** [comment]
![image](https://user-images.githubusercontent.com/67528597/201311732-9821b958-87ea-462c-8d37-4831ab6c876f.png)
在选择自己创建的大屏创建公共链接时，链接中甚至出现了null

**Comment by BBchicken-9527** [comment]
你可以参考一下我们的前后端部署的文档：https://dataease.io/docs/dev_manual/dev_deployment/tool/

**Comment by zhantiao** [comment]
> 你可以参考一下我们的前后端部署的文档：https://dataease.io/docs/dev_manual/dev_deployment/tool/

![image](https://user-images.githubusercontent.com/67528597/201863133-ce86acc9-264d-4920-8613-61ff45c5ca82.png)
我想知道这里为什么会是null呢？我是否缺失了某项配置，我在官网的文档中并未得到答案

**Comment by fit2cloud-chenyw** [comment]
为什么是null？
因为默认运行/打包方式是使用application-whole.properties配置文件 这里指定了server.servlet.context-path为空，如下图
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/67260074/202073966-7e849049-589f-45ef-84e3-e5c71244a55f.png">
[在前后端分离部署文档中](https://dataease.io/docs/dev_manual/dev_deployment/compile/?h=前后#12-nginx)
明确指定了分离部署的打包方式 如下图
<img width="975" alt="image" src="https://user-images.githubusercontent.com/67260074/202074187-1d4cc27d-a828-4862-bcaa-8f6aee30cf7a.png">
此时使用的是application-stage.properties配置文件，文件中指定了server.servlet.context-path=/de-api。
现在你明白了为什么是null，也明白了为什么要用官方文档中的部署方式。
