### ISSUE TITLE
[Bug]定时报告截图下图不完整问题

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#3724]
**DataEase 版本**
v1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
截图不完整

**Bug 重现步骤(有截图更好)**
1.配置 【长图】仪表板，定时报告邮箱 Lark 截图只有上半身
2.
![img_v2_1227c091-f23d-43ef-b10c-13cf83989b3h](https://user-images.githubusercontent.com/96223591/201253756-5ac078bd-0f2c-457a-b149-be73ac2c58a3.jpg)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，请问还有别的操作吗。我这边的环境是没有你说的这个问题的，或者给我多一些的异常方便我的判断，我这边大概添加了27个视图但依然没有出现你说的问题
