### ISSUE TITLE
[Feature]Lark 推送后续支持推送群组吗？

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#3726]
**请描述您的需求或者改进建议.**
Lark 推送后续支不支持推送群组咧，在把机器人加到群里直接发。
![img_v2_954a3fd3-39f6-482d-a423-6778bed4bdeh](https://user-images.githubusercontent.com/96223591/201260412-e0a86303-a4b5-419a-9752-dc00d8a2ef49.jpg)

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到，需要先调研一下。
