### ISSUE TITLE
[Bug]使用SQL聚合查询不添加别名时预览数据显示空白

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#3728]
**DataEase 版本**
1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新版本

**Bug 描述**
使用如下SQL创建SQL数据集时，预览数据最后一列不显示数据。
数据源使用的是 DataEase 内置 demo 数据源。
select t1.province,t1.num,sum(t2.gdp)
from demo_gdp_district_top100 t1
left join demo_gdp_by_city t2
on t1.province = t2.province
group by t1.province

**Bug 重现步骤(有截图更好)**
1. 不添加别名时不显示数据：
<img width="1715" alt="image" src="https://user-images.githubusercontent.com/30886198/201286013-4cde91a3-f2b6-4f5e-9f8c-cf3758dfbac9.png">
2. 添加别名后显示正常
<img width="1715" alt="image" src="https://user-images.githubusercontent.com/30886198/201286743-002933f4-2a6e-4317-b0bb-92bb6f0d91c3.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快优化

**Comment by BBchicken-9527** [comment]
经过我们讨论最后决定不做修改了，考虑到如果添加函数的字段后的字段名称的可读性以及一些函数可能会存在超长的问题

**Comment by liuboF2c** [comment]
目前的情况是预览时不显示数据但保存后却能查看到数据，是否应保证二者一致？
或者页面是否应提示一下应添加别名，否则很容易给使用者带来困扰且会被认为是 BUG

**Comment by BBchicken-9527** [comment]
确实。我们优化一下，感谢反馈
