### ISSUE TITLE
[Bug]SQL数据集，当变量不是放在最后的WHERE中会保存报错

### ISSUE THREAD

**Issue by zhangchaolei** [dataease/dataease#3731]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
使用如下SQL脚本计算metersphere的接口覆盖率，保存时报错
定位原因是因为变量不是放在最外层的WHERE中，确认前一版本无此问题

`SELECT
	t1.cover_num / t2.total_num 
FROM
	(
	SELECT
		count( t.url ) AS cover_num,
		'row_num' 
	FROM
		(
		SELECT
			x.api_scenario_id,
			x.case_id,
			x.case_name,
			x.method,
			x.project_id,
			x.url,
			project.NAME 
		FROM
			(
			SELECT
				api_scenario_reference_id.api_scenario_id AS api_scenario_id,
				api_scenario_reference_id.method AS method,
				api_scenario_reference_id.url AS url,
				api_scenario.project_id AS project_id,
				api_scenario.id AS case_id,
				api_scenario.NAME AS case_name 
			FROM
				api_scenario_reference_id
				LEFT JOIN api_scenario ON api_scenario_reference_id.api_scenario_id = api_scenario.id 
			WHERE
				LEFT ( api_scenario_reference_id.url, 1 )= '/' 
			GROUP BY
				api_scenario_reference_id.url,
				api_scenario_reference_id.method 
			) x
			LEFT JOIN project ON x.project_id = project.id 
		WHERE
			project.NAME = ‘${project_name}’
		) t 
	WHERE
		t.url IN (
		SELECT
			api_definition.path 
		FROM
			api_definition
			LEFT JOIN project ON api_definition.project_id = project.id 
		WHERE
			project.NAME = ‘${project_name}’
			AND api_definition.STATUS != "Trash" 
		) 
	) t1
	LEFT JOIN (
	SELECT
		count(*) AS total_num,
		'row_num' 
	FROM
		api_definition
		LEFT JOIN project ON api_definition.project_id = project.id 
	WHERE
		project.NAME =  ‘${project_name}’
	AND api_definition.`status` != "Trash" 
	) t2 ON t1.row_num = t2.row_num
	`

![image](https://user-images.githubusercontent.com/29458304/201314727-13bc306a-5d80-4a4e-8db7-f9646c2715d3.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们修复一下

**Comment by JunTech** [comment]
+1

**Comment by yayanpei** [comment]
感谢您的反馈，问题已经收集，issue我们先关闭了
