### ISSUE TITLE
[Bug]同一个SQL数据集，新建两个不同的增量更新sql任务-，发现新建后一sql任务前一个的sql也会变成后一个

### ISSUE THREAD

**Issue by zhangshihao930112** [dataease/dataease#3732]
**DataEase 版本**
1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
101.0.4951.41（正式版本） （64 位）

**Bug 描述**
同一个SQL数据集，新建两个不同的增量更新sql任务-，发现新建后一sql任务前一个的sql也会变成后一个

**Bug 重现步骤(有截图更好)**
1.同一个数据集，新建一个增量更新任务，并写参数sql
2.再新建一个增量更新sql任务，并写参数sql与第一个任务不同
3.查看第一个任务发现变成了第二个任务的sql

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
