### ISSUE TITLE
sql数据集不支持日期范围检索[Bug]

### ISSUE THREAD

**Issue by Jarry520** [dataease/dataease#3733]
**DataEase 版本**

v1.54
**运行方式(安装包运行 or 源码运行 ?)**

安装包运行
**浏览器版本**

google 107.0.5304.110（正式版本） (arm64)
**Bug 描述**
统一数据源，使用数据库数据集直连，仪表盘中可以使用日期范围进行检索，使用sql数据集查询出来的数据配置仪表盘后无法进行日期检索，一检索就会出现数据没有的现象。

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/108266979/201572595-3374a5ad-717b-4447-b247-959ae26ac215.png)
数据格式，这是使用数据库数据集 可以正常进行日期检索。
2.同样的数据 改为sql数据集后，便无法实现日期范围检索。
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境是没有发现你说的问题的，方便发一下 sql语句看一下吗我们排查一下，还有就是有没有什么异常的提示，不管是前端的还是后端的都可以

**Comment by Jarry520** [comment]
with `hzb` as 
(select * from dwd_zhuyewu_huizongbiao),
`sjb` as(
select * from dwd_zhuyewu_shoujiebiao),
`sjqzb` as(
select * from dwd_zhuyewu_shoujie_qianzhibiao),
`fjb` as(
select * from dwd_zhuyewu_fujiebiao)
select t1.* from (
(select dt, sxsqjs as index_value, '授信申请件数' as index_key, app_id from `hzb`)UNION ALL
(select dt, sxtgjs as index_value, '授信通过件数' as index_key, app_id from `hzb`)UNION ALL
(select dt, yxsqjs as index_value, '用信申请件数' as index_key, app_id from `hzb`)UNION ALL
(select dt, yxsqje as index_value, '用信申请金额' as index_key, app_id from `hzb`)UNION ALL
(select dt, yxtgjs as index_value, '用信通过件数' as index_key, app_id from `hzb`)UNION ALL
(select dt, yxtgje as index_value, '用信通过金额' as index_key, app_id from `hzb`)UNION ALL
(select dt, fkcgjs as index_value, '放款成功件数' as index_key, app_id from `hzb`)UNION ALL
(select dt, fkcgje as index_value, '放款成功金额' as index_key, app_id from `hzb`)UNION ALL
(select dt, qzfkjs as index_value, '前置放款件数' as index_key, app_id from `hzb`)UNION ALL
(select dt, qzfkje as index_value, '前置放款金额' as index_key, app_id from `hzb`)UNION ALL
(select dt, hzfkjs as index_value, '后置放款件数' as index_key, app_id from `hzb`)UNION ALL
(select dt, hzfkje as index_value, '后置放款金额' as index_key, app_id from `hzb`)UNION ALL
(select dt, hkjs as index_value, '还款件数' as index_key, app_id from `hzb`)UNION ALL
(select dt, hkje as index_value, '还款金额' as index_key, app_id from `hzb`)UNION ALL
(select dt, azcg as index_value,'安装成功' as index_key, app_id from `sjb`)UNION ALL
(select dt, zccg as index_value,'注册成功' as index_key, app_id from `sjb`)UNION ALL
(select dt,sjsxsqjs as index_value,'首借授信申请件数' as index_key, app_id from `sjb`)UNION ALL
(select dt,sjsxtgjs as index_value,'首借授信通过件数' as index_key, app_id from `sjb`)UNION ALL
(select dt,sjyxsqjs as index_value,'首借用信申请件数' as index_key, app_id from `sjb`)UNION ALL
(select dt,sjyxsqje as index_value,'首借用信申请金额' as index_key, app_id from `sjb`)UNION ALL
(select dt,sjyxtgjs as index_value,'首借用信通过件数' as index_key, app_id from `sjb`)UNION ALL
(select dt,sjyxtgje as index_value,'首借用信通过金额' as index_key, app_id from `sjb`)UNION ALL
(select dt,sjfkjs as index_value,'首借放款件数' as index_key, app_id from `sjb`)UNION ALL
(select dt,sjfkje as index_value,'首借放款金额' as index_key, app_id from `sjb`)UNION ALL
(select dt,sjhkjs as index_value,'首借还款件数' as index_key, app_id from `sjb`)UNION ALL
(select dt,sjhkje as index_value,'首借还款金额' as index_key, app_id from `sjb`)UNION ALL
(select dt, sjqzsxtgjs as index_value, '首借前置授信通过件数' as index_key,app_id from `sjqzb`)UNION ALL
(select dt, sjqzyxsqjs as index_value, '首借前置用信申请件数' as index_key,app_id from `sjqzb`)UNION ALL
(select dt, sjqzyxsqje as index_value, '首借前置用信申请金额' as index_key,app_id from `sjqzb`)UNION ALL
(select dt, sjqzyxtgjs as index_value, '首借前置用信通过件数' as index_key,app_id from `sjqzb`)UNION ALL
(select dt, sjqzyxtgje as index_value, '首借前置用信通过金额' as index_key,app_id from `sjqzb`)UNION ALL
(select dt, sjqzfkjs   as index_value, '首借前置放款件数' as index_key,app_id from `sjqzb`)UNION ALL
(select dt, sjqzfkje   as index_value, '首借前置放款金额' as index_key,app_id from `sjqzb`)UNION ALL
(select dt, sjhzsxtgjs as index_value, '首借后置授信通过件数' as index_key,app_id from `sjqzb`)UNION ALL
(select dt, sjhzyxsqjs as index_value, '首借后置用信申请件数' as index_key,app_id from `sjqzb`)UNION ALL
(select dt, sjhzyxsqje as index_value, '首借后置用信申请金额' as index_key,app_id from `sjqzb`)UNION ALL
(select dt, sjhzyxtgjs as index_value, '首借后置用信通过件数' as index_key,app_id from `sjqzb`)UNION ALL
(select dt, sjhzyxtgje as index_value, '首借后置用信通过金额' as index_key,app_id from `sjqzb`)UNION ALL
(select dt, sjhzfkjs   as index_value, '首借后置放款件数' as index_key,app_id from `sjqzb`)UNION ALL
(select dt, sjhzfkje   as index_value, '首借后置放款金额' as index_key,app_id from `sjqzb`)UNION ALL
(select dt, fjsxsqjs as index_value, '复借授信申请件数' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjsxtgjs as index_value, '复借授信通过件数' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjyxsqjs as index_value, '复借用信申请件数' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjyxsqje as index_value, '复借用信申请金额' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjyxtgjs as index_value, '复借用信通过件数' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjyxtgje as index_value, '复借用信通过金额' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjfkjs   as index_value, '复借放款件数' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjfkje   as index_value, '复借放款金额' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjhkjs   as index_value, '复借还款件数' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjhkje   as index_value, '复借还款金额' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjqzsxtgjs as index_value, '复借前置授信通过件数' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjqzyxsqjs as index_value, '复借前置用信申请件数' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjqzyxsqje as index_value, '复借前置用信申请金额' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjqzyxtgjs as index_value, '复借前置用信通过件数' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjqzyxtgje as index_value, '复借前置用信通过金额' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjqzfkjs as index_value, '复借前置放款件数' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjqzfkje as index_value, '复借前置放款金额' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjhzsxtgjs as index_value, '复借后置授信通过件数' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjhzyxsqjs as index_value, '复借后置用信申请件数' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjhzyxsqje as index_value, '复借后置用信申请金额' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjhzyxtgjs as index_value, '复借后置用信通过件数' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjhzyxtgje as index_value, '复借后置用信通过金额' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjhzfkjs as index_value, '复借后置放款件数' as index_key, app_id from `fjb`)UNION ALL
(select dt, fjhzfkje as index_value, '复借后置放款金额' as index_key, app_id from `fjb`)
)t1;
上面的sql 数据集查出来的结果 是下面的图，配置透视图后 无法日期筛选
![image](https://user-images.githubusercontent.com/108266979/202100086-a814198c-20b3-470d-8047-4eab3e99f83f.png)

同样的数据 我将其在数据查询写入到star rocks 的一张表中，然后使用数据库数据集直连，再次配置仪表盘 就可以使用日期检索筛选功能，如下图所示
![image](https://user-images.githubusercontent.com/108266979/202100475-b9d8f1bc-994b-46c1-aa3e-6558599c398c.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复的
