### ISSUE TITLE
[Bug]上传 Excel 数据保存前无法直接修改字段类型为“地理位置”

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3738]
**DataEase 版本**
v1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装部运行

**浏览器版本**
Chrome 105

**Bug 描述**
上传 Excel 数据保存前无法直接修改字段类型为“地理位置”，如果字段类型为地理位置则需要先保存数据，在字段管理处再进行修改。

**Bug 重现步骤(有截图更好)**
1.上传 Excel 数据，有经纬度数据，但是在保存前能够选择的字段类型中，没有地理位置。
![image](https://user-images.githubusercontent.com/48945409/201613530-e92d8c37-fd9d-4cb4-b11c-5d1dd0d96e78.png)

2.保存后才能在字段管理处修改字段类型为“地理位置”。
![image](https://user-images.githubusercontent.com/48945409/201613635-195d0b15-a137-4b91-9c7a-3b36e5f46078.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，因为其实数据库本身是没有地理位置这种字段属性的，本质长他可能是一个字符串儿或者是小数，而地理位置是我们系统内部赋予这个字段的属性，所以在数据集创建时是无法看到地理位置这个字段属性的
