### ISSUE TITLE
[Bug]符号地图组件大小首次调整后后续无法调整

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3740]
**DataEase 版本**
v1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装部运行

**浏览器版本**
Chrome 105

**Bug 描述**
符号地图组件拖入仪表板后，首次可以编辑大小，当鼠标离开后再次编辑无法拖动其边界。

**Bug 重现步骤(有截图更好)**
**详情可见录屏：**
https://user-images.githubusercontent.com/48945409/201619154-d9867604-b85a-4086-bc9f-cbd623eaee4f.mp4

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，方便的话补充更为具体的操作方式或者异常，以便我们进一步排查
