### ISSUE TITLE
[Bug]下钻后的维度显示乱序

### ISSUE THREAD

**Issue by haipeng-fit2** [dataease/dataease#3742]
**DataEase 版本**
1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome版本 107.0.5304.110

**Bug 描述**
当钻取的下一层，用的是汉字（如下图的月份），排序就会出现乱序的情况，没办法对在钻取位置的维度自定义排序

**Bug 重现步骤(有截图更好)**
1.
<img width="415" alt="image" src="https://user-images.githubusercontent.com/81673899/201634317-5e9f40ca-7c40-44db-bd70-830a16c4c651.png">

2.
<img width="415" alt="image" src="https://user-images.githubusercontent.com/81673899/201634345-45858215-ce6e-4bfc-9078-ec3a4495639d.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，中文排序是按照ASCII码进行排序的
