### ISSUE TITLE
[Feature]在Echarts图表中支持数值格式设置

### ISSUE THREAD

**Issue by haipeng-fit2** [dataease/dataease#3743]
**请描述您的需求或者改进建议.**
在Echarts中指标项没有数值格式设置，对于需要使用Echarts独有视图（如组合图）的时候有些不方便，只能先在数据集处理好后再视图上使用
![截屏2022-11-14 下午6 27 41](https://user-images.githubusercontent.com/81673899/201637207-9cb29781-2869-4084-9baa-409cc70a15fd.png)

**Comment by yayanpei** [comment]
感谢反馈，组合图的数值格式不支持设置是已知问题，我们也在规划相关的优化。
