### ISSUE TITLE
希望能支持一下Mac OS

### ISSUE THREAD

**Issue by Seifon** [dataease/dataease#3744]
因为没有服务器，只能先在自己的Mac OS上安装体验，但是我发现官方的脚本并不支持

我也尝试了一下在线脚本安装，但出现了各种目录相关的报错

希望官方改进一下安装脚本，同时支持一下Mac OS安装

**Comment by yayanpei** [comment]
感谢反馈，不推荐您在Mac OS系统上安装，如果需要体验，可以先在demo环境（https://dataease.fit2cloud.com/#/login?redirect=%2Fpanel%2Findex）中试用。
