### ISSUE TITLE
[Bug] antv 散点图 pgsql 数值格式化报错: 数值 overflow 因为默认的 (18,8)

### ISSUE THREAD

**Issue by JunTech** [dataease/dataease#3745]
**DataEase 版本**
dev分支

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 102

**Bug 描述**
pgsql 数值格式化报错: 数值 overflow 因为默认的 (18,8)

**Bug 重现步骤(有截图更好)**
1.antv 散点图 新建视图
2.指标选择数值格式化（数值尽量大一点）
3.保存

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
