### ISSUE TITLE
local模式下添加SQL数据集定时同步报错

### ISSUE THREAD

**Issue by 56warmers** [dataease/dataease#3747]
**DataEase 版本**
1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包离线安装

**浏览器版本**
Chrome >= 62

**Bug 描述**

添加SQL数据集，选择定时同步，编写SQL语句，点确认时报错，报名内容如下：
“Data source connection exception: Communications link failure The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server”

**Bug 重现步骤(有截图更好)**
数据源校验成功，直连模式没问题
![image](https://user-images.githubusercontent.com/56248947/201818750-ed46c4cf-7b3b-4394-8969-5623cc4b12f3.png)
![image](https://user-images.githubusercontent.com/56248947/201818391-f9f92e8e-cc14-4b18-859b-b719aeea1030.png)
![image](https://user-images.githubusercontent.com/56248947/201818581-144e182f-d8b4-4622-92c4-2fca061c841c.png)

**Comment by 56warmers** [comment]
离线安装时修改过install.conf中的Doris数据库密码以及Doris的前后端端口，问题出现。
重新安装未更改Doris相关参数，则问题未复现。
安装时不可以在install.conf文件修改Doris相关配置吗？
能否说明以下问题原因呢？

**Comment by BBchicken-9527** [comment]
感谢反馈，因为离线安装的doris其实在读取配置文件的时候已将安装完成了，这代表着密码等信息其实已经设置完成了的，所以才会出现你说的这种情况，我们给出的配置文件主要的功能是读取的，当读取到与数据库本身实际存在出入产生的问题（如你改动了密码）

**Comment by 56warmers** [comment]
> 感谢反馈，因为离线安装的doris其实在读取配置文件的时候已将安装完成了，这代表着密码等信息其实已经设置完成了的，所以才会出现你说的这种情况，我们给出的配置文件主要的功能是读取的，当读取到与数据库本身实际存在出入产生的问题（如你改动了密码）

那请问在线安装时可以避免这个问题吗？就是可以在在线安装的过程中设置Doris的相关配置参数吗？没有尝试在线安装过。

**Comment by 56warmers** [comment]
> 感谢反馈，因为离线安装的doris其实在读取配置文件的时候已将安装完成了，这代表着密码等信息其实已经设置完成了的，所以才会出现你说的这种情况，我们给出的配置文件主要的功能是读取的，当读取到与数据库本身实际存在出入产生的问题（如你改动了密码）

感谢回答。
所以我总结下：
1.我的需求比较简单，就是简单地数据读取大屏展示，一般的simple模式即可实现；
2.但是我还需要实现定时更新，则必须放弃local模式，选择部署local模式；
2.部署local模式，按照说明需要默认添加Doris和Kettle；
3.依照说明，Kettle是内置的，暂不支持更改配置；
4.内置Doris也无法更改数据库密码等信息；
5.所以我只有两种选择：一是使用默认设置的Doris，二是使用外置的Doris；
综上，本来simple模式即可满足我的需求，但为了实现定时更新功能，就需要做出选择：
- 要么完全默认配置安装
- 要么就需要外置安装Doris
不知道我的理解正确吗？如有不对，还请答疑，感谢
