### ISSUE TITLE
[Bug]仪表板内容过多时导出pdf或图片，页面会一直处于加载状态

### ISSUE THREAD

**Issue by xiangsong97** [dataease/dataease#3753]
**DataEase 版本**
15.0和16.0均出现

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome 107.0.5304.107

**Bug 描述**
导出成pdf和图片会存在正在load中,配置使用的默认配置,服务器是8c16g,然后刷新频率设置为200分钟一次,视图加载提示关了和开着都试过,没用,还是有那个load的样式

**Bug 重现步骤(有截图更好)**
1. 直接到图片或pdf文件会出现load的样式,底下的数据看不清,数据量整体也不是很大,加载超过10秒的那2个用了缓存加载,导出还是有问题
![image](https://user-images.githubusercontent.com/86103786/201850913-667f04c0-749f-4737-881c-4ae3b99d3927.png)

2.
3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们排查一下问题，尽快修复。
