### ISSUE TITLE
[Feature] 定时报告状态运行中不明显

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3757]
**请描述您的需求或者改进建议.**
例如我在16：00设置了定时报告，每5分钟运行一次
![image](https://user-images.githubusercontent.com/82353425/201865059-5b0892c5-3be3-4d2d-8843-9aa6cdd55dfe.png)
在16:10分的时候应该要运行的，定时报告里面的状态一直是上次执行的成功状态，没有运行中。
后续能不能继续优化这些状态，或者说运行中可以点击，可以查看输出的日志。

**Comment by xuwei-fit2cloud** [comment]
点击任务名称，可以看到该任务的执行记录。
若单次执行失败，可以点击失败状态边上的图标查看具体的失败原因。
