### ISSUE TITLE
[Bug]一个 tab 下加入多个视图，公共链接打开后，饼图的图示里折叠切换按钮不可用

### ISSUE THREAD

**Issue by mayjiang0203** [dataease/dataease#3761]
**DataEase 版本**
1.16

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 最新版本

**Bug 描述**
一个 tab 下加入多个视图，公共链接打开后，饼图的图示里折叠切换按钮不可用

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/9443637/201876821-7ba1c89e-6122-4d4b-84e4-cfbb4191296a.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，经测试发现是ECharts图库下的饼图会有这个问题，我们尽快修复。

**Comment by Avanbchen** [comment]
好的

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
