### ISSUE TITLE
[Bug]定时任务拉取数据是一次性全量拉取，经常导致系统经常宕机

### ISSUE THREAD

**Issue by zijin-zj** [dataease/dataease#3767]
**DataEase 版本**
v1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
dataease服务器配置：4c8g

目前dataease的定时任务拉取MySQL数据的方式是：一次性全量拉取，只要对应的SQL结果比较大，就容易导致MySQL Server IOPS瞬间100%，而且dataease服务的CPU也容易100%

datease服务器CPU指标
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/48403386/202100942-c0763d7d-7a8c-442f-a7de-6e45e8100e8e.png">

群聊天记录
![image](https://user-images.githubusercontent.com/48403386/202100692-7b537a91-3d1d-42ef-90a4-d9ee90f1c61b.png)
![image](https://user-images.githubusercontent.com/48403386/202100723-ed545a98-7df8-4dd9-9408-2a2f7ff1cb52.png)
![image](https://user-images.githubusercontent.com/48403386/202100758-7fd221a7-f5c5-4797-9400-f01af8cf43ed.png)

**Bug 重现步骤(有截图更好)**

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们后期会考虑在doris使用方面做一些相关优化。

**Comment by zijin-zj** [comment]
> 感谢反馈，我们后期会考虑在doris使用方面做一些相关优化。

嗯嗯 期待

**Comment by xuwei-fit2cloud** [comment]
从v1.18.0版本开始，DataEase采用分页的方式拉取数据，您可以升级到当前最新的v1.18.4版本。
