### ISSUE TITLE
[Bug] 报表明细的图表的分页是假分页，返回数据量大容易导致系统和浏览器页面奔溃

### ISSUE THREAD

**Issue by zijin-zj** [dataease/dataease#3768]
**DataEase 版本**
v1.15.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

Google Chrome | 107.0.5304.110 (正式版本) (arm64)

**Bug 描述**
报表明细的图表的分页是假分页，返回数据量大容易导致系统和浏览器页面奔溃

**Bug 重现步骤(有截图更好)**

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前新版本正在做表格分页的相关处理工作，可以等待v1.17版本试试。

**Comment by zijin-zj** [comment]
> v1.17

好的

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理直连模式下大部分数据源的后端分页问题，请更新最新版本。
