### ISSUE TITLE
[Bug]视图快速计算占比问题

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#3772]
**DataEase 版本**
v1.16.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
占比计算无法去除

**Bug 重现步骤(有截图更好)**
1.Antv 透视表，新增快速计算占比
![image](https://user-images.githubusercontent.com/96223591/202164778-f8ec3a04-e35c-4086-9cd9-511639164fd7.png)

2. 勾选后出现百分数设置成无后 依然显示%
![image](https://user-images.githubusercontent.com/96223591/202164900-f005268a-7c7a-4aa1-86e0-cbddc499e1a8.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，这里其实是和数据格式做了关联；你查看一下数据格式将百分比改回来就可以了，我们后续也会讨论一下这里的流程优化，是否可以更简单的理解使用流程的扭转
