### ISSUE TITLE
[Bug]【数据源】数据源当前不支持数据库名带‘-’，望支持！

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3773]
**DataEase 版本**
1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
数据源的数据库名带‘-’，点击保存报错！

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/24768910/202333709-6ec9afd2-ea74-4f5b-8272-2db76aebbfec.png)

2.
![image](https://user-images.githubusercontent.com/24768910/202333725-2b8186b8-6635-4cee-a46a-c0003b502dc0.png)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，这个看着应该是driver的报错，你可以尝试降低driver版本试试看
