### ISSUE TITLE
[Feature]【模板市场】希望 DataEase 支持套用模板市场（官方网站）中的应用

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3774]
**请描述您的需求或者改进建议.**
希望 DataEase 支持套用模板市场（官方网站）中的应用。
![image](https://user-images.githubusercontent.com/24768910/202340920-37fb7bc2-bf04-47b3-a830-92ddfbcd0603.png)

**Comment by xuwei-fit2cloud** [comment]
感谢您的建议！
但由于目前应用管理这块有自己的管理逻辑，和模板市场还不太一样。
我们后期会考虑进行整合，短期内应该不会有太大改动。

**Comment by AndroidBaby1** [comment]
好的，谢谢。
