### ISSUE TITLE
如果开启外网放问

### ISSUE THREAD

**Issue by Seifon** [dataease/dataease#3776]
在Mac OS系统，我将服务搭建好了，本地能够访问

但是在外网无法访问，想问一下如何开启才能访问呢

我电脑是做了内网穿透，其它服务都是可以在外网访问到的，就dataease的web在外网访问不通额

**Comment by xuwei-fit2cloud** [comment]
是服务端口不通，还是服务访问异常？
DataEase这边并没有特殊限制的。
如果端口不通，可以查看一下防火墙是否放开了相关端口。也可以试试用nginx转发服务的方式访问。

**Comment by Seifon** [comment]
> 是服务端口不通，还是服务访问异常？ DataEase这边并没有特殊限制的。 如果端口不通，可以查看一下防火墙是否放开了相关端口。也可以试试用nginx转发服务的方式访问。

好的，今天又突然可以了，谢谢
