### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by zczhaichao** [dataease/dataease#3780]
**DataEase 版本**
官方demo，2022年11月17日测试当前版本

**运行方式(安装包运行 or 源码运行 ?)**
官方demo，https://dataease.fit2cloud.com/#/panel/index

**浏览器版本**
谷歌107.0.5304.88

**Bug 描述**
一个仪表盘中如果需要看两个地图试图，点击第一个试图的刷新会调用第二个地图的JSON

**Bug 重现步骤(有截图更好)**
1.两个地图选择不同的“地图范围”
![image](https://user-images.githubusercontent.com/37654158/202439024-f7727b83-a739-47d5-a4bb-44b036f46e25.png)
![image](https://user-images.githubusercontent.com/37654158/202439154-fded884f-44b7-4de2-9857-de8dfbbf3ab4.png)

2.点击第一个地图的刷新
![image](https://user-images.githubusercontent.com/37654158/202439333-ae832e98-53ee-49ff-b97b-0bb846433051.png)

3.结果第一地图会使用第二个地图的JSON
![image](https://user-images.githubusercontent.com/37654158/202439411-e10d1a61-1e02-463d-b51a-6ee1cb5dd53d.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题已知了，我们会尽快修复的
