### ISSUE TITLE
[Bug] 地图多实例，工具栏还原缩放级别功能异常

### ISSUE THREAD

**Issue by lxd870911** [dataease/dataease#3782]
**DataEase 版本**
1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 103.0.5060.134

**Bug 描述**
两个不同地图，单击地图工具栏刷新图标，两个地图变成一样，由图一变为图二

**Bug 重现步骤(有截图更好)**
1.图一![image](https://user-images.githubusercontent.com/5519797/202495544-c465f4b9-60fb-4d3a-a8ce-02d881160ce8.png)
2.图二
![image](https://user-images.githubusercontent.com/5519797/202495995-62ff0847-a114-45c0-8dd9-7d5b0ab7a0a4.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复此问题

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
