### ISSUE TITLE
[Question]HA模式使用外部kettle数据集问题

### ISSUE THREAD

**Issue by yorkbai** [dataease/dataease#3786]
DataEase 版本
1.16.0

运行方式(安装包运行 or 源码运行 ?)
安装包离线安装， dataease HA模式

组件：
1. mysql，kettle多个节点，doris集群 都是外部单独部署的
2. 多个kettle节点通过nfs共享（/data/privatisation/dataease/data/kettle）

问题描述
      
       dataease与kettle运行在不同服务器上;  dataease 服务运行正常，控制台配置了外部doris，kettle ，校验成功
       1.  请介绍下一份原始数据在dataease/kettle/doris中的数据流逻辑， nfs在整体架构中的作用
       2.  测试数据集失败，检查doris里会创建表，但没有数据，dataease服务日志有错误， 在/opt/dataease/data/kettle下产生一些tmp_***.txt文件， /data/privatisation/dataease/data/kettle目录是空的
![issue-1](https://user-images.githubusercontent.com/7995150/202606893-1f422da9-7b5e-4998-bf48-ed49825ae731.jpeg)

**Comment by xuwei-fit2cloud** [comment]
大概的流程是这样的：
DataEase 上传 Excel 数据到 nfs 目录下，DataEase 调用 Kettle 从 nfs 目录中读取文件进行数据抽取，Kettle 将数据抽取后存入 Doris。

可以参考一下在线文档，是不是这一步没有做
https://dataease.io/docs/installation/HA/dataease_installation/#4
