### ISSUE TITLE
[Bug]透视表维度在做了筛选操作后排序不正确

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3788]
**DataEase 版本**
v1.16.1

**运行方式(安装包运行 or 源码运行 ?)**
安装部运行

**浏览器版本**
Chrome 105

**Bug 描述**
对透视表维度做了排序，但是通过筛选条件做了数据过滤后，维度的排序就不正确了。

**Bug 重现步骤(有截图更好)**
1.对行维度进行排序，初始查看是正常的。
![image](https://user-images.githubusercontent.com/48945409/202613250-3f2f6b7f-bd04-455c-9767-6679267546a0.png)

2.加了筛选条件之后，排序顺序不正常了。
![image](https://user-images.githubusercontent.com/48945409/202613376-89432dd8-e79a-4d46-8245-95c81807199b.png)

**Comment by BBchicken-9527** [comment]
感谢反馈。我们开会商量一下
