### ISSUE TITLE
[Bug]透视表的阈值设置针对文本计数设置阈值时应当提供大于小于的条件

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3789]
**DataEase 版本**
v1.16.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 105

**Bug 描述**
透视表的列如果放入的是非数值字段，则阈值设置的条件未提供大于小于功能。但其实这里本身是计数，最后的结果是数值，还是应当提供大于小于的条件。

**Bug 重现步骤(有截图更好)**
1.数据列放入非数值型的字段，例如下方，放入文本型字段，内容展示的为对其的计数结果。
![image](https://user-images.githubusercontent.com/48945409/202613909-7cbbad37-be4b-43c4-9cb0-d0f34a486233.png)

2.该字段的条件是按照文本型给提供的，并没有大于小于等条件，如果想要展示多少数量以上变色则无法操作。
![image](https://user-images.githubusercontent.com/48945409/202614064-4a304c1a-3f8d-47cc-8623-225c6fd6287e.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，嗯..因为是两个字段进行排序，并且存在优先级，我们商量一下处理的方式
