### ISSUE TITLE
[Feature] 定时报告提供回调接口发送图片文件流或者图片

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3790]
**请描述您的需求或者改进建议.**
DataEase 的定时报告图片是不落服务器的。可能有多方面的考虑。
想能不能在定时任务在添加一种，发给我们自定义的回调接口，你们只管把文件发给指定的接口，我们自己来保存等形式。
![6960598ffa3402b65a610a513b6a750](https://user-images.githubusercontent.com/82353425/202644939-601720b2-ff27-4ef6-80d9-5bc540f6e702.png)

或者说能出一个接口，返回定时报告最新的仪表板图片文件流，也是可以的，我们第三方系统直接调用将文件流转成图片进行保存。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个我们内部先讨论一下。
