### ISSUE TITLE
[Bug]API数据集 更新任务执行失败

### ISSUE THREAD

**Issue by gaohonghai** [dataease/dataease#3792]
**DataEase 版本**
1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
 106.0.5249.119

**Bug 描述**
API数据集 更新任务执行失败

**Bug 重现步骤(有截图更好)**

https://user-images.githubusercontent.com/92966838/202645261-6c97d2e8-bc3a-4c6d-9ca5-a594cbaba8e2.mp4

**Comment by 13358253225** [comment]
1、excel没问题。
2、后端没有报错，需要定位源码。如果需要复现我可以找客户要临时api。

**Comment by 13358253225** [comment]
111

**Comment by gaohonghai** [comment]
怀疑是这边对数组中的 String 元素需要做判空：
![image](https://user-images.githubusercontent.com/92966838/203006234-50a15d4a-0bd1-4622-bc65-9b552f4a2674.png)

修改后：
`@Override
public String insertSql(String name, List<String[]> dataList, int page, int pageNumber) {
    String res="";
    try {
        String insertSql = "INSERT INTO TABLE_NAME VALUES ".replace("TABLE_NAME", name);
        StringBuffer values = new StringBuffer();

        Integer realSize = page * pageNumber < dataList.size() ? page * pageNumber : dataList.size();
        for (String[] strings : dataList.subList((page - 1) * pageNumber, realSize)) {
            String[] strings1 = new String[strings.length];
            for (int i = 0; i < strings.length; i++) {
                System.out.println(strings[i]);
                if(strings[i]==null){
                    strings1[i]="";
                }else {
                    strings1[i] = strings[i].replace("'", "\\'");//你们原先api的如果传空会出错，我改了个判断
                }
            }
            values.append("('").append(UUID.randomUUID())
                    .append("','").append(String.join("','", Arrays.asList(strings1)))
                    .append("'),");
        }
        res=insertSql + values.substring(0, values.length() - 1);
    }catch (Exception e){e.printStackTrace();}
    return res;
}`

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复的

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。

**Comment by gaohonghai** [comment]
收到 感谢
