### ISSUE TITLE
[Feature]视图标题名称修改在视图的更新里面

### ISSUE THREAD

**Issue by wxcen** [dataease/dataease#38]
**请描述您的需求或者改进建议.**
希望在视图项的三个点菜单中增加重命名的功能，目前修改标题的功能隐藏太深了。
![Uploading image.png…]()

**Comment by xuwei-fit2cloud** [comment]
已实现，请等待 v1.1.0 版本发布

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已支持
