### ISSUE TITLE
[Bug]hive数据集配置报错

### ISSUE THREAD

**Issue by suyang1024** [dataease/dataease#3803]
**DataEase 版本**
v1.16.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 版本 107.0.5304.107（正式版本） （64 位）

**Bug 描述**
hive版本为0.13.1，无法正常连接

**Bug 重现步骤(有截图更好)**
1. 添加数据源，虽然显示校验成功，但是无法显示hive数据的表：
![image](https://user-images.githubusercontent.com/55219792/202861144-0d1a8405-bf81-453c-ad52-22068ee98bc4.png)
![image](https://user-images.githubusercontent.com/55219792/202861162-ef01a298-7970-4dd1-8522-91f0b3bb6f38.png)

2.配置数据集，报错：
![image](https://user-images.githubusercontent.com/55219792/202861249-4ce8e505-dbf6-42f1-aac9-a3981d8ba787.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，嗯... 我看你这个库里面好像没有表，是存在表但是我们没有找到吗

**Comment by suyang1024** [comment]
您好，感谢回复：
&nbsp; &nbsp; 我使用的hive库里是有表的，如图，但是dataease的数据源加载不出来





我在使用hive default驱动的时候，目前报连接不上，如下图：










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataease/dataease"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月21日(星期一) 中午11:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataease/dataease] [Bug]hive数据集配置报错 (Issue #3803)





 
感谢反馈，嗯... 我看你这个库里面好像没有表，是存在表但是我们没有找到吗

**Comment by BBchicken-9527** [comment]
嗯...你使用自己添加的driver试试呢？因为考虑到用户不同的版本所以是可以自己添加driver的
