### ISSUE TITLE
本地开发环境，无法访问knife4j文档

### ISSUE THREAD

**Issue by TateLu** [dataease/dataease#3804]
本地开发环境，无法访问knife4j文档

已经按照官方文档，在本地搭建了开发环境，也成功本地访问页面，功能都正常

但是，我想访问knife4j文档，查看API 接口

访问地址： http://localhost:8081/doc.html, 报404错误

应该如何解决？需要修改什么配置么？

**Comment by yayanpei** [comment]
感谢您的反馈，查看API接口需要官方授权。建议您先申请企业版使用一下，申请链接为：https://jinshuju.net/f/TK5TTd
