### ISSUE TITLE
API 数据集报错

### ISSUE THREAD

**Issue by Seifon** [dataease/dataease#3807]
预览时，都能展示数据，但是一旦增加后，就会报错了

```
Data source connection exception: Communications link failure The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
```

API URL：http://ip-api.com/json

![](https://raw.hisi.ga/histb/pic/master/2022/11/20/91839732.jpg)

**Comment by BBchicken-9527** [comment]
改写反馈，看你的异常应该是数据库服务没有找到，受累确认一下这个接口是否可以连接，若改变了结构，如增加或减少了字段需要在字段管理-定时同步，同步一下，再到更新信息tab中同步数据；若只是更新了数据可以在更新信息tab中再同步一下数据就可以了

**Comment by Seifon** [comment]
> 感谢反馈，看你的异常应该是数据库服务没有找到，受累确认一下这个接口是否可以连接，若改变了结构，如增加或减少了字段需要在字段管理-定时同步，同步一下，再到更新信息tab中同步数据；若只是更新了数据可以在更新信息tab中再同步一下数据就可以了

这是API接口呀，跟数据库没有关系吧？ 另外我是搭建的本地精简版

**Comment by BBchicken-9527** [comment]
感谢反馈，接口也是从服务中发出的，如果de连接不上数据存放的服务就会提示这个异常的，这个和你是不是精简还是本地是没关系的，如果你确定你的这个数据服务是正常的并且是在创建时就会提示这个问题那可能确实是我们服务的问题，不过我需要你提供更多的信息给我我才能判断是那里出了问题，目前你这张截图无法精准判断的

**Comment by paperplane123** [comment]
我也遇到一样的报错，是在我换了个服务器，加载Excel 的数据集就会出问题，别的方式就不会
