### ISSUE TITLE
[Bug]hive数据库数据集查询列与数据表不匹配（多了一个修改前的字段），使用同步字段也一样

### ISSUE THREAD

**Issue by aptx4869211** [dataease/dataease#3810]
**DataEase 版本**
1.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

chrome 107
**Bug 描述**
使用hive数据源数据库数据集时，预览界面正常查看，保存报错
![image](https://user-images.githubusercontent.com/57996919/202938626-5fe26659-4163-419f-9469-3e9c35d094f1.png)

**Bug 重现步骤(有截图更好)**
1.新建hive数据源并连接成功
![image](https://user-images.githubusercontent.com/57996919/202938890-4b5472f9-b6ba-4675-8c12-f15d3eae2171.png)

2.
![image](https://user-images.githubusercontent.com/57996919/202939517-ffbc4b69-de50-4aa5-9fd2-84c630e5ca4c.png)
查看某个表的详细，发现多了一个字段，update_date，这个字段在之前已经进行修改，使用alter语句将这个字段名称修改为update_time，但是在这里仍然出现
3.选择新ji建数据集，使用刚才创建的hvie连接，选中其中的一个表，数据预览正常，此处并没有显示update_date这个列
![image](https://user-images.githubusercontent.com/57996919/202941170-acf85ee7-edf8-4b7a-b03b-de69652639b3.png)
4.保存后提示报错
![image](https://user-images.githubusercontent.com/57996919/202941858-8800d0d6-4fef-4ca2-ad97-aa427dd21306.png)
同时有两个更新时间，一个是修
![image](https://user-images.githubusercontent.com/57996919/202942168-30002258-cc50-4502-b48a-490fb7ff7daa.png)
改表前的，一个是修改表后的
使用dbeaver查询列的信息也没有查到这个字段
![4d439a5c1028ffd306938783b1ebc87](https://user-images.githubusercontent.com/57996919/202943488-a8024eb5-4052-4b1b-9763-04eeaa0ac6e8.jpg)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们确认一下

**Comment by BBchicken-9527** [comment]
感谢反馈我们目前并没有发现你说的这个问题，我这边造了一个相同21个字段的表；但是没发现有然后先将这个21个字段的表加到de之后去修改字段名称；之后再去同步字段。我的操作流程请问和你有出入吗？或者是有什么细节我不清楚的，方便的话告知我我这边模拟一下

**Comment by aptx4869211** [comment]
问了一下相关人员，他们也是说只是对字段名称进行了修改。如果不能复现的话，方便告知一下，获取hive数据源的表信息以及字段信息执行的sql是什么吗，十分感谢

**Comment by BBchicken-9527** [comment]
嗯是问我测试用的sql吗？我看你用的DBeaver所以我也用的这个去创建的表你列举的字段我都添加了，改的也是相通的名称
![image](https://user-images.githubusercontent.com/84372766/203252246-0772302a-e4b5-4dae-b98f-c0951e64d716.png)

**Comment by aptx4869211** [comment]
> 

dataease后端程序获取表信息的sql.目前跟别人对接了一下，感觉有可能是hive那边有缓存的原因
