### ISSUE TITLE
[Feature]【数据集】添加表的时候显示中文描述或者提示中文描述

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3811]
**请描述您的需求或者改进建议.**
【数据集】添加表的时候显示中文描述或者提示中文描述
![image](https://user-images.githubusercontent.com/24768910/202953474-9d6bf155-3f8d-4fec-934a-1e31662b7f3b.png)

**Comment by xuwei-fit2cloud** [comment]
是需要显示表的comment字段内容吗？上面截图的第一个表括号后面的内容就是comment字段内容。

**Comment by AndroidBaby1** [comment]
好的，谢谢，当前有显示在一起，只是 SQL 数据集没有。
