### ISSUE TITLE
[Feature]【数据集】SQL 数据集旁边的表提示和字段提示增加中文描述

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3812]
**请描述您的需求或者改进建议.**
SQL 数据集旁边的表提示和字段提示增加中文描述
![image](https://user-images.githubusercontent.com/24768910/202953629-f89bb0a1-f11d-4d1a-839a-20439bcaa308.png)
![image](https://user-images.githubusercontent.com/24768910/202953686-352efce2-68bb-4262-93e3-4d3e03d86d7f.png)

**Comment by xuwei-fit2cloud** [comment]
收到反馈，我们后续优化一下。
