### ISSUE TITLE
[Bug] 数据源 MaxCompute 图片拼写错误

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3814]
**DataEase 版本**
1.16.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/45852479/202979066-dd404ea8-054f-4a5e-a0a5-873d8b413767.png">
MaxCompute图片拼写错误

**Bug 重现步骤(有截图更好)**

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
