### ISSUE TITLE
[Bug]消息接收管理配置了仪表板分享时飞书提醒，但未收到提醒

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3825]
**DataEase 版本**
v1.16.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 105

**Bug 描述**
消息接收管理配置了仪表板分享时同时有站内信提醒及飞书提醒，但是只收到站内信的提醒。飞书对接无问题，可收到定时报告。

**Bug 重现步骤(有截图更好)**
1.消息接收管理开启飞书提醒。
![image](https://user-images.githubusercontent.com/48945409/203247484-300e363c-92b3-427b-ae9b-68dcfb6ffe8e.png)

2.对用户 A 分享了一个仪表板
![image](https://user-images.githubusercontent.com/48945409/203246494-7d5819d8-cc97-43a2-aaa7-6a4e37eaaf3c.png)

3.使用用户 A 的账号登录系统，收到站内信的通知，且可以看到分享给我的仪表板
![image](https://user-images.githubusercontent.com/48945409/203246833-313e8769-6b10-4a12-87ac-783f688d5633.png)
![image](https://user-images.githubusercontent.com/48945409/203246973-bba77594-f883-4a84-ae02-b2ad54749f91.png)

4.查看飞书信息，并未收到相关通知

5.测试飞书接收定时报告，是否正常，测试正常，连通性是没问题的。
![image](https://user-images.githubusercontent.com/48945409/203247258-d5e11447-ade9-491b-860d-4c63d8ee95f9.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前环境中没有发现你说的这个问题。是否可以确认一下绑定关系以及服务配置
![image](https://user-images.githubusercontent.com/84372766/203258607-bd9f05ed-5750-4b69-8c65-5cabf2b5cd70.png)

**Comment by luyang351** [comment]
好的，我们换个人测试下看看。

**Comment by BBchicken-9527** [comment]
好的，有问题可以在说明一下具体的情况
