### ISSUE TITLE
[Bug]API 名称与内容不匹配

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3828]
**DataEase 版本**
v1.16.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 105

**Bug 描述**
Excel 上传的 API 文档与实际情况不符

**Bug 重现步骤(有截图更好)**
1.查看 API 接口之 Excel 上传：/dataset/table/excel/upload，参数需要传入”编辑类型“、”数据表 ID“，且为必填参数，但实际上上传 Excel 并不涉及到这两个字段
![image](https://user-images.githubusercontent.com/48945409/203251118-8cbff517-3de1-4431-8ab0-7aa26e15859a.png)

2.调用该接口抓包后发现 body 内容为空，与接口所描述情况不符。
![image](https://user-images.githubusercontent.com/48945409/203260461-98687a27-6649-445d-9ca7-906ddd4b2f20.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by BBchicken-9527** [comment]
感谢反馈，是否必须： 指的是请求是一定要有这个参数，editType: 追加/替换；tableId：为空，新建数据集；不为空，在指定数据集上进行操作
