### ISSUE TITLE
[Question] v1.2.0 的版本规划

### ISSUE THREAD

**Issue by xuwei-fit2cloud** [dataease/dataease#383]
**请描述您的问题.**
V1.2.0 的版本规划和时间

**Comment by xuwei-fit2cloud** [comment]
v1.2.0 计划9月2日发布，该版本的计划内容有：

仪表板:
1. 支持视图和组件之间的联动

视图:
1. 新增图表类型：地图类型、气泡图、矩形树图
2. 支持多级钻取
3. 柱状图支持多维度叠加
4. 支持指标数值格式设置

数据集:
1. Excel数据集支持多sheet页
2. 定时检测数据源状态信息
3. 支持添加衍生列

数据源:
1. 数据源配置增加数据库连接参数支持
2. 支持 SQL Server 数据源
3. 支持 PostgreSQL 数据源
4. 支持 API 数据源

**Comment by lnts2015** [comment]
@xuwei-fit2cloud   数据源中的 “4支持 API 数据源” 为什么删掉了。 很期待这个功能。谢谢

**Comment by xuwei-fit2cloud** [comment]
这个版本大功能有点多，api数据源的支持在这个版本大概率完成不了了，向后推一个版本

**Comment by visionwang** [comment]
请问下，mongodb的有没有计划支持呢？

**Comment by StruggleYang** [comment]
elasticsearch 有支持计划吗

**Comment by maninhill** [comment]
v1.2 已经发布，欢迎下载体验，具体版本更新日志请查看：https://github.com/dataease/dataease/releases/tag/v1.2.0

**Comment by chhwang1981** [comment]
> v1.2 已经发布，欢迎下载体验，具体版本更新日志请查看：https://github.com/dataease/dataease/releases/tag/v1.2.0

使用升级命令，但是说没有发现新版本

**Comment by maninhill** [comment]
> > v1.2 已经发布，欢迎下载体验，具体版本更新日志请查看：https://github.com/dataease/dataease/releases/tag/v1.2.0
> 
> 使用升级命令，但是说没有发现新版本

你这个应该是访问 GitHub 的网络问题，请多试一下，或者直接下载离线安装包进行升级。
