### ISSUE TITLE
[Feature]SQL数据集编写SQL时可以自动补全表名和字段名

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#3832]
**请描述您的需求或者改进建议.**
希望增加功能： SQL数据集编写SQL时 可以自动补全表名和字段名

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个需求之前我们也做过一些相关调研，目前我们所用的sql编辑器是可以支持的，但存在一些效率上的问题还没有处理好，等解决了问题，我们会把该功能上线的。
