### ISSUE TITLE
[Feature] 希望新增隐藏世界地图功能按钮的功能

### ISSUE THREAD

**Issue by dxrdxrdxr** [dataease/dataease#3844]
![image](https://user-images.githubusercontent.com/40909844/203684581-579b0f9f-f36d-40cc-904d-cc3ce99230d8.png)
![image](https://user-images.githubusercontent.com/40909844/203684610-729afe13-0fec-40f5-b72b-ecb924c43bbc.png)
目前正在做BI项目，没有使用这些功能按钮的需求，且这些功能按钮稍微有点影响美观度，希望新增隐藏世界地图中上图显示的功能按钮的功能。thanks~~

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这些按钮在v1.17.0版本中已经可以设置是否显示了，请等待新版本发布。

**Comment by dxrdxrdxr** [comment]
> 感谢反馈，这些按钮在v1.17.0版本中已经可以设置是否显示了，请等待新版本发布。

目前github上开发版版本号已经是1.17.0了，还没有这些功能，请问是否要等待正式版发布

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
