### ISSUE TITLE
[Bug]表格序号列宽在使用自适应列宽时未跟随自适应

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3846]
**DataEase 版本**
v1.16.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 105

**Bug 描述**
使用 AntV 明细表，设置”显示序号“，列宽调整选择”自适应“，序号列宽并未跟随自适应，而是跟随自定义列宽中的值。

**Bug 重现步骤(有截图更好)**
1.选择 AntV 明细表，并开启表格序号。
![image](https://user-images.githubusercontent.com/48945409/203689817-fac24316-c6d0-413f-aada-66eb320cc6cb.png)

2.配置一个列宽自定义的值。
![image](https://user-images.githubusercontent.com/48945409/203689985-8775652d-56b5-4b27-8721-0a76e9ed51c7.png)

3.列宽调整为”自适应“，其他列为成了自适应，但是序号未自适应。
![image](https://user-images.githubusercontent.com/48945409/203690172-6759ccc3-258a-44a8-85f4-ee387d791285.png)

4.重新将列宽设置为”自定义“，并调整到最小值，这时只有”序号“列缩小为最小值。
![image](https://user-images.githubusercontent.com/48945409/203690389-2b0bd4f2-3f1f-4e77-ab00-ca9ecca13878.png)

5.再将列宽调整为”自适应“，序号列仍然保持刚才的最小值无法正常查看。
![image](https://user-images.githubusercontent.com/48945409/203690491-186ed7a6-046b-4ff2-877b-95eb12f67583.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前设计如此，这个字段是挤进去的一个字段，所以是没有和自适应做链接的
