### ISSUE TITLE
[Bug]表格使用自适应列宽总是会有个别数据展示不全

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3849]
**DataEase 版本**
v1.16.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 105

**Bug 描述**
表格使用自适应列宽总是会有个别数据展示不全，例如下图所示，想要使用自适应展示，但是自适应的列宽效果不是太好，总是会存在宽度跟上下数据差不多一致的数据无法完全展示出来，影响查看。
![image](https://user-images.githubusercontent.com/48945409/203703401-07775142-0fc5-46c1-b2d7-12051b0e88ff.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，这是图库配置属性，操作上空间较小的，我们商量一下是否有优化的空间
