### ISSUE TITLE
[Feature] 在使用应用创建仪表板时，如果不小心点到旁边会收起信息填写界面，已填写的内容会丢失。建议优化下，关闭弹框前给出提示。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#3854]
在使用应用创建仪表板时，如果不小心点到旁边会收起信息填写界面，已填写的内容会丢失。
![image](https://user-images.githubusercontent.com/30063018/203732945-71f165b8-15d2-404b-b180-b948e0f4c88d.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
