### ISSUE TITLE
[Bug] 数据集字段比较多的情况下，添加行权限，选择字段时显示不全，建议固定选择框位置，并增加上下滚动条

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#3855]
**DataEase 版本**
v1.16.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome
版本 107.0.5304.110（正式版本） (arm64)

**Bug 描述**
数据集字段比较多的情况下，添加行权限，选择字段时显示不全，建议固定选择框位置，并增加上下滚动条

**Bug 重现步骤(有截图更好)**
1、数据库表有36个字段，建表语句如下所示：
`CREATE TABLE `test_many_columns` (
  `column1` varchar(50) DEFAULT NULL,
  `column2` varchar(50) DEFAULT NULL,
  `column3` varchar(50) DEFAULT NULL,
  `column4` varchar(50) DEFAULT NULL,
  `column5` varchar(50) DEFAULT NULL,
  `column6` varchar(50) DEFAULT NULL,
  `column7` varchar(50) DEFAULT NULL,
  `column8` varchar(50) DEFAULT NULL,
  `column9` varchar(50) DEFAULT NULL,
  `column10` varchar(50) DEFAULT NULL,
  `column11` varchar(50) DEFAULT NULL,
  `column12` varchar(50) DEFAULT NULL,
  `column13` varchar(50) DEFAULT NULL,
  `column14` varchar(50) DEFAULT NULL,
  `column15` varchar(50) DEFAULT NULL,
  `column16` varchar(50) DEFAULT NULL,
  `column17` varchar(50) DEFAULT NULL,
  `column18` varchar(50) DEFAULT NULL,
  `column19` varchar(50) DEFAULT NULL,
  `column20` varchar(50) DEFAULT NULL,
  `column21` varchar(50) DEFAULT NULL,
  `column22` varchar(50) DEFAULT NULL,
  `column23` varchar(50) DEFAULT NULL,
  `column24` varchar(50) DEFAULT NULL,
  `column25` varchar(50) DEFAULT NULL,
  `column26` varchar(50) DEFAULT NULL,
  `column27` varchar(50) DEFAULT NULL,
  `column28` varchar(50) DEFAULT NULL,
  `column29` varchar(50) DEFAULT NULL,
  `column30` varchar(50) DEFAULT NULL,
  `column31` varchar(50) DEFAULT NULL,
  `column32` varchar(50) DEFAULT NULL,
  `column33` varchar(50) DEFAULT NULL,
  `column34` varchar(50) DEFAULT NULL,
  `column35` varchar(50) DEFAULT NULL,
  `column36` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8`

2、添加直连模式的 SQL 数据集，并添加行权限，选择字段如下所示：
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/30063018/203735755-4370402c-20cf-4a3e-acb8-5cc3e4d23015.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
