### ISSUE TITLE
[Bug]指标格式的视图，数值格式设置为数值，小数位数1，点击确定后仍为原格式未保存成功

### ISSUE THREAD

**Issue by zhangshihao930112** [dataease/dataease#3857]
**DataEase 版本**
1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
指标格式的视图，数值格式设置为数值，小数位数1，点击确定后仍为原格式未保存成功

**Bug 重现步骤(有截图更好)**
1.设置视图选择指标格式（123）
2.指标取平均值
3.设置数值格式为数值，小数位数为1
4.确定保存后查看指标显示
![微信截图_20221124171723](https://user-images.githubusercontent.com/85295604/203746228-5278e8a6-d624-4112-ab80-09a92e57f892.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为一致问题并以修改，将在下个版本修复；

**Comment by JunTech** [comment]
1.15.2 修复了这个问题的
