### ISSUE TITLE
[Bug]分组柱状图指标升降序不起作用 

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#3867]
**DataEase 版本**

1.16.0

**运行方式(安装包运行 or 源码运行 ?)**

安装包运行

**浏览器版本**

谷歌浏览器 104.0.5112.102

**Bug 描述**

分组柱状图指标升降序不起作用 

**Bug 重现步骤(有截图更好)**
1.制作仪表板时选择分组柱状图
2.设置好对应的类别轴 / 维度、子类别 * / 维度、值轴 / 指标
3.值轴 / 指标排序方式选择升序或者降序，虽然视图有变化，但是并没有起到升序和降序的作用，如下图
![image](https://user-images.githubusercontent.com/35896106/203804014-39827419-b8e9-41f6-be04-442b54cf7904.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，其实是没有问题的，按照主维度和子维度分组后再聚合排序 视图层面的排序是按照主维度数据出现的顺序排的
