### ISSUE TITLE
[Bug] SQL数据集，预览没有数据，添加别名后有数据

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3869]
**DataEase 版本**
v1.16.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
SQL数据集，预览没有数据，添加别名后又数据

**Bug 重现步骤(有截图更好)**
1.新建SQL数据集，编写SQL，预览
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/45852479/203894836-966352a6-a0b6-4083-810f-e41230e5d745.png">
2.添加别名后预览成功
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/45852479/203894686-463a3970-fe2c-4ef7-9dbf-4be75e1e6658.png">
附：
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/45852479/203896076-63dc97e7-a29f-4952-a13c-885c28f3fa67.png">
<img width="893" alt="image" src="https://user-images.githubusercontent.com/45852479/203895679-bfd71dd3-7c7d-48ef-8d76-bc29a5eb0fde.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，考虑到表头的可读性以及可能会因为有的函数的长度、复杂度、可控性；所以设计如此

**Comment by BBchicken-9527** [comment]
感谢反馈，考虑到表头的可读性以及可能会因为有的函数的长度、复杂度、可控性；所以设计如此
