### ISSUE TITLE
[Feature]【视图】词云图支持自定义配色方案

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#3872]
**请描述您的需求或者改进建议.**
在指标比较多的时候，词云图中的字体不太能看清，希望可以自定义调整配色方案

![c2Rji9xd11](https://user-images.githubusercontent.com/96223591/203906892-811d1c0d-3e2e-491a-90b5-5660da33d95e.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个我们再考虑一下，是否增加几种内置的区分度比较明显的配色方案。

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
