### ISSUE TITLE
[Bug]编辑应用管理的分类，在名称未修改进行保存时会提示”分类名称已存在“

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3874]
**DataEase 版本**
v1.16.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 106

**Bug 描述**
编辑”应用分类“，再次保存时，会提示名称已存在，实际上已存在的名称就是当前自己的名称。
![image](https://user-images.githubusercontent.com/48945409/203915202-9e5f6bad-85d6-40a4-a1aa-155e7cf25467.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，将会在下个版本修复

**Comment by BBchicken-9527** [comment]
问题已修复可下载新版本体验
