### ISSUE TITLE
[Feature]建议应用文件可以修改自己的应用分类

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#3875]
**请描述您的需求或者改进建议.**
如果删除应用分类，则分类下的应用也会被一起删除，但是应用本身却并未提供修改自己分类的操作。
![image](https://user-images.githubusercontent.com/48945409/203915659-871aac46-9427-45aa-a60c-b38b68ea36c3.png)

建议提供修改应用所属分类的操作，不论是在管理的逻辑上想修改分类，还是想删除分类时保留应用文件都是需要的。

**Comment by yayanpei** [comment]
感谢反馈，您的建议很不错，我们已加入后续版本的优化清单中。
