### ISSUE TITLE
[Feature] 添加一个类似superset的自定义变量供数据集使用且变量不止在where条件中才可以应用

### ISSUE THREAD

**Issue by JunTech** [dataease/dataease#3893]
**请描述您的需求或者改进建议.**
1.添加一个类似superset的自定义变量供数据集使用
2.变量不止在where条件中才可以应用，在sql中间也可以使用比如case when 或者 join on等条件亦或者子查询

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们会先做一下前期技术调研。
