### ISSUE TITLE
[Feature] 添加API数据源获取数据表时，对传输的请求信息进行加密

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3895]
**请描述您的需求或者改进建议.**
添加API数据源获取数据表时，建议对传输的请求信息进行加密，特别是认证相关内容
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/45852479/204188658-45eecb59-fa90-49fc-abc0-04d4538fd982.png">
目前如图都是非加密的

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，后期我们做一下相关优化。

**Comment by xuwei-fit2cloud** [comment]
v1.18.0版本已处理，请更新最新版本。
