### ISSUE TITLE
[Feature]支持SQL数据集与Excel数据集进行关联

### ISSUE THREAD

**Issue by wangzhen-fit2cloud** [dataease/dataease#39]
**请描述您的需求或者改进建议.**
数据关联功能可以跨数据集类型关联，在SQL数据集中关联数据时，可以关联到Excel数据集

**Comment by xuwei-fit2cloud** [comment]
自定义数据集是可以跨数据集类型进行关联的，但目前版本支持关联的数据集有定时更新类型的数据库数据集、定时更新类型的SQL数据集以及Excel数据集
