### ISSUE TITLE
[Feature]【仪表板】默认仪表板取消默认把”删除“字样改成”取消默认“

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#3901]
**请描述您的需求或者改进建议.**
默认仪表板取消默认把”删除“字样改成”取消默认“，”删除“字样容易让用户误认为是删除仪表板，而非取消默认。
![image](https://user-images.githubusercontent.com/24768910/204201441-2b4c5408-99dd-4f84-8097-f6657d92711f.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们调整一下。

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。

**Comment by AndroidBaby1** [comment]
好的，太帅了，非常感谢
