### ISSUE TITLE
[Bug]仪表板视图图层调整效果不明显

### ISSUE THREAD

**Issue by Avanbchen** [dataease/dataease#3905]
**DataEase 版本**
v1.16.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome
版本 107.0.5304.121（正式版本） （64 位）

**Bug 描述**
仪表板视图图层调整偶尔无效， Tab 组件里的视图无法调整图层。

**Bug 重现步骤(有截图更好)**
1.如图：
![image](https://user-images.githubusercontent.com/96223591/204227021-ae563003-bf50-406a-b6b9-47aad213c9a4.png)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.17.0版本已处理，请更新最新版本。
