### ISSUE TITLE
[Feature]仪表板上的外部参数，希望能传递到数据集的sql语句里作为条件

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#3911]
**请描述您的需求或者改进建议.**
仪表板上的外部参数，希望能传递到数据集的sql语句里作为条件
可以只在sql数据集实现此功能。

**Comment by yayanpei** [comment]
感谢您的反馈，我们先记录并讨论一下。

**Comment by sewenc** [comment]
我也有同样的需求，参数应该像组件一样，直接控制数据集啊
