### ISSUE TITLE
[Bug]配置 CAS 认证登陆页不显示

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#3925]
**DataEase 版本**
1.16.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器107.0.5304.107

**Bug 描述**
配置 CAS 认证登陆页不显示

**Bug 重现步骤(有截图更好)**
1.认证设置中设置CAS认证设置
![image](https://user-images.githubusercontent.com/35896106/204444907-c21850fd-db72-4a0b-9e89-a1454b86c915.png)

2.返回登陆页面未发现CAS认证登陆按钮
![image](https://user-images.githubusercontent.com/35896106/204445039-d98fc449-5580-48bf-a065-76b16962d272.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前cas配置完成后是没有登陆提示的，设置完成cas如果成功的话会自动跳转到cas的登陆页面。
