### ISSUE TITLE
[Feature]视图的过滤器建议增加动态时间

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#3940]
**请描述您的需求或者改进建议.**
视图的过滤组价建议增加动态时间，如果一个仪表板有很多视图，每个视图都需要加时间的过滤，会涉及到很多个时间过滤组件；
建议在制作视图时就可以设置动态时间的过滤

<img width="189" alt="图片" src="https://user-images.githubusercontent.com/48307752/204532349-641276d4-9130-4f6c-80be-86be9ef5033b.png">

**Comment by yayanpei** [comment]
感谢反馈，如果仪表板中有多个视图需要进行时间过滤，建议在仪表板中增加一个日期过滤组件，该日期过滤组件可以绑定多个视图的日期字段，从而实现用一个日期过滤组件控制多个视图，具体可以参考在线文档：https://dataease.io/docs/user_manual/filter_module/filtertime_module/#3
