### ISSUE TITLE
跟前端配置不一样时候，导致启动时候会报错[Bug]

### ISSUE THREAD

**Issue by shenghui-lee** [dataease/dataease#3942]
**DataEase 版本**
1.16

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
报错：Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'.
这个驱动已弃用，建议采用新的，涉及到两个文件类。

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/97576409/204574255-d518245c-95c0-4488-add9-6db76f220827.png)
2.
![image](https://user-images.githubusercontent.com/97576409/204574349-8a8d8887-756a-4044-9f2e-139d16b62a53.png)
3.
![image](https://user-images.githubusercontent.com/97576409/204574421-ff7141ed-8fad-476b-a747-d578b1c2a02f.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，这么设计是为了兼容旧版本的mysql的，如果你的mysql版本不适配可以通过登陆管理员账户在数据源处添加新的mysql driver
