### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by supercarpenter** [dataease/dataease#3956]
1：建议仪表板内元素支持框选成组，进行相关操作；
2：建议仪表板内支持通过ctrl或者鼠标，来多选元素进行拖拽等操作；
3：建议支持通过键盘的上下左右对仪表板元素进行位置调整；
4：建议外部引入的图片，允许进行像素大小的数值控制，目前只能鼠标控制大小；
5：建议取消所有外部图片引入时，自带的白色底色；
6：建议图表及字体颜色支持呈现渐变色，允许对图标多个参数进行单独的颜色控制，例如柱状图；
7：建议指标卡字段名称样式支持横向对齐，当前仅支持上下呈现；
8：建议增补回收站功能，方便查找误删后的仪表板并进行恢复；

**Comment by xuwei-fit2cloud** [comment]
非常感谢您用心的建议，我们都会加入到我们的需求池里进行讨论。
