### ISSUE TITLE
[Question]https://nexus.pentaho.org/content/groups/omni 不可用用了

### ISSUE THREAD

**Issue by xuxiepeng** [dataease/dataease#3965]
**请描述您的问题.**
https://nexus.pentaho.org/content/groups/omni 不可用用了，有什么替代地址么？

**Comment by xuwei-fit2cloud** [comment]
这个是pentaho官网的nexus仓库，我们没有其他替代地址。
如果是缺少依赖包的话，可以参考一下在线文档：
https://dataease.io/docs/faq/dev_faq/

**Comment by StiofanZ** [comment]
可以替换为这个试试，是pentaho的新的。
https://repo.orl.eng.hitachivantara.com/ui/native/pnt-mvn/

**Comment by FreedBird** [comment]
> 可以替换为这个试试，是pentaho的新的。 https://repo.orl.eng.hitachivantara.com/ui/native/pnt-mvn/

这个地址我也试过了下载下来的jar 包是不完整的
