### ISSUE TITLE
[Bug] 经常出现无效数据源

### ISSUE THREAD

**Issue by JunTech** [dataease/dataease#3966]
**DataEase 版本**
dev

**运行方式(安装包运行 or 源码运行 ?)**

源码运行 
**浏览器版本**
chrome 107

**Bug 描述**
经常出现无效数据源，然后重新编辑校验保存就好了，怀疑是数据库连接数太多了，在不修改数据库配置的情况下减少数据库连接数

**Bug 重现步骤(有截图更好)**

![0f4a1df461251130b69bb6a9c373b66](https://user-images.githubusercontent.com/54126696/204749006-77ac4981-fcb4-447f-8740-aa1ab2ba99c9.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，有没有可能是网络或者其他原因导致在轮训的时候无法连接呢，不过因为无法连接数据库的非常的多，我们这边也再讨论一下这个地方的机制看看是否有尽可能的覆盖
