### ISSUE TITLE
[Bug] 手机端查看仪表板原本未被遮挡的视图，放大后被遮挡了部分

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3967]
**DataEase 版本**
v1.16.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
手机查看，chrome浏览器

**Bug 描述**
原本未被遮挡的视图，放大后被遮挡了部分

**Bug 重现步骤(有截图更好)**
1.![image](https://user-images.githubusercontent.com/45852479/204750876-edbac04c-a6e6-452e-b516-7cfe4b20910d.png)
2.![image](https://user-images.githubusercontent.com/45852479/204750925-305e51d8-5686-43f3-bd59-97cb958012d2.png)
能源消费比重

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
