### ISSUE TITLE
[Bug] 手机端横屏查看大屏，视图内容会被挤压遮挡

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#3969]
**DataEase 版本**
v1.16.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
手机查看，chrome浏览器

**Bug 描述**
手机端横屏查看大屏，视图内容会被挤压遮挡

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/45852479/204752010-abdd60df-849b-4cf7-9d5d-b8d2e2032ade.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，因为在设计手机查看布局其实是竖屏布局的，所以为了布满画布才回变形的；当时设计的时候考虑到手机可能尺寸太小横屏显示很多数据看不清只能看到大概的走势；
