### ISSUE TITLE
[Feature]vV43__1.16-app-add.sql 文件不存在

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#3970]
**请描述您的需求或者改进建议.**
安装或升级时遇到 v43 执行报错的问题，需要手动执行v43sql，但发现这个地址的sql 不存在，1.16 和 1.17 都找过，可能被删除了。
https://github.com/dataease/dataease/tree/dev/backend/src/main/resources/db/migration)/V43__1.16-app-add.sql 

<img width="992" alt="图片" src="https://user-images.githubusercontent.com/48307752/204753555-9dd07fc4-61f2-435f-8b01-67639b04a020.png">

**Comment by xuwei-fit2cloud** [comment]
没看太明白，但上面的地址是不对的，可以试试这个
https://github.com/dataease/dataease/blob/v1.16/backend/src/main/resources/db/migration/V43__1.16-app-add.sql

**Comment by mfanoffice** [comment]
这个地址 的 V43__1.16-app-add.sql 也不能下载，难道是我网络的问题？

**Comment by mfanoffice** [comment]
果然网络问题，gitee 是可以下载的
