### ISSUE TITLE
[Feature] 增加视图：UX 交互优化

### ISSUE THREAD

**Issue by maninhill** [dataease/dataease#3979]
**请描述您的需求或者改进建议.**

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/41712985/204944520-6c0d9630-1a87-460f-a770-493cf057210d.png">

希望能够优化下这个页面的布局。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们后续做一下相关的优化。
