### ISSUE TITLE
[Feature] 希望可以支持对 ES 数据集进行关联

### ISSUE THREAD

**Issue by zijin-zj** [dataease/dataease#3980]
**请描述您的需求或者改进建议.**
希望可以支持对 ES 数据集进行关联，目前 ES 数据集 不支持定时同步，所以也不能对ES 的数据集进行关联处理

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个短期内还没有相关计划，我们会先纳入到需求池中。

**Comment by zijin-zj** [comment]
好的，期待
