### ISSUE TITLE
[Feature] 关于数据源分类的改进

### ISSUE THREAD

**Issue by maninhill** [dataease/dataease#3983]
**请描述您的需求或者改进建议.**

建议分类调整为：

- OLTP 型数据库
- OLAP 型数据库
- 数仓 / 数据湖
- 其他

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/41712985/204961820-ee76b5d6-19d0-4833-909a-7776c6f4139a.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们后续版本做一下优化。
