### ISSUE TITLE
[Feature]移动端需求

### ISSUE THREAD

**Issue by charlesmiao** [dataease/dataease#399]
**请描述您的需求或者改进建议.**
PC端移动端自适应，或可以进行移动端布局设计

**Comment by yayanpei** [comment]
非常感谢您的反馈，移动端一直在我们的规划中，由于DataEase还处于产品打磨阶段，计划经过几个版本的迭代，功能相对完善且稳定后，再满足移动端的需求。

**Comment by xuwei-fit2cloud** [comment]
v1.6.0 版本会增加对移动端的支持，请关于1月份版本的发布。
