### ISSUE TITLE
[Feature]DataEase 是否可以支持通过nginx 文根转发访问

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#3990]
**请描述您的需求或者改进建议.**
DataEase 是否可以支持 通过nginx 文根转发访问到DataEase的页面，
比如：原地址为 http://IP  通过nginx代理 访问访问为 http://IP/dataease  这么访问
目前只在nginx上无法配置实现，只能通过端口转发。

**Comment by yayanpei** [comment]
感谢您的反馈，请参考在线文档（https://dataease.io/docs/dev_manual/dev_deployment/compile/
）
