### ISSUE TITLE
[Bug] 词云图无法自定义调整内容大小

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#3992]
**DataEase 版本**
1.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌标准版

**Bug 描述**
1.假如数据很少，词云图的视图大小不管拉的多大，内容字体大小不变，留白的位置更大。
![image](https://user-images.githubusercontent.com/82353425/205000707-9b30498f-e833-4914-8c97-ed316ad0ea49.png)

希望能自定义词云图内容大小

**Comment by BBchicken-9527** [comment]
感谢反馈，词云图受到高度和宽度共同影响显示内容的，目前显示来说没有太大的操作空间，我们讨论一下是否有处理的可能
