### ISSUE TITLE
[Bug]日期过滤组件 无法过滤 presto的sql数据集数据

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#3997]
**DataEase 版本**
1.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome

**Bug 描述**
presto 的 sql数据集，select * from  table ,
在仪表板上使用日期过滤组件会识别时间为字符类型，导致报错；
使用sql参数可以避免这个问题。

**Bug 重现步骤(有截图更好)**
1. 新建presto数据集 select * from  table

2. 仪表板添加日期过滤组件（日期和日期范围都行）
3. 选择日期过滤，presto数据集的视图会报错
![图片](https://user-images.githubusercontent.com/48307752/205196516-f3a5ebb6-ccd0-4961-9820-a088e956913f.png)

**Comment by ChewJ404** [comment]
@BBchicken-9527   presto 日期范围 筛选组件 存在 ，开始时间 与结束时间 ，解析后的 sql 用的都是 开始时间情况
数据集sql
![image](https://user-images.githubusercontent.com/10162958/206388049-10023cf6-190f-4e37-a671-1c02b29df623.png)
视图组件 解析后的查询sql
![image](https://user-images.githubusercontent.com/10162958/206388175-5cfe5fab-cd18-4c90-9b30-34acc9e7ad36.png)
视图配置 饼图
![image](https://user-images.githubusercontent.com/10162958/206388347-633c207d-ecbf-4475-8535-5cde5f6c8945.png)
![image](https://user-images.githubusercontent.com/10162958/206388420-681b938b-b970-477d-9d39-cb92f44f09a8.png)

**Comment by ChewJ404** [comment]
@BBchicken-9527  经过反复测试 ，发现 问题是 由于 如果 同一个数据集  被多个视图引用 ，并且勾选多个视图参数 的时候，筛选会出问题
