### ISSUE TITLE
添加视图，表名太长，导致显示不全，拉大最大也不行

### ISSUE THREAD

**Issue by plateauandsp** [dataease/dataease#4]
添加视图，表名太长，导致显示不全，拉大最大也不行
![image](https://user-images.githubusercontent.com/30932762/123370155-bf479800-d5b1-11eb-899d-766713ab9819.png)

**Comment by xuwei-fit2cloud** [comment]
右侧视图编辑区域需要保持最小区域大小，不建议支持左侧无限拉大
鼠标停留在指定的视图上，会给出该视图的全部名称显示。
