### ISSUE TITLE
[Bug]echarts表格移动数据列字段排序时没有实时变化

### ISSUE THREAD

**Issue by Fat-Mushroom** [dataease/dataease#4000]
**DataEase 版本**
v17.0

**运行方式(安装包运行 or 源码运行 ?)**
dev

**浏览器版本**
edge

**Bug 描述**
echarts表格挪动数据列的字段位置，表格内容没有跟着实时变化（退出重进才行）

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/85673588/205224451-33cf5550-68b6-440c-94fe-0d4807c314c3.png)

![image](https://user-images.githubusercontent.com/85673588/205224594-dd1b1d78-ae4b-40c5-852e-a8fc9f14d490.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们讨论一下怎样处理，建议使用AntV；后续我很会逐步剔除掉Echarts
