### ISSUE TITLE
[Bug]【权限管控】仪表板在转移到新文件夹的时候刷新权限有问题

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#4003]
**DataEase 版本**
1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
仪表板在转移到新文件夹的时候刷新权限有问题

**Bug 重现步骤(有截图更好)**
1.文件夹 A 被赋予了全用户可见，文件夹 B 仅用户甲可见；
2.用户甲在文件夹 A 中创建仪表板 a ，这时仪表板 a 全用户可见；
3.用户甲把仪表板 a 转移到 文件夹 B 时，仪表板 a 还是能全用户可见（这个时候应该按照文件夹的权限重新赋予仪表板权限才对）。

**Comment by xuwei-fit2cloud** [comment]
目前权限设计是这样的。对资源的授权都是具体到资源上，并没有组授权。
文件夹授权仅影响文件夹内新增资源的默认授权以及批量授权。
当仪表板a已授权给所有用户后，即使移动到文件夹B，它既不能继承文件夹B的默认授权，也不满足批量授权条件。
