### ISSUE TITLE
[Feature]柱状图里的柱子直角可调节为圆角

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4004]
**请描述您的需求或者改进建议.**
柱状图里的柱子直角能变成可调节的么？比如调节成圆角柱子
<img width="477" alt="图片" src="https://user-images.githubusercontent.com/48307752/205238441-93536baf-886c-4bf1-b13e-50e19bdc22cb.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们已记录该需求。
