### ISSUE TITLE
[Feature]透视表每一行做了颜色渐变，能否调整统一颜色

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4005]
**请描述您的需求或者改进建议.**
透视表 在深色主题下，隔行变色，黑色部分可以调整，白色部分不能调整，希望都能调整。
<img width="441" alt="图片" src="https://user-images.githubusercontent.com/48307752/205239694-f32a651c-7ccb-4d1b-898f-d79334a4d4c6.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这是个已知问题，我们在努力解决。
