### ISSUE TITLE
[Bug]Echart地图放入选项卡后，在预览模式下，鼠标点击无法选中地图的区域，鼠标悬浮无法显示地图提示数据

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4006]
**DataEase 版本**
1.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome

**Bug 描述**
Echart地图放入选项卡后，在预览模式下，鼠标点击无法选中地图的区域
鼠标移上地图，没有提示

<img width="753" alt="图片" src="https://user-images.githubusercontent.com/48307752/205254047-7996976b-4daa-4e11-bf2f-ee489f3bf0eb.png">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下
