### ISSUE TITLE
[Feature]文本卡可以指定默认显示空值

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4007]
**请描述您的需求或者改进建议.**
地图跟文本卡设置了联动， 如果没有选中任何省份，希望文本卡可以指定显示默认值，比如默认空值。
![图片](https://user-images.githubusercontent.com/48307752/205255143-de89e04e-0266-4311-90f9-5069b069b843.png)

**Comment by yayanpei** [comment]
感谢反馈，文本卡视图显示的是数据集中字段的真实值，如果需要显示空，建议您修改数据集。
