### ISSUE TITLE
[Question]kettle及数据源依赖 无法下载

### ISSUE THREAD

**Issue by orgccav** [dataease/dataease#4008]
**请描述您的问题.**
https://nexus.pentaho.org/content/groups/omni 无法访问，国内和国外都不可用
kettle及数据源依赖 无法下载
<groupId>pentaho-kettle</groupId>
            <artifactId>kettle-core</artifactId>
            <version>8.3.0.18-1112</version>
<groupId>pentaho-kettle</groupId>
            <artifactId>kettle-engine</artifactId>
            <version>8.3.0.18-1112</version>
<groupId>pentaho</groupId>
            <artifactId>metastore</artifactId>
            <version>8.3.0.18-1112</version>
<groupId>org.pentaho.di.plugins</groupId>
            <artifactId>pdi-engine-configuration-impl</artifactId>
            <version>8.3.0.7-683</version>

麻烦提供下jar包 或者可用资源地址

**Comment by xuwei-fit2cloud** [comment]
您可以参考一下我们的在线文档，也可以在文档里找到依赖包的离线下载方式。
https://dataease.io/docs/faq/dev_faq/#1-dataease

**Comment by huangapple** [comment]
还是不行， 离线版本的是 8.3.0.18-1084， 项目需要的是 8.3.0.18-1112

这个有开源吗？
