### ISSUE TITLE
[Feature]传统MOLAP数据源支持需求

### ISSUE THREAD

**Issue by charlesmiao** [dataease/dataease#401]
**请描述您的需求或者改进建议.**
1、比如Oracle Hyperion Essbase数据源
2、又如 IBM TM1 Tabase 数据源
3、其他支持 XMLA协议的数据源

**Comment by yayanpei** [comment]
非常感谢您的反馈，我们规划是优先支持常见的MySQL、Oracle、Sql Server、Excel等数据源，能支持不同的数据源是我们产品的优化方向，后面的版本迭代会支持更多类型的数据源，还请您多多关注。

**Comment by xuwei-fit2cloud** [comment]
近期版本还不会做支持，该需求暂时关闭
