### ISSUE TITLE
[Bug] 因为“下载”按钮导致右上角TAB组件内的视图无法查看

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4010]
**DataEase 版本**
1.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/82353425/205535945-e4e0278c-2a90-41e3-8a18-df0b3143907c.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，遮挡问题为已知问题，不过tab组件中出现下载这种按钮是有问题的我们一起处理一下
