### ISSUE TITLE
[Bug] 第一次打开仪表板，过滤组件无法过滤 Tab 组件内的视图

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4011]
**DataEase 版本**
1.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/82353425/205536553-5217651d-0b0a-49de-9117-eda85a26f161.png)
默认打开无法过滤，只能重新编辑下过滤组件才能过滤，
但是将过滤组件拖到tab内，就可以默认过滤，能不能实现默认都可以过滤呢？

**Comment by xuwei-fit2cloud** [comment]
v1.18.0版本已处理，请更新最新版本。
