### ISSUE TITLE
[Feature]simple安装模式下定时同步功能不可用的提示

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4012]
**请描述您的需求或者改进建议.**
使用 simple 模式 安装后，在数据集创建界面选择 “定时同步” 模式时是灰色的，能否加一个 鼠标悬浮提示 “simple 模式不可用” 的类似说明？
<img width="639" alt="图片" src="https://user-images.githubusercontent.com/48307752/205546275-c10883c8-c90a-43ab-9b24-d611e6086c25.png">

**Comment by yayanpei** [comment]
感谢您的反馈，我们讨论后优化一下。
