### ISSUE TITLE
[Bug]【用户管理】用户创建时未填写角色，则会在用户列表显示异常

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#4015]
**DataEase 版本**
1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
用户创建时未填写角色，则会在用户列表显示异常。

**Bug 重现步骤(有截图更好)**
1.创建一个没有角色的用户；
![image](https://user-images.githubusercontent.com/24768910/205564324-0940c961-a867-4adc-8daf-5f90319eb861.png)

2.用户列表发现没有显示该用户；
![image](https://user-images.githubusercontent.com/24768910/205564540-f77d4c86-64bc-4df6-a218-f6d45d002ace.png)
![image](https://user-images.githubusercontent.com/24768910/205564575-27f2251a-c2be-4c1b-818a-3781caa6e6b7.png)

3.将筛选条件的角色勾选放开，新建用户又出现在用户列表了；
![image](https://user-images.githubusercontent.com/24768910/205565646-9c2139ed-3609-4c36-b593-d2aea680323e.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题；是否还有什么步骤是没有说明；我按照你的操作方式创建了一个没有没有角色的用户，直接显示在了列表首行
![image](https://user-images.githubusercontent.com/84372766/205795384-f6aaa1b7-6c85-4276-8115-b95cabe1983b.png)
