### ISSUE TITLE
[Bug]数据集左侧列表栏调整宽度后需要切换模块后才生效

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4016]
**DataEase 版本**
v1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 107

**Bug 描述**
数据集左侧列表栏调整宽度后需要切换模块后才生效，调整完后直接切换数据集会变回去。

**Bug 重现步骤(有截图更好)**
1.当前宽度如下所示：
![image](https://user-images.githubusercontent.com/48945409/205571659-09aab018-35d5-4470-93b6-090074843860.png)

2.宽度拉宽到下图所示：
![image](https://user-images.githubusercontent.com/48945409/205571793-a5d566d5-1ec4-477c-9d22-00aaf754f422.png)

3.切换一个数据集，宽度收缩回去了，如下图所示：
![image](https://user-images.githubusercontent.com/48945409/205571972-9fcd0b0c-0da5-4fce-aa70-c5dcb5f93cba.png)

4.切换到仪表板模块再切换回去，宽度重新回归到刚刚调节的较宽的情况：
![image](https://user-images.githubusercontent.com/48945409/205572557-74e128d8-c3a5-47c8-a85a-e7c5cf775a41.png)

5.此时，再切换数据集，宽度不再收缩：
![image](https://user-images.githubusercontent.com/48945409/205572715-65edf9f1-6d7f-413f-86ca-83523f6519dc.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下
