### ISSUE TITLE
[Bug] Oracle 时间字段 SQL动态参数过滤保存后失效

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4017]
**DataEase 版本**
1.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1. 如图，点击运行查询是成功的，过滤时间为2022-12-01 到 2022-12-04.
2. select * from  SY_COURSE where "time_ne" between to_date('${star}', 'YYYY-MM-DD') and to_date('${end}', 'YYYY-MM-DD')
3. 
![image](https://user-images.githubusercontent.com/82353425/205590082-fc46dd97-0187-4924-b067-dc277568613f.png)

4.保存之后，看数据集过滤条件失效了。
5.
![image](https://user-images.githubusercontent.com/82353425/205590193-1427ce45-ca3a-4bb5-a845-87b615848761.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，TO_TIMESTAMP试一下

**Comment by ywhfzy** [comment]
> 感谢反馈，TO_TIMESTAMP试一下

也不行，保存之后再看数据集还是没有过滤。

**Comment by ywhfzy** [comment]
![image](https://user-images.githubusercontent.com/82353425/205854610-9a81170c-d3d8-4d1b-97b2-aed19757e947.png)
![image](https://user-images.githubusercontent.com/82353425/205854652-4b8d6f80-666b-4b08-98f7-a74fd52a87ba.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，设置的参数设置是不影响预览页面的数据显示的，退出编辑页面后预览的是sql语句查询的全部数据；
