### ISSUE TITLE
[Bug] 直连 sqlserver 数据集的 AntV 明细表有页码，但左下角是0数据

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4018]
**DataEase 版本**
1.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**

![企业微信截图_16702323675467](https://user-images.githubusercontent.com/82353425/205855402-06b0fc1c-9c04-49f7-a020-063f6d9087c0.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，大概多少条数据呢？还有就是分页模式选择的是翻页还是下拉呢？我你的截图有滚动条分页模式是不是错了

**Comment by BBchicken-9527** [comment]
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/84372766/205839384-a191ad7e-dbb4-4a1a-94a1-2ac808d91b62.png">
嗯... 你再看看你的文件吧

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
