### ISSUE TITLE
[Bug]筛选组件开启多选后内框变窄的样式问题

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4019]
**DataEase 版本**
v1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 107

**Bug 描述**
**筛选组件开启多选后的样式问题。示例如下：**

**不开启多选时筛选框效果：**
<img width="306" alt="image" src="https://user-images.githubusercontent.com/48945409/205606659-dd4974ad-f6a7-42e5-9a22-437b097e9470.png">

**开启多选后，中间的内框变窄了：**
<img width="303" alt="image" src="https://user-images.githubusercontent.com/48945409/205606969-a9e8db1e-f35d-4184-8008-30c7974f2a6f.png">

以下图示，上方为多选框，下方为单选框，可对比查看：
<img width="304" alt="image" src="https://user-images.githubusercontent.com/48945409/205607217-678c376f-f4f3-4c8d-8f26-cbddf43801b7.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，需要和你确认一下是什么情况下出现这种问题呢？全屏模式下还是正常的预览下就会存在，或者编辑状态就有这个问题了？

**Comment by luyang351** [comment]
两种情况下都有的，编辑界面下和预览界面下都有。
![image](https://user-images.githubusercontent.com/48945409/205805259-d17a8d9e-7083-49ed-a66b-0176d801e7f9.png)
![image](https://user-images.githubusercontent.com/48945409/205805328-66d23026-4606-4409-a60b-3d4de4257c67.png)

**Comment by BBchicken-9527** [comment]
好像确实有点儿出入，看起来像是和屏幕分辨率有一定关系；我们尝试修复一下
