### ISSUE TITLE
[Feature]数据回写需求

### ISSUE THREAD

**Issue by charlesmiao** [dataease/dataease#402]
**请描述您的需求或者改进建议.**
1、支持数据回写数据库的需求
2、支持针自动获取图表上的一些数据，生成一些描述性文字等需求
3、支持手工补录一些描述性问题，能编辑这些问题的大小、字体、样色等，并能回去数据库的需求

**Comment by yayanpei** [comment]
非常感谢您的反馈，您的建议是我们产品改进和优化的方向。

**Comment by xuwei-fit2cloud** [comment]
在最开始的几个版本中，暂时不考虑回写功能。
