### ISSUE TITLE
[Bug]【系统管理】地图组件直接上传某地级市后无法正常解析显示且无法删除

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#4020]
**DataEase 版本**
v1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome 103.0.5060.134

**Bug 描述**
1、任意城市json文件可正常导入，但无法正常解析
2、无法删除，不显示“删除”按钮

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/40846859/205825743-b1c33c7d-8c7d-42c9-aee0-c19ed9362b87.png)

2.
![image](https://user-images.githubusercontent.com/40846859/205825806-93d265b5-85e9-421d-a520-603fac3a5357.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，您这个文件是json格式的吗，上传文件必须是json格式的

**Comment by xusongtao** [comment]
是json的，您可以查看一下
[156440304.zip](https://github.com/dataease/dataease/files/10163346/156440304.zip)

**Comment by BBchicken-9527** [comment]
![image](https://user-images.githubusercontent.com/84372766/205841090-c63a2b0d-8c7b-4860-b22d-67d62a686f41.png)
嗯... 你这个文件再改改？
