### ISSUE TITLE
[Feature]【仪表板】地图组件支持自定义行政规划

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#4021]
**请描述您的需求或者改进建议.**
场景一：某公司主营A、B、C、D四个城市的业务，希望把A和B城市合并到一起并命令为一号大区、再把C和D城市合并到一起并命名为二号大区，希望在地图上能分别显示这两个对照组的城市，相当于把两个城市合并到一起。

场景二：某政府机构在疫情期间把辖区内的A、B、C街道合并到一起，成立联防联控小组，希望支持在地图上支持该联防联控小组的地理范围，并能进行上卷下钻。即支持依据地理位置描点的方式进行自定义的行政区域规划。

**Comment by yayanpei** [comment]
感谢您的反馈，可参考知乎文章：https://zhuanlan.zhihu.com/p/565073866，稍加改动，实现地图的自定义。

**Comment by xusongtao** [comment]
感谢回复，这确实是一个比较不错的方法。
请问后续考虑在产品上直接支持基于地图描点作为地图展示吗？

**Comment by yayanpei** [comment]
考虑到用户自定义地图偏个性化，自定义出的地图展示效果不好把控，因此暂时不考虑在产品中支持。
