### ISSUE TITLE
[Feature] 文本卡以及指标卡目前非垂直居中，建议做成可配置的模式，且默认垂直居中

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4023]
如图所示，文本卡及指标卡目前有点偏上，在缩的比较小的情况下效果不好，
建议居中对齐方式可配置，且默认垂直居中
![image](https://user-images.githubusercontent.com/30063018/205855775-3b3bd4d5-bcee-4a88-8d15-46e15f9fbe3a.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.0版本已处理，请更新最新版本。
