### ISSUE TITLE
[Feature] 数据预览页面前端自适应

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4024]
**请描述您的需求或者改进建议.**
如图
![image](https://user-images.githubusercontent.com/45852479/205856395-ae8d5bb6-9423-4342-9bbf-8fab3fbaa961.png)
![image](https://user-images.githubusercontent.com/45852479/205856766-3b4e2ddb-c092-4a97-a51a-fd232a650823.png)

**Comment by xuwei-fit2cloud** [comment]
v1.18.0版本已处理，请更新最新版本。
