### ISSUE TITLE
[Bug]直连 ES，Presto 数据集的 AntV 明细表左下角是0数据

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4026]
**DataEase 版本**
1.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
有分页，但是左下方总数是0.
![image](https://user-images.githubusercontent.com/82353425/205860649-3bd3b277-1934-40af-9e50-cf60a99baaa5.png)

![image](https://user-images.githubusercontent.com/82353425/205863118-ee757a0a-773d-4cf3-9fed-5bd45f9d5adc.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前问题已修复将会在下次发版修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.0版本已处理，请更新最新版本。
