### ISSUE TITLE
[Bug] excel数据集修改数据格式错误

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4028]
**DataEase 版本**
v1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
添加excel数据集时，在多sheet情况下，多次修改数据格式后，出现如下情况

**Bug 重现步骤(有截图更好)**
1.点击修改1⃣️字段数据格式，同时弹出两个字段的数据格式修改框
![image](https://user-images.githubusercontent.com/45852479/205861710-618fd5f0-6d97-4ecf-9872-8c952150e85d.png)
2.修改1⃣️的无效，会去修改2⃣️的数据格式
![image](https://user-images.githubusercontent.com/45852479/205865147-e976f05e-ec8c-4bf2-9c3a-3dc6819ec55d.png)
3.点击2⃣️的数据格式修改没有反应

**Comment by BBchicken-9527** [comment]
感谢反馈，所有的excel导入都有这样的问题嘛

**Comment by MaekBlack** [comment]
> 感谢反馈，所有的excel导入都有这样的问题嘛
测试了下 多sheet 的都能复现

**Comment by BBchicken-9527** [comment]
我这边没有发现这种情况方便的话微信联系一下？
