### ISSUE TITLE
[Bug] Echarts 组合图，图例、标题均设置为水平位置：中，垂直位置：上的情况下会重合

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4033]
**DataEase 版本**
v1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
Google Chrome
版本 108.0.5359.94（正式版本） (arm64)

**Bug 描述**
Echarts 组合图，图例、标题均设置为水平位置：中，垂直位置：上的情况下会重合

**Bug 重现步骤(有截图更好)**
如图所示：
![image](https://user-images.githubusercontent.com/30063018/206073640-09ce203a-886c-457d-810e-c9a425beee0f.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前此处没有太大的操作空间，我们讨论一下
