### ISSUE TITLE
[Bug]表格视图内部滚动时会穿透，影响到页面滚动条同步滚动

### ISSUE THREAD

**Issue by vencher** [dataease/dataease#4034]
**DataEase 版本**
v1.17

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
android

**Bug 描述**
表格视图内部滚动时会穿透，影响到页面滚动条同步滚动，在操作上不便。

**Bug 重现步骤(有截图更好)**
1. 定义有内部滚动的表格。
2. 多拉几个组件，形成三屏的页面滚动条。
3. 上下滚动表格内部数据

**Comment by BBchicken-9527** [comment]
感谢反馈，能详细说一下你的问题嘛，你的的意思是手机查看仪表板的问题嘛？

**Comment by vencher** [comment]
> 感谢反馈，能详细说一下你的问题嘛，你的的意思是手机查看仪表板的问题嘛？

页面中存在表格视图，表格数据有100条，存在表格内部的滚动条。
同时页面还有其他的视图，存在页面级别的滚动条。

需求是滑动表格组件内容滚动条。
现象是最终会滑动页面的滚动条。

**Comment by BBchicken-9527** [comment]
好的，是编辑页面还是预览页面呢？

**Comment by vencher** [comment]
> 



> 好的，是编辑页面还是预览页面呢？

在android真机下访问

**Comment by vencher** [comment]
> 安卓仿真机那就是预览页面是吗？

是用的预览页面。除了preview，还有其他地址能访问发布后的页面嘛？

**Comment by BBchicken-9527** [comment]
仿真机和实际机器还是有出入的，电脑页面访问会有问题吗或者真实手机访问
