### ISSUE TITLE
[Feature]单独打包移动端运行时，解决H5页面渲染效率低的问题

### ISSUE THREAD

**Issue by vencher** [dataease/dataease#4035]
**建议单独构建移动端运行时资源，去掉无用的功能，提升移动端渲染效率。**

当前dataease打包没有区分运行时和设计时，整体页面加载资源14M。在H5渲染时，首屏加载等待5-8s，经分析，引用了许多运行时无关的资源导致了页面加载解析时间过长。

<img width="989" alt="QQ20221207-111949" src="https://user-images.githubusercontent.com/15223719/206080817-67308663-6fe8-4f84-ab58-fcfcb58e3068.png">

<img width="989" alt="QQ20221207-111949@2x" src="https://user-images.githubusercontent.com/15223719/206080746-f1234b8f-feab-4d6b-9b1d-22f38eb79e6b.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们后续版本会做一下相关优化。

**Comment by vencher** [comment]
谢谢您的来信，我会尽快回复您
