### ISSUE TITLE
[Bug] Impala 新建数据库数据集选择表报错

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4037]
**DataEase 版本**
1.16

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 描述**
报错信息：
Star exprs only expand to scalar-typed columns because complex-typed exprs are currently not supported in the select list.
报错截图：
<img width="856" alt="0483a56e-4769-4c7e-9793-dd0b7b732850" src="https://user-images.githubusercontent.com/82353425/206090571-9b0b875d-5bfe-4f41-996e-eeae317ce41a.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下
