### ISSUE TITLE
[Bug] 仪表盘视图缩小后被挤压，没有自适应

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4039]
**请描述您的需求或者改进建议.**
如图
![image](https://user-images.githubusercontent.com/45852479/206103343-709300d6-a51d-42ca-b661-2fd310ea5126.png)
建议设置当中的可以不显示，或者自适应

**Comment by BBchicken-9527** [comment]
感谢反馈，是否是因为缓存原因导致？建议清除一下缓存是一下，视图缩放移动等都与使用的电脑浏览器内存有关系，我这边服务没有发现你说的问题
