### ISSUE TITLE
[Feature] 符号地图不显示名称

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4043]
**请描述您的需求或者改进建议.**
例如如下：
![2256aec4-00f0-48b0-b898-917cf88cf827](https://user-images.githubusercontent.com/82353425/206334096-9f266389-3660-4047-b694-c8f1b86850cc.png)
![7f9d7186-e101-4889-9612-06b45100c1e4](https://user-images.githubusercontent.com/82353425/206334103-40de76a3-da25-4a91-8a92-61d61b337aac.png)
能不能新增展示名称列呢？例如店名。

**Comment by xuwei-fit2cloud** [comment]
这个已经支持的，可以在标签里进行相关设置。
![图片](https://user-images.githubusercontent.com/1892127/206346681-89ec003b-b9db-4797-9664-ed730cf50a11.png)
