### ISSUE TITLE
定时任务手动执行非第一页的任务，会自动返回到第一页

### ISSUE THREAD

**Issue by Avey777** [dataease/dataease#4045]
**DataEase 版本**
最近几个版本都有此问题

**运行方式(安装包运行 or 源码运行 ?)**
docker

**Bug 描述**
"我是谁😉：
「DataEase 社区客服小北：“我是谁😉: 
「DataEase 社区客服小北：“我是谁😉: 
点击后面的几页的时候   没词都会返回第一页  要命的很”
------
@我是谁😉 这个问题可以优化，我们记录一下，批量数据集同步除非把kettle部署到其他服务器，并且部署多个kettle，才能抗住并发执行拉去任务。」
- - - - - - - - - - - - - - -
系统管理 数据同步 页面”
------
@我是谁😉 创建定时任务不应该是在这里添加吗？往后翻是为了什么？」
- - - - - - - - - - - - - - -
如果你在第4页手动执行了 定时任务， 点击 运行一次  后  页面会返回到第一页   真的很不爽"
------
@我是谁😉 https://github.com/dataease/dataease/issues 也可提交下issue反馈下

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/35259040/206342009-42509bbe-f9be-460c-87be-3895e14bec01.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，定时任务列表是这样设计的，新创建任务是在最末位的，当执行后会排在首位，因为排序的顺序是按照最近执行任务去排序的；因为考虑到最近的执行任务的使用率高于沉底的任务因此这了这方面的处理
