### ISSUE TITLE
[Bug] sqlserver SQL数据集加了order by 排序报错

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4050]
**DataEase 版本**
1.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.加了order by 就会报错com.microsoft.sqlserver.jdbc.SQLServerException: The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.

![image](https://user-images.githubusercontent.com/82353425/206371857-ea8eb1c6-c4c5-42a6-b7c5-1e05a3e952aa.png)

2.不加order by 报错：com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'score'.
![image](https://user-images.githubusercontent.com/82353425/206372047-d44fd34a-6102-491e-83ac-5364f8abef47.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下
