### ISSUE TITLE
[Bug] 前端：store中mobileLayoutStatus状态问题

### ISSUE THREAD

**Issue by liushuaipeng** [dataease/dataease#4051]
**DataEase 版本**
1.16

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
任意

**Bug 描述**
前端代码中store中有一个叫mobileLayoutStatus的状态，这个状态代码中给的注释是“移动端布局状态”，但是这个状态好像“飘忽不定”，因为有个方法openMobileLayout（启用移动端布局）中的有行逻辑：state.mobileLayoutStatus = !state.mobileLayoutStatus；这会导致该方法每执行一次，mobileLayoutStatus的值会变一次，并不是指向固定的值，这是正确的么？该值是否是用来判断是否为移动端？为true是什么含义？为false是什么含义？

**Bug 重现步骤(有截图更好)**
frontend\src\components\canvas\components\Editor\Preview.vue
此文件的mounted中会触发openMobileLayout；

frontend\src\views\link\view\index.vue
此文件中使用Preview组件，但是因为v-if判断条件问题，会导致Preview加载一次，同理openMobileLayout触发一次；

frontend\src\components\canvas\components\Editor\PreviewEject.vue 
此文件中使用Preview组件，但是因为v-if判断条件问题，会导致Preview加载两次，同理openMobileLayout触发两次；

那么mobileLayoutStatus是否能准确描述某种状态？

**Comment by ziyujiahao** [comment]
mobileLayoutStatus 是true 时指的是在开启移动端的布局设计或者当前处于移动端展示；Preview.vue  不一定会触发mounted中会触发openMobileLayout只有检测到时移动端设备的时候才会触发；PreviewEject.vue 因为有边缘数据加载不同的问题确实可能导致加载两次，我们这里会进行相关的优化，感谢反馈

**Comment by liushuaipeng** [comment]
加载两次的问题是优化问题，但我感觉“万恶之源”是这个 state.mobileLayoutStatus = !state.mobileLayoutStatus；直接state.mobileLayoutStatus  = true;不行么？我不太懂清楚开发者是否有其他的考量，我说两点我自己的想法；
1.假如发生router跳转，是否还是有可能造成Preview重复加载，openMobileLayout重复触发的问题？
2.frontend\src\components\canvas\components\Editor\ComponentWrapper.vue 文件 198  行

```` js
componentActiveFlag() {
    // 此处判断!this.mobileLayoutStatus是否合理？这样会导致移动端edit-bar组件（全屏按钮等）不显示
    return !this.mobileLayoutStatus && ((this.curComponent && this.config === this.curComponent && !this.previewVisible && !this.showPosition.includes('email-task')) || this.showPosition.includes('multiplexing'))
},
````

因为刚接触dataease，不甚熟悉，以上个人愚建；

**Comment by liushuaipeng** [comment]
关于第二点，正是因为你说的边缘数据的问题导致加载两次，“阴差阳错”？反而让edit-bar显示了~

**Comment by BBchicken-9527** [comment]
敢接反馈，我们会尽快优化的

**Comment by BBchicken-9527** [comment]
问题已修复，将会在下个版本上线，感谢你的关注与支持

**Comment by xuwei-fit2cloud** [comment]
v1.18.0版本已处理，请更新最新版本。
