### ISSUE TITLE
不应该明文暴露数据源的敏感信息

### ISSUE THREAD

**Issue by wf-xian** [dataease/dataease#4053]
数据源接口和页面会暴露数据库的用户名密码、ip端口，是非常危险的；

在保存信息时建议加密传输、加密存储、页面上应当脱敏展示；

建议校验和连接数据源时读取数据库中保存的用户名密码，而不是接口传输的用户名密码（因为前端需要脱敏和加密，已经不是原始明文），因此“校验”和“连接”需要发生在“保存”之后。

实际上系统启动时读取所有数据源配置加载到缓存，修改数据源时同步刷新缓存即可，不需要频繁读库。

**Comment by yayanpei** [comment]
感谢您的反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.0版本已处理，请更新最新版本。
