### ISSUE TITLE
[Bug] 参数设置按钮消失

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4054]
**DataEase 版本**
1.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌浏览器

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.设置了 SQL 动态传参
![image](https://user-images.githubusercontent.com/82353425/206613813-6a243414-39fe-4e3b-a282-31487efb7893.png)

2.回到仪表板，参数设置出不来。
![image](https://user-images.githubusercontent.com/82353425/206613764-09aacd35-60d3-4232-adcb-cb97e1e3fdc6.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题

**Comment by tjlygdx** [comment]
当前展示的参数是在仪表板里用到的数据集的参数；
过滤组件所选数据集中的参数，这功能下个版本实现；
