### ISSUE TITLE
[Bug]请问1.17的分页是好的吗，我下载到了 本地启动，查看TableNormal.vue，发现initData方法没有刷新data啊。。

### ISSUE THREAD

**Issue by Level1Accelerator** [dataease/dataease#4055]
**DataEase 版本**
1.17

**运行方式(安装包运行 or 源码运行 ?)** 
源码运行

**浏览器版本**
 googel

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，分页是没问题的；

**Comment by Level1Accelerator** [comment]
> 

我看dataease.fit2cloud.com上的分页是好的，但是1.17的源码本地运行分页数据不变，debug到TableNormal.vue有问题

**Comment by BBchicken-9527** [comment]
请问是直连模式还是定时同步模式呢？直连模式我们有部分数据源原因是无法做到分页的；定时同步模式原本就不分页，肯定不会刷新数据了，都是一次性返回
