### ISSUE TITLE
[Bug]明细表导出excel只能导出当前页，不能导出仪表板的所有数据

### ISSUE THREAD

**Issue by Level1Accelerator** [dataease/dataease#4056]
**DataEase 版本**
1.17

**运行方式(安装包运行 or 源码运行 ?)**
https://dataease.fit2cloud.com/

**浏览器版本**
googel

**Bug 描述**
导出excel只能导出当前页，不能导出仪表板的所有数据

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，此处这个版本做了优化所以只显示当前显示的数据，这么做的原因是因为可能数据量过大导致页面卡顿所；但因为考虑到可能用户存在导出的需求，因为此次的优化导致用户需求不满足所以我们新增了数据集导出的功能；数据集导出功能是可以完整导出你想要的数据的

**Comment by Level1Accelerator** [comment]
> 感谢反馈，此处这个版本做了优化所以只显示当前显示的数据，这么做的原因是因为可能数据量过大导致页面卡顿所；但因为考虑到可能用户存在导出的需求，因为此次的优化导致用户需求不满足所以我们新增了数据集导出的功能；数据集导出功能是可以完整导出你想要的数据的
感谢，看到数据导出了

**Comment by Level1Accelerator** [comment]
> 感谢反馈，此处这个版本做了优化所以只显示当前显示的数据，这么做的原因是因为可能数据量过大导致页面卡顿所；但因为考虑到可能用户存在导出的需求，因为此次的优化导致用户需求不满足所以我们新增了数据集导出的功能；数据集导出功能是可以完整导出你想要的数据的

感谢，看到数据集导出了
