### ISSUE TITLE
[Question] 新增国际化的步骤

### ISSUE THREAD

**Issue by PainAshura** [dataease/dataease#4057]
您好。
请问新增一门国际化的具体操作有哪些。

我打开源码看到了java-resource-i18n里有spring-message的国际化文件，是否新增一个文件，翻译其中的200多个条目，就可以完整的国际化？

或者说，还需要前端代码等调整？

**Comment by yayanpei** [comment]
首先，感谢您对产品的关注和支持。

如果需要新增一种语言的支持，如您所述，不仅要修改后端文件，前端代码也需要调整。
