### ISSUE TITLE
[Feature] 几个版本都还存在的前端展示问题

### ISSUE THREAD

**Issue by ChewJ404** [dataease/dataease#4058]
1. 视图组件 下钻后 ，缩略轴 显示范围 太小了，导致只能展示很少数据，这个能不能优化下 ，看了几个版本都没优化
2. 范围筛选组件 多选 选了一个后 点旁边  收不起来  必须点组件才能收起来

能不能优化下 细节 ，几个版本都还有这种问题

**Comment by maninhill** [comment]
感谢您的反馈。我们这边确认并落实。

**Comment by ChewJ404** [comment]
@yayanpei   第一个问题是  缩略轴外层数据多设置的10% , 下钻  一个维度分类, 如果这个维度不多,下钻后的 缩略轴10% 就很难看了 ,只能显示出一个了 例如
![image](https://user-images.githubusercontent.com/10162958/206949440-1fbc6353-16ab-4fe2-a862-37ae1c124352.png)


第二个问题是 多选的下拉组件 不是日期组件 ,点旁边不收起来
![image](https://user-images.githubusercontent.com/10162958/206949551-fe6b8ea2-75c0-4375-94cb-f51e193fc223.png)

**Comment by yayanpei** [comment]
感谢您的回复，请见如下回复：
1、缩略轴建议在分类较多的情况下使用，如果分类比较少，视图本身是可以完整展示所有分类的，这时不建议您再使用缩略轴了。视图是系统默认给的显示10%，您也可以根据实际需要进行调整。
2、多选的下拉组件，对选项选择完成后，点击下图所示的区域均可以收起下拉框
<img width="517" alt="image" src="https://user-images.githubusercontent.com/84168063/206951503-686cb0b8-208c-4535-8923-4b9bfe6b8423.png">

**Comment by ChewJ404** [comment]
@yayanpei   问题1 是 外层 数据多 ,下钻后 分类少 ,导致缩略图问题,因为下钻 前后数据量不一致
问题2  我试了 下拉组件 ,点左右和下面 ,都没有收起来 是因为  我发现 光标在 下拉框里面 ,是由于这个引起的吗????  版本 v1.17.0
![image](https://user-images.githubusercontent.com/10162958/206970141-0f6d0e52-6fb9-4500-93b2-69faad1824d2.png)

**Comment by ChewJ404** [comment]
@yayanpei  说错了 应该 文本下拉 带搜索的那种  会 点左右 无效

**Comment by ChewJ404** [comment]
@yayanpei 问题1   表达的意思是 ,比如 外层 时间维度 ,很多日期  默认用 缩略图  显示最近一个月的, 下钻后 ,这个缩略图又带到内层 ,内层 维度 不多 ,导致显示看着很怪 ,

**Comment by yayanpei** [comment]
感谢您的回复，问题1我们需要讨论一下，不确定用户的下钻层级以及下钻后数据本身的维度多少，我估计不太好控制。问题2我再确认一下。
