### ISSUE TITLE
[Bug]接口 /systemInfo/userLoginInfo 跳转异常

### ISSUE THREAD

**Issue by leim** [dataease/dataease#4060]
**DataEase 版本**
v1.17.0

**运行方式**
安装包运行（docker）

**浏览器版本**
108.0.5359.99

**Bug 描述**
使用分享链接打开大屏，页面会调用一个接口 /systemInfo/userLoginInfo 判断当前登录状态，如果用户是登录状态，会直接返回json登录信息，如果当前用户不是登录状态，该URL会直接302至首页，如果当前是通过https访问，重定向地址是一个http，浏览器console会报 Mixed Content 异常。

![image](https://user-images.githubusercontent.com/1665397/206945122-314b49ac-477a-40d8-a9a9-b2687dbccaab.png)

**Bug 重现步骤(有截图更好)**
1. 未登录状态打开https分享链接，查看F12，即可看见异常
2. 已登录状态打开https分享链接，查看F12，没有异常，在network里面找到 /systemInfo/userLoginInfo 请求，发现正常返回的json
3. 未登录状态打开http分享链接，查看F12，在network里面找到 /systemInfo/userLoginInfo 请求，发现301重定向到了首页。
4. 已登录状态打开http分享链接，查看F12，在network里面找到 /systemInfo/userLoginInfo 请求，发现正常返回json。

PS：
1. 在v1.16.0版本，无论当前是否登录状态，打开分享链接，都没有这个请求。
2. 在v1.16.0版本，无论当前是否登录状态，如果直接访问 /systemInfo/userLoginInfo，在浏览器内，会直接要求输入basic认证的用户名密码，但是输入dataease的用户名密码并不会验证通过。
3. 通过curl直接请求 /systemInfo/userLoginInfo ，v1.16.0 直接返回 401 ，v1.17.0 直接返回302，跳转至http的首页，无论请求是 http或者https 。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复。
