### ISSUE TITLE
[Bug] 源仪表板存在视图计算字段，在复制仪表板后，编辑复制后的视图计算字段时，表达式区域空白。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4062]
**DataEase 版本**
v1.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome
版本 108.0.5359.94（正式版本） (arm64)

**Bug 描述**
源仪表板存在视图计算字段，在复制仪表板后，编辑复制后的视图计算字段时，表达式区域空白。

**Bug 重现步骤(有截图更好)**
1. 源仪表板存在视图计算字段：
![image](https://user-images.githubusercontent.com/30063018/206949908-23e5e26e-b979-46ce-ab85-a7461bd6f79a.png)
2. 复制后，目标仪表板的视图计算字段表达式区域为空白：
![image](https://user-images.githubusercontent.com/30063018/206950061-de9b2eb1-1c8e-4595-8ff1-195680b08b49.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.0版本已处理，请更新最新版本。
