### ISSUE TITLE
[Bug]使用直连模式数据集的明细表导出 Excel 只有第一页的数据

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4064]
**DataEase 版本**
v1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
使用直连模式数据集的明细表导出 Excel 只有第一页的数据，如下图所示：
![image](https://user-images.githubusercontent.com/48945409/206968974-e30f2870-4ddc-4e8e-b6df-6e6464b82af0.png)

**更多测试情况补充：**
1.定时同步数据集：导出的为全部；
2.AntV 直连导出的为第一页；
3.ECharts 直连导出的为第一页；
4.Excel 数据集导出的为全部。

**Comment by BBchicken-9527** [comment]
感谢反馈，你说的是视图中的明细然后再经过明细导出嘛？如果是这里的导出的话是没有问题的，此次升级优化了明细表的分页来解决数据量过大导致仪表板相应的问题，如果给出全部数据的话数据的存放等问题依然会导致仪表板的响应的

**Comment by luyang351** [comment]
但是导出的数据不应该受到分页影响的，导出的是整个视图的数据，视图通过分页一页一页的展示，但是数据应该是所有页面的。
且上述的几个测试内容中，只有 AntV 明细表为后台分页，ECharts 明细表是前台分页却也只能导出第一页的数据。
总的来说导出数据跟视图本身分页展示已经无关了，逻辑应当是一致的，不论是何种数据源数据集，是前台分页还是后台分页。

**Comment by BBchicken-9527** [comment]
感谢反馈，因为如果此处导出依旧按照原本的方式导出那就像我之前说的全部数据的存放已让会是影响仪表板响应产生大幅的增加，嗯... 不过你说的点也确实会受到影响，这样我们讨论一下看看有没有更完整的解决方案
