### ISSUE TITLE
[Bug]时间过滤组件中「日期范围」的长度&宽度的控制与文本筛选框在可见性上明显不一致

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#4069]
**DataEase 版本**
v1.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome：107.0.5304.121

**Bug 描述**
时间过滤组件中「日期范围」的长度&宽度的控制与可见的框不一致
同样的宽/高设置，日期范围组件与文本搜索组件显示不一致，不方便对整体控件的大小/位置进行调整

**Bug 重现步骤(有截图更好)**
<img width="624" alt="image" src="https://user-images.githubusercontent.com/46042812/206997781-b1fa2ade-8940-414b-bcf5-531eb45dd6ea.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，上是画板与视图上端的像素距离，左是画板与视图左侧像素距离，看您的截图左应该是没问题的，宽和高代表了组件的大小，目前我从我这边现有环境上测试是没有问题的，不过我们判断可能会和之前的一个问题是同样原因导致，我们下次发版你尝试更新看一下是否有解决
