### ISSUE TITLE
[Feature]增加组件隐藏功能

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#4070]
**请描述您的需求或者改进建议.**
增加组件隐藏功能，使用场景
1、有些视图只是在某一时间段不用展示，但是后期还会再用
2、筛选组件不想展示，可以根据不同条件显示不同数据以达到不同大屏的展示效果

**Comment by yayanpei** [comment]
感谢反馈，我们先记录一下，也烦请您能够再具体一点描述所使用的场景，比如在什么业务场景下，需要隐藏视图？为什么要隐藏呢？隐藏后会可能影响现有仪表板的布局，造成布局与原先不一致、或者原视图位置会有留白。

**Comment by xiebei-l** [comment]
使用场景：
1、有些视图只是在某一时间段不用展示，但是后期还会再用
2、筛选组件不想展示，可以根据不同条件显示不同数据以达到不同大屏的展示效果
建议隐藏后的视图默认为悬浮模式，并隐藏起来，位置可以留白，但是需要可以选择已隐藏视图的按钮

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。
