### ISSUE TITLE
[Feature]视图样式结果展示条数可以根据时间升序或者降序设置

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#4074]
**请描述您的需求或者改进建议.**
视图样式结果展示条数可以根据时间升序或者降序设置，目前截取的数据，展示的效果跟想要的一直是反的，例如想要截取时间近的十条数据，但是并不是
<img width="648" alt="image" src="https://user-images.githubusercontent.com/70566485/207009676-6cdc1286-2d60-46b4-91f7-d3726eef9ce0.png">
<img width="889" alt="image" src="https://user-images.githubusercontent.com/70566485/207009994-c386c675-0aaa-4eca-9590-2c6e02cfb99d.png">

**Comment by yayanpei** [comment]
感谢反馈，类似于top10排行榜这样的，视图中还未支持上，建议在数据集中先将数据集按最近时间截取10条，然后视图中排序展示。
