### ISSUE TITLE
[Feature]柱状图显示占比同时可以显示每根柱子的具体数值

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4076]
**请描述您的需求或者改进建议.**
如下图，目前只能显示 “快速计算” 的占比，不能显示每根柱子的具体数值，可否同时显示占比和数值？
<img width="430" alt="图片" src="https://user-images.githubusercontent.com/48307752/207011963-2fa3fb88-d2f6-4ae7-8503-5fe2ff64278c.png">

**Comment by xuwei-fit2cloud** [comment]
这个涉及到标签内容自定义的支持，目前AntV图库还没有做相关功能开发，需求我们已记录。
