### ISSUE TITLE
[Bug] 数据源check，Success后，过一会后会变成Error

### ISSUE THREAD

**Issue by VanLiuZhi** [dataease/dataease#4084]
**DataEase v1.5.0**

**源码运行**

**Bug 描述**

新增了vertica数据源支持，系统不是有个定时check的机制吗？这些我都实现了，job check的时候，新增加的
vertica数据源，状态是Success，但是等一小会，可能十多秒左右，或者半分钟，从数据库看这个状态，又变回Error了

难道还有其它地方去修改这个状态吗？表示很费解，没有在代码里面找到原因，希望能给一点点提示

我也考虑过是不是数据库事务级别，自动提交的问题，貌似不是

**Comment by BBchicken-9527** [comment]
感谢反馈，你这么说我也不是很清楚的，有更具体的信息吗
