### ISSUE TITLE
[Bug]透视图关联效果与其他视图的关联效果不一致

### ISSUE THREAD

**Issue by gaohonghai** [dataease/dataease#4086]
**DataEase 版本**
V1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 108.0.5359.98（正式版本） (x86_64)

**Bug 描述**
1、饼状图关联明细表的效果
![image](https://user-images.githubusercontent.com/92966838/207489739-36dfaaa1-62cd-4e41-96bc-56c8a59fb3f4.png)
![image](https://user-images.githubusercontent.com/92966838/207489929-9f09c578-c3a5-43c1-b1a3-e6918dc3fab9.png)

2、透视图的关联明细表的效果
![image](https://user-images.githubusercontent.com/92966838/207490360-98de152a-d0bd-4349-bb7b-14a0e1928b00.png)
![image](https://user-images.githubusercontent.com/92966838/207490645-96e5544f-19b3-4372-9e8b-655ea8b65d8e.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前是不支持的，再就是因为联动的最终关联是字段与字段直接的联系，是一个点到点的逻辑，不可能点击指标发送维度的，如果这样联动肯能会引起一些不必要的异常，望理解；
