### ISSUE TITLE
[Bug] clickhouse数据源，直连模式下通过字段管理时间格式化异常

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4089]
**DataEase 版本**
v1.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 108.0.5359.94（正式版本） (arm64)

**Bug 描述**
clickhouse 版本：22.1.3.7
clickhouse数据源，直连模式下通过字段管理时间格式化异常

**Bug 重现步骤(有截图更好)**
1.  直连数据库数据集如下所示：
![image](https://user-images.githubusercontent.com/30063018/207498453-2e0cab2a-a585-4192-9349-1d2ad6edc1a2.png)
2. 字段管理设置时间格式化：
![image](https://user-images.githubusercontent.com/30063018/207498538-9c6002a9-db2c-45f0-bdbd-de6519086c77.png)
3. 转换后的结果非预期结果，如下所示：
![image](https://user-images.githubusercontent.com/30063018/207498645-db3a5a1e-1b08-4f84-9a2d-f621f24620d7.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
目前还没找到字符串格式化成为时间的函数
