### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by dai-yulong** [dataease/dataease#4090]
**DataEase 版本**
15.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌

**Bug 描述**
![image](https://user-images.githubusercontent.com/52453981/207524472-6cad1b1f-e0a3-48bd-b759-7f859e24c012.png)

实参可以，变量报错，可以查询，但不能保存

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你这是什么数据源？

**Comment by dai-yulong** [comment]
oracle的数据库，直连方式

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by tjlygdx** [comment]
> 

能把完整的sql 贴一下吗？

**Comment by tjlygdx** [comment]
> oracle的数据库，直连方式

能把完整的sql 贴一下吗？

**Comment by dai-yulong** [comment]
select a."日期",a."院区" ,a."科室名称",a."物资编码",a."物资名称",a."规格型号",a."是否高值",a."是否试剂",nvl(b."数量",0) 基年数量,nvl(b."出库额",0) 基年出库额,a."数量" 报告年数量,a."出库额" 报告年出库额,round((a."数量"-nvl(b."数量",0))/nvl(b."数量",1),4) 同比增长率
from (select a.* from V_BI_SETTLE_GOOD_SORT a where a.日期 = '${parm_stat}') a
left join (select b.* from V_BI_SETTLE_GOOD_SORT b where b.日期 = to_char(ADD_MONTHS(TO_DATE(trim(concat('${parm_stat}','/01')),'YYYY/MM/DD'),-1),'YYYY/MM')) b 
on a."科室名称"=b."科室名称"(+) and a."物资编码"=b."物资编码"(+)
where a.院区='${parm_ownername}'
and a.科室名称='${parm_deptname}'
and a.是否高值='${parm_isbar}'
and a.是否试剂='${parm_isrgt}'

**Comment by tjlygdx** [comment]
目前还不支持在join 中使用参数；
我们要调研一下实现难度。
