### ISSUE TITLE
给一份docker的安装方案， 暴露哪些变量这些

### ISSUE THREAD

**Issue by huangapple** [dataease/dataease#4094]
我知道  目前脚本安装的也是走的docker
```
curl -sSL https://github.com/dataease/dataease/releases/latest/download/quick_start.sh | sh
```

但我更需要一份docker的说明， 而不是一个脚本文件， 有点黑盒。
我可能是要部署在k8s， 或别的地方上， docker说明才是刚需

**Comment by leim** [comment]
version: '2.1'

services:
  dataease:
    image: registry.cn-qingdao.aliyuncs.com/dataease/dataease:v1.17.0
    container_name: dataease
    mem_limit: 2048m
    restart: always
    networks:
    - de
    ports:
    - 8081:8081
    volumes:
    - /opt/dataease/conf:/opt/dataease/conf
    - /opt/dataease/data/kettle:/opt/dataease/data/kettle
    - /opt/dataease/logs:/opt/dataease/logs
    - /opt/dataease/plugins/thirdpart:/opt/dataease/plugins/thirdpart
  kettle:
    container_name: kettle
    image: registry.cn-qingdao.aliyuncs.com/dataease/kettle:v8.3-0318
    environment:
      PENTAHO_DI_JAVA_OPTIONS: -Xms2048m -Xmx2048m -XX:MaxPermSize=256m -Dfile.encoding=utf-8
    networks:
    - de
    restart: always
    volumes:
    - /opt/dataease/conf:/opt/dataease/conf
    - /opt/dataease/data/kettle:/opt/dataease/data/kettle

networks:
  de:
    external:
      name: de

**Comment by huangapple** [comment]
是不是少了mysql的配置

**Comment by xuwei-fit2cloud** [comment]
可以参考以下这个工程
https://github.com/dataease/installer
