### ISSUE TITLE
[Bug] 公共链接导出为 pdf 时，视图的边框丢失

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4096]
**DataEase 版本**
v1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
Google Chrome
版本 108.0.5359.94（正式版本） (arm64)

**Bug 描述**
 公共链接导出为 pdf 时，视图的边框丢失

**Bug 重现步骤(有截图更好)**
1. 仪表板内的视图带边框，使用公共链接分享出来，如下所示：
![image](https://user-images.githubusercontent.com/30063018/207784937-d75e4488-83ee-471d-b99b-d8779315cbc5.png)
2. 点击下载，预览界面无边框，最终导出的 pdf 也无边框
![image](https://user-images.githubusercontent.com/30063018/207785224-d12aa529-26e5-45e1-abe6-750c1570ba98.png)
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/30063018/207785270-442c8e98-9d89-45b0-9c39-573105385956.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，请问是必现吗？我在测试环境和开发环境都没发现此问题
