### ISSUE TITLE
[Bug]AntV图表类型标题字体大小未自适应

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#4101]
**DataEase 版本**
V1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 107.0.5304.121（正式版本） (x86_64)

**Bug 描述**
AntV图表类型中柱状图标题字体大小未自适应

**Bug 重现步骤(有截图更好)**
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/70566485/207805184-76a443c2-ab00-49ab-a9b8-e39eb9088a11.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你说的不自适应是因为图例显示和标题显示大小不一致吗？还是什么意思？首先图例的文字是不能和标题相比较的，标题是文字属性的，而图例显示的文字你可以立即他本质是一个图片的；两者相比较是会不一样的
