### ISSUE TITLE
[Bug]富文本视图设置字体颜色不生效

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#4104]
**DataEase 版本**
V1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 107.0.5304.121（正式版本） (x86_64)

**Bug 描述**
富文本视图设置字体颜色后，全屏预览后再进入仪表板编辑页面，字体颜色不生效（丢失）

**Bug 重现步骤(有截图更好)**
1、设置富文本字体颜色
<img width="236" alt="image" src="https://user-images.githubusercontent.com/70566485/207809201-b99e3915-5121-4ae5-af25-9a372e6e6ba7.png">

2.全屏预览后恢复为设置前颜色红色
<img width="268" alt="image" src="https://user-images.githubusercontent.com/70566485/207809325-4b7d576a-b200-4482-90d7-4a6b4b9dfc18.png">

3.无法切换其它颜色

**Comment by BBchicken-9527** [comment]
感谢反馈，你说的是富文本视图吗？目前没发现你说的不生效的情况；
