### ISSUE TITLE
[Question]定时同步不能选， 是正常的？

### ISSUE THREAD

**Issue by huangapple** [dataease/dataease#4105]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/10572028/207813685-3de996cf-71fa-49b0-8a71-9f9e77ab4595.png)

**Comment by xuwei-fit2cloud** [comment]
默认安装方式是精简模式，在精简模式下是没有定时同步功能的。如果需要定时同步功能，可以参考文档：
https://dataease.io/docs/installation/installation_mode/

**Comment by huangapple** [comment]
仪表盘我没看到哪边可以设置多久重新拉取一次数据， 是通过这个 定时同步的吗？

**Comment by huangapple** [comment]
可以在界面上把为什么定时同步不能勾选的理由写出来

**Comment by xuwei-fit2cloud** [comment]
仪表板上可以设置页面刷新的频率，同步类型数据集的更新频率是在定时任务里设置的。
我们在下个版本里会对这个下拉选项做相关优化，精简模式下不会显示定时同步选项。

**Comment by huangapple** [comment]
有点不好找， 居然在样式里面。

**Comment by xuwei-fit2cloud** [comment]
嗯嗯，这个地方我们后续版本也会相继做一下优化工作。
