### ISSUE TITLE
[Bug]定时同步报错

### ISSUE THREAD

**Issue by hzhfit2cloud** [dataease/dataease#4108]
**DataEase 版本**
v1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome

**操作系统版本**
CentOS Linux release 7.9.2009 (Core)

**Bug 描述**
自带Demo及其他MySQL数据源：直连没问题，定时同步则报错
在演示环境未复现，但是客户环境一直有报错
尝试了重启服务器、重启DE服务错误仍然存在

**Bug 重现步骤(有截图更好)**
1、页面报错截图
<img width="814" alt="image" src="https://user-images.githubusercontent.com/89765365/208010247-7d1c6826-ce88-474f-8e2e-1a39d177ed1b.png">
2、数据库执行 show variables like "%collation%";
<img width="663" alt="image" src="https://user-images.githubusercontent.com/89765365/208010422-1dd363d2-cfe2-4775-9fc3-009a5fa09508.png">
3、时区排查
<img width="416" alt="image" src="https://user-images.githubusercontent.com/89765365/208010477-89d7b464-2df6-463b-8aa4-c4b559ae5485.png">
4、容器健康检查
<img width="777" alt="image" src="https://user-images.githubusercontent.com/89765365/208010730-9dadf623-530c-4ace-9faf-f4ae2b6baa3b.png">

**Comment by hzhfit2cloud** [comment]
[error.log](https://github.com/dataease/dataease/files/10242227/error.log)
[info.log](https://github.com/dataease/dataease/files/10242228/info.log)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们排查一下
