### ISSUE TITLE
[Bug]API 数据源请求时会放置错误的 ContentEncoding 导致接口调用异常

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#4109]
**DataEase 版本**
1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 最新

**Bug 描述**
ContentEncoding 不应放置 charset
![image](https://user-images.githubusercontent.com/30886198/208011364-b4abda95-95a1-4dff-901b-8b4f6ee6e0d7.png)

参见
https://blog.csdn.net/u014569188/article/details/78912446

**Comment by BBchicken-9527** [comment]
感谢反馈，我们修复一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.2版本已处理，请更新相关版本。
