### ISSUE TITLE
[Bug]富文本视图设置字体时，动态参数字体无法单独设置

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4110]
**DataEase 版本**
v1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
富文本视图设置字体时，动态参数字体无法单独设置，设置后展示无效，只有行高改变了。

**Bug 重现步骤(有截图更好)**
1.统一设置 18px 的字体
![image](https://user-images.githubusercontent.com/48945409/208015782-1ec47b45-e9d2-4533-a69a-fa0b145fc620.png)

2.单独选中渗透率的参数，选择 32px 的字体
![image](https://user-images.githubusercontent.com/48945409/208015849-56cb6fb0-506c-46d7-9c70-0ef53e75ea63.png)

3.字体无变化，行间隔变宽
![image](https://user-images.githubusercontent.com/48945409/208015920-8841d9a1-594f-4c1e-9f04-004b6671d46b.png)

4.单独设置别的字的字体正常
![image](https://user-images.githubusercontent.com/48945409/208015977-f146e010-e872-4669-ab43-5c8ad9c30d75.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，如果要设置动态参数大小点击动态参数即可设置参数文字属性，如图：
![image](https://user-images.githubusercontent.com/84372766/208300324-21cfb319-a913-47d7-a5fb-018a678859da.png)
