### ISSUE TITLE
[Bug]复制视图后修改图表类型或修改数据集，视图颜色恢复成默认值

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4116]
**DataEase 版本**
1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
复制视图后修改图表类型或修改数据集，视图颜色恢复成默认值

**Bug 重现步骤(有截图更好)**
1.原视图如下
![image](https://user-images.githubusercontent.com/48945409/208053454-56bff08c-6d0c-437c-8fb9-2394761f0107.png)

2.复制后的视图如下，颜色是一致的
![image](https://user-images.githubusercontent.com/48945409/208054047-227cacd2-231b-4dad-a22f-444a283fee20.png)

3.修改图表类型，颜色变为默认的
![image](https://user-images.githubusercontent.com/48945409/208054218-d27cc498-fdb1-4c82-831f-a1a41040e473.png)
![image](https://user-images.githubusercontent.com/48945409/208054317-ad91c895-e6ef-4884-b54d-c61d54be8e6b.png)

4.再重新从原视图复制一个，这次修改所使用的数据集，颜色也变成了默认色
![image](https://user-images.githubusercontent.com/48945409/208054500-00526e87-7d18-4ae3-a798-0b59ea9a818d.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，切换数据集和图表类型，重置自定义颜色。
因为自定义颜色，是绑定维度枚举值或者指标字段的。
数据集的改变会导致数据和字段变化，因此不保留原来的设置结果；图表类型切换会导致汇总计算方式改变，也会导致枚举值改变或者字段改变，因此无法保留结果
