### ISSUE TITLE
[Question] 关于k8s部署说明

### ISSUE THREAD

**Issue by huangapple** [dataease/dataease#4122]
我了解到的， 不能在k8s中部署是因为 doris  ， 那如果是精简模式的呢？是否能给一份部署说明？

**Comment by mfanoffice** [comment]
我个人整理一份 k8s 部署 DataEase 的方案，你可以参考一下 https://github.com/mfanoffice/dataease-helm

**Comment by huangapple** [comment]
没有看懂，   但还有一个问题， 如何添加访问前缀？  比如我要添加 de访问前缀，  即  访问路径变成了 127.0.0.1/de, 要如何处理？

**Comment by yayanpei** [comment]
添加访问前缀，可以参考一下这个文档：https://dataease.io/docs/dev_manual/dev_deployment/compile/
