### ISSUE TITLE
[Bug]分组折线图，添加子类别后，数值格式不生效

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4137]
**DataEase 版本**
1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome

**Bug 描述**
分组折线图，添加子类别后，数值格式不生效

**Bug 重现步骤(有截图更好)**
1. 添加折线图

2.维度和指标，添加后，设置指标的数值格式，以万为单位显示； 
<img width="1190" alt="图片" src="https://user-images.githubusercontent.com/48307752/208629628-49ce8480-3447-4bce-af6b-43e6bf79a689.png">

3.添加子维度后，折线图不再以万为单位显示
<img width="1191" alt="图片" src="https://user-images.githubusercontent.com/48307752/208629356-216abdf7-b0e5-4c7c-abd5-af08f1541aff.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
