### ISSUE TITLE
[Bug]数据集编辑页面数据名称始为新建数据集

### ISSUE THREAD

**Issue by wzf159** [dataease/dataease#4140]
**DataEase 版本**
1.16.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome新

**Bug 描述**
数据集中编辑例如名称为“项目情况”的数据集同步数据库表数据集，显示的名称任然为新建数据集

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/45838600/208694195-b5634938-c1af-4cd0-b8eb-ad3a528d8b25.png)

2.
![image](https://user-images.githubusercontent.com/45838600/208694285-faf135ac-010a-4fc0-ae85-9f065c2f7431.png)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，此问题是修复过的，你可以更新版本尝试
