### ISSUE TITLE
[Feature] 点击透视表内容，能展示对应的明细表数据。

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4142]
**请描述您的需求或者改进建议.**
仪表板内含有透视表与明细表，比如透视表里面有个“95 后”，“身高 180 以上”记录数为“ 3”，点击“3” 的时候，能看到关于“95 后”并且“身高 180 以上”的明细。
![98e784ee68c62eba7809f48f2c05902](https://user-images.githubusercontent.com/82353425/208804592-0acc5df1-4ca4-498d-9f32-6b6b01b19205.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，记录数是我们做统计新加的字段，目前这个字段还没有支持跳转。
