### ISSUE TITLE
[Bug] 文本下拉组件多选时按照模糊搜索过滤出部分内容，再选择全选，没有按照过滤后的内容全选

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4144]
**DataEase 版本**
v1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 108.0.5359.124（正式版本） (arm64)

**Bug 描述**
文本下拉组件多选时按照模糊搜索过滤出部分内容，再选择全选，没有按照过滤后的内容全选

**Bug 重现步骤(有截图更好)**
1. 设置好文本下拉组件，并且选择多选
<img width="821" alt="image" src="https://user-images.githubusercontent.com/30063018/208809404-1da94af2-5b3a-434c-a8e8-b8657155aba2.png">
2. 下拉框内进行模糊搜索
<img width="464" alt="image" src="https://user-images.githubusercontent.com/30063018/208809501-39ea985a-d5f8-469c-9d6e-86a43a61f2ca.png">
3. 勾选全选，选中的并非是过滤后的内容，而是所有内容，期望是按照勾选后的结果进行选择
<img width="392" alt="image" src="https://user-images.githubusercontent.com/30063018/208809597-848c4e04-c100-479a-80bf-16240d9c9b31.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by BBchicken-9527** [comment]
问题已修复，将会在下个版本上线，感谢你的反馈与支持；

**Comment by xuwei-fit2cloud** [comment]
v1.18.0版本已处理，请更新最新版本。
