### ISSUE TITLE
[Feature] 轴值自动，最小值能动态读取数据展示，不是默认为0

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4147]
**请描述您的需求或者改进建议.**
例如如图：他的值都是在0.1-0.12波动，根本就看不出来变化，实际上百分之1的波动影响也很大，原因就在于轴值默认为0开始
![img_v2_bae669a9-270c-4b8b-8c37-0e896d78c70h](https://user-images.githubusercontent.com/82353425/208821836-1135065a-27c7-4b6c-9656-a9ba225b3d19.jpg)

虽然轴值能自定义调节最小值最大值，但是需要提前判断最小值是多少才行。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈。这个应该是ECharts图库中的组合图类型。
ECharts图库是可以支持根据最大值和最小值动态设置坐标上下限值的，我们先记录一下。
