### ISSUE TITLE
[Question]如何添加请求前缀？

### ISSUE THREAD

**Issue by huangapple** [dataease/dataease#4150]
部署好后， 默认是127.0.0.1

但服务器上还有其它服务， 也只有一个域名， 如何添加访问前缀， 比如 /de,
使访问  127.0.0.1/de ， 才能进入系统

**Comment by huangapple** [comment]
@xuwei-fit2cloud 支持吗？

**Comment by huangapple** [comment]
或者能不能马上支持一下， 留个环境变量， 让外部可以控制

**Comment by yayanpei** [comment]
感谢反馈，可以参考一下在线文档，文档地址为：https://dataease.io/docs/dev_manual/dev_deployment/compile/
