### ISSUE TITLE
[Bug]缺少全局scss变量导致的样式问题

### ISSUE THREAD

**Issue by OlderBabyML** [dataease/dataease#4151]
**DataEase 版本**
1.17分支

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome 108.0.5359.125（正式版本） （64 位）

**Bug 描述**
有很多全局变量并没有被引入，导致系统用的默认变量，然后出现了样式问题

**Bug 重现步骤(有截图更好)**
比如下面这个情况是因为没有引入全局变量--deWhiteHover造成的
![dd3fab81b83a710f21d54e325d8f194](https://user-images.githubusercontent.com/50657209/208842256-821ae3e8-daf4-4971-af91-cf68cb117de0.jpg)
我把变量写到dark.scss里，然后在index.scss里引入就显示正常了
![image](https://user-images.githubusercontent.com/50657209/208842571-c2d350eb-76a3-49b4-9e81-5c3cdc7f7846.png)
![image](https://user-images.githubusercontent.com/50657209/208842608-e09bc457-2f93-4ace-a79a-12dde513efcf.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
感谢你的关注，目前问题已修复，将会在下个版本上线，可下载体验

**Comment by xuwei-fit2cloud** [comment]
v1.18.0版本已处理，请更新最新版本。
