### ISSUE TITLE
[Feature]过滤组件的控制范围显示优化

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4152]
**请描述您的需求或者改进建议.**
过滤组件中的 “控制范围” ，希望选择数据集的字段后，才会显示该数据集关联的视图，而不是直接显示仪表板所有的视图；

<img width="791" alt="图片" src="https://user-images.githubusercontent.com/48307752/208844378-0f7517a2-efdd-4d65-8dae-55d0511528a4.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这块我们后期做一下优化。
