### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by kennth** [dataease/dataease#4153]
**DataEase 版本**
1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 108.0.1462.46

**Bug 描述**
使用hive1.1.1時，創建數據源成功，創建數據集報錯
看源代碼后發現HiveQueryProvider使用了該版本的hiveSQL不支持的limit start,end方法

**Bug 重现步骤(有截图更好)**
1.連接hive1.1.1
2.使用該hive數據源創建數據集
3.報錯Error while compiling statement: FAILED: ParseException line 1:25 missing EOF at ',' near '0' (state=42000,code=40000)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by BBchicken-9527** [comment]
你尝试过，修改驱动吗？有没有可能是驱动导致出现异常的呢
