### ISSUE TITLE
[Bug]日期过滤组件和数值组件对地图不生效

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4158]
**DataEase 版本**
1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome

**Bug 描述**
日期过滤组件 和 数值组件 对 Echart地图不生效，其他视图正常

**Bug 重现步骤(有截图更好)**
1. 仪表板添加Echart 地图；
2. 添加日期组件  和 数值组件
3. 选择日期，或选择数值，Echart地图视图没有反应。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前我这边环境没有发现你说的问题，我这边看了地图与气泡地图都没有发现你这种情况，方便提供更多的一些信息给我们判断吗？如前段异常等

**Comment by BBchicken-9527** [comment]
嗯...你说的这三个组件我也看过确实没有发现什么问题
![image](https://user-images.githubusercontent.com/84372766/209044839-415752b5-2995-4a44-a7e8-c2fc11322592.png)
![image](https://user-images.githubusercontent.com/84372766/209044865-a952d24a-6c8f-400d-9b68-b627dc1c0bac.png)
![image](https://user-images.githubusercontent.com/84372766/209044902-90f98c17-da3b-4e53-90e4-c5979e123907.png)

**Comment by mfanoffice** [comment]
刚刚测试确实没有问题，不知道上次哪里操作不对

**Comment by mfanoffice** [comment]
我们有发现了新问题，年份组件、日期范围组件，如果选择不存在的日期，柱状图会显示空白数据，但地图没有变化。
<img width="517" alt="图片" src="https://user-images.githubusercontent.com/48307752/209261292-a015a510-56bc-49c7-8ab3-23c6321a6d3e.png">
<img width="720" alt="图片" src="https://user-images.githubusercontent.com/48307752/209261480-479bc127-c1b9-4055-9be4-9f8c8c6b4804.png">

**Comment by BBchicken-9527** [comment]
确实存在此类问题，我们尽快修复一下
