### ISSUE TITLE
[Bug] 浏览器崩溃之后，点击其他功能卡顿

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4166]
**DataEase 版本**
1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.仪表板都是AntV的汇总表，且数据量很大，之后就会导致前端浏览器崩溃，崩溃之后CPU一直高负载
![bf58d134a3ea5725787e64c14d0fd7a](https://user-images.githubusercontent.com/82353425/209089738-9e9e3ad7-bad7-443e-b3f4-88f98366fb0b.png)
![47fe19d5cc36dd67b14c8d892cf1abe](https://user-images.githubusercontent.com/82353425/209089756-5a550f2a-3479-48e8-b64d-d957206819fa.png)
![fc94b792c4660a08c65471a99486e15](https://user-images.githubusercontent.com/82353425/209089788-c65e6724-f8a6-44d8-b9b4-3b7f4d967be9.jpg)

2.再点击“用户管理”“数据集”等功能页面都不会返回数据，猜测就是后端的线程卡主了，导致请求堵塞了。
3.比较棘手的问题就是，明明前端已经崩溃了，点击其他功能卡主。

**Comment by BBchicken-9527** [comment]
感谢反馈，请问大概是多大的数据量我这边模拟一下

**Comment by ywhfzy** [comment]
> 感谢反馈，请问大概是多大的数据量我这边模拟一下

13万的数据，使用的是透视表。

**Comment by BBchicken-9527** [comment]
感谢反馈，建议将数据先做一次聚合处理，如果数据量过大是会产生一些问题，我们这边的优化空间其实很有限，因这种timeout并不是前端绘图导致，而是后端数据量查询数据过大导致，大部分的压力都在io上面其实，我们开会讨论一下看看有没有什么更好的解决方案去处理你现在的这种情况；
