### ISSUE TITLE
[Bug] 数据源是Doris, 新建SQL 数据集，SQL 排序返回数据集排序异常

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [dataease/dataease#4180]
**DataEase 版本**
1.17

**运行方式(安装包运行 or 源码运行 ?)**

安装包运行（Local 模式）

**浏览器版本**
谷歌浏览器108版本

**Bug 描述**
数据源是Doris ， 新建SQL 数据集， SQL 包含排序的内容， 返回的数据集没有如预期要求的顺序。

**Bug 重现步骤(有截图更好)**
1.  新建SQL 数据集，执行SQL , 如下：
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/30264974/209345654-aed435e6-3832-46ff-8d33-4738955c11f4.png">

2. 数据库表的字段类型如下，不是字符串类型
<img width="973" alt="image" src="https://user-images.githubusercontent.com/30264974/209345881-cbde7ccc-8c75-4dba-9289-dda138ab2636.png">

3.同样的SQL , 直连Doris ， 在Navicat 执行结果如下：
![image](https://user-images.githubusercontent.com/30264974/209346038-06b6c9d1-8eb4-4836-9688-a7bb3b9d9ab5.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by xuwei-fit2cloud** [comment]
预览sql时，DataEase为了加上limit会将sql包一层，所以嵌套sql后，内层的排序失效
