### ISSUE TITLE
[Bug]修改SQL 数据集，导致视图配置的字段排序以及过滤器失效

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [dataease/dataease#4181]
**DataEase 版本**
1.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 （Local 模式）

**浏览器版本**
谷歌浏览器（108 版本）

**Bug 描述**
修改SQL 数据集，删除字段再新增字段，保存。 数据集对应的视图字段排序失效，配置的过滤器失效。需要手动进行一个个视图重新配置。

**Bug 重现步骤(有截图更好)**
1.  新建SQL 数据集， 配置对应的视图，如下图：
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/30264974/209347137-22f15480-457f-46ee-b4bd-7daf4e07d991.png">
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/30264974/209347293-fd4cfdee-1eb9-4f89-b3e0-01d2174c83af.png">

2.编辑SQL 数据集， 删除num 字段，保存SQL 数据集。 
3.编辑SQL 数据集， 新增num 字段，保存SQL 数据集。
（这个操作在调试sql 的过程很常见）
4.打开仪表板，对应的视图，效果如下图，排序失效，过滤器失效
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/30264974/209347812-a7fa007d-5604-4d30-a10b-7ba9e2bcbe66.png">

这会导致需要手动修改该数据集所关联的每一个视图。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前我这边测试没发现你说的这种问题，请问是不是有什么细节？

**Comment by fit2cloud-zaopengguo** [comment]
> 

您在SQL 数据集删除的字段是要在视图已经引用了的字段。 而且是删除字段之后要保存SQL数据集， 再新增回同样的字段，保存SQL 数据集

**Comment by fit2cloud-zaopengguo** [comment]
> > 
> 
> 您在SQL 数据集删除的字段是要在视图已经引用了的字段。 而且是删除字段之后要保存SQL数据集， 再新增回同样的字段，保存SQL 数据集

并且这个字段在视图上 配置排序 以及 过滤器。

**Comment by BBchicken-9527** [comment]
> > > 
> > 
> > 
> > 您在SQL 数据集删除的字段是要在视图已经引用了的字段。 而且是删除字段之后要保存SQL数据集， 再新增回同样的字段，保存SQL 数据集
> 
> 并且这个字段在视图上 配置排序 以及 过滤器。

你说的删除字段后要保存SQL数据集是进入编辑页面后不改动sql语句直接保存吗？

**Comment by fit2cloud-zaopengguo** [comment]
> > > > 
> > > 
> > > 
> > > 您在SQL 数据集删除的字段是要在视图已经引用了的字段。 而且是删除字段之后要保存SQL数据集， 再新增回同样的字段，保存SQL 数据集
> > 
> > 
> > 并且这个字段在视图上 配置排序 以及 过滤器。
> 
> 你说的删除字段后要保存SQL数据集是进入编辑页面后不改动sql语句直接保存吗？



> > > > 
> > > 
> > > 
> > > 您在SQL 数据集删除的字段是要在视图已经引用了的字段。 而且是删除字段之后要保存SQL数据集， 再新增回同样的字段，保存SQL 数据集
> > 
> > 
> > 并且这个字段在视图上 配置排序 以及 过滤器。
> 
> 你说的删除字段后要保存SQL数据集是进入编辑页面后不改动sql语句直接保存吗？

是通过修改sql 的方式，删除字段。删除后，要保存SQL 数据集。

**Comment by xuwei-fit2cloud** [comment]
目前确实会给出修改提示，但不会影响仕途展示。
我们后期优化一下。
