### ISSUE TITLE
[Feature]希望增加在线数据填报功能，可选择更新到数据库或更新到数据集

### ISSUE THREAD

**Issue by lyons-hz** [dataease/dataease#4186]
**请描述您的需求或者改进建议.**
目前Excel数据集只能通过文件上传方式更新，填写新数据或者修改错误数据比较麻烦。
在工厂生产活动中，有些数据不能写入数据库，需要员工手工填写。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个需求已经在我们需求池中，我们会做相关开发计划。
