### ISSUE TITLE
[Bug]【仪表板】移动端布局去除组件有问题

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#4187]
**DataEase 版本**
1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
仪表板】移动端布局去除组件有问题，详见视频

**Bug 重现步骤(有截图更好)**

https://user-images.githubusercontent.com/24768910/209497268-c03321fb-a2a2-432f-8012-0a49bd31f544.mov

**Comment by xuwei-fit2cloud** [comment]
v1.18.0版本已处理，请更新最新版本。

**Comment by AndroidBaby1** [comment]
好的，谢谢，给力！
