### ISSUE TITLE
[Bug]【仪表板】移动端布局调整有问题

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#4188]
**DataEase 版本**
1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
【仪表板】移动端布局调整有问题，详见视频

**Bug 重现步骤(有截图更好)**

https://user-images.githubusercontent.com/24768910/209497371-ce4596c3-47bb-466b-abb7-8032d5f6bda7.mov

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.0版本已处理，请更新最新版本。
