### ISSUE TITLE
[Bug][hive数据集]

### ISSUE THREAD

**Issue by wzwyoyo** [dataease/dataease#4197]
**DataEase 版本**
1.17.0

**运行方式(安装包运行 or 源码运行 ?)**

离线安装
**浏览器版本**
chrome  108.0.5359.124

**Bug 描述**
when running hive sql   meet such error 
org.apache.hive.service.cli.HiveSQLException: Error while compiling statement: FAILED: ParseException line 4:34 missing EOF at ',' near '0'

the sql in  hive  cli can run well

**Bug 重现步骤(有截图更好)**
1.
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/12044966/209520625-0c7a3437-1c85-45dc-b64a-fc91a4398401.png">

2.
3.

**Comment by BBchicken-9527** [comment]
请问你是用的hive是什么版本号是多少？

**Comment by wzwyoyo** [comment]
hive  version is  apache-hive-1.2.1U3-bin
![image](https://user-images.githubusercontent.com/12044966/209598625-5864a80b-fe84-4959-8eea-3efb0eac3060.png)
I have attempt to change the driver  ,I dont know whether the main class  "org.apache.hive.jdbc.HiveDriver"  is right
<img width="819" alt="image" src="https://user-images.githubusercontent.com/12044966/209598834-7c69fbcb-ace3-4190-8650-39a904d0eb92.png">

I meet such errors after change the dirver 
<img width="754" alt="image" src="https://user-images.githubusercontent.com/12044966/209599070-6f88ea94-e5a4-416c-afbe-4842315da728.png">

**Comment by wzwyoyo** [comment]
可以给一个怎么添加hive驱动的教程吗？我感觉问题出现在这里

**Comment by wzwyoyo** [comment]
java version "1.7.0"     dataease version v1.17.1      安装路径 是  /data/hdp-ads-antifraud/dataEase/dataease   安装配置是这些 
![image](https://user-images.githubusercontent.com/12044966/209601071-909569b6-2fdf-40ab-bfc9-59b832f5b099.png)
这些会影响吗？

**Comment by BBchicken-9527** [comment]
> 可以给一个怎么添加hive驱动的教程吗？我感觉问题出现在这里

使用admin登录数据源处添加驱动即可

**Comment by BBchicken-9527** [comment]
> hive version is apache-hive-1.2.1U3-bin ![image](https://user-images.githubusercontent.com/12044966/209598625-5864a80b-fe84-4959-8eea-3efb0eac3060.png) I have attempt to change the driver ,I dont know whether the main class "org.apache.hive.jdbc.HiveDriver" is right <img alt="image" width="819" src="https://user-images.githubusercontent.com/12044966/209598834-7c69fbcb-ace3-4190-8650-39a904d0eb92.png">
> 
> I meet such errors after change the dirver <img alt="image" width="754" src="https://user-images.githubusercontent.com/12044966/209599070-6f88ea94-e5a4-416c-afbe-4842315da728.png">

好的，我们验证一下，感谢反馈

**Comment by wzwyoyo** [comment]
这个有什么进展了吗？

**Comment by BBchicken-9527** [comment]
已经提交开发处理了请耐心等待，感谢你的支持，努力处理中；
