### ISSUE TITLE
[Bug][sql多层嵌套union all子查询+参数变量 查询出错]

### ISSUE THREAD

**Issue by acduan** [dataease/dataease#4200]
**DataEase 版本**
v1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
windows  jar包 

**浏览器版本**
Google Chrome 版本 108.0.5359.125（正式版本） （64 位）

**Bug 描述**
 1. select多层嵌套union all 子查询+参数变量，出现错误：
【net.sf.jsqlparser.statement.select.SetOperationList cannot be cast to net.sf.jsqlparser.statement.select.PlainSelect】

 2. left join 两个sql子查询分别有where 参数变量 提示：
 【SQL 变量只能在 WHERE 条件中使用】

**Bug 重现步骤(有截图更好)**
1.
![1672043441832](https://user-images.githubusercontent.com/23454389/209525953-82bc93ed-46ad-494c-b9ab-6ee3d2acb0eb.jpg)

2.
![image](https://user-images.githubusercontent.com/23454389/209526801-fb799160-7bd6-4a7c-aa08-6739d52f3e9e.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前参数化无法有效的对较为复杂的sql生效，我们会尽快完善此处功能；

**Comment by acduan** [comment]
感谢回复，期待此功能的完善！

**Comment by JunTech** [comment]
【net.sf.jsqlparser.statement.select.SetOperationList cannot be cast to net.sf.jsqlparser.statement.select.PlainSelect】

不强转类型 可以临时解决这个问题

**Comment by BBchicken-9527** [comment]
> 【net.sf.jsqlparser.statement.select.SetOperationList cannot be cast to net.sf.jsqlparser.statement.select.PlainSelect】
> 
> 不强转类型 可以临时解决这个问题
