### ISSUE TITLE
[Question] 请问SQL数据集目前是否支持可选的where clause

### ISSUE THREAD

**Issue by ysn2233** [dataease/dataease#4202]
类似于Metabase 中括号的语法 
``` sql
SELECT xxx FROM yyy WHERE 1=1 [[AND x={{x}}]]
```
如果参数x不存在，则整个中括号的语句都不在执行

**Comment by yayanpei** [comment]
感谢反馈，Dataease的SQL数据集是支持带参数的，用法与您描述的基本一致，可以尝试一下，可参考文档：https://dataease.io/docs/user_manual/dataset_configuration/dataset_SQL/#4

**Comment by ysn2233** [comment]
> 感谢反馈，Dataease的SQL数据集是支持带参数的，用法与您描述的基本一致，可以尝试一下，可参考文档：https://dataease.io/docs/user_manual/dataset_configuration/dataset_SQL/#4

你好，我指的不是参数，是可选的where语句，就是如果不传入参数，这部分的语句就不加到SQL里了。

**Comment by yayanpei** [comment]
我们目前是这么处理的，如果省份传入参数，比如广东省，那么查询的是广东省的数据；如果省份没有传入参数值，那么查询的是所有省份的数据。

> > 感谢反馈，Dataease的SQL数据集是支持带参数的，用法与您描述的基本一致，可以尝试一下，可参考文档：https://dataease.io/docs/user_manual/dataset_configuration/dataset_SQL/#4
> 
> 你好，我指的不是参数，是可选的where语句，就是如果不传入参数，这部分的语句就不加到SQL里了。
