### ISSUE TITLE
[chore] 每次项目启动会清除任务然后再添加数据集定时同步任务，会不会有点多余

### ISSUE THREAD

**Issue by JunTech** [dataease/dataease#4208]
**请描述您的需求或者改进建议.**
![69271048bff61b57ed2e50fc45d5e23](https://user-images.githubusercontent.com/54126696/209605816-a4a096da-2e22-42c4-b6c5-811fce7b64d1.png)

这里可不可以不清除任务，每次启动只是去检查是否任务存在，不存在就添加，而不是全量删除然后在全量添加

**Comment by tjlygdx** [comment]
感谢建议，我们会考虑改进的。
