### ISSUE TITLE
[Bug]在仪表板的数据集字段管理界面快速编辑多个字段名称时，第二次修改会失效

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#4227]
**DataEase 版本**
v1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 最新版

**Bug 描述**
进入仪表板的数据集字段管理界面，快速连续的修改字段名称，会发现第一次修改生效后第二次修改的内容会被重置。
详情请查看视频，连续删除两个字段的名称前三个字符，第一个修改生效，第二个字段名修改后被重置回修改前状态，需再次修改才能生效。

**Bug 重现步骤(有截图更好)**

https://user-images.githubusercontent.com/30886198/209802605-35c1d4bc-5b3b-4e5a-aee4-4bea53fa2d8f.mp4

**Comment by BBchicken-9527** [comment]
感谢反馈，测试环境没能复现你说的问题，是不是缓存原因导致的？

**Comment by xuwei-fit2cloud** [comment]
v1.18.2版本已处理，请更新相关版本。
