### ISSUE TITLE
[Bug]【视图】Tab 页签中的明细表滚动条拖动有问题

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#4228]
**DataEase 版本**
1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
普通浏览器

**Bug 描述**
Tab 页签中的明细表滚动条拖动有问题，详见视频

**Bug 重现步骤(有截图更好)**

https://user-images.githubusercontent.com/24768910/209893937-05142c24-c373-4859-9f04-d20600393b3e.mov

**Comment by AndroidBaby1** [comment]
不是普通浏览器，是标准谷歌浏览器，写错了

**Comment by BBchicken-9527** [comment]
感谢反馈，下个版本将会在此处做出部分调整，目前是不支持左右的滚动条的，同时将会放开编辑页面中视图事件；

**Comment by xuwei-fit2cloud** [comment]
v1.18.2版本已处理，请更新相关版本。

**Comment by AndroidBaby1** [comment]
好的，非常感谢！
