### ISSUE TITLE
[Bug] 柱状图标签位置为“上”时无法看到标签

### ISSUE THREAD

**Issue by fengqilantian** [dataease/dataease#4230]
**DataEase 版本**
在线演示环境

**浏览器版本**
Chrome 108.0.5359.124（正式版本） (arm64)

**Bug 描述**
柱状图启用标签展示后，将标签位置修改为“上”，此时无法看到最大的数据的标签

**Bug 重现步骤(有截图更好)**
<img width="843" alt="image" src="https://user-images.githubusercontent.com/44064179/209898386-17dbaf55-7356-4823-b51b-c3f1aa3fd792.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，确实存在此类问题，不过这属于图库资产处理导致，我们尽可能的去优化，但优化的空间可能不大，所以可能不会立即解决希望你可以理解；

**Comment by fengqilantian** [comment]
理解，这个问题并不是什么恶性bug，修复只是锦上添花。

**Comment by fengqilantian** [comment]
那么现在这个问题需要关闭吗

**Comment by BBchicken-9527** [comment]
感谢理解，我们会尽可能的完善的，那我就给你关掉了哈
