### ISSUE TITLE
[Bug]富文本视图在悬浮模式下，“选择视图字段”的按钮会消失

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4235]
**DataEase 版本**
v1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
富文本视图在悬浮模式下，“选择视图字段”的按钮会消失

**Bug 重现步骤(有截图更好)**
1.矩阵模式如下，选项是在的：
<img width="1546" alt="image" src="https://user-images.githubusercontent.com/48945409/209915325-d3096263-e1c9-429a-9312-a72184174e89.png">

2.切换为悬浮模式，刚切换后选项也还在：
<img width="1546" alt="image" src="https://user-images.githubusercontent.com/48945409/209915363-375efa23-5118-415d-a55d-28176d6480c0.png">

3.放掉对该视图的光标控制后再重新选择该视图，不再有选择字段的选项按钮。
<img width="1549" alt="image" src="https://user-images.githubusercontent.com/48945409/209915449-370cc86b-120a-4d30-bae8-fc2e4228a4da.png">

4.重新切换为矩阵模式后，按钮重新回来。
<img width="1546" alt="image" src="https://user-images.githubusercontent.com/48945409/209915499-6ab62bed-a83e-4dca-a252-842a9f696daf.png">

**Comment by luyang351** [comment]
这个确认是在文本中的。

**Comment by BBchicken-9527** [comment]
可以稳定复现吗？

**Comment by luyang351** [comment]
可以稳定复现。

**Comment by luyang351** [comment]
https://user-images.githubusercontent.com/48945409/210031251-43e10197-b003-4f7e-89e3-ae9ff8122314.mp4

**Comment by BBchicken-9527** [comment]
感谢反馈，方便私下聊一下，我看一下你的环境的情况吗

**Comment by luyang351** [comment]
可以的

**Comment by BBchicken-9527** [comment]
感谢反馈，问题新版本已修复；

**Comment by xuwei-fit2cloud** [comment]
v1.18.0版本已处理，请更新最新版本。
