### ISSUE TITLE
[Bug] 仪表板修改属性不保存，系统会自动保存

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#4251]
**DataEase 版本**
v1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
仪表板修改属性后，选择不保存，系统会自动保存

**Bug 重现步骤(有截图更好)**
1.点击“编辑仪表板”，如：修改颜色属性，点击确定
![image](https://user-images.githubusercontent.com/43403764/210057945-18395d7c-ba8c-4659-864a-dc1871e90348.png)
2.点击不保存
![image](https://user-images.githubusercontent.com/43403764/210058009-88ace49e-53b6-465a-81d5-460b53adbf5d.png)
3.仪表板颜色修改
![image](https://user-images.githubusercontent.com/43403764/210058063-d48f087b-f3b4-4ad5-8ea7-37b7fa21a6d4.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，因为一些历史原因导致视图的样式设计是独立出来的，虽然你已经设置不保存了但视图是没有办法改变的，我们会尽快优化此处功能，感谢你的支持
