### ISSUE TITLE
[Bug]文本下拉组件，修改字体大小时，按删除键字体大小会变成12

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#4252]
**DataEase 版本**
v1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
文本下拉组件，修改组件标题字体大小时，按键盘删除键字体大小自动变成12

**Bug 重现步骤(有截图更好)**
1.修改组件标题字体大小
![image](https://user-images.githubusercontent.com/43403764/210073144-7832bcb0-60d1-466e-89cd-d3e32c4ebb78.png)
2.按键盘删除键，自动变成 12
![image](https://user-images.githubusercontent.com/43403764/210073222-8cb9211e-2b4e-4c30-8632-f444a34d67b1.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，此处为组件行为，可调优空间较低，我们开会讨论一下有没有什么方案可以解决此问题。
