### ISSUE TITLE
[Feature]在用户集中修改字段名称

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#4253]
**请描述您的需求或者改进建议.**
需求：在数据集中修改字段名称后，编辑仪表板中的视图，“视图”-“结果展示”对应的维度和指标字段名称不会更新，需要重新进行拖拉拽。
建议：数据集中修改字段名称后，仪表板视图中的展示结果的对应字段可以自动更新为数据集中修改字段名称。

**Comment by yayanpei** [comment]
感谢反馈，在数据集字段更新后，后台需要刷新存量的视图，我们需要进行讨论一下。
