### ISSUE TITLE
[Bug] install.sh脚本

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4254]
**DataEase 版本**
略

**运行方式(安装包运行 or 源码运行 ?)**
略

**浏览器版本**
略

**Bug 描述**
执行脚本时，防火墙端口开放端口写死了
<img width="516" alt="image" src="https://user-images.githubusercontent.com/45852479/210296658-d63edbbc-003f-444b-ad73-e549203f75ec.png">

**Bug 重现步骤(有截图更好)**

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快优化

**Comment by xuwei-fit2cloud** [comment]
v1.18.0版本已处理，请更新最新版本。
