### ISSUE TITLE
[Bug]仪表板无法导出PDF

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#4258]
**DataEase 版本**
v 1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
仪表板公共链接无法导出PDF文件，点击“下载”按钮后的预览页面是空白的，导出后的PDF也是空白的

**Bug 重现步骤(有截图更好)**
1.请使用附件中的模板复现
2.
3.
![image](https://user-images.githubusercontent.com/40846859/210318330-ab18fb5c-f04b-4ff8-b987-d13c26740ce7.png)

[1.重要信息概览-TEMPLATE(1).zip](https://github.com/dataease/dataease/files/10334931/1.-TEMPLATE.1.zip)

**Comment by BBchicken-9527** [comment]
感谢反馈，排查后确认应该是仪表板存在一些多余内容导致，删除多余文本内容应该就可以正常导出了；
