### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by kukule75** [dataease/dataease#4260]
**请描述您的需求或者改进建议.**
**需求背景：** 目前有个需求，动态传递时间参数获取销售报表，获取商品名称、销量、实付金额、单价
<img width="534" alt="image" src="https://user-images.githubusercontent.com/19264463/210328384-633b78b0-4e72-497b-bef0-baf2c4cd8887.png">

<img width="710" alt="image" src="https://user-images.githubusercontent.com/19264463/210325399-b9fc5233-b23a-436b-bec4-19ace19f4cb7.png">
**sql如下：**
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/19264463/210325225-4ed9358e-e894-4184-b933-a5e7e7d22bbe.png">

此功能无法实现，因为时间字段不能移到最外层的where上；另外就算能移出来，sql本书需要扫描处理的数据量就太大了。
根据日期分析报表数据是很常见的需求，请考虑迭代此需求，支持复杂情况下的动态sql传参。

**Comment by yayanpei** [comment]
感谢您的反馈，此需求已经在需求池中，后期会根据需求的优先级排期优化的。
