### ISSUE TITLE
[Bug]echart地图数据为零不显示

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4268]
**DataEase 版本**
1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome

**Bug 描述**
echart地图对数据为零的不显示

**Bug 重现步骤(有截图更好)**
1. 准备数据
<img width="754" alt="图片" src="https://user-images.githubusercontent.com/48307752/210482907-b58b0c71-2f9c-40b5-ab55-d70fc211f63d.png">

3.echart 地图展示数据
<img width="884" alt="图片" src="https://user-images.githubusercontent.com/48307752/210482984-a1a5155a-dcd2-4afc-b39c-7c98718ba6fa.png">

4. 可以看到，数据为0 的省份，标签和提示 均没有数据。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快优化

**Comment by xuwei-fit2cloud** [comment]
v1.18.2版本已处理，请更新相关版本。
