### ISSUE TITLE
[Bug] PostgreSQL 的动态传参脚本内含有 row_to_json 函数出错

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4270]
**DataEase 版本**
1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 重现步骤(有截图更好)**
1.SQL脚本如下：SELECT order_id,nsrsbh,row_to_json(t.*) from tb_zbsl_lr_jc t  where order_id  = '${1}'

报错信息如下：Encountered unexpected token: "(" "(" at line 1, column 35. Was expecting one of: "&" "::" ";" "<<" ">>" "ACTION" "ACTIVE" "ALGORITHM" "ARCHIVE" "ARRAY" "AS" "AT" "BYTE" "CASCADE" "CASE" "CAST" "CHANGE" "CHAR" "CHARACTER" "CHECKPOINT" "COLLATE" "COLUMN" "COLUMNS" "COMMENT" "COMMIT" "CONNECT" "COSTS" "CYCLE" "DBA_RECYCLEBIN" "DESC" "DESCRIBE" "DISABLE" "DISCONNECT" "DIV" "DO" "DUMP" "DUPLICATE" "ENABLE" "END" "EXCLUDE" "EXTRACT

![image](https://user-images.githubusercontent.com/82353425/210490701-f17331f7-c2ad-40d6-9ce6-aa0fdaedd2bd.png)

2.去掉动态传参是正常的。
![image](https://user-images.githubusercontent.com/82353425/210490777-02a88d83-c98a-4c66-b5d4-ebdb1ef85a62.png)

3.而且将动态传参的 “${}“ 改成 “${]“  也是正常的。
![image](https://user-images.githubusercontent.com/82353425/210490857-cf38191c-6c00-4e4d-bafd-843c8794c3ae.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by stdnt-xiao** [comment]
错误任然存在，请问有准备修复？
