### ISSUE TITLE
[Question] frontend在npm run serve 时遇到的问题

### ISSUE THREAD

**Issue by qq670176019** [dataease/dataease#4272]
**请描述您的问题.**各位大家好，请问各位在运行frontend时，有没有遇到以下问题：
![3c25b342fe1f4c5dfe5dfbc6cfd118a](https://user-images.githubusercontent.com/35839281/210494507-ab9c0f3d-1b2b-469c-9c14-f434f48cff5c.png)
根据提示，定位到下方代码：
![38b6fe46712c2249f57624a55bb2ef4](https://user-images.githubusercontent.com/35839281/210494529-e925e54f-ac1e-4fc6-9a48-56bc845fc8ef.png)

问题尝试：
搜索了一下，有的说是copy-webpack-plugin版本问题，尝试换了多个版本，有的版本并不能解决问题，有的版本则会改变报错问题。

各位有遇到这种问题的请帮忙指正一下，不胜感激！

**Comment by dataeaseShu** [comment]
本地未复现，提供几个可能的解决方案 1.  清除node_modules 安装包 包缓存也清下  升级node到v16.15.0
2. 修改配置 （https://www.npmjs.com/package/copy-webpack-plugin）   
new CopyWebpackPlugin({
            patterns: [
                {
          from: path.join(__dirname, 'static'),
          to: path.join(__dirname, 'dist/static')
        }
            ],
        }),

**Comment by qq670176019** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件我已经收到，尽快给您回复。

**Comment by qq670176019** [comment]
> 

谢谢大佬的耐心解答，我试一下
