### ISSUE TITLE
[Bug]通过ifream 将仪表板嵌入到其他系统后，下拉树的大小会变大

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4273]
**DataEase 版本**
1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
仪表板的外部公共链接，通过ifream 嵌入到其他系统后，下拉树的大小会变大，但是其他的是筛选组件不会发生变化；
下图是嵌入其他系统的界面，红框内是下拉树组件变高了。
<img width="817" alt="图片" src="https://user-images.githubusercontent.com/48307752/210496084-4483d47d-7b88-4ca3-9821-c78bc09c9303.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，方便的话私下聊一下
