### ISSUE TITLE
[Bug]组件设置位置后再复制有一定概率复制不出来

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4279]
**DataEase 版本**
v1.17.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
**悬浮模式下**，给组件做位置信息调整后，再点击复制，没有新的组件被复制出来，一定概率下会出现，暂时还未测出必现的条件。

**Bug 重现步骤(有截图更好)**
1.比如仪表板中的一个图片组件。
![image](https://user-images.githubusercontent.com/48945409/210512062-20ce5fe5-dddb-4317-9446-25e117e83994.png)

2.点击复制，可以正常复制。
![image](https://user-images.githubusercontent.com/48945409/210512153-d59dc91a-8ef6-4f42-a2a8-c34fc4cae625.png)

3.给新复制的图片组件做位置调整，上、左、宽、高可以随便乱调一些。
![image](https://user-images.githubusercontent.com/48945409/210512426-4e721837-ba8b-4e0d-a394-d6b7526caf55.png)

4.对调整完的视图点击复制。
![image](https://user-images.githubusercontent.com/48945409/210512556-c05247e7-dacb-4c77-8a0c-2a304ffa8b59.png)

5.界面闪了一下后并没有新的组件被复制出来。
![image](https://user-images.githubusercontent.com/48945409/210512646-3cb37f18-c418-45f5-a5a4-bcde6673a16f.png)

**操作视频：**
https://user-images.githubusercontent.com/48945409/210512821-d5aee6ad-91a7-4c3a-81dc-4cd94ddf4e21.mp4

**Comment by BBchicken-9527** [comment]
感谢反馈，其实是复制出来了，只不过是在仪表板的最下面，我们优化一下

**Comment by BBchicken-9527** [comment]
问题已修复到时可更新体验，感谢你的反馈与支持

**Comment by xuwei-fit2cloud** [comment]
v1.18.2版本已处理，请更新相关版本。
