### ISSUE TITLE
[Bug] 有长字段的excel数据集导入失败

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4282]
**DataEase 版本**
v1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
simple模式下 有长字段的excel数据集导入失败

**Bug 重现步骤(有截图更好)**
![wecom-temp-13612-891269a82c422ce39fc07b3bb012bbeb](https://user-images.githubusercontent.com/45852479/210520591-7b1432a2-151d-45d1-a036-c762713f23ec.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，方便问一下是多少个字符的长文本吗，还有长文本是字段名称长文本还是字段内容呢

**Comment by BBchicken-9527** [comment]
感谢反馈，我们修复一下
