### ISSUE TITLE
[Bug] 大小写导致指标和维度无法切换

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4283]
**DataEase 版本**
v1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
大小写导致指标和维度无法切换

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/45852479/210520810-265c4110-341a-4da8-8a36-8100b4f326a3.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
