### ISSUE TITLE
[Bug] join子查询下的sql变量无法识别的问题

### ISSUE THREAD

**Issue by OlderBabyML** [dataease/dataease#4284]
**DataEase 版本**
dev

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
版本 108.0.5359.125（正式版本） （64 位）

**Bug 描述**
无法识别到join子查询里面的where条件

**Bug 重现步骤(有截图更好)**
![img_v2_a4f6e0ab-5249-4bba-99a9-0f153406669g](https://user-images.githubusercontent.com/50657209/210521015-b5c91879-fd91-45a5-8956-a24d5a33fd74.jpg)

1.如下sql，会报图上的只能在where条件中使用
select region, month, sum(new_vj) as new_vj
from 
(select 
    country,
    replace(substr(create_time,1,7),'-','') as month,
    count(distinct uid) as new_vj
from waka.ods_vj_signed_record
where dt = '${end_date}'
and substr(create_time,1,10) >= '2022-01-01'
and verified = 1
and is_delete = 0
group by country,replace(substr(create_time,1,7),'-','')
)a
left join(
select distinct country_code, region
from waka.dim_country_region_mapping
where dt = '${end_date}'
)b on a.country = b.country_code
where region in ('MECA','TR','FR','TH','ID','MY','VN','KH','US','IN','PK','TW','JP','KR')
group by region,month

**Comment by OlderBabyML** [comment]
解决方案 https://github.com/dataease/dataease/pull/4285

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快优化此处内容
