### ISSUE TITLE
[Bug] ck22.4.5.9 数据格式切换保留两位没有生效

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4286]
**DataEase 版本**
v1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
ck22.4.5.9 数据格式切换保留两位没有生效

**Bug 重现步骤(有截图更好)**
![wecom-temp-111766-1cd21258e3cff1f250dd983722701205](https://user-images.githubusercontent.com/45852479/210522239-ccf2096a-d71a-4cf1-b5d0-4ce93714b27c.png)

**Comment by BBchicken-9527** [comment]
目前数据格式为前端行为，与数据源无关，因为js净度问题导致此问题，我们将会持续进行优化；感谢你的支持与反馈
