### ISSUE TITLE
[Bug]复用模板时，编辑过滤组件无法选择表

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4290]
**DataEase 版本**
v1.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 108.0.5359.98（正式版本） (x86_64)

**Bug 描述**
见截图
![bug](https://user-images.githubusercontent.com/89771514/210528560-9a42f165-ada8-483a-aaf0-416befd811a5.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试测试环境上没有发现你说的问题呢，建议升级一下最新版本看看

**Comment by ZhaoQian1222** [comment]
可能是跟数据集权限有关，用新版本v1.18测试也有同样的问题，步骤：
1、新建仪表板——>复用模板——>选择系统模板中的“某运动品牌销售看板”
2、编辑看板右上角的部门、产品下拉框，此时就会发现按表选择的数据列表为空

**Comment by BBchicken-9527** [comment]
好的，我们验证一下
