### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by huzi068** [dataease/dataease#4296]
图片中的这个线,通过自己在数据库表的配置,然后动态的生成,蓝色箭头中的数据也是通过这个线超过的部分进行动态生成,这个线就是一个单独的数据集,和数据没直接的关联关系,这得考虑到两个数据集在一个视图里面的操作
https://user-images.githubusercontent.com/120470741/210711959-93dc89d9-b1f4-460e-b809-ce118783a62e.jpg

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。
