### ISSUE TITLE
[Bug]添加不同过滤条件并设置为无限制，会出现不同的结果

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#43]
**DataEase 版本**
v1.0.0-rc2
**浏览器版本**
Chrome 91.0.4472.114（正式版本） (arm64)
**Bug 描述**
编辑视图，加结果过滤器，条件设置为“等于+无限制”或“小于+无限制”时，数据全被过滤掉了。但是条件改为“大于+无限制”则数据未被过滤，全部都在。

**Bug 重现步骤(有截图更好)**
1.选择一个视图->添加结果过滤器->添加过滤；
2.过滤设置为“大于+无限制”后确认；
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/48945409/123412355-15cdca00-d5e4-11eb-96c5-312553d4a91b.png">
3.图表与未加过滤时一致，仍然是全部数据；
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/48945409/123413427-5a0d9a00-d5e5-11eb-99d8-b8f70f1dba7f.png">
4.重新调整过滤条件为“小于+无限制”并确认
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/48945409/123413498-70b3f100-d5e5-11eb-9a0e-f9af7574934c.png">
5.图表数据变为空
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/48945409/123413559-82959400-d5e5-11eb-87ec-6530eb7ed2ef.png">

**Comment by xuwei-fit2cloud** [comment]
收到您的反馈，我们下一个小版本 v1.0.2 中修复

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已支持
