### ISSUE TITLE
[Bug]当指标或维度过多时，使用富文本视图选择参数，参数超过一屏显示不全

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4300]
**DataEase 版本**
v1.18.0

**运行方式(安装包运行 or 源码运行 ?)**
安装部运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
当指标或维度过多时，使用富文本视图选择参数，参数超过了一屏导致显示不全，建议增加滚动条。
![image](https://user-images.githubusercontent.com/48945409/210737943-0b985a26-ea38-49d6-a899-5c63d4466155.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快优化

**Comment by xuwei-fit2cloud** [comment]
v1.18.2版本已处理，请更新相关版本。
