### ISSUE TITLE
[Bug] 公共链接打开 tab 页里的下拉框，下拉框有两页的内容的时候无法拖动

### ISSUE THREAD

**Issue by mayjiang0203** [dataease/dataease#4305]
**DataEase 版本**
1.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
下拉条框向下拖动又会被弹回来，编辑页面没有这个问题，公共链接会有这个问题。

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/9443637/210918055-42a15cc7-ee3d-48c9-a137-780cdd6e546a.png)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，会不会是缓存原因造成，目前环境中没发现你说的问题
![image](https://user-images.githubusercontent.com/84372766/210948138-e4caec7f-f23d-4a7d-ba29-9a5c48e7a0fa.png)
