### ISSUE TITLE
[Bug] 数据集关联 不区分字符大小写

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4310]
**DataEase 版本**
v1.18.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
数据集关联 不区分字符大小写

**Bug 重现步骤(有截图更好)**
![企业微信截图_16729943956449](https://user-images.githubusercontent.com/45852479/210991545-eb27f9a3-b37c-4fcf-8810-a0b5e8e683e7.png)
![企业微信截图_1672994432627](https://user-images.githubusercontent.com/45852479/210991598-6c28c5e3-67f2-429f-897c-b4a9a4d6dcc8.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
