### ISSUE TITLE
[Bug] 修改数据源时，若没有做改动直接保存没法保存

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4312]
**DataEase 版本**
v1.18.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
修改数据源时，若没有做改动直接保存没法保存

**Bug 重现步骤(有截图更好)**
编辑数据源-保存-报错
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/45852479/211128597-15653bd1-0c3f-4a74-a1de-df9ff65e083a.png">

**Comment by BBchicken-9527** [comment]
问题为已知问题，目前我们正在努力修改，感谢你的反馈与支持

**Comment by xuwei-fit2cloud** [comment]
v1.18.2版本已处理，请更新相关版本。
