### ISSUE TITLE
[Bug]导入excel文件后保存，却无法预览

### ISSUE THREAD

**Issue by klzdy123** [dataease/dataease#4313]
**DataEase 版本**
v1.18.0

**运行方式(安装包运行 or 源码运行 ?)**
在线安装方式，docker启动

**浏览器版本**

**Bug 描述**
导入excel文件后保存，却无法预览

**Bug 重现步骤(有截图更好)**
1.数据集创建新文件夹
2.使用excel导入数据集
3.返回到数据预览窗会报错

excel数据如下
![截屏2023-01-08 11 58 48](https://user-images.githubusercontent.com/24836285/211179835-41c5bcbf-4ea2-4705-a4b2-c860d3780bb3.png)
报错如下
![截屏2023-01-08 11
![截屏2023-01-08 11 50 23](https://user-images.githubusercontent.com/24836285/211179840-ec6c4714-9710-4b98-bb9f-ff8c328be252.png)
 53 21](https://user-images.githubusercontent.com/24836285/211179839-562bb751-28cf-4108-9641-838d1a8bd653.png)

**Comment by klzdy123** [comment]
![截屏2023-01-08 11 50 23](https://user-images.githubusercontent.com/24836285/211179881-8d9f3a07-3135-47a3-9256-10e43aea8368.png)

**Comment by klzdy123** [comment]
目前在 Centos 7.9 系统里操作是会报错的，但在 Ubuntu 22.04 的主机上却可以

**Comment by BBchicken-9527** [comment]
感谢反馈，嗯...你看centos7.9服务doris是否有在工作呢

**Comment by klzdy123** [comment]
![截屏2023-01-09 10 51 25](https://user-images.githubusercontent.com/24836285/211234081-d163b513-6067-4084-86b3-58eacfc5985b.png)
![截屏2023-01-09 10 52 29](https://user-images.githubusercontent.com/24836285/211234089-09dbd1d2-59fc-41a8-bfe6-c693fb4f2666.png)
![截屏2023-01-09 10 52 39](https://user-images.githubusercontent.com/24836285/211234095-43ade103-fa03-4019-b722-f2f098ec0f4a.png)
目前来看，docker容器是跑起来了

**Comment by BBchicken-9527** [comment]
嗯... 我们这边测试环境没有发现你的这种情况，一般这种异常是因为连接不到数据服务器所给的提示，这个问题在你的环境中是否可以稳定复现呢？

**Comment by klzdy123** [comment]
17 和 18 在这台主机上都是一样的问题

**Comment by BBchicken-9527** [comment]
嗯... 受累你看看更新记录，那里应该上传是失败的，你看看异常信息提示的是什么

**Comment by BBchicken-9527** [comment]
对了问一下你选择的是什么模式？是本地模式吗

**Comment by klzdy123** [comment]
![截屏2023-01-09 18 51 46](https://user-images.githubusercontent.com/24836285/211291641-3a4c99cf-12df-4384-9286-90dde170f1b6.png)
模式为：local

**Comment by BBchicken-9527** [comment]
你之前修改过模式吗？

**Comment by klzdy123** [comment]
之前系统下下来默认是simple，手动改成 local 后安装的，期间还修改了docker 容器的端口，80接口也调整了一下

**Comment by BBchicken-9527** [comment]
你删除一下dataease容器试一下

**Comment by klzdy123** [comment]
刚刚切换 simple 模式安装后，导入Excel文件，时间格式变成这样，无法使用
![截屏2023-01-11 10 18 21](https://user-images.githubusercontent.com/24836285/211702705-59a13915-6174-4e64-bdd0-a2b8bc12bbe3.png)

**Comment by klzdy123** [comment]
![截屏2023-01-13 10 36 39](https://user-images.githubusercontent.com/24836285/212224267-ce12f495-e590-45cc-9306-67e3f8cd7ea5.png)
v1.18.1
导入excel数据全部默认为 时间类型？？

**Comment by BBchicken-9527** [comment]
实在抱歉，因为受到Excel时间格式类型的多样化影响，目前格式类型识别上确实存在不小的误差，我们也在努力的去完善此处的功能，你可以通过手动调整字段类型格式作为临时的解决方案，我们也回在后续的版本迭代中升级此处的功能；
