### ISSUE TITLE
[Bug]ES 数据库， 新建数据库数据集， 只要表名含有- ， 出现预览数据失败

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [dataease/dataease#4315]
**DataEase 版本**
1.17.1

**运行方式(安装包运行 or 源码运行 ?)**

安装包

**浏览器版本**
谷歌浏览器

**Bug 描述**
ES 数据库版本 7.9.1， 连接正常。 新建数据库数据集， 只要表名含有- ， 出现预览数据失败，报错日志如下。其他的数据库表是正常的。
2023-01-03 11:19:01,025 [http-nio-8081-exec-32] ERROR i.d.c.handler.GlobalExceptionHandler ? - Fail to proceed /dataset/table/dbPreview
io.dataease.exception.DataEaseException: java.lang.RuntimeException: HttpClient查询失败: {"error":{"root_cause":[{"type":"parsing_exception","reason":"line 1:36: mismatched input '-' expecting {')', ',', 'ANALYZE', 'ANALYZED', 'AS', 'CATALOGS', 'COLUMNS', 'CURRENT_DATE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'DAY', 'DEBUG', 'EXECUTABLE', 'EXPLAIN', 'FIRST', 'FORMAT', 'FULL', 'FUNCTIONS', 'GRAPHVIZ', 'GROUP', 'HAVING', 'HOUR', 'INNER', 'INTERVAL', 'JOIN', 'LAST', 'LEFT', 'LIMIT', 'MAPPED', 'MINUTE', 'MONTH', 'NATURAL', 'OPTIMIZED', 'ORDER', 'PARSED', 'PHYSICAL', 'PIVOT', 'PLAN', 'RIGHT', 'RLIKE', 'QUERY', 'SCHEMAS', 'SECOND', 'SHOW', 'SYS', 'TABLES', 'TEXT', 'TOP', 'TYPE', 'TYPES', 'VERIFY', 'WHERE', 'YEAR', LIMIT_ESC, IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}"}],"type":"parsing_exception","reason":"line 1:36: mismatched input '-' expecting {')', ',', 'ANALYZE', 'ANALYZED', 'AS', 'CATALOGS', 'COLUMNS', 'CURRENT_DATE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'DAY', 'DEBUG', 'EXECUTABLE', 'EXPLAIN', 'FIRST', 'FORMAT', 'FULL', 'FUNCTIONS', 'GRAPHVIZ', 'GROUP', 'HAVING', 'HOUR', 'INNER', 'INTERVAL', 'JOIN', 'LAST', 'LEFT', 'LIMIT', 'MAPPED', 'MINUTE', 'MONTH', 'NATURAL', 'OPTIMIZED', 'ORDER', 'PARSED', 'PHYSICAL', 'PIVOT', 'PLAN', 'RIGHT', 'RLIKE', 'QUERY', 'SCHEMAS', 'SECOND', 'SHOW', 'SYS', 'TABLES', 'TEXT', 'TOP', 'TYPE', 'TYPES', 'VERIFY', 'WHERE', 'YEAR', LIMIT_ESC, IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}","caused_by":{"type":"input_mismatch_exception","reason":null}},"status":400}

**Bug 重现步骤(有截图更好)**
1. 表名含有 - ， 预览数据失败的截图
<img width="1767" alt="image" src="https://user-images.githubusercontent.com/30264974/211233837-2acd7e1e-846a-406d-b46d-e748028b920b.png">

2. 表名不含 -， 预览数据成功
<img width="1870" alt="image" src="https://user-images.githubusercontent.com/30264974/211234093-1dd0ab68-992a-4158-ab8a-174cb51646f4.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
