### ISSUE TITLE
[Bug]数据集中存在空字段，在视图中导出 Excel 报空指针异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4333]
**DataEase 版本**
1.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 108.0.5359.98（正式版本） (x86_64)

**Bug 描述**
使用MySQL数据源，使用的数据库数据集，数据集中存在空字段，在明细表视图中使用这个数据集，视图导出 Excel 报空指针异常，数据集中导出 Excel 没有问题

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/89771514/211448988-0fa98561-6b4f-4e18-b9dd-73a9f8f1a478.png)
![image](https://user-images.githubusercontent.com/89771514/211449092-e89faa69-b324-47b8-820d-de16f8724149.png)
![WechatIMG378](https://user-images.githubusercontent.com/89771514/211449237-9b6f5b64-7da3-441c-a531-e327e7b6b725.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题已修复，将在小版本中发布

**Comment by xuwei-fit2cloud** [comment]
v1.18.2版本已处理，请更新相关版本。
