### ISSUE TITLE
[Bug] 企业版的列权限自定义功能不可用

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4334]
**DataEase 版本**
1.18.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.如图点击“自定义”一直弹不出窗口
![image](https://user-images.githubusercontent.com/82353425/211453568-591aa581-406a-4b16-aa56-04a0b13900b8.png)
2.假如多点几次“自定义”，页面就会卡住导致关不掉右边的选择框。
3.重复点击“自定义”与其他脱敏，回到相应的数据集就会报错了。
![image](https://user-images.githubusercontent.com/82353425/211453877-4d029c1f-271c-4cb7-b6c2-2e313e91a1bb.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前系统管理-权限管理中配置列权限的入口存在问题，可先在数据集页面设置列权限作为临时解决方案，我们正在努力修复

**Comment by fit2cloudrd** [comment]
请升级到v1.18.1版本。
