### ISSUE TITLE
[Bug] 仪表板制作页面 使用‘撤销’操作后 视图的操作列表消失

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4335]
**DataEase 版本**
v1.18.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
仪表板制作页面 使用‘撤销’操作后 视图的操作列表消失

**Bug 重现步骤(有截图更好)**
1.操作仪表板，使用‘撤销’操作
2.预期
<img width="340" alt="image" src="https://user-images.githubusercontent.com/45852479/211468474-6c478d93-4351-4cfe-a33d-4cc820fb739a.png">
实际
<img width="342" alt="image" src="https://user-images.githubusercontent.com/45852479/211468379-839a102a-fa34-44d3-b2cf-c61a609e1b2d.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
请更新到v1.18.1版本。
