### ISSUE TITLE
[Feature] 仪表板搜索能否支持模糊查询呢

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4347]
**请描述您的需求或者改进建议.**
如图所示：
![image](https://user-images.githubusercontent.com/82353425/211738935-22ee03aa-e8c1-4513-a052-8087b13905ed.png)
![image](https://user-images.githubusercontent.com/82353425/211738971-0e0433be-4bc5-41ec-9796-bf6bff07e525.png)

**Comment by xuwei-fit2cloud** [comment]
模糊查询是支持的，这个需求应该是希望查询时忽略英文大小写吧？我们记录一下先。

**Comment by ywhfzy** [comment]
好嘞好嘞，嗯嗯，是忽略大小写

**Comment by xuwei-fit2cloud** [comment]
近期版本将支持。

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
