### ISSUE TITLE
[Feature]整合分享与公共链接功能

### ISSUE THREAD

**Issue by wan92hen** [dataease/dataease#4350]
**请描述您的需求或者改进建议.**

将目前的分享与创建公共链接功能整合为一个分享功能，在分享界面既可以分享给指定组织、用户及角色，也可以开启匿名访问并支持配置密码保护。

同时支持复制统一的访问链接，无论仪表盘配置的分享方式如何，登录用户及匿名用户均可通过该链接访问仪表盘（有权限时）。

在 #1132 中提到的复制 iframe 代码也统一整合在该页面。

参考腾讯文档及 Office365 分享功能。
![image](https://user-images.githubusercontent.com/27671436/211747970-3658c879-7860-4e22-91b9-1a4e0fc26aed.png)
![image](https://user-images.githubusercontent.com/27671436/211748209-ad4b6c68-34ce-4f79-9954-2ec68e6d85ca.png)

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。

**Comment by gwdgithubnom** [comment]
@xuwei-fit2cloud @yayanpei-fit2cloud 现在最新的分享访问的链接，最新版本支持iframe标签么？
