### ISSUE TITLE
[Feature]图表点击详情弹出的数据，没法显示千分位

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#4364]
**请描述您的需求或者改进建议.**
点击图表弹出数据后，建议根据数值格式设置的数据展示，或者支持仪表板增加一个设置项，设置弹出详情的数值格式，当前是直接展示元数据，也没有千分位分割，建议增加。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前数值格式是在图库的接口中实现的。视图详情的数值格式需要额外处理，这个我们先记录一下。

**Comment by xiebei-l** [comment]
> 感谢反馈，目前数值格式是在图库的接口中实现的。视图详情的数值格式需要额外处理，这个我们先记录一下。

好的，谢谢
