### ISSUE TITLE
[Feature]Antv 明细表指标中空值为0的修复

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4371]
**请描述您的需求或者改进建议.**
antv 明细表 指标中空值为0的状态，能不能与echart的明细表一样，空值为空单元格

<img width="887" alt="图片" src="https://user-images.githubusercontent.com/48307752/212286981-0af7742f-16d3-4d5d-a85e-48895135f736.png">

**Comment by yayanpei** [comment]
感谢反馈，空值的处理前面版本进行过优化：antv的明细表，如果为空值，显示的为“-”。建议您升级到1.18版本。

**Comment by mfanoffice** [comment]
您好，是我没有描述清楚，当前版本是1.18.0，指标如果是文本类型，会显示0，如果是数值类型是 “-”。

**Comment by yayanpei** [comment]
建议您检查一下数据集，我这边试了，如果数据集中文本字段的值是空的情况下，antv的明细表显示的为“-”

<img width="716" alt="image" src="https://user-images.githubusercontent.com/84168063/215375324-d2384651-a0d4-4d42-83fd-a327c7d25ef9.png">

<img width="414" alt="image" src="https://user-images.githubusercontent.com/84168063/215375269-78e02a02-ca1b-4596-b417-4000b3b7738d.png">
