### ISSUE TITLE
[Bug]词云图视图框的大小调整后，词条分布不均匀

### ISSUE THREAD

**Issue by lyons-hz** [dataease/dataease#4372]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
词云图视图框的大小调整后，词条分布不均匀
**Bug 重现步骤(有截图更好)**
图例：词云图
1.编辑界面已经调整OK
<img width="404" alt="image" src="https://user-images.githubusercontent.com/89773363/212287651-c5fc577c-1b57-4fa3-9c4e-ded0d91ac45d.png">

2.全屏展示后，词条分布不均匀，影响视觉
<img width="443" alt="image" src="https://user-images.githubusercontent.com/89773363/212287816-2ab619e9-2a9c-4d65-bacc-b242fed09eca.png">

**Comment by BBchicken-9527** [comment]
嗯... 感谢反馈，目前词云图数据的展示是图表内部计算行为，我们可操控的空间较少，我这边记录一下下次会议看看有什么好的方式可以解决这种问题
