### ISSUE TITLE
仪表板视图编辑时 数据能否先不全部加载

### ISSUE THREAD

**Issue by AccelWhite** [dataease/dataease#4374]
直连数据集情况下，编辑模式，如果数据非常多的情况下，无法创建新的视图了，服务器cpu直接跑满且容器当机，建议编辑模式数据就算选了全部数据也只显示100行左右，影响服务器性能。

**Comment by yayanpei** [comment]
感谢反馈，我们考虑后还是倾向于所见即所得，即用户选择展示多少条，视图展示多少条。如果数据量大造成当机，建议您不要选择展示全部数据，选择展示100条。

**Comment by AccelWhite** [comment]
如果确实要显示全部数据的时候进程会卡死 尤其是多个视图的时候

**Comment by AccelWhite** [comment]
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                             18082 root      20   0 4363148   1.9g  13764 S  2208  3.0  16:36.92 java
