### ISSUE TITLE
[Bug] 地图文件上传之后，缺少删除按钮

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4376]
**DataEase 版本**
1.18.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 重现步骤(有截图更好)**
1.如图所示，缺少了删除按钮。
![b4fde8c5-d853-4cc3-9ae3-9fa490505bef](https://user-images.githubusercontent.com/82353425/212582814-fe5410d1-0e44-4a71-9f25-a9a2959c7f24.png)
![95c38937-7604-4b9c-a708-9b9a641f8b73](https://user-images.githubusercontent.com/82353425/212582824-2eafa687-9a44-4184-aed0-d28d49e94d69.png)
![ad365550-c6dc-4460-ab89-db51dbf37b4a](https://user-images.githubusercontent.com/82353425/212582833-0827decf-0687-43e3-b43c-7528331081fe.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前设计是允许更新自定义地图的，所以界面上是不存在删除的按钮标识，你的诉求我也记录下来了，将会在下次开会讨论是否添加删除的相关标识
