### ISSUE TITLE
[Bug] 日期范围组件的开始结束时间参数重复出现

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4377]
**DataEase 版本**
1.18.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.如图所示，当重复点击“开始”与“结束”的时候，就会重新出现SQL动态传参的参数
![image](https://user-images.githubusercontent.com/82353425/212583749-350b3da0-15eb-4987-aa05-5ea755811f4c.png)
![image](https://user-images.githubusercontent.com/82353425/212583781-6a132bd3-ee5d-4d9c-94e9-bd20ff1e5fdd.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，此处有一个小优化，我们处理一下

**Comment by BBchicken-9527** [comment]
问题已修复，将会在下个小版本中发布，感谢你的反馈与支持！

**Comment by xuwei-fit2cloud** [comment]
v1.18.2版本已处理，请更新相关版本。
