### ISSUE TITLE
[Bug] pgsql 的unnest函数无法与动态传参一块使用

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4378]
**DataEase 版本**
1.18.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 重现步骤(有截图更好)**
1.如图所示：select '张三' as name, unnest(Array['语文','数学','英语']) as course from wzl_test where name = '${1}'
![image](https://user-images.githubusercontent.com/82353425/212590911-9c637651-15b8-4aa1-9842-c89bfcc5d6e1.png)

2. 应该是跟之前的 row_to_json 函数一样的报错。

**Comment by BBchicken-9527** [comment]
感谢感喟，目前测试环境没有发现此类问题，能否详细说明一下具体的步骤与服务，如PG版本等

**Comment by ywhfzy** [comment]
PostgreSQL 14.1

**Comment by BBchicken-9527** [comment]
好的，应该是中文导致的，我们处理一下，感谢反馈

**Comment by xuwei-fit2cloud** [comment]
v1.18.2版本已处理，请更新相关版本。
