### ISSUE TITLE
[Bug]过滤组件与查询按钮匹配存在问题

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4379]
**DataEase 版本**
1.18.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
叉掉过滤组件的默认值， 点 “查询按钮”  过滤结果没有变化 

**Bug 重现步骤(有截图更好)**
1.仪表板添加任意视图、任意过滤组件、查询按钮，过滤组件设置默认值；
<img width="1198" alt="图片" src="https://user-images.githubusercontent.com/48307752/212591393-9e0f6f92-13d2-4505-9135-661f7001118e.png">

2. 在仪表板预览界面，叉掉默认值，点击“查询”按钮，这时应该出现全部数据，但明细表没有出现全部数据。
<img width="1210" alt="图片" src="https://user-images.githubusercontent.com/48307752/212592326-d77599a9-204d-42a4-905b-e330eb9423ec.png">
3. 此时随便选择一个过滤值，点查询，会生效；然后叉掉筛选框的值，点查询，就可以显示全部数据了。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复。

**Comment by BBchicken-9527** [comment]
目前问题已修复，将会在下个版本发布，到时可下载体验，感谢你的反馈与支持

**Comment by xuwei-fit2cloud** [comment]
v1.18.2版本已处理，请更新相关版本。
