### ISSUE TITLE
[Feature] 将图表分离为单独的功能，供其他看板去选择

### ISSUE THREAD

**Issue by JunTech** [dataease/dataease#4384]
将图表分离为单独的功能，然后其他看板在创建的时候可以通过选择图表来制作看板，和图表复用功能有点相似

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，在DataEase早起版本中视图是独立的功能，也是支持复用的。
我们从多个版本的迭代反馈来看，复用视图的场景还是比较少的，为了优化仪表板制作流程，我们从v1.8.0，将视图合并到了仪表板内。短期来看，我们暂时还不会恢复成以前的设计。
