### ISSUE TITLE
[Bug]明细表不开启序号的情况下导出excel预览界面切换页码不生效

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4390]
**DataEase 版本**
1.18.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
明细表不开启序号，在仪表板预览界面，选择明细表导出，预览界面切换页码不生效。

**Bug 重现步骤(有截图更好)**
1. 仪表板添加明细表，设置翻页模式，显示序号选择 “否”；
2.保存，回到预览界面，选择明细表--导出数据，在导出界面，选择翻页不生效；
<img width="1460" alt="图片" src="https://user-images.githubusercontent.com/48307752/212797036-9b0a7779-b836-4983-a0b0-11b83fd3329f.png">

3. 明细表设置，显示页码选择“是”，则导出预览界面翻页生效

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，不管是使用方向的标识点击或者直接点击数字，受累看一下前端的异常或者清除浏览器缓存查看一下此类问题是否依旧复现
