### ISSUE TITLE
[Bug]添加用户时，部分手机号码无法输入，未通过手机号码校验

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#4391]
**DataEase 版本**
V1.18.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 109.0.5414.87（正式版本） (x86_64)

**Bug 描述**
添加用户时，部分手机号码无法输入，未通过手机号码校验，但实际上手机号码为正常使用号码，且正常发送接受了验证码

**Bug 重现步骤(有截图更好)**
1.添加用户，输入手机号码：1995****319，会显示手机格式错误
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/70566485/212797975-809c9066-a2e4-4c7e-85a4-cb8060411c6f.png">
<img width="694" alt="image" src="https://user-images.githubusercontent.com/70566485/212798060-9b7befe3-f740-4c5d-98f1-a487d8b5cdb7.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快优化

**Comment by BBchicken-9527** [comment]
问题已修复，将会在下个版本上线到时可下载体验，新年快乐哦
