### ISSUE TITLE
sql器针对join语句解析支持不完善[Bug]

### ISSUE THREAD

**Issue by LeefVictor** [dataease/dataease#4393]
**DataEase 版本**
1.18

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**

**Bug 描述**
sql 针对join表的解析有误 (impala数据源)
代码位置： io.dataease.service.dataset.DataSetTableService  line:1131

**Bug 重现步骤(有截图更好)**
1. 使用语句： `SELECT *
FROM
  ( SELECT *
   FROM t1
   INNER JOIN og ON t1.game_id = og.id
   INNER JOIN
     (SELECT *
             ROW_NUMBER() OVER (PARTITION BY mr.c1
                                ORDER BY mr.c1 DESC) rn
      FROM mr) t2 ON (t2.rn=1 and xxxx)
   ) c`
2. 解析sql后会丢掉了 INNER JOIN og ON t1.game_id = og.id
3. 初步看是对join解析对象枚举不全：
![1673928990641](https://user-images.githubusercontent.com/24560998/212808910-5fbe8189-a5ec-48bd-9ce4-241abdc9b4de.png)
丢掉应该是 INNER JOIN og ON t1.game_id = og.id解析的对象是net.sf.jsqlparser.schema.Table导致的

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快优化
