### ISSUE TITLE
[Feature]血缘关系拓扑图展示优化

### ISSUE THREAD

**Issue by wan92hen** [dataease/dataease#4407]
**请描述您的需求或者改进建议.**

期望可以通过图例或者不同类型节点采用不同样式、颜色、图标等方式，让用户可以方便地区分出一个节点是仪表板、数据集还是数据源。

**Comment by xuwei-fit2cloud** [comment]
非常感谢反馈，很好的建议，我们后期会做一下优化。

**Comment by xuwei-fit2cloud** [comment]
v1.18.3版本已做处理，请更新到最新版本。
