### ISSUE TITLE
[Bug] excel数据集相关bug

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4409]
**DataEase 版本**
v1.18.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
1.excel数据集，原本数据格式为数值类型的数据上传后识别为时间，保存数值错误
2.用上述数据集修改字段类型，数值丢失
3.用上述数据集替换数据，数据格式修改后，依旧没有数值

**Bug 重现步骤(有截图更好)**
1.（1）
<img width="723" alt="image" src="https://user-images.githubusercontent.com/45852479/215329531-9fe6da2f-ec76-402a-bc73-62643a5dd5c7.png">
（2）
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/45852479/215329517-77c693da-9e35-430a-b322-e0a8fd44630d.png">
（3）
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/45852479/215329934-ddbf195c-72f3-4b21-ba37-6fc63b60cf30.png">
2.（1）
<img width="809" alt="image" src="https://user-images.githubusercontent.com/45852479/215330143-7ed1a9ce-ccbc-437d-8f46-454c543b7f02.png">
3.（1）
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/45852479/215330265-7e57005d-6ffe-4211-9701-9778a80c28ad.png">
（2）
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/45852479/215330274-cd22171f-d84c-4aa0-a6f0-37ed947c8ff4.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前excel上传判断类型的问题还在进一步的优化中，因为判断为时间当excel存储到数据库中的格式发生了改变导致无法按照用户期待的方向显示，我们会尽快优化此处问题，请耐心等待。
