### ISSUE TITLE
where语句中多个传参传入时， 没处理全面

### ISSUE THREAD

**Issue by LeefVictor** [dataease/dataease#4419]
**DataEase 版本**
1.18

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
无关

**Bug 描述**
像这种n个传参数的语句连在一起的时候， 目前我这边调试来看的话是没有生效的. （如果是我写sql不对， 请忽略[doge]）
![1675074970043](https://user-images.githubusercontent.com/24560998/215454898-27e5de8d-28ae-4520-8c83-dff8a825d48e.png)

**Bug 重现步骤(有截图更好)**

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是在创建的时候运行查询吗？还是说保存之后呢？还是在仪表板中？其实不管是哪里在你没有使用到参数化的时候本身就是不生效的可以理解为where bi=bi

**Comment by LeefVictor** [comment]
> 是在仪表板中， 通过下拉组件进行查询控制的时候， 传参没有生效，看最终的输出sql，入参的条件语句都没有了

**Comment by LeefVictor** [comment]
也有可能是我用了很多临时表的原因

**Comment by LeefVictor** [comment]
sorry,  sql写得太长了， 有个引用参数格式写错了。o(╥﹏╥)o
