### ISSUE TITLE
力导图 [Feature]

### ISSUE THREAD

**Issue by alifzl** [dataease/dataease#4420]
您能否考虑将 力导图 添加到下一个版本？ 它在关系分析图表中非常有用

<img width="1251" alt="image" src="https://user-images.githubusercontent.com/12857891/215565295-9155d051-be69-44e6-8092-8d43a72a534b.png">

像这样的
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/12857891/215565361-6e1bd9a9-b082-40bb-b278-510bc6584689.png">

**Comment by yayanpei** [comment]
感谢您的反馈，我们先记录并讨论一下。

**Comment by alifzl** [comment]
万事如意

**Comment by alifzl** [comment]
任何更新？

**Comment by alifzl** [comment]
你能更新状态吗？
