### ISSUE TITLE
[Bug]折线图柱状图不显示纵轴后图变高

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4421]
**DataEase 版本**
1.18.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
折线图，显示标签，如果取消显示纵轴，折线会变高，导致标签在上方遮挡
<img width="585" alt="图片" src="https://user-images.githubusercontent.com/48307752/215626722-de0f25bb-072f-4547-9d9d-5c9d047de7fd.png">

**Bug 重现步骤(有截图更好)**
1.折线图，显示标签，显示纵轴，效果正常：
<img width="924" alt="图片" src="https://user-images.githubusercontent.com/48307752/215626794-d948d84a-f40c-433f-a616-6e714b315fe1.png">

2.取消纵轴，图像上移，上方标签遮挡：
<img width="940" alt="图片" src="https://user-images.githubusercontent.com/48307752/215626954-b79d2839-73dc-472f-945a-bfadd82c052d.png">

3.柱状图也存在这个问题：
<img width="938" alt="图片" src="https://user-images.githubusercontent.com/48307752/215627034-41cd6d1a-cfca-44d6-a439-8a7e29169ded.png">
<img width="937" alt="图片" src="https://user-images.githubusercontent.com/48307752/215627062-54881d92-ee85-4764-bca7-2fddacf5d378.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，没有纵轴，即没有轴值（最大，最小），图形默认占据整个区域，标签不算图形区域会被挤在外。

既然都不要纵轴，那是不是说明值不重要，是不是也可以隐藏标签，或者在柱状图中，将标签位置放在内部或者底部。
