### ISSUE TITLE
[Feature] 优化查询逻辑构建

### ISSUE THREAD

**Issue by azkm1234** [dataease/dataease#4423]
**请描述您的需求或者改进建议.**
感谢飞致云开源dataease项目，期望dataease可以越做越好！！前几天抽时间查看了一下查询后端的代码，有一个小建议说一下，如果说错了，请各位大佬勿怪！ 当前代码查询SQL生成过程中，可以增加一个逻辑计划层，向上承接接口层传递过来的参数，如：Filters、Dims、Indice、高级计算（比如占比，同环比），衍生字段等；在逻辑计划层，根据Filters、Dims、Indice构建BasicLogicalPlan，之后将高级计算、衍生字段等映射成规则，作用于BasicLogicalPlan，最后整体将LogicalPlan翻译成SQL下推到数据源查询；
这样做的好处有：
1、在计算同环比时，可以保证不会出现Filter提前过滤掉数据，导致同环比计算不准确；（占比应该类似，没有细看）
2、计算逻辑可以下推到数据源做，保证dataease服务本生的稳定性；
3、代码架构上，做到动静分离；比如：在以后新增高级计算的时，直接映射成新规则，保证原有代码正确性，方便扩展；
希望可以和各位一起成长！祝大家新年快乐，感谢！！

**Comment by xuwei-fit2cloud** [comment]
非常感谢您的建议！在数据处理这块我们正在计划做相关改进，我们会将您的建议考虑进来的。也祝您新年快乐！

**Comment by azkm1234** [comment]
不客气，这个是我之前总结的，不知道能不能用得上！地址贴在这里，https://juejin.cn/post/7171057238876913677，如果有需要，我们继续交流；

**Comment by xuwei-fit2cloud** [comment]
1.x架构下我们不会再做相关调整，您提到的相关优化工作我们在后续的2.0版本中会仔细参考。
