### ISSUE TITLE
[BUG]修改API名称后，数据集同步任务失败

### ISSUE THREAD

**Issue by wf-xian** [dataease/dataease#4425]
修改API名称后，同步数据集的任务会执行失败，并出现“未找到API数据表”的异常；

建议修复，可从参考一下方案：
1.API被使用的时候禁止修改名称，做应提醒；
2.改用id做配置关联，而不是名称；id创建后是不变的，而名称可以改变；（建议）
3.API改名时，相关配置同时修改；（实际上能实现1就能实现3）

<img width="950" alt="551dd54b8a320ce006db565c09c2b46" src="https://user-images.githubusercontent.com/50934425/215657479-79f1f8cd-1cd0-4676-b6b5-6181fc529c7f.png">
<img width="1088" alt="870e419f185804510de16c9364fb251" src="https://user-images.githubusercontent.com/50934425/215657509-79f536db-1695-4f71-b9e1-b1958e634a4a.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.2版本已处理，请更新相关版本。
