### ISSUE TITLE
[Feature] 定时报告的附件能携带仪表板图片么

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4430]
**请描述您的需求或者改进建议.**
目前定时报告的附件只能是仪表板视图的 Excel 数据。
后续会不会出携带仪表板图片或者PDF么？
![55b6340d60db5f0d942a7c31c1c68aa](https://user-images.githubusercontent.com/82353425/215726287-9019fa85-066f-46b9-ac39-e1382c37db7e.png)

**Comment by yayanpei** [comment]
感谢您的反馈，定时报告的邮件正文中已展示了仪表板图片，所以附件中就没有再携带了。
