### ISSUE TITLE
[Bug]SQL中有左连接和参数保存会报错

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4432]
**DataEase 版本**
1.18.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
SQL数据集中，使用左连接，where 后 添加参数，可以运行查询，但保存会报错 ： （1.17.0 版本不报错）
<img width="1453" alt="图片" src="https://user-images.githubusercontent.com/48307752/215734474-0464c684-8b34-4d17-90cf-9960a6dadc68.png">

SQL 如下：
select s.地区 ,s.售后 , g.公司人数, g.日期 from  sales s
left JOIN  各区人数 g
on s.日期 = g.日期
where s.日期 BETWEEN '${begintime}' and '${endtime}'

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by ywhfzy** [comment]
https://github.com/dataease/dataease/issues/4393 查看下这个

**Comment by BBchicken-9527** [comment]
感谢反馈，我们修复一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.3版本已做处理，请更新到最新版本。
