### ISSUE TITLE
希望可以增加能通过手动输入数据的方式来配置仪表板中chart的宽度和高度[Feature]

### ISSUE THREAD

**Issue by SummerInzaghi** [dataease/dataease#4444]
希望可以增加能通过手动输入数据的方式来配置仪表板中chart的宽度和高度，目前只支持拖拽来配置chart宽度和高度，如果用户想设定chart具体宽高的数据就比较麻烦

**Comment by yayanpei** [comment]
感谢反馈，该需求已经在需求池中，会根据后期的规划去实现的。
