### ISSUE TITLE
想知道仪表板中，对于每一个chart的宽度和高度的计算逻辑是怎么样的[Question]

### ISSUE THREAD

**Issue by SummerInzaghi** [dataease/dataease#4445]
在代码中可以大致看出，对于每一个chart，是通过上下左右边距来计算具体每个chart的宽度和高度，但是具体的计算方式，代码中并没有相应注释，所以想请教这方面的实现逻辑

**Comment by xuwei-fit2cloud** [comment]
这个有点复杂，建议您慢慢的研读一下代码。
