### ISSUE TITLE
[Bug]新建sql数据集join中包含参数保存失败

### ISSUE THREAD

**Issue by lxc66** [dataease/dataease#4450]
**DataEase 版本**
v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
源码运行，和 https://dataease.fit2cloud.com/ 测试结果都不行

**浏览器版本**

Chrome 已是最新版本
版本 109.0.5414.120（正式版本） （64 位）
**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.参数设置，赋值之后运行查询可以成功
2.点击保存提示报错如图
3.
![image](https://user-images.githubusercontent.com/23331298/216264360-f03cf0c9-b4c6-4e2d-95b7-e64e4df4dc39.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by sshd123** [comment]
请问这个问题有在1.18.3版本修复吗？

**Comment by xuwei-fit2cloud** [comment]
v1.18.3版本中已修复，您可以升级到最新的v1.18.4版本。
