### ISSUE TITLE
[Feature] DataEase 增强数据处理功能

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4451]
**请描述您的需求或者改进建议.**
数据加工、处理、二次计算功能增强，提升 DataEase 整体 ETL 
DataEase 2.0 有对应的规划吗？

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，您的需求我们会做相关技术调研，在和产品设计本身不冲突的情况下是可以加入到产品规划里来的。
