### ISSUE TITLE
[Feature] 文本搜素框，支持按逗号隔开多选搜索

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4452]
**请描述您的需求或者改进建议.**
用户场景：选项内容非常多，每次要下拉一个一个选很麻烦，想把需要多选的所有内容直接从外部拷贝进去即可
例如 A，B，C，D 直接复制到文本框搜索就行。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，需求已理解，但具体实现方案及设计我们再讨论一下。
