### ISSUE TITLE
[Feature] 定时报告想发送仪表板里面的某个视图

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4453]
**请描述您的需求或者改进建议.**
场景：
仪表板做的粒度会更加细致，但是在发送邮件或者 Lark 时是不需要的，只需要一个较为宏观上的视图，目前就只能通过将宏观与细节分开做来达到这种效果

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前看短期可能还不会支持。
