### ISSUE TITLE
[Bug]数据源编辑名称后，页面左侧数据源列表名称不自动更新

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4454]
**DataEase 版本**
v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 109.0.5414.119（正式版本） (x86_64)

**Bug 描述**
见截图
![iShot_2023-02-03_16 14 20](https://user-images.githubusercontent.com/89771514/216548555-b34369a4-1dd6-424e-a7b1-b481e4a3b929.png)
![iShot_2023-02-03_16 15 35](https://user-images.githubusercontent.com/89771514/216548569-37df6059-474a-4532-aea8-2893aa750218.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下。
