### ISSUE TITLE
[Bug] 表格视图查看 Excel 数据点击分页无反应

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4458]
**DataEase 版本**
1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.使用表格视图填入数据，点击右上角查看详细数据
2.点击分页，无反应，默认第一页内容。
![image](https://user-images.githubusercontent.com/82353425/216870287-419c5658-0caa-4bc2-8fba-c3d406b2edac.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，因为考虑到数据量较大情况可能导致前端占用资源过大所以做了分页处理，所以只显示看到的数据，不过右下角页码确实不太友好容易让用户产生误判是可点击的，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.4版本已处理。
