### ISSUE TITLE
[Bug]创建用户，不填手机号码，无法添加用户，报错：手机号码格式错误

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#4459]
**DataEase 版本**
V1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 109.0.5414.119（正式版本） (x86_64)

**Bug 描述**
创建用户，不填手机号码，无法添加用户，报错：手机号码格式错误

**Bug 重现步骤(有截图更好)**
创建用户，不填手机号

<img width="843" alt="image" src="https://user-images.githubusercontent.com/70566485/216914251-5ca493ac-72e2-438d-9e8c-4f5f186505be.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下。
