### ISSUE TITLE
[Bug]SQL数据集，使用带动态参数的inner join语句，不能保存

### ISSUE THREAD

**Issue by zqstarmoon** [dataease/dataease#4461]
**DataEase 版本**
1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器109

**Bug 描述**
SQL数据集，使用带动态参数的inner join语句，不能保存

**Bug 重现步骤(有截图更好)**
1. SQL语句是select f.id,f.oid,m.mid from sj_fbq f inner join sj_merchant m on m.mid=f.business_id where f.vol=${vol}
2. 可以正常查询
3.点击保存，提示com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'm.mid' in 'field list'

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，此处确实有问题，我们修复一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.3版本已做处理，请更新到最新版本。
