### ISSUE TITLE
[Bug] 本地开发环境部署缺少达梦等数据库

### ISSUE THREAD

**Issue by ywhfzy** [dataease/dataease#4462]
**DataEase 版本**
1.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌标准版

**Bug 重现步骤(有截图更好)**
1.已经将服务器上的/opt/dataease/plugins/default/目录下的插件放在本地环境下，重启了dataease
![image](https://user-images.githubusercontent.com/82353425/216926326-a37ea459-265d-4c21-b46b-4a583667e048.png)

2.如图所示，还是缺少了达梦数据库
3.![7a5c3553-6769-4525-950a-02c0687e8475](https://user-images.githubusercontent.com/82353425/216926194-b4b5f08d-804e-4460-ba91-0c0f830fafdc.png)

**Comment by xuwei-fit2cloud** [comment]
你好，可以检查一下my_plugin表中是否有达梦相关的数据记录。

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #4589
