### ISSUE TITLE
[Bug]仪表板创建公共链接，开启密码保护，访问链接异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4463]
**DataEase 版本**
v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行，官方demo环境

**浏览器版本**
版本 109.0.5414.119（正式版本） (x86_64)

**Bug 描述**
![image](https://user-images.githubusercontent.com/89771514/216926344-92250e20-25ca-4b7a-a7e4-e598052f3feb.png)
![image](https://user-images.githubusercontent.com/89771514/216926376-72deeef1-64b5-42b2-94a1-426875862d6b.png)

**Comment by ZhaoQian1222** [comment]
问题的原因是复制的时候把密码也一起贴进去了，把密码部分去掉，再访问就可以的

建议进行优化：可以参考腾讯会议复制会议链接时的样式效果

**Comment by BBchicken-9527** [comment]
感谢反馈，目前应该不会去改变这里的复制，主要是考虑使用场景不会是自己使用，而是去做分享的时候发送给别人的一个操作。
