### ISSUE TITLE
[Feature]定时报告能支持设置发送到指定链接（如：ftp）

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4465]
**请描述您的需求或者改进建议.**
使用场景：
系统部署在内网环境，财务报表的场景比较多，需要将报表导出后进行编辑和处理，希望通过定时报告的方式将 excel 数据定时发送到指定的地方，然后由其他同事再编辑，减少用户在中间过程中自己导出的工作量

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个短期内还不会做支持。根据发送对象的不同，我们需要支持不同的服务接口，如ftp、oss等。我们会先记录此需求，如果有更多的用户有同样的需求，我们会安排相关的开发工作。
