### ISSUE TITLE
[Feature]excel 数据集支持自动导入，定时更新

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4466]
**请描述您的需求或者改进建议.**
指定位置在文件共享服务器，DataEase 定时去取（财务会计——财务报表导出后放到指定目录之后，DE自动读取固定目录的文件报表）

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到并放入需求池中。

**Comment by yayanpei** [comment]
您的需求和建议我们已记录，近期我们主要规划并实施2.0的开发，因此暂不规划实现该需求，issue暂时先关闭，再次感谢您对DataEase的关注和支持。
