### ISSUE TITLE
[Feature]仪表板设置主题样式更丰富些（比如节假日的主题等）

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4467]
**请描述您的需求或者改进建议.**

模板市场中虽然也有不错的主题，但是站在使用者的角度去使用时，应用模板后可能需要删掉很多不用的图表等内容，而且为了应用某个模板的主题，可能需要用户对已经存在的仪表板做很多调整，这样并不是很友好，所以建议仪表板中可以通过直接切换主题设置来调整仪表板的主题。

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到，后续也会逐渐丰富仪表板主题的。
