### ISSUE TITLE
[Feature]Echarts 折线图希望支持热点区域高亮设置

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4469]
**请描述您的需求或者改进建议.**

针对实验数据的使用场景，折线图中希望做热点区域高亮设置，如最高点、最低点等区域范围，类似于辅助线的动态设置。

**Comment by yayanpei** [comment]
感谢反馈，您的建议很不错，后续我们会优先进行优化的。

**Comment by yayanpei** [comment]
感谢您的反馈，最高点、最低点高亮显示，这个建议很不错，我们先记录并规划进后续的优化。

**Comment by ZhaoQian1222** [comment]
这里有Echarts的效果图：
https://echarts.apache.org/examples/zh/editor.html?c=area-pieces
![image](https://user-images.githubusercontent.com/89771514/217979015-844e0881-c0bf-45d3-a8c1-2c13aebf2f29.png)

https://echarts.apache.org/examples/zh/editor.html?c=line-sections
![image](https://user-images.githubusercontent.com/89771514/217979062-626f0765-3823-4d19-a303-f69e320181b2.png)

**Comment by yayanpei** [comment]
我们后期会侧重在antv图库做扩展，antv图库折线图最高点、最低点的标记已经规划在最近的小版本中实现，还请多加关注，issue我们就先关闭了，感谢您的关注和支持。
