### ISSUE TITLE
[Feature]希望不同类型的数据集也可以支持关联

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4470]
**请描述您的需求或者改进建议.**
使用场景：有Excel数据集、API数据集、数据库数据集三种数据集，而且三种数据集之前需要进行关联
但是 Excel 数据集关联数据集，目前仅支持关联同类型的数据集，无法满足此场景的需求（见截图）

![截图](https://user-images.githubusercontent.com/89771514/216946549-e108f16e-83ec-4966-8688-ac6da967a734.png)

是否可以引入类似 DataX 这样的工具，或者借鉴其设置理念

**Comment by yayanpei** [comment]
感谢您的反馈，数据集无法关联，主要是由于他们所属不同的数据源，跨数据源的关联暂时还不支持，后续我们再看看其他可行的方案。

**Comment by ameizi** [comment]
好需求，顶起来 +1

**Comment by ZhaoQian1222** [comment]
Excel数据集和API数据集底层的数据都是存储在 doris 中的，数据库数据集和 SQL 数据集如果设置为定时同步模式，数据也是存储在 doris 中的，理论上数据都是存储在 doris 中的情况下，进行关联是可行的

**Comment by yayanpei** [comment]
感谢反馈，1.x 版本暂不考虑跨数据源数据集的关联，我们在 2.0 调研技术方案时 ，会将跨数据源的支持加入考虑，issue暂时先关闭了，再次感谢您对 DataEase 的关注和支持。
