### ISSUE TITLE
[Feature]支持动态弹框或者增加一些动态展示效果

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#4471]
**请描述您的需求或者改进建议.**
使用场景：
1、使用文本组件、富文本视图组件、富文本组件等文字类型的组件，点击之后可弹出弹出框，弹出框内可设置文字或者视图等；
2、目前我们的网页、超链接等，设置超链接，只支持页面弹出，打开新的页面或者覆盖当前页面，希望可以设置弹出框展示，并可以关闭；
3、支持动态图片效果展示，除了目前的GIF，例如支持flash动画效果，文件后缀为fla、swf等；
4、是否可以内置一些动态的按钮展示效果，点击后，按钮变化等；
5、支持动态时间轴效果，跟日期类型字段绑定，实现时间轴数据展示效果；
以上需求是想用DE实现故事类数据可视化作品，实现一系列的大屏的组装。
时间轴效果如下，可以绑定视图，进行灵活过滤：
<img width="676" alt="image" src="https://user-images.githubusercontent.com/70566485/217125279-a56b8aee-365d-4b11-9ae9-382f86ef9e3f.png">

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到并记录。

**Comment by xuwei-fit2cloud** [comment]
该需求已记录，我们会在后续的2.0版本中安排支持，暂时关闭。
