### ISSUE TITLE
[Feature]血缘关系图，支持在页面上放大缩小

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#4472]
**请描述您的需求或者改进建议.**
血缘关系图，支持在页面上放大缩小，目前如果血缘关系复杂的情况，无法分析相关的血缘关系
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/70566485/217128975-5d1cf77d-81fa-40f4-8797-1a66d483ba25.png">

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到，后面会进行相关的优化。

**Comment by yayanpei** [comment]
该功能已经进行优化，请升级至 V1.18.3 版本。
