### ISSUE TITLE
[Feature]希望支持钉钉移动端免登功能

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4473]
**请描述您的需求或者改进建议.**
目前PC端已经支持钉钉免登功能，但是移动端还不支持

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到并记录。

**Comment by yayanpei** [comment]
该功能已经在 V1.18.0 版本中实现，请升级至该版本即可使用。
