### ISSUE TITLE
[Feature]定时报告希望支持指定按角色、组织发送

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4474]
**请描述您的需求或者改进建议.**
定时报告希望支持指定按角色、组织发送，目前仅支持按人发送，人数众多的情况下使用不够方便
![image](https://user-images.githubusercontent.com/89771514/217161866-0c37eebf-aa1a-410b-9396-ebcdf0181070.png)

**Comment by xuwei-fit2cloud** [comment]
短期内我们还不会做相关支持，我们会放到2.0版本中去实现。
