### ISSUE TITLE
[Feature]希望发送钉钉的消息通知中能够支持设置通过链接跳转到钉钉工作台的 DataEase 应用

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4475]
**请描述您的需求或者改进建议.**
![1675750110037](https://user-images.githubusercontent.com/89771514/217162497-1433e16e-0b00-4627-b446-e917d289e761.jpg)

**Comment by ZhaoQian1222** [comment]
场景是这样的：目前我们发送的定时报告，希望将仪表板的访问链接放置到报告中，用户在钉钉中收到报告通知后，点击链接可跳转到钉钉工作台中查看此仪表板，同时携带用户信息，按数据行列权限的设置展示此用户过滤后的数据

**Comment by xuwei-fit2cloud** [comment]
钉钉收到的定时报告，是不受接收者权限控制的，若在链接中带有用户信息进行了应用登录，则显示的内容会按用户权限进行过滤，即会出现报告与应用数据不一致的情况，目前还不考虑做相关支持。
