### ISSUE TITLE
[Feature]行列权限设置的白名单设置，希望支持按角色、组织进行设置

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4476]
**请描述您的需求或者改进建议.**
行列权限设置的白名单设置目前仅支持按用户进行设置，白名单用户太多时，需要一个一个选，使用不够方便
![picture](https://user-images.githubusercontent.com/89771514/217164737-08695404-a518-4f11-9b97-90ad66a7268f.png)

**Comment by yayanpei** [comment]
感谢反馈，白名单的设置这里我们暂时不做优化，如果白名单的用户过多，可能您给用户分配的角色或者组织不太合适，建议调整这些用户的角色或者组织。

**Comment by ZhaoQian1222** [comment]
比如白名单用户有 A1-A30 这30个用户，把这30个用户设置到同一个角色下，此时白名单设置希望能支持按角色控制，这个场景应该是比较常见的

**Comment by yayanpei** [comment]
感谢反馈，咱们这里暂时不做优化了，原因如下：

白名单用户过多，建议这些白名单用户不要归属于当前角色a，将这些白名单用户归属于另外一个角色b，在行列权限设置时，选择a角色进行设置。

issue就先关闭了，感谢关注与支持。
