### ISSUE TITLE
[Feature]钉钉应用中的仪表板希望支持跟PC端一样的全屏幕预览功能，或者支持隐藏仪表板左侧菜单栏

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4477]
**请描述您的需求或者改进建议.**
钉钉应用中的仪表板希望支持跟PC端一样的全屏幕预览功能，或者支持隐藏仪表板左侧菜单栏
![image](https://user-images.githubusercontent.com/89771514/217165075-8d24778d-d1f0-4a74-bc95-824d6ce051a2.png)

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到并记录。

**Comment by xuwei-fit2cloud** [comment]
由于钉钉、企业微信等应用中打开DataEase，是在应用内部打开，全屏预览的功能在此情况下意义并不大，所以在此类场景里，我们将全屏预览功能给移除了，近期版本中我们还没有添加的计划。
