### ISSUE TITLE
[Bug]Tab组件中添加AntV明细表，设置下钻，当屏幕比较小时，下钻后tab中的导航栏看不见了，导致无法回到上一级

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4479]
**DataEase 版本**
v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
版本 109.0.5414.119（正式版本） (x86_64)

**Bug 描述**
Tab组件中添加AntV明细表，设置下钻，当屏幕比较小时，下钻后tab中的导航栏看不见了，导致无法回到上一级（见截图）
![WechatIMG392](https://user-images.githubusercontent.com/89771514/217166521-c2f4632d-a5a2-4886-9814-f8de1270a9a3.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，缩小后选项卡组件应该是可以向下滑动的

**Comment by ZhaoQian1222** [comment]
已经试过了，向下滑动滑到底部也是没有导航栏，应该是被遮挡了

**Comment by BBchicken-9527** [comment]
感谢反馈，我们修复一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
