### ISSUE TITLE
echarts汇总表没有数据格式设定[Bug]

### ISSUE THREAD

**Issue by Gujiaweiguo** [dataease/dataease#4480]
**DataEase 版本**
dataease-v1.18.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge
版本 109.0.1518.78 (正式版本) (64 位)

**Bug 描述**
echarts汇总表没有数据格式设定，汇总表格式混乱

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/40282813/217266050-3b4362d4-2d65-4931-9b5d-df7df0c6d8d5.png)

**Comment by xuwei-fit2cloud** [comment]
目前ECharts图库中的视图类型都还没有支持数值格式设置的功能，如果需要的话，可以试试AntV图库的表格。
若AntV图库表格有不满足需求的地方，您可以给我们提，我们会做相关优化。

**Comment by xuwei-fit2cloud** [comment]
Echarts图库暂时还没有支持数值格式设置的计划，该需求暂时关闭。
