### ISSUE TITLE
[Bug]代码中SQL参数处理部分如果表名中含有‘-’时，会出现异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4487]
**DataEase 版本**
v1.18.0

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**Bug 描述**
问题代码位置：
Statement statement = CCJSqlParserUtil.parse(tmpSql);

![iShot_2023-02-08_16 26 40](https://user-images.githubusercontent.com/89771514/217476122-bd44f195-db32-44a2-8ae0-9642c1c301cf.png)
当tmpSql ="SELECT * from internal-diagnostic_log WHERE logstore='DATAEASE_PATAMS_BI'" 时，会抛出异常
Method threw 'net.sf.jsqlparser.JSQLParserException' exception.

当tmpSql ="SELECT * from internal_diagnostic_log WHERE logstore='DATAEASE_PATAMS_BI'" 时，执行正常

**Comment by xuwei-fit2cloud** [comment]
您好，SQL数据集中如果使用了表名带-的数据表，建议将该表名用``括起来，且建议在创建表名时，不要使用-。

**Comment by ZhaoQian1222** [comment]
自己开发的 influxdb 数据源插件，写的 SQL 语句中设置 SQL 参数变量的同时还使用了 group by time(30d) 进行分组，也是这个地方报错

完整 SQL：
select resourceName,max(cpuUsageMax) from cloud_server_metric where time > '${startTime}'  and time < '${endTime}' group by time(30d),resourceName
