### ISSUE TITLE
[Feature]过滤组件文本下拉支持模糊搜索

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#4492]
**请描述您的需求或者改进建议.**
1、使用文本下拉组件数据量大的情况下，下拉选择找数据比较困难，希望在下拉选择的时候能够支持模糊搜索
2、使用文本列表组件，数据较多，展示不好看
3、使用文本搜索组件，数据量大，不知道搜索哪些数据
4、下拉树可以实现，但是还是希望下拉组件能够支持模糊搜索

**Comment by yayanpei** [comment]
感谢反馈，您的建议很不错，已经加入需求中，后续会根据需求优先级规划实现的。

**Comment by yayanpei** [comment]
我们会在 2.0 的下拉框组件重构时加入该需求，1.x 的下拉框组件不再支持该功能，issue就先关闭了，再次感谢您对DataEase的关注和支持

**Comment by yayanpei** [comment]
目前是支持模糊搜索的，如下：
<img width="370" alt="image" src="https://user-images.githubusercontent.com/84168063/223604669-a87332ac-ea3c-41e5-9456-1695eaab9256.png">
