### ISSUE TITLE
[Bug]分页明细表，字段设置跳转链接，只有第一页生效

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4494]
**DataEase 版本**
v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
分页明细表，字段设置跳转链接，只有第一页生效点击可跳转，翻页后该字段点击不再跳转。

**Bug 重现步骤(有截图更好)**
1.设置邮件字段启用跳转。
![image](https://user-images.githubusercontent.com/48945409/217727759-21be0e23-90ba-45a4-aac1-513d4c512744.png)

2.在第一页点击该字段，成功跳转了出去。
![image](https://user-images.githubusercontent.com/48945409/217727932-084cd0d1-6204-4eae-b8c1-d14a06cc0395.png)

3.翻到第二页再点击该列任意数据，都不再跳转。
![image](https://user-images.githubusercontent.com/48945409/217728040-d7fce353-9869-4b07-a331-590564e605c4.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.3版本已做处理，请更新到最新版本。
