### ISSUE TITLE
[Bug]sql数据集中pgsql多表连接查询使用参数无法保存

### ISSUE THREAD

**Issue by fagains** [dataease/dataease#4496]
**DataEase 版本**1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
edge108.0.1.1462.54

**Bug 描述**

[Bug]sql数据集中pgsql多表连接查询使用参数无法保存
**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前参数化的功能还在逐步的完善，目前只支持相对简单的，并且在where之后的参数化配置

**Comment by xuwei-fit2cloud** [comment]
由于SQL语法的场景比较复杂，我们可能没有办法很快都能支持上，希望您能够提供一下相对详细的信息，我们好对此做相关处理。
