### ISSUE TITLE
[Feature]【视图】缩略轴的高度可调整

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#4498]
**请描述您的需求或者改进建议.**
希望缩略轴的高度可进行调整，当前缩略轴太高了！
![wecom-temp-167960-de9a161592291b5bfb69a2b345c77a1a](https://user-images.githubusercontent.com/24768910/217760609-4f960b9f-63a2-411b-8acb-25282c63cef9.png)

**Comment by yayanpei** [comment]
感谢反馈，请用使用的是echarts图库的柱形图吗？建议您使用antv图库的柱形图，后续也将侧重在antv图库上做功能拓展。

**Comment by AndroidBaby1** [comment]
好的，明白了，谢谢！
