### ISSUE TITLE
[Bug]视图已重新编辑，但仪表盘所引用的视图并未变化

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#45]
DataEase 版本
v1.0.0-rc2
浏览器版本
Chrome 91.0.4472.114（正式版本） (arm64)
**Bug 描述**
在视图处对表格类型的图表做了字体、颜色的修改并保存，但是在仪表盘查看却未变化，重新拖出来的该视图也是原本的样式。

**Bug 重现步骤(有截图更好)**
1.对“用例维护人分布”的表格视图进行样式的调整，主要为字体大小、表格颜色等，并保存，修改后的表格样式如下；
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/48945409/123415268-980bbd80-d5e7-11eb-8c6c-cf93b40e243d.png">
2.进入仪表盘查看，该表格仍然未之前的样式；
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/48945409/123415361-bb366d00-d5e7-11eb-89c9-e2ba1323fc79.png">
3.重新查看刚才编辑的图表确认之前是有保存成功的；
4.编辑仪表盘拖出新的“用例维护人分布”的视图也仍然是之前的样式；
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/48945409/123415695-38fa7880-d5e8-11eb-8f46-1ce0ca722608.png">

**Comment by XiaJunjie2020** [comment]
不是bug，无需修改，视图样式优先级调整成 视图优先，视图中的样式才会生效，图中是仪表板优先
