### ISSUE TITLE
[Bug]查看某个视图中，对某视图执行重命名操作，重命名成功，但是视图设计区域被清空，并提示「从左侧选择视图」

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#450]
**DataEase 版本**
1.10-rc2

**浏览器版本**
chrome-92.0.4515.107

**Bug 描述**
查看某个视图时，对该视图执行重命名操作，虽然视图已经被重命名了，但视图设计区域被清空，并提示「从左侧选择视图」

**Bug 重现步骤(有截图更好)**
1.差看某个视图（以设计好）
2.对改视图执行重命名操作
3.视图树中该视图已被重命名，但视图设计区域被清空，并提示「从左侧选择视图」【问题1】
4.重命名后，视图树状结构还会重新排序【问题2】

作为使用者，我只想对某个视图的名称进行重命名而已，我不想有任何其他多余的非自主的操作出现。不要违背「所见即所得」的原则。

**Comment by xuwei-fit2cloud** [comment]
问题1，我们会修改为重命名后，仍显示当前视图
问题2，视图树是按名称排序的，这个刷新结果是符合设计预期的，此问题不做修改
