### ISSUE TITLE
[Bug]doris数据源视图报错

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4507]
**DataEase 版本**
1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
数据源 doris，任何视图都会报错；
<img width="873" alt="图片" src="https://user-images.githubusercontent.com/48307752/217815134-cd316dba-1b73-4c06-b21e-12c5ed88ef88.png">

**Bug 重现步骤(有截图更好)**
1. 在doris中创建库、创建表；
2. 在DataEase 中创建 doris数据源、数据集（直连）；
3.在视图中，展示 doris的数据集，基本所有视图都会报错。

测试数据表可参见附件
[测试数据表.txt](https://github.com/dataease/dataease/files/10697231/default.txt)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.3版本已做处理，请更新到最新版本。
