### ISSUE TITLE
[Bug]气泡地图样式配置中部分字体大小不协调

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4512]
**DataEase 版本**
v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
如下图所示，红色部分框全出类的字体明显更偏大，显得很不协调
![image](https://user-images.githubusercontent.com/48945409/218019760-de9028cb-72b6-4b5b-a11c-2923c54dcac1.png)
![image](https://user-images.githubusercontent.com/48945409/218019896-238df8f1-36d2-496c-ac99-34de154a1248.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们尝试优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.3版本已做处理，请更新到最新版本。
