### ISSUE TITLE
mysql数据集同步时报错（SQL ERRORStatement cancelled due to timeout or client request）[Bug]

### ISSUE THREAD

**Issue by Xiaosade** [dataease/dataease#4513]
**DataEase 版本**

18.1
**运行方式(安装包运行 or 源码运行 ?)**
docker

**浏览器版本**
chorm

**Bug 描述**

查询脚本在datagrip的查询时间为50秒，预览可以看到数据，但是数据同步报错：
SQL ERRORStatement cancelled due to timeout or client request

**Bug 重现步骤(有截图更好)**
1.
2.
![image](https://user-images.githubusercontent.com/35336961/218234094-9c47418f-7198-4148-9dd4-28d098192211.png)

3.

**Comment by xuwei-fit2cloud** [comment]
你好，可以试试调整一下超时时间试试。
![图片](https://user-images.githubusercontent.com/1892127/218361074-85017808-82de-4a65-8659-ec5a189efaf6.png)

**Comment by Xiaosade** [comment]
设置这里可以了，但会存为一个新的数据源？

**Comment by xuwei-fit2cloud** [comment]
如果是编辑该数据源的话，是不会另存为一个新的数据源的，但如果是复制的话，会新建一个数据源。
