### ISSUE TITLE
[Bug]编辑用户时不填手机号保存提示“手机号码格式错误”

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4514]
**DataEase 版本**
v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
如下图所示，用户手机号并未标识必填，但是编辑用户保存时，无法保存，提示“手机号码格式错误”。
<img width="850" alt="image" src="https://user-images.githubusercontent.com/48945409/218261609-f01d2daa-7110-438e-b3a7-6b96ed0ba297.png">

**Comment by xuwei-fit2cloud** [comment]
问题已修复，请等待新版本发布。

**Comment by xuwei-fit2cloud** [comment]
v1.18.3版本已做处理，请更新到最新版本。
