### ISSUE TITLE
[Feature]希望富文本组件、富文本视图支持内容自动重复滚动

### ISSUE THREAD

**Issue by lyons-hz** [dataease/dataease#4517]
**请描述您的需求或者改进建议.**
希望富文本组件、富文本视图支持内容自动重复滚动。
目前只能手动滚动，在门户大屏展示的时候，内容太多时效果不好。

**Comment by xuwei-fit2cloud** [comment]
您需要的应该是新的走马灯组件吧，一般需要滚动的内容都是文本型内容，这个需求我们已经记录到需求池中了。

**Comment by yayanpei** [comment]
您的需求和建议我们已记录，近期我们主要规划并实施2.0的开发，因此暂不规划实现该需求，issue暂时先关闭，再次感谢您对 DataEase 的关注和支持。
