### ISSUE TITLE
[Feature]多次关联数据集的需求

### ISSUE THREAD

**Issue by Xiaosade** [dataease/dataease#4518]
**请描述您的需求或者改进建议.**
在给数据清先和分层的时候，现有系统只能做2次的转储，即：1、建立sql数据集，2、数据集关联
但在实际的业务中需要对2个系统（两个库）的数据进行关联后作为维度表或事实表，此时还需要在第2步的基础上进行再次关联产生宽表。

**Comment by yayanpei** [comment]
您的建议和需求已记录，该功能涉及到的改动较大，在1.x 版本上不会再规划相关功能的实现，我们近期在规划 2.x 的设计时，会评估该功能实现的可行性，issue暂时先关闭，感谢您对 DataEase 的关注和支持。
