### ISSUE TITLE
过滤组件无法选择字段

### ISSUE THREAD

**Issue by yilujun100** [dataease/dataease#4521]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1. 在仪表板中选择过滤组件年份
2.选择按表页签进行字段查询
3.但是，字段列表为空，请求接口是有返回字段的

**Comment by xuwei-fit2cloud** [comment]
你好，是在源码运行的情况下出现的问题吗？
请问一下是哪个分支的代码，可以试试v1.18分支的代码。
另外，你也可以在 https://dataease.fit2cloud.com 在线体验环境上试试，看看有没有这个问题。
在线体验环境上的代码是 v1.18 分支的最新代码。

**Comment by yilujun100** [comment]
就是用的在线体验的地址 https://dataease.fit2cloud.com/ 年前看都是好的

**Comment by yilujun100** [comment]
![image](https://user-images.githubusercontent.com/5162481/218450599-db76143a-9267-4b19-a90c-5d0dce7512bd.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，这是因为此处的数据类型为数值，需要修改字段类型为时间类型过滤器才可以过滤出匹配的字段
