### ISSUE TITLE
[Feature]可以对折线图中的高点或低点，添加注释

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4522]
**请描述您的需求或者改进建议.**
可以对折线图中的高点或低点，添加注释，如下图：
<img width="766" alt="图片" src="https://user-images.githubusercontent.com/48307752/218410227-d536e360-245c-45f4-b277-536103298232.png">

上图所示的地址：http://antv.antfin.com/zh-cn/g2/3.x/demo/line/line4.html

**Comment by yayanpei** [comment]
感谢您的反馈建议，该需求目前已经在需求池中。

**Comment by yayanpei** [comment]
该需求已规划在近期的小版本中进行实现，issue先关闭了，感谢您对 DataEase 的关注和支持。
