### ISSUE TITLE
[Feature]可视化插件集成到三方系统

### ISSUE THREAD

**Issue by Jorkins** [dataease/dataease#4525]
一般第三方都有自己的大屏展示系统，期望能直接用dataEase部分组件，如今年上半年GDP产业分布组件集成到已有系统中，其他的组件不需要嵌入已有系统

![ea8041b50e11cb654dc79069d4bb269](https://user-images.githubusercontent.com/6858010/218655527-3836b36e-13a6-4284-a84c-ffd4d37796ad.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，嵌入式的支持我们正在做相关设计，可能还需要些时间才能发布，还请持续关注。

**Comment by yayanpei** [comment]
我们有规划在 2.x 中做嵌入式的支持，issue我们先关闭了，再次感谢您对 DataEase 的关注和支持。
