### ISSUE TITLE
[Bug] AntV 明细表列宽调整为自适应的情况下，加了千分符会导致数值格式的字段显示不全

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4531]
**DataEase 版本**
v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 109.0.5414.119（正式版本） (arm64)

**Bug 描述**
AntV 明细表列宽调整为自适应的情况下，加了千分符会导致数值格式的字段显示不全

**Bug 重现步骤(有截图更好)**
1. 明细表，列宽调整为自适应，且将数值格式的千分符去掉
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/30063018/218907130-8927db46-8b7b-4c1b-bb41-58f3c70d59b9.png">
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/30063018/218907172-8fd2e0cd-3711-460e-8f3d-4c510396f027.png">
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/30063018/218907223-6f81fc7c-592f-4b02-a809-e6b8b3b431bf.png">

2. 添加千分符后，明细表数值显示不全
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/30063018/218907319-80add1ce-8329-4e76-a885-3cc3c7f6f659.png">
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/30063018/218907365-9db7ef39-0e91-445a-b973-0f3a2cfa84f2.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个列宽的计算是S2自动完成的，我们也反馈一下。
