### ISSUE TITLE
[Bug]文本列表组件在深色模式下选中内容不可见

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#4532]
**DataEase 版本**
1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 最新

**Bug 描述**
当仪表板是深色模式时，文本列表组件已选中的值颜色与背景接近导致文字不可读。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/30886198/218913711-08d204f8-fb43-47e5-bd9a-416970ee15f0.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.3版本已做处理，请更新到最新版本。
