### ISSUE TITLE
在仪表盘上新增【显示图片租价】

### ISSUE THREAD

**Issue by 1144075799** [dataease/dataease#4535]
在我们的需求需求中，在仪表盘中，不仅仅是图表的显示，还有对应商品图片的显示，所以希望官方可以提供一个 “根据图片链接”显示的组件

**Comment by xuwei-fit2cloud** [comment]
在仪表板的其他组件中，可以通过添加图片、视频、流媒体、网页等组件来丰富展示。
甚至在富文本组件中，也可以添加图片、视频等多媒体元素，您可以试试。

**Comment by 1144075799** [comment]
我要的需求是点击商品 通过切换图片地址，从而达到切换图片的效果。现有的“图片”组件只能写出死的地址

**Comment by xuwei-fit2cloud** [comment]
这个功能目前确实还不能支持，我们先记录一下该需求。
