### ISSUE TITLE
[Feature]建议 Tab 组件轮播设置放在“设置”中，而非“Tab 内部样式”中

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4538]
**请描述您的需求或者改进建议.**
目前 Tab 组件的轮播设置放在 “内部样式” 的设置中，不是太合理与直观，其设置内容并不属于样式范畴。
![image](https://user-images.githubusercontent.com/48945409/218953703-4d3d24a3-743e-4528-9e65-8adc9c08ddc2.png)

正常情况下我们会更倾向于在设置中找该配置项。
![image](https://user-images.githubusercontent.com/48945409/218953777-9893f2cb-97f0-43bd-b103-25e195ae3194.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们后续优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已处理，请更新最新版本。
