### ISSUE TITLE
[Bug]明细表分页展示却并未向后端发起分页数据请求

### ISSUE THREAD

**Issue by wsc58888** [dataease/dataease#4539]
**DataEase 版本** 
dataease-v1.18.2-offline

**运行方式(安装包运行 or 源码运行 ?)**
安装包离线运行

**浏览器版本**
google

**Bug 描述**
列表的右上角有有个详情按钮
打开后的详情分页有问题，不刷新数据

**Bug 重现步骤(有截图更好)**
1.
![751c9a8fff1190add87e9b4b2869861](https://user-images.githubusercontent.com/4038711/218962717-29157736-21ff-47d1-8c3f-f66786ec02a7.png)

2.
![da47351b63daa1ce93a8bfb2021b2e7](https://user-images.githubusercontent.com/4038711/218962654-919d0500-c4b6-4aff-b020-ade0c5003cf4.png)

3.

**Comment by xuwei-fit2cloud** [comment]
您好，现在还不是所有的情况下都支持分页的，您可以参考一下我们的文档：
https://dataease.io/docs/release_notes/v1.17.0/#22

目前仅对直连模式的数据集可支持大部分的分页。
