### ISSUE TITLE
[Bug]多用户命名空间的问题

### ISSUE THREAD

**Issue by alzerwv** [dataease/dataease#4545]
**DataEase 版本**
v1.18

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome

**Bug 描述**
A用户在创建数据源，数据集，仪表盘的时候，虽然看不到B用户创建的，但是名称却不能跟B用户创建的一样。会报错，名称重复。这样会让A用户觉得很奇怪。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前确实是会有这个问题。
当前的设计中并没有包含命名空间或者工作空间的概念，所以资源之间不存在完全的隔离。
我们后期版本中会专门对这块进行处理，可能会需要些时间。

**Comment by xuwei-fit2cloud** [comment]
近期版本还不会支持，暂时关闭该issue。
