### ISSUE TITLE
筛选条件对选项卡内的视图无效

### ISSUE THREAD

**Issue by Toy-data** [dataease/dataease#4547]
**DataEase 版本**
v1.18.1

**运行方式(安装包运行 or 源码运行 ?)**
在线安装

**浏览器版本**
版本 110.0.1587.41 (正式版本) (64 位)

**Bug 描述**
筛选条件对选项卡内的视图无效，我将一些视图拖到选项卡后，发现筛选条件无法对其生效，将其移除选项卡后，就可以正常筛选了

**Bug 重现步骤(有截图更好)**
1.创建一个视图，并添加筛选条件，并且创建一个选项卡；
2.将视图拖进选项卡中，发现筛选条件对其无法生效；
3.再次将视图拖出选项卡后，筛选条件就生效了。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，您可以在我们在线体验环境里试试能否复现此问题，我们并未发现此处有您反馈的情况。
选项卡外的过滤组件，是可以对选项卡内的视图做过滤的；而选项卡内的过滤组件，只能对该选项卡内的视图做过滤。

**Comment by Toy-data** [comment]
***@***.***

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月15日 18:27
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [dataease/dataease] 筛选条件对选项卡内的视图无效 (Issue #4547)


感谢反馈，您可以在我们在线体验环境里试试能否复现此问题，我们并未发现此处有您反馈的情况。
选项卡外的过滤组件，是可以对选项卡内的视图做过滤的；而选项卡内的过滤组件，只能对该选项卡内的视图做过滤。

―
