### ISSUE TITLE
[Feature]新增筛选条件可以默认选中第一个条件

### ISSUE THREAD

**Issue by Toy-data** [dataease/dataease#4548]
**请描述您的需求或者改进建议.**
在日常使用中，常常需要使用筛选条件，在使用”文本下拉“组件时，经常需要默认展示第一个选项内容，但是DataEase目前不支持改功能，每次都要手动设置默认选择第一个或者默认不选择。
希望贵团队能够考虑添加该功能。

**Comment by yayanpei** [comment]
感谢您的反馈，过滤组件由于用户的业务场景不同，默认值的选择会存在差异，如果默认展示第一个选项不太合适，因此还是由用户在新建或者编辑组件时，手动设置下组件的默认值。

**Comment by Toy-data** [comment]
只是说在默认值里添加一个可以默认选择第一个的选项

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月16日 9:40
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [dataease/dataease] [Feature]新增筛选条件可以默认选中第一个条件 (Issue #4548)


感谢您的反馈，过滤组件由于用户的业务场景不同，默认值的选择会存在差异，如果默认展示第一个选项不太合适，因此还是由用户在新建或者编辑组件时，手动设置下组件的默认值。

―

**Comment by yayanpei** [comment]
如果组件的选项值不固定，排序后第一个选项值可能是动态变化的，咱们这边的需求是组件默认值动态变化，是吗？

**Comment by Toy-data** [comment]
是的，比如业务的数据是两个月统计一次，那么就需要手动制作两个月的标签，然后筛选条件按照时间倒序排列，这时候就需要默认显示第一个

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月16日 11:13
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [dataease/dataease] [Feature]新增筛选条件可以默认选中第一个条件 (Issue #4548)


如果组件的选项值不固定，排序后第一个选项值可能是动态变化的，咱们这边的需求是组件默认值动态变化，是吗？

―

**Comment by yayanpei** [comment]
好的，您的建议我们已收到并放入需求池中。

**Comment by yayanpei** [comment]
您的需求和建议我们已记录，近期我们主要规划并实施2.0的开发，因此暂不规划实现该需求，issue暂时先关闭，再次感谢您对DataEase的关注和支持。
