### ISSUE TITLE
[Bug] 用户和角色数据重复问题

### ISSUE THREAD

**Issue by limin-fit2** [dataease/dataease#4550]
**DataEase 版本**
v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
离线安装包

**浏览器版本**
版本 109.0.5414.119（正式版本） (arm64)

**Bug 描述**
用户和角色未做椒盐，连续触发保存可以保存多条数据

**Bug 重现步骤(有截图更好)**
1.创建用户和创建角色时候点击确认按钮无反应，则重复点击，最后出现多条数据

![image](https://user-images.githubusercontent.com/61964761/218989707-088bff72-79e9-4634-aaee-e4b58d411a21.png)

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/61964761/218989472-ceb28ad0-87aa-4898-9d02-af0de8201f65.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
