### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by CoFamer** [dataease/dataease#4552]
**DataEase 版本**
v1.18.2

**运行方式**
源码运行

**浏览器版本**
Chrome 110.0.5481.96（正式版本） （64 位）

**Bug 描述**
新建报表生成视图，设置报表样式为深色，可以看到视图报表的左边框明显缺失

**Bug 重现步骤**
![image](https://user-images.githubusercontent.com/50297716/219259644-08b9bef9-21f9-437c-a877-a02505085b9d.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，是否是因为缓存所导致的显示差异

**Comment by CoFamer** [comment]
是否是因为您新建的是Echart视图呢，Echart视图是没有这个问题的，这边在清除缓存后新建AntV视图依然存在这个问题

**Comment by xuwei-fit2cloud** [comment]
您好，我们在windows和mac os下测试了一下我们的在线体验环境 https://dataease.fit2cloud.com，ECharts 和 AntV图库的表格均未复现该问题。您可以在上面的体验环境试试吗？

**Comment by CoFamer** [comment]
好的谢谢您，应该是版本问题导致的
