### ISSUE TITLE
[Bug] 数据同步页面筛选不生效

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4553]
**DataEase 版本**
v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
数据同步页面筛选不生效

**Bug 重现步骤(有截图更好)**
如图 
![image](https://user-images.githubusercontent.com/45852479/219260301-fbb1ee1f-1ff8-4c61-adc8-3e2771170b8f.png)

**Comment by xuwei-fit2cloud** [comment]
我们在该版本的几个环境中，包括在线体验环境 https://dataease.fit2cloud.com ，均未复现此问题。
您可以尝试清理一下缓存，然后试试。

**Comment by xuwei-fit2cloud** [comment]
问题未复现。
