### ISSUE TITLE
[Bug]excel上传数据错误(数值型 会变成 字符，错误的数据

### ISSUE THREAD

**Issue by lin99012018** [dataease/dataease#4555]
**DataEase 版本**
v1.18.2
**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge
版本 106.0.1370.47 (正式版本) (64 位)

**Bug 描述**
excel上传数据错误(数值型 会变成 字符型

**Bug 重现步骤(有截图更好)**
1.
![39dda342e3a1efa076677296ba6eec9](https://user-images.githubusercontent.com/42168092/219296113-9d63d1bd-7a07-4947-9db5-b8137e3b7dbd.png)

2.
![a4dd2dbc0a2657bd20975651fe02452](https://user-images.githubusercontent.com/42168092/219297729-eee92eb4-d4bd-4d46-bd46-566dcf5ebaaa.png)

3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个问题是个已知问题，我们正在修复中，还需要一些时间。
当前版本的临时方案是：您可以在上传数据的时候，先选择好字段的类型，这样DataEase可以正确处理相关类型数据。

**Comment by lin99012018** [comment]
上传数据时候，先改好字段类型为“数值型（小数）”，然后再保存，结果又变成字符型，数据还是错误的。

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是说再平台上修改了类型但是保存后查看数据类型变味了字符类型吗？这个问题倒是在测试环境没有发现，而且我看你的截图本身就是数值类型的，是您的截图不对吗？目前这里的数据类型判断如果是数值类型确实会存在一些问题，但基本上都是判断位日期类型的，我们也在努力完善此处是别的可靠性，感谢你的反馈，如果我理解错误期待你的回复；

**Comment by hzhfit2cloud** [comment]
精简模式遇到了相同的问题，麻烦排查一下是不是精简模式Excel数据存储到Mysql时出现的bug
