### ISSUE TITLE
柱状图颜色设置

### ISSUE THREAD

**Issue by lhy881126** [dataease/dataease#4556]
柱状图现在只能根据值轴设置统一的一个颜色，希望在修改样式时可以设置每根柱都不同的颜色

**Comment by xuwei-fit2cloud** [comment]
您可以试试AntV图库里的分组柱状图，将需要展示的维度拖入到子类别/维度中，如下图所示：
![图片](https://user-images.githubusercontent.com/1892127/219326526-261c4993-1577-4c48-9150-457c4b2bbea8.png)

然后在【样式】里可以对不同的维度值设置不同的自定义颜色。

**Comment by lhy881126** [comment]
这样不行啊老哥，这样图例没法用，而且横向柱状图也没法用这种方式实现。

**Comment by xuwei-fit2cloud** [comment]
您的具体需求是什么？
如果是基础柱状图的话，那确实只能是每个指标一个颜色，否则图例会有问题。

**Comment by yayanpei** [comment]
柱状图设置不同的柱子为不同的颜色，在 1.x 版本不再进行支持，如果有更多的用户需要该功能，我们会在 2.x 的版本迭代中追加该功能，建议您选择其他图形，比如矩形树图、环形图，或者其他更加合适的图形，来实现不同分类显示不同颜色的需求。issue我们先进行关闭，再次感谢您对DataEase的关注和支持。
