### ISSUE TITLE
[Feature]docker-compose脚本添加自动重启配置

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4558]
**请描述您的需求或者改进建议.**
docker-compose-mysql.yml 和 docker-compose.yml 两个文件没有 restart: always ；
虽然Ubuntu 部署无异常，但重启Ubuntu服务器，Dataease 没有跟随启动，
centos7 可以自启动 DataEase，是因为启动脚本写在 /etc/rc.d/rc.local  ， 但Ubuntu 没有 /etc/rc.d/rc.local  

建议：将 docker-compose文件都加上 restart: always

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前DE的脚本中没有直接支持Ubuntu下的service。
您提供的方案在DE服务本身就完全停止的情况下（如执行了service dataease stop，DE相关容器已不存在），DE服务在重启Ubuntu后，也是无法自动启动的。

我们后续会补充一下对Ubuntu系统服务的支持。

**Comment by mfanoffice** [comment]
了解，临时方案只是避免了重启服务器 DataEase 不会跟随启动。没考虑删除容器的场景。
