### ISSUE TITLE
[Feature] english translation

### ISSUE THREAD

**Issue by canob** [dataease/dataease#4560]
**请描述您的需求或者改进建议.**

Is there any idea in the near future to translate the ui of dataease and the docs to english?

**Comment by xuwei-fit2cloud** [comment]
Thank you for your suggestion. Currently DataEase is available for English language switching, but the DataEase related documentation is not yet available in English.
Currently you can access the DataEase documentation through the chrome translation plugin, and we will work hard to complete the translation of the documentation.

**Comment by MichalisDBA** [comment]
Hello. I can not find in the UI how to change the language to English. Can you show us where to change the language via print screens?
