### ISSUE TITLE
[Bug]【数据集】SQL 数据集预览数据报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#4563]
**DataEase 版本**
1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
SQL 数据集加入参数预览数据的时候报错，去掉参数预览就正常。
报错：com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 't.id' in 'field list'

**Bug 重现步骤(有截图更好)**
1.加入参数点击“运行查询”，如下显示：
![image](https://user-images.githubusercontent.com/24768910/219582982-5089a836-59d7-468a-a584-55cea94042a4.png)

2.去掉参数点击“运行查询”，如下显示：
![image](https://user-images.githubusercontent.com/24768910/219583113-ab1fcdde-fee0-46fe-b67a-891b7f4222d0.png)

注意：环境可私聊提供

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，已知问题，目前还在修复中。

**Comment by AndroidBaby1** [comment]
好的，谢谢！

**Comment by xuwei-fit2cloud** [comment]
v1.18.3版本已修复，请更新版本。
