### ISSUE TITLE
[Feature]全球地图能否支持飞线图

### ISSUE THREAD

**Issue by BeatenMo** [dataease/dataease#4564]
因为是外贸公司，客户涉及的国家大概在10个左右，用气泡图其实不一定能很好显示，用飞线图反而能更好展示，而且也会更好看
所以全球地图能否支持一下飞线图，非常感谢

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前我们正在调研流向地图，应该能满足您的需求。

**Comment by BeatenMo** [comment]
大概什么时候会发版本呢？
