### ISSUE TITLE
[Bug] SQL 数据集设置完参数后无法保存问题

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4565]
**DataEase 版本**
v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 110.0.5481.100（正式版本） (arm64)

**Bug 描述**
SQL 数据集设置完参数后无法保存问题

**Bug 重现步骤(有截图更好)**
1. SQL 数据集设置参数，如下所示：
![image](https://user-images.githubusercontent.com/30063018/219602268-a0362c40-aa10-4300-884d-6894f028314d.png)
2. 数据集保存时报错，如下所示：
![image](https://user-images.githubusercontent.com/30063018/219602386-a1b22365-af52-43a4-aca1-c8848e5875a4.png)
3. 后台查看执行 SQL 后，发现拼接的 SQL 变成了如下内容：
`select sys_users_roles.* from sys_user where 'BI'='BI'`
join 表的内容在拼接的时候被删除了。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个问题已经修复，请等待新版本发布。

**Comment by xuwei-fit2cloud** [comment]
v1.18.3版本已做处理，请更新到最新版本。
