### ISSUE TITLE
[Bug]localStroage不足，图表不能正常显示

### ISSUE THREAD

**Issue by alzerwv** [dataease/dataease#4567]
**DataEase 版本**
1.18

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome  版本 109.0.5414.122（正式版本） （64 位）

**Bug 描述**
定时同步，Echars，明细表，如果配置的数据集超过6万条，localStorage不够
**Bug 重现步骤(有截图更好)**
1.创建定时同步数据集
2.创建仪表盘，选择明细表，ECharts，在右侧结果展示中选“全部”数据
3.图表不能正常显示，显示无法正常显示请联系管理员

**Comment by BBchicken-9527** [comment]
感谢反馈，方便截图看一下问题表象吗，还有一些具体的异常

**Comment by xuwei-fit2cloud** [comment]
咱们在localstorage中并不会存储数据，按理来说不会有太大数据量，这块是否有自己二开的内容？
或者联系我们客服人员，提供一下更详细的信息。
