### ISSUE TITLE
[Feature]组件 数值区间 增加小数支持

### ISSUE THREAD

**Issue by penjoyw** [dataease/dataease#4568]
**请描述您的需求或者改进建议.**
组件——数字过滤组件——数值区间    增加小数支持

场景：金融行业对金额做筛选，需要支持到小数（单位：分）

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。

**Comment by yayanpei** [comment]
您的需求和建议我们已记录，近期我们主要规划并实施2.0的开发，因此暂不规划实现该需求，issue暂时先关闭，再次感谢您对 DataEase 的关注和支持。
