### ISSUE TITLE
[Feature]安装脚本中增加安装时最小磁盘空间的限制

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#4574]
**请描述您的需求或者改进建议.**
安装脚本中增加安装时最小磁盘空间的限制
例如说，当磁盘空间小于20G不允许执行DE安装，目前，即使磁盘只有2G，也允许继续安装，但是会安装失败，导致出现反复在值班群里咨询为什么安装失败，如果增加这个提醒，用户可以直观的看到安装失败的原因

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们优化一下脚本。

**Comment by yayanpei** [comment]
该优化已经在完成，您这边升级到1.18.4版本就可以了。
