### ISSUE TITLE
[Bug]文字组件使用MAC的Safari浏览器无法编辑

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4581]
**DataEase 版本**
1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Safari 版本15.6 (17613.3.9.1.5)

**Bug 描述**
文字组件使用MAC的Safari浏览器无法编辑
![image](https://user-images.githubusercontent.com/89771514/220076734-7a5f6f51-1771-4505-9df4-625ba4d88527.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先记录一下。
目前DataEase确实存在一些浏览器兼容性问题，推荐使用基于chromium内核的浏览器。
