### ISSUE TITLE
[Feature]【仪表板】视图矩阵模式也能进行宽高设置

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#4582]
**请描述您的需求或者改进建议.**
视图矩阵模式也能进行宽高设置。

**Comment by xuwei-fit2cloud** [comment]
矩阵模式下，组件只能是最小宽高的整数倍大小，所以在该模式下进行宽高设置是会影响到矩阵模式的正常使用的，我们推荐在悬浮模式下使用宽高设置。

**Comment by yayanpei** [comment]
关于矩阵模式、悬浮模式，已经进行宽高设置等，1.x由于需要兼容用户的历史数据，改造起来难度较大，我们会在 2.0 重构时将这部分重新设计，issue 就先进行关闭了，再次感谢您对 DataEase 的关注和支持。
