### ISSUE TITLE
[Bug]使用MAC的Safari浏览器设置指标卡名称字体不生效

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4583]
**DataEase 版本**
1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Safari 版本15.6 (17613.3.9.1.5)

**Bug 描述**
![image](https://user-images.githubusercontent.com/89771514/220077080-4f1f3e6e-8c27-43cc-ae3a-e8dc94cb9d71.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先记录一下。
目前DataEase确实存在一些浏览器兼容性问题，推荐使用基于chromium内核的浏览器。

**Comment by BBchicken-9527** [comment]
你好，目前暂时不支持mac的字体切换，主要是因为mac字体映射的字体名称不一样，也就是说可能你的字体是存在的但是名称并不是宋体的名称所以找不到。
