### ISSUE TITLE
[Bug]分组柱状图下钻后，显示的数据不对

### ISSUE THREAD

**Issue by haipeng-fit2** [dataease/dataease#4584]
**DataEase 版本**
v1/18/2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行，采用excel数据集

**浏览器版本**
chrome 110.0.5481.100版本

**Bug 描述**
分组柱状图下钻后，显示的数据不对，展示的和透视表不一致

**Bug 重现步骤(有截图更好)**
1.分组柱状图的类别轴-年月，子类别-职位，指标入职人数，钻取-职位》事业部。
<img width="339" alt="image" src="https://user-images.githubusercontent.com/81673899/220081529-f2ef9f59-2d7a-4cd0-9f7d-5286b7e5f00a.png">
透视表数据行年月，数据列职位、事业部。
<img width="346" alt="image" src="https://user-images.githubusercontent.com/81673899/220081487-7e7e9c83-126c-42a4-b3ed-7aad875926f7.png">
职位与事业部的关系
![image](https://user-images.githubusercontent.com/81673899/220081385-cb2d721d-44c0-477e-92a8-98836e0af3dc.png)

2.用2022-11列的数据对比，分组柱状图和透视表数据是一样的
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/81673899/220081979-291d56ad-1d62-4416-8a03-0c9c6ddcd31b.png">

3.下钻后，分组柱状图的数据就和透视表不一样了，并且分组柱状图的标签和提示也不一样
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/81673899/220082646-0860f7f6-5b94-4b53-bb9d-d2d68825de02.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.6已处理，请更新最新版本。
