### ISSUE TITLE
[Bug]存储xss

### ISSUE THREAD

**Issue by Mia0a-hi** [dataease/dataease#4585]
**DataEase 版本**
v1.18.2
**运行方式(安装包运行 or 源码运行 ?)**
DEMO
**浏览器版本**
Google Chrome 110.0.5481.77
**Bug 描述**
仪表盘存储XSS
**Bug 重现步骤(有截图更好)**
1.仪表盘保存修改```propValue:123<audio src=x onerror=confirm('XSS')>```
2.触发payload
![image](https://user-images.githubusercontent.com/40627909/220086680-51eb4695-c733-494d-941b-a1e4115695db.png)
![image](https://user-images.githubusercontent.com/40627909/220086716-f13be59e-03a0-435b-84c3-b08c38af777e.png)
3.漏洞存在成功触发

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复

**Comment by ziyujiahao** [comment]
你好 麻烦把操作步骤在写详细点

**Comment by Mia0a-hi** [comment]
> 你好 麻烦把操作步骤在写详细点

使用postman添加payload即可
