### ISSUE TITLE
[Bug]新建视图计算字段在制作视图时报错

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#4586]
**DataEase 版本**
v1.18.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome  110.0.5481.77

**Bug 描述**
图表操作>视图字段管理，创建新字段（计算规则：${指标名} * 2），制作视图应用新创建字段时报错。

**Bug 重现步骤(有截图更好)**
1. 图表中点击视图字段管理
2. 创建一个新字段，计算规则为：${指标名} * 2
3. 在柱状图视图中应用新创建字段
4. 出现bug

**Comment by xuwei-fit2cloud** [comment]
您好，我们在自己的环境里并没有复现您的问题。
是否方便告知您用的是什么类型的数据源、数据集，在添加完视图字段后，数据集里是否能正常预览到该计算字段的值？
创建视图时出现bug，具体是什么bug？
如果可以的话，麻烦截两张图：新建计算字段的公式图，以及bug报错图。
谢谢。

**Comment by xuwei-fit2cloud** [comment]
由于一段时间内无近一步反馈，该issue暂时关闭。
