### ISSUE TITLE
[Bug]过滤组件进行查询时，明细表中的分页属性失效

### ISSUE THREAD

**Issue by RocketM** [dataease/dataease#4588]
**DataEase 版本**
v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 版本 110.0.5481.77（正式版本） （64 位）

**Bug 描述**
过滤组件进行查询时，明细表中的分页属性失效，固定以20条/页显示

**Bug 重现步骤(有截图更好)**
> [复现链接](https://dataease.fit2cloud.com/link/hEyloREM)（截止2023-2-22 00:00:00）

1.创建明细表，将【样式-分页】属性设为“10条/页”
2.创建任意过滤组件，关联明细表字段
3.保存仪表盘，进入预览模式
4.通过过滤组件进行查询，分页大小变为20条/页
![00cf235c9eb0e34660d7c046fe35e44](https://user-images.githubusercontent.com/29275855/220222685-6a54f510-b3d3-4b12-a7dd-8fe1ff513977.png)
![fd2f84d282be0ff8f0470ed7f08452d](https://user-images.githubusercontent.com/29275855/220222751-63fcc610-5d33-4e98-a80a-ddab09702f81.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.3版本已做处理，请更新到最新版本。
