### ISSUE TITLE
[Question]源码运行时没有找到达梦数据源选项

### ISSUE THREAD

**Issue by naturlly** [dataease/dataease#4589]
本地部署的1.18.2怎么没有达梦数据源的选项

**Comment by xuwei-fit2cloud** [comment]
达梦数据源是以插件的形式来支持的。
DataEase的插件有一个独立工程，达梦数据源的插件地址在 https://github.com/dataease/dataease-extensions/tree/dev/dataease-extensions-datasource/dm。

Linux操作系统的话，执行目录下的build.sh脚本即可生成对应的插件安装包，在DataEase的插件管理里可以进行插件的安装。

**Comment by naturlly** [comment]
达梦插件内置有，我打包传上去的时候提示已经有这个插件了，但是新增数据源的时候并没有达梦的图标选项

**Comment by xuwei-fit2cloud** [comment]
您可以在插件工程中编译好达梦的插件，然后将对应的jar包，包括达梦插件的jar包和达梦数据驱动jar包，放置到 /opt/dataease/plugins/default 目录下。
以1.18.4版本为例，路径为：
/opt/dataease/plugins/default/dm-backend-1.18.4.jar
/opt/dataease/plugins/default/dmDriver/DmJdbcDriver18.jar

然后重启服务即可。
