### ISSUE TITLE
代码，拉取下拉，不是缺少依赖，就是直接报错[Question]

### ISSUE THREAD

**Issue by yololee** [dataease/dataease#4591]
**请描述您的问题.**

**Comment by xuwei-fit2cloud** [comment]
在v1.18分支代码中，backend/pom.xml 里更新了pentaho的仓库地址，更新后为 https://repo.orl.eng.hitachivantara.com/artifactory/pnt-mvn/。
但目前这个最新仓库也是503状态，所以从在线的方式是无法下载到依赖了。

您可以参考[在线文档](https://dataease.io/docs/faq/dev_faq/#1-dataease)，从百度网盘下载。

另外，如果使用的是v1.18分支的代码，依赖中还有些目前还没发版的SDK v1.18.3，您可以下载SDK工程 https://github.com/dataease/dataease-extension-sdk，并切换到对应的v1.18分支，本地执行 mvn install命令即可。
您也可以切换到v1.18.2 的tag来编译运行DataEase，相关的SDK均已上传到中央仓库。
