### ISSUE TITLE
[Feature]后续是否考虑SQL数据集把“表名”作为动态参数进行筛选

### ISSUE THREAD

**Issue by hzhfit2cloud** [dataease/dataease#4599]
**请描述您的需求或者改进建议.**
需求场景：
大部分通信公司数据量很大，表名用日期定义的，所以希望做数据集时能够把【数据库表名】作为动态参数在大屏的过滤组件进行筛选时能够根据不同的日期把不同表的结果展示出来。

现状：
目前 DataEase 中的 SQL 动态传参以及过滤组件只支持字段级过滤，由于表数据量过大若采用 union 把结果拼接起来根据字段过滤会导致查询缓慢甚至崩溃。

期望：
希望之后过滤组件和 SQL 动态传参能支持动态修改数据库表名

**Comment by xuwei-fit2cloud** [comment]
感谢您的反馈，这个功能我们先记录一下，可能在近期还不会做相关的功能支持，等方案确定下来后我们才会做开发排期。
