### ISSUE TITLE
[Bug]编辑视图无法重命名，偶尔按钮会跑偏

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#46]
**DataEase 版本**
v1.0.0

**浏览器版本**
谷歌浏览器 版本 91.0.4472.114（正式版本） （64 位）

**Bug 描述**
视图无法重命名

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/35896106/123499447-5ae80f80-d669-11eb-92b5-4d2eda4dff10.png)
![image](https://user-images.githubusercontent.com/35896106/123499457-6b988580-d669-11eb-9906-1be1a411f6fd.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，视图重命名的功能将在 v1.1.0 中发布，bug 我们将在 v1.0.2 版本中修复

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已支持
