### ISSUE TITLE
[Bug]添加Hive数据源认证方式选择Kerberos时，校验异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4605]
**DataEase 版本**
1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 109.0.5414.119（正式版本） (x86_64)

**Bug 描述**
添加Hive数据源认证方式选择Kerberos时，校验异常
![image](https://user-images.githubusercontent.com/89771514/220534388-fbba50ec-6476-49cc-a359-4bd0be323c0a.png)

本地运行跟踪代码也发现了异常
![iShot_2023-02-22_13 47 40](https://user-images.githubusercontent.com/89771514/220534504-ec2fe8d6-2374-487b-810a-ebc34f108ca9.png)

百度了一下产生的原因：可能是由于引入的jar包不全，解决办法是将hadoop common下的lib文件夹中的所有jar包全部添加至project项目中

**Comment by 15705043110** [comment]
您好，这个BUG有计划多久能解决么

**Comment by BBchicken-9527** [comment]
感谢反馈，你是否添加了hive的驱动呢？Kerberos验证方式需要添加一个自己的驱动，若版本相同的话可以在drivers中找到对应的驱动

**Comment by xuwei-fit2cloud** [comment]
该问题应该是驱动版本的问题，需要通过驱动管理上传对应版本的驱动程序。
