### ISSUE TITLE
[Feature]SQL数据集编辑界面，没有横向滚动条

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4606]
**请描述您的需求或者改进建议.**
SQL数据集编辑界面，执行SQL显示数据，字段过多时，没有横向滚动条，无法查看后面的字段
<img width="1463" alt="图片" src="https://user-images.githubusercontent.com/48307752/220547666-9db99a1b-21cc-4e62-a433-177423e1ba4f.png">

**Comment by xuwei-fit2cloud** [comment]
纵向滚动条滚动到最下方的时候是有横向滚动条的。
这块我们优化一下。

**Comment by maninhill** [comment]
https://github.com/dataease/dataease/releases/tag/v1.18.4

已解决。
