### ISSUE TITLE
[Bug]精简模式部署 csv表导入数据集无数据

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4610]
**DataEase 版本**
1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
精简模式部署模式，数据集 导入 csv表，导入成功，但数据集预览无数据。

**Bug 重现步骤(有截图更好)**
1.simple 模式；
2.准备简单的csv表数据即可；
3.导入数据集，预览无数据；
<img width="1464" alt="图片" src="https://user-images.githubusercontent.com/48307752/220806927-38f6a399-a0dd-477e-be45-176cd65ee02b.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
