### ISSUE TITLE
[Feature]建议后续能基于仪表板进行数据集选择

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#4614]
**请描述您的需求或者改进建议.**
希望后续能够基于仪表板进行数据集选择：
1）当前选择数据集是基于视图选择，真实的使用场景，一个仪表板一般会固定使用几个数据集；
2）当前选择数据集需要从个人有权限的数据集中去挑选，每次选择过程也比较繁琐，需要层层目录点击选择才行；
基于以上建议可通过基于仪表板选择数据集来降低选择数据集的频率。

**Comment by yayanpei** [comment]
感谢反馈，您的建议很不错，我们会优先考虑进行实现的。

**Comment by yayanpei** [comment]
您的建议很不错，我们会在 2.0 重构时参考您的建议进行相关功能的优化，issue我们先进行关闭了。
