### ISSUE TITLE
[Bug]透视表视图设置样式宽度自适应，数据列/维度的表头宽度没有自适应

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4615]
**DataEase 版本**
1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 109.0.5414.119（正式版本） (x86_64)

**Bug 描述**
透视表视图设置样式宽度自适应，添加数据列/维度，表头宽度没有自适应
![image](https://user-images.githubusercontent.com/89771514/220830957-ef48c245-bb20-4fec-940c-a9b28b84e3f4.png)

**Comment by BBchicken-9527** [comment]
目前透视表的表头的可控性较低，我们开会商量一下是否有比较合理的处理方式解决你说的问题，感谢你的支持与反馈

**Comment by xuwei-fit2cloud** [comment]
受限于图库本身，我们暂时没有办法处理。
