### ISSUE TITLE
[Bug] 直连 MySQL 数据集，通过计算字段拼接出日期格式字段后，日期过滤组件筛选不出正确数据

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4616]
**DataEase 版本**
v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 110.0.5481.100（正式版本） (arm64)

**Bug 描述**
直连 MySQL 数据集，通过计算字段拼接出日期格式后，日期过滤组件筛选不出正确数据

**Bug 重现步骤(有截图更好)**
1. 原始数据集如下所示，存在月份字段：
![image](https://user-images.githubusercontent.com/30063018/220833514-e384016f-a093-4d99-a347-c5d62e4e83e5.png)
2. 添加计算字段，拼接 -01 ，字段类型选择日期：
![image](https://user-images.githubusercontent.com/30063018/220833802-9bd9c252-db8d-4322-ba42-621883006f9c.png)
![image](https://user-images.githubusercontent.com/30063018/220833853-6da4f886-afcc-4c4f-b516-2de51b1e4b71.png)
3. 制作仪表板，并且使用年月组件进行数据过滤，过滤组件无法筛选出正确数据：
![image](https://user-images.githubusercontent.com/30063018/220834114-091b3bd0-afd9-42e9-b9ac-54ea6dc35c47.png)
![image](https://user-images.githubusercontent.com/30063018/220834091-4d65e5bc-913d-42bd-a2c0-b51cada9a07b.png)
4. 查看后台执行 SQL 发现，在拼接过滤组件时未对字段进行时间格式化，如下所示：
![image](https://user-images.githubusercontent.com/30063018/220834290-40720007-2f89-4385-aa42-0345ab584658.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
感谢反馈，目前逻辑是需要concat引用字段与计算字段类型相同
如你的这个需要均为字符类型，之后再将计算字段转换为你设想的时间类型，这样就可以了
