### ISSUE TITLE
[Bug]创建仪表板目录时，目录名重复，提示信息有误

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#4619]
**DataEase 版本**
v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
目录名称重复，但是提示信息为：当前“仪表板名称”已经存在，而不是目录名称已经存在。
![image](https://user-images.githubusercontent.com/48945409/220879020-fee8bff5-168c-4d19-9e78-93db031492d1.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下
