### ISSUE TITLE
[Bug] 看板生成应用导出时，携带组件的应用导入新环境会报错

### ISSUE THREAD

**Issue by JunTech** [dataease/dataease#4620]
**DataEase 版本**

dev
**运行方式(安装包运行 or 源码运行 ?)**

源码运行
**浏览器版本**

chrome /edge /firefox
**Bug 描述**
本地环境导出具有组件的看板作为应用，然后导入到新环境，编辑组件会报错（原因是找不到数据集）

**Bug 重现步骤(有截图更好)**
1.添加看板如下，带组件的
![image](https://user-images.githubusercontent.com/54126696/220878398-c5de9ce2-4ac5-433b-945c-d747f1ac97dc.png)
2.导出为应用
3.然后在新环境导入应用，修改组件，会提示报错
![image](https://user-images.githubusercontent.com/54126696/220879091-4e21ad11-75b7-4ce2-bff1-cee16f4b2ae8.png)

**Comment by JunTech** [comment]
可以这样解决
![bc3c7fc188e8b69390bbce23c13df18](https://user-images.githubusercontent.com/54126696/220879306-ad494284-b47c-407f-b3ef-358d7f62c428.png)

**Comment by BBchicken-9527** [comment]
感谢反馈 ，我们验证一下

**Comment by maninhill** [comment]
https://github.com/dataease/dataease/releases/tag/v1.18.4

已解决。
