### ISSUE TITLE
[Feature]【仪表板】公共链接打开的仪表板上面的下载按钮增加权限控制

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#4622]
**请描述您的需求或者改进建议.**
公共链接打开的仪表板上面的下载按钮增加权限控制。

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。

**Comment by yayanpei** [comment]
该功能暂不考虑增加权限控制，原因如下：

1、目前的下载只是仪表板导出为pdf，数据导出的button已经屏蔽，因此不会造成数据的外传。
2、如果是考虑到不想仪表板的pdf外传，感觉也没必要，如果关闭了下载功能，用户也可以通过拍照、截屏的方式获取。
3、如果实在担心pdf的外传，还可以在水印设置中开启水印，这样pdf在流传出去后，可以进行追踪。

issue先进行关闭，再次感谢您对 DataEase 的关注和支持。
