### ISSUE TITLE
[Feature]仪表板添加查询按钮后，过滤组件没有设置默认值时，希望视图可设置进页面不自动请求

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4627]
**请描述您的需求或者改进建议.**
仪表板添加查询按钮后，过滤组件没有设置默认值时，目前会自动请求加载数据，希望视图可设置进页面不自动请求

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。

**Comment by yayanpei** [comment]
感谢反馈，过滤组件是用来过滤视图数据的，如果没有设置过滤值，应该是加载所有数据更加合适，也是常规做法，如果由于没设置默认值，而不请求视图的数据，可能会误导查看仪表板的用户，认为视图的数据为空。如果是由于数据量较大，不想打开仪表板时加载大量数据从而造成卡顿，建议还是通过设置过滤组件默认值的方式，来请求加载少量的数据会更加合适。
