### ISSUE TITLE
[Feature]明细表格的样式设置中，分页数设置希望支持自定义

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4628]
**请描述您的需求或者改进建议.**
明细表格的样式设置中，分页数设置希望支持自定义
目前只有固定的值可选
![image](https://user-images.githubusercontent.com/89771514/221081438-92c1e929-a8e4-416f-afff-20b9ebd1b83a.png)

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。

**Comment by yayanpei** [comment]
已经内置了常见的分页数，考虑到简化使用，暂不考虑支持，issue我们先进行关闭，感谢您对 DataEase 的关注和支持。
