### ISSUE TITLE
[Bug]辅助线设置精度丢失的问题

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4630]
**DataEase 版本**
1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 109.0.5414.119（正式版本） (x86_64)

**Bug 描述**
![image](https://user-images.githubusercontent.com/89771514/221081872-2d7ace08-6203-47ff-9178-8e5d361d6df9.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题方便提供更详细的步骤方便我们后续的复现以及修正吗

**Comment by BBchicken-9527** [comment]
感谢反馈，这个是Echarts图库自身精确问题，如果对精度有明确要求的话建议使用AntV图库
