### ISSUE TITLE
[Bug]视图自定义排序问题，第一次排序点确认是正常的，在点排序进去，不做操作直接点确认，排序就无效了

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4631]
**DataEase 版本**
1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 109.0.5414.119（正式版本） (x86_64)

**Bug 描述**
视图自定义排序问题，第一次排序点确认是正常的，在点排序进去，不做操作直接点确认，排序就无效了
显示的排序还是自定义排序，但是此时自定义排序其实已经无效了
<img width="987" alt="wecom-temp-93257-174fbcf08cf56a313b26b55c244d6c63" src="https://user-images.githubusercontent.com/89771514/221082102-39f186a5-c261-4ff7-9afa-b6248a34513c.png">

<img width="729" alt="wecom-temp-56065-28f4554ac5ac2a5f6e8ad32e08020c38" src="https://user-images.githubusercontent.com/89771514/221082075-5172de32-9ed7-4669-a4aa-c7c3dbac53db.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by maninhill** [comment]
https://github.com/dataease/dataease/releases/tag/v1.18.4

已解决。
