### ISSUE TITLE
[Bug]【视图】CK 数据集两位小数的数值在视图标签处显示多位小数

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#4634]
**DataEase 版本**
1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
CK 数据集两位小数的数值在视图标签处显示多位小数，直连

**Bug 重现步骤(有截图更好)**
数据集：
![image](https://user-images.githubusercontent.com/24768910/221094767-900190c9-d9ec-4408-8a2a-6e96d5bed4d0.png)
视图：
![image](https://user-images.githubusercontent.com/24768910/221094851-90200a45-d594-4654-b666-667f0f7152d2.png)

**Comment by BBchicken-9527** [comment]
这个应该是js精度的问题，已知问题，目前我们也在想解决的方案，感谢你的关注与支持。
