### ISSUE TITLE
[Bug]MySQL定时同步SQL数据集异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4635]
**DataEase 版本**
1.18.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 109.0.5414.119（正式版本） (x86_64)

**Bug 描述**
SQL数据集截图：
![0](https://user-images.githubusercontent.com/89771514/221103080-ed22b171-9d96-4717-a12f-31a648d7e7f7.png)
异常信息截图：
![1](https://user-images.githubusercontent.com/89771514/221103098-0e7e54c7-79ba-4654-9785-6d1f2fb7045d.png)
![2](https://user-images.githubusercontent.com/89771514/221103122-5fe3147b-8024-4b80-b353-720cd924427f.png)
![3](https://user-images.githubusercontent.com/89771514/221103204-51802e5a-54d1-441f-aa77-d7c293f2e6d3.png)
![4](https://user-images.githubusercontent.com/89771514/221103218-aa6a0abf-bc41-4ce3-8436-197c8ce03aa5.png)

数据源为MySQL，数据库版本 5.5，建表语句如下：

CREATE TABLE `zt_task` (
  `id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `project` mediumint(8) unsigned NOT NULL,
  `parent` mediumint(8) NOT NULL DEFAULT 0,
  `execution` mediumint(8) unsigned NOT NULL,
  `module` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `design` mediumint(8) unsigned NOT NULL,
  `story` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `storyVersion` smallint(6) NOT NULL DEFAULT 1,
  `designVersion` smallint(6) unsigned NOT NULL,
  `fromBug` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `fromIssue` mediumint(8) unsigned NOT NULL DEFAULT 0,
  `feedback` mediumint(8) unsigned NOT NULL,
  `name` varchar(255) NOT NULL,
  `type` varchar(20) NOT NULL,
  `mode` varchar(10) NOT NULL,
  `pri` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `estimate` float unsigned NOT NULL,
  `consumed` float unsigned NOT NULL,
  `left` float unsigned NOT NULL,
  `deadline` date NOT NULL,
  `status` enum('wait','doing','done','pause','cancel','closed') NOT NULL DEFAULT 'wait',
  `subStatus` varchar(30) NOT NULL DEFAULT '',
  `color` char(7) NOT NULL,
  `mailto` text DEFAULT NULL,
  `desc` mediumtext NOT NULL,
  `version` smallint(6) NOT NULL,
  `openedBy` varchar(30) NOT NULL,
  `openedDate` datetime NOT NULL,
  `assignedTo` varchar(30) NOT NULL,
  `assignedDate` datetime NOT NULL,
  `estStarted` date NOT NULL,
  `realStarted` datetime NOT NULL,
  `finishedBy` varchar(30) NOT NULL,
  `finishedDate` datetime NOT NULL,
  `finishedList` text NOT NULL,
  `canceledBy` varchar(30) NOT NULL,
  `canceledDate` datetime NOT NULL,
  `closedBy` varchar(30) NOT NULL,
  `closedDate` datetime NOT NULL,
  `realDuration` int(11) NOT NULL,
  `planDuration` int(11) NOT NULL,
  `closedReason` varchar(30) NOT NULL,
  `lastEditedBy` varchar(30) NOT NULL,
  `lastEditedDate` datetime NOT NULL,
  `activatedDate` datetime NOT NULL,
  `order` mediumint(8) NOT NULL DEFAULT 0,
  `repo` mediumint(8) unsigned NOT NULL,
  `mr` mediumint(8) unsigned NOT NULL,
  `entry` varchar(255) NOT NULL,
  `lines` varchar(10) NOT NULL,
  `v1` varchar(40) NOT NULL,
  `v2` varchar(40) NOT NULL,
  `deleted` enum('0','1') NOT NULL DEFAULT '0',
  `vision` varchar(10) NOT NULL DEFAULT 'rnd',
  PRIMARY KEY (`id`),
  KEY `project` (`execution`),
  KEY `story` (`story`),
  KEY `parent` (`parent`),
  KEY `assignedTo` (`assignedTo`),
  KEY `order` (`order`)
) ENGINE=MyISAM AUTO_INCREMENT=109 DEFAULT CHARSET=utf8;

**Comment by ZhaoQian1222** [comment]
这是禅道的数据库
看了下禅道18 windows一件安装包包里是用xampp，里面写的是mysql，select version 出来是MariaDB
但是数据源mysql  mariadb我都测试过 同样的报错。请知悉。
![wecom-temp-1928-8d1ac1507c590e4d4b0e40a26fbb3c8a](https://user-images.githubusercontent.com/89771514/221107927-88e62459-014f-4392-b18b-60e9a1e881b9.png)
![wecom-temp-6200-82260bc86b62b99c335e6842dd231c61](https://user-images.githubusercontent.com/89771514/221107952-626c5b6f-bfbd-429e-94c3-8becacd50621.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，嗯... 你把这个去掉看看呢
![image](https://user-images.githubusercontent.com/84372766/221416738-809f1a8e-b9b8-4794-a176-84bdb1f8d282.png)

**Comment by xzour** [comment]
> 感谢反馈，嗯... 你把这个去掉看看呢 ![image](https://user-images.githubusercontent.com/84372766/221416738-809f1a8e-b9b8-4794-a176-84bdb1f8d282.png)

去掉之后可以查询。

**Comment by ZhaoQian1222** [comment]
不是这个意思的，步骤是这样的哈：
1、添加SQL数据集如图所示
![image](https://user-images.githubusercontent.com/89771514/221452603-3b1483ca-14f4-47cd-af0b-7523babd6510.png)
2、设置定时同步，同步任务异常，查看详情，如图所示
![image](https://user-images.githubusercontent.com/89771514/221452711-acdd59f7-789b-4261-be6e-7fd2509be88a.png)
3、跟踪 dataease 容器中的后台日志，发现同步执行报错信息，如图所示
![image](https://user-images.githubusercontent.com/89771514/221452786-0de9d26e-8ed0-43d2-9c93-6ace044965f1.png)
4、上一步的异常日志中有一条SQL，复制出来，拿到SQL数据集中进行预览，结果也是执行异常，如图所示
![image](https://user-images.githubusercontent.com/89771514/221452919-0c9e4366-c6ce-4b7c-990d-b1edb31bbe46.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们排查一下。

**Comment by maninhill** [comment]
https://github.com/dataease/dataease/releases/tag/v1.18.4

已解决。
