### ISSUE TITLE
[Feature]【视图】柱状图支持百分比排序

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#4636]
**请描述您的需求或者改进建议.**
【视图】柱状图支持百分比排序

**Comment by yayanpei** [comment]
感谢反馈，该需求已经在需求池中。

**Comment by yayanpei** [comment]
支持按照整个柱子的高低进行排序，柱子内堆叠后根据百分比排序图库本身也是不支持的，issue我这边先关闭了，再次感谢您对DataEase 的关注和支持。
