### ISSUE TITLE
[Bug]AntV基础折线图维度+子维度时，折线出现异常情况

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4637]
**DataEase 版本**
1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 109.0.5414.119（正式版本） (x86_64)

**Bug 描述**
AntV基础折线图维度+子维度时，折线出现异常情况
![wecom-temp-110094-77840d94852c4a3993b94e02a1e80ea8](https://user-images.githubusercontent.com/89771514/221108237-79810606-cdda-4c05-8cd5-6493360c5067.png)
![wecom-temp-27227-8829df917b702e194760e7b437eb50fb](https://user-images.githubusercontent.com/89771514/221108256-c15d09b3-5638-444e-8e47-e02df6140452.png)
![wecom-temp-34850-9ce987dcb22b3183f52e1c0ba00e7c2c](https://user-images.githubusercontent.com/89771514/221108272-f323c800-716e-4a4a-8a57-fb211ff50d06.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by An575** [comment]
通过SQL直连（MySql）方式查询出的数据基本都能复现
