### ISSUE TITLE
[Bug] 富文本组件设置字体、修改文字颜色等保存后不生效。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4639]
**DataEase 版本**
v1.18.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 110.0.5481.100（正式版本） (arm64)

**Bug 描述**
富文本组件设置字体、修改文字颜色等保存后不生效。

**Bug 重现步骤(有截图更好)**
1. 添加富文本组件，仪表板-其它-富文本组件，写入一行文字并调整字号及文字颜色
<img width="1478" alt="image" src="https://user-images.githubusercontent.com/30063018/221152939-6929f814-099c-4c63-9b8d-2f2bf2196607.png">
2. 保存后发现不生效
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/30063018/221153032-eead3931-0a17-47bc-b379-771851afc9fb.png">

**Comment by xueqidove** [comment]
> **DataEase 版本** v1.18.3
> 
> **运行方式(安装包运行 or 源码运行 ?)** 安装包运行
> 
> **浏览器版本** Google Chrome 版本 110.0.5481.100（正式版本） (arm64)
> 
> **Bug 描述** 富文本组件设置字体、修改文字颜色等保存后不生效。
> 
> **Bug 重现步骤(有截图更好)**
> 
> 1. 添加富文本组件，仪表板-其它-富文本组件，写入一行文字并调整字号及文字颜色
> 
> <img alt="image" width="1478" src="https://user-images.githubusercontent.com/30063018/221152939-6929f814-099c-4c63-9b8d-2f2bf2196607.png">
> 
> 2. 保存后发现不生效
> <img alt="image" width="1092" src="https://user-images.githubusercontent.com/30063018/221153032-eead3931-0a17-47bc-b379-771851afc9fb.png">

该bug需要编辑富文本（所有编辑操作）后不生效，不要点击其他地方直接点击仪表板保存即可复现，当前解决方案是，修改完成后先点击仪表板上其他任一视图，然后再点击仪表板保存即可生效。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by maninhill** [comment]
https://github.com/dataease/dataease/releases/tag/v1.18.4

已解决。
