### ISSUE TITLE
[Feature]复用其他仪表板文本组件时，能否支持按照源仪表板样式直接复用

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#4640]
**请描述您的需求或者改进建议.**
复用其他仪表板的文本组件时，能够支持用户自行选择按照源或者目的仪表板样式完成复用：
复用源仪表板样式使用场景：几个仪表板共用的一个文本组件，需要保证所有样式内容一致，当在几个仪表板中复用时，整个操作过程比较复杂，需要逐个重新设置。
<img width="364" alt="image" src="https://user-images.githubusercontent.com/60059766/221394725-029bbae7-ee16-4f20-9f41-17a737d0a576.png">

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。

**Comment by yayanpei** [comment]
感谢反馈，该需求暂不考虑去实现，复用也是仪表板中新添加的组件，默认适应当前仪表板的主题样式，保证当前仪表板的各组件风格一致。如果几张仪表板需要保证一个文本组件样式内容一致，建议设置相同的主题，或者通过复制仪表板的方式获取。
