### ISSUE TITLE
[Bug] 系统中的 demo 数据源已删除，升级 1.18.3 版本时服务启动失败。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4642]
**DataEase 版本**
v1.18.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 110.0.5481.100（正式版本） (arm64)

**Bug 描述**
删除 demo 数据源后，服务启动失败。

**Bug 重现步骤(有截图更好)**
1. 系统中的 demo 数据源已删除，升级 1.18.3 版本时服务启动失败，查看后台日志报空指针异常。查看代码后发现，updateDemoDs未对 datasource 做判空。
<img width="932" alt="image" src="https://user-images.githubusercontent.com/30063018/221481683-c9ecfb17-e416-43b1-807f-649f6210af40.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下。

**Comment by maninhill** [comment]
https://github.com/dataease/dataease/releases/tag/v1.18.4

已解决。
