### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by jackieriver** [dataease/dataease#4647]
**请描述您的需求或者改进建议.**
运行失败
SQL 变量只能在 WHERE 条件中使用
可否支持参数在语句中使用

**Comment by xuwei-fit2cloud** [comment]
您好，目前版本对于字段以及表名等还不支持变量。
相关的技术方案还未确定，短期内应该还不会支持。

**Comment by jackieriver** [comment]
不涉及表名 我在查询的过程中使用case when实现列转行的功能

**Comment by yayanpei** [comment]
该需求已经记录在需求池中，近期我们主要规划并实施2.0的开发，因此暂不规划实现该需求，issue暂时先关闭，再次感谢您对DataEase的关注和支持。
