### ISSUE TITLE
[Bug]符号地图出现多位小数展示问题

### ISSUE THREAD

**Issue by luckymuye** [dataease/dataease#4648]
**dataease-v1.18.3-offline.tar.gz**

**运行方式(安装包运行 or 源码运行 ?)**
/bin/bash install.sh

**浏览器版本**
版本 98.0.4758.102（正式版本） （64 位）

**Bug 描述**
符号地图出现多位小数展示问题,
![image](https://user-images.githubusercontent.com/13705194/221519502-d62672a4-5cb4-4763-b490-62d81b26fb28.png)

**Bug 重现步骤(有截图更好)**

1.数据集
select 114.765636 as 经度,	
25.766105 as 纬度,
174 as 数量,
73913.06 as 面积

![image](https://user-images.githubusercontent.com/13705194/221520234-7fb87527-86fc-4d9b-a12e-ecfe349a1dfb.png)

2.经纬度设置
![image](https://user-images.githubusercontent.com/13705194/221520896-c87393c5-95fc-48bb-a9d3-086bb19f74ab.png)

3.展示的数据是这样的，有8位小数。这个小数位数量过多
![image](https://user-images.githubusercontent.com/13705194/221520841-682aca87-1aa6-4b0a-a5d3-71f9f0166ebd.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前符号地图还没有支持数值格式化，我们先记录一下，后期加上支持。

**Comment by luckymuye** [comment]
请问下有这个大概计划安排时间吗？

**Comment by xuwei-fit2cloud** [comment]
应该在近2个版本左右。

**Comment by xuwei-fit2cloud** [comment]
这个问题目前我们有两个解决方案：
