### ISSUE TITLE
[Bug]Kettle内存不释放

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4650]
**DataEase 版本**
1.18.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
测试使用20万数据的表，10个表；
上传 Excel 数据集，Kettle 容器的内存随着上传Excel 数据集的次数二增加；
持续增加到 2.17G，不再增加，但也不会自动释放内存。

希望优化 Kettle 内存自动释放。
<img width="1075" alt="图片" src="https://user-images.githubusercontent.com/48307752/221570310-3cd8900a-6f31-4b8d-a3e4-482ee8f1de20.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，此问题为一直问题，因为这个问题是kettle内部处理导致，我们也在想入手的方案
