### ISSUE TITLE
[Feature]用户不可以在多终端同时登录的设置项

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4652]
**请描述您的需求或者改进建议.**
安全设置的需求：
统一用户在新终端登录，上一个已登录的终端会被下线。
管理员可以设置是否启用此功能。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先讨论一下。

**Comment by yayanpei** [comment]
该需求已经在 V1.18.5 实现，再次感谢您的关注的支持。
