### ISSUE TITLE
[Feature]建议实时进行数据源有效性校验，而不需要手动校验

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#4654]
**请描述您的需求或者改进建议.**

建议在进行数据查询时实时校验数据源有效性。

我发现有一个 SQL 数据集在预览数据和使用此 SQL 数据集创建视图时会提示数据源无效。而实际此时数据源是有效的，我手动校验一次后就可以正常使用了。

问题在于，默认的数据源有效性校验是 30 分钟一次（一般用户可能不会注意到这个设置），如果某一次有效性校验由于网络波动没有成功，那么接下来的 30 分钟相关的数据集全部是不可用状态，只能手动校验一次数据源，这无疑使操作更加繁琐。如果在数据查询时实时校验数据源有效性则可以避免此问题。

<img width="1422" alt="WeChat71aea7a4139f8a97978ded791f782770" src="https://user-images.githubusercontent.com/30886198/221750440-b72ccae4-8ed7-4dc9-8a5f-9ebd6fe32b69.png">
<img width="1417" alt="WeChat587c765ceddefe6ab1e7d01841b77260" src="https://user-images.githubusercontent.com/30886198/221750532-e39642df-bb15-4fef-9cf0-4819887d14cb.png">

**Comment by xuwei-fit2cloud** [comment]
感谢建议。
校验数据源的有效性，在某些网络环境下，或者某些数据源下可能是一个相对较为耗时的操作，我们并不建议频繁的对数据源的有效性进行校验。
但此处我们会优化数据源状态校验的逻辑，尽量让数据源的状态维持最新状态。
