### ISSUE TITLE
[Feature]水波图无法设置数据格式

### ISSUE THREAD

**Issue by 17600120049** [dataease/dataease#4657]
**请描述您的需求或者改进建议.**
![1677567054570](https://user-images.githubusercontent.com/102302189/221778104-005ac65c-72c1-45c0-8839-40079b699f35.jpg)
![1677567054570](https://user-images.githubusercontent.com/102302189/221778147-ae1e0c8b-f43c-446b-85b4-4d83666105f1.jpg)

**Comment by xuwei-fit2cloud** [comment]
您可以参考一下下图：
<img width="388" alt="图片" src="https://user-images.githubusercontent.com/1892127/222020572-51af320c-14a1-406c-8b48-51e5b2d2cb57.png">
