### ISSUE TITLE
[Bug]视图升序和降序点击无效

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#466]
**DataEase 版本**

v1.1.0-rc2

**浏览器版本**

**Bug 描述**
升序和降序点击无效

**Bug 重现步骤(有截图更好)**
1.新建视图
2.选择指标排序
3.选择升序和降序
![image](https://user-images.githubusercontent.com/35896106/127840311-bec4c0ba-9396-4bc3-b126-145a9640b460.png)

**Comment by xuwei-fit2cloud** [comment]
取消username的排序就可以了
