### ISSUE TITLE
[Bug]外部参数解析问题

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4662]
**DataEase 版本**
v1.18.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
配置外部参数，传入不同的值，有些可以解析成功，有些提示“外部参数解析错误未生效，请按规定编码方式传参”。
或者为参数做不同的命名也有此类情况。

经过多轮测试发现，下图中，加密后，长度到蓝色线部分的是正常的，红色线的无法解析成功。
![image](https://user-images.githubusercontent.com/48945409/221786796-9cf0e9c7-1588-4799-a403-2698ccbc129d.png)

未解析成功的错误提示如下
![image](https://user-images.githubusercontent.com/48945409/221786919-c5bd5b27-a8ea-4f23-8c5b-f679dd2bd866.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们排查一下。

**Comment by BBchicken-9527** [comment]
感谢反馈，部分特殊字符需要经过特定处理才可以的，如你上面的+要经过url的encodeURIComponent编码，改为%2
