### ISSUE TITLE
[Bug] tab组件内视图太多移动端展示问题

### ISSUE THREAD

**Issue by JunTech** [dataease/dataease#4667]
**DataEase 版本**
官方演示环境

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
tab组件内视图太多移动端展示太拥挤没法查看图表

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/54126696/221826845-e19d4491-baea-4c1a-8be2-a38285867652.png)

![image](https://user-images.githubusercontent.com/54126696/221826794-6082117c-f2e9-4d73-93fc-245ff9d79e54.png)

2.
3.

**Comment by JunTech** [comment]
![image](https://user-images.githubusercontent.com/54126696/221827108-f7b456a0-f1a3-4317-903e-1f1de7a07705.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前在无此处优化的排期，后续大版本将重新适配移动端内容，尽情期待
