### ISSUE TITLE
[Bug]多个任务同时拉取，经常会导致Doris OOM

### ISSUE THREAD

**Issue by zijin-zj** [dataease/dataease#4668]
**DataEase 版本**
v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**Bug 描述**
机器配置：4核(vCPU)16 GiB
十几个定时任务几乎同时段拉取，坚持两三天后，Doris最终OOM。这种情况已经有1个多月了，本以为升级了新版本定时任务有了分页功能就不会再有这种情况了，但是还是无法避免。

<img width="913" alt="image" src="https://user-images.githubusercontent.com/48403386/221834130-3330ac4c-0e9a-4060-bcf0-dc415c68c9f8.png">

**Comment by zijin-zj** [comment]
重启之后的组件监控：
![image](https://user-images.githubusercontent.com/48403386/221834395-d1443314-6e17-4074-bd85-5b5e79362c33.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，尝试调大dorisfe的jvm参数看看

**Comment by BBchicken-9527** [comment]
感谢反馈，尝试调大dorisfe的jvm参数看看

**Comment by zijin-zj** [comment]
doris-be 的内存一直处于增长的情况 没有下跌

**Comment by zijin-zj** [comment]
![image](https://user-images.githubusercontent.com/48403386/222025290-74f55ee1-9737-4d20-a403-fbf2551dab1d.png)

**Comment by zijin-zj** [comment]
数据定时变更和视图查询的时候才会消耗资源吗 如果定时变更已经结束 内存不是应该会降下来吗

**Comment by zijin-zj** [comment]
建议你们将doris升级到v.1.2.0版本，新版本解决了内存泄漏的bug以及有内存指标监控

https://github.com/apache/doris/issues/16446

**Comment by BBchicken-9527** [comment]
感谢反馈，其实我们是尝试过升级的，但是在升级过程中出现了兼容问题，目前还没有好的解决方案就暂时搁置了；

**Comment by xuwei-fit2cloud** [comment]
由于doris升级是存在特定的升级路径的，跨版本升级可能会出现问题。
考虑到DataEase早期使用的是doris 0.15版本，我们在尝试升级到最新1.2.2后，出现了兼容问题暂时还没有解决。
但用户如果是自己部署的doris，是可以使用1.2.2版本的，DataEase本身完全可以支持v1.2.2版本的doris，只是DataEase本身的安装包在短期内不会对此进行升级。

**Comment by zijin-zj** [comment]
> 
好的，但这种方案涉及到已有数据的迁移，你们有对应的迁移方案吗
