### ISSUE TITLE
[Bug] ClickHouse数据源JDBC连接字符串不生效

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#4669]
**DataEase 版本**
1.18.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome

**Bug 描述**
ClickHouse数据源JDBC连接字符串不生效，使用直连模式，小表可以正常加载，大表不能加载。

**Bug 重现步骤(有截图更好)**
1.
![img_v2_555d7f0e-1250-476f-aac9-46b6c371a25g](https://user-images.githubusercontent.com/40846859/222039401-014b2554-143a-4c1e-b8c5-6909dfc50811.jpg)

2.
![img_v2_97d0a9d7-da32-41a4-b90a-a719bf91561g](https://user-images.githubusercontent.com/40846859/222039451-cd2ec95c-5108-4135-bdcb-91014f32f7b5.jpg)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下，你可以先使用高级设置中的查询超时解决目前情况

**Comment by BBchicken-9527** [comment]
你好，你删掉连接“？”试一下，连接符我们是加好了的

**Comment by xusongtao** [comment]
感谢回复。已再次确认【请求超时时间】和【额外的JDBC连接字符串】均按照您给的方式填写，异常仍然存在，是否还有别的排查思路？请帮忙确认，谢谢。

![img_v2_223b1b2e-6e15-40e3-b3e3-b369cb03366g](https://user-images.githubusercontent.com/40846859/222091210-c7cd4cc6-6865-4e2c-9b8f-4d6a3a2206a2.jpg)
![img_v2_497b2772-3d91-41d2-a4c0-5aefa6d6894g](https://user-images.githubusercontent.com/40846859/222091241-de59401b-86b2-4235-b009-4e30cde41b10.jpg)
![img_v2_2a20cae9-b3d3-432b-9629-746c5bb386dg](https://user-images.githubusercontent.com/40846859/222091262-0e4b594c-4012-491f-86ec-c77e1a769089.jpg)

**Comment by BBchicken-9527** [comment]
你设置的数值太大了，还有我说的不是请求超时时间而是你你要设置参数的数据源中有一个高级设置打开后你就能看到查询超时的设置默认是30秒你可以调整这个数值解决你的问题，这里设置了可以不设置jdbc链接字符串相当于我们帮你做了拼接

**Comment by xusongtao** [comment]
感谢老师，了解了
