### ISSUE TITLE
[Feature]下拉树不支持跨数据集

### ISSUE THREAD

**Issue by jackieriver** [dataease/dataease#4670]
下拉树不支持跨数据集, 使得无法控制同一个仪表盘内的图表, 望支持

**Comment by yayanpei** [comment]
感谢反馈，我们先讨论一下。

**Comment by yayanpei** [comment]
您的需求和建议我们已记录，近期我们主要规划并实施2.0的开发，因此暂不规划实现该需求，issue暂时先关闭，再次感谢您对DataEase的关注和支持。
