### ISSUE TITLE
[Bug]视图级别计算字段做聚合函数操作无法保存

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4672]
**DataEase 版本**
v1.18.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
数据源为直连，数据库为 MySQL。
使用视图级别的计算字段做聚合参数的除法，提示”字段表达式语法错误“。重新找到以前做过的保存的聚合类的计算字段，进入编辑界面原封不动点保存也无法保存成功了。
![image](https://user-images.githubusercontent.com/48945409/222057680-d801da14-453f-449e-b927-0325a78240b2.png)
![image](https://user-images.githubusercontent.com/48945409/222058064-67ac9f95-4bd4-4848-a144-6966494ff406.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，目前数据库函数是无法使用的，将会在下个小版本中修正，期待下载体验

**Comment by maninhill** [comment]
https://github.com/dataease/dataease/releases/tag/v1.18.4

已解决。
