### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by naturlly** [dataease/dataease#4674]
怎么连接达梦数据源
dataease1.18.3  idea本地源码部署
![image](https://user-images.githubusercontent.com/64082313/222082300-3364a045-3c49-45aa-a169-9417a547e7aa.png)

**Comment by xuwei-fit2cloud** [comment]
达梦数据源的支持是以插件形式支持的，源码运行需要自己编译达梦数据源插件。
插件地址：https://github.com/dataease/dataease-extensions/tree/dev/dataease-extensions-datasource/dm

插件的编译与安装，可以参考在线文档：
https://dataease.io/docs/dev_manual/dev_datasource_plugin/#24

**Comment by naturlly** [comment]
![image](https://user-images.githubusercontent.com/64082313/223338150-2b9cddf9-88e1-4c70-a745-27609dfac91e.png)
以插件的形式导入会提示已存在

**Comment by naturlly** [comment]
以插件包导入，会提示已存在这个插件了，达梦插件内置的不能删除
![image](https://user-images.githubusercontent.com/64082313/223340408-9b06e977-c2e5-4d7c-a80e-88e662c4e9d8.png)

**Comment by xuwei-fit2cloud** [comment]
deplicate of #4589

**Comment by QingLiangZhang1** [comment]
解决了吗，怎么解决的？

**Comment by naturlly** [comment]
本地部署会少些包，/opt/dataease/plugins/default 目录下没有拓展数据库的包，
我是重新拉了一个那个一件部署的工程，把那个工程的包拷贝到本地来.
再检查一下这个my_plugin表信息是否与拷贝过来的包相匹配
