### ISSUE TITLE
[Bug]组件查询条件关联数据集sql参数没有反应

### ISSUE THREAD

**Issue by jackieriver** [dataease/dataease#4676]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**
谷歌浏览器

**Bug 描述**
仪表盘的组件发起查询, 关联sql数据集的入参没什么反应 可以确定选择了控制范围

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/24654534/222115735-11bbf98f-ebff-4e42-b4b4-3213cd7955a6.png)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，能详细说明一下入参没有反应是什么意思嘛？是参数化没有参与到查询中？还是选择了备选项视图数据没有显示过滤数据呢？

**Comment by jackieriver** [comment]
https://github.com/dataease/dataease/issues/4685
可以查看这个, 我验证出bug的重现步骤了

**Comment by BBchicken-9527** [comment]
好的 那咱们在#4685中说吧，这个我先关掉好了
