### ISSUE TITLE
[Bug] 升级后，登陆超时时间设置回调

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4678]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
升级后，登陆超时时间设置回调

**Bug 重现步骤(有截图更好)**
<img width="568" alt="image" src="https://user-images.githubusercontent.com/45852479/222312023-5ec5a9d7-edb9-4eac-ae81-92ec9dbef5d1.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，你是之前改过超时时间升级之后又变回默认了是吗

**Comment by MaekBlack** [comment]
> 感谢反馈，你是之前改过超时时间升级之后又变回默认了是吗

是的，修改后进行了升级操作，又被改回去了

**Comment by BBchicken-9527** [comment]
好的，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
