### ISSUE TITLE
[Bug] 视图计算字段页面，编辑-关闭-编辑，编辑页面上的维度指标丢失

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4679]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
视图计算字段页面，编辑页面关闭后再打开，页面上的维度指标丢失

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/45852479/222324250-10a25c9e-03a9-47ca-8a76-773012dba6a4.png)
2.
![image](https://user-images.githubusercontent.com/45852479/222324295-61e380ac-f831-4719-a51a-3080addf2da6.png)

**Comment by xuwei-fit2cloud** [comment]
您好，建议您清理一下浏览器缓存试试。
您也可以在我们的在线体验环境上试试，我们在在线体验环境中没有复现。
环境地址： https://dataease.fit2cloud.com
登录信息： demo / dataease
