### ISSUE TITLE
[Feature]表格类组件支持单元格内换行显示

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#4683]
**请描述您的需求或者改进建议.**
表格类组件支持单元格内换行显示，数据重要，不能缩略展示，且字段内容过多，可以支持换行展示，以显示全部数据

**Comment by yayanpei** [comment]
感谢反馈，您的建议我们已收到。

**Comment by yayanpei** [comment]
该需求涉及到的工作量较大，我们近期主要规划2.0版本的开发，近期暂时不会规划该功能的开发，issue我们先关掉了，再次感谢您的反馈与支持。
