### ISSUE TITLE
[Bug]仪表盘组件先与参数sql拖出来, 筛选条件会不生效, 反着来就是生效的

### ISSUE THREAD

**Issue by jackieriver** [dataease/dataease#4685]
**DataEase 版本**
1.18.3

**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**
谷歌

**Bug 描述**
仪表盘的组件筛选条件对sql数据集(where带参数的)无效

**Bug 重现步骤(有截图更好)**
1. 先创建where带参数的数据集
2. 创建仪表盘, 先拖出文本下拉组件
3. 在拖出视图, 选择带参数的那个数据集, 
4. 下拉组件编辑选择参数, 勾选上面那个参数
5. 开始执行筛选, 就会没什么反应
6. 但是如果上面的步骤, 仪表盘先创建视图, 再拖出组件, 筛选条件就是生效的

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，你那边可以稳定复现吗？清除一下缓存或者使用无痕模式会不会复现？

**Comment by jackieriver** [comment]
![image](https://user-images.githubusercontent.com/24654534/222379406-d0904402-1e4d-4207-819e-7b841631ea80.png)
经过再次测试, 发现当仅勾选参数选项时, 可以生效, 
![image](https://user-images.githubusercontent.com/24654534/222379630-7008a73c-03a6-4a00-b5ee-559ce561bb11.png)
但同时勾选了控制范围, 其他视图, 参数视图就不生效了, 无痕模式下验证的

**Comment by BBchicken-9527** [comment]
按照你说的方法我测试还是正常的，
我的步骤是：
1.创建仪表板后拉取过滤组件并否选参数化选项
2.创建视图
3.修改过滤组件设置将控制范围开启并勾选控制的视图
这个步骤是正确的吗

**Comment by jackieriver** [comment]
步骤是正确的 但尝试一下多几个视图一起控制,我现在的仪表盘有很多视图

**Comment by BBchicken-9527** [comment]
一个过滤组件控制多个视图吗？
