### ISSUE TITLE
[Bug]使用应用时出现报错，无法正常应用

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4686]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
应用以下应用模版时报错，无法应用成功。
![image](https://user-images.githubusercontent.com/48945409/222367492-fc94bf45-f309-4fc5-b950-0205168ba85b.png)

**Bug 重现步骤(有截图更好)**
1.导出应用文件。
![image](https://user-images.githubusercontent.com/48945409/222367817-d2401875-00ed-4d12-a07e-392085c3ddb3.png)

2.该应用所使用的数据库为自带的 demo 数据库。
![image](https://user-images.githubusercontent.com/48945409/222367967-5232f798-1007-4d12-9bf4-9e17ca797f6e.png)

3.将该应用仍然上传到当前环境中，在正式应用时选择 demo 数据源。
![image](https://user-images.githubusercontent.com/48945409/222368228-d979d84f-f10a-47de-a607-b90b17e7dcfd.png)

4.点击保存，出现报错信息如下：
### Error updating database. Cause: java.sql.SQLIntegrityConstraintViolationException: Column 'chart_id' cannot be null ### The error may exist in io/dataease/plugins/common/base/mapper/ChartViewFieldMapper.xml ### The error may involve io.dataease.plugins.common.base.mapper.ChartViewFieldMapper.insert-Inline ### The error occurred while setting parameters ### SQL: insert into chart_view_field (id, table_id, chart_id, `name`, dataease_name, group_type, `type`, `size`, de_type, de_type_format, de_extract_type, ext_field, `checked`, column_index, last_sync_time, o
![image](https://user-images.githubusercontent.com/48945409/222368287-239acb0d-ea2b-496e-bf26-eafd29d0877d.png)

附件：应用文件
[2021年全国GDP数据.zip](https://github.com/dataease/dataease/files/10868937/2021.GDP.zip)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们修复一下，将会在下个版本中修复
