### ISSUE TITLE
[Bug]通过公共链接打开仪表板，echart明细表多列挤在一起

### ISSUE THREAD

**Issue by hu2013** [dataease/dataease#4689]
**DataEase 版本**
v1.18.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 110.0.1587.57

**Bug 描述**
echart表格所有列都挤在左边，没有撑满整个表格区域

**Bug 重现步骤(有截图更好)**
1. 创建仪表板
2. 仪表板中创建echart明细表
3. 创建公共链接，并在浏览器中打开公共链接

**Comment by BBchicken-9527** [comment]
感谢反馈，在没有分享的平台中查看明细表显示的是正常吗？

**Comment by hu2013** [comment]
> 感谢反馈，在没有分享的平台中查看明细表显示的是正常吗？

有时候，也是不正常的，我换了AntV的明细表，现在好了

**Comment by BBchicken-9527** [comment]
其实我们这边是建议你使用AntV图库的，后续后续图表内容也会计划做一些精简，感谢你的反馈与支持，如果没有别的问题我将关闭这个问题。

**Comment by hu2013** [comment]
> 其实我们这边是建议你使用AntV图库的，后续后续图表内容也会计划做一些精简，感谢你的反馈与支持，如果没有别的问题我将关闭这个问题。

好的
