### ISSUE TITLE
[Bug]源码运行不支持达梦数据库

### ISSUE THREAD

**Issue by pageContext** [dataease/dataease#4692]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome 110.0.5481.178

**Bug 描述**
源码运行，数据源不支持达梦数据库，一键部署又支持。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/39287031/222620157-a1a1e254-36b8-45fd-9297-c9490ea4bc65.png)
![image](https://user-images.githubusercontent.com/39287031/222620485-c5541ed3-f741-4172-b53a-470317f9cd01.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，受累看一下执行一下sql看一下：SELECT * FROM  my_plugin;

**Comment by BBchicken-9527** [comment]
如果可能的话希望可以咱们投屏看一下具体的问题

**Comment by pageContext** [comment]
> 如果可能的话希望可以咱们远程投屏看一下具体的问题

找到问题的原因了。源码重新部署，插件会失效，重新上传达梦数据源插件就可以了。但是这个应该算bug吧，插件好像是保存在当前服务器上。如果一套源码在多台服务器上部署，插件都要重新上传一遍。

**Comment by qq54766209** [comment]
> > 如果可能的话希望可以咱们远程投屏看一下具体的问题
> 
> 找到问题的原因了。源码重新部署，插件会失效，重新上传达梦数据源插件就可以了。但是这个应该算bug吧，插件好像是保存在当前服务器上。如果一套源码在多台服务器上部署，插件都要重新上传一遍。

是的，我也遇到了这个问题，我在尝试修复下
