### ISSUE TITLE
[Question] sql select '${}' 去掉校验影响范围?

### ISSUE THREAD

**Issue by jackieriver** [dataease/dataease#4693]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/24654534/222622532-cde85245-5899-482c-a41e-d2ec2e9ee19f.png)
将这里的校验判断去掉 将会影响什么

**Comment by JunTech** [comment]
在那一步之后需要得到的是完整的能执行的sql，不然后面到数据库连接的时候去生成数据集字段会显示sqlprovider连接异常

**Comment by jackieriver** [comment]
那如果字段名是正确的的 应该不会有问题吧

**Comment by jackieriver** [comment]
我的想法是判断一下as 别名替换一下

**Comment by tjlygdx** [comment]
现在没有没有支持在任意地方嵌入sql变量
如果去掉这段代码，但是在不支持的地方使用了sql变量，就会出错

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，因为有些地方不支持使用sql变量，因此为了安全起见，建议不要去掉。如果您这边有需要去掉，您可以尝试看看。issue先进性关闭了，再次感谢您的关注和支持。
