### ISSUE TITLE
[Bug] 仪表盘的外部传参不支持查询sql带参数的数据集

### ISSUE THREAD

**Issue by jackieriver** [dataease/dataease#4694]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1. select * from table1 t where t.column = '${params}' 
2. 配置视图后, 仪表盘的外部参数配置无法绑定到这个参数
3. 外部参数配置参数名与此同名也无法筛选生效
4.

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是说如果外部参数的变量名称和参数化的名称相同就会过滤不了吗？方便问一下提示的异常吗？我这边参数化的变量名是test然后设置了一个外部参数test是没有问题的。
