### ISSUE TITLE
[Feature]柱状图实现钻取后，仪表板间跳转，支持携带多级参数

### ISSUE THREAD

**Issue by jsummer** [dataease/dataease#4695]
**请描述您的需求或者改进建议.**
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/11641557/222666700-a6ce2b69-f2fa-45f8-8cf8-67f500f87250.png">
目前是不会携带多级参数

**Comment by yayanpei** [comment]
感谢您的反馈，我们先讨论一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
