### ISSUE TITLE
直连 Elasticsearch 7.5.2无法创建数据集

### ISSUE THREAD

**Issue by sandy420** [dataease/dataease#4696]
**DataEase 版本**

1.18.3
**运行方式(安装包运行 or 源码运行 ?)**

DOCKER
**浏览器版本**
Google Chrome
版本 110.0.5481.178（正式版本） （64 位）
**Bug 描述**
直连 Elasticsearch 7.5.2无法创建数据集
![image](https://user-images.githubusercontent.com/10955441/223013150-5cdd30a8-8b92-4fe9-81a0-f0bb8e9e5dbf.png)

**Bug 重现步骤(有截图更好)**
1.正常创建了ES数据源后，
![image](https://user-images.githubusercontent.com/10955441/223012193-bdd2ffc9-682a-499a-ab5e-0322d31c4a0e.png)
开始添加数据集，ES索引内容为：
{
  "_index": "applog-2023.03.06",
  "_type": "logs",
  "_id": "keXbtIYBV6XpvdadfKAf",
  "_version": 1,
  "_score": 0,
  "_source": {
    "agent": {
      "hostname": "filebeat-cvv99",
      "id": "a99e1fa0-027a-4237-bf11-38cc1ca16e91",
      "type": "filebeat",
      "ephemeral_id": "fa3a2253-3ec4-44a2-ab7f-507f91935013",
      "version": "7.5.2"
    },
    "@timestamp": "2023-03-06T02:58:42.446Z",
    "level": "INFO",
    "@version": "1",
    "host": {
      "name": "filebeat-cvv99"
    },
    "namespace": "cms",
    "podname": "editor",
    "message": "10:58:38.710 [http-nio-8080-exec-25] INFO  c.c.s.f.s.s.i.SensitiveServiceImpl - 没有配置腾讯ai,调用原ai检查\n10:58:38.711 [http-nio-8080-exec-25] INFO  c.c.spider.utils.HttpClientUtils - 请求url: [http-nio-8080-exec-25] INFO  c.c.spider.utils.HttpClientUtils - 请求参数:{\"content\":\"今日惊蛰，这些知识告诉孩子！\"}\n10:58:39.044 [http-nio-8080-exec-25] INFO  c.c.spider.utils.HttpClientUtils - 请求url:,返回:{\"data\":[],\"message\":\"操作成功\",\"state\":200,\"success\":true}"
  },
  "fields": {
    "@timestamp": [
      "2023-03-06T02:58:42.446Z"
    ]
  }
}
	
2.
![image](https://user-images.githubusercontent.com/10955441/223011929-0e64a7a9-f06f-4cd3-9722-9deac15810e0.png)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我这边验证一下

**Comment by BBchicken-9527** [comment]
你好，目前我们这边尝试复现你说的问题，但是始终没有成功，想问一下是否方便可以远程看一下，确定一下问题到底出在了哪里
