### ISSUE TITLE
[Bug]v1.18.4普通用户导出分享的明细表报错[object Blob]

### ISSUE THREAD

**Issue by 56warmers** [dataease/dataease#4697]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
离线安装，local模式，Docker

**浏览器版本**
Chrome\Edge

**Bug 描述**
v1.18.4普通用户导出分享的明细表报错[object Blob]

**Bug 重现步骤(有截图更好)**
1.管理员分享仪表板
2.仪表板内的明细表（AntV、ECharts均有）导出Excel，功能正常
3.登录普通用户账户，仪表板内的明细表（AntV、ECharts均有）导出Excel，显示[object Blob]报错
![image](https://user-images.githubusercontent.com/56248947/223021623-eda22b7d-a836-4bb6-80cf-fd6d3c19533d.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前分享是最低权限的，是不应该存在导出按钮的，清一下缓存看一下是否还存在这个按钮呢。

**Comment by 56warmers** [comment]
> 感谢反馈，目前分享是最低权限的，是不应该存在导出按钮的，清一下缓存看一下是否还存在这个按钮呢？

公共链接分享才应该是最低权限吧？这个不是已经不支持导出了么？
您误会了，这个不是公共链接分享，是管理员建立的普通用户，有账号密码的那种，登陆后打开管理员分享的仪表板，其中的明细表是无法导出Excel报错的。
如果说是权限问题，那为什么其他表，折线、饼图啥的，都可以正常导出Excel呢？唯独明细表不可以？这个说法太牵强了吧？
ps.这个问题和缓存无关，我在另一台服务器上重新安装了v1.18.4版本，使用默认的示例数据，新建一个仪表板分享给新建的普通账户，依然无法导出Excel，而且其他表都正常。之后我又重新安装了v1.18.3版本，完全不存在这个问题。
目前已经和官方群反馈，有人员回复确认这个问题是存在的，希望能解决在下个版本这个问题。

**Comment by xuwei-fit2cloud** [comment]
我们将在v1.18.5版本中修复。

**Comment by 56warmers** [comment]
> 我们将在v1.18.5版本中修复。

好的，感谢

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
