### ISSUE TITLE
[Bug]数据源是maxcompute，数据明细仪表盘数据显示为空

### ISSUE THREAD

**Issue by rankang666** [dataease/dataease#4698]
**DataEase 版本**
V1.18.

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
google浏览器

**Bug 描述**
数据源是maxcompute，建了一个数据明细的数据集，配置仪表盘后，仪表盘数据显示为空，数据集中可以查看到数据

**Bug 重现步骤(有截图更好)**
<img width="943" alt="ce7ac77f0b36b672de3af0eab442a35" src="https://user-images.githubusercontent.com/43208859/223024732-3c3471b9-7e5b-4e51-8642-db0b3a6903b8.png">
<img width="948" alt="d650a265e976e1fdabab3e7f33b5f71" src="https://user-images.githubusercontent.com/43208859/223024767-9dadd171-2626-4097-84ae-b5b94e54a36b.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，不出意外的话下个小版本就可以的

**Comment by rankang666** [comment]
小版本多久更新一次？

**Comment by BBchicken-9527** [comment]
目前小版本的周期是不定的，但大概月底应该会有一版的

**Comment by rankang666** [comment]
现在可以通过编译源码的方式测试修复之后的版本吗？

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
