### ISSUE TITLE
[Bug]视图点击保存没有反应

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#47]
**DataEase 版本**
v1.0.0

**浏览器版本**
谷歌浏览器91.0.4472.114（正式版本） （64 位）

**Bug 描述**
视图点击保存没有反应

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/35896106/123499477-c0d49700-d669-11eb-9f06-40dc35c1675b.png)

**Comment by xuwei-fit2cloud** [comment]
视图操作是实时保存的，即使不点保存也会自动保存。我们会加上loading界面和信息提示来改善体验。

**Comment by xuwei-fit2cloud** [comment]
v1.1.1 版本已加上保存成功提示
