### ISSUE TITLE
[Bug]MySQL 表中存在0000-00-00 的时间数据时无法创建数据集

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4705]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
数据源是 MySQL;
数据集直连;
则报错：
<img width="1473" alt="图片" src="https://user-images.githubusercontent.com/48307752/223107409-9e0eb4d9-f033-45a2-8f77-2f6fcb5e12a7.png">

**Bug 重现步骤(有截图更好)**
1.MySQL数据库新建表；
CREATE TABLE `kar_meeting` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `lng_lag` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `begintime` datetime DEFAULT NULL,
  `endtime` datetime DEFAULT NULL,
  `sale_id` int(11) DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `createtime` datetime DEFAULT NULL,
  `updatetime` datetime DEFAULT NULL,
  `deletetime` datetime DEFAULT NULL,
  `act_id` int(11) DEFAULT NULL,
  `hospital_id` int(11) DEFAULT NULL,
  `join_qrcode` varchar(255) DEFAULT NULL,
  `material` varchar(255) DEFAULT NULL,
  `join_info` varchar(255) DEFAULT NULL,
  `out_info` varchar(255) DEFAULT NULL,
  `time_json` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

导入数据：
INSERT INTO `kar_meeting` (`id`, `name`, `lng_lag`, `address`, `begintime`, `endtime`, `sale_id`, `status`, `createtime`, `updatetime`, `deletetime`, `act_id`, `hospital_id`, `join_qrcode`, `material`, `join_info`, `out_info`, `time_json`) VALUES (1, '北试试学', NULL, '试关闭维码', '2022-12-08 00:08:00', '2022-12-08 00:13:00', 473, '3', '2022-12-08 00:08:58', '2022-12-08 00:23:01', NULL, 1, 4, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `kar_meeting` (`id`, `name`, `lng_lag`, `address`, `begintime`, `endtime`, `sale_id`, `status`, `createtime`, `updatetime`, `deletetime`, `act_id`, `hospital_id`, `join_qrcode`, `material`, `join_info`, `out_info`, `time_json`) VALUES (2, '北啊啊学', NULL, '十二点试二维码', '2022-12-08 00:08:00', '2022-12-08 00:13:00', 473, '3', '2022-12-08 00:09:00', '2022-12-08 00:23:01', NULL, 1, 4, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `kar_meeting` (`id`, `name`, `lng_lag`, `address`, `begintime`, `endtime`, `sale_id`, `status`, `createtime`, `updatetime`, `deletetime`, `act_id`, `hospital_id`, `join_qrcode`, `material`, `join_info`, `out_info`, `time_json`) VALUES (3, '内方法', NULL, '内蒙古烤全羊', '2022-12-08 00:20:00', '2022-12-08 00:30:00', 3122, '3', '2022-12-08 00:15:23', '2022-12-08 00:30:02', NULL, 1, 3193, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `kar_meeting` (`id`, `name`, `lng_lag`, `address`, `begintime`, `endtime`, `sale_id`, `status`, `createtime`, `updatetime`, `deletetime`, `act_id`, `hospital_id`, `join_qrcode`, `material`, `join_info`, `out_info`, `time_json`) VALUES (60, '电动车院', NULL, '医院', '2023-01-05 08:30:00', '0000-00-00 00:00:00', 3123, '0', '2022-12-27 22:42:52', '2023-02-02 17:23:15', '2023-02-02 17:23:15', 5, 2740, 'https://task-mini.oss-cn-beijing.aliyuncs.com/xcxqrcode/80727b7dd2f7ba7f6d9f2f53dfa86c96.jpeg', NULL, NULL, NULL, NULL);
INSERT INTO `kar_meeting` (`id`, `name`, `lng_lag`, `address`, `begintime`, `endtime`, `sale_id`, `status`, `createtime`, `updatetime`, `deletetime`, `act_id`, `hospital_id`, `join_qrcode`, `material`, `join_info`, `out_info`, `time_json`) VALUES (75, '富贵包院', NULL, '', '0000-00-00 00:00:00', '0000-00-00 00:00:00', 6432, '0', '2022-12-29 13:14:34', '2022-12-29 13:14:35', NULL, 5, 5103, 'https://task-mini.oss-cn-beijing.aliyuncs.com/xcxqrcode/2a5770a25d3f6bdc0086fc9824505dcc.jpeg', NULL, NULL, NULL, NULL);

2.新建直连数据集，复现报错

**Comment by BBchicken-9527** [comment]
感谢反馈，嗯... 你给的这个数据在创建的时候应该就会有问题的。

**Comment by mfanoffice** [comment]
是的，在导入 insert 数据时就会报错，修改 my.cnf 可解决，但用户数据库中原有的数据就是这样，数据集能否兼容这种时间格式

**Comment by BBchicken-9527** [comment]
嗯嗯，那我们优化一下吧

**Comment by xuwei-fit2cloud** [comment]
可以在数据库连接url增加参数zeroDateTimeBehavior=convertToNull
