### ISSUE TITLE
[Feature]希望数据源可以支持一下Phoenix

### ISSUE THREAD

**Issue by youngxiaoyun-it** [dataease/dataease#4706]
1、Phoenix数据源直连和数据抽取；
2、通过Phoenix连接可以查询hbase数据；
3、支持配置phoenix.schema.isNamespaceMappingEnabled和phoenix.schema.mapSystemTablesToNamespace；

**Comment by yayanpei** [comment]
您的需求和建议我们已记录，近期我们主要规划并实施2.0的开发，因此暂不规划实现该需求，issue暂时先关闭，再次感谢您对DataEase的关注和支持。

**Comment by youngxiaoyun-it** [comment]
好的，希望后续能够实现这个功能，目前是我自己写了一个数据源插件，但是自定义的插件数据源不支持定时同步，这个也希望后续能够支持
