### ISSUE TITLE
[Bug]数据同步执行记录导出功能，会报错空指针

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#4708]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
数据同步，在执行记录中点击导出，提示报错，空指针

**Bug 重现步骤(有截图更好)**
1.数据同步，在执行记录中点击导出
![image](https://user-images.githubusercontent.com/57552153/223307334-ce3815f9-a83c-42b3-8542-99f8ed9da80c.png)
2.筛选没有生效

**Comment by s-phenix** [comment]
浏览器版本：
![image](https://user-images.githubusercontent.com/57552153/223310285-7006f258-f2e0-4aa7-8769-1a936bbd59a9.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们尽快处理一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
