### ISSUE TITLE
下拉树组件配合视图使用报错[Bug]

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#4710]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome版本 110.0.5481.177（正式版本） (arm64)

**Bug 描述**
使用下拉叔组件筛选时，视图（sql数据集）报错(测试三种数据源，mysql不报错，ck，sql-server报错，目前测试了三种)

**Bug 重现步骤(有截图更好)**
1.
![51678159913_ pic](https://user-images.githubusercontent.com/109720729/223317644-10bc9f23-1105-4339-ab9e-387e8b2b409c.jpg)

2.
![image](https://user-images.githubusercontent.com/109720729/223317704-cf42dcca-e964-4cba-9717-6a2093116421.png)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快处理

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快处理

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
