### ISSUE TITLE
[Feature] 缩略轴和钻取的联动展示效果

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4714]
**请描述您的需求或者改进建议.**
在配置缩略轴的情况下，有多维度钻取到少维度，依旧保留缩略轴，能否有个可以配置最小展示条目的地方。

**Comment by xuwei-fit2cloud** [comment]
目前来看，我们用的AntV图库中关于缩略轴的接口，还不能支持配置指定数量的数据点，所以我们将保持现有设计不变。
