### ISSUE TITLE
[Bug]编辑手机端仪表板后，重新切换到仪表板显示异常

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#4717]
**DataEase v1.18.4**

**运行方式(安装包运行 or 源码运行 ?)**
离线安装

**浏览器版本**
版本 110.0.5481.178（正式版本） （64 位）

**Bug 描述**
从PC端编辑手机端仪表板后，再次切换到PC端仪表板自适应显示异常

**Bug 重现步骤(有截图更好)**
1.编辑移动端仪表板
![image](https://user-images.githubusercontent.com/43403764/223477058-0a721a8c-b148-401f-beb6-c71d02b04704.png)

2.编辑完成不保存，点击浏览器返回按钮
![image](https://user-images.githubusercontent.com/43403764/223478185-a87c2f7b-666c-43df-9d61-cc9d780cc7f5.png)

3.仪表板显示异常，重新刷新恢复正常
![image](https://user-images.githubusercontent.com/43403764/223477540-dfc60718-8bf6-42fc-b197-90f0f0b8b8c1.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，若在编辑移动端部署的时候点击后退按钮则退出此界面，这个可以稳定复现吗？

**Comment by LinuxLeader** [comment]
编辑移动端，点击后退按钮后，然后随便打开一个仪表板，就可以复现此问题

**Comment by BBchicken-9527** [comment]
你点击浏览器的后退后没有弹窗提示是否退出编辑页面吗？

**Comment by LinuxLeader** [comment]
会提示，是否放弃编辑当前页面，然后选择“确定”，然后再随便打开仪一个表板就会看到那个问题了

**Comment by BBchicken-9527** [comment]
感谢反馈，我们目前正在处理请耐心等候
