### ISSUE TITLE
[Bug] 第一次如果通过企微激活，那么 OIDC 是登录不了的。但是反过来，第一次通过 OIDC 激活，之后在企微里用是没问题的

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4722]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
同时配置企业微信和oidc后，第一次如果通过企微激活，那么 OIDC 是登录不了的。但是反过来，第一次通过 OIDC 激活，之后在企微里用是没问题的

**Bug 重现步骤(有截图更好)**

**Comment by xuwei-fit2cloud** [comment]
第一次用企业微信激活，会新建一个DataEase用户，而第二次通过oidc登录时，是不会创建用户的，所以会报用户已存在。
第一次通过oidc登录时，会创建一个DataEase用户，而第二次通过企业微信登录，会把企业微信绑定在oidc创建出来的用户上。
所以目前的现象是正常的。
