### ISSUE TITLE
[Bug] 下拉框内文本带有 ' ，使用该过滤组件时，该组件所控制的视图报错

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4723]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
下拉框内文本带有 ' ，使用该过滤组件时，该组件所控制的视图报错

**Bug 重现步骤(有截图更好)**
1.![image](https://user-images.githubusercontent.com/45852479/223666180-34dd4811-5a14-4902-9ff6-adb934f86827.png)
2.![image](https://user-images.githubusercontent.com/45852479/223666328-63ba2650-02ca-443c-925b-0a9532e7c9a4.png)
3.![Uploading image.png…]()

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，确实有这问题，我们修复一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
