### ISSUE TITLE
[Feature]人口金字塔

### ISSUE THREAD

**Issue by michmore** [dataease/dataease#4727]
在人口健康领域，常常会用到人口金字塔进行人员性别、年龄的集中展示，这需要用到性别和年龄两个维度，请问能否在下一版本提供支持：
![image](https://user-images.githubusercontent.com/55172288/223722178-2ac9484e-9045-4d7a-88c5-92da8d33e307.png)

**Comment by yayanpei** [comment]
感谢您的反馈，我们需要先讨论并调研一下。

**Comment by xuwei-fit2cloud** [comment]
请升级v1.18.7版本。
