### ISSUE TITLE
[Bug] 定时报告任务执行失败

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4728]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
18.2版本定时任务，立即执行后（发送成功）停用，升级至18.4版本，立即执行发送失败

**Bug 重现步骤(有截图更好)**
1.18.2配置定时任务，测试发送成功后，停用该任务
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/45852479/223903620-beb539b6-7961-4d4a-aece-744e51828461.png">
2.升级至18.4版本
3.无论是否启用该任务，立即执行发送失败
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/45852479/223903772-5809b0e9-0e4b-4bbf-9293-a8bbe9c28538.png">
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/45852479/223903828-5d607e7f-d953-4c1f-b5d0-fd2d24ce9df6.png">

**Comment by BBchicken-9527** [comment]
感谢反馈。目前测试环境没有发现你说的这个问题，方便详细说明一下任务具体的设置嘛？方便我们更好的定位
