### ISSUE TITLE
[Feature]图例顺序调整问题

### ISSUE THREAD

**Issue by 56warmers** [dataease/dataease#4732]
**请描述您的需求或者改进建议.**
目前折线图添加子类别/维度后，在一些条件下无法改变图例顺序，例如：
下图的数据源内，在类别轴 / 维度为升序（日期升序，格式为“%m-%d“）的情况下，2023的数据后于2022年
![image](https://user-images.githubusercontent.com/56248947/223939875-4129dd6e-fdb8-4371-ab02-55ab93ff35f3.png)
此时就无法通过调整子类别/维度的排序，来调整图例顺序（也就是数据源导致只能是2022在前，哪怕调整为降序）
![image](https://user-images.githubusercontent.com/56248947/223940188-6f69bb25-f7e7-4a53-bfb5-095fa6bf93f2.png)
正常情况下（数据源内2022和2023都是01-01开始有数据），就可以通过调整子类别/维度的排序来调整图例顺序

希望后续版本可以有好的方式调整图例顺序

**Comment by 56warmers** [comment]
> 感谢反馈，请问您这边是什么类型的数据源？可能和数据源类型有关，我这边试了excel是可以的，请见下图：
> ![image](https://user-images.githubusercontent.com/84168063/223991571-ac6c832d-8f37-46f5-a8a7-8909fd17ff31.png)
> 

mysql数据源，基础折线图，AntV
。
您误会了，我这边您图上这样的数据源也是可调的。
我说的不可调的例子是：
2022年是从2月才开始有数据，2023年则是1月就开始有数据了。
这样默认按照01-01的日期升序按照年份子分类，也就是01-01开始有两条折线。
那么从01-01开始先有数据的就是2023的数据，所以图例顺序就只会是2023在前，无论如何调整年份排序。
不知道我是否表达清楚了...

**Comment by yayanpei** [comment]
出现这种情况原因是：子维度的排序是基于主维度排序的结果，主维度先进行升序排列，那么1月份排在靠前的位置。基于主维度排序的结果，再进行子维度排序，由于2023年没有1月份的数据，而只有2022年1月份的数据，那么2022年就排在前面了。

如果需要最终的图例2023年展示在前面，那么建议您补充2023年1月份的数据记录，然后将指标的值设置为空。

**Comment by 56warmers** [comment]
> 出现这种情况原因是：子维度的排序是基于主维度排序的结果，主维度先进行升序排列，那么1月份排在靠前的位置。基于主维度排序的结果，再进行子维度排序，由于2023年没有1月份的数据，而只有2022年有1月份的数据，那么2022年就排在前面了。
> 
> 如果需要最终的图例2023年展示在前面，那么建议您补充2023年1月份的数据记录，然后将指标的值设置为空。

了解了，所以希望后续增加图例排序的功能，可以直接在图例选项调整

**Comment by yayanpei** [comment]
收到，近期我们在做大版本的升级，因此暂不考虑优化，issue已经记录，后续我们也会跟进看是否有更加合适的方案，目前状况下，建议您补充2023年1月份的数据记录，然后将指标的值设置为空。

issue暂时先关闭了，再次感谢您对 DataEase 的关注和支持。
