### ISSUE TITLE
[Bug]数值区间区间只能输入整数

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4733]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
如图，数值区间组件只能输入整数，数据集是小数的，也是提示需要输入整数，希望可以精确到小数。
![图片](https://user-images.githubusercontent.com/48307752/223967001-dc15471b-8c73-49ac-8be5-02f06a66d71b.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
