### ISSUE TITLE
[Feature]视图的时间显示类型增加 年月日时 的方式

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4734]
**请描述您的需求或者改进建议.**
视图的时间显示类型增加 “年月日时” 的方式，目前没有
<img width="370" alt="图片" src="https://user-images.githubusercontent.com/48307752/223967588-7dcfa574-fb40-446f-9f84-fca0262a7d7e.png">

**Comment by xuwei-fit2cloud** [comment]
我们处理一下。
