### ISSUE TITLE
[Bug]仪表盘分享给一个用户，分享的用户查看该仪表盘，点导出Excel会报错

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#4735]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
Linux单机版

**浏览器版本**
![image](https://user-images.githubusercontent.com/57552153/223977599-0b05130a-d0e5-4289-b588-e53cc8dca16b.png)

**Bug 描述**
仪表盘分享给一个用户，分享的用户查看该仪表盘，点导出Excel会报错

**Bug 重现步骤(有截图更好)**

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
