### ISSUE TITLE
[Feature]在表格阈值设置中，可以根据两列差值来设置颜色，不是只根据当前列的固定值设置

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#4739]
**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
目前阈值设置的颜色是当前单元格生效的，如果是两列差值的话，影响的是两个单元格，在显示上不确定是否合理。
当前版本中，建议新增计算字段，新计算字段为两列之差，根据新计算字段来设置阈值。

**Comment by hcff2c** [comment]
你好，用户不希望使用计算字段实现，展示上会比较奇怪，不需要直接展示差值，只需要用颜色显示差值范围

**Comment by xuwei-fit2cloud** [comment]
但是这个颜色作用在哪个单元格上呢

**Comment by xuwei-fit2cloud** [comment]
整个阈值设置的交互上都需要有所调整，这个我们先内部讨论一下。

**Comment by yayanpei** [comment]
两列的差值设置颜色，作用到其中一列上，阅读报表时可能会引起歧义，还是建议将颜色设置在差值列上。

该功能我们暂不规划实现，待收集更多相关需求后我们再进行考虑，issue就先暂时关闭了，感谢关注，您的支持是我们不断前进的动力。
