### ISSUE TITLE
[Question]部署以后，创建公共链接，访问公共链接报错

### ISSUE THREAD

**Issue by yp94** [dataease/dataease#4742]
![image](https://user-images.githubusercontent.com/28262260/224202871-5de9cac9-ef20-4ece-be67-17d95935ad9e.png)

**Comment by fit2cloud-chenyw** [comment]
请问您是安装包部署还是源码部署
如果是源码编译部署请参考官网文档https://dataease.io/docs/dev_manual/dev_deployment/compile/
