### ISSUE TITLE
视图插件怎么开发，按照文档的来启动了前端一片空白

### ISSUE THREAD

**Issue by VanLiuZhi** [dataease/dataease#4745]
我看官方后面也想去推这个视图插件市场吧。

我现在把 插件代码 clone 到本地，前端运行成功了，但是页面啥也没有，这样怎么开发调试呢，
是目前的模式只能修改完成，然后打包成插件安装后才能看效果吗？

我建议是插件开发要能看到下面这样的效果，所见即所得，这样才知道改的对不对

![image](https://user-images.githubusercontent.com/22883555/224215759-fe7927b2-e44e-4b94-8e53-2da031346299.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前确实是存在这样的问题。
我们正在大版本中对前端框架这块进行改进，但短期内还无法上线。

**Comment by VanLiuZhi** [comment]
好的，现阶段要开发插件，又不清楚上下文数据结构，也看不到结果，还是很困难的。期待后续完善这块功能和文档，也方便大家开发自己的插件上架到插件市场

**Comment by Rt821940205** [comment]
> 感谢反馈，目前确实是存在这样的问题。 我们正在大版本中对前端框架这块进行改进，但短期内还无法上线。

这个上线时间预估多久

**Comment by yuandajn578** [comment]
同问

**Comment by qingyumonian** [comment]
同问
