### ISSUE TITLE
[Bug]checkApiDefinition对json解析问题

### ISSUE THREAD

**Issue by Silecne666** [dataease/dataease#4747]
**DataEase 版本**
1.18.1

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
111.0.5563.65

**Bug 描述**
 在使用API数据源的时候，新建API数据源，解析字段的时候，其中有一个字段是一个String类型的json字符串，但是把里边具体的值给解析出来了，然后就在创建数据集的时候报错了
具体错误如下：Expected to find an object with property ['prodNum'] in path $['data']['payload'] but found 'java.lang.String'. This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JsonSmartJsonProvider

**Bug 重现步骤(有截图更好)**
1.新建API数据源，然后返回的结果中，某个字段（payload）是String类型JSON字符串
2.在checkApiDefinition接口中，会将该字段下的JSON字符串中的所有字段解析出来，然后勾选了相关字段（ $['data']['payload']['prodNum']）
3.在创建数据集时，就会报错，具体错误为Expected to find an object with property ['prodNum'] in path $['data']['payload'] but found 'java.lang.String'. This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JsonSmartJsonProvider

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们排查一下。

**Comment by tjlygdx** [comment]
能把原始 API 数据贴一下吗？

**Comment by Silecne666** [comment]
{
	"code": 200,
	"data": {
		"termId": "1",
		"userId": "36",
		"time": "2023-03-03T15:30:45.747Z",
		"testMode": "{\"subType\":\"1\",\"prodNum\":\"23\",\"mainProcVer\":\"1\"}",
		"addTime": "2023-03-03 23:30:45",
	},
	"msg": "success",
}
问题主要是针对testMode这个字段，类型是一个jsonstring，就会出现上述问题
目前我的做法是在handleStr中，加了一个判断是否是JSONObject，这样testMode就不会进一步解析了
但是，是否有更好的办法，即是是jsonstring，也能解析出来呢，坐等大神思路

**Comment by BBchicken-9527** [comment]
好的，我们验证一下

**Comment by Silecne666** [comment]
请问一下，这个问题不是说要在1.18.5解决嘛？我看好像没有解决呀

**Comment by tjlygdx** [comment]
> 

没有找到好的处理方式；
加了一个判断是否是JSONObject，这样testMode就不会进一步解析了，这里你是怎么处理的？

**Comment by Silecne666** [comment]
我目前也是判断是否是JSONObject，但是我们这边业务要求，是要对testMode进行解析的，还没较好的处理的方式

**Comment by BBchicken-9527** [comment]
好的，我们会尽快优化此处内容
