### ISSUE TITLE
[Feature]开放数据源的定时同步功能

### ISSUE THREAD

**Issue by youngxiaoyun-it** [dataease/dataease#4748]
1、能够已经支持的直连数据源希望能够都开放定时同步功能；
-- 使用直连进行模板开发完成后转定时同步时发现不支持，很难受
2、对本地上传的插件对应的数据源也开放定时同步功能；

**Comment by yayanpei** [comment]
感谢您的反馈，现回复如下：

1、直连模式创建的数据集解析运用的语法与原数据源是一致的，定时缓存模式是将数据同步至doris数据库了，所以数据集解析用的是doris数据库的语法。两种模式下数据集的解析语法是不一致的，转换后会引发一系列的报错，比如计算字段；两种数据源类型不一致，可能字段类型不一致，都会引发报错。

2、数据源插件是不支持定时同步功能，是因为新的数据源需要在kettle中增加对应的驱动，以及修改相关的代码。如果您这边本地插件需要支持定时同步模式，您可以参考kettle官方进行对接。

**Comment by yayanpei** [comment]
没有收到您的反馈，issue就先暂时关闭了，感谢关注，您的支持是我们不断前进的动力。
