### ISSUE TITLE
[Question] 配置了外部跳转, 但无法关联数据集的参数， 该如何解决？

### ISSUE THREAD

**Issue by huangapple** [dataease/dataease#4749]
![bb5b6eb67b78827698a6d0a2b24717a](https://user-images.githubusercontent.com/10572028/224277696-30f5a136-0a9a-401a-9aff-ea97611820ec.png)
上为 图1

![3cea50c03507138ae53cbcd8d061da2](https://user-images.githubusercontent.com/10572028/224277664-37062c65-b9de-402c-9de6-57ef8e39e121.png)
上为 图2

![82485f19e02c0899f4f63e50575df0a](https://user-images.githubusercontent.com/10572028/224280888-02bfad94-5c46-48f0-a358-fa430d37b310.png)
上为图3

![2c722bfbb9139c4ee1e37d8b179ab20](https://user-images.githubusercontent.com/10572028/224280174-3864a2f6-6f9e-4d6d-8831-00917bade512.png)
 上为图4

-----

我现在有一个列表（如图1），配置了外部跳转，跳转出来的页面（如图2）， 需要传送图3的channelName参数， 但目前无法传递（图4）

该怎么解决？

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，仪表板之间的跳转，您可以在设置跳转时，通过点击渠道名称，触发跳转，那么就会将渠道名称传递给目标仪表板，并影响目标仪表板中视图。
