### ISSUE TITLE
[Bug]明细表对某列添加外部链接后，只有第一页可以跳转，其他页点击无效

### ISSUE THREAD

**Issue by jsummer** [dataease/dataease#4750]
**DataEase 版本**
v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 版本 110.0.5481.100（正式版本） (arm64)

**Bug 描述**
明细表对某列添加外部链接后，只有第一页可以跳转，其他页点击无效

**Bug 重现步骤(有截图更好)**
1.
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/11641557/224463189-592615d4-7d02-4a22-954e-ebeb71032a22.png">
点击可以跳转外部链接
2.
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/11641557/224463216-35546135-b8cd-4913-a566-afee794d8013.png">
点击不可以跳转外部链接

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，该问题已在v1.18.3版本中修复，当前最新版本为 v1.18.4，您可以下载最新版本。
