### ISSUE TITLE
[Bug] 新建完视图计算字段，点击切换数据集，在未选择其它数据集的情况下点击确定，视图计算字段消失。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4751]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 110.0.5481.177（正式版本） (arm64)

**Bug 描述**
新建完视图计算字段，点击切换数据集，在未选择其它数据集的情况下点击确定，视图计算字段消失。

**Bug 重现步骤(有截图更好)**
1. 新建计算字段
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/30063018/224534488-bd724092-50ab-42ad-966b-cbc14340b0fd.png">
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/30063018/224534515-14102539-6896-4e7a-a89a-6e6bd69f413f.png">
2. 点击切换数据集，在未选择其它数据集的情况下点击确定
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/30063018/224534555-b105a7a5-3b82-4586-af55-580a0214cb87.png">
<img width="1478" alt="image" src="https://user-images.githubusercontent.com/30063018/224534602-446370ec-01d1-4e0e-8df0-5b4b3933a37f.png">
3. 视图计算字段消失
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/30063018/224534627-f5af27b4-269d-4c0e-87ff-55d10ee513cd.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
