### ISSUE TITLE
[Bug] 移动端的日期范围组件显示不完整

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4752]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 110.0.5481.177（正式版本） (arm64)

**Bug 描述**
移动端的日期范围组件显示不完整

**Bug 重现步骤(有截图更好)**
1. 如图所示：
![image](https://user-images.githubusercontent.com/30063018/224534867-66a38a74-4ced-43c7-889d-6f4ce02312c8.png)

**Comment by xuwei-fit2cloud** [comment]
目前确实存在这个问题，当前用的日期组件并非移动端适配组件，我们会在后续版本里将这些组件都替换成移动端组件。
但这个工作在近期版本内还不会实施，该需求已记录，暂时先关闭。
