### ISSUE TITLE
[Feature] 应用导出支持导出原仪表板的联动与跳转效果

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4753]
**请描述您的需求或者改进建议.**
应用导出支持导出原仪表板的联动与跳转效果

**Comment by yayanpei** [comment]
感谢您的反馈，我们需要讨论一下。

**Comment by yayanpei** [comment]
在后面发布的小版本中，会支持导出带联动和外部链接跳转的效果，请关注一下release notes，issue我们先关闭了，再次感谢您的关注和支持。
