### ISSUE TITLE
[Feature] 透视表支持配置小计维度

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4754]
**请描述您的需求或者改进建议.**
透视表支持配置小计维度，目前是所有维度都会进行小计，在维度比较多的情况下效果不太好

**Comment by yayanpei** [comment]
感谢反馈，我们需要讨论一下，并调研透视表是否支持按维度配置小计。

**Comment by xuwei-fit2cloud** [comment]
这个目前还不太好实现，我们暂时可能还不能支持。
