### ISSUE TITLE
[Feature] 对于视图结果集的缓存支持配置，直连模式也希望可以支持配置缓存

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4755]
**请描述您的需求或者改进建议.**
目前视图的结果集缓存仅针对定时同步数据集，希望可以支持配置，直连模式也可支持缓存。

**Comment by yayanpei** [comment]
感谢反馈，直连模式不考虑使用缓存视图的结果集缓存，原因如：直连本身是实时查询数据，并在视图中显示数据的最新状态，如果需要用缓存模式，那么建议使用定时同步模式。
