### ISSUE TITLE
[Bug] SQL 数据集创建完后再进行编辑，偶发性页面显示空白

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4756]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 110.0.5481.177（正式版本） (arm64)

**Bug 描述**
SQL 数据集创建完后再进行编辑，偶发性页面显示空白

**Bug 重现步骤(有截图更好)**
1. 详见如下视频，录制环境 ：https://dataease.fit2cloud.com/#/dataset/index
https://user-images.githubusercontent.com/30063018/224536048-8da04fb9-891c-4fc8-b97d-2f393bd11ed6.mov

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，该问题已解决，请等待新版本发布。

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
