### ISSUE TITLE
[Feature] 过滤组件，拖入字段较多时页面优化

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4764]
**请描述您的需求或者改进建议.**
1.页面优化
![image](https://user-images.githubusercontent.com/45852479/224651078-8a51d193-ae8b-44d5-b61a-f70c0bac53ca.png)
2.这个地方数据量不大，但是加载很慢

**Comment by xuwei-fit2cloud** [comment]
收到，我们后续版本优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
