### ISSUE TITLE
[Bug] 删除仪表板目录提示删除仪表板

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4766]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
删除仪表板目录提示删除仪表板

**Bug 重现步骤(有截图更好)**
删除仪表板目录提示删除仪表板
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/45852479/224667805-f7f5fcf2-a2cf-4171-9848-3a90a32250c0.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快优化

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
