### ISSUE TITLE
[Bug] 新用户创建目录需要刷新页面才会显示

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4767]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
新用户创建目录需要刷新页面才会显示

**Bug 重现步骤(有截图更好)**

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
