### ISSUE TITLE
[Bug]使用模板编辑内容会导致原仪表板内容跟随变化

### ISSUE THREAD

**Issue by qiulinjie0327** [dataease/dataease#4772]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**

离线安装

**浏览器版本**
chrome/edge

**Bug 描述**
A仪表板内视图为选项卡时导出为模板，使用模板新建仪表板B，B仪表板选项卡第二个tab页内编辑视图不提示此为模板需替换数据集，且内容修改会导致A仪表板内容跟随变化

**Bug 重现步骤(有截图更好)**
1.新建仪表板A，使用选项卡创建两个或多个tab页，导出为模板
2.使用模板新建仪表板B，修改选项卡内tab页内容
3.回到仪表板A 内容会跟随变化

**Comment by BBchicken-9527** [comment]
感谢反馈，目前没有发现你说的问题， 我创建了一个两个tab页的选项卡，在没有展示的tab页中做了修改并没有发现有什么变化，方便视频或者远程看一下吗

**Comment by qiulinjie0327** [comment]
企业微信联系我
