### ISSUE TITLE
[Feature] 定制图表时，支持用户选择是否对指标进行聚合

### ISSUE THREAD

**Issue by stopit** [dataease/dataease#4773]
**功能**：仪表板-创建视图-堆叠折线图-“值轴/指标”
<img width="269" alt="6f6bf1a8f9acf4642f6cb9047646fb2" src="https://user-images.githubusercontent.com/2113544/224721326-e56a429e-ccd6-46b0-ae53-a63b3ece7dfa.png">

**改进建议**：“汇总方式”中建议增加“无”的选项，表示不对指标进行聚合。

**依据**：
（1）部分数据源中的指标为已经被聚合的数据，不需要再次对指标进行聚合
（2）像es这类对sql支持不太好的数据源，如果对已经定义的sql数据源再使用求和 就会报错
（3）datart中有"数据聚合"的选项供用户选择是否对指标再次进行聚合:
![image](https://user-images.githubusercontent.com/2113544/224724138-50cfd494-6572-4386-a7a1-c4c54b53aa2c.png)

**Comment by yayanpei** [comment]
感谢反馈，我们需要先讨论一下。

**Comment by stopit** [comment]
最近看了腾讯云中的相关产品，也支持用户选择是否对指标再次进行聚合：
![image](https://user-images.githubusercontent.com/2113544/225819344-ee134e97-5b7b-4c84-8ae4-12ff37bb2b33.png)

**Comment by yayanpei** [comment]
感谢反馈，经过讨论，我们近期暂不考虑实现该功能，主要考虑如下：

如果我们增加了该功能，用户在不熟悉“sql分组后，指标是需要求聚合”的情况下，可能会引发更多的报错，比如用户在使用柱形图时，数据源并非聚合后的数据，那么这时选择了不聚合的方式，就会引发报错。此种情况下，程序也无法判定数据源的数据是聚合后还是聚合前的，无法给出相关的提示。

建议您看下是根据哪个字段分组求聚合的，确认下字段类型是否为text，修改为keyword试一下。

**Comment by yayanpei** [comment]
issue暂时先关闭了，再次感谢您对 DataEase 的关注和支持。
