### ISSUE TITLE
[Bug]Maxcompute数据源，使用sql数据集时用变量会报错

### ISSUE THREAD

**Issue by haipeng-fit2** [dataease/dataease#4774]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 111.0.5563版本

**Bug 描述**
Maxcompute数据源，使用sql数据集时用变量会报错

**Bug 重现步骤(有截图更好)**
1. 直接写值是可以的(该列类型是字符串)
<img width="498" alt="截屏2023-03-13 下午10 55 41" src="https://user-images.githubusercontent.com/81673899/224739603-f22e95bf-3965-40ca-9338-e3185a92470e.png">

2.使用变量，点击运行查询时可以查询出来的，但点击保存就会报错
<img width="796" alt="截屏2023-03-13 下午10 56 25" src="https://user-images.githubusercontent.com/81673899/224740151-a020b0ad-953d-48de-89e3-97a8fdd1f9fc.png">

3.报错信息如下：
 failed: ODPS-0130071:[0,0] Semantic analysis exception - physical plan generation failed: java.lang.RuntimeException: Table(market,qinghe_sms_population_stratification_tag3) is full scan with all partitions, please specify partition predicates.
提示语句是全表扫描

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
> 感谢反馈，我们验证一下
