### ISSUE TITLE
[Feature]SQL数据集不会同步sql中的字段注释(comment)

### ISSUE THREAD

**Issue by haipeng-fit2** [dataease/dataease#4775]
**请描述您的需求或者改进建议.**
v1.18.4版本

在使用sql数据集时，不会自动把sql中的字段注释同步到de中，需要到字段管理中一个个字段改，当字段很多时就加大了很多工作量

**Comment by yayanpei** [comment]
感谢反馈，请问字段注释是指数据源表中的description吗？目前sql数据集是拿不到的，如果您这边有好的建议，欢迎您随时与我们交流。

**Comment by haipeng-fit2** [comment]
就是mysql数据源中表的字段注释信息，可以通过show full colums from 表名 查看到的comment列。
我能想到的就是把information_schema库的columns表中的column_comment列的内容与别的表的列名做关联查询，这需要用到存储过程或函数，但目前sql数据集还不支持存储过程。暂时也想不到好的解决办法😂（这个需求优先级不高）


------------------ 原始邮件 ------------------
发件人: yayanpei ***@***.***&gt;
发送时间: 2023年3月14日 09:31
收件人: dataease/dataease ***@***.***&gt;
抄送: haipeng-fit2 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [dataease/dataease] [Feature]SQL数据集不会同步sql中的字段注释(comment) (Issue #4775)





 
感谢反馈，请问字段注释是指数据源表中的description吗？目前sql数据集是拿不到的，如果您这边有好的建议，欢迎您随时与我们交流。

**Comment by yayanpei** [comment]
该功能近期我们没有规划实现，issue就先暂时关闭了，感谢关注，您的支持是我们不断前进的动力。
