### ISSUE TITLE
[Bug] 仪表板文本下拉组件（多选）右侧滚动条一直虚化滚动

### ISSUE THREAD

**Issue by pangzhili** [dataease/dataease#4776]
**DataEase 版本**
V1.17存在，当前官网上最新部署版本也存在

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome

**Bug 描述**
仪表板中文本下拉组件(多选)中如果可选项仅有8个值时，下拉文本后一直将滚动条移动到最下方会出现滚动条一直虚化滚动的问题。

**Bug 重现步骤(有截图更好)**
1. 新建SQL数据集(省份名称有八种结果)
   select *  from area_mapping where province_name in ('内蒙古自治区','辽宁省','黑龙江省','安徽省','河北省','浙江省','河南省','北京市')
2. 新建仪表板
   拖入文本下拉组件，选择上述数据集，province_name字段，多选。
  
  ![image](https://user-images.githubusercontent.com/46517296/224878090-f8e2f220-ced6-463a-b3a1-062d49a065be.png)

4. 下面显示的下拉框中滚动条一直虚化滚动
   
   ![image](https://user-images.githubusercontent.com/46517296/224878197-e6d3985d-7e30-4b17-b28d-ec3b317cc33a.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by BBchicken-9527** [comment]
嗯嗯，我们优化一下
