### ISSUE TITLE
[Bug]环形图显示异常

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#4780]
**DataEase 版本**
1.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 110.0.5481.177（正式版本） (arm64)

**Bug 描述**
使用antv的环形图的时候，指标差距过大，标签会有重叠，echarts会看不见占比小的

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/109720729/224907804-75551217-c21c-4f47-b8a3-1e4e47d19492.png)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前标签的具体位置我们是没有可操作的空间的，建议将环形图弄小一些，这样指标会显示的会好一些
