### ISSUE TITLE
[Feature]日期范围组件在移动端上显示不全

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#4781]
**请描述您的需求或者改进建议.**
日期范围组件，在手机端 展示不全 这个问题有反馈修复吗？目前部署版本v18.1

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这是个已知问题。
目前移动端使用的组件并非移动端适配的，所以会有问题。
我们会在2.0版本中统一对移动端组件进行替换。

**Comment by yayanpei** [comment]
issue我们就先关闭了，再次感谢您对 Dataease 的关注和支持。
