### ISSUE TITLE
[Bug]配置列权限时，要保存后第二次打开规则的配置才会出现

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4789]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
配置列权限时，勾选完字段，配置规则并未显示，需要先保存该列权限，再编辑才能配置规则。

**Bug 重现步骤(有截图更好)**
1.新增列权限
![image](https://user-images.githubusercontent.com/48945409/225184339-82b96d5c-0659-444b-9966-0559fce3b4a8.png)

2.保存列权限后重新点【编辑】打开
![image](https://user-images.githubusercontent.com/48945409/225184983-f44bb20f-dd06-4e9a-829e-e4cf9d1d5c25.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前设计是这样的，权限控制这里我们认为是需要非常谨慎的操作，所以在操作的路径上做的相对复杂了一些，不过就想你说的确实会给体验造成一些不好的体验，这个问题我已经记录了，会在例会中和交互讨论一下是否需要重新设计这里的操作路径；
