### ISSUE TITLE
[Feature] 过滤组件期望支持placeholder自定义

### ISSUE THREAD

**Issue by pwjack** [dataease/dataease#4791]
**请描述您的需求或者改进建议.**
为了更好的用户体验，期望对过滤组件可以自定义placeholder，让用户一眼就明白这个操作是过滤的什么内容。

**Comment by yayanpei** [comment]
感谢反馈，目前是不支持设置的，建议您先通过组件的标题来明确过滤内容，我们近期增加一下配置项。

**Comment by yayanpei** [comment]
已经规划在最近的小版本中了，issue我们就先关闭了，感谢关注，您的支持是我们不断前进的动力。
