### ISSUE TITLE
[Bug]列权限配置自定义脱敏规则后，图表显示问题

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4792]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
配置完脱敏规则后，柱状图显示变成了一条柱子，汇总表显示未做汇总，记录数全部为 1。
脱敏规则设置如下：
![image](https://user-images.githubusercontent.com/48945409/225231992-056d4506-e189-437c-b094-6d9253da9c71.png)
柱状图显示如下：
![image](https://user-images.githubusercontent.com/48945409/225232155-789e7259-0dae-4723-afa5-415b56109387.png)
汇总表如下：
![image](https://user-images.githubusercontent.com/48945409/225232261-12723dd2-aa4e-4b65-a263-ba4c95e6a31b.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前脱敏数据是不支持聚合类型的图表的；
