### ISSUE TITLE
[Bug] 精简模式下，上传 Excel 文件文件时，空值会被置为0

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4793]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 111.0.5563.64（正式版本） (arm64)

**Bug 描述**
精简模式下，上传 Excel 文件文件时，空值会被置为0

**Bug 重现步骤(有截图更好)**
1. Excel 文件如图所示，存在空值
<img width="228" alt="image" src="https://user-images.githubusercontent.com/30063018/225272611-60ed2ffb-4452-409a-9e0c-86fc273c03ff.png">
2. 文件上传后，空值变为 0 
![image](https://user-images.githubusercontent.com/30063018/225273175-513aeb12-3bb3-4b7a-80d7-ca7324020877.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们讨论一下如何优化此处
