### ISSUE TITLE
[Question]没有找到连接excel数据源的地方

### ISSUE THREAD

**Issue by siknet** [dataease/dataease#4794]
**请描述您的问题.**
是我打开方式不对吗？还是SQL Server方式连接？

**Comment by xuwei-fit2cloud** [comment]
您可以参考一下我们的在线文档：
https://dataease.io/docs/user_manual/dataset_configuration/dataset_Excel/

如果在使用中还有其他问题，欢迎您在此咨询。
为了更快的得到响应，您也可以扫码加入我们的社区用户微信群：
![图片](https://user-images.githubusercontent.com/1892127/225486865-b6f23197-1fa3-4535-b650-3cf2413d87a8.png)
