### ISSUE TITLE
[Bug]Excel 数据集替换后界面显示字段类型与数据库不一致问题

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#4796]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 最新

**Bug 描述**
替换 Excel 数据集后若替换时的字段类型与第一次上传时的字段类型不一致，则会导致界面显示的字段类型与 Doris 中存储的字段类型不一致。
比如，第一次上传字段 a 是数值格式，第二次上传字段 a 改成文本格式（由于字段内有空值，导致自动识别为文本类型了），第二次上传后，在字段管理界面显示字段是数值格式，但是 Doris 中的字段类型是 TEXT 格式，导致使用 SUM 等函数会报错。

**Bug 重现步骤(有截图更好)**
1. 使用如图数据创建 Excel 数据集
![image](https://user-images.githubusercontent.com/30886198/225576344-fadb7257-0039-447a-a85b-ddbdd4e87564.png)
![image](https://user-images.githubusercontent.com/30886198/225576113-a404633f-852a-4cbd-b02f-0b1324ed87e1.png)
2. 替换 Excel 数据集，将 a 字段改为文本类型
![image](https://user-images.githubusercontent.com/30886198/225576545-98ca82a7-1032-4819-aac2-b172c2bdcffc.png)
3. 此时字段管理界面显示 a 字段是数值类型 
![image](https://user-images.githubusercontent.com/30886198/225576698-05c05849-0524-4578-91b6-06549c9e6898.png)
4. 但 Doris 中的字段类型是 TEXT 类型
![image](https://user-images.githubusercontent.com/30886198/225577370-77a36e05-69da-4005-8c70-5da19935c419.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
