### ISSUE TITLE
[Bug] 未授权上传文件导致XSS漏洞

### ISSUE THREAD

**Issue by hbdxmz** [dataease/dataease#4798]
**DataEase 版本**
v1.18.4

**Bug 描述**
文件上传未作权限校验，未登录用户可以直接向后台上传任意文件，文件类型未作校验，可以上传任意类型文件

**Bug 重现步骤**
漏洞接口：static/resource/upload/
1. 向static/resource/upload/接口上传一个html，html中的js用于弹出cookie，我把cookie删除了，任然可以上传成功
![image](https://user-images.githubusercontent.com/94107024/225582741-ffb56926-5e24-4ab6-8dae-a1068f1b5b09.png)

3.上传文件名为b1ace870-c3d6-11ed-9218-a9fe7c2f5491，文件名不重复即可

4.文件上传后存储在了static-resource目录，访问http://192.168.253.1:8091/static-resource/b1ace870-c3d6-11ed-9218-a9fe7c2f5491.html

弹出了cookie信息，形成存储XSS漏洞
![image](https://user-images.githubusercontent.com/94107024/225583171-3a5d7da3-abd5-4850-8a44-6e242140e3f6.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
