### ISSUE TITLE
[Bug]在含有group by的SQL数据集中使用参数后查询报空指针

### ISSUE THREAD

**Issue by Huzhangs** [dataease/dataease#4799]
**DataEase 版本**
v1.18.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器，版本 111.0.5563.65（正式版本） （64 位）

**Bug 描述**
在含有group by的SQL数据集中使用参数后查询报空指针，去掉group by之后查询正常

**Bug 重现步骤(有截图更好)**
1.在数据集中新建一个sql数据集（不包含group by），设置参数范围，此时查询是可以查询到结果的
![image](https://user-images.githubusercontent.com/41146743/225783816-031aeb36-f7de-4418-80bd-aa474715ab40.png)
2.在第一步中新建的sql数据集加上group by，再设置参数范围，此时查询就会报错
![image](https://user-images.githubusercontent.com/41146743/225784027-882322f2-ecd6-4762-8c6e-9d42cfe3fcc6.png)
3.此时查看服务器上dataease的日志，报错为空指针
![lQLPJxSnpnIttyDNAyHNBTGwXn5wLLqT2-oEDOJnCIAVAA_1329_801](https://user-images.githubusercontent.com/41146743/225785228-50fa809a-e5dc-4700-99ab-04358da2fd65.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们排查一下

**Comment by Huzhangs** [comment]
你好，该问题已经提出两周了，请问您这边有什么进展吗？

**Comment by BBchicken-9527** [comment]
你好，之前排查没有发现你说的问题因为一些事情就没回你实在不好意思，方便wx联系一下吗，这样询问一些细节会比较方便，如果方便的话受累说明一下你在那个群我加一下你

**Comment by Huzhangs** [comment]
我在29群，你在群里说下我加你，谢谢

**Comment by BBchicken-9527** [comment]
好的，企业微信群29已经说了受累有时间看一下

**Comment by Huzhangs** [comment]
谢谢！

**Comment by Huzhangs** [comment]
你好，请问下这个问题现在有进展吗？

**Comment by BBchicken-9527** [comment]
感谢反馈，目前问题已经提交到开发，但由于目前工作重心主要放在后续的大版本上所以处理可能存在延后实在抱歉，我会和开发沟通尽快处理你这边的问题；之前我记得咱们也加过微信，修改完成后我也会第一时间在微信中和你说明；

**Comment by Huzhangs** [comment]
好的，谢谢

**Comment by BBchicken-9527** [comment]
抱歉，目前经过我们讨论这里的功能无法实现，问题已加入到问题池中，后续中若有良好的解决方法将会再进行处理；
