### ISSUE TITLE
dataease前端有支持vue3版本的计划吗

### ISSUE THREAD

**Issue by bingLAN** [dataease/dataease#4800]
相较于vue2，vue3版本在开发效率可读性以及部分性能上都有提升，现在使用的也越来越多。dataease有升级到vue3版本的计划吗？

**Comment by xuwei-fit2cloud** [comment]
感谢建议！
我们在后续的2.0版本中，会用vue3进行前端开发。

**Comment by aoyeQ** [comment]
> 感谢建议！ 我们在后续的2.0版本中，会用vue3进行前端开发。

请问2.0版本预计什么时候上线呢？
