### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by zhoujiuan** [dataease/dataease#4801]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
谷歌

**Bug 描述**
创建关联数据集的时候，选择ABC3个表关联，进行字段选择的时候选择展示了A表部分字段，C表部分字段，B表字段没有进行选择，保存报错

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/18531413/225791695-5ae24edf-6f9e-417e-864a-4f2eef0b44a1.png)

2.
![image](https://user-images.githubusercontent.com/18531413/225791712-75d3b3e2-2873-4018-ac2c-c5ce55414633.png)

3.
![image](https://user-images.githubusercontent.com/18531413/225791736-6d8c2aab-cee5-4787-8e04-6c0c95a708cd.png)

4.
![image](https://user-images.githubusercontent.com/18531413/225791782-953b4664-854a-4de6-8ed9-9857b06d7306.png)
5.
![image](https://user-images.githubusercontent.com/18531413/225791897-dd60a963-0bea-4a33-90df-022338b8a5e6.png)
解决办法：
![image](https://user-images.githubusercontent.com/18531413/225792060-58c8dc7d-67e8-4227-83f6-00aa6762b578.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快优化

**Comment by BBchicken-9527** [comment]
目前问题已修复，可以下载新版本体验
