### ISSUE TITLE
[Feature]仪表板跳转按钮的设计

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4802]
**请描述您的需求或者改进建议.**
目前 DE 没有一个按钮跳转到仪表板，可以为 文本卡 增加跳转功能来实现，用户点击文本卡，就可以跳转到指定仪表板。
<img width="393" alt="图片" src="https://user-images.githubusercontent.com/48307752/225792392-798652d9-03c0-419a-9595-1cb9a91568c5.png">

**Comment by xuwei-fit2cloud** [comment]
我们先内部讨论一下。

**Comment by a616766585** [comment]
其实是需要的，甚至还需要轮动之类的
