### ISSUE TITLE
[Bug]公共链接通过https+端口访问，跳转页面会抹掉端口，导致访问失败

### ISSUE THREAD

**Issue by 56warmers** [dataease/dataease#4805]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
离线安装本地模式

**浏览器版本**
Edge/Chrome

**Bug 描述**
1. https访问de，分享仪表板的公共链接
![image](https://user-images.githubusercontent.com/56248947/225830362-c5fe5c51-b84d-4025-8bf8-ea06ce78f4e4.png)
2. 浏览器访问该分享链接
![image](https://user-images.githubusercontent.com/56248947/225831032-19ff7b3f-e900-45cf-b6b2-eaf298de25a6.png)
3. 跳转链接后，端口号消失，导致访问失败
![image](https://user-images.githubusercontent.com/56248947/225830855-740f2ed3-1b19-45d0-b532-0e89c6968799.png)

**Comment by 56warmers** [comment]
4. 手动将跳转链接修改，增加端口号并更改协议为https，可以访问
![image](https://user-images.githubusercontent.com/56248947/225832025-cc6cf4cb-1943-4a1e-a3a8-c617dcc1ba70.png)

**Comment by 56warmers** [comment]
> 感谢反馈，请问你是前后端分离部署的吗？

docker部署，mysql和kettle都是容器集成的

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你中间的代理配置方式是什么？可能和此处有关。

**Comment by 56warmers** [comment]
> 感谢反馈，请问你中间的代理配置方式是什么？可能和此处有关。

域名+端口的nginx转发。
具体是域名指向公网IP，交换机分配公网IP+端口指向内网IP+端口，最后nginx转发。

**Comment by jsummer** [comment]
> > 感谢反馈，请问你中间的代理配置方式是什么？可能和此处有关。
> 
> 域名+端口的nginx转发。 具体是域名指向公网IP，交换机分配公网IP+端口指向内网IP+端口，最后nginx转发。

+1
