### ISSUE TITLE
[Feature]表格类视图样式支持斑马纹效果

### ISSUE THREAD

**Issue by lyons-hz** [dataease/dataease#4806]
**请描述您的需求或者改进建议.**
目前表格类视图的样式只能设置表格和表头的背景，希望可以设置斑马纹效果，或者背景色可以隔行显示，更加符合审美习惯。
表格类组件一般也有相关属性支持。

**Comment by xuwei-fit2cloud** [comment]
DataEase表格部分使用的是AntV的S2组件，若S2支持的话，我们在后期是可以加上的。

**Comment by xingwanying** [comment]
S2 支持的哦
https://s2.antv.antgroup.com/api/general/s2-theme#celltheme
![image](https://user-images.githubusercontent.com/10885578/234465458-e8739f46-3343-4a25-91b1-998cd9076816.png)
