### ISSUE TITLE
Windows 离线安装  docker  报错  启动不了

### ISSUE THREAD

**Issue by lucktoo** [dataease/dataease#4810]
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

**Comment by xuwei-fit2cloud** [comment]
看着像是docker服务没启动报的错。
可以查看一下docker desktop的状态。

**Comment by BBchicken-9527** [comment]
感谢反馈，你可以先看一下我们的安装文档，可能是docker没有安装成功，也可能是docker安装成功后没有起来，单纯从错误无法判断你是那种情况，所以建议你先看一下具体事哪里出了问题，或给出更详细的说明，看见一先看一下我们的安装文档尝试一下https://dataease.io/docs/installation/offline_installation_windows/

**Comment by BBchicken-9527** [comment]
你好，不知道是否解决了你的问题呢？如果没有其他问题我们将在今天下午三点后进行关闭。
