### ISSUE TITLE
[Bug] Excel 存在无数据单元格时，数字列会前移，与标题不对应问题

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#4815]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 最新

**Bug 描述**
Excel 表格中 H 列和 I 列格式为文字，存在无数据的单元格，J 列为数字，全部不为空。
上传至 DataEase 后，当 H 列或 I 列为空时，J 列的数字会向前移动至 H 列或 I 列。

**Bug 重现步骤(有截图更好)**
1. 创建 Excel 数据集，附件：
[dataeaseIssues.xlsx](https://github.com/dataease/dataease/files/11013348/dataeaseIssues.xlsx)

2. 上传时预览数据没有问题： 
![image](https://user-images.githubusercontent.com/30886198/226237998-8d7e4220-7060-40ef-9371-85dd3a9dcc6b.png)

3. 上传后预览数据集时数据错列：
![25891679280640_ pic](https://user-images.githubusercontent.com/30886198/226237798-4fa34bd0-9afd-4890-9e6e-fee62da4e859.jpg)

4. 实际数据：
![image](https://user-images.githubusercontent.com/30886198/226237874-2b1f07bc-0d92-49b4-b321-9f8b08e5d4d3.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
