### ISSUE TITLE
[Bug]选项卡预览时无法完整显示指标卡内容

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4817]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
编辑状态下，选项卡中放置指标卡，正常显示，回到预览状态，选项卡无法完整显示指标卡，因为指标卡被拉长了；
<img width="1460" alt="图片" src="https://user-images.githubusercontent.com/48307752/226245047-0d4f4b7a-4420-4e46-afc4-b7d81514a6da.png">
<img width="1234" alt="图片" src="https://user-images.githubusercontent.com/48307752/226245084-d6b4698e-4ded-4287-bdfa-cff1704c40a9.png">

**Bug 重现步骤(有截图更好)**
1.加入选项卡，选项卡上下高度调小一些，如下图：
<img width="1474" alt="图片" src="https://user-images.githubusercontent.com/48307752/226245161-d6e3dfbf-bf2f-42b6-b950-09b1794a393f.png">

2.将指标卡放到 选项卡中；
<img width="1469" alt="图片" src="https://user-images.githubusercontent.com/48307752/226245244-4d1db54b-2750-450d-929d-3a4780f44b65.png">

3.保存返回预览
<img width="1215" alt="图片" src="https://user-images.githubusercontent.com/48307752/226245317-2bc07f19-bb8b-4b69-a6b1-057005c29502.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为一直问题并已经优化，将在下个小版本中发布，到时可以下载体验一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
