### ISSUE TITLE
[Feature]考虑支持databend吗

### ISSUE THREAD

**Issue by WUWEI111222333** [dataease/dataease#4823]
**请描述您的需求或者改进建议.**
目前公司在调研databend，dataease官方有没有考虑支持下databend，目前按照mysql的方式进行连接新建数据集的时候会报错。
![a11b3c90c0fc9ba651f1f5b14d0846be](https://user-images.githubusercontent.com/35459358/226274147-f8f8cfeb-d01a-435e-bfc2-ad76d200d7d4.png)

**Comment by xuwei-fit2cloud** [comment]
非常感谢您对我们的关注。
但由于目前我们正在进行大版本的开发，短期内可能还没有余力来支持新的数据源。
如果您比较着急的话，可以参考一下我们的插件工程（包含数据源插件和视图插件），自行对databend进行支持。
