### ISSUE TITLE
[Feature]时间范围组件可选择关闭自定义选择日期只显示动态时间选项

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4824]
**请描述您的需求或者改进建议.**
时间范围筛选组件调整建议：
能否只显示左边的相对时间，不显示日历表的内容，只给查看者几个可选的范围：本周、上月等，不给用户自定义选择；
<img width="785" alt="图片" src="https://user-images.githubusercontent.com/48307752/226292760-578d958c-b5d8-453e-8ea7-61e22627d96b.png">

图中自定义选择的区域可以由制作者选择是否开启，如果展示的场景只有本月、上月，只给查看者展示本月、上月两个选项即可，查看者就不能选择此时间范围以外的日期范围，这样对于时间的计算可以精确控制，减少不必要的计算量。

**Comment by yayanpei** [comment]
感谢反馈，我们先记录并讨论一下。

**Comment by fit2cloud-yayanpei** [comment]
时间范围组件是通用的组件，查询任何选定范围内的数据，因此我们经过慎重考虑，不修改日期范围组件。

根据您的描述，是要限制用户查询数据的日期范围，因此我们建议您做如下操作：
第一步，在数据集中增加计算字段，使用函数动态可以计算出每条数据是属于上周、上月等，该计算字段的值为：上周、上月。
第二步，在仪表板中增加文本下拉组件，绑定计算字段，用于过滤视图数据。
上述操作，如果您的日期范围并非自然月，自然周，也是可以根据需要自己来定义，相对也更加灵活。

再次感谢您对关注和支持，您的支持是我们不断前进的动力。
