### ISSUE TITLE
[Bug]Sql数据集exists后面的子查询报错

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#4825]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
标准谷歌浏览器

**Bug 描述**

select * from area_mapping o where Exists (select 1 from area_mapping_global p where p.country_name = '${paramALTER}')

**Bug 重现步骤(有截图更好)**
1.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/109720729/226345075-ad03a334-2a25-4ea6-9852-ebe41a86c4f7.png">

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
