### ISSUE TITLE
[Feature] 自己编辑数据集

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#4826]
**请描述您的需求或者改进建议.**
该提供一种自定义数据集。 就是自己定义表结构 自己添加数据。

**Comment by yayanpei** [comment]
感谢反馈，是自己建表，然后在线录入数据是吗？该需求已经在需求池中，近期我们主要在做大版本的升级，暂不规划该功能的支持。建议您先将数据录入至excel，然后上传使用。

**Comment by yayanpei-fit2cloud** [comment]
在线填报在我们的产品规划中，issue就先关闭了，再次感谢您的关注和支持。
