### ISSUE TITLE
[Bug]参数在子SQL里报错

### ISSUE THREAD

**Issue by zzx769394358** [dataease/dataease#4827]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
mysql数据源, sql语句:    select * from table_1 o where Exists (select 1 from table_2 p where p.name =  '${param_name}')

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/57294442/226498747-2edb5f49-668e-4540-a7c0-efd44f5c10cf.png)

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #4825

**Comment by zzx769394358** [comment]
该问题是否解决了呀?
