### ISSUE TITLE
[Bug]数据集预览数据行设置不生效

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4830]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
数据集预览界面的显示行数，设置为其他数值当时生效，刷新一下就恢复了默认值1000，希望保持设置的数值。
<img width="922" alt="图片" src="https://user-images.githubusercontent.com/48307752/226507085-56ca13b8-b6c8-4ce0-9b87-632b132b333b.png">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，这里确实是没有落盘的，而是统一设置一个默认值，，目前没有改变这里逻辑的打算。
