### ISSUE TITLE
[Feature] 能否支持修改视图数据集

### ISSUE THREAD

**Issue by Mr-Glin** [dataease/dataease#4831]
**请描述您的需求或者改进建议.**
现在有两个样式相同的视图，只是数据集不同。这个时候需要直接复用组件 并且直接修改数据源即可。避免了重复工作。

**Comment by liuboF2c** [comment]
![image](https://user-images.githubusercontent.com/30886198/226514817-ed1a4a85-652f-4629-84d5-716551412eb7.png)
这个按钮可以修改视图的数据集

**Comment by liuboF2c** [comment]
建议看一下教学视频

**Comment by Mr-Glin** [comment]
好的 谢谢。
