### ISSUE TITLE
[Bug] 复用组件样式会丢失

### ISSUE THREAD

**Issue by Mr-Glin** [dataease/dataease#4832]
**DataEase 版本**

v1.18
**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome 版本 111.0.5563.65（正式版本） （64 位）

**Bug 描述**
我有一个样式已经设置好的视图组件。但是我复用之后 样式会丢失。需要重新设置。

**Bug 重现步骤(有截图更好)**
1. 
![image](https://user-images.githubusercontent.com/55646980/226509884-f8a3b814-263e-43f3-b076-968f84f58f14.png)
这是已经设置好的组件，然后点击复用组件将会出现如下组件
2.
![image](https://user-images.githubusercontent.com/55646980/226509971-59ae23cb-5b42-4504-aaf5-cb1d6bc1c3d5.png)
该组件是没有我设置的样式的。我需要重新设置一遍

**Comment by BBchicken-9527** [comment]
感谢反馈，目前其实是这样设计的，并不是丢失了而是和你的目标仪表板的设置对其。

**Comment by BBchicken-9527** [comment]
不知道是否还有什么疑问吗？如果没有新的疑问我将会在今天下午六点半前关闭。

**Comment by Mr-Glin** [comment]
好的 谢谢
