### ISSUE TITLE
[Feature] SQL 数据集编辑时建议默认不执行 SQL，以提高用户体验

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#4833]
**请描述您的需求或者改进建议.**
建议如下：
1. 预览数据集界面预览条数减少，比如一次只预览20条，增加预览速度。（如果支持修改数据预览条数后能够保存预览条数就更好了）
2. 编辑 SQL 数据集时默认不执行 SQL，需手动点击按钮执行

原因描述：
我添加了一个 SQL 数据集，但是 SQL 查询比较慢，每次查询耗时 2-5 秒。
如果我想修改这个 SQL 数据集，需要经历以下步骤：
1. 点击数据集，会进入预览界面，此时会自动查询数据 耗时 2-5 秒
2. 点击编辑数据集按钮，进入编辑界面，会自动查询数据，耗时 2-5 秒
4. 修改 SQL 保存...

在修改 SQL 前的 4-10 秒钟对我来说是无意义的。

**Comment by yayanpei** [comment]
感谢反馈，您的建议很不错，第2点在最近的小版本中优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级到最新版本。
