### ISSUE TITLE
[Feature]定时同步数据集添加增量更新任务时，sql配置和任务绑定不和数据集绑定

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#4834]
**请描述您的需求或者改进建议.**
当前给定时同步数据集添加增量更新任务时，sql配置是和数据集绑定的，导致有客户想要配置先执行增量删除再增量新增时无法配置。建议sql配置不和数据集绑定，这样就可以配置多个任务

**Comment by yayanpei** [comment]
感谢反馈，我们需要先内部讨论一下。

**Comment by fit2cloud-yayanpei** [comment]
感谢反馈，您描述的应该是一个任务中，有多个数据处理的子任务，形成一个数据处理流，与目前数据集任务的设计相比，涉及的改动较大，我们经过讨论后暂不进行优化。

issue我们就先关闭了，再次感谢您的关注和支持。
