### ISSUE TITLE
[Bug]偶发性出现定时报告折线图（面积图）显示不全

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4835]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
偶发性出现定时报告折线图（面积图）显示不全。不是所有仪表板都会出现，但是下面重现步骤中的图几乎是必现的，可以用该仪表板测试。

**Bug 重现步骤(有截图更好)**
1.应用模版
![image](https://user-images.githubusercontent.com/48945409/226532200-ed9878c4-4154-4d89-913a-08b632cf1e64.png)

2.新建定时报告，选择刚才的仪表板以及选择如下图所示分辨率
![image](https://user-images.githubusercontent.com/48945409/226532289-78b3f4c2-593b-4979-9b1e-f7ce4b321216.png)

3.点击预览，可看到圈出的图显示不全
![image](https://user-images.githubusercontent.com/48945409/226532442-771d1b5f-9918-4fbf-aefd-63eb2fd20c5d.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，嗯... 确实会有个问题，因为图表的显示是和数据量以及网速挂钩的，所以是会在特定的情况下导致这个问题，但目前我们没有想到更好的解决方案。
