### ISSUE TITLE
[Bug]定时报告中文字字体与仪表板字体不一致

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4837]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
如下图所示，右侧定时报告的字体感觉变了。
![image](https://user-images.githubusercontent.com/48945409/226541269-a41d6fcd-0919-4dd7-b9e3-fcc5908e6a7c.png)

局部对比，上：原仪表板，下：报告。
![image](https://user-images.githubusercontent.com/48945409/226541802-bada4d71-8542-4a47-87f0-1f30b4189a1d.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，确实不是同一种字体，导出字体是给的默认字体，而从浏览器中看到的字体是浏览器设置的字体，是不一样的。到处的时候走的是服务器后台的配置，而你在前端看到的是依托于浏览器，所以会字体不一致。
