### ISSUE TITLE
[Bug] jwt filter token处理逻辑BUG

### ISSUE THREAD

**Issue by VanLiuZhi** [dataease/dataease#4840]
**DataEase 版本 1.18.4**

**运行方式(源码运行)**

我在做开源的改造，发现新版本对token处理很奇怪，感觉是BUG

首先是  src/main/java/io/dataease/auth/filter/JWTFilter.java，

protected boolean executeLogin(ServletRequest request, ServletResponse response) throws Exception 里面

这个逻辑应该是判断token是否有效

if (TokenCacheUtils.invalid(authorization)) {
      throw new AuthenticationException(expireMessage);
}

在下面这个方法中，逻辑没有问题，这样上面的 ，`TokenCacheUtils.invalid(authorization) `应该改成 `!TokenCacheUtils.invalid(authorization)`

```
    public static boolean invalid(String token) {
        if (useRedis()) {
            RedisTemplate redisTemplate = (RedisTemplate) CommonBeanFactory.getBean("redisTemplate");
            //  有key，返回 true
            return redisTemplate.hasKey(KEY + token);
        }
        Object sys_token_store = CacheUtils.get(KEY, token);
        //  有，也是返回 true
        return ObjectUtils.isNotEmpty(sys_token_store) && StringUtils.isNotBlank(sys_token_store.toString());
    }
```

但是用下来没有问题，甚至去缓存中，删除key，也能照样请求接口。

然后在退出登录的代码中 io/dataease/auth/server/AuthServer.java，public String logout()

```
      Long userId = JWTUtils.tokenInfoByToken(token).getUserId();
      authUserService.clearCache(userId);
      if (StringUtils.isBlank(result)) {
          result = "success";
      }
      //  这段是新版本加的，退出登录，却把token重新写回缓存
      TokenCacheUtils.add(token, userId);
```

那整个流程就变成了

1. 登录的时候，通过ServletUtils.setToken(token); 把token响应到前端，前端存储到vuex里面，但是后端缓存没存，假设此时token是token-A
2. 后续请求，filter中，因为是 if (TokenCacheUtils.invalid(authorization)) ，缓存没有自然返回false，不会进入异常，token校验逻辑通过
3. 退出登录的时候，把这个 token-A，存储到缓存中，然后如果再登录，又回到流程1

整个流程中token-A在后端没有发挥作用，之前我看1.15.4 版本不是这样的，还有token过期时间判断，现在封装了一个 TokenCacheUtils，整个流程都怪怪的

**Comment by BBchicken-9527** [comment]
感谢反馈，我们是采用黑名单模式 缓存中有key说明是失效token，invalid是无效的意思，valid是有效的意思。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们是采用黑名单模式 缓存中有key说明是失效token，invalid是无效的意思，valid是有效的意思。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们是采用黑名单模式 缓存中有key说明是失效token，invalid是无效的意思，valid是有效的意思。

**Comment by VanLiuZhi** [comment]
好的，谢谢答疑。一般会认为是做token缓存，原来是这个意思

**Comment by jackieriver** [comment]
黑名单模式, 那么请问一下, 加入黑名单的入口是哪里呢 有什么触发加入名单的
