### ISSUE TITLE
[Bug] 图表配置下钻后下钻层级会与缩略轴重叠

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#4841]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 最新

**Bug 描述**
AntV 配置缩略轴后，下钻层级与缩略轴重叠：
<img width="879" alt="WeChat4a6285e938be1ad752c6a45c117e1356" src="https://user-images.githubusercontent.com/30886198/226790463-afd75984-34e8-4aa6-b88c-8fa10e5a262f.png">

Echarts 配置缩略轴后，下钻层级与缩略轴重叠，即使修改了下边距也无法解决问题：
<img width="1060" alt="WeChat19e223ef2d62c52fea81be0845755dc2" src="https://user-images.githubusercontent.com/30886198/226790477-9042562d-8660-488e-99e0-3bf6cc8bd5c6.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，但目前没有好的解决方式，所以建议使用AntV图库。

**Comment by liuboF2c** [comment]
> 感谢反馈，已知问题，但目前没有好的解决方式，所以建议使用AntV图库。

AntV 和 Echarts 均存在此问题
