### ISSUE TITLE
[Bug] 定时同步小数精度为 10 位的表会报错

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#4848]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新

**Bug 描述**
定时同步数据集同步任务报错如图：
![image](https://user-images.githubusercontent.com/30886198/226851206-10c0d13e-f375-4267-80bf-7c0c6171ddff.png)

原因是原表中的数据是 DECIMAL(16,10)，而同步到 Doris 数据库中用的是 DECIMAL 最大只支持 9 未小数，建议修改为DECIMALV3

![image](https://user-images.githubusercontent.com/30886198/226882795-35e4f52b-cdf2-4100-9932-4c7c27a5aa7f.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前dataease的doris版本为1.1，之前也尝试过升级但因为一些问题放弃了。所以目前doris无法使用你说的方法做出调整。
