### ISSUE TITLE
图表类型为指示卡类型时,页面显示与查看详情数据不一致

### ISSUE THREAD

**Issue by dzMoon** [dataease/dataease#4849]
* 图表类型为指示卡类型时，对数值格式保留小数之后，查看详情尽量与页面保持一致
> 问题如下图：
![f790a0c29d026359e3506351810af69](https://user-images.githubusercontent.com/23649132/227083921-76b99470-ac20-441a-8cbb-783803918967.png)
![9b333c6c1fadc177024426865e680fe](https://user-images.githubusercontent.com/23649132/227083931-092b8cca-9c6a-40e4-bc9c-c62cd1531ad1.png)

**Comment by yayanpei** [comment]
感谢反馈，您的建议很不错，由于1.x 用的是图库本身的数值格式，而图库返回的数据是原始数据，并非格式化后的。我们将在2.0版本采用更为合适的方案，来避免不一致的情况。
