### ISSUE TITLE
[Feature]仪表盘弹窗

### ISSUE THREAD

**Issue by zzx769394358** [dataease/dataease#4851]
**请描述您的需求或者改进建议.**
dataease的跳转功能非常好用,  能否支持弹窗的类型

**Comment by xuwei-fit2cloud** [comment]
弹窗的方式打开的是外部链接还是仪表板呢？
一般来说，仪表板以弹窗形式打开，显示效果可能不太好。

**Comment by zzx769394358** [comment]
仪表盘.  根据现有的联动信息打开一个新的仪表盘(弹窗里的仪表盘内容只会有一个 试图)
您方便吗,加一下q, 有一些前端代码想请教您 (我用户名里的数字是q)
