### ISSUE TITLE
[Feature]利用url进行传参

### ISSUE THREAD

**Issue by zzx769394358** [dataease/dataease#4853]
若多个仪表盘, 内容一样, 只是使用的数据集里的某个参数有差异.
若使用复制的形式,一张一张配置较为繁琐,  且后期改动麻烦.
可否利用url进行传参

**Comment by yayanpei** [comment]
感谢反馈，我们需要讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
Issue我们先关闭了，再次感谢您的关注和支持。
