### ISSUE TITLE
[Bug] 复制仪表板错误 column chart_view_field.pv_copy.chart_view_id not exist

### ISSUE THREAD

**Issue by Mr-Glin** [dataease/dataease#4854]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**

源码运行
**浏览器版本**

chrome最新版
**Bug 描述**

进行复制仪表板操作时。接口报错；
debug发现是 dataease/backend/src/main/java/io/dataease/ext/ExtChartViewMapper.xml 
chartFiledCopyWithPanel方法SQL有错误。
**Bug 重现步骤(有截图更好)**
1. 复制仪表板，输入仪表板名称
2. 点击确定，就会出现错误信息
3. 
![image](https://user-images.githubusercontent.com/55646980/227118960-1fe94b2d-a241-48f5-b6f4-b2fafe565844.png)
![image](https://user-images.githubusercontent.com/55646980/227119006-9f9518c3-2205-44db-a7c0-bf0cde613284.png)

4.DEBUG后定位问题
![image](https://user-images.githubusercontent.com/55646980/227119123-2c646b9a-c4a5-4b5c-8b04-353d4cd610a1.png)
![image](https://user-images.githubusercontent.com/55646980/227119168-ce64da80-e2f7-4add-b759-7736ad11ae1c.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们修复一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.5版本已处理，请升级最新版本。
