### ISSUE TITLE
[Bug]视图计算字段引用原始字段，配置该字段视图报错

### ISSUE THREAD

**Issue by zhimayuyuan** [dataease/dataease#4856]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**
Chrome 版本 110.0.5481.78（正式版本） （64 位）

**Bug 描述**
视图计算字段引用原始字段，配置该字段视图报错

**Bug 重现步骤(有截图更好)**
1.![截图1](https://user-images.githubusercontent.com/128681370/227137846-7e16bbf4-ddc6-44f2-a547-f4b315a27c94.jpg)
2.
![截图2](https://user-images.githubusercontent.com/128681370/227137960-0e5f43c8-a7dc-4cb3-8eb6-29c61ba201e3.jpg)

**Comment by BBchicken-9527** [comment]
感谢反馈，视图里的计算字段，如果是指标，就一定要聚合函数，因为视图最终要聚合运算，sum之类的
