### ISSUE TITLE
[Bug] mongodb 数据源 计算字段原文本类型，设置为数值类型后，无法正确使用+-*/

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4857]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
mongodb 数据源 计算字段原文本类型，设置为数值类型后，无法正确使用+-*/

**Bug 重现步骤(有截图更好)**
1.新建数据集，修改字段类型，文本至数值
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/45852479/227139750-35c027a0-f1d5-4c97-bf32-b748b1a5b5f9.png">
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/45852479/227139794-30f2ddf6-0c67-4fca-b0db-30b8c7c323c2.png">
2.新建字段字段，使用改字段做+-*/运算
【字段+100】<img width="1006" alt="image" src="https://user-images.githubusercontent.com/45852479/227139987-a960b20b-d850-4ed2-a3e9-51bc5bd73450.png">
【字段-100】<img width="1021" alt="image" src="https://user-images.githubusercontent.com/45852479/227140154-1eac16c4-2855-4e52-89a1-ede75efce014.png">
【字段*100】<img width="1027" alt="image" src="https://user-images.githubusercontent.com/45852479/227140213-963fe0bb-1a42-4bd7-9223-9f489eb8341b.png">
【字段/100】<img width="1023" alt="image" src="https://user-images.githubusercontent.com/45852479/227140262-94a71acc-f8f7-41b3-b011-64396199fb68.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我这边建议使用mongodb bi，因为mongodb的driver很多功能上存在缺陷。
