### ISSUE TITLE
[Bug] mongoDb数据集使用除法后，无法保留小数

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4858]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
mongoDb数据集使用除法后，无法保留小数

**Bug 重现步骤(有截图更好)**
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/45852479/227141030-2ecb1bc0-026f-44e3-bbcf-6dd73234a96c.png">
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/45852479/227141077-82173765-be72-4495-aa06-ce0dad482397.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我这边建议使用mongodb bi，因为mongodb的driver很多功能上存在缺陷。
