### ISSUE TITLE
[Bug]脚本有时间参数和union all时会导致sql解析报错

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#4859]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
最新chrome

**Bug 描述**
新建sql数据集时，脚本里有时间参数，且子查询中用到了union all语句，会导致sql解析问题报错

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/57552153/227141524-cf436a17-f4d2-409e-a184-247b26f61c15.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，能受累详细说一下吗？目前测试环境没有模拟出来你说的问题
