### ISSUE TITLE
[Feature] 上传excel数据集时，把第一次上传的取消勾选后，再上传一个，会把之前取消勾选的重新选上

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4863]
**请描述您的需求或者改进建议.**
上传excel数据集时，把第一次上传的取消勾选后，再上传一个，会把之前取消勾选的重新选上
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/45852479/227153063-04d0bba9-138d-465a-8e5f-f0b11f364e9b.png">
<img width="1479" alt="image" src="https://user-images.githubusercontent.com/45852479/227153175-06fe5012-b916-45d3-82a8-2940ad134288.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已处理，请更新最新版本。
