### ISSUE TITLE
[Feature]文本下拉组件多选时，输入框内容过滤后希望支持一次选择多个后再置空

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4871]
**请描述您的需求或者改进建议.**
文本下拉的组件设置成多选时，搜索关键词出现多个选项，选中一个之后需要重新输入关键词，再多选一个，再重新输入一次，建议优化，选择之后保留输入关键词搜索的结果

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们在近期版本做一下优化。

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已处理，请更新最新版本。
