### ISSUE TITLE
[Feature] 在配置仪表板时，是否可以支持添加自定义脚本

### ISSUE THREAD

**Issue by MJAIYJ** [dataease/dataease#4872]
在配置仪表板时，编辑属性，是否可以支持添加自定义脚本，类似于这样
![image](https://user-images.githubusercontent.com/62281466/227414742-8f69b50b-1b06-4acc-a3fa-0137db390b3f.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个功能会需要一定的编码能力，对用户来说会有一定的使用门槛。
在近期的版本内，我们还没有相关的开发计划。
后续版本我们再考虑一下。
