### ISSUE TITLE
[Feature]是否可增加快捷键操作

### ISSUE THREAD

**Issue by MJAIYJ** [dataease/dataease#4873]
建议增加常用快捷键操作，比如
delete ：直接删除某个组件；
shift ：组件多选，达到批量移动的效果，目前时间、文字、图片等不支持批量操作，移动时，容易将已调好的间距打乱；
上下左右  方向键移动组件，达到微调效果

**Comment by MJAIYJ** [comment]
另，批量操作是否可支持批量拖拽，调整大小？

**Comment by MJAIYJ** [comment]
另，批量操作是否可支持批量拖拽，调整大小？
比如，同样大小/类型的图表，想批量调整大小（宽度或高度），一个个调，容易存在误差

**Comment by yayanpei** [comment]
快捷键以及批量操作的功能优化，由于近期我们主要做大版本的升级，因此1.x的版本不再规划相关的优化，但是我们会在2.x的版本迭代中加入该需求，再次感谢您的关注和支持。
