### ISSUE TITLE
[Feature]间隙大小是否可以自定义

### ISSUE THREAD

**Issue by MJAIYJ** [dataease/dataease#4874]
矩形布局时，当前的间距过小，是否可自行定义间隙大小
![image](https://user-images.githubusercontent.com/62281466/227415886-0413966f-89cb-4d5d-bfb9-751d384e1bd1.png)

**Comment by yayanpei** [comment]
感谢反馈，该需求已经记录在需求池中，默认的间隔目前来看效果还不错，能满足绝大部分用户的需求。由于需求涉及到的改动较多，我们需要收集更多用户的需求后再进行下一步的规划，再次感谢您的关注和支持。
