### ISSUE TITLE
[Bug] 仪表板迁移目录后显示视图已被删除，无法正常显示

### ISSUE THREAD

**Issue by limin-fit2** [dataease/dataease#4875]
**DataEase 版本**

v1.18.5

**运行方式(安装包运行 or 源码运行 ?)**

安装包

**浏览器版本**

版本 111.0.5563.110（正式版本） (arm64)

**Bug 描述**
仪表板迁移后显示视图已被删除，无法正常显示

**Bug 重现步骤(有截图更好)**
1. 创建新仪表板，选择比较类型的组件和地图组件后点击保存
2. 将创建好的仪表板迁移至其他目录
3. 在新目录打开仪表板显示视图已被删除
![image](https://user-images.githubusercontent.com/61964761/227417568-84bde352-2503-4438-8955-58ee97fab3fe.png)
![image](https://user-images.githubusercontent.com/61964761/227417578-1ca1839b-54fb-40fd-a057-fd25b1011110.png)
![image](https://user-images.githubusercontent.com/61964761/227417589-2f979000-7c7f-4776-884b-1814c25e8396.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已处理，请更新最新版本。
