### ISSUE TITLE
[Question] 能否增加 图例 字体大小最小字体选项 

### ISSUE THREAD

**Issue by Mr-Glin** [dataease/dataease#4877]
**请描述您的问题.**
目前字体大小选择范围为 10-60
能否支持 8-60
能够告诉我怎么修改吗？感谢

**Comment by BBchicken-9527** [comment]
感谢反馈，目前该类需求反馈并不多，考虑到实际使用场景中字体显示过于小，目前没有在此处做修改的打算。如果是二开的话，建议自己放开一下限制吧。
