### ISSUE TITLE
[Bug]【数据集】MongoDB SQL 数据集创建报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#4880]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
MongoDB SQL 数据集创建报错。
![image](https://user-images.githubusercontent.com/24768910/227445589-ad40c6bb-feb5-437c-963a-3dfe9be31bdc.png)

环境可提供~

**Comment by BBchicken-9527** [comment]
感谢反馈，如果方便的话可以微信联系我，我可能需要你提供一些具体的信息
