### ISSUE TITLE
[Feature] 行列权限设置白名单时下拉组件支持模糊搜索匹配用户

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4882]
**请描述您的需求或者改进建议.**
行列权限设置白名单时下拉组件支持模糊搜索匹配用户
![image](https://user-images.githubusercontent.com/30063018/227445807-2d5fc10b-48f0-49ae-b99c-4d645df1c723.png)

**Comment by yayanpei** [comment]
感谢反馈，我们近期小版本优化一下。
