### ISSUE TITLE
[Bug]SQL数据集union ALL语句中含有注释行，且注释行中含有参数变量时，执行异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4883]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
SELECT t.* from (
(SELECT 
 *
 -- test = '${test}'
 from user order by create_time desc
)
UNION ALL
(SELECT * from user order by create_time asc)
) t

参数${test}在程序中有特殊的处理逻辑，这块应该是没处理好，导致出现异常，不带参数执行就是正常的
![image](https://user-images.githubusercontent.com/89771514/227446081-dc5df8e9-ac81-47c0-b208-cc5feb36bc5c.png)
![image](https://user-images.githubusercontent.com/89771514/227446127-bed2d2be-2a6a-45ec-b1c8-e7bc46466703.png)

**Comment by ZhaoQian1222** [comment]
还有一个情况，如果对union ALL的语句外面嵌套一层，且union All语句中含有参数变量，此时就会报同样的异常
![image](https://user-images.githubusercontent.com/89771514/227449119-3afe0282-4a30-4319-83fd-424a1ca47720.png)

不嵌套就没有问题
![image](https://user-images.githubusercontent.com/89771514/227449364-e9692cb7-39b1-48fc-a3b3-9f0b86304d33.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
