### ISSUE TITLE
[Bug]直连MySQL数据库数据集使用时间筛选条件时全部数据被过滤

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4891]
**DataEase 版本**
v1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome标准版

**Bug 描述**
直连 MySQL 数据库数据集使的视图用时间筛选条件时，全部数据都被过滤。而使用同步模式的数据集视图可以正常被过滤。

**Bug 重现步骤(有截图更好)**
1.直连 MySQL 的数据集创建视图和对应的筛选条件。
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/48945409/227681970-a6777448-7fa1-4ada-8bcf-a1c8eda1c6eb.png">
<img width="802" alt="image" src="https://user-images.githubusercontent.com/48945409/227681995-cf217d60-bee7-4ac2-9598-946a9a1f252a.png">
<img width="637" alt="image" src="https://user-images.githubusercontent.com/48945409/227681983-eaac90c5-2e67-469b-b808-251217ac6eab.png">

2.测试筛选，选择了一个有数据的时间段，筛选完后，所有数据均被过滤掉了。符合要求的数据没有被显示出来。
<img width="631" alt="image" src="https://user-images.githubusercontent.com/48945409/227682048-2c9bf7b6-609d-4de8-83b1-30a58508cb1c.png">

3.对比测试了一个 MySQL 同步模式的数据集如下。
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/48945409/227682158-e2fc29e9-2633-45d9-a145-38c0004e1802.png">
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/48945409/227682183-54b3a5ca-0636-44ef-90b5-89e3278a6b9e.png">

4.结果正常。
<img width="483" alt="image" src="https://user-images.githubusercontent.com/48945409/227682218-4e1174aa-b6e5-4daa-b1b7-324d4a9a35c2.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的这种情况，方便的话希望可以提供更为详细的说明，已方便我们后面进一步的排查。

**Comment by luyang351** [comment]
补充：该时间类型为 13 位时间戳。

**Comment by BBchicken-9527** [comment]
感谢反馈，确实这里有点儿问题，我们会尽快修复的

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已处理，请更新最新版本。
