### ISSUE TITLE
创建一个数据库数据源后，如果不是采用默认驱动的话，则基于这个数据源创建的数据集没有定时同步功能[Bug]

### ISSUE THREAD

**Issue by Linsk110** [dataease/dataease#4892]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
源码打包运行

**浏览器版本**
chrome 111.0.5563.111
**Bug 描述**
创建一个数据库数据源后，如果不是采用默认驱动的话，则基于这个数据源创建的数据集时，同步模式的下拉框只有直连可选，定时同步的选项无法选择。

**Bug 重现步骤(有截图更好)**
![c4f1d3c310b7e222a04baf8bdacbef6](https://user-images.githubusercontent.com/49526254/227701415-f863db19-b84e-4524-a6c8-c47e912ee994.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前涉及如此，自定义的驱动无法动态放入kettle。
