### ISSUE TITLE
[Feature]动态辅助线增加小数为控制

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4893]
**请描述您的需求或者改进建议.**
视图中高级设置--辅助线，选择动态--平均值，没有小数为限制，如果可以，希望添加小数位控制。
![图片](https://user-images.githubusercontent.com/48307752/227769424-ad2ad460-73a5-4d2f-9211-4186acf3e979.png)

**Comment by yayanpei** [comment]
感谢反馈，我们在最近的小版本中优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已处理，请更新最新版本。
