### ISSUE TITLE
[Bug]使用模版创建仪表板发送定时报告报错的问题

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4894]
**DataEase 版本**
v1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
1.未替换 demo 数据时就在发送定时报告时选择发送视图数据，报错空指针，这个是否应该在选视图数据时做一下判断，如果仍然是 demo 数据给予提示，而不是发送报告时再报错；
2.存在比较旧的仪表板即使给视图替换了真实数据，发送视图数据仍然报错的问题。

**Bug 重现步骤(有截图更好)**
1.使用【某运动品牌销售概览】模版创建仪表板。
![image](https://user-images.githubusercontent.com/48945409/227822537-66244c4b-0c78-4883-b864-9dcc8747c4e3.png)

2.未附加视图数据，发送仪表板，正常接收，这个是没有问题的。
![image](https://user-images.githubusercontent.com/48945409/227823653-3891a1e6-9b81-4518-b099-04ba5275ba6c.png)

3.选择附件发送一个视图数据，该视图未做真实数据替换。
![image](https://user-images.githubusercontent.com/48945409/227823822-d883cdfc-76b9-41d7-8c09-7d719bbd858d.png)
定时报告发送报错，出现空指针异常。如上，建议在发送之前选择的时候就做一下判断，给予提示。
![image](https://user-images.githubusercontent.com/48945409/227823937-e519e414-2922-42b6-a1e7-cf9c08021b18.png)

4.对其中一个视图进行真实数据替换，并选择附带该视图数据，仍然失败报空指针异常。（这里后面换了一个其他的模版进行测试，替换真实数据再发送是没问题的，所以应该跟这个模版本身出自较老版本的 DataEase 有关）
![image](https://user-images.githubusercontent.com/48945409/227824207-2ba50546-b8bb-4923-96d3-41208af0aa3c.png)
![image](https://user-images.githubusercontent.com/48945409/227824282-fb88d326-8cc3-4ba3-bd7a-ebc2104d1df7.png)
![image](https://user-images.githubusercontent.com/48945409/227824415-bedcf091-cf6b-45a7-be5a-c4cda92944b3.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已处理，请更新最新版本。
