### ISSUE TITLE
[Bug]视图名称中带有“/”字符时发送定时报告同时选择附带该视图数据报错

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#4896]
**DataEase 版本**
v1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
视图名称中带有“/”字符时发送定时报告同时选择附带该视图数据报错，报错内容为非法字符：java.lang.IllegalArgumentException: Invalid char (/) found at index (2) in sheet name '用户/资产活跃情况'

**Bug 重现步骤(有截图更好)**
1.使用下图模版做测试，使用该模版创建仪表板并针对所选择的视图做真实数据替换。
![image](https://user-images.githubusercontent.com/48945409/227825826-f788b647-c99e-49d5-82db-cf5c3e8a7b45.png)
![image](https://user-images.githubusercontent.com/48945409/227826053-88945cff-ce8c-4c9a-998e-d39c894b9a5e.png)

2.配置定时报告，选择上述的仪表板以及选择附带视图数据。
![image](https://user-images.githubusercontent.com/48945409/227826193-de611a38-71bd-42f9-8eda-bafb8772b2e8.png)

3.发送定时报告，出现如下报错，“/”为非法字符。
![image](https://user-images.githubusercontent.com/48945409/227826392-6b811ed3-0a42-4e7a-b1ac-b39e5026c138.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已处理，请更新最新版本。
