### ISSUE TITLE
[Bug] mongodb（非bi-connector）添加数据库数据集报错

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4897]
**DataEase 版本**
v1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
mongodb（非bi-connector）添加数据库数据集报错

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/45852479/227834531-1ff8bc47-5ce6-45ff-b8f9-08628ea0b2de.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前没有发现你所说的问题，现将问题关闭，若你那边复现了或者有新的条件要补充可打开此问题，我们会及时跟进。
