### ISSUE TITLE
[Feature]希望在制作视图时，能支持操作回滚操作，不仅可以撤回当前操作，还可以回退到指定的操作记录。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#4898]
**请描述您的需求或者改进建议.**
希望在制作视图时，能支持操作回滚操作，不仅可以撤回当前操作，还可以回退到指定的操作记录。目前dataease只能进行撤回操作，撤回还不好用。

**Comment by yayanpei** [comment]
感谢反馈，受限于1.x的设计，这部分改动涉及范围较大。我们团队正在做大版本的升级，会在2.0版本优化视图制作的回滚，再次感谢您的关注和支持。

**Comment by yayanpei** [comment]
issue这边就先关闭了，再次感谢您的关注和支持。
