### ISSUE TITLE
[Question] DataEase 有技术交流群吗？

### ISSUE THREAD

**Issue by maninhill** [dataease/dataease#49]
**请描述您的问题.**

如题。

**Comment by fit2cloudrd** [comment]
你好，可以在我们的官网最下方的 `联系我们` 中看到微信群的二维码。
https://dataease.io/#contact
<img width="1439" alt="WX20210627-143207@2x" src="https://user-images.githubusercontent.com/985347/123535207-fefab500-d754-11eb-8f01-6569fa9e8afb.png">

**Comment by maninhill** [comment]
欢迎大家参与贡献。如果 PR 被官方确认并 Merge 进主干后，DataEase 社区讲为您颁发贡献者证书。

证书下载地址：https://community.fit2cloud.com/#/products/dataease/techexchange

**Comment by wyj291758444** [comment]
1.18.2数据库怎么没有达梦的连接选项
