### ISSUE TITLE
[Bug] 时间过滤组件SQL拼接问题

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4901]
**DataEase 版本**
v1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
时间过滤组件SQL拼接问题

**Bug 重现步骤(有截图更好)**
1.数据库sql，添加过滤条件
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/45852479/227865456-6fb1c087-a99a-48d6-93cd-b6c70b683fd6.png">
2.添加过滤组件拼接条件
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/45852479/227865705-87bf0309-bf03-4539-92a8-bfbcd3122362.png">
3.去掉毫秒
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/45852479/227865846-ea67dbc8-fdd5-418f-8c42-226909f887d0.png">
4.过滤组件配置
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/45852479/227865947-30cf6fc3-e890-4fe6-9ad5-b4eae405f722.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复。

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已处理，请更新最新版本。
