### ISSUE TITLE
[Feature]折线趋势图点击选项后，只展示当前选项的指标数据

### ISSUE THREAD

**Issue by zijin-zj** [dataease/dataease#4905]
**请描述您的需求或者改进建议.**
折线趋势图点击选项后，只展示当前选项的指标数据，而不是隐藏当前选项的指标数据
![image](https://user-images.githubusercontent.com/48403386/228107940-f2bbc632-56a2-4e9a-a346-ae7a4028d9b3.png)

**Comment by yayanpei** [comment]
感谢反馈，图表默认是两个指标均展示的，点击其中一个指标，调整被点击指标的状态为隐藏更合适一些，因此暂不考虑进行优化，再次感谢您对 Dataease 的关注和支持。
