### ISSUE TITLE
[Feature]支持自动更新excel数据集内容，将文件放在固定目录，通过脚本实现

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#4906]
**请描述您的需求或者改进建议.**
采用excel更新数据集，不用手工操作，比如写个脚本把更新的excel定期放在某个目录里面，脚本自动触发更新Excel数据集

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个需求之前已经有用户提过，我们记录。
我们会在2.0版本中考虑支持，目前的1.x系列中应该不会支持了。
