### ISSUE TITLE
[Feature]Knowledge maps增加“知识图谱”风格图形

### ISSUE THREAD

**Issue by duncanfun** [dataease/dataease#4907]
**请描述您的需求或者改进建议.**
当前，知识图谱在各行各业的应用非常广泛，希望可以增加新的图表类型，支持展示知识图谱。
Currently, knowledge maps are widely used in various industries, and it is hoped that new chart types can be added to support the display of knowledge maps.

**Comment by yayanpei** [comment]
感谢您对 Dataease 的关注和支持，该图表类型已经在需求池中，后续我们也会持续提供更加丰富的图表类型。
Thanks for your attention and support for Dataease, and this chart type is already in the demand pool, and we will continue to provide richer chart types in the future.

**Comment by xuwei-fit2cloud** [comment]
1.x版本暂时还没有支持计划，可以添加到2.0系列中。
