### ISSUE TITLE
[Bug]当联动字段包含日期格式的字段时联动失效

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#4908]
**DataEase 版本**
18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 110.0.5481.177（正式版本） (x86_64)

**Bug 描述**
当联动字段包含日期格式的字段时联动失效

**Bug 重现步骤(有截图更好)**
1.创建多个视图，使用同一个数据集，数据集包含时间格式字段，设置联动
2.联动后，联动的视图为空白
![image](https://user-images.githubusercontent.com/70566485/228177568-cd54407a-432c-4a17-8105-c8ba660d7f74.png)
![image](https://user-images.githubusercontent.com/70566485/228177685-4228ebb3-f21a-478a-9f7c-0a421a5b4762.png)
![image](https://user-images.githubusercontent.com/70566485/228177747-6457ecbb-1141-473b-9c97-f557ab9b1485.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，你看一下你的时间时间字段是不是有时分秒？因为默认显示是不时分秒的，这样就会造成数据聚合，当数据聚合后就无法判断具体事那一条数据了。所以将时分秒开启后数据不是聚合状态应该就可以了

**Comment by xiebei-l** [comment]
> 感谢反馈，你看一下你的时间时间字段是不是有时分秒？因为默认显示是不时分秒的，这样就会造成数据聚合，当数据聚合后就无法判断具体事那一条数据了。所以将时分秒开启后数据不是聚合状态应该就可以了。

已内部测试，开启时分秒后，日期格式为年月日时分秒，可以正常联动
