### ISSUE TITLE
[Bug]API数据源接口中包含{}无法连接

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#4909]
**DataEase 版本**
18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 110.0.5481.177（正式版本） (x86_64)

**Bug 描述**
API数据源接口中包含{}无法连接，直接浏览器里可以，无认证方式
接口案例：http://17*.**.*.**:****/prod-api/api/v1/query?query=mysql_global_status_uptime{job=~%22mysqld_exporter%22,%20instance=~%22172.17.0.201:9104%22}

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/70566485/228178548-b66dfe48-6fad-42b8-bb4c-2b51f0ecad57.png)
![image](https://user-images.githubusercontent.com/70566485/228178571-6befe4a0-6c3e-4e0a-829b-28034db89277.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，你试一下将路径使用encodeURIComponent编码方式转换一下呢？url对于花括号是无法识别的，你再浏览器中可以正常定位应该是浏览器自动翻译了，实际查询应该是：mysql_global_status_uptime%7Bjob%3D~%2522mysqld_exporter%2522%2C%2520instance%3D~%2522172.17.0.201%3A9104%2522%7D

**Comment by xiebei-l** [comment]
> 感谢反馈，你试一下将路径使用encodeURIComponent编码方式转换一下呢？url对于花括号是无法识别的，你再浏览器中可以正常定位应该是浏览器自动翻译了，实际查询应该是：mysql_global_status_uptime%7Bjob%3D~%2522mysqld_exporter%2522%2C%2520instance%3D~%2522172.17.0.201%3A9104%2522%7D

收到，十分感谢
