### ISSUE TITLE
[Bug] 仪表板清空画布后保存，此时撤回报错

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4910]
**DataEase 版本**
v1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
仪表板（有视图，已保存）清空画布后保存，此时撤回报错

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/45852479/228179495-b3bd044d-df3f-4e48-b1e2-f036aeb704a4.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，因为历史原因（仪表板和视图分离）导致，后续版本将会优化，因为改动的话影响会很大（底层架构都会发生改变），所以短期内不会在此处进行修改。
