### ISSUE TITLE
[Bug]【仪表板】CK 数据集联动时间筛选组件报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#4915]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准浏览器

**Bug 描述**
CK 数据集联动时间筛选组件报错

**Bug 重现步骤(有截图更好)**
1.连接数据集
![image](https://user-images.githubusercontent.com/24768910/228499469-647c0223-ba06-40f0-95a1-a2e0aa0136ee.png)

2.仪表板正常显示
![image](https://user-images.githubusercontent.com/24768910/228499637-db45759c-a569-45f1-b061-6a9221b573d0.png)

3.时间筛选组件配置
![image](https://user-images.githubusercontent.com/24768910/228499946-da449fe5-1855-4ac7-bc3f-5c3924b6287e.png)

4.仪表板筛选报错
![image](https://user-images.githubusercontent.com/24768910/228499807-d8c10a79-3cf1-4998-a231-d314835d5ac7.png)

**Comment by AndroidBaby1** [comment]
标准谷歌浏览器

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已处理，请更新最新版本。
