### ISSUE TITLE
[Bug]大屏分辨率无法自定义按UI设计稿配置，组件显示容易错位显示

### ISSUE THREAD

**Issue by evanlin84991** [dataease/dataease#4916]
**DataEase 版本**
V1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
所有版本

**Bug 描述**
<img width="944" alt="1680145050390" src="https://user-images.githubusercontent.com/52950960/228716883-df419e05-4658-4225-b90f-cf3fa3f68974.png">

**Bug 重现步骤(有截图更好)**
 1.  制作大屏，上传组件“图片”或其他组件；
 2. 设置“位置”，无法按照UI设计稿提供的准确宽度和高度进行配置，
 3. 大屏默认的分辨率为1920X1080和3840X2160，但系统最大宽度配置自动切换为1595
 4. 最后虽然系统支持自适应，但由于无法按照UI设计稿准确定位位置，容易导致错位显示；

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，短期不会对此处进行优化，但后续将会有重大升级请耐心等候，感谢你的支持与热爱。

**Comment by evanlin84991** [comment]
有计划放在V2.0.0大版本的里程碑中实现否？

**Comment by BBchicken-9527** [comment]
嗯嗯，目前确实有这方面的打算；
