### ISSUE TITLE
[Bug]Echarts图库汇总表，使用presto数据集文本字段类型去重计数 报错

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#4917]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌 版本 110.0.5481.177（正式版本） (x86_64)

**Bug 描述**
Echarts图库汇总表，使用presto数据集文本字段类型去重计数 报错

**Bug 重现步骤(有截图更好)**
1.添加presto数据集
2.添加Echarts汇总表视图
3.对文本字段类型的指标字段去重计数，报错
![image](https://user-images.githubusercontent.com/70566485/228723542-adeb439b-94ac-4ded-8a34-f62ede48a2af.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
