### ISSUE TITLE
视图字段修改计算逻辑后不自动生效刷新数据

### ISSUE THREAD

**Issue by pangzhili** [dataease/dataease#4919]
**DataEase 版本**
当前官网版本

**浏览器版本**
chrome

**Bug 描述**
1、任意选择一个数据集新建natv123指标卡
![image](https://user-images.githubusercontent.com/46517296/228728004-3c0e2df8-77a8-4698-a5ba-283270a6967a.png)

2、针对当前数据集和123指标卡新建视图字段 test，此时结果是 3
![image](https://user-images.githubusercontent.com/46517296/228728471-ab23d621-44dd-41ed-87bd-8eaa82c1adea.png)
3、拖动指标test字段到值/指标中，当前123指标卡数值显示正常
![image](https://user-images.githubusercontent.com/46517296/228728546-099a3728-d36d-4adf-af70-051e34f231a0.png)
4、修改视图字段计算逻辑，现在结果是 2
![image](https://user-images.githubusercontent.com/46517296/228728851-8a115a00-1e91-48ca-9018-5a141fe6bf86.png)
5、返回编辑页面数据不刷新
![image](https://user-images.githubusercontent.com/46517296/228728823-711a1631-d7c3-4226-a7cc-3aa9917ae06d.png)
6、拖动替换更新也不更新数据
![image](https://user-images.githubusercontent.com/46517296/228728823-711a1631-d7c3-4226-a7cc-3aa9917ae06d.png)
7、先删除当前值/指标中的test字段，再拖入test字段才生效
![image](https://user-images.githubusercontent.com/46517296/228729237-d9bae876-ef56-4dc0-b941-daa93d0a71b3.png)

**Comment by pangzhili** [comment]
期望正常的逻辑是修改视图字段逻辑后就自动刷新数据结果，或者，重新替换test字段自动刷新数据结果。

**Comment by BBchicken-9527** [comment]
感谢反馈，设计如此，字段的变动，对视图的计算影响较大，无法自动生效；目前短期内没有优化此处的计划，但你的意见我已经记录，后续会根据产品的计划做出调整；
