### ISSUE TITLE
[Bug]精简模式部署，导入excel数据集，单元格内包含\，导入后，查看无数据、执行记录报错

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#4921]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌 版本 110.0.5481.177（正式版本） (x86_64)

**Bug 描述**
精简模式部署，导入excel数据集，单元格内包含\，导入时正常，导入后，查看无数据、执行记录报错

**Bug 重现步骤(有截图更好)**
<img width="962" alt="image" src="https://user-images.githubusercontent.com/70566485/228760175-6c2dd198-ef5d-4609-852a-f76eb37e99b0.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
