### ISSUE TITLE
[Feature]【仪表板】视图增加竖向辅助线

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#4922]
**请描述您的需求或者改进建议.**
直方图或者折线图等视图增加竖向辅助线
![image](https://user-images.githubusercontent.com/24768910/228788206-30a4520a-935a-4f3e-8676-81e1e6f62ef7.png)

**Comment by xuwei-fit2cloud** [comment]
我理解这个应该可以通过数据点标记+区域标记功能来支持，我们需要讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们计划放在2.0版本中支持。
