### ISSUE TITLE
[Feature]非指标或维度的字段提供一个排序功能

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#4924]
社区群客户反应有些场景下需要某个特定的字段排序，但是不需要在视图中显示出来，当前必须要拖到指标或维度才显示排序操作。
<img width="593" alt="image" src="https://user-images.githubusercontent.com/57552153/228803286-e9417ae0-5496-454c-9790-ebf850fcd920.png">

**Comment by xuwei-fit2cloud** [comment]
这个我们正在考虑2.0版本中进行改造，目前1.0版本中应该不会做相关支持。
