### ISSUE TITLE
[Feature] 日期范围组件增加阈值设置，可设置一次最大查询的日期范围

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4926]
**请描述您的需求或者改进建议.**
日期范围组件增加阈值设置，可设置一次最大查询的日期范围（为了限制一次查询数据量）

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，但用户在正常使用日期范围组件时，本身就可以合理的去选择日期范围，也就不会存在查询数据量的问题。
如果添加了限制，反而可能会让这个组件在使用时进行频繁的阈值修改，我们目前没有相关的调整计划。
