### ISSUE TITLE
[Bug]用户通过分享的仪表板跳转到另一个分享的仪表板时报错

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#4928]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
最新chrome

**Bug 描述**
用户通过分享的仪表板跳转到另一个分享的仪表板时报错

**Bug 重现步骤(有截图更好)**
1.用户A比如管理员分享2个仪表板给用户B，其中第一个仪表板可以跳转到第二个仪表板
2.用户B登陆，打开其中的第一个仪表板，点击跳转
3.报错
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/57552153/228808992-6642419e-228f-412a-9148-fbc27e85ddbd.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前设计如此，分享给出的权限为临时权限，而跳转后走的是仪表板的查看权限。是无法找到你的临时权限的，不过你提出的缺失会有这种场景，我们会重新考虑此处的处理逻辑的，但由于产品进度近期内不会考虑此处的调整，目前可以在授权管理中给出查看权限临时解决你的这个问题，我们将会在后续的大版本中优化此处的逻辑处理，感谢你的建议与反馈。
