### ISSUE TITLE
[Feature]在趋势图中点击某项单独显示而不是隐藏

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#4929]
经社区群用户反馈，建议在趋势图中可以增加类似grafana中点击某一项后只显示它自己那条线，而不是隐藏掉。
当存在多条趋势时，避免了要一个个点掉其它所有的

**Comment by fit2cloud-yayanpei** [comment]
感谢反馈，此处我们暂不支持做优化，原因如下：
1、默认所有图例均显示，点击哪个图例修改自身的状态也比较符合操作习惯。
2、点击一个图例，其他的均隐藏，像一共5个图例，需要显示2个或者3个这种的场景不太好兼容。
3、折线图显示的线条数不建议太多，太多可能影响展示效果。建议线条数最多控制在5条左右，此时如果不需要展示的逐个点掉，操作上相对也不会太多。

再次感谢您的关注和支持～
