### ISSUE TITLE
[Feature]跳转设置为当前页面时，建议增加后退操作

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#4932]
跳转设置为当前页面时，当前点击后退会回到仪表板首页，用户要重新选到之前编辑的仪表板，操作不太方便，建议增加后退操作

**Comment by fit2cloud-yayanpei** [comment]
感谢反馈，受限于1.x的设计（每个仪表板没有独立的url），1.x版本上无法支持返回。我们已规划在2.0优化这里的设计。

再次感谢您的关注和支持。
