### ISSUE TITLE
[Bug]新建数据集后页面刷新出一个空白数据集选项

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#4935]
**DataEase 版本**
v1.18.6-rc1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 最新

**Bug 描述**
如动图，新建一个 SQL 数据集后，页面会刷新出一个空白名称的数据集，且点击无反应。刷新整个页面后才能看到新添加的数据集。
操作动图：
![iShot_2023-03-31_09 41 10](https://user-images.githubusercontent.com/30886198/229001968-e7b43c8d-4e5b-4f77-93fc-96c80d0a253d.gif)

刷新整个页面后的截图：
![image](https://user-images.githubusercontent.com/30886198/229001726-4848cc30-8966-4070-a334-a26b9dc60b27.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，目前正在修复，请耐心等候。

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已处理，请更新最新版本。
