### ISSUE TITLE
[Feature]地图跑马灯

### ISSUE THREAD

**Issue by zzx769394358** [dataease/dataease#4936]
**请描述您的需求或者改进建议.**
能否按照某指标顺序跑马灯点亮各个地区,
其中点亮的可以显示出自定义数据
![e8b0f9b49fe8d85e1f54ddae2cc2d30](https://user-images.githubusercontent.com/57294442/229014340-3a122b6e-b97c-4ce7-9ac0-efaa5b230ce8.jpg)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们会在2.0版本中考虑实现。
