### ISSUE TITLE
[Bug] doris fe经常会出现com.sleepycat.je.DiskLimitException

### ISSUE THREAD

**Issue by zijin-zj** [dataease/dataease#4940]
**DataEase 版本**
v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包
服务器配置8C16G

**浏览器版本**

**Bug 描述**
dataease的定时任务越来越来 数据量也越来越大 doris时不时会挂掉 主要是fe 经常会出现异常
[BDBJEJournal.write():153] catch an exception when writing to database. sleep and retry. journal id 5407038
com.sleepycat.je.DiskLimitException: (JE 18.3.12) Disk usage is not within je.maxDisk or je.freeDisk limits and write operations are prohibited: maxDiskLimit=0 freeDiskLimit=5,368,709,120 adjustedMaxDiskLimit=0 maxDiskOverage=0 freeDiskShortage=9,498,62

健康检查重启后，定时任务执行数据依然没有存储到doris be，但是定时任务的执行状态却是成功。

**Bug 重现步骤(有截图更好)**
doris fe异常（时间+8小时）
![image](https://user-images.githubusercontent.com/48403386/229052501-5c01e7f0-ea52-4c0d-a143-6a1349dc6038.png)

定时任务执行状态
![image](https://user-images.githubusercontent.com/48403386/229052326-65001578-ca42-42f7-87be-fbfbc3288d93.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，应该是doris自身问题导致，目前平台使用的doris 1.1存在内存占用问题，长时间的数据io导致内存被占，但是新版本的doris依旧修复了此处的问题，平台因为兼容问题没有做此处升级，你可以自己尝试升级看一下，或者调整/opt/dataease/conf/fe.conf文件中的JAVA_OPTS参数调大它作为临时解决方案，但因为doris这个版本自身存在这个问题，最终还是会被占满导致崩溃，这里我们在后续的大版本会有调整，你可以稍稍的期待一下😝

**Comment by BBchicken-9527** [comment]
不知道是否还有其他问题？若没有问题问题将会在今天下午六点半关闭；
