### ISSUE TITLE
[Feature]希望支持同一个事实表多级汇总

### ISSUE THREAD

**Issue by Xiaosade** [dataease/dataease#4947]
**请描述您的需求或者改进建议.**
没有使用ods，直接从数据源定时抽取到轻度汇总（By Day)后，有时还需要By week或By month进行汇总，整体字段不变，希望增多级汇总的设计，以更大程度上提高效率。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，如果需要多级汇总，建议您做如下操作：
第一种方式，创建多个sql数据集，分别根据week或者month进行汇总。
第二种方式，按天进行汇总生成数据集后，新建计算字段：week、month，在视图制作时，选择week或者month进行汇总。

**Comment by Xiaosade** [comment]
第二种方式适用场景有限，当用于sku时，数据量太大，视图运算占用大量浮点资源，前端明显感觉到卡顿。
目前在使用第一种方式。但是这样会也会有数据量的问题：生产库按天做了轻度汇总，就不希望再重复到生产库获取序时明细数据（量太大），而希望在by day的轻量汇总后再上向汇总。
