### ISSUE TITLE
访问不了在wsl中启动的项目地址

### ISSUE THREAD

**Issue by gtrgeg** [dataease/dataease#4948]
在wsl执行 /bin/bash install.sh后显示成功，但是在页面上无法访问，详情如图：
<img width="480" alt="ttttt" src="https://user-images.githubusercontent.com/47472797/229403994-ad5589ef-e824-4fef-a30b-aff557705ded.png">
<img width="1280" alt="uuuuu" src="https://user-images.githubusercontent.com/47472797/229403997-ef3f050a-4044-43e4-b0e0-4de82a2f89bd.png">
<img width="1280" alt="yyyyyy" src="https://user-images.githubusercontent.com/47472797/229403999-d2f9a33c-18c4-4f60-a397-19a834544aa4.png">

**Comment by xuwei-fit2cloud** [comment]
建议换成root用户，再次执行一下bash install.sh脚本。
