### ISSUE TITLE
[Feature]权限管理功能可以控制仪表板的创建权限

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4949]
**请描述您的需求或者改进建议.**
使用场景：给公司销售的同事开通了DataEase的账号，用于销售同事登陆进来查看仪表板，但是希望销售只能查看仪表板，不希望销售有创建仪表板的权限。
目前无法做到控制

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们会在2.0版本中对此进行相关优化，当前的1.x版本暂不做调整。
