### ISSUE TITLE
[Bug]仪表板创建公共链接，换一个浏览器访问此公共链接，导出excel异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4950]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
仪表板创建公共链接，换一个浏览器访问此公共链接，仪表板中的明细表导出excel异常
仪表板无反应，F12打开控制台有异常
看后台日志也有异常输出

**Bug 重现步骤(有截图更好)**
![wecom-temp-32107-37e5a43066e9c8a4d6fb8d7eea8449d5](https://user-images.githubusercontent.com/89771514/229446744-4fcb6225-9e36-4c7f-8580-45693f8404ea.png)
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/89771514/229446743-187e073f-226b-41cb-932f-5ff53bef0580.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，嗯... 目前测试环境没有发现你说的这种情况，受累补充一下更详细的步骤呢？
![图片](https://user-images.githubusercontent.com/84372766/229448460-42373849-b81e-4e93-8ad3-24f5db24b754.png)

**Comment by zzx769394358** [comment]
仪表板创建公共链接，换一个浏览器(记得清缓存) 访问此公共链接, 
 这时候 入参componentFilterInfo 是没有user值的
![image](https://user-images.githubusercontent.com/57294442/229759377-705ee998-02ec-43c8-8441-fd1862e94b66.png)

这个时候 DataSetTableService 506行的user就是空, 
然后因没有登录信息,  AuthUtils.getUser()也为空, 所以currentUserDto.getUserId()空指针
