### ISSUE TITLE
[Question]升级版本的时候报错，然后一直起不来

### ISSUE THREAD

**Issue by dev-lcl** [dataease/dataease#4952]
**请描述您的问题.**
Creating network "dataease_dataease-network" with driver "bridge"
ERROR: Failed to Setup IP tables: Unable to enable SKIP DNAT rule:  (COMMAND_FAILED: '/usr/sbin/iptables -w2 -t nat -I DOCKER -i br-d46c4038f275 -j RETURN' failed: iptables: No chain/target/match by that name.
)
以上，请问怎么解决呢

**Comment by xuwei-fit2cloud** [comment]
如果没有其他的docker容器处于运行状态，可以执行一下service docker restart，重启一下docker服务试试。
