### ISSUE TITLE
[Question]本地源码启动

### ISSUE THREAD

**Issue by zzx769394358** [dataease/dataease#4953]
**请描述您的问题.**
启动后端Application.java
启动前端frontend:    npm run dev
![image](https://user-images.githubusercontent.com/57294442/229473044-8b7a885b-b0e0-45a8-9073-da0f8af18d08.png)

分享仪表盘链接打开,  
![image](https://user-images.githubusercontent.com/57294442/229473329-de896964-183f-40b7-99d7-8f5fe07e3159.png)

看过文档 源码部署-编译运行,  是以打包的方式吧? 我想要本地调试

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，源码部署不是以打包的形式，需要您下载源码，在本地运行、调试。
