### ISSUE TITLE
[Feature] 【API URL 编码自动解析】

### ISSUE THREAD

**Issue by Guojunwei888** [dataease/dataease#4955]
**请描述您的需求或者改进建议.**
你好，为什么DataEase API 数据源需要经过 encodeURL 之后才能解析呢，你们的设计思路是怎么样的？
![Escape 编码字符串出错界面](https://user-images.githubusercontent.com/55652988/229666707-e0777677-9e94-465f-8745-00e823da44f2.png)

传进来的 URL 是否可以进行一个特殊符号判断，根据特殊字符的判断结果自动实现 URL 的转码过程，不需要客户自己自行 encodeURL 编码之后才能置入 DataEase 中，这是不是一个可以优化的点？

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们讨论一下这个地方的优化方案。
