### ISSUE TITLE
[Bug]选项卡组件tab页过多时，轮播标题被遮挡，看不见标题了

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4956]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
tab切换头部设置对其方式为居中，开启轮询后，前两个tab的头部就不显示了，实际还是在轮播的
宽度小于所有tab的情况下才能复现，居中和居右都有问题哈

**Bug 重现步骤(有截图更好)**
<img width="705" alt="wecom-temp-98164-ad505bfebc9757f97a9fadcb8a13f697" src="https://user-images.githubusercontent.com/89771514/229700105-87cb53ca-fd14-45be-8ca3-fb8d47df00fc.png">
<img width="555" alt="wecom-temp-75696-6159d0e562a8ecd93bd779d8a2f26e04" src="https://user-images.githubusercontent.com/89771514/229700128-f539795a-afd8-42e0-befb-b8ac0ec085b7.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已处理，请更新最新版本。
