### ISSUE TITLE
[Feature]数据源接入以及数据限流管控

### ISSUE THREAD

**Issue by zhugezifang** [dataease/dataease#496]
**请描述您的需求或者改进建议.**
(1)能否支持更多的数据源，包括 api、还有一些其他的数据库
(2)在数据配置当中，能否做一些限流管控。
比如某个用户新建了图表，查询数据，而写sql导致性能极差，因此就会出现拖垮整张表或者整个库，不知道是否会有这方面的处理
(3)后续是否会支持大屏相关的需求呢？

**Comment by yayanpei** [comment]
非常感谢您的反馈，您的建议对我们很重要。
（1）支持丰富的数据源，是我们产品的方向，9月份的V1.2.0版本会增加支持sql server数据库、PG数据库和API。
（2）限流管控，我们会重点考虑，能否纳入产品中。
（3）产品目前是支持大屏的，建议您将仪表板调整为全屏模式。

**Comment by zhugezifang** [comment]
大屏主要指的是动态特效相关，报表的话一般都是没什么太多特效的，主要是指这块

**Comment by xuwei-fit2cloud** [comment]
大屏的实现会放在未来的2.0版本中，短期内还不会支持。
