### ISSUE TITLE
[Bug]创建数据集时，使用默认驱动，kettle无法连接到数据源

### ISSUE THREAD

**Issue by lyons-hz** [dataease/dataease#4960]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**

**Bug 描述**
安装模式：cluster
外置kettle和Doris
kettle版本：pdi-ce-8.3.0.0-371
数据源版本：Mysql  5.7.39
创建数据集时，使用默认驱动连接Mysql数据源，连接超时。

**Bug 重现步骤(有截图更好)**
1.创建数据集时使用默认驱动，连接超时
<img width="647" alt="image" src="https://user-images.githubusercontent.com/89773363/229717582-e8ec84a8-5329-406f-afe7-1f28f932d3fc.png">
<img width="594" alt="image" src="https://user-images.githubusercontent.com/89773363/229717657-364c158c-78f0-44fb-8b91-fcf2d7a4d4ba.png">

注：使用自己上传的驱动可以正常连接数据源，但是创建数据集时没有定时同步功能。

**Comment by tjlygdx** [comment]
1、创建数据集时使用默认驱动时，确保源码中drivers/下的驱动已经放置在目录：/opt/dataease/drivers
2、使用自己上传的驱动时，应为没发把驱动同步放置到kettle中，所以把【创建数据集时定时同步功能】屏蔽掉了
