### ISSUE TITLE
[Feature] 建议在数据集导出时，点击确认按钮后增加遮罩层或禁用导出按钮，出错时给出提示

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#4961]
**请描述您的需求或者改进建议.**
1. 点击数据集导出弹窗中的确认按钮后，如果数据量过大或者后台响应慢，页面没有任何反应，操作者会认为操作未生效从而多次点击按钮。此时会出现连续下载多个文件问题。
![image](https://user-images.githubusercontent.com/30886198/229738239-0515418b-a25b-48a6-bb18-4663fbb2ac3d.png)

2. 当下载报错时页面没有任何提示，不太友好，建议添加合理提示
![image](https://user-images.githubusercontent.com/30886198/229739465-9aed6423-d3c0-4b7b-a163-83c73e39aa4e.png)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议很不错，我们会在最近的小版本中增加遮罩。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
