### ISSUE TITLE
[Bug]doris数据源小数类型处理异常

### ISSUE THREAD

**Issue by kunmeng** [dataease/dataease#4963]
**DataEase 版本**

1.18.2
**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome  111.0.5563.147（正式版本） （64 位）

**Bug 描述**
Dataease v1.18.2 做doris 1.2.3数据库的表格小数统计异常-20230404
#doris 表结构及测试数据
CREATE TABLE TEST_XS
(    id int,    cls  varchar(10),    v_int int,    v_decimal  DECIMAL(6, 2) ,
    v_decimalV3  DECIMALV3(6, 2) ,    v_double double ,    v_float float 
) ENGINE=OLAP
DUPLICATE KEY(`id`)
DISTRIBUTED BY HASH(`id`) BUCKETS 10
PROPERTIES ("replication_allocation" = "tag.location.default: 1","in_memory" = "false","storage_format" = "V2","disable_auto_compaction" = "false");
INSERT INTO TEST_XS VALUES (1, 'c1',1,10.3,10.3,10.3,10.3);
INSERT INTO TEST_XS VALUES (2, 'c2',1,10.3,10.3,10.3,10.3);

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/9875584/229755077-a2092b9f-19ee-4533-804e-804524947a8e.png)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你使用的doris版本是多少呢？还有是定时任务还是直连的呢？如果是直连的那创建定时数据集是否有此类问题呢？

**Comment by BBchicken-9527** [comment]
感谢反馈，我们看了一下确认之前.2版本确实存在此问题，但在.3做了修复，你可以尝试更新一下看一下是否还存在此问题。

**Comment by ZhaoQian1222** [comment]
这个问题解决了，升级后就没问题了
