### ISSUE TITLE
[Bug]数值区间组件没有横向居中，当上下距离设置较小有一半的搜索框显示不出

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4969]
**DataEase 版本**
1.19.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
数值区间组件没有横向居中，当上下距离设置较小有一半的搜索框显示不出
![wecom-temp-44928-0f886541ecb6c20e29ac2021c09cd894](https://user-images.githubusercontent.com/89771514/230283007-ec26b295-ba64-44d7-91b1-1327deed7c72.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快优化的
