### ISSUE TITLE
[Feature] 新建用户时，用户 ID 允许以数字开头

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4970]
**请描述您的需求或者改进建议.**
新建用户时，用户 ID 允许以数字作为开头，主要考虑到很多公司会以员工工号作为用户 ID 登录，员工工号很多情况下都是纯数字的情况。
![image](https://user-images.githubusercontent.com/30063018/230289087-dba7d6a5-62f7-4260-9172-cfb281001f34.png)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，您的建议很不错，我们已规划在2.0放开ID的限制，允许纯数字或者数字开头的形式。

**Comment by yayanpei-fit2cloud** [comment]
Issue先关闭了，再次感谢您的关注和支持。
