### ISSUE TITLE
[Feature] 视图下钻的同时支持联动其它视图。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#4971]
**请描述您的需求或者改进建议.**
视图下钻的同时支持联动其它视图。
2.0 是否可以考虑支持该功能，会使得仪表板的交互性更好。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录并放入2.x的需求池中，后续还需要进一步的调研。
