### ISSUE TITLE
[Feature]【仪表板】仪表板功能优化

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#4973]
**请描述您的需求或者改进建议.**
打开一个仪表板就会在历史页签栏加上一个页签，打开新的旧的仪表板页签还在历史页签栏，用户可以自己关闭页签栏。
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/24768910/230296570-5816b4b9-7ec4-4f00-8a68-524c4f897e7b.png">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前我们并没有相关的调整计划。
当前DataEase的仪表板列表，点击列表项，本身就会直接打开仪表板；
另外，使用tab页的形式对资源的占用也会比单个页面中打开要高一些。
