### ISSUE TITLE
[Feature]【仪表板】默认仪表板可以创建文件夹，并且可以做权限管控

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#4974]
**请描述您的需求或者改进建议.**
【仪表板】默认仪表板可以创建文件夹，并且可以做权限管控。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，用户将仪表板设置为默认后，可以在默认中快捷查看，权限管控还是在原仪表板中控制。
这里我们就不再做优化了，issue先进性关闭了，再次感谢您的关注和支持。
