### ISSUE TITLE
[Bug]ES数据源，两个数据库数据集关联异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4976]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
ES数据源，两个数据库数据集关联，创建关联数据集异常
![image](https://user-images.githubusercontent.com/89771514/230342226-88677d0e-cce8-4e4c-8d70-9cad699900f9.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们确认一下

**Comment by BBchicken-9527** [comment]
感谢你的反馈，我们会尽快修复的；

**Comment by BBchicken-9527** [comment]
你好我们发现es是无法支持join的，我们后续考虑更完善的解决方式；目前此处将不做修改，感谢你的支持与反馈
