### ISSUE TITLE
[Bug]新版的docker compose命令没有中间的-，安装脚本自动检测到存在docker，docker-compose 是旧版的命令格式，导致无法安装

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4977]
**DataEase 版本**
v1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
新版的docker compose命令没有中间的-，安装脚本自动检测到存在docker，docker-compose 是旧版的命令格式，导致无法安装
install.sh 安装脚本文件需要修改

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
