### ISSUE TITLE
[Bug]API数据源数据显示问题

### ISSUE THREAD

**Issue by Silecne666** [dataease/dataease#4978]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**

**Bug 描述**
使用API数据源，如果响应的数据中，某个字段是数组形式，则在数据集中，同一条数据会分成多条数据显示

**Bug 重现步骤(有截图更好)**
1.新建API数据源
2.在数据集中引用API数据源
3.展示如下
![image](https://user-images.githubusercontent.com/58200177/230523225-82deb920-bddb-4a03-8c01-2fcb628b4ccc.png)
具体数据格式如下：
{
  "code": 200,
  "data": {
    "deviceTypeCode": "0249",
    "termId": "5870135",
    "addTime": "2023-03-15 09:10:00",
    "payload": {
      "exception": [
        2
      ],
      "snapshots": [
        {
          "dataCells": [
            "0"
          ],
          "serial": 1,
          "timestamp": "2023/03/14 16:19:31"
        },
        {
          "dataCells": [
            "0"
          ],
          "serial": 2,
          "timestamp": "2023/03/14 16:34:31"
        },
        {
          "dataCells": [
            "0"
          ],
          "serial": 3,
          "timestamp": "2023/03/14 16:49:31"
        }
      ],
      "rssi": 13,
      "channels": [
        {
          "channelSerial": 2,
          "dataCellCode": "PRE",
          "dataCellUnit": "Pa"
        }
      ],
      "optimized": null,
      "sn": "000000000000",
      "connectNetCount": 3,
      "voltage": {
        "type": "DC",
        "value": 3686
      },
      "gatherMeta": {
        "actual": 3,
        "baselineTime": "2023-03-14 16:04:31",
        "intervalUnit": "m",
        "interval": 15,
        "capacity": 32
      }
    },
    "appId": "29",
    "mid": "fd8fb5d0e200436f9d438caf80121a43",
    "channelType": "NB",
    "deviceCode": "111896120601",
    "time": "2023-04-04T09:56:41.871+08:00",
    "userId": "36",
    "status": "0"
  },
  "msg": "success",
  "total": 0,
  "pageCount": 0,
  "pageNow": 0,
  "pageSize": 0
}

**Comment by BBchicken-9527** [comment]
感谢反馈，你是使用勾选的方式去筛选数据的吗？如果是勾选的方式我没发现解析有什么问题

**Comment by Silecne666** [comment]
具体操作步骤是：在新建数据源的时候，在提取数据时，选择了相关的数据，如图1；在数据集中，展示的是3条数据，但是本质上一条数据，如图二
![image](https://user-images.githubusercontent.com/58200177/230547764-32e61a97-af13-4d75-9639-d5d17c3a5865.png)
![image](https://user-images.githubusercontent.com/58200177/230547812-aa14e4a5-5d3d-41a5-862d-79dc6909af21.png)
或者：可以去你们的demo案例中，查看具体情况
![image](https://user-images.githubusercontent.com/58200177/230547987-86ae6e7b-c445-4581-b506-aa54181bf6ca.png)
![image](https://user-images.githubusercontent.com/58200177/230548044-34e31b74-0b26-485c-aa8c-99dd658edb95.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，了解了你的困扰，是这样的，如果你以勾选的方式去筛选的话是会将数据以字段去拆分的，设计就是这样的，但如果你想只有有一条数据可以通过创建时的jsonpath提取，向你说的只要一条就直接$就可以了，并且在创建的时候是可以预览到产出的数据的，如果你觉得不合适可以及时通过jsonpath方式修改或者勾选方式修改都是可以的；
![图片](https://user-images.githubusercontent.com/84372766/230568610-0e982158-814f-4191-9e05-d910fa49db76.png)

**Comment by BBchicken-9527** [comment]
感谢你的热爱与支持，若没有其他问题问题将在今天下午六点半关闭此问题

**Comment by dldxz** [comment]
如果数据格式类似于下方这种，能否通过jsonpath匹配所有需要的字段，我也碰到了这个问题，如果使用自动匹配的话，数据表里面会出现只有一个字段有值的空数据，本质上是另一条数据中，字段类型是json数组的产生的数据，我尝试使用jsonpath匹配items数组，这时像application字段，在数据表中保存的格式又不对了，不是标准json格式，而是类似于这种{id=48, created_at=2026-01-08T16:36:41.169+08:00, updated_at=2026-01-08T16:36:41.169+08:00, name=aaa}，关于这个问题我提了一个[issues](https://github.com/dataease/dataease/issues/17772)，如果能够通过jsonpath解决的话，那么issues可以关了
{
  "code": 200,
  "data": {
    "items": [{
      "application": {
        "id": 49,
        "created_at": "2026-01-09T15:47:46.772+08:00",
        "updated_at": "2026-01-09T15:47:46.772+08:00",
        "name": "aaa"
      },
      "assignees": [{
        "id": 1,
        "created_at": "",
        "updated_at": "",
        "username": "aaa"
      },{
        "id": 2,
        "created_at": "",
        "updated_at": "",
        "username": "bbb"
      }],
      "created_at": "2026-01-09T15:56:10.12+08:00",
      "creator": {
        "id": 8,
        "created_at": "2025-09-23T09:19:01.74+08:00",
        "updated_at": "2026-01-09T10:36:32.837+08:00",
        "username": "ccc"
      },
      "description": "",
      "id": 1,
    }],
    "total": 1
  },
  "message": "success",
  "time": 1768188880
}
