### ISSUE TITLE
[Feature]明细表汇总方式建议增加个无，有的数据只是展示不一定汇总

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#498]
**请描述您的需求或者改进建议.**
明细表汇总方式建议增加个无，有的数据只是展示不一定汇总
![image](https://user-images.githubusercontent.com/35896106/127974884-cbc5acc2-165a-498a-b992-7f81d516ef3f.png)

**Comment by yayanpei** [comment]
非常感谢您的反馈，我们规划在V1.3.0中纳入此优化

**Comment by xuwei-fit2cloud** [comment]
v1.3.0 已处理
