### ISSUE TITLE
[Bug]打开一个仪表板未加载完成，再打开第二个仪表板会很慢

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4980]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
打开一个仪表板，该仪表板内容很多，未加载完成，或者加载超时一直转圈时，这时再打开第二个仪表板，是无法打开的
它要等第一个仪表吧那加载完成才会打开第二个。
此处的逻辑是否可以改一下？
**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，感觉到慢是因为服务器还在计算之前的仪表板任务导致，目前没有更好的方法解决这里；
