### ISSUE TITLE
[Bug]SQL数据集变量设置存在失效的情况

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4981]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**

SQL语句如下：

SELECT t_zhihu_answer.*,user.orgnization from t_zhihu_answer
left join user on user.show_name = t_zhihu_answer.`user`
WHERE t_zhihu_answer.`user` in (
 SELECT `user` from t_zhihu_answer where title in(select t2.title from t_zhihu_answer t2 where  t2.`user`='${user}' and t2.title='${title}')
)
and user.orgnization="${orgnization}"

![image](https://user-images.githubusercontent.com/89771514/230568862-59f31a44-8c15-4fa2-9383-183c8d99ddcc.png)

![image](https://user-images.githubusercontent.com/89771514/230568773-533546c2-7a8b-44c2-956c-8a0a94629b84.png)

从上面的数据集中可以看到设置了 user、title、orgnization三个变量

数据集中存在user 和 orgnization字段，当修改 user 和 orgnization参数时，在这两个字段上查询到的数据应该会体现变化
数据预览看到的效果是没问题的。

当我在仪表板视图中添加两个文本下拉组件时，user参数不生效了
![image](https://user-images.githubusercontent.com/89771514/230569489-9817bd60-df5a-47a6-ba6e-603d269ac915.png)
![image](https://user-images.githubusercontent.com/89771514/230569647-6abac60c-403c-41da-8cc4-428f61c51f6c.png)
从上面的截图可以看到，选择赵乾时，查询出来的数据并不全是赵乾的数据

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
