### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by PheonixHkbxoic** [dataease/dataease#4982]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
源码运行，前后端分离部署, stage

**浏览器版本**
版本 111.0.5563.147（正式版本） （64 位）

**Bug 描述**
企业微信扫码登陆，自动跳转到: 域名/de-api，导致404

**Bug 重现步骤(有截图更好)**
/plugin/wecom/callBack

**Comment by PheonixHkbxoic** [comment]
![image](https://user-images.githubusercontent.com/16241829/230577747-2369ecf7-ac29-4fb1-9a37-d79632c95d4a.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前企业微信是xpack功能 只支持标准产品的。

**Comment by BBchicken-9527** [comment]
你好，不知道是否还有其他疑问呢？若没有其他问题我将会在今天六点三十分前关闭，期待你再次反馈；
