### ISSUE TITLE
[Bug]权限管理功能中角色数据行权限冲突时，权限失效，数据看不到了

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#4983]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
给一个人配置例如4个角色，这4个角色对同一个数据集有不同的行权限，导致这个人查看该数据集制作的仪表板时没有数据显示
![image](https://user-images.githubusercontent.com/89771514/230593491-6d0e844b-a3ab-4866-b03c-b1fd825bdb94.png)
![image](https://user-images.githubusercontent.com/89771514/230593600-71fac649-aec2-4b54-8ce2-8a85469fdb89.png)
![image](https://user-images.githubusercontent.com/89771514/230593714-83dea857-4f33-4f4a-af8c-3af2a2d7b2f5.png)
![image](https://user-images.githubusercontent.com/89771514/230593779-f6e60bc5-3a74-471c-874f-e0bc9b857ccd.png)
![image](https://user-images.githubusercontent.com/89771514/230593830-d3d8eb69-d8f3-4554-8870-a0334585d4e6.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，涉及如此；权限限制是会重叠的，目前暂时没有修改这里逻辑的计划；

**Comment by ZhaoQian1222** [comment]
“权限限制是会重叠的”，这里的意思是所有相关角色被限制的内容的集合，在被赋予角色的用户查看数据时，都会被限制吗

**Comment by BBchicken-9527** [comment]
是的呢亲
