### ISSUE TITLE
[Feature]MySQL容器希望开启binlog

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4984]
**请描述您的需求或者改进建议.**
我们发现 MySQL 开启binlog 可以解决误删除的场景，可以快速回退；
但 MySQL 容器中没有mysqlbinlog 命令，无法进行恢复 binlog
mysql 镜像能否加上 mysqlbinlog 程序，并默认开启 binlog

**Comment by xuwei-fit2cloud** [comment]
感谢反馈。
我们认为这个其实应该是回收站的需求，我们会在2.x版本中新增对回收站的支持。

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已更新MySQL镜像，请更新最新版本。
