### ISSUE TITLE
[Bug]动态时间过滤组件不会自动刷新

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#4985]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
仪表板上设置动态时间过滤组件，下图是：昨天，通过公共链接访问仪表板，电脑一直开着，第二天动态时间并未刷新
4月8号 查看的仪表板，动态时间应该是4月7号，浏览器仍然显示4月6号，包括动态时间控制的指标卡也未更新。仪表板中其他视图都自动刷新了最新数据。
这时需要手动刷新浏览器，动态时间才会更新。
![图片](https://user-images.githubusercontent.com/48307752/230690088-95b320d1-1fee-4d2a-b342-6875ce09642f.png)

**Bug 重现步骤(有截图更好)**
1.仪表板加入时间过滤组件，设置动态时间；
2.放一晚上，第二天查看动态时间有没有更新。
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，请问一下你的仪表板刷新开启了吗？

**Comment by mfanoffice** [comment]
> 

仪表板定时刷新时每5分钟一次。内容是刷新的。仪表板放一晚上，第二天动态时间组件不会自动更新。手动刷新才会更新

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复的

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已处理，请更新最新版本。
