### ISSUE TITLE
[Bug]国际化失败

### ISSUE THREAD

**Issue by dzMoon** [dataease/dataease#4986]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**
谷歌83版

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1. 设置为简体中文
2. 点击导出pdf
3. 结果如图
![微信图片_20230409113428](https://user-images.githubusercontent.com/23649132/230752771-f545d6c3-c8b6-4b29-9b05-09d97f09da79.png)

4. 预期如图
![微信图片_20230409113455](https://user-images.githubusercontent.com/23649132/230752779-8ebae5a4-0ec8-45a7-a642-f758991c5491.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，其实这里显示是那种语言和国际化是没有关系的。这里是可以自行设置的

**Comment by BBchicken-9527** [comment]
你好，不知道是否解决了你的困扰呢，若没有其他问题将于今天下午六点半前关闭；感谢你的支持与反馈；
