### ISSUE TITLE
[Feature]表格中数据替换成图片

### ISSUE THREAD

**Issue by jstbw** [dataease/dataease#4988]
**请描述您的需求或者改进建议.**
如图所示，表格中高中低替换成相应的图片
![ecb8a0f7ef86cbe00512e3ba8cffd72](https://user-images.githubusercontent.com/66759501/230838539-7c498fc1-5554-4190-9585-511f847f1f90.png)
![ba7df24cb52cc1a2e7f193beccb67e4](https://user-images.githubusercontent.com/66759501/230838568-8dacf825-f81f-4f3b-9fb3-565ce7de89b0.png)

**Comment by yayanpei-fit2cloud** [comment]
感觉您的反馈，我们需要讨论一下。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前2.0的表格方案还没有确定，等方案确定下来以后我们再讨论该需求。

**Comment by zsnmwy** [comment]
这个似乎还没支持？请问后续有计划支持吗？

我是希望可以将数据表中的图片URL转换为图片展示。
不然像我们这种商品图就没办法对应展示，不够直观。

<img width="745" alt="image" src="https://github.com/dataease/dataease/assets/35299017/6f2742f2-0018-41fc-98ee-9f662cf2699f">
