### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by wolfkill** [dataease/dataease#4990]
**请描述您的需求或者改进建议.**
excle类型的数据源，日期格式不支持“年-周”这种格式

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，可以在视图制作时，直接选择日期的显示格式为“年周”，如下图所示：
![image](https://user-images.githubusercontent.com/84168063/231033944-b2868a42-3b7e-416e-a41b-3430cba63b52.png)

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已支持，请更新最新版本。
