### ISSUE TITLE
时间组件日期过滤bug[Bug]

### ISSUE THREAD

**Issue by putaopin** [dataease/dataease#4991]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
源码运行 和 安装包运行

**浏览器版本**
谷歌版本 91.0.4472.114

**Bug 描述**
用时间组件过滤数据时会过滤不准。比如我选年份组件，我得数据库存储得时间格式是年月格式。会遗漏掉一月份得数据。经过排查发现是时间格式转化得问题。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/35058324/230848377-93b9cc1b-9ce9-42af-8d93-a8775552497b.png)
下边是打印出来得sql
![image](https://user-images.githubusercontent.com/35058324/230848633-ff9906b8-b986-400c-b64b-36dc70e3ffff.png)
可以看出l来是格式不匹配 条件加了毫秒，匹配字段没加

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已处理，请更新最新版本。
