### ISSUE TITLE
建议同一个面板里面可以针对时间的不同维度做展示[Feature]

### ISSUE THREAD

**Issue by huhutouch** [dataease/dataease#4992]
比如A面板里面有a b c d e 5个视图，而这5个视图希望有个按钮可以选择：按周、按月、按年的形式展示
目前只能分别建立不同时间维度显示的仪表板 或者编辑不同视图显示模式

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，视图的显示内容和形式，是在视图制作时完成的，一般不建议通过其他操作方式改变视图的展示形式。根据您描述的场景，建议您做如下操作：
1、用tab组件，比如tab项（周）中，添加按周统计的视图；tab项（月）中，添加按月统计的视图；tab项（年）中，添加按年统计的视图。
2、通过切换tab项（周、月、年），然后查看不同形式的视图。
