### ISSUE TITLE
[Bug] SQL 数据集设置参数变量，保存失败

### ISSUE THREAD

**Issue by gaohonghai** [dataease/dataease#4994]
**DataEase 版本**
1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
112.0.5615.49

**Bug 描述**
在编辑 SQL 数据集（SQL server）的时候，设置了 SQL 数据集，可以正常运行查询，但是点击保存之后，提示保存“无法绑定由多个部分组成的标识符“json.n_serial””

**Bug 重现步骤(有截图更好)**
1.编辑 SQL 数据集，设置参数变量（客户设置了两个参数）；
![image](https://user-images.githubusercontent.com/92966838/230867507-fe995eec-b016-480b-95ec-d8b851e9fc4b.png)
2.直接点击运行查询，可以查询成功；
![image](https://user-images.githubusercontent.com/92966838/230867661-e327b9bd-eeb3-49da-953f-71f58f3ad5d3.png)
3.点击保存，提示下述保存；
![image](https://user-images.githubusercontent.com/92966838/230867573-51e2c8a3-4bf9-4ea7-b47f-fa60e80edc41.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，方便给出你的sql语句我们这边复现一下吗？目前单纯的提示无法判断到底是哪里导致的

**Comment by gaohonghai** [comment]
`SELECT 结算时间, total AS 总门诊量, 诊间结算总笔数
 , 电子凭证结算笔数, 非电子凭证结算笔数 FROM (
 SELECT CONVERT(varchar(100), invoice.d_input_time, 23) AS 结算时间, 
  SUM(CASE 
   WHEN josn.n_serial IS NULL THEN n_money
   ELSE 0
  END) AS 非电子凭证结算金额, COUNT(1) AS 诊间结算总笔数
  , SUM(CASE 
   WHEN josn.n_serial IS NULL THEN 0
   ELSE 1
  END) AS 电子凭证结算笔数, SUM(CASE 
   WHEN josn.n_serial IS NULL THEN 1
   ELSE 0
  END) AS 非电子凭证结算笔数
 FROM dbo.HIS_patient_invoice invoice
  LEFT JOIN HIS_yb_json josn
  ON (josn.s_safety_no = invoice.s_safety_no
   --AND charindex(invoice.s_bill_no, s_reply_json) > 0
   AND charindex('"bke284":"06"', s_request_json) > 0)
 WHERE (invoice.d_input_time BETWEEN ${param_data1} AND ${param_data2}
  AND s_operator NOT LIKE '%350%'
  AND s_operator NOT LIKE '%自助%'
  AND s_operator NOT IN ('周泉霞')
  AND s_operator NOT IN (
   SELECT s_name
   FROM dbo.Public_sysuser
   WHERE s_office = '0102010000'
  )
  AND s_write_off = '0'
  AND invoice.s_safety_no <> '/')
 GROUP BY CONVERT(varchar(100), invoice.d_input_time, 23)
) a
 INNER JOIN (
  SELECT SUM(CAST(pocu.n_cure_number AS FLOAT)) AS total, convert(date, d_input_time) AS 录入时间
  FROM VW_HIS_patient_out_cure pocu
   INNER JOIN dbo.Public_office ks ON LEFT(pocu.s_office_doctor, 6) + '0000' = ks.s_mark
  WHERE (pocu.d_input_time BETWEEN '2023-03-01' AND '2023-04-02'
   AND s_cure_name LIKE '%挂号费'
   AND (pocu.s_charge_mark = '1')
   AND (ks.s_mark <> '0103000000'))
  GROUP BY convert(date, d_input_time)
 ) b
 ON a.结算时间 = b.录入时间`

**Comment by BBchicken-9527** [comment]
![图片](https://user-images.githubusercontent.com/84372766/231113815-620c8e54-90fc-4803-b00a-1dd8ff6277a9.png)
这里的变量添加单引号呢？
