### ISSUE TITLE
[Feature]轴值设置支持最大值最小值的动态值

### ISSUE THREAD

**Issue by sliverTwo** [dataease/dataease#4997]
**请描述您的需求或者改进建议.**
echart最小值设置是支持设置函数和数据的最小值的，目前dataease只支持浮点数，有些场景不能满足需求。
![image](https://user-images.githubusercontent.com/29396611/231038218-7e0c7483-4be1-4e95-ac2a-b8e896cef353.png)
![image](https://user-images.githubusercontent.com/29396611/231038259-e29d16a4-33f8-46ed-8d2b-0ef863471c37.png)

**Comment by sliverTwo** [comment]
> 您的需求应该是轴值设置支持最大值最小值的动态值吧，这个我们先记录一下，会在2.x版本中进行实现。
根本原因是：
当折线图存在多条线段时，其Y轴值差异可能较大，但是根据场景需求，需要在同一个图中显示，在实际查看的时候，有些时候只要关注其中一条的波动，但由于Y轴范围问题，导致显示不出波动趋势，期望能够通过查询条件自定义。具体场景比如：熔炉温度： A熔炉的范围是 800 -1200度， B熔炉的温度范围在 1300 - 1500度， 需要同时在一个图中展示，而有的时候只需要看其中一条的范围波动

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈与建议，功能：在视图查看时，能够自定义查询条件，从而使视图重新展示。我们预计会在2.0的版本稳定使用后增加该功能。
