### ISSUE TITLE
[Bug] 新建视图计算字段，待选择字段类型与当前字段类型不匹配（显示为修改前的）

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#4999]
**DataEase 版本**
v1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
新建视图计算字段，待选择字段类型与当前字段类型不匹配（显示为修改前的）

**Bug 重现步骤(有截图更好)**
1.修改字段类型
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/45852479/231075362-c8e6900d-952b-4ee5-8997-f054eb9a2188.png">
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/45852479/231075389-6c8d0a2c-cec5-4ea7-bf63-60e52df0ab13.png">
2.新建视图计算字段
3.字段显示类型和当前类型不匹配
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/45852479/231075527-110779ed-0591-492e-b5be-377a32bbef85.png">
数据集计算字段无此问题

**Comment by BBchicken-9527** [comment]
感谢反馈，这个是对的，显示的就是源数据字段类型的

**Comment by MaekBlack** [comment]
这个是数据集计算字段那边的截图
<img width="934" alt="image" src="https://user-images.githubusercontent.com/45852479/231131968-33fadb29-0486-4497-99ab-1afc8c415cd1.png">

**Comment by BBchicken-9527** [comment]
嗯嗯 ，这两个是不一样的，数据集显示的是改变后的字段类型，视图计算字段显示的是原始数据类型，这两种计算字段是有区别的；
