### ISSUE TITLE
建议非直连数据添加完数据集后默认同步一次

### ISSUE THREAD

**Issue by plateauandsp** [dataease/dataease#5]
非直连数据集需要先同步这个提示，应该在添加完数据集后提示，或者默认同步一次
![image](https://user-images.githubusercontent.com/30932762/123370232-e2724780-d5b1-11eb-8081-2aa6527103f6.png)

**Comment by xuwei-fit2cloud** [comment]
我们先计划一下，争取在 v1.1.0 版本中加入。

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已支持
