### ISSUE TITLE
[Question] v1.1.0 版本规划

### ISSUE THREAD

**Issue by maninhill** [dataease/dataease#50]
**请描述您的问题.**

v1.1.0 的版本规划及发布时间？

**Comment by xuwei-fit2cloud** [comment]
## 仪表板

1. 支持直接添加视图
2. 支持视图复制

## 视图

1. 支持更换数据集

## 数据源

1. 支持 Oracle

## 系统管理

1. 支持任务中心，可对定时任务进行全生命周期管理
2. 支持消息通知中心

**Comment by maninhill** [comment]
1.1.0-rc1 已经发布，具体请看：https://github.com/dataease/dataease/releases/tag/v1.1.0-rc1
