### ISSUE TITLE
[Question]linux上启动不了项目

### ISSUE THREAD

**Issue by gtrgeg** [dataease/dataease#5001]
启动项目的时候报错了，提示访问不到阿里云
![image](https://user-images.githubusercontent.com/47472797/231083339-65f19b10-b946-4e9c-853f-d7c348495400.png)
该咋办

**Comment by xuwei-fit2cloud** [comment]
是否修改了docker的镜像源？可以改回默认源试试。
我们的镜像都是在阿里云的镜像服务上的，国内访问的话速度应该还可以，不需要走mirror。
