### ISSUE TITLE
[Bug]【仪表板】下拉树数据组件空数据问题修复

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5003]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
下拉树组件会出现空数据，希望可以修复

**Bug 重现步骤(有截图更好)**
1.数据结构如下：
![image](https://user-images.githubusercontent.com/24768910/231134146-abd4e68b-1d0b-4057-9a93-39026c1c11a1.png)

2.下拉树显示情况
![image](https://user-images.githubusercontent.com/24768910/231134255-6c8a0aac-6b84-4022-bdfc-483e4ef3eeb6.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们讨论一下
