### ISSUE TITLE
[Bug]小数数值展示问题

### ISSUE THREAD

**Issue by zzx769394358** [dataease/dataease#5004]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
谷歌

**Bug 描述**
对于小数数值, 有时候后面会加6个0

**Bug 重现步骤(有截图更好)**
1. 创建数据集:     SELECT ROUND(COUNT(1)/100,2) FROM area_mapping
2. 创建仪表盘  创建视图
3.  
![image](https://user-images.githubusercontent.com/57294442/231324259-3a574006-fe3d-4114-8e53-078650ab873f.png)

**Comment by zzx769394358** [comment]
在哪里设置呢, 系统全局  小数都只显示2位

**Comment by BBchicken-9527** [comment]
![图片](https://user-images.githubusercontent.com/84372766/231333180-16e26509-215b-4d8c-8225-c633f3e502b8.png)

**Comment by zzx769394358** [comment]
我这是'文本卡',  该字段是维度

**Comment by BBchicken-9527** [comment]
我看你这个是数值类型的，应该是指标卡吧
![图片](https://user-images.githubusercontent.com/84372766/231336932-617b645d-62bd-4ac6-9337-24fc64421231.png)

**Comment by BBchicken-9527** [comment]
你好，不知道是否有帮到你，若没有其他问题，此问题将在下午六点三十前关闭

**Comment by zzx769394358** [comment]
没问题了  , 后续使用指标卡就可以了
