### ISSUE TITLE
[Bug]带有时间过滤组件的仪表板导出为模板，应用模板后时间过滤组件无法切换数据集

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5008]
**DataEase 版本**
v1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
带有时间过滤组件的仪表板导出为模板，应用模板后时间过滤组件无法切换数据集，切换数据集时浏览器控制台会出现异常，且没有数据集可选
![image](https://user-images.githubusercontent.com/89771514/231401348-83cd46a2-f99d-4259-8223-7fe1e75b7313.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问谁.5版本嘛？目前测试环境上没有复现你说的问题；

**Comment by ZhaoQian1222** [comment]
还是存在这个问题。模板套用过来，更换过滤组件的数据集就应该能查询到所有当前系统内的数据集才算合理吧，就跟新建一个仪表板，没有视图的情况下新建时间过滤组件一样，也可以选到所有数据集

**Comment by ZhaoQian1222** [comment]
还是存在这个问题。模板套用过来，更换过滤组件的数据集就应该能查询到所有当前系统内的数据集才算合理吧，就跟新建一个仪表板，没有视图的情况下新建时间过滤组件一样，也可以选到所有数据集
