### ISSUE TITLE
[Bug]SQL Server数据源的SQL数据集，使用with as语法，定时同步异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5009]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
SQL 如下：
with temp1 as (
 select convert(varchar(7), create_time, 111) 开卷月,
     count(case_id) 委案量
 from businessMng_pci
 group by convert(varchar(7), create_time, 111)),
  temp2 as (
 select convert(varchar(7), divisional_date, 111) 新申请递交月,
     count(case_id) 递交量
 from businessMng_pci
 group by convert(varchar(7), divisional_date, 111))
select convert(datetime, temp1.开卷月+'/1', 111) 统计月,
    temp1.委案量,
    temp2.递交量,
    temp2.递交量*1.0/temp1.委案量 出案率
from temp1
left join temp2
on temp1.开卷月 = temp2.新申请递交月

下面是kettle容器的异常日志
![image](https://user-images.githubusercontent.com/89771514/231402026-6b2a9969-87a0-4588-be78-cc2482b87df0.png)
这个异常实际上是因为同步的时候后台自动去拼SQL，做嵌套查询，会在原有SQL基础上做嵌套，这样嵌套出来的 SQL 可能语法上是有问题的

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下
