### ISSUE TITLE
[Bug]【仪表板】日期组件筛选报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5010]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
日期组件筛选 Oracle 数据库报错

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/24768910/231407119-f46a5685-8448-49ec-bead-5828fa663ba3.png)

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已处理，请更新最新版本。
