### ISSUE TITLE
[Bug]仪表板视图样式设置，设置svg格式的背景图，上传失败，报异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5013]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
svg格式的背景图，上传失败，报异常
![image](https://user-images.githubusercontent.com/89771514/231427013-8b979856-cbab-4311-b5f9-4e9ee1b32e2d.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，我们会尽快修复；
