### ISSUE TITLE
[Bug] antv的基础折线图，当存在子类别是，指标的数值格式设置失效

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5015]
**DataEase 版本**
v1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
antv的基础折线图，当存在子类别是，指标的数值格式设置失效

**Bug 重现步骤(有截图更好)**
1.数据集
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/45852479/231454147-0ac3560b-14e5-4fcb-a75a-5eb917eb9075.png">
2.设定数值格式
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/45852479/231453845-805d912e-4b93-4024-80c3-7daf106db612.png">
3.有子类别时
<img width="855" alt="image" src="https://user-images.githubusercontent.com/45852479/231453946-2ad2fc25-d669-4200-b1c0-1a8321e95eb7.png">
4.无子类别时
<img width="843" alt="image" src="https://user-images.githubusercontent.com/45852479/231454104-248588e3-30cf-4836-9770-37e1335cdd4c.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快处理；

**Comment by xuwei-fit2cloud** [comment]
v1.18.6版本已处理，请更新最新版本。
