### ISSUE TITLE
[Bug]建议代码中表名和数据库中大小写一致

### ISSUE THREAD

**Issue by dragonzoebai** [dataease/dataease#5016]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
离线安装方式

**浏览器版本**
谷歌

**Bug 描述**
改为外置数据库mariadb时候报错

**Bug 重现步骤(有截图更好)**
1.
![bf82f2e486c951cd34a30760aacce51](https://user-images.githubusercontent.com/5774016/231637788-b34ad0fb-3cb2-47fc-b767-af1797bcfd86.png)

2.
![7aa8e0247976e101b7feade0f7cdafe](https://user-images.githubusercontent.com/5774016/231637805-c0977c8c-3676-406a-bfac-0e0403e7a13a.png)

3.

**Comment by dragonzoebai** [comment]
![345df52eb95eeb5996ea6fb5e363ee0](https://user-images.githubusercontent.com/5774016/231639574-24de31a4-eaed-422c-ad03-0b776eb3fc24.png)
当我自己改造视图后可以在外置数据库mariadb中正常运行

**Comment by tjlygdx** [comment]
![image](https://user-images.githubusercontent.com/12710377/231655756-af68772d-d444-40d1-9aed-65a741e52a7d.png)
请参考这个文档：https://dataease.io/docs/dev_manual/dev_manual/
