### ISSUE TITLE
[Bug]Excel数据导入后显示错误

### ISSUE THREAD

**Issue by 17600120049** [dataease/dataease#5018]
**DataEase 版本**
v1.18.5
**Bug 描述**
excel导入数据预览数据都是对的，导入之后数据都显示错的 

**Bug 重现步骤(有截图更好)**
1.
导入数据预览
![1a72ea92f12493ab779f1ae93da1469](https://user-images.githubusercontent.com/102302189/231650619-d390de33-40a9-4f1e-ab11-665190aea815.png)

2.
导入后查看
![baafbc591fe1f494b75f99fe19efda0](https://user-images.githubusercontent.com/102302189/231650642-18b34db1-57c1-4cda-914f-f51bc4d8911c.png)
![650b1c66f48b2b168eb6cae64de90e4](https://user-images.githubusercontent.com/102302189/231650708-4199d530-8c76-430a-a0ec-a3dadb23e8fc.png)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，请问上传后是否修改了数据类型呢？我看截图显示上传的字段是时间类型的，也是因为是时间类型所以导入后的数据显示错误，可以手动修改字段类型后再保存应该就没有问题了；

**Comment by BBchicken-9527** [comment]
你好不知道是否解决了你的问题，若没有其他问题将会在今天下午六点三十分前关闭；

**Comment by 17600120049** [comment]
csv是没问题的，excel有问题，这个bug修了吗已经?

**Comment by BBchicken-9527** [comment]
嗯... 之前没有发现你说的这个问题所以不知道问题在哪儿，并没有进入处理的流程，excel你导入的时候更换格式还会出问题是吗？

**Comment by 17600120049** [comment]
新版没有了

**Comment by 17600120049** [comment]
额，刚试了还是有问题.

**Comment by BBchicken-9527** [comment]
嗯.... 我模拟和你类似的excel数据并没有发现你说的情况... 还是和之前的问题是一样的显示的数据是不对的？你看看那导入时候的数据类型是什么？如果是时间调整成文本或者数值试试呢

**Comment by 17600120049** [comment]
我刚试了清除格式后再上传不会有问题

**Comment by BBchicken-9527** [comment]
好的，请问还有什么其他的问题吗？如果没有其他的问题我将于今天下午六点三十分之前关闭；
