### ISSUE TITLE
[Bug]oracle 19C不支持

### ISSUE THREAD

**Issue by jstbw** [dataease/dataease#5026]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
docker

**浏览器版本**

**Bug 描述**
连接19c oracle 无法进行sql查询

**Bug 重现步骤(有截图更好)**
![d51c0fd7f94d7990dc3207617652cbd](https://user-images.githubusercontent.com/66759501/231698752-7e05a6fe-71ca-4dcb-9ee6-4d912516b4d8.jpg)
![image](https://user-images.githubusercontent.com/66759501/231699072-d76c4a6d-48f7-41ed-ad8e-8dc452275500.png)

**Comment by BBchicken-9527** [comment]
你好，不知道是否有帮到你呢，若没有其他问题反馈我将在今天六点半前关闭此问题；
