### ISSUE TITLE
[Feature]请问可以增加文本下拉组件之间的联动配置吗？

### ISSUE THREAD

**Issue by baijingui** [dataease/dataease#5033]
**请描述您的需求或者改进建议.**
请问可以增加文本下拉组件之间的联动配置吗？
比如第一个配置地市的名字、第二个配置区县的名字

**Comment by xuwei-fit2cloud** [comment]
可以尝试使用下拉树组件。

**Comment by baijingui** [comment]
感谢回复。
但是有些联动关系涉及多层的，放在一个下拉树组件里，内容会比较乱。
而且可能有些情况，联动内容之间是交叉的、没有清楚的层级关系的。
还是需要在下拉组件之间的联动配置，比较清晰方便。

**Comment by baijingui** [comment]
> 可以尝试使用下拉树组件。

您好，感谢回复！
但是有些联动关系涉及多层的，放在一个下拉树组件里，内容会比较乱。
而且有些情况，联动内容之间是交叉的、没有清楚的层级关系的。
还是需要在下拉组件之间的联动配置，比较清晰方便。

**Comment by xuwei-fit2cloud** [comment]
这个目前在1.x版本中应该不会去调整了，不过后期的2.x版本里，我们在设计之初会把这个需求考虑进去。
