### ISSUE TITLE
[Question]地图组件咨询

### ISSUE THREAD

**Issue by xiaobai158269** [dataease/dataease#5037]
**DataEase 版本**
1.18.5
**请描述您的问题.**
1.17.0使用地图组件标签内容格式可以展示，升级到1.18.5就不展示了。跟了下源码
src\views\chart\chart\util.js 3201行formatter删除了，导致标签内容格式不展示。我尝试手动放开后出现了以下问题
![企业微信截图_16814570867348](https://user-images.githubusercontent.com/27656311/231979597-69269824-fd30-4c21-b8fe-5a2a9d46ba49.png)
![企业微信截图_16814571174243](https://user-images.githubusercontent.com/27656311/231979673-b26e0538-fd2a-498b-af39-53e0223439f4.png)
我跟踪源码到了
src\views\chart\chart\map\map.js 100行 发现params.seriesName,params.value不存在。
想问下地图组件标签内容格式 功能删除了吗？还是这边有BUG？

**Comment by BBchicken-9527** [comment]
感谢反馈，此处功能因为在版本就去除了，目前新版本是没有格式内容的，应该是在做坐标功能的时候去除的；
