### ISSUE TITLE
[Feature]公共链接优化

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5039]
**请描述您的需求或者改进建议.**
公共链接可以自定义链接地址，方便用户进行公共链接管理。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，公共链接是由系统自动生成的唯一url，是临时生成的用于分享给系统外用户查阅仪表板的入口。公共链接最主要的目的是用于快捷分享，因此暂不考虑支持自定义。
