### ISSUE TITLE
[Bug]impala数据源 日期字段 无法在透视表内使用排序

### ISSUE THREAD

**Issue by qiulinjie0327** [dataease/dataease#5046]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
edge

**Bug 描述**
impala数据源 日期字段 无法在透视表内使用排序

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/52249559/232186850-31e47004-09cf-4070-a657-5762098c0a82.png)

2.
![image](https://user-images.githubusercontent.com/52249559/232186902-1d47ed4f-1668-40ec-bb78-14769b289653.png)

**Comment by qiulinjie0327** [comment]
使用过滤组件过滤数据也有问题
![image](https://user-images.githubusercontent.com/52249559/232196754-3e51996f-f229-4baa-a643-3b52ec0739cd.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们确认一下

**Comment by qiulinjie0327** [comment]
ANTV基础折线图，日期筛选开始时间，视图内少一天
![image](https://user-images.githubusercontent.com/52249559/232430547-537f257d-7023-4459-97a8-2ee13ab94c4f.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前你说的两个问题：第一个无法排序问题，目前测试没有发现你说的情况，你的截图其实也不是很清晰，因为列维度排序是需要列维度多个字段看得出来的，但我看你的截图就一个字段，所以没有效果 ；第二个问题确实存在我们会尽快修复；

**Comment by qiulinjie0327** [comment]
> 感谢反馈，目前你说的两个问题：第一个无法排序问题，目前测试没有发现你说的情况，你的截图其实也不是很清晰，因为列维度排序是需要列维度多个字段看得出来的，但我看你的截图就一个字段，所以没有效果 ；第二个问题确实存在我们会尽快修复；

bug1截图是排序后，bug2截图是排序前，排序前是多天数据，排序后显示的数据就缺失了
