### ISSUE TITLE
[Bug]impala数据源 日期过滤查询不到开始日期的数据

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5050]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
chrome

**Bug 描述**
impala数据源 日期过滤查询不到开始日期的数据
![图片](https://user-images.githubusercontent.com/48307752/232468888-79ab225e-6e75-4c6b-b45b-5bed00421b46.png)

![图片](https://user-images.githubusercontent.com/48307752/232468762-3c452d59-2b63-4371-97da-1eaf18efe4f2.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by mfanoffice** [comment]
该问题一直存在，目前收集到的环境信息如下：
原始数据的 date 字段为 string 类型：
![图片](https://github.com/dataease/dataease/assets/48307752/fc7f3ae3-c0f1-4d10-afef-bc99d314cccf)
![图片](https://github.com/dataease/dataease/assets/48307752/c24ef9bb-fd89-4146-ab0f-efb0ceeba089)

Impala 数据集 SQL 中，对 date 字段做了转换：

![图片](https://github.com/dataease/dataease/assets/48307752/ee7681f2-bc29-4487-9ca0-48eff365417b)


转换后 “日期” 字段在数据集预览中如下显示：

`  2019-03-04 00:00:00.000000000`

最后，在仪表板中的 日期范围 过滤组件中，对该数据集的数据过滤，没有起始时间的数据。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下
