### ISSUE TITLE
[Bug]下钻到市区，然后联动，返回后联动导致数据丢失，同时定时刷新会重置联动

### ISSUE THREAD

**Issue by MilesLeeeeee** [dataease/dataease#5051]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
线上版本

**浏览器版本**
chrome 105

**Bug 描述**
地图下探到市区后，选择某个市区联动，再返回全国，再点击某个省进行联动，绑定联动的元素会丢失数据

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/129132865/232664280-a09ad1a5-e0db-4939-9da0-94c38540a77b.png)
2.
![image](https://user-images.githubusercontent.com/129132865/232664459-426e1c61-ec29-4a93-a53f-a2b3d100ae01.png)

### 第一个bug：

1. ![image](https://user-images.githubusercontent.com/129132865/232665281-8c383199-86f4-4a2d-a86c-b418aec98c96.png)
2. ![image](https://user-images.githubusercontent.com/129132865/232666106-76e3ab12-176f-4f92-8fd1-4c40c24d9092.png)

### 第二个bug，在达到定时刷新页面时，联动的数据会被重置(推测是下钻的时候没有更新地区，导致定时刷新时还是用的全国的数据)

1. ![image](https://user-images.githubusercontent.com/129132865/232665585-6c51dc21-5c64-4297-a1f0-5d95e5d68939.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，确实存在这些问题，我们尽快修复。
