### ISSUE TITLE
[Question]安装出错

### ISSUE THREAD

**Issue by jklist** [dataease/dataease#5052]
Metadata Cache Created
+ sh -c 'yum install -y -q docker-ce docker-ce-cli containerd.io docker-scan-plugin docker-compose-plugin docker-ce-rootless-extras docker-buildx-plugin'
No Presto metadata available for docker-ce-stable
https://mirrors.aliyun.com/docker-ce/linux/centos/7/x86_64/stable/Packages/docker-ce-23.0.4-1.el7.x86_64.rpm: [Errno -1] Package does not match intended download. Suggestion: run yum --enablerepo=docker-ce-stable clean metadata
Trying other mirror.

Error downloading packages:
  3:docker-ce-23.0.4-1.el7.x86_64: [Errno 256] No more mirrors to try.

[DATAEASE Log]: ... 启动 docker 
Failed to execute operation: No such file or directory
Redirecting to /bin/systemctl start docker.service
Failed to start docker.service: Unit not found.
install.sh: line 217: docker: command not found
[DATAEASE Log]: docker 安装失败 

![image](https://user-images.githubusercontent.com/115347699/232699126-c6cc93d1-a4ec-4c3e-8101-ac3dd61e6b5c.png)
重装几次系统 都是这个问题 ？请问如何解决？

**Comment by xuwei-fit2cloud** [comment]
在线安装docker失败的话，可能是安装源的问题，比如网络环境无法访问脚本中的源。
建议使用离线安装包安装，离线安装包中包含了docker和docker-compose的安装程序。
