### ISSUE TITLE
[Feature]整张仪表板导出整体的excel

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5053]
**请描述您的需求或者改进建议.**
整张仪表板导出整体的excel

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
您好，我们觉得这个需求对产品体验的提升，以及产品功能的增强来说，并不是特别明显，我们会将该需求先归入需求池，等有更多的用户反馈时，我们再给与支持。
