### ISSUE TITLE
[Bug]组合图中设置固定轴值，当实际指标值大于设置的最大值时，图表消失，应该是顶天才对

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5055]
**DataEase 版本**
1.18.5

**Bug 描述**
组合图中设置固定轴值，当实际指标值大于设置的最大值时，图表消失，应该是顶天才对

**Bug 重现步骤(有截图更好)**
1.轴值自动时
![image](https://user-images.githubusercontent.com/101089844/232713306-6bd2b0bd-1e67-43d9-aa56-b0d0d5d9ff4b.png)

2.设置最大轴值后
![企业微信截图_7390d30f-205b-4c8f-be2d-ec600b6d154a](https://user-images.githubusercontent.com/101089844/232713162-c69b9281-4d12-4646-97d4-2128539cdf26.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们再想想这块怎么处理。
