### ISSUE TITLE
[Feature] 数据源建议支持时序数据库

### ISSUE THREAD

**Issue by jck9** [dataease/dataease#5057]
**请描述您的需求或者改进建议.**

数据源支持时序数据库？
例如：influxDB / 涛思数据库TDengine

**Comment by xuwei-fit2cloud** [comment]
influxDB的话，有版本区别，目前有用户贡献了1.x版本的插件，但还没有合并到产品中，您这边的版本是？

**Comment by jck9** [comment]
版本：InfluxDB 2.1.1

**Comment by jck9** [comment]
> influxDB的话，有版本区别，目前有用户贡献了1.x版本的插件，但还没有合并到产品中，您这边的版本是？

当前版本：InfluxDB 2.1.1

**Comment by xuwei-fit2cloud** [comment]
短期内还没有相关的支持计划，暂时关闭。
