### ISSUE TITLE
impala数据源，折线图结果展示条件设置后导致视图显示异常[Bug]

### ISSUE THREAD

**Issue by qiulinjie0327** [dataease/dataease#5058]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
edge

**Bug 描述**

折线图结果展示条件设定导致视图显示异常

**Bug 重现步骤(有截图更好)**
原始数据
![image](https://user-images.githubusercontent.com/52249559/232754467-1e458771-21a9-4aa7-b4e3-01a5e328f36c.png)
修改为日期后数据
![image](https://user-images.githubusercontent.com/52249559/232754602-e797a8c3-b812-4bed-bbf5-74c1b85bca3e.png)
字段管理内设置
![image](https://user-images.githubusercontent.com/52249559/232754704-4f0e7174-30b2-4226-bc3a-d47f4b9dabae.png)

使用原始文本做维度，结果展示条数设定为6，类别轴显示数量为4，子类别显示结果为6个，
![image](https://user-images.githubusercontent.com/52249559/232760262-e50d6790-43f0-4937-bedb-1b01eaa3e88e.png)
类别轴无法进行排序，排序后只显示一天数据
![image](https://user-images.githubusercontent.com/52249559/232761095-6b13594d-cc88-4a12-8c64-e5a242b12f44.png)

使用时间格式字段效果同上
![image](https://user-images.githubusercontent.com/52249559/232761423-d699daea-0681-4a1c-8ef8-d0c7327761fc.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by qiulinjie0327** [comment]
已确认，因为日期维度包含多个数据，结果展示为随机单个数值导致
