### ISSUE TITLE
[Bug]明细表下钻后，列字段发生变化

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#5061]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 112.0.5615.87（正式版本） （64 位）

**Bug 描述**
明细表下钻后，列字段左右位置发生变化

**Bug 重现步骤(有截图更好)**
![1](https://user-images.githubusercontent.com/43403764/232786231-5f601707-d320-4949-839f-eefd078a0509.png)
![2](https://user-images.githubusercontent.com/43403764/232786284-fe07d7ed-2688-4198-bca5-9c3f4d10540f.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，不过目前没有较好的优化方式，所以目前先搁置了；
