### ISSUE TITLE
【数据集】API 数据集支持直连模式

### ISSUE THREAD

**Issue by qiulinjie0327** [dataease/dataease#5062]
**请描述您的需求或者改进建议.**
减少服务资源占用，针对经常变化得数据现查现用，有部分业务场景有数据存放要求，不允许数据另存库

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，API数据集中的数据需要同步至数据库的原因：数据集被用于制作图表时，聚合函数、快速计算等均需要通过数据库函数进行运算，因此API数据集目前无法支持直连模式。
