### ISSUE TITLE
[Bug] 明细表文本类的排序错乱

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#5063]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 112.0.5615.87（正式版本） （64 位）

**Bug 描述**
明细表文本类的排序规则是按照首字母进行排序么？截图中按照省份进行排序，房价排序设置为无，测试发现顺序是错乱的

**Bug 重现步骤(有截图更好)**
1.
![微信截图_20230418222311](https://user-images.githubusercontent.com/43403764/232810541-de14bbf2-cb72-4c26-a2a0-42e3047ed69f.png)

**Comment by xuwei-fit2cloud** [comment]
此处排序使用的是数据库默认的字符集排序，并非中文拼音排序，所以排序顺序与中文拼音排序不一样。
中文排序的选项，我们会在后续版本中加入支持。
