### ISSUE TITLE
[Feature] AntV 柱状图颜色设置渐变时，渐变支持设置柱体颜色从上浅到下深

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#5065]
**请描述您的需求或者改进建议.**
目前渐变颜色仅为下浅上深，支持设置柱体颜色从上浅到下深，颜色渲染效果反过来，最好是能够进行配置如何渲染，例如颜色从上至下依次变深、颜色从上至下依次变浅等
<img width="407" alt="image" src="https://user-images.githubusercontent.com/70566485/232950317-676719cb-58c7-4f0c-be92-6fc360ac1fe6.png">

**Comment by xuwei-fit2cloud** [comment]
目前DataEase是按照近轴端浅色的原则处理的，因为DataEase的柱体在轴线处开始，结束于远轴端，若远轴端颜色较浅的话，不太容易识别出来柱体的结束。
