### ISSUE TITLE
[Feature]API数据集动态传参，在查询的时候绑定过滤组件，和外部传参

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5066]
**请描述您的需求或者改进建议.**
API数据集动态传参，在查询的时候绑定过滤组件，和外部传参

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，APi动态传参，是希望将参数拼接在sql的内部查询，用于提升数据集的查询效率吗？这里与sql数据集处理方式还不太一样，我们需要先讨论一下。
