### ISSUE TITLE
[Bug]excel导入后有下面有空行

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5067]
**DataEase 版本**
1.18.6

**Bug 描述**
excel导入后有下面有空行

**Bug 重现步骤(有截图更好)**
1.yi que ren已确认源数据表不存在空行
2.
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/101089844/233030999-e0af9504-1324-4148-a84c-7b6b08b4c3c7.png">

3.

**Comment by xuwei-fit2cloud** [comment]
这个应该是Excel文件中存在空行导致的，删除空行，或者把数值行复制到一个新的Excel文件里试试，应该就正常了。
不过其实不用修改也可以的，此处是数据预览，真正在数据导入的时候，这部分空行会被处理掉。
