### ISSUE TITLE
[Feature]表格单列汇总

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5068]
**请描述您的需求或者改进建议.**
表格总计可以分单独的列进行计算，不是整表汇总，就是想实现这个效果，然后只算数量和总价的汇总，单价的汇总不算是吧，然后规格也不能用汇总
![wecom-temp-17280-1d5a1687fee82e3d4b1a897aea4640f8](https://user-images.githubusercontent.com/101089844/233032293-64b0f186-a7e2-4e62-9aa5-39e40da0b1d4.jpg)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，当前使用的是S2表格，S2还不支持控制到单列，待S2实现后，我们会追加上该功能的。
