### ISSUE TITLE
[Feature]视图详情图标建议可以拖动位置，容易被挡住

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#5070]
![wecom-temp-53889-e9748b26203696f7e88377aa998a4c96](https://user-images.githubusercontent.com/57552153/233239762-c50986c3-de7c-4ba6-9ca2-e2310ae36f9a.png)
![wecom-temp-200599-80c35e58d64cd2b832f060872cedc32e](https://user-images.githubusercontent.com/57552153/233239788-feb68fc0-7161-499b-931a-55715823c1f2.png)
详情图标放在右上有时会被这个按钮挡住

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录并优化一下设计。
