### ISSUE TITLE
[Bug] 其他组件-选项卡组件在头部位置居中时, 无法滚动到第一个tab

### ISSUE THREAD

**Issue by wywppkd** [dataease/dataease#5071]
**DataEase 版本**
v1.18.5 当前 [在线体验](https://dataease.fit2cloud.com/#/panel/index) 可复现

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
如题

**Bug 重现步骤(有截图更好)**
1. 将选项卡组件的头部位置设置为居中
<img width="787" alt="image" src="https://user-images.githubusercontent.com/20620574/233253617-67e88acd-4a56-4c42-b28d-e9f4904bff2a.png">
2. 缩小组件宽度后, 无法显示第一个 tab1
<img width="532" alt="image" src="https://user-images.githubusercontent.com/20620574/233269081-095189a7-04ce-48f9-a01b-2f929c072b9b.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快部署上线；
