### ISSUE TITLE
[Feature]excel导出按钮做成控件，按需添加

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5073]
**请描述您的需求或者改进建议.**
只要excel导出数据量稍大一点，服务直接就挂了。准的很，搞一次挂一次，excel导出按钮，建议不要放到详情弹窗里面，这样还要二次查询，消耗资源，把导出做成控件，需要的自已添加。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
您好，我们最终讨论的结果如下：

1. 我们先尝试解决一下数据量较大的情况下，数据导出导致服务无法使用的问题
2. 导出按钮我们考虑放在视图中，减少操作路径

至于添加导出控件的方案，我们认为增加了使用的复杂度，暂时不考虑。
