### ISSUE TITLE
[Bug] 升级报错，修改 /usr/bin/dectl 中的 en_US 为 zh_CN 后可以执行

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5076]
**DataEase 版本**
V1.18.5、V1.18.6 都有此问题

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
最新 Edge

**Bug 描述**
升级时执行 dectl upgrade 会报如下错误：
![141681986376_ pic](https://user-images.githubusercontent.com/30886198/233343447-8093c44e-ca6f-44db-a0bd-a994fb96f5f3.jpg)

系统版本：CentOS Linux release 8.3.2011
uname 信息：Linux localhost.localdomain 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Mon Jan 18 17:05:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

修改如下内容后可以解决，但升级完成后会被覆盖，下次升级还会报错，需要再次修改：
<img width="728" alt="WeChatdcae5dbdf3fa64dcfd119f99a99f68ec" src="https://user-images.githubusercontent.com/30886198/233343554-9647f06d-44e3-41ea-90f4-da75e9623f47.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
