### ISSUE TITLE
[Feature]辅助线的数值加数值格式配置

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5077]
**请描述您的需求或者改进建议.**
提个优化建议，辅助线的数值加个数值格式配置，否则像平均值这种不能整除时就会显示的很长

<img width="969" alt="wecom-temp-220071-f01f942051158320fb59c230c4834576" src="https://user-images.githubusercontent.com/101089844/233344925-fe02709c-32d9-4f74-908a-a42423b54aa6.png">
<img width="359" alt="wecom-temp-55260-14e6b2343391955cd3182869c3233736" src="https://user-images.githubusercontent.com/101089844/233344928-eae6a2d3-47c9-4096-a650-ea52c5bda3e8.png">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，这个辅助线的数值格式是跟随纵轴，可以通过设置纵轴的数值格式来控制保留位数。
