### ISSUE TITLE
[Bug]数据源没了，但是数据库里有

### ISSUE THREAD

**Issue by OlderBabyML** [dataease/dataease#5078]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Google 112.0.5615.122
**Bug 描述**
今早发现配置的数据源全部消失了，看操作日志没删除记录，配置的图表也能正常查到数据，数据集也消失了几个，但我看数据库里的datasource表数据是有的，debug datasource/list接口发现接口没返回数据，是因为缓存吗？可以我把ehcache那个目录都清掉了重启还是不管用
![image](https://user-images.githubusercontent.com/50657209/233528964-d8901fa0-355f-4bf8-9087-b999f4934c7f.png)
![image](https://user-images.githubusercontent.com/50657209/233529034-563e36ed-499b-48d9-a755-4f659ab17d44.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，你用的账号是自建账号还是admin？如果是自建账号的话受累看看admin是否可以正常的看到数据

**Comment by OlderBabyML** [comment]
> 谢谢回复，你用的账号是自建账号还是admin？如果是自建账号的话受累看admin是否可以正常的看数据

![image](https://user-images.githubusercontent.com/50657209/233917146-3a64fe9c-222c-42ec-8f6a-6600282fe97f.png)
找到原因是因为查数据源的SQL会用到这个存储过程，这个存储过程返回空，所以就没有查到数据源，link类型在sys_auth这个表里没有，这个表里只有panel、menu、dataset三种类型的数据，我先把所以数据源做为link类型添加到sys_auth和sys_auth_detail里面就有了

**Comment by BBchicken-9527** [comment]
没有问题就好，不知道是否还有其他问题呢？如果没有问题我将关闭此问题；

**Comment by OlderBabyML** [comment]
> 找到问题就好，不知道是否还有其他问题呢？如果没有问题我将关闭此问题；

没了，谢谢，关了吧
