### ISSUE TITLE
[Bug] 保存SQL数据集超时

### ISSUE THREAD

**Issue by zijin-zj** [dataease/dataease#5079]
**DataEase 版本**

v1.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
112.0.5615.49（正式版本） (arm64)

**Bug 描述**
如果是一个查询数据量比较大的SQL 本身执行时间就比较长 保存SQL数据集（或保存增量定时任务）的时候会超时 我排查你们源码 保存的时候你们会预执行SQL http请求超过1分钟就超时了 

**Bug 重现步骤(有截图更好)**
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/48403386/233532174-69f255be-2f2b-4530-97db-cc2377d0e75d.png">

**Comment by zijin-zj** [comment]
期望保存SQL数据集（或保存增量定时任务）的时候不要去预览查SQL

**Comment by BBchicken-9527** [comment]
感谢反馈，你的需求我已经汇总到需求池中，我们内部讨论一下。

**Comment by zijin-zj** [comment]
调整MySQL这个超时无效，因为是前端页面请求dataease的http超时了

**Comment by zijin-zj** [comment]
或者你们给一个调整前端http超时的配置

**Comment by yayanpei-fit2cloud** [comment]
前端http超时的配置如下：
![image](https://user-images.githubusercontent.com/84168063/233816781-3a819b4b-db7a-46f4-83a6-ae8eaebe0282.png)

**Comment by zijin-zj** [comment]
这里我改成了300秒，但是还是1分钟就超时了，请求504

**Comment by tjlygdx** [comment]
运行方式(安装包运行 or 源码运行 ?)
安装包
问一下有使用nginx做代理吗？

**Comment by zijin-zj** [comment]
没有 直接docke-compose运行
