### ISSUE TITLE
[Bug]Ubuntu下一键安装脚本执行报错

### ISSUE THREAD

**Issue by moma-tech** [dataease/dataease#5080]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
void

**Bug 描述**
针对给出的安装脚本和命令
`curl -sSL https://dataease.oss-cn-hangzhou.aliyuncs.com/quick_start.sh | sh`
建议修改为bash执行，同时脚本增加shebang
`curl -sSL https://dataease.oss-cn-hangzhou.aliyuncs.com/quick_start.sh | bash`
ubuntu环境下，sh命令的解释器实际为dash，执行该脚本会报错

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/7851881/233533488-8dbc2151-a268-4e9f-8427-a36643c06bd7.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下；

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
