### ISSUE TITLE
[Bug]添加一个文本下拉组件，在设置默认值的时候下拉列表被覆盖在弹窗口下面了

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#5081]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
添加一个文本下拉组件，在设置默认值的时候下拉列表被覆盖在弹窗口下面了

**Bug 重现步骤(有截图更好)**
1.
<img width="800" alt="wecom-temp-127575-60519751e397f3306ad7a9b07983810e" src="https://user-images.githubusercontent.com/57552153/233535950-76353e5d-aa44-4217-a7bb-f753818a2748.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，不知道你那边是否可以稳定复现呢？如果出现清除一下缓存能不能解决呢？
