### ISSUE TITLE
[Feature] 自定义仪表板、数据集等文件夹的排序

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5082]
**请描述您的需求或者改进建议.**
希望能够支持自定义仪表板、数据集等文件夹的排序。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，由于仪表板、数据集的文件夹会涉及到较频繁的调整，比如增加新目录，目录的重命名，目录的删除等，自定义排序后，如果文件夹目录有调整，顺序就会打乱，就可能需要再进行自定义排序。自定义排序还是较适合内容不变的情况，根据自定义达到预期的排序结果。

为了更好的体验，文件夹的排序后面我们会考虑根据名称、修改时间等进行排序的。

**Comment by ziliang-wan** [comment]
目前其实就是根据名称来进行排序的，但是在文件夹比较多的情况下，想把一些重点的文件夹放在上方就只能在文件夹的最前面加上编号，这种情况下如果涉及到中间需要插入新的文件夹，就需要修改比较多的文件夹名称，略为麻烦。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的关注和支持，我们暂时不考虑进行目录的自定义排序。
