### ISSUE TITLE
[Feature]数据集字段类型选择为数值时，对常见的逗号等分隔符进行兼容处理

### ISSUE THREAD

**Issue by moma-tech** [dataease/dataease#5084]
一般API设计的时候，或者excel，一些较大的数字结果，通常是使用字符类型返回，而且为了显示的需要，通常会进行一定的格式化，类似包含逗号等千位分隔符，

当使用这类数据集的时候，选择数据项为数值类型的时候，目前的处理方式是不正确的，似乎是基于逗号进行分隔转换了。

这样会导致需要去修改数据集，excel容易修改，但是api的话，就需要现有系统提供新的独立接口，涉及一整套的需求、开发、测试、部署。

建议先对字符类型进行一定的标准化，再转换为数值类型，类似去货币符号，去逗号一类的，或者增加校验，提示无法转化。

**例如2,000.00会变为2**
![image](https://user-images.githubusercontent.com/7851881/233563850-0913f3f0-979b-4e46-90f2-f686555080ab.png)
![image](https://user-images.githubusercontent.com/7851881/233563740-094a9c05-943c-4bda-b612-5cc3cc44c562.png)
![image](https://user-images.githubusercontent.com/7851881/233563889-7018e40e-4a79-4286-b35c-56c9393a54d4.png)
![image](https://user-images.githubusercontent.com/7851881/233563942-2b05f75b-af52-418b-a3f6-b5124a2b3d37.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们考虑一下优化方案。
目前版本的话，您可以通过新建一个计算字段来处理，例如salary字段为文本类型的数值，以逗号分割，可以新建一个计算字段，公式为replace([salary], ",", "")。
