### ISSUE TITLE
[Bug]全屏模式下备注不显示

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#5086]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
全屏模式下备注不显示

**Bug 重现步骤(有截图更好)**
1.
<img width="682" alt="image" src="https://user-images.githubusercontent.com/57552153/233825693-3358281d-aaad-4e7c-b598-9f439df3074d.png">

2.全屏模式下鼠标放上去没反应
<img width="926" alt="image" src="https://user-images.githubusercontent.com/57552153/233825719-2c6a2582-9b0b-49cc-a83b-bd1c3afd289c.png">

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
