### ISSUE TITLE
[Feature]瀑布图图例不支持隐藏

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#5087]
**请描述您的需求或者改进建议.**
瀑布图的图例目前不支持控制显示和隐藏，建议支持
![wecom-temp-11235-a1d484a065467adc1078f5def939d498](https://user-images.githubusercontent.com/57552153/233825884-a08a9c6c-dd1a-4cd2-b9af-e5863c2f8871.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个目前确实还不能支持，包括图例的位置调整，目前也还不好支持。
