### ISSUE TITLE
[Bug]瀑布图的提示不显示

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#5088]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
瀑布图的提示不显示，鼠标放上去是空的

**Bug 重现步骤(有截图更好)**
1.
![wecom-temp-13335-4e3cdf4120c5e7d2f75f555a81d9195e](https://user-images.githubusercontent.com/57552153/233825975-fe926856-db5a-4b77-bb4b-2f263d11d5a6.png)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，受累看一下样式-提示中的颜色设置是不是调整成了白色或接近白色的颜色；
![图片](https://user-images.githubusercontent.com/84372766/233828479-f7b5ffed-666b-4c3f-a40c-d65aa41eff64.png)
