### ISSUE TITLE
[Feature]antV透视表只用数据行维度也支持算同环比

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5089]
**请描述您的需求或者改进建议.**
在antV透视表组件设置的，只支持数据列，才会有同比/环比；若只用数据行，同比/环比就被屏蔽的，若客户要求数据行显示时间的话，就无法使用，同比/环比功能

![image](https://user-images.githubusercontent.com/101089844/233828189-716c7a99-34d6-42fb-bd90-0009f5f2b9a7.png)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们在后续版本支持一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
