### ISSUE TITLE
[Bug]明细表保存后设置的宽度失效

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#5090]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
明细表调整好宽度后下次进来还是等宽显示

**Bug 重现步骤(有截图更好)**
1.
![wecom-temp-14369-c16f94a838846080db97f38cbd7fa368](https://user-images.githubusercontent.com/57552153/233828945-dc76ceec-c485-4c5f-bbc3-bb4895620eed.png)
这个是默认的
2.
![wecom-temp-24375-892e746ac5d0a9f091c333aaf6b28b35](https://user-images.githubusercontent.com/57552153/233828958-f7a38ed5-dfea-4e28-bb00-3760994cb06c.png)
这个是调整好，想要的宽度
3.
保存后，再次进来还是默认的

**Comment by BBchicken-9527** [comment]
感谢反馈，你说的调整好的宽度是手动拖拽竖线调整的还是调整的样式中的配置呢？

**Comment by xuwei-fit2cloud** [comment]
手动调整的宽度，目前还不支持记录，短期内咱们也还没有支持的计划，暂时先关闭。
