### ISSUE TITLE
[Feature]文本过滤组件输入框中的提示“请选择文本（单选）”改成自定义内容

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5091]
**请描述您的需求或者改进建议.**
文本过滤组件输入框中的提示“请选择文本（单选）”改成自定义内容

![image](https://user-images.githubusercontent.com/101089844/233833677-efa9b747-330d-43db-83f3-3dd9a32f52b0.png)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，如果组件设置了默认值，那么文本过滤组件的提示会被默认值顶掉，如果需要提示过滤组件的内容，建议将组件的标题显示出来。
