### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by cuilong1009** [dataease/dataease#5092]
**DataEase 版本**
 1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
谷歌最新

**Bug 描述**
1.数据集今早（之前也出现过）出现 postgresql查询 报错，同时导致仪表盘视图报错，
数据集预览报错--仪表盘也报错了
2.前一天没事，今天早上新增了一个数据集 ，引发了其他数据集也报错
如图：
3.之前的经验 需要重启 然后稳定一段时间会好

**Bug 重现步骤(有截图更好)**
1.
![15E239F5-23A3-4277-9F52-3F5E7BF5D265](https://user-images.githubusercontent.com/47907572/233893697-13422dcd-3c87-4c05-a991-e7c4b31054c0.png)

2.
![2AE8F04E-9F3F-45E4-832E-1D3A67A81710_edit_9299127860558](https://user-images.githubusercontent.com/47907572/233895327-d000a612-5193-4173-ab77-bcd385e54131.png)

3.

**Comment by tjlygdx** [comment]
数据集预览报错，这个数据集的详细信息能提供一下吗？ 扩阔原始表，以及数据。

**Comment by cuilong1009** [comment]
我这边不只这一份数据，其他的视图数据集也会时不时报这个错，你们随便造一下数据就行，刚才远程你们同事范伟民，他知道情况



| |
13552845423
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月24日 15:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [dataease/dataease] [Bug] (Issue #5092) |

数据集预览报错，这个数据集的详细信息能提供一下吗？ 扩阔原始表，以及数据。

**Comment by BBchicken-9527** [comment]
感谢你的支持，建议你使用安装包安装，源码部署设计因素比较多我们无法准确帮助排查
