### ISSUE TITLE
[Bug] token 过期的逻辑

### ISSUE THREAD

**Issue by jackieriver** [dataease/dataease#5093]
这里判断token有没有过期 , 为什么判断的是缓存中没有对应key的时候是不过期,
说明这里不是很理解, 另外一点没有看到登录续期的逻辑呢
![企业微信截图_16822397986395](https://user-images.githubusercontent.com/24654534/233908755-5f158d1d-d391-4eac-aa0b-83b85e6e055f.png)

if (TokenCacheUtils.invalid(authorization)) { throw new AuthenticationException(expireMessage); }

    public static boolean invalid(String token) {
        if (useRedis()) {
            RedisTemplate redisTemplate = (RedisTemplate) CommonBeanFactory.getBean("redisTemplate");
            return redisTemplate.hasKey(KEY + token);
        }
        Object sys_token_store = CacheUtils.get(KEY, token);
        return ObjectUtils.isNotEmpty(sys_token_store) && StringUtils.isNotBlank(sys_token_store.toString());
    }

**Comment by BBchicken-9527** [comment]
感谢反馈，这里是黑名单的逻辑，而过期是走的jwt验证的，至于token的续命逻辑在1.18.2就去除了，去除原因主要考虑到性能开销以及平台需要续命逻辑的地方几乎没有，并且如果在黑名单以及单点登录中加上续命会导致逻辑十分复杂等等多种因素的考量；
