### ISSUE TITLE
[Feature] 对于数值格式可否抽取出一个公共的属性？

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5094]
**请描述您的需求或者改进建议.**
一个仪表板中的数值格式一般都是一致的，在表格类的图表比较多且指标比较多的情况下一个个的去设置数值格式比较麻烦，可否针对数值格式抽取出公共的属性，允许一个仪表板设置一个默认的数值格式。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先内部讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们先记录一下，近期暂时还没有计划支持。
