### ISSUE TITLE
数字组建不能支持动态参数选择

### ISSUE THREAD

**Issue by wanghaifengnihaoa** [dataease/dataease#5095]
![image](https://user-images.githubusercontent.com/19945385/233931015-99e93a5d-d08f-40de-8d66-4c286d741314.png)

**Comment by wanghaifengnihaoa** [comment]
目前发现只有文本下拉框才能使用动态参数

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在之后的小版本中优化一下。
