### ISSUE TITLE
[Feature]【权限管控】仪表板导出权限优化

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5096]
**请描述您的需求或者改进建议.**
我想对导出做分别权限控制
1、页面的导出PDF、图片；
2、页面的导出模板、应用；
3、页面模块的导出图片、excel；

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，当前1.x版本中，目前没有计划将权限控制做的更复杂了。
我们先在2.x版本中思考一下，是否需要增加这些细粒度的权限控制。
