### ISSUE TITLE
[Feature]建议优化仪表板“已下架”的图标

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#5097]
**请描述您的需求或者改进建议.**
如图所示，仪表板“已下架”的图标更像是“已加入购物车”，建议调整一个更贴文字的图标。
<img width="321" alt="image" src="https://user-images.githubusercontent.com/48945409/233946658-9bb43c73-9c80-4982-a686-22cc5d95d1cd.png">

**Comment by xuwei-fit2cloud** [comment]
感谢建议，我们优化一下。
