### ISSUE TITLE
[Bug]用户通过分享的仪表板跳转提示没有权限

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5099]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
chrome

**Bug 描述**
test1,test2 都分享给了 用户A，用户A 打开test1 ，跳转test2 时 报错，没有权限。
![图片](https://user-images.githubusercontent.com/48307752/234164079-5cba67ae-9e65-497d-a81d-a010d0bb9ce6.png)

![图片](https://user-images.githubusercontent.com/48307752/234164035-d10beff6-03b7-4d76-b4e3-8a16c2d8e0ec.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前设计如此，分享给出的权限为临时权限，而跳转后走的是仪表板的查看权限。是无法找到你的临时权限的，不过你提出的缺失会有这种场景，我们会重新考虑此处的处理逻辑的，但由于产品进度近期内不会考虑此处的调整，目前可以在授权管理中给出查看权限临时解决你的这个问题，我们将会在后续的大版本中优化此处的逻辑处理，感谢你的建议与反馈。
