### ISSUE TITLE
[Bug]Excel数据集使用数据集计算字段保留两位小数部分数值小数异常

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#5100]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌浏览器版本 112.0.5615.137（正式版本） (x86_64)

**Bug 描述**
Excel数据集使用数据集计算字段保留两位小数部分数值小数异常，出现很多位小数，如图：

![image](https://user-images.githubusercontent.com/70566485/234192103-a2b1fb30-7182-4689-948c-1e189f176a26.png)
![image](https://user-images.githubusercontent.com/70566485/234192313-c8c279f2-a099-44d9-b683-039a224d042c.png)
![image](https://user-images.githubusercontent.com/70566485/234192691-be7032db-d056-4091-8302-35b36ad46072.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，导致原因是因为前端js小数精度问题导致，目前我们也在想办法解决这个问题，但短期内应该不会有什么变化；
