### ISSUE TITLE
配置Clickhouse数据源时，只有密码，没有用户名，校验是失败。

### ISSUE THREAD

**Issue by lnts2015** [dataease/dataease#5102]
**请描述您的问题.**

dataease 版本： 1.18.6
问题：配置Clickhouse数据源时，只有密码，没有用户名，校验是失败。（我们的Clickhouse 只有密码，没有用户名）
![image](https://user-images.githubusercontent.com/6037915/234222794-09f8beec-4677-4b0e-ba72-333da45f0436.png)

感谢

**Comment by tjlygdx** [comment]
Clickhouse 只有密码，没有用户名；这种情况我们还不清楚，有相关的官方文档可以参考一下吗？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，这边没有输入用户名，只输入密码可以登陆，我们查了一下资料，应该是使用了默认的账户default进行登陆，建议您新建数据源时，将这个默认账户输入进去，再输入密码试一下。
<img width="868" alt="image" src="https://user-images.githubusercontent.com/84168063/234754233-d42042aa-68d4-4e44-be49-4083198c47b3.png">

**Comment by lnts2015** [comment]
> 感谢您的反馈，这边没有输入用户名，只输入密码可以登陆，我们查了一下资料，应该是使用了默认的账户default进行登陆，建议您新建数据源时，将这个默认账户输入进去，再输入密码试一下。 <img alt="image" width="868" src="https://user-images.githubusercontent.com/84168063/234754233-d42042aa-68d4-4e44-be49-4083198c47b3.png">

感谢。 按照这个步骤。问题已解决。
