### ISSUE TITLE
[Bug]【数据集】MySQL bigint 数据被识别为文本类型

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5103]
**DataEase 版本**
1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
MySQL bigint 类型数据被识别为文本类型，导致关联条件“1524298868858331138”被识别为“1524298868858331138.0”而不能进行数据关联等下一步操作。
注意：有现成数据和系统进行测试，可私聊~

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
