### ISSUE TITLE
[Bug] 以年月日为日期的维度字段，设置联动、跳转、外部参数过滤后均无数据展示

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5104]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
以年月日为日期的维度字段，设置联动、跳转、外部参数过滤后均无数据展示

**Bug 重现步骤(有截图更好)**
1.原始数据
<img width="283" alt="image" src="https://user-images.githubusercontent.com/45852479/234464403-627f6b11-b5d3-4fe5-9fa4-ee35dacd9f25.png">
<img width="550" alt="image" src="https://user-images.githubusercontent.com/45852479/234464446-e11204ac-4259-4739-a6ba-338d4a1c9f9e.png">
2.联动效果
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/45852479/234464976-6ea1e3a3-0bad-4b4f-b3a5-2b00209d5d2f.png">
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/45852479/234464826-14389302-7a15-4745-9f2b-631ad4870c25.png">
3.跳转效果
<img width="939" alt="image" src="https://user-images.githubusercontent.com/45852479/234465008-5884b0e1-a898-4804-be22-7197c0e8abb1.png">
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/45852479/234464919-25afa676-bbce-4b3a-bfd8-0b052274c202.png">
4.外部参数效果
<img width="901" alt="image" src="https://user-images.githubusercontent.com/45852479/234465037-e53ec59e-4b1b-45df-b333-37fe8a4eabcd.png">
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/45852479/234464939-37e8dbc0-1c52-4be5-9ae9-b9d5ca2238a6.png">

------------------------
Bug 所在：联动、跳转、外部参数执行SQL如下
<img width="656" alt="image" src="https://user-images.githubusercontent.com/45852479/234465212-e054d7f8-4561-48b4-8787-c2b137c2a010.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
