### ISSUE TITLE
[Bug] 列权限对字段设置脱敏规则后，使用该字段作为维度制作柱状图等，视图显示异常，维度不显示

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5106]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 112.0.5615.137（正式版本） (arm64)

**Bug 描述**
列权限对字段设置脱敏规则后，使用该字段作为维度制作折线图等，视图显示异常，维度不显示

**Bug 重现步骤(有截图更好)**
1. 基于 5105 bug，https://github.com/dataease/dataease/issues/5105
我们使用商品名称作为维度制作柱状图，维度不能正常显示
![image](https://user-images.githubusercontent.com/30063018/234475760-ead87d63-e1e2-4989-9f6f-8f7086b7d01f.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下；
