### ISSUE TITLE
[Bug]从中国地图无法下钻显示重庆市各区

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5107]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
中国地图可以下钻显示指定省内的区信息，但是无法下钻到重庆市，单显示重庆市是可以的，原因是地图选择重庆市下级还有个重庆市

**Bug 重现步骤(有截图更好)**
1.全国地图，点击重庆市下钻，
<img width="1410" alt="图片" src="https://user-images.githubusercontent.com/48307752/234481126-40f90370-415f-4b72-8353-f4ac4e61194f.png">
<img width="1401" alt="图片" src="https://user-images.githubusercontent.com/48307752/234481201-13c763f7-78dd-460d-b1e7-20bf058de74f.png">

2.如果只展示重庆市，可以显示各区信息
<img width="1436" alt="图片" src="https://user-images.githubusercontent.com/48307752/234481390-01d42736-6313-4864-abe8-e73227a4207b.png">

3. 原因是，只展示重庆市，选择的是二级重庆市
<img width="411" alt="图片" src="https://user-images.githubusercontent.com/48307752/234481527-f8cf61aa-6164-415a-af5d-e5030b0c79d9.png">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下；
