### ISSUE TITLE
[Bug]同一个ElasticSearch表，可以创建数据库数据集但是创建SQL数据集报错

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#5108]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
同一个ElasticSearch数据源的一张表，可以创建数据库数据集，但是创建SQL，select 查询却报错。

**Bug 重现步骤(有截图更好)**
1.创建数据库数据集，正常创建。
![image](https://user-images.githubusercontent.com/48945409/234488103-2b003c05-d0e2-4de5-bead-79aa14d757f3.png)
![image](https://user-images.githubusercontent.com/48945409/234488190-118f6376-38e8-45e6-bc5b-7ccafa9107a4.png)

2.使用该表做 select 查询创建 SQL 数据集，报错。
![image](https://user-images.githubusercontent.com/48945409/234488468-33dcaead-36cf-455f-9252-9f8fdfc60771.png)

3.测试 SQL 查询另外一张表是正常的。
![image](https://user-images.githubusercontent.com/48945409/234488837-bc821bab-38b9-40ff-a209-8c615c3e7251.png)

**错误信息：**
java.lang.RuntimeException: HttpClient查询失败: {"error":{"root_cause":[{"type":"parsing_exception","reason":"line 1:39: mismatched input '-' expecting {')', ',', 'ANALYZE', 'ANALYZED', 'AS', 'CATALOGS', 'COLUMNS', 'CURRENT_DATE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'DAY', 'DEBUG', 'EXECUTABLE', 'EXPLAIN', 'FIRST', 'FORMAT', 'FULL', 'FUNCTIONS', 'GRAPHVIZ', 'GROUP', 'HAVING', 'HOUR', 'INNER', 'INTERVAL', 'JOIN', 'LAST', 'LEFT', 'LIMIT', 'MAPPED', 'MINUTE', 'MONTH', 'NATURAL', 'OPTIMIZED', 'ORDER', 'PARSED', 'PHYSICAL', 'PIVOT', 'PLAN', 'RIGHT', 'RLIKE', 'QUERY', 'SCHEMAS', 'SECOND', 'SHOW', 'SYS', 'TABLES', 'TEXT', 'TOP', 'TYPE', 'TYPES', 'VERIFY', 'WHERE', 'YEAR', LIMIT_ESC, IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}"}],"type":"parsing_exception","reason":"line 1:39: mismatched input '-' expecting {')', ',', 'ANALYZE', 'ANALYZED', 'AS', 'CATALOGS', 'COLUMNS', 'CURRENT_DATE', 'CURRENT_TIME', 'CURRENT_TIMESTAMP', 'DAY', 'DEBUG', 'EXECUTABLE', 'EXPLAIN', 'FIRST', 'FORMAT', 'FULL', 'FUNCTIONS', 'GRAPHVIZ', 'GROUP', 'HAVING', 'HOUR', 'INNER', 'INTERVAL', 'JOIN', 'LAST', 'LEFT', 'LIMIT', 'MAPPED', 'MINUTE', 'MONTH', 'NATURAL', 'OPTIMIZED', 'ORDER', 'PARSED', 'PHYSICAL', 'PIVOT', 'PLAN', 'RIGHT', 'RLIKE', 'QUERY', 'SCHEMAS', 'SECOND', 'SHOW', 'SYS', 'TABLES', 'TEXT', 'TOP', 'TYPE', 'TYPES', 'VERIFY', 'WHERE', 'YEAR', LIMIT_ESC, IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}","caused_by":{"type":"input_mismatch_exception","reason":null}},"status":400}

**Comment by BBchicken-9527** [comment]
感谢反馈，因为你的表名中存在中线，你看看使用引号包上是不是可以查询了呢，如："usertable-xxx-xx-x"
