### ISSUE TITLE
[Bug] sql没有别名就没有结果

### ISSUE THREAD

**Issue by zzx769394358** [dataease/dataease#5109]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1. 
![image](https://user-images.githubusercontent.com/57294442/234513434-1fb6b6c9-618d-4bed-8ec9-481bc4a55a87.png)

2. 
![image](https://user-images.githubusercontent.com/57294442/234513587-abe24666-1aea-40ea-af9e-9773a9859bab.png)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前设计如此，主要考虑到sql语句字段书写过长表头显示所以强制在包含函数和计算的这种情况加上别名才显示；
