### ISSUE TITLE
[Feature]建议增加回收站功能

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#511]
**请描述您的需求或者改进建议.**
建议删除的数据集、视图、仪表盘等增加回收站功能，以免误删除导致需要重新编辑一遍，同时建议删除的时候增加确定删除的输入框。

**Comment by xuwei-fit2cloud** [comment]
感谢您的反馈，我们讨论一下这个功能。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
