### ISSUE TITLE
[Question]公共链接访问时ip和端口会转发为后端的ip和端口

### ISSUE THREAD

**Issue by hhzhldhjl** [dataease/dataease#5110]
**请描述您的问题.**
源码模式运行时也需要nginx代理吗？发现不用nginx代理所有模块都没问题但是访问公共链接有问题，公共链接访问时会重定向到8081端口访问link.html页面，直接404

**Comment by xuwei-fit2cloud** [comment]
是的，源码在公共链接的访问这里做了处理，会将短链接解析为长链接，所以才会出现您遇到的情况。

**Comment by hhzhldhjl** [comment]
好吧，谢谢
