### ISSUE TITLE
[Feature]流向地图能标记出指定坐标的地名吗

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5112]
**请描述您的需求或者改进建议.**
目前只有经纬度字段，如果数据有地名字段，是否可以将该字段显示出来。
<img width="1382" alt="图片" src="https://user-images.githubusercontent.com/48307752/234755187-9a9455d6-4bba-4c0f-b426-1be442881361.png">

**Comment by xuwei-fit2cloud** [comment]
技术上是可以的，但目前没有支持，我们先记录一下。
