### ISSUE TITLE
[Bug] Echarts 明细表开启自动换行后滚动步长失效

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5115]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新

**Bug 描述**
1.添加 Echarts 明细表，打开自动滚动开关
2.打开自动换行开关
3.此时表格滚动会一点点向下滚动，没有按照步长滚动

https://user-images.githubusercontent.com/30886198/234820097-dc9335cd-f01b-4d5e-a6fb-249e9523a273.mp4

**Comment by BBchicken-9527** [comment]
感谢反馈，是生效的，你看一下开启自动换行之后高级配置里面的滚动变成了步长（px），这是因为不开启自动换行的时候高度是一样的我们可以按照固定的行高去滚动，但当开启自动换行后表格的高度是不可预的，所以变成了步长并自己设置步长值；

**Comment by liuboF2c** [comment]
> 感谢反馈，是生效的，你看一下开启自动换行之后高级配置里面的滚动变成了步长（px），这是因为不开启自动换行的时候高度是一样的我们可以按照固定的行高去滚动，但当开启自动换行后表格的高度是不可预的，所以变成了步长并自己设置步长值；

个人觉得这样不太符合我的心理预期的，换行开启之前，每次滚动 10 行，开启之后滚动都不到一行，我会直观认为开启后出现了问题。

建议开启换行后，自动将步长设置为原来的 行高*36px，也就是 360px，这样至少能看出滚动的效果，用户也能看明白步长和滚动效果的关系。

如果在滚动设值中将“步长(px)”加粗或提示让用户意识到单位已变换，就更容易理解了 ^_^

**Comment by BBchicken-9527** [comment]
好的，你的优化建议我们已经记录了；
