### ISSUE TITLE
能否增加api数据源动态传参功能

### ISSUE THREAD

**Issue by baijingui** [dataease/dataease#5116]
您好，
在通过api数据源查询数据时，常常需要动态传递参数，比如开始时间、结束时间和id等。
不能动态传参的情况下，需要多一步开发，取数据入数据库，才能通过sql实现数据刷新。
能否在api数据源定义功能中，增加动态传参功能，动态传参需要能够关联过滤组件，实现动态数据查询和仪表板数据的动态刷新功能。
谢谢！

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先内部讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
我们需要进一步的调研以及评估，因此先放进需求池中，近期暂时不考虑规划实现。

**Comment by reillynicholas** [comment]
你好，我想问下目前有没支持这个功能？
