### ISSUE TITLE
[Bug] 使用 admin 账户登录后退出再使用 oidc 账户登录时能够查看到 admin 权限的数据集

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5118]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新

**Bug 描述**
使用 admin 账户登录后退出再使用 oidc 账户登录时能够查看到 admin 权限的数据集

**Bug 重现步骤(有截图更好)**
1. 使用 admin 账户登录系统，打开一个普通用户无权限查看的数据集
2. 退出 admin 用户，使用 oidc 账户登录系统
3. 进入数据集页面，可以查看到所有数据集列表
4. 在数据集页面重新刷新页面后，数据集列表变成了用户自己有权限查看的列表

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
