### ISSUE TITLE
[Bug]消息中心的接收管理始终默认有国际飞书的配置选项不论是否有启用

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#5119]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
消息中心的接收管理始终默认有国际飞书的配置选项不论是否有启用，但是其他平台如果未启用则不会出现。

**Bug 重现步骤(有截图更好)**
1.平台对接页面关闭钉钉。
![image](https://user-images.githubusercontent.com/48945409/235043201-da412481-e6f5-4b7e-beef-a24802055fb3.png)

2.接收管理处则没有钉钉。
![image](https://user-images.githubusercontent.com/48945409/235043257-2f9d06a6-0914-4f51-9714-456f4d7d1397.png)

3.平台对接处开启钉钉后，接收管理这里才会出现钉钉。
![image](https://user-images.githubusercontent.com/48945409/235043336-086ef8bf-805b-4fce-a7fe-e1d802977319.png)

4.国际飞书始终是关闭状态，但是接收管理处始终有国际飞书的配置项。
![image](https://user-images.githubusercontent.com/48945409/235043443-b222b194-1f26-4ebd-a512-c6cd3659f40b.png)
![image](https://user-images.githubusercontent.com/48945409/235043498-5597e06e-b9a2-4928-aadd-17743999aca9.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
