### ISSUE TITLE
[Bug]Excel数据无法导入

### ISSUE THREAD

**Issue by shenlanchenwei** [dataease/dataease#5120]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**
 安装包运行
**浏览器版本**

Microsoft Edge
版本 111.0.1661.41 (正式版本) (x86_64)

**Bug 描述**
导入Excel后表头正常识别,表数据导入不进

**Bug 重现步骤(有截图更好)**
1.上传excel 保存,数据量大概20W左右
报错截图
![image](https://user-images.githubusercontent.com/6754634/235049999-9dd11139-0128-4307-a651-9307a3e5480b.png)
2.然后通过追加的方式再次导入还是报错
![image](https://user-images.githubusercontent.com/6754634/235050131-038f6da6-edde-4a46-8a2c-ef5a6120909d.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你导入的数据符合我们要求的规范吗？
