### ISSUE TITLE
[Bug]指定docker网段不生效

### ISSUE THREAD

**Issue by DNSTESTWEB** [dataease/dataease#5121]
**DataEase 版本**
1.86

**运行方式(安装包运行 or 源码运行 ?)**
离线安装

**浏览器版本**

**Bug 描述**
通过自动化脚本安装，install.conf 文件中的DE_DOCKER_SUBNET 定义的值，不生效，启动的时候创建网桥网卡会读取本地的网卡地址，导致服务启动后地址冲突，其他机器无法访问这台机器，目前解决办法是在docker-compose文件中指定特定的IP地址段，目前是成功的，不知道是不是bug，系统版本是BigCloud Enterprise Linux For Euler 21.10 LTS

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by DNSTESTWEB** [comment]
isntall.conf 文件修改端口不生效 ，因为80端口被nginx占用 更换其他端口不生效

**Comment by xuwei-fit2cloud** [comment]
DataEase启动时，真正生效的变量是在.env 文件里。你可以看看DataEase的运行目录下（默认为 /opt/dataease/)是否有一个.env的隐藏文件，在这个文件中有网段的信息，可以通过执行命令 cat /opt/dataease/.env  | grep DE_DOCKER_SUBNET 获取。
在DataEase启动时，会先source /opt/dataease/.env 文件，会将 DE_DOCKER_SUBNET 变量值替换到 docker-compose.yml 文件里，这个过程和你手动去指定docker-compose中的ip段其实是一样的，所以应该是没有问题的。

**Comment by DNSTESTWEB** [comment]
> dataEase启动启动，真正生效变量是在是在文件文件看看看看可以看看可以看看可以可以看看可以可以/opt/dataease/）是否是否是否目录是否是否信息，可以通过执行命令 cat /opt/dataease/.env | grep DE_DOCKER_SUBNET 获取。 在DataEase启动时，会先source /opt/dataease/.env文件，会把DE_DOCKER_SUBNET变量值替换到docker-compose.yml文件里，这个过程和你手动去指定docker-compose中的ip段其实是一样的，所以应该是没有问题的。

是否有文件的优先级高，目前我查看现有的.env还是之前部署的网段信息，目前所有的我是改了docker-compose.yml 的config的值，好像值没有被覆盖
![image](https://user-images.githubusercontent.com/36812022/235083828-6b05c93e-966f-4012-a43d-7dd4e212261b.png)
![image](https://user-images.githubusercontent.com/36812022/235083969-a914febc-854f-43b6-bd71-d496761e4b01.png)

**Comment by xuwei-fit2cloud** [comment]
可以先把DataEase 服务停了，执行 service dataease stop命令停服务，然后修改 .env 文件里的这些值，再启动DataEase服务，执行命令 service dataease start 启动服务。
