### ISSUE TITLE
[Question] 项目启动耗时很短, 做了哪些针对的优化

### ISSUE THREAD

**Issue by jackieriver** [dataease/dataease#5122]
**请描述您的问题.**
在使用过程中发现, 
项目启动时间基本在10秒钟以内, 大部分在几秒钟就完成了启动并可用, 
但对于一个springboot的项目, 即使是空项目, 启动时间也没有这么短的
想请问做了哪些针对的优化?
谢谢啦

**Comment by JunTech** [comment]
你确定启动时间很短？我咋感觉加载插件和扫描公共包里面mapper文件啥的还有一开始启动的时候监听quarztjob的任务就不止10s 了

**Comment by jackieriver** [comment]
2023-05-05 16:02:48,530  INFO                  io.dataease.Application:  61 - Started Application in 18.576 seconds (JVM running for 20.779)

也挺快了,

**Comment by jackieriver** [comment]
我接触过很多springboot项目, 慢的都到90多秒了 甚至更多
