### ISSUE TITLE
希望能支持颜色采取

### ISSUE THREAD

**Issue by renziyou** [dataease/dataease#5123]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/8150303/235092877-8b936cdd-0992-4813-9a29-5edb0858a010.png)

希望能支持吸管 颜色采集功能

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们会在2.0进行颜色组件的重构，已规划了取色器功能。
