### ISSUE TITLE
[Bug]符号地图鼠标移上有提示，移走提示不消失

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5124]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
符号地图鼠标移上有提示，移走提示不消失，如下图，shou'b鼠标移走后提示信息没有消失
<img width="700" alt="图片" src="https://user-images.githubusercontent.com/48307752/235096932-c2603b3b-a316-448b-a60d-476e850cbd9b.png">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by BBchicken-9527** [comment]
确认已修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
