### ISSUE TITLE
[Bug]选项卡有两页都是符号地图时，第二页不能正常显示

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5125]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
两个符号地图，都放入选项卡，选项卡第一页可以正常显示，第二页选项卡如下图，不能正常显示。
<img width="753" alt="图片" src="https://user-images.githubusercontent.com/48307752/235098387-e409fc1d-8526-4b59-9d54-4b8f8bf47158.png">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，确实有这个问题，我们修复一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
