### ISSUE TITLE
[Feature] 关联数据集 数据集选择时css样式优化

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5127]
**请描述您的需求或者改进建议.**
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/45852479/235116817-1bd41bb3-2d91-4b89-acea-3b109401b9b7.png">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们把宽度适当调大一些，如果表名让然较长，显示不全，将鼠标悬浮至表名上方稍作停留，即可提示完整的表名信息。
