### ISSUE TITLE
表结构问题

### ISSUE THREAD

**Issue by hhzhldhjl** [dataease/dataease#5128]
目前看各种授权都是在sys_auth表，sys_roles_menus好像没用到，这个表有什么用吗？还有sys_auth_detail表是干啥用的？有没有表结构说明文档

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，这部分授权的表是属于xpack功能用到的，这部分功能的代码不在开源的代码中，您这边忽略就好了。我么2.x会将xpack功能的表与非xpack功能隔离开。

**Comment by hhzhldhjl** [comment]
好的，我们现在因为在做框架选型，看咱这个产品还不错，还没有确定要不要购买咱这个产品，但是我们有一个需求是嵌入我们系统单点登入dataease并且可以控制权限，单点登录好说，但是权限控制文档里没有这部分介绍，这个有解决办法吗？如果普通用户也有数据源管理之类的权限怕有安全风险

**Comment by yayanpei-fit2cloud** [comment]
感谢您的关注和认可，权限控制和单点登录在xpack中都是支持的，我们在2.x中也有计划支持嵌入，关于xpack功能的介绍或者文档，您可以加入咱们的社区交流群，我们有专业的支持人员会给您解答的
![image](https://user-images.githubusercontent.com/84168063/236100323-c7b3dba1-e160-42f1-9ccb-c401884976d7.png)
