### ISSUE TITLE
仪表版的数据集显示异常，数据行错位[Bug]

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#5130]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
数据集中显示如下：
![bug1 2](https://user-images.githubusercontent.com/85436572/236121839-99e416b6-baf3-4818-af2a-f8333bf2cf6e.png)
仪表板中显示如下：
![Uploading bug1.1.png…]()
Data Hub 这一行错位至Earth Explorer这一行，数据源是MySQL数据，用户端展示有该效果，本地没有复现出来，可能是偶发现象。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你说的本地是本地模式吗？

**Comment by Renata1027** [comment]
是指我在自己的环境里没有复现用户的问题（我的数据源，DE版本，浏览器和用户都是相同的）

**Comment by BBchicken-9527** [comment]
嗯嗯，看起来大概率是缓存问题，受累让他清除一下缓存看看是否还有此问题，若还有此问题可以将问题再次打开
