### ISSUE TITLE
Echarts 的气泡地图调整地图在视图组件中的大小占比[Feature]

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#5132]
**请描述您的需求或者改进建议.**
原本的地图在视图组件中占比太小，默认预览时只占很小一块。
![wecom-temp-1196957-a3ab419c58d2303969d04b7b799c86f2](https://user-images.githubusercontent.com/85436572/236142486-c820cf57-50b5-489f-9016-1407641a873b.png)
通过拉大组件大小可以调整地图大小，如下图：
![wecom-temp-1376423-1638792230fa0e5c3413791b3bb85c8c](https://user-images.githubusercontent.com/85436572/236142665-6960156a-a33a-44fd-866a-a53e08690bbe.png)
当地图做了下钻设置后，返回上一级的按钮会被其他组件遮挡，而且该按钮不能自定义颜色、大小和位置，难以寻找
![wecom-temp-243892-fc074b50f669dfc0133093a373ca01bc](https://user-images.githubusercontent.com/85436572/236143093-4109686e-11b0-48e1-975b-7379d543b49b.png)

![wecom-temp-1497355-930b393d393050858417d29a7d124c6b](https://user-images.githubusercontent.com/85436572/236143134-44c72976-a70a-47b7-afd4-51e5e4906a22.png)

希望能调整地图在视图组件中的占比，或自定义返回上层的按钮颜色、大小和位置

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录并讨论一下。
