### ISSUE TITLE
[Bug]Excel包含Emoji字符会导致导入失败

### ISSUE THREAD

**Issue by shenlanchenwei** [dataease/dataease#5135]
**DataEase 版本**
最新版本

**运行方式(安装包运行 or 源码运行 ?)**

安装包运行
**浏览器版本**

Chrome最新版本
**Bug 描述**

Excel中内容中含Emoji字符会导致导入失败
比如下面这句
"有超赞的👍一直幸福😁"

**Bug 重现步骤(有截图更好)**
1.导入一个含有Emoji字符的Excel
![image](https://user-images.githubusercontent.com/6754634/236167948-7a553177-8218-41f2-98bd-5f2dd9d5b43c.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，已知问题，因为考虑到常规数据没有存在emoji的可能，所以目前暂时没有处理此处的排期，你是有这方面的需求吗？

**Comment by shenlanchenwei** [comment]
是的,我们导入了客户的评论数据,他里面含有这个字符

**Comment by BBchicken-9527** [comment]
好的，我这边记录一下，我们内部讨论一下看看是否有方法处理，但短时间内确实无法实现；

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
