### ISSUE TITLE
[Feature]开发一个便捷迁移功能，比如在Web界面点击迁移

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#5136]
很多软件已经可以实现前段迁移了，希望前端页面可以有备份操作，然后可以在另外一台服务器前端直接恢复。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈！
这个在技术上是可以实现的，但备份操作涉及到的备份数据点及备份方案会比较多，我们还需要好好考虑一下相关的设计问题，可能会在2.x版本中去支持。
