### ISSUE TITLE
[Bug] 选项卡轮播三个仪表板时仪表板中的表格样式异常

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5137]
**DataEase 版本**
V1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新

**Bug 描述**
仪表板中包含一个选项卡组件，有三个选项卡，分别放了三个仪表板的公共链接。
仪表板中包含 Echarts 表格，轮播时间为 30 秒
在页面轮播过程中，会出现表格全部挤在一起的异常显示
![image](https://user-images.githubusercontent.com/30886198/236368308-319656b8-c492-42ca-bc10-9378046a8559.png)

控制台报错如图：
![image](https://user-images.githubusercontent.com/30886198/236368153-20322d26-5d4e-402a-a9ca-e3c8d2ff07fd.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
