### ISSUE TITLE
[Feature]【仪表板】全屏预览仪表板优化

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5138]
**请描述您的需求或者改进建议.**
当前仪表板进行条件筛选之后，全屏预览仪表板会重新刷新页面数据！可否全屏预览的时候继承之前的筛选条件呢？

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议很不错，我们先记入需求并规划进行优化。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，经过重新评估，暂时没有计划支持该优化。

**Comment by AndroidBaby1** [comment]
好的，辛苦
