### ISSUE TITLE
[Bug]组合图图例显示，方向选择【垂直】，水平位置选择【中】时，图例和横轴之间会出现遮挡

### ISSUE THREAD

**Issue by zhimayuyuan** [dataease/dataease#5139]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**
Chrome 版本 110.0.5481.78（正式版本） （64 位）

**Bug 描述**
组合图图例显示，方向选择【垂直】，水平位置选择【中】时，图例和横轴之间会出现遮挡

**Bug 重现步骤(有截图更好)**
![组合图](https://user-images.githubusercontent.com/128681370/236372883-bea37bdb-d10f-4f5d-a308-e457fa4ced41.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知，我们优化一下
