### ISSUE TITLE
[Bug] 超时错误：timeout of 100000ms exceeded

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#514]
**DataEase 版本**
v1.1.0 rc2

**浏览器版本**
chrome:92.0.4515.107

**Bug 描述**
在使用过程中，时不时就提出超时错误，应该是因为后台连接超时等待的原因，建议延长

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/46042812/128135882-5fa993ed-2585-41d2-886c-31c99f8746be.png)

**Comment by xuwei-fit2cloud** [comment]
由于数据量较大，或者网络原因可能会导致超时，目前默认超时时间是10秒，后续会将该参数修改为可编辑。
感谢您的反馈。

**Comment by xuwei-fit2cloud** [comment]
v1.4版本支持超时时间设置。
