### ISSUE TITLE
[Bug]仪表板点击加载的时候有的仪表板在等待视图数据加载完之前会一直存在一个遮罩层

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5141]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 112.0.5615.137（正式版本） (x86_64)

**Bug 描述**
不知道跟数据量大小有没有必然关系，其中一个数据量比较大的仪表板会出现这种情况，另一个相对小的就不会存在这种遮罩层
![image](https://user-images.githubusercontent.com/89771514/236427891-0f9680c6-9d9b-4082-8c43-ff03d1e5c062.png)

正常的异步加载应该是这样的，不会存在对整个页面进行遮挡的遮罩层
![image](https://user-images.githubusercontent.com/89771514/236427628-d52173bf-b67b-4b4f-bb3d-529192c1b87a.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下
