### ISSUE TITLE
[Bug] 添加数据向左选择的错误

### ISSUE THREAD

**Issue by weiensong** [dataease/dataease#5142]
**DataEase 版本**
dataease:v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**

docker 安装运行
**浏览器版本**

112.0.5615.138 (正式版本) （64 位） (cohort: Stable) 
**Bug 描述**
添加数据源的时候API方式，基础信息粘贴向左选择会自动退出数据表页面

**Bug 重现步骤(有截图更好)**
添加数据源的时候API方式，基础信息粘贴向左选择会自动退出数据表页面
![bugtest](https://user-images.githubusercontent.com/61647484/236486791-f71f19de-236f-4672-b10d-f485fc84324b.gif)

**Comment by weiensong** [comment]
浏览器是chrome

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
