### ISSUE TITLE
[Feature]仪表盘多个视图同时在处于下钻的状态时，提供一个一键清除下钻效果，返回父级视图的按钮

### ISSUE THREAD

**Issue by blooze123** [dataease/dataease#5143]
**请描述您的需求或者改进建议.**
希望DE能够提供像“一键清除联动”那样有一个“一键清除下钻效果”的按钮，为同一个仪表盘内多个处于下钻状态的视图，提供一键返回父级视图的操作。这个需求的场景主要是人员在使用DE进行多视图比较的时候，经常需要同时将所有视图下钻到下一级，再进行进一步比较，但是比较完后，要返回父级再次验证时，总是需要一个个视图重新点击返回，才能回到父级视图，用户体验差，因此建议多加一个一键清楚下钻效果的按钮支持。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，需求我们先放进需求池中，近期暂不考虑规划实现，待收集到更多用户的类似需求后再做进一步规划。
