### ISSUE TITLE
[Bug]仪表板导出PDF时图片异常，展示不全

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#5151]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 最新版

**Bug 描述**
仪表板导出 PDF 时，图片变成只有一角，不全。

**Bug 重现步骤(有截图更好)**
访问飞致云公司大屏，点击右上角导出 PDF，预览如下所示，部分图片异常了。
补充：经咨询，有问题的图片使用的 svg 格式的，png 图片没问题。
![image](https://user-images.githubusercontent.com/48945409/236617314-c6d6c567-1b08-41e3-b3b2-916c4fb5c161.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，建议目前先将图片转为png使用，后续大版本将会处理此处问题。
