### ISSUE TITLE
[Feature]建议优化导出 PDF 时，选择默认模版的描述文字

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#5152]
**请描述您的需求或者改进建议.**
建议调整下此处的描述，“加参数样式”给人一种可以添加筛选参数或者 CSS 样式等内容，看是否调整为“加仪表板描述”这种类似的？
![image](https://user-images.githubusercontent.com/48945409/236617486-af6fb0a8-8b25-4ce5-aacc-b8e27d8d2cbf.png)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下这里的提示文案。

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
