### ISSUE TITLE
[Bug]表格组件排序按钮双击时会出现排序混乱的情况

### ISSUE THREAD

**Issue by yehevah** [dataease/dataease#5155]
**DataEase 版本**
v1.17.0

**运行方式(安装包运行 or 源码运行 ?)**
docker镜像

**浏览器版本**
版本 112.0.5615.138（正式版本） （64 位）

**Bug 描述**
![image](https://user-images.githubusercontent.com/15710778/236730701-45806fdb-5341-409a-af1e-aec8a79ed42a.png)

表格视图，详情，表头排序，连点两次顺序排序箭头，或者连点两次倒序排序箭头，排序就乱了

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
您好，表格组件的排序按钮，点一下生效，点两下是还原状态，即不生效，您可以尝试在上面已乱序的情况下，点击一下试试，看看是否生效。
我们在我们的测试环境中验证过是正常的，如果还存在上述问题，还麻烦您给我们回复，谢谢。
