### ISSUE TITLE
[Feature]通过Api接口返回值渲染图片

### ISSUE THREAD

**Issue by A-LayDown** [dataease/dataease#5156]
当前使用版本为v1.18.6；
目前仅支持本地上传图片，希望可以通过调用Api接口返回的参数显示图片：
接口返回参数类似于：[https://192.168.0.1:8080/tupian.png]

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前的图片组件设计得并没有太复杂，仅支持本地图片文件上传显示。
如果需要url的方式展示图片的话，可以选择网页组件，或者富文本组件。
