### ISSUE TITLE
文件上传时只能一个一个上传，太慢太麻烦，希望可以支持多个同时选择上传

### ISSUE THREAD

**Issue by xiang-svg** [dataease/dataease#5157]
![image](https://user-images.githubusercontent.com/73943674/236751975-bbde4eec-aec2-4880-b174-763cd7c054ba.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
已纳入开发计划。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，v1.18.x版本中暂不支持。
