### ISSUE TITLE
[Bug] csv文件上传一直乱码，我用了多个不同的csv文件都是乱码

### ISSUE THREAD

**Issue by xiang-svg** [dataease/dataease#5158]
**DataEase 版本**
**运行方式(安装包运行 or 源码运行 ?)**
在线demo测试

**浏览器版本**
Google Chrome

**Bug 描述**
 csv文件上传一直乱码

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/73943674/236752857-8682aa38-0047-4142-aa8e-f6b266795cc0.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的这个问题，推测可能和数据相关，方便给我们一条你存在问题的数据吗？将有问题的数据拼接成一条就可以我们只是定位一下到底是哪里出了问题导致的你乱码的
