### ISSUE TITLE
[Bug]时间过滤组件——>日期范围组件：左边为开区间（不包含）是否合理？

### ISSUE THREAD

**Issue by Arno-y** [dataease/dataease#5159]
时间过滤组件——>日期范围组件：左边为开区间（不包含）是否合理？
![image](https://user-images.githubusercontent.com/49140157/236752690-fbe26387-dfcd-487a-bad7-d5e44387b3b6.png)
![image](https://user-images.githubusercontent.com/49140157/236752353-e5ce2253-ee78-4085-830d-8d1245ca2f2c.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你的版本是？之前的小版本是存在此类问题的但目前已经修复，你可以下载最新版本体验，感谢你的反馈与支持期待下次的反馈😄；

**Comment by BBchicken-9527** [comment]
目前最新的是1.18.6，可以下载尝试一下；

**Comment by Arno-y** [comment]
> 目前最新版本为1.18.6，可以下载尝试一下；

好的

**Comment by BBchicken-9527** [comment]
你好 不知道是否解决了你的问题呢？
