### ISSUE TITLE
[Feature] 离线升级后，配置文件被覆盖

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5160]
**请描述您的需求或者改进建议.**
离线升级后，docker-compose文件配置的参数被覆盖，conf文件下下的配置文件被覆盖

**Comment by xuwei-fit2cloud** [comment]
spring.datasource.url在配置外部MySQL的时候，确实有可能有参数需要特别指定，这个我们在后续版本的脚本中做一下处理。
至于2和3中提到的文件，其实是DataEase自身服务组件所用到的相关配置文件，并不建议直接修改。如果要使用MySQL8的话，建议独立运行，并将MySQL8配置为DataEase的外部数据库。

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
