### ISSUE TITLE
[Bug] SQL 数据集在设置了参数的情况下报错，SetOperationList cannot be cast to PlainSelect

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5161]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome
版本 112.0.5615.137（正式版本） (arm64)

**Bug 描述**
 SQL 数据集在设置了参数的情况下报错，SetOperationList cannot be cast to PlainSelect，数据源为 MySQL 数据源

**Bug 重现步骤(有截图更好)**
1.  SQL 语句文件如下所示：
`select * from (
select * 
from demo_shop_kind 
union all 
select * 
from demo_shop_kind ) tmp
where tmp.name = '${name}'`
2. 报错截图如下所示：
![image](https://user-images.githubusercontent.com/30063018/236986296-b783e700-30ca-47b1-8d84-436964efe8bb.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
