### ISSUE TITLE
[Feature] 版本升级带来的前端缓存可否通过前端JS、CSS构建去处理下

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5163]
**请描述您的需求或者改进建议.**
DataEase 目前在版本升级后因为前端的一些缓存问题，有时候会出现无法登录或页面报错等清空，清空缓存或者隐身模式打开后方法解决。能否在技术层面去解决下这个问题。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先排查一下原因。

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
