### ISSUE TITLE
[Bug] 精简模式下，上传 Excel 文件数值类型识别为时间，且手动修改字段类型为数值后不生效

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5164]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 112.0.5615.137（正式版本） (arm64)

**Bug 描述**
精简模式下，上传 Excel 文件数值类型识别为时间，且手动修改字段类型为数值后不生效

**Bug 重现步骤(有截图更好)**
1. Excel 如下所示：
![image](https://user-images.githubusercontent.com/30063018/236991494-56de49c8-ee00-424c-bf87-6a4175e9fec6.png)
2. 上传 Excel 文件，数值类型识别为时间：
![image](https://user-images.githubusercontent.com/30063018/236991626-df630a21-4289-4675-ad56-30c544a4be6b.png)
3. 手动修改为数值，保存后数据不正确：
![image](https://user-images.githubusercontent.com/30063018/236991721-c4fa293f-ced9-451c-bfe2-7201d82b1616.png)
![image](https://user-images.githubusercontent.com/30063018/236991743-aac7d695-318a-4683-9c68-6c355f75e83d.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
问题已修复，可下载新版本体验；
