### ISSUE TITLE
[Bug]RedShift数据源无法通过校验

### ISSUE THREAD

**Issue by kaneenak** [dataease/dataease#5165]
**DataEase 版本**

v1.18.6
**运行方式(安装包运行 or 源码运行 ?)**
 curl -sSL https://dataease.oss-cn-hangzhou.aliyuncs.com/quick_start.sh | sh
**浏览器版本**
chrome  112.0.5615.139（正式版本） （64 位）

**Bug 描述**
我链接AWS redshift 时，校验的时候报错”数据源无效: Invalid database name“，
并且我获取Schema是成功的。
我相同的信息在beekeeper studio上可以连接。

**Bug 重现步骤(有截图更好)**
1.获取Schema：成功
![image](https://user-images.githubusercontent.com/122849336/237027124-3c1fb8be-0c94-4eaf-bf34-3c4355a89b21.png)
2.校验失败
![image](https://user-images.githubusercontent.com/122849336/237026921-2549d6ef-9643-43a9-bc2a-5af2378ed157.png)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
