### ISSUE TITLE
[Feature]明细表可根据阈值高亮整行数据

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#5166]
**在以表格视图进行数据展示的时候，需要对重点的一些行进行突出展示**
目前我看DataEase只能做到这种程度，根据列指定规则，把文字颜色改变，但突出的仅仅是该字段的内容。
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/45967454/237039854-447e2e4b-5e6e-4323-905f-6b09a40e4772.png">

**Comment by xuwei-fit2cloud** [comment]
很抱歉，目前我们还没有相关的支持计划。
