### ISSUE TITLE
[Feature]表格视图各列列宽需要分别设置

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#5167]
**表格视图各列列宽需要分别设置**
目前DataEase只能做到自适应和简单的自定义列宽：其中自适应会在右侧留白，自定义是所有列同宽度（需要单独指定某列的列宽）。
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/45967454/237041496-7aa6699e-6b0b-4b77-9f25-163a2f880072.png">
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/45967454/237041643-0a0d307a-b249-483b-bfd4-10aeafd02697.png">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，透视表我们现在用的是S2组件，S2当前还不支持自定义每一列的列宽。另外我们考虑到透视表是可以拖维度到表头的，在维度变化的情况下，表头是不固定的，在这种情况下再去设置每一列的列宽，最终的展示效果也和预期不一致。因此在制作透视表时，也不太建议去设置每一列的列宽。
