### ISSUE TITLE
[Feature]统计结果当做条件实现跳转

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#5168]
是否会考虑把后面的统计结果当做条件实现跳转，查看明细，测试目前只能支持纬度的跳转。
![超](https://user-images.githubusercontent.com/43403764/237058140-842f0e24-ba18-4ac1-9ff3-92166aca84be.jpg)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。
