### ISSUE TITLE
[Bug]Elasticsearch 数据源在制作图表时使用排序就报错

### ISSUE THREAD

**Issue by wangwen1220** [dataease/dataease#5169]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chromium 102.0.5005.167

**Bug 描述**
![1683625901234.png](https://img1.imgtp.com/2023/05/09/pCIXObcX.png)
如图：ES 数据源，指标如果不设置排序可以正常显示，如果设置排序就报错。

**Bug 重现步骤(有截图更好)**
1. Elasticsearch
2. 创建 SQL 数据集
3. 指标设置排序

**Comment by BBchicken-9527** [comment]
感谢反馈，请问方便给我们截取一下当时的后台日志吗？目前测试环境是没有出现你说的问题的；
