### ISSUE TITLE
[Feature]建议增加数据集、视图复制的功能

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#517]
**请描述您的需求或者改进建议.**
有的数据集或者视图可能是相同的修改一下就行，有复制就方便一些
![image](https://user-images.githubusercontent.com/35896106/128145068-7b572b34-5898-41dc-9af6-f1ec79b6c396.png)

**Comment by xuwei-fit2cloud** [comment]
数据集的复制我们认为目前没有支持的必要，尤其DataEase对于数据库数据集来说，同一个数据表是不允许重复的。
视图的复制我们还需要讨论一下必要性，目前还没有考虑到特别需要的场景。

**Comment by weishuo6** [comment]
1、关于数据集，比如我写的SQL类型数据集，我可能只要改SQL里面一个字段，如按照天和周去统计，那SQL改一个数字就行，这样有复制就会方便一些；
2、关于视图也是一样，比如按照天和周去统计，视图样式、数据维度和指标都是一样的，如果有复制或者引用功能，可以延伸其他视图的格式，只是数据集换下就行了，对相同类型的视图都重新编辑太麻烦。

个人意见，仅供参考
 
发件人： xuwei-fit2cloud
发送时间： 2021-08-05 10:37
收件人： dataease/dataease
抄送： weishuo6; Author
主题： Re: [dataease/dataease] [Feature]建议增加数据集、视图复制的功能 (#517)
数据集的复制我们认为目前没有支持的必要，尤其DataEase对于数据库数据集来说，同一个数据表是不允许重复的。
视图的复制我们还需要讨论一下必要性，目前还没有考虑到特别需要的场景。
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xuwei-fit2cloud** [comment]
复制暂时先不会支持，视图这块会有较大改动，请等待新版本。
