### ISSUE TITLE
[Bug]仪表板目录删除后，目录下的仪表板对应的默认仪表板没有跟随自动删除，导致查看默认仪表板异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5171]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
仪表板目录删除后，目录下的仪表板对应的默认仪表板没有跟随自动删除，导致查看默认仪表板异常

**Bug 重现步骤(有截图更好)**
1.新建仪表板目录
2.在目录下创建新的仪表板，并将仪表板保存为默认仪表板
3.点击默认仪表板进行查看
4.删除仪表板目录
5.再次查看默认仪表板未被删除
这个不是每次都必现的，我测试了三次才复现出来一次
![image](https://github.com/dataease/dataease/assets/89771514/d4d8aa82-c62e-44c3-b6d4-40de3cb6d2c3)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
