### ISSUE TITLE
[Bug]新建的 Echarts 的地图和气泡地图视图，不添加维度和指标时无法显示标题

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5172]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/89771514/7ff9dc01-7c5c-4dcc-8f7a-bcc235b895b0)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
