### ISSUE TITLE
[Bug]AntV横向柱状图：图表颜色与图例颜色不一致

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#5177]
**DataEase 版本**
1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌：113.0.5672.92（正式版本） (arm64)

**Bug 描述**
![Uploading WechatIMG173.png…]()

图例的颜色和图表对应显示颜色错位，切换成无痕浏览器后未改善。

**Comment by BBchicken-9527** [comment]
感谢反馈，你增加视图的高度看看呢？
