### ISSUE TITLE
[Feature]表格的列宽度可否每一列都支持自定义宽度

### ISSUE THREAD

**Issue by luanlinpeng** [dataease/dataease#5178]
目前表格的自定义宽度设置后每一列的宽度是相同的，需要每一列定义不同的宽度
比如这样：
![image](https://github.com/dataease/dataease/assets/89448362/78967d88-82aa-4d87-bbb0-ea71bbf80736)

**Comment by xuwei-fit2cloud** [comment]
duplicated of #5167
