### ISSUE TITLE
[Question]结果过滤能否实现在大于小于时传入sql表达式，想要实现是否只能通过SQL数据集控制实现

### ISSUE THREAD

**Issue by huxi28** [dataease/dataease#5180]
**请描述您的问题.**
![image](https://github.com/dataease/dataease/assets/130810396/6f134966-2c7a-4a2f-bf13-b4e8382c823a)
结果过滤能否实现在大于小于时传入sql表达式，如果不能，想要实现是否只能通过SQL数据集或者日期查询组件控制实现。
`SELECT *
FROM dy_video_data_view
WHERE `create_time` >= DATE_SUB(NOW(), INTERVAL 2 WEEK)`

**Comment by huxi28** [comment]
所以如果需要升序显示最近30天的数据趋势，只能通过在sql中写死参数来实现是吗？还有其他的实现方式吗

**Comment by fanziwy** [comment]
可以加一个是否是30天内的计算字段，然后再使用该字段过滤
