### ISSUE TITLE
[Bug] SQL Server 数据源 文本下拉过滤中文 无法获得结果

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5181]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
SQL Server 数据源 文本下拉过滤中文 无法获得结果

**Bug 重现步骤(有截图更好)**
1.
<img width="1066" alt="image" src="https://github.com/dataease/dataease/assets/45852479/78e6e653-8830-4db4-8c69-7c2ac6c51f33">
2.
<img width="1073" alt="image" src="https://github.com/dataease/dataease/assets/45852479/1b86704c-e3d6-4a69-8644-eff88330a290">
<img width="1041" alt="image" src="https://github.com/dataease/dataease/assets/45852479/be09149f-29dc-410d-bff1-a70bd64c11be">

**Comment by BBchicken-9527** [comment]
目前已修复，可以下载新版本体验；
