### ISSUE TITLE
[Bug]富文本视图，会出现无法编辑标题名称的情况

### ISSUE THREAD

**Issue by zhimayuyuan** [dataease/dataease#5182]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**
Chrome 版本 110.0.5481.78（正式版本） （64 位）

**Bug 描述**
富文本视图，会出现无法编辑标题名称的情况

**Bug 重现步骤(有截图更好)**
![1](https://github.com/dataease/dataease/assets/128681370/d8741ccc-82a9-4a7e-8f58-b45b44e578fe)
![2](https://github.com/dataease/dataease/assets/128681370/4a287634-3060-4d54-9e21-64ecca597ba0)
![3](https://github.com/dataease/dataease/assets/128681370/321d7833-3fa0-4088-85d5-a6fb747a7c4f)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
