### ISSUE TITLE
[Feature] 表格类视图优化

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5183]
**请描述您的需求或者改进建议.**
1. 各列的列宽支持自定义
2. 表头颜色支持分开设置
3. 汇总表支持指定某列进行汇总
4. 汇总、透视表导出，所见即所得

**Comment by 17600120049** [comment]
建议增加表格数据在线编辑

**Comment by xuwei-fit2cloud** [comment]
> **请描述您的需求或者改进建议.**
> 
>     1. 各列的列宽支持自定义
> 
>     2. 表头颜色支持分开设置
> 
>     3. 汇总表支持指定某列进行汇总
> 
>     4. 汇总、透视表导出，所见即所得

目前的表格图库使用的是AntV S2，有些特性还无法支持。需求我们已记录，在2.x版本中，我们也会调研其他的表格图库。

**Comment by xuwei-fit2cloud** [comment]
> 建议增加表格数据在线编辑

您好，对于数据的在线修改，目前DataEase还没有相关计划。
