### ISSUE TITLE
[Bug] 相同excel，local模式可以上传，simple模式上传失败

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5186]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
相同excel，local模式可以上传，simple模式上传失败

**Bug 重现步骤(有截图更好)**
<img width="737" alt="image" src="https://github.com/dataease/dataease/assets/45852479/8af1dfec-7778-4ed1-be14-84631863a7b9">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
问题已修复，可下载新版本体验；
