### ISSUE TITLE
StarRocks数据源配置的明细表视图设置翻页无效

### ISSUE THREAD

**Issue by pangzhili** [dataease/dataease#5190]
**DataEase 版本**
v1.17

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome 版本 110.0.5481.78（正式版本） （64 位）

**Bug 描述**
数据源是StarRocks
仪表板中配置明细表，分页模式设置为：翻页，但是明细表中不生成分页。
经测试MySQL数据源配置的明细表支持，后续有计划支持StarRocks配置的明细表翻页吗？

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/46517296/931d063e-8677-49ea-82ad-8d4ec06941d8)

**Comment by BBchicken-9527** [comment]
感谢反馈，你是用大于十条的数据看一下呢？

**Comment by pangzhili** [comment]
![image](https://github.com/dataease/dataease/assets/46517296/63161cf8-2244-4114-afde-40326bfd08c7)
 是的，我是用的大于10条的数据来看的

**Comment by pangzhili** [comment]
前端中找到了如下代码块，这是否表明：如下数据集不支持分页查询。

export const NOT_SUPPORT_PAGE_DATASET = ['kylin', 'sqlServer', 'es', 'presto', 'ds_doris', 'StarRocks']

**Comment by BBchicken-9527** [comment]
感谢反馈，因为考虑到这类数据源分页需要先做排序，所以如果分页的成本比较高所以暂时不考虑做此类数据源的分页；

**Comment by pangzhili** [comment]
ok，可以理解，因为我们有这类需求，如果要实现的话，是不是最好在前端做分页比较合适？

**Comment by pangzhili** [comment]
明白了，感谢

**Comment by BBchicken-9527** [comment]
没关系，期待你下次提出的需求与建议😝
