### ISSUE TITLE
[Bug]tab选项卡里放明细表时表格宽度异常

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#5193]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
tab选项卡里放明细表时表格宽度异常

**Bug 重现步骤(有截图更好)**
1.表格先拖到正常宽度
<img width="683" alt="image" src="https://github.com/dataease/dataease/assets/57552153/aeb5967b-6d99-456a-ab4a-7da16aa8e23d">

2.切换到靠右的页签
<img width="681" alt="image" src="https://github.com/dataease/dataease/assets/57552153/5b7184a5-4654-4288-9584-974e1dc040b4">

3.再切回表格的页签，表格宽度缩短
<img width="679" alt="image" src="https://github.com/dataease/dataease/assets/57552153/ff918209-d4e0-412f-9d18-823585c79b4d">

**Comment by BBchicken-9527** [comment]
感谢反馈，因为视图确实在切tab的时候布局有些改变所以会重新加载一下他的样式，可能感觉这个有时间间隔；感知上有个大概十秒左右；后续我们讨论一下是否有优化的方案；
