### ISSUE TITLE
[Feature] 地图自定义颜色的渲染

### ISSUE THREAD

**Issue by hzhfit2cloud** [dataease/dataease#5197]
**请描述您的需求或者改进建议.**
需求场景：客户对地图区域颜色比较敏感，指标超过某个临界值有一定的预警含义，客户需要自定义指标在某个区间内展示某个特定颜色
备注：类似折线图高级设置中的分析预警辅助线

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议很不错，我们先记录并讨论一下实现方式。

**Comment by xuwei-fit2cloud** [comment]
技术上是可以实现，我们加入到开发计划中。
