### ISSUE TITLE
[Feature]地图标签能否扩展显示指标值

### ISSUE THREAD

**Issue by hzhfit2cloud** [dataease/dataease#5198]
**请描述您的需求或者改进建议.**
场景：仪表盘作为展厅大屏时，希望指标值直接在地图上展示
备注：类似提示中的内容格式，可供客户按需选择
<img width="345" alt="image" src="https://github.com/dataease/dataease/assets/89765365/914332a6-4aa1-4dd5-a7bb-e6b00053751b">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们扩展一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，与色彩地图的标记功能有冲突，我们需要先讨论一下。
