### ISSUE TITLE
[Feature]地图地名映射后能否合并区域块

### ISSUE THREAD

**Issue by hzhfit2cloud** [dataease/dataease#5199]
**请描述您的需求或者改进建议.**
场景：目前在地图高级设置中编辑地图映射后区域地名变更了，但是还是两块区域并展示两次名称，影响美观；需要合并在一起且仅展示一个名称
![image](https://github.com/dataease/dataease/assets/89765365/f9b330bc-2b4a-4184-9606-7cede770fa27)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们讨论一下。

**Comment by xuwei-fit2cloud** [comment]
这个在当前版本中，可以通过自定义地图的方式来实现，但需要自己修改地图的json文件，相对来讲比较复杂。
2.x版本中，我们会考虑支持分组功能。
