### ISSUE TITLE
[Bug]看板创建公共链接进行分享，URL地址为localhost且不能编辑。

### ISSUE THREAD

**Issue by zhanggefei** [dataease/dataease#52]
**DataEase 版本**
v1.0.0-rc2

**Bug 描述**
看板创建公共链接进行分享，URL地址为localhost且不能编辑。

**Bug 重现步骤(有截图更好)**
![WechatIMG1589](https://user-images.githubusercontent.com/37612532/123510683-75dd7280-d6af-11eb-8aa2-2ef949ca2f57.png)

**Comment by xuwei-fit2cloud** [comment]
v1.0.1 版本已修复，且已发布
