### ISSUE TITLE
[Bug]数值格式缺“/”

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5200]
**DataEase 版本**
1.18.6

**Bug 描述**
mmdd之间是不是少了个/
<img width="1004" alt="image" src="https://github.com/dataease/dataease/assets/101089844/c36e579c-6c22-4392-8ec3-43a19d99478c">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
