### ISSUE TITLE
[Bug]es数据集字段改字段类型后拖入视图报错

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5201]
**DataEase 版本**
1.18.6

**Bug 描述**
es直连数据集字段改字段类型后拖入视图报错

**Bug 重现步骤(有截图更好)**
1.直连ec sql数据集后，都是文本字段
<img width="773" alt="image" src="https://github.com/dataease/dataease/assets/101089844/701dc0de-f77b-412a-8919-dc5e54ddad9b">

2.更改为其他字段类型后，拖入视图就会报错
<img width="833" alt="image" src="https://github.com/dataease/dataease/assets/101089844/4d27c337-05a5-43ce-b0e1-2441ccc7c036">
<img width="954" alt="image" src="https://github.com/dataease/dataease/assets/101089844/8eadbb5d-845a-4acc-96c2-e238d34fd32a">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下
