### ISSUE TITLE
[Bug]【任务管理】站内消息中心显示异常

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5203]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
详见步骤

**Bug 重现步骤(有截图更好)**
1.站内消息通知有一堆报错消息。
![image](https://github.com/dataease/dataease/assets/24768910/2663a93a-3c78-410d-ba68-d05a2e5ac86e)

2.点击一条跳转到消息界面，这个地方的执行记录里面筛选失败的。
![image](https://github.com/dataease/dataease/assets/24768910/319db9a7-87b6-4d5d-9001-6f20ff137a1b)

3.筛选不到错误信息。
![image](https://github.com/dataease/dataease/assets/24768910/03506922-d3c2-4e57-90b0-a21100624dfa)

4.直接在消息界面筛选是可以筛选到的，跳转之后再筛选不行。
![image](https://github.com/dataease/dataease/assets/24768910/8a531b85-ce95-4474-91c4-396db3ef959d)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，确实存在您说的问题，我们尽快修复。

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
