### ISSUE TITLE
[Feature]echart地图切换指标只能在编辑界面操作

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5204]
**请描述您的需求或者改进建议.**
如下图所示，echart地图，设置了多个指标，可在编辑状态下切换，展示状态下没有此按钮；
希望可以在展示状态下可以切换指标。
![图片](https://github.com/dataease/dataease/assets/48307752/d24b1c56-ce27-4077-ad67-1029e4c32f78)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在预览状态下增加个切换button。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
