### ISSUE TITLE
地图配置了多个指标能否全部显示在地图上

### ISSUE THREAD

**Issue by dwjf123** [dataease/dataease#5205]
![微信截图_20230512191922](https://github.com/dataease/dataease/assets/29540234/986b75a5-708d-433b-a44c-f56b5d5a49fa)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们讨论一下。

**Comment by xuwei-fit2cloud** [comment]
这个改动会有点大，短期内我们还不会支持。
