### ISSUE TITLE
[Question]excel导出

### ISSUE THREAD

**Issue by zzx769394358** [dataease/dataease#5207]
**请描述您的问题.**
excel导出能否将XSSFWorkbook 改成SXSSFWorkbook

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请问改成SXSSFWorkbook，是基于效率考虑，比如降低内存开销，缩减导出时间吗？

**Comment by zzx769394358** [comment]
是的, 大数据的导出时, 服务差不多就完了

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的关注和支持，我们在后面的小版本中优化一下。
