### ISSUE TITLE
[Feature]建议调整查看视图图片时使用仪表板背景图作为其背景的逻辑

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#5209]
**请描述您的需求或者改进建议.**
请看如下示例，当仪表板背景图过于定制化时，查看视图图表使用仪表板背景图便会很奇怪。
![image](https://github.com/dataease/dataease/assets/48945409/08707d41-ee17-45c6-ba25-8c204fbfd26a)
![image](https://github.com/dataease/dataease/assets/48945409/da51e7c4-f700-4c36-81cb-a07363e7eef3)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们优化一下，当组件没有背景时，根据仪表板主题给组件一个默认的背景色。

**Comment by xuwei-fit2cloud** [comment]
暂时没有支持计划。
