### ISSUE TITLE
[Bug]数据集的数据导入到图表中错乱了

### ISSUE THREAD

**Issue by juanmaocxy** [dataease/dataease#5214]
**DataEase 版本**
1.18.5
**运行方式(安装包运行 or 源码运行 ?)**
安装包运行
**浏览器版本**

**Bug 描述**
我需要展示近24小时的数据变化，维度为 HH:ss,数据如下：
14605937 | 14:00
16000587 | 13:00
15655728 | 12:00
13558206 | 11:00
13844309 | 10:01
16716336 | 09:00
17914089 | 08:00
9453733 | 07:00
3759767 | 06:00
1962767 | 05:00
1693036 | 04:00
2027557 | 03:00
2538672 | 02:00
4490252 | 01:00
6426466 | 00:00
9388513 | 23:00
12012923 | 22:00
14930475 | 21:00
17032565 | 20:00
18981714 | 19:00
19568021 | 18:00
18027979 | 17:00
16909218 | 16:00
16984681 | 15:00

导入到图表之后，数据从00:00开始展示，跟数据集的顺序不一样
**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by juanmaocxy** [comment]
> 感谢反馈，请问你是用的是什么数据库呢？主要看你是用的数据库是否是有序的；

我的数据源是mysql，数据集采集之后预览显示也是没问题的，最近的一条数据是14:00,但是放到图标里就是按照从0-24的顺序展示，我将数据集的数据导出给你们官方运维，也有同样的问题

**Comment by BBchicken-9527** [comment]
好的，请稍等我们验证一下

**Comment by BBchicken-9527** [comment]
感谢反馈，测试发现应该是聚合时group自身特性导致，建议使用非聚合的视图查看，数据反馈结果就没有问题了；
