### ISSUE TITLE
[Feature] 配置cas后，默认登陆方式选择cas，此时无法登录admin

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5217]
**请描述您的需求或者改进建议.**
目前对接cas后，只能通过修改默认登陆方式的方法登陆cas用户。建议和ad、oidc保持一致

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先内部讨论优化方式。

**Comment by xuwei-fit2cloud** [comment]
1.x版本要调整的话，改动部分比较大，我们计划在2.0版本对这部分进行重构。

**Comment by yayanpei-fit2cloud** [comment]
已经优化完成，2.x不存在这个情况，issue先进行关闭了。
