### ISSUE TITLE
[Feature]针对多个过滤组件使用查询按钮时建议隐藏组件本身的查询按钮

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#5218]
**请描述您的需求或者改进建议.**
目前针对多个过滤组件使用查询按钮时，过滤组件本身的按钮还在，虽然点击无效，但是对于查询条件比较多的情况下整体效果没那么友好，对使用者也会产生误导
![image](https://github.com/dataease/dataease/assets/35896106/f5ec3048-319f-4ba5-a457-8cf27794aefe)
建议最终效果类似常规的过滤组件，如下图，每个组件旁边是没有查询按钮的，所有过滤内容都输入完成后点击查询按钮就可以
<img width="761" alt="750957e04eab9cb82753d2ce91d3e49" src="https://github.com/dataease/dataease/assets/35896106/cc39e7ee-5515-4e0f-ba45-c01bccd4772d">

**Comment by yayanpei-fit2cloud** [comment]
建议您使用文本下拉组件或者文本列表组件，也是支持模糊搜索的，文本搜索组件不再做相关优化了，感谢您的反馈与支持。
