### ISSUE TITLE
[Bug]Excel数据集导入excel，数据集中的顺序与excel中的数据顺序不一致了

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5219]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
Excel数据集导入excel，数据集中的顺序与excel中的数据顺序不一致了

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/89771514/e7cfbf3c-1a87-4746-901c-fd605ed0ba9d)
![image](https://github.com/dataease/dataease/assets/89771514/0b8a0a0f-de2f-4bb9-b0c3-6a4594c979fe)

**Comment by BBchicken-9527** [comment]
感谢反馈，因为使用的是聚合的视图，所以group时自身特性导致排序，建议使用非聚合的视图查验，这样数据显示将会与数据库一致；

**Comment by Coder-Tang** [comment]
> 感谢反馈，因为使用的是聚合的视图，所以group时自身特性导致排序，建议使用非聚合的视图查验，这样数据显示将会与数据库一致；

非聚合的视图是啥意思，是指excel的sheet页吗？还是...
我试了一下，还是乱序的
