### ISSUE TITLE
[Bug] Oracle 数据集 getTables() 疑问，这个sql非常的慢

### ISSUE THREAD

**Issue by VanLiuZhi** [dataease/dataease#5220]
**v1.18.4**

在配置了Oracle的数据源之后，去查看这个schema下面的 table，非常的慢，我看执行了这么一个sql

代码位置：io/dataease/provider/datasource/JdbcProvider.java    public String getTablesSql(DatasourceRequest datasourceRequest)

Oracle部分：

return "select table_name, owner, comments from all_tab_comments where owner='OWNER' AND table_type = 'TABLE' AND table_name in (select table_name from all_tables where owner='OWNER')".replaceAll("OWNER", oracleConfiguration.getSchema());

基本耗时要1分半左右，我看了这个sql的执行计划，很繁琐，Oracle原理不太清楚，不知道为什么这么一个联合查询要这么慢

我觉得这块代码是不是可以改写成这样：
"select table_name, owner, comments from all_tab_comments where owner='" + oracleConfiguration.getSchema() + "' AND table_type = 'TABLE'";

因为我看查询视图部分的就是这么写的，把 table_type 换一下

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们优化一下。

**Comment by fit2cloudrd** [comment]
v1.18.7版本已优化，请升级最新版本。
