### ISSUE TITLE
[Question]导出功能

### ISSUE THREAD

**Issue by zzx769394358** [dataease/dataease#5222]
**请描述您的问题.**
可能存在多人同时使用导出excel功能, 对服务是个很大的压力, 想问问有啥建议?

**Comment by zzx769394358** [comment]
排查了下, 在 findExcelData()方法里一次性把所有数据都查询并加载到内存当中.  请问是否有改成分页的计划

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的建议和支持，我们2.0有改成分页的计划。
