### ISSUE TITLE
[Bug]ES数据源创建一个SQL数据集，数据集预览正常，在视图中使用报错

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5223]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
![image](https://github.com/dataease/dataease/assets/89771514/604486b9-1977-49b6-a24d-c43dd6da7153)

**Bug 描述**
ES数据源创建一个SQL数据集：
SELECT company_code,count(1) as count from fit2cloud
GROUP by company_code

数据集预览正常，在视图中使用报错

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/89771514/07f39d22-ac6f-4991-9f71-30e82a4ef86e)
![image](https://github.com/dataease/dataease/assets/89771514/39703c7b-bdfa-49d6-84d2-b3b5cabf2240)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问字段是什么类型的呢？受累看看在明细表中是否可以正常显示呢？

**Comment by ZhaoQian1222** [comment]
![image](https://github.com/dataease/dataease/assets/89771514/87a8130e-0cca-4fc4-b426-44e56046caeb)
明细表可以正常显示

字段类型信息如下：

curl -XPOST -u "elastic:elastic"  -H "Content-Type: application/json" '10.1.13.13:9200/fit2cloud/_mapping/_doc' -d '
{
      "dynamic": "true",
      "properties": {
        "available": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "birthday": {
          "type": "long"
        },
        "class_code": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "company_code": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "unique_code": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        }
      }
}'

**Comment by ZhaoQian1222** [comment]
![image](https://github.com/dataease/dataease/assets/89771514/ffd16e36-8e39-4ebb-8a4a-ead0bbad9d80)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前es暂不支持text的聚合，我们还在努力完善请耐心等候；

**Comment by BBchicken-9527** [comment]
抱歉，目前经过我们讨论这里的功能无法实现，问题已加入到问题池中，后续中若有良好的解决方法将会再进行处理；
