### ISSUE TITLE
[Feature]已存在的定时同步数据集切换数据源后无法选择模式，只能默认为直连模式，希望能支持自定义模式

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5225]
**请描述您的需求或者改进建议.**
已存在的定时同步数据集切换数据源后无法选择模式，只能默认为直连模式，希望切换数据集的数据源的时候也能支持自定义模式：直连/定时同步

**Comment by xuwei-fit2cloud** [comment]
数据集同步类型是不允许修改的，所以之前是定时同步类型的数据集，之后也只能是定时同步类型的数据集。
您在切换数据源后，页面上定时同步选项消失，是为了避免不必要的操作，但确实也会存在理解问题，让您误会此处数据集的同步类型有所改变。
我们在后面的版本里对这块做一下优化，选项仍然显示出来，但处于disable状态。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
