### ISSUE TITLE
[Feature]文本过滤组件想从上面的选择框里面把它删掉，但是找不到是哪一个

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5226]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/89771514/7076f78f-a7a4-4ee7-a239-ec0e17ad05b9)

文本过滤组件的选择框无法得知哪个字段对应的是哪个数据集

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们增加个提示优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
