### ISSUE TITLE
[Feature]【仪表板】仪表板获取数据优化

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5230]
**请描述您的需求或者改进建议.**
可以基于 Redis 做一个数据缓存，不要每次打开大屏都要重新查数据库的数据，而是从缓存中查数据；

**Comment by xuwei-fit2cloud** [comment]
为了满足数据实时性的需求，当前DataEase中直连模式数据集我们并没有做缓存，但对于定时同步类型的数据集，我们是有数据缓存机制的。
您可以将仪表板中实时性要求不高的数据集更换为定时同步类型的数据集试试。
