### ISSUE TITLE
[Feature]【视图】视图标签设置优化

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5231]
**请描述您的需求或者改进建议.**
视图中多条线进行展示的时候，有时候会出现标签叠加在一起的情况，希望视图支持分指标设置标签位置（上下，相对等）

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，折线图的标签显示在上中下差别不太大，线条比较密集的情况下，为了展示效果，建议您隐藏标签。
