### ISSUE TITLE
[Feature]【视图】视图放大框支持样式设置

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5232]
**请描述您的需求或者改进建议.**
放大视图的时候，视图的放大框支持样式设置，让仪表板看起来更加炫酷。或者另外加一个点击放大的功能，也可以理解为点击悬浮的效果。
![image](https://github.com/dataease/dataease/assets/24768910/873df11e-0741-432f-bef5-586b78825f15)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。
