### ISSUE TITLE
[Bug]上传 svg 格式图片文件时报错

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5233]
**DataEase 版本**
V1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新

**Bug 描述**
图片组件上传 svg 格式图片时提示异常信息：
io.dataease.commons.exception.DEException: Multipart file must be image

**Bug 重现步骤(有截图更好)**
![WeChatea2c39f6cee2aec12980f71c6742ae39](https://github.com/dataease/dataease/assets/30886198/c7b43687-88e1-45ec-bac3-52b37049b4f3)

要上传的图片：
![DataEase](https://github.com/dataease/dataease/assets/30886198/ca431446-884b-4f3d-9f6c-ed8378719229)
使用这个 jpg 图片也会报错
[2.jpg.zip](https://github.com/dataease/dataease/files/11495019/2.jpg.zip)

**Comment by BBchicken-9527** [comment]
感谢反馈，此为已知问题，问题将会在后续版本中修复；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
