### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by wikeryong** [dataease/dataease#5235]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
docker 运行

**浏览器版本**
版本 113.0.1774.42 (正式版本) (64 位)

**Bug 描述**
新建数据集时，Mongo的字段是中文，提报错
java.sql.SQLException: Parse Exception: unity.parser.TokenMgrError: Lexical error at line 1

**Bug 重现步骤(有截图更好)**
1.新建mongo数据源，编码设置为UTF-8或者不设置
2.新建数据集，选择对应的mongo数据源，提示报错
3.我的结构如下图
{
    "中文":{}
}

**Comment by BBchicken-9527** [comment]
由于mongodb的driver自身的功能支持性上不完备，建议使用mongodb-bi的方式尝试连接；

**Comment by wikeryong** [comment]
> 

用的MongoDB

**Comment by BBchicken-9527** [comment]
> > 
> 
> 用的MongoDB

建议你使用Mongodb-bi进行创建数据集，就像我说的mongodb的driver会缺少很多的功能；

**Comment by BBchicken-9527** [comment]
不知道是否还有其他问题吗，若没有问题将会在下午6:30进行关闭；
