### ISSUE TITLE
[Feature] starrocks integration 

### ISSUE THREAD

**Issue by alifzl** [dataease/dataease#5236]
I wonder is it possible to integrate [starrocks](https://www.starrocks.io) to dataease solution?

**Comment by yayanpei-fit2cloud** [comment]
Thanks for your support. We have recorded and placed it in the requirement pool. As the current main task is the development of 2.0, we do not plan to develop a new data source in the near future.

**Comment by alifzl** [comment]
OK. thanks for the kind response.
