### ISSUE TITLE
请问这源码能直接用idea运行吗？我的运行不了[Question]

### ISSUE THREAD

**Issue by dc1013** [dataease/dataease#5238]
**请描述您的问题.**
请问这源码能直接用idea运行吗？我的运行不了，没办法下载maven包，是不是要jdk8还是‘’？哪里有源码的部署手册？
![image](https://github.com/dataease/dataease/assets/28622226/b79266fa-fc4f-4cfd-b54b-4bc57b921026)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，将源码下载至本地，maven使用中央仓库的，使用jdk8
