### ISSUE TITLE
[Bug] 组件样式清空背景色后，无法选中白色

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5239]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
组件样式清空背景色后，无法选中白色

**Bug 重现步骤(有截图更好)**
![组件样式背景色选择](https://github.com/dataease/dataease/assets/45852479/42088a36-4a77-4eff-a773-2fe0a81837b4)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
