### ISSUE TITLE
[Feature]添加数据库数据集的同时，可以对该数据库数据集进行命名

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#524]
**请描述您的需求或者改进建议.**
作为DataEase使用者，我希望在添加数据库数据集时，在Web Ui上可以对该数据库数据集进行命名。目前默认是使用数据库表名进行命名，有两个问题，一个是阅读习惯问题，国内大部分还是对中文阅读比较习惯，另外就是数据库表名有可能很长，在左边的树状结构中有可能显示不全。所以目前我一般添加之后都要再次进行重命名，可以更简洁一些。
此外也是希望和其它地方的设计风格保持一致，例如添加SQL数据集、添加Excel数据集时，都可以命名。

**Comment by xuwei-fit2cloud** [comment]
数据库数据集和其他类型的数据集有一个比较大的区别在于，它支持批量创建，可以一次选择多个数据表创建多个数据集，所以命名这个功能如果要加上的话，需要一个比较好的交互设计，我们思考一下。

**Comment by xuwei-fit2cloud** [comment]
暂时不予处理。
