### ISSUE TITLE
[Bug]在 Tab 页中添加 AntV 符号地图显示异常

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#5242]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google 113.0.5672.126（正式版本） (arm64)

**Bug 描述**
添加两个地图到Tab页里，制作界面显示正常。预览时，第二个地图显示异常。

**Bug 重现步骤(有截图更好)**
1. **制作界面：**
地图一：
![image](https://github.com/dataease/dataease/assets/85436572/2de90e68-2112-4c75-844e-fd63ac3986ce)
地图二：
![image](https://github.com/dataease/dataease/assets/85436572/d90ddbf2-2e65-4059-895a-254f6080ac53)
2.**预览界面**
地图一：
![image](https://github.com/dataease/dataease/assets/85436572/31d6cce2-0d64-43c5-ac55-f3db636d7228)
地图二：
![image](https://github.com/dataease/dataease/assets/85436572/4c1f2e9f-2c19-4457-9778-46f3fae03d87)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
