### ISSUE TITLE
[Bug]PostgreSql数据源，创建了一个数据集，添加视图计算字段使用sum (a)/sum(b)除法运行异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5243]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
PostgreSql数据源，创建了一个数据集，在视图中添加视图计算字段使用

sum (a字段)/sum(b字段)除法运行异常

**Bug 重现步骤(有截图更好)**
数据集：
![image](https://github.com/dataease/dataease/assets/89771514/1b24b32b-8b92-416e-8163-036248ba7cb9)

字段类型：
![image](https://github.com/dataease/dataease/assets/89771514/b2d6e0f2-581e-49f7-9e01-8ac15d595631)

视图计算字段：
![image](https://github.com/dataease/dataease/assets/89771514/3ea39131-3339-4419-aa2d-8391cae77945)

异常截图：
![image](https://github.com/dataease/dataease/assets/89771514/894ae2ec-e853-4b7b-a25d-363f4edd20fe)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前视图计算字段，不支持再次聚合，求和平均都不能；
