### ISSUE TITLE
[Bug]AntV汇总表序号的文本颜色无法跟随表格字体颜色变化

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5246]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**Bug 描述**
AntV汇总表序号的文本颜色无法跟随表格字体颜色变化
<img width="995" alt="iShot_2023-05-18_21 01 14" src="https://github.com/dataease/dataease/assets/89771514/5afa7e5a-3a96-4178-9399-0f4db2e4d85d">
<img width="986" alt="iShot_2023-05-18_21 01 34" src="https://github.com/dataease/dataease/assets/89771514/118e2d90-23e6-4c92-b9f2-76f9bc563220">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
