### ISSUE TITLE
[Feature]导出为应用 ，提示该仪表板存在模板中的视图，建议优化下提示，提示出具体的视图名称

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5247]
**请描述您的需求或者改进建议.**
导出为应用 ，提示：该仪表板存在模板中的视图
不知道是哪一个视图
可以优化下提示，提示出具体的视图名称

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们后续版本做一下相关优化。

**Comment by ziyujiahao** [comment]
https://github.com/dataease/dataease/pull/7927/commits/e6293fe1dc902f9a829490b0b02511923010f51b
