### ISSUE TITLE
[Feature]视图支持通过设置元素的点击，控制一个或多个其它视图组件的显隐

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5248]
**请描述您的需求或者改进建议.**
视图支持通过设置元素的点击，控制一个或多个其它视图组件的显隐
应用场景：
想在地图上做了业务的分析功能，点击"分析"按钮，能在旁边弹出一排分析图表，不用的时候再点击按钮就能隐藏
不需要数据做联动，只是显示和隐藏

**Comment by xuwei-fit2cloud** [comment]
您的建议我们已收到，但具体设计与实现我们还需要做进一步的讨论，在当前的1.x版本中暂时还不好有相关计划。

**Comment by xuwei-fit2cloud** [comment]
您好，这个需求短期内还不会做相关支持。
