### ISSUE TITLE
[Feature]dataease跳转第三方链接，希望支持携带过滤组件的数值做参数

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5250]
**请描述您的需求或者改进建议.**
dataease跳转第三方链接，支持携带参数
是想在视图的跳转设置里的超链接上拼接上这个下拉框的值作为参数

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议很不错，我们先加入需求池中，后期规划优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
