### ISSUE TITLE
[Bug] SQL 参数报错

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5253]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
SQL 参数报错

**Bug 重现步骤(有截图更好)**
1.sql 如图 
<img width="990" alt="image" src="https://github.com/dataease/dataease/assets/45852479/9a4a3243-2f25-4a39-b1fc-78d6f20abb4d">
2.去除参数可以执行
<img width="680" alt="image" src="https://github.com/dataease/dataease/assets/45852479/d5edbaf4-d918-4ede-9a56-aa1f96f753fb">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by BBchicken-9527** [comment]
感谢反馈，我们修复一下；
