### ISSUE TITLE
[Bug]仪表板样式设置过滤组件样式设置不生效

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5254]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/89771514/ba6ca0a7-9233-4f1f-ace9-94a6905cba89)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，试试清一下缓存呢？

**Comment by ZhaoQian1222** [comment]
保存后再次编辑可以了，可能是缓存的问题，但是有一个新的问题出现，即编辑生效后仪表板未识别到变化，保存按钮不可点击
![image](https://github.com/dataease/dataease/assets/89771514/5ef35e8c-a2f1-41c9-acdf-7542f178f68c)

**Comment by BBchicken-9527** [comment]
好的此处我们修复一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
