### ISSUE TITLE
[Bug]新建的仪表板保存为模板，数据表 panel_template 里多了很多垃圾数据

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5256]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
创建了一个仪表板，把这个仪表板保存为模板的时候，panel_template表中的dynamic_data字段会把以前模板的数据也带上
![image](https://github.com/dataease/dataease/assets/89771514/02c6c971-b4a7-41d7-9c64-8bdf649ea647)
![image](https://github.com/dataease/dataease/assets/89771514/fe5ba646-8bea-48c7-b117-40ef1d0efd6e)

使用上没什么问题，因为 panel_data 是对的，就是每次依据这个模板去创建仪表板的时候，chart_view 表会有很多垃圾数据

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by ZhaoQian1222** [comment]
OK
