### ISSUE TITLE
[Feature]融合AI能力

### ISSUE THREAD

**Issue by cake79** [dataease/dataease#5263]
**请描述您的需求或者改进建议.**
AIGC对BI产品有巨大商业价值及应用空间，希望下阶段产研方向可以融合AI能力
1、SQL助手
特性：支持自然语言转 SQL、SQL 转自然语言、SQL 优化建议
项目：阿里开源项目Chat2DB，地址：https://github.com/alibaba/Chat2DB
2、AI 图表&解读生成
特性：根据自然语言生成对应的分析看板及图表，将图表数据绑定到数据模型中的字段来关联图表数据将数据转化为有意义的故事或信息，从而提供数据的更深层次的解释和理解。

![image](https://github.com/dataease/dataease/assets/116251332/647ef0c3-49ba-456e-8e33-f81e00615e50)

**Comment by maninhill** [comment]
感谢你的建议。我们也正在研究，希望能尽快融合到产品中去。

**Comment by cake79** [comment]
Microsoft  CoPilot 的一些精彩演示：
https://www.youtube.com/watch?v=E5g20qmeKpg
