### ISSUE TITLE
[Bug]新建计算字段时通过函数保留3位小数，但dataease给转成了一位

### ISSUE THREAD

**Issue by WZqian6688** [dataease/dataease#5265]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
fix:计算字段，页面和数据库里的结果不一样，我函数里写的保留3位小数点，但dataease给转成了一位
![654b6f0049b6a4d8ca92581960ac639](https://github.com/dataease/dataease/assets/111053436/69fa37ae-8188-4014-9c58-9f1a3161f43a)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by WZqian6688** [comment]
版本1.18.6，数据源是mysql

**Comment by WZqian6688** [comment]
![image](https://github.com/dataease/dataease/assets/111053436/c6a00ef6-6153-484b-9460-ae9f1c36f0cf)

**Comment by BBchicken-9527** [comment]
那咱俩的环境应该是统一的，你是二开了吗？

**Comment by WZqian6688** [comment]
![image](https://github.com/dataease/dataease/assets/111053436/08d5be57-af38-4fe8-9480-6b9c7f794f93)
![image](https://github.com/dataease/dataease/assets/111053436/964dbb5a-6173-4240-92a5-4df34a0ed008)
![image](https://github.com/dataease/dataease/assets/111053436/9fc5cfc6-2ade-406f-99cd-eb69b2f28f1b)
我是二开了，但这是你们的环境，round小数点还是没有保留呢。

**Comment by BBchicken-9527** [comment]
> ![image](https://user-images.githubusercontent.com/111053436/240190282-08d5be57-af38-4fe8-9480-6b9c7f794f93.png) ![image](https://user-images.githubusercontent.com/111053436/240190610-964dbb5a-6173-4240-92a5-4df34a0ed008.png) ![image](https://user-images.githubusercontent.com/111053436/240190706-9fc5cfc6-2ade-406f-99cd-eb69b2f28f1b.png) 我是二开了，但这是你们的环境，round小数点还是没有保留呢。

受累看看这个qwe这个表的字段类型是什么呢？应该是一个整型吧

**Comment by WZqian6688** [comment]
![image](https://github.com/dataease/dataease/assets/111053436/df8f0ece-f3c5-4410-ab73-28a43a9c864a)
好神奇。。qwe表这个字段也显示的小数类型，
![image](https://github.com/dataease/dataease/assets/111053436/ed74f37e-dfb1-4300-814e-b09c3dcf7699)
你们这个demo表这个字段也显示的小数类型，为什么这个表计算就是对的呢。。。

打扰再问一下，这个计算是要库里字段为小数类型，计算后才能正确显示吗？

**Comment by BBchicken-9527** [comment]
额。其实直连数据我们是没有做处理的，driver返的数据直接呈现的，也不一定要数据库字段类型是小数，但不能是整数，这是mysql自身特性导致的
![图片](https://github.com/dataease/dataease/assets/84372766/675b4a36-d220-4ab3-b7ba-16786851f29f)

**Comment by WZqian6688** [comment]
额。知识欠缺了，没想到是mysql自身特性导致的。明白了，感谢~

**Comment by BBchicken-9527** [comment]
好的，如果没有别的问题我就先关闭这个问题了，感谢你的提出的疑问与支持，如果有更多的疑问可以加入我们的交流群上面会有专门的人员替你解答，也可以直接在github中提出；
