### ISSUE TITLE
[Feature]现在可以通过API数据源配置，实现连接TDengine数据库吗？尝试用这种方法连接TDengine，但是得到的Data 

### ISSUE THREAD

**Issue by likang105030** [dataease/dataease#5267]
**请描述您的需求或者改进建议.**

**Comment by likang105030** [comment]
形式如下： "data": [
        [
            "information_schema",
            16,
            "ready"
        ],
        [
            "performance_schema",
            9,
            "ready"
        ] ；这种data格式，好像并不能生成 对应的表

**Comment by xuwei-fit2cloud** [comment]
是的，从返回的数据结构来看，并不是键值对形式，也就不能在二维表中创建对应的字段名，所以目前还不太好处理。
