### ISSUE TITLE
修改mysql端口导致无法启动dataease[Bug]

### ISSUE THREAD

**Issue by rty813** [dataease/dataease#5270]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
如果本机已经使用了3306端口，修改install.conf中的mysql端口为其他端口，例如3307，会导致无法启动dataease容器。
这是因为，修改后，dataease中的jdbc连接参数中使用的为3307端口，但是3307仅为Docker暴露在主机上的端口。如果不修改install.conf中mysql_host为主机的eth IP的话，会导致dataease会用docker的虚拟网卡访问mysql。这种情况下，3307端口肯定是不通的，需要修改jdbc中的3307，改为3306，即可访问。

**Comment by xuwei-fit2cloud** [comment]
您可以参考一下文档：
https://dataease.io/docs/faq/configuration_faq/dataease_mysql/#1-mysql
