### ISSUE TITLE
请问有什么办法可以在群晖的DOCKER中运行么？[Question]

### ISSUE THREAD

**Issue by xihan62** [dataease/dataease#5271]
**请描述您的问题.**
1. 我目前运行在群晖的虚拟机上，我想使用群晖自带的docker来运行请问怎么操作？
2. Dataease制作出来的报表，我想嵌入到我的wordpress中，但是发现一个问题，我的公共连接是http的而wordpress是https。如果不将dataease的连接变成加密的，那么就无法使用iframe嵌入到wordpress中。
请问这两个问题有什么解决方案么？谢谢！！

**Comment by xuwei-fit2cloud** [comment]
1. 群晖的环境我们这里没有，所以不太好测试。您可以先确认一下群晖平台架构，看介绍的话，群晖应该也会区分x86和ARM，您可以根据架构的不同，选择我们不同的离线安装包尝试安装；
2. 可以在前端加一个Nginx，将DataEase转为HTTPS访问即可。
