### ISSUE TITLE
【Feature】数据集导入问题

### ISSUE THREAD

**Issue by yingnan521** [dataease/dataease#5277]
1、能否支持大屏展示的表格关联多个excel数据集，场景需求是大屏要对外展示每天的产品数据，这个数据每天都不一样，所以每天都会生产新的excel数据表格。所以能否实现每天上传一个ecxel数据集，然后大屏表格展示可以选择多个excel。
2、如果以上功能无法实现，在现有追加数据集上能否增加一个 撤销或者删除上次追加数据，因为比如我的数据集里已经有修改好的一部分数据，已经在展示了，当我追加新的excel数据集时，这部分有点格式的问题，或者出现空数据，导致我展示的数据就有问题了，但是此时也无法方便的回复之前没有问题的阶段，此时想修改只能把所有数据集都删除了，重新上传之前没问题的数据，这就很麻烦。望采纳。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，一个图表只能使用一个数据集，所以无法做到一个表格选择多个excel。关于撤销追加数据的功能，我们还需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的关注和支持，经过讨论，我们暂不计划支持撤销功能，如果要支持，每个excel数据集都需要在后台多缓存一份数据，开销也是比较大的。我们会优化追加数据时的提示信息，方便用户提前做好数据备份，来应对需要撤销追加的场景。
