### ISSUE TITLE
[Bug]明细表颜色控制调色板无法全部显示

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#528]
**DataEase 版本**
v1.1.0-rc2

**浏览器版本**
chrome: 92.0.4515.107

**Bug 描述**
调整明细表图形颜色属性时，表头背景、表格背景的颜色调色板无法完全显示。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/46042812/128200076-e7e41937-1edd-4395-83fd-69bc6b695457.png)

**Comment by xuwei-fit2cloud** [comment]
感谢您的反馈，我们已确认是bug，我们会尽快修复。

**Comment by XiaJunjie2020** [comment]
v1.1.0已解决
