### ISSUE TITLE
[Bug]达梦数据库新建计算字段，使用函数计算，只要返回值是0的，dataease都给处理成0.0了

### ISSUE THREAD

**Issue by WZqian6688** [dataease/dataease#5280]
**DataEase 版本**

1.18.6
**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**

**Bug 描述**
达梦数据库新建计算字段，使用函数计算，只要返回值是0的，dataease都给处理成0.0了。比如函数LEAST、ABS、ROUND等。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/111053436/c209a000-d16c-4eaf-9ae5-427c6718fe5f)

2.
![900d537abb4de89588d24d9ebeb5659](https://github.com/dataease/dataease/assets/111053436/050e62e5-bb6a-40a4-affa-460fce7110c7)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有你说的问题，新建计算字段时字段类型是否正确呢？

**Comment by WZqian6688** [comment]
新建字段类型都是数值类型。我这还是有问题，可以给我看看你们运行后的结果图吗，我这还是显示0.0

**Comment by BBchicken-9527** [comment]
不好意思，我这边是不能这样做的。
