### ISSUE TITLE
[Bug]复杂sql union all关联查询不支持，使用union all查询实际返回的是“union”的查询结果

### ISSUE THREAD

**Issue by nawentao** [dataease/dataease#5281]
**DataEase 版本**
v1.18.5
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome 113.0.5672.92

**Bug 描述**
复杂sql union all关联查询不支持，使用union all查询实际返回的是“union”的查询结果
**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，你是定时同步吧，如果是直连是没有问题的，但定时同步底不支持是因为将数据放到了doris中而doris是自动去重的

**Comment by BBchicken-9527** [comment]
请问还有其他问题吗如果没有的话问题将在今天下午6:30关闭
