### ISSUE TITLE
[Bug]使用ES数据源进行查询时，会出现查询报错。以及通过报表查询出来的结果列，本该有数据，但是实际数据没有展示

### ISSUE THREAD

**Issue by blooze123** [dataease/dataease#5284]
**DataEase 版本**
V1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
在连接配置了ElasticSearch数据源，配置完成后，在仪表盘使用查询条件进行查询时，会报错：
![93ef7df03074ef2a80a2a010d98df1d5_](https://github.com/dataease/dataease/assets/47737772/54c88b77-4e96-44d1-aa79-355ddf82826c)
此外，在报表展示时，会出现原本应该存在的列数据，展示出来后，数据是空的，如下图：
![0c9d6e495ed1b0a891ac2a8fbff97576_](https://github.com/dataease/dataease/assets/47737772/c7fe3aad-aac7-47fc-a2f0-00a078714b03)
还有，希望能解答一下关于ES数据源这块适配性上的兼容性，是否有指定版本兼容，DE哪些统计报表不支持ES的视图，后续是否会做支持。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，请问使用的es版本是什么？还有就是使用的是什么类型的字段呢？目前是不支持text类型过滤的。

**Comment by BBchicken-9527** [comment]
你好，是问题已经解决了吗？如果没有其他问题将于下午六点三十分时关闭

**Comment by blooze123** [comment]
嗯嗯，先关闭吧，后续有问题再请教请教哈
