### ISSUE TITLE
[Bug]气泡图插件前端运行测试缺少webpack配置文件

### ISSUE THREAD

**Issue by luanlinpeng** [dataease/dataease#5288]
**DataEase 版本**
1.81.6

**运行方式(安装包运行 or 源码运行 ?)**
cd dataease-extensions-view/view-bubblemap/view-bubblemap-frontend
npm i
npm run dev

**浏览器版本**
谷歌 113.0.5672.127

**Bug 描述**
气泡地图插件前端需要二次开发或开发其他插件，dataease-extensions里代码缺少webpack配置文件

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/89448362/3e89149b-d4f2-4e52-a538-fec40bbfd2fb)

2.
3.

**Comment by maninhill** [comment]
二开请自行阅读源码和问答。
