### ISSUE TITLE
[Bug]视图/指标卡/组件样式 标题Disable/Enable开关有时无效

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#529]
**DataEase 版本**
v1.1.0-rc2

**浏览器版本**
chrome:92.0.4515.107

**Bug 描述**
视图/指标卡/组件样式 标题Disable/Enable开关有时无效,暂时没有找到规律

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/46042812/128212233-6b148a82-4480-437e-87e1-5d862729826f.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们排查一下问题。

**Comment by xuwei-fit2cloud** [comment]
v1.2.0 已修复
