### ISSUE TITLE
[Feature] 分组堆叠柱状图相关优化建议

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5290]
**请描述您的需求或者改进建议.**
如图：
1、目前的分组堆叠柱状图提示不支持展示子维度相关信息，并且提示信息会受到当前视图的大小限制，展示不全。
![image](https://github.com/dataease/dataease/assets/30063018/4300a3ae-ce38-415a-8051-0b29bd04804f)
![image](https://github.com/dataease/dataease/assets/30063018/d137cac6-8164-4b34-9a27-c86814668cd9)
2、堆叠项支持年季度（目前维度支持的数据源堆叠项也可同步支持）
![image](https://github.com/dataease/dataease/assets/30063018/bf9c2a2d-4d1d-4e63-a2b1-656681429dcb)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们要看下图库是否支持。

**Comment by yayanpei-fit2cloud** [comment]
目前用的图库确实存在展示不全的情况，暂时还没有好的解决方法。
堆叠项支持年季度，暂时仅支持了MySQL、Doris、StarRocks，这是由于数据源的用户存在差异，逐个支持会花费较多的精力，因此在1.x上暂不计划继续支持，您这边用的是什么数据源？

**Comment by ziliang-wan** [comment]
Excel 数据集，是 local 模式部署的，数据上传到 doris 的，这么看来可能是个 bug ?

**Comment by yayanpei-fit2cloud** [comment]
年季度目前子维度上没有增加，我们先记录并优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
