### ISSUE TITLE
[Feature] 视图过滤器，日期及数字类型支持非空判断

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5291]
**请描述您的需求或者改进建议.**
视图过滤器，日期及数字类型支持非空判断，这个还挺常用的，建议支持下。
![image](https://github.com/dataease/dataease/assets/30063018/4ae46b78-b172-41aa-92b4-a9172ccf8c6f)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们优化一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已在版本 V1.18.9 中进行优化，如有需要，建议把版本升级至 V1.18.9。
