### ISSUE TITLE
[Bug]编辑仪表盘时，右键功能菜单被遮挡。

### ISSUE THREAD

**Issue by zhanggefei** [dataease/dataease#53]
**DataEase 版本**
v1.0.0-rc2

**Bug 描述**
编辑仪表盘时，右键功能菜单被遮挡。

**Bug 重现步骤(有截图更好)**
![WechatIMG1588](https://user-images.githubusercontent.com/37612532/123510777-f2705100-d6af-11eb-8da5-d9e647215a39.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复一下

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本增加编辑按钮
