### ISSUE TITLE
页面刷新自动返回 时间组建默认值  高频刷新的交互页不可使用

### ISSUE THREAD

**Issue by Mini2118** [dataease/dataease#5304]
**DataEase 版本**
 18.6  4.17更新版本

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**
最新版Chrome

**Bug 描述**
仪表板设置高频更新的场景下，时间过滤组建刷新未保留选择条件，刷新返回默认范围
不支持高频数据更新业务的交互屏使用

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们已经记录了，内部讨论一下功能的可行性，产出结果会第一时间给你回复；

**Comment by xuwei-fit2cloud** [comment]
我们在后续版本里对这个使用场景进行一下优化处理。

**Comment by Mini2118** [comment]
这个问题有计划时间么？

**Comment by BBchicken-9527** [comment]
正在排期，请耐心等待...

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
