### ISSUE TITLE
[Feature]优化仪表板页面查看方式

### ISSUE THREAD

**Issue by qiulinjie0327** [dataease/dataease#5309]
**请描述您的需求或者改进建议.**
目前点到仪表板菜单页面，会访默认仪表板内第一个仪表板，如果默认仪表板没有内容则是空白，能否调整查看方式，以分组加略缩图的形式展示，点击之后再查看仪表板具体内容

![image](https://github.com/dataease/dataease/assets/52249559/a95d65e1-9f21-40a6-97da-6f4708a97639)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，您的建议我们已经讨论过，但和目前的设计比较，并没有太大的变化，所以我们暂时还是保留当前设计。
