### ISSUE TITLE
[Feature]视图详情表格的表头希望可以设置自动换行和列宽自适应，每次都需要一个一个调列宽不是很方便使用

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5310]
**请描述您的需求或者改进建议.**
视图详情表格的表头希望可以设置自动换行和列宽自适应，每次都需要一个一个调列宽不是很方便使用
![image](https://github.com/dataease/dataease/assets/89771514/95ef622f-4179-4944-b50a-ffd6b7d9f86f)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，但目前我们在视图详情里所用到的表格组件还不支持列宽的自适应。
