### ISSUE TITLE
[Bug]新建视图计算字段，可以与原字段重名。

### ISSUE THREAD

**Issue by WZqian6688** [dataease/dataease#5313]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**

**Bug 描述**
新建视图计算字段，名称校验时，只对视图计算字段进行了重命名校验，没有对原数据集字段进行重命名校验。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/111053436/04bacaa3-291d-4aa9-9736-8316b34feb67)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by BBchicken-9527** [comment]
感谢反馈，这是因为视图计算字段跟随视图当你使用相同的数据源去创建一个新的视图的时候这个字段就会消失的。虽然回到视图编辑里，看起来重复，但本身就来自两个不同的地方的；

**Comment by BBchicken-9527** [comment]
你好，请问还有其他的问题吗，如果没有的话问题将在今天下午6:30关闭
