### ISSUE TITLE
富文本与操作界面重合

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#5315]
富文本在画面右侧时，点击编辑会与右侧操作界面重合，建议修复
![image](https://github.com/dataease/dataease/assets/133861755/2ff7d48b-b2eb-4a01-9a2e-c9e9d68dcef4)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，确实存在这个问题，我们修复一下。

**Comment by BBchicken-9527** [comment]
问题已修复，请升级到最新版本体验；
