### ISSUE TITLE
[Feature]新建计算字段建议支持外部参数

### ISSUE THREAD

**Issue by evanlin84991** [dataease/dataease#5316]
**请描述您的需求或者改进建议.**
<img width="545" alt="微信图片_20230525150657" src="https://github.com/dataease/dataease/assets/52950960/4431a88c-cc43-412f-a5c5-2f58f371c1ad">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要讨论一下。

**Comment by xuwei-fit2cloud** [comment]
目前没有想到比较合适的使用场景，暂时没有对应的支持计划。
