### ISSUE TITLE
[Bug]文本组件在仪表板和tab页相同大小，显示有差异

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#5317]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**

安装包运行

**浏览器版本**

Chrome 版本 113.0.5672.127（正式版本）

**Bug 描述**
文本组件在仪表板和tab页面里面，设置相同大小，显示起来却有差异

**Bug 重现步骤(有截图更好)**

<img width="632" alt="0dd500fd94900b808dce8a7788322f8" src="https://github.com/dataease/dataease/assets/127368807/10bf1771-15e3-44ae-9ebd-cfd2295e57e5">

**Comment by BBchicken-9527** [comment]
感谢反馈，显示不一样的原因是因为本质上选项卡也是画布，两个的缩放比例不一样，所以并不是问题的；

**Comment by BBchicken-9527** [comment]
你好，不知道我之前的回答是否解决了你的疑虑呢？若没有其他问题将于下午6:30关闭

**Comment by greenyhsj** [comment]
好的，如果不算BUG那就没有问题哈。
