### ISSUE TITLE
EXCEL数据集更新撤回

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#5322]
EXCEL有时候追加数据失败，或者追加数据错误，希望有个撤回的功能

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，该issue同5277，待我们讨论后统一回复。

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #5277

**Comment by yayanpei-fit2cloud** [comment]
经过讨论，我们暂不计划支持撤销功能，如果要支持，每个excel数据集都需要在后台多缓存一份数据，开销也是比较大的。
我们会优化追加数据时的提示信息，方便用户提前做好数据备份，来应对需要撤销追加的场景。

Issue就先暂时关闭了，再次感谢您的关注和支持。
