### ISSUE TITLE
[Bug]地图视图进行下钻联动后，回退升级联动异常

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#5325]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
地图视图进行联动时，如果是就在地图选择省份下钻到市级联动后，回退到省级进行其他省份联动失效，但如果是下钻到其他省份下的市级联动可以生效

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/127368807/fa8da411-c6b4-4785-8cab-0e8228ce904b)

2.
![image](https://github.com/dataease/dataease/assets/127368807/dc7712a5-406b-40a5-82cc-869fb3ccc821)

3.
![image](https://github.com/dataease/dataease/assets/127368807/b57008a6-ac89-4782-bf97-385476d6f71b)
应该是联动以后穿了城市的参数，退回来以后没有刷新，城市的参数还带着

![image](https://github.com/dataease/dataease/assets/127368807/50c03982-34da-4333-9157-c1b512b23b9c)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的这个问题，请问你点击右上角的清除所有联动了吗

**Comment by greenyhsj** [comment]
还是会出现这种情况，用了两个环境测试过了。你试着点击湖南进行下钻，选择长沙后进行联动，再返回选择广东进行联动，这个时候就会报错，但是下钻到城市，选择深圳进行联动，可是广东联动又会报错

> 感谢反馈，目前测试环境没有发现你说的这个问题，请问你点击右上角的清除所有联动了吗

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by greenyhsj** [comment]
开源群社区反馈的这个问题，然后我又复现了，用了两个部署的DataEase都出现这种情况，在下钻到城市联动的时候，返回到省份进行联动就会异常

**Comment by BBchicken-9527** [comment]
嗯...私聊一下？

**Comment by greenyhsj** [comment]
好嘞

**Comment by BBchicken-9527** [comment]
问题已修复，可下载新版本体验；
