### ISSUE TITLE
[Bug]【视图】kurtPop()函数在视图计算字段中使用报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5334]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
ClickHouse 数据库 kurtPop()函数在视图计算字段中使用报错

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/24768910/71ac61c0-9f8c-4258-ae7a-38dee242548e)
![image](https://github.com/dataease/dataease/assets/24768910/2cdb9a70-44db-4c2e-a015-07f99b0d201a)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by BBchicken-9527** [comment]
你好，计算字段是不支持聚合函数的；
<img width="893" alt="图片" src="https://github.com/dataease/dataease/assets/84372766/a75ff16f-b49c-47af-8825-000f4916d966">
