### ISSUE TITLE
[Feature] SQL 数据集的数据参考栏在表名过长时无法显示全名，导致无法区分表名

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5339]
**请描述您的需求或者改进建议.**
建议提供滚动显示功能，或鼠标移上时悬浮显示全名。
![image](https://github.com/dataease/dataease/assets/30886198/f36e8c2c-9d5b-4924-b48d-806266c723d1)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们增加一下悬浮显示。

**Comment by xuwei-fit2cloud** [comment]
v1.18.7版本已处理，请升级最新版本。
