### ISSUE TITLE
[Feature]维度和指标支持多选拖动

### ISSUE THREAD

**Issue by hds1999** [dataease/dataease#5347]
在编辑仪表板的时候，建议维度和指标可以多选，然后再拖动到数据列。
![75161b64c54f8cf31d780618c156238](https://github.com/dataease/dataease/assets/20547693/71811cbd-893c-4601-a74d-595e06a858e1)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，2.0已有相关设计。
