### ISSUE TITLE
[Bug]鼠标点击符号地图后，再移动鼠标地图随鼠标移动

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5351]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
鼠标在符号地图中点击后，无法移出符号地图，鼠标移动地图也在移动，除非双击可终止移动。
<img width="1467" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/c6036a41-deae-489f-976f-bd0a1e286a7e">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前还没有找到合适的方法去控制此处的事件
