### ISSUE TITLE
[Feature]自定义表格各字段的宽度

### ISSUE THREAD

**Issue by zzx769394358** [dataease/dataease#5352]
**请描述您的需求或者改进建议.**
某table只有4列，
名称  类型   价格  时间
名称长度不定，  类型   价格  时间 都是比较短的

若使用自适应， 会把名称拉很长， 导致后面的列看不见；
若使用自定义， 则会均分表格宽度， 后面的列不需要那么宽， 想分一点给前面的名称

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，但目前所用的表格组件S2还不支持，所以短期内还无法实现。

**Comment by QQ853695231** [comment]
能加个element ui当中的表格吗？
