### ISSUE TITLE
[Feature]个人信息页面，认证绑定样式建议优化，

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5356]
**请描述您的需求或者改进建议.**
这里的认证很多人都以为是已经绑定钉钉的状态，但实际是需要操作的状态，是否可以考虑更换较为不容易引起歧义的设计

![iShot_2023-05-29_17 06 55](https://github.com/dataease/dataease/assets/89771514/df801939-67e4-483a-b6ad-d07d180ca328)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，这个样式我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.8版本已处理，请更新版本。
