### ISSUE TITLE
[Feature] How to expose knife4j swagger/openapi

### ISSUE THREAD

**Issue by alifzl** [dataease/dataease#5367]
in application.properties of the backend, I tried to expose the internal API of the database solution:

![image](https://github.com/dataease/dataease/assets/12857891/e868ddee-9e01-48af-9560-66d3a0cc841e)

after re-launching the project, requesting the port 8083 would give me this:

<img width="834" alt="image" src="https://github.com/dataease/dataease/assets/12857891/ca8cad1e-5a09-4b50-b0b3-983e19c7b2a0">

how to access the web-ui of knife4j? how to fetch the whole api collection?
I'd be grateful if you could advise.

**Comment by yayanpei-fit2cloud** [comment]
Please refer to the following link for the api collection.
https://de.fit2cloud.com/deApi#/home

**Comment by xuwei-fit2cloud** [comment]
I'm sorry, but currently our API-related information is not available in the open source version, so the documentation is currently inaccessible.

**Comment by alifzl** [comment]
ok. thanks for clarification.
