### ISSUE TITLE
[Bug]访问仪表板分享页面报错

### ISSUE THREAD

**Issue by hds1999** [dataease/dataease#5370]
**DataEase 版本**
最新版本

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
点击仪表板分享报错
![image](https://github.com/dataease/dataease/assets/20547693/734dba93-720d-426f-b773-b78aaa8655a1)

**Bug 重现步骤(有截图更好)**

![11034c60870315c1ce68ba92a128f36](https://github.com/dataease/dataease/assets/20547693/8912eda5-6f4e-4be4-bc0a-05340f4f9eaa)

**Comment by xuwei-fit2cloud** [comment]
您好，您是否使用的是源码运行方式？
我们用最新的安装包运行并没有复现您描述的问题。

**Comment by BBchicken-9527** [comment]
未复现该问题；

**Comment by luoyang125024608** [comment]
我也出现这个问题。离线包安装的 dataease-v1.18.11-arm64-offline

**Comment by jsznb** [comment]
使用 1panel 安装, [mysql ](mysql:5.7.43), registry.cn-qingdao.aliyuncs.com/dataease/dataease:v1.18.11, 两台机器连续出现两次该问题

**Comment by jsznb** [comment]
就是 only_full_group_by 导致的

**Comment by fengqing11** [comment]
> 就是 only_full_group_by 导致的

`sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
`
禁用了only_full_group_by 为啥还是不行啊

**Comment by fengqing11** [comment]
> > 就是 only_full_group_by 导致的
> 
> `sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" ` 禁用了only_full_group_by 为啥还是不行啊

先试用ANY_VALUE函数吧

`sql
SELECT
    ANY_VALUE(`product_number`) as `product_number`,
    `spu`,
    `skc`,
    SUM(`product_sales`) AS `product_sales`
FROM
    `product_sales_data_historical`
WHERE
    statistical_date >= '${statistical_date_begin}' AND statistical_date <= '${statistical_date_end}'
GROUP BY
    `spu`,
    `skc`
ORDER BY
    product_sales desc
`
