### ISSUE TITLE
[Bug]复用组件和编辑时，Tab页的左右移动按钮被遮挡

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#5380]
**DataEase 版本**
v1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/85436572/a65bbc70-b659-4cc7-bfb2-9bfd8aa67684)
![image](https://github.com/dataease/dataease/assets/85436572/3f2c4b90-84f1-4399-b50b-337caddacb4e)

一般情况下，这个蓝色的编辑框在组件外，视图占满全屏的时候它会移动到组件内。导致左右切换的按钮会被覆盖，无法点击。

![image](https://github.com/dataease/dataease/assets/85436572/022f8959-7e5f-4893-9669-2fe31aac8a2f)
在复用场景中   左右切换的按钮也会被覆盖，无法点击。

**Comment by BBchicken-9527** [comment]
感谢反馈，问题1段时间内应该不会有改动，如果改动成本会非常高，问题2我们修复一下；

**Comment by xuwei-fit2cloud** [comment]
v1.18.8版本已处理，请更新版本。
