### ISSUE TITLE
[Bug]【定时报告】预览报告视图内容加载不全，邮件收到的报告也有视图内容加载不全的问题

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5382]
**DataEase 版本**
1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
创建一个定时报告任务，创建页面点击预览
![image](https://github.com/dataease/dataease/assets/89771514/103c045f-b855-43e5-a6df-9ebd33cecc3a)
![image](https://github.com/dataease/dataease/assets/89771514/70cdb750-246f-4447-9115-0670496ab6ba)

预览报告视图内容加载不全，邮件收到的报告也有视图内容加载不全的问题。
原因可能是等待视图加载时间过短，视图加载还没完成就被截取了，导致视图不完整

**Comment by BBchicken-9527** [comment]
感谢反馈，此问题为已知问题，但事件无法精准判断暂时还没有想到更好的处理方式，我们记录一下，这个问题先关闭，短期无法实现此处的优化
