### ISSUE TITLE
[Bug]使用sql数据集的动态参数，查询结果出错

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#5383]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge：113.0.1774.57

**Bug 描述**
数据源：oracle
[错误日志.txt](https://github.com/dataease/dataease/files/11623559/default.txt)

使用sql数据集的动态参数，查询报错，提示“The server responds 500 but no detailed message”
![image](https://github.com/dataease/dataease/assets/104493699/6a6fdef1-ac36-49e2-b768-aa9acccc1b73)
如果去掉该查询条件，或者直接在sql语句中写死一个值都可以正常查询到结果。

**Bug 重现步骤(有截图更好)**
1.使用sql数据集动态传参，点击查询
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们修复一下

**Comment by BBchicken-9527** [comment]
你好，受累看一下这里加一个别名是否可以通过
![图片](https://github.com/dataease/dataease/assets/84372766/c253b883-d7c0-4f37-8340-7b3c09072d9b)
