### ISSUE TITLE
[Feature]dataease 仪表板模块 ：网页组件

### ISSUE THREAD

**Issue by xiaoran1020** [dataease/dataease#5384]
**请描述您的需求或者改进建议.**
希望可以支持动态 通过接口 来修改网页组件的 url地址。  类似动态修改iframe地址功能。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我觉得对您的需求，我们应该支持网页组件可绑定数据集的字段。所有组件都通过字段与具体数据关联，需要修改网页URL，则可以通过修改数据集对应字段的值来实现。
