### ISSUE TITLE
[Feature]建议编辑仪表板时右侧的面板能悬浮使用

### ISSUE THREAD

**Issue by QQ853695231** [dataease/dataease#5386]
组件编辑功能，右侧弹出的面板能悬浮出来吗？因为这个面板在显示状态下，中间的画布操作区当中的组件会变形。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们暂时不考虑修改这里，在仪表板编辑状态下，组件的编辑窗口使用频率还是挺高的，如果悬浮出来，那么画布中的组件会一直被遮挡。如果需要查看组件的整体显示状态，建议将编辑窗口收缩起来，或者点击预览。
