### ISSUE TITLE
[Bug] api数据源字符校验

### ISSUE THREAD

**Issue by sky84892070** [dataease/dataease#5387]
**DataEase 版本**

v1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
api数据源校验格式不正确
**Bug 重现步骤**
1.在api数据源中使用post http://11.0.0.40:9090/api/v1/query?query=topk(5,cpu_usage_active{busigroup="n9e-monitor"})
实际结果：提示错误，见附件，在postman中都可以正常。
DE添加数据源截图：
![a179cab7cff88cfbc792ce8940f0862](https://github.com/dataease/dataease/assets/94676284/bdbbebaf-fe35-491f-aca0-43d68cc35e3d)

Postman运行api截图
![428fa74489014e4c323a4b865a03e8a](https://github.com/dataease/dataease/assets/94676284/e3499990-198f-4cda-a6f5-202fd64163e1)

期望结果：可以正常使用。

**Comment by BBchicken-9527** [comment]
感谢反馈，嗯...postman是get请求，你在de上用相同的参数post请求....是不是错了呢
