### ISSUE TITLE
[Feature]仪表板的公共链接增加访问IP白名单的功能

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5388]
**请描述您的需求或者改进建议.**
使用场景：
订阅用户较少或使用社区版，不满足通过登录DE访问或授权访问。

创建仪表板的公共链接，每个公共链接，希望可以添加访问的 IP 到白名单，只有在白名单内的IP可以访问这个公共链接。
请评估一下是否可以做这个功能。

**Comment by xuwei-fit2cloud** [comment]
我们在2.x里有相关的支持。
