### ISSUE TITLE
[Feature]仪表板视图支持切换指标

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#5389]
在使用仪表板过程中，需要动态的查看不同的指标结果，目前dataease里面无法切换指标，希望加一个如下拉框的组件，支持视图中的指标切换。
![1](https://github.com/dataease/dataease/assets/26103277/09564513-9c63-4f56-b002-aa34e74a1e31)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下。

**Comment by hw872715125** [comment]
请问怎么样了？有计划实现么

**Comment by yayanpei-fit2cloud** [comment]
我们近期主要精力在2.0的开发，因此没有规划去实现。
