### ISSUE TITLE
[Bug]新建字段使用 last_day 函数报错

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5390]
**DataEase 版本**
1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
 last_day 是 Doris的函数，用于计算一个日期所在月的最后一天；
Excel数据集，新建字段，使用Doris的函数 last_day 会报错
<img width="1067" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/379154b8-c8b0-4550-8111-77f2996e5162">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，这个函数只有doris版本1.2之后才有的，目前你是用1.1是没有这个函数的。
