### ISSUE TITLE
[Feature]tab组件标题和图表间隔太大，是否可以自定义

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5391]
**请描述您的需求或者改进建议.**
<img width="704" alt="wecom-temp-28467-7495052d5c1f86e404f6c39bbf7bfecb" src="https://github.com/dataease/dataease/assets/101089844/c0541686-7cab-48a8-ad61-15e07971cad8">

**Comment by yayanpei-fit2cloud** [comment]
同issue：https://github.com/dataease/dataease/issues/5126

该优化实现起来难度较大，我们还需要更多的时间，再次感谢您的关注和支持。

**Comment by maninhill** [comment]
该问题暂无修复计划，先关闭，望理解。
