### ISSUE TITLE
[Feature]tab组件标题可以隐藏展示

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5394]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/101089844/04294490-4797-4e0a-b322-ac8ad7e0a7fd)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，轮播图已经在需求池中，有计划去支持图片的轮播。tab组件暂时不考虑隐藏标题。
