### ISSUE TITLE
[Feature]连接SQLSERVER数据库支持库名为中文

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5395]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/101089844/af2f9972-e523-45fc-bd11-125995bfb8b3)
![image](https://github.com/dataease/dataease/assets/101089844/9786537f-380d-41bc-82d0-2925e42fbd33)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先调研并讨论一下。中文的库名、表名、字段名如果识别不出来，可能会有乱码的风险，安全起见，还是建议使用英文名。

**Comment by yayanpei-fit2cloud** [comment]
当前没有规划去做支持，issue先进性关闭了，再次感谢您的关注和支持。
