### ISSUE TITLE
[Feature]将将要钻取的下一级字段与上级字段同层展示，希望钻取后各字段顺序不变

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5397]
**请描述您的需求或者改进建议.**

1、钻取前已经将“商品”列展示出来
<img width="851" alt="image" src="https://github.com/dataease/dataease/assets/101089844/dfab9cf4-49dc-407d-9733-c460e2af9c86">

2、钻取后，“销量”从最后跑到前面来了，希望字段顺序不变
<img width="854" alt="image" src="https://github.com/dataease/dataease/assets/101089844/38f273d2-7fef-41ab-87b0-b4e1a4ff92bd">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们在后续版本里处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
