### ISSUE TITLE
[Bug] 创建仪表板用户名称过长时，仪表板页面ui失常

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5398]
**DataEase 版本**
v1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
创建仪表板用户名称过长时，仪表板页面ui失常

**Bug 重现步骤(有截图更好)**
<img width="1150" alt="image" src="https://github.com/dataease/dataease/assets/45852479/e5842eb9-df2e-4b63-8ed2-a816c10cfa86">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快优化

**Comment by xuwei-fit2cloud** [comment]
v1.18.8版本已处理，请更新版本。
