### ISSUE TITLE
[Bug]v1.1.0-rc2 编译backend 报:org.apache.commons.lang不存在

### ISSUE THREAD

**Issue by fengyubiao** [dataease/dataease#540]
**DataEase 版本**
tag v1.1.0-rc2

**Bug 描述**
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project backend: Compilation failure: Compilation failure: 
[ERROR] /data/jenkins_salve_workspaces/workspace/dataease-compile/src/backend/src/main/java/io/dataease/service/CommonFilesService.java:[4,31] 程序包org.apache.commons.lang不存在
[ERROR] /data/jenkins_salve_workspaces/workspace/dataease-compile/src/backend/src/main/java/io/dataease/auth/util/RsaUtil.java:[4,31] 程序包org.apache.commons.lang不存在

**编译日志**
[INFO] ------------------------< io.dataease:backend >-------------------------
[INFO] Building backend 1.1.0                                             [3/3]
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from nexus: https://nexus3.emarbox.com/repository/maven-public/pentaho-kettle/kettle-core/8.3.0.18-1084/kettle-core-8.3.0.18-1084.pom
[WARNING] The POM for pentaho-kettle:kettle-core:jar:8.3.0.18-1084 is missing, no dependency information available
Downloading from nexus: https://nexus3.emarbox.com/repository/maven-public/pentaho-kettle/kettle-engine/8.3.0.18-1084/kettle-engine-8.3.0.18-1084.pom
[WARNING] The POM for pentaho-kettle:kettle-engine:jar:8.3.0.18-1084 is missing, no dependency information available
Downloading from nexus: https://nexus3.emarbox.com/repository/maven-public/pentaho/metastore/8.3.0.18-1084/metastore-8.3.0.18-1084.pom
[WARNING] The POM for pentaho:metastore:jar:8.3.0.18-1084 is missing, no dependency information available
Downloading from nexus: https://nexus3.emarbox.com/repository/maven-public/org/pentaho/di/plugins/pdi-engine-configuration-impl/8.3.0.7-683/pdi-engine-configuration-impl-8.3.0.7-683.pom
[WARNING] The POM for org.pentaho.di.plugins:pdi-engine-configuration-impl:jar:8.3.0.7-683 is missing, no dependency information available
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ backend ---
[INFO] 
[INFO] --- maven-antrun-plugin:1.8:run (main-class-placement) @ backend ---
[INFO] Executing tasks

main:
     [move] Moving 108 files to /data/jenkins_salve_workspaces/workspace/dataease-compile/src/backend/src/main/resources/static
     [move] Moving 2 files to /data/jenkins_salve_workspaces/workspace/dataease-compile/src/backend/src/main/resources/templates
[INFO] Executed tasks
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ backend ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 76 resources
[INFO] Copying 136 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ backend ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 546 source files to /data/jenkins_salve_workspaces/workspace/dataease-compile/src/backend/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /data/jenkins_salve_workspaces/workspace/dataease-compile/src/backend/src/main/java/io/dataease/service/CommonFilesService.java:[4,31] 程序包org.apache.commons.lang不存在
[ERROR] /data/jenkins_salve_workspaces/workspace/dataease-compile/src/backend/src/main/java/io/dataease/auth/util/RsaUtil.java:[4,31] 程序包org.apache.commons.lang不存在
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for dataease 1.1.0:
[INFO] 
[INFO] dataease ........................................... SUCCESS [  0.998 s]
[INFO] frontend ........................................... SUCCESS [06:23 min]
[INFO] backend ............................................ FAILURE [ 27.477 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:53 min
[INFO] Finished at: 2021-08-05T15:10:43+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project backend: Compilation failure: Compilation failure: 
[ERROR] /data/jenkins_salve_workspaces/workspace/dataease-compile/src/backend/src/main/java/io/dataease/service/CommonFilesService.java:[4,31] 程序包org.apache.commons.lang不存在
[ERROR] /data/jenkins_salve_workspaces/workspace/dataease-compile/src/backend/src/main/java/io/dataease/auth/util/RsaUtil.java:[4,31] 程序包org.apache.commons.lang不存在
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :backend
Build step 'Invoke top-level Maven targets' marked build as failure
Finished: FAILURE

**Comment by xuwei-fit2cloud** [comment]
您可以检查一下您的maven settings.xml配置，比如 mirror 设置等，kettle的依赖其实在pom中已经指定了仓库，如果使用了mirror的话，可能会导致依赖包无法下载。可以不用特意指定mirror等额外设置试试，应该是没问题的。

**Comment by fengyubiao** [comment]
> 
> 
> 您可以检查一下您的maven settings.xml配置，比如 mirror 设置等，kettle的依赖其实在pom中已经指定了仓库，如果使用了mirror的话，可能会导致依赖包无法下载。可以不用特意指定mirror等额外设置试试，应该是没问题的。

感谢回复，问题已经解决。
我们这里的编译全部走的私有仓的代理 setting中mirror用的*，代理中添加https://nexus.pentaho.org/content/groups/omni/ 后就可以编译了
