### ISSUE TITLE
数据集增加复制功能[Feature]

### ISSUE THREAD

**Issue by xiexiangg** [dataease/dataease#5400]
**请描述您的需求或者改进建议.**
数据集增加单个复制，或者整个数据集的文件夹复制

**Comment by xiexiangg** [comment]
有些数据集是公用的，因为每个组件的请求是分开的，就导致有大量的数据集可以复制微调进行重复使用

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，您的建议很不错，我们会优先考虑在版本迭代中添加此功能。

**Comment by xuwei-fit2cloud** [comment]
如果要支持数据集的复制的话，也只能支持直连模式的数据集。
在直连模式的数据集中，数据库数据集、Excel数据集、API数据集是不能编辑的，没有复制的意义。
所以暂时还没有相关支持计划。
