### ISSUE TITLE
[Feature]建议样式-配色方案支持用户自定义配色方案

### ISSUE THREAD

**Issue by lyons-hz** [dataease/dataease#5402]
**请描述您的需求或者改进建议.**
在一个仪表板中希望相同类型的视图可以保持统一配色，目前的方案，在一个视图中自定义颜色后，新画的视图并不能直接使用之前配好的配色方案，只能重新设置一遍，比较浪费时间。
希望可以支持用户自定义配色方案并保存，在后续的视图制作过程中，可以直接选用已经配好的方案。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，目前不建议支持配色方案的保存，可能会保存较多的配色方案需要系统、或者用户维护。
如果需要配色方案的复用，同一个仪表板，可以通过仪表板的样式，将视图的配色方案自定义，这样新建的视图会默认使用自定义的配色方案。
