### ISSUE TITLE
[Feature]图表类型为明细表,分页模式为翻页,每页10条时,数据集数据有接近50000条,明细表一直加载中,最后浏览器显示Out of Memory

### ISSUE THREAD

**Issue by hhxiaming** [dataease/dataease#5404]
**请描述您的需求或者改进建议.**
浏览器显示Out of Memory后,服务器都是正常的,刷新后服务也可能正常访问
感觉像是后端没有进行分页查询,而是把所有数据查出来在前端进行分页,导致数据量太大,浏览器就崩了

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，这个是已知问题，如您所述，后端目前没有进行分页，我们暂时还没有合适的方案。如果后端要实现分页，需要先对数据源数据进行排序。
有的数据源是不支持排序的。
有的数据源是可以支持排序的，但如果要实现分页，也需要先对数据源进行排序，在数据量较大的情况下，这个排序过程也是比较耗时的。

如果您这边有好的建议，欢迎随时联系我们，不胜感激。
