### ISSUE TITLE
[Bug]视图过滤功能，无法对指标进行过滤

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5405]
**DataEase 版本**
1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
视图过滤功能，对指标不起作用，如下图，销售额，过滤大于等于100，无法显示数据。
<img width="852" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/8bd1e5c9-58a1-457a-97da-360d8b7ebcf0">

<img width="1074" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/cfa8ea14-72ac-40cb-9832-1ad73f2b50a4">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，因为你是用的是汇总表且数据没有超过或等于一百的数值所以导致没有搜索到的，这主要是因为汇总表将数值自动聚合导致你判断出现了误差，如果使用明细表可能会看的更清晰一些；
