### ISSUE TITLE
[Question] 前端下载依赖后启动报错 You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by liuqingsong1528** [dataease/dataease#5406]
**请描述您的问题.**
![image](https://github.com/dataease/dataease/assets/29009093/9529a605-e29c-4dd3-9aeb-dc0667977eaa)
Module parse failed: Unexpected token (346:22)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file

**Comment by xuwei-fit2cloud** [comment]
您可以检查一下webpack和cli版本，建议版本：
webpack 4  
webpack-cli 3

**Comment by RocketM1** [comment]
你的babel没有正常工作，无法识别可选链语法
可以在node_modules中检查下是否能找到@vue/babel-preset-app这个包
