### ISSUE TITLE
[Feature]antv折线图动画效果在高频刷新时造成了闪动

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5407]
**请描述您的需求或者改进建议.**
折线图用来展示趋势，antv 的折线图、面积图自带动画，如果设置 1 秒刷新一次，动画效果造成了闪动；
希望只刷新数据，没有动画效果，可在 2.x 修改这个效果。

https://github.com/dataease/dataease/assets/48307752/adad3231-ff0b-40c3-a634-ed37d2d36b46

**Comment by xuwei-fit2cloud** [comment]
按下图，把加载动画去掉试试？
![图片](https://github.com/dataease/dataease/assets/1892127/99a78712-5d81-4d8f-8ed8-c8ad0c9079e0)

**Comment by mfanoffice** [comment]
> 
感谢，全局刷新关闭，加载提示也关闭，只开启视图刷新，现象仍然存在：
<img width="405" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/c5129f22-6c10-4802-9515-bb13af8f4ce6">

<img width="785" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/e9a60867-2be2-402d-8675-602de1c52bb2">

**Comment by xuwei-fit2cloud** [comment]
好的，我们在2.x里增加一个视图动画的控制。
