### ISSUE TITLE
[Bug] 定时同步数据集，%Y%m%d格式的时间字段，时间过滤组件均失效

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5408]
**DataEase 版本**
v1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
定时同步数据集，%Y%m%d格式的时间字段，时间过滤组件均失效

**Bug 重现步骤(有截图更好)**
1.原始数据
<img width="980" alt="image" src="https://github.com/dataease/dataease/assets/45852479/43803bb6-b104-4e71-9b01-0fd5d5c59cdf">
2.年月
<img width="978" alt="image" src="https://github.com/dataease/dataease/assets/45852479/4394c4b9-93e3-45bd-8aa2-f24f4d93b506">
3.日期
<img width="955" alt="image" src="https://github.com/dataease/dataease/assets/45852479/a323a1d7-16ee-4a14-b2e0-ed1e05309ca4">
4.年份
<img width="961" alt="image" src="https://github.com/dataease/dataease/assets/45852479/5cba3295-a82c-43c6-93b5-6b62563d26c1">
5.日期范围
<img width="951" alt="image" src="https://github.com/dataease/dataease/assets/45852479/793e39d6-a5a4-460d-8503-d3dee4d25d88">

**Comment by MaekBlack** [comment]
问题点在于str_to_date的时候，时间格式错了
<img width="528" alt="image" src="https://github.com/dataease/dataease/assets/45852479/fb46414a-bdb1-40c6-9712-45e6d43e1db8">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快优化

**Comment by BBchicken-9527** [comment]
问题已修复，可以更新最新版本体验；
