### ISSUE TITLE
[Feature] 文本卡或指标卡新增 数据库趋势显示箭头

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#5409]
**请描述您的需求或者改进建议.**
建议在文本卡或指标卡新增数据库趋势显示箭头，在页面一目了然和数据历史数据做对比（前一天、前一周等），比较直观；
![图片1](https://github.com/dataease/dataease/assets/43403764/f21379ef-7c0d-452e-84f2-d88ba2ffa99a)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，该需求已经在需求池中，我们会规划在2.x版本中实现该功能。
