### ISSUE TITLE
多支持点数据源吧

### ISSUE THREAD

**Issue by ynzzxc** [dataease/dataease#541]
支持的数据源太少，止步于试用。我离线安装的，个人感觉是除metabase以外最友好的。

**Comment by yayanpei** [comment]
非常感谢您的反馈，支持丰富的数据源是Dataease的方向和目标。在8月初的V1.1.0中会增加支持Oracle数据库，计划9月初发布的V1.2.0版本会增加支持 Sql Server数据库、PG数据库、以及API。

**Comment by ynzzxc** [comment]
> 
> 
> 非常感谢您的反馈，支持丰富的数据源是Dataease的方向和目标。在8月初的V1.1.0中会增加支持Oracle数据库，计划9月初发布的V1.2.0版本会增加支持 Sql Server数据库、PG数据库。

那真是太好了！刚看到1.20的版本规划，很棒！

**Comment by FengAiLing2016** [comment]
正需要支持Sql Server数据库

**Comment by annisun2020** [comment]
可以支持hive或者impala数据库吗

**Comment by AloneFire** [comment]
可以支持 csv , json 数据源吗 @yayanpei

**Comment by xuwei-fit2cloud** [comment]
新数据源会持续增加，暂时关闭该issue
