### ISSUE TITLE
[Bug]MySQL 数据源创建时数据库名包含减号-会报错

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5410]
**DataEase 版本**
1.18.7，MySQL 5.7

**运行方式(安装包运行 or 源码运行 ?)**

安装包运行
**浏览器版本**
chrome

**Bug 描述**
mysql 填写数据库名称时，如果名称中包含减号 - 数据源创建会报错
<img width="1441" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/ee079b39-b7f7-49fc-915a-3f4375c3c987">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by hmczju** [comment]
backend/src/main/java/io/dataease/provider/datasource/JdbcProvider.java第784行改一下正则表达式，构建一下就行。希望官方后续对这个正则表达式增加允许减号-

**Comment by BBchicken-9527** [comment]
目前问题已修复，可以下载最新版本体验，感谢你的建议与支持；
