### ISSUE TITLE
[Feature]指标卡数值单位后缀增加字体大小的设置

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5413]
**请描述您的需求或者改进建议.**
如下图，指标卡数值可以增加单位，希望增加单位的大小设置，仪表板制作通常会将单位文字设置较小，目前没有这个功能，只能用富文本实现此功能
![图片](https://github.com/dataease/dataease/assets/48307752/a1c69b50-f085-4c1d-ac24-a04c895a8ebe)
<img width="750" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/1d3eba86-a34c-4bc2-9c86-8c25590b5a9a">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议很不错，我们会优先考虑规划实现。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
