### ISSUE TITLE
[Feature]表格视图中的文本内容可以选中复制

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5414]
**请描述您的需求或者改进建议.**
用户在查看仪表板时，可以对表格中的文本内容复制，粘贴到其他系统中。
<img width="479" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/e1212d5e-6e64-4e97-bfee-c5ce7d5f3db6">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，该需求现阶段没有支持的计划。
