### ISSUE TITLE
[Bug]创建定时报告选择仪表板时，最上面的仪表板列表会被遮挡

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#5415]
**DataEase 版本**
v1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 最高版

**Bug 描述**
如下图所示，最上面的仪表板被报告正文的富文本框盖住了，即使滚动条拉到最上方也看不到上面的仪表板。
![image](https://github.com/dataease/dataease/assets/48945409/99d81a12-091f-4bf0-98e8-cd411a8d65f3)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们修复一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.8版本已处理，请更新版本。
