### ISSUE TITLE
[Bug]标签提示遮挡

### ISSUE THREAD

**Issue by 17600120049** [dataease/dataease#5417]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
图标中的标签值会被遮挡
![1686033668713](https://github.com/dataease/dataease/assets/102302189/a6cd1e50-035c-44c1-ba77-782ef7300f40)

**Bug 重现步骤(有截图更好)**
1.
![1686033668713](https://github.com/dataease/dataease/assets/102302189/310cf6d0-fa73-4da3-9e58-a61805975ef7)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，你是用的应该是AntV图库的视图吧，目前视图内可操作空间有限我们也在想办法处理，但是还没有找到最优解，你可以暂时用Echarts图库当作替代；
