### ISSUE TITLE
[Bug] 下拉过滤组件数据源超时，数据量大的数据需要下拉条件时会超时

### ISSUE THREAD

**Issue by a1056094641** [dataease/dataease#5420]
**DataEase 版本**
1.18.6 精简模式

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述 **
直连明细表数据量上千万时，加入下拉框条件筛选，下拉框数据源必须选择组件数据源筛选或者，明细表源数据筛选，导致下拉框数据超时加载

正常需求应当是下拉框选择字典表来进行加载数据而非以表格数据筛选下拉框数据

**Bug 重现步骤(有截图更好)**
1. 大数据量明细表
2. 加入下拉框，选择数据源

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是说再千万级别的数据量进行组件过滤时，备选项timeout是嘛？请问有问题的数据过滤使用的字段去重之后有多少呢？

**Comment by a1056094641** [comment]
是的&nbsp;


测试你的爱情命运，速配你的理想伴侣てもおい


&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2023年6月7日(星期三) 下午2:08
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [dataease/dataease] [Bug] 下拉过滤组件数据源超时，数据量大的数据需要下拉条件时会超时 (Issue #5420)





 
感谢反馈，你的意思是说再千万级别的数据量进行组件过滤时，备选项timeout是嘛？

**Comment by BBchicken-9527** [comment]
请问你一千万条数据去重之后大搞会剩下多少数据量呢？下拉组件的备选项是查库拿到的，所以如果timeout的情况下可以在数据源处设置超时时间，加大查询时间可能会对你起到帮助，你可以试一下；
