### ISSUE TITLE
[Bug] 视图计算字段保存异常，查看请求参数后发现部分字段未转换成主键。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5421]
**DataEase 版本**
v1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 113.0.5672.126（正式版本） (arm64)

**Bug 描述**
视图计算字段保存异常，查看请求参数后发现部分字段未转换成主键。

**Bug 重现步骤(有截图更好)**
1.SQL 数据集如图所示：
![image](https://github.com/dataease/dataease/assets/30063018/13fc816a-f623-4a17-bb22-f88e3de700b8)
2.添加指标卡视图，创建如图所示计算字段，报错字段表达式语法错误，查看请求参数后发现部分字段未转换成字段id
![image](https://github.com/dataease/dataease/assets/30063018/74622e09-6cfe-4095-815f-9742a749a10b)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.8版本已处理，请更新版本。
