### ISSUE TITLE
[Feature] 数据集行列权限设置

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#5426]
**请描述您的需求或者改进建议.**
1、目前行权限、列权限只能针对单个数据集设置权限，是否会支持可以对一个数据源当中多个数据集的一个或多个相同字段统一设置行权限和列权限，目前看只能添加多条实现。

2、公共链接的方式不走权限规则，是否可以禁用创建公共链接；

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复请见如下：
1、目前行列权限是基于单个数据集进行权限设置，当前阶段没有计划去改变设计，支持多数据集统一设置。
2、公共链接的禁用，请问是出于什么考虑？数据安全吗？如果是考虑到数据安全，避免在系统外的传播使用，建议您打开仪表板水印，这样不论是截屏使用，或者创建公共链接，都可以进行追踪。
