### ISSUE TITLE
[Feature]鼠标放在地图上黄颜色希望能修改

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5428]
**请描述您的需求或者改进建议.**
下图鼠标放在地图上黄颜色希望能修改；因为黄色可能会有颜色不搭的情况。
<img width="468" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/9303341e-70e9-4b61-b5d0-b438a5aff312">

**Comment by xuwei-fit2cloud** [comment]
您好，短期内我们还不会对此需求做相关支持。
