### ISSUE TITLE
[Bug]V1.18.7CORS原始验证失败

### ISSUE THREAD

**Issue by shyepeng** [dataease/dataease#5429]
**DataEase 版本**
V1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome114.0.5735.110

**Bug 描述**
深信服漏扫发现，CORS原始验证失败

**Bug 重现步骤(有截图更好)**
![微信图片_20230609111311](https://github.com/dataease/dataease/assets/136044162/ad35da61-c233-4aa9-822c-9f445960d868)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们确认一下
