### ISSUE TITLE
[Bug] Local 模式部署，上传 CSV 文件作为数据集，在字段非常多的情况下显示上传成功，查看数据集预览，无数据显示。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5432]
**DataEase 版本**
v1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 113.0.5672.126（正式版本） (arm64)

**Bug 描述**
 Local 模式部署，上传 CSV 文件作为数据集，在字段非常多的情况下显示上传成功，查看数据集预览，无数据显示。

**Bug 重现步骤(有截图更好)**
1.  测试 csv 数据如下，一共700+列，点击可进行下载：http://democenter.fit2cloud.com:40780/testDataForDE.csv
![image](https://github.com/dataease/dataease/assets/30063018/14787a57-6f08-4d52-bc1f-d81aefa44ffb)
2. 上传 csv 文件，预览正常。
![image](https://github.com/dataease/dataease/assets/30063018/3d853ac5-49c8-4368-9a44-babe3479491c)
3. 更新记录显示成功，但数据预览无数据。
![image](https://github.com/dataease/dataease/assets/30063018/983e5f76-55f1-4d52-93e4-c284011aa418)
![image](https://github.com/dataease/dataease/assets/30063018/b0b70c0f-70aa-426b-8417-d7a684a07cc3)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复；
