### ISSUE TITLE
[Feature]仪表板导出PDF比较模糊

### ISSUE THREAD

**Issue by lyons-hz** [dataease/dataease#5433]
**请描述您的需求或者改进建议.**
1.18.6，仪表板导出成PDF，未放大的情况下也比较模糊，建议优化一下
<img width="1332" alt="image" src="https://github.com/dataease/dataease/assets/89773363/f510fda9-1bac-4229-a598-a5ec15446c6f">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们这边也试了，现在导出的质量还是不错的，建议您用无痕或者换台设备试试。
