### ISSUE TITLE
[Feature]指标默认值

### ISSUE THREAD

**Issue by world926** [dataease/dataease#5434]
数据集中若尚为出现数据则在求和后为null值；例使用指标过滤器过滤`状态`等于4，然后求和指标`数量`，显示为null。
这里的显示单元希望能够进行配置默认值。
![60d4ff3e48f96fc883722a93e1ae6c7](https://github.com/dataease/dataease/assets/47386463/f934dde7-c7c8-45fe-8cf7-632b3dd05636)
![97a1409c7a1dfd17a0e6ccc865f9c1b](https://github.com/dataease/dataease/assets/47386463/ccf50473-2add-40bf-87be-eee94a9f58da)

**Comment by xuwei-fit2cloud** [comment]
需求收到，我们先讨论一下，是否支持指标卡的空值处理。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，这里所有图表类型均保持一致，过滤后如果为null，那么显示真实的过滤结果，不再进行特殊处理。
