### ISSUE TITLE
[Feature]建议在复用界面当复选框重叠时能够并排显示，避免遮挡

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5435]
**请描述您的需求或者改进建议.**
如图，在复用其他仪表板的视图时，当两个视图重叠，会出现复选框重叠问题，此时无法选中后方的复选框，也就无法复用。
希望复选框能够避免重叠，当重叠时能够并排显示。
![image](https://github.com/dataease/dataease/assets/30886198/6ed63271-0082-49c3-a2ab-876061f9eaf4)

**Comment by yayanpei-fit2cloud** [comment]
目前1.x的仪表板支持悬浮模式，所以会出现上下层级组件重叠的情况，如果无法选择下层组件，建议您在仪表板中新增，不要采用复用的形式。

在2.x中我们已考虑到这个情况并优化了此处的设计。1.x中目前没有规划优化此处，一是不影响复用常规的视图，二是这一块的设计要重新修改，代价较大。

再次感谢您的反馈和支持。

**Comment by liuboF2c** [comment]
比如想复用模板中的图片，新增的话我需要先把图片导出来，再重新上传。复用则非常方便。期待 2.0 的发布~

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的关注和支持，issue先进行关闭了。
