### ISSUE TITLE
[Feature]数据分界怎么显示到镇街这一级别？

### ISSUE THREAD

**Issue by tsl9906202** [dataease/dataease#5436]
**请描述您的需求或者改进建议.**
现在有些统计需要地图到街道这个级别，但是目前地图只能到区一级

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈和支持，目前系统中的地图统计支持到省市区，没有支持到街道这个粒度，我们先记录到需求池中并调研一下，近阶段还没有规划进行支持。

**Comment by tsl9906202** [comment]
现在有大量智慧城市这一块业务，城市治理需要基层镇街治理的数据统计，需求还是挺大的

**Comment by yayanpei-fit2cloud** [comment]
系统当前采用的是离线的高德底图，高德现在是仅支持到区县级别的，如果要更换，改动还是比较大的，我们需要更多的调研，寻找合适的方案。
