### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#5438]
**DataEase 版本**
V 1.18.7

**运行方式(安装包运行 or 源码运行 ?)**

安装包部署
**浏览器版本**
版本 114.0.5735.110（正式版本） （64 位）

**Bug 描述**
新建计算字段，计算(A-B)/A时，遇到B字段值为空值时，计算结果直接为空值。正常情况下B为空值，计算结果应该为1，不应该为空值。

**Bug 重现步骤(有截图更好)**
<img width="441" alt="1e95e2c3d612030b35a0d48047fe024" src="https://github.com/dataease/dataease/assets/127368807/680fb652-0b51-4268-a6a5-ba0d5ee09adc">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
由于这个空值处理和其他视图的空值处理不太一样，需要在后端进行相关处理，目前建议您可以通过计算字段来对空值进行判断及处理。
