### ISSUE TITLE
[Bug]新建用户时的UI问题

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#544]
**DataEase 版本**
v1.1.0

**浏览器版本**
chrome:92.0.4515.107

**Bug 描述**
新建用户时，先角色（不选中）、后选择组织（有多级），角色的空间菜单没有自动消失，并且上浮在组织菜单之上，导致无法选择具体组织。

**Bug 重现步骤(有截图更好)**
1、先点击角色，出现Context Menu,但不选中
2、再选择组织，角色Context Menu没有消失，且无法选中具体组织【正常的逻辑，此时其它的Context Menu应该消失】

<img width="1438" alt="WechatIMG333" src="https://user-images.githubusercontent.com/46042812/128374758-7854abd2-b603-4962-9f31-6a6fec237634.png">

**Comment by xuwei-fit2cloud** [comment]
感谢您的反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.1.1 已处理
