### ISSUE TITLE
普通用户通过未授权接口漏洞删除应用[Bug]

### ISSUE THREAD

**Issue by hbdxmz** [dataease/dataease#5442]
**DataEase 版本**
最新版

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
由于应用删除接口没有做鉴权，普通用户通过未授权接口漏洞可以删除应用

**Bug 重现步骤(有截图更好)**
1.管理员有”应用“这个功能项
<img width="743" alt="管理员有应用这个功能项" src="https://github.com/dataease/dataease/assets/94107024/68ca18e3-c666-4f3c-9ac1-0bf17468e83c">

在系统管理功能中，管理员可以上传应用
![image](https://github.com/dataease/dataease/assets/94107024/81ea964e-18d2-4260-8330-a7981f4e2faf)

2.普通用户没有”应用“这个功能项
<img width="891" alt="普通用户没有应用这个功能项" src="https://github.com/dataease/dataease/assets/94107024/d873daef-6309-4e4b-8bfc-f0298053292c">

3.\backend\src\main\java\io\dataease\controller\panel\PanelAppTemplateController.java中有一个删除应用接口/delete/{appTemplateId}，接口未作鉴权
![image](https://github.com/dataease/dataease/assets/94107024/faf45572-85e0-4c10-91f5-48722ee4bbc5)

4、使用管理员登录，当前存在的应用如下
<img width="718" alt="当前存在的应用" src="https://github.com/dataease/dataease/assets/94107024/6b9d193a-cee0-45e9-8adc-f0c2c5315150">

5、使用普通用户登录，调用/delete/{appTemplateId}传入应用id
<img width="880" alt="删除" src="https://github.com/dataease/dataease/assets/94107024/8492e6f6-e918-441a-bd65-c7104871304c">

6、使用管理员登录，之前存在的应用已被普通用户删除
<img width="745" alt="当前存在的应用被删除" src="https://github.com/dataease/dataease/assets/94107024/0aad07f9-2f26-40af-a20d-1e45527b5d65">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.8版本已处理，请更新版本。
