### ISSUE TITLE
存在权限绕过漏洞，普通用户可以获取包括管理员在内所有用户的密码md5、用户名、邮箱、手机号等敏感信息[Bug]

### ISSUE THREAD

**Issue by hbdxmz** [dataease/dataease#5446]
**DataEase 版本**
最新版

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
存在权限绕过漏洞，普通用户可以获取包括管理员在内所有用户的密码md5、用户名、邮箱、手机号等敏感信息

**Bug 重现步骤(有截图更好)**

1、使用demo账号登录，调用接口api/user/userGrid/1，传入数据集id 1，提示未授权
![image](https://github.com/dataease/dataease/assets/94107024/7cf4e10a-dea5-49d4-a37a-d830b3481d2c)

2.接口代码位置
\backend\src\main\java\io\dataease\controller\sys\SysUserController.java
![image](https://github.com/dataease/dataease/assets/94107024/c63bc8ea-b12b-4b2b-abfd-5e8ba84555c3)

3.aop注解限制level级别为3，用户的level级别大于等于3才能访问
![image](https://github.com/dataease/dataease/assets/94107024/e1325e2e-fa98-4743-ab09-28a69e10133e)

4、使用demo用户去调用这个接口，在\dataease-1.18\backend\src\main\java\io\dataease\auth\aop\DePermissionAnnotationHandler.java中会调用AuthUtils.permissionByType(type）返回当前用户对应的level级别可以调用的数据集，
![image](https://github.com/dataease/dataease/assets/94107024/46c113a8-4b00-4a68-8fe9-f5c7c4d9b20e)
demo用户的级别为1，调用不了level3 的接口，所以调用api/user/userGrid/1提示未授权
![image](https://github.com/dataease/dataease/assets/94107024/8c77248c-d21d-4c57-a750-11c7635e0bb2)

5、但是在最后返回的时候自动增加了一个level为3，值为0的数据集
![image](https://github.com/dataease/dataease/assets/94107024/1912fb94-eb7c-4378-bedf-c9827678dbd2)

6、
![image](https://github.com/dataease/dataease/assets/94107024/6f9aa8a7-4d4d-4889-9710-a7c91ded1851)

7、此时requireLevel是3，会提取出level大于等于3的数据集，判断请求过来的/userGrid/{datasetId} 的datasetId在不在level大于等于3的数据集中，而经过校验返回的数据集中刚好存在level为3，值为0的数据集
![image](https://github.com/dataease/dataease/assets/94107024/0ee1357c-1e1c-4b5e-b5fc-6536ff58da04)

8、于是通过/api/user/userGrid/0可以实现权限绕过，以https://dataease.fit2cloud.com/#/wizard/index 为例，使用demo账号登录，调用接口/api/user/userGrid/0，返回了包括管理员在内所有用户的密码md5、用户名、邮箱、手机号等敏感信息
![image](https://github.com/dataease/dataease/assets/94107024/d21b3565-c6e9-4a45-abc2-cb7ef18f10cc)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by fit2cloud-chenyw** [comment]
1、首先这是个测试api现在已经移除
2、另一方面 为什么要增加一个level为3值为0的数据集？
      因为在新增数据集的时候 需要校验用户是否有数据集目录的权限 也就是对pid是否有权限
      当新增数据集在根目录时 pid为0 所以如果不增加这个默认根目录权限 会导致用户无法在根目录新建资源 数据源仪表板也
      是如此

**Comment by xuwei-fit2cloud** [comment]
v1.18.8版本已处理，请更新版本。
