### ISSUE TITLE
[Bug] 对称柱状图，副轴值数值格式无法设置，点击无弹窗

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5448]
**DataEase 版本**
v1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 113.0.5672.126（正式版本） (arm64)

**Bug 描述**
对称柱状图，副轴值数值格式无法设置，点击无弹窗。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
目前问题已修复，可以下载最新版本体验，感谢你的建议与支持；
