### ISSUE TITLE
权限绕过漏洞，普通用户可以操作管理员创建的仪表板，或者自己创建仪表板目录[Bug]

### ISSUE THREAD

**Issue by hbdxmz** [dataease/dataease#5450]
**DataEase 版本**
最新版

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
普通用户可以修改管理员创建的仪表板目录
普通用户可以创建仪表板目录
普通用户可以修改仪表板名称

**Bug 重现步骤(有截图更好)**

1）普通用户可以修改管理员创建的仪表板目录
1.登录管理员对仪表板目录进行重命名
<img width="935" alt="登录管理员对仪表板目录进行重命名" src="https://github.com/dataease/dataease/assets/94107024/b5748da0-b1d2-434a-be2e-21b5a882c1b9">

2.实例用户demo没有修改仪表板目录的权限
<img width="889" alt="实例用户demo没有修改仪表板目录的权限" src="https://github.com/dataease/dataease/assets/94107024/4c8575cb-84fc-44bf-b6ae-73a3999eb1d8">

3.代码位置：
https://github.com/dataease/dataease/blob/dev/backend/src/main/java/io/dataease/controller/panel/PanelGroupController.java
中的@PostMapping("/update")
![image](https://github.com/dataease/dataease/assets/94107024/83ed4e09-5d77-4015-b785-54d961161a27)

4、查看管理员对仪表板目录进行重命名的请求，传入为id，根据@PostMapping("/update")上面的aop注解可知，操作id数据只需要默认level 1
<img width="670" alt="level默认值为1" src="https://github.com/dataease/dataease/assets/94107024/de0ae28c-e33d-45a9-80db-956848b423d8">

5、于是使用level为1的demo用户调用@PostMapping("/update")，也可以修改仪表板目录，如果任意用户都可以修改，整个系统就会变得没有规范，乱套了
![image](https://github.com/dataease/dataease/assets/94107024/83125038-59b6-4824-88a1-497b514fcd36)

2）普通用户可以创建仪表板目录
1、登录管理员创建仪表板目录
![image](https://github.com/dataease/dataease/assets/94107024/74041b5a-9228-4b0d-8afb-bcd47c4fe103)

2、调用了接口/panel/group/save，代码位置backend\src\main\java\io\dataease\controller\panel\PanelGroupController.java，根据aop注解，操作pid时，用户level为5才能调用接口/panel/group/save创建仪表板目录
![image](https://github.com/dataease/dataease/assets/94107024/ee201fc9-cc35-4788-aa44-9f7843f99f93)

3、查看aop的校验，AuthUtils.permissionByType(type)中会取出level大于等于5的panel，但是最后会自动增加一个level为5，值为panel_list的pid
![image](https://github.com/dataease/dataease/assets/94107024/8eb49cae-99a7-43d7-bdab-27a2ac984269)

4、于是使用level为1的demo用户去调用接口/panel/group/save仪表板目录，请求中包含"pid":"panel_list"，即可绕过权限校验去创建仪表板目录
![image](https://github.com/dataease/dataease/assets/94107024/8789b746-3377-4a8d-b939-8cea87332600)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by fit2cloud-chenyw** [comment]
第一个问题 我们会在下版提升对ID的权限级别为3
第二个问题 任何人能够创建仪表板目录是符合预期的

**Comment by xuwei-fit2cloud** [comment]
v1.18.8版本已处理，请更新版本。
