### ISSUE TITLE
[Feature]过滤组件，多个数据集里面字段名称一样，增加字段显示内容，标记数据集或者组件名称

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#5457]
**请描述您的需求或者改进建议.**
过滤组件，多个数据集里面字段名称一样，无法区别是哪几个数据集字段已拖入，可以增加字段显示内容，标记数据集或者组件名称
<img width="924" alt="image" src="https://github.com/dataease/dataease/assets/70566485/4d6cb841-6b57-4e5f-baf2-b06b6e09f23d">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，2.0我们已经重新设计过滤组件，在交互上进行了优化。1.x如果要优化，可能需要重新设计此处的交互，我们还需要评估一下。

**Comment by xuwei-fit2cloud** [comment]
增加了鼠标悬浮的提示。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
