### ISSUE TITLE
[Feature]指标卡、文本卡视图备注是否可以考虑不跟标题绑定

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#5458]
**请描述您的需求或者改进建议.**
1、指标卡使用时，不使用标题，展示的是名称或者是值内容，这种情况下想增加备注说明，无法做到
2、备注在全屏预览中无法展示，是否能够解决呢？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，现回复如下：
1、备注是指标题的备注，因此如果标题不展示，备注也是无法展示的。
2、备注在全屏中无法展示，这个我们看看修复一下。

> 1、指标卡使用时，不使用标题，展示的是名称或者是值内容，这种情况下想增加备注说明，无法做到
2、备注在全屏预览中无法展示，是否能够解决呢？

**Comment by xuwei-fit2cloud** [comment]
1.18.x版本中暂不支持。
