### ISSUE TITLE
[Feature]移动端增加组件的基础配置、展示效果

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#5459]
**请描述您的需求或者改进建议.**
1、是否展示视图的背景
2、可以修改视图对应的字体大小
3、支持悬浮模式
4、增加隐藏功能，针对于移动端跟PC端的组件进行区别处理（如果上面三个可以解决，可以不考虑），不然如果增加组件藏在现有组件后面，修改的时候比较复杂，可能会影响已有布局后才能进行组件修改
当前如果加了背景，如果想要移动端效果好的话，需要增加额外组件，藏在现有组件后面，或者新增一个仪表板制作移动端，不太友好

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复请见如下：

1、视图背景展示，移动端与pc端统一设置，即pc端展示背景，移动端模式也展示背景。
2、视图字体的大小，根据移动端的情况，后期我们会有默认的字体大小，比如大、中、小，可以切换。
3、悬浮模式，现阶段没有计划去支持。
4、隐藏功能，当前是支持的，当仪表板切换至pc端时，如果组件不需要在移动端展示，不要勾选即可。
> 1、是否展示视图的背景。
2、可以修改视图对应的字体大小。
3、支持悬浮模式。
4、增加隐藏功能。

**Comment by xiebei-l** [comment]
针对反馈回复如下：
1、背景效果展示并不好，但是PC端背景展示是没有问题的，建议支持视图背景是否进行展示，或者替换，能够更好的适配移动端的展示效果
2、无问题，如果支持大、中、小字体应该可以满足移动端字体大小展示
3、PC端其实有用悬浮模式下叠加视图做较好的展示效果，移动端不支持，会导致移动端效果不好，建议考虑悬浮，或者通过其它实现同等效果
4、隐藏功能支持的是移动端，希望PC端也可以支持，因为为了让移动端效果展示的更好，不能使用有背景的视图会同步增加一个视图，或者调整字体大小增加一个视图，实际需要调整是无法找到对应的视图，因为被藏在视图的后面，所以建议PC端可以增加隐藏组件功能，可以跟移动端隐藏功能互不影响

> 感谢您的反馈，回复请见如下：
> 
> 1、视图背景展示，移动端与pc端统一设置，即pc端展示背景，移动端模式也展示背景。 2、视图字体的大小，根据移动端的情况，后期我们会有默认的字体大小，比如大、中、小，可以切换。 3、悬浮模式，现阶段没有计划去支持。 4、隐藏功能，当前是支持的，当仪表板切换至pc端时，如果组件不需要在移动端展示，不要勾选即可。
> 
> > 1、是否展示视图的背景。
> > 2、可以修改视图对应的字体大小。
> > 3、支持悬浮模式。
> > 4、增加隐藏功能。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的建议，我们会综合考虑后优化移动端的展示。

**Comment by xuwei-fit2cloud** [comment]
v1.18.x版本暂不支持。
