### ISSUE TITLE
[Bug]仪表板右边边框预留位置与实际预留位置不一致，组件需放置到最边边才能预留合适位置

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#5461]
**DataEase 版本**
1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
仪表板右边边框预留位置与实际预留位置不一致，组件需放置到最边边才能预留合适位置
第一张图片编辑状态
第二张图片预览状态

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/70566485/131e8905-e262-4ddd-8ca7-d1c2c774c223)
![image](https://github.com/dataease/dataease/assets/70566485/82619f03-0bf5-4ef2-b0f4-3e8b5bd7d51e)

**Comment by BBchicken-9527** [comment]
感谢反馈，这里预留的位置主要是为了和左侧操作栏做区分，如果取消预留的空间可能会导致视图边缘和导航栏过于贴合；
