### ISSUE TITLE
[Bug] ES数据源模糊查询BUG

### ISSUE THREAD

**Issue by tktkl** [dataease/dataease#5463]
**DataEase 版本**
V1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome 版本 114.0.5735.106（正式版本） (x86_64)

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/35550859/adcddeb1-d2a9-4ef5-b82b-297ee30db733)
`{
    "success": false,
    "message": "io.dataease.exception.DataEaseException: io.dataease.exception.DataEaseException: java.lang.RuntimeException: HttpClient查询失败: {\"error\":{\"root_cause\":[{\"type\":\"verification_exception\",\"reason\":\"Found 1 problem\\nline 15:10: Unknown function [upper], did you mean [USER]?\"}],\"type\":\"verification_exception\",\"reason\":\"Found 1 problem\\nline 15:10: Unknown function [upper], did you mean [USER]?\"},\"status\":400}",
    "data": null
}`

**Bug 重现步骤(有截图更好)**
1. ES数据源模糊查询即可
2. io.dataease.provider.query.es.EsQueryProvider#transExtFilterList 
3.修改1124行即可处理
![image](https://github.com/dataease/dataease/assets/35550859/dbbfc766-c7f2-4c5d-a06f-0e4ad8759f90)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
