### ISSUE TITLE
[Feature]时间插件修改字体大小

### ISSUE THREAD

**Issue by baoshan2020** [dataease/dataease#5465]
时间、input等插件修改字体大小
![4099354a669acf9bf1923adc4149413713a4ad79](https://github.com/dataease/dataease/assets/61979600/e4e50fca-9087-41c0-9a43-eb85900e7039)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们计划在2.x版本中进行支持。

**Comment by baoshan2020** [comment]
非常感谢！问问2.X预计什么时候发布

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的关注和支持。

2.0计划是在今年下半年发布，发布后按月进行版本迭代。
