### ISSUE TITLE
[Feature]数据范围组件数值大小

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#5468]
**请描述您的需求或者改进建议.**
数据范围组件，int范围限制，最大 2*32 -1，有办法改成long范围。

**Comment by yayanpei-fit2cloud** [comment]
同issue：https://github.com/dataease/dataease/issues/5453

我们需要讨论一下。

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #5453

**Comment by xuwei-fit2cloud** [comment]
v1.18.8版本已处理，请更新版本。
