### ISSUE TITLE
[Bug] 文本组件自适应问题

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#5471]
**DataEase 版本**
1.18.7

**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**
谷歌

**Bug 描述**
tal 组件上的 文本组件，在调大字体后，进入全屏预览模式，字体变成没调之前

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/7127ef6b-2029-4fff-a735-f93617c1595f)

2.
![image](https://github.com/dataease/dataease/assets/109720729/904a7d0c-63cd-410f-8f6f-cab946e15056)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.8版本已处理，请更新版本。
