### ISSUE TITLE
[Feature]视图中数据排序能够根据非指标和维度字段排序

### ISSUE THREAD

**Issue by lhy881126** [dataease/dataease#5472]
使用过程中有的数据是有专门的排序字段，在视图中展示时数据需要根据专门的排序字段展示，但排序字段不需要在视图中展示。
视图中是否能够增加一个专门配置排序字段的地方，能够自定义排序字段，并定义排序方式，展示时根据排序字段排序后展示

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，需求已经在需求池中，我们计划在2.x中添加该功能。
