### ISSUE TITLE
数据源添加功能存在SSRF漏洞[Bug]

### ISSUE THREAD

**Issue by hbdxmz** [dataease/dataease#5473]
**DataEase 版本**
最新版

**Bug 描述**
数据源添加功能，未对远程服务器地址进行合法性检验，攻击者可以向与dataease相通但互联网不可访问的内网地址、云环境发起请求（SSRF漏洞：服务器端请求伪造），可以进一步获取内网服务信息、云环境中元数据等敏感信息

**Bug 重现步骤(有截图更好)**
1.数据源配置功能中，添加一个api地址，这里设置api地址为阿里云元数据项地址，点击下一步，返回了元数据项
![image](https://github.com/dataease/dataease/assets/94107024/f6051094-7e9f-474a-948e-bb83fa89e714)

2.由于没有对数据源地址做限制，造成了ssrf漏洞，建议对用户可编辑的数据源地址做合法性校验
![image](https://github.com/dataease/dataease/assets/94107024/6912fc38-0f8e-4478-8c8f-8c7d6b21cca0)

**Comment by maninhill** [comment]
感谢反馈，我们尽快修复。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们无法对访问的目标进行限制；
