### ISSUE TITLE
[Feature]【视图】横轴标签旋转点优化

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5479]
**请描述您的需求或者改进建议.**
当前横轴标签的以文本中心为旋转点，可否改成以文本尾部作为旋转点！
![image](https://github.com/dataease/dataease/assets/24768910/d27421bc-0b46-4d3a-a0a0-532b8336d5f2)
另外也可以增加一个长度限制，超过多少长度就省略，参考如下图：
<img width="716" alt="image" src="https://github.com/dataease/dataease/assets/24768910/4177cde1-8fcb-4b92-b91a-f981c49ebf8b">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议很不错，我们需要先看一下当前的图库是否支持。
