### ISSUE TITLE
[Feature] 移动端布局组件支持重叠

### ISSUE THREAD

**Issue by limin-fit2** [dataease/dataease#5482]
**请描述您的需求或者改进建议.**
移动端 组件不支持重叠
![image](https://github.com/dataease/dataease/assets/61964761/ce60da59-58fc-4443-90c6-2f5ec258276a)
![image](https://github.com/dataease/dataease/assets/61964761/66ca3149-3f8a-4c9e-9f17-841852efa790)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，移动端是不支持组件的悬浮，近期没有规划去支持，建议您更换仪表板移动端背景图片。
