### ISSUE TITLE
[Feature] 新增过滤组件（下拉框键值对类型）和全局自定义变量

### ISSUE THREAD

**Issue by AnemoneIndicum** [dataease/dataease#5484]
背景：
      目前过滤组件中下拉文本框只支持文本类型，然而在实际开发中很键值对枚举类型的数据是非常常见且基本的，例如：编码<=>与中文描述。这就导致针对一些表结果存储的是 “编码”时而下拉框没有对应的中文选项；为了能显示中文而又不得不在 sql中去关联对应的维度表，导致查询性能损失和sql复杂度增加。
建议1：
     希望官方能支持一个kv类型的下拉框组件，最好此组件能够支持 a:从一个sql数据集获取 kv数据 b:从全局自定义变量获取kv数据
建议2：
     希望官方能支持自定义全局参数：比如枚举值、自定变量等；此类数据支持在 sql数据集中引用，支持在筛选过滤组件中引用。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要讨论一下。

**Comment by AnemoneIndicum** [comment]
期待支持！

**Comment by xuwei-fit2cloud** [comment]
已加入2.x开发计划。

**Comment by AnemoneIndicum** [comment]
之前贵公司销售反馈说是 DataEase 会进行一次大版本升级架构调整，新的调整会跟随2.0版本发布吗？整体的2.0版本预计在什么时候发版？

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您对产品的关注和支持。

2.0 规划是在今年下半年进行发布，架构以及 UI 都进行了重构和优化，上述的需求会在2.x 中规划，具体规划在2.x的哪个版本中，我们还需要根据需求的紧急性以及优先级进一步安排。
