### ISSUE TITLE
[Bug] 数据集选sql数据集，在sql编辑框中sql的注释效果不正确

### ISSUE THREAD

**Issue by taiyangzhige** [dataease/dataease#5485]
**DataEase 版本**
18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
数据集选sql数据集，在sql编辑框中sql的注释效果不正确，当行首输入**“--”（不带空格时）**，该行sql显示被注释，但实际查询结果将“--字段”作为一个新字段查询显示，而当**_行首输入“-- ”（带空格时）_**，该行sql显示被注释，此时查询结果显示如预期。

**Bug 重现步骤(有截图更好)**
1. 当行首输入**“--”（不带空格时）**，该行sql显示被注释，但实际查询结果将“--字段”作为一个新字段查询显示
![de1](https://github.com/dataease/dataease/assets/934199/e0216781-9967-4937-ac17-b2e6102e396e)

2. 当**行首输入“-- ”（带空格时）**，该行sql显示被注释，此时查询结果显示如预期
![de2](https://github.com/dataease/dataease/assets/934199/c7a9283c-614c-4c44-b1bd-23e908d5354f)

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是说--不加空格会被识别成字段是吗？

**Comment by taiyangzhige** [comment]
有两个主要的问题：
1. --不加空格的情况，在sql编辑器里该行已显示为绿色（即被注释的效果），但实际没有被注释，而是被识别为新的查询字段；
2. 如果--不加空格不是注释，或者说是非法语法，则建议不能显示为绿色效果，并明确提示语法错误则比较好（比如Navicat工具，如果--不带空格，会识别为语法错误）。

**Comment by BBchicken-9527** [comment]
是的，不加空格是不符合mysql的注释语法的，你提的建议我们这边会开会讨论一下，感谢你的反馈，如果没什么问题那我就先关闭了；
