### ISSUE TITLE
[Feature] 关于鼠标悬浮提示内容排序的一点优化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5486]
**请描述您的需求或者改进建议.**
视图鼠标悬浮时显示的提示可以根据数值大小进行排序，目前默认是根据图例顺序排序的，查看起来不是非常清晰。
![image](https://github.com/dataease/dataease/assets/30063018/c0093a74-5d99-4218-bf7c-d8348e4acb8b)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，提示信息我们这边优化一下，悬停到折线图上的某一个数据点时，只提示这一个数据点的值。

**Comment by xuwei-fit2cloud** [comment]
暂时没有支持计划。
