### ISSUE TITLE
[Feature] 轴值最大值自动情况下可以调大一点上限，目前轴值自动情况下部分标签会被遮挡。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5487]
**请描述您的需求或者改进建议.**
轴值最大值自动情况下可以调大一点上限，目前轴值自动情况下部分标签会被遮挡。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，轴值最大值自动情况下，是由图库自动返回的，调大上限，根据什么规则调，调多少这些都不固定，我们需要先讨论一下。
