### ISSUE TITLE
[Feature] 关于仪表板、数据集等加载时候的蒙板范围优化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5488]
**请描述您的需求或者改进建议.**
目前在点击仪表板或者数据集预览时会给整个平台盖上蒙板，在数据加载的时候无法做任何操作，也无法中止（除非刷新整个页面），能够蒙板不要覆盖菜单？只盖住右侧的操作区域。
![image](https://github.com/dataease/dataease/assets/30063018/8e410515-2462-475c-9017-d29cd36728a1)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，左侧的仪表板列表如果不覆盖，则可能出现一个仪表板没有加载完毕，又连续点击其他仪表板，造成后台压力更大，更卡顿的情况发生。
