### ISSUE TITLE
[Bug] 仪表板编辑状态进入全屏幕预览，视图位置乱跳

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#5490]
**DataEase 版本**
v1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 114.0.5735.133（正式版本） (arm64)

**Bug 描述**
仪表板编辑状态进入全屏幕预览，视图位置乱跳，视图下面是一个图片组件，采用悬浮模式，没进全屏预览显示如图一，进入全凭预览点击后显示如图二，而且很奇怪，点击跳啦几次后，就不会在跳了

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/a5d6b58a-81d2-4247-8719-c59c4265458e)

2.
![image](https://github.com/dataease/dataease/assets/109720729/370d4a5c-57e4-4f42-9595-4d3163595c0a)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，这种情况有可能是使用的机器算力不足导致，可以先关闭浏览器清空浏览器占用内存再看看呢
