### ISSUE TITLE
视图样式颜色设置与页面上展示的颜色不匹配

### ISSUE THREAD

**Issue by spritelyl** [dataease/dataease#5499]
**DataEase 版本**
v1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
114.0.5735.110（正式版本）

**Bug 描述**
在视图样式上面设置了颜色，但是页面上显示的颜色与设置好的颜色不匹配

**Bug 重现步骤(有截图更好)**
1. 新建视图，选择折线图表类型
2. 在样式中选择好了颜色方案
3. 最终页面上显示的颜色与设置好的颜色不匹配
![1687332601904](https://github.com/dataease/dataease/assets/50016789/0f4c27a0-23ce-405d-a87c-57cdc3a39e78)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境并未发现你所说的问题，是否有其他的一些操作呢？
