### ISSUE TITLE
[Feature]过滤条件增加：包含与不包含

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#55]
**请描述您的需求或者改进建议.**
建议过滤条件增加：包含与不包含
![image](https://user-images.githubusercontent.com/46042812/123517364-15f8c300-d6d3-11eb-9004-0ae4af24ba4b.png)

**Comment by yayanpei** [comment]
感谢您的反馈，您的建议是我们产品改进的方向

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已支持
