### ISSUE TITLE
关于防碰撞和边框的设计

### ISSUE THREAD

**Issue by lishuang1314** [dataease/dataease#550]
**请描述您的需求或者改进建议.**
如果有一个开关可以开启或者关闭图表之间防碰撞（重叠的效果就比较好）如果能在图表边缘加上datav的边框或者组件（http://datav.jiaminghi.com ）效果会更好一点

**Comment by xuwei-fit2cloud** [comment]
非常好的建议，我们其实已经在做相关的技术调研，相信很快会有这个功能。

**Comment by xuwei-fit2cloud** [comment]
v1.3.0 版本已支持碰撞检测
