### ISSUE TITLE
[Bug]在仪表板进入数据集字段管理页面使用 Ctrl+Z 快捷键后界面功能异常

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5501]
**DataEase 版本**
V1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新版

**Bug 描述**
在仪表板编辑界面，编辑某个视图标题时，如果输入了错误的文本，想要撤销，按 Ctrl+Z 快捷键后界面会直接关闭。
在仪表板界面修改数据集计算字段时也会出现此问题，当计算字段中输入了错误的文本，按 Ctrl+Z 撤销时会关闭整个页面回到仪表板界面。

**Bug 重现步骤(有截图更好)**
1.编辑仪表板
2.编辑某个视图
3.打开视图的数据集字段管理页面
4.新建计算字段
5.在计算字段表达式输入框中输入多个文字，按 Ctrl+Z 快捷键
6.此时整个计算字段页面会全部关闭

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
