### ISSUE TITLE
[Bug] OIDC单点登出不支持OpenID Connect RP-Initiated Logout 1.0

### ISSUE THREAD

**Issue by zju-zhanglu** [dataease/dataease#5502]
**DataEase 版本**
v1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome 114.0.5735.133（正式版本） (x86_64)

**Bug 描述**
OIDC logout不支持OpenID Connect RP-Initiated Logout 1.0

**Bug 重现步骤(有截图更好)**
1. 默认登录方式为普通登录时，退出DataEase后并未退出单点登录系统OP。
2. 默认登录方式为OIDC时，退出DataEase会自动重新登录。

[https://github.com/dataease/dataease/blob/dev/backend/src/main/java/io/dataease/auth/server/AuthServer.java#L323]()，OidcXpackService的logout()方法似乎只支持OpenID Connect Back-Channel Logout 1.0，但是很多单点登录系统仅支持OpenID Connect RP-Initiated Logout 1.0，例如[IDaaS](https://help.aliyun.com/document_detail/453391.html)，OidcXpackService的logout()方法应该跟CasXpackService一样返回字符串类型，才能通过浏览器重定向到logout endpoint。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by maninhill** [comment]
请升级到最新版本再次验证，如有问题再打开。
