### ISSUE TITLE
仪表板数据大屏点击导出为图片之后视图位置错位了

### ISSUE THREAD

**Issue by spritelyl** [dataease/dataease#5503]
**DataEase 版本**
v1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
114.0.5735.110（正式版本）

**Bug 描述**
仪表板数据大屏点击导出为图片之后视图位置错位了

**Bug 重现步骤(有截图更好)**
1. 保存好制作好的数据大屏
2. 点击导出为图片
3. 导出成功，但是打开发现数据大屏里面的各视图位置错位了
![image](https://github.com/dataease/dataease/assets/50016789/51982762-19a0-4cff-9a2c-74969a87149f)
![image](https://github.com/dataease/dataease/assets/50016789/e56c5a8e-165c-4eed-a166-55cf10c3d358)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，不知道是否有你认为无关的其他步骤操作没有说明呢？

**Comment by BBchicken-9527** [comment]
经过排查确认这是因为底图和白色边框为一个整体所导致，因为自适应的情况下图片和导出比例不一致在底图自适应的情况下白色边框也会跟随改变导致；可以尝试将底图和白色的框分开应该可以解决这个问题
