### ISSUE TITLE
[Feature]手机竖屏 点击图标放大后，自动切换成横屏模式，关闭后手机还是竖屏模式。

### ISSUE THREAD

**Issue by baoshan2020** [dataease/dataease#5509]
**请描述您的需求或者改进建议.**
手机竖屏 点击图标放大后，自动切换成横屏模式，关闭后手机还是竖屏模式。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，视图放大后，横屏还是竖屏展示我们这边没有做控制，根据您的描述，像是手机设置了自动切换横竖屏，可以更改一下设置再试试。
