### ISSUE TITLE
[Bug] 【加急...】新增Excel数据集时，保存后查询的数据乱序，还有空行

### ISSUE THREAD

**Issue by Coder-Tang** [dataease/dataease#5510]
**DataEase 版本**
dataease-v1.18.4-offline

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Microsoft Edge
版本 114.0.1823.51 (正式版本) (64 位)

**Bug 描述**
新增Excel数据集时，保存后预览的数据乱序，还有空行

**Bug 重现步骤(有截图更好)**
1.点击新增Excel数据集
2.导入Excel，此时导入预览的数据排序是正确的

![image](https://github.com/dataease/dataease/assets/20924425/da500fd4-c96a-472b-b7bc-9d2a8f3bc034)

3.保存后，查询的数据是乱序的，数据库里的表数据也是乱序的

![image](https://github.com/dataease/dataease/assets/20924425/3f90e7e1-f1f4-490b-84c9-f3ee30423048)

**Comment by BBchicken-9527** [comment]
感谢反馈，后面有空行大概率是因为你的excel中存在空格或空行的情况，你可以尝试将原文件后面的空行批量删除即可；
因为excel数据集本质是存在了doris中，doris的抽取是随机的；希望我的回答可以帮助到你；

**Comment by Coder-Tang** [comment]
> 感谢反馈，后面有空行大概率是因为你的excel中存在空格或空行的情况，你可以尝试将原文件后面的空行批量删除即可； 因为excel数据集本质是存在了doris中，doris的抽取是随机的；希望我的回答可以帮助到你；

doris的抽取是随机的话，那保存到数据库的时候可以加个数据排序过程吗？

**Comment by BBchicken-9527** [comment]
嗯... 目前不会考虑添加排序的，其实之前是存在排序的，但后续考虑到性能的问题我们这边去除了排序的；
