### ISSUE TITLE
[Feature] 希望数据源能支持IoTDB，手动开发的插件会报错

### ISSUE THREAD

**Issue by Coder-Tang** [dataease/dataease#5511]
**请描述您的需求或者改进建议.**
希望数据源能支持IoTDB，手动开发的插件会报错

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录至需求池中并调研一下，近期没有规划进行支持。如果出现插件报错的情况，建议您参考数据源插件开发示例（https://dataease.io/docs/dev_manual/dev_datasource_plugin/）排查一下报错原因。

**Comment by Coder-Tang** [comment]
> 感谢您的反馈，我们先记录至需求池中并调研一下，近期没有规划进行支持。如果出现插件报错的情况，建议您参考数据源插件开发示例（[https://dataease.io/docs/dev_manual/dev_datasource_plugin/）排查一下报错原因。](https://dataease.io/docs/dev_manual/dev_datasource_plugin/%EF%BC%89%E6%8E%92%E6%9F%A5%E4%B8%80%E4%B8%8B%E6%8A%A5%E9%94%99%E5%8E%9F%E5%9B%A0%E3%80%82)

插件开发完成，但是导入后新增数据源报错。。

**Comment by yayanpei-fit2cloud** [comment]
可以把报错信息和日志，追加一下评论，这边帮忙看一下呢。

**Comment by 66545shiwo** [comment]
请问下，数据源已经支持IOTDB了吗，我们有同样的需求

**Comment by jiajiazyj0108** [comment]
同问，能支持iotdb数据库了不
