### ISSUE TITLE
[Bug]看板查询次数过多，系统崩溃问题

### ISSUE THREAD

**Issue by DuLianYong-Chinese** [dataease/dataease#5515]
**DataEase 版本**
v1.18

**运行方式(安装包运行 or 源码运行 ?)**

官网
**浏览器版本**

谷歌浏览器
**Bug 描述**

看板不停的点查询，浏览器监测的堆内存一直在增加，如果机器本身内存不是很充足，过一会系统就会崩溃
**Bug 重现步骤(有截图更好)**
1.F12找到memory
2.打开系统，一直点击看板【【官方示例】阿勒泰地区旅游数据】
3.发现内存一直在增加，基本上不释放内存
![image](https://github.com/dataease/dataease/assets/42732955/5ceea71b-3576-4752-8e6b-b1512c56d37d)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们做一下相关优化。

**Comment by DuLianYong-Chinese** [comment]
您好，这个bug要多长时间能解决，挺着急的

**Comment by BBchicken-9527** [comment]
感谢反馈，目前已经将你的问题加到了池子里，我们还需要讨论一下解决方案，暂时没有排期，我已经将你的问题进行了标注，会尽可能优先处理你的问题的，感谢你的支持；

**Comment by DuLianYong-Chinese** [comment]
代码太多，希望您那边能帮忙定位问题在哪，具体是哪块没释放内存，然后我可以自己先修正下

**Comment by BBchicken-9527** [comment]
感谢反馈，目前经过排查可以确定ChartComponentG2.vue和UserView.vue是存在问题的，这个问题也会跟随下个小版本进行发布；

**Comment by DuLianYong-Chinese** [comment]
你好，下个小版本是哪天发布

**Comment by BBchicken-9527** [comment]
嗯... 具体的发布时间目前是还没有明确，但应该是在下个月中旬之后了

**Comment by DuLianYong-Chinese** [comment]
你好，ChartComponentG2.vue和UserView.vue这两个文件具体原因能跟我描述下吗，或者代码截个图，我们这没看出来问题，解决方案能提供下不，下个月中旬有点时间来不及了，或者您那改好了，能提前把代码发给我吗

**Comment by BBchicken-9527** [comment]
这个实在不好意思，目前只定位了问题的还没有进行具体的修改，我们也需要根据任务的排期进行的；

**Comment by DuLianYong-Chinese** [comment]
我把代码合并到1.18.2上，其实还是有内存不释放的问题，只不过没之前崩溃的快了

**Comment by BBchicken-9527** [comment]
嗯嗯 ，问题已经修复将会在下个小版本上线，可以小小的期待一下哦；

**Comment by BBchicken-9527** [comment]
目前问题已修复，可以下载最新版本体验，感谢你的建议与支持；
