### ISSUE TITLE
符号地图里气泡提示里面的小数会自动补充好多个0

### ISSUE THREAD

**Issue by KevinInce** [dataease/dataease#5516]
符号地图里气泡提示里面的小数会自动补充好多个0，这个能优化一下吗？看起来有些乱
<img width="138" alt="09fd0fbc3e1ea66d18da62696931890" src="https://github.com/dataease/dataease/assets/27195203/0d4318f5-a16f-427e-a89f-f81a9161132b">
我的数据是两位小数，数据集里看也是正常的，在气泡里就会自动补0
<img width="91" alt="5f8b691ebe83b65aa5582e235014311" src="https://github.com/dataease/dataease/assets/27195203/3debf778-3857-4a73-8100-8303ab0b8e6d">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个我们再想想，在交互上如何添加字段的格式化设置支持。

**Comment by xuwei-fit2cloud** [comment]
在1.x版本中目前还不是特别好处理，我们会在2.x中进行处理。
