### ISSUE TITLE
[Feature]仪表板导出为应用时支持API数据源

### ISSUE THREAD

**Issue by damoasis** [dataease/dataease#5518]
**请描述您的需求或者改进建议.**
目前版本V1.18.7 当仪表板中有用到API数据源的数据集时，把仪表板导出为应用时系统会提示：仪表板中不能存在API数据源或者Excel数据集。
需求：仪表板导出为应用时支持API数据源。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
数据源的配置相比数据库而言，会更加复杂，暂时没有规划支持API数据源
