### ISSUE TITLE
[Bug] 时间过滤组件带参过滤符号地图数据失效。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5519]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 114.0.5735.133（正式版本） (arm64)

**Bug 描述**
时间过滤组件带参过滤符号地图数据失效

**Bug 重现步骤(有截图更好)**
1. 创建待时间参数的 SQL 数据集。
![image](https://github.com/dataease/dataease/assets/30063018/8298b30f-d575-4e89-8775-8991b6508727)
![image](https://github.com/dataease/dataease/assets/30063018/86106707-20dd-49f4-8706-3ba4abeaf371)
2. 创建符号地图。
![image](https://github.com/dataease/dataease/assets/30063018/229c8373-2789-4aab-9619-3a0a38e2c75f)
3. 添加日期过滤组件，不带参数的情况下可以正常进行数据过滤。
![过滤组件不带参数](https://github.com/dataease/dataease/assets/30063018/ebee47e7-dd22-4103-bfba-ae6f55a240fc)
4. 带上参数的情况下，过滤就不生效了。
![过滤组件带参数](https://github.com/dataease/dataease/assets/30063018/9e495216-4e6e-47c7-bfe5-c543d7c08387)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
