### ISSUE TITLE
[Feature] 符号地图标签、提示显示优化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5520]
**请描述您的需求或者改进建议.**
符号地图在多条数据聚合的情况下，标签或者提示的文字会出现重复的情况，建议可以做一下去重。
![image](https://github.com/dataease/dataease/assets/30063018/5c49746d-e943-4c4e-98d2-dd3f94cde9b5)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。
