### ISSUE TITLE
[Bug] 相同excel，local和simple模式下保存后的数据不同

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5521]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
相同excel，local和simple模式下保存后的数据不同（local被去重了）

**Bug 重现步骤(有截图更好)**
1.simple 
<img width="1187" alt="image" src="https://github.com/dataease/dataease/assets/45852479/d3c36525-1c1e-48b7-ba6c-9c7eeaad1eec">
2.local
<img width="1113" alt="image" src="https://github.com/dataease/dataease/assets/45852479/ac05b827-57a5-4411-9943-e915a6b45514">

**Comment by BBchicken-9527** [comment]
感谢反馈，因为模式不同使用的数据库不一样，本地模式使用的是doris接收数据，而精简模式是用mysql接收的，doris目前是没有办法做到去重的，短时间内没有找到更好的办法去解决；
