### ISSUE TITLE
[Feature]后续是否加入自定义分辨率功能

### ISSUE THREAD

**Issue by ArvinC** [dataease/dataease#5522]
本身项目支持自适应这点我是清楚的，但是我们有很多异性屏，拼接屏，所以无法保证所有的大屏拼接后都是16:9的比例，所以迫切希望加入此功能

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，1.x中暂不规划实现该功能。我们在2.0中，加入了自定义大屏分辨率的功能，还请多加关注。
