### ISSUE TITLE
源码部署f12中websocket连接一直报错

### ISSUE THREAD

**Issue by QingLiangZhang1** [dataease/dataease#5523]
![image](https://github.com/dataease/dataease/assets/59195190/c2b90cfb-f0aa-4821-bd7d-fed7486abb41)

**Comment by QingLiangZhang1** [comment]
为啥会一直自动连接这个websocket，它是干啥用的？为啥会连接不上

**Comment by fit2cloud-chenyw** [comment]
为啥会一直自动连接这个websocket? websocket的长链接和心跳机制导致
它是干啥用的？服务器主动推送消息到前端
为啥会连接不上？端口错误
