### ISSUE TITLE
[Bug]分组柱状图子类别的维度如果有两个以上则图例显示不完整

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5525]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
分组柱状图，子类别的维度如果添加两个，图例显示不完整，貌似只给图例留了一行的空间。

<img width="891" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/77334d6b-174c-4ae4-a0f8-9d6a15b52ee8">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前图库中的视图内可操控性比较低，暂时还无法对此处进行优化，若显示多个字段，建议你将图例的方向改为垂直；

**Comment by BBchicken-9527** [comment]
感谢反馈，目前图库中的视图内可操控性比较低，暂时还无法对此处进行优化，若显示多个字段，建议你将图例的方向改为垂直；
