### ISSUE TITLE
[Feature]建议优化移动端配置时按钮的位置

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#5526]
**请描述您的需求或者改进建议.**
如下图所示，按按钮与界面是贴着的，建议适当增加一点间距会更好看一些。
![image](https://github.com/dataease/dataease/assets/48945409/6f429a21-a012-4c77-b6b3-e5a961414b31)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
