### ISSUE TITLE
[Bug]选项卡组件移入移动端后，选项卡中的多个组件只显示一个

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#5527]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 最高版

**Bug 描述**
选项卡组件移入移动端后，选项卡中的多个组件只显示一个，且该组件位置与原始位置不对应，也无法调整。

**Bug 重现步骤(有截图更好)**
1.PC 端样式
![image](https://github.com/dataease/dataease/assets/48945409/76340a84-a17b-4382-9854-db2d8c953702)

2.移动端样式：相对位置不一样且里边的组件大小无法调整
![image](https://github.com/dataease/dataease/assets/48945409/7ea6cb00-edca-400c-9640-84b9f161c21f)

3.PC 端样式：Tab 里边有两个视图组件
![image](https://github.com/dataease/dataease/assets/48945409/4a1e155f-af9e-4954-8c2f-ee2a3bfb68a0)

4.移动端样式：Tab 里只剩一个视图组件，即使将 Tab 拉的较长，希望里边的视图能够竖着显示也并没有，只有第一个存在的视图同时被拉长了
![image](https://github.com/dataease/dataease/assets/48945409/eeccf97a-3cc8-4fe0-8c23-477aaca3ef52)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
感谢反馈，我们修复一下
