### ISSUE TITLE
[Feature]视图维度指标批量选择拖拽功能

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5528]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/89771514/bb7ba5b7-dcb3-4772-8372-1a676411929d)

希望快速把所有的指标和维度字段全部拉到指标或维度框中，一个个拉取太费劲了

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，一个一个拖拽对于需要展示较多字段的明细表可能不太友好，但是对于其他图表来说还是比较合适的方式，我们暂时没有规划去修改当前的拖拽交互方式。
