### ISSUE TITLE
[Bug]DataEase不管有没有存在空闲操作,到时间后都会超时退出

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5529]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**

安装包运行 
**浏览器版本**
chrome

**Bug 描述**

DataEase 配置文件conf/dataease.properties 中的超时时间默认480分钟，这里并不是空闲操作480分钟后断开登录，不管用户有没有操作，登录时间到达480分钟后，DE就会断开登录，能否改为空闲操作才会超时退出登录？
![图片](https://github.com/dataease/dataease/assets/48307752/09caa0fc-1832-4711-ab7c-3b1566c885c0)

**Bug 重现步骤(有截图更好)**
1. 超时时间改为 1分钟
2. 1分钟内不断的增加视图、保存、删除视图、保存
3. 1分钟时间到，浏览器界面提示登录超时。

**Comment by BBchicken-9527** [comment]
感谢反馈，在综合考虑到性能开销以及添加黑名单单点登录等功能后存在续命机制的复杂性，续命机制在1.18.2就取消了的；

**Comment by mfanoffice** [comment]
> 

用户在操作中退出  感觉挺不合理的  一般都会认为是BUG，我们商讨出一个方案：空闲操作超时退出  + 登录超时改成12个小时 ，DE 空闲操作 30 分钟就退出登录，用户连续在线 12 个小时也会退出登录，这样用户就不会遇到操作中途退出的现象了，因为用户不可能不间断连续操作 12 个小时。

**Comment by BBchicken-9527** [comment]
感谢你的建议，我们讨论一下

**Comment by xuwei-fit2cloud** [comment]
短期内还没有相关调整计划，我们先记录一下。
