### ISSUE TITLE
修改源码后通过docker映射方式替换容器内部JAR

### ISSUE THREAD

**Issue by ShuXinRen12138** [dataease/dataease#5531]
根据需求修改源码本地运行测试后打包，通过映射dataease容器内部JAR方式替换一键部署容器内部JAR。容器启动报错 Error creating bean with name 'emailXpackDefaultService': lookup method resolution failed

**Comment by maninhill** [comment]
请参考：https://dataease.io/docs/dev_manual/dev_manual/
