### ISSUE TITLE
[Bug]全屏预览时下拉框选项错位

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5532]
**DataEase 版本**
V1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新

**Bug 描述**
当仪表板有下拉框时，全屏预览仪表板时点击下拉框，下拉选项离下拉框很远。
如果下拉框放在了右侧，下拉选项会看不到。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/30886198/4c3bdb76-4d1c-466b-aaa6-d41b87c6a907)
![image](https://github.com/dataease/dataease/assets/30886198/8bc82c5d-34b7-43f8-af69-24fff5590efb)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by liuboF2c** [comment]
此问题依然存在
