### ISSUE TITLE
达梦数据库能支持数据定时同步功能么引用相关问题（4748）

### ISSUE THREAD

**Issue by ShuXinRen12138** [dataease/dataease#5533]
达梦数据库能通过修改插件的方式支持数据定时同步功能么

**Comment by xuwei-fit2cloud** [comment]
目前插件形式实现的数据源还不能支持定时同步功能，原因有几个：
1. 定时同步需要用到kettle，数据源本身的驱动需要传到kettle镜像中为kettle所用
2. dataease主工程中对插件形式的数据源也还没有添加kettle任务调用的接口

所以如果要通过插件形式来支持定时同步的话，需要做一些二开工作。

**Comment by ShuXinRen12138** [comment]
那是说逻辑上是可以支持的，只是对于插件实现的数据源不支持么，那为什么dataease-extensions 项目中 kingbase的数据同步是支开启的DIRECT_AND_SYNC。

**Comment by ShuXinRen12138** [comment]
Oracle支持数据定时同步是做过适配的，语法很相似，如果二开需要做那些具体的工作

**Comment by xuwei-fit2cloud** [comment]
1. 可以参考Oracle或者MySQL等支持定时同步的内置数据源的代码，将达梦数据源内置到dataease主工程中。当然，二开的话，也可以自行在dataease主工程里加入调用kettle任务的接口
2. 更新kettle镜像，或将其驱动目录映射出来维护

**Comment by ShuXinRen12138** [comment]
已将kettle lib 映射出来并加入了达梦依赖，将extension dm代码移植到主工程中，修改了sdk、和dmconfig配置文件，页面运行同步功能的时候还是报错，看来是需要动主工程中同步相关代码

**Comment by ShuXinRen12138** [comment]
问题解决了
