### ISSUE TITLE
[Bug]Oracle 数据库添加动态辅助线时视图报错

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5534]
**DataEase 版本**
 V1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新

**Bug 描述**
使用 Oracle 数据库作为数据源，在仪表板中添加堆叠柱状图，当给柱状图添加动态辅助线后视图显示异常。

**Bug 重现步骤(有截图更好)**
设值动态辅助线时视图异常
![image](https://github.com/dataease/dataease/assets/30886198/2a200376-7e66-4f7f-9856-889377fb650f)
将辅助线修改为固定值时视图显示正常
![image](https://github.com/dataease/dataease/assets/30886198/98dbc758-c33e-4229-b1c8-c6203aff142d)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快处理

**Comment by BBchicken-9527** [comment]
目前问题已修复，可以下载最新版本体验，感谢你的建议与支持；
