### ISSUE TITLE
[Feature]日期显示建议增加按小时显示

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#554]
**请描述您的需求或者改进建议.**
目前之前按时分秒显示，希望增加个只按小时显示，类似按天显示，这样折线图就可以按照小时汇总结果了
![image](https://user-images.githubusercontent.com/35896106/128652963-76bf937c-d16c-4f16-968d-5f5b7e7d8b5c.png)

**Comment by yayanpei** [comment]
非常感谢您的反馈，我们会在后面的版本迭代中，支持更加丰富的日期显示格式

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
