### ISSUE TITLE
[Bug]新建 API 数据集时国际化文字错误，简体中文下出现繁体

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5540]
**DataEase 版本**
V1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 最新

**Bug 描述**
创建 API 数据集页面国际化文字错误

**Bug 重现步骤(有截图更好)**
![wecom-temp-11052-b0418ccab6cea80db3f6bb7b1d9b92de](https://github.com/dataease/dataease/assets/30886198/6d17f7a4-b175-4015-b8fd-2822f9519ff4)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by BBchicken-9527** [comment]
目前问题已修复，可以下载最新版本体验，感谢你的建议与支持；
