### ISSUE TITLE
[Bug]简体中文下出现繁体中文

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5541]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

![image](https://github.com/dataease/dataease/assets/89771514/95dd5b02-c2f0-4bab-a63b-889e25a32f81)

**Comment by BBchicken-9527** [comment]
感谢反馈，你的问题和5540重复，我将关闭此问题； [https://github.com/dataease/dataease/issues/5540](url)
