### ISSUE TITLE
源码本地运行引入default文件中依赖

### ISSUE THREAD

**Issue by ShuXinRen12138** [dataease/dataease#5543]
**DataEase 版本**

1.18。3
**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**

**Bug 描述**
本地开发需要数据库依赖所以把服务器dataease容器中的default依赖拉到本地对应目录下，源码运行报错 Error creating bean with name emailXpackDefautService  ,我将default文件中的 deplugin-xpack-backend包删除就可以正常启动。
服务器版本是1.18.7 和本地代码1.18.3会有影响么

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
不影响，那个是企业版功能包。
