### ISSUE TITLE
[Feature]符号地图支持标记样式的设置

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5544]
**请描述您的需求或者改进建议.**
Echarts的地图上的支持标记样式了，符号地图上什么时候可以设置标记样式呢
![image](https://github.com/dataease/dataease/assets/89771514/d614470c-f6c3-4654-8cbe-57f7fe3bad71)

**Comment by xuwei-fit2cloud** [comment]
需求已收到，但短期内还没有相关开发计划。
