### ISSUE TITLE
[Feature]新开发的数据源插件替换时，存在使用中的数据源数据集则无法更新

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5545]
**请描述您的需求或者改进建议.**
正在使用的插件，无法进行更新。必须要把数据源、数据集全删了才行。
那要是在生产上怎么操作，全删了再更新插件感觉并不友好，希望优化。

目前可以先手动替换一下插件目录下的 jar 包，然后重启服务，这样就不用删除数据源、数据集，但还是希望进行优化。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个地方我们后期优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
