### ISSUE TITLE
[Bug]AntV的富文本视图设置标题不会显示

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5546]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

![image](https://github.com/dataease/dataease/assets/89771514/e615e44e-cec0-4165-baf4-1183a839fced)

**Comment by BBchicken-9527** [comment]
感谢反馈，富文本视图相较于其他视图比较特殊，本身就不会显示名称的；
