### ISSUE TITLE
[Feature]dataease的明细表支持按列修改样式，希望后续能够跟grafana一样按列配置样式与功能

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5547]
**请描述您的需求或者改进建议.**
grafana 设置列的 Color scheme
![1688008881443](https://github.com/dataease/dataease/assets/89771514/7a786c16-70ec-454d-8d7c-08ac6ec6bf3b)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，但目前还没有相关支持计划。
