### ISSUE TITLE
[Feature]希望支持红绿箭头的设置，比如：上涨就是向上的攻色箭头 ，下跌就是绿色向下箭头 

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5548]
**请描述您的需求或者改进建议.**
有没有什么方式 能实现这种 ：如果比上周情况好 ，就红色箭头向上 ，如果比上周数据下跌 ，那么绿色向下箭头
![image](https://github.com/dataease/dataease/assets/89771514/d44e33d6-0054-43a1-8e33-f05efde58dd3)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前还没支持图标显示的阈值设置，我们先记录一下。
