### ISSUE TITLE
[Bug]选项卡组件，字体过大时，超出tab边框名边框大小不会自适应

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5549]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

![image](https://github.com/dataease/dataease/assets/89771514/3b6848ba-1ba6-49b7-9283-f73585ec6fd6)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
当前版本无法支持。
