### ISSUE TITLE
[Bug] 复制仪表板时，新的仪表板副本会丢失原来的外部参数设置

### ISSUE THREAD

**Issue by FJEagle** [dataease/dataease#5550]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
docker离线安装方式运行

**浏览器版本**
Microsoft Edge Version 113.0.1774.50 (Official build) (64-bit)

**Bug 描述**
原仪表板A设置了外部参数，复制得到新的仪表板B后，B没有原来A的外部参数信息

**Bug 重现步骤(有截图更好)**
1. 创建仪表板A，并设置任意外部参数
2. 复制仪表板A，得到副本仪表板B
3. 查看编辑仪表板B， B的外部参数设置为空

**Comment by BBchicken-9527** [comment]
感谢反馈，目前复制仪表板本身就是不对带上外部参数的，其实不光是外部参数，还有跳转和联动也是不会因为复制带过去的；
