### ISSUE TITLE
[Bug]【视图】视图筛选异常

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5551]
**DataEase 版本**
1.18.8 版本

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
SQLServer 数据源的带参数的 SQL 数据集在下拉树进行筛选时报错。

**Bug 重现步骤(有截图更好)**

1.异常情况

数据源类型：SQLServer
SQL 数据集：SELECT * FROM departTable WHERE depart_name = '${CESHI}'
组件：下拉树组件
筛选结果截图：
![image](https://github.com/dataease/dataease/assets/24768910/75368eb9-4c44-40e3-86ea-cda9e7049898)

2.正常情况

数据源类型：MySQL
SQL 数据集：SELECT * FROM area_mapping WHERE city_name = '${CESHI}'
组件：下拉树组件
筛选结果截图：
![image](https://github.com/dataease/dataease/assets/24768910/3758da8a-849e-4fe0-88d6-942c267463d6)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
