### ISSUE TITLE
部署后无法访问

### ISSUE THREAD

**Issue by ouyangyuanpeng** [dataease/dataease#5552]
版本 1.18.8
端口修改为10080
服务器端口已经放开
![image](https://github.com/dataease/dataease/assets/54929191/a2570f03-5ac4-4b9f-b301-f0c4dff35278)
![image](https://github.com/dataease/dataease/assets/54929191/16a25eff-5465-4e46-96bb-ba4aa3220275)

**Comment by xuwei-fit2cloud** [comment]
您可以先这样确认一下：
1. 服务器上执行 curl localhost:10080，看看是否有html响应返回
2. 找一台远程机器，通过nc、telnet等工具，测试安装了DataEase服务器的 10080 端口是否可访问

如果1无响应，则是服务本身有问题；如果2不可从外部访问端口的话，请检查防火墙。
如还有问题，可以加入我们的社区群，向我们的技术支持咨询。

**Comment by ouyangyuanpeng** [comment]
![image](https://github.com/dataease/dataease/assets/54929191/46030093-2f75-47af-b593-7fd1b588098c)
![image](https://github.com/dataease/dataease/assets/54929191/90835f93-8dbf-4d3d-bed8-098c6e31bdde)

**Comment by xuwei-fit2cloud** [comment]
您可以看看：
1. 浏览器是否有代理设置
2. 换个浏览器试试

或者联系社区群里的技术支持帮忙远程看看。

**Comment by ouyangyuanpeng** [comment]
还是访问不了，但是通过nginx代理可以访问，直接通过端口还是不行
