### ISSUE TITLE
[Bug]安装脚本检测磁盘空间是否小于 20G 判断方法有误

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5553]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
安装脚本 install.sh 中会检测安装目录所在磁盘空间如果小于 20G 会报提示信息：
”[警告] DataEase 运行目录所在磁盘剩余空间不足 20G 可能无法正常启动!“

但是有时候在磁盘空间足够时也会报错

```
read available_disk <<< $(df -H --output=avail ${DE_BASE} | tail -1)
available_disk=${available_disk%?}
if [[ $available_disk < 20.0 ]];then
   log "\033[31m[警告] DataEase 运行目录所在磁盘剩余空间不足 20G 可能无法正常启动!\033[0m"
fi
```
在 install.sh 以上代码部分，将判断逻辑进行修改
`if (( $(echo "$available_disk < 20.0" | bc -l) )); then`
即可避免误判。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by mfanoffice** [comment]
![图片](https://github.com/dataease/dataease/assets/48307752/8da9eb09-419b-4ae4-946d-ea74ab3d53f1)

```
read available_disk <<< $(df -H --output=avail ${DE_BASE} | tail -1)
available_disk=${available_disk%?}
available_disk=$(printf "%.0f" "$available_disk")

if [[ $available_disk -lt 20 ]];then
   echo -e "\033[31m[警告] DataEase 运行目录所在磁盘剩余空间不足 20G 可能无法正常启动!\033[0m"
fi
```
考虑 bc 命令有些环境可能不存在，可将 bc 换成 printf 
printf命令将浮点数available_disk转换为整数。"%.0f"指定了printf命令的格式，其中%.0f表示将浮点数四舍五入到整数

**Comment by xuwei-fit2cloud** [comment]
已修复，等待新版本发布。
