### ISSUE TITLE
[Bug]PostgreSql数据源创建的数据集制作的仪表板，通过公共链接访问仪表板，跳转时参数无效

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5554]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**Bug 重现步骤(有截图更好)**
1.创建一个PostgreSql数据源
2.使用PostgreSql数据源创建【数据库数据集】
3、使用【数据库数据集】制作 【仪表板 1】，【仪表板 1】中添加一个 明细表
![image](https://github.com/dataease/dataease/assets/89771514/3579a451-b6e6-435e-917e-95629e3cafbe)

4.使用【数据库数据集】制作 【仪表板 2】，【仪表板 2】中添加一个 AntV 折线图，为视图设置跳转设置，跳转【仪表板 1】
![image](https://github.com/dataease/dataease/assets/89771514/2e5c3353-abfc-43ed-91e2-7de5ff2e7159)
![image](https://github.com/dataease/dataease/assets/89771514/a7a8475c-0e40-47f7-b937-cd44f5e3e2dd)

5、在【仪表板 2】的仪表板预览页面点击进行跳转没有问题
![image](https://github.com/dataease/dataease/assets/89771514/95708028-3aa5-4e58-9c2f-cd6865c40aa3)
![image](https://github.com/dataease/dataease/assets/89771514/1ddcfeb6-b8a9-4726-857a-94276952ddef)

6、为【仪表板 1】和【仪表板 2】创建公共链接，用【仪表板 2】的公共链接访问，点击进行跳转，此时跳转后的【仪表板1】过滤无效
![image](https://github.com/dataease/dataease/assets/89771514/e0c82755-8bd1-4797-9063-3d61c7dc5bca)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
