### ISSUE TITLE
[Bug]MySQL 数据源配置界面，数据库名称中含有小数点 . 会报错数据库名无效

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5555]
**DataEase 版本**
 v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**

**Bug 描述**
MySQL 数据源配置界面，数据库名称中含有小数点 . 会报错数据库名无效
<img width="1415" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/61f08437-80c8-4bf8-82e7-3b0fdb8dd6bb">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
目前问题已修复，可以下载最新版本体验，感谢你的建议与支持；
