### ISSUE TITLE
[Feature]视图文本卡组件，希望支持设置默认值，当没有数据或数据为空时展示默认值

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5557]
**请描述您的需求或者改进建议.**
视图文本卡组件，当前过滤器过滤后，可能对应的维度是空值，希望有值的时候显示具体值，空值的时候显示默认值
有尝试用计算字段；
但对于过滤器过滤后，没有记录（不是字段为空值）的情况，还是会显示为空的

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请问默认值从哪里获取？

**Comment by ZhaoQian1222** [comment]
类似视图的高级设置里空值处理，支持对用户自己设置默认值

**Comment by yayanpei-fit2cloud** [comment]
暂时不规划实现该功能，文本展示的是数据集的真实数据，如果需要对数据进行处理，建议在数据集中新建计算字段。

Issue先进性关闭了，感谢您的关注和支持。
