### ISSUE TITLE
[Feature]折线图设置辅助线为动态平均值，辅助线小数位过长时无法设置小数位

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5558]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/89771514/cf2746a0-2b65-4393-96f8-04ad4a98f4fb)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，辅助线的格式是跟随纵轴的轴标签格式类型，可参考下图进行设置：

<img width="348" alt="image" src="https://github.com/dataease/dataease/assets/84168063/75c43108-176e-47ea-8ba9-d98e81d1a7da">

**Comment by ZhaoQian1222** [comment]
收到
