### ISSUE TITLE
使用修改后的代码制作镜像是报错

### ISSUE THREAD

**Issue by dengguoqing93** [dataease/dataease#5561]
Failed to deploy 'dataease Dockerfile: Dockerfile': Status 500: {"message":"Error processing tar file(exit status 1): mkdir /mobile/node_modules/puppeteer/.local-chromium/mac-756035/chrome-mac/Chromium.app/Contents/Frameworks/Chromium Framework.framework/Resources/de.lproj: no such file or directory"}

**Comment by xuwei-fit2cloud** [comment]
在 Apple M1 环境下测试，并没有复现您所提及的问题。
您可以尝试下载源码后，不修改任何代码，进行镜像制作试试。
我的build命令如下：
docker build --build-arg IMAGE_TAG=1.18.8 -t  wei/de:v1.18.8 .
