### ISSUE TITLE
[Feature]期望当 Echarts 地图没有数据时标签和提示均不显示，而不是显示 NaN

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5562]
**请描述您的需求或者改进建议.**
 当地图中某个省份没有数据时，希望鼠标移上地图中不显示省份名称且不显示提示。仅当有数据时显示提示信息。
原因是想展示十几个省份的分公司数据，没有分公司的省份不想显示。

![image](https://github.com/dataease/dataease/assets/30886198/6ac8d525-ce5f-49b5-9915-d636a41a3289)

**Comment by fit2cloud-chenyw** [comment]
已处理

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已在版本 V1.18.9 中进行优化，如有需要，建议把版本升级至 V1.18.9。
