### ISSUE TITLE
[Bug] SQL Server 库名包含中横线时无法校验通过和保存，提示 Invalid database name 

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5563]
**DataEase 版本**
V1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 最新

**Bug 描述**
当添加 SQLServer 数据库时，若库名包含中横线，则提示 Invalid database name，无法添加数据源

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/30886198/24df3bff-f7ba-4e83-9fb1-03c7d1ffb015)

**Comment by BBchicken-9527** [comment]
感谢反馈， 我们会尽快修复；

**Comment by liuboF2c** [comment]
追加一个问题：数据库名称是中文的也会提示 invalid database name
<img width="1707" alt="image" src="https://github.com/dataease/dataease/assets/30886198/94628a7a-799b-4ceb-950c-1f02b1b6d5af">

**Comment by BBchicken-9527** [comment]
问题已修复，可以下载新版本体验；
