### ISSUE TITLE
[Bug]仪表板编辑状态下查询速度比非编辑状态下查询速度慢很多

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#5566]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌114.0.5735.111（正式版本） （64 位）

**Bug 描述**
1，仪表板查询速度慢，都是相同的操作，在仪表板编辑状态下，切换查询条件后的查询速度比非编辑状态下查询速度慢很多。

**Bug 重现步骤(有截图更好)**
1.在仪表板编辑状态下，切换时间范围进行查询，先查上月，等所有视图都显示后，切换查上周的数据，正常来说没有任何的数据，应该是立马就能显示的，但是却转圈圈转了好久。
![11](https://github.com/dataease/dataease/assets/26103277/7919e791-3357-48c8-8681-f0bbcca7aaff)
2.退出编辑后，切换时间查询上个月的数据，等所有视图都显示后，切换时间查询上周的数据，立马就出结果了。
![22](https://github.com/dataease/dataease/assets/26103277/7dc6eb58-ac1e-4b19-a6a7-7d18b2e58f85)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问这种情况可以稳定复现嘛？目前我这边测试环境没有发现你说的问题，方便说一下每张表大概的数据量吗我这边在做一下更细致的模拟

**Comment by hw872715125** [comment]
稳定复现！宽表的数据量6亿，join了三个视图
![image](https://github.com/dataease/dataease/assets/26103277/361ec3df-67d0-40a2-870a-0d7ac18c8724)
在编辑状态下的查询速度慢的很明显呀，你看动图中，我做了对比，同样的操作，只是修改了查询日期

**Comment by BBchicken-9527** [comment]
嗯嗯 ，我这边要做出复现主要是方便后期研发修改，我们这边再尝试一下

**Comment by hw872715125** [comment]
验证编辑状态下的查询速度慢的问题，我又测试了下，切换日期查询的结果都是没有数据的，比如在上周和本周之间来回切换。在刚开始的时候，切换日期查询响应是秒出的，界面的loading一晃就消失了。多次切换后，是越来越慢。我就停顿了几秒钟后，继续来回切换，刚开始是很快响应的，再多切换几次后，就开始变慢了。
![33](https://github.com/dataease/dataease/assets/26103277/d2900d4b-ae2f-4b93-b62c-e2de2a5be0bf)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们这边基本找到了原因回尽快修复；

**Comment by hw872715125** [comment]
还有一个现象，不知是否为同一个问题。
打开两个不同的仪表板，数据集一样。在仪表板**运营状况**做查询时，仪表板**运营状况1**的查询速度会受影响，导致查询速度变慢？
操作如下图：
![66](https://github.com/dataease/dataease/assets/26103277/06719f72-905b-4fa3-8eb8-a1831a6ae8e7)

**Comment by hw872715125** [comment]
又发现一个问题，切换到仪表板设置手机页面，这个查询有点问题，明明设置了时间范围，但是查询的数据结果，怎么1970年的都显示了
![image](https://github.com/dataease/dataease/assets/26103277/e00703ac-dfaf-4d36-a674-41de0b1d6606)

**Comment by BBchicken-9527** [comment]
> 又发现一个问题，切换到仪表板设置手机页面，这个查询有点问题，明明设置了时间范围，但是查询的数据结果，怎么1970年的都显示了 ![image](https://user-images.githubusercontent.com/26103277/250469153-e00703ac-dfaf-4d36-a674-41de0b1d6606.png)

是不会生效的，这个页面主要是针对移动端布局使用的，只是样式显示，所以过滤组件是不会生效的

**Comment by hw872715125** [comment]
设置移动端布局时，可以优化一下吗，确实有点卡呀！

**Comment by hw872715125** [comment]
> > 又发现一个问题，切换到仪表板设置手机页面，这个查询有点问题，明明设置了时间范围，但是查询的数据结果，怎么1970年的都显示了 ![image](https://user-images.githubusercontent.com/26103277/250469153-e00703ac-dfaf-4d36-a674-41de0b1d6606.png)
> 
> 是不会生效的，这个页面主要是针对移动端布局使用的，只是样式显示，所以过滤组件是不会生效的

设置移动端布局时，可以优化一下吗，确实有点卡呀！

**Comment by BBchicken-9527** [comment]
嗯....确实数据量过大的时候会有卡顿，这里我们讨论一下优化的方案吧

**Comment by ziyujiahao** [comment]
这个问题之前已经进行了优化，产生这个原因是因为含有默认值的过滤组件的时候，因为要涉及到视图的自定义颜色，加上过滤的话导致查询到的属性不全，所以需要去掉过滤条件再查一次数据保证全部属性可以得到，因此再编辑界面，含有默认过滤条件的视图会走两次查询。但是没有默认值的过滤组件或者在预览界面不用这么操作所以比较快
