### ISSUE TITLE
[Feature]折线图空值或者NULL不需要显示

### ISSUE THREAD

**Issue by baoshan2020** [dataease/dataease#5567]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/61979600/a9230cc9-045a-441b-9574-594d748dab00)
![image](https://github.com/dataease/dataease/assets/61979600/9a5e04fb-cc80-4439-b109-2802d2a79b06)
对比2张图标。  空值或者NULL不显示，效果会好很多。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，该需求已经开发完成，请关注我们后面的小版本发布。

**Comment by baoshan2020** [comment]
我一直在关注。

**Comment by xuwei-fit2cloud** [comment]
在视图里设置一下控制处理。
<img width="350" alt="图片" src="https://github.com/dataease/dataease/assets/1892127/cb9513b9-a96b-465d-aa7f-843c4e21c49f">

**Comment by baoshan2020** [comment]
漂亮
