### ISSUE TITLE
[Feature]折现图原始数据是年月日，能否按照月来显示

### ISSUE THREAD

**Issue by baoshan2020** [dataease/dataease#5568]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/61979600/c3e28242-160b-4479-8d43-4535dd7f89f2)
![Snipaste_2023-06-30_18-36-05](https://github.com/dataease/dataease/assets/61979600/3fcd7b7f-3472-4ef7-a70e-326007d8dc52)
折现图原始数据是年月日，能否按照月来显示。最好间隔一个月。如2023年4月1日  显示2023年4月。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，是支持按月显示进行的，请参考下图进行设置：
<img width="330" alt="image" src="https://github.com/dataease/dataease/assets/84168063/2aed3bfa-87cc-47e6-9f65-169fed8404e0">

**Comment by baoshan2020** [comment]
这样操作就按月汇总数据了。和我的需求不一样
<img width="581" alt="2a07c0d361f1e851e729f4191a4f3b0" src="https://github.com/dataease/dataease/assets/61979600/f7c171fb-f2a8-4956-beca-510d2bda96ec">
我的原始数据精确到日。但是我想显示到月。 比如2023年5月有好多数据，2023年5月1日显示2023年5月，其他的日期不在显示，依次类推。

**Comment by yayanpei-fit2cloud** [comment]
建议您先按照月汇总展示，然后用下钻的方式展示当月的数据。
