### ISSUE TITLE
[Feature] 折线图空白很多的地方删除掉

### ISSUE THREAD

**Issue by baoshan2020** [dataease/dataease#5569]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/61979600/e8865d1e-9e7c-4e61-9f30-481d9f20783a)
如图，折线图空白很多的地方能否删除掉，如图，从400以上开始显示，400以下不显示。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议您自定义纵轴的轴值最小值为400，如下图所示：
<img width="350" alt="image" src="https://github.com/dataease/dataease/assets/84168063/14fadbf5-a238-42ac-8e8b-3c0fa0fb3693">

**Comment by baoshan2020** [comment]
非常感谢，解决问题了。
