### ISSUE TITLE
[Bug]elasticserach7.17.5 数据集，使用富文本组件精度丢失

### ISSUE THREAD

**Issue by imiem** [dataease/dataease#5570]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 14.0.5735.198

**Bug 描述**
elasticserach7.17.5 数据集，使用富文本组件精度丢失

**Bug 重现步骤(有截图更好)**
1. 如真实数据为 10.1，但是富文本组件显示 10.0。
2.
3.

**Comment by zrfit** [comment]
您好，感谢反馈！计划v1.18.10修复。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
