### ISSUE TITLE
[Bug]mysql数据源，数据库中新建表，数据源中的数据源表不会更新

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5574]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
mysql数据源，数据库中新建表，数据源中的数据源表不会更新
创建一个新的数据源，使用相同的数据源连接信息，数据源表可以获取到最新的表
![1688353354881](https://github.com/dataease/dataease/assets/89771514/6e92327d-bb61-4830-92b0-864ccd0f5cd1)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，更新数据源后请刷新一下数据源表页面；
