### ISSUE TITLE
[Bug]API 数据集同步任务增量更新修改为全量更新不生效

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5577]
**DataEase 版本**
V1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新版

**Bug 描述**
API 数据集同步任务先设置为增量更新、简单重复，后改为全量更新后依然是增量更新。

**Bug 重现步骤(有截图更好)**
1.选取一个 API 数据集，在更新信息中添加一个同步任务，参数如图
![image](https://github.com/dataease/dataease/assets/30886198/b6df0ef3-3024-4106-b6a0-1ded6280bde7)
2. 点击立即同步，立即触发一次增量同步，此时数据预览时数据量变成原来的 2 倍
3. 将同步任务修改为全量更新，如图
![image](https://github.com/dataease/dataease/assets/30886198/016bf37b-84ad-4a98-9dd5-3d4a385669d8)
4. 修改后再次点击立即同步，此时数据量会变为原来的 3 倍
5. 删除上面创建的任务，重新创建一个全量更新的任务，点击立即更新，数据量会变为原来的 1 倍
6. 所以，全量更新选项只有在第一次创建任务时选择才生效，如果是从增量更新切换为全量更新，此选项不生效 

期望：如果不支持修改更新方式，应置灰。如果支持修改，则第 4 步同步后数据量应是原来的 1 倍。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
