### ISSUE TITLE
[Bug]elasticserach7.17.5 数据集，时间戳转日期错误 

### ISSUE THREAD

**Issue by imiem** [dataease/dataease#5578]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 14.0.5735.198

**Bug 描述**
es中源数据存储的时间戳，使用明细表显示的时间格式有误

**Bug 重现步骤(有截图更好)**
1. 如时间戳为 1688452300569（2023-07-04 14:31:40），明细表中显示为：2023-07-04 06:31:40
2. 应该是转成了 UTC 时间
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是说明细表新建一个视图字段后再添加显示的时间不对吗？

**Comment by imiem** [comment]
存储的时间为：1688465062844
<img width="635" alt="image" src="https://github.com/dataease/dataease/assets/18100370/8ef76f48-994c-4295-94a1-b43208ac5ce5">
查询出显示的为：
<img width="1429" alt="image" src="https://github.com/dataease/dataease/assets/18100370/7837200b-c6ac-44af-976a-80dd992f4349">

**Comment by imiem** [comment]
存储的为：1688465062844
<img width="635" alt="image" src="https://github.com/dataease/dataease/assets/18100370/5949be90-8de1-469e-a398-26e026619815">

查询出的为：
<img width="543" alt="image" src="https://github.com/dataease/dataease/assets/18100370/772e7fd6-fae3-46c8-9174-7be79d70a945">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们处理一下；

**Comment by ChangeMaker2018** [comment]
同样的时间戳问题，在V2.4.0中，也出现了。求教~~~应该怎么办？

https://github.com/dataease/dataease/issues/8539#issuecomment-2002443293
