### ISSUE TITLE
[Feature]数据同步可以同时同步表名和字段名称到doris

### ISSUE THREAD

**Issue by Zhb95** [dataease/dataease#5579]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/75066592/9fd773bf-3c6d-4e8b-8453-71abd82f1d41)
如图这些表名和字段名跟源表不一致,希望doris的同步表可以跟源表一致

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，在2.0的底层设计中底层会保存原始表名和字段名。1.x如果要修改底层设计，代价太大，因此不再进行修改。
