### ISSUE TITLE
[Bug]达梦数据源添加问题

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5580]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新版

**Bug 描述**
达梦数据源添加时需要填写数据库然后再选择 schema，两个重复了。且达梦官方示例中并没有在 jdbc 链接地址后追加数据库名。
建议去除页面填写数据库，且 JDBC 链接地址后去掉数据库名

![image](https://github.com/dataease/dataease/assets/30886198/c2650fc7-577f-423d-8b16-c169adb78e51)
![image](https://github.com/dataease/dataease/assets/30886198/8cd3650a-cbc5-465c-8654-92dec0dcdf00)
![image](https://github.com/dataease/dataease/assets/30886198/eb7f41e4-da1b-42de-8362-45fd91833cdb)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
