### ISSUE TITLE
希望过滤组件（下拉文本、时间）能传递到api接口调用的查询参数里

### ISSUE THREAD

**Issue by iknitting** [dataease/dataease#5582]
**请描述您的需求或者改进建议.**
希望过滤组件（下拉文本、时间）能传递到api接口调用的查询参数里
对于复杂的业务场景，写sql会很复杂，通过写代码方式会比较灵活，提供的接口需要接收特定的参数，否则数据量会非常大，因此希望过滤组件（下拉文本、时间）能传递到api接口调用的查询参数里

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下。

**Comment by hw872715125** [comment]
我觉得这个是很有必要的，在dataease的仪表板中利用可视化的组件来显示其他系统中的数据，其他系统的数据可能会存在二次加工的问题。仪表板中的动态参数传递给api接口的查询参数中，调用其他系统中的接口，获取最终的结果数据做报表分析~

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的关注和支持，我们近期暂时没有规划进行支持。
