### ISSUE TITLE
[Feature]通过指标自助分析能力

### ISSUE THREAD

**Issue by cuilong1009** [dataease/dataease#5584]
**请描述您的需求或者改进建议.**
目前自助分析，只支持单表，但目前每个公司有自己的指标库，公司更系统使用自己的指标库的指标数据进行动态拖拽展示能力，如下图

![image](https://github.com/dataease/dataease/assets/47907572/8559d9d6-0ef8-41df-b054-1c4eddaa4ab1)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，没太理解您的意思，在制作图表时，目前只能选择一个数据集，您是建议能选择多个数据集吗？

**Comment by cuilong1009** [comment]
抛弃数据集概念，用户可以自助分析，您可以结合我发的图表示例看一下，用户打开自助分析
左侧展示维度和指标（维度和指标是）指标和维度是配置化，选择图表展示方式，可以进行拖拽
实际应用场景中是 运营用户是不关心底表的（也就是不关系数据集是什么）

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，数据的自助式分析，在我们产品的长期规划中，但是近期暂时没有规划去支持。
