### ISSUE TITLE
[Feature]【应用】默认应用适配不了 JumpServer 3.0

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5585]
**请描述您的需求或者改进建议.**
Dataease 当前的这个应用目前是 JumpServer 3.0 以前的版本，看是去掉这个默认还是标注一下还是把 3.0 默认进去。
![image](https://github.com/dataease/dataease/assets/24768910/2af7de77-e91a-4c5f-ae4c-781a5de51b51)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们来处理一下。

**Comment by maninhill** [comment]
应用这块需求很少，后续不再考虑。
