### ISSUE TITLE
[Feature]【视图】地图的点击事件优化

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5587]
**请描述您的需求或者改进建议.**
地图的点击事件（提示缺少关联字段）可以去掉么，如果没有值的话，会提示缺少关联字段。
提前会体验不好，没有值能自动补零也好！
![image](https://github.com/dataease/dataease/assets/24768910/8f4837ab-2edf-411b-9740-9814329e31dd)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.9版本已处理，请更新版本。
