### ISSUE TITLE
[Bug]【视图】地图视图没有「新加坡」这个国家

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5588]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
地图视图没有「新加坡」这个国家。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下

**Comment by xuwei-fit2cloud** [comment]
很抱歉，地图的GEO JSON文件不好处理，短期内还无法解决。

**Comment by xuwei-fit2cloud** [comment]
v1.18.25版本已处理。
