### ISSUE TITLE
[Feature]【视图】视图展示优化

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5591]
**请描述您的需求或者改进建议.**
当去掉纵轴的标签显示，带标签的折线图（柱状图）的标签会被遮挡。

![image](https://github.com/dataease/dataease/assets/24768910/fffd5dc1-650f-45fc-94cd-26725e5fbe2c)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，这里图库根据收到的数据和计算规则，算出来的最大值，修改不了。建议通过自定义纵轴最大值、或者调整标签位置的方式获取更好的显示效果。
