### ISSUE TITLE
[Feature]增加动态维度和动态指标

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#5593]
**请描述您的需求或者改进建议.**
增加动态维度和动态指标，提升查询的自由度。
在一个视图中选定维度和指标后就固定了，想查看其他维度和指标，又只能新建一个视图。
希望能够增加动态维度和动态指标来支持在一个视图内就即可实现不同维度和指标的自由组合查询。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，这个需求已经在需求池中，我们预计在2.x版本中进行支持。
