### ISSUE TITLE
[Bug]【数据源】SQLServer 2000 数据源连接失败

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5594]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
在驱动管理里上传了 SQLServer 2000 版本的驱动，连接数据源连接失败。
![image](https://github.com/dataease/dataease/assets/24768910/ce810f1f-25da-4c7f-9fae-0194456e90c9)
原因是，2000 版本没有 schema 的概念，所以 schema 应该非必填。
（售前客户反馈）

**Comment by BBchicken-9527** [comment]
感谢反馈，我们确认一下

**Comment by xuwei-fit2cloud** [comment]
目前我们没有获取到SQLserver 2000的环境，短期内无法处理。
