### ISSUE TITLE
[Bug] 含有with as语句的pg sql 预览成功，保存报错

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5595]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
含有with as语句的pg sql 预览成功，保存报错

**Bug 重现步骤(有截图更好)**
<img width="1445" alt="image" src="https://github.com/dataease/dataease/assets/45852479/eafc53d3-469c-47a9-9a6a-933ee5e037ce">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，方便将你的语句处理掉关键信息给我这边看一下嘛？
