### ISSUE TITLE
[Bug]doris数据源，创建SQL数据集时，order by排序不生效

### ISSUE THREAD

**Issue by zhanwonichengshizhu** [dataease/dataease#5596]
**DataEase 版本**
1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
doris数据源，创建SQL数据集时，order by排序不生效

**Bug 重现步骤(有截图更好)**
1.doris数据库做为数据源
2.创建SQL数据集直连，使用order by进行排序，运行查询，查询结果并没有做排序
3.在数据库中直接执行相同语句，排序是生效的

**Comment by BBchicken-9527** [comment]
感谢反馈，其实是生效了的，因为页面中tree没有动态刷新所以需要全局刷新后才能显示为修改后的名称，我们优化一下；

**Comment by BBchicken-9527** [comment]
感谢您的反馈，目前版本doris是不支持orderby排序的，短期内目前没有计划对此处做出变更，因为我们的理解中数据集只是用来单纯预览数据进行数据的确认，而视图才有可能有排序的需求，不过你的需求我这边已经记录了可能会在后续版本中展开

**Comment by niefajun** [comment]
Starrocks数据源也有相同的排序问题

**Comment by niefajun** [comment]
> 感谢您的反馈，目前版本doris是不支持orderby排序的，短期内目前没有计划对此处做出变更，因为我们的理解中数据集只是用来单纯预览数据进行数据的确认，而视图才有可能有排序的需求，不过你的需求我这边已经记录了可能会在后续版本中展开

我们实际用法跟这个理解有一些不一样，有时候会有些临时数据统计需求，就直接使用SQL数据集，写SQL统计排序出来，然后直接导出Excel。现在导出的数据无序(虽然已经指定了order by)，就需要在Excel里面调整排序。

**Comment by xuwei-fit2cloud** [comment]
暂时还无法支持。
