### ISSUE TITLE
[Feature]大屏数据可通过企微机器人实时通知

### ISSUE THREAD

**Issue by sirlover** [dataease/dataease#5597]
**请描述您的需求或者改进建议.**
已商城业务场景为例，通过数据库直连搭建大屏，针对分销订单、客户充值等信息，是否可以通过机器人接口实时推送到群（xx员工分销xx商品，获得xx佣金；xx员工推荐xx充值xx元），其中xx为数据库字段的变量。可参考腾讯轻联

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论后再回复您。

**Comment by maninhill** [comment]
记得要真反馈，而不是就没有下文了。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的支持，实时通知是可视化展示的附加功能，我们当前阶段暂时没有规划去做支持，待收到更多用户的反馈后再进行规划。
