### ISSUE TITLE
[Bug]【仪表板】默认仪表盘里重命名改完不生效

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5599]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
默认仪表盘里重命名改完不生效。
![wecom-temp-13207-ac6152e08111acbd74a50688f95328d1](https://github.com/dataease/dataease/assets/24768910/619b216b-0aad-4413-a048-0e712cd0a42d)

**Comment by BBchicken-9527** [comment]
感谢反馈，其实是生效了的，因为页面中tree没有动态刷新所以需要全局刷新后才能显示为修改后的名称，我们优化一下；

**Comment by BBchicken-9527** [comment]
目前问题已修复，可以下载最新版本体验，感谢你的建议与支持；
