### ISSUE TITLE
[Bug]仪表板收藏后再取消，仪表板显示为空

### ISSUE THREAD

**Issue by Andyguo5891** [dataease/dataease#56]
**DataEase 版本**
1.0

**浏览器版本**
chrome 91.0.4472.114

**Bug 描述**
仪表板收藏后再取消，仪表板内容显示为空

**Bug 重现步骤(有截图更好)**
1.点击收藏
![image](https://user-images.githubusercontent.com/46042812/123517911-38401000-d6d6-11eb-9c7a-92dba33346ad.png)
2.然后取消
![image](https://user-images.githubusercontent.com/46042812/123517932-50179400-d6d6-11eb-95b4-590d2d8b79e0.png)
3.取消后的结果：仪表板所有图示都不再显示
![image](https://user-images.githubusercontent.com/46042812/123517955-63c2fa80-d6d6-11eb-979b-c973db186074.png)

**Comment by xuwei-fit2cloud** [comment]
已复现问题，步骤为：
1. 点击收藏tab页，然后返回到仪表板tab页
2. 选择任一仪表板，点击右上角收藏，再取消

**Comment by xuwei-fit2cloud** [comment]
我们尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已修复
