### ISSUE TITLE
[Feature]【仪表板】仪表板背景增加透明背景设置

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5600]
**请描述您的需求或者改进建议.**
仪表板背景增加透明背景设置，效果如下图（仪表板叠到其他系统里，可以透过仪表板看到背景图片，红圈为单独的 DE 仪表板，非圈的为其他系统的图片素材）。
![image](https://github.com/dataease/dataease/assets/24768910/69eed70c-b2cb-433e-9aff-8e25746ec9e0)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论后再回复您。

**Comment by xuwei-fit2cloud** [comment]
仪表板背景颜色我们可以支持透明度设置，但仪表板背景图，我们短期内没有支持透明度的计划。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
