### ISSUE TITLE
[Feature]企业版试用到期后的提示修改建议

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5601]
**请描述您的需求或者改进建议.**

企业版试用到期后的提示，过于醒目，且只提示更新 license，给用户提示不友好；
参考建议：
1. 红色背景改为灰色或其他浅色；
2. 提示内容改为中文；
3. 增加说明，如：“企业版功能将会受限，数据可视化等社区版功能不影响使用，如果想取消该提示请在社区联系我们”等此类提示。

<img width="1364" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/f4a2b300-9a53-4f3c-920a-2b7cf068652f">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们考虑看看优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.9版本已支持，请更新版本。
