### ISSUE TITLE
外网怎么访问创建的公共链接呢

### ISSUE THREAD

**Issue by CyberPunkYu** [dataease/dataease#5602]
**请描述您的问题.**
仪表板创建的公共链接仅能本机访问，请问应该如何操作才能让其他主机也能访问，由于上面没有端口号，所以也不能用花生壳内网穿透
**部署方式**
Linux 单机部署 在线部署，开源版
![image](https://github.com/dataease/dataease/assets/85816973/f1a68d6e-50c3-4761-aba5-36bb2784d283)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，应该是把 DataEase 部署在了内网，然后需要在外网中访问。

建议您使用内网穿透工具，没有端口号，可能是用的默认端口号，您试试常用的默认端口号，希望能帮到您。

**Comment by CyberPunkYu** [comment]
我利用花生壳内网穿透，现在能正常访问dataease的服务界面了，
![image](https://github.com/dataease/dataease/assets/85816973/71ad3cd5-b839-40fa-85f1-4cd28dfc5742)
如果在手机端登录，虽然能正常访问，但是无法打开仪表板，显示仪表板为白色
![Screenshot_20230711_165755_com huawei browser](https://github.com/dataease/dataease/assets/85816973/9dd129c7-99b1-4eeb-bf43-affe62bd21bd)
电脑端能正常看到仪表板，但这个问题并不要紧，主要是对于其生成的公共链接
![image](https://github.com/dataease/dataease/assets/85816973/0efe1b3f-7e32-4418-baf6-d8d34be02c26)
仍无法访问，不知道是什么原因
![image](https://github.com/dataease/dataease/assets/85816973/d6b47291-f21b-4105-ad6a-aa385fe45d52)

**Comment by CyberPunkYu** [comment]
已经解决了，，问题出在花生壳只能用https服务，应该用http，所以我使用cpolar内网穿透后能成功访问，谢谢你

**Comment by itsukaa** [comment]
请问下怎么部署内网
