### ISSUE TITLE
水波图添加阈值

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#5603]
不同数值没办法显示不同颜色，希望水波图添加阈值功能
![image](https://github.com/dataease/dataease/assets/133861755/c9d05842-1cbd-4ebf-8ea7-c701f62216e9)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先看下水波图是否支持。

**Comment by xuwei-fit2cloud** [comment]
v1.18.12版本已处理，请升级到最新版本。
