### ISSUE TITLE
[Feature]【视图】报表增加可隐藏/展示列 （当前报表无法控制隐藏和展示列）

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5604]
**请描述您的需求或者改进建议.**
使用场景：根据图表做数据分析时，有时需要隐藏掉某个维度或指标列，同时其他的指标列会自动根据展示的维度列做汇总，目前DataEase只能在制作视图时指定维度指标，查看时不可操作
![image](https://github.com/dataease/dataease/assets/89771514/ff2e2e2d-54fd-4980-8dc9-387ab54d0b6c)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，仪表板更加侧重数据的可视化展示。看您的描述，是对数据进行自助式分析，这个在我们产品的长期规划中，近阶段暂时还没有规划去支持。
