### ISSUE TITLE
[Bug]antv 透视表，总计修改聚合方式后无用

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#5605]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**
114.0.5735.199（正式版本） （64 位）

**Bug 描述**
使用demo数据集中的全国各省gdp数据集，在仪表板中做透视表分析，对总计列设置聚合方式，默认是求和，切换总计的聚合方式，总计的值没有任何变化。

**Bug 重现步骤(有截图更好)**
![11](https://github.com/dataease/dataease/assets/26103277/330e23b8-5085-4e21-a7d7-c753372c4bd8)

**Comment by BBchicken-9527** [comment]
感谢反馈，如果你将数据列/维度也加上字段呢？是否是正确的，因为视图限制原因必须要两个维度都添加上字段才可以的；

**Comment by BBchicken-9527** [comment]
你好，不知道时候解决了你的问题呢？
