### ISSUE TITLE
[Feature]在县级添加乡镇地图数据文件会报错不支持 4 级行政级别

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5606]
**请描述您的需求或者改进建议.**
目前 中国地图支持下钻 ：中国地图-》省地图-》市地图-》县地图，如果用户继续在县级添加乡镇地图，则会报错提示超过 4 级，能否解除这个限制？最终实现： 中国地图-》省地图-》市地图-》县地图-》乡镇地图

用户自行准备了县级、乡镇地图文件，如果添加在 中国地图下一级是可以使用的。

<img width="600" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/d80fefaa-f753-4be9-8ab4-6c5855e6dcca">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，我们暂时先保持现状，支持常规的三级省市区。
