### ISSUE TITLE
[Feature]雷达图轴坐标可调节

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5607]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/101089844/e6d5bebb-6beb-4515-98d6-19ce07923c0e)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议很不错，我们增加一下自定义最小值、最大值的设置项。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
