### ISSUE TITLE
[Feature]视图缩略轴调整大小和样式

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5608]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/101089844/00bd2145-f3df-4feb-832e-3fb16ec3f391)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先看下图库是否支持。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，缩略轴目前暂时没有规划去调整大小和样式，建议使用antv的图，缩略轴的高度会小一些。
