### ISSUE TITLE
[Bug]Doris数据源，用于视图时小数字段报错

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#5609]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
Doris数据源，用于视图时小数字段报错
<img width="978" alt="image" src="https://github.com/dataease/dataease/assets/57552153/1dec3e6e-c71c-4148-85fc-1c3b34c03d28">
![image](https://github.com/dataease/dataease/assets/57552153/7afe5e52-fe04-447a-a6b6-f6e087b4c47d)

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/57552153/e3cc581c-22ab-4766-8bff-3c1bf7ad9282)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，方便问一下说一下你的连接方式吗？还有就是小数点长度是多少呢？

**Comment by s-phenix** [comment]
DECIMAL(20, 4)的数据类型

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快处理；

**Comment by gaozhan333** [comment]
同样也遇见这样的问题。不知道是什么原因。数据源是doris，数据类型是小数型。就报错。
