### ISSUE TITLE
建议Docker安装过程标准化，可以极大降低认知成本

### ISSUE THREAD

**Issue by HeyChiang** [dataease/dataease#5611]
**问题**
今天亲身体验的一遍安装过程，详细看过官网文档后，想在安装的时候指定存储目录，不知道在哪里改，加了微信群以后，说是在install.sh的opt里，结果也没有找到，为了了解项目需要翻看各种压缩包里的文件找答案，很繁琐。
![image](https://github.com/dataease/dataease/assets/12081334/3e90c99e-f938-4afd-b680-2f5f3be387e6)

**建议**
1.为了极大的降低新手开发部署的认知，和增加DataEase的上手成本，建议做到所有的文件都在一个`docker-compose.yaml`中，当开发需要定制化的时候，配置docker的环境变量即可。
2.在部署过程中，不同的容器需要执行的个性化脚本，应该在它归属的容器当中，这样对于错误发生的时候，也能快速定位是哪个容器的问题。

**国产软件就看你们的了！**

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，您可以参考一下installer工程里的install.conf文件，文件地址如下：
https://github.com/dataease/installer/blob/master/dataease/install.conf

这个是安装时的配置文件，如果需要调整配置，可以参考这个文件里的参数说明来进行调整。

由于我们会根据不同的部署方式启动不同的容器，所以目前还不会将所有docker-compose文件集中在一个文件中，望理解。
