### ISSUE TITLE
[Feature]SQL数据集表名支持变量

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#5612]
**请描述您的需求或者改进建议.**
例如，sql查询 select * from table的table希望可以支持变量，原因是：数据为一天一张表，我只要获取当前的数据，所以table是会变化的。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们暂时不规划表名支持变量，不同表的表结构不一致的话，会频繁的引发报错。
