### ISSUE TITLE
[Feature]通过配置让y轴的最小值直接取当前数据的最小值

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5614]
**请描述您的需求或者改进建议.**
![wecom-temp-126942-718d1c3c17153d55b9da112be424559e](https://github.com/dataease/dataease/assets/101089844/fa05b0c7-c7fd-4c91-9855-14500d73e170)
<img width="658" alt="image" src="https://github.com/dataease/dataease/assets/101089844/83692180-d535-463a-8a23-1fb36d73669f">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，由于折线图的纵轴需要根据最小值和最大值，来计算纵轴的每个刻度值，为了增强图表的可读性，刻度值一般为整十数、或者2、4、6、8结尾等的数据。

如果最小值来自某个指标汇总后的结果，那么在根据最大值、最小值，以及刻度数来计算刻度值的时候，刻度值会是一些除不尽的小数，或者一些可读性不强的数值等，从而降低了图表的可读性。

看截图中的图表，数据的波动是在一个固定的范围内，建议自定义固定的最小值、最大值。
