### ISSUE TITLE
[Feature]饼图柱状图只显示Top N，剩余的归到“其他”

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5620]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/101089844/a1d9d3b2-c8c2-4f8e-a42c-edc019c8f94b)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先讨论评估一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
