### ISSUE TITLE
[Feature]希望Hive数据源可以支持定时同步功能

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#5622]
**请描述您的需求或者改进建议.**
希望Hive数据源可以支持定时同步功能

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，Hive本身是一个数据仓库工具，用于大数据的抽取、转换、存储、查询分析等，因此如果对接Hive的话，建议用户使用直连模式。
