### ISSUE TITLE
[Question]给定一组散点坐标，无法通过dataease绘制出标准的散点图

### ISSUE THREAD

**Issue by qiruijiudian** [dataease/dataease#5623]
**请描述您的问题.**
在dataease中必须将一组散点坐标拆分成维度和值轴才能绘制出散点图，这样绘制出的散点图x相同的点y值会被汇总，不符合echarts的散点图设计理念。
我想了解的是我的使用方式有误，还是你们的设计方案就是如此。

**Comment by yayanpei-fit2cloud** [comment]
我们当前的设计如此，指标显示的是汇总的结果，而非明细。

感谢您的建议，我们先调研一下，再考虑后面的优化。

**Comment by qiruijiudian** [comment]
了解了，那目前有没有替代方案？比如进行插件开发增加符合要求的散点图？
类似于这种：
![image](https://github.com/dataease/dataease/assets/97870361/c70b0adf-80b5-424e-be19-ab0e0bb25d0f)

**Comment by yayanpei-fit2cloud** [comment]
视图是支持插件开发的，如果您这边比较紧急，可以先尝试插件开发。

**Comment by qiruijiudian** [comment]
了解了，谢谢
