### ISSUE TITLE
[Feature]AntV折线图标签和指标点的重叠处理

### ISSUE THREAD

**Issue by seanwwh** [dataease/dataease#5630]
**请描述您的需求或者改进建议.**

AntV折线图有时标签会跟指标点重合，导致指标点很难选中，建议优化标签位置或增加标签与指标点间距的配置功能，另外，ECharts折线图的指标不支持定义显示格式，对于百分比的标签显示不方便，所以没使用ECharts。
![image](https://github.com/dataease/dataease/assets/5187541/fc3d8e12-15d1-49e4-8f8e-b1440f636931)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先看下重叠的原因

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，echarts图库本身有自己的处理机制，改变了这个机制可能会引发其他的问题，因此我们暂时先保持现状。
