### ISSUE TITLE
[Bug]导入带有筛选框的模版，筛选框内无法更换数据集

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#5634]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
![img_v2_9d9a4d5f-ba24-4505-9c7e-9bda3ac0d39g](https://github.com/dataease/dataease/assets/85436572/81b036a5-b026-4cbd-a05e-6aef09d273bb)
原模板中带有筛选框，复用模板后筛选框内无法更换数据集

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，问题正在努力处理中；

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
