### ISSUE TITLE
[Feature] 公共链接打开看板并且进行视图联动时，清除所有联动默认不显示，需要鼠标悬浮在右上角才显示出来，建议进行优化。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5637]
**请描述您的需求或者改进建议.**
公共链接打开看板并且进行视图联动时，清除所有联动默认不显示，需要鼠标悬浮在右上角才显示出来，（并且不是特别好点，需要移到比较靠右）可否进行优化，与在 DataEase 内打开看板进行联动时样式一致。
<img width="1715" alt="image" src="https://github.com/dataease/dataease/assets/30063018/c6f3b29e-c0a0-484e-92f3-d3eaa746350f">
<img width="1366" alt="image" src="https://github.com/dataease/dataease/assets/30063018/d9ee8e9d-94f2-4531-a4f5-f7311e67e5ea">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
默认不显示是为了整体展示效果，不希望在展示仪表板的时候显示过多的操作按钮。
此需求暂不安排实现。
