### ISSUE TITLE
[Bug] 插件管理上传处存在任意文件覆盖风险

### ISSUE THREAD

**Issue by mdkk** [dataease/dataease#5641]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
任意

**Bug 描述**
插件管理上传处存在任意文件覆盖风险

**Bug 重现步骤(有截图更好)**
url:  http://127.0.0.1/api/plugin/upload
![image](https://github.com/dataease/dataease/assets/24806881/8e5a39ec-ccaf-496f-a5d8-ab585b405548)
![image](https://github.com/dataease/dataease/assets/24806881/29b3535f-6193-40ca-b01d-23f4bf728467)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，问题已修复，请等待新版本发布。
Duplicate of #5559

**Comment by BBchicken-9527** [comment]
目前问题已修复，可以下载最新版本体验，感谢你的建议与支持；
