### ISSUE TITLE
[Feature]数据里面有简称和全称两个字段，图表里面显示简称，视图悬浮提示显示全称

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5643]
**请描述您的需求或者改进建议.**
<img width="514" alt="image" src="https://github.com/dataease/dataease/assets/101089844/a1fa45ec-54e2-44fe-9587-97730b8a6aaa">
<img width="651" alt="image" src="https://github.com/dataease/dataease/assets/101089844/1f84e828-29a4-44aa-a096-4497c6310e79">

**Comment by hcff2c** [comment]
<img width="651" alt="image" src="https://github.com/dataease/dataease/assets/101089844/5b87cb44-cdac-4694-a74c-f53636c60ec8">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，您反馈的场景我们暂时没有规划去支持，提示中的维度，是来自制作视图的维度，没有用于制作视图的维度，无法显示在提示中。
