### ISSUE TITLE
[Bug] 定时同步数据集，带有计算字段的气泡地图下钻报错

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5644]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
定时同步数据集，带有计算字段的气泡地图下钻报错

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/45852479/a49db9e8-02b9-40b8-ba73-c7116aa35054)

另：
气泡地图编辑页面和查看页面气泡颜色不同
<img width="1023" alt="image" src="https://github.com/dataease/dataease/assets/45852479/5fdb01b2-119c-40f3-aa03-1eb6323734d3">
<img width="987" alt="image" src="https://github.com/dataease/dataease/assets/45852479/92504458-762a-438c-bc2a-c161bb5adcbc">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复

**Comment by BBchicken-9527** [comment]
感谢反馈，问题已修复可更新新版本体验
