### ISSUE TITLE
[Bug]计算公式中设置的数据格式不生效

### ISSUE THREAD

**Issue by lianzhuhuang96** [dataease/dataease#5645]
**DataEase 版本**
<html>
<body>

v1.18.8
--

</body>
</html>

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.在“视图字段管理”中创建计算字段，10/3=convert(10/3,decimal(3,2)
2.新增Antv/指标卡视图，将10/3作为要显示的指标
3.指标卡中显示的值为3.3333333333，没有按预期显示为3.3
![image](https://github.com/dataease/dataease/assets/113155578/96806d97-a88c-463d-b925-d3418443c31c)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你使用的数据库是什么呢？如果使用数据库管理工具将你的公式放进去的结果是否会保留两位？计算字段这里我们是没有做处理的，都是将你的公式直接交给driver去做处理的，如果平台上显示的是没有截断的哪我大胆猜测应该你使用其他工具也是这个结果，其实你可以尝试使用我们的数据格式功能；因为每个数据库的driver结果可能达不到统一，所以我们特意做了这里的功能你可以体验一下；
![image](https://github.com/dataease/dataease/assets/84372766/b38d12f2-1e24-4248-94ab-48af54f6a976)

**Comment by lianzhuhuang96** [comment]
MYSQL数据库

在mysql数据库查询  select convert(10/3,decimal(3,2))  能正常返回2位小数
![image](https://github.com/dataease/dataease/assets/113155578/ab9c1496-58b1-4bd6-9ada-2b121297aa55)

**Comment by lianzhuhuang96** [comment]
需要用echart视图，echart视图无法设置数值格式

**Comment by BBchicken-9527** [comment]
嗯..视图应该不会影响显示的，我们前端是没有对数据格式进行控制的。你是不是定时同步呢？如果定时同步数据会存到doris里面的；

**Comment by lianzhuhuang96** [comment]
> 嗯..视图应该不会影响显示的，我们前端是没有对数据格式进行控制的。你是不是定时同步呢？如果定时同步数据会存到doris里面的；

有定时同步的，每天9点、13点、15点更新

**Comment by BBchicken-9527** [comment]
嗯.... 定时同步数据是存放在doris中的，所以和你想象的在mysql的结果不一样；你可以进doris中去看看函数的结果，应该也是没有截断的；

**Comment by BBchicken-9527** [comment]
你好，不知道是否解决了你的问题，但由于你长时间没有进行回复我将关闭这个问题，如果你还有没有解决的问题可以随时将这个问题打开或重新提一个新的问题，还可以在我们的官方群中去了解，我们将会第一时间对你的问题进行处理，感谢你的建议与支持；
