### ISSUE TITLE
[Feature]折线图的辅助线支持选择使用视图计算列

### ISSUE THREAD

**Issue by seanwwh** [dataease/dataease#5647]
**请描述您的需求或者改进建议.**
折线图的辅助线请支持选择使用视图计算列
![image](https://github.com/dataease/dataease/assets/5187541/4aa6bc38-c8c4-40d1-bc36-d35e652c0943)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先内部讨论一下需求安排。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的关注和支持，视图计算列本身是数据集字段聚合后的结果，因此我们暂时不考虑进行支持。方便的话，也可以留言描述一下您的业务使用场景。

**Comment by seanwwh** [comment]
> 再次感谢您的关注和支持，视图计算列本身是数据集字段聚合后的结果，因此我们暂时不考虑进行支持。方便的话，也可以留言描述一下您的业务使用场景。

比如将平均值作为辅助线，Tableau是支持这个功能的。
