### ISSUE TITLE
[Bug]全屏预览时，筛选组件的下拉框显示错位了

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#5650]
**DataEase 版本**
18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
社区群反馈全屏预览时，他的筛选组件的下拉框显示错位了，我本地试了几次没有复现，还是先提个issue跟踪一下吧

**Bug 重现步骤(有截图更好)**
1.
![wecom-temp-43314-877d155febce6f74ee450dd4f105313f](https://github.com/dataease/dataease/assets/57552153/9a53b5cd-185c-4b6b-824d-48b6a063006b)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快处理；

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #5532
