### ISSUE TITLE
地图与词云或者选项卡联动

### ISSUE THREAD

**Issue by CyberPunkYu** [dataease/dataease#5652]
假设每个地区都拥有一个词云，地图和词云图放在两个视图中，能不能实现点击地图对应位置后，出现对应地区的词云这个功能。或者地区能和选项卡联动吗，选项卡选项名就是省份名，点击地图上地区后自动转到相应选项卡

**Comment by xuwei-fit2cloud** [comment]
ECharts图库里的地图是可以和词云图做联动的，关联上需要联动的数据集字段后，点击地图，可以联动词云图。
选项卡选项本身现在是不支持联动的，短期内也还没有相关支持计划。
