### ISSUE TITLE
[雷达图]希望每根轴线上的轴值是可以不同的，可以是正向的，也可以是逆向的

### ISSUE THREAD

**Issue by jiangzhaohong** [dataease/dataease#5653]
关于雷达图，希望：
1.不同轴线上的数值刻度，可以设置为不同（比如：轴线a：1,2,3,4,5 ；轴线b：60,120,180,240,300 等）
2.轴线上的刻度值，也可以设置越往外越小（比如：轴线a从内向外依次是：300,240,180,120,60 ）

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议我们已收到，雷达图暂时没有规划支持上述功能。
