### ISSUE TITLE
[Bug]日期范围组件 在手机端显示错位 没有适配移动端 无法选择日期

### ISSUE THREAD

**Issue by xiaoqiaotq** [dataease/dataease#5654]
DataEase 版本
18.8

运行方式(安装包运行 or 源码运行 ?)
安装包

浏览器版本
chrome

Bug 描述
日期范围组件 在手机端显示错位 没有适配移动端 无法选择日期

Bug 重现步骤(有截
![WX20230713-143120](https://github.com/dataease/dataease/assets/8088060/c9a832ec-0a0e-458e-bff3-820cf655b61b)
图更好)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前确实移动端的优化不够完善，我们会尽快想办法做出优化；

**Comment by xuwei-fit2cloud** [comment]
很抱歉，短期内还无法优化。
