### ISSUE TITLE
[Feature]视图计算字段可以拖入过滤器使用

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5656]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/101089844/81394f8d-62f3-4dcf-af0a-d418786c4cab)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，可以描述一下您的使用场景吗？

视图计算字段是数据集某个字段聚合后的结果，而视图的过滤器是对数据集的字段进行过滤，用字段聚合后的结果去过滤数据集，可能意义不大。
