### ISSUE TITLE
[Bug] Echarts 散点图 标签内容格式不正确

### ISSUE THREAD

**Issue by F1F88** [dataease/dataease#5657]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行（CentOS 7.5 + readme 中的一键安装）

**浏览器版本**
Chrome 版本 114.0.5735.199（正式版本） （64 位）

**Bug 描述**
**Echarts散点图** 中，设置 **标签** 的 **内容格式** 为 **{c}** 时
不仅显示了两次数据值，还额外显示了数据名

期望：只显示一次数据值，没有其他多余的信息

**Bug 重现步骤(有截图更好)**

![Img_230713_150821](https://github.com/dataease/dataease/assets/66011476/82d68316-032d-49da-a048-2df154480773)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们确认一下；

**Comment by BBchicken-9527** [comment]
你好我们确认了一下，这并不是标签格式错误了，而是echarts图表c显示会将横轴和竖轴也显示出来，所以你看到的就是：横坐标,纵坐标,value；

**Comment by F1F88** [comment]
这样显示效果不好看啊。。
是否有方法可以单独取出数据值呢？比如我想实现下图的效果
![image](https://github.com/dataease/dataease/assets/66011476/f9c4ac84-dc8d-4585-a613-bf0aecd8da45)

**Comment by BBchicken-9527** [comment]
好的，您的需求我这边已经记录了，我们内部讨论一下看看如果对此处做出优化

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，数值显示两遍的bug已经修复，请升级至最新的v1.18.12版本。
