### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by liaoxiaodongabc** [dataease/dataease#5659]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本 v1.18.7

**Bug 重现步骤(有截图更好)**
自定义字段无法拖入过滤器

**Comment by BBchicken-9527** [comment]
感谢反馈，受累你能详细说一下吗？你说的自定义字段是计算字段吗？

**Comment by BBchicken-9527** [comment]
嗯...如果你说的自定义字段是计算字段的话，目前视图计算字段是无法参与组件过滤的；希望我的回答能给你带来帮助，因为你太长时间没有回复我暂时先将这个问题关闭掉，若有什么问题你可以随时打开，感谢你的支持；
