### ISSUE TITLE
模板复用功能BUG

### ISSUE THREAD

**Issue by ShuXinRen12138** [dataease/dataease#5660]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
谷歌

**Bug 描述**
模板复用后添加联动功能不生效，复用模板是直接将Gson数据转成对象返回给前端，并没有使用linkageFilters做筛选

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前模版不支持联动，应该说是模版的联动与跳转是不带过去的；

**Comment by ShuXinRen12138** [comment]
复制的模板手动添加联动也是不好用的

**Comment by BBchicken-9527** [comment]
受累看一下手动添加模版数据和关联后，关联的弹窗中是否存在关联字段；

**Comment by ShuXinRen12138** [comment]
存在，无法关联的原因我认为是VIEW_DATA_FROM.TEMPLATE 不同类型走的不一样的处理了方法导致的，当走getChartDataInfo 方法时只是将数据取出并没用使用 linkageFilters 字段进行筛选

**Comment by BBchicken-9527** [comment]
你好，受累点击视图编辑按钮看一下你是否添加了数据，我们这边是没有出现你的这种情况的，VIEW_DATA_FROM.TEMPLATE就是区分数据走向的，所以我们推测你可能没有添加数据集导致的，模版是需要添加一个新的数据集的；

**Comment by ShuXinRen12138** [comment]
TEMPLATE类型没有做联动筛选呀
新建模板选择复用模板时在newPanel（）方法设置所有panelView 数据来源为template，我尝试设置为chart解决了个别字段null的问题后，复用模板设置关联可以正常使用

**Comment by ziyujiahao** [comment]
建议服用模板时 正常替换对应视图数据集 如果改后端数据 模板是当前系统导出的是可以的 但是跨系统导入模板时不可以的 还是建议按照正常流程操作吧 正常替换数据集
<img width="1355" alt="image" src="https://github.com/dataease/dataease/assets/42510293/89cddcee-32d8-4478-8a21-0e2a068a3bad">
