### ISSUE TITLE
多按钮功能

### ISSUE THREAD

**Issue by jiangyunhao** [dataease/dataease#5663]
**请描述您的需求或者改进建议.**
![28ab522fd4b9c4420b7c2fe18cac18b](https://github.com/dataease/dataease/assets/77140433/c131ba2c-43db-4b26-b663-ceb0d8ca552e)
现阶段只支持单个查询按钮关联筛选组件，但是有的需求是需要多个按钮，例如 “今日”、“本周”、“本月”等，单按钮功能无法满足需求

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，综合各种情况，现在的1.x版本设计的是支持单个查询按钮。我们规划2.0版本中支持多个查询按钮。
