### ISSUE TITLE
[Feature]仪表盘视图刻度值可以不显示

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5664]
**请描述您的需求或者改进建议.**
<img width="682" alt="image" src="https://github.com/dataease/dataease/assets/101089844/b15d33c1-fd08-4c3e-89c8-98d6a0870179">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，已经加入开发计划中。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
