### ISSUE TITLE
[Bug]仪表板主图切换后，辅助网格设置操作相反了

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5665]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行
![image](https://github.com/dataease/dataease/assets/89771514/a7409824-1e1b-4519-b5e6-bbbf6162ba71)

![image](https://github.com/dataease/dataease/assets/89771514/ca4ed4e4-9973-49f5-a2a6-ca974988354a)

**Comment by ZhaoQian1222** [comment]
保存自定义主题只保存了仪表板背景颜色，其他的视图颜色配色方案没有保存，但是切换系统内置的主题是可以替换掉视图的主题样式颜色的，这个是不是bug呢？

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下；

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
