### ISSUE TITLE
[Feature]多个过滤器字段支持选择“and”和“or”的关系

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#5666]
**请描述您的需求或者改进建议.**
![wecom-temp-135920-bda12a2998657ef8390972b615ac5e7d](https://github.com/dataease/dataease/assets/57552153/1abe5b6d-0e7e-4deb-a853-bbf0a41f8eaf)
就是他有好几个过滤器，类似 a>0 or b>0 or c>0这种条件，现在不支持选择多个过滤器之间的关系

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们暂时没有规划进行支持。这种复杂的过滤关系，建议新建SQL数据集，用原生的SQL，性能更好。
