### ISSUE TITLE
[Bug]SQL数据集中使用了left join，同时关联的SQL中使用了union，条件中带有参数变量时执行异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5668]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**Bug 描述**
SQL如下：

SELECT a.*,user.* from user left JOIN 
(
SELECT title,user,created_time from t_zhihu_answer
UNION 
SELECT title,user,created_time from t_zhihu_article) as a
on user.show_name=a.user
WHERE a.created_time BETWEEN '${start}' and '${end}'

异常信息：net.sf.jsqlparser.statement.select.SetOperationList cannot be cast to net.sf.jsqlparser.statement.select.PlainSelect

![image](https://github.com/dataease/dataease/assets/89771514/0fb52a71-bb3f-4d4a-a320-4982e3971eb2)

**Comment by ZhaoQian1222** [comment]
mysql数据源

**Comment by BBchicken-9527** [comment]
感谢反馈，目前参数化功能还在进一步的完善中，暂时不支持多层嵌套union all子查询+参数变量 查询等较为复杂的场景；
