### ISSUE TITLE
[Feature]视图中子维度增加自定义排序功能

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5671]
**请描述您的需求或者改进建议.**

子维度增加自定义排序功能
<img width="385" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/6a2e8165-cdb7-4fad-9156-63d98f922742">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，我们暂时还没有相关的开发计划。
