### ISSUE TITLE
[Feature]仪表盘js加载问题

### ISSUE THREAD

**Issue by pianZL** [dataease/dataease#5674]
在启动后首次加载仪表盘得某一个设计页面时，js加载过多，且有些慢，能否进行一些优化 加载展示速度

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，您的建议非常好，1.x受限于当初的设计，现在改动起来的工作量比较大，所以暂时没有规划去做优化。

我们开发人员已经注意到这个情况，所以在2.0的设计中进行了相关的优化，再次感谢您的关注和支持。
