### ISSUE TITLE
[Feature]指标卡视图，在正数的时候可以设置前面显示 + 号

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5675]
**请描述您的需求或者改进建议.**

希望 指标卡视图，在正数的时候可以设置前面显示 + 号

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，指标卡中可以添加图标，已经在需求池中，近期在开发其他的需求，所以可能还需要等待一些时间。
