### ISSUE TITLE
[Bug]筛选项数据获取超时，筛选项执行语句内原数据集字段被更改。

### ISSUE THREAD

**Issue by China-BlueFat** [dataease/dataease#5676]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
一键部署

**浏览器版本**
Edge

**Bug 描述**
我用仪表盘做了一张下单日报表，其中有两个筛选项。一个筛选项为日期，与数据集里面的下单日期关联了参数的，默认日期为当天。另一个筛选项为工厂，关联了数据集的工厂字段，没有默认值。我点到做好的仪表盘里面，选择需要查看的日期后，表正常显示。但是
我选择工厂那个筛选项的时候，里面没有值，过一会儿提示timeout。具体看图1。后来我从数据库那边查问题。发现是你们那个筛选项的语句有问题。我数据集里面的语句有一个条件是DATE_FORMAT(h.create_time,'%Y-%m-%d') = '${date}‘，在你们的语句里面变成了'BI’=‘BI'。具体看图2，这是你们那个筛选项的执行语句，红线框着的是我数据集里面的语句，但是黄框里面的语句跟我数据集里面的时间语句是不一样的。我尝试过更改日期格式，例如:Y-m-d，Y/m/d，Y-m，Y/m。改了之后都不行，我改过语句，把那句改成了 DATEDIFF(h.create_time,NOW()) = -1 也就是查询上一天的数据，那个筛选项就没有问题。而且我在另一个表也做了一个时间参数，那个表的格式是:Y-m，一切正常，这个表，除了日期那个字段，其他字段做筛选项都是timeout加载不出来。
**Bug 重现步骤(有截图更好)**
[1.](https://postimg.cc/jns12rCx)
![筛选项timeout](https://github.com/dataease/dataease/assets/26730667/0e59641f-ce0f-4c88-852a-5712965477bb)

[2.](https://postimg.cc/N2ccxVMS)
![筛选项语句](https://github.com/dataease/dataease/assets/26730667/e8c234e3-076a-4e4d-bdfa-1c9494b1095a)

[3.](https://postimg.cc/Ty1gRNTz)
![原语句](https://github.com/dataease/dataease/assets/26730667/ca50e9af-3393-4556-ad06-2136b26c6f74)

**Comment by BBchicken-9527** [comment]
感谢反馈，bi=bi是当参数化没有得到应用时候的替代的，受累看一下如果不使用参数化的情况是否会出现time out的情况能？还有受累问一下你的数据量是多少呢？多少个字段；

**Comment by China-BlueFat** [comment]
> 感谢反馈，bi=bi是当参数化没有得到应用时候的替代的，受累看一下如果不使用参数化的情况是否会出现超时的情况能？还有受累问一下你的数据量是多少呢？多少个字段;

刚才试了下，不使用参数，直接给值的情况下，那个筛选没有问题，不会timeout。数据量的话，如果我那个时间是每天的话，每天的数据也就五六十条左右。字段的话有7个字段。
 DATE_FORMAT(h.create_time,'%Y-%m-%d') = '2023-07-17'

**Comment by BBchicken-9527** [comment]
嗯... 数据量这么少应该不至于超时才对，你可以先将参数化去掉，然后不在sql中进行筛选，直接加过滤组建，先让业务跑起来，这里我们研究一下到底是什么情况，如果方便的话能不能给我你用的sql语句我按照你的问题去模拟一下；

**Comment by China-BlueFat** [comment]
> 嗯... 数据量这么少应该不至于超时才对，你可以先将参数化去掉，然后不在sql中进行筛选，直接加过滤组建，先让业务跑起来，这里我们研究一下到底是什么情况，如果方便的话能不能给我你用的sql语句我按照你的问题去模拟一下；

语句上面图里面就是完整的，你要也可以给你，不过，你没有那些数据库啊。

**Comment by China-BlueFat** [comment]
> 嗯... 数据量这么少应该不至于超时才对，你可以先将参数化去掉，然后不在sql中进行筛选，直接加过滤组建，先让业务跑起来，这里我们研究一下到底是什么情况，如果方便的话能不能给我你用的sql语句我按照你的问题去模拟一下；

SELECT o.VBELN 销售单号,
			COALESCE(d.name,s.name) 经销商名称,
      COALESCE(c.name,ovl.customer_person) 客户名称,
			CASE WHEN o.factory_contract_no like 'P%' THEN '彭州工厂'
      		 WHEN o.factory_contract_no like 'J%' THEN '荆门工厂'
      END AS 生产基地,
			CASE WHEN h.erp_order_no IS NULL THEN '未付款' 
				ELSE DATE_FORMAT(h.create_time,'%Y-%m-%d')
			END AS 付款时间,
			CASE o.OSTAT WHEN 5 THEN '生产中' 
				WHEN 10 THEN '已入库'
				WHEN 'created' THEN '上传订单'
				WHEN 'auditPlan' THEN '审图(方案)'
				WHEN 'auditHole' THEN '审图(审孔)'
				WHEN 'beforeEnd' THEN '确认下单'
				WHEN 'pushOrder' THEN '推单'
				WHEN 'orderOffer' THEN '报价'
				WHEN 'judgeEntry' THEN '判定录入'
				WHEN 'placeOrder' THEN '下单'
				WHEN 'orderReview' THEN '订单评审'
				WHEN 'confirmReceipt' THEN '确认收款'
				WHEN 'dealerConfirmation' THEN '经销商确认'
			END AS 订单状态,
			e.KWERT 金额
FROM order_vbak o
LEFT JOIN oppty_customer c ON o.customer_id = c.customer_no
LEFT JOIN order_push_history h ON o.factory_contract_no = h.erp_order_no
LEFT JOIN partner_dealer d ON o.shop_code = d.code
LEFT JOIN partner_straight_shop s ON o.shop_code = s.code
LEFT JOIN order_vbak_logistics ovl ON o.VBELN = ovl.vbeln
LEFT JOIN (SELECT KWERT, 
								CASE WHEN KNUMV REGEXP 'R|U|V|Z' THEN SUBSTRING(KNUMV,1,10)
									WHEN KNUMV REGEXP 'D|E|M|Y' THEN SUBSTRING(KNUMV,1,11)
								END KNUMV 
						FROM order_prcd_elements 
						WHERE KWERT != 0 GROUP BY KNUMV) e 
						ON o.VBELN = e.KNUMV
WHERE o.OSTAT != '1' AND DATE_FORMAT(h.create_time,'%Y-%m-%d') = '${date}'

**Comment by China-BlueFat** [comment]
> 嗯... 数据量这么少应该不至于超时才对，你可以先将参数化去掉，然后不在sql中进行筛选，直接加过滤组建，先让业务跑起来，这里我们研究一下到底是什么情况，如果方便的话能不能给我你用的sql语句我按照你的问题去模拟一下；

你们这个是这样运行的对吧，仪表盘里面插入一个视图。视图做成了表，表的数据就是直接执行我数据集里面的语句查询出来的。而筛选框，是将我们那个数据集那个语句做了嵌套查询。对吧！但是，每次查表的时候，视图里面的数据一下就出来了，那说明参数是执行了的，问题应该就在于筛选那个地方的语句那个条件变了。

**Comment by BBchicken-9527** [comment]
嗯嗯，我们验证一下；

**Comment by China-BlueFat** [comment]
还有另一个问题，我不知道是不是也和这个bug有关，还是筛选框。我举个例，在7月19日的订单里面，下单的客户有A，B，C三位。在7月18日的订单里面有D，E，F三位用户。我做一个日期筛选框，筛选了日期，跟数据集做了时间参数。然后再做一个筛选框，筛选客户的，客户的那个筛选框的语句应该是把我们查询某天的数据做嵌套查询。比如查询19号的，我们数据集的语句就应该是SELECT * FROM tab WHERE xdsj='2023-7-19'，查出来的客户有ABC三位。你们那个客户筛选框的语句则应该是SELECT kehu 
 FROM (SELECT * FROM tab WHERE xdsj='2023-7-19')，那么筛选框里也是只有ABC三位客户，三个文本。但是，实际是筛选框里面不止那三位客户，还包含了DEF这三位，所以实际是六个文本。

> 嗯嗯，我们验证一下；

**Comment by BBchicken-9527** [comment]
好的，我们统一确认一下，你用的数据源是mysql数据源吧

**Comment by China-BlueFat** [comment]
> 好的，我们统一确认一下，你用的数据源是mysql数据源吧

是的

**Comment by BBchicken-9527** [comment]
收到🫡

**Comment by China-BlueFat** [comment]
hello，这个事还有人处理吗？要不要连接我的数据库来试试呢！

**Comment by China-BlueFat** [comment]
> 收到🫡

请问还能帮忙查这个问题吗？可以提供数据库连接

**Comment by BBchicken-9527** [comment]
请问你在公众群中吗？方便我私下联系你；

> > 收到🫡
> 
> 请问还能帮忙查这个问题吗？可以提供数据库连接
