### ISSUE TITLE
[Bug]mysql数据源经常失效

### ISSUE THREAD

**Issue by jstbw** [dataease/dataease#5677]
**DataEase 版本**

1.18.8
**运行方式(安装包运行 or 源码运行 ?)**
docker安装包

**浏览器版本**
chrome

**Bug 描述**

用1.18.8连接了mysql 5.6数据源，前端对应的仪表板经常显示对应的数据源失效，到数据源里查看直接点击校验显示无效，点击编辑之后再点击校验才会校验成功。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/66759501/93f6d086-993f-49bd-9cf3-60991f26f53a)
![image](https://github.com/dataease/dataease/assets/66759501/6047a0f9-6040-4ce9-9219-960e22bb3b8a)

**Comment by jstbw** [comment]
并行的1.13连接同一数据源就不会出现这个情况

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，请问异常是什么呢？

**Comment by BBchicken-9527** [comment]
感谢你的反馈，由于你太久没有回复问题将在今天下午六点半左右关闭，若问题仍没有解决可再次他开我们会在第一时间进行解决；
