### ISSUE TITLE
修改install.conf的DE_DORIS_PASSWORD配置无效

### ISSUE THREAD

**Issue by HeyChiang** [dataease/dataease#5678]
**DataEase 版本**
dataease-v1.18.8-offline

**运行方式(安装包运行 or 源码运行 ?)**
使用install.sh脚本运行local模式安装

**浏览器版本**
版本 114.0.5735.134（正式版本） （64 位）

**Bug 描述**
修改install.conf的DE_DORIS_PASSWORD配置无效，登录8030后台和9030数据库登录还是旧密码：Password123@doris

**Comment by BBchicken-9527** [comment]
感谢反馈，目前我们是不允许修改内置的doris密码，这个配置项是配置外部doris使用的
