### ISSUE TITLE
[Feature]透视表视图导出 Excel，格式跟透视表一致（2.x 版本能否支持 ）

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5679]
**请描述您的需求或者改进建议.**
透视表视图导出 Excel，格式跟透视表一致，当前已知不支持，2.x 版本能否支持 ？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，按照透视表的格式导出至Excel，当前还不能给出明确答复。方便的话，可以描述一下您这边的使用场景吗？

**Comment by DuLianYong-Chinese** [comment]
跟领导汇报时，透视表相对来说很直观，领导一般不看明细数据，所以期望页面的透视表导出后，依然可以和页面一样，汇报时领导只看ppt或者word，并不会去系统上看

**Comment by yayanpei-fit2cloud** [comment]
建议您将仪表板生成一个公共链接，这样不用登录到系统中，直接打开链接就可以查看，也是非常便捷的。
