### ISSUE TITLE
[Feature]关于时间范围过滤组件的需求

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5680]
**请描述您的需求或者改进建议.**
新加一个时间过滤组件，支持选择时间维度：按年、按月、按季度、按周
点击不同维度后，右侧的选择时间组件跟随变化，最终目的是为了时间范围选择的灵活性
![image](https://github.com/dataease/dataease/assets/89771514/f8f88a99-02db-4587-b8c1-479905347f95)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们暂时不考虑支持。时间范围组件是需要用户选择起始日期的，当前的日期选择面板左侧内置了本周、本月、本季度等，是为了更便捷的去选择起始日期，因此右侧还是保持日期选择更合适。
