### ISSUE TITLE
[Feature] Echarts横向柱状图排序，降序应该是从大到小，现在实际是从小到大

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5681]
**请描述您的需求或者改进建议.**
Echarts横向柱状图排序，降序应该是从大到小，现在实际是从小到大
AntV视图是正常的
![image](https://github.com/dataease/dataease/assets/89771514/120cc813-ae84-4c13-bf93-06d6c55fbbd3)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，每个图库的排序机制不太一样，建议您使用antv图库。
