### ISSUE TITLE
[Bug] Local 模式下，两个 Excel 数据集创建关联数据集，数值类型的字段会识别为文本

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5684]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 114.0.5735.198（正式版本） (arm64)

**Bug 描述**
 Local 模式下，两个 Excel 数据集创建关联数据集，数值类型的字段会识别为文本

**Bug 重现步骤(有截图更好)**
1. Excel 数据集如下所示，商品数据表里，进货价，零售价均为数值类型。
<img width="1475" alt="image" src="https://github.com/dataease/dataease/assets/30063018/50e004d6-92a4-49f7-8542-6ac1db430e54">
2. 关联数据集编辑页面，显示为数值。
<img width="1475" alt="image" src="https://github.com/dataease/dataease/assets/30063018/1dbe9d93-b258-494c-beaa-47227ca435e7">
3. 保存后查看，发现字段类型变成了文本。
<img width="1475" alt="image" src="https://github.com/dataease/dataease/assets/30063018/e09ac90e-9279-4ac5-ad88-765d331f6578">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下；
