### ISSUE TITLE
[Feature] 明细表视图，SQL Server 数据源分页问题优化建议

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5685]
**请描述您的需求或者改进建议.**
**问题描述：**
SQL Server 数据源在不设置 order by 字段的情况下，无法设置分页信息，因此 DataEase 明细表目前对于 SQL Server 数据源做的是前端的假分页，在数据量比较大的情况下前端页面非常容易崩溃。
**优化建议：**
明细表视图一般都会设置排序字段，在设置了排序字段的情况下，可以将分页信息拼接进查询 SQL，做真分页。在不设置排序字段的情况下，依然按照现在的逻辑，前端做假分页。

**Comment by ziliang-wan** [comment]
补充下，doris 的分页是否也可以使用这种方式来处理。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，理论上是可行，我们需要先讨论一下。
