### ISSUE TITLE
[Feature]在前端代码中 你们使用了tinymce 同时也使用了@tinymce/tinymce-vue

### ISSUE THREAD

**Issue by zcx992132258** [dataease/dataease#5686]
![image](https://github.com/dataease/dataease/assets/54138798/586690da-b4d3-4833-9719-267cb06dfb62)
你们在一些组件中单独引入了  一些组件没有单独引入 RemarkEditor.vue例如这个组件就没有引入，如果加载顺序出现问题的话就会
![image](https://github.com/dataease/dataease/assets/54138798/8cf56b0b-c022-4bc6-a035-e240e261c912)
样式丢失的问题 希望你们进行一下全局引入这样的功能或者参考一下官方文档的写法

**Comment by zcx992132258** [comment]
你们是否考虑按照官方文档来编写呐？
![image](https://github.com/dataease/dataease/assets/54138798/e593b074-29c5-4034-bf8a-6079c0dc67e0)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经fixed，预计在下个小版本发布。
