### ISSUE TITLE
[Feature]下拉模式的明细表没有数据条数总计

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5688]
**请描述您的需求或者改进建议.**

明细表翻页模式有统计数据条数，下拉模式没有统计数据条数，能否加上数据条数统计？

<img width="850" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/61c3ba2e-3193-4a02-8d9c-bad68c165d7f">

<img width="841" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/1eff1f66-c52d-4fd8-a9f0-a1dc77243a35">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，我们暂时没有规划支持该功能，待收到更多用户的需求后再进行规划。
