### ISSUE TITLE
[Feature]数据源支持 SSH 隧道功能

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5691]
**请描述您的需求或者改进建议.**

数据源创建时，DataEase 可能无法直接访问业务环境数据库，可以通过 SSH 隧道，使用业务边缘的一台服务器作为跳转机跳转到 业务数据库，如 Matabase 的截图：
<img width="1001" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/726d3ce6-ab2e-418e-a62e-c5479f3cb532">
ssh 隧道的功能说明：
https://www.metabase.com/docs/v0.46/databases/ssh-tunnel.html

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，已加入开发计划中。
