### ISSUE TITLE
[Feature] 希望表格组件能有tooltip功能

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5693]
**请描述您的需求或者改进建议.**
希望表格组件能有tooltip功能
<img width="839" alt="image" src="https://github.com/dataease/dataease/assets/45852479/20cc5eb6-9e23-4020-b597-2ef7b65c0e28">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
