### ISSUE TITLE
明细表指标希望添加动态阈值

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#5694]
明细表指标超过某个平均值（根据结果集动态计算出来的值，不是固定的）想让这行或者其中某列红色显示
![wecom-temp-14422-d415567497ea83e67a6549ba0127e910](https://github.com/dataease/dataease/assets/133861755/7d64be4c-b2f2-430b-833b-432d867daf57)

**Comment by yayanpei-fit2cloud** [comment]
重复需求，请见issue：https://github.com/dataease/dataease/issues/5695
