### ISSUE TITLE
[Feature]明细表阈值设置能否支持动态值

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5695]
**请描述您的需求或者改进建议.**

如下图，明细表阈值设置，可否设置与一个动态值来对比，这个动态值可以是视图计算字段，
比如，视图字段求了平均数，可以将平均数的字段，放到这里。
<img width="1072" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/21416637-6411-4291-9c79-df6c5e531391">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
