### ISSUE TITLE
[Feature]数据集字段管理每修改一个字段刷新一次，希望只在最后提交刷新一次

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5696]
**请描述您的需求或者改进建议.**
数据集字段管理，修改一个字段名称，切换下一个字段名称页面就会刷新；
在数据量较大的场景，刷新时间会变长，希望修改完只提交一次。
<img width="1063" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/0a457f17-66e4-42e4-b4b9-5ccf4a86fe99">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要讨论后再进行回复。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，还是保持实时刷新的机制，我们优化一下后台的校验规则，缩减刷新时间。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
