### ISSUE TITLE
[Feature] 外部参数配置时，对于某一参数下已经配置的视图，添加参数联动字段选择视图时不重复出现

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5697]
**请描述您的需求或者改进建议.**
外部参数配置时，对于某一参数下已经配置的视图，添加参数联动字段选择视图时不重复出现
<img width="919" alt="image" src="https://github.com/dataease/dataease/assets/45852479/1e0f134c-7c6a-443d-9cd6-6a1a5769ef4a">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议很不错，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
