### ISSUE TITLE
[Feature] 配置颜色，在没有数据的时候识别不到

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#5698]
视图配置颜色，有数据时才会识别到修改颜色，一旦没有数据就识别不到，只能等有数据以后再去修改，希望可以在没数据的时候也能配置对应的样式
<img width="1295" alt="Pasted Graphic" src="https://github.com/dataease/dataease/assets/133861755/ff20aa9b-8f17-435d-85f9-774333b39f24">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，目前暂时没有规划进行支持，待收集更多用户的需求后再进行下一步的规划。
