### ISSUE TITLE
[Feature]从模版市场中多选一些做成仪表板主题

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5699]
**请描述您的需求或者改进建议.**
多做一些仪表板主题，目前模版主题有点少，但非常好用，做完视图布局后，直接选择主题，背景、视图、色系、透明度一键更换完成，比起选择模版--应用--修改数据集 -- 调整视图，方便多了。
<img width="1439" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/e427cc41-4e95-4469-8f24-ada510c38e36">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，后面我们会再拓展一些主题，您也可以修改现有主题，从而生成新的主题。或者在新建仪表板时，选择喜欢的模版，使用模版新建仪表板。
