### ISSUE TITLE
[Bug]时间组件无法控制选项卡第二页及第二页以后的数据过滤

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5700]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome、火狐

**Bug 描述**
时间组件无法控制选项卡第二页及第二页以后的数据过滤
<img width="754" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/06dd4ba2-8cf3-4107-ae27-5e0d386957a9">

**Bug 重现步骤(有截图更好)**
1.仪表板准备，选项卡、添加三个视图，添加时间过滤组件，默认动态时间本周
2.仪表板预览状态，选项卡默认显示第一页，切换时间过滤，选择本月
3.选项卡第一页显示本月数据，第二页、第三页不显示过滤后的数据。

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，目前正在努力处理中，请耐心等待；

**Comment by BBchicken-9527** [comment]
感谢反馈，目前问题已修复，可以下载最新版本体验；
