### ISSUE TITLE
[Bug]Oracle 数据库 timestamp 类型字段会被识别为文本类型，且修改为时间类型时报错

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5701]
**DataEase 版本**
V1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 最新

**Bug 描述**
Oracle 数据库 timestamp 类型字段会被识别为文本类型，且修改为时间类型时报错

**Bug 重现步骤(有截图更好)**
1. 数据库字段类型如图
![image](https://github.com/dataease/dataease/assets/30886198/8a70b5fb-8b5a-4802-b9f3-c624a1618fd5)
2. timestamp 字段会被自动识别为文本类型，当切换为时间类型时会报如图错误
![image](https://github.com/dataease/dataease/assets/30886198/0c531045-05cd-40c4-a73f-9dd290899fb3)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下；

**Comment by BBchicken-9527** [comment]
感谢反馈，确实在数据库数据集直连的情况下会出现这个问，我们修复一下，麻烦先使用sql数据集可以暂时规避这个问题；

**Comment by BBchicken-9527** [comment]
问题已修复，可以下载新版本体验；
