### ISSUE TITLE
[Feature] 复用视图相关优化

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5703]
**请描述您的需求或者改进建议.**
复用视图时能否增加选项（是否保留原视图的样式），因为复用视图有可能是想用已有的样式来简化工作量

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已加入开发计划中。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
