### ISSUE TITLE
[Question]  在local部署模式下，为什么还需要MySQL数据库

### ISSUE THREAD

**Issue by HeyChiang** [dataease/dataease#5704]
**请描述您的问题.**
请教一个问题，在local模式下，完全可以使用Doris去创建一个数据库，为什么还要运行一个MySQL的容器？

**Comment by liuboF2c** [comment]
Local 模式 Doris 只是用来存储抽取的业务数据。MySQL 是用来存储 DataEase 自己的数据，比如你的仪表板配置、数据集字段配置、数据源链接信息。只有定时同步的数据集里的数据和 Excel 数据集的数据才会存储在 Doris 中。

**Comment by HeyChiang** [comment]
为什么不把MySQL的数据一起放入Doris，有什么影响吗？

**Comment by HeyChiang** [comment]
我觉得多了一个MySQL又需要多维护一样东西了

**Comment by liuboF2c** [comment]
> 我觉得多了一个MySQL又需要多维护一样东西了

建议你了解下数据库的不同类型以及适用场景

**Comment by HeyChiang** [comment]
MySQL的MVCC模式是很好的，但我觉得还是没必要多一个MySQL的存在，这种数据分析平台不存在并发，就算有用程序完全可以做到，我觉得多一个MySQL的设计很糟糕。（当然，用MySQL是一种比较省事的做法，避免多写代码）
