### ISSUE TITLE
[Feature]分享仪表板可以选整个目录

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5713]
**请描述您的需求或者改进建议.**

目前仪表板分享只能分享单个仪表板，能否对整个目录进行分享？
<img width="420" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/ffb74a0e-6274-40f2-b7db-7db32bb37bc7">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，暂时没有规划进行支持。如果有多个需要分享，建议您通过授权方式，将查看权限授予其他用户。

**Comment by mfanoffice** [comment]
> 感谢反馈，暂时没有规划进行支持。如果有多个需要分享，建议您通过授权方式，将查看权限授予其他用户。

分享和授权可以实现同样的效果，但功能概念不一样，分享目录是在分享额基础上，增加分享目录的功能
