### ISSUE TITLE
[Bug]AntV视图标题字体设置无效

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5721]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/89771514/edc3ad0e-d1f8-4c8b-b270-d3c8a01b4887)

**Comment by BBchicken-9527** [comment]
感谢反馈， 选择字体需要电脑中的字体库存在相同的字体的；你用的是mac还是windows呢？如果你使用的是mac需要你字体库中字体名称与平台设置的是一致才可以；
