### ISSUE TITLE
[Feature] 透视表汇总相关优化

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5722]
**请描述您的需求或者改进建议.**
1.允许指定列进行小记、总计
2.小记、总计方式自定义

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，回复请见如下：

允许指定列进行小记、总计。S2图库不支持，暂时先保持现状。
小记、总计方式自定义。 已加入开发计划中。
