### ISSUE TITLE
[Feature]定时报告邮件，支持设置是否发送仪表板截图

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5724]
**请描述您的需求或者改进建议.**
场景：有的仪表板中全是分页的表格，定时报告只需要发送明细的数据excel即可，此时发送的截图中数据不全，并没有什么意义

所以希望定时报告邮件，支持设置是否发送仪表板截图

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
您好，这个地方我们暂时还不考虑进行调整。
