### ISSUE TITLE
[Feature]联动、跳转、下钻的有效区域希望大点

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5728]
**请描述您的需求或者改进建议.**
联动、跳转、下钻的有效区域希望可以调整到标签；
场景如下：数据特别小时，柱状图柱子很小，下钻、联动、跳转都不放便选择点击，可以把生效区域扩展到标签，或扩展到另一侧的横轴纵轴。

![图片](https://github.com/dataease/dataease/assets/48307752/72759529-a10a-47b4-81f1-4e24a7ee8c2f)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先记录并讨论一下。

**Comment by xuwei-fit2cloud** [comment]
新版本支持了鼠标刷选功能，可以通过刷选放大区域。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
