### ISSUE TITLE
[Feature] 希望视图表格能支持单元格超链接跳转

### ISSUE THREAD

**Issue by Register2016** [dataease/dataease#5732]
希望将来能支持对视图Table表格的单元格字段进行超链接设置，通过点击超链接能跳转到其他视图或仪表板，并且超链接可以携带自定义参数值，携带的参数值可以作为目标视图的动态参数进行传参。
需求场景： 统计公司开发人员的相关数据指标，例如任务，完成率，bug等等，通过表格可以看到整体情况。但是想看某个人的数据历史变化趋势，希望能点击员工单元格，跳转到员工历史数据变化趋势视图或者仪表板查看。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
目前的版本应该是可以支持您提的需求的，具体用法您可以在我们的社区交流群里咨询一下技术支持。
