### ISSUE TITLE
[Feature] 流程图

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5733]
**请描述您的需求或者改进建议.**
希望可以支持流程图
https://antv.alipay.com/zh-cn/g6/3.x/demo/flow/node-flow.html
附：本质是关系图，运用了dagre.graphlib.Graph算法得到规整化的关系图

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论并调研一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，我们规划是优先支持数据分析类的图表，关系类的图表当前暂时没有规划进行支持。
