### ISSUE TITLE
[Feature]符号地图按指定维度配置颜色

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5735]
**请描述您的需求或者改进建议.**

目前符号地图的标点只有单一颜色，能不能根据指定的维度，进行颜色划分？
<img width="352" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/81b1624d-ed24-4001-a63a-d6c335e7525b">

<img width="1101" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/e9bfacbe-c6a1-4e0d-b0f4-fdb3cce9fb5c">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下实现方式。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
