### ISSUE TITLE
[Bug] wap端访问仪表盘页面跳转异常

### ISSUE THREAD

**Issue by cdq502** [dataease/dataease#5740]
**DataEase 版本**
v1.18.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行（docker）

**浏览器版本**
chrome版本 114.0.5735.201（正式版本） / Firefox 115.0.2 (64 位) / Microsoft Edge 版本 114.0.1823.82 (正式版本)

**Bug 描述**
使用分享链接手机端打开大屏，页面会调用一个接口 /tempMobileLink/ 获取面板数据，该URL会直接302到http。
我当前是通过https访问，它会重定向地址是一个http，浏览器console会报 Mixed Content 异常。

**Bug 重现步骤(有截图更好)**
1. https://{mydomain}/app.html#/pages/tabBar/home/index
2.F12, 直接爆出：
Mixed Content: The page at 'https://{mydomain}/app.html#/pages/tabBar/home/detail?detailDate=%257B%2522id%2522%253A%25229f4a216c-26dc-11ee-8ef3-351f3e8e834c%2522%252C%2522title%2522%253A%2522Meboom%25E4%25BA%25A7%25E5%2593%2581%25E8%25BF%2590%25E8%2590%25A5%25E6%2595%25B0%25E6%258D%25AE%25E5%2588%2586%25E6%259E%2590%2522%252C%2522index%2522%253A0%257D' was loaded over HTTPS, but requested an insecure frame 'http://{mydomain}/#preview/9f4a216c-26dc-11ee-8ef3-351f3e8e834c'. This request has been blocked; the content must be served over HTTPS.

这个{mydomain}我置换了地址，不方便提供。

![image](https://github.com/dataease/dataease/assets/133115516/225276b4-a5df-4688-b895-82b99015cd37)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，但应该是nginx问题，建议你参考我们的官方文档配置一下nginx，若还是有部署的问题也可以加入我们的官方微信群，会有人及时对你的疑问回复的；https://dataease.io/docs/installation/HA/nginx_installation/

**Comment by cdq502** [comment]
单只有手机端访问app.html才出现此问题，NGINX已经设置80强制跳转至443.
服务启动用得8080端口，Nginx启动用了，80及443端口。只有这个查阅面板功能才会访问http。
我也用了安卓，苹果手机测试，也是如此。麻烦再测试，或者需要我提供什么资料呢？

**Comment by cdq502** [comment]
已成功，是这段配置生效，
```
add_header X-Upstream $upstream_addr;
```
