### ISSUE TITLE
[Bug]新建数据源，数据库名称带空格校验失败

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5748]
**DataEase 版本**
1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/89771514/57e19f31-bef8-4a32-9af3-58ca8ad05c5b)

**Comment by BBchicken-9527** [comment]
目前问题已修复，可以下载最新版本体验，感谢你的建议与支持；

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复；

**Comment by ZhaoQian1222** [comment]
数据库名不支持有特殊符号-
![image](https://github.com/dataease/dataease/assets/89771514/30ee4dc9-f266-4d7e-97e1-954eaf35bb81)

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
