### ISSUE TITLE
[Bug] 仪表板下存在看不见的视图

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5752]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
仪表板下存在看不见的视图

**Bug 重现步骤(有截图更好)**
1.仪表板共6个视图
<img width="1156" alt="image" src="https://github.com/dataease/dataease/assets/45852479/b0d25533-0e70-48a4-9ce1-ae39f29ff937">
<img width="1121" alt="image" src="https://github.com/dataease/dataease/assets/45852479/94bda218-092e-4598-8433-d0488cace717">
2.s数据库能查到的有10个
<img width="820" alt="image" src="https://github.com/dataease/dataease/assets/45852479/88623632-f3ba-4561-899f-faaec7fce4a3">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下

**Comment by BBchicken-9527** [comment]
查看发现因为模版中存在宽度为0的视图导致，关闭此问题；
