### ISSUE TITLE
[Feature] 支持配置密码修改策略

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5753]
**请描述您的需求或者改进建议.**
支持配置新用户登录时强制修改密码，避免用户不修改密码带来的一些数据泄露风险。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，默认密码在登陆后系统右上角会弹出提示，提示用户修改密码的，因此暂时没有规划进行支持。
