### ISSUE TITLE
[Bug] websocket 的 ws_url 上下文写死为 /，对于使用了其他上下文（如 /de-api）的 backend 会 404

### ISSUE THREAD

**Issue by calvinit** [dataease/dataease#5754]
**DataEase 版本**
1.18.x

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome 版本 115.0.5790.102（正式版本） **(x86_64)**

**Bug 描述**
以下这个 JS 文件中 ws_url 写死了，这对于 backend 添加了上下文 context-path 的接口请求会 **404**！
[frontend/src/websocket/index.js](https://github.com/dataease/dataease/blob/dev/frontend/src/websocket/index.js)

**Bug 重现步骤(有截图更好)**
![dataease_issue_jietu](https://github.com/dataease/dataease/assets/27403411/7f8f36b4-6743-429b-b18a-0319cad63523)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下；

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
