### ISSUE TITLE
[Bug]升级到1.18.9版本后，SQLserver2008版本数据源报错

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#5755]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/85436572/3e75f8b0-73b2-4526-af6c-c826e385ce8f)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下；

**Comment by orwenxiang** [comment]
此问题是因为升级JDK 版本到11后，JDK 的安全配置禁用了TLS1.0 协议，具体参考 $JAVA_HOME/conf/security/java.security 文件的 jdk.tls.disabledAlgorithms 配置项

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
