### ISSUE TITLE
请问下如何格式化 ES 数据源中时间字段

### ISSUE THREAD

**Issue by MoonBottle** [dataease/dataease#5756]
**请描述您的问题.**
![image](https://github.com/dataease/dataease/assets/12904505/02940cab-962a-4416-8072-fa095bd5f25a)

es 数据集中又 alarmTime 这样的一个字段，请问下怎么格式化成 年月日 这种格式呢

dataease 版本 v1.18.8

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，直连的数据源数据不保存在DataEase这边，因此无法做格式的转换，建议使用sql数据集，在sql语句中用日期格式函数进行转换。

**Comment by MoonBottle** [comment]
https://zhuanlan.zhihu.com/p/592653039

请问下为啥这个教程里的可以，版本不一样么？
