### ISSUE TITLE
[Bug]表格行高跳变

### ISSUE THREAD

**Issue by aihpossssssssssssssssssssssss** [dataease/dataease#5757]
**DataEase 版本**
1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
火狐 90.0

**Bug 描述**
表格列较多时，表格配置为自动换行，如果未显示的列中有一些较高的行，已显示的列中行高都比较小，那么在滑动条往右滑动至行较高的列时，会出现跳变的现象。

**Bug 重现步骤(有截图更好)**
1.配置一个多列的表格，设置自动换行；
2.当前显示列的行高较低，后面存在行高较高的行；
3.滑动条向右拖动；
![图片](https://github.com/dataease/dataease/assets/39285782/3f9617eb-7647-41f6-b3fc-6a8544b2e7c8)
![图片](https://github.com/dataease/dataease/assets/39285782/f9c4e47d-ef38-49ed-9122-d9820cc95ae9)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的这个问题，不过确实有可能出现这种情况，本质是因为没办法知道具体的行高导致，因为此处自动换行是前端计算的，不知道具体高度时前端无法计算一个准确的高度用于展示，目前我们没有更好的方式去解决这个问题，因为文本的长度、表格的宽度这些我们都是没办法控制的，建议你文本高度尽可能一致并且尽量固定在一个宽度，给你带来不好的体验实在不好意思，后续我们会尽可能完善此处功能；
