### ISSUE TITLE
[Feature] 系统管理-任务管理-数据同步菜单支持排序

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5760]
**请描述您的需求或者改进建议.**
系统管理-任务管理-数据同步菜单支持排序
![image](https://github.com/dataease/dataease/assets/45852479/de513c26-aaca-4a83-8744-6958d4f6fbbf)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
