### ISSUE TITLE
[Bug] 仪表盘点击编辑，如页面没有加载完，一直在loading 点了保存，会保存一个空白页面。

### ISSUE THREAD

**Issue by yunfeng1993** [dataease/dataease#5761]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**

实际上  标红框的是由内容的  加载慢 加载不出来。。因为链接的是HIve 数据库
**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，能麻烦详细描述一下吗，嗯.... 不确定是什么情况下的加载导致可以保存；
