### ISSUE TITLE
[Feature]DE用户创建的时候，用户ID能否以纯数字输入，因为有很多情况下想把员工的工号作为ID来输入

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#5763]
**请描述您的需求或者改进建议.**
目前DE在创建用户的时候不支持用户ID为纯数字，能否进行支持
<img width="878" alt="image" src="https://github.com/dataease/dataease/assets/45967454/32be0ecf-26c4-4ffc-8eb7-97c133bda604">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
好的，我们后期优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
