### ISSUE TITLE
[Feature]视图联动与下钻功能能否同时支持

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#5764]
**请描述您的需求或者改进建议.**
<img width="548" alt="image" src="https://github.com/dataease/dataease/assets/45967454/e6925b09-5fd9-419c-a650-f367c62b912f">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经放置在需求池中，当前暂时还没有规划进行支持。
