### ISSUE TITLE
[Bug]  DataEase  报超时，是否能配置4分钟以上timeout时间

### ISSUE THREAD

**Issue by ops120** [dataease/dataease#5765]
**DataEase 版本**

v1.18.8  

CH 20.7.2.30

因为量大，SQL 查询时间都很长 现在 dbeaver 常规查询4分钟左右
现在需求是超时能到10分钟

**运行方式(安装包运行 or 源码运行 ?)**
LINUX 单机  安装包

**浏览器版本**
chrome  109.0.5414.149

**Bug 描述**
clickhouse 执行超时，已修改系统配置为 300S 

**Bug 重现步骤(有截图更好)**
1.  修改参数到 6000S
![image](https://github.com/dataease/dataease/assets/49262338/11948333-b067-4428-8649-36929f8fdd3f)

2. 执行超过100S 超时
![image](https://github.com/dataease/dataease/assets/49262338/94577e0c-1004-411b-b780-9981b51de9f1)

3. 按图修为改 300S ，依然和2 同样的错
![image](https://github.com/dataease/dataease/assets/49262338/436975ba-5a60-4d49-bee7-971d01deef36)

**Comment by BBchicken-9527** [comment]
感谢反馈， 我们核对代码目前没看出来什么问题，请问你开源了吗？

**Comment by ops120** [comment]
开源是啥意思，你们是否可以找个查询 时间超过100S的数据库试试，

**Comment by xuwei-fit2cloud** [comment]
我们处理一下。

**Comment by tjlygdx** [comment]
执行超过100S 超时时，看一下后台日志有没有报错？有的话，贴出来看看

**Comment by xuwei-fit2cloud** [comment]
无法获取有效反馈，暂时关闭。
