### ISSUE TITLE
[Feature] 关于Mysql数据集动态参数改进意见

### ISSUE THREAD

**Issue by Register2016** [dataease/dataease#5767]
1. 希望动态参数能支持到表，这样可以达到分表的效果，目前只能支持where条件后的动态传参。
2. 希望动态传参的逻辑能优化:
        2.1 动态参数如果设置了默认值，就用默认值替换占位符。
        2.2 动态参数如果没有设置默认值，就根据参数类型以类型默认值替换占位符或者不做处理，查询不出数据就查不出得了，待仪表视图实际传参的时候再出数据即可，之前是用 1< 2替换整个动态参数，现在是 BI=BI，逻辑有点奇怪。
3. 动态参数默认全局生效，或者干脆取消近编辑时生效。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复请见如下：
1、动态参数暂时没有计划支持到表名。
2、如果没有默认值，即不参与过滤，查询全部数据。如果不做处理，那么在编辑sql语句时，无法预览sql查询结果，无法预知sql语法是否正确，以及sql执行结果是否符合预期。
3、暂时不做修改，由用户来选择生效范围，适应不同的应用场景。
