### ISSUE TITLE
[Bug] 同时对视图配置下钻跟联动时，联动触发的位置不准确

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5768]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 114.0.5735.248（正式版本） (arm64)

**Bug 描述**
同时对视图配置下钻跟联动时，联动触发的位置不准确，如设置商品大类->商品小类—>商品名称的钻取，再对商品小类设置联动，在钻取到商品小类时点击可进行联动，但是到了商品名称，联动依然存在，此时联动应该不存在。

**Bug 重现步骤(有截图更好)**
1. 如图所示，柱状图与明细表，设置好柱状图的三层钻取（商品大类->商品小类—>商品名称），以及商品小类的联动
<img width="1268" alt="image" src="https://github.com/dataease/dataease/assets/30063018/3a3e08ae-f0b8-4604-994e-9ef5a23208ea">
<img width="1298" alt="image" src="https://github.com/dataease/dataease/assets/30063018/f03a5f1c-6270-402c-bc91-a46790f66346">
2. 当钻取到商品小类时，点击出现联动的按钮，此时符合预期。
<img width="980" alt="image" src="https://github.com/dataease/dataease/assets/30063018/8056d39c-3cdc-4e6e-b7da-cbe12ad62dcf">
3. 当继续钻取到商品名称时，点击仍然会出现联动的按钮，此时不符合预期。
<img width="1295" alt="image" src="https://github.com/dataease/dataease/assets/30063018/0de17077-d7a8-4e88-92b7-00979456c5dc">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下；

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
