### ISSUE TITLE
[Bug] 明细表联动视图传值不正确。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5769]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 114.0.5735.248（正式版本） (arm64)

**Bug 描述**
明细表联动其它视图，设置明细表的两个字段联动视图的一个字段，发现传值不正确。

**Bug 重现步骤(有截图更好)**
1. 如下所示明细表与柱状图
<img width="973" alt="image" src="https://github.com/dataease/dataease/assets/30063018/45268bc2-1e65-46b6-b311-2499c99083d7">
2. 设置联动字段，明细表的商品大类与商品小类均联动柱状图的商品大类（模拟场景）
<img width="1239" alt="image" src="https://github.com/dataease/dataease/assets/30063018/0b768764-f285-4afc-b592-8ea060230885">
3. 此时我们点击商品小类，视图发生了联动
<img width="963" alt="image" src="https://github.com/dataease/dataease/assets/30063018/3adfad2b-6da2-4230-bb38-c978f34817cb">
4. 将视图的查询 SQL 解码后，SQL 如下所示：
`SELECT
    *
FROM
    (SELECT
        CAST(t_a_0.`f_cb39c5514af50e68e727b09e284da135` AS VARCHAR) AS f_ax_0
        ,
        sum(CAST(t_a_0.`f_58b622b0b9e5f8a2d759f151e8a05a51`*t_a_0.`f_d6d7eeac7d2f069f4706e668b549482e` AS BIGINT)) AS f_ay_0
    FROM
        `ds_a5d72c4d_8251_48b1_bd27_11811963d529`   t_a_0
    WHERE
        (CAST(t_a_0.`f_cb39c5514af50e68e727b09e284da135` AS VARCHAR)  = '坚果炒货')
    GROUP BY
        f_ax_0
    )   t_a_1
 LIMIT 0,1000`
发现我点击的商品小类，但是实际上将商品大类的值传了过去，这与预期不符，预期应该是点击的什么字段，传什么字段的值。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们验证一下；

**Comment by ziyujiahao** [comment]
当前明细表的联动设计是按照行数据匹配 即不管点击当前行的那个字段 都会按照整行数据和目标视图的字段进行匹配；但这中间会有个去重机制，即当多个源视图字段匹配到目标视图的一个字段时，只保留一个值，这个保留的值原先是按照字段的展示顺序保留较后一个，当前优化为优先保留点击字段匹配的值。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
