### ISSUE TITLE
[Bug] ProxyAuthService @Lazy 注解类 import 导入引用错误 (groovy.lang.Lazy)

### ISSUE THREAD

**Issue by calvinit** [dataease/dataease#5770]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome 版本 115.0.5790.102（正式版本） **(x86_64)**

**Bug 描述**
backend 模块的 [ProxyAuthService](https://github.com/dataease/dataease/blob/dev/backend/src/main/java/io/dataease/auth/service/ProxyAuthService.java) 这个 Java 类中 `@Lazy` 注解类 import 导入引用错误了，使用了 `groovy.lang.Lazy`，如果没理解错的话，应该是 `org.springframework.context.annotation.Lazy` 才对？

**Bug 重现步骤(有截图更好)**
![issue_lazy](https://github.com/dataease/dataease/assets/27403411/fe43af80-0aab-4856-84a6-6eab7572fd0d)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们处理一下；

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
