### ISSUE TITLE
[Bug]在视图中设置显示名，单击回车会刷新页面，并且访问路径发生变化。

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#5771]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
在设置显示名时单机键盘回车，会刷新页面。访问路径由http://xx.xx.xx.xx/#/panel/index变为：http://xx.xx.xx.xx/?#/panel/index

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下；

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
