### ISSUE TITLE
[Question] v1.18.9 新建计算字段时，指标字段列表为空。选择不到已创建的指标字段

### ISSUE THREAD

**Issue by zhenwufang** [dataease/dataease#5772]
**请描述您的问题.**
Dataease版本：v1.18.9
问题描述：通过Excel导入的数据集，在创建计算字段时，无法选择指标字段

如下，创建了指标字段：
![image](https://github.com/dataease/dataease/assets/4045933/6a54c9dc-6462-40b9-84d7-aae69fd2592b)
创建计算字段时，指标字段列表为空：
![image](https://github.com/dataease/dataease/assets/4045933/ef3390fc-6731-4bf2-9f60-e67ec7601f02)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，是由于已创建的指标字段本身就是一个计算字段，系统当前还不支持用计算字段再次创建计算字段。
