### ISSUE TITLE
[Bug] 新建sql数据集 sql运行查询正常，保存的时候报错

### ISSUE THREAD

**Issue by sanglei0807** [dataease/dataease#5773]
**DataEase 版本**

v.18.8
**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**

Google Chrome 114.0.5735.199
**Bug 描述**
新建sql数据集 sql运行查询正常，保存的时候报错

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/33617860/9f7918b6-9c4e-4bab-a28d-4f20e4b7c61b)

2.
![image](https://github.com/dataease/dataease/assets/33617860/6c3cafed-b308-48ef-8cde-98d63bbfb224)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，麻烦看一下如果不使用参数化的情况是否能正常保存呢？

**Comment by sanglei0807** [comment]
> 感谢反馈，麻烦看一下如果不使用参数化的情况是否能正常保存呢？

可以正常保存

**Comment by BBchicken-9527** [comment]
建议这种过于复杂的sql语句先不要使用参数化的设置，目前此功能不够完善，给你的带来不好的体验非常抱歉，我们也在尽快完善此处功能；
