### ISSUE TITLE
[Feature]SQL数据集--参数设置，建议文本类型的增加一个允许空字符串选项

### ISSUE THREAD

**Issue by lcawen** [dataease/dataease#5774]
目前sql中一旦遇到了类似这种参数放在前面的情况，(('${param}' != '' AND find_in_set(table.param,'${param}')) OR ('${param}' = ''))，就会异常：
1. 因为后台处理SQL时候会转换成'DATAEASE_PATAMS_BI'!=''，从而导致removeVariables时因为包含DATAEASE_PATAMS_BI而异常；
2. 如果增加了允许空字符串的话，参数允许为空，'${param}' != ''，通过参数值就可以转换为''!=''，不包含DATAEASE_PATAMS_BI就可以正常执行了

**Comment by lcawen** [comment]
比如这样，![image](https://github.com/dataease/dataease/assets/4370695/92b976d4-eff8-4c1e-b26c-87e5b940c32a)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下优化方式。

**Comment by tjlygdx** [comment]
我要看一下你的sql数据集是怎么写的？
