### ISSUE TITLE
[Feature]希望过滤组件支持手动设置宽度、高度

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5775]
**请描述您的需求或者改进建议.**
场景：制作仪表板存在多个不同的过滤组件时，有时宽度和高度通过拖拽的方式不是很好统一，希望支持手动设值的方式设置宽度、高度

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，暂时没有规划进行支持。
