### ISSUE TITLE
[Feature]希望关联数据集支持： 左外连接，右外连接，全连接（参考自PowerBI）

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5776]
**请描述您的需求或者改进建议.**
场景：对于企业内部的使用者来说，很多用户没有 SQL 的知识储备，需要关联数据时又不会写 SQL，只能通过关联数据集创建关联关系，所以希望支持的关联类型更更丰富一些

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，左外连接和右外连接，与系统当前支持的左连接、右连接数据的处理结果是一致的。全连接的结果中没有匹配上的用null进行了补位，对于大部分图表聚合后的结果没有太大的意义，因此暂时没有规划进行支持。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，左外连接和右外连接，与系统当前支持的左连接、右连接数据的处理结果是一致的。全连接的结果中没有匹配上的全部用null进行了补位，对于大部分图表聚合后的结果没有太大的意义，因此暂时没有规划进行支持。
