### ISSUE TITLE
[Feature] 针对多指标折线图、或者堆叠图之类的图形标签叠在一起的情况进行优化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5778]
**请描述您的需求或者改进建议.**
当前版本折线图、堆叠图之类的图表标签打开的情况下会出现堆叠在一起的现象。
查看了 AntV 的文档，AntV 的 G2 是支持标签的一些布局方案的，建议开放出来可供调整。
![image](https://github.com/dataease/dataease/assets/30063018/7eb1075a-cacd-45c6-9ae8-caacf4b0f5a6)
另外多标签可能会造成无法精确读数的情况，标签太多了，不知道哪个对应哪个，能否支持标签颜色与指标颜色一致，如下所示：
![image](https://github.com/dataease/dataease/assets/30063018/4a12df13-6cbb-4caf-bebe-0f30001d4d54)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈和建议，我们需要先讨论后再进行回复。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，关于标签重叠的情况，是由于线条数据点比较密，与标签的布局关系不大，标签是显示在数据点周围，也还是会出现重叠的情况。为了有一个较好的展示效果，后面会规划增加设置项，重叠的标签可能仅显示一个，隐藏部分标签。
