### ISSUE TITLE
[Feature]支持 微软的Analysis Services 数据源

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5779]
**请描述您的需求或者改进建议.**
Analysis Services 是一个分析数据引擎，用于决策支持和业务分析。 它为商业智能 (BI) 、数据分析和报表应用程序（如 Power BI、Excel、Reporting Services 和tableau 其他数据可视化工具）提供企业级语义数据模型功能。

希望在 2.x 支持此数据源。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议我们已收到，近期暂时没有规划进行支持。
