### ISSUE TITLE
[Bug]时间范围组件自定义时间异常

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5780]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
 Edge 最新版

**Bug 描述**
如图，使用日期范围组件设定自定义动态时间，生成的日期变成了 9 月，实际日期是 7 月 27 日
![17351690438005_ pic](https://github.com/dataease/dataease/assets/30886198/792e1f70-cc86-4677-a8cd-ff2b7c48e6f6)

**复现步骤**
添加日期范围组件，勾选显示时间，并设值为时分秒格式
默认值修改为动态时间，选择自定义
在时分秒输入框中手动输入 10，按回车，日期显示就会异常
![image](https://github.com/dataease/dataease/assets/30886198/33987748-2fa6-4589-9850-61c633637b67)

**Comment by liuboF2c** [comment]
![image](https://github.com/dataease/dataease/assets/30886198/b9df8f50-4ef6-4156-84ef-fa16f9a9f734)
服务器时间是正常的

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
