### ISSUE TITLE
年份时间组件不能正常work

### ISSUE THREAD

**Issue by QiuchengGitHub** [dataease/dataease#5782]
DataEase 版本
v1.18.9

运行方式(安装包运行 or 源码运行 ?)
安装包

浏览器版本
版本 86.0.4240.198（正式版本） （32 位）

Bug 描述
如图，列表包含2022年及2023年的数据，但是使用年份控件作为查询条件时，导致查询不到数据
![image](https://github.com/dataease/dataease/assets/8490665/a6984ebd-e076-4e49-8b24-cf645355c221)
![image](https://github.com/dataease/dataease/assets/8490665/20afbc5c-1352-4120-ac56-3616f76ad858)
![image](https://github.com/dataease/dataease/assets/8490665/822cc206-9fe3-4cb4-ba86-8918c04f695c)
![image](https://github.com/dataease/dataease/assets/8490665/fc29bdcd-810d-4a41-8e39-ef638f1dd085)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复；

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
