### ISSUE TITLE
[Feature]大数据量的同步问题

### ISSUE THREAD

**Issue by HeyChiang** [dataease/dataease#5783]
**请描述您的需求或者改进建议.**
线上数据库一张表有100多个字段，总行数有2~3千万时，无法一次性同步数据。

**期望**
通过增量同步，根据Doris已有的数据，获取最新的数据值去同步其他的数据库数据。

例：截取下面的$()内的SQL执行，获得同步值以后替换掉$()，然后没5分钟分页同步一次
`INSERT INTO books select * from jdbc_oracle.ERPSPACE.BOOKS where ID > $(select max(ID) from books) limit 100"`

```java

  /**
     * 
     * @param query 源查询SQL
     * @return Doris同步值的SQL语句
     */
    private static String takeCustomizeSQL(String query) {
        Matcher matcher = Pattern.compile("\\$\\(.+\\)").matcher(query);
        if (matcher.find()) {
            String sql = matcher.group(0);
            return sql.substring(2, sql.length() - 1);
        }
        return null;
    }
```

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，与当前的同步机制不一样，我们需要先讨论一下。

**Comment by HeyChiang** [comment]
有新的消息还请和我同步，目前这个问题导致我不敢在线上环境启用dataease

**Comment by xuwei-fit2cloud** [comment]
我们这边后续版本设计一下，可以支持指定更新的判断字段来处理这个问题。
