### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by QiuchengGitHub** [dataease/dataease#5784]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 86.0.4240.198（正式版本） （32 位）

**Bug 描述**
从MySQL数据源中，以直连的方式创建了一个数据集，其中有个varchar类型的字段我期望转换成时间（%Y）类型，但是设置后仍为（yyyy-MM-dd HH:mm:ss）格式

**Bug 重现步骤(有截图更好)**
1.创建数据集并修改字段类型
![image](https://github.com/dataease/dataease/assets/8490665/af0c10f4-ecce-4e6b-8c6d-2367cc60a7ef)

2.预览字段数据，格式并不正确
![image](https://github.com/dataease/dataease/assets/8490665/2c353558-e726-4605-ac9c-e7b804c0d2ae)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前平台的日期格式是固定的，就算日期是只有年，在预览页面也会在后面添加上月日时分秒的；
