### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by QiuchengGitHub** [dataease/dataease#5785]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 86.0.4240.198（正式版本） （32 位）

**Bug 描述**
计算字段的计算逻辑有问题。

**Bug 重现步骤(有截图更好)**
1.基于日期字段，我想新增年、月、日三个新增字段
![image](https://github.com/dataease/dataease/assets/8490665/4c33f3e0-ad6c-414d-8d6c-8b9194f498cd)

2.以年的新增字段计算逻辑来举例
![image](https://github.com/dataease/dataease/assets/8490665/759020d2-d078-4229-969e-6c13344c11e8)

3.讲道理，新增字段“年”应该是4位的年信息，但实际上字段为空
![image](https://github.com/dataease/dataease/assets/8490665/8d34e6e3-166d-4f06-890e-c8e763c1bbc5)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前平台的时间格式是固定的，这样转换平台无法判断你的时间具体是什么，比如你切分出来一个06月，平台是无法知道你这个是年还是月或者是日的；
