### ISSUE TITLE
[Bug]使用插件形式支持的数据源添加动态辅助线时视图报错

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5788]
**DataEase 版本**
 V1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 最新

**Bug 描述**
使用达梦数据源创建的数据集制作折线图，添加动态值辅助线后视图显示如图错误
![image](https://github.com/dataease/dataease/assets/30886198/24a04333-748c-4417-b047-0482178a8b17)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复；
