### ISSUE TITLE
[Feature]建议数据集预览不自动触发，增加按钮，按需预览

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#5789]
**请描述您的需求或者改进建议.**
当用户在切换数据集时，目的并非是预览数据。可能是做 Excel 数据更新、配置字段管理、导出数据、配置行列权限、编辑 SQL 等等。

如果用户的整体数据量较大，则每次切换数据集需要等待较长时间加载数据，而他的目的也不在于查看数据时，此段等待时间就会有些多余。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，像操作：Excel 数据更新、配置字段管理、导出数据、配置行列权限、编辑 SQL 等，均属于数据集的编辑操作，建议在数据集的编辑中完成。

为图表切换新的数据集，主要是为了选择一个其他的数据集，因此此处的数据预览，是便于用户在选择数据集时，给予参考，帮助用户确认是否是他想要选择的数据集。因此，这里我们还是保持现状。
