### ISSUE TITLE
[Feature] 定时报告选择用户添加校验

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5790]
**请描述您的需求或者改进建议.**
定时报告可以选择用户，也可以填写不存在dataease中的用户邮箱，希望加一个校验
<img width="984" alt="image" src="https://github.com/dataease/dataease/assets/45852479/6a513625-f100-4c58-863d-3e59e35c554c">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先记录并讨论一下。

**Comment by xuwei-fit2cloud** [comment]
此输入框不仅仅能接受邮件的输入，还可以支持用户名、飞书账号等信息的输入，所以不予处理。
