### ISSUE TITLE
[Bug]API数据源同步任务修改更新方式不生效

### ISSUE THREAD

**Issue by wan92hen** [dataease/dataease#5792]
**DataEase 版本**
v1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**Bug 描述**
修改API数据源同步任务的更新方式不生效，从 `增量更新` 方式改为 `全量更新` 后，实际执行时还是采用了增量更新。 

**Bug 重现步骤(有截图更好)**
1. 创建 API 数据源及 API 数据集
2. 在 API 数据集上创建更新方式为 `增量更新` 的定时更新任务
3. 立即执行上一步的任务，数据集中的数据进行了增量更新
4. 修改更新任务的更新方式为 `全量更新` 后，再次立即执行这个任务，数据集还是进行了增量更新，旧数据没有被覆盖

**Comment by BBchicken-9527** [comment]
感谢反馈，你尝试更新最新的版本问题应该已经在之前版本解决了；

**Comment by wan92hen** [comment]
升级到最新的 v1.18.9 之后，该问题依然存在。

**Comment by BBchicken-9527** [comment]
请问你是精简模式吗？

**Comment by wan92hen** [comment]
> 请问你是精简模式吗？

是的。

**Comment by BBchicken-9527** [comment]
了解了，实在不好意思给你造成了不好的体验，我们会尽快修复；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
