### ISSUE TITLE
[Bug]chart、table视图组件文字会随界面尺寸缩小而自动缩小

### ISSUE THREAD

**Issue by nextll** [dataease/dataease#5793]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
edge  版本 116.0.1938.29 (正式版本) stable应用

**Bug 描述**
当浏览器缩放时，仪表板中的各chart类视图组件、表格组件中的**文字**会自动缩小、放大。当全屏时设置的12号文字，在缩小后会无法看清。同类QuickBI、FineBI等产品没有这个问题，可以让仪表板在嵌入到业务应用时、以弹窗方式跳转时（DataEase没有该功能，但假设有的话该BUG将造成弹窗跳转无法实际使用）。
这个BUG个人认为还是比较严重的，至少我自己不会考虑将DataEase应用到实际项目中。

**Bug 重现步骤(有截图更好)**
1.最大化浏览器显示仪表板，文字大小正合适，可以看清。
![image](https://github.com/dataease/dataease/assets/53806089/52f8c8d3-379e-4818-936f-87db19673350)

2.浏览器用鼠标缩小，文字大小也会自动缩小，文字已经小的看不清了。
![image](https://github.com/dataease/dataease/assets/53806089/1d08ba8a-7eaa-4ca6-9661-370db9364171)

3.同类功能的QuickBI缩放是没有问题的。文字始终保持相同大小（未提供图片）。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前我们设计是自适应的方式，我们后续会讨论一下；

**Comment by nextll** [comment]
> 感谢反馈，目前我们设计是自适应的方式，我们后续会讨论一下；

这个自适应做得有点脱离实用性了。正常的自适应是该是图、表的边框会缩小，但字体、行高不会缩小。当缩小到一定程度时出现滚动框无法缩小（最小尺寸）。具体可以参考竞品。

**Comment by BBchicken-9527** [comment]
好的，我们会着重研讨一下你提的建议的，感谢你的建议；

**Comment by xuwei-fit2cloud** [comment]
组件增加文字是否自适应选项。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
