### ISSUE TITLE
[Bug]Tab组件中的过滤组件设置默认值不生效

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#5795]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
放置筛选组件在 Tab 组件中，对 Tab 组件的视图做默认值筛选，其默认值不生效，手动选择可以生效。

**Bug 重现步骤(有截图更好)**
1.为 Tab 中视图设置筛选条件，并设置默认值“上海市”，请注意，筛选条件需要与视图同时在一个 Tab 下。
![image](https://github.com/dataease/dataease/assets/48945409/d958b406-8c39-4cba-ae36-d9e1485ad517)

2.保存后，切换到该仪表板下，默认值显示为“上海市”，但左侧表格数据并未被过滤。
![image](https://github.com/dataease/dataease/assets/48945409/e5c2d94c-e99d-4fdd-9d64-4de34edde8f9)

3.手动做筛选切换，数据正常过滤。
![image](https://github.com/dataease/dataease/assets/48945409/f1d3e00e-69d3-4f79-9f13-d9c6834e85df)

**Comment by BBchicken-9527** [comment]
感谢反馈，应该是过滤筛选顺序问题，我们修复一下；

**Comment by Shenguobin0102** [comment]
问题已修复，请关注 v1.18.10 版本。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
