### ISSUE TITLE
[Feature]色彩地图标签、提示支持显示多个指标值

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#5799]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/70566485/eeb90ddf-a10d-4bbf-92c8-9165f12054b8)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们可以在２.ｘ版本中考虑实现，目前１.１８.ｘ版本还无法实现。
