### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#580]
**DataEase 版本**
v1.2

**浏览器版本**
Chrome 91.0.4472.114

**Bug 描述**
编辑表格类型的视图颜色时，一部分颜色无法选到。

**Bug 重现步骤(有截图更好)**
1.如下图所示，上半部分的颜色被遮挡。
![image](https://user-images.githubusercontent.com/48945409/128861318-2238bfc7-2625-4ec7-ab5b-0a391cb8d09c.png)

**Comment by xuwei-fit2cloud** [comment]
v1.1.0 正式版本已修复
