### ISSUE TITLE
[Feature]【数据集】SQL 数据集自定义参数增加「是否必填」选项

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5800]
**请描述您的需求或者改进建议.**
SQL 数据集自定义参数增加「是否必填」选项，必填则增加以下限制「在没有筛选值的时候不显示数据」，其他逻辑不动。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，参数是用于对数据集进行过滤，如果参数没有值，即不对数据集的数据进行过滤，那么显示全部数据，因此这里我们暂时先保持当前的处理逻辑。
