### ISSUE TITLE
[Bug]【仪表板】仪表板适配性优化

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5801]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
Linux 平台打开的仪表板和 WIndows 平台打开的仪表板分辨率不一样

**Bug 重现步骤(有截图更好)**
标题大小不一致
![image](https://github.com/dataease/dataease/assets/24768910/62b520cf-8355-4d54-acd7-5c41294f3afa)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问分辨率大小和显示比例都是一致的吗？

**Comment by AndroidBaby1** [comment]
用的是谷歌浏览器直接打开

**Comment by BBchicken-9527** [comment]
我的意思是说你看看系统设置里面的屏幕分辨率是否一致，再看看谷歌浏览器中缩放是否是正常的百分之百，如果有不一样的地方调整一下应该应该就没什么问题了；
