### ISSUE TITLE
[Bug]DM数据源表名为小写，添加数据库数据集、SQL数据集报错

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#5803]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
离线包运行

**浏览器版本**

**Bug 描述**
DM数据源表名为小写，添加数据库数据集、SQL数据集报错
已确认是bug，表名为小写时需要添加标识符扩起来

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/70566485/9ad03b4d-f6e7-40a9-84d4-b96ee898d6e3)
![image](https://github.com/dataease/dataease/assets/70566485/8083a133-c015-4acc-b020-595212d60701)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复
