### ISSUE TITLE
[Bug]官网点击"交流&贡献"报错:java.sql*

### ISSUE THREAD

**Issue by yazong** [dataease/dataease#5806]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**

### Error updating database. Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'dataease-E1se2t' for key 'name' ### The error may involve com.fit2cloud.community.mapper.CmtyContributorsMapper.insert-Inline ### The error occurred while setting parameters ### SQL: insert into cmty_contributors (product, name, cert_date ) values (?, ?, ? ) ### Cause: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'dataease-E1se2t' for key 'name' ; Duplicate entry 'dataease-E1se2t' for key 'name'; nested exception is java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'dataease-E1se2t' for key 'name'

**Bug 重现步骤(有截图更好)**

**Comment by yazong** [comment]
"https://community.fit2cloud.com/#/products/dataease/techexchange"

**Comment by xuwei-fit2cloud** [comment]
已修复。
