### ISSUE TITLE
[Feature]图例左右居中上下居上时，能将图例默认放在视图标题下方

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#581]
**请描述您的需求或者改进建议.**
图例左右居中上下居上时，能将图例默认放在视图标题下方
图例左右居中上下居下时，能将图例默认放在视图标题上方

**Comment by yayanpei** [comment]
非常感谢您的反馈，您的建议是我们产品改进和优化的方向。

**Comment by xuwei-fit2cloud** [comment]
v1.2.0 已支持
