### ISSUE TITLE
[Feature] 跳转配置选择仪表板页面 仪表板名称显示不全

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5816]
**请描述您的需求或者改进建议.**
跳转配置选择仪表板页面 仪表板名称显示不全，如果有前缀相同的仪表板，选择不太明显
![image](https://github.com/dataease/dataease/assets/45852479/e7053f81-bb89-44a4-a57b-2fae60377a07)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下显示。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
