### ISSUE TITLE
[Feature]仪表板及数据集配置改进

### ISSUE THREAD

**Issue by xone2023** [dataease/dataease#5821]
**请描述您的需求或者改进建议.**
1.数据集预览建议设置为手动触发形式
2.数据集更改为仅配置模式，标记聚合、非聚合字段等，在面板编辑时组装SQL去实际查询，这样实际查询可根据面板字段需要，方便实现聚合
3.透视表需增加翻页功能，结合第2条即可实现前后端分页查询，针对不同面板组装分页查询SQL即可
4.面板编辑和数据集字段定义对date格式支持不完善，面板自定义格式支持不完善
5.面板编辑，时间范围搜索框星期日可放在最右列
6.面板编辑时，下拉框存在闪动情况

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by jikuanyu** [comment]
强烈建议分页。

**Comment by xuwei-fit2cloud** [comment]
我们在2.x版本中尝试处理。
