### ISSUE TITLE
[Question] 移动端下的tab组件里的视图 如何进行布局，目前是被挤压到一起的

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5822]
**请描述您的问题.**
移动端下的tab组件里的视图 如何进行布局，目前是被挤压到一起的
![image](https://github.com/dataease/dataease/assets/45852479/8ec5cb2a-86eb-43fd-bb2d-00e87bf09dea)

**Comment by xuwei-fit2cloud** [comment]
目前Tab组件在PC端和移动端是同样的布局，其他的组件是独立布局。
短期内还不会做相应的调整。
