### ISSUE TITLE
[Bug] 官网demo仪表板全屏预览时间选择器出现位移

### ISSUE THREAD

**Issue by kanouken** [dataease/dataease#5823]
**DataEase 版本**
  官网demo

**运行方式(安装包运行 or 源码运行 ?)**
  查看官网demo

**浏览器版本**
chrome 115

**Bug 描述**
仪表板全屏预览 时间选择器出现位移

**Bug 重现步骤(有截图更好)**

**Comment by BBchicken-9527** [comment]
感谢反馈 ，我们会尽快修复；

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #5532
