### ISSUE TITLE
[Feature]选项卡标签切换时白屏

### ISSUE THREAD

**Issue by Linkjie-11** [dataease/dataease#5826]
**请描述您的需求或者改进建议.**
选项卡标签切换时会有一段时间白屏，非常影响观感。优化下切换时的效果。
![1690954739297](https://github.com/dataease/dataease/assets/52249559/2726dee0-435a-4aad-a0f1-541080f57df7)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先调研一下能否处理。

**Comment by xuwei-fit2cloud** [comment]
可以试试将动画加载提示关闭。
