### ISSUE TITLE
[Bug]API数据源 请求体乱码

### ISSUE THREAD

**Issue by hds1999** [dataease/dataease#5827]
**DataEase 版本**
1.8.6

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
请求体中文乱码
![f7592fb6fc0858895141dac7adea643](https://github.com/dataease/dataease/assets/20547693/efd62ae3-2726-44aa-beeb-927ec28773ba)

**Comment by BBchicken-9527** [comment]
感谢反馈，嗯... 方便问一下你具体的复现步骤吗，目前测试环境没发现你说的问题；

**Comment by hds1999** [comment]
> 感谢反馈，嗯... 方便问一下你具体的复现步骤吗，目前测试环境没发现你说的问题；

源码部署（前后端分离）的，Windows环境。

**Comment by hds1999** [comment]
> 感谢反馈，嗯... 方便问一下你具体的复现步骤吗，目前测试环境没发现你说的问题；

今天验证了一下，应该是Windows环境源码部署（前后端分离）的有这个问题，CentOS环境没有问题（同一个数据库）。是不是Windows的字符集有什么关系？

**Comment by wang-yudong** [comment]
![image](https://github.com/dataease/dataease/assets/54743538/d0ee7a28-a53e-4a5a-bfbc-4d34fff17c20)
我也遇到了，windows本地idea启动建的数据集和仪表盘正常，迁移到windos服务器上用jar按文档打包运行，出现乱码问题了

**Comment by wang-yudong** [comment]
问题解决了，windows下启动脚本需要增加 -Dfile.encoding=UTF-8参数，例如：
java -jar -Dfile.encoding=UTF-8 backend-1.18.9.jar

**Comment by hds1999** [comment]
> 问题解决了，windows下启动脚本需要增加 -Dfile.encoding=UTF-8参数，例如： java -jar -Dfile.encoding=UTF-8 backend-1.18.9.jar

这段我增加了，可是也没有解决。
