### ISSUE TITLE
[Feature] 视图操作支持快捷键

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5830]
**请描述您的需求或者改进建议.**
视图支持 crtl c 复制
 crtl v 粘贴
delete 删除

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，当前已经支持了部分快捷键，后面我们也会规划支持更多的快捷操作。

**Comment by xuwei-fit2cloud** [comment]
目前规划在2.x中，1.18.x短期内还不会支持。
