### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by sanglei0807** [dataease/dataease#5831]
**请描述您的问题.**
一个日期组件能给多个数据集传参吗

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，如果需要给多个数据集传递参数，那么组件这里绑定多个数据集的字段就可以了。如下图所示：
<img width="740" alt="image" src="https://github.com/dataease/dataease/assets/84168063/c27d81a0-09fd-467f-a29b-908a6a1ffc83">

**Comment by sanglei0807** [comment]
![image](https://github.com/dataease/dataease/assets/33617860/5baf34fb-f00a-4290-8a4f-43065fb86012)
我这样配置只有第一个date可以传日期进去，第二个date帅选结果无反应

**Comment by yayanpei-fit2cloud** [comment]
在线文档地址：https://dataease.io/docs/user_manual/filter_module/filtertime_module/#4 ，建议您参考文档检查一下。
