### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by lose50281** [dataease/dataease#5832]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
docker

**浏览器版本**
chrome

**Bug 描述**
com.microsoft.sqlserver.jdbc.SQLServerException: The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]". 

**Bug 重现步骤(有截图更好)**
![9cef376f69e5408a21e5f759d689896](https://github.com/dataease/dataease/assets/35716011/bf2bbfab-fc59-478d-95d6-42ab13446b71)

**Comment by BBchicken-9527** [comment]
感谢反馈，这个问题应该解决了，你重新拉一下镜像就好了；我现将这个问题关闭掉，如果还不行可以重新打开或者联系我们交流群中的同学他们会第一时间反馈给我大家的问题；

**Comment by lose50281** [comment]
好了，需要更新两个镜像：
docker pull registry.cn-qingdao.aliyuncs.com/dataease/fabric8-java-alpine-openjdk8-jre:edge-chromium
docker pull registry.cn-qingdao.aliyuncs.com/dataease/dataease:v1.18.9
