### ISSUE TITLE
辅助线名称和数字信息能否隐藏[Feature]

### ISSUE THREAD

**Issue by Linkjie-11** [dataease/dataease#5834]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/52249559/9f929cd0-d885-4aae-8f49-fdc2c082e755)
辅助线上的信息能否自动隐藏，鼠标悬停再显示 或者其他隐藏方式。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，辅助线是辅助用户查阅图表，因此暂时没有计划支持将其隐藏。
