### ISSUE TITLE
[Feature]数据集字段

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#5836]
**请描述您的需求或者改进建议.**
修改数据集字段类型，每次修改名称后会刷新一遍数据。希望增加一个确认按钮，全部修改完之后统一刷新

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们这里已经规划了优化机制，会降低刷新频次。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
