### ISSUE TITLE
[Bug] 配置列权限后，维度丢失

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5837]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
配置列权限后，维度丢失

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/45852479/f3cfce57-d6fb-4814-92be-a81bc9c17a11)

**Comment by BBchicken-9527** [comment]
感谢反馈，某个维度设置了脱敏并且这个维度会用于分组聚合，后台的处理是直接删除这个维度， issue 里的视图在后台查询时只查询了指标这一列，所以视图里下面显示是空的；
