### ISSUE TITLE
[Feature]下拉过滤组件是否可以考虑支持自定义视图配置字典key,value形式（直连模式）

### ISSUE THREAD

**Issue by wang-yudong** [dataease/dataease#5838]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/54743538/18525b16-8ba3-47e8-a50e-2bcac6a5af9d)
下拉过滤目前直连只能通过显示的的中文名去过滤结果值，不知道怎么按图中的account编码字段值去过滤用户，下拉拖account就是显示用户的编码而不是实际名称，如果拖realname，显示是中文名，也能过滤，但无法分辨同名用户，重名的数据（account不一样）就被合并了

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已经在需求池中，近期暂时没有规划进行支持。
