### ISSUE TITLE
[Bug]流向地图保存后，线条的类型无法修改

### ISSUE THREAD

**Issue by zhanwonichengshizhu** [dataease/dataease#5840]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
流向地图保存后，线条的类型无法修改

**Bug 重现步骤(有截图更好)**
1.创建流向地图配置好后保存；
2.重新编辑流向地图，更改线条类型；
3.无法选择其他类型线条。
<img width="1413" alt="image" src="https://github.com/dataease/dataease/assets/102785193/f4010c9a-a135-4c44-8cb8-ac967d18bc74">

**Comment by BBchicken-9527** [comment]
感谢反馈，你看一下你「颜色-渐变」是否开启了，目前直线和弧线是不支持渐变的；

**Comment by zhanwonichengshizhu** [comment]
感谢，确实开启了渐变
