### ISSUE TITLE
[Question]请问其他组件中的网页组件是否支持参数关联

### ISSUE THREAD

**Issue by ZephaniaP** [dataease/dataease#5843]
比如说我有一个文本下拉组件，是否可以把字段传递给网页组件的网页地址中

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，文本下拉组件中的参数是不能传递给网页组件的，文本下拉组件中的参数是传递到所绑定的sql数据集中，用于过滤数据的。
