### ISSUE TITLE
[Bug]创建分享链接有中null

### ISSUE THREAD

**Issue by fengybl** [dataease/dataease#5845]
**DataEase 版本**
1.18.6

**运行方式(安装包运行 or 源码运行 ?)**
源码打包运行

**浏览器版本**
edge

**Bug 描述**
![66f941c25a7ced95bddedb9e83921f8](https://github.com/dataease/dataease/assets/18284232/06bce540-212b-41f6-82a8-57d24f25f567)
创建的分享链接地址中含有null值,分享不成功

**Comment by BBchicken-9527** [comment]
感谢反馈，因为你是源码部署不确定你是否改动建议参照文档进行部署：https://dataease.io/docs/dev_manual/dev_deployment/tool/
若依然无法解决你目前的问题可以重新打开或加入我们的交流群会有专门的工作人员第一时间解决你的问题；
