### ISSUE TITLE
[Feature]数据合并，两张不同来源的表，合并成同一个表

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#5848]
**请描述您的需求或者改进建议.**
<img width="581" alt="image" src="https://github.com/dataease/dataease/assets/101089844/fa9aeee1-943a-49af-a6a0-9880f723980a">
<img width="575" alt="image" src="https://github.com/dataease/dataease/assets/101089844/1bb6712d-8ba4-496e-b753-ce1b93191cd0">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，回复请见如下：
1、A库同步的数据，如果同步，默认放入系统内置的doris数据库中，不支持放入另一个库。原因：涉及数据的安全性，系统只对用户的数据做读操作，用于数据的分析展示，不对用户的数据库做写入操作。
2、两表合并成一个宽表，建议使用关联数据集，这样当需要分析展示时，可使用关联数据集查询数据并用于展示，关联数据集中保存了关联关系，没有再次保存数据的原因，一方面会造成大量的冗余数据，给系统带来较大的压力；另外一方面如果源数据有更新，那么还要再次对关联数据集进行刷新。综上考虑，我们还是保持当前的现状。
