### ISSUE TITLE
[Feature]文字组件 字体大小跟随屏幕大小自适应

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5849]
**请描述您的需求或者改进建议.**
不同屏幕大小下的，文字组件中的文本，字体大小是固定的，影响页面展示的效果，希望支持字体大小的自适应，就像下图明细表中的字体大小一样（会跟随屏幕大小自适应）
![image](https://github.com/dataease/dataease/assets/89771514/0a2939e2-e522-4c41-8cfc-5b8017d9e176)
![image](https://github.com/dataease/dataease/assets/89771514/4d5f8364-8580-4cfd-8bc9-c88bbc6d3a37)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，自适应当前没有覆盖所有的内容，我们先加入需求池中。
