### ISSUE TITLE
[Bug]数据库表名错误

### ISSUE THREAD

**Issue by hxpmc** [dataease/dataease#5851]
**DataEase 版本**

开发版本
**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.
![5eb33bffa029beeeda0432173129428](https://github.com/dataease/dataease/assets/27937161/5100c2bb-05af-4cb0-b482-290811d218e5)

2.V57__1.18-table-desc-update.sql 第50行的表名下划线多了个空格
3.

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by Shenguobin0102** [comment]
问题已修复，请关注 v1.18.10 版本。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
