### ISSUE TITLE
[Question]更新18.9版之后，视图中没有桑基图的选项。

### ISSUE THREAD

**Issue by 8252398** [dataease/dataease#5852]
**请描述您的问题.**
18.9的更新说明中写的支持了桑葚图。我已经更新了18.9版，用dectl version查询显示当前版本已经为18.9版。使用浏览器为chrome v81，并清空了浏览器缓存。但是在视图选项中并没有出现桑葚图。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，桑基图是以插件的形式开发的，如果需要可以参考在线文档打包插件并在系统中上传。
在线文档地址：https://dataease.io/docs/dev_manual/dev_view_plugin/

**Comment by xuwei-fit2cloud** [comment]
后续版本我们将其加入默认镜像中。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
