### ISSUE TITLE
[Bug]仪表板中聚合字段取均值或百分比总计计算问题

### ISSUE THREAD

**Issue by xone2023** [dataease/dataease#5853]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
仪表板中取均值或百分比的聚合字段总计/小计计算有问题，仅做简单总和，应根据字段计算情况（字段相除时或手动标记）取汇总后的均值

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/141128600/7ebc4403-6bf0-47af-93ff-6d09b4ceec09)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，方便详说明一下复现步骤吗？

**Comment by xone2023** [comment]
这些字段是透视表里增加视图字段，由其他两个字段的和相除计算得到的一个百分比/均值；然后在样式里面添加行汇总后，直接把这些字段相加得到了一个总和，应该是按同样的计算方式，计算一个均百分比/均值，即将此列按查询条件先汇总（除去小计）然后除以汇总数得到均值

**Comment by xuwei-fit2cloud** [comment]
这个是图库默认的计算方式，我们会在后面的大版本中尝试增加一下相关的计算方式支持。
