### ISSUE TITLE
[Question]我是一名前端开发&UI设计师，我看到dataease的UI比较原始，所以看能否寻求合作机会。

### ISSUE THREAD

**Issue by jay86cn** [dataease/dataease#5855]
**请描述您的问题.**
我开发了一个可视化的前端开发框架，框架有非常多的闪光点，花费了3年的时间开发。我只懂UI设计和前端开发，不懂后端，无法将其打造成一个完整的产品，而也并找不到合适的推广渠道，所以没有变现和商用的能力。想咨询没有可能合作的机会？我的框架无图片，全部用动态SVG开发的装饰图形，在国内很少有人去做这类型的开发。

这里是github地址
https://github.com/ayin86/techui-vue2

这里是预览地址
(托管到githubPages上的中国国内访问比较慢，请耐心等待)
https://techui.net 

这个是lite，免费版的
https://github.com/ayin86/techui-vue3-lite

**Comment by xuwei-fit2cloud** [comment]
您好，您开发的前端框架挺不错的，我们先研究一下。如果可以的话，还是很希望能和您合作的。

**Comment by jay86cn** [comment]
非常感谢您的回复，有问题请随意联系我，我的微信是 ayin86cn 如果需要海外的联系方式，可以再我的github中readme最下方找到。我的框架特性特点特别多，只是看图片和查看Demo并无法了解到更多的细节功能，所以也可以通过腾讯会议安排一次演示。

期待您的回复！

**Comment by xuwei-fit2cloud** [comment]
好的，已添加，保持联系。
