### ISSUE TITLE
能不能彻底关闭手机端界面，在手机端界面为空面板的情况下还是会转跳到手机端。

### ISSUE THREAD

**Issue by yixunwl** [dataease/dataease#5856]
电视属于安卓系统，在电视上打开链接就自动跳到手机端的界面，所以需要彻底关掉手机端界面。手机用户直接打开电脑端界面（特殊原因电视端无法修改浏览器User-Agent）

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们在后期版本中会添加一个强制PC端显示的设置。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。

**Comment by yixunwl** [comment]
感谢！！！！
