### ISSUE TITLE
[Question]源码运行项目，前端报sass错误

### ISSUE THREAD

**Issue by peiningxin312** [dataease/dataease#5858]
【前端】在本地启动和构建打包时， 都报了sass的错误。该怎么解决

   ╷
31 │       color: mix($--tag-info-color, $--color-white, $fontColorWeight);
   │              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    node_modules\element-ui\packages\theme-chalk\src\tag.scss 31:14            genTheme()
    node_modules\element-ui\packages\theme-chalk\src\tag.scss 127:5            @content
    node_modules\element-ui\packages\theme-chalk\src\mixins\mixins.scss 121:7  m()
    node_modules\element-ui\packages\theme-chalk\src\tag.scss 126:3            @content
    node_modules\element-ui\packages\theme-chalk\src\mixins\mixins.scss 83:5   b()
    node_modules\element-ui\packages\theme-chalk\src\tag.scss 94:1             @import
    node_modules\element-ui\packages\theme-chalk\src\select.scss 6:9           @import
    node_modules\element-ui\packages\theme-chalk\src\pagination.scss 4:9       @import
    node_modules\element-ui\packages\theme-chalk\src\index.scss 2:9            @import
    src\styles\variables.scss 26:9                                             @import
    src\styles\de-tabs.scss 3:12                                               @import
    stdin 61:9                                                                 root stylesheet

Deprecation Warning: $weight: Passing a number without unit % (0) is deprecated.

To preserve current behavior: $weight * 1%

More info: https://sass-lang.com/d/function-units

**Comment by xuwei-fit2cloud** [comment]
会影响项目运行吗？

**Comment by peiningxin312** [comment]
不影响，看着难受

**Comment by dataeaseShu** [comment]
@peiningxin312 你可以尝试修复一下 https://blog.csdn.net/hcb1998/article/details/130244147

**Comment by liaoliaojun** [comment]
> @peiningxin312 你可以尝试修复一下 https://blog.csdn.net/hcb1998/article/details/130244147

这个方案不行
