### ISSUE TITLE
建议时间控件可以精确到秒

### ISSUE THREAD

**Issue by ynzzxc** [dataease/dataease#586]
（1）对于大部分互联网企业，日期控件精确到天其实已经够用了，因为数据几乎都是按自然日汇总的；但也有很多行业，不是按自然日汇总数据的，就要麻烦一点。
（2）时间控件结合sql变量，做实时分析真的方便，这对发展中的公司很重要，他们的业务系统往往不完善，也基本都是增量用户（这点帆软做的比较人性化，虽然他们分bi和report两个产品的，单看bi还是体验不好，但集成后就很棒）。

**Comment by xuwei-fit2cloud** [comment]
感谢您的反馈，我们讨论一下这个需求。
