### ISSUE TITLE
[Feature]支持用户选择是否对指标再次进行聚合

### ISSUE THREAD

**Issue by jnfJNF** [dataease/dataease#5860]
**希望支持用户选择是否对指标再次进行聚合.**
![image](https://github.com/dataease/dataease/assets/25213350/54dcb4dc-5655-4723-b0b6-11bba7956b48)

**Comment by xuwei-fit2cloud** [comment]
你好，我们先内部讨论一下。

**Comment by jnfJNF** [comment]
有太多场景需要这个功能，指标数据都是统计好的，如果再次使用组件去聚合数据没法满足业务，可以新增一个“无”选项，就算报错了，用户自己也可以找问题。

**Comment by xuwei-fit2cloud** [comment]
您能举例说明一下具体场景吗？我们讨论后觉得这个选项似乎没有意义。

**Comment by jnfJNF** [comment]
例如我已有的接口或数据源仓库对某些数据已经进行了聚合计算，或业务场景的数据已经是聚合归纳的数据指标，只需要在dataease里面进行展示，不需要进行二次聚合。




995224106
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataease/dataease"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月11日(星期五) 下午4:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataease/dataease] [Feature]支持用户选择是否对指标再次进行聚合 (Issue #5860)





 
您能举例说明一下具体场景吗？我们讨论后觉得这个选项似乎没有意义。

**Comment by yayanpei-fit2cloud** [comment]
如果数据集是根据维度聚合后的结果，那么在制作图表时，任何的聚合方式，都不影响最终的结果。

Issue我们就先进行关闭了，再次感谢您的关注和支持。
