### ISSUE TITLE
DataEase has a SQL injection vulnerability that Not affected by SQL injection blacklists

### ISSUE THREAD

**Issue by Devotes** [dataease/dataease#5861]
Impact

DataEase has a SQL injection vulnerability that Not affected by SQL injection blacklists

The SQL statement is located in the following file location, using the ${} symbol.
https://github.com/dataease/dataease/blob/dev/backend/src/main/java/io/dataease/ext/query/GridSql.xml
![image](https://github.com/dataease/dataease/assets/46367664/6861ddf0-a1c2-4925-882c-49104d7927ea)

The SQL injection blacklist is as follows:

Pattern pattern = Pattern.compile("(.*\\=.*\\- \\-.*)|(.*(\\+).*)|(.*\\w+(%|\\$|#|&)\\w+.*)|(.*\\|\\|.*)|(.*\\s+(and|or)\\s+.*)" + "|(.*\\b(select|update|union|and|or|delete|insert|trancate|char|into|substr|ascii|declare|exec| count|master|into|drop|execute|sleep|extractvalue|updatexml|substring|database|concat|ra nd|gtid_subset)\\b.*)"); Matcher matcher = pattern.matcher(orders.toLowerCase());

Not affected by SQL injection prevention at this location
![image](https://github.com/dataease/dataease/assets/46367664/1eeefd6b-178a-471b-bfbb-e22f1cf77d54)

So we can get the database data
![image](https://github.com/dataease/dataease/assets/46367664/7d947dd3-3743-4bdb-9343-ce09a3b95be8)

Affected versions: <= 1.18.9

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复；
