### ISSUE TITLE
[Feature]希望在仪表板中鼠标悬浮视图时不要有选中的边框效果

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#5863]
**客户的大屏样式非常简单，主要是表格展示，一个仪表板中可能由一个或几个表格组成，当鼠标悬浮在视图上时希望不要有选中的边框效果，目前我们是不支持去掉这个设置的，希望可以增加该功能，让客户有自由选择的空间。（此客户为意向客户）**

如下图，红框内的视图已经去掉所有边框效果，但在全屏预览状态，鼠标悬浮后仍然出现了选中边框的效果：
![image](https://github.com/dataease/dataease/assets/77324661/c2413393-7b0a-4692-b9e4-fb8157e0cb56)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们考虑一下如何优化。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
