### ISSUE TITLE
DataEase has an arbitrary file viewing vulnerability

### ISSUE THREAD

**Issue by Devotes** [dataease/dataease#5864]
Impact

DataEase has an arbitrary file viewing vulnerability, which allows attackers to view application configuration files in a Windows environment

Affected controller

https://github.com/dataease/dataease/blob/dev/backend/src/main/java/io/dataease/controller/staticResource/StaticResourceController.java
![image](https://github.com/dataease/dataease/assets/46367664/1238e041-8210-48cd-ad1a-c1d177b4f646)

Description

1、The system extracts the file name corresponding to the last / symbol in the file path, and cannot use ../ for directory jump in Linux environments
![e48298c565d03d5e85f52ff59edd719c](https://github.com/dataease/dataease/assets/46367664/f20fa237-866b-45fe-8640-4ea35b1060aa)

2、You can use ..\ for directory redirection
![0da5c656f44c2fbc40c11f904ab5e49c](https://github.com/dataease/dataease/assets/46367664/61a9a77f-a066-447a-a39c-98842d1de84d)

![cbf17b94c9e2a7633f0a16956c4f63bd](https://github.com/dataease/dataease/assets/46367664/011a6ce5-044b-418c-92b0-e0b2c32f70ea)

3、when the application is deployed in a Windows environment, attackers can use ..\ to perform directory jumps to read server configuration files
![d](https://github.com/dataease/dataease/assets/46367664/669ad537-bedf-407e-b849-0548ff3082b5)

Affected versions: <= 1.18.9

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尽快修复。
