### ISSUE TITLE
[Feature] 视图报错日志处理

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5865]
**请描述您的需求或者改进建议.**
仪表板上存在数据源校验失败的数据集时，日志打印频率变高，后台日志会有很多很多，撑满磁盘，能不能减少相关的重复日志输出

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们考虑一下减少日志内容的输出。
当遇到DataEase占用了大量磁盘空间的情况时，可以使用 dectl clear-images 和 dectl clear-logs 命令清理一下DataEase运行过程中产生的日志和无用的镜像。

**Comment by MaekBlack** [comment]
<img width="434" alt="image" src="https://github.com/dataease/dataease/assets/45852479/2e131e2d-de2b-4469-b67e-c4c1b8e5bd9a">

希望clear-logs命令添加有关清理容器日志的内容

**Comment by xuwei-fit2cloud** [comment]
我们会做一下相关优化：
1. 减少不必要的错误信息输出
2. 可以配置日志文件的数量及大小

**Comment by xuwei-fit2cloud** [comment]
v1.18.15版本可以在 dataease.properties里配置logging.file.history和logging.file.size，分别对应日志保存的天数和文件大小
例如：
logging.file.history=30
logging.file.size=50MB
