### ISSUE TITLE
[Feature] 仪表板层面的轮播

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5867]
**请描述您的需求或者改进建议.**
一个仪表板不能完整的叙述一个故事，能否支持多个仪表板关联，进行轮播操作

**Comment by xuwei-fit2cloud** [comment]
当前版本还没有支持仪表板的轮播，但您可以试试使用选项卡组件制作多个页面来进行轮播。

**Comment by xuwei-fit2cloud** [comment]
仪表板的轮播我们在2.x版本中考虑一下。
