### ISSUE TITLE
[Bug] 在标签打开的情况下，如果值不在轴值范围内，标签依旧展示

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5868]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
在标签打开的情况下，如果值不在轴值范围内，标签依旧展示

**Bug 重现步骤(有截图更好)**
<img width="1049" alt="image" src="https://github.com/dataease/dataease/assets/45852479/5d5dba42-0f49-406b-85db-b0ae360dbba0">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们后期的改进方案：如果数值超出了设置的轴值范围，则轴值范围设置失效。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
