### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by lean-wang** [dataease/dataease#5869]
**请描述您的问题.**
你好，我使用本地安装之后，直连模式没有问题，但是切换到定时同步报如下错，也尝试将文档中的access denied for user 'root'(using password:YES)这个问题解决完成，现在不报ccess denied for user 这个错误，现在报这个
SQL ERRORerrCode = 2, detailMessage = There is no scanNode Backend available.[10003: not alive]，我查看docker 容器的状态，发现  doris-be 的状态为unhealthy，也尝试重启该容器，但是依然报这个错误，请问我该怎么办？

**Comment by chenwenhang** [comment]
@lean-wang 同学，我也遇到这个问题了，请教下你后来是怎么解决的呀？

**Comment by lean-wang** [comment]
> @lean-wang 同学，我也遇到这个问题了，请教下你后来是怎么解决的呀？
换支持axv2指令集的机器就行
