### ISSUE TITLE
[Bug]cluster 模式下已配置好 Redis，升级后dataease.properties 文件会还原

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5870]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**
cluster 模式下，dataease.properties 文件已配置好 Redis，每次升级后dataease.properties 文件都会还原，包括 Redis 的信息都回清空。
曾尝试在.env 下添加 Redis 配置信息，但Redis 有单机、哨兵和集群模式，无法预知用户使用 Redis模式；
产品团队有没有好的方法来保持dataease.properties 文件中的 Redis 配置不被升级清空？

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
DataEase在每次升级的时候，会根据之前的设置去替换安装包里配置文件的相关值，但redis设置这块没有加上相关处理，我们后续版本处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
