### ISSUE TITLE
[Bug]文本过滤组件反复拖放多个字段时，备选内容会变化

### ISSUE THREAD

**Issue by ds6686** [dataease/dataease#5871]
**DataEase 版本**
1.18.8
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
360X
谷歌浏览器
360急速浏览器

**Bug 描述**
文本下拉组件，同一字段，多次作为筛选字段，备选内容会有变化，且在仪表盘下拉选择时，备选内容又会和添加时不同

**Bug 重现步骤(有截图更好)**
1.添加不同筛选字段前
![image](https://github.com/dataease/dataease/assets/141817831/71c53986-bbcf-4b8f-b4d4-a75924d971bd)

2.添加筛选字段后
![image](https://github.com/dataease/dataease/assets/141817831/56b36214-c24c-4f51-a4b5-694c511b4213)

3.删除后再添加同一字段
![image](https://github.com/dataease/dataease/assets/141817831/18b0a0d5-b2ee-45aa-b953-2f0b54e0f402)
4。在仪表盘上下拉选择时
![image](https://github.com/dataease/dataease/assets/141817831/333735d8-63fd-41fe-9bdd-9114fe8c0b30)

**Comment by ds6686** [comment]
最后一个图是在仪表盘下拉选择时看到的，又会和添加筛选时看到的不同

**Comment by BBchicken-9527** [comment]
感谢反馈，请问一下你数据格式就是xx,xx,xx,xx,xx.....这样的格式吗？还有是什么类型数据源的数据集呢？

**Comment by BBchicken-9527** [comment]
感谢反馈，由于你长时间没有回复并且测试环境中没有复现你说的问题，我这边暂时先给你这个问题关闭，若你更新之后还存在此处问题可以打开或在官方群中联系我们，期待你的反馈；

**Comment by ds6686** [comment]
都是这种xx,xx,xx,xx,xx.....这样的格式
