### ISSUE TITLE
[Feature]横向堆叠柱状图希望按照数值排序

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#5872]
**请描述您的需求或者改进建议.**
横向堆叠柱状图希望按照数值排序
![wecom-temp-24351-ce24b3ce6e235c12eebc50b5fe94fe2f](https://github.com/dataease/dataease/assets/133861755/33ea4d6b-931c-4a70-b01f-552621090918)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下看能否实现。

**Comment by xuwei-fit2cloud** [comment]
我们在后续版本中支持。
