### ISSUE TITLE
[Feature]明细表想要实现没有表头的列表，表头希望可以隐藏

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#5873]
**请描述您的需求或者改进建议.**
明细表想要实现没有表头的列表，表头希望可以隐藏
![wecom-temp-84817-d2a9a07fbb61b7f1476acddcddbd7e10](https://github.com/dataease/dataease/assets/133861755/9e8244d5-669e-4a96-a615-3ef83c67a377)

**Comment by xuwei-fit2cloud** [comment]
技术上可以实现，我们后续版本考虑增加一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
