### ISSUE TITLE
[Feature]希望有类似动态面板的功能

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#5874]
**请描述您的需求或者改进建议.**
希望有类似动态面板的功能，点击可以进行图表切换
<img width="365" alt="wecom-temp-74155-dcd396ec1812e38fadf4a958ef637ec1" src="https://github.com/dataease/dataease/assets/133861755/d85688f9-c568-40f9-aea1-7565e6a8c603">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个首先需要DataEase的视图可以支持切换指标，然后才可以实现切换指标的联动效果。这个需求短期内可能还无法支持。
