### ISSUE TITLE
[Feature]明细表/透视表希望可以设置行背景或不同的颜色进行区分

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#5875]
**请描述您的需求或者改进建议.**
明细表/透视表希望可以设置行背景或不同的颜色进行区分
<img width="358" alt="image" src="https://github.com/dataease/dataease/assets/133861755/392c3dc8-4851-4d9c-bfbf-3bd6fad54b96">

**Comment by xuwei-fit2cloud** [comment]
不同颜色的需求已经记录，我们在后续版本中会尝试处理。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
