### ISSUE TITLE
[Feature]仪表板列表希望可以增加排序功能

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#5876]
**请描述您的需求或者改进建议.**
仪表板列表希望可以增加排序功能
![wecom-temp-51408-967cb36d44c3d57c6fcd47b84218a42a](https://github.com/dataease/dataease/assets/133861755/5fba603f-f739-4eab-a499-d283b719a81b)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，短期内还没有相关支持计划，先加入到2.x的需求池中。
