### ISSUE TITLE
[Feature]希望柱形图有超过某一个值变成其他颜色的配置，或者随着数值变化逐渐变成其他颜色

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#5878]
**请描述您的需求或者改进建议.**
希望柱形图有超过某一个值变成其他颜色的配置，或者随着数值变化逐渐变成其他颜色
![wecom-temp-23144-f56ecf4f42d78cf1edf13668d99a7d19](https://github.com/dataease/dataease/assets/133861755/7115960b-5412-4185-94bc-f50a753c4ee7)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下。建议您先使用辅助线作为参考值。

**Comment by xuwei-fit2cloud** [comment]
我们后续考虑支持柱状图的阈值。

**Comment by fit2cloudrd** [comment]
暂时无法支持。
