### ISSUE TITLE
[Bug]在不同的dataease之间将看板以应用的形式进行迁移后，再次编辑其数据集会报错

### ISSUE THREAD

**Issue by aihpossssssssssssssssssssssss** [dataease/dataease#5880]
**DataEase 版本**
1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
火狐 90.0

**Bug 描述**
以应用的形式将仪表板从一个dataease服务迁移到另一个dataease服务后，在新的服务中编辑其数据集，会无法保存且报错

**Bug 重现步骤(有截图更好)**
1.将服务1中的仪表板导出为应用（仪表板的数据集是关联数据集），然后迁移至服务2
2.在服务2中编辑该仪表板的对应的数据集，会报错：
![图片](https://github.com/dataease/dataease/assets/39285782/8ccc2ac1-0c65-49b6-b9cd-2c8de58478de)

**Comment by BBchicken-9527** [comment]
由于不可控的原因，用户自行打包或者二次开发产生的问题请用户自行研究解决。这里先把issue关掉。如果后面建议用官方镜像和官方安装方式再出现问题可以再打开issue。
