### ISSUE TITLE
[Bug] ck数据源，带有with的sql语句使用参数，可以预览，但是保存失败

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5882]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
ck数据源(version 21.1.3.32)，带有with的sql语句使用参数，可以预览，但是保存失败

**Bug 重现步骤(有截图更好)**
<img width="1452" alt="image" src="https://github.com/dataease/dataease/assets/45852479/b049654e-cf1b-4b3b-bc31-0e8e2114288e">

**Comment by BBchicken-9527** [comment]
感谢反馈，感谢反馈目前暂时不支持过于复杂的sql语句中使用参数化，我们会继续完善此处功能，但目前短期无法做出改变；
