### ISSUE TITLE
[Feature] 期望在趋势图标Hover上支持排序

### ISSUE THREAD

**Issue by guodage** [dataease/dataease#5883]
1. Hover样式排序
目前Hover上的样式：
<img width="131" alt="image" src="https://github.com/dataease/dataease/assets/5564268/31e43584-5037-4cf8-b100-ac339223ef45">

像Grafana一样，支持简单的升降序配置。
<img width="59" alt="image" src="https://github.com/dataease/dataease/assets/5564268/a97f3e77-086a-45cd-bddd-dc7e201a7d6e">

2. 趋势线条是否可以提供指定仅展示某一项的能力，也类似Grafana，目的是为了方便看某一项的具体趋势，否则当多个线条的数值相差过大时，底部线条会堆积起来，很不直观。而且目前提供的，点击后隐藏某一个线条的功能，几乎也用不上。
此类功能确实可能和不同的用户习惯有关，因此建议支持用户可配。

如图，底部堆在一起，想看的话，目前只能一个一个隐藏掉。
<img width="954" alt="image" src="https://github.com/dataease/dataease/assets/5564268/1b0c3caf-7439-42cf-b632-aa811d4e3eaa">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们尝试在后续版本中支持一下hover排序
