### ISSUE TITLE
[Feature]雷达图希望可以自行设置最大最小值

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#5886]
**请描述您的需求或者改进建议.**
雷达图希望可以自行设置最大最小值
![wecom-temp-29978-94cf65a18f4d2e71cfffc09fc75da93b](https://github.com/dataease/dataease/assets/133861755/a2f7fe5f-d09f-4082-b7ce-c125bd8eabc6)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已经在需求池中，后面会在版本中规划实现。

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #5607
