### ISSUE TITLE
[Feature] 系统管理侧，权限配置增加消息中心菜单选项

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5888]
**请描述您的需求或者改进建议.**
系统管理侧，权限配置增加消息中心菜单选项
<img width="739" alt="image" src="https://github.com/dataease/dataease/assets/45852479/da338a39-5262-4c16-9eae-a34511cfa024">

**Comment by xuwei-fit2cloud** [comment]
消息原本就是给所有用户使用的，每个用户只能看到自己权限范围内的消息。目前我们并没有相关的支持计划。
