### ISSUE TITLE
[Bug]【仪表板】明细表横向滚动条显示 BUG

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#5889]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
当分页设置的明细表（Echarts 图库）压缩到一定程度时滚动条会消失，如下图

**Bug 重现步骤(有截图更好)**
1.正常时
![image](https://github.com/dataease/dataease/assets/24768910/d2f28c6c-cb68-47f0-a2a9-3d86f66ec25e)

2.非正常时
![image](https://github.com/dataease/dataease/assets/24768910/225c256a-58a6-4f0e-b980-10a2fba96023)

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。

**Comment by BBchicken-9527** [comment]
由于尝试见没有反馈，我们将关闭这个问题，若你依旧未解决可将问题重新打开或再公众群中联系我们的同学，期待你的反馈；
