### ISSUE TITLE
[Bug] 曲线数据总是会取整，无法设置

### ISSUE THREAD

**Issue by skyqsk1** [dataease/dataease#5890]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome

**Bug 描述**
曲线总是会取整，无法设置，不能正确显示曲线。
用曲线图展示的话，值只能是1或者2， 导致都是直线。 用表格取数的话可以看见原始数据是没问题的

**Bug 重现步骤(有截图更好)**
目标曲线
<img width="1423" alt="image" src="https://github.com/dataease/dataease/assets/14859076/b55d9c9a-a55a-48d1-b330-bdf3931e1007">

目前
<img width="1483" alt="image" src="https://github.com/dataease/dataease/assets/14859076/000e1940-28f3-4445-ab96-a02666c69b12">

<img width="1463" alt="image" src="https://github.com/dataease/dataease/assets/14859076/93d8897d-b719-4e32-a719-2591afb51fee">

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。

**Comment by BBchicken-9527** [comment]
由于这个问题长时间没有得到响应我这边再是先将这个问题关闭，如果依然存在这个问题可以将这个问题打开或在官方群中联系我们的同学解决，感谢你的反馈与支持；
