### ISSUE TITLE
[Feature]仪表板设置外部参数过滤与仪表板中筛选框默认值冲突时，报表数据显示为空

### ISSUE THREAD

**Issue by aihpossssssssssssssssssssssss** [dataease/dataease#5891]
为仪表板设置外部参数A，关联仪表板中表格中的a字段，并在公共链接url中添加过滤条件{“A”:“value1”}，与此同时，仪表板内部有一个对a字段进行筛选的文本筛选框，且其默认值为value2。这时用带过滤条件的公共链接打开报表时，查看到的数据就是空。有没有方法能让有外部参数时，仪表板过滤组件中的值默认设置为外部参数的值？

**Comment by xuwei-fit2cloud** [comment]
这个是外部参数与仪表板内的过滤组件谁先生效的问题，我们先讨论一下，然后做一下相关优化。

**Comment by xuwei-fit2cloud** [comment]
我们后期做一下调整，在设置页面可以选择需要关联的过滤组件。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
