### ISSUE TITLE
[Bug]导出应用若包含无效数据集应禁止导出

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#5892]
**DataEase 版本**
V1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新

**Bug 描述**
当仪表板中的视图使用了已删除的数据集，导出为应用并使用此应用新建仪表板时会报错。报错如图
![image](https://github.com/dataease/dataease/assets/30886198/68e27444-18dd-409b-846c-3cffd6c69a07)

**Bug 重现步骤(有截图更好)**
1.新建多个直连 SQL 数据集
2.使用所有新建的数据集创建仪表板，制作视图
3.删除其中一个数据集
4.将仪表板导出为应用
5.将应用导入系统，并使用此应用新建仪表板
6.系统会提示错误：

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
