### ISSUE TITLE
[Question]可以支持https部署吗？

### ISSUE THREAD

**Issue by xiaoxiao261258** [dataease/dataease#5893]
**请描述您的问题.**
当前的安装部署文档只有http部署，是否可以提供https部署的guide？

**Comment by xuwei-fit2cloud** [comment]
请参考示例：
```nginx
server {
    listen 443 ssl;
    ssl_certificate /PATH/YOUR_CERT;
    ssl_certificate_key /PATH/YOUR_KEY;
    server_name  YOUR_DOMAIN;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_redirect http:// $scheme://;
    proxy_connect_timeout 500s;
    proxy_read_timeout 500s;
    proxy_send_timeout 500s;
    location / {
        proxy_pass http://YOUR_SERVER_IP:PORT;
        client_max_body_size 1000m;
        access_log off;
    }
}
```

**Comment by xiaoxiao261258** [comment]
> 请参考示例：
> 
> ```nginx
> server {
>     listen 443 ssl;
>     ssl_certificate /PATH/YOUR_CERT;
>     ssl_certificate_key /PATH/YOUR_KEY;
>     server_name  YOUR_DOMAIN;
>     proxy_set_header Host $host;
>     proxy_set_header X-Forwarded-For $remote_addr;
>     proxy_set_header X-Forwarded-Host $server_name;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-Proto $scheme;
>     proxy_redirect http:// $scheme://;
>     proxy_connect_timeout 500s;
>     proxy_read_timeout 500s;
>     proxy_send_timeout 500s;
>     location / {
>         proxy_pass http://YOUR_SERVER_IP:PORT;
>         client_max_body_size 1000m;
>         access_log off;
>     }
> }
> ```

你好，我之前的配置方法如下，对比了下示例，发现 location少了很多，是不是应该基于你提供的示例，把这两个merge一下？
   ```

   server {
        listen       12000;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;
    location / {
        root    /opt/dataease/frontend/dist/;
        index   index.html;
    }

    location /app.html {
        root    /opt/dataease/mobile/dist/;
    }

    location /de-app/ {
        alias   /opt/dataease/mobile/dist/;
    }

    location /de-api/ {
        proxy_pass http://localhost:8081/de-api/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host:12000;
        server_name_in_redirect on;
    }
}
```

**Comment by xiaoxiao261258** [comment]
> > 请参考示例：
> > ```nginx
> > server {
> >     listen 443 ssl;
> >     ssl_certificate /PATH/YOUR_CERT;
> >     ssl_certificate_key /PATH/YOUR_KEY;
> >     server_name  YOUR_DOMAIN;
> >     proxy_set_header Host $host;
> >     proxy_set_header X-Forwarded-For $remote_addr;
> >     proxy_set_header X-Forwarded-Host $server_name;
> >     proxy_set_header X-Real-IP $remote_addr;
> >     proxy_set_header X-Forwarded-Proto $scheme;
> >     proxy_redirect http:// $scheme://;
> >     proxy_connect_timeout 500s;
> >     proxy_read_timeout 500s;
> >     proxy_send_timeout 500s;
> >     location / {
> >         proxy_pass http://YOUR_SERVER_IP:PORT;
> >         client_max_body_size 1000m;
> >         access_log off;
> >     }
> > }
> > ```
> 
> 你好，我之前的配置方法如下，对比了下示例，发现 location少了很多，是不是应该基于你提供的示例，把这两个merge一下？
> 
> ```
> 
> server {
>      listen       12000;
>      server_name  localhost;
> 
>      #charset koi8-r;
> 
>      #access_log  logs/host.access.log  main;
>  location / {
>      root    /opt/dataease/frontend/dist/;
>      index   index.html;
>  }
> 
>  location /app.html {
>      root    /opt/dataease/mobile/dist/;
>  }
> 
>  location /de-app/ {
>      alias   /opt/dataease/mobile/dist/;
>  }
> 
>  location /de-api/ {
>      proxy_pass http://localhost:8081/de-api/;
>      proxy_set_header X-Real-IP $remote_addr;
>      proxy_set_header Host $host:12000;
>      server_name_in_redirect on;
>  }
> }
> ```

已经调试ok，忽略
