### ISSUE TITLE
[Feature]导出Excel增加导出明细数据的功能

### ISSUE THREAD

**Issue by seanwwh** [dataease/dataease#5894]
希望在下载Excel的地方增加可以导出明细数据的功能，类似Tableau这样，可选择导出视图数据还是原始的明细数据

![WechatIMG6](https://github.com/dataease/dataease/assets/5187541/981ef070-b884-4559-9d70-4209cacb351a)
![WechatIMG7](https://github.com/dataease/dataease/assets/5187541/09999612-173a-464e-b3dc-db8cbf84ef64)
![WechatIMG17](https://github.com/dataease/dataease/assets/5187541/5481b221-4e5c-41de-ad84-38e482dd528b)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前我们的数据导出功能主要是在数据集模块中支持的，如果需要导出明细数据，可以在数据集中导出。关于在视图侧直接导出明细数据的需求，我们需要再讨论一下是否给与支持。

**Comment by seanwwh** [comment]
> 感谢反馈，目前我们的数据导出功能主要是在数据集模块中支持的，如果需要导出明细数据，可以在数据集中导出。关于在视图侧直接导出明细数据的需求，我们需要再讨论一下是否给与支持。

在视图直接导出是与视图中筛选条件一致的结果，便于用户导出明细数据进行核对或进一步分析，如果在数据集中导出，需要重新选择筛选条件，不够方便直观，另外数据集的权限不一定开放给普通用户。

**Comment by xuwei-fit2cloud** [comment]
视图这边展示的是聚合后的结果，如果选择的是展示部分数据的话，我们这边并不好得到所有参与计算的具体明细数据。
要支持视图导出明细数据的话，我们是可以做到导出该视图的全部明细数据（带过滤条件）。

**Comment by xuwei-fit2cloud** [comment]
暂时没有相关的支持计划。
