### ISSUE TITLE
[Bug] SQL 数据集 ES 数据源导出数据错误

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#5896]
**DataEase 版本**

1.18.9
**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 已是最新版本
版本 115.0.5790.170（正式版本） (arm64)

**Bug 描述**
在 SQL 数据集 使用数据导出，在使用导出条件为枚举类型的时候，报错

**Bug 重现步骤(有截图更好)**
1.
![英卡](https://github.com/dataease/dataease/assets/109720729/3fdb5315-07b9-433b-bbc0-2c13ae8d8f58)

2.
![英卡2](https://github.com/dataease/dataease/assets/109720729/48c7c913-5e69-458f-ab7a-fdcab85b974b)

3.

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在后续版本修复这个问题。
