### ISSUE TITLE
[Feature]视图和仪表盘里的柱状图横轴字段显示不全

### ISSUE THREAD

**Issue by songrui88** [dataease/dataease#59]
**请描述您的需求或者改进建议.**
柱状图比如较小的时候，横轴只能显示2个字，拉大后可显示全。缩小的时候，直接就缺失，建议显示第一个字。
<img width="352" alt="2" src="https://user-images.githubusercontent.com/46080992/123533601-49763480-d749-11eb-9f29-5a010b4f83d0.png">

**Comment by xuwei-fit2cloud** [comment]
可以设置横轴文字的倾斜度
