### ISSUE TITLE
[Bug]编辑仪表板时符号地图总是跟随鼠标移动

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#5901]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
在仪表板的编辑界面下，鼠标事件点击进入符号地图，地图便会跟随鼠标移动，但鼠标实际上并未操作组件可移动范围（四个边）。

https://github.com/dataease/dataease/assets/48945409/bccf1fcd-b3e0-4c0d-accf-cad5913623a2

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
