### ISSUE TITLE
[Feature] 定时报告仪表板渲染增加渲染时间相关配置项

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5902]
**请描述您的需求或者改进建议.**
目前写死的渲染时间可能会导致加载不全
<img width="1423" alt="image" src="https://github.com/dataease/dataease/assets/45852479/f5237e2d-94c5-4147-b6cb-c61dea62f502">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈。更好的办法应该是找到图形渲染结束的事件，设置渲染时间并不是一个好的解决方案。我们还在研究如何处理。

**Comment by xuwei-fit2cloud** [comment]
已增加配置项。
