### ISSUE TITLE
API接口配置需求

### ISSUE THREAD

**Issue by xianzifeng** [dataease/dataease#5903]
目前API接口格式只支持一行多个字段拼接的方式， 但是 实际业务中， 多数情况下  数据接口的格式是不规则的，有可能是多级的级联显示，现在的版本无法满足多级显示的概念， 起不到分组或是分级的汇总，  希望可以根据支持多级显示

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是说API数据源目前无法满足你多级的级联业务吗？

**Comment by xianzifeng** [comment]
您好， 是的， 现在发现是有这个多级都在一行显示的问题， 看不出来是多级的级联关系 ，











在 2023-08-15 10:10:23，"9527" ***@***.***> 写道：

感谢反馈，你的意思是说API数据源目前无法满足你多级的级联业务吗？

**Comment by maninhill** [comment]
暂无支持计划。
