### ISSUE TITLE
[Bug]动端访问dataease仪表板，传参控件会失效，需要切换别的月份再切换回来才会生效。

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#5904]
**DataEase 版本**

V1.18.9
**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**
Chrome 已是最新版本
版本 115.0.5790.171 (正式版本) (64 位)

**Bug 描述**

**Bug 重现步骤(有截图更好)**
测试移动端初始进入不会传参。
![4f67f9d8-26e7-473b-9ba8-ca7d45795263](https://github.com/dataease/dataease/assets/127368807/532119e8-a873-4a01-bb13-8f6a6dd5650f)
![44ba8301-4ce4-4f50-9ba7-fd85a6cb2c25](https://github.com/dataease/dataease/assets/127368807/2faa0e25-10d5-4ba5-aa34-bd805e37c9ae)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
