### ISSUE TITLE
[Bug]AntV 透视表排序后数据列显示不全

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#5905]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
在AntV 的透视表中将日期放进【数据列/维度】中，不按日期排序时，日期可以全部显示，按日期排序后，日期不会全部显示。

**Bug 重现步骤(有截图更好)**
1.
<img width="1414" alt="image" src="https://github.com/dataease/dataease/assets/85436572/45bda7f2-12a4-40a2-a001-9f00a6ac3d25">

2.
<img width="1419" alt="image" src="https://github.com/dataease/dataease/assets/85436572/579801e5-0875-4241-ab79-d8ff74d996c5">

**Comment by BBchicken-9527** [comment]
感谢反馈，因为你的数据不止一千条在按照日期排序的时候会前后排序所以导致显示的日期数量不一致，如果想全部看到计算全部即可；
