### ISSUE TITLE
[Feature]按照创建好的样式导出Excel

### ISSUE THREAD

**Issue by yky888** [dataease/dataease#5906]
**请描述您的需求或者改进建议.**
目前表格导出，只能按照源数据样式进行导出，业务部门更想要的是 按照已有创建好的表格样式，进行导出
![image](https://github.com/dataease/dataease/assets/39984594/7eaf19d6-3a99-4558-b38b-897987972235)![image](https://github.com/dataease/dataease/assets/39984594/c737270b-7ff9-4956-9041-7a77aef02226)

**Comment by yky888** [comment]
图一为 透视表+汇总表样式

**Comment by yky888** [comment]
透视表+汇总表样式1
<img width="971" alt="image" src="https://github.com/dataease/dataease/assets/39984594/9eec2381-ac37-4f91-9764-14833942dc33">
现有导出样式
<img width="1205" alt="image" src="https://github.com/dataease/dataease/assets/39984594/9acd216b-a599-46a5-8ada-d37a49148937">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前受限于AntV S2图库，我们还不能按照已有表格样式进行数据的导出，还需要等待S2图库有相关支持，短期内还无法实现。
