### ISSUE TITLE
[Question]v1.18 jdk版本改回1.8源码打包出错

### ISSUE THREAD

**Issue by JefferWu** [dataease/dataease#5908]
问题如标题
![image](https://github.com/dataease/dataease/assets/53201141/22460a0a-f5ad-45cf-8cdd-be3d97107095)

![image](https://github.com/dataease/dataease/assets/53201141/247d118b-7f26-4e5c-8ed4-61528c9f1f36)

**Comment by xuwei-fit2cloud** [comment]
您可以下载sdk工程 https://github.com/dataease/dataease-extension-sdk，切换到同样的分支，自己构建一下jdk1.8的sdk试试。
