### ISSUE TITLE
[Feature] antv 表格组件支持复制

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5909]
**请描述您的需求或者改进建议.**
antv 表格组件支持复制
https://s2.antv.vision/manual/basic/analysis/copy-export

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先调研一下。

**Comment by xuwei-fit2cloud** [comment]
我们尝试过，似乎图库本身的复制功能还存在bug，无法使用。
