### ISSUE TITLE
[Bug]上传 Excel 数据集报错

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#5912]
**DataEase 版本**

1.18.9
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

谷歌
**Bug 描述**
simple 模式上传 excel 是，预览正常，保存报错，
![image](https://github.com/dataease/dataease/assets/109720729/344bd7af-0a98-44f0-9af6-1b536592c431)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在后续版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
