### ISSUE TITLE
[Feature] 仪表板外部参数允许和过滤组件联动

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5914]
**请描述您的需求或者改进建议.**
仪表板外部参数允许和过滤组件联动，如果过滤组件和外部参数对于同一视图进行不同结果的过滤，此时该视图无结果

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池中。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
