### ISSUE TITLE
[Bug]antv 柱状图

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#5915]
**DataEase 版本**

1.18.9
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
antv 标签显示遮挡

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/50f6f6cf-b4a8-4eab-903d-ddf484b57215)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
