### ISSUE TITLE
[Feature] 柱状图

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#5916]
**请描述您的需求或者改进建议.**
希望可以有一个功能，就是可以把我想要合并的柱子可以有按钮合并，而不需要我去写 sql 进行操作。类似图片的other是我写sql将一些小于某个值的数据汇总得到的

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们近期暂时没有规划进行支持。

**Comment by linyuiu** [comment]
好的
