### ISSUE TITLE
[Bug]模版市场复用模版更换中国地图为世界地图时拉入字段报错

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#5918]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
模版市场复用模版时，将模版中的中国地图为世界地图时拉入字段报错，具体报错如下，如果不拉入数据，地图显示正常

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/80c06feb-7a1c-4330-a198-049ca451b96c)

2.
![image](https://github.com/dataease/dataease/assets/109720729/e05b9243-5026-4fc5-8924-d51deec626aa)

3.

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
