### ISSUE TITLE
[Feature]建议用户可自定义是否始终以 PC 端显示

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#5919]
**请描述您的需求或者改进建议.**
**需求描述：** 建议在系统管理处增加可配置项，用户可以设置 DataEase 不论在哪里打开始终被识别为 PC 端或移动端。

**背景描述：** DataEase 仪表板是可以根据浏览器自适应展示为 PC 端或移动端的，但是在电视端展示的时候由于其也是安卓应用会被识别为移动端，此时需要手动修改浏览器 UA 配置，使其按照 PC 端。但在一些制造业企业中，工厂会采用广告机，有专门的后台发布系统，一键发布到十几台广告机上。广告机看起来跟电视差不多，但没有浏览器概念以及其他可配置的内容，导致自动识别为移动端而无法正常显示。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个需求我们之前考虑过，技术上是可以支持全局设置是否始终以某种形式展示，但因为是全局影响，所以我们想思考一种其他的解决方案，能否在具体仪表板上单独设置，但目前还没有最终结论，需要再考虑一下。
