### ISSUE TITLE
[Bug]这个页面frontend/src/components/asyncComponent/index.vue 有个非空判断不对

### ISSUE THREAD

**Issue by william-xue** [dataease/dataease#5920]
**DataEase 版本**

if (res)
const dynamicCode = res.data res;
console.log(dynamicCode,const component = new Fn(~return $fdynamicCode1~)()this .mode = component.default  component;
**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by william-xue** [comment]
![41611692175280_ pic](https://github.com/dataease/dataease/assets/20151622/7b3638bd-b711-49e0-88c2-9f37b65b3a6f)
dynamicCode不能是个空对象 
if(res&&res.data)目测目前是好的

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by dataeaseShu** [comment]
判断没问题 逻辑是插件优先加载res.data 否则加载res。if(res&&res.data)会导致res丢失
