### ISSUE TITLE
[Bug]在全屏预览下过滤组件，靠右放置会出现错位和无法显示的情况/文本下拉会一个空位

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#5922]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**

Chrome 已是最新版本
版本 116.0.5845.97（正式版本） （64 位）

**Bug 描述**

在全屏预览下时间范围组件，靠右放置会出现错位和无法显示的情况，编辑已经在仪表板预览的时候不会出现

**Bug 重现步骤(有截图更好)**
1.正常情况下
![image](https://github.com/dataease/dataease/assets/127368807/78a33452-0cd8-47b1-8fe5-3b19199ad7c6)

2.全屏预览错位情况
![image](https://github.com/dataease/dataease/assets/127368807/703ea2b7-58f6-4cfb-9076-3c48a06dc4da)

3.全屏预览点击不显示
![image](https://github.com/dataease/dataease/assets/127368807/4b58caf4-b859-46ab-92be-cdecf93c1e81)

**Comment by greenyhsj** [comment]
文本组件有一个空位，靠右的组件也是出不来
![image](https://github.com/dataease/dataease/assets/127368807/1f4ee247-0512-4400-9fa5-3378d67b16bb)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
