### ISSUE TITLE
[Feature]跳转中只能设置一个仪表板，想要跳转多个仪表板

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#5923]
**请描述您的需求或者改进建议.**
目前的跳转仪表板是一个视图只能选择一张仪表板，想要类似根据点击不同维度的值来分别跳转不同仪表板。
比如一个饼图展示第一产业、第二产业、第三产业的情况，点击分别跳出到对应的仪表板

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
从技术角度来说是可以支持的，类似我们的自定义排序、自定义颜色。但我们还需要想想交互上如何设计，短期内还没有相关计划。
