### ISSUE TITLE
[Feature] 跳转和过滤组件允许配合使用

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5924]
**请描述您的需求或者改进建议.**
在通过跳转过来的大屏上使用过滤组件，如果跳转配置的字段和过滤组件的相同，此时跳转过来的页面上进行过滤就不会得到正确的结果
跳转配置允许和过滤组件配合使用
https://github.com/dataease/dataease/assets/45852479/15392e3e-f5f4-4f03-813f-740934ab7825

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们考虑在跳转设置上，允许设置过滤组件的关联字段，在后期版本会实现。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
