### ISSUE TITLE
[Bug] 多个视图使用同一个数据集且字段较多的情况下，配置联动页面时直接崩溃

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5926]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
多个视图使用同一个数据集且字段较多的情况下，配置联动时页面直接崩溃

**Bug 重现步骤(有截图更好)**
https://github.com/dataease/dataease/assets/45852479/213f3933-1c21-4865-aa76-dc623a7345e2

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
