### ISSUE TITLE
[Bug] simple模式下，日期格式化后，数据集预览可以，视图制作没有正确格式化

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5927]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
simple模式下，日期格式化后，数据集预览可以，视图制作没有正确格式化

**Bug 重现步骤(有截图更好)**
1.数据预览
![image](https://github.com/dataease/dataease/assets/45852479/92851e0f-35c6-41e2-be27-84894c1b6bb2)
2.计算字段编辑页面
![image](https://github.com/dataease/dataease/assets/45852479/2ef4e195-0a65-4586-aee7-e3614d0fd5e0)
3.字段管理页面
![image](https://github.com/dataease/dataease/assets/45852479/85b6c4ab-db07-40c3-8dfe-f41517255500)
4.视图制作
![image](https://github.com/dataease/dataease/assets/45852479/fc388748-8f3a-46b5-bad0-7a725bb3681b)
5.视图使用sql及查询结果
![image](https://github.com/dataease/dataease/assets/45852479/c954ad8f-8d3a-4750-91ce-d065a138a54d)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在后续版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
