### ISSUE TITLE
[Feature]数据集支持设置预览显示条数

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5929]
**请描述您的需求或者改进建议.**
数据集这个地方，有时显示1条就行，或者不显示都可以。只检查语句是否正确就可以了

场景：SQL语句较为复杂，数据源查询效率低，每次查询速度很慢，这样编辑数据集时，每次默认查询1000条数据的效率很低，会影响数据集的编辑效率
<img width="1469" alt="image" src="https://github.com/dataease/dataease/assets/89771514/fcc731f5-48d4-4eb7-9dbd-92738d1e27d8">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，在复杂的sql语句下，点击查询，查询1条和1000条的时间差可以忽略。如果不需要预览数据，建议不要点击【运行查询】，直接点击右上角的保存。
