### ISSUE TITLE
[Bug] 升级最新v1.18.9后 下拉树控件选择后页仪表板报错io.dataease.exception.DataEaseException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by yhy729** [dataease/dataease#5931]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome 版本 116.0.5845.96（正式版本） （64 位）

**Bug 描述**
更新最新版本后下拉树组件选择后 仪表板报错。

![image](https://github.com/dataease/dataease/assets/16042766/7b9f8ff0-d3d4-4826-84e9-b4ec2218d1b0)
![image](https://github.com/dataease/dataease/assets/16042766/9cd7e8d6-fc2b-437c-95b0-5ed65512cdee)
![image](https://github.com/dataease/dataease/assets/16042766/9de276bb-4007-40f3-b0af-b0fd815e3b25)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个 版本修复这个问题。

**Comment by yhy729** [comment]
下个版本发布计划有定吗

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
