### ISSUE TITLE
[Bug]原本的定时同步SQL数据集，编辑换成其他数据源，定时同步就变成直连

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#5932]
**DataEase 版本**

v.1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

Chrome 已是最新版本
版本 116.0.5845.97（正式版本） （64 位）

**Bug 描述**

原本的定时同步SQL数据集，编辑换成其他数据源，定时同步就变成直连

用户的场景是把测试服数据源换成正式服数据源

**Bug 重现步骤(有截图更好)**

<img width="633" alt="397d89cfe455038f4346817d4766908" src="https://github.com/dataease/dataease/assets/127368807/5a3788cb-6ab6-4112-93b1-afcaf2a4d762">

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
