### ISSUE TITLE
[Feature]将不同数据源的指定表进行数据追加合并

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5933]
**请描述您的需求或者改进建议.**
有这么一种场景，数据表所在的数据源不同，但表名、表结构相同，将不同数据源的这个表进行数据合并。
我们在 2.x 版本会不会考虑这个功能？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，数据合并的需求在2.x的规划中。
