### ISSUE TITLE
[Feature]智能生成视图

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5934]
**请描述您的需求或者改进建议.**
当前 ChartGPT 比较火，某易数帆捷足先登了，做出了一款 chartBI，可以输入需求，自动生成视图；
在 2.x 会不会考虑这个功能？
![图片](https://github.com/dataease/dataease/assets/48307752/142eadf9-81ba-4bf3-bbc4-c7ce0486454a)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，近期暂时没有规划，后期可能要等2.x的版本稳定运行之后，先进性调研，再进行后面的规划。
