### ISSUE TITLE
[Bug]查询重置按钮在和选项卡一起用的时候，查询重置定位不固定，当滚动页面时会局部乱动

### ISSUE THREAD

**Issue by ds6686** [dataease/dataease#5937]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
360X
谷歌浏览器
360急速浏览器

**Bug 描述**
查询重置按钮在和选项卡一起用的时候，查询重置定位不固定，当滚动页面时会局部乱动

**Bug 重现步骤(有截图更好)**
![31943c2275c1863d4f77732e941de10](https://github.com/dataease/dataease/assets/141817831/afc6d9de-726a-4140-84f3-941a188d131f)
![60714809c87088b52a9ebe089cc2fe5](https://github.com/dataease/dataease/assets/141817831/6413ba89-0623-4597-9265-f72096d97400)

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。

**Comment by ds6686** [comment]
如果新版本没有问题，我们升级试试，之前反馈你们已经复现了的

**Comment by ds6686** [comment]
我们现在用的就是1.18.9最新版了，没有见更新版本了

**Comment by BBchicken-9527** [comment]
感谢你的反馈，你的意思是说这两个按钮跟随你的屏幕移动吗？如果是这个问题是因为按钮是悬浮模式，他是固定在仪表板中的但你的Tab组件进行滚动他的位置是不会发生改变的，所以按钮才会在滚动的时候跟随，目前Tab组件中是不支持放入按钮的；

**Comment by ds6686** [comment]
是的多tab仪表板查询和重置按钮不能加入tab只能悬浮，但在tab里的筛选组件也是悬浮，相对于tab和表格等确实位置固定的，如果查询和重置能有多个且项筛选组件一样能加入固定的tab就好了

**Comment by BBchicken-9527** [comment]
是的，我没这样设计主要是考虑到规则上是不允许存在多个按钮组件的，但如果想添加进Tab组件需要先在仪表板上创建，这样有可能会导致在同一个仪表板上创建多个按钮组件（将按钮组件拖拽或拖出Tab组件）；

**Comment by ds6686** [comment]
确实可能会。我使用时之所以将筛选和查询放在tab里，是因为将筛选和查询放在tab外时，查询筛选条件仅对当前看到的tab生效，而如问题中的图上我创建3个tab，当切换到webtab时，查询后，另外两个tab是没有根据筛选查询条件展示的，还要再次查询，但再次点查询的前提是修改筛选项，所以如果查询能对所有tab生效也可以，

**Comment by ds6686** [comment]
但再次点查询的前提是修改筛选项，所以如果可以对所有tab进行查询生效也可以，

**Comment by BBchicken-9527** [comment]
没生效可能是之前的一个接口调用顺序导致的问题和按钮没有关系，目前应该是对这里进行修复了，我在测试环境中没有看到这个问题；

**Comment by ds6686** [comment]
好的，待新版本1.18.10发布后我升级看看效果

**Comment by ds6686** [comment]
多谢！

**Comment by BBchicken-9527** [comment]
好的，那我现在将关闭这个问题，你说的需求我这边已经提交到相关负责人，感谢你的反馈和支持；
