### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by lovecove** [dataease/dataease#5938]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
连接Doris/Start Rocks数据库, 无法可视化符号地图,其他数据库(holo,mysql等)是可以的???

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。

**Comment by BBchicken-9527** [comment]
因为这个问题太长时间你没有回复所以我们决定暂时关闭这个问题，如果依然存在这个问题可以将问题重新打开或联系公众群中的同学，感谢你的反馈与支持；
