### ISSUE TITLE
[Question]配置doris数据源提示错误：Access denied for user 'root@172.19.0.4' (using password: YES)

### ISSUE THREAD

**Issue by m872384296** [dataease/dataease#5939]
在网页端配置doris数据源提示错误：Access denied for user 'root@172.19.0.4' (using password: YES)
另外，在mysql的容器中也无法连接doris-fe，具体命令如下：
`docker exec -it mysql sh`
`mysql -h doris-fe -u root -P 9030 -p`
提示错误Access denied for user 'root@172.19.0.3' (using password: YES)

但是，在doris-fe的容器中可以通过127.0.0.1连接，具体命令如下：
`docker exec -it doris-fe sh`
`mysql -h 127.0.0.1 -u root -P 9030 -p`
这个问提各位有遇到过吗

**Comment by xuwei-fit2cloud** [comment]
如果从外部浏览器访问doris-fe ui的话，需要在docker-compose文件中将fe的8030端口映射出来，并保证防火墙放行了8030端口。

从mysql容器中无法访问doris，应该是docker network有些问题，可以尝试关闭DataEase服务，重启docker服务，然后重新启动DataEase服务试试。

**Comment by f2m4** [comment]
截止到1.18.23之前的版本，只要修过mysql的密码都会有这个错误。 1.18.23已修复改错误，但是更新信息里面没有提这个。

**Comment by f2m4** [comment]
截止到1.18.23之前的版本，只要修过drios的密码都会有这个错误。 1.18.23已修复改错误，但是更新信息里面没有提这个。
