### ISSUE TITLE
[Bug]文本下拉组件，同一字段，多次作为筛选字段，备选内容会有变化，且在仪表盘下拉选择时，备选内容又会和添加时不同

### ISSUE THREAD

**Issue by ds6686** [dataease/dataease#5940]
DataEase 版本
1.18.8
1.18.9
运行方式(安装包运行 or 源码运行 ?)
安装包运行
浏览器版本
360X
谷歌浏览器
360急速浏览器
Bug 描述
文本下拉组件，同一字段，多次作为筛选字段，备选内容会有变化，且在仪表盘下拉选择时，备选内容又会和添加时不同
Bug 重现步骤(有截图更好)
1.添加不同筛选字段前
 
![image](https://github.com/dataease/dataease/assets/141817831/cfedd895-a98e-444f-9062-e3fabfe014e2)

2.添加筛选字段后
 
![image](https://github.com/dataease/dataease/assets/141817831/fdc22a2a-1d02-4832-ba8a-978e7e3b2118)

3.删除后再添加同一字段
 
![image](https://github.com/dataease/dataease/assets/141817831/612a4263-3819-4368-8ae2-c13a2111cee7)

4。在仪表盘上下拉选择时
 
![image](https://github.com/dataease/dataease/assets/141817831/999ede36-6ce4-4d8b-be6b-22c05e6b7029)

数据格式都是xx,xx,xx,xx,xx.....这样的格式

**Comment by ds6686** [comment]
之前提的关闭了，更具贵公司提示再提交一次

**Comment by BBchicken-9527** [comment]
感谢反馈，按照你的步骤我看了一下还是没有复现方便问一下你收否在微信群里我们1v1看一下呢？

**Comment by ds6686** [comment]
看了的
反馈说你们复现了，暂时无法解决

**Comment by ds6686** [comment]
看过了，已将复现步骤录屏发送过

**Comment by BBchicken-9527** [comment]
您好，目前是否还存在你说的这个问题呢？
