### ISSUE TITLE
雷达图轴线上下界的设置

### ISSUE THREAD

**Issue by czborz** [dataease/dataease#5942]
目前anTv格式雷达图与echarts格式雷达图均不能设置轴线的上界与下界，anTv格式显示上70分与80分可能一个接近上限一个接近下限，差距过大，并且无法对不同的用户实现统一的标准。可能某个用户的70 80 中的70 比另一个40 45中的40还要小，这明显有点不合理。希望能够设置统一的上界与下界，这样不同对象的数据也具有可比性，并且数据的直观显示上也能更加合理。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们在后续版本中会加入支持。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
