### ISSUE TITLE
PC端移植移动端富文本字体大小

### ISSUE THREAD

**Issue by czborz** [dataease/dataease#5943]
目前如果PC端存在富文本框，字数稍多的情况下，在PC端正常显示的字体大小在转成移动端时，字体会显示的很大，像老年机上的加大字体，十分影响美观，目前想要在移动端使用需要在PC端复制仪表板并且将字体改小，希望以后可以移动端自适应字体大小

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议我们已收到，后续会优化移动端上的展示。
