### ISSUE TITLE
[Bug]Excel数据集字段类型识别不正确

### ISSUE THREAD

**Issue by jjyy0622** [dataease/dataease#5944]
**DataEase 版本**
v1.18.8标准版

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome
版本 116.0.5845.96（正式版本） （64 位）

**Bug 描述**
EXCEL数据集导入或替换数据时，时间类型的字段会变成一串数字。
根据测试，仅在OFFICE编辑的文档会出问题，WPS编辑的文档没问题，可以显示正常的日期。
我使用的office版本是2016
**Bug 重现步骤(有截图更好)**
1.这是初次导入的数据表生成的字段，是正确的
![image](https://github.com/dataease/dataease/assets/41662971/9d53b460-61a4-43d3-a247-07c5d241ad77)

2.在替换数据的时候，被解析成数值，即使手动改字段类型也不可以
![image](https://github.com/dataease/dataease/assets/41662971/fb9bc55e-52fa-4b52-8eae-bf953661583d)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前我没发现存在你说的这个问题，我这边使用的16.75版本，如果方便的话最好是可以给我们当时使用的文件，只保留表头即可，我们自己造数据，因为excel数据相对比较特殊，他会受到版本甚至小版本的影响产生不同的结果；
