### ISSUE TITLE
[Feature]指标卡设置名称与值的”位置选项“布局不对

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#5946]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**描述**
以下截图中对于位置的设置同时控制了名称和值，但是却只有将名称的显示打开才能操作该选项。
![image](https://github.com/dataease/dataease/assets/48945409/44f2f3b4-08c4-4fbb-b1af-f31c0d206c52)

以下步骤会显得很奇怪：
1.在名称打开时设置了值和名称位于右下角；
![image](https://github.com/dataease/dataease/assets/48945409/9efb0a6b-8353-4f17-9b5b-f625c1e07801)

2.关闭了名称显示；
![image](https://github.com/dataease/dataease/assets/48945409/4e498e72-4736-4add-97f1-7b3bda7ed9ae)

3.想重新修改值的位置，此时即使不需要显示名称，但也需要先打开再名称才能修改，修改完再将名称关掉。
![image](https://github.com/dataease/dataease/assets/48945409/0b154bdf-6788-49e0-929c-5f714ac24d1a)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经加入优化清单中。

**Comment by xuwei-fit2cloud** [comment]
v1.18.12版本已处理，请升级到最新版本。
