### ISSUE TITLE
[Bug] 手机端页面，日期组件没有适配

### ISSUE THREAD

**Issue by triumph** [dataease/dataease#5947]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome，系统自带浏览器

**Bug 描述**
手机端页面，日期组件，好像没有适配，不能自由的选择上月的时间范围

**Bug 重现步骤(有截图更好)**

![b50807c1312e636beb0e625e3fb34f9](https://github.com/dataease/dataease/assets/11950/fa8051de-8dd0-4e36-ab06-568358d6002b)

**Comment by BBchicken-9527** [comment]
感谢反馈，后续版本会优化该问题。
