### ISSUE TITLE
[Bug]有选项卡的仪表板，筛选组件在选项卡里，设置默认筛选条件，初进入仪表板时不生效，手动选新的才生效

### ISSUE THREAD

**Issue by ds6686** [dataease/dataease#5949]
数易版本
1.18.9

运行方式(安装包运行还是源码运行？)
安装包运行

浏览器版本
360X
谷歌浏览器
360急速浏览器

Bug 描述
有选项卡的仪表板，筛选组件在选项卡里，设置默认筛选条件，初进入仪表板时不生效，手动选新的才生效

**Comment by BBchicken-9527** [comment]
感谢您的反馈，问题已经在处理了，我们将在下个版本修复这个问题。

**Comment by ds6686** [comment]
好的

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。

**Comment by ds6686** [comment]
好的，我们后续升级看看效果，多谢
