### ISSUE TITLE
[Feature]  DE支持目录形式的URL访问吗？

### ISSUE THREAD

**Issue by triumph** [dataease/dataease#5950]
我们是外包公司， 甲方的一个项目，只给了我们一个项目二级域名， xxx01.test.com
现在这个域名给了业务使用，我们项目也用到DE了， 现在想问下如何配置nginx和DE程序，
想使用 http://xxx01.test.com/DE/  （目录的形式)  访问BI系统。  谢谢了
【 源码编译打包，安装配置】

**Comment by xuwei-fit2cloud** [comment]
你可以试试修改一下源码，将绝对路径改成相对路径。
