### ISSUE TITLE
[Bug]下拉树选择具体值查询后报错空指针

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#5951]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
下拉树组件，选择某个值，点击查询后视图报错空指针

**Bug 重现步骤(有截图更好)**
1.
<img width="1514" alt="image" src="https://github.com/dataease/dataease/assets/57552153/768d5913-5b9c-4511-b9a0-0ac8a6ffbd1e">

2.
<img width="1240" alt="image" src="https://github.com/dataease/dataease/assets/57552153/532fbf40-640d-4fcb-9678-bce7f7885331">

3.
<img width="990" alt="image" src="https://github.com/dataease/dataease/assets/57552153/6d4ac936-4328-4dc2-a5bb-468454f20728">

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在后续版本修复这个问题。
