### ISSUE TITLE
[Bug]SQL 数据集存在多个表的相同字段导致执行报错

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5952]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
数据库客户端写好的 SQL 无法在 DE的 SQL 数据集执行，经排查此类报错场景绝大多数原因是多个表的字段名相同导致：

以下 SQL，select 两个表的 id 字段，由于没有给两个相同的字段起别名，导致报错。
select t.id,w.id from transactions t LEFT JOIN wendu w on t.id=w.id limit 10
<img width="1031" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/cf69bce5-293a-4f5a-8aec-3d42bb23e4af">

数据库客户端市可以兼容此问题的。
<img width="683" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/92545ac4-eee7-44e1-be03-9c092a796daa">

希望可以自动兼容重复字段，或者中文提示字段重复，因为大多数用户都是在数据库客户端写好 SQL 复制到 SQL 数据集中运行，忽略了字段重复的问题。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，不允许重复字段主要是考虑到用户在使用时可能会因为名称相同导致无法准确判断数据内容，不过你的意见我们也会仔细考虑的，这边我已经记录了，我们讨论一下；

**Comment by yayanpei-fit2cloud** [comment]
请问是什么类型数据源？

**Comment by mfanoffice** [comment]
> 请问是什么类型数据源？

我是 MySQL 直连

**Comment by xuwei-fit2cloud** [comment]
很抱歉，短期内我们还没有比较好的方式处理这个问题，建议自行添加alias

**Comment by mfanoffice** [comment]
V2.0 已实现
