### ISSUE TITLE
[Feature]建议优化堆叠图的排序后展示

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#5953]
**请描述您的需求或者改进建议.**
目前对堆叠图的指标排序后即不是按照堆叠总数，也不是按照某一个固定子分类。

最终呈现的排序逻辑是上面总有一个子维度的值是大于下面一个的（例如下图所呈现的排序），在实际图表中几乎没有价值，建议优化为按照总数排序。
![image](https://github.com/dataease/dataease/assets/48945409/6b7322ed-0ece-47ac-98d9-65c7648dc086)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，antv图库有自身的排序机制，目前我们暂时还没有规划去修改图库的排序机制。Issue我们已经记录进需求中，就先进行关闭了。
