### ISSUE TITLE
[Feature]集成 Doris 2.0

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#5956]
**请描述您的需求或者改进建议.**
Doris 发布了 release2.0，DataEase 是否可以集成 doris2.0 的版本呢？
<img width="1371" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/e77e6c1b-c542-4844-b286-26f89967552a">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，由于不同版本之间存在兼容性问题，因此是不能直接集成doris 2.0版本的，当前暂时没有升级的计划。
