### ISSUE TITLE
[Bug] ECharts 的视图在全屏模式下，提示无法显示

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5960]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 116.0.5845.110（正式版本） (arm64)

**Bug 描述**
ECharts 的视图在全屏模式下，提示无法显示，试了试饼图、柱状图、折线图均无法显示。

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
