### ISSUE TITLE
[Bug] 仪表板偶发性打开空白，关闭仪表板提示未保存，点击保存后数据丢失。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#5962]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 116.0.5845.110（正式版本） (arm64)

**Bug 描述**
仪表板偶发性打开空白，关闭仪表板提示未保存，点击保存后数据丢失。

**Bug 重现步骤(有截图更好)**
1. 该问题本地未能复现，偶发性的碰到开源用户咨询该问题，建议可以排查下。
2. 根据客户描述是点编辑仪表板时，仪表板内容为空白，点击关闭仪表板提示未保存。点击报错后仪表板原有数据即丢失。

**Comment by BBchicken-9527** [comment]
由于不可控的原因，用户自行打包或者二次开发产生的问题请用户自行研究解决。这里先把issue关掉。如果后面建议用官方镜像和官方安装方式再出现问题可以再打开issue。
