### ISSUE TITLE
[Feature]建议过滤条件支持左包含和右包含

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#5964]
**请描述您的需求或者改进建议.**
如题所示，建议包含可以衍生为：1.包含（like '%xxx%'），2.左包含（like '%xxx'），3.右包含（like 'xxx%'）。
![image](https://github.com/dataease/dataease/assets/48945409/243569e7-6cfb-4ccb-889b-7c4629f0045e)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们在后续版本中会加入此功能支持。
