### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by hiep-wjl** [dataease/dataease#5970]
能不能支持共享url动态入参

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请问是指向公共链接url中传入参数吗？

**Comment by boommanpro** [comment]
@yayanpei-fit2cloud 支持url传参直接到SQL数据集的变量吗，superset是支持的

**Comment by BBchicken-9527** [comment]
感谢反馈，目前外部参数是支持sql数据集的参数化的，当然前提是你设置的过滤组件开启了参数化，可以参考我们的官方文档：https://dataease.io/docs/v2/user_manual/dashboard_using/?h=%E5%8F%82#32；
