### ISSUE TITLE
[Feature]视图过滤字段添加过滤条件，对于时间的过滤可以加一些函数么，比如想查昨日的数据等等

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5972]
**请描述您的需求或者改进建议.**
视图过滤字段添加过滤条件，对于时间的过滤可以加一些函数么，比如想查昨日的数据等等
![image](https://github.com/dataease/dataease/assets/89771514/c02c08a1-9d06-4890-82aa-b48baa5b9cbd)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，该需求已经在需求中，后期根据需求的优先级进行规划实现。
