### ISSUE TITLE
[Feature]仪表盘外部参数设置，添加联动视图选择视图时，仪表板中视图过多，添加不便

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#5973]
**请描述您的需求或者改进建议.**
仪表盘外部参数设置，添加联动视图选择视图时，仪表板中视图过多，添加不便
建议下拉选择视图时加个序号并按固定排序规则进行排序
或者做成个搜索下拉框也可以， 不然得手动下拉很久才找到想要设置视图

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论下优化方案。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，这里我们优化一下，做成搜索下拉框，可快捷选择视图。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
