### ISSUE TITLE
[Feature]支持导出单个视图带样式的图表

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#5975]
当前针对视图的导出只能导出视图数据集的数据，建议支持导出单个图表

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，点击图表的放大，是可以导出图表的。
<img width="1132" alt="image" src="https://github.com/dataease/dataease/assets/84168063/a475441d-0b39-42b0-8510-23fc30d55ebc">
