### ISSUE TITLE
[Feature] 矩阵模式下，视图大小的精确控制（类似于悬浮的）

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5976]
**请描述您的需求或者改进建议.**
悬浮可配置如下
![image](https://github.com/dataease/dataease/assets/45852479/ac67fe3c-887f-4487-aec5-f608c103257d)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，矩阵模式下，暂时没有规划支持精确控制。
