### ISSUE TITLE
[Feature] 希望类似于透视表、基础折线图的维度（子维度）可以支持自定义排序

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5977]
**请描述您的需求或者改进建议.**
透视表、基础折线图的子类别稳度不支持自定义排序
![image](https://github.com/dataease/dataease/assets/45852479/18e8339c-ecae-4969-97c0-d5b0548e2fa4)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先放入需求池中，当前暂时没有规划进行支持。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
