### ISSUE TITLE
[Feature] 文本卡、指标卡在名称不显示的情况下，没发单独对 值/文本 进行水平/垂直位置的设定

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#5978]
**请描述您的需求或者改进建议.**
文本卡、指标卡在名称不显示的情况下，没发单独对 值/文本 进行水平/垂直位置的设定
![image](https://github.com/dataease/dataease/assets/45852479/bbfdd323-a3f7-4ae4-90d2-4fd91ed30583)
![image](https://github.com/dataease/dataease/assets/45852479/b1dd2c26-54d8-4a3c-b66e-fb4bd4e300a1)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在最近的小版本中优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
