### ISSUE TITLE
[Question]哪个版本有分离渐变和自定义配色的

### ISSUE THREAD

**Issue by yixunwl** [dataease/dataease#5981]
哪个版本有分离渐变和自定义配色的 怎么1.18.9的没有
![image](https://github.com/dataease/dataease/assets/97295834/5c8ddaeb-efa9-4c79-8260-660f3dd13981)

![image](https://github.com/dataease/dataease/assets/97295834/46c09127-b09e-4bfb-bd5e-cc239c565b7f)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，V1.16.0 版本已经支持，这个配置项是【色彩地图】特有的属性，其他图表类型没有该配置项。
