### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by huyichao123456** [dataease/dataease#5982]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Google Chrome 116.0.5845.111（正式版本）

**Bug 描述**
dataEase嵌套到系统中登出之后会再次调用查询用户信息的接口

**Bug 重现步骤(有截图更好)**
1.登录
2.登出  之后会调用查询用户信息的接口
3.

**Comment by BBchicken-9527** [comment]
由于不可控的原因，用户自行打包或者二次开发产生的问题请用户自行研究解决。这里先把issue关掉。如果后面建议用官方镜像和官方安装方式再出现问题可以再打开issue。
