### ISSUE TITLE
希望可以支持配置加载页面时不加载数据，点了搜索再去加载

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#5983]
当页面数据量特别大的时候全量加载数据会卡顿，希望可以支持配置加载页面时不加载数据，点了搜索再去加载

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，请问具体是哪个页面？

**Comment by xiebei-l** [comment]
> 感谢反馈，请问具体是哪个页面？

仪表板页面，相当于对视图支持不加载数据

**Comment by xuwei-fit2cloud** [comment]
该需求并没有相关支持计划，但我们对数据加载次数做了一些优化，可以尝试一下。
