### ISSUE TITLE
记录数可以去重计数

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#5984]
希望针对记录数可以去重计数

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，记录数是数据集的总条数，去重计数需要基于一个字段的值进行去重，请参考下图所示选择一个字段进行去重计数。
<img width="357" alt="image" src="https://github.com/dataease/dataease/assets/84168063/55d20b40-7749-40ad-bfda-88529456ffe7">

**Comment by s-phenix** [comment]
就是要对记录数去重的

**Comment by s-phenix** [comment]
指标只能对一个字段去重，不好对多个字段组合的维度结果去重

**Comment by yayanpei-fit2cloud** [comment]
建议您创建sql数据集，根据您需要的几个维度去进行分组，然后用该数据集制作视图求记录数。视图这里暂没有计划支持对多个字段进行去重计数。
