### ISSUE TITLE
[Feature] 血缘关系的展示粒度能否支持到视图？

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#5986]
**血缘关系的展示粒度能否支持到视图，目前仅支持到了仪表板层面，详细如图所示：**
<img width="1163" alt="image" src="https://github.com/dataease/dataease/assets/45967454/a810cb5d-c91f-40f3-89a2-50a59e935eba">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
技术上是可以实现，但由于视图可能数量过多，展示效果上可能并不太好。
另外，在DataEase中，视图并没有归到资源层级上，所以短期内还不会做相关支持。
