### ISSUE TITLE
[Feature] 视图制作时，环比与同比的功能能否支持自定义时间进行对比？

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#5987]
**视图制作时，环比与同比的功能能否支持自定义时间进行对比（比如本季度与上季度，或者本次暑假与上次暑假）**
<img width="637" alt="image" src="https://github.com/dataease/dataease/assets/45967454/e76e90c7-633e-4ea7-8d88-77499dd898a6">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，当前阶段暂时没有规划进行支持，待收集更多用户的同类需求后再做规划。
