### ISSUE TITLE
[Question]如何支持二级路径代理

### ISSUE THREAD

**Issue by ihse1988** [dataease/dataease#5989]
公司只有1个ip，代理出来不能放到/路径，除了修改源码？能否增加配置支持二级目录代理呢？

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，系统当前是不支持配置的，如果需要，您可以参考前后端分离部署文档做调整。
https://dataease.io/docs/dev_manual/dev_deployment/tool/

**Comment by ihse1988** [comment]
ok,已经搞定了。
