### ISSUE TITLE
[Feature] 针对地图组件渲染铁路局相关路局信息

### ISSUE THREAD

**Issue by zjp1111** [dataease/dataease#5990]
**请描述您的需求或者改进建议.**
基于省份地区映射十八路局所属单位相关信息 (例如：黑龙江省映射哈尔滨铁路局集团有限公司)    其它省份如果没有对应的路局信息，例如(吉林省)    则鼠标移动至该省份地区不想弹出提示窗口。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，提示是统一控制的，暂时没有计划根据数据去控制提示弹框。
