### ISSUE TITLE
当导入很多模板时，系统模板页面卡顿，建议优化

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#5992]
当导入的模板多了之后，打开“系统管理”>“模板管理”>“系统模板”这个菜单会很慢，在系统模板的预览页就加载了大量的数据
![image](https://github.com/dataease/dataease/assets/57552153/4a178283-0718-4dde-a7a1-889ba0a40f69)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们试着做一下优化。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
