### ISSUE TITLE
[Question] 插件项目dataease-extension 前端部分无法启动

### ISSUE THREAD

**Issue by hopperhuang** [dataease/dataease#5993]
**请描述您的问题.**

根据Readme.md 执行命令后，无法将插件中的前端项目启动。

**Comment by xuwei-fit2cloud** [comment]
您可以参考一下我们的在线文档
https://dataease.io/docs/dev_manual/dev_deployment/compile/#21

**Comment by hopperhuang** [comment]
> 您可以参考一下我们的在线文档 https://dataease.io/docs/dev_manual/dev_deployment/compile/#21

同学你好，我不能启动的是你们的插件前端项目。但你这个文档是项目的前端项目。不能跟着做的。麻烦大佬找技术的同学看看可以吗？已经按照 https://dataease.io/docs/dev_manual/dev_view_plugin/ 这个文档去做了。真的不能启动。一启动就webpack报错。能找大佬看看吗，十分感谢。

**Comment by qiruijiudian** [comment]
我也遇到了类似的问题，报错日志如下：
![01bfc7890ebad59e125561700df5066](https://github.com/dataease/dataease/assets/97870361/e8543d14-eca2-49a7-93bb-d245d89e5a80)

当我尝试手动安装webpack-cli的安装包，并调整它们的版本，仍然不起作用。
