### ISSUE TITLE
[Question] 既然有了内置mongo接口，为啥还有扩展 mongo-bi

### ISSUE THREAD

**Issue by triumph** [dataease/dataease#5994]
**请描述您的问题.**
既然有了内置mongo接口，为啥还有扩展 mongo-bi， 他们有啥区别呢？

**Comment by xuwei-fit2cloud** [comment]
因为之前对接MongoDB的实现方式对MongoDB的支持并不好且容易出错，所以我们才在后续的版本中新增了MongoDB-BI的对接方式。
