### ISSUE TITLE
[Bug] 默认禁用 demo 账号

### ISSUE THREAD

**Issue by hbdxmz** [dataease/dataease#5995]
dataease部署后，除了admin账户，还带了一个demo账户，admin账户基本都改密码了，不过似乎很多用户部署后忘记删除这个demo账户了，导致很多人的dataease可以用这个demo账户登录，造成安全隐患了
```
https://github.com/dataease/dataease/blob/v1.18.9/backend/src/main/resources/db/migration/V3__init_data.sql
```
![image](https://github.com/dataease/dataease/assets/94107024/f1b37f48-5b6b-4db3-be16-8c807ff892ea)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们讨论一下；

**Comment by xuwei-fit2cloud** [comment]
我们后期会将demo用户设置为默认禁用状态。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
