### ISSUE TITLE
[Feature] 计算字段能否参与二次计算？

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#5996]
**数据集中的计算字段，能否引用之前的计算字段再次计算？**
<img width="1148" alt="image" src="https://github.com/dataease/dataease/assets/45967454/4b880b38-74a6-47be-8337-598d81b0af65">
<img width="1013" alt="image" src="https://github.com/dataease/dataease/assets/45967454/401c5dbd-878c-4797-a38e-213f21634f4a">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，近期暂时没有计划支持计算字段的二次计算。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
