### ISSUE TITLE
[Feature]导出功能加强

### ISSUE THREAD

**Issue by yhy729** [dataease/dataease#5997]
统随着深度应用，数据需要输出展示。数据报表数据超过1000条无法全部导出，也没有看到设置导出数量限制的设置。希望针对导出功能进行加强！

**Comment by xuwei-fit2cloud** [comment]
在仪表板中的视图主要是用来做展示用途，对于数据的导出，我们建议在数据集页面进行相关操作。

**Comment by lht-618** [comment]
> 在仪表板中的视图主要是用来做展示用途，对于数据的导出，我们建议在数据集页面进行相关操作。

一般导出功能都是具体实际使用用户使用，用户不会涉及到在报表开发平台操作。

**Comment by yhy729** [comment]
好的 谢谢解答

**Comment by lht-618** [comment]
您好，来信已收到。我会尽快处理的。

**Comment by lht-618** [comment]
您好，来信已收到。我会尽快处理的。
