### ISSUE TITLE
数据集，立即更新提示错误

### ISSUE THREAD

**Issue by plateauandsp** [dataease/dataease#6]
数据集，立即更新提示错误，不稳定复现，错误提示不明确。过一段时间后，会自动刷新一个成功任务
![image](https://user-images.githubusercontent.com/30932762/123370290-0170d980-d5b2-11eb-96e4-1af4cc1f67db.png)

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已修复
