### ISSUE TITLE
[Bug]颜色方案点了没变色，默认都是第一个颜色

### ISSUE THREAD

**Issue by songrui88** [dataease/dataease#60]
**Bug 描述**
颜色方案点了没变色，默认都是第一个颜色
**Bug 重现步骤(有截图更好)**
<img width="705" alt="2" src="https://user-images.githubusercontent.com/46080992/123533655-a2de6380-d749-11eb-8ed5-5fb90a205b80.png">

**Comment by XiaJunjie2020** [comment]
应该不是bug，配色方案是按照指标依次渲染，同一指标只有一个颜色，不是一个柱子一个颜色，否则图例不能区分
