### ISSUE TITLE
过滤组件支持设置跟随屏幕滚动

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#6002]
过滤组件支持设置跟随屏幕滚动，不然内容过长时还要拖上去选择

**Comment by winterbells07** [comment]
或者在屏幕右下角增加"返回顶部"的按钮

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by ziyujiahao** [comment]
https://github.com/dataease/dataease/commit/8c7f395805d893e33798d7686c5be0c721fec3af
