### ISSUE TITLE
[Bug]时间、下拉框过滤组件拖拽至仪表板最右侧，全屏预览后，点击展开的选择框、下拉框未能正常显示

### ISSUE THREAD

**Issue by sageonedream** [dataease/dataease#6004]
**DataEase 版本**
V1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Googel 104.0.5112.81

**Bug 描述**
时间、下拉框过滤组件全屏预览后，点击展开的选择框、下拉框位置显示未能与原组件位置对齐，显示不友好

**Bug 重现步骤(有截图更好)**
1.新建仪表板
2.添加日期范围和文本下拉过滤组件
3.将组件拖拽至仪表板最右侧，并全屏预览，点击对应的日期选择、文本下拉框，查看展开的下拉框显示情况。
![e17cf80a715f6c98c659ff59c3bd504](https://github.com/dataease/dataease/assets/92150453/98224db9-eb93-45c5-be66-5b96761cc9d5)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在 下个 版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
