### ISSUE TITLE
[Feature]日期筛选组件可设置查询的起始日期

### ISSUE THREAD

**Issue by winterbells07** [dataease/dataease#6005]
日期筛选组件在现有的功能上新增可以查询的起始日期，或自定义“最近3个月”“最近半年”“最近1年”，超过以上时间的自定义提示文案。

原因是现有的功能：有查询按钮的时候，默认加载全部数据，点查询后才查询需要日期或日期取件的数据
没有查询按钮的时候，虽然默认显示所设置日期或日期取件的数据，但是点清除时间按钮后缺默认加载全部数据。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈。

有查询按钮的时候，默认加载全部数据，点查询后才查询需要日期或日期取件的数据
>> 这个我们可以考虑增加一个选项，默认是否执行查询条件。

没有查询按钮的时候，虽然默认显示所设置日期或日期取件的数据，但是点清除时间按钮后缺默认加载全部数据
>> 目前控件确实有这个问题，临时的方法是直接点击日期进行选择，而不清除时间，我们再看看控件的清除按钮能否做相应处理。

自定义时间范围短期内还没有支持计划。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
