### ISSUE TITLE
[Feature]图片地址展示为图片

### ISSUE THREAD

**Issue by tang1798242063** [dataease/dataease#6006]
**请描述您的需求或者改进建议.**
图片地址展示为缩略图图片。然后点击之后为全屏图片。
![image](https://github.com/dataease/dataease/assets/109281669/5fd2c5ad-c2a0-4343-b7e6-7dc6b162fd20)
![image](https://github.com/dataease/dataease/assets/109281669/6d86ed9c-d5e9-42cd-9566-bc8f012a9c3f)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有规划支持表格中放置图片，我们先加入需求池中。

**Comment by xuwei-fit2cloud** [comment]
图库目前还不能做相关支持。
