### ISSUE TITLE
[Feature] 希望增加轴线颜色配置的功能，缩略轴大小的调整功能等

### ISSUE THREAD

**Issue by zyp971018** [dataease/dataease#6007]
①根据主题配色的不同，对于轴线的展示效果可能会有不同的需求，轴线颜色无法设置会导致图表与整体风格差异过大。
②缩略轴默认大小太大了，所占的空间比较大，希望能够让用户根据实际情况自行对缩略轴的大小进行调整。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先调研一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢反馈，您的建议我们已收到，近期暂时没有规划进行支持，待收集更多用户的需求后再做规划。
