### ISSUE TITLE
[Bug]字段类型转化错误

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6008]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**
版本 115.0.5790.170（正式版本） (arm64)

**Bug 描述**
在使用 mysql 直接连接数据库数据集的时候，数据库中数据时 int(11),字段类型修改为 时间后不正确

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/ac8cc7f2-7911-44ac-ba81-b025f68b76da)

2.
<img width="1408" alt="image" src="https://github.com/dataease/dataease/assets/109720729/322aceea-0c19-4f5a-b9e4-129243d6c112">

3.
<img width="1408" alt="image" src="https://github.com/dataease/dataease/assets/109720729/c790aeae-e65d-448f-b575-861e4f24b6db">
4。
<img width="1408" alt="image" src="https://github.com/dataease/dataease/assets/109720729/597831c8-9f11-45bb-b99d-e40f6af257d7">
5 
<img width="1388" alt="image" src="https://github.com/dataease/dataease/assets/109720729/59c44ed9-fccb-41bc-8a55-8ef6af41edf9">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前只有文本类型字段支持自定义转换方式，如果是数值会按照时间戳的方式进行转换；
