### ISSUE TITLE
[Feature]期望横轴支持文字过长时可以设置换行的功能

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#6009]
**请描述您的需求或者改进建议.**
在使用柱图等图形时，横轴的文字过长，导致被隐藏掉了，期望能够增加一个可以设置文字换行的功能。
如下图
![6513d31d9fcb5958b86405ad39924bd](https://github.com/dataease/dataease/assets/26103277/1c045c1f-e55d-4331-b09d-cdb4bf8a45c5)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先看看能不能支持，目前版本中，您可以试试旋转标签角度。
![图片](https://github.com/dataease/dataease/assets/1892127/891edad8-f5c7-4836-b97e-9203d0cd42e5)

**Comment by xuwei-fit2cloud** [comment]
我们暂时还是依赖标签角度的调整来处理，换行可以支持，但和多维度显示难以区别，暂时维持不动。
