### ISSUE TITLE
日期格式化错误[Bug]

### ISSUE THREAD

**Issue by iamlaobie** [dataease/dataease#6010]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
docker-compose simple

**浏览器版本**
chrome 116

**Bug 描述**
日期格式化是，误将分钟的格式参数写为英文月份的格式参数

**Bug 重现步骤(有截图更好)**
<img width="700" alt="image" src="https://github.com/dataease/dataease/assets/1291722/8c394eca-d182-4125-a431-ca92a73b349d">

**Comment by BBchicken-9527** [comment]
感谢反馈，方便说明一下你用的是什么数据源以及什么数据格式原本是什么样的吗？受累详细描述一下我这边好尝试复现一下你的问题；

**Comment by iamlaobie** [comment]
> 感谢反馈，方便说明一下你用的是什么数据源以及什么数据格式原本是什么样的吗？受累详细描述一下我这边好尝试复现一下你的问题；

客气了，数据源是clickhouse，字段的数据类型是DateTime

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。
![image](https://github.com/dataease/dataease/assets/84372766/e930d771-a85b-4cc7-846a-cc433bf62d63)

**Comment by BBchicken-9527** [comment]
由于这个issue在这个状态中停留时间过长我这边先关闭，如果你依然存在相同的问题可以将问题进行补充后打开，感谢你的支持与回复；
