### ISSUE TITLE
[Bug] 添加mongo-bi接口报错， mysql命令行测试mongo-bi 没问题

### ISSUE THREAD

**Issue by triumph** [dataease/dataease#6011]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
源码编译安装

**浏览器版本**
chrome

**Bug 描述**
mongodb-bi-v2.14.9 版本。mongodb 版本是  4.4.11
添加mongo-bi接口报错， mysql命令行测试mongo-bi 没问题

**Bug 重现步骤(有截图更好)**
1. 添加mongo-bi数据源
![image](https://github.com/dataease/dataease/assets/11950/6948f219-3f6d-4ac0-826e-faa77c41699a)
![image](https://github.com/dataease/dataease/assets/11950/0840361b-f55f-4471-9da7-ab488f14f9db)
![image](https://github.com/dataease/dataease/assets/11950/3af90f89-403e-41d2-902e-e6e2503316f1)

2.命令行测试连接mongo-bi 是正常的
![image](https://github.com/dataease/dataease/assets/11950/7c3898dc-5304-4f20-97c7-fa9f14ad03e3)

  用Navicat 可以连接，查询数据
![image](https://github.com/dataease/dataease/assets/11950/aadbc21b-3918-42a7-b4eb-1f1c78f948ab)

3.现在不知道是那里有问题，咋解决问题呢?

**Comment by BBchicken-9527** [comment]
由于不可控的原因，用户自行打包或者二次开发产生的问题请用户自行研究解决。这里先把issue关掉。如果后面建议用官方镜像和官方安装方式再出现问题可以再打开issue。嗯..可以看一下 mongobi 的证书有没有过期;
