### ISSUE TITLE
[Feature] 视图数据字段绑定规则优化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#6016]
**请描述您的需求或者改进建议.**
目前视图计算字段是与当前视图绑定的，新建视图后就无法复用，是否考虑绑定到数据集上？复用性会变的更好。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，视图的计算字段是属于当前视图的，如果其他视图需要复用，可参考如下方式：
1、在对应数据集上新建计算字段。
2、复制视图。
