### ISSUE TITLE
值轴 / 指标 只有 计数和去重计数 没有其他选项

### ISSUE THREAD

**Issue by jaedongjuly** [dataease/dataease#6017]
**请描述您的问题.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，字段的聚合方式与所选择的字段类型有关，如下：
1、当选择的字段类型为非数值时，只能对其进行计数、去重计数。
2、当选择的是数值型字段时，会有其他的聚合方式，比如求和、求平均，如下图所示：
<img width="232" alt="image" src="https://github.com/dataease/dataease/assets/84168063/1967ea28-d295-47aa-885f-cc9a3eb0bd11">
