### ISSUE TITLE
[Feature]DataEase对接钉钉实现免密登录优化建议

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#6018]
**请描述您的需求或者改进建议.**

现象：DataEase对接钉钉实现免密登录，首次通过钉钉登录DE会自动创建一个用户，但是只显示仪表板和系统管理，没有数据集的权限，用户无法直接操作DE，需要管理员手动指定角色。

建议：（1）首次通过钉钉登录DE创建的用户是否可以默认普通用户角色，这样管理员只针对个别人员设置权限；（2）如果平台有同名用户系统也会提示，免密登录会不成功，只能手动修改用户名或者手动和该用户进行绑定，可以考虑钉钉用户自定和DE同名用户自动绑定。
![微信截图_20230902104758](https://github.com/dataease/dataease/assets/43403764/98dcb14e-6b5c-4a43-804d-07002f2c7cf5)
![微信截图_20230902111352](https://github.com/dataease/dataease/assets/43403764/cbc6048a-9483-44e5-a8de-dc8c27640a88)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们后期加上默认角色设置功能。
