### ISSUE TITLE
[Bug] 轮播链接失效导致DE重新登录

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#6019]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 116.0.5845.141（正式版本） （64 位）

**Bug 描述**
设置轮播如果公共链接失效以后，tab页面会重新登录导致DE平台登录；

**Bug 重现步骤(有截图更好)**
![微信截图_20230902111111](https://github.com/dataease/dataease/assets/43403764/dfbe161f-da86-4dce-8014-3fe25a1a3668)
![微信截图_2023090212222](https://github.com/dataease/dataease/assets/43403764/688fcf2e-0bc7-44ae-864b-cb6c99b9a5d0)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前暂时不建议已这种方式实现其他仪表板的轮训，我们后续会增加新的方式来达到同等效果，但近期无法实现，期望你可以耐心等待我们的新功能😝！
