### ISSUE TITLE
[Question]文本下拉组件使用中遇到的问题

### ISSUE THREAD

**Issue by izombielandgit** [dataease/dataease#6021]
**请描述您的问题.**
版本号 | v1.18.9

问题：“文本下拉”组件设置为多选，在使用时，下拉菜单展开并选择了选项后，必须点击空白的地方才会收回菜单，如果点击其他组件或视图，不会收回。在组件和视图排列紧密，没有留空的情况，收回不是很方便。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #6888
