### ISSUE TITLE
[Feature] 删除时会有对应的资源名称显示

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6022]
**请描述您的需求或者改进建议.**
删除时会有对应的资源名称显示，仪表板、数据集、数据源
<img width="690" alt="image" src="https://github.com/dataease/dataease/assets/45852479/bbe90b33-a6e9-4140-8767-29f83a0af89f">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们已经加入需求池中。
