### ISSUE TITLE
[Question]表格表头能否分别设定样式？

### ISSUE THREAD

**Issue by tzengshinfu** [dataease/dataease#6026]
您好，表格表头能否分别设定样式(文字背景颜色)？
示意如下图
![image_20230906_100245](https://github.com/dataease/dataease/assets/2170033/1741d396-64be-4e5f-8bc1-721b557537a6)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，当前是不支持按照单元格设置表头的样式，表头样式是统一设置的。

**Comment by tzengshinfu** [comment]
您好，目前无急需，只是希望有机会能加入，
建议"明细表>编辑>样式>表头背景"是所有表头的全局设定，
或可以像阈值功能一样能另外针对个别表头做文字/背景颜色设定

另外，本来想有没有功能可以让用户注入JavaScript去设定表头样式，
但因为目前没此功能，
还有明细表组件这应该是用Canvas描制的，也没法这样做。

**Comment by xuwei-fit2cloud** [comment]
理论上图库是支持的，我们先记录一下。

**Comment by tzengshinfu** [comment]
好的，感谢。
