### ISSUE TITLE
[Bug]Excel 数据集

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6029]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
1 panel 安装

**浏览器版本**
116

**Bug 描述**

simple模式，上传excel预览有数据保存后没数据，local 有数据
**Bug 重现步骤(有截图更好)**
1.
<img width="1390" alt="image" src="https://github.com/dataease/dataease/assets/109720729/0a4e23c9-012f-4f70-9c28-c5a8c78dd779">

2.
3.

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。
