### ISSUE TITLE
[Bug]Echarts 堆叠图显示不出数据

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6030]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
pg 数据库直连使用 echarts 堆叠图展示不出数据，antv 可以

**Bug 重现步骤(有截图更好)**
1.
<img width="1404" alt="image" src="https://github.com/dataease/dataease/assets/109720729/b334c1b6-a2e5-40e8-a791-3557cc38cdd4">

2.
![image](https://github.com/dataease/dataease/assets/109720729/6ead4bd6-0c75-40b9-a28a-ffc84685448b)

3.

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。
