### ISSUE TITLE
[Feature] antv 堆叠图横轴标签遮挡

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6031]
**请描述您的需求或者改进建议.**
横轴标签遮挡住图
![image](https://github.com/dataease/dataease/assets/109720729/b83e8e23-8794-41eb-8d1e-cd6bd4cea989)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
