### ISSUE TITLE
[Feature]表格组件隔行变色

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6032]
**请描述您的需求或者改进建议.**
查看数据的时候，看着醒目一点
<img width="325" alt="image" src="https://github.com/dataease/dataease/assets/109720729/dcb9cf78-1964-4257-8169-c38fa8ffded9">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，您的建议已放入需求池中，后续会根据需求的优先级进行调研以及开发。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
