### ISSUE TITLE
[Feature]AntV 图库数值格式英文设置

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6051]
**请描述您的需求或者改进建议.**
能否支持直接设置为英文单位 K  这种
![image](https://github.com/dataease/dataease/assets/109720729/fc6f4352-d674-43bd-909c-ad0d7d1152e6)

**Comment by xuwei-fit2cloud** [comment]
咱们的单位包含 千、万、百万、亿，不能与英文一一对应，所以目前还做不了。
![图片](https://github.com/dataease/dataease/assets/1892127/e4990615-10c5-4ab6-b292-030054485c18)
