### ISSUE TITLE
[Feature]视图维度/指标-时间类型的字段日期显示格式设置希望支持“年月日时”格式

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#6056]
**请描述您的需求或者改进建议.**
<img width="295" alt="image" src="https://github.com/dataease/dataease/assets/89771514/dcacb7ea-ddea-4a4b-b19d-be84fecc65d0">

目前功能可以精确到秒，就单单没有设计“年月日时”格式，希望添加一下

**Comment by xuwei-fit2cloud** [comment]
已加入开发计划。

**Comment by xuwei-fit2cloud** [comment]
v1.18.10版本已处理，请更新版本。
