### ISSUE TITLE
[Feature] 分享的连接可以直接传入密码参数打开，不用手动输入密码

### ISSUE THREAD

**Issue by Horus-K** [dataease/dataease#6070]
**请描述您的需求或者改进建议.**
https://dataease.fit2cloud.com/link/WPPYUOXK?password=BzVZ
类似这样的方式直接能够打开不用输入密码，对安全方面有极大帮助

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，增加密码的手动输入，是考虑到数据安全。如果拼接到链接中，以免输入的方式自动打开链接，相当于没有对链接打开做密码保护，建议在生成公共链接的时候，不要开启密码保护，这样便可以直接打开链接。

**Comment by Horus-K** [comment]
因为我们目前是将大屏嵌入在后台中使用，需要能够直接在页面中打开，但是我们是希望大屏本身有密码保护的
