### ISSUE TITLE
[Feature]支持图表的纵轴的起始和结束刻度自适应或者自定义

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#608]
**请描述您的需求或者改进建议.**
支持图表的纵轴的起始和结束刻度自适应或者自定义，不要永远都是从0开始；

![image](https://user-images.githubusercontent.com/60059766/129176745-a630bf7c-095c-4b1a-a055-159236eecbd2.png)

**Comment by xuwei-fit2cloud** [comment]
这个需求已经记录在列表中，近期版本会实现。

**Comment by xuwei-fit2cloud** [comment]
v1.3.0版本已支持。
