### ISSUE TITLE
[Question]SQL变量只能在WHERE条件中使用？

### ISSUE THREAD

**Issue by tzengshinfu** [dataease/dataease#6081]
您好，
有个需求是要在数据库动态产生该年月份的所有日期，
在将所产生的1~31的数字格式化成日期时，因为要传入该年月份为变量，
却显示错误讯息"运行失败 SQL变量只能在WHERE条件中使用"
如下图所示
![image_20230908_113321](https://github.com/dataease/dataease/assets/2170033/ebd4441c-fd8c-4e2c-940e-15b5be753e97)

**Comment by tzengshinfu** [comment]
想用暂存表绕过限制，但发现不支持(右边是执行正常的SQL语法)
![image_20230908_150333](https://github.com/dataease/dataease/assets/2170033/18ef20d6-fbc9-40c5-9118-2aa63f3f9038)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复请见如下：
1、SQL变量目前仅支持在where条件中使用。
2、当前也不支持新建缓存表，再查询缓存表的方式，只能在sql编辑器中输入一个select查询。

**Comment by tzengshinfu** [comment]
您好，我看到了，文檔有提到要使用”标准”SQL查询语句，
![image_20230911_081055](https://github.com/dataease/dataease/assets/2170033/680d13a8-4de8-43fe-bba4-069d977ade76)

目前应该会朝向预建日期资料，或是改采API数据集方式处理，谢谢您。
