### ISSUE TITLE
[Bug] dataease cpu占用过高

### ISSUE THREAD

**Issue by lean-wang** [dataease/dataease#6085]
**DataEase 版本**
v1.18.9
**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome
**Bug 描述**
机器就安了这个dataease，十二核，64内存，只要打开仪表盘，dataease这个docker的cpu就疯狂占用，然后关了页面，cpu资源也不返还。接着又开始出现访问不了dataease以及共享的url，总数据为四张表，每张表为200w行数据，观察docker进程但是be和fe并无明显cpu占用，仪表盘为三张饼状图，和七张柱状图，柱状图仅展示1000行数据

**Bug 重现步骤(有截图更好)**
![2961694145038_ pic](https://github.com/dataease/dataease/assets/28487239/a0ee96ca-9ce4-42c8-9136-f34d9f347d0a)
![2971694145161_ pic](https://github.com/dataease/dataease/assets/28487239/39ad06b4-05ca-4c77-bd5a-d3b780322617)

**Comment by lean-wang** [comment]
柱状图只展示了1000行数据

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你的环境中是否存在大量的定时报告？如果存在那么报告的仪表板数据大概是一个什么量级的？

**Comment by lean-wang** [comment]
问题我自己尝试解决了，把dataease的docker的内存调大，cpu就没用占用了。
