### ISSUE TITLE
[Bug]字段过多时，使用文本过滤组件进行排序，字段显示不全！

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#6088]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
字段过多时，使用文本过滤组件进行排序，字段显示不全，可以加滚动条处理

**Bug 重现步骤(有截图更好)**
1.
<img width="1281" alt="image" src="https://github.com/dataease/dataease/assets/45967454/cdc3faf5-0128-432f-bcb6-9b1b78afb531">

2.
3.

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。
