### ISSUE TITLE
[Bug]使用时间区间控件生成sql ，WHERE  DATE_FORMAT(t_a_0.day_time, '%Y-%m-%d %H:%i:%S') BETWEEN 性能低

### ISSUE THREAD

**Issue by yanjun521520** [dataease/dataease#6091]
**DataEase 版本**
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
官方脚本安装，docker 运行

**Bug 描述**
使用时间区间筛选数据在数据量较大的情况下性能低，主要原因在于DATE_FORMAT，本是时间字段进行区间筛选，建议此处删除DATE_FORMAT 性能提升极大。目前由于这个原因导致无法正常展示。
WHERE
  (t_a_0.`country` IN ('us')
   AND t_a_0.`aff_id` IN ('221')
    AND DATE_FORMAT(t_a_0.`day_time`, '%Y-%m-%d %H:%i:%S') BETWEEN '2023-09-02 00:00:00' AND '2023-09-02 23:59:59')

**Comment by BBchicken-9527** [comment]
感谢反馈，我已经进行了记录讨论一下处理方案；

**Comment by xuwei-fit2cloud** [comment]
目前我们还没有较好的优化方案。
