### ISSUE TITLE
[Feature] 分享生成的链接，希望可以手动生成链接的字符串

### ISSUE THREAD

**Issue by anhuihu** [dataease/dataease#6098]
**请描述您的需求或者改进建议.**
[Feature] 分享生成的链接，希望可以手动生成链接的字符串
目前看板多了，分享出去不好区分具体是哪一个看板分享出去的，尤其一个项目下面的不同展示，希望可以自己填写字符串生成更有意义的分享链接

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议我们已收到，需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，公共链接是共享出去的，如果带上仪表板的信息或者自定义，可能存在安全隐患，因此暂时没有支持手动生成链接的规划。
