### ISSUE TITLE
[Feature] AntV 和 ECharts 组合图增加横轴、纵轴、图例设置

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#6099]
**请描述您的需求或者改进建议.**
该图为 ECharts 组合图样式编辑界面，AntV 相同。没有图例无法直观看出图形含义，没有纵轴设置 轴线较为混乱无法隐藏。
![image](https://github.com/dataease/dataease/assets/85436572/51593081-1dda-4655-aa7a-3b689d2e69ba)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。

**Comment by ulleo** [comment]
参考Echarts组合图的设置项，还需要添加图形大小的设置

**Comment by ulleo** [comment]
antv组合图使用antv的Mix图实现，但是mix图设置图例有bug，所以暂时无法实现
