### ISSUE TITLE
[Bug]创建仪表盘点击复用模板后返回自定义输入输入仪表盘名称确认会报错

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#61]
DataEase 版本
v1.0.0-rc2
浏览器版本
Chrome 91.0.4472.114（正式版本） (arm64)
**Bug 描述**
创建仪表盘点击复用模板后返回自定义输入输入仪表盘名称确认会报错
**Bug 重现步骤(有截图更好)**
1.点击新建仪表盘并调整选项为“复用模板”；
![image](https://user-images.githubusercontent.com/48945409/123534168-b4c20580-d74d-11eb-8764-1e67eafd1bc6.png)
2.重新返回“自定义”，输入名称后。点“确定”；
![image](https://user-images.githubusercontent.com/48945409/123534187-d28f6a80-d74d-11eb-9b70-8bdd1560cd28.png)
3.保存报错；
![image](https://user-images.githubusercontent.com/48945409/123534193-e1761d00-d74d-11eb-94bb-3290feb9c186.png)
4.取消并重新新建仪表盘，直接在自定义中输入名称确定可以新建成功

**Comment by ziyujiahao** [comment]
这个问题已经修复 当前已经发布

**Comment by xuwei-fit2cloud** [comment]
v1.0.1 版本已修复
