### ISSUE TITLE
[Bug] ECharts / AntV 组合图图形覆盖，显示异常

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#6101]
**DataEase 版本**
1.18.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/85436572/4d07ee9e-0e63-4eb6-97fa-312b562f36ef)
在【权重/指标】中添加两个维度，下方的指标会覆盖上方的指标。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by ulleo** [comment]
#6100

**Comment by BBchicken-9527** [comment]
已修复，请等待新版本发布。
