### ISSUE TITLE
[Bug] 添加数据库数据集时，如果第一次选择的数据库A下表较多，在还没加载完成的情况下切换表较少数据库B，这个时候B库下显示的数据表时A库下的表

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6102]
**DataEase 版本**
v1.18.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
添加数据库数据集时，如果第一次选择的数据库A下表较多，在还没加载完成的情况下切换表较少数据库B，这个时候B库下显示的数据表时A库下的表

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/45852479/c1efa0d1-979d-4e74-8c10-a19d83ff080a)
2.
![image](https://github.com/dataease/dataease/assets/45852479/66d05837-33be-40e5-a75e-89a7e3cc0b1e)

另：如果数据库下的表较多，数据源界面下的数据源表 tab 加载较慢（表有3k+）
![image](https://github.com/dataease/dataease/assets/45852479/7b3e27d5-5e75-4ec2-bdc0-5ae9172d7b93)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
