### ISSUE TITLE
[Bug]Echarts的组合图视图样式缺失

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#6103]
**DataEase 版本**
v1.18.10

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
Echarts的组合图视图样式缺失,被antv视图样式覆盖

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/70566485/731d870b-ef20-4a6c-8416-e73a36d8012b)
![image](https://github.com/dataease/dataease/assets/70566485/1a1dd9ac-9fa8-4e2c-a053-bafcb111778a)
![image](https://github.com/dataease/dataease/assets/70566485/ba5e43f9-085e-4913-ae45-7466cff19d4f)

**Comment by xuwei-fit2cloud** [comment]
已修复，请等待新版本发布。
