### ISSUE TITLE
[Question]视图插件项目dataease-extension 前端部分启动报错

### ISSUE THREAD

**Issue by qiruijiudian** [dataease/dataease#6107]
按照视图开发的文档进行操作，npm install 的命令能够成功，但是npm run dev失败，提示缺少webpack-cli的模组：
![image](https://github.com/dataease/dataease/assets/97870361/9430e798-f685-44b5-8f84-e1de234c3b93)

但是当我尝试安装npm install webpack-cli的各种版本，仍然失败报错。删除node_modules,重新拉取项目，使用yarn代替npm等方式皆为无用功。我想知道这个问题该如何解决。

**Comment by maninhill** [comment]
dataease-extension 代码已经被合并到主库：https://github.com/dataease/dataease/tree/dev/extensions

**Comment by qiruijiudian** [comment]
> dataease-extension 代码已经被合并到主库：https://github.com/dataease/dataease/tree/dev/extensions

用你们主库的代码也是这个报错
