### ISSUE TITLE
[Bug] echarts 地图，指标多个的情况下，全屏预览无法切换

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6110]
**DataEase 版本**
v1.18.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
echarts 地图，指标多个的情况下，全屏预览无法切换

**Bug 重现步骤(有截图更好)**
<img width="1379" alt="image" src="https://github.com/dataease/dataease/assets/45852479/da018ec4-87bc-46ad-a88f-e29c5d982f74">

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
