### ISSUE TITLE
[Bug] pg数据源添加时，获取 schema 报空指针

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6111]
**DataEase 版本**
v1.18.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
pg数据源添加时，获取 schema 报空指针

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/45852479/1e999ce3-8a07-4a24-942c-648810d9bd4c)

代码位置：
![image](https://github.com/dataease/dataease/assets/45852479/f9337235-d12a-444c-9043-0fad5b801092)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。
