### ISSUE TITLE
[Feature]请求在DataEase中集成DuckDB以提升数据分析性能和便利性

### ISSUE THREAD

**Issue by wozaitianwai** [dataease/dataease#6112]
现DuckDB在分析查询方面具有高效性和出色的性能。

### DuckDB的优点：
- 列式存储：能高效地读取大型数据集。
- SQL兼容：对已经使用基于SQL的工具的团队来说，过渡非常容易。
- 开源：提供了极大的灵活性和社区支持。

### 应用场景：
1. 实时分析
2. 数据转换任务
3. 涉及连接、聚合和窗口函数的复杂查询。

### 集成的好处：
- 提升查询性能
- 降低系统资源使用
- 增强分析能力

### 集成开发简便性：
DuckDB提供了多种编程语言的API支持，包括java等，这将大大简化集成过程。

### DuckDB Extensions示例：
1. **autocomplete**: 提供shell自动完成支持。
2. **excel**: 支持Excel文件操作。
3. **fts**: 支持全文搜索索引。
4. **httpfs**: 支持通过HTTP(S)读写文件，包括S3。
5. **icu**: 使用ICU库支持时区和排序规则。
6. **inet**: 支持IP相关的数据类型和函数。
7. **jemalloc**: 使用JEMalloc覆盖系统分配器。
8. **json**: 支持JSON操作。
9. **parquet**: 支持读写Parquet文件。
10. **postgres_scanner**: 支持从Postgres数据库读取。
11. **spatial**: 支持地理空间数据处理。
12. **sqlite_scanner**: 支持读取SQLite数据库文件。
13. **substrait**: 支持Substrait集成。
14. **tpcds**: 支持TPC-DS数据生成和查询。
15. **tpch**: 支持TPC-H数据生成和查询。

DuckDB的功能性和灵活性的扩展，使其更适用于多种数据分析场景。
以下是我再superset中的集成样例展示
![da4661ce006d3b97f3b30238d55ee04](https://github.com/dataease/dataease/assets/22335540/438c6c95-0114-4379-a026-a83c142542a2)

**Comment by xuwei-fit2cloud** [comment]
感谢您提供的信息，我们已将需求记录到需求池中，在后续版本里我们会做相关调研工作。
