### ISSUE TITLE
[Bug]筛选组件使用SQL动态传参且设置为多选时视图报错

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#6113]
**DataEase 版本**
v1.18.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
**表层问题**：筛选组件使用 SQL 动态传参且设置为多选时（单选时测试正常）视图报错，如下图所示：
![image](https://github.com/dataease/dataease/assets/48945409/f174ffa1-a53a-46a0-baa9-11734679228f)
![image](https://github.com/dataease/dataease/assets/48945409/59933221-3dde-4a73-9eee-38f30d0fa380)

**实际问题**：SQL 数据集写的时候本来就使用的 = xxx 参数，而不是 in xxx 参数，本身就不适配多选。所以筛选组件这里是否应在交互上做限制，或视图的报错信息上进行提示优化。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前平台无法判断输入sql是等于还是in，从而无法在给到组件消息这个sql参数化如果单选或者多选；
