### ISSUE TITLE
[Question]视图插件开发data.vue字段选择问题

### ISSUE THREAD

**Issue by wianleo** [dataease/dataease#6114]
问题：我有两个字段都需要是纬度类型，但是不添加指标字段的话获取不到数据，如何像内置的流向地图一样两个字段都是纬度类型。

**Comment by xuwei-fit2cloud** [comment]
具体问题我没太理解，但您可以参考一下流向地图的实现方式，或者基于流向地图的源码复制一份，在源码基础上做调整？
