### ISSUE TITLE
[Bug] pg 数据库设置时区后，同步到 doris 时间差8小时

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6115]
**DataEase 版本**
v1.18.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
pg 数据库设置时区后，同步到 doris 时间差8小时

**Bug 重现步骤(有截图更好)**
字段类型 timestamptz
pg时区 PRC

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在后续版本修复这个问题。

**Comment by f2m4** [comment]
不光是pg数据库.  链接所有的数据库都有这样的问题.
涉及到时间的sql语句, 转义后, 都会受到时区的影响. 导致执行异常.

**Comment by maninhill** [comment]
v1.18.16 发版时再核对下这个问题。
