### ISSUE TITLE
[Feature]更换数据集的按钮样式调整

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6116]
**请描述您的需求或者改进建议.**

更换数据集的按钮样式，被大多数用户认为是刷新按钮；
<img width="389" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/7f342f8f-38cd-4041-911e-91c0f2060dc5">

建议：在下图位置显示正在使用的数据集的名称，点击该数据集名称可以更换数据集。
<img width="353" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/1bb1b1f9-9bca-43cf-a916-372fd6d7a1ef">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
