### ISSUE TITLE
[Bug] 透视表的维度行和维度列都进行排序的状态下，维度行的排序失效

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6118]
**DataEase 版本**
v1.18.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
透视表的维度行和维度列都进行排序的状态下，维度行的排序失效

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/45852479/4be1b391-a248-48fe-8070-a8f27d957218)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前排序等操作都是交给数据库进行的，而且因为透视表的特殊性数据是交错的；
