### ISSUE TITLE
[Feature] 仪表板导出视图明细时连带着视图图片一起导出

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#6119]
**请描述您的需求或者改进建议.**
如下图所示，仪表板导出视图明细时可以把图片也一起导出。
![image](https://github.com/dataease/dataease/assets/30063018/bf9110bd-3afd-42bf-817e-2152bb238348)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议我们已收到，需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，我们暂时没有支持计划。
