### ISSUE TITLE
[Bug]无法添加Maxcompute数据源，报数据源无效

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#6124]
**DataEase 版本**
1.18.10版本

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
新建一个Maxconpute数据源后，无法添加数据源

**Bug 重现步骤(有截图更好)**
根据数据源参数填写，校验报错
<img width="1232" alt="image" src="https://github.com/dataease/dataease/assets/70566485/c8fb0b06-6f44-41e5-bb37-594f884bdfd9">

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在 下个 版本修复这个问题。
