### ISSUE TITLE
[Feature]视图过滤组件

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6126]
**请描述您的需求或者改进建议.**
同环比根据时间过滤组件周期进行计算

**Comment by xuwei-fit2cloud** [comment]
能详细描述一下具体需求吗？我理解您的意思可能是在日期范围组件的使用场景中？

**Comment by linyuiu** [comment]
例如就是如果我时间范围组件选择的时间范围，可以自动算与选择时间范围一样的同环比

**Comment by linyuiu** [comment]
例如选择 2023-05-10 到 2023-06-02
可以自动算 2023-04-18 到 2023-05-10 的环比

**Comment by xuwei-fit2cloud** [comment]
时间范围组件限定的是展示的数据范围，而这个需求所需处理的数据已经超出了时间范围，似乎不太合理。

**Comment by linyuiu** [comment]
好的
