### ISSUE TITLE
[Feature]视图过滤器空置处理

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6132]
**请描述您的需求或者改进建议.**
视图过滤器中，只有一个不为空，可否实现一个为空的判断，因为这样可以避免我去写计算字段，比较方表
<img width="656" alt="image" src="https://github.com/dataease/dataease/assets/109720729/26cb3785-82cf-44ca-98fa-7fb9dd89b9a7">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。
