### ISSUE TITLE
[Bug]仅调整 Tab 组件的标签顺序未触发到仪表板的保存按钮转为可点击状态

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#6133]
**DataEase 版本**
v1.18.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
仅调整 Tab 组件的标签顺序未触发到仪表板的保存按钮转为可点击状态

**Bug 重现步骤(有截图更好)**
1.保存按钮处于不可点击状态。
![image](https://github.com/dataease/dataease/assets/48945409/079c3759-488e-4e01-b96c-bab91681ac84)

2.调整 Tab 组件排序并保存新的排序。
![image](https://github.com/dataease/dataease/assets/48945409/b4f9509c-9f77-43a5-b0bb-8899f31fab8b)
![image](https://github.com/dataease/dataease/assets/48945409/f6533bda-a537-4617-b8df-6344efd5c9e0)

3.调整完成后，仪表板的保存按钮未显现，仍需要特意调整其他内容，才可继续保存仪表板。
![image](https://github.com/dataease/dataease/assets/48945409/ab9b3792-ce80-4a8f-9350-f5a973b149ad)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。
