### ISSUE TITLE
[Bug] 视图编辑页面，提示闪烁导致仪表板刷新

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6134]
**DataEase 版本**
v1.18.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
视图编辑页面，提示闪烁导致仪表板刷新

**Bug 重现步骤(有截图更好)**
https://github.com/dataease/dataease/assets/45852479/6968dbf6-56df-46b9-a9a7-bc299ad2ef64

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在 下个 版本修复这个问题。

**Comment by BugHunter7788** [comment]
请问这个问题解决了吗，是哪一个提交？
