### ISSUE TITLE
[Bug]Oracle 数据源在SQL数据集中查询数据非原始值

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#6138]
**DataEase 版本**
v1.18.10

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
Oracle 数据源在SQL数据集中查询数据非原始值

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/70566485/d677e5ce-f4f9-411b-9686-b8fff4e264ab)
![image](https://github.com/dataease/dataease/assets/70566485/a4e8f0c0-b907-493c-abe1-d84ee861bf1a)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在 下个版本修复这个问题。
