### ISSUE TITLE
[Feature] 时间轴日期格式增加

### ISSUE THREAD

**Issue by jychan000** [dataease/dataease#6142]
希望增加日期格式：月日时分
因为年太占空间，最好可以自助勾选
<img width="351" alt="image" src="https://github.com/dataease/dataease/assets/1819633/bb2d9956-0dcf-4e3f-9121-082f3b19ea31">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，我们暂时没有支持计划。
