### ISSUE TITLE
希望柱状图的网格线可以支持更多样式，比如虚线

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#6149]
希望柱状图、堆叠柱状图等可以支持这种网格线
![image](https://github.com/dataease/dataease/assets/57552153/d00bca0a-5222-4688-9400-e60a7838e0a9)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池中并调研一下图库。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
