### ISSUE TITLE
优化高分辨率机器的导出效果

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#6150]
导出仪表板图片时，用笔记本屏幕导出就正常，用外接的2k屏幕，和4k屏幕，分别导出，分辨率越大，下面的空白越多。希望可以优化一下
![image](https://github.com/dataease/dataease/assets/57552153/6d056496-ad5e-4567-887f-76d49df3592a)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。
