### ISSUE TITLE
希望可以增加一种类似日历或者日程表的时间组件

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#6151]
希望可以增加一种类似日历或者日程表的时间组件，每天的日期上可以有文字描述。
![image](https://github.com/dataease/dataease/assets/57552153/b549cb72-d76c-49f0-bc21-218c9be1712b)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
这个不太适合数据可视化工具，目前并没有支持的计划。
