### ISSUE TITLE
希望dataease仪表盘可以滚动显示

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#6152]
希望dataease仪表盘可以滚动显示，显示比较长的仪表盘自动滚动效果比较好。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，仪表板是用于更加直观的分析和展示数据，还是建议查阅者根据各自需要，自行向上或者向下滚动查阅仪表板，原因如下：
1、一个仪表板是要给多个用户查阅的，每个用户关注的图表和数据不一样，不好统一进行设置。
2、仪表板常规情况下，也不建议制作的特别长，2-3屏左右能满足使用，如果过长，也影响查看效果，建议根据业务进行拆分，制作多个仪表板。
