### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by wangsong8586** [dataease/dataease#6156]
**DataEase 版本**

1.18.9
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**

透视图总计占比显示不对。

**Bug 重现步骤(有截图更好)**
计算“新车/（新车+二手车）”的比值，但是在透视图的总计里面，是两个比值直接相加了，超过100%了，计算逻辑有问题。

![image](https://github.com/dataease/dataease/assets/25869159/c9bad5e5-75e1-42b8-838b-971bf12e1504)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题将会在后去版本修复，我们讨论一下解决方案；

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这是一个已知问题，目前依赖的图库确实还没支持这个功能，我们后期会考虑修改图库。
