### ISSUE TITLE
[Bug]明细表拖入选项卡中再点击明细表空白处字段会清空

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6157]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
 chrome\firefox

**Bug 描述**
明细表拖入选项卡中,再点击明细表的空白处字段会清空

**Bug 重现步骤(有截图更好)**
1. 准备明细表，拖入几个字段
2. 添加选项卡，将明细表拖入选项卡
![图片](https://github.com/dataease/dataease/assets/48307752/99e89a7a-33a7-4db7-883d-0c7a832476d2)

3. 随便点其他地方，然后再点击明细表的标题位置，明细表字段会清空
![图片](https://github.com/dataease/dataease/assets/48307752/6ba0e005-60a0-4dfd-a31b-5b2a9568fc0b)
![图片](https://github.com/dataease/dataease/assets/48307752/ed97b4fe-882a-4e17-a0bf-2a4fe26d4552)
![图片](https://github.com/dataease/dataease/assets/48307752/ce15408d-8265-46eb-b638-8af67bdaf7fc)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。
