### ISSUE TITLE
[Feature]支持API数据集动态参数

### ISSUE THREAD

**Issue by Y15822526881** [dataease/dataease#6158]
比如：我创建了一个仪表盘，分享链接给别人，但是在用的时候，在分享的链接后面多拼接了一个参数，比如http://127.0.0.1:6640/link/kOh0Z5?id=1 
然后这个仪表盘中用到了API数据集，数据集里面的get请求的参数，想要拿到链接里面的id的值

**Comment by xuwei-fit2cloud** [comment]
这个目前的设计还不好支持。我们的API数据集都需要API调用获取到数据后，将数据存放到本地数据库中，再通过数据库来实现数据处理的部分工作。而动态替换API数据集的URL，由于本地数据库里没数据，所以无法利用数据库提供的数据处理能力。
