### ISSUE TITLE
[Feature]时间过滤组件中的日期组件中，希望默认值-动态时间支持选择“上一交易日”选项

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#6161]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/89771514/6f9460ab-bd8c-4a0e-b95f-5919dc2bb9ef)
针对证券/金融行业来说，动态日期中的昨日意义不大，上一交易日的意义更大，因为他们关注的是交易日的数据。
协会每年年末都会发布下一年的交易日历，交易日历在交易所（上交所、深交所、银行间市场）网站上都可以查到。

**Comment by xuwei-fit2cloud** [comment]
这个需求比较具有行业针对性，类似上一交易日的选项并不适合与昨天、月初等标准选项放在一起。
我们也调研了一下交易日历相关的API，目前还没有找到比较合适的，需求暂时搁置。

**Comment by ZhaoQian1222** [comment]
可以考虑下，是否可以这样进行设计实现：
日期过滤组件自定义动态时间 扩展一下，支持设置跳过那些日期，这样既可以满足用户的需求，同时也不需要产品后续维护交易日信息了
![image](https://github.com/dataease/dataease/assets/89771514/1097a35d-c455-440b-9cfe-d53eb669daf1)


第二种实现方式，可以参考FineBI的日期过滤组件中的工作日设置的实现方式：
![image](https://github.com/dataease/dataease/assets/89771514/aac5c88a-1453-4d58-b083-b71f0675611a)
https://help.fanruan.com/finebi-en/index.php?doc-view-135.html
