### ISSUE TITLE
[Bug] V1.18.8修复了报告预览不全，发送失败问题，但是现在又出现了报告预览、报告发送的问题

### ISSUE THREAD

**Issue by Coder-Tang** [dataease/dataease#6162]
**DataEase 版本**
v1.18.8

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge
版本 117.0.2045.31 (正式版本) (64 位)

**Bug 描述**
官方更新说报告支持PDF，修复了报告显示不全的问题，但我在报告预览时，发现图表显示不全，报告发送失败，能帮我解答一下吗？

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/20924425/d9453d4c-0336-4dc1-afdb-75d606f62fe7)

2.
![image](https://github.com/dataease/dataease/assets/20924425/d60f822f-05e0-4888-8ab0-150e4b024bb2)

3.
![image](https://github.com/dataease/dataease/assets/20924425/1fe0db8b-ee1e-4d32-b37c-956804bf4666)

**Comment by BBchicken-9527** [comment]
感谢反馈，看异常是超时了，你可以尝试将系统设置中的超时时间增加等待时常；我需要和你确定一下大概你导出的仪表板总共多少个视图，每个视图的数据量是多少呢？

**Comment by Coder-Tang** [comment]
系统设置中的超时时间增加等待时常，这个没找到入口

![image](https://github.com/dataease/dataease/assets/20924425/12733445-f05f-417f-ba15-b92ffcfc4465)

仪表板有17个图表，数据量不大，数据集数据没有超过100条

![image](https://github.com/dataease/dataease/assets/20924425/1b73da19-93e4-4676-932d-e7c14bd614f4)

**Comment by Coder-Tang** [comment]
> 感谢反馈，看异常是超时了，你可以尝试将系统设置中的超时时间增加等待时常；我需要和你确定一下大概你导出的仪表板总共多少个视图，每个视图的数据量是多少呢？

超时时间已经改的很长了
![image](https://github.com/dataease/dataease/assets/20924425/848939e2-c104-4c40-a851-f4186c437bad)

**Comment by Coder-Tang** [comment]
> 感谢反馈，看异常是超时了，你可以尝试将系统设置中的超时时间增加等待时常；我需要和你确定一下大概你导出的仪表板总共多少个视图，每个视图的数据量是多少呢？

视图、数据量我在下面评论了

**Comment by BBchicken-9527** [comment]
感谢反馈，目前我在本地环境中没有发现你说的这个问题，我做了十八个视图数据量超过了你说的不到一百条，嗯....你的数据源使用的是什么呢？我这边用的doris；

**Comment by Coder-Tang** [comment]
> 感谢反馈，目前我在本地环境中没有发现你说的这个问题，我做了十八个视图数据量超过了你说的不到一百条，嗯....你的数据源使用的是什么呢？

我这边用的doris；

用的也是doris，就是挺奇怪的，有时候发送报告成功，有时会发送失败，而且报告里的图表时不时会有缺漏。

难道真的是网络问题吗

**Comment by BBchicken-9527** [comment]
嗯... 我这边反复发送了两遍没出现你说的这种问题😂，你用本地的doris 呢？也会出现这种情况吗要是没有出现大概率还真有可能是网络问题

**Comment by Coder-Tang** [comment]
> 嗯... 我这边反复发送了两遍没出现你说的这种问题😂，你用本地的doris 呢？也会出现这种情况吗要是没有出现大概率还真有可能是网络问题

用的是一个集群下在其他机器上的doris

**Comment by xuwei-fit2cloud** [comment]
很抱歉，我们这边还是无法复现您提的问题，暂时先关闭一下。
