### ISSUE TITLE
[Bug]使用企业微信登录 DataEase 后，导出视图表格会报错

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6163]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
企业微信端

**Bug 描述**
使用企业微信免登 DE 后，导出视图表格会报错；
![图片](https://github.com/dataease/dataease/assets/48307752/4c0164b3-a36f-419e-baff-98a0a456d952)

（不一定是免登，只要用企业微信访问，在导出视图时就会报错）
**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。

**Comment by mfanoffice** [comment]
升级企业微信至最新版本可解决
