### ISSUE TITLE
[Feature]仪表板导出时跳转设置的相关链接一起导出

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#6164]
**请描述您的需求或者改进建议.**
仪表板导出时跳转设置的相关链接一起导出，目前只能导出当前导出的仪表板，跳转设置消失，只能重新配置。
<img width="900" alt="image" src="https://github.com/dataease/dataease/assets/133861755/72067214-c49e-4aaf-9923-fc9022526411">

**Comment by xuwei-fit2cloud** [comment]
我们在导出仪表板的时候，导出的是当前仪表板，而跳转的对象是另一个仪表板，我们并不能保证它在导入的环境中存在，也不能保证ID是不变的，所以这个需求目前还不能支持。
