### ISSUE TITLE
[Bug]维度是小数时，会多出很多 0

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6165]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
维度是小数时，会多出很多 0
<img width="665" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/50f2bc07-9372-426f-a830-032cd7699ef8">

目前可以将小数格式的字段，转换为文本，可以避免多个 0 出现。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前设计数值小数是会对小数位进行一个8位的截取的如果图表显示中可以通过格式化去解决显示的问题的；
