### ISSUE TITLE
[Bug] sql 数据集参数被注释后，依旧能被识别到且 sql 执行报错

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6166]
**DataEase 版本**
v1.18.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
sql 数据集参数被注释后，依旧能被识别到且 sql 执行报错

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/45852479/04f2ed50-156e-47f1-99ba-5dda49272228)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
目前在SQL语句里还不能支持注释。
