### ISSUE TITLE
[Feature]数据集预览界面可以拖动字段移动前后位置排序

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#6167]
**请描述您的需求或者改进建议.**
数据集预览界面可以拖动字段移动前后位置排序
<img width="277" alt="image" src="https://github.com/dataease/dataease/assets/101089844/ca78113d-5710-47ce-be29-8903b2c6b22d">

**Comment by xuwei-fit2cloud** [comment]
我们先讨论一下支持的方式。

**Comment by xuwei-fit2cloud** [comment]
我们当前使用的表格组件不能直接支持拖拽来重新排序，需要设置一个单独的排序功能，短期内还没有相关的开发计划。
