### ISSUE TITLE
[Bug]定时同步数据集修改 SQL 在数据集预览界面报错

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#6169]
**DataEase 版本**
1.18.10

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
修改 SQL 的定时同步数据集在编辑界面可以正常预览，数据集界面显示会报错
![image](https://github.com/dataease/dataease/assets/85436572/6b2f9f3f-b2d5-43bf-90ee-0343f7094db0)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，可以点击字段管理-同步字段来解决这个异常，异常主要产生原因是因为当源数据表字段发生变化时和doris中的表字段没有对齐导致；
