### ISSUE TITLE
[Feature]希望可以点击柱状图或者折线图某个点位有弹框弹出

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#6170]
**请描述您的需求或者改进建议.**
希望可以在点击柱状图或者折线图某个点位时有弹框弹出，比如可以显示详细分页列表
<img width="1206" alt="image" src="https://github.com/dataease/dataease/assets/133861755/0003563e-6dac-4f71-8507-cab3c0d94403">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，当前暂时没有计划，如果需要查看某个数据点的详细数据，建议用内部图表联动或者跳转目标仪表板的方式。
