### ISSUE TITLE
[Feature] 视图支持横纵轴都是数字的散点图

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6171]
**请描述您的需求或者改进建议.**
视图支持横纵轴都是数字的散点图，目前 de 中的其实是气泡图
<img width="716" alt="image" src="https://github.com/dataease/dataease/assets/45852479/022c375c-d009-4422-af6a-99ad712c6afb">
<img width="662" alt="image" src="https://github.com/dataease/dataease/assets/45852479/3ecf8803-bb2f-4491-a03f-457305d911ff">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，您的建议很不错，我们先进行调研一下。
