### ISSUE TITLE
[Bug]Antv 堆叠柱状图颜色自动还原

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6172]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

正在检查更新
版本 116.0.5845.187（正式版本） (arm64)

**Bug 描述**
使用antv 堆叠状图时，当鼠标放到图上视图就会刷新，刷新几次后会将设置好的配色方案重制为初始化方案，手动设置的配色丢失

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。
