### ISSUE TITLE
[Feature]X-pack功能能否增加一个页面可以看到那些该用户有哪些仪表板数据集的权限，或者反之

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6175]
**请描述您的需求或者改进建议.**
目前需要一个一个仪表板去看，不是很方便

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，在权限管理页面，可以切换至「按用户配置权限」tab项，在该页面可以查看每个用户所拥有的资源权限。
<img width="1473" alt="image" src="https://github.com/dataease/dataease/assets/84168063/abfe5bd5-e1c4-49fa-a61f-8770964df479">
