### ISSUE TITLE
[Bug]数据集使用定时同步，数据量超过50000时，有可能会丢失数据

### ISSUE THREAD

**Issue by seanwwh** [dataease/dataease#6177]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
所有

**Bug 描述**
数据集使用定时同步，数据量超过50000时，有可能会丢失数据

**Bug 重现步骤(有截图更好)**
1.现象：
数据源是PostgreSQL 12，SQL数据集，如果SQL无排序条件，同步后发现比原始数据集少了一些，如果加上主键ID排序条件，数据同步正常
2.分析原因：
Dataease同步大数据量时会使用分页查询，将原始SQL作为子查询，例如：SELECT 字段1, 字段2,... FROM(原始SQL) AS DE_TEMP   LIMIT 50000 OFFSET 50000 ，但如果原始SQL不带排序条件，每次查询的结果有可能是不稳定的，导致丢失部分数据。
3.建议：
不要使用子查询的分页方式，改用流式查询的方式来分批同步，参考方法：https://segmentfault.com/a/1190000022167975

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，我这边使用的测试数据是10w的数据，感谢理解和支持。

**Comment by seanwwh** [comment]
抱歉，我在生产数据中发现的问题，不方便上传复现文件，请参考下面的文章创建测试数据复现，谢谢
https://blog.csdn.net/u012736152/article/details/88865760

**Comment by BBchicken-9527** [comment]
感谢反馈，我们确认一下；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
