### ISSUE TITLE
[Bug]clickhouse 数据源 时间格式化 小时 变成英文月份

### ISSUE THREAD

**Issue by chase-cai-huan** [dataease/dataease#6180]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.
![微信图片_20230920144313](https://github.com/dataease/dataease/assets/145539087/697f416f-d99a-4961-96f3-535bd744af92)
目前使用clickhouse 数据源 时间格式化 小时 变成英文月份
2.
3.

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。

**Comment by BBchicken-9527** [comment]
感谢你的反馈，由于状态停留时间过长没有收到反馈，我暂时先将问题关闭，若依然存在问题可在公共群中联系我们的同学或再次将问题打开；
