### ISSUE TITLE
动态sql参数配置，in 条件无法保存

### ISSUE THREAD

**Issue by VanLiuZhi** [dataease/dataease#6181]
**DataEase 版本**
v1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**
edge or chrome 最新

**Bug 描述**

sql 数据集，用动态参数，= 条件可以，in 条件不行

![image](https://github.com/dataease/dataease/assets/22883555/0675487f-e4d7-457f-95de-817bce147a9a)

我看了代码，应该是这里的问题

![image](https://github.com/dataease/dataease/assets/22883555/189cff59-b0b4-4bfe-ac04-a9336b672661)

没法转换，执行不了 stringBuilder.append(SubstitutedSql);

导致后续判断异常，我看前端提示就是说 in ‘$params’  这种写法，但是这么写，sql是不对的
如果改成  in (‘$params’ ) sql 对了，binaryExpression 也不是null，就可以过判断，保存成功了

但是在后面看板处理动态参数的时候，transFilter

return "('" + String.join("','", chartExtFilterRequest.getValue()) + "')";

就会返回  (('a')) 类似这种，我临时改了代码，return "" + String.join("','", chartExtFilterRequest.getValue()) + "";  然后看最终执行sql，
变成  status in ('a')，就不会报错了，整个流程可以通。

我也对比了最新版代码，这部分差不多是一样的，请问是不是有问题，要么就是动态sql校验问题，要么就是看板参数处理问题，感觉2个地方要修改一处

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，可参考提示，用in的话，sql语句中参数不要加引号。
<img width="893" alt="image" src="https://github.com/dataease/dataease/assets/84168063/4235c7d5-5044-44c7-9d3f-51100c528e4e">

**Comment by VanLiuZhi** [comment]
原来如此，看来是我的问题，感谢
