### ISSUE TITLE
[Feature]选项卡组件方框大小无法随字体大小调节

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6182]
**请描述您的需求或者改进建议.**
选项卡组件，方框大小无法随字体大小调节，字体多大时和方框边缘会重合
![图片](https://github.com/dataease/dataease/assets/48307752/db6df461-abfc-4bc0-a33c-1ccb16b61796)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
