### ISSUE TITLE
[Bug]自定义数据源插件上传后重启就失效了

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6183]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
自定义数据源插件上传后，正常使用，重启DE服务，在数据源中就找不到上传的数据源了；
已创建的数据源就变成了空标题
<img width="1232" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/b19d2cd5-c34d-444d-a294-60d7cd58deff">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在后续版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
