### ISSUE TITLE
[Bug]透视表列总计字段对于比率计算不对

### ISSUE THREAD

**Issue by wangsong8586** [dataease/dataease#6184]
**DataEase 版本**

1.18.11
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

crhome
**Bug 描述**
新车单量占比=新车单量/(新车目标单量+二手车目标单量)，是一个比例，在列总计时，不应该是简单的把8月和9月两个比例相加

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/25869159/895a5c61-85ee-4103-96de-de7a4ddc6244)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这是一个已知问题，目前依赖的图库确实还没支持这个功能，我们后期会考虑修改图库。

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #6156
