### ISSUE TITLE
[Feature]透视表支持列占比计算

### ISSUE THREAD

**Issue by wangsong8586** [dataease/dataease#6185]
**请描述您的需求或者改进建议.**
透视表，计算每一列占列总计的比例，如下图 计算出 382/764的比例
![image](https://github.com/dataease/dataease/assets/25869159/b51c50b9-bf48-4190-bd1c-51638a3b7bab)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前依赖的图库确实还没支持这个功能，我们后期会考虑修改图库。
