### ISSUE TITLE
[Bug]下拉树配合 Tab 组件过滤不生效

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6186]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包，最行新版

**浏览器版本**
谷歌

**Bug 描述**
在使用下拉树组件时，在过滤同一个tab 组件的不同页面时，第一次进入仪表板不会生效，需要把下拉树内容清空，重新过滤，则两个页面都会被筛选，数据集都是同一个，下拉树组件按组件过滤。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/9168fe3c-3b94-4da1-ae57-0b14a2ffb0d8)

2.
![image](https://github.com/dataease/dataease/assets/109720729/c823f904-3d8b-4f45-b9e6-37d0b2f240d3)

3.
![image](https://github.com/dataease/dataease/assets/109720729/0571974e-222e-43f3-bdfc-5a57024f24f9)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.12版本已处理，请更新版本。
