### ISSUE TITLE
[Bug]Antv 组合图设置数值格式不生效

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6187]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

谷歌
**Bug 描述**
在使用 Antv 组合图时，指标设置数值格式不生效

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/84547fba-9fcd-4eff-a91e-9cb419544083)

2.
3.

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。

**Comment by BBchicken-9527** [comment]
感谢你的反馈，由于状态停留时间过长没有收到反馈，我暂时先将问题关闭，若依然存在问题可在公共群中联系我们的同学或再次将问题打开；
