### ISSUE TITLE
[Bug] Antv和ECharts组合图互相覆盖

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6188]
**DataEase 版本**
1.18。11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
在新建 Antv 组合图时，数据拦不对，而且切换为 Echarts 时，会切换不成功，反之亦然。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/5ff94e8c-7cd9-4a33-bb7a-72421cbdc0d2)

2.
3.

**Comment by linyuiu** [comment]
![image](https://github.com/dataease/dataease/assets/109720729/13146834-726c-4fd4-af90-f8653d601cc3)
antv 数据栏目前是这样

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。
