### ISSUE TITLE
[Bug]Antv 组合图曲线设置不生效

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6189]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
新建组合图的线是是平滑曲线的，切成折线图、再切回组合图，就变成不平滑的了

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/b957c78f-cbc9-4b56-be81-32f3291a19f3)

2.
![image](https://github.com/dataease/dataease/assets/109720729/5429bb15-9982-4b54-88d4-7cb9fde181d9)

3.
![image](https://github.com/dataease/dataease/assets/109720729/39d44791-7daa-4d49-ab19-376b41404e43)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by ulleo** [comment]
这个问题是由于 #6188 导致的，实际上平滑曲线是Echart的组合图提供的，由于bug，切换的时候会错乱。
antv的组合图支持设置平滑曲线的需求加到这里 #6099

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
