### ISSUE TITLE
[Bug]对称柱状图副轴值同样的指标求占比，导出Excel是两列一样的（且Y轴被遮挡）

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#6191]
**DataEase 版本**
版本1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
对称柱状图副轴值同样的指标选择占比，视图的数据不同 但是导出Excel是两列一样的。（且Y轴被遮挡）
<img width="342" alt="image" src="https://github.com/dataease/dataease/assets/133861755/7055493f-9444-4b65-b79a-eebc35d5dca2">
<img width="989" alt="image" src="https://github.com/dataease/dataease/assets/133861755/d27bdc1e-55bc-4509-809c-1861509f2ea2">
<img width="1385" alt="image" src="https://github.com/dataease/dataease/assets/133861755/6b841fb7-2f7c-4b54-967c-fd2935821569">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。
