### ISSUE TITLE
[Bug]Echarts的地图组件，没有数据情况下修改了属性名（不一定是对应的中文），视图的对应位置会有颜色改变

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#6192]
DataEase 版本
版本1.18.11

运行方式(安装包运行 or 源码运行 ?)
安装包运行

浏览器版本
chrome

**Bug 描述**
Echarts的地图组件，没有数据情况下修改了属性名（不一定是对应的中文），视图的对应位置会有颜色改变。
<img width="1171" alt="image" src="https://github.com/dataease/dataease/assets/133861755/a4a76b61-4366-4650-a945-e3cdc59e7db8">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
