### ISSUE TITLE
[Feature] 可以支持 null 字段的联动吗？

### ISSUE THREAD

**Issue by mayjiang0203** [dataease/dataease#6193]
**请描述您的需求或者改进建议.**
使用版本 v1.18.8

饼图和表格视图设置了联动，点击饼图 null 字段会报如下的错误
![image](https://github.com/dataease/dataease/assets/9443637/de906725-ab8d-4933-9eb9-a58228d5b2fc)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们已加入需求池，如有其他用户反馈，我们再进行支持。
