### ISSUE TITLE
[Bug]echarts动态排序图显示NAN

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#6194]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
 117.0.5938.88（正式版本） （64 位）

**Bug 描述**
使用的是官方示例GDP的数据集，使用的是echarts动态排序视图，如下图。自动切换维度的时候，有的值显示的是NAN

**Bug 重现步骤(有截图更好)**
1.
![117e369a766d338c472580272ce19ed](https://github.com/dataease/dataease/assets/26103277/b91d5aba-03bc-47cc-89ca-d9b8115b6abe)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前此处还没有更好的解决办法，经过我们测试原生库本身就存在这种问题，我们也在进一步的讨论如果优化此处，这个问题暂时先关闭掉如果有真正可实行的方案我们会第一时间优化此处，实在不好意思给你带来了不好的体验；
