### ISSUE TITLE
[Bug]在线安装脚本，访问地址回显信息不正确

### ISSUE THREAD

**Issue by chenxin2001** [dataease/dataease#62]
**DataEase 版本**
v1.0.0-rc2

**浏览器版本**
FireFox 89.0.2 (64 位)

**Bug 描述**
在线安装，安装完成后，访问地址回显信息不正确，未显示正确的IP地址

**Bug 重现步骤(有截图更好)**
1. 执行“curl -sSL https://github.com/dataease/dataease/releases/latest/download/quick_start.sh | sh”
2. 安装完成，访问地址回显信息不正确，未显示正确的IP地址
![图片](https://user-images.githubusercontent.com/34565342/123535822-16d43800-d759-11eb-8247-69128ef31c4e.png)

**Comment by xuwei-fit2cloud** [comment]
暂时不予处理
