### ISSUE TITLE
动态排序图部分数据会显示NaN

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#6200]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
动态排序图部分数据会显示NaN

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/57552153/121ec59d-8e44-4d52-b651-0a741a007e6e)

2.
![image](https://github.com/dataease/dataease/assets/57552153/76c32935-accc-461a-b77d-f21fcb2252c1)

**Comment by BBchicken-9527** [comment]
感谢反馈，由于原生图库导致，我们没有更好的操作空间，后续如果有好的解决方案我们会第一时间进行处理；
