### ISSUE TITLE
[Feature]仪表盘刻度标签挤在一起了

### ISSUE THREAD

**Issue by yixunwl** [dataease/dataease#6202]
**请描述您的需求或者改进建议.**
仪表盘刻度标签挤在一起了，能不能自己调整大小，和显示类型可为百分比。还有颜色只能调指针指到的颜色，能不能调指针未指到那块的颜色
![image](https://github.com/dataease/dataease/assets/97295834/635aab1e-2317-4475-aaef-11e24f645e18)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议您使用antv的仪表盘。
