### ISSUE TITLE
[Bug] 仪表板页面复制仪表板后出现错误， 仪表板全部不见

### ISSUE THREAD

**Issue by DogeVenci** [dataease/dataease#6204]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
Edge 117.0.2045.36

**Bug 描述**
仪表板页面复制仪表板后出现错误， 仪表板区域显示空白，重启后依旧，报错信息：
```Duplicate key d5f324b3-5791-11ee-bad3-8be39b6fa457 (attempted merging values PanelGroupDTO(creatorName=null, updateName=null, label=月报, leaf=null, privileges=export,grant,manage,view, defaultPanelId=4aa8676c-46e4-4caf-bb03-c0b08ec2c10f, defaultPanelName=月报_copy, isDefault=true, sourcePanelName=null, children=null, viewsInfo=null, parents=null, requestId=null, responseSource=null, watermarkInfo=null) and PanelGroupDTO(creatorName=null, updateName=null, label=月报, leaf=null, privileges=export,grant,manage,view, defaultPanelId=7cb0113f-c2c1-4a80-9bec-a00658d2d2e7, defaultPanelName=月报, isDefault=true, sourcePanelName=null, children=null, viewsInfo=null, parents=null, requestId=null, responseSource=null, watermarkInfo=null))```

**Bug 重现步骤(有截图更好)**
![a1e7c86527b5659ef359fe7c1e4cf3a](https://github.com/dataease/dataease/assets/1185501/c37d3385-5f8f-428d-ba7a-11d6678512e9)
![8ec70bbc54cc7b8b32ff2e503afcced](https://github.com/dataease/dataease/assets/1185501/795a7da8-0fe6-452d-8e18-34ed83a2f277)

定位到代码https://github.com/dataease/dataease/blob/7565161c2d7b534fd482816d9902020a13852c99/core/backend/src/main/java/io/dataease/commons/utils/TreeUtils.java#L31C50-L31C50

**急求解决方案，保存的大量仪表板不见了**

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。请问是做了二开吗？目前我们本地环境没有发现你说的这种情况；

**Comment by DogeVenci** [comment]
[MobaXterm_172.19.1.19_20230922_194252.txt](https://github.com/dataease/dataease/files/12720858/MobaXterm_172.19.1.19_20230922_194252.txt)
@BBchicken-9527

**Comment by ziyujiahao** [comment]
日志上看应该是出现了重复的ID导致资源树的构建失败，可以做一个临时解决方案：1.备份数据库dataease（切记，如果已经指定其他数据库要备份指定的数据库） 2.找到panel_group 这个表 查看id = d5f324b3-5791-11ee-bad3-8be39b6fa457 这个数据，日志结果显示关联查询出来有重复，在表里面应该不会重复，如果这条数据没用可以备份表后删除一下这条数据试一下；以上都要做好数据备份工作防止出现异常方便回退

**Comment by DogeVenci** [comment]
@ziyujiahao 我早些时候就删掉了 删除就正常了 主要要看看为什么会出现id重复情况  防止以后再出现问题

**Comment by BBchicken-9527** [comment]
感谢反馈，目前我们本地环境是没有发现id重复的问题，所以我们也不是很清楚具体引发的原因，如果依然出现这种问题受累看记录一下前后的操作并告诉我们，我们会第一时间进行处理，如果没有其他问题我先关闭这个issue；
