### ISSUE TITLE
[Feature]【视图】明细表支持冻结列

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#6205]
**请描述您的需求或者改进建议.**
明细表支持冻结列

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们在后续版本中增加支持。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。

**Comment by keith2008** [comment]
具体怎么用的，相关文档没有说明啊。说v.1.18.14已经修复了。我在v.18.15版本没有看到这个功能。

**Comment by AndroidBaby1** [comment]
我看到这一块确实是有了：https://dataease.io/docs/v1/user_manual/view_module/view_style_design/?h=%E5%86%BB%E7%BB%93#14

**Comment by keith2008** [comment]
> Contributor

谢谢，我看到了。但是好像不支持透视图，我的需求是：透视图有总计行，要把总计行冻结，请问怎么处理。
