### ISSUE TITLE
[Bug]全屏预览模式下视图标题的备注无法显示

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#6207]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/89771514/08cd4faa-6f0c-45f7-8e6c-2401e7b6cbeb)
![image](https://github.com/dataease/dataease/assets/89771514/acb6e27b-22c4-4847-a3be-cc21f0da0a07)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们修复一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
