### ISSUE TITLE
[Bug]【视图】明细表从显示十条设置成显示全部之后浏览器会崩溃

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#6209]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
明细表从显示十条设置成显示全部之后浏览器会崩溃（50 个维度，2000 条数据）
![image](https://github.com/dataease/dataease/assets/24768910/23274a02-f01a-49f1-90de-a483e8c5decd)

![image](https://github.com/dataease/dataease/assets/24768910/ea2f199e-b4c7-4b12-bd84-411876bc8fc1)

**Comment by xuwei-fit2cloud** [comment]
直连模式数据源可支持分页模式，定时同步和Excel数据集是不支持真分页的，会将所有数据获取出来，应该是这个问题。
我们已有计划对此做优化，但需要些时间。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
