### ISSUE TITLE
[Feature]计数的时候，需要有group by功能，并且可以自定义group by字段

### ISSUE THREAD

**Issue by jinyingyan** [dataease/dataease#6211]
**请描述您的需求或者改进建议.**

**Comment by jinyingyan** [comment]
计数的时候，我需要自定义根据指定字段去技术，比如我目前有数据表：【用户名】、【功能按钮】、【点击时间（年月日）】三个字段，我要查询本月内，各用户使用功能按钮的次数，即：select 用户名、功能按钮、count(1)  from 数据表 where 点击时间 = 本月 group by 用户名、功能按钮，而目前的计数方法是这样的：select 用户名、功能按钮、count(1)  from 数据表 where 点击时间 = 本月 group by 用户名、功能按钮、点击时间。默认group by数据表中所有字段，而不可自定义。

**Comment by maninhill** [comment]
暂无支持计划。
