### ISSUE TITLE
[Feature]数据集页面的数据集导出按钮建议权限控制

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#6213]
**请描述您的需求或者改进建议.**
当前仪表板可以设置导出权限，但是如果有数据集的只读权限，数据集就可以导出对应的数据，无法做到完全控制，建议细化对应的权限

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
目前暂时还无支持计划。
