### ISSUE TITLE
[Feature]筛选组件选择省份后，地图视图显示对应省份地图，不是目前的全中国地图

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#6214]
**请描述您的需求或者改进建议.**

![image](https://github.com/dataease/dataease/assets/101089844/48d4038f-981e-4d39-a07e-d3e30c5d6376)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，筛选组件过滤的是视图的数据，并不改变图表展示范围，如果需要展示对应的省份数据，建议使用下钻功能。
