### ISSUE TITLE
[Feature]组合图加缩略轴 

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#6215]
**请描述您的需求或者改进建议.**
组合图加缩略轴 ，移动端宽度太小，横轴显示不全
<img width="395" alt="image" src="https://github.com/dataease/dataease/assets/101089844/d03cfdc9-90c1-49d7-a4cc-056bee8bce71">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议我们已收到，我们先看下图库是否支持，如果支持，会尽快支持上。

**Comment by xuwei-fit2cloud** [comment]
目前还无法支持。
