### ISSUE TITLE
dataease 复用仪表板后，联动的配置变成乱码

### ISSUE THREAD

**Issue by zhanghongdago** [dataease/dataease#6217]
**DataEase 版本2.0**

**Bug 描述**
dataease 复用仪表板后，联动的配置变成乱拿吗

**Bug 重现步骤(有截图更好)**
![13d057bca2d3513db62855210985350](https://github.com/dataease/dataease/assets/16815408/7ec78d8f-4f6a-43db-9d6f-14266b61a964)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，应该是被联动的视图不在当前仪表板中，我们先讨论一下优化方案。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，在最新版本中没有复现出该问题，建议您升级版本试试。
