### ISSUE TITLE
[Bug]动态排序图中“分组/维度”使用计算字段时，视图显示异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#6218]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
动态排序图中“分组/维度”使用计算字段时，视图显示异常
![image](https://github.com/dataease/dataease/assets/89771514/39ab2197-d16f-460c-8d9c-4f8b49d1d035)

![image](https://github.com/dataease/dataease/assets/89771514/acf0b2a9-ba1c-4df2-a05f-0b4d9c994f18)

![image](https://github.com/dataease/dataease/assets/89771514/8d165968-fbad-4f87-8898-c19dfcd56cde)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
