### ISSUE TITLE
[Bug]厦门市地图岛屿部分边界和实际地图有一定差异

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#6219]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
主要差异部分如下图所示：
![image](https://github.com/dataease/dataease/assets/48945409/a3833418-4bde-4ed0-8f81-b9fe290a449a)

可以参考下如下地图：
![image](https://github.com/dataease/dataease/assets/48945409/5dde45ae-5780-47bd-bfe9-768deb298c7d)

**Comment by fit2cloudrd** [comment]
我们尽量优化一下地图的轮廓。
