### ISSUE TITLE
[Bug]当上传多个第三方图库的视图插件后，选择视图类型时会提示多个三方图库类型选项

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#6220]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/89771514/705d7c6e-f636-499e-b766-efdf5d67a640)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在后续版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.12版本已处理，请升级到最新版本。
