### ISSUE TITLE
[Bug]antv明细表限制结果显示后自定义排序失效

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#6222]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.已经自定义排序将 湛江市 放第一个了
<img width="518" alt="image" src="https://github.com/dataease/dataease/assets/101089844/4aaa3995-e2de-4a59-8529-cd1b900143bd">
2.限定了显示结果后 还是现实 兴宁市
![image](https://github.com/dataease/dataease/assets/101089844/31d70a1e-7476-4578-ae3e-ca98835a90a4)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前平台设计的实现方式上无法达到你所说的程度，但可以使用sql自定义排序来解决你目前的困扰；
