### ISSUE TITLE
[Bug]使用视图插件的和数据源插件，两者组合制作仪表板视图时，视图查看异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#6223]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
1、使用kingbase数据源，并创建数据集
2、制作仪表板选择桑基图，数据集选择kingbase数据源中的数据集
3、拖入维度、指标字段后，视图显示异常
![image](https://github.com/dataease/dataease/assets/89771514/afe7898e-1a10-46fa-b44e-21552d044f61)
![image](https://github.com/dataease/dataease/assets/89771514/e1648d1a-e595-41c9-9a89-05f72d4626b2)

![image](https://github.com/dataease/dataease/assets/89771514/d0e86586-b1e4-44ff-9d05-169f6273035f)
![image](https://github.com/dataease/dataease/assets/89771514/5dac8b74-6785-4a80-8d2d-3731d1232276)

**Comment by ZhaoQian1222** [comment]
刚开始以为是数据源插件写的问题，但是排查后发现是扫描不到数据源插件里的继承SQLConstants的子类导致的，使用达梦数据源也存在同样问题
![image](https://github.com/dataease/dataease/assets/89771514/cc641f8d-a54d-49db-b74d-e366022dd7d5)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
