### ISSUE TITLE
[Feature] 仪表板导出视图明细时连带着视图图片一起导出

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6224]
**请描述您的需求或者改进建议.**
如下图所示，仪表板导出视图明细时可以把图片也一起导出。
![image](https://github.com/dataease/dataease/assets/45852479/ea8a14ee-7d4a-4c79-99e2-0238191a974c)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，暂时没有计划进行支持，原因如下：
1、用户在导出数据时，其主要目的是导出数据，不一定需要图片。
2、导出数据后，如果需要图片，也可自行将图片复制到合适的位置。

**Comment by MaekBlack** [comment]
可以做可配置选项，导出带图片、不带图片
