### ISSUE TITLE
[Feature] 视图支持甘特图

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6225]
**请描述您的需求或者改进建议.**
<img width="350" alt="image" src="https://github.com/dataease/dataease/assets/45852479/0e57237c-d96c-493b-96e3-2b463ada485c">
<img width="763" alt="image" src="https://github.com/dataease/dataease/assets/45852479/33adc24f-7ce7-43c9-a14f-cb402165d414">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，甘特图已经在需求池中，它常用于任务、活动的进度管理中，并非常见的数据分析类图表，所以当前暂时没有规划进行支持。
