### ISSUE TITLE
[Feature] 组件选中效果优化

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6226]
**请描述您的需求或者改进建议.**
每个组件都有选中效果，当出现叠加组件时体验就不太好。
选中效果是否可以设置可配置项，例如标题框或者叠加的辅助横线可以取消选中效果
<img width="714" alt="image" src="https://github.com/dataease/dataease/assets/45852479/586f8884-7949-424d-8f39-486330102c13">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议我们已收到，选中效果是所有组件统一的，暂时没有计划做特殊处理。
