### ISSUE TITLE
[Feature] 公共链接防爆破

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6228]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/45852479/4d5a1da5-2f3e-4fe1-93cc-b14a2b5c06ef)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议非常好，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
暂时没有支持计划。
