### ISSUE TITLE
[Bug]仅仅只修改文字控件中的字保存按钮未变成可点击状态

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#623]
**DataEase 版本**
v1.1.0

**浏览器版本**
Chrome 91

**Bug 描述**
在当前内容都已保存的情况下（保存按钮为灰），仅仅只修改文字控件中的文字内容后，保存按钮仍然不可点击。

**Bug 重现步骤(有截图更好)**
1.保存当前内容让保存按钮变为不可点击状态
![image](https://user-images.githubusercontent.com/48945409/129431420-64b0d81c-6b26-4e83-baf5-76971bd67e67.png)

2.双击文字内容进行修改，其余任何内容不变动，修改完成后查看保存按钮仍然不可点击，无法仅仅只保存此文字的修改
![image](https://user-images.githubusercontent.com/48945409/129431453-21925418-be03-4c55-9514-5ea8fd419d5d.png)

**Comment by xuwei-fit2cloud** [comment]
感谢您的反馈，我们尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.4.0 已修复
