### ISSUE TITLE
[Bug]符号地图标签在数据量稍多的情况下不显示

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#6233]
**DataEase 版本**
v1.18.11&v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
1、符号地图标签在数据量稍多的情况下不显示
2、v1.18.11 地图跟随鼠标移动，鼠标没有按住拖动的情况下，跟着鼠标走

**Bug 重现步骤(有截图更好)**
1.数据可联系提供，数据量在150+条
![image](https://github.com/dataease/dataease/assets/70566485/a2edc5bb-1407-4d43-a752-48b2eff0eca8)
![image](https://github.com/dataease/dataease/assets/70566485/aa40072a-c114-48d3-9ef5-089e338a5e16)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by fit2cloud-chenyw** [comment]
经排查，是数据中存在经纬度字段值为空的记录导致！已修复请等待下版发布
