### ISSUE TITLE
[Bug]API数据源数据结构不含暂时为空的字段

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#6234]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
API数据源数据结构不含暂时为空的字段，这个问题在 v1.14.0 版本中处理过，现在依然存在，见#2845

整包部署测试
![image](https://github.com/dataease/dataease/assets/89771514/e31d3c9d-8bb1-48ec-9937-3e020b014262)
![image](https://github.com/dataease/dataease/assets/89771514/88764d56-3aa6-480a-bae1-ef766255aaa6)

本地测试
![image](https://github.com/dataease/dataease/assets/89771514/692975d9-d61a-474e-bceb-6ef538173389)
![image](https://github.com/dataease/dataease/assets/89771514/558e3bb5-2d78-4ab9-9d50-24e53a7d29b1)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
