### ISSUE TITLE
[Feature]仪表盘支持iframe嵌入

### ISSUE THREAD

**Issue by While4** [dataease/dataease#6235]
### 需求背景
通过iFrame，可以就像在网站上打开一个窗口以显示外部内容一样，实际内容从嵌入的源中加载。
比如嵌入：
1、天气
2、时间
3、视频
4、图片
...

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，系统是支持网页组件的，用于显示第三方的内容，建议您参考文档配置一下（文档地址：https://dataease.io/docs/user_manual/other_module/other_module/#2）

**Comment by While4** [comment]
我是想集成一些其他的小组件，甚至于简单的HTML代码，例如以下HTML代码：
![image](https://github.com/dataease/dataease/assets/47239344/135120ad-deb7-427d-9b4e-10c4a804191a)
最终效果：
![image](https://github.com/dataease/dataease/assets/47239344/3e069c16-bfb6-46d4-bac4-8a3d44a847a9)

**Comment by While4** [comment]
请问这个可以实现吗？

**Comment by xuwei-fit2cloud** [comment]
出于安全性的考虑，我们暂时还不会增加相关支持。
