### ISSUE TITLE
[Feature]流向地图能否做一个3D 地球的视图？

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6236]
**请描述您的需求或者改进建议.**
如图所示的流向地图，希望可以在这种 3D 地图上实现流向效果。
<img width="384" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/590c4a11-eee6-4b6a-bf78-3e1dbf241cc7">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先记录并调研一下。
