### ISSUE TITLE
[Feature]柱状图项目名称能增加序号吗？可以支持向下滑动吗

### ISSUE THREAD

**Issue by jiangyunhao** [dataease/dataease#6237]
**请描述您的需求或者改进建议.**
1、这个可以用鼠标滑轮向下滑动吗？
2、前面能否显示序号？
![1696759800844](https://github.com/dataease/dataease/assets/77140433/50d38084-d3fe-4ab2-aeb9-ecb37376c9eb)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
暂时还无法支持。
