### ISSUE TITLE
[Bug]  - 1.18.11 辅助线导致图表异常

### ISSUE THREAD

**Issue by jasonci198** [dataease/dataease#6238]
**DataEase 版本 - v1.18.11**

**运行方式 - 安装包运行 **

**浏览器版本 - chrome-113** 

**Bug 描述**

**Bug 重现步骤**
1. 1.18.6升级到1.18.11，原有图表展示异常
2. 排查发现是动态辅助线设置问题
3. 删除辅助线或固定值辅助线均正常显示

![image](https://github.com/dataease/dataease/assets/129830691/05a79143-ec8f-4990-ac76-6672764ead6b)

![image](https://github.com/dataease/dataease/assets/129830691/7b6a3066-9e25-4ac7-aca2-6dcf2d8089c8)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你使用的数据源是什么？

**Comment by jasonci198** [comment]
> 感谢反馈，请问你使用的数据源是什么？

odps

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在后续版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
