### ISSUE TITLE
[Bug]复制来的仪表板导出成应用失败

### ISSUE THREAD

**Issue by aihpossssssssssssssssssssssss** [dataease/dataease#6239]
**DataEase 版本**
1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
火狐最新版

**Bug 描述**
从仪表板A复制得到仪表板B，对仪表板B进行修改，此时，仪表板A中的视图均由数据源A配置而来，仪表板B的视图均由数据源B配置而来，但是在导出仪表板B为应用时失败。

**Bug 重现步骤(有截图更好)**
1.创建仪表板A，仪表板A中的视图均由数据源A配置而来；
2.复制仪表板A得到仪表板B，修改仪表板B，保证仪表板B中的视图均由数据源B配置而来；
3.选择仪表板B，选择导出为应用。
![图片](https://github.com/dataease/dataease/assets/39285782/db02729e-1a8e-400b-8d6b-336bd9e3d558)

**Comment by BBchicken-9527** [comment]
感谢反馈，如果你复制之后不修改数据源是否可以正常的导出为应用呢？我这边在本地环境尝试并没有发现你说的这个问题，受累再确认一下是否有数据源遗漏修改了，或者你可以尝试减少视图然后导出测试一下；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
