### ISSUE TITLE
[Feature]数据集中excel数据源编辑时是否可以支持字段新增、删除

### ISSUE THREAD

**Issue by wml3** [dataease/dataease#624]
**请描述您的需求或者改进建议.**
如标题描述，当前只有替换以及追加行数，是否可以对已有表格的字段进行编辑，新增字段；
或者支持新增了字段的表格（在原表基础上增加几个字段）替换

**Comment by yayanpei** [comment]
感谢您的反馈，我们先讨论一下该需求。

**Comment by xuwei-fit2cloud** [comment]
v1.2.0支持新增计算字段
