### ISSUE TITLE
[Bug]横向堆叠柱状图自定义排序失效

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#6240]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
横向堆叠柱状图调整堆叠项排序时，未按调整项变化
![image](https://github.com/dataease/dataease/assets/85436572/7fc990a6-81d4-4b7f-ac9c-2b8c68e56f80)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
暂时没有支持计划。
