### ISSUE TITLE
[Bug] AntV 折线图图例缺失

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#6241]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/85436572/eccc74a7-234a-451c-b0ab-5c9a9f40a32a)
当数据维度较多时，缺少 10 月 5 日图例

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，受累确认一下是否调整了展示结果条目数导致数据获取的时候没有拿到你想要的数据；
