### ISSUE TITLE
[Feature]处理 iso8601 格式日期字段

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#6242]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/85436572/90f8cdf0-d9da-4688-847f-28c8f5c1cbc3)
希望能新增该格式的日期字段的处理

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先进行内部讨论。

**Comment by xuwei-fit2cloud** [comment]
目前还是建议先用字符处理函数来预处理一下时间文本字段。
