### ISSUE TITLE
[Bug]地图放大后，下钻和联动悬浮框位置偏离选择区域

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#6243]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/85436572/260cb41c-957d-4bc6-a4e7-584790ce4b48)
如图所示

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
