### ISSUE TITLE
[Bug]通过日期字段联动，日期展示形式不同，则联动失效

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#6244]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.使用一个包含日期字段的数据集制作两个视图 A 和 B
2.在两个视图中对日期字段显示不同的日期格式，如 年月、年周
3.对两个视图添加日期字段的联动
4.联动失效

**Comment by BBchicken-9527** [comment]
感谢反馈，如你所说的这种方式处理逻辑比较复杂所以目前暂不支持这种使用的方式，目前联动逻辑类似于等于；
