### ISSUE TITLE
[Feature]自定义过滤组件内部字体大小以及组件内部筛选框高度

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#6245]
**请描述您的需求或者改进建议.**
当前在悬浮模式下，可以使用位置自定义组件大小。但过滤组件内部线框和字体大小是固定值，希望能够随组件大小自适应或增加内部调整大小的设置

**Comment by xuwei-fit2cloud** [comment]
暂时不支持过滤组件的文字大小随组件的大小自适应，其他图表的横纵轴坐标等也是根据设置的字体大小，没有根据图表的大小进行自适应。
