### ISSUE TITLE
[Feature]水波图希望可以计算占比

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#6248]
**请描述您的需求或者改进建议.**
水波图希望可以计算某一项占总数的比，如学士的人数，占总数的百分之几
![wecom-temp-4130-4de1462ba125475a04a01f84a9ff4db6](https://github.com/dataease/dataease/assets/133861755/4db44ae1-6ea3-4f29-b8d2-64fe91518be2)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，该需求暂时无法实现，因此我们先关闭了。
