### ISSUE TITLE
[Feature]是否可以支持对已有视图克隆以及替换数据集

### ISSUE THREAD

**Issue by wml3** [dataease/dataease#625]
**请描述您的需求或者改进建议.**
如题所述：
        某些情况下，感觉这个视图的样式设计花了心思，是否可以克隆视图或者将视图保存样式，在原有的视图基础上进行设计，并替换数据集

**Comment by xuwei-fit2cloud** [comment]
目前在仪表板里支持对引用的视图进行复制，视图页本身还没有支持。

**Comment by xuwei-fit2cloud** [comment]
v1.1.0 已支持数据集替换
