### ISSUE TITLE
[Feature]希望可以添加流程图一样的图表组件

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#6250]
**请描述您的需求或者改进建议.**
希望可以添加流程图一样的图表组件，方便更好的讲数据故事
<img width="1274" alt="image" src="https://github.com/dataease/dataease/assets/133861755/0b538cfa-d970-4515-bbd7-f6ed66080c47">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们所使用的图库里是有相关图表类型，但实验的效果并不太理想，该需求先挂起，等待后续反馈。
