### ISSUE TITLE
[Bug]富文本视图的表格单元格间距不生效

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6251]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
 chrome

**Bug 描述**
富文本视图中，加入表格，表格属性设置 单元格外边距、单元格内间距，设置没有变化，是使用方法不对还是故障？
![图片](https://github.com/dataease/dataease/assets/48307752/c63fa741-3ea3-4ae5-b325-b0399936514e)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。
