### ISSUE TITLE
[Feature]移动端打开公共链接下载查看仪表板的功能希望可以完善下

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#6252]
**请描述您的需求或者改进建议.**
移动端打开公共链接下载查看仪表板的功能希望可以完善下，目前下载的页面全是乱的，并且下载是空白页面
<img width="332" alt="image" src="https://github.com/dataease/dataease/assets/133861755/a8f1e202-9b18-41e7-b8ce-ceab07363649">
<img width="332" alt="image" src="https://github.com/dataease/dataease/assets/133861755/55805290-23ee-4235-b8d9-dd136f6d9c15">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
