### ISSUE TITLE
【Bug】antv基础折线图图例内容超7后不展示部分图例

### ISSUE THREAD

**Issue by pangzhili** [dataease/dataease#6253]
**DataEase 版本**
当前官网最新版本

**运行方式(安装包运行 or 源码运行 ?)**
官网最新版本

**浏览器版本**
版本 117.0.5938.134（正式版本） （64 位）

**Bug 描述**
antv基础折线图中图例的显示当达到8条以上时，默认显示7条，部分图例数据丢失，但是视图上能正常展示数据。

**Bug 重现步骤(有截图更好)**
1. 导入excel数据集，此表格中数据存在9天的数据
![image](https://github.com/dataease/dataease/assets/46517296/974b87ef-d205-4d87-8afe-489376aaf136)
[测试bug.xlsx](https://github.com/dataease/dataease/files/12865631/bug.xlsx)
2. 新建视图，使用此数据集创建anv基础折线图
![image](https://github.com/dataease/dataease/assets/46517296/7dba5b0d-9cda-4890-9b4e-135c3184c1a2)
3. 最终发现，图例中丢失部分内容展示，仅展示了7条数据

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。
