### ISSUE TITLE
[Bug]AntV视图中明细表数据量比较大时，导出明细表数据出现异常：java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#6254]
**DataEase 版本**
1.18.10

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 117.0.5938.150

**Bug 描述**
仪表盘中使用AntV明细表视图，数据约21万，全量导出时出现内存溢出问题

**Bug 重现步骤(有截图更好)**
问题出现在类PanelGroupService的findExcelData方法，如下图所示。怀疑没有采用分页方式全量查询，字段信息比较多的情况下会导致该问题出现。
![20231011-1](https://github.com/dataease/dataease/assets/27687681/ef57717e-ed4d-431b-acc1-b9eca5c1189f)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们在图表数据导出这了做了100w的限制，由于不可控的原因，用户自行打包或者二次开发产生的问题请用户自行研究解决。这里先把issue关掉。如果后面建议用官方镜像和官方安装方式再出现问题可以再打开issue。

**Comment by xiaorsly88** [comment]
限制100W数据没有问题，但直接一次性查询100W数据会导致内存溢出的概率会较大，因为包装的chartViewInfo对象包含了太多除数据以外的属性，相当于将查询记录的大小翻了几倍，我本次调试了一下，将一次查询拆成循环100次，每次10000行，这样每次从chartViewInfo中取出tableRow（数据行）后，临时变量待垃圾回收，整个内存会恢复。目前我实验，导出同样30W数据没有内存溢出。 但潜在的，数据量达到堆配置的阈值，仍有潜在OOM风险。
![image](https://github.com/dataease/dataease/assets/27687681/0ff49301-c210-431a-a8be-017f910124e9)
