### ISSUE TITLE
[Bug]文本过滤组件中文本下拉的数据不全问题

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#6255]
**DataEase 版本**
1.18.10

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 117.0.5938.150

**Bug 描述**
仪表盘中使用文本下拉组件进行条件过滤，下拉列表中的值不全

**Bug 重现步骤(有截图更好)**
1.准备一个mysql的SQL数据集，数据集记录超过1000，数据越多效果越明显
2.准备一个仪表盘，拖选文本下拉组件
3.验证文本下拉组件，发现数据缺失

跟踪源码发现页面调用了的方法过程如下：
1、DataSetTableFieldController类的方法multFieldValues
2、DirectFieldService类的方法fieldValues
3、问题出现在如下图图一所示的“datasourceRequest.setQuery(qp.createSQLPreview(createSQL, null)); ”，通过debug发现使用了MysqlQueryProvider中的createSQLPreview方法，方法中在sql结尾有附加"limit 0,1000"，如果数据集记录超过1000条以上，则下拉框中显示的值是该1000条记录中去重后的字段值，但明显，1001条记录之后的值记录丢失了

图一：
![image](https://github.com/dataease/dataease/assets/27687681/87fe84ae-e433-4466-929f-467a3b4fe3b4)

图二：
![image](https://github.com/dataease/dataease/assets/27687681/0ccc51d3-1f4f-44b0-90e6-02285670b904)

**Comment by BBchicken-9527** [comment]
感谢反馈，这里是预览数据，并且由于不可控的原因，用户自行打包或者二次开发产生的问题请用户自行研究解决。这里先把issue关掉。如果后面建议用官方镜像和官方安装方式再出现问题可以再打开issue。
