### ISSUE TITLE
[Bug] 定时同步数据集，年月组件过滤失效

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6256]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
定时同步数据集，年月组件过滤失效

**Bug 重现步骤(有截图更好)**
前端抓取到的 sql 如下：
<img width="912" alt="image" src="https://github.com/dataease/dataease/assets/45852479/d3f2181c-5ee4-4549-9a47-24e253df91a3">
没有000和999，sql 可以查询到结果

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.12已处理，请更新版本。
