### ISSUE TITLE
[Feature]希望支持http://url地址显示图片功能，url地址从数据库表字段中获取

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#6260]
**请描述您的需求或者改进建议.**
希望支持http://url地址显示图片功能，url地址从数据库表字段中获取，将图片以二进制的形式存储在数据库表的字段中，在dataease中将其进行展示，数据库中地址字段更新，dataease也会及时更新

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前图片组件，可支持上传本地图片，或者在线图表。请问根据地址展示图片，是在表格中展示图片吗？还是图片组件？

**Comment by xuwei-fit2cloud** [comment]
没有相关的支持计划。
