### ISSUE TITLE
[Bug] sql数据集设置参数报错

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#6263]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
 117.0.5938.134（正式版本） （64 位）

**Bug 描述**
数据源为doris，使用sql数据集并设置参数时报错

**Bug 重现步骤(有截图更好)**
1.新建sql数据集，数据源为Doris，sql如：
select * from alp
lateral view explode_split(replace(second_tag_names,'，',','), ',') tmp1 as second_tag_name
where first_tag_name in ${param}
2.点击运行查询发现报错
3.将in ${param}修改为 in ('a', 'b')后，点击运行查询是可以正常执行的
4.执行select * from alp where first_tag_name in ${param}是正常的

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在后续版本修复这个问题。

**Comment by YS0mind** [comment]
I also find this problem，it maybe SQL parser doesn't support lateral view grammar？

**Comment by xuwei-fit2cloud** [comment]
> I also find this problem，it maybe SQL parser doesn't support lateral view grammar？

是的，目前还无法处理该问题。
