### ISSUE TITLE
[Bug]下拉树二级目录过长导致无横向滚动条

### ISSUE THREAD

**Issue by pangzhili** [dataease/dataease#6264]
**DataEase 版本**
当前官网最新版本

**运行方式(安装包运行 or 源码运行 ?)**
官网最新

**浏览器版本**
版本 117.0.5938.134（正式版本） （64 位）

**Bug 描述**
下拉树数据中当一级目录较短，二级目录较长时，会导致无横向滚动条，没有办法查看二级目录的全部内容。

**Bug 重现步骤(有截图更好)**
1. 导入excel数据集
[测试bug.xlsx](https://github.com/dataease/dataease/files/12876546/bug.xlsx)
2. 新建下拉树组件，组件配置如
![image](https://github.com/dataease/dataease/assets/46517296/d7210fe1-fc51-4776-977f-8900f4f333e8)
3. 缺少横向滚动条，没有办法查看二级目录所有内容
![image](https://github.com/dataease/dataease/assets/46517296/b6e728f6-9e57-41a1-b9ee-a16484838b22)

**Comment by pangzhili** [comment]
麻烦得空帮忙看下此问题，是否是前端层次问题

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
