### ISSUE TITLE
[Feature]1.x版本 ECharts 表格增加跳转功能

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#6266]
**请描述您的需求或者改进建议.**
ECharts的表格有点击表头排序的功能，而且数据量大的时候用AntV容易崩溃，ECharts也更合适。我看很多用户 在用表格的时候 如果不追求样式设计 都更青睐用ECharts。希望添加跳转等功能设计

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先调研下echarts的表格是否支持。

**Comment by wisonic-s** [comment]
[feat: Echarts 表格联动跳转](https://github.com/dataease/dataease/pull/6610)

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
