### ISSUE TITLE
[Bug]修改已存在数据源保存时提示已存在相同配置数据源

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6267]
**DataEase 版本**
v.1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
修改数据源点击保存会提示已存在相同配置数据源，这个提示应该是再新建数据源提示，不应该在修改原有数据源这里提示
<img width="1162" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/a2487212-ef58-431f-b6e9-fb039269bbb4">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在后续版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
