### ISSUE TITLE
[Feature]下拉树组件希望可以支持多个图表，或者其他方式做级联

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#6268]
**请描述您的需求或者改进建议.**
下拉树组件希望可以支持多个图表，或者其他方式做级联
<img width="1030" alt="image" src="https://github.com/dataease/dataease/assets/133861755/9e4509ef-1adc-4549-bed8-bfbbd3f32ba5">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，下拉树近期暂时没有计划支持跨数据集的字段关联。
