### ISSUE TITLE
[Bug]水波图在百分百的状态下显示有问题，图形自适应大小变化卡顿

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#6269]
DataEase 版本
当前官网最新版本

运行方式(安装包运行 or 源码运行 ?)
官网最新

浏览器版本
Chrome

**Bug 描述**
水波图在百分百的状态下显示有问题，其他数值正常，拖动视图大小时，水波图形自适应大小变化卡顿，点击编辑或者页面大小变化才会恢复正常
![image](https://github.com/dataease/dataease/assets/133861755/a832a3df-54db-446d-896e-3d0bc766084b)
![image](https://github.com/dataease/dataease/assets/133861755/bdbd4c3e-fbcb-4ae7-a9bf-6de0864df190)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
