### ISSUE TITLE
[Bug]浏览器窗口变化时，会自动刷新数据，参数为空

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#6270]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
117.0.5938.134（正式版本） （64 位）

**Bug 描述**
设置了了过滤条件，并添加了查询按钮，在浏览器窗口发生变化后，会重新刷新数据，并且过滤条件没有生效

**Bug 重现步骤(有截图更好)**
1.初次加载时如图
![image](https://github.com/dataease/dataease/assets/26103277/8743dbd7-d977-4663-a501-f4b0cbd5714b)
2.改变浏览器窗口大小后
![image](https://github.com/dataease/dataease/assets/26103277/f1434e0e-8324-4ec0-98f6-775111240548)
发现数据发生了变化
3.查看请求参数
![image](https://github.com/dataease/dataease/assets/26103277/18e07e7e-5783-4e8d-85c6-f4e969a88ba0)

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是添加了默认选项之后添加了按钮移动窗口导致了默认选项没有生效嘛？

**Comment by hw872715125** [comment]
不是，是第一次打开这个仪表板时，加载的数据是正常的，是按着上面的过滤组件中的值去查询的数据。但是只要窗口发生了变化，就会重新去查询一次数据，而且没有按着上面过滤组件中的值去查询数据。

**Comment by hw872715125** [comment]
@BBchicken-9527 不是，是第一次打开这个仪表板时，加载的数据是正常的，是按着上面的过滤组件中的值去查询的数据。但是只要窗口发生了变化，就会重新去查询一次数据，而且没有按着上面过滤组件中的值去查询数据。

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你用的是什么系统什么浏览器呢？

**Comment by hw872715125** [comment]
windows系统，谷歌浏览器

**Comment by BBchicken-9527** [comment]
感谢反馈，我这边依然没有复现你说的那个问题，你的这个方式百分百可以复现吗？

**Comment by hw872715125** [comment]
@BBchicken-9527 可以百分百复现，必须要有查询按钮，如果你复现不出来，那么你先建好仪表板后保存刷新整个界面，再重新去查看这个仪表板，如下图
![image](https://github.com/dataease/dataease/assets/26103277/f4b70c0c-9709-4715-a180-e884cf57c0e5)
这个时候点浏览器右上角的窗口化按钮或其他方式改变浏览器窗口大小后，发现数据会刷新，刷新数据如下图：
![image](https://github.com/dataease/dataease/assets/26103277/a41171f9-f893-4eaa-abe2-389c433ed970)

**Comment by BBchicken-9527** [comment]
感谢反馈，由于之前没有察觉到你的回复实在不好意思，经过我反复的尝试确实会存在这个问题，并且我看你也重新提交了相同的问题，我这边已经和开发反馈了这个问题，我先将这个重复问题关闭，后续修改完成会同步到你新提交的问题上，针对我的疏忽再次表达歉意；
