### ISSUE TITLE
[Bug]API数据集因为返回字段不全，导致无法正常同步

### ISSUE THREAD

**Issue by SevenCham** [dataease/dataease#6271]
**DataEase 版本**

1.18
**运行方式(安装包运行 or 源码运行 ?)**

源码运行 

**浏览器版本**

**Bug 描述**
通过api的数据源，添加了一个数据集，但是因为返回的数据字段不全，比如一共20个字段，但是返回的数据，有的可能缺少某些字段，同步成功之后，数据表为空，请问以后会优化这个问题么，

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/31249168/aed694f2-2520-421b-82bc-f4d06402ce1d)

2.
![image](https://github.com/dataease/dataease/assets/31249168/7510a162-ed98-4e4f-bde3-00c35f79a42d)

3.
![image](https://github.com/dataease/dataease/assets/31249168/268e953d-04c9-442a-8c71-ce497f87355b)

**Comment by BBchicken-9527** [comment]
由于不可控的原因，用户自行打包或者二次开发产生的问题请用户自行研究解决。这里先把issue关掉。如果后面建议用官方镜像和官方安装方式再出现问题可以再打开issue。
