### ISSUE TITLE
[Feature]选项卡希望可以拖动另一个选项卡进去，形成二级选项卡

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#6273]
**请描述您的需求或者改进建议.**
选项卡希望可以拖动另一个选项卡进去，形成二级选项卡
![image](https://github.com/dataease/dataease/assets/133861755/6442f2b0-fad5-4926-8f24-6591373f5e75)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，近期暂无支持二级选项卡的计划。
