### ISSUE TITLE
[Feature]【视图】柱状图支持特殊柱面标记颜色

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#6274]
**请描述您的需求或者改进建议.**
柱状图支持特殊柱面标记颜色，当维度等于 A 时，该柱面标记红色……

**Comment by DiamondMyK** [comment]
Please assign this task to me and I am willing to take charge of solving it.Thanks. @AndroidBaby1

**Comment by xuwei-fit2cloud** [comment]
很抱歉，目前还没有合适的方式可以支持。
