### ISSUE TITLE
[Feature] 希望透视图的快速计算占比支持按行或按列汇总

### ISSUE THREAD

**Issue by seanwwh** [dataease/dataease#6275]
**请描述您的需求或者改进建议.**
如图所示，目前透视图的快速计算占比只支持全部汇总的占比
![image](https://github.com/dataease/dataease/assets/5187541/96351bfe-4378-459c-86e0-a56664410a69)
希望能像Tableau或Excel一样支持按行或按列汇总占比
![image](https://github.com/dataease/dataease/assets/5187541/b4eaee00-b715-4c87-a2bf-b17fb198331d)
![image](https://github.com/dataease/dataease/assets/5187541/1fd1dacc-b465-4c4b-8308-6fcdc9f944f2)

**Comment by maninhill** [comment]
暂无支持计划。
