### ISSUE TITLE
[Feature]希望定时同步任务支持在历史数据变动后增量更新到doris中

### ISSUE THREAD

**Issue by seanwwh** [dataease/dataease#6276]
**请描述您的需求或者改进建议.**
有些业务情况下，已经同步到doris的数据会发生改变，需要再次增量更新到doris中，目前的增量更新只有增量insert或delete，且只能二选一，无法实现update操作，这将导致数据的重复。具体现象参见 https://github.com/dataease/dataease/issues/2904 。
希望增量更新时可以指定关联键，通过关联键自动判断对doris中的数据进行增量insert或update，类似于下文中介绍的Kettle增量更新功能 https://www.cnblogs.com/stuka/p/11245623.html。

**Comment by xuwei-fit2cloud** [comment]
非常感谢，我们先研究一下，如果可行的话，我们会在后续版本中添加相关优化。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
