### ISSUE TITLE
[Bug]数值下拉组件

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6277]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
正在检查更新
版本 117.0.5938.149（正式版本） (arm64)

**Bug 描述**
数值下拉组件，设置排序不生效

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/a4e469eb-ec67-4875-9f17-cb62da8e1670)

2.
![image](https://github.com/dataease/dataease/assets/109720729/8bad90a9-f578-4611-b6be-35992bc8aeba)

3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们会尽快修复。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
