### ISSUE TITLE
[Feature]当定时同步任务日志较多时查询较慢。建议优化查询效率或提供历史日志清除功能。

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#6278]
**请描述您的需求或者改进建议.**
当定时同步任务日志较多时查询较慢。建议优化查询效率或提供历史日志清除功能。

详情：
1. dataset_table_task 表数据量：271
2. dataset_table_task_log 表数据量：747002
3. dataset_table_task_log 去除Excel导入日志数据量：746999
4. 慢查询日志见截图和附件：
![381697508676_ pic](https://github.com/dataease/dataease/assets/30886198/ab47dd47-25e6-4d6f-8674-887c15da6222)

[dataease慢SQL.txt](https://github.com/dataease/dataease/files/12923974/dataease.SQL.txt)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们后续版本会进行相关优化。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
