### ISSUE TITLE
[Bug]明细表会清空

### ISSUE THREAD

**Issue by sanglei0807** [dataease/dataease#6279]
**DataEase 版本**

1.18.11
**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**
Chrome 118.0.5993.70

**Bug 描述**
新建明细表拖入维度指标后 点击其他地方，再回来点明细表 会把刚配置好的维度合指标清空

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/33617860/458a0248-830d-44c7-a077-65fd898f3f80)

2.
![image](https://github.com/dataease/dataease/assets/33617860/0d566ff2-feae-4afc-911b-588ffa5e8938)

3.

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.12版本已处理，请更新版本。
