### ISSUE TITLE
[Bug] Echarts 视图提示消息在全屏预览并放大的情况下失效

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#6280]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 118.0.5993.70（正式版本） (arm64)

**Bug 描述**
Echarts 视图提示信息在全屏预览并放大的情况下失效

**Bug 重现步骤(有截图更好)**
1. 仪表板预览界面，提示信息可正常显示：
![image](https://github.com/dataease/dataease/assets/30063018/fd202e37-1793-47a8-877d-72a22a35747e)
2. 全屏预览并放大图片的情况下，提示信息无法显示：
![image](https://github.com/dataease/dataease/assets/30063018/f60e21ea-5f37-4654-8802-a5ce0622ef4a)

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
