### ISSUE TITLE
[Bug] 全屏预览情况下，靠右侧的日期范围组件显示不全

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#6281]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 118.0.5993.70（正式版本） (arm64)

**Bug 描述**
全屏预览情况下，靠右侧的日期范围组件显示不全

**Bug 重现步骤(有截图更好)**
1. 如下所示：
![image](https://github.com/dataease/dataease/assets/30063018/098efafd-408f-4d2a-b383-e81f52871ed0)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.12版本已处理，请更新版本。
