### ISSUE TITLE
[Feature] 组合图扩展

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#6282]
**请描述您的需求或者改进建议.**
组合图支持堆叠图以及面积图，扩充图表类型
![image](https://github.com/dataease/dataease/assets/30063018/c8d5f5de-31f1-4a12-a0ef-9672bc5efdee)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前支持常见的组合类型，暂时没有扩展其他图表组合的计划。
