### ISSUE TITLE
[Feature]【视图】符号地图优化

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#6283]
**请描述您的需求或者改进建议.**
undefined.百度的坐标系和高德的坐标系会有偏差，希望符号地图可以开放设置给用户选择是用高德地图还是百度地图。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前的符号地图是基于高德开发的，不支持再切换为百度地图或者其它地图。
