### ISSUE TITLE
[Feature]【数据源】希望 Oracle 数据源支持 AL32UTF8 字符集

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#6285]
**请描述您的需求或者改进建议.**
希望 Oracle 数据源支持 AL32UTF8 字符集
Oracle 字符集截图：
![image](https://github.com/dataease/dataease/assets/24768910/41662122-22a7-4520-8d9d-4385bf9175d4)
当前数据源配置字符集为 utf-8 时的显示：
![image](https://github.com/dataease/dataease/assets/24768910/37917676-a3b5-4659-808e-1fe1fa1da76f)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先调研并讨论一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
