### ISSUE TITLE
[Bug]仪表盘视图设置了阈值后，刻度无法去掉

### ISSUE THREAD

**Issue by hzhwyh0116** [dataease/dataease#6286]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome

**Bug 描述**
仪表盘视图设置了阈值后，刻度无法去掉

**Bug 重现步骤(有截图更好)**
<img width="1425" alt="image" src="https://github.com/dataease/dataease/assets/89765365/b013f026-4cf6-4075-8a07-8d0da7497774">

建议可以修改刻度的字体大小，不然很容易出现刻度值重叠的情况~

**Comment by xuwei-fit2cloud** [comment]
v1.18.12版本已处理，请更新版本。
