### ISSUE TITLE
[Feature]【数据集】SQL 数据集变量希望支持 with rollup

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#6287]
**请描述您的需求或者改进建议.**
SQL 数据集变量希望支持 with rollup，且 with rollup 作为关键字高亮显示。
不带变量：
![image](https://github.com/dataease/dataease/assets/24768910/2e9ce7c0-5a41-4461-8788-06fa77413f15)
带变量：
![企业微信截图_6875ae7c-adaf-467b-bbb1-6d697c5f7655](https://github.com/dataease/dataease/assets/24768910/cd3ca00f-b6c6-4ea2-8be4-4291ccdac54d)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请问是什么类型的数据源？

**Comment by AndroidBaby1** [comment]
MySQL

**Comment by xuwei-fit2cloud** [comment]
目前还解决不了这个问题。
