### ISSUE TITLE
[Feature]希望仪表板增加编辑时自动锁定功能， 防止多人编辑进入时误保存后图表被删除的风险。

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#6289]
**请描述您的需求或者改进建议.**
希望仪表板增加编辑时自动锁定功能， 防止多人编辑进入时误保存后图表被删除的风险。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，手动锁定已经加入需求池中，我们还需要进一步确认实现方式，因此近期暂时没有规划进行支持。
