### ISSUE TITLE
[Feature]文本搜索组件可以设置全文匹配或绑定数据集参数

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#6291]
在使用文本搜索组件进行条件过滤时，发现是模糊查询，如果查询字段是索引字段时，此时查询不走索引，会比较慢。因此是否可以优化该组件，使其可以设置为全文匹配？ 或者是可以设置绑定数据集中的参数，在SQL中去处理全文匹配还是模糊匹配？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，重复需求：https://github.com/dataease/dataease/issues/5718 ，已经在需求池中，并规划在后面几个版本进行实现。
