### ISSUE TITLE
[Bug]富文本视图中的表格边框样式设置为无或 Hidden 均无法隐藏

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#6292]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
富文本视图中的表格边框样式设置为无或 Hidden 均无法隐藏，显示为虚线。

**Bug 重现步骤(有截图更好)**
1.在富文本视图中增加表格，初始边框显示如下：
![image](https://github.com/dataease/dataease/assets/48945409/c8807876-cee7-4fcf-849f-56545b149210)

2.做以下修改来试图隐藏边框：
![image](https://github.com/dataease/dataease/assets/48945409/63dbbc7d-05c4-4cf7-932f-fed214a2915a)
![image](https://github.com/dataease/dataease/assets/48945409/8e896a0c-b2ba-44c1-ac6a-beeb57ba60bf)
完成后边框显示为虚线，并未消失：
![image](https://github.com/dataease/dataease/assets/48945409/d830c295-f7b3-45fd-828c-402ae1f41d2f)

3.将边框样式设置为 Hidden：
![image](https://github.com/dataease/dataease/assets/48945409/c059959a-cb18-4bc3-a53f-5054530e16d4)
整个表格四周的边框线消失了，但是内边框线仍然为虚线：
![image](https://github.com/dataease/dataease/assets/48945409/f59dd10c-30bf-4345-9b96-c5202c6f46f7)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by BBchicken-9527** [comment]
这里经过测试 是表格自有属性的问题

单元格如果隐藏使用的单元格属性
![image](https://github.com/dataease/dataease/assets/84372766/d5e30fe4-03f3-4054-88de-80212b8a0939)
![image](https://github.com/dataease/dataease/assets/84372766/3f1807d1-6324-4294-a614-33e600ef5dec)


不过只能隐藏当前所在的单元格边框
![image](https://github.com/dataease/dataease/assets/84372766/3f84c3ab-0800-45e1-8e89-991f931d632a)
