### ISSUE TITLE
[Bug]ES数据源创建数据集后报错

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6293]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
 chrome

**Bug 描述**
 数据源是 elasticsearch:6.8.11
新建数据集正常；

保存后预览报错：
预览数据错误：执行SQL失败。可能因相关字段、表、数据集等元素发生变更，请检查->java.lang.RuntimeException: HttpClient查询失败: {"error":{"root_cause":[{"type":"verification_exception","reason":"Found 1 problem(s)\nline 9:5: Cannot use field [geoValue] type [geo_point] as is unsupported"}],"type":"verification_exception","reason":"Found 1 problem(s)\nline 9:5: Cannot use field [geoValue] type [geo_point] as is unsupported"},"status":400}   
![图片](https://github.com/dataease/dataease/assets/48307752/ebb54217-59e4-48ea-8bb5-04de9e08d70f)

查询报错得知：
这个错误消息似乎是与执行SQL查询相关的问题，与数据中的字段类型有关。错误消息中提到了一个字段 geoValue，它的类型被指定为 geo_point，但不支持此类型的操作。这意味着你正在尝试在 geoValue 字段上执行不支持 geo_point 类型的操作，可能是由于查询语句中的某些操作不支持地理位置数据。

其他数据创建数据集正常，只有这个数据集报错，所以，“geoValue 字段上执行不支持 geo_point 类型的操作” 是在技术上无法实现吗？

ES 6.8.11 可以通过docker 创建
docker run -d --name elasticsearch  -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:6.8.11
（附件中有 ES 的mapping 和数据，如果有需要可以复现一下）
[mapping.json](https://github.com/dataease/dataease/files/12999258/mapping.json)
[data.json](https://github.com/dataease/dataease/files/12999261/data.json)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
