### ISSUE TITLE
[Feature]使用数据同步到自带的Doris中，decimal类型应该映射为Doris的DECIMALV3

### ISSUE THREAD

**Issue by xinkeng0** [dataease/dataease#6296]
我有一个 mysql decimal(35, 4) 字段，将其定时同步到数据集会同步失败。

> java.sql.SQLException: errCode = 2, detailMessage = Precision of decimal must between 1 and 27. Precision was set to: 35.

https://github.com/dataease/dataease/blob/6c964254b8548d3ee9b5931f0d4996dbc094539d/core/backend/src/main/java/io/dataease/provider/engine/doris/DorisDDLProvider.java#L74-L80

- https://doris.apache.org/docs/1.2/sql-manual/sql-reference/Data-Types/DECIMALV3/

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们规划升级一下doris

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
