### ISSUE TITLE
[Bug]keywords:mysql,arm64,mac,installation,failed

### ISSUE THREAD

**Issue by libeiheng** [dataease/dataease#6298]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
按照如下链接文档安装的
https://dataease.io/docs/installation/offline_installation_macos/

**浏览器版本**
还没有启动浏览器呢.

**Bug 描述**
*******************************************************

======================= 开始安装 =======================
sed: 1: "docker-compose-mysql.yml": extra characters at the end of d command
[DATAEASE Log]: 拷贝配置文件模板文件  -> /Users/abc/
[DATAEASE Log]: 根据安装配置参数调整配置文件 
time: 2023年10月19日 星期四 18时36分28秒 CST
[DATAEASE Log]: 加载镜像 
Loaded image: registry.cn-qingdao.aliyuncs.com/dataease/dataease:v1.18.11
Loaded image: registry.cn-qingdao.aliyuncs.com/dataease/doris:v1.2.4.1-0606
Loaded image: registry.cn-qingdao.aliyuncs.com/dataease/kettle:v8.3-0318
Loaded image: registry.cn-qingdao.aliyuncs.com/dataease/mysql:5.7.43
[DATAEASE Log]: 启动服务 

[+] Running 4/4
 ⠿ Network dataease_dataease-network                                                                                                                    Created 0.1s               Creating 0.3s
 ⠿ Container kettle                                                                                                                                     Created 0.4s               Creating 0.3s
 ⠿ Container doris-fe                                                                                                                                   Created 0.4s
[+] Running 3/7sql                                                                                                                            ⠿ Network dataease_dataease-network                                                                                                                    Created 0.1simage's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was ⠿ Container kettle                                                                                                                                     Starting 0.5s                                                                                                                      ⠿ Container doris-fe                                                                                                                                   Starting 0.5s                                                                                                                     [+] Running 3/7sql                                                                                                                            ⠿ Network dataease_dataease-network                                                                                                                    Created 0.1simage's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was ⠿ Container kettle                                                                                                                                     Starting 0.6s         

我看了一眼docker,感觉是脚本下载了x86的mysql,但我是arm64. 怎么解决一下,谢谢.

**Comment by mfanoffice** [comment]
你需要下载arm 版的 DataEase 离线安装包。

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；

**Comment by libeiheng** [comment]
下载的就是arm64的.除了mysql都安装上了.就mysql不行.
