### ISSUE TITLE
[Feature] 允许一个配置全局视图配色方案的地方

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6299]
**请描述您的需求或者改进建议.**
允许一个配置全局视图配色方案的地方
![image](https://github.com/dataease/dataease/assets/45852479/09737d6b-a12a-4902-a962-2aa2e8e31b1c)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，建议在仪表板的样式中进行全局配色方案的配置。
