### ISSUE TITLE
[Feature]用户管理，高级搜索条件，提高易用性

### ISSUE THREAD

**Issue by chenxin2001** [dataease/dataease#63]
**请描述您的需求或者改进建议.**
用户状态只分为2种：启用和禁止
完全没必要在前面还再加 等于 和 不等于 的判断条件
![图片](https://user-images.githubusercontent.com/34565342/123535867-76cade80-d759-11eb-8422-f8d5b4bd35e8.png)

**Comment by yayanpei** [comment]
感谢您的反馈，您的建议是我们产品改进的方向

**Comment by xuwei-fit2cloud** [comment]
v1.1.1 版本已支持
