### ISSUE TITLE
[Feature] SQL 数据集参数相关问题

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6301]
**请描述您的需求或者改进建议.**
SQL 数据集参数相关问题：
1. 动态group by
2. left join 子查询参数报错

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，当前参数仅支持在where条件后添加，我们先调研一下。

**Comment by zhuang-maowei** [comment]
> 感谢您的反馈，当前参数仅支持在where条件后添加，我们先调研一下。

可参考开源的Davinci,他的SQL参数可以在任意地方。
咱们用了什么特殊的组件吗？
