### ISSUE TITLE
[Bug]组合图互相覆盖问题

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6304]
**DataEase 版本**

1.18.11
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
组合图 AntV EchartS 互相切换会出现覆盖问题，有概率出现，切换不稳定

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/89478384-be4a-41fe-b4c2-0f086b06f3d0)

2.
![image](https://github.com/dataease/dataease/assets/109720729/8c74dbf2-7035-46e1-94c2-53a1209a0c98)

3.

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本版本修复这个问题。
