### ISSUE TITLE
[Bug]仪表盘存储XSS漏洞

### ISSUE THREAD

**Issue by Mia0a-hi** [dataease/dataease#6305]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
docker

**浏览器版本**
chrome

**Bug 描述**
仪表盘存储XSS漏洞

**Bug 重现步骤(有截图更好)**
1.编辑仪表盘插入富文本
2.插入payload `<audio src=x onerror=confirm(x)>`
<img width="631" alt="3a4b30569b824ce028daaba0e466950" src="https://github.com/dataease/dataease/assets/40627909/02671984-931f-4f30-b98f-866d2e5e9334">
![20231020153950](https://github.com/dataease/dataease/assets/40627909/22327552-1dfd-4ae9-8dd3-d06793e3921d)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在后续版本修复这个问题。

**Comment by Mia0a-hi** [comment]
好像1.18.12版本没有修复

**Comment by Mia0a-hi** [comment]
> 感谢您的反馈，我们将在后续版本修复这个问题。

好像1.18.12并未修复
