### ISSUE TITLE
[Bug]筛选组件在切换TAB时未生效

### ISSUE THREAD

**Issue by jsznb** [dataease/dataease#6307]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
docker

**浏览器版本**
chrome

**Bug 描述**
当含Tab组件时,筛选组件在切换TAB时筛选组件无法联动

**Bug 重现步骤(有截图更好)**
1. 需要含有两个数据表(有时一个表也可以),分别放在两个TAB中
2.一个筛选组件同时筛选两个表的相同字段
3.这个时候会有两种情况,当另一个Tab加载过之后筛选组件是可以覆盖两个TAB,若只加载过一个,筛选组件在当前TAB生效后,切换到另一个TAB,筛选组件失效,需要重新刷新筛选组件

**结论**
估计是当TAB第一次加载的时候并不会加载组件筛选字段
目前是可以通过筛选之前把每个TAB点一遍避开这个问题,还是希望能优化一下这个地方

**Comment by BBchicken-9527** [comment]
感谢反馈，目前已经收到来自其他小伙伴的这个问题，问题将会在下个版本修复；

**Comment by xuwei-fit2cloud** [comment]
v1.18.12版本已处理，请更新版本。
