### ISSUE TITLE
[Feature]地图视图显示比例支持调整

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#6320]
地图视图初始进去时，能否支持显示比例设置？ 以展示中国地图为例，目前因为展示全国地图，最下方岛屿展示占用的空间较多，造成上方地图显示位置较小（如图一所示）。目前使用场景多是查看内陆的省市为主，所以能否支持这个功能，展示时显示主要是内陆的地图？（如图二所示）
图一：
![image](https://github.com/dataease/dataease/assets/27687681/2f401b74-034f-4bad-ba45-8dc5976df72d)

图二：
![image](https://github.com/dataease/dataease/assets/27687681/eb0f53d5-8f59-4e07-8b83-a73e8f9dd681)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，当前暂时没有规划去调整，建议根据需要，对地图进行放大、缩小，从而方便查阅。
