### ISSUE TITLE
[Feature]公共链接打开仪表板右上角视图的数据下载按钮会被遮挡，建议返回上一级、下载按钮可移动

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#6321]
**请描述您的需求或者改进建议.**
公共链接打开仪表板右上角视图的数据下载按钮会被遮挡，建议返回上一级、下载按钮可移动
点击空白地方隐藏此按钮，再去下载，还是会默认展示并遮挡查看数据按钮、放大按钮，建议优化。
![image](https://github.com/dataease/dataease/assets/70566485/3e072fcd-67f1-4b33-a2d9-9b38e30f72a3)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。
