### ISSUE TITLE
[Bug]富文本视图插入表格宽度超过视图宽度

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6322]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
 安装包

**浏览器版本**
chrome

**Bug 描述**
 富文本视图，插入表格是，宽度总超出富文本视图，如下图：
<img width="512" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/ba302e64-bf74-4d87-8076-249a8215d819">
原因是，表格属性，宽度默认是 114%，改为 100% 后，表格宽度就正合适了，能不能默认改为 100%？
<img width="1109" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/1420513d-5531-4ccb-8a80-ea09f0cb32f6">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本对此处进行优化。

**Comment by xuwei-fit2cloud** [comment]
处理起来代价太大，暂时没有优化的计划。
