### ISSUE TITLE
[Bug]富文本视图添加表格，手动调整表格行高后使用数值设置行高会失效

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6323]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
 安装包运行

**浏览器版本**
 chrome

**Bug 描述**
富文本视图添加表格，手动调整表格行高后，再使用数值设置行高会失效
<img width="1456" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/e9c8fab0-3c60-4598-bced-99a20108b0fc">
<img width="1061" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/95edda53-2523-4ad1-b6bb-8cfa974c1c03">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，你需要设置一下范围的，毕竟表格和其他是一个整体不能单独针对某一个表格进行调整都是调整一行或者一列的；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
