### ISSUE TITLE
[Feature]建议图表的自动轴值增加功能，可以设定为一个字段

### ISSUE THREAD

**Issue by kkljcf** [dataease/dataease#6326]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/125198800/011b830c-c675-423b-aa09-97db1ee0d61e)
比如这个图，我的轴值是40，他是一个具体数值，是固定的，
建议能增加兼容为字段，

比如max(数值)这样类型的字段，字段从我的sql数据源里面读取。

建议原因是，轴值如果选择了自动，对称图两边比例就不对称了，用手动的话，比例相等，但是数值变化又不能及时变化对应比例

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们在后续版本支持一下。
