### ISSUE TITLE
[Feature] 过滤器支持对结果进行过滤

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#6330]
**请描述您的需求或者改进建议.**
目前的过滤器都是子查询中的where条件后，是对行进行过滤。
有的使用场景是需要对结果进行再过滤，希望过滤器可以支持对结果进行过滤。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，对结果的过滤我们已经加在需求中，近期暂时还没有规划进行支持。
