### ISSUE TITLE
[Bug]文本下拉框框中对过滤字段排序后数据不完整

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6333]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
 安装包

**浏览器版本**
 chrome

**Bug 描述**
文本下拉组件选择 “资源类型” 进行筛选，内容有 3 个；
<img width="941" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/47c5be40-6997-496d-afed-27fb9491d089">
对“资源类型”字段本身进行排序，则出现数据不完整情况
<img width="934" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/fcf66c1a-f201-459c-b6f0-bd7715fcf975">
<img width="936" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/5f24683f-6b04-4422-b807-e9aa7dceb36d">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本修复这个问题

**Comment by xuwei-fit2cloud** [comment]
由于下拉选项过多，我们对数据做了截断处理，暂时还解决不了此问题。
后期我们会加上对过滤组件的过滤条件支持，可以缓解此问题的出现。
