### ISSUE TITLE
[Feature]视图的日期显示希望增加“月日”格式

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6345]
**请描述您的需求或者改进建议.**
下图中所示视图的日期显示，希望可以增加月日格式。
![图片](https://github.com/dataease/dataease/assets/48307752/7c592d24-ffb6-4221-ac6b-7c047fab9206)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入优化清单中，根据需求的优先级规划实现。
