### ISSUE TITLE
[Feature]文本下拉组件可以动态默认选择最新的一个

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#6351]
**请描述您的需求或者改进建议.**
文本下拉组件可以动态默认选择最新的一个，数据是动态的情况下

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，请问是根据数据集中的时间字段，来判定是否为最新吗？

**Comment by chetaofeng** [comment]
感谢回复。
期望文本下拉组件可以支持默认选择列表第一项，以支持下拉文本框数据是定期动态生成的场景。 这个下拉文本字段不一定是时间字段，可以是自己定义的字段逻辑（如：订单号2023102500001XXABC 这种），按照字符串的ASCII比较排序，支持正序、倒序设置，设置之后排序的列表第一项（如果有的话）默认为选中状态并激活相应事件即可

**Comment by xuwei-fit2cloud** [comment]
我们在近期版本会支持。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
