### ISSUE TITLE
[Bug] 数据集与模版市场中模版的维度/指标不匹配时数据无法正常显示

### ISSUE THREAD

**Issue by limin-fit2** [dataease/dataease#6353]
**DataEase 版本**

v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 118.0.5993.70（正式版本） (arm64)

**Bug 描述**
在模版市场中复用新模版，替换图表数据，当新数据字段与图表字段名称不一致，则显示无法加载数据

**Bug 重现步骤(有截图更好)**
1.复用模版市场模版，编辑视图图表，替换数据集
![image](https://github.com/dataease/dataease/assets/61964761/a44f856a-7d77-4ca8-b691-7e053c119e37)
2.原视图组件指标名称为数量，替换新数据集之后，指标名称为销售额，则提示无法加载数据
![image](https://github.com/dataease/dataease/assets/61964761/5e901a72-1d2d-4659-a4a7-c389d5eadc28)
3.修改数据集指标名称，则数据正常显示
![image](https://github.com/dataease/dataease/assets/61964761/14920223-f53a-4dab-97f9-cce43499f96e)

**Comment by BBchicken-9527** [comment]
感谢反馈，由于你现在选中这个模版的富文本视图，需要将字段进行替换才可以显示的；
![image](https://github.com/dataease/dataease/assets/84372766/ae2932f0-a0cd-439c-88e5-55f28a36ca31)
