### ISSUE TITLE
[Bug]过滤组件文本下拉组件，搜索栏展示数据不全

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#6355]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
过滤组件文本下拉组件，搜索栏展示数据不全
实际上数据有7条，文本搜索组件可以查询7条，但是文本下拉搜索只有三条。
联系，可以提供数据集

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/70566485/4c56c16e-b345-41cc-86c3-1865051b366c)

**Comment by BBchicken-9527** [comment]
感谢反馈，需要和你确定一下你使用的数据源和创建数据集的时候是直连还是定时同步；

**Comment by xiebei-l** [comment]
> 感谢反馈，需要和你确定一下你使用的数据源和创建数据集的时候是直连还是定时同步；

Excel数据集

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
