### ISSUE TITLE
[Bug]Echarts的地图视图组件，当选择结果展示不是全部时，视图出现空指针异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#6356]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/89771514/022a7470-79af-4e18-858f-b78cacca4ece)
![image](https://github.com/dataease/dataease/assets/89771514/dbccef9d-27e0-4c12-8229-2939f5672d42)

![image](https://github.com/dataease/dataease/assets/89771514/d736e69e-d7c3-4e74-975f-58b1560d3e69)
跟踪代码发现，查询维度、指标做了一次查询，查询维度和经纬度又做了一次查询，当使用精简模式部署时，查询的是mysql数据库，两次查询的SQL，一次根据维度做了group by，另一次没有做group by，导致两次查询的数据不一致，这个我尝试修 MysqlQueryProvider倒是可以解决。但是考虑到如果是定时同步的数据集，数据是无序的，不确定是否可以通过修改DorisQueryProvider进行处理？

这里是否可以修改处理逻辑，合并为一次查询呢

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复

**Comment by xuwei-fit2cloud** [comment]
v1.18.12版本已处理，请更新版本。
