### ISSUE TITLE
[Feature]文本类型下钻后排序失效或无法排序

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#6357]
**请描述您的需求或者改进建议.**
<img width="557" alt="image" src="https://github.com/dataease/dataease/assets/101089844/070feb4a-0027-4cc5-95eb-ad5c3199b8e9">
时间、数值都是随着维度排序的，下钻后也是随着维度排序，文本类型下钻后，无法进行排序了

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们尝试一下。
