### ISSUE TITLE
[Bug]直连presto数据源使用时间过滤组件报错

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#6359]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
在线安装

**Bug 描述**
直连presto数据源使用时间过滤组件报错

**Bug 重现步骤(有截图更好)**
1.
<img width="789" alt="wecom-temp-49811-aff944201d9859f86c1002544c369ed2" src="https://github.com/dataease/dataease/assets/101089844/fec051b8-041a-43d5-bda4-76bf2c6c9dac">

2.
<img width="872" alt="wecom-temp-46943-bcde7a4f9874b1e4016203c391190f6c" src="https://github.com/dataease/dataease/assets/101089844/3e623af2-2b9e-41dc-bdff-7a82f73b0640">

3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们排查一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
