### ISSUE TITLE
[Question] 公共链接访问404

### ISSUE THREAD

**Issue by zerotocode398** [dataease/dataease#6367]
**请描述您的问题.**
dataease version: v1.18.11
Browser version: Chrome 118.0.5993.89

源码安装，参考文档：https://dataease.io/docs/dev_manual/dev_deployment/compile/

仪表盘创建公共链接密码访问，访问404

![d1](https://github.com/dataease/dataease/assets/31309558/5a40de46-a18a-4dc5-887f-e9090b023d0d)
![d2](https://github.com/dataease/dataease/assets/31309558/752692cd-098c-4471-baa1-0d6b05c53d1f)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议使用标准的安装包部署，或者等下个版本发布（V1.18.12版本对访问路径的设置进行了优化）。

**Comment by gitfortian** [comment]
1.18.12我测试了 还是有这个问题
