### ISSUE TITLE
[Bug]仪表板公共链接也会因为 8 小时登录超时而提示退出登录

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6373]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
 chrome

**Bug 描述**
DataEase 默认 8 小时退出登录，仪表板的公共链接也会因为 8 小时登录超时而提示退出登录；
有没有办法不影响公共链接？
<img width="1412" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/792553d9-9e9e-4837-b1e1-3d97a4bf6fb2">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
