### ISSUE TITLE
[Feature]时间数据有点小问题

### ISSUE THREAD

**Issue by kkljcf** [dataease/dataease#6374]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/125198800/b2acd687-6d45-4fe3-a290-6355a46e87ed)
![image](https://github.com/dataease/dataease/assets/125198800/d97b68c2-1cbc-4408-a2cb-150dc49bd997)
SQL server查询数据源调好了时间格式的，到了data不知道为何结尾多了个.0
交流群也没有能说明白

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请问数据集是直连还是定时缓存模式？

**Comment by kkljcf** [comment]
> 感谢您的反馈，请问数据集是直连还是定时缓存模式？
直连模式的
