### ISSUE TITLE
[Bug]【数据集】SQL 数据集的参数和【not exists】用法有冲突

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#6383]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
SQL 数据集的参数和【not exists】用法有冲突 。

**Bug 重现步骤(有截图更好)**
1.BUG 截图：
![image](https://github.com/dataease/dataease/assets/24768910/889256ae-4e16-4c1d-be01-51f675ea3357)

2.不带参数执行情况：
![image](https://github.com/dataease/dataease/assets/24768910/e4524fa2-62a8-47fc-8d94-bd60682eb24e)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前exists函数方式暂时无法支持参数化设置，功能我们会在后续逐步完善，对你的使用带来困扰非常抱歉；
