### ISSUE TITLE
[Feature]【数据集】postgresql 支持时间格式转化

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#6384]
**请描述您的需求或者改进建议.**
postgresql 支持时间格式转化。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录并调研一下。

**Comment by AndroidBaby1** [comment]
![image](https://github.com/dataease/dataease/assets/24768910/a018e4e0-d7c7-4b6b-918c-9a2c7b6d66da)
是【数据集】，不好意思，这一块在内容里没有表述清楚。
