### ISSUE TITLE
[Bug]API数据源，填写时数据源有效，保存后数据源显示无效

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#6386]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
<img width="725" alt="image" src="https://github.com/dataease/dataease/assets/89771514/e676e60e-db30-49a4-a385-d3c307a4091b">

![image](https://github.com/dataease/dataease/assets/89771514/faac4895-98a7-4281-9fb3-55ba442e572b)

排查发现是因为接口返回的数据中，字段中包含特殊字符‘.’，导致解析的时候抛出异常
![image](https://github.com/dataease/dataease/assets/89771514/1b395ae7-d9b9-4727-8f84-7fcc72a0ca78)

JsonPath.read(result, "$.['data'].['data'].['table'].['columns'].t_product_position_information.bond_type3[*].['value']")

接口示例：
https://console-docs.apipost.cn/preview/13e2749b08972e19/45905309b8f7740e?target_id=0d9678e9-0a03-4b08-9121-d4b783303d6d

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将会在后续版本进行修复；
