### ISSUE TITLE
[Bug]浏览器窗口变化时，会自动刷新数据，参数为空

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#6387]
**DataEase 版本**

v1.18.11
**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**
谷歌浏览器117.0.5938.134（正式版本） （64 位）

**Bug 描述**
浏览器窗口发生变化时，会自动刷新数据，并且查询数据的请求里面时没有任何过滤条件的。

**Bug 重现步骤(有截图更好)**
1.百分百复现，必须要有查询按钮，如果复现不出来，可以先建一个demo仪表板，再刷新浏览器后直接去查看这个仪表板，如下图
![image](https://github.com/dataease/dataease/assets/26103277/aa759e43-560c-4a53-859a-ee41985dfb28)
2.点浏览器右上角的窗口化按钮或其他方式改变浏览器窗口大小后，发现数据会刷新，刷新数据如下图：
![image](https://github.com/dataease/dataease/assets/26103277/f0d11be5-76fb-49e2-a364-69134897bfb5)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行优化；
