### ISSUE TITLE
[Feature]数据源分配权限缺失全部或者文件夹维度，数据源多的时候分配权限非常不便

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#6388]
**请描述您的需求或者改进建议.**
数据源分配权限缺失全部或者文件夹维度，数据源多的时候分配权限非常不便，需要一个个勾选，耗时很久。
建议增加全部勾选选项，增加文件夹维度。
<img width="977" alt="image" src="https://github.com/dataease/dataease/assets/70566485/135debba-6186-4986-a522-9bb26a2395f1">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，数据源这里文件夹的添加1.x暂时没有规划，如果数据源较多，建议将数据源的权限分配给一个角色，其他用户添加上该角色。
