### ISSUE TITLE
[Bug]缓存问题导致的输入错误

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6395]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
在谷歌浏览器正常模式下，按 S 键会保存，D 键会复制，B 键会回撤操作，在无痕模式下可以，是不是缓存管理的问题

**Bug 重现步骤(有截图更好)**
1.
<img width="1435" alt="image" src="https://github.com/dataease/dataease/assets/109720729/d303c596-5b68-4f14-ac1b-6e54d0d4751d">

<img width="1430" alt="image" src="https://github.com/dataease/dataease/assets/109720729/49450420-995e-4c3c-b752-3c1df06b2463">

2.
3.

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在后续版本修复这个问题。

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在后续版本修复这个问题。

**Comment by BBchicken-9527** [comment]
目前已对此处进行了优化，可以下载新版本体验；
