### ISSUE TITLE
[Feature] 定时同步任务结构添加更详细的信息

### ISSUE THREAD

**Issue by DogeVenci** [dataease/dataease#6396]
增量更新 执行记录结果希望能增加 查看更新了多少行等更加详细的信息 不然只显示成功和失败 但是有些数据仍然有遗漏可能

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
目前我们1.x版本还无法做到这个支持。
2.x版本我们可以支持。
