### ISSUE TITLE
[Bug]FireFox浏览器，在视图页面进行拖拽时会引发多余操作

### ISSUE THREAD

**Issue by chenxin2001** [dataease/dataease#64]
**DataEase 版本**
 v1.0.0-rc2

**浏览器版本**
 FireFox 89.0.2 (64 位)

**Bug 描述**
FireFox浏览器，在视图页面进行拖拽时会引发多余操作

**Bug 重现步骤(有截图更好)**
1. 新增视图
2. 拖拽左侧 维度 和 指标 时，会引发浏览器自动搜索该关键字
![图片](https://user-images.githubusercontent.com/34565342/123535942-040e3300-d75a-11eb-8140-bcf6fb339cd3.png)

**Comment by XiaJunjie2020** [comment]
FireFox 浏览器设置导致。
解决方法: 菜单->扩展与主题->启用拖拽手势 去掉勾选
