### ISSUE TITLE
[Bug]组合图的数值格式副轴指标格式不生效

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#6404]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
组合图的数值格式只有第一个指标是生效的，第二个无论怎么设置都不生效。

**Bug 重现步骤(有截图更好)**
1.为指标一设置数值格式，后缀增加百分号，是可以生效的。
![image](https://github.com/dataease/dataease/assets/48945409/a0072d3b-f5a8-49b9-9a52-41c9a843d8da)
![image](https://github.com/dataease/dataease/assets/48945409/309155b1-814f-4e75-b4c2-12cf353255cc)

2.为第二个指标（副轴指标）设置数值格式，不生效。
![image](https://github.com/dataease/dataease/assets/48945409/cd4bf4c3-7b02-4172-99e2-682d779018b0)
![image](https://github.com/dataease/dataease/assets/48945409/09ec47e2-ab36-4714-ac94-34a57b5981ec)

再次尝试：
![image](https://github.com/dataease/dataease/assets/48945409/c2f2fbff-769b-4866-98ef-f35a7d1b9440)
![image](https://github.com/dataease/dataease/assets/48945409/6ddb1078-c188-44ce-93ee-476a64579c1b)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，你目前使用的环境依然可以复现嘛？
![image](https://github.com/dataease/dataease/assets/84372766/b729ddf1-aced-492a-a9e5-d6af8236ff8c)

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
