### ISSUE TITLE
[Feature]增加箱线图

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#6405]
**请描述您的需求或者改进建议.**
主要可以看同一类型下数据的离散情况 以及一些异常值，如果他可以跟其他图形做组合图就更好了
![image](https://github.com/dataease/dataease/assets/101089844/8309647e-52bf-4910-8e14-826021a4dc8f)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经加入2.x的需求池中。
