### ISSUE TITLE
[Bug]修改视图标题后，将视图导出为Excel时，导出的文件名称还是初始标题名

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#6406]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**Bug 描述**
修改视图标题后，将视图导出为Excel时，导出的文件名称还是初始标题名

**Bug 重现步骤(有截图更好)**
1.原始标题名称
![image](https://github.com/dataease/dataease/assets/101089844/f0323c2f-3cdf-4206-876f-18399518e735)

2.修改标题后，再到处Excel文件还是原始的标题名
![image](https://github.com/dataease/dataease/assets/101089844/7abf9242-0253-4736-a772-92edf2911185)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将会在下个版本进行优化；

**Comment by xuwei-fit2cloud** [comment]
v1.18.12版本已处理，请升级到最新版本。
