### ISSUE TITLE
[Feature]可以将过滤组件设置为必选项

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#6409]
**请描述您的需求或者改进建议.**
可以将过滤组件设置为必选项，这样就不用无选项的时候查询全部数据了

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，您的建议我们已收到，已加入版本迭代中。

**Comment by xiaorsly88** [comment]
建议不仅仅是时间组件，其它组件也能实现同样效果。 条件必填控制针对整个仪表盘，或单个视图（如果可以）。
应用场景如下：
1、 针对一些大数据量的表格查询时比较有效，因为大多数情况下，默认条件查询不是用户第一次想看到的数据，用户一般会调整条件在次查询，所以可以通过控制必输条件来减少一次查询交互。 
2、另外，还有一些场景，只能查询特定的极少量的记录，比如一些安全要求比较高的数据查询，因此增加条件的必输控制，没有输入条件不能查询
