### ISSUE TITLE
[Feature] 請協助提供離線安裝檔

### ISSUE THREAD

**Issue by l29461970** [dataease/dataease#6410]
無中國地區手機號碼，無法下載，請提供安裝檔，謝謝

**Comment by l29461970** [comment]
我能提供電子郵件，可以提供後請您們寄給我嗎?
謝謝

**Comment by yayanpei-fit2cloud** [comment]
感谢您的关注和支持，您可以在评论区留下邮箱，在本周四（11月2日）发布版本V1.18.12后，会将最新版本的下载地址发送至您的邮箱。

**Comment by l29461970** [comment]
> 感谢您的关注和支持，您可以在评论区留下邮箱，在本周四（11月2日）发布版本V1.18.12后，会将最新版本的下载地址发送至您的邮箱。
-->l2946197076@gmail.com
可以先给我V1.18.11的安装檔，后续再给我V1.18.12的安装檔吗?
谢谢啊！

**Comment by yayanpei-fit2cloud** [comment]
V1.18.11版本的下载地址已经发送至您的邮箱，请注意查收。

**Comment by l29461970** [comment]
> V1.18.11版本的下载地址已经发送至您的邮箱，请注意查收。
已收到V1.18.11离线安装包，谢谢！
