### ISSUE TITLE
[Bug]AntV组合图，点击维度字段设置排序，自定义排序无响应

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#6411]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
AntV组合图，点击维度字段设置排序，自定义排序无响应
![image](https://github.com/dataease/dataease/assets/89771514/641dc931-25d6-41df-a0d1-c818cee5bf0f)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
v1.18.12版本已处理，请升级到最新版本。
