### ISSUE TITLE
[Bug]移动端中无法调整图片组件到合适大小

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#6418]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 117.0.5938.92

**Bug 描述**
移动端中无法调整图片组件到合适大小，调整到一定大小后就无法继续调整组件的最小长/宽限制。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/40846859/58fcafb1-2f9f-467b-93f7-b3049e12a23c)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是当组件达到最小的状态的时候无法再调整组件的大小吗？

**Comment by xusongtao** [comment]
是的，希望能进一步调小组件的大小

**Comment by BBchicken-9527** [comment]
感谢反馈，目前选区大小是固定的，并且暂时不支持这种小组件的形式使用；
