### ISSUE TITLE
[Bug] 日期范围组件过滤定时同步数据集，结果集数据筛选不正确

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#6423]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 118.0.5993.117（正式版本） (arm64)

**Bug 描述**
定时同步模式数据集制作的视图，在使用日期范围组件进行数据过滤时，日期范围左侧的数据错误的被过滤了。

**Bug 重现步骤(有截图更好)**
1. 定时同步数据集如下所示：
![image](https://github.com/dataease/dataease/assets/30063018/210d1b20-ac06-44f9-ae3d-d14f5f5bde59)
![image](https://github.com/dataease/dataease/assets/30063018/96cbec3c-52f0-4aa0-aec5-8ac46bbedbef)

2. 使用数据集创建视图，并新增日期范围组件绑定 statistic_month 字段
![image](https://github.com/dataease/dataease/assets/30063018/dc1c1499-a6d4-4ff1-9945-f7b86c7841aa)

3.选择筛选范围为 2021-01-31 ～ 2021-02-28
![image](https://github.com/dataease/dataease/assets/30063018/95acc822-7991-488b-82d5-885373e6f532)

4. 发现 2021-01-31 日的数据并未成功被筛选出来。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有复现你说的问题，请问你使用的数据库和字段类型是什么呢？

**Comment by xuwei-fit2cloud** [comment]
v1.18.12版本已处理，请升级到最新版本。
