### ISSUE TITLE
[Bug] excel导出设置数值格式所见即所得

### ISSUE THREAD

**Issue by zhanglubao** [dataease/dataease#6428]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

**Bug 描述**

将指标设置了数值格式，进行数据导出，希望可以带上数值格式。实际未带

![image](https://github.com/dataease/dataease/assets/67628857/837a6068-cab1-492f-a6c8-ce3beeee21d6)

![image](https://github.com/dataease/dataease/assets/67628857/f798f0e8-c2de-4ca8-8a04-634c536b0593)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前导出数据内容是与数据明细是一致的。暂时还不支持你说的这种用法，你的需求我这边已经进行了记录，请耐心等候；

**Comment by xuwei-fit2cloud** [comment]
暂时还没有支持计划。
