### ISSUE TITLE
[Bug] 公共链接分享时，其他用户登陆查看时打开页面报“没有权限查看，请联系管理员”

### ISSUE THREAD

**Issue by blooze123** [dataease/dataease#6442]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
离线安装

**浏览器版本**
chrome最新版

**Bug 描述**
用户A创建了一个仪表板大屏，用户B权限设置没有授权这个大屏的查看权限。此时用户A创建公共链接，将链接给到用户B后，用户B打开时，大屏内容会报错“没有权限查看，请联系管理员”。只有在权限设置中，授权查看或以上的权限，用户B才能看到大屏。

正常的结果应是公共链接分享给用户B，用户B能正常以用户A的权限看到这个大屏。
报错截图如下：
![image](https://github.com/dataease/dataease/assets/47737772/58442057-6c16-491e-8b5f-9d347ec28639)

**Comment by BBchicken-9527** [comment]
感谢反馈，公共分享需要当前使用的浏览器下不存在平台的token的，因为公共分享链接是给链接的使用者赋予创建链接用户的临时权限，如果这个时候token已经存在则不会进行替换，这也就是为什么当浏览器中存在用户B则提示没有权限的原因；

**Comment by blooze123** [comment]
拿这种场景不能实现吗，或者后续有考虑支持优化这个点吗
