### ISSUE TITLE
[Feature] 数据集预览添加默认条件

### ISSUE THREAD

**Issue by Domi-Zhang** [dataease/dataease#6443]
如果数据库数据集底层的是列式数据库，且列数量达到数百个之多的时候，默认的“”SELECT * FROM LIMIT 1000“”的预览SQL语句会导致预览页面加载非常缓慢，且底层数据库资源会被无故消耗。
是否可以考虑在“显示1000行”按钮旁增加“默认查询SQL”的配置？

**Comment by xuwei-fit2cloud** [comment]
如果增加默认查询SQL配置项的话，其实和SQL数据集就重复了。
建议在数据库数据集里的字段管理中，仅选择需要的列来显示。
