### ISSUE TITLE
[Bug]文本搜索组件无法输入英文的逗号 ----> ,

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#6453]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌最新版本

**Bug 描述**
文本搜索组件无法输入英文格式的逗号 ----> , 
其他符号都可以输入唯独英文的逗号不行

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
![image](https://github.com/dataease/dataease/assets/84372766/47830925-799b-4897-b9c1-582efd20687f)
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。

**Comment by hw872715125** [comment]
需要在编辑文本搜索组件的弹框里面，在输入框设置默认值时，无法输入英文的逗号
![image](https://github.com/dataease/dataease/assets/26103277/4a2a81c6-bbdd-4263-a5da-b5efd050e035)

**Comment by BBchicken-9527** [comment]
感谢反馈，在过滤组建中半角分的逗号是平台系统分隔符，所以在默认参数处作了限制的；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
