### ISSUE TITLE
[Bug]AntV 动态辅助线平均值存在多个小数位的问题，Echarts默认会保留两位

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#6460]
**DataEase 版本**
v1.18.11 

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 118.0.5993.118（正式版本） （64 位）

**Bug 描述**
AntV 动态辅助线平均值存在多个小数位的问题，Echarts默认会保留两位

**Bug 重现步骤(有截图更好)**
1.
![f4bea8d9b74b4991f10ffa3845b8246](https://github.com/dataease/dataease/assets/43403764/1f48fdab-9c4c-4b22-b6d8-426f9b3493a7)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
