### ISSUE TITLE
[Bug]SQL数据集，数据预览时，若字段名称中含有特殊字符点“.”时，数据就会显示为空

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#6484]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
前端显示异常，实际是有数据的
![image](https://github.com/dataease/dataease/assets/89771514/a3581463-c568-47ae-b6da-71f7de821a65)

**Comment by BBchicken-9527** [comment]
感谢反馈，已经合到了环境中，验证后将会在下个版本上线，感谢你的支持；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
