### ISSUE TITLE
[Bug]视图编辑完成，点击“保存”，没有任何提示保存成功的信息

### ISSUE THREAD

**Issue by chenxin2001** [dataease/dataease#65]
**DataEase 版本**
 v1.0.0-rc2

**浏览器版本**
 FireFox 89.0.2 (64 位)

**Bug 描述**
视图编辑完成，点击“保存”，没有任何提示保存成功的信息

**Bug 重现步骤(有截图更好)**
1.新增视图
2.编辑视图完成后，点击右上角“保存”按钮，没有任何提示，但实际已经保存成功
![图片](https://user-images.githubusercontent.com/34565342/123535994-52233680-d75a-11eb-8ebb-6f6e80df1663.png)

**Comment by xuwei-fit2cloud** [comment]
视图是实时保存的，我们会加入保存成功提示。
