### ISSUE TITLE
[Bug] Mongo数据源，无法对日期维度排序

### ISSUE THREAD

**Issue by zhuang-maowei** [dataease/dataease#6506]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 107.0

**Bug 描述**
Mongo数据源，无法对日期维度排序
尚不清楚其他数据源是否也有此现象

**Bug 重现步骤(有截图更好)**
1.仪表板中选择基础折线图
2.维度拖入日期类型维度
3.设置日期显示升序
4.系统报错 Field is not a valid field based on tables in the query

**Comment by BBchicken-9527** [comment]
感谢反馈，因为mongodb受到自身的driver限制部分功能无法生效，建议使用mongodb-bi；
