### ISSUE TITLE
[Bug]Mongo数据源，无法对日期维度聚合

### ISSUE THREAD

**Issue by zhuang-maowei** [dataease/dataease#6507]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 107.0

**Bug 描述**
Mongo数据源，无法对日期维度聚合
尚不清楚其他数据源是否也有此现象
**Bug 重现步骤(有截图更好)**
1.仪表板中选择基础折线图
2.维度拖入日期类型维度，拖入指标统计
3.维度下拉选项，日期显示中选择，年月日
4.图表未按照日期维度聚合统计显示，仍然显示原数据

**Comment by BBchicken-9527** [comment]
感谢反馈，因为mongodb受到自身的driver限制部分功能无法生效，建议使用mongodb-bi；
