### ISSUE TITLE
[Feature]设置跳转打开方式为当前页面增加回退

### ISSUE THREAD

**Issue by zhuang-maowei** [dataease/dataease#6517]
在设置图表跳转联动时，当设置打开方式为当前页面时，跳转后无法返回。
请增加回退的功能。

另外，希望增加打开方式为弹出层的选项，并可对弹出层的大小进行设置，这样用户交互会更好。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，我们暂时还无法支持。
