### ISSUE TITLE
[Feature]表格阈值设定多个条件可以选择与或关系运算

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6519]
**请描述您的需求或者改进建议.**
如下图，两个条件，默认是 或关系，希望增加可选 “与”、“或”。
<img width="1239" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/c3b7cfa2-7654-4e05-a050-7824d16ec63e">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们已加入需求池，等待排期。
