### ISSUE TITLE
[Bug]符号地图背景色设置无效

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#6520]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运动

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/89771514/5507c3a1-0ca5-45ae-bcef-aa62615e20dd)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。
