### ISSUE TITLE
[Bug]v2.0 设置图表标签样式不生效

### ISSUE THREAD

**Issue by fants** [dataease/dataease#6521]
**DataEase 版本**
v2.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome118.0.5993.117

**Bug 描述**
柱状图控件，复制，更换取值字段后，再设置标签颜色会一直不起作用

**Bug 重现步骤(有截图更好)**
![1698979984725](https://github.com/dataease/dataease/assets/2188977/71b986ed-e06c-4f0e-94b1-424ec8aefe58)

**Comment by fants** [comment]
不仅复制，手动新建两个横向柱状图图表，设置第一个的标签颜色是有效的，设置第二个的就不生效了。

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。

**Comment by fants** [comment]
> 你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。

又测试了下，我这个取值字段是一个计算字段，这个图表的“值轴 / 指标” 如果选这个计算字段，设置标签样式就是无效的。其他非计算字段，可以正常设置标签样式。

浏览器的Console没有任何错误信息。

![WX20231103-150024](https://github.com/dataease/dataease/assets/2188977/fb58b3dc-04ba-402d-9278-2f80ffcfbedc)

新建计算字段`Test` , 选为值指标，设置标签样式无效，其他非计算字段，正常

![WX20231103-151342](https://github.com/dataease/dataease/assets/2188977/bb7effd9-fc32-4771-b979-de43d412efc2)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。
