### ISSUE TITLE
[Bug]透视表中使用计算字段算出的百分比，总计项中仅简单求和

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#6522]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome 118.0.5993.118

**Bug 描述**
透视表中使用计算字段算出的百分比，总计项中仅简单求和

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/40846859/492b8797-37c8-465b-98ad-f8cc27240f7e)

2.
![image](https://github.com/dataease/dataease/assets/40846859/01777b8a-1830-48b1-9246-aad32fdf03f9)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，由于透视表总计是AntV图库运算产生结果，目前没有调整的可能，所以暂时无法支持，后续如果有比较好的解决方案我们会统一进行处理；
