### ISSUE TITLE
新增指标的数字动态刷新效果，实现数字在刷新的时候滚动翻转

### ISSUE THREAD

**Issue by leosayy** [dataease/dataease#6525]
期望效果：

![image](https://github.com/dataease/dataease/assets/76548090/2e0677b4-52de-43e9-a998-279511a03276)
数字

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先调研一下是否有合适的图库。

**Comment by maninhill** [comment]
6个月内无更新，关闭。
