### ISSUE TITLE
[Bug] DataEase 2.0 帮助文档跳转错误，跳转至V1在线手册。

### ISSUE THREAD

**Issue by sky84892070** [dataease/dataease#6526]
**DataEase 版本**
DataEase 2.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 119.0.6045.106

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1. 登录Dataease 2.0 系统
2. 点击右上角方 帮助文档

期望结果：打开 V2 帮助文档 https://dataease.io/docs/v2/
实际结果：打开 V1 帮助文档 https://dataease.io/docs/v1/

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们在下个版本修复。
