### ISSUE TITLE
[Bug]仪表板全屏预览时地图的联动与下钻按钮间距位置较远

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#6527]
**DataEase 版本**
v1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
仪表板全屏预览时地图的联动与下钻按钮间距地图的位置变远。

**Bug 重现步骤(有截图更好)**
1.点击仪表板的【全屏预览】；
![image](https://github.com/dataease/dataease/assets/48945409/b5aa05ea-b805-4315-8348-49dd4330a03b)

2.点击地图，唤出联动与跳转的按钮，如下图所示，距离较大。
![image](https://github.com/dataease/dataease/assets/48945409/a25bad79-b1e6-4c36-8c22-ef106dad0930)

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。
![image](https://github.com/dataease/dataease/assets/84372766/99a803bd-e453-4911-a3f7-e6cf8fc82b06)

**Comment by LuKK351** [comment]
https://github.com/dataease/dataease/assets/48945409/a427d7c0-56df-4277-91c4-f8ba6f0c3426

**Comment by BBchicken-9527** [comment]
感谢反馈，根据你的说明是在类似带鱼屏的情况下才会出现，我们想办法验证一下；

**Comment by BBchicken-9527** [comment]
感谢反馈，根据你的说明是在类似带鱼屏的情况下才会出现，我们想办法验证一下；
