### ISSUE TITLE
[Bug] EChart 视图集-横向柱状图， 排序的升序、降序搞反了

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [dataease/dataease#6528]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌浏览器

**Bug 描述**
EChart 视图集。横向柱状图，配置升序、降序，显示反了。

以下是目前的显示效果
升序：
<img width="1050" alt="image" src="https://github.com/dataease/dataease/assets/30264974/be9b7ec1-ca09-4f19-b8c2-d2dddebbc6e1">
降序：
<img width="1036" alt="image" src="https://github.com/dataease/dataease/assets/30264974/af1645e1-e8b8-4a93-a5c0-a3f4a13b486a">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前echarts图库自身去进行升序和降序的排序的，我们优化一下；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
