### ISSUE TITLE
[Bug]数据源无效: Unknown system variable ‘transaction_isolation’

### ISSUE THREAD

**Issue by haitanghuadeng** [dataease/dataease#6529]
**DataEase 版本**
DataEase版本是v1.18.11，mariaDB版本是11.0.1。

**运行方式(安装包运行 or 源码运行 ?)**
shell部署

**浏览器版本**
Eadg版本 119.0.2151.42 (正式版本) stable应用，beta频道 (64 位)

**Bug 描述**
dataease在添加mariadb数据源并进行校验的时候，遇到了数据源无效: Unknown system variable 'transaction_isolation’的问题。

**Comment by haitanghuadeng** [comment]
补充一下，这个问题在DataEase的v1和v2中都存在。

**Comment by xuwei-fit2cloud** [comment]
这应该是驱动版本的问题，1.18.x版本中是有驱动管理的，可以自己添加相应的驱动；v2版本中目前还没有加入驱动管理功能，暂时还不能处理此问题。
