### ISSUE TITLE
无法正常使用sqlserver

### ISSUE THREAD

**Issue by xnddxndd** [dataease/dataease#6530]
**DataEase 版本 v2.0 （但实际上1.x版本一样有问题）**

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
edge118 firefox118 chrome118

**Bug 描述**
登陆后，无法正常配置sqlserver数据源，一直无法获取Schema， 请选择数据库 Schema 时：

提示：
The driver could not establish a secure connection to SQL Server by using Secure Sockets Layer (SSL) encryption. Error: "The server selected protocol version TLS10 is not accepted by client preferences [TLS13, TLS12]". ClientConnectionId:bccb8729-648b-4974-ac5d-48e48aececd0

**Bug 重现步骤(有截图更好)**
1.
2.
3.
![Uploading 222.jpg…]()

**Comment by BBchicken-9527** [comment]
感谢反馈，需要在连接字符串中添加这个：encrypt=true;trustServerCertificate=true

**Comment by xnddxndd** [comment]
> 感谢反馈，需要在连接字符串中添加这个：encrypt=true;trustServerCertificate=true
我试过了，还是一样的问题，并没有解决问题。

**Comment by xnddxndd** [comment]
截图给大家看吧：
![1212](https://github.com/dataease/dataease/assets/51181547/b9c360f2-7e60-4f3f-a0bd-42333bfa87a0)
