### ISSUE TITLE
[Feature]建议看板生成的公共连接，支持自定义

### ISSUE THREAD

**Issue by kkljcf** [dataease/dataease#6532]
**请描述您的需求或者改进建议.**
[Feature]建议看板生成的公共连接，支持自定义
当前是随机连接，便利性不够，
建议在当前随机的基础上，额外增加支持自定义连接自定义连接

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，公共链接目前是系统自动生成的，能够确保链接的安全性和唯一性，暂时没有计划支持自定义。

**Comment by kkljcf** [comment]
> 感谢您的反馈，公共链接目前是系统自动生成的，能够确保链接的安全性和唯一性，暂时没有计划支持自定义。

我就奇怪了，自定义个连接，怎么就变成有安全问题了，
唯一性解决的问题，
1、自定义保存时候，检查是否冲突，冲突则报错提示
2、不冲突的情况下，SQL不过是做个case判断，有无自定义的时候，明明就是一个很简单，而且很便捷的问题
