### ISSUE TITLE
[Bug] ECharts 条形图会刷新后会变成默认样式

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#6533]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
效果如视频所示，看起来是刷新后导致，但不知道触发机制是什么，出现概率较高。

https://github.com/dataease/dataease/assets/85436572/fbaf7296-babb-475b-aa2f-4111efe1110a

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我试了几次没发现你说的问题，我这边再看一下是否能复现；
