### ISSUE TITLE
[Bug]自定义SQL编辑页无法调节左侧侧边栏宽度

### ISSUE THREAD

**Issue by fants** [dataease/dataease#6535]
**DataEase 版本**
v2.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome最新

**Bug 描述**
在数据集编辑页面，新建“自定义SQL”，左侧的侧边栏宽度无法用鼠标拖动，鼠标拖动会变成拖动低栏高度

**Bug 重现步骤(有截图更好)**
![1699208945757](https://github.com/dataease/dataease/assets/2188977/dbd3475a-72d4-4e81-9344-095b61c59bed)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们在下个版本修复。
