### ISSUE TITLE
[Feature] 希望能增加一个隐藏组件

### ISSUE THREAD

**Issue by 12frame** [dataease/dataease#6539]
**请描述您的需求或者改进建议.**
有些场景下，针对指定的视图需要增加一个过滤条件，但又不希望展示给用户，类似前端的hidden属性。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议在制作视图时，为视图添加过滤器。
<img width="351" alt="image" src="https://github.com/dataease/dataease/assets/84168063/88349349-47c4-4f63-9085-f0b27c6ed97d">
