### ISSUE TITLE
[Question] DataEas-2.0源码本地跑数据库的配置不对，按照文档的配置数据库启动不了

### ISSUE THREAD

**Issue by mkcmgl** [dataease/dataease#6544]
**请描述您的问题.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请将报错信息发一下。

**Comment by mkcmgl** [comment]
2023-11-08T07:58:27.606657Z 0 [ERROR] [MY-011071] [Server] C:\phpstudy_pro\COM\..\Extensions\MySQL8.0.12\\bin\mysqld.exe: Error while setting value 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' to 'sql_mode'
2023-11-08T07:58:27.606736Z 0 [ERROR] [MY-010119] [Server] Aborting

2023-11-08T07:58:27.606791Z 0 [Note] [MY-010120] [Server] Binlog end

**Comment by mkcmgl** [comment]
> 感谢您的反馈，请将报错信息发一下。

![Upload

**Comment by mkcmgl** [comment]
> 感谢您的反馈，请将报错信息发一下。



> 感谢您的反馈，请将报错信息发一下。

**Comment by mkcmgl** [comment]
> 感谢您的反馈，请将报错信息发一下。

'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' to 'sql_mode'

**Comment by mkcmgl** [comment]
> 感谢您的反馈，请将报错信息发一下。

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-11-08 16:07:47,781 ERROR g.springframework.boot.SpringApplication: 856 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Schema `dataease` contains a failed migration to version 4 !

**Comment by mkcmgl** [comment]
删除sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
skip-name-resolve
这两个配置数据库能够启动，但是java后台还是报错
Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Schema `dataease` contains a failed migration to version 4 !
