### ISSUE TITLE
[Feature]建议在时间组件上增加必填选项

### ISSUE THREAD

**Issue by viphackl** [dataease/dataease#6546]
**请描述您的需求或者改进建议.**
目前问题就是一个正常的SQL里面使用SQL动态参数，如果使用的小伙伴人为的把时间传空会导致SQL动态参数解析为空，dataease默认使用`'BI'='BI'`进行动态参数占位，导致SQL扫表，时不时的拉爆mysql的CPU。

**强烈建议增加此选项**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，同issue https://github.com/dataease/dataease/issues/6409

该需求已经规划在最近的版本中进行实现，请关注一下后面版本的 release notes。
