### ISSUE TITLE
[Bug]Echart 地图读取 SQL Server 数据源的数据集为空值（全被判定空值）

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#6548]
**DataEase 版本**

1.18.12
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 118.0.5993.89（正式版本） （64 位）

**Bug 描述**
demo全国GDP数据导入SQL Server 2012、2022后，连接数据集没有问题，视图中明细表也可以展示，但是在地图中读取指标值和记录数为空值了，在地图高级设置中空值策略可以全部置为0

**Bug 重现步骤(有截图更好)**
![479d1089-338c-4013-8109-58d56ea4acdb](https://github.com/dataease/dataease/assets/127368807/134a4e51-a33e-4e82-a649-24ddf80ef7b3)

![041ca5881a746543fbeca7da4a8edf3](https://github.com/dataease/dataease/assets/127368807/807a0961-ce0a-47da-91e5-74dbfb95f51b)

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。
![image](https://github.com/dataease/dataease/assets/84372766/0986ea55-8c1b-423e-897d-eb76b3433ec0)

**Comment by greenyhsj** [comment]
数据源没有问题，创建地图没有问题没有报错，数据明细可以看到，不论是GDP还是记录数都被读取为null(空值策略可以辅助判断)
![image](https://github.com/dataease/dataease/assets/127368807/b30c2b19-7d2b-447b-8e42-dd9749d0adb5)
![image](https://github.com/dataease/dataease/assets/127368807/9c5cac35-282f-4f52-b0c3-40af3918f660)
![image](https://github.com/dataease/dataease/assets/127368807/cbf8d957-937b-49a8-ad38-aaaff849817e)
![image](https://github.com/dataease/dataease/assets/127368807/3fa6bde0-2b11-4b22-a275-23805b39f187)

**Comment by greenyhsj** [comment]
![chrome_8yjUyW8Oxf](https://github.com/dataease/dataease/assets/127368807/d33d426c-8446-4867-ba5f-de2246b6e49b)

**Comment by greenyhsj** [comment]
![30e1c72d642a6a44333c457ca25f608](https://github.com/dataease/dataease/assets/127368807/08dde298-d830-4440-b426-6c70ff7519e9)

**Comment by greenyhsj** [comment]
数据库导入时候生成的空字符问题
