### ISSUE TITLE
[Bug]连接 SQL Server 报错......TLS10 is not accepted by client preferences

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#6549]
**DataEase 版本**

2.0
**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**
版本 118.0.5993.89（正式版本） （64 位）

**Bug 描述**
连接 SQL Server 报错......TLS10 is not accepted by client preferences，2.0 的 jdk 是 17，1.18 是处理了这个tls的，2.0 没处理，需要处理一下 java 配置文件

**Bug 重现步骤(有截图更好)**
![bd60738d52aab0bf1cc7d1fcc16292f](https://github.com/dataease/dataease/assets/127368807/6230c2be-6744-4068-83f2-afadd0e94fbc)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在后续版本修复这个问题。
