### ISSUE TITLE
柱状图标签数据部分展示[Feature]

### ISSUE THREAD

**Issue by IversonJay** [dataease/dataease#6553]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/16457096/082d23ff-74b0-427d-a3e9-8e8305c85eeb)
柱状图，只想显示其中一个指标（比如达成率）的数据，但是选择显示标签功能后，所有的指标数据都显示，不能区分想重点展示的指标了。能否提供只展示某一指标的数据的功能？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该功能在1.x版本上暂没有计划进行支持，2.0版本中已经支持上，建议您使用2.0版本。
