### ISSUE TITLE
[Bug] 创建Mysql数据源,校验通过,但是无法保存

### ISSUE THREAD

**Issue by linjicong** [dataease/dataease#6555]
**DataEase 版本**
2.0.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge
版本 119.0.2151.44 (正式版本) (64 位)

**Bug 描述**
创建Mysql数据源,点击"校验"提示"校验成功",点击"保存"提示"Cannot invoke "java.sql.Connection.unwrap(java.lang.Class)" because "this.connection" is null"

**Bug 重现步骤(有截图更好)**
1.创建数据源
2.填写数据源配置,点击"校验"提示"校验成功"
3.点击"保存"提示"Cannot invoke "java.sql.Connection.unwrap(java.lang.Class)" because "this.connection" is null"

**Comment by BBchicken-9527** [comment]
感谢反馈，需要和你确认一下你使用的数据库版本是多少呢？

**Comment by linjicong** [comment]
> 感谢反馈，需要和你确认一下你使用的数据库版本是多少呢？
数据源的版本是5.7.20,8.0.22两个版本都试过无法添加.使用dataease 1.18.12版本可正常添加数据源

**Comment by BBchicken-9527** [comment]
> > 感谢反馈，需要和你确认一下你使用的数据库版本是多少呢？
> > 数据源的版本是5.7.20,8.0.22两个版本都试过无法添加.使用dataease 1.18.12版本可正常添加数据源

目前没有发现你说的这个问题。是不是jdbc连接时需要的参数没有添加呢？如果1.x的版本可以正常的话，你试试将1.x的jdbc链接字符串放到2.0中是否可以正常的链接呢？

**Comment by rick009** [comment]
我也出现了这个问题，就是按照文档进行安装的，添加数据源提示这个错误

<img width="718" alt="image" src="https://github.com/dataease/dataease/assets/888127/90bb1f5d-7ec2-4e57-88ec-35df9f67a3f3">

**Comment by BBchicken-9527** [comment]
> 我也出现了这个问题，就是按照文档进行安装的，添加数据源提示这个错误
> 
> <img alt="image" width="718" src="https://user-images.githubusercontent.com/888127/281367049-90bb1f5d-7ec2-4e57-88ec-35df9f67a3f3.png">
经过排查发现这里确实存在链接的问题导致无法创建数据源，目前已经修复，将会在后续的版本上线，给大家的使用体验带来不便实在不好意思；

**Comment by Dream-Ling** [comment]
现在是2023.11.18 下载最新的 还是一样的问题

**Comment by 1937lensen** [comment]
> 现在是2023.11.18 下载最新的 还是一样的问题

我用是2.1  连接的是sqlserver 依然存在这个问题  后面在op/apps/config/application.yml 找到问题  将datasource:
    url: jdbc:mysql://mysql-de:3306/dataease? 改为 datasource:
    url: jdbc:mysql://mysql-de:3306/dataease?autoReconnect=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true 即可
![51952119af1fcd9696b0aece588fe1ffed3fe9b6_2_690x92](https://github.com/dataease/dataease/assets/96633244/0bf7d14e-ba55-43e2-b680-c45b77cb914c)

**Comment by hystrix0779** [comment]
我用了2.3.0也报这个错，校验能通过，数据库版本是mysql:8.2.0 


<br class="Apple-interchange-newline">
<img width="1337" alt="image" src="https://github.com/dataease/dataease/assets/57122774/c0d8209d-dd52-4da9-93fc-140960e9b303">
