### ISSUE TITLE
[Bug]符号地图切换暗色主题不生效

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#6559]
**DataEase 版本**

v1.18.12
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

版本 118.0.5993.89（正式版本） （64 位）
**Bug 描述**

符号地图切换暗色主题不生效，只能显示亮色主题
**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/127368807/2109ac94-c37f-40ba-a20b-dc223a4507a7)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题并且已经修复，将会在下个版本上线；
