### ISSUE TITLE
[Bug]oracle数据库使用数据库数据集，保存数据集后没有数据。

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#6563]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
 Chrome 119.0.6045.105

**Bug 描述**
https://github.com/dataease/dataease/assets/104493699/fbb595b1-59fc-46da-ae6f-228e17edbf73

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，请问一下你用的oracle的版本是什么呢？

**Comment by shimengqiao** [comment]
oracle 11g，我这里可以提供环境

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
