### ISSUE TITLE
[Feature]时间过滤组件支持设置可查时间范围

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#6565]
**请描述您的需求或者改进建议.**
时间过滤组件支持设置可查时间范围，设置这个范围之后，用户仪表板界面上切换时只能在此范围进行数据查询，减少服务的压力以及控制可查询数据范围。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。
