### ISSUE TITLE
[Bug]【数据集】StarRocks SQL 数据集保存报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#6566]
**DataEase 版本**
2.0.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
StarRocks SQL 数据集保存报错

**Bug 重现步骤(有截图更好)**
1.在 StarRocks 创建表并导入数据；
[测试.sql.zip](https://github.com/dataease/dataease/files/13277561/sql.zip)

2.在连接工具中执行 SQL 如下所示：
2.1 SQL 示例：
select
 reg_date,
 reg_sys,
 reg_channel_id,
 reg_game_id,
 ad_type,
 tz_account_id,
 role_id
from
 tzbigdata_tzpingtaiold_dwd_role
where
 create_role_date <= DATE_ADD(CURDATE(), INTERVAL -2 DAY)
 and create_role_date = reg_date

2.2 执行截图：
![image](https://github.com/dataease/dataease/assets/24768910/bf54f725-164d-424c-8dd1-778a01c4e935)

3.在 DataEase 中创建 SQL 数据集并报错，报错如下：
![image](https://github.com/dataease/dataease/assets/24768910/01fbae65-9cc9-4079-b890-4314ecaef3af)

**Comment by BBchicken-9527** [comment]
感谢反馈，2.x统一了sql语法，相应的原函数是无法使用的，建议使用函数列表中的函数去执行；
