### ISSUE TITLE
[Bug]列权限脱敏规则设置后应该显示部分原数据实际显示 XX

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6567]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
 列权限设置脱敏规则，XXX***XXX 实际脱敏后显示XXX***XXX ，X 应该是数据，不应该是 X 字符；
还有“保留前 M 位，后 N 位“，实际显示的也是 X***X，X 应该是数据不应该是 X 字符。
![图片](https://github.com/dataease/dataease/assets/48307752/06a7c3a0-02ae-493a-a8c0-d31f77801541)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，请确认数据是否超出了限制的个数，超出个数则会直接显示限制规则；

**Comment by mfanoffice** [comment]
1. 保留前1位后1位，应该保留前1位后1位的数据，加密中间的字，不应该限制原数据的字数；
2. 即使在5个字以上的，使用保留前M后N规则脱敏后，也无法显示最后一个字。
![图片](https://github.com/dataease/dataease/assets/48307752/62a95d5d-d943-406b-aa3d-3a8f13df4175)
