### ISSUE TITLE
[Bug]【视图】富文本视图超链接无法在当前页打开

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#6576]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
富文本视图超链接无法在当前页打开

**Bug 重现步骤(有截图更好)**
1.富文本视图插入链接设置的是当前窗口
![image](https://github.com/dataease/dataease/assets/24768910/83e0597f-2dbe-450b-8993-d4fcf27d2038)

2.点击，却没有在当前页打开
![image](https://github.com/dataease/dataease/assets/24768910/d1b479b1-5c84-4bd5-913f-47ac413fe18f)
![image](https://github.com/dataease/dataease/assets/24768910/02745736-e528-4848-bf50-9448168a2415)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在后续版本修复这个问题。
