### ISSUE TITLE
[Bug] 产品文档https://dataease.io/docs/v1/customercase/ 处的页面布局有问题

### ISSUE THREAD

**Issue by Ray2310** [dataease/dataease#6577]
**Bug 描述**
系统：Ubuntu22.04
浏览器： Chrome

**Bug 重现步骤(有截图更好)**
1. 打开https://dataease.io/docs/v1/customercase/ 网址
2. 打开功能导航的功能手册 -> 数据源 
3. 往下翻会出现
![image](https://github.com/dataease/dataease/assets/109897266/8d874ca6-870e-423f-9294-6518672b3a80)

**Comment by greenyhsj** [comment]
![image](https://github.com/dataease/dataease/assets/127368807/3aed5af9-b26e-420c-8c3b-57f82f2b85f8)
没有复现

**Comment by Ray2310** [comment]
> ![image](https://user-images.githubusercontent.com/127368807/281242276-3aed5af9-b26e-420c-8c3b-57f82f2b85f8.png) 没有复现

抱歉， 我第二次也没有复现到 ，但是第一次确实出现这样的问题了 。 可能是我的浏览器问题
