### ISSUE TITLE
[Bug] AntV 组合图柱状图重叠在一起

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#6578]
**DataEase 版本**
v 1.8.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 118.0.5993.89（正式版本） （64 位）

**Bug 描述**

AntV 组合图柱状图重叠在一起，两个指标放在一个位置展示了，正确的应该是两个柱状图左右挨着
**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/127368807/6e567ecd-fc5b-47b2-b132-90b0bce1f8c2)
![image](https://github.com/dataease/dataease/assets/127368807/62da7c47-171f-4e58-87fa-07b70199adf1)

**Comment by BBchicken-9527** [comment]
感谢反馈，图库原因轴无法做区分，目前无法更好的处理；
