### ISSUE TITLE
[Bug]透视图功能bug

### ISSUE THREAD

**Issue by zhangtaogxl** [dataease/dataease#6579]
**DataEase 版本**
1.0体验版

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
透视图中，使用某列做为标题。指标放入后，指标数据无法正常显示（指标数据是正常的数据，但在显示时，显示的是指标名称）

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/75556942/f92d19f2-7920-4108-bb36-d7b1d3e8020d)

2.
3.

**Comment by greenyhsj** [comment]
透视图中的数据直接展示位指标名称，没有展示指标的值，v.1.18.12已复现

**Comment by BBchicken-9527** [comment]
感谢反馈，如果添加添加数据行维度呢？

**Comment by greenyhsj** [comment]
放在行没有问题，列有问题，明显BUG

**Comment by greenyhsj** [comment]
![chrome_Ts6WTN7uiU](https://github.com/dataease/dataease/assets/127368807/1bebba27-67a6-41f2-8b3a-e7b85d018dfc)

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，透视表用的是antv的组件，当前antv组件还不支持该功能，待antv图库支持后，我们也会尽快支持上。
