### ISSUE TITLE
execl函数的计算数字后，导入预览正常，但是保存后数据丢失[Bug]

### ISSUE THREAD

**Issue by plateauandsp** [dataease/dataease#658]
**DataEase 版本**

v1.1.0-rc1

**浏览器版本**

chrom 91.0.4472.164
**Bug 描述**
execl中带函数的计算数字后，导入预览正常，但是保存后数据丢失。
![image](https://user-images.githubusercontent.com/30932762/129855144-311042ab-faf6-406d-aa00-0e578c3c056f.png)
![image](https://user-images.githubusercontent.com/30932762/129855164-a0092d53-fdee-4106-9f23-310f112f3dd2.png)

[月度佣金费走势图.xlsx](https://github.com/dataease/dataease/files/7005311/default.xlsx)

**Comment by plateauandsp** [comment]
execl原文已经提交

**Comment by xuwei-fit2cloud** [comment]
v1.2.0 已修复
