### ISSUE TITLE
[Bug] 2.0 数据源如果是 Oracle，SQL 数据集就会报错

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#6580]
**DataEase 版本**
v2.0.0

**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**

版本 118.0.5993.89（正式版本） （64 位）
**Bug 描述**
 2.0 数据源如果是 Oracle，只要是 SQL 数据集就会报错，已复现

**Bug 重现步骤(有截图更好)**
![87f5117b94ccd7f6752339ed137a21f](https://github.com/dataease/dataease/assets/127368807/52e8ade8-3a81-4518-afad-9a2f338bcca5)

**Comment by BBchicken-9527** [comment]
你好，在最新版本没有复现，请上传复现场景文件和后台日志信息，方便我们进一步排查原因，感谢理解和支持。请说明一下你使用的oracle版本；

**Comment by greenyhsj** [comment]
报错
![image](https://github.com/dataease/dataease/assets/127368807/dc0f2dd4-70d9-4bea-9f7b-7918072ae5bb)
![Uploading chrome_KbOXlmCIIn.gif…]()

**Comment by greenyhsj** [comment]
![chrome_KbOXlmCIIn](https://github.com/dataease/dataease/assets/127368807/67950d8e-6666-4ad8-9a90-5c6d6344bc6d)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前2.x暂时不支持低于12的版本，后续版本将逐步上线驱动管理解决这一问题；
