### ISSUE TITLE
[Feature]折线图横轴数据显示能不能整体设置不要靠近纵轴

### ISSUE THREAD

**Issue by linxiao0915** [dataease/dataease#6584]
折线图横轴数据显示能不能整体设置不要靠近纵轴,如果太靠近纵轴,横轴数据显示就会和纵轴的数值有部分重叠遮挡.
![f8bb4f97d010f5baa6dfff6523d4a3c](https://github.com/dataease/dataease/assets/31397975/8bf203c2-df46-414d-b51f-0550d9556ba1)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，标签的位置是由图库经过计算后统一返回的，如果设置不靠近纵轴，当标签数字较长时，也可能与其他标签发生重叠，当前还没有合适的方案进行优化。建议您设置数值格式，缩短数值长度，从而呈现更好的阅读和展示效果。
