### ISSUE TITLE
【Bug】自定义驱动连接oracle8报错

### ISSUE THREAD

**Issue by gaokr** [dataease/dataease#6585]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome 版本 119.0.6045.106（正式版本） （64 位）

**Bug 描述**
使用classes12.jar添加驱动，连接oracle8服务器，校验通过，但数据源表打不开，有报错

**Bug 重现步骤(有截图更好)**
![eb5d1deba91f5c26540aa34bf52ac04](https://github.com/dataease/dataease/assets/17250905/8761ef0a-55c7-498e-b596-c070e3be6cd7)
![320652741a55c484bd3b6c462f5c2bb](https://github.com/dataease/dataease/assets/17250905/bfcbe400-adf3-4e86-976d-6c0247d82c27)
![e5e9cfbdc61673c0af97545e1456cd1](https://github.com/dataease/dataease/assets/17250905/c616d2b2-9531-45d0-8aa9-91da1ac62300)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前平台支持的最低的oracle版本为11的版本，再低的版本目前无法支持，给你的使用带来不便实在不好意思；
