### ISSUE TITLE
[Bug]非默认驱动时，oracle数据集无法使用定时同步

### ISSUE THREAD

**Issue by gaokr** [dataease/dataease#6586]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome 版本119.0.6045.106 (正式版本) (64 位)

**Bug 描述**
使用默认版本驱动包添加驱动后，连接数据库无法使用定时同步，换成缺省后，即可使用

**Bug 重现步骤(有截图更好)**
![74089c8174da265b77e03d9a052655f](https://github.com/dataease/dataease/assets/17250905/7e7b9c5a-ac03-4223-972d-bf515657611f)
![b93487e1c27d725b6a8414ad5dc797d](https://github.com/dataease/dataease/assets/17250905/ccf0da08-28b9-4496-96f7-265e8bcbc94b)
![466cbcdd592d0919642fe462e09a8ca](https://github.com/dataease/dataease/assets/17250905/cb249ac8-f1ad-4f2c-9547-c7068b66aa7e)
![bc846fcfc439e87b25c5c10fa95032a](https://github.com/dataease/dataease/assets/17250905/f0ffdafd-24d9-4040-bf62-af13944b9b88)
![image](https://github.com/dataease/dataease/assets/17250905/5cf5fc6b-2840-4b69-b48b-77c9035dafa1)

**Comment by gaokr** [comment]
使用v1.18.11系统中的原始驱动包来添加驱动，同样有这个问题。【/var/lib/docker/overlay2/27ac3dca547128ed73e77bb8b675773adf5e24eb33627aba6384d33dbe4e3189/diff/opt/dataease/drivers/ojdbc8-12.2.0.1.jar】

**Comment by BBchicken-9527** [comment]
感谢反馈，如果使用了自定义的驱动在当前版本是不允许定时同步的，因为目前还没有办法将自定义的驱动放到kettle中；

**Comment by f2m4** [comment]
官方能加一下吗.   需要 mssql12 的版本支持....
