### ISSUE TITLE
[Bug]角色管理中内置角色：普通员工，编辑时提示为管理员提示，建议修改

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#6593]
**DataEase 版本**
v.18.12

**运行方式(安装包运行 or 源码运行 ?)**
离线包

**Bug 描述**
角色管理中内置角色：普通员工，编辑时提示为管理员提示，建议修改

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/70566485/c235ea5c-9af9-4d3a-8d57-7ff370ff7115)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们下个版本修复。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
