### ISSUE TITLE
Oracle数据库创建数据集问题

### ISSUE THREAD

**Issue by lgycqu** [dataease/dataease#6595]
**DataEase 版本**
v2.0

**运行方式(安装包运行 or 源码运行 ?)**
在线安装

**浏览器版本**
chrome浏览器

**Bug 描述**
创建Oracle数据源后，创建数据集提示错误

**Bug 重现步骤(有截图更好)**
1.
<img width="657" alt="image" src="https://github.com/dataease/dataease/assets/37897479/aecbfe36-0e41-4ab5-8be0-8e62b8770187">

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你使用的oracle数据集是什么版本的呢？目前暂时不支持oracle12一下的版本；

**Comment by lgycqu** [comment]
请问v1.18版本支持Oracle11吗？

**Comment by lgycqu** [comment]
> 感谢反馈，请问你使用的oracle数据集是什么版本的呢？目前暂时不支持oracle12一下的版本；

请问v1.18版本支持Oracle11g吗？

**Comment by BBchicken-9527** [comment]
1.18.13将会正常支持11g；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
