### ISSUE TITLE
数据同步

### ISSUE THREAD

**Issue by 123456chegnwei** [dataease/dataease#6596]
**DataEase 版本** 
V2

**运行方式(安装包运行 or 源码运行 ?)** 
IDEA 源码运行

**浏览器版本** 
火狐开发版 最新

**Bug 描述**
1、系统管理-数据同步-添加任务（左边菜单没有了）
![图片](https://github.com/dataease/dataease/assets/50759654/529e8580-af0c-4c45-aad2-cedb3cc53ca3)
2、选择数据集没有数据
![图片](https://github.com/dataease/dataease/assets/50759654/5696608e-ccba-4e76-ac98-49e114daa2e1)

**Bug 重现步骤(有截图更好)**

怀疑是不是值个地方写错了
![49643bff2eb5a698c2e270da3bd8e57](https://github.com/dataease/dataease/assets/50759654/66c7ceaa-f56e-43e1-8656-bd851415a871)
但是我在本地改了，zu左边选择的树出来了，一选择又报错了，我就没看了

**建议**
加一个数据库A对数据库B的数据推送任务就好了

**Comment by BBchicken-9527** [comment]
感谢反馈，建议使用官方的安装包尝试，若二开产生问题建议添加提问或官方交流群中询问，会有非常专业的小伙伴进行解答；
