### ISSUE TITLE
[Question] Dataease 2.0 后台源码ide运行求能够正常运行的步骤，卡在数据库的配置，后台和数据库就是启动不了，maven这些是好的

### ISSUE THREAD

**Issue by mkcmgl** [dataease/dataease#6597]
**请描述您的问题.**

**Comment by mkcmgl** [comment]
官网的文档能准确点吗，源码本地运行不行，docker能够正常运行

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请在下图所示位置填写正确的数据库信息，如果还是报错的话，可以在评论这里追加一下报错信息。
![image](https://github.com/dataease/dataease/assets/84168063/eb340646-9bb0-41e2-bad0-87ed3b261b2e)

**Comment by hxpmc** [comment]
> 官网的文档能准确点吗，源码本地运行不行，docker能够正常运行
de-pack 怎么处理的呀
