### ISSUE TITLE
[Feature]对于已创建的视图，无法修改视图名称。建议新增视图重命名功能。

### ISSUE THREAD

**Issue by chenxin2001** [dataease/dataease#66]
**请描述您的需求或者改进建议.**
对于已创建的视图，无法修改视图名称。
建议新增视图重命名功能。
![图片](https://user-images.githubusercontent.com/34565342/123536057-91518780-d75a-11eb-9250-e5ea510895b4.png)

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #74

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已支持
