### ISSUE TITLE
[Feature]明细表自定义宽度功能，不能实现自定义

### ISSUE THREAD

**Issue by kkljcf** [dataease/dataease#6600]
**请描述您的需求或者改进建议.**
[Feature]明细表自定义宽度功能，不能实现自定义
只能调整成等比宽度，等同不能自定义，需要调整

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录并讨论一下实现方式。

**Comment by xuwei-fit2cloud** [comment]
我们在后续版本做一下支持。
