### ISSUE TITLE
[Feature]创建公共连接后，查看页面中，鼠标移动到部件之上，不要显示框框

### ISSUE THREAD

**Issue by kkljcf** [dataease/dataease#6601]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/125198800/93ba0ac4-cfc0-44ed-83cc-f71081b5891a)
创建公共连接后，查看页面中，鼠标移动到部件之上，不要显示框框

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，这个优化我们在v1.18.11已经完成，建议您升级一下版本。
