### ISSUE TITLE
[Feature]建议增加一键备份/迁移/导出/恢复

### ISSUE THREAD

**Issue by kkljcf** [dataease/dataease#6602]
**请描述您的需求或者改进建议.**
建议在web页面上，增加一键备份/迁移/导出/恢复，
并不是每个人都有较好的计算机基础的，需要更加简易化

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录并讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们考虑一下备份和导出功能，迁移和恢复功能在web页面上不太好支持。

**Comment by kkljcf** [comment]
> 我们考虑一下备份和导出功能，迁移和恢复功能在web页面上不太好支持。
用其他系统，几乎市面流通的付费系统都支持一键备份还原。
只是将手动备份，做成自动化，一键化
手动+脚本的思路是，
启动脚本，判断data是否运行，
然后停止运行data
备份走/opt
最后启动data
感觉并没有那么多难点呀。

**Comment by xuwei-fit2cloud** [comment]
可以考虑提供备份和还原的脚本，但web页面的操作短期内没有支持计划。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
