### ISSUE TITLE
[Feature]需要增加百分比进度条

### ISSUE THREAD

**Issue by kkljcf** [dataease/dataease#6603]
**请描述您的需求或者改进建议.**
![124be150e73b6a94fc6b773637ce18c6_u=1796559635,2692109260 fm=193](https://github.com/dataease/dataease/assets/125198800/b69e650e-4840-4496-9194-e680a7850d4d)
需要增加百分比进度条
给两个字段，
一个字段代表满值，比如80
一个字段代表进度值，比如20
这样组合起来，就可以得到一条25%的进度条。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池并进行调研一下，建议您先使用水波图、仪表盘等图表。

**Comment by kkljcf** [comment]
市面上成熟的作图表软件/系统/工具等，全都有百分比进度条，data没有让人很意外
