### ISSUE TITLE
dataset table task log表的数据无法自动周期性删除导致MYSQL的cpu占用异常

### ISSUE THREAD

**Issue by moncat2005** [dataease/dataease#6604]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 

**Bug 描述**
我这边自二季度以来，在系统上做了一些每分钟进行数据同步的任务，
运行一段时间后发现系统中MYSQL进程存在每分钟特性的CPU高占用性的情况（高达350%）。
后来我尝试分析数据库，发现只有dataset table task log这张表数据量非常大，将近200w。
具体查看后发现数据确实是从任务设定的一开始就存在的，至今没有删除过。
我直接通过数据库操作删除该表中30天之前的数据后，剩下不到30w数据，
此时系统中的MYSQL的每分钟执行任务时的CPU占用降低到了60%样子。

我看系统管理中有一个日志周期限制，默认是30天，但我不确定这个配置项是否指的是数据同步任务的日志。
另外，在系统管理里，有个数据同步的执行记录，这张列表正是对应着dataset table task log，但上面没有删除功能。

**Bug 重现步骤(有截图更好)**
数据表处理前：
![image](https://github.com/dataease/dataease/assets/34859687/83f56695-be2e-470a-b8c9-c3e207be4e86)

数据表处理后：
![image](https://github.com/dataease/dataease/assets/34859687/c7fcf24f-e7ac-40a1-bd72-7c3ace935923)

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在后续的版本修复这个问题。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前问题已经修复，可以下载最新版本尝试；
