### ISSUE TITLE
[Bug]authUserService.clearCache缓存清理报错

### ISSUE THREAD

**Issue by naturlly** [dataease/dataease#6607]
**DataEase 版本**
1.18.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
CHROME11

**Bug 描述**
jar包形式在虚拟机上运行，admin登录后不退出，第二天登录不上去了，需要重新启动后才可以登录
**Bug 重现步骤(有截图更好)**
1.
![1699438194675](https://github.com/dataease/dataease/assets/64082313/e83f17a5-62de-4922-b853-d4176a64c920)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，如果你使用的不是最新的版本建议升级为最新的版本尝试；

**Comment by naturlly** [comment]
升到2.0还是1.18.12

**Comment by BBchicken-9527** [comment]
建议升级到1.18.12的版本，2.0是做了底层的重构无法直接升级到2.0的；

**Comment by naturlly** [comment]
好的，谢谢
