### ISSUE TITLE
[Feature]折线图数据移动鼠标到某条线时，支持线高亮，对应的提示高亮

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#6615]
**请描述您的需求或者改进建议.**
折线图数据移动鼠标到某条线时，支持线高亮，对应的提示高亮，其它线变灰暗
![image](https://github.com/dataease/dataease/assets/70566485/62534f72-fc2f-418e-8afb-c12d8b4fb46c)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，已记录到需求池中，但短期内还没有开发计划。
