### ISSUE TITLE
[Bug]仪表盘视图选择组合图但是显示效果只要柱状图

### ISSUE THREAD

**Issue by liangshasha1994** [dataease/dataease#6617]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
谷歌

**Bug 描述**
仪表盘视图选择组合图但是显示效果只要柱状图

**Bug 重现步骤(有截图更好)**
1.新建视图-组合图
2.选择字段 显示图不对
![1699515493117](https://github.com/dataease/dataease/assets/101374773/bc11d7f4-7acd-4827-892d-1d6c2b1badf7)

**Comment by BBchicken-9527** [comment]
感谢反馈，因为你源码运行无法精准的确定问题产出的原因，建议你使用官方包如果依然存在此类问题，可以将此问题再次打开，若源码运行建议给出日志信息 并添加问题的标签，也可以加入我们的官方群，里面会有非常专业的同学实时为你答疑；
