### ISSUE TITLE
[Bug]【仪表板】时间范围组件筛选报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#6623]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
Oracle 数据源，SQL 数据集，时间范围传参用时间范围组件筛选传参。

**Bug 重现步骤(有截图更好)**
1.Oracle 表数据类型如下所示：
![image](https://github.com/dataease/dataease/assets/24768910/8206e823-0001-4986-9fc4-12979808fd78)
![image](https://github.com/dataease/dataease/assets/24768910/41d88123-6d65-43a1-bd00-b1b4869d8729)

2.SQL 数据集配置如下图所示：
![image](https://github.com/dataease/dataease/assets/24768910/a96a5b4c-a750-415d-b9ce-37c748980a4b)
![image](https://github.com/dataease/dataease/assets/24768910/7c71808f-c18c-47de-ac4e-d1a679c23ee9)
SQL 如下：
select COLUMN1,COLUMN2,to_date(COLUMN3,'yyyy-mm-dd hh24:mi:ss') COLUMN3 from NEWTABLE where to_date(COLUMN3,'yyyy-mm-dd hh24:mi:ss') BETWEEN ${c1} and ${c2}

3.时间范围组件配置如下：
![image](https://github.com/dataease/dataease/assets/24768910/3683549d-acb2-43a7-b0f1-8b497dd29961)

4.筛选情况截图：
![image](https://github.com/dataease/dataease/assets/24768910/d5b08e21-873a-474c-a6af-4a0347c101fe)
![image](https://github.com/dataease/dataease/assets/24768910/2aadffaf-5b78-4aa6-a90a-edac9b3d2017)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问在数据集预览中参数化预览设置是否可以正常查询呢？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
