### ISSUE TITLE
[Bug]SQL变量误报错

### ISSUE THREAD

**Issue by fants** [dataease/dataease#6624]
**DataEase 版本**
V1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome最新

**Bug 描述**
明明所有参数都在 where 后面，还依然报错“SQL 变量只能在 WHERE 条件中使用”

**Bug 重现步骤(有截图更好)**
![WX20231109-214935](https://github.com/dataease/dataease/assets/2188977/17f97e10-a2f2-4170-a05f-2762458b2c89)

**Comment by BBchicken-9527** [comment]
感谢反馈，因为目前参数化功能还不够完善，这里说的where是指的只能加载最末尾的where中，我们优化一下这里的提示；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
