### ISSUE TITLE
[Feature]饼图视图变小时不希望标签遮挡

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6626]
**请描述您的需求或者改进建议.**
饼图标签视图变小时会遮挡，既然柱状图顶部标签可以自动适应不遮挡，饼图、环形图等能不能也做这个功能？
就是饼图在视图大小变窄时，标签自动向里移动。
<img width="335" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/de8e4204-e866-4f01-9067-84125766ab7f">
<img width="635" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/6b0551f9-1045-4a78-89c7-d5806f3aea42">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先看下图库是否支持。

**Comment by xuwei-fit2cloud** [comment]
我们在后续版本里尝试做一下优化。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
