### ISSUE TITLE
地图组件样式修改

### ISSUE THREAD

**Issue by 1627449553** [dataease/dataease#6628]
地图的悬浮样式能否添加悬浮框样式的修改内容，以及钻取后的区划的位置修改，除此之外可否增加钻取及打点的相关字段提示，就是需要哪种类型的哪种格式的字段

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录并讨论一下。

**Comment by 1627449553** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，关于您提出的建议，现回复如下：
1、《地图悬浮框样式的修改》，1.x上暂时没有计划提供内容、样式的修改，但是在 2.0 版本中进行提示框内容和样式的自定义，如果需要，建议您使用 2.0 版本。
2、《钻取后的区划的位置修改》，没有太理解这个位置修改是指哪里，如果方便，请追加一下评论。
3、《符号地图中打点字段的提示》，这里我们记录并优化一下。

**Comment by 1627449553** [comment]
> 再次感谢您的反馈，关于您提出的建议，现回复如下： 1、《地图悬浮框样式的修改》，1.x上暂时没有计划提供内容、样式的修改，但是在 2.0 版本中进行提示框内容和样式的自定义，如果需要，建议您使用 2.0 版本。 2、《钻取后的区划的位置修改》，没有太理解这个位置修改是指哪里，如果方便，请追加一下评论。 3、《符号地图中打点字段的提示》，这里我们记录并优化一下。

《区划位置》就是地图的图表在钻取后会显示面包屑，例如 全部>陕西省>西安市 这个样子的，这个组件的位置修改。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，左上角一般放图表标题，所以左下角放下钻的目录还是比较合适的，下钻目录的位置修改，是什么场景要使用呢？左下角位置被其他组件占用了？

**Comment by 1627449553** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
