### ISSUE TITLE
[Feature]单根柱子可以设置两个颜色的渐变

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6629]
**请描述您的需求或者改进建议.**
柱状图支持两个颜色的渐变，如下如，单根柱子可以设置两个颜色的渐变。
<img width="626" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/b0bcfd96-5a7c-4eba-a4ae-10347a59e0f0">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，近期暂时没有计划进行支持。
