### ISSUE TITLE
[Bug]oracle 数据集创建数据集 SQL 报错

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6630]
**DataEase 版本**
v2.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
 chrome

**Bug 描述**
数据源：oracle 11.2.0.4
数据集：SQL 简单查询
报错如下图：
![图片](https://github.com/dataease/dataease/assets/48307752/cfcc9f58-a4d5-4c6c-ab9a-bd47ab4153e6)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前由于没有开放驱动管理，所以目前暂时不支持12版本一下的oracle，后续版本将逐步上线驱动管理，给你的使用带来不便实在不好意思；

**Comment by maninhill** [comment]
对于老版本 Oracle，能不能以更友好的方式提示不支持，而不是报错。
