### ISSUE TITLE
[Feature] 仪表盘的组件（过滤条件）中文本下拉等不能携带自定义参数

### ISSUE THREAD

**Issue by 12frame** [dataease/dataease#6631]
**请描述您的需求或者改进建议.**
仪表盘-》组件（过滤条件）-》文本下拉、下拉树、数字下拉等：如果选择了sql数据集，不能携带自定义参数，不够灵活。希望能考虑加上这个功能，感谢。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
请问自定义参数是sql数据集的吗？如果是sql数据集的自定义参数，现在是可以绑定到过滤组件中的。

**Comment by 12frame** [comment]
> 请问自定义参数是sql数据集的吗？如果是sql数据集的自定义参数，现在是可以绑定到过滤组件中的。

可能我表达的不够准确，视图里的是可以绑定自定义参数的。

**Comment by 12frame** [comment]
> 请问自定义参数是sql数据集的吗？如果是sql数据集的自定义参数，现在是可以绑定到过滤组件中的。

我表达不够准确抱歉，

**Comment by 12frame** [comment]
> 请问自定义参数是sql数据集的吗？如果是sql数据集的自定义参数，现在是可以绑定到过滤组件中的。

我表达的不够准确抱歉，
视图他如果使用sql数据集是没有问题的，但是过滤组件他使用了sql数据集，自定义参数是没有办法设置，我看sql里他是用'bi'='bi'替换了
![image](https://github.com/dataease/dataease/assets/63937733/c7a150f9-bcac-4f57-bb2e-3e72540285a0)
![image](https://github.com/dataease/dataease/assets/63937733/9294973a-a21e-469b-b0e3-49930f874ce6)

**Comment by 12frame** [comment]
补充功能点
1：过滤组件可以设置默认值
2：可以和其他的过滤组件进行联动，比如A条件选择了广东，B条件就会根据广东去查找广州、深圳等（这个功能和下拉树类似的，但是我在B条件里因为业务上的一些原因，需要做一些特殊的处理）

我目前的痛点：我的报表有十几个，每个报表的过滤条件sql都是一样的，只要改变一个参数值就可以，但是为此我需要创建十几个数据集，感觉没有必要。如果有自定义参数，我只需要写一个sql数据集就够了，后面如果需要调整也只有调整这一个sql数据集。

**Comment by maninhill** [comment]
暂无支持计划。
