### ISSUE TITLE
[Bug]关于视图管理中计算指标在数据透视图的总计计算错误

### ISSUE THREAD

**Issue by Songjiadong** [dataease/dataease#6632]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

chrome
**Bug 描述**
我在视图管理中添加了计算指标，如：`round(sum([agg_money])/sum([pre_agg_money])-1,1)`，其中agg_money、pre_agg_money,分别为clickhouse中表的字段。
在数据透视图的构建中，在总计一栏中，没有将其正确的计算，如：sum(agg_money)/sum(pre_agg_money)-1，而是将总计下面的所有项进行统一sum，个人认为这是个BUG，也与在Excel当中使用的习惯不符

**Bug 重现步骤(有截图更好)**
 #1.
![Uploading 截图.png…]()

**Comment by BBchicken-9527** [comment]
感谢反馈，目前由于antV图库原因只支持了简单的sum，我这边已经记录了你的问题并反馈给了相应负责的小伙伴，我们讨论一下如果可以支持的话我们会尽快的完善这里；

**Comment by Songjiadong** [comment]
希望尽快，感觉其他部分挺好的，就这里硬伤，因为很多传统报表都不是简单求和的，都要搞个公式计算






 宋家东
***@***.***











Original:
From：9527 ***@***.***>Date：2023-11-10 14:21:05(中国 (GMT+08:00))To：dataease/dataease ***@***.***>Cc：JustinSong ***@***.***> , Author ***@***.***>Subject：Re: [dataease/dataease] [Bug]关于视图管理中计算指标在数据透视图的总计计算错误 (Issue #6632)
感谢反馈，目前由于antV图库原因只支持了简单的sum，我这边已经记录了你的问题并反馈给了相应负责的小伙伴，我们讨论一下如果可以支持的话我们会尽快的完善这里；

**Comment by xuwei-fit2cloud** [comment]
我们先调研一下。
