### ISSUE TITLE
[Feature]横向柱状图靠近纵轴一侧标签值会与纵轴重和

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6634]
**请描述您的需求或者改进建议.**

如下图所示，标签值较长时，靠近纵轴会与纵轴重和，希望可以想柱状图一样，标签可以自动偏移。
<img width="1020" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/ecd6da4d-fd8e-4b46-ba3d-879c98b5319c">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，规划在后面几个版本迭代中，对标签的位置和显示进行优化，请关注我们 Release Notes。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
