### ISSUE TITLE
如何修改WEB UI访问端口

### ISSUE THREAD

**Issue by zerotocode398** [dataease/dataease#6635]
1. dataease version： 1.18.11
2. 部署方式：编译安装

测试方式
1. 将所有的":8081"替换为":8083"
![image](https://github.com/dataease/dataease/assets/31309558/d29c65c2-caee-42cf-b470-c88df5ed86a9)

测试结果

![image](https://github.com/dataease/dataease/assets/31309558/2149d088-6dcf-447e-8809-4767713b5d2e)

**Comment by tjlygdx** [comment]
![image](https://github.com/dataease/dataease/assets/12710377/f08f4cd8-2b1e-4c72-a9d7-252c7a12009e)
改这里

**Comment by zerotocode398** [comment]
> ![image](https://user-images.githubusercontent.com/12710377/282380502-f08f4cd8-2b1e-4c72-a9d7-252c7a12009e.png) 改这里

不行啊兄弟。
![image](https://github.com/dataease/dataease/assets/31309558/5ece24aa-5315-4084-bfa7-cff2ceb762c9)
我是将全部":8081"替换为了":8083"，然后额外替换了server.port=8083。
部署的时候前端和后端也都替换了，访问还是404
直接访问的dataease服务

**Comment by maninhill** [comment]
二开问题请自行研究，望理解。
