### ISSUE TITLE
[Bug] 仪表板时间范围组件设置了默认时间查询，但多次的 SQL 查询没有带上时间参数，导致全表数据查询

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [dataease/dataease#6638]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器 117 版本

**Bug 描述**
仪表板时间范围组件设置了默认时间查询，但在实际仪表板显示数据的过程中，通过抓取 /chart/view/getData 接口的响应体的 sql 字段，发现两次的 SQL 查询没有带上时间参数，导致全表数据查询。由于单表的数据过亿，直接导致数据库负载过高，以及DataEase CPU 占用飙升。

**Bug 重现步骤(有截图更好)**
数据库：MySQL  (StarRocks 也有此问题)

1. 新建 SQL 数据集， 筛选条件包含时间字段， 使用动态参数传递。
![image](https://github.com/dataease/dataease/assets/30264974/10b8f3ce-7a16-47d8-a692-bf914cb9a393)

2. 新建仪表板，使用明细表组件，配置时间范围过滤组件，时间范围组件设置默认查询时间。
![image](https://github.com/dataease/dataease/assets/30264974/d71462d2-786a-415e-88e3-a6e800f7e8c4)

3 编辑仪表板，如视频操作，前端 F12 监控接口 /chart/view/getData 的响应体 sql 字段，记录该接口每次调用的 sql 字段，base 64 解密查看SQL ，发现有两次 SQL 没有带默认时间参数。

https://github.com/dataease/dataease/assets/30264974/57151f98-f6d9-4b8e-8050-9739af05b802

[DE 参数.docx](https://github.com/dataease/dataease/files/13317043/DE.docx)

该问题会导致在编辑仪表板-查看仪表板的过程中，产生全表查询的SQL 执行，直接导致数据库负载过高，DataEase CPU 负载过高。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复这个问题

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
