### ISSUE TITLE
[Feature]支持旭日图

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6639]
**请描述您的需求或者改进建议.**
希望支持旭日图
https://g2plot.antv.antgroup.com/examples/more-plots/sunburst/#label
![图片](https://github.com/dataease/dataease/assets/48307752/2c0422d5-ea24-49b7-a226-7990ef8919a6)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈和建议，我们先加入需求并进行调研，不断地丰富图表类型一直在我们的产品规划中，再次感谢您的关注和支持。
