### ISSUE TITLE
V1版本Echart地图视图的标签显示的位置是什么

### ISSUE THREAD

**Issue by lan2wen2hui** [dataease/dataease#6641]
V1版本Echart地图视图标签显示的位置是JSON文件中的哪个参数确定的？我按照DataEase的地图格式上传了我们一个车场的JSON文件，发现标签显示的位置偏差很大，到泊位就直接找不到了。但是气泡地图就可以看到标签

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，标签的显示位置是由图库根据坐标计算后返回的，echarts图库的地图和气泡地图用的是echarts地图，符号地图用的L7地图，因此可能计算规则有些差异。
