### ISSUE TITLE
[Bug]MySQL数据源添加时额外的JDBC的连接字符串useSSL=true时，网络无问题的情况下报错Communication link failure

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#6642]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
MySQL数据源添加时额外的JDBC的连接字符串useSSL=true时，网络无问题报错Communication link failure
查看代码里pom文件中的jar包为8.*，而实际用的jar包为5.*，也就是数据源添加时使用的还是5.*版本的驱动，建议进行版本统一到8.*

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/70566485/b53b0bcd-67b6-4f62-a335-2867437eaaf4)
![image](https://github.com/dataease/dataease/assets/70566485/864b8b9d-d1df-494f-a8dd-ea72a38ca6bc)

**Comment by BBchicken-9527** [comment]
感谢反馈，默认msysql驱动：mysql-connector-java-5.1.46.jar，不满足的话可以通过自定义添加；

**Comment by ziliang-wan** [comment]
自定义驱动只能直连，不能定时同步，能否升级下驱动？8 应该也是支持 5 的

**Comment by maninhill** [comment]
测试下看能否全部统一成 8.* 的驱动。

**Comment by BBchicken-9527** [comment]
感谢反馈，没有支持8的驱动是因为kettle不支持mysql 8.x的驱动，并且目前的驱动是兼容8的；

**Comment by xuwei-fit2cloud** [comment]
目前还无法处理。
