### ISSUE TITLE
[Bug]更换仪表板主题后，仪表板样式中“视图样式”无法展开

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#6643]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
更换仪表板主题后，仪表板样式中“视图样式”无法展开

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/101089844/0538c043-ad7a-40da-b115-4b87b916a9c9)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，请问题这个问题可以稳定复现嘛？我这边的测试环境是没有问题的，或者清理一下缓存试试看呢？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
