### ISSUE TITLE
[Bug]通过仪表板样式中标题属性统一更改的标题颜色，tab组件中非当前页中的视图标题更改颜色未生效

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#6644]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
通过仪表板样式中标题属性统一更改的标题颜色，tab组件中非当前页中的视图标题更改颜色未生效

**Bug 重现步骤(有截图更好)**
1.统一将标题修改为深灰色了
![image](https://github.com/dataease/dataease/assets/101089844/a246d886-ee2e-47d9-9174-aec38c64996a)

2.第二个tab中标题修改未生效
![image](https://github.com/dataease/dataease/assets/101089844/8fe00b6d-2ece-4d5e-b7b3-dbe4c348fc2d)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本修复；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
