### ISSUE TITLE
[Bug]dataease v2.0: dataease-license-sdk 未上传至仓库

### ISSUE THREAD

**Issue by mmmmmmiracle** [dataease/dataease#6646]
**DataEase 版本**
V2.0

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome 已是最新版本
版本 119.0.6045.124（正式版本） （64 位）

**Bug 描述**
打包提示找不到 dataease-license-sdk

**Bug 重现步骤(有截图更好)**
1. 在sdk目录下执行 mvn clean package, 提示找不到包
![image](https://github.com/dataease/dataease/assets/38560338/a464a9eb-6a78-4668-95db-9a6554cf7302)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行此处的修复；

**Comment by rocklei123** [comment]
请问这个问题修复了嘛？

**Comment by heartInGod** [comment]
请问这个问题修复了嘛？

**Comment by mmmmmmiracle** [comment]
已修复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataease/dataease"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月3日(星期三) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataease/dataease] [Bug]dataease v2.0: dataease-license-sdk 未上传至仓库 (Issue #6646)





 
请问这个问题修复了嘛？

**Comment by heartInGod** [comment]
> 已修复！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "dataease/dataease" ***@***.***&gt;; 发送时间:&nbsp;2024年1月3日(星期三) 下午5:06 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [dataease/dataease] [Bug]dataease v2.0: dataease-license-sdk 未上传至仓库 (Issue #6646) 请问这个问题修复了嘛？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

好像还是会报错

<img width="1894" alt="image" src="https://github.com/dataease/dataease/assets/30049098/aa5c8c60-c866-4696-b3e1-17bb35d4823f">

**Comment by mmmmmmiracle** [comment]
我这2.1版本的貌似没问题了，2.2新版本的应该还没上传吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataease/dataease"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月3日(星期三) 下午5:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataease/dataease] [Bug]dataease v2.0: dataease-license-sdk 未上传至仓库 (Issue #6646)





  
已修复！
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "dataease/dataease" @.&gt;; 发送时间:&nbsp;2024年1月3日(星期三) 下午5:06 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [dataease/dataease] [Bug]dataease v2.0: dataease-license-sdk 未上传至仓库 (Issue #6646) 请问这个问题修复了嘛？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
好像还是会报错
 image.png (view on web)

**Comment by heartInGod** [comment]
咱们的主分支是哪一个

**Comment by topul** [comment]
`Exception in thread "main" java.lang.IllegalArgumentException: File /opt/apps/xpack-permission.jar must exist`
你们源码运行不会报这个吗？
`de-xpack/xpack-permissions/target/xpack-permissions-$IMAGE_TAG.jar`这个包没有啊

**Comment by dingding668** [comment]
现在似乎还是没有修复啊
![6e1449bf33941ff37e6284d223d6b19](https://github.com/user-attachments/assets/ea15ac7c-eb9a-4bcd-ac0f-a5c33ec2aa0c)
