### ISSUE TITLE
[Bug] 大屏里的视频流组件无法播放视频流

### ISSUE THREAD

**Issue by Chinamonster123** [dataease/dataease#6651]
**DataEase 版本**
v1.18

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
使用dataease里面的视频流组件去播放一个flv视频流地址，无法播放。

**Bug 重现步骤(有截图更好)**
1. 把视频流组件放置在大屏上
2. 设置视频流组件的视频流地址

**Comment by BBchicken-9527** [comment]
感谢反馈，由于你是源码方式运行，中间可能因为打包等原因导致，我无法给出精准的判断，目前测试环境中没有你说的问题，可以在线上环境去看一下是否存在你说的问题，如果是因为二开导致建议你进行提问或者是加入我们的公众群，让面会有非常专业的小伙伴在线实时给你解决你的困扰；
