### ISSUE TITLE
[Bug] 数值下拉组件排序异常

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [dataease/dataease#6661]
**DataEase 版本**
v 1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器 v 117 版本

**Bug 描述**
Excel 数据源，字段格式为数值格式， 仪表板配置数字下拉组件，并设置排序规则，排序显示异常

**Bug 重现步骤(有截图更好)**
1. 数据集导入 Excel 表格，具体的数据如下图，设置 “年” 字段格式为数值格式
![image](https://github.com/dataease/dataease/assets/30264974/106ae72f-29f6-40dd-9b01-4b9b552fb7c0)
![image](https://github.com/dataease/dataease/assets/30264974/ac8d2d5a-aff6-435b-a7fb-9b6660ce7edb)

2. 配置仪表板，新增一个明细表视图，以及 数值下拉组件，配置数值下拉组件 排序为 倒序。
![image](https://github.com/dataease/dataease/assets/30264974/579456ca-232d-4796-aeaf-b14e6a190b1d)

![image](https://github.com/dataease/dataease/assets/30264974/697bbdba-a637-4063-bfb4-958fa1decd41)

3.可以看到数值下拉组件，排序显示异常。
![image](https://github.com/dataease/dataease/assets/30264974/19ab9d5d-f1dc-42ab-88ea-698b729395f1)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的这个问题，前后端是否存在异常文件方便我们定位问题；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
