### ISSUE TITLE
[Bug]V2版本API数据源使用Post请求报错

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#6670]
**DataEase 版本**
V2.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌浏览器最新

**Bug 描述**
V2版本API数据源使用Post请求报错

**Bug 重现步骤(有截图更好)**
1.配置API数据源，类型选择POST请求
2.正常填写请求头和请求体，请求体为json格式
3.点击校验和点击下一步都报错，报错截图如下
![image](https://github.com/dataease/dataease/assets/35896106/3abc08b6-eabe-44af-b764-68ad783c185f)

备注：使用相同API请求在v1.18.11版本正常

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
