### ISSUE TITLE
[Bug] TIDB数据源的数据集，明细视图中不能分页问题

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#6672]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 119

**Bug 描述**
TIDB数据源的数据集，明细视图中底部没有分页组件。 问题在于“core/backend/src/main/java/io/dataease/provider/ProviderFactory.java” 方法 “getQueryProvider(String type)“， tidb不能使用”dorisQueryProvider“，而应该使用”mysqlQueryProvider“

**Bug 重现步骤(有截图更好)**
1.新建tidb数据库数据源
2.新建sql数据集，表来源于步骤1中的tidb数据源
3.新建仪表盘，选择步骤2中的sql数据集，选择antv明细表

**Comment by BBchicken-9527** [comment]
感谢您的反馈，我们将在下个版本修复这个问题。

**Comment by BBchicken-9527** [comment]
感谢反馈，经过调研tidb分页时，需要排序，跟doris类似，无法处理；

**Comment by xiaorsly88** [comment]
使用doris数据源的时候，明细表下面的分页是能正常显示的，但tidb不能显示，改用mysqlProvider才可以，那么dorisProvider是不是要调整下，兼容tidb的分页方式？
