### ISSUE TITLE
仪表板数据请求

### ISSUE THREAD

**Issue by qc-jyp** [dataease/dataease#6675]
**DataEase 版本**
1.18.4

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
 chrome 119.0.6045.124

**Bug 描述**
仪表板通过筛选获取数据，总数据量大，筛选后数据量小，但仪表板进入编辑后获取筛选数据后还会进行获取全部数据的操作从而导致页面卡死

**Bug 重现步骤(有截图更好)**
1.找个数据量大的接口进行筛选获取
2.进入编辑
3.这时候会调用两次https://api.eos-ts.h3c.com/data-ease/v1.0/chart/view/getData/xxx/xxx找个接口
4.第一次调用会通过筛选条件去查询（正常），第二次不带筛选条件查询（卡死）
![image](https://github.com/dataease/dataease/assets/103424265/b62c794b-0f7d-4344-89cd-f2522c3edc6f)
![image](https://github.com/dataease/dataease/assets/103424265/7fe48908-4b46-412e-b846-0b123023d91f)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，与issue：https://github.com/dataease/dataease/issues/6638  相同，已经在v1.18.13版本进行了优化，请关注最近的版本发布。
