### ISSUE TITLE
[Feature]图片组件配置超链接后可以直接点击图片进行跳转

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6682]
**请描述您的需求或者改进建议.**
图片组件配置超链接后可以直接点击图片进行跳转，而不是点击图片触发小图标，再点击小图标跳转。
![图片](https://github.com/dataease/dataease/assets/48307752/71e69862-a0de-41aa-b99c-3bdd41d7cde9)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们在后续版本优化一下。

**Comment by ziyujiahao** [comment]
这里是可以支持的，需要注意的是因为在编辑界面 需要进行拖动布局 所以编辑界面这个点击图片跳转是不生效的 预览会生效
