### ISSUE TITLE
[Bug]富文本组件中添加超链接，选择“当前窗口”打开，实际会打开一个新窗口

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6685]
**DataEase 版本**
v1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
富文本组件中添加超链接，选择“当前窗口”打开，实际会打开一个新窗口。
![图片](https://github.com/dataease/dataease/assets/48307752/565c8c74-2474-4586-b11a-479bd259c661)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，目前正在努力修复中；

**Comment by mfanoffice** [comment]
![图片](https://github.com/dataease/dataease/assets/48307752/a07af2b3-c107-46f5-8491-795c24e05cad)
v2版本也会存在相同问题，希望再v2版本修复。
