### ISSUE TITLE
[Bug] 符号地图背景色配置不生效

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#6691]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome
版本 119.0.6045.123（正式版本） (arm64)

**Bug 描述**
符号地图背景色配置不生效，配置暗色时仍然显示亮色

**Bug 重现步骤(有截图更好)**
如下图所示：
<img width="946" alt="image" src="https://github.com/dataease/dataease/assets/30063018/f9ff6eed-0cb8-43ef-b380-6daacfb13f2f">

**Comment by BBchicken-9527** [comment]
感谢反馈，问题已经修复，将会在下个版本上线；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
