### ISSUE TITLE
[Bug]移动端目录仪表板展示的顺序与PC端不一致

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#6692]
**DataEase 版本**
v1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

版本 119.0.6045.124（正式版本） （64 位）
**Bug 描述**
1和1.1的两个仪表板，PC端展示是按照 1→1.1，移动端则是1.1→1，展示的顺序与PC端不一致

**Bug 重现步骤(有截图更好)**
1.PC端
![image](https://github.com/dataease/dataease/assets/127368807/11d64cc3-0d2b-4238-9686-af7f1657be54)

2.移动端
![image](https://github.com/dataease/dataease/assets/127368807/97dd314a-3349-4e51-86f0-c4768bfbe2da)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题将会在后续版本发布；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
