### ISSUE TITLE
[Bug]给某个柱状图视图设置了联动和跳转，全屏预览模式下，点击没有出现联动/跳转气泡菜单

### ISSUE THREAD

**Issue by BugHunter7788** [dataease/dataease#6696]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
都一样

**浏览器版本**
chrome 119.0.6045.106

**Bug 描述**
给某个柱状图视图设置了联动和跳转，点击图标元素会弹出联动/跳转气泡菜单，但在全屏预览模式下，点击没有出现联动/跳转气泡菜单，
原因估计是因为vue-fullscreen插件调用了Element.requestFullscreen()，产生了一个[top-layer](https://developer.mozilla.org/en-US/docs/Glossary/Top_layer)，盖住了元素

**Bug 重现步骤(有截图更好)**
1.
![Clip_20231115_140232](https://github.com/dataease/dataease/assets/14085100/82b0a935-6923-4d0d-ae3b-b17c37d82c6b)

2.
![Clip_20231115_140304](https://github.com/dataease/dataease/assets/14085100/a7d28477-431b-42ab-a598-436cef474b76)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前最新版本已经修复了这个问题，欢迎升级体验；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
