### ISSUE TITLE
[Bug]仪表盘中，编辑仪表盘，对于已创建的文本，无法编辑修改字体颜色

### ISSUE THREAD

**Issue by chenxin2001** [dataease/dataease#67]
**DataEase 版本**
v1.0.0-rc2

**浏览器版本**
 FireFox 89.0.2 (64 位)

**Bug 描述**
仪表盘中，编辑仪表盘，对于已创建的文本，无法编辑修改字体颜色

**Bug 重现步骤(有截图更好)**
1. 编辑仪表盘
2.选择已创建的文本字体，右键选择编辑
3.更字体颜色，点击确定保存，修改的字体颜色无法生效
![图片](https://user-images.githubusercontent.com/34565342/123536108-e68d9900-d75a-11eb-89d2-d3b174468c2d.png)

**Comment by ziyujiahao** [comment]
这个问题 还没复现 可以选择颜色后点击一下确认试一下，文本编辑下个版本v1.1.0会改为富文本编辑方式，这种方式将会被取消

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已支持
