### ISSUE TITLE
[Bug]数据集自定义SQL异常修正后，保存后没有字段展示

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#6705]
**DataEase 版本**
2.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
1、写一个语法错误的SQL，保存报错
<img width="1475" alt="image" src="https://github.com/dataease/dataease/assets/89771514/09ed7c7f-171e-4388-aa9d-a8596fb596cf">

2、修正它，执行成功后点击保存
<img width="1475" alt="image" src="https://github.com/dataease/dataease/assets/89771514/fb8daf5f-c4d7-4b8e-b77f-d2e058efd087">

3、关掉编辑sql页面后，数据预览没有显示字段
<img width="1475" alt="image" src="https://github.com/dataease/dataease/assets/89771514/c5294f4d-1b14-4951-a9d8-7043ba2715ce">

**Comment by BBchicken-9527** [comment]
感谢反馈，没有显示字段是因为你新的sql没有勾选字段导致，只需要你进入编辑页面-点击sql下拉框-勾选字段，勾选你需要用到的字段就可以了；

**Comment by ZhaoQian1222** [comment]
你理解错了，步骤是这样的：
1、
<img width="1475" alt="image" src="https://github.com/dataease/dataease/assets/89771514/29b725a5-ebb4-4e17-b819-186a9c6e42c9">
2、
<img width="1475" alt="image" src="https://github.com/dataease/dataease/assets/89771514/848100af-b054-4255-b8da-ccf7da072fa8">
3、
<img width="1475" alt="image" src="https://github.com/dataease/dataease/assets/89771514/efb46ec9-1906-4f09-8323-b53ebd5e9c0b">
4、
<img width="1475" alt="image" src="https://github.com/dataease/dataease/assets/89771514/73efed00-a8e8-4f8b-8156-da98ce59714b">
