### ISSUE TITLE
[Bug]仪表板编辑时，鼠标经过柱状图，就是导致整个仪表板的数据一直刷新

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#6710]
**DataEase 版本**

v1.18.12

**运行方式(安装包运行 or 源码运行 ?)**

安装包

**浏览器版本**

版本 119.0.6045.124（正式版本） （64 位）

**Bug 描述**

鼠标经过柱状图的柱子，就是导致整个仪表板的数据一直刷新

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/127368807/f275ef25-3ee2-40be-8434-b6a5c24235a5)

**Comment by greenyhsj** [comment]
![lwpQSFG](https://github.com/dataease/dataease/assets/127368807/31cdc000-c395-4f1d-9e06-ddb3a9f836e4)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前这个问题应该已经修复了，可以下载最新版本体验；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。

**Comment by BugHunter7788** [comment]
请问是哪一个提交解决了这个问题？想参考一下 @xuwei-fit2cloud
