### ISSUE TITLE
[Bug] 仪表盘筛选框在不同电脑上数据不一致

### ISSUE THREAD

**Issue by liaoxiaodongabc** [dataease/dataease#6711]
**DataEase 版本** v1.18.11

**运行方式(安装包运行 or 源码运行 ?)** linux单机精简版

**浏览器版本** 谷歌最新浏览器

**Bug 描述**  同样的条件（一个的数据集，一个仪表盘），同一个筛选框，在A电脑和B电脑显示的筛选内容不一样

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by liaoxiaodongabc** [comment]
现在在使用过程中这个问题给我们带来了很大的困扰，听说 v 1.18.3会修复，是这样吗？

**Comment by BBchicken-9527** [comment]
感谢反馈，方便问一下数据是一个什么量级嘛？

**Comment by liaoxiaodongabc** [comment]
> 感谢反馈，方便问一下数据是一个什么量级嘛？
才几万条数据

**Comment by liaoxiaodongabc** [comment]
几万条数据

**Comment by liaoxiaodongabc** [comment]
> 谢谢反馈，方便问一下数据是一个什么量级啊？

**Comment by BBchicken-9527** [comment]
请问是什么类型的数据呢？因为定时同步类型数据获取数据是随机的，而因为图表默认计算1000条数据，如果这时你搜索数据大于一千条是会随机进行显示的，可以通过排序等方式固定数据顺序达到显示数据相同；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
