### ISSUE TITLE
[Feature]明细表建议可以对多个列设置合并表头

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#6712]
**请描述您的需求或者改进建议.**
请问类似明细表增加多级表头后续还会实现吗？参见issue #1941

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先看下图库是否支持。

**Comment by xuwei-fit2cloud** [comment]
我们在后续版本会做相关支持。

**Comment by xiaorsly88** [comment]
好的，感谢！ 另外，如果表头的字很长，能像表格一样自动换行更好

**Comment by yayanpei-fit2cloud** [comment]
请问是antv表格吗？antv表格不支持换行，我们在后面的版本会增加支持功能：悬浮至单元格上方，可以显示完整的内容。

**Comment by xiaorsly88** [comment]
是的，antv的表格表头，如果字数较多的话，调整列宽属性后，要么列宽显示太宽了，要么只能显示部分文字。这样在导出图片或PDF的时候效果不太美观。
