### ISSUE TITLE
[Feature] 提供数据字典配置，在前端展示的是名称，实际查询的是名称ID

### ISSUE THREAD

**Issue by blooze123** [dataease/dataease#6716]
**请描述您的需求或者改进建议.**
场景：
遇到一个比较通用的场景，在进行DE查询条件查询时，如果希望通过用户ID去查询用户信息，但是查询时，显示的是用户名称，而不是直接把用户ID展示出来，目前DE找不到这样子的解决方式。
希望实现的效果：
希望提供一个数据字典配置的功能，能把例如用户ID和用户名称进行关联，作为key-value键值对，当我需要查询某个用户的信息时，我的查询条件查找的是用户的名称，而实际我到后台sql查询时，其实查询的是对应的用户ID。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
这个需求的前提是，key和value在数据表里都是唯一的，否则如果一个value可以重复，那在选择的时候是无法确定对应的key的。

**Comment by hzhwyh0116** [comment]
> 这个需求的前提是，key和value在数据表里都是唯一的，否则如果一个value可以重复，那在选择的时候是无法确定对应的key的。

不太理解，key-value数据字典作为下拉框选择条件，用户选择哪个key就将对应value值传过去过滤，至于这个value是否在字典中重复应该影响不大吧？
