### ISSUE TITLE
[Feature] 能否提供一个弹窗组件，组件能够放置许多查询条件等内容

### ISSUE THREAD

**Issue by blooze123** [dataease/dataease#6718]
**请描述您的需求或者改进建议.**
场景
在做大屏时，如果遇到大屏需要选择的查询条件很多的情况下，在DE里面，只能不断加到大屏中，把真正要展示的视图都挤掉了。希望能否提供一个弹出层的组件，能放置各种查询条件过滤组件，把所有查询条件都藏在这个弹出层组件里面，当需要进行查询条件筛选过滤时，点击这个组件，才弹出众多查询条件，不需要的时候，就只有这个组件占大屏位置。能够极简地把空间让给其他要展示的视图。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们已加入需求池，等待排期。
