### ISSUE TITLE
[Bug] backend中的ojdbc8依赖版本重复冲突

### ISSUE THREAD

**Issue by one-knows** [dataease/dataease#672]
**DataEase 版本**
ed0f590

**浏览器版本**

**Bug 描述**
backend的pom.xml中的ojdbc8重复依赖如下
<dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc8</artifactId>
            <version>19.7.0.0</version>
        </dependency>

<dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc8</artifactId>
            <version>12.2.0.1</version>
        </dependency>

**Comment by xuwei-fit2cloud** [comment]
感谢您的反馈，我们修改一下

**Comment by xuwei-fit2cloud** [comment]
v1.2.0 已修复
