### ISSUE TITLE
[Bug]富文本无法识别[记录数]的值

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#6724]
**DataEase 版本**
v2.0.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
富文本无法识别[记录数]的值，仍然显示为[记录数]。

**Bug 重现步骤(有截图更好)**
1.分别添加[记录数]与其他的指标到富文本中；
![image](https://github.com/dataease/dataease/assets/48945409/3912c8a2-21d2-4d6a-919e-979a888f3a4c)

2.完成后，其他的指标正常被替换为实际数值，而[记录数]未被替换为实际的值。
![image](https://github.com/dataease/dataease/assets/48945409/6053be96-1e6a-4290-86ca-c16040c5ed26)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下此处；
