### ISSUE TITLE
[Bug]预览按钮与编辑按钮贴在一起

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#6732]
**DataEase 版本**
v2.0.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 标准版

**Bug 描述**
社区版没有【分享】按钮，【预览】按钮与【编辑】按钮中间没有留出间隔。
社区版无间隔如下图所示：
![image](https://github.com/dataease/dataease/assets/48945409/581e0110-58bd-4742-9c6a-482e7260912c)
企业版带间隔如下图所示：
![image](https://github.com/dataease/dataease/assets/48945409/1d4f2ec1-a9a8-4144-9c83-3f6ae8cf23fc)

**Comment by BBchicken-9527** [comment]
感谢反馈，分享功能是xpack功能，ui我们优化一下
