### ISSUE TITLE
[Feature]文字换行太宽了

### ISSUE THREAD

**Issue by kkljcf** [dataease/dataease#6733]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/125198800/9fe33b5d-a5fb-4df9-8569-c98bbd0bb5c9)
文字组件， 文字换行，间隔太宽，不能调节，需要增加与横向字间距一样的功能

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请问是组件间距吗？

**Comment by kkljcf** [comment]
> 感谢您的反馈，请问是组件间距吗？

![image](https://github.com/dataease/dataease/assets/125198800/79c24dee-95fd-4c87-8fc9-3a79310cc523)
不是，是同一个文字组件，换行的间隔太宽，并且无法调节

**Comment by xuwei-fit2cloud** [comment]
可以试试富文本组件，富文本组件可以条件行间距。
