### ISSUE TITLE
[Feature]组件间隙可以增加单独控制吗

### ISSUE THREAD

**Issue by kkljcf** [dataease/dataease#6735]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/125198800/550934eb-c529-4116-a006-d5f8a6e5bd2d)
某个组件可以单独选择是否有间隙

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，当前暂时没有计划进行支持。
