### ISSUE TITLE
[Bug]通过计算字段截取字符串不生效

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#6736]
**DataEase 版本**
V2.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 118.0.5993.117（正式版本） (arm64)

**Bug 描述**
新增计算字段时通过引用 SUBSTRING 函数新建字段不生效

**Bug 重现步骤(有截图更好)**
场景一：
1.原始数据字段为版本号（Excel数据集），数据具体内容包含V2.10.1、V1.20.21等若干；
2.新增计算字段：字段表达式 SUBSTRING([版本号],0,6)、 维度、字段类型为文本，名称为大版本号；
3.预览后获取到了通过函数计算的新字段大版本号，且数据按照函数计算正确；
4.在仪表板中将新字段大版本号拖入维度列，制作横向柱状图或者明细表，无法按照计算获取的大版本号进行统计展示。

场景二：
1.原始数据字段为交付负责人（Excel数据集），数据具体内容包含张三、王五等若干；
2.新增计算字段：字段表达式 SUBSTRING([交付负责人],0,1)、 维度、字段类型为文本，名称为负责人姓；
3.预览后未获取计算得到的负责人姓。

截图：
大版本号计算字段设置方式：
<img width="1031" alt="image" src="https://github.com/dataease/dataease/assets/60059766/a178e4d3-949d-41cb-b586-ab5f6acabec8">

大版本号预览结果：
<img width="654" alt="image" src="https://github.com/dataease/dataease/assets/60059766/56bf1a06-44bb-44cc-a6d6-ac19ae7b65ec">

基于大版本号拖入维度效果：
<img width="807" alt="image" src="https://github.com/dataease/dataease/assets/60059766/224be8fd-3227-463e-bac9-06e3ecebeadc">

**Comment by xueqidove** [comment]
补充说明下：
通过将函数参数修改SUBSTRING([版本号],1,5)后，通过仪表板可以作为维度展示，但是当基于该计算字段设置钻取时，一级为计算字段，二级为原生字段，钻取不生效

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的这个问题，请问前端有什么异常吗？

**Comment by BBchicken-9527** [comment]
> 补充说明下： 通过将函数参数修改SUBSTRING([版本号],1,5)后，通过仪表板可以作为维度展示，但是当基于该计算字段设置钻取时，一级为计算字段，二级为原生字段，钻取不生效

这里确实有点问题，我们修复一下；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，并且钻取的问题已经在新版本进行了修复，感谢你的反馈与支持；
