### ISSUE TITLE
[Bug] 基础折线图的颜色没有正确保存

### ISSUE THREAD

**Issue by sky84892070** [dataease/dataease#6737]
**DataEase 版本**
V 2.18.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome 119.0.6045.159

**Bug 描述**
修改基础折线图 样式-> 颜色 ->  配色方案 ->指标默认颜色 后，视图刷新后修改的颜色变为修改前。

**Bug 重现步骤(有截图更好)**
1. 新建一个空的仪表板
2. 新建一个视图，选择基础折线图
3. 选择记录数作为指标
4. 选择 样式 -> 颜色 -> 配色方案
5. 在弹出的“系统方案”窗体上，修改记录数对应的颜色由默认的蓝色为其他颜色
![image](https://github.com/dataease/dataease/assets/94676284/4cdbb146-8041-4e06-81d4-2a935190f86b)

6. 选择保存，点击2步创建的视图，视图自动刷新后

期望结果： 基础折线图的颜色为第五步修改后的颜色
实际结果： 基础折线图的颜色由修改后的颜色，变为修改前的蓝色

**Comment by BBchicken-9527** [comment]
感谢反馈，目前问题已经修复，将会在下个版本发布；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
