### ISSUE TITLE
[Bug]环形图的图例没有正常显示

### ISSUE THREAD

**Issue by sky84892070** [dataease/dataease#6738]
**DataEase 版本**
V1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
119.0.6045.159

**Bug 描述**
配置显示环形图的图例后，视图一旦自动刷新，图例消失。

**Bug 重现步骤(有截图更好)**
1. 新建仪表板
2. 新建视图 -> 选择环形图
3. 选择 样式 -> 图例 -> 显示， 点击保存
4. 点击第2步的视图，视图刷新后

期望结果：正确显示图例
实际结果：显示的图例消失

**Comment by BBchicken-9527** [comment]
感谢反馈，目前问题已经修复将会在下个版本发布；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
