### ISSUE TITLE
[Feature]视图-明细表类能否支持分页查看

### ISSUE THREAD

**Issue by brainsWangyang** [dataease/dataease#674]
视图-明细表类能否支持分页查看
![image](https://user-images.githubusercontent.com/15187776/130339667-1ddac1c0-1a21-45c9-bf32-ecb9d3b71620.png)

**Comment by yayanpei** [comment]
非常感谢您的反馈，我们讨论一下该需求。

**Comment by xuwei-fit2cloud** [comment]
v1.3.0 版本已支持。
