### ISSUE TITLE
[Bug] 对成柱状图维度错位

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6745]
**DataEase 版本**
v1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
对成柱状图维度错位

**Bug 重现步骤(有截图更好)**
<img width="669" alt="image" src="https://github.com/dataease/dataease/assets/45852479/efe6330f-bb45-4518-a2fe-9fe4ef52658c">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们修复一下；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
