### ISSUE TITLE
[Bug]ECharts 汇总表序号显示不全

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6747]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
echarts 汇总表自动生成的序号，当表的列很多的时候（60），会出现序号显示不全

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/f87a7665-f97b-46b6-9087-6764b7a54514)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，请问可以稳定复现吗？

**Comment by linyuiu** [comment]
> 感谢反馈，目前测试环境没有发现你说的问题，请问可以稳定复现吗？

是的，你的列要很多，我大概试了十几个列，三位数序号显示不全，60列的话2位数就显示不全了

**Comment by BBchicken-9527** [comment]
emm...我大概加了二十几个字段，你是不是调整过列宽？其实如果显示不全是可以通过调整列宽来增加显示宽度的；

**Comment by linyuiu** [comment]
> emm...我大概加了二十几个字段，你是不是调整过列宽？其实如果显示不全是可以通过调整列宽来增加显示宽度的；

这个生成的序号的列宽是不可调的，效果是这样的，我测试稳定复现
![image](https://github.com/dataease/dataease/assets/109720729/b96ac698-3ea8-4e46-94ca-db3009663d68)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问前端有提示什么异常吗？测试环境目前看是没什么问题，不过我们优化一下这里的列宽控制，尽可能让echarts的宽度也是一个可控的状态；
![image](https://github.com/dataease/dataease/assets/84372766/e8a2af65-b494-4d39-b438-b2abdcbd856c)

**Comment by linyuiu** [comment]
> 感谢反馈，请问前端有提示什么异常吗？测试环境目前看是没什么问题，不过我们优化一下这里的列宽控制，尽可能让echarts的宽度也是一个可控的状态； ![image](https://user-images.githubusercontent.com/84372766/284445720-e8a2af65-b494-4d39-b438-b2abdcbd856c.png)

这个刚刚我又测试了一下，三位数没问题，这下四位数显示不全了，这个bug看起来不稳定，那就更裂开了。
<img width="1377" alt="image" src="https://github.com/dataease/dataease/assets/109720729/125a47af-4654-485a-a742-ac62e07b93a5">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们后续会让序号的列宽变为可控，一定程度上可以规避你现在所困扰的问题；
