### ISSUE TITLE
[Bug] 仪表盘的视图中，关联doris数据集的视图在查询时没有分页，导致页面崩溃或系统内存溢出

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#6749]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 119

**Bug 描述**
使用doris数据集时，如果查询结果有10万或大几十万时，打开仪表板，系统会hang住，类似问题参见#5190

**Bug 重现步骤(有截图更好)**
1. 创建doris数据源
2. 创建doris查询的数据集
3. 新建仪表盘，选择antv明细表视图，关联数据集，分页选择10条或20条，视图的结果展示选择“全部”

问题原因，源码没有针对doris实现分页逻辑， 参见源码如下：
1、core/backend/src/main/java/io/dataease/provider/ProviderFactory.java，方法：getQueryProvider
2、core/backend/src/main/java/io/dataease/provider/query/doris/DorisQueryProvider.java，方法：getSQLWithPage，getResultCount
3、core/frontend/src/views/chart/chart/chart.js，全局常量：NOT_SUPPORT_PAGE_DATASET

显示视图时，使用ProviderFactory类中的方法getQueryProvider(String type)，如果是doris，该方法会使用了DorisQueryProvider中的getSQLWithPage，getResultCount来组装查询的sql和total count sql，但DorisQueryProvider虽然继承了MysqlQueryProvider，但和MysqlQueryProvider实现相差很大，这个类中这二个方法是没有实现分页的，total count sql直接返回了null。 
我的一个解决办法是在ProviderFactory中，doris类型和mysql类型一样，使用MysqlQueryProvider，同时移除chart.js中的NOT_SUPPORT_PAGE_DATASET中的ds_doris，把doris当mysql来处理， 最后在仪表盘的明细表视图中设置一个字段进行排序来解决。
以上解决方案，请评估是否有问题，谢谢！

**Comment by tjlygdx** [comment]
不行的，doris要先排序（order by），才能分页；
代码是故意这么写的

**Comment by xiaorsly88** [comment]
在SQL数据集的SQL中，最后写上order by [排序字段]；又或者在明细表祖图中被选择的某个维度配置它的排序是否可以呢？

**Comment by xiaorsly88** [comment]
经过测试，doris数据源代码调整为mysql一致，使用MysqlQueryProvider时，并在视图的维度中设置排序字段，可实现排序分页

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
