### ISSUE TITLE
[Bug]数据集中字段值为空时视图统计结果在视图中不展示，排序后取TOP时数据展示错误

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#6751]
**DataEase 版本**
V2.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 118.0.5993.117（正式版本） (arm64)

**Bug 描述**
Excel数据集中，数值字段A中部分数据为空，基于某维度统计后视图不展示为空的维度，但是部分展示数据时却将为空的维度值计算在内，导致部分展示结果错误。

**Bug 重现步骤(有截图更好)**
1.Excel 数据集准备，包含名称（文本）以及数量（数值）字段，其中50个文本值，50个文本对应的数量有11个为空，其他均有数值填充
2.基于该数据集创建横向柱状图，维度为名称，指标为数值，并按照数值降序排序，排序结果为（50-10）即40个维度的视图展示结果；
3.将数据展示数量展示从全部改为小于11的数，无数据展示，将数据展示从全部改为12则展示前1个数据；
4.如在高级中将为【空值处理】设置为【置为0】，则展示12条数据时将为空的展示在最前面。
截图展示：
截图1:数据展示结果改为10（小于11）的结果图如下：
<img width="914" alt="image" src="https://github.com/dataease/dataease/assets/60059766/1079218b-3ad5-4c4c-8936-38ec4f4ff13e">

截图2:将【空值处理】设置为【置为0】，全部改为12展示效果
<img width="276" alt="image" src="https://github.com/dataease/dataease/assets/60059766/b353ff58-6da1-44d8-bce5-286ed108ed62">
<img width="921" alt="image" src="https://github.com/dataease/dataease/assets/60059766/73a786a5-2a26-4c61-9f1f-fd2c3d0463a7">

截图3：保持隐藏为空，改为展示20则展示TOP9
<img width="920" alt="image" src="https://github.com/dataease/dataease/assets/60059766/7edbd349-6d44-4d3c-a4f6-503ed0fcfd6d">

**Comment by BBchicken-9527** [comment]
感谢反馈，经过排查calcite 中间件的设计中null为最大值，目前没有处理的方式，并且null在不同的数据源中默认排序的大小也不都是最大或者最小，暂时按照calcite中最大进行处理；
