### ISSUE TITLE
[Feature] antV明细表表头能否支持排序和增加小计合计

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#6754]
**请描述您的需求或者改进建议.**
如图所示，类似antv s2中的表头效果，可以升序或降序。 目前echarts可以，但感觉没有antv外观好。 另外明细表中最下面或上面能否增加小计合计的功能？
![image](https://github.com/dataease/dataease/assets/27687681/a175fbc1-607b-439a-b749-ffafcfe12d4a)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先调研一下。

**Comment by xuwei-fit2cloud** [comment]
近期版本我们会先把排序的支持给加上。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
