### ISSUE TITLE
nginx代理使用虚拟路径

### ISSUE THREAD

**Issue by zerotocode398** [dataease/dataease#6757]
**请描述您的问题.**
使用虚拟路径"de"，想通过**ip:port/de**的路径访问dataease主页，貌似不行。
1. nginx配置
```shell
server {
    listen      18011;
    location /de {
        root    /opt/dataease/frontend/dist/;
        index   index.html;
    }
    location /app.html {
        root    /opt/dataease/mobile/dist/;
    }
    location /de-app/ {
        alias   /opt/dataease/mobile/dist/;
    }
    location /de-api/ {
        proxy_pass http://app1:8083/;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host:18011;
        server_name_in_redirect on;
    }
}
```
**在dist目录下已经创建了de目录，并把文件移动到了de目录下**
```shell
[root@app1 dist]# pwd
/opt/dataease/frontend/dist
[root@app1 dist]# ll de/
total 8316
-rw-r--r--. 1 root root   47434 Nov 19 15:18 axios.js
drwxr-xr-x. 2 root root    4096 Nov 19 15:18 board
-rw-r--r--. 1 root root      41 Nov 19 15:18 ci_commit_sha_id
drwxr-xr-x. 2 root root    4096 Nov 19 15:18 css
-rw-r--r--. 1 root root 8186144 Nov 19 15:18 dynamic.gif
-rw-r--r--. 1 root root  207962 Nov 19 15:18 favicon.ico
drwxr-xr-x. 2 root root     244 Nov 19 15:18 fonts
drwxr-xr-x. 2 root root    4096 Nov 19 15:18 img
-rw-r--r--. 1 root root    2228 Nov 19 15:18 index.html
drwxr-xr-x. 2 root root    4096 Nov 19 15:18 js
-rw-r--r--. 1 root root   31471 Nov 19 15:18 lic.png
-rw-r--r--. 1 root root    1376 Nov 19 15:18 link.html
-rw-r--r--. 1 root root     782 Nov 19 15:18 nolic.html
-rw-r--r--. 1 root root     863 Nov 19 15:18 nologin.html
drwxr-xr-x. 5 root root      41 Nov 19 15:18 static
drwxr-xr-x. 4 root root      32 Nov 19 15:18 tinymce
drwxr-xr-x. 2 root root      55 Nov 19 15:18 vendor
```
2. 访问页面的时候加载不到dist/de/下的js、css文件
![image](https://github.com/dataease/dataease/assets/31309558/3ed2f9e0-0700-48fa-a53c-610b83f8d8ee)
![image](https://github.com/dataease/dataease/assets/31309558/1a35bb25-adfb-44f7-96f8-2900061617d8)
3. 尝试修改dist/de/index.html加载的路径改为de，还是不行
![image](https://github.com/dataease/dataease/assets/31309558/208c8a25-f444-4085-b0ee-59b6df681e50)
![image](https://github.com/dataease/dataease/assets/31309558/e4e6c83c-194d-40af-8f82-d79ca2170b40)

3. 使用环境
dataease 版本：v1.18.12
安装方式：前后端编译

是nginx配置有问题吗，还是需要额外处理什么？
麻烦帮忙看下，应该怎么处理

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，产品本身是不支持的，建议修改下图中的配置文件后，再打包试试。
![image](https://github.com/dataease/dataease/assets/84168063/76763135-de5d-4a62-a104-ff07eb42a462)
![image](https://github.com/dataease/dataease/assets/84168063/fc2c8def-bb29-4cf5-81ad-c5b06ebb1ccc)
