### ISSUE TITLE
[Feature]数据源大约几百张表时，数据库数据集加载很慢

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#6758]
数据源大约几百张表时，数据库数据集加载很慢，大约要一分钟
1、
<img width="1511" alt="image" src="https://github.com/dataease/dataease/assets/57552153/0722d54e-b90f-4fb3-b034-2145c797bdb2">
2、
<img width="1511" alt="image" src="https://github.com/dataease/dataease/assets/57552153/6ae62a9b-fe6c-4c36-8264-942b9781f199">
3、
<img width="1511" alt="image" src="https://github.com/dataease/dataease/assets/57552153/877f0b65-ea1c-4597-a54e-d9326b8450d0">

**Comment by xuwei-fit2cloud** [comment]
DataEase 是通过JDBC来获取数据库表名的，而相应的接口没有分页的支持。
如果要做数据库表名缓存的话，又缺少了一些实时性，这个我们还需要再考虑一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
