### ISSUE TITLE
[Bug]仪表板未添加数据源添加富文本后，富文本显示错误

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#6759]
**DataEase 版本**
2.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 118.0.5993.117（正式版本） (arm64)

**Bug 描述**
在仪表板中富文本，未指定数据集，添加富文本后首次查看以及保存都没有问题，但是进入预览页面查看时提示数据集已经丢失以及无数据权限

**Bug 重现步骤(有截图更好)**
1.进入一个仪表板添加富文本视图，不指定数据源
2.编辑保存完成后，关闭编辑
3.重新查看仪表板，富文本视图无法查看

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是富文本在不添加数据集的情况下保存后查看会显示异常？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
