### ISSUE TITLE
[Bug]页面嵌入式报错Uncaught (in promise) TypeError: Cannot read property 'panelData' of undefined

### ISSUE THREAD

**Issue by SLD-Allen** [dataease/dataease#676]
**DataEase 版本**
V1.1.0
**浏览器版本**
Google Chrome
版本 92.0.4515.131（正式版本） （64 位）

**Bug 描述**
页面嵌入 index.vue  文件 
this.$store.commit('setComponentData', this.resetID(JSON.parse(res.data.panelData)))
处报错
Uncaught (in promise) TypeError: Cannot read property 'panelData' of undefined
**Bug 重现步骤(有截图更好)**
1.iframe页面嵌入，dataease 分享链接
2.打开响应页面
3. index.vue 文件 this.$store.commit('setComponentData', this.resetID(JSON.parse(res.data.panelData)))报错Uncaught (in promise) TypeError: Cannot read property 'panelData' of undefined、

![image](https://user-images.githubusercontent.com/89327023/130340658-7b645b46-ae88-410e-bd2e-681e19b7e3ad.png)

![image](https://user-images.githubusercontent.com/89327023/130340644-1dbf2e18-f7c2-458d-94e6-d8f76b54ee53.png)

**Comment by SLD-Allen** [comment]
浏览器版本：Google Chrome 92.0.4515.131（正式版本） （64 位）

**Comment by SLD-Allen** [comment]
请问 这个BUG在 9.2 发布的 V1.2.0版本 会修复吗

**Comment by xuwei-fit2cloud** [comment]
这个bug在v1.1.1 和 v1.2.0 里都会修复

**Comment by xuwei-fit2cloud** [comment]
v1.1.1 和 v1.2.0 已修复
