### ISSUE TITLE
[Feature]文本下拉组件支持动态默认值设置

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#6763]
**请描述您的需求或者改进建议.**
文本下拉组件支持动态默认值设置，像日期过滤组件的动态默认值设置一样，希望支持动态选项：首值、尾值
![image](https://github.com/dataease/dataease/assets/89771514/b4d77437-da38-41e9-baa2-2141f4229ed2)

**Comment by xuwei-fit2cloud** [comment]
下个版本会支持，但只支持首值。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
