### ISSUE TITLE
[Bug]1.18版本 Echarts南丁玫瑰图以及Antv的对称柱状图  点击其他地方以后，视图样式会重置

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#6765]
**DataEase 版本**
v.18.12

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
 Echarts南丁玫瑰图以及Antv的对称柱状图  点击其他地方以后再点视图，视图样式会重置

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/133861755/eaf66a5c-d893-45a1-866d-b926bf7fbc5f)
![image](https://github.com/dataease/dataease/assets/133861755/4d63a6c1-18b8-49f6-b7c8-ba3fa317d56c)
![image](https://github.com/dataease/dataease/assets/133861755/6a8db217-a269-4cf5-b9bf-d992ff705220)
![image](https://github.com/dataease/dataease/assets/133861755/e2c882f4-c387-48f8-b146-a4246c180c33)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题并已修复，将会在下个版本更新；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
