### ISSUE TITLE
[Feature] 允许配置数据集之间的关系

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6767]
**请描述您的需求或者改进建议.**
实现以下效果：
允许类似血缘关系的方式 查看数据集之间的关系

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先内部讨论一下。

**Comment by xuwei-fit2cloud** [comment]
手动配置数据集键与键之间的关联关系，然后形成关系图，对我们来说并不是DataEase的功能范畴，目前没有相关的支持计划。
