### ISSUE TITLE
[Bug]将图表和过滤组件添加到选项卡内过滤组件的默认值筛选将不生效。

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#6777]
**DataEase 版本**
V1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
整包运行

**浏览器版本**
Edge 最新

**Bug 描述**
将图表和过滤组件添加到选项卡内，过滤组件的默认值筛选将不生效。

**Bug 重现步骤(有截图更好)**
1.新建一个明细表
2.新建一个文本过滤组件，配置一个默认值
3.新建一个选项卡组件
4.将明细表和过滤组件移动至选项卡组件
5.保存仪表板，退出并预览
6.过滤组件默认值筛选未生效，手动选择则可以正常过滤
![image](https://github.com/dataease/dataease/assets/30886198/72013902-fe71-4cae-95b2-39cb1c499077)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将会下个版本进行优化

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
