### ISSUE TITLE
[Bug]v2版本开源版浏览器控制台提示 No license record

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#6779]
**DataEase 版本**
v2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
部署开源版本，浏览器控制台提示 No license record
![image](https://github.com/dataease/dataease/assets/89771514/37c4b17f-dd57-4c67-af83-22e512874cd8)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们下个版本优化一下这里；
