### ISSUE TITLE
[Feature]系统通知那边建议加一个全部已读按钮

### ISSUE THREAD

**Issue by cjwts** [dataease/dataease#678]
系统通知那边建议加一个全部已读按钮
![image](https://user-images.githubusercontent.com/30405402/130385711-afd16844-28cb-49cb-a1c6-c1a87bb76e87.png)

**Comment by xuwei-fit2cloud** [comment]
感谢您的反馈，我们会加上此功能

**Comment by xuwei-fit2cloud** [comment]
v1.3.0 版本已支持该功能。
