### ISSUE TITLE
[Feature]2.0版本是否会支持数据源elasticsearch?

### ISSUE THREAD

**Issue by MatrixCheng** [dataease/dataease#6780]
我看1.0版本是支持elasticsearch的，怎么2.0突然不支持的，是出于什么考量吗？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，2.x版本重构使用了calcite技术，我们需要先调研一下。

**Comment by zhcloud** [comment]
请问 2.0 具体有排期支持了吗？

**Comment by tangguangliang** [comment]
同问什么时候支持elasticsearch，另外考虑支持es的时候，可以考虑一下索引按天生成的情况，获取每天最新的索引信息

**Comment by xuwei-fit2cloud** [comment]
短期内还没有开发计划，暂时关闭。
