### ISSUE TITLE
[Question]请问1.18.12版本新增支持动态设置访问路径前缀，在部署时如何修改？

### ISSUE THREAD

**Issue by chirspan** [dataease/dataease#6787]
1.18.12版本新增支持动态设置访问路径前缀，docker部署时如何修改
<img width="376" alt="image" src="https://github.com/dataease/dataease/assets/17754764/3b84b164-12a5-4f94-a645-1903dccca868">

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，先修改下图中的配置文件后，再重新打包部署。
![image](https://github.com/dataease/dataease/assets/84168063/974e512b-e126-4206-aacf-d4e075f177dd)
![image](https://github.com/dataease/dataease/assets/84168063/5cef20bb-89a2-4209-81be-1b0b8b52898e)
