### ISSUE TITLE
[Bug]词云图，词大小和数值不匹配

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6789]
**DataEase 版本**

1.18.12
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

谷歌
**Bug 描述**
使用词云图，当最大的值和最小的值差的较多时，小值之间大小显示差不多

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/052cf219-5c5d-401c-bb42-93fd85f22757)

2.
![image](https://github.com/dataease/dataease/assets/109720729/90f152ae-acbd-45ed-80a1-f2783861a056)

3.

**Comment by linyuiu** [comment]
是不是和这个字号区间设置的有关，差值这么大其实两个小值来讲区别很小，肉眼难以观察到

**Comment by BBchicken-9527** [comment]
感谢反馈，词云图的字体大小是图库自身进行控制的，这个运算的过程目前无法介入；
