### ISSUE TITLE
[Feature]组合图支持堆叠柱状图+ 折线图

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6795]
**请描述您的需求或者改进建议.**
组合图支持堆叠柱状图+ 折线图
![图片](https://github.com/dataease/dataease/assets/48307752/cdefa505-a71d-4c54-8c73-ec5af4523fb9)
antvG2Plot图例：
![图片](https://github.com/dataease/dataease/assets/48307752/e9477801-171b-4b96-86fd-86185be668a2)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前组合图已支持常见的组合类型，因此暂时没有计划拓展其他的组合类型。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前组合图已支持常见的组合类型，因此暂时没有计划拓展其他的组合类型。
