### ISSUE TITLE
[Bug]Oracle 定时同步 8000W 数据时报错

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#6797]
**DataEase 版本**
v1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**

版本 119.0.6045.160（正式版本） （64 位）
**Bug 描述**
创建 SQL 数据集成功的，数据预览没有问题，但是在定时同步报错，是 Oracle数据源 

**Bug 重现步骤(有截图更好)**

![e7eae09edc7c8eb7092c469c0775dde](https://github.com/dataease/dataease/assets/127368807/19005470-615a-4a3c-a0a1-a3e83e768795)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先确认一下。

**Comment by maninhill** [comment]
暂无支持计划。
