### ISSUE TITLE
[Bug]AntV的对称柱状图标签显示被遮盖。

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#6798]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
如图：纵轴标签显示不全
![20231122-162217](https://github.com/dataease/dataease/assets/85436572/d72a1b01-0f53-47b3-a275-160f31f5769c)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，目前已经修复将会在下个版本上线；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
