### ISSUE TITLE
[Bug]视图板块会自动保存

### ISSUE THREAD

**Issue by yaoyuopeng** [dataease/dataease#68]
**DataEase 版本**
v1.0.0-rc2

**浏览器版本**
Chrome 版本 91.0.4472.114（正式版本） （64 位）

**Bug 描述**
在对视图进行编辑时，所进行的每一步操作都被保存，即使没有点击保存按钮。

**Comment by xuwei-fit2cloud** [comment]
DataEase 当前版本的设计是视图会自动保存的。
