### ISSUE TITLE
[Bug]v2版本,starrocks数据查询异常

### ISSUE THREAD

**Issue by Gavin-Zeng** [dataease/dataease#6802]
**DataEase 版本**
2.0

**运行方式(安装包运行 or 源码运行 ?)**
 安装包运行

**浏览器版本**
Chrome 119.0.6045.159

**Bug 描述**
对starrocks支持有点问题？对starrocks数据集查询报sql错误

**Bug 重现步骤(有截图更好)**
![WechatIMG8](https://github.com/dataease/dataease/assets/21352945/bb1f8354-7e87-4aa0-852c-57768ac60a14)
![WechatIMG9](https://github.com/dataease/dataease/assets/21352945/2d1b365f-02eb-4553-9fe7-0e4efca661af)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试的环境没有发现你说的问题，方便看一下后端日志嘛？这样可能方便我们定位到问题的所在；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
