### ISSUE TITLE
[Bug] 1.18.9 升级 1.18.12 ，视图计算字段报错

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6808]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
升级之后，excel 数据集替换数据，execl 结构不变，使用该数据集的视图，以前建立的视图计算字段，发生变化，变成如图所示，字段变成 undinfe

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/151cb4b3-05f7-4739-8c8e-8b10222c6c65)

2.
![image](https://github.com/dataease/dataease/assets/109720729/4a0fc404-80ee-4735-96e7-9070885e9dca)

3.
![image](https://github.com/dataease/dataease/assets/109720729/b647e667-bf33-478b-8643-4935087b14c5)
![image](https://github.com/dataease/dataease/assets/109720729/aa8fabe9-559c-4c53-bdd5-41c44c686e03)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境尝试升级没发现你说的问题，请问有什么后端的异常可以看一下嘛

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
