### ISSUE TITLE
【feature】过滤条件优化

### ISSUE THREAD

**Issue by fengfenga1** [dataease/dataease#6809]
过滤条件支持 2个字段之间相互比较， 比如我有一个表包含fieldA 和 fieldB 字段， 过滤条件配置 fieldA = fieldB

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
短期内还没有相关的支持计划。
