### ISSUE TITLE
[Bug]权限问题，demo用户无权限管理驱动，但可通过接口调用实现驱动添加

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#6812]
**DataEase 版本**
V1.18.12

**Bug 描述**
如图，前台限制了驱动仅管理员可操作，但后台接口则只要有数据源查看权限即可管理。二者不一致。

**Bug 重现步骤(有截图更好)**

![WeChatc7a26f6fb8b1940fa396f24307a70801](https://github.com/dataease/dataease/assets/30886198/ab5f04ce-87e9-4112-b806-4b2e5375783e)
![WeChatb1d412160ba195f25256a1d8f89d2d85](https://github.com/dataease/dataease/assets/30886198/d5ddb456-ec70-4ebb-b2ed-81e79b019b9c)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将在下个版本中修复这个缺陷；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
