### ISSUE TITLE
[Bug]筛选器对web端 tab页数据起作用， 移动端默认过滤不起作用

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#6823]
**DataEase 版本**
V1.18

**Bug 描述**
 筛选器对web端 tab页数据起作用， 移动端默认过滤不起作用

**截图**
<img width="512" alt="wecom-temp-67208-ecff040db41ed420459cd7210ed2aec0" src="https://github.com/dataease/dataease/assets/133861755/4fb78d75-0111-435c-a20f-d946511a8768">

**Comment by BBchicken-9527** [comment]
Duplicate of #6818
