### ISSUE TITLE
[Feature]希望地图的提示信息可以配多个数据值

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#6824]
希望地图的提示信息可以配多个数据值
![wecom-temp-31479-2d408431c7fc987cf2798cd657b85914](https://github.com/dataease/dataease/assets/133861755/1bec1820-3fd0-4b71-863b-71507df3b509)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们尝试一下。

**Comment by xuwei-fit2cloud** [comment]
暂时先不予处理。
