### ISSUE TITLE
[Feature]添加明细表时，字段太多能否搞个一键移动到维度的功能？

### ISSUE THREAD

**Issue by zhangwenkl** [dataease/dataease#6831]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/28699054/47a6585c-2601-4665-b382-e63ae513ae00)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
在1.18.13版本中，维度和指标支持多选拖拽，可以一定程度上解决您的问题。
