### ISSUE TITLE
[Feature] 增加模块放大功能

### ISSUE THREAD

**Issue by kaijie-yu** [dataease/dataease#6834]
**请描述您的需求或者改进建议.**
1.我现在做了一个仪表板，想要这6块，每一块都可以实现放大的功能，现在有没有什么组件可以实现我的这个想法，比如说我把功能用例这3个组件放到一个组件a中，然后这个组件a放大的同时可以把这里面包含的其他3个组件全部放大。
![image](https://github.com/dataease/dataease/assets/55130444/6850d5b9-8b31-48d6-9165-2286e27ce237)

**Comment by xuwei-fit2cloud** [comment]
现在在2.x版本的大屏中是可以支持分组功能的，有分组功能后，才能实现放大功能。
我们会尝试在2.x版本中支持一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
