### ISSUE TITLE
[Bug]仪表板预览时，点击一个视图，视图整个偏移跟旁边的视图重叠

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#6835]
**DataEase 版本**
v.1.18.12

**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**
Chrome 已是最新版本
版本 119.0.6045.160（正式版本） （64 位）

**Bug 描述**
预览的时候点击视图，出现漂移重叠。视图需要靠右边点，测试多次均复现。

**Bug 重现步骤(有截图更好)**
![KGB1J3MF36](https://github.com/dataease/dataease/assets/127368807/8fcd48b5-28cc-4793-b939-686598face0c)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现此类问题，方便给出前端的异常吗方面我们确认问题出处；

**Comment by greenyhsj** [comment]
编辑界面下，进行全屏预览的时候会复现

**Comment by greenyhsj** [comment]
编辑界面下，进行全屏预览的时候会复现

**Comment by BBchicken-9527** [comment]
感谢反馈，可以尝试更新最新的版本看一下，目前测试环境是没有你说的这个情况的；
