### ISSUE TITLE
[Bug]环形图和饼图在图标点击后样式，刷新后会产生变化

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#6836]
DataEase 版本
v.1.18.12

运行方式(安装包运行 or 源码运行 ?)

安装包
浏览器版本
Chrome 已是最新版本
版本 119.0.6045.160（正式版本） （64 位）

Bug 描述
环形图和饼图在图标点击后样式，刷新后会产生变化，饼图和环形图均会，antv是图例消失、echart的引线变成向内

Bug 重现步骤(有截图更好)
环形图：
![chrome_Tln7uMVA6P](https://github.com/dataease/dataease/assets/127368807/1a99b1ea-08b6-4245-8f26-4114657d4bb8)

饼图：
![chrome_7AW5H0fduB](https://github.com/dataease/dataease/assets/127368807/ac17ad3b-7f69-4b87-83bd-1f98019a9252)

**Comment by BBchicken-9527** [comment]
感谢反馈，为相同原因导致，目前已修复，将会在下个版本上线，尽情期待；
Duplicate of #6520
