### ISSUE TITLE
[Feature]地图可以显示指标值吗？

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#6845]
**请描述您的需求或者改进建议.**
目前地图显示标签只能显示维度的省份，如下图所示。 所果想显示省份这个维度下的具体指标值，可以做到吗？
![image](https://github.com/dataease/dataease/assets/27687681/4dfe9eb4-0e80-4b32-a6de-6936f2c947b9)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，标签的显示与标记功能冲突，目前无法进行支持，我们再看下其他的优化方案。
