### ISSUE TITLE
[Feature]AntV组合图支持多指标

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#6853]
**请描述您的需求或者改进建议.**
请问在1.x版本中，AntV组合图后续是否会支持多指标？客户反馈由于ECharts组合图不支持数值格式功能，AntV组合图目前会用的较多一些。希望能有媲美ECharts组合图的功能。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先看一下antv图库是否支持。

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
