### ISSUE TITLE
[Feature]进度环图

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6857]
**请描述您的需求或者改进建议.**

进度环图虽然可以用 环形图 制作，但使用不方便，希望增加一个进度环图，类似水波图配置一个数值即可展示。

<img width="295" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/39ea79e3-3b49-417b-afa4-55b164db8fe9">

https://g2plot.antv.antgroup.com/examples/tiny/ring-progress/#ring-progress-style

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先调研一下。
