### ISSUE TITLE
[Feature]进度条图

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6858]
**请描述您的需求或者改进建议.**
进度条目前可以使用横向柱状图实现，操作不方便，希望增加 进度条 图，像水波图一样，添加一个数值即可展示。
<img width="419" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/7200637f-0cab-4ece-8910-d300f1cc2df3">
https://g2plot.antv.antgroup.com/examples/tiny/progress/#progress-style

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先调研一下。
