### ISSUE TITLE
[Bug]【视图】AntV 指标卡数值格式默认有问题

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#6859]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
在仪表板当中复制一个 AntV 图库的指标卡组件，重新拉入一个数值指标，它的数值格式默认成百分比（第三个选项），我觉得默认成自动（第一个选项）才是对的。
![image](https://github.com/dataease/dataease/assets/24768910/7a33b065-61fc-471a-a9e5-d00a3cb94275)

**Bug 重现步骤(有截图更好)**

https://github.com/dataease/dataease/assets/24768910/3be83602-eca4-4b21-b4a0-9396cd980a9a

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的这个问题，前端是否有什么异常提示呢？或者这个问题可以稳定复现吗？
![image](https://github.com/dataease/dataease/assets/84372766/c9dd1b1b-16c1-4081-95ec-68f900191f77)

**Comment by AndroidBaby1** [comment]
好像确实不是必现，就是有个仪表板复用的图表会这样子，那这个先关闭了，谢谢！
