### ISSUE TITLE
[Feature]时间范围过滤组件，希望支持年、月范围的选择

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#6860]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/89771514/f3f620e6-ad50-4af5-a915-f49f52ba0241)
希望支持年、月范围的选择，不支持支持某日到某日范围的选择
场景举例：
选择年份范围：选择2001年-2006年的范围
选择月份范围：选择1月-9月的范围

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
在目前组件上不太好设计相关交互，暂时不予支持，您可以使用2.x版本。
