### ISSUE TITLE
[Bug]Excel本地数据源添加数据字段后重新替换数据源后丢失sheet

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#6862]
**DataEase 版本**
2.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 118.0.5993.117（正式版本） (arm64)

**Bug 描述**
通过 DataEase 上传 Excel 数据源，数据源包含sheet1、sheet2、sheet3、sheet4，上传后修改本地 Excel 数据文件中的 sheet4，修改方式为添加字段T，并添加补充数据。然后通过DataEase数据源中的替换Excel数据方式，用替换数据方式重新上传修改后的Excel，上传后原Excel数据源丢失sheet4。

**Bug 重现步骤(有截图更好)**
1.通过DataEase上传Excel文件，其中包含sheet1-4多个sheet
2.上传后在DataEase中数据显示正确，然后在本地Excel文件的sheet4添加字段T
3.通过DataEase的替换数据，重新添加字段T的本地Excel文件
4.替换后更新提示保存成功，但是sheet4丢失了

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
