### ISSUE TITLE
[Bug] AntV词云图维度数据缺失

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6865]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
使用词云图的时候，词少了一个，具体看图

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/ea2dde3e-3836-44a2-8267-776a0e679f34)

2.
![image](https://github.com/dataease/dataease/assets/109720729/c752a95f-52ed-48dd-a706-71cf5744888c)
[明细表.xlsx](https://github.com/dataease/dataease/files/13471070/default.xlsx)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，词云图的显示是有图表自身计算产生的结果，你可以通过大小中的字号区间等设置去进行调整达到你想要的效果；
![image](https://github.com/dataease/dataease/assets/84372766/02b3300b-6a2e-4a7f-8a19-9158f08ed69a)
