### ISSUE TITLE
[Bug]StarRocks 嵌套函数提示语法错误

### ISSUE THREAD

**Issue by Xyuncheng** [dataease/dataease#6873]
**DataEase 版本**
v1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
用MySQL 数据库，新增计算字段，是可以函数里面嵌套函数的。 但是在 SR 数据库就不行，用视图数据集也不行，会提示语法错误。（另外用 Excel 数据集也不行）

**Bug 重现步骤(有截图更好)**
1.数据集中新增计算字段：
![cf0b7dee708fa0655695d8ce9042fa5](https://github.com/dataease/dataease/assets/137035261/4b121f6a-c7dd-41a7-a19b-38c47aa6f235)

2.视图计算字段：
![6af76d2797ddf173cb1745fd4bb74c6](https://github.com/dataease/dataease/assets/137035261/ef0f66f2-528e-42a5-8c05-b9d6af9ea91d)

3.同样的语句在 DE 上执行跟直连数据库执行的区别，直连数据库是可以执行的：
<img width="1374" alt="cab177032b2a77e068047fe3da9cbd8" src="https://github.com/dataease/dataease/assets/137035261/a6e4a4ca-6465-40db-a494-797c6f25343f">
<img width="1006" alt="029cc1b21a8fc8d219892de3bd10b2c" src="https://github.com/dataease/dataease/assets/137035261/70f2ed54-b3b8-4905-ae24-c94c65839cbc">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前计算字段因为是嵌套在外层处理的，所以目前无法完成支持，如果处理可能要改变这里的处理方式，我们讨论一下；

**Comment by xuwei-fit2cloud** [comment]
此处目前还不好处理。
