### ISSUE TITLE
[Bug]Echart 的柱状图自适应有问题，堆叠在一起

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#6877]
DataEase 版本
v.1.18.12

运行方式(安装包运行 or 源码运行 ?)

安装包
浏览器版本
Chrome 已是最新版本
版本 119.0.6045.160（正式版本） （64 位）

Bug 描述
Echart 的柱状图自适应有问题，堆叠在一起

Bug 重现步骤(有截图更好)
![chrome_hxJHgh64Y8](https://github.com/dataease/dataease/assets/127368807/a7ffb7d2-95a6-442b-a0ef-a219345fea8c)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，能否看一下前台是否存在异常呢？说这问题是否可以稳定复现？

https://github.com/dataease/dataease/assets/84372766/3f4e6093-795c-4434-98ab-b8606343fdb5

**Comment by greenyhsj** [comment]
![image](https://github.com/dataease/dataease/assets/127368807/b3d86d3d-4eda-43b1-81ed-15670689c27a)
把自适应关掉，之前版本取消自适应固定列宽，拖拉是会自适应的，不会重叠

**Comment by BBchicken-9527** [comment]
感谢反馈，如果你关闭自适应完全可以通过柱宽和柱间距去进行调整，达到你理想的位置，如果你关闭了自适应，这时候你去调整他的大小又希望他自适应，这本身就是一个相冲突的需求。所以我个人并不认为这是一个问题；
