### ISSUE TITLE
[Bug]AntV的分组柱状图，鼠标移上时出现频闪

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#6883]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 119.0.6045.123（正式版本） (x86_64)

**Bug 描述**
使用AntV的分组柱状图，当鼠标移上时出现频闪，这个问题不是必现的，当F12打开浏览器控制台时，此问题基本必现
![image](https://github.com/dataease/dataease/assets/89771514/e4f5fc39-c08d-4fd2-b0aa-efec26d54a73)

视图虽然在频闪刷新，但并没有触发接口的请求，应该是前端问题

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，并且在下个版本将会上线，敬请期待；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
