### ISSUE TITLE
[BUG]横向百分比柱状图，当维度为时间字段时，指标进行排序功能失效

### ISSUE THREAD

**Issue by zhimayuyuan** [dataease/dataease#6886]
**DataEase 版本**
v1.18.11

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**
Google Chrome   版本 119.0.6045.160（正式版本） （64 位）

**Bug 描述**
横向百分比柱状图，当维度为时间字段时，指标进行排序功能失效

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/128681370/a477570e-42d5-490a-876a-fe50e379391f)

**Comment by BBchicken-9527** [comment]
感谢反馈，我这边看应该是堆叠想导致的，指标排序是按照每个分类的总和去计算的，如果你去掉分类是否会回复正常的排序呢？你可以理解为之前一个维度的拉扯变成了两个维度的拉扯，所以看上去感觉不太正确；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
