### ISSUE TITLE
[Feature] 2.0 版本的文本下拉框的确定按钮会在 1.18版本添加上吗？

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6888]
**请描述您的需求或者改进建议.**
1.18 版本的文本下拉，多选时，点击其他区域（其他视图）存在不能收起下拉框的问题，2.0 版本在下拉框上做了“确定”按钮可以解决，1.18 可以做上吗？
<img width="408" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/9c638580-eecc-470f-9aaa-b225d3fec0ce">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，1.x与2.x实现机制不一样，我们先调研并评估一下。

**Comment by xuwei-fit2cloud** [comment]
不能收起的问题新版本已处理，请更新版本。
