### ISSUE TITLE
[Bug] 关联数据集字段选择问题

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6894]
**DataEase 版本**
v1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
关联数据集字段选择问题

**Bug 重现步骤(有截图更好)**
1. 添加关联数据集，选择 A 表 a1，a2，a3 字段，B 表 b1 字段，用 a1 和 b1 关联
![image](https://github.com/dataease/dataease/assets/45852479/e6644140-8ab2-4c80-ac48-f5e2128acc37)
2. 修改 A 表字段，减少为 a1
3. 编辑关联数据集，报错
<img width="952" alt="image" src="https://github.com/dataease/dataease/assets/45852479/fb39f857-98ff-4869-beee-cc651f8d7281">
<img width="782" alt="image" src="https://github.com/dataease/dataease/assets/45852479/ebb79626-eba9-4e7e-ae06-294f852a55fe">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将在下个版本进行修复；

**Comment by BBchicken-9527** [comment]
目前修复了提示信息没有传过来的问题，显示数量和实际不正确是为了方便提示用户查看的表做了修改导致（考虑到关联表过多的的情况），所以这里的逻辑没有变化，如果想继续使用这张表只需要编辑修改过的表的显示字段即可正常使用；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
