### ISSUE TITLE
管理员添加新用户时， 界面没有角色下拉框

### ISSUE THREAD

**Issue by lnts2015** [dataease/dataease#6898]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
在线安装

**浏览器版本**
版本 119.0.6045.160（正式版本） （64 位）

**Bug 描述**
现象 ： 
![image](https://github.com/dataease/dataease/assets/6037915/d7b70504-fe91-419f-a451-22ccfc1d98e3)

应该是这样的：
![image](https://github.com/dataease/dataease/assets/6037915/478109b8-5c47-4c60-a582-cedcea0c8b81)

**Bug 重现步骤(有截图更好)**
1.  如上图
2. 使用管理角色登陆

**Comment by xuwei-fit2cloud** [comment]
你好，企业版才有角色选择的功能，社区版是没有的。

**Comment by lnts2015** [comment]
@xuwei-fit2cloud 明白。感谢
