### ISSUE TITLE
[Bug]对繁体中文的国际化没有完成

### ISSUE THREAD

**Issue by yaoyuopeng** [dataease/dataease#69]
**DataEase 版本**
v1.0.0-rc2

**浏览器版本**
Chrome 版本 91.0.4472.114（正式版本） （64 位）

**Bug 描述**
![image](https://user-images.githubusercontent.com/82791515/123564970-e5f21280-d7ed-11eb-8326-af366e270940.png)

**Comment by xuwei-fit2cloud** [comment]
感谢你提供的信息，我们会在下一个版本中修复。

**Comment by xuwei-fit2cloud** [comment]
v1.0.1 版本已修复并发布
