### ISSUE TITLE
[Feature] echart地图能否支持标签参数显示？

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#6908]
**请描述您的需求或者改进建议.**
echart地图中，目前标签只能显示维度信息，能否像汽泡地图一样，在标签属性列表中增加“内容格式”一项，可以用{a}, {b}, {c}, {d}控制输入项。 
另外，如果“内容格式”输出项是{c}，能否支持条件控制颜色？ 比如正数 +10%， 负数 -5%显示不同颜色
![image](https://github.com/dataease/dataease/assets/27687681/2f9c8a81-fd74-46fa-8df2-55afc7648d1b)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前与地图的标记功能有冲突，我们再看下其他的解决方案。

**Comment by xuwei-fit2cloud** [comment]
暂时还没有比较好的方案。
