### ISSUE TITLE
[Bug]使用数据库数据集新增计算字段，如果点击引用字段输入框中有信息，保存时会提示字段表达式语法错误。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#6919]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome118

**Bug 描述**

使用数据库数据集新增计算字段，如果点击引用字段输入框中有信息，保存时会提示字段表达式语法错误。
**Bug 重现步骤(有截图更好)**
1.使用数据库数据集新增计算字段
2.如果点击引用字段输入框中有信息
3.保存时会提示字段表达式语法错误
<img width="559" alt="1efe0073ba2a4d944ef66e7677ddd07" src="https://github.com/dataease/dataease/assets/83771182/25cdcc53-0b8b-4d9a-b4d7-914fdcb013c2">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
