### ISSUE TITLE
[Feature]视图所在的画布，能否调整边距？

### ISSUE THREAD

**Issue by zhanggefei** [dataease/dataease#693]
**请描述您的需求或者改进建议.**
排版时有的画布边距太大，能否调整边距。如图
<img width="1279" alt="WechatIMG1665" src="https://user-images.githubusercontent.com/37612532/130625840-8c8bc01b-3540-43f1-98c1-29a44f4ade4a.png">

**Comment by yayanpei** [comment]
非常感谢您的反馈，我们先内部讨论一下。

**Comment by xuwei-fit2cloud** [comment]
v1.4.0 版本增加antv图库，边距控制比echarts图库要好些，可以体验一下。
