### ISSUE TITLE
[Feature]视图时间过滤组件类型希望不要转换

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#6931]
**请描述您的需求或者改进建议.**
视图上使用了时间过滤组件，后端数据库最终生成sql 会做截图中装换，这种装换会影响性能，能否不进行转换。

![image](https://github.com/dataease/dataease/assets/109720729/ebce8c59-1be8-4c85-a6dd-71877ccf425d)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们尝试下，这个跟数据源所用的数据库有关，可能有的数据库可以转换，有的数据库不可以。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
