### ISSUE TITLE
[Feature]明细表格控制是否有”合计行“。

### ISSUE THREAD

**Issue by zhanggefei** [dataease/dataease#694]
**请描述您的需求或者改进建议.**
有的明细表不需要求和，如图。
<img width="772" alt="WechatIMG1666" src="https://user-images.githubusercontent.com/37612532/130654351-5e38a93d-0ea6-43ad-aa0b-ecef3f64e960.png">

**Comment by yayanpei** [comment]
非常感谢您的反馈，我们规划在V1.3.0版本实现该需求。

**Comment by xuwei-fit2cloud** [comment]
v1.3.0中表格分为明细表和汇总表，明细表不带合计项
