### ISSUE TITLE
[Feature]下拉选择框增加小建议

### ISSUE THREAD

**Issue by kkljcf** [dataease/dataease#6954]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/125198800/d8f658d2-0efb-4fc0-8f32-91b33c8161b6)
下拉 选择框，
建议1、增加一个反选按钮
建议2、全选，反选按钮，固定在头部，下方下拉框滑动，全选按钮始终保持在顶部可见。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，全选按钮已经支持，当前暂时没有计划支持反选。
