### ISSUE TITLE
[Bug]定时报告添加图片推送邮件，图片会裂开

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#6956]
DataEase 版本
v.1.18.12

运行方式(安装包运行 or 源码运行 ?)

安装包

浏览器版本
Chrome 已是最新版本
版本 119.0.6045.160（正式版本） （64 位）

**Bug 描述**
定时报告添加图片推送邮件，图片会裂开，在定时报告的保持预览是正常的

**Bug 重现步骤(有截图更好)**
图片链接：
http://pic.soutu123.com/back_pic/04/33/47/1158454b888241c.jpg%21/fw/700/quality/90/unsharp/true/compress/true
预览正常
![image](https://github.com/dataease/dataease/assets/127368807/f002a469-9ef5-4765-b6ad-f352df0f11b2)

推送失败
![image](https://github.com/dataease/dataease/assets/127368807/c485cbd3-d029-49a8-9a75-b406a9a45554)

**Comment by BBchicken-9527** [comment]
感谢反馈，我这边测试没有发现你说的问题，因为你给的地址我这边尝试根本添加不进去这张照片我就找了一张别的照片，看起来是没有问题的，你更换其他照片是否还会出现这种问题呢？
![image](https://github.com/dataease/dataease/assets/84372766/43ff78fd-e055-4acd-a5db-ec3fb5c8c2dd)

**Comment by greenyhsj** [comment]
有些图片可以发送正常，有些图片编辑时正常发送裂开，是什么原因？图片地址上有什么要求？
