### ISSUE TITLE
[Bug]数据集预览时间远大于执行记录中显示的时间

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6958]
**DataEase 版本**
v1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
chrome

**Bug 描述**
SQL 数据集（SQL 比较复杂）执行预览数据时，大概 5 秒左右才显示数据（查询结果数据共有一行），但在 SQL数据集界面的执行记录时间显示 10ms，这是为什么？中间有什么逻辑处理占用了显示预览数据的时长吗？
<img width="1667" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/af840758-3eb9-4618-b5ab-158ba29d4689">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，这里显示的时间为数据库执行sql的查询时间，而你看到数据的时间包含了请求的传输；

**Comment by mfanoffice** [comment]
> 感谢反馈，这里显示的时间为数据库执行sql的查询时间，而你看到数据的时间包含了请求的传输；

查询结果数据量不大，只有一条数据，用户体验不太好，请求和传输的时间还有没有优化的空间？

**Comment by BBchicken-9527** [comment]
emm...你肉眼看到数据的时间收到了很多方面的影响的，比如网络和服务，所以不是单纯的应用层面优化就能行的；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
