### ISSUE TITLE
[Feature] 快速计算支持组内占比

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6965]
**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前快速计算已经支持了组内占比，入口请见下图所示：
<img width="350" alt="image" src="https://github.com/dataease/dataease/assets/84168063/b72e47e9-72a4-480e-8ee2-4c5c64530860">
