### ISSUE TITLE
[Feature] 动态排序图效果

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#6975]
**请描述您的需求或者改进建议.**
https://github.com/dataease/dataease/assets/45852479/b5e971d1-23fd-46a5-ba7e-ac8d9077d65e
动态排序图支持如上效果，在切换分组时，视图不会整个刷新

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们当前暂时没有计划进行支持，需求先记录并放进2.x的需求池中。
