### ISSUE TITLE
[Bug]模版市场编辑文本组件时页面卡死

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#6977]
**DataEase 版本**
v1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome/firefox

**Bug 描述**
模版市场中的 “销售数据监控中心” 模版编辑文字组件时，页面会卡死，多次复现，与之前的 issue （https://github.com/dataease/dataease/issues/5258）现象一致。

<img width="1659" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/5a218d8b-9f42-4cbd-a9e4-b492c60e9520">
<img width="1268" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/62e8a8e7-c654-40ab-9746-5bcff816ae03">

<img width="1649" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/0fc2fe44-20a9-4c14-a45a-c8e55e1a530d">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
