### ISSUE TITLE
[Bug]定时报告推送企微，点击详情图片裂开

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#6984]
DataEase 版本
v.1.18.12

运行方式(安装包运行 or 源码运行 ?)

安装包

浏览器版本
Chrome 已是最新版本
版本 119.0.6045.160（正式版本） （64 位）

Bug 描述
定时报告推送企微后，推送提醒正常，但是点击详情图片裂开，需要鼠标单独点击图片才能看到具体内容

Bug 重现步骤(有截图更好)
<img width="435" alt="1701669767690" src="https://github.com/dataease/dataease/assets/127368807/c82b6739-520a-4e95-9425-bc38e3b50c7c">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有复现你说的问题，请问是必现的嘛？

**Comment by greenyhsj** [comment]
最新测试，必现。多个账号都一样
<img width="563" alt="93c5b74b8d5b6ef8bfc12fbe2b7d52e" src="https://github.com/dataease/dataease/assets/127368807/a0d95300-f19b-4fb3-a9a2-aaff79f36553">

**Comment by BBchicken-9527** [comment]
感谢反馈，有环境可以让我们看一下吗？目前测试环境是没有发现这种情况的；

**Comment by greenyhsj** [comment]
可以提供远程测试
