### ISSUE TITLE
[Bug]【视图】符号地图标签聚合不去重

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#6988]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
符号地图标签聚合不去重，如下截图（供应商名称）：
<img width="272" alt="image" src="https://github.com/dataease/dataease/assets/24768910/491959d5-b81f-4158-a171-250de109ebe1">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行优化；

**Comment by xuwei-fit2cloud** [comment]
v1.18.13版本已处理，请更新版本。
