### ISSUE TITLE
[Bug]【X-Pack】通过 API 接口创建的组织，前台删除不掉

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#6989]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本谷歌浏览器

**Bug 描述**
通过 API 接口创建的组织，前台删除不掉

**Bug 重现步骤(有截图更好)**
1.提示删除成功，但是组织还在：
接口调用：
![image](https://github.com/dataease/dataease/assets/24768910/59cedfd4-d4c4-4991-b662-d295fac218be)
界面显示：
![image](https://github.com/dataease/dataease/assets/24768910/3fb4c02e-cd91-4fd5-b09c-4cf477880e35)

2.一些其他辅助测试的截图，执行删除时的一些后台信息：
![image](https://github.com/dataease/dataease/assets/24768910/c33824b3-742e-4f7d-8761-2cfb24fb46dd)
![image](https://github.com/dataease/dataease/assets/24768910/23bf0a22-4d46-446f-ae5b-5c57da4b7a4f)
![image](https://github.com/dataease/dataease/assets/24768910/8dc46af3-5771-4ffd-a892-360158be3278)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，接口饭回成功的话应该是删掉了，受累看一下search接口里面有你删除的数据吗？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
