### ISSUE TITLE
视图不支持重命名

### ISSUE THREAD

**Issue by plateauandsp** [dataease/dataease#7]
视图不支持重命名，如果修改视图名称，只能删除重新添加
![image](https://user-images.githubusercontent.com/30932762/123370329-177e9a00-d5b2-11eb-9b95-d35e3bf6e271.png)

**Comment by fitchibing** [comment]
同上 没找到在哪里rename

**Comment by xuwei-fit2cloud** [comment]
我们处理一下，v1.1.0 版本里加上。

**Comment by XiaJunjie2020** [comment]
视图标题，即名称

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #74

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已支持
