### ISSUE TITLE
[Feature]仪表板加载的遮罩层希望支持设置颜色，以及设置加载提示的文本内容

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#7015]
**请描述您的需求或者改进建议.**
目前加载仪表板视图时，默认会有一层白色的遮罩层
仪表板加载的遮罩层希望支持设置颜色，以及支持设置加载提示的文本内容，如：加载中，请稍后。。。
<img width="1218" alt="image" src="https://github.com/dataease/dataease/assets/89771514/7940bfb3-a297-47f7-9f07-4597aef4ae59">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，暂时没有计划支持该设置项。
