### ISSUE TITLE
[Bug] sql数据集设置参数后，日期控件传入参数不生效

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#7023]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
 119.0.6045.200（正式版本） （64 位）

**Bug 描述**
sql数据集设置参数后，在仪表板的时间范围控件中设置参数后，实际查询时，该事件范围参数没有生效。
在仪表板中
**Bug 重现步骤(有截图更好)**
1.建了一个sql数据集如下图
![image](https://github.com/dataease/dataease/assets/26103277/f5f2aa35-03ac-40e2-b8cc-a52c347b902f)
![image](https://github.com/dataease/dataease/assets/26103277/fa28ddbb-b428-4b7e-a0af-35c5c7471dec)
2.在仪表板中的范围控件设置如下图
![image](https://github.com/dataease/dataease/assets/26103277/9601a745-47ee-4d1a-991d-badc538783bb)
3.新建一个汇总表视图，切换时间控件参数，发现参数并没有生效，**但是在sql数据集中去掉type=${type}参数后是生效的**。

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你你使用的是什么数据库呢？

**Comment by hw872715125** [comment]
我使用的是mysql和doris

**Comment by hw872715125** [comment]
请问有结果了么 @BBchicken-9527 @fit2cloudrd

**Comment by BBchicken-9527** [comment]
感谢反馈，应该是参数化后因为后面也做了参数化导致都是bi=bi，我们看看有没有优化的方案；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
