### ISSUE TITLE
[Feature]使用 http2 协议

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#7027]
**请描述您的需求或者改进建议.**
我们发现浏览器请求服务端使用的时 http1.1 协议；
而 http1.1 协议相比 http2 协议有很多弊端，http2 引入了一些新的特性和优化，以提高性能和效率；
目前我们使用Nginx 代理，实现浏览器到 Nginx 服务器之间实现了 http2 协议，Nginx 到后端服务还是 http1.1 ，在性能上仍然无法达到全链路实现 http2 协议的效果。
所以在产品层面上能否实现 http2 协议？

**Comment by xuwei-fit2cloud** [comment]
主要性能瓶颈不在nginx服务到后端服务之间，主要瓶颈在浏览器到nginx，所以目前没有相关调整计划。
