### ISSUE TITLE
[Bug] v2版本选择 Excel数据源 >自定义SQL > 编写行转列SQL 运行报错。

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#7041]
**DataEase 版本**
V2.0.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome 119.0.6045.199（正式版本） (arm64)

**Bug 描述**
行转列 SQL执行不成功并报错

**Bug 重现步骤(有截图更好)**
1. 提供离线数据供测试（在附件）
2. 行转列SQL：
SELECT
  student_id,
  MAX(CASE WHEN subject = 'Math' THEN score END) AS "Math",
  MAX(CASE WHEN subject = 'Science' THEN score END) AS "Science",
  MAX(CASE WHEN subject = 'History' THEN score END) AS "History"
FROM scores
GROUP BY student_id;
[data_20231205_144748.csv](https://github.com/dataease/dataease/files/13577756/data_20231205_144748.csv)

**Comment by BBchicken-9527** [comment]
感谢反馈，新版本的数据集统一了sql的语法方式，函数使用和语法上是calcite的语法和函数，calcite应该是不支持then后面跟数据字段，可以尝试使用固定字段；
