### ISSUE TITLE
[Bug]SQL传参“数据集预览时全局生效”未在仪表板生效

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#7045]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
具体情况如图所示：在数据集传参页面设置了“数据集预览时全局生效”，仍未在仪表板生效。
![WeChat9305a05a2d296d09c624be0dd4da8347](https://github.com/dataease/dataease/assets/85436572/132ee690-ec49-4580-8e03-db7e785a6158)
![WeChatcbd8c1b25787d0d35444e625425de265](https://github.com/dataease/dataease/assets/85436572/1237eb25-1b5d-4351-9868-2ccc068356cd)
![WeChatadacce510596994f9a30f0bd31880c1b](https://github.com/dataease/dataease/assets/85436572/bdffcd0a-2d5a-4fe6-ac30-d3a47659537c)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，这里是只在数据集预览的时候生效，当进入仪表板的时候还是会全部显示的，如果需要对数据进行控制可根据行列权限进行控制，这样可能会更安全；
