### ISSUE TITLE
[Bug]在计算字段里使用round函数，显示结果异常

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#7046]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
使用ECharts组合图，添加计算字段，如下：
![image](https://github.com/dataease/dataease/assets/85436572/1d126232-d3d2-486e-b64e-49ee1db4c977)
显示结果如下：
![127241701850547_ pic](https://github.com/dataease/dataease/assets/85436572/ef08fdd9-35fb-4de6-a248-8b73b115ae5c)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，应该是已知的一个问题，你看详情中的数据显示的是否正确，我们尝试看看是否可以处理；
