### ISSUE TITLE
[Bug]筛选组件添加默认值和添加查询按钮时。在编辑页面、仪表板预览区、全屏预览 显示不一致

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#7047]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
在仪表板预览区，选项卡内视图未进行筛选，选项卡外筛选。
![WeChatb7c741f7bf89ae0c95827e21ce6b8059](https://github.com/dataease/dataease/assets/85436572/f086d390-d335-48b3-ba12-cb33cb428dff)
在编辑页面，依然是选项卡内视图未进行筛选，选项卡外筛选。
![WeChat43ead972a04a6461d7d31804f1e7d617](https://github.com/dataease/dataease/assets/85436572/de7d5b99-1576-4ec6-915d-4c3074b55ea1)
在全屏预览界面，均未筛选，默认值失效。
![WeChat166c6a5a4d74ed7d0750bbb68987e161](https://github.com/dataease/dataease/assets/85436572/eeaa22a6-6b1b-46aa-be6c-8228c660cd80)
qi
期望形式：仪表板预览区、编辑页面以及全屏预览页面在设置默认值后 均进行筛选。
**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，请问按钮你有做什么设置吗？

**Comment by hw872715125** [comment]
我也遇到了这个问题，放一个按钮是因为查询条件类型过多，类似有七八个以上的查询过滤条件，不想每修改一下过滤条件时就触发查询，所以加了一个查询按钮，当所有的查询条件修改完成后再点击查询按钮触发查询。按钮设置是默认值，拖入的时候是什么就是什么，没有手动做任何设置。

**Comment by BBchicken-9527** [comment]
> 我也遇到了这个问题，放一个按钮是因为查询条件类型过多，类似有七八个以上的查询过滤条件，不想每修改一下过滤条件时就触发查询，所以加了一个查询按钮，当所有的查询条件修改完成后再点击查询按钮触发查询。按钮设置是默认值，拖入的时候是什么就是什么，没有手动做任何设置。

感谢反馈，看你们的描述应该是全屏预览的时候接口请求顺序存在一点儿问题，最新的版本这里做了一点优化，你可以尝试升级看看，应该不会存在这里的问题了；
