### ISSUE TITLE
[Bug] 使用echarts的表格，无法选中表格内容进行复制

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#7050]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

最新版本
**Bug 描述**

我使用了echarts的表格，想复制表格内的部分内容，但是却无法选中，导致无法复制。

**Comment by BBchicken-9527** [comment]
感谢反馈，方便详细说明一下吗？你的意思是复制数据字段吗？

**Comment by hw872715125** [comment]
复制表格内的数据，如图
![image](https://github.com/dataease/dataease/assets/26103277/e658d722-7cf7-4117-b5cd-5410653eee51)

**Comment by hw872715125** [comment]
无法选中表格内容

**Comment by BBchicken-9527** [comment]
感谢反馈，可以点击图标右上方详情进行选中的，图表本身是无法选中的；

**Comment by hw872715125** [comment]
有点无法理解，为什么图表要设计成无法选中的

**Comment by BBchicken-9527** [comment]
emm，可以将表格看成图片，所以长按无法选择文字；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，下个版本这里会做一定的优化，应该可以满足你的需求，期待一下，感谢你的反馈与支持；
