### ISSUE TITLE
[Bug]设置联动后，查询时没有带过滤条件

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#7061]
**DataEase 版本**
1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
119.0.6045.200（正式版本） （64 位）

**Bug 描述**
对视图设置联动后，点击进行联动查询时，没有设置联动的视图查询数据时没有带过滤条件。

**Bug 重现步骤(有截图更好)**
1.三个数据集的数据如下图
![image](https://github.com/dataease/dataease/assets/26103277/19f37fc5-eead-41ec-a7dc-d68d2755657b)
![image](https://github.com/dataease/dataease/assets/26103277/756021ae-0b2f-4ae1-8009-5d39b4f2702d)
![image](https://github.com/dataease/dataease/assets/26103277/c0e9fca6-0a40-47ba-a68c-98a81f6a0fbf)
2.仪表板及过滤条件设置如下图
![image](https://github.com/dataease/dataease/assets/26103277/756a8c73-f9be-4b57-a5c0-b9c66752964e)
![image](https://github.com/dataease/dataease/assets/26103277/4daffa2a-6668-4d96-a4d5-919a68464c82)
对新建视图设置联动，联动新建视图1，如下图。设置完成后直接保存退出到预览仪表板界面。
![image](https://github.com/dataease/dataease/assets/26103277/29e194a2-6756-4fa7-a057-bbb966b13966)
3.点击新建视图中的任意一项，联动查询后，新建视图1和新建视图2的结果显示，此次查询并没有使用上面的过滤条件即【研发部】，如下图：
![image](https://github.com/dataease/dataease/assets/26103277/67c82b96-8aae-48aa-ba65-b2770114dcfd)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将会在下个版本进行修改；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
