### ISSUE TITLE
[Feature] 仪表板中仪表很多（>40）且单条查询为2~8秒，前端请求同时进行，数据仓库压力大且容易超时异常

### ISSUE THREAD

**Issue by wangxiaominger** [dataease/dataease#7065]
**请描述您的需求或者改进建议.**
由于展示需要，我们在单个仪表板集成了大量仪表盘及数据表格，我发现在使用时，每个人前端请求没有请求队列，而是一次性将所有数据请求全部发送出去，这样在多人同时使用的时候，就会导致数据库短时间内载荷上升，极大概率会使数据库内存占用超90%，造成超时不可用，前端请求数量能不能做个合理的限制（下图选了个相对少的请求以及错误截图），多谢
<img width="386" alt="image" src="https://github.com/dataease/dataease/assets/49179468/e5521476-e9fd-4f57-b417-e2384540c782">
<img width="1110" alt="image" src="https://github.com/dataease/dataease/assets/49179468/f6bf3d22-6e44-4628-bf5d-9079ed35fb59">
![image](https://github.com/dataease/dataease/assets/49179468/294c0d29-6e77-48ee-92d8-ef3c920d05b5)
![image](https://github.com/dataease/dataease/assets/49179468/befa705f-3af1-4f84-afcd-054df63a62dc)

**Comment by wangxiaominger** [comment]
我们临时的解决方式是，把仪表分类放到多个选项卡内，按模块切换选项卡的方式限制仪表请求数量，这似乎不是长久之计。。。虽然挺好用

**Comment by xuwei-fit2cloud** [comment]
如果数仓性能有限的话，可以试试限制数据源的连接池大小？

**Comment by wangxiaominger** [comment]
好的，多谢
