### ISSUE TITLE
[Bug]外观配置登陆页面右侧图片按建议尺寸 500*450 设置后有白边

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#7066]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
![iShot_2023-12-18_11 24 01](https://github.com/dataease/dataease/assets/89771514/c1b7518f-42c4-4726-ab53-8c9a39f7307b)
![iShot_2023-12-18_11 24 16](https://github.com/dataease/dataease/assets/89771514/c9264f70-eefc-4c52-bdc9-6e29148317f8)

![image](https://github.com/dataease/dataease/assets/89771514/8c895178-6671-4878-b22d-594c9ee129e5)

**Comment by ZhaoQian1222** [comment]
实际应该是640*520，是页面提示的问题还是图片没有自适应的问题？

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
