### ISSUE TITLE
页面加载时增加正在加载提示,比如在转的图形[Feature]

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#7068]
页面加载时增加正在加载提示,比如在转的图形. 某些页面打开比较久，用户不知道在加载。 出现长时间的白屏问题。 特别是内嵌报表.

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们加一下。

**Comment by yayanpei-fit2cloud** [comment]
优化已经完成，请关注下1月初的新版本发布。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，仪表板整体的遮罩，会在1月初的版本中进行优化。视图的加载提示，您先确认下在仪表板配置中是否打开。如下图所示。
<img width="357" alt="image" src="https://github.com/dataease/dataease/assets/84168063/ee260073-5469-4dc0-b973-dfb7fd719387">

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
