### ISSUE TITLE
筛选框支持多个字段展示，并且能支持多个字段传递参数。支持下拉树，支持文本列表[Feature]

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#7070]
**请描述您的需求或者改进建议.**
筛选框支持多个字段展示，并且能支持多个字段传递参数。支持下拉树，支持文本列表[Feature]
比如现在很多业务模块都是三级的，需要选到1级模块，展开然后再选二级。 最后按三级模块去 传递参数过滤数据。 
为了灵活，最好能支持多个参数的传递.

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
当前下拉树在传递参数时，已经会把多级参数同时进行传递的，您可以试试。
