### ISSUE TITLE
[Feature]视图计算字段参与二次计算

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#7072]
**请描述您的需求或者改进建议.**
看了新版本1.18.13发布了数据集计算字段支持二次计算的功能，期望视图计算字段也可以支持二次计算。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
在当前的架构上不太好支持，目前没有开发计划。
