### ISSUE TITLE
[Bug]tab选项卡隐藏标题后无法保存仪表板

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#7082]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**

**Bug 描述**

给tab选项卡的标题设置隐藏后，无法保存仪表板，右上角的保存按钮为不可点击状态。
**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，问题将会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
