### ISSUE TITLE
[Bug]视图过滤会额外过滤掉空数据

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#7085]
**DataEase 版本**
v1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome firefox

**Bug 描述**
表中有空数据
<img width="1075" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/0ffc00fc-beea-4eec-995a-73df8e5a0938">
视图过滤添加不等于 aaa
<img width="1382" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/52b87981-d280-4d61-80fb-e1b4f243071d">
空数据没有了，希望只过滤掉 aaa, 空数据不影响
<img width="1062" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/fe6d1bc1-89d1-4728-8377-b183cf4de295">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，null正常的sql逻辑中是会被正常过滤的，因为在数据库底层null它并不是一个值，而是没有值，所以会过滤掉null；
