### ISSUE TITLE
[Bug]明细表下拉模式，下面的横向滚动条鼠标无法点击拖动

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#7086]
**DataEase 版本**
v1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome Firefox

**Bug 描述**
![图片](https://github.com/dataease/dataease/assets/48307752/37197903-8933-4bc1-adab-25ce50272c5a)
明细表下拉模式，下面的横向滚动条，鼠标无法点击拖动

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，编辑状态下由于图表位置的不确定性，所以四边都是触发移动的事件，所以在编辑状态下靠近四边是无法进行表格内的操作的；
