### ISSUE TITLE
前端工程run serve报错，TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by gtrgeg** [dataease/dataease#7088]
![image](https://github.com/dataease/dataease/assets/47472797/ad1a43a6-ed82-4643-88ed-f257d89cef21)
问题如图，执行npm run serve的时候卡在这一步执行不下去了，提示：TypeError: this.getOptions is not a function
    at runMicrotasks (<anonymous>)

**Comment by maninhill** [comment]
我们这边暂无法复现，预计是本地环境差异导致，建议自行 Google 解决。
