### ISSUE TITLE
[Feature]文本下拉组件可以支持过滤null和空串

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#7089]
**请描述您的需求或者改进建议.**
期望文本下拉组件可以支持过滤null和空串

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
建议您通过新建计算字段来处理null和空串数据，这样de话，在下拉选择中出现的选择内容可读性也会强很多。
