### ISSUE TITLE
[Feature]过滤组件必填改进建议

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#7091]
**请描述您的需求或者改进建议.**
1.18.13版本，在过滤组件中增加了“必填”配置，勾选时，需要配置默认值才能保存。 在多数表格类的查询业务场景中，默认值是未知的或不确定的。 这里能否优化为，保存时不去校验默认值？ 如果过滤组件勾选了必填项，过滤组件值为空的时候，不查询，填值了才去查？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时保持现有的逻辑。
