### ISSUE TITLE
版本2安装问题

### ISSUE THREAD

**Issue by alifzl** [dataease/dataease#7097]
亲爱的朋友们，为你们在 dataease 版本 2 上所做的出色工作而欢呼吧。 我只是想问一下有没有2.x版本的源代码编译文档？ 因为我想从`https://dataease.io/docs/v2/` 检查编译过程，但我没有找到类似于1.18.x版本的文档。 你能帮我吗？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，文档请参考：https://dataease.io/docs/v2/installation/offline_INSTL_and_UPG/
