### ISSUE TITLE
[Bug]无法正常启动backend jar包

### ISSUE THREAD

**Issue by SevenCham** [dataease/dataease#7099]
**DataEase 版本**

dataease1.18.13
**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**

**Bug 描述**
后端代码打包后无法正常启动，其他版本的正常可以启动

**Bug 重现步骤(有截图更好)**

![98d7fb669df9bbe3d6a02c81aebd93011401f1a1](https://github.com/dataease/dataease/assets/31249168/e7865471-282c-40b4-8ae0-524cbd103049)

**Comment by BBchicken-9527** [comment]
感谢反馈，由于你是源码运行，不确定你是否改动和以及打包方式都有可能存在问题，建议你加入我们的交流群，上面有非常专业的同学会实时的回复你的问题，方便你快速并精准的定位到你的问题所在；
