### ISSUE TITLE
[Feature]批量操作优化建议

### ISSUE THREAD

**Issue by yaoyuopeng** [dataease/dataease#71]
**请描述您的需求或者改进建议.**
建议增加批量选择仪表板进行分享、批量勾选视图移动到其他文件夹、以及批量删除等操作。

**Comment by yayanpei** [comment]
感谢您的反馈，您的建议是我们改进的方向

**Comment by xuwei-fit2cloud** [comment]
视图的功能已经合并到仪表板中，且已支持批量选择。
视图隶属于仪表板，删除仪表板时，对应的所有视图也会被批量删除。
关于仪表板的批量分享，目前还没有相关计划。
