### ISSUE TITLE
[Bug]日期函数BUG

### ISSUE THREAD

**Issue by China-BlueFat** [dataease/dataease#7100]
**DataEase 版本**
V1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
最新版EDGE

**Bug 描述**
升级到1.18.13版本后，在数据集中使用任何日期函数时，都无法保存及运行。如果将日期函数换成准确的值，就没问题。我在我这里的正式机和测试机都是一样的结果。现在的状态是不更改语句中日期函数情况下，点击数据集能按照默认时间来查出东西，如果在仪表盘更改日期函数值，那么就无法查询和保存，报错：net.sf.jsqlparser.parser.TokenMgrException: Lexical error at line 1, column 16. Encountered: '38144' (38144),。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/26730667/4da2a404-dc77-4484-9f01-cc2fbded1bf2)如图，这个数据集是在更新前建好的，当我在数据集中点击之后能查询结果出来。

2.
![image](https://github.com/dataease/dataease/assets/26730667/f43af80f-930c-43c5-a42f-34e6a70ed914)
进入编辑页面后，不修改语句的情况下，点运行，直接报这个错。但是，把日期函数改成准确日期，就可以正常运行。
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，方便将完整的sql语句看一下嘛？你用的是mysql数据源是吧？

**Comment by China-BlueFat** [comment]
SELECT o.VBELN 销售单号,
			COALESCE(d.name,s.name) 经销商名称,
      COALESCE(c.name,ovl.customer_person) 客户名称,
			m.name 生产基地,
			CASE WHEN h.erp_order_no IS NULL THEN '未付款' 
				ELSE DATE_FORMAT(h.create_time,'%Y-%m-%d')
			END AS 付款时间,
			CASE o.OSTAT WHEN 5 THEN '生产中' 
				WHEN 10 THEN '已入库'
				WHEN 'created' THEN '上传订单'
				WHEN 'auditPlan' THEN '审图(方案)'
				WHEN 'auditHole' THEN '审图(审孔)'
				WHEN 'beforeEnd' THEN '确认下单'
				WHEN 'pushOrder' THEN '推单'
				WHEN 'orderOffer' THEN '报价'
				WHEN 'judgeEntry' THEN '判定录入'
				WHEN 'placeOrder' THEN '下单'
				WHEN 'orderReview' THEN '订单评审'
				WHEN 'confirmReceipt' THEN '确认收款'
				WHEN 'dealerConfirmation' THEN '经销商确认'
			END AS 订单状态,
			e.KWERT 金额
FROM order_vbak o
LEFT JOIN oppty_customer c ON o.customer_id = c.customer_no
LEFT JOIN order_push_history h ON o.factory_contract_no = h.erp_order_no
LEFT JOIN partner_dealer d ON o.shop_code = d.code
LEFT JOIN partner_straight_shop s ON o.shop_code = s.code
LEFT JOIN order_vbak_logistics ovl ON o.VBELN = ovl.vbeln
LEFT JOIN (SELECT KWERT, 
								CASE WHEN KNUMV REGEXP 'R|U|V|Z' THEN SUBSTRING(KNUMV,1,10)
									WHEN KNUMV REGEXP 'D|E|M|Y' THEN SUBSTRING(KNUMV,1,11)
								END KNUMV 
						FROM order_prcd_elements 
						WHERE KWERT != 0 GROUP BY KNUMV) e 
						ON o.VBELN = e.KNUMV
LEFT JOIN (SELECT * FROM order_vbap GROUP BY VBELN) v ON o.VBELN = v.VBELN						
LEFT JOIN mas_factory m ON v.WERKS = m.code
WHERE o.OSTAT != '1' AND DATE_FORMAT(h.create_time,'%Y-%m-%d') = '${date}'

> 感谢反馈，方便将完整的sql语句看一下嘛？你用的是mysql数据源是吧？

**Comment by China-BlueFat** [comment]
> 感谢反馈，方便将完整的sql语句看一下嘛？你用的是mysql数据源是吧？

不止一个语句，好几个都是，更新之前正常的，更新之后测试和正式的都有这个bug

**Comment by BBchicken-9527** [comment]
感谢反馈，方便给我看一下后台的报错日志嘛？

**Comment by maninhill** [comment]
长时间未反馈，请升级到最新版本。我们先关闭，如还有问题，请再重新打开。
