### ISSUE TITLE
[Feature]不设置默认仪表板时，默认仪表板菜单可以关闭显示

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#7102]
**请描述您的需求或者改进建议.**
不设置默认仪表板时，默认仪表板菜单这里空空的，希望可以设置默认仪表板菜单关闭显示。
<img width="571" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/e1b6ab21-0aad-4cd7-9f13-1d4257b76d9d">

**Comment by xuwei-fit2cloud** [comment]
我们经过讨论后，还是决定保持现有设计。
