### ISSUE TITLE
[Feature]期望优化过滤组件控制范围选项及配置必填时清空时的表现

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#7106]
**请描述您的需求或者改进建议.**
1.我新建了一个SQL数据集如下：
实际业务场景中，会使用非常复杂的SQL加工自己的业务数据，希望通过传参来限制基础数据量防止多表关联时数据量过大效率降低。
![image](https://github.com/dataease/dataease/assets/30886198/81f7be90-7d21-4114-af44-0a44dfed560e)
2.新建仪表板
其中包含四个视图，和一个过滤组件，过滤组件限制了必填（防止过滤过多数据）。
下拉框的选项是来自于一个独立的数据集（基表），视图是来源于多个不同的SQL数据集，每个SQL数据集中会做非常多的表 join，再汇总。
基表有几千条数据，但根据权限过滤后只有几个。所以希望通过传参方式限制每个SQL数据集中的基表数据量，提高查询效率。

![image](https://github.com/dataease/dataease/assets/30886198/962423b5-a35c-4430-b620-289f70493ce7)

此时会出现两个问题
a. 当过滤组件不限制控制范围时，如果删除过滤组件中的值，所有视图都会变成如图状态，不显示任何内容：
![image](https://github.com/dataease/dataease/assets/30886198/d9164bd9-5b5d-4225-bd1e-76ce1351bab8)
b. 当限制过滤组件控制范围时，只能选择仪表板中的“明细表”视图（因为过滤组件中只添加了明细表的字段）
此时无法将组件选值传参给“SQL汇总传参”数据集，导致查询全量数据

期望：
1. 当过滤组件不限制控制范围时，如果必填选项不填写任何值时，视图不发生任何改变（当前仪表板编辑界面是这种逻辑），并使用顶部悬浮提示用户必须填写必填项，避免整个仪表板数据无法查看。
2. 当限制过滤组件控制范围时，能够选择需要传参的视图（即在“参数”中勾选的视图也能在“控制范围”中勾选）

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
