### ISSUE TITLE
[Bug]v2.0 在线升级失败

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#7108]
**DataEase 版本**
v2.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
v2.0 环境使用命令 dectl upgrade 升级，网络验证通过了，但升级失败，请问这是为何？
<img width="1164" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/5d5448a1-5413-483a-bed7-820dc7ad6e43">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
