### ISSUE TITLE
[Bug] API数据源的数据解析异常

### ISSUE THREAD

**Issue by yuqun-nj** [dataease/dataease#7109]
**DataEase 版本**
V1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome 19.0.6045.159

**Bug 描述**
解析API数据源的数据时会出现数据格式混乱的情况，异常情况的原因是API返回结果中字段不一致

**Bug 重现步骤(有截图更好)**
1.添加API数据源，预览页面对比API返回结果数据不一致
API数据源解析结果
<img width="833" alt="image" src="https://github.com/dataease/dataease/assets/97491875/9e86c514-f4c4-4262-9642-49a1bb9a8ceb">
原始API返回结果
<img width="455" alt="image" src="https://github.com/dataease/dataease/assets/97491875/d61b3cfe-1d3c-434b-98a1-18d89f3438bc">
2.通过API数据源添加数据集，结果仍不一致
<img width="1163" alt="image" src="https://github.com/dataease/dataease/assets/97491875/63f7285c-c862-44a6-bfef-98911810528d">

**Comment by BBchicken-9527** [comment]
感谢反馈，由于你的数据字段不一致导致了数据内容的错位，建议保持字段的一致性，这主要我们这边处理并不知道实际的数据字段到底有几个；
