### ISSUE TITLE
[Feature] 希望DataEase支持连接Hive 3.0数据源

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#7113]
**请描述您的需求或者改进建议.**
1. 上传Hive 3.0驱动后，无法正常连接到Hive3.0 数据源，报错截图如下： 
<img width="327" alt="image" src="https://github.com/dataease/dataease/assets/45967454/7477cc8d-416b-438b-8683-1c8ecba22e09">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先确认一下。

**Comment by xuwei-fit2cloud** [comment]
我们测试了一下hive 3.1.2版本，用默认的驱动是可以正常连接的。可以试试默认驱动？

**Comment by xuwei-fit2cloud** [comment]
由于长时间无反馈，暂时关闭该issue。
