### ISSUE TITLE
[Feature]仪表板中的内容过多时，希望视图查询的http请求顺序可以根据仪表板中视图的布局优先

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#7114]
**请描述您的需求或者改进建议.**
我有一个内容较多的仪表板，里面有较多的文本下拉组件，并且视图也比较多。在查看该仪表板时，浏览器限制一次只能发出6个http请求，其他的请求都在等待当中。这个时候希望能够根据视图布局的顺序，把布局在前面的视图优先发起http请求。可以在给仪表板视图布局的时候把一些查询较快的视图放在前面，一些查询较慢的视图放在后面，这样就不会因为一些查询慢的视图而导致整个仪表板的视图都处于等待状态。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先确认下现在的请求顺序。根据查询较快、查询较慢来确定发起http请求的顺序可能不太合适，由于每个视图的网络、数据量都在变化，发起请求前系统并不知道每个视图的查询速度。

**Comment by hw872715125** [comment]
我已经知道当前仪表板中全部视图做数据查询时的查询速度（视图查询速度取决于我的sql数据集的sql在数据库中的查询速度），再来调整视图的顺序，把快的视图放在最前面，慢的放在后面。再根据视图的布局顺序来发起http请求。 @yayanpei-fit2cloud

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，数据库中当时的查询速度，并不能作为最终视图的查询速度，受网络环境的影响。建议您通过控制前端超时时间和数据源连接池数量配合使用，以此来限制并发数和超时时间；产品这边也会做相关的优化，将仪表板整体的遮罩去掉，这样当视图请求数据完毕时，可以先展示这部分视图数据，不用等到全部视图加载完毕。
