### ISSUE TITLE
[Bug]语言在英文下，行权限无删除功能以及其它，详情见图

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#7116]
**DataEase 版本**
v1.18.13

**Bug 重现步骤(有截图更好)**
行权限无删除按钮
![image](https://github.com/dataease/dataease/assets/70566485/8b397a1a-2718-491c-aeb4-e09cb0653a9a)

新建饼图视图
<img width="397" alt="image" src="https://github.com/dataease/dataease/assets/70566485/dd3427c8-6cf5-429f-9de0-d4d654b3752e">

新建视图时，默认给的视图名称也是中文
<img width="182" alt="image" src="https://github.com/dataease/dataease/assets/70566485/31a3005e-2dee-4000-a82d-1d11c1d19d4e">

仪表板样式部分错位
![image](https://github.com/dataease/dataease/assets/70566485/922a9173-f8b1-491f-a4c8-a5535a8e296b)
![image](https://github.com/dataease/dataease/assets/70566485/39ef5a97-5bd0-47d3-89c9-2b18a362af25)

仪表板左侧显示不全
![image](https://github.com/dataease/dataease/assets/70566485/13ba4e71-8a57-4984-a5ff-deac28e4f861)

以及等等……
建议测试一波

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将会在下个版本进行优化；
