### ISSUE TITLE
[Bug]登陆后可通过路由查看swagger接口json数据，存在API泄漏风险

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#7117]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**Bug 描述**
浏览器中访问：
DE请求地址 + /v3/api-docs?group=视图管理

存在API泄漏风险
![image](https://github.com/dataease/dataease/assets/89771514/90734b19-89d6-412d-bcb5-4356c29d1ebb)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们下个版本优化一下；

**Comment by xuwei-fit2cloud** [comment]
如许可无效 swagger接口会被拦截。
