### ISSUE TITLE
[Feature]时间组件里“动态时间”描述不准确

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#7119]
**请描述您的需求或者改进建议.**
无法选择时间，只能选择天，是不是叫“动态日期”更合适，另外，提一个小需求，可不可以有动态时间，在勾选显示时间以后，可以选择一小时前等等选择
![image](https://github.com/dataease/dataease/assets/101089844/088dc5b7-1bb4-4795-a131-199b1e6c709b)
![image](https://github.com/dataease/dataease/assets/101089844/c1f4c67b-9062-47d6-a43e-b5924fb641bc)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，原本我们设计日期组件的初衷是以日期为单位进行条件的选择，所以其中的动态时间均以天为单位。后期添加了时间的设置项，但动态时间这部分并没有做相应的调整。我们需要讨论一下是否有必要在动态时间里增加小时等其他动态设置项。

**Comment by yayanpei-fit2cloud** [comment]
当前暂时没有计划支持该需求，issue就先进行关闭了，再次感谢您对产品的关注和支持。
