### ISSUE TITLE
[Question] 是否支持可选参数

### ISSUE THREAD

**Issue by huiali** [dataease/dataease#7123]
**请描述您的问题.**
是否支持可选参数，比如我有3个条件，其中一个条件设置可选，也就是他不传输时我不关联该条件
比如：select * from A where A.a=${a} and A.b=${b}  if c and c=${c} 
也就是c当有值才作为筛选条件，无值时不作为筛选条件。

**Comment by BBchicken-9527** [comment]
你好， 现在如果你再不输入参数的时候筛选条件就是不会执行的，所以不确定你这个问题的具体意思是什么；

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，正如微信沟通结果，目前不支持根据参数去动态调整sql语句。
