### ISSUE TITLE
[Bug]设计器中“样式”tab页中的标签名称长度变窄，显示换行，上个版本没有这个问题

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#7124]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
官网试用版

**浏览器版本**
chrome 119

**Bug 描述**
如截图附件所示，设计器中的样式tab页，属性配置的标签，有部分换行了，1.18.12版本没有这个问题

**Bug 重现步骤(有截图更好)**
1. 选择仪表盘
2. 编辑仪表盘
3. 选择其中一个视图，点击编辑按钮，点击样式Tab

![image](https://github.com/dataease/dataease/assets/27687681/5ed0cdbb-da4c-4733-89d0-8c3e2520a298)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
