### ISSUE TITLE
[Question]修改nginx代理后有两个接口报错

### ISSUE THREAD

**Issue by Shanyoufusu12** [dataease/dataease#7126]
**请描述您的问题.**
我修改了前后端的接口地址，然后有两个接口在报错
![image](https://github.com/dataease/dataease/assets/60723145/4a7d8242-f429-4eb2-8032-f471edcf0c06)
![image](https://github.com/dataease/dataease/assets/60723145/51a63fa9-3027-4c6f-b044-ca0088bab81d)
然后这是修改后的正常接口地址
![image](https://github.com/dataease/dataease/assets/60723145/8d856a51-620c-476b-8b26-4b980712e8bb)
我想知道这两个接口为什么没有在修改配置的时候涉及到，还有就是是否影响正常使用？

**Comment by mfanoffice** [comment]
你得配置 websocket 代理呀

**Comment by Shanyoufusu12** [comment]
> 你得配置 websocket 代理呀
搞定了，感谢😁
