### ISSUE TITLE
[Bug] v2.1 版本自定义 SQL 设置参数并设置limit后，数据查询不出

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7130]
**DataEase 版本**
v2.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 119.0.6045.199（正式版本） (arm64)

**Bug 描述**
v2.1 版本自定义 SQL 设置参数并设置limit后，无法查询数据

**Bug 重现步骤(有截图更好)**
1. 如下图所示：
![image](https://github.com/dataease/dataease/assets/30063018/fd036e93-7170-4ac6-a238-43bb2e1cd6d9)
2. 去掉参数或者去掉limit后，查询结果正常
![image](https://github.com/dataease/dataease/assets/30063018/4a77ee97-bb63-4fcd-bd7f-6ffa783d3cde)
![image](https://github.com/dataease/dataease/assets/30063018/e72ad23d-7bee-42e7-b7ce-b9d66ee3ce16)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
