### ISSUE TITLE
[Bug] 添加 图片 组件后，设置大屏百分比，图片组件消失

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7131]
**DataEase 版本**
v2.1.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 120.0.6099.71（正式版本） (arm64)

**Bug 描述**
添加 图片 组件后，设置大屏百分比，图片组件消失

**Bug 重现步骤(有截图更好)**
https://github.com/dataease/dataease/assets/45852479/de117b1e-c5ef-4fed-a815-9039952d4767

另：希望屏幕百分比添加锁定按钮，触摸板容易误触导致放大或缩小

**Comment by BBchicken-9527** [comment]
感谢反馈，emm...确实有点儿问题但应该并不是消失了而是你选中图表的时候点击backspace给删除了，我们优化一下；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
