### ISSUE TITLE
[Bug]组件设置背景后，组件无法响应点击

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#7132]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
视图样式设置，设置背景后，保存预览仪表板，所有视图都无法点击了，选项卡 就没法手动点了， 其他的一些图标，鼠标放上去 也就没有数据提示 了
![image](https://github.com/dataease/dataease/assets/89771514/30c2dc7d-ac2c-4309-b7e8-53fd7cf023e7)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
