### ISSUE TITLE
[Feature]视图的图例希望支持的图形更加丰富

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#7133]
**请描述您的需求或者改进建议.**
目前支持的图例：
![image](https://github.com/dataease/dataease/assets/89771514/b7d98cef-473d-40d4-9ad3-b541cb306199)

希望支持的图例：
![wecom-temp-6448-c44bbbd54bb9af1854e5e75ce28d4e4b](https://github.com/dataease/dataease/assets/89771514/5ba5a887-7172-4a2d-bd97-7ec6fa46a7d2)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前图库内置支持的标记类型有："circle" | "square" | "line" | "diamond" | "triangle" | "triangle-down" | "hexagon" | "bowtie" | "cross" | "tick" | "plus" | "hyphen"，我们挑选了一些常见的标记类型，如果需要的话，我们可以放开一些其他内置的标记，但短期内还没有增加上图标记的计划。
