### ISSUE TITLE
[Bug]仪表板导出为图片，出现过滤组件内容错位的问题

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#7138]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
仪表板导出为图片，出现过滤组件内容错位的问题
实际的仪表板效果：
![image](https://github.com/dataease/dataease/assets/89771514/2cb651f7-d60b-4a4d-8ec6-9600cadbc7cc)

导出为图片后的效果：
<img width="1410" alt="image" src="https://github.com/dataease/dataease/assets/89771514/8c414c95-d44e-4c1a-a033-1ec7bbc89a6c">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将在后续的版本进行修复；

**Comment by ziyujiahao** [comment]
已提交 https://github.com/dataease/dataease/commit/50b793928826abae433d58d0aa4848d69746d155

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
