### ISSUE TITLE
[Feature]下拉树组件希望支持参数设置选项

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#7140]
**请描述您的需求或者改进建议.**
下拉树组件希望支持参数设置选项

需求场景：
下拉树中实现了一个4级的组织机构，视图中实现了一个人口类型统计（人口绑定最后一级的组织机构网格），点击下拉树某个节点，来统计这个节点下的所有子级机构网格的人口类型人数
![截图](https://github.com/dataease/dataease/assets/89771514/21cef459-08b6-492c-bc5f-ac668e8e32d4)

下拉树的sql：
`SELECT
    d1.dept_id AS level_1_id,
    d1.dept_name AS level_1_name,
    d2.dept_id AS level_2_id,
    d2.dept_name AS level_2_name,
    d3.dept_id AS level_3_id,
    d3.dept_name AS level_3_name,
    d4.dept_id AS level_4_id,
    d4.dept_name AS level_4_name
FROM
    sys_dept d1
LEFT JOIN
    sys_dept d2 ON d1.dept_id = d2.parent_id
LEFT JOIN
    sys_dept d3 ON d2.dept_id = d3.parent_id
LEFT JOIN
    sys_dept d4 ON d3.dept_id = d4.parent_id
WHERE
    d1.parent_id = 0;`

视图sql：
`SELECT
	dept_id,
	dept_name,
	ancestors,
	user_type,
	CASE 
		WHEN user_type = 1 THEN '常住人口'
		WHEN user_type = 2 THEN '流动人口'
		WHEN user_type = 3 THEN '留守人口'
		WHEN user_type = 4 THEN '境外人员'
		ELSE '未知类型'
	END AS 人口类型,
	COUNT(user_type) AS 人数
FROM
	zh_wgxt_base_user
	WHERE
	dept_name in (WITH RECURSIVE DeptHierarchy AS (
  SELECT dept_id, parent_id, dept_name, dept_level
  FROM sys_dept
  WHERE dept_name = '${dept_name}'

  UNION ALL

  SELECT d.dept_id, d.parent_id, d.dept_name, d.dept_level
  FROM sys_dept d
  JOIN DeptHierarchy dh ON d.parent_id = dh.dept_id
)
SELECT DISTINCT sg.dept_name AS grid_name
FROM DeptHierarchy dh
JOIN sys_dept sg ON dh.dept_id = sg.parent_id
WHERE sg.dept_level = 4)
GROUP BY
	dept_id, dept_name, ancestors, user_type;`

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by maninhill** [comment]
暂无支持计划。
