### ISSUE TITLE
[Bug] Local模式，API 数据源字段变动导致页面上过滤组件保存失败

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7144]
**DataEase 版本**
v1.8.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 120.0.6099.71（正式版本） (arm64)

**Bug 描述**
Local模式，API 数据源字段变动导致页面上过滤组件保存失败

**Bug 重现步骤(有截图更好)**
1. 添加 API 数据源、数据集
2. 制作视图，配置过滤插件
3. API 字段变动，A -> B，此时编辑过滤组件，不显示字段，且拖入 B 字段报错报错
<img width="844" alt="image" src="https://github.com/dataease/dataease/assets/45852479/fd512192-aeef-41e4-9622-96fa1ca54496">

另：希望过滤组件拖入字段的地方有个清空按钮
<img width="859" alt="image" src="https://github.com/dataease/dataease/assets/45852479/eb010b90-4cf2-42d4-8701-3a66a8764457">

**Comment by BBchicken-9527** [comment]
感谢反馈，问题将会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
