### ISSUE TITLE
 [Feature]v2.x社区版还不支持仪表板链接分享

### ISSUE THREAD

**Issue by maninhill** [dataease/dataease#7148]
**请描述您的需求或者改进建议.**

如题。

**Comment by xuwei-fit2cloud** [comment]
我们讨论一下。

**Comment by 172151295** [comment]
> 我们讨论一下。

需要支持后续才有更多的用户群体关注到这个项目，从而提高知名度，希望支持分享

**Comment by maninhill** [comment]
v2.3 已经支持。

https://github.com/dataease/dataease/releases/tag/v2.3.0
