### ISSUE TITLE
2.1版本安装后出现问题

### ISSUE THREAD

**Issue by kattocloud** [dataease/dataease#7149]
安装2.1后默认登录后是工作区
看不到管理后台，管理后台地址是多少？
或者就没有管理后台了？![1702483288933](https://img.gugu.ovh/i/2023/12/14/uzff.webp)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您点击右上角的「返回工作台」。

**Comment by kattocloud** [comment]
> 感谢反馈，您点击右上角的「返回工作台」。

没有后台管理，连修改默认密码的地方都没有
之前的版本都是没有问题的，安装好就可以修改默认密码
安装的途径是最新版的1panel应用商店

**Comment by xuwei-fit2cloud** [comment]
目前社区版里没有重置密码功能，在后面的版本，我们会增加重置密码功能，还请稍后。

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #7118

**Comment by kattocloud** [comment]
感觉这次更新后和之前完全不一样了，之前试用过，第一次登陆需要更改密码，而且很多功能感觉缺失了？

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
