### ISSUE TITLE
[Feature]在一个仪表板上展示 8 个以上地图卡顿的优化

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#7150]
**请描述您的需求或者改进建议.**
在一个仪表板上展示 8 个以上地图，有时按业务分析需要，展示十几个，会出现卡顿；
地图确实包含了很多 json 文件占用前端资源较多，有没有优化的空间？

**Comment by xuwei-fit2cloud** [comment]
前端json文件是有缓存的，在后续的访问时是不会再次请求的，目前没有优化的方案了。
