### ISSUE TITLE
[Bug]饼图文字内容重叠

### ISSUE THREAD

**Issue by lifeigtr** [dataease/dataease#7155]
**DataEase 版本** 
1.18.13

**运行方式(安装包运行 or 源码运行 ?)** 
安装包运行

**浏览器版本**
版本号：13.5.2044.0
内核版本：86.0.4240.198
极速浏览器基于Chromium:开源项目，支持开源社区发展。

**Bug 描述**
饼图不是特别大的时候，文字内容重叠； 期望文字能自适应 错开

**Bug 重现步骤(有截图更好)**
![微信截图_20231214113435](https://github.com/dataease/dataease/assets/49359158/cbb20c1e-6db1-40e7-97de-aa326c5b034b)

**Comment by BBchicken-9527** [comment]
感谢反馈，这个仪表板的视窗是全屏的吗？方便导出一个模版我这边看一下吗？

**Comment by lifeigtr** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；

**Comment by lifeigtr** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
