### ISSUE TITLE
2.1版本Google Chrome浏览器适配问题：创建仪表板页面缺少工具栏

### ISSUE THREAD

**Issue by mmmmmmiracle** [dataease/dataease#7160]
**DataEase 版本**
2.1

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome 已是最新版本
版本 120.0.6099.110（正式版本） （64 位）

**Bug 描述**
源码运行后，用Google Chrome浏览器访问，创建仪表板页面中缺少工具栏，使用Edge浏览器可正常显示。
![image](https://github.com/dataease/dataease/assets/38560338/825afd26-dc69-490b-90a3-2582e6c7d2bb)

使用edge可以正常显示
![image](https://github.com/dataease/dataease/assets/38560338/909637f2-9be4-4854-9aba-48471a61cb2b)

**Comment by xuwei-fit2cloud** [comment]
用隐身窗口试试？

**Comment by xuwei-fit2cloud** [comment]
无法复现此问题。
