### ISSUE TITLE
[Bug]下拉树组件筛选无数据时，提示“暂无数据”被遮挡问题

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#7165]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
官网demo

**浏览器版本**
chrom 119

**Bug 描述**
下拉树组件筛选无数据时，提示“暂无数据”被遮挡问题

**Bug 重现步骤(有截图更好)**
1. 新建仪表盘
2. 选择组件->下拉树，绑定一个数据集
3. 在设计器中，点击下拉树，输入不存在的值点查询，显示“暂无数据”，样式有问题

![image](https://github.com/dataease/dataease/assets/27687681/d9ad4fa2-788f-48ed-9fdf-f3c172c10a4d)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
