### ISSUE TITLE
[Bug] ECharts 表格隐藏表头同时隐藏统计行的问题1.18.13修复说明中的问题没有修复

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#7167]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
官网

**浏览器版本**
chrome 119

**Bug 描述**
ECharts 汇总表格隐藏表头同时隐藏统计行的问题，仍然存在

**Bug 重现步骤(有截图更好)**
1.新建仪表板
2.拖一个echart汇总表
3.设计表头显示和不显示，查看效果

显示表头时，汇总行正常显示
![image](https://github.com/dataease/dataease/assets/27687681/bda97f24-c2b1-4d60-a19c-115ab020a7bf)

不显示表头时，汇总行也不显示了
![image](https://github.com/dataease/dataease/assets/27687681/0bee1f96-ea39-4d34-a8a5-d2b5b81d835c)

**Comment by BBchicken-9527** [comment]
感谢反馈，修复说明的意思其实是隐藏表头的同时也隐藏了总计是这个意思😂，我们主要是考虑到表头隐藏后用户也不清楚具体的字段含义，以及如果不隐藏总计他的显示效果会看起来很怪异，最后决定将总计也同时隐藏掉；

**Comment by xiaorsly88** [comment]
好吧，中华文化博大精深
