### ISSUE TITLE
[Bug]新建计算字段提示不准确

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#7168]
**DataEase 版本**
V2.1.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新

**Bug 描述**
页面提示：表达式语法请遵循该数据源对应的数据库语法。数据集中不支持聚合运算。

而实际此处应遵循calcite语法

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/30886198/2105d344-d90c-486c-882d-93ce84b53eab)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下相应的提示；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
