### ISSUE TITLE
[Feature] 如何设置组件的动态效果，让每一个模块有动画在边框运动

### ISSUE THREAD

**Issue by Degree-21** [dataease/dataease#7169]
如何设置组件的动态效果，让每一个模块有动画在边框运动

如设置一个svg的边框代码
<svg width="445" height="29"><polyline fill="transparent" stroke-width="3" points="0,5.800000000000001 80.1,5.800000000000001 89,11.600000000000001 111.25,11.600000000000001 120.15,17.4 320.4,17.4 333.75,11.600000000000001 356,11.600000000000001 364.9,5.800000000000001 445,5.800000000000001" stroke="#3f96a5"><animate attributeName="stroke-dasharray" attributeType="XML" from="0, 225.68738071656065, 0, 225.68738071656065" to="0, 0, 451.3747614331213, 0" dur="1.2s" begin="0s" calcMode="spline" keyTimes="0;1" keySplines="0.4,1,0.49,0.98" repeatCount="indefinite"></animate></polyline> <polyline fill="transparent" stroke-width="2" points="133.5,23.200000000000003 311.5,23.200000000000003" stroke="#3f96a5"><animate attributeName="stroke-dasharray" attributeType="XML" from="0, 89, 0, 89" to="0, 0, 178, 0" dur="1.2s" begin="0s" calcMode="spline" keyTimes="0;1" keySplines=".4,1,.49,.98" repeatCount="indefinite"></animate></polyline></svg>

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，近期暂时没有支持的计划，我们先记录并加入2.x的需求池中。
