### ISSUE TITLE
[Feature] 明细表调整是否支持自定义跳转参数

### ISSUE THREAD

**Issue by yuqun-nj** [dataease/dataease#7173]
点击明细表一行中的任意字段，可以支持自定义跳转的参数。
如一个统计结果表，点击统计结果字段时可以使用统计的维度字段跳转到对应的明细表中并过滤中该维度下的结果

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们v2.0版本是支持的，建议您试用下新版本。
