### ISSUE TITLE
[Feature] 饼图/柱状图等视图标签是否可以新增字体大小

### ISSUE THREAD

**Issue by yuqun-nj** [dataease/dataease#7176]
饼图/柱状图等视图标签是否可以新增字体6号和8号字体

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，浏览器中常见的字体一般是12号，14号，6号和8号可能会有些看不清楚了。

请问您这边是出于什么考虑，要用到小号的字体呢？如果是标签比较长显得拥挤，建议您通过设置数值格式，便于查看和阅读。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，浏览器中常见的字体一般是12号，14号，6号和8号可能会有些看不清楚了。

请问您这边是出于什么考虑，要用到小号的字体呢？如果是标签比较长显得拥挤，建议您通过设置数值格式，便于查看和阅读。

**Comment by yuqun-nj** [comment]
当柱状图的维度字段或者饼图分类类型名称过长时无法显示全部完整信息

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，当标签过长时，字体调整成6号，可能还是显示不全，且字体较小，可能也看不太清楚。建议字体调整为常规字体大小，维度如果过长，在标签中展示不全，可以在提示框中查看完整的信息。
