### ISSUE TITLE
[Feature] Tab组件的字体能否增加自定义设置

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#7177]
**请描述您的需求或者改进建议.**
如图所示，Tab组件中的标签目前只能支持大小、颜色和位置设置，能不能支持字体的设置？
![image](https://github.com/dataease/dataease/assets/27687681/5637a0f1-7d0d-463c-8899-0290d25f3923)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，我们先看下当前的组件是否支持。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，我们先加入需求池中。
