### ISSUE TITLE
[Bug]查询按钮关闭自动触发后，进入页面还是会触发查询

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#7178]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
119.0.6045.200（正式版本） （64 位）

**Bug 描述**
在仪表板中增加了查询按钮，并且关闭了自动触发，这个并没有生效，查看该仪表板时，还是会触发一次查询。
按我的理解，关闭了自动触发以后，那么在打开这个仪表板时必须要点查询按钮才能触发视图的数据查询吧。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/26103277/cca894a8-cb2e-40d0-868d-e2b051eb139b)
![image](https://github.com/dataease/dataease/assets/26103277/68e572a8-fd7a-4c8e-b7a7-39527d95b71d)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，无痕模式下也会出现相同的问题吗？

**Comment by hw872715125** [comment]
看来你没有get到我的意思，我的想法是，关闭查询按钮的自动触发后，在打开这个仪表板的时候，就不要去查询视图的数据了，而是在点击查询以后再去查数据。比如，如果给查询按钮设置了关闭自动触发，那么在打开这个仪表板的时候，就不会触发数据查询的功能，视图是空白的。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，仪表板加载是一个比较特殊的情况，不受查询按钮设置的控制。
仪表板在加载时，会根据查询条件自动加载一次，产品是这么设计的，当前暂时没有更改的计划，如果需要限制加载的数据量，建议给过滤组件设置默认值。
