### ISSUE TITLE
[Feature]为仪表板内视图/组件增加一个说明文本框

### ISSUE THREAD

**Issue by liulongleo** [dataease/dataease#7181]
**请描述您的需求或者改进建议.**
问题场景：
1. 仪表板内的标题是外语，配置和维护人员看不懂标题
2. 视图/组件不显示标题
3. 视图的数据有过滤、样式等要求
4. 对视图的格式有一些特殊记录

希望：
1. 为视图/组件新增一个仅用于配置时编辑和查看的说明文本框，不用于仪表板对外的显示
2. 该文本框与标题同级，便于配置维护人员编辑和查看
3. 该说明文本框可实现仪表板内各视图/组件的自解释说明

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，编辑和预览状态显示的内容原则上需要保持一致，因此暂时没有计划支持该需求。
如果需要给图表增加说明，建议在标题中添加备注。
