### ISSUE TITLE
[Bug]【视图】AntV 图库汇总表自适应列宽展示有问题。

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#7184]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
AntV 图库汇总表选择自适应列宽，但是表格中的字段还是未展示完全，如下图所示：
![image](https://github.com/dataease/dataease/assets/24768910/1e1d63f9-7545-4666-9997-3dad56df4d9b)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现此类问题，请问是什么数据源？直连还是定时任务？

**Comment by AndroidBaby1** [comment]
[real_datas.xlsx](https://github.com/dataease/dataease/files/13701028/real_datas.xlsx)
是 Excel 数据集，您请试试~

**Comment by BBchicken-9527** [comment]
感谢反馈，我看第23条数据和24条数据字符是相同的，但是23条数据生省略了部分，应该是s2自身计算存在一些问题，但因为是图库内部进行运算我们无法对其进行干涉；

**Comment by AndroidBaby1** [comment]
好的，感谢！
