### ISSUE TITLE
[Bug]明细表视图，分页模式选择下拉，且数据结果为全部时，空指针异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#7188]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/89771514/db880b22-2567-42d0-9db7-7ae417cea5b2)
![image](https://github.com/dataease/dataease/assets/89771514/d5254d78-99e6-49b4-8743-9b0d194563c5)

1.oracle数据源，sql数据集
2.明细表视图，数据结果为全部，分页模式选择下拉

**Comment by BBchicken-9527** [comment]
感谢反馈，问题将会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
