### ISSUE TITLE
表格组件中单元格的内容可布局

### ISSUE THREAD

**Issue by jonahzheng** [dataease/dataease#7190]
讨论贴：https://bbs.fit2cloud.com/t/topic/2596

1、需要单元格的内容由多个字段拼合而成；
2、如果单元格的内容可以是‘富文本视图’也满足需求；
类似这样的
![image](https://github.com/dataease/dataease/assets/5125282/f992ff1c-072a-4018-bedf-4d8b82ae0a4e)
![image](https://github.com/dataease/dataease/assets/5125282/93d8dcfc-c505-44a8-a8a7-2ac98dd9a3da)
3、这个需求还是满普遍的，特别是需要滚动显示定制的实时信息时；
4、不一定要用表格视图，实现一个滚动的视图，内容可以自定义的设置多个字段的富文本

**Comment by xuwei-fit2cloud** [comment]
目前还没有这样的支持，但您可以通过计算字段来处理一下数据，类似下图：

![图片](https://github.com/dataease/dataease/assets/1892127/2a9517e1-136c-4e61-a6da-0d4c179ade35)

**Comment by maninhill** [comment]
暂无支持计划。
