### ISSUE TITLE
[Bug] 行权限无法过滤下拉组件设置好的默认值

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7195]
**DataEase 版本**
v1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 120.0.6099.71（正式版本） (arm64)

**Bug 描述**
针对数据集设置好行权限，将 city 为 A 的数据授权给用户小王，并使用该数据集做好看板，看板同时针对字段 city 设置好文本下拉组件，设置多选，并设置好默认值 ABC，切换到用户小王后，默认值并未被过滤。

**Bug 重现步骤(有截图更好)**
1. 数据集如下所示：
![image](https://github.com/dataease/dataease/assets/30063018/c365bd7b-0bcd-4204-92c7-388fc4806fb5)
2. 针对用户设置好行权限，city = 南京市
![image](https://github.com/dataease/dataease/assets/30063018/b1e5e481-f54f-4b58-bc5e-8ccaf92cf2cb)
3. 配置看板，并对 city 字段配置多选下拉组件，默认值设置为南通市，南京市，宿迁市
![image](https://github.com/dataease/dataease/assets/30063018/fcd953d2-bc39-4179-a9f0-4246d55f16be)
4. 切换配置好行权限的用户，查看看板，发现数据虽然发生了过滤，但是下拉组件的默认值并未过滤
![image](https://github.com/dataease/dataease/assets/30063018/13f47a37-d676-4260-89a9-17db41e59a24)

**Comment by Shenguobin0102** [comment]
感谢反馈，我们会在后续版本修复。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
