### ISSUE TITLE
[Bug]数据集-添加Excel表格的数据集解析失败-表格中包含公式计算结果

### ISSUE THREAD

**Issue by youmu-2019** [dataease/dataease#72]
**DataEase 版本**
v1.0

**浏览器版本**
Chrome 版本 91.0.4472.114

**Bug 描述**
excel表格首行是空，添加到DataEase后，提示解析错误
Excel表格中有数据是百分比格式，添加到DataEase后，百分比的数据是空白
![image](https://user-images.githubusercontent.com/56707401/123571541-05446c00-d7fd-11eb-81a1-e3c6daf0c92b.png)

表格中通过率结果是通过函数计算出来，导致导入的时候提示解析失败

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
目前没有支持Excel公式，我们会作为新功能来完善对Excel的支持。

**Comment by xuwei-fit2cloud** [comment]
v1.0.1 版本已支持并发布
