### ISSUE TITLE
[Bug]查询组件时间范围无法添加参数

### ISSUE THREAD

**Issue by jstbw** [dataease/dataease#7211]
**DataEase 版本**

v2.1.0
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
数据集正常添加了sql及配置了参数，到仪表板用查询组件，选择时间是可以连接到参数，但时间范围是空的

**Bug 重现步骤(有截图更好)**
![8ce00820aafc323ff2e2ae05ba3425e](https://github.com/dataease/dataease/assets/66759501/f3b59703-c0a6-4f57-b6a0-3bfb8a46ccf5)

![95059cce844c9dbfab2ff1776fb12b0](https://github.com/dataease/dataease/assets/66759501/daa96ed0-a925-4f2a-be93-9d77ed9cbde4)

**Comment by Shenguobin0102** [comment]
你好，时间范围绑定参数的功能在 v2.1.0 版本没有实现，这个功能会在 v2.2.0 版本与大家见面，敬请关注。
