### ISSUE TITLE
[Feature] 开发大佬们，代码中的字体、本地 jar 包等大文件可以使用 OSS 上传么，或者 git lfs？

### ISSUE THREAD

**Issue by calvinit** [dataease/dataease#7235]
**请描述您的需求或者改进建议.**
例如 core/drivers 中的 jar 包（可使用 maven nexus 管理？）、core/frontend/static/fonts 中的字体文件等，这些大文件会在私有仓库中遇到提交不了的问题（单文件大小限制）！

**Comment by xuwei-fit2cloud** [comment]
jar包仅在做镜像的时候需要用到，可以自己删除jar包，自己改一下Dockerfile文件。
字体的话，二开也可以对这块自行处理，比如换个字体，或者用默认字体。
