### ISSUE TITLE
[Bug]消息接收逻辑错误

### ISSUE THREAD

**Issue by fangdo** [dataease/dataease#7237]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**
谷歌

**Bug 描述**
首先勾选目录后，把下一级的勾取消后，目录的勾没有取消

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/96818402/c08cc2e0-2a23-44fc-8c33-f5795abeb88b)

2.
3.

**Comment by pixel-Flow3** [comment]
Setting.vue
formatTreeNode方法中
添加
else {
                node.check_all_map[key] = false
                node.indeterminate_map[key] = false
              }
              目前解决方案

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将在下个版本进行此处的修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
