### ISSUE TITLE
过滤组件添加边框样式后无法点击[Bug]

### ISSUE THREAD

**Issue by fangdo** [dataease/dataease#7242]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
 源码

**浏览器版本**
谷歌

**Bug 描述**
文本过滤组件，数字过滤组件，设置样式-背景-边框后无法点击

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/96818402/2ea6620e-6376-43a2-af45-f44f7f5f99ef)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前问题已修复，将会在下个版本发布；

**Comment by fangdo** [comment]
贴下代码出来呗

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
