### ISSUE TITLE
应用管理-应用记录无法筛选[Bug]

### ISSUE THREAD

**Issue by fangdo** [dataease/dataease#7244]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**
谷歌

**Bug 描述**
应用管理-应用记录无法进行筛选

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/96818402/ad8caf8a-daee-4b9c-a560-e7d0cb81b760)

2.
![image](https://github.com/dataease/dataease/assets/96818402/21a6b241-a8a7-4637-a926-8a253b30ae9c)

3.

**Comment by Shenguobin0102** [comment]
感谢反馈，我们会在后续版本修复这个问题。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
