### ISSUE TITLE
[Feature]建议 v2.x 安装完成后在提示的登录信息中补充说明访问地址，主要提示访问端口

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#7247]
**请描述您的需求或者改进建议.**
建议 v2.x 安装完成后在提示的登录信息中补充说明访问地址，主要目的为给用户提示下访问端口。
![image](https://github.com/dataease/dataease/assets/48945409/dbfe7d3a-a05f-43df-9887-03d26a5bbc69)

**Comment by xuwei-fit2cloud** [comment]
已优化，等待新版本发布。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
