### ISSUE TITLE
[Feature]希望增加对数据大屏文件夹下多个大屏进行轮播的功能

### ISSUE THREAD

**Issue by Yuri-NagaSaki** [dataease/dataease#7248]
**请描述您的需求或者改进建议.**
你好。

举例：
我在某个文件夹下新建了一套相关的数据大屏，希望能够进行展示
但目前Dataease只支持单个大屏的预览展示，无法和其他大屏产生联动
每次切换到别的大屏展示，需要退出原先的大屏，切换到新的。

希望能实现一组文件夹下的大屏全部展示，类似ppt，可以通过某个按键功能进行切换
![image](https://github.com/dataease/dataease/assets/77047823/33742b8d-6393-4cf4-98d1-9fdc2562577b)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，该需求已经在我们需求池内，后续会进行开发排期。
