### ISSUE TITLE
数据源表的详细详细中表描述不同步[Bug]

### ISSUE THREAD

**Issue by fangdo** [dataease/dataease#7251]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
 源码

**浏览器版本**
谷歌

**Bug 描述**
使用PostgreSQL与SQL Server
数据源表的详细详细中表描述不同步

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/96818402/09f76d03-27fb-4d7d-b911-91eeb391cb67)

2.
![image](https://github.com/dataease/dataease/assets/96818402/27363c81-c634-410a-bd1b-4a89d2795952)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，部分数据库的描述目前无法获取，目前无法对此出进行优化；
