### ISSUE TITLE
应用管理中，应用应用成功后在应用记录中无法编辑[Bug]

### ISSUE THREAD

**Issue by fangdo** [dataease/dataease#7252]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**
谷歌

**Bug 描述**
应用管理中，使用对应的应用模板，在数据源选项选择新建。即使新建成功，应用记录有显示，仪表板存在。在应用记录里也无法编辑该应用。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/96818402/c6276934-77c5-4ac2-84b7-0910e32d1c69)

2.
![image](https://github.com/dataease/dataease/assets/96818402/ca0a2091-b200-43f1-92e0-0fb1ed3bd9bc)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
