### ISSUE TITLE
组件-数字下拉组件/数字列表组件错误提示异常[Bug]

### ISSUE THREAD

**Issue by fangdo** [dataease/dataease#7254]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**
谷歌

**Bug 描述**
组件-数字下拉组件/数字列表组件错误提示异常
使用pg数据源数据报错
输入不存在数据回车错误提示异常
**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/96818402/874ae9dd-525a-4baf-a71a-7e1a9d345e99)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，问题将会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
