### ISSUE TITLE
目录/仪表板/视图标题可输入空格创建[Bug]

### ISSUE THREAD

**Issue by fangdo** [dataease/dataease#7255]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
 源码

**浏览器版本**
谷歌

**Bug 描述**
目录/仪表板/视图标题可输入空格创建

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/96818402/ee4032c3-d4b8-4633-a293-ac4330a381b2)
2.
3.

**Comment by fangdo** [comment]
![image](https://github.com/dataease/dataease/assets/96818402/ad65ba22-49ec-4a7c-a9e6-6cf2f54ffc95)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
