### ISSUE TITLE
[Feature]计算字段对于聚合计算的建议

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#7260]
**请描述您的需求或者改进建议.**
2.1 版本计算字段提示不支持聚合计算，实际是支持的，并且可以在视图正常使用，如下图：
![图片](https://github.com/dataease/dataease/assets/48307752/05644660-77cb-41b1-9726-d9ab6b02c5c2)
![图片](https://github.com/dataease/dataease/assets/48307752/ff6dce08-59c2-42d2-8e10-278c3bc111c9)

可以继续沿用此功能，不必单独设计视图字段，就像 finebi 一样，计算字段只有一个入口，可以做任何计算。

**Comment by xuwei-fit2cloud** [comment]
此处的意思是，聚合计算在数据集中无法使用，无法在数据集中预览。但这个计算字段在图表中是可以使用的。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
