### ISSUE TITLE
[Bug]明细表视图聚合函数展示问题

### ISSUE THREAD

**Issue by hzhwyh0116** [dataease/dataease#7266]
**DataEase 版本**
V1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
添加视图计算字段：[num]/sum([num])  计算行占比情况
未拖入视图计算字段时，数据总行数是 3 条
拖入视图计算字段后，只显示 1 条数据

**Bug 重现步骤(有截图更好)**
<img width="1400" alt="image" src="https://github.com/dataease/dataease/assets/89765365/c05e72a3-0dee-45b7-a52d-14430ef02c59">

<img width="1397" alt="image" src="https://github.com/dataease/dataease/assets/89765365/85760d92-fb9c-41ac-9609-af68dd12b310">

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你数据源使用的是什么呢？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；

**Comment by hzhwyh0116** [comment]
Excel 数据集
