### ISSUE TITLE
[Feature]建议数据大屏增加矩形组件

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#7274]
**请描述您的需求或者改进建议.**
建议 v2 数据大屏增加「矩形」组件，数据大屏在设计上时常需要使用到分块垫一个底层的背景再在此之上增加各种小的元素的场景。
例如下面的大屏，每一块需要放一个区域的背景块，需要使用到矩形组件。
![image](https://github.com/dataease/dataease/assets/48945409/e810e8c0-4546-49ea-b946-b21456fc2b05)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，后面有计划内置一些常见的图形组件。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
