### ISSUE TITLE
[Feature] 柱状图的辅助线是否可以将辅助线名称隐藏

### ISSUE THREAD

**Issue by yuqun-nj** [dataease/dataease#7276]
柱状图的辅助线是否可以支持隐藏名称文字的功能，这样样式可能会好看一点

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，辅助线一般用于辅助阅读数据，因此常见设置为指标的平均值等，不展示名称，用户查看图表时无法获知辅助线的含义。

如果不需要显示名称，不需要获知线条的含义，建议将坐标轴上的网格线打开。
