### ISSUE TITLE
[Bug] 透视表总计聚合方式选择除求和外的其他方式不生效

### ISSUE THREAD

**Issue by connor-chl** [dataease/dataease#7281]
**DataEase 版本**
1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 120.0.6099.129

**Bug 描述**
透视表总计聚合方式选择除求和外的其他方式不生效

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/24839442/a1ea9cff-f14d-49ec-9e0a-23e24efd17d9)

**Comment by BBchicken-9527** [comment]
感谢反馈，应该使用列汇总才会有所改变的，我们建议最好将数据行和数据列全部添加；
![image](https://github.com/dataease/dataease/assets/84372766/039ac90d-a60c-4b4f-812d-fcf411342984)
