### ISSUE TITLE
[Feature] 散点图支持类似于 直方图、折线图的辅助线

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7289]
**请描述您的需求或者改进建议.**
如题
![image](https://github.com/dataease/dataease/assets/45852479/e4627b6c-5156-4017-8516-2fd37aac07a4)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在最近的版本会支持散点图的辅助线功能。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
