### ISSUE TITLE
[Feature] Echarts 支持数值格式设置

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#7290]
**请描述您的需求或者改进建议.**
echatrs 的表格数值希望显示千分符号，看7位数的时候比较好看

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议使用antv图库，echarts上暂时没有计划支持数值格式。
