### ISSUE TITLE
[Feature] 1.0 版本 antv 视图支持类似 2.0 版本的 提示内容修改

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7291]
**请描述您的需求或者改进建议.**
如题
![image](https://github.com/dataease/dataease/assets/45852479/aa32547d-b96d-45e1-a21a-4f7541f44552)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，暂时没有计划在1.x版本实现该功能，建议您试用下2.x版本。
