### ISSUE TITLE
导出PDF希望可以带出所有数据

### ISSUE THREAD

**Issue by s-phenix** [dataease/dataease#7292]
如果明细表字段比较多，导出pdf的话，只能看到页面展示的一部分数据，可以滚动的部分就看不了了，希望可以优化一下
![image](https://github.com/dataease/dataease/assets/57552153/304a9ed4-e23d-4682-adc6-a99f605ca154)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，pdf可以看作是图片，所以看不到的内容无法带出来。
