### ISSUE TITLE
[Bug]数据集-添加Excel数据集之后查看信息报错

### ISSUE THREAD

**Issue by youmu-2019** [dataease/dataease#73]
**DataEase 版本**
v1.10

**浏览器版本**
Google Chrome
版本 91.0.4472.114

**Bug 描述**

![image](https://user-images.githubusercontent.com/56707401/123572047-0924be00-d7fe-11eb-8d62-c66a2388c962.png)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
我们排查一下，尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.1.1 版本已修复
