### ISSUE TITLE
[Bug]Api方式，中文乱码问题

### ISSUE THREAD

**Issue by cjpcamb2005** [dataease/dataease#7303]
**DataEase 版本**
2.1.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
使用api方式，返回数据中，有字段是中文，在饼图中显示未乱码"??"

**Bug 重现步骤(有截图更好)**

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，受累看一下本地的mysql数据库中存储的内容是什么呢？

**Comment by cjpcamb2005** [comment]
![image](https://github.com/dataease/dataease/assets/24823785/f990e271-8032-4b67-b213-10d133059037)
我使用的是API方式，这是我测试的API，帮忙看看是否有误

**Comment by BBchicken-9527** [comment]
感谢反馈，你使用postman请求到的数据时候也是乱码？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
