### ISSUE TITLE
[Bug]1.18.11- 1.18.13版本存在导入时间自动乱序 无法调整

### ISSUE THREAD

**Issue by Yuri-NagaSaki** [dataease/dataease#7304]
**DataEase 版本**

1.18.11- 1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
1panel + docker 

**浏览器版本**

Chrome最新

**Bug 描述**

excel有一列是月份，在表格里是安装顺序1月 2月----12月排序
导入Dataease中自动乱序，无法调整

**Bug 重现步骤(有截图更好)**
原数据 excel排序
<img width="100" alt="image" src="https://github.com/dataease/dataease/assets/77047823/d68827ce-cacd-4807-b48c-664fcf7b3b10">

dataease 导入后
<img width="209" alt="image" src="https://github.com/dataease/dataease/assets/77047823/755c695e-4412-4609-82bd-46ccc3e676ec">

**Comment by Yuri-NagaSaki** [comment]
<img width="474" alt="image" src="https://github.com/dataease/dataease/assets/77047823/a6d22de9-d31f-4560-8600-13e8b4b787e3">

实测同样的数据，在2.1版本导入可以识别正确的顺序

**Comment by BBchicken-9527** [comment]
感谢反馈，这是因为1.x和2.x在底层有根本性的改变，目前1.x在抽取时是无序的；

**Comment by Yuri-NagaSaki** [comment]
> 感谢反馈，这是因为1.x和2.x在底层有根本性的改变，目前1.x在抽取时是无序的；

好的，谢谢
也就是说 只能通过跨大版本到2.1才能解决吗？
我尝试过1.x 更新2.1 ，似乎更新后直接容器无法启动
请问是否有更新方案

**Comment by BBchicken-9527** [comment]
感谢反馈，目前是不支持跨大版本升级的，就像我之前说的，为了解决一些1.x的根本问题，所以2.x做了很大的架构调整，所以目前是无法跨大版本去升级的；

**Comment by Yuri-NagaSaki** [comment]
> 感谢反馈，目前是不支持跨大版本升级的，就像我之前说的，为了解决一些1.x的根本问题，所以2.x做了很大的架构调整，所以目前是无法跨大版本去升级的；

好的，感谢，我清楚了

**Comment by BBchicken-9527** [comment]
好的，如果没什么问题我就先将问题关闭了，感谢你的支持；
