### ISSUE TITLE
[Feature]过滤筛选框联动需求

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#7308]
**请描述您的需求或者改进建议.**
有二级业务模块，我选择完对应的业务模块后，  同时有一个筛选框是 机房，  机房是希望展示 对应的 二级模块 下有的 机房。  而不是展示其他无关机房。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，该需求早期已经记入到我们的需求池中，我们会在后续的版本中加入支持。
在当前的版本下，您可以使用下拉树来解决您的问题。

**Comment by 18927580527** [comment]
你好，下拉树不支持传递参数。  另外能否加入到2.0的版本计划中.
