### ISSUE TITLE
[Feature]建议当DataEase服务器无法联通外网时，使用模板新建功能能够列出模板管理中本地上传的模板文件

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#7312]
**请描述您的需求或者改进建议.**
如图，当服务器与外网不通时，即使在 工具箱-模板管理 中上传了模板，页面也不会列出。
期望当 DataEase 服务器无法联通外网时，使用模板新建功能 能够列出模板管理中本地上传的模板文件。
![image](https://github.com/dataease/dataease/assets/30886198/da663f5d-8be2-43db-93fc-01cb0576b0a0)

**Comment by xuwei-fit2cloud** [comment]
此处已做优化，请等待下个版本的发布。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
