### ISSUE TITLE
[Bug] 时间戳年月组件过滤失效

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7313]
**DataEase 版本**
v2.1.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 120.0.6099.71（正式版本） (arm64)

**Bug 描述**
原本是时间戳的字段切换为日期字段 使用年月组件过滤失败

**Bug 重现步骤(有截图更好)**
1. 视图制作并配置过滤组件
![image](https://github.com/dataease/dataease/assets/45852479/6cb3d24a-ca58-4de5-b2f5-d2fc0f0c089a)
2. 过滤 2023-05
![image](https://github.com/dataease/dataease/assets/45852479/bdf57935-62a1-498d-aaaa-08850f62f17d)

**Comment by Shenguobin0102** [comment]
感谢反馈，我们会在后续版本修复。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
