### ISSUE TITLE
[Bug] 在过滤组件使用默认值的情况下，视图过滤放大后展示的是组件默认值 

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7314]
**DataEase 版本**
v2.1.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 120.0.6099.71（正式版本） (arm64)

**Bug 描述**
在过滤组件使用默认值的情况下，视图过滤放大后展示的是组件默认值 

**Bug 重现步骤(有截图更好)**
1. 视图制作并配置过滤组件及默认值（2022-04）
2. 过滤组件切换至 2022-05
![image](https://github.com/dataease/dataease/assets/45852479/d2874f98-ad2a-499d-ac8d-7c31aa056283)
3. 放大后依旧展示为 2022-04
![image](https://github.com/dataease/dataease/assets/45852479/c7bf05c7-b38a-4fd1-b974-e30f113cfeac)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
