### ISSUE TITLE
[Bug] SQL 参数识别异常，运行 SQL 报错。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7320]
**DataEase 版本**
v1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
Google Chrome
版本 120.0.6099.129（正式版本） (arm64)

**Bug 描述**
数据源 MySQL，添加参数后执行 SQL 报错

**Bug 重现步骤(有截图更好)**
1. SQL 语句如下所示：
`SELECT `项目中文名称`,
       `项目名称`,
       `累计次数`,
       `人工累计工时/h`,
       `软件累计工时/h`,
       `节省工时/h`,
       `收益/W`,
       if(ROUND((`人工累计工时/h` - `软件累计工时/h`) / `人工累计工时/h` * 100, 3) is not null,
          ROUND((`人工累计工时/h` - `软件累计工时/h`) / `人工累计工时/h` * 100, 3), 0) as '节省人工率%'
FROM (SELECT `项目中文名称`,
             `项目名称`,
             sum(`累计次数`)             as '累计次数',
             ROUND(sum(`人工工时/h`), 3) as '人工累计工时/h',
             ROUND(sum(`软件工时/h`), 3) as '软件累计工时/h',
             ROUND(sum(`节省工时/h`), 3) as '节省工时/h',
             ROUND(sum(`收益/W`), 3)   as '收益/W'
      FROM (SELECT `项目名称`,
                   `项目中文名称`,
                   `模块`,
                   `累计次数`,
                   `人工操作工时/min`,
                   `软件操作工时/min`,
                   `人工工时/h`,
                   `软件工时/h`,
                   ROUND(`人工工时/h` - `软件工时/h`, 3)             as '节省工时/h',
                   ROUND((`人工工时/h` - `软件工时/h`) * `标准工时费`, 3) as '收益/W'
            FROM (SELECT `项目中文名称`,
                         `项目名称`,
                         a.`模块`,
                         `核心点击次数`                               as '累计次数',
                         `人工操作工时/min`,
                         `软件操作工时/min`,
                         `操作人层级`,
                         ROUND((`人工操作工时/min` / 60) * 核心点击次数, 3) as '人工工时/h',
                         ROUND((`软件操作工时/min` / 60) * 核心点击次数, 3) as '软件工时/h'
                  FROM (SELECT `项目名称`, COUNT(`核心点击次数`) AS '核心点击次数', `模块`
                        FROM softwarecrop
                        WHERE `日期` BETWEEN '${start_date}' and '${end_date}'
                          and `模块` is not null
                        GROUP BY `项目名称`, `模块`) as a
                           LEFT JOIN(SELECT `项目ID`, `模块`, `人工操作工时/min`, `软件操作工时/min`, `操作人层级` FROM tablefrom) as b
                                    on b.`模块` = a.`模块`
                           LEFT JOIN(SELECT `项目编号`, `项目名称` as '项目中文名称' FROM softwareform) as e
                                    on e.`项目编号` = a.`项目名称`) as c
                     LEFT JOIN(SELECT `层级`, `标准工时费` FROM wagerates) as d on d.`层级` = c.`操作人层级`) as c
      GROUP BY `项目名称`) as d;`
2. 报错信息如下所示：
![wecom-temp-603793-7f05ab68182388cf8dee974111988698](https://github.com/dataease/dataease/assets/30063018/ebe6c3b6-2ce5-406e-8da8-96692395dba9)

**Comment by BBchicken-9527** [comment]
感谢反馈，方便将后台提示的异常给我一份嘛？

**Comment by ziliang-wan** [comment]
这个问题是中文字符导致的，给中文字符加上``后该问题就得到解决了，感谢支持。
