### ISSUE TITLE
[Feature]筛选框的值联动功能

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#7322]
**请描述您的需求或者改进建议.**
第一个筛选框是 一级业务模块， 第二个筛选框是 二级业务模块。  来源于同一个数据集.
我在第一个筛选框选择完后， 第二个筛选框里面的值 为 第一个筛选框筛选后的值。 避免用户找不到的情况.

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #7308
