### ISSUE TITLE
[Bug]AntV组合图快速计算占比数据有误

### ISSUE THREAD

**Issue by Newland-jiajia** [dataease/dataease#7323]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Google Chrome 版本 110.0.5481.177（正式版本） （64 位）

**Bug 描述**
AntV组合图指标的快速计算占比项计算结果有误

**Bug 重现步骤(有截图更好)**
1.选择组件antv组合图并创建，选择维度和指标后，将快速计算设置为占比。
![组合图1](https://github.com/dataease/dataease/assets/96104467/25fd5f3e-b01b-469d-9cf2-002e4ef27731)

2.查看效果如图
![组合图2](https://github.com/dataease/dataease/assets/96104467/61eecb79-704e-41c2-bf8c-b386df12707a)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
