### ISSUE TITLE
[Feature]定时报告可以选择只发送视图数据

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#7325]
**请描述您的需求或者改进建议.**
场景：目前的定时报告会发送仪表板，不想让报告接收者看到仪表板的整体内容，只允许看到某几个视图的数据，所以希望可以只发送视图的数据。
 能否在定时报告编辑界面增加 “只发送视图数据” 的选项？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by mfanoffice** [comment]
需求关闭，通过行权限可以控制用户查看到指定数据，定时报告发送用户有权限的仪表板和视图数据。
