### ISSUE TITLE
[Bug]【数据源】API 数据源界面莫名添加行问题

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#7335]
**DataEase 版本**
V2.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本谷歌浏览器

**Bug 描述**
API 数据源 QUERY 参数页签在【值】里录入数据的时候，”双击“【值】那个文本框的时候会自动创建新的行。
详见以下视频：
本地环境和客户环境皆有复现。

https://github.com/dataease/dataease/assets/24768910/6900e0bd-a148-492b-9a55-18f22ec026ca

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by Shenguobin0102** [comment]
你好，感谢反馈，我们会在后续版本修复。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
