### ISSUE TITLE
[Bug]【数据源】API 数据源 QUERY 参数页签删除行异常

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#7336]
**DataEase 版本**
v2.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
API 数据源 QUERY 参数页签当【键】和【值】点击第二行的删除按钮，删除不掉，点击第一行的删除按钮才能删除。
详见视频：
本地环境和客户环境皆有复现。

https://github.com/dataease/dataease/assets/24768910/03b9a055-94de-4fc3-9b27-53965e81c523

**Comment by Shenguobin0102** [comment]
你好，感谢反馈，我们会在后续版本修复。

**Comment by maninhill** [comment]
这个问题 v2.4 发版前再核对下。
