### ISSUE TITLE
[Feature]下拉框支持显示值和绑定值

### ISSUE THREAD

**Issue by x-light-ai** [dataease/dataease#7343]
**请描述您的需求或者改进建议.**
比如部门或者省份这种下拉框，过滤组件，下拉框能支持显示是文本，实际给组件的是数字id，不然如果只能用显示值去查询的话效率会非常非常低，因为数据库实际存储的一般都是关联id，或者编码

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，建议您试用下2.x版本，我们在2.x上做了优化，组件的显示值和绑定值进行了拆分。

**Comment by x-light-ai** [comment]
> 感谢反馈，建议您试用下2.x版本，我们在2.x上做了优化，组件的显示值和绑定值进行了拆分。

就是用的最新版本的2.x

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，目前选项值是拼接在where条件后，直接用于过滤数据的。我们先将需求记录进需求池中，后面根据需求优先级规划进版本迭代中。
