### ISSUE TITLE
[Feature] 漏斗图标签/提示支持展示转化率

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7346]
**请描述您的需求或者改进建议.**
漏斗图标签/提示支持展示转化率，如下所示：
![image](https://github.com/dataease/dataease/assets/30063018/68c79d01-cdc8-4397-9fae-6fbd986df0df)

**Comment by xuwei-fit2cloud** [comment]
图库本身可以支持，我们先记录一下需求。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
