### ISSUE TITLE
[Feature] 散点图的类别支持在横轴为维度时生效

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7351]
**请描述您的需求或者改进建议.**
散点图的类别支持在横轴为维度时生效
<img width="709" alt="image" src="https://github.com/dataease/dataease/assets/45852479/4d2827fe-96ff-47b2-a787-8aea6c0f901c">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by maninhill** [comment]
暂无支持计划。
