### ISSUE TITLE
希望新增箭头连接组件

### ISSUE THREAD

**Issue by pangzhili** [dataease/dataease#7354]
**请描述您的需求或者改进建议.**
假设一种场景，现在仪表板中存在a文本卡，b文本卡，c折线图，d趋势图，他们之间存在一种自下而上的连接关系，现在需要一个连接箭头来实现这种组织结构树的实现，类似如下结构，通过箭头指示，我能快速知道对应视图的关系，明确指示1，2的视图是由3组成的，这样视图还能帮助用户快速定位问题。

希望其他组件中新增 箭头 组件，用于连接多个视图，标识视图之间的层级关系。

![image](https://github.com/dataease/dataease/assets/46517296/49eb5470-d52e-4abb-8127-50a40e20f32e)

**Comment by pangzhili** [comment]
或者也可以是从左到右的排版，整个箭头比较顺滑

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，暂时没有计划支持，建议您上传本地的箭头文件。
