### ISSUE TITLE
[Bug] DataEase v2.1 无法连接 SQL Server 2008R2、2014 

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7358]
**DataEase 版本**
v2.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
Google Chrome
版本 120.0.6099.129（正式版本） (arm64)

**Bug 描述**
DataEase v2.1 无法连接 SQL Server 2008R2、2014 

**Bug 重现步骤(有截图更好)**
获取 Schema 时报错，具体报错截图如下所示：
![wecom-temp-173233-e9d60599c7fd8fe8596cdbb13411f90b](https://github.com/dataease/dataease/assets/30063018/866d1cd1-f042-4604-9705-7dca151fd7df)

**Comment by Shenguobin0102** [comment]
在额外的JDBC连接字符串中输入：encrypt=false，再试试

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持
