### ISSUE TITLE
[Feature]echarts 矩形树图点击某个维度后视图出现位移

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#7361]
**请描述您的需求或者改进建议.**
echarts 矩形树图，点击某个维度后，视图出现位移，用户体验不好，希望禁用该事件。

echarts 矩形树图，默认情况布满视图；
![图片](https://github.com/dataease/dataease/assets/48307752/b20da4e9-5d97-4a89-a9d5-08df758abaf2)

点击某个维度后，视图出现位移；
![图片](https://github.com/dataease/dataease/assets/48307752/0a933ae9-89be-483a-8f70-14e2bdb5bacf)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先看下图库是否支持。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
