### ISSUE TITLE
[Feature] 优化全量同步一张数据量较大的表

### ISSUE THREAD

**Issue by xinkeng0** [dataease/dataease#7367]
**请描述您的需求或者改进建议.**
我有一张数据量较大的表，大约在4千万左右，全量同步耗时大约2天之后依旧未完成。
## 建议
同步时，检测表是否有PK，有的话按照PK分段的去同步，不要直接limit。
```SQL
select * from demo where id >= 0 and id < 1000;
select * from demo where id >= 1000 and id < 2000;
···
```

**Comment by xuwei-fit2cloud** [comment]
感谢反馈和建议，同步这块的设定我们还需要持续增强，但4千万的数据按理来说不应该同步那么长时间还未完成。您可以在数据库里查看一下，是否该查询已结束。我们这边也会考虑一下如何去处理这种大数据量同步的场景优化。建议您可以使用增量同步的方式。

**Comment by maninhill** [comment]
暂无支持计划。
