### ISSUE TITLE
[Feature]柱状图或者折线图中，快速计算里的占比和指标无法同时显示，希望后面可以加入占比和指标值同时显示功能。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#7368]
**请描述您的需求或者改进建议.**
柱状图或者折线图中，快速计算里的占比和指标无法同时显示，只能显示指标的值，或者显示占比值，如果希望能同时看到指标值和占比值就无法实现，只能分成两个视图去展现，希望后面可以加入占比和指标值同时显示功能。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个需要等我们在后期版本支持了自定义标签内容后才可以支持，还请等待。

**Comment by maninhill** [comment]
6个月内无更新，关闭。
