### ISSUE TITLE
[Feature]ECHARTS图表标签数据为平均值 时无法设置数值格式，小数点位数。antv图表可以，希望ECHARTS图表也能支持

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#7369]
**请描述您的需求或者改进建议.**
ECHARTS图表标签数据为平均值 时无法设置数值格式，小数点位数。antv图表可以，希望ECHARTS图表也能支持。
![1703586957848](https://github.com/dataease/dataease/assets/83771182/3d8b72a3-4e35-4e92-87cd-99295e67edc0)

**Comment by xuwei-fit2cloud** [comment]
ECharts图表类型里目前都不支持数值格式化，与自定义标签和提示内容有冲突，短时间内还不好支持。
