### ISSUE TITLE
[Feature]下拉框支持显示值和绑定值-2.1版本

### ISSUE THREAD

**Issue by x-light-ai** [dataease/dataease#7372]
**请描述您的需求或者改进建议.**
比如部门或者省份这种下拉框，过滤组件，下拉框能支持显示是文本，实际给组件的是数字id，不然如果只能用显示值去查询的话效率会非常非常低，因为数据库实际存储的一般都是关联id，或者编码

使用的是最新2.1版本
![图片](https://github.com/dataease/dataease/assets/17698581/d4ee87e0-8661-46a9-87b8-bd2ac6262229)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈和支持，该issue已经加入需求池中，会在最近几个版本中进行支持，与issue：https://github.com/dataease/dataease/issues/7343 为重复issue，因此就先关闭了。
