### ISSUE TITLE
[Bug]系统管理-任务管理-数据同步，点击“添加任务”后，页面左侧导航栏自动消失

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#7373]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge120.0.2210.9

**Bug 描述**
系统管理-任务管理-数据同步，点击“添加任务”后，页面左侧导航栏自动消失变成空白

**Bug 重现步骤(有截图更好)**
1.进入：系统管理-任务管理-数据同步
2.点击“添加任务"按钮
3.页面左侧导航栏自动消失变成空白
![image](https://github.com/dataease/dataease/assets/77324661/43b3866f-61ce-4bcd-bdc4-d32084b0337d)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下此处；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请升级版本。
