### ISSUE TITLE
[Feature] 1.0 版本公链参数安全性优化

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#7375]
**请描述您的需求或者改进建议.**
版本：1.18.13
1、设计器中配置外部参数
2、创建仪表板公链，例如：http://[ip]:[port]/link/04sYHESV
3、使用  http://[ip]:[port]/link/04sYHESV?attachParams=adfasdfasdfasdfasdfasdfasdf 访问
因attachParams后的参数是base64加密，用户可以解密并篡改里面的参数后，在进行base64加密，得到新的url进行访问， 因此能否优化加密和验证参数的方案？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录一下需求，近期暂时没有计划进行优化。

**Comment by xiaorsly88** [comment]
可以考虑一下sha256，使用加密盐
