### ISSUE TITLE
[Bug]文本下拉组件默认值的动态首项，仪表板刷新时没有动态加载首项

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#7376]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
文本下拉组件设置开启默认值的动态首项，开启仪表板刷新，仪表板刷新时，下拉组件的过滤条件一直没有变化，且过滤条件没有生效，视图中展示了全部的数据
![image](https://github.com/dataease/dataease/assets/89771514/ca5335a9-12df-43c9-a1dd-35ba9d6627a1)

![image](https://github.com/dataease/dataease/assets/89771514/ace3d929-22fc-4719-9fc5-68fb1d74c18d)
![image](https://github.com/dataease/dataease/assets/89771514/587ab273-9af6-4434-8162-981e3d7a22b6)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前是不支持通过数据集去影响过滤组件的排序的，而这种使用方式也是不正确的，因为过滤组件是有其自己的排序控制的，不应该会受到数据集的影响；
