### ISSUE TITLE
dev-2.0 建议添加多轴图

### ISSUE THREAD

**Issue by provenceo** [dataease/dataease#7377]
**请描述您的需求或者改进建议.**
dev-2.0 建议添加多轴图
![image](https://github.com/dataease/dataease/assets/43238325/2a146896-5035-4ffd-8f89-3fae97ad266a)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈和支持，随着版本的迭代，图表类型会逐渐丰富起来，请多多关注我们的release notes 。

**Comment by xuwei-fit2cloud** [comment]
v2.6已添加。
