### ISSUE TITLE
[Bug]视图无法重命名

### ISSUE THREAD

**Issue by shenkaibo** [dataease/dataease#74]
**DataEase 版本**
v.1.0

**浏览器版本**
版本 91.0.4472.114

**Bug 描述**
1.视图无法重命名

**Bug 重现步骤(有截图更好)**
1.创建视图，保存。
2.无法重命名视图。
<img width="1298" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/30038088/123573489-a4b72e00-d800-11eb-93a7-054c089976bb.png">

**Comment by xuwei-fit2cloud** [comment]
视图的名称与标题一致，可通过选择【组件样式】，修改视图的标题来实现。
我们会在 v1.1.0 版本中视图的操作菜单里加上支持。

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已支持
