### ISSUE TITLE
[Feature] 辅助线制作，动态值可以选到 “记录数”

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7411]
**请描述您的需求或者改进建议.**
<img width="1396" alt="image" src="https://github.com/dataease/dataease/assets/45852479/f88c4992-05b1-462f-9e95-595556a63ea2">
<img width="1170" alt="image" src="https://github.com/dataease/dataease/assets/45852479/5e135149-0109-434e-8fd5-5d016a7f0311">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们下个版本优化一下。
