### ISSUE TITLE
[Feature] 柱状图柱宽支持调整

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7416]
**请描述您的需求或者改进建议.**
柱状图自适应的情况下，柱子较少时不太美观，希望能够支持柱宽的自定义调整。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，宽度和柱间距是图库经过计算，一个较好的呈现的结果，因此不建议调整。如果打开自定义后，会有较多不可控的情况，比如重叠、柱间距过大等。

**Comment by ziliang-wan** [comment]
自定义的情况下，重叠、间距过大等，其实是由制作图表的人主观控制的，问题应该不是很大，反而是很多时候，自适应的柱宽不够美观。

**Comment by maninhill** [comment]
暂无支持计划。
