### ISSUE TITLE
[Bug] v1.18.13 版本符号地图标签及提示显示不正确。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7419]
**DataEase 版本**
v1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 120.0.6099.129（正式版本） (arm64)

**Bug 描述**
数据集文本类型的字段转为时间后，制作符号地图
在标签或者提示里选择这个字段后，显示的格式仍然是转换前的文本格式。

**Bug 重现步骤(有截图更好)**
1. 数据集原始数据：
![image](https://github.com/dataease/dataease/assets/30063018/f61d6736-6d0f-4f36-af60-3c2548e8b359)

2. 字段管理里调整字段类型
![image](https://github.com/dataease/dataease/assets/30063018/56b07e97-5be4-4c05-924b-0a0c1439b23d)
![image](https://github.com/dataease/dataease/assets/30063018/d8c841c8-dad7-4600-9fd9-0d5ac0b957b4)

3. 制作符号地图
![image](https://github.com/dataease/dataease/assets/30063018/30c93389-a9c7-4814-b321-24269397da47)

4. 标签或提示选择该时间字段
![image](https://github.com/dataease/dataease/assets/30063018/11368f8f-c79d-4db4-a6a1-863117b56b50)
![image](https://github.com/dataease/dataease/assets/30063018/c5a4db95-daa6-4d54-aa13-2b7a4ba26d0d)

5. 时间字段显示的仍然为切换前的文本类型，非切换后的时间类型字段。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by fit2cloudrd** [comment]
处理代价太大，短期内暂不处理。
