### ISSUE TITLE
[Feature] DataEase v2 版本富文本支持指标数据的格式化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7444]
**请描述您的需求或者改进建议.**
希望能够支持富文本指标数据的格式化，目前是无法调整富文本的数值格式的
![image](https://github.com/dataease/dataease/assets/30063018/046e664e-1a41-4040-afcd-6b68a6166237)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期版本中会进行支持。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
