### ISSUE TITLE
[Bug] doris DATEV2 和 DATETIMEV2 被自动识别成了 文本类型

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7450]
**DataEase 版本**
v1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 120.0.6099.71（正式版本） (arm64)

**Bug 描述**
doris DATEV2 和 DATETIMEV2 被自动识别成了 文本类型（数据库数据集）

**Bug 重现步骤(有截图更好)**
<img width="864" alt="image" src="https://github.com/dataease/dataease/assets/45852479/41baebd7-fcbf-4adf-8b93-16edc861abcc">
<img width="1062" alt="image" src="https://github.com/dataease/dataease/assets/45852479/f409f857-3a7c-41db-a62f-0b41b7e7adb9">
<img width="993" alt="image" src="https://github.com/dataease/dataease/assets/45852479/04edb9ec-f14e-43b3-908f-f334888dbaec">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
