### ISSUE TITLE
[Feature] DataEase v1 公共链接下载按钮是否可配置不显示

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7461]
**请描述您的需求或者改进建议.**
当前公共链接下载按钮虽然是贴边显示的，但是有时候还是会挡住一些点击事件，如下所示，希望公共链接下载按钮可配置不显示。
<img width="1130" alt="wecom-temp-1299712-2b5ad0153829a3bfcd354fdaedc22902" src="https://github.com/dataease/dataease/assets/30063018/abfc823a-6c97-49ac-8a89-d9d74066e629">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们近期版本会优化一下这里的交互。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
