### ISSUE TITLE
[Bug] DataEase v1 社区版，配置跳转后的看板分享给用户后，用户跳转后提示无权限。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7462]
**DataEase 版本**
v1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**
Google Chrome
版本 120.0.6099.129（正式版本） (arm64)

**Bug 描述**
DataEase v1 社区版，配置了 A 看板跳转至 B 看板，将两个看板同时分享给用户
用户单独查看 A 、B 看板都没有问题，但是从 A 看板点击跳转至 B 看板时，会提示权限问题。

**Bug 重现步骤(有截图更好)**
1. 配置两个测试看板，并且配置测试看板跳转至测试看板1
![image](https://github.com/dataease/dataease/assets/30063018/d32a979e-938b-44cf-bb10-a2e571fcde37)
![image](https://github.com/dataease/dataease/assets/30063018/e227514e-0594-4351-b48d-3d1354082038)

2.将这两个看板都分享给用户，用户登录后单独打开都可以查看
![image](https://github.com/dataease/dataease/assets/30063018/6e5b97d7-ba3c-485a-aa43-2dc59fa1c875)

3.由测试看板跳转至测试看板1，提示权限问题
![image](https://github.com/dataease/dataease/assets/30063018/a515ea70-6f0d-454a-91b4-98415490236e)

**Comment by Shenguobin0102** [comment]
感谢反馈，我们会在后续版本修复。

**Comment by maninhill** [comment]
v1.18.16 发版前再核对下这个问题。
