### ISSUE TITLE
[Feature]过滤组件查询按钮可以根据实际情况选择是否显示

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#7467]
**请描述您的需求或者改进建议.**
可以让我们选择 保留或者 隐藏
<img width="834" alt="wecom-temp-38095-99516099a9c7c75b4ac93df313b7a812" src="https://github.com/dataease/dataease/assets/101089844/bce57589-fd13-4e40-b560-cc4ef86ea887">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，我们暂时没有计划去支持。
