### ISSUE TITLE
[Bug] 使用1Panel应用商店搭建的最新DataEase 登陆报java.lang.reflect.InvocationTargetException且无法登录

### ISSUE THREAD

**Issue by Wuqiyang312** [dataease/dataease#7468]
**1Panel 版本：1.9.2**
**DataEase 版本：2.1.0**

**运行方式(安装包运行 or 源码运行 ?)**
使用1Panel应用商店搭建的最新DataEase

**浏览器版本**
Microsoft Edge 119.0.2151.44 (正式版本)

**Bug 描述**
使用1Panel 应用商店搭建的最新DataEase 登陆时报 java.lang.reflect.InvocationTargetException
docker 运行日志：
 [1Panel-dataease-k1yJ-20231229120047.log](https://github.com/dataease/dataease/files/13790882/1Panel-dataease-k1yJ-20231229120047.log)

**Bug 重现步骤(有截图更好)**
1.按照1Panel应用商店的提示安装DataEase 及 mysql
2.输入密码出现报错
![image](https://github.com/dataease/dataease/assets/86960631/6d8bb497-92fa-4545-86f4-3eb8d2a9d5a9)

**Comment by BBchicken-9527** [comment]
感谢反馈，方便给我一份de的日志看一下吗？

**Comment by Wuqiyang312** [comment]
[https://github.com/dataease/dataease/files/13791142/1Panel-dataease-k1yJ-20231229120047.log](https://github.com/dataease/dataease/files/13791142/1Panel-dataease-k1yJ-20231229120047.log)

**Comment by Wuqiyang312** [comment]
> 感谢反馈，方便给我一份de的日志看一下吗？

[https://github.com/dataease/dataease/files/13791142/1Panel-dataease-k1yJ-20231229120047.log](https://github.com/dataease/dataease/files/13791142/1Panel-dataease-k1yJ-20231229120047.log)

**Comment by BBchicken-9527** [comment]
感谢反馈，受累看一下core_rsa表有没有记录，如果有刷新浏览器，如果没有清空库重新启动，看看收否能解决你的问题；

**Comment by Wuqiyang312** [comment]
> 感谢反馈，受累看一下core_rsa表有没有记录，如果有刷新浏览器，如果没有清空库重新启动，看看收否能解决你的问题；

谢谢可以登录了

**Comment by wumindc** [comment]
@Wuqiyang312 请问下默认账号密码是什么，我到处都找不到欸

**Comment by Wuqiyang312** [comment]
> @Wuqiyang312 请问下默认账号密码是什么，我到处都找不到欸

v1.* 账号：admin 密码：dataease
v2.* 账号：admin 密码：DataEase@123456

**Comment by wumindc** [comment]
@Wuqiyang312 谢谢
