### ISSUE TITLE
[Feature]自定义x,y轴起始点功能+自定义y轴跨度功能

### ISSUE THREAD

**Issue by User-debbie** [dataease/dataease#747]
【功能描述】希望加入x,y轴起始点功能 和 自定义y轴跨度功能
【应用场景】当数据基数较大，数据之间差距较小时，很难看出数据之间的差异，所有柱状图看起来都是一样的高度。希望可以自定义y轴起始点和y轴跨度，从图上放大数据间的差异情况。

**Comment by xuwei-fit2cloud** [comment]
v1.3.0 会支持

**Comment by User-debbie** [comment]
好的，谢谢，柱状图，折线图都挺需要这个功能的！


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: xuwei-fit2cloud ***@***.***&gt;
发送时间: 2021年9月6日 14:57
收件人: dataease/dataease ***@***.***&gt;
抄送: User-debbie ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[dataease/dataease] [Feature]自定义x,y轴起始点功能+自定义y轴跨度功能 (#747)





 
v1.3.0 会支持
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
