### ISSUE TITLE
[Feature]SQL数据集支持LATERAL VIEW EXPLODE语法

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#7485]
**请描述您的需求或者改进建议.**
dataease版本：1.18.13
SQL数据集增加参数后，若SQL中使用了LATERAL VIEW EXPLODE语法，会导致报错。
dataease1.18.13版本中使用的JSQLParser来解析sql语法，JSQLParser官方已经更新到4.8版本，并且支持了LATERAL VIEW EXPLODE语法。
希望dataease也能更新下JSQLParser版本，支持sql数据集中使用LATERAL VIEW EXPLODE语法。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，那我们升级一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。

**Comment by hw872715125** [comment]
更新到v1.18.15后，较多的sql使用场景下，查询报错，如使用了in语法和select a,b,c from(select a,b,c from (子查询) t1 left join (select d,e,f from (子查询) t2 union all (子查询)) ) 这种语法下也会有报错，目前我发现的有这两种。
