### ISSUE TITLE
[Bug]仪表盘分享给 用户后，以该用户登录后无法查看

### ISSUE THREAD

**Issue by shenkaibo** [dataease/dataease#75]
**DataEase 版本**
v1.10

**浏览器版本**
版本 91.0.4472.114

**Bug 描述**
仪表盘分享给 用户后，以该用户登录后无法查看

**Bug 重现步骤(有截图更好)**
1.创建仪表盘，分享给对应用户
2.用该用户账号登录，并未看见对应的仪表盘
<img width="1208" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/30038088/123574418-5e62ce80-d802-11eb-9bd6-2518ad660618.png">
<img width="619" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/30038088/123574419-5e62ce80-d802-11eb-84c5-d4f842dde59d.png">

**Comment by xuwei-fit2cloud** [comment]
点击【分享】Tab 页，可以查看到他人给你分享的所有仪表板。
