### ISSUE TITLE
[Feature] 长链接校验

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7500]
**请描述您的需求或者改进建议.**
同一个仪表板公共链接关闭-打开-关闭-打开，这中间会有两个短链 A1，A2，那么对应长链 B1，B2，此时 A1无法访问，A2 可以访问，但是 B1，B2 都可以正常访问
此时长链接 B1 应该无法访问才对

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
