### ISSUE TITLE
[Feature] 权限框支持半选效果

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7501]
**请描述您的需求或者改进建议.**
<img width="789" alt="image" src="https://github.com/dataease/dataease/assets/45852479/997668d4-1a9c-42df-8c42-e51f8ef42c7b">
效果如下
![image](https://github.com/dataease/dataease/assets/45852479/a99597c8-9a61-425c-a4ae-5d4c6f38b464)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，暂时没有计划调整。
