### ISSUE TITLE
[Feature]l建议增加表格整体居中功能

### ISSUE THREAD

**Issue by kkljcf** [dataease/dataease#7502]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/125198800/b1bfa67c-51b3-4587-ac04-23e70d0d995f)
 如图，一个明细表内容他可以居中对齐这些方式了。
但是最后整张表格还是左对齐。

建议：可以正常表增加对齐方式。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议您调整一下表格样式「列宽调整」
<img width="357" alt="image" src="https://github.com/dataease/dataease/assets/84168063/8a0e49df-2196-483f-b8ca-7fa3c65618d0">

**Comment by kkljcf** [comment]
> 感谢您的反馈，建议您调整一下表格样式「列宽调整」 <img alt="图像" width="357" src="https://private-user-images.githubusercontent.com/84168063/293822174-8a0e49df-2196-483f-b8ca-7fa3c65618d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNDkwMTMsIm5iZiI6MTcwNDI0ODcxMywicGF0aCI6Ii84NDE2ODA2My8yOTM4MjIxNzQtOGEwZTQ5ZGYtMjE5Ni00ODNmLWI4Y2EtN2ZhM2M2NTYxOGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDAyMjUxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwODhmOGE5NmExYmYyNzllZTBlY2U4ODhlMjMwODNiNjAyZGM1ZTQ3NWJkYTFkNjU1OGVmODk2ZDNmNzZhNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cnqyi4L2KQv7TNO_4fdrnTTIxgGvh3E1qvEAKy12dy8">
内容实时变化，只能自适应

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，经过评估，目前暂时不考虑支持该功能，待收集更多用户需求后再做进一步的规划，也欢迎您向DataEase开源项目提交pr。
