### ISSUE TITLE
[Feature]建议定时同步的数据集 也可以使用全局参数

### ISSUE THREAD

**Issue by zhoulel** [dataease/dataease#7504]
**请描述您的需求或者改进建议.**
建议定时同步的数据集 也可以使用全局参数
![image](https://github.com/dataease/dataease/assets/139849659/31827a62-0095-4b4a-acaf-fde220045c76)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，直连和定时同步的处理是不一样的。

直连，是直接将sql语句传回数据源，查询后并返回结果。
定时同步，是根据sql语句从数据源中读取数据存储至doris，查询数据集数据时，是直接从doris查全量数据，并不走sql查询，因此支持了参数也是不生效的。

Issue我们先关闭了，如果您有不错的建议，欢迎随时沟通交流，微信号：18317092178。
