### ISSUE TITLE
[Feature] 柱状图、折线图支持可根据维度之外的字段进行排序

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7507]
**请描述您的需求或者改进建议.**
柱状图、折线图支持可根据维度之外的字段进行排序，有些时候，作为维度项展示的内容排序会存在一些问题，希望能有另外一个字段支持辅助排序。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，由于柱状图、折线图等均是根据维度，对指标进行聚合后的结果，因此只能根据视图中的字段进行排序，当前暂时没有计划支持视图之外的字段进行排序。
