### ISSUE TITLE
[Question]v1.3.0 的版本规划和时间

### ISSUE THREAD

**Issue by xuwei-fit2cloud** [dataease/dataease#751]
**请描述您的问题.**
V1.3.0 的版本规划和时间

**Comment by xuwei-fit2cloud** [comment]
v1.3.0 计划10月14日发布，该版本的计划内容有：

仪表板:

  1. 列表增加搜索功能
  2. 支持导出pdf
  3. 增加tab组件支持

视图:

  1. 新增图表类型：瀑布图
  2. 柱状图、折线图、叠加图等有纵坐标的图表类型，支持设置纵坐标起始和结束值范围
  3. 组合图表支持
  4. 柱形图，折线图等图形，可设置双Y轴

数据源:

  1. 支持 ClickHouse 数据源
  2. 支持 ElasticSearch 数据源

系统管理:

  1. 消息中心支持通过邮件配置，自动推送邮件

**Comment by maninhill** [comment]
v1.3 已经发布，具体请查看：https://github.com/dataease/dataease/releases/tag/v1.3.0
