### ISSUE TITLE
[Bug]仪表盘中的表格拖动条就不见了

### ISSUE THREAD

**Issue by 2581218163** [dataease/dataease#7510]
**DataEase 版本**
社区办2.1.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome

**Bug 描述**
仪表盘中的表格拖动条就不见了

**Bug 重现步骤(有截图更好)**
1.
![5bef9c80fdc80e64fe1badfb5ab73c2](https://github.com/dataease/dataease/assets/45324237/11df4650-ec12-4250-ab7c-af40557d7b90)

2.
![7cf6fde8dcc1e93787f4c1a8cd38e4e](https://github.com/dataease/dataease/assets/45324237/97f4bd30-a9dd-4c54-8122-08a6abf46409)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
