### ISSUE TITLE
[Bug] 视图过滤器过滤条件sql拼接错误

### ISSUE THREAD

**Issue by yuqun-nj** [dataease/dataease#7511]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
109.0.5414.120

**Bug 描述**
通过数据集修改字段类型之后，视图过滤器的过滤条件sql依旧使用原始字段做过滤

**Bug 重现步骤(有截图更好)**
1、添加视图过滤器选择字段进行过滤，查看sql结果为
<img width="736" alt="image" src="https://github.com/dataease/dataease/assets/97491875/45ca108f-f95b-4beb-a895-a8db0c435614">
2、修改数据库字段为文本类型后再选择该字段过滤，查看sql结果为
<img width="728" alt="image" src="https://github.com/dataease/dataease/assets/97491875/08125d7d-303a-4755-b61d-950fdd4751ea">
3、可以发现两次过滤的条件都是通过原始字段进行过滤，这样会导致修改数据集字段类型后过滤条件不生效的情况

**Comment by BBchicken-9527** [comment]
感谢反馈，我看你的截图没有什么问题额，改变字段类型后的id是不会变化的，为什么说是使用原始字段呢？而且就算你修改了字段类型也不影响图表过滤器的生效的；是你的数据没有找到吗？方便说一下你使用的数据源以及找不到的字段类型是什么吗？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
