### ISSUE TITLE
[Feature]v1版本 透视表 “数据行/维度”这里面的字段，字体大小、加粗等不能调整

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#7515]
v1版本 透视表 “数据行/维度”这里面的字段，字体大小、加粗等不能调整；相当于表格外框一圈都不能调整，只有里面白色底色的单元格字体可以调整。
<img width="467" alt="2cebc1b60edd5c08fe5c901b66575f64" src="https://github.com/dataease/dataease/assets/141667200/b47b02e5-721f-42cb-a217-16fcba271ec3">
![image](https://github.com/dataease/dataease/assets/141667200/d2c90f3d-7c43-429f-b3e7-583cc156d718)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，字体、加粗等目前图库不支持，字体大小建议调整如下设置项：
<img width="946" alt="image" src="https://github.com/dataease/dataease/assets/84168063/3bd7be77-d622-4847-9030-566d3936f9a5">
