### ISSUE TITLE
[Feature]建议数据的维度与指标的选取可以灵活性

### ISSUE THREAD

**Issue by bnuzhangshl** [dataease/dataease#7516]
**请描述您的需求或者改进建议.**
因为同一个仪表盘中，对于数据的要求不同，目前“类别轴 / 维度”、“值轴 / 指标”定义的不灵活，建议可以参考navicat的图表功能。
“类别轴 / 维度”可以使用指标，“值轴 / 指标”也可以使用维度，这样灵活度更高。
如果只是将数据集中的维度和指标进行转换，对于不同的数据图形，还是难以满足的。
谢谢

**Comment by bnuzhangshl** [comment]
目前使用的版本是V1.18

**Comment by maninhill** [comment]
暂无支持计划。
