### ISSUE TITLE
[Bug]视图过滤字段与自定义函数冲突导致报错

### ISSUE THREAD

**Issue by hzhwyh0116** [dataease/dataease#7518]
**DataEase 版本**
v1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 

**Bug 描述**

1、数据源是 MariaDB
2、数据集是SQL直连数据集，SQL如下：
SELECT
 posting_number 订单号,
 tracking_number 运单号,
 customer_address_address_tail 买家地址,
 in_process_at,
  get_name_shujzd(status,'fbs_status') 状态,
 offer_id 商品sku,
 delivery_method_tpl_provider 快递方式,
 customer_name 买家姓名,
 customer_customer_email 买家邮箱,
 price 价格,
 cost 商品成本,
 commission_amount 佣金,
 quantity 商品数量
FROM
 v3_posting_fbs_list_info;

其中【状态】字段 引用了 MariaDB 中自定义函数 get_name_shujzd(status,'fbs_status') ，函数如下：
![image](https://github.com/dataease/dataease/assets/89765365/dea07696-f80c-4514-8b2b-975949e19437)

3、视图类型选择的横向柱状图，当视图添加过滤字段时视图报错，AntV、Echarts 均报错
![image](https://github.com/dataease/dataease/assets/89765365/bb69c117-5bb3-4d65-b5aa-1834d92cef9f)
![image](https://github.com/dataease/dataease/assets/89765365/f16021de-0d31-4fd1-a348-ef5b01d9844e)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，不过新版本会对此处进行大的改造可以升级尝试；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持
