### ISSUE TITLE
[Bug]升级至v1.2.0点击【系统管理】菜单，出现接口报错

### ISSUE THREAD

**Issue by SLD-Allen** [dataease/dataease#752]
**DataEase 版本**
v1.2.0

**浏览器版本**

版本 92.0.4515.159（正式版本） （64 位）
**Bug 描述**
![image](https://user-images.githubusercontent.com/89327023/131802676-958f992e-fe74-4688-93fc-7ec08aae1f9c.png)
![image](https://user-images.githubusercontent.com/89327023/131803041-381438dc-3944-4529-b313-9b69931853e5.png)

**Bug 重现步骤(有截图更好)**
1.升级至v1.2.0版本
2.登录系统，点击【系统管理】菜单
3.出现/api/role/all not found.错误提示

是后端未上线的角色管理新功能的 代码 在1.2.0前端调用了？

**Comment by xuwei-fit2cloud** [comment]
您可以清理一下浏览器缓存试试
