### ISSUE TITLE
[Feature] V1版本 表格功能建议

### ISSUE THREAD

**Issue by 2581218163** [dataease/dataease#7520]
①   柱状图的列名能不能设置最大值显示,多出的部分隐藏起来,鼠标移到上面在显示完整的。因为现在的名字太长导致柱状图很丑
![208475d5d0f0a65837b9657e1713fdd](https://github.com/dataease/dataease/assets/45324237/b7901547-e614-45d2-8edf-6b4912996ff6)
②   表格中能否支持图片url预览功能,就是数据库查出来一个图片的url,然后放在表格中预览出来

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，回复如下：
第一个建议我们规划在近期的版本中优化一下，请关注一下我们的release notes；
第二个建议目前暂不考虑支持。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
