### ISSUE TITLE
[Question] v1.18.14 升级后连接数据库异常 "Datasource is invalid: 当前驱动不支持此版本!"

### ISSUE THREAD

**Issue by tzengshinfu** [dataease/dataease#7521]
**DataEase 版本**
v1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome v120.0.6099.200

**问题描述**
今早执行`dectl upgrade`升级成功后，
发现有几支报表显示错误讯息`Datasource is invalid: 当前驱动不支持此版本!`而无法运行，
数据来源都是MSSQL 2014，但DataEasev1.18.14的MSSQL驱动版本只支持13,14,15,16(MSSQL 2016~2022)，
请问能否自行增加驱动？
![image_20240104_082402](https://github.com/dataease/dataease/assets/2170033/59c63a70-23c2-4b1c-9760-6d1e18049d25)
![image_20240104_082416](https://github.com/dataease/dataease/assets/2170033/4ddc6a75-722c-45c5-9c1e-eb754c463e73)

**Comment by zqj50** [comment]
我也遇到这个问题了，请问解决了吗？

**Comment by tzengshinfu** [comment]
查找文檔后发现数据源也能自己扩展
[https://dataease.io/docs/v1/dev_manual/dev_datasource_plugin/](https://dataease.io/docs/v1/dev_manual/dev_datasource_plugin/)

如果官方没时间处理，下周我应该会开始着手进行**旧版MSSQL数据源**的插件开发...

**Comment by zqj50** [comment]
https://bbs.fit2cloud.com/t/topic/2815/19
我的问题解决了，参考这个，不过我的版本是2012

**Comment by tzengshinfu** [comment]
[zqj50](https://github.com/zqj50):
谢谢您的热心帮忙找到上传驱动的方法；
但是我这边在上传驱动文件后按钮状态一直是[上传中...]。
(近一个小时，驱动文件本身不到2MB。)

执行`dectl restart`重启服务，也清除浏览器快取，还是会这样。
只能看官方的回复了。

- 主机error.log
[error.log](https://github.com/dataease/dataease/files/13842604/error.log)
- 上传页面console log
![image_20240105_213130](https://github.com/dataease/dataease/assets/2170033/596428bb-0bf1-45e1-b04a-ca418c710a11)

**Comment by tzengshinfu** [comment]
自问自答，这个错误讯息是主机的Nginx服务默认有上传1MB大小的限制，修改nginx.conf(加上红框处)之后重启，服务驱动文件已上传正常。
![image_20240108_100813](https://github.com/dataease/dataease/assets/2170033/b57aa8fc-6a44-4284-a23f-fe5af5cea2eb)

但在校验时又遇到问题，
![image_20240108_100512](https://github.com/dataease/dataease/assets/2170033/ea7a0866-5f74-4fb4-aba7-e5dd1afa466a)

这在数据源配置>额外的JDBC连接字符串加上`trustServerCertificate=true`就可正常。
![image_20240108_101315](https://github.com/dataease/dataease/assets/2170033/4370d7d9-2a68-4f28-9db7-8926916c5555)

已经搞定，谢谢[zqj50](https://github.com/zqj50)的帮忙啊！

**Comment by f2m4** [comment]
自己上传的驱动无法进行 定时同步.......
