### ISSUE TITLE
[Bug] 两个不同浏览器打开仪表板删除或新增不同步问题

### ISSUE THREAD

**Issue by pangzhili** [dataease/dataease#7522]
**DataEase 版本**
官方最新版本

**浏览器版本**
chrome

**Bug 描述**
新增仪表板的问题：
第一步：分别使用两个浏览器打开仪表板页面，我这里是chrome和360急速浏览器，新建测试目录22
![image](https://github.com/dataease/dataease/assets/46517296/116fb0fd-1fd6-4b14-95c8-52ffc3682336)
第二步：在360急速浏览器上的22目录下新建仪表板aa，仪表板正常显示在目录下
![image](https://github.com/dataease/dataease/assets/46517296/43786170-8d4a-4ac2-9a2a-72b02f27f918)
第三步：切换到chrome浏览器上的仪表板页面，刷新浏览器，此时22目录下无内容
![image](https://github.com/dataease/dataease/assets/46517296/c100572d-06c0-4995-9ea6-82aded95445d)
第三步：再次刷新才会出现aa仪表板
![image](https://github.com/dataease/dataease/assets/46517296/8d3b9663-ae9d-4675-9006-1b628028d99b)

删除仪表板的问题和新增类似，在360急速浏览器上删除aa仪表板后切换到chrome浏览器该仪表板仍会存在，点击仪表板报错
![image](https://github.com/dataease/dataease/assets/46517296/fd43a39e-db6c-474a-ab10-9a9bf31d5478)

**Comment by Shenguobin0102** [comment]
感谢反馈，我们会在后续版本修复。

**Comment by xuwei-fit2cloud** [comment]
目前不支持协同操作，所以确实会存在该情况，短期内还没有支持计划。
