### ISSUE TITLE
@antv/g2/esm/core这个包安装不了

### ISSUE THREAD

**Issue by seveneElevenup** [dataease/dataease#7524]
Failed to resolve import "@antv/g2/esm/core" from "src\views\chart\components\js\panel\types\impl\g2plot.ts". Does the file exist?

**Comment by yinyixie** [comment]
do not use cnpm install , use npm install

**Comment by seveneElevenup** [comment]
> do not use cnpm install , use npm install

![image](https://github.com/dataease/dataease/assets/50972125/c66a4230-8a97-400e-8be9-22d15325439f)
![image](https://github.com/dataease/dataease/assets/50972125/795ecf55-1f0c-4f15-9070-d9c28d44d80b)

**Comment by yayanpei-fit2cloud** [comment]
Thank you for your feedback , please try switching NPM based on network.

**Comment by zxh666a** [comment]
> > do not use cnpm install , use npm install
> 
> ![image](https://private-user-images.githubusercontent.com/50972125/294138414-c66a4230-8a97-400e-8be9-22d15325439f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxOTkwMzgsIm5iZiI6MTcwNzE5ODczOCwicGF0aCI6Ii81MDk3MjEyNS8yOTQxMzg0MTQtYzY2YTQyMzAtOGE5Ny00MDBlLThiZTktMjJkMTUzMjU0MzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDA1NTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NWRlYjY4ZDk0ZjE0YmJkZGUzZGU2YTdiNjE2ZWJiNDk3YWZiNzJkMTIwYzVjMGI1MTZiNzU2YmFiYTgzNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F8dYC8JiuvbVeFmBxzdW7Lin65B6mp6QyssCG9ne4Xk) ![image](https://private-user-images.githubusercontent.com/50972125/294142407-795ecf55-1f0c-4f15-9070-d9c28d44d80b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxOTkwMzgsIm5iZiI6MTcwNzE5ODczOCwicGF0aCI6Ii81MDk3MjEyNS8yOTQxNDI0MDctNzk1ZWNmNTUtMWYwYy00ZjE1LTkwNzAtZDljMjhkNDRkODBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDA1NTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYjFkNTJkNzc4MTQ0YTgwNDgzYWJhNGM1NjZhYzQzNmIxMjM1OTlmZTkyOGIxODY0OTc3YjkzODlhMTZmMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FfZKSh6p7NbS6Ny73zMAWeUiI_rgDqIxi6Idp0_gz2U)

请问这个问题解决了吗，我也遇到了

**Comment by seveneElevenup** [comment]
切最新的分支去处理npm i 就好了
