### ISSUE TITLE
[Feature]2.3版本支持下拉树多选框，且支持自定义传参

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#7525]
期望2.3版本支持下拉树多选框，且支持自定义传参控制.  
展示的场景下需要展示多级， 某些是只做展示，某一些需要传递参数给面板.

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，下拉树组件计划安排在 v2.5或者v2.6 版本中进行实现。

**Comment by 172151295** [comment]
> 感谢您的反馈，下拉树组件计划安排在 v2.5或者v2.6 版本中进行实现。

什么时候支持分享？？？

**Comment by maninhill** [comment]
2月1日发布v2.3版本，支持分享。

**Comment by 172151295** [comment]
> 2月1日发布v2.3版本，支持分享。

可以牛

**Comment by 18927580527** [comment]
感谢您的反馈，下拉树组件计划安排在 v2.5或者v2.6 版本中进行实现。
@yayanpei-fit2cloud @xuwei-fit2cloud 
---------
这个v2.5里面没有看到有， v2.6, v2.7也没看到有排期呀。
