### ISSUE TITLE
[Feature]v2数据集不支持ORACLE试图

### ISSUE THREAD

**Issue by hapeacock** [dataease/dataease#7526]
v2数据集不支持ORACLE试图

**Comment by hapeacock** [comment]
V1的能看到。V2看不到

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请问是查看并使用oracle数据源中的view，是吗？预计在下个版本中进行支持，与issue：https://github.com/dataease/dataease/issues/7539 重复，因此先关闭了，还请及时关注我们的release notes。
