### ISSUE TITLE
[Question]开源版本是否支持把报表嵌入到自己的系统

### ISSUE THREAD

**Issue by toughhou** [dataease/dataease#7527]
**请描述您的问题.**
请问一下，开源版本是否支持把报表嵌入到自己的系统？如果可以的话需要怎么做？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，开源版本是不支持嵌入第三方系统的。嵌入式相关功能需要购买license，建议您先申请license试用一下，申请链接请见：https://jinshuju.net/f/TK5TTd
