### ISSUE TITLE
[Feature] 区间条形图需求&优化

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7528]
**请描述您的需求或者改进建议.**
1. 纵轴标签和轴线重合
<img width="642" alt="image" src="https://github.com/dataease/dataease/assets/45852479/42583617-54cc-4cf5-a8fe-5cbbdde8face">
2. 允许配置子维度用于图例展示、允许不做聚合（或者允许一行展示多个矩阵）
<img width="868" alt="image" src="https://github.com/dataease/dataease/assets/45852479/e83c6b02-796f-4c37-957a-139ef72349af">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
我们下个版本优化一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
