### ISSUE TITLE
[Bug]最新1.18.14明细表没数据了

### ISSUE THREAD

**Issue by kkljcf** [dataease/dataease#7529]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
一键安装命令的，我也不知道

**浏览器版本**
任何浏览器都不行

**Bug 描述**
明细表数据报错

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你添加了图表所需要的字段了吗？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
