### ISSUE TITLE
[Bug] 报错 - 请选择组件

### ISSUE THREAD

**Issue by wonderfulwxw** [dataease/dataease#753]
**DataEase 版本**
1.1.11

**浏览器版本**
chrome Version 92.0.4515.159 (Official Build) (64-bit)

**Bug 描述**
在任何一个输入框位置， 点ctrl V 都会有这个报错...

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/38770463/131826321-1f7d9d4c-82f9-4bbd-b1f7-f0cbb5f9f381.png)

**Comment by yayanpei** [comment]
感谢您的反馈，我们尽快验证并修复。

**Comment by xuwei-fit2cloud** [comment]
v1.3.0 版本已修复
