### ISSUE TITLE
[Question]Could not resolve dependencies for project io.dataease:backend:jar:1.18.14: Failed to collect dependencies at io.dataease:dataease-plugin-interface:jar:1.18.14

### ISSUE THREAD

**Issue by allen001** [dataease/dataease#7530]
**请描述您的问题.**
[ERROR] Failed to execute goal on project backend: Could not resolve dependencies for project io.dataease:backend:jar:1.18.14: Failed to collect dependencies at io.dataease:dataease-plugin-interface:jar:1.18.14: Failed to read artifact descriptor for io.dataease:dataease-plugin-interface:jar:1.18.14: Failure to find io.dataease:dataease:pom:1.18.14 in https://repo.orl.eng.hitachivantara.com/artifactory/pnt-mvn/ was cached in the local repository, resolution will not be reattempted until the update interval of pentaho-public has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，源码安装部署报错的我们原则上是不支持帮忙排查原因的，建议您尝试清空本地maven仓库中dataease-plugin-interface相关的内容，并重新构建试试。
