### ISSUE TITLE
建议表格显示时，前端可以按照内容填写逻辑，然后渲染

### ISSUE THREAD

**Issue by rsj0315** [dataease/dataease#7531]
[**请描述您的需求或者改进建议.**[](url)]([url](![微信图片_20240107205909](https://github.com/dataease/dataease/assets/61722745/bde6d4fe-f832-4a3c-9356-e7b575ab7ed3)))
根据√或者x，表格显示内容可以显示不同颜色便于区分

**Comment by rsj0315** [comment]
![微信图片_20240107205909](https://github.com/dataease/dataease/assets/61722745/317d5d80-c92d-4f0b-b13b-ff4885ffc68b)
效果如图

**Comment by wolf-kingx** [comment]
可以在阈值里面设置背景颜色达到这样的效果

**Comment by wolf-kingx** [comment]
<img width="528" alt="1d326a34a34605e4a8a74ff01e80f43d" src="https://github.com/dataease/dataease/assets/141667200/c0e2c1b2-904e-4471-b651-ff278250bf52">
