### ISSUE TITLE
[Bug]明细表视图进行跳转设置，设置某一个字段跳转打开外部链接，点击其他字段同样出现跳转

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#7533]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
明细表视图进行跳转设置，设置 字段A 跳转打开 外部链接A，设置 字段B 跳转打开 外部链接B，点击A/B字段跳转都没有问题，但是字段C没有设置跳转的情况下，点击字段C也会跳转到外部链接A
![image](https://github.com/dataease/dataease/assets/89771514/f71ee2e5-5490-4aa4-87e8-218b0072a14b)

**Comment by Shenguobin0102** [comment]
感谢反馈，我们会在后续版本修复。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
