### ISSUE TITLE
[Bug] DataEase v1.18.14，simple 模式部署，Excel 文件上传失败

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7534]
**DataEase 版本**
v1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 120.0.6099.129（正式版本） (arm64)

**Bug 描述**
 DataEase v1.18.14，simple 模式部署
Excel 文件最后一列存在数值为空的，上传就会失败，详情见如下视频

**Bug 重现步骤(有截图更好)**

https://github.com/dataease/dataease/assets/30063018/32da4be3-c3eb-4658-81b7-580861b261fa

测试文件可参考如下：
[测试.xls](https://github.com/dataease/dataease/files/13856043/default.xls)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下一个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
