### ISSUE TITLE
[Bug]doris数据源sql数据集使用collect_set函数，数据集预览异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#7535]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
doris 数据源 2.0.2版本

新建sql数据集：SELECT _col0,array_size(collect_set(_col1)) 测试 from test111 GROUP by _col0
编辑数据集页面运行查询没有问题，保存后数据集预览页面报错
![image](https://github.com/dataease/dataease/assets/89771514/1aa53d4b-1f15-41fd-8856-190c38863961)
![image](https://github.com/dataease/dataease/assets/89771514/1827266e-1c73-4a90-801e-b976911c7df7)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
