### ISSUE TITLE
[Bug]SQL 变量只能在 WHERE 条件中使用

### ISSUE THREAD

**Issue by zqj50** [dataease/dataease#7536]
**DataEase 版本**
1.18.14
sql server 2012

**浏览器版本**
chrome

**Bug 描述**

sql server里面通过查询一有一个问题：查询参数不是在最后的一段where里面，这时，用这段sql会提示SQL 变量只能在 WHERE 条件中使用
![image](https://github.com/dataease/dataease/assets/3654942/4a97352e-7834-477d-9fa2-8ca97207ba3b)

请问这个参数问题何时可以进行优化？

**Comment by BBchicken-9527** [comment]
感谢反馈，你说的是参数化是吗？截图不是很能看清你的sql，方便给一个清晰的版本看一下吗？

**Comment by zqj50** [comment]
> 感谢反馈，你说的是参数化是吗？截图不是很能看清你的sql，方便给一个清晰的版本看一下吗？

select 
                                      distinct vbsl.FNAME as FSaleMan,--销售员
                                      ISNULL((select 
                                      SUM(pse.FAMOUNT)
                                      from PAEZ_SXJD_SKD pss 
                                      inner join PAEZ_SKD_Entry pse on pss.FID=pse.FID
                                      inner join V_BD_SALESMAN_L vbsl2 on vbsl2.FID=pss.FSALER
                                      where  DATEDIFF(YEAR,pss.FRECEIVABLESDATE,'${fyear}')=0 and pss.FORGID = tool.FORGID and vbsl2.FNAME=vbsl.FNAME),0) as FYearSaleManReceiveAmount--年销售员收款金额
                                      from V_BD_SALESMAN vbs 
                                      inner join V_BD_SALESMAN_L vbsl on vbsl.FID=vbs.FID
                                      inner join T_ORG_ORGANIZATIONS_L tool on tool.FORGID=vbs.FBIZORGID
                                      where vbs.FFORBIDSTATUS='A'
                                      and tool.fname = '${forgname}'
这个时候就会报SQL 变量只能在 WHERE 条件中使用

**Comment by zqj50** [comment]
帮我看一下呀？

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by fit2cloudrd** [comment]
目前还无法在函数里支持参数，短期内还无法支持。
