### ISSUE TITLE
[Bug]doris数据源，添加视图计算字段使用array_size(collect_set())函数语法报错

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#7537]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**Bug 描述**
添加视图计算字段 array_size(collect_set()) 报错：字段表达式语法错误
![image](https://github.com/dataease/dataease/assets/89771514/7392d575-604d-4212-a592-05782206039c)

doris是支持此函数的
<img width="1336" alt="image" src="https://github.com/dataease/dataease/assets/89771514/dc41d22c-09af-419f-998b-da5934b3de07">

**Comment by BBchicken-9527** [comment]
感谢反馈，请问是直连还是定时同步？以及环境的doris是什么版本的？

**Comment by ZhaoQian1222** [comment]
doris 数据源 2.0.2版本
直连模式

**Comment by ZhaoQian1222** [comment]
同#7535，此issue关闭
