### ISSUE TITLE
[Question]v2版本不再支持MongoDB了吗

### ISSUE THREAD

**Issue by rzsjason** [dataease/dataease#7540]
数据源只看到MongoDB-BI，没有MongoDB。
插件也没有。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，如果是MongoDB数据源，建议直接使用Mongo-BI。

**Comment by rzsjason** [comment]
后续会支持MongoDB吗

**Comment by yayanpei-fit2cloud** [comment]
目前暂时没有规划支持，如果使用过程中出现不兼容的情况，我们会根据用户反馈情况再做下一步的规划。
