### ISSUE TITLE
[Bug]AntV组合图无法使用日期维度

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#7542]
**DataEase 版本**
v1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge最新

**Bug 描述**
如图，使用 AntV 组合图时，如果维度是日期类型，横轴显示异常，实际表中有很多数据，但视图中只显示了一个。

![image](https://github.com/dataease/dataease/assets/30886198/5ad5c29b-ca03-4354-827b-8f090cbfb9c3)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问使用的是什么数据源？是直连还是定时同步？

**Comment by liuboF2c** [comment]
> 感谢反馈，请问使用的是什么数据源？是直连还是定时同步？

用的Excel数据集

**Comment by BBchicken-9527** [comment]
目前测试环境没有发现你说的问题，Excel方便看一下吗？

**Comment by liuboF2c** [comment]
> 目前测试环境没有发现你说的问题，Excel方便看一下吗？

[测试日期转换.xlsx](https://github.com/dataease/dataease/files/13868109/default.xlsx)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题将会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
