### ISSUE TITLE
[Bug]simple模式文本类型转时间类型后日期筛选异常

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#7544]
**DataEase 版本**
v1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 最新

**Bug 重现步骤(有截图更好)**
1. 原始数据日期格式为：2023-06-06T00:00:00+08:00
[测试日期转换.xlsx](https://github.com/dataease/dataease/files/13859098/default.xlsx)

2. Excel 上传后自动识别为文本，保存数据集后在数据管理中将类型修改为日期，格式选择 %Y-%m-%d

![image](https://github.com/dataease/dataease/assets/30886198/ef81b123-7032-4f7a-bf2f-c8f0f785322d)

3. 在仪表板中添加明细表和年月过滤组件，筛选2023-07的数据，发现明细表中展示了6月30的数据

![image](https://github.com/dataease/dataease/assets/30886198/f4ab9aa9-ae40-49ec-b4eb-c81df97c62fc)

期望只筛选出7月的数据
看现象是显示时将2023-06-06T00:00:00+08:00 转换为了2023-06-05 16:00:00，实际筛选时则按照转换前的日期筛选的。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前没发现你说的这个问题，方便看一下你查询是的sql吗？
![image](https://github.com/dataease/dataease/assets/84372766/6c4c1a06-8e75-47e6-86be-6fe8da9d1361)

**Comment by liuboF2c** [comment]
simple 模式才有这问题，local模式没有此问题。你是用simple模式测试的吗？

**Comment by BBchicken-9527** [comment]
哦，确实精简模式是会存在时区的问题，我们会在下个版本进行修复；

**Comment by BBchicken-9527** [comment]
1、格式化时要选择正确的格式；如果内置的不满足，可以自定义

2、如果自定义感觉难的话，可以使用计算字段
![image](https://github.com/dataease/dataease/assets/84372766/6ebadcea-e82d-4487-a294-995967a4bfb0)
