### ISSUE TITLE
[Feature]符号地图图标可是设置阈值变色

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#7545]
**请描述您的需求或者改进建议.**
<img width="330" alt="image" src="https://github.com/dataease/dataease/assets/101089844/626d80ae-d6a4-4416-835d-0e49fb610221">
<img width="589" alt="image" src="https://github.com/dataease/dataease/assets/101089844/2ca2f221-57a9-4fe3-b6ac-d1ab4ca6a3cd">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。
