### ISSUE TITLE
[Feature]优化过滤组件里的文本下拉和文本列表的输入匹配功能为客户端匹配，并忽略大小写

### ISSUE THREAD

**Issue by seanwwh** [dataease/dataease#7557]
版本：1.18.13
需求：
1. 目前过滤组件里的文本下拉和文本列表的输入匹配功能是后台重新查询，导致响应比较慢，并且大小写敏感是依赖数据库的逻辑，导致用户体验不太好，希望能优化成类似下拉树那样的客户端匹配，并忽略大小写。
2. 下拉树的搜索按钮增加回车事件响应搜索。
<img width="244" alt="image" src="https://github.com/dataease/dataease/assets/5187541/d94c4512-3026-405d-a9a1-ed5d31ce9139">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，现回复如下：
1、忽略大小写是由于有的数据库本身是不区分大小写的，如果要区分大小写，需要在后台中进行处理，我们先加入需求池中。
2、组件搜索暂时没有计划增加回车事件，待收集更多用户的需求后再考虑。

**Comment by seanwwh** [comment]
> 感谢您的反馈，现回复如下： 1、忽略大小写是由于有的数据库本身是不区分大小写的，如果要区分大小写，需要在后台中进行处理，我们先加入需求池中。 2、组件搜索暂时没有计划增加回车事件，待收集更多用户的需求后再考虑。

那为什么要文本下拉和文本列表要使用后台匹配，而下拉树使用前台匹配呢？统一使用前台匹配用户体验不是更好吗？

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，文本下拉和文本列表，是之前加了优化：选项值过多加载时卡顿，所以增加了懒加载。由于搜索是全局搜索，因此需要再请求一次后台数据。

**Comment by seanwwh** [comment]
> 再次感谢您的反馈，文本下拉和文本列表，是之前加了优化：选项值过多加载时卡顿，所以增加了懒加载。由于搜索是全局搜索，因此需要再请求一次后台数据。

下拉和列表一般是维度，数据过多导致加载慢的情况比较少吧，多到加载慢的下拉或列表使用起来体验也很差，这种场景使用文本搜索框更合适吧？另外，慢的原因会不会是数据库查询过程慢导致的？如果确实需要解决数据过多采用懒加载，那能不能加个选项给选择是否启用懒加载？这样一刀切用懒加载的结果是大部分场景体验变差
