### ISSUE TITLE
[Feature]透视表导出到Excel时按显示格式导出

### ISSUE THREAD

**Issue by seanwwh** [dataease/dataease#7559]
版本：1.18.13
需求：透视表导出Excel的格式与显示的格式不一致，希望能增加按显示格式导出的功能
<img width="1067" alt="image" src="https://github.com/dataease/dataease/assets/5187541/ca108432-7662-47cb-a267-d085fc788104">
<img width="409" alt="image" src="https://github.com/dataease/dataease/assets/5187541/4dc0691b-0cd3-4ed3-90d6-fb56b2d07b4e">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，需求已记录并加入需求池中，近期的需求较多，因此可能排期会靠后一些，还请多加关注我们的release notes 。
