### ISSUE TITLE
[Bug]v2 版本 富文本中插入的表格  单元格行宽调整有问题 

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#7560]
不管对哪一列的行宽进行调整，第一列的行宽每次都会增加

**Comment by wolf-kingx** [comment]
![Uploading 5dad97277325ad6f01164a9bde436a6b.png…]()

**Comment by wolf-kingx** [comment]
<img width="621" alt="5dad97277325ad6f01164a9bde436a6b" src="https://github.com/dataease/dataease/assets/141667200/b8b9dfbe-42ee-4333-afb8-813e33e7abf2">

**Comment by maninhill** [comment]
6个月内无更新，关闭。
