### ISSUE TITLE
日期组件的查询条件为时间戳，希望改为标准日期格式

### ISSUE THREAD

**Issue by marcomeng** [dataease/dataease#7562]
通过日期组件进行筛选时，查询条件为时间戳，不能有效利用时间字段的分区信息。希望改成标准日期字符串：YY-dd-mm HH:mm:ss
<img width="1161" alt="image" src="https://github.com/dataease/dataease/assets/8347862/14508f54-471d-4679-96e8-18288892ea10">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，时间戳是所有数据源通用的，如果改为字符串，有些数据源可能无法转换，因此暂时没有计划更换，issue我们就先关闭了，再次感谢您的关注和支持。
