### ISSUE TITLE
[Question]从模板市场下载导入的模板无法使用

### ISSUE THREAD

**Issue by kkrrsq** [dataease/dataease#7563]
版本：2.2.0
环境：部署在内网，无法访问模板市场
问题：从模板市场下载模板，在平台模板管理中导入成功（模板管理中可以看见导入的模板），但是在工作台中无法使用模板新建，模板中心查看不到导入的模板（显示请检查网络）。请问是一定要能访问模板市场才能看到导入的模板吗？怎么才能在内网中使用外部导入的模板？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，正常情况下，内网环境，是可以访问模版管理中的模版，请问您这边是安装包部署还是源码部署？

**Comment by kkrrsq** [comment]
安装包部署的

**Comment by kkrrsq** [comment]
@yayanpei-fit2cloud 有解决方法吗？

**Comment by yayanpei-fit2cloud** [comment]
我们这边的内网环境中没有复现出该问题，麻烦您加我下微信：18317092178，帮您排查一下。

**Comment by kkrrsq** [comment]
![image](https://github.com/dataease/dataease/assets/16069934/5dc5c81e-39d5-4dcf-9db9-9497be923177)

![image](https://github.com/dataease/dataease/assets/16069934/13085cd9-395f-4cd1-8f83-7c91096f02d1)

![image](https://github.com/dataease/dataease/assets/16069934/9d113783-352a-41ba-a4d0-35b9d33d6a4c)

内网环境，无法远程，只能提供错误日志

**Comment by xuwei-fit2cloud** [comment]
我们再次确认，确实无法复现您反应的情况。
在无法访问在线模板市场的情况下，错误日志确实会有输出，但并不影响正常使用来自模板管理的模板。
您可以尝试升级一下版本试试，或者联系我们的交流群的技术支持。

![图片](https://github.com/dataease/dataease/assets/1892127/daf0929f-f9fd-48a4-9747-445bffd6f942)
![图片](https://github.com/dataease/dataease/assets/1892127/928d3526-dd1c-45ea-97ce-130909dd04ca)
