### ISSUE TITLE
[Feature] api 数据集取数逻辑优化

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7564]
**请描述您的需求或者改进建议.**
json 数据，格式如图
![image](https://github.com/dataease/dataease/assets/45852479/4b64b983-7a80-4dd5-a0b5-7680f81153d3)
下面没有值的字段应该复制 “凯工厂”
![image](https://github.com/dataease/dataease/assets/45852479/8708ae8b-35a1-4670-8a2c-8cc60b657d95)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，所有api的逻辑获取数据的逻辑是统一的，且不对数据源的数据进行修改，因此这里暂时没有计划进行优化。

**Comment by ziliang-wan** [comment]
目前测试下来还有个问题，在存在为空的数据情况下，api 数据集的数据会错位，详情如下所示：
API 接口：https://east-ms.fit2cloud.com/api/mock/100001/test?test=2
![image](https://github.com/dataease/dataease/assets/30063018/8cac03e1-2228-4e3b-9660-9bb28eb09543)
API 数据集：
![image](https://github.com/dataease/dataease/assets/30063018/f3809b1b-5c95-4e7e-b4da-e83c020b4ab5)

**Comment by yayanpei-fit2cloud** [comment]
当数据结构较复杂时出现错乱，为已知bug，目前还没有合适的解决方案，如果有好的建议或者方案，也欢迎随时联系我们。
