### ISSUE TITLE
[Bug]v2版本 sql数据集sql查询通过，但是保存数据集不能保存，报错

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#7565]
<img width="836" alt="28c25e42ab627b946c7d65296a3564fc" src="https://github.com/dataease/dataease/assets/141667200/888074a2-54fb-428f-a33f-44d29d711c4d">
<img width="673" alt="22739eda1a4a2f601a98044456fcf92c" src="https://github.com/dataease/dataease/assets/141667200/327ae46b-19e3-4bc4-9e37-52895f7bbe78">

**Comment by Shenguobin0102** [comment]
感谢反馈，请问您保存SQL后，刷新数据了吗？如果没有请刷新数据后保存，因为数据集保存需要获取字段，所以需要在保存前刷新数据，来获取字段。

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
