### ISSUE TITLE
[Bug]v2 富文本中插入的表格 合并拆分过程中 会自动改变行高

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#7568]
情况不会一下子出现  多试几次 尤其是在合并拆分合并多次操作的时候出现 表格的行高和列宽是自动变化
<img width="819" alt="3d6741b379e3477c29c1817c0ddcbbb3" src="https://github.com/dataease/dataease/assets/141667200/85e507d6-6df6-432f-b9cb-7157d6aebdc0">
<img width="819" alt="e833b4f65ed3e596aa941f7a218087bc" src="https://github.com/dataease/dataease/assets/141667200/8be40562-6900-45de-ac91-622d2815a2a7">

**Comment by BBchicken-9527** [comment]
感谢反馈，富文本为原生组件，我们尝试修复一下

**Comment by maninhill** [comment]
6个月内无更新，关闭。
