### ISSUE TITLE
[Feature]年月、年份组件希望可以多选

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#7577]
**请描述您的需求或者改进建议.**
日期过滤组件：年月、年份 希望可以多选
![图片](https://github.com/dataease/dataease/assets/48307752/8f909d80-d6d7-4fc8-8da0-71480109efbf)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，暂时没有计划进行支持，2.x中在逐渐完善这一部分的功能，可以实现时间区间的选择，还请多加关注release notes。
