### ISSUE TITLE
[Feature]仪表板视图过多时，期望支持滚动加载的方式

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#7579]
**请描述您的需求或者改进建议.**
仪表板视图过多时，期望支持滚动加载的方式

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请问是和明细表一样，设置后自动的从上到下滚动吗？

**Comment by hw872715125** [comment]
是仪表板里面有很多个视图（30+），瀑布流这种，期望可以支持滚动加载。
目前是打开仪表板后，一次加载和显示所有视图，在视图过多时，会有明显的卡顿。
使用的版本：v1.18.13

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池中，近期暂时没有计划支持，待收集更多相关的需求后再做进一步的规划。

**Comment by maninhill** [comment]
暂无支持计划。
