### ISSUE TITLE
对使用apisix的疑惑，能否出个不依赖apisix的版本

### ISSUE THREAD

**Issue by mayou33** [dataease/dataease#7581]
下载dataease-online-installer-v2.2.0.tar.gz，
看了application.yml ，发现有个配置
dataease:
  apisix-api:
    domain: http://apisix:9180
    key: DE_APISIX_KEY

再结合install.sh文件 和apisix 的init.sh文件

if [[ $DE_INSTALL_MODE != "community" ]];then
   access_port=9080
fi
###
虽然我们也在用apisix。但是个人觉得，这个软件没有必要使用apisix，增加了复杂度和实施落地的成本。
许多公司的人还不会使用apisix。
##
能不能出 可以使用nginx 版本的，不依赖apisix的。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，apisix为dataease企业版本提供网关、权限、认证等服务，因此拿不掉apisix。
如果觉得重复，后面有规划出桌面版，是不包含apisix模块的。

**Comment by mayou33** [comment]
谢谢，回复。
