### ISSUE TITLE
[Bug]升级后，原先正常使用的SqlServer数据源不可用了

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#7584]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
升级到最新的1.18.14版本后，原先正常使用的SqlServer数据源不可用了
![image](https://github.com/dataease/dataease/assets/89771514/6140a0ae-2ea0-40ec-bafe-180364555ae0)

临时解决：上传了驱动包sqljdbc4-4.0.jar，这个驱动包是从dataease的容器里拿出来的驱动包，在定义驱动的时候指定了 10 版本
![image](https://github.com/dataease/dataease/assets/89771514/5c04e385-d29f-49af-91c8-b4a49d48f517)

期望：升级之前支持的数据源版本，升级后依旧可用

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
