### ISSUE TITLE
[Bug]microsoft.sqlserver.jdbc.SQLServerException: 'offset' 附近有语法错误

### ISSUE THREAD

**Issue by ynzzxc** [dataease/dataease#759]
**DataEase 版本**

1.21
**浏览器版本**

Firefox 91.0.2 (64 位)
**Bug 描述**
数据更新方式：直连
数据预览报错：microsoft.sqlserver.jdbc.SQLServerException: 'offset' 附近有语法错误（sql编辑页面预览正常）
影响：无法预览数据，创建视图时无法引用相应数据集
数据库版本：Microsoft SQL Server 2008 R2 (RTM) - 10.50.1600.1 (X64) 
	Apr  2 2010 15:48:46 
	Copyright (c) Microsoft Corporation
	Enterprise Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: ) (Hypervisor)

**Bug 重现步骤(有截图更好)**
1.添加sql数据集
2.预览并确认
3.点击确认后进入数据预览界面，报错：microsoft.sqlserver.jdbc.SQLServerException: 'offset' 附近有语法错误

补充：定时更新数据预览报错：io.dataease.exception.DataEaseException: errCode = 2, detailMessage = there is no scanNode Backend. [10002: not alive]

**Comment by chhwang1981** [comment]
我也是遇到一样的问题，SQL SERVER 版本也是2008 R2

**Comment by ynzzxc** [comment]
> 
> 
> 我也是遇到一样的问题，SQL SERVER 版本也是2008 R2

我在群里也反馈了，说修复之后会发公告
