### ISSUE TITLE
[Bug]数据集中有数据，明细表显示异常

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#7592]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
数据集中可以看到数据
![wecom-temp-82587-74ed169de908635dc03bdbd6054b277c](https://github.com/dataease/dataease/assets/85436572/27a483d3-d1e0-43aa-bad6-df8a30e43f00)
明细表报错
![wecom-temp-45385-9ef935c078ce6c70a197c1d998fcb949](https://github.com/dataease/dataease/assets/85436572/363a7469-2eed-42b1-b67a-0046117cc0c9)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by Shenguobin0102** [comment]
感谢反馈。需要您提供以下信息来帮助定位问题：
1.明细表使用是哪种类型的数据源；
2.明细表使用的数据集是什么类型；
3.数据集数据量是什么量级的。

**Comment by BBchicken-9527** [comment]
感谢反馈，应该是使用的sqlserver版本过于老旧分页语法不兼容导致的，为已知问题，目前正在修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
