### ISSUE TITLE
[Feature]跳转按钮默认显示

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#7596]
**请描述您的需求或者改进建议.**
当前跳转按钮是隐藏的点击才会显示，希望能默认显示出来。否则观看者不知道视图可以跳转

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，已经在2.x的版本中进行实现，还请试用2.x版本。
<img width="510" alt="image" src="https://github.com/dataease/dataease/assets/84168063/894d932d-e265-4f4d-93ab-d720dca061a7">
