### ISSUE TITLE
[Bug]分享公共链接，电脑全屏显示时间久会变成白屏

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#7597]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
浏览器、Google、360都试过

**Bug 描述**
有两个开源用户反馈都出现了这个情况，分享公共链接后隔一段时间会白屏。一天会出现4,5次。电源选项里设置过显示器永久不进入睡眠，一个设置了局域网，一个设置了反向代理。
![wecom-temp-347918-4d1b5cce451006041d9790b3b77faebb](https://github.com/dataease/dataease/assets/85436572/1cd6fff8-f0ee-4773-9351-2aec7561eff7)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的这个问题，方便看一下前台是否存在一些异常的日志嘛？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
