### ISSUE TITLE
[Feature]v2版本 玫瑰环形图 标签向外能不能改成和v1版本的一样

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#7598]
现在向内向外区别不大 尤其是向现实的内容稍微多的时候 非常难看 希望还是想v1一样 有线支出来

<img width="303" alt="4320cec315e7b71415920d7089093d8a" src="https://github.com/dataease/dataease/assets/141667200/253f94dd-1337-4526-9ecf-27bb88a65e00">

<img width="314" alt="ecb1d891dd8e3e6483564702d9aefda7" src="https://github.com/dataease/dataease/assets/141667200/3e4ea98e-394f-4d84-b6b6-c0525218e5e3">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，v1有引导线应该用的是echarts图库，antv图库如果要支持引导线的，应该要升级图库，可能存在一些不兼容的情况，我们先调研一下。

**Comment by xuwei-fit2cloud** [comment]
暂时不好支持。
