### ISSUE TITLE
[Bug]Navicat可运行的SQL在SQL数据集中报错，刷新页面后可正常使用

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#7599]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
SQL如下：
`(
  SELECT
    a.project_id AS 'projectId',
    a.busi_code as '编号',
    a.project_state AS 'projectState',
    a.audit_type AS 'auditType',
    m.complete_state AS 'completeState',
    a.auditState AS 'project.auditState',
    a.paid_amount AS 'paidAmount',
    a.pay_state AS 'payState',
    a.apply_time AS 'applyTime',
    a.confirm_date AS 'confirmDate',
    a.loan_price AS 'loanPrice',
    a.audit_date AS 'auditDate',
    month(a.apply_time) as 'applyTimeMonth',
    year(a.apply_time) as 'applyTimeYear'
    FROM
    biz_risk_standingbook_report a
    LEFT JOIN biz_project bp ON bp.id = a.project_id
    LEFT JOIN biz_pay_mangement m ON m.project_id = bp.id
    WHERE
    a.audit_type != '未审核' /*是否有担保人 */
    AND DATE_FORMAT( a.apply_time, '%Y-%m-%d' ) >= DATE_FORMAT( '${applyTime1}', '%Y-%m-%d' )
		AND DATE_FORMAT( a.apply_time, '%Y-%m-%d' ) <= DATE_FORMAT( '${applyTime2}', '%Y-%m-%d' )
    AND DATE_FORMAT( a.audit_date, '%Y-%m-%d' ) >= DATE_FORMAT( '${applyTime1}', '%Y-%m-%d' )
		AND DATE_FORMAT( a.audit_date, '%Y-%m-%d' ) <= DATE_FORMAT( '${applyTime2}', '%Y-%m-%d' )
    AND NOT EXISTS ((
        SELECT 1 
        FROM biz_project_end_record 
        WHERE project_id = a.project_id 
				AND termination_type = '3'/*重新立项*/
    ))
  )
  UNION
  (
  SELECT
    a.project_id AS 'projectId',
    a.busi_code as '编号',
    a.project_state AS 'projectState',
    a.audit_type AS 'auditType',
    m.complete_state AS 'completeState',
    a.auditState AS 'project.auditState',
    a.paid_amount AS 'paidAmount',
    a.pay_state AS 'payState',
    a.apply_time AS 'applyTime',
    a.confirm_date AS 'confirmDate',
    a.loan_price AS 'loanPrice',
    a.audit_date AS 'auditDate',
    month(a.apply_time) as 'applyTimeMonth',
    year(a.apply_time) as 'applyTimeYear'
    FROM
    biz_risk_standingbook_report a
    LEFT JOIN biz_project bp ON bp.id = a.project_id
    LEFT JOIN biz_pay_mangement m ON m.project_id = bp.id
    WHERE
    a.audit_type != '未审核' /*是否有担保人 */
    AND DATE_FORMAT( a.apply_time, '%Y-%m-%d' ) >= DATE_FORMAT( '${applyTime3}', '%Y-%m-%d' )
		AND DATE_FORMAT( a.apply_time, '%Y-%m-%d' ) <= DATE_FORMAT( '${applyTime4}', '%Y-%m-%d' )
    AND DATE_FORMAT( a.audit_date, '%Y-%m-%d' ) >= DATE_FORMAT( '${applyTime1}', '%Y-%m-%d' )
		AND DATE_FORMAT( a.audit_date, '%Y-%m-%d' ) <= DATE_FORMAT( '${applyTime2}', '%Y-%m-%d' )
    AND a.confirm_date IS Null
		AND a.audit_type != '审核取消'
 		AND  NOT EXISTS ((
        SELECT 1 
        FROM biz_project_end_record
        WHERE project_id = a.project_id 
				AND termination_type = '3'/
      ))
  )
 UNION
	(
    SELECT
    a.project_id AS 'projectId',
    a.busi_code as '编号',
    a.project_state AS 'projectState',
    a.audit_type AS 'auditType',
    m.complete_state AS 'completeState',
    a.auditState AS 'project.auditState',
    a.paid_amount AS 'paidAmount',
    a.pay_state AS 'payState',
    a.apply_time AS 'applyTime',
    a.confirm_date AS 'confirmDate',
    a.loan_price AS 'loanPrice',
    a.audit_date AS 'auditDate',
    month(a.apply_time) as 'applyTimeMonth',
    year(a.apply_time) as 'applyTimeYear'
    FROM
    biz_risk_standingbook_report a
    LEFT JOIN biz_project bp ON bp.id = a.project_id
    LEFT JOIN biz_pay_mangement m ON m.project_id = bp.id
     WHERE
    a.audit_type != '未审核' /*是否有担保人 */
    AND DATE_FORMAT( a.apply_time, '%Y-%m-%d' ) >= DATE_FORMAT( '${applyTime3}', '%Y-%m-%d' )
		AND DATE_FORMAT( a.apply_time, '%Y-%m-%d' ) <= DATE_FORMAT( '${applyTime4}', '%Y-%m-%d' )
    AND DATE_FORMAT( a.confirm_date, '%Y-%m-%d' ) >= DATE_FORMAT( '${applyTime1}', '%Y-%m-%d' )
		AND DATE_FORMAT( a.confirm_date, '%Y-%m-%d' ) <= DATE_FORMAT( '${applyTime2}', '%Y-%m-%d' )
    )`
报错信息：

![企业微信截图_17048751129242](https://github.com/dataease/dataease/assets/85436572/a2d7f7eb-dee7-4fe1-a4c8-4ee8866e0b4e)
数据集中有一个UNION时可以正常运行，两个UNION即报错，刷新链接后可正常运行
**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，由于你是源码运行，不确定你是否改动和以及打包方式都有可能存在问题，建议你加入我们的交流群，上面有非常专业的同学会实时的回复你的问题，方便你快速并精准的定位到你的问题所在；
