### ISSUE TITLE
新建视图后无法改名[Feature]

### ISSUE THREAD

**Issue by yacheng-xie** [dataease/dataease#76]
添加新视图后，无法更改视图名称。
![image](https://user-images.githubusercontent.com/66484040/123575080-974f7300-d803-11eb-84e9-1d3e2a0d7e24.png)

**Comment by yayanpei** [comment]
感谢您的反馈，视图的名称与标题一致，可通过选择【组件样式】，修改视图的标题来实现

**Comment by xuwei-fit2cloud** [comment]
在 v1.1.0 版本中，视图的操作菜单里会加上支持。

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #74

**Comment by xuwei-fit2cloud** [comment]
v1.1.0-rc1 版本已支持
