### ISSUE TITLE
[Bug]ECharts 组合图设置了下钻后，维度排序正常，指标排序失效

### ISSUE THREAD

**Issue by Renata1027** [dataease/dataease#7600]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
对维度和指标都进行排序，在下钻前排序正常，下钻后维度排序正常，指标排序混乱

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，设置多个字段排序只生效一个的，一般是先维度再指标，多维度指标按照主次，如有子维度那么祝维度优先，然后再子维度最后指标；
