### ISSUE TITLE
[Bug]手机端仪表板下载页面错乱

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#7603]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
苹果手机自带浏览器safari

**Bug 描述**
仪表析进行手机端适配后，在手机端打开，点击下载按钮后，展示的页面错乱，兼容问题

**Bug 重现步骤(有截图更好)**
1.仪表板配置手机端
2.在手机端打开查看
3.点击下载仪表板，页面展示错乱

手机端页面部局正常情况下：
![31e215f574435ee013693f94350e79b](https://github.com/dataease/dataease/assets/77324661/4c62e07f-1834-4c01-b706-8696062bb226)
点击屏幕右上角位置会出现下载按钮：
![dbfddc8b771de0a05ed55c207670caf](https://github.com/dataease/dataease/assets/77324661/f66a1898-8b05-489d-a396-82c3978f98ed)
点击下载按钮后页面展示错乱：
![39358f88c193f5497832b9f50ca38c1](https://github.com/dataease/dataease/assets/77324661/d57d6484-308c-4b53-b068-d841c5f2df08)

**Comment by BBchicken-9527** [comment]
感谢反馈，后续版本将去除此处的下载功能；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
