### ISSUE TITLE
[Bug]日期筛选组件bug

### ISSUE THREAD

**Issue by Pikawang** [dataease/dataease#7605]
**DataEase 版本** 
v1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
edge 120.0.2210.121

**Bug 描述**
选项卡内嵌报表，点击报表内的日期筛选组件，不选择日期，点击组件外空白处则无法关闭弹出的日期列表。

**Bug 重现步骤(有截图更好)**
1.
![Uploading image.png…]()

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是tab组件中的日期过滤组件在展开弹窗后点击空白区域无法收回是吗？

**Comment by Pikawang** [comment]
是的，刚进入的时候会有这个问题，选中一个日期之后，在x掉，就没有了

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有出现你说的情况，方便能详细说一下你复现的步骤吗？我这边尝试复现一下，你是全屏？或者移动端？

**Comment by Pikawang** [comment]
https://github.com/dataease/dataease/assets/42234435/0065634f-b8f3-4c0f-9fdb-c992efff29b5

**Comment by Pikawang** [comment]
浏览器正常标签页打开，pc端，没有全屏，视频是把浏览器上方的隐私信息截掉了

**Comment by Pikawang** [comment]
空白仪表板放置一个选项卡，选项卡内嵌网页，网页的地址是做好的报表的公共连接

**Comment by Pikawang** [comment]
现在使用的版本是v1.18.14

**Comment by BBchicken-9527** [comment]
感谢反馈，我试一下；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
