### ISSUE TITLE
[Question]sql数据源或者看板能否根据登录人员得不同而不同

### ISSUE THREAD

**Issue by pangafu** [dataease/dataease#761]
1. 第一种情况：
    数据源A只给用户A开放，数据源B只给B开放
    看板A只给用户A开放，看板B只给用户B开放

2. 第二种情况：
    数据源定义为 select * from table where userid=%登录的用户ID%
    A和B进来，看到的同一个数据源内容不一样

   或者在看板里面，接受用户ID等外部传入的参数（不光在数据源内定义）

**Comment by xuwei-fit2cloud** [comment]
目前没有支持，我们讨论一下

**Comment by xuwei-fit2cloud** [comment]
该功能会在近期版本v1.6.0 或v1.7.0版本中支持，请关注新版本发布。
