### ISSUE TITLE
[Question] 请问dev-v2分支，是否有全量sql文件

### ISSUE THREAD

**Issue by Zhaobudaoyuema** [dataease/dataease#7610]
拉代码下来运行，会报表找不到
![image](https://github.com/dataease/dataease/assets/66905526/289f61db-6c8e-4920-a1d8-6226f7132fd8)

**Comment by ziyujiahao** [comment]
感谢反馈 建议先用v2.2 Release版本开发 dev-v2是开发版本 应该是部分功能没有完成测试存在些问题 我们之后会尽量避免
