### ISSUE TITLE
[Bug]impala 3.1.0版本，在手动上传数据库驱动并连接成功后，BIGINT的日期类型无法转换为标准日期格式(impala 4.0可转换成功)

### ISSUE THREAD

**Issue by sageonedream** [dataease/dataease#7611]
**DataEase 版本**
V1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
离线安装

**浏览器版本**
chrome 104.0.5112.81

**Bug 描述**
impala 3.1.0版本，在手动上传数据库驱动并连接成功后，BIGINT的日期类型无法转换为标准日期格式(impala 4.0可转换成功)

**Bug 重现步骤(有截图更好)**
1.新建一个表格，里面增加BIGINT的日期字段；
2.在数据库数据集中查询该表格数据，并新建计算字段，通过函数将BIGINT的日期字段，转换为标准的日期格式
![f25f70472c6efa8e0f3713feff91f13](https://github.com/dataease/dataease/assets/92150453/3f50ad4c-7c30-4e9f-8f77-6ece79f5ac1f)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问题这个sql片段在你的3.1的服务中可以跑通吗？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
