### ISSUE TITLE
关于表格的功能拓展

### ISSUE THREAD

**Issue by zhoulel** [dataease/dataease#7615]
**请描述您的需求或者改进建议.**

1. 建议增加横向滚动 数据 目前只有上下滚动
2. 建议表格可以争对单个数据 可以自定义列展示效果，比如 百分比数据可以 使用进度条 ，图片可以根据地址直接显示图片

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，第一个需求已经在我们的需求池中，但短期内还没有支持计划；
第二个需求，目前使用的表格组件还无法支持图片的展示。

**Comment by maninhill** [comment]
暂无支持计划。
