### ISSUE TITLE
[Bug]【数据集】MySQL 8 数据源创建 SQL 数据集时不支持 !=

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#7617]
**DataEase 版本**
v2.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
MySQL 8 数据源创建 SQL 数据集时不支持 !=。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/24768910/2065ebb5-2511-4300-800d-f2dc9bfb0605)

**Comment by xusongtao** [comment]
这位朋友，自定义SQL走Calcite的语法，可以把 != 换成 <> 试试
![image](https://github.com/dataease/dataease/assets/40846859/8324e2da-ebd6-4287-9d39-8d1c09a5e63e)
