### ISSUE TITLE
[Bug] v2 数据集计算字段使用日期函数(如 WEEK、YEAR、DAY等)抛异常

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#7619]
**DataEase 版本**
v2.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
最新版Chrome

**Bug 描述**
1.字段为时间类型
2.添加计算字段，提取时间中的周数
3.前台抛异常 Request failed with status code 500

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/40846859/2494ec1c-7793-45f4-868c-0f2f6bc5d472)

2.
![image](https://github.com/dataease/dataease/assets/40846859/e407cb75-7237-40a6-b5b6-4b06eb0897fa)

3.
![image](https://github.com/dataease/dataease/assets/40846859/64415d2d-e6aa-4e75-b12e-0104653e6f33)
4.
![image](https://github.com/dataease/dataease/assets/40846859/7e7c7d47-535c-4f28-9bc1-957d7b595d31)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问目标字段类型是什么？使用的又是什么类型的数据源？

**Comment by xusongtao** [comment]
字段类型是时间类型，格式如   2024-01-15，  希望使用 WEEK() 函数拿到对应日期的周数。
可以参考 
![image](https://github.com/dataease/dataease/assets/40846859/3a2eec69-dd42-4749-b117-7c6fa4c7ce82)

**Comment by BBchicken-9527** [comment]
我知道这个函数的😂，我昨天在测试环境上看了是没问题的，所以我问一下具体的数据源类型和字段类型，确定一下是否是因为数据源或者字段类型导致的异常；
![image](https://github.com/dataease/dataease/assets/84372766/0cf547b4-db36-42b2-a444-c74935c59616)
![image](https://github.com/dataease/dataease/assets/84372766/239f380f-4066-4345-8141-36567b405444)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
