### ISSUE TITLE
[Feature]希望视图支持“数据桶”功能

### ISSUE THREAD

**Issue by xusongtao** [dataease/dataease#7620]
**请描述您的需求或者改进建议.**
业务场景
公司有上百种商品，如果全部展示出来会比较多，希望能把前几名的商品（或任意组合）归到一个“数据桶”中做展示。
类似如下视图表示
![image](https://github.com/dataease/dataease/assets/40846859/901b5c4e-1197-4895-bf12-9a07f908329f)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的关注，该功能已规划在版本规划中，还请多家关注release notes。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
