### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by YunQianAtl** [dataease/dataease#7621]
**DataEase 版本**
社区版2.1和2.2

**运行方式(安装包运行 or 源码运行 ?)**
脚本install.sh安装，在docker容器运行

**浏览器版本**
chrome v120

**Bug 描述**
V2.2版本在虚拟机上部署断电重启后数据集关联异常
版本：v2.1.0社区版和v2.2.0社区版同样有问题
dataease(2.1.0和2.2.0）正常安装后配置数据源和数据集，然后简单创建一张明细报表后，虚拟机断电重启。重启后dataease正常启动，登录正常，点击数据集的时候提示错误SQL执行失败，请检查表、字段、关联关系等信息是否正确并重新编辑。
删除数据集和数据源重新创建新的使用正常，但是重复断电重启又会出现同样的错误。
虚拟机：VMware® Workstation 17 Pro 版本号：17.0.0 build-20800274
安装的系统版本：CentOS Linux release 8.5.2111
执行dataease脚本安装后有两个docker容器见下图：
![企业微信截图_20240113153442](https://github.com/dataease/dataease/assets/7821575/d59ced81-968a-4ed5-8f3e-31e112d3afb2)
![企业微信截图_17051243853319](https://github.com/dataease/dataease/assets/7821575/38315b53-b637-42c2-9e5c-c1c12d99a280)

**Bug 重现步骤(有截图更好)**
1.正常创建数据源和数据集
2.创建一个报表选用明细报表，数据用刚才建好的数据集并保存
3.虚拟机断电后重启
4.虚拟机打开电源dataease自动运行，登录正常
5.点击数据集提示上面截图的错误信息

**Comment by BBchicken-9527** [comment]
感谢反馈，我们确认一下问题；

**Comment by BBchicken-9527** [comment]
感谢反馈，我用mysql5.x的数据源尝试，重启de服务的服务器没发现你说的问题，所以想和你确认具体的情况；

**Comment by YunQianAtl** [comment]
我是使用install.sh脚本安装的，安装后容器的mysql版本是8.1然后服务器重启使用的是虚拟机的直接断电，不是正常关闭服务器。







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dataease/dataease"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月15日(星期一) 晚上11:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dataease/dataease] [Bug] (Issue #7621)





 
感谢反馈，我用mysql5.x的数据源尝试，重启de服务的服务器没发现你说的问题，所以想和你确认具体的情况；

**Comment by BBchicken-9527** [comment]
我这边是云服务强制关机后重启验证的，但是没有发现你说的问题，我明天申请一台虚拟机看看吧。对了如果你在此重启这个问题还会出现吗？

**Comment by YunQianAtl** [comment]
每次重启之后，没有关闭网页，直接访问数据集就会出现这个问题，我有复现整个过程的录屏录像，请问要怎么样提供给你？

**Comment by BBchicken-9527** [comment]
我这边用虚拟尝试了一下还是没有出现你说的问题，我使用的是2.2的版本，你用的是什么数据源？excel？

**Comment by YunQianAtl** [comment]
> 我这边用虚拟尝试了一下还是没有出现你说的问题，我使用的是2.2的版本，你用的是什么数据源？excel？

使用的数据源是mysql 版本是5.7.18，复现BUG的操作视频已经发给贵公司的贺晨芳。

**Comment by YunQianAtl** [comment]
复现BUG步骤:
1、设置数据源，我使用的是mysql 5.7.18
2、设置数据集，设置了订单主表和明细表，使用左连接用订单号做条件
3、仪表板新增一个数据明细报表，使用刚刚创建的数据集。
4、虚拟机关闭电源重启，然后点击dataease数据集界面上面步骤2设置的数据集就会提示关联错误的提示。

**Comment by BBchicken-9527** [comment]
😂我印象中我当时使用的也是5.7的版本，我明天再试试；

**Comment by xuwei-fit2cloud** [comment]
由于长时间未有反馈，暂时关闭该issue，如有问题，咱们在继续沟通。
