### ISSUE TITLE
[Question] 请问源码中多处引用dataease-license-sdk且未提供此模块源码，是否违反gpl协议

### ISSUE THREAD

**Issue by yulongz** [dataease/dataease#7622]
源码中多处引用dataease-license-sdk导致编译无法正常运行。既未将此模块的源码交互剥离来使得编译正常运行，又未提供此模块源码，是否违反gpl协议

**Comment by ziyujiahao** [comment]
多谢提问 我们当前dev-v2分支使用的事对应SDK版本号使用的2.3 dataease-license-sdk-2.3还没上传到公库中 我们会优化一下dev-v2分支的sdk版本管理 增加snapshot分支，请先使用我们的release分支 如v2.2 进行开发

**Comment by kevinlxj** [comment]
dataease-license-sdk源码可以提供吗？
