### ISSUE TITLE
[Feature] 数据源字段类型可以支持json

### ISSUE THREAD

**Issue by MoLeft** [dataease/dataease#7623]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/41848811/eee92f57-28fb-4ecc-8d1a-4c7bedc82852)

由于我们单位使用的蜜罐部分字段是json, 所以希望可以在字段类型处支持解析json
![image](https://github.com/dataease/dataease/assets/41848811/57f19d15-bcae-435f-a72f-cbf62182ca9a)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
支持了json类型的话，似乎在DataEase中也没有实际的使用场景。

**Comment by MoLeft** [comment]
> 支持了json类型的话，似乎在DataEase中也没有实际的使用场景。

确实使用场景很小众，而且我发现DataEase可以用sql语句当成数据源，然后我把单位服务器的mysql升级到8.x之后就可以通过写sql来解决问题了

**Comment by xuwei-fit2cloud** [comment]
感谢您的回复，那这个需求我们暂时不考虑了。
