### ISSUE TITLE
[Feature]饼图显示自定义里面的提示信息有些可以不展示

### ISSUE THREAD

**Issue by huangxine** [dataease/dataease#7624]
**请描述您的需求或者改进建议.**
饼图显示自定义里面的提示信息有些可以不展示
![1705286451969](https://github.com/dataease/dataease/assets/78218624/b4b1bffd-0365-4805-bc29-7b59ff94b692)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，标签是整体控制展示或者不展示的，暂没有计划根据图例去控制展示或者不展示部分标签。如下图所示，建议可以点击图例控制该分类展示或者不展示：
<img width="448" alt="image" src="https://github.com/dataease/dataease/assets/84168063/b713a76b-7255-443a-af04-a743ee409cb0">
