### ISSUE TITLE
[Bug]仪表板视图维度自定义排序，目前仅支持对当前页的重排序，无法做到全排序

### ISSUE THREAD

**Issue by zhimayuyuan** [dataease/dataease#7628]
**DataEase 版本**
v2.2.0

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**
Chrome 版本 120.0.6099.217（正式版本） （64 位）

**Bug 描述**
[Bug]仪表板视图维度自定义排序，目前仅支持对当前页的重排序，无法做到全排序

**Bug 重现步骤(有截图更好)**
![048a5a0688331ef81f05921f5a74579e](https://github.com/dataease/dataease/assets/128681370/756b716d-b050-414a-ae2c-9afc8c513084)
![9133789ddb644279c7df1ebf7db20405](https://github.com/dataease/dataease/assets/128681370/b53718df-1000-4dca-baeb-40bda21d05ca)
![f901da1da2cb7caf2e75620399b0a5d3](https://github.com/dataease/dataease/assets/128681370/25c0f0ea-a138-4755-8316-56b742784831)

**Comment by BBchicken-9527** [comment]
感谢反馈，这个应该是1.x的内容吧，请问你是用的数据源是？我用测试环境excel数据集没有发现你的这个情况，方便可以提供我更细致一些的情况吗？

**Comment by zhimayuyuan** [comment]
> 感谢反馈，这个应该是1.x的内容吧，请问您用的数据源是？我用测试环境excel数据集没有发现您的这种情况，方便可以提供我更引导一些的情况吗？

使用的是这个数据集
![image](https://github.com/dataease/dataease/assets/128681370/ec8bd793-0476-4666-a454-9a5bf330e961)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by fit2cloudrd** [comment]
只能对已有数据排序，未在当前页展示的数据无法排序
