### ISSUE TITLE
[Bug]日期范围组件设置背景后不能点击

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#7630]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 120

**Bug 描述**
日期范围组件点击设置组件样式->勾选背景->设置边框后，不能点击

**Bug 重现步骤(有截图更好)**
1、未设置组件样式前，日期选择正常
![image](https://github.com/dataease/dataease/assets/27687681/2c351a06-d5d7-40fe-a7f1-23f586eac467)

2、设置组件样式->勾选背景->设置边框后，日期不能点击。无论是悬浮还是矩阵，是否设置置顶置底，都不能正常点击
![image](https://github.com/dataease/dataease/assets/27687681/7cd43a80-1b7c-45c8-a75c-137833f03998)

![image](https://github.com/dataease/dataease/assets/27687681/51fea433-f88e-440c-9e18-3d024bd5309e)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，请问你是用的版本是14版吗？如果使用的是14版方便问一下前端是否存在异常可以看一下吗？

**Comment by xiaorsly88** [comment]
截图都是在体验环境完成，测试地址：https://dataease.fit2cloud.com/#/panel/index

**Comment by maninhill** [comment]
<img width="968" alt="image" src="https://github.com/dataease/dataease/assets/41712985/28db393e-3bdf-417e-b2ed-118930c91b48">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前体验环境没有及时更新给你的体验带来不便实在不好意思，目前正在更新最新的版本，这个问题已被修复，问题我现在这里关闭掉，如果依然存在相关问题你可以重新打开；
