### ISSUE TITLE
[Bug] ES数据源的SQL数据集使用group by后视图报错

### ISSUE THREAD

**Issue by limin-fit2** [dataease/dataease#7632]
**DataEase 版本**
v1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
最新版本

**Bug 描述**
对接ES数据源后，编写SQL数据集，使用group by分组查询，数据集展示正常，在仪表板中关联数据集，除明细表之外所有图表类型均报错。

**Bug 重现步骤(有截图更好)**
1.SQL数据集使用group by，数据集预览正常
![image](https://github.com/dataease/dataease/assets/61964761/5bb9cf5f-f236-484c-a9f1-f720b7606203)
2.仪表板中的使用带有group by的数据集，视图无法正常预览
![image](https://github.com/dataease/dataease/assets/61964761/54011912-6d51-45c0-9b88-5f38c8d76558)
3.切换图表类型为明细表，视图正常预览数据
![image](https://github.com/dataease/dataease/assets/61964761/d17b5758-d5ef-43e7-ad08-cc3ad48b2ddc)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
