### ISSUE TITLE
[Bug]echarts明细表底部分页显示样式问题

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#7633]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome120

**Bug 描述**
问题1：echarts明细表在设计器中水平条不能拖拉，而1.18.13版本在弹出右侧编辑器的情况下水平条可以拖拉
问题2：echarts明细表修改记录显示条数为10条，保存后回到仪表盘，分页条显示和记录行重叠，且全屏显示时和记录行显示很大的空白空间。 但如果记录显示条数较多，有垂直下拉条的时候没有这个问题。
echarts问题相较antV问题较多，建议升版本后能回归测试。

**Bug 重现步骤(有截图更好)**
1、水平拖拉条不能拖动
![image](https://github.com/dataease/dataease/assets/27687681/9be27259-c21f-403f-8f31-a5cb5988e0b1)

2、记录数的高度正好和表格高度一样时（选择显示每页显示10行记录），此时没有垂直上下拉动条，保存后显示分页样式错乱了
![image](https://github.com/dataease/dataease/assets/27687681/5c5c53f3-c8f5-4d2e-8f04-bfba1787a661)

3、全屏显示时，和记录行有很大的空白
![image](https://github.com/dataease/dataease/assets/27687681/95934ef3-ec9f-4ab8-b5aa-dc7528a7efbe)

4、将echarts明细表的记录数设置显示为20条或更多，这时会出现垂直下拉条，显示又都正常了
![image](https://github.com/dataease/dataease/assets/27687681/86e303e2-5550-401c-8704-02a943697640)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题1，并不是不能拖拽因为弹出右侧弹窗后改变了仪表板的大小，导致计算后的选中范围可能会因为像素问题出现偏差，我们这边商量一下看看是否能解决；问题2，目前测试环境没有发现你说的问题，如果可以的话可以说一下详细的复现步骤嘛我这边进行进一步的复现，感激不尽；

**Comment by xiaorsly88** [comment]
已录视频并反馈到DataEase 交流群 38，由管理转发

**Comment by BBchicken-9527** [comment]
感谢反馈，问题2目前测试环境依然没有复现，我们讨论了一下和屏幕比例和分辨率也是有一定关系的并在此处做了一定的调优现在你那边还有这个问题吗？

**Comment by xuwei-fit2cloud** [comment]
由于长时间未有反馈，暂时关闭该issue，如有问题，咱们在继续沟通。
