### ISSUE TITLE
[Bug]跳转设置BUG，设置某个字段跳转，实际点击其它地方都可以跳转

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#7635]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome120

**Bug 描述**
目前仅验证了echarts的明细表，设置了某个字段的跳转，实际点击其它地方都可以跳转

**Bug 重现步骤(有截图更好)**
1. 如图，仅设置一个字段跳转到外链
![image](https://github.com/dataease/dataease/assets/27687681/1210bc58-5c26-40db-8a9d-c039dbb72997)

2. 保存后，点击图示单元格，也发生了跳转。 实际应该点击第三个单元格才能跳转
![image](https://github.com/dataease/dataease/assets/27687681/26f05199-b85a-4d43-b8d1-f66e86107422)

![image](https://github.com/dataease/dataease/assets/27687681/be5dd5ab-673c-4cc9-ab79-db677da21361)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，我们将会在这个版本进行修复，请耐心等候；

**Comment by xiaorsly88** [comment]
收到，感谢反馈

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
