### ISSUE TITLE
[Bug]驱动管理中支持版本反显问题

### ISSUE THREAD

**Issue by xiaorsly88** [dataease/dataease#7640]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
源码运行 

**浏览器版本**
chrome120

**Bug 描述**
新建一个驱动后，切换到另一个驱动，在切回新建的驱动，字段“支持的版本”反显为空。需要重新创建一个驱动，或刷新页面，或跳转其它页面在回来后，点击新创建的驱动，字段“支持的版本”才能正常反显

**Bug 重现步骤(有截图更好)**
1. 新建驱动，填写驱动类和版本，保存
![image](https://github.com/dataease/dataease/assets/27687681/5def05e0-932e-41db-bbc4-ad80bc63d000)

2. 切换到其驱动
![image](https://github.com/dataease/dataease/assets/27687681/b18b0504-ec90-4585-9c89-7ed2cf931e88)

3. 在切换回第1步中新建的驱动，“支持的版本”反显为空
![image](https://github.com/dataease/dataease/assets/27687681/5a309dee-1550-4fa3-a8a4-7fc50c395f15)

4. 退出驱动管理页面，在回来重新点击第1步中新建的驱动，“支持的版本”反显正常
![image](https://github.com/dataease/dataease/assets/27687681/70c0ec8f-4d73-4a22-aaad-83824f776dec)

![image](https://github.com/dataease/dataease/assets/27687681/76618359-d24e-4526-9f0f-1f3bf0114fed)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本修复此问题；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
