### ISSUE TITLE
分析场景-自由构建图形功能[Feature]

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#7644]
在某些分析场景下，分析人员期望能自由构建图形，比如自由构建 维度 和 指标， 自由选择仪表板的 图标展示等。  
类似在点击编辑按钮后的效果。  比如默认可以在 图标上面 加一个自由构建按钮，  用户点击后， 打开编辑页面让用户构建。  最后屏蔽掉保存按钮即可。 

![image](https://github.com/dataease/dataease/assets/30259184/6f398633-b521-4189-804e-c6ff2d2d3750)

期望在2.X版本实现.

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，2.x版本构建图表的流程：先选择图表类型、再选择数据集，如果修改为先选择数据再构建图表，跟目前的设计是相反的，因此2.x没有计划做此处的更改，再次感谢您的反馈和支持。

**Comment by 18927580527** [comment]
额，我说的意思是。 用户不止是看报表。 他可能要基于这个数据自己做分析。  不是所有人员都是 报表的开发。  绝大部分人员是只有查看权限的。   在查看的状态下，如何自由构图。 这种情况下一般是分析人员需要用到。
