### ISSUE TITLE
[Feature] DataEase v2 数据集数据表加载优化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7649]
**请描述您的需求或者改进建议.**
当前 DataEase v2 版本在数据集添加自定义 SQL 时，数据源中的表数据量较大会导致浏览器崩溃。
实测表数量 30855 张。
观察了浏览器请求，在选中数据源及拖拽自定义SQL时分别都会去请求一次表结构，这块是否可以进行优化。
<img width="1268" alt="image" src="https://github.com/dataease/dataease/assets/30063018/919038b8-5808-4fd6-8e8a-2094c3a5d5a1">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们讨论一下优化方案。

**Comment by xuwei-fit2cloud** [comment]
我们在后续版本优化一下。
