### ISSUE TITLE
[Feature] DataEase v1 ，过滤组件提示文字颜色支持调整

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7650]
**请描述您的需求或者改进建议.**
希望过滤组件的提示文字可支持调整配色
<img width="786" alt="image" src="https://github.com/dataease/dataease/assets/30063018/9b42cce4-863e-46e1-916d-64832c48cfcb">
<img width="522" alt="image" src="https://github.com/dataease/dataease/assets/30063018/17eb30c3-ced0-4d0e-a8ca-d22ccd73f53b">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，需求已记录，会在近几个版本内支持。
