### ISSUE TITLE
[Feature]表格视图滚动条的鼠标识别宽度建议放大一些，windows系统下仪表板编辑页面滚动条不好选择，容易造成视图位置变动

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#7655]
**请描述您的需求或者改进建议.**
windows系统下，仪表板编辑页面滚动条不好选择，鼠标移到滚动条上总是显示十字花的标识（即视图拖动状态），本来只是想拖一下滚动条，容易造成视图位置的拖拽
![image](https://github.com/dataease/dataease/assets/89771514/4d0f899d-0c7d-43dc-bc41-087ef334dd9e)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们会在近几个版本内做相关优化。

**Comment by fit2cloudrd** [comment]
在编辑状态下，横向滚动条与组件拖动区域重叠，目前确实不好处理。
但在查看状态下，是不会有这个问题的，应该是不会影响使用的。
