### ISSUE TITLE
【需求】【仪表板】可以配置/指定数据排序顺序

### ISSUE THREAD

**Issue by hailiejam** [dataease/dataease#7657]
**请描述您的需求或者改进建议.**
背景：目前多字段排序是按照列表中列的前后顺序进行排序 可参考下图，先进行A排序，再进行B排序
期待：可以在不改变列表中列的展示顺序，指定列排序顺序，比如：指定先进行B排序，再进行A排序
![image](https://github.com/dataease/dataease/assets/156776170/d72b237e-797c-40a0-b78b-a507d5bff259)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，技术上是可以实现，但我们还需要讨论一下相关的交互设计。

**Comment by xuwei-fit2cloud** [comment]
我们尝试支持一下。
