### ISSUE TITLE
[Bug] DataEase v2 连接 oracle 11g，创建数据集报错

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7661]
**DataEase 版本**
v2.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 120.0.6099.216（正式版本） (arm64)

**Bug 描述**
DataEase v2 连接 oracle-xe-11g，数据源校验成功，创建数据集时，拖拽单表或自定义SQL均会报错。

**Bug 重现步骤(有截图更好)**
1. 添加 oracle 数据源，校验成功
<img width="1475" alt="image" src="https://github.com/dataease/dataease/assets/30063018/671c057d-2ea4-40fd-a185-e4f68d381c53">

2. 创建数据集，拖拽单表，点击刷新数据报错
<img width="1475" alt="image" src="https://github.com/dataease/dataease/assets/30063018/cb50d915-45cf-4b79-9e58-046e550450a1">

3. 自定义 SQL，同样有报错信息
<img width="1475" alt="image" src="https://github.com/dataease/dataease/assets/30063018/799b6d4d-8423-41a5-bc5f-1e7b471de6e6">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by mayou33** [comment]
我也遇到了同样的问题

**Comment by hapeacock** [comment]
我的也是。我还一直以为是我的问题。视图也获取不到。还有就是数据集也获取不到中文注释字段别名

**Comment by reteng** [comment]
问题同上

**Comment by 1395961821** [comment]
我的也一样，Oracle11g，我看生成的sql语句和Oracle11g兼容的语句不一样，Oracle旧版本需要使用rownum进行分页，新版本使用的是limit和offset，希望尽快修复这个问题

**Comment by maninhill** [comment]
这个问题 v2.4 发版前再核对下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
