### ISSUE TITLE
[Question]添加数据库数据集时无法导入doris

### ISSUE THREAD

**Issue by SumaraiRyuma** [dataease/dataease#7663]
我从mysql数据库选择了自带的sys_log表来创建数据集，kettle job会把数据写到txt文件，大小为4M，接着会自动通过shell脚本导入到doris，但是在导入doris时报错了，错误如下图
![image](https://github.com/dataease/dataease/assets/19151862/36fcd933-58e8-4826-a6d1-1733c2797e5a)
当我选择其他数据量小的表来创建数据集时是可以正常导入doris的，请问下这种情况各位大佬有遇到吗？麻烦协助处理下，谢谢

**Comment by SumaraiRyuma** [comment]
shell脚本如下 curl --location-trusted -u root: -H "label:2977687c-25bf-4781-9e06-ecc367acc5351705404987610" -H "column_separator:|DE|" -H "columns:C_b80bb7740288fda1f201890375a60c8f,C_a15b1ede78d4601bf7345a42159f849d,C_57746cc8160496aefc9fb306b6ba24e3,C_c4d98dbd5badae901761ab6422fa3e70,C_305d28898e362717b3ad3d0181c15636,C_9acb44549b41563697bb490144ec6258,C_caf9b6b99962bf5c2264824231d7a40c,C_b16a626598674ad426e4b885017906d7,C_87663c41625eb6d18e22f0381e226139,dataease_uuid" -H "merge_type: APPEND" -T /F/opt/dataease/data/kettle/tmp_ds_2977687c_25bf_4781_9e06_ecc367acc535.txt -XPUT http://192.168.8.239:8030/api/dataease/tmp_ds_2977687c_25bf_4781_9e06_ecc367acc535/_stream_loads

**Comment by SumaraiRyuma** [comment]
dataease 版本是1.8 ，doris版本是2.0.2 ，kettle版本是8.2

**Comment by maninhill** [comment]
暂无支持计划。

**Comment by SumaraiRyuma** [comment]
您好，邮件已收到！我会尽快回复你。
