### ISSUE TITLE
[Bug]AntV基础柱状图，设置样式颜色后，再手动修改数据指标的显示名称，设置的样式颜色失效

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#7665]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
AntV基础柱状图，设置样式颜色后，再手动修改数据指标的显示名称，设置的样式颜色失效
![image](https://github.com/dataease/dataease/assets/89771514/d443c644-6485-4b32-bef2-c9ebd0bcf459)
![image](https://github.com/dataease/dataease/assets/89771514/6fa69abe-84ca-415f-a158-4bcef60e9c51)

![image](https://github.com/dataease/dataease/assets/89771514/21e95a13-576c-4264-b930-25db92452546)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
