### ISSUE TITLE
[Feature] antv 表格组件支持表头排序

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7671]
**请描述您的需求或者改进建议.**
如图
![image](https://github.com/dataease/dataease/assets/45852479/975b7d1d-f3db-4060-9018-a87090d534f3)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个需求已排期。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
