### ISSUE TITLE
[Feature]v2 希望数据大屏在加入参考线 像wps在制作ppt的时候一样 对齐居中的时候能进行显示，包括选中很多图层时，可以组合内对齐（参照ppt）

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#7696]
v2 希望数据大屏在加入参考线 像wps在制作ppt的时候一样 对齐居中的时候能进行显示，包括选中很多图层时，可以组合内对齐（参照ppt）

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，批量选中组件实现对齐的功能在v2.3中实现，请关注下个版本的release notes。

对齐参考线规划到近期的版本中增加。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
