### ISSUE TITLE
[Feature] DataEase v1 兼容 CAS 2

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7698]
**请描述您的需求或者改进建议.**
DataEase v1 目前支持对接 CAS 3，不支持对接 CAS 2 ，对接 CAS 2 的时候会抛出以下异常
<img width="1156" alt="image" src="https://github.com/dataease/dataease/assets/30063018/686939d6-b62c-4944-a9a5-0cc1fb5cd6cc">
<img width="816" alt="image" src="https://github.com/dataease/dataease/assets/30063018/60ac0857-ef37-4516-806c-ccc5c54d581b">
希望能够支持 CAS 2

**Comment by xuwei-fit2cloud** [comment]
我们会在近期版本添加相关支持。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
