### ISSUE TITLE
[Bug] SQL Server 数据源，明细表，当按照某个字段进行排序是，如果结果展示没有限制，会有如下报错

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7700]
**DataEase 版本**
v1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
SQL Server 数据源，明细表，当按照某个字段进行排序是，如果结果展示没有限制，会有如下报错

**Bug 重现步骤(有截图更好)**
<img width="1284" alt="企业微信截图_d536cbb2-0f64-4d2f-b14b-41c17e9fa985" src="https://github.com/dataease/dataease/assets/45852479/7de527ba-33c5-4c95-a4fc-7f3ef2c7c7ac">
<img width="1291" alt="企业微信截图_7ae917a0-915d-463b-b219-374e6216e391" src="https://github.com/dataease/dataease/assets/45852479/2530ed66-b0fe-4c74-8ce1-2d1f47a0707b">

**Comment by BBchicken-9527** [comment]
感谢反馈，问题将会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
