### ISSUE TITLE
[Bug]使用SQL数据集在进行新建字段的时候报错

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#7702]
**DataEase 版本**

v2.2.0
**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 120.0.6099.217（正式版本） （64 位）

**Bug 描述**

先用case when对字段进行条件判断，新建计算字段sum(casewhen的字段)/sum(其他字段)，报错
**Bug 重现步骤(有截图更好)**
使用SQL数据集正常
![image](https://github.com/dataease/dataease/assets/127368807/0215a2f8-3c98-4e61-b05e-7646ac9c6ea0)
新建计算字段
![image](https://github.com/dataease/dataease/assets/127368807/69335017-57e5-407a-afd6-1f9d047f0899)
数据大屏使用字段的时候报错
![image](https://github.com/dataease/dataease/assets/127368807/32672a2a-9669-45bd-b0e0-9e6e930b746e)

**Comment by greenyhsj** [comment]
![image](https://github.com/dataease/dataease/assets/127368807/b6117219-6063-4f92-a95e-806c65c1c3df)

**Comment by BBchicken-9527** [comment]
感谢反馈，sum 里不能case when的；
