### ISSUE TITLE
表格列宽自定义或者自适应 我拉开的列宽能不能也保存[Feature]

### ISSUE THREAD

**Issue by zhoulel** [dataease/dataease#7707]
**请描述您的需求或者改进建议.**
表格这边 有些列我需要特别宽  数字列又不需要 不能根据我 自定义的保存  
![image](https://github.com/dataease/dataease/assets/139849659/0e6b7702-498f-45b2-b12a-1da50543dec7)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，该需求已经加入近期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
