### ISSUE TITLE
V2版本的H2SQL语句初始化有问题，希望在2.3.0版本修复一下！

### ISSUE THREAD

**Issue by 172151295** [dataease/dataease#7708]

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请问初始化是报错吗？可以把报错信息发一下，我们这边排查下。

**Comment by 172151295** [comment]
创建表的SQL有问题你可以自己测试一下

**Comment by 172151295** [comment]
> 感谢您的反馈，请问初始化是报错吗？可以把报错信息发一下，我们这边排查下。

2.2版本切换成桌面配置文件，在初始化的时候就报错

**Comment by yayanpei-fit2cloud** [comment]
确认已修复，下个版本发。

**Comment by maninhill** [comment]
v2.3 已经支持。

https://github.com/dataease/dataease/releases/tag/v2.3.0
