### ISSUE TITLE
v2 版本后续分享功能可否支持自定义用户密码登陆，而不是单纯的通过分享密码就可以查看。

### ISSUE THREAD

**Issue by 172151295** [dataease/dataease#7709]

**Comment by xuwei-fit2cloud** [comment]
是要求创建公共链接的时候，自己可以设置这个公共链接的访问密码吗？

**Comment by 172151295** [comment]
> 是要求创建公共链接的时候，自己可以设置这个公共链接的访问密码吗？

不是，需要用户名密码登陆和帆软那样的登陆

**Comment by 172151295** [comment]
创建公共连接，可以指定一个用户和密码登陆，而不是单纯的密码，创建公共连接后可以实现其他用户登陆的方式查看

**Comment by xuwei-fit2cloud** [comment]
公共链接的访问，是以创建公共链接的用户的权限来访问的，所以不存在以其他用户登录的方式来访问的场景。
您说的应该是仪表板的分享功能，那个我们也是支持的。
