### ISSUE TITLE
[Bug] antv 折线图折点大小设置后，移动端未生效

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7710]
**DataEase 版本**
v1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
antv 折线图折点大小设置后，移动端未生效

**Bug 重现步骤(有截图更好)**

**Comment by BBchicken-9527** [comment]
感谢反馈，因为移动端适配问题折点这里就是固定值；
