### ISSUE TITLE
希望提供数据集可传变量的功能

### ISSUE THREAD

**Issue by pengzhengyou** [dataease/dataease#7711]
**请描述您的需求或者改进建议.**
需求背景：需要制作一个测试质量大屏，大屏里需要按照项目维度和时间维度统计 ，某个时间段内的某些项目的测试计划数量。
SQL语句如下：
select count(*) '测试计划总数量', t.project_id ,t.status '测试计划状态' , project.name '项目名称' from test_plan t left join     project on project.id = t.project_id where test_plan.create_time  group by t.status  , t.project_id  ;
由于需要使用聚合函数 count(*)按照项目分组后统计数量，因此测试计划的创建时间在聚合完成后如下图所示：
<img width="779" alt="截屏2024-01-19 下午2 26 29" src="https://github.com/dataease/dataease/assets/34637801/c2868eef-c442-4c84-900f-3935e61ee979">
三条测试计划的记录的创建时间聚合成一个时间，因此平台现有的功能在聚合完成后再通过时间筛选，则结果不准确。
需求描述：希望能增加前端时间组件能将选中的时间作为变量传递给数据集的SQL语句，以实现在数据聚合完成之前筛选出目标数据。
实现建议：数据集支持图表前端传递参数作为变量。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议您使用日期过滤组件，并绑定数据集的参数，以此来完成数据的过滤。具体可参考文档：
https://dataease.io/docs/v1/user_manual/dataset_configuration/dataset_SQL/#4
