### ISSUE TITLE
[Feature] antv s2 支持根据列设置不同的对齐方式，比如左对齐、居中对齐、右对齐

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7712]
**请描述您的需求或者改进建议.**
antv s2 支持按照数值格式类型进行对齐（V2.x）
![image](https://github.com/dataease/dataease/assets/45852479/21b6dc02-b50e-4f40-a608-b6d11f8ebc1d)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先加入到需求池中，短期内还没有支持计划。
