### ISSUE TITLE
DORIS数据源表，comment值读取不出来[Bug]

### ISSUE THREAD

**Issue by Linkjie-11** [dataease/dataease#7713]
**DataEase 版本**
V2.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**

字段描述未获取到

**Bug 重现步骤(有截图更好)**
1.
![32eb9faaa9d421192b2d22a9d78bd10](https://github.com/dataease/dataease/assets/52249559/cc47daeb-c509-4091-ac74-f0dd66001998)

**Comment by BBchicken-9527** [comment]
感谢反馈，由于现在是通过calcite进行连接，我们讨论一下；

**Comment by maninhill** [comment]
已支持。
