### ISSUE TITLE
大屏时间组件无法正确传递时间参数到数据集，作为数据集的SQL的变量

### ISSUE THREAD

**Issue by pengzhengyou** [dataease/dataease#7714]
**DataEase 版本**
v1.18.14

**运行方式(安装包运行 or 源码运行 ?)**

安装包运行
**浏览器版本**

谷歌120.0.6099.216（正式版本）
**Bug 描述**
大屏时间组件在绑定好相关参数后，切换时间，图表上展示的数据和数据库中查询实际得到的数据不一致

**Bug 重现步骤(有截图更好)**
1.准备一个metersphere v2.10.10的环境，并创建多个项目，并在各个项目中创建多个测试计划
2.创建数据集，SQL语句为：select count(*) '测试计划总数量', t.project_id ,t.status '测试计划状态' , project.name '项目名称', FROM_UNIXTIME(t.`create_time` / 1000, '%Y-%m-%d %H:%i:%s') AS '创建日期' from test_plan t left join     project on project.id = t.project_id  where  FROM_UNIXTIME(t.`create_time` / 1000, '%Y-%m-%d %H:%i:%s')  BETWEEN '${BEGINTIME}' AND '${ENDTIME}'    group by t.status  , t.project_id  ;
3.通过SQL语句查询目标数据，如下图所示：
<img width="1155" alt="截屏2024-01-19 下午4 42 22" src="https://github.com/dataease/dataease/assets/34637801/d82fc4cd-2962-4e0e-85d6-5498247f38ff">
4.配置好数据集对应的参数
<img width="1350" alt="截屏2024-01-19 下午4 43 18" src="https://github.com/dataease/dataease/assets/34637801/84e38519-7b9e-40b5-8b6a-09f5ac5ed652">
5.配置对应图表参数
<img width="342" alt="截屏2024-01-19 下午4 43 45" src="https://github.com/dataease/dataease/assets/34637801/c37fefda-cea4-4e82-83cd-e9a488c5db6f">
6.配置时间组件对应的参数
<img width="1164" alt="截屏2024-01-19 下午4 45 55" src="https://github.com/dataease/dataease/assets/34637801/72d3f92c-4a34-4a80-a6e5-2bcce1339c22">
7.根据前面数据库查询的结果，选择2023-10-18日-2023-12-5日的数据
<img width="1377" alt="截屏2024-01-19 下午4 47 10" src="https://github.com/dataease/dataease/assets/34637801/a05d0068-1a31-4d0b-9c3e-b73bf99aa891">
8.查询的结果为3个，但根据数据库实际结果应该为5

**Comment by BBchicken-9527** [comment]
感谢反馈，方便看一下接口的sql吗？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
