### ISSUE TITLE
地图这个地方不支持多个数据吗？

### ISSUE THREAD

**Issue by 172151295** [dataease/dataease#7716]
**请描述您的问题.**
![wx_camera_1705653952128.jpg](https://github.com/dataease/dataease/assets/70830248/8b55f592-ebe5-4813-bc07-46335fe06f73)

![wx_camera_1705653952128.jpg](https://github.com/dataease/dataease/assets/70830248/9b54198c-878d-4e3f-b55f-ee57aea5761d)

后面支持吗？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，后面有计划进行支持。
