### ISSUE TITLE
[Feature]通过Excel导入数据预览时无法选择地理数据匹配地理类型

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#772]
**请描述您的需求或者改进建议.**

通过Excel导入数据预览时无法【地理数据】类型可设置
![image](https://user-images.githubusercontent.com/60059766/132189541-b238bff5-1870-42a8-b8e3-815af4bb8195.png)

**Comment by yayanpei** [comment]
感谢您的反馈，您可以参考用户手册设置进行地理数据匹配。
