### ISSUE TITLE
[Feature]文本类型的列中存在空值时，过滤组件可筛选空值

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#7720]
**请描述您的需求或者改进建议.**
<img width="378" alt="image" src="https://github.com/dataease/dataease/assets/101089844/d14e964d-0968-46a9-ab60-0c36be686f61">
<img width="560" alt="image" src="https://github.com/dataease/dataease/assets/101089844/f652e92b-df94-48c5-b02d-b14bc3db67f3">
![wecom-temp-669363-485514a9ef0c8efc74b28b66a25b9385](https://github.com/dataease/dataease/assets/101089844/66007065-326c-4123-b14e-548e66190656)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先讨论一下。
