### ISSUE TITLE
[Bug] DataEase v2 在 Excel 数据比较多的情况上传后数据为空

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7722]
**DataEase 版本**
v2.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 120.0.6099.234（正式版本） (arm64)

**Bug 描述**
3w 的 Excel 数据，上传文件时预览正常，保存后数据为空。
Excel 数据：
[测试.xlsx](https://github.com/dataease/dataease/files/14000256/default.xlsx)

**Bug 重现步骤(有截图更好)**
1. 数据源上传 Excel 文件，预览正常，如下所示：
<img width="1476" alt="image" src="https://github.com/dataease/dataease/assets/30063018/faa38044-68dd-47ce-8c18-3a8a4e623d47">

2.保存后数据预览为空
<img width="1192" alt="image" src="https://github.com/dataease/dataease/assets/30063018/0e5ed3dd-901f-4bf8-858e-f6c5c71dea11">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by Lucas200404** [comment]
> 感谢反馈，我们会在下个版本进行修复；

大概什么时间嗯

**Comment by maninhill** [comment]
v2.3.0 已修复。
