### ISSUE TITLE
[Feature]建立的数据集可以导出对应的sql语句或.sql文件

### ISSUE THREAD

**Issue by Linkjie-11** [dataease/dataease#7724]
**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
这个需求是v1.x版本的吗？
数据集的SQL的导出，我没有理解。数据库数据集的SQL就相当于是 select * from xxx，SQL数据集本身就有SQL，Excel和API是DataEase存在数据库里的，也相当于select * from xxx，您需求的意义是？

**Comment by Linkjie-11** [comment]
关联数据集以及进行过新建字段处理后的数据的sql是否可以支持导出？

**Comment by xuwei-fit2cloud** [comment]
这个目前还没有支持计划。
