### ISSUE TITLE
[Feature]透视表的合计功能行汇总可以进行独立计数，汇总求和后，可查看汇总结果计数

### ISSUE THREAD

**Issue by Linkjie-11** [dataease/dataease#7725]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/52249559/7d47d2b0-1dd2-4c5a-b0e3-6f88cfa727ca)

**Comment by xuwei-fit2cloud** [comment]
已有相关需求，我们还在设计中，请耐心等待。
