### ISSUE TITLE
[Feature]页面可以直接拷贝数据：指标卡内数据可以进行选中复制

### ISSUE THREAD

**Issue by Linkjie-11** [dataease/dataease#7726]
**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/52249559/187d107c-f13c-412b-aee0-eef0b2a083b1)

**Comment by xuwei-fit2cloud** [comment]
我们在后续版本支持一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
