### ISSUE TITLE
[Feature]视图可以放大查看，阈值标识的背景色及数值的颜色不变

### ISSUE THREAD

**Issue by Linkjie-11** [dataease/dataease#7728]
**请描述您的需求或者改进建议.**

![image](https://github.com/dataease/dataease/assets/52249559/68bfd995-8c3e-45e1-8821-c6e20d2e6827)
![image](https://github.com/dataease/dataease/assets/52249559/e860e677-6b37-4010-a7b2-f5342e9112e5)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，表格是不支持放大功能的。
