### ISSUE TITLE
[Feature]表格视图查看明细，字体自适应调整

### ISSUE THREAD

**Issue by Linkjie-11** [dataease/dataease#7729]
**请描述您的需求或者改进建议.**
目前表格查看明细时，字体大小不会自适应调整，字体显示过小
![image](https://github.com/dataease/dataease/assets/52249559/2b93dfe6-dd9f-4d5e-80a3-771b80df0603)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，视图明细窗口的大小是固定的，因此暂不考虑做自适应的功能。我们调整下明细数据的字体大小。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
