### ISSUE TITLE
[Feature]横向柱状图柱子多个标签重叠问题

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#7735]
DataEase 版本:
v1.18.14

目前有这种情况，横向柱状图，柱子值很小时标签会重叠的问题，目前我们也没有想到解决方案，不知产品这边有没有好的想法避免这个问题
![图片](https://github.com/dataease/dataease/assets/48307752/5373f28f-f36c-481e-a382-c0bf000d7bd3)

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议设置一下数值格式，减小数值的长度。已知问题，图库这边目前无法处理。
