### ISSUE TITLE
[Feature]希望 echart 的散点图  和 antv散点图一样，可以配置多个维度

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#7739]
DataEase 版本:
1.18.14

希望 echart 的散点图  和 antv散点图一样，可以配置横轴/维度或指标、配置子维度等。
![图片](https://github.com/dataease/dataease/assets/48307752/a71e5cae-e02e-4389-9f0f-62d4bf628866)

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
建议使用AntV图库的散点图，是有什么地方让您需要使用ECharts图库的散点图呢？

**Comment by mfanoffice** [comment]
> 建议使用AntV图库的散点图，是有什么地方让您需要使用ECharts图库的散点图呢？

antv散点图可以设置多个维度/指标，但标签不支持自定义显示多个维度/指标的内容，而echart 散点图可以自定义设置标签内容。

**Comment by xuwei-fit2cloud** [comment]
我们会在后期对AntV图库进行增强，对ECharts图库，暂时没有计划对这块进行调整。
