### ISSUE TITLE
想请问一下有没有考虑支持自定义JDBC数据源的连接

### ISSUE THREAD

**Issue by wuwuwuuw** [dataease/dataease#774]
**请描述您的需求或者改进建议.**
用户可以通过JDBC连接字符串的配置连接到任意支持JDBC的数据库

**Comment by yayanpei** [comment]
感谢您的反馈，我们内部先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
目前dataease使用jdbc方式连接数据库，还需要做一层自己的抽象处理，在当前的设计下暂时还不能实现该需求。
