### ISSUE TITLE
[Feature] DataEase v2 版本仪表板名称、文件夹名称等按照名称进行升序

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7741]
DataEase 版本:
 DataEase v2.2

**请描述您的需求或者改进建议.**
目前 DataEase v2 版本仪表板的排序是按照创建时间来的，新创建的在最上面。
希望可以按照名称进行排序。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池中，近3个月暂时没有支持的计划。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
