### ISSUE TITLE
[Question]请问我安装的开源版本，为什么没有数据大屏的分享功能呢，就是公共链接

### ISSUE THREAD

**Issue by xczlife** [dataease/dataease#7744]
如标题，我装了v2版本的dataease，但是仪表盘和数据大屏都没有找到分享按钮

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，社区版分享功能已实现，会在 v2.3（发布日期：2024/2/1） 版本发布。

**Comment by maninhill** [comment]
v2.3 已经支持。

https://github.com/dataease/dataease/releases/tag/v2.3.0
