### ISSUE TITLE
[Bug]doris数据源，sql数据集中使用参数时，sql中含有两行空行时执行报错

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#7750]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
doris数据源，sql数据集中使用参数时，sql中含有两行空行时执行报错，一行空行时不报错
![image](https://github.com/dataease/dataease/assets/89771514/21d8b300-2096-46f4-b0f6-cab01fddd4dd)
![image](https://github.com/dataease/dataease/assets/89771514/502d07a1-cd01-43ed-ab90-40c747e82c2f)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
