### ISSUE TITLE
[Bug] 导入Excel数据集时，字段类型被设置为bigint(20)，保存时报长度超限异常

### ISSUE THREAD

**Issue by DevotedTangLiu** [dataease/dataease#7752]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 版本 120.0.6099.225（正式版本） （64 位）

**Bug 描述**
创建数据集时，导入Excel数据集，字段被创建为bigint(20), 但excel 中实际值超过了Long (bigint(20)) ，（值为 20230705000100000057），在保存数据时失败，提示 `Out of range value for column`

**Bug 重现步骤(有截图更好)**
1. 创建数据集
2. 导入Excel数据集
3. 预览->保存
![image](https://github.com/dataease/dataease/assets/7692677/468e4182-3855-4232-9c79-89257c663b1f)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
