### ISSUE TITLE
[Bug]【权限】人员没有数据集的权限，筛选框却能看到所有数据

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#7757]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
人员没有数据集的权限，筛选框却能看到所有数据

**Bug 重现步骤(有截图更好)**
1.不赋予用户 Shane 关于数据集 6S 的权限；
![image](https://github.com/dataease/dataease/assets/24768910/e7373f78-194b-47c1-8a87-7d6fa6ce3f30)

2.创建一个基于 6S 数据的视图和筛选组件的仪表板，并将这个仪表板给到查看权限给 Shane 用户；
![image](https://github.com/dataease/dataease/assets/24768910/eebe7072-798b-4845-831a-6c5c5a2ad1f6)
![image](https://github.com/dataease/dataease/assets/24768910/f937b3c5-aca3-4d70-86d9-80339a2606ee)
![image](https://github.com/dataease/dataease/assets/24768910/268910d8-0e2e-4259-93dd-8af77a096fbc)

3.切换 Shane 用户，查看仪表板的时候发现，视图看不到（正常），但是筛选组件有数据（不正常）。
![image](https://github.com/dataease/dataease/assets/24768910/4872db5c-a6dd-4483-bd1d-aec61296d99c)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们讨论一下；

**Comment by xuwei-fit2cloud** [comment]
我们在近期版本修复一下
