### ISSUE TITLE
报表图形支持查看sql[Feature]

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#7773]
DataEase 版本: 2.4
支持查看报表或者图形的sql, 用于排查问题.
![image](https://github.com/dataease/dataease/assets/30259184/c72a529a-4b6b-4f4f-8c2c-1e241dc263a3)

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求我们先加入需求池中，可能近期还不会进行支持。如果需要查看视图sql，可以 F12 进行查看。

**Comment by maninhill** [comment]
6个月内无更新，关闭。
