### ISSUE TITLE
[Bug]v2 SQL 添加库名会报错

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#7778]
**DataEase 版本**
v1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
在写 SQL 是有时会设计跨库查询，SQL 中使用 库名.表名 格式会报错，而这个语法是符合 calcite 的。
请问是 bug还是功能设计限制？
<img width="1927" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/dc42980c-cba8-499e-8dc4-f9f2d7611c89">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by heihei180** [comment]
sql 看起来被修改了，你的库名.表明，被当成一个字段了

**Comment by BBchicken-9527** [comment]
感谢反馈，这种sql跨库的方式是不被允许的，这样就跳过了数据源的创建和权限的控制，我们无法保证你跨库访问的表在你应有的范围内，所以建议还是正常的形式通过数据源进行连表；
