### ISSUE TITLE
[Bug]仪表板界面ctrl+s保存会错乱

### ISSUE THREAD

**Issue by zhangcongwayne** [dataease/dataease#778]
**DataEase 版本**
V1.2.1

**浏览器版本**
谷歌

**Bug 描述**
仪表板界面，ctrl+s保存，会错乱

**Bug 重现步骤(有截图更好)**
1.保存后，官方模板被覆盖
![image](https://user-images.githubusercontent.com/34704409/132285864-2a0143e1-89ed-4a16-aee7-c38cf9d3adb7.png)

2.保存后，官方样式丢失。
![image](https://user-images.githubusercontent.com/34704409/132285886-f8b6e5e1-015f-422b-9a61-5f0864a1c4f3.png)

**Comment by yayanpei** [comment]
非常感谢您的反馈，我们尽快验证并修复。

**Comment by xuwei-fit2cloud** [comment]
该问题已修复。
