### ISSUE TITLE
[Bug]v1版本 文本下拉框选择问题 

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#7782]
文本下拉框 编辑的时候显示正常 但是如果在编辑页面预览或者是返回仪表板全屏预览 下拉框显示不出里面的内容  对于分享链接查看（包括全屏）都没有问题
![image](https://github.com/dataease/dataease/assets/141667200/b9333317-a4ba-4cd2-9afd-75d4b7e3fc44)

**Comment by wolf-kingx** [comment]
![image](https://github.com/dataease/dataease/assets/141667200/18ce6efe-90b7-4c79-9780-fdf34d5ede67)

**Comment by BBchicken-9527** [comment]
感谢反馈，方便详细说明一下你的复现步骤嘛？

**Comment by wolf-kingx** [comment]
1 随便一个视图 再加一个文本下来框
2 在编辑页面 下拉框可以显示所以选项 但是如果在编辑页面点击预览 发现下拉框不管怎么点 没有选项了
3 保存编辑 返回到仪表板页面 然后点全屏预览 也会出现同样的问题

**Comment by wolf-kingx** [comment]
emmmm。。
我第一回复现 直接就复现出来了 但是我刚写完步骤 突然有了

**Comment by BBchicken-9527** [comment]
是出现提示：无数据吗？

**Comment by wolf-kingx** [comment]
不是 正常下拉框里面是有数据的 但是全屏预览的时候 不管怎么点下拉框 都不显示选项了

**Comment by BBchicken-9527** [comment]
是的我知道的，我说是不是全屏状态下，下拉框会提示你无数据

**Comment by wolf-kingx** [comment]
没有任何提示 就是点了没什么反应

**Comment by BBchicken-9527** [comment]
emm...受累看看清除一下缓存是否可以正常打开，如果还不行方便看一下前端是否有什么异常提示吗？

**Comment by wolf-kingx** [comment]
刚开始直接复现出来了 后续正常了 可能是缓存的问题 之后在再遇到 我注意一下

**Comment by wolf-kingx** [comment]
试了一下 清缓存没有用 点击文本框 就是无响应的状态

**Comment by wolf-kingx** [comment]
一般有这个报错是正常的吗
<img width="817" alt="1de366cb59fa9a84b738e4501aff49ab" src="https://github.com/dataease/dataease/assets/141667200/9282ece9-ddeb-48cf-a1a3-996f7ce6318a">

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你的平台版本是最新的吗？

**Comment by wolf-kingx** [comment]
是最新版

**Comment by BBchicken-9527** [comment]
方便给录像看一下你完整的操作步骤吗？

**Comment by BBchicken-9527** [comment]
请问你的数据源是什么，连接方式是什么？如果可以我整体的模拟一下你的情况看看能不能达到复现的可能

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
