### ISSUE TITLE
[Bug] 移动端仪表盘前端console报错

### ISSUE THREAD

**Issue by DuLianYong-Chinese** [dataease/dataease#7783]
**DataEase 版本**
v1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
官网

**浏览器版本**

**Bug 描述**
移动端仪表盘前端console报错

**Bug 重现步骤(有截图更好)**
1.点击仪表盘样式，选择智慧数据主题并应用
![image](https://github.com/dataease/dataease/assets/42732955/50ed548e-c754-4820-a028-3dd79217be7e)
2.切换到移动端
![image](https://github.com/dataease/dataease/assets/42732955/bff439b8-51e8-43b6-b6e8-0f9b31e52b85)
3.前端consolelog报错
![image](https://github.com/dataease/dataease/assets/42732955/f139e69f-8187-42ce-901f-ea43c59e99b3)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
