### ISSUE TITLE
[Bug]v2版本 地图映射 即使改成标准的国家名称 在地图上还是不能显示 有的会显示有的不行

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#7793]
这个是使用的数据集
![image](https://github.com/dataease/dataease/assets/141667200/4b943e24-fd20-45d5-95e6-56b743ec02ea)

这个是xian'shi显示结果 只有两个显示出来了 China都没有显示出来
![image](https://github.com/dataease/dataease/assets/141667200/a7275150-54d8-4c50-904d-3510a40f0272)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前没发现你说的这个问题，方便问一下具体的步骤吗？并且说明一下使用的数据源以及字段类型；
![image](https://github.com/dataease/dataease/assets/84372766/364a8ecf-abf1-47c7-9c68-b717b439289d)

**Comment by wolf-kingx** [comment]
这个直接是excel的数据集 三个城市 只显示了两个
![image](https://github.com/dataease/dataease/assets/141667200/b28966c9-5cc9-4009-9479-b08341937f5c)
![image](https://github.com/dataease/dataease/assets/141667200/7c6dcc31-7767-49cd-a0a6-edf8dff4605d)

**Comment by BBchicken-9527** [comment]
如果是excel的话方便给我看一下你这两次的测试数据吗？

**Comment by wolf-kingx** [comment]
这个原来的excel是这样的
![image](https://github.com/dataease/dataease/assets/141667200/1332f078-5c01-43b7-9379-b3be22578a45)

然后用sql 把不符合的名字换成标准的
![image](https://github.com/dataease/dataease/assets/141667200/fe52307f-f453-4e67-bb92-3390a4c98d10)

最后的结果只有这样
![image](https://github.com/dataease/dataease/assets/141667200/b9d767c1-0f35-4936-8db1-2eef57eeb865)

**Comment by wolf-kingx** [comment]
[date.xlsx](https://github.com/dataease/dataease/files/14035384/date.xlsx)

**Comment by wolf-kingx** [comment]
select 
case when city='中国' then 'China'
  when city='无名氏' then 'Indonesia'
when city='吼吼吼' then 'Cuba'
when city='河北省' then 'Australia'
when city='北京市' then 'Spain'
end as city,
订单数量
from excel_Sheet1_f509c12084

**Comment by wolf-kingx** [comment]
第一次的excel没保存 照着随便写下就行了

**Comment by BBchicken-9527** [comment]
好的，我现在看看；

**Comment by BBchicken-9527** [comment]
感谢反馈，问题已经开始定位了，我们会尽快修复此问题；

**Comment by xuwei-fit2cloud** [comment]
v2.6版本已处理，请升级版本。
