### ISSUE TITLE
[Feature]AntV组合图依赖文件有点大 目前看有6.6M 影响页面加载速度

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#7802]
仪表板在加载的时候速度还可以 但是通过分享链接访问的时候 仪表板的组合图在加载的时候非常慢 比其他的慢9s左右 数据集里面只有70条数据

![5944c51eff8f85c3798812a8cebeb11](https://github.com/dataease/dataease/assets/141667200/2392c6e4-d589-4316-b5e0-e506d5a00997)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们回复如下：
1、组合图依赖的文件比其他图表大，是由于组合图是以插件的形式开发的。
2、仪表板在系统中加载和公共链接加载，第一次的加载速度应该是差不多的。由于系统中仪表板加载时用了缓存机制，因此再次加载时相对第一次会快一些。我们看一下公共链接这里能否优化。

**Comment by yayanpei-fit2cloud** [comment]
我们对组合图加载的依赖文件进行了缩小，页面加载速度比之前提升了很多，但由于是插件的关系，还是会比其他图表略慢一点。优化已完成，会在下周四的版本发布。

**Comment by wolf-kingx** [comment]
好的

**Comment by maninhill** [comment]
v2.3 已经支持。

https://github.com/dataease/dataease/releases/tag/v2.3.0
