### ISSUE TITLE
[Feature]指标计算可以支持百分数方式

### ISSUE THREAD

**Issue by fitchibing** [dataease/dataease#782]
**请描述您的需求或者改进建议.**
版本：1.2
希望指标计算后的值可以支持百分数存在；目前指标计算 可以通过concat(ROUND((具体指标或者指标的运算结果*100),2),"%")  方式转换为百分数，但是只能以文字方式，导致视图界面只能选为文字，则只能计数方式展示 无法进一步使用

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
