### ISSUE TITLE
[Bug] 横向堆叠图标签显示时，有标签重叠现象，影响观感！

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#7820]
**DataEase 版本**
v2.2.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
横向堆叠图标签显示时，有重叠现象，影响观感！

**Bug 重现步骤(有截图更好)**
<img width="886" alt="image" src="https://github.com/dataease/dataease/assets/45967454/7863a4bc-0646-4f0a-9e3c-c7480041e992">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们讨论一下看如何处理；

**Comment by maninhill** [comment]
6个月内无更新，关闭。
