### ISSUE TITLE
[Feature] 横向堆叠图调整图形显示比例

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#7821]
DataEase 版本:
v2.2.0

**请描述您的需求或者改进建议.**
<img width="876" alt="image" src="https://github.com/dataease/dataease/assets/45967454/70068bdc-6a32-4469-85d7-7692f6c149a0">
现在的图形长短可能是根据数值比例来的，那就存在一种情况，如果数值之间差异过大，比如1000和1，那1对应的图形颜色就显示不出来了。能不能为了考虑图形展示效果，适当的提升1对应的图形大小，从视觉上达到可见的效果。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，如您描述，图形的长短是根据数值比例展示的，数字较小也是显示颜色的，由于太小，所以不太容易看到。如果单独提升某一个数字的图形大小，查阅报表时会引起误解，因此我们还是建议保持现状。
