### ISSUE TITLE
[Bug]默认仪表板取消默认的时候，提示的是删除仪表板，而不是取消默认

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#7822]
**DataEase 版本**

v.18.14
**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**

版本 120.0.6099.225（正式版本） （64 位）
**Bug 描述**
默认仪表板取消默认的时候，提示的是删除仪表板，而不是取消默认。给用户一种错觉要删除一张仪表板，而不是进行默认缺陷
![image](https://github.com/dataease/dataease/assets/127368807/d5edc05f-00ab-4694-8364-d61db6f363ab)

**Comment by greenyhsj** [comment]
![image](https://github.com/dataease/dataease/assets/127368807/77fd4438-f839-4838-b3b1-813971a4a060)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下此处提示；

**Comment by maninhill** [comment]
v1.18.5 已修复。
