### ISSUE TITLE
[Bug]查看分享时报sql错误

### ISSUE THREAD

**Issue by pickleqin** [dataease/dataease#7825]
**DataEase 版本**

1.18.14
**运行方式(安装包运行 or 源码运行 ?)**

安装包运行
**浏览器版本**

**Bug 描述**
分享仪表盘后登录被分享的账号查看分享的仪表板报sql查询错误。实际查看后为sql预计查询列不在分组列中。

**Bug 重现步骤(有截图更好)**
1.管理员分享一个仪表板
2.登录被分享用户
3.查看分享
<img width="1966" alt="image" src="https://github.com/dataease/dataease/assets/9959615/421191e7-264e-49cf-b5ab-68a459df42b3">

<img width="2423" alt="image" src="https://github.com/dataease/dataease/assets/9959615/ca0d68dc-777a-405c-8cc3-c6278ff34f44">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你的问题方便说一下具体的复现流程吗？

**Comment by BBchicken-9527** [comment]
你好现在问题是否有所解决呢？如果这个问题还在困扰你，或者你可以尝试升级，之前验证你问题的时候是在中间版本进行的；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
