### ISSUE TITLE
[Bug]】【仪表板】CK 数据源数据展示缓慢问题

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#7827]
**DataEase 版本**
1.18.14 & 2.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
DataEase 展示数据会慢与正常数据库查询，还请帮忙看看能不能优化。
附：clickhouse 查出来的聚合数据有 28000   原始数据就比较大了；
CK 版本：23.5.3.24

**Bug 重现步骤(有截图更好)**
1.数据库查询：

https://github.com/dataease/dataease/assets/24768910/614a6f57-630f-4616-a00f-823a2cc8db58

2.数据集查询：

https://github.com/dataease/dataease/assets/24768910/bf22ce0d-89af-47c2-8633-c55b20fab0e2

3.仪表板查询：
v1：echarts 的组合图和 antv 的汇总表

https://github.com/dataease/dataease/assets/24768910/faac573e-7ed7-465a-aadd-3542172db2f9

v2：汇总表

https://github.com/dataease/dataease/assets/24768910/5da0cd19-e8c3-4578-b8ad-6decf16218d5

**Comment by BBchicken-9527** [comment]
感谢反馈，我们讨论一下；

**Comment by maninhill** [comment]
6个月内无更新，关闭。
