### ISSUE TITLE
[Question]时间日期组件无效！！！！

### ISSUE THREAD

**Issue by niexiaohu123** [dataease/dataease#785]
**请描述您的问题.**
两种时间日期格式 对应 日期组件过滤筛选都不生效 。 第一种：2021-09-05 00:00:00   第二种：2021-09-05

**Comment by yayanpei** [comment]
非常感谢您的反馈，我们尽快验证并修复。

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 版本已修复
