### ISSUE TITLE
[Bug]连接mongobi数据源，使用新创建的集合创建数据集会报sql错误

### ISSUE THREAD

**Issue by JNing5473452** [dataease/dataease#7851]
**DataEase 版本**
v2版本

**运行方式(安装包运行 or 源码运行 ?)**
两种方式都不行

**浏览器版本**

![图片](https://github.com/dataease/dataease/assets/37338840/b13c4c9b-42a8-4e11-9c9b-2ac5750b5fd7)

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.使用mongobi方式创建数据源，创建成功
2.在MongoDB中新建一个集合并插入数据
3.创建数据集，选择刚刚创建的mongo数据源
4.能拉取到刚刚新创建的集合
![图片](https://github.com/dataease/dataease/assets/37338840/7f63faa1-9760-4df7-a6a5-419a07626624)
5.将这个集合拖动到右侧进行数据集创建，报错
![图片](https://github.com/dataease/dataease/assets/37338840/fc6045b5-600d-42c4-a2b1-b00e1695c4b9)
日志信息如下：
![图片](https://github.com/dataease/dataease/assets/37338840/5485ee59-d736-4eb6-affc-e182136a598e)
6.拖动连接数据源之前的集合不会报错
![图片](https://github.com/dataease/dataease/assets/37338840/5a58df86-e116-460d-ad43-2d233f05ee6f)

**Comment by BBchicken-9527** [comment]
感谢反馈，方便透露一下表结构吗？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
