### ISSUE TITLE
2.4支持tab的嵌套功能[Feature]

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#7852]
DataEase 版本:  v2.4

**请描述您的需求或者改进建议.**
tab能支持嵌套，我们有多个tab相互嵌套的场景。目前tab不支持嵌套.

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，预计在v2.4或者v2.5支持。

**Comment by xuwei-fit2cloud** [comment]
经讨论，暂时没有支持计划。
