### ISSUE TITLE
[Feature]数据源列表指定表可隐藏

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#7856]
DataEase 版本:
V2

**请描述您的需求或者改进建议.**
![2001706240119_ pic](https://github.com/dataease/dataease/assets/101089844/dfc55b53-f9e9-43dc-ac75-ad24cb0084cf)
![2021706240512_ pic](https://github.com/dataease/dataease/assets/101089844/5ad3de9f-df35-44e2-9167-4bc49648cb81)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
由于DataEase并不会保存数据源表记录，对于数据源表的实际变化情况很可能会不及时，导致出现设置的不一致性，所以我们没有相关的支持计划。
