### ISSUE TITLE
[Bug]【数据源】Kerberos 认证方式的 hive 数据源对接报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#7858]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
Kerberos 认证方式的 hive 数据源对接报错。（hive 版本 2.3.3）
注意：驱动管理上传驱动未解决该问题，重启服务等操作未解决问题，当前未排查出问题，还请研发协助排查！

**Bug 重现步骤(有截图更好)**
1.keytab 生成指令：
![image](https://github.com/dataease/dataease/assets/24768910/38bfd5d8-dfab-46cf-af14-0c2a26cc1781)

2.数据源配置
![image](https://github.com/dataease/dataease/assets/24768910/2fc99303-498b-4ceb-b014-df142c047cab)
![image](https://github.com/dataease/dataease/assets/24768910/21dca767-817a-4d00-b40a-a49b7c3d5eac)

3.校验报错
![image](https://github.com/dataease/dataease/assets/24768910/25fe3ec6-4fd6-425a-ac3d-068c9adb6b6f)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快处理；
