### ISSUE TITLE
[Bug] Tab 组件内的过滤组件没法控制 Tab 组件外的视图

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7884]
**DataEase 版本**
v1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
Tab 组件内的过滤组件没法控制 Tab 组件外的视图

**Bug 重现步骤(有截图更好)**

**Comment by BBchicken-9527** [comment]
感谢反馈，因为仪表板包含选项卡组件，所以外部的过滤组件可以过滤选项卡内部图表，但选项卡无法包含仪表板所以选项卡内部的过滤组件是无法过滤到外部的图表的；
