### ISSUE TITLE
[Feature] 数据库连接支持加密ca证书添加

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#7907]
DataEase 版本:
v1.18

**请描述您的需求或者改进建议.**

数据库连接支持加密ca证书，目前证书无法添加，只能支持账号密码的方式

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先调研一下。

**Comment by yayanpei-fit2cloud** [comment]
需求我们已放进需求池中，近期暂时不考虑支持，等有更多类似的需求后，我们再做进一步的规划，再次感谢您对项目的关注和支持。
