### ISSUE TITLE
[Feature] antv 组合图添加图例相关配置

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#7913]
DataEase 版本:
v1.18.14

**请描述您的需求或者改进建议.**
<img width="1207" alt="image" src="https://github.com/dataease/dataease/assets/45852479/4d418bcb-2bd7-43d0-a34c-e2178343938d">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，组合图图库目前对图例支持不太好，只显示部分图例，因此目前暂时没有计划放出来。
