### ISSUE TITLE
视图自定义计算字段计算有误

### ISSUE THREAD

**Issue by Luckyu920** [dataease/dataease#7918]
使用视图自定义计算字段计算，添加了一个MAX函数来计算最大值，但是与汇总方式中的最大值不一致；同样的，MIN函数也会出错。

![image](https://github.com/dataease/dataease/assets/46528689/392da99e-62f0-400f-b643-12f02214e03e)

![image](https://github.com/dataease/dataease/assets/46528689/adf1ac35-cdd4-4b24-a4de-9ca66dd500ee)

其实我的需求是，**能否在一个图/表中，同时显示一个指标的三值（即，最大值、平均值以及最小值）**，这样就不用再额外新增计算字段了。

我目前是用excel表格的，是一份成绩表，包含学号、姓名、语数英各科目的成绩。不知道是否是我使用的问题。有缺考的学生，试过填“缺考”，现在是直接空着，但是通过聚合函数计算出来的最大、最小值都不准确，反而平均值又是准确的。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我这边造了数据进行测试，最大值的计算是准确的，建议您再检查一下，或者方便的话把数据微信（微信号：18317092178）给我，我这边帮忙看看.
<img width="852" alt="image" src="https://github.com/dataease/dataease/assets/84168063/ec4f85bb-41c7-48b0-b586-9e8a50d2d899">

**Comment by Luckyu920** [comment]
感谢回复。是的，我一开始也单独用了测试数据来计算，也发现是正确的。我先试试删除其他成绩，减少学生数量试一下。稍后我再添加你吧

**Comment by Luckyu920** [comment]
我看到你的维度是学号，也就是【个人】，这样的话确实没错。我的维度是班级，即我想统计每班的某科成绩的最高分、最低分、以及平均分，是否是数据出现的先后顺序会导致计算错误呢？

**Comment by yayanpei-fit2cloud** [comment]
正如微信沟通，问题已排查到并解决，再次感谢您对项目的关注和支持。
