### ISSUE TITLE
[Feature]表格滚动的时候希望可以支持到能循环滚动，目前是到底之后直接从第一个开始了。

### ISSUE THREAD

**Issue by zqj50** [dataease/dataease#7930]
DataEase 版本:
v1.18.14

**请描述您的需求或者改进建议.**
表格滚动的时候希望可以支持到能循环滚动，目前是到底之后直接从第一个开始了。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前的滚动规则：滚动到最后一行后，继续从上到下开启下一次循环滚动。您这边是建议滚动到最后一行后，继续从底部往上滚动是吗？暂时没有计划修改滚动规则，我们先加入需求池中，等累计更多类似需求后再做下一步的规划。

**Comment by zqj50** [comment]
> 感谢您的反馈，目前的滚动规则：滚动到最后一行后，继续从上到下开启下一次循环滚动。您这边是建议滚动到最后一行后，继续从底部往上滚动是吗？暂时没有计划修改滚动规则，我们先加入需求池中，等累计更多类似需求后再做下一步的规划。

我的意思是到底后，最后一行接着第一行进行滚动。

**Comment by zqj50** [comment]
> 感谢您的反馈，目前的滚动规则：滚动到最后一行后，继续从上到下开启下一次循环滚动。您这边是建议滚动到最后一行后，继续从底部往上滚动是吗？暂时没有计划修改滚动规则，我们先加入需求池中，等累计更多类似需求后再做下一步的规划。

就是循环滚动

**Comment by xuwei-fit2cloud** [comment]
我们先调研一下是否能支持。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，目前暂时还无法支持。
