### ISSUE TITLE
[Feature]明细表汇总表可以隐藏字段

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#7937]
DataEase 版本:
v1.18.14

表格视图添加到维度框，希望可以选择隐藏某字段的显示；目的是需要用到这个字段的功能，只是不显示这个字段内容。
场景：明细表中有 “会场”、“URL” 两个字段，在做视图跳转时，点击“会场”的数据，设置跳转到 “URL“ 对应的网址，但在视图中不希望显示”URL“内容。

![图片](https://github.com/dataease/dataease/assets/48307752/f03c964c-6e2d-488c-afda-ea77b9a18acb)

![图片](https://github.com/dataease/dataease/assets/48307752/31f6a6d8-290d-401c-ade9-f39c69acb781)

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下优化方案。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
