### ISSUE TITLE
[Bug] DataEase v1 ，AntV 雷达图标签显示被遮挡。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#7951]
**DataEase 版本**
v1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 121.0.6167.85（正式版本） (arm64)

**Bug 描述**
DataEase v1 ，AntV 雷达图标签显示被遮挡，最上方被盖住。

**Bug 重现步骤(有截图更好)**
如下所示，雷达图最上面的标签被遮挡，且无法调节使其正常显示：
![image](https://github.com/dataease/dataease/assets/30063018/354e00b0-6c25-43d5-b71a-daa6f9ac957d)

**Comment by BBchicken-9527** [comment]
感谢反馈，可以对样式中的大小进行设置；
![image](https://github.com/dataease/dataease/assets/84372766/0f3ba9ad-2cf6-4745-b460-2db272434375)
