### ISSUE TITLE
[Feature] 关于卸载与备份的建议

### ISSUE THREAD

**Issue by Coder-Tang** [dataease/dataease#7955]
DataEase 版本:
v 1.18.8

**请描述您的需求或者改进建议.**

场景：
执行卸载脚本时，会把数据目录/opt/dataease删除，脚本执行没有提示备份数据目录

方案：
1、卸载脚本执行时，让用户确认是否备份数据目录
2、dectl加个backup的功能，一键备份，方便用户操作

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在下个版本中增加一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
