### ISSUE TITLE
[Feature]希望DE能支持配置SSL，SSL直接做到功能中，不想再单独配置nginx

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#7957]
DataEase 版本:
1.18.14

**请描述您的需求或者改进建议.**
希望DE能支持配置SSL，SSL直接做到功能中，不想再单独配置nginx

**Comment by xuwei-fit2cloud** [comment]
DataEase并没有相关的开发计划，你可以试试我们的[1panel](https://1panel.cn/)，支持一键配置nginx和证书。
