### ISSUE TITLE
[Bug]2.x版本sql语句或计算字段使用REGEXP_EXTRACT、SPLIT函数时报错

### ISSUE THREAD

**Issue by vilian00** [dataease/dataease#7963]
**DataEase 版本**
2.3.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome版本 121.0.6167.86（正式版本）

**Bug 描述**
2.x版本sql语句或计算字段使用REGEXP_EXTRACT、SPLIT函数时报错

**Bug 重现步骤(有截图更好)**
1. 新建数据集页面，SQL的select语句中包含SPLIT([path],'a')  or REGEXP_EXTRACT( [path] , 'a|b')，点击运行时报错
2. 新建计算字段，字段表达式输入 SPLIT([path],'a')  or REGEXP_EXTRACT( [path] , 'a|b')，点击刷新数据报错
![image](https://github.com/dataease/dataease/assets/42952901/06b72b4e-3219-4ded-a319-e2998b3363ec)

**Comment by BBchicken-9527** [comment]
感谢反馈，为了规范SQL数据集的sql的编辑，所以使用了calcite进行连接，目前split函数calcite是不支持的；

**Comment by vilian00** [comment]
https://calcite.apache.org/docs/reference.html 文档上有split函数呀？ REGEXP_EXTRACT函数文档也有，但也是一样报错，请一起看一下。
![image](https://github.com/dataease/dataease/assets/42952901/30450822-7beb-41e9-b50d-fb1872e24564)
