### ISSUE TITLE
[Bug]编辑SQL数据集，参数设置页面文本显示错乱

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#7968]
**DataEase 版本**
v2.2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge版本 121.0.2277.83 (正式版本) (64 位)

**Bug 描述**
编辑SQL数据集时，点击页面右上2角“参数设置”，打开页面后兼容性问题，文本显示错乱

**Bug 重现步骤(有截图更好)**
1.
![1706789052682](https://github.com/dataease/dataease/assets/77324661/af91a3c8-e348-45b0-b115-96d6e42190a1)

2.
![1706789052666](https://github.com/dataease/dataease/assets/77324661/4f630dc2-2fd0-4093-8c53-9c35baca95bd)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行优化；
