### ISSUE TITLE
AntV的雷达图中样式里面的标签位置设置不生效

### ISSUE THREAD

**Issue by Luckyu920** [dataease/dataease#7969]
**DataEase 1.18.14**

**运行方式(1panel docker运行 ?)**

**Edge12-**

**AntV的雷达图数据标签位置设置不生效**

**Bug 重现步骤(有截图更好)**
1.AntV的雷达图中样式里面的**标签位置**设置不生效
2.换成ECharts后可以正常更改数据标签的位置
3.

**Comment by Luckyu920** [comment]
设置为 上：

![image](https://github.com/dataease/dataease/assets/46528689/702a6911-943c-45a4-b7cf-e41e84832bff)

设置为 中：

![image](https://github.com/dataease/dataease/assets/46528689/1c2f7c8f-124c-425c-ae89-370cb6a1832a)

设置为 下：

![image](https://github.com/dataease/dataease/assets/46528689/a7768a42-1465-4e87-9828-822d9a80ce93)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，antv位置的调整与其它事件冲突，因此调整位置是不生效的。这里本身是一个数据点，位置调整为上中下差别不大，我们会默认标签的位置，并将标签位置的配置项去掉。

**Comment by Luckyu920** [comment]
道理是这个道理，但是Echart中的雷达图是可以实现的。或者是否可以稍微错开一点，现在刚好被遮住了一点

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
