### ISSUE TITLE
在地图中或其他地方支持多维度跳转和跳转字段隐藏URL

### ISSUE THREAD

**Issue by jmtally1** [dataease/dataease#7973]
DataEase 版本:
v2.3

**请描述您的需求或者改进建议.**
1.在官方案例地图中，跳转的方法只有一个，点击地图跳转百度查询人口。如果可以支持多维度跳转，例如跳转人口，用电量，粮食产量，让开发者自行设置连接和参数会适合更多场景。
2.前面有ISSUE提过，官方提供的多级连接是通过视图设置URL点解跳转的，实际业务中，显示地址不是一个好主意，更希望可以点击行直接跳转，可以通过定义事件比如click_row这种来触发。

**Comment by xuwei-fit2cloud** [comment]
我们尝试支持一下字段隐藏功能。
