### ISSUE TITLE
[Feature]antV明细表表头排序标识能否支持隐藏

### ISSUE THREAD

**Issue by cy414933307** [dataease/dataease#7978]
DataEase 版本:1.18.15

https://github.com/dataease/dataease/issues/6754
这个表头排序标识能否支持隐藏，多出来这个标识后，原本的表头文字因为空间有限，显示不全了

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们后期优化一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
