### ISSUE TITLE
[Bug] v1版本 sql数据集传参 用in传参报错

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#7980]
安装包安装
 sql用等于之后 筛选无问题
![4b00aef13c33034967bfa3502d42b47e](https://github.com/dataease/dataease/assets/141667200/49a05b7d-696d-45a0-976c-cd7c661ba48b)
![40f4a8c7c0f29b5bb27767095648f9dd](https://github.com/dataease/dataease/assets/141667200/83bbbc9d-3288-41b0-890a-91d504341a06)

sql用in筛选 数据集没问题 但是加了文本下拉框传参之后 出现问题  和上面的 只差一个等于和in的区别
![aeed64d41257924071d94f7adb0be53c](https://github.com/dataease/dataease/assets/141667200/70d52b45-6382-4862-904c-3ec0297000b2)
![472fea9f38b4414398dd784fe099a137](https://github.com/dataease/dataease/assets/141667200/5f2c2d13-b24b-479c-ac9e-789d0e6d109f)

mysql和doris源 都有这个问题

**Comment by wolf-kingx** [comment]
v1.18.15版本

**Comment by BBchicken-9527** [comment]
感谢反馈，受累看看将过滤组件改为多选呢？

**Comment by wolf-kingx** [comment]
多选和in一起用 正常来说应该是没问题的 但是有这种报错说不过滤字段类型不合法 之前18.13还可以用 升级到18.15就不可以了
<img width="618" alt="a45c16658b596988c0a19d4344d37243" src="https://github.com/dataease/dataease/assets/141667200/97f7b5e7-abe3-46da-a1ae-d84a49c8ab15">

**Comment by hw872715125** [comment]
我也遇到了这个问题，更新到1.18.15后，许多sql语句都不好使了，查询报错。可能是我提的这个issue：https://github.com/dataease/dataease/issues/7485
升级后没有处理好

**Comment by wolf-kingx** [comment]
我们倒是没有用炸裂函数 之前13的时候文本下拉框过滤还没有问题 升级之后就报的where后面过滤的类型不合法 你们也是一样的报错吗？

> 我也遇到了这个问题，更新到1.18.15后，许多sql语句都不好使了，查询报错。可能是我提的这个issue：#7485 升级后没有处理好

**Comment by BBchicken-9527** [comment]
> 我们倒是没有用炸裂函数 之前13的时候文本下拉框过滤还没有问题 升级之后就报的where后面过滤的类型不合法 你们也是一样的报错吗？
> 
> > 我也遇到了这个问题，更新到1.18.15后，许多sql语句都不好使了，查询报错。可能是我提的这个issue：#7485 升级后没有处理好

感谢反馈，这次对in的处理是做了一些优化的，因为发现在部分情况下in在创建图表不添加参数会无法显示数据，因为显示数据需要in后面的参数内容，但过滤组件的内容又需要通过in来去筛选显示，你看一下如果你用in的情况下用括号将参数包裹呢（${}）我在测试环境看是没问题的；

**Comment by BBchicken-9527** [comment]
> 我也遇到了这个问题，更新到1.18.15后，许多sql语句都不好使了，查询报错。可能是我提的这个issue：#7485 升级后没有处理好

是这里我们这次in在特定的情况下可能会出现死锁的问题，显示图表需要in中的参数，但过滤组件又需要数据表中的反显的数据，加上（）应该就没问题了；
![image](https://github.com/dataease/dataease/assets/84372766/c5d11bb8-a0b7-4b64-98f2-e70bb72d3bdb)

**Comment by wolf-kingx** [comment]
> > 我也遇到了这个问题，更新到1.18.15后，许多sql语句都不好使了，查询报错。可能是我提的这个issue：#7485 升级后没有处理好
> 
> 是这里我们这次in在特定的情况下可能会出现死锁的问题，显示图表需要in中的参数，但过滤组件又需要数据表中的反显的数据，加上（）应该就没问题了； ![image](https://private-user-images.githubusercontent.com/84372766/302086668-c5d11bb8-a0b7-4b64-98f2-e70bb72d3bdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzUwNTMsIm5iZiI6MTcwNzAzNDc1MywicGF0aCI6Ii84NDM3Mjc2Ni8zMDIwODY2NjgtYzVkMTFiYjgtYTBiNy00YjY0LTk4ZjItZTcwYmI3MmQzYmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA4MTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ZjEyYWYyOWI2MTgxMzg4YWQ5ZTg4ZDk4OTNkMThlNGUzZjcyNzVkN2I2MDRkNzZjZDkzYjY3MTZlMDE0ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nzEcjTPanLh50QFH92QAYpA25zOROxb4J80-WNM0sLQ)

换成这个试了一下 还是不行 报错换了
![a4cd2bc0c1f5455a6c61f67bd59de74](https://github.com/dataease/dataease/assets/141667200/a649955c-6116-4c9b-91ae-da8d0429b38f)
<img width="830" alt="d764f6b2c4ff459d05806a21babe19a0" src="https://github.com/dataease/dataease/assets/141667200/76b5d093-090e-4d6d-a8a3-43d9090bfe33">

**Comment by wolf-kingx** [comment]
> > 我也遇到了这个问题，更新到1.18.15后，许多sql语句都不好使了，查询报错。可能是我提的这个issue：#7485 升级后没有处理好
> 
> 是这里我们这次in在特定的情况下可能会出现死锁的问题，显示图表需要in中的参数，但过滤组件又需要数据表中的反显的数据，加上（）应该就没问题了； ![image](https://private-user-images.githubusercontent.com/84372766/302086668-c5d11bb8-a0b7-4b64-98f2-e70bb72d3bdb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzUwNTMsIm5iZiI6MTcwNzAzNDc1MywicGF0aCI6Ii84NDM3Mjc2Ni8zMDIwODY2NjgtYzVkMTFiYjgtYTBiNy00YjY0LTk4ZjItZTcwYmI3MmQzYmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDA4MTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ZjEyYWYyOWI2MTgxMzg4YWQ5ZTg4ZDk4OTNkMThlNGUzZjcyNzVkN2I2MDRkNzZjZDkzYjY3MTZlMDE0ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nzEcjTPanLh50QFH92QAYpA25zOROxb4J80-WNM0sLQ)

只加括号(${id}) 这样 也不行  报错和最开始的不合法类型那个一样

**Comment by wolf-kingx** [comment]
如果是（"${id}"） 页面报错
 
![c8eb53226b363899b330b9aa6ce60a3](https://github.com/dataease/dataease/assets/141667200/3b405829-188e-40a6-b1b0-aca51d803bef)

**Comment by BBchicken-9527** [comment]
你这个用的数据源是.....CK？

**Comment by wolf-kingx** [comment]
> 你这个用的数据源是.....CK？

是的

**Comment by BBchicken-9527** [comment]
确实有些问题，我们将在下个版本进行修复；
