### ISSUE TITLE
[Bug] calcite-core only version 1.35.0 1.36.0 not have 1.35.3 

### ISSUE THREAD

**Issue by andotorg** [dataease/dataease#7982]
**DataEase 版本**
dev-v2
2.3

**运行方式(安装包运行 or 源码运行 ?)**
source

**浏览器版本**

**Bug 描述**
not jar version

**Bug 重现步骤(有截图更好)**
1.  
![image](https://github.com/dataease/dataease/assets/25116294/ccad039c-56cf-4a58-bfd3-5a9171941797)
![image](https://github.com/dataease/dataease/assets/25116294/11837174-181f-4c7c-8a54-67b0f591f0d9)

2. 
3.

**Comment by maninhill** [comment]
你可以改成：v1.35.0
