### ISSUE TITLE
[Bug]Sql中特殊字符无法使用

### ISSUE THREAD

**Issue by f2m4** [dataease/dataease#7983]
**DataEase 版本**
v1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge

**Bug 描述**
数据源 Sqlserver 2014 
字段名称中含有  |  符号. 导致无法获取数据.

**Bug 重现步骤(有截图更好)**
1. 执行正常
![image](https://github.com/dataease/dataease/assets/13922622/824149e1-6236-4d7a-adb2-cb5f821ebfdc)

2. 无法预览.提示错误
![image](https://github.com/dataease/dataease/assets/13922622/6ce2dfac-7fa7-4ca0-bd66-7c04a93c1d5f)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，因为升级底层依赖之前是不支持这种操作形式的，及[]的方式，我们讨论一下看看是否可以有效的达到你的预期；

**Comment by tjlygdx** [comment]
![image](https://github.com/dataease/dataease/assets/12710377/3c173655-887c-4978-926e-793dacfa657e)
![image](https://github.com/dataease/dataease/assets/12710377/97566b2f-e489-42da-b0fe-5c026a6e816f)
没有复现

**Comment by xuwei-fit2cloud** [comment]
由于长时间未有反馈，暂时关闭该issue，如有问题，咱们在继续沟通。
