### ISSUE TITLE
[Bug]SQLserver 2014  驱动版本号12 添加到 default中

### ISSUE THREAD

**Issue by f2m4** [dataease/dataease#7984]
**DataEase 版本**
v1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
edge

**Bug 描述**
SQLserver 2014 的驱动. 麻烦添加上12版本

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/13922622/7ecb0d31-4828-43ec-a7c4-83d3e6346de6)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下这里补课编辑的问题；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
