### ISSUE TITLE
[Feature]过滤器支持时间类型字段设置动态时间参数

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#7987]
DataEase 版本:

1.18.14
**请描述您的需求或者改进建议.**
希望可以在过滤器中给时间类型字段设置动态时间，类似时间过滤组件中的动态时间功能。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先加到需求池中，待后期支持。

**Comment by xuwei-fit2cloud** [comment]
近期暂不考虑支持，暂时关闭。
