### ISSUE TITLE
[Feature]设置了联动后希望可以覆盖过滤条件

### ISSUE THREAD

**Issue by hw872715125** [dataease/dataease#7988]
DataEase 版本:
v1.18.14

**请描述您的需求或者改进建议.**
有多个视图，用1，2，3表示，视图1和2，3设置了联动效果，2，3是依赖视图1点击联动后查出对应的数据，给视图2和3设置了默认过滤条件，比如code='app'，设置的视图1和2，3的联动字段也是code。希望在联动查询时，可以覆盖原有的默认值。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，但由于过滤组件影响的范围默认是整个仪表板，由联动去覆盖过滤组件的默认值，可能在很多情况下会引起其他非联动组件的一起变化，我们目前没有该支持的计划。
