### ISSUE TITLE
[Bug]v1.18.15 CK数据源 数字下拉框 不能绑定参数 

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#7994]
创建两个数据集 一个用in传参 另一个从库中查全部 用来当作筛选条件
<img width="1269" alt="1a09c2d150dded63c87af3b5f2d88696" src="https://github.com/dataease/dataease/assets/141667200/a4690946-4d15-4ebe-8aa5-9c84b178280b">
<img width="709" alt="4eec72e6203be9e1b6aacbfde1863d0b" src="https://github.com/dataease/dataease/assets/141667200/130aeaef-2296-40ee-8bdd-9c2de1aff6f5">

用in传参的数据集建了一个视图
<img width="1163" alt="d4c43daf123fee9883fe583490ad2aaf" src="https://github.com/dataease/dataease/assets/141667200/92730fbe-ff2c-4d74-9bfa-fbb30b04f915">

用数字下拉框 使用另一个数据集传参 绑定参数 但是绑定参数的列表中没有任何参数显示
<img width="1250" alt="da9b4ea01d68ffcc4d18f57923f8ed9a" src="https://github.com/dataease/dataease/assets/141667200/09a5f1b0-c84f-41bb-a98f-18f50e220516">

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你的参数设置字段类型是否改为了数值？

**Comment by wolf-kingx** [comment]
> 感谢反馈，请问你的参数设置字段类型是否改为了数值？
没有改 原始的类型就是数值类型

**Comment by BBchicken-9527** [comment]
不是的，你如果想用数值类型进行参数化的话需要在参数化设置中将文本改为数值；老哥是那个群的方便的话可以加你一个微信，我看你提了挺多的问题，还有一些其他的问题可以和你问问你具体的流程；

**Comment by wolf-kingx** [comment]
> 不是的，你如果想用数值类型进行参数化的话需要在参数化设置中将文本改为数值；老哥是那个群的方便的话可以加你一个微信，我看你提了挺多的问题，还有一些其他的问题可以和你问问你具体的流程；

15698628928

**Comment by maninhill** [comment]
长时间未反馈，请升级到最新版本。我们先关闭，如还有问题，请再重新打开。
