### ISSUE TITLE
[Bug]缓存导致数据源驱动不验证版本号的 bug

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#7996]
**DataEase 版本**
1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome、firefox

**Bug 描述**
1.18.12 版本升级到 1.18.15，浏览器没有清理缓存的情况下；
添加数据源驱动，应该会有“支持版本”的必填项：
![图片](https://github.com/dataease/dataease/assets/48307752/364ce2e8-0dd6-4542-a338-02d11b02598c)

由于没有清理缓存，没有出现该填写框，可以正常保存驱动配置，也可以正常使用该驱动配置到数据源。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们排查一下。

**Comment by xuwei-fit2cloud** [comment]
v1.18.12版本有点问题，升级到v1.18.15版本会有问题。
在v1.18.15版本中，我们已经对缓存问题做了处理。
