### ISSUE TITLE
[Feature]隐藏选项卡标签显示，增加边框颜色设置支持

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#7998]
**DataEase 版本**
v1.18.12

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
制作tab页轮播效果时，tab页上方有明显白边，影响美观！！！
建议：能否去掉白边、标签显示？或者让用户自定义显示！

**Bug 重现步骤(有截图更好)**
<img width="1475" alt="image" src="https://github.com/dataease/dataease/assets/45967454/0c3971ec-9f37-444d-9b4b-a6a2e0676c6f">

**Comment by xuwei-fit2cloud** [comment]
您可以升级到v1.18.13及以后版本，是支持隐藏标题，以及一些其他样式设置的。
https://dataease.io/docs/v1/release_notes/v1.18.13/#33

当前v1系列最新版本为 v1.18.15。
