### ISSUE TITLE
[Feature] 支持配置VITE_API_BASEPATH

### ISSUE THREAD

**Issue by kassiansun** [dataease/dataease#7999]
DataEase 版本: 2.0

**请描述您的需求或者改进建议.**

DataEase可能部署在子路径下（比如`/analysis/dataease`），现在前端会固定请求`/de2api`这个路径（正确的请求路径应该跟随DataEase的路径 `/analysis/de2api`），无法在后端配置，希望能提供一个后端部署选项来修改这个路径。

类似Kibana的`server.basePath`选项：https://www.elastic.co/guide/en/kibana/current/settings.html

**Comment by xuwei-fit2cloud** [comment]
下个版本v2.4.0会支持。
