### ISSUE TITLE
数据量大的情况下，重新定义表字段后，报错

### ISSUE THREAD

**Issue by plateauandsp** [dataease/dataease#8]
数据量大的情况下（3万），重新定义表字段后，报错，刷新又可以。（不稳定）

![image](https://user-images.githubusercontent.com/30932762/123370397-39781c80-d5b2-11eb-8a0b-b4555c66e122.png)

**Comment by xuwei-fit2cloud** [comment]
v1.4 版本已经支持自定义超时时间。
