### ISSUE TITLE
[Bug]添加表-添加数据库表，添加完中文显示乱码

### ISSUE THREAD

**Issue by xulinde** [dataease/dataease#80]
**DataEase 版本**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/64065190/123576835-3f197080-d805-11eb-9cd6-8af0f855e5d8.png)

**Comment by xuwei-fit2cloud** [comment]
问题依旧存在

**Comment by xuwei-fit2cloud** [comment]
v1.11.3版本，oracle编码已支持设置
