### ISSUE TITLE
[Feature]数据集可以根据数据来源表名搜索

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#8001]
DataEase 版本:

**请描述您的需求或者改进建议.**
<img width="483" alt="image" src="https://github.com/dataease/dataease/assets/101089844/bf7e1af9-3333-4a1b-ada1-be9818bb5ff4">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个需求我们可能会更倾向于在血缘关系功能模块里增强支持，比如可以通过血缘关系列出所有相关资源，点击对应资源进入到资源的页面。
