### ISSUE TITLE
[Bug]【仪表板】仪表板导出图片或者 PDF 不全

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#8005]
**DataEase 版本**
1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
仪表板导出图片或者 PDF 不全
![image](https://github.com/dataease/dataease/assets/24768910/a82134ab-cece-469f-af27-fe13ff3cafc8)

建议：
仪表板导出图片或者 PDF 加一个「额外等待时间」设置，参考如下：

功能参考：定时报告
![302211754-3ecb7603-2a5c-477d-a9a7-241375e6bb21](https://github.com/dataease/dataease/assets/24768910/fffb0553-9322-4d6a-9f52-4707cc5c6507)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们在近期版本做一下相关优化。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
