### ISSUE TITLE
[Bug]富方本组件，文字进行超链接，设置为当前窗口打开后，仍然以新窗口方式打开，并未按设置实现。

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#8007]
**DataEase 版本**
1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
富方本组件，文字进行超链接，设置为当前窗口打开后，仍然以新窗口方式打开，并未按设置实现。

**Bug 重现步骤(有截图更好)**
1.
<img width="1155" alt="image" src="https://github.com/dataease/dataease/assets/101089844/c62c9fd4-48a0-416f-aaf8-0f506182094b">

2.打开后还是新标签
<img width="1222" alt="image" src="https://github.com/dataease/dataease/assets/101089844/e945281a-561b-4686-979c-10baf4076e30">

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，应该是原生组件的问题，我们也在积极的讨论解决的方案，我们会尽快修复；
