### ISSUE TITLE
[Question] 最新版本2.3.0 前端npm run dev报错 求帮助

### ISSUE THREAD

**Issue by chenhangMOB** [dataease/dataease#8012]
> dataease@0.0.0 dev F:\2024项目\DataEase-v2.3.0\core\core-frontend
> NODE_OPTIONS=--max_old_space_size=2048 vite --mode dev --host 0.0.0.0

'NODE_OPTIONS' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dataease@0.0.0 dev: `NODE_OPTIONS=--max_old_space_size=2048 vite --mode dev --host 0.0.0.0`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dataease@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\nodejs\node_cache\_logs\2024-02-06T02_23_18_168Z-debug.log

**node版本为12.18.0**

**Comment by XiaJunjie2020** [comment]
看上去您应该是windows开发环境，尝试先运行 npm install -g win-node-env ，然后再运行 npm run dev，如果还有问题，尝试升级node版本

**Comment by chenhangMOB** [comment]
还有一个问题 gitee上标签1.18.x和2.x有什么区别呢 感谢
