### ISSUE TITLE
[Feature]指标可以默认不展示

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#8014]
DataEase 版本:
V1

**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/101089844/9e480358-7e65-411f-9ecf-2b672b38ea7c)

![wecom-temp-33785-32b007f100b70babaa970b5387eda96d](https://github.com/dataease/dataease/assets/101089844/7d142385-7844-4308-b2a6-f6ff1a2874fb)

**Comment by xuwei-fit2cloud** [comment]
建议通过查询组件来处理，暂时没有对图例默认值的相关支持计划。
