### ISSUE TITLE
[Question]前端依赖问题

### ISSUE THREAD

**Issue by zxh666a** [dataease/dataease#8017]
请问 为什么npm 下载后，还是会报很多依赖没有，要一个一个安装。是我的操作哪里不对吗
而且目前有个 import { getEngine } from '@antv/g2/esm/core' 会报错，我安装g2包，也没有找到这个

**Comment by xuwei-fit2cloud** [comment]
可以尝试替换一下npm源。

**Comment by zxh666a** [comment]
> 可以尝试替换一下npm源。

谢谢 已解决
