### ISSUE TITLE
[Question]前端打包问题

### ISSUE THREAD

**Issue by zxh666a** [dataease/dataease#8018]
**请描述您的问题.**
import pkg from '../package.json' assert { type: "json" }
这段代码打包会报错，Unexpected identifier 请问如何解决呀

**Comment by xuwei-fit2cloud** [comment]
建议升级一下node的版本，我本地版本是 v16.14.2，没有遇到上述问题。

**Comment by zxh666a** [comment]
> 建议升级一下node的版本，我本地版本是 v16.14.2，没有遇到上述问题。

我升级了，已经解决。但打包我看到需要../dist/panel.html。但我并没有看到dist文件夹，但是在根目录有panel.html。我是需要自己创建dist文件夹吗
