### ISSUE TITLE
[Bug]sql数据集子查询中使用union，同时使用参数的情况下执行异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#8022]
**DataEase 版本**
1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
sql数据集子查询中使用union，同时使用参数的情况下执行异常
升级之前使用的是1.18.14版本，是没有这个问题的，升级之后出现了这个问题
<img width="1468" alt="image" src="https://github.com/dataease/dataease/assets/89771514/19c29819-c4a2-41ca-a5dc-c69840755d21">
<img width="1456" alt="image" src="https://github.com/dataease/dataease/assets/89771514/de2208e6-c1f8-4bae-a981-6e9dbda961e6">
<img width="1474" alt="image" src="https://github.com/dataease/dataease/assets/89771514/70c2f224-d2a9-4413-94b5-3ea7a5523910">
<img width="1439" alt="image" src="https://github.com/dataease/dataease/assets/89771514/e5efae57-7e9f-44fe-942b-1b71c91d0af6">

**Comment by ZhaoQian1222** [comment]
mysql数据源

**Comment by xuwei-fit2cloud** [comment]
我们先排查一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
