### ISSUE TITLE
[Question] 在拉取镜像出现502错误

### ISSUE THREAD

**Issue by Thexiaoyuqaq** [dataease/dataease#8026]
**请描述您的问题.**
root@Thexiaoyu:~# curl -sSL https://dataease.oss-cn-hangzhou.aliyuncs.com/quick_start.sh | bash
检测 gitee.com ... 1 ok
检测 gitee.com ... 2 ok
检测 gitee.com ... 3 ok
使用下载服务器 gitee.com
开始下载 DataEase v1.18.15 版本在线安装包
下载地址： https://gitee.com/fit2cloud-feizhiyun/DataEase/releases/download/v1.18.15/dataease-v1.18.15-online.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   174    0   174    0     0    452      0 --:--:-- --:--:-- --:--:--   453
100   255    0   255    0     0    440      0 --:--:-- --:--:-- --:--:--   440
100 12923  100 12923    0     0  15050      0 --:--:-- --:--:-- --:--:--  247k
Warning: Got more output options than URLs
dataease-v1.18.15-online/
dataease-v1.18.15-online/dataease/
dataease-v1.18.15-online/dataease/docker-compose-doris.yml
dataease-v1.18.15-online/dataease/docker-compose-kettle.yml
dataease-v1.18.15-online/dataease/templates/
dataease-v1.18.15-online/dataease/templates/.kettle/
dataease-v1.18.15-online/dataease/templates/.kettle/repositories.xml
dataease-v1.18.15-online/dataease/templates/fe.conf
dataease-v1.18.15-online/dataease/templates/mysql.env
dataease-v1.18.15-online/dataease/templates/be.conf
dataease-v1.18.15-online/dataease/templates/dataease.properties
dataease-v1.18.15-online/dataease/templates/my.cnf
dataease-v1.18.15-online/dataease/templates/version
dataease-v1.18.15-online/dataease/docker-compose-mysql.yml
dataease-v1.18.15-online/dataease/docker-compose.yml
dataease-v1.18.15-online/dataease/bin/
dataease-v1.18.15-online/dataease/bin/dataease/
dataease-v1.18.15-online/dataease/bin/dataease/dataease.service
dataease-v1.18.15-online/dataease/bin/doris/
dataease-v1.18.15-online/dataease/bin/doris/init.sql
dataease-v1.18.15-online/dataease/bin/mysql/
dataease-v1.18.15-online/dataease/bin/mysql/init.sql
dataease-v1.18.15-online/dataease/plugins/
dataease-v1.18.15-online/dataease/plugins/thirdpart/
dataease-v1.18.15-online/dataease/logs/
dataease-v1.18.15-online/dataease/logs/be/
dataease-v1.18.15-online/dataease/logs/README.md
dataease-v1.18.15-online/dataease/logs/fe/
dataease-v1.18.15-online/quick_start.sh
dataease-v1.18.15-online/install.sh
dataease-v1.18.15-online/install.conf
dataease-v1.18.15-online/README.md
dataease-v1.18.15-online/dectl
dataease-v1.18.15-online/.gitignore
dataease-v1.18.15-online/uninstall.sh

*******************************************************

 当前部署模式为 simple，如需切换模式，
 请修改 /opt/dataease/.env 中的 DE_ENGINE_MODE 变量后，
 重新执行 bash install.sh 即可

*******************************************************

======================= 开始安装 =======================
[DATAEASE Log]: [警告] DataEase 运行目录所在磁盘剩余空间不足 20G 可能无法正常启动! 
[DATAEASE Log]: 拷贝配置文件模板文件  -> /opt/dataease/conf 
[DATAEASE Log]: 根据安装配置参数调整配置文件 
time: Wed Feb  7 09:52:05 AM UTC 2024
[DATAEASE Log]: 检测到 Docker 已安装，跳过安装步骤 
[DATAEASE Log]: 启动 Docker  
[DATAEASE Log]: 检测到 Docker Compose 已安装，跳过安装步骤 
[DATAEASE Log]: 拉取镜像 
[+] Pulling 0/13
 ⠇ mysql 10 layers [⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                                                                                                                       5.8s 
   ⠇ 8e0176adc18c Retrying in 1 second                                                                                                                                                                                        4.7s 
   ⠇ 14e977b0f4b2 Retrying in 1 second                                                                                                                                                                                        4.7s 
   ⠇ a7b58dd6f78b Waiting                                                                                                                                                                                                     4.7s 
   ⠇ fba70cc872a5 Waiting                                                                                                                                                                                                     4.7s 
   ⠇ 5db2cc6eab8f Waiting                                                                                                                                                                                                     4.7s 
   ⠇ 081f41f573ba Waiting                                                                                                                                                                                                     4.7s 
   ⠇ 86bf2dc4ded9 Waiting                                                                                                                                                                                                     4.7s 
   ⠇ 47f08b0e916e Waiting                                                                                                                                                                                                     4.7s 
   ⠇ 850e29ae8eeb Waiting                                                                                                                                                                                                     4.7s 
   ⠇ 13517fe0d921 Waiting                                                                                                                                                                                                     4.7s 
 ⠇ dataease 1 layers [⠀]      0B/0B      Pulling                                                                                                                                                                              5.8s 
   ⠹ b790c763077d Waiting                                                                                                                                                                                                     5.2s 
error pulling image configuration: download failed after attempts=6: received unexpected HTTP status: 502 Bad Gateway
/root/dataease-v1.18.15-online
[DATAEASE Log]: 配置 dataease Service 
[DATAEASE Log]: 配置开机自启动 
install.sh: line 336: ((: 1vm: value too great for base (error token is "1vm")
[DATAEASE Log]: 停止服务进行升级... 

[DATAEASE Log]: 启动服务 
Job for dataease.service failed because the control process exited with error code.
See "systemctl status dataease.service" and "journalctl -xeu dataease.service" for details.
======================= 安装完成 =======================

请通过以下方式访问:
 URL: http://$LOCAL_IP:80
 用户名: admin
 初始密码: dataease
root@Thexiaoyu:~#

**Comment by xuwei-fit2cloud** [comment]
看着应该是在拉取镜像的时候出现了网络问题，您可以在机器上直接执行一下下面的命令，直接拉取镜像试试：
```bash
docker pull registry.cn-qingdao.aliyuncs.com/dataease/mysql:8.1.0
```

如果可以拉取的话，您可以重新执行一下安装脚本 bash install.sh。

**Comment by Thexiaoyuqaq** [comment]
> 看着应该是在拉取镜像的时候出现了网络问题，您可以在机器上直接执行一下下面的命令，直接拉取镜像试试：
> 
> ```shell
> docker pull registry.cn-qingdao.aliyuncs.com/dataease/mysql:8.1.0
> ```
> 
> 如果可以拉取的话，您可以重新执行一下安装脚本 bash install.sh。

Last login: Wed Feb  7 09:51:56 2024 from 127.0.0.1
thexiaoyu@Thexiaoyu:~$ su -
密码： 
root@Thexiaoyu:~# docker pull registry.cn-qingdao.aliyuncs.com/dataease/mysql:8.1.0
8.1.0: Pulling from dataease/mysql
8e0176adc18c: Retrying in 1 second 
14e977b0f4b2: Retrying in 1 second 
a7b58dd6f78b: Retrying in 1 second 
fba70cc872a5: Waiting 
5db2cc6eab8f: Waiting 
081f41f573ba: Waiting 
86bf2dc4ded9: Waiting 
47f08b0e916e: Waiting 
850e29ae8eeb: Waiting 
13517fe0d921: Waiting 
error pulling image configuration: download failed after attempts=6: received unexpected HTTP status: 502 Bad Gateway
root@Thexiaoyu:~#

**Comment by Thexiaoyuqaq** [comment]
对于拉取其他镜像，也许因走的docker.io 所以是正常的

**Comment by xuwei-fit2cloud** [comment]
嗯，那应该是网络可达性的问题，镜像本身是托管在aliyun的镜像服务上的，在正常情况下是可拉取的。
您可能得自己处理一下网络访问问题了。

**Comment by Thexiaoyuqaq** [comment]
我采取了：挂梯子，检查网络问题，切换宽带 方式，
依旧是此类问题，也许我需要一个其他的源

**Comment by maninhill** [comment]
建议使用离线安装包进行安装。
