### ISSUE TITLE
[Bug]v2版本 面积图 柱状图

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8032]
v2.3 安装包安装

之前使用没有这种问题 年前做的仪表板 今天打开 视图里面数据就乱了 刚开始我重新把两个表更新了一下 没问题了 但是在修改视图的过程中 又出现了这种问题 更新也没用了

在仪表板首页看的是乱的 点进去编辑显示正常的 分享链接看到的还是乱的 视图的时间 我都是设置的年和年月显示还升序排列了  但是乱的里面有不符合的数据

<img width="821" alt="64b9c998f0b9e49c69a025e8cb8c9827" src="https://github.com/dataease/dataease/assets/141667200/7b3bd253-2f38-4b14-8e4b-92e4789f785d">
<img width="906" alt="27d23e1c6ae993133ff371a51d650feb" src="https://github.com/dataease/dataease/assets/141667200/4c2fe4ae-bb9d-45e0-be6e-c85edb7102f3">
<img width="985" alt="b41c7b5d008941ddd127ec5990ebd29b" src="https://github.com/dataease/dataease/assets/141667200/661c5834-3f57-4309-bfd5-3abafc59148b">
<img width="129" alt="d0ad7c2792447040919e405954c64a76" src="https://github.com/dataease/dataease/assets/141667200/28509bde-4dc7-4423-aa12-ae0cc980cc83">

**Comment by wolf-kingx** [comment]
<img width="821" alt="64b9c998f0b9e49c69a025e8cb8c9827" src="https://github.com/dataease/dataease/assets/141667200/182c576c-e36c-49cd-914b-7c16336b363c">

**Comment by xuwei-fit2cloud** [comment]
从截图上来看，确实应该是数据本身有些问题，可以检查一下数据集中是否有脏数据。
![图片](https://github.com/dataease/dataease/assets/1892127/d329d703-b3b3-4133-be33-1fe0ff74e225)

**Comment by wolf-kingx** [comment]
没有 用的excel文件 搜索里一下 里面并没有类似1119-03-07这种乱乱的数据

**Comment by wolf-kingx** [comment]
[采购详单.xlsx](https://github.com/dataease/dataease/files/14321674/default.xlsx)

**Comment by xuwei-fit2cloud** [comment]
收到，我们排查一下，请稍等。

**Comment by wolf-kingx** [comment]
> 收到，我们排查一下，请稍等。

这个问题我是在v2.3里面遇到的 怎么加到v1.18.16了

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
