### ISSUE TITLE
v1.18 kettle相关组件下载报错

### ISSUE THREAD

**Issue by mute-mute** [dataease/dataease#8039]
v1.18 kettle相关组件下载报错，是需要下载本地导入吗？
![微信图片_20240218150327](https://github.com/dataease/dataease/assets/55970913/d1c1e053-7040-44b1-ab46-d204e3b228c7)

**Comment by xuwei-fit2cloud** [comment]
可以参考一下：

https://bbs.fit2cloud.com/t/topic/3250

https://dataease.io/docs/v1/faq/dev_faq/#1-dataease
