### ISSUE TITLE
[Bug]tab组件中的筛选默认值刚打开tab页面是不生效

### ISSUE THREAD

**Issue by victorchens** [dataease/dataease#8041]
**DataEase 版本**
    v1.18.15

**Bug 描述**
   tab组件中的筛选默认值刚打开tab页面是不生效的,重新选择筛选值才生效；
   配置在tab组件外用来控制tab组件内的筛选组件也存在这个问题

**Bug 重现步骤(有截图更好)**

问题录频
https://github.com/dataease/dataease/assets/39784162/f9d93c51-9887-4f70-bcc9-ca1ba98673d4
![image](https://github.com/dataease/dataease/assets/39784162/c6e1e8e1-7714-43ab-8beb-6617bc2436aa)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
