### ISSUE TITLE
[Bug] 饼图设置联动，点击后无法恢复样式

### ISSUE THREAD

**Issue by hiblacker** [dataease/dataease#8043]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
源码运行、官方示例

**浏览器版本**
Chrome Version 121.0.6167.184 (Official Build) (arm64)

**Bug 描述**
饼图设置联动，点击后样式无法恢复，只能刷新恢复。
未设置联动时，点击 - 再点击即可恢复
期望效果：再次点击  清除联动、样式恢复或者清除联动后样式恢复

**Bug 重现步骤(有截图更好)**
1. 饼图设置联动
2. 点击一个扇形
3. 清除联动、查询、清空都无法恢复样式
![image](https://github.com/dataease/dataease/assets/22385375/26113bd3-fac2-4f4e-be93-2882fbc878f2)
![image](https://github.com/dataease/dataease/assets/22385375/f581e434-1866-4e62-8474-8155a0b13c22)

**Comment by hiblacker** [comment]
![image](https://github.com/dataease/dataease/assets/22385375/72aaeb39-4896-481e-8683-b63e6087f2bc)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前升级到了v1.18.15，更新一下环境应该没问题了，我在目前的测试环境上看没发现此问题；

**Comment by hiblacker** [comment]
@BBchicken-9527 
antv的没问题，echarts的还是不行
在官方示例：
![image](https://github.com/dataease/dataease/assets/22385375/21c86db5-3520-479c-bd00-1f5754bf0a8f)

选中状态：
![image](https://github.com/dataease/dataease/assets/22385375/904c1869-5414-46cd-96dd-ee8009d3374f)
清除联动后：
![image](https://github.com/dataease/dataease/assets/22385375/9defdfa9-3b5e-41e7-aef5-58f546f0b4b1)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下这里；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
