### ISSUE TITLE
[Bug]oracle 数据源的sql数据集使用 in 语法和参数时，执行异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#8053]
**DataEase 版本**
1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
oracle 数据源
sql数据集使用 in 语法和参数时，执行异常
![image](https://github.com/dataease/dataease/assets/89771514/0c2bc43a-03d0-4069-ad3a-d94c9c84f1bd)

换成 or 语法执行正常
![image](https://github.com/dataease/dataease/assets/89771514/5691559f-7b51-4da5-97b3-483f766a8cd1)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
