### ISSUE TITLE
[Bug]AntV组合图使用doris数据源的sql数据集报错

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#8054]
**DataEase 版本**
1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
AntV组合图，使用doris数据源的sql数据集报错
![image](https://github.com/dataease/dataease/assets/89771514/852fafe5-b20e-4775-af16-e5641cca573f)

sql数据集如下：
![image](https://github.com/dataease/dataease/assets/89771514/1a42f783-70c5-4402-994b-effc77712fa5)

![image](https://github.com/dataease/dataease/assets/89771514/c75b09ce-e66e-445d-9207-98df65755cf1)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们排查一下；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
