### ISSUE TITLE
[Bug]v1.18.15 数据集转化成日期年月日  还有时分秒存在全都是0

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8059]
安装包安装   不想要这个时分秒 虽然在视图中可以调节不显示  但是如果用视图的过滤器去按日期筛选 会有错误

![image](https://github.com/dataease/dataease/assets/141667200/8b5109dd-b6bf-4695-87e3-c5750684daeb)

![image](https://github.com/dataease/dataease/assets/141667200/0d7e60cd-218f-462b-8025-7d81aeb5844d)

**Comment by BBchicken-9527** [comment]
感谢反馈，格式转换会主要针对现有格式的转换，但数据集时间格式显示为固定格式；
