### ISSUE TITLE
[Bug]ck数据源 sql创建数据集 sql中包括if语句和where中的参数起冲突

### ISSUE THREAD

**Issue by poachedEgg1** [dataease/dataease#8066]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**

ck数据源 sql创建数据集 sql中包括if语句和where中的参数起冲突
把if去掉或者where参数去掉就可以正常执行
**Bug 重现步骤(有截图更好)**
<img width="1185" alt="1708367247578" src="https://github.com/dataease/dataease/assets/42458033/b2e2a5fd-5e9c-46f8-afcb-0178a758f068">

**Comment by BBchicken-9527** [comment]
感谢反馈，if应该是=吧而不是==，看着像是你语法有问题额；

**Comment by xuwei-fit2cloud** [comment]
由于长时间未有反馈，暂时关闭该issue，如有问题，咱们在继续沟通。
