### ISSUE TITLE
[Bug]【仪表板】【v1】全屏展示仪表板会清空过滤组件中的内容

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#8076]
**DataEase 版本**
1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
全屏展示仪表板会清空过滤组件中的内容，详细情况请见以下视频。

https://github.com/dataease/dataease/assets/24768910/9f61fc03-da0f-469e-bab4-cfd5d06d8853

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。

**Comment by AndroidBaby1** [comment]
感谢
