### ISSUE TITLE
[Bug]数据集计算字段逻辑修改，仪表板不生效，需要进入仪表板编辑之后才能生效

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#8078]
**DataEase 版本**
v1.18.15

**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**

版本 121.0.6167.185（正式版本） （64 位）
**Bug 描述**
数据集计算字段逻辑修改，仪表板不生效，需要进入仪表板编辑之后才能生效，是视图设计中字段会显示红色，仪表板展示的数据还是之前的逻辑值

**Bug 重现步骤(有截图更好)**

![image](https://github.com/dataease/dataease/assets/127368807/db4b421b-a738-45b7-9914-d19a7da41eaa)
![image](https://github.com/dataease/dataease/assets/127368807/61206765-a233-433b-8463-f0c669c6b305)
![image](https://github.com/dataease/dataease/assets/127368807/a630790f-1227-49db-a655-67d3928567db)
![image](https://github.com/dataease/dataease/assets/127368807/7caa7327-fab8-4fed-b16d-fb388dbb4043)

**Comment by BBchicken-9527** [comment]
感谢反馈，因为你编辑计算字段在系统中相当于将之间的计算字段删除重建了，所以会显示异常状态，删除掉这个字段重新添加即可；

**Comment by greenyhsj** [comment]
新建字段字段，乘数变了，但是原始字段没有发生改变，提示的是原始字段发生改变
