### ISSUE TITLE
[Bug]未登陆用户使用公共链接访问仪表板，点击视图详情提示输入用户密码

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#8079]
**DataEase 版本**
1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
非登录用户，使用公共链接访问仪表板，点击视图详情提示输入用户密码
<img width="1461" alt="image" src="https://github.com/dataease/dataease/assets/89771514/e256c846-5c00-454c-b729-0dc4093d42ad">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
