### ISSUE TITLE
[Bug]文本下拉过滤组件，在tab组件中使用时，开启多选以及设置默认首项，仪表板预览界面第一次取消时，数据未自动更新

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#8081]
**DataEase 版本**
1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
文本下拉过滤组件，在tab组件中使用时，开启多选以及设置默认首项，仪表板预览界面第一次取消时，数据未自动更新
![image](https://github.com/dataease/dataease/assets/89771514/3d4eac6b-84cb-4b80-a1c9-ae17c814fc47)

![image](https://github.com/dataease/dataease/assets/89771514/746b9982-da7b-434f-9b03-2b3e0a4bade2)

![image](https://github.com/dataease/dataease/assets/89771514/eb01e537-e2f4-426d-acc5-942a529f4b9d)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
