### ISSUE TITLE
表格——明细表列宽问题

### ISSUE THREAD

**Issue by xiaole992** [dataease/dataease#8090]
**DataEase 版本**
V1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌浏览器121.0.6167.185

**Bug 描述**
明细列表列宽调整自定义拉到最低无效果

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，列宽并非任何时候都能生效。容器宽度优先级高于列宽，即(表格容器宽度 / 列数 > 指定列宽)，则列宽优先取(容器宽度 / 列数)。

**Comment by xiaole992** [comment]
容器宽度已经拉的非常宽了，所有内容都能显示完整，就是无法缩小列宽
