### ISSUE TITLE
[Bug]antV组合图插件图标命名与modelName不一致

### ISSUE THREAD

**Issue by DevotedTangLiu** [dataease/dataease#8091]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome 版本 120.0.6099.225（正式版本） （64 位）

**Bug 描述**
antV 组合图插件svg文件名为：
extensions/dataease-extensions-view/view-chartmix/view-chartmix-frontend/src/icons/svg/`view-chart-mix-backend.svg`
plugin.json中modelName为`view-chartmix-backend`,
ChartMixService 中定义的name 为`view-chartmix-backend`:
```
    private StaticResource pluginSvg() {
        StaticResource staticResource = new StaticResource();
        staticResource.setName("view-chartmix-backend");
        staticResource.setSuffix("svg");
        return staticResource;
    }
```
加载logo是url为`pluginCommon/staticInfo/view-chartmix-backend/svg` 
找不到svg图片导致404

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下这里的图片显示；
