### ISSUE TITLE
多级查询的过滤方式要怎么关联[Question]

### ISSUE THREAD

**Issue by kennnnnnnnnn** [dataease/dataease#8098]
**请描述您的问题.**
比如省、市、区三个下拉选择要怎么关联 选择了省后面市区自动只显示当前省的?

**Comment by kennnnnnnnnn** [comment]
v2版本的，另外就是过滤选项数据集下面的绑定参数是哪来的，为什么我这不管怎么设置都是空的

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复如下：
1、过滤组件目前尚未支持下拉树，因此暂不支持省市区的自动关联，下拉树的需求已经在排期了，预计在后面几个版本中会进入开发。
2、绑定的参数为空，请检查下数据集中是否添加了参数，另外参数类型是否与过滤组件的类型匹配。

**Comment by kennnnnnnnnn** [comment]
谢谢
