### ISSUE TITLE
[Bug]仪表板，复用用户模版，报sql错误

### ISSUE THREAD

**Issue by xulinde** [dataease/dataease#81]
**DataEase 版本**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/64065190/123577011-9cadbd00-d805-11eb-9957-55cfc723ea7f.png)

**Comment by xuwei-fit2cloud** [comment]
这个应该是当时无法连接数据源导致的错误。

**Comment by tjlygdx** [comment]
现在模版-视图-数据集的耦合性太强了，我们在考虑重构一下

**Comment by xuwei-fit2cloud** [comment]
无法连接数据源导致的错误，先关闭
