### ISSUE TITLE
apache hive新建数据库数据源选择数据表报错

### ISSUE THREAD

**Issue by eayorlilu** [dataease/dataease#8100]
**DataEase 版本**

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**
添加hive-jdbc-uber-2.6.5.0-292驱动，新建数据库数据源选择数据表报错

**Bug 重现步骤(有截图更好)**
![bbd424d1c090ebe84c3cd7c0aa44687](https://github.com/dataease/dataease/assets/160688594/68742c4a-6d8f-4ec2-851e-9dc5ae5599bf)
驱动链接：https://github.com/timveil/hive-jdbc-uber-jar/releases/download/v1.9-2.6.5/hive-jdbc-uber-2.6.5.0-292.jar

**Comment by BBchicken-9527** [comment]
感谢反馈，方便说明一下详细的步骤吗？你的意思是你添加了一个新的数据源使用的是自定义驱动，创建数据集的时候编辑预览页面可以看到数据但是保存后提示异常？

**Comment by eayorlilu** [comment]
> 感谢反馈，方便说明一下详细的步骤吗？你的意思是你添加了一个新的数据源使用的是自定义驱动，创建数据集的时候编辑预览页面可以看到数据但是保存后提示异常？

对的，排查出问题是2.6不支持limit0，1000的写法，但是程序生成了，需要修改

**Comment by maninhill** [comment]
v2.6 单数据源支持原生 jdbc sql。
