### ISSUE TITLE
[Bug] 二次点击 查询 按钮，表格数据无法刷新

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [dataease/dataease#8101]
**DataEase 版本**
v 1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器  114

**Bug 描述**
在仪表板配置一个明细表， 然后配置一个文本搜索组件 以及 查询按钮， 在文本搜索组件搜索某些内容，点击查询按钮查询，此时数据查询是正常的。 在数据集更新数据后，重新点击查询按钮，发现数据没有更新。

**Bug 重现步骤(有截图更好)**
1.  新建仪表板，包含一个明细表、文本搜索组件、查询按钮
![image](https://github.com/dataease/dataease/assets/30264974/3f72236b-3469-45e9-9e61-91d987ed4255)

2. 如下图，搜索 “云南”， 可以看到 “昆明市 ”的数据
![image](https://github.com/dataease/dataease/assets/30264974/3550031f-b1d5-4dad-8cfe-53d469e8a534)

3. 数据集更新对应的 Excel 数据集， 删除 “昆明市”的数据。
4. 点击查询按钮，依旧有“昆明市”的数据，数据没有更新。
![image](https://github.com/dataease/dataease/assets/30264974/a7fdddcc-c812-447c-bc9d-d3b0b69633eb)
5. 删除文本搜索组件的内容，重新输入 “云南”，重新搜索，此时才更新数据。
![image](https://github.com/dataease/dataease/assets/30264974/45eaf44b-8624-482a-bee7-f32ee7b37e89)

观察：
1、反复点击 查询按钮，发现前端是没有发起查询请求的，此处是设计如此还是 bug ?
2、若设计如此，可否优化一下设计，给用户一定友好的提示呢？

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下这个组件；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
