### ISSUE TITLE
[Bug]v1.18.15 模板市场《增值服务销售分析》模板 选中标题的背景图 页面就会崩溃

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8103]
安装包安装 v1.18.15
这个模板
![image](https://github.com/dataease/dataease/assets/141667200/34a51ad5-c9ad-4a8d-897a-64fa811380e3)
![image](https://github.com/dataease/dataease/assets/141667200/cec33c08-0172-4261-92a8-a61cbd96bf05)
![image](https://github.com/dataease/dataease/assets/141667200/dce3cfb1-f6d1-42fe-9960-aff97684a638)
点击退出网页然后就说崩溃
![image](https://github.com/dataease/dataease/assets/141667200/4d984d15-37e6-4487-81ba-aa830d716f42)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下这个模版；

**Comment by wolf-kingx** [comment]
> 感谢反馈，我们优化一下这个模版；
这个问题不止在模板市场里遇到了 在平时自己制作模板也遇到了  在制作模板里遇到的是编辑标题的时候会卡死 然后崩溃 虽然重新复制了一个仪表板 在新的上面操作是没有问题的 但是这个问题需要解决一下
