### ISSUE TITLE
[Bug]源码编译失败，缺少很多依赖包

### ISSUE THREAD

**Issue by kkrrsq** [dataease/dataease#8104]
**DataEase 版本**
v2.3.0 社区版

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**Bug 描述**
core-backend 编译失败，maven 缺少很多依赖包，其中大部分是第三方包，还有一个 calcite-core-de 包是修改过的

**Bug 重现步骤(有截图更好)**
1.从 github 拉取 v2.3.0 分支源码
2.编译

**建议**
将  calcite-core-de 上传到公共仓库，并补充 maven 缺少的依赖，最好写个源码编译运行文档

**Comment by xuwei-fit2cloud** [comment]
core-backend 源码编译并不会有问题，一些依赖无法下载，应该是 Maven 仓库无法正常访问的原因。
包括您提到的  calcite-core-de 包，我们在 pom.yml 文件中也是指明了下载仓库的，是可以正常下载的。
近期我们会提供在线的源码开发文档，还请等待。

**Comment by kkrrsq** [comment]
@xuwei-fit2cloud 你自己拉 github 的源码编译一下就知道有没有问题了

**Comment by xuwei-fit2cloud** [comment]
我是在全新的Linux环境下从头开始一步一步编译执行写的文档，所以，还请等待文档上线。

**Comment by kkrrsq** [comment]
@xuwei-fit2cloud 嗯，多谢，我已经跑起来了，只是提个建议，希望这个项目越来越好

**Comment by xuwei-fit2cloud** [comment]
非常感谢

**Comment by tigerli216** [comment]
> @xuwei-fit2cloud 嗯，多谢，我已经跑起来了，只是提个建议，希望这个项目越来越好

老铁！这个calcite-core  1.35.2的包 你怎么弄的？

**Comment by kkrrsq** [comment]
> > @xuwei-fit2cloud 嗯，多谢，我已经跑起来了，只是提个建议，希望这个项目越来越好
> 
> 老铁！这个calcite-core 1.35.2的包 你怎么弄的？

从安装包里面找到这个 jar 包，然后 deploy 到本地 maven 仓库就可以了

**Comment by xuwei-fit2cloud** [comment]
在 core/core-backend/pom.xml 文件中定义了拉取 calcite-core 依赖的仓库：
```xml
    <repositories>
        <repository>
            <id>fit2cloud-public</id>
            <name>Fit2cloud Public</name>
            <url>https://repository.fit2cloud.com/repository/fit2cloud-public/</url>
        </repository>
    </repositories>
```

另外，可以参考一下在线文档：
https://dataease.io/docs/v2/installation/deployment_installation/

**Comment by wat1r** [comment]
@kkrrsq 老铁，前端的 core-fronend 编译安装成功了?

**Comment by kkrrsq** [comment]
> @kkrrsq 老铁，前端的 core-fronend 编译安装成功了?

成功了，前端编译没遇到啥问题

**Comment by huguiqi** [comment]
centos环境，这几个包确实下载不下来，必须把本地maven的其它国内镜像去掉，才走它pom.xml配置仓库，但是去掉以后，它的仓库里很多Spring和apache相关的包又拉不下来

**Comment by SerMs** [comment]
> 在 core/core-backend/pom.xml 文件中定义了拉取 calcite-core 依赖的仓库：
> 
> ```
>     <repositories>
>         <repository>
>             <id>fit2cloud-public</id>
>             <name>Fit2cloud Public</name>
>             <url>https://repository.fit2cloud.com/repository/fit2cloud-public/</url>
>         </repository>
>     </repositories>
> ```
> 
> 另外，可以参考一下在线文档： https://dataease.io/docs/v2/installation/deployment_installation/
您好,请问一下这个死活都拉不下来是怎么回事呢? 443是否需要配置权限?
![image](https://github.com/dataease/dataease/assets/67584847/632ff67b-b7cf-4a91-b9ab-ce0e1b23c6d4)
