### ISSUE TITLE
源码方式部署之后数据库表信息不全?

### ISSUE THREAD

**Issue by shuyixiao-better** [dataease/dataease#8105]
源码方式部署之后数据库表信息不全?de-xpack包下的依赖丢失？导致打包docker镜像存在问题？

**Comment by shuyixiao-better** [comment]
源码方式部署v2.3分支源码

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复如下：
1、源码部署方式是不支持xpack功能的。
2、源码部署后没有xpack部分数据库表，既不影响打包，也不影响开源功能的使用。

**Comment by shuyixiao-better** [comment]
你好，我想请问一下 如果xpack功能属于非开源部分，但目前源码部署完成后，后台持续有关于找不到xpack相关报错，后续是否有源码部署方式支持xpack功能的计划？

**Comment by xuwei-fit2cloud** [comment]
你好，近期会上线源码开发文档，还请等待。

**Comment by shuyixiao-better** [comment]
> 你好，近期会上线源码开发文档，还请等待。

好的，谢谢啦~
