### ISSUE TITLE
视图：明细表-高级-阈值设置

### ISSUE THREAD

**Issue by 2023fan** [dataease/dataease#8111]
DataEase 版本:V2

视图：明细表-高级-阈值设置
V1支持选用本文类数据，V2只支持整数类数据
希望V2也可以支持文本类数据
V1如下图
<img width="399" alt="v1" src="https://github.com/dataease/dataease/assets/145900305/bd200371-bac8-466c-ada9-a611c07adcbe">
V2如下图
<img width="780" alt="v2" src="https://github.com/dataease/dataease/assets/145900305/0da3ce44-4ff2-424a-b451-13326ef1e7fe">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，v2版本会根据需求的优先级，规划在后面的版本迭代中实现该功能。
