### ISSUE TITLE
[Feature]页面排序需要在控制台可管理

### ISSUE THREAD

**Issue by kkljcf** [dataease/dataease#8113]
DataEase 版本:
1.85

**请描述您的需求或者改进建议.**
如图，超管来判断分享页面是否开启排序，而不是现在这样全部具备排序
![image](https://github.com/dataease/dataease/assets/125198800/d111a095-a34b-4c8c-9060-941082fd0a3c)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们增加个配置项。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
