### ISSUE TITLE
[Bug]【仪表板】视图多语言环境下文本内容显示异常

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#8116]
**DataEase 版本**
1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
视图多语言环境下文本内容显示异常，详见以下截图
![image](https://github.com/dataease/dataease/assets/24768910/048fe0f3-1172-4473-bc06-dd584a76accb)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行优化；
