### ISSUE TITLE
[Feature]【仪表板】仪表盘视图优化

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#8117]
DataEase 版本:
1.18.15

**请描述您的需求或者改进建议.**
目前 AntV 图库的仪表盘只能展示百分达成情况，不能显示成对应的值范围：
![image](https://github.com/dataease/dataease/assets/24768910/b40d9480-b6cb-4d0a-a50c-c43c32d13069)

Echarts 图库的仪表盘都可以展示，但是，数值容易堆叠在一块：
![image](https://github.com/dataease/dataease/assets/24768910/428d569c-930c-4451-85d2-8cc5842af010)

能否优化一下 AntV 仪表盘，使其可以支持具体值范围，或者优化 Echarts 仪表盘，使其可以设置数值大小。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们已经加入需求池。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。

**Comment by AndroidBaby1** [comment]
感谢老师💐
