### ISSUE TITLE
[Bug]新建SQLServer数据源报错

### ISSUE THREAD

**Issue by reteng** [dataease/dataease#8123]
**DataEase 版本**
2.3.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
EDGE 版本 121.0.2277.128 (正式版本) (64 位)

**Bug 描述**
新建SQLServer数据源报错

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/13897633/ff389d38-b598-4db6-9d5d-d8c2b394c2f8)

**Comment by BBchicken-9527** [comment]
感谢反馈，在额外的JDBC链接字符串中加入这个试试看呢：encrypt=true;trustServerCertificate=true

**Comment by reteng** [comment]
JDBC链接字符串添加：encrypt=true;trustServerCertificate=true 后问题解决
