### ISSUE TITLE
[Bug]新建账号登陆时，出现缓存bug，导致DataEase无法正常访问

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#8124]
**DataEase 版本**
1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 版本 121.0.6167.184（正式版本） (x86_64)

**Bug 描述**
无论如何刷新页面，DataEase始终卡在如下图所示页面的状态，且输入框无法输入内容

**Bug 重现步骤(有截图更好)**
1.admin账号登陆DE，创建一个新的账号lisi
![image](https://github.com/dataease/dataease/assets/89771514/967e079d-d5b8-45f6-a2f5-817c32c5d52a)

2.使用lisi登陆DE,首次登陆弹出修改用户密码提示框
![image](https://github.com/dataease/dataease/assets/89771514/645b2c5f-a2e4-4069-b849-0f393aa25724)
此时，新旧密码全部输入默认的密码，点击确定
![image](https://github.com/dataease/dataease/assets/89771514/f0154f49-4e6a-4c90-9ae6-399bdf2f27f2)
点击确定后，自动退出到登陆界面
![image](https://github.com/dataease/dataease/assets/89771514/12ecfebe-014d-4302-98a6-77287597ab41)

3. 此时刷新导航栏，就会出现下面图片的状态，登陆页面直接变成了这样的状态，且密码输入框无法编辑
![image](https://github.com/dataease/dataease/assets/89771514/30284500-e72d-418f-bde6-141b58807bfc)

**Comment by linyuiu** [comment]
使用的什么浏览器，edge可能会有这个问题。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，受累看一下前端是否有什么报错异常可以提供给我们排查一下；
![image](https://github.com/dataease/dataease/assets/84372766/69cb768b-5a2c-4576-9ddc-8d077653b82f)

**Comment by ZhaoQian1222** [comment]
<img width="1461" alt="image" src="https://github.com/dataease/dataease/assets/89771514/2d2c8e9c-6cc4-4673-b42b-dde6586706cc">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
