### ISSUE TITLE
elasticSearch构建的数据集查看有数据，但是构建面板的时候，有的数据就没值。

### ISSUE THREAD

**Issue by mute-mute** [dataease/dataease#8128]
![微信图片_20240222145714](https://github.com/dataease/dataease/assets/55970913/417be01c-ed27-4039-955c-918db7f56796)
![微信图片_20240222145720](https://github.com/dataease/dataease/assets/55970913/6c68a5c2-6472-4a42-a775-f8202c3a21af)

**Comment by mute-mute** [comment]
我这边发现是数值类型有数据，文本类型没有

**Comment by BBchicken-9527** [comment]
感谢反馈请问你是用的es版本是多少呢？

**Comment by mute-mute** [comment]
> 感谢反馈请问你是用的es版本是多少呢？
6.8.11

**Comment by BBchicken-9527** [comment]
感谢反馈，我这边使用es6.8的版本没发现你说的这个问题，请问你是字段类型上有啥特殊的设置吗？
![image](https://github.com/dataease/dataease/assets/84372766/1b3bb825-536d-435f-9488-5418e8d94100)

**Comment by mute-mute** [comment]
我刚才用你们官网的也不行，数据格式没修改

**Comment by mute-mute** [comment]
数据量2w左右，这是你们测试demo上配置的面板
![image](https://github.com/dataease/dataease/assets/55970913/e82f0b24-dec0-445a-9f74-f1baefdfc1af)

**Comment by maninhill** [comment]
无法重现，先关闭。
