### ISSUE TITLE
[Feature] 数据集查询数据改为打开时异步查询或者由按钮触发查询。

### ISSUE THREAD

**Issue by BertonSun-fit2cloud** [dataease/dataease#8139]
DataEase 版本: 1.18 和 2.3

问题描述：打开数据集时，页面会进行一次数据查询，如果数据库的数据量比较大，或性能不是很优的时候，这个查询速度就会比较慢，甚至于加载需要几分钟，加载过程中页面是不可以操作的，如果我想编辑数据集的 SQL，就需要等待加载完成后，才能使用编辑功能。

优化建议：将数据集打开时的数据查询框改为异步或通过查询按钮进行查询，这样可以在我只是想编辑 SQL 时，能够快速的进入到数据集编辑状态，而不用在页面上等待数据集查询完成。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈和支持，我们优化一下，将页面加载时不能编辑的限制放开。

查询特别慢的情况，预览仅显示100条数据，理论上说应该不会特别慢的，请问这边是什么数据库？

**Comment by BertonSun-fit2cloud** [comment]
> 感谢您的反馈和支持，我们优化一下，将页面加载时不能编辑的限制放开。
> 
> 查询特别慢的情况，预览仅显示100条数据，理论上说应该不会特别慢的，请问这边是什么数据库？

我是用的是 MySQL，页面显示的是1000 条数据，查询用了 1.2 分钟
![WX20240318-114933](https://github.com/dataease/dataease/assets/77650472/85a87d13-8d0f-411a-af3d-f9a191b00831)

**Comment by xuwei-fit2cloud** [comment]
新版本已优化，请更新版本。
