### ISSUE TITLE
[Bug]echart地图海南省的显示异常

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#8140]
DataEase 版本
v1.18.15

运行方式(安装包运行 or 源码运行 ?)

安装包
浏览器版本

版本 121.0.6167.185（正式版本） （64 位）

**Bug 描述**

echart海南省地图异常，把群岛全部加进去，海南岛主岛的占比特别小
**Bug 重现步骤(有截图更好)**
1.正常的其他省份
![image](https://github.com/dataease/dataease/assets/127368807/b3c40bb2-2663-41de-bf97-c201899b6481)
![image](https://github.com/dataease/dataease/assets/127368807/5a1a2986-9792-44ea-a635-489097823a8e)

2.异常的海南省
![image](https://github.com/dataease/dataease/assets/127368807/18aaad6a-0640-49db-bd84-4fa70237ce15)

**Comment by BBchicken-9527** [comment]
感谢反馈，受到地图自身的影响，目前暂时不支持设置每个区域的room比例的；
