### ISSUE TITLE
[Bug]v1版本 starrocks数据源 sql数据集  antv组合图维度不起作用 只会根据数据集的第一个字段进行分组

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8142]
v1.18.15 安装包安装

starrocks数据源 sql数据集 

sql数据集1
![image](https://github.com/dataease/dataease/assets/141667200/ec0f31a4-fb83-427f-a78a-7afaeaed7ae1)

在使用antv组合图时，选择的是按照name分组，但是显示的视图是按照year字段分组。
![image](https://github.com/dataease/dataease/assets/141667200/35061cd8-2233-4cf6-9d97-0ad0d53676a2)

后续排查问题，更换了字段的显示顺序。
![image](https://github.com/dataease/dataease/assets/141667200/ddfd6a2e-fb99-4687-8ac2-dcee6a3e995c)

继续设置按照name分组，发现这回是根据amount1这个字段进行分组的。
![image](https://github.com/dataease/dataease/assets/141667200/9462da0f-cb32-490d-91d4-9f9830dc6f1b)

综上，在使用starrocks数据源创建sql数据集是，使用antv组合图，视图分组会强制根据数据集所指定的第一个字段，手动拖进去的字段并为生效。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，你那边清除缓存之后也是必现的吗？

**Comment by wolf-kingx** [comment]
> 感谢反馈，目前测试环境没有发现你说的问题，你那边清除缓存之后也是必现的吗？

是的 必现的 antv的组合图 echarts没问题

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
