### ISSUE TITLE
[Feature]建议 AntV 表格的排序图标可以跟随表头文字颜色更改颜色

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#8147]
DataEase 版本:
v1.18.15

**请描述您的需求或者改进建议.**
如下图所示，建议排序的小图标颜色可以修改，或者直接跟随表头文字颜色变化，否则会出现融入背景看不到或是比较突兀的情况。
![image](https://github.com/dataease/dataease/assets/48945409/e3916e70-c414-42e8-8880-17ece9b3390b)
![image](https://github.com/dataease/dataease/assets/48945409/4e348506-61a8-4923-94b0-280ee01a456e)
![image](https://github.com/dataease/dataease/assets/48945409/46d30656-f7a5-4538-a817-08208f4d0c5d)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先看下图库是否支持自定义图标颜色，如果图库支持，我们会尽快支持上。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
