### ISSUE TITLE
[Feature]echarts汇总表导出时带合计行数据

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#8148]
DataEase 版本:
1.18.15

**请描述您的需求或者改进建议.**
1、视图
![image](https://github.com/dataease/dataease/assets/101089844/a2d130c3-d05b-4446-aa6e-5b090b655663)

 2、导出数据不带合计，希望带合计数据
<img width="420" alt="image" src="https://github.com/dataease/dataease/assets/101089844/7730976f-d60c-4885-a5d3-589d80e989b4">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已经在v1.18.17版本迭代中。
