### ISSUE TITLE
[Bug] 用elasticSearch数据集制作面板时，结果展示必须选全部才能展示数据，否则报错

### ISSUE THREAD

**Issue by mute-mute** [dataease/dataease#8149]
**DataEase 版本**
v1.18.15
**elasticSearch 版本**
V7.17.9
**运行方式(安装包运行 or 源码运行 ?)**
官网
**浏览器版本**
微信自带 或者 chrome 121.0.6167.185
**Bug 描述**
用elasticSearch数据集制作面板时，结果展示必须选全部才能展示数据，否则报错。
**Bug 重现步骤(有截图更好)**
1.配置数据集数据集
![image](https://github.com/dataease/dataease/assets/55970913/091d202d-8588-4743-9751-e0990ad362cc)

2.配置仪表盘，选择了表格明细，添加字段后报错
![1708919383404](https://github.com/dataease/dataease/assets/55970913/b43a61ac-416c-48a9-bff0-fd23fb09ceae)

3.数据jie结果勾选全部，正常显示
![1708919325922](https://github.com/dataease/dataease/assets/55970913/e0961fea-f271-475f-9ada-df48b08e0308)

**Comment by BBchicken-9527** [comment]
感谢反馈，我这边用es7的数据源看了一下没发现什么问题，emm是对数据量有什么要求吗？你那边是什么量级的数据呢？
![image](https://github.com/dataease/dataease/assets/84372766/a2d44519-91c3-45a4-b95a-3d18c444234a)

**Comment by xuwei-fit2cloud** [comment]
由于长时间未有反馈，暂时关闭该issue，如有问题，咱们在继续沟通。
