### ISSUE TITLE
[Feature]V1 筛选组件多选希望加一个一键清除按钮

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#8152]
DataEase 版本:
1.18.15

**请描述您的需求或者改进建议.**
![wecom-temp-24560-f4fac010c6b1eeec3810afa10001aecb](https://github.com/dataease/dataease/assets/101089844/308f4793-9c78-4791-9dbb-31f5792e83a9)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中支持一键清除功能。
