### ISSUE TITLE
[Feature]视图支持word格式下载，方便我们日常工作报告时，可以简单修改后就能使用。

### ISSUE THREAD

**Issue by huangxine** [dataease/dataease#8158]
DataEase 版本:

**请描述您的需求或者改进建议.**
需求：视图支持word格式下载，下载的是仪表板里视图、以及视图后面的数据明细：视图以图片的形式提供，视图对应的数据提供明细。
目的：日常工作报告时，简单修改后就能使用，目前的pdf无法修改

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复请见：
1、视图下载，视图本身可看作一张图片，因此仅支持图片下载。
2、仪表板导出，目前支持导出为图片和pdf，由系统直接导出的内容，为了数据的严谨性，因此以原格式导出，并且不允许修改。
      目前暂时没有计划支持导出为word，如果需要，建议将视图和数据导出后，放在word中，自定义成需要的格式。
