### ISSUE TITLE
[Bug]v1.18.14版本的SQL数据集能正常查询，升级到v1.18.15报错

### ISSUE THREAD

**Issue by victorchens** [dataease/dataease#8169]
**DataEase 版本**

v1.18.15

**Bug 描述**
v1.18.14版本的SQL数据集能正常查询，升级到v1.18.15报错
报错信息：class net.sf.jsqlparser.statement.select.SetOperationList cannot be cast to class net.sf.jsqlparser.statement.select.PlainSelect (net.sf.jsqlparser.statement.select.SetOperationList and net.sf.jsqlparser.statement.select.PlainSelect are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @68be2bc2)

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/39784162/639ce79d-3d32-463b-a4d9-88fc712bca13)

2.
[Uploading 报错sql.txt…]()

3.报错sql
select * from (
select a.data_type,a.country_name,a.ls_qty,b.ls_qty as ls_y_qty from (
 select '零售' as data_type,
  			 country_name,
     		 sum(sale_qty) as ls_qty
 from mv_cbu_retail_month_detail
 where 1=1
 and ls_month = '${data_month}'
 and brand = '${brand}'
 and area = '${dept_name}'
 and data_type = '${data_type}'
 group by country_name
 having sum(sale_qty)>0
 order by sum(sale_qty) desc
 ) a left join 
 ( select '零售' as data_type,
  			 country_name,
     		 sum(sale_qty) as ls_qty
 from mv_cbu_retail_month_detail
 where 1=1
 and substr(ls_month,1,4) = substr('${data_month}',1,4)
 and ls_month <= '${data_month}'
 and brand = '${brand}'
 and area = '${dept_name}'
 and data_type = '${data_type}'
 group by country_name
 having sum(sale_qty)>0
 order by sum(sale_qty) desc) b 
 on a.data_type = b.data_type and a.country_name = b.country_name
 
union all

select a.data_type,a.country_name,a.ls_qty,b.ls_qty as ls_y_qty from (
select 
  '开票' as data_type,
  country_name,
  sum(invoice_qty) as ls_qty
  from mv_cbu_invoice_month_sum
 where 1=1
 and invoice_month = '${data_month}'
 and category2 = '${brand}'
 and area = '${dept_name}'
 and data_type = '${data_type}'
 group by country_name
  ) a left join (
 select 
  '开票' as data_type,
  country_name,
  sum(invoice_qty) as ls_qty
  from mv_cbu_invoice_month_sum
 where 1=1
 and substr(invoice_month,1,4) = substr('${data_month}',1,4)
 and invoice_month <= '${data_month}'
 and category2 = '${brand}'
 and area = '${dept_name}'
 and data_type = '${data_type}'
 group by country_name
  ) b 
  on a.data_type = b.data_type and a.country_name = b.country_name
  )   t where data_type = '${data_type}'

**Comment by BBchicken-9527** [comment]
感谢反馈，应该是升级的依赖导致，我们优化一下；

**Comment by victorchens** [comment]
会在v1.18.16版本解决不

**Comment by ZionLoh90** [comment]
有人升级到最新版本嘛？之前尝试了一下，最新版本sql依赖和语法全换了，还要学习新的语法，由于时间原因又降回来版本了
