### ISSUE TITLE
数据源中增加MQTT协议采集做设备状态展示

### ISSUE THREAD

**Issue by songgang1997** [dataease/dataease#8172]
建议在数据源中增加MQTT协议的采集，kepserver是连接PLC的一个数采软件，通过kepserver可以采集设备的参数，采集参数后可以在IOT中增加MQTT agent，增加agent后搭建MQTT服务器，kepserver会将要转发的数据发送到MQTT服务器，MQTT客户端连接MQTT服务器增加模版，即可接收kepserver的标签信息。
通过这种方式可以实现设备状态展示：如设备电流、设备压力、设备转速、设备的步骤等等一些信息
设备的PLC点位的数据是数字，特定点位的数字可能拥有另一层含义，所以需要增加对个别字段的数据转换，如某一点位与上位机软件进行交互，其中数据为1为打印2为移出0为待机，包括显示PLC手动自动状态可能为显示1为自动显示0为手动。这是我目前的需要，并且需要可以对数据进行小数点的换算，比如有可能采集到的数据是123456，但是实际这是一个显示电压的点位，所以需要进行换算到123.456，增加小数点。
另一方面可以增加一些动画，动画图片可与接收到的信号进行联动，等于几个时候显示什么状态，比如1的时候，图片是绿色或者转，是2的时候它就是红色或者不转。
并希望官网若采纳后可出一个教程。我搭建时使用的MQTT客户端是MQTTX，MQTT服务器是EMQX好像。
请采纳，谢谢

**Comment by songgang1997** [comment]
![06e268db4f28e33cb8d06f4b829f0da](https://github.com/dataease/dataease/assets/35589880/82809443-ccd5-4505-80fd-f72d656bb180)
![e0067ee9df13d883c0c0c1ddf9739c8](https://github.com/dataease/dataease/assets/35589880/a23620e5-fd6d-4527-81e3-71f5453c2fc9)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有规划进行支持，等有更多相关的需求后我们再做下一步的规划。
