### ISSUE TITLE
[Bug]精简模式下的excel数据集使用round函数处理后的小数位数不符合预期

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#8173]
**DataEase 版本**
1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
上传excel数据集，新建数据集计算字段，使用ROUND(x,y)函数保留两位小数，查看数据预览，计算字段的结果与预期不符，后面多了很多00000
![image](https://github.com/dataease/dataease/assets/89771514/3f722c4f-5564-41bf-983c-dc201d979d59)
![image](https://github.com/dataease/dataease/assets/89771514/4cee5789-441f-4a66-b217-785d1ab289b5)

**Comment by BBchicken-9527** [comment]
感谢反馈，计算字段返回内容数据库有关；
