### ISSUE TITLE
[Bug]v2版本 富文本框 华文仿宋字体加粗没反应

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8174]
v2.3.0 安装包安装，富文本框在使用华文仿宋字体时，加粗没反应，复制一个尝试也不行，网页开启无痕也不行，加粗和斜体同时使用有变化，但是只粗体不行。

https://github.com/dataease/dataease/assets/141667200/f4d54e24-6d91-4eda-9a17-38c9c1c7c63c

**Comment by BBchicken-9527** [comment]
感谢反馈，应该是原生组件导致，我们看看有没有方式修复此处；

**Comment by wolf-kingx** [comment]
> 感谢反馈，应该是原生组件导致，我们看看有没有方式修复此处；

黑体和有些其他华文也有这个问题

**Comment by BBchicken-9527** [comment]
> > 感谢反馈，应该是原生组件导致，我们看看有没有方式修复此处；
> 
> 黑体和有些其他华文也有这个问题

嗯嗯 ，应该是相同的问题导致的，如果可以修复应该一并都没什么问题了；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
