### ISSUE TITLE
[Bug]时间字段跳转失效

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#8175]
**DataEase 版本**
1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**Bug 描述**
时间字段跳转失效

**Bug 重现步骤(有截图更好)**
1.点击时间字段跳转
![image](https://github.com/dataease/dataease/assets/101089844/22ecedba-2530-4fde-97fa-9641f04b47af)

2.跳转过滤失效
![image](https://github.com/dataease/dataease/assets/101089844/d25ee847-5ace-4bc6-b1a8-45eda36f1ac4)

3.查看过Doris ，考虑是筛选时where条件没有用时间转换过的格式进行筛选

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你是用的数据源是什么？我用doris数据源没有发现问题是可以联动的；
![image](https://github.com/dataease/dataease/assets/84372766/017b136d-1b7f-4031-9934-c70490a54d32)
