### ISSUE TITLE
[Feature]明细表导出未展示的同数据集的其他字段

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#8179]
DataEase 版本:
1.18.15

**请描述您的需求或者改进建议.**
做完仪表板后，通过链接分享给别人，是想要根据  已筛选后 的明细表数据进行导出，明细表能够 只展示部分列数据，导出的时候全列导出吗

**Comment by xuwei-fit2cloud** [comment]
即将发布的v1.18.16版本可以自定义每列的列宽，将不需要展示的列的宽度设置为0即可满足你的要求。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
