### ISSUE TITLE
[Feature] 堆叠柱状图优化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#8180]
DataEase 版本:
v1.18.15

**请描述您的需求或者改进建议.**
堆叠柱状图的指标过滤条件增加TopN选项
![image](https://github.com/dataease/dataease/assets/30063018/a7ec50e2-ad60-4c76-b485-f06767953358)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，该需求已在近期的需求池中。
