### ISSUE TITLE
[Bug] 公共链接点击跳转时的数据过滤问题

### ISSUE THREAD

**Issue by zgm1234567890** [dataease/dataease#8184]
**DataEase 版本**
版本 | 企业版
v1.18.9

**运行方式(安装包运行 or 源码运行 ?)**
不清楚
**浏览器版本**
谷歌浏览器：版本 122.0.6261.70（正式版本） （64 位）

**Bug 描述**
通过跳转，实现a页面跳到b页面的时候，点击a页面的姓名想要在b页面显示对应人，【对应日期】的详细数据，
在仪表盘配置以后是可以实现的，
但是在公共连接里点击名字以后，跳转到的对应人【所有日期】的数据

**Bug 重现步骤(有截图更好)**
1.a页面跳转设置：
![image](https://github.com/dataease/dataease/assets/158808982/d5b55a26-0958-4b6f-b022-cfbe809261ae)
2.操作视频：
链接：https://pan.baidu.com/s/1r7L5HFfRv5M-S0bOW9mctQ?pwd=nr06 
提取码：nr06 
3.截图：
点击位置：
![image](https://github.com/dataease/dataease/assets/158808982/e631c214-370f-45fb-a073-16ac2f621f6e)
仪表盘点击跳转结果：只包含此人2月26号的数据
![image](https://github.com/dataease/dataease/assets/158808982/de753324-b7fd-4d58-b2a7-0d1f0ce4c81f)
公共链接点击后跳转结果：包含此人所有日期的数据
![image](https://github.com/dataease/dataease/assets/158808982/18e94acd-6699-4e89-a5b8-3ff1097c306a)

**Comment by zgm1234567890** [comment]
补充下，数据集采用的是sql数据集

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
