### ISSUE TITLE
[Bug] local模式下，原本是文本类型的数值字段，使用该字段新建视图计算字段报错

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#8185]
**DataEase 版本**
v1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
local模式下，原本是文本类型的数值字段，使用该字段新建视图计算字段报错

**Bug 重现步骤(有截图更好)**
1. <img width="1044" alt="image" src="https://github.com/dataease/dataease/assets/45852479/23f8e5b9-50ee-4f5b-b441-511de4c442fb">
2. <img width="1139" alt="image" src="https://github.com/dataease/dataease/assets/45852479/c9bf307d-f750-4275-a764-917e0888ee6c">

**Comment by BBchicken-9527** [comment]
感谢反馈，计算字段进行计算是使用的数据类型为字段原始类型，你可能需要先将参数转成数值；
