### ISSUE TITLE
[Bug]【数据集】SQL 数据集从旧版本升级到新版本之后报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#8186]
**DataEase 版本**
1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
从 v1.18.14 版本升级到 v1.18.15 之后 SQL 数据集报错，于是做了以下测试。

**Bug 重现步骤(有截图更好)**
1.比如说这段 SQL：
![image](https://github.com/dataease/dataease/assets/24768910/8c014667-c5e5-498f-ba94-1ceaaeaa5054)

2.「运行查询」报如下错：
![image](https://github.com/dataease/dataease/assets/24768910/e328cf92-fbe9-4b65-94cd-1fd1ac919fb6)

3.当我只取这一部分：
![image](https://github.com/dataease/dataease/assets/24768910/75ec0812-5bf1-4a16-abc9-29acc3fbad66)

4.「运行查询」就不报错了：
![image](https://github.com/dataease/dataease/assets/24768910/446bab2a-eeb1-404f-8cc0-bed30688ec3f)

注意：这一段 SQL 只是我 SQL 当中的其中一段，所以不能说是用步骤 3 的 SQL 就行，烦请帮忙看一下，感谢~

**Comment by BBchicken-9527** [comment]
感谢反馈，你强制刷新一下页面看看呢？

**Comment by AndroidBaby1** [comment]
好咧~
