### ISSUE TITLE
[Feature]过滤组件可以筛选其他非其对应数据集的内容

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#8189]
DataEase 版本:
v1 版本

**请描述您的需求或者改进建议.**
过滤组件的值是基于数据集 A，让它拥有过滤数据集 B 的功能，并向数据集 B 传入外部参数。

**Comment by xuwei-fit2cloud** [comment]
为何不将数据集A中需要传递给数据集B的字段和数据集B一起创建关联数据集呢？

**Comment by AndroidBaby1** [comment]
嗯嗯，已经叫用户来回复具体的一个场景了

**Comment by liuhaonan001** [comment]
因为如果将数据集AB进行关联：1、对开发人员不友好，每次都要进行这样重复的操作。2、影响性能。3、关联到的空行影响判断。如果过滤组件可以使用数据集 B 传入外部参数就不会存在这种问题，而且使用起来也更简单

**Comment by xuwei-fit2cloud** [comment]
v1版本对这块的改造工作量较大，暂时不考虑，v2版本可以支持。
