### ISSUE TITLE
[Feature]过滤组件加强，支持 key-value 模式

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#8190]
DataEase 版本:
v1

基于这个 issue：https://github.com/dataease/dataease/issues/8189
**请描述您的需求或者改进建议.**
过滤组件可以配置一个数据集 A 的 key-value 的值组，筛选的时候展示 value，却输出 key 值来对数据集 B 进行筛选。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已加入近期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
1.
