### ISSUE TITLE
[Feature]【数据集】关联数据集可以和普通数据集一样在字段管理处展示原始名称

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#8191]
DataEase 版本:
v1

**请描述您的需求或者改进建议.**
关联数据集可以和普通数据集一样在字段管理处展示原始名称
<img width="1045" alt="image" src="https://github.com/dataease/dataease/assets/24768910/08a17ad4-47e1-44ff-a05f-7844ad631c07">
<img width="922" alt="image" src="https://github.com/dataease/dataease/assets/24768910/638ac2db-79b0-43a2-853f-2aed60d1577c">

**Comment by xuwei-fit2cloud** [comment]
很抱歉，目前关联数据集中并未记录该字段的值，无法实现该需求。
