### ISSUE TITLE
短链接可自定义及可设置查看看板的IP白名单

### ISSUE THREAD

**Issue by songgang1997** [dataease/dataease#8195]
1.短链接现在是随机生成，建议增加可自定义短链接内容，如XX设备运行状态看板，可自定义短链接为/XXYXZT，可不需要每次对照输入
2.增加设置访问固定看板的白名单IP，如我有一个看板不想让其他无关人员看到，或看板中有非常重要的内容但平常又经常需要查看，设置IP白名单可只在本部门电脑上查看，其他未设置白名单的IP无法打开此看板，可避免信息泄露。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，回复请见如下：

1、短链接自定义我们先加入需求中，规划在2.x的版本中进行实现；
2、IP白名单目前暂时没有规划进行实现。
