### ISSUE TITLE
后续会出发布版本为Jar包部署的版本吗

### ISSUE THREAD

**Issue by 172151295** [dataease/dataease#8199]
后续会出发布版本为Jar包部署的版本吗？

**Comment by 172151295** [comment]
> 后续会出发布版本为Jar包部署的版本吗？

> V2.版本

**Comment by xuwei-fit2cloud** [comment]
我们会提供v2版本的开发手册，里面会有说明如何编译生成对应的jar包，以及运行时相关配置文件的设置，近期将会上线，还请等待。

**Comment by silloy** [comment]
![image](https://github.com/user-attachments/assets/28782982-47f6-44c2-91c9-627ed89d1891)
没有提供这三个包吗，2.10 版本，无法编译
