### ISSUE TITLE
[Bug]数据集，查看sql数据集超时

### ISSUE THREAD

**Issue by xulinde** [dataease/dataease#82]
**DataEase 版本**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/64065190/123577179-eac2c080-d805-11eb-88ff-58233bf09426.png)

**Comment by xuwei-fit2cloud** [comment]
这个是 DataEase 里的超时设置，默认超时时间是10秒。
这部分我们先讨论一下如何改进。

**Comment by xuwei-fit2cloud** [comment]
v1.4 版本中已支持超时时间设置。
