### ISSUE TITLE
[Bug]获取数据成功，但数据错误

### ISSUE THREAD

**Issue by kkljcf** [dataease/dataease#8200]
**DataEase 版本**
1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
脚本一键安装的

**浏览器版本**
所有

**Bug 描述**
MSSQL2008R2
字段time(3)
内容08:00:00.000
到了DE就变成了08:05:43.000

**Bug 重现步骤(有截图更好)**
1.就直接查询就出现了
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，你用的什么方式查询的？是sql查询还是数据库数据集？是否是定时任务？你说的直接查询就出来是预览页面就有问题还是保存之后出现问题的呢？受累说明一下具体的情况；

**Comment by kkljcf** [comment]
SQL直连查询
![image](https://github.com/dataease/dataease/assets/125198800/56d48907-dab5-4743-8d61-f9fb522124b7)
而我的原始数据
![image](https://github.com/dataease/dataease/assets/125198800/9b219e62-34ef-4560-a4b5-1d094ef729b0)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前平台只支持sqlserver版本在2012以上版本，抱歉为您的使用带来不便；
