### ISSUE TITLE
[Bug]鼠标触发的视图提示，如果维度特别多，下方视图会将提示框遮挡

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#8201]
**DataEase 版本**
v1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome   firefox

**Bug 描述**
提示框超出视图后，下方视图会遮挡提示框

![图片](https://github.com/dataease/dataease/assets/48307752/dce0eb8b-0987-43b3-8867-b78f90ad2bb0)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，应该是图层顺序的问题，我们优化一下；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
