### ISSUE TITLE
[Bug] 在本地环境无法访问模版市场的情况下，模版管理页面无法加载离线模版

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#8206]
**DataEase 版本**
v 2.3

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
在本地环境无法访问模版市场的情况下，模版管理页面无法加载离线模版

**Bug 重现步骤(有截图更好)**
1. <img width="1479" alt="image" src="https://github.com/dataease/dataease/assets/45852479/83a1b8eb-212a-4a00-aebd-2c295fd2434c">
2. <img width="1479" alt="image" src="https://github.com/dataease/dataease/assets/45852479/2692d775-cf15-4d17-acca-93ad2481fc75">

**Comment by xuwei-fit2cloud** [comment]
无法复现。
