### ISSUE TITLE
地图经纬度点位显示增加该地址的描述信息

### ISSUE THREAD

**Issue by BJZB** [dataease/dataease#8217]
DataEase版本：V1版
![p1](https://github.com/dataease/dataease/assets/52100619/f0e72ad1-3525-45fa-ad60-9677ff5749bf)
在制作地图时，增加一些地址的经纬度可以在地图上显示该地址点位，但是能不能像图p1那样给该点位地址在地图旁边显示一个文本框啥的显示一些该地址的主题、介绍或者数据等描述信息，特指该点位的，而不是地图的整个地区的。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划给每个数据点增加备注信息。
