### ISSUE TITLE
[Feature]V2 读取ORCLE没有表注释。V1的那种都达不到啊

### ISSUE THREAD

**Issue by hapeacock** [dataease/dataease#8234]
DataEase 版本:V2.3

参考一下V1链接ORACLE数据库读取一下表注释把。V1还能自动字段映射，V2不行啊

使用版本第一步就是链接数据源，映射字段啊。这是最基础的啊。后面直接劝退了呀

**Comment by maninhill** [comment]
v2 版本还在迭代中，我们会尽快上线这个功能。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，由于v2版本使用的calcite获取不到字段注释，我们已经调研， 并已经有了初步的方案，接下来会进行这一块的优化。

**Comment by maninhill** [comment]
和 #7857 重复
