### ISSUE TITLE
[Feature]明细表排序符号隐藏

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#8237]
DataEase 版本
v1.18.15

**请描述您的需求或者改进建议.**
明细表排序符号隐藏排序的符号，没有排序的需求，在这边显示占用位置同时影响美观
![image](https://github.com/dataease/dataease/assets/127368807/e792934e-f44b-4b5d-a016-040fa01d0119)
![image](https://github.com/dataease/dataease/assets/127368807/3a2d2410-1a8b-4a93-8588-396062029a6b)

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #7978
