### ISSUE TITLE
[Bug]移动端成功上传背景图片，但下次进行编辑的时候背景图片不显示

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#8239]
DataEase 版本
v1.18.15

运行方式(安装包运行 or 源码运行 ?)

安装包
浏览器版本

版本 121.0.6167.185（正式版本） （64 位）
Bug 描述
移动端成功上传背景图片，但下次进行编辑的时候背景图片不显示。
移动端打开是可以看到背景的，但是编辑的时候没有背景，有些背景是有位置标记等作用，背景不显示的话编辑起来有麻烦

**Bug 重现步骤(有截图更好)**
设置好移动端背景
![image](https://github.com/dataease/dataease/assets/127368807/d3f40a5e-c980-40dc-8436-c3c52f1befc8)
设置好再次进入编辑界面，背景不显示，移动端或者手机模式打开公共链接显示，只是编辑界面不显示
![image](https://github.com/dataease/dataease/assets/127368807/d92c1293-0ee4-4019-933d-15af4639c9c9)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
