### ISSUE TITLE
[Bug] 饼图或者矩形树图，当设置2个维度的时候，标签遮挡了

### ISSUE THREAD

**Issue by mmmlong** [dataease/dataease#8243]
**DataEase 版本：**
 v2.2

**运行方式(安装包运行 or 源码运行 ?)** 
安装包和源码

**浏览器版本**
Chrome
版本 122.0.6261.94

**Bug 描述**
<img width="1193" alt="image" src="https://github.com/dataease/dataease/assets/30709129/1a82344e-77ca-4994-b25a-827e886d0243">

<img width="1179" alt="image" src="https://github.com/dataease/dataease/assets/30709129/64609b01-f845-4ebb-915c-dababed0a10c">

**Bug 重现步骤(有截图更好)**
1.创建仪表板
2.新建--饼图

**Comment by BBchicken-9527** [comment]
感谢反馈，这个问题是图表自身携带问题，我们想办法优化一下这里；
