### ISSUE TITLE
[Bug]日期函数无法使用

### ISSUE THREAD

**Issue by lpt524937674** [dataease/dataease#8267]
**DataEase 版本**
v2.3.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome 版本 122.0.6261.95（正式版本） （64 位）

**Bug 描述**
doris数据源
数据集中，自定义sql无法使用日期函数获取最近7天数据
计算字段也无法使用日期函数

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/11208010/2e62a18c-d57a-4f19-8733-18774e5af759)

2.
![image](https://github.com/dataease/dataease/assets/11208010/0a3c465a-fc8f-4e60-834b-a553b9913982)

3.

**Comment by 172151295** [comment]
![wx_camera_1709280416980.jpg](https://github.com/dataease/dataease/assets/70830248/4c4b7155-a513-4cf1-b5d9-6922fc34817a)

我也遇到了

**Comment by 172151295** [comment]
> ![wx_camera_1709280416980.jpg](https://github.com/dataease/dataease/assets/70830248/4c4b7155-a513-4cf1-b5d9-6922fc34817a)
> 
> 我也遇到了

我这是oracle

**Comment by 172151295** [comment]
![wx_camera_1709280416980.jpg](https://github.com/dataease/dataease/assets/70830248/4c4b7155-a513-4cf1-b5d9-6922fc34817a)

我也遇到了@fit2cloudrd

**Comment by lpt524937674** [comment]
> > ![wx_camera_1709280416980.jpg](https://private-user-images.githubusercontent.com/70830248/309190496-4c4b7155-a513-4cf1-b5d9-6922fc34817a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODExMzksIm5iZiI6MTcwOTI4MDgzOSwicGF0aCI6Ii83MDgzMDI0OC8zMDkxOTA0OTYtNGM0YjcxNTUtYTUxMy00Y2YxLWI1ZDktNjkyMmZjMzQ4MTdhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA4MTM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZjEzZTJmMTZhMGJiM2RiMGMwOTNiNDQzYjZiM2ZhNDI1YmRmMTYxYzBiZWNhOTFlYmViNmYyNDgwMWJhYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e8pE8eafOhV2IbMYpzjHk6ADftPBrFjDGUMv74q9pfM)
> > 我也遇到了
> 
> 我这是oracle

你这个应该是dual的问题，换个你自己的表名试下呢

**Comment by 172151295** [comment]
> > > ![wx_camera_1709280416980.jpg](https://private-user-images.githubusercontent.com/70830248/309190496-4c4b7155-a513-4cf1-b5d9-6922fc34817a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyODExMzksIm5iZiI6MTcwOTI4MDgzOSwicGF0aCI6Ii83MDgzMDI0OC8zMDkxOTA0OTYtNGM0YjcxNTUtYTUxMy00Y2YxLWI1ZDktNjkyMmZjMzQ4MTdhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDA4MTM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1ZjEzZTJmMTZhMGJiM2RiMGMwOTNiNDQzYjZiM2ZhNDI1YmRmMTYxYzBiZWNhOTFlYmViNmYyNDgwMWJhYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e8pE8eafOhV2IbMYpzjHk6ADftPBrFjDGUMv74q9pfM)
> > > 我也遇到了
> > 
> > 我这是oracle
> 
> 你这个应该是dual的问题，换个你自己的表名试下呢

![wx_camera_1709279798296.jpg](https://github.com/dataease/dataease/assets/70830248/664a6ab0-d2e8-42dc-8773-b01b512ee799)

不行就是不行啊，！！！不行你们试试啊

**Comment by wuyufei1993** [comment]
![image](https://github.com/dataease/dataease/assets/28557476/b493fae6-99fb-4dae-b59f-e8c0a1b37a84)
clickhouse的日期函数也无法使用

**Comment by lpt524937674** [comment]
试了半天发现直接使用CURRENT_DATE会报错，但是CURRENT_DATE作为其他函数的参数可以，比如STR_TO_DATE(CURRENT_DATE,'yyyy-MM-dd HH:mm:ss')就能执行成功，虽然执行成功获取到当前日期了，但是又出现问题STR_TO_DATE的返回值是时间类型，DataEase默认成了文本类型，导致调用DAYS_SUB(STR_TO_DATE(CURRENT_DATE,'yyyy-MM-dd HH:mm:ss'),1)时候报参数类型错误

**Comment by 172151295** [comment]
> 试了半天发现直接使用CURRENT_DATE会报错，但是CURRENT_DATE作为其他函数的参数可以，比如STR_TO_DATE(CURRENT_DATE,'yyyy-MM-dd HH:mm:ss')就能执行成功，虽然执行成功获取到当前日期了，但是又出现问题STR_TO_DATE的返回值是时间类型，DataEase默认成了文本类型，导致调用DAYS_SUB(STR_TO_DATE(CURRENT_DATE,'yyyy-MM-dd HH:mm:ss'),1)时候报参数类型错误

什么时候修复，还有oracle的sysdata

**Comment by 172151295** [comment]
@fit2cloudrd

**Comment by xuwei-fit2cloud** [comment]
正在处理中，还需要一些时间。

**Comment by 172151295** [comment]
> 正在处理中，还需要一些时间。

还得多久 2.4版本能修复吗？

**Comment by BBchicken-9527** [comment]
感谢反馈，由于现在统一sql规则是通过calcite去进行实现的，所以函数的话需要calcite有才可以支持。我们也发现了这个问题，目前我们正在讨论支持的方案，在后续的版本我们会逐步的支持，请各位小伙伴耐心等候；

**Comment by 172151295** [comment]
> 感谢反馈，由于现在统一sql规则是通过calcite去进行实现的，所以函数的话需要calcite有才可以支持。我们也发现了这个问题，目前我们正在讨论支持的方案，在后续的版本我们会逐步的支持，请各位小伙伴耐心等候；

v2.5版本能修复吗？

**Comment by 172151295** [comment]
> 感谢反馈，由于现在统一sql规则是通过calcite去进行实现的，所以函数的话需要calcite有才可以支持。我们也发现了这个问题，目前我们正在讨论支持的方案，在后续的版本我们会逐步的支持，请各位小伙伴耐心等候；

预计什么时候能支持那？？

**Comment by maninhill** [comment]
v2.6 单数据源已经支持原生 jdbc sql
