### ISSUE TITLE
[Bug]自定义sql获取当前日期，字段类型默认为字符串，而不是日期类型

### ISSUE THREAD

**Issue by lpt524937674** [dataease/dataease#8274]
**DataEase 版本**
v2.3.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome 版本 122.0.6261.95（正式版本） （64 位）

**Bug 描述**
doris数据源，自定义sql获取当前日期，字段类型默认为字符串，导致调用日期函数时，报参数类型错误

**Bug 重现步骤(有截图更好)**
1.获取当前时间，字段类型默认为字符串，而不是日期类型
![image](https://github.com/dataease/dataease/assets/11208010/2a435641-bef3-4e26-a57e-40aa29b253cc)

2.调用字符串转日期函数，转换后的类型依然不对
![image](https://github.com/dataease/dataease/assets/11208010/3141344b-9efd-48ca-87ec-2a75a31692e4)

3.调用日期函数DAYS_SUB减去指定天数时，报参数类型错误
![image](https://github.com/dataease/dataease/assets/11208010/e0bfcda2-0cb3-418f-acc4-66bcf506c0d3)

**Comment by BBchicken-9527** [comment]
感谢反馈，问题将在下个版本修复；

**Comment by maninhill** [comment]
v2.10-lts 版本已经发布，请在最新版本上面验证，有问题请 re-open。
