### ISSUE TITLE
多页面跳转组件

### ISSUE THREAD

**Issue by BJZB** [dataease/dataease#8289]
DataEase 版本: v1版

本项目有多个主题内容，需要涉及多个仪表板页面，需要在页面之间来回跳转观看，能否增加一个跳转组件，点击该组件就实现跳转仪表板，当然可以编辑该组件的标题。另外已有的组件，例如文本组件、图片组件、富文本组件能不能增加我这样需求的跳转功能，还有特别是那些过滤组件，包括下拉、文本、搜索，能不能增加这样需求的跳转功能，我点击所选的项来实现跳转，特别是下拉组件。感谢考虑此需求。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，现回复如下：
1、多个仪表板来回切换查看，建议您将这些仪表板放在一个文件目录下，手动来回切换查看。如果是投放在显示器中自动轮播，建议您参考该文档操作，文档链接：https://kb.fit2cloud.com/?p=231
2、下拉组件是用于过滤仪表板中图表的数据，从而展示不同的结果，因此目前没有计划支持通过点击选项来实现跳转。
