### ISSUE TITLE
视图中明细表指标汇总方式需要多个“无”

### ISSUE THREAD

**Issue by jstbw** [dataease/dataease#829]
**请描述您的需求或者改进建议.**
数据列/指标这里，应该有个选择“无”，有时候不需要求和
![image](https://user-images.githubusercontent.com/66759501/133561969-0b78d30b-93a1-4307-b982-8d355fb5b66e.png)
![image](https://user-images.githubusercontent.com/66759501/133562040-ae072d40-d73b-4bca-96d8-f381add79c09.png)

**Comment by yayanpei** [comment]
非常感谢您的反馈，10.14号的V1.3.0版本实现该需求，请多多关注～

**Comment by xuwei-fit2cloud** [comment]
v1.3.0 版本已支持。
