### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by 143027** [dataease/dataease#83]
**请描述您的需求或者改进建议.**
<img width="1016" alt="屏幕快照 2021-06-28 11 36 29" src="https://user-images.githubusercontent.com/86582619/123577313-31b0b600-d806-11eb-9ad0-5bcddde8f1c3.png">
标签无法更改位置，可能会被图形遮挡

**Comment by XiaJunjie2020** [comment]
![image](https://user-images.githubusercontent.com/59437931/123577496-87855e00-d806-11eb-8572-4127b54d5255.png)
标签位置，可以修改
