### ISSUE TITLE
[Feature]打开移动端默认显示的不是首页

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#8307]
DataEase 版本:
v1.18

打开移动端界面，在首页没有内容的情况下，是空白的，大多数人第一感觉是没有内容的，希望打开可以默认显示目录。
或者，“首页” 和 “目录” 位置互换，首页在中间，目录在左边，默认显示目录页。

![图片](https://github.com/dataease/dataease/assets/48307752/22d51bda-e953-43b3-9ed6-f399e7a37582)

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，如果没有显示内容，是由于这个菜单中确实没有内容，可以切换其他菜单。如果没有内容，我们优化下，增加相应的提示。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
