### ISSUE TITLE
[Feature]V1版本 在显示部分数据的时候 希望支持从前截取或者从后截取的选择

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8308]
想取近6个月数据（202309-202402），但是按时间升序排序再限制取6条数据的话，取的是202308-202401的数据；如果按照降序排序，去的虽然是202309-202402的数据，但是在视图显示的时候，也是从左到右降序显示了，不符合趋势的习惯性展示。
![1f8b824430934f3944f13e5770eec17](https://github.com/dataease/dataease/assets/141667200/58ab0a1e-58c8-4717-8665-816e8034025f)

虽然可以用时间过滤组件进行筛选，但是日期不是标准格式的情况，如现在我们是2024-W01这种形式，就无法用日期组件进行筛选。
这样的话，就只能手动自定义排序，每周变化也很麻烦。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，该需求当前暂不考虑进行支持，待收集更多同类需求后再做下一步的规划。
