### ISSUE TITLE
[Bug] 定时同步 mysql 数据集，时间类型字段日期过滤组件无法正确的查询结果

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#8312]
**DataEase 版本**
v1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome 105.0.5195.125（正式版本） (arm64)

**Bug 描述**
定时同步 mysql 数据集，时间类型字段日期过滤组件无法正确的查询结果

**Bug 重现步骤(有截图更好)**
1. 
![image](https://github.com/dataease/dataease/assets/45852479/cf8d60be-c1b4-4dfa-9410-e8583cfefaec)
2. 
![image](https://github.com/dataease/dataease/assets/45852479/a4320ec2-3bd0-4987-b5b9-1366f4c41a5b)
3. 
![image](https://github.com/dataease/dataease/assets/45852479/759b87b8-d712-4210-a570-93a2ffee5155)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，可以尝试更新最新的版本看一下；
![image](https://github.com/dataease/dataease/assets/84372766/8bf48347-1119-43a1-b14e-12e83701abcb)
