### ISSUE TITLE
[Feature]组合图的提示可以显示维度信息

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#8326]
DataEase 版本:
v1.18
组合图的提示希望显示维度信息；

![图片](https://github.com/dataease/dataease/assets/48307752/6b62d0b5-3a21-47f5-a40f-5111a837b00c)

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
技术上应该可以，我们试试。
