### ISSUE TITLE
[Feature]组合图的标签，希望可以控制只显示一个指标

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#8328]
DataEase 版本:
v1.18
两个指标的标签都显示会感觉乱，希望能控制只显示一个指标的标签
![图片](https://github.com/dataease/dataease/assets/48307752/abf3920f-384c-430f-81ed-813155a71d11)

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
技术上可以支持，我们考虑一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
