### ISSUE TITLE
[Feature]antv组合图维度不能对时间字段调整格式

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#8329]
DataEase 版本:
v1.18.15
antv组合图,维度内有对时间字段调整格式的选项，希望加上
![图片](https://github.com/dataease/dataease/assets/48307752/1147087b-c45f-434e-b8db-9419401b1658)

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
技术上应该可以，我们后面加一下。
