### ISSUE TITLE
[Feature]看下面

### ISSUE THREAD

**Issue by 98bc-art** [dataease/dataease#834]
**请描述您的需求或者改进建议.**
我下载了1.2版本的dataease 在pom中dataease-plugins显示由于暂时插件接口未注册到公司仓库，请先down下代码安装到本地仓库这个怎么安装啊，父项目的打包方式是pom，我就把里面的三个分别打包了，之后项目运行的时候显示程序包io.dataease.plugins.xpack.ldap.dto.request不存在

**Comment by zhangkwq** [comment]
dataease-plugins下载到本地后 直接mvn clean 然后 install

**Comment by xuwei-fit2cloud** [comment]
请检查代码分支，dataease v1.2分支里是没有ldap内容的。v1.2的代码所用的dataease-plugins依赖已上传中央仓库。如需使用开发分支代码，请参考楼上的解答。
