### ISSUE TITLE
[Feature] 项目选择太短了，最多只能显示 9 个字母，建议增加到 20 个

### ISSUE THREAD

**Issue by ibuler** [dataease/dataease#8343]
DataEase 版本: ${current} 

**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/17382885/c831e977-2572-4d9b-8483-9ad892d040e2)

宽度太窄，不够美观，增加到 20个字母宽度

**Comment by xuwei-fit2cloud** [comment]
应该是屏幕分辨率问题，您也可以将文本下拉组件拉宽一些。

**Comment by maninhill** [comment]
gddznb
