### ISSUE TITLE
sqlServer 字段不能用[]包裹

### ISSUE THREAD

**Issue by gkerry** [dataease/dataease#8366]
DataEase 版本
v2.3.0

运行方式(安装包运行 or 源码运行 ?)
安装包运行,1 Panel商店安装

浏览器版本
Edge,Chrome

数据库:
数据源 Sqlserver 20112
 
Bug 描述
查询字段用中括号 [ ] 包裹后报错. 因为有个字段和关键字冲突了 : count

Bug 重现步骤(有截图更好)
 
 ![image](https://github.com/dataease/dataease/assets/50052250/76d2203a-ffdd-4b4e-afc5-10a6f7864c23)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，如果与关键字冲突，加上反引号试试，如下所示：
select ‘count’ from tablename

**Comment by xuwei-fit2cloud** [comment]
由于长时间未有反馈，暂时关闭该issue，如有问题，咱们在继续沟通。

**Comment by gkerry** [comment]
抱歉.确实解决了问题. 当时由于github登录不上. 没回复时间久了就忘了
