### ISSUE TITLE
[Bug]v1.18.15 滚动条有时候不灵

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8382]
安装包安装

刚点编辑进入仪表盘的时候 滚动条不滚动 刷新之后可以  用的谷歌浏览器 用360反而没问题了

进入滚动2min左右 数据没到底 又不滚动了

**Comment by wolf-kingx** [comment]
https://github.com/dataease/dataease/assets/141667200/2a00e986-290e-4238-90de-af85504a527c

**Comment by wolf-kingx** [comment]
有点概率问题，有时候等个2分钟就会复现出来

**Comment by BBchicken-9527** [comment]
感谢反馈，目前在最新版本的测试环境中没有发现此类问题，建议使用最新版本尝试一下；
