### ISSUE TITLE
[Bug]v1.18.15 编辑滚动条开启滚动后 不会动 保存之后也不生效 刷新浏览器之后才有变化

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8390]
安装包安装
谷歌浏览器

v1.18.15 编辑滚动条开启滚动后 不会动 保存之后也不生效 刷新浏览器之后才有变化
 试了四次 都不管用

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境和本地环境均没有发现你说的这个问题，建议尝试最新版本看一下是否依然存在此类问题；
