### ISSUE TITLE
[Feature]建议透视表和汇总表，支持按照汇总列（维度项）填充不同颜色

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#8394]
DataEase 版本:
v1.18.15

请描述您的需求或者改进建议.
建议透视表和汇总表，支持按照汇总列（维度项）填充不同颜色，不同颜色突出不同维度，有利于查看和对比数据

![image](https://github.com/dataease/dataease/assets/127368807/195ae375-6619-4e12-aa0a-6e65d0db2977)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持该需求，待收集更多同类需求后再做下一步的规划。
