### ISSUE TITLE
[Feature]增加针对doris 、starrocks的bitmap数据类型及其函数支持

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#8396]
DataEase 版本:
v2.5

**请描述您的需求或者改进建议.**
针对doris db，starrocks等olap引擎，增加增加针对bitmap数据类型及其函数的支持，calcite 目前无法解析bitmap相关函数

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们目前正在尝试处理该场景，还需要一些时间。

**Comment by maninhill** [comment]
v2.6单数据源已经支持原生jdbc sql
