### ISSUE TITLE
希望模板可以在离线环境下访问

### ISSUE THREAD

**Issue by 172151295** [dataease/dataease#8399]
DataEase 版本:V2.X

希望后续版本支持在无网络环境，仍能访问模板，而不是只在有互联网环境，才能使用或者访问模板市场里的模板。

**Comment by xuwei-fit2cloud** [comment]
您可以登录在线模板市场 https://templates.dataease.cn 下载对应的模板文件，如下图
![图片](https://github.com/dataease/dataease/assets/1892127/bd6f4ce2-8ccf-485c-98ee-7d431b575ee3)

具体操作可参考在线文档
https://dataease.io/docs/v2/user_manual/template_market/#31
