### ISSUE TITLE
描述不详[Feature]

### ISSUE THREAD

**Issue by yacheng-xie** [dataease/dataease#84]
在过滤设置中，建议针对文本和指标两种类型的数据，做出不同的过滤条件描述，如对文本信息，条件为”包含“等。
![image](https://user-images.githubusercontent.com/66484040/123577593-b7346600-d806-11eb-90c3-9b3e19babaec.png)

**Comment by yayanpei** [comment]
您的建议非常好，后续我们会跟进该需求，感谢您的反馈

**Comment by xuwei-fit2cloud** [comment]
v1.2.0 版本已修改
