### ISSUE TITLE
[Feature] 同环比设置添加周环比

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#8401]
DataEase 版本:
v1.18.16

**请描述您的需求或者改进建议.**
同环比设置添加周环比
![image](https://github.com/dataease/dataease/assets/45852479/3ba2a3fa-c43e-4cc4-9b55-0fc4730cd472)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们会在后续版本进行支持。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
