### ISSUE TITLE
[Feature] 仪表板导出图片/PDF 支持通过接口实现

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#8402]
DataEase 版本:
v1.18.16

**请描述您的需求或者改进建议.**
仪表板导出图片/PDF 支持通过接口实现

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，可以支持，我们规划在近期的版本中进行支持。

**Comment by c-dada** [comment]
请问是在最新的v1.18版本中支持的吗，没有知道对应的实现接口呢

**Comment by c-dada** [comment]
> 感谢您的反馈，可以支持，我们规划在近期的版本中进行支持。

请问是在最新的v1.18版本中支持的吗，没有找到对应的实现接口呢
