### ISSUE TITLE
[Bug] MongoDb 数据源校验异常

### ISSUE THREAD

**Issue by heartInGod** [dataease/dataease#8407]
<img width="1408" alt="image" src="https://github.com/dataease/dataease/assets/30049098/54b23e98-f5c1-4742-84f4-111feb88e587">

**Comment by Shenguobin0102** [comment]
您好，您描述的问题我们没有复现，看报错信息可能跟您的 MongoDB 服务状态异常或填写的连接信息不准确有关，请再检查一下服务和连接信息后试试。

**Comment by xuwei-fit2cloud** [comment]
由于长时间未有反馈，暂时关闭该issue，如有问题，咱们在继续沟通。
