### ISSUE TITLE
自行上传的驱动无法选择"定时同步"连接方式

### ISSUE THREAD

**Issue by tzengshinfu** [dataease/dataease#8410]
_Originally posted by @f2m4 in https://github.com/dataease/dataease/issues/7521#issuecomment-1926840320_
            
**问题描述**
与@f2m4状况相同，我们的数据库是MSSQL 2014，无法在v1.18.14后使用，
已自行上传mssql-jdbc-10.2.0.jre8.jar后可以`直连`，
但`定时同步`却是无法选取的状态。
(其他原本已有的驱动则是正常。)
![image_20240308_091129](https://github.com/dataease/dataease/assets/2170033/1264a257-9b2c-4f1f-a6bb-df64ad196096)
![image_20240308_091157](https://github.com/dataease/dataease/assets/2170033/dcfc2ee4-d00d-4908-89a7-2c0fb573a0dd)
![image_20240308_092719](https://github.com/dataease/dataease/assets/2170033/2ff45e94-a13a-4fdb-9f68-2348498d6a80)

**DataEase 版本**
v1.18.16

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome v122.0.6261.112

**Comment by xuwei-fit2cloud** [comment]
因为定时同步是通过kettle来执行的，而上传的驱动是给DataEase自身使用，并不能直接给kettle使用，所以自行上传的驱动无法使用定时同步模式。

**Comment by tzengshinfu** [comment]
> 因为定时同步是通过kettle来执行的，而上传的驱动是给DataEase自身使用，并不能直接给kettle使用，所以自行上传的驱动无法使用定时同步模式。

我们还有很旧的MSSQL 2000，我们自建的Kettle原本不支持，也是要另外找驱动(jtds-1.3.1.jar)才能读取；能否DataEase的Kettle也可如此？

**Comment by xuwei-fit2cloud** [comment]
理论上是的，需要：
1. DataEase默认驱动可以提供多个版本的内置驱动选择；
2. 所有内置驱动都需要在kettle的驱动目录下存放一份；
3. kettle可以使用这些内置驱动。

**Comment by tzengshinfu** [comment]
尝试用docker cp指令将自行上传的驱动复制到kettle容器的`/opt/kettle/lib`目录下，并重启DataEase和kettle容器，仍无作用；
不知DataEase如何能感知kettle也有自行上传的驱动？

**Comment by maninhill** [comment]
这个问题暂无支持计划。
