### ISSUE TITLE
[Bug] starrocks数据源配置图表查询执行的sql中时间字段两层转换导致物化表加速改写失效

### ISSUE THREAD

**Issue by marvel-007** [dataease/dataease#8419]
**DataEase 版本**
1.18.13

**运行方式(安装包运行 or 源码运行 ?)**
docker镜像

**浏览器版本**

**Bug 描述**
数据源是starrocks  查询的是基表 ，创建了这个基表的物化表进行进行加速，由于时间字段进行了两层转换 无法实现自动改写到物化进行加速查询了。
时间字段timestamp 就是datetime类型的 2024-03-08 00:00:00这个格式   由于查询语句进行了两次准转换 
WHERE (DATE_FORMAT(DATE_FORMAT(t_a_0.`timestamp`,'%Y-%m-%d %H:%i:%S'),'%Y-%m-%d %H:%i:%S') BETWEEN '2024-03-08 00:00:00' AND '2024-03-09 00:00:00')
可以直接使用这样查询实现物化加速能力：WHERE timestamp BETWEEN '2024-03-08 00:00:00' AND '2024-03-09 00:00:00'

**Bug 重现步骤(有截图更好)**
<img width="1029" alt="image" src="https://github.com/dataease/dataease/assets/18569221/e1fbc452-0570-4a74-bdb7-40d8599bb6b6">

**Comment by BBchicken-9527** [comment]
感谢反馈，受累和你确认一下原本使用的sql是什么？是否使用了参数化？

**Comment by marvel-007** [comment]
> 感谢反馈，受累和你确认一下原本使用的sql是什么？是否使用了参数化？

就是通用的图表配置，配置了时间选择组件，控制图表进行时间范围查询，通过直连 数据库 直接进行查询，在创建物化视图后发现查询速度没有加速，然后通过startrocks 检测到的查询语句分析和测试，查询语句时间两次转换导致物化改写没有生效。

<img width="951" alt="image" src="https://github.com/dataease/dataease/assets/18569221/73efcd1d-b5f7-4962-81a6-12c0c5bd173a">
<img width="1137" alt="image" src="https://github.com/dataease/dataease/assets/18569221/21ab46a9-0480-44cd-8998-2962acb82b9a">
<img width="332" alt="image" src="https://github.com/dataease/dataease/assets/18569221/82c74e0e-d81c-4a52-87a8-8efc4fa9eebc">

最终查询的语句：

SELECT * FROM (SELECT t_a_0.`source_ip` AS f_ax_0 , COUNT(*) AS f_ay_0 FROM `nginx_log` t_a_0 WHERE (DATE_FORMAT(DATE_FORMAT(t_a_0.`timestamp`,'%Y-%m-%d %H:%i:%S'),'%Y-%m-%d %H:%i:%S') BETWEEN '2024-03-14 00:00:00' AND '2024-03-14 23:59:59') GROUP BY t_a_0.`source_ip` ) t_a_1 ORDER BY f_ay_0 desc LIMIT 0,10

**Comment by marvel-007** [comment]
测试发现 在 1.18.18 中已修复，查询效果提升明显
