### ISSUE TITLE
[Bug]ClickHouse 自定义驱动创建数据集报错

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#8423]
**DataEase 版本**
1.18.16

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1. 新建自定义驱动
驱动类：com.clickhouse.jdbc.ClickHouseDriver
支持版本：24
驱动包：https://github.com/ClickHouse/clickhouse-java/releases/download/v0.4.6/clickhouse-jdbc-0.4.6-all.jar
![image](https://github.com/dataease/dataease/assets/30886198/6ea489ec-15c6-4c4c-a309-e71587d0f9cb)

2. 新建数据源，使用ClickHouse 24 版本，校验通过，成功添加数据源
3. 创建数据库数据集，选择上一步的数据源，报错如下：
报错类与自定义驱动类名不一致
![image](https://github.com/dataease/dataease/assets/30886198/a3cd1a6f-12a8-42e8-98bd-75d0842fc38c)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
