### ISSUE TITLE
[Question] 不同数据源为什么calcite语法树解析差别那么大

### ISSUE THREAD

**Issue by heartInGod** [dataease/dataease#8424]
**请描述您的问题.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，不同数据库语法树解析差别的原因主要有以下几点：
1、SQL方言差异，虽然大多数数据库均支持ANSI SQL标准，但是每家数据库厂商会根据自身产品的特性和需求，扩展出自己特有的方言。
2、功能扩展，不同数据库可能会拓展额外的功能，比如索引类型、自定义函数等，这些都会导致SQL语法的丰富和变化，从而引起解析结果的差异。
3、兼容性和历史遗留问题，为了保持向后兼容，一些数据库可能会保留旧版本中的非标准语法结构。
4、性能优化考量，数据库设计可能会针对特定场景优化SQL执行路径，因此允许特定的语法结构来指导优化器。

**Comment by maninhill** [comment]
v2.6 单数据源已经支持原生jdbc sql
