### ISSUE TITLE
[Bug]clickhouse 数据源  在转calcite语法过程中，把时间类型字段的hhmmss的分钟minute转化至yyyymmdd那个month数值

### ISSUE THREAD

**Issue by 1782007694** [dataease/dataease#8426]
**DataEase 版本**
2.4.0

**运行方式(安装包运行 or 源码运行 ?)**

在线升级，在线安装
**浏览器版本**
 谷歌122.0.6261.112

**Bug 描述**
1.clickhouse 数据集编辑查询sql时间类型字段展示征程，但到这个柱状图直接给时间类型字段的hhmmss的分钟转minute化至yyyymmdd那个month数值
2.clickhouse 数据集 查询字段枚举值正常，但到了筛选组件，这个字段去查询组件去查询，枚举值显示不全

**Bug 重现步骤(有截图更好)**
1.
![10c90cdcf7316af6ff0fde734f15ad4](https://github.com/dataease/dataease/assets/73865643/7e180163-5b51-48e3-91b2-78a02a00765f)

2.
![460930c1e7417ce6f33b2f3f1e12ea0](https://github.com/dataease/dataease/assets/73865643/e90e78dd-4a9d-4032-aae2-66187c942bd2)

3.
![image](https://github.com/dataease/dataease/assets/73865643/2adc5613-a874-4e19-9313-5f9ebed00753)
4.
![image](https://github.com/dataease/dataease/assets/73865643/e8bc4cf0-8601-408f-bb9b-7cf4268e49c3)

**Comment by 1782007694** [comment]
还有自己做的视频还原操作，已和客服小北，拉会对齐，确实是存在这个问题

**Comment by BBchicken-9527** [comment]
![image](https://github.com/dataease/dataease/assets/84372766/44540cc4-7ef7-436c-8ffa-d69daa88312b)
感谢反馈，目前测试环境没有发现你说的问题，我这边已经和小北对齐了，为了保证能还原你的情况也用的是你给的表设计，你用的是最新的版本吗？如果不是的话升级一下看看是否还有这方面的问题，第二个问题方便问一下你的数据量吗？我看看同等数据量的情况下是否会出现你现在的问题；

**Comment by 1782007694** [comment]
您好，请问是用了clickhouse 数据源吗？想请问下这个您们测试环境原始表数据能发我一份吗，我想试试是哪个类型不一致

**Comment by PengyuDeng** [comment]
> 是用了clickhouse 数据源吗

我也遇见了找个问题，我也同样反馈了，https://github.com/dataease/dataease/issues/8538

**Comment by 1782007694** [comment]
> > 是用了clickhouse 数据源吗
> 
> 我也遇见了找个问题，我也同样反馈了，#8538

请问您解决了吗

**Comment by BBchicken-9527** [comment]
那可能是我这边版本的问题，我这边查看的是22的版本，后续我做一个22以上版本的ck确认一下两位的问题；

**Comment by 1782007694** [comment]
> 那可能是我这边版本的问题，我这边查看的是22的版本，后续我做一个22以上版本的ck确认一下两位的问题；
DataEase 版本
2.4.0 有这个问题，2.3.0就没有这个问题

**Comment by PengyuDeng** [comment]
> 那可能是我这边版本的问题，我这边查看的是22的版本，后续我做一个22以上版本的ck确认一下两位的问题；

ok

**Comment by 1782007694** [comment]
> > 那可能是我这边版本的问题，我这边查看的是22的版本，后续我做一个22以上版本的ck确认一下两位的问题；
> 
> ok

请问这个问题在新版本解决了吗

**Comment by 1782007694** [comment]
> 那可能是我这边版本的问题，我这边查看的是22的版本，后续我做一个22以上版本的ck确认一下两位的问题；

请问这个问题在新版本解决了吗

**Comment by maninhill** [comment]
v2.6 单数据源已经支持原生 jdbc sql

**Comment by PengyuDeng** [comment]
1.X版本不修改此？
