### ISSUE TITLE
[Bug]v2.4.0版本 :mysql数据源，sql数据集， sql在根据某一个字段join很多的时候，视图只要加了筛选器会报错，数据集和数据源都没有问题

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8429]
安装包安装

MySQL数据源 
 在v2.3.0的时候一样的sql完全没有问题，升级之后，视图不能看了。
这个是报错
![50c168c545080eb2c4704d4ecf62d62](https://github.com/dataease/dataease/assets/141667200/15e4bc0c-9393-4068-8a18-6fce8ab51d05)
根据报错尝试了一下
首先原版完整sql：
select
issues.id `ID`,
issues.subject `标题`,
issues.description `描述`, 
issues.created_on `创建时间`,
 issues.updated_on `更新时间`,
 issues.start_date `开始时间`,
 issues.closed_on `关闭时间`,
trackers.name `跟踪类型`,
projects.name `项目`,
issue_statuses.name `状态`,
versions.`name` `目标版本`,
concat(substring(u1.firstname,1,1),'某') `处理人`,
concat(substring(u2.firstname,1,1),'某') `创建人`,
versions.effective_date `版本日期`,
priority.name `优先级`

from issues

left join trackers on issues.tracker_id = trackers.id
left join projects on issues.project_id = projects.id
left join issue_statuses on issues.status_id = issue_statuses.id
left join users u1 on issues.assigned_to_id = u1.id
left join users u2 on issues.author_id = u2.id
left join versions on issues.fixed_version_id = versions.id
left join
(
select 
id,name 
from enumerations 
where type = 'IssuePriority'

)priority on issues.priority_id = priority.id

排查过程中简化到最简且不会出错的sql：
select
issues.id `ID`,
issues.subject `标题`,
issues.description `描述`, 
issues.created_on `创建时间`,
 issues.updated_on `更新时间`,
 issues.start_date `开始时间`,
 issues.closed_on `关闭时间`,
trackers.name `跟踪类型`,
projects.name `项目`,
issue_statuses.name `状态`

from issues
left join trackers on issues.tracker_id = trackers.id
left join projects on issues.project_id = projects.id
left join issue_statuses on issues.status_id = issue_statuses.id

根据原来的sql，只要在加上一个join，数据集啥的都没问题，视图加了筛选器筛多个值就会报如上图所示的错误。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
