### ISSUE TITLE
[Feature] dataease v2 支持组合图

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#8430]
DataEase 版本:
DataEase v2

**请描述您的需求或者改进建议.**
dataease v2 支持组合图、支持堆叠柱状图与折线图组合

**Comment by xuwei-fit2cloud** [comment]
该需求已在资源池中。

**Comment by IversonJay** [comment]
> 该需求已在资源池中。

请问一下，这个功能预计哪个版本或者多久可以上线呢？
