### ISSUE TITLE
[Bug]仪表板-文本搜索框无法搜索到百分号%

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#8432]
**DataEase 版本**
v1.18.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包
**浏览器版本**
版本 122.0.2365.80 (正式版本) (64 位)

**Bug 描述**
仪表板-文本搜索框无法搜索到百分号%

**Bug 重现步骤(有截图更好)**
1.在仪表板中添加文本搜索框
2.输入%搜索
3.无法搜索到包含%的数据内容

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本就行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
