### ISSUE TITLE
[Feature]使用查询按钮时，希望不显示搜索框的搜索按钮，不使用查询按钮时再显示搜索框的按钮

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#8433]
DataEase 版本:
1.18.15

**请描述您的需求或者改进建议.**
在仪表板中使用查询按钮时，希望不再显示搜索框的搜索按钮（类似变成只显示一个文本框），因为此时点击该按钮也不会生效，反而会引起误会。当不使用查询按钮时再显示搜索框的按钮。
客户的实际场景：给领导查看仪表板时，发现点击了搜索框的查询按钮不生效。
![image](https://github.com/dataease/dataease/assets/77324661/fcc476c5-0840-4d12-8727-0079d3c389c9)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，已经纳入开发计划。
