### ISSUE TITLE
[Feature]仪表板-横柱图字段文本过长时，会挤压柱图的空间

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#8438]
DataEase 版本:
1.18.15

**请描述您的需求或者改进建议.**
仪表板-横柱图字段文本过长时，会挤压柱图的空间，且不能通过新建计算字段截取文本的方式实现，因为由于客户的数据必须做到准确无误的完整显示。对于客户来说少一位字符都是错误数据。因此希望能有个鼠标滑过效果展示完整数据，并且可以配置最大展示字符位数，多余的用省略号表示。
![image](https://github.com/dataease/dataease/assets/77324661/e069ead4-20d6-4ed0-b502-d5eec7cc9e1b)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先讨论一下可行性。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
