### ISSUE TITLE
[Question]数据库版本。MySQL 5.7.20

### ISSUE THREAD

**Issue by ElapsedSoul** [dataease/dataease#844]
**请描述您的问题.**
### Cause: java.sql.SQLException: Row 28 was cut by GROUP_CONCAT()

**Comment by xuwei-fit2cloud** [comment]
这是MySQL参数问题，可以参考在线文档https://dataease.io/docs/faq/configuration_faq/#dataease-row-30153-was-cut-by-group_concat
