### ISSUE TITLE
[Feature]仪表板-地图调节那个图示的字体颜色无法改变

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#8442]
DataEase 版本:
1.18.15

**请描述您的需求或者改进建议.**
仪表板-地图调节那个图示的字体颜色目前无法改变，希望可以自定义配置，更好的与各种背景颜色适配。
![1710148358836](https://github.com/dataease/dataease/assets/77324661/945bde92-fa53-4cd3-978d-de729eacc8a7)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，已纳入需求池，我们先讨论一下。
