### ISSUE TITLE
[Feature]仪表板-下钻面包屑文字的颜色不可以更改

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#8443]
DataEase 版本:
1.18.15

**请描述您的需求或者改进建议.**
仪表板-下钻面包屑文字的颜色目前不可以更改，希望支持更改其颜色，更好的适合各种色系的背景色
![image](https://github.com/dataease/dataease/assets/77324661/cc4f90cc-678a-4c71-a67b-c29de138f7b5)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，已纳入需求池，我们先讨论一下。
