### ISSUE TITLE
[Feature]明细表图表，表头的排序可以配置开关

### ISSUE THREAD

**Issue by Arhang123** [dataease/dataease#8446]
DataEase 版本:v1.18.15

**请描述您的需求或者改进建议.**
明细表图表，表头的排序可以配置开关
![47f9b60def8f7f4584fbc8d93bfa008](https://github.com/dataease/dataease/assets/52651631/fb06ece4-3cd2-4d95-b2b0-de20a79f9aea)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已经规划在下个版本（v1.18.17）中实现，还请多加关注release notes 。

同issue：https://github.com/dataease/dataease/issues/8113 ，因此该issue这边就先关闭了，再次感谢您的反馈和支持。
