### ISSUE TITLE
[Feature]仪表板-富文本框内引用的数据字体无法修改颜色

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#8447]
DataEase 版本:
2.3

**请描述您的需求或者改进建议.**
v2版本，仪表板-富文本框内引用的数据字体无法修改颜色
![image](https://github.com/dataease/dataease/assets/77324661/13462ed4-8d55-465c-8f96-936313469ef9)

**Comment by xuwei-fit2cloud** [comment]
这个是支持修改颜色的，只是字段选中状态有点不明显，我们后续版本优化一下。

![图片](https://github.com/dataease/dataease/assets/1892127/76078b55-db58-4725-8673-efa232ef7f17)

**Comment by ziyujiahao** [comment]
功能已添加 https://github.com/dataease/dataease/pull/8560
