### ISSUE TITLE
[Bug]使用v2.3版本的源码，前端编译失败

### ISSUE THREAD

**Issue by wat1r** [dataease/dataease#8449]
**DataEase 版本**
v2.3

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome

**Bug 描述**

**Bug 重现步骤(有截图更好)**

在 core目录下执行：`mvn clean package -Pstandalone -U -Dmaven.test.skip=true`

<img width="887" alt="image" src="https://github.com/dataease/dataease/assets/20732599/c0e27a2a-a9f2-4cda-9162-c8a6b142bd04">

npm config get registry
https://registry.npm.taobao.org/

 pnpm --version
8.15.4

这个安装注意事项：注意：编译前端代码如果出现网络问题导致编译失败，可以将 npm 镜像源换为淘宝镜像源，并使用 pnpm 进行编译。手动编译前端，将下图前端 pom 文件相关插件注释,然后再执行 mvn clean package -Pstandalone -U -Dmaven.test.skip=true。

指的是是在core-frontend下执行 `mvn clean package -Pstandalone -U -Dmaven.test.skip=true` ?

可以将 npm 镜像源换为淘宝镜像源，并使用 pnpm 进行编译 这个需要改什么？pom里的excution标签的内容要改？

**Comment by maninhill** [comment]
请参考：https://dataease.io/docs/v2/installation/deployment_installation/

**Comment by wat1r** [comment]
参考的是上述贴出来的链接，编译失败
