### ISSUE TITLE
[Feature]  数据源密码在接口中是明文传输的，存在安全漏洞，建议改为密文传输

### ISSUE THREAD

**Issue by you10906** [dataease/dataease#845]
**请描述您的需求或者改进建议.**

当前版本（v1.1.2）中数据源密码在接口中是明文传输的，存在安全漏洞，建议改为密文传输

**Comment by yayanpei** [comment]
非常感谢您的反馈，该需求已规划在后期的版本中进行优化。

**Comment by tjlygdx** [comment]
请配置https，保证数据传输安全
