### ISSUE TITLE
[Feature]【数据源】希望支持 ADB（for MySQL）数据源连接

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#8453]
DataEase 版本:
希望支持 ADB（for MySQL）数据源连接
详见此 issue：https://github.com/dataease/dataease/issues/8278

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
我们先调研一下。

**Comment by AndroidBaby1** [comment]
不好意思，信息填写错误，当前 DataEase 支持 ADB for MySQL。DataEase 真的简单易用，在公司推动也很成功，祝越来越好！
