### ISSUE TITLE
以es sql 使用group查询作为数据源报错

### ISSUE THREAD

**Issue by habbyCP** [dataease/dataease#8454]
**DataEase 版本**

1.18.15
**运行方式(安装包运行 or 源码运行 ?)**
镜像运行

**浏览器版本**
chrome  122.0.6261.112

**Bug 描述**
以es作为数据源，通过group聚合查询做数据集，在编辑sql数据集页面可以查处数据，
在数据集数据预览界面报错。
在仪表盘添加此数据集报错

**Bug 重现步骤(有截图更好)**
1. 以es作为数据源，以某个字段group查询聚合。
2. 保存返回到数据预览界面报错 
<img width="1028" alt="image" src="https://github.com/dataease/dataease/assets/7379786/cde64ab1-8fec-468b-9d60-f89e8e611247">
4.进入某一个看板，添加此数据集报错。
<img width="1033" alt="image" src="https://github.com/dataease/dataease/assets/7379786/e1dc4cf1-e96b-4b1f-bd1f-904a91a4eb28">

**Comment by BBchicken-9527** [comment]
感谢反馈，请问是否是text类型字段，目前暂时不支持text类型字段的聚合；

**Comment by habbyCP** [comment]
> 感谢反馈，请问是否是text类型字段，目前暂时不支持text类型字段的聚合；

意思就是我如果是text类型的聚合就有问题？2.*版本有这个问题吗？

**Comment by tangguangliang** [comment]
> > 感谢反馈，请问是否是text类型字段，目前暂时不支持text类型字段的聚合；
> 
> 意思就是我如果是text类型的聚合就有问题？2.*版本有这个问题吗？

2.0版本还没有接入es数据源查询

**Comment by habbyCP** [comment]
> > > 感谢反馈，请问是否是text类型字段，目前暂时不支持text类型字段的聚合；
> > 
> > 
> > 意思就是我如果是text类型的聚合就有问题？2.*版本有这个问题吗？
> 
> 2.0版本还没有接入es数据源查询

不是不能查询，是我可以查询，在数据集可以查询出来，在看板里面是用这个数据集就报错

**Comment by habbyCP** [comment]
> > > > 感谢反馈，请问是否是text类型字段，目前暂时不支持text类型字段的聚合；
> > > 
> > > 
> > > 意思就是我如果是text类型的聚合就有问题？2.*版本有这个问题吗？
> > 
> > 
> > 2.0版本还没有接入es数据源查询
> 
> 不是不能查询，是我可以查询，在数据集可以查询出来，在看板里面是用这个数据集就报错

1.* 版本

**Comment by BBchicken-9527** [comment]
感谢反馈，明细表呢？明细表是没有聚合的应该是可以正常显示，其他的图表都会因为维度的影响导致聚合从而出现错误；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
