### ISSUE TITLE
[Bug]视图过滤器，Doris数据库，整型筛选失效

### ISSUE THREAD

**Issue by boolean-dev** [dataease/dataease#846]
**DataEase 版本**
v1.2 分支，节点ID：3cb889a4

**浏览器版本**
Microsoft Edge
版本 93.0.961.52 (官方内部版本) (64 位)

**Bug 描述**
1. 数据来源来自于 Doris，我要进行 id  < 20 的条件筛选，可以把条件加上后，无法生效
![image](https://user-images.githubusercontent.com/20177406/134298360-56ece821-f127-4a95-bcca-c4d88d75a2f6.png)
2. 在 Debug 的时候，发现 `DorisQueryProvider` 在进行拼接查询 SQL时，将过滤条件拼接成了 `T_A_0.`C_b718adec73e04ce3ec720dd11a06a308`  < '20'` ，导致查询条件失效
3. nacivat sql 执行结果
 
![image](https://user-images.githubusercontent.com/20177406/134299050-f010e1b5-7dd4-44b6-8500-1c8ca1dadacf.png)
改成 20 后，结果执行正常
![image](https://user-images.githubusercontent.com/20177406/134299101-bf039548-6fd9-4b96-a08f-182861139f93.png)

 
**Bug 重现步骤(有截图更好)**
1.数据表结构
![image](https://user-images.githubusercontent.com/20177406/134299302-5b89d0e3-8b5e-4300-9290-b80062999774.png)

2. 过滤条件
![image](https://user-images.githubusercontent.com/20177406/134299310-6050aeef-aff9-4842-b007-ac14a73b0449.png)

3. SQL 截图
![image](https://user-images.githubusercontent.com/20177406/134299380-a2d1067c-4962-457c-a0f3-26a8f90c27a0.png)

4. 源码截图 `DorisQueryProvider.transExtFilterList`
![image](https://user-images.githubusercontent.com/20177406/134299530-15148a4e-532b-4ba5-894d-3fdcdd088a0d.png)

**Comment by xuwei-fit2cloud** [comment]
v1.4.0 版本已修复
