### ISSUE TITLE
内网环境源码方式部署之后，通过上传模板或者应用使用时候有部分图片无法加载

### ISSUE THREAD

**Issue by shuyixiao-better** [dataease/dataease#8477]
内网环境源码方式部署之后，通过上传模板或者应用使用时候有部分图片无法加载

**Comment by maninhill** [comment]
因为环境不可控，我们难以重现，请自行排查，或者提供更多日志之类的信息。

**Comment by shuyixiao-better** [comment]
> 因为环境不可控，我们难以重现，请自行排查，或者提供更多日志之类的信息。

请问一下就是仪表版的静态资源文件是都是在线获取的吗还是只要应用的模板都是直接存储到本地的，导出应用和模板时候也是整个资源都导出吗？
