### ISSUE TITLE
[Bug] CK语法检测异常

### ISSUE THREAD

**Issue by heartInGod** [dataease/dataease#8479]
![img_v3_028t_d6fdec8f-4c25-40ea-af7d-7f9cc0295bdg](https://github.com/dataease/dataease/assets/30049098/6d764d04-adcc-4e66-88b9-4e2eedf9a9cf)

SELECT 
    npc_create_date,
    COUNT(DISTINCT case when npc_expose_uv_30day >= 200 then npc_id end) AS success_cnt,
    COUNT(DISTINCT npc_id) AS npc_cnt 
FROM 
    xingye_new_author_npc_activation_stats 
GROUP BY 
    npc_create_date

**Comment by BBchicken-9527** [comment]
感谢反馈，因为V2版本使用了calcite中间件，calcite会主动的优化输入的sql导致，我们将会在后续版本进行修复；

**Comment by maninhill** [comment]
v2.6 单数据源已经支持原生 jdbc sql
