### ISSUE TITLE
[Feature]视图中日期显示格式支持季度

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#8481]
DataEase 版本:
1.18 2.4

**请描述您的需求或者改进建议.**
视图中日期显示格式支持季度
![image](https://github.com/dataease/dataease/assets/101089844/2e2a746e-e841-4425-9272-c864d17f1a1e)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
我们会在后期分数据源进行支持。
