### ISSUE TITLE
[Bug]报错提示的在线文档参考链接失效，缺少版本

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#8483]
**DataEase 版本**

v1.18.16
**运行方式(安装包运行 or 源码运行 ?)**
安装包

**Bug 描述**
由于在线文档有 v1 和 v2 ，文档的链接发生变化，需要在 docs 后加版本 v1，如 https://dataease.io/docs/v1/user_manual/general/

**Bug 重现步骤(有截图更好)**
![wecom-temp-1311803-7cf7253bc2fd0e8af7ed79597829f9ba](https://github.com/dataease/dataease/assets/127368807/b6cd4ff4-848e-4ce9-a2c2-27d842902e0e)

**Comment by xuwei-fit2cloud** [comment]
已修复，请等待新版本发布。
