### ISSUE TITLE
[Bug]sql数据源和Excel数据源：数据集左连接不行只能右连接。Excel数据源的第一列的值，就是sql数据源a表里status的值，使用左关联链接，无法显示Excel数据，只能使用右关联才可以

### ISSUE THREAD

**Issue by huangxine** [dataease/dataease#8493]
**DataEase 版本**
V2.4版本

**运行方式(安装包运行 or 源码运行 ?)**
标准安装

**浏览器版本**
Chrome浏览器，122版本

**Bug 描述**
[Bug]sql数据源和Excel数据源：数据集左连接不行只能右连接。Excel数据源的第一列的值，就是sql数据源a表里status的值，使用左关联链接，无法显示Excel数据，只能使用右关联才可以

**Bug 重现步骤(有截图更好)**
1.设置左连接及链接字段
![image](https://github.com/dataease/dataease/assets/78218624/3ef5b9ad-efd8-408b-b701-3e4d0d37dfd9)

2.左连接刷新数据，此时没有Excel相关数据

![image](https://github.com/dataease/dataease/assets/78218624/dd258b58-af24-43fa-bf62-60170d03d8e1)

3.链接方式改为右连接
![image](https://github.com/dataease/dataease/assets/78218624/e27abe2a-d97c-42d4-893f-b2daa1cbee6d)

4.右连接刷新数据
![image](https://github.com/dataease/dataease/assets/78218624/762ba18f-afab-48ba-8005-c9ae9b92bdf3)

5.使用的Excel文件
[bm_demand_type.xlsx](https://github.com/dataease/dataease/files/14595951/bm_demand_type.xlsx)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行修复；
