### ISSUE TITLE
[Feature]希望增加折线图异常数据标记颜色功能

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#8495]
DataEase 版本:
1.18

**请描述您的需求或者改进建议.**
希望增加折线图异常数据标记功能，异常数据值可以自定义设置颜色、字体加粗，这样看起来一目了然

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先调研下图库是否支持。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈和支持，我们先加入需求池中，近3个月暂时没有计划进行支持。
