### ISSUE TITLE
[Bug] Doris 直接导入的数据集字段类型映射有误，使用关联数据集或SQL数据集后数据类型恢复正常

### ISSUE THREAD

**Issue by PeatBoy** [dataease/dataease#8496]
**DataEase 版本**
1.18.13
**Doris 版本**
doris-2.0.3-rc06

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome  122.0.6261.112（正式版本） (arm64)

**Bug 描述**
Dataease 中使用 数据库数据集 导入 Doris 数据后，数据类型映射有误（全部映射为文本）
![image](https://github.com/dataease/dataease/assets/64261406/6f2f456d-1d73-4802-9d49-ec3166d30067)
在其基础上，使用 关联数据集 后，数据类型恢复正常
![image](https://github.com/dataease/dataease/assets/64261406/40c17cc2-5fd3-4503-9799-ef398598002b)
Doris 中的字段类型
![image](https://github.com/dataease/dataease/assets/64261406/e1f96daa-7565-4bc7-949b-45103d58f13f)

**Bug 重现步骤(有截图更好)**
1. 连接 Doris 并在数据集中导入数据表
2. 查看 DECIMAL 类型是否被正确解析为 数值
3. 创建 关联数据集 查看 DECIMAL 类型是否被正确解析为 数值

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的数据类型不对的问题，我尝试了直连和定时同步两种方式，我看你使用的版本还是在1.18.13，可以尝试升级看一下问题获取得到了解决；
定时同步任务：
![image](https://github.com/dataease/dataease/assets/84372766/ba53f9af-6d51-4cf5-8131-d3a9ea5e964f)
直连：
![image](https://github.com/dataease/dataease/assets/84372766/0494fd68-64ee-41b5-b601-3a220396033f)

**Comment by maninhill** [comment]
长时间未反馈，请升级到最新版本。我们先关闭，如还有问题，请再重新打开。
