### ISSUE TITLE
[Bug]数据集文本脱敏问题

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#8498]
**DataEase 版本**
1.18.16

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome、版本 122.0.2365.80 (正式版本) (64 位)

**Bug 描述**
数据集文本脱敏后，文本内容全都不显示了

**Bug 重现步骤(有截图更好)**
1.数据集-行列权限设置脱敏
2.选择XXX***XXX脱敏规则
3.在仪表板中文本内容全都不显示了
![image](https://github.com/dataease/dataease/assets/77324661/797d44ee-4a88-4390-b142-5180286635f8)
![e0557f470b9386b34beb38b880e552b](https://github.com/dataease/dataease/assets/77324661/995ccaea-75de-43f2-8fc6-242d43a5ebb6)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前脱敏规则需要符合规定的字符才可以的，若你没有达到要求的字符限制则显示为实例中的样子，你可以尝试大于五个字符的数据尝试一下；

**Comment by maninhill** [comment]
长时间未反馈，请升级到最新版本。我们先关闭，如还有问题，请再重新打开。
