### ISSUE TITLE
[Feature]官网下载安装包，未标明v2不兼容v1，”旧版本“ 描述概念比较模糊

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#8499]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
 
<img width="412" alt="image" src="https://github.com/dataease/dataease/assets/101089844/47d317f6-5cdf-41e6-aa44-c0d0c648d572">

![3141710385650_ pic](https://github.com/dataease/dataease/assets/101089844/f2203c0a-471d-41b5-8608-6c7161c61f83)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们完善一下相关文档。
