### ISSUE TITLE
[Bug]V2.4版本API数据源使用Post请求报错

### ISSUE THREAD

**Issue by MMM-li** [dataease/dataease#8501]
**DataEase 版本**
v2.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 122.0.6261.95

**Bug 描述**
API数据源无论发送什么POST请求都是报如下错

**Bug 重现步骤(有截图更好)**
1.请求头配置
![image](https://github.com/dataease/dataease/assets/40291028/e9e2896a-5bd6-4d77-ad61-80e7f1c8fb08)
2.请求体配置，认证为No Auth。
![image](https://github.com/dataease/dataease/assets/40291028/75501b05-f45a-40a5-b448-9f8de81a8eef)

**Comment by BBchicken-9527** [comment]
感谢反馈，因为你API具体需要的参数我无法确定，所以没有办法给你更直观的说明，受累你看一下用相同的参数在其他的接口请求工具是否可以正常的获取呢？如postman；

**Comment by maninhill** [comment]
长时间未反馈，请升级到最新版本。我们先关闭，如还有问题，请再重新打开。
