### ISSUE TITLE
[Bug]金山轻维表 API 链接 DataEase，数据显示错行

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#8502]
**DataEase 版本**
v1.18.16

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Microsoft Edge
22.0.2365.80（正式版本）(64位）

**Bug 描述**

金山轻微表API链接DataEase后数据展示是错行的状态

**Bug 重现步骤(有截图更好)**
1.金山表格数据（api调用说明https://developer.kdocs.cn/server/guide/api-overview.html）
![image](https://github.com/dataease/dataease/assets/127368807/6f472848-b3ce-46db-8d4a-73977b7cb010)

2.DataEase的数据，左边是API数据，右边是导出EXCEL上传的，对比可以发现都错行了
![image](https://github.com/dataease/dataease/assets/127368807/ab9a83c0-76b8-440c-b7a9-6ea0aaffc722)

**Comment by BBchicken-9527** [comment]
感谢反馈，因为API数据获取与Excel获取的实现方式是不一样的，Excel二维表格获取方式非常的简单只需要根据指定的位置进行获取即可，但API数据获取是是以json的形式获取的，在获取中假如数据没有保证一致性（存在空）则数据会出现前移的情况的；
