### ISSUE TITLE
[Bug]清除明细表联动后明细表异常

### ISSUE THREAD

**Issue by LuKK351** [dataease/dataease#8503]
**DataEase 版本**
v1.18.16

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行（本地模式）

**浏览器版本**
Edge 标准

**Bug 描述**
使用 API 数据集，在仪表板通过其他图表对明细表进行联动，点击清除联动后，明细表显示异常。

**Bug 重现步骤(有截图更好)**
1.当前仪表板上存在一个明细表（下拉模式）和一个横向柱状图，并设置联动；
![image](https://github.com/dataease/dataease/assets/48945409/ab0f2399-8283-42bd-b044-97be09139efd)

2.点击横线柱状图，明细表被联动；
![image](https://github.com/dataease/dataease/assets/48945409/d1ee48fd-e203-43af-936b-1acf2061db50)

3.点击横线柱状图右上角的“清除联动”按钮；
![image](https://github.com/dataease/dataease/assets/48945409/0a5ae376-8bd6-422d-9f13-9479342bb97c)

4.明细表出现异常。
![image](https://github.com/dataease/dataease/assets/48945409/6a0be33c-5e3d-47a4-828f-ffb64e45e124)

完整录制：
![iShot_2024-03-14_11 39 26](https://github.com/dataease/dataease/assets/48945409/ae98da20-b20d-4200-ab73-bed44064caf0)

相关问题：https://bbs.fit2cloud.com/t/topic/3779

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境中没有发现你上述提到的空指针的问题，因为我这边的接口都是mock出来的，相关的接口信息方便给我一份我看一下嘛？

**Comment by LuKK351** [comment]
http://ip/chart/view/getData/388cac4c-ef3a-4265-bf30-78364d82da3a/f21eb1ba-e1b2-11ee-b1a7-6d2c337fee63
![image](https://github.com/dataease/dataease/assets/48945409/e9109a0b-9e26-4c2c-96f0-37b6b1cc7e8e)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
