### ISSUE TITLE
[Feature]希望折线图支持根据不同类别生成若干图

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#8505]
DataEase 版本:
1.18.16

**请描述您的需求或者改进建议.**
希望像下图这种分组别展示的数据，根据不同的类别，生成以时间和产量的折线图。就是相当于要选三个维度，自动根据不同类别生成若干图。

原始数据：
![image](https://github.com/dataease/dataease/assets/77324661/0bfc583d-9aa9-4c35-a5d0-f3a00a8d3afe)

期望效果：
![image](https://github.com/dataease/dataease/assets/77324661/ea01390f-e8e5-4717-8275-5f2f6915d67d)

DE目前只能先生成一个图表，再复制一个，通过筛选类别再次生成一个

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，如果要根据不同的维度值在折线图中生成不同的线条，建议您做下图所示操作：
<img width="899" alt="image" src="https://github.com/dataease/dataease/assets/84168063/c3e04d68-edc1-4d26-97e9-431931ab6f33">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议您参考下图所示制作折线图。
<img width="912" alt="image" src="https://github.com/dataease/dataease/assets/84168063/6f6c4881-a9bc-4a91-b2d6-c0dc5f7e1758">
