### ISSUE TITLE
选项有NULL值会出现快闪[Bug]

### ISSUE THREAD

**Issue by lily-arya** [dataease/dataease#8506]
**DataEase 版本**
1.18.16

**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**
Google Chrome  版本 122.0.6261.112

**Bug 描述**
选项下拉出现快闪，过滤NULL值后正常

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，你说的快闪是视窗出现抖动的意思吗？

**Comment by maninhill** [comment]
长时间未反馈，请升级到最新版本。我们先关闭，如还有问题，请再重新打开。
