### ISSUE TITLE
[Feature]透视表中左侧大项提供折叠，否则一项就沾满了一页，可读性差

### ISSUE THREAD

**Issue by huangxine** [dataease/dataease#8509]
DataEase 版本:
v2.4

**请描述您的需求或者改进建议.**
透视表中左侧大项提供折叠，否则一项就沾满了一页，可读性差
![image](https://github.com/dataease/dataease/assets/78218624/8399336f-71ce-4956-844c-ae3b482a2f7b)
![image](https://github.com/dataease/dataease/assets/78218624/207d9b16-bda8-4129-a62c-af89f6f219c3)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，已纳入开发计划。
