### ISSUE TITLE
[Feature] 视图中支持多维的折线图

### ISSUE THREAD

**Issue by pcr1234567** [dataease/dataease#851]
缺失了一个很普遍的图表类型，现在的折线图目前只支持显示一条线，希望能尽快支持多条线的多维折线图，感谢！
类似这种：
![image](https://user-images.githubusercontent.com/26478675/134321025-58c95c3c-7045-4fd7-9c52-23558fe9a7a8.png)

**Comment by yayanpei** [comment]
目前的折线图是支持多折线的，如下图所示，将多个指标拖入【值轴 / 指标】即可，再次感谢您的关注和使用。
![image](https://user-images.githubusercontent.com/84168063/134324853-d261ff60-00f7-49ec-9649-f8daba01730b.png)

**Comment by pcr1234567** [comment]
就比如你们demo中的那个销售品牌的例子，如何把四个部门的销售额放在同一个折线图里去纵向比较呢？ 我看到现在都只能通过过滤的方式一个一个的筛选出来

**Comment by pcr1234567** [comment]
@yayanpei 
![image](https://user-images.githubusercontent.com/26478675/134442096-8a8b03dd-c158-4ae0-8a25-c7eae7b25f08.png)
补充我上面说的场景截图，或者说一个视图能否支持导入多个数据集？

**Comment by yayanpei** [comment]
如果每根折线代表一个部门的销售额，那么每个部门的销售额均需要作为一个指标，建议您调整数据集的格式，如下图：
![image](https://user-images.githubusercontent.com/84168063/134444750-16b0ade7-fe81-4641-a893-ff2eec2b340a.png)
