### ISSUE TITLE
[Bug]使用关联数据集，自定义SQL数据集关联excel数据集，自定义SQL数据集中文字转时间格式报错

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#8510]
**DataEase 版本**
v2.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
无论哪种数据集，关联数据集中，文字转时间格式报错使用关联数据集，自定义SQL数据集关联excel数据集，自定义SQL数据集中文字转时间格式报错
**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/101089844/695b5241-3cb5-4682-880a-cef44bc8ac79)

2.
![image](https://github.com/dataease/dataease/assets/101089844/0cc7d2b4-7c50-49e3-b07c-6798f2214fa8)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行修复；

**Comment by maninhill** [comment]
v2.10-lts 版本已经发布，请在最新版本上面验证，有问题请 re-open。
