### ISSUE TITLE
[Bug]v1.18.16版本AntV透视表视图错乱,老版本正常（v1.18.13）

### ISSUE THREAD

**Issue by winterbells07** [dataease/dataease#8514]
**DataEase 版本**
v1.18.16

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行，数据源：Sql Server

**浏览器版本**
chrome 103.0.5060.114（正式版本） （64 位）
测试多个浏览器同样问题

**Bug 描述**
AntV透视表视图，加了筛选组件+数据列 / 指标添加了视图计算字段

**Bug 重现步骤(有截图更好)**
1.
![微信截图_20240314142852](https://github.com/dataease/dataease/assets/56105196/f9c13248-b31c-444d-939c-1f4ee04f283a)
2.
![微信截图_20240314143125](https://github.com/dataease/dataease/assets/56105196/38926357-dd9c-48c9-b345-ac2b0d01f991)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，方便看一下控制台是否存在异常的情况呢？

**Comment by maninhill** [comment]
长时间未反馈，请升级到最新版本。我们先关闭，如还有问题，请再重新打开。
