### ISSUE TITLE
[Feature]建议新增象限图

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#8517]
DataEase 版本:
V2.0

**请描述您的需求或者改进建议.**
希望能够支持如下图所示的象限图
<img width="678" alt="image" src="https://github.com/dataease/dataease/assets/60059766/9f42b26a-99b2-44fa-8e1b-1ea0000d8cf2">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先调研并思考一下具体的需求设计。

**Comment by maninhill** [comment]
已经支持。
