### ISSUE TITLE
[Feature]支持视图拖动保存顺序或者排列顺序

### ISSUE THREAD

**Issue by liuchangfitcloud** [dataease/dataease#852]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/44662176/134321186-f11427c9-2bd8-4870-9e1a-84b987751cfa.png)

**Comment by yayanpei** [comment]
非常感谢您的反馈，我们需要先内部讨论下。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
