### ISSUE TITLE
[Feature]地图组件修改建议

### ISSUE THREAD

**Issue by winterbells07** [dataease/dataease#8521]
DataEase 版本:

**请描述您的需求或者改进建议.**
中国地图南海11段线参考国家标准地图以小图形式展示
![微信截图_20240314160513](https://github.com/dataease/dataease/assets/56105196/7e73ed64-389e-47bd-b4c2-a1ef1f371d5a)

![4o28b0625501ad13015501ad2bfc0045](https://github.com/dataease/dataease/assets/56105196/4e056e64-1378-4388-9e3e-5ba9dc6e67a6)

国家标准地图，图片来源：http://bzdt.ch.mnr.gov.cn/

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先调研一下图库是否支持。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，近期暂时没有计划进行支持。
