### ISSUE TITLE
[Question] 树状图是在哪个版本支持的

### ISSUE THREAD

**Issue by heartInGod** [dataease/dataease#8522]
<img width="314" alt="image" src="https://github.com/dataease/dataease/assets/30049098/2ffa4ad3-c6ec-4fae-8dc2-561ccd2ae76b">
我在2.3只能选择左边或者右边。我想使用下面这个双轴功能
![image](https://github.com/dataease/dataease/assets/30049098/f63e77bf-aa72-474d-bb8e-d8c7a670a42f)

**Comment by heartInGod** [comment]
<img width="898" alt="image" src="https://github.com/dataease/dataease/assets/30049098/4b5987f7-4946-4be2-abb2-c70b23376180">

**Comment by maninhill** [comment]
这个你可以自行搜索下提交记录。
