### ISSUE TITLE
[Question]v2.4.1Docker

### ISSUE THREAD

**Issue by zzx769394358** [dataease/dataease#8527]
**请描述您的问题.**
从git上下的v2.4分支，然后执行docker打包：
<img width="931" alt="image" src="https://github.com/dataease/dataease/assets/57294442/77431871-8812-4e90-86ab-7a0891189495">

**Comment by maninhill** [comment]
请参考这个文档：https://dataease.io/docs/v2/installation/deployment_installation/

**Comment by zzx769394358** [comment]
> 请参考这个文档：https://dataease.io/docs/v2/installation/deployment_installation/

完全按照文档，core-front的pom有关代码注释前后都是这个错

<img width="569" alt="image" src="https://github.com/dataease/dataease/assets/57294442/58f1f489-3ee1-4c3a-bd8f-3a938bc5f33f">

**Comment by jnfJNF** [comment]
我也遇到了，请问怎么解决呢？

**Comment by jnfJNF** [comment]
我也遇到了，请问怎么解决呢？
