### ISSUE TITLE
[Bug]360浏览器适配

### ISSUE THREAD

**Issue by haohaoyizheng** [dataease/dataease#853]
**DataEase 版本**
V1.2.0

**浏览器版本**
360浏览器SE13.1版本

**Bug 描述**
360浏览器中 仪表板-编辑-“组件”和“其他”的logo展示适配有问题。

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/56429047/134321109-42022b46-66f3-4ab2-bb1f-b24dcc82ad88.png)

**Comment by xuwei-fit2cloud** [comment]
浏览器的适配我们会在后续逐步加上，在前期还是建议大家使用Chrome，Firefox等浏览器

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
