### ISSUE TITLE
[Feature]关于 v2 SQL 数据集引擎的问题

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#8532]
DataEase 版本:
v2

v2 版本使用 Calcite 连接数据源，现在产生两类问题：
1. 因为语法问题，导致用户需要花大量的时间调试 SQL；
2. Calcite 支持跨库关联，但是在 DE 中考虑到权限问题，不支持 “库.表” 的写法，导致不能通过 SQL 一次完成跨库关联。 

探讨建议：
能否加一个直连方式的数据集，使用直连方式直连数据源，没有跨源关联、关联数据集等功能，只有一个直连查询的功能；
考虑用户与数据源的权限，可以给用户授权是否有权限使用直连查询的功能。

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们正在尝试支持根据不同数据库支持自身函数的技术方案，请等待后续版本。

**Comment by maninhill** [comment]
v2.6 单数据源已经支持原生 jdbc sql
