### ISSUE TITLE
[Feature]【视图】组合图双轴保持零刻度同一水准

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#8533]
DataEase 版本:
v1

**请描述您的需求或者改进建议.**
当前：
![image](https://github.com/dataease/dataease/assets/24768910/b0812bfe-e0f4-42cf-9dbe-2de975c9b3a5)
期望：
![image](https://github.com/dataease/dataease/assets/24768910/2442bb70-3039-4a53-8948-041eedb0c1b4)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先调研一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，组合图是两个图层的叠加，因此刻度是各自计算的，目前零刻度无法保持同一水准。
