### ISSUE TITLE
[Feature]【视图】明细表排序按钮支持隐藏

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#8535]
DataEase 版本:
v1

**请描述您的需求或者改进建议.**
<img width="915" alt="image" src="https://github.com/dataease/dataease/assets/24768910/8216ea93-bf9c-439e-9891-87af7a2ec19d">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已经规划在 v1.18.17 中，正在开发中。

同issue：https://github.com/dataease/dataease/issues/7978。 这边就先关闭了，再次感谢您的反馈和支持。
