### ISSUE TITLE
[Feature]增加数字翻滚效果，类似双十一淘宝交易数据滚动，计数器翻滚

### ISSUE THREAD

**Issue by dami000111** [dataease/dataease#8537]
DataEase 版本:V1
![image](https://github.com/dataease/dataease/assets/163497744/9e696535-3f1c-48ad-82e0-dfd46a5dede5)

增加数字翻滚效果，类似双十一淘宝交易数据滚动，计数器翻滚， 定时刷新滚动 及颜色定义

![592a953ff5aaf31a97de99ce9ef6df59c792fa54](https://github.com/dataease/dataease/assets/163497744/4be305c5-ef68-47d8-8857-efd54f1d6619)

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，该需求已经在技术调研排期中。
