### ISSUE TITLE
[Bug]【视图】ClickHouse DateTime 时间格式的字段用“年月日时分秒”格式显示异常

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#8538]
**DataEase 版本**
1.18.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
【视图】高版本的 ClickHouse DateTime 时间格式的字段用“年月日时分秒”格式显示异常

**Bug 重现步骤(有截图更好)**
1.ClickHouse v22.1.3.7 以及 v22.7.2.15 版本显示正常。
2.ClickHouse  v24.2.1 和 v23.12.4.15 有这个问题，具体显示如下：
![image](https://github.com/dataease/dataease/assets/24768910/e561bbae-3c14-4df9-a24b-2755866d7a44)

**Comment by 1782007694** [comment]
请问您解决了吗

**Comment by PengyuDeng** [comment]
> 请问您解决了吗

没

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将在下个版本进行修复；

**Comment by PengyuDeng** [comment]
我查看离线安装包 v1.18.21都有了，请问这个BUG是修复了吗？

**Comment by maninhill** [comment]
v2.10-lts 版本已经发布，请在最新版本上面验证，有问题请 re-open。

**Comment by PengyuDeng** [comment]
1.X版本不能迁移到2.X吧
