### ISSUE TITLE
[Bug]通过分享链接进入仪表盘页面时，排序点击无效

### ISSUE THREAD

**Issue by YouShf** [dataease/dataease#8543]
**DataEase 版本**
2.4.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome 122.0.6261.128

**Bug 描述**
通过分享链接进入仪表盘页面时，排序点击无效

**Bug 重现步骤(有截图更好)**
1.仪表板点击分享生成链接
2.通过分享链接进入到页面
3.点击表格列头的排序图标无响应
![image](https://github.com/dataease/dataease/assets/43171544/bac5ee67-9ff6-4ab2-8f3d-30e307cf52fa)

**建议可以增加一个是否显示表头排序的选项**

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，已在计划中。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
