### ISSUE TITLE
[Feature]仪表板筛选条件发生变化时就加载数据

### ISSUE THREAD

**Issue by YouShf** [dataease/dataease#8544]
DataEase 版本:
2.4.0

**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/43171544/68b2a4fa-6c7c-41f3-8227-29eb37504f88)

建议可以在选项发生变化时就自动加载数据，不需要点击查询后再加载，可以减少一步操作，提升用户体验~

**Comment by xuwei-fit2cloud** [comment]
因为查询组件可以添加一组查询条件，当其中一个选项变化就自动加载数据的话，会造成不必要的重复请求，所以暂时还是保持现在的设计。
