### ISSUE TITLE
[Bug]编译出错，缺包。。。。

### ISSUE THREAD

**Issue by huguiqi** [dataease/dataease#8545]
**DataEase 版本**

2.4.1

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**

**Bug 描述**
core模块下的core-back，就是缺包

**Bug 重现步骤(有截图更好)**

<img width="1495" alt="image" src="https://github.com/dataease/dataease/assets/490617/59507e47-7f93-4780-ac30-77bd69426ad9">

**Comment by xuwei-fit2cloud** [comment]
您可以参考一下下面的文档：
https://dataease.io/docs/v2/installation/deployment_installation/
