### ISSUE TITLE
[Bug]修改了数据显示名称，但是在透视图表头还是原来字段描述。

### ISSUE THREAD

**Issue by huangxine** [dataease/dataease#8546]
**DataEase 版本**
2.4

**运行方式(安装包运行 or 源码运行 ?)**
标准安装

**浏览器版本**
Chrome122

**Bug 描述**

修改了数据显示名称，但是在透视图表头还是原来字段描述。
**Bug 重现步骤(有截图更好)**
1.
![5d15de674bcf8dd6c412042b6c58622](https://github.com/dataease/dataease/assets/78218624/d229fbac-c94e-47e8-8c4f-e5b625b81d6d)

2.
3.

**Comment by huangxine** [comment]
刷新过数据，也刷新过页面，描述都没有变化

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
