### ISSUE TITLE
[Bug]透视表>>>>样式>>>>行汇总设置了排序，保存刷新数据，透视表无实现排序

### ISSUE THREAD

**Issue by huangxine** [dataease/dataease#8550]
**DataEase 版本**
V2.4

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome122

**Bug 描述**
[Bug]透视表>>>>样式>>>>行汇总设置了排序，保存刷新数据，透视表无实现排序

**Bug 重现步骤(有截图更好)**
1.
2.
![1710496494719](https://github.com/dataease/dataease/assets/78218624/3b055b46-3007-4119-845a-ab833862cf20)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，行总计在表格的最下方；

**Comment by maninhill** [comment]
长时间未反馈，请升级到最新版本。我们先关闭，如还有问题，请再重新打开。
