### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by wt7060** [dataease/dataease#8561]
**DataEase 版本*V1.18.17*

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Google Chrome  122.0.6261.129

**Bug 描述**
新建Oracle数据源时，无法连接到Oracle 11G数据库，使用默认驱动无法连接，使用自定义驱动也连接失败。

**Bug 重现步骤(有截图更好)**
选择Schema时候报错。
![image](https://github.com/dataease/dataease/assets/30554104/6b7bd993-9116-4ec5-8ee1-1afc872b5b22)

**Comment by xuwei-fit2cloud** [comment]
麻烦您帮忙确认一下：
1. 该Oracle服务器是否能被DataEase服务访问
2. 数据源中的相关配置信息是否正确
3. 防火墙策略是否允许访问

**Comment by wt7060** [comment]
> 麻烦您帮忙确认一下：
> 
> 1. 该Oracle服务器是否能被DataEase服务访问
> 2. 数据源中的相关配置信息是否正确
> 3. 防火墙策略是否允许访问

可以的，使用例如DataGrip，PL/SQL都可以正常访问，但是使用DataEase就无法连接和访问，我也不知道问题出在哪里了。

**Comment by wt7060** [comment]
我使用DataGrip的Service Name的连接类型，可以正常连接和访问数据，我们的DataEase没有相关的配置，无法选择连接类型来配置数据库连接，以下是我的连接测试截图：
![image](https://github.com/dataease/dataease/assets/30554104/f18a75f1-f38f-42c5-a966-882a4655c0b7)
![image](https://github.com/dataease/dataease/assets/30554104/a64aec76-84fb-423f-b671-3a3969dd9d8a)

以上，感谢。

**Comment by xuwei-fit2cloud** [comment]
这个异常信息是网络异常，还不是驱动程序的问题，所以还请确认一下诸如连接字符串、数据库连接池配置、网络可达性等其他情况呢，我们这边暂时也没有其他建议。

**Comment by wt7060** [comment]
![image](https://github.com/dataease/dataease/assets/30554104/d9fae03f-2c06-4c51-a412-bfa8e4f25e13)
主要是我没有在页面上看到连接字符串等配置选项呢，目前我的版本是V1.18.17版本，上面没有连接字符串等配置呢，而且我使用的是同一台计算机来连接数据库，我用DataGrip就可以成功连接上，但是我用咱们的DataEase配置页面配置数据库连接就失败，所以到现在我依然不知道问题出在哪里了，如果我们的数据库服务器配置问题，和网络问题，那么不应该我在同一台计算机上能够连接上呢。

**Comment by maninhill** [comment]
其他用户那边都是工作正常，目前我们无法进一步解决，先关闭问题，望理解。
