### ISSUE TITLE
更新到V1.18.17全屏预览按钮遮挡，以及颜色适配主题问题

### ISSUE THREAD

**Issue by wt7060** [dataease/dataease#8562]
DataEase 版本: V1.18.17
在Dashboard页面，右下角的图片下载和全屏预览按钮使用体验不好，遮挡画面，以及无法自动隐藏抽屉，只有浅色图标，不能自动适配主题色，影响使用体验。
![image](https://github.com/dataease/dataease/assets/30554104/470be0cc-1e39-4878-884b-a8521c9b54bb)

个人建议：推荐使用透明背景的图标，鼠标移动到图标上，然后显现出来按钮，移开后自动隐藏，同时自动适配主题色，不然会很突兀。
最后感谢，以上为个人建议。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个地方我们已经优化了部分使用体验，我们再看看怎样能做的更好一些。

**Comment by xuwei-fit2cloud** [comment]
建议您可以先使用深色主题，图标会自动变为深色图标。
至于隐藏设置，可能会让人无法清楚功能所在，暂时先保持现状，等待后续其他用户的反馈。
