### ISSUE TITLE
[Bug] 国际化很多地方显示的有问题，英文显示的中文，文字显示大小也有问题

### ISSUE THREAD

**Issue by tclxzz08514** [dataease/dataease#8566]
**DataEase 版本**
V1.18.15

**运行方式(安装包运行 or 源码运行 ?)**
..

**浏览器版本**
任意

**Bug 描述**
国际化支持遗漏

**Bug 重现步骤(有截图更好)**
![截图显示](https://github.com/dataease/dataease/assets/135008993/d6e2d115-dd03-4621-ada7-cb4705b67c37)

**Comment by tclxzz08514** [comment]
切换英文后，部分地方还是显示中文， 有些按钮上文字会溢出

**Comment by BBchicken-9527** [comment]
感谢反馈，目前正在逐步的支持，请耐心等候；
