### ISSUE TITLE
[Feature]数据分析报告

### ISSUE THREAD

**Issue by While4** [dataease/dataease#8568]
DataEase 版本:
v1.18.17

**请描述您的需求或者改进建议.**
有考虑为咨询行业提供整体解决方案吗？
比如专业的数据分析师，针对看板报表，会定期出具咨询报告，能否集成到该产品中？

功能点：
1、支持某个时间点，针对1-n个看板的咨询报告维护
2、支持按照时间线，展示咨询报告

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们内部先讨论一下该需求。

**Comment by xuwei-fit2cloud** [comment]
您的需求已记录，但短期内还没有支持该需求的计划，我们收集更多类似的用户反馈后会排期开发。
