### ISSUE TITLE
[Bug]文本下拉组件，选择首项时，过滤组件在全屏预览情况下缩小原来的组件大小

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#8569]
**DataEase 版本**
v1.18.16&v1.18.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**Bug 描述**
文本下拉组件，选择首项时，过滤组件在全屏预览情况下缩小原来的组件大小
在退出编辑页面后，也会缩小组件大小

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/70566485/d41520df-b6e1-41c1-95ab-17a7d15c0068)
![image](https://github.com/dataease/dataease/assets/70566485/e3c19a15-8a25-4bb0-9973-98c581c32a53)
![image](https://github.com/dataease/dataease/assets/70566485/eac59c63-0713-4575-9d3b-a9f008b8a09f)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行优化；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
