### ISSUE TITLE
希望视图工作区的指标/维度等可以批量选中拖拽添加。

### ISSUE THREAD

**Issue by gcfanjiawen** [dataease/dataease#857]
![示例](https://user-images.githubusercontent.com/42668877/134451401-13015790-5ae2-4747-adee-8af10e6e36ea.png)

**Comment by yayanpei** [comment]
非常感谢您的反馈，我们需要内部讨论和评估。

**Comment by gcfanjiawen** [comment]
好的，谢谢啦

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
