### ISSUE TITLE
升级后连接oracle19C数据库数据源无效

### ISSUE THREAD

**Issue by songgang1997** [dataease/dataease#8574]
DataEase 版本:
目前已升级为1.18.17最新版，但连接oracle19C数据库连接失败，数据源无效，请增加19C驱动。上传从官网下载的新的驱动还是不行，可能是驱动名称配置有问题，请指导
![image](https://github.com/dataease/dataease/assets/35589880/90eec7cc-de2f-43c6-86c3-f8d2cbc160dd)
![image](https://github.com/dataease/dataease/assets/35589880/1bd708b5-4681-4286-9d04-6eb2d126d88b)

**Comment by tjlygdx** [comment]
使用默认驱动 “连接oracle19C数据库失败”，能把这里的报错信息发一下？

**Comment by tjlygdx** [comment]
驱动：oracle.jdbc.driver.OracleDriver

**Comment by songgang1997** [comment]
使用你发的这个驱动名已经顺利连接上了。谢谢 ，但还是希望默认驱动就带19C驱动

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们在后续版本考虑一下怎么优化。
