### ISSUE TITLE
地图无法显示，提示404

### ISSUE THREAD

**Issue by zoxaklxl** [dataease/dataease#8575]
**DataEase 版本**
v2.4.1

**运行方式(安装包运行 or 源码运行 ?)**
源码编译运行

**浏览器版本**
Chrome版本 120.0.6099.200（正式版本） （64 位）

**Bug 描述**
地图无法显示，提示404，http://localhost:8100/de2api/map/156/156.json提示404，不知道是否是core-frontend编译有问题，源码编译命令:
cd dataease
mvn clean install
cd core
mvn clean package -Pstandalone -U -Dmaven.test.skip=true

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/36411125/24859a7a-f8c2-4368-9000-df32e24c5a07)

**Comment by xuwei-fit2cloud** [comment]
请参考一下在线文档：
https://dataease.io/docs/v2/installation/deployment_installation/#33

**Comment by zoxaklxl** [comment]
就是按照在线文档编译运行的，地图无法显示，提示404，是/de2api/map/路径下吗？
