### ISSUE TITLE
[Bug]下拉过滤组件，下拉框选了一个之后再次搜索选择第二个，第一个就会被取消勾选

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#8576]
**DataEase 版本**
1.18.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
下拉过滤组件，下拉框选了一个之后，再次搜索选择第二个，第一个就会被取消勾选
文本下拉组件和数字下拉组件都存在这个问题
![image](https://github.com/dataease/dataease/assets/89771514/1a79a1a2-9b1a-4d97-ab59-c8e3edfb898f)

**Comment by xuwei-fit2cloud** [comment]
已处理，下个版本发布。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
