### ISSUE TITLE
[Bug]仪表板，结果展示选择展示全部的情况下，默认只查询了一条数据

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#8577]
**DataEase 版本**
1.18.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
时间过滤组件设置动态默认值，设置查询按钮开启自动触发，明细表视图结果展示中设置展示全部，右侧条数设置1，预览时只加载了一条数据，结果与预期不符
![image](https://github.com/dataease/dataease/assets/89771514/d27f9393-776f-4c38-8db0-2983419b4322)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
