### ISSUE TITLE
[Bug]文本下拉过滤组件两个，同时设置两个过滤组件为首项时，在编辑和查看页面为空白，全屏预览时正常

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#8579]
**DataEase 版本**
v1.18.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 122.0.6261.112（正式版本） (x86_64)

**Bug 描述**
文本下拉过滤组件两个，同时设置两个过滤组件为首项时，在编辑和查看页面为空白，全屏预览时正常，切换选项也正常展示

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/70566485/25a58546-09aa-4118-86b8-86e9c7179ba6)
![image](https://github.com/dataease/dataease/assets/70566485/e6840439-6979-451d-a251-0829aa79fe2f)
![image](https://github.com/dataease/dataease/assets/70566485/9ecf9a40-87ec-4eba-b716-4605580b8f59)
![image](https://github.com/dataease/dataease/assets/70566485/b932d7c8-18b3-48e2-be46-b50d9a5a55cd)
![image](https://github.com/dataease/dataease/assets/70566485/caf4850a-138b-418c-82f3-3218656df9fe)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
