### ISSUE TITLE
[Bug]AntV明细表配合过滤组件使用，分页模式为下拉时，过滤组件选择值后再清空值，报空指针

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#8581]
**DataEase 版本**
v1.18.7

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 122.0.6261.112（正式版本） (x86_64)

**Bug 描述**
AntV明细表配合过滤组件使用，分页模式为下拉时，过滤组件选择值后再清空值，报空指针；为翻页是使用正常。

**Bug 重现步骤(有截图更好)**
1.创建AntV明细表，设置分页模式为下拉
2.添加过滤组件：文本下拉、时间范围都报错
3.选择值后，再清空，报错
另一种情况：
AntV明细表，开启仪表板刷新，刷新后空指针报错，应该是相同问题。
![image](https://github.com/dataease/dataease/assets/70566485/6a95964b-9570-4701-be6f-8300ab3a464b)
![image](https://github.com/dataease/dataease/assets/70566485/7bda3550-8ba4-4af6-8d8e-b9ffb51bf493)
<img width="1474" alt="image" src="https://github.com/dataease/dataease/assets/70566485/96298794-6a60-489c-a199-fe76de32811c">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们下个版本修复。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
