### ISSUE TITLE
[Bug]AntV堆叠折线图标签越界无法显示 & 辅助线数值格式支持

### ISSUE THREAD

**Issue by wt7060** [dataease/dataease#8584]
**DataEase 版本**
V1.18.17
**Bug 描述**
1.在AntV堆叠折线图中，存在数据标签无法完整显示问题，即使我使用自动纵向坐标轴值，也无法显示完整，此Bug一直在以往版本中也一直存在，需要修复不然会影响使用体验。
2.目标线显示问题：如果我的指标是百分比的值，我目标线应该显示目标是百分比，但是我无法设置为百分比目标，只能是0.000XX这种小数显示，感觉很怪异。
**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/30554104/1a44018b-425a-4915-90ed-e43f2e29d8dc)

以上，感谢！

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们在后续版本处理一下。

**Comment by xuwei-fit2cloud** [comment]
> 2.目标线显示问题：如果我的指标是百分比的值，我目标线应该显示目标是百分比，但是我无法设置为百分比目标，只能是0.000XX这种小数显示，感觉很怪异。

这个的话，您可以试试在【样式】的【纵轴】里设置一下数值格式，参考下图：
![图片](https://github.com/dataease/dataease/assets/1892127/02ab1248-b323-4c8e-b9f5-34ccb5042731)
