### ISSUE TITLE
[Feature] 仪表板导出Excel 希望提供一些限制参数，不希望总是导出数据集所有数据

### ISSUE THREAD

**Issue by 15767714253** [dataease/dataease#8586]
DataEase 版本: V2.4.0

**请描述您的需求或者改进建议.**
现在导出总是把仪表板对应的数据集的所有数据全部返回，希望有所限制

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请问您这边是导出什么图表的数据呢？请问是明细表吗？

**Comment by 15767714253** [comment]
> 感谢您的反馈，请问您这边是导出什么图表的数据呢？请问是明细表吗？

是的

**Comment by yayanpei-fit2cloud** [comment]
请问是要限制导出的行数？还是需要增加过滤条件，然后按条件导出？

**Comment by 15767714253** [comment]
> 请问是要限制导出的行数？还是需要增加过滤条件，然后按条件导出？

目前限制导出行数就可以了，还有一个地方就是数据集，拖拉拽方式居然没有一个地方可以限制行数的，必须通过自定义SQL

**Comment by xuwei-fit2cloud** [comment]
后续版本中我们会在数据集里添加数据导出功能，以后可以在数据集进行一些导出限制。

**Comment by nathaniel090** [comment]
明细表加了查询组件，查询需要的数据之后，点导出按逻辑应该是导出筛选后的数据，
或者是点导出之后可以选择导出全部数据或者是筛选后数据

**Comment by xuwei-fit2cloud** [comment]
仪表板中导出的Excel，调整为导出参与制作当前图表的所有数据。
