### ISSUE TITLE
[Feature] 公共链接密码增强

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#8593]
DataEase 版本:
v1.18.17 v2.4.1

**请描述您的需求或者改进建议.**
目前公共链接密码为4位随机数，可否对此做下增强，密码长度为10位，且由大写字母、小写字母、数字、特殊符号组成。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，后期会考虑位数增加，并支持自定义密码。
