### ISSUE TITLE
[Feature] 视图导出数据等按钮尺寸适当调大

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#8596]
如下所示，分辨率比较高的情况下，视图的操作按钮非常小，不太好点击。
![image](https://github.com/dataease/dataease/assets/30063018/c74b504a-0d6e-4c83-9471-750880b4aec5)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
需求已记录，暂时不做改动。
