### ISSUE TITLE
[Feature]SQL能否支持在WHERE后面以外的地方添加参数

### ISSUE THREAD

**Issue by H1ser0** [dataease/dataease#8597]
DataEase 版本: V1.18.15

**请描述您的需求或者改进建议.**

目前参数只能放在最外层的WHERE后面，希望参数也可放在其他位置，如
SELECT FUNC(${param1}, ${param2}) FROM table;
其中FUNC是一个函数

**Comment by tzengshinfu** [comment]
Hi, 这么巧，
我之前也有提出，官方回复是目前无法达到
[[Question]SQL变量只能在WHERE条件中使用？ #6081](https://github.com/dataease/dataease/issues/6081)，

当时是与其他报表系统比较，其他报表系统是可行的，
很意外DataEase无法达到(感觉卡在是标准SQL转换成其他来源的逻辑...)

**Comment by H1ser0** [comment]
@tzengshinfu 只能希望官方能优化一下，不然对报表来说，有点过于局限了

**Comment by yayanpei-fit2cloud** [comment]
如楼上回复，目前暂时没有计划支持该需求，您可以加我微信（18317092178）一起聊下具体的场景，再次感谢您的反馈和支持。
