### ISSUE TITLE
[Feature] V2 版本数据集中新增定时同步,

### ISSUE THREAD

**Issue by f2m4** [dataease/dataease#8600]
DataEase 版本: V2

** 希望V2版本,在数据集中添加定时同步的功能.  有些数据查询起来很慢,这样的数据做定时同步很有用.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，v2 的定时同步是放在了企业版中，如果需要，建议您申请一个license先进行试用，申请链接：https://jinshuju.net/f/TK5TTd
