### ISSUE TITLE
[Feature]仪表板内为各个图表的轴或者维度增加额外独立的标签变量，用于在标题、提示、标签、图例中增加图标的可读性

### ISSUE THREAD

**Issue by atreeofroy** [dataease/dataease#8608]
DataEase 版本:
1.18.17

**请描述您的需求或者改进建议.**
目前，各个图表中全部为数据维度，没有专门的标签维度。为了便于阅读，很多场景都将字典代码转为标签。但是在跳转和联动时，如果原来的代码字段没有出现在轴或维度里，那么就只能传出标签。如果标签与代码不是唯一对应，跳转和联动将不能保证正确。如饼图内，代码和标签都显示的话，不太美观；而在桑基图里，代码和标签只能选其一。（传入的参数好像不要求出现在表头内，可以生效）
![3d1aeb6a5b64f390b57390103c50d5b](https://github.com/dataease/dataease/assets/116705461/70b3d427-ed2e-42ae-8de0-527036064475)
如图：桑基图里，专门传了标签字段，但是无处可以显示。
希望在样式里，增加标签字段的用法，如标题、提示、标签、图例中，以增加图标的可读性。
![1710922832728](https://github.com/dataease/dataease/assets/116705461/9b209e5b-34cc-4d0a-82b1-6ee881dd74cc)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，该需求已经在我们的需求池中，还在等待排期中。
