### ISSUE TITLE
[Feature]导出整个仪表板的数据为 Excel

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#8612]
DataEase 版本:
v2

希望可以 将数据大屏和仪表板 所有的视图一同导出为Excel，每个 sheet 代表一个视图。

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
技术上是可以实现，我们先讨论一下是否支持。

**Comment by xuwei-fit2cloud** [comment]
需求已记录，若有其他用户反馈同样需求，我们再安排开发。
