### ISSUE TITLE
[Feature]API接口加注释@JsonInclude(value= JsonInclude.Include.NON_NULL)，接口字段为空的话不会返回字段，会导致数据错乱，建议优化

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#8620]
DataEase 版本:
v1.18.17

**请描述您的需求或者改进建议.**
如果API接口加注释@JsonInclude(value= JsonInclude.Include.NON_NULL)，接口字段为空的话不会返回字段，会导致数据错乱，建议优化。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们讨论一下相关优化。

**Comment by xuwei-fit2cloud** [comment]
目前并没有发现问题，暂不处理。
