### ISSUE TITLE
[Feature] 分享数据集，类似仪表盘

### ISSUE THREAD

**Issue by 15767714253** [dataease/dataease#8621]
DataEase 版本:

**请描述您的需求或者改进建议.**
在很多公司内部资产管理产品需要查看某种数据的数据集，可以嵌入式打开dataease的数据集

**Comment by xuwei-fit2cloud** [comment]
DataEase v2版本支持数据集的嵌入，您可以联系我们了解一下。

**Comment by 15767714253** [comment]
> DataEase v2版本支持数据集的嵌入，您可以联系我们了解一下。

有没有微信群之类

**Comment by xuwei-fit2cloud** [comment]
您可以访问我们的网站获取到联系方式：
https://dataease.io/#contact
