### ISSUE TITLE
[Bug] 用户 token 过期后仪表板仍在请求数据源

### ISSUE THREAD

**Issue by hzhwyh0116** [dataease/dataease#8630]
**DataEase 版本**
v1.18.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome

**Bug 描述**
仪表板数据集为直连，并且设置好仪表板刷新频率，进行报表预览
当用户token 时效时，仪表板仍然在后台请求数据，直到用户退出登录才不会请求数据

期望 token 失效后仪表盘不要继续向后台请求数据

**Comment by maninhill** [comment]
v2.10-lts 版本已经发布，请在最新版本上面验证，有问题请 re-open。
