### ISSUE TITLE
[Feature]铜山区标签位置希望可以移动到实际区域位置，而不是中心位置

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#8632]
DataEase 版本:
1.18

**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/101089844/1ff21b01-b458-4f13-80ce-e97b0638da87)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，色彩地图是根据地区的中心点位置显示标签的，图库本身是不支持移动标签位置的，目前暂时无法支持。
