### ISSUE TITLE
[Feature]建议支持1、批量上传图 2、支持设置图标尺寸3、支持设置背景图片透明度

### ISSUE THREAD

**Issue by huguangya** [dataease/dataease#864]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/54281046/134635042-a2c11ea7-bafa-4c72-b9c9-3bc6a6af4569.png)

**Comment by yayanpei** [comment]
非常感谢您的反馈，设置图片尺寸适应模式和背景图透明度设置，目前已经在规划的需求中。批量上传图片，也会在接下里的版本中规划实现，敬请关注。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
