### ISSUE TITLE
[Bug]在编辑页面时选择全屏预览后 如果点击全屏画面下的组件时会发生位移

### ISSUE THREAD

**Issue by nbjelly91** [dataease/dataease#8646]
**DataEase 版本**

v1.18.17
--

**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**
chrome 122.0.6261.112

**Bug 描述**

在编辑页面时选择全屏预览后 如果点击全屏画面下的组件时会发生位移

**Bug 重现步骤(有截图更好)**
1.进入仪表板
![image](https://github.com/dataease/dataease/assets/52103215/81e9fb79-9ffe-4aa6-a1a2-799d93224dc7)

2.点击其中一个组件进入编辑模式
![image](https://github.com/dataease/dataease/assets/52103215/b825a1b0-567a-4926-9f21-1b5fc78bf7f4)

3.然后进入全屏模式
![image](https://github.com/dataease/dataease/assets/52103215/85890ec5-5298-4dec-92df-b3ffdad12bec)

3.点击组件就会位移
![image](https://github.com/dataease/dataease/assets/52103215/440c2136-a9d4-4981-b36f-dfc4c4e11622)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你的屏幕尺寸是多少吗，如果可以的话最好在给我一个视频看一下，目前测试环境没有发现你说的这个问题；

**Comment by nbjelly91** [comment]
分辨率2K 2560*1440
录了段视频 在官方的演示地址里面操作的
https://github.com/dataease/dataease/assets/52103215/31d8be8e-4a79-49dd-bf62-eb1fd7722a87

**Comment by BBchicken-9527** [comment]
感谢反馈，一般此类情况为前端内存不足导致的计算错误，我看您视频中也开了很多页面受累清理一下内存试试；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
