### ISSUE TITLE
[Feature]文本框添加背景颜色后就无法取消背景颜色了，只能改颜色，建议优化

### ISSUE THREAD

**Issue by huguangya** [dataease/dataease#865]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/54281046/134640248-e61a7ac7-d33a-4a57-899e-c7bc4f71398c.png)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下

**Comment by xuwei-fit2cloud** [comment]
v1.4.0 版本后可以通过设置透明度来解决。
