### ISSUE TITLE
[Feature]【仪表板】跳转设置支持日期类型的过滤组件联动

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#8661]
DataEase 版本:
v1

**请描述您的需求或者改进建议.**
跳转设置支持日期类型的过滤组件联动，当前支持文本类型
![image](https://github.com/dataease/dataease/assets/24768910/f59b4ce0-b23e-465f-ad4a-2bcb82a6425b)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中支持一下。
