### ISSUE TITLE
[Feature]v2 增加插件管理入口

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#8668]
DataEase 版本:
v2

插件管理需求：希望可以自行开发视图插件，上传的 DataEase 中。

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，这个我们在后续版本是会支持的，但短期内还没有排期。

**Comment by Light-Towers** [comment]
v1 版本还支持数据源插件和视图插件，v2却没了
