### ISSUE TITLE
[Feature]饼图建议同时支持数量及占比

### ISSUE THREAD

**Issue by huguangya** [dataease/dataease#867]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/54281046/134647567-4677433b-4117-4198-bd36-4e25fb5d46ef.png)

**Comment by yayanpei** [comment]
该需求已实现，需要设置标签的内容格式，可参考下图设置：
![image](https://user-images.githubusercontent.com/84168063/134790804-b41924d4-b12c-46ef-b004-eda75454e0e3.png)
