### ISSUE TITLE
[Feature] 关联数据集关联字段允许使用计算字段

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#8678]
DataEase 版本:
v1.18.15

**请描述您的需求或者改进建议.**
关联数据集关联字段允许使用计算字段

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
由于v1版本关联数据集的设计问题，目前并不太好做该需求的支持。
