### ISSUE TITLE
[Bug]v1版本 数据集计算字段中ifnull（）不管用

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8679]
v1.18.17 安装包安装
数据集新建字段 excel数据源
原始的数据类型是文本类型（估计其他类型的也不行）
新建的字段test 如果日期（文本类型）的指不为空 用*代替 不管用  IFNULL([日期],'*') 后来换成另一种写法IFNULL([日期],2) 也不行。第二种写法在v2版本里面是可以的

后来换成case when  字段 is not null 试了一下，他好像是空的地方不知道用什么占位了，即使是空值的地方仍然走了写的逻辑。
用 字段=’‘倒是没问题

**Comment by wolf-kingx** [comment]
原始字段类型
![14a503e1a2fdeb4fcd108f7679053f4b](https://github.com/dataease/dataease/assets/141667200/68ab076a-0c1b-434b-a882-2c153f913093)

新建计算字段
![351029a50f6e87b4f9628869bd2e7422](https://github.com/dataease/dataease/assets/141667200/66307309-32aa-4882-9bb7-cba2946f40ae)

数据预览
![967f5ead93e7de72a04e8993ff93c665](https://github.com/dataease/dataease/assets/141667200/5679867e-3398-41c9-a8ac-efa58b568217)

**Comment by wolf-kingx** [comment]
case when 尝试
![image](https://github.com/dataease/dataease/assets/141667200/bca22a98-242c-48b5-a27f-94c5c3841706)
数据预览
![image](https://github.com/dataease/dataease/assets/141667200/a9a66db5-a6bf-44a5-b9ca-002c05980504)

**Comment by BBchicken-9527** [comment]
感谢反馈，因为是excel导入，入库时文本类型是会转为空，所以ifnull拿不到的，我们讨论一下这里是否可以优化一下；

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下此处实现逻辑；
