### ISSUE TITLE
[Feature]建议支持元素组合

### ISSUE THREAD

**Issue by huguangya** [dataease/dataease#868]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/54281046/134649161-e976a48e-2b3a-415d-baf4-797b5fac929b.png)

**Comment by yayanpei** [comment]
非常感谢您的反馈，您的建议很不错，我们会优先考虑加入产品迭代中。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
