### ISSUE TITLE
[Bug]未登录用户访问公共连接tab组件中的视图，还是会提示需要登录

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8680]
v1.18.17 安装包安装
和issue8079一样的问题，但是新版只修复了一半，在查看仪表板中tab组件里面的视图，还会出现一样的提示信息。

![image](https://github.com/dataease/dataease/assets/141667200/74b3f9dc-ba12-4ac3-be06-b9a2365f6a4c)
![image](https://github.com/dataease/dataease/assets/141667200/9b518922-cb8d-47b9-9ecc-958e9101e57c)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在这个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
