### ISSUE TITLE
[Feature]希望DE能支持 自由式表格视图，财务用户在制作视图时需要该功能，详见链接。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#8683]
DataEase 版本:

V2.4.1
**请描述您的需求或者改进建议.**
希望DE能支持 自由式表格视图，财务用户在制作视图时需要该功能，详见链接。

https://www.yonghongtech.com/real-help/Z-Suite/9.4/ch/make_visual_dashboard_complexform_free.html?zoom_highlightsub=%E8%87%AA%E7%94%B1%E8%A1%A8

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，自由式表格我们先加入需求池中，近期暂时还没有规划去做支持。
