### ISSUE TITLE
[Feature] 希望散点图支持分析两个指标间的关系

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#8685]
DataEase 版本:
2.4.0

**请描述您的需求或者改进建议.**
目前Dataease的散点图只能做维度与指标的分析，没有办法实现数据 与 数据 之间的二维分析（如果硬把数值数据转成维度，也可以展示，只不过没办法实现维度间距的体现），希望增加此能力。
下面则是原型图，Ecahrs上也有很多demo做数据的二维分析，可以参考下
![image](https://github.com/dataease/dataease/assets/45967454/41b3bbd5-5d82-48c5-a50c-f9ac72f05158)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中支持一下。

**Comment by xuwei-fit2cloud** [comment]
暂无支持计划。
