### ISSUE TITLE
[Feature]建议支持超链接文本

### ISSUE THREAD

**Issue by huguangya** [dataease/dataease#869]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/54281046/134650832-adf5c7e5-2e70-4a1f-ba0e-31d418abe6d1.png)

**Comment by yayanpei** [comment]
感谢您的反馈，该需求已规划在 10.14号发布的V1.4.0版本中。

**Comment by xuwei-fit2cloud** [comment]
v1.4.0 已支持
