### ISSUE TITLE
[Bug]org.apache.calcite:calcite-core:jar:de:1.35.5

### ISSUE THREAD

**Issue by laosandegudai** [dataease/dataease#8690]
**DataEase 版本**
2.4 在2.3是一样的

**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**

**Bug 描述**
Failed to execute goal on project core-backend: Could not resolve dependencies for project io.dataease:core-backend:jar:2.4.0: The following artifacts could not be resolved: org.apache.calcite:calcite-core:jar:de:1.35.5 (absent): Could not find artifact org.apache.calcite:calcite-core:jar:de:1.35.5 in aliyunmaven (https://maven.aliyun.com/repository/public) ->

**Bug 重现步骤(有截图更好)**
1.cd dataease
mvn clean install

2.cd core
mvn clean package -Pstandalone -U -Dmaven.test.skip=true

**Comment by maninhill** [comment]
请参考文档：https://dataease.io/docs/v2/installation/deployment_installation/

**Comment by laosandegudai** [comment]
> 请参考文档：https://dataease.io/docs/v2/installation/deployment_installation/
看啦啊，严格按照文档。
`core-backend 源码引用到 calcite-core 依赖，是 DataEase 基于 Apache Calcite 工程修改后的依赖包，不属于开源部分。该依赖包会持续迭代，并上传到公共仓库中，对社区版源码的编译和使用不会造成任何影响。
注意：编译前端代码如果出现网络问题导致编译失败，可以将 npm 镜像源换为淘宝镜像源，并使用 pnpm 进行编译。手动编译前端，将下图前端 pom 文件相关插件注释,然后再执行 mvn clean package -Pstandalone -U -Dmaven.test.skip=true。`

**Comment by sionguo** [comment]
我也是按照文档来的。遇到了同样的问题
