### ISSUE TITLE
[Bug] 富文本设置超链接无法跳转到DE分享出来的公共链接

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#8696]
**DataEase 版本**
2.4.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
富文本设置超链接无法跳转到DE分享出来的公共链接

**Bug 重现步骤(有截图更好)**
1. 打开富文本，设置超链接
2.随意分享一个仪表板的公共链接，复制链接地址
3.将公共链接地址设置在富文本的超链接，进行外部链接跳转测试
![image](https://github.com/dataease/dataease/assets/45967454/30402e00-0d79-4fae-9f9d-d9f80b920e00)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
