### ISSUE TITLE
[Bug]文本框的格式框工具栏经常点不出来

### ISSUE THREAD

**Issue by huguangya** [dataease/dataease#870]
**DataEase 版本**
最新版

**浏览器版本**
谷歌浏览器最新版

**Bug 描述**
![image](https://user-images.githubusercontent.com/54281046/134651062-d1a52b59-5e5a-47b1-896a-0677f88a7672.png)
![image](https://user-images.githubusercontent.com/54281046/134651254-fb2f96b2-774f-41ae-b009-b8c88386f987.png)

**Bug 重现步骤(有截图更好)**
1.先双击文本框，然后点到其他元素
2.再点回文本框
3.可以看到格式框出不来了

**Comment by yayanpei** [comment]
非常感谢您的反馈，我们尽快修复。

**Comment by xuwei-fit2cloud** [comment]
v1.4.0版本已修复
