### ISSUE TITLE
[Feature]【仪表板】钻取的同时支持配置是否直接联动

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#8701]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
钻取的同时支持配置是否直接联动
![image](https://github.com/dataease/dataease/assets/24768910/1f7083bc-3346-41b3-a554-fc10b9e2fdd6)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中支持一下。
