### ISSUE TITLE
[Feature]【仪表板】仪表板加载时的白底支持设置成透明

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#8702]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
仪表板加载时的白底支持设置成透明

https://github.com/dataease/dataease/assets/24768910/27d79cdd-4454-4b4e-b137-c119eb05bd77

![image](https://github.com/dataease/dataease/assets/24768910/85803b40-5377-4ac6-9b49-3d18d2079fcb)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们优化一下。

**Comment by fit2cloudrd** [comment]
v2.5.0版本已去掉了遮罩。

**Comment by yaocanke** [comment]
这个问题在V1.18.18版本中也存在，是否可以下一个版本也更新一下？
