### ISSUE TITLE
[Feature][仪表盘]用户收到分享的仪表盘无法进行整理

### ISSUE THREAD

**Issue by baoziyucha** [dataease/dataease#8705]
DataEase 版本:1.18

**请描述您的需求或者改进建议.**
用户收到分享的仪表盘都在”管理员“文件夹下，当仪表盘较多的时候显示很差

**Comment by baoziyucha** [comment]
![仪表盘](https://github.com/dataease/dataease/assets/77571914/8598b827-4ae3-4bc5-b8c4-4eefc4e69eb1)


具体是这样

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，如果需要查阅的仪表板较多，建议您在仪表板的资源列表中进行查阅。
