### ISSUE TITLE
[Feature]v1.18.17 希望筛选框里的文字大小能调整

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8707]
![a399904fd3e41fc82ae724cf9d6e316](https://github.com/dataease/dataease/assets/141667200/e723df2b-1fd2-4063-80ac-966c1cc42c0d)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，仪表板本身是自适应的，因此当使用较大屏幕时，字体是会自适应放大的。当前阶段暂时没有规划进行支持。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，仪表板本身是自适应的，因此当使用较大屏幕时，字体是会自适应放大的。当前阶段暂时没有规划进行支持。
