### ISSUE TITLE
[Bug]基础折线图，当提示信息过长，超出屏幕尺寸展示不全时，页面就会频繁的进行刷新

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#8708]
**DataEase 版本**
1.18.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
基础折线图，当子维度很多时，鼠标移动到折线图的某一个维度上，会显示当前维度的所有子维度的提示信息，提示信息过长时，就会超出屏幕尺寸展示不全，这个时候就会触发浏览器页面的刷新，导致无法正常查看信息
<img width="1173" alt="image" src="https://github.com/dataease/dataease/assets/89771514/feb011ed-1af9-419d-b016-f5f05ef4e3aa">

当提示过长时，是否可以通过滚动条的方式展示，或者分多列展示

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。
