### ISSUE TITLE
[Bug]v1.18.17 表格视图 数据集导出的时候 空单元格会出现被null填充的现象

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8711]
安装包安装
dataease中的表格展示
![image](https://github.com/dataease/dataease/assets/141667200/db89c997-fa6e-47c2-9c76-42e8b97b709d)
第一次导出后
![image](https://github.com/dataease/dataease/assets/141667200/2bc4f9d6-85d2-4c3d-a043-b3c61c5172f9)
第二次导出后
![image](https://github.com/dataease/dataease/assets/141667200/b257ba30-cae2-4d81-aca1-4bbbe6520ea1)

具有随机性

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，我这边使用的是excel数据导入的数据，方便的话说明一下你使用的数据源我这边尽可能按照你的场景去复现一下；

**Comment by wolf-kingx** [comment]
我这边测试也是用的excel，多试几次，他这不是每次都出现。

**Comment by wolf-kingx** [comment]
[工作簿2.xlsx](https://github.com/dataease/dataease/files/14818550/2.xlsx)

**Comment by wolf-kingx** [comment]
这是我试的时候用的，你试试。
