### ISSUE TITLE
[Feature]v1.18.17 文本下拉框组件里面的排序功能希望根据全部数据进行排序

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8714]
原本这个项目应该有四个值
![e4bb5072f2175b7773a6ac2321d0062](https://github.com/dataease/dataease/assets/141667200/50585b10-d3c3-43fc-9633-3e2a868a1415)
后来设置根据项目序号进行项目的排序，只显示了一个济南字段
![17a9193a9086ecb9b8852f3d2738dd5](https://github.com/dataease/dataease/assets/141667200/3559047d-f509-4d63-92cf-523d300346f7)
排查过程看了下个项目的数据量，发现数据不少，猜测这个排序应该是只根据了前1000条进行排序，希望能根据全部的数据进行这个排序。
![7bc476d8243f668931d9237f471e33f](https://github.com/dataease/dataease/assets/141667200/d58d86e3-a587-420d-8851-267ad9a46c26)

**Comment by xuwei-fit2cloud** [comment]
目前确实是取了部分数据进行排序，因为在数据量特别大的情况下，进行全数据排序响应会很慢。
我们再考虑一下如何优化。
