### ISSUE TITLE
[Feature]【仪表板】筛选组件支持隐藏（详见「场景点」）

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#8716]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
筛选组件支持隐藏（详见「场景点」）
场景点：
近期版本 v2 会发布仪表板外部参数功能，外部参数可以传给过滤组件，过滤组件可以对 SQL 数据集进行动态传参。但是有些时候想通过参数对 SQL 数据集进行动态传参，但是又不想展示筛选组件给到客户去调整，数据大屏可以盖住，仪表板不能，所以仪表板看看能不能支持过滤组件的隐藏。或者看看能不能直接通过参数对 SQL 数据集进行动态传参。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，v2.5版本已支持，外部参数可以直接关联图表，并对图表数据进行过滤，请等待版本发布。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，v2.5版本已支持，外部参数可以直接选择图表，并对图表数据进行过滤，请等待版本发布。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。

**Comment by AndroidBaby1** [comment]
感谢！
