### ISSUE TITLE
[Bug]使用dataease的镜像出现  “缺少许可证”

### ISSUE THREAD

**Issue by laosandegudai** [dataease/dataease#8718]
**DataEase 版本**
registry.cn-qingdao.aliyuncs.com/dataease/dataease:v2.4.1

**运行方式(安装包运行 or 源码运行 ?)**
使用官方的镜像启动后，页面不能正常显示，发现数据返回了，但是被拦截了。
接口返回 “缺少许可证”
镜像内日志
`2024-03-26 19:38:55.574 INFO  --- [ [_default_]-14] io.dataease.listener.MyCacheListener     : 'CREATED' : [1eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsIm9pZCI6MSwiZXhwIjoxNzExNDUzMjM1fQ.qgHLeKe-b5a41IV5Ey28qnzayON69aPmSFCROdZFvqQ] --> 1
2024-03-26 19:38:55.578 INFO  --- [ [_default_]-14] io.dataease.listener.MyCacheListener     : 'REMOVED' : [1eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOjEsIm9pZCI6MSwiZXhwIjoxNzExNDUzMjM1fQ.qgHLeKe-b5a41IV5Ey28qnzayON69aPmSFCROdZFvqQ] --> null`

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
使用官方镜像，社区版的功能都是可以正常使用的，您的具体问题是？在使用什么功能的时候遇到了问题？

**Comment by laosandegudai** [comment]
> 使用官方镜像，社区版的功能都是可以正常使用的，您的具体问题是？在使用什么功能的时候遇到了问题？

我是自己打包失败后，看到教程文档有镜像地址，就自己尝试版本号，用了镜像
`registry.cn-qingdao.aliyuncs.com/dataease/dataease:v2.4.1`，可以创建数据集，数据集也可以看到数据，但是在显示到仪表板时就不显示了，我在调试工具内看到数据接口已经正常返回数据了，但是看到控制台 有异常显示  
`缺少许可证`
我不知道这是否是商业版镜像，如果是我就直接关闭这个了。

**Comment by maninhill** [comment]
建议使用安装包或者安装脚本进行规范部署。
