### ISSUE TITLE
[Feature]批量导入模版

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#8727]
DataEase 版本:
v1, v2

纯内网环境部署，想要导入模版需要一个一个导入，希望可以批量导入。
**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
这个我们讨论一下，其实还可以自己在内网搭建一个模板服务，使用自己内网的模板服务器。

**Comment by xuwei-fit2cloud** [comment]
暂时还没有计划支持批量导入，您可以安装一个Halo，在内网环境里搭建自己的模板市场，效果会更好。
