### ISSUE TITLE
[Bug]【数据集】关联数据集显示异常

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#8736]
**DataEase 版本**
v1.18.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
关联数据集显示异常（详见 Bug 重现步骤）

**Bug 重现步骤(有截图更好)**
1.创建 SQL 数据集「测试名称 001」
<img width="1015" alt="image" src="https://github.com/dataease/dataease/assets/24768910/d2bb3632-d7e2-42eb-8e2b-c96274eed350">

2.创建 SQL 数据集「测试名称 002」
<img width="1003" alt="image" src="https://github.com/dataease/dataease/assets/24768910/902201cf-f755-4ee1-8706-38bbc33b1276">

3.添加关联数据集「测试名称 999」
<img width="805" alt="image" src="https://github.com/dataease/dataease/assets/24768910/98e894b5-f8ae-4955-a36a-9d448e5daa1d">

4.修改「测试名称 001」名称为「测试名称 001-改」
<img width="696" alt="image" src="https://github.com/dataease/dataease/assets/24768910/fc6e693a-719a-4843-987e-5310c06e10ed">

5.关联数据集没有同步显示正常
<img width="550" alt="image" src="https://github.com/dataease/dataease/assets/24768910/f62858d1-6684-4e65-8b73-76506a5ad0b0">

<img width="701" alt="image" src="https://github.com/dataease/dataease/assets/24768910/02d4630e-3c93-41e5-bfff-4526f78fef32">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by maninhill** [comment]
v2.10-lts 版本已经发布，请在最新版本上面验证，有问题请 re-open。
