### ISSUE TITLE
[Feature]添加视图-视图标题文本框不支持复制黏贴只能手输，建议优化

### ISSUE THREAD

**Issue by huguangya** [dataease/dataease#874]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/54281046/134675841-c25bbae1-37dd-4284-b239-045d803145d4.png)

**Comment by yayanpei** [comment]
非常感谢您的反馈，该需求我们先评估一下，您可以通过浏览器自带的复制功能，复制名称，如下图
![image](https://user-images.githubusercontent.com/84168063/134791047-79692a35-56cf-4e56-842c-9320fff1d828.png)
