### ISSUE TITLE
[Feature]sql 数据集创建时期望像数据库数据集一样携带comment信息

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#8748]
DataEase 版本:
v1.18.12

**请描述您的需求或者改进建议.**
问题：
数据库数据集创建时会自动携带comment信息作为字段名称，而sql数据集创建时则没有携带comment信息。
![image](https://github.com/dataease/dataease/assets/45967454/111f9c1a-03d7-43cd-9355-9c3f75753a46)
![image](https://github.com/dataease/dataease/assets/45967454/82cc49f0-9eb4-471c-9489-c06e082b79d3)

改进意见：
sql数据集创建时期望像数据库数据集一样携带comment信息

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，sql数据集是根据输入的sql语句解析的，因此无法携带原始字段comment信息。
