### ISSUE TITLE
[Bug]内容格式的百分比未生效

### ISSUE THREAD

**Issue by wml3** [dataease/dataease#875]
**DataEase 版本**
v1.2.0

**浏览器版本**

**Bug 描述**
如题，在视图中编辑

**Bug 重现步骤(有截图更好)**
1.视图中折线图，编辑样式，标签显示，内容格式
2.选择{d}，不显示百分比
3.
<img width="799" alt="不生效" src="https://user-images.githubusercontent.com/49503874/134757470-2d75aa8d-57c3-4273-a0a4-dd72786f6e6e.png">

**Comment by wml3** [comment]
另外，仪表盘的这个地方的内容格式没有使用说明

**Comment by yayanpei** [comment]
非常感谢您的反馈，可能格式说明不够清晰，我们再优化一下。您将内容格式设置为：{c}%，应该就可以了

**Comment by wml3** [comment]
这样的话，增加了“%”，数值没有转换为百分比，比如原来的数值 是0.5，百分比为50%，加了这个后为0.5%

**Comment by yayanpei** [comment]
目前是需要在原数据中换算好，系统还不支持数值格式转换，比如转换为百分比，单位换算为千等，我们已经规划增加这部分优化了，敬请关注。

**Comment by wml3** [comment]
好的，期待新功能
