### ISSUE TITLE
[Feature] 参数优化，参数可在where条件之前

### ISSUE THREAD

**Issue by codegit10001** [dataease/dataease#8753]
DataEase 版本:
1.18.17

**请描述您的需求或者改进建议.**

目前只支持参数放置在where条件之后，希望支持参数可以在select 语句之后，where条件之前，这样用户能灵活配置sql数据集。input_param作为一个手动输入的常数，在sql数据集上用处很大。

select 
   *, #{input_param} as constant
from 
  table

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，如果将参数放置在select后，可能会引起数据集结构的变化，目前暂时没有计划支持该功能。

**Comment by codegit10001** [comment]
> 感谢您的反馈，如果将参数放置在select后，可能会引起数据集结构的变化，目前暂时没有计划支持该功能。

我理解要是需要做数据同步的话会引起变化，但是sql数据集应该没有啥问题啊，sql数据集每次都需要去数据库查询的。
而且可以在sql数据集上做一个用户可选的设置，参数默认放在where条件之后，用户可自行设置取消参数必须放在where条件之后。
这样用起来效果会更好，我们的场景用户经常需要输入自定义的一些数字。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，按照您上述的sql语句，不会引起数据集结构的变化，支持是没有问题的，但是如果放开，要考虑用户的其他使用情况，是会引起数据集结构的变化，因此经过综合评估，我们还是保持现状。
