### ISSUE TITLE
[Feature] 下拉树组件隐藏空值选项

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#8754]
DataEase 版本:
v1.18.17

**请描述您的需求或者改进建议.**
如下所示，当存在空值时，对其进行隐藏。
![image](https://github.com/dataease/dataease/assets/30063018/4f8fa62e-5fa0-4024-a894-db5bffc7c195)

**Comment by xuwei-fit2cloud** [comment]
我们考虑处理一下。
