### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by hao65103940** [dataease/dataease#876]
**DataEase 版本**
v1.2.0

**浏览器版本**

版本 93.0.4577.82（正式版本） (arm64)
**Bug 描述**
当在数据集中更换原来的指标数据项为维度的时候，这个时候视图已经保存了原来的指标项，现在已经更换了为了维度，但视图还能展示原来的指标项

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/33945037/134791208-90ed9d28-553f-408d-b27d-ffa5ae19c2b7.png)

2.
3.

**Comment by yayanpei** [comment]
感谢您的反馈，视图保存时，该字段是作为视图的指标项。如果数据集的该字段后面再调整，视图是不自动修改的。
