### ISSUE TITLE
[Bug]v1版本 富文本框插入表格 有很多问题

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8760]
安装包安装 1.18.17
问题1：在显示1上面插入表格，拖动列宽没什么问题，但是如果把页面放在显示器2上，拖动某列其他的会跟着乱动。

https://github.com/dataease/dataease/assets/141667200/b8e9edf5-538a-461c-b495-6856eb018303

问题2：点后面的格，总是在操作前面（新插入的列）

https://github.com/dataease/dataease/assets/141667200/972e16a1-4d01-439b-a431-410ae13c4eef

问题3：像这种新插入的一行，就没法往里输入东西

https://github.com/dataease/dataease/assets/141667200/2df68d31-7185-4722-9d77-91aa9f4c416b

**Comment by BBchicken-9527** [comment]
感谢反馈，我们后续版本优化一下；
