### ISSUE TITLE
[Feature]视图计算字段支持设置参数，跟过滤组件绑定

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#8762]
DataEase 版本:
v1.18

**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/89771514/ceb8b057-d8dc-45cc-a78b-0590335573a6)
希望视图计算字段支持设置参数，比如：[字段] * ${参数}
参数能够做到跟过滤组件（文本搜索组件/数值过滤组件）绑定，这样就能实现类似下面的效果：

<img width="866" alt="image" src="https://github.com/dataease/dataease/assets/89771514/02ebe68d-3cc9-45b0-92ea-ea1cadafbc75">

**Comment by xuwei-fit2cloud** [comment]
技术上可以实现，我们再等待一下相关需求反馈。
