### ISSUE TITLE
[Bug]按SQL数据集，每次重新编辑一次数据集(不做任何修改)，视图里面的过滤条件就无效

### ISSUE THREAD

**Issue by SloanGao** [dataease/dataease#878]
**DataEase 版本**
   v1.2.2

**浏览器版本**
  

**Bug 描述**
   按SQL数据集，每次重新编辑一次数据集(不做任何修改)，视图里面的过滤条件就无效，每次需要重新删除再次添加才可以生效

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by SloanGao** [comment]
另外 编辑SQL数据集时，指定字段名称，每次重新编辑时，指定字段名称会被还原，如下红色区域字段，会被还原原始字段
![image](https://user-images.githubusercontent.com/37204403/134794931-b83809c6-da0f-4529-99d2-36aaac26be64.png)

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 版本已处理。
