### ISSUE TITLE
[Bug]v1版本 日志消息保留时间，即使设置了，过期的日志还会存在

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8787]
v1.18.16 安装包安装
![540b3ad282b8a73f1bec902efa60cee](https://github.com/dataease/dataease/assets/141667200/a7bfaa82-163e-4812-9aab-f81d6660400f)
![dfc2900c67b251b4c2bf42d3b35376d](https://github.com/dataease/dataease/assets/141667200/789a47ff-9727-4441-89d4-b075248d71a1)

**Comment by xuwei-fit2cloud** [comment]
系统参数里的日志保留时间，对应的是【操作日志】模块里的日志时间，不是系统的日志时间。
要控制系统日志文件的话，需要修改 /opt/dataease/conf/dataease.properties文件，通过下列参数：

logging.file.history=30
logging.file.size=50MB

logging.file.history空值日志文件数量，logging.file.size控制单个日志文件大小。

**Comment by wolf-kingx** [comment]
好的 谢谢

**Comment by wolf-kingx** [comment]
这个之后能不能加到配置文件中呢，原来的文件里面也有啥，大家都不知道可以这样写。
