### ISSUE TITLE
[Feature] v2 数据大屏缺少过滤组件功能

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#8791]
DataEase 版本:
2.4.0

**请描述您的需求或者改进建议.**
仪表板是有过滤组件可实现添加的，但是数据大屏居然没有过滤组件。
![image](https://github.com/dataease/dataease/assets/45967454/bdf888ad-fb0c-419b-b084-498031eade7c)
![image](https://github.com/dataease/dataease/assets/45967454/f25fa2f4-e0a9-4e12-bb54-e3730aaad289)

**Comment by xuwei-fit2cloud** [comment]
大屏的主要目的是展示，而不是交互，所以目前没有考虑加过滤组件的功能，如果反馈比较多的话，我们再考虑。
