### ISSUE TITLE
[Feature] v2 创建数据集时，无法携带数据库表中的comment信息，希望加上这个功能，v1 都有。

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#8809]
DataEase 版本:
2.4.0

**请描述您的需求或者改进建议.**
v2 创建数据集时，无法携带数据库表中的comment信息，希望加上这个功能。v1 创建数据库数据集都有comment信息会自动携带。
<img width="1473" alt="image" src="https://github.com/dataease/dataease/assets/45967454/43b6c516-be0b-47fb-a45d-eeb705cdd091">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，v2.5版本中已支持该需求，请等待新版本发布。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
