### ISSUE TITLE
[Bug]1.18.17提示站点不安全、左右拉表格之后，表格列错位

### ISSUE THREAD

**Issue by songgang1997** [dataease/dataease#8810]
**DataEase 版本**
1.18.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包离线升级

**浏览器版本**
win10 edge

**Bug 描述**
1.页面提示此站点不安全输入用户名和密码
2.antv明细表表格设置滚动播放，鼠标滑轮控制无法自由上下滑动
3.表格不支持自定义列宽，希望再1.18.XX版本上实现此功能（需求）
4.左右拉表格之后，表格列错位
**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/35589880/28a3fdf1-b0d4-4d4b-b30a-56345953ca29)
![image](https://github.com/dataease/dataease/assets/35589880/f1745acb-9c0a-48eb-8d13-0f60032b2419)
![image](https://github.com/dataease/dataease/assets/35589880/b581f27a-92a0-4d89-bc44-d0a5e9a86c25)
![image](https://github.com/dataease/dataease/assets/35589880/8ad897b7-e91d-4270-8a68-1a4db89ade03)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前你说的问题1、3已经修复了，第2个问题的滚动配置本身是用于大屏显示中的，是不会去手动再滚动的，所以这里我们目前没有考虑需要优化，问题4我们这边修复一下，会在下个版本上线；
