### ISSUE TITLE
[Feature]希望支持弹窗功能

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8816]
大屏上的显示很多条数据，根据我点击的条目做主键返回我要的数据到一个新的页面或者在当前页面弹窗。

**Comment by xuwei-fit2cloud** [comment]
不是很明白您的意思。
这个需求具体是哪个版本的需求呢？
点击的条目是什么？是表格组件的单元格？是柱状图的柱？当前两个版本应该都支持跳转功能，不能满足使用场景吗？

**Comment by wolf-kingx** [comment]
![b7520431975430fee82564b203a37f8](https://github.com/dataease/dataease/assets/141667200/d25a07df-9bf1-4322-b0a6-3e26ae9044eb)
点击某一个数据，弹窗显示这一条数据的详细内容。
v2版本，目前是表格有这种需求。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，建议通过跳转或者联动明细数据实现。
