### ISSUE TITLE
[Bug]Oracle日期函数无法使用

### ISSUE THREAD

**Issue by 172151295** [dataease/dataease#8822]
**DataEase 版本**
2.3.1

**Bug 描述**

Oracle时间函数报错，无法使用例如 SYSDATA

**Comment by BBchicken-9527** [comment]
感谢反馈，是不是手误打错了应该是sysdate，目前我们应该是支持的；
![image](https://github.com/dataease/dataease/assets/84372766/07fe0818-7e4c-4069-8356-50201e820a90)
