### ISSUE TITLE
使用透视表，这个平均值就是视图计算出来的，他并没有字段可以在指标或者维度上可以看到，如果通过改变其他字段的精度，达到改变视图总计平均值字段的目的，那么这个算出来平均值会失去精度。

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8826]
使用透视表，这个平均值就是视图计算出来的，他并没有字段可以在指标或者维度上可以看到，如果通过改变其他字段的精度，达到改变视图总计平均值字段的目的，那么这个算出来平均值会失去精度。

_Originally posted by @wolf-kingx in https://github.com/dataease/dataease/issues/8804#issuecomment-2029038023_

**Comment by xuwei-fit2cloud** [comment]
我们先讨论一下，暂时还不想为这个功能增加设置项。
