### ISSUE TITLE
[Bug]仪表板编辑||查询视图数据未将【已删除文本/时间/数字过滤组件】的filter对象删除

### ISSUE THREAD

**Issue by gcfanjiawen** [dataease/dataease#883]
**DataEase 版本**
线上demo环境

**浏览器版本**
Microsoft Edge
版本 93.0.961.52 (官方内部版本) (64 位)

**Bug 描述**
查询视图数据未将【已删除文本/时间/数字过滤组件】的filter对象删除。（已删除的组件选择过筛选值，导致查询带有已删除的条件）

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/42668877/134798425-215f3f2e-7898-404d-82ed-bf85be7dc08a.png)

**Comment by gcfanjiawen** [comment]
补充： 通过按键盘【Delete】进行组件的删除操作，会有上述情况。通过鼠标点击删除按钮进行删除操作，无上述情况。

**Comment by xuwei-fit2cloud** [comment]
v1.4.0 版本已移除按键操作。
