### ISSUE TITLE
明细图表可不可添加合并单元格的功能

### ISSUE THREAD

**Issue by Bing-q** [dataease/dataease#8830]
使用明细图表时，比如是一对多的关系，就会一直显示a-b，a-c，a-d，添加合并单元格之后就是 a-b，c，d，看起来也不是那么繁琐

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，我们在近期的版本中支持一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
