### ISSUE TITLE
[Bug]连接API 数据源在数据源校验的时候数据预览有数据，但是变成数据集就没有数据了

### ISSUE THREAD

**Issue by spritelyl** [dataease/dataease#8831]
**DataEase 版本**
V1.18.14

**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**

**Bug 描述**
在数据源校验的时候数据预览有数据，但是变成数据集就没有数据了

**Bug 重现步骤(有截图更好)**
1.连接api 数据源，预览有数据  

![image](https://github.com/dataease/dataease/assets/50016789/380961ce-3774-4390-a499-3ef2e5468797)

2. 变成数据集就没有数据了
<img width="1593" alt="e1d906310cbaaed791be0227ef4e5a4" src="https://github.com/dataease/dataease/assets/50016789/72e55805-ab9c-4c35-a53c-f8d2c15cf097">

3. 执行是成功的
<img width="1609" alt="7a467618bef83826c306d79bbffdd98" src="https://github.com/dataease/dataease/assets/50016789/a93e92b7-4548-4ece-ac9c-5c4b09aafcfc">
4.  接口返回结果如下：
![image](https://github.com/dataease/dataease/assets/50016789/4c4db9b9-c76c-47d4-bba4-baef47f235a4)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前最新版本的测试环境我看了一下是没问题的，建议你升级一下看看；

**Comment by spritelyl** [comment]
升级到了v1.18.18 还是有问题

**Comment by huipeng0015** [comment]
**版本v1.18.18**
**1.数据源**
<img width="1884" alt="9bd2ee6fec2a1f2d208fd5fb0ec26d9" src="https://github.com/dataease/dataease/assets/55947818/84f18c7d-8064-4749-9ea6-9592674e160c">
**2.API数据集**
<img width="1167" alt="7ff956f7aefba04cc0eac7bdb5fdb6a" src="https://github.com/dataease/dataease/assets/55947818/8ebf8577-0d43-49c1-bde9-63b3cba9ce52">
