### ISSUE TITLE
[Feature]数据大屏能否隐藏明细表表头、且隐藏导出图标

### ISSUE THREAD

**Issue by hzhwyh0116** [dataease/dataease#8834]
DataEase 版本:
V2.4.0

**请描述您的需求或者改进建议.**
1、明细表能否隐藏表头
2、能否隐藏导出图标

需求场景：
1、明细表只展示一列去表头在大屏左侧展示可用作类似 Tab 的页面切换效果
2、跳转的小图标希望能用户自定义是否显示，否则对于一些不展示标题的视图来看比较突兀
![image](https://github.com/dataease/dataease/assets/89765365/25c5532d-2090-4bb1-bf54-6df3c26930b9)

**Comment by xuwei-fit2cloud** [comment]
技术上是可以实现的，我们后续会排期支持。

**Comment by hzhwyh0116** [comment]
感谢支持

**Comment by hzhwyh0116** [comment]
表头的排序图标希望也可以选择隐藏或展示，感谢🙏
![image](https://github.com/dataease/dataease/assets/89765365/d56a10fc-2c64-438d-9ade-da22e10e4396)
