### ISSUE TITLE
[Bug] 编辑自定义 SQL 时报错

### ISSUE THREAD

**Issue by hzhwyh0116** [dataease/dataease#8837]
**DataEase 版本**
 V 2.4.0

**运行方式(安装包运行 or 源码运行 ?)**
 安装包

**浏览器版本**
 chrome

**Bug 描述**
 编辑自定义 SQL 时报错

**Bug 重现步骤(有截图更好)**
1.导入 Excel 数据源
2.创建 Excel 数据集，编写 SQL 为：select * from 表名，保存成功
3.编辑 刚刚创建好的 SQL 数据集，修改查询字段  select 字段 1,字段 2 from 表名 运行正常，但保存报错
4.报错如下（规律改变数据集字段就报错，只要不改变数据集结果字段是可以编辑 SQL 的）
![image](https://github.com/dataease/dataease/assets/89765365/7570f782-e3be-45f9-a05a-fd63a8f8f79b)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，你可以尝试升级到最新版本看看；

**Comment by hzhwyh0116** [comment]
我理解底层我们是保存数据集时在缓存中创建了一个表，所以当我们编辑 SQL，有字段变化的时候（比如我新增一个字段）那缓存中的表结构无法变化而报错

所以目前我要避开报错的操作是：1、把我之前新建的数据集删除掉；2、重新创建一个新的数据集

那有没有可能我在编辑的时候后台帮我处理掉，直接把之前的表结构干掉重新保存，就不会报错了吧？感觉这样用户体验更好一点
