### ISSUE TITLE
[Feature]移动视图-不支持批量移动，建议优化

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#884]
**请描述您的需求或者改进建议.**
目前移动视图，只能单个移动，且每次移动之后，左侧视图栏会全部关闭到一级菜单，非常不方便，建议优化。

**Comment by yayanpei** [comment]
非常感谢您的反馈，菜单关闭的情况，我们尽快优化。

**Comment by xiebei-l** [comment]
批量移动视图的功能会考虑做吗？

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
