### ISSUE TITLE
[Bug] 数据大屏预览模式下跳转当前页面失败

### ISSUE THREAD

**Issue by hzhwyh0116** [dataease/dataease#8840]
**DataEase 版本**
 V2.4.0

**运行方式(安装包运行 or 源码运行 ?)**
 安装包运行

**浏览器版本**
Chrome 

**Bug 描述**
数据大屏预览模式下跳转当前页面失败

**Bug 重现步骤(有截图更好)**
1.数据大屏的图表 a 设置跳转，跳转类型选择：数据大屏；打开方式选择：当前页面，保存
2.预览刚刚保存的数据大屏，点击图表跳转时浏览器地址发生变化却未完成跳转动作
3.若选择打开方式为：新开页面 ，预览模式下可以正常跳转打开新页面

**Comment by xuwei-fit2cloud** [comment]
我们没有复现您说的情况，麻烦打开浏览器调试模式，看看跳转的时候是否有相关错误信息，谢谢。

**Comment by hzhwyh0116** [comment]
1、从这里进入的预览页面
![image](https://github.com/dataease/dataease/assets/89765365/35837124-6e6b-413c-9b41-bc7c08edf3d7)
2、页面预览链接如下：http://democenter.fit2cloud.com:35005/#/preview?dvId=962788699974799360
![image](https://github.com/dataease/dataease/assets/89765365/44818c13-dab2-44e8-a36f-b238b63cc1d1)
3、点击图表跳转，链接变化但页面无变化，此时链接为：http://democenter.fit2cloud.com:35005/#/preview?dvId=956995574262009856&jumpInfoParam=eyJvcHRpb24iOiJqdW1wIiwibmFtZSI6IjE3MDk1NDUyMjE2OTAiLCJ2aWV3SWQiOiI3MTgwNDYyMjk5MjY4NzgwMDMyIiwiZGltZW5zaW9uTGlzdCI6W3siaWQiOiIxNzA5NTQ1MjIxNjkwIiwidmFsdWUiOiJDROWPium7keiDtuWUseeJhyJ9XSwicXVvdGFMaXN0IjpbXSwic291cmNlVHlwZSI6InRhYmxlLWluZm8iLCJzb3VyY2VEdklkIjoiOTYyNzg4Njk5OTc0Nzk5MzYwIiwic291cmNlVmlld0lkIjoiNzE4MDQ2MjI5OTI2ODc4MDAzMiIsInNvdXJjZUZpZWxkSWQiOiIxNzA5NTQ1MjIxNjkwIn0%3D
未发出请求，控制台无报错
![image](https://github.com/dataease/dataease/assets/89765365/ba78567a-8348-4ab1-8f82-756abefeb71c)

**Comment by xuwei-fit2cloud** [comment]
收到，我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
