### ISSUE TITLE
[Feature] 明细图表支持单元格合并

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#8845]
DataEase 版本:

1.18.17
**请描述您的需求或者改进建议.**
支持维度值一样的，手动合并单元格（区别于透视表）

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，重复需求，请参考issue：https://github.com/dataease/dataease/issues/8830

**Comment by xuwei-fit2cloud** [comment]
v1不再支持该功能，请使用v2版本。
