### ISSUE TITLE
[Feature]希望数据集-表名搜索不区分大小写

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#8852]
DataEase 版本:
2.4.0

**请描述您的需求或者改进建议.**
希望数据集-表名搜索不区分大小写
![image](https://github.com/dataease/dataease/assets/83771182/a43e868a-c02a-4d57-a9c7-90f6cc15dc92)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。
