### ISSUE TITLE
[Bug]仪表板-字段显示名称修改完成后点击更新图标，数据视图无变化

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#8854]
**DataEase 版本**
2.4.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome120

**Bug 描述**
仪表板-字段显示名称修改完成后点击更新图标，数据视图无变化

**Bug 重现步骤(有截图更好)**
1.仪表板-字段显示名称修改完成后点击更新图标，数据视图无变化
2.连带问题 重命名数据集中字段名称后，直接点击更新图表数据字段依旧无变化，只能删除现有维度中字段重新配置刷新后生效。
3.
![image](https://github.com/dataease/dataease/assets/83771182/49b1b55f-a34e-419d-8d41-ba81841026b8)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没发现你说的这个问题，可以尝试更新一下最新版本；
![image](https://github.com/dataease/dataease/assets/84372766/34d1c246-2bee-48a0-aa3c-0f81abf425c0)
