### ISSUE TITLE
[Feature]仪表板-日期字段类型无'月日'/'日'显示，希望能增加

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#8855]
DataEase 版本:

2.4.1
**请描述您的需求或者改进建议.**
仪表板-日期字段类型无'月日'/'日'显示，希望可以增加，当制作每天视图时影响显示体验
![image](https://github.com/dataease/dataease/assets/83771182/89cd35ef-d91f-42b6-9615-957e7ad0308b)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，日期显示格式较多，此处是内置了常用的一些格式，如果需要展示「月日」或者「日」，建议您通过计算字段方式获取。
