### ISSUE TITLE
时序数据库tdengine集成到数据源

### ISSUE THREAD

**Issue by star012388** [dataease/dataease#8857]
DataEase 版本:
V2

**请描述您的需求或者改进建议.**
时序数据库tdengine集成到数据源

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池中，但近期暂时没有规划进行支持，待有更多同类需求后，我们再进行下一步的规划。

**Comment by star012388** [comment]
好的
