### ISSUE TITLE
[Feature]移动端增加 pad 界面布局

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#8858]
DataEase 版本:
v2
移动端配置界面增加一个 pad布局；
开启移动端，自动识别手机和 pad，显示制作好的布局页面。

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
我们会考虑将pad识别为pc端显示，目前没有计划针对pad增加布局支持。
