### ISSUE TITLE
[Feature] 过滤组件区分不同富文本视图

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#8867]
DataEase 版本:
v 2.5.0

**请描述您的需求或者改进建议.**
过滤组件配置 富文本 相关视图时，如果有多个无法区别
<img width="1216" alt="image" src="https://github.com/dataease/dataease/assets/45852479/0b3fcaa0-da45-4274-8e63-d51d2c43dba4">

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们会做一下相关优化。

**Comment by xuwei-fit2cloud** [comment]
请升级版本。
