### ISSUE TITLE
[Feature] v2 能否增加对现已经处理好的数据集进行二次利用，进行数据关联的能力

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#8869]
DataEase 版本:
v2.4.0

**请描述您的需求或者改进建议.**
v2 能否增加对现已经处理好的数据集进行二次利用，进行数据关联的能力
![image](https://github.com/dataease/dataease/assets/45967454/ccf1c269-4e38-4a59-9996-ce30ec9c8878)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划进行支持，建议您在一个数据集内对多表进行关联，生成需要的数据集。
