### ISSUE TITLE
[Bug]编辑仪表板报timeout of 10000ms exceeded

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#888]
**DataEase 版本**
v1.2.0

**浏览器版本**
谷歌浏览器版本 93.0.4577.82（正式版本） (x86_64)

**Bug 描述**
使用仪表盘编辑是，一直在刷新页面，然后报错，报错如图所示

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/70566485/134842547-bf566471-b9ae-47f9-b1d1-e49ed4b1d1a6.png)
1.编辑仪表盘
2.编辑视图
3.保存返回仪表盘，有较大的几率出现此报错

**Comment by xuwei-fit2cloud** [comment]
读取数据超时导致，后续我们会优化一下

**Comment by xuwei-fit2cloud** [comment]
v1.4.0 版本支持在系统管理里设置超时时间
