### ISSUE TITLE
[Bug]v1.18.17版本 使用表格表头快捷排序后，进行跳转，跳转之后的值与排序后的表对不上，这个快捷排序之后的跳转应该还是根据之前的值进行的，表格表面上排序正常了，这背后的链接啥的可能都没变。

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8888]
![ebaf7b3db6faccbe22221eb920fe279](https://github.com/dataease/dataease/assets/141667200/e63db324-0695-4687-909c-7b217331a785)
![a9a0d0cbc7ffbca8a25ccf7c7ce3045](https://github.com/dataease/dataease/assets/141667200/48da753e-fc84-4550-928b-ed3047a2562f)
![2f54f8f5e8641cbcc9e3c66833db675](https://github.com/dataease/dataease/assets/141667200/21a44ee8-3d2e-4767-9821-d2128025c427)
![aac212481f13278e41667b3afd55d7a](https://github.com/dataease/dataease/assets/141667200/3353636c-dd7a-47a9-a8e6-e15d1e0dc6ba)
![600e3b11aaae666f7846c8c0a5a5b7f](https://github.com/dataease/dataease/assets/141667200/38cf0574-945a-494e-ae08-0d3b7f5fdea8)

线下我可以提供视频

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在这个版本进行修复；

**Comment by xuwei-fit2cloud** [comment]
新版本已处理，请更新版本。
