### ISSUE TITLE
[Bug]仪表盘中如果有特殊字符保存报错

### ISSUE THREAD

**Issue by xiebei-l** [dataease/dataease#889]
**DataEase 版本**
![image](https://user-images.githubusercontent.com/70566485/134844465-090b3f6d-d769-4eeb-923e-9f3ff5799162.png)

**浏览器版本**
谷歌浏览器版本 93.0.4577.82（正式版本） (x86_64)

**Bug 描述**
仪表盘保存爆粗

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/70566485/134844303-7bfdfbb4-3c8a-4e3e-a774-df1bf199270b.png)
![image](https://user-images.githubusercontent.com/70566485/134844836-65d20fbf-9f94-4e64-b66a-a2379d9379cf.png)
1.编辑仪表盘后保存仪表盘
2.仪表板中选中左边操作栏其它
3.编辑后保存报错

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，目前我们还没有支持特殊字符的文本内容。
后续我们处理一下。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
