### ISSUE TITLE
[Feature]统一各组件时区

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#8898]
DataEase 版本:
v1, v2

原因是在将时间戳转为时间时发现差 8 小时，因为保存数据的 doris、mysql 都是 UTC 时区，建议将所有组件统一设置为 CST 

v1  组件: kettle、doris、mysql
v2 组件：mysql-de、apisix-etcd、apisix-dashboard

调整 docker-compose 文件
添加：
    privileged: true
    environment:
      - TZ=Asia/Shanghai
![图片](https://github.com/dataease/dataease/assets/48307752/5cf76b01-af16-408b-9d96-a3534f0112ed)

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们统一下时区。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，由于日期过滤数据，各数据库之间的差异较大，当统一时间戳转换后，发现时区问题还是存在的。
