### ISSUE TITLE
[Bug]仪表板的视图导出为图片放大会失真，不能等比例缩放

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#8916]
**DataEase 版本**
v2.4

**运行方式(安装包运行 or 源码运行 ?)**
离线安装

**浏览器版本**
版本 123.0.6312.88（正式版本） （64 位）

**Bug 描述**
仪表板的视图导出为图片放大会失真，不能等比例缩放。

**Bug 重现步骤(有截图更好)**
单个视图放大效果
![image](https://github.com/dataease/dataease/assets/43403764/1ef01c06-6d9a-48e6-abeb-787faff94c76)
仪表板导出da放大效果
![image](https://github.com/dataease/dataease/assets/43403764/d5069180-4f9d-4236-aae7-5bf280fbdb0c)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。
