### ISSUE TITLE
[Bug]v2.5版本 表格使用斑马纹的时候，如果开启显示序号，序号不带斑马纹

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#8926]
v2.5 安装包安装
![image](https://github.com/dataease/dataease/assets/141667200/84ad7f7a-8dc2-4aad-9881-83667b00a28b)

**Comment by wolf-kingx** [comment]
汇总表

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行优化；
