### ISSUE TITLE
[Feature] v2 能否增加甘特图，来展示某个项目的进度

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#8930]
DataEase 版本:
2.4.0

**请描述您的需求或者改进建议.**
v2 能否增加甘特图，来展示某个项目的进度

**Comment by xuwei-fit2cloud** [comment]
可以的，我们会在近期版本将v1版本的区间条形图移植过来。

**Comment by 35plus** [comment]
东区有个客户，需要甘特图，目前的区间条形图，展示的是 开始和结束时间，客户 还想要任务进度也展示出来。下面这个是客户数据。
[日期 甘特图.xlsx](https://github.com/user-attachments/files/16490090/default.xlsx)
