### ISSUE TITLE
[Feature]表格当数据表格宽度显示不全时，可以鼠标悬浮显示完整信息

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#8936]
DataEase 版本:
1.18.17

**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/109720729/8dd48501-5c43-4113-8dc5-bbc8a96574f8)

**Comment by xuwei-fit2cloud** [comment]
可以将单元格提示打开。
![图片](https://github.com/dataease/dataease/assets/1892127/45d2c204-30ae-44d3-a941-4ce5894b0921)
