### ISSUE TITLE
[Feature] 建议可以改进下区间条形图，（标签显示数值，而不是区间范围）

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#8951]
DataEase 版本:
v1.18.17

**请描述您的需求或者改进建议.**
使用区间条形图制作出来的甘特图效果如下：
<img width="1064" alt="image" src="https://github.com/dataease/dataease/assets/45967454/f050f85e-d9f9-4951-af78-31d95e6f900c">

正常逻辑下的甘特图应该显示成这样：
<img width="1191" alt="image" src="https://github.com/dataease/dataease/assets/45967454/fdb347e4-4934-4ec2-82ba-19509c21503d">

**Comment by xuwei-fit2cloud** [comment]
已收到需求，我们尝试优化一下。
