### ISSUE TITLE
[Bug]数据源是sqlsever，使用数据库数据集能正常保存，使用关联数据保存时DE服务会挂掉。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#8959]
**DataEase 版本**
1.18.17

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

chrome120
**Bug 描述**
数据源是sqlsever，使用数据库数据集能正常保存，使用关联数据保存时DE服务会挂掉。

**Bug 重现步骤(有截图更好)**
1.连接sqlserver数据源保存正常。
<img width="1280" alt="17bea1700f6e303092815802182a1b8" src="https://github.com/dataease/dataease/assets/83771182/79ab7219-6a2f-4424-a203-1bffcff9fc99">
2.新建数据库数据集保存保存正常
3.新建关联数据集保存，de服务挂掉，日志见附件。字段格式基本都是varchar
<img width="479" alt="6b5410f036c9873703007cc2e228205" src="https://github.com/dataease/dataease/assets
/83771182/150ebb52-2100-47ff-b0f8-0c5b36bcea04">
[error.log](https://github.com/dataease/dataease/files/14863758/error.log)
[info.log](https://github.com/dataease/dataease/files/14863757/info.log)

**Comment by maninhill** [comment]
重复提交。
