### ISSUE TITLE
[Bug]数据源是sqlsever，使用数据库数据集能正常保存，使用关联数据保存时DE服务会挂掉。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#8960]
**DataEase 版本**
v2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

chrome120
**Bug 描述**
数据源是sqlsever，使用数据库数据集能正常保存，使用关联数据保存时DE服务会挂掉。

**Bug 重现步骤(有截图更好)**
1.连接sqlserver数据源保存正常。
<img width="1280" alt="17bea1700f6e303092815802182a1b8" src="https://github.com/dataease/dataease/assets/83771182/79ab7219-6a2f-4424-a203-1bffcff9fc99">
2.新建数据库数据集保存保存正常
3.新建关联数据集保存，de服务挂掉，日志见附件。字段格式基本都是varchar
<img width="479" alt="6b5410f036c9873703007cc2e228205" src="https://github.com/dataease/dataease/assets/83771182/b4939068-612c-4e81-a436-0347f3117b54">

[error.log](https://github.com/dataease/dataease/files/14863758/error.log)
[info.log](https://github.com/dataease/dataease/files/14863757/info.log)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你的数据量是多少？如果是sql进行关联是否在sql语句中就进行了join，大改每个数据集join了多少次？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
