### ISSUE TITLE
数据导出列表预览显示Bug

### ISSUE THREAD

**Issue by wt7060** [dataease/dataease#8963]
**DataEase 版本  V1.18.17
数据导出功能，列表预览中有数据，但是字体和背景都是白色，无法正常预览数据，建议列表可以跟随主题色或者便于区分颜色，能够正常的显示数据列表。
![image](https://github.com/dataease/dataease/assets/30554104/18de9e44-d763-4f93-8827-f5f836fc5dc4)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你的表格背景色的不透明度是不是调整到了0？

**Comment by wt7060** [comment]
是的，透明度0%，我应该要给他改成100才对吧，OK，了解，我已经修改，现在可以正常显示了，我以为导出的界面背景和界面背景不是关联的呢，再次感谢提醒。
