### ISSUE TITLE
[Feature]外部参数设置支持时间范围和起始时间

### ISSUE THREAD

**Issue by xiaoxiao261258** [dataease/dataease#8968]
DataEase 版本:1.18.18

**请描述您的需求或者改进建议.**
需求1、外部参数设置支持时间范围，可以输入开始时间和结束时间，并且可以基于这个时间范围过滤图表中的数据。
需求2、外部参数设置支持起始时间，可以输入起始时间，并且可以基于这个时间过滤图表中的数据。

**Comment by xuwei-fit2cloud** [comment]
可以使用如下格式：
{"queryTime" : [1xxxxxxxxxxxx,1xxxxxxxxxxxx]}

queryTime为参数名，后面list中包含时间范围的开始时间和结束时间的13位时间戳。

**Comment by xiaoxiao261258** [comment]
> 可以使用如下格式： {"queryTime" : [1xxxxxxxxxxxx,1xxxxxxxxxxxx]}
> 
> queryTime为参数名，后面list中包含时间范围的开始时间和结束时间的13位时间戳。

你好，对于时间过滤组件，可以指定开始和结束时间，但是对于外部参数，通过这种方式传过来的两个时间参数，应该如何使其生效才能过滤数据吗？

**Comment by xuwei-fit2cloud** [comment]
我们建议通过过滤组件来实现数据的过滤，在仪表板上存在过滤组件的情况下，通过外部传参的方式，与过滤组件的默认值，是有冲突的，所以我们目前还没有计划去支持。
