### ISSUE TITLE
[Bug]升级到1.18.18版本页面不定时出现“timeout of 100000ms exceeded”的错误提示

### ISSUE THREAD

**Issue by xiaoxiao261258** [dataease/dataease#8970]
**DataEase 版本**
1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome  版本 123.0.6312.88（正式版本） （64 位）

**Bug 描述**
页面不定时出现“timeout of 100000ms exceeded”的错误提示

**Bug 重现步骤(有截图更好)**
1.从1.18.17升级到1.18.18版本（中间因为网络问题，升级过程中拉取镜像失败，重试几次后解决）后，浏览页面，页面最上方的中间区域不定时出现“timeout of 100000ms exceeded”的错误提示

**Comment by BBchicken-9527** [comment]
感谢反馈，请问清缓存后是否还会出现此类提示？

**Comment by maninhill** [comment]
如果清理缓存后还有问题，请再打开 issue。
