### ISSUE TITLE
[Bug] tab组件内，过滤组件失效问题。

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#8975]
**DataEase 版本**
v1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome
版本 123.0.6312.87（正式版本） (arm64)

**Bug 描述**
Tab 组件内，放置了过滤组件，并设置了首选项，切换过滤条件后，过滤组件会失效。
在编辑界面无此问题，预览界面有该问题。

**Bug 重现步骤(有截图更好)**
1. 设置好过滤组件首选项，并将其放置到过滤组件中。
![image](https://github.com/dataease/dataease/assets/30063018/a06dee17-1b48-4c9e-93d1-0d196e2a70f6)
2. 预览界面切换过滤组件后，不再过滤视图数据。
![image](https://github.com/dataease/dataease/assets/30063018/5e3134d5-abd3-4fc7-91cc-60c8c723deca)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
