### ISSUE TITLE
[Bug]数据源创建端口号输入字母成功保存并报错

### ISSUE THREAD

**Issue by haohaoyizheng** [dataease/dataease#898]
**DataEase 版本**
1.2.0

**浏览器版本**
360

**Bug 描述**
数据源创建时，端口号输入字母，成功保存后。开始报错。报错后

**Bug 重现步骤(有截图更好)**

![image](https://user-images.githubusercontent.com/56429047/136649437-3ebf5323-a65d-408f-9bdc-ec5f95548d7c.png)

**Comment by xuwei-fit2cloud** [comment]
v1.3 已修复
