### ISSUE TITLE
[Bug]表格开启滚动，表格提示不生效。

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#8981]
**DataEase 版本**
v1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
表格开启滚动之后，表格提示不生效
**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/ccc2bedb-1442-4be9-b2cc-c40f28bd8cad)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前是不支持滚动的同时鼠标悬浮给出提示的；
