### ISSUE TITLE
[Bug]数值类型ID全部显示成了9999999999999...

### ISSUE THREAD

**Issue by rocymp** [dataease/dataease#8984]
**DataEase 版本**
2.5.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge

**Bug 描述**
数值类型ID全部显示成了9999999999999...

**Bug 重现步骤(有截图更好)**
<img width="494" alt="image" src="https://github.com/dataease/dataease/assets/7627227/80af73d6-9c30-4e9a-bd5d-2ef5a772293a">

**Comment by BBchicken-9527** [comment]
感谢反馈，受累说明一下你使用的数据源以及库中的字段类型；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
