### ISSUE TITLE
[Bug]选项卡内部设置关联存在问题

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#8985]
**DataEase 版本**
v1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Google Chrome

**Bug 描述**
选项卡内部设置关联，编辑模式都是正常的，保存后返回正式模式就失效。

**Bug 重现步骤(有截图更好)**
1.选项卡内部设置关联
2.保存后返回正式模式就失效

<img width="443" alt="bug" src="https://github.com/dataease/dataease/assets/163749505/d743878f-3c92-40ee-900c-3d8a8737ff42">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
