### ISSUE TITLE
汇总表新增由业务人员自定义按字段排序功能

### ISSUE THREAD

**Issue by 137997** [dataease/dataease#8988]
汇总表可以由业务人员在查看页面自定义按哪个字段排序数据

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该功能已经支持，如1.x版本，需要在样式中开启表头排序，如果没有该配置项，可能需要升级到较新的版本。
<img width="687" alt="image" src="https://github.com/dataease/dataease/assets/84168063/0b12857b-1805-487f-bd27-20f9bf31a335">
开启表头排序后，在预览页面可以进行排序。
<img width="490" alt="image" src="https://github.com/dataease/dataease/assets/84168063/f4d9dddd-98eb-41f2-b06b-6c9af61c648a">
