### ISSUE TITLE
[Bug]流向地图无内容显示

### ISSUE THREAD

**Issue by zhuhuaibin** [dataease/dataease#8991]
**DataEase 版本**
V1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
 谷歌123.0.6312.86

**Bug 描述**
流向地图无内容显示，但符号地图是正常显示。

**Bug 重现步骤(有截图更好)**
1.
<img width="1735" alt="315b37be317dbb4b638c8d33182d3b8" src="https://github.com/dataease/dataease/assets/50860759/88b328dc-ab18-47bf-b33d-394f60203e49">
2.
![2411c8b16f8bc0f8fdb61ade787fb2d](https://github.com/dataease/dataease/assets/50860759/d8c9fbd4-9749-4a64-99cc-aa005096e885)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
