### ISSUE TITLE
[Bug]筛选组件对选项卡中视图筛选失效

### ISSUE THREAD

**Issue by DanteL126** [dataease/dataease#8998]
**DataEase 版本**
1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 123.0.6312.106

**Bug 描述**
在线升级从1.18.15升级到1.18.18后，使用筛选组件时，选项卡中已加载好的视图无变化，切换到未加载的视图时筛选生效，但在变更筛选条件时，加载好的视图仍然无变化；在编辑状态下，筛选组件可以对选项卡中的视图生效，但是在非编辑状态下，筛选组件无法对选项卡中的视图生效生效；

**Bug 重现步骤(有截图更好)**
1.在编辑界面时筛选组件正常
![编辑界面正常](https://github.com/dataease/dataease/assets/166382002/f699b29b-7785-45a0-8ed0-ef46e6852ad6)

2.非编辑界面时筛选组件失效
![非编辑界面无法筛选](https://github.com/dataease/dataease/assets/166382002/55c00a93-ebb2-4e29-a44c-3ba9a8f6e379)

3.切换到未加载的test2中筛选组件生效
![切换到未加载的test2筛选生效](https://github.com/dataease/dataease/assets/166382002/cefa1823-47a7-47a7-afa7-d712582d0278)

4.变更筛选条件时已加载的test2筛选组件失效
![换筛选调解已加载的test2筛选失效](https://github.com/dataease/dataease/assets/166382002/17dd69dc-8721-4918-bc59-953d048fe526)

5.切换到未加载的test3中筛选组件失效
![切换到未加载的test3筛选生效](https://github.com/dataease/dataease/assets/166382002/d1fce05d-985b-40e9-b2c6-fe39af392282)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
