### ISSUE TITLE
能开发iotdb数据库不，对这个数据库有极大需求。

### ISSUE THREAD

**Issue by jiajiazyj0108** [dataease/dataease#9005]
DataEase 版本:

希望能开发iotdb数据库的支持功能，在工作中会用到。

**Comment by Sunshow** [comment]
刚好也在看，iotdb应该直接支持calcite整合，不知道有没有办法快速支持

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录进需求池中，并讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，我们先记录进需求池中，近期暂时没有计划进行排期，待有更多同类的需求后再做进一步的规划。

**Comment by maninhill** [comment]
暂无支持计划。
