### ISSUE TITLE
[Bug]sum 无法计算 case 中的结果

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#9006]
**DataEase 版本**
v2.5

**运行方式(安装包运行 or 源码运行 ?)**
安装宝
**浏览器版本**
 chrome

**Bug 描述**
sum 无法计算 case 中的结果，count 可以；
case 中必须存在 else,否则报错；
这样导致了 不能用 sum 也不能用 count。
测试 SQL 如下：

```
select 
  pay_method,
  sum(
  case when  pay_method in ('支付宝','云闪付') then 1
  else 0
  end) as 商家补贴

from transactions_sl group by pay_method
```

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前处理是calcite代为处理，根据calcite的要求必须是标准的sql语句，所以是要加上else；
