### ISSUE TITLE
日期选择器Bug

### ISSUE THREAD

**Issue by wt7060** [dataease/dataease#9007]
**DataEase 版本**：V1.18.18
BUG描述：日期选择器可能触发点击后无法收回问题，必须要选择日期后才能收回，点击触发后，再点击页面空白处无法收起，改Bug不是100%会被触发，如果触发次Bug，手动刷新页面可能能够解决。
![image](https://github.com/dataease/dataease/assets/30554104/ced74533-fb96-4352-8e2c-064ae94a475a)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问是首次点击的时候必现吗？

**Comment by wt7060** [comment]
是的，我目前遇到就是如此，点击后必须要再次点击选择日期后才能折叠回去，次Bug包括年月日期筛选和日期范围筛选两个插件都有相同Bug。
![image](https://github.com/dataease/dataease/assets/30554104/523ae721-457b-4fd5-96ca-8a99d7a1795c)

**Comment by BBchicken-9527** [comment]
嗯嗯 感谢反馈，这个问题我们已经知道了正在排查并解决，会在下个版本进行修复；
