### ISSUE TITLE
[Bug]tab组件内编辑状态下过滤组件生效，预览状态下过滤组件不生效

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#9009]
**DataEase 版本**
1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
tab组件内编辑状态下过滤组件生效，预览状态下过滤组件不生效

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/101089844/2c0da902-cbc1-4200-b623-f0050067ee54)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行处理；
