### ISSUE TITLE
[Feature] 建议查询条件增加输入框

### ISSUE THREAD

**Issue by shenxrs** [dataease/dataease#9013]
DataEase 版本: V2.5.0

**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/26434700/b8d7ea95-ca26-4e36-ac90-d3ff8fcc666e)
目前文本搜索只能下拉，建议查询条件增加输入框，查询时可自定义输入任何内容进行查询，而不是拉下框的只能选择

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，查询组件支持文本搜索已规划在v2.6版本中，请等待新版本发布。

**Comment by xuwei-fit2cloud** [comment]
请升级版本。
