### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Xakorn** [dataease/dataease#9015]
**DataEase 版本**
2.4.0

**运行方式(安装包运行 or 源码运行 ?)**
在线安装，快捷部署

**浏览器版本**
chrome

**Bug 描述**
1. ClickHouse 数据集编辑查询sql时间类型字段展示征程，但到这个柱状图直接给时间类型字段的hhmmss的分钟转minute化至yyyymmdd那个month数值
2. clickhouse 数据集 查询字段枚举值正常，但在筛选组件，这个字段去查询组件去查询，枚举值显示不全

**Bug 重现步骤(有截图更好)**
1.
![微信截图_20240409153017](https://github.com/dataease/dataease/assets/106822795/e577eb81-beab-4d60-a90c-a2d1c29e4c2a)

2.
DateTime 时间格式的字段用“年月日时分秒”格式显示异常；January应该改为分钟
![微信截图_20240409153147](https://github.com/dataease/dataease/assets/106822795/9a73cb76-c7dd-4f35-b7ec-c3741afd00e4)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你的ck的版本是多少呢？

**Comment by Xakorn** [comment]
ClickHouse 的完整版本号：24.2.1.2248
565190559
***@***.***
---- Replied Message ----
***@***.***>Date4/15/2024 ***@***.***>***@***.***>,
***@***.***>SubjectRe: [dataease/dataease] [Bug] (Issue #9015)
感谢反馈，请问你的ck的版本是多少呢？

**Comment by BBchicken-9527** [comment]
感谢反馈，应该是一个已知问题，将会在下个版本进行修复；
