### ISSUE TITLE
[Feature]增加自动根据查询条件查询数据功能

### ISSUE THREAD

**Issue by 1510350856** [dataease/dataease#9019]
DataEase 版本:V2.5.0

**请描述您的需求或者改进建议.**
例如
![image](https://github.com/dataease/dataease/assets/46345075/30d586e7-bc7e-48e6-9f43-aaeaae8bc4e8)
上图时首次打开页面按照常理来说，应当根据默认的查询条件查询数据

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，首次加载仪表板时，是根据查询条件的默认值触发查询的，建议您再检查一下，比如：是否为查询组件设置了默认值，查询组件是否关联了图表等。

**Comment by 1510350856** [comment]
![image](https://github.com/dataease/dataease/assets/46345075/dd829aa7-6dcc-4683-b9fe-5a0765f6d4bd)
我这边已经设置了组件的默认值，就是首次打开仪表盘时没有触发查询条件

**Comment by flyingdew** [comment]
@yayanpei-fit2cloud 当查询条件为时间范围并且默认值为动态时间时，确实存在这个问题

**Comment by 1510350856** [comment]
好的 谢谢您啦 这个只是建议



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月26日 08:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [dataease/dataease] [Feature]增加自动根据查询条件查询数据功能 (Issue #9019) |

@yayanpei-fit2cloud 当查询条件为时间范围并且默认值为动态时间时，确实存在这个问题
