### ISSUE TITLE
[Bug]视图页面，字段过多时，滚动条无法预览所有字段

### ISSUE THREAD

**Issue by boolean-dev** [dataease/dataease#902]
**DataEase 版本**
v1.2.3

**浏览器版本**
Microsoft Edge
版本 94.0.992.38 (官方内部版本) (64 位)

**Bug 描述**
【视图】【数据】
视图数据页面，如果表字段过多的话，则滚动条无法下拉到最下面
导致后续很多字段无法展示和操作

**Bug 重现步骤(有截图更好)**
滚动条无法下拉至最下面
![image](https://user-images.githubusercontent.com/20177406/136770087-0b9a4cfa-5660-40d2-bcbf-dffe1953dd16.png)

数据库的纬度字段
![image](https://user-images.githubusercontent.com/20177406/136770157-7590573e-675f-4492-b657-2d3594856105.png)
数据库指标字段
![image](https://user-images.githubusercontent.com/20177406/136770183-749e618b-7d44-4844-b729-7ba06e3b2dd6.png)

**Comment by boolean-dev** [comment]
我这边用谷歌浏览器也一样，Edge和Chrome 内核应该都一样，应该差别不大

**Comment by xuwei-fit2cloud** [comment]
我们环境确实无法重现该问题，看起来像是前端库的问题。

**Comment by boolean-dev** [comment]
我现在更新到最新版本，问题也已经解决了
