### ISSUE TITLE
[Feature] 数据填报支持多次填写

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#9024]
DataEase 版本:

下发一个填报任务，只要到期之前，用户可以随时新增记录，一个人填多条，可以整个预览自己填报的数据表

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，近期规划中有批量上传的功能，可通过上传excel文件实现一次新增多条填报。

**Comment by mfanoffice** [comment]
> 感谢您的反馈，近期规划中有批量上传的功能，可通过上传excel文件实现一次新增多条填报。

支持多次填写会更方便些，如果Excel 上传，涉及到下载上传操作，还有文件格式检查，在操作和代码上都会复杂。

**Comment by xuwei-fit2cloud** [comment]
允许多次上传的话，我们无法判断下发的填报任务是否处于完成状态。
通过授权用户，允许指定用户通过Excel批量上传的方式，实际上并不走填报任务，与任务状态无冲突。

目前我们并无计划对多次填写进行支持。
