### ISSUE TITLE
[Bug]升级到1.18.18后，BI中的地图定位显示功能失效。

### ISSUE THREAD

**Issue by moncat2005** [dataease/dataease#9029]
**DataEase 版本**
1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 123.0.6312.106

**Bug 描述**
升级到1.18.18后，BI中的地图定位显示功能（AntV符号地图）失效

**Bug 重现步骤(有截图更好)**
![map-error](https://github.com/dataease/dataease/assets/34859687/b85aa5ef-020e-4340-9df2-dc7469d96ea2)

跟踪chrome相关报错信息
index.896c5630.1.18.17.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at index.896c5630.1.18.17.js:1:11636
    at G (index.896c5630.1.18.17.js:1:10189)
    at index.896c5630.1.18.17.js:1:10671
    at p (vendor.dll.js:109:119582)
    at Generator.<anonymous> (vendor.dll.js:109:120909)
    at Generator.next (vendor.dll.js:109:119992)
    at o (chunk-vendors.689f373c.1.18.17.js:37:177901)
    at s (chunk-vendors.689f373c.1.18.17.js:37:178096)
    at chunk-vendors.689f373c.1.18.17.js:37:178155
    at new Promise (<anonymous>)

**Comment by xuwei-fit2cloud** [comment]
您好，您在【系统参数】的【地图设置】中查看一下【在线地图】，是否有输入有效的key，内置的key可能由于超出调用频率而失效，您可以自己申请一个免费的key试试。

**Comment by moncat2005** [comment]
已替换自己申请的高德地图Key码，登陆BI后可以看到地图。
但是创建的公共链接页面不能显示地图，这是什么原因呢？
怀疑是公共链接的js api应用中缺少key的相关信息？

**Comment by xuwei-fit2cloud** [comment]
应该不会的，您可以把浏览器的调试模式打开，看看是否有请求还未返回。
我们在测试的测试环境中并没有发现相关的问题。

**Comment by moncat2005** [comment]
目前在chrome 123.0.6312.106新版上仍旧存在以下问题：
1、更换高德地图的js api的KEY码后，第二天登陆BI系统仍然无法显示地图。
必须进入系统管理-系统参数-地图设置，显示出地图后，再回到仪表板才能正常显示地图。
2、在上述操作可以显示系统内仪表板地图的前提下，创建公共链接页面确认仍旧无法显示地图。

我卸载上述版本chrome，改为安装很老的32位版本88,X的chrome，则没有上述问题，公共链接的地图显示是正常的。

**Comment by moncat2005** [comment]
目前仍旧存在的问题：
1、更换高德地图的js api的KEY码后，第二天登陆BI系统仍然无法显示地图。
必须进入系统管理-系统参数-地图设置，显示出地图后，再回到仪表板才能正常显示地图。
2、在上述操作可以显示系统内仪表板地图的前提下，创建公共链接页面确认仍旧无法显示地图。
