### ISSUE TITLE
[Feature]透视表总计对占比类数据计算有误

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#9030]
DataEase 版本:
v1.18.18

目前透视表的汇总逻辑是数学运算，与实际值不符；
如下图：
补贴占比为视图聚合计算字段：sum(补贴值)/sum(总值)

透视表中为每个城市做了分组计算，但总计应该是 sum(补贴值)/sum(总值)
这里有没有办法处理一下总计的计算值？

![图片](https://github.com/dataease/dataease/assets/48307752/7e9e7be9-2cc6-4016-8578-a7a2d9b3a0f8)

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #6632
