### ISSUE TITLE
[Bug]【数据集】SQLServer SQL 数据集报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#9031]
**DataEase 版本**
v1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌浏览器

**Bug 描述**
DBeaver 不报错，DataEase 报错，如下截图。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/24768910/b2e6c799-9a37-4f0b-b17c-ce233824a8d3)

SQL 参考：
select
	num1,
	num2,
	num1 / num2
from
	(
	select
		count(1) as num1,
		did
	from
		zz
	group by
		did)a,
	(
	select
		count(1) as num2,
		did
	from
		zz
	group by
		did)b
where
	a.did = b.did

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by maninhill** [comment]
v2.10-lts 版本已经发布，请在最新版本上面验证，有问题请 re-open。
