### ISSUE TITLE
[Bug]下拉组件支持平铺风格展示功能未出现

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#9035]
**DataEase 版本**
1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
下拉组件支持平铺风格展示功能未出现
官方demo环境：https://dataease.fit2cloud.com/#/panel/index

![image](https://github.com/dataease/dataease/assets/89771514/ca838221-42e0-4a7c-8e8d-8f4646fac766)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，当设置为单选且配置为必填时，才可以用radio风格展示。
