### ISSUE TITLE
[Bug]AntV 漏斗图显示转换率文本颜色不支持设置，深色模式下，文字看不清晰

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#9037]
**DataEase 版本**
1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/89771514/d1d9b177-2b23-44fd-95cb-c3de0346f989)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们下个版本修复一下。

**Comment by tuobameng** [comment]
请问这个问题计划什么时候修复

**Comment by tuobameng** [comment]
> 感谢反馈，我们下个版本修复一下。


请问这个问题计划什么时候修复

**Comment by maninhill** [comment]
v2.10-lts 版本已经发布，请在最新版本上面验证，有问题请 re-open。
