### ISSUE TITLE
[Bug]数据填报，当再次手动触发已执行的任务时，出现异常

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#9038]
**DataEase 版本**
1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
数据填报，当再次手动触发已执行的任务时，出现异常：Value for name cannot be null
![image](https://github.com/dataease/dataease/assets/89771514/d5b80921-bc79-4588-9562-e170c5ec78a7)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前正是包是没有这个问题的，如果可以的话建议下载正式包尝试；
