### ISSUE TITLE
[Bug] v2 行列权限Bug：无法为普通用户角色的用户编辑行列权限

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#9039]
**DataEase 版本**
v2.5.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome/edge/safari

**Bug 描述**
无法为普通用户角色的用户编辑行列权限

**Bug 重现步骤(有截图更好)**
1. 设置Eren用户为普通用户角色
![image](https://github.com/dataease/dataease/assets/45967454/bf1e7d2a-d4b2-44ca-9fad-2522df3a7ad5)
2.为Eren用户编辑行列权限时，发现如果不给该用户单独授权，就无法编辑行列权限（普通用户不是默认具备所有资源的查看权限吗，既然都具备查看权限了，为什么无法为其分配行列权限？）
<img width="1470" alt="image" src="https://github.com/dataease/dataease/assets/45967454/c38ed710-ad4f-4a3d-9eae-082643d70091">

另外，在数据集中配置行列权限也有问题:
![image](https://github.com/dataease/dataease/assets/45967454/54a82037-65bb-4338-a9d3-c323792caf18)

**Comment by BBchicken-9527** [comment]
感谢反馈，你的第一个问题，为什么账号无法进行行列权限的配置，是因为维度不一样，你给了这个账号的角色拥有查看权限不代表这个账号本身可以查看，所以账号是无法设置行列权限的，不过这里行列权限显示高亮我这边提一个优化后期优化一下，这样避免大家误解，第二应该是用户的id可能因为网络或客户端原因响应慢没有没有返回回来，目前我这边测试环境是没有这个问题的，还有一点需要说明一下以免造成不必要的误会，就是目前的系统角色是无法修改行列权限的，这代表着如果你给了这个用户一个系统角色是无法对他的权限进行编辑，所以只能通过账号授权后进行编辑，如果你觉得过于麻烦可以通过自定义角色来解决这个困扰，这样做主要是为了限制自定义角色权限可能大于系统级别权限问题，望理解；

**Comment by xuwei-fit2cloud** [comment]
v2.8版本开始支持为默认角色进行行权限设置。
