### ISSUE TITLE
[Bug]自定义SQL使用case when语句查询生成的数据集在地图上显示不全

### ISSUE THREAD

**Issue by zhuhuaibin** [dataease/dataease#9040]
**DataEase 版本**
V2.5.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 123.0.6312.106（正式版本） （64 位）

**Bug 描述**
自定义SQL使用case when语句查询生成的数据集在地图上显示不全，而使用excel原数据集可以进行完整的地图显示

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/50860759/f59b45b0-590b-4631-a432-40fc35afa0ab)

2.
![image](https://github.com/dataease/dataease/assets/50860759/06856cea-86e6-4923-a95d-242981857cf7)

3.使用excel原数据集显示为正常
![image](https://github.com/dataease/dataease/assets/50860759/bcea969c-8465-4635-a03f-edf724249c21)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，方便问一下这个问题是必现的吗？
![image](https://github.com/dataease/dataease/assets/84372766/d23f0f2d-df13-42e9-8aea-ca5f54def5af)
![image](https://github.com/dataease/dataease/assets/84372766/a77d7e6d-1e8e-4f93-96aa-876127491bd3)

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
