### ISSUE TITLE
[Feature]饼图合并为其他，文案自定义

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#9042]
DataEase 版本:
v1.18

希望“其他”两个字可以自定义，因为有的用户是 日语、英语环境，视图显示中文有些突兀，场景不合适。

![图片](https://github.com/dataease/dataease/assets/48307752/6403057a-76b3-4e41-b0e9-4bb4256f8ce5)

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，已排期。
