### ISSUE TITLE
[Feature]标题修改处，显示不显示仅控制视图是否显示即可，不要控制配置页面是否显示

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#905]
**请描述您的需求或者改进建议.**
视图/样式处：显示不显示仅控制视图是否显示即可，不要控制配置页面是否显示
![image](https://user-images.githubusercontent.com/60059766/136883096-6bc71432-6862-4561-ba3e-8bd6a198c8e3.png)

**Comment by xuwei-fit2cloud** [comment]
不予支持
