### ISSUE TITLE
[Feature]强制用户修改密码功能可选

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#9050]
DataEase 版本:
v1.18.18
部分用户不希望强制修改密码，给登录带来不便，能否把强制用户修改密码，改为可选开关？或者在配置文件中可配置。

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要讨论一下。

**Comment by xuwei-fit2cloud** [comment]
密码安全策略应该是公司统一策略，不应该部分用户不受策略约束，我们不打算实现这样的功能。
