### ISSUE TITLE
导出模板之后仪表板的背景图片会丢失

### ISSUE THREAD

**Issue by shuyixiao-better** [dataease/dataease#9053]
**DataEase 版本**

V1.18.17
**运行方式(安装包运行 or 源码运行 ?)**
源码方式打包部署

**浏览器版本**
![image](https://github.com/dataease/dataease/assets/111023943/a3d51742-7644-4ad9-82e8-a20305bdcde2)

**Bug 描述**
在仪表板中导出模板后在另一个仪表板中导入模板，如果说仪表板中的背景是图片会丢失

**Bug 重现步骤(有截图更好)**
1.
![1712134413326_B91742C3-DAFC-4902-A6DA-A4036BAFE53A](https://github.com/dataease/dataease/assets/111023943/9c44858c-147b-405c-879a-9f732f70e35d)

2.
3.

**Comment by xuwei-fit2cloud** [comment]
麻烦问一下，具体是什么的背景图，是仪表板的背景图，还是组件的？

**Comment by ziyujiahao** [comment]
可以查询一下 在导出时ec92.png 在导出的服务器中是否存在 /opt/dataease/data/static-resource 这个文件夹  看着像是这个图片在导出模版的服务器中没找到，调试的时候可以追踪这个方法 findResourceAsBase64 看是否返回该图片

**Comment by shuyixiao-better** [comment]
> 麻烦问一下，具体是什么的背景图，是仪表板的背景图，还是组件的？

是仪表板的背景图

**Comment by BBchicken-9527** [comment]
感谢反馈，目前最新的测试环境没有发现你说的问题，你可以尝试升级看一下问题是否被解决；

**Comment by shuyixiao-better** [comment]
> 感谢反馈，目前最新的测试环境没有发现你说的问题，你可以尝试升级看一下问题是否被解决；

好的谢谢

**Comment by shuyixiao-better** [comment]
> 感谢反馈，目前最新的测试环境没有发现你说的问题，你可以尝试升级看一下问题是否被解决；
但是我想请问一下就是仪表板中的背景图片的存储实现方式是作为静态资源流经过base64编码之后给后端存储的吗

**Comment by ziyujiahao** [comment]
> > 感谢反馈，目前最新的测试环境没有发现你说的问题，你可以尝试升级看一下问题是否被解决；
> > 但是我想请问一下就是仪表板中的背景图片的存储实现方式是作为静态资源流经过base64编码之后给后端存储的吗

不是的 静态文件后端存储是直接存储文件的 只有导出模版的时候会讲静态文件base64处理一下存到模版文件中

**Comment by shuyixiao-better** [comment]
> > > 感谢反馈，目前最新的测试环境没有发现你说的问题，你可以尝试升级看一下问题是否被解决；
> > > 但是我想请问一下就是仪表板中的背景图片的存储实现方式是作为静态资源流经过base64编码之后给后端存储的吗
> 
> 不是的 静态文件后端存储是直接存储文件的 只有导出模版的时候会讲静态文件base64处理一下存到模版文件中

但是我在导出模版中查找静态文件为null，就在我上面的截图中，是什么原因？
