### ISSUE TITLE
仪表版数据配置显示错误

### ISSUE THREAD

**Issue by shuyixiao-better** [dataease/dataease#9054]
**DataEase 版本**
V1.18.17

**运行方式(安装包运行 or 源码运行 ?)**
源码方式运行

**浏览器版本**
![image](https://github.com/dataease/dataease/assets/111023943/747bb3ef-7da9-40d9-9f54-0fdbc216f58c)

**Bug 描述**
在配置了数据集之后，使用视图下的指标卡进行数据展示，展示的数据明显大于数据集配置的数据

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/111023943/40d237ea-b2e1-4ce1-9bbb-c61dae37fd96)

2.
![image](https://github.com/dataease/dataease/assets/111023943/dcdc47e3-9b9b-4b54-b5fd-06a3aef418b2)

3.

**Comment by xuwei-fit2cloud** [comment]
您好，我们这边没有复现您说的问题。
方便的话，是否可以提供脱敏后的测试数据？
或者您可以在我们的在线体验环境上试试？我们的体验环境是 https://dataease.fit2cloud.com。

您也可以看看，是不是源码运行时有对数据处理这块有所修改。

**Comment by codzzb** [comment]
这块我来做一下详细说明，
![image](https://github.com/dataease/dataease/assets/14198222/02016fed-eb38-4f80-a77b-8d1169c160d3)
这块我们通过测试环境数据集配置参数为151展示上海GDP数据为20102.00亿
![image](https://github.com/dataease/dataease/assets/14198222/baeb2d3b-4cdb-437f-b8b9-22421710ea82)
数据集保存后显示数据也是正常数据
![image](https://github.com/dataease/dataease/assets/14198222/305018a9-e3c5-490a-ba1c-25381db02003)
打开仪表板开始配置后 参数并没有生效
![image](https://github.com/dataease/dataease/assets/14198222/2654f640-9f19-4fad-995e-ffe2ec9f274f)

![image](https://github.com/dataease/dataease/assets/14198222/5718ad7b-b335-4078-a922-25173a4d5f6e)

请问是设计如此还是，哪里配置有问题

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是说预览数据和实际添加到仪表板中的数据没有对齐是吗？添加到仪表板后图表显示的输入值还是查询全部的，但预览数据是现实筛选后的，是这个意思吗？

**Comment by shuyixiao-better** [comment]
> 感谢反馈，你的意思是说预览数据和实际添加到仪表板中的数据没有对齐是吗？添加到仪表板后图表显示的输入值还是查询全部的，但预览数据是现实筛选后的，是这个意思吗？

是的

**Comment by BBchicken-9527** [comment]
是这样的，你在数据集中编辑的参数是用于仪表板的过滤的，你可以看到在参数化窗口中你输入数值的输入框左侧写着预览的方式如：仅在编辑时生效或数据集‘预览时’全局生效，这两个种方案去让用户根据自己的实际情况预览显示时生效，若添加到仪表板还是会查询全部数据的；
![image](https://github.com/dataease/dataease/assets/84372766/8e075855-7054-4384-b495-bdaabe4520bc)

**Comment by shuyixiao-better** [comment]
> 是这样的，你在数据集中编辑的参数是用于仪表板的过滤的，你可以看到在参数化窗口中你输入数值的输入框左侧写着预览的方式如：仅在编辑时生效或数据集‘预览时’全局生效，这两个种方案去让用户根据自己的实际情况预览显示时生效，若添加到仪表板还是会查询全部数据的； ![image](https://private-user-images.githubusercontent.com/84372766/322427279-8e075855-7054-4384-b495-bdaabe4520bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzM1NzYsIm5iZiI6MTcxMzE3MzI3NiwicGF0aCI6Ii84NDM3Mjc2Ni8zMjI0MjcyNzktOGUwNzU4NTUtNzA1NC00Mzg0LWI0OTUtYmRhYWJlNDUyMGJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA5Mjc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiODVlNWZhN2Q2NTVlMzdkZTUzMmQyN2RhZWVjNGVjMGI0ODQ4ZDdlMjY5MDQ4NDZiZWYxMjM1NGU4YjVlMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Y1H8TZDewVsqYbqu_NKurhR2MYplGTu-Cst7tzaeCw)

您好那我确认一下就是dataease目前不支持动态参数设置过滤在仪表板中生效？

**Comment by BBchicken-9527** [comment]
请问你说的动态过滤设置是权限的控制，还是说单纯数据的动态传参？

**Comment by BBchicken-9527** [comment]
如果是权限控制需要在行列权限种去进行设置，参数是无法干预用户的实际查看的，这样也不符合这个功能的定位，如果进行了限制会导致功能性的重叠，这样会有问题的，如果你只是想进行单纯的动态穿参需要对过滤组件开启绑定参数并选中匹配的过滤参数；
![image](https://github.com/dataease/dataease/assets/84372766/05c81ac6-f77a-4b01-bf3d-b0a2bb70f0fd)
不过需要注意需要在自定义sql-参数设置-参数类型中选中正确的数据类型，比如你是数值类型的参数则选择数值或数值小数，若你是日期类型的则选择日期类型，因为如果你设置的参数类型是日期则这个参数将不会出现在其他类型的过滤规则当中，如你的参数为时间，则这个参数将不会再数值类型的过滤规则中显示；
![image](https://github.com/dataease/dataease/assets/84372766/b29c4eb8-eb48-4c3b-b8ad-0876bd25e76e)
希望我的回答会对你起到一些帮助，也感谢你对DataEase的支持；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
