### ISSUE TITLE
[Bug] V2 数据集动态传参进行逻辑计算时不生效

### ISSUE THREAD

**Issue by hzhwyh0116** [dataease/dataease#9058]
**DataEase 版本**
2.5.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
 chrome

**Bug 描述**
需求场景：希望查询到同比数据，因此喜欢传过来的年份比如是 2024，但我希望查询的结果是根据 2023 进行筛选

结果：当数据集动态传参进行逻辑计算时数据预览只能看到一条数据，并且在仪表板中查询不出数据

**Bug 重现步骤(有截图更好)**
1. 创建数据集，select * from student_score where year = ${year}-1
2.预览时只看到 1 条数据
3.选择明细表无法加载出数据

临时解决：若 SQL 这么写是 OK 的
select * from student_score where year +1 = ${year}

请排查下是否和 calcite 语法相关

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行处理；

**Comment by BBchicken-9527** [comment]
感谢反馈，目前受到是calcite语法的问题，等号右侧不支持表达式计算，所以建议按照你先有方法去处理，我们会持续优化calcite的处理；
