### ISSUE TITLE
[Feature]过滤器中如果传入日期字段，实现使用相对时间快速条件筛选

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#9059]
DataEase 版本:
v2.5.0
**请描述您的需求或者改进建议.**
过滤器中如果传入日期字段，实现使用相对时间快速条件筛选

![image](https://github.com/dataease/dataease/assets/40597893/e0413dd5-0440-439f-a3aa-135e4072663f)
如上图，dt为时间字段，如果我要最新dt这种动态的没法设置

![image](https://github.com/dataease/dataease/assets/40597893/f02e316d-ea56-45a0-a29a-5e7cfdc8cce6)
能否类似查询组件一样，快速设置一个动态时间条件

ps:有时候需要查询组件基础上 在过滤器中额外增加筛选条件

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录并加入需求池中。

**Comment by xuwei-fit2cloud** [comment]
请升级版本。
