### ISSUE TITLE
[Bug]程序运行一定时间后，数据源失效

### ISSUE THREAD

**Issue by serson** [dataease/dataease#9065]
**DataEase 版本**
v2.3

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome

**Bug 描述**
程序运行一定时间后，数据源失效

**Bug 重现步骤(有截图更好)**
1.项目启动后，建立仪表板成功
2.在程序运行一段时间后(一天左右)，提示数据源not found
3.
 i.d.d.s.DatasetDataServer - [error,139] - Method[getFieldEnum][DEException(code=40001, msg=SQL执行失败，请检查表、字段、关联关系等信息是否正确并重新编辑。Error while preparing statement [SELECT
     DISTINCT  t_a_0.`f_d6d98c2bfb03bbdb` AS f_ax_0
FROM
    (SELECT t_a_0.`承运航班号` AS f_8b634d39a20cbc42,t_a_0.`起飞航站` AS f_a331ec6670a02c80,t_a_0.`到达航站` AS f_97a7b36b1411ef72,t_a_0.`航线` AS f_7e1f42b82385ceb7,t_a_0.`当地航班日期` AS f_d6d98c2bfb03bbdb,t_a_0.`北京航班日期` AS f_46aae2b97e6bce4a,t_a_0.`客公里` AS f_7517abbae1544509,t_a_0.`座公里` AS f_8b604e5366909468,t_a_0.`分摊票价` AS f_e25569ce8e93199b,t_a_0.`分摊燃油费` AS f_c7eb8789db6582dd,t_a_0.`人数` AS f_85a43847d3cd8012 FROM (SELECT `opcarrier_flight_no` AS `承运航班号`, `concat`(`dep_city_name`, `dep_airport_name`) AS `起飞航站`, `concat`(`arr_city_name`, `arr_airport_name`) AS `到达航站`, `dep_city_name` || `dep_airport_name` || '-' || `arr_city_name` || `arr_airport_name` AS `航线`, `departure_date` AS `当地航班日期`, `departure_date_cn` AS `北京航班日期`, MAX(CAST(`final_distance` AS DECIMAL)) * COUNT(DISTINCT `concat`(`ticketnumber`, `couponnumber`)) AS `客公里`, MAX(CAST(`available_seat` AS DECIMAL)) * MAX(CAST(`final_distance` AS DECIMAL)) AS `座公里`, SUM(CAST(`fare_alloc` AS DECIMAL)) AS `分摊票价`, SUM(CAST(`fuel_alloc` AS DECIMAL)) AS `分摊燃油费`, COUNT(DISTINCT `concat`(`ticketnumber`, `couponnumber`)) AS `人数`
    FROM `s_a_1773592937682296832`.`dwm_tic_trace_ticket`
    WHERE `departure_date` >= CAST(CAST(SUBSTRING(`now`(), 1, 10) AS DATE) - (INTERVAL 30 DAY) AS VARCHAR) AND `departure_date` < SUBSTRING(`now`(), 1, 10) AND `airport_link_sign` = 'I' AND `opcarrier_airlinecode` = 'HO' AND `checkin_flag` = '1'
    GROUP BY `opcarrier_flight_no`, `concat`(`dep_city_name`, `dep_airport_name`), `concat`(`arr_city_name`, `arr_airport_name`), `dep_city_name` || `dep_airport_name` || '-' || `arr_city_name` || `arr_airport_name`, `departure_date`, `departure_date_cn`) t_a_0)   t_a_0
 LIMIT 1000 OFFSET 0] [Object 's_a_1773592937682296832' not found])]
![image](https://github.com/dataease/dataease/assets/25809082/04cf11c0-f2b9-4ae4-adc6-fcb1459ae140)
4.重启后，再次读取仪表板可以成功

**Comment by BBchicken-9527** [comment]
感谢反馈，请问数据源在这期间是否有重启或关闭的情况？

**Comment by serson** [comment]
在这期间数据源没有重启或者关闭

**Comment by BBchicken-9527** [comment]
感谢反馈，受累确认一下数据源是否有效，如果有效看一下系统设置-基础设置-数据源检测时间，静候上面的等待时间后是否恢复并有效，若依然无效可能是和我现在了解到的一个问题是相同原因，将会在后续版本一并处理；

**Comment by serson** [comment]
确认数据源是有效的 等待时间后未恢复

**Comment by BBchicken-9527** [comment]
感谢反馈，目前数据源有效性检测已经修复，你可以下载新版本尝试；

**Comment by xuwei-fit2cloud** [comment]
请更新到v1.18.21版本。
