### ISSUE TITLE
[Feature] V2 数据大屏能否支持查询组件，或 仪表板能否支持悬浮布局

### ISSUE THREAD

**Issue by hzhwyh0116** [dataease/dataease#9069]
DataEase 版本:
V2.5.0

**请描述您的需求或者改进建议.**
V2 版本数据大屏和仪表板定位有个区分，我的理解：
数据大屏：一般是在固定分辨率的屏幕上展示，设计器仅悬浮式布局，可编辑图层，交互式分析功能较少（无筛选组件）；
仪表板：一般是内部传阅快速进行数据分析统计，设计器仅紧凑式布局，有下钻、联动、条件筛选等。

本身仪表板和大屏的定位没啥问题，但实际项目中会遇到非常多的需求，是既要有悬浮交叉占位的布局又要有查询组件和交互式分析的，并且有些展厅的固定大屏也是有一些筛选过滤演示的，两个非常硬性的设计导致无法满足项目需求，比较尴尬。

期待产品后续能考虑到上述需求场景，设计上突出两个定位的重点优势区别，但尽量满足实际项目需求。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要讨论一下。

**Comment by hzhwyh0116** [comment]
感谢支持🙏

**Comment by yooyea** [comment]
+1

**Comment by xuwei-fit2cloud** [comment]
已纳入开发计划。
