### ISSUE TITLE
[Feature]气泡图的气泡大小支持自定义，且能够在仪表板和视图之间进行自适应大小调整

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#907]
**请描述您的需求或者改进建议.**
气泡图的气泡大小支持自定义，且能够在仪表板和视图之间进行自适应大小调整，当前两个是一样大小的，比较尴尬，不随着仪表板的调整而自适应
视图气泡大小如下图：
![image](https://user-images.githubusercontent.com/60059766/136886373-2593975f-d1bf-467e-8950-7259759eafc7.png)

仪表板气泡大小如下图：
![image](https://user-images.githubusercontent.com/60059766/136886318-d42f12c3-6f22-45d6-8dab-e2cd32ab9af5.png)

**Comment by xuwei-fit2cloud** [comment]
这个目前确实还不太好实现。
