### ISSUE TITLE
[Bug]数据集中复制的字段无法删除

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#9070]
**DataEase 版本**
v2.5.0

**运行方式(安装包运行 or 源码运行 ?)**
 源码运行

**浏览器版本**
chrome Version 123.0.6312.107

**Bug 描述**
数据集中复制的字段无法删除

**Bug 重现步骤(有截图更好)**
1. 任选一个数据集，进入编辑界面
2. 数据预览部分任选一个字段复制
![image](https://github.com/dataease/dataease/assets/40597893/a9a1ba7a-9f6f-4471-8822-0b7772e6ab47)
3. 复制后的字段没有删除选项
![image](https://github.com/dataease/dataease/assets/40597893/57af3796-326e-4d65-b69d-7b33c5831603)

**Comment by BBchicken-9527** [comment]
感谢反馈，你可以尝试滚动弹窗，因为窗口大小是固定的，隐藏在了下面，我们优化一下这里的弹窗显示，确实容易让用户使用起来产生误解；

**Comment by lillcol** [comment]
好的，看到了，感谢
