### ISSUE TITLE
[Feature]表格行高自适应组件高度

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#9072]
DataEase 版本:
v1.18

在数据行较少情况下，表格组件下面会有空白，及时调整组件高度避免了空白，换个分辨率高的显示器，空白又出来了，影响美观；
希望可以加一个自适应行高的开关。

<img width="437" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/efba6305-5346-4c9d-8b69-4e3b941a385a">

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
已纳入需求池，类似列宽设置，行高增加自适应和固定高度两个选项，自适应则通过计算容器高度和数据条数来自行计算行高。
