### ISSUE TITLE
[Feature] DataEase v1 查询按钮优化

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#9075]
DataEase 版本:
v1.18.18

**请描述您的需求或者改进建议.**
设置好了查询按钮，且将自动触发勾掉后，进入看板仍然会自动执行一次查询，是否考虑将该查询去掉？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，默认触发一次，是因为首次进入仪表板后要显示图表数据，图表的数据和过滤组件设置的默认有关，所以这里是相关联的，暂时没有计划修改这里的设计。
