### ISSUE TITLE
[Bug]选项卡内嵌网页组件底部留白问题

### ISSUE THREAD

**Issue by xiaole992** [dataease/dataease#9082]
**DataEase 版本**
V1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌浏览器99.0.4844.51

**Bug 描述**
选项卡内嵌网页组件，隐藏选项卡以后，底部有留白情况，网页组件无法填充，下拉会变成滚动条

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是底部留白导致组件无法填充问题吗？目前这个问题已经在处理当中了，下个版本会进行修复；

**Comment by BBchicken-9527** [comment]
感谢反馈，由于你长时间没有恢复我这里将按照底部留白导致组件无法填充的问题进行处理；

**Comment by xiaole992** [comment]
v1.18.19版本该问题还未修复

**Comment by maninhill** [comment]
v2.10-lts 版本已经发布，请在最新版本上面验证，有问题请 re-open。
