### ISSUE TITLE
[Feature]建议增加基于根据源目标IP的经纬度制作路径图

### ISSUE THREAD

**Issue by aiaiduo** [dataease/dataease#9085]
DataEase 版本:
2.5

**请描述您的需求或者改进建议.**
建议增加基于源、目标IP的解析后的经纬度制作路径图，或者根据源、目标IP解析后的归属地制作可视化地图，类似于人员迁徙的这个图
![image](https://github.com/dataease/dataease/assets/28044296/23813f04-cb45-4e7a-b75f-bfc42328f137)

参考链接
https://baijiahao.baidu.com/s?id=1791350432593281450&wfr=spider&for=pc

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已规划在近期的版本中，预计在7、8月的版本中进行支持。

**Comment by aiaiduo** [comment]
> 感谢您的反馈，该需求已规划在近期的版本中，预计在7、8月的版本中进行支持。

嗯 好的 多谢~
