### ISSUE TITLE
[Question]v1 数据集计算字段聚合函数能否依"栏位分组计算"功能？

### ISSUE THREAD

**Issue by tzengshinfu** [dataease/dataease#9086]
**DataEase 版本**
1.18.18

**问题叙述**
您好，我们使用直连SQL数据集，内容是子报表的每笔详细纪录，
查询SQL语法会使用CASE WHEN或REPLACE对某些栏位内容进行置换，
大概会像是"SELECT [维度栏位1], CASE [维度栏位1] WHEN 'A' THEN 'B' END AS [维度栏位2], [指标栏位1] From [表1]"
在父报表的数据集也使用相同的语法，增加计算字段，字段表达式为"SUM([指标栏位1])"，
却发现是将所有纪录加总计算，
请问有无方法能让其依指定的维度栏位进行分组计算？

**Comment by maninhill** [comment]
暂无支持计划。
