### ISSUE TITLE
[Bug]使用位运算符&报错

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#9087]
**DataEase 版本**
V2.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome 123.0.6312.107

**Bug 描述**
执行位运算符SQL报错
![9d89421329d3fe52a8f4ac40ef7197b](https://github.com/dataease/dataease/assets/104493699/c69500c0-a783-4eed-9bd6-c63da90027b9)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前数据集统一经过中间件calcite进行处理，calcite应该是暂时不支持位运算的方式，后续版本我们会逐步完善，非常抱歉给你的体验带来不便；
