### ISSUE TITLE
[Bug]流向地图不显示

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#9089]
**DataEase 版本**
1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
 chrome

**Bug 描述**
流向地图，没有数据，我测了两个环境都一样，应该不是我环境的问题。
数据没问题，符号地图可以显示。
<img width="1489" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/1a851777-2e24-4f12-8311-e902a5f02698">

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前问题已修复将会在下个版本上线；
