### ISSUE TITLE
[Feature]表格列比较多时，查看不方便

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#9090]
DataEase 版本:
1.18.18
表格列比较多时，查看不方便，希望可以像版本纹一样，做个隔列配色，透视表、明细表、汇总表希望都支持。
<img width="1301" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/5988ccdd-ef0c-4a69-ac8b-e2b68eb853cf">

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
我们将在后续版本增加斑马纹的方向支持，支持横向与纵向设置。
