### ISSUE TITLE
[Feature]【图表】仪表板中的明细表下钻功能优化

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#9094]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
仪表板中的明细表下钻功能优化
当前的明细表的下钻是点击表格中的其他字段（非上级字段）也会进行下钻，以后只点击上级字段的时候才下钻，详见录屏。

https://github.com/dataease/dataease/assets/24768910/2f1365fc-a901-4f00-8e12-e43969acb6cd

**Comment by xuwei-fit2cloud** [comment]
这个我们讨论一下。

**Comment by xuwei-fit2cloud** [comment]
已排期，还请等待。
