### ISSUE TITLE
[Bug]【数据集】数据集刷新数据报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#9095]
**DataEase 版本**
v2.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
数据集勾选某个时间字段然后点击“刷新数据”就报错，不勾选就正常，报错情况如下图：
![image](https://github.com/dataease/dataease/assets/24768910/e7259a0b-9f86-4886-b882-fdfde1771e64)
报错信息：SQL执行失败，请检查表、字段、关联关系等信息是否正确并重新编辑。java.sql.SQLException: Zero date value prohibited
数据库类型：mariaDB
有问题字段类型：datetime
存在数据格式：
![image](https://github.com/dataease/dataease/assets/24768910/d07a2c7d-de74-4126-8107-de7a3c9980e1)
数据库版本：10.1.48-MariaDB-0ubuntu0.18.04.1

**Comment by BBchicken-9527** [comment]
感谢反馈，方便可以具体说明一下你的问题吗？你的意思是进行数据库数据集吗？还是说你进行连表的时候勾选时间字段进行关联然后异常呢？

**Comment by AndroidBaby1** [comment]
感谢，就是拉动数据源其中一个表，然后执行数据预览的时候报的错

**Comment by BBchicken-9527** [comment]
你好，我这边尝试了一下是没问题的，数据源是根据你提供的版本10.1.48-MariaDB，如果查看数据de是没有做限制的，如果你过滤掉这些无效数据是否可看呢？
![image](https://github.com/dataease/dataease/assets/84372766/24e767f7-6a90-4f94-b373-d2ff1e694777)
![image](https://github.com/dataease/dataease/assets/84372766/eb49c708-a787-4286-9a1a-b77ef7b73db7)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在后续版本进行修复；

**Comment by AndroidBaby1** [comment]
感谢

**Comment by BBchicken-9527** [comment]
我们确认了一下，是因为你的部分日期为无效日期，在de获取数据时进行格式转换导致，我们想了一下建议你直接在jdbc链接处增加zeroDateTimeBehavior=CONVERT_TO_NULL解决这个问题可能是最优解；
![image](https://github.com/dataease/dataease/assets/84372766/43b6d820-6a87-4076-8acc-2db00969cc22)

**Comment by AndroidBaby1** [comment]
感谢，没有问题了
