### ISSUE TITLE
[Feature]添加数据库数据集时，支持树状结构展示数据表，同时支持点击预览数据

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#91]
**请描述您的需求或者改进建议.**
添加数据库数据集时，支持树状结构展示数据表，同时支持点击预览数据
同时支持批量选择数据集，选择时默认仅预览显示第一个表的数据

![image](https://user-images.githubusercontent.com/60059766/123722387-d8ef2500-d8ba-11eb-83d9-313e7356479e.png)

**Comment by yayanpei** [comment]
感谢您的反馈，您的建议对我们非常重要

**Comment by xuwei-fit2cloud** [comment]
以树状结构展示数据表，在数据表比较多的情况下下拉列表会很长；
另外，在选择数据表阶段预览数据，这个需求目前不确定是否是强需求；
我们会继续思考如何优化当前页面的展示和使用设计。

**Comment by xuwei-fit2cloud** [comment]
近期版本还不会支持该需求
