### ISSUE TITLE
[Feature][数据集]-[数据关联] 希望增加左差连接、右差连接、全连接

### ISSUE THREAD

**Issue by snbnsbsw** [dataease/dataease#9105]
DataEase 版本:V1 V2
现有数据集功能 数据关联 仅有左连接、右连接、内连接三种。
希望增加左差连接、右差连接、全连接功能。否则只能使用sql语句实现，不够方便。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们讨论一下。

**Comment by xuwei-fit2cloud** [comment]
各种数据库对连接方式的支持不一定完全，我们会分别进行支持。该需求已纳入需求池，等待后期开发支持。

**Comment by xuwei-fit2cloud** [comment]
新增了全连接。
