### ISSUE TITLE
[Feature]大屏支持外部参数

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#9107]
DataEase 版本:
v2

大屏的制作比较灵活，有时不一定会放在大屏上展示，也可能是嵌入或网页，希望大屏支持外部参数。

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
已排期，请等待开发。
