### ISSUE TITLE
[Feature] DE v2 系统变量能否增加组织字段

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#9108]
DataEase 版本:
v2.5.0

**请描述您的需求或者改进建议.**
DE v2 系统变量能否增加组织字段，这样在数据权限控制的时候会更加灵活，我看v1版本目前就可以控制组织的系统变量来实现数据权限的管理。
<img width="1956" alt="image" src="https://github.com/dataease/dataease/assets/45967454/2d3fc252-76d9-4072-8f25-71b21c413255">

**Comment by xuwei-fit2cloud** [comment]
目前在支持用户自定义扩展字段，用于配置行列权限，还请等待。
