### ISSUE TITLE
[Bug]定时报告加载仪表板额外等待时间提示有误

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#9115]
**DataEase 版本**
v1.18.18

**运行方式(安装包运行 or 源码运行 ?)**

安装包

**浏览器版本**

版本 123.0.6312.107（正式版本） (arm64)
**Bug 描述**

定时报告加载仪表板额外等待时间提示有误，额外等待时间必须是(10-30]之间整数，实际是0-100之间

**Bug 重现步骤(有截图更好)**
1.输入101，提示额外等待时间必须是(10-30]之间整数
![image](https://github.com/dataease/dataease/assets/127368807/0be948b9-b9b2-49f6-ba4c-9f4a961931e4)

2.输入99 可以，(10-30]区间有失误
![image](https://github.com/dataease/dataease/assets/127368807/0d4d8ae2-d9a1-4ee6-904f-771a44b5dfba)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将在下个版本进行修复；
