### ISSUE TITLE
[Bug]添加字段信息后编辑左边的列的格式，右边的列格式会跟着变化

### ISSUE THREAD

**Issue by zhangwenkl** [dataease/dataease#9126]
**DataEase 版本**
1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
https://dataease.fit2cloud.com/#/panel/index

**浏览器版本**
123.0.6312.123

**Bug 描述**
添加字段信息后编辑左边的列格式，右边的列格式会跟着变化

**Bug 重现步骤(有截图更好)**
1.新建一个数据集，包含多个数值类型，并在仪表板建立antV明细表，将维度和指标shift+左键批量拖入数据列
![图片1](https://github.com/dataease/dataease/assets/28699054/1a367a67-0bb3-4f14-884a-037e59fe9a1a)

2.明细表各数据正常显示如下：
![图片2](https://github.com/dataease/dataease/assets/28699054/05a46ce8-7196-4574-a10a-217cde914cdf)

3.将其中一个指标的数据格式改为百分比，所有数值类型的指标列都变成了百分比格式，如下图所示：
![图片3](https://github.com/dataease/dataease/assets/28699054/bc2342d0-468a-4264-a6c4-594fc85bc9df)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
