### ISSUE TITLE
[Bug]V2的SQL数据集图表与数据集显示不一致

### ISSUE THREAD

**Issue by zhuhuaibin** [dataease/dataease#9127]
**DataEase 版本**
V2.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 123.0.6312.123（正式版本） （64 位）

**Bug 描述**
SQL数据集查询的结果与图表显示数据不一致。

**Bug 重现步骤(有截图更好)**
1.通过仪表板查看，添加”数据列/维度或指标“为两列时显示数是正常，单放一列时数据查询显示不正确。
![d7820337c17942252e2f642a43abea3](https://github.com/dataease/dataease/assets/50860759/16cafce6-50f4-46fa-a8b0-5e2e094726e4)
![71330854dea90b7a2091099a2116ec3](https://github.com/dataease/dataease/assets/50860759/7f899bb5-833a-492e-b76c-ab20eccef7a7)

2.通过渲染图表sql进行解析发现，嵌套的查询单独查询一列数据显示错误，取全部数据正常。
![3732ed02cd4dcdcacaf3b398a76e7fa](https://github.com/dataease/dataease/assets/50860759/20962eaf-e152-46e3-80f6-cfb76ed68e4b)

![b50d9dba76aa8f6d04557c9a0a50570](https://github.com/dataease/dataease/assets/50860759/3f21093c-5eff-4061-8bfe-9b64bb06ea81)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你是用的数据源是什么？

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
