### ISSUE TITLE
[Bug]悬浮模式下视图错位

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#9141]
**DataEase 版本**
v1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包离线部署

**浏览器版本**
谷歌

**Bug 描述**
数据源excel，悬浮模式下视图进行关联，全屏显示后，点击关联，较高概率发生错位

**Bug 重现步骤(有截图更好)**
1.数据源excel
2.悬浮模式下视图进行关联
3.全屏显示后，点击关联，错位
![chrome_7hRswxUbNC](https://github.com/dataease/dataease/assets/163749505/f267fb52-d302-4b59-9c1e-96f8f7e5d403)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by maninhill** [comment]
v2.10-lts 版本已经发布，请在最新版本上面验证，有问题请 re-open。
