### ISSUE TITLE
[Bug]雷达图会自己变化排列顺序

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#9142]
**DataEase 版本**
v1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌

**Bug 描述**
数据源excel，数据没有改变，雷达图编辑再退出，总是会自己变化排列顺序

**Bug 重现步骤(有截图更好)**
1.数据源excel，数据没有改变
2.雷达图编辑再退出，总是会自己变化
3.默认固定排列应该会更加美观

![chrome_jd15ABRBI7](https://github.com/dataease/dataease/assets/163749505/370046e9-743b-4892-ac5d-930652ed4c1c)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，如果你将数据源换成mysql是否依然存在你说的问题呢？

**Comment by BBchicken-9527** [comment]
感谢反馈，由于excel都是存储到doris中并通过kettle进行抽取，抽取顺序是随机的，目前没有比较优质的解决方案，建议可以使用直连或者字段排序方式进行固定；
