### ISSUE TITLE
大屏内增加查询组件功能

### ISSUE THREAD

**Issue by yanlong-big** [dataease/dataease#9149]
DataEase 版本：社区版 2.5.0

请在大屏内增加查询组件功能，这个非常重要，不然大屏等于没用了。
需要根据查询组件的维度，动态的筛选图表。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #9069 .
我们会在后续版本为大屏设计上查询组件功能，还请等待。
