### ISSUE TITLE
复制图表再使用时报错

### ISSUE THREAD

**Issue by yanlong-big** [dataease/dataease#9151]
**DataEase 版本**社区版 2.5.0

**浏览器版本**edge 浏览器

**Bug 重现步骤(有截图更好)**
1.复制A图表到B,C,D不报错
2.但是把BCD的指标更换后，就报错，他们是同一个数据集
3.数据集检查没有错误
4.使用这个数据集，重新做是没有问题的，但效率太低，使用复制就报错
![Uploading image.png…]()

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #9152
