### ISSUE TITLE
复制图表再使用时报错

### ISSUE THREAD

**Issue by yanlong-big** [dataease/dataease#9152]
**DataEase 版本**社区版 2.5.0

**浏览器版本**edge 浏览器

**Bug 重现步骤(有截图更好)**
1.复制A图表到B,C,D不报错
2.但是把BCD的指标更换后，就报错，他们是同一个数据集
3.数据集检查没有错误
4.使用这个数据集，重新做是没有问题的，但效率太低，使用复制就报错
![image](https://github.com/dataease/dataease/assets/116066130/ce47aa91-2b1b-41ef-b7ee-28f2c14ff620)

**Comment by yanlong-big** [comment]
![image](https://github.com/dataease/dataease/assets/116066130/cfa22abf-0562-4c8d-8c63-9dd1079b121f)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你是用的是什么数据源，目前在测试环境中使用mysql数据源没有发现你说的问题

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
