### ISSUE TITLE
[Bug]明细表时间过滤器底层查询日期转换不和逻辑

### ISSUE THREAD

**Issue by zhuhuaibin** [dataease/dataease#9155]
**DataEase 版本**
V2.5.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 123.0.6312.123（正式版本）

**Bug 描述**
明细表时间过滤器底层查询日期转换不和逻辑

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/50860759/a374b59e-15f8-4f24-a960-6ff53bae9009)

2.
![image](https://github.com/dataease/dataease/assets/50860759/0965a194-1bde-4f70-aa9c-21bf5fcb8731)

3.
![image](https://github.com/dataease/dataease/assets/50860759/f042a934-4430-41a9-9c89-18a4384a54fc)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们下个版本修复一下。
