### ISSUE TITLE
[Bug]token续期失败

### ISSUE THREAD

**Issue by zhangwenkl** [dataease/dataease#9170]
**DataEase 版本**
1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
123.0.6312.124

**Bug 描述**
在token快超时的时候点击页面操作，token无法续期

**Bug 重现步骤(有截图更好)**
1.登录系统
2.等待token超时时间到前2分钟操作系统
3.2分钟后在操作系统提示重新登录

**Comment by BBchicken-9527** [comment]
感谢反馈，目前1.x是没有token的续命机制；

**Comment by maninhill** [comment]
暂无支持计划。
