### ISSUE TITLE
各位大神，有个小建议，后期能否增加按数据库某字段内容，自动切换对应图片。

### ISSUE THREAD

**Issue by zzc1czz** [dataease/dataease#9172]
自己研究了一段时间，感觉现有功能基本很齐全了，就差这么个功能。
逻辑很简单就是上传几张照片GIF那种，然后可以根据数据库一字段内容自动切换显示，如字段值为1，显示图片1，字段值为2，显示图片2。这个功能好多地方能用上，比如不同产品展示，不同状态动态图片显示。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录并讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈和支持，我们先记录进需求池中，排期可能会晚一些。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已支持图片组组件，您可以试试。
