### ISSUE TITLE
[Feature]仪表板加载时间较长时，建议增加"加载中"的动态效果图提示

### ISSUE THREAD

**Issue by 102408** [dataease/dataease#9175]
DataEase 版本:1.18.18

**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/41459984/69cd5a4f-55dd-480f-839a-bbea3e82b281)

可参考：
![image](https://github.com/dataease/dataease/assets/41459984/3d87c215-ef03-40ff-b024-7b5b2e223a8a)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议您将仪表板样式中的「视图加载提示」勾选上。
<img width="357" alt="image" src="https://github.com/dataease/dataease/assets/84168063/1c136abc-b29d-4e0a-91dc-8709a36c0439">
