### ISSUE TITLE
组件间像PPT一样添加组合功能

### ISSUE THREAD

**Issue by Bing-q** [dataease/dataease#9182]
调整组件排版很繁琐，比如调整好一小块排版，这一小块是三个组件组成的，但是复制只能一个一个复制，一个一个移动，新增加组合功能，将三个组件组合为一个，可以一起复制一起拖动

**Comment by xuwei-fit2cloud** [comment]
您好，在我们的v2.x版本中，数据大屏是支持组合功能的。

**Comment by Bing-q** [comment]
好的
