### ISSUE TITLE
[Bug] 数值字段超过 18 位， 数据集查询显示异常

### ISSUE THREAD

**Issue by fit2cloud-zaopengguo** [dataease/dataease#9186]
**DataEase 版本**
v 2.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
123版本

**Bug 描述**
数据库表的 ID 都是基于雪花算法生成的，是个 19 位数的 ID ， 数据库是 MySQL 数据库，字段类型是 bigInt。 在 DE 数据集显示异常，变成一组 99999

**Bug 重现步骤(有截图更好)**
1.  MySQL 表插入一个 19 位数的 bigint 的 ID 
![image](https://github.com/dataease/dataease/assets/30264974/8a896ce7-225d-4e1b-99f9-f5eec8034cb3)

2. 数据集通过 自定义 SQL 方式查询数据
![image](https://github.com/dataease/dataease/assets/30264974/7330310a-6df1-4413-82f4-e5aea417935a)

3. 刷新数据集
![image](https://github.com/dataease/dataease/assets/30264974/0e9b28fa-9b4e-442c-8618-9b7f04cb7d81)

4. 18 位数的 ID 显示正常， ID: 174149214997707161
![image](https://github.com/dataease/dataease/assets/30264974/f16cb824-2d1c-4d6f-ae4b-cfd85605c265)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
