### ISSUE TITLE
[Feature] v2版本API数据源 能否支持Token认证

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#9189]
DataEase 版本:
v2.5.0

**请描述您的需求或者改进建议.**
背景：
现在很少有网站使用Basic auth啊，大部分其实都是以token的形式，token有效期如果很短，在目前的API请求中配置需要频繁更换Token值，导致API数据源的使用很不人性化。

建议：
能否增加Token的认证方式。

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈和支持，我们支持一下。
