### ISSUE TITLE
[Bug]当仪表板设置分辨率之后，点击选项卡的页签  会出现 <这是个空的仪表板，可以通过编辑来丰富内容>

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#9190]
**DataEase 版本**
v1.18.18
安装包安装

**Bug 重现步骤(有截图更好)**
新建一个选项卡，第一页放入一个视图，然后新建一个标签页但是不点进去，然后再刷新，f12更改分辨率，点击第二个标签，在此之前不要点击第二个标签。

https://github.com/dataease/dataease/assets/141667200/a96f5a0e-3315-40aa-bafd-91d36189288c

**Comment by BBchicken-9527** [comment]
感谢反馈，正常使用是没问题的，因为仪表板是会通过分辨率去进行计算，如果通过开发者工具去进行分辨率修改是有可能产生一些前端计算上的问题的，建议你通过常规方式使用；
