### ISSUE TITLE
[Bug]日期类型维度过滤器存在问题

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#9192]
**DataEase 版本**
v2.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌浏览器

**Bug 描述**
日期维度设置过滤器筛选大于没问题，或者筛选等于也没问题，唯独筛选大于等于出现错误

**Bug 重现步骤(有截图更好)**
1.横轴带日期类型的视图
2.过滤器选择日期类型维度，筛选大于等于
3.筛选结果错误
![lAGVEv3dPW](https://github.com/dataease/dataease/assets/163749505/02214051-5a13-4c90-a629-f4a74ef19b5a)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你用的数据源是什么？字段类型又是什么呢？

**Comment by janus177** [comment]
> 感谢反馈，请问你用的数据源是什么？字段类型又是什么呢？

日期字段，mysql以及excel都会出现该问题

**Comment by BBchicken-9527** [comment]
感谢反馈，受累确认一下是否为时区问题导致？如果是时区导致建议统一一下时区；

**Comment by janus177** [comment]
> 感谢反馈，受累确认一下是否为时区问题导致？如果是时区导致建议统一一下时区；

不是时区问题，我要筛选大于等于，数据只有等于，如果是时区问题应该一条数据都没有

**Comment by BBchicken-9527** [comment]
感谢反馈，新版本我这边是没问题的，你可以尝试一下最新的版本；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
