### ISSUE TITLE
[Feature]v2 漏斗图能不能像 v1.18.18 一样能够展示转化率

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#9194]
DataEase 版本:
DataEase v2 版本

**请描述您的需求或者改进建议.**
v2 漏斗图也能够展示转化率
![image](https://github.com/dataease/dataease/assets/163749505/d3eb647e-9083-43af-b978-30cc10fba11e)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在v2中也增加转化率的展示功能。
