### ISSUE TITLE
[Bug]编辑状态和预览状态下词云图形状不一样

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#9198]
**DataEase 版本**
v2.5.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Chrome
版本 123.0.6312.124（正式版本） (arm64)

**Bug 描述**
在编辑状态添加词云图，保存以后，在预览界面的词云图变了，甚至超出范围。
能确认编辑时候的词云图，丹预览的会怎么改变不好确认，需要跟编辑状态保持一致。

**Bug 重现步骤(有截图更好)**
1.编辑状态下：
![image](https://github.com/dataease/dataease/assets/127368807/787ad242-662b-4dda-8c0d-e5709b3711ac)

2.预览状态下：
![image](https://github.com/dataease/dataease/assets/127368807/bc2c7ad8-b7ce-42d8-a506-b6cb73cf4dd2)
![image](https://github.com/dataease/dataease/assets/127368807/c294ad7a-dba5-464a-b08a-a503b35e0dd4)

**Comment by BBchicken-9527** [comment]
感谢反馈，编辑状态因为存在左侧图层管理和右侧设置的抽屉所以显示的窗口大小是不一样的，受累你看一下编辑状态点击右上角预览是否和预览状态的编辑显示的一致；

**Comment by greenyhsj** [comment]
不一致，数据大屏的页面有个左侧目录栏导致长宽比不一样，会突出去。但是词云图的自适应很差，改变浏览器长宽会严重变形，其他图表适应比较正常
![image](https://github.com/dataease/dataease/assets/127368807/a6745d5a-1d3f-40b0-823c-2b97ed018abe)
![image](https://github.com/dataease/dataease/assets/127368807/c086f73f-9c24-4d47-bbda-a578165b63a3)

**Comment by BBchicken-9527** [comment]
感谢反馈，因为显示字段多少显示在哪里都是有图表内部进行计算的，目前没有好的干预方式，建议对边框内部显示预留足够的空间可能这样会好一些，非常抱歉没有帮到你，后期我们也会逐步完善图表的功能；
