### ISSUE TITLE
[Feature]添加数据集后，树状结构中展示的数据集名称展示顺序调整下

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#92]
**请描述您的需求或者改进建议.**
可以将添加到数据集中的名称顺序改为：表名-数据库名-数据源名称（展示方式可换行，可默认省略号）

![image](https://user-images.githubusercontent.com/60059766/123723625-60d62e80-d8bd-11eb-99eb-ad70b26e9701.png)

**Comment by xuwei-fit2cloud** [comment]
建议的名称顺序确实可以代表一部分需求，但我们认为当前的规则也是有其存在的理由的，暂时不予改动。
