### ISSUE TITLE
[Bug] 从世界地图下钻到中国地图失败

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#9201]
**DataEase 版本**
v 1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 123.0.6312.124（正式版本） (arm64)

**Bug 描述**
从世界地图下钻到中国地图失败

**Bug 重现步骤(有截图更好)**
1. 数据集
![image](https://github.com/dataease/dataease/assets/45852479/a51c45fc-6243-44b3-a94f-abaa79a726f6)
2. 视图配置
![image](https://github.com/dataease/dataease/assets/45852479/21971312-cd97-4c7b-b92d-47ddff6e856a)
3. 点击下钻，下钻失败
![image](https://github.com/dataease/dataease/assets/45852479/7239caa3-b7fe-4598-9103-aa8c15c10065)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
