### ISSUE TITLE
[Bug] pg sql 设置参数后，预览报错

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#9203]
**DataEase 版本**
v 1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
版本 123.0.6312.124（正式版本） (arm64)

**Bug 描述**
pg sql 设置参数后，预览报错

**Bug 重现步骤(有截图更好)**
1. 参数位置
<img width="1230" alt="image" src="https://github.com/dataease/dataease/assets/45852479/242028d1-5791-447b-bc30-363bbd1654f4">
2. 报错信息
<img width="1034" alt="image" src="https://github.com/dataease/dataease/assets/45852479/9b916610-7949-43a5-803f-0e12ab06471f">
<img width="1230" alt="image" src="https://github.com/dataease/dataease/assets/45852479/242028d1-5791-447b-bc30-363bbd1654f4">

附: [pg.sql](https://github.com/dataease/dataease/files/15022554/pg.txt)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by maninhill** [comment]
v2.10-lts 版本已经发布，请在最新版本上面验证，有问题请 re-open。
