### ISSUE TITLE
[Bug]仪表板里面的图表预览正常，编辑模式下，图表的顺序错乱了

### ISSUE THREAD

**Issue by mmmlong** [dataease/dataease#9205]
**DataEase 版本**
2.5

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome：123.0.6312.122

**Bug 描述**
仪表板里面做了10个图表，在预览模式下，图表的顺序是正常的，但是点编辑后，里面的有些图表会错位，

**预览的时候图表位置**：
<img width="1083" alt="image" src="https://github.com/dataease/dataease/assets/30709129/8d32503c-9878-4d61-b15a-4a49625cdcb1">

**编辑的时候图表位置**：
![image](https://github.com/dataease/dataease/assets/30709129/4508fcde-56a8-4ae7-984f-4f386f77201a)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问错位是点击之后发生了错位还是进入编辑页面就是错位的状态？

**Comment by mmmlong** [comment]
点击之后是正常的，进入编辑页面就错位了，

**Comment by BBchicken-9527** [comment]
错位一般是因为分辨率的变化导致计算出现错误，受累需要和你确认一下这个仪表板大概多少个图表，且每个图表的平均数据量是多少？还有就是受累问一下客户端的内存是多大的？

**Comment by mmmlong** [comment]
一排7个查询条件，8个图表，表格的数据量限制在7000条数据，
客户端mac系统8g,windows8g都会出现

**Comment by BBchicken-9527** [comment]
感谢反馈，我这边尝试模拟一下你说的场景，你说的错位的意思就是选中图表后显示的一个蓝色区域范围和实际显示的位置不一致对吧；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
