### ISSUE TITLE
[Feature]堆叠柱状图希望可以显示每根柱子的总计

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#9210]
DataEase 版本:
v1.18

堆叠柱状图希望可以添加柱子的总计标签，标签分为子标签和汇总标签，汇总标签就是 每根柱子的总计。
<img width="626" alt="图片" src="https://github.com/dataease/dataease/assets/48307752/23cce5d3-1270-4c1b-b5f7-40bc29535a16">

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先调研下图库是否支持。

**Comment by xuwei-fit2cloud** [comment]
已排期，请等待。

**Comment by xuwei-fit2cloud** [comment]
v1.18.22版本已处理，请更新版本。
