### ISSUE TITLE
[Feature] 消息中心支持更多种类的消息提醒

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#9213]
DataEase 版本:
v 1.18.18

**请描述您的需求或者改进建议.**
消息中心支持更多种类的消息提醒，例如: 权限变动、看板加载失败等

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
权限变动可能会比较频繁，如果持续发送消息提醒的话，不一定合适。
还有其他需要增加的提示类型吗？可以列出来我们讨论增加一下。

**Comment by MaekBlack** [comment]
主要是权限变动这一部分，v1 能和 v2 一样权限有个确认按钮不，确认后再进行发送

**Comment by MaekBlack** [comment]
看板加载失败这个我们能try catch到不
