### ISSUE TITLE
[Bug] 仪表板背景设置成透明 但不能生效

### ISSUE THREAD

**Issue by yaocanke** [dataease/dataease#9214]
**DataEase 版本**
V1.18.18

**Bug 描述**
在某个仪表板中，将仪表板背景设置成白色，不透明度设置成0（见图1），但仪表板还是有背景（见图2）。

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/89123307/68e01128-dcd0-483d-86b1-e7f0b78b4559)

![image](https://github.com/dataease/dataease/assets/89123307/899777e1-8209-4118-a4f4-ad6cc6dd1633)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，请问是还有其他的一些操作吗？如果方便的话能否将问题仪表板导出一个模版我们看一下呢？
![image](https://github.com/dataease/dataease/assets/84372766/8dc6efe0-e8e4-4800-b65c-02df19f25144)

**Comment by yaocanke** [comment]
我将我的步骤做成了视频，你可以参考我的步骤重现一下，谢谢。
![Video_2024-04-23_164442_edit (1)](https://github.com/dataease/dataease/assets/89123307/5f58fe0d-a975-4ee5-a983-2bf73a4bff1f)

**Comment by yaocanke** [comment]
模版分别为2个，见压缩文件。
[透明度测试.zip](https://github.com/dataease/dataease/files/15144526/default.zip)

**Comment by BBchicken-9527** [comment]
emm...有没有可能这个颜色是组件的颜色🤯，我看着应该是组件的颜色；

**Comment by yaocanke** [comment]
不太可能是组件的颜色，因为页面里是1个按钮，但整个灰色的部分是个大的方块，你可以试一试，具体步骤如下：
1：新建1个仪表板（简称仪表板B），在仪表板B里放一个按钮组件，再将仪表B的仪表板背景设置一个颜色，并将不透明度设置成功0，保存，创建公共链接。
2：再新建1个仪表板（简称仪表板A），在仪表板A里放一个网页组件，并将上一个步骤中仪表板B的公共链接设置到网页组件（相当于将仪表板B嵌入到仪表板A），再将仪表板A的设置一个背景色，这样对比效果就出来了。

**Comment by BBchicken-9527** [comment]
emm...不好意思我真没看出区别，我尝试了你说的方法，但看上去和你给我的模版是没有区别的；大屏是有一个基础底色的，如果背景色设置为0会将基础底色暴露出来的；
![image](https://github.com/dataease/dataease/assets/84372766/76f3866a-58df-4f60-94bc-70bd6f261a56)
<img width="1252" alt="image" src="https://github.com/dataease/dataease/assets/84372766/c8f15747-171c-42a6-a728-61c4919f8a6d">

**Comment by yaocanke** [comment]
我用的是V1.18.X的版本，其实想要的效果是：将仪表版A嵌套到仪表板B里，将仪表板的A的背景色设置成透明，只保留仪表板B的背景色，这样看起来更像1个页面。但实际情况是，将仪表板的A的背景色设置成透明，还是会有一个底色，这样一眼就能看出是2个页面。

**Comment by BBchicken-9527** [comment]
感谢反馈，目前暂时不支持透明的，建议直接将两个仪表板的背景色调整成一样的；
