### ISSUE TITLE
[Bug]趋势图中纵轴轴值设置为自动，当有数据的结果接近最大值时，标签显示会出现被遮挡的情况

### ISSUE THREAD

**Issue by xiaoxiao261258** [dataease/dataease#9216]
**DataEase 版本**
v1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
趋势图中的基础折线图等，在纵轴的轴值设置为自动模式下时，对于数据中的最大值，会出现标签部分被遮挡的情况

**Bug 重现步骤(有截图更好)**
1. 因公司限制，无法截图，原始数据脱敏后如下，使用如下数据绘制基础折线图，横轴选择Month，子类别选Name，纵轴选择Time
纵轴的轴值选择自动，此时，纵轴轴值最大值会被设置为2500，与表格中的最大值2473非常接近，退出编辑模式（编辑模式下显示正常）后，会出现最大值2473标签显示不完整。

Month      Name    Time(min)
2024-04    A       6.9
2024-04    B       2.3333
2024-04    C       2473.5983
2024-04    D       59.7483
2024-04    E       5.155
2024-04    F       21.1167
2024-04    G       0.73
2024-04    H       23.0417

**Comment by BBchicken-9527** [comment]
感谢反馈，这个看起来应该是图库本身的问题，我们尝试优化一下，会在后续版本更新；

**Comment by xiaoxiao261258** [comment]
你好， v1.18.20 之后只修复安全漏洞，是说1.0版本不优化这个了吗？
