### ISSUE TITLE
[Bug]V2 仪表板筛选组件，文本下拉框值获取不全

### ISSUE THREAD

**Issue by hzhwyh0116** [dataease/dataease#9221]
**DataEase 版本**
 v2.5.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
 仪表板筛选组件，文本下拉框值获取不全

**Bug 重现步骤(有截图更好)**
1.选择一个 3w 行数据的数据集进行明细表展示
2.选择其中一个字段进行文本下拉框筛选过滤
3.若数据集行数过大会出现文本下拉框值获取不全的情况
![image](https://github.com/dataease/dataease/assets/89765365/39b467a4-0072-4e4e-8d35-09c180ca775a)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行优化；
