### ISSUE TITLE
[Bug]V2 ClickHouse SQL查询不支持Array（string）类型

### ISSUE THREAD

**Issue by Linkjie-11** [dataease/dataease#9222]
**DataEase 版本**
标准部署

**Bug 描述**
自定义SQL查询报错，表结构中有一个类型是Array（string）
![image](https://github.com/dataease/dataease/assets/52249559/0e6d03bb-1379-4dc8-829b-66c531e94e00)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，你可以尝试升级看一下是否问题依然存在；
![image](https://github.com/user-attachments/assets/211864ef-8035-4f68-9f12-92f74d2ed010)
