### ISSUE TITLE
[Bug]V1 can not be represented as java.sql.Timestamp

### ISSUE THREAD

**Issue by Linkjie-11** [dataease/dataease#9223]
**DataEase 版本**
V1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
标准部署

**Bug 描述**
MySQL定时同步，库里时间值字段为：0000-00-00 00:00:00 修改字段类型为时间后报错“can not be represented as java.sql.Timestamp
![451c0d76-7649-4c7e-9275-965bc757a799](https://github.com/dataease/dataease/assets/52249559/f0166887-07ff-4564-b5ec-5a44535476d5)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前定时同步的数据是存储到doris中的，doris本身并不支持这种无效的时间格式，在 Doris 中，日期值的有效范围是从 1000-01-01 到 9999-12-31，受限于存储库的原因短时间内无法支持；
