### ISSUE TITLE
[Feature]建议增加多个组件组合和组件批量移动等功能

### ISSUE THREAD

**Issue by yaocanke** [dataease/dataease#9224]
DataEase 版本:
V1.18.18

**请描述您的需求或者改进建议.**
当某一个仪表中用到了大量的组件时，在对页面的排版或布局调整时，需要对每个组件逐一拖动，工作量较大、效率较低，建议增加支持组件多选、多个组件组合成组、多个组件批量移动等功能，可大大节省工作量和提高工作效率。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议您使用2.x版本中的数据大屏。
