### ISSUE TITLE
[Feature]过滤组件支持联动

### ISSUE THREAD

**Issue by xiaoxiao261258** [dataease/dataease#9225]
DataEase 版本:
v1.18.18

**请描述您的需求或者改进建议.**
1、期望过滤组件支持联动如一个过滤条件是部门，另一个是人员名单，当我选择对应部门时，人员名单下拉组件只挂出当前所选择部门下的人员，而不是所有部门的人员列表。
2、这个功能最好是可配置的，即可以选择联动，也可以选择不联动。有些场景需要联动，但有些场景也是不需要联动的。

**Comment by hapeacock** [comment]
是不是这种过滤啊。我也想要啊。可以多个字段过滤，字段里的哪些可以显示或不显示，还可以标签显示。
![333](https://github.com/dataease/dataease/assets/59914136/64c2ec76-8090-42ff-b0ae-93e1a1edc2d7)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
v2版本已排期，v1版本暂缓支持。
