### ISSUE TITLE
[Feature]视图中的钻取/维度字段希望支持排序、显示名设置等维度下拉设置的功能

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#9226]
DataEase 版本:
v1.18.18

**请描述您的需求或者改进建议.**
当前视图中的钻取/维度字段，不支持排序、显示名设置等维度下拉设置的功能，希望支持像数据列/维度里的设置一样的功能支持
![image](https://github.com/dataease/dataease/assets/89771514/68515fef-301d-4dcb-8463-03f54a51501c)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，这里仅是下钻目录的设置，像对视图中的字段进行排序、显示名设置等还是在数据列中设置。
![image](https://github.com/dataease/dataease/assets/84168063/cc96fcf2-79b2-43ad-8da9-b50af3c6c588)

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，排序已经支持，显示名设置下个版本增加一下。
