### ISSUE TITLE
[Bug]V2时间动态组件，设置默认筛选日期，首次打开时不生效

### ISSUE THREAD

**Issue by zhuhuaibin** [dataease/dataease#9230]
**DataEase 版本**

V2
**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
版本 124.0.6367.61（正式版本） （64 位）

**Bug 描述**
时间动态组件，设置默认筛选日期，首次打开时不生效

**Bug 重现步骤(有截图更好)**
1.
![cc0fc42e48cc901d6c84afc47c00523](https://github.com/dataease/dataease/assets/50860759/d4e5ab29-bf31-44ea-a3dc-ce4476308c4b)

2.
![885ef52322af33dbfa3c89cfbcbbe11](https://github.com/dataease/dataease/assets/50860759/436c25a9-aaf9-4621-a429-bc539ea44878)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们将会在下个版本修复；
