### ISSUE TITLE
[Bug]透视表 v1和v2 数据行/维度 和 数据列/维度 定义问题，v1和v2相反

### ISSUE THREAD

**Issue by LinuxLeader** [dataease/dataease#9238]
**DataEase 版本**
v1.18.18 和 v2.5

**运行方式(安装包运行 or 源码运行 ?)**
离线

**浏览器版本**
最新版

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1. v1版本的数据行/维度 和 数据列/维度
![image](https://github.com/dataease/dataease/assets/43403764/ba314dd2-e6bb-425b-8e7b-801f7ff60d02)
2. v2版本的数据行/维度 和 数据列/维度
![image](https://github.com/dataease/dataease/assets/43403764/c1e7374d-4329-4fdf-9fd6-0a863def417d)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
