### ISSUE TITLE
[Bug]创建mysql数据源报错

### ISSUE THREAD

**Issue by spider1998** [dataease/dataease#9239]
**DataEase 版本**
v2.5

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 版本 124.0.6367.60（正式版本） （64 位）

**Bug 描述**
创建mysql数据源报错，校验正常，保存时报错：
![image](https://github.com/dataease/dataease/assets/42063601/c756d382-f26d-496a-8dfe-08fbb316aa3a)

**Bug 重现步骤(有截图更好)**
1.基于2.5源码编译，创建excel数据源都是正常的，但是在创建mysql时，校验都是正常，保存时报错
![image](https://github.com/dataease/dataease/assets/42063601/5b375bd3-3532-499f-b55a-c0a0f487c042)
2.mysql版本8.0
3.idea运行

**Comment by BBchicken-9527** [comment]
感谢反馈，数据集在最新版本做了优化，建议升级到最新版本尝试；我先将问题标记后关闭，若依然存在问题可将问题打开或联系交流群的伙伴进行支持；
