### ISSUE TITLE
[Bug]【数据源】SQLServer 数据源对接报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#9243]
**DataEase 版本**
v1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
SQLServer 数据源对接报错，截图如下：
![image](https://github.com/dataease/dataease/assets/24768910/2b91da43-c598-4299-9ee0-af2b7ed1e6b9)

数据库版本信息：Microsoft SQL Server 2012 (SP1) - 11.0.3000.0 (Intel X86)   Oct 19 2012 13:43:21   Copyright (c) Microsoft Corporation  Enterprise Evaluation Edition on Windows NT 6.2 <X64> (Build 9200: ) (WOW64) (Hypervisor)

**Comment by AndroidBaby1** [comment]
一开始用该驱动包，怎么也连不上，但是把版本全加上就可以对接 SqlServer 2012，请问这个是什么原理呀？
![image](https://github.com/dataease/dataease/assets/24768910/6f184846-0392-47a8-8b4d-f62b16dec9f9)

**Comment by BBchicken-9527** [comment]
感谢反馈，应该是版本与driver适配不够精确问题，我们尝试进行一下优化；
