### ISSUE TITLE
[Feature]定时报告收件人下拉列表的优化

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#9247]
DataEase 版本:
v1.18.18

**请描述您的需求或者改进建议.**
定时报告，收件人，输入后可以下拉，这可能是为自定义邮箱设计的，但用户输入中文姓名时也会下拉出来，用户误认为是 DE 系统存在的用户，结果报告并没有发出去。
可以做个邮箱格式识别，是邮箱才会下拉，非邮箱在用户体系没有匹配到下拉为空。
![图片](https://github.com/dataease/dataease/assets/48307752/c368cfac-a486-47fa-ae4a-a3a44bda5b59)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
v2版本已做相关优化，v1版本的优化暂缓。
