### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Sky-shang** [dataease/dataease#9250]
**dataease-release-v1.18.18**

**安装包运行**

**124.0.6367.61*

**更新到v1.18.18，Oracle驱动不支持19C**

**Bug 重现步骤(有截图更好)**
1.![image](https://github.com/dataease/dataease/assets/29321889/12d4a4fd-bad2-4ba3-9909-10ee229546ae)

**Comment by BBchicken-9527** [comment]
感谢反馈，de是支持自定义驱动的，毕竟我们支持大部分的主流数据库，对应又有不同的版本，如果包含太多的驱动则会太过臃肿，期望你能理解，可以通过管理员账号-数据源-驱动管理自己上传需要的驱动从而进行链接；
![image](https://github.com/dataease/dataease/assets/84372766/ca755bb3-4a2c-44e4-9e3f-3c4e6bd5c87e)
