### ISSUE TITLE
[Feature]嵌入式应用，一个应用的跨域设置可以配置多个访问地址

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#9253]
DataEase 版本:
V2.5

**请描述您的需求或者改进建议.**
由于在开发过程中，一般都存在开发环境、测试环境、生产环境等不用的地址，都共用一套Dataease实例，这样需要针对每个环境配置一个应用配置，但是其实都属于1个项目，所以希望在：“跨域设置”这里可以配置多个访问地址，兼容不同的部署环境。
![image](https://github.com/dataease/dataease/assets/89771514/ea942eaf-2d70-4595-a6f3-5c95f5872f11)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，目前暂时没有计划支持该功能。
