### ISSUE TITLE
[Feature]数据集行权限配置支持组织、角色、用户的模糊查询

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#9254]
DataEase 版本:
1.18.18

**请描述您的需求或者改进建议.**
数据集行权限配置支持组织、角色、用户的模糊查询
![image](https://github.com/dataease/dataease/assets/89771514/cd923fff-44f9-4462-b657-1d72a00be40a)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by xuwei-fit2cloud** [comment]
已排期。
