### ISSUE TITLE
通过api上传的数据在画图时展示的数据不一样

### ISSUE THREAD

**Issue by imjking** [dataease/dataease#9257]
通过api成功上传数，成功构造数据源和数据集，但是在生成图表时展示的数据和数据集里的不一样？？

数据集如下：
![a](https://github.com/dataease/dataease/assets/46706333/94b349b7-2537-422e-92ba-93f8a9dc2e27)、   
  
但画折线图时展示如下：
![image](https://github.com/dataease/dataease/assets/46706333/59f75c52-fa06-42d4-bf8f-b07521bfe9e2)   
勾选轴值添加最大最小值之后没有数据展示了：   
![image](https://github.com/dataease/dataease/assets/46706333/94b96f63-1266-4157-9e68-7d0abf166802)   

跟原始数据不匹配的原因是什么啊？可能是我哪里没搞对吗？
使用excel传的数据是完全ok的

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，您上传的数据是明细数据，比如：7时，数据集中是有多条数据的。在制作折线图时，会把明细数据进行分组聚合，建议您检查一下聚合方式。

**Comment by imjking** [comment]
好的，了解了，谢谢。
