### ISSUE TITLE
[Bug]V1 English 语言下前端布局错乱，公共链接无法支持 English

### ISSUE THREAD

**Issue by hzhwyh0116** [dataease/dataease#9258]
**DataEase 版本**
v1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
chrome

**Bug 描述**
1、V1 English 语言下前端布局错乱
2、公共链接无法支持其他语言

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/89765365/61ce004a-c58d-4610-ac12-4214b7b2a509)

2.免登录默认打开公共链接，仪表板内 button（下钻、详情等） 都是中文，能否在创建公共链接时多一个语言选择？
![image](https://github.com/dataease/dataease/assets/89765365/f59f8f36-8a32-4654-ad68-1086dc4d54b0)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前de的英文适配还不够完善，我们会尽快进行优化；

**Comment by hzhwyh0116** [comment]
视图放大导出图片也没做语言化：
![image](https://github.com/dataease/dataease/assets/89765365/69193619-484f-4e1f-b855-dca0916d219e)
