### ISSUE TITLE
组合图下，纵轴和副纵轴的轴值，在默认为自动的情况下，两边的值能否都默认为建议的最高值

### ISSUE THREAD

**Issue by htl258** [dataease/dataease#9264]
DataEase 版本:1.18.18

**请描述您的需求或者改进建议.**
组合图下，纵轴和副纵轴的轴值，在默认为自动的情况下，两边的值能否都默认为建议的最高值。比如 纵轴最高值为50，副纵轴最高值为130，能否把主副纵轴的轴值动态调整到150？目前主副纵轴轴值各自为自己的建议值，不好直接参照比较。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，在轴值自动计算的情况下，是图库根据指标值计算出来的一个比较好的显示结果，如果觉得自动的结果不合适，建议自定义轴值。

**Comment by htl258** [comment]
> 撤回的反馈，在轴值自动计算的情况下，是图库根据值计算出来的比较结果，如果自动的结果不理想，建议自定义轴值。
是主副轴默认值的值不对称的问题。单轴使用不影响，主副轴同时用影响比较大，手动调整的话，要是轴值超过设定值，又得再去手动调整数值，显得操作繁琐体验不佳，还是期望能优化下。
