### ISSUE TITLE
我在使用dataease的时候在有是个视图的情况下加上时间过滤在使用火狐浏览器的时候会导致后端服务挂起，在使用谷歌浏览器的时候不会

### ISSUE THREAD

**Issue by zcx992132258** [dataease/dataease#9265]
1.17.2
我在使用dataease的时候在有是个视图的情况下加上时间过滤的时候重复筛选不同时间并且切换视图使用时间筛选在使用火狐浏览器的时候会导致后端服务挂起，在使用谷歌浏览器的时候不会
你们有遇到过这个问题吗

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，不过测试环境的版本和你目前使用的版本相差比较大，建议升级一下看看是否依然存在问题；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
