### ISSUE TITLE
[Bug]DE_DATE_FORMAT函数格式转换有误

### ISSUE THREAD

**Issue by serson** [dataease/dataease#9267]
**DataEase 版本**
v2.5

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome

**Bug 描述**
数据源选择本地上传excel，将其中一文本类型的字段设置为时间。原始字段为'2024-03-01'这样的格式,页面选择期望转换的类型为yyyyMMdd，点击刷新数据，转换后显示的格式为yyyy-MM-dd HH:mm:ss.页面选择格式为yyyy-MM-dd,转换后显示的格式也为yyyy-MM-dd HH:mm:ss.格式的format没有生效，感觉只有一种默认的格式

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/25809082/35872804-0c8b-48e6-9bb2-71623f8b0ead)
2.
![image](https://github.com/dataease/dataease/assets/25809082/47aaa2bf-99cf-4519-bdc1-661aa69227c4)
3.
日志输出的sql为
calcite data preview sql: SELECT
     DE_STR_TO_DATE(t_a_0.`f_7fedb6b454fd0ddb`,'yyyy-MM-dd') AS f_ax_0,
     t_a_0.`f_1f7f6f4057041d01` AS f_ax_1,
     t_a_0.`f_37dfcaf66e6c3465` AS f_ax_2,
     CAST(t_a_0.`f_38fa3d9fb51ccda3` AS DECIMAL(20,4)) AS f_ax_3,
     t_a_0.`f_96044e9ee7ebb372` AS f_ax_4
FROM
    (SELECT t_a_0.`日期` AS f_7fedb6b454fd0ddb,t_a_0.`成本类型` AS f_1f7f6f4057041d01,t_a_0.`成本项目` AS f_37dfcaf66e6c3465,t_a_0.`成本（万元）` AS f_38fa3d9fb51ccda3,t_a_0.`test` AS f_96044e9ee7ebb372 FROM s_a_1.`excel_Sheet1_fb888b4354` t_a_0)   t_a_0
 LIMIT 100 OFFSET 0
4.可以看到DE_STR_TO_DATE的入参是正确的，由于无法看到DE_STR_TO_DATE的内部实现，所以无法解决这个问题

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，由于你是源码运行，不确定你是否改动和以及打包方式都有可能存在问题，建议你加入我们的交流群，上面有非常专业的同学会实时的回复你的问题，方便你快速并精准的定位到你的问题所在；

**Comment by serson** [comment]
> 感谢反馈，目前测试环境没有发现你说的问题，由于你是源码运行，不确定你是否改动和以及打包方式都有可能存在问题，建议你加入我们的交流群，上面有非常专业的同学会实时的回复你的问题，方便你快速并精准的定位到你的问题所在；

好的 请问交流群号是多少

**Comment by maninhill** [comment]
v2.6 单数据源已经支持原生 jdbc sql。
