### ISSUE TITLE
[Bug]移动端关联的仪表板，没有开通公共链接不会进行提示，PC端会提示

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#9276]
DataEase 版本
v2.5.0

运行方式(安装包运行 or 源码运行 ?)
安装包

浏览器版本
Chrome
版本 123.0.6312.124（正式版本） (arm64)

Bug 描述
设置跳转，如果对应仪表板没有开启公共链接，pc会进行提示，移动端不会提示，会错认以为跳转失效

![image](https://github.com/dataease/dataease/assets/127368807/15e00ad8-ec5b-4acf-9093-ca7c2e65047a)
![image](https://github.com/dataease/dataease/assets/127368807/e9dfb0bb-f2ca-4335-8478-abe2e48aea14)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行优化；
