### ISSUE TITLE
[Feature]【仪表板】v2 支持外部参数传值给图表过滤器

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#9281]
DataEase 版本:
v2

**请描述您的需求或者改进建议.**
v2 支持外部参数传值给图表过滤器
![image](https://github.com/dataease/dataease/assets/24768910/6fbed8a6-a15e-48f9-9ad0-983cd7bd1394)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，建议您外部参数直接关联图表，联动图表过滤图表的数据。
