### ISSUE TITLE
增加一个排序组件

### ISSUE THREAD

**Issue by XuGuangY** [dataease/dataease#9286]
DataEase 版本:

**请描述您的需求或者改进建议.**
如果有多个视图需要按降序或者升序排列，目前只能每一个视图就手动修改，无法联动，建议新增一个排序组件，用来联动排序多个视图

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，目前暂时没有计划支持该功能。
