### ISSUE TITLE
[Feature]【数据集】增加数据集不支持排序提示

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#9288]
DataEase 版本:
v1 or v2

**请描述您的需求或者改进建议.**
建议增加数据集不支持排序的提示

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请问是数据集哪个页面的排序功能？

**Comment by AndroidBaby1** [comment]
好的，是 SQL 数据集的数据预览页，看看要不要加一个提示，表示这里用 order by 没有作用，就是排序没有作用

**Comment by yayanpei-fit2cloud** [comment]
数据预览仅展示小部分数据，主要用于查看数据格式等，排序或者不排序关系不大，因此这里也暂时没有计划增加提示，建议在制作图表时进行排序查阅。

**Comment by AndroidBaby1** [comment]
是的，因为这个原因用户不知道，所以感觉可以考虑加一行注意什么的，避免用户觉得我们是有什么 BUG 存在！
