### ISSUE TITLE
[Bug]v1版本数据集无法读取sql server数据库的中文注释

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#9290]
**DataEase 版本**
1.18.11

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
v1版本数据集无法读取sql server数据库的中文注释，而mysql的中文注释是可以正常读取的；sql server版本为2016

**Bug 重现步骤(有截图更好)**
1.连接sql server数据源
2.创建sql数据集
3.无法获取数据库表结构的中文注释

如图，以下中文注释无法读取：
![image](https://github.com/dataease/dataease/assets/77324661/516c7113-66da-44f4-99d3-c43467f268b9)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本修复；

**Comment by maninhill** [comment]
#9387 重复。
