### ISSUE TITLE
[Feature] 高级多重联动选择

### ISSUE THREAD

**Issue by darrkz** [dataease/dataease#9294]
DataEase 版本:  
官网 v1.18.18 demo

**请描述您的需求或者改进建议.**

## 能否支持高级联动
比如同个地图组件, 省市可以多选
类似同时选中同一个组件的两部分, 类似
![d9f99537911130467347fa50d8fd18c](https://github.com/dataease/dataease/assets/1310923/9cfaa07a-4115-4f5e-9c6c-a7bcf1f99682)

或者多个不同组件的部分来进行联动
![09fc1e2e621ce289df29a14685fc9f7](https://github.com/dataease/dataease/assets/1310923/6bbf5d55-5b7d-471d-b634-ad831c83fff1)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by darrkz** [comment]
> 感谢您的反馈，我们需要先讨论一下。

感谢, 希望能尽快有个结论, 这个功能对我们来说是比较重要的功能

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和关注，我们目前暂时还没有计划支持该功能。
