### ISSUE TITLE
[Bug]升级V2.5版本后原先的sql无法执行

### ISSUE THREAD

**Issue by serson** [dataease/dataease#9303]
**DataEase 版本**
v2.5

**运行方式(安装包运行 or 源码运行 ?)**
源码原先

**浏览器版本**
chrome

**Bug 描述**
在2.3版本可执行的sql 在升级2.5版本后不可用，提示sql执行异常

**B ug 重现步骤(有截图更好)**
1.在2.3版本可执行的sql 在升级2.5版本后不可用，提示sql执行异常
SELECT DATE_FORMAT(`dt`, '%Y-%m-%d') AS `f_ax_0`, CAST((COUNT(DISTINCT `ac_reg`) FILTER (WHERE `type` = '引进')) - (COUNT(DISTINCT `ac_reg`) FILTER (WHERE `type` = '退出')) AS DECIMAL(18, 0)) AS `f_ay_0` FROM `airplan`.`ads_ap_airplane_import_leave_details` GROUP BY DATE_FORMAT(`dt`, '%Y-%m-%d')
![image](https://github.com/dataease/dataease/assets/25809082/1d6b4c62-841c-449c-9352-58f5e3a042a0)

**Comment by BBchicken-9527** [comment]
感谢反馈，由于之前为了降低数据集创建时calcite导致的问题做了源码上的优化，所以导致之前的部分数据出现了问题，给你的体验到来不便非常抱歉，目前只能通过重新创建解决，后期数据集这里会趋于稳定，请放心食用；
