### ISSUE TITLE
[Bug]可以正常创建oracle数据源，且能预览表及字段，但创建数据集的时候就崩溃了

### ISSUE THREAD

**Issue by jstbw** [dataease/dataease#9307]
**DataEase 版本**
2.5.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包，导入了嵌入式license

**浏览器版本**
多个同事的Chrome（124.0.6367.79）、edge（124.0.2478.51）都是这个问题

**Bug 描述**
大概有1000+的表，超时时间调成了3000s，de服务器配置是18C CPU、8G内存、300G硬盘。
oracle版本是：Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production

另外连了一个oracle，版本是Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production，表很少，可以正常创建数据集

**Bug 重现步骤(有截图更好)**
1.添加完数据源，可以看到预览的表和字段
![image](https://github.com/dataease/dataease/assets/66759501/b835655e-5dd6-4501-baaf-fec34b3fc9db)
![image](https://github.com/dataease/dataease/assets/66759501/916738cc-040a-4392-9d35-89cd4750b871)
![image](https://github.com/dataease/dataease/assets/66759501/d1e042ed-e4f2-4000-a5bc-f42ea198466b)
2、创建数据集就蹦了
![image](https://github.com/dataease/dataease/assets/66759501/160a8b6e-0ac7-4fcf-b6f9-8964887f7f1a)
![image](https://github.com/dataease/dataease/assets/66759501/43387edd-5aec-4612-a5f8-7bbdcadabc4c)

**Comment by xuwei-fit2cloud** [comment]
我们调研一下优化方案。
