### ISSUE TITLE
[Bug]图例居中显示，当字符串太长时显示不完整

### ISSUE THREAD

**Issue by xiaoxiao261258** [dataease/dataease#9315]
**DataEase 版本**
v1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome 124.0.6367.61

**Bug 描述**
图例居中显示，当描述较长时，比如30个英文字符，后面会显示成...，但实际上，对于居中的场景，是没必要的，因为有足够的空间可以显示完整。
居左和居右的场景下，太长显示为...是符合预期的。

**Bug 重现步骤(有截图更好)**
1.选择一个图表，设置图例较长，比如30个英文字符以上。
2.图例选择上方或下方均可，同时设置为居中显示，次数大概超过25个字符的部分，会被隐藏掉，显示为...

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是说超过了25个字符会隐藏部分字符显示是这个意思吗？

**Comment by xiaoxiao261258** [comment]
> 感谢反馈，你的意思是说超过了25个字符会隐藏部分字符显示是这个意思吗？

是的，当我的图例选择居中，并且放在图表上面或者下面的时候，这些图例是被会分成多行显示的，这种情况下，没必要隐藏了，全部显示出来就好了

**Comment by BBchicken-9527** [comment]
感谢反馈，因为是动态计算的所以会有一定的难度，我们想办法看看是否可以优化一下；

**Comment by maninhill** [comment]
v1 版本目前进入维护阶段，仅修复安全漏洞相关问题。
