### ISSUE TITLE
[Feature]When exporting pictures, can the export resolution support custom resolutions (because the title and label fonts still retain the original size after the table is full-screen, resulting in unclear text in the exported pictures)

### ISSUE THREAD

**Issue by xixistdio** [dataease/dataease#9316]
DataEase 版本:
v1.18.18

**请描述您的需求或者改进建议.**
When exporting pictures in any board, could you support  the export resolution by custom size ？(because the title and label fonts still retain the original size after the table is full-screen, resulting in unclear text in the exported pictures)

**Comment by yayanpei-fit2cloud** [comment]
Thanks for your feedback.The requirement had been planned in the version recently,please pay attention to version's release notes.

**Comment by xixistdio** [comment]
> Thanks for your feedback.The requirement had been planned in the version recently,please pay attention to version's release notes.



> Thanks for your feedback.The requirement had been planned in the version recently,please pay attention to version's release notes.
Thank you, you are the most professional

**Comment by xixistdio** [comment]
> Thanks for your feedback.The requirement had been planned in the version recently,please pay attention to version's release notes.

Thank you, you are the most professional
