### ISSUE TITLE
[Bug]瀑布图，提示的数值和图例的数值不一致

### ISSUE THREAD

**Issue by mmmlong** [dataease/dataease#9318]
**DataEase 版本**
2.5

**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**
谷歌

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.提示的格式类型，小数位数，单位，和标签的设置是一样的，但是提示的数值显示的不正确
![image](https://github.com/dataease/dataease/assets/30709129/d578fd6f-0909-4da0-ba4e-9a149f8b9635)
2.
![image](https://github.com/dataease/dataease/assets/30709129/208dc6dd-58d8-44b0-86bb-ab4334994d65)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本修复；
