### ISSUE TITLE
[Feature] 区间条形图支持类别

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#9319]
DataEase 版本:
v 1.18.18

**请描述您的需求或者改进建议.**
如图
![image](https://github.com/dataease/dataease/assets/45852479/b9c29ae5-18b3-424e-bb3a-79c24b23a5d1)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池中并调研一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的图库，图库不支持，issue我们这边就先关闭了。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的图库，图库不支持，issue我们这边就先关闭了。
