### ISSUE TITLE
[Question]v1.4.0 版本规划和时间

### ISSUE THREAD

**Issue by xuwei-fit2cloud** [dataease/dataease#932]
**请描述您的问题.**
v1.4.0 版本规划和时间

**Comment by xuwei-fit2cloud** [comment]
v1.4.0 计划11月4日发布，该版本的计划内容有：

仪表板:

- 支持超链接组件
- 支持仪表板的跳转
- 增加时间组件支持

数据源:

- 支持 CTE 及存储过程调用
- 支持 MongoDB 数据源
- druid 替换 c3p0

**Comment by maninhill** [comment]
v1.4.0 已经发布，详情请见：https://github.com/dataease/dataease/releases/tag/v1.4.0
