### ISSUE TITLE
[Feature]增加tab嵌套功能

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#9320]
DataEase 版本:
v2.5.0

**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/40597893/7e736fec-8628-472c-8c47-9a628596b587)
xia
现在tab组件无法再嵌套一个tab组件，但是很多这样的使用场景。
希望后续版本能支持tab嵌套

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，v2版本目前暂时没有计划支持tab嵌套。
