### ISSUE TITLE
[Feature]图表标题的备注显示问题

### ISSUE THREAD

**Issue by xiaoxiao261258** [dataease/dataease#9321]
DataEase 版本:

V1.18.18
**请描述您的需求或者改进建议.**
图表标题的备注，如果用英文描述的话，会出现单词从中间被截断换行的问题（因为行宽是固定的），影响阅读，建议考虑优化下显示效果。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在下个版本优化一下。
