### ISSUE TITLE
[Feature] v2 可以像 v1 的选项卡一样，tab页面可以调整顺序

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#9322]
DataEase 版本:
v2.5

**请描述您的需求或者改进建议.**
v2中tab页面调整不了顺序，里面视图多的时候，重做或者拖出来太麻烦，希望像 v1 这样：
![malA7VAlKw](https://github.com/dataease/dataease/assets/163749505/7bf35aff-f0b1-43b6-9403-6ad1d9800033)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先加入需求池中。
