### ISSUE TITLE
[Bug]图表选择详细列表，存在分页的情况下，右上角详情只能显示当前页面的数据，并且导出excel也只能导出当前页面数据

### ISSUE THREAD

**Issue by xiaoxiao261258** [dataease/dataease#9323]
**DataEase 版本**
v1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包版本

**浏览器版本**
 Chrome 124.0.6367.61

**Bug 描述**
详细列表的右上角详情页打开，存在分页的情况下，只能显示当前页面，导出excel也只能导出当前页面

**Bug 重现步骤(有截图更好)**
1.详细列表设置分页，比如10
2.表格的数据超过单页最大记录数，如13，单页最大在步骤1中设置了10
3.表格右上角详情查看，只能显示当前页面的数据，无法查看所有数据

**Comment by BBchicken-9527** [comment]
感谢反馈，目前问题已修复，可下载最新的进行体验；
