### ISSUE TITLE
[Question]请问支持https部署吗？

### ISSUE THREAD

**Issue by xiaoxiao261258** [dataease/dataease#9325]
**请描述您的问题.**
目前通过安装包部署的，访问方式是http，如果要修改成https（最好能支持从http自动跳转到https），应该如何修改配置文件？

**Comment by xiaoxiao261258** [comment]
我找到了一个guide，这里说的是可以配置80跳转到https，我配置的访问端口是8080 ，所以，guide里面的80我按照8080来配置的，提示8080端口被占用。

https://kb.fit2cloud.com/?p=9

**Comment by xuwei-fit2cloud** [comment]
这是nginx代理的配置问题，如果你要以域名的方式访问的话，一般建议搭建的nginx以80端口运行，后端的DataEase可以运行在8080端口，这个没问题。

在https://kb.fit2cloud.com/?p=9文档里，proxy_pass   http://172.31.0.48:9876/; 这个可以换成DataEase的ip加端口。

**Comment by xiaoxiao261258** [comment]
> 这是nginx代理的配置问题，如果你要以域名的方式访问的话，一般建议搭建的nginx以80端口运行，后端的DataEase可以运行在8080端口，这个没问题。
> 
> 在[https://kb.fit2cloud.com/?p=9文档里，proxy_pass](https://kb.fit2cloud.com/?p=9%E6%96%87%E6%A1%A3%E9%87%8C%EF%BC%8Cproxy_pass) http://172.31.0.48:9876/; 这个可以换成DataEase的ip加端口。

这个guide里面的https部署，实际是通过反向代理的方式，对外呈现为https，但工具本身，仍然是http部署的，我这么理解对吗？

**Comment by xuwei-fit2cloud** [comment]
> > 这是nginx代理的配置问题，如果你要以域名的方式访问的话，一般建议搭建的nginx以80端口运行，后端的DataEase可以运行在8080端口，这个没问题。
> > 在[https://kb.fit2cloud.com/?p=9文档里，proxy_pass](https://kb.fit2cloud.com/?p=9%E6%96%87%E6%A1%A3%E9%87%8C%EF%BC%8Cproxy_pass) http://172.31.0.48:9876/; 这个可以换成DataEase的ip加端口。
> 
> 这个guide里面的https部署，实际是通过反向代理的方式，对外呈现为https，但工具本身，仍然是http部署的，我这么理解对吗？

可以。

**Comment by xiaoxiao261258** [comment]
> > > 这是nginx代理的配置问题，如果你要以域名的方式访问的话，一般建议搭建的nginx以80端口运行，后端的DataEase可以运行在8080端口，这个没问题。
> > > 在[https://kb.fit2cloud.com/?p=9文档里，proxy_pass](https://kb.fit2cloud.com/?p=9%E6%96%87%E6%A1%A3%E9%87%8C%EF%BC%8Cproxy_pass) http://172.31.0.48:9876/; 这个可以换成DataEase的ip加端口。
> > 
> > 
> > 这个guide里面的https部署，实际是通过反向代理的方式，对外呈现为https，但工具本身，仍然是http部署的，我这么理解对吗？
> 
> 可以。

好的，感谢~

**Comment by hoccxx** [comment]
https://kb.fit2cloud.com/?p=9按照这个配置https后显示 Invalid Host header
