### ISSUE TITLE
[Bug] DataEase V2 修改数据集字段类型为日期后，切换过滤组件为自定义，无法更改过滤组件类型

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#9328]
**DataEase 版本**
v2.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行 

**浏览器版本**

正在更新 Chrome
版本 124.0.6367.61（正式版本） (arm64)

**Bug 描述**
[Bug] DataEase V2 修改数据集字段类型为日期后，切换过滤组件为自定义，无法更改过滤组件类型

**Bug 重现步骤(有截图更好)**
1.  数据集字段类型为文本，手动切换为时间，在数据集侧展示没有问题
![image](https://github.com/dataease/dataease/assets/30063018/b0c3b368-3b48-4bac-a513-b56e79af59d0)
![image](https://github.com/dataease/dataease/assets/30063018/3de8555f-100e-4771-91f6-a65b21ce15d6)

2. 仪表板选择该字段作为查询条件，切换到自定义，可以看到使用的是切换前的字段类型
![image](https://github.com/dataease/dataease/assets/30063018/480cd25b-5b70-4db3-8d54-515b61097948)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前最新测试环境没有发现你所说的问题，可以尝试下载新版本体验；
