### ISSUE TITLE
[Feature]希望水波图或者指标卡达到阈值时不单是字体颜色，能有文字的提示

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#9333]
DataEase 版本:
v1 和 v2

**请描述您的需求或者改进建议.**
1、指标卡达到阈值的时候，希望有提醒文字出来
2、水波图超过100%，能有阈值的提示效果

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，可以通过给指标卡和水波图进行样式设置，来区分是否达到阈值。请问是什么场景下，需要文字提示呢？

**Comment by janus177** [comment]
> 感谢您的反馈，可以通过给指标卡和水波图进行样式设置，来区分是否达到阈值。请问是什么场景下，需要文字提示呢？

是希望展示效果更好，比如设置阈值并设置文字提示低于该值怎样怎样、或者高于该值怎样怎样、或者这是标准值要注意怎样怎样；水波图低于百分百会有动画，超过百分百没有溢出的效果

**Comment by yayanpei-fit2cloud** [comment]
您可能是考虑到查阅报表的人，不太清楚阈值的设置规则，建议您将这些信息放在图表的标题备注中，方便查阅报表时帮助用户理解。

**Comment by maninhill** [comment]
这个问题暂无支持计划。
