### ISSUE TITLE
[Bug]仪表板界面左侧样式折叠打开以后，最下方样式已经下沉到界面下面，但是没有下拉框，只能折叠其他样式后才能进行样式更改

### ISSUE THREAD

**Issue by lanshan12315** [dataease/dataease#934]
**DataEase 版本**

1.3
**浏览器版本**

Chrome google最新版
**Bug 描述**

仪表板界面左侧样式折叠打开以后，最下方样式已经下沉到界面下面，但是没有下拉框，只能折叠其他样式后才能进行样式更改
**Bug 重现步骤(有截图更好)**
1.在样式修改的时候，如果打开多个折叠样式，就会使下面的样式没法看到
2.
![image](https://user-images.githubusercontent.com/65176188/137272081-a15d2c73-97b0-4a48-9f7b-b259ececc19f.png)
3.

**Comment by xuwei-fit2cloud** [comment]
确实无法复现
