### ISSUE TITLE
[Bug] v2.5 的tab中放置多个图表进行操作有概率触发图表错位压缩

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#9340]
**DataEase 版本**
v2.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包部署

**浏览器版本**
谷歌

**Bug 描述**
tab 中放置了10个左右的视图，会对 tab 里的视图进行调整拖动预览的操作，
一天操作下来会随机出现两次错乱，而且只错乱tab里的，需要不停复制仪表板备份

**Bug 重现步骤(有截图更好)**
1. tab 中放置了10个左右的视图
2. 对 tab 里的视图进行调整拖动预览的操作
3. 一天操作下来会出现两次错乱，而且恢复不了
原始是这样：
![image](https://github.com/dataease/dataease/assets/163749505/338ff9fd-5c24-408f-a921-350ac7d92179)
之后会变成：
![image](https://github.com/dataease/dataease/assets/163749505/33526a4f-decc-4f18-8c84-1b6a5a8520d8)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你在调整的时候是否调整了tab组件的大小？

**Comment by janus177** [comment]
> 感谢反馈，请问你在调整的时候是否调整了tab组件的大小？

是把tab组件拉满整个画布，会在里面调整视图

**Comment by BBchicken-9527** [comment]
刚刚我也是这样试了一下好像没有发现你说的问题，你那边还会有这种问题吗？

**Comment by janus177** [comment]
> 刚刚我也是这样试了一下好像没有发现你说的问题，你那边还会有这种问题吗？

v2.5是偶发性的，v2.6目前还没出现

**Comment by BBchicken-9527** [comment]
好的，那我这边先关掉这个问题，如果再发现再打开这个问题吧，我这边测试环境也是暂时没有发现这个问题；

**Comment by janus177** [comment]
> 好的，那我这边先关掉这个问题，如果再发现再打开这个问题吧，我这边测试环境也是暂时没有发现这个问题；


你好，v2.6也会出现这个问题

**Comment by janus177** [comment]
> 好的，那我这边先关掉这个问题，如果再发现再打开这个问题吧，我这边测试环境也是暂时没有发现这个问题；

你好，v2.6也出现这个问题了

**Comment by BBchicken-9527** [comment]
> > 好的，那我这边先关掉这个问题，如果再发现再打开这个问题吧，我这边测试环境也是暂时没有发现这个问题；
> 
> 你好，v2.6也出现这个问题了

感谢反馈，请问你那边出现这种问题频繁嘛？数据量是多少？多少个图表呢？

**Comment by janus177** [comment]
> > > 好的，那我这边先关掉这个问题，如果再发现再打开这个问题吧，我这边测试环境也是暂时没有发现这个问题；
> > 
> > 
> > 你好，v2.6也出现这个问题了
> 
> 感谢反馈，请问你那边出现这种问题频繁嘛？数据量是多少？多少个图表呢？

这个问题不会有固定规律出现，就是会在制作 v2 仪表板过程中突然出现，这次就只在 tab 里放了一个图表。

**Comment by BBchicken-9527** [comment]
> > > > 好的，那我这边先关掉这个问题，如果再发现再打开这个问题吧，我这边测试环境也是暂时没有发现这个问题；
> > > 
> > > 
> > > 你好，v2.6也出现这个问题了
> > 
> > 
> > 感谢反馈，请问你那边出现这种问题频繁嘛？数据量是多少？多少个图表呢？
> 
> 这个问题不会有固定规律出现，就是会在制作 v2 仪表板过程中突然出现，这次就只在 tab 里放了一个图表。

好的我这边再看看，因为是偶现的问题所以解决起来不会那么的及时希望你可以理解；

**Comment by mmmlong** [comment]
2.6的也发现这个问题了， 偶发性的，tab里面的图表编辑的时候宽度正常的， 预览打开再编辑，被挤在一起了
