### ISSUE TITLE
[Bug]导出PDF时tab标签内的背景边框丢失

### ISSUE THREAD

**Issue by alita0824** [dataease/dataease#9344]
**DataEase 版本**
v1.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
导出PDF时tab标签内的背景边框全部丢失，tab外的边框颜色丢失

**Bug 重现步骤(有截图更好)**
1.
![微信截图_20240425160932](https://github.com/dataease/dataease/assets/11935354/615780fc-88d5-481d-910c-ccaa0e4f8b69)

2.
![微信截图_20240425160919](https://github.com/dataease/dataease/assets/11935354/ddee82ed-cd85-4ff0-a0f5-c9d6920dcd27)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
