### ISSUE TITLE
[Feature]符号地图只坐标在边角显示不佳，建议留点空隙

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#9349]
DataEase 版本:
符号地图只坐标在边角显示不佳，建议留点空隙，不然圈都显示不全

**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/127368807/22e669b7-7693-4448-b52a-909f2d4399c7)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，地图显示的空间是这么大，因此当气泡刚好在边界时会显示不全，可以用鼠标拖动地图显示完整气泡。
