### ISSUE TITLE
[Feature]可以自行调整某一单一元素（例如条形图某一列）颜色

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#935]
**请描述您的需求或者改进建议.**
希望支持对图形中更细粒度元素的颜色自定义，例如单独调整每一列/行的条形图颜色，而非调整配色方案中的颜色。
应用场景：需要在图形中突出某一信息等。
![image](https://user-images.githubusercontent.com/48945409/137273006-9b9393ab-c6cc-4f26-b630-614724b7b953.png)

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
