### ISSUE TITLE
[Bug]视图层对大数据量进行渲染的时候一直处于加载状态，过十几秒以后就变成初始状态了

### ISSUE THREAD

**Issue by lanshan12315** [dataease/dataease#936]
**DataEase 版本**
1.3

**浏览器版本**
谷歌最新版

**Bug 描述**
视图层对大数据量进行渲染的时候一直处于加载状态，过十几秒以后就变成初始状态了

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/65176188/137274209-3c70fba8-f7f2-4085-bc05-0f317c53c511.png)
 有超过一千条数据
2.
![image](https://user-images.githubusercontent.com/65176188/137274353-95292563-6869-4e9d-812e-9cf88d93cbd1.png)
 一直处于加载状态
3.
![image](https://user-images.githubusercontent.com/65176188/137274581-7bf91746-3679-4963-b657-ee913446d16b.png)
jiazaiwan 加载完毕的状态

**Comment by tjlygdx** [comment]
数据集是直连还是同步的呢，数据量有多大？

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 版本已处理
