### ISSUE TITLE
Cannot invoke "java.sql.Connection.unwrap(java.lang.Class)" because "this.connection" is null

### ISSUE THREAD

**Issue by hystrix0779** [dataease/dataease#9363]
我用了2.3.0也报这个错，校验能通过，数据库版本是mysql:8.2.0 

<img width="973" alt="image" src="https://user-images.githubusercontent.com/57122774/325843424-1df8e7ea-5ed4-4786-a054-8aec5520457f.png">
<img width="872" alt="image" src="https://user-images.githubusercontent.com/57122774/325843637-235280ac-9c72-44d6-b687-a66c16900784.png">

<br class="Apple-interchange-newline">
<img width="1337" alt="image" src="https://github.com/dataease/dataease/assets/57122774/c0d8209d-dd52-4da9-93fc-140960e9b303">

_Originally posted by @hystrix0779 in https://github.com/dataease/dataease/issues/6555#issuecomment-2078576037_

**Comment by hystrix0779** [comment]
应该是这里的问题，但是没想到解决方法

<img width="1383" alt="image" src="https://github.com/dataease/dataease/assets/57122774/5f5f6a83-c90c-4e05-8662-8d17145c2caf">

**Comment by xuwei-fit2cloud** [comment]
可以参考一下：
https://bbs.fit2cloud.com/t/topic/2180/5
