### ISSUE TITLE
[Feature] 指标卡阈值增加背景变色

### ISSUE THREAD

**Issue by limin-fit2** [dataease/dataease#9370]
DataEase 版本:

V2.5

**请描述您的需求或者改进建议.**
 希望 “ 指标卡 ” 能像V1版本一样在阈值设置背景变色
![image](https://github.com/dataease/dataease/assets/61964761/99ee3484-9e88-46ca-b506-984478b28baf)

**Comment by limin-fit2** [comment]
还有水波图，可以像V1版本一样设置区间变色

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已规划在版本迭代中，请等待版本发布。
