### ISSUE TITLE
[Feature] 图表类型增加文本卡

### ISSUE THREAD

**Issue by limin-fit2** [dataease/dataease#9371]
DataEase 版本:

V2.5版本

**请描述您的需求或者改进建议.**
数据展示层存在文字也会设置阈值情况，例如状态等类型，富文本无法满足需求，所以希望能像V1版本一样支持“文本卡”，并且支持设置阈值（文字和背景都可变色）
![image](https://github.com/dataease/dataease/assets/61964761/11aad636-e2d8-4135-96e2-561971ad1402)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，富文本中计划支持条件格式，可以通过条件格式的设置，设置文字颜色和组件背景色。

**Comment by xuwei-fit2cloud** [comment]
请升级版本。
