### ISSUE TITLE
[Bug]【数据集】SqlServer 2012 和 2016 数据集注释获取不对

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#9387]
**DataEase 版本**
v1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
SqlServer 2012 数据集注释获取不对，获取的是字段名称而非字段注释

**Bug 重现步骤(有截图更好)**
1.数据库显示
![image](https://github.com/dataease/dataease/assets/24768910/84588315-d3b5-4596-a3e7-b17e2c7f0183)

2.数据集显示
![image](https://github.com/dataease/dataease/assets/24768910/5149aa4e-4071-4015-970a-4d9aea162af1)

**Comment by AndroidBaby1** [comment]
这边可以提供该版本的环境哈~

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
