### ISSUE TITLE
[Bug]透视图表头为日期或者日期转化的文本时，不完全展示，自动省略

### ISSUE THREAD

**Issue by cuckooM** [dataease/dataease#9415]
**DataEase 版本**
v2.5.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 123.0.63

**Bug 描述**
透视图表头为日期或者日期转化的文本时，不完全展示，自动省略。即使手动拖动表格列宽度，保存后查看，仍然自动省略。

**Bug 重现步骤(有截图更好)**
1. 在仪表板中增加透视图
2. “数据行/维度”选择一个时间属性（或者时间转化的文本）
3. “数据列/指标”选择一个“数值(小数)”属性
4. 表头自动省略，即使手动拖动宽度，保存后查看依然自动省略。
![image](https://github.com/dataease/dataease/assets/19563707/e50f6fd0-7e0c-49a1-ac0b-7fa73218293e)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问时间是带时分秒的吗？还有你的表格设置是否是自适应，如果是自适应的话是没问题的，透视表时根据表格内的内容去自适应而给是表头；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；

**Comment by cuckooM** [comment]
> 感谢反馈，请问时间是带时分秒的吗？还有你的表格设置是否是自适应，如果是自适应的话是没问题的，透视表时根据表格内的内容去自适应而给是表头；

不好意思，我刚看到回复。我设置了自适应，存在这个问题的。表头列比较宽，表身列比较窄，看起来“自适应”是根据表身列适应的，所以表头被省略了。即使不选“自适应”而选“固定宽度”也会有这个问题。所以看起来是个 bug。

**Comment by BBchicken-9527** [comment]
现在还有问题吗？我现在在测试环境没发现你说的这个问题了，或者尝试升级一下；
![image](https://github.com/dataease/dataease/assets/84372766/e312dee8-5d34-41c7-a264-98312459e653)

**Comment by cuckooM** [comment]
> 现在还有问题吗？我现在在测试环境没发现你说的这个问题了，或者尝试升级一下； ![image](https://private-user-images.githubusercontent.com/84372766/332337597-e312dee8-5d34-41c7-a264-98312459e653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjUxNzQsIm5iZiI6MTcxNjM2NDg3NCwicGF0aCI6Ii84NDM3Mjc2Ni8zMzIzMzc1OTctZTMxMmRlZTgtNWQzNC00MWM3LWEyNjQtOTgzMTI0NTllNjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA4MDExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4MTM5MDliYWJkOGY4NjMzMGIzZTE3MDAxODQ4NTA1MDQ1MWEyMTE0N2MzMjdiN2FhMDJkOWQ1ZWYwNTM3YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bqD88zIzgTjbIBUjNAKvgLCjRzVPgscl75yZoW0WClc)

设置为“自适应”的话还有问题，不过我通过设置“固定列宽”为 130 规避了。
