### ISSUE TITLE
源码部署后，运行 java -jar CoreApplication.jar 时报错

### ISSUE THREAD

**Issue by imjking** [dataease/dataease#9417]
源码部署后，运行java -jar CoreApplication.jar时报如下错误：

java.sql.SQLException: Access denied for user 'root'@'172.17.0.1' (using password: YES)
![image](https://github.com/dataease/dataease/assets/46706333/0dbe20bf-0180-475b-ada3-1af735bc427e)

mysql已经docker部署，可以访问成功。
请问这是什么问题啊？

**Comment by maninhill** [comment]
请查阅在线文档中源码部署章节。
