### ISSUE TITLE
这几个版本是不是都不能本地源码调试 啊？

### ISSUE THREAD

**Issue by bergkamp2008999** [dataease/dataease#9425]
您好，这几个版本是不是都不能本地源码调试 啊？
2.3我试了，一直报错呢。flyway错误
### Cause: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "CORE_RSA" not found; SQL statement:
SELECT id,private_key,public_key,aes_key,create_time FROM core_rsa WHERE id=?  [42102-214]
; bad SQL grammar []]
java.lang.IllegalArgumentException: No enum constant io.dataease.model.DeModel.@PROFILES.ACTIVE@
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at io.dataease.model.DeModel.valueOf(DeModel.java:3)
	at io.dataease.utils.ModelUtils.get(ModelUtils.java:18)

配置数据库是哪个文件呢，挺乱的。

**Comment by maninhill** [comment]
请参考：https://dataease.io/docs/v2/installation/deployment_installation/
