### ISSUE TITLE
[Feature] 视图支持双击字段选择维度/指标

### ISSUE THREAD

**Issue by ziliang-wan** [dataease/dataease#9427]
DataEase 版本:
v2.5

**请描述您的需求或者改进建议.**
视图支持双击字段自动设置维度/指标

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录并加入需求池中。

**Comment by xuwei-fit2cloud** [comment]
由于有些图表字段栏较多，如堆叠项等，我们并不能确定点击的字段应该添加到哪一栏中，所以不予支持。
2.10.2版本可以支持批量选择多个字段进行拖动操作，可以通过选择多个字段来进行批量操作。
