### ISSUE TITLE
[Bug] DE服务器在不接入互联网的情况下，无法使用导入的离线模板（但是可以正常导入，创建仪表板或大屏时却无法使用）

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#9440]
**DataEase 版本**
v2.5.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
DE服务器在不接入互联网的情况下，无法使用导入的离线模板（但是可以正常导入，创建仪表板或大屏时却无法使用）

**Bug 重现步骤(有截图更好)**
1. 在DE服务器无法访问互联网的情况下，导入任意一个离线模板
2. 创建仪表板或者数据大屏时使用模板
<img width="1268" alt="image" src="https://github.com/dataease/dataease/assets/45967454/01687297-d527-45ca-9a8c-6a4c721427d8">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
