### ISSUE TITLE
地图出现小数 数值

### ISSUE THREAD

**Issue by Light-Towers** [dataease/dataease#9458]
**请描述您的问题.**
版本：V2.4
请问为什么地图的左侧会带有小数点？明明我的数据集都是整数

![image](https://github.com/dataease/dataease/assets/29267453/ca1583d7-f80a-4061-ba48-e0309ebc7e3e)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们已经在v2.5版本进行了优化，建议您升级至v2.5版本。
