### ISSUE TITLE
[Feature]文件夹内的子文件夹/看板 支持排序，自定义排序，上移下移

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#9462]
DataEase 版本:
1.18.18

**请描述您的需求或者改进建议.**
仪表板目录：文件夹内的子文件夹/看板 支持排序，自定义排序，上移下移

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持资源列表的自定义排序，建议您根据一定的规则对资源名称进行命名，然后再根据名称排序。
