### ISSUE TITLE
[Feature]导出仪表板，支持导出excel数据，每一个视图数据一个sheet页

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#9464]
DataEase 版本:
1.18.18

**请描述您的需求或者改进建议.**
导出仪表板，支持导出excel数据，每一个视图数据一个sheet页

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，1.x上没有计划进行支持了，2.x近期暂时也不考虑支持。
