### ISSUE TITLE
[Feature]指标卡可以放文本类型字段，方便使用去重计数

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#9466]
DataEase 版本:
V2.5

**请描述您的需求或者改进建议.**
比如计算展示一共多少类商品
![image](https://github.com/dataease/dataease/assets/101089844/8fad237e-c0a6-4f67-bf6d-c97f4aa394d4)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。
