### ISSUE TITLE
[Bug]当仪表板中包含“/”时，定时报告发送报错 FileNotFoundException

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#9468]
**DataEase 版本**
V1.18.18

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge最新

**Bug 描述**
我的仪表板标题是：PC/Server采购分析看板
当仪表板标题中包含斜杠 / 时，发送定时报告报错如下

java.io.FileNotFoundException: /opt/dataease/data/b5101331-c7b9-11ed-b332-ab73d1b09bde_18/330/PC/Server采购分析看板.xlsx (No such file or directory)

<img width="1695" alt="image" src="https://github.com/dataease/dataease/assets/30886198/bee4cc31-db32-463b-a717-c01419e4e90a">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行优化；
