### ISSUE TITLE
[Feature] 仪表板界面图表设置刷新频率后，能否以数据集为判断条件进行前端的数据请求和查询

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#9470]
DataEase 版本:
v2.5.0 

**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/45967454/d2e9da9a-1a82-4148-ac96-bc6c9137ef01)
问题：从上图可以看到，这9个图表都使用了一个数据集，在数据刷新的时候数据查询接口却请求了9次，如果这是一个API数据源，那是不是会查询9次我的API接口，有性能上的压力，并且展示速度也不会很快。
建议：能否以数据集为判断条件进行前端的数据请求和查询

**Comment by xuwei-fit2cloud** [comment]
这里虽然使用的是同一个数据集，但查询的内容不同，统计方式不同，导致在后台生成的查询SQL也不相同，所以还是需要分开进行请求的。DataEase本身并不提供过多的计算能力，而是通过将查询转换成数据库对应的SQL语句来进行计算处理的，所以这个需求目前是无法支持的。
