### ISSUE TITLE
筛选框联动功能[Feature] V2.7

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#9472]
DataEase 版本: V2.7

**请描述您的需求或者改进建议.**
比如我有 一级，二级，三级业务模块， 以及业务模块对应的机房， 机柜， 产品等筛选字段。 
期望筛选 一级模块后， 二级业务模块只展示 属于改 业务模块的 二级模块，  其他的三级业务模块， 机房， 机柜， 产品等以此类推。 
我在筛选框上可以选择对应的联动字段. 

因为这些范围太大。 单纯要人去记下来是特别难的事情.

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，组件之间的联动功能，我们已经规划在近期的版本中进行支持，请等待版本的发布。

**Comment by 18927580527** [comment]
这个筛选框的联动，不止有两层，如果用下拉树来实现是不能满足要求的。  期望有多层可自定义的联动.

**Comment by 18927580527** [comment]
提了需求，又排了里程碑。结果又不做.

**Comment by xuwei-fit2cloud** [comment]
收集到的需求比较多，人力有限，目前已支持，还请理解。
