### ISSUE TITLE
[Feature]数据源支持

### ISSUE THREAD

**Issue by sixawn** [dataease/dataease#9473]
DataEase 版本:1.18.18

**请描述您的需求或者改进建议.**
 目前数据源的支持很丰富，请问是否有将vertica 这种 MPP 的数据库纳入的计划吗？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们目前没有计划在v1.x版本上支持新的数据源，我们先记录并放进2.x的需求池中，待收集更多同类需求后，再进行下一步的规划。

**Comment by xuwei-fit2cloud** [comment]
#4084
