### ISSUE TITLE
同一数据源自定义SQL支持通过库表关联查询

### ISSUE THREAD

**Issue by kevinlxj** [dataease/dataease#9475]
DataEase 版本:
V2.x

**请描述您的需求或者改进建议.**
v2.x版本以mysql为例，下面有两个库，A、B库，自定义sql不支持库表关联，比如A.表 left join B.表，但其实账号同时拥有访问A，B库的权限，麻烦支持下呢，现实情况这种很常见。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，自定义目前没有计划支持跨源关联。
