### ISSUE TITLE
[Bug]SQL Server 2008R2 的数据源创建数据集时报错

### ISSUE THREAD

**Issue by The0neHK** [dataease/dataease#9478]
**DataEase 版本**
V2.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google Chrome 123.0.6312.124

**Bug 描述**
SQL Server 2008R2 数据源创建数据集的时候报错

**Bug 重现步骤(有截图更好)**
1.
![603badfefb2826d2d1397002866fa55](https://github.com/dataease/dataease/assets/38492381/e6dd388f-1618-4185-8daf-9882b99410b4)

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，目前数据集采用calcite中间件进行数据的链接，目前calcite无法支持sqlserver2012一下的版本；
