### ISSUE TITLE
[Bug]查询正常运行，仪表盘无法使用，报错： [You cannot use the window function 'min' in this context.']

### ISSUE THREAD

**Issue by NetBOOSS** [dataease/dataease#9482]
**DataEase 版本**
2.5

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome 

**Bug 描述**
自定义sql查询数据时可以的，但是在仪表盘使用这个数据就不行

**Bug 重现步骤(有截图更好)**
1.新建sql数据集
![微信图片_20240430143020](https://github.com/dataease/dataease/assets/44220143/3920c0a6-12e2-4db6-8ce0-355f9a64de67)
2.创建仪表盘使用指标卡
![微信图片_20240430143026](https://github.com/dataease/dataease/assets/44220143/6f6d82eb-8b09-45fb-b920-666df3ea406c)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你使用的数据源是APi数据源吗？目前最新版本测试环境没有发现你说的问题，建议升级查看一下是否依然存在
![image](https://github.com/dataease/dataease/assets/84372766/27cae009-3b7f-48f3-af40-1a8a77fd1183)
![image](https://github.com/dataease/dataease/assets/84372766/21d160e1-0b95-4d98-82aa-601be1879950)

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
