### ISSUE TITLE
[Feature]小助手可以隐藏

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#9483]
DataEase 版本:
v1,v2

嵌入的场景有需要隐藏的需求。
可设置开关。

![图片](https://github.com/dataease/dataease/assets/48307752/9cd3455b-4f97-494a-8d43-9a0b67f9706c)
![图片](https://github.com/dataease/dataease/assets/48307752/2988f026-d539-49a1-84e2-58bd233d6919)

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们增加个配置项。
