### ISSUE TITLE
[Feature]优化-视图联动时有共同字段会自动关联

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#9487]
DataEase 版本:
v1.18.18

关联时，会把仪表板中同一个数据集的视图自动勾选上，视图有共同字段会自动关联，如下图，如果视图上字段不同不会自动关联字段。
![60174c443c83c5b6bce9b1ceb509116](https://github.com/dataease/dataease/assets/48307752/9a772213-e764-4b88-a956-4fc997841c7f)

之前是视图没有共同字段，只要表一样，也能把相同的字段关联上。希望优化一下。

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录一下，建议您先手动关联。

**Comment by maninhill** [comment]
v1.18.20 为最后一个功能版本， 暂无支持计划。
