### ISSUE TITLE
[Feature]v2流媒体组件支持

### ISSUE THREAD

**Issue by jstbw** [dataease/dataease#9491]
DataEase 版本:
v2.5

**请描述您的需求或者改进建议.**
v1版本有支持流媒体，可以接入rtsp之类的视频流，现在v2.5及后续的2.6这块还是不能支持，这块是比较刚需的，特别是嵌入式版本，影响购买意愿，希望能尽快支持。

**Comment by xuwei-fit2cloud** [comment]
这个需求已经在排期中，目前排期在v2.8
