### ISSUE TITLE
地图图例是否支持自定义

### ISSUE THREAD

**Issue by Light-Towers** [dataease/dataease#9493]
**请描述您的问题.**
请问地图图例是否支持自定义编辑：显示的区间范围，显示的个数。
(下面的地图数据中广东省的数据太大，导致其它省份的显示的颜色都是黄色)
![image](https://github.com/dataease/dataease/assets/29267453/020f5231-98e1-4e42-9abb-cdd3dbf37866)

**Comment by xuwei-fit2cloud** [comment]
已排期。
