### ISSUE TITLE
透视表如何直接显示原文本，而不是汇总？

### ISSUE THREAD

**Issue by xix1** [dataease/dataease#9496]
如题，在使用透视表时，如何直接显示原文本呢？明细表可以显示原文本，但是维度不够多，无法满足需要。

**Comment by xuwei-fit2cloud** [comment]
透视表的设计本身就是会对同组数据进行汇总，如果要显示原文本，只能使用明细表。
您说的维度不够多是指？

**Comment by xix1** [comment]
透视表横竖方向都可以设置表头，相同的表头内容还可以自动合并，我想在透视表中显示数据的原始内容，无论是数值格式还是文本格式的。
