### ISSUE TITLE
docker 部署后  添加数据源类型为sql server时报错

### ISSUE THREAD

**Issue by SuperManYo** [dataease/dataease#9504]
获取Schema 的时候报错，com.microsoft.sqlserver.jdbc.SQLServerDriver。
![微信图片_20240507132937](https://github.com/dataease/dataease/assets/167167620/3f8d4ba8-0870-451c-ac6c-178c991946d5)

**Comment by xuwei-fit2cloud** [comment]
SQLServer具体的版本是？

**Comment by SuperManYo** [comment]
@xuwei-fit2cloud  2019 版本的sql server，现在问题是我用 docker部署的话  就会报这个错，但是我直接在控制台启动jar包就没问题。下图为docker启动日志。
![Uploading 微信图片_20240507145557.png…]()

**Comment by xuwei-fit2cloud** [comment]
是官方的docker镜像吗？我们并没有复现这个问题。如果是自己做的镜像的话，是否有将驱动程序打入镜像中？

**Comment by C726** [comment]
请问这个问题有解决吗？ 我也遇到同样的问题
