### ISSUE TITLE
[Feature]sql 数据集编辑页面数据参考可以拉宽

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#9505]
DataEase 版本:
v1.0 

**请描述您的需求或者改进建议.**
r如图所示，当表名比较长的时候，看不清，希望可以能拉宽红框部分。
<img width="1383" alt="image" src="https://github.com/dataease/dataease/assets/109720729/f4191c35-f6ec-41d4-9e83-4392ad5bbfc7">

**Comment by xuwei-fit2cloud** [comment]
上方提供了模糊搜索功能，鼠标移动到选项上，也提示了完整的表名信息。
暂时不考虑支持拉宽。
