### ISSUE TITLE
我电视浏览器访问外部链接的时候报错

### ISSUE THREAD

**Issue by peipeilove** [dataease/dataease#9506]
![微信图片_20240507142609](https://github.com/dataease/dataease/assets/38198872/3e3af209-a043-4e4d-9607-e2de27448f03)
![微信图片_20240507142614](https://github.com/dataease/dataease/assets/38198872/b38d8505-8bb9-48eb-8180-d9031c320d1e)

手机和PC电脑 访问没有问题，电视谷歌浏览器访问的时候出现了问题。是不是跟浏览器的版本有关系，电视端的浏览器我也开了桌面模式尝试依旧不可以。

**Comment by xuwei-fit2cloud** [comment]
使用短链接在电视上再试试？

**Comment by xuwei-fit2cloud** [comment]
也可以试试清理一下浏览器缓存。
