### ISSUE TITLE
仪表板添加数据源再添加富文本后，富文本字体无法调整，没有编辑框

### ISSUE THREAD

**Issue by Tom4CS** [dataease/dataease#9508]
**DataEase 版本**
V2.3 社区版，部署机器无网络访问权限

**运行方式(安装包运行 or 源码运行 ?)**
离线安装包

**浏览器版本**
试过EDGE和Chrome 都不行

**Bug 描述**
富文本格式编辑窗口没出来

**Bug 重现步骤(有截图更好)**
1.添加富文本
![image](https://github.com/dataease/dataease/assets/102843073/46ebfb9e-febe-4b67-bf93-49ef4839007d)

2.输入文字
![image](https://github.com/dataease/dataease/assets/102843073/e7f79ef2-bee8-416e-b212-398b9994b6e0)

3.x选中文字无编辑框出现
![image](https://github.com/dataease/dataease/assets/102843073/9a9c8985-490f-4048-b069-c0c9ec686c07)

**Comment by Shenguobin0102** [comment]
您好，感谢反馈，您描述的问题在 v2.6 社区版中没有复现，如果您的环境中问题依然存在，建议将系统升级到最新版本。
