### ISSUE TITLE
[Feature]仪表盘组件增加刻度值相关配置

### ISSUE THREAD

**Issue by yuhuaimaomao** [dataease/dataease#9510]
DataEase 版本:2.5.0

**请描述您的需求或者改进建议.**

![image](https://github.com/dataease/dataease/assets/24558648/0a1612d3-3482-4091-a903-e335cbda706e)
仪表盘组件缺少取消刻度数值的相关配置，希望能增加

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们增加一下。
