### ISSUE TITLE
[Bug]V2版本，sql在命令行可以正常执行，放入sql数据集执行异常

### ISSUE THREAD

**Issue by Y-ai** [dataease/dataease#9516]
**DataEase 版本**
v2.4.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Chrome 已是最新版本
版本 124.0.6367.119（正式版本） （32 位）

**Bug 描述**
sql数据集没有办法执行正常sql

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
v2版本的SQL需要遵循Calcite的语法，并不是在SQL命令行能正常执行的SQL都符合Calcite语法的。
我们目前正在支持原生SQL语法，5月9日即将发版的v2.6.0版本即可支持，还请关注。

**Comment by JackChius** [comment]
同样的情况，怪不得就说sql在shell里正常运行的dataease大都运行不了

**Comment by Y-ai** [comment]
好的，明天更新一下，

**Comment by maninhill** [comment]
v2.6 单数据源已经支持原生 jdbc sql。
