### ISSUE TITLE
[数据集]数据集excel上传数据，数据类型识别错误

### ISSUE THREAD

**Issue by BBchicken-9527** [dataease/dataease#952]
**DataEase 版本**
v1.3

**浏览器版本**
谷歌

**Bug 描述**
数据类型识别错误

**Bug 重现步骤(有截图更好)**
1.上传
![image](https://user-images.githubusercontent.com/84372766/137436153-b06c31fd-0b06-404b-8e10-58eb7d017e3e.png)

2.识别为
![image](https://user-images.githubusercontent.com/84372766/137436210-6fba1d29-292b-42ad-ac07-9dea8be7c56f.png)

3.

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我们处理一下

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 已修复
