### ISSUE TITLE
[Bug]java.sql.SQLException: Access denied for user 'root' (using password: YES)

### ISSUE THREAD

**Issue by WholeWorld-Timothy** [dataease/dataease#953]
**DataEase 版本**
1.3.0

**浏览器版本**
chrome

**Bug 描述**
离线安装完成后，定义定时更新的数据集后，访问报错

**Bug 重现步骤(有截图更好)**
1.离线安装
2.创建mysql或者posgresql数据源
3.创建定时更新数据集
4.访问数据集报错

**Comment by tjlygdx** [comment]
https://dataease.io/docs/faq/dataset_faq/#excel-access-denied-for-user-rootusing-passwordyes 
参考这个文档，尝试解决一下
