### ISSUE TITLE
[Feature]表格鼠标浮动时的背景色及文字颜色需要能够修改

### ISSUE THREAD

**Issue by yuhuaimaomao** [dataease/dataease#9540]
DataEase 版本:V2.25.0

**请描述您的需求或者改进建议.**
如图，表格鼠标浮动时的背景色及文字颜色需要能够修改

![image](https://github.com/dataease/dataease/assets/24558648/9d996e49-eefc-48bb-9733-83caac7bad94)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录一下，近期暂时没有计划进行支持。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本可以选择表格鼠标焦点是否显示，可以试试。
