### ISSUE TITLE
[Feature]富文本组件增加文字间距调整功能

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#9542]
DataEase 版本:
V2

**请描述您的需求或者改进建议.**
![16271715161002_ pic](https://github.com/dataease/dataease/assets/101089844/813dedc7-b687-4127-8698-ab5fe3ac2e3e)

**Comment by yayanpei-fit2cloud** [comment]
感谢你的反馈，需要先看下组件是否支持。

**Comment by xuwei-fit2cloud** [comment]
请升级版本。
