### ISSUE TITLE
[Feature]轴值自动显示的时候，从最小值开始显示，便于观察趋势波动

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#9544]
DataEase 版本:
2.6

**请描述您的需求或者改进建议.**
轴值选了自动以后，显示的数据范围从最小值开始，而不是从零开始，否则当最小值很大的时候，会有很长的空白范围，以及不便与观察数据趋势
![image](https://github.com/dataease/dataease/assets/40597893/6274c244-a522-4cf7-99bf-38fe811135b1)

![image](https://github.com/dataease/dataease/assets/40597893/26a2e425-899b-4192-ada1-fda58141be53)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，常见的图表纵轴一般是从0开始的，图库这里也是根据图表的数值给出的一个最佳展示效果，因此这里暂时没有计划进行优化，如有需要建议您自定义纵轴的轴值。
