### ISSUE TITLE
请问我如何在现有的表格组件基础上，计算两列的比值呢？

### ISSUE THREAD

**Issue by xix1** [dataease/dataease#9547]
如题，我现在有一个明细表，有两列是数值类型，请问怎么计算这两列的比值呢？这两列已经根据第一列group过了，不是原始数据

**Comment by yayanpei-fit2cloud** [comment]
如果数据集中是已经group后的结果，需要在仪表板的明细表中展示数据集，建议您在数据集中增加计算字段，计算两列的比值。
