### ISSUE TITLE
[Question] CAST DECIMAL 長度錯誤

### ISSUE THREAD

**Issue by tonyfud** [dataease/dataease#9549]
**请描述您的问题.**
v 2.5

SQL执行失败，请检查表、字段、关联关系等信息是否正确并重新编辑。exception while executing query: While executing SQL [SELECT CAST(`id` AS DECIMAL(18, 0)) AS `f_ax_0` FROM `test`.`stock_info` LIMIT 100 OFFSET 0] on JDBC sub-schema [errCode = 2, detailMessage = (172.30.221.160)[CANCELLED][E-124][E-124] Arithmetic overflow no enable stack]

正常應該是 CAST(`id` AS DECIMAL(19, 0))   我是 19為長度， 爲什麽自動搞成 18呢？ 創建數據集全都是這種問題報錯，沒法用。

數據源是  aliyun  的 Doris ->   selectdb

**Comment by tonyfud** [comment]
SELECT LENGTH(1266897420672184322);

**Comment by tonyfud** [comment]
也沒地方設置吧 强制 cast 關掉。

**Comment by yayanpei-fit2cloud** [comment]
感谢你的反馈，我们对这里进行了优化，今天发布v2.6版本，建议您升级到v2.6版本。
