### ISSUE TITLE
[Feature] 增加功能：可以查看我已经分享出去的仪表板记录。

### ISSUE THREAD

**Issue by zyy2721** [dataease/dataease#955]
**请描述您的需求或者改进建议.**
因为仪表板已经分享出去，且数量可能较多。
希望支持查看有哪些仪表板是我已经分享出去的、分别分享给了哪些人。

**Comment by yayanpei** [comment]
非常感谢您的反馈，您的建议非常好，我们会优先考虑加入版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 已支持
