### ISSUE TITLE
[Bug]SQLServer 2008 创建数据集报错

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#9553]
**DataEase 版本**
v2.6.0

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新

**Bug 描述**

如图
![image](https://github.com/dataease/dataease/assets/30886198/b3e5b1ca-21e7-4546-a75d-427670e4efb9)

**Comment by Shenguobin0102** [comment]
感谢反馈，我们会在后续版本修复。

**Comment by coderxucoder** [comment]
请问这个问题计划什么时候解决呢？

**Comment by wxpqs** [comment]
这个问题现在2.9版本了还未能解决，不知道还能不能得到解决，还是说只能使用V1版本了？

**Comment by maninhill** [comment]
@XiaJunjie2020 俊杰看看这个问题。

**Comment by XiaJunjie2020** [comment]
已修改calcite修复该问题。
9403f7f7d80177e5eb322d8bfd5176405a451dbb
