### ISSUE TITLE
[Feature] 有没有可能让仪表盘图表增加一个“扩展配置项”？

### ISSUE THREAD

**Issue by snecker** [dataease/dataease#9554]
DataEase 版本:
目前的固定配置项有限。

**请描述您的需求或者改进建议.**

antv图表配置项非常多，也不可能把每一个配置都集成到dataease的前端来给用户自定义配置。

如果图表这里有个“扩展配置”字段，接受一个json字符串，让用户可以参考antv的对应选项来灵活设置，这样便会灵活很多。

如图
![image](https://github.com/dataease/dataease/assets/4178594/510553a9-e395-4a27-abfd-105fac2fca04)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，目前暂时没有计划进行支持。
