### ISSUE TITLE
[Question]与zabbix6对接时发生sql语法错误。

### ISSUE THREAD

**Issue by vzrs** [dataease/dataease#9557]
**请描述您的问题.**
zabbix数据库为mysql，查询functions表时发生错误。如下：
 [Object 'functions' not found]

**Comment by vzrs** [comment]
补充一下：
sql语句：
SELECT
	h.NAME AS 主机名称,
	COUNT( p.eventid ) AS 问题数 
FROM
	problem p
	LEFT JOIN (
	SELECT
		s1.triggerid,
		( SELECT s2.itemid FROM functions s2 WHERE s2.triggerid = s1.triggerid LIMIT 1 ) AS itemid 
	FROM
		functions s1 
	GROUP BY
		s1.triggerid 
	) AS f ON f.triggerid = p.objectid
	LEFT JOIN `items` AS i ON i.itemid = f.itemid
	LEFT JOIN `hosts` AS h ON h.hostid = i.hostid
	LEFT JOIN `interface` AS inf ON inf.hostid = h.hostid 
WHERE
	p.r_eventid IS NULL 
	AND h.STATUS = 0 
	AND i.STATUS = 0 
GROUP BY
	h.hostid,
	h.HOST 
ORDER BY
	问题数 DESC 
	LIMIT 10;

在数据库软件中执行没有问题，在新建数据集时出现问题。
报错信息：SQL执行失败，请检查表、字段、关联关系等信息是否正确并重新编辑。Error while preparing statement [SELECT * FROM (SELECT `h`.`NAME` AS `主机名称`, COUNT(`p`.`eventid`) AS `问题数` FROM `s_a_981935237858725888`.`problem` AS `p` LEFT JOIN (SELECT `s1`.`triggerid`, (SELECT `s2`.`itemid` FROM `functions` AS `s2` WHERE `s2`.`triggerid` = `s1`.`triggerid` FETCH NEXT 1 ROWS ONLY) AS `itemid` FROM `s_a_981935237858725888`.`functions` AS `s1` GROUP BY `s1`.`triggerid`) AS `f` ON `f`.`triggerid` = `p`.`objectid` LEFT JOIN `s_a_981935237858725888`.`items` AS `i` ON `i`.`itemid` = `f`.`itemid` LEFT JOIN `s_a_981935237858725888`.`hosts` AS `h` ON `h`.`hostid` = `i`.`hostid` LEFT JOIN `s_a_981935237858725888`.`interface` AS `inf` ON `inf`.`hostid` = `h`.`hostid` WHERE `p`.`r_eventid` IS NULL AND `h`.`STATUS` = 0 AND `i`.`STATUS` = 0 GROUP BY `h`.`hostid`, `h`.`HOST` ORDER BY `问题数` DESC FETCH NEXT 10 ROWS ONLY) tmp LIMIT 100 OFFSET 0] [Object 'functions' not found]

但是直接执行select * from functions是没问题的。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请问是v2.5版本吗？

**Comment by vzrs** [comment]
是v2.5版本的。

**Comment by maninhill** [comment]
v2.6 在单数据源情况下支持原生 jdbc sql，请升级。
