### ISSUE TITLE
[Bug]【数据集】Impala 数据源拖入表报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#9559]
**DataEase 版本**
v2.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
Impala 数据源拖入表报错，截图如下
![image](https://github.com/dataease/dataease/assets/24768910/7b1ffb37-267e-482e-8560-62ae54861c9b)
Impala 版本：3.1.0+cdh6.1.0

**Bug 重现步骤(有截图更好)**
可提供环境直接对接复现

**Comment by Shenguobin0102** [comment]
感谢反馈，我们会在下个版本修复。

**Comment by liuboF2c** [comment]
impala SQL 数据集创建也报异常
![image](https://github.com/dataease/dataease/assets/30886198/6b64083b-c312-450f-a6ee-1f2961546510)

**Comment by maninhill** [comment]
v2.10-lts 版本已经发布，请在最新版本上面验证，有问题请 re-open。
