### ISSUE TITLE
[Feature]定时更新数据集能够对接其他类型数据库？

### ISSUE THREAD

**Issue by WholeWorld-Timothy** [dataease/dataease#956]
**请描述您的需求或者改进建议.**
doris目前更新比较慢，druid、hudi等产品在蓬勃发展，能否其他数据源作为定时更新数据集的存储？

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
