### ISSUE TITLE
[Question]【数据源】目前 v2.6 版本对接 doris 数据源，是否不支持添加 hive catalog 这种形式

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#9560]
**请描述您的问题.**
目前 v2.6 版本对接 doris 数据源，是否不支持添加 hive catalog 这种形式（目前 v1.18.19 可以用这种方式对接成功）
v2.6 截图
![image](https://github.com/dataease/dataease/assets/24768910/6faf1b46-97ad-4bb8-bc69-0e9539dc47be)
v1.18.19 截图
![image](https://github.com/dataease/dataease/assets/24768910/3affc92d-a113-449a-a3a1-f58dd7a380dd)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们兼容一下。
