### ISSUE TITLE
[Feature]【数据同步】数据同步功能源数据支持 doris、impala 两种类型

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#9563]
DataEase 版本:
v2.6

**请描述您的需求或者改进建议.**
数据同步功能源数据支持 doris、impala 两种类型

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈，我们先记录一下需求，待有更多同类需求后再做下一步的规划。
doris和impala自身的数据处理能力也是非常不错的，建议您通过直连的方式直接使用。
