### ISSUE TITLE
[Bug]数据大屏多选有系列问题

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#9565]
DataEase 版本:

2.6

1.c t r l 多选三个图表调节不起作用
2.多选两个图表后，第三个图表与组合框重合时，不能被选中
3.多选后直接保存，返回数据大屏列表页显示出现问题，再进入大屏，原组合框还存在
4.（有时发生）移动图层位置后，不按ctrl的情况下鼠标直接点击图层也会多选
5.（有时发生）点击图层操作按钮，会选中所有图层，且弹窗显示问题

**Bug 重现步骤(有截图更好)**
1.2.
https://github.com/dataease/dataease/assets/133861755/53bd3488-4f2b-44c1-921f-9bb1997ad60e
3.
https://github.com/dataease/dataease/assets/133861755/8e7d0a7e-fc48-4901-9c72-1d90f7af0d86
4.5.
https://github.com/dataease/dataease/assets/133861755/1975d67e-b116-43a1-b00d-346572c0330f

https://github.com/dataease/dataease/assets/133861755/1fdec914-edbf-497d-aaa9-5864107179a9

**Comment by BBchicken-9527** [comment]
感谢反馈，
问题1：目前同时选中两个以上需要点击一下多选时的提示边框才会出现拖拽的标识，这个可能对用户的体验造成影响我们优化一下；
问题2：无法选中组合框重叠的部分是因为当选中多个组件时你可以理解为这两个组件相当于在归于一个图层所以在点击遮盖的部分是属于下层组件（虽然你可以看见,但实际隔了一个图层）无法选中，这个我们看看有没有优化的空间可以调整；
问题3：确实存在此类问题，我们下个版本进行修复；
问题4和5：目前我尝试没有发现此类问题，是否存在其他操作，导致这种情况呢？
我这边先去处理1、2、3问题，4和5暂时未发现；

**Comment by zhangtong9898** [comment]
4、5发现是快捷键冲突，按了录屏快捷键command+shift+5之后开始录屏，录屏过程中点击多选会复现
