### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ITwuwei** [dataease/dataease#958]
sqlesever  计算字段
![8c26a2abef60eea67aecce04caac5e4](https://user-images.githubusercontent.com/35763006/137444370-6944eec1-c6d5-4020-83f2-30eec5546aed.png
![c9be70fcd3c91a4b2142c89c3b35ffc](https://user-images.githubusercontent.com/35763006/137444431-8a3d10f4-955f-4b7f-9b56-bd73740c4e77.png)
)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈， 我们尽快修复

**Comment by xuwei-fit2cloud** [comment]
v1.4.0 已修复
