### ISSUE TITLE
[Feature]支持Es数据源

### ISSUE THREAD

**Issue by timeroar** [dataease/dataease#9583]
DataEase 版本:
v2.x

**请描述您的需求或者改进建议.**
1.x为啥有es 2.x咋给取消了,希望引入

**Comment by xuwei-fit2cloud** [comment]
由于Calcite对ES的支持问题，我们在2.x版本中还没引入，后续会通过JDBC连接方式支持。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
