### ISSUE TITLE
[Bug]首页工作台，点击分享，如果取消分享，弹出框无法关闭

### ISSUE THREAD

**Issue by mmmlong** [dataease/dataease#9584]
**DataEase 版本**
2.6

**Bug 描述**
首页工作台，当点击分享图标后，弹出的对话框，如果不想分享或者取消分享，弹出框无法关闭，只能强迫分享，并复制链接才能关闭，
建议不操作分享的情况下，也可以关闭

**Bug 重现步骤(有截图更好)**
1.
<img width="1208" alt="image" src="https://github.com/dataease/dataease/assets/30709129/46806f30-b4c7-4cef-9c7a-0a07c4902bba">

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行优化；

**Comment by BBchicken-9527** [comment]
感谢反馈，问题已修复，可以尝试下载新版本体验；
