### ISSUE TITLE
[Feature]SQL 重复字段自动加 0

### ISSUE THREAD

**Issue by hzhwyh0116** [dataease/dataease#9588]
DataEase 版本:
v2.6.0

**请描述您的需求或者改进建议.**
数据集编写 SQL 时能否考虑重复字段自动加 0？

例如：
select * from area a left join area b on a.id=b.id

1、之前 v2.5.0 时，会默认修改重复字段名称，在重复字段名称后+0 如：
<img width="1440" alt="image" src="https://github.com/dataease/dataease/assets/89765365/08434ae6-2e05-45c5-b1b2-1e35c172e85c">

2、升级到 v2.6.0 后，之前保存好的数据集都报错；并且数据集做的大屏都无法正常显示结果，导致所有大屏的数据集需要重新调整
<img width="1440" alt="image" src="https://github.com/dataease/dataease/assets/89765365/92505821-db61-45f9-9678-c09a9c340333">

期望：
1、升级时尽量考虑向下兼容，让存量数据走 calcite 引擎，避免由于升级导致大屏不可用的情况发生
2、个人认为 “默认在重复字段名称后+0” 的用户体验更好，当数据表字段过大时，穷举字段的确增加了使用成本

**Comment by xuwei-fit2cloud** [comment]
走Calcite处理与走JDBC处理的方式不一样，Calcite里我们可以处理字段名称重复的情况，JDBC的话，这个语句作为一条语句去执行，我们还没拿到字段处理，就已经返回报错了。
