### ISSUE TITLE
[Bug]仪表板复制出现大小变形

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#9596]
**DataEase 版本**
2.6

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
复制yi一张仪表板之后，自适应出现问题

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/8aa48665-d967-4cde-b311-571ee92a80a4)

2.
![image](https://github.com/dataease/dataease/assets/109720729/f899e3ad-3f33-4b92-9c20-15e6c69da170)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
