### ISSUE TITLE
[Bug] desktop版本启动报错

### ISSUE THREAD

**Issue by hhw3KevinHou** [dataease/dataease#9597]
**DataEase 版本**
2.6.0

**运行方式(安装包运行 or 源码运行 ?)**
源码

**浏览器版本**

**Bug 描述**
desktop版本启动失败

**Bug 重现步骤(有截图更好)**
1. java -jar CoreApplication.jar
2.![image](https://github.com/dataease/dataease/assets/14155363/1171fc0b-398a-4af1-8bc8-8c902042318c)

**Comment by BBchicken-9527** [comment]
感谢反馈，由于你是源码运行，不确定你是否改动和以及打包方式都有可能存在问题，建议你加入我们的交流群，上面有非常专业的同学会实时的回复你的问题，方便你快速并精准的定位到你的问题所在；其实这个就是flyway报错了，对数据库做一下调整就可以了；

**Comment by hhw3KevinHou** [comment]
交流群是哪个，你不是搞技术的来玩github？

**Comment by xuwei-fit2cloud** [comment]
desktop版本目前还没发布，flyway里的SQL确实有些问题。
除此之外，在使用的时候，有些查询SQL也没做测试，使用上也可能存在问题，还请等待desktop版本正式发布后再使用。
