### ISSUE TITLE
[Feature] 矩形树图

### ISSUE THREAD

**Issue by MaekBlack** [dataease/dataease#9598]
DataEase 版本:
v 1.18.19

**请描述您的需求或者改进建议.**
1. 矩形树图标签如果在方块较多情况下，个别不会居中
2. 希望标签展示能够包含维度

![image](https://github.com/dataease/dataease/assets/45852479/bebd3f18-2cd6-414d-8c8e-3d4f42159d61)

**Comment by xuwei-fit2cloud** [comment]
v2版本可以支持维度、指标和占比的显示，v1版本目前没有支持的计划。
