### ISSUE TITLE
[Bug]数据视图中修改图标颜色仪表盘不更新，还是默认颜色配色

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#96]
**DataEase 版本**
1.0.0

**浏览器版本**

谷歌浏览器

**Bug 描述**
在数据视图中将饼状图或者柱状图的颜色色调修改完成后在仪表盘页面中还是默认配色，未更新

**Bug 重现步骤(有截图更好)**
1.数据视图中将图标配色改为复古
2.进入仪表盘查看仪表盘依旧是默认配色
3.

**Comment by XiaJunjie2020** [comment]
修改视图中样式优先级，视图默认仪表板样式优先

**Comment by xueqidove** [comment]
这个太隐蔽了，感觉应该加个说明

**Comment by xueqidove** [comment]
响应速度超级赞👍
