### ISSUE TITLE
[Feature]超链接钻取

### ISSUE THREAD

**Issue by caiiansheng** [dataease/dataease#960]
建议支持钻取到另一个视图或仪表盘，现在这种需求比较多，点击一个图的字段，通过传参数的形式跳转到另一个视图

**Comment by yayanpei** [comment]
感谢您的反馈，我们规划在 V1.4.0版本（发版日期：11月4日）实现跳转，还请您多多关注。

**Comment by xuwei-fit2cloud** [comment]
v1.4.0 已支持跳转
