### ISSUE TITLE
[Feature] 数据大屏中的图表能否支持图表类型切换？

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#9601]
DataEase 版本:
v2.6.0

**请描述您的需求或者改进建议.**
数据大屏中的图表能否支持图表类型切换？仪表板中的图表是可以进行图表类型切换的。

**Comment by xuwei-fit2cloud** [comment]
我们讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录一下需求，待有更多同类需求后再做进一步的规划。
