### ISSUE TITLE
分析场景自由构图拖拽维度指标功能  [Feature]

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#9604]
DataEase 版本:
在用户分析的场景中，业务可以自己根据数据集自定义指标和维度，以及自定义图形。  可以临时给用户生成用户想要的报表. 

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，即席分析功能目前还没有相关排期，需要等待后期产品设计完成后才会支持。
