### ISSUE TITLE
Tab支持嵌套功能[Feature] V2.8

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#9605]
DataEase 版本: V2.8

目前在配置报表的时候，包含实时和离线指标。期望能在 一级tab 区分 实时和离线。  
然后再二级 tab 里面展示不同的指标。 这样在单个页面可以减少 第一次 打开去查询的数据。

**请描述您的需求或者改进建议.**

**Comment by xuwei-fit2cloud** [comment]
目前没有计划支持Tab嵌套。
我们讨论一下这个场景的其他解决方案。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，已经加入需求池中，优化方案不确定，因此近期暂时没有计划进行支持。
