### ISSUE TITLE
[Feature]可以对图例中某一属性增加注释

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#961]
**请描述您的需求或者改进建议.**
有时在一个图表中需要特别对某一数据做解释/注释以增强说明和用户的关注。
![image](https://user-images.githubusercontent.com/48945409/137455332-908010d7-69b2-46be-848f-a972e976e1fe.png)

**Comment by yayanpei** [comment]
非常感谢您的反馈，您的建议非常好，我们会考虑加入后期的版本迭代中。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
