### ISSUE TITLE
api数据源请求接口数据量为500条时接口超时，系统参数里设置为3000s不管用

### ISSUE THREAD

**Issue by 465722253** [dataease/dataease#9610]
![截屏2024-05-11 16 52 04](https://github.com/dataease/dataease/assets/83146405/f96fcdef-5182-4c8a-b482-9b0445839a13)
数据量200以下可以正常查询

![Uploading 200条.png…]()
![Uploading 500条.png…]()

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你是用的版本是？

**Comment by 465722253** [comment]
> 感谢反馈，请问你是用的版本是？

版本是2.5的 好像2.6的也不行  ，用postman请求是不会超时的

**Comment by 465722253** [comment]
![Uploading A4OG$0X7%LNZ4_}FLSM)33Y.png…]()

看代码好像是后端写死了，就是10s,在系统参数里设置超时时间设置多大也没用

**Comment by BBchicken-9527** [comment]
我这边尝试没有发现超时，但会非常的卡顿，每条数据多少个字段？我这边模拟一下；

**Comment by 465722253** [comment]
我这边一共的数据量为4000多条 每条数据的字段差不多将近100个字段了 
![截屏2024-05-13 09 06 34](https://github.com/dataease/dataease/assets/83146405/03f58eeb-706f-4962-829b-8256c11b2638)

这个查询200条是正常的
我把这个改成500条就time out 了
![截屏2024-05-13 09 07 53](https://github.com/dataease/dataease/assets/83146405/f0542cb2-ffa3-43d4-8377-63cb81cd215f)

**Comment by 465722253** [comment]
![Uploading 200条.png…]()
![Uploading 500条.png…]()

**Comment by 465722253** [comment]
![截屏2024-05-13 09 10 45](https://github.com/dataease/dataease/assets/83146405/7e6939c6-b33c-46bb-92ae-5e407cf481bb)
好像是后端代码固定写成10s了 不知道是不是这个原因

**Comment by BBchicken-9527** [comment]
感谢反馈，我这边测试环境看了一下是没有出现timeout的问题的，请问多少个字段？

**Comment by BBchicken-9527** [comment]
😂确实，不好意思给你带来困扰，我们修复一下，将会在下个版本上线；

**Comment by 465722253** [comment]
请问下个版本会在什么时间上线，有通知提醒吗

**Comment by BBchicken-9527** [comment]
公众群会有通知的，并且官网以及github同步，我们是坚持每月定时发版的，一般是在每个月的月初；

**Comment by maninhill** [comment]
v2.10-lts 版本已经发布，请在最新版本上面验证，有问题请 re-open。
