### ISSUE TITLE
时间过滤条件 小于等于 1970-01-01 00:00:00 ，查询失效

### ISSUE THREAD

**Issue by juicezws** [dataease/dataease#9611]
**DataEase 版本** v2.5

**运行方式(安装包运行 or 源码运行 ?)** 源码运行

**浏览器版本** chrome

**Bug 描述**

时间过滤条件 小于等于 1970-01-01 00:00:00 ，时间格式化后变成负数

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/32792548/68ed050b-dceb-4d0d-b2a6-748554f3fddc)

![image](https://github.com/dataease/dataease/assets/32792548/d9e9bb3d-d7e5-42db-aaa1-6332ce5a9c0a)

**Comment by Shenguobin0102** [comment]
感谢反馈，这是个已知问题，是因为calcite不支持1970年以前的时间，如果您的时区是当前时区，1970-01-01 00:00:01这个时间应该是可以的，建议先检查一下时区。至于不支持1970年以前时间的问题，我们也在研究解决，请关注后续版本。
