### ISSUE TITLE
[Bug]导出原始明细报错，看不到错误原因

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#9612]
**DataEase 版本**
v1.18.19

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Edge 最新版

**Bug 描述**
数据导出中心显示失败，但不知道原因
![image](https://github.com/dataease/dataease/assets/30886198/f8c718a6-8344-4da4-9bb4-04a236a6d71d)
/opt/dataease/logs/dataease/error.log 日志中的内容
![image](https://github.com/dataease/dataease/assets/30886198/53f399a4-6225-4674-9d4c-e3ad971e5e2d)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，下个版本修复。
