### ISSUE TITLE
[Bug]编辑数据集报错，无语了

### ISSUE THREAD

**Issue by hhw3KevinHou** [dataease/dataease#9616]
**DataEase 版本**
2.6.0

**运行方式(安装包运行 or 源码运行 ?)**

源码运行

**Bug 重现步骤(有截图更好)**
1.  编辑数据集，报错， 原因是啥，是原始数据数量超，还是计算结果数据超
2.
![image](https://github.com/dataease/dataease/assets/14155363/e3e8a123-6d8d-4241-befe-f5a5e007b77b)

**Comment by maninhill** [comment]
社区版单个数据集支持的最大记录数是 10 万条。
