### ISSUE TITLE
[Feature]希望可以自定义同/环比的周期

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#9617]
DataEase 版本:
v2.6.1

**请描述您的需求或者改进建议.**
希望达到的效果就是这里筛选的时间是5月1日到5月4日，点击查询后去对比4月1日到4月4日的数据
![image](https://github.com/dataease/dataease/assets/104493699/9fbb4de5-be04-4457-b05d-fe1853e7497f)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，目前暂时没有计划支持。
