### ISSUE TITLE
[Feature]外部参数可否直接关联sql数据集动态参数啊

### ISSUE THREAD

**Issue by 15206125206** [dataease/dataease#9619]
DataEase 版本:2.6

**请描述您的需求或者改进建议.**
很多数据是靠客户ID进行数据隔离的，表分区键也是客户ID，所以sql都会带上客户的ID参数，查询快而且不会看到别人的数据，希望通过外部链接直接传入客户的ID,目前外部参数关联图表的话，子查询无法使用参数，关联查询组件，查询组件又无法隐藏

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请问登录的用户和客户ID有关系吗？比如目前登录dataease的用户为a用户，a用户能够看哪个客户ID的数据？

**Comment by 15206125206** [comment]
客户不懂技术的，我们有自己的平台，报表是我们公司制作，想嵌入到我们系统里面得，仪表分享链接会带上客户的ID，但是现在无法关联到sql动态参数

**Comment by 15206125206** [comment]
一般仪表板直接嵌入自身系统得很常用，很多隐藏参数，比如登录信息等等，想直接通过公共链接传过去，sql通过动态参数能直接过滤掉大部分数据了，1.0虽然能实现，也只能通过盖住过滤组件实现，很麻烦，2.x好像直接没法实现了，请你们讨论下还好实现，确实很需要这个功能

**Comment by xuwei-fit2cloud** [comment]
我们计划支持隐藏式查询组件，还请等待后续版本的开发。

**Comment by xuwei-fit2cloud** [comment]
弹窗区已支持，外部传参对数据集参数的支持还需要在后续版本实现。
