### ISSUE TITLE
[Feature]你们前端使用了自动导入组件插件 但是还引入全部import 'element-plus-secondary/es/css' css变量

### ISSUE THREAD

**Issue by zcx992132258** [dataease/dataease#9624]
DataEase 版本:2.5
是因为你们import {} from 'element-plus'导致没有被识别到
可以使用import ElementPlus from 'unplugin-element-plus/vite'; 这个插件去避免重复引入的资源浪费

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈和建议，我们处理一下。
