### ISSUE TITLE
[Bug] v2 图表轴值显示bug

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#9625]
**DataEase 版本**
2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome

**Bug 描述**
轴值显示bug，下图中框出来的数值不应该是0.9吗，为什么是0.89999999999

**Bug 重现步骤(有截图更好)**
1.
<img width="1309" alt="image" src="https://github.com/dataease/dataease/assets/45967454/1334da3e-66aa-4a29-91d3-38afb287ac0c">

2.
3.

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为js精度丢失导致，目前我们没有找到可施行的解决方案，暂时无法处理，给你的使用带来不便非常抱歉；
![image](https://github.com/dataease/dataease/assets/84372766/40060d61-2184-4ba6-860c-f5b9197669ea)
