### ISSUE TITLE
[Feature] 富文本能否支持阈值设置？

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#9627]
DataEase 版本:
2.6.1

**请描述您的需求或者改进建议.**
富文本能否支持阈值设置，用来区别正增长 和 负增长，如图所示：
<img width="1473" alt="image" src="https://github.com/dataease/dataease/assets/45967454/81b99a50-d6ee-4377-855c-dc9913d19669">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已经规划在v2.7版本中
