### ISSUE TITLE
[Feature]添加视图模板

### ISSUE THREAD

**Issue by jstbw** [dataease/dataease#963]
目前有了仪表盘模板，希望添加视图模板。创建的视图另存为模板，只需要修改其中的数据源，但是不需要修改图表。

**Comment by yayanpei** [comment]
感谢您的反馈，我们先内部讨论一下。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
