### ISSUE TITLE
dataease V2.6

### ISSUE THREAD

**Issue by SuperManYo** [dataease/dataease#9630]
请问 如何在这里配置多数据源，可在代码中使用。
![Uploading 微信图片_20240514093845.png…]()

**Comment by SuperManYo** [comment]
![123](https://github.com/dataease/dataease/assets/167167620/20e52afc-3437-41dc-b829-cde1e374f430)

**Comment by maninhill** [comment]
没看明白你的问题，代码类问题请自行研究代码或者查看文档。
