### ISSUE TITLE
[Question]仪表板导出图片

### ISSUE THREAD

**Issue by c-dada** [dataease/dataease#9631]
请问v1.18版本的仪表版导出图片有后端接口的实现方式吗

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，仪表板预览页面的导出是前端导出的，相关的实现请参考相关代码。仪表板导出的后端接口，是x-pack功能定时报告所使用的接口，目前没有对外开放。

**Comment by c-dada** [comment]
> 感谢您的反馈，仪表板预览页面的导出是前端导出的，相关的实现请参考相关代码。仪表板导出的后端接口，是x-pack功能定时报告所使用的接口，目前没有对外开放。

#8402 这里我看回复已经支持了，是接口在x-pack里的吗

**Comment by yayanpei-fit2cloud** [comment]
是的，接口在x-pack里，仅企业版可以调用。
