### ISSUE TITLE
[Feature] V2 版本建议添加 Trino / Presto 数据源

### ISSUE THREAD

**Issue by liujie-yt** [dataease/dataease#9633]
DataEase 版本: V2

**请描述您的需求或者改进建议.**

V2 版本无法连接 Trino / Presto 希望能够添加该数据源，它们超好用的！而且也比较流行 [比心]
之前V1 有用，现在没了

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已经在需求池中，近期暂无计划进行中支持，待有更多同类需求后，再进行下一步的规划。
