### ISSUE TITLE
[Feature]视图的辅助线文字显示不全

### ISSUE THREAD

**Issue by huahua2023** [dataease/dataease#9635]
DataEase 版本:v.1.18.19

视图的辅助线的数值如果设定的接近100%就会显示不全，如图所示，新版和之前的版本都有同样问题

![微信图片_20240514105722](https://github.com/dataease/dataease/assets/122066560/896c3f77-6099-4476-a932-37955b38a244)

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，当超出了图表的展示空间时，是会出现展示不全的情况。目前暂无合适的方案进行优化，如果您有不错的建议，欢迎随时与我们沟通交流。
