### ISSUE TITLE
[Bug]升级企业版后，复制的仪表板缩小了一半

### ISSUE THREAD

**Issue by zhangtong9898** [dataease/dataease#9636]
**DataEase 版本**

v2.6.1 

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Google

**Bug 描述**
升级企业版后，复制的仪表板缩小了一半

**Bug 重现步骤(有截图更好)**
<img width="1021" alt="image" src="https://github.com/dataease/dataease/assets/133861755/f11d0127-2e8e-416b-80d0-dc07708e5cff">
![53811715655535_ pic](https://github.com/dataease/dataease/assets/133861755/92f17f1f-5de0-49c5-bfcc-340a1084406d)

<img width="1015" alt="image" src="https://github.com/dataease/dataease/assets/133861755/aacabb5b-d03c-4b1a-bae7-909461c1fc1e">
<img width="694" alt="image" src="https://github.com/dataease/dataease/assets/133861755/5f3779f4-b73a-492d-8440-a8ab0c67c105">

**Comment by BBchicken-9527** [comment]
感谢反馈，问题为已知问题，问题原因是复制历史数据导致，目前正在努力解决这个问题，问题将会在下个版本进行修复；
