### ISSUE TITLE
[Feature]期望象限图支持小数恒线

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#9637]
DataEase 版本:V2.6

**请描述您的需求或者改进建议.**
象限图当纵轴是小数（百分比）时，无法自动显示纵轴恒线，且无法手动调整为0.5，会自动变为1。
期望纵轴恒线能支持小数。
![image](https://github.com/dataease/dataease/assets/30886198/3fa8b960-5b4f-43cb-93f8-f6ef17837dca)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。
