### ISSUE TITLE
[Bug]V2 象限图的一些问题

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#9638]
**DataEase 版本**
2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

设置X恒线不设置Y恒线时显示异常
![image](https://github.com/dataease/dataease/assets/30886198/fe4830ac-19d5-4344-949e-e149fe9af0dd)

当使用计算字段作为纵轴时，纵轴显示异常：
![image](https://github.com/dataease/dataease/assets/30886198/a7023d45-4582-41d7-824a-ac61a8b7b11d)

**Comment by BBchicken-9527** [comment]
感谢反馈，计算字段确实存在问题，我们会在下个版本进行修复；
