### ISSUE TITLE
[Feature]图标类型建议添加世界地图

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#964]
**请描述您的需求或者改进建议.**
我在做”网站被攻击地点展示图“时发现大量国外的地点，DataEase只有全国地图，无法生成展示图，是否可以添加世界地图，可以先精确到国家名，后续慢慢补充其他国家的主要城市。同功能产品含有地图的都会有世界地图。望采纳。

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。

**Comment by pwjack** [comment]
世界地图大概什么计划呢？
