### ISSUE TITLE
[Bug]仪表板导出为图片，查询组件会丢失信息

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#9641]
**DataEase 版本**
2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
仪表板有查询组件时，导出为图片缺少文字信息

**Bug 重现步骤(有截图更好)**
1.
<img width="1387" alt="image" src="https://github.com/dataease/dataease/assets/109720729/1ff4c585-df1f-4021-a4a2-74008896bee7">

2.
![image](https://github.com/dataease/dataease/assets/109720729/8dd84f8f-5b8f-47b7-89ba-f77e00a6dc5f)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
