### ISSUE TITLE
快速计算同环比功能建议

### ISSUE THREAD

**Issue by sxjm** [dataease/dataease#9650]
DataEase 版本:v1.18.11

**请描述您的需求或者改进建议.**
希望当图表内未添加日期字段时，也能快速计算同环比，并且在添加快速计算同环比字段后，还能再添加放入原字段

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，和现在的实现方式不一样，我们需要讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，我们先记录进需求池中，近期暂时没有计划进行支持。
