### ISSUE TITLE
[Feature] 添加表格列

### ISSUE THREAD

**Issue by ITwuwei** [dataease/dataease#966]
**请描述您的需求或者改进建议.**
添加表格列时 在不断提交svae
能不能 先全部选择完在 有个预览的按钮

**Comment by yayanpei** [comment]
感谢您的反馈，目前的逻辑是实时保存的，我们需要内部讨论该需求。

**Comment by xuwei-fit2cloud** [comment]
我们觉得还是暂时保留现有设计比较合适。
