### ISSUE TITLE
[Bug]堆叠折线图显示存在大小不匹配问题 

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#9661]
**DataEase 版本**
 v 2.6

**Bug 描述**
![image](https://github.com/dataease/dataease/assets/40597893/294ddda0-69b9-428e-ae54-66de8dca0971)

配置了一个堆叠折线图，图形中发现图形并没有按照实际数据大小展示。
此处按照数据大小应该会有交叉的

**Comment by BBchicken-9527** [comment]
感谢反馈，请问你说的交叉是指不同颜色的折线会在你标记的位置产生重叠是吗

**Comment by lillcol** [comment]
> 感谢反馈，请问你说的交叉是指不同颜色的折线会在你标记的位置产生重叠是吗

是的，但是这种类型的图好像确实有好几种，有些会交叉，有些不会交叉。有不同的使用场景

**Comment by BBchicken-9527** [comment]
感谢反馈，堆叠类型的图表本身是不会产生交叠的，因为他的图表显示逻辑是根据之前的数据向上或者其他方向去累积的，你可以理解为这个图表示模拟积木的显示，每种颜色代表一块积木堆叠而出的就是显示的图表，如果希望产生堆叠可以尝试一下其他的图表；
