### ISSUE TITLE
[Feature]希望地图视图的指标项能支持拖入多条指标。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#9668]
DataEase 版本:
V2.6.0

**请描述您的需求或者改进建议.**
希望地图视图的指标项能支持拖入多条指标。
<img width="323" alt="7634f56bc03dacf077cdd8f74024472" src="https://github.com/dataease/dataease/assets/83771182/6326520d-9f48-45d0-b012-1ab0c95de3df">

**Comment by xuwei-fit2cloud** [comment]
在地图上拖入多个指标项，但显示上其实只能显示一个指标。多余的指标我们只能支持在标签或者提示中展示。或者提供指标切换的功能。这个我们再讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持地图中拖拽多个指标，v2.7版本会支持功能：提示中支持显示多个指标，建议您在提示中进行设置。
