### ISSUE TITLE
[Feature]希望支持修改数据源表名称

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#9670]
DataEase 版本:
v2.5

**数据源模块，上传excel表后，希望支持在线修改数据源表名称，同时在数据集也同步显示修改后的表名称，否则不方便识别.**
![image](https://github.com/dataease/dataease/assets/77324661/c6bdac28-1d3f-4ff9-bbbd-4287326388e4)
![image](https://github.com/dataease/dataease/assets/77324661/290b5e0a-a046-402c-96c6-bd2a0afb35a5)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，已经记录进需求池中。

**Comment by xuwei-fit2cloud** [comment]
暂不支持。
