### ISSUE TITLE
[Feature]希望仪表板支持导出视图明细数据

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#9671]
DataEase 版本:
v2.5

**希望在仪表板和大屏中，支持导出单个图表的明细数据，即原始数据。比如图表共有10个字段，但只拖拽使用了2个，希望导出excel文件时能够选择导出全部字段。.**

**Comment by xuwei-fit2cloud** [comment]
v1.18.19版本已支持，v2版本需要在数据导出中心完成后加上。
