### ISSUE TITLE
[Feature]明细表的分页，可以自定义输入跳转到多少页

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#9672]
DataEase 版本:
V2.6.0

**请描述您的需求或者改进建议.**
分页这里有个输入框，输入多少跳转到多少页。
![325a22ec522f6722c26950e112a5abe](https://github.com/dataease/dataease/assets/104493699/4284de07-2883-48b0-a9d7-6ac5c3daf5b0)
类似这种
![image](https://github.com/dataease/dataease/assets/104493699/5e2966dd-a0fc-41ff-ae2f-289328e25292)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，您的建议非常不错，已经加入近期的版本迭代中。
