### ISSUE TITLE
[Feature]可以在页面自定义添加导出的按钮

### ISSUE THREAD

**Issue by shimengqiao** [dataease/dataease#9673]
DataEase 版本:
v2.6

**请描述您的需求或者改进建议.**
这个导出也可以像查询按钮一样，再页面上自定义一个吗？功能就跟页面右上角的导出一样，这样更直观一些，这个功能使用频率还比较高。
![image](https://github.com/dataease/dataease/assets/104493699/5894bfd1-3732-41f0-a216-b18aa7da1bd5)

**Comment by xuwei-fit2cloud** [comment]
我们考虑像v1版本那样，增加一个隐藏式按钮，里面包含常用的导出、下载等功能。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈和支持，我们优化一下此处的交互。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
