### ISSUE TITLE
[Bug] v2.6.1 堆叠柱状图导出数据不全问题

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#9676]
**DataEase 版本**
v2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 最新

**Bug 描述**
使用堆叠柱状图时，在编辑界面直接打开查看数据界面，然后点击导出Excel
导出的Excel只有第一列有数据，另外两列数据丢失。测试过程中基础柱状图也偶现此现象，建议其他柱状图也一并测试。

![image](https://github.com/dataease/dataease/assets/30886198/bba10e98-9239-4a82-ba54-30a3d9c8f34a)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行处理；
