### ISSUE TITLE
[Bug] v2.6.1 指标卡查看数据详情页面导出报错

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#9677]
**DataEase 版本**
v2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
Edge 最新

**Bug 描述**
打开查看指标卡明细数据，点击导出Excel
打开导出的Excel发现数据是异常报错信息
![image](https://github.com/dataease/dataease/assets/30886198/79eb1c17-70da-4dc5-9269-28fb70163fce)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前测试环境没有发现你说的问题，不过发生了前面一个导出没有数据的问题，目前问题已经在解决中，受累看一下这个空指针的问题是否毕现，如果毕现方便说一下使用的数据源吗？

**Comment by BBchicken-9527** [comment]
感谢反馈，我这边已经验证出来了，我们将会在下个版本进行修复；
