### ISSUE TITLE
[Feature] v2 版本查询组件，默认选择即查询更好

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#9681]
DataEase 版本:
DataEase v2 版本

**请描述您的需求或者改进建议.**
查询组件，现在默认选择后需要点击查询按钮，希望可以默认选择完即查询

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，选择完即查询，如果在查询条件较多的情况下，每选择完一个查询条件，便会自动触发一次查询，可能这些查询都不是用户需要的。目前的设计是所有查询条件选择完毕后，如果需要由用户点击「查询」按钮，触发一次查询请求，会更加合适，因此暂时没有计划更改。
