### ISSUE TITLE
[Bug]数据源表结构变更，sql 数据集无法获得变更字段信息

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#9682]
**DataEase 版本**
 v2.6

**Bug 描述**
已经通过 sql 配置了了一个数据集，当对应的数据源表变更，比如增加了一个字段，现有的 sql数据集获取不到新增的字段

**Bug 重现步骤(有截图更好)**
1. 我有一张 pg 的表，已经通过 sql 配置了数据集，配置了报表
![WeChatWorkScreenshot_d54d3c5b-6957-4a79-9048-17849e095af0](https://github.com/dataease/dataease/assets/40597893/5f00fbd4-44f9-4bb9-a337-3f427bb0654b)
2. 业务的 pg 表增加了一个字段 conmmands ，现在要将新增的字段加入之前的数据集中，发现在配置数据集的时候，运行的时候可以拿到conmmands字段，也可以保存
![WeChatWorkScreenshot_8b3269c9-625d-45c0-955d-ac99e3206f41](https://github.com/dataease/dataease/assets/40597893/fd1add40-9203-471f-835c-1fe011113913)

测试过如果直接拖表是可以的，sql 数据集不行

**Comment by BBchicken-9527** [comment]
感谢反馈，由于之前的字段已经固定需要对字段重新进行添加，点击图表位置即可，这里确实会对用户使用造成一些困扰，我这边和产品进行反馈，看看后续版本是否可以优化一下；
![image](https://github.com/dataease/dataease/assets/84372766/3ebc0da4-ca12-44d0-8422-417af721e8e8)

**Comment by BBchicken-9527** [comment]
感谢反馈，假如你写的是select * 在de中存储的sql没有变化导致无法作出相应的变化，所以这里暂时无法进行优化，我这边暂时先关闭这个问题，后期如果有什么好的优化方案会再进行处理的；

**Comment by lillcol** [comment]
好的 感谢

**Comment by lillcol** [comment]
> 感谢反馈，由于之前的字段已经固定需要对字段重新进行添加，点击图表位置即可，这里确实会对用户使用造成一些困扰，我这边和产品进行反馈，看看后续版本是否可以优化一下； ![image](https://private-user-images.githubusercontent.com/84372766/331856007-3ebc0da4-ca12-44d0-8422-417af721e8e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDg2ODUsIm5iZiI6MTcxNjM0ODM4NSwicGF0aCI6Ii84NDM3Mjc2Ni8zMzE4NTYwMDctM2ViYzBkYTQtY2ExMi00NGQwLTg0MjItNDE3YWY3MjFlOGU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAzMjYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMTFhNjkwMjc5YTYwMDA0NGUzMzNkNjM5MDk4MDYwMjEzMjc0Mjg5OWRkYjhlYjZlNTllZWY4YzI2NWE5ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gp3AFm7LTHJRHLUAvj2Vgnkvu_WmKpO5d-SmBwQ-81g)

好的 感谢，确实没注意可以选择字段
