### ISSUE TITLE
[Bug] 筛选器点开后在有背景挡住的情况下无法自动回弹

### ISSUE THREAD

**Issue by pilot6** [dataease/dataease#9689]
**DataEase 版本**
   v1 版都存在这个问题

**Bug 描述**
    筛选器选择之后如果有矩形的背景或者其他图表的时候不会自动回弹，需要点击一次旁边的空白的地方才会回弹。点击一次空白的地方之后可以回弹，也有概率会再次无法回弹，这种情况需要再点一次空白的地方。（如下图，筛选器首次下拉之后点击红框位置不会回弹，需要点击一次红框以外的地方）

**Bug 重现步骤(有截图更好)**
![99ed4c5cfeb0e5ecade288efac54199](https://github.com/dataease/dataease/assets/7956071/c655bb68-dff0-473b-ae84-100a5093ad4d)

**Comment by pilot6** [comment]
补充：只有查看页面或者说预览页面有这样的问题，仪表盘编辑页面正常的。

**Comment by BBchicken-9527** [comment]
感谢反馈，我们优化一下；

**Comment by pilot6** [comment]
请问 v1.18.20 没有修复这个问题吗，计划什么时候优化啊

**Comment by pilot6** [comment]
请问有没什么好的办法解决

**Comment by maninhill** [comment]
v1 版本目前进入维护阶段，仅修复安全漏洞相关问题。
