### ISSUE TITLE
[Bug]MySQL数据源，时间过滤组件选择2024-05-14到2024-05-16，后台自动转成了BETWEEN '2024-05-13 23:59:59' AND '2024-05-16 23:59:59'

### ISSUE THREAD

**Issue by ZhaoQian1222** [dataease/dataease#9693]
**DataEase 版本**
1.18.19

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**Bug 描述**
MySQL数据源，时间过滤组件选择2024-05-14到2024-05-16，后台日志中显示sql自动转成了 BETWEEN '2024-05-13 23:59:59' AND '2024-05-16 23:59:59'
阿里云的ADB数据库执行时，会导致实际查询的结果与预期不符，应当改为 BETWEEN '2024-05-14 00:00:00' AND '2024-05-16 23:59:59'

![image](https://github.com/dataease/dataease/assets/89771514/616ae707-6114-4c2b-a49b-1747e0bbc2e3)

<img width="1178" alt="image" src="https://github.com/dataease/dataease/assets/89771514/c420c6a4-8f25-4bb4-b7a5-a699a0b709b4">

**Comment by xuwei-fit2cloud** [comment]
已处理。
