### ISSUE TITLE
dataease 源码第二次启动BUG

### ISSUE THREAD

**Issue by SuperManYo** [dataease/dataease#9698]
**DataEase 版本**
V2.6

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Microsoft Edge
124.0.2478.105
**Bug 描述**
dataease 源码启动，第一次初始化正常，关闭重新启动后 sql 创建报错。

**Bug 重现步骤(有截图更好)**
![111](https://github.com/dataease/dataease/assets/167167620/bca20704-3494-4e24-9719-f2d8949f196e)

**Comment by SuperManYo** [comment]
版本是2.6.1

**Comment by xuwei-fit2cloud** [comment]
第一次初始化正常的话，第二次应该不会执行这个flyway，是否有修改数据库相关。

**Comment by yaokai-oos** [comment]
我也遇到了这个问题
