### ISSUE TITLE
支持监控告警功能 V2.8[Feature]

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#9699]
DataEase 版本: V2.8

期望能支持告警通知功能，在我们不关注报表的时候，期望能有指标监控功能 自动监控着 指标变化情况。 及时告警出来.

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，现阶段的功能规划是围绕数据可视化的，因此监控告警功能暂不支持。
