### ISSUE TITLE
[Bug]新增字段（小数）进行减法运算结果不正确

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#970]
**DataEase 版本**
v1.3.0

**浏览器版本**
Chrome 94

**Bug 描述**
新增一个小数字段，设置为两个小数字段相减而得，其中有个字段减出来结果不正确。

**Bug 重现步骤(有截图更好)**
1.设置一个新的字段，为两个字段相减所得
![image](https://user-images.githubusercontent.com/48945409/137662727-4e0d1328-e70a-40eb-a36f-599ad2611a3b.png)

2.查看新增的字段
![image](https://user-images.githubusercontent.com/48945409/137662791-774d1bcb-ae1f-44f5-9cb1-7f9f0e69498b.png)

3.查看预览数据，有一个数据明显小数位数变多，结果不正确。
![image](https://user-images.githubusercontent.com/48945409/137662921-f4093f43-7aa6-40a6-822f-6a6e63220d00.png)

**Comment by xuwei-fit2cloud** [comment]
这个是由于doris导致的问题，暂时还无法修复。
