### ISSUE TITLE
[Feature]下钻的字段提供排序功能

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#9700]
DataEase 版本:
2.6

**请描述您的需求或者改进建议.**
当我配置了一个dt,hour的下钻配置后，在维度中可以配置 dt 排序
![image](https://github.com/dataease/dataease/assets/40597893/892ff635-06a8-40d5-81f0-b1033368e2aa)
我能查询 dt 级别的报表
![image](https://github.com/dataease/dataease/assets/40597893/441b5dfb-6bb1-4223-af9a-1a81089718e3)
但是当我下钻到 hour 的时候，没法对 hour 排序，这样无法查看 hour 的趋势变化
![image](https://github.com/dataease/dataease/assets/40597893/14649b0c-6474-4a25-987b-dd25634e2fae)

目前看下钻字段的排序和上一级的维度列保持一致，这块希望能提供单独的排序选项

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中支持一下。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
