### ISSUE TITLE
[Feature]对于同一指标列，希望能实现同时获取不同的的聚合逻辑

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#9701]
DataEase 版本:
 2.6

**请描述您的需求或者改进建议.**
对于一个指标列，我可能同时需要不同的聚合计算逻辑，比如count(a ), count(distinct a )，但是目前不支持在指标列中添加同一字段进行聚合计算

**Comment by yayanpei-fit2cloud** [comment]
感觉您的反馈，我们需要讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂不考虑支持拖拽相同的字段，建议您通过复制字段，为每个字段设置不同的聚合逻辑来满足使用。
