### ISSUE TITLE
[Bug] v1.18.19 版本 echart 明细表无法导出 excel

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#9702]
**DataEase 版本**
 v1.18.19 版本

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌

**Bug 描述**
 v1.18.19 中新建 echart 明细表导出 Excel 和导出原始明细没反应，新建 antv 所有表格导出原始明细失败

**Bug 重现步骤(有截图更好)**
1. Excel数据集
![image](https://github.com/dataease/dataease/assets/163749505/7bee8e35-e1d0-4050-9d45-d1d3f061cddc)
![image](https://github.com/dataease/dataease/assets/163749505/d8851091-a784-4e38-85be-45af1d3c5076)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们下个版本进行修复；
