### ISSUE TITLE
[Bug]导出报表操作，计算报表文件大小的问题

### ISSUE THREAD

**Issue by Dktioned** [dataease/dataease#9707]
**DataEase 版本**
tag V11819

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**

**Bug 描述**
导出报表操作，在计算报表文件大小的时候，代码中报表文件的路径重复拼接，导致找不到报表文件，因此计算的文件大小都是0

**Bug 重现步骤(有截图更好)**
1.
![微信图片_20240517161218](https://github.com/dataease/dataease/assets/33315538/f101104d-82f0-41b4-81c4-c8a77fde610e)

2.
3.

**Comment by xuwei-fit2cloud** [comment]
dev分支代码已修复：
https://github.com/dataease/dataease/commit/8af7659bcec8bd887ce01d64d23336d9b8aa6c98
