### ISSUE TITLE
[Bug]v2透视表  小计没反应and多指标时出现图表变白

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#9711]
https://github.com/dataease/dataease/assets/141667200/f547d1f4-c382-4ce6-8906-02b5fe1421ea

（这个变白应该不是所有数据集必现，需要数据集可以找我）

**Comment by BBchicken-9527** [comment]
感谢反馈，目前问题1已经修复，因为为之前行列小计的位置弄反了，我们修复一下问题2
