### ISSUE TITLE
[Feature] v2 增加 仪表板/大屏 的全屏预览功能

### ISSUE THREAD

**Issue by huskiesir** [dataease/dataease#9712]
DataEase 版本:
2.6.1

**请描述您的需求或者改进建议.**
v1可以做到全屏预览啊，v2没有全屏预览功能，导致大屏展示会显示浏览器功能区。
<img width="1955" alt="image" src="https://github.com/dataease/dataease/assets/45967454/b8a47e9e-a307-43d7-971a-006d6d1ab17d">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，将浏览按照下图所示进行配置，便可以隐藏浏览器的工具栏和标签栏。

<img width="1007" alt="image" src="https://github.com/dataease/dataease/assets/84168063/415238ec-ce63-4eba-9e4f-cb9b155a6bcb">
