### ISSUE TITLE
[Feature] 词云组件中，希望增加字体大小调整功能，优化显示效果

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#9722]
DataEase 版本:
2.6

**请描述您的需求或者改进建议.**
词云组件中，内容部分占整个组件的很小一部分，显示效果不太理想
希望真是整体字体调整或自适应功能，是内容尽可能和组件匹配，显示效果更好
![image](https://github.com/dataease/dataease/assets/40597893/2cd12885-741c-491b-9b7d-4b1c05b279ce)

**Comment by xuwei-fit2cloud** [comment]
这个可以通过调整字号区间以及文字间隔来达到充满容器的目的。我们已将自适应的需求记录下来，后期会安排开发。
