### ISSUE TITLE
[Feature]v1 视图如果很靠上，展示的值用被上面挡住，虽然将图例放在上面可以暂时解决，但是有时候不需要展示图例，就没办法了。

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#9725]
<img width="420" alt="54faea37297b7259bedaef880182fe9" src="https://github.com/dataease/dataease/assets/141667200/8ae82d8d-0714-480b-8ee2-a07ad3403ad0">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，这里是因为标签超出了图表的展示空间，所以展示不全，目前没有合适的解决方法。建议您调整标签的位置为下，或者自定义纵轴的轴值。
