### ISSUE TITLE
图表展示的屏幕自适应[Feature]

### ISSUE THREAD

**Issue by 18927580527** [dataease/dataease#9726]
DataEase 版本: V2.8

**请描述您的需求或者改进建议.**
目前配置报表后，在不同的终端展示不能自适应。 比如我在台式机上调整好的样式。  在笔记本，平板上面没办法看。 
报表数据都挤在一起了。 特别难看。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，请问用的是仪表板还是数据大屏？

**Comment by 18927580527** [comment]
主要是仪表板为主

**Comment by yayanpei-fit2cloud** [comment]
仪表板是自适应模式的，理论上应该不会出现您描述的情况，方便的话您把图片发出来，我们看一下。

**Comment by lillcol** [comment]
这个情况确实遇到过，我这边笔记本配置好，在扩展显示器上也能正常显示，但是，其他人的笔记本打开就是挤在一起了

**Comment by mmmlong** [comment]
这个问题我也遇到了，笔记本上配置的是显示好的，其他人打开，全部挤在一起了

**Comment by 18927580527** [comment]
<img width="412" alt="企业微信截图_17162136322270" src="https://github.com/dataease/dataease/assets/30259184/f85c8032-9272-4c8e-a212-2feef9a25802">

**Comment by mmmlong** [comment]
<img width="1304" alt="image" src="https://github.com/dataease/dataease/assets/30709129/54e5d15b-b87e-42f3-baee-77a9e54b680e">

**Comment by 18927580527** [comment]
@xuwei-fit2cloud @yayanpei-fit2cloud

**Comment by xuwei-fit2cloud** [comment]
我们处理一下。

**Comment by lyons-hz** [comment]
我这边也有遇到过，仪表板编辑界面看着是ok的，预览的时候展示不全
<img width="915" alt="image" src="https://github.com/dataease/dataease/assets/89773363/70461d60-685a-445c-8c0f-21952f092614">

<img width="798" alt="image" src="https://github.com/dataease/dataease/assets/89773363/4211e40b-438b-4513-a565-456e5d167741">

**Comment by 18927580527** [comment]
这是一个特别普遍而且影响很大的问题。 估计绝大部分人都遇到了。  在移动端其实也有类似问题。

**Comment by ziyujiahao** [comment]
应该是缩放模式导致的，2.8以后版本已经对缩放模式进行了优化，会去宽度和高度缩放较小的值，再不同尺寸和宽高比例的设备上会有很大改观

**Comment by 18927580527** [comment]
v2.8并没有什么改变哈。

**Comment by yayanpei-fit2cloud** [comment]
已经在v2.9版本处理，请等待新版本发布。
