### ISSUE TITLE
[Bug]明细表和汇总表下钻后异常

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#9727]
**DataEase 版本**
v1.18.19 版本

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌

**Bug 描述**
1.点击明细表的的字段下钻，字段消失
2.点击汇总表的的字段下钻，字段列宽被压缩右移

**Bug 重现步骤(有截图更好)**
上图明细表消失，下图汇总表压缩

![未命名](https://github.com/dataease/dataease/assets/127368807/cebc4c1f-a650-456d-93d4-dd352494aff6)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
