### ISSUE TITLE
不手动删除搜索关键字，无法再次搜索默认模板

### ISSUE THREAD

**Issue by github-tsg** [dataease/dataease#9730]
DataEase 版本:
V2使用模板新建，不手动删除搜索关键字，无法再次搜索默认模板
![image](https://github.com/dataease/dataease/assets/146046004/b4c0a2e4-b45c-49ba-b172-4e931ef7cc3a)
删了以后才可以
![image](https://github.com/dataease/dataease/assets/146046004/ff817d37-b615-4ad2-b0f3-766acae25abc)

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，关键字不清空的情况下，默认是会根据关键字搜索的，可按照下图所示清掉关键字。
<img width="1281" alt="image" src="https://github.com/dataease/dataease/assets/84168063/4d90614e-6b87-4f8d-896b-21ea77bae6af">
