### ISSUE TITLE
[Feature]透视表的列总计栏的某个字段可以隐藏

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#9732]
DataEase 版本:
V2

**请描述您的需求或者改进建议.**
<img width="1157" alt="image" src="https://github.com/dataease/dataease/assets/101089844/6b3fe11c-a7ab-4a41-90af-1da94fa372d3">
<img width="400" alt="image" src="https://github.com/dataease/dataease/assets/101089844/2d68e880-7b75-405f-9645-0578d5dcc1ed">
<img width="426" alt="image" src="https://github.com/dataease/dataease/assets/101089844/4831841f-cb54-4a3f-a4ed-6d92fae08586">

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先对需求进行记录，目前暂时没有计划进行支持。
