### ISSUE TITLE
[Bug] v2 版本脱敏后字段显示效果不规范

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#9736]
**DataEase 版本**
v2 版本

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
谷歌

**Bug 描述**
在富文本中拖入某字段后，再设置该字段脱敏，富文本并不显示 * ；
在明细表中拖入某字段后，再设置该字段脱敏，则会显示 * ；
以及其他视图脱敏后显示效果不统一，应该统一显示成对应脱敏规则。

**Bug 重现步骤(有截图更好)**
1. 在富文本中拖入某字段后，并刷新数据，正常显示
2. 再数据集设置该字段脱敏，富文本显示 获取中
3. 明细表以及其他视图各不一样的显示效果
![image](https://github.com/dataease/dataease/assets/163749505/e41f8ac6-de65-4a1a-997a-146e7e69a299)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下，保持统一。
