### ISSUE TITLE
[Bug]Excel 上传的数据个别小数有时精度会异常

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#974]
**DataEase 版本**
v1.3.0

**浏览器版本**
Chrome 94

**Bug 描述**
使用 Excel 上传数据，在上传不同数据的几次使用过程中，时常存在某个别小数精度变化。

**Bug 重现步骤(有截图更好)**
1.上传数据，数据内容如下
![image](https://user-images.githubusercontent.com/48945409/137689929-b4cfdb7f-3716-44af-96dd-0bb3e9cbdd4d.png)

2.预览数据中一个小数精度不正常
![image](https://user-images.githubusercontent.com/48945409/137690011-2a3eee06-cc1f-46cd-b98c-f80506cf1027.png)

3.确认该数据在 Excel 中的精度及格式
![image](https://user-images.githubusercontent.com/48945409/137690235-5fac3b1b-7581-4247-91d6-cd1613a47650.png)

4.再次编辑 Excel 重新更新数据，重试试验
![image](https://user-images.githubusercontent.com/48945409/137690342-640b9c1e-690a-42b5-b256-d3abb119b026.png)

5.结果仍然和之前一样
![image](https://user-images.githubusercontent.com/48945409/137690407-61d86834-2bb5-4a9c-bfb5-6844ec42f6aa.png)
![image](https://user-images.githubusercontent.com/48945409/137690433-4ff7ca9d-47fc-4198-bff7-30de6b4726ce.png)

**Comment by xuwei-fit2cloud** [comment]
这是doris的一个bug，我们暂时无法修复。
