### ISSUE TITLE
[Bug]V2 版本使用导入的模板创建仪表盘，界面布局异常

### ISSUE THREAD

**Issue by HuangMingFrancis** [dataease/dataease#9743]
**DataEase 版本**
v2

**运行方式(安装包运行 or 源码运行 ?)**
使用的官方的demo

**浏览器版本**
Microsoft Edge
版本 124.0.2478.105 (正式版本) (64 位)

**Bug 描述**
使用导入的模板创建仪表盘，界面布局异常。

**Bug 重现步骤(有截图更好)**
1. 导入模板
![微信截图_20240521085325](https://github.com/dataease/dataease/assets/18553234/576b9016-eecc-4f98-9096-2c6488222af2)

2. 使用模板新建仪表盘
![微信截图_20240521085412](https://github.com/dataease/dataease/assets/18553234/e3a669a3-3c56-491c-bf47-6de0b9d16de4)

**Comment by BBchicken-9527** [comment]
感谢反馈，请问是否是只有自定义模版这样。官方模版是否存在此类问题呢？

**Comment by mmmlong** [comment]
我也发现这个问题了， 自定义的模版是这样，官方的模版没发现

**Comment by BBchicken-9527** [comment]
> 我也发现这个问题了， 自定义的模版是这样，官方的模版没发现

嗯嗯 ，应该是历史数据导致的，如果自定义模版数量不多建议重新创建一下应该就可以了，我们也会在下个版本进行修复，如果不多的话可以你先手动临时处理一下；

**Comment by elvaysy** [comment]
请问是哪个commit呢？想合一下

**Comment by xuwei-fit2cloud** [comment]
https://github.com/dataease/dataease/commit/6ff602bb
