### ISSUE TITLE
[Bug]通过api数据源拿过来的业务数据错乱

### ISSUE THREAD

**Issue by lizheng-steedos** [dataease/dataease#9744]
**DataEase 版本**
2.6.2

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
chrome 版本 124.0.6367.208（正式版本） (arm64)

**Bug 描述**
通过api数据源拿过来的业务数据错乱
<img width="1693" alt="image" src="https://github.com/dataease/dataease/assets/151509384/6041b3eb-fd08-453a-8928-db3ac6ba1db4">

**Bug 重现步骤(有截图更好)**
1.api接口返回的数据
<img width="1920" alt="image" src="https://github.com/dataease/dataease/assets/151509384/46f47ded-36f6-42ad-af1b-9b995376f071">
<img width="1920" alt="image" src="https://github.com/dataease/dataease/assets/151509384/c3ab239e-aabd-4cf5-bcd9-2a96b44be3da">
2.预览的数据和接口原始数据相比就乱了
<img width="1920" alt="image" src="https://github.com/dataease/dataease/assets/151509384/d5698398-b7a8-434a-8f49-0453a7f3caca">

**Comment by BBchicken-9527** [comment]
感谢反馈，目前API数据源无法处理字段数量不一致的接口，这是因为我们没有办法确定你给出的接口具体事有多少个字段，当字段内容缺失会导致统计的时候后面的数据往前移导致数据出现错乱；
