### ISSUE TITLE
[Feature]鼠标移动到表格上时，提示色可以根据仪表板主题改变而改变

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#9748]
DataEase 版本:
v1&v2 

**请描述您的需求或者改进建议.**
鼠标移上去的这个颜色应该也随主题的改变而改变
1、浅色主题下，鼠标移上去是浅色的这样。表格里的字都能看出来
![image](https://github.com/dataease/dataease/assets/101089844/218cb589-38df-424d-aa27-c6c244ddc370)
2、但是深色主题下鼠标移上去以后。它的背景也是浅色的。那表格里的字都是浅色的话，这样这个字就显现不出来了，是不是深色的主题下鼠标移上去，这个颜色应该也变成深色
![image](https://github.com/dataease/dataease/assets/101089844/19a0c9b1-81a9-45ae-bdf0-20f220238c97)

**Comment by xuwei-fit2cloud** [comment]
暂时不予支持。
