### ISSUE TITLE
[Feature]希望仪表板增加日期时间显示控件

### ISSUE THREAD

**Issue by weishuo6** [dataease/dataease#9749]
DataEase 版本:

V2.6.1

**请描述您的需求或者改进建议.**
目前数据大屏已经支持日期时间显示控件，希望仪表板尽快能支持
![image](https://github.com/dataease/dataease/assets/35896106/63607df3-2ee2-46dd-8ca6-1fba02d53aa2)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，这是大屏特有的组件，目前暂时没有计划在仪表板中增加。
