### ISSUE TITLE
[Bug]更新Excel数据集数据提示错误

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#975]
**DataEase 版本**
1.3

**浏览器版本**
Google Chrome 94.0.4606.61（正式版本） (arm64)

**Bug 描述**
1、DE版本从1.0-1.3，一直使用到现在
2、更新已有Excel数据
3、更新数据后提示timeout
**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/60059766/137842998-11dc5a84-c519-48c4-91e9-9eaef20ce293.png)

**Comment by xuwei-fit2cloud** [comment]
这应该是网络问题
