### ISSUE TITLE
[Feature]v2 增加可识别移动端功能

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#9751]
DataEase 版本:
v2 

**请描述您的需求或者改进建议.**
增加可识别移动端功能
![image](https://github.com/dataease/dataease/assets/101089844/62c24853-82a5-4b36-9e17-9513a7bd0398)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前是系统自动识别移动端的，如果仪表板开启了移动端，那么在移动端打开仪表板时，使用移动端的样式，目前暂时没有计划修改。
