### ISSUE TITLE
[Feature]支持动态指标图

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#9753]
DataEase 版本:
v1&v2

**请描述您的需求或者改进建议.**
调价格，其它的值也跟着变化
https://www.163.com/dy/article/I5DS64EU0516BGRH.html
![image](https://github.com/dataease/dataease/assets/101089844/cd21a685-8b9a-42ab-a5b7-08707f32038e)

**Comment by xuwei-fit2cloud** [comment]
暂时没有相关计划。
