### ISSUE TITLE
[Feature]时间筛选框基于相对时间范围的基础上，增加单次查询天数的限制

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#9756]
DataEase 版本:
2.6

**请描述您的需求或者改进建议.**
时间筛选框基于相对时间范围的基础上，增加单次查询天数的限制
目前筛选部分可以基于日期的相对时间控制查询范围，但是可能会涉及很大的数据量
避免 sql 执行时间过长，希望添加一个范围大小限制，
比如我限制的相对时间是最近一个月，但是我最多能查询 7 天的数据，那我在仪表板的筛选的日期范围天数必须小于等于 7
如 【1～7】【2～8】之类，即在相对时间范围内实现一个查询范围起止的限制，并且这个条件是必须满足的
<img width="645" alt="image" src="https://github.com/dataease/dataease/assets/40597893/725d5708-62d4-42b7-bbd2-b00ad9642b81">

**Comment by yayanpei-fit2cloud** [comment]
该需求已经实现，请参考下图所示进行配置
![image](https://github.com/dataease/dataease/assets/84168063/d90f23f7-eb22-43cf-921d-56b7ef05a605)

**Comment by lillcol** [comment]
> 该需求已经实现，请参考下图所示进行配置 ![image](https://private-user-images.githubusercontent.com/84168063/333002216-d90f23f7-eb22-43cf-921d-56b7ef05a605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NDkxNjYsIm5iZiI6MTcxNjQ0ODg2NiwicGF0aCI6Ii84NDE2ODA2My8zMzMwMDIyMTYtZDkwZjIzZjctZWIyMi00M2NmLTkyMWQtNTZiN2VmMDVhNjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA3MjEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0NzQwMDAzMWZiMDg3NTVjMGVjOTk5NGRhNGI4NDAwYzRjNTYzYjc2Y2VjNWI0NTZlMDRhMjU1ZGMwZGI3ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tXyNnEi9NgcVFCMtVscyAA4XvDLzeMYhGmvJBQ-1CLI)

好的，刚看完 2.5 没注意 2.6 版本
