### ISSUE TITLE
建议新增图表组件添加使用说明部分

### ISSUE THREAD

**Issue by github-tsg** [dataease/dataease#9764]
<img width="955" alt="象限图" src="https://github.com/dataease/dataease/assets/146046004/e87fd5e3-b35d-4a7b-8f0a-03ec74854dc7">

**Comment by github-tsg** [comment]
DataEase 版本:
V2.6
**请描述您的需求或者改进建议.**
版本更新新增的功能，比如图表组件，建议增加一项图表组件使用说明的部分。在线文档不会及时更新出具体的操作方法；发布说明会上讲师也只是简单操作。对应用户来说，是希望快速上手，实现新增图表的数据展示。若能举个例子，比如附加一个Excel数据源表结构（是怎样的），配置区的维度指标大概是什么字段，这样体验感会非常好，谢谢。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈和支持，所有图表的制作方式基本一致，将所需要的数据集字段拖拽至图表的配置区，点击「更新图表数据」便可以展示出来，如果使用上有不太清楚的，可以在用户群中进行沟通交流。交流群二维码如下图所示：
![image](https://github.com/dataease/dataease/assets/84168063/104b9182-432f-4c34-811e-99fa1e5b0460)
