### ISSUE TITLE
[Feature]期望指标卡支持联动/跳转

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#9765]
DataEase 版本:
 V2

**请描述您的需求或者改进建议.**
希望仪表板中展示多个指标卡，分别展示不同状态或类型的订单数量。
希望能通过点击不同的指标卡查看对应过滤条件的数据。

![image](https://github.com/dataease/dataease/assets/30886198/67ebde6e-a09a-4ff8-9aa4-6738e45285ab)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，指标卡目前暂无计划支持联动、跳转事件。
