### ISSUE TITLE
[Bug] v2.6.1 版本多选图层方向键失效

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#9766]
**DataEase 版本**
v2.6.1 版本

**运行方式(安装包运行 or 源码运行 ?)**
安装包安装

**浏览器版本**
谷歌浏览器

**Bug 描述**
数据大屏中多选图层移动，使用键盘方向键失效，只移动最外层框，
保存返回后会图层+1

**Bug 重现步骤(有截图更好)**

![chrome_d8YIVLYdpn](https://github.com/dataease/dataease/assets/163749505/8d18d390-d00e-4ac5-9213-193a1fe039ee)
![image](https://github.com/dataease/dataease/assets/163749505/41154d18-86cd-4c77-8216-c3e36f23149f)

**Comment by xuwei-fit2cloud** [comment]
已处理，请等待新版本发布。
