### ISSUE TITLE
[Feature]数据集的列宽可以进行拖动

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#9769]
DataEase 版本:

v2.6.1

**请描述您的需求或者改进建议.**
v1 数据集是可以进来拖动列宽的，v2 还不支持但有时候数据集的字段显示不全，希望v2数据集后续可以支持列宽的拖动
v2 显示不全的情况
![37531716356417_ pic](https://github.com/dataease/dataease/assets/127368807/6898de5a-7a8e-4662-8e1e-6e99f9994121)
v1 可以拖动
![未命名](https://github.com/dataease/dataease/assets/127368807/50f408c4-b24a-4145-9163-a958494e2e30)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们在近期的版本中增加该优化。

**Comment by yayanpei-fit2cloud** [comment]
需求已记录，目前使用的组件不支持调整列宽，可能需要更换组件，因此近期暂时保持现状，如果需要查看完整内容，可以鼠标悬浮上去，会有提示。
