### ISSUE TITLE
图表字体太模糊了

### ISSUE THREAD

**Issue by HotMancheA** [dataease/dataease#977]
![image](https://user-images.githubusercontent.com/45034584/137865991-a0db3b4d-cbfb-4d83-a75a-84326c137ed1.png)

**Comment by yayanpei** [comment]
感谢您的反馈，pdf导出后是图片，放大可能会有些模糊；系统中放大视图并非图片，应该不会出现模糊，建议您调整一下标题的字体颜色（比如黑色）后，再对比一下。
