### ISSUE TITLE
[Bug]oracle数据集计算字段报错

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#9773]
**DataEase 版本**
v2

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**Bug 描述**
新建数据集计算字段报错

**Bug 重现步骤(有截图更好)**
1.复制一个字段新的计算字段
![image](https://github.com/dataease/dataease/assets/101089844/db7aa2bd-b75a-414c-9a80-f0ed2e7f3caa)

2.
![image](https://github.com/dataease/dataease/assets/101089844/e2b53ce7-520d-441d-80f4-abedd9ed2bf2)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
