### ISSUE TITLE
[Bug]透视表“数据列/维度”按照时间属性排序错误

### ISSUE THREAD

**Issue by cuckooM** [dataease/dataease#9776]
**v2.6.1**

**安装包运行**

**Chrome 124.0.6367.209**

**透视表“数据列/维度”按照时间属性排序错误**

**Bug 重现步骤(有截图更好)**
1. 创建一个透视表，“数据列/维度”设置一个时间属性。可以是数据库查询 timestamp 属性，也可以是手动增加的“时间”类型属性。
2. 设置“数据列/维度”按照这个时间属性排序。
![image](https://github.com/dataease/dataease/assets/19563707/c970c4ea-e163-4c61-9ac2-4fcea595037f)

3. 查看透视表，横向滚动条拉到最后，可以看到时间顺序排序错误，无规则。
![image](https://github.com/dataease/dataease/assets/19563707/5ad9c4ae-b7d0-4fad-8f9d-8315a11a1b10)

**Comment by cuckooM** [comment]
好像是自动把无数据的列放在最后了，这是怎么回事呢？

**Comment by BBchicken-9527** [comment]
感谢反馈，目前透视表字段排序只支持单一字段进行排序，数据行/维度优先级高于数据列的，所以工时没有生效，是因为你已经设置了产品名称的排序；

**Comment by cuckooM** [comment]
> 感谢反馈，目前透视表字段排序只支持单一字段进行排序，数据行/维度优先级高于数据列的，所以工时没有生效，是因为你已经设置了产品名称的排序；

删除“数据行/维度”排序后确实正常了。
我有疑问，我设置的“数据行/维度”，是对数据在行层面进行排序，为什么会影响数据列的排序？感觉应该可以同时支持的呀。
