### ISSUE TITLE
数据集字段批量管理页面显示问题

### ISSUE THREAD

**Issue by github-tsg** [dataease/dataease#9787]
DataEase 版本:V2.6
环境：Win10
浏览器：Edge
**请描述您的需求或者改进建议.**
数据集字段批量管理页面，默认需要向上拖动才可以浏览全维度和指标字段，但仍会显示不全如“字段类型……”的列选项
![image](https://github.com/dataease/dataease/assets/146046004/e9753063-6c03-4081-baa2-fc346d420082)
缩小浏览器视图，维度和指标字段则会有空隙（数据不多的话），且此时若改为正常显示比例（100%），也需刷新一下才会恢复空隙间的间距。
![image](https://github.com/dataease/dataease/assets/146046004/391e49d8-70a8-4079-a219-1aa517cbf0e8)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前项目没有做浏览器的兼容适配，建议您使用谷歌浏览器。
