### ISSUE TITLE
[Feature]v2 的预览页链接支持进行登陆后打开

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#9796]
DataEase 版本:
v2.6.1

**请描述您的需求或者改进建议.**
v1 打开预览页（或者新tab页预览）会有一个链接带着仪表板ID的，分享这个链接给其他人，打开会先让用户进行登陆，登陆后可查看仪表板。
打开提示登录
![image](https://github.com/dataease/dataease/assets/127368807/6d5262f9-0005-42cf-8c42-f260792f44dc)
登陆后可查看这个preview页面
![image](https://github.com/dataease/dataease/assets/127368807/c404d917-4d83-44cd-98e1-34fc9e729f50)

v2 打开预览页（或者新tab页预览）不会跳转到登录界面，会提示500，建议v2可以像v1跳转到登录页，登陆后可以打开previews页面
![image](https://github.com/dataease/dataease/assets/127368807/37eeee85-5f1b-444b-a34c-c9277555db68)

**Comment by xuwei-fit2cloud** [comment]
请清理浏览器缓存试试，没有复现您说的情况。
