### ISSUE TITLE
对于象限图使用后的一些建议[Feature]

### ISSUE THREAD

**Issue by github-tsg** [dataease/dataease#9800]
DataEase 版本:V2.6
**请描述您的需求或者改进建议.**
1.标签文本取消大小限制就好了（都能显示或不显示，这样比较统一）
 ![image](https://github.com/dataease/dataease/assets/146046004/af0ea7ed-6c82-4bdd-a3cd-560a3a2d358a)
 ![image](https://github.com/dataease/dataease/assets/146046004/f4b45f93-413b-4cdd-913a-e66f7111d3c5)
2.X轴/Y轴值线不能设置小数，求和是奇数的话，感官上左右象限之间就不平均，只通过调横轴轴值的话，数据就需要调整一下（位置移动了）；另外希望象限背景可以调成圆角矩形会更好看。
 ![image](https://github.com/dataease/dataease/assets/146046004/8efff06f-2af0-4828-9d3b-13e60674bf10)
![image](https://github.com/dataease/dataease/assets/146046004/845d1942-d410-4b0c-a268-82b0b32d9a92)
3.四个象限的参数（比如文本颜色和大小）能批量调整就好了
 ![image](https://github.com/dataease/dataease/assets/146046004/66638ebc-6382-4c73-9519-87e2949e3f8e)
4.下钻后显示的比较异常了，调整象限及横轴、纵轴后比较理想，请留意一下。
 ![image](https://github.com/dataease/dataease/assets/146046004/d0ac3667-b2fd-463a-b05d-994bdb4adc0a)
![image](https://github.com/dataease/dataease/assets/146046004/14891559-014c-45cf-a1c9-6675954565d0)

**Comment by xuwei-fit2cloud** [comment]
感谢反馈，我一一回复一下：
1. 目前标签显示位置的控制还不太好，遇到点问题，我们正在处理，但下个版本应该还无法解决；
2. 即将发布的v2.7.0版本中，恒线可以支持小数以及负数；
3. 象限设置的样式这块在v2.7.0版本中有所调整，目前还不太好做批量设置，我们后期想想交互上怎么优化一下；
4. 下钻后确实有点问题，我们近期版本优化一下。
