### ISSUE TITLE
[Feature]数据大屏排序和自适应浏览器问题

### ISSUE THREAD

**Issue by hehe210417** [dataease/dataease#9801]
DataEase 版本:2.6.1

1.排序问题。在mysql里面已经按照id将单位名称按照一定序列排好了顺序，在维度上拖放单位名称，结果显示出来的顺序就改变了，没有按照一定序列排序，需要手动进行排序，单位名称实在太多了，排起来好痛苦
2.大屏项目自适应浏览器问题。新建大屏默认就是1920*1080的尺寸，在预览或者分享后，会多出来浏览器顶部的一段距离，不能自适应浏览器，只有浏览器全屏显示才能正常

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，回复请见如下：
1、如果没有指定排序字段，按照什么顺序去读取是和数据库本身有关，因此这里我们处理不了，建议用order by指定排序字段。
2、大屏是根据设置的宽高比例进行展示的，因此展示效果和屏幕的宽高比例有关。
