### ISSUE TITLE
[Feature]操作日志，关于“修改用户”，能否增加具体修改的类型

### ISSUE THREAD

**Issue by mfanoffice** [dataease/dataease#9802]
DataEase 版本:
1.18

**请描述您的需求或者改进建议.**
操作日志记录中，关于“修改用户”，能否增加修改的类型，比如修改邮箱、是否启用等
![图片](https://github.com/dataease/dataease/assets/48307752/a143384c-5762-4d38-be93-eaadb415f9a4)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，近期暂时没有计划支持。
