### ISSUE TITLE
[Bug]视图过滤器使用视图计算字段不生效

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#9807]
**DataEase 版本**
1.18.19

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌最新

**Bug 描述*
数据库 doris 1.2 和 2.1 视图计算字段使用  DATEDIFF(CAST([end_time] AS DATETIME),cast([str_time] AS DATETIME) ) 使用函数计算出数字后，过滤器中过滤不生效，见图二，数据集计算字段无问题，见图一。

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/109720729/0ec711ad-9835-4a31-8466-291579f93932)

2.
![image](https://github.com/dataease/dataease/assets/109720729/42746f63-f2b8-4f69-84ba-d9c7b35243dd)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，将见面的连接符改成and呢？

**Comment by BBchicken-9527** [comment]
感谢反馈，我们尝试在后续版本进行修复；
