### ISSUE TITLE
[Feature] 使用动态参数后，如果参数不在 select 字段列表中，无法配置参数值

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#9810]
DataEase 版本:
2.6

此处我配置了一个动态参数，但是不在 group  by 中，所以该参数没在最终的 select 字段列表中
当我用这个数据集配置仪表板的时候，我无法为该参数赋值

![image](https://github.com/dataease/dataease/assets/40597893/4752ed26-00a5-4dd3-9873-c73d6c9cd4f2)
![image](https://github.com/dataease/dataease/assets/40597893/de57526f-fa89-411d-803d-7b187c919442)
![image](https://github.com/dataease/dataease/assets/40597893/a1cc8ef9-78ed-4f10-8d65-7559151e3f8e)
![image](https://github.com/dataease/dataease/assets/40597893/64419aac-b62c-4b19-81ab-a94ca7ce50b4)

此处的动态参数起到的作用是 group by 之前的过滤作用。
在 select 列表中不存在，目前看动态参数赋值只能在 select 字段列表中才能选择

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，v2.7版本对参数的绑定进行了优化，请等待新版本发布。
