### ISSUE TITLE
[Feature]希望仪表板导出时能支持导出移动端样式。

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#9819]
DataEase 版本:
希望仪表板导出时能支持导出移动端样式，用户导出时可以选择导出PC端样式还是移动端样式。

![image](https://github.com/dataease/dataease/assets/83771182/9121d1b1-7273-452d-b610-cd8c866094a9)

**请描述您的需求或者改进建议.**

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前暂时没有计划支持，建议您用截长图的方式，生成仪表板的手机端图片。
