### ISSUE TITLE
[Feature]移动端添加跳转

### ISSUE THREAD

**Issue by jstbw** [dataease/dataease#9828]
DataEase 版本:
v2.6

**请描述您的需求或者改进建议.**
当前版本制作移动端之后可以实现联动、钻取，但是在web端设置的跳转丢失了，希望支持这一功能

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，需要先讨论一下。

**Comment by jstbw** [comment]
测试了一下，v1.17.1是可以正常跳转的，还是希望能在下个版本支持，有用户需要这个功能点

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，已经加入近期的版本迭代中。
