### ISSUE TITLE
[Feature]标签定制间隔展示

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#9829]
DataEase 版本:
v1 或者v2

**请描述您的需求或者改进建议.**
在维度很多的情况下，标签展示会密密麻麻，可以定制隔几个维度展示一个
![image](https://github.com/dataease/dataease/assets/101089844/50ff8ac1-6274-4f38-83ba-e0a464f8954b)
![wecom-temp-97565-27d4589919f21cbf304f75a91986d50f](https://github.com/dataease/dataease/assets/101089844/1bfc6aae-59fc-4679-9798-5baf675361b2)

**Comment by xuwei-fit2cloud** [comment]
我们后期版本会提供最优显示选项，但不会提供间隔定制。

**Comment by xuwei-fit2cloud** [comment]
v2.10.2版本已处理，请升级版本。
