### ISSUE TITLE
[Bug]全屏预览下过滤组件位于仪表板下方（需要滚动下滑）的位置，点击过滤组件下拉框无法出现

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#9833]
**DataEase 版本**
v1.18.19

**运行方式(安装包运行 or 源码运行 ?)**

安装包
**浏览器版本**

Google Chrome
版本 124.0.6367.210（正式版本） (arm64)

**Bug 描述**
全屏预览下，过滤组件放在仪表板下方的位置，第二屏或者第一屏最下方，控制的是需要滚动到下面的视图。这时候过滤组件点击后出不来。
公共链接的全屏预览不会，在编辑状态或者tab页签全屏预览才会

截图gif，位于最上面的时候点击下拉框正常，第二个过滤组件已经有一部分看不到，第三第四个过滤组件位于仪表板下方，已经出不来

**Bug 重现步骤(有截图更好)**
第一个正常使用的，第二个已经有些出不来，第三个只能出来一部分，已经有问题。第四个完全不出来了
![未命名2](https://github.com/dataease/dataease/assets/127368807/93910d9f-fc6b-4913-8b54-6fbf5e9cfedb)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
