### ISSUE TITLE
[Bug]数据大屏明细表提示错误

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#9834]
**DataEase 版本**
v2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome、edge

**Bug 描述**
数据大屏中，创建明细表，表头和单元格的提示错误，未提示正确内容，而是显示一个白框

**Bug 重现步骤(有截图更好)**
1.创建数据大屏
2.创建明细表，开启表头和单元格提示
3.鼠标悬浮到明细表上，提示出现一个白框
![image](https://github.com/dataease/dataease/assets/77324661/8a84bf5f-d934-48d8-9af3-42f9d2169580)

**Comment by BBchicken-9527** [comment]
感谢反馈，应该是字体颜色设置为白色导致，我们修复一下；
![image](https://github.com/dataease/dataease/assets/84372766/27a9a368-cac9-41ca-be0a-93f264b5ad95)
