### ISSUE TITLE
[Feature]外部参数拼接公共链接实现定向分享

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#9835]
DataEase 版本:
2.6

**请描述您的需求或者改进建议.**
外部参数通过 base 加密后通过拼接公共链接分享 业务查看报表。
通过参数配置可以让用户看到目标数据。
但是如果只想让用户看到目标数据，不让他看目标数据之外的数据该如何做呢？
现在用户只要把attachParams部分去掉就可以看到所有的数据

比如拼接后的链接如下
http://xx.xx.xx.xx:8100/#/de-link/xxx?attachParams=xxxxx

只要用户去掉?attachParams=xxxxx部分 变成
http://xx.xx.xx.xx:8100/#/de-link/xxx
就可以访问所有的数据

这里能否实现分享链接的时候结合外部参数呢，避免用户通过去掉参数操作看到所有的数据？
![image](https://github.com/dataease/dataease/assets/40597893/f607e68e-fcc8-40f7-8fe5-f680104938e5)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们计划在v2.8版本的公共链接支持Ticket设置，可满足该场景下的使用。
