### ISSUE TITLE
[Feature]词云视图，希望支持读取文本，按词语出现的频次自动识别展示

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#9838]
DataEase 版本:
v2.6.1

**请描述您的需求或者改进建议.**
词云视图，希望支持读取文本，按词语出现的频次自动识别展示。
客户的场景是爬虫来一些数据，如果能直接读取文本进行识别会非常方便，这是痛点需求，如果能实现可以考虑企业版。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，产品目前主要是围绕数据可视化为核心的，即根据用户的数据，选择维度和指标，对数据聚合计算后进行展示。且系统对用户的业务场景也无法获知，因此并不能确认哪些词条需要分析展示，如果有需要，建议根据自己的需求，对数据先进行清洗整理后，再进行展示。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，项目目前主要是围绕数据可视化为核心的，即根据用户的数据，选择维度和指标，对数据聚合计算后进行展示。且系统对用户的业务场景也无法获知，因此并不能确认哪些词条需要分析展示，如果有需要，建议根据自己的需求，对数据先进行清洗整理后，再进行展示。
