### ISSUE TITLE
[Bug]仪表板中切换视图后，视图名称未更新

### ISSUE THREAD

**Issue by binbin0406** [dataease/dataease#9839]
**DataEase 版本**
v2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome、edge

**Bug 描述**
仪表板中切换视图后，视图名称未更新。比如选选择了基础柱状图，然后更换为基础折线图，但视图的标题仍显示为基础柱状图

**Bug 重现步骤(有截图更好)**
1.创建仪表板
2.选择一个视图后，重新更换一个视图
3. 查看该视图标题，未更新
![image](https://github.com/dataease/dataease/assets/77324661/86154f7d-03ac-4d6e-8668-c2c739407bf5)
![image](https://github.com/dataease/dataease/assets/77324661/f051f427-5326-4155-8f82-11b4e1fdd903)

**Comment by BBchicken-9527** [comment]
感谢反馈，你的意思是当你创建了一个图表后发现不符合自身需求，使用右侧切换图表方式进行的切换是吗？

**Comment by binbin0406** [comment]
> 感谢反馈，你的意思是当你创建了一个图表后发现不符合自身需求，使用右侧切换图表方式进行的切换是吗？

是的

**Comment by BBchicken-9527** [comment]
复制后标题是固定的，这个是没有办法根据你切换的图表去显示的，打个比方，比如你说你要我们按照之前的顾客做一份蛋炒饭我们做出来了，这时候你又说不要胡萝卜，那这时候我我们也只能帮你去除胡萝卜而没办法去做其他的操作，也就是说你在做出修改的时候已经将复制对象的全部属性都复制完了，这个时候只能受累你手动进行修改一下了；
