### ISSUE TITLE
[Feature]v2版本 表格下钻之后的列宽不能调整占满。

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#9841]
如下视频，下钻前可以占满自适应，下钻之后不能占满。
https://github.com/dataease/dataease/assets/141667200/ce657ee6-be47-4d88-b8b9-1178a53da44e

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要讨论下优化方式。

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们先记录一下，目前暂时没有合适的优化方案。

**Comment by xuwei-fit2cloud** [comment]
请升级版本。
