### ISSUE TITLE
[Bug]连接sql server成功，但是搭建的大屏无法渲染出数据，报错。版本v2.61

### ISSUE THREAD

**Issue by zaixingzheng** [dataease/dataease#9842]
**DataEase 版本**
v2.61

**运行方式(安装包运行 or 源码运行 ?)**
源码docker

**浏览器版本**
Edge 125.0.2535.51

**Bug 描述**
sql server数据源建立ok，但是搭建的大屏无法渲染出数据，报错。

**Bug 重现步骤(有截图更好)**
1. 数据源成功
![1](https://github.com/dataease/dataease/assets/130120094/09a07e3a-bb04-4e7e-a24a-57b94624e41e)

2. 渲染页面报错
![2](https://github.com/dataease/dataease/assets/130120094/ab5b807e-8f90-4c65-a56a-674bbda8f08d)

3. docker logs
![3](https://github.com/dataease/dataease/assets/130120094/cc9b7e7d-66d8-400a-9eef-e665565cefdb)

**Comment by zaixingzheng** [comment]
补充一点，数据库版本是sqlserver2008 r2

**Comment by BBchicken-9527** [comment]
感谢反馈，由于你是源码运行，不确定你是否改动和以及打包方式都有可能存在问题，建议你加入我们的交流群，上面有非常专业的同学会实时的回复你的问题，方便你快速并精准的定位到你的问题所在；
