### ISSUE TITLE
联动时所选类目怎么突出显示

### ISSUE THREAD

**Issue by yanlong-big** [dataease/dataease#9848]
![879eb3db6ec99d22f959d32c94928ba](https://github.com/dataease/dataease/assets/116066130/0a5a1896-2866-4bf3-8106-6147c95c4f08)

我点了D61，视图联动了，这是正常的，怎么做到我点D61，D61那条突出显示，区别于其他类目。类似这样

![Uploading 1716533199227.jpg…]()

**Comment by yanlong-big** [comment]
![1716533199227](https://github.com/dataease/dataease/assets/116066130/25af76ce-12f3-4570-b21f-75026f8c0f07)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们优化一下。
