### ISSUE TITLE
[Bug]v2 时间字段转化

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#9849]
![image](https://github.com/dataease/dataease/assets/141667200/6ddd8872-bdfd-4daa-ab02-2fe1e6ee5210)
![image](https://github.com/dataease/dataease/assets/141667200/21d0b8a0-85e3-4147-8b9e-b8e76ec3a0a0)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前转换格式为固定格式，文本转换后统一使用-分割；
