### ISSUE TITLE
更改查询组件内元素的大小

### ISSUE THREAD

**Issue by yanlong-big** [dataease/dataease#9850]
![1716537815540](https://github.com/dataease/dataease/assets/116066130/3e8b5e64-5ce7-4461-b74e-08c59b7872fe)

如图红框内，我想更改片区查询组件的长度

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，目前查询条件的大小、样式等均是统一的，不支持单独配置。

**Comment by xuwei-fit2cloud** [comment]
可以试试：
![图片](https://github.com/user-attachments/assets/4e403c3e-17ed-4292-b075-8e82e5360e81)
