### ISSUE TITLE
怎么更改查询组件和图表的背景颜色

### ISSUE THREAD

**Issue by yanlong-big** [dataease/dataease#9852]
我想更改颜色和一定程度的透明填充，如图

![1716539586525](https://github.com/dataease/dataease/assets/116066130/08b90fbe-ef98-4041-8330-bd87ca954d19)

**Comment by yayanpei-fit2cloud** [comment]
可调整下图所示的配置项调整查询组件的图表的背景颜色。
查询组件背景色设置：
![image](https://github.com/dataease/dataease/assets/84168063/29b2d039-a2ba-49d9-aa51-ea3bd7ee92e7)
图表背景设置：
![image](https://github.com/dataease/dataease/assets/84168063/e321fae5-865c-4493-97e8-c4a1baa7d032)
