### ISSUE TITLE
[Feature] 查询组件关联到sql参数上

### ISSUE THREAD

**Issue by heichong** [dataease/dataease#9857]
DataEase 版本:V2

目前V2只能把查询组件关联到dataset返回的某个列上面，能否直接关联到sql动态参数上？ 
因为这个参数对应的列可能不会在dataset结果集里。

**Comment by heichong** [comment]
举一个例子：
有两张表：项目表和项目参与人表，项目与参与人是一对多的关系。
我想根据查询组件，查询某个人员参与的所有项目列表。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，建议将项目参与人员姓名作为查询组件的选项值，在查询组件配置中，将该查询条件与项目图表关联。
