### ISSUE TITLE
[Bug]提交的Excel文件百分比值有问题

### ISSUE THREAD

**Issue by jstbw** [dataease/dataease#9859]
**DataEase 版本**

v2.6.0
**运行方式(安装包运行 or 源码运行 ?)**

**浏览器版本**

**Bug 描述**

上传了一份excel文件到v2.6.0，自动将百分比内容识别为文本类型
![image](https://github.com/dataease/dataease/assets/66759501/00ba1a0c-beb1-484d-b725-2faea88c62ff)
![image](https://github.com/dataease/dataease/assets/66759501/00ba1a0c-beb1-484d-b725-2faea88c62ff)
![image](https://github.com/dataease/dataease/assets/66759501/0b71e198-5171-48f4-b96a-605b4427fb15)
![image](https://github.com/dataease/dataease/assets/66759501/0b71e198-5171-48f4-b96a-605b4427fb15)

v1.17.1则是正常的识别为数值类型
![image](https://github.com/dataease/dataease/assets/66759501/06865e7e-dbfa-44d2-b2c3-53ecc43a2969)
![image](https://github.com/dataease/dataease/assets/66759501/06865e7e-dbfa-44d2-b2c3-53ecc43a2969)

这样才能便于做计算he和修改格式

**Comment by BBchicken-9527** [comment]
感谢反馈，我们在后续版本优化一下；
