### ISSUE TITLE
[Bug]V2 跨数据源关联数据集预览时间字段没问题，到视图中都变为1970-01-01

### ISSUE THREAD

**Issue by hcff2c** [dataease/dataease#9863]
**DataEase 版本**
v2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**Bug 描述**
V2 跨数据源关联数据集预览时间字段没问题，到视图中都变为1970-01-01

**Bug 重现步骤(有截图更好)**
1.
![image](https://github.com/dataease/dataease/assets/101089844/6fac8867-9cbb-48a4-9214-30284e2104e7)

2.
![image](https://github.com/dataease/dataease/assets/101089844/c3ff0ae1-a8c8-4ef1-8ef7-90c40457123e)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会尽快修复；

**Comment by maninhill** [comment]
v2.10-lts 版本已经发布，请在最新版本上面验证，有问题请 re-open。
