### ISSUE TITLE
横向柱状图可以更改横坐标轴大小吗

### ISSUE THREAD

**Issue by yanlong-big** [dataease/dataease#9865]
![image](https://github.com/dataease/dataease/assets/116066130/f709b968-ab08-4db1-af30-a916b19e561f)

如图，这是横向柱状图，我想把恒坐标改成150到180的区间，请问怎么修改

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，可以按照下图所示进行设置。
![image](https://github.com/dataease/dataease/assets/84168063/c584c0c7-f109-498e-89a0-4d49cd5e7610)
