### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by yanlong-big** [dataease/dataease#9866]
DataEase 版本:社区版 2.5.0

**请描述您的需求或者改进建议.**
![image](https://github.com/dataease/dataease/assets/116066130/9d51a27a-808b-402a-ad67-7842463d72fa)
怎么在查询组件内排序，D1,D2,D3,D4,D5

**Comment by yayanpei-fit2cloud** [comment]
重复issue：https://github.com/dataease/dataease/issues/9867
