### ISSUE TITLE
查询组件怎么没法自定义排序

### ISSUE THREAD

**Issue by yanlong-big** [dataease/dataease#9867]
**请描述您的问题.**
![image](https://github.com/dataease/dataease/assets/116066130/d9547f56-84b5-4997-b9c5-e63a339a2dcd)

![1716624351947](https://github.com/dataease/dataease/assets/116066130/3cd9966f-1ebe-4561-b542-b2a8e0f97d9d)

怎么没法自定义排序，D1,D2,D3,D4,D5

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，建议您升级版本，新版本中可以指定数据集的字段作为排序字段，如下图所示：
![image](https://github.com/dataease/dataease/assets/84168063/c87f9069-27d6-4fad-92f9-d05e3d832d2f)
