### ISSUE TITLE
[Bug]【数据集】Oracle 数据源新建计算字段报错报错

### ISSUE THREAD

**Issue by AndroidBaby1** [dataease/dataease#9868]
**DataEase 版本**
v2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
标准谷歌浏览器

**Bug 描述**
Oracle 数据源新建计算字段报错报错，详见截图（Oracle 11g）

**Bug 重现步骤(有截图更好)**
1.如图对 Oracle 数据源的其中一个表中添加新建字段。
![image](https://github.com/dataease/dataease/assets/24768910/1ea860c6-5148-4123-b242-15ee89312ff3)

2.点击保存，保存如下。
![image](https://github.com/dataease/dataease/assets/24768910/7e0f799f-19d6-4207-8740-5a4c8e8cc96b)

3.DBeaver 执行正常。
![image](https://github.com/dataease/dataease/assets/24768910/6a1fa67a-7fa0-4e43-a9ed-5f7fb7554b10)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；
