### ISSUE TITLE
[Bug]仪表板设计布局完成后，点击中间列的视图进行编辑，编辑完成后返回最右侧仪表板位置发生了左移

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#987]
**DataEase 版本**
1.3

**浏览器版本**
chrome 版本 94.0.4606.61（正式版本） (arm64)

**Bug 描述**
仪表板设计布局完成后，点击中间列的视图进行编辑，编辑完成后返回最右侧仪表板位置发生了左移

**Bug 重现步骤(有截图更好)**
当前布局到的仪表板：
![image](https://user-images.githubusercontent.com/60059766/138045339-620f146b-e295-4c38-ae84-1ea280f78f7a.png)

点击红框内编辑按钮，编辑视图，编辑视图完成后页面布局：
![image](https://user-images.githubusercontent.com/60059766/138045126-421195e2-6013-4478-96aa-eb23f5ba036f.png)

**Comment by yayanpei** [comment]
感谢您的反馈，我们尽快修复一下。

**Comment by xuwei-fit2cloud** [comment]
v1.4.0 已修复
