### ISSUE TITLE
[Bug]跨数据源关联时报错

### ISSUE THREAD

**Issue by dengfj** [dataease/dataease#9875]
**DataEase 版本**
V2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
源码运行

**浏览器版本**
Chrome

**Bug 描述**
mysql和Excel上传的文件，跨数据源进行关联时报500错误，说

**Bug 重现步骤(有截图更好)**
1.
java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: Could not initialize class org.apache.calcite.util.BuiltInMethod [in thread "http-ni
o-8089-exec-3"]
        at org.apache.calcite.rel.metadata.BuiltInMetadata$PercentageOriginalRows.<clinit>(BuiltInMetadata.java:354)
        at org.apache.calcite.rel.metadata.RelMdPercentageOriginalRows$RelMdPercentageOriginalRowsHandler.getDef(RelMdPercentageOriginalRows.java:239)
        at org.apache.calcite.rel.metadata.ReflectiveRelMetadataProvider.reflectiveSource(ReflectiveRelMetadataProvider.java:137)
        at org.apache.calcite.rel.metadata.RelMdPercentageOriginalRows.<clinit>(RelMdPercentageOriginalRows.java:43)

2.
![image](https://github.com/dataease/dataease/assets/54826920/29c2dfe8-536b-465a-bfe9-3b6bca8704d4)

3.

**Comment by dengfj** [comment]
![image](https://github.com/dataease/dataease/assets/54826920/76105ed8-9613-4510-9b3e-fde120ed1042)
 项目中这个包已经引入了

**Comment by dengfj** [comment]
calcite-linq4j
![image](https://github.com/dataease/dataease/assets/54826920/926e626b-9557-4a10-b333-3e61134689cc)

**Comment by dengfj** [comment]
calcite-linq4j版本改为1.35.0后， 数据库表 跟 Excel文件直接关联没有写SQL的情况下，还是报错：
Method[deExceptionHandler][SQL执行失败，请检查表、字段、关联关系等信息是否正确并重新编辑。Error while preparing statement [SELECT
     t_a_0.`f_1cb7521d775ee649` AS f_ax_0,
     t_a_0.`f_766c4310c6277752` AS f_ax_1,
     t_a_0.`f_90310acdd757d155` AS f_ax_2,
     t_a_0.`f_21a2ca8deeec8604` AS f_ax_3,
     CAST(t_a_0.`f_f53b039cc20a6e89` AS DECIMAL(26,8)) AS f_ax_4
FROM
    (SELECT t_a_0.`user_name` AS `f_90310acdd757d155`,t_a_0.`cost_center_code_to` AS `f_21a2ca8deeec8604`,t_a_0.`busi_num` AS `f_f53b039cc20a6e89`,t_a_1.`id` AS `f_1cb7521d775ee649`,t_a_1.`nick_name` AS `f_766c4310c6277752` FROM s_a_1.`excel_Sheet1_667eef7f7b` t_a_0  LEFT JOIN  s_a_992847979608150016.`t_sys_user` t_a_1  ON t_a_0.`user_name` = t_a_1.`user_name`)   t_a_0
 LIMIT 100 OFFSET 0] [Compiling "Baz" in Line 1, Column 14: Line 2, Column 45: Compiling "bind(org.apache.calcite.DataContext root)"]]

**Comment by dengfj** [comment]
![image](https://github.com/dataease/dataease/assets/54826920/f66d31be-723f-4ecc-879e-781b0a72742b)
官方的体验环境，Excel跟表关联，也是报错

**Comment by BBchicken-9527** [comment]
感谢反馈，应该是calcite产生的异常，我们分析一下错误原因会努力尽快解决；

**Comment by maninhill** [comment]
v2.10-lts 版本已经发布，请在最新版本上面验证，有问题请 re-open。
