### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by htl258** [dataease/dataease#9877]
**DataEase 版本**
v1.18.19 

**运行方式(安装包运行 or 源码运行 ?)**
数据集导出到excel失败

**浏览器版本**
EDGE或GOOGLE的最新版

**Bug 描述**
在数据集中，选中任一数据集，点右上角的数据集导出，一会儿后便报错。

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by xuwei-fit2cloud** [comment]
Duplicate of #9702
