### ISSUE TITLE
[Feature]希望可以自定义组件间吸附的间距

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#988]
**请描述您的需求或者改进建议.**
组件自动吸附的默认间距是否可以自定义，目前的间距会稍微感觉有些宽，比如想和图表距离仪表盘上面的间距相等。
![image](https://user-images.githubusercontent.com/48945409/138073300-1212ec49-3b1d-42e9-9330-b0d615088c62.png)

**Comment by xuwei-fit2cloud** [comment]
v1.5.0 对间距进行了统一
