### ISSUE TITLE
[Feature]v2 辅助线功能，设置动态值为辅助线时，希望平均值可以设置小数位数的保留

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#9883]
![image](https://github.com/dataease/dataease/assets/141667200/3af924a6-dbcb-4e02-906d-bb6d672bebc6)
![image](https://github.com/dataease/dataease/assets/141667200/469cb4fb-acbf-4af1-9d60-f493d502106a)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，辅助线是跟随纵轴的数值格式，可按照下图所示进行设置。
![image](https://github.com/dataease/dataease/assets/84168063/955b0783-4ad7-4fcb-82d0-795d8189a33b)

**Comment by wolf-kingx** [comment]
![image](https://github.com/dataease/dataease/assets/141667200/f931c091-5bbd-4c3b-9b59-9d655e61810b)

**Comment by wolf-kingx** [comment]
![image](https://github.com/dataease/dataease/assets/141667200/d0f61b22-fd8d-43a9-b6d0-78729edf3d09)

**Comment by xuwei-fit2cloud** [comment]
从上图轴值来看，应该是右纵轴，而图中设置的是左纵轴。
