### ISSUE TITLE
[Feature]建议可以更灵活设置图表背景相对元素的距离（当去掉图例后图表背景可以收缩）

### ISSUE THREAD

**Issue by luyang351** [dataease/dataease#989]
**请描述您的需求或者改进建议.**
当去掉图表很多元素后，想呈现的更简约一些，例如去掉图例、纵坐标等，但是背景给这些元素预留的位置仍然在。会显得很空。
建议是否可以根据配置自动收缩或是可以自定义相对间隔。
![image](https://user-images.githubusercontent.com/48945409/138074496-8546ca9d-292f-49d5-9a33-cd7bf90b599d.png)
![image](https://user-images.githubusercontent.com/48945409/138074662-1b43b1bd-625d-4bfc-a275-3503fd32feeb.png)

**Comment by xuwei-fit2cloud** [comment]
antv图库对这部分处理教好，可以使用antv图库的图形。
