### ISSUE TITLE
[Bug]世界地图标签无法展示各个国家地名

### ISSUE THREAD

**Issue by yaoyi111** [dataease/dataease#9890]
**DataEase 版本**
V2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
chrome121

**Bug 描述**
世界地图标签无法展示各个国家地名

**Bug 重现步骤(有截图更好)**
1.世界地图拖入维度数据
2.样式中打开标签选项
3.点击更新视图按钮
![a932b63171901ee00880609e30e310e](https://github.com/dataease/dataease/assets/83771182/4467c628-3446-496b-b836-734c73f837ef)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在最近两个版本内尽快修复；
