### ISSUE TITLE
提交筛选后图表没有筛选

### ISSUE THREAD

**Issue by yanlong-big** [dataease/dataease#9894]
社区版2.5.0

安装包

![c67adc61f63ab1d72c049c0ef707173](https://github.com/dataease/dataease/assets/116066130/fdcc11be-2ba0-4c73-a22a-9da4618d67c3)

如图，已经添加小于1月30日的筛选，怎么图表中还有2月份的数据

**Comment by BBchicken-9527** [comment]
感谢反馈，下个版本会对此处进行优化，可以到时下载新版本进行体验；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
