### ISSUE TITLE
[Feature]期望 V2 版本能像 V1 版本一样 隐藏透视表行小计

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#9896]
DataEase 版本:
v2.6.1

**请描述您的需求或者改进建议.**
V1 支持隐藏
![image](https://github.com/dataease/dataease/assets/30886198/6d4b49cd-5068-446a-bbda-64b06440fc64)

V2 无法取消勾选
![image](https://github.com/dataease/dataease/assets/30886198/407f6156-47ed-49c4-aeb0-aec0ed935e3e)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，这里是个bug，v2.7版本已经修复，会在下周发布。
