### ISSUE TITLE
[Feature]V2 期望查询组件支持对齐

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#9898]
DataEase 版本:
 V2.6.1

**请描述您的需求或者改进建议.**
如图，查询组件纵向排列时名称长短会导致查询条件参差不齐，样式不好，期望查询框可以实现上下对齐。目前只能通过修改查询组件的名称保持同样字数才能对齐。

![image](https://github.com/dataease/dataease/assets/30886198/29a428c7-cd57-48b5-9bca-610c7343b271)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，查询组件的名称和组件之间的间距目前是统一的，我们增加个配置项：可以调整间距。另外，您也可以调整名称和组件的位置关系，从而使组件上下对齐，如下图所示：
![image](https://github.com/dataease/dataease/assets/84168063/bcfec052-623a-45ce-af1b-402dc6b27686)
