### ISSUE TITLE
[Feature]希望能够修改查询按钮颜色

### ISSUE THREAD

**Issue by liuboF2c** [dataease/dataease#9900]
DataEase 版本:
 v2.6.1

**请描述您的需求或者改进建议.**
 目前的查询按钮默认颜色无法修改。无法根据仪表板样式修改成合适的颜色。期望提供颜色修改功能。

![image](https://github.com/dataease/dataease/assets/30886198/244e2862-ed63-474b-b92a-e4d50c4dbc4e)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议很不错，我们优化一下。
