### ISSUE TITLE
折线图的渐变色是什么意思

### ISSUE THREAD

**Issue by yanlong-big** [dataease/dataease#9907]
社区版
2.5.0

选择了渐变颜色，但是颜色几乎没有改变，怎么能做到像第2张图那样

![image](https://github.com/dataease/dataease/assets/116066130/5ccb6d6b-5988-4671-aab1-8b012f665399)
![1716873868252](https://github.com/dataease/dataease/assets/116066130/51ee1307-2416-4d18-b14c-2efba4e94b02)

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，是在这里设置的，请问是没生效吗？可以刷新或者重启浏览器再试试。
![image](https://github.com/dataease/dataease/assets/84168063/2b6ba1ed-1d07-4f5e-8b7e-af6f2ae24877)

**Comment by yayanpei-fit2cloud** [comment]
应该是自定义了纵轴的轴值引起的，当轴值的最小值大于0时，渐变效果没那么明显了，这里我们再优化一下。
