### ISSUE TITLE
怎么把柱状图做成椭圆柱状图

### ISSUE THREAD

**Issue by yanlong-big** [dataease/dataease#9909]
社区版 2.5.0

![image](https://github.com/dataease/dataease/assets/116066130/83b7d259-ea6d-4e15-8587-146cc710f577)

![image](https://github.com/dataease/dataease/assets/116066130/40da905e-4e16-4d4f-a8ba-2043279c5229)

1.怎么做成图2那种椭圆的柱状图？
2.是否可以通过echarts实现?

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，您的建议很不错，我们在近期的版本中支持一下。
