### ISSUE TITLE
[Bug]漏斗图展示错误

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#991]
**DataEase 版本**
1.3

**浏览器版本**
谷歌版本 94.0.4606.61（正式版本） (arm64)

**Bug 描述**
漏斗图数值不一致但是漏斗宽度一致

**Bug 重现步骤(有截图更好)**
制作视图
![image](https://user-images.githubusercontent.com/60059766/138203886-d403d0de-a9ff-49b2-a326-d5761042d05b.png)

**Comment by yayanpei** [comment]
感谢您的反馈，V1.4.0 (11月4日)会发布新的图库，还请多家关注。

**Comment by xuwei-fit2cloud** [comment]
图形展示和使用的图库有关，echarts原生的漏斗图对上述数据展示确实如此，可以考虑更换 v1.4.0 antv图库的漏斗图。
