### ISSUE TITLE
[Bug] 在富文本中设置跳转链接 "在当前窗口" 不生效

### ISSUE THREAD

**Issue by janus177** [dataease/dataease#9910]
**DataEase 版本**
v2 和  v1 均不生效

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**
谷歌

**Bug 描述**
富文本组件中设置跳转链接，链接打开位置 "在当前窗口" 不生效，还是会打开新窗口

**Bug 重现步骤(有截图更好)**
![image](https://github.com/dataease/dataease/assets/163749505/df7cc76c-dc3f-49ba-8c9b-8013f3d9ad9b)

**Comment by BBchicken-9527** [comment]
感谢反馈，原生组件问题修改起来会相对麻烦，我们会尽快完善，感谢；

**Comment by xuwei-fit2cloud** [comment]
请更新版本。
