### ISSUE TITLE
[Bug]数据超过1页无法打印超出部分

### ISSUE THREAD

**Issue by Diidaer** [dataease/dataease#9911]
**DataEase 版本**
v2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge v125.0.2535.67

**Bug 描述**
打印页面，只能打印1页，超过1页的内容无法打印出来

**Bug 重现步骤(有截图更好)**
1.数据超过一页
![image](https://github.com/dataease/dataease/assets/75790780/c11cd732-8b0d-4042-9843-6942576d0db4)
2.导出图片
![image](https://github.com/dataease/dataease/assets/75790780/59c6a7ad-e1a4-4aea-a5e2-4e7af408ca3b)
3.导出的图片只导出了网页当前显示的数据，并不能导出所有被筛选出的数据
![image](https://github.com/dataease/dataease/assets/75790780/f36e0afd-9797-4bf2-a953-af7c14a0f890)

**Comment by BBchicken-9527** [comment]
感谢反馈，目前图片的导出是只导出当前页面的，因为明细表接近数据的导出，如果需要全不导出的话建议导出到excel中；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
