### ISSUE TITLE
[Bug]柱线图相关

### ISSUE THREAD

**Issue by Diidaer** [dataease/dataease#9914]
**DataEase 版本**
v2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包运行

**浏览器版本**
Microsoft Edge v125.0.2535.67

**Bug 描述**
柱线组合图中的线图错误
柱线图不能多加线，只能固定1条线

**Bug 重现步骤(有截图更好)**
1.画圈处两个相同的数据柱线显示却不同
![bug](https://github.com/dataease/dataease/assets/75790780/4a26efc3-d2a0-4e44-948e-f7744d482789)
2.柱线组合图只能画一条线
![bug2](https://github.com/dataease/dataease/assets/75790780/ef96ab6c-02be-499b-b67e-d1f46b263c7e)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们下个版本尝试修复一下；

**Comment by ulleo** [comment]
#10192
