### ISSUE TITLE
[Feature]能否添加被动接收数据源的功能

### ISSUE THREAD

**Issue by miaowmint** [dataease/dataease#9915]
目前 dataease 获取数据的方式似乎都是通过数据库 API 本地文件等主动获取数据

那么能否增加通过 http接口 的方式**被动获取**其它来源推送过来的数据呢

例如腾讯云EO 有个实时日志的功能，能够向http接口主动推送实时日志

![image](https://github.com/dataease/dataease/assets/58991169/3a594f91-86ac-41e9-9f13-a8c606661e5b)

![image](https://github.com/dataease/dataease/assets/58991169/e8966038-5381-4b0f-a09f-0b283a4ddd5d)

![image](https://github.com/dataease/dataease/assets/58991169/c2b3fc72-9970-4ba3-8b10-f528eafc2db2)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们需要先讨论一下。

**Comment by yayanpei-fit2cloud** [comment]
再次感谢您的反馈和支持，目前暂时没有计划进行支持，issue我们就先关闭了。
