### ISSUE TITLE
筛选器和联动功能

### ISSUE THREAD

**Issue by sxjm** [dataease/dataease#9918]
DataEase 版本:
v1.18.11

**请描述您的需求或者改进建议.**
需求一：A筛选器的选项能否跟着B筛选器的筛选变动？例如，省份筛选器筛选福建省后，城市筛选器里只剩下福建省的城市；
需求二：图表内的联动功能能否类似于需求一作用到筛选器？例如在款号销量图里点击A款号，其它图表会联动筛选A款号的数据，相对应的款号筛选器能否变为显示筛选A款号？

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，筛选器的联动v1版本目前没有计划进行支持，已经规划在v2近期的版本中。
