### ISSUE TITLE
[Bug]v1 动态排序图，在动态变化的时候，部分柱子标签偶尔会出现-的情况及在排序过程中，如果排名不变的话，是不是类别名字也不变合理些，现在每次换时间段的时候，排名不变但是名字仍然有切换的动画

### ISSUE THREAD

**Issue by wolf-kingx** [dataease/dataease#9922]
![image](https://github.com/dataease/dataease/assets/141667200/37b52a48-b68a-49e3-b3b9-76f95f13600d)

视频如下：

https://github.com/dataease/dataease/assets/141667200/b9639388-5210-44fe-94bc-05412329e056

**Comment by Shenguobin0102** [comment]
你好，纵轴标签跳动的问题已修复，请关注下个版本。
