### ISSUE TITLE
[Bug]dataease cpu占用率过高

### ISSUE THREAD

**Issue by lit2430** [dataease/dataease#9930]
**DataEase 版本**
1.18.14

**运行方式(安装包运行 or 源码运行 ?)**
本地私有化部署（非docker容器化部署）

**浏览器版本**

**Bug 描述**
采用直连数据源，8核8g的服务器，cpu拉满，并且资源不释放。

![lQLPKHYfGNkhcXnNASDNBBCwyj2kyHD_PTYGQVWvUVfIAA_1040_288](https://github.com/dataease/dataease/assets/91309604/4760f190-81b3-4eaf-a848-078aa72f4cbc)

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by maninhill** [comment]
请升级到 v1.18.19，如还有问题，请贴上日志。

**Comment by lit2430** [comment]
18.19版本有专门针对cpu占用率高做过处理吗

**Comment by xuwei-fit2cloud** [comment]
这个还是需要结合具体时间点的日志来排查问题的，看看在CPU使用率很高的时候执行了什么操作。
常见的比较消耗资源的操作有：
数据导出、报告生成、大数据查询等。
