### ISSUE TITLE
[Bug]v2 下钻后的图表跳转没有生效

### ISSUE THREAD

**Issue by greenyhsj** [dataease/dataease#9933]
**DataEase 版本**
v2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

Chrome 已是最新版本
版本 125.0.6422.113（正式版本） (arm64)

**Bug 描述**
图表设置下钻，下钻后的字段设置跳转，先进行下钻后点击跳转不生效。没有设置下钻，直接点击跳转能生效。

**Bug 重现步骤(有截图更好)**
![未命名](https://github.com/dataease/dataease/assets/127368807/06e87da2-2138-4622-98a0-60ed2a7f1741)

**Comment by BBchicken-9527** [comment]
感谢反馈，我们会在下个版本进行修复；

**Comment by BBchicken-9527** [comment]
目前问题已修复，可在最新版本中使用；
