### ISSUE TITLE
[Question] Terminating due to java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by yejue** [dataease/dataease#9935]
2024-05-29 11:38:26,101 DEBUG atasourceMapper.updateByExampleSelective: 137 - <==    Updates: 1
Terminating due to java.lang.OutOfMemoryError: Java heap space

**Comment by yejue** [comment]
dataease 版本：1.8
mysql版本：8.0+

部署形式：使用 dataease 和 mysql 容器

**Comment by maninhill** [comment]
目前这些信息我们没有办法进一步排查。
应该是内存太小了，我们其他用户没有反馈此类问题。

**Comment by yejue** [comment]
> 目前这些信息我们没有办法进一步排查。 应该是内存太小了，我们其他用户没有反馈此类问题。

![image](https://github.com/dataease/dataease/assets/49857339/daee4b2f-436d-45a1-ab41-77c351ffa396)

发现是在一个 update 操作之后被中断的，现在每一次启动都会直接中断，要怎么取消这个操作呢
