### ISSUE TITLE
[Bug]手机访问，仪表盘的过滤控件未示完全

### ISSUE THREAD

**Issue by htl258** [dataease/dataease#9936]
**DataEase 版本**
V1.18.19

**运行方式(安装包运行 or 源码运行 ?)**
在微信或手机浏览器上打开电脑分享的仪表盘链接

**浏览器版本**
手机端浏览器

**Bug 描述**
仪表盘的过滤控件未示完全，其他仪表盘组件暂未发现异常。

**Bug 重现步骤(有截图更好)**
1.
![微信图片_20240529114245](https://github.com/dataease/dataease/assets/131636095/8e388839-b680-4f73-acae-95e72bf66509)

2.
![微信图片_20240529114249](https://github.com/dataease/dataease/assets/131636095/904592ca-69f2-4ea0-a5b0-6abadfbfd10c)

3.

**Comment by BBchicken-9527** [comment]
感谢反馈，请问是否设置了移动端布局？如果没有设置移动端布局因为要按照横版显示竖版的内容可能会导致图表挤压导致异常；

**Comment by BBchicken-9527** [comment]
由于问题状态停留时间过长，我先将问题暂时关闭，若依旧存在此问题可随时重新打开问题或向公众群中反馈，到时会有非常专业的同学进行处理，感谢你的反馈与支持；
