### ISSUE TITLE
如何用SQL变量进行计算

### ISSUE THREAD

**Issue by xix1** [dataease/dataease#9948]
如题，我在SQL数据集中添加了参数，我想使用这个参数进行计算，比如我设置了两个时间参数，分别表示开始和结束时间，也就是一个时间区间，现在我想计算数据库中某个时间区间和这个参数区间的交集时间，但是提示'SQL 变量只能在 WHERE 条件中使用'，有什么办法可以实现吗？

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，目前SQL变量仅支持在where条件中使用。
