### ISSUE TITLE
[Feature]视图排序，支持多个排序

### ISSUE THREAD

**Issue by linyuiu** [dataease/dataease#9949]
DataEase 版本:
1.18.19

**请描述您的需求或者改进建议.**
目前图库只能按照一个指标或者维度排序，希望可以支持多个指标排序，像 order by 一样。

**Comment by yayanpei-fit2cloud** [comment]
感谢反馈，请问是哪个图库？哪一种视图？

**Comment by linyuiu** [comment]
目前好像所有的视图都是以维度字段优先级更高，且只生效一个

**Comment by yayanpei-fit2cloud** [comment]
排序的生效，是维度的优先级高于指标。
