### ISSUE TITLE
[Feature] 数据同步模块增加doris写入端口

### ISSUE THREAD

**Issue by limin-fit2** [dataease/dataease#9953]
DataEase 版本:

V2.6.1 

**请描述您的需求或者改进建议.**

 数据同步模块目标数据源目前是使用的Doris，认证对接填写的端口是9030（默认），实际上数据同步写入的端口是8040（默认），如果8040端口没有正常打开，那么同步日志有提示，但是实际上是未同步成功，第一，是否考虑同步状态异常的情况，方便排查，第二，数据库链接信息建议增加一个写入端口，避免开放端口与默认端口不一致问题
![image](https://github.com/dataease/dataease/assets/61964761/4c6b41eb-bdb2-4b7e-b713-291022131752)
![image](https://github.com/dataease/dataease/assets/61964761/441022e3-4d76-4297-9b28-45503153a6a7)

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，我们近期的版本中会进行优化。
