### ISSUE TITLE
[Feature]汇总表支持合并单元格

### ISSUE THREAD

**Issue by xueqidove** [dataease/dataease#996]
**请描述您的需求或者改进建议.**
汇总表视图类型能够支持单元格合并展示
![image](https://user-images.githubusercontent.com/60059766/138217657-e61c387a-8346-436f-8cbf-0f06310bfd98.png)

**Comment by xuwei-fit2cloud** [comment]
很抱歉，该需求还需要一些时间来处理，近期内还不会支持，先暂时关闭。
