### ISSUE TITLE
[Feature] 外观配置

### ISSUE THREAD

**Issue by limin-fit2** [dataease/dataease#9966]
DataEase 版本:

V2.6.1

**请描述您的需求或者改进建议.**

 V2顶部导航背景色现在默认只能设置深色和浅色，是否能像V1一样增加自定义颜色设置。
![image](https://github.com/dataease/dataease/assets/61964761/bfaece76-3d1a-47a4-bcfd-8e22e346bc14)
![image](https://github.com/dataease/dataease/assets/61964761/7c45739f-b745-41f1-9e46-81be1d0ad4c4)

**Comment by xuwei-fit2cloud** [comment]
暂无支持计划。
