### ISSUE TITLE
[Feature] 辅助线的平均值能否支持格式调整？

### ISSUE THREAD

**Issue by Xyuncheng** [dataease/dataease#9970]
DataEase 版本:
1.18.18 & 2.6.1

**请描述您的需求或者改进建议.**
试过 v1 跟 v2 的版本，目前的辅助线求平均值后无法自定义调整，影响整体观感，希望能支持像字段中的数值格式调整的选项。
![image](https://github.com/dataease/dataease/assets/137035261/e6ec1ae1-7226-4b57-a6fd-9b2342a66dff)
![1717050002457](https://github.com/dataease/dataease/assets/137035261/6f60bc52-03e1-47fa-a0ae-be7ce3692686)

如上图所示，求出的平均值过长，希望能够优化。

**Comment by xuwei-fit2cloud** [comment]
可以在纵轴里调整数值格式。
![图片](https://github.com/dataease/dataease/assets/1892127/a77ad619-e421-45cb-9568-44744b69f046)
