### ISSUE TITLE
[Bug]数据大屏的公共链接通过手机打开会显示“资源不存在或已经被删除”

### ISSUE THREAD

**Issue by jstbw** [dataease/dataease#9971]
**DataEase 版本**
v2.6.1

**运行方式(安装包运行 or 源码运行 ?)**
安装包

**浏览器版本**

**Bug 描述**
数据大屏的公共链接通过手机打开会显示“资源不存在或已经被删除”，在web端是正常的。如果就是这么设计d的，不支持数据大屏移动端，提示应该友好点。
![3ff836d9591575f008232078fad2317](https://github.com/dataease/dataease/assets/66759501/44624250-19c2-4ece-a6b1-31198ddfb34a)

**Comment by BBchicken-9527** [comment]
感谢反馈，确实是有问题的，目前数据大屏是无法支持移动端的访问，我们优化一下此处的逻辑，非常抱歉给你带来使用不便；
