### ISSUE TITLE
[Feature] 报表配置过程中实现自动保存

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#9991]
DataEase 版本:
 2.7

**请描述您的需求或者改进建议.**
配置报表的过程中可能偶发浏览器崩溃，重新打开的时候之前配置的会丢失。
需要重新配置，体验很不好。

希望实现自动保存功能，通过定时或者修改后自动保存功能，避免修改丢失

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，v2.7版本会有优化，当异常退出时，再次进入会有相应的提示，根据提示操作便可以恢复。

**Comment by lillcol** [comment]
> 感谢您的反馈，v2.7版本会有优化，当异常退出时，再次进入会有相应的提示，根据提示操作便可以恢复。

好的 ，到时候我试试
