### ISSUE TITLE
[Feature] 建议仪表板的保存和发布分离

### ISSUE THREAD

**Issue by lillcol** [dataease/dataease#9992]
DataEase 版本:
2.7

**请描述您的需求或者改进建议.**

目前的操作是保存即发布，
有些场景在我不希望我的修改保存马上是用户可见的。
比如修改只完成部分、数据还待校验
我保存了修改，但是整体工作还没完成，此时用户不该看到最新的修改信息。

建议增加保存，发布机制。
用户只能看到发布版本的报表
保存的最新报表只有经过发布操作后用户才能看到

**Comment by yayanpei-fit2cloud** [comment]
感谢您的反馈，该需求已经在需求池中，近期的版本中暂时没有计划支持仪表板的发布和版本管理。
